### ISSUE TITLE
Crash in freerdp_certificate_data_get_subject during the "New host identification" prompt

### ISSUE THREAD

**Issue by grawity** [FreeRDP/FreeRDP#10002]
**Describe the bug**

Running `xfreerdp3 /v:HOSTNAME.example.com` results in a crash during certificate check, and then another crash within the crash-handler. Apparently, this is caused by an earlier cached certificate and not by the server's current certificate.

Both certificates are typical self-generated Windows RDP certificates (machine is in AD but there's no AD CA, because I broke that a few months ago).

**To Reproduce**

1. Have a previous (expired) certificate cached in `~/.config/freerdp/server/`.
2. Attempt to connect to the server, without any special options.

**Expected behavior**

It should ask me about the certificate change instead of crashing.

**Screenshots**

[Backtrace](https://github.com/FreeRDP/FreeRDP/files/14692881/20240321.111626.fk5gL8.txt)

**Application details**
* FreeRDP version (`xfreerdp /version`): `3.4.0` (Arch Linux [testing build](https://gitlab.archlinux.org/archlinux/packaging/packages/freerdp/-/blob/151da15e63fd71a320ffed867e07ea27cb39d5bf/PKGBUILD))
* Command line used: `xfreerdp3 /v:FOO.example.com`
* Output of `xfreerdp /buildconfig`: [20240321.113304.Jswz1H.txt](https://github.com/FreeRDP/FreeRDP/files/14692927/20240321.113304.Jswz1H.txt)
* OS version connecting to (server side): Windows 11

Cc: @dvzrv

**Comment by akallabeth** [comment]
@grawity the pull request #10003 will fix your crash, but it is caused by your `OpenSSL` configuration not allowing weak ciphers (yes, RDP uses weak ones, nothing we can do until MS changes that)

**Comment by grawity** [comment]
> but it is caused by your `OpenSSL` configuration not allowing weak ciphers (yes, RDP uses weak ones, nothing we can do until MS changes that)

Hmm, that doesn't sound right – I'm looking at the cached certificate with `certtool` and `openssl x509` and it seems to be a fairly typical 2048-bit RSA SHA256 certificate.

**Comment by grawity** [comment]
Actually, since you say "If a certificate can not be read", I just realized why it cannot be read – I input the hostname in mixed-case (`/v:FOO.bar.tld`) but the cached file is named all-lower-case (`foo.bar.tld_3389.pem`). If I try to connect using a lower-case hostname (`/v:foo.bar.tld`) it does not crash.

**Comment by akallabeth** [comment]
@grawity ok, checking.
