### ISSUE TITLE
xfreerdp command replaced with xfreerdp3 and its not working!

### ISSUE THREAD

**Issue by banafshehft** [FreeRDP/FreeRDP#10019]
**Describe the bug**

xfreerdp command is not exist any more but i have xfreerdp3 and its not working anyways. 

![Screenshot from 2024-03-25 15-27-50](https://github.com/FreeRDP/FreeRDP/assets/104374380/c8888859-debb-4900-b788-afc90f668d76)

i am using archlinux. and i faced this issue since last update.

**Comment by mcodax** [comment]
Not entirely clear to me from your comment, but have you tried using xfreerdp3 as the command instead of xfreerdp? I had the same problem when I updated my system a couple of days ago (also on Arch).

If you run:

`$ compgen -c | grep freerdp`

You should see all the available freerdp commands.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/discussions/10018
