### ISSUE TITLE
Some multimedia keys on the keyboard are not sent to the RDP server

### ISSUE THREAD

**Issue by sasha0552** [FreeRDP/FreeRDP#10029]
**Describe the bug**
FreeRDP tries to map X11 keycodes to RDP scancodes, but fails with certain media keys.

For example, when I press the `VK_BROWSER_REFRESH` (`XF86Refresh`) key, the following log appears in the console:
`[ERROR][com.freerdp.client.x11] - [xf_keyboard_send_key]: Unknown key with X keycode 0x08`

Note: The `VK_BROWSER_REFRESH` key exists in the RDP scancode list
https://github.com/FreeRDP/FreeRDP/blob/d864393a8a7ec1b54b0c89c8141b2b563e8249ec/include/freerdp/scancode.h#L222

A list of keys that don't work:
| rdp code | scancode | keysym                 |
|----------|----------|------------------------|
| `103`    | `181`    | `XF86Refresh`          |
| `104`    | `136`    | `XF86Stop`             |
| `109`    | `234`    | `XF86AudioMedia`       |
| `110`    | `156`    | `XF86Launch0`          |
| `111`    | `157`    | `XF86Launch1`          |

*(from https://github.com/neutrinolabs/xrdp/pull/3022)*

**To Reproduce**
Try pressing certain media keys (or, in my case, send the key programmatically with `xdotool key "XF86Refresh"`)

**Expected behavior**
FreeRDP sends a valid RDP scancode to the RDP server.

**Screenshots**
Not applicable.

**Application details**
* FreeRDP version (`xfreerdp /version`)
**This is FreeRDP version 3.4.0-3 (2-3.4.0-3)**
* Command line used
**xfreerdp3 /v:omitted /u:omitted /p:omitted**
* Output of `xfreerdp /buildconfig`
**Unnecessary**
* OS version connecting to (server side)
**ArchLinux, pinned to [2024-03-06](https://archive.archlinux.org/repos/2024/03/06/) + xrdp (PR https://github.com/neutrinolabs/xrdp/pull/3022) + Xvnc session**
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`
**Unnecessary**
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help
**[Tag 3.4.0](https://github.com/FreeRDP/FreeRDP/tree/3.4.0), [CMake parameters](https://gitlab.archlinux.org/archlinux/packaging/packages/freerdp/-/blob/main/PKGBUILD#L75), Compiler: gcc (GCC) 13.2.1 20230801**

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]
 **Linux**
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]
**ArchLinux, pinned to [2024-03-06](https://archive.archlinux.org/repos/2024/03/06/). FreeRDP is from [ArchLinux GitLab](https://gitlab.archlinux.org/archlinux/packaging/packages/freerdp/).**
 - Architecture: [amd64, arm]:
**amd64**

**Additional context**
Related: https://github.com/neutrinolabs/xrdp/pull/3022

**Comment by akallabeth** [comment]
@sasha0552 check `freerdp_keyboard_get_rdp_scancode_from_x11_keycode` there is a map `X11_KEYCODE_TO_VIRTUAL_SCANCODE` that should contain this mapping. 
it is populated in `freerdp_keyboard_init` so check which keys are mapped and which are not.
