### ISSUE TITLE
freerdp 3 is not able to use the gateway option

### ISSUE THREAD

**Issue by Levijd** [FreeRDP/FreeRDP#10023]
Using the /g option in freerdp 3 does not work and returns Unexpected keyword before attempting a connection:

```
$ xfreerdp3 /v:workstation.company.com /g:gateway.company.com /u:user /p:pass /d:domain
[8230:00002026] [ERROR][com.winpr.commandline] - [log_error]: Failed at index 2 [/g:gateway.company.com]: Unexpected keyword
```

The /g or /gateway option has always worked in previous versions of freerdp, but as of version 3 appears to not be recognized with any combination of sub-options, or any ordering of options.

**Comment by mcodax** [comment]
Exact same problem here (some additional parameters and in a different order, but same symptom):

```
$ xfreerdp3 /v:suddomain.domain.com /d:domain /u:username /p:pwd /gd:gatewaydomain /g:gatewayaddress /gu:gatewayuser /gp:gatewaypwd
[209489:00033251] [ERROR][com.winpr.commandline] - [log_error]: Failed at index 5 [/gd:gatewaydomain]: Unexpected keyword

```

I did notice the gateway parameter specification is now slightly different but couldn't make it work straight away:
```

    /gateway: g:<gateway>[:<port>],u:<user>,d:<domain>,p:<password>,
              usage-method:[direct|detect],access-token:<token>,type:[rpc|http[,
              no-websockets][,extauth-sspi-ntlm]|auto[,no-websockets][,
              extauth-sspi-ntlm]]|arm,url:<wss://url>,
              bearer:<oauth2-bearer-token>
```
I ended up downgrading back to 2.11.x, so any help would be appreciated.

**Comment by mcodax** [comment]
@Levijd took me a while to get it, but this works for me on 3.4.0:

```
$ xfreerdp3 /v:subdomain.domain.com /d:domain /u:username /p:pwd /gateway:g:gatewayaddress,u:gatewayuser,d:gatewaydomain,p:gatewaypwd
```
So I guess if /g:gateway.company.com is the only gateway parameter you're using on 2.x, you need to turn it into:

`/gateway:g:gateway.company.com`

**Comment by mcodax** [comment]
FYI, these probably need to be updated:

https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface

https://github.com/awakecoding/FreeRDP-Manuals/blob/master/User/FreeRDP-User-Manual.markdown (link via https://github.com/FreeRDP/FreeRDP/wiki/manuals)

**Comment by Levijd** [comment]
Ah you're correct. I guess I missed the change from /g to /gateway:g. Thanks for solving this!

Marking the issue closed since it's not a bug.

**Comment by akallabeth** [comment]
@Levijd @mcodax yes, docs need updating.
as for syntax, there is `-DWITH_FREERDP_DEPRECATED_COMMANDLINE=ON` to keep old syntax alive for now.
