### ISSUE TITLE
zsh: command not found: xfreerdp

### ISSUE THREAD

**Issue by rogue-agent** [FreeRDP/FreeRDP#10043]
I've checked a few pages of issues to see if there is something similar. Also active in IRC, but it is being quite slow today.

**Describe the bug**
Did the call handle change? I can't call xfreerdp anymore after updating my Arch system around 16:~~ UTC
I was told on IRC that Arch can install package version parallel, not sure what was meant by this. My Freerdp version is 2:3.4.0-5
I tried xfreerdp, xfreerdp2, xfreerdp-2, freerdp, and now finally xfreerdp3, please do not change call handles like this, I don't follow your feed and I'm completely unaware of new updates because to be honest, I have other things to care for.

**Application details**
* FreeRDP version (`xfreerdp-2:3.4.0-5`)
* zsh in kitty

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/discussions/10018

**Comment by 1010dvpt** [comment]
jfc!  Had to come here in order to solve my "xfreerdp not found" that has been working fine up until the other day.

Thanks for causing huge disrupts in workflows for people. -S
