### ISSUE TITLE
Can not use bottom of the screen with the mouse if monitor resolution differs

### ISSUE THREAD

**Issue by kungzlatan** [FreeRDP/FreeRDP#10071]
Have been fine untill i updated the newst version some days back

step to reproduce 

1 have 3 screens where 2 is 1080 and 1 1440 (this one is master screen)

2 connect to a windows machine with 

xfreerdp /multimon:force /monitors:0,1,3 /u:xxxxxxx /v:xxxxxxxxx

then on the 1440 screen i can not click with the mouse on anything below the lowest pixel of 1080p 

so for example my click on the start button or anything in task bar will not register. 

works fine on both 1080 screens

**Comment by akallabeth** [comment]
can not reproduce.
Got a 3 monitor setup here:
1. 1080p
2. 1600x900 (master)
3. 1080p or 1920x1200

in any constellation I can always click each corner (up, down) of each of the monitors.
closing until more data is added.
