### ISSUE TITLE
More compiler warnings

### ISSUE THREAD

**Issue by floppym** [FreeRDP/FreeRDP#10089]
Following on from https://github.com/FreeRDP/FreeRDP/issues/10085, I now get 2 warnings when building from master.
```
libfreerdp/core/orders.c:4018:33: warning: ‘free_cache_color_table_order’ called on pointer returned from a mismatched allocation function [-Wmismatched-dealloc]
winpr/libwinpr/utils/test/TestStream.c:132:9: warning: ‘Stream_Free’ called on unallocated object ‘staticStream’ [-Wfree-nonheap-object]
```
Full build log:
[build-log.txt](https://github.com/FreeRDP/FreeRDP/files/15014981/build-log.txt)

**Comment by akallabeth** [comment]
@floppym the `winpr/libwinpr/utils/test/TestStream.c:132:9: warning: ‘Stream_Free’ called on unallocated object ‘staticStream’ [-Wfree-nonheap-object]` is on purpose (just like written in the comment above the code)

I can´t get the `free_cache_color_table_order` warning though, neighter with `clang` not with `gcc`

**Comment by floppym** [comment]
I haven't looked at the code, so I was unaware of any comments. 🙂

I'll see if I can figure out what is triggering the other warning on my system.
