### ISSUE TITLE
stable-2.0 branch fails to build with GCC 14

### ISSUE THREAD

**Issue by david-geiger** [FreeRDP/FreeRDP#10091]
Hi,

On Mageia Cauldron freerdp 2.11.x fails to build with GCC 14 due to compiler error (-Wincompatible-pointer-types) like:

`/home/iurt/rpmbuild/BUILD/freerdp-2.11.6/libfreerdp/core/info.c: In function 'rdp_read_info_null_string':
/home/iurt/rpmbuild/BUILD/freerdp-2.11.6/libfreerdp/core/info.c:88:39: error: initialization of 'const WCHAR *' {aka 'const short unsigned int *'} from incompatible pointer type 'BYTE *' {aka 'unsigned char *'} [-Wincompatible-pointer-types]
   88 |                 const WCHAR* domain = Stream_Pointer(s);
      |                                       ^~~~~~~~~~~~~~
gmake[2]: *** [libfreerdp/CMakeFiles/freerdp.dir/build.make:863: libfreerdp/CMakeFiles/freerdp.dir/core/info.c.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....`

Attached full build log:
[build.x86_64.0.20240417141007.log](https://github.com/FreeRDP/FreeRDP/files/15022093/build.x86_64.0.20240417141007.log)

**Comment by akallabeth** [comment]
deactivate the warning for the build or provide a pull request please.
oldstable only gets security fix releases at this point in time.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/pull/10456
