### ISSUE TITLE
[sdl] Should /kbd:remap:KEY=VALUE work?

### ISSUE THREAD

**Issue by m1027** [FreeRDP/FreeRDP#10096]
I see no effect of using `/kbd:remap:KEY=VALUE` in the `sdl-freerdp`client.

Shouldn't this work?

My test setup:
- linux / amd64 / pure wayland / no X
- freerdp-3.4.0 or freerdp-3.5.0
- changing keys for the number keys "1" and "2" like this `sdl-freerdp -kbd:remap:2=3 -v:HOST -u:USER`
- in the remote machine, opened editor and typed "1", "2", "3"

Expected result "2", "2", "3".

Actual result: "1", "2", "3".

FYI: With freerdp-2.x we had `remap` working but in freerdp-3.x wayland users are said to use the sdl client now.

Thanks for any pointers.

**Comment by akallabeth** [comment]
this is actually not implemented yet for sdl-client, put it on the list for next release.

**Comment by m1027** [comment]
3.6.2 tested against Window Server 2016. It...works!! Thank you so much
