### ISSUE TITLE
Multiple monitors acts weirdly under Plasma 6 Wayland

### ISSUE THREAD

**Issue by MakwaWes** [FreeRDP/FreeRDP#10098]
**Describe the bug**
With a dual monitors setup, connecting to a Windows 10 client in fullscreen displays correctly on the monitor where the mouse is active and the second monitor flickers and shows the actual dual windows scaled to the single monitor. Hovering the mouse on the problematic monitor makes the issue alternate between the monitors.

Note that this issue doesn't happen under a Plasma 6 X11 session. Also doesn't happen under a Gnome Wayland session.

**To Reproduce**
Under a Plasma 6 Wayland session, connect to a Windows client with the multimon argument and more than 1 monitor.

**Expected behavior**
Expect to see the Windows desktop scaled correctly on all monitors like under a X11 session.

**Screenshots**
Below is a video since screenshots are not showing the issue.

**Application details**
* FreeRDP version 3.4.0 (n/a)
* xfreerdp3 /d:xx.xx /u:xxxxx /p:xxxx /cert:ignore /v:127.0.0.1 /audio-mode:2 -clipboard /multimon /prevent-session-lock
* Output of `xfreerdp /buildconfig`
```
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_BINARY_VERSIONING=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_ICU=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=ON WITH_PCSC=ON WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SDL_IMAGE_DIALOGS=OFF WITH_SDL_LINK_SHARED=ON WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=ON WITH_SYSTEMD=ON WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=ON WITH_WEBVIEW_QT=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          None
CFLAGS:              -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/freerdp/src=/usr/src/debug/freerdp -flto=auto -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer
Compiler:            GNU, 13.2.1
Target architecture: x64
```
* Windows 10

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Arch Linux
 - Architecture: amd64

https://github.com/FreeRDP/FreeRDP/assets/12200405/9255f45e-fceb-4d9c-b5b3-a684cea3e91d

PS: Found a reddit with kind of the same issue : https://www.reddit.com/r/Fedora/comments/16ol9ln/rdp_multiple_monitors_on_wayland/

**Comment by akallabeth** [comment]
well, sounds like a KDE/plasma issue, keeping it open as reference for now.

**Comment by akallabeth** [comment]
> Does this also happen when using `sdl-freerdp ...` instead of `xfreerdp ...`? xfreerdp isn't quite suited for running on Wayland.

@danir-de still using `xfreerdp` quite heavily on `wayland` (`XWayland`) and don´t see a problem ;)
even draws more smooth than on original `X11` settings.
but only regularily use dual monitor setups. (there have been quite a number of issues with kde and xfreerp/multimonitor a few years back, but they solved it in kwin as far as I remember)
maybe the same issue again with `XWayland` ?

**Comment by gtiborcz** [comment]
Same issue for me.
Arch linux up to date.
KDE plasma 6.1.5
Session: wayland
The problem exist : xfreerdp and xfreerdp3

**Comment by jdarmetzki** [comment]
I cannot confirm at the moment. I had to switch back to windows for working now since i cannot get freerdp to connect to my work-pc and i am currently spending my freerdp time-budget for finding the cause for this problem and why sdl-freerdp with wayland worked exactly once for me and not once since then.

**Comment by gtiborcz** [comment]
The problem still exists.  (Arch Linux up to date)

**Comment by akallabeth** [comment]
unless someone can point out why this is our bug I consider this a plasma bug as the same works well on other window managers / desktop environments.
so please stop  the me too things (does not really help) and answer that question ;)

**Comment by gtiborcz** [comment]
@akallabeth 


I don't know what is causing the problem. You are the programmers. I'll give you feedback to our experience if it gets you closer to the solution. Of course, if the solution still doesn't belong to you, then you say pass :)
(I post to KDE developing group as well.)
New news:
Until now, I used an I-tech dock for my laptop connected to USB-C DP alt mode. Linux identified both the DP and HDMI outputs as Displayport. (DP-1, DP-2..etc)
I changed the dock (Lenovo 40AF). Connection is the same USB-C DP alt mode  The new dock identifies the 2 monitors as DVI ports. This works perfectly.


By the way , It is wrong again , If I connect 1 monitor directly to the laptop's HDMI port.


Summary:
DVI port(s) thru dock is working.
DP, HDMI ports:  wrong.




I really don't know who this belongs to. Unfortunately, the KDE team is not responding, so I can only hope that you put pressure on them and you can explain it to them more clearly and professionally,  if it's not freerdp fault.


Thank you

**Comment by chpoit** [comment]
I can confirm this is also an issue for me. On the "second" display, the first one gets mirrored instead of being rendered properly

**Comment by akallabeth** [comment]
did find a bug in kde: https://bugs.kde.org/show_bug.cgi?id=506097
not sure it is the one you experience, but hope it is. (then it can be resolved when they fix that)

**Comment by chpoit** [comment]
> did find a bug in kde: https://bugs.kde.org/show_bug.cgi?id=506097 not sure it is the one you experience, but hope it is. (then it can be resolved when they fix that)

I don't think it's the same issue, when I switch back to x11 instead of wayland it starts working properly again. The behavior I experience is very similar to what is shown in the OP's video, when the mouse triggers an update on "display 0", the second display gets overriden by "display 0".

**Comment by akallabeth** [comment]
> I don't think it's the same issue, when I switch back to x11 instead of wayland it starts working properly again. The behavior I experience is very similar to what is shown in the OP's video, when the mouse triggers an update on "display 0", the second display gets overriden by "display 0".

that would suggest a bug in `kde/plasma` as well.
`xfreerdp` always does the same (it is a `X11` application after all)

can you reproduce this with other sessions? (`xfce`, `gnome`, ... ?)

this is why I told above to stop posting *me too* and instead add some data from affected systems (I can not reproduce all the possible configurations every user around the world has without some detailed information - the provided data is not nearly enough to reproduce)

**Comment by lutravox** [comment]
Adding KWIN_DRM_NO_DIRECT_SCANOUT=1 to /etc/environment seems to fix this issue.

**Comment by c9806961** [comment]
I had this exact same issue with my second screen mirrored and the above fix fixed it for me (KWIN_DRM_NO_DIRECT_SCANOUT=1).
Applying the fix did however stop the floatbar from displaying now.
