### ISSUE TITLE
Debian Repository for Stable Build

### ISSUE THREAD

**Issue by SnejPro** [FreeRDP/FreeRDP#10127]
**Is your feature request related to a problem? Please describe.**
I have a few ThinClients using xFreeRDP, but Debian/Ubuntu repositories deliver a quite old version of FreeRDP.

**Describe the solution you'd like**
A Debian stable repository (like FreeRDP-nightly)

**Describe alternatives you've considered**
- Self Building: Is not very trivial for someone who is not that experienced with building packages; No automatic update
- PreBuilts as deb
- Complete build script for a specific debian version

**Additional context**
Thank you for your great work. It helps us to keep Windows computers at the necessary minimum.

**Comment by akallabeth** [comment]
we have a [flatpak](https://flathub.org/apps/com.freerdp.FreeRDP) but no interest in maintaining more binary builds than necessary. (it takes time to keep them up to date and running - and time is already short ;))

**Comment by SnejPro** [comment]
> we have a [flatpak](https://flathub.org/apps/com.freerdp.FreeRDP) but no interest in maintaining more binary builds than necessary. (it takes time to keep them up to date and running - and time is already short ;))

I tried flatpak, but how can i start the xfreerdp client with flatpak? When i run `flatpak run com.freerdp.FreeRDP` it starts the sdl-client.

**Comment by akallabeth** [comment]
@SnejPro `flatpak run --command=xfreerdp com.freerdp.FreeRDP` (you might need to adjust permissions with `Flatseal` to allow `X11` to work with it)
