### ISSUE TITLE
Screen flickers on random squares after update to FreeRDP3 (3.5.1) Not problem with FreeRDP 2.11.5// X session, KDE

### ISSUE THREAD

**Issue by danielbgto** [FreeRDP/FreeRDP#10136]
Hi!
Screen is flickering very similar to the way described in #8568. There is video there and I see the same, only not so intensive.
My platform is Fedora 39 KDE on X11. It happens when I decided to go for version 3.5.1 as version 3 is default in Fedora 40 which was released yesterday. I got the problem with nla described in #10130 and I was lucky to see that the fix commit is already in Master branch. I have recompile the master branch code with the F40 default config. Then RDP started working but... the flickering appears. Downgrading to FreeRDP 2 solve the problem. I'm using the distro package version 2.11.5 as for today. No problem at all with it, rock solid.
In this context - I guess I'm missing some default parameter which was changed from v2. to v.3. Or it's a bug.

The desired machine is Windows Server 2019 S. My command line is pretty standard (and probably outdated, but it works fine with v.2):

xfreerdp /v:XXXXX.XXX.XXX.XXX /d:XXXX.XX /u:XXXXX /p:XXXXX  +clipboard /dynamic-resolution -wallpaper /network:auto /w:1920 /h:1035 /t:XXXXXXX +heartbeat  /drive:share,/home/XXXX/Documents/share  +fonts /microphone:format:1 /sound 
 
Thanks!

**Comment by akallabeth** [comment]
hi,
can you specify more precisely what you mean with flicker?

**Comment by danielbgto** [comment]
Hi! Sure! I mean similar like that screen cast from the fist post of #8568. Simply the areas with black squares are not so much as in that video but practically is the same. 

![image](https://github.com/FreeRDP/FreeRDP/assets/5525957/8f0e68a3-f165-4cc4-9c12-1e76dae5c0b8)

**Comment by akallabeth** [comment]
@danielbgto
1. the issue you link to is a different client and unrelated (completely)
1. what do you want to show with the screenshot?

**Comment by danielbgto** [comment]
1. Yes, you are right but I see the same in my system as well.
2. I want to show what I'm referring to. The RDP screen with big black squares. This is what I;m pointing to because this is what is the problem. I guess this is main symptom.

**Comment by akallabeth** [comment]
ok, did not realize that is your `xfreerdp` window?
can you post the `buildconfig` ? does seem strange, can´t reproduce here , also on fedora (but gnome)

**Comment by akallabeth** [comment]
@danielbgto ok, can you check with `sdl-freerdp` as well?
we did not change much in how `xfreerdp` is drawing stuff and protocol decoding issues should be visible regardless of client and windowing system.

**Comment by danielbgto** [comment]
Yes! It's working normal! 
The only one "NO GO" for me with sdl is the lack of clipboard and file transfer. For my job this is a must.

**Comment by akallabeth** [comment]
@danielbgto ok, that is then really strange, as the drawing routines in `xfreerdp` did not change since 2.0 and I have not seen issues like yours at all up to now?
as `sdl-freerdp` works for you that means the library is not at fault but something client specific.

can you try this in a different environment, maybe it is something specific to `KDE`?
or can you try it in a wayland session maybe? (trying to find out how to reproduce here, otherwise it is hard to debug/fix)

**Comment by danielbgto** [comment]
Yes, you are right. Looks like a KDE specific. I fired a VM with F40 KDE. Same behavior. Then installed on the same VM Cinnamon desktop and tried it via Cinnamon Wayland session - then no issue.
So...good news for you - this is KDE related problem. Bad news for me - I have no idea what could be problem. :)
Thanks for your help!

**Comment by danielbgto** [comment]
I found the issue. Wrong scaling - It was 110% which is not ok for X11.  KDE shows a clear message. 
It's interesting that FreeRDP 2 was able to overcome it, FreeRDP 3 not. V2 simply rocks! :)

![image](https://github.com/FreeRDP/FreeRDP/assets/5525957/e44ae4d1-5837-4645-8eb7-5f4002294ec1)

**Comment by akallabeth** [comment]
ah, ok, that is an interesting find. then it was just pure luck that `xfreerdp2` did not show these and `xfreerdp3` did.
anyway, good the causing factor is now known.
