### ISSUE TITLE
Glyph cache cannot show any characters in login window

### ISSUE THREAD

**Issue by RolKau** [FreeRDP/FreeRDP#10154]
If I connect using the options given by the command-line:
```
xfreerdp /cache:bitmap:on,offscreen:on,glyph:on /f /gfx:avc444,progressive:on /network:broadband
```
I get a login window where _some_ of the glyphs are shown as black squares.

Remote end: xrdp v0.9.23.1, with xorgxrdp v0.2.19, on Ubuntu 20.04
Local end: xfreerdp v3.5.1, compiled with libh264 v2.4.1, on Ubuntu 20.04

The 2.x series of xfreerdp were able to show the characters in the login window (admittedly using RFX codec instead of AVC444); this regression started with the 3.x series.

If I use `/cache:glyph:off`, I am unable to connect (even with `/relax-order-checks`).

![glyph-10154](https://github.com/FreeRDP/FreeRDP/assets/826091/4a25e12a-2eeb-4d5e-9221-30cb6da88e85)

**Comment by akallabeth** [comment]
just don´t use any arguments at all, that should be fine. if not try to add `/rfx` to force the RFX mode.

note: with freerdp 2 you do not use the ancient gdi mode but RFX, with FreeRDP 3 you do not use GFX (xrdp does not support that yet or not in the version you use).
that cache setting is only relevant for the ancient modes that are used as fallbacks. (and was buggy in xrdp and freerdp for a very long time)

**Comment by RolKau** [comment]
@akallabeth 
> that cache setting is only relevant for the ancient modes that are used as fallbacks

You are correct in that the `/cache` parameter was something I had grand-fathered in from previous versions and that stuck with me after the upgrade. If I remove it, the glyphs in the login dialog renders correctly again.

However, if I omit it, the connection gets noticably more sluggish, leaving me a little confused about what would truly be the best connection parameters. I was under the impression that AVC444 > RFX > GDI. But running with `/gdi:sw -rfx` (which should be awful, but it's not) and `+rfx /gfx:RFX` both seems to give better results than `/gfx:AVC444`. Is this due to xrdp on the remote side? (I don't have any Windows server to test against for the moment).

> with freerdp 2 you do not use the ancient gdi mode but RFX, with FreeRDP 3 you do not use GFX

I cannot parse if you meant that normatively or descriptively. Is there any Wiki-page that describe how to infer the best connection parameters in one's setup?

**Comment by akallabeth** [comment]
@RolKau do not use any parameters at all for these.
you only end up in unusable or slow connection settings (or somewhere in between)

the default (autodetection with every option available) is usually the best and if you like something else it is better to configure that on the server side as there the decision is made which mode is actually used. (the client just tells 'I support that and that' and the server then 'Ok, I take xxx')
