### ISSUE TITLE
does this support raspberry pi devices?

### ISSUE THREAD

**Issue by dnb02** [FreeRDP/FreeRDP#10150]
i have a raspberry pi zero w, can i connect to that device using freerdp?

**Comment by akallabeth** [comment]
if you have a `RDP` server installed (`gnome-remote-desktop`, `ogon` or `xrdp`) and it is running yes.
or do you mean you want to connect *from* your raspberry to some windows/other os?

**Comment by dnb02** [comment]
ok ty
