### ISSUE TITLE
FreeRDP Display Issues on Ubuntu 24.04 LTS with Windows 10 VM

### ISSUE THREAD

**Issue by gitspeaks** [FreeRDP/FreeRDP#10156]
Hello,

I am experiencing issues with FreeRDP where the display output does not fit the entire window. 

**Environment:**

- Host OS: Ubuntu 24.04 LTS on a MacBook Pro 2012 Retina (15”).
- Virtualization: qemu-kvm with virt-manager.
- Guest OS: Windows 10 (22H2) with Fedora virtio drivers version 0.1.240 for display/nic/storage/pci.
  Windows 10 Display Settings: 2560x1600 resolution with 200% text scale.
- Networking: Bridge networking between host and guest.

**Issue Description:**

1. After installing FreeRDP version 3.5.1 (release date 2024-04-22) from Flatpak, the Windows desktop does not extend to cover the entire window when initiating an RDP session with the command:

```flatpak run com.freerdp.FreeRDP /u:xxx /p:xxx /v:192.168.1.19 /floatbar:sticky:on,default:visible```

Attempting flags such as /size, /dynamic-resolution, and /smart-sizing does not alter the outcome.

Here is a screenshot:

![FreeRDP-3-5-1-window](https://github.com/FreeRDP/FreeRDP/assets/37540903/33736fac-73bf-456b-87d5-1d66aea98372)

2. Using the /f flag results in a full-screen session, but the RDP session's float bar is not visible. 

![FreeRDP-3-5-1-full-screen](https://github.com/FreeRDP/FreeRDP/assets/37540903/602ed3d7-97c2-4ff8-968f-f17ff285220f)

**Comparison with virt-manager GTK client running in full-screen**

![GTK-full-screen](https://github.com/FreeRDP/FreeRDP/assets/37540903/41aa192c-bf4a-438d-868b-b7d37a3327b7)

**Comparison with freerdp2-x11 (Version 2.11.5)**

- Connection command:

 ``` xfreerdp /u:xxx /p:xxx /v:192.168.1.19 /f /floatbar:sticky:on,default:visible```
  
- Issues noted:

  <strike>1. Full-screen mode does not honor the configured text scaling. </strike>
  <strike>2. Window mode does not maintain the desktop's aspect ratio, causing stretched and blurred text. </strike>
  Solved by adding the flags:
  ``` /scale:180 /scale-desktop:200 /dynamic-resolution /workarea```

I attempted to capture a screenshot of a full-screen FreeRDP2-x11 session to show how the display quality compare with the GTK client

Here's what I did:

1. I initiated the FreeRDP2-x11 session with the +clipboard option 

``` xfreerdp /cert:ignore /u:xxx /p:xxx /v:192.168.1.19 /f /floatbar:sticky:on,default:visible +clipboard ```

2. I created a shortcut on the Windows remote desktop to quickly access the "Snip & Sketch" tool. The shortcut was set up with the command 'explorer ms-screenclip:' to execute Snip & Sketch directly.

5. Upon activating Snip & Sketch via the shortcut and selecting the 'Full Screen Snip' option to take a screenshot of the entire session, the FreeRDP session was abruptly terminated with the following error:

```
[12:31:19:521] [18880:18881] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[12:31:19:521] [18880:18881] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[12:31:19:595] [18880:18881] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[12:31:19:595] [18880:18881] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  216 ()
  Minor opcode of failed request:  0
  Serial number of failed request:  5972
  Current serial number in output stream:  5973 
```
Note this does not happen with version 3.5.1
 
I appreciate any guidance on how to resolve these issues. 

Thanks in advance,

Itai

**Comment by akallabeth** [comment]
@gitspeaks well, you compare `sdl-freerdp` against `xfreerdp`
1. the bugs with `sdl-freerdp` should be gone with `/dynamic-resolution` and a manual window resize. (I think that is a `SDL` bug but not sure) see https://github.com/FreeRDP/FreeRDP/issues/9074 for a (incomplete) overview of things to fix
2. the issue you see there is a bug in `X11` not much we can fix there.

**Comment by akallabeth** [comment]
@gitspeaks check the other issues in the referenced one, there is already a bug for this.

**Comment by gitspeaks** [comment]
@akallabeth The float bar issue is indeed documented in https://github.com/FreeRDP/FreeRDP/issues/9457, however, I couldn't find an issue addressing the most critical problem: the desktop not extending to cover the entire window as shown in the first screenshot above.
