### ISSUE TITLE
Nightly builds segfaults on Ubuntu 22.04.4

### ISSUE THREAD

**Issue by nyaalex** [FreeRDP/FreeRDP#10163]
**Describe the bug**
The prebuilt binary for Ubuntu 22.04.4 fails with the following error:
`==72721==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.`

Using `LD_PRELOAD` instead segfaults
```
$ LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.6.0.0 sdl-freerdp3
Segmentation fault (core dumped)
```
Here are the specific versions for `libasan6` and `freerdp-nightly`:
```
$ apt info libasan6
Package: libasan6
Version: 11.4.0-1ubuntu1~22.04
[...]

$ apt info freerdp-nightly
Package: freerdp-nightly
Version: 3.0.0+0~20240427014826.1529~1.gbpef8363
[...]

$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy

$ ldd $(which sdl-freerdp3) | grep asan
        libasan.so.6 => /lib/x86_64-linux-gnu/libasan.so.6 (0x00007f0ce8800000)
```

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Ubuntu 22.04.4
 - Architecture: amd64

**Comment by akallabeth** [comment]
ok, just tried on my `jammy` vm and it works nicely. (setup with default ubuntu/gnome env)

sounds like you have something in your `LD_PRELOAD` or `PATH` settings changed from default?

**Comment by nyaalex** [comment]
Hmm. I love errors on my end cos now it's on me to fix it.

**Comment by akallabeth** [comment]
sorry for the bad news.
if you find out what exactly it is, maybe give us a ping (we can add it to the `FAQ` or fix it if it turns out it is our fault)

**Comment by nyaalex** [comment]
Okay I managed to fix it. Turns out when you install Citrix ICA it adds a random library called "App Protection" to `/etc/ld.so.preload` which has apparently been breaking a bunch of other stuff on my host too... I just removed it.

I feel like this is too niche to put in the FAQ, if someone else has this issue they can find it through a google search, this is on me for not checking `/etc/ld.so.preload` first before raising an issue :pensive:
