### ISSUE TITLE
Card Reader/Writer Redirection as "low-level" USB device is not working

### ISSUE THREAD

**Issue by outofsight** [FreeRDP/FreeRDP#10167]
I'm trying to redirect a HID OmniKey 5021 CL card reader via freerdp to a remote Windows 11 Pro desktop. It's not needed for logon to Windows but inside another Windows application.

From a Windows 7 desktop, with `mstsc`, I can redirect the device as a "high level" SmartCard and the Windows app can read and program the card successfully.

From the Linux-based distro (ThinStation) I can't do the same because of missing Linux drivers. So I'm trying to use the "new RemoteFX way", i.e. redirect the device with `/usb:id:076b:5340` and install the drivers in the remote.

Windows Device Manager apparently show the device with no issue, load the drivers, and starts the Smart Card Service, but the HID Global Omnikey Workbench diagnostic tool does'nt show the device and the windows app can't open the reader.

The only error I can see is a "PDU_TYPE_DATA" not properly parsed. Not even sure if it's related.

Any help would be appreciated.

Command line used: `/v:... /u:... /p:... /usb:id:076b:5340`
System I connect to: Windows 11 Pro
freerdp version (e.g. xfreerdp --version) or package version or git commit
Operating System: Linux ThinStation x64

FreeRDP version and build config:
![image](https://github.com/FreeRDP/FreeRDP/assets/12085715/e1d279e7-300f-4b4e-b8c7-8a918a8f16be)

Command Line and logs:
![image](https://github.com/FreeRDP/FreeRDP/assets/12085715/6c537dff-7575-43d8-837a-f38de3d3f7d3)

Windows Device Manger:
![image](https://github.com/FreeRDP/FreeRDP/assets/12085715/9e14243a-98c9-4c95-84b7-4f611d7f4cf8)

HID Global OmniKey Workbench:
![image](https://github.com/FreeRDP/FreeRDP/assets/12085715/364f7a5c-c25d-45a8-a8f1-557a73a02a19)

**Comment by akallabeth** [comment]
can not be redirected this way, use `/smartcard`

**Comment by outofsight** [comment]
As I wrote, /smartcard doesn't work

**Comment by hardening** [comment]
Perhaps you can try installing the HID pcsc drivers on your linux host...

**Comment by akallabeth** [comment]
@outofsight then try if that works with `mstsc` first, as that specific kind of redirection is not available for all device types. we can not support if the server does not. (I doubt you well be successful ;))

**Comment by outofsight** [comment]
> Perhaps you can try installing the HID pcsc drivers on your linux host...

5021 CL has not drivers for Linux on HID Global site
product with drivers have drivers only for 2 common distro

**Comment by outofsight** [comment]
> @outofsight then try if that works with `mstsc` first, as that specific kind of redirection is not available for all device types. we can not support if the server does not. (I doubt you well be successful ;))

According to MS documentation, my understanding is that "new", "RemoteFX", USB redirection, where drivers are installed in the remote windows desktop and usb device is redirected at a lower level, should be the preferred easy way. The fact that the reader is present in device manager is not a proof of the fact is recognized? I can even see a Smart Card when the Smart Card is close to the reader.

I have a machine with three USB device, two of wich doesn't have drivers for Linux; the third is a serial (Prolific 2303) but is not working when redirected as high level serial port. I think the RemoteFX USB redirection is the only way in situation like this.

Under Windows with mstsc, I can't see any device in the list of "other" USB device, but this doens't prevent to successfully redirect via /usb:... two USB printers and an USB webcam.

**Comment by akallabeth** [comment]
@outofsight well, it means there is something accepted server side.
but many devices have constraints on timing which you will never meet using this kind of redirection.

anyway, without a proper debug/trace log not much can be said here (and please no screenshots ;))

anyway, we have such smartcard readers here and they work under linux, you sure that you can´t redirect them? the low level USB redirection is just a fallback in case everything else fails (high bandwidth usage, prone to timing issues, ...)

**Comment by hardening** [comment]
> > Perhaps you can try installing the HID pcsc drivers on your linux host...
> 
> 5021 CL has not drivers for Linux on HID Global site product with drivers have drivers only for 2 common distro

Try unpacking the driver in the ZIP in pcsc's drivers directory. Even if the distro is not officially supported,  that should work.
