### ISSUE TITLE
How to implement USB device redirection in wfreerdp?

### ISSUE THREAD

**Issue by adream100** [FreeRDP/FreeRDP#10162]
I'm wondering if the latest version v2.11.7, wfreerdp (windows client version of freerdp), has implemented USB device redirection?

I have a USB Camera, two PCS, one is Server, one is Client, OS are the latest Win10 22H2.
This USB Camera redirection can be easily implemented through the mstsc that comes with Windows.

I don't know if USB Camera redirection is possible with wfreerdp. wfreerdp is compiled with the libusb 1.0.27 library added.
If so, how should the parameters be constructed? I use the USB TreeView to see the PID and VID of the USB device. But it never worked.
I'm confused, please help.
![p1](https://github.com/FreeRDP/FreeRDP/assets/153361306/19c4c99b-53ea-42d7-b64a-a5199d7b1dad)
![p2](https://github.com/FreeRDP/FreeRDP/assets/153361306/b31eaf31-48b7-4877-8cea-318208330d03)

**Comment by akallabeth** [comment]
never tried the thing under windows, your mileage may vary.
in theory it could work, but I don´t know if libusb can do all the stuff under windows like under linux (there is at least additional configuration work required that nobody did yet nor document, maybe libusb wiki can help there)
