### ISSUE TITLE
Wiki Documentation update needed for CLI command options listing

### ISSUE THREAD

**Issue by bmullan** [FreeRDP/FreeRDP#10173]
The freerdp CLI Options listed on..."

>**_[https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface](https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface)_**

*Must be quite outdated as* ***it does not list/describe many CLI options*** *listed by executing*:

>**$ xfreerdp3 --help**

*Just a couple examples.*
The **_[CommandLineInterface pages](https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface)_** is *completely missing these entirely*:   
   
```
 /gfx[: [[progressive[:on|off]|RFX[:on|off]|AVC420[:on|off]AVC444[:on|off]],
           mask:<value>,small-cache[:on|off],thin-client[:on|off],progressive[
           :on|off]]]                 RDP8 graphics pipeline
    /gfx-h264[: [[AVC420|AVC444],mask:<value>]]
                                      [DEPRECATED, use /gfx:avc420] RDP8.1 
                                      graphics pipeline using H264 codec
    +gfx-progressive                  Enable [DEPRECATED, use /gfx:progressive] 
                                      RDP8 graphics pipeline using progressive 
                                      codec
    -gfx-small-cache                  Disable [DEPRECATED, use 
                                      /gfx:small-cache] RDP8 graphics pipeline 
                                      using small cache mode
    +gfx-thin-client                  Enable [DEPRECATED, use /gfx:thin-client] 
                                      RDP8 graphics pipeline using thin client 
                                      mode
```
   
`+home-drive             Enable Redirect user home as share   
`

**Comment by akallabeth** [comment]
@bmullan yes, best only rely on the docs directly from the binary.
the wiki is hopelessly outdated in some areas and I don´t have the time to  update all of it.

accepting pull requests / issuse with `git bundles` for improvement, but had to disable direct editing due to vandalism.
