### ISSUE TITLE
Black Screen?

### ISSUE THREAD

**Issue by mdavidjohnson** [FreeRDP/FreeRDP#10179]
Probably NOT a bug, but I'm experiencing difficulty trying to use FreeRDP.

I have Debian 12 (Bookworm) running on my 10.0.0.93 server at home. I did "sudo apt-get install freerdp2-x11" and "sudo apt-get install freerdp2-shadow-x11".

Then I started the RDP server with "sudo freerdp-shadow-cli /bind-address:10.0.0.93 /sec:rdp /may-view /may-interact -auth". It responded "Listening on [10.0.0.93]:3389".

Then I went to my Windows 11 desktop (in the same room, at 10.0.0.100), started Windows' RDP and connected to "10.0.0.93:3389". It connected right away, but the screen was (and remained) entirely black.

Back on my Debian machine, the terminal was continuously reporting "[ERROR][com.freerdp.server.shadow.x11] - X11 error: BadMatch (invalid parameter attributes) Error code: 8, request code: 49, minor code: 0" over and over.

**Comment by akallabeth** [comment]
1. why do you use `sudo`?
2. is your `root` account set up for proper `X11`?

**Comment by mdavidjohnson** [comment]
Thank you -

Does using sudo make some sort of difference I'm missing? I tried running the command without sudo and it seemed to work exactly the same with no difference either way.

I'm not sure I understand what you mean about my root account being set up for proper x11. I'm not a company; just an at-home user. The root account and my sudoers account are the only two accounts on the machine and they both run graphics in exactly the same way.

Why is /sec:rdp highly discouraged? I'm trying to access the machine from my Windows 11 desktop which is using RDP, so I just sort-of-naturally assumed /sec:rdp would be the way to go. BTW, /sec:tls results in the same black screen as does /sec:rdp and /sec:nla doesn't even allow the Windows machine to connect, but instead throws a long line of "authorization errors" and other similarly offended missives. What is a SAM file?

I'm not concerned at all about security: I'm sitting behind a nice, high firewall on a completely isolated 10.0.0.1 gateway. All I'm trying to do is to avoid having to have two keyboards and two mice on the same desk. If possible, I'd also like to be able to get that accomplished without having to read 37 different man-pages.

Can you point me at anything that will help?

**Comment by akallabeth** [comment]
a huge one, it will run the thing as different user (e.g `root`) and some permissions are different, even preventing further use as normal user.

**Comment by akallabeth** [comment]
and `/sec:rdp` is an outdated security mechanism dating back to windows NT days that is not really secure (some custom `TLS` like encryption but not the real thing)

**Comment by akallabeth** [comment]
as for a nice and easy thing, did you try `gnome-remote-desktop`? that uses `FreeRDP` as backend so you can just connect to your system

**Comment by mdavidjohnson** [comment]
Thank you indeed!

gnome-remote-desktop did the trick perfectly!
