### ISSUE TITLE
3.5.1 build fails with fPIC linker error

### ISSUE THREAD

**Issue by blapalp** [FreeRDP/FreeRDP#10189]
Hi,

first off, I  have to wonder about your lax attitude here. 
This bug was closed without so much as a snarky remark by akallabeth.

I suggest you fix this asap, as the build currently fails with freerdp 3.5.1 and gstreamer 1.24.3 due to your referring to a static gstreamer lib built without PIC.
You either have to coordinate with gstreamer or provide your own compatible version of libswscale!

why is the build configured to link a .so to a gstreamer .a which might or might not have fPIC enabled?
Debian 12, gstreamer 1.24.3, freerdp 3.5.1

24.96 [ 77%] Linking C shared library libfreerdp3.so
47.62 /usr/bin/ld: /opt/gst/lib64/libswscale.a(libswscale_x86_swscale.c.o): warning: relocation against ff_M24B' in read-only section .text'
47.69 /usr/bin/ld: /opt/gst/lib64/libswscale.a(libswscale_x86_swscale.c.o): relocation R_X86_64_PC32 against symbol `ff_M24A' can not be used when making a shared object; recompile with -fPIC
47.69 /usr/bin/ld: final link failed: bad value
47.73 collect2: error: ld returned 1 exit status
47.74 make[2]: *** [libfreerdp/CMakeFiles/freerdp.dir/build.make:2857: libfreerdp/libfreerdp3.so.3.5.1] Error 1
47.74 make[1]: *** [CMakeFiles/Makefile2:2836: libfreerdp/CMakeFiles/freerdp.dir/all] Error 2
47.75 make: *** [Makefile:156: all] Error 2

**Comment by akallabeth** [comment]
well, this is your issue and you still fail to provide information that might help us to find out what you did wrong.

**Comment by akallabeth** [comment]
duplicate https://github.com/FreeRDP/FreeRDP/issues/10188
