### ISSUE TITLE
Build fails with trying to link shared lib to static gstreamer lib (fPIC)

### ISSUE THREAD

**Issue by blapalp** [FreeRDP/FreeRDP#10188]
Hi,

why is the build configured to link a .so to a gstreamer .a which might or might not have fPIC enabled? 
Debian 12, gstreamer 1.24.3, freerdp 3.5.1

24.96 [ 77%] Linking C shared library libfreerdp3.so
47.62 /usr/bin/ld: /opt/gst/lib64/libswscale.a(libswscale_x86_swscale.c.o): warning: relocation against `ff_M24B' in read-only section `.text'
47.69 /usr/bin/ld: /opt/gst/lib64/libswscale.a(libswscale_x86_swscale.c.o): relocation R_X86_64_PC32 against symbol `ff_M24A' can not be used when making a shared object; recompile with -fPIC
47.69 /usr/bin/ld: final link failed: bad value
47.73 collect2: error: ld returned 1 exit status
47.74 make[2]: *** [libfreerdp/CMakeFiles/freerdp.dir/build.make:2857: libfreerdp/libfreerdp3.so.3.5.1] Error 1
47.74 make[1]: *** [CMakeFiles/Makefile2:2836: libfreerdp/CMakeFiles/freerdp.dir/all] Error 2
47.75 make: *** [Makefile:156: all] Error 2

**Comment by akallabeth** [comment]
because you configured it that way?
please some details, or nobody can help ;)
