### ISSUE TITLE
How to start Windows applications form Linux short cut?(Or does FreeRDP have this feature?)

### ISSUE THREAD

**Issue by wuz1run** [FreeRDP/FreeRDP#10190]
How can I launch a Windows application from a shared folder containing shortcuts, accessible from both Windows and Linux? I'm aware that using SMB with Linux Symbolic Links could potentially solve this, but I'm also hoping for the application to be visible and launchable directly from Linux. Can anyone provide a solution or assistance?

**Comment by wuz1run** [comment]
> @wuz1run remote app mode or desktop sessions?

thx for your reply, it 's remote app mode

**Comment by akallabeth** [comment]
@wuz1run you can create a `.desktop` file which then starts `xfreerdp` with the appropriate arguments. (or wrap that in a shell script and start that from the `.desktop` file)

**Comment by akallabeth** [comment]
@ladeng07 with your mouse?
other than that check the help for the application you want to start if that supports such arguments (you can send them on the command line)
