### ISSUE TITLE
TestWinPRUtils "TestBacktrace" fails on 32-bit arm

### ISSUE THREAD

**Issue by jbicha** [FreeRDP/FreeRDP#10223]
**Describe the bug**
One build test is failing on 32-bit arm* on Debian and Ubuntu. The test passes on other architectures including arm64 (64-bit arm).

**To Reproduce**
1. Build with `-DTESTING=ON` on recent Debian (Testing or Unstable) or Ubuntu (24.04 LTS or 24.10 development).

**Expected behavior**
Build tests pass

**Application details**
* FreeRDP version 3.5.1
* Build configuration at https://salsa.debian.org/debian-remote-team/freerdp3/-/blob/master/debian/rules

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Debian Testing or Ubuntu 24.04 LTS
 - Architecture: armel, armhf

**Logs**
```
test 73
        Start  73: TestBacktrace

73: Test command: /<<PKGBUILDDIR>>/debian/testtmp/Testing/TestWinPRUtils "TestBacktrace"
73: Working Directory: /<<PKGBUILDDIR>>/debian/testtmp/winpr/libwinpr/utils/test
73: Test timeout computed to be: 1500
73: winpr_backtrace failed!
```

**Additional context**
Full build logs at https://buildd.debian.org/status/logs.php?pkg=freerdp3&ver=3.5.1%2Bdfsg1-4 (click Maybe-Failed)
or at https://launchpad.net/ubuntu/+source/freerdp3/3.5.1+dfsg1-4

**Comment by akallabeth** [comment]
@jbicha by default we set `-DUSE_UNWIND=ON -DUSE_EXECINFO=ON` (`unwind` preferred)
in your case it seems that `winpr_backtrace` is failing for some reason.

you might run the test manually and break in `winpr_unwind_backtrace` to see where it is failing.

**Comment by akallabeth** [comment]
I´ve created https://github.com/FreeRDP/FreeRDP/pull/10224 to log the specific failure code as string.

**Comment by akallabeth** [comment]
ok, can confirm.
the test fails, because neither `unwind` nor `execinfo` return successful.
