### ISSUE TITLE
Can't use the /app arguments on Fedora 40



### ISSUE THREAD

**Issue by olive007** [FreeRDP/FreeRDP#10249]
So I installed a brain new Fedora 40 and played around with freerdp. Whatever I use xfreerpd wlfredrdp I can't use the /app arguments
I tried many way. I don't get a error about connection or anything like that. I get a error likes it's a parsing problem.

Step to reproduce:
- Install Fedora40
- installation freerdp
- use the command with /u:oli /p:pass /v:$IP --> work
- add the argument: /app:explorer.exe and see it displaying the help message.

**Comment by akallabeth** [comment]
check the argument help.
```
/app: program:[<path>|<||alias>],cmd:<command>,file:<filename>,guid:<guid>,
                                      Remote application program
```

fedora builds the application without backward compatibility support.

**Comment by olive007** [comment]
Can you give an example to make it work with notepad or explorer?

I tried different way to use this argument but I can't figure out how to use it.
`/app: program: explorer.exe`
Don't work neither

**Comment by akallabeth** [comment]
@olive007 `/app:program:explorer.exe` should work, if not check your windows is configured for remote app mode.
