### ISSUE TITLE
Black Borders in Window When Using remote app

### ISSUE THREAD

**Issue by ladeng07** [FreeRDP/FreeRDP#10250]
**Describe the bug**
We can see the black borders in freerdp version 2.11.7 . But it fixed in freerdp version 3.5.1. When we try to use the freerdp version 3.5.1, there are many bugs we can't tolerant. We want to fix the black borders in 2.11.7. Which files can we modify? Thanks a lot.

**Expected behavior**
We want to fix the black borders in 2.11.7.

**Screenshots**
2.11.7
![image](https://github.com/FreeRDP/FreeRDP/assets/40017222/4b0fef2c-ad42-4430-ab5f-e9f361680842)

3.5.1
![image](https://github.com/FreeRDP/FreeRDP/assets/40017222/8c788744-8b62-47b6-9ef4-f5501aab40b7)

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Ubun 22.04
 - Architecture: amd64

**Comment by akallabeth** [comment]
> When we try to use the freerdp version 3.5.1, there are many bugs we can't tolerant.

please name them, we´re fixing what we are aware of.

> We want to fix the black borders in 2.11.7.

a huge backport for all codecs and image copy operations.
we´re not really doing feature backports.

**Comment by JongHong** [comment]
Hi，My problem still exists, what is your execution command?

**Comment by zhuyaliang** [comment]
@ladeng07 I still have black borders on Freerdp version 3.6.3, how did you make the black borders disappear
