### ISSUE TITLE
The video is stuttering when playing videos on Android.

### ISSUE THREAD

**Issue by wlgus9343** [FreeRDP/FreeRDP#10275]
When watching YouTube videos using FreeRdp on the Android Galaxy S7 FE, the frame drops and it's stuttering. The symptoms are severe on the FHD resolution 1920*1080 standard, and it plays a little smoother on lower resolutions. Can you tell me why? The FreeRDP version I used is 3.5.1.

**Comment by akallabeth** [comment]
well, one or more of:
1. hardware not fast enough
2. code currently not fully optimized for arm intrinsics
3. bad connection options
4. bad server configuration
