### ISSUE TITLE
Printer redirection not working properly in freerdp-proxy

### ISSUE THREAD

**Issue by StudyAndGrow** [FreeRDP/FreeRDP#10289]
I connected to the target machine through freerdp-proxy, and the disk redirection was normal, but the printer redirection could not be normal. However, after I forced the flags to add REDIRECTED_SESSIONID_FIELD_VALID in the TS_UD_CS_CLUSTER sent to the rdp server, the printer redirection worked normally. I would like to ask why REDIRECTED_SESSIONID_FIELD_VALID affects the printer redirection.
The following code is where I modified "flags |= REDIRECTED_SESSIONID_FIELD_VALID;"
/**
 * Write a client cluster data block (TS_UD_CS_CLUSTER).\n
 * @msdn{cc240514}flags
 * @param s stream
 * @param settings rdp settings
 */

void gcc_write_client_cluster_data(wStream* s, rdpMcs* mcs)
{
	UINT32 flags;
	rdpSettings* settings = mcs->settings;
	gcc_write_user_data_header(s, CS_CLUSTER, 12);
	flags = REDIRECTION_SUPPORTED | (REDIRECTION_VERSION4 << 2);
	flags |= REDIRECTED_SESSIONID_FIELD_VALID;

	if (settings->ConsoleSession || settings->RedirectedSessionId)
		flags |= REDIRECTED_SESSIONID_FIELD_VALID;

	if (settings->RedirectSmartCards)
		flags |= REDIRECTED_SMARTCARD;

	Stream_Write_UINT32(s, flags);                         /* flags */
	Stream_Write_UINT32(s, settings->RedirectedSessionId); /* redirectedSessionID */
}

Thanks

**Comment by akallabeth** [comment]
@StudyAndGrow sorry, not enough information to make heads and tails from it. 
could you please provide a basic configuration description of your proxy?
* pass through channels?
* intercept channels?
* ...

**Comment by StudyAndGrow** [comment]
> @StudyAndGrow sorry, not enough information to make heads and tails from it. could you please provide a basic configuration description of your proxy?
> 
> * pass through channels?
> * intercept channels?
> * ...

[Channels]
GFX = TRUE
DisplayControl = TRUE
Clipboard = TRUE
AudioOutput = TRUE
RemoteApp = TRUE
; a list of comma seperated static channels that will be proxied. This feature is useful,
; for example when there's a custom static channel that isn't implemented in freerdp/proxy, and is needed to be proxied when connecting through the proxy.
Passthrough = rdpdr

**Comment by akallabeth** [comment]
@StudyAndGrow and you are using which version?

**Comment by StudyAndGrow** [comment]
> @StudyAndGrow and you are using which version?

I am using tag  2.9.0

**Comment by akallabeth** [comment]
> > @StudyAndGrow and you are using which version?
> 
> I am using tag 2.9.0

ok, that explains it.
please update.
we´ve rewritten most of the proxy with the 3.x series to fix a lot of these issues that were due some design bugs in 2.x

**Comment by StudyAndGrow** [comment]
> > > @StudyAndGrow and you are using which version?
> > 
> > 
> > I am using tag 2.9.0
> 
> ok, that explains it. please update. we´ve rewritten most of the proxy with the 3.x series to fix a lot of these issues that were due some design bugs in 2.x

OK, I'll try it now.

**Comment by StudyAndGrow** [comment]
> > > > @StudyAndGrow and you are using which version?
> > > 
> > > 
> > > I am using tag 2.9.0
> > 
> > 
> > ok, that explains it. please update. we´ve rewritten most of the proxy with the 3.x series to fix a lot of these issues that were due some design bugs in 2.x
> 
> OK, I'll try it now.

@akallabeth I implemented it on the master branch, but the printer still doesn't redirect, even after I add the REDIRECTED_SESSIONID_FIELD_VALID flag

**Comment by akallabeth** [comment]
@StudyAndGrow ok, just now did:
1. `winpr-makecert -rdp -path /tmp proxy`
2.  `freerdp-proxy --dump-config /tmp/proxy.ini`
3. modify `proxy.ini`
4. start `freerdp-proxy /tmp/proxy.ini`
5. start `xfreerdp /v:localhost:3333 /u:user /p:pwd /printer`

and that works quite fine.

here is the 
<details><summary>proxy.ini</summary>
```
[Server]
Host=0.0.0.0
Port=3333

[Target]
Host=hostname
Port=3389
FixedTarget=true
TlsSecLevel=1

[Channels]
GFX=true
DisplayControl=true
Clipboard=true
AudioInput=true
AudioOutput=true
DeviceRedirection=true
VideoRedirection=true
CameraRedirection=true
RemoteApp=false
PassthroughIsBlacklist=true
Passthrough=
Intercept=

[Input]
Keyboard=true
Mouse=true
Multitouch=true

[Security]
ServerTlsSecurity=true
ServerNlaSecurity=false
ServerRdpSecurity=true
ClientTlsSecurity=true
ClientNlaSecurity=true
ClientRdpSecurity=true
ClientAllowFallbackToTls=true

[Plugins]
#Modules=module1,module2,...
#Required=module1,module2,...

[Clipboard]
TextOnly=false
MaxTextLength=0

[GFXSettings]
DecodeGFX=false

[Certificates]
CertificateFile=/tmp/proxy.crt
PrivateKeyFile=/tmp/proxy.key
```
</details>

**Comment by StudyAndGrow** [comment]
> ClientNlaSecurity

After adding PassthroughIsBlacklist=true configuration, it can work normally，thank you
