### ISSUE TITLE
Update the documentation for freerdp3

### ISSUE THREAD

**Issue by hum4nizer** [FreeRDP/FreeRDP#10285]
First I want to thank you for this awesome project. Thank you! But the users need an updated and correct documentation of how to use the software. It seems that command lins switches has changed and needs to be updated. Myself for example is trying to go from version 2 to version 3 and just found out in a thread that the gateway option is updated to /gateway:g:[address] but the user /gu does not work. When the binary lists it features and switches it tells me to use /g: for gateway and /gu: for user but none of those are correct values for example.

Thanks!

**Comment by akallabeth** [comment]
@hum4nizer `xfreerdp /help` lists the currently valid command line (and depending on some compile options a few backward compatible ones)
so which issue did you have, where did you look?

**Comment by akallabeth** [comment]
@hum4nizer you are using a distro package or self compiled? in the latter case set `-DWITH_FREERDP_DEPRECATED_COMMANDLINE=ON` to get a stable-2.0 compatible command line (we´ve deprecated stuff but kept it in for now)

**Comment by hum4nizer** [comment]
@akallabeth  Thank you for your support! I see now that i mixed up the output from different versions of the software. I use latest binary release in the Arch repository (2:3.5.1-2) and the /help output gives the correct information: 

/gateway: g:<gateway>[:<port>],u:<user>,d:<domain>,p:<password>,
              usage-method:[direct|detect],access-token:<token>,type:[rpc|http[,
              no-websockets][,extauth-sspi-ntlm]|auto[,no-websockets][,
              extauth-sspi-ntlm]]|arm,url:<wss://url>,
              bearer:<oauth2-bearer-token>
                                      Gateway Hostname 

Thank you!
