### ISSUE TITLE
Failed to map shared memory from the driver

### ISSUE THREAD

**Issue by qq363960630** [FreeRDP/FreeRDP#1029]
Failed to map shared memory from the driver

Who can tell me how to solve this error

My client is x11 and server is winXP

**Comment by dashingvik** [comment]
@qq363960630 how did you solve it ?

**Comment by dashingvik** [comment]
@awakecoding I am still facing the same issue. I have install Mirage driver but encounter with below error
![image](https://user-images.githubusercontent.com/56148491/67196644-d3201b80-f418-11e9-874a-22ba21e3e633.png)
