### ISSUE TITLE
Kerberos deactivation not possible with Fedora 40 FreeRDP version 3.5.1 (n/a)

### ISSUE THREAD

**Issue by michaelschefczyk** [FreeRDP/FreeRDP#10309]
**Describe the bug**
Moving from Fedora 39 to Fedora 40, xfreerdp can no longer connect to windows servers via the command line, such as:

/usr/bin/xfreerdp /d:[domain] /u:[user]l /v:192.168.X.X

This is independent of v being a numerical address or a domain name.

The result is [ERROR][com.winpr.sspi.Kerberos] - [kerberos_AcquireCredentialsHandleA]: krb5glue_get_init_creds (KDC für Realm ... not found

Kerberos is not in use on the system. Commenting out krb5.conf does not help.

Adding

[libdefaults]
rdns = false
dns_lookup_kdc = 0

to krb5.conf does not help either.

Adding /auth-pkg-list:!kerberos yields
bash: !kerberos: event not found

The same bug was posted for Arch and closed a fixed, however the fixes do not seem to work under Fedora 40: https://github.com/FreeRDP/FreeRDP/issues/10138

**To Reproduce**
Under Fedora 40 run /usr/bin/xfreerdp /d:[domain] /u:[user]l /v:192.168.X.X

**Expected behavior**
Connect as under Fedora 39

**Application details**
* FreeRDP version 3.5.1 (n/a)
* Fedora 40

**Comment by hardening** [comment]
Le 26/06/2024 à 08:43, michaelschefczyk a écrit :
> *Describe the bug*
> Moving from Fedora 39 to Fedora 40, xfreerdp can no longer connect to 
> windows servers via the command line, such as:
> 
> /usr/bin/xfreerdp /d:[domain] /u:[user]l /v:192.168.X.X
> 
> This is independent of v being a numerical address or a domain name.
> 
> The result is [ERROR][com.winpr.sspi.Kerberos] - 
> [kerberos_AcquireCredentialsHandleA]: krb5glue_get_init_creds (KDC für 
> Realm ... not found
> 
> Kerberos is not in use on the system. Commenting out krb5.conf does not 
> help.
> 
> Adding
> 
> [libdefaults]
> rdns = false
> dns_lookup_kdc = 0
> 
> to krb5.conf does not help either.
> 
> Adding /auth-pkg-list:!kerberos yields
> bash: !kerberos: event not found
> 

Hi,

of course you must use '/auth-pkg-list:!kerberos' (quoted) or the ! is 
interpreted by bash.

Best regards.

-- 
David FORT
website: https://www.hardening-consulting.com/

**Comment by michaelschefczyk** [comment]
Thank you very much! This does work, but it leads to the next error. I will find a new bug report.

-----Ursprüngliche Nachricht-----
