### ISSUE TITLE
[xfreerdp] (bisected) 2.11.7 can't play Solitaire in Win7 home

### ISSUE THREAD

**Issue by duncan-roe** [FreeRDP/FreeRDP#10357]
**Describe the bug**
On the stable-2.0 branch, mouse drag has not worked for some time. master branch does not have this problem.
A git bisect identified
\# first bad commit: [2d84387fcd3787af6294509d166d746c83d0acf5] Conservative keyboard state sync, refactored input API

**To Reproduce**
1. Start solitaire
2. Attempt to drag a face-up card
3. Card cannot be moved.

**Expected behavior**
Card should move.

**Application details**
* FreeRDP version 2.11.7
* Command line used: xfreerdp /u:Duncan /v:rockstar
* OS version connecting to: Win 7 Home Premium, patched with `Concurrent RDP Patcher April 2019` by Raymond.CC. This patch is no longer available from Raymond's site www.raymond.cc which now gets his new site whatsoftware.com.

**Environment**
 - OS: Linux
 - Distribution: Slackware 15.0 patched to 240630; Linux 6.8.4
 - Architecture: amd64

**Build environment**
- gcc (GCC) 11.2.0
```
  cmake \
    -DCMAKE_C_FLAGS="-O2 -fPIC" \
    -DCMAKE_CXX_FLAGS="-O2 -fPIC" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_ALSA=ON \
    -DWITH_PULSE=ON \
    -DWITH_CHANNELS=ON \
    -DBUILTIN_CHANNELS=ON \
    -DWITH_CUPS=ON \
    -DWITH_PCSC=ON \
    -DWITH_JPEG=ON \
    -DWITH_FFMPEG=ON \
    -DWITH_DSP_FFMPEG=ON \
    -DWITH_WAYLAND=ON \
    -DWITH_GSSAPI=OFF \
    -DCHANNEL_URBDRC=ON \
    -DCHANNEL_URBDRC_CLIENT=ON \
    -DWITH_SERVER=ON \
    -DWITH_CAIRO=ON \
    -DBUILD_TESTING=OFF
```
[bisect.log](https://github.com/user-attachments/files/16114717/bisect.log)

**Comment by akallabeth** [comment]
ok, did a fresh build from `stable-2.0` and `2.11.7` and tested:
1. connect `/tmp/test/bin/xfreerdp /v:192.168.xx.xx /u:demo /p:pwd /tls-seclevel:0`
2. target is a windows 7 starter (but that should not matter if there is really an issue with dragging)
3. open solitaire and play, drag cards

works every time.
the commit you reference in the bisect also does not change anything with regard to mouse. (it just calls `freerdp_input_send_mouse_event` instead of `input->MouseEvent` which is just a wrapper)

maybe something in combination with your window manager/compositor? which one are you using?

**Comment by duncan-roe** [comment]
On Fri, Jul 05, 2024 at 09:45:43PM -0700, akallabeth wrote:
> ok, did a fresh build from `stable-2.0` and `2.11.7` and tested:
> 1. connect `/tmp/test/bin/xfreerdp /v:192.168.xx.xx /u:demo /p:pwd
> /tls-seclevel:0`
> 2. target is a windows 7 starter (but that should not matter if there is
> really an issue with dragging)
> 3. open solitaire and play, drag cards
>
> works every time.
> the commit you reference in the bisect also does not change anything
> with regard to mouse. (it just calls `freerdp_input_send_mouse_event`
> instead of `input->MouseEvent` which is just a wrapper)

Quoting from https://bugzilla.kernel.org/show_bug.cgi?id=203935 that I
submitted:

> Borislav Petkov 2019-06-20 08:04:00 UTC
> Hmm, this patch shouldn't change anything AFAICT. Adding some people to CC.

But it *was* that patch. Brought on by a bug in the specific GCC version I was
using. I just now edited the problem description to include gcc revision and
cmake command. Sorry I didn't have them in originally.

Here's what I did to verify I have the right patch this time:
- Create a test branch at a8326f9d4 (commit after 2d84387fc) with 2d84387fc reverted.
- Build and test: can drag cards again.
- Progressively rebase test branch on later commits, build and test OK.
- Stopped when I got to 2.10.0 (2 manual merge fixes by then).
- Still builds and drags cards OK.

I don't have an environment with a different gcc to try yet, will post if I
manage to build one.

You might find the kernel bug report mildly entertaining esp. Linus Torvalds's
first comment.
>
> maybe something in combination with your window manager/compositor?
> which one are you using?

Window manager is fvwm-2.6.6.

**Comment by akallabeth** [comment]
@duncan-roe hmm, can you check which `X11` events you receive? It might be a bug with the window manager forcing `xf_sync_kbd_state` to be called (always done after a keyboard key press)
do you, by chance, get a keyboard event for your mouse events too?

**Comment by akallabeth** [comment]
@duncan-roe fyi: tried on my machine now `fvwm`, `fvwm1`, `fvwm2`, `fvwm3` as window managers (debian 12 system) and in all cases can drag normally.
you mind testing this with a default fvwm config rather than what you currently use?
it might have to do something with mouse handling options that interferes here, so that test might be helpful.

**Comment by duncan-roe** [comment]
Updated problem description to mention the target system is Windows Home *Premium*

**Comment by duncan-roe** [comment]
Tried fvwm2 with no customisation and could drag cards. Will try to find out what customisation makes it not work

**Comment by duncan-roe** [comment]
The thing that breaks it is installing Windows95 look and feel. fvwm-2.6.6 was the last rev to have the win95-style task bar which I rather like. You can still get 2.6.6 at https://github.com/fvwmorg/fvwm/releases/download/version-2_6_6/fvwm-2.6.6.tar.gz. Run it with no config and run the "Setup 95 Script" from the root menu. I accepted all defaults except editor (chose gvim). Restart fvwm when done and cards stop dragging. More info in $PREFIX/share/fvwm/system.fvwm2rc-sample-95.
fvwm2 is no longer supported. 2.6.6 is the oldest release still available.

**Comment by akallabeth** [comment]
ok, so basically a fvwm or configuration bug.

had a similar request for sway and multimonitor on matrix channel.
try a build with `-DWITH_DEBUG_X11=ON`, run with `/log-level:trace` and check the log.

the one for sway did have `FocusOut` and `FocusIn` events between `ButtonPress` and `ButtonRelease` events. (you only need the log lines with `xf_event_process` in them)

you most likely configured something similar with that.

closing as not our bug ;)
