### ISSUE TITLE
Messed up graphics in large 3.6.2 windows

### ISSUE THREAD

**Issue by LinAGKar** [FreeRDP/FreeRDP#10351]
**Describe the bug**
With the latest version (3.6.2, flatpak 84217f5ed3cc8c4236e48d3e50a66091241c94b1365a595871766195e6dd9e68), the graphics get completely messed up, as can be seen in the attached video. This does not happen if I downgrade the flatpak to fe367f9eeea3a870437fcf636ebc7db0f1eb09710a5d205edeaf935b8ae7edb1. It also only seems to happen if I have the freerdp window at a large size. If I make the window a bit smaller, the problem disappears

**Screenshots**
https://github.com/FreeRDP/FreeRDP/assets/3390621/48a30825-ba21-43f6-8f44-4c903f19405e

**Application details**

* FreeRDP version (`xfreerdp /version`): 3.6.2
* Command line used: `flatpak run --command=xfreerdp com.freerdp.FreeRDP /dynamic-resolution /w:2560 /h:1412 "/v:$HOST" "/u:.\\AzureAD\\$USER" /sec:tls /cert:ignore /p:"$PASS"`
* Output of `xfreerdp /buildconfig`:  [freerdp-buildconf.txt](https://github.com/user-attachments/files/16108548/freerdp-buildconf.txt)
* OS version connecting to (server side): Windows 11
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`: [freerdp-log.txt](https://github.com/user-attachments/files/16108566/freerdp-log.txt)

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: OpenSUSE Leap 15.5
 - Architecture: amd64

**Additional context**

Windows Group policy settings:
Prioritize H.264/AVC 444 graphics mode for Remote Desktop Connections: enabled
Configure image quality for RemoteFX Adaptive Graphics: lossless
Optimize visual experience when using RemoteFX: Screen capture rate: highest, Screen Image Quality: highest

**Comment by akallabeth** [comment]
@LinAGKar ok, that is an interesting one.
did test against a windows 11 vm with same policy (dual 4k setup) and can not reproduce.

can you check which codec is actually used by running with `/log-level:trace`? there should be  `[gdi_SurfaceCommand]: surfaceId=0, codec=RDPGFX_CODECID_AVC444v2 [15],`  (or another codec) entries for the codecs used.

**Comment by akallabeth** [comment]
@LinAGKar ok, can reproduce now, spoke too soon :grin:

**Comment by akallabeth** [comment]
@LinAGKar ok, `git bisect` revealed 1a58e74c17a367dbbdd7038ded8ecd03eeddbb5b as culprit. Reverted in referenced pull request, please test.

**Comment by LinAGKar** [comment]
Sorry for not responding sooner. It looks to me like the single memcpy path would work under the additional condition that `copyDstWidth == nDstStep` (and `srcVMultiplier == 1 && dstVMultiplier == 1 && srcVOffset == 0 && dstVOffset == 0`, but I guess `!vSrcVFlip` is supposed to take care of that).

I haven't managed to build it to test though, as I got an error that it's missing SDL3_ttf, and when I tried to build that and point CMake at it I got:

```
CMake Error at /home/linus/git/SDL_ttf/build/SDL3_ttfConfig.cmake:57 (add_library):
  add_library cannot create ALIAS target "SDL3_ttf::SDL3_ttf" because target
  "SDL3_ttf::SDL3_ttf-static" does not already exist.
Call Stack (most recent call first):
  /home/linus/git/SDL_ttf/build/SDL3_ttfConfig.cmake:66 (_sdl_create_target_alias_compat)
  client/SDL/SDL3/dialogs/CMakeLists.txt:51 (find_package)
  client/SDL/SDL3/dialogs/CMakeLists.txt:59 (find_sdl_component)
```

**Comment by akallabeth** [comment]
@LinAGKar SDL3 is not an error, just a warning (builds fine without it)

**Comment by LinAGKar** [comment]
Certainly looks like an error to me. When I didn't try to point it at SDL3_ttf I got:

```
CMake Error at client/SDL/SDL3/dialogs/CMakeLists.txt:51 (find_package):
  By not providing "FindSDL3_ttf.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "SDL3_ttf",
  but CMake did not find one.

  Could not find a package configuration file provided by "SDL3_ttf" with any
  of the following names:

    SDL3_ttfConfig.cmake
    sdl3_ttf-config.cmake

  Add the installation prefix of "SDL3_ttf" to CMAKE_PREFIX_PATH or set
  "SDL3_ttf_DIR" to a directory containing one of the above files.  If
  "SDL3_ttf" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  client/SDL/SDL3/dialogs/CMakeLists.txt:59 (find_sdl_component)


-- Configuring incomplete, errors occurred!
```

And a bit before that:

```
Building both, SDL2 and SDL3 clients, forcing WITH_CLIENT_SDL_VERSIONED=ON
```

So maybe it's finding SDL3 and choosing to use it automatically, but then failing because it can't find a library for it.

**Comment by akallabeth** [comment]
@LinAGKar don´t force SDL3 build then ;)

**Comment by LinAGKar** [comment]
I'm not, I'm literally just running `cmake -G Ninja ..`, with no more arguments

**Comment by akallabeth** [comment]
@LinAGKar then delete your old build directories.
the configure run does probe which dependencies are there and uses these as default for some settings (SDL3 for example)

**Comment by LinAGKar** [comment]
What build directories (other than the one for FreeRDP, which I have cleared)?

There seems no check in https://github.com/FreeRDP/FreeRDP/blob/master/client/SDL/CMakeLists.txt for whether SDL3_ttf is available, it tries to build for SDL3 regardless.

**Comment by akallabeth** [comment]
@LinAGKar 
* you need to clean `../`
* the default of `SDL2` and `SDL3` `on|off` is determined by the availability of the `SDL` package, everything else  (SDL_image, SDL_ttf) is a different matter. (only required if the SDL dialogs are build) (it is only the default, check the current value with `ccmake`, you can change it anytime)

**Comment by LinAGKar** [comment]
>you need to clean ../

There aren't any files in there outside of the build directory other than the stuff from the git repo.

>the default of SDL2 and SDL3 on|off is determined by the availability of the SDL package, everything else (SDL_image, SDL_ttf) is a different matter. (only required if the SDL dialogs are build) (it is only the default, check the current value with ccmake, you can change it anytime)

WITH_SDL_IMAGE_DIALOGS is OFF according to ccmake.

Where is that check? From what I can see, https://github.com/FreeRDP/FreeRDP/blob/master/client/SDL/SDL3/CMakeLists.txt unconditionally includes the dialogs directory, and then https://github.com/FreeRDP/FreeRDP/blob/master/client/SDL/SDL3/dialogs/CMakeLists.txt unconditionally tries to find SDL3_ttf.

**Comment by akallabeth** [comment]
@LinAGKar what about https://github.com/FreeRDP/FreeRDP/blob/9d1f98a19582336b651dbd1f3ae0f47b8142a21b/client/SDL/CMakeLists.txt#L92 then for general SDL3 on/off?
as for `SLD3_ttf` that might be a bug, not tried that combination yet.

**Comment by LinAGKar** [comment]
`SDL3_FOUND` I assume is autogenerated, but I was now able to build by setting `WITH_CLIENT_SDL3` to OFF, and adding a `copyDstWidth == nDstStep` condition does appear to fix the original issue.

**Comment by akallabeth** [comment]
@LinAGKar adding the condition where?

**Comment by LinAGKar** [comment]
Like this:

```diff
diff --git a/libfreerdp/primitives/prim_copy.c b/libfreerdp/primitives/prim_copy.c
index 195d289bd..fb4d1ce7f 100644
--- a/libfreerdp/primitives/prim_copy.c
+++ b/libfreerdp/primitives/prim_copy.c
@@ -243,7 +243,7 @@ pstatus_t generic_image_copy_no_overlap_memcpy(
 	const SSIZE_T xSrcOffset = nXSrc * srcByte;
 	const SSIZE_T xDstOffset = nXDst * dstByte;
 
-	if (!vSrcVFlip && (nDstStep == nSrcStep) && (xSrcOffset == 0) && (xDstOffset == 0))
+	if (!vSrcVFlip && (nDstStep == nSrcStep) && (xSrcOffset == 0) && (xDstOffset == 0) && (copyDstWidth == nDstStep))
 	{
 		const void* src = &pSrcData[1ull * nYSrc * nSrcStep];
 		void* dst = &pDstData[1ull * nYDst * nDstStep];

```
