### ISSUE TITLE
Cannot exit fullscreen

### ISSUE THREAD

**Issue by JonnyTech** [FreeRDP/FreeRDP#1036]
I just downloaded and installed the latest snapshot of FreeRDP.
Running on Slackware 14 64bit - connecting to any Windows system.
When I hit CTRL-ALT-ENTER to exit fullscreen then nothing happens.
The previous snapshot from a few weeks ago worked fine.
My connection string is:
xfreerdp +clipboard /cert-ignore /f -themes -wallpaper /bpp:16 /u:username /v:ipadddress /p:password

**Comment by jocull** [comment]
CTRL-ALT-Enter also conflicts with the VMware fullscreen hotkeys in my case.

**Comment by bernd-wechner** [comment]
I disable this specifically because it clashes with Window keys I do use. Would be nice if we could associate a desired key sequence to this. In a config file or command line whatever really.

**Comment by rbreaves** [comment]
Agreed - Ctrl-Alt-Enter is problematic and can create conflicts. Users need to be able to change this.

**Comment by rbreaves** [comment]
I did find that I can change the Ctrl-Alt-Enter hotkey of vmware player to Ctrl-Win-Shift-Enter and this is how I do that. I also hide the toolbar hover menu. Might help you out @bernd-wechner 

%APPDATA%\VMware\preferences.ini
`` `
pref.hotkey.gui = "true"
pref.hotkey.shift = "true"
pref.hotkey.control = "true"
pref.hotkey.alt = "false"
pref.vmplayer.fullscreen.autohide = "TRUE"
```

**Comment by bernd-wechner** [comment]
But I'm not using VMWare. I'm connecting to a remote Windows desktop machine from a  local Linux desktop machine (over a VPN) working from home.

**Comment by rbreaves** [comment]
Ah, well more helpful for @jocull then lol. I read somewhere online that Ctrl-Alt-End might remap to Ctrl-Alt-Del on windows remote sessions?

**Comment by Fazx** [comment]
my alternative way after connection already established:
1. disable the hotkey in VMware preference settings
2. ctrl+alt+enter

**Comment by sr3dna** [comment]
My guest OS is Windows 11.   The Ctrl-Alt-Enter keys somehow only works for me the first time.  Anyways, in my case, the only reason I want to exit fullscreen is to end the remote session.  So my work around is, I would click on the Start menu button, then select the Power button, as if I am going to Shutdown or Restart.   But since this is a remote desktop session, there is also a  'Disconnect'option.  I would use that option to end the remote desktop session.
