### ISSUE TITLE
FreeRDP  logging faill with empty password

### ISSUE THREAD

**Issue by goodnewday** [FreeRDP/FreeRDP#10379]
**Describe the bug**

 I use user admin and empty password.  Why does using FreeRDP in AuthenticationOnly mode always fail when logging into a Windows host with an empty password?

**Comment by akallabeth** [comment]
because it will never succeed in logging in?

`+auth-only` tries to authenticate and then terminate the session. (Note: This only works reliable with `NLA` security anyway)

**Comment by goodnewday** [comment]
Sorry, I didn't describe it clearly;  The problem is that  I can't authed success when use empty password;

**Comment by akallabeth** [comment]
yes?
how do you want to login with an empty password & `NLA`? (hint: even with kerberos one is required)

**Comment by goodnewday** [comment]
I want use it to  find  weak password problem;
