### ISSUE TITLE
Drive mapping parsing failing yet drive still redirected

### ISSUE THREAD

**Issue by user-629782** [FreeRDP/FreeRDP#10378]
When redirecting a local drive to a Windows server, I receive the following error from xfreerdp;
...
[17:08:21:662] [23509:00005bd5] [ERROR][com.freerdp.client.common.cmdline] - [freerdp_client_command_line_post_filter_int]: Command line parsing failed at 'drive' value 'Temp,/home/user/Temp' [1]
...
However, the Temp folder is correctly redirected to the Windows server.

Command line used:
/usr/local/freerdp/bin/xfreerdp /network:auto /gfx:avc444 /u:username /p:password /f /smart-sizing:1920x1080 /drive:Temp,/home/user/Temp /d:DOMAIN /sec:nla /cert:ignore /v:192.168.0.XYZ

Client: Ubuntu 22.04.4 LTS
Server: Windows 2022 RDS Server

FreeRDP: Version 3.6.3

Possible side-effect of #10320

**Comment by akallabeth** [comment]
fixed with https://github.com/FreeRDP/FreeRDP/pull/10365
