### ISSUE TITLE
SDL client does not reconnect properly

### ISSUE THREAD

**Issue by eyalt** [FreeRDP/FreeRDP#10389]
**Describe the bug**
SDL client does not reconnect when encountering a network problem.

**To Reproduce**
1. Run SDL client with auto reconnect (`+auto-reconnect`)
2. Connect to a server
3. Run command `sudo ss --kill dport = 3389` (or other OS specific alternative)
4. Client exits and doesn't try to reconnect

**Expected behavior**
Client will attempt to reconnect (up to max retries), and will continue in case of a successful connection

**Application details**
* FreeRDP version (`xfreerdp /version`): `This is FreeRDP version 3.6.4-dev0 (fa0232048)`
* Command line used: `+auto-reconnect` (and connection credentials)
* OS version connecting to (server side): Windows 11
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help - Latest commit `fa0232048c256d73e40bc4cc711fd70b1b238561`

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Ubuntu 23.04
 - Architecture: amd64

**Additional context**
Function `sdl_client_thread_proc` has a call to `client_auto_reconnect` but seems to be out of place.
Right now it only tries to reconnect when `WaitForMultipleObjects` fails, but the correct place should be in the case `freerdp_check_event_handles` fails (this is the flow in `xf_client_thread`, the X11 client), as this is the function that fails when a connection is closed (and other circumstances).

**Comment by akallabeth** [comment]
@eyalt thx for the nice bug report.
hope the referenced pull request did fix your issue.

**Comment by TolchiIsland** [comment]
Thank you for your quick respone.
I also noted a race in matrix chat (that I actually encountered myself), I don't believe this pull requests addresses it, am I correct? Is there an intention to fix that as well?

**Comment by akallabeth** [comment]
@TolchiIsland ok, missed that (thought you just copied the same text ^^)
fixed that now as well.
