### ISSUE TITLE
the display gets messy with ghosting when dragging windows or scrolling tables.

### ISSUE THREAD

**Issue by yuweiming2016** [FreeRDP/FreeRDP#10388]
![e1d047b5c46ae36ba38d5685e3bc8d80](https://github.com/user-attachments/assets/e0abb023-5eec-4d3f-a86a-76f471c28fcd)

When dragging windows or scrolling through menus, the display gets messy with ghosting effects appearing on the screen.

xfreerdp version: 2.2.0
windows server version:   windows server 2016

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

1. please don´t report stuff for ancient versions.
2. please provide the requested information (no idea which connection mode you use for example)

**Comment by akallabeth** [comment]
old version, no details, no feedback
closing.
