### ISSUE TITLE
Suspicious arithmetic

### ISSUE THREAD

**Issue by pkopylov** [FreeRDP/FreeRDP#10382]
https://github.com/FreeRDP/FreeRDP/blob/1033471a31529d66e2bb42135a39abf3b1aafbcf/libfreerdp/core/gateway/rpc_client.c#L1086

The `frag_length` is the `UINT16` field. The assigned value here is  32 or 64 bit depending on a target system. It looks suspicious. Maybe all arith made with the offset variable shall control overflow for `UINT16` max value?

For instance, [here](https://github.com/FreeRDP/FreeRDP/blob/1033471a31529d66e2bb42135a39abf3b1aafbcf/libfreerdp/core/gateway/rpc_client.c#L1055) the length is cut to `UINT16` value, but in the following code https://github.com/FreeRDP/FreeRDP/blob/1033471a31529d66e2bb42135a39abf3b1aafbcf/libfreerdp/core/gateway/rpc_client.c#L1085  the `8` value is added which might be not safe for the length greater than 65527 or a bit less (because we have already some non-zero value in the `offset` accumulator).

The wrong calculated value then is used to allocate memory as shown in the code fragment below finally the memory copy function is used to write to a buffer potentially having not enough memory allocated::

	request_pdu.header.frag_length = offset;
	buffer = (BYTE*)calloc(1, request_pdu.header.frag_length);

	if (!buffer)
		goto fail;

	CopyMemory(buffer, &request_pdu, 24);
	offset = 24;
	rpc_offset_pad(&offset, stub_data_pad);
	CopyMemory(&buffer[offset], request_pdu.stub_data, length);

**Comment by akallabeth** [comment]
same as before, this is a `write` function where the application controls all sizes.
you can create a pull request if you want to, but a simple `WINPR_ASSERT` at the beginning should suffice.
