### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by pkopylov** [FreeRDP/FreeRDP#10386]
https://github.com/FreeRDP/FreeRDP/blob/7d6bdbaef8014f7247d3b65efc365c92f1aa5253/libfreerdp/core/gateway/tsg.c#L1342

I think there should be `goto fail` instead of return in order to free `s`.

**Comment by akallabeth** [comment]
[no](https://github.com/FreeRDP/FreeRDP/blob/7d6bdbaef8014f7247d3b65efc365c92f1aa5253/libfreerdp/core/gateway/rpc_client.c#L1121)

**Comment by pkopylov** [comment]
> [no](https://github.com/FreeRDP/FreeRDP/blob/7d6bdbaef8014f7247d3b65efc365c92f1aa5253/libfreerdp/core/gateway/rpc_client.c#L1121)

Now I see, the `rpc_client_write_call()` frees the `s` parameter passed into the function. Thank ypu!
