### ISSUE TITLE
Probably a NULL value can be returned but is not checked

### ISSUE THREAD

**Issue by pkopylov** [FreeRDP/FreeRDP#10380]
https://github.com/FreeRDP/FreeRDP/blob/1033471a31529d66e2bb42135a39abf3b1aafbcf/libfreerdp/core/gateway/rpc_client.c#L989

The `rpc_client_call_find_by_id() ` function uses `header.call_id` as a parameter.  The `header.call_id` is read from a stream provided by an external source. It seems like a vulnerability. I suggest to check the `clientCall` whether is NULL value and return -1.

**Comment by akallabeth** [comment]
not a vulnerability (this is a function sending data, if it is `NULL` here the program is dysfunctional already), but a check would be nicer, true.
thx for the hint.
