### ISSUE TITLE
Option to not change cursor

### ISSUE THREAD

**Issue by parsiad** [FreeRDP/FreeRDP#10407]
**Is your feature request related to a problem? Please describe.**

With `-mouse-motion`, the cursor still changes to the client's cursor but only when clicking. The effect of this is that sometimes the cursor changes to a caret cursor which is hard to see.

**Describe the solution you'd like**

An option to not display the client's cursor and instead use the host's cursor.

**Describe alternatives you've considered**

N/A

**Additional context**

I would be happy to take a crack at writing this feature if someone gives me a few code pointers (e.g., where the cursor is set).

**Comment by parsiad** [comment]
It seems like the issue is actually more nefarious than I thought. I increased the size of the cursor and made it bright green and noticed that it wasn't necessarily always turning into a hard-to-see caret. It is often just disappearing entirely. Regardless, an option to disable drawing the client's cursor would solve these problems.

**Comment by akallabeth** [comment]
@parsiad ok, which client did you see that behavior with? (the disappearing cursor)
using it quite often with `xfreerdp` and the cursor is always the same as with native windows (except the mentioned caret cursor, which is alternating black/white as there is no way to display it inverted to background as done on windows)

anyway, did some draft of this here: https://github.com/akallabeth/FreeRDP/tree/mouse-host-pointer just not sure another option is a good idea - better fix the bug you have

**Comment by parsiad** [comment]
Thanks @akallabeth!

It's a Windows 11 client and I've narrowed it down to the following behavior: when I type (but only in certain applications such as Windows Terminal or Outlook) the cursor disappears.

**Comment by akallabeth** [comment]
@parsiad ok,
* does this behavior also happen with `mstsc`?
* can you run a debug build from https://github.com/akallabeth/FreeRDP/tree/mouse-host-pointer ? I´ve added log entries for mouse pointer changes (enable with `/log-filters:com.freerdp.cache.pointer:trace` to get all cursor related changes in the log)

**Comment by parsiad** [comment]
I compiled it but I couldn't get it to connect to the host. It complains about the host key having changed. The xfreerdp on my system is still able to connect, however.

I did notice that the gateway options changed and there is no longer a /gt option which I had to remove.

**Comment by parsiad** [comment]
Ok I got everything compiled and am running with your flag. I am seeing this when I type into Windows Terminal:

```
[21:02:07:940] [144369:000233f2] [TRACE][com.freerdp.cache.pointer] - [update_pointer_system]: Pointer::SetNull []
```

**Comment by parsiad** [comment]
Having said that, the `+mouse-use-host-pointer` feature works wonderfully. I hope you will consider merging it to master regardless of whether or not the disappearing mouse bug can be fixed.

**Comment by akallabeth** [comment]
> ```
> [21:02:07:940] [144369:000233f2] [TRACE][com.freerdp.cache.pointer] - [update_pointer_system]: Pointer::SetNull []
> ```

this indicates the pointer is intended to be hidden:
* you receive the message from the server indicating the cursor should be hidden 
* there is no local path to trigger that

> In addition to that, I tested with `mstsc` under which the cursor behaves normally (it does not disappear).

which connection options did you use? sometimes windows servers behave differently depending on connection options

**Comment by parsiad** [comment]
Here's how I run it:

```shell
#!/bin/bash

GATEWAY=XXXXXX
HOST=XXXXXX
USER=XXXXXX

MOUSE_MOTION=$(zenity --cancel-label="No" --ok-label="Yes" --question --text="Do you want to enable mouse motion?" && echo + || echo -)mouse-motion
PASSWORD=$(zenity --entry --hide-text --text="Enter password for $USER" --title="$HOST")

if [ -n "${FREERDP2}" ]; then
  BIN="xfreerdp /dynamic-resolution /g:$GATEWAY /gt:http /jpeg"
else
  BIN="xfreerdp3 +dynamic-resolution /gateway:g:$GATEWAY +jpeg"
fi

$BIN \
  /compression-level:2 \
  -fonts \
  -grab-keyboard \
  -grab-mouse \
  $MOUSE_MOTION \
  /p:$PASSWORD \
  -themes \
  /u:$USER \
  /v:$HOST \
  -wallpaper
```

**Comment by akallabeth** [comment]
`/compression-level:2 /jpeg` are useless, better drop these.

**Comment by parsiad** [comment]
Thanks! I dropped them from the script. The mouse disappearing persists after dropping those options.

**Comment by akallabeth** [comment]
> Thanks! I dropped them from the script. The mouse disappearing persists after dropping those options.

did not expect that.
just curious, if you leave out all arguments except `/v:host /u:user /p:pass` does it still hide the mouse then? (most likely yes, but just to be sure)

**Comment by parsiad** [comment]
Can confirm it persists

**Comment by parsiad** [comment]
So it turns out Windows has a feature to hide the cursor! Sorry I thought this was RDP related...

![image](https://github.com/user-attachments/assets/e92a9d07-38c7-4c11-91ec-3ed624e4aa21)

**Comment by akallabeth** [comment]
so, closing this then?
