### ISSUE TITLE
/serial forwarding and carriage return

### ISSUE THREAD

**Issue by dontsueme** [FreeRDP/FreeRDP#1044]
$ git describe
1.0.0-2274-g7ac7fe3

command used:
xfreerdp /network:modem /serial:"COM1","/dev/ttyUSB0" /v:xxx /u:xxx /p:xxx /d:xxx

![freerdp-putty](https://f.cloud.github.com/assets/345782/225300/2607401c-85ee-11e2-93ec-3f8379e08b85.png)

which is also descriped here: https://github.com/FreeRDP/FreeRDP/issues/963

My testscenario is simple: i forwarded a getty listening on a ttyS0 with 9600 baud.

Also tested with rdesktop, that doesn't have this issue.

**Comment by Vladimir-csp** [comment]
I can confirm this with freerdp2-x11 2.0.0~git20161130.1.e60d0d5+dfsg1-1 on Debian Stretch.
The last symbol that a barcode scanner produces is CR (`0D`), but what PuTTY shows inside RDP session looks like LF.

**Comment by Vladimir-csp** [comment]
Behavior I described in previous comment is happening if the argument was `/serial:COM3,/dev/ttyS0`. When launching with argument `/serial:COM3,/dev/ttyS0,serial,permissive`, then CR appears to be transmitted normally.

**Comment by akallabeth** [comment]
@Vladimir-csp There have been some commits to serial redirection, is this still an issue?
