### ISSUE TITLE
xfreerdp can't display window icon in gnome

### ISSUE THREAD

**Issue by amazingfate** [FreeRDP/FreeRDP#10461]
I'm running xfreerdp3 in ubuntu 24.04 gnome wayland with command:
```
xfreerdp3 /f /cert:ignore /floatbar /v:10.5.120.15
```
And freerdp's icon is not showed in gnome's task bar and window overview:
![image](https://github.com/user-attachments/assets/f7a7895b-c012-46e1-a6d2-f055dfc04254)

This is not a issue in ubuntu 22.04. I guess gnome has done some changes related.

I'm using freerdp shipped in ubuntu 24.04: https://packages.ubuntu.com/noble/freerdp3-x11

**Comment by akallabeth** [comment]
window icons are read from the `.desktop` file for the application.
we do not ship one, so this is more or less expected.

**Comment by akallabeth** [comment]
might not be the worst idea to add these to the linux builds for all clients

**Comment by amazingfate** [comment]
We have icon intergrated in client https://github.com/FreeRDP/FreeRDP/blob/3.7.0/client/X11/xf_window.c#L581.
To pass args to desktop entry, I have to add `Exec=/usr/bin/xfreerdp3 %U` to desktop file, and run with
```
gio launch .local/share/applications/xfreerdp.desktop /cert:ignore /floatbar /v:10.5.120.15 /u:liujianfeng1994@gmail.com /p:12345678
```
Now the icon is showed with the one defined in desktop file.
But `gio` command will raise a terminal window.

**Comment by akallabeth** [comment]
@amazingfate for `_NET_WM_ICON` I´ve found https://stackoverflow.com/questions/78473551/how-to-get-an-icon-for-the-gnome-dash-from-a-terminal-app-that-opens-a-window and can confirm this on my systems.

**Comment by amazingfate** [comment]
I've created a bug to gnome: https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7835

**Comment by amazingfate** [comment]
Quoted from [Florian Müllner](https://gitlab.gnome.org/fmuellner):
>Yes, since 46.0 mutter no longer exposes the window icon of X11 clients (they never existed for wayland clients).
>That means that if a .desktop file is missing or cannot be matched to a window, we will now always directly fall back to a generic >icons for both X11 and wayland windows.
>(Note that we only show "app" icons in gnome-shell. Using the X11 window icon in case the app is incomplete or faulty has been >considered a fallback for the last 15 or so years, not a feature or desirable behavior)

Unfortunately gnome won't fix this issue.

**Comment by akallabeth** [comment]
@amazingfate ok, so closing this as it is not our bug.
