### ISSUE TITLE
Missing scancode for '=' character

### ISSUE THREAD

**Issue by OfirMatasas** [FreeRDP/FreeRDP#10478]
**Describe the bug**
Using the "FreeRDP" library, I need to remotely type a password, which could contain the '=' character.
I've tried, but got a failure for not having a scancode for this character.
After checking this file (include/freerdp/scancode.h), it seems that there's a missing scancode for the '=' character.
The interesting thing is that when I'm connected to the remote machine, and I'm trying to type '=' - it works.

**To Reproduce**
I'm not entirely sure how to reproduce it, for using an adapter for this library.
It think it could be using the "press key" function using the '=' character.
But it looks like the library itself is not supporting this scancode, like it's supporting all the other characters.

**Expected behavior**
When typing the '=' character using the FreeRDP library - it would actually type and write it.

**Application details**
* FreeRDP version - I think it's FreeRDP2, but again, I'm using an adapter for it.
* OS version connecting to - Windows Server 2019

**Environment (please complete the following information):**
 - OS: Windows
 - Version/Distribution: Windows Server 2019
 - Architecture: 64bit

**Comment by akallabeth** [comment]
no idea what you need the defines for, but you can not use scancodes like that without knowing the remote keyboard layout ;)
anyway, the scancode you´re looking for is `RDP_SCANCODE_OEM_PLUS`

https://kbdlayout.info/kbdusx/scancodes might help you with understanding the naming.

**Comment by OfirMatasas** [comment]
> no idea what you need the defines for, but you can not use scancodes like that without knowing the remote keyboard layout ;) anyway, the scancode you´re looking for is `RDP_SCANCODE_OEM_PLUS`
> 
> https://kbdlayout.info/kbdusx/scancodes might help you with understanding the naming.

Thank you for your instant reply!
Much appreciated :)
