### ISSUE TITLE
 Could not find com.android.tools.build:gradle:2.3.3

### ISSUE THREAD

**Issue by WengMingJ** [FreeRDP/FreeRDP#10486]
* What went wrong:
A problem occurred configuring project ':aFreeRDP'.
> Could not resolve all artifacts for configuration ':aFreeRDP:classpath'.
   > Could not find com.android.tools.build:gradle:2.3.3.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project :aFreeRDP > com.gladed.androidgitversion:com.gladed.androidgitversion.gradle.plugin:0.4.4 > gradle.plugin.com.gladed.gradle.androidgitversion:gradle-android-git-version:0.4.4

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by akallabeth** [comment]
@WengMingJ pull requests welcome.
android client is looking for a maintainer ;)

**Comment by WengMingJ** [comment]
![image](https://github.com/user-attachments/assets/7816ffed-ab0a-482d-a42d-de7ef13ba891)
update version '0.4.14'  fix Could not find com.android.tools.build:gradle:2.3.3

**Comment by aaagab** [comment]
As a workaround not a fix, you can comment in file  FreeRDP/client/Android/Studio/aFreeRDP/build.gradle the following lines:

```gradle
plugins {
    // id 'com.gladed.androidgitversion' version '0.4.4'
}

// androidGitVersion {
//     abis = ['armeabi':1, 'armeabi-v7a':2, 'arm64-v8a':3, 'mips':5, 'mips64':6, 'x86':8, 'x86_64':9 ]
//     prefix ''
// }

// println 'Version Name: ' + androidGitVersion.name()
// println 'Version Code: ' + androidGitVersion.code()

apply plugin: 'com.android.application'
android {
    compileSdkVersion = rootProject.ext.compileApi
    buildToolsVersion = rootProject.ext.toolsVersion

    defaultConfig {
        applicationId "com.freerdp.afreerdp"
        minSdkVersion rootProject.ext.minApi
        targetSdkVersion rootProject.ext.targetApi
        vectorDrawables.useSupportLibrary = true
        // versionName = androidGitVersion.name()
        // versionCode = androidGitVersion.code()
    }

    // signingConfigs {
    //     release {
    //         storeFile file(RELEASE_STORE_FILE)
    //         storePassword RELEASE_STORE_PASSWORD
    //         keyAlias RELEASE_KEY_ALIAS
    //         keyPassword RELEASE_KEY_PASSWORD
    //         storeType "jks"
    //     }
    // }

    buildTypes {
        release {
            minifyEnabled false
            // signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
        debug {
            jniDebuggable true
            renderscriptDebuggable true
        }
    }
}

dependencies {
    implementation project(':freeRDPCore')
}
```

**Comment by aaagab** [comment]
> ![image](https://private-user-images.githubusercontent.com/63531314/359381327-7816ffed-ab0a-482d-a42d-de7ef13ba891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNTA2NjgsIm5iZiI6MTcyODI1MDM2OCwicGF0aCI6Ii82MzUzMTMxNC8zNTkzODEzMjctNzgxNmZmZWQtYWIwYS00ODJkLWE0MmQtZGU3ZWYxM2JhODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDIxMzI0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4MjUxOWZmYTE5YWE4Y2FmMDkyNmQ5ZGVhMDVlNjJlNmJkOTU3ZGFkYTIyMmNhNmZhYWZmNjUwODI4M2M2ZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qwQZEKiQxNDg7TsYKsHeVXt7bfs4lHX-IW95hrvtI1o) update version '0.4.14' fix Could not find com.android.tools.build:gradle:2.3.3

Your fix is better than my workaround, thanks
