### ISSUE TITLE
SDL: missing keys for FR_ca keyboard layout and probably other non-english layouts

### ISSUE THREAD

**Issue by bassdr** [FreeRDP/FreeRDP#10550]
**Describe the bug**
I'm using a Canadian French keyboard layout on both my linux client and my remote windows machine, and some keys are not sent when using SDL2's implementation of freerdp. It works with X11. Some accented letters (`à`, `ù` and backtick) takes two keys to produce, and neither the "silent" backtick (`) nor the actual letter key is sent thru rdp, so I can't type any accented letter.

**To Reproduce**
1. Setup your local machine keyboard to Canadian French
2. Start a sdl2-freerdp session
3. Type à or ù (that would be single-quote (`'`) key followed by the A key on a US keyboard)
4. Nothing is sent in freerdp

**Expected behavior**
Keys are sent thru RDP

**NOTE**
I'll activate WITH_DEBUG_SDL_KBD_EVENTS and see what happens tomorrow. I'm quite sure it's one of the `ENTRY(SDL_SCANCODE_LANG1, RDP_SCANCODE_UNKNOWN)` that breaks the layout, but I'm not familiar with the code.

**Application details**
* FreeRDP version 3.8.0
* `sdl2-freerdp /audio /gfx /multimon /u:<email> /d: /v:<remote-PC>`
* Output of `xfreerdp /buildconfig`
```
This is FreeRDP version 3.8.0 (3.8.0)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_BINARY_VERSIONING=OFF WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CJSON_REQUIRED=OFF WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL2=ON WITH_CLIENT_SDL3=OFF WITH_CLIENT_SDL_AVAILABLE=1 WITH_CLIENT_SDL_VERSIONED=ON WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=ON WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FDK_AAC=ON WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FULL_CONFIG_PATH=OFF WITH_FUSE=ON WITH_GFX_FRAME_DUMP=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_JSONC_REQUIRED=OFF WITH_JSON_DISABLED=OFF WITH_KEYBOARD_LAYOUT_FROM_FILE=OFF WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LIBSYSTEMD=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=ON WITH_OPAQUE_SETTINGS=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OPUS=ON WITH_OSS=OFF WITH_PCSC=OFF WITH_PKCS11=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SDL_IMAGE_DIALOGS=ON WITH_SDL_LINK_SHARED=ON WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=ON WITH_SSE2=OFF WITH_SWSCALE=ON WITH_SYSTEMD=OFF WITH_THIRD_PARTY=OFF WITH_TIMEZONE_COMPILED=ON WITH_TIMEZONE_FROM_FILE=OFF WITH_TIMEZONE_ICU=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=ON WITH_WEBVIEW_QT=OFF WITH_WEBVIEW_QT6=ON WITH_WINPR_DEPRECATED=OFF WITH_WINPR_JSON=ON WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:               -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer
Compiler:            GNU, 13.3.1
Target architecture: 
CONFIGURATION FILE

  The SDL client supports some user defined configuration options.
  Settings are stored in JSON format
  The location is a per user file. Location for current user is /home/david/.config/freerdp/sdl-freerdp.json
  The XDG_CONFIG_HOME environment variable can be used to override the base directory.

  The following configuration options are supported:

    SDL_KeyModMask
      Defines the key combination required for SDL client shortcuts.
      Default KMOD_RSHIFT
      An array of SDL_Keymod strings as defined at https://wiki.libsdl.org/SDL2/SDL_Keymod

    SDL_Fullscreen
      Toggles client fullscreen state.
      Default SDL_SCANCODE_RETURN.
      A string as defined at https://wiki.libsdl.org/SDL2/SDLScancodeLookup

    SDL_Resizeable
      Toggles local window resizeable state.
      Default SDL_SCANCODE_R.
      A string as defined at https://wiki.libsdl.org/SDL2/SDLScancodeLookup

    SDL_Grab
      Toggles keyboard and mouse grab state.
      Default SDL_SCANCODE_G.
      A string as defined at https://wiki.libsdl.org/SDL2/SDLScancodeLookup

    SDL_Disconnect
      Disconnects from the RDP session.
      Default SDL_SCANCODE_D.
      A string as defined at https://wiki.libsdl.org/SDL2/SDLScancodeLookup
```
* OS version connecting to (server side): Windows 11
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

**Environment (please complete the following information):**
 - OS: Linux 
 - Version/Distribution: Gentoo with custom 3.8.0 ebuild
 - Architecture: tried on both arm64 rpi4 and x86_64

**Comment by akallabeth** [comment]
that might actually be a `SDL2` bug.
can you check with a build with `-DWITH_DEBUG_SDL_KBD_EVENTS=ON` set? (that prints out all key events received from `SDL` so don´t use in production, just for testing ;))

**Comment by bassdr** [comment]
The "silent" does not trigger any debug keyboards events, `sdl_scancode_to_rdp` does not get called at all. Either it's a bug in SDL2 like you suggest, or `keyboard_handle_event` is not setup properly. Maybe there is a way to force SDL to grab the "raw" keyboard keys and let the remote deal with the layout? I'll continue my investigations when I get the chance...

Also, I do not have a SDL3 setup (it's not in Gentoo yet AFAICS), would it worth trying if this bug exists there? Is FreeRDP's SDL2 implementation gonna die in favor of SDL3's when it is (more?) stable?

**Comment by bassdr** [comment]
OK so after investigating a little more, and writing a small SDL2 keylogger, it definietly looks like a bug between my window manager (LXQT/X11) and SDL2.

 - SDL_KEYDOWN is never sent for those keys, no matter how I poll
 - SDL_TEXTINPUT is sent tho, but only once for the letter `à` for exemple... I am not sure if we could do something about that...

I can't think of a way to force the keyboard layout for the SDL process, at least none that I found are cross-platform. From my understanding SDL3 will have the same problem, did not try.

**Comment by akallabeth** [comment]
@bassdr if the keys are some combined symbols that are handled by your window manager (or whatever does that) then there is not really something we can change.
we can only map events we can intercept.

**Comment by bassdr** [comment]
@akallabeth you are right, I experimented a bit and it's a SDL bug, maybe fixed in SDL3 (not sure). All threads I found suggested ditching sdl's input system and use os/dm specific input system. I tested qt's and it works fine, but that would mean additional dependencies...
I can't find the threads I was reading right now. Sorry.
