### ISSUE TITLE
Use-of-uninitialized-value in function `WLog_PrintMessageVA()`

### ISSUE THREAD

**Issue by skorpion98** [FreeRDP/FreeRDP#10557]
**Describe the bug**
We found a use-of-uninitialized-value bug in function `WLog_PrintMessageVA()` after testing one of the harnesses provided on the OSS-Fuzz repository (TestFuzzCoreClient).
https://github.com/FreeRDP/FreeRDP/blob/de5b7c8e429ea7e9bd005dd4a4484ae9c77de6e9/winpr/libwinpr/utils/wlog/wlog.c#L376-L377

Given that the error originates from a subsequent call to `vsnprintf()`, after a brief static analysis of the code, we think that the uninitialised value could either be the “message.FormatString” variable or one of the many args passed as parameters to the formatted string.

We cannot provide more info on the error as the binary seems to be compiled, by default, without debugging symbols and our attempts to add them were unsuccessful.
We are confident that developers with knowledge on the codebase will be able to find the root of the issue with little effort, but we remain available to assist you in case of need.

The program has been tested on the standard Docker image provided on OSS-Fuzz using Ubuntu 20.04, providing AFL++ as fuzzing engine and build flag `--sanitizer=none`.

The hash commit used to perform the tests is `5aff241`.

**To Reproduce**
In the [attached archive](https://github.com/user-attachments/files/16870217/freerdp_msan.zip) you will find:
- the executable on which we performed our tests
- the input file that caused the bug
- the output of Valgrind confirming our finding

To reproduce the errors, a memory safety tool is required to expose the bug.
Run the given binary with the testcase files inside Valgrind with a command like `valgrind ./TestFuzzCoreClient /path_to_testcases/input`.

**Environment**
- OS: Linux
- Version/Distribution: Ubuntu 20.04
- Architecture: x86_64

**Comment by akallabeth** [comment]
@skorpion98 interesting enough, I´ve just build the same commit with fuzzers and your input data (converted with `xxd -i -n foo filename >foo.h`) to run the test and it did not fail nor did it reveal uninitialized data.

as for debugging symbols, just build it as `CMAKE_BUILD_TYPE=Debug`?

**Comment by skorpion98** [comment]
Hello,
Thanks for the prompt answer. 

We see from OSS-Fuzz that you did not enable MSan for your project, that would detect this kind of issues, which could explain why you never detected an error like this. 

Regarding this issue, we detected it with a new approach, strictly related to fuzzing. Can you confirm that by simply feeding the input we provided in the binary we gave in the archive, valgrind detects an error? Does it change if you use the binary file you generated on your own?

**Comment by akallabeth** [comment]
@skorpion98 ok, true, we did not enable it as we get way too many false positives from dependent libraries (openssl, ...)
I also just realized I get one if I compile the SDL client in `convert_res_to_c.cpp:165` - which is definitely wrong as argv contains a value there...

don´t have spare hardware here to run your binary (sorry, not running stuff I did not compile myself ;))
but with the library and openssl compiled with `-fsanitize=memory ` I only get stuff from `drbg_ctr_generate` - which is kind of expected
