### ISSUE TITLE
not able to run the application

### ISSUE THREAD

**Issue by Pushpan80** [FreeRDP/FreeRDP#10589]
@akallabeth Could you please help me to run the application I am getting below error:
Could not find com.android.tools.build:gradle:2.3.3.
Searched in the following locations:
  - https://plugins.gradle.org/m2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
Required by:
    project :aFreeRDP > com.gladed.androidgitversion:com.gladed.androidgitversion.gradle.plugin:0.4.4 > gradle.plugin.com.gladed.gradle.androidgitversion:gradle-android-git-version:0.4.4
    thank you in advance

**Comment by akallabeth** [comment]
not without more information.
the error does not occur on our branches so I have no idea what you try to build (and from which version that branched)

**Comment by Pushpan80** [comment]
@akallabeth  I have taken pull from master and try to run the application getting error> Configure project :
----------------- Project configuration -------------------
RELEASE_STORE_FILE: nokeyfile
RELEASE_KEY_ALIAS:  
compile API:        31
target API:         31
min API:            23
tools version:      31.0.0
-----------------------------------------------------------

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':aFreeRDP'.
> Could not resolve all files for configuration ':aFreeRDP:classpath'.
   > Could not find com.android.tools.build:gradle:2.3.3.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
