### ISSUE TITLE
Black screen when connecting to a remote machine due to a libfreerdp2 error

### ISSUE THREAD

**Issue by manuelbuil** [FreeRDP/FreeRDP#10592]
**Found a bug? - We would like to help you and smash the bug away.**
1. __Please don't "report" questions as bugs. For these (questions/build instructions/...) please use one of the following means of contact:__
   * We are reachable via:
    * Matrix room : #FreeRDP:matrix.org (main)
    * XMPP channel: #FreeRDP#matrix.org@matrix.org (bridged)
    * IRC channel : #freerdp @ irc.oftc.net (bridged)
   * We are reachable via mailing list <freerdp-devel@lists.sourceforge.net>
   * Try our mailing list for discussions/questions
1. Before reporting a bug have a look into our issue tracker to see if the bug was already reported and you can add some additional information.
1. If it's a __new__ bug - create a new issue.
1. For more details see https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Describe the bug**

I am using freerdp via the Vinagre package in my recently installed OpenSUSE Leap 15.6 Linux. The versions are:
```
libfreerdp2-2-2.11.2-150600.4.3.1.x86_64
vinagre-3.22.0-bp156.4.7.x86_64
```

I start vinagre, provide the RDP details to connect to a Windows machine and then I click on connect. Then I get a black screen with a colorful first line. If I check the journalctl logs, I see:
```
Sep 11 16:46:38 localhost.localdomain vinagre.desktop[14878]: [16:46:38:698] [14878:14878] [WARN][com.freerdp.crypto] - Certificate verification failure 'self-signed certificate (18)' at stack position 0
Sep 11 16:46:38 localhost.localdomain vinagre.desktop[14878]: [16:46:38:698] [14878:14878] [WARN][com.freerdp.crypto] - CN = mbuil-windows
Sep 11 16:46:42 localhost.localdomain gnome-character[14808]: JS LOG: Characters Application exiting
Sep 11 16:46:42 localhost.localdomain dleyna-renderer-service[14867]: Client :1.375 lost
Sep 11 16:46:43 localhost.localdomain dleyna-renderer-service[14867]: dLeyna: Exit
Sep 11 16:46:43 localhost.localdomain vinagre[14878]: Theme parsing error: <data>:2:28: The style property GtkButton:default-border is deprecated and shouldn't be used anymore. It will be removed in a future version
Sep 11 16:46:43 localhost.localdomain vinagre[14878]: Theme parsing error: <data>:3:36: The style property GtkButton:default-outside-border is deprecated and shouldn't be used anymore. It will be removed in a future version
Sep 11 16:46:43 localhost.localdomain vinagre[14878]: Theme parsing error: <data>:4:25: The style property GtkButton:inner-border is deprecated and shouldn't be used anymore. It will be removed in a future version
Sep 11 16:46:43 localhost.localdomain vinagre[14878]: Theme parsing error: <data>:5:30: The style property GtkWidget:focus-line-width is deprecated and shouldn't be used anymore. It will be removed in a future version
Sep 11 16:46:43 localhost.localdomain vinagre[14878]: Theme parsing error: <data>:6:27: The style property GtkWidget:focus-padding is deprecated and shouldn't be used anymore. It will be removed in a future version
Sep 11 16:46:44 localhost.localdomain vinagre.desktop[14878]: [16:46:44:274] [14878:14878] [ERROR][com.freerdp.core.update] - [0x05] Cache Bitmap V2 (Compressed) - SERVER BUG: The support for this feature was not announced! Use /relax-order-checks to ignore
Sep 11 16:46:44 localhost.localdomain vinagre.desktop[14878]: [16:46:44:274] [14878:14878] [WARN][com.freerdp.core.update] - Adding +bitmap-cache might mitigate
Sep 11 16:46:44 localhost.localdomain vinagre.desktop[14878]: [16:46:44:274] [14878:14878] [ERROR][com.freerdp.core.update] - order flags 03 failed
Sep 11 16:46:44 localhost.localdomain vinagre.desktop[14878]: [16:46:44:274] [14878:14878] [ERROR][com.freerdp.core.fastpath] - Fastpath update Orders [0] failed, status 0
Sep 11 16:46:44 localhost.localdomain vinagre.desktop[14878]: [16:46:44:274] [14878:14878] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update() - -1
Sep 11 16:46:44 localhost.localdomain vinagre.desktop[14878]: [16:46:44:274] [14878:14878] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
Sep 11 16:46:44 localhost.localdomain vinagre.desktop[14878]: [16:46:44:274] [14878:14878] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
Sep 11 16:46:44 localhost.localdomain vinagre[14878]: Failed to check FreeRDP file descriptor
```

**To Reproduce**
Already explained

**Expected behavior**

I except to connect to the remote machine and see its UI

**Screenshots**

**Application details**
* FreeRDP version (`xfreerdp /version`): libfreerdp2-2-2.11.2
* Command line used
* Output of `xfreerdp /buildconfig`
* OS version connecting to (server side): Windows 2022
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]: Linux 
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10] openSUSE Leap 15.6
 - Architecture: [amd64, arm]: amd64
 - kernel: 6.4.0-150600.23.17-default

**Additional context**

** Please remove this text before submitting your issue!

_Thank you for reporting a bug!_

**Comment by akallabeth** [comment]
this is a vinagre bug (wrong configuration settings) and the project is retired, see https://gitlab.gnome.org/Archive/vinagre
