### ISSUE TITLE
Trying to connect to wfreerdp-server, disconnected every time.

### ISSUE THREAD

**Issue by jpippy** [FreeRDP/FreeRDP#1059]
I am trying to connect to the wfreerdp-server with the FreeRDP android client. Although everytime I do so it starts connecting and then disconnects. I don't think it is getting past authentication or something. I have attached an image to show what the server is outputting.

![faultscreenshot](https://f.cloud.github.com/assets/3783465/234174/c43cbb94-876b-11e2-95c0-32c11fe01aea.png)

I have no idea what the problem is or how to fix it.

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
