### ISSUE TITLE
how to use freerdp-server? it seems that some file is missing

### ISSUE THREAD

**Issue by macarthor** [FreeRDP/FreeRDP#1060]
Hi,

I've been testing xfreerdp-server recently. it ever fail to connect. the detailed information is as follows:

root@ubtvm:~# /home/freerdp/usr/bin/xfreerdp-server 
Listening on 0.0.0.0 port 3389.
bind: Address already in use
We've got a client 10.190.50.53
Client Security: NLA:1 TLS:1 RDP:0
Server Security: NLA:1 TLS:1 RDP:1
Negotiated Security: NLA:1 TLS:0 RDP:0
private key file: /root/.freerdp/server/server.key
SSL_CTX_use_RSAPrivateKey_file failed
Failed to check freerdp file descriptor
Client 10.190.50.53 disconnected.

I traced the code, error is at libfreerdp\crypto\tls.c:

printf("private key file: %s\n", privatekey_file);
if (SSL_CTX_use_RSAPrivateKey_file(tls->ctx, privatekey_file, SSL_FILETYPE_PEM) <= 0)
{
    printf("SSL_CTX_use_RSAPrivateKey_file failed\n");
    return FALSE;
}

the argument "privatekey_file" is /root/.freerdp/server/server.key, but this file does not exist.

i wonder if i should use some command to generate this file before starting xfreerdp-server?

**Comment by believeyourself** [comment]
@macarthor Hi. I followed all the steps you have mentioned for setting up xfreerdp-server in linux. However at last I am unable to start the server by using the command  xfreerdp-server . I am getting command not found.

**Comment by macarthor** [comment]
@believeyourself what's the full path of you xfreerdp-server binary? is it marked with executable? it seems you are a newbie of linux :)

try:
1. sudo chmod +x /full/path/to/xfreerdp-server, and
2. sudo vim /etc/ld.conf.d/freerdp.conf, and add /full/path/to/xfreerdp-server/lib/i386-xxx, and
3. sudo ldconfig, and
4. /full/path/to/xfreerdp-server <any options you want>, and
5. done

**Comment by mailinglists35** [comment]
is there any way to authenticate using standard linux users, not via external SAM file?

**Comment by nekohayo** [comment]
With the 2.0 release, assuming freeRDP provides a RDP server for Linux for Xorg and/or Wayland, it would be really nice to document this. There's a "freerdp-server" 2.0.0 package available in Fedora, and it provides no binary nor systemd service/unit, and I couldn't find any documentation on how to make that work.

I tried xrdp/xorgxrdp also (which I understand is a separate project, but I'm just mentioning it here) and had zero luck there too.

I'm hoping in the future I can use FreeRDP for my "remote desktop into a Fedora or Centos Linux workstation with something that isn't VNC or X2go" needs. I don't know what the status of readiness of the code/implementation is for freerdp-server, but if it's already supposed to work, the lack of documentation (looked at every wiki, README, and websites I could find) is very confusing to say the least :)

**Comment by akallabeth** [comment]
@nekohayo the binaries in freerdp are mostly samples (shadow and proxy are complete)
A Rdp server on linux that uses freerdp is ogon (ogon-project here on github)

**Comment by akallabeth** [comment]
Oh, and your problem is you need to create a certificate for the server ;)

**Comment by inukaze** [comment]
Hi there i am using Slackware64 14.2 i had download the files from https://slackbuilds.org/repository/14.2/network/freerdp/?search=freerdp

i had edit the freerdp.slackbuild file the follow section : 

#ORIGINAL :
```
mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS $(pkg-config --cflags gstreamer-base-1.0)" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_CUPS=ON \
    -DWITH_FFMPEG=$WITH_FFMPEG \
    -DWITH_LIBSYSTEMD=OFF \
    -DWITH_WAYLAND=OFF \
    -DWITH_PULSE=ON \
    -DCMAKE_BUILD_TYPE=Release ..
  make VERBOSE=1
  make install DESTDIR=$PKG
cd ..
```

#Edited by myself : 
```
mkdir -p build
cd build
  cmake \
    -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS $(pkg-config --cflags gstreamer-base-1.0)" \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_CUPS=ON \
    -DWITH_SERVER=ON \
    -DWITH_SAMPLE=ON \
    -DWITH_FFMPEG=$WITH_FFMPEG \
    -DWITH_LIBSYSTEMD=OFF \
    -DWITH_WAYLAND=OFF \
    -DWITH_PULSE=OFF \
    -DCMAKE_BUILD_TYPE=Release ..
  make VERBOSE=1
  make install DESTDIR=$PKG
cd ..
```

Notes : 
1 - I had upgrade the ffmpg manually and i had that dependecy solved

2 - I don't use : Avahi, PulseAudio neither SystemD because i just don't like because come very Slowpoke my system.

3 - A lot of sites says things like :
```
copy server/X11/server.crt and server.key to ~/.config/freerdp/server/


Issue #600 - server certificates - this requires server.crt and server.key to be in ~/.freerdp/server

 cd ./server/X11/
 mkdir -p ~/.freerdp/server
 cp server.* ~/.freerdp/server
./xfreerdp-server
```

And well i had a dunnos, at the point 3
A) what is the full path of that file? 
because on the source code that files are not included, neither had a explaniation how i can make it.

B) how the user can make own and valid key file and certified file for use the server ?

C) why that lot of copy relative path with server.{crt,key} can't don't exist in the source code of git, the Slackbuild Source ? i really need generate that file because when i try to connect for my own freerdp-server i notice in the terminal the follow : 

```
[00:32:01:073] [13928:13929] [INFO][com.freerdp.primitives] - primitives autodetect, using generic
[00:32:01:205] [13928:13929] [ERROR][com.freerdp.core] - unable to open RSA key file server.key: No such file or directory.
[00:32:01:205] [13928:13929] [ERROR][com.freerdp.core.peer] - invalid RDP key file server.key
[00:32:01:205] [13928:13929] [INFO][com.freerdp.server.sample] - We've got a client 192.168.1.27
[00:32:01:205] [13928:13929] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
[00:32:01:205] [13928:13929] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:1
[00:32:01:205] [13928:13929] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
[00:32:01:206] [13928:13929] [ERROR][com.freerdp.crypto] - BIO_new_file failed for private key server.key
```

**Comment by inukaze** [comment]
Well i try the follow : 

```
mkdir -p ~/.config/freerdp/server

ssh-keygen -f ~/.config/freerdp/server/server.key -t rsa -b 4096

ssh-keygen -s ~/.config/freerdp/server/server.key -I "$USER"@"$HOSTNAME" ~/.config/freerdp/server/server.key.pub ; cp ~/.config/freerdp/server/server.key.pub ~/.config/freerdp/server/server.key-cert.pub server.crt
```

After i try to connect from another machine from Remmina i got the follow message : 

"Error connecting to RDP server «IP». TLS connection failed. Check that client and server support a common TLS version."

On the terminal output the follow i notice

```
[01:13:49:578] [14440:14482] [INFO][com.freerdp.server.sample] - We've got a client 192.168.1.17
[01:13:49:578] [14440:14482] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
[01:13:49:578] [14440:14482] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:1
[01:13:49:578] [14440:14482] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
[01:13:49:579] [14440:14482] [ERROR][com.freerdp.crypto] - invalid certificate
```

Well i suppose i need another way from make the configuration with TLS the server/client needs for make the connection works fine.

By the moment i don't have ideas for solve it.

**Comment by inukaze** [comment]
Someday the browsers can edit on this site (really i don't know why never works try to edit)

Well my last try was :

```
mkdir -p ~/.config/freerdp/server
cd ~/.config/freerdp/server
ssh-keygen -f ~/.config/freerdp/server/server.key -t rsa -b 4096
openssl genrsa -des3 -out private.pem 2048
openssl rsa -in private.pem -outform PEM -pubout -out public.pem
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:4096 -keyout private.pem -out server.crt
```

and the terminal output :
```
02:26:26:260] [16130:16130] [INFO][com.freerdp.core.listener] - Listening on 0.0.0.0:3389
[02:26:26:260] [16130:16130] [INFO][com.freerdp.core.listener] - Listening on socket /tmp/tfreerdp-server.3389.
[02:26:30:278] [16130:16136] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[02:26:30:328] [16130:16136] [INFO][com.freerdp.server.sample] - We've got a client 192.168.1.17
[02:26:30:328] [16130:16136] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
[02:26:30:328] [16130:16136] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:1
[02:26:30:328] [16130:16136] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
```

Well this looks like is most near the server expect, but i don't understand why "TLS" and i don't idea how make keys + cert with rsa & tls using (open)ssl3

**Comment by akallabeth** [comment]
@inukaze what are you trying to do? the sample server expects these files in the current work directory (the one you start from) but it will just show you a window with a fancy mouse cursor.

**Comment by inukaze** [comment]
@akallabeth : i just trying to start a freerdp server, but does not exist any sample configuration file or the key file the server expect, because of that i try to generate one compatible with the freerdp server to start it.

**Comment by akallabeth** [comment]
@inukaze you know what a ssl key and certificate is? `winpr-makecert` is wrapping that to some extent, but normal `openssl` stuff works too

**Comment by inukaze** [comment]
@akallabeth : yes i know, well the openssl looks like compatible, but if i try to connect, i just got and error says TLS is not compatible.

**Comment by akallabeth** [comment]
@inukaze ok, rereading the thread, I think I get we´re talking about different things.
The `TLS` in `Client Security: NLA:1 TLS:1 RDP:0` is for `RDP` authentication modes:

1. `NLA` means you send the credentials before connection
2. `TLS` means you establish a `SSL/TLS` connection anonymously and you are presented with a login screen in the RDP connection
3. `RDP` is the same as `TLS` just without the encryption (very very old stuff)

**Comment by inukaze** [comment]
@akallabeth : Thank you very much for the information and specifications
