### ISSUE TITLE
bundle-mac-os.sh fails: ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by AlexanderProd** [FreeRDP/FreeRDP#10611]
**Describe the bug**
When I try to build the native macOS client, im getting the following error: 

```
ninja: build stopped: subcommand failed.
```

The error happens during this step: 

```
cmake -GNinja -Bfreerdp -S"$SCRIPT_PATH/.." \
	$CMAKE_ARGS \
	-DWITH_PLATFORM_SERVER=OFF \
	-DWITH_NEON=ON \
	-DWITH_SSE=ON \
	-DWITH_FFMPEG=OFF \
	-DWITH_SWSCALE=ON \
	-DWITH_OPUS=ON \
	-DWITH_WEBVIEW=OFF \
	-DWITH_FAAD2=ON \
	-DWITH_FAAC=ON \
	-DWITH_INTERNAL_RC4=ON \
	-DWITH_INTERNAL_MD4=ON \
	-DWITH_INTERNAL_MD5=ON
cmake --build freerdp
cmake --install freerdp
```

I've used commit hash 073f1ee642827a97d549d7760dfaf14501b72235 

**To Reproduce**
1. clone the repo
2. navigate to scripts directory
3. run `./bundle-mac-os.sh`

**Expected behavior**
build works 

**Screenshots**

**Environment (please complete the following information):**
 - OS: macOS
 - Version/Distribution: 15.0
 - Architecture: arm

**Additional context**
I've attached the whole [log.txt](https://github.com/user-attachments/files/17013196/log.txt).

**Comment by akallabeth** [comment]
there seem to be some include paths messing with your build:
```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DFREERDP_EXPORTS -DUSE_EXECINFO -DUSE_UNWIND -DWINPR_CRITICAL_SECTION_DISABLE_SPINCOUNT -          DWINPR_EXPORTS -DWINPR_TIMEZONE_FILE=\"/var/db/zoneinfo\" -DWITH_JSONC -DWITH_OPENSSL -DWITH_PKCS11 -DWITH_SMARTCARD_EMULATE -DWITH_SMARTCARD_PCSC -DWITH_TIMEZONE_COMPILED -                 DWITH_URIPARSER -DWITH_VERBOSE_WINPR_ASSERT -D_DARWIN_C_SOURCE -D_POSIX_C_SOURCE=200809L -Dwinpr_EXPORTS -I/Users/alexanderhoerl/Developer/FreeRDP/winpr/include -I/Users/alexanderhoerl/     Developer/FreeRDP/scripts/build/freerdp/winpr/include -I/Users/alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils -I/opt/homebrew/Cellar/json-c/0.17/include/json-c -I/Users/              alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils/. -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks -      isystem /Users/alexanderhoerl/Developer/FreeRDP/scripts/install/MacFreeRDP.app/Contents/include -Weverything -Wall -Wpedantic -Wno-padded -Wno-switch-enum -Wno-cast-align -Wno-declaration-  after-statement -Wno-unsafe-buffer-usage -Wno-reserved-identifier -Wno-covered-switch-default -Wno-c11-extensions -Wno-gnu -fno-omit-frame-pointer -DWINPR_DLL -O3 -DNDEBUG -std=gnu11 -arch  x86_64 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -mmacosx-version-min=12 -fPIC -MD -MT winpr/libwinpr/         CMakeFiles/winpr.dir/utils/json/json.c.o -MF winpr/libwinpr/CMakeFiles/winpr.dir/utils/json/json.c.o.d -o winpr/libwinpr/CMakeFiles/winpr.dir/utils/json/json.c.o -c /Users/alexanderhoerl/   Developer/FreeRDP/winpr/libwinpr/utils/json/json.c
 /Users/alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils/json/json.c:30:10: fatal error: 'json-c/json.h' file not found
 #include <json-c/json.h> 
          ^~~~~~~~~~~~~~~
          ```

**Comment by AlexanderProd** [comment]
> there seem to be some include paths messing with your build:
> 
> ```
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DFREERDP_EXPORTS -DUSE_EXECINFO -DUSE_UNWIND -DWINPR_CRITICAL_SECTION_DISABLE_SPINCOUNT -          DWINPR_EXPORTS -DWINPR_TIMEZONE_FILE=\"/var/db/zoneinfo\" -DWITH_JSONC -DWITH_OPENSSL -DWITH_PKCS11 -DWITH_SMARTCARD_EMULATE -DWITH_SMARTCARD_PCSC -DWITH_TIMEZONE_COMPILED -                 DWITH_URIPARSER -DWITH_VERBOSE_WINPR_ASSERT -D_DARWIN_C_SOURCE -D_POSIX_C_SOURCE=200809L -Dwinpr_EXPORTS -I/Users/alexanderhoerl/Developer/FreeRDP/winpr/include -I/Users/alexanderhoerl/     Developer/FreeRDP/scripts/build/freerdp/winpr/include -I/Users/alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils -I/opt/homebrew/Cellar/json-c/0.17/include/json-c -I/Users/              alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils/. -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks -      isystem /Users/alexanderhoerl/Developer/FreeRDP/scripts/install/MacFreeRDP.app/Contents/include -Weverything -Wall -Wpedantic -Wno-padded -Wno-switch-enum -Wno-cast-align -Wno-declaration-  after-statement -Wno-unsafe-buffer-usage -Wno-reserved-identifier -Wno-covered-switch-default -Wno-c11-extensions -Wno-gnu -fno-omit-frame-pointer -DWINPR_DLL -O3 -DNDEBUG -std=gnu11 -arch  x86_64 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -mmacosx-version-min=12 -fPIC -MD -MT winpr/libwinpr/         CMakeFiles/winpr.dir/utils/json/json.c.o -MF winpr/libwinpr/CMakeFiles/winpr.dir/utils/json/json.c.o.d -o winpr/libwinpr/CMakeFiles/winpr.dir/utils/json/json.c.o -c /Users/alexanderhoerl/   Developer/FreeRDP/winpr/libwinpr/utils/json/json.c
>  /Users/alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils/json/json.c:30:10: fatal error: 'json-c/json.h' file not found
>  #include <json-c/json.h> 
>           ^~~~~~~~~~~~~~~
>           ```
> ```

I'm wondering why this is the case, since I have libjson-c installed using homebrew, and it also found the correct path at `/opt/homebrew/Cellar/json-c/0.17/include/json-c`

**Comment by akallabeth** [comment]
> > there seem to be some include paths messing with your build:
> > ```
> > /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DFREERDP_EXPORTS -DUSE_EXECINFO -DUSE_UNWIND -DWINPR_CRITICAL_SECTION_DISABLE_SPINCOUNT -          DWINPR_EXPORTS -DWINPR_TIMEZONE_FILE=\"/var/db/zoneinfo\" -DWITH_JSONC -DWITH_OPENSSL -DWITH_PKCS11 -DWITH_SMARTCARD_EMULATE -DWITH_SMARTCARD_PCSC -DWITH_TIMEZONE_COMPILED -                 DWITH_URIPARSER -DWITH_VERBOSE_WINPR_ASSERT -D_DARWIN_C_SOURCE -D_POSIX_C_SOURCE=200809L -Dwinpr_EXPORTS -I/Users/alexanderhoerl/Developer/FreeRDP/winpr/include -I/Users/alexanderhoerl/     Developer/FreeRDP/scripts/build/freerdp/winpr/include -I/Users/alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils -I/opt/homebrew/Cellar/json-c/0.17/include/json-c -I/Users/              alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils/. -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/System/Library/Frameworks -      isystem /Users/alexanderhoerl/Developer/FreeRDP/scripts/install/MacFreeRDP.app/Contents/include -Weverything -Wall -Wpedantic -Wno-padded -Wno-switch-enum -Wno-cast-align -Wno-declaration-  after-statement -Wno-unsafe-buffer-usage -Wno-reserved-identifier -Wno-covered-switch-default -Wno-c11-extensions -Wno-gnu -fno-omit-frame-pointer -DWINPR_DLL -O3 -DNDEBUG -std=gnu11 -arch  x86_64 -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -mmacosx-version-min=12 -fPIC -MD -MT winpr/libwinpr/         CMakeFiles/winpr.dir/utils/json/json.c.o -MF winpr/libwinpr/CMakeFiles/winpr.dir/utils/json/json.c.o.d -o winpr/libwinpr/CMakeFiles/winpr.dir/utils/json/json.c.o -c /Users/alexanderhoerl/   Developer/FreeRDP/winpr/libwinpr/utils/json/json.c
> >  /Users/alexanderhoerl/Developer/FreeRDP/winpr/libwinpr/utils/json/json.c:30:10: fatal error: 'json-c/json.h' file not found
> >  #include <json-c/json.h> 
> >           ^~~~~~~~~~~~~~~
> >           ```
> > ```
> 
> I'm wondering why this is the case, since I have libjson-c installed using homebrew, and it also found and logged the correct path at `/opt/homebrew/Cellar/json-c/0.17/include/json-c`

exactly because of that.
need to check the `CMake` search paths, `homebrew` is bad in this case as they only install platform arch binaries whereas the script builds a universal binary

**Comment by AlexanderProd** [comment]
Unfortunately I'm still getting the same error with the latest master 
[log.txt](https://github.com/user-attachments/files/17032620/log.txt)

**Comment by akallabeth** [comment]
@AlexanderProd your log is missing quite a bit, did you run with `scritp 2>&1 |tee log.txt` ?

**Comment by akallabeth** [comment]
@AlexanderProd anyhow, I think I did find the remaining bug you are experiencing:
https://github.com/FreeRDP/FreeRDP/pull/10626 should fix the preference between `cJSON` and `json-c` libraries.

**Comment by AlexanderProd** [comment]
@akallabeth No, I had just copied it from my terminal, but I will try your fix branch swiftly.

**Comment by SaubaanHsn** [comment]
> @akallabeth No, I had just copied it from my terminal, but I will try your fix branch swiftly.

Hey Alexander, im running into similar issues, were you able to solve this issue?

**Comment by AlexanderProd** [comment]
@SaubaanHsn 
Yeah the problem has been fixed for me with the merge request #10626 that had been merged into the master.

**Comment by AlexanderProd** [comment]
@SaubaanHsn how have to clone the whole repository not just the script. And then run the script from within the cloned directory. Also I’ve had to install some dependencies using homebrew, but those have been stated while the script ran.

**Comment by SaubaanHsn** [comment]
Are you running the script via the scripts folder or did you move it someplace else in the cloned github? 

Also did you have to make your own cmakelists.txt file? for some reason it is looking for the cmakelists file on my desktop.

**Comment by AlexanderProd** [comment]
@SaubaanHsn I think I ran the script from within the root of the cloned repository, so directly inside the cloned folder. I didn’t have to create any cmakelists file.

**Comment by AlexanderProd** [comment]
@SaubaanHsn maybe I ran it from inside the scripts directory, I don’t remember it completely. Also I didn’t have to edit the script in any way.

**Comment by akallabeth** [comment]
@SaubaanHsn this sounds like you did not start from a fresh checkout?
remove your current one and start fresh, that most likely resolves that.

**Comment by SaubaanH** [comment]
> @SaubaanHsn this sounds like you did not start from a fresh checkout? remove your current one and start fresh, that most likely resolves that.

I see i have been doing it all in a new folder on my desktop (cloning the github and running the script). Should i be moving the script to the root of the freerdp folder and then running it or should i leave it in the scripts folder and run it there?. I consistently get the Cmaketext file error

**Comment by akallabeth** [comment]
@SaubaanH no.
please post a log of your build. Create with `./scripts/bundle-mac-os.sh 2>&1 |tee log.txt`

**Comment by SaubaanH** [comment]
> @SaubaanH no. please post a log of your build. Create with `./scripts/bundle-mac-os.sh 2>&1 |tee log.txt`

Hey so i tried running that and the script ran but when opening the app it doesnt open and automatically crashes. 

Here is the log[
[FreeRDPlog.txt](https://github.com/user-attachments/files/17122960/FreeRDPlog.txt)
](url)

**Comment by akallabeth** [comment]
@SaubaanH 
1. why? why do you run the whole ting with `sudo`? Are you asking for trouble?
2. define crash, you just added the build log, not an actual freerdp execution log

**Comment by SaubaanH** [comment]
> @SaubaanH
> 
> 1. why? why do you run the whole ting with `sudo`? Are you asking for trouble?
> 2. define crash, you just added the build log, not an actual freerdp execution log

I see, I am relatively new to programming and didnt think that would be an issue. The MacFreeRDP.app is crashing for me, where would i be able to find the execution logs? the following is what happens when I try opening the .app file 
<img width="932" alt="Screenshot 2024-09-24 at 11 06 23 PM" src="https://github.com/user-attachments/assets/ab1e4097-41c7-4e2c-ac9f-3cd99a125882">

**Comment by SaubaanH** [comment]
> > @SaubaanH
> > 
> > 1. why? why do you run the whole ting with `sudo`? Are you asking for trouble?
> > 2. define crash, you just added the build log, not an actual freerdp execution log
> 
> I see, I am relatively new to programming and didnt think that would be an issue. The MacFreeRDP.app is crashing for me, where would i be able to find the execution logs? the following is what happens when I try opening the .app file <img alt="Screenshot 2024-09-24 at 11 06 23 PM" width="932" src="https://private-user-images.githubusercontent.com/106204098/370540268-ab1e4097-41c7-4e2c-ac9f-3cd99a125882.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMzUzMzMsIm5iZiI6MTcyNzIzNTAzMywicGF0aCI6Ii8xMDYyMDQwOTgvMzcwNTQwMjY4LWFiMWU0MDk3LTQxYzctNGUyYy1hYzlmLTNjZDk5YTEyNTg4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQwMzMwMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmZlMmVmZmU2NzQ0NjMwMWRhMjZlODdmNmE0ZjllMTk0NjM0ZGUxYWI1NTEyODI5ZmM2Njc3YWY4MjU1NzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Cz8JKIUubEuOOt9T_prn8d3srgc2ImWDDZyLxXoTmkk">

Here is the crash report if thats what you mean: 
[crashreport.txt](https://github.com/user-attachments/files/17124135/crashreport.txt)
