### ISSUE TITLE
CMake Error: PLATFORM argument not set when creating Xcode project in FreeRDP folder

### ISSUE THREAD

**Issue by Venkateshazibtek** [FreeRDP/FreeRDP#10613]
@akallabeth I installed CMake (version 3.30.3) successfully inside the FreeRDP root folder. However, when attempting to create an Xcode project, I encountered the following warning and error:

CMake Warning:
No source or binary directory provided. Both will be assumed to be the same as the current working directory, but note that this warning will become a fatal error in future CMake releases.

CMake Error:
CMake Error at cmake/ios.toolchain.cmake:204 (message):
  PLATFORM argument not set.  Bailing configure since I don't know what
  target you want to build for!
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.30.3/share/cmake/Modules/CMakeDetermineSystem.cmake:143 (include)
  CMakeLists.txt:26 (project)
  -- Configuring incomplete, errors occurred!
  
 Steps to reproduce:
1. Clone FreeRDP from GitHub.
2. Install CMake inside the FreeRDP root folder.
3. Attempt to create an Xcode project.
4. Encounter the above warning and error.

Environment:
Chip: Apple M2
macOS: Sonoma 14.3
Xcode version: 15.3

Screenshot
<img width="577" alt="Screenshot 2024-09-16 at 6 33 44 PM" src="https://github.com/user-attachments/assets/516ed926-ee6a-4952-ac03-bb0339e8d1d8">

**Comment by akallabeth** [comment]
if you are using a `CMAKE_TOOLCHAIN_FILE` you need to provide the arguments that file expects.
open it in any text editor and read the information there ;)

**Comment by Venkateshazibtek** [comment]
@akallabeth, Are you referring to the CMakeCache.txt file? I couldn't find any CMAKE_TOOLCHAIN_FILE in the FreeRDP folder.

**Comment by akallabeth** [comment]
@Venkateshazibtek look at your own screenshot and read the `CMake` configure call you did there.
Take that file you reference there and open it in any text editor.

**Comment by Venkateshazibtek** [comment]
Thank you for your response @akallabeth 
I reviewed the CMake configuration, and I am indeed building for the OS64 platform. However, I am encountering the following error:

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find FFmpeg (missing: _FFmpeg_FOUND_LIBRARIES AVUTIL_LIBRARIES AVUTIL_INCLUDE_DIRS AVUTIL_FOUND AVCODEC_LIBRARIES AVCODEC_INCLUDE_DIRS AVCODEC_FOUND AVUTIL AVCODEC)

Could you please assist me with resolving this issue and guide me on how to properly install FreeRDP for an iOS app? Thank you!
<img width="1468" alt="Screenshot 2024-09-17 at 11 35 20 AM" src="https://github.com/user-attachments/assets/083f4794-56bc-4a66-9d5d-c11ca101c443">

**Comment by akallabeth** [comment]
read https://github.com/FreeRDP/FreeRDP/wiki/Compilation and follow the compilation suggestions for dependencies.
Replace the `CMAKE_TOOLCHAIN_FILE` with the one you´re using.

I don´t do iOS builds so I also can not give any more details, but the compilation with `CMake` is the same on all platforms (except for the toolchain file)

**Comment by Venkateshazibtek** [comment]
@akallabeth, Thank you for your quick response. I reviewed the documentation and followed the steps provided, but I’m still encountering issues. I’m unable to create the iOS project.

**Comment by Kaushu1999** [comment]
I am an iOS developer and I try to make iOS applications using FreeRDP. I had previously created a project, but now I want to update it. However, when I run the CMake build, I encounter the same problem.
please guide me and give me the valuable response.


-- Git Revision 7f38019e9
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS18.2.sdk/usr/lib/libz.tbd (found version "1.2.12")
--  default symbol visibility: hidden
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /Users/rrajput/Documents/kaushal/OpenSSL-for-iPhone/bin/iPhoneOS18.2-arm64.sdk/lib/libcrypto.a (found version "1.1.1w")
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:227 (message):
  Could NOT find FFmpeg (missing: _FFmpeg_FOUND_LIBRARIES AVUTIL_LIBRARIES
  AVUTIL_FOUND AVCODEC_LIBRARIES AVCODEC_FOUND AVUTIL AVCODEC)
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:591 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFFmpeg.cmake:208 (find_package_handle_standard_args)
  CMakeLists.txt:397 (find_package)


-- Configuring incomplete, errors occurred!
rrajput@COG-SYS-072 build-ios % 

<img width="1441" height="547" alt="Image" src="https://github.com/user-attachments/assets/bb4e6b72-edf3-46e5-be6e-b5e237de08b6" />
