### ISSUE TITLE
xfreerdp Screen Corruption

### ISSUE THREAD

**Issue by zeha** [FreeRDP/FreeRDP#1062]
I see new screen corruption on master. git bisect gives me 5034ad7aa4becdd939ccf53d60ec0ee3d1fc968e as the first bad commit.

![Bad](http://dl.dropbox.com/u/5552862/xfreerdp_corruption_bad.png)
![Good](http://dl.dropbox.com/u/5552862/xfreerdp_corruption_good.png)

Note that there is screen corruption in the "good" version as well, directly under the dropdown list in the toolbar, but this must have started way earlier.

Command line used is:
/home/ch/Source/FreeRDP/build/client/X11/xfreerdp  /u:Christian /v:172.16.172.113 /size:1800x1050 -clipboard -sound

Server is WinXP Pro SP3.
xfreerdp on Linux.

**Comment by akallabeth** [comment]
Could not reproduce on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
Feel free to reopen if you still experience these issues.
