### ISSUE TITLE
Windows automatically minimizing when switching workspaces (ubuntu 24.04)

### ISSUE THREAD

**Issue by Juanfi8** [FreeRDP/FreeRDP#10632]
Hi, I'm using ubuntu 24.04 with gnome 46 and I ran into the same issue. I have the xfreerdp3 version 3.5.1, that I installed  directly from the apt repositories.  Is this an issue or could it be related to the flags i'm using? 
Thanks

_Originally posted by @Juanfi8 in https://github.com/FreeRDP/FreeRDP/issues/6701#issuecomment-2358148232_

**Comment by akallabeth** [comment]
update. fix is in 761c3a807b2 part of release 3.7.0

**Comment by Juanfi8** [comment]
Thanks, it worked (with the flatpak package, 3.8.0).Do you have any clues to make it work in wayland too? (the solution only worked in xorg for me). Thanks
