### ISSUE TITLE
Clipboard file URL supports Windows

### ISSUE THREAD

**Issue by 2fly2** [FreeRDP/FreeRDP#10649]
I am currently debugging the clipboard functionality of FreeRDP based on SDL3 and found that when obtaining text/uri-list data from the SDL3 interface, FreeRDP does not take Windows into account when parsing the URI. As far as I know, path representations differ between Windows and UNIX/Linux:

Windows:
Absolute path, for example: C:\path\to\file.txt
The corresponding URI representation should be: file:///C:/path/to/file.txt
UNIX/Linux:
Absolute path, for example: /path/to/file.txt
The corresponding URI representation should be: file:///path/to/file.txt

The related function is cliprdr_local_stream_update.

**Comment by akallabeth** [comment]
well, you´re on the most experimental part of `FreeRDP` there ;)
first of all `SDL3` and secondly `clipboard` which is not yet supporting file copy for sdl client ;)

(note: windows does not use `URI` for file copy at all, check the older windows native client)
