### ISSUE TITLE
FFmpeg version detected () is too old.  (Require at least 57.48.101 for   sound).  Deactivating

### ISSUE THREAD

**Issue by bj-mitchell** [FreeRDP/FreeRDP#10659]
**Describe the bug**
 CMake thinks libavcodec is old even though the latest version of ffmpeg is present.
Trying to do a compile on windows with ffmpeg installed using vcpkg.  Getting the following error abount it not finding avcodec version properly.  Looks almost identical to an older bug #8186, so this might be a regression bug.

**To Reproduce**
1. ```git clone https://github.com/FreeRDP/FreeRDP.git```
2. Try to compile with the following options:
```
cmake -G "Visual Studio 17 2022" -A x64 `
    -DCMAKE_INSTALL_PREFIX="C:/Program Files/FreeRDP" `
    -DWITH_CLIENT=ON `
    -DWITH_SERVER=ON `
    -DWITH_CHANNELS=ON `
    -DCHANNEL_URBDRC=ON `
    -DWITH_DIRECTX=ON `
    -DWITH_OPENSSL=ON `
    -DWITH_ZLIB=ON `
    -DWITH_DSP_FFMPEG=ON `
    -DWITH_FFMPEG=ON `
    -DWITH_JPEG=ON `
    -DWITH_OPENH264=ON `
    -DWITH_OPUS=ON `
    -DWITH_PCAP=ON `
    -DBUILD_TESTING=OFF `
    -DWITH_MANPAGES=ON `
    -DDOCBOOKXSL_DIR="$docbookXslDir" `
    -DCMAKE_TOOLCHAIN_FILE="$vcpkgDir\scripts\buildsystems\vcpkg.cmake" `
    ../src
```

**Expected behavior**
 CMake correctly detects libavcodec version

**Screenshots**
```CMake Warning at CMakeLists.txt:585 (message):
  FFmpeg version detected () is too old.  (Require at least 57.48.101 for
  sound).  Deactivating
```

**Application details**
* FreeRDP version (master)

**Environment:**
 - OS: Windows
 - Version: Windows 11
 - Architecture: x86_64

**Additional context**
FFmpeg was installed using:
```
vcpkg install ffmpeg:x64-windows
```

**Comment by akallabeth** [comment]
so:
1. which version do you have installed now?
2. a little bit more from the configuration log might help ;)

**Comment by akallabeth** [comment]
ok, just tested this with a custom build:
1. Current version `7.0.2` installed
2. detect the whole thing with our script in https://github.com/FreeRDP/FreeRDP/blob/master/cmake/FindFFmpeg.cmake
3. everything working fine, `AVCODEC_VERSION` is filled with appropriate values.

so this smells like a caching issue/broken build you´re using?
closing until we receive evidence it is a bug in our detection script.

**Comment by bj-mitchell** [comment]
.\vcpkg install ffmpeg
Computing installation plan...
The following packages are already installed:
    ffmpeg[core,postproc,gpl,avresample,swscale,swresample,avformat,avfilter,avdevice,avcodec]:x64-windows@7.0.2#4

**Comment by bj-mitchell** [comment]
Not sure why this was closed, but I didn't realize vcpkg had a freerdp build already.  I'll use that for now, but it goes back to 3.4.0.  I think something still broke here...

**Comment by akallabeth** [comment]
@bj-mitchell no.
the script detects fine is stuff is installed, maybe your `vcpkg-ffmpeg` is lacking a header file?
