### ISSUE TITLE
UDP for FreeRDP

### ISSUE THREAD

**Issue by marcellowy** [FreeRDP/FreeRDP#10669]
First i like freeRDP project, help me study windows programming

**Is your feature request related to a problem? Please describe.**
when i use freerdp connect windows server or win10 
i use wireshark capture packet, free rdp always via tcp transport data

when i use windows application mstsc
the Application Data transport via RDUDP protocol

i found some about UDP for FreeRDP  https://www.hardening-consulting.com/en/posts/20230109-udp-support-2.html

and i found some about RDPUDP protocol code in freeRDP source code, but i don't know how it works

**Describe the solution you'd like**
want freeRDP support udp transport application data.

**Describe alternatives you've considered**

**Additional context**
freerdp connect win10 
![image-2024-9-18_16-26-44](https://github.com/user-attachments/assets/f2ed0646-2ba8-4512-acd5-5993d607be99)

mstsc connect win10
![image-2024-9-18_16-22-5](https://github.com/user-attachments/assets/d2b86b0d-5113-4e5a-9ddc-16f8cac739dc)

thank you read the all, my english so sad. sorry

**Comment by hardening** [comment]
@marcellowy follow instructions at https://github.com/awakecoding/wireshark-rdp and you'll see all the traffic in clear in wireshark including RDPUDP (at least if it's MS-RDPUDP2)

**Comment by marcellowy** [comment]
> @marcellowy follow instructions at https://github.com/awakecoding/wireshark-rdp and you'll see all the traffic in clear in wireshark including RDPUDP (at least if it's MS-RDPUDP2)

thank you for reply, i will do it and feedback results

**Comment by marcellowy** [comment]
@hardening thank you for reply again
I observed freeRDP use RDP protocol over TCP,  not over UDP, like this:
![cc](https://github.com/user-attachments/assets/31bf2c5c-6bf5-45b6-a90c-f37a63b00181)

when use mstsc the RDPUDP2 protocol over UDP, like this:
![cc2](https://github.com/user-attachments/assets/c20d5844-f4a6-45c7-9db1-f2e755b530da)

i didn't find freeRDP client send data paket via UDP  to RDP server
or my compilation parameters are incorrect and udp is not enabled ?

i see mstsc client  actively send the first UDP packet, didn't see it at freeRDP

**Comment by hardening** [comment]
@marcellowy there's currently no UDP support in FreeRDP master, so no surprise here. But I have experimented a little the subject, more in private messages (you've already cited my blog posts).

Regarding mstsc captures, I've not implement various compressions at the "RDP level" (channels) in wireshark, so if you want better captures run mstsc with a .rdp where you have desactivated compression. Also if you have configured everything correctly you shall see `egfx` traffic and other dynamic channels within the RDPUDP packets.

**Comment by bmiklautz** [comment]
@marcellowy as @hardening states there is currently no UDP support.  We have the long open issue #4978 for tracking. closing this as duplicated.
