### ISSUE TITLE
Cannot launch a RAIL application when multiple monitors are synchronized

### ISSUE THREAD

**Issue by Voxnod** [FreeRDP/FreeRDP#10670]
**Steps to reproduce:**
1. Configure multiple monitors (two are enough) to synchronize picture. For example, in my setup, an external LG monitor is connected to my laptop and it is configured to be a replica of the build-in screen.
![display-settings](https://github.com/user-attachments/assets/5245fc5b-bf47-4aba-a64c-237e8baf439e)

2. Launch a RAIL application with `/multimon` argument:
```
xfreerdp3 /v:address /u:user /p:pass /cert:ignore /multimon /app:"||Microsoft Word"
```

**Expected result:**
The application should launch.

**Actual result:**
The application does not launch, and the following errors appear in the console:
```
[12:50:38:420] [23:47412700] [ERROR][com.freerdp.core.transport] - [transport_read_layer]: BIO_read returned a system error 54: Connection reset by peer
[12:50:38:420] [23:47412700] [ERROR][com.freerdp.core] - [transport_read_layer]: ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
```

Here is the full trace-level log.
[log-does-not-work-trace.log](https://github.com/user-attachments/files/17113490/log-does-not-work-trace.log)

After some investigation, I found events on the RDP host side:
![windows-event-1](https://github.com/user-attachments/assets/a6c775ea-989b-49cc-aa01-60c73d2e77d8)
![windows-event-2](https://github.com/user-attachments/assets/7e4c3b7a-3717-46f4-8578-f6374ff00bdd)

Error 4405 corresponds to `ERRINFO_MONITORGEOMETRYVALIDATIONFAILED`: [source code reference](https://github.com/FreeRDP/FreeRDP/blob/master/include/freerdp/error.h#L164C9-L164C48)

In the xfreerdp log there is a monitor-related section:
```
[12:50:38:416] [23:47412700] [DEBUG][com.freerdp.core.gcc] - [gcc_write_client_monitor_data]: MonitorCount=2
[12:50:38:416] [23:47412700] [DEBUG][com.freerdp.core.gcc] - [gcc_write_client_monitor_data]: Monitor[0]: top=0, left=0, bottom=1599, right=2559, flags=1
[12:50:38:416] [23:47412700] [DEBUG][com.freerdp.core.gcc] - [gcc_write_client_monitor_data]: Monitor[1]: top=0, left=0, bottom=1079, right=1919, flags=0
[12:50:38:416] [23:47412700] [DEBUG][com.freerdp.core.gcc] - [gcc_write_client_monitor_data]: FINISHED
```

The implementation of the function `gcc_write_client_monitor_data` in file [libfreerdp/core/gcc.c](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/gcc.c#L2154) seems compliant with the standard described in [2.2.1.3.6 Client Monitor Data (TS_UD_CS_MONITOR)](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/a8029f8e-01e1-4f19-af67-bcad5bdef624).

I did some experiments with passed coordinates in the `gcc_write_client_monitor_data` function, and it seems that the server throws an error if the monitor fields overlap, even by one pixel.

**Potential Solutions:**
1. Simply avoid passing the `/multimon` argument when launching the xfreerdp client if monitors are configured to synchronize their displays. This is a non-invasive solution, though I am unsure if it's the best one.
2. Add a check into [this part](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/gcc.c#L2165) of `gcc_write_client_monitor_data` to verify that monitors do not overlap
```
    // line 2165
    if (settings->MonitorCount > 1 && monitorsDoNotOverlap)
    {
        ...
    }
```

Option one is less invasive but may not be the most appropriate long-term fix.

**Comment by akallabeth** [comment]
@Voxnod 
1. `/multimon` is redundant for `/app` rails mode, it is always used.
2. yes, overlapping monitor layouts are not supported (at all!) maybe we can add a check and terminate right there.

**Comment by Voxnod** [comment]
It is quite strange. `/multimon` always affects rail applications in my setup. Without it I cannot even drag application window on second display. And if I don't pass the argument, the current issue won't occur.
Maybe it has something to do with the fact that I use FreeBSD.

**Comment by akallabeth** [comment]
@Voxnod no, nothing OS specific. I´ll check this (maybe I am just remembering it wrong :grin: )

**Comment by akallabeth** [comment]
@Voxnod ok, added https://github.com/FreeRDP/FreeRDP/pull/10672 this should prevent connection attempts with such monitor layouts early.

**Comment by akallabeth** [comment]
ok, closing as this is an unsupported configuration (sorry)
