### ISSUE TITLE
Clipboard redirection on Windows XP

### ISSUE THREAD

**Issue by pachuco** [FreeRDP/FreeRDP#10691]
Server specs:
- Windows XP x86 SP3

Client specs:
- Windows 10 x64
- build rev 51b179b9c742475a07ea58d1fd59031a43b6d8f5
- build bitness x64
- build type wfreerdp and sdl-freerdp
- note: this happens with arm64 android client aRDP as well.

CLI:
wfreerdp %PATH_TO_RDP_FILE% +clipboard

Problam:
Clipboard redirection only works one way. I can paste from client to server, but not viceversa.
Regarding aRDP, I suspect this is problem with handling earlier RDP, as I was able to properly share clipboard with a win7 machine using this client.
Have not tried connecting to modern windows using wfreerdp/sdl-freerdp, but I suspect same holds true.

**Comment by akallabeth** [comment]
@pachuco a debug log would be nice to check what is going on (just start your `wfreerdp <yourargs> /log-level:debug > somefile.txt 2>&1` in a directory where you can write to, then all the log is written to `somefile.txt`

**Comment by pachuco** [comment]
Any particular things I should blank out from this log before I put on the Internets?

**Comment by akallabeth** [comment]
@pachuco if you don´t want your (hopefully internal) `IP/url` of the windows XP to leak that one.
maybe your `username` and `computer/machine name` too if you care about that.

**Comment by pachuco** [comment]
How do I exit/switch away from wfreerdp?

**Comment by akallabeth** [comment]
@pachuco disconnect the session from within the session or do not start fullscreen?
maybe `<ctrl>+<alt>+return` to escape fullscreen, but I don´t use that client, so don´t know.

**Comment by pachuco** [comment]
[somefile.txt](https://github.com/user-attachments/files/17195574/somefile.txt)
Here I do in order:
- copy some text from notepad
- Ctrl+Alt+Del to switch to browser
- attempt to paste copied text in browser
- switch back to wfreerdp
- disconnect using server GUI

Hope I didn't leak anything.

**Comment by akallabeth** [comment]
@pachuco ok, from the log your windows XP does not have a properly working clipboard. (browser is html format, that is advanced clipboard, can you test simple text copy (notepad)?

**Comment by akallabeth** [comment]
@pachuco does not matter, `notepad` on both ends (or it will request `html` format)
but good to know it works with `mstsc`, that is a datapoint we can work with. (would have been the next question)

**Comment by pachuco** [comment]
Notepad on both ends, unilateral clipboard still.
Start new session? You mean restart windows on server side? No, my server PC has been running for months.
I did next best thing, connect with official MS rdp client and check copypaste functionality. And it does work.

**Comment by akallabeth** [comment]
@pachuco yes, restarting the windows server or logging out all user sessions with task manager.
the clipboard is running as user and different clients get a different session, so `mstsc` and `freerdp` do not connect to the same one.

**Comment by akallabeth** [comment]
@pachuco ok, got another datapoint:
digged up an old server 2003 vm (should be equivalent to XP with regard to clipboard) and tested this: working fine in both directions.

**Comment by pachuco** [comment]
Build 3fe99c87a169394ecf8462c2f6ca8c3e67260472 wfreerdp x64.
Still unilateral.

%insert data here%

**Comment by akallabeth** [comment]
@pachuco you still did not answer the question if there are multiple sessions running on your server ;)
the rest is old news.

**Comment by pachuco** [comment]
Only one user logged in.

**Comment by akallabeth** [comment]
> Only one user logged in. Only one pair of hands working with that user at any time.

and how many sessions are active?
one user can have multiple logins ;)

**Comment by pachuco** [comment]
> > Only one user logged in. Only one pair of hands working with that user at any time.
> 
> and how many sessions are active? one user can have multiple logins ;)

Only one I think. Any new session disconnects any other.
Desktop usage and two devices via RDP.

**Comment by akallabeth** [comment]
closing as server issue:
* `[DEBUG][com.freerdp.channels.cliprdr.client] - [cliprdr_order_recv]: msgType: CB_FORMAT_DATA_RESPONSE [0x0005] (5), msgFlags: CB_RESPONSE_FAIL|[0x0002] dataLen: 0`

tried this now multiple times with a server 2003 VM and it works in all directions (all versions of 3.x)

**Comment by pachuco** [comment]
Is there build I can try to verify?

**Comment by pachuco** [comment]
Nope, same defect on my side.
If it's server's fault, then how come clipboard redirection works fine with official client?

**Comment by akallabeth** [comment]
@pachuco needs investigation of your `rdpclip.exe` - that one is very picky on xp.

what I´ve tested so far:
* all versions of `wfreerdp.exe` and `xfreerdp` from 3.0.0 to 3.8.0 and current `master`
* server is a windows server 2003 (don´t have original xp anymore, but is same codebase)

copying text in both directions works fine.

the log you posted suggests that the windows xp for some reason does not want to serve a copy request (e.g. does not send the text but the mentioned `CB_RESPONSE_FAIL` after receiving the request)

**Comment by pachuco** [comment]
To be fair, I do use a certain unofficial version of winxp x86.
https://zone94.com/downloads/software/operating-systems/123-windows-xp-professional-sp3-x86-integral-edition#comment-12217

So, `rdpclip.exe` is of interest now? Let's try:
- version 5.1.2600.5512
- md5 hash DCCF6ED915BC05C244801B550AD12B17

**Comment by pachuco** [comment]
I'll see if I can get off me bum and make a VM to record captures.
Or maybe I hand you cliprdp.exe binary?
