### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by fleurmari** [FreeRDP/FreeRDP#10697]
Xfreerdp closes when sound starts playing

Version xfreerdp: 2.11, 2.10, 3.6, and others 🤔
Sound codec: alc233
Pipewire (pulse)

![IMG_20241001_151811_767.jpg](https://github.com/user-attachments/assets/5227e9d1-ef8c-45d5-b14a-17f73207ac8f)

I don't know how to fix it, please, help 🙏 😢

**Comment by akallabeth** [comment]
@fleurmari well, fix your local sound setup. not much we can do from our side here.
