### ISSUE TITLE
Smartcard Redirection

### ISSUE THREAD

**Issue by awakecoding** [FreeRDP/FreeRDP#107]
Migrate the smartcard redirection plugin to 1.0.

**Comment by rctan** [comment]
Which first stable version after 0.7.3 of the FreeRDP will work with Smartcard, 1.0, 1.1? My customer is using FreeRDP 0.7.3. I know this version does not work with Smartcard after reading the mailing list. My platform is RHEL 5.2 (Linux kernel 2.6.18 32-bit) with Windows 7 Pro 64-bit. Thanks!
