### ISSUE TITLE
Microphone (via alsa) stopped working after upgrading from 3.7 to 3.8

### ISSUE THREAD

**Issue by kostya-sh** [FreeRDP/FreeRDP#10703]
I am using Arch Linux and noticed that microphone stopped working (it is not detecting any sound inside remote session) after upgrading from version 3.7 to 3.8. Audio still works with no issues.

I am starting freerdp with the following parameters:

```
xfreerdp3 /v:HOSTNAME \
         /compression-level:2 \
         /scale:140 \
         /audio-mode:0 /sound:sys:alsa /mic:sys:alsa,format:1,quality:high \
         /f \
         -wallpaper -themes -window-drag +auto-reconnect +clipboard
```

**Comment by akallabeth** [comment]
@kostya-sh a log with `/log-filters:com.freerdp.channels.audin.client:trace` might help here.

**Comment by kostya-sh** [comment]
[audin3.8.txt](https://github.com/user-attachments/files/17255492/audin3.8.txt)
[audin3.7.txt](https://github.com/user-attachments/files/17255493/audin3.7.txt)

Logs attached for both versions 3.7 and 3.8.

While recording these logs I opened  "Open Sound Settings" dialog inside the remote session.

**Comment by kostya-sh** [comment]
Just FYI, I have installed version 3.9 and the microphone works. Thanks a lot for the fix.
