### ISSUE TITLE
Where to get public key for signature?

### ISSUE THREAD

**Issue by Business1sg00d** [FreeRDP/FreeRDP#10705]
**Describe the bug**
Not really a bug. No solutions found on google or in issues. Recieving the following error after running command ```dpkg-buildpackage``` for packaging/deb/freerdp-nightly:

![image](https://github.com/user-attachments/assets/dc9407c3-ef45-4820-b70e-c57b48c19a76)

I've attempted downloading the latest release and can not find the public key to verify. Tried debian and ubuntu servers:
```
keyring.debian.org
keyserver.ubuntu.com
```

**To Reproduce**
Steps to reproduce the behavior; from within git repo:
1. sudo apt build-dep freerdp2-x11
2. ln -s packaging/deb/freerdp-nightly debian
3. dpkg-buildpackage
4. See error in image posted.

**Expected behavior**
Just looking for public key to verify installation whether using "dpkg-buildpackage" or for .asc file in releases.

**Environment (please complete the following information):**
 - OS:Linux
 - Version/Distribution:  kali 6.10.9-amd64
 - Architecture: [amd64, arm]: amd64

**Comment by akallabeth** [comment]
@Business1sg00d you need to create your own certificate/key pair for that ;)
see https://earthly.dev/blog/creating-and-hosting-your-own-deb-packages-and-apt-repo/#step-3-signing-your-apt-repository-with-gpg

basically the one that builds the package sings it with a key they posess so everyone can check that that package is actually from that person/organisation.
