### ISSUE TITLE
'localhost' no longer valid as a server name

### ISSUE THREAD

**Issue by daj92109** [FreeRDP/FreeRDP#10736]
I have several scripts that route my RDP connections through SSH tunnels.  They connect to servers with with command-lines like:

xfreerdp /v:localhost:6901 /u:<username> /d: /p:<password> /cert:ignore

These scripts stopped working around release 6.3.2.

By setting the log-level to DEBUG I see these (somewhat misleading) errors:

[11:01:06:420] [3116933:002f8f89] [DEBUG][com.freerdp.core.nego] - [nego_send_negotiation_request]: RequestedProtocols: [SSL|HYBRID][0x00000003]
[11:01:06:420] [3116933:002f8f89] [ERROR][com.freerdp.core.transport] - [transport_default_write]: BIO_should_retry returned a system error 32: Broken pipe
[11:01:06:420] [3116933:002f8f89] [ERROR][com.freerdp.core] - [transport_default_write]: ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]

I have found a work-around.  If I replace 'localhost' with '127.0.0.1' my scripts continue to work.

I have also compiled a few different version  of xfreerdp and it looks like the failure is caused by this change to libfreerdp/core/tcp.c: 

https://github.com/FreeRDP/FreeRDP/commit/562fa8a03d20957bff73fa3e1c5429aa3672dfd0#diff-c3b201d4c2b1152732b0975aa78f99c369ec784d5fe9385b902cbcfe21ff4397

If I back out that change to tcp.c, 'localhost' continues to work as a server name.

I tested this with several builds on Fedora Linux 40 and Raspbian Linux 64-bit.

**Comment by akallabeth** [comment]
@daj92109 then you should check your local setup.
`localhost` works quite well if it can be properly resolved. (we do not do that, we ask the system to resolve addresses for this project)

also, we have no version 6.3.2 ;)
most recent is 3.8.0

fyi: tested current freerdp on debian 12 and a self compiled version from master, both resolve `localhost` just fine on my systems.
