### ISSUE TITLE
Connection dropped when minimizing remote desktop window

### ISSUE THREAD

**Issue by anhcuongdev** [FreeRDP/FreeRDP#10737]
**Describe the bug**
Connection dropped when minimizing remote desktop window

**To Reproduce**
1. Use the .rdp file to connect.
2. While the connection is being established, minimize the Remote Desktop window
3. The connection will be disconnected.

**Expected behavior**
Connection is not disconnected when minimizing window

**Screenshots**
![image](https://github.com/user-attachments/assets/9a2c5a2c-9c1c-4d1a-bb2b-c61e3ffe4769)

**Application details**
* FreeRDP version (`freerdp-proxy /2.11.7`)
* .rdp file

**Comment by akallabeth** [comment]
@anhcuongdev please read https://github.com/FreeRDP/FreeRDP/wiki/BugReporting again.

there is no indication of what you are actually using (the screenshot is `mstsc`?)
just `FreeRDP` is too vague (there are clients/server/proxy/helper binaries in this project)

**Comment by anhcuongdev** [comment]
I use freerdp-proxy as an intermediate server to the windows server.
When freerdp-proxy is making a connection, if you minimize the mstsc window, the connection will be immediately disconnected. This does not happen with a direct connection.

**Comment by anhcuongdev** [comment]
> @anhcuongdev please read https://github.com/FreeRDP/FreeRDP/wiki/BugReporting again.
> 
> there is no indication of what you are actually using (the screenshot is `mstsc`?) just `FreeRDP` is too vague (there are clients/server/proxy/helper binaries in this project)
> 
> we also do not know which platform is affected (what are you using? linux? windows? mac os? BSD? ...)

I use freerdp-proxy as an intermediate server to the windows server.
When freerdp-proxy is making a connection, if you minimize the mstsc window, the connection will be immediately disconnected. This does not happen with a direct connection.

**Comment by akallabeth** [comment]
@anhcuongdev does this also happen with current stable releases?
we´ve rewritten most of proxy with 3.0

**Comment by akallabeth** [comment]
also, can you share your proxy configuration? (hard to guess what you do without some hints)
