### ISSUE TITLE
Ubuntu 24 cant install .deb package

### ISSUE THREAD

**Issue by xBr0th3rx** [FreeRDP/FreeRDP#10766]
**Describe the bug**
When I install the .deb package I get a dependency error that cannot be installed.

**To Reproduce**
1. apt install ./freerdp-nightly_3.0.0+0~20241022014826.1638~1.gbpf1725b_amd64.deb
2. See Error

**Expected behavior**
Package Installed 

**Screenshots**
![Screenshot_20241022_112032](https://github.com/user-attachments/assets/204cfe9c-1010-4a25-ba99-3aa9e6bf1b69)

Installed "Libicu" Version
![Screenshot_20241022_112208](https://github.com/user-attachments/assets/efab3254-45cb-4e0a-8f2f-d01504fc72bd)

**Application details**
* FreeRDP version (`freerdp-nightly_3.0.0+0~20241022014826.1638~1.gbpf1725b_amd64.deb`)
* freerdp-nightly_3.0.0+0~20241022014826.1638~1.gbpf1725b_amd64.deb

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version/Distribution: Ubuntu 24.04 (Noble)
 - Architecture: amd64

**Comment by akallabeth** [comment]
@xBr0th3rx did you compile that yourself or did you just use one from another distribution?

**Comment by akallabeth** [comment]
updated the nightly builder as `noble` was not in the build list, so try the correct package ;)

**Comment by xBr0th3rx** [comment]
I took the one from Mantic Link because I thought it would also work.

Will this be available for Noble at some point?

**Comment by akallabeth** [comment]
@xBr0th3rx just triggered a rebuild of the nighty.
aside from that https://github.com/FreeRDP/FreeRDP/wiki/Compilation#linux-specifics tells how to (easily) build the nightly yourself using `dpkg-buildpackage`

**Comment by xBr0th3rx** [comment]
Thank you for your quick feedbacks :)

I've never done anything with build packages before so I'm always careful ^^

But I'll give it a try.

Does it mean that from tomorrow there will also be a download for Noble?

**Comment by akallabeth** [comment]
yes, if the build is successful.

**Comment by xBr0th3rx** [comment]
> yes, if the build is successful.

Thank you 

The package works :D
