### ISSUE TITLE
multimonitor restrictions enforced in windowed mode

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#10779]
when running in windowed mode multimonitor restrictions are enforced.
fix that by using fake monitor data

**Comment by tigockel** [comment]
I hope it is okay to ask a curious question, but would /f be considered "windowed mode"? If not, the restrictions should not affect that either, right?

**Comment by akallabeth** [comment]
@tigockel `/f` is currently not `windowed mode`, I'll look into this. 
(sorry for the inconvenience, but adding checks all over the place to uncover such oversights)

**Comment by akallabeth** [comment]
@tigockel ok, just added another check to enforce `0/0` and `primary=TRUE` in case of fullscreen. (we don´t really care about the other details of monitor information there)
only `multimon` is now affected by the other restrictions (as there is currently no code that can translate between the layouts the layouts must be compatible)

**Comment by tigockel** [comment]
> @tigockel `/f` is currently not `windowed mode`, I'll look into this. (sorry for the inconvenience, but adding checks all over the place to uncover such oversights)

I am aware, that sdl is considered experimental, but I don't use x11 and wlfreerdp3 does have some artifact glitches, so except this bug it works best for me. (Other than, that I still can't get the clipboard to be shared)

Also this was my first bug I ever found in some software I use, so I am very happy I could help!

**Comment by akallabeth** [comment]
@tigockel clipboard will require `SDL3` - which is currently even more experimental

**Comment by tigockel** [comment]
@akallabeth  I have seen the progress and the merge already! Lovely! About sdl3... I thought I read, that it would come with 3.9.0, but it is a minor problem to me. I just start a tmp wl session; copy what I need; hop back to sdl again.

I will release you to your coding again and stop distracting you! :D Kind regards and thanks a lot!

**Comment by akallabeth** [comment]
@tigockel there is already a sdl3 client included (and with 3.9.0 it uses the stablized SDL3 API)
but that is just the basic porting done, now the features need to be implemented...
