### ISSUE TITLE
seamless app: Internet Explorer 11 dialog boxes get shorter with every drag and drop

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#10778]
**Describe the bug**

Bad behavior of dialog boxes get shorter with every drag and drop

Video 

https://github.com/user-attachments/assets/82824ac8-7d67-4951-91d1-7accd97aceae

For example:

/u:test /app:program:"||iexplorer",cmd:'"https://example.com"' /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100% /cert:ignore

Any setting that could improve this behavior?

**Application details**

This is FreeRDP version 3.9.1-dev0 (ae5f655f1)

/u:test /app:program:"||iexplore",cmd:'"https://example.com"' /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100% /cert:ignore

OS version connecting to (server side)
Windows Server 2016

OS: Fedora
Version/Distribution: Debian with xfce
Architecture: amd64

**Comment by akallabeth** [comment]
ok, adding to the list of rail issues.
looks like the coordinates are not calculated correctly (the spec is a real mess there, you send window sizes with/without some magic borders and you receive them in the opposite format :/
