### ISSUE TITLE
Inconsistant display with remote app (win32calc - Windows Server 2022)

### ISSUE THREAD

**Issue by fusion916** [FreeRDP/FreeRDP#10785]
Compiled from git (arch linux):

This is FreeRDP version 3.9.1-dev0 (6c7f88aec)

I'm on this verison because the current head has a broken compile in arch.

This is the command I am using to open up the remote app:

xfreerdp /v:<ip> /u:administrator /p:<pw> /scale:140 /scale-desktop:125 /app:program:"||win32calc" /cert:ignore '/auth-pkg-list:!kerberos' /gfx:RFX:off /gfx:AVC444:off

I'm on KDE/Wayland with 120% scale if that matters.

Calc actually has 3 different appearances when i run this same command. Which appearance comes up seems completely random to me:

Appearance 1 (Normal - This is how it should look):

![calc1](https://github.com/user-attachments/assets/78565c76-e496-40f9-a153-8a81e68f37df)

Appearance 2 (Cut off):

![calc2](https://github.com/user-attachments/assets/d0048dc4-3dfb-418b-bb1a-d53ed3f17785)

Appearance 3 (Blurry - Something messed up about the scaling/DPI):

![calc3](https://github.com/user-attachments/assets/2515820a-6f7d-45c7-ac97-5b6b48b09960)

**Comment by akallabeth** [comment]
duplicate issue, check https://github.com/FreeRDP/FreeRDP/labels/channel%3Arail
(we don´t need an issue for every possible application you can start, but some hands to fix issues ;))

specific duplicate: https://github.com/FreeRDP/FreeRDP/issues/10778
