### ISSUE TITLE
freerdp can't connect to 2012r2 rdp from xubuntu 22.04 client

### ISSUE THREAD

**Issue by vovchok70** [FreeRDP/FreeRDP#10804]
I can connect to 2012r2 server from xubuntu 18.04 (without /sec:rdp option) (freerdp 2.0.0)
But I can't connect to this server from xubuntu 22.04 (freerdp 2.6.1 & freerdp3 nightly):

(xfreerdp /v:ipaddress:port /cert:ignore /u:username /p:password):
[com.freerdp.core] - transport_connect_tls:freerdp_set_last_error_ex ERRCONNECT_TLS_CONNECT_FAILED [0x00020008]

(/opt/freerdp-nightly/bin/xfreerdp3 /v:ipaddress:port /cert:ignore /u:username /p:password):
[com.freerdp.crypto] - [freerdp_tls_handshake]: BIO_do_handshake failed
[com.freerdp.core] - [transport_default_connect_tls]: ERRCONNECT_TLS_CONNECT_FAILED [0x00020008]

(xfreerdp /v:ipaddress:port /cert:ignore /u:username /p:password /sec:rdp):
[com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[com.freerdp.core] - transport_read_layer:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]

(/opt/freerdp-nightly/bin/xfreerdp3 /v:ipaddress:port /cert:ignore /u:username /p:password /sec:rdp):
[com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[com.freerdp.core] - transport_read_layer:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]

I can successfully connect via freerdp/freerdp3 from xubuntu 22.04 to 2008r2/2016/xubuntu+xrdp, but not 2012r2...
Also I have macos (monterey) on this pc and I can successfully connect via ms rdp client for mac to this server...

Also I tried to connect this 2012r2 server from another pc with archlinux and with xubuntu 22.04 and got the same errors...

Anybody help me!

**Comment by akallabeth** [comment]
most likely https://github.com/freerdp/freerdp/wiki/FAQ#windows-7-errconnect_tls_connect_failed
e.g. the SSL ciphers supported by server 2012 are too old and blocked by default.

ping me if it is something different, closing until then.

**Comment by vovchok70** [comment]
Thanks for the answer, but it doesn't work...

xfreerdp /v:ipaddress:port /cert:ignore /u:username /p:password /tls-seclevel:1
[com.freerdp.core] - transport_connect_tls:freerdp_set_last_error_ex ERRCONNECT_TLS_CONNECT_FAILED [0x00020008]

xfreerdp /v:ipaddress:port /cert:ignore /u:username /p:password /tls-seclevel:0
[com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex ERRCONNECT_CONNECT_FAILED [0x00020006]
[com.freerdp.core] - failed to connect to ipaddress

**Comment by akallabeth** [comment]
@vovchok70 hmm, then it might be due to your openssl not having legacy ciphers activated.
that you can connect to 2008 does only mean that that installation has a better configuration.

**Comment by vovchok70** [comment]
https://services.dartmouth.edu/TDClient/1806/Portal/KB/ArticleDet?ID=136495
This helped me (with /tls-seclevel:0)
