### ISSUE TITLE
Building for iOS broken since 3.9.0

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#10818]
I just updated to 3.9.0 and now my iOS builds are failing with:

```
Undefined symbols for architecture arm64:
  "_CommDeviceIoControl", referenced from:
      _GetCommProperties in libFreeRDP.a[arm64][244](comm.c.o)
      _GetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _GetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _GetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _GetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _SetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _SetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _SetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _SetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _SetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      ...
  "__comm_ioctl_tcsetattr", referenced from:
      _SetCommState in libFreeRDP.a[arm64][244](comm.c.o)
      _CommCreateFileA in libFreeRDP.a[arm64][244](comm.c.o)
ld: symbol(s) not found for architecture arm64
```

I think this is the commit that caused this: https://github.com/FreeRDP/FreeRDP/commit/9c6126c470c03f334d25fd5599d297833da35188; specifically, the changes to `winpr/libwinpr/comm/CMakeLists.txt`.

If I'm reading it correctly, [`comm.c`](https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/comm/CMakeLists.txt#L23) is now compiled even on iOS, but the file containing the symbols that my build is complaining about are in [`comm_ioctl.c`](https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/comm/CMakeLists.txt#L30) which is not compiled when targeting iOS.

Update: Just to clarify; it's not the actual FreeRDP build that fails. Since I'm compiling statically, the issue only shows up when trying to link the static lib into a dylib or an app.

**Comment by thenextman** [comment]
@lemonmojo I confirm we have the same issue, I didn't try to address it upstream yet but to workaround the problem you can just reintroduce the files in cmake

<img width="1689" alt="Screenshot 2024-11-05 at 09 38 56" src="https://github.com/user-attachments/assets/60220fda-b47e-47b7-a905-cc035305825d">

**Comment by akallabeth** [comment]
@lemonmojo thx for the hint.
updated the ci builder and added a dummy implementation for iOS
