### ISSUE TITLE
3.9.0 keyboard remap stopped working (/kbd:remap invalid entry '015b=006a')

### ISSUE THREAD

**Issue by gitgoggles** [FreeRDP/FreeRDP#10810]
**Describe the bug**
The following command, with keyboard remap, worked on FreeRDP 3.8.0:
```
sdl-freerdp /u:XXX /d:XXX /p:XXX /gateway:g:XXX,u:XXX,d:XXX,p:XXX,type:http,no-websockets /v:XXX /w:3840 /h:2160 -grab-mouse -grab-keyboard /scale-desktop:125 /scale-device:100 /cert:ignore +auto-reconnect /kbd:layout:0x00000809,lang:0x0809,remap:015b=006a /sound /log-level:trace
```

On FreeRDP 3.9.0 it fails with the following error:
```
[09:46:01:931] [14392:00003838] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_warn_experimental]: [experimental] sdl-freerdp client is currently experimental!
[09:46:01:931] [14392:00003838] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_warn_experimental]:  If problems occur please check https://github.com/FreeRDP/FreeRDP/issues for known issues or create a new one!
[09:46:01:931] [14392:00003838] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_warn_experimental]:  Developers hang out in https://matrix.to/#/#FreeRDP:matrix.org?via=matrix.org - dont hesitate to ask some questions. (replies might take some time depending on your timezone)
[09:46:01:944] [14392:00003838] [WARN][com.freerdp.client.common.cmdline] - [check_kbd_remap_valid]: /kbd:remap invalid entry '015b=006a'
[09:46:01:944] [14392:00003838] [ERROR][com.freerdp.client.common.cmdline] - [freerdp_client_settings_parse_command_line_arguments_int]: Command line parsing failed at 'kbd' value 'layout:0x00000809,lang:0x0809,remap:015b=006a' [-1002]
```

**Expected behavior**
The `remap:015b=006a` part was being used to remap my left SUPER/WIN key to F19, moving it out of the way of my local computer. I use my left SUPER/WIN for my local computer, and my right SUPER/WIN for the remote desktop. This has been working fine for the last couple of months I've been using it.

For reference, here is the relevant part of my `sdl-freerdp /list:kbd-scancode`
```
RDP scancodes and their name for use with /kbd:remap
0x015b  --> VK_LWIN
0x006a  --> VK_F19
```

**Application details**
* FreeRDP version: This is FreeRDP version 3.9.0 (n/a)
* Output of `sdl-freerdp +buildconfig`
  * Build configuration: BUILD_TESTING=FALSE WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRERROR_R=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_AVX2=OFF WITH_AVX2_AVAILABLE=0 WITH_BINARY_VERSIONING=OFF WITH_CAIRO=TRUE WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CJSON_REQUIRED=OFF WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL2=ON WITH_CLIENT_SDL3=OFF WITH_CLIENT_SDL_AVAILABLE=1 WITH_CLIENT_SDL_VERSIONED=OFF WITH_CUPS=TRUE WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DOCUMENTATION=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=FALSE WITH_FAAD2=TRUE WITH_FDK_AAC=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FULL_CONFIG_PATH=OFF WITH_FUSE=TRUE WITH_GFX_FRAME_DUMP=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_JPEG=TRUE WITH_JSONC_REQUIRED=OFF WITH_JSON_DISABLED=OFF WITH_KEYBOARD_LAYOUT_FROM_FILE=OFF WITH_KRB5=TRUE WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=TRUE WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSSL=ON WITH_OPUS=TRUE WITH_OSS=FALSE WITH_PCSC=TRUE WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=TRUE WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SDL_IMAGE_DIALOGS=OFF WITH_SDL_LINK_SHARED=ON WITH_SERVER=TRUE WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=ON WITH_SYSTEMD=ON WITH_THIRD_PARTY=OFF WITH_TIMEZONE_COMPILED=ON WITH_TIMEZONE_FROM_FILE=OFF WITH_TIMEZONE_ICU=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=ON WITH_VAAPI=FALSE WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=FALSE WITH_WINPR_DEPRECATED=OFF WITH_WINPR_JSON=ON WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=TRUE WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          Release  
CFLAGS:               -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer  
Compiler:            GNU, 13.3.0  
Target architecture: x64  

* OS version connecting to (server side): Windows Server 2022

**Environment (please complete the following information):**
Operating System: NixOS 24.05 (Uakari)              
Kernel: Linux 6.6.58
Architecture: x86-64

**Comment by akallabeth** [comment]
duplicate, already fixed.
https://github.com/FreeRDP/FreeRDP/pull/10798

**Comment by jcalve** [comment]
This does not work for me on Windows, with neither sdl-freerdp.exe nor wfreerdp.exe (using version 3.9.1-dev).

I wanted to remap caps lock to control, the actual full command is this:

```
wfreerdp.exe /u:xxx /p:xxx /v:xxx /w:1366 /h:768 +clipboard +home-drive -themes -wallpaper /prevent-session-lock:15 /kbd:layout:0x00000409,lang:0x0409,remap:001d=003a -grab-keyboard
```

It fails with the same "invalid entry" error.

**Comment by akallabeth** [comment]
@jcalve well, 
1. `wfreerdp` does not suport that
2. works fine with `sdl-freerdp`, for example `/kbd:remap:0xa=0xb,remap:0xb=0xa` remaps the `9` and `0` keys on a us layout

**Comment by jcalve** [comment]
@akallabeth perhaps I'm using the wrong values but I tried with sdl-freerdp and this parameter `/kbd:remap:001d=003a,remap:003a=001d`, and it fails with this message:

```
Command line parsing failed at 'kbd' value 'remap:001d=003a,remap:003a=001d' 
```
