### ISSUE TITLE
Primary monitor position is incorrectly set to (0, 0) with multimon enabled

### ISSUE THREAD

**Issue by caseif** [FreeRDP/FreeRDP#10811]
When passing the `/multimon` flag to FreeRDP with multiple monitors connected and the primary monitor positioned somewhere other than (0, 0), the primary monitor will incorrectly have its position set to (0, 0) causing erroneous messages about monitor overlaps/gaps. If these messages are suppressed, the connection will still fail (at least for Win11) due to the nonsense configuration being passed.

This occurs because of logic introduced by commit 392a0857280943002b1fffc4a5fd25deedec3ed2 which overrides the primary monitor position as (0, 0) if the fullscreen flag is set. Because multimon implies fullscreen ([here](https://github.com/FreeRDP/FreeRDP/blob/master/client/common/client.c#L262)), this effectively makes the second condition redundant and causes the position to always be overridden. Changing the first condition to `(fullscreen && !multimon)` results in the expected behavior.

I'm submitting this issue instead of creating a PR myself 1) the basic fix is trivial, and 2) I don't fully understand the reasoning behind overriding the coordinate. I imagine that the top-left coordinate of the workspace is still a consideration in this scenario which may require more complex logic to handle platforms that would otherwise cause issues.

**To Reproduce**
1. With multiple monitors attached, position one at (0, 0) and the other somewhere adjacent
2. Set the second monitor as primary
3. Run FreeRDP with `/multimon`
4. Overlap message is displayed in the console output and the program exits

**Expected behavior**
FreeRDP should accept this configuration because it is valid.

**Application details:**
* FreeRDP version: `3.9.1-dev0 (070115e77)`
* Command line used: `sdl-freerdp /v:<host> /u:<user> /multimon`
* Output of `xfreerdp /buildconfig`: See below
* OS version connecting to (server side):** Windows 11 23H2
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`: Likely irrelevant but can provide if required
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help: `master@070115e`, Clang 19.1.0, CMake flags are in the `/buildconfig` output

**Environment:**
 - OS: Linux
 - Version/Distribution: Fedora 41 KDE Spin
 - Architecture: [amd64, arm]: amd64

**`/buildconfig` output:**
```
This is FreeRDP version 3.9.1-dev0 (070115e77)
Build configuration: BUILD_TESTING=OFF BUILD_TESTING_INTERNAL=OFF BUILD_TESTING_INTERNAL_AVAILABLE=1 WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRERROR_R=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_AVX2=ON WITH_AVX2_AVAILABLE=1 WITH_BINARY_VERSIONING=OFF WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CJSON_REQUIRED=OFF WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL2=ON WITH_CLIENT_SDL3=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CLIENT_SDL_AVAILABLE=1 WITH_CLIENT_SDL_VERSIONED=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DOCUMENTATION=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FDK_AAC=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FULL_CONFIG_PATH=OFF WITH_FUSE=ON WITH_GFX_FRAME_DUMP=OFF WITH_GFX_H264=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_INSTALL_CLIENT_DESKTOP_FILES=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_JSONC_REQUIRED=OFF WITH_JSON_DISABLED=OFF WITH_KEYBOARD_LAYOUT_FROM_FILE=OFF WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=ON WITH_PCSC=OFF WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_RESOURCE_VERSIONING=OFF WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SDL_IMAGE_DIALOGS=ON WITH_SDL_LINK_SHARED=ON WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=OFF WITH_SOXR=ON WITH_SSE2=ON WITH_SWSCALE=ON WITH_SYSTEMD=ON WITH_THIRD_PARTY=OFF WITH_TIMEZONE_COMPILED=ON WITH_TIMEZONE_FROM_FILE=OFF WITH_TIMEZONE_ICU=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=ON WITH_WEBVIEW_QT=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_JSON=ON WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          Release
CFLAGS:               -Wno-c11-extensions -Wno-gnu -fno-omit-frame-pointer -O3 -DNDEBUG -Wno-builtin-macro-redefined -D__FILE__='"$(subst /home/max/git/thirdparty/freerdp/build/,,$(subst /home/max/git/thirdparty/freerdp/,,$(abspath $<)))"'
Compiler:            Clang, 19.1.0
Target architecture: x64
```

**Comment by akallabeth** [comment]
Not really trivial.
The check enforces [\[MS-RDPBCGR\]](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-RDPBCGR/%5BMS-RDPBCGR%5D-170123-diff.pdf) restrictions.
The clients have so far never been handling layouts fully correct

So, the only fix here is properly maintaining a coordinate mapping between client and remote coordinate systems

**Comment by caseif** [comment]
Would an interim fix make sense to address this specific regression? I assume the second condition was meant to catch this case, so updating it as in the OP would at least restore the behavior in 3.9.0 for this scenario.

**Comment by akallabeth** [comment]
Will check that next week, only onobile till then

**Comment by xBr0th3rx** [comment]
I have exactly the same problem.

Before I could easily tell from 3 monitors with the /monitor flag that monitor 1 & 2 is windows session and monitor 3 is my main monitor for other applications.

This means that everyone would always have to have the main monitor set to 0,0, which makes no sense to me.

We didn't have any problems with the monitors being arranged incorrectly or anything else before.

It would be great if this could be reversed or at least there would be an option to ignore this.

**Comment by akallabeth** [comment]
@xBr0th3rx a fix is on the roadmap, but will take some time.
we´re identifying issues with regard to the spec and prevent configurations that do not conform for the time being  (yes, annoying for some, but less annoying for us as it is clear this does not work as supposed)

**Comment by xBr0th3rx** [comment]
Can't you first add an option so that you can turn off the check yourself?

Because it sounds like it could take longer ^^

**Comment by akallabeth** [comment]
as we´re receiving more bug reports with it turned on no.

**Comment by xBr0th3rx** [comment]
Okay, I had to go back to version 3.8 for some people because they have laptops with docking stations and 2 additional monitors.

The setup is such that they have monitors 1 & 2 on the left and also have the laptop as a 3rd screen.

With 3.9 it does not work because their main monitor where the bar is displayed is on the right of the laptop because they have monitors 1 & 2 on the left and use them for Windows sessions in full screen.

Because then the error with the overlaps occurs.

In addition, I have the problem with a desktop space with 3 monitors despite the main monitor is set to 0.0 and the monitors are arranged from left to right the error message with overlaps.
See log and screenshot.
[log.txt](https://github.com/user-attachments/files/17975639/log.txt)
![Screenshot_20241202_101935](https://github.com/user-attachments/assets/71cce8e2-4feb-44a1-8a09-56b2627c744f)

/opt/freerdp-nightly/bin/xfreerdp3 /list:monitor
```
[10:16:50:060] [43470:0000a9ce] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
[10:16:50:060] [43470:0000a9ce] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: This build is using [runtime-check] build options:
[10:16:50:060] [43470:0000a9ce] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: * 'WITH_VERBOSE_WINPR_ASSERT=ON'
[10:16:50:060] [43470:0000a9ce] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: 
[10:16:50:060] [43470:0000a9ce] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: [runtime-check] build options might slow down the application
[10:16:50:060] [43470:0000a9ce] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
      * [0] 1920x1080   +0+0
        [1] 1920x1080   +3840+0
        [2] 1920x1080   +1920+0

```
With my desktop space with 3 monitors I don't have the problem because I have my main monitor in the center and not at 0,0 see output:
```
Keyboard Shortcuts:
        <Right CTRL>
                releases keyboard and mouse grab
        <CTRL>+<ALT>+<Return>
                toggles fullscreen state of the application
        <CTRL>+<ALT>+c
                toggles remote control in a remote assistance session
        <CTRL>+<ALT>+m
                minimizes the application
        Action Script
                Executes a predefined script on key press.
                Should the script not exist it is ignored.
                Scripts can be provided at the default location ~/.config/freerdp/action.sh or as command line argument /action:script:<path>
                The script will receive the current key combination as argument.
                The output of the script is parsed for 'key-local' which tells that the script used the key combination, otherwise the combination is forwarded to the remote.
      * [0] 1920x1080   +1920+0
        [1] 1920x1080   +3840+0
        [2] 1920x1080   +0+0

```

**Comment by akallabeth** [comment]
@xBr0th3rx and all your configurations are not properly handled so far.
you can create a list so we can add them to https://github.com/FreeRDP/FreeRDP/blob/6b81b6ed78586f849eec89dd2047934a23dfee6d/libfreerdp/core/test/TestSettings.c#L1295

**Comment by akallabeth** [comment]
@xBr0th3rx ok, thank you for the monitor layouts.
added those monitor configurations to our test suite.
Looks like there was indeed a bug and that is fixed now.

**Comment by xBr0th3rx** [comment]
@akallabeth 
I didn't understand exactly what I was supposed to do or what you meant regarding the config.

**Comment by xBr0th3rx** [comment]
@akallabeth 
I'm really sorry, but either I don't understand you or you don't understand me.

In version 3.8 and before I could tell on which screens I use 2 monitors for my Windows sessions no matter which one is my main monitor, see pictures:

Installed version: “This is FreeRDP version 3.8.0 (3.8.0)”

**Main Monitor in the Middle:**
Output from /list:monitor:
```
      * [0] 1920x1080   +1920+0
        [1] 1920x1080   +3840+0
        [2] 1920x1080   +0+0
```

Command i use to start the Session:
`/opt/freerdp-nightly/bin/xfreerdp3 /d:XXXX /u:XXX /v:XXXX /multimon /monitors:2,0 /sound /clipboard /sec:tls /cert:ignore /dynamic-resolution +auto-reconnect /rfx`

![v3 8 0-main-monitor-middle](https://github.com/user-attachments/assets/b5b16504-e647-412b-8eea-116f53130784)


**Main Monitor Right side:**
Output from /list:monitor: 
```
      * [0] 1920x1080   +3840+0
        [1] 1920x1080   +1920+0
        [2] 1920x1080   +0+0
```

Command i use to start the Session: 
`/opt/freerdp-nightly/bin/xfreerdp3 /d:XXXX /u:XXX /v:XXXX /multimon /monitors:2,1 /sound /clipboard /sec:tls /cert:ignore /dynamic-resolution +auto-reconnect /rfx`

![v3 8 0-main-monitor-right](https://github.com/user-attachments/assets/f8a6868f-0719-4572-82eb-5104dacffdd0)

In version 3.9 it is only possible if the main monitor is also set to 0.0, but why is that?

Because of this I have the problem that users who have a docking station and use monitor 1, monitor 2 and laptop as 3rd monitor and have the laptop on the right and have the laptop as main screen is not possible to say that only monitor 1 & monitor 2 unless they switch the main monitor which then leads to the main bar of the basic system being under the Windows session.

![laptop-screen](https://github.com/user-attachments/assets/d9c37384-2b84-4628-b58c-9eb3cfc409aa)

**Comment by xBr0th3rx** [comment]
@akallabeth 

Thanks for the info.

But what exactly does this mean for me now? Should I open further tickets regarding the problem?

And I will add more information to the screenshots in the future if needed.

**Comment by akallabeth** [comment]
@xBr0th3rx 
1. identify commandline / monitor configurations that do not work but should
2. open a bug with detailed descriptions (command line, mointor layout from `xfreerdp /list:monitor` as well as connection log with `/log-level:trace`)

**Comment by akallabeth** [comment]
@xBr0th3rx please do so using most recent `master` branch, the logging there will greatly help in finding issues.

**Comment by xBr0th3rx** [comment]
@akallabeth 
Okay, I'll do that tomorrow 

Thanks to your help, I now know how I can always build the package from Master Branch 😁.
