### ISSUE TITLE
USB webcam redirection: libusb_control_transfer: error LIBUSB_ERROR_NO_DEVICE[-4]

### ISSUE THREAD

**Issue by Defenso-QTH** [FreeRDP/FreeRDP#10847]
**Describe the bug**
I am trying to forward a built-in USB camera from a FreeBSD client to a Windows 11 server.
To do so I am providing the USB device VID and PID. I am using Remmina as a libfreerdp wrapper.

The Windows machine can see the camera device, and after installing the drivers, it is correctly recognized.
![image](https://github.com/user-attachments/assets/407458c1-a8b8-480e-9fe2-85273634ad54)

However, testing in Microsoft Teams, for instance, the video feed remains empty.
In the xfreerdp logs, I can see the following error message, repeated multiple times:
```
[07:12:37:563] [63884:444bba00] [DEBUG][com.freerdp.channels.urbdrc.client] - libusb_control_transfer: error LIBUSB_ERROR_NO_DEVICE[-4]
```

Complete urbdrc debug log: 
[urbdrc.remmina.log](https://github.com/user-attachments/files/17727548/urbdrc.remmina.log)

**Application details**
* FreeRDP version (`xfreerdp /version`): 2.11.7
* Command line used: (none, using Remmina, USB option: dbg,id:04f2:b7c0
* Output of `xfreerdp /buildconfig`
```
[07:30:35:681] [64787:9c812000] [DEBUG][com.freerdp.utils] - Registering signal hook...
[07:30:35:683] [64787:9c812000] [DEBUG][com.freerdp.client.common.cmdline] - windows: -2004/1 posix: -1000/0 compat: 1/0
This is FreeRDP version 2.11.7 (2.11.7)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_BACKTRACE= HAVE_EXECINFO_BACKTRACE_SYMBOLS= HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD= HAVE_EXECINFO_HEADER=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_PIXMAN_REGION=OFF HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=false WITH_CAIRO=false WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=true WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=1 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=false WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=false WITH_FAAD2=false WITH_FFMPEG=false WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=false WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=true WITH_ICU=true WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=false WITH_LAME=false WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=true WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=false WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=false WITH_PROFILER=OFF WITH_PULSE=false WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=false WITH_SSE2=true WITH_SWSCALE=true WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=true WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -O2 -pipe  -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            Clang, 18.1.5
Target architecture: 
```
* OS version connecting to (server side) : Windows 11 24H2 Version 10.0.26100 Build 26100.2033
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`: I don't think I can do that with Remmina? But I can try to connect with xfreerdpdireclty if that helps.
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help: Nothing specific.

**Environment (please complete the following information):**
 - OS: FreeBSD
 - Version/Distribution: 14.1-RELEASE
 - Architecture: amd64

**Comment by akallabeth** [comment]
@Defenso-QTH better upgrade to `FreeRDP 3.x` as `USB` redirection is not really suitable to redirect high bandwidth devices. (and not all devices allow redirection as multi configuration devices are not supported - which are almost all webcams)
There is experimental [\[MS-RDPECAM\]](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpecam/92af6790-b79c-4813-9c07-7c545bed0242) support in 3.x

**Comment by DaanSelen** [comment]
I also have this issue with the spamming of:

```
[13:31:58:733] [3201:00000da3] [WARN][com.freerdp.channels.drdynvc.client] - [check_open_close_receive]: {URBDRC:11} OnOpen=(nil), OnClose=0x7f0a7c234c80
[13:31:59:731] [3201:00000da3] [WARN][com.freerdp.channels.drdynvc.client] - [check_open_close_receive]: {URBDRC:11} OnOpen=(nil), OnClose=0x7f0a7c234c80
[13:31:59:734] [3201:00000da3] [WARN][com.freerdp.channels.drdynvc.client] - [check_open_close_receive]: {URBDRC:11} OnOpen=(nil), OnClose=0x7f0a7c234c8
```

But I am not using a webcam but a USB flash drive.

**Comment by DaanSelen** [comment]
> I also have this issue with the spamming of:
> 
> ```
> [13:31:58:733] [3201:00000da3] [WARN][com.freerdp.channels.drdynvc.client] - [check_open_close_receive]: {URBDRC:11} OnOpen=(nil), OnClose=0x7f0a7c234c80
> [13:31:59:731] [3201:00000da3] [WARN][com.freerdp.channels.drdynvc.client] - [check_open_close_receive]: {URBDRC:11} OnOpen=(nil), OnClose=0x7f0a7c234c80
> [13:31:59:734] [3201:00000da3] [WARN][com.freerdp.channels.drdynvc.client] - [check_open_close_receive]: {URBDRC:11} OnOpen=(nil), OnClose=0x7f0a7c234c8
> ```
> 
> But I am not using a webcam but a USB flash drive.

I have found the /drives parameter... which I think is intended.
