### ISSUE TITLE
libfreerdp/core/client.c:freerdp_channels_get_id_by_name contradicting return type and value

### ISSUE THREAD

**Issue by DVeron-RC** [FreeRDP/FreeRDP#10863]
Hello I was writting code about channels and tried to use libfreerdp/core/client.c:freerdp_channels_get_id_by_name.

```c
UINT16 freerdp_channels_get_id_by_name(freerdp* instance, const char* channel_name)
{
	rdpMcsChannel* mcsChannel = NULL;
	if (!instance || !channel_name)
		return -1;

	mcsChannel = freerdp_channels_find_channel_by_name(instance->context->rdp, channel_name);
	if (!mcsChannel)
		return -1;

	return mcsChannel->ChannelId;
}
```

There is a missmatch between UINT16 and -1.
A caller has to compare the returned channel with 2^16 - 1 to check for error.
2^16 - 1 is an unlikely but valid channel number.

I thought about 2 ways to fix the issue:
+ change the return type to a broader type, maybe INT32
+ change the error channel number by an invalid channel number,
  I'm not that sure but reading T.125 it looks like 0 is not a valid channel number.

Are you interested ? If so what fix do you think is the best ?

**Comment by akallabeth** [comment]
@DVeron-RC oh, thank you for the hint.
Already created a pr, the version with `0` was already expected (if you check the usage of the function)

not an actual bug though, because `UINT16_MAX` is also considered invalid (which matches `-1` cast to `UINT16`)
