### ISSUE TITLE
screen tearing when I use the command ：xfreerdp /v:xx.xx.xx.xx /u:Administrator /p:xxxxxxxx  +f 

### ISSUE THREAD

**Issue by 94nbzd** [FreeRDP/FreeRDP#10876]
I compiled xfreerdp on my Raspberry Pi, and when I connect using the command xfreerdp /v:xx.xx.xx.xx /u:Administrator /p:xxxxxxxx +f, I encounter screen tearing. The version of xfreerdp I'm using is 2.3.0, and the Xorg version is 1.20.4. However, when I use the command xfreerdp /v:xx.xx.xx.xx /u:Administrator /p:xxxxxxxx +f +gfx-h264, the screen displays normally. Why is this happening?Do I need a GPU on my client side when using gfx?

**Comment by akallabeth** [comment]
this is happening because you are using ancient versions of `FreeRDP`.
add `/network:auto` manually for these old versions or just upgrade to something more recent.

**Comment by 94nbzd** [comment]
I found that after adding the /network:auto parameter, it still ends up calling gfx-related functions. My ultimate goal is to run xfreerdp on an embedded device without GPU acceleration. After adding /network:auto, the mouse can be displayed, but there is no video output. What is the role of gfx? Does it require GPU support?

**Comment by 94nbzd** [comment]
Thank you very much. I found that after adding the /network:auto parameter, it still ends up calling gfx-related functions. My ultimate goal is to run xfreerdp on an embedded device without GPU acceleration. After adding /network:auto, the mouse can be displayed, but there is no video output. What is the role of gfx? Does it require GPU support?

**Comment by akallabeth** [comment]
`gfx` is the graphics transport for windows 8 and newer.
if you do not use that you only get bitmaps sent from the server which is bandwidth hungry and slow (therefore your tearing issues)

I do not understand your question regarding `GPU` though.

**Comment by 94nbzd** [comment]
So, can devices with only a CPU also use GFX technology to connect to Windows 8 and newer?

**Comment by akallabeth** [comment]
> So, can devices with only a CPU also use GFX technology to connect to Windows 8 and newer?

well, you should have a monitor attached?
`FreeRDP` does the encoding/decoding, I don´t know what you want to ask.
It is just a (bunch of) video encoding format(s) with some transport metadata?

**Comment by 94nbzd** [comment]
Yes, xfreerdp can run normally on Raspberry Pi. But it has been confirmed that there is no GPU on the device I will ultimately to deploy xfreerdp. That device calculates the images through the CPU and writes images to the framebuffer for display.In theory, it is possible to decode GFX data without a GPU, but I encountered some issues during deployment that I use GFX, the screen does not display. I'll debug later to see which link went wrong. Thank you very much.

**Comment by akallabeth** [comment]
@94nbzd sorry, what you say does not make any sense at all.

**Comment by 94nbzd** [comment]
My English is poor，Thank you for your patient replay，your answer has already solved my problem.

**Comment by akallabeth** [comment]
ok, then lets hope nothing got lost in translation.
