### ISSUE TITLE
consider using a spell checker on the code

### ISSUE THREAD

**Issue by stephanebill** [FreeRDP/FreeRDP#10879]
Use codespell to fix comments and error messages,
it reports 500+ typos in freerdp 3.9.0 (some are false positives)
e.g.:
./channels/location/client/location_main.c:224: logitude ==> longitude
./libfreerdp/core/redirection.c:1008: eighter ==> either
./libfreerdp/core/rdp.c:2912: repetedly ==> repeatedly, reputedly
./libfreerdp/core/nego.c:1510: explicitely ==> explicitly
./libfreerdp/core/nego.c:1818: lenght ==> length
./libfreerdp/core/settings.c:357: thre ==> three, there, their, the

**Comment by akallabeth** [comment]
@stephanebill happy about pull requests.
