### ISSUE TITLE
Refresh Screen remote session for window server 2012 R2

### ISSUE THREAD

**Issue by srjohny** [FreeRDP/FreeRDP#10890]
I'm doing a remote desktop connection to a windows server 2012 R2 and sometimes the screen does not rendering well, I need wait and or do back to refresh all screen. 

![image](https://github.com/user-attachments/assets/cd13634d-2009-43fe-bd92-d532b924e248)

How can i check the FreeRDP version?

**Comment by akallabeth** [comment]
well, since this is android and obviously not our client I would start asking the supplier?
