### ISSUE TITLE
Unsupported bulk rdp6.1 version

### ISSUE THREAD

**Issue by chengxiaoku** [FreeRDP/FreeRDP#10906]
Problem description:
Microsoft describes in the document that the server will use rdp6.1 version to the client, where the L1 compression algorithm is 6.1 and the L2 compression algorithm is 5.0, as described below:
https://learn.microsoft.com/zh-cn/openspecs/windows_protocols/ms-rdpegdi/c33884de-c58c-43b8-8326-1f93076a0504
I currently use the client compiled by freerdp to connect to the server that comes with win10, transfer files, and download the files on the server to the local computer.
But the request returned by the server does not use 6.1 compression.
Question 1: How can I start the freerdp client so that the server's response uses bulk 6.1 compression?
My current startup method is: wfreerdp /v:192.168.41.11:3389 +compression /compression-level:2 /u:cc123 /p:cc123 > wf.log
Question 2: I saw mppc.c and xcrush.c codes in the freerdp source code. I tried to decompress the 6.1 compressed data packet data by calling the bulk_decompress function in bulk.c, and found that the data was incomplete.

Environment 
- OS：ubuntu

**Comment by akallabeth** [comment]
@chengxiaoku 
1. do not use the `+compression /compression-level:2`  flags client side, let the client and server negotiate what they support
2. microsoft just describes what happens *if*  the server *and*  client support that compression format. That highly depends on configuration settings of both. `FreeRDP` has `PACKET_COMPR_TYPE_RDP61` as default highest support level (`PACKET_COMPR_TYPE_RDP8` is not implemented)

**Comment by chengxiaoku** [comment]
First, I understand that I am calling the C code of freerdp through cgo. I encapsulate the parameters and call bulk_decompress. The logic of xcrush_decompress will appear -1009. In fact, &Literals[OutputLength] > pSrcEnd is established. But the data source is decompressed and output from RDP5.0. Is it a known bug? Or do you need me to provide any other information?

**Comment by akallabeth** [comment]
> First, I understand that I am calling the C code of freerdp through cgo. I encapsulate the parameters and call bulk_decompress. The logic of xcrush_decompress will appear -1009. In fact, &Literals[OutputLength] > pSrcEnd is established. But the data source is decompressed and output from RDP5.0. Is it a known bug? Or do you need me to provide any other information?

ok, you do something and something unexpected happens - sorry, you need to provide a lot more details here.
(best some sample code to check, log output and data dumps to compare) as the data you decompress is very dependent on the configuration that is negotiated.
