### ISSUE TITLE
make passing password more secure: run an external program providing the password (like borgbackup's BORG_PASSCOMMAND)

### ISSUE THREAD

**Issue by jirib** [FreeRDP/FreeRDP#10918]
IIUC, `/p:<password>` is only way to pass password; this makes it not very secure: could be seen in shell history (in process list the password is replaces with asterisks though).

**Describe the solution you'd like**
It would be great if `xfreerdp` could run a command which would print the password to stdout. An example from might be taken from [borgbackup](https://github.com/borgbackup/borg/pull/2573).

**Comment by akallabeth** [comment]
@jirib then don´t use it.
there is `/args-from` which allows reading the whole thing from pipe/file/stdin

**Comment by akallabeth** [comment]
there is also `FREERDP_ASKPASS` env variable that works like the ssh equivalent.

**Comment by jirib** [comment]
Thank you!
