### ISSUE TITLE
rdp bulk 6.1 version, Decompression data missing

### ISSUE THREAD

**Issue by chengxiaoku** [FreeRDP/FreeRDP#10912]
[bulk.c.txt](https://github.com/user-attachments/files/18006581/bulk.c.txt)
[mppc.c.txt](https://github.com/user-attachments/files/18006582/mppc.c.txt)
[xcrush.c.txt](https://github.com/user-attachments/files/18006584/xcrush.c.txt)
The code files related to the decompression algorithm are as above. I have hardly changed the main logic and added some log printing. Because I got the data of the RDP protocol,
so I will call the bulk_decompress_cc function in bulk.c to decompress the data in bulk.
[cc.log](https://github.com/user-attachments/files/18006590/cc.log)

My data sample file is in cc.log. The data in the log:
The data starting with the keyword xcrush-cc-go is the data I passed to bulk_decompress_cc
The data starting with the keyword xcrush-cc-mppc after decompression is the data decompressed by 5.0mppc
The data starting with the keyword xcrush-cc-xcrush after decompression is the data decompressed by 6.1

You can see that the error code -1009 of xcrush decompression failure appears in the log
and part of the decompressed data is missing:
![image](https://github.com/user-attachments/assets/4f1c934c-40b0-497f-93c7-88275326956d)

Original content
![image](https://github.com/user-attachments/assets/3b56b849-b2df-4fec-a82a-895ef77db940)

**Comment by akallabeth** [comment]
@chengxiaoku and what do you want from us?
you do something and it does not work so retry until it does?

or provide a minimal sample that we can compile and analyze to provide some feedback.

not an issue, so closing.
