### ISSUE TITLE
FreeRDP hangs or segfaults on big-endian

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#10926]
**Describe the bug**
FreeRDP on big-endian (s390x) architectures doesn't work properly after upgrading to the 3.9.0 version. See https://issues.redhat.com/browse/RHEL-69446. It hangs, or segfaults. Also, graphical glitches appear...

The major issue seems to be broken critical section handling by the usage of `WINPR_REINTERPRET_CAST` which is not endian-safe when used with differently sized types: https://github.com/FreeRDP/FreeRDP/commit/0d5bc92a2b9af578c9a900ac1af448a41e2b3824#diff-a2069916b3916e0bbc3aabae9c04ba0af985b623b290cee9eca8c7252e8edb0bR909. This is also why `TestSynchCritical` and `TestFreeRDPCodecProgressive` tests fail there. The following change fixes the tests. But I am not sure what the right fix should be as I suppose that  `WINPR_REINTERPRET_CAST` was used here for some very good reason...

```
diff --git a/winpr/libwinpr/thread/thread.c b/winpr/libwinpr/thread/thread.c
index f31c15d99..3267436c7 100644
--- a/winpr/libwinpr/thread/thread.c
+++ b/winpr/libwinpr/thread/thread.c
@@ -913 +913 @@ DWORD GetCurrentThreadId(VOID)
-       return WINPR_REINTERPRET_CAST(tid, pthread_t, DWORD) & 0xffffffffUL;
+       return (DWORD)tid & 0xffffffffUL
```

Also, the `TestCommonAssistance` test fails there. One thing is a regression caused by the following change: https://github.com/FreeRDP/FreeRDP/commit/3674c5c2f7a9db6c05f92dcf97b98e273e92506f. Another thing is that the improved test (https://github.com/FreeRDP/FreeRDP/commit/8e33854c62ab284fcaf56cc0728bae408ddd9f31) revealed a bug there. Reverting the 3674c5c2f7a9db6c05f92dcf97b98e273e92506f commit together with the following dirty change fixes the test:

```
diff --git a/libfreerdp/common/assistance.c b/libfreerdp/common/assistance.c
index e0a368758..1ba2cda0a 100644
--- a/libfreerdp/common/assistance.c
+++ b/libfreerdp/common/assistance.c
@@ -881 +881 @@ BYTE* freerdp_assistance_encrypt_pass_stub(const char* password, const char* pas
-       *((UINT32*)pbIn) = (UINT32)cbPassStubW;
+        *((UINT32*)pbIn) = __builtin_bswap32((UINT32)cbPassStubW);
```

This change obviously won't work on little-endian architectures. I suppose freerdp has some neat macros that could be used there, but I can't find them right now...

I hope that the mentioned changes fix the hangs and segfaults, not just the tests, but I didn't have time to verify that. I will continue with debugging next week. I just wanted to let you know this as it would be nice to have it fixed in 3.10.0...

**Comment by akallabeth** [comment]
@ondrejholy we´re working through the code to unify how casts and similar things are done.
the first looks like a unintended side effect,
the reverted commits are doing something that is obviously not endian safe (and most likely never really was)

for the last thing, you can use `wStream` `API` or the `Data_Write_*` macros in `winpr/include/winpr/endian.h`

**Comment by akallabeth** [comment]
@ondrejholy ok, did create a pr addressing these issues (and also refactor the endianess macros to current `C` standard, they have not been touched in ages)

**Comment by ondrejholy** [comment]
I don't see any graphical glitches or other issues now.

**Comment by akallabeth** [comment]
@ondrejholy great, thx for testing!
