### ISSUE TITLE
Clipboard attaches copied items at the end

### ISSUE THREAD

**Issue by xBr0th3rx** [FreeRDP/FreeRDP#10941]
**Describe the bug**
I copy from local Debian 11 to Windows Terminal Server 2016, this is pasted normally.
If I copy something new, the previous copy is also pasted.

The newly copied is simply appended to the end when pasting.

Copy local: 1234
Paste Windows: 1234

Copy local: 9876
Paste Windows: 
1234
 9876

**Application details**
* FreeRDP version (`xfreerdp /version`)
`This is FreeRDP version 3.9.1-dev0 (31c70979a)`
* Command line used
`/opt/freerdp-nightly/bin/xfreerdp3 /d:XXX /u:XXX /v:XXX /decorations /sound /clipboard /sec:tls /cert:ignore /fonts /dynamic-resolution +auto-reconnect /rfx`
* Output of `xfreerdp /buildconfig`
```
[07:36:31:613] [65877:00010155] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
[07:36:31:613] [65877:00010155] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: This build is using [runtime-check] build options:
[07:36:31:613] [65877:00010155] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: * 'WITH_VERBOSE_WINPR_ASSERT=ON'
[07:36:31:613] [65877:00010155] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: 
[07:36:31:613] [65877:00010155] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: [runtime-check] build options might slow down the application
[07:36:31:613] [65877:00010155] [WARN][com.freerdp.core.rdp] - [log_build_warn][0x623000000100]: *************************************************
This is FreeRDP version [/opt/freerdp-nightly/bin/xfreerdp3] 3.9.1-dev0 (31c70979a)
[/opt/freerdp-nightly/bin/xfreerdp3] Build configuration: BUILD_TESTING=ON BUILD_TESTING_INTERNAL=OFF BUILD_TESTING_INTERNAL_AVAILABLE=0 WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRERROR_R=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_AVX2=ON WITH_BINARY_VERSIONING=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CJSON_REQUIRED=OFF WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL2=ON WITH_CLIENT_SDL3=OFF WITH_CLIENT_SDL_AVAILABLE=1 WITH_CLIENT_SDL_VERSIONED=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DOCUMENTATION=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FDK_AAC=ON WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=ON WITH_FULL_CONFIG_PATH=OFF WITH_FUSE=ON WITH_GFX_FRAME_DUMP=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_INSTALL_CLIENT_DESKTOP_FILES=OFF WITH_INTERNAL_MD4=ON WITH_INTERNAL_MD5=ON WITH_INTERNAL_RC4=ON WITH_JPEG=OFF WITH_JSONC_REQUIRED=OFF WITH_JSON_DISABLED=OFF WITH_KEYBOARD_LAYOUT_FROM_FILE=ON WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_OPUS=ON WITH_OSS=ON WITH_PCSC=ON WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_RESOURCE_VERSIONING=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SDL_IMAGE_DIALOGS=ON WITH_SDL_LINK_SHARED=ON WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SIMD=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SWSCALE=ON WITH_SYSTEMD=ON WITH_THIRD_PARTY=OFF WITH_TIMEZONE_COMPILED=ON WITH_TIMEZONE_FROM_FILE=ON WITH_TIMEZONE_ICU=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=ON WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_JSON=ON WITH_WINPR_TOOLS=ON WITH_WINPR_UTILS_IMAGE_JPEG=ON WITH_WINPR_UTILS_IMAGE_PNG=ON WITH_WINPR_UTILS_IMAGE_WEBP=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -ffile-prefix-map=<src dir>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fno-omit-frame-pointer -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fsanitize=address -fsanitize-address-use-after-scope -O2 -g -DNDEBUG
Compiler:            GNU, 10.2.1
Target architecture: x64
```
* OS version connecting to (server side)
`Windows Terminal Server 2016`
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`
[67914.log](https://github.com/user-attachments/files/18073576/67914.log)

**Environment (please complete the following information):**
 - OS: Linux 
 - Version/Distribution: Debian 11
 - Architecture: amd64

**Comment by ThexXTURBOXx** [comment]
Ah, I just wanted to also create an issue for that. I would also like to mention that this was already a problem two days ago (so, it's not only the newest nightly build).
Furthermore, there are a few additional things to note (Windows is the guest and Linux is the host):
- When copying something from Linux and pasting it into some Windows application via FreeRDP, this issue happens
- When copying something from Windows into either Windows or Linux, it gets pasted just once everytime, as it should be. However, when copying something from Linux after that and pasting it again in Windows, it gets appended to the *previous* copied string (which might even be affected by this issue)

Hence, this is currently a rather typical occurence:
1. Copy `1234` in Linux
2. Paste in Windows yields `1234`
3. Again pasting in Windows yields `12341234`
4. Again pasting in Windows yields `123412341234`
5. Copy `5678` in Windows
6. Paste in Windows yields `5678`
7. Paste in Linux yields `5678`
8. Copy `9101` in Linux
9. Paste in Windows yields `1234123412349101

Also using `xfreerdp` - on Wayland Ubuntu

**Comment by akallabeth** [comment]
@xBr0th3rx @ThexXTURBOXx thx for the ping, overlooked a cache reset for incremental clipboard copy.
should be fixed in the referenced pr, please confirm.

**Comment by xBr0th3rx** [comment]
@akallabeth 
Not yet working.

It works normally the first few times. 

But if you then copy and paste and paste and paste again in the Windows session ... the line is always doubled when pasting.

[195182.log](https://github.com/user-attachments/files/18076972/195182.log)

**Comment by akallabeth** [comment]
@xBr0th3rx can not reproduce.
procedure:
1. copy `1234` on linux
2. paste multiple times
3. copy `5678` on linux
4. paste multiple times
5. ... continue

**Comment by xBr0th3rx** [comment]
@akallabeth 

I Can reproduce this

I Copy lokal in Kate 
1. Test test 1234567890

Paste in Windows
Test test 1234567890

And when Paste again multiple times in windows then i would:
Test test 1234567890 Test test 1234567890

If I then copy a new line again, the line is pasted the first time, but if I then paste it back into Windows and paste again, the copied line is added again until I copy something new

**Comment by ThexXTURBOXx** [comment]
Is there a build for Ubuntu of the latest PR or do I need to compile it myself if I want to test?

**Comment by xBr0th3rx** [comment]
You need to compile Itself 
There is a script in the project 
pull the project and the start the script in the felder 
./packaging/scripts/create_deb.sh them make itself 

Need to install package when comes an error

**Comment by ThexXTURBOXx** [comment]
Thank you :) There are many dependencies missing on my system for the build, so I will just wait until the nightly arrived and report back

**Comment by akallabeth** [comment]
> @akallabeth
> 
> I Can reproduce this
> 
> I Copy lokal in Kate
> 
>     1. Test test 1234567890
> 
> 
> Paste in Windows Test test 1234567890
> 
> And when Paste again multiple times in windows then i would: Test test 1234567890 Test test 1234567890
> 
> If I then copy a new line again, the line is pasted the first time, but if I then paste it back into Windows and paste again, the copied line is added again until I copy something new

so the test I did above that works fine here?

anyway, did add another change to reset the incremental buffer once the data is sent, so this should be fixed in any case, reproducible or not on my setup.

**Comment by xBr0th3rx** [comment]
@akallabeth 
I have tested this again with the latest change and the error no longer occurs.

Thank you very much

**Comment by ThexXTURBOXx** [comment]
I have also tested this on the newest nightly build and it works fine on my end as well! Thank you very much for the quick fix!
