### ISSUE TITLE
Printer with driver specified is redirected but not set as default in RDP session

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#10951]
**Describe the bug**

Printer with driver specified is redirected but not set as default in RDP session

For example:

/u:test /app:program:"||iexplorer",cmd:'"https://example.com"' /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100% /cert:ignore /printer:"queuePrinter","driverPrinter"
![image](https://github.com/user-attachments/assets/9a648c7d-fb62-4884-8db0-e7c04f877ec5)

In version 2.10.0 works, is set as default and if last release xfreerdp is launched with /printer parameter but without specifications works also. 

![image](https://github.com/user-attachments/assets/f4816bca-2b12-4987-8da1-5a5372e628f4)

**Application details**

This is FreeRDP version 3.9.1-dev0 (ae5f655f1)

/u:test /app:program:"||iexplore",cmd:'"https://example.com"' /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100% /cert:ignore   /printer:"queuePrinter","driverPrinter"

OS version connecting to (server side)
Windows Server 2016

OS: Fedora
Version/Distribution: Debian with xfce
Architecture: amd64

**Comment by akallabeth** [comment]
@FutureKidBuu ok, looks like the help was not updated in all places:
```
xfreerdp /? |grep printer
    /printer[: <name>[,<driver>]]     Redirect printer device
Printer Redirection: /printer:<device>,<driver>,[default]
```

you need to manually set the `default` printer now.

**Comment by FutureKidBuu** [comment]
thanks! that was all
