### ISSUE TITLE
Build fails with WITH_SIMD on FreeBSD

### ISSUE THREAD

**Issue by VVD** [FreeRDP/FreeRDP#10967]
**Describe the bug**
Configure stage prints warnings:
```
INTRINSIC_TYPE=sse2: not supported on target platform, ignoring
INTRINSIC_TYPE=neon: not supported on target platform, ignoring
INTRINSIC_TYPE=sse2: not supported on target platform, ignoring
INTRINSIC_TYPE=sse3: not supported on target platform, ignoring
INTRINSIC_TYPE=ssse3: not supported on target platform, ignoring
INTRINSIC_TYPE=sse4.1: not supported on target platform, ignoring
INTRINSIC_TYPE=sse4.2: not supported on target platform, ignoring
INTRINSIC_TYPE=avx2: not supported on target platform, ignoring
INTRINSIC_TYPE=neon: not supported on target platform, ignoring
```
```cmake
message(NOTICE "${CMAKE_C_COMPILER_ID} ${CMAKE_SYSTEM_PROCESSOR}")
```
prints
```
Clang amd64
```
After this there are a lot of errors during compile:
```
/tmp/work/usr/ports/net/freerdp3/work/freerdp-3.10.0/libfreerdp/primitives/sse/prim_copy_avx2.c:55:23: error: always_inline function '_mm256_set_epi32' requires target feature 'avx', but would be inlined into function 'avx2_image_copy_bgr24_bgrx32' that is compiled without support for 'avx'
    55 |         const __m256i mask = _mm256_set_epi32(0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
```

**To Reproduce**
1. Build with `WITH_SIMD` option on and `CFLAGS=-march=core2`.
2. See warnings during configure stage.
3. See errors during build stage.

**Expected behavior**
Build without errors.

**Application details**
- FreeRDP version (`xfreerdp /version`) - 3.10.0

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..] FreeBSD 14.1-p6 amd64
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10] FreeBSD ports: https://www.freshports.org/net/freerdp3
 - Architecture: [amd64, arm]: amd64

**Additional context**
Patch tested on FreeBSD 14.1-p6 amd64:
```diff
--- cmake/DetectIntrinsicSupport.cmake.orig     2024-12-13 19:21:11 UTC
+++ cmake/DetectIntrinsicSupport.cmake
@@ -19,8 +19,8 @@ macro(set_simd_source_file_properties INTRINSIC_TYPE)
   set(GCC_CLANG_NAMES "AppleClang;Clang;CrayClang;FujitsuClang;GNU;IntelLLVM;TIClang;XLClang;IBMClang")

   set(SSE_X86_LIST "i686;x86;X86")
-  set(SSE_LIST "x86_64;ia64;x64;AMD64;IA64;EM64T;${SSE_X86_LIST}")
-  set(NEON_LIST "arm;armv7;armv8b;armv8l")
+  set(SSE_LIST "x86_64;ia64;x64;amd64;AMD64;IA64;EM64T;${SSE_X86_LIST}")
+  set(NEON_LIST "aarch64;arm;armv6;armv7;armv8b;armv8l")
   set(SUPPORTED_INTRINSICS_LIST "neon;sse2;sse3;ssse3;sse4.1;sse4.2;avx2")

   if(NOT "${INTRINSIC_TYPE}" IN_LIST SUPPORTED_INTRINSICS_LIST)
```
On FreeBSD 64bit x86 architecture have name `amd64`, 64bit ARM have name `aarch64`, also there are `armv6` and `armv7`:
https://man.freebsd.org/cgi/man.cgi?query=arch&manpath=FreeBSD+15.0-CURRENT

**Comment by akallabeth** [comment]
@VVD thx for the bug report.
so basically shoud be a case insensitive compare?
(`aarch64` is, as mentioned in the matrix channel, not to be added as no linker flag is required there)
