### ISSUE TITLE
wfreerdp not available after e375556 with Windows 11

### ISSUE THREAD

**Issue by tsz8899** [FreeRDP/FreeRDP#10983]
VS2022 and nightly can successfully compile e375556
windows 10 run wfreerdp is ok

but  windows 11 ltsc run wfreerdp error,does not work properly.  
It cannot connect to a session,  no response or error output
and it cannot even output the help information for `wfreerdp /?` in the command window.

**Comment by akallabeth** [comment]
@tsz8899 looks like a bug with getting the hostname.
work around with argument `/client-hostname:yourname` for the time being.

as for the terminal output, that did not change ;)
if you need output from `wfreerdp` you need to redirect to a file

**Comment by xBr0th3rx** [comment]
The fix works for me both with /client-hostname: and without.

Version: This is FreeRDP version 3.10.2-dev0 (1b6fb6fd4)

Command i use: /opt/freerdp-nightly/bin/xfreerdp3 /d:XXX /u:XXX /v:XXXX /decorations /sound /clipboard /sec:tls /cert:ignore /fonts /dynamic-resolution +auto-reconnect /rfx
