### ISSUE TITLE
Missing wtypes.h

### ISSUE THREAD

**Issue by jbicha** [FreeRDP/FreeRDP#11009]
The Debian/Ubuntu builds are failing because they expect wtypes.h to be available in the **build directory's**  `winpr/include/winpr` but it is not there.

**Application details**
* FreeRDP version 3.10.2 with cherry-picked af41563d6ba20b9e1678ddf2e6c83e541df48e67 and 91ae892f91b4a1d1f4a3595702999528dadf2677 which should be functionally equivalent to 3.10.3 which was tagged but not reelased

**Environment (please complete the following information):**
 - Debian Unstable or Ubuntu 25.04
 - All architectures

**Additional context**

Full build log available at https://launchpad.net/~jbicha/+archive/ubuntu/arch/+sourcepub/16820385/+listing-archive-extra Click amd64

**Comment by akallabeth** [comment]
@jbicha we've reworked the `wtypes.h` header, it is no longer auto generated but a normally installed header file.
adjust your debian build config.
