### ISSUE TITLE
Build fails with be3ba1c4 for windows

### ISSUE THREAD

**Issue by tsz8899** [FreeRDP/FreeRDP#11025]
vs2022 build error info:
Severity Code Description The item file line does not display status details

Error (Active) E0020 does not define identifier "rc" libusb_udevman.c.O.BJ (channels\urbdrc\client\libusb\CMakeFiles\urbdrc-client-libusb.dir\libusb_udevman.c.obj) -  x86-Release	\FreeRDP\channels\urbdrc\client\libusb\libusb_udevman.c	928

The message VCR003 function "FREERDP_ENTRY_POINT" can be a static function D:\dev\FreeRDP\channels\urbdrc\client\libusb\ libusb_udevman.c 899

Message lnt-uninitialized-local The local variable was not initialized. libusb_udevman.c.obj  (channels\urbdrc\client\libusb\CMakeFiles\urbdrc-client-libusb.dir\libusb_udevman.c.obj)	D:\dev\FreeRDP\channels\urbdrc\ client\libusb\libusb_udevman.c	582

Error C2065 "rc" : Undeclared identifier D:\dev\FreeRDP\out\build\x86-Release\FreeRDP D:\dev\FreeRDP\channels\urbdrc\client\libusb\ libusb_udevman.c 928 929 935 938

**Comment by akallabeth** [comment]
@tsz8899 happy about pull requests.

need to adjust the ci builders first to cover these parts (`libusb` on windows)
