### ISSUE TITLE
The problems encountered with audio redirection in Ubuntu.

### ISSUE THREAD

**Issue by zhangxj21** [FreeRDP/FreeRDP#11027]
Ubuntu audio capture related, assuming the use of PulseAudio for system audio capture, how is the captured audio delivered to the FreeRDP server? In the server code, I saw the following code, which should receive audio data and send it to the client, but I can't find who sends this audio data, and I searched the entire code directory and couldn't find it.
case SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES_ID:
{
	const SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES* msg =
			  (const SHADOW_MSG_OUT_AUDIO_OUT_SAMPLES*)message->wParam;

	WINPR_ASSERT(msg);

	if (client->activated && client->rdpsnd && client->rdpsnd->Activated)
	{
		client->rdpsnd->src_format = msg->audio_format;
		IFCALL(client->rdpsnd->SendSamples, client->rdpsnd, msg->buf, msg->nFrames,
				     msg->wTimestamp);
	}

	break;
}

**Comment by akallabeth** [comment]
from your audio source.
there is currently no implementation in `FreeRDP` but only gnome-remote-desktop and ogon.

**Comment by zhangxj21** [comment]
thanks very much，Are you saying that when Ubuntu is used as a server, it is unable to redirect audio to the client?
If it is possible to redirect to the client, how should it be configured? Are there any relevant documents or links? I tried using PulseAudio but failed.

**Comment by akallabeth** [comment]
@zhangxj21 as you did never mention which application you use I can´t answer your question correctly.
(if it is freerdp shadow server, then no, that one does not support that, gnome-remote-desktop does)

**Comment by zhangxj21** [comment]
Thank you again for your response, I understand now, I am using the FreeRDP Shadow Server, and this version currently does not support audio redirection.
