### ISSUE TITLE
RemoteApp closing application by Close button (top right X button) doesn't close the xfreerdp console program

### ISSUE THREAD

**Issue by bakytn** [FreeRDP/FreeRDP#1105]
RemoteApp closing application by Close button (top right X button) doesn't close the xfreerdp console program.

Environment:
1. xfreerdp Latest GIT version (cmake with -DWITH_FFMPEG=NO)
2. Linux Ubuntu 12.10

How to reproduce:
1. Run any remote app in Linux (xfreerdp) with any params
2. Close by clicking the top right close button
3. See the console app is still working

Expected:
xfreerdp would close too

**Comment by cpfeiffer** [comment]
This still happens with xfreerdp 2.0.0~git20161130.1.e60d0d5+dfsg1 on Debian.

> [10:26:50:263] [8202:8203] [INFO][com.freerdp.core] - ERRINFO_RPC_INITIATED_DISCONNECT_BY_USER (0x0000000B):The disconnection was initiated by an administrative tool on the server running in the user's session.

Is there another option to disconnect locally without killing xfreerdp?

**Comment by Victor2kyang** [comment]
This still exists in version 2.3.2

**Comment by akallabeth** [comment]
@Victor2kyang and it will never change, this is by design of the protocol.
There are always some things running (e.g. tray icons, ...) and only the server knows when to close the connection in rails mode.

**Comment by Victor2kyang** [comment]
> @Victor2kyang and it will never change, this is by design of the protocol.
> There are always some things running (e.g. tray icons, ...) and only the server knows when to close the connection in rails mode.

@akallabeth 
so sad T.T , but thanks for your reply.
