### ISSUE TITLE
error occus: ...Unknown CMake command "set_complex_link_libraries"...

### ISSUE THREAD

**Issue by jiangzi** [FreeRDP/FreeRDP#1113]
error when cross-compile android client jni code: 
CMake Error at CMakeLists.txt:47 (set_complex_link_libraries):
  Unknown CMake command "set_complex_link_libraries".

I figure out this is a macro defined in file ComplexLibrary.cmake.
How can i reference this file during my cross-compile process?  Should i compile in which ENV setup and start at which directory?

**Comment by YangLi20** [comment]
hello,i met also error  when i build iOS  code , the reason is " Unknown CMake command "set_complex_link_libraries" ", Before you is how to solve? thank you.

**Comment by hardening** [comment]
@YangLi20 There's no point to add your comment on a closed issue. Continue your investigations before asking !
