### ISSUE TITLE
Does freerdp (linux or windows) support reconnect after a network failure?

### ISSUE THREAD

**Issue by macarthor** [FreeRDP/FreeRDP#1120]
My teammates have some network failure when using xfreerdp/wfreerdp, of course the failure is not because of freerdp. But freerdp windows would have no response to mouse or keyboard when network failure occurs, and it would no reconnect the rdp session when network becomes usable.

I wonder if there's some options or implicit flags in the codes to reconnect rdp session, or such feature has not been implemented yet.

**Comment by akallabeth** [comment]
Autoreconnect is implemented (at least on linux)
