### ISSUE TITLE
freerdp vs. keyboards

### ISSUE THREAD

**Issue by nschneider** [FreeRDP/FreeRDP#1123]
Whenever I login via freerdp to a remote machine, I get an english kbd layout. And whenever I open a new window on the remote machine, it gets switched back to english and this is a major pita.
I found this link: http://social.msdn.microsoft.com/Forums/de-DE/windows7de/thread/019ecd9f-3ef4-426c-af6b-3b03966099b9/

Which provides this workaround:

Create a REG_DWORD "IgnoreRemoteKeyboardLayout=1" in the registry at
 [HKEY_LOCAL_MACHINE][SYSTEM][CurrentControlSet][Control][Keyboard Layout]

From this workaround I assume that freerdp somehow communicates the keyboard I have to the remote machine and does so wrong.

**Comment by hardening** [comment]
no feedback, closing.
