### ISSUE TITLE
geometry percentage no longer available

### ISSUE THREAD

**Issue by robled** [FreeRDP/FreeRDP#1139]
I'm running this recently updated package from the Ubuntu PPA:  1.0.1-2ubuntu1.1freerdp1~1265+31~quantal1

In this version the new command line syntax is present.  I've found that the legacy -g P% and new /size options no longer allow a geometry percentage to be specified.  1024x768 seems to be a fallback default when a percentage is specified.

Has this feature been removed or has the syntax changed?

**Comment by akallabeth** [comment]
Current 2.0.0-rc0 already supports ```/size:<width>x<height> or <percent>%[wh]```
