### ISSUE TITLE
Problem with spaces on directories and files

### ISSUE THREAD

**Issue by praelet** [FreeRDP/FreeRDP#1176]
Hi all,

I am using freerdp to run remoteapps and open specific files with the desired application, and it seems to work fine apart from when the path or file that I require to open contains some spaces.

Ex: "C:\a a\test.doc"

I have tried this with debian wheezy and freerdp 1.0.1 and 1.1.0 versions with the following parameters when calling the remote application:

Version 1.0.1 :

"||winword:%SYSTEMDIR%\a a:%SYSTEMDIR%\a a\test.doc"

"||winword":"%SYSTEMDIR%\a a":"%SYSTEMDIR%\a a\test.doc"

||winword:%SYSTEMDIR%\a a:%SYSTEMDIR%\a a\test.doc

Version 1.1.0:

/app:"||winword" /app-cmd:"z:\a a\test.doc"
/app:"||winword" /app-cmd:"%SYSTEMDIR%\a a\test.doc"

But Microsoft Word is trying to open "C:\a" instead of "C:\a a\test.doc" .

Regards

**Comment by JesusMcCloud** [comment]
How would I pass a variable containing spaces as a single argument?
