### ISSUE TITLE
ClipBoard, visual studio 2012 windows 2008 R2

### ISSUE THREAD

**Issue by eltrikiman** [FreeRDP/FreeRDP#1179]
I am currently using remoteAPP  windows 2008 R2
 (chrome 26, VS2012, ie9, SQL 2008)

in window's visual studio 2012  frame (restore mode)  have marco
clipboard does not work  (very important)

**Comment by bmiklautz** [comment]
Fixed on current master. If the problem still exists for you please re-open the issue or create a new one.
