### ISSUE TITLE
The big problem ifreerdp! Because Apple abandoned the OpenSSL now cause I do not build him, please pay attention to!

### ISSUE THREAD

**Issue by yglaas** [FreeRDP/FreeRDP#1192]
Hello:
Most recent concern ios ifreerdp, I use multiple versions of the master and tag, found that the dependent openssl armv7 and armv7s of build is unsuccessful, use the command reference README.ios.

See here:
https://devforums.apple.com/message/803477#803477

I asked a compiler to Apple after discussions, they say I gave up in the schema using the openssl. I use README.ios compilation, I do not understand why I compiled unsuccessful, how did you do that. If it is not a bug, please help me see where I have a problem.
But it looks like the updated version of the result of a bug.

I is the Macbook, OS X 10.8.2, Xcode 4.6.1, sdk 6.1.
Compiled parameters are behind CC to add-V.

The armv7‘s makefile：

VERSION=1.0.0e
MAJOR=1
MINOR=0.0
SHLIB_VERSION_NUMBER=1.0.0
SHLIB_VERSION_HISTORY=
SHLIB_MAJOR=1
SHLIB_MINOR=0.0
SHLIB_EXT=.$(SHLIB_MAJOR).$(SHLIB_MINOR).dylib
PLATFORM=darwin-armv7-cc
OPTIONS= no-gmp no-jpake no-krb5 no-md2 no-rc5 no-rfc3779 no-shared no-store no-zlib no-zlib-dynamic static-engine
CONFIGURE_ARGS=darwin-armv7-cc
SHLIB_TARGET=darwin-shared
# HERE indicates where this Makefile lives.  This can be used to indicate
# where sub-Makefiles are expected to be.  Currently has very limited usage,
# and should probably not be bothered with at all.

HERE=.
# INSTALL_PREFIX is for package builders so that they can configure
# for, say, /usr/ and yet have everything installed to /tmp/somedir/usr/.
# Normally it is left empty.

INSTALL_PREFIX=
INSTALLTOP=/usr/local/ssl
# Do not edit this manually. Use Configure --openssldir=DIR do change this!

OPENSSLDIR=/usr/local/ssl

CC= /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc -v
CFLAG= -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk -O3 -fomit-frame-pointer -DL_ENDIAN
DEPFLAG= -DOPENSSL_NO_GMP -DOPENSSL_NO_JPAKE -DOPENSSL_NO_MD2 -DOPENSSL_NO_RC5 -DOPENSSL_NO_RFC3779 -DOPENSSL_NO_STORE
PEX_LIBS= -Wl,-search_paths_first
EX_LIBS= 
EXE_EXT= 
ARFLAGS= 
AR= ar $(ARFLAGS) r
RANLIB= /usr/bin/ranlib
NM= nm
PERL= /usr/bin/perl
TAR= tar
TARFLAGS= --no-recursion
MAKEDEPPROG=makedepend
LIBDIR=lib

AS=$(CC) -c
ASFLAG=$(CFLAG)
.....

The end of Log:

Using built-in specs.
Target: arm-apple-darwin10
Configured with: /private/var/tmp/llvmgcc42_Embedded/llvmgcc42_Embedded-2410.2~111/src/configure --enable-checking --enable-werror --prefix=/Developer/usr/llvm-gcc-4.2 --mandir=/share/man --enable-languages=c,objc,c++,obj-c++ --program-prefix=llvm- --program-transform-name=/^[cg][^.-]_$/s/$/-4.2/ --with-slibdir=/usr/lib --disable-tls --build=i686-apple-darwin10 --enable-llvm=/private/var/tmp/llvmgcc42_Embedded/llvmgcc42_Embedded-2410.2~111/dst-llvmCore/Developer/usr/local --program-prefix=arm-apple-darwin10- --host=x86_64-apple-darwin10 --target=arm-apple-darwin10 --with-gxx-include-dir=/usr/include/c++/4.2.1 --with-build-sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.Internal.sdk
Thread model: posix
gcc version 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2410.2.00)
 /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/llvm-gcc-4.2/bin/../libexec/gcc/arm-apple-darwin10/4.2.1/collect2 -dynamic -arch armv7 -iphoneos_version_min 3.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk -weak_reference_mismatches non-weak -o openssl -lcrt1.o -L.. -L.. -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/llvm-gcc-4.2/bin/../lib/gcc/arm-apple-darwin10/4.2.1/v7 -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk/usr/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/llvm-gcc-4.2/bin/../lib/gcc/arm-apple-darwin10/4.2.1 -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/llvm-gcc-4.2/bin/../lib/gcc -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/llvm-gcc-4.2/bin/../lib/gcc/arm-apple-darwin10/4.2.1/../../.. openssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o -search_paths_first -lssl -lcrypto -lgcc_s.1 -lgcc -lSystem
Undefined symbols for architecture armv7:
  "_accept$UNIX2003", referenced from:
      _do_server in s_socket.o
      _BIO_accept in libcrypto.a(b_sock.o)
  "_bind$UNIX2003", referenced from:
      _do_server in s_socket.o
      _BIO_get_accept_socket in libcrypto.a(b_sock.o)
  "_chmod$UNIX2003", referenced from:
      _RAND_write_file in libcrypto.a(randfile.o)
  "_close$UNIX2003", referenced from:
      _sv_body in s_server.o
      _s_client_main in s_client.o
      _speed_main in speed.o
      _s_time_main in s_time.o
      _init_client in s_socket.o
      _do_server in s_socket.o
      _acpt_ctrl in libcrypto.a(bss_acpt.o)
      ...
  "_closedir$UNIX2003", referenced from:
      _OPENSSL_DIR_end in libcrypto.a(o_dir.o)
  "_connect$UNIX2003", referenced from:
      _init_client in s_socket.o
      _conn_state in libcrypto.a(bss_conn.o)
      _BIO_get_accept_socket in libcrypto.a(b_sock.o)
      _RAND_query_egd_bytes in libcrypto.a(rand_egd.o)
  "_fdopen$UNIX2003", referenced from:
      _speed_main in speed.o
  "_fopen$UNIX2003", referenced from:
      _enc_main in enc.o
      _BIO_new_file in libcrypto.a(bss_file.o)
      _file_ctrl in libcrypto.a(bss_file.o)
      _RAND_load_file in libcrypto.a(randfile.o)
      _RAND_write_file in libcrypto.a(randfile.o)
      _open_console in libcrypto.a(ui_openssl.o)
  "_fputs$UNIX2003", referenced from:
      _main in openssl.o
      _BIO_debug_callback in libcrypto.a(bio_cb.o)
      _write_string in libcrypto.a(ui_openssl.o)
      _read_string in libcrypto.a(ui_openssl.o)
  "_fstat$INODE64", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
  "_fwrite$UNIX2003", referenced from:
      _check in verify.o
      _req_main in req.o
      _dsa_main in dsa.o
      _speed_main in speed.o
      _s_time_main in s_time.o
      _load_index in apps.o
      _write_fp in libcrypto.a(b_dump.o)
      ...
  "_getsockname$UNIX2003", referenced from:
      _s_client_main in s_client.o
  "_listen$UNIX2003", referenced from:
      _do_server in s_socket.o
      _BIO_get_accept_socket in libcrypto.a(b_sock.o)
  "_open$UNIX2003", referenced from:
      _RAND_poll in libcrypto.a(rand_unix.o)
  "_opendir$INODE64$UNIX2003", referenced from:
      _OPENSSL_DIR_read in libcrypto.a(o_dir.o)
  "_read$UNIX2003", referenced from:
      _raw_read_stdin in apps.o
      _conn_read in libcrypto.a(bss_conn.o)
      _fd_read in libcrypto.a(bss_fd.o)
      _fd_gets in libcrypto.a(bss_fd.o)
      _sock_read in libcrypto.a(bss_sock.o)
      _RAND_query_egd_bytes in libcrypto.a(rand_egd.o)
      _RAND_poll in libcrypto.a(rand_unix.o)
      ...
  "_readdir$INODE64", referenced from:
      _OPENSSL_DIR_read in libcrypto.a(o_dir.o)
  "_recvfrom$UNIX2003", referenced from:
      _dgram_read in libcrypto.a(bss_dgram.o)
  "_select$UNIX2003", referenced from:
      _sv_body in s_server.o
      _s_client_main in s_client.o
      _doConnection in s_time.o
      _process_responder in ocsp.o
      _RAND_poll in libcrypto.a(rand_unix.o)
  "_sendto$UNIX2003", referenced from:
      _dgram_write in libcrypto.a(bss_dgram.o)
  "_sleep$UNIX2003", referenced from:
      _www_body in s_server.o
  "_stat$INODE64", referenced from:
      _app_isdir in apps.o
      _RAND_load_file in libcrypto.a(randfile.o)
      _RAND_write_file in libcrypto.a(randfile.o)
      _get_cert_by_subject in libcrypto.a(by_dir.o)
  "_strerror$UNIX2003", referenced from:
      _ERR_load_ERR_strings in libcrypto.a(err.o)
  "_write$UNIX2003", referenced from:
      _raw_write_stdout in apps.o
      _conn_write in libcrypto.a(bss_conn.o)
      _dgram_write in libcrypto.a(bss_dgram.o)
      _fd_write in libcrypto.a(bss_fd.o)
      _fd_puts in libcrypto.a(bss_fd.o)
      _sock_write in libcrypto.a(bss_sock.o)
      _sock_puts in libcrypto.a(bss_sock.o)
      ...
ld: symbol(s) not found for architecture armv7
collect2: ld returned 1 exit status
make[2]: *_\* [link_app.] Error 1
make[1]: **\* [openssl] Error 2
make: **\* [build_apps] Error 1

**Comment by huangjunsong** [comment]
@yglaas I got the same problem as your's.Can you tell me how to change the header search path?
