### ISSUE TITLE
TSGateway Consent Signing Message and administrative message

### ISSUE THREAD

**Issue by MartinHaimberger** [FreeRDP/FreeRDP#1195]
The  Consent Signing Message and administrative message are missing according to TS Gateway specification. These messages are part of the TsProxyMakeTunnelCall. See blow for the Message structure.

http://msdn.microsoft.com/en-us/library/dd357419.aspx

Nice regards,
Martin Haimberger

**Comment by akallabeth** [comment]
@MartinHaimberger Added as a first step callbacks that can be implemented by a client to present it to the user.
For existing command line clients there is already a `WLog` message printed.
