### ISSUE TITLE
freerdp /printer does not work on ubuntu

### ISSUE THREAD

**Issue by ban87** [FreeRDP/FreeRDP#1197]
I'm trying to start xfreerdp on ubuntu as follows:

xfreerdp /u:user /p:pass /v:192.168.1.2 /printer:PDF,PDF

I got following output:

loading channel rdpdr
loading channel rdpsnd
connected to 192.168.1.2:3389
Loading device service printer (static)
Segmentation fault (core dumped)

I got this backtrace:

No symbol table info available.
#1  0x0020f8a0 in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:42

```
    resultvar = <value optimized out>
    resultvar = <value optimized out>
    pid = <value optimized out>
```
#2  0x00ebd0d9 in fatal_handler (signum=11) at /home/user/Tmp/FreeRDP/libfreerdp/utils/signal.c:64

```
    default_sigaction = {__sigaction_handler = {sa_handler = 0, sa_sigaction = 0}, sa_mask = {__val = {2147483647, 4294967294, 4294967295 <repeats 30 times>}}, sa_flags = 0, 
      sa_restorer = 0}
    this_mask = {__val = {1024, 0 <repeats 31 times>}}
```
#3  <signal handler called>

No symbol table info available.
#4  0x0022fb1e in DeviceServiceEntry () from /usr/local/lib/freerdp/printer-client.so

No symbol table info available.
#5  0x00131990 in devman_load_device_service (devman=0x818cf28, device=0x8161c98) at /home/user/Tmp/FreeRDP/channels/rdpdr/client/devman.c:112

```
    ServiceName = 0x15096e "printer"
    ep = {devman = 0x818cf28, RegisterDevice = 0x131840 <devman_register_device>, device = 0x8161c98}
    entry = 0x22fb00 <DeviceServiceEntry>
```
#6  0x0012fbe5 in rdpdr_process_connect (plugin=0x8155f00) at /home/user/Tmp/FreeRDP/channels/rdpdr/client/rdpdr_main.c:63

```
    index = 0
    device = 0x8161c98
    settings = 0x80e3d80
    rdpdr = 0x8155f00
```
#7  0x00ebd7ec in svc_plugin_thread_func (arg=0x8155f00) at /home/user/Tmp/FreeRDP/libfreerdp/utils/svc_plugin.c:188

```
    data = 0x0
    event = 0x0
    message = {id = 0, context = 0x0, wParam = 0x0, lParam = 0x0, time = 0, Free = 0}
    plugin = 0x8155f00
```
#8  0x00206e99 in start_thread (arg=0xb6e5bb70) at pthread_create.c:304

```
    pd = 0xb6e5bb70
    unwind_buf = {cancel_jmp_buf = {{jmp_buf = {2191348, 0, 4001536, -1226460008, -483017773, 1754138814}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, 
          cleanup = 0x0, canceltype = 0}}}
    not_first_call = <value optimized out>
    robust = <value optimized out>
    pagesize_m1 = <value optimized out>
    sp = <value optim
```

Does anyone knows where could be a problem?

**Comment by akallabeth** [comment]
Printer redirection should work with #3165

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
