### ISSUE TITLE
inst->rdp_check_fds failed  Windows server 2008

### ISSUE THREAD

**Issue by pisix** [FreeRDP/FreeRDP#1201]
I am able to shutdown a computer running WINDOWS SERVER 2003 SP2  by RDP without any error but  
When I try the same thing on  a computer running  WINDOWS SERVER 2008 R2   I have This Error "ios_run_freerdp: inst->rdp_check_fds failed." How can I fix it?? 
Thanks in advance .

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
