### ISSUE TITLE
Lost screen real estate when using bluetooth keyboard on iOS

### ISSUE THREAD

**Issue by bslande** [FreeRDP/FreeRDP#1204]
When I use a bluetooth keyboard in iOS, the black screen is still there for the virtual keyboard.  This seems to be an artifact of the extra keys, but should not be needed unless the other keyboard is selected.

**Comment by glitchphan** [comment]
There's some way other rdp clients keep input from physical keyboards enabled all the time, not requiring the onscreen one to be brought up. Those usually have working shift and ctrl too. This is my favorite rdp client on iOS but the keyboard thing is a huge annoyance.
