### ISSUE TITLE
No user send with smartcard redirection

### ISSUE THREAD

**Issue by fabdim** [FreeRDP/FreeRDP#1209]
Hi,

I am using freerdp to connect to Windows 2003 server with a smartcard (CPS carte from ASIP Santé). From the server log it seems that freerdp does not send the user name which is correctly read from the card?

Here is my client configuration:
- Linux Fedora 12
- freerdp stable 1.0.3-dev or freerdp master 1.1.0-beta1
- xfreerdp /v:217.119.188.206 /smartcard:scard

Please note that connecting from a Windows client using mstsc.exe works perfectly.

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
