### ISSUE TITLE
Server 2012 VDI - Connection

### ISSUE THREAD

**Issue by petegriggs** [FreeRDP/FreeRDP#1210]
Hello !

We have a server 2012 RDS Server with a RD Gateway / Connection Broker. We can RDP directly into the virtual machines behind the broker but if we attempt to access the broker it will not connect.

We have disabled NLA. Does anyone have any ideas?

Cheers

Peter

**Comment by akallabeth** [comment]
still an issue?

**Comment by akallabeth** [comment]
No feedback, closing.
