### ISSUE TITLE
Smartcard redirect not working I think (Mac)

### ISSUE THREAD

**Issue by Ryukain** [FreeRDP/FreeRDP#1220]
Hello all, 

First of all thank you for making such a great rdp client. I am slightly stuck though and I am not sure whether this is down to my own stupidity. 
I started playing around with rdekstop but got stuck as this did not support NLA, then I found FreeRDP! Yay, so I installed it via MacPorts got it all running and NLA works flawlessly. 

Now for the stupid part, I managed to use a eToken perfectly fine with rdesktop but now when I just try xfreerdp /u:username /p:password /d:domain /v:192.168.168.60 /smartcard
I managed to get in perfectly, but the token is not being picked up. 

Running pcsctest in terminal shows the token;
Testing SCardEstablishContext    : Command successful.
Testing SCardGetStatusChange 
Please insert a working reader   : Command successful.
Testing SCardListReaders         : Command successful.
Reader 01: Aladdin eToken PRO USB 72K Java 00 00

So did I maybe make a mistake by installing it via MacPorts?
The version that got installed was "This is FreeRDP version 1.1.0-beta1 (git n/a)"

Hopefully you can help! :) Thank you for reading. 

Regards,
Ryuk

**Comment by sconstantine** [comment]
Any progress or updates to smart card redirection?

**Comment by sconstantine** [comment]
Any progress or updates to smart card redirection support with OS X?

**Comment by bmiklautz** [comment]
I tested with the latest master (openssl from ports and compiled maually) and at least for my testing it worked on macOS (High Sierra).
Closing this issue. If you still see this issue please re-open or recreate a new one.
