### ISSUE TITLE
iOS Build Error: library not found for -lwinpr-environment 

### ISSUE THREAD

**Issue by ghillam** [FreeRDP/FreeRDP#1234]
I am getting the following error when trying the iOS build to device.

ld: library not found for -lwinpr-environment
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by YangLi20** [comment]
When compiling the iOS code, I met a mistake does not support architecture，Have met or know?The following is the error log

-- Configuring incomplete, errors occurred!
See also "/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeOutput.log".
See also "/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeError.log".

yangli:FreeRDP-1.1.0-beta1-ios4 yangli$ cat /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeError.log
Determining if files fcntl.h exist failed with the following output:

Source:
/* */
#include

int main(){return 0;}

Determining if files unistd.h exist failed with the following output:

Source:
/* */
#include

int main(){return 0;}

Determining if files stdint.h exist failed with the following output:

Source:
/* */
#include

int main(){return 0;}

Determining if files inttypes.h exist failed with the following output:

Source:
/* */
#include

int main(){return 0;}

Determining if files sys/modem.h exist failed with the following output:

Source:
/* */
#include

int main(){return 0;}

Determining if files sys/filio.h exist failed with the following output:

Source:
/* */
#include

int main(){return 0;}

Determining if files sys/strtio.h exist failed with the following output:

Source:
/* */
#include

int main(){return 0;}

Performing C SOURCE FILE Test HAVE_TM_GMTOFF failed with the following output:

Source file was:

#include

int main()
{
struct tm* tmp;
tmp->tm_gmtoff;
return 0;
}

Determining if files pthread.h exist failed with the following output:

Source:
/* */
#include

int main(){return 0;}

Performing C SOURCE FILE Test Wno-unused-but-set-variable failed with the following output:
Change Dir: /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp

Run Build Command:/usr/local/bin/cmakexbuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTryCompileExec1847124611 -configuration Debug
2015-11-19 20:15:13.385 xcodebuild[1188:39790] warning: The file reference for "CMakeLists.txt" is a member of multiple groups ("ALL_BUILD" and "cmTryCompileExec1847124611"); this indicates a malformed project. Only the membership in one of the groups will be preserved (but membership in targets will be unaffected). If you want a reference to the same file in more than one group, please add another reference to the same path.
=== BUILD TARGET cmTryCompileExec1847124611 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
/bin/mkdir -p /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64
write-file /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/cmTryCompileExec1847124611.LinkFileList

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/src.o src.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
cd /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp
export LANG=en_US.US-ASCII
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug/include -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/DerivedSources/x86_64 -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug -Wall -Wno-unused-result -DWno-unused-but-set-variable -Wno-unused-but-set-variable -MMD -MT dependencies -MF /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/src.d --serialize-diagnostics /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/src.dia -c /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/src.c -o /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/src.o
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
In file included from :326:
:2:12: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
#define Wno-unused-but-set-variable 1
^
2 warnings generated.

Ld Debug/cmTryCompileExec1847124611 normal x86_64
cd /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp
export MACOSX_DEPLOYMENT_TARGET=10.11
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug -F/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug -filelist /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/cmTryCompileExec1847124611.LinkFileList -mmacosx-version-min=10.11 -Wl,-headerpad_max_install_names -Xlinker -dependency_info -Xlinker /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/cmTryCompileExec1847124611_dependency_info.dat -o /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug/cmTryCompileExec1847124611

** BUILD SUCCEEDED **

Source file was:
int main(void) { return 0; }
Determining if files sys/eventfd.h exist failed with the following output:
Change Dir: /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp

Run Build Command:/usr/local/bin/cmakexbuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTryCompileExec663028920 -configuration Debug
2015-11-19 20:15:14.662 xcodebuild[1230:39897] warning: The file reference for "CMakeLists.txt" is a member of multiple groups ("ALL_BUILD" and "cmTryCompileExec663028920"); this indicates a malformed project. Only the membership in one of the groups will be preserved (but membership in targets will be unaffected). If you want a reference to the same file in more than one group, please add another reference to the same path.
=== BUILD TARGET cmTryCompileExec663028920 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
/bin/mkdir -p /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64
write-file /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/cmTryCompileExec663028920.LinkFileList

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.o CheckIncludeFiles.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
cd /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp
export LANG=en_US.US-ASCII
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0** BUILD FAILED **

The follow -Wno-trigraphs -fpascal-strings -O2 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug/include -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/DerivedSources/x86_64 -I/Users/yangli/Documents/src/Freing build coeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug -Wall -Wno-unused-result -Wno-deprecated-declarations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -DWINPR_EXPORTS -DFREERDP_EXPORTS -MMD -MT dependencies -MF /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.d --serialize-diagnostics /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.dia -c /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CheckIncludeFiles.c -o /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMmmands failed:
akeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.o
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk'
/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: 'sys/eventfd.h' file not found
#include 
^
1 error generated.

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.o CheckIncludeFiles.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Source:
/* */
#include

int main(){return 0;}

yangli:FreeRDP-1.1.0-beta1-ios4 yangli$
