### ISSUE TITLE
No Sound output using ALSA  in beta verison of FreeRDP-1.1.0-beta1-ios3

### ISSUE THREAD

**Issue by jiaxi2000** [FreeRDP/FreeRDP#1251]
No sound output using ALSA,But It is ok when switch pulse.
Anybody  else was experiencing this issue?

The Log:ALSA
# xfreerdp --no-nla /d:CONT /u:vdp22  /p:Hua123 /f /sound:sys:alsa  /microphone:sys:alsa   /v:192.168.1.95:3389

DBG_CHANNELS MyVirtualChannelInit (313): enter
loading channel rdpsnd
DBG_CHANNELS MyVirtualChannelInit (313): enter
loading channel drdynvc
DBG_CHANNELS freerdp_channels_pre_connect (720): enter
DBG_CHANNELS MyVirtualChannelInit (313): enter
DBG_CHANNELS freerdp_channels_pre_connect (746): registered fake rdpdr for rdpsnd.
DBG_SVC svc_plugin_init_event (261): event 0
DBG_SVC svc_plugin_init_event (261): event 0
connected to 192.168.1.95:3389
!!!!!!!!!!!!s->s3->rbuf.buf:0x44d77000
DBG_CHANNELS freerdp_channels_post_connect (776): hostname [192.168.1.95] channels->num_libs [3]
DBG_SVC svc_plugin_init_event (261): event 1
DBG_CHANNELS MyVirtualChannelOpen (400): enter
DBG_SVC svc_plugin_init_event (261): event 1
DBG_CHANNELS MyVirtualChannelOpen (400): enter
DBG_SVC svc_plugin_thread_func (186): in
DBG_DVC drdynvc_process_connect (359): connecting
Loading Dynamic Virtual Channel audin
DBG_DVC dvcman_register_plugin (159): num_plugins 0
DBG_DVC audin_register_device_plugin (442): device registered.
DBG_DVC audin_plugin_initialize (400): 
DBG_DVC dvcman_create_listener (109): 0.AUDIO_INPUT.
DBG_SVC svc_plugin_thread_func (186): in
DBG_SVC rdpsnd_process_connect (644): connecting
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 12 totalLength 12 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x5
DBG_DVC drdynvc_process_capability_request (181): Sp=3 cbChId=0
DBG_SVC svc_plugin_send (308): length 4
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 4 totalLength 4 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 12 totalLength 12 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x5
DBG_DVC drdynvc_process_capability_request (181): Sp=3 cbChId=0
DBG_SVC svc_plugin_send (308): length 4
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 4 totalLength 4 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 8 totalLength 8 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x1
DBG_DVC drdynvc_process_create_request (240): ChannelId=0 ChannelName=PNPDR
DBG_DVC drdynvc_process_create_request (256): no listener
DBG_SVC svc_plugin_send (308): length 6
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 6 totalLength 6 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 9 totalLength 9 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x1
DBG_DVC drdynvc_process_create_request (240): ChannelId=0 ChannelName=URBDRC
DBG_DVC drdynvc_process_create_request (256): no listener
DBG_SVC svc_plugin_send (308): length 6
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 6 totalLength 6 dataFlags 0

DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 700 totalLength 700 dataFlags 3
DBG_SVC rdpsnd_recv_pdu (489): msgType is 7
DBG_SVC svc_plugin_send (308): length 602
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 11 dataLength 602 totalLength 602 dataFlags 0
DBG_SVC svc_plugin_send (308): length 8
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 11 dataLength 8 totalLength 8 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1024 totalLength 1024 dataFlags 3
DBG_SVC rdpsnd_recv_pdu (489): msgType is 6
DBG_SVC svc_plugin_send (308): length 8
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 11 dataLength 8 totalLength 8 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 16 totalLength 16 dataFlags 3
DBG_SVC rdpsnd_recv_pdu (489): msgType is 2
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 1
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 820 totalLength 8820 dataFlags 2
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 16 totalLength 16 dataFlags 3
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 1
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
Warning: requested sound buffer size 17600, got 8820 instead
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 820 totalLength 8820 dataFlags 2
DBG_SVC rdpsnd_recv_wave_pdu (392): process wave data.
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 16 totalLength 16 dataFlags 3
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 1
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 820 totalLength 8820 dataFlags 2
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 16 totalLength 16 dataFlags 3
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 1
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0

Pulse, Log
# xfreerdp --no-nla /d:CONT /u:vdp22  /p:Hua123 /f /sound:sys:pulse  /microphone:sys:alsa   /v:192.168.1.95:3389

DBG_CHANNELS MyVirtualChannelInit (313): enter
loading channel rdpsnd
DBG_CHANNELS MyVirtualChannelInit (313): enter
loading channel drdynvc
DBG_CHANNELS freerdp_channels_pre_connect (720): enter
DBG_CHANNELS MyVirtualChannelInit (313): enter
DBG_CHANNELS freerdp_channels_pre_connect (746): registered fake rdpdr for rdpsnd.
DBG_SVC svc_plugin_init_event (261): event 0
DBG_SVC svc_plugin_init_event (261): event 0
connected to 192.168.1.95:3389
!!!!!!!!!!!!s->s3->rbuf.buf:0x44d77000
DBG_CHANNELS freerdp_channels_post_connect (776): hostname [192.168.1.95] channels->num_libs [3]
DBG_SVC svc_plugin_init_event (261): event 1
DBG_CHANNELS MyVirtualChannelOpen (400): enter
DBG_SVC svc_plugin_init_event (261): event 1
DBG_CHANNELS MyVirtualChannelOpen (400): enter
DBG_SVC svc_plugin_thread_func (186): in
DBG_DVC drdynvc_process_connect (359): connecting
Loading Dynamic Virtual Channel audin
DBG_DVC dvcman_register_plugin (159): num_plugins 0
DBG_DVC audin_register_device_plugin (442): device registered.
DBG_DVC audin_plugin_initialize (400): 
DBG_DVC dvcman_create_listener (109): 0.AUDIO_INPUT.
DBG_SVC svc_plugin_thread_func (186): in
DBG_SVC rdpsnd_process_connect (644): connecting
Home directory not accessible: Permission denied
DBG_SVC rdpsnd_pulse_context_state_callback (78): state 1
DBG_SVC rdpsnd_pulse_context_state_callback (78): state 2
DBG_SVC rdpsnd_pulse_context_state_callback (78): state 3
DBG_SVC rdpsnd_pulse_context_state_callback (67): PA_CONTEXT_READY
DBG_SVC rdpsnd_pulse_connect (126): connected
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 12 totalLength 12 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x5
DBG_DVC drdynvc_process_capability_request (181): Sp=1 cbChId=0
DBG_SVC svc_plugin_send (308): length 4
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 4 totalLength 4 dataFlags 0

DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 12 totalLength 12 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x5
DBG_DVC drdynvc_process_capability_request (181): Sp=2 cbChId=0
DBG_SVC svc_plugin_send (308): length 4
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 4 totalLength 4 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 8 totalLength 8 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x1
DBG_DVC drdynvc_process_create_request (240): ChannelId=0 ChannelName=PNPDR
DBG_DVC drdynvc_process_create_request (256): no listener
DBG_SVC svc_plugin_send (308): length 6
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 6 totalLength 6 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 9 totalLength 9 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x1
DBG_DVC drdynvc_process_create_request (240): ChannelId=0 ChannelName=URBDRC
DBG_DVC drdynvc_process_create_request (256): no listener
DBG_SVC svc_plugin_send (308): length 6
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 6 totalLength 6 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 700 totalLength 700 dataFlags 3
DBG_SVC rdpsnd_recv_pdu (489): msgType is 7
DBG_SVC svc_plugin_send (308): length 620
DBG_SVC svc_plugin_send (308): length 8
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 11 dataLength 620 totalLength 620 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 11 dataLength 8 totalLength 8 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1024 totalLength 1024 dataFlags 3
DBG_SVC rdpsnd_recv_pdu (489): msgType is 6
DBG_SVC svc_plugin_send (308): length 8
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 11 dataLength 8 totalLength 8 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 16 totalLength 16 dataFlags 3
DBG_SVC rdpsnd_recv_pdu (489): msgType is 2
DBG_SVC rdpsnd_pulse_stream_state_callback (177): state 1
DBG_SVC rdpsnd_pulse_stream_state_callback (166): PA_STREAM_READY
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 1
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC rdpsnd_pulse_open (334): connected
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 1600 totalLength 8820 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 820 totalLength 8820 dataFlags 2
DBG_SVC rdpsnd_recv_wave_pdu (392): process wave data.
DBG_SVC svc_plugin_open_event (153): openHandle 1 event 10 dataLength 16 totalLength 16 dataFlags 3

**Comment by cumt2010** [comment]
FreeRDP only support WAVE_FORMAT_PCM ,  correct usage:
/microphone:sys:alsa,format:1
/sound:sys:alsa

**Comment by akallabeth** [comment]
> FreeRDP only support WAVE_FORMAT_PCM , correct usage: /microphone:sys:alsa,format:1 /sound:sys:alsa

ah wrong?
just `/microphone /sound` is recommended, all other arguments are only suggested in *really specific* use cases.
