### ISSUE TITLE
Audio input error using pulse in version of FreeRDP-1.1.0-beta1-ios3

### ISSUE THREAD

**Issue by jiaxi2000** [FreeRDP/FreeRDP#1252]
Audio input error in pulse of of FreeRDP-1.1.0-beta1-ios3.  freerdp version 1.0.1 and 1.0.2 works fine using pulse.

we can get the log:Warning audin_pulse_open (418): bad stream state (5)
# xfreerdp --no-nla /d:CON /u:vdp22  /p:Hua123 /f /sound:sys:pulse  /micr

ophone:sys:pulse   /v:192.168.1.95:3389
DBG_CHANNELS MyVirtualChannelInit (313): enter
loading channel rdpsnd
DBG_CHANNELS MyVirtualChannelInit (313): enter
loading channel drdynvc
DBG_CHANNELS freerdp_channels_pre_connect (720): enter
DBG_CHANNELS MyVirtualChannelInit (313): enter
DBG_CHANNELS freerdp_channels_pre_connect (746): registered fake rdpdr for rdpsnd.
DBG_SVC svc_plugin_init_event (261): event 0
DBG_SVC svc_plugin_init_event (261): event 0
connected to 192.168.1.95:3389
!!!!!!!!!!!!s->s3->rbuf.buf:0x44d77000
DBG_CHANNELS freerdp_channels_post_connect (776): hostname [192.168.1.95] channels->num_libs [3]
DBG_SVC svc_plugin_init_event (261): event 1
DBG_CHANNELS MyVirtualChannelOpen (400): enter
DBG_SVC svc_plugin_init_event (261): event 1
DBG_CHANNELS MyVirtualChannelOpen (400): enter
DBG_SVC svc_plugin_thread_func (186): in
DBG_DVC drdynvc_process_connect (359): connecting
Loading Dynamic Virtual Channel audin
DBG_DVC dvcman_register_plugin (159): num_plugins 0
DBG_SVC svc_plugin_thread_func (186): in
DBG_SVC rdpsnd_process_connect (644): connecting
Home directory not accessible: Permission denied
DBG_SVC rdpsnd_pulse_context_state_callback (78): state 1
Home directory not accessible: Permission denied
DBG_DVC audin_pulse_context_state_callback (82): state 1
DBG_SVC rdpsnd_pulse_context_state_callback (78): state 2
DBG_DVC audin_pulse_context_state_callback (82): state 2
DBG_DVC audin_pulse_context_state_callback (82): state 3
DBG_DVC audin_pulse_context_state_callback (71): PA_CONTEXT_READY
DBG_DVC audin_pulse_connect (125): connected
DBG_DVC audin_register_device_plugin (442): device registered.
DBG_DVC audin_plugin_initialize (400): 
DBG_DVC dvcman_create_listener (109): 0.AUDIO_INPUT.
DBG_SVC rdpsnd_pulse_context_state_callback (78): state 3
DBG_SVC rdpsnd_pulse_context_state_callback (67): PA_CONTEXT_READY
DBG_SVC rdpsnd_pulse_connect (126): connected
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 12 totalLength 12 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x5
DBG_DVC drdynvc_process_capability_request (181): Sp=0 cbChId=0
DBG_SVC svc_plugin_send (308): length 4
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 4 totalLength 4 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 12 totalLength 12 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x5
DBG_DVC drdynvc_process_capability_request (181): Sp=0 cbChId=0
DBG_SVC svc_plugin_send (308): length 4
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 4 totalLength 4 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 8 totalLength 8 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x1
DBG_DVC drdynvc_process_create_request (240): ChannelId=0 ChannelName=PNPDR
DBG_DVC drdynvc_process_create_request (256): no listener
DBG_SVC svc_plugin_send (308): length 6
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 6 totalLength 6 dataFlags 0

DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 9 totalLength 9 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x1
DBG_DVC drdynvc_process_create_request (240): ChannelId=0 ChannelName=URBDRC
DBG_DVC drdynvc_process_create_request (256): no listener
DBG_SVC svc_plugin_send (308): length 6
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 6 totalLength 6 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 14 totalLength 14 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x1
DBG_DVC drdynvc_process_create_request (240): ChannelId=0 ChannelName=AUDIO_INPUT
DBG_DVC audin_on_new_channel_connection (380): 
DBG_DVC dvcman_create_channel (368): listener AUDIO_INPUT created new channel 0
DBG_DVC drdynvc_process_create_request (251): channel created
DBG_SVC svc_plugin_send (308): length 6
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 6 totalLength 6 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 7 totalLength 7 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x3
DBG_DVC drdynvc_process_data (295): ChannelId=0
DBG_DVC audin_on_data_received (325): MessageId=0x1
DBG_DVC audin_process_version (99): Version=1
DBG_DVC drdynvc_write_data (90): ChannelId=0 size=5
DBG_SVC svc_plugin_send (308): length 7
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 7 totalLength 7 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 687 totalLength 687 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x3
DBG_DVC drdynvc_process_data (295): ChannelId=0
DBG_DVC audin_on_data_received (325): MessageId=0x2
DBG_DVC audin_process_formats (132): NumFormats 22
DBG_DVC audin_process_formats (163): wFormatTag=1 nChannels=2 nSamplesPerSec=44100 nBlockAlign=4 wBitsPerSample=16 cbSize=0
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=2 nChannels=2 nSamplesPerSec=44100 nBlockAlign=2048 wBitsPerSample=4 cbSize=32
DBG_DVC audin_process_formats (163): wFormatTag=17 nChannels=2 nSamplesPerSec=44100 nBlockAlign=2048 wBitsPerSample=4 cbSize=2
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=6 nChannels=2 nSamplesPerSec=22050 nBlockAlign=2 wBitsPerSample=8 cbSize=0
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=2 nChannels=2 nSamplesPerSec=22050 nBlockAlign=1024 wBitsPerSample=4 cbSize=32
DBG_DVC audin_process_formats (163): wFormatTag=17 nChannels=2 nSamplesPerSec=22050 nBlockAlign=1024 wBitsPerSample=4 cbSize=2
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=2 nChannels=1 nSamplesPerSec=44100 nBlockAlign=1024 wBitsPerSample=4 cbSize=32
DBG_DVC audin_process_formats (163): wFormatTag=17 nChannels=1 nSamplesPerSec=44100 nBlockAlign=1024 wBitsPerSample=4 cbSize=2
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=2 nChannels=2 nSamplesPerSec=11025 nBlockAlign=512 wBitsPerSample=4 cbSize=32
DBG_DVC audin_process_formats (163): wFormatTag=17 nChannels=2 nSamplesPerSec=11025 nBlockAlign=512 wBitsPerSample=4 cbSize=2
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=2 nChannels=1 nSamplesPerSec=22050 nBlockAlign=512 wBitsPerSample=4 cbSize=32
DBG_DVC audin_process_formats (163): wFormatTag=17 nChannels=1 nSamplesPerSec=22050 nBlockAlign=512 wBitsPerSample=4 cbSize=2
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=49 nChannels=1 nSamplesPerSec=44100 nBlockAlign=65 wBitsPerSample=0 cbSize=2
DBG_DVC audin_process_formats (163): wFormatTag=2 nChannels=2 nSamplesPerSec=8000 nBlockAlign=512 wBitsPerSample=4 cbSize=32
DBG_DVC audin_process_formats (163): wFormatTag=17 nChannels=2 nSamplesPerSec=8000 nBlockAlign=512 wBitsPerSample=4 cbSize=2
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=2 nChannels=1 nSamplesPerSec=11025 nBlockAlign=256 wBitsPerSample=4 cbSize=32
DBG_DVC audin_process_formats (163): wFormatTag=17 nChannels=1 nSamplesPerSec=11025 nBlockAlign=256 wBitsPerSample=4 cbSize=2
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=49 nChannels=1 nSamplesPerSec=22050 nBlockAlign=65 wBitsPerSample=0 cbSize=2
DBG_DVC audin_process_formats (163): wFormatTag=2 nChannels=1 nSamplesPerSec=8000 nBlockAlign=256 wBitsPerSample=4 cbSize=32
DBG_DVC audin_process_formats (163): wFormatTag=17 nChannels=1 nSamplesPerSec=8000 nBlockAlign=256 wBitsPerSample=4 cbSize=2
DBG_DVC audin_process_formats (173): format ok
DBG_DVC audin_process_formats (163): wFormatTag=49 nChannels=1 nSamplesPerSec=11025 nBlockAlign=65 wBitsPerSample=0 cbSize=2
DBG_DVC audin_process_formats (163): wFormatTag=49 nChannels=1 nSamplesPerSec=8000 nBlockAlign=65 wBitsPerSample=0 cbSize=2
DBG_DVC drdynvc_write_data (90): ChannelId=0 size=1
DBG_SVC svc_plugin_send (308): length 3
DBG_DVC drdynvc_write_data (90): ChannelId=0 size=205
DBG_SVC svc_plugin_send (308): length 207
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 3 totalLength 3 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 207 totalLength 207 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 10 dataLength 51 totalLength 51 dataFlags 3
DBG_DVC drdynvc_process_receive (325): Cmd=0x3
DBG_DVC drdynvc_process_data (295): ChannelId=0
DBG_DVC audin_on_data_received (325): MessageId=0x3
DBG_DVC audin_process_open (260): FramesPerPacket=2205 initialFormat=6
DBG_DVC audin_pulse_set_format (248): aligned FramesPerPacket=3048
DBG_DVC audin_pulse_open (374): 
DBG_DVC audin_pulse_stream_state_callback (277): state 1
DBG_DVC audin_pulse_stream_state_callback (272): state 3
Warning audin_pulse_open (418): bad stream state (5)
DBG_DVC audin_pulse_close (345): 
DBG_DVC drdynvc_write_data (90): ChannelId=0 size=5
DBG_SVC svc_plugin_send (308): length 7
DBG_DVC drdynvc_write_data (90): ChannelId=0 size=5
DBG_SVC svc_plugin_send (308): length 7
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 7 totalLength 7 dataFlags 0
DBG_SVC svc_plugin_open_event (153): openHandle 2 event 11 dataLength 7 totalLength 7 dataFlags 0

**Comment by akallabeth** [comment]
Closing, reopen if still an issue.

**Comment by jphein** [comment]
I'm having this exact issue. When trying to record audio xfreerdp throws the error: 
Warning audin_pulse_open (430): bad stream state (5)
I am using Ubuntu Bionic and the freerdp-x11 package from the official repos. The remote machine is a Windows2012r2 KVM virtual machine.  
`
xfreerdp --version
This is FreeRDP version 1.1.0-beta1 (git n/a)  
`
```
xfreerdp /v:192.168.2.103/sound:sys:pulse /mic:sys:pulse /log-level:debug
```
```
loading channel rdpdr
loading channel rdpsnd
loading channel drdynvc
connected to 192.168.2.103:3389
Loading Dynamic Virtual Channel audin
Warning audin_pulse_open (430): bad stream state (5)
ERRINFO_LOGOFF_BY_USER (0x0000000C):
The disconnection was initiated by the user logging off his or her session on the server.
Failed to check FreeRDP file descriptor
```
When I add your nightly repos, and try freerdp2-x11. It works, but the audio coming from the microphone is incredibly choppy.

**Comment by akallabeth** [comment]
@jphein I'd check with a more recent version ;)
