### ISSUE TITLE
Graphical drawing issues

### ISSUE THREAD

**Issue by serial326** [FreeRDP/FreeRDP#1273]
Hi,
We are having this problem when opening windows in Acomba. The drawing issue dissapear for the current windows is we move it but will reappear on new windows windows.
Got this problem on mac and linux. We was not having this problem on non-master branches.

We have tried the -offset-cache, -bitmap-cache, -glyph-cache, /gdi:sw, /gdi:hw, /rfx but none of them make the problem dissapear.

Here is the command line : ./xfreerdp /size:1366x768 /kbd:0x00011009 /v:SERVER2008 /shell-dir:"C:\Partage\Apps\FORTUNE" /shell:"C:\Partage\Apps\FORTUNE\Acomba.exe" /d:$domain /u:$user /cert-ignore;

![screenshot from 2013-05-31 15 26 42](https://f.cloud.github.com/assets/4580981/591671/a9df5daa-ca06-11e2-8bf4-d359a35b9429.png)
![screenshot from 2013-05-31 15 27 19](https://f.cloud.github.com/assets/4580981/591672/afb7206e-ca06-11e2-84ff-dd99392a30ac.png)

**Comment by akallabeth** [comment]
Master drawing code has been (mostly) rewritten.
Closing, reopen if still an issue.
