### ISSUE TITLE
Build with WITH_XINERAMA=OFF has no window in fullscreen or workarea 

### ISSUE THREAD

**Issue by maddeer** [FreeRDP/FreeRDP#1285]
$ cmake -DWITH_PCSC=ON  -DWITH_XINERAMA=OFF -DCHANNEL_URBDRC_CLIENT=ON .
-- FreeRDP GIT
-- Git Revision 1.1.0-beta1+android5-85-g0475
-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Skipping optional feature Pulse for sound (audio input, audio output and multimedia redirection)
--     Enable feature Pulse using "-DWITH_PULSE=ON"
-- Skipping optional feature Cups for printing (printer device redirection)
--     Enable feature Cups using "-DWITH_CUPS=ON"
-- Finding optional feature PCSC for smart card (smart card device redirection)
-- Finding recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Disable feature FFmpeg using "-DWITH_FFMPEG=OFF"
-- Skipping recommended feature Gstreamer for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- Skipping optional feature NPP for performance (NVIDIA Performance Primitives library)
--     Enable feature NPP using "-DWITH_NPP=ON"
-- FreeRDP GIT
-- Finding recommended feature XKBFile for X11 keyboard (X11 keyboard file extension)
--     Disable feature XKBFile using "-DWITH_XKBFILE=OFF"
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Adding static channel client "rdpdr": Device Redirection Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding dynamic channel client "urbdrc": USB Devices Virtual Channel Extension
-- Adding static channel client "cliprdr": Clipboard Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding static channel client "drdynvc": Dynamic Virtual Channel Extension
-- Adding dynamic channel client "echo": Echo Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Found XMLTO: /usr/bin/xmlto
-- Finding required feature XShm for X11 shared memory (X11 shared memory extension)
-- Skipping recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Finding recommended feature Xcursor for cursor (X11 cursor extension)
--     Disable feature Xcursor using "-DWITH_XCURSOR=OFF"
-- Finding recommended feature Xv for video (X11 video extension)
--     Disable feature Xv using "-DWITH_XV=OFF"
-- Finding recommended feature Xi for input (X11 input extension)
--     Disable feature Xi using "-DWITH_XI=OFF"
-- Finding recommended feature Xrender for rendering (X11 render extension)
--     Disable feature Xrender using "-DWITH_XRENDER=OFF"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/maddeer/FreeRDP.mar/FreeRDP
.......

$xfreerdp  /v:hostname -sec-nla -sec-tls /smartcard:scard /f
loading channel rdpdr
loading channel rdpsnd
connected to hostname:3389
Unable to get current timezone rule
Loading device service smartcard (static)
registered device #1: SCARD (type=32 id=1)

I don`t see any window

**Comment by akallabeth** [comment]
closing for being ancient.
Create a new one if still an issue.
