### ISSUE TITLE
Issues connecting to an MS RDP TS Farm (behind a broker)

### ISSUE THREAD

**Issue by asafge** [FreeRDP/FreeRDP#1309]
Hi.
- I've tested the latest version and it looks like I'm unable to connect using xfreerdp to a TS farm. Looks like the TS broker (some sort of load balancer) is sending out an RDS Redirection PDU packet, but on the linux machine I get a segfault and a crash from the xfreerdp process.
- Also, I've tested v1.0.1 and it looks like it works, so this is something that was working before. Anyway I'd be happy to help out with this one.

Edit:
- Command was: xfreerdp /cert-ignore /u:user /p:pass /v:farmname

Thanks.

**Comment by biapar** [comment]
Any news?

**Comment by caramorsimon** [comment]
@biapar - I am just embarking on fixing licensing issues preventing full use of my load balanced farms. 
Which platform were you interesting in getting resolved? AFAIK, win2008r2 will be ok based on the May 2014 master + PR #1841 
I am just about to pick up the codebase again to see whether I can get USB smartcard passthrough  working this time [previously it was unusable with my combo of pcsc-lite, old debian linux, win2x svr] but that area had been rewritten & I don't think had seen a lot of real world use.

**Comment by biapar** [comment]
Hi,

I'm using win2003 RDP Farm with session directory.
I tried with rdesktop package and works.

**Comment by chrisdavis925** [comment]
@caramorsimon if you are looking for feedback, I can report that connecting to a farm from a broker in 2012R2 is still having problems. I can get the connection to work, but it disconnects after sometime. Usually the session will work for a few minutes before the disconnect. 

Error is: Failed to check FreeRDP file descriptor"

**Comment by scroogie** [comment]
Same problem here (file descriptor). Any news about that?

**Comment by slonkak** [comment]
Any news on this?  I'm connecting to a TS through RD Gateway (though both are on the same server).  SSL on 443.  I get disconnected after being inactive in the window for seemingly random periods of time.  None of the above suggestions help.  Here is the command I'm using to connect.
`xfreerdp +toggle-fullscreen /gt:rpc /w:1280 /h:1024 /u:username /p:password /cert-ignore /g:server.company.com:443 /v:server.company.local`
