### ISSUE TITLE
aFreeRDP, last version, cyrillic logins not authenticate

### ISSUE THREAD

**Issue by Pionegr** [FreeRDP/FreeRDP#1311]
I use last version aFreeRDP from Google Play and try to connect to PC(windows 7 or Windosw 2008 R2) with login "Администратор" (in russian), but "Failed to establish a connection to the server". If I try to connect with login "admin" - all works. In first situation windows events is empty. Previos version of aFreeRDP works perfectly. This bug came after last update. 
Thanks! And sorry for my english

**Comment by akallabeth** [comment]
Is this issue still relevant with current master?
