### ISSUE TITLE
XfreeRDP Segfault with multimedia redirection

### ISSUE THREAD

**Issue by bs819** [FreeRDP/FreeRDP#1319]
Attempting to use multimedia redirection with a Windows 2008 R2 Session Host server, however whenever the video is about to play xfreerdp crashes with a segfault. The videos play fine on Windows 7 fat clients as well as newer Wyse terminals supporting redirection.

Are there certain libraries or packages that need to be installed for multimedia redirection to work propertly with xfreedp?

Using Ubuntu 12.04 and latest Xfreerdp from Ubuntu Precise PPA (1360+32) as of today.

My command line is as follows
xfreerdp /v:tsfarm.lan.local /bpp:16 /d:domain.com /f +compression -sec-nla -encryption -wallpaper -window-drag -menu-anims -themes -decorations -sec-tls /multimedia /gdi:hw /cert-ignore

The issue also persists if I only use:
xfreerdp /v:tsfarm.lan.local /multimedia

**Comment by akallabeth** [comment]
Closing due to being inactive for a long time and redirection having received many fixes in the meantime. Repoen if still relevant.
