### ISSUE TITLE
Could not create device driver context!

### ISSUE THREAD

**Issue by srhahaar** [FreeRDP/FreeRDP#1324]
When I run wfreerdp-server.exe,  I am facing this issue

Detecting screens...

ID      Resolution              Name (Interface)

0       1360x768x32     \.\DISPLAY1 (Intel(R) Graphics Media Accelerator HD)
Starting server
Listening on :: port 3389.
Listening on 0.0.0.0 port 3389.
Activating Mirror Driver
Could not create device driver context!
CreateDC failed on device [\.\DISPLAYV4] with error 0: The operation completed
successfully.

Unable to map memory for mirror driver!

I am running the freerdp server on Windows 7 64 bit system.  Please help me in fixing this issue

**Comment by Abhineet-Ayan-Verma** [comment]
Any solution for this issue? I am facing the same. Details:
--> Server
- OS : Windows 7 Pro x86
- Mirage Driver (2.0.301) Installed
- Run wfreerdp-server.exe

--> Client
- OS : Windows 7 Pro x64
- mstsc to server with custom server port on which FreeRDP is listening

Error - Could not create device driver context!
