### ISSUE TITLE
disconnection when the remote control and farm

### ISSUE THREAD

**Issue by noobpower** [FreeRDP/FreeRDP#1332]
hello, i'm french ( sorry for the problems of expressions).

about:

freerdp 1.1.0 = I have a connection problem when I connect to the farm but the remote control from the servers running tse is ok .

freerdp 1.0.1 = the connection to the farm is ok, but the remote control from the server tse  is no ok

someone he found a solution to a problem ?

Thank you in advance

**Comment by akallabeth** [comment]
Closing due to being stall.
Reopen if still an issue.
