### ISSUE TITLE
Tool bar obtrusive in iOS client

### ISSUE THREAD

**Issue by sabas** [FreeRDP/FreeRDP#1338]
On iPad, the client offers to hide the toolbar, but there's no way to open the keyboard.
But if the toolbar is enabled, it overlays the top part of the screen (making impossible to click for closing a window which top part is under the toolbar).
It's possible to offer an alternative menu when toolbar is hidden (via gesture?) or make the toolbar appear above the window?

**Comment by glitchphan** [comment]
+1. Would be cool if it was a hideable tiny toolbar in the center.
