### ISSUE TITLE
aFreeRDP does not support setting the client hostname

### ISSUE THREAD

**Issue by benmann90** [FreeRDP/FreeRDP#1343]
A major problem with Android is that it is so difficult for a sys admin (in an enterprise environment) to change the hostname of the client device.

It would be nice to have a way to manually set the client hostname that is reported to the server in aFreeRDP.

**Comment by Kidsdoc** [comment]
has this problem been solved ? I 'm looking for a way to manually set the client hostname. If there ist a way, I would be lucky to get to know.....

**Comment by bmiklautz** [comment]
This feature is already implemented on master since quite a while with a minor issue (" is prepended).

**Comment by bmiklautz** [comment]
Related PR #4092
