### ISSUE TITLE
Thin line drawing issue (1.1.0~beta1+git20130629-1 and others)

### ISSUE THREAD

**Issue by ChrisH79** [FreeRDP/FreeRDP#1347]
Hi

Having problems with line drawing when windows apps first load to the screen, both are winform apps if this helps.  They are also quite a few years old. Newer applications seem fine, office 2007 excel seems fine.

The lines (I think) are 1 pixel height by n length.

The slightest movement of the window renders the screen correctly.

Some lines draw broken, some blank, some broken with different colours.

Setup 

Windows 2008R2 servers - no additional special software like RemoteFX etc.
Ubuntu 10.04 running 1.1.0~beta1+git20130629-1 and others from Debain experimental, with all associated libraries (hopefully) installed - I did an apt-get not manual install.

Thanks

Chris

**Comment by ipitcher** [comment]
This issue is still present in the master branch. I have reproduced it by building a simple Windows Form Application targeted at .NET Framework 3.5 with a DataGridView control on a form. All attempts to screencap the rendering errors produce normal images.

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
