### ISSUE TITLE
New command line argument - "/console" - to open a debug console in windows

### ISSUE THREAD

**Issue by macarthor** [FreeRDP/FreeRDP#1348]
hi all,
This new argument, "/console", will open a debug console for Windows release version, just like Windows debug version, but it's a runtime switch, so it's more convenient in practice.
It seems that I should commit a pull request, but I really don't know how to do it... So, please review this patch here...
# Index: client/common/cmdline.c

--- client/common/cmdline.c (revision 4699)
+++ client/common/cmdline.c (working copy)
@@ -136,6 +136,7 @@
    { "help", COMMAND_LINE_VALUE_FLAG | COMMAND_LINE_PRINT_HELP, NULL, NULL, NULL, -1, "?", "print help" },
    { "play-rfx", COMMAND_LINE_VALUE_REQUIRED, "<pcap file>", NULL, NULL, -1, NULL, "Replay rfx pcap file" },
    { "auth-only", COMMAND_LINE_VALUE_BOOL, NULL, BoolValueFalse, NULL, -1, NULL, "Authenticate only." },
-   { "console", COMMAND_LINE_VALUE_BOOL, NULL, BoolValueFalse, NULL, -1, NULL, "Open debug console (Windows only)" },
  { NULL, 0, NULL, NULL, NULL, -1, NULL, NULL }
  };

@@ -1604,6 +1605,12 @@
        {
            settings->AuthenticationOnly = arg->Value ? TRUE : FALSE;
        }
-       CommandLineSwitchCase(arg, "console")
-       {
  +#ifdef _WIN32
-           status = OPEN_CONSOLE_WINDOWS_ONLY;
  +#endif
-       }
      CommandLineSwitchDefault(arg)
      {
# Index: client/Windows/cli/wfreerdp.c

--- client/Windows/cli/wfreerdp.c   (revision 4699)
+++ client/Windows/cli/wfreerdp.c   (working copy)
@@ -52,6 +52,7 @@
    rdpContext\* context;
    rdpSettings\* settings;
    RDP_CLIENT_ENTRY_POINTS clientEntryPoints;
-   BOOL open_console = FALSE;
  
  ZeroMemory(&clientEntryPoints, sizeof(RDP_CLIENT_ENTRY_POINTS));
  clientEntryPoints.Size = sizeof(RDP_CLIENT_ENTRY_POINTS);
  @@ -71,6 +72,15 @@
      context->argv[index] = _strdup(__argv[index]);
  
  status = freerdp_client_parse_command_line(context, context->argc, context->argv);
-   open_console = (OPEN_CONSOLE_WINDOWS_ONLY == status);
  +#if defined(WITH_DEBUG) || defined(_DEBUG)
-       wf_create_console();
  +#else
-   if (TRUE == open_console)
-   {
-       wf_create_console();
-   }
  +#endif
  
  status = freerdp_client_command_line_status_print(context->argc, context->argv, settings, status);

@@ -92,5 +102,14 @@

```
freerdp_client_context_free(context);
```

+#if defined(WITH_DEBUG) || defined(_DEBUG) 
-   system("pause");
  +#else
-   if (TRUE == open_console)
-   {
-       system("pause");
-   }
  +#endif
  +
  return 0;
  }
  # Index: client/Windows/wf_interface.c
  
  --- client/Windows/wf_interface.c   (revision 4699)
  +++ client/Windows/wf_interface.c   (working copy)
  @@ -988,9 +988,9 @@
  
  WSAStartup(0x101, &wsaData);

-#if defined(WITH_DEBUG) || defined(_DEBUG)
-   wf_create_console();
  -#endif
  +//#if defined(WITH_DEBUG) || defined(_DEBUG)
  +// wf_create_console();
  +//#endif
  
  freerdp_channels_global_init();
# Index: client/Windows/wf_interface.h

--- client/Windows/wf_interface.h   (revision 4699)
+++ client/Windows/wf_interface.h   (working copy)
@@ -139,6 +139,8 @@

 FREERDP_API int RdpClientEntry(RDP_CLIENT_ENTRY_POINTS\* pEntryPoints);

+FREERDP_API int wf_create_console(void);
+
 #ifdef __cplusplus
 }
 #endif
# Index: include/freerdp/client/cmdline.h

--- include/freerdp/client/cmdline.h    (revision 4699)
+++ include/freerdp/client/cmdline.h    (working copy)
@@ -41,6 +41,8 @@
 FREERDP_API int freerdp_client_add_static_channel(rdpSettings\* settings, int count, char*\* params);
 FREERDP_API int freerdp_client_add_dynamic_channel(rdpSettings\* settings, int count, char*\* params);

+#define OPEN_CONSOLE_WINDOWS_ONLY 8866
+
 #ifdef __cplusplus
 }
 #endif

**Comment by akallabeth** [comment]
No pull done, closing.
