### ISSUE TITLE
Could not open SAM file!

### ISSUE THREAD

**Issue by mrkwjc** [FreeRDP/FreeRDP#1350]
Hi!
I'm trying to establish rdp connection with the command:

xfreerdp start.rdp /p:*****************

but the segfault occurs:

Using connection file: start.rdp
autoreconnection enabled:i:1
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
server port:i:3389
compression:i:1
keyboardhook:i:2
authentication level:i:0
promptcredentialonce:i:1
gatewayusagemethod:i:1
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
remoteapplicationmode:i:1
remoteapplicationname:s:ANSYS 14.5 EN (AP)
remoteapplicationprogram:s:||cce7103e-ec77-11e2-8c02-00155d020101
full address:s:bl-pl-03-ap.platon.local
gatewayhostname:s:pl-rds.p.lodz.pl
username:s:platon\pl-mwojc
connection type:i:5
displayconnectionbar:i:1
screen mode id:i:2
use multimon:i:1
redirectclipboard:i:1
redirectposdevices:i:0
redirectprinters:i:0
redirectcomports:i:0
redirectsmartcards:i:0
session bpp:i:32
allow font smoothing:i:1
allow desktop composition:i:1
disable wallpaper:i:0
disable full window drag:i:0
disable menu anims:i:0
disable themes:i:0
bitmapcachepersistenable:i:1
disable cursor setting:i:0
redirectdirectx:i:1
audiomode:i:0
audiocapturemode:i:0
videoplaybackmode:i:1
loading channel rail
connected to pl-rds.p.lodz.pl:443
connected to pl-rds.p.lodz.pl:443
Could not open SAM file!
Could not open SAM file!
Could not open SAM file!
Could not open SAM file!
rts_connect error! Status Code: 401
HTTP/1.1 401 Unauthorized
Content-Type: text/plain
Server: Microsoft-IIS/7.5
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
WWW-Authenticate: Basic realm="pl-rds.p.lodz.pl"
X-Powered-By: ASP.NET
Date: Sun, 14 Jul 2013 13:10:37 GMT
Content-Length: 13

rts_connect error!
rpc_connect failed!
Error: protocol security negotiation or connection failure
Segmentation fault

Any ideas what is happening?

BTW: I'm using freerdp-1.1.0_beta1_p20130605 (on Gentoo)

**Comment by akallabeth** [comment]
Closing, reopen if still an issue.
