### ISSUE TITLE
RemoteApp doesn't allow mouse interaction with windows, parts of windows are blacked out

### ISSUE THREAD

**Issue by maikthulhu** [FreeRDP/FreeRDP#1355]
I built FreeRDP from source today on Fedora 19 after not having luck with RemoteApp in FreeRDP in the Fedora repos.  I was able to establish a connection but I cannot interact with the application using the mouse.  It appears to raise focus when the application is clicked on, and I can use the keyboard to navigate around and type in the applications and windows, but I cannot resize or select window elements with the mouse.

Drawing also seems to be an issue as per the following screenshot.  This is HEAD 18a3f37d06cdc8e8a837e07f07a72566ca66419d.

![screenshot from 2013-07-16 15 00 44](https://f.cloud.github.com/assets/680830/808407/355adfe6-ee63-11e2-9ada-501fcb519c0e.png)

**Comment by akallabeth** [comment]
Works on target release.
