### ISSUE TITLE
Feature Request: GUI Prompt for Password

### ISSUE THREAD

**Issue by jar349** [FreeRDP/FreeRDP#1358]
Love xfreerdp!  I've created a script for each of the machines that I often RDP into, so I now have quick access to them!

I'd like to be able to launch these scripts in the command box I get when I press ALT+F2 in linux.  Now, if I set my script to be "xfreerdp <options> $@", then I can call my script and add /p:<password> as an argument and it works great.

The problem is that anyone sitting next to me will see my password.  I'd love for xfreerdp to popup a GUI prompt for my password so that it's not visible as I type it.  Is that already possible somehow?  If so, I'm sorry for this issue - but I couldn't find it.

If it's not already possible, would you please consider it as a feature request?

**Comment by mjevans** [comment]
What I would really prefer is the ability to specify credentials from files.  This way using a secure folder ( E.G. $XDG_RUNTIME_DIR as specified in http://www.freedesktop.org/software/systemd/man/pam_systemd.html ) it is possible to provide credential information in a way which is not accessible by other user's processes.

**Comment by hashstat** [comment]
I agree with @mjevans. Reading from a file could be made more secure than from the command-line or environment variables. One could even use a fifo (named pipe) or bash magic (process substitution) to call a generic GUI prompter for the password and pass it to freerdp via the file. The simplest approach would be to read a single line from the file and use it for authentication. What would be even better is to find some way to signal an unsuccessful attempt and then read another line. Another file might be required for that.

**Comment by j-rueger** [comment]
Any news on this?

As a workaround, I wrote the following script. Been using it for some time, a bit hacky but works like a charm. (You need ![yad](http://sourceforge.net/projects/yad-dialog/), a fork of Zenity that provides much more functionality, and xdotool for this)

Hope someone finds it useful! Cheers!

```shell
#!/bin/bash

AUDIO=
DOWNS=
USB=
USER=
DOMAIN="MyDomain"
SERVER="10.20.30.40"
GEOMETRY="/f"


while [ -n "$1" ]
do
	case "$1" in
		--USB)
			USB="/drive:USB,/media/user"
			;;
		--downloads)
			DOWNS="/drive:Downloads,$HOME/Downloads"
			;;
		--audio)
			AUDIO="/sound"
			;;
		-g)
			shift
			[[ ! $1 =~ ^[0-9]{3,4}x[0-9]{3,4}$ ]] && echo "Invalid resolution, defaulting to fullscreen." && continue
			GEOMETRY=$(echo $1 | awk -Fx '{ printf("/w:"$1" /h:"$2); }')
			;;
		*)
			[ "${1:0:1}" != "-" ] && USER=$1
	esac
	shift
done


while true
do

[ -n "$USER" ] && until xdotool search "Terminal server login" windowactivate key Right Tab 2>/dev/null ; do sleep 0.05; done &

FORM=$(yad --center --width=380 \
	--window-icon="gtk-execute" --image="gcr-password"\
	--title "Terminal server login" \
	--form --field="User name" "$USER"\
	--field="Password":H)

[ $? != 0 ] && exit

USER=$(echo $FORM | awk -F '|' '{ print $1 }')
PASS=$(echo $FORM | awk -F '|' '{ print $2 }')

RES=$(xfreerdp /v:"$SERVER" /cert-ignore /sec-tls $GEOMETRY /d:"$DOMAIN" /u:"$USER" /p:"$PASS" +compression +clipboard -menu-anims +fonts $USB $DOWNS $AUDIO 2>&1)

echo $RES | grep -q "Authentication failure" && yad --center --image="error" --window-icon="error" --title "Authentication failure" --text="Please make sure you typed\nyour password correctly." --text-align=center --width=320 --button=gtk-ok --buttons-layout=spread && continue

echo $RES | grep -q "connection failure" && yad --center --image="error" --window-icon="error" --title "Connection failure" --text="Could not connect to the server.\n\nPlease check your network connection." --text-align=center --width=320 --button=gtk-ok --buttons-layout=spread

break
done
```

**Comment by ondrejholy** [comment]
I don't think there are any news about this (at least not from my side), however you might also use some external tools (e.g. Remmina, Vinagre) to manage your connections...

**Comment by Link-Satonaka** [comment]
Try using [dmenu](http://tools.suckless.org/dmenu/):
```bash
#!/bin/sh
# Use echo to populate dmenu's selection list
machine=$(echo -e "preset1\npreset2\npreset3" | dmenu -l 5 -p "Choose a host")
user=$(echo -e "Link\nBob\nMark" | dmenu -l 5 -p "Username:")
# Set background and foreground colors the same to mask password input
pass=$(echo "..." | dmenu -p "Password:" -nb "#222222" -nf "#222222")

# Define presets
case $machine in
	"preset1")
		xfreerdp /v:192.168.1.101 /u:$user /p:$pass /workarea /rfx +home-drive ;;
	"preset2")
		xfreerdp /v:127.0.0.1     /u:$user /p:$pass /workarea -compression +clipboard ;;
	"preset3")
		xfreerdp /v:example.com   /u:$user /p:$pass /workarea ;;
esac
```

**Comment by rkeene** [comment]
This doesn't really help since if yo use "from-stdin" you are not able to accept the certificate of the remote host.

```
The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the documentation on how to create local certificate store for a private CA.
Do you trust the above certificate? (Y/N) 
Error: Could not read answer from stdin. - Run without parameter "--from-stdin" to set trust.
```

**Comment by wyllianbs** [comment]
# [xfreerdp-gui](https://github.com/wyllianbs/xfreerdp-gui)

**Adapted from:** https://github.com/FreeRDP/FreeRDP/issues/1358#issuecomment-175075061

**URL:** [](https://github.com/wyllianbs/xfreerdp-gui)

**Comment by Jackfritt** [comment]
Try this. 
`xfreerdp /v:example.com /d:DOMAIN /u:User +clipboard -themes -wallpaper /drives /cert-ignore /w:2560 /h:1350 /p:$(kdialog --password "Please enter RDP Password")
`
You can add this to an KDE Desktop file like:
[Desktop Entry]
Categories=
Comment[de_DE]=Connect to Client
Comment=Connect to Client
Exec=xfreerdp /v:example.com /d:DOMAIN /u:User +clipboard -themes -wallpaper /drives /cert-ignore /w:2560 /h:1350 /p:$(kdialog --password "Please enter RDP Password")

**Comment by Jogai** [comment]
@Jackfritt Yes, for lxqt I used qarma succesfully

**Comment by vermgit** [comment]
I don't know if it helps in all situations (and I hope it's on-topic :) ), but I also didn't like the password in the command line. However, [I learned](https://unix.stackexchange.com/a/187370/153505) that I can use `/sec:tls` instead of the `/p`-switch, which at least helps when connecting to Windows machines. What it does is it shows the typical Windows login form where you enter the password as you'd be when sitting in front of the machine. You can still preset the username with `/u`.

Maybe a different approach to the matter...

**Comment by victorhooi** [comment]
Would be nice if there was a lightweight wrapper included with FreeRDP, or perhaps a pointer to a recommended one.

Thanks @vermgit for the tip about `/sec:tls` - that works well, and takes you straight to a normal Windows login screen.

You can even omit both the /u and /p prompts - it pre-fills the username field with the currently logged in Linux user, but you can still fill in both the username and password fields.

**Comment by Palmitoxico** [comment]
Unfortunately `/sec:tls` doesn't work in my case:

```
[10:12:02:807] [216188:216189] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[10:12:02:807] [216188:216189] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[10:12:02:807] [216188:216189] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[10:12:02:807] [216188:216189] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[10:12:02:807] [216188:216189] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[10:12:02:807] [216188:216189] [INFO][com.freerdp.client.x11] - Property 374 does not exist
[10:12:02:116] [216188:216189] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[10:12:02:120] [216188:216189] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[10:12:02:120] [216188:216189] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[10:12:03:198] [216188:216189] [WARN][com.freerdp.core.nego] - Error: HYBRID_REQUIRED_BY_SERVER
[10:12:03:198] [216188:216189] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[10:12:03:198] [216188:216189] [ERROR][com.freerdp.core] - rdp_client_connect:freerdp_set_last_error_ex ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[10:12:03:198] [216188:216189] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
```

rdesktop would show a Windows login screen, so I could type the password there. Unfortunately it doesn't support NTLM.

An easy way to add this functionality would be having an argument to specify an external program to get the password (ex: [zenity](https://gitlab.gnome.org/GNOME/zenity)). No xlib tinkering necessary.

Life would be easier if Windows supported authentication using PGP or ssh keys.

**Comment by DanielGibson** [comment]
I agree with the original poster that an option to show a simple dialog would be very useful, so I neither have to run it in a terminal (to interactively enter the password) nor have the password shown in `ps aux` (as I would when hacking a script with zenity or whatever that passes the entered password via `/p:MyP4SSW0RD`).
IMO being able enter just the password would suffice (I don't mind hardcoding the username in a script or shortcut), but probably allowing entering the username as well would be nice.

**Comment by DanielGibson** [comment]
Does FreeRDP have a GUI to enter passwords now?
Is it already released?
How do we use it? Is there a new commandline argument for it or does it open automatically?

**Comment by akallabeth** [comment]
@DanielGibson yes, the SDL client got one. will not be ported to `xfreerdp` or other clients though. (of course, contributions welcome ;))
