### ISSUE TITLE
xfreerdp/wfreerdp crash in random conditions

### ISSUE THREAD

**Issue by macarthor** [FreeRDP/FreeRDP#1360]
I build xfreerdp/wfreerdp (many GIT versions, from 2012-9 till now, I git clone every 1-2 weeks) in ubuntu 12.04.2 LTS and windows 7 sp1 with visual studio 2010 pro. Both versions encounter crash in random conditions. But the debug output is similar: SSL read/write error. I think the problem may be the interaction with OpenSSL.

Build environment as following:
ubuntu 12.04.2 LTS x86 desktop
su -
apt-get purge libfreerdp1 (remove all system built-in freerdp libs)
apt-get install cmake build-essential libssl-dev libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxdamage-dev libxv-dev libxkbfile-dev libasound2-dev libcups2-dev libxml2 libxml2-dev libxrandr-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libavutil-dev libavcodec-dev
cmake .
make
make install
xfreerdp /u:xxx /p:xxx /v:xxx (use simplest arguments)
RDP host is windows 7 sp1 or windows 2008 r2, and xfreerdp crashes occassionally, and the debug message is:
SSL read/write error.

BTW, freerdp officially released by ubuntu (1.0.1) works fine and never has crash.

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
