### ISSUE TITLE
x11 fullscreen mode  seems to be broken in 12ec6c6

### ISSUE THREAD

**Issue by arcadoss** [FreeRDP/FreeRDP#1361]
➜  FreeRDP git:(12ec6c6) git bisect bad 12ec6c60db789ddd52b6b758a53ece236c671103 
12ec6c60db789ddd52b6b758a53ece236c671103 is the first bad commit
commit 12ec6c60db789ddd52b6b758a53ece236c671103
Author: Marc-André Moreau marcandre.moreau@gmail.com
Date:   Sun Apr 28 18:48:27 2013 -0400

```
xfreerdp: add support for selecting individual monitors
```

:040000 040000 df5f378eb4ec98094759651efcc62cf774509980 925af87143a3abf917bc939785168c9e277b19ec M  client
:040000 040000 9a0c655efc427387b2e46535b401c6044fc9ae61 b03323c7537347fb74cb1b6cd46f37b3ba359658 M  include

**Comment by akallabeth** [comment]
Working on target release.
