### ISSUE TITLE
Connecting Windows server 2012 via RDP-Gateway fails with memory error message

### ISSUE THREAD

**Issue by A-nd-y** [FreeRDP/FreeRDP#1362]
I've tried it with the version from 2013-07-18.
When i try to connect my server via rdp gateway the following error message is shown: 

Commandline: 
xfreerdp /v:server.domain /u:domain-user /d:domain /p:mysecret /g:server.domain

connected to server.domain:443
connected to server.domain:443
Speicherzugriffsfehler

---

Existing Windows 7 Clients are reachable over the gateway,
only Windows Server 2012 are unreachable.

When i open a vpn-tunnel to my company network all connections are fine,
only when i use the rdp-gateway the windows server 2012 connections fails.

**Comment by akallabeth** [comment]
Closing as no longer reproducible.
