### ISSUE TITLE
mouse positioning in RAIL applications broken since ba41825

### ISSUE THREAD

**Issue by arcadoss** [FreeRDP/FreeRDP#1363]
If you try to draw a line in mspaint it appears elsewhere.

The last checked good commit is 2b3241258dba6463b0dc4c0b32aac602ebbd247b
The first bad commit is ba4182566cf4ac60ceac0ae3c6c33172d9565fc7

**Comment by akallabeth** [comment]
Working on target release, reopen if still an issue.
