### ISSUE TITLE
Color problem

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#1368]
Reported from Nick:

In some windows I have strange colors of scrolls. Look lease at the
attached screenshots. (green is good, red is the bad one).
I have the same problem on a few other RDP clients. But another RDP clients
don't have such problem.

![good](https://f.cloud.github.com/assets/195793/848453/97dfa4d2-f460-11e2-9ee1-380791461b34.png)
![problem](https://f.cloud.github.com/assets/195793/848454/97f729ae-f460-11e2-84e6-7b7e240505cb.png)

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
