### ISSUE TITLE
RemoteApp not working in Windows 7

### ISSUE THREAD

**Issue by jpippy** [FreeRDP/FreeRDP#1417]
I am trying to get RemoteApp working. I am using the wfreerdp server on the remote pc and the wfreerdp client on the local pc. Both the remote pc and local pc are using Windows 7.  I can't seem to figure out why it is not working.

Here is the arguments I am using:

wfreerdp.exe -u myuser -p mypass --rfx --app "||C:\Windows\system32\notepad.exe" -o 192.168.1.100

**Comment by akallabeth** [comment]
Working on target release.
