### ISSUE TITLE
RemoteApp not working with XP-Mode

### ISSUE THREAD

**Issue by Falcon-1** [FreeRDP/FreeRDP#142]
When running xfreerdp from git to a XP-Mode running in Virtual box on Ubuntu Natty I only get the following message but no windows with the app:

loading plugin channels/rail/rail.so
connected to 192.168.56.101:3389
incorrect offset, type:0x14 actual:12 expected:8
incorrect offset, type:0x0E actual:8 expected:4
incorrect offset, type:0x14 actual:12 expected:8
incorrect offset, type:0x0E actual:8 expected:4

Running a full session gives me the same messages but does show a desktop. 

Please advice.

**Comment by hardening** [comment]
Just pinging this bug, has something changes on that side ? 
It's not clear if you can connect with RAILs with mstsc on a WinXP host ? If not I'd tend to close the issue...

**Comment by TGruenberg** [comment]
Hi everybody,

does everyone have the KB961742-v3.exe in the german version? It is no longer available on the microsoft homepage.

Thank you very much.

**Comment by tristan-k** [comment]
I can confirm the issue. Unable to connect to Win XP SP3 with Debian and `This is FreeRDP version 2.0.0-dev (git n/a)`.

```
$ /opt/freerdp-nightly/bin/xfreerdp /u:Username /p:Password /v:192.168.0.201 /app:"||Notepad"[01:02:06:281] [21095:21096] [INFO][com.freerdp.client.common.cmdline] - loading channel rail
```

And then nothing happens.
