### ISSUE TITLE
Linux smartcard redirection not working correctly

### ISSUE THREAD

**Issue by caramorsimon** [FreeRDP/FreeRDP#1424]
I would like some pointers on how to investigate to find further details, as rdesktop scard passthrough works fine for all these cards/servers.
xfreerdp commit c998f0b173d06  master, Fri Aug 9 15:53
[subsequent commits on head from this week are failing with compile errors for me]

The platform is a debian, pcsc-lite 1.8.8.3

I am using rdesktop 1.7.1 as a reference since the smartcard passthrough seems to work very reliably, although it is missing a number of important features (farm/UAG support, TLS etc that make it unsuitable in the target environment). It does however provide a reasonable test of whether the client & server config is basically sound, although I appreciate the age of the build could possibly be masking issues present in other client libraries.

1) 2003r2 (non-farm, hid safesign/gemsafe libraries)
rdesktop -> smartcard read/interaction OK
xfreerdp -> reader passed ok, but cards not seen inside session

2) 2008r2 (non-farm, hid safesign, gemsafe libs not installed here)
rdesktop -> smartcard read/interaction fine 
xfreerdp -> safesign admin software crashes on launch.

3) 2008r2 (non-farm, gemsafe, hid safesign libs not installed here)
rdesktop -> smartcard read/interaction fine 
xfreerdp -> gemalto admin software crashes on launch.

I have also raised an issue that smartcard redirection segfaults when I connect to a server farm (issue #1425). It is possible that the two are linked but I suspect its more likely the segfault is just a side effect of the reconnection attempt, rather than related to the content/behaviour of the scard virtual channel.

Any ideas on how best to investigate further?

**Comment by sconstantine** [comment]
Any progress or updates to smart card redirection?

**Comment by bmiklautz** [comment]
Should work on master. If you still see this issue please re-open or recreate a new one.
