### ISSUE TITLE
Caps lock does not work on mac client (possible solution included)

### ISSUE THREAD

**Issue by chmod84** [FreeRDP/FreeRDP#1449]
Dear all,
caps lock management has not been implemented into MRDPView.m

I added the following implementation replacing TODO'S printf and it seems to work.

Thank you
Stefano Iannucci
grep srl

// caps lock
    if (mf == 0x10100) {
        instance->input->KeyboardEvent(instance->input, KBD_FLAGS_DOWN, 0x3a);
        instance->input->KeyboardEvent(instance->input, KBD_FLAGS_RELEASE, 0x3a);
        kdcapslock =1;
    }
    if (kdcapslock && (mf == 0x100)) {
        kdcapslock = 0;
        instance->input->KeyboardEvent(instance->input, KBD_FLAGS_DOWN, 0xba);
        instance->input->KeyboardEvent(instance->input,KBD_FLAGS_RELEASE,0xba);
    }

**Comment by akallabeth** [comment]
Fixed with #4252
