### ISSUE TITLE
USB redirection from Ubuntu to Win7 Ultimate

### ISSUE THREAD

**Issue by gdhgdhgdh** [FreeRDP/FreeRDP#1452]
Hey guys,

I've compiled the current Git master of FreeRDP on Ubuntu 12.04 and it's working apart from the USB redirection. e.g.

gdh@gdh-x60s:~/FreeRDP$ sudo xfreerdp /v:10.0.0.28 /u:gdh /p:MySecret123 /usb:id,dev:1131:1001 /home-drive
loading channel rdpdr
loading channel rdpsnd
loading channel drdynvc
connected to 10.0.0.28:3389
Loading device service drive (static)
Loading Dynamic Virtual Channel urbdrc
VID: 0x1131 PID: 0x1001
Regist Device: Vid: 0x1131 Pid: 0x1001 InterfaceClass = 0xE0
registered device #1: home (type=8 id=1)

I can see 'home on gdh-x60s' in 'Computer' and can browse my local files just fine. The thing that's failing is the redirection of a Bluetooth USB device:
# lsusb | grep 1131

Bus 002 Device 004: ID 1131:1001 Integrated System Solution Corp. KY-BT100 Bluetooth Adapter

In the Device Manager of the remote Windows 7 Ultimate machine, no Bluetooth adapter, or 'Unknown Device' appears... nor does anything appear in the System event log about new hardware.

What have I missed? Is this even a supported thing - I couldn't find anything on the wiki about it.

**Comment by akallabeth** [comment]
I've started refactoring the code with #3175 hoping to improve the situation.

**Comment by akallabeth** [comment]
Fixed with #5745

**Comment by ott** [comment]
@akallabeth I'm unable to test it but can be close this issue if you are confident that the changes solve the problem?

**Comment by akallabeth** [comment]
@ott pr has been merged, so current nightly packages should work.
Closing this (and all related issues). Create a new one if there are still issues.
