### ISSUE TITLE
Problems mit remote apps

### ISSUE THREAD

**Issue by arakis** [FreeRDP/FreeRDP#1471]
Hello,
i've found some bugs with remote apps.
- With "calc" (in my case called via cmd), sometimes, its possible to resize it, when dragging to the screen borders. This is the auto resizing method of xfce4 (and a lot of other WMs) to "dock" a window and resize it. With notepad, is works normally. With calc, is will not resized....most of the time. But sometimes, it will be resized. This should not be.
- Sometimes, when trying to "force" to resize (moving to the screen borders), the calc windows completly freezes (instead of accidently resizing). It must be terminated.
- Huge problems with Visual Studio 2012. (Screenshot)
  The application has an "extra" border arround it. Its not there, when the app is maximized. But when in non-maximized state, the border makes problems:
- When another (linux) window is over the visual studio window, the border is always on top. (Screenshot)
- When moving the visual studio window. the border will "stay" there, untill the move operation is completed.

command line: xfreerdp /u:sebastian /p:***\* /v:192.168.20.14 /app:"||cmd"
version: the latest git version
host os: Arch Linux, latest version (kernel 3.10.10).
Windows manager: xfce4, using tripple head (three screens connected)
remote os: win7 x64 ultimate, all updates installed

![border](https://f.cloud.github.com/assets/1831942/1124907/7e7cbf5c-1b07-11e3-9895-b9346b94705c.png)
![border always on top](https://f.cloud.github.com/assets/1831942/1124909/86beda24-1b07-11e3-9b21-7d325a2af1db.png)
![border while moving](https://f.cloud.github.com/assets/1831942/1124911/8a2e36dc-1b07-11e3-97fa-09e2abd8516f.png)

Greetings,
Sebastian

**Comment by bmiklautz** [comment]
I'm closing this issue because it has been inactive for a while.
Possibly we've already fixed the issue or it is not reproducible (anymore).

If you still encounter the reported problem with our [latest stable release](https://github.com/FreeRDP/FreeRDP/releases) please re-open this issue with updated information or create a [new bug report](https://github.com/FreeRDP/FreeRDP/issues/new?template=bug_report.md).

Thank you!
