### ISSUE TITLE
One screen is black when using full screen on tripple monitor

### ISSUE THREAD

**Issue by Arakis** [FreeRDP/FreeRDP#1472]
Hello,
my left monitor is black, when using fullscreen mode while using the middle or right monitor in the /monitors: argument. The selected monitor as fullscreen with rdp, and the "non-black" screen has the normal xfce4-desktop.

My monitors are in this order (when using /monitors:) Left monitor=2, middle=0, right=1.
My xrandr command: 
xrandr --output DVI-0 --pos 0x0 --output DisplayPort-0 --pos 1920x0 --primary --output HDMI-0 --pos 3840x0 --output DVI-1 --off
(this works 100% fine. I post here only a problem about xfreerdp).

And of course, the montors are in the right order.

The xfreerdp command:
xfreerdp /u:**\* /p:**\* +clipboard /f /bpp:24 /cert-ignore /v:**\* /monitors:0

Greetings,
Sebastian

**Comment by akallabeth** [comment]
Works on current master (pre 2.0.0-rc2)
