### ISSUE TITLE
freerdp crashing sporadically with connection to gateway

### ISSUE THREAD

**Issue by elangelo** [FreeRDP/FreeRDP#1473]
I'm using freerdp from master,
connect to a 2012 gateway server to a windows 8 workstation. Seems to work ok, everynow and then freerdp quits with the below message printed on the command line (until EOM):

Got stub length 4 with flags 3 and callid 27298
Got stub length 4 with flags 3 and callid 27299
Got stub length 4 with flags 3 and callid 27300
Got stub length 4 with flags 3 and callid 27301
Got stub length 4 with flags 3 and callid 27302
Got stub length 4 with flags 3 and callid 27303
Got stub length 4 with flags 3 and callid 27304
Got stub length 4 with flags 3 and callid 27305
Got stub length 4 with flags 3 and callid 27306
Got stub length 4 with flags 3 and callid 27307
Got stub length 4 with flags 3 and callid 27308
Got stub length 4 with flags 3 and callid 27309
Got stub length 4 with flags 0 and callid 6
WARNING: invalid packet signature
Got stub length 4 with flags 3 and callid 27310
WARNING: invalid packet signature
Failed to check FreeRDP file descriptor
Got stub length 4 with flags 3 and callid 27311
Got stub length 4 with flags 2 and callid 6
WaitForSingleObject: pthread_join failure: [3] No such process

**EOM**

build with: 
                -DCMAKE_BUILD_TYPE=Debug \
                -DWITH_SSE2=ON \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_INSTALL_LIBDIR=lib \
        -DWITH_PULSE=ON \
        -DWITH_SERVER=ON \

**Comment by akallabeth** [comment]
error message no longer part of freerdp, closing.

**Comment by greenLeopard** [comment]
sorry to hit this again. yesterday after some Ubuntu Software updates (Ubuntu 16.04) my xfreerdp had disappeared.
i re-installed xfreerdp (sudo apt-get install freerdp-x11), now i can't connect to remote desktop...
Command line I'm using: xfreerdp /u:[username] /p:[password] /v:[workstation] /g:[gateway]
Message I'm getting:
connected to [gateway]:443
connected to [gateway]:443
TS Gateway Connection Success
Got stub length 4 with flags 3 and callid 7
Got stub length 4 with flags 3 and callid 6
Error: protocol security negotiation or connection failure.

Tried removing and re-installing.
Tried installing and failed installing from source (https://github.com/FreeRDP/FreeRDP/wiki/Compilation).

Just want to get onto the remote desktop and get to work.

**Comment by akallabeth** [comment]
@greenLeopard Try our nightly builds https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by dagrha** [comment]
I was getting those stub length errors too (Ubuntu 18.04). I uninstalled freerdp-x11 (and autoremoved dependencies), then instead installed `freerdp2-x11` (`sudo apt install freerdp2-x11`). All is working perfectly now. 

Thanks to the FreeRDP team for this fantastic project.
