### ISSUE TITLE
Manpage compilation issue in 

### ISSUE THREAD

**Issue by BUGgs** [FreeRDP/FreeRDP#1474]
Compilation failed using Ubuntu 10.04 with xsltproc (libxml 20706, libxslt 10126, libexslt 815) on ARM CPU

[ 99%] Built target xfreerdp-client
make -f client/X11/CMakeFiles/xfreerdp.manpage.dir/build.make client/X11/CMakeFiles/xfreerdp.manpage.dir/depend
make[2]: Entering directory `/root/dev/FreeRDP-master'
make[2]: Warning: File`client/X11/CMakeFiles/xfreerdp.manpage.dir/build.make' has modification time 1.6e+04 s in the future
cd /root/dev/FreeRDP-master && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /root/dev/FreeRDP-master /root/dev/FreeRDP-master/client/X11 /root/dev/FreeRDP-master /root/dev/FreeRDP-master/client/X11 /root/dev/FreeRDP-master/client/X11/CMakeFiles/xfreerdp.manpage.dir/DependInfo.cmake --color=
make[2]: warning:  Clock skew detected.  Your build may be incomplete.
make[2]: Leaving directory `/root/dev/FreeRDP-master'
make -f client/X11/CMakeFiles/xfreerdp.manpage.dir/build.make client/X11/CMakeFiles/xfreerdp.manpage.dir/build
make[2]: Entering directory`/root/dev/FreeRDP-master'
make[2]: Warning: File `client/X11/CMakeFiles/xfreerdp.manpage.dir/build.make' has modification time 1.6e+04 s in the future
/usr/bin/cmake -E cmake_progress_report /root/dev/FreeRDP-master/CMakeFiles 
[ 99%] Generating xfreerdp.1
cd /root/dev/FreeRDP-master/client/X11 && /root/dev/FreeRDP-master/client/X11/generate_argument_docbook
cd /root/dev/FreeRDP-master/client/X11 && /usr/bin/cmake -E copy /root/dev/FreeRDP-master/client/X11/xfreerdp-channels.1.xml /root/dev/FreeRDP-master/client/X11
cd /root/dev/FreeRDP-master/client/X11 && /usr/bin/cmake -E copy /root/dev/FreeRDP-master/client/X11/xfreerdp-examples.1.xml /root/dev/FreeRDP-master/client/X11
cd /root/dev/FreeRDP-master/client/X11 && /usr/bin/xsltproc /usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl xfreerdp.1.xml
xfreerdp-argument.1.xml:425: parser error : PCDATA invalid Char value 25
                                <term><option>/jpeg-quality</option> <replaceable>&lt;percentage&gt;</repla
                                                           ^
xfreerdp-argument.1.xml:624: parser error : chunk is not well balanced

^
xfreerdp.1.xml:51: parser error : Failure to process entity syntax
        &syntax;
                ^
xfreerdp.1.xml:51: parser error : Entity 'syntax' not defined
        &syntax;
                ^
unable to parse xfreerdp.1.xml
make[2]: **\* [client/X11/xfreerdp.1] Error 6
make[2]: Leaving directory `/root/dev/FreeRDP-master'
make[1]: *** [client/X11/CMakeFiles/xfreerdp.manpage.dir/all] Error 2
make[1]: Leaving directory`/root/dev/FreeRDP-master'
make: **\* [all] Error 2

**Comment by TheElf** [comment]
I just experienced the same issue on a ubuntu Trusty in a crouton chroot (Chromeos host)

disabling manpages didn't do the trick. I'm debugging it right now
