### ISSUE TITLE
Smartcard Redirection to Windows 2008 R2 Shared Mode

### ISSUE THREAD

**Issue by michaelschefczyk** [FreeRDP/FreeRDP#1476]
Dear All,

My aim is to connect from a Debian PC (or Linux Mint Debian Edition - tried both) to a WTS running on a Windows Server 2008 R2 via FreeRDP. I want to redirect a smartcard into that session and it needs to be in "shared mode". Unfortunately, I do not find documentation of such issues to be quite extensive, yet.

Since I felt that the 1.0.1 version of FreeRDP in Debian packages may have been the cause of issues, I did compile from git on September 15, 2013. I did cure initial problems with smartcard redirection as inicated here:

http://sourceforge.net/mailarchive/forum.php?thread_name=20121207144603.GC6362%40glanzmann.de&forum_name=freerdp-devel

After that, the session on the WTS server did see and recognize the smartcard. The program there did ask for the smartcard PIN, it did validate the PIN but it did not work to the very end. The probable cause is that the windows application (Datev eG accounting software) requires the smartcard to be in "shared mode". Doing a pcsc_scan on the Debian PC, I cannot detect the "shared mode" capability for that card. Plugging the same reader and card into a Windows PC yiels full performance including "shared mode". Most pcsc_scan output I could find searching the internet shows the "shared mode" state. However, I could by no means find any instruction regarding how to get a reader/card to "shared mode" in a Debian system.

Could someone please point me (and others) to the right direction?

Thanks & Regards,

Michael

**Comment by akallabeth** [comment]
#4312 fixed a lot of smartcard usability errors.
Reopen if still an issue.
