### ISSUE TITLE
virtual channels should support compression

### ISSUE THREAD

**Issue by atong** [FreeRDP/FreeRDP#148]
Compression breaks rdpdr; will likely cause segfault

loading plugin rdpdr
connected to <...>
svc_plugin_process_received: read error
Warning rdpdr_process_capability_request (162): Unknown capabilityType 11264
Warning rdpdr_process_capability_request (162): Unknown capabilityType 44235
Warning rdpdr_process_capability_request (162): Unknown capabilityType 4000
... many Warnings

edit: updated title

**Comment by avigruda** [comment]
From what I see, the vchan code still doesn't support compression:
(`flags = VCCAPS_NO_COMPR;` in `rdp_write_virtual_channel_capability_set()`)
Am I right?
