### ISSUE TITLE
Security Negotiation Fails to Detect RDP in Some Cases

### ISSUE THREAD

**Issue by Lonniebiz** [FreeRDP/FreeRDP#1484]
I use Remmina, and Remmina uses FreeRDP under the hood. Sometimes FreeRDP fails to auto-negotiate (detect) that the correct security is RDP, and here's the confusion that causes to the end user:
https://bugs.launchpad.net/freerdp/+bug/1205484

**Comment by akallabeth** [comment]
Still an issue?

**Comment by Lonniebiz** [comment]
Actually, now, the negotiation feature is more reliable than explicitly indicating it is RDP these days for me. Sometimes specifically indicating RDP fails to connect without much elaboration. Then, I'll switch to negotiate and it will prompt me to approve a new fingerprint and then proceed to connect without issue.

FYI: I'm using the latest version of Remmina Next on Ubuntu 16.04.3; I install it in one line like this:

sudo apt-add-repository ppa:remmina-ppa-team/remmina-next ; sudo apt-get update ; sudo apt-get install remmina remmina-plugin-rdp

**Comment by akallabeth** [comment]
Thank you, another one bites the dust, yea
