### ISSUE TITLE
smartcard redirection problem: not valid certificate found

### ISSUE THREAD

**Issue by k84834** [FreeRDP/FreeRDP#1488]
Hello 
after working with both FreeRDP1.1 and FreeRDP-1.0.2 , I face with " not valid certificate found" problem. 
on Freerdp-1.1 with debug mode I get: 
xfreerdp  -sec-nla -sec-tls /smartcard:"OMNIKEY CardMan (076B:3021) 3021 00 00" /v:x.x.x.x
DBG_SCARD handle_GetAttrib (1149): Success (10 bytes)
0000 72 44 43 49 01 00 00 00 00 00 00 00 11 00 00 00 rDCI............
0010 30 00 00 00 01 10 08 00 cc cc cc cc 20 00 00 00 0........... ...
0020 00 00 00 00 00 00 00 00 0a 00 00 00 00 02 00 00 ................
0030 0a 00 00 00 48 49 44 20 47 6c 6f 62 61 6c 00 00 ....HID Global..
0040 00 00 00 00                                     ....
DBG_SCARD handle_GetAttrib (1080): hcard: 0x1605f2f0, attrib: 0x00010102 (-1 bytes)
DBG_SCARD handle_GetAttrib (1143): Failure: Feature not supported. (0x8010001f)
0000 72 44 43 49 01 00 00 00 00 00 00 00 11 00 00 00 rDCI............
0010 14 01 00 00 01 10 08 00 cc cc cc cc 04 01 00 00 ................
0020 00 00 00 00 22 00 10 80 00 00 00 00 00 00 00 00 ...."...........
0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0080 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0090 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0100 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0110 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0120 00 00 00 00 00 00 00 00  

and on Freerdp-1.0.2:
  xfreerdp --no-nla --no-tls --plugin rdpdr --data scard:"OMNIKEY CardMan (076B:3021) 3021 00 00" -- x.x.x.x
DBG_SCARD handle_GetAttrib (1141): Success (10 bytes)
0000 72 44 43 49 01 00 00 00 00 00 00 00 00 00 00 00 rDCI............
0010 30 00 00 00 01 10 08 00 cc cc cc cc 18 00 00 00 0...............
0020 00 00 00 00 00 00 00 00 0a 00 00 00 00 02 00 00 ................
0030 0a 00 00 00 48 49 44 20 47 6c 6f 62 61 6c 00 00 ....HID Global..
0040 00 00 00 00                                     ....
DBG_SCARD handle_GetAttrib (1066): hcard: 0x0db3b7d2, attrib: 0x00010102 (-1 bytes)

DBG_SCARD handle_GetAttrib (1135): Failure: Feature not supported. (0x8010001f)
0000 72 44 43 49 01 00 00 00 00 00 00 00 00 00 00 00 rDCI............
0010 18 01 00 00 01 10 08 00 cc cc cc cc fc 00 00 00 ................
0020 00 00 00 00 22 00 10 80 00 00 00 00 00 00 00 00 ...."...........
0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0080 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0090 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
00f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0100 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0110 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
0120 00 00 00 00 00 00 00 00 00 00 00 00      

I try smartcard redirection on rdesktop and first face with "not valid certificate found" issue but after I try with second commandline and all thing be right .
first: rdesktop -r scard:"OMNIKEY CardMan (076B:3021) 3021 00 00" x.x.x.x
second: rdesktop -r scard:"OMNIKEY CardMan (076B:3021) 3021 00 00"="CardMan 3x21;OMNIKEY" x.x.x.x
rdesktop needs windows reader name.
thanks for your attentions before. :)

**Comment by akallabeth** [comment]
#4312 fixed a lot of smartcard usability errors.
Reopen if still an issue.
