### ISSUE TITLE
Clipboard On Remote APP *master branch*

### ISSUE THREAD

**Issue by hteles** [FreeRDP/FreeRDP#1513]
Hi, 

clipboard doens't seem to be working in Remote Application Mode.

Compilation : Kubuntu 13.10
$git log
commit 0d7df9ab72f1cc1c453db90fd8d193319b899bdf
Merge: 3d6139f 6328006
Author: Marc-André Moreau marcandre.moreau@gmail.com
Date:   Wed Sep 25 08:37:26 2013 -0700

Compiled With:
cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_FFMPEG=ON -DWITH_CUPS=ON ..

Command Line:
xfreerdp -themes -wallpaper +clipboard  /printer:teste_fds_Printer /drive:MyDisk,$HOME/Desktop -sec-rdp /cert-ignore  /u:USER /p:PASS  /app:"||Erp800LP"  /v:192.168.X.XX

**Comment by bmiklautz** [comment]
Fixed with #3934
