### ISSUE TITLE
Big problem in 'ALT+TAB' to switch applications inside of RDP.

### ISSUE THREAD

**Issue by UiuSilveira** [FreeRDP/FreeRDP#1520]
Hi.
Well, i have a big problem.
First, sorry for my english, i'm brazilian and don't speak english very well..
My problem is that, when i press 'ALT+TAB', to switch between two applications, for example, two excel documents. When i press the shortcut 'ALT+TAB', the cursor 'lost', then, i cannot keep writing while i don't move the mouse. After i move the mouse,  i 'return to the application', and then, i can writing in the document.
But it just happens when i pressed 'ALT+TAB' fast, if i do it with a interval about 2 seconds, it works.

**Comment by akallabeth** [comment]
Looks like a dead issue, closing.
Reopen if still of matter.
