### ISSUE TITLE
Arguments in Client Execute PDU do not seem to work in windows server 2012 RemoteApp

### ISSUE THREAD

**Issue by howardko** [FreeRDP/FreeRDP#1522]
The arguments in client execute PDU for remoteApp does not seem to work in server 2012, i.e., the arguments value in Client Execute PDU does not transmitted successfully to windows server 2012; the remoteApp can execute successfully, but the arguments for the RemoteApp does not work.

But there's no problem in server 2008. Does anyone have any ideas?

The following is the command I execute in my ubuntu machine, 
xfreerdp -u srvadmin -d domain -p password --app --plugin rail --data "%windir%\system32\notepad.exe:%windir%:%windir%\mytest.txt" -- 192.168.87.229

In server 2008 R2, notepad.exe will execute and mytest.txt will open, but in server 2012, the notepad.exe will execute but mytest.txt will not open. 

Furthermore, I use processExplorer.exe to see the commandline argument of RemoteApp(which is notepad.exe)  in server 2008 R2, I can see the "Command Line" displaying "c:\windows\system32\notepad.exe c:\windows\mytest.txt".

But in server 2012,  I use processExplorer.exe to see the commandline argument of RemoteApp(which is notepad.exe), I can see the "Command Line" displaying only "c:\windows\system32\notepad.exe", which means that the argument for RemoteApp is not transmitted successfully or somehow dropped by RemoteApp shell of server 2012.

**Comment by itsmikeeng** [comment]
I was running into the same problem for Windows Server 2012 R2. RemoteApp programs need to be specifically allowed to use command-line parameters. That can be configured from Server Manager, see section 5 and 6 of http://blogs.technet.com/b/infratalks/archive/2013/02/06/publishing-remoteapps-and-remote-session-in-remote-desktop-services-2012.aspx.

**Comment by akallabeth** [comment]
Closing as a configuration issue.
