### ISSUE TITLE
FreeRDP auth failed on powerpc linux

### ISSUE THREAD

**Issue by dejiko** [FreeRDP/FreeRDP#1529]
i tried FreeRDP on powerpc, but couldn't login to rdp host.

OS : Debian wheezy on PowerMac G5 (32-bit userland), X11
FreeRDP branch : stable-1.1 branch, d2a9df1ce02305e22fe0b7d10b0f8961ed694ec3
connect to Windows 7 host, NLA enabled.
(Same problem on Windows8, Windows Server 2008R2. These also NLA enabled.)
make parameter : no extra parameter.   $ cmake CMakeLists.txt

Console:

$ ./client/X11/xfreerdp /u:user /v:host
connected to host:3389
Password: 
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure
$

i will test with more debug options, but what infomation need to debug this issue?

thanks,

**Comment by akallabeth** [comment]
Closing as fixed, reopen if still an issue.
