### ISSUE TITLE
PDU ERROR

### ISSUE THREAD

**Issue by guxinglei** [FreeRDP/FreeRDP#1539]
run_wfreerdp: inst->rdp_connect OK!
run_wfreerdp: freerdp_chanman_post_connect OK!
run_wfreerdp: wf_post_connect OK!
ui_error: ERROR: pduType version must be 0 and 1 but is 0 and 0

what is the reason to cause this problem?
pduType version must be 0 and 1 but is 0 and 0

**Comment by jdiazbb** [comment]
i think you have no login rights to that machine (or incorrect password...)

**Comment by hardening** [comment]
@guxinglei this doesn't look like a bug report (missing a lot of details). If you have questions there's IRC or the mailing list. This is a bug tracker not a forum.

**Comment by bmiklautz** [comment]
@guxinglei  https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
