### ISSUE TITLE
Unable to redirect sound to local machine

### ISSUE THREAD

**Issue by parmsd** [FreeRDP/FreeRDP#1540]
I am user git master compiled on tiny core
I am unable to redirect audio from the RDP server to the local client machine

Either command:
xfreerdp /u:XXX /p:XXX /d:XX /cert-ignore / sec:rdp /f /sound:sys:alsa /multimon /v:XXXX
xfreerdp /u:XXX /p:XXX /d:XX /cert-ignore / sec:rdp /f /sound /multimon /v:XXXX

Generates this error when I try to play a sound
requested sound buffer size 4400, for 1881 instead

And when I try to disconnect from the RDP session, the RDP session hangs

If I run xfreerdp without the /sound option I can disconnect from the RDP session but obviously no sound is redirected.

Similar to this which doesn't have a solution
https://github.com/FreeRDP/FreeRDP/issues/1365

(and discussed in this thread 
http://sourceforge.net/mailarchive/forum.php?thread_name=zarafa.514b23b8.733a.478c2c4f78973d39%40srvgr1.ubrichter.de&forum_name=freerdp-devel 
)

I tried using a different version of rdpsnd_alsa.c as suggested in the above but just received different errors

**Comment by marblenix** [comment]
`/sound:sys:pulse` worked for me

`FreeRDP version 2.0.0-dev (git 3375865)`

**Comment by akallabeth** [comment]
Tested on debian jessie, working with alsa and pulse.
