### ISSUE TITLE
Squiggly lines show up as an inverted-color block

### ISSUE THREAD

**Issue by jaapp** [FreeRDP/FreeRDP#1546]
Using the latest version of freeRDP from source. The issue is not client specific - I encounter it on all machines I connect to.

![screenshot](https://f.cloud.github.com/assets/3406948/1327391/3a2e0422-34ee-11e3-9e8b-3a03a01cddb4.png)

As you can see in the screenshot the red on white squiggly lines show as blue on black (inverted).

**Comment by jaapp** [comment]
6 months later this issue is still present. Even when using the latest from the remmina-next repository.

**Comment by bmiklautz** [comment]
@jaapp does it only happen with sql server managment studio or do you have other programs one can reproduce it with?

**Comment by jaapp** [comment]
@bmiklautz - Over the last weeks I tried to produce the same artifact in various other tools (Microsoft Word, Chrome, Firefox). None of them show the black bar. So the issue seems to be specific to SQL Server Management Studio.

**Comment by bmiklautz** [comment]
@jaapp what version of the SQL server management studio did you test with?

**Comment by jaapp** [comment]
@bmiklautz SQL Server 2008R2

I believe it's present in visual studio 2008 SP1 and onwards due to the adding of the 'Live Semantic Error'-feature. I get the same black line when I create a vb.net application and add some errors in my code.

**Comment by bmiklautz** [comment]
@jaapp can you add the command line you are using and the RDP sever OS you are connecting to?

**Comment by akallabeth** [comment]
Any news on this one, is it still not working?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
