### ISSUE TITLE
Installing FreeRDP on Raspberry Pi

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#1549]
Hi there,

I'm trying to install FreeRDP on my Raspberry Pi running Raspbian, using the manual provided here: https://github.com/FreeRDP/FreeRDP/wiki/Compilation

I follow it through step to step (to the letter) and every time I'm getting to the part where I'm generating makefiles (cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .) I get this error message: 

root@raspberrypi:/home/pi/FreeRDP# cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_ALSA=OFF .
-- FreeRDP GIT
-- Git Revision 1.1.0-beta+2013071101-625-gf0fe2
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:288 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindThreads.cmake:166 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:304 (find_package)

-- Configuring incomplete, errors occurred!
root@raspberrypi:/home/pi/FreeRDP# 

Any help would be greatly appreciated.

**Comment by si458** [comment]
Hi,
I managed to compile the freerdp just using ` cmake -DWITH_NEON=OFF . `
however the full screen doesnt work :(
any way of making it work?
Simon

**Comment by rnubis** [comment]
On other system same, but for x86 fullscreen start work after use  -DWITH_X11=ON -DWITH_XINERAMA=ON .
