### ISSUE TITLE
xfreerdp: corrupted double-linked list: 0x0955e540

### ISSUE THREAD

**Issue by monosoul** [FreeRDP/FreeRDP#1555]
Hello!
Today I've faced this issue: xfreerdp crashes during connection to Windows 2008R2 TS. Branch is stable-1.1.
_FreeRDP is compiled with next options:_ -DWITH_PCSC=ON -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF
_Command line:_ xfreerdp /d:DOMAIN_NAME /bpp:16 /kbd:0x00000419 -bitmap-cache -offscreen-cache -sec-nla /f /cert-ignore /v:SERVER_IP:3389

Here is xfreerdp crash report ( http://pastebin.com/Uqm5fASD ):

**\* glibc detected **\* xfreerdp: corrupted double-linked list: 0x0955e540 ***
======= Backtrace: =========
/lib/bin/../libc.so.6(+0x6aae1)[0xb7108ae1]
/lib/bin/../libc.so.6(+0x6af1a)[0xb7108f1a]
/lib/bin/../libc.so.6(+0x6ca65)[0xb710aa65]
/lib/bin/../libc.so.6(__libc_malloc+0x5c)[0xb710d07c]
/lib/bin/../libxfreerdp-client.so.1.1(xf_Bitmap_Decompress+0x2b9)[0xb76e68c9]
/lib/bin/../libfreerdp-cache.so.1.1(update_gdi_cache_bitmap_v2+0xa1)[0xb765a361]
/lib/bin/../libfreerdp-core.so.1.1(update_recv_secondary_order+0x282)[0xb7624632]
/lib/bin/../libfreerdp-core.so.1.1(update_recv_order+0x98)[0xb7624a98]
/lib/bin/../libfreerdp-core.so.1.1(+0x3f80d)[0xb763280d]
/lib/bin/../libfreerdp-core.so.1.1(fastpath_recv_updates+0x33f)[0xb7632f0f]
/lib/bin/../libfreerdp-core.so.1.1(+0x3e867)[0xb7631867]
/lib/bin/../libfreerdp-core.so.1.1(transport_check_fds+0x9d)[0xb763513d]
/lib/bin/../libfreerdp-core.so.1.1(rdp_check_fds+0x20)[0xb7631b60]
/lib/bin/../libfreerdp-core.so.1.1(freerdp_check_fds+0x2a)[0xb7624f4a]
/lib/bin/../libxfreerdp-client.so.1.1(xf_thread+0x503)[0xb76ebc43]
/lib/bin/../libpthread.so.0(+0x5de9)[0xb7211de9]
/lib/bin/../libc.so.6(clone+0x5e)[0xb716ab7e]
======= Memory map: ========
08048000-0804a000 r-xp 00000000 00:0e 224        /lib/bin/xfreerdp
0804a000-0804b000 rw-p 00001000 00:0e 224        /lib/bin/xfreerdp
08988000-09cd3000 rw-p 00000000 00:00 0          [heap]
b6300000-b6321000 rw-p 00000000 00:00 0
b6321000-b6400000 ---p 00000000 00:00 0
b643b000-b6456000 r-xp 00000000 00:01 705        /fastboot/libgcc_s.so.1
b6456000-b6457000 rw-p 0001a000 00:01 705        /fastboot/libgcc_s.so.1
b6457000-b6458000 r-xp 00000000 00:0e 836        /lib/X11/locale/common/xlcUTF8Load.so.2.0.0
b6458000-b6459000 rw-p 00000000 00:0e 836        /lib/X11/locale/common/xlcUTF8Load.so.2.0.0
b6459000-b645a000 r--s 00000000 00:0e 162        /lib/gconv/gconv-modules.cache
b645a000-b645b000 rw-s 00000000 00:04 32768      /SYSV00001e61 (deleted)
b645b000-b645c000 ---p 00000000 00:00 0
b645c000-b6c7d000 rw-p 00000000 00:00 0          [stack:1858]
b6c7d000-b6d9d000 r--p 0022a000 00:0e 154        /lib/locale/locale-archive
b6d9d000-b6f9d000 r--p 00000000 00:0e 154        /lib/locale/locale-archive
b6f9d000-b6fa1000 rw-p 00000000 00:00 0
b6fa1000-b7069000 r-xp 00000000 00:0e 165        /lib/libasound.so.2.0.0
b7069000-b706d000 rw-p 000c8000 00:0e 165        /lib/libasound.so.2.0.0
b706d000-b7075000 r-xp 00000000 00:0e 941        /lib/libpcsclite.so.1.0.0
b7075000-b7076000 rw-p 00008000 00:0e 941        /lib/libpcsclite.so.1.0.0
b7076000-b707a000 r-xp 00000000 00:0e 370        /lib/libXfixes.so.3
b707a000-b707b000 rw-p 00003000 00:0e 370        /lib/libXfixes.so.3
b707b000-b707f000 r-xp 00000000 00:0e 235        /lib/libXdmcp.so.6
b707f000-b7080000 rw-p 00003000 00:0e 235        /lib/libXdmcp.so.6
b7080000-b7081000 rw-p 00000000 00:00 0
b7081000-b7083000 r-xp 00000000 00:0e 234        /lib/libXau.so.6
b7083000-b7084000 rw-p 00001000 00:0e 234        /lib/libXau.so.6
b7084000-b7085000 r-xp 00000000 00:0e 304        /lib/libpthread-stubs.so.0
b7085000-b7086000 rw-p 00000000 00:0e 304        /lib/libpthread-stubs.so.0
b7086000-b709d000 r-xp 00000000 00:0e 303        /lib/libxcb.so.1
b709d000-b709e000 rw-p 00016000 00:0e 303        /lib/libxcb.so.1
b709e000-b71f3000 r-xp 00000000 00:01 432        /fastboot/libc.so.6
b71f3000-b71f4000 ---p 00155000 00:01 432        /fastboot/libc.so.6
b71f4000-b71f6000 r--p 00155000 00:01 432        /fastboot/libc.so.6
b71f6000-b71f7000 rw-p 00157000 00:01 432        /fastboot/libc.so.6
b71f7000-b71fa000 rw-p 00000000 00:00 0
b71fa000-b71fb000 r-xp 00000000 00:0e 939        /lib/libwinpr-environment.so.0.1.0
b71fb000-b71fc000 rw-p 00000000 00:0e 939        /lib/libwinpr-environment.so.0.1.0
b71fc000-b71fd000 rw-p 00000000 00:00 0
b71fd000-b71fe000 r-xp 00000000 00:0e 937        /lib/libwinpr-heap.so.0.1.0
b71fe000-b71ff000 rw-p 00000000 00:0e 937        /lib/libwinpr-heap.so.0.1.0
b71ff000-b7202000 r-xp 00000000 00:0e 935        /lib/libwinpr-crt.so.0.1.0
b7202000-b7203000 rw-p 00002000 00:0e 935        /lib/libwinpr-crt.so.0.1.0
b7203000-b7207000 r-xp 00000000 00:0e 933        /lib/libwinpr-path.so.0.1.0
b7207000-b7208000 rw-p 00003000 00:0e 933        /lib/libwinpr-path.so.0.1.0
b7208000-b720a000 r-xp 00000000 00:01 706        /fastboot/libdl.so.2
b720a000-b720b000 r--p 00001000 00:01 706        /fastboot/libdl.so.2
b720b000-b720c000 rw-p 00002000 00:01 706        /fastboot/libdl.so.2
b720c000-b7221000 r-xp 00000000 00:01 710        /fastboot/libpthread.so.0
b7221000-b7222000 r--p 00014000 00:01 710        /fastboot/libpthread.so.0
b7222000-b7223000 rw-p 00015000 00:01 710        /fastboot/libpthread.so.0
b7223000-b7226000 rw-p 00000000 00:00 0
b7226000-b7227000 r-xp 00000000 00:0e 931        /lib/libwinpr-handle.so.0.1.0
b7227000-b7228000 rw-p 00000000 00:0e 931        /lib/libwinpr-handle.so.0.1.0
b7228000-b722a000 r-xp 00000000 00:0e 929        /lib/libwinpr-thread.so.0.1.0
b722a000-b722b000 rw-p 00001000 00:0e 929        /lib/libwinpr-thread.so.0.1.0
b722b000-b722c000 r-xp 00000000 00:0e 927        /lib/libwinpr-interlocked.so.0.1.0
b722c000-b722d000 rw-p 00000000 00:0e 927        /lib/libwinpr-interlocked.so.0.1.0
b722d000-b7231000 r-xp 00000000 00:0e 925        /lib/libwinpr-synch.so.0.1.0
b7231000-b7232000 rw-p 00003000 00:0e 925        /lib/libwinpr-synch.so.0.1.0
b7232000-b7256000 r-xp 00000000 00:01 707        /fastboot/libm.so.6
b7256000-b7257000 r--p 00023000 00:01 707        /fastboot/libm.so.6
b7257000-b7258000 rw-p 00024000 00:01 707        /fastboot/libm.so.6
b7258000-b7259000 rw-p 00000000 00:00 0
b7259000-b7260000 r-xp 00000000 00:01 589        /fastboot/librt-2.13.so
b7260000-b7261000 r--p 00006000 00:01 589        /fastboot/librt-2.13.so
b7261000-b7262000 rw-p 00007000 00:01 589        /fastboot/librt-2.13.so
b7262000-b7263000 r-xp 00000000 00:0e 923        /lib/libwinpr-sysinfo.so.0.1.0
b7263000-b7264000 rw-p 00001000 00:0e 923        /lib/libwinpr-sysinfo.so.0.1.0
b7264000-b73b1000 r-xp 00000000 00:01 587        /fastboot/libcrypto.so.1.0.0
b73b1000-b73c5000 rw-p 0014c000 00:01 587        /fastboot/libcrypto.so.1.0.0
b73c5000-b73c8000 rw-p 00000000 00:00 0
b73c8000-b7413000 r-xp 00000000 00:01 559        /fastboot/libssl.so.1.0.0
b7413000-b7417000 rw-p 0004b000 00:01 559        /fastboot/libssl.so.1.0.0
b7417000-b742a000 r-xp 00000000 00:0e 80         /lib/libz.so.1
b742a000-b742b000 rw-p 00012000 00:0e 80         /lib/libz.so.1
b742b000-b742c000 rw-p 00000000 00:00 0
b742c000-b7440000 r-xp 00000000 00:0e 920        /lib/libwinpr-utils.so.0.1.0
b7440000-b7441000 rw-p 00014000 00:0e 920        /lib/libwinpr-utils.so.0.1.0
b7441000-b7451000 rw-p 00000000 00:00 0
b7451000-b7458000 r-xp 00000000 00:0e 918        /lib/libfreerdp-utils.so.1.1.0
b7458000-b7459000 rw-p 00006000 00:0e 918        /lib/libfreerdp-utils.so.1.1.0
b7459000-b745c000 r-xp 00000000 00:0e 916        /lib/libfreerdp-rail.so.1.1.0
b745c000-b745d000 rw-p 00002000 00:0e 916        /lib/libfreerdp-rail.so.1.1.0Aborted

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
