### ISSUE TITLE
RD Connection Broker support is broken in master branch since commit 3b7994a9a6

### ISSUE THREAD

**Issue by monosoul** [FreeRDP/FreeRDP#1558]
Hello!
Remote Desktop Connection Broker support is broken in master branch since commit 3b7994a9a65523e9f53e3222842e188dc6875de1 . When I'm trying to connect to TS behind Connection Broker where is already exist my session, I'm just getting Segmentation fault.

_FreeRDP is compiled with next options:_ -DWITH_PCSC=ON -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF
_Command line:_ xfreerdp /wm-class:xfreerdpfs /size:1280x1024 /u:USERNAME /p:PASSWORD /cert-ignore /v:CONNECTION_BROKER_IP:3389 /d:DOMAIN /bpp:16 /kbd:0x00000419 -bitmap-cache -offscreen-cache

**Comment by trentasis** [comment]
With latest master branch seems to work
