### ISSUE TITLE
Click key "Caps Lock" repeatly, the client will be exit

### ISSUE THREAD

**Issue by baoshizhuang** [FreeRDP/FreeRDP#1560]
I compile freerdp on windows 7. when i access remote windows desktop by wfreerdp.exe, just click "Caps Lock" repeatly after I login windows successfully, the client will exit. The debug console display: SSL_read: I/O error\n, Failed to check FreeRDP file descriptor. I am looking forward your reply, thanks.

**Comment by akallabeth** [comment]
Still an issue?

**Comment by akallabeth** [comment]
Lacking feedback, closing.
Reopen if still an issue.
