### ISSUE TITLE
FreeRDP build error on windows 7

### ISSUE THREAD

**Issue by Ansujit** [FreeRDP/FreeRDP#1561]
I am building FreeRDP for android in windows 7.
I am using static openssl,Android SDK API 17,Android NDK r8d .
I have set the Environment variables
ANDROID_SDK,ANDROID_NDK,FREERDP_ANDROID_EXTERNAL_SSL_PATH.

Then I am running the below command,as per the instruction 

cmake -DCMAKE_TOOLCHAIN_FILE=cmake\AndroidToolchain.cmake

And getting the below Output with many missing include files but I checked the android-ndk-r8d and found some files are there but still getting the warning.
/******************************************************************************************/
CMake Warning (dev) at CMakeFiles/2.8.12/CMakeSystem.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:23 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/
CMakeDetermineSystem.cmake:90 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:43 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- FreeRDP GIT
STATUS,"ANDROID ADDED BY ANSUJIT"
-- Git Revision n/a
-- Performing Test Wno-unused-result
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test Wno-unused-result - Success
-- Performing Test Wno-unused-but-set-variable
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test Wno-unused-but-set-variable - Success
-- Performing Test Wno-deprecated-declarations
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test Wno-deprecated-declarations - Success
-- Looking for include file fcntl.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file unistd.h - found
-- Looking for include file stdint.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file stdint.h - found
-- Looking for include file inttypes.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/strtio.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/select.h - found
-- Performing Test HAVE_TM_GMTOFF
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for include file sys/eventfd.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/eventfd.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/timerfd.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/timerfd.h - not found
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: C:/Users/Ansu/Downloads/android-ndk-r8d/platforms/android-9/arch-
arm/usr/lib/libz.so (found version "1.2.3")
-- Finding required feature OpenSSL for cryptography (encryption, certificate va
lidation, hashing functions)
-- Found OpenSSL: C:/work/RAT_PATROL/FreeRDP-master/external/openssl/obj/local/a
rmeabi/libssl.a;C:/work/RAT_PATROL/FreeRDP-master/external/openssl/obj/local/arm
eabi/libcrypto.a (found version "0.9.8h")
-- Finding required feature OpenSLES for multimedia (OpenSLES audio / video)
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- Found OPENSLES: C:/Users/Ansu/Downloads/android-ndk-r8d/platforms/android-9/a
rch-arm/usr/include
-- Skipping disabled feature ALSA for sound (audio input, audio output and multi
media redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and mult
imedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)

-- Skipping disabled feature FFmpeg for multimedia (multimedia redirection, audi
o and video playback)
-- Skipping disabled feature Gstreamer for multimedia (multimedia redirection, a
udio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- FreeRDP GIT
-- Looking for pthread_tryjoin_np in pthread
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for pthread_tryjoin_np in pthread - not found
-- Adding dynamic channel client "audin": Audio Input Redirection Virtual Channe
l Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Exte
nsion
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extensio
n
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extens
ion
-- Adding device channel client "drive": Drive Redirection Virtual Channel Exten
sion
-- Adding dynamic channel client "echo": Echo Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extensio
n
-- Adding static channel client server "rdpdr": Device Redirection Virtual Chann
el Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Ex
tension
-- Adding Android client
-- Configuring done
-- Generating done
-- Build files have been written to: C:/work/RAT_PATROL/FreeRDP-master
/*****************************************************************************************/

Then I am runing the make commad

c:\Users\Ansu\Downloads\android-ndk-r8e\prebuilt\windows\bin\make.exe

And I am getting errors,check the below outputs

/***********************************************************************************************/
CMake Warning (dev) at CMakeFiles/2.8.12/CMakeSystem.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:23 (project)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/
CMakeDetermineSystem.cmake:93 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:43 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- FreeRDP GIT
STATUS,"ANDROID ADDED BY ANSUJIT"
-- Git Revision n/a
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate va
lidation, hashing functions)
-- Finding required feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multi
media redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and mult
imedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)

-- Skipping disabled feature FFmpeg for multimedia (multimedia redirection, audi
o and video playback)
-- Skipping disabled feature Gstreamer for multimedia (multimedia redirection, a
udio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- FreeRDP GIT
-- Adding dynamic channel client "audin": Audio Input Redirection Virtual Channe
l Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Exte
nsion
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extensio
n
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extens
ion
-- Adding device channel client "drive": Drive Redirection Virtual Channel Exten
sion
-- Adding dynamic channel client "echo": Echo Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extensio
n
-- Adding static channel client server "rdpdr": Device Redirection Virtual Chann
el Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Ex
tension
-- Adding Android client
-- Configuring done
-- Generating done
-- Build files have been written to: C:/work/RAT_PATROL/FreeRDP-master
Scanning dependencies of target winpr-wtsapi
[  0%] Building C object winpr/libwinpr/wtsapi/CMakeFiles/winpr-wtsapi.dir/wtsap
i.c.o
[  1%] Building C object winpr/libwinpr/wtsapi/CMakeFiles/winpr-wtsapi.dir/wtsrp
c_c.c.o
[  1%] Built target winpr-wtsapi
Scanning dependencies of target winpr-asn1
[  2%] Building C object winpr/libwinpr/asn1/CMakeFiles/winpr-asn1.dir/asn1.c.o
[  2%] Built target winpr-asn1
Scanning dependencies of target winpr-com
[  2%] Building C object winpr/libwinpr/com/CMakeFiles/winpr-com.dir/com.c.o
[  2%] Built target winpr-com
Scanning dependencies of target winpr-bcrypt
[  2%] Building C object winpr/libwinpr/bcrypt/CMakeFiles/winpr-bcrypt.dir/bcryp
t.c.o
[  2%] Built target winpr-bcrypt
Scanning dependencies of target winpr-credentials
[  3%] Building C object winpr/libwinpr/credentials/CMakeFiles/winpr-credentials
.dir/credentials.c.o
[  3%] Built target winpr-credentials
Scanning dependencies of target winpr-credui
[  3%] Building C object winpr/libwinpr/credui/CMakeFiles/winpr-credui.dir/credu
i.c.o
[  3%] Built target winpr-credui
Scanning dependencies of target winpr-crt
[  3%] Building C object winpr/libwinpr/crt/CMakeFiles/winpr-crt.dir/alignment.c
.o
[  4%] Building C object winpr/libwinpr/crt/CMakeFiles/winpr-crt.dir/conversion.
c.o
[  4%] Building C object winpr/libwinpr/crt/CMakeFiles/winpr-crt.dir/buffer.c.o
[  4%] Building C object winpr/libwinpr/crt/CMakeFiles/winpr-crt.dir/memory.c.o
[  5%] Building C object winpr/libwinpr/crt/CMakeFiles/winpr-crt.dir/string.c.o
[  5%] Building C object winpr/libwinpr/crt/CMakeFiles/winpr-crt.dir/unicode.c.o

[  6%] Built target winpr-crt
Scanning dependencies of target winpr-crypto
[  6%] Building C object winpr/libwinpr/crypto/CMakeFiles/winpr-crypto.dir/crypt
o.c.o
[  6%] Building C object winpr/libwinpr/crypto/CMakeFiles/winpr-crypto.dir/cert.
c.o
[  6%] Built target winpr-crypto
Scanning dependencies of target winpr-dsparse
[  7%] Building C object winpr/libwinpr/dsparse/CMakeFiles/winpr-dsparse.dir/dsp
arse.c.o
[  7%] Built target winpr-dsparse
Scanning dependencies of target winpr-environment
[  7%] Building C object winpr/libwinpr/environment/CMakeFiles/winpr-environment
.dir/environment.c.o
C:\work\RAT_PATROL\FreeRDP-master\winpr\libwinpr\environment\environment.c: In f
unction 'GetCurrentDirectoryA':
C:\work\RAT_PATROL\FreeRDP-master\winpr\libwinpr\environment\environment.c:39:2:
 warning: implicit declaration of function 'getcwd' [-Wimplicit-function-declara
tion]
C:\work\RAT_PATROL\FreeRDP-master\winpr\libwinpr\environment\environment.c:39:6:
 warning: assignment makes pointer from integer without a cast [enabled by defau
lt]
[  7%] Built target winpr-environment
Scanning dependencies of target winpr-error
[  7%] Building C object winpr/libwinpr/error/CMakeFiles/winpr-error.dir/error.c
.o
[  7%] Built target winpr-error
Scanning dependencies of target winpr-file
[  8%] Building C object winpr/libwinpr/file/CMakeFiles/winpr-file.dir/file.c.o
C:\work\RAT_PATROL\FreeRDP-master\winpr\libwinpr\file\file.c: In function 'Creat
eFileA':
C:\work\RAT_PATROL\FreeRDP-master\winpr\libwinpr\file\file.c:187:21: error: stor
age size of 's' isn't known
C:\work\RAT_PATROL\FreeRDP-master\winpr\libwinpr\file\file.c:227:2: error: inval
id application of 'sizeof' to incomplete type 'struct sockaddr_un'
C:\work\RAT_PATROL\FreeRDP-master\winpr\libwinpr\file\file.c:231:71: error: inva
lid application of 'sizeof' to incomplete type 'struct sockaddr_un'
C:\work\RAT_PATROL\FreeRDP-master\winpr\libwinpr\file\file.c:187:21: warning: un
used variable 's' [-Wunused-variable]
make[2]: **\* [winpr/libwinpr/file/CMakeFiles/winpr-file.dir/file.c.o] Error 1
make[1]: **\* [winpr/libwinpr/file/CMakeFiles/winpr-file.dir/all] Error 2
make: **\* [all] Error 2

C:\work\RAT_PATROL\FreeRDP-master>

/***********************************************************************************************/

Need Help ,kindly suggest 
Thanks in Andvance

**Comment by akallabeth** [comment]
Build scripts for android updated (although still no windows support)
Closing due to lack of interest.
