### ISSUE TITLE
pthread missing error while configuring freerdp for android on windows 7 environment 

### ISSUE THREAD

**Issue by Ansujit** [FreeRDP/FreeRDP#1564]
I am getting "-- Looking for include file pthread.h - not found" error while configure freerdp using cmake.
Below is my compile log ,kindly check and let me know the cause as soon as possible.

/**************************************************************************************************/

C:\work\RAT_PATROL\FreeRDP-master>cmake -G  "MinGW Makefiles" -DCMAKE_TOOLCHAIN_FILE=cmake\AndroidToolchain.cmake -DFREERDP_ANDROID_EXTERNAL_SSL_PATH="C:\work\RAT_PATROL\FreeRDP-master\external\openssl" -DCMAKE_MAKE_PROGRAM=c:\Users\Ansu\Downloads\android-ndk-r8e\prebuilt\windows\bin\make.exe

struct sockaddr_un {
 short sun_family;  /\* AF_UNIX _/
 char sun_path[108];  /_ path name (gag) */
};
C:\work\RAT_PATROL\FreeRDP-master>cmake -G  "MinGW Makefiles" -DCMAKE_TOOLCHAIN_
FILE=cmake\AndroidToolchain.cmake -DFREERDP_ANDROID_EXTERNAL_SSL_PATH="C:\work\R
AT_PATROL\FreeRDP-master\external\openssl" -DCMAKE_MAKE_PROGRAM=c:\Users\Ansu\Do
wnloads\android-ndk-r8e\prebuilt\windows\bin\make.exe
CMake Warning (dev) at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/
CMakeDetermineSystem.cmake:90 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:43 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- FreeRDP GIT
-- Git Revision n/a
-- Performing Test Wno-unused-result
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test Wno-unused-result - Failed
-- Performing Test Wno-unused-but-set-variable
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test Wno-unused-but-set-variable - Failed
-- Performing Test Wno-deprecated-declarations
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test Wno-deprecated-declarations - Failed
-- Looking for include file fcntl.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file fcntl.h - not found
-- Looking for include file unistd.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file unistd.h - not found
-- Looking for include file stdint.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file stdint.h - not found
-- Looking for include file inttypes.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file inttypes.h - not found
-- Looking for include file sys/modem.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/strtio.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file sys/select.h - not found
-- Performing Test HAVE_TM_GMTOFF
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test HAVE_TM_GMTOFF - Failed
-- Looking for include file pthread.h
CMake Warning (dev) at C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/2.8.12/CMake
System.cmake:6 (include):
  Syntax Warning in cmake code at

```
C:/work/RAT_PATROL/FreeRDP-master/cmake/AndroidToolchain.cmake:724:30
```

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  CMakeLists.txt:3 (PROJECT)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for include file pthread.h - not found
CMake Error at C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/FindPack
ageHandleStandardArgs.cmake:108 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/FindPackageHandleStan
dardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files (x86)/CMake 2.8/share/cmake-2.8/Modules/FindThreads.cmake:166
 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:304 (find_package)

-- Configuring incomplete, errors occurred!
See also "C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/CMakeOutput.log".
See also "C:/work/RAT_PATROL/FreeRDP-master/CMakeFiles/CMakeError.log".

C:\work\RAT_PATROL\FreeRDP-master>

/**************************************************************************************/

**Comment by akallabeth** [comment]
Nightly builds of master are fine.
Closing.
