### ISSUE TITLE
aFreeRDP keyboard not sending punctuation to the server

### ISSUE THREAD

**Issue by mershadies** [FreeRDP/FreeRDP#1568]
I have a problem that not all keyboard signs are sent.
using latest android version remoting an xbian

- ' " : ; , ? /

are not working

**Comment by glitchphan** [comment]
I have this problem typing into certain applications using the iOS FreeRDP connected into Windows systems. For example, I can type everything into Skype, but only alphanumeric characters into Pidgin. I can't type any punctuation or space. This issue exists with many other RDP clients (maybe they use this code?), but not all.
