### ISSUE TITLE
Major graphical artifacts (solved)

### ISSUE THREAD

**Issue by PenelopeFudd** [FreeRDP/FreeRDP#1573]
Hi...

In connecting to a real windows XP machine,I was getting horrible artifacts, such as the start menu was transparent, and login/disconnect dialog boxes were partially covered by a blue (desktop) rectangle.  I tried every command line option in the man page, to no avail.

This command line failed:
  xfreerdp -g 1920x1100+1920+0 -u myusername -d office -g 1677x900 1.2.3.4
This command line made the problems go away:
  xfreerdp -g 1920x1100+1920+0 -u myusername -d office  1.2.3.4

Apparently specifying the geometry twice messes things up, reproducibly!

Thanks for a great program!

**Comment by bmiklautz** [comment]
The issue shouldn't happen anymore with the new command line parser (changed syntax!). Re-open or create a new issue is the problem still exists.
