### ISSUE TITLE
wfreerdp not work with RemoteApp

### ISSUE THREAD

**Issue by Sleeper32** [FreeRDP/FreeRDP#1579]
When running: wfreerdp.exe /u:myuser /d:mydomain /p:mypass /app:"C:\Windows\system32\notepad.exe" /v:myserver
or
wfreerdp.exe /u:myuser /d:mydomain /p:mypass /app:"||notepad.exe" /v:myserver
, displayed remote desktop without icons, but application not running, and view not same mstsc. MSTSC display only app window, but WFREERDP display fullsize remote desktop.
How solve throuble?

**Comment by ferasd** [comment]
Hi , 
does Remoteapp works with wfreerdp.exe ?

i have tried it with stable-1.1 branch and master , for both the behavior is the same .
i am getting a black screen that disconnects after a while .

i am trying to connect from win8 to win server 2012 . 
and this is the command i am running :

wfreerdp.exe /u:user /p:pass /app:"||calc" /v:server


any advice , help ??

thanks

**Comment by cmbaker82** [comment]
Looks related to https://github.com/FreeRDP/FreeRDP/issues/4074

I get the black screen if the name of the remote app does not match what the server is expecting
