### ISSUE TITLE
something error while using photoshop

### ISSUE THREAD

**Issue by cschenlu** [FreeRDP/FreeRDP#1586]
Hello,I've met a strange problem when I use freerdp and cannot figure it out. The Problem is that when I drag mouse to choose a rectangle region in photoshop, some lines are left on the screen(see the following picture). Is it because there is something wrong with the rdp’s settings, or it is infected by gdi drawing? Longing for your reply. Many thanks!

![1](https://f.cloud.github.com/assets/2970527/1519552/bc1896ec-4b63-11e3-8db0-d7e8c4db0f04.png)

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
