### ISSUE TITLE
Linking fails on Solaris 11.2 – undefined symbol: futimes

### ISSUE THREAD

**Issue by Mr-Tao** [FreeRDP/FreeRDP#1617]
futimes() is missing on Solaris.

> ⋮
> [ 95%] Built target freerdp-client
> [ 99%] Built target xfreerdp-client
> Linking C executable ../xfreerdp
> Undefined                       first referenced
>  symbol                             in file
> futimes                             ../../common/libfreerdp-client.so.1.1.0
> ld: fatal: symbol referencing errors
> collect2: error: ld returned 1 exit status
> make[2]: **\* [client/X11/xfreerdp] Error 1
> make[1]: **\* [client/X11/cli/CMakeFiles/xfreerdp-cli.dir/all] Error 2
> make: **\* [all] Error 2

**Comment by akallabeth** [comment]
function no longer used by FreeRDP.
