### ISSUE TITLE
rdp window become sticky in fullscreen mode

### ISSUE THREAD

**Issue by sandeepkapase** [FreeRDP/FreeRDP#1623]
# Problem Description:

In fullscreen mode xfreerdp window becomes sticky and becomes visible on all work-space. Expected behavior is xfreerdp window (in either mode) should be visible on only one workspace.

I have 2 monitors and 10 workspaces. When I start xfreerdp to connect to my windows 7 machine in fullscreen mode, one monitor (display) from each workspace get occupied by xfreerdp windows.
When I exit fullscreen mode, xfreerdp become visible only on one workspace which is fine. When I enter fullscreen mode it again becomes visible on all workspace(sticky).

Also, in fullscreen mode I am not able get xfreerdp window in windows listing
i.e. wmctrl -l
When I exit fullscreen mode xfreerdp window get listed in "wmctrl -l"

This bug need to be verified.
# Following are setup/configuration details(information may be useful):

source base : commit :  [75b919a915c87430db04bf3dc97fd8da054b87af]
# cat /etc/issue

Ubuntu 13.10 \n \l

bash-4.2$ cat /etc/X11/default-display-manager 
/usr/sbin/lightdm

bash-4.2$ env | grep -i DESK
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
DESKTOP_SESSION=ubuntu
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
XDG_CURRENT_DESKTOP=Unity

bash-4.2$ xrandr --query
Screen 0: minimum 320 x 200, current 3286 x 1080, maximum 32767 x 32767
LVDS1 connected 1366x768+0+0 (normal left inverted right x axis y axis) 310mm x 174mm
   1366x768       60.0_+
   1360x768       59.8     60.0  
   1024x768       60.0  
   800x600        60.3     56.2  
   640x480        59.9  
VGA1 connected primary 1920x1080+1366+0 (normal left inverted right x axis y axis) 477mm x 268mm
   1920x1080      60.0_+
   1280x1024      75.0     60.0  
   1152x864       75.0  
   1024x768       75.1     60.0  
   800x600        75.0     60.3  
   640x480        75.0     60.0  
   720x400        70.1  
HDMI1 disconnected (normal left inverted right x axis y axis)
DP1 disconnected (normal left inverted right x axis y axis)
HDMI2 disconnected (normal left inverted right x axis y axis)
HDMI3 disconnected (normal left inverted right x axis y axis)
DP2 disconnected (normal left inverted right x axis y axis)
DP3 disconnected (normal left inverted right x axis y axis)
VIRTUAL1 disconnected (normal left inverted right x axis y axis)

bash-4.2$ lspci | grep VGA ;
00:02.0 VGA compatible controller: Intel Corporation 3rd Gen Core processor Graphics Controller (rev 09)

bash-4.2$ glxinfo | grep -i "vendor|rendering" 
direct rendering: Yes
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
OpenGL vendor string: Intel Open Source Technology Center

bash-4.2$ grep LoadModule /var/log/Xorg.0.log
[    26.429](II) LoadModule: "dri2"
[    26.429](II) LoadModule: "glamoregl"
[    28.156](II) LoadModule: "glx"
[    28.156](II) LoadModule: "intel"
[    28.308](II) LoadModule: "vesa"
[    28.308](II) LoadModule: "modesetting"
[    28.309](II) LoadModule: "fbdev"
[    28.309](II) LoadModule: "fbdevhw"
[    28.310](II) LoadModule: "dri2"
[    28.909](II) LoadModule: "evdev"
[    28.930](II) LoadModule: "synaptics"

bash-4.2$ sudo find /dev -group video ;
[sudo] password for sandeep: 
/dev/video0
/dev/fb0
/dev/dri/card0
/dev/dri/controlD64

bash-4.2$ cat /proc/cmdline
BOOT_IMAGE=/boot/vmlinuz-3.11.0-13-generic root=UUID=e607aa62-de72-4b3a-90a8-5494db6d99e2 ro quiet splash vt.handoff=7

bash-4.2$ sudo lshw -C video
  *-display  
       description: VGA compatible controller
       product: 3rd Gen Core processor Graphics Controller
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 09
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:45 memory:f0000000-f03fffff memory:e0000000-efffffff ioport:5000(size=64)

**Comment by caramorsimon** [comment]
"Stickiness" is resolved with new Gnome3 release.
- ubuntu 16.04LTS xenial
- gnome 3.20 
- dual monitor setup

With the prior version the rdp window was visible on its monitor after switching workspaces
I imagine for anyone with a single monitor this made workspaces & fullscreen rdp unusable - the workaround is to leave fullscreen mode & switch workspaces, switching freerdp back to fullscreen when desired again.

Following the 3.20 upgrade the rdp fullscreen window remains within the assigned workspace & the monitor is cleared for other purposes after switching to a different workspace.

NB - the preview thumbnail for the workspace switcher doesn't appear when in freerdp is in full screen mode , although it appears as soon as fullscreen is changed for windowed mode.

There is an additional difficulty in gnome3.18 which is that the workspace preview is not displayed for secondary monitors. Gnome 3.20 has an extension available (Multi Monitors Add On) which shows a separate workspace preview on each monitor, containing the workspace windows assigned to it.

**Comment by caramorsimon** [comment]
After a restart/update I now see that thumbnails *are* working for multimon with freerdp in fullscreen mode [I may have inadvertently started a bundled 1.1.0 in error]
It treats the whole remote desktop (all monitors) as a single canvas & scales this to produce the thumbnail,  which is then shown in both the workspace overview & the desktop overview on whichever monitor xfreerdp has set as the primary one for the session.

**Comment by akallabeth** [comment]
Ok, assuming resolved?
Closing.
