### ISSUE TITLE
protocol security negotiation failure

### ISSUE THREAD

**Issue by alizafzali** [FreeRDP/FreeRDP#1639]
Hi

i just tried to connecting to my Hyper-V server with this command (From my Ubuntu and the FreeRDP version is latest one):

xfreerdp /cert-ignore –no-nego /u:administrator /p:123 /v:192.168.172.129 /port:2179 /vmconnect:8021D293-FA6F-4CB5-AFD2-2499936D0949

but i got this error message :

transport_connect: getaddrinfo (Name or service not known)
Error: protocol security negotiation failure

**Comment by adamziaja** [comment]
Brew still use 1.0.2 version in 2017...
```xfreerdp +clipboard /size:1280x1024 /u:Administrator /p:'test' /v:10.1.2.3```
How can I write this in old style command? @bmiklautz

**Comment by bmiklautz** [comment]
@adamziaja give --HEAD a try with brew.
