### ISSUE TITLE
Mouse is not working in rdp window ( In XP ) and Rightclick in ( Win7 )

### ISSUE THREAD

**Issue by alizafzali** [FreeRDP/FreeRDP#1641]
Hi

im connecting to my vm using this command : 

xfreerdp /cert-ignore /u:administrator /p:123 /vmconnect:8021D293-FA6F-4CB5-AFD2-2499936D0949 /v:192.168.172.129

every thing is alright and the keyboard is working but
the mouse is not working at all !

**Comment by akallabeth** [comment]
Closing as fixed. Reopen if still an issue.
