### ISSUE TITLE
Problems with mstsc inside FreeRDP session

### ISSUE THREAD

**Issue by diger74** [FreeRDP/FreeRDP#1642]
I faced with a pretty strange problem.

Here is a description of test case reqs:
- FreeRDP (for Linux, latest from 1.1-stable branch)
- connecting to Windows Server 2003R2 via FreeRDP
- running mstsc inside FreeRDP session and trying to connect to any other Windows machine (I tried Win7, Server 2003R2 and Win8)
- mstsc freezes at welcome screen and not responding at all, it only can be killed from task manager
- and there is no such problem with nested mstsc's from Windows

I captured a little video describing this process.
You can download this video from here: https://www.dropbox.com/s/o0z4ixqh317vwlj/freerdp.rar

**Comment by akallabeth** [comment]
Closing due to being ancient.
If still an issue feel free to reopen.
