### ISSUE TITLE
mouse can not redirect in ubuntu 

### ISSUE THREAD

**Issue by zhaohb** [FreeRDP/FreeRDP#1644]
When I use that command ：
sudo xfreerdp /sound:sys:alsa /microphone:sys:alsa /multimedia:decoder:gstreamer  /usb:001:005,dev:192f:0916 /rfx /f /bpp:32 /network:auto /cert-ignore -window-drag -sec-tls -sec-nla  /u：xx  /p:xx /v:xx 
to connect the RDP8.0 ,and use /usb:id,dev: to redirect the mouse ,I found that the mouse can not redirect successful ,but I can found the device in the remote desktop.
and I also test webcam , it was good

**Comment by akallabeth** [comment]
Closing, reopen if still an issue.
