### ISSUE TITLE
Keyboard Redirection Issue In Fullscreen With Dual Monitors

### ISSUE THREAD

**Issue by absolutelyNoWarranty** [FreeRDP/FreeRDP#1645]
Local - Ubuntu 13.04, Remote - Windows 8
Fullscreen running in one monitor, local desktop in another.

In fullscreen mode the mouse can still switch seamlessly between the fullscreened remote desktop (first monitor) and my local desktop (second monitor) but the keyboard cannot. As soon as I switch focus to the remote desktop the keyboard will be stuck there, and I have to click on one local window then click on a second local window. In the second local window, the keyboard will be back to normal. That is, my mouse can switch focus but the keyboard does not follow until I jump around a bit.

**Comment by akallabeth** [comment]
Ungrab key combo has been added.
