### ISSUE TITLE
client/X11 - wrong colors with 30 bit depth 

### ISSUE THREAD

**Issue by fidoman** [FreeRDP/FreeRDP#1646]
When client is run on X11 screen with 30-bit color depth, colors of target system are displayed incorrectly.

This is FreeRDP version 1.2.0-beta1 (git 1.1.0-beta+2013071101-972-g72f3)
X.Org X Server 1.14.5
Release Date: 2013-12-12

**Comment by akallabeth** [comment]
Color conversion has been rewritten.
