### ISSUE TITLE
Multimon with 2 Monitors of different sizes

### ISSUE THREAD

**Issue by anchapin** [FreeRDP/FreeRDP#1651]
I am relatively new to GitHub, FreeRDP, and Linux. I spent a while today figuring out how to make FreeRDP work (currently using version 1.2.0-beta1) on Ubuntu 13.10 connecting to Windows Server 2008 R2 Enterprise and my problem is that when I use /multimon with my laptop (1366 x 768) and external monitor (1920 x 1080) I get what appears to be one effective monitor of size 3286 x 1080. This means that when I maximize a window it spans both physical monitors and when I open programs/windows on the laptop side the top portion goes off the screen.

I have tried the following commands (note that I searched through the issues to see if I could find a solution and so far nothing seems to work):

```
xfreerdp /multimon /f -wallpaper -themes +fonts +clipboard +compression /d:xxx "/u:xxxx xxx" /p:xxxxxx /v:xxxxxxxxxxxxxx
```

```
xfreerdp /multimon /workarea -wallpaper -themes +fonts +clipboard +compression /d:xxx "/u:xxxx xxx" /p:xxxxxx /v:xxxxxxxxxxxxxx
```

Any help is appreciated thanks.

**Comment by Daniyal-Javani** [comment]
Is there any solutions for this issue currently?

**Comment by akallabeth** [comment]
@Daniyal-Javani what issue do you have? I´m using current nightly and I can use multimon with different resolutions quite fine (it even automatically adjusts to resolution changes)

**Comment by Daniyal-Javani** [comment]
Thank for your attention.
I miss some part of the screen in the smaller monitor like the start menu button on Windows.
With this paramaters:
`xfreerdp /multimon /u:danial.javani /p:XLmWexGKbuxYuNX /v:192.168.254.1:23020 /smart-sizing /span`
and this version:
`Installed: 2.2.0+git202007201338-0+remmina202007310643.rd2ba84a.dfabe85c~ubuntu20.04.1`
![image](https://user-images.githubusercontent.com/8044163/106144186-18d5a300-6189-11eb-9529-bb61a705011f.png)

**Comment by Daniyal-Javani** [comment]
Thank for your attention.
I miss some part of the screen in the smaller monitor like the start menu button on Windows.
With this paramaters:
xfreerdp /multimon /u:danial.javani /******** /v:********:***** /smart-sizing /span
and this version:
Installed: 2.2.0+git202007201338-0+remmina202007310643.rd2ba84a.dfabe85c~ubuntu20.04.1

![image](https://user-images.githubusercontent.com/8044163/106144847-060f9e00-618a-11eb-84a0-86562b9184f9.png)

**Comment by akallabeth** [comment]
I´d start without special case arguments like `/smart-sizing /span`, they are both more useless and might cause harm for your use case.
on the other hand, I´d add `/network:auto /gfx:avc444 /rfx` so that modern RDP can be used.
Also give the nightly builds a try (but be careful with updating them, they might break)
