### ISSUE TITLE
CMake configure errors when used in another project

### ISSUE THREAD

**Issue by jhakonen** [FreeRDP/FreeRDP#1653]
I'm using FreeRDP library in another project and include the FreeRDP into it using the cmake config files included in prefix/cmake/FreeRDP. In Windows 7, using VS2010 Pro I've configured, build and installed FreeRDP like this:

```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX:PATH=C:/FreeRDP/release -G "NMake Makefiles" .
```

I've also applied a pull request (https://github.com/FreeRDP/FreeRDP/pull/1565) which fixes some build errors.

When I try to include FreeRDP in my project with "find_package(WinPR)" and "find_package(FreeRDP)" and configuring with cmake:

```
cmake -DFreeRDP_DIR=C:\FreeRDP\release\cmake\FreeRDP -DWinPR_DIR=C:\FreeRDP\release\cmake\WinPR
```

I get following error:

```
CMake Error at C:/FreeRDP/release/cmake/WinPR/WinPRConfig.cmake:12 (message):
  File or directory C:/FreeRDP/include referenced by variable
  WinPR_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  C:/FreeRDP/release/cmake/WinPR/WinPRConfig.cmake:33 (set_and_check)
  src/CMakeLists.txt:12 (find_package)
```

The error occurs because in C:\FreeRDP\release\cmake\WinPR\WinPRConfig.cmake, on line 7 a relative path in PACKAGE_PREFIX_DIR variable is incorrectly defined. Defined like this:

```
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
```

But, it should be:

```
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)
```

I can fix this if in FreeRDP's root CMakeLists.txt I change on line 461:

```
set(CMAKE_INSTALL_LIBDIR ".")
```

To:

```
set(CMAKE_INSTALL_LIBDIR ${CMAKE_INSTALL_PREFIX})
```

This, however, has a side effect that paths in FreeRDPTargets-relwithdebinfo.cmake become absolute paths instead of relative, e.g, originally:

```
IMPORTED_IMPLIB_RELWITHDEBINFO "${_IMPORT_PREFIX}/./winpr-asn1.lib"
```

Becomes:

```
IMPORTED_IMPLIB_RELWITHDEBINFO "C:/FreeRDP/release/winpr-asn1.lib"
```

It doesn't seem to matter, but I guess if I were to move the installed files somewhere else the cmake config would not work anymore?

Next cmake error:

```
CMake Error at C:/FreeRDP/release/cmake/WinPR/WinPRTargets.cmake:160 (message):
  The imported target "winpr-sspicli" references the file

     "C:/FreeRDP/release/winpr-sspicli.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/FreeRDP/release/cmake/WinPR/WinPRTargets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/FreeRDP/release/cmake/WinPR/WinPRConfig.cmake:35 (include)
  src/CMakeLists.txt:12 (find_package)
```

The winpr-sspicli.lib is referenced in WinPRTargets-relwithdebinfo.cmake:

```
IMPORTED_IMPLIB_RELWITHDEBINFO "C:/FreeRDP/release/winpr-sspicli.lib"
```

But, there is no such file in C:/FreeRDP/release.
I'm guessing that is because the sspicli doesn't export any symbols, so there is no lib-file built for that either?
The reference is added to the targets file in winpr\libwinpr\sspicli\CMakeLists.txt, line 33:

```
install(TARGETS ${MODULE_NAME} DESTINATION ${CMAKE_INSTALL_LIBDIR} EXPORT WinPRTargets)
```

If I remove the "EXPORT WinPRTargets" part, then the cmake error goes away. No more reference to the non-existing lib-file.
This same error occurs for timezone, winhttp and winsock projects as well. Removing the EXPORT part fixes the errors in all cases.

Next cmake error:

```
CMake Warning at src/CMakeLists.txt:12 (find_package):
  Found package configuration file:

    C:/FreeRDP/release/cmake/WinPR/WinPRConfig.cmake

  but it set WinPR_FOUND to FALSE so package "WinPR" is considered to be NOT
  FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  freerdp-client freerdp-core freerdp-gdi freerdp-codec freerdp-primitives
  freerdp-utils
```

So WinPR fails to load because it depends of FreeRDP's libraries? Shouldn't FreeRDP depend of WinPR and not the other way around?
This dependency seems to occur because WinPRTargets-relwithdebinfo.cmake has import target for "wfreerdp-client" library.
In client\Windows\CMakeLists.txt on line 66 install is configured like this:

```
install(TARGETS ${MODULE_NAME} DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT libraries EXPORT WinPRTargets)
```

But surely it should be?

```
install(TARGETS ${MODULE_NAME} DESTINATION ${CMAKE_INSTALL_LIBDIR} COMPONENT libraries EXPORT FreeRDPTargets)
```

With that change there's no more cmake errors with my project.

Here's a forked branch with all the changes applied: https://github.com/sailfish-sdk/FreeRDP/tree/build-fixes.
Here's the project which uses FreeRDP: https://github.com/sailfish-sdk/RemoteDisplay

**Comment by akallabeth** [comment]
CMake configuration files have been cleaned up.
Reopen if this is still an issue.
