### ISSUE TITLE
/shell and ,/app not working with server 2008

### ISSUE THREAD

**Issue by kkeybbs** [FreeRDP/FreeRDP#1669]
ms-rdc+ /shell with server 2003 - working
wfreerdp + /shell with server 2003 - working
ms-rdc+ /shell with server 2008 - not working
wfreerdp + /shell with server 2008 - not working

ms-rdc+ remote app with server 2008 - working
wfreerdp + remote  app with server 2008 - not working

So /shell works well on server 2003, but wfreerdp doesn't work with shell or rempte app to connect to server 2008.

So how could wfreerdp start a program when connected to server 2008?

**Comment by akallabeth** [comment]
Tried with #4322 RAILS working
