### ISSUE TITLE
Build FreeRDP error

### ISSUE THREAD

**Issue by magicdmer** [FreeRDP/FreeRDP#1692]
I use cmake 2.8.12.2 to build the wfreerdp-server in windows 7, but it  prompts ("Unknown CMake command "set_complex_link_libraries".) why ?

Dose remoteapp need wfreerdp-server? i use wfreerdp client by follow command to link windows server 2012:
wfreerdp /u:user /p:password  /app:"||calc"  /v:ip address  
or
wfreerdp /u:user /p:password  /app:"c:\windows\system32\notepad.exe"   /v:ip address  
but the remote windows is dark and the app dosen't run....

**Comment by YangLi20** [comment]
I also met the same problem, you have a solution,my cmake version is 3.3.2,thank you

**Comment by magicdmer** [comment]
I don't know ,I didn't build wfreerdp-server any more,  I only build the wfreerdp client.  you can change your cmake's version and test it

**Comment by YangLi20** [comment]
i change my cmake version is 3.3.2 and build it ,but it also error , the reason is  ''Error in configuration process, project files may be invalid'',thank you
