### ISSUE TITLE
bug and soulution for photoshop

### ISSUE THREAD

**Issue by chumingchen** [FreeRDP/FreeRDP#1699]
Problem: 
　　　photoshop display not right when enlarging the selection region.

Environment:
Remote pc : 32bit win7
Client pc : linux and android
Test software : photoshop 7.0 and photoshop CS6
Test freeRDB version: FreeRDP-1.1.0-beta-2013071101

Solution: as you can see at below, the solution is come from the Patblt API in RealOS.

Detail:

![0](https://f.cloud.github.com/assets/6309406/2254975/7a5ca034-9dea-11e3-93b0-6a7e9fad526e.jpg)

Photoshop 7.0 also has the same problem, but not so serious. Here just take the screenshot of Photoshop CS6 .

As the picture, the problem is lines are remained, and the animation of frame lines is irregular when enlarging the selection region.

![1](https://f.cloud.github.com/assets/6309406/2254959/50e316a2-9dea-11e3-9951-61ceb1e1ab08.jpg)

![2](https://f.cloud.github.com/assets/6309406/2254961/5a9ca58c-9dea-11e3-891d-f7df18066238.jpg)

How to fix this bug?
Debudding is hardly for me, but modify code is easy.

1、/freerdp/include/freerdp/gdi/gdi.h
![11](https://f.cloud.github.com/assets/6309406/2254992/c901e302-9dea-11e3-967a-f9f0a7153c3a.jpg)

2、/freerdp/libfreerdp/gdi/gdi.c
Function: gdi_patblt
……
![22](https://f.cloud.github.com/assets/6309406/2254993/ce9a41a6-9dea-11e3-8174-c50a9fa0003f.jpg)

3、/freerdp/libfreerdp/gdi/32bpp.c
Function ：BitBlt_PATCOPY_32bpp
![33](https://f.cloud.github.com/assets/6309406/2255002/d539d1d4-9dea-11e3-83ce-d48bf637ef50.jpg)

4、/freerdp/libfreerdp/gdi/32bpp.c
Function ：BitBlt_PATINVERT_32bpp
The same as BitBlt_PATCOPY_32bpp

5、of course , 8bpp.c and 16bpp.c should also be modified.

The animation of frame lines is fixed, and the remained lines are improved.
![1](https://f.cloud.github.com/assets/6309406/2255020/1c1ccbec-9deb-11e3-8eb1-385acb8c22b7.jpg)

When background is a colorful picture and drag quickly to enlarge selection region, there also has lines remained. 
![2](https://f.cloud.github.com/assets/6309406/2255022/21db6214-9deb-11e3-9452-5acdc9d04e0e.png)

I have tested the version of FreeRDP-1.1.0-beta-2013071101 by the windows client, it also has the same problem. And this is the new bug that I am looking for help...

![3](https://f.cloud.github.com/assets/6309406/2255027/40389cc2-9deb-11e3-96b8-f6c03dea6161.png)

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
