### ISSUE TITLE
TS Gateway behind F5 LTM

### ISSUE THREAD

**Issue by kchch** [FreeRDP/FreeRDP#1723]
Hello. I'm really excited about the TS gateway support, but I'm experiencing a peculiar issue. We have a TS gateway server -- call it rdpgw -- and we have configured a virtual server on an F5 LTM to stand in front of it -- call the virtual server rdpproxy.

Windows' native RDP client can use rdpproxy as a gateway with no apparent problems, but xfreerdp cannot, it can only use rdpgw. I can set rdpproxy in my hosts file to resolve to rdpgw's IP, and I get the error. However, setting rdpgw to resolve to rdpproxy's IP address also gets the error, so if it's a hostname thing I'm not able to fake it out that way.

> $ xfreerdp /cert-ignore /g:rdpproxy:443 /gu:foo /gp:bar /v:someserver /u:foo2 /p:bar2
> connected to rdproxy:443
> connected to rdproxy:443
> Unexpected RTS PDU: Expected CONN/A3
> rts_connect error!
> rpc_connect failed!
> Error: protocol security negotiation or connection failure

Turning on with_debug_all, I see it stops here:

> Receiving PDU (length: 16, CallId: 0)
> 0000 00 14 03 10 00 00 00 1c 00 00 00 00 00 00 00 00 ................
> Unexpected RTS PDU: Expected CONN/A3
> rts_connect error!
> rpc_connect failed!
> DBG_NEGO nego_connect (/homedir/FreeRDP/libfreerdp/core/nego.c:142): Protocol Security Negotiation Failure
> Error: protocol security negotiation or connection failure

I've verified with tcpdump that that PDU packet is one of the last packets received. Afterwards, my side sends a couple of FINs to close the connection.

**Comment by akallabeth** [comment]
There has been a major re-factoring of gateway support witn `2.0.0-rc4` and following.
