### ISSUE TITLE
mingw cross compiling error 

### ISSUE THREAD

**Issue by jun0s** [FreeRDP/FreeRDP#1735]
[  6%] Building C object winpr/libwinpr/memory/CMakeFiles/winpr-memory.dir/memory.c.obj
In file included from /home/neo/FreeRDP/winpr/include/winpr/file.h:26:0,
                 from /home/neo/FreeRDP/winpr/include/winpr/memory.h:31,
                 from /home/neo/FreeRDP/winpr/libwinpr/memory/memory.c:26:
/home/neo/FreeRDP/winpr/include/winpr/nt.h:1298:2: error: redeclaración del enumerador ‘FileFullDirectoryInformation’
  FileFullDirectoryInformation
.
.
.
.
.
In file included from /home/neo/FreeRDP/winpr/include/winpr/nt.h:1287:0,
                 from /home/neo/FreeRDP/winpr/include/winpr/file.h:26,
                 from /home/neo/FreeRDP/winpr/include/winpr/memory.h:31,
                 from /home/neo/FreeRDP/winpr/libwinpr/memory/memory.c:26:
/usr/share/mingw-w64/include/winternl.h:249:5: nota: la definición previa de ‘FileShortNameInformation’ estaba aquí
     FileShortNameInformation = 40,
     ^
make[2]: **\* [winpr/libwinpr/memory/CMakeFiles/winpr-memory.dir/memory.c.obj] Error 1
make[1]: **\* [winpr/libwinpr/memory/CMakeFiles/winpr-memory.dir/all] Error 2
make: **\* [all] Error 2
neo@dbox:~/FreeRDP$ cmake -DCMAKE_TOOLCHAIN_FILE=cross-mingw32-linux.cmake

host debian migw32 cross compiler

**Comment by akallabeth** [comment]
We're not supporting mingw ourselves, but pull requests are welcome and will be merged.
