### ISSUE TITLE
Negotiation not working thru GW to 2003 server

### ISSUE THREAD

**Issue by dbungert** [FreeRDP/FreeRDP#1744]
Per #1710, negotiation appears to not be working when connecting thru a RD Gateway to a 2003R2 server.  That configuration should support both the RDP and TLS/SSL security layers.

**Comment by akallabeth** [comment]
Gateway support has been hugely improved with `2.0.0-rc4` and #5022 
Closing as no longer applicable.
Create a new issue if still a problem.
