### ISSUE TITLE
xfreerdp-server: double free or corruption

### ISSUE THREAD

**Issue by zunke1410** [FreeRDP/FreeRDP#1745]
Hi,
I just try the latest rdp version (server and client), git SHA1 Id: 037fb5e4ebe3234caabbdeaeb55bd2e51bff8906. 
Both server and client in a LAN network.
Server run on ubuntu  12.04 (precise) 32-bit( 3.5.0-23-generic), client (ubuntu  12.04 (precise) 32-bit, 3.8.0-29-generic) connect to server : ./xfreerdp /bpp:16 /rfx /u:username /p:password /v:192.168.1.119 /max-fast-path-size:9999999 /size:800x600 /rfx-mode:i /gdi:sw /jpeg /codec-cache:rfx.
Client display a black window. On server side i got these messages :

./xfreerdp-server 
Listening on 0.0.0.0 port 3389.
bind: Address already in use
We've got a client 192.168.1.100
      \* [0] 1366x768    +0+0
display: 0xb5d3e6a8 root_window: 0xc4 width: 1366 height: 768 depth: 24
Using X Shared Memory Extension (XShm)
DBG_NEGO nego_process_negotiation_request (libfreerdp/core/nego.c:749): RDP_NEG_REQ
DBG_NEGO nego_process_negotiation_request (libfreerdp/core/nego.c:755): requested_protocols: 3
Client Security: NLA:1 TLS:1 RDP:0
Server Security: NLA:1 TLS:1 RDP:1
Negotiated Security: NLA:1 TLS:0 RDP:0
TLS connection accepted
Accepted client: user-virtual-ma
Accepted channels:
Client 192.168.1.100 is activated
Client requested desktop: 800x600x32
Client sent a synchronize event (flags:0x2)
Client sent a synchronize event (flags:0x2)
Client sent a synchronize event (flags:0x2)
Client sent a synchronize event (flags:0x2)
Client sent a synchronize event (flags:0x2)
**\* glibc detected **\* ./xfreerdp-server: double free or corruption (fasttop): 0xb25009b0 ***
======= Backtrace: =========
/lib/i386-linux-gnu/libc.so.6(+0x75ee2)[0xb7628ee2]
/home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/pool/libwinpr-pool.so.1.1(CloseThreadpoolWork+0x1b)[0xb70e584b]
/home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/codec/libfreerdp-codec.so.1.2(rfx_encode_message+0x7c7)[0xb73cbe97]
/home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/codec/libfreerdp-codec.so.1.2(rfx_compose_message+0x56)[0xb73cc836]
/home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/server/X11/libxfreerdp-server.so.1.2(xf_update_encode+0x21e)[0xb778729e]
/home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/server/X11/libxfreerdp-server.so.1.2(xf_update_thread+0x14c)[0xb778743c]
/lib/i386-linux-gnu/libpthread.so.0(+0x6d4c)[0xb7188d4c]
/lib/i386-linux-gnu/libc.so.6(clone+0x5e)[0xb76a2bae]
======= Memory map: ========
08048000-0804a000 r-xp 00000000 08:02 2378903    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/server/X11/xfreerdp-server
0804a000-0804b000 r--p 00001000 08:02 2378903    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/server/X11/xfreerdp-server
0804b000-0804c000 rw-p 00002000 08:02 2378903    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/server/X11/xfreerdp-server
087b6000-087fb000 rw-p 00000000 00:00 0          [heap]
b1d00000-b1dff000 rw-p 00000000 00:00 0 
b1dff000-b1e00000 ---p 00000000 00:00 0 
b1e00000-b1e67000 rw-p 00000000 00:00 0 
b1e67000-b1f00000 ---p 00000000 00:00 0 
b1f00000-b1f55000 rw-p 00000000 00:00 0 
b1f55000-b2000000 ---p 00000000 00:00 0 
b2000000-b20fe000 rw-p 00000000 00:00 0 
b20fe000-b2100000 ---p 00000000 00:00 0 
b2100000-b214f000 rw-p 00000000 00:00 0 
b214f000-b2200000 ---p 00000000 00:00 0 
b2200000-b2237000 rw-p 00000000 00:00 0 
b2237000-b2300000 ---p 00000000 00:00 0 
b2300000-b23ff000 rw-p 00000000 00:00 0 
b23ff000-b2400000 ---p 00000000 00:00 0 
b2400000-b24fe000 rw-p 00000000 00:00 0 
b24fe000-b2500000 ---p 00000000 00:00 0 
b2500000-b2521000 rw-p 00000000 00:00 0 
b2521000-b2600000 ---p 00000000 00:00 0 
b26ff000-b2700000 ---p 00000000 00:00 0 
b2700000-b2f00000 rw-p 00000000 00:00 0          [stack:32162]
b2f00000-b3000000 rw-p 00000000 00:00 0 
b30fa000-b30fb000 ---p 00000000 00:00 0 
b30fb000-b38fb000 rw-p 00000000 00:00 0          [stack:32161]
b38fb000-b38fc000 ---p 00000000 00:00 0 
b38fc000-b40fc000 rw-p 00000000 00:00 0          [stack:32160]
b40fc000-b40fd000 ---p 00000000 00:00 0 
b40fd000-b48fd000 rw-p 00000000 00:00 0          [stack:32159]
b48fd000-b48fe000 ---p 00000000 00:00 0 
b48fe000-b50fe000 rw-p 00000000 00:00 0          [stack:32158]
b50fe000-b50ff000 ---p 00000000 00:00 0 
b50ff000-b58ff000 rw-p 00000000 00:00 0          [stack:32157]
b58ff000-b5d00000 rw-s 00000000 00:04 16678928   /SYSV00000000 (deleted)
b5d00000-b5d90000 rw-p 00000000 00:00 0 
b5d90000-b5e00000 ---p 00000000 00:00 0 
b5e05000-b5e21000 r-xp 00000000 08:02 525141     /lib/i386-linux-gnu/libgcc_s.so.1
b5e21000-b5e22000 r--p 0001b000 08:02 525141     /lib/i386-linux-gnu/libgcc_s.so.1
b5e22000-b5e23000 rw-p 0001c000 08:02 525141     /lib/i386-linux-gnu/libgcc_s.so.1
b5e3a000-b5eff000 rw-p 00000000 00:00 0 
b5eff000-b5f00000 ---p 00000000 00:00 0 
b5f00000-b6700000 rw-p 00000000 00:00 0          [stack:32156]
b6700000-b6721000 rw-p 00000000 00:00 0 
b6721000-b6800000 ---p 00000000 00:00 0 
b680a000-b680b000 ---p 00000000 00:00 0 
b680b000-b700e000 rw-p 00000000 00:00 0          [stack:32155]
b700e000-b7010000 r-xp 00000000 08:02 3450643    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/nt/libwinpr-nt.so.1.1.0
b7010000-b7011000 r--p 00001000 08:02 3450643    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/nt/libwinpr-nt.so.1.1.0
b7011000-b7012000 rw-p 00002000 08:02 3450643    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/nt/libwinpr-nt.so.1.1.0
b7012000-b7063000 r-xp 00000000 08:02 524293     /lib/i386-linux-gnu/libssl.so.1.0.0
b7063000-b7065000 r--p 00050000 08:02 524293     /lib/i386-linux-gnu/libssl.so.1.0.0
b7065000-b7069000 rw-p 00052000 08:02 524293     /lib/i386-linux-gnu/libssl.so.1.0.0
b7069000-b706a000 rw-p 00000000 00:00 0 
b706a000-b706f000 r-xp 00000000 08:02 2101710    /usr/lib/i386-linux-gnu/libXdmcp.so.6.0.0
b706f000-b7070000 r--p 00004000 08:02 2101710    /usr/lib/i386-linux-gnu/libXdmcp.so.6.0.0
b7070000-b7071000 rw-p 00005000 08:02 2101710    /usr/lib/i386-linux-gnu/libXdmcp.so.6.0.0
b7071000-b7073000 r-xp 00000000 08:02 2101699    /usr/lib/i386-linux-gnu/libXau.so.6.0.0
b7073000-b7074000 r--p 00001000 08:02 2101699    /usr/lib/i386-linux-gnu/libXau.so.6.0.0
b7074000-b7075000 rw-p 00002000 08:02 2101699    /usr/lib/i386-linux-gnu/libXau.so.6.0.0
b7075000-b7089000 r-xp 00000000 08:02 525231     /lib/i386-linux-gnu/libz.so.1.2.3.4
b7089000-b708a000 r--p 00013000 08:02 525231     /lib/i386-linux-gnu/libz.so.1.2.3.4
b708a000-b708b000 rw-p 00014000 08:02 525231     /lib/i386-linux-gnu/libz.so.1.2.3.4
b708b000-b70b5000 r-xp 00000000 08:02 531289     /lib/i386-linux-gnu/libm-2.15.so
b70b5000-b70b6000 r--p 00029000 08:02 531289     /lib/i386-linux-gnu/libm-2.15.so
b70b6000-b70b7000 rw-p 0002a000 08:02 531289     /lib/i386-linux-gnu/libm-2.15.so
b70b7000-b70b8000 rw-p 00000000 00:00 0 
b70b8000-b70bb000 r-xp 00000000 08:02 3450829    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/input/libwinpr-input.so.1.1.0
b70bb000-b70bc000 r--p 00002000 08:02 3450829    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/input/libwinpr-input.so.1.1.0
b70bc000-b70bd000 rw-p 00003000 08:02 3450829    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/input/libwinpr-input.so.1.1.0
b70bd000-b70e0000 r-xp 00000000 08:02 2102308    /usr/lib/i386-linux-gnu/libxkbfile.so.1.0.2
b70e0000-b70e1000 ---p 00023000 08:02 2102308    /usr/lib/i386-linux-gnu/libxkbfile.so.1.0.2
b70e1000-b70e2000 r--p 00023000 08:02 2102308    /usr/lib/i386-linux-gnu/libxkbfile.so.1.0.2
b70e2000-b70e3000 rw-p 00024000 08:02 2102308    /usr/lib/i386-linux-gnu/libxkbfile.so.1.0.2
b70e3000-b70e4000 rw-p 00000000 00:00 0 
b70e4000-b70e7000 r-xp 00000000 08:02 3450750    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/pool/libwinpr-pool.so.1.1.0
b70e7000-b70e8000 r--p 00002000 08:02 3450750    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/pool/libwinpr-pool.so.1.1.0
b70e8000-b70e9000 rw-p 00003000 08:02 3450750    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/pool/libwinpr-pool.so.1.1.0
b70e9000-b70ef000 r-xp 00000000 08:02 5794229    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/primitives/libfreerdp-primitives.so.1.2.0
b70ef000-b70f0000 r--p 00005000 08:02 5794229    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/primitives/libfreerdp-primitives.so.1.2.0
b70f0000-b70f1000 rw-p 00006000 08:02 5794229    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/primitives/libfreerdp-primitives.so.1.2.0
b70f1000-b70f2000 rw-p 00000000 00:00 0 
b70f2000-b70f3000 r-xp 00000000 08:02 3450646    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/error/libwinpr-error.so.1.1.0
b70f3000-b70f4000 r--p 00000000 08:02 3450646    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/error/libwinpr-error.so.1.1.0
b70f4000-b70f5000 rw-p 00001000 08:02 3450646    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/error/libwinpr-error.so.1.1.0
b70f5000-b70f6000 r-xp 00000000 08:02 3450701    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/library/libwinpr-library.so.1.1.0
b70f6000-b70f7000 r--p 00000000 08:02 3450701    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/library/libwinpr-library.so.1.1.0
b70f7000-b70f8000 rw-p 00001000 08:02 3450701    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/library/libwinpr-library.so.1.1.0
b70f8000-b70fc000 r-xp 00000000 08:02 2504138    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/wtsapi/libwinpr-wtsapi.so.1.1.0
b70fc000-b70fd000 r--p 00003000 08:02 2504138    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/wtsapi/libwinpr-wtsapi.so.1.1.0
b70fd000-b70fe000 rw-p 00004000 08:02 2504138    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/wtsapi/libwinpr-wtsapi.so.1.1.0
b70fe000-b7107000 r-xp 00000000 08:02 3450698    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/rpc/libwinpr-rpc.so.1.1.0
b7107000-b7108000 r--p 00008000 08:02 3450698    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/rpc/libwinpr-rpc.so.1.1.0
b7108000-b7109000 rw-p 00009000 08:02 3450698    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/rpc/libwinpr-rpc.so.1.1.0
b7109000-b711a000 r-xp 00000000 08:02 3450775    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/sspi/libwinpr-sspi.so.1.1.0
b711a000-b711b000 r--p 00010000 08:02 3450775    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/sspi/libwinpr-sspi.so.1.1.0
b711b000-b711c000 rw-p 00011000 08:02 3450775    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/sspi/libwinpr-sspi.so.1.1.0
b711c000-b711d000 rw-p 00000000 00:00 0 
b711d000-b711e000 r-xp 00000000 08:02 3450835    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/dsparse/libwinpr-dsparse.so.1.1.0
b711e000-b711f000 r--p 00000000 08:02 3450835    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/dsparse/libwinpr-dsparse.so.1.1.0
b711f000-b7120000 rw-p 00001000 08:02 3450835    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/dsparse/libwinpr-dsparse.so.1.1.0
b7120000-b7123000 r-xp 00000000 08:02 3450761    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/registry/libwinpr-registry.so.1.1.0
b7123000-b7124000 r--p 00002000 08:02 3450761    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/registry/libwinpr-registry.so.1.1.0
b7124000-b7125000 rw-p 00003000 08:02 3450761    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/registry/libwinpr-registry.so.1.1.0
b7125000-b712d000 r-xp 00000000 08:02 5791436    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/utils/libfreerdp-utils.so.1.2.0
b712d000-b712e000 r--p 00007000 08:02 5791436    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/utils/libfreerdp-utils.so.1.2.0
b712e000-b712f000 rw-p 00008000 08:02 5791436    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/utils/libfreerdp-utils.so.1.2.0
b712f000-b7135000 r-xp 00000000 08:02 5791458    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/common/libfreerdp-common.so.1.2.0-beta1
b7135000-b7136000 r--p 00005000 08:02 5791458    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/common/libfreerdp-common.so.1.2.0-beta1
b7136000-b7137000 rw-p 00006000 08:02 5791458    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/common/libfreerdp-common.so.1.2.0-beta1
b7137000-b7138000 rw-p 00000000 00:00 0 
b7138000-b7145000 r-xp 00000000 08:02 5793223    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/crypto/libfreerdp-crypto.so.1.2.0
b7145000-b7146000 r--p 0000c000 08:02 5793223    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/crypto/libfreerdp-crypto.so.1.2.0
b7146000-b7147000 rw-p 0000d000 08:02 5793223    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/libfreerdp/crypto/libfreerdp-crypto.so.1.2.0
b7147000-b714a000 r-xp 00000000 08:02 531293     /lib/i386-linux-gnu/libdl-2.15.so
b714a000-b714b000 r--p 00002000 08:02 531293     /lib/i386-linux-gnu/libdl-2.15.so
b714b000-b714c000 rw-p 00003000 08:02 531293     /lib/i386-linux-gnu/libdl-2.15.so
b714c000-b714d000 rw-p 00000000 00:00 0 
b714d000-b716c000 r-xp 00000000 08:02 2099701    /usr/lib/i386-linux-gnu/libxcb.so.1.1.0
b716c000-b716d000 r--p 0001f000 08:02 2099701    /usr/lib/i386-linux-gnu/libxcb.so.1.1.0
b716d000-b716e000 rw-p 00020000 08:02 2099701    /usr/lib/i386-linux-gnu/libxcb.so.1.1.0
b716e000-b7170000 r-xp 00000000 08:02 3450621    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/environment/libwinpr-environment.so.1.1.0
b7170000-b7171000 r--p 00001000 08:02 3450621    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/environment/libwinpr-environment.so.1.1.0
b7171000-b7172000 rw-p 00002000 08:02 3450621    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/environment/libwinpr-environment.so.1.1.0
b7172000-b7173000 r-xp 00000000 08:02 3450627    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/heap/libwinpr-heap.so.1.1.0
b7173000-b7174000 r--p 00000000 08:02 3450627    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/heap/libwinpr-heap.so.1.1.0
b7174000-b7175000 rw-p 00001000 08:02 3450627    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/heap/libwinpr-heap.so.1.1.0
b7175000-b7176000 r-xp 00000000 08:02 3450649    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/libwinpr/interlocked/libwinpr-interlocked.so.1.1.0
b7176000-b7177000 r--p 00001000 08:02 3450649    /home/mrhieu/rdp_dev/rdp_compare/rdp_git/FreeRDP2/winpr/Aborted (core dumped)

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
