### ISSUE TITLE
Latest xfreerdp (git 17.03.14 and later) freezes up when playing video (from youtube or elsewhere)

### ISSUE THREAD

**Issue by tsol** [FreeRDP/FreeRDP#1759]
When playing video through browser (chrome, or IE - doesn't matter) extensive drawing causes xfreerdp to receive (send) mouse and keyboard inputs very badly while playing video.
Looks like xfreerdp is so busy updating screen that mouse and keyboard events get lost on the way. Video runs smoothly through. You can stop playback or close it or click anything only after 20 seconds of vain efforts. Then once video is stopped all runs ok and inputs are just fine.

Server is Windows 2003, no RFX used ofcourse.
Same is true for Windows 2008R2 + Google Chrome + YouTube.

Overlapping video window partly with some other window gives an improvement - so meaning the less video is actually visible during playback the better mouse and keyboard events do get to the server!
Disabling sound doesn't redirection affect the behaivor

Command line:
xfreerdp /cert-ignore +clipboard /f /u:'' /bpp:16 -sec-nla /drive:cdrom,/mnt/cdrom /drive:floppy,/mnt/floppy /drive:flash,/mnt/usbdevice /v:192.168.4.2

That does not happen with xfreerdp 1.0.2

**Comment by takenit2far** [comment]
If I specify -async-input it fixes the problem against 2008, haven't tested with 2012 yet.

According to /help the default for this option is off, but specifying '-' is definitely improving any tested video playback.  Without it, the client input is unavailable until the video has finished playing.
