### ISSUE TITLE
Session gets stuck dragging in Excel

### ISSUE THREAD

**Issue by chris-y** [FreeRDP/FreeRDP#1783]
I've just updated to the latest Git of xfreerdp and it seems to have introduced a problem that manifests itself in Excel.

When drag-highlighting a range of cells, if you drag off to the side and bottom (so the spreadsheet scrolls, highlighting more cells) every so often the remote session gets stuck highlighting cells - releasing the mouse button does not stop Excel scrolling and highlighting.  Clicking into another cell within Excel sometimes stops it but not always (and when it doesn't it is impossible to interact with anything in the remote session).

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
