### ISSUE TITLE
Freerdp server in Windows 8 x64 system Compile error

### ISSUE THREAD

**Issue by artwebs** [FreeRDP/FreeRDP#1797]
Error 246 error LNK1120: eight cannot resolve the external command E: \ temp \ RDP \ FreeRDP_build \ Debug \ libfreerdp - server. DLL freerdp - server
Error 238 error LNK2001: cannot resolve the external symbol of WTSFreeMemory E: \ temp \ RDP \ FreeRDP_build \ server \ common \ audin - server lib (audin. Obj) freerdp - server
Error 239 error LNK2001: cannot resolve the external symbol of WTSFreeMemory E: \ temp \ RDP \ FreeRDP_build \ server \ common \ cliprdr - server lib (cliprdr_main. Obj) freerdp - server
Error 240 error LNK2001: cannot resolve the external symbol of WTSFreeMemory E: \ temp \ RDP \ FreeRDP_build \ server \ common \ drdynvc - server lib (drdynvc_main. Obj) freerdp - server
Error 241 error LNK2001: cannot resolve the external symbol of WTSFreeMemory E: \ temp \ RDP \ FreeRDP_build \ server \ common \ RDPDR - server lib (rdpdr_main. Obj) freerdp - server
Error 222 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelClose E: \ temp \ RDP \ FreeRDP_build \ server \ common \ RDPSND - server lib (rdpsnd_main. Obj) freerdp - server
Error 243 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelOpen E: \ temp \ RDP \ FreeRDP_build \ server \ common \ drdynvc - server lib (drdynvc_main. Obj) freerdp - server
Error 244 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelOpen E: \ temp \ RDP \ FreeRDP_build \ server \ common \ RDPDR - server lib (rdpdr_main. Obj) freerdp - server
Error 245 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelOpen E: \ temp \ RDP \ FreeRDP_build \ server \ common \ RDPSND - server lib (rdpsnd_main. Obj) freerdp - server
Error 233 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelQuery E: \ temp \ RDP \ FreeRDP_build \ server \ common \ audin - server lib (audin. Obj) freerdp - server
Error 234 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelQuery E: \ temp \ RDP \ FreeRDP_build \ server \ common \ cliprdr - server lib (cliprdr_main. Obj) freerdp - server
Error 235 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelQuery E: \ temp \ RDP \ FreeRDP_build \ server \ common \ drdynvc - server lib (drdynvc_main. Obj) freerdp - server
Error 236 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelQuery E: \ temp \ RDP \ FreeRDP_build \ server \ common \ RDPDR - server lib (rdpdr_main. Obj) freerdp - server
Error 224 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelRead E: \ temp \ RDP \ FreeRDP_build \ server \ common \ audin - server lib (audin. Obj) freerdp - server
Error 225 error LNK2001: cannot resolve the external symbol of WTSVirtualChannelRead E: \ temp \ RDP \ F

How do I solve??

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
