### ISSUE TITLE
Windows VM cannot get serial output

### ISSUE THREAD

**Issue by macarthor** [FreeRDP/FreeRDP#1808]
I've got a serial device which connects to ubuntu through PL2303 USB converter. The serial device would output strings to USB-serial when it's working.

In ubuntu I open a console and type "cat /dev/ttyUSB0" to see if there's any string from the device.
sudo xfreerdp /serial:COM1,/dev/ttyUSB0
When the serial device is working, I can see output in the console with "cat /dev/ttyUSB0", but no any output in Windows VM opening a hyper terminal.

What might lead to this?

**Comment by akallabeth** [comment]
There have been some changes in serial redirection. Reopen if this still affects current nightly builds.
