### ISSUE TITLE
glyph forecolor and backcolor swapped?

### ISSUE THREAD

**Issue by naughton** [FreeRDP/FreeRDP#1811]
it seems that update_read_glyph_index_order reads them in the right order according to the spec (http://msdn.microsoft.com/en-us/library/cc241591.aspx), so that should mean that GLYPH_INDEX_ORDER has them in the correct order... 

when the callback for pGlyph_BeginDraw is called, background and foreground are swapped.

```c
typedef void (*pGlyph_BeginDraw)(rdpContext* context,
    int x, int y, int width, int height,
    UINT32 bgcolor, UINT32 fgcolor);
```

Am I interpreting something incorrectly, or is this a bug?

**Comment by bmiklautz** [comment]
Closing du to inactivity. Please re-open or create a new issue if this problem still exists on the current mater branch.
