### ISSUE TITLE
No Glyph support for Windows Server 2012?

### ISSUE THREAD

**Issue by itsmikeeng** [FreeRDP/FreeRDP#1827]
After building the latest FreeRDP version for Linux (Ubuntu), I ran the sample X11 client and targeting a Windows Server 2008 R2 SP1 machine. Everything worked fine, glyph callbacks in FreeRDP/client/X11/xf_graphics.cs (i.e. xf_Glyph_BeginDraw) were getting called.

However, targeting a Window Server 2012 machine, those glyph callbacks are not invoked. The text in the RDP session seem to be sent as bitmaps instead.

Is this a configuration issue in the sample app or possibility a setting issue on the target machine? Both Windows Servers were fresh built VMs in Azure, assuming default Windows settings.

Thanks,
Michael

**Comment by akallabeth** [comment]
Legacy RDP is phased out by MS just as @dbungert said.
