### ISSUE TITLE
Glitches when connecting with /bpp:32

### ISSUE THREAD

**Issue by grawity** [FreeRDP/FreeRDP#1838]
When connecting with FreeRDP 1.1 in 32-bit or 24-bit mode to Windows XP or Server 2003, there are frequent glitches in menus, sometimes also menu bars & buttons:

![](http://i.imgur.com/Qy2oeDn.png)
- FreeRDP 1.2.0-beta1 (git 1.1.0-beta+2013071101-1821-g8abc0)
- 16-bit mode works fine
- Both rdesktop and mstsc.exe work fine

**Comment by grawity** [comment]
Update – it seems that `+glyph-cache` helps, and `+glyph-cache /gdi:sw` makes Server 2003 work well even with 32bpp (except for the occassional misplaced text).

**Comment by akallabeth** [comment]
@grawity good to hear, just to clarify: you're using the old version mentioned or something more recent?

**Comment by grawity** [comment]
I test both the distro package and current Git builds. With Arch's 1.2.0_20160606 package, just `/gdi:sw` is enough (it seems glyph-cache is on by default). With today's 2.0.0-dev (git 215fbe8446e9) build, I need to enable both manually. (I've seen the misplaced text already reported in other issues, so I don't mind that.)
