### ISSUE TITLE
Poor sound quality problem

### ISSUE THREAD

**Issue by soar** [FreeRDP/FreeRDP#1842]
This is very old bug. When listening to some music via any player in terminal session, after some time sound becomes very ugly. This looks like sound stream in some moment degrades from 320 kbps to 32 kbps. And this poor sound stream can continues for 1-2 minutes before it becomes normal again. Music listening is unreal.

This patch (https://github.com/FreeRDP/FreeRDP/pull/1737) solves this problem. For example on revision db1159f7b6f60aa882611a229dd5d20673b44409 - this bug goes and only 1-2 millisecond small sound glitches appears. But today I try two different revisions: 01865f0e284ce34bb5f38842b34dc80f08b58749 (stable-1.1) and 3b47715a78eb15192caca4535ae740f3c719ca4d (master) - and both have this bug.

**Comment by ivan-83** [comment]
Fix: https://github.com/ivan-83/FreeRDP/commit/8d5825ee007a7889992d5a01e482d1589dd6a7ee
or use: /sound:sys:alsa,format:1,quality:high

**Comment by akallabeth** [comment]
#4453 should address this.

**Comment by akallabeth** [comment]
Should be fixed with #4453 (if proper codec support is compiled in)
