### ISSUE TITLE
Misuse of realloc()

### ISSUE THREAD

**Issue by zhangzl2013** [FreeRDP/FreeRDP#1856]
The realloc() function is nearly a trap.
It will return NULL, with the old ptr unchanged, when it failes.
Code like this is an error:

```
size *= 2;
ptr = (TYPE*) realloc(ptr, size);
```

It should be corrected as:

```
/* use code block to avoid the c89 compilter's complaint ;) */
{
    TYPE* nptr;

    nptr = (TYPE*) realloc(ptr, size * 2);
    if (!nptr)
    {
        /* error handle */
    }
    else
    {
        size *= 2;
        prt = nptr;
    }
}
```

We should correct the existing incorrect code when we meet them,
and avoid it in the future.

**Comment by akallabeth** [comment]
@mfleisz @hardening @bmiklautz From a first glance it looks like we did fix this, should this be closed?

**Comment by mfleisz** [comment]
@akallabeth Yes I'm pretty sure we did

**Comment by akallabeth** [comment]
Ok, closing this then.
