### ISSUE TITLE
Keyboard layout detection: Swiss French instead of swiss german

### ISSUE THREAD

**Issue by uzhoasit** [FreeRDP/FreeRDP#1862]
The automatiy keyboard layout detection chooses Swiss French instead of Swiss German. `setxkbmap -query` with swiss german keyboard layout says: 

```
rules:      evdev
model:      pc105
layout:     ch
options:    grp:shift_caps_toggle
```

If it's not possible to distinct between french swiss and german swiss the default should be changed to german swiss because there are more swiss german than swiss french.

**Comment by akallabeth** [comment]
Outdated, create a new issue if still relevant.
