### ISSUE TITLE
Leak in server-side NLA authentication

### ISSUE THREAD

**Issue by hardening** [FreeRDP/FreeRDP#1881]
Just a reminder for leaked buffers:
==24960== 12 bytes in 1 blocks are definitely lost in loss record 17 of 553
==24960==    at 0x4C2CD7B: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==24960==    by 0x77C922A: sspi_CopyAuthIdentity (sspi.c:354)
==24960==    by 0x50C02B4: peer_recv_callback (peer.c:282)
==24960==    by 0x50B08D9: transport_check_fds (transport.c:1207)
==24960==    by 0x50A8F4C: rdp_check_fds (rdp.c:1190)
==24960==    by 0x50BFBA4: freerdp_peer_check_fds (peer.c:88)
==24960==    by 0x404204: test_peer_mainloop (sfreerdp.c:751)
==24960==    by 0x63B5F8D: start_thread (pthread_create.c:311)
==24960==    by 0x66C5A0C: clone (clone.S:113)

**Comment by akallabeth** [comment]
Still relevant?
