### ISSUE TITLE
ringbuffer failure

### ISSUE THREAD

**Issue by phoenixfawkes** [FreeRDP/FreeRDP#1889]
On linux Mint/Maya

xfreerdp: /home/greg/FreeRDP/libfreerdp/utils/ringbuffer.c:243: ringbuffer_commit_read_bytes: Assertion `rb->size - rb->freeSize >= sz' failed.

It does not seem to be an issue with memory starvation.

**Comment by diaasami** [comment]
Getting the same error on Mint KDE 17 (14.04), happens after a while of normal usage with some features turned off.
/audio-mode:2 +clipboard /bpp:16 /sec:rdp /gateway-usage-method:direct /size:1440x900 -wallpaper -themes -grab-keyboard

**Comment by wartman4404** [comment]
I'm no longer experiencing this issue, and commit 81e190ec fixes the loop I pointed out above.  I can't say for sure that they're related, but it seems likely.  Thanks, awakecoding!

**Comment by awakecoding** [comment]
@wartman4404 I am pretty confident that the bug I fixed was this one. I just forgot about this issue when fixing it, it was very easy to reproduce in certain usage scenarios with the clipboard for some reason. I believe we can close this issue.
