### ISSUE TITLE
Segmentation fault in rfx.c line 1399

### ISSUE THREAD

**Issue by Arkantos7** [FreeRDP/FreeRDP#1893]
In file rfx.c, function  rfx_encode_message, line 1399

code snippet:
/\* when using threads ensure all computations are done _/
    message->tilesDataSize = 0;
    workObject = context->priv->workObjects;
    for (i = 0; i < message->numTiles; i++)
    {
        tile = message->tiles[i];
        if (context->priv->UseThreads)
        {
        WaitForThreadpoolWorkCallbacks(_workObject, FALSE); //<-----SEG FAULT
            CloseThreadpoolWork(*workObject);
            workObject++;
        }
        message->tilesDataSize += rfx_tile_length(tile);
    }

This prevents xfreerdp-server from sending any frame/message to client which results in a frozen screen at client and ultimately a crash.
workObject is NOT a null pointer so the trivial cause is ruled out.

**Comment by SekharSamala** [comment]
In latest stable branch , we are also seeing the same issues. have you figured out the cause . Please share any thing you know about fixing this issue.
