### ISSUE TITLE
Free RDP do not working over gateway.

### ISSUE THREAD

**Issue by SergeyShl** [FreeRDP/FreeRDP#1895]
1. the steps to reproduce the bug, command line you have used:
   There are two terminal Windows 2008 R2 servers, united in a farm. Connection to them is carried out through gateway available from the Internet.
   Means of RemoteApp created the RDP file. 
   In the RDP file: 
2.  The application name to which connection is carried out is entered. 
3.  FQDN of a termanal farm, as knot to which the appendix is carried out is registered. 
4.  The external name gateway through which connection is carried out is entered. 
5.  Custom parameters of connection "authentication level:i:0, enablecredsspsupport:i:0". 
6. The RDP file is signed by the certificate of the external CA.
   Command "wfreerdp.exe NameRDPFile.rdp" do nor working. Note: Thus classical the Windows RDP client works correctly.
   I tried to start commands with RDP file and without:
   "wfreerdp.exe NameRDPFile.rdp /u:domainuser /d:domain /p:password /gu:domainuser /gd:domainuser/ gp:password/ v:terminalfarmname /g:gatewayname"
   and
   "wfreerdp.exe /u:domainuser /d:domain /p:password /gu:domainuser /gd:domainuser /gp:password /v:terminalfarmname /g:gatewayname"
   In all cases the debug console window is closed too quickly, with what mistake work of freerdp comes to the end it is impossible to see. The log of files in the FreeRDP client any isn't present. In system events also aren't registered.
7. to what system did you connect to? (win8, 2008, ..)
   Client side - Windows 7, server side - Windows 2008 R2.
8. what did you expect to happen? what actually happened?
   Want to connect to terminal farm? but now it'snot works.
9. freerdp version (e.g. xfreerdp --version) or package version or git commit; operating System, architecture, distribution e.g. linux, amd64, debian; if you built it yourself add some notes which branch you have used, also your cmake parameters can help:
   FreeRDP 1.0. Client side - Windows 7, server side - Windows 2008 R2.

How to force to work as FreeRDP with the RDP file? Or what keys need to be used to be connected to the opublirovanny appendix directly?
I studied the link https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface. I tried to start FreeRDP with different keys but since dens in the client of FreeRDP aren't present, search of keys looks senselessly.

**Comment by akallabeth** [comment]
There have been fixes for gateway and redirection #4547, #4539 and #4548

**Comment by akallabeth** [comment]
Closing due to lack of feedback and successful connection attempts to (some) gateway configurations.
Look in referenced issues #4875 and #4781 for remaining issues.
