### ISSUE TITLE
Usb Redirection SegFault

### ISSUE THREAD

**Issue by mkurtgis** [FreeRDP/FreeRDP#1898]
I am running ubuntu 14.04 and I have installed the latest xfreerdp using git clone.  I have installed all the necessary dependencies for urbdrc and I am using this to compile

cmake -DCMAKE_BUILD_TYPE=Release  -DWITH_PCSC=ON -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DWITH_FFMPEG=ON -DWITH_XINERAMA=ON -DWITH_XCURSOR=ON -DWITH_DIRECTFB=ON -DCMAKE_INSTALL_PREFIX=~/freerdp

It compiles fine with no errors however I cannot get the usb redirection to work.  When I run it as non root I get the following error

loading channel drdynvc
Unable to find a match for unix timezone: Etc/UTC
Loading Dynamic Virtual Channel urbdrc
VID: 0x1D6B PID: 0x0002
libusb_open: (by id) error: 0xFFFFFFFD (-3)
libusb_open: (by id) error: 0xFFFFFFFD (-3)

I figure this may because of running as non root.  But as root I it seg faults...

loading channel drdynvc
Unable to find a match for unix timezone: Etc/UTC
Loading Dynamic Virtual Channel urbdrc
VID: 0x1D6B PID: 0x0002
fatal_handler: signum=11

I feel like this is something simple that I am missing.  Any ideas?

Matt

**Comment by akallabeth** [comment]
I've started refactoring the code with #3175 any feedback welcome.

**Comment by akallabeth** [comment]
Fixed with #5745
