### ISSUE TITLE
crash: 7271 Aborted (core dumped)

### ISSUE THREAD

**Issue by pascalBokBok** [FreeRDP/FreeRDP#1899]
I'm experiencing a crash every now and then  with 7271 Aborted (core dumped).
What can I do to work around?
Connecting to a windows 2012r2 terminal server.

xfreerdp -u username -p password --plugin rdpsnd --data latency:50 -- --plugin rdpdr --data disk:usb-media:/media/ -- -a 16 --rfx -x 80 -f 192.168.1.158

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/Prebuilds

**Comment by pascalBokBok** [comment]
@akallabeth Thanks :+1:
BTW. back then, after removing the sound and disk redirection the problem disappeared...
I think we should close this bug since there is very little tangible information about the crash
