### ISSUE TITLE
Build fails for iOS7.1 SDK on MAC OS X 10.9.3/Xcode 5.1.1

### ISSUE THREAD

**Issue by chrwick** [FreeRDP/FreeRDP#1905]
I have succesfully installed all the prerequisites.
According to README.ios, I have tried: 

    admins-mac-mini:FreeRDP admin$ cmake  -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode
    -- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk
    CMake Error at CMakeLists.txt:23 (project):
      The CMAKE_C_COMPILER:

    gcc

      is not a full path and was not found in the PATH.

    -- Checking whether C compiler has -isysroot
    -- Checking whether C compiler has -isysroot - yes
    -- Checking whether C compiler supports OSX deployment target flag
    -- Checking whether C compiler supports OSX deployment target flag - no
    CMake Error at CMakeLists.txt:23 (project):
      The CMAKE_CXX_COMPILER:

    g++

      is not a full path and was not found in the PATH.

    -- Checking whether CXX compiler has -isysroot
    -- Checking whether CXX compiler has -isysroot - yes
    -- Checking whether CXX compiler supports OSX deployment target flag
    -- Checking whether CXX compiler supports OSX deployment target flag - no
    -- Configuring incomplete, errors occurred!

Then I have tried:

    admins-mac-mini:FreeRDP admin$ cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DIOS_PLATFORM=SIMULATOR
    -- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.1.sdk
    -- The C compiler identification is AppleClang 5.1.0.5030040
    -- The CXX compiler identification is AppleClang 5.1.0.5030040
    -- Check for working C compiler using: Xcode
    -- Check for working C compiler using: Xcode -- broken
    CMake Error at /Applications/CMake.app/Contents/share/cmake-3.0/Modules/CMakeTestCCompiler.cmake:61 (message):
      The C compiler
      "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang"
      is not able to compile a simple test program.

      It fails with the following output:

       Change Dir: /Users/admin/FreeRDP/CMakeFiles/CMakeTmp

  

      Run Build Command:"/Applications/CMake.app/Contents/bin/cmakexbuild"  "-project" "CMAKE_TRY_COMPILE.xcodeproj" "build" "-target"  "cmTryCompileExec366925955" "-configuration" "Debug"

      === BUILD TARGET cmTryCompileExec366925955 OF PROJECT CMAKE_TRY_COMPILE
      WITH CONFIGURATION Debug ===

  

      Check dependencies

      target specifies product type 'com.apple.product-type.tool', but there's no
      such product type for the 'iphonesimulator' platform

      No architectures to compile for (ARCHS=armv7 armv7s, VALID_ARCHS=i386 x86_64).

  

      ** BUILD FAILED **

  

  

      The following build commands failed:

      	Check dependencies

      (1 failure)

  

  

      CMake will not be able to correctly generate this project.
    Call Stack (most recent call first):
      CMakeLists.txt:23 (project)

    -- Configuring incomplete, errors occurred!
    See also "/Users/admin/FreeRDP/CMakeFiles/CMakeOutput.log".
    See also "/Users/admin/FreeRDP/CMakeFiles/CMakeError.log".

Any ideas? It must be something very basic.

**Comment by bmiklautz** [comment]
Should be fixed on master and no feedback received for a while.
