### ISSUE TITLE
Connect FreeRDP to RD Farm

### ISSUE THREAD

**Issue by AShkaruba** [FreeRDP/FreeRDP#1924]
Hello
Please help me. We have a Server 2012 R2 connection broker - glx-broker. Two RD servers glx-term1, glx-term2. I install Debian and install freerdp on instruction https://github.com/FreeRDP/FreeRDP/wiki/Compilation. I run 
xfreerdp -f /v:glx-broker but i connected glx-broker. How i can connect to glx-term1 or glx-term2 with using glx-broker.

**Comment by akallabeth** [comment]
Fixed on current master.
