### ISSUE TITLE
Problems when connecting to xrdp (v0.8)

### ISSUE THREAD

**Issue by helongwen** [FreeRDP/FreeRDP#1932]
```
     My aim is to connect linux operating system(suse10sp2) for graphical operating by 
```

freerdp client.So I installed xrdp(v0.8) in suse 10sp2 ,and I installed freerdp(FreeRDP-1.1.0)
client in my Windows 7 ,when I opened wfreerdp.exe to connect suse10sp2 in windows 7,I found 
some characters are blank ,for example ,characters on the button can not be seen;When I open 
a text file which contains characters,it displays blank. 
        But when I use mstsc to connect suse10sp2 in windows 7, it displays normally.
        Does freerdp support to connect the linux operating system "suse10sp2" for  graphical operating? Have you ever test it on suse10sp2?Hope you can help me ,thanks!

**Comment by akallabeth** [comment]
Working on current debian stable (xrdp 0.9)
