### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#1949]
Currently there is very limited ipv6 support.
In the code there exists a setting to "enable" ipv6 (settings->IPv6Enabled) but this isn't exposed via command line switch. Also the hostname parsing (/v:) might not be ipv6 aware.

**Comment by sgargbugreporter** [comment]
Please convert this to a bug. Not having IPv6 support in 2015 is a big no-no!

**Comment by bmiklautz** [comment]
@sgargbugreporter the issue says "limited" ipv6 is basically supported so you can connect to a ipv6 host just use /v:[ipv6_adress] or /v:dnsnamethatresolvestov6. But some more complex features like gateway are not tested for v6 yet.
So give it a try!

**Comment by PPed72** [comment]
I can confirm that basic connection works.

**Comment by avollmerhaus** [comment]
So ipv6 support will be included in the next release? I'm using 1.2.1_pre20150326 and ipv6 does not work

**Comment by bmiklautz** [comment]
@avollmerhaus what distribution you are on? I don't now this release.

**Comment by avollmerhaus** [comment]
This is Gentoo, it seems like the ebuilds (Gentoo packages) just point to some commit.
Quoting from the ebuild:

        COMMIT="aa2181dcf2dd98693767ba738c5b2ad8c3d742d4"
        SRC_URI="https://github.com/FreeRDP/FreeRDP/archive/${COMMIT}.tar.gz

**Comment by bmiklautz** [comment]
@avollmerhaus this commit should work with ipv6 basic connectivity. But if the ip isn't used directly (via /v:[xxxx:xxx:..]) and a hostname is used that also has ipv4 entries those are given preferences (for now) even if there is an ipv6 dns entry.

**Comment by avollmerhaus** [comment]
Ah, the [ ] got interpreted away by my z-shell. Sorry for the nuisance and thanks for the quick answers!

**Comment by hardening** [comment]
@bmiklautz shall we close this one, as we can now use basic IPv6 ?

**Comment by weberhofer** [comment]
«hardening, you didn't ask me, but I think this issue can be closed. It was reported against a 1.2 version and is not related to a specific IPv6 issue.
