### ISSUE TITLE
PPA not working (404)

### ISSUE THREAD

**Issue by thany** [FreeRDP/FreeRDP#1951]
I wanted to install freerdp on Mint 16 (Unbuntu 13.10 it says while booting) in a Virtualbox 4.3.12 VM, using the PPA as linked to from here:
https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

So, I added the ppa:

```
sudo add-apt-repository ppa:freerdp-team/freerdp
```

And performed an update:

```
sudo apt-get update
```

And then I got this:

```
[snip]
Ign http://packages.linuxmint.com petra/main Translation-en                                                                                                 
Ign http://packages.linuxmint.com petra/upstream Translation-en_US                                                                                          
Ign http://packages.linuxmint.com petra/upstream Translation-en                                                                                             
Fetched 208 kB in 7s (29,4 kB/s)                                                                                                                            
W: Failed to fetch http://ppa.launchpad.net/freerdp-team/freerdp/ubuntu/dists/saucy/main/source/Sources  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/freerdp-team/freerdp/ubuntu/dists/saucy/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/freerdp-team/freerdp/ubuntu/dists/saucy/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

When I open those urls ([1](http://ppa.launchpad.net/freerdp-team/freerdp/ubuntu/dists/saucy/main/source/Sources) [2](http://ppa.launchpad.net/freerdp-team/freerdp/ubuntu/dists/saucy/main/binary-amd64/Packages) [3](http://ppa.launchpad.net/freerdp-team/freerdp/ubuntu/dists/saucy/main/binary-i386/Packages)) in a browser, they return a 404 as well, so I don't think any more system specs are needed, right?

**Comment by akallabeth** [comment]
nightly builds are working for all supported architectures.
