### ISSUE TITLE
Cannot connect to FreeRDP server using NTLM Single-Sign-On

### ISSUE THREAD

**Issue by mfleisz** [FreeRDP/FreeRDP#1966]
When trying to connect to the FreeRDP server using mstsc with SSO I get the following error:

unexpected pubKeyAuth buffer size:0
Error: could not verify client's public key echo
client authentication failure
Client (local) disconnected.

This problem was introduced with: 03cf7933d9c239be958e5aa8a570d5f591c7bbee
Changing the NLA_PKG_NAME back to NTLMSP_NAME makes everything work again.

**Comment by akallabeth** [comment]
Fixed on current master, reopen/create a new issue if still broken.
