### ISSUE TITLE
Error code change in 1.2 vs 1.1 - Obtaining SSL_read error codes from 1.2

### ISSUE THREAD

**Issue by takenit2far** [FreeRDP/FreeRDP#1968]
Hello

Under version 1.1, FreeRDP would produce different error codes if a password was wrong, or if a password had expired.

Bad password: SSL_read: error:14094419:SSL routines:SSL3_READ_BYTES:tlsv1 alert access denied

Expired account: SSL_read: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error

Using this we were able to push the users through a password reset screen, depending on the error output

In 1.2 we always get an error code of 0x2000D, regardless of the account status. 

Is it possible to receive a difference in response based on these two different conditions in version 1.2.  Perhaps by enabling some sort of debug option if possible? 

Much appreciated

James

**Comment by akallabeth** [comment]
Improved on target release.
Reopen if still not satisfactory.

**Comment by abhilashhm** [comment]
​Hello Team,

I am using GitHub desktop v1.6.5 and git version 2.21.0.windows.1 on Windows 7 with Service pack 1. I have 2 GitHub accounts, one is enterprize which I am able to clone using GitHub desktop and I've another personal account which is throwing me the below error when I try to clone a repository:

![GitHub Desktop Error](https://user-images.githubusercontent.com/9567333/57754756-d21dec00-770c-11e9-9e08-b5b1b508edd8.PNG)

"Closing into '<path>'....

fatal:unable to access 'https://github.com/abhilashhm/git-integration-public.git/': schannel: next InitializeSecurityContext failed: SEC_E_ILLEGAL_MESSAGE (0x80090326) - This error usually occurs when a fatal SSL/TLS alert is received (e.g. handshake failed). More details may be available in the Windows System event log."

The repository is public but I am unable to clone it. And we have an agent which connects to GitHub and pulls the scripts from there and I am unable to access it from our agent and get the below error:

![Git Agent Error](https://user-images.githubusercontent.com/9567333/57754748-ccc0a180-770c-11e9-99a3-f881c03f8dc5.PNG)

"Failed to retrieve branch information from specified repository.

fatal: unable to access
"https://github.com/abhilashhm/git-integration-public.git/":
error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied"

I tried passing the git URL with and without creds but I get the same error. Please suggest.
