### ISSUE TITLE
freerdp master_22-7-14 version using /rfx not showing RDP session in fullscreen

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#1980]
Dear Team,
xfreerdp /f /cert-ignore -sec-tls -sec-nla  /sound:sys:alsa /multimedia:decoder:gstreamer  /bpp:32  /network:lan /drive:home,/home/pano /gdi:hw /rfx  /u:admin /p:xxx@123 /v:192.168.1.153

**Comment by akallabeth** [comment]
Fullscreen working on current master c325ec5325d0a7836ef706ee6872976be6a12850
