### ISSUE TITLE
Unaligned access in SRCREADPIXEL (16 bpp) in bitmap_decode.c

### ISSUE THREAD

**Issue by ptsekov** [FreeRDP/FreeRDP#1986]
Hello,

I am porting FreeRDP to an older ARM processor which would genereate an exception on unaligned access. This could occur when using the SRCREADPIXEL in 16bpp session.  

See the proposed patch:
https://gist.github.com/ptsekov/40f2aeb71b9883f20423

**Comment by akallabeth** [comment]
Color conversion has been rewritten in 3c7cc555a5a5f02366918be7eb935bb1f22115ef
