### ISSUE TITLE
The logcat report error: OpenGLRender    Cannot generate texture from bitmap

### ISSUE THREAD

**Issue by uforgetmenot** [FreeRDP/FreeRDP#1987]
The remote desktop frame is standstill sometime and at the same time the logcat report lots of same errors: "OpenGLRender    Cannot generate texture from bitmap"  while I play some vedio. 
I think this is reference to the android hardware acceleration,and I close it by the code "setLayer".After that,it does not occured any more.
But next I found that the remote frame would be a white one in small posible case.
My android device is 4.2.
Is there any suggestions?

**Comment by bmiklautz** [comment]
Should be fixed on master. Closing.
