### ISSUE TITLE
master: aFreeRDP: remote screen is not displaying correctly.

### ISSUE THREAD

**Issue by g-reno** [FreeRDP/FreeRDP#1992]
I just tried aFreeRDP from master and the remote screen is not displaying correctly.

The background color is completely wrong.  The Start button on Windows 2008R2 is unreadable.  Icons all seem to be highlighted.

I compared this to a Remote Desktop session running from XP to the remote machine and there everything looks normal.

Tested on Android 4.0.4 and 4.2.2.

Phone image:
![screenshot_2014-07-24-16-19-34](https://cloud.githubusercontent.com/assets/803808/3694416/f7f8d83a-1371-11e4-93c5-b6722ca07209.jpg)

Remote Desktop image:
![screenshot from 2014-07-24 16 20 20](https://cloud.githubusercontent.com/assets/803808/3694423/11537dee-1372-11e4-85be-10ad7838f337.png)

**Comment by sriram-kakarala** [comment]
Any updates if these changes were merged to the master? I see the same issues with the latest code as well.

Thank you.

**Comment by akallabeth** [comment]
Master has a greatly improved rendering path, closing as resolved.
Reopen if still an issue with master.
