### ISSUE TITLE
FreeRDP's own 32bpp ROPs operate on the alpha channel

### ISSUE THREAD

**Issue by ptsekov** [FreeRDP/FreeRDP#1998]
I noticed a glitch when running Windows Explorer within a FreeRDP 16bpp session with all fancy visual features disabled (see attached pictures). It seemed like a place on the screen, where an icon was supposed to be displayed, was not painted into. After investigating the issue it turned out that the alpha channel byte for every pixel in this particular area was set to 0x00 instead of 0xFF. I traced the issue to BitBlt_SRCINVERT_32bpp() which applies the XOR operation on all 4 bytes of the operands instead just on the color information. Other 32bpp BitBlt ROPs also operate on all 4 bytes but I haven't investigated into details. I decided to give a heads up first.

Notice the three green rectangles in the upper right part of the screenshot - they are supposed to display icons
![ss_srcinvert_bug](https://cloud.githubusercontent.com/assets/8249935/3703336/b5739b84-1408-11e4-80ed-725719b64232.PNG)

After applying a fix to BitBlt_SRCINVERT_32bpp() things looks as expected
![ss_srcinvert_fix](https://cloud.githubusercontent.com/assets/8249935/3703381/34131442-1409-11e4-8c28-39644f4c8b35.PNG)

**Comment by akallabeth** [comment]
Closing as master has seen a lot of rendering patches.
