### ISSUE TITLE
freerdp_mono_image_convert() does not use ARGB32/ABGR32 for conversion to 32bpp destination

### ISSUE THREAD

**Issue by ptsekov** [FreeRDP/FreeRDP#1999]
I noticed a visual glitch when scrollbars were displayed in a 16bpp session with all visual enhancements turned off and 32bpp client display. The areas of the scrollbars above and below the scrollbar thumb would not get painted (see attached screenshot). I traced the problem to freerdp_mono_image_convert() which does not honour clrconv->alpha. freerdp_mono_image_convert() is called when the server instructs FreeRDP to use PatBlt with 1bpp bitmap pattern to fill the areas above and below the thumb.

![ss_freerdp_mono_image_convert_bug](https://cloud.githubusercontent.com/assets/8249935/3703659/0be843e0-140c-11e4-9e37-d781a8c8542f.PNG)

**Comment by akallabeth** [comment]
Color conversion has been rewritten in current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
