### ISSUE TITLE
Excessive memory usage when using bitmap cache with gdi_Bitmap_* bitmap implementation

### ISSUE THREAD

**Issue by ptsekov** [FreeRDP/FreeRDP#2003]
Hello,

I am porting FreeRDP to an embedded ARM device with proprietary OS and tight memory requirements. I found out that after some usage FreeRDP would consume all the memory available to its process and would crash. Investigating the issue I found the cause of the high memory usage to be the bitmap implementation as represented by the gdi_Bitmap_\* family of functions. The cached bitmaps sent by the server are decompressed into some memory block and attached to the `data' field of the`rdpBitmap' structure. Next the decompressed data is converted to the framebuffer format and stored in another memory block and attached to the field `bitmap' of`gdiBitmap'. Both copies are kept trough the entire bitmap lifetime though only the one in `gdiBitmap' is actually necessary. Worst case scenario is 32bpp session with 32bpp framebuffer. The X11 implementation take care of this issue and releases the block holding the uncompressed image data. The Win32 client has custom bitmap implementation but seems to suffer from the problem described above though I haven't investigated in depth (just looked at the source). The Android and iOS clients would suffer from this problem too and those have limited memory too.

Now, an easy solution would be to do what xf_Bitmap_New() does. What I don't like about this approach is the use of both the bitmap data pointer in `rdpBitmap' and in`gdiBitmap'. I would rather eliminate the pointer in `rdpBitmap' and pass the uncompressed source data via function arguments instead. Any thoughts?

Best regards,
Pavel Tsekov

**Comment by akallabeth** [comment]
closing for being ancient.
Create a new one if still an issue.
