### ISSUE TITLE
[Android] cmake error on win7_x86_64 and Cygwin

### ISSUE THREAD

**Issue by fengyc** [FreeRDP/FreeRDP#2013]
Hi, all.

I am compiling the code on windows and cygwin,  and getting an error:
CMake Error at client/Android/CMakeLists.txt:47 (message):
  android not found but required to build android java

Command used:
cmake -DCMAKE_TOOLCHAIN_FILE=cmake/AndroidToolchain.cmake \
-DCMAKE_HOST_WIN32=ON \
-DFREERDP_EXTERNAL_SSL_PATH="../android-external-openssl-ndk-static" \ 
-DFREERDP_EXTERNAL_JPEG_PATH="../jpeg8d"  \
-DANDROID_NDK=/cygdrive/d/programs/android-ndk-r10 \
-DANDROID_SDK=/cygdrive/d/programs/adt-bundle-windows-x86_64/sdk \
-DANDROID_ABI="armeabi-v7a"

Found an issue here : https://github.com/FreeRDP/FreeRDP/blob/master/client/Android/CMakeLists.txt#L45

The file does not exist in the android-sdk (windowns-x86_64 version). So, I replaced the code with:
if(CMAKE_HOST_WIN32)
    set(ANDROID_COMMAND "${ANDROID_SDK}/tools/android.bat")
else()
    set(ANDROID_COMMAND "${ANDROID_SDK}/tools/android")
endif()
And it works now. 
Please confirm the issue.

**Comment by zenix98** [comment]
I was having the same issue and after applying the above mentioned code replacement. it works.
Thanks for sharing i am building the freerdp project on windows using cygwin.

**Comment by akallabeth** [comment]
Assuming that works?
Since we are not using windows based builds I'll close it.
