### ISSUE TITLE
RemoteApp doesn't work anymore

### ISSUE THREAD

**Issue by evertheylen** [FreeRDP/FreeRDP#2014]
I'm trying to connect (from the host itself) to a Windows 7 Ultimate x64 VM running in KVM in an Arch Linux host. I previously used the freerdp package in Arch Linux' repos, which is version 1.0.2-6. I used the following command:

```
xfreerdp -u Evert -p xxxxx --app --plugin rail --data "||OneNote" -- 192.168.1.31
```

Things worked fine, but there where some problems with grainy text and RemoteFX. I've been playing with the `-x`argument to get smooth text and colors (which still confuses me) and `--rfx` to enable RemoteFX. When enabling RemoteFX though, text would become grainy (even when using `-x 99`), and `--enable-fonts` didn't work. Realizing the version I was using was quite old, I compiled freerdp from git (using the AUR). Then, I used this command:

```
evert% xfreerdp /u:Evert /p:xxxx /app:"||OneNote" /v:192.168.1.31 
loading channel rail
Unable to detect time zone

```

While it seems to be loading the rail thing which is obviously needed, nothing appears on my screen, and the cursor simply blinks. Without `/app:"||OneNote"` however, things work fine. I've also tried using cmd instead of OneNote, without succes.

**Comment by akallabeth** [comment]
Tried with #4322 RAILS working
