### ISSUE TITLE
Debian random closing

### ISSUE THREAD

**Issue by csabagy** [FreeRDP/FreeRDP#2025]
Dear costumer support,

I have a problem, and I’m hoping maybe you can help me..
The problem is that under debian 7, the newest version freerdp is quitting when I'm starting the Libre Office.
Can you help me about that please (maybe you have an idea or some solution to fix this)? I'd be really glad.
Thank you in advance.
Best regards:

**Comment by akallabeth** [comment]
Closing this one, there have been many memory issues fixed.
Reopen if still an issue.
