### ISSUE TITLE
Android: RedirectSound values reversed from Microsoft documentation

### ISSUE THREAD

**Issue by g-reno** [FreeRDP/FreeRDP#2043]
In looking through some code this weekend I noticed that the value that is used in redirecting sound appears to be reversed from the audiomode settings in Microsoft documentation.

```
Syntax
audiomode:i:<value>

Values
Value	 Explanation
0        Play sounds on the local computer (Play on this computer)
1        Play sounds on the remote computer (Play on remote computer)
2        Do not play sounds (Do not play)
The default value is 0.
```
In Android client, the setting is set from the index of the list in Advanced Settings, Redirect Sound
The list is ordered:
Do not play
Play on Server
Play on Device

Which would yield the reverse of the documentation.

**Comment by akallabeth** [comment]
Fixed with current master 52f1e6b27a3c2ecbfa757cdc1ecdcfcb283f16ce
