### ISSUE TITLE
Cannot connect to Connection Broker through Gateway

### ISSUE THREAD

**Issue by kyvandoan** [FreeRDP/FreeRDP#2052]
I have a non-persistent VDI collection on Windows Server 2012 R2 named "Pool".

I use the latest master build (1.2), and also the stable version (1.10). I have the same problem on both version,

I am able to connect to a VM using the Connection Broker by adding /load-balance-info:tsv://VMResource.1.Pool parameter (IP based redirection:)

However, if I add the Gateway settings, I will get through the Gateway, but there is no way to reach the Connection Broker.
FreeRDP returns me TS Gateway Connection Success and launches the Windows Server Session login screen instead of continuing to the Connection Broker.

Is there any tips for a workaround on this issue ?
The problem is similar to #836 but none of the workarround and new build fixes it.

Thank you for helping :)

**Comment by kyvandoan** [comment]
@Reflexic Hi! Happy new year! I didn't figured out how to solve the issue yet. Still running into the same issue.

**Comment by awakecoding** [comment]
@kyvandoan @Reflexic can you try my branch? I have a bunch of stability fixes for the connection broker. If you're lucky one of those fixes might help. https://github.com/awakecoding/FreeRDP

**Comment by Reflexic** [comment]
I will try your branch tomorrow, thank you. Can you or someone else tell me
exactly what my command should look like to connect to a ts gateway on a
server 2012? The /v: and /g: should be the same correct as all remote
desktop services / gateway are running on the same server.

On Sat, Jan 3, 2015 at 7:38 AM, Marc-André Moreau <notifications@github.com>
wrote:

> @kyvandoan <https://github.com/kyvandoan> @Reflexic
> <https://github.com/Reflexic> can you try my branch? I have a bunch of
> stability fixes for the connection broker. If you're lucky one of those
> fixes might help. https://github.com/awakecoding/FreeRDP
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeRDP/FreeRDP/issues/2052#issuecomment-68598541>.
>



-- 
Tyler Scott

**Comment by akallabeth** [comment]
Closing, no feedback and code changed significantly.
