### ISSUE TITLE
Audio Redirection against a session broker in 1.1 Stable not working.

### ISSUE THREAD

**Issue by takenit2far** [FreeRDP/FreeRDP#2063]
Does anyone have this working on 1.1 stable?

If I connect to a single host, it works fine.  If I am redirected to another host by the broker, all I hear is silence.  No error messages,  both 2008 R2 and 2012 R2 behave the same. 

It works fine in Master, does anyone have this working?   I am using Alsa 1.0.27 in Ubuntu 14.04.

**Comment by akallabeth** [comment]
#4548 #4539 #4547

**Comment by akallabeth** [comment]
Working in `2.0.0-rc3`.
Reopen or create a new issue if there are still issues.

**Comment by DanielErnesto88** [comment]
I also have this problem with version 2.3 of freerdp
