### ISSUE TITLE
Unimplemented signature id: 0x00100001 (TS Gateway)

### ISSUE THREAD

**Issue by Edlanta** [FreeRDP/FreeRDP#2074]
Freerdp freezes about 30-50 minutes after connecting to a win2008r2/win2012r2 server over TS Gateway with the following terminal output:

Unimplemented signature id: 0x00100001
RTS PDU Signature: Flags: 0x0004 NumberOfCommands: 1
Identified OUT_R1/A1 RTS PDU

According to [MS-RPCH] this PDU indicates, that the server is trying to recycle the VirtualOutChannel. 

I have compiled Freerdp from master branch with the following cmake statement:
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DMONOLITHIC_BUILD=ON -DBUILD_SHARED_LIBS=OFF .

The command line looks like this:
xfreerdp -sec-nla /g:"Gateway-Server-Name.dev.extern" /bpp:32 /u:"Anon" /d:"dev.test" /p:"Passwd" /v:"Server-Name.dev.test" /port:3389

(The domain of the Gateway server is a different one as the domain of the server connecting to)

The Gateway server is a normal win2012r2 server with Gateway role added. The RAP and CAP is configured to let anybody connect to the gateway and the user with which i connect exists in Gateway-Server and Normal-Server.

**Comment by awakecoding** [comment]
@Edlanta did you make any progress on this? I spent some time trying to fix this issue today. The first thing I fixed was the improper identification of the RTS PDU, the first message we get for OUT channel recycling is an OUT_R1/A2 PDU, not an OUT_R1/A1 PDU. I added code to send an HTTP message with content length 120 as per the spec for a replacement OUT channel. I also added code to send the OUT_R1/A3 PDU. However, I don't get the expected OUT_R1/A6 PDU after that, so something must be wrong in the messages I'm sending. Any help would be nice. https://github.com/awakecoding/FreeRDP/commit/f79deaff7ba54e1832854b752aa52ae5a9f962f2

**Comment by Edlanta** [comment]
I also have done some research about this topic. Here is what i got:

- I also have tried to send the correct HTTP message for channel recycling, but unfortunately this does not work like described in the documentation, so i talked to a guy at Microsoft dochelper and he tried to help me with this. It seems that we need to open a new TCP connection if we want to do the channel recycle. (In section 3.2.1.5.3.4 there is a note at the end of the chapter which says:
Note In an effort to improve readability, the establishments of TCP connections are not shown in the figure.)

So this is my current state at the moment:

- First i initialize a new transport layer with function transport_new(). After that i create a new rpc layer with function rpc_new(new_transport). Then i allocate memory for rpc->VirtualConnection->NonDefaultOutChannel (old rpc struct). 
- After that im calling the function rpc_ncacn_http_ntlm_init(new_rpc, TSG_CHANNEL_OUT) and after that i start preparing the HTTP Out Channel Request. This is a little bit tricky, because we first need to do the ntlm thing again by calling ntlm_authenticate(ntlm) If this function returns 0 we must set the content length of our HTTP request to 0, prepare the stream with function rpc_ntlm_http_request(rpc, &ntlm->outputBuffer[0], content_length, TSG_CHANNEL_OUT) and send the request via rpc_out_write(rpc, Stream_Buffer(s), Stream_Length(s)). 
- After that i'm waiting for the HTTP response. I always get the response, so i think this is a good sign. The response contains the ntlm token data which we will use in our next step. 
-The next step is sending the out channel request again, but this time  ntlm_authenticate(ntlm) should not return 0 anymore. So we prepare our HTTP request and set the content length to 120. 

After that i switch the channels: 
- rpc_new->VirtualConnection->NonDefaultOutChannel = rpc_old->VirtualConnection->DefaultOutChannel

- rpc_new->VirtualConnection->DefaultOutChannel = rpc_old->VirtualConnection->NonDefaultOutChannel

The last step i have managed is sending out the OUT_R1/A3 PDU but after that something strange is happening:
- I always get an HTTP Error 401 (Access denied) and i dont know why
- But if i sniff the traffic with Message Analyzer i can see that the server is sending the next PDU (OUT_R1/A6 PDU)

Another thing i observed is that Message Analyzer isn't able to decrypt the traffic reliable. Sometimes i need the certificate from Gateway Server, sometimes i need both certificates (Gateway and Terminal Server) and sometimes Message Analyzer isn't able to decrypt the traffic at all.

The last tip i got is a Registry Key for Gateway Server to set the amount of data which can be transmitted throug Out Channel before the Server initiates a Channel Recycle:
-  HKLM\Software\Microsoft\Rpc\DefaultChannelLifetime
You can set this to decimal 131072 (128kb) and you will get the Channel Recycle mechanism, after round about 10 seconds instead of wating an hour to check if your changes were successfull.

At the moment i don't have much time to investigate this topic further. So it would be nice if you can help and share your gathered information with me, so we can complete this complicated mechanism. ( Remember that we also need to do the IN Channel Recycle, after we are successfull with OUT Channel recycle)

**Comment by akallabeth** [comment]
Is this resolved with `2.0.0-rc4` and following?

**Comment by akallabeth** [comment]
Tried with `2.0.0-rc4` and da819bf770cf14202514601182ea2a9d48056280
channel recycling is working there.
