### ISSUE TITLE
remoteApp failed

### ISSUE THREAD

**Issue by chym95** [FreeRDP/FreeRDP#2081]
xfreerdp 1.1 crashes when I run a remoteapp. The error message is slightly different:

loading channel rail
loading channel drdynvc
Warning xf_GetWindowProperty (177): Property 365 does not exist
connected to etudes4:3389
creating directory /root/.config/freerdp
creating directory /root/.config/freerdp/certs
creating directory /root/.config/freerdp/server
certificate_store_open: error opening [/root/.config/freerdp/known_hosts] for writing
Unable to find a match for unix timezone: conf/localtime
Loading Dynamic Virtual Channel urbdrc
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  147 (RENDER)
  Minor opcode of failed request:  4 (RenderCreatePicture)
  Serial number of failed request:  145
  Current serial number in output stream:  149

loading channel rail
loading channel drdynvc
Warning xf_GetWindowProperty (177): Property 365 does not exist
connected to etudes4:3389
creating directory /root/.config/freerdp
creating directory /root/.config/freerdp/certs
creating directory /root/.config/freerdp/server
certificate_store_open: error opening [/root/.config/freerdp/known_hosts] for writing
Unable to find a match for unix timezone: conf/localtime
Loading Dynamic Virtual Channel urbdrc
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  147 (RENDER)
  Minor opcode of failed request:  4 (RenderCreatePicture)
  Serial number of failed request:  184
  Current serial number in output stream:  188

loading channel rail
loading channel drdynvc
Warning xf_GetWindowProperty (177): Property 365 does not exist
connected to etudes4:3389
creating directory /root/.config/freerdp
creating directory /root/.config/freerdp/certs
creating directory /root/.config/freerdp/server
certificate_store_open: error opening [/root/.config/freerdp/known_hosts] for writing
Unable to find a match for unix timezone: conf/localtime
Loading Dynamic Virtual Channel urbdrc
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  147 (RENDER)
  Minor opcode of failed request:  4 (RenderCreatePicture)
  Serial number of failed request:  136
  Current serial number in output stream:  140

I use :
xfreerdp   -sec-nla /cert-ignore  -grab-keyboard  /gdi:sw  +window-drag  +menu-anims  /app:"||calc"  /t:"calc"  /bpp:16  /kbd:0x0000040C  /u:"user"  /p:'password' /d:"domain" -offscreen-cache  /usb:id,dev: -toggle-fullscreen  /v:myserver

**Comment by boospy** [comment]
Should this work now? Have the same error here... 1.1.0-beta1 on Ubuntu 16.04

**Comment by akallabeth** [comment]
@boospy 1.1.0 is old, try https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by boospy** [comment]
Oh yes, it is extremly old... why share ubuntu such old software for stable? ... I installed the nightly version, it is working perfectly :) very thanks.

**Comment by boospy** [comment]
Oh yes, it is extremly old... why share ubuntu such old software for stable? ... I installed the nightly version, it is working perfectly :) very thanks.

**Comment by akallabeth** [comment]
@boospy good to know, closing this issue.

**Comment by massich** [comment]
I had the same issue. (and also an old version: `This is FreeRDP version 1.1.0-beta1 (git n/a)`). Then reading through your FAQ I found that you had a PPA (but its also old)

https://github.com/FreeRDP/FreeRDP/wiki/FAQ

maybe you want to remove it from the wiki. (I'm trying the PRebuild, now)
