### ISSUE TITLE
NumLock out of sync

### ISSUE THREAD

**Issue by rchovan** [FreeRDP/FreeRDP#2083]
This latest build version has bug with NumLock. Numlock is not synced between local host and remote host.
If on my keyboard is NumLock ON, then on remote is OFF
If I switch Numlock during connection, then state is out of sync, but NumLock LED does not change, LED is in same state as before connection, and NumLock function change state.

**Comment by rchovan** [comment]
solved

**Comment by bmiklautz** [comment]
@rchovan thanks for the feedback. Was this solved in xrdp or on FreeRDP master?

**Comment by rchovan** [comment]
I'm using only windows binary FreeRDP client. See my post from  9 Sep 2014
