### ISSUE TITLE
Unexpected RTS PDU: Expected CONN/C2

### ISSUE THREAD

**Issue by VasasA** [FreeRDP/FreeRDP#2100]
Hi, I want to connect to Win2008 Standard via gateway. But usually I see this error (like in issue #1505):

loading channel rdpdr
loading channel rdpsnd
loading channel cliprdr
connected to xxx.xxx.xxx.xxx.xx:443
connected to xxx.xxx.xxx.xxx.xx:443
Unexpected RTS PDU: Expected CONN/C2
rts_connect error!
rpc_connect failed!
Error: protocol security negotiation or connection failure

I think, the FreeRDP is the only RDP client, what can use the TS Gateway on Linux. My company bought a lot of PC with Suse, but we cannot use the terminal servers. The TS gateway consists 12 servers, and the terminal server farm consists 22 servers.
I did this testing procedure on aug. 27:
1. I Downloaded freeRDP 1.1 Zip from https://github.com/FreeRDP/FreeRDP/tree/stable-1.1
2. I wanted to see the out_channel_request's PDU, so I modified the libfreerdp/core/gateway/rpc.c file: I copied the lines of WITH_DEBUG_TSG (6 lines) from the "rpc_in_write" function into the "rpc_out_write" function.
3. I built it with -DWITH_DEBUG_TSG=ON
Exactly: cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_CUPS=ON -DWITH_DEBUG_TSG=ON .
4. The command:
xfreerdp /cert-ignore /g:gateway /gu:user /gp:password /gd:domain /d:domain /u:user +clipboard /printer /v:TS-farm
5. The FreeRDP stops on "VIRTUAL_CONNECTION_STATE_WAIT_C2" state. Later writes the error message. The output is here: http://pastie.org/9507303
6. Important: Sometimes connection is established successfully. The chance of it: 3-4%. In this case I see the windows login screen. The output is here: http://pastie.org/9507370
7. I tried the shareware version of iTap software. (It has been discontinued by the provider on Linux: https://itap-mobile.com/desktop/rdp)
iTap always connect successfully.

I'm not an expert, but I have two tips: Probably the reason of error: If the OUT Channel and the IN Channel are established by two different TS gateway servers... RPC over HTTP v1 and RPC over HTTP v2 are not compatible...
Thanks...

**Comment by akallabeth** [comment]
Gateway fixes #4539, #4547 and #4548

**Comment by akallabeth** [comment]
This specific issue seems to be fixed, reopen or create a new issue if you encounter it again.
