### ISSUE TITLE
Send release event for pressed keys if client loses focus (xfreerdp)

### ISSUE THREAD

**Issue by leoluk** [FreeRDP/FreeRDP#2104]
If a shortcut is used to switch away from the xfreerdp window, no release event is send to the remote server, resulting in the keys being stuck.

The same issue has been affecting Remmina: https://github.com/FreeRDP/Remmina/issues/7

It was fixed with this commit: https://github.com/FreeRDP/Remmina/commit/17f023202bed56cf43383d50a8014f8eab77c5ee

**Comment by Vladimir-csp** [comment]
Why isn't it already merged after almost a year? Switching desktops away from xfreerdp window results in stuck Super key inside RDP session.
I will test the patch...

**Comment by Vladimir-csp** [comment]
I've applied the patch to version 1.1.0~git20140921.1.440916e+dfsg1-4 (Debian jessie), replacing "xf_keyboard" with "xf_kbd". But Super key is still stuck when returning to freedesktop window after swithcing from it with keyboard.

**Comment by leoluk** [comment]
Remmina had a similar issue, see https://github.com/FreeRDP/Remmina/issues/7#issuecomment-126452716

**Comment by Vladimir-csp** [comment]
does [this](https://github.com/FreeRDP/Remmina/commit/cc427c785726594bbdfbcdaf36601f4f82b66fe1) commit help? if so, how it can be adapted for xfreerdp?

**Comment by bmiklautz** [comment]
Should be fixed on master. Closing.
