### ISSUE TITLE
Current master fails to build with WITH_MACAUDIO=ON if architecture includes i386

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#2109]
When building the current master with mac audio and the architecture is set to or includes i386 the build fails.

Here's the cmake that cause trouble: 
cmake "-DMONOLITHIC_BUILD=ON" "-DWITH_CHANNELS=ON" "-DSTATIC_CHANNELS=ON" "-DWITH_FFMPEG=OFF" "-DWITH_X11=ON" "-DWITH_MACAUDIO=ON" "-DWITH_CUPS=ON" "-DWITH_CLIENT=ON" "-DBUILD_SHARED_LIBS=ON" "-DWITH_PCSC=ON" -D "CMAKE_OSX_ARCHITECTURES:STRING=i386;x86_64" .

The relevant parts of the make output:
Scanning dependencies of target rdpsnd-client-mac
[ 89%] Building C object channels/rdpsnd/client/mac/CMakeFiles/rdpsnd-client-mac.dir/rdpsnd_mac.c.o
In file included from /Volumes/Temp/Downloads/FreeRDP-master/channels/rdpsnd/client/mac/rdpsnd_mac.c:33:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:34:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AUMIDIController.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/CoreMIDI.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIDriver.h:19:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPlugInCOM.h:18:16: error: 
      typedef redefinition with different types ('SInt32' (aka 'long') vs 'ULONG' (aka 'unsigned int'))
typedef SInt32 HRESULT;
               ^
/Volumes/Temp/Downloads/FreeRDP-master/winpr/include/winpr/wtypes.h:157:15: note: previous definition is here
typedef ULONG HRESULT;
              ^
In file included from /Volumes/Temp/Downloads/FreeRDP-master/channels/rdpsnd/client/mac/rdpsnd_mac.c:33:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:34:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AUMIDIController.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/CoreMIDI.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIDriver.h:19:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPlugInCOM.h:19:16: error: 
      typedef redefinition with different types ('UInt32' (aka 'unsigned long') vs 'unsigned int')
typedef UInt32 ULONG;
               ^
/Volumes/Temp/Downloads/FreeRDP-master/winpr/include/winpr/wtypes.h:78:22: note: previous definition is here
typedef unsigned int ULONG;
                     ^
In file included from /Volumes/Temp/Downloads/FreeRDP-master/channels/rdpsnd/client/mac/rdpsnd_mac.c:33:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AudioToolbox.h:34:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/AudioToolbox.framework/Headers/AUMIDIController.h:15:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/CoreMIDI.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreMIDI.framework/Headers/MIDIDriver.h:19:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFPlugInCOM.h:21:21: error: 
      typedef redefinition with different types ('CFUUIDBytes' vs 'IID _' (aka 'struct _GUID *'))
typedef CFUUIDBytes REFIID;
                    ^
/Volumes/Temp/Downloads/FreeRDP-master/winpr/include/winpr/wtypes.h:194:14: note: previous definition is here
typedef IID_ REFIID;
             ^
3 errors generated.
make[2]: **\* [channels/rdpsnd/client/mac/CMakeFiles/rdpsnd-client-mac.dir/rdpsnd_mac.c.o] Error 1
make[1]: **\* [channels/rdpsnd/client/mac/CMakeFiles/rdpsnd-client-mac.dir/all] Error 2
make: **\* [all] Error 2

If I compile either without i386 or without mac audio, all is fine.

**Comment by bmiklautz** [comment]
Still an issue or can this be closed?

**Comment by lemonmojo** [comment]
I don't care about 32 bit at this point, so from my side, this can be closed.
