### ISSUE TITLE
aFreeRDP crash when connecting to xrdp

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#2117]
aFreeRDP (from git) crashes when connecting to xrdp (0.61) on Fedora 20.

Following backtrace (crash in memcpy):

V/WindowOrientationListener(  197): nearestRotation : 3   Angle: 268   tilt: 39
   I/DEBUG   (  104):          #00  pc 0000dcb4  /system/lib/libc.so (memcpy)
   I/DEBUG   (  104):          #01  pc 00080920  /data/data/com.freerdp.afreerdp/lib/libfreerdp-android.so
   I/DEBUG   (  104):
   I/DEBUG   (  104): code around pc:
   I/DEBUG   (  104): 4009ac94 e0422003 e2522020 3a000008 e3c1c01f  . B.  R....:....
   I/DEBUG   (  104): 4009aca4 e28cc040 e8b10ff0 f5dcf040 e2522020  @.......@...  R.
   I/DEBUG   (  104): 4009acb4 849c3020 e8a00ff0 2afffff9 e2822020   0.........*  ..
   I/DEBUG   (  104): 4009acc4 e312001f 0a00000c e1b0ce02 28b100f0  ...............(
   I/DEBUG   (  104): 4009acd4 48b10300 28a000f0 48a00300 e1b0cf02  ...H...(...H....
   I/DEBUG   (  104):
   I/DEBUG   (  104): code around lr:
   I/DEBUG   (  104): 5bde5904 e3a03000 e50b3008 ea00000f e51b3014  .0...0.......0..
   I/DEBUG   (  104): 5bde5914 e51b000c e51b1010 e1a02003 ebfff03e  ......... ..>...
   I/DEBUG   (  104): 5bde5924 e51b3018 e51b2010 e0823003 e50b3010  .0... ...0...0..
   I/DEBUG   (  104): 5bde5934 e51b3018 e51b200c e0823003 e50b300c  .0... ...0...0..
   I/DEBUG   (  104): 5bde5944 e51b3008 e2833001 e50b3008 e51b2008  .0...0...0... ..
   I/DEBUG   (  104):
   I/DEBUG   (  104): memory map around addr 5c6ad000:
   I/DEBUG   (  104): 5c4e1000-5c6ad000
   I/DEBUG   (  104): 5c6ad000-5c6ae000
   I/DEBUG   (  104): 5c6ae000-5c7ad000
   I/DEBUG   (  104):
   I/DEBUG   (  104): stack:
   I/DEBUG   (  104):     5dc879d0  00bf4b20  [heap]
   I/DEBUG   (  104):     5dc879d4  56d7d948  /dev/ashmem/dalvik-LinearAlloc (deleted)
   I/DEBUG   (  104):     5dc879d8  5dc87a68 
   I/DEBUG   (  104):     5dc879dc  4098617f  /system/lib/libdvm.so
   I/DEBUG   (  104):     5dc879e0  00bf4b20  [heap]
   I/DEBUG   (  104):     5dc879e4  56d7d948  /dev/ashmem/dalvik-LinearAlloc (deleted)
   I/DEBUG   (  104):     5dc879e8  41410e78  /dev/ashmem/dalvik-heap (deleted)
   I/DEBUG   (  104):     5dc879ec  1d20000d 
   I/DEBUG   (  104):     5dc879f0  56d7d948  /dev/ashmem/dalvik-LinearAlloc (deleted)
   I/DEBUG   (  104):     5dc879f4  009c1c30  [heap]
   I/DEBUG   (  104):     5dc879f8  409ccf9c  /system/lib/libdvm.so
   I/DEBUG   (  104):     5dc879fc  00bf4b20  [heap]
   I/DEBUG   (  104):     5dc87a00  40c4aecc  /dev/ashmem/dalvik-heap (deleted)
   I/DEBUG   (  104):     5dc87a04  40976b5f  /system/lib/libdvm.so
   I/DEBUG   (  104):     5dc87a08  df0027ad 
   I/DEBUG   (  104):     5dc87a0c  00000000 
   I/DEBUG   (  104): #00 5dc87a10  00bf4b20  [heap]
   I/DEBUG   (  104):     5dc87a14  00000007 
   I/DEBUG   (  104):     5dc87a18  5c462f24 
   I/DEBUG   (  104):     5dc87a1c  5dc87af8 
   I/DEBUG   (  104):     5dc87a20  5c462f0c 
   I/DEBUG   (  104):     5dc87a24  5bc6876a  /data/dalvik-cache/data@app@com.freerdp.afreerdp-1.apk@classes.dex
   I/DEBUG   (  104):     5dc87a28  5dc87a64 
   I/DEBUG   (  104):     5dc87a2c  41b94578  /dev/ashmem/dalvik-heap (deleted)
   I/DEBUG   (  104):     5dc87a30  56fdbd60  /dev/ashmem/dalvik-LinearAlloc (deleted)
   I/DEBUG   (  104):     5dc87a34  5bde5924  /data/data/com.freerdp.afreerdp/lib/libfreerdp-android.so
   I/DEBUG   (  104): #01 5dc87a38  00000000 
   I/DEBUG   (  104):     5dc87a3c  00000000 
   I/DEBUG   (  104):     5dc87a40  5c4e1020 
   I/DEBUG   (  104):     5dc87a44  419c8f78  /dev/ashmem/dalvik-heap (deleted)
   I/DEBUG   (  104):     5dc87a48  5dc87aa8 
   I/DEBUG   (  104):     5dc87a4c  00000640 
   I/DEBUG   (  104):     5dc87a50  00000f00 
   I/DEBUG   (  104):     5dc87a54  5c6ac620 
   I/DEBUG   (  104):     5dc87a58  41b94578  /dev/ashmem/dalvik-heap (deleted)
   I/DEBUG   (  104):     5dc87a5c  00000498 
   I/DEBUG   (  104):     5dc87a60  5dc87abc 
   I/DEBUG   (  104):     5dc87a64  5bde5a50  /data/data/com.freerdp.afreerdp/lib/libfreerdp-android.so
   I/DEBUG   (  104):     5dc87a68  00000780 
   I/DEBUG   (  104):     5dc87a6c  000004b0 
   I/DEBUG   (  104):     5dc87a70  00000320 
   I/DEBUG   (  104):     5dc87a74  00000498 
   I/DEBUG   (  104):     5dc87a78  00000002 
   I/DEBUG   (  104):     5dc87a7c  ffffffff

**Comment by akallabeth** [comment]
Closing, if it is still an issue with current master reopen.
