### ISSUE TITLE
Color issue and Update missing in windows 2010 R2

### ISSUE THREAD

**Issue by Joseph1977** [FreeRDP/FreeRDP#2118]
This is an old issue, but I saw you close it, I pull the code (master) this morning, and try it, unfortunately I get a BAD image and corrupted color in Windows 2010 R2, see attached snapshot.
- I had an old version, in that version which I can't remember which version it was, I can dig and find it if it is important, in that version, I get some missing draw/update but never had color issues.
- When connect to windows 2012, all work ok!!!, see image attached!
  +Im using and need to use colorDepth = 16

![win2012](https://cloud.githubusercontent.com/assets/1216345/4345844/a890ee1a-40e2-11e4-8f33-4bcf8b7c754a.jpg)
![win2kbadcolorandimage](https://cloud.githubusercontent.com/assets/1216345/4345845/a89612c8-40e2-11e4-8739-3c75e1179dc7.jpg)

**Comment by akallabeth** [comment]
Color conversion has been rewritten
