### ISSUE TITLE
Ubuntu 14.10

### ISSUE THREAD

**Issue by urang27** [FreeRDP/FreeRDP#2119]
Hi, I found this error where doing make, any idea?

Building C object channels/drdynvc/tsmf/ffmpeg/CMakeFiles/tsmf_ffmpeg.dir/tsmf_ffmpeg.c.o
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:42:15: error: field ‘codec_id’ has incomplete type
  enum CodecID codec_id;
               ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c: In function ‘tsmf_ffmpeg_init_context’:
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:57:2: warning: implicit declaration of function ‘avcodec_alloc_context’ [-Wimplicit-function-declaration]
  mdecoder->codec_context = avcodec_alloc_context();
  ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:57:26: warning: assignment makes pointer from integer without a cast
  mdecoder->codec_context = avcodec_alloc_context();
                          ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c: In function ‘tsmf_ffmpeg_init_video_stream’:
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:77:2: warning: ‘avcodec_alloc_frame’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3189) [-Wdeprecated-declarations]
  mdecoder->frame = avcodec_alloc_frame();
  ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c: In function ‘tsmf_ffmpeg_init_audio_stream’:
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:92:25: error: ‘AVCodecContext’ has no member named ‘dsp_mask’
  mdecoder->codec_context->dsp_mask = AV_CPU_FLAG_SSE2 | AV_CPU_FLAG_MMX2;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c: In function ‘tsmf_ffmpeg_prepare’:
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:177:2: warning: implicit declaration of function ‘avcodec_open’ [-Wimplicit-function-declaration]
  if (avcodec_open(mdecoder->codec_context, mdecoder->codec) < 0)
  ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c: In function ‘tsmf_ffmpeg_set_format’:
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:206:25: error: ‘CODEC_ID_VC1’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_VC1;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:206:25: note: each undeclared identifier is reported only once for each function it appears in
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:209:25: error: ‘CODEC_ID_WMAV2’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_WMAV2;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:212:25: error: ‘CODEC_ID_WMAPRO’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_WMAPRO;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:215:25: error: ‘CODEC_ID_MP3’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_MP3;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:218:25: error: ‘CODEC_ID_MP2’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_MP2;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:221:25: error: ‘CODEC_ID_MPEG2VIDEO’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_MPEG2VIDEO;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:224:25: error: ‘CODEC_ID_WMV3’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_WMV3;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:227:25: error: ‘CODEC_ID_AAC’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_AAC;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:239:25: error: ‘CODEC_ID_H264’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_H264;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:242:25: error: ‘CODEC_ID_AC3’ undeclared (first use in this function)
    mdecoder->codec_id = CODEC_ID_AC3;
                         ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c: In function ‘tsmf_ffmpeg_decode_video’:
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:302:3: warning: ‘avcodec_alloc_frame’ is deprecated (declared at /usr/include/libavcodec/avcodec.h:3189) [-Wdeprecated-declarations]
   frame = avcodec_alloc_frame();
   ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c: In function ‘tsmf_ffmpeg_decode_audio’:
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:340:32: error: ‘AVCODEC_MAX_AUDIO_FRAME_SIZE’ undeclared (first use in this function)
   mdecoder->decoded_size_max = AVCODEC_MAX_AUDIO_FRAME_SIZE + 16;
                                ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:375:4: warning: implicit declaration of function ‘avcodec_decode_audio3’ [-Wimplicit-function-declaration]
    len = avcodec_decode_audio3(mdecoder->codec_context,
    ^
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c: In function ‘TSMFDecoderEntry’:
/home/kami/FreeRDP-stable-1.0/channels/drdynvc/tsmf/ffmpeg/tsmf_ffmpeg.c:502:3: warning: implicit declaration of function ‘avcodec_init’ [-Wimplicit-function-declaration]
   avcodec_init();
   ^
channels/drdynvc/tsmf/ffmpeg/CMakeFiles/tsmf_ffmpeg.dir/build.make:54: recipe for target 'channels/drdynvc/tsmf/ffmpeg/CMakeFiles/tsmf_ffmpeg.dir/tsmf_ffmpeg.c.o' failed
make[2]: *** [channels/drdynvc/tsmf/ffmpeg/CMakeFiles/tsmf_ffmpeg.dir/tsmf_ffmpeg.c.o] Error 1
CMakeFiles/Makefile2:686: recipe for target 'channels/drdynvc/tsmf/ffmpeg/CMakeFiles/tsmf_ffmpeg.dir/all' failed
make[1]: *** [channels/drdynvc/tsmf/ffmpeg/CMakeFiles/tsmf_ffmpeg.dir/all] Error 2
Makefile:133: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by hardening** [comment]
@urang27 I'd say that you don't have the correct version for ffmpeg headers

**Comment by bmiklautz** [comment]
@urang27 how did you install the ffmpeg headers?

**Comment by hardening** [comment]
No feedback, closing the issue.
