### ISSUE TITLE
URBDRC client with multiple USB devices

### ISSUE THREAD

**Issue by diger74** [FreeRDP/FreeRDP#2126]
Hi all,

Could anyone tell me please how to launch xfreerdp with redirecting two (or more) USB devices?

I tried the following syntax:

xfreerdp -sec-nla /dvc:urbdrc,id,dev:1a86:7523 /dvc:urbdrc,id,dev:04b9:0300 /v:myServerIp

And I got working only the first device. On the second one I got "existing device, abort." message in the console.
But these devices are different!
First (1a86:7523) is USB-to-COM cable and the second (04b9:0300) is Sentinel's USB token. But they have the same class (0xFF).

Any help appreciated.

**Comment by dd-jacks** [comment]
`
/usb:id,dev:aaaa:xxxx#bbbb:yyyy
`

`aaaa` and `bbbb` - is idVendor
`xxxx` and `yyyy` - is idProduct
`#` - is delimiter

**Comment by akallabeth** [comment]
Fixed with #5745
