### ISSUE TITLE
Security Exchange failed when connect with /sec:tls /network:auto

### ISSUE THREAD

**Issue by hyacinthes** [FreeRDP/FreeRDP#2131]
Hi all,

Does any one meet the following issue from master branch code? I've built it to xfreerdp.
I had captured the packet at server side (Win8.1) using Message analyzer and it reported the following diagnostic error and warning. 

Following is my question:
Q1: Point 3 and 4 cause the Security exchange failed, And I guess it also affect the auto-detect feature. Does anyone meet the similar phenomenon? 
Q2: Is /network:auto only could work under /sec:tls? I've tried with /sec:rdp, the server never send auto-detect request to client.

1.Validation RDPBCGR: The EncryptionMethods field in type TSUDCSSec should be set to a combination of one or more of 0x00000001, 0x00000002, 0x00000008, 0x00000010, not 0 (0x00000000) (0 (0x00000000)).

2.Validation RDPBCGR: The ExtEncryptionMethods field in type TSUDCSSec should be set to a combination of one or more of 0x00000001, 0x00000002, 0x00000008, 0x00000010, not 0 (0x00000000) (0 (0x00000000)).

3.Validation RDPBCGR: The ClientAddressFamily field in type TSExtendedInfoPacket must be set to one of 0x0002, 0x0017, not 0 (0x0000).

4.Parsing RDPBCGR: ClientInfoPdu cannot be decoded successfully.

5.Parsing RDPBCGR: ClientAutoDetectResponsePdu cannot be decoded successfully.

**Comment by akallabeth** [comment]
Not reproducible on current master.
Create a new issue if not fixed.
