### ISSUE TITLE
Microphone (master/stable-1.1) issues 

### ISSUE THREAD

**Issue by Testinos** [FreeRDP/FreeRDP#2133]
Have problem with microphone redirection, try build stable-1.1 with (cmake -DWITH_PULSE=ON . ) microphone in Win 2012R2 not work(pulse/alsa), in corrent master version not work too, but i find some commit where microphone work but not perfect (commit 98077cfc2443cf7da9973cccc616c2e7cf0346f8 (may 30 15:06:07)), 
So i have question: FreeRDP doesn't support microphone anymore?
Try it in Ubuntu 14.04/12.04/Debian 7/ Thinstation 5.2.

**Comment by akallabeth** [comment]
Is this still an issue with current master (2.0)?

**Comment by akallabeth** [comment]
Fixed command line parsing with #3172, looks like it was always using pulse.
