### ISSUE TITLE
Graphic artifacts in 24bpp session

### ISSUE THREAD

**Issue by Alkenso** [FreeRDP/FreeRDP#2140]
In session with 24bpp color depth in some cases artifacts appears.
(Example: goto youtube.com, scroll page. In some place there are bitmaps with artifacts)
![screen shot 2014-10-09 at 12 54 37 pm](https://cloud.githubusercontent.com/assets/8972879/4574225/97438b7e-4f9a-11e4-8b47-35e8eb101d85.png)

**Comment by hardening** [comment]
@BUGgs any feedback on this one ?

**Comment by BUGgs** [comment]
Yes, on ARM device, I still need /gdi:sw to make it work correctly in 24/32 bit... (tested with yesterday master)

**Comment by hardening** [comment]
@BUGgs could you open another issue for your specific ARM bug, and give us more details, and try to put a screenshot so that we can have an idea of the kind of artifact you're experimenting.

**Comment by hardening** [comment]
@Alkenso does the changes done by @awakecoding fixed the artfiacts ?

**Comment by akallabeth** [comment]
working in current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
