### ISSUE TITLE
misbehaving remote programs lock local session

### ISSUE THREAD

**Issue by grawity** [FreeRDP/FreeRDP#2147]
Sometimes I have to run Windows console-based programs that generate a lot of output (let's say 3000 lines in a few seconds, or in rare cases an infinite backtrace loop). This seems to cause quite a few problems with both FreeRDP _and_ rdesktop:
- the RDP client ignores absolutely any input (mouse or keyboard) as long as the program keeps printing output, so I cannot Ctrl+C the misbehaving program or at least minimize the console window &ndash; I have to wait it out;
- Windows wants to redraw the console window after every single line, so I disconnect to make it 5x faster;
- the RDP client also keeps the keyboard grabbed, which [breaks interaction with local UI in certain window managers](https://bugzilla.gnome.org/show_bug.cgi?id=735785), so I cannot close the RDP window either...

(If I connect to another Windows computer, however, and from there use `mstsc` to connect to the 'broken' one, it does have problems with input but is merely a bit laggy, not completely unresponsive, so this doesn't seem to be an unfixable problem in RDP or Windows...)

Still, I don't know how much of this is FreeRDP's fault, but I hope that at least the 3rd item could be fixed.

**Comment by akallabeth** [comment]
Working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
