### ISSUE TITLE
Gateway password from cmdline not respected

### ISSUE THREAD

**Issue by frispete** [FreeRDP/FreeRDP#2149]
In contrary to 1.1, when a gateway password is given by /gp:xxx, it is not respected.

For 1.1, one was able to supply /u, /g and /gp arguments by cmdline, but omitting /p with the result, that authentication for the gateway was "bypassed" and authentication was requested from the target machine. With 1.2, one has to give either both passwords by cmdline and bypass authentication all together, otherwise the gateway password is requested in the terminal, from where xfreerdp is executed, which is rather inconvenient.

Of course, the gw password handling by cmdline is suboptimal at best, but without great efforts in a local user interface not solvable otherwise.

This is related to 1.2.0 beta as of 2014/10/14, running on openSUSE 13.1, connecting to Windows Server 2008 R2.

My build is publicly accessible here:
https://build.opensuse.org/package/show/home:frispete:RemoteDesktop/freerdp12
Please, don't be confused due to the patches, they're not applied in the 1.2 build.

**Comment by akallabeth** [comment]
Setting `/p` without `/gp` does use the same password for both, gateway and target.
