### ISSUE TITLE
libwinpr RPATH handling issue in current 1.1 and 1.2 builds

### ISSUE THREAD

**Issue by frispete** [FreeRDP/FreeRDP#2150]
Without supplying -DCMAKE_SKIP_INSTALL_RPATH=ON, build fails with:

[   44s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/freerdp12-0-git20141014.0.0.x86_64/usr/lib64/libwinpr.so.1.1.0
[   44s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/freerdp12-0-git20141014.0.0.x86_64/usr/lib64/libwinpr.so.1.1
[   44s] -- Installing: /home/abuild/rpmbuild/BUILDROOT/freerdp12-0-git20141014.0.0.x86_64/usr/lib64/libwinpr.so
[   44s] CMake Error at winpr/libwinpr/cmake_install.cmake:60 (FILE):
[   44s]   file RPATH_CHANGE could not write new RPATH:
[   44s] 
[   44s]     $ORIGIN/../lib64:$ORIGIN/..
[   44s] 
[   44s]   to the file:
[   44s] 
[   44s]     /home/abuild/rpmbuild/BUILDROOT/freerdp12-0-git20141014.0.0.x86_64/usr/lib64/libwinpr.so.1.1.0
[   44s] 
[   44s]   No valid ELF RPATH or RUNPATH entry exists in the file;
[   44s] Call Stack (most recent call first):
[   44s]   winpr/cmake_install.cmake:64 (INCLUDE)
[   44s]   cmake_install.cmake:71 (INCLUDE)
[   44s] 
[   44s] 
[   44s] make: **\* [install] Error 1
[   44s] error: Bad exit status from /var/tmp/rpm-tmp.nmfCAd (%install)
[   44s] 

Usual Linux distribution builds don't like RPATH anyway, but it took me some time to figure out a workaround. 

My build is publicly accessible here:
https://build.opensuse.org/package/show/home:frispete:RemoteDesktop/freerdp12
Please, don't be confused due to the patches, they're not applied in the 1.2 build.

**Comment by akallabeth** [comment]
Fixed for 2.0 release candidates.
