### ISSUE TITLE
Wrong graphics, color shifted. Xcode 5.1.1, Mac OS X 10.9.3, cmake 2.8.12.2

### ISSUE THREAD

**Issue by palmoff** [FreeRDP/FreeRDP#2152]
Im getting strange picture on iOS 7.1, iOS 8.0.2, on different iOS devices (iPads/iPhones):
![img_1957](https://cloud.githubusercontent.com/assets/8365333/4662797/78185f72-5535-11e4-9993-37cf58c96a3d.PNG)

The same issue on different RDP servers, with different graphic setting.
May be I missing something obvious ? What Im doing wrong ?

**Comment by wwwzys** [comment]
@Elyas-Crimean Has this issue been solved?

**Comment by wwwzys** [comment]
@bmiklautz   “ looks for me like this is related to recent changes in GDI (CLRCONV_INVERT).  ”
How to solve ?

**Comment by wwwzys** [comment]
@bmiklautz   “ looks for me like this is related to recent changes in GDI (CLRCONV_INVERT).  ”
How to solve ?

**Comment by wwwzys** [comment]
@bmiklautz  i want to solve this problem,and i do not how to do. can you help me.

**Comment by wwwzys** [comment]
@palmoff  who has solved this problem ? can you give me a hand ?

**Comment by DonMag** [comment]
No guarantees, but (in iOS client app)...

In:
>    ios_freerdp_ui.m  

in:
>    static void ios_create_bitmap_context(mfInfo* mfi) { ... }

Change:
>    if (gdi->dstBpp == 16)

to:
>    if (gdi->dstBpp == 16 || gdi->dstBpp == 15)

**Comment by wwwzys** [comment]
@DonMag yes, it worked!  You are great! Thank you very much.

**Comment by kaizirlewagen** [comment]
@DonMag works perfect.

**Comment by bmiklautz** [comment]
@DonMag I'll see that we get your fix on master. Thank you.

**Comment by bmiklautz** [comment]
@DonMag could you test if PR #2428 fixes this problem on master?

**Comment by DonMag** [comment]
@bmiklautz looks good to me - I hadn't seen ->bytesPerPixel when I initially looked at the problem.

**Comment by R3G3N3R4T0R** [comment]
I have a similar issue now and it is on Artix x86_64 LXQt with OpenRC. The colors are off like the picture above and the server is running Win10. I have tried KRDC, Remmina and running xfreerdp in the terminal. Only Remmina have the right color from the start but it shifted if I track the window's size to change the resolution. 
Should I submit a separate ticket for that?
![issue1](https://user-images.githubusercontent.com/54089608/137082077-2448c544-1994-4e94-b0a8-83f4c731c1ac.png)
![issue](https://user-images.githubusercontent.com/54089608/137082095-a0321d22-e4d0-447a-85f3-64b97ec654d9.png)
