### ISSUE TITLE
Unicode characters are wrong interpreted in title

### ISSUE THREAD

**Issue by rchovan** [FreeRDP/FreeRDP#2153]
Hi, 
I'm heavily using title caption in Windows FreeRDP client with parameter /t:.
Latest versions have bug, Unicode characters are wrong interpreted. 
See screenshot.

![wfrerdp-unicode](https://cloud.githubusercontent.com/assets/6713920/4663339/b4c1899e-553a-11e4-9dc4-c4fae17a84ed.png)

**Comment by rchovan** [comment]
this bug is still present in nightly build from 12.2.2015 (windows binary client)

**Comment by bmiklautz** [comment]
@rchovan which nightlies are you using?

**Comment by rchovan** [comment]
@bmiklautz binaries are from http://www.cloudbase.it/freerdp-for-windows-nightly-builds/

**Comment by akallabeth** [comment]
Referenced bugfix has long been merged.
