### ISSUE TITLE
Windows client disable keyboard

### ISSUE THREAD

**Issue by rchovan** [FreeRDP/FreeRDP#2159]
Hi, 
sometimes (once in a week) windows freerdp client disable keyboard on local host. I can't type. When I terminate wfreerdp.exe from process explorer, then keyboard works again. I want to provide logs, but currently windows client do not have any option for debug, or log to file (https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface). 
If you can provide me static binary with enabled debug, I can upload logs.

**Comment by majkinetor** [comment]
This should be reopened. It happens constantly to me. I had to terminate connection. 

I can send feedback, whatever needed. 

Its certain its not about CPU.

**Comment by majkinetor** [comment]
BTW, it happens daily to me. I am using latest nightly release on Windows 10. If you want, I can open a new ticket or we can debug here @akallabeth

**Comment by akallabeth** [comment]
@majkinetor ok, then better a new issue with a more detailed failure description. (and you know the `<ctrl>+<alt>` escape combo?)

**Comment by majkinetor** [comment]
No, what does CTRL + ALT + ESC do ?

**Comment by akallabeth** [comment]
@majkinetor only `<crtl>+<alt>` removes the keyboard input capture from the freerdp session so you can use the keyboard in the system again?

**Comment by majkinetor** [comment]
OK, I will try that and open a new ticket.

**Comment by majkinetor** [comment]
Tried latest master via nightlz and it still happens.
