### ISSUE TITLE
xcode 6.1 compile error

### ISSUE THREAD

**Issue by kaizirlewagen** [FreeRDP/FreeRDP#2162]
Hi,

I try to compile FreeRDP with Mac OS X 10.9.5 64-Bit and XCode 6.1 SDK 8.1 CMake 3.0.2

I have to modify the script /scripts/OpenSSL-DownloadAndBuild.command to build armv7 and armv7s OpenSSL libs ... 

USER_OS_SDK="iPhoneOS8.1.sdk"
USER_SIM_SDK="iPhoneSimulator7.1.sdk"

After that i use the following cmake command:

/Applications/CMake.app/Contents/bin/cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode -DIOS_PLATFORM=SIMULATOR

If i try to compile FreeRDP.xcodeproj -> BUILD_ALL i got this error at iFreeRDP package:

Undefined symbols for architecture i386:
  "_fwrite$UNIX2003", referenced from:
      _int_rsa_verify in libcrypto.a(rsa_sign.o)
      _read_string in libcrypto.a(ui_openssl.o)
      _read_string_inner in libcrypto.a(ui_openssl.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas to solve the problem?

**Comment by kaizirlewagen** [comment]
Currently I can compile FreeRDP with Mac OS X 10.9.5 64-Bit and XCode 6.1.1 SDK 8.1 CMake 2.8.12 for arm7 arm7s. 

The "new" arm64 support is missing, are there any plans to add arm64 support?

**Comment by bmiklautz** [comment]
@kaizirlewagen plans yes but no scheduler for it. We'll work on it when someone got some time left ;). The debian people have fixed the build for arm64 and have packages for it so it should basically work but you need a patch from them http://anonscm.debian.org/cgit/collab-maint/freerdp.git/tree/debian/patches/1004_64-bit-architectures.patch that didn't make it to master yet.

**Comment by bmiklautz** [comment]
Since the issue itself is solved I'll close it.

**Comment by kaizirlewagen** [comment]
Thank you for the informations, i will try it.

**Comment by bmiklautz** [comment]
@kaizirlewagen didn't try it for ios arm64 myself but let us know how it went ;)

**Comment by kaizirlewagen** [comment]
I use the latest FreeRDP version with Mac OS X 10.9.5 64-Bit and XCode 6.1 SDK 8.1.

I create these two patches to use compile it for arm64, works fine.

```
--- a/winpr/include/winpr/wtypes.h	2015-03-17 09:34:16.000000000 +0100
+++ b/winpr/include/winpr/wtypes.h	2015-03-16 10:47:00.000000000 +0100
@@ -54,7 +54,7 @@
 #define __int32 int
 #define __int64 long long
 
-#if __x86_64__
+#if __ILP64__ || __LP64__
 #define __int3264 __int64
 #else
 #define __int3264 __int32
@@ -168,7 +168,7 @@
 typedef void *PVOID64, *LPVOID64;
 typedef unsigned short WORD, *PWORD, *LPWORD;
 
-#if __x86_64__
+#if __ILP64__ || __LP64__ || __LLP64__
 typedef __int64 INT_PTR;
 typedef unsigned __int64 UINT_PTR;
 #else
```
```
--- a/cmake/iOSToolchain.cmake	2015-03-17 09:34:16.000000000 +0100
+++ b/cmake/iOSToolchain.cmake	2015-03-16 10:43:50.000000000 +0100
@@ -49,8 +49,8 @@
 # Force the compilers to gcc for iOS
 if(NOT CMAKE_C_COMPILER)
 	include (CMakeForceCompiler)
-	CMAKE_FORCE_C_COMPILER (gcc GNU)
-	CMAKE_FORCE_CXX_COMPILER (g++ GNU)
+	CMAKE_FORCE_C_COMPILER (/usr/bin/gcc GNU)
+	CMAKE_FORCE_CXX_COMPILER (/usr/bin/g++ GNU)
 endif()
 
 # Skip the platform compiler checks for cross compiling
@@ -146,7 +146,7 @@
 # set the architecture for iOS 
 # NOTE: Currently both ARCHS_STANDARD_32_BIT and ARCHS_UNIVERSAL_IPHONE_OS set armv7 only, so set both manually
 if (${IOS_PLATFORM} STREQUAL "OS")
-	set (IOS_ARCH armv7 armv7s)
+	set (IOS_ARCH arm64 armv7 armv7s)
 	set (CMAKE_SYSTEM_PROCESSOR armv7)
 else (${IOS_PLATFORM} STREQUAL "OS")
 	set (IOS_ARCH i386)
```

**Comment by huangjunsong** [comment]
@bmiklautz @kaizirlewagen What does it mean to create patch?How to create it?

**Comment by kaizirlewagen** [comment]
@huangjunsong The two code blocks in my post are the patches (created with diff).

**Comment by huangjunsong** [comment]
@kaizirlewagen I succeed to compile it for arm64.Thank you very much.I really appreciate your help！

**Comment by phongleq** [comment]
Is there a update to this diff? Im trying to get the current master to build for 64bit.

**Comment by mhoskin** [comment]
Hello, has this been tried with OpenSSL 1.1.0e and SDK 10.3?  I've been struggling trying to get this built with the current versions for a 64-bit compliant app.  I've tried building the libraries separately through OpenSSL for iOS and loading them, but get an error with libwinpr.a not being built with bitcode and also by modifying the DownloadAndBuild command to download the 1.1.0e OpenSSL version, but it seems to fail building each arm (I only see the lib crypto and libel libraries in the 386 formats).

I'm using Xcode 8.3.1 and MacOS 10.12.4.  Could anyone point me in the right direction with this problem?

**Comment by MjzDk** [comment]
@mhoskin I was also in this situation, eventually reducing the "cmake" version and successfully generating some other required files. Just now I need to integrate my project, I don't know what documents to import
