### ISSUE TITLE
ConnectionType and network bandwidth

### ISSUE THREAD

**Issue by itsmikeeng** [FreeRDP/FreeRDP#2163]
Setting ConnectionType doesn't appear affect bandwidth usage. For example, when testing I'm running a FreeRDP client on a Windows desktop and setting ConnectionType to "modem". There are two target servers, ServerHigh and ServerLow, where the network bandwidth to the servers are high and low respectively. When watching the same YouTube video on each server via RDP, much more data is sent from ServerHigh than ServerLow.

Is this expected? If so, is there any way to limit bandwidth usage?

Note: Using latest release version of 1.1.

**Comment by akallabeth** [comment]
Fixed on master.
Create a new issue if not.
