### ISSUE TITLE
xfreerdp fullscreen not rendering correctly or not at all

### ISSUE THREAD

**Issue by oelbox** [FreeRDP/FreeRDP#2166]
Connecting to a rdp-server in fullscreen renders only the first 15-20 percent of the remote desktop, pressing ctrl-alt-enter (exiting fullscreen) the entire remote desktop is rendered normally, pressing ctrl-alt-enter to enter fullscreen again result in what appears to be a transparent window, meaning it is showing my local desktop, but nothing on the desktop is clickable - so it's like a fullscreen window that is completely transparent.

When connecting in fullscreen and getting a partial render of the desktop, doing a "windows-key+d" (toggle desktop), xfreerdp will render the entire screen, but exiting fullscreen, and entering fullscreen again, doing "windows-key+d" again will not render the window, and I'm stuck in a "fullscreen transparent window" until I exit fullscreen.

Everything works fine if I start xfreerdp without the fullscreen switch (but going fullscreen with ctrl-alt-enter introduces the problem again).

This was not an issue in xfreerdp 1.0.2, but was first experienced with 1.1.0. I've tried with version 1.2.0-beta1, but with the same result.

I've tried various bpp settings and other adjustments to see if something else was influencing this (disabling xfwm compositor etc), but this did not seem to have any effect on the issue.

My system is running Arch Linux, with xfce 4.10 on an Intel HD 3000 (xf86-video-intel version 2.99.916).

Command line to connect:
xfreerdp /f /admin /u:user /p:password /network:broadband /v:server:3389 /bpp:16

This goes for connecting to a windows xp machine, a windows server 2008, a windows server 2008 R2 and also windows XP running in virtualbox and connecting to the built in virtualbox rdp-server implementation.

Once in a while though, a fullscreen connect works, but pressing ctrl-alt-enter to exit full screen, and then pressing ctrl-alt-enter to enter fullscreen will always result in the "fullscreen transparent window".

Downgrading to freerdp 1.02  and connecting using: "xfreerdp -0 -f -u user -p password -x b server" fixes the issue.

If this is a known bug, I apologize for posting a duplicate issue, I could not find any other issue describing the above, but that might come down to my lacking github-search-skills.

**Comment by jawz101** [comment]
remmina/freerdp have been causing me issues on Arch since I'd been using Arch for the past couple of years.  Switching to Xubuntu seems to work well.  I tried so many iterations of settings (disabling themes service on the Windows 7 box, disabling NLA and just using plain old security, trying different compression levels on the Arch box... nothing helps.  All I can say is the RDP session hangs and I constantly have to disconnect and reconnect after every mouse click to get the screen to redraw itself.

**Comment by akallabeth** [comment]
Fullscreen is working on `2.0.0-rc2`, create a new issue if you find something again.
