### ISSUE TITLE
 ${MSVC_RUNTIME} not defined in cmake/FindOpenSSL.cmake

### ISSUE THREAD

**Issue by bocajspear1** [FreeRDP/FreeRDP#2168]
When running CMake on latest master, in cmake/FindOpenSSL.cmake, the value of  ${MSVC_RUNTIME} is not defined resulting in

```
CMake Error at cmake/FindOpenSSL.cmake:65 (if):
  if given arguments:

    "STREQUAL" "static"

  Unknown arguments specified
Call Stack (most recent call first):
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:524 (find_feature)

```

cmake version 2.8.12.2
Mingw version: 3.1.0-1
3.13.0-37-generic Ubuntu x86_64

**Comment by akallabeth** [comment]
Should be fixed on current master.
