### ISSUE TITLE
graphic bug in colum 119 in notepad 

### ISSUE THREAD

**Issue by mvogt1** [FreeRDP/FreeRDP#2173]
Hello,

this bug can be reproduced in notepad.
It is reproducible, but it needs a bit of experiments / patience.

Start xfreerdp (tested git today) with:
- ./xfreerdp -sec-nla /w:1280 /h:1024 /v:<host>
- start notepad and maximise it
- make sure Format->WordWrap is off
- write three lines with more words/letters than the window can handle
- set cursor to line "2" column 119 (!) and mark this position with X
- enable WordWrap
- now put cursor on the X (WordWrap put the cursor to begin of the text)
- type some letters remove them with backspace
- repeat it a few time

You should see around the position X that the letters are not printed correctly.
If you have the error on the second line, you can put the cursor on the
top line (same column) too, and adding/deleting a letter on the position should
give a similar graphic error as inl line "2" .

This is true for xfreerdp:
- git
- 1.1
- 1.2
- 0.8.6 works

regards,

Martin

![bug_line119](https://cloud.githubusercontent.com/assets/640800/4792060/5704195a-5de3-11e4-82dd-8857f1d3bcf1.jpg)

**Comment by nfedera** [comment]
@mvogt1 can you reproduce the issue if you add the -glyph-cache command line parameter ?

**Comment by mvogt1** [comment]
The option -glyph-cache removes the "bug".
I have verified that current git, still has the problem, and then started with -glyph-cache.

==> Problem gone

At least I cannot reproduce it in "some" tries. Usually it needs 1-3 "tries".

**Comment by akallabeth** [comment]
Closing, as `glyph-cache` is not required for operation and part of a (hopefully) soon to be phased out revision of RDP
We've disabled it by default and marked it `experimental`
