### ISSUE TITLE
Smart Card redirection in OS X 10.10 Yosemite

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#2184]
Smart Card redirection seems to be broken on OS X 10.10 Yosemite.

When trying to connect using `/smartcard` the session comes up and works for a split second, then crashes with a segfault.

Here's the generated output:

```
[18:45:34:290] [9701:188960768] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[18:45:34:291] [9701:188960768] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[18:45:34:409] [9701:189497344] [INFO][com.freerdp.channels.rdprd.client] - Loading device service smartcard (static)
[18:45:35:663] [9701:189497344] [INFO][com.freerdp.channels.rdprd.client] - registered device #1: SCARD (type=32 id=1)
[18:45:35:786] [9701:190570496] [ERROR][com.winpr.smartcard] - PCSC_GetReaderAliasFromName: Gemalto PC Twin Reader
[18:45:35:786] [9701:190570496] [ERROR][com.winpr.smartcard] - PCSC_GetReaderAliasFromName: 
[18:45:35:864] [9701:190570496] [ERROR][com.winpr.smartcard] - PCSC_GetReaderAliasFromName: Gemalto PC Twin Reader
[18:45:35:864] [9701:190570496] [ERROR][com.winpr.smartcard] - PCSC_GetReaderAliasFromName: 
[18:45:35:075] [9701:210829312] [ERROR][com.winpr.smartcard] - PCSC_GetReaderAliasFromName: (nil)
Segmentation fault: 11
```

The last 5 lines are debug messages I added in `PCSC_GetReaderAliasFromName` (smartcard_pcsc.c): `WLog_ERR(TAG, "PCSC_GetReaderAliasFromName: %s", namePCSC);`

When I run my FreeRDP client from Xcode I can see that the offending method is a `strlen` call in `PCSC_ConvertReaderNameToWinSCard`. See attached screenshot for details.

![capturfiles_12](https://cloud.githubusercontent.com/assets/186198/4887596/d99a3960-6385-11e4-8cf8-755ba70ad6a9.png)

**Comment by sephiroth4** [comment]
I don't know if anything has changed, but smart card functions with
RoyalTSX now.

**Comment by lemonmojo** [comment]
@sephiroth4 On Yosemite? Can you actually use the smart card or is it just visible to the system? I was always able to get the card to be recognized by the system but when trying to access it I get the previously mentioned SCardGetAttrib error.

**Comment by sephiroth4** [comment]
Just an update on this, the most recent build broke smart card again :(
 RoyalTSX Beta 2.0.0.26 and FreeRDP 20.0.022 plugin. It was working
PERFECTLY before the updates today.  Thanks again!

**Comment by lemonmojo** [comment]
@sephiroth4 Yep, I recently updated FreeRDP to master and am now having the original issue again. Have to do some more debugging though.

**Comment by lemonmojo** [comment]
@Vinche59 Hey! Any update on this?

**Comment by lemonmojo** [comment]
Update: Just tested Smart Card redirection on OS X 10.11 El Capitan DP and at least for me it's back to working again!

**Comment by lemonmojo** [comment]
On the other side, [this](http://ludovicrousseau.blogspot.fr/2015/06/pcsc-framework-removed-in-mac-os-x-1011.html) isn't very promising.... Although I cannot confirm the removal in my installation. The framework is still there under /System/Library/Frameworks/PCSC.framework.

**Comment by lemonmojo** [comment]
Just wanted to give anyone on this thread a short update regarding PCSC on El Capitan.
The framework is luckily not going anywhere. See this post for more info: http://ludovicrousseau.blogspot.fr/2015/06/pcsc-framework-will-stay-in-mac-os-x.html

**Comment by sconstantine** [comment]
Any progress or updates to smart card redirection?

**Comment by sephiroth4** [comment]
It's been working for me in version 2.2.0.1000 (stable)

**Comment by sconstantine** [comment]
Still crashes upon connection when set to redirect the smart card; running Royal TSX and Remote Desktop (FreeRDP) v2.2.1.1 beta with SCR3310 USB Smart Card Reader.

Suggestions or new FreeRDP plugin beta to try?

**Comment by sephiroth4** [comment]
Yoooo!

I'm using the same beta version and the omnikey 3121 usb smart card
reader.  Might want to try a different reader??

**Comment by sconstantine** [comment]
Nailed it; purchased the Omni 3021 and it works with Felix's custom LMFreeRDPClient via OS X 10.11.2.  Still broken within Royal TSX and FreeRDP v2.2.1.1 tho

**Comment by tburgin** [comment]
Link to LMFreeRDPClient?

**Comment by lemonmojo** [comment]
@tburgin It's an app that we at Lemon Mojo use internally to test new FreeRDP releases/features/bugfixes on OS X. Every now and then we send it to customers if there's a certain bug or feature that needs to be tested outside of our lab but it's not publicly available.
If you're a Royal TSX customer you can contact us via our [support portal]( http://support.royalapplications.com/). thx!

**Comment by sconstantine** [comment]
@lemonmojo, any knowledge of progress or updates to smart card redirection support with OS X?  Thx!

**Comment by sephiroth4** [comment]
Yo sconstantine, 

I just tried my smartcard this morning to a host and it works fine with osx 10.11.3, royal tsx 2.2.2.1000, and freerdp 2.2.1.1, omnikey 3121.

**Comment by sconstantine** [comment]
It seems to have 'partial' function, in that the Windows host recognizes a reader now, however unable to query card status.  For example, ActivClient and Remote Desktop clients sit at 'checking status'  indefinitely when trying to use for logon or state query.

Env: OS X v10.11.4 and FreeRDP plugin v3.0.0.8 (with Royal TSX v3.0.0.11 beta)

**Comment by mindisfree** [comment]
Can I ask how you got Royal TSX to try smart card with freerdp? I have same version of Royal TSX and FreeRDP plugin and using activeclient as well.

**Comment by sconstantine** [comment]
I only require redirection to use my smart card from within the connected session (vs initial credential auth to the remote session) so I am choosing the checkbox for "Smart Cards" under the redirection properties of the connection.

**Comment by mindisfree** [comment]
@sconstantine Yeah I did the check box for smart cards but it still want my login and it should be grabbing the smart card login and asking for PIN. Did you have to do anything more than the check box in Royal TSX?

**Comment by sephiroth4** [comment]
Edit the RDC settings.

On the connection settings:
**Common -> Credentials**
"Do not use any credentials"
**Advanced -> Advanced -> Authentication tab**
deselect "Network Level Authentication (NLA) check box
**Advanced -> Redirection**
select "Smart Cards" check box
 Save and merge try to connect with smart card after hovering over switch user (on server 2k8 anyway :))

**Comment by mindisfree** [comment]
So I get an error right away. I set up like listed above.
The connection failed. (Error Code: CONNECTERROR)

**Comment by bmiklautz** [comment]
A lot of fixes related to smart card are on master now. I've tested on macOS High Sierra and it worked so far for me. I'll close the issue. Please re-open or create a new one of you still see this problem.
