### ISSUE TITLE
ERRINFO_DECRYPT_FAILED (0x00001192) and close the application

### ISSUE THREAD

**Issue by LuchoLopez** [FreeRDP/FreeRDP#2190]
Hi!! I compiled FreeRDP from master branch.

When I connect to my Windows Server 2003 I can use the rdpclient for a while, but after some minutes/seconds ("randmonly") my computer close the connection...

lucho@pcluis:~$ xfreerdp --version
This is FreeRDP version 1.2.0-beta1 (git n/a)

---

Here is what I run:
xfreerdp /clipboard /t:'PC Testing' /u:administrador /sec-rdp /f /toggle-fullscreen /drive:transferencia,/home/lucho/Público/Transferencia -glyph-cache /v:192.168.39.1 /p:xxxxxxxxx

Here is the log:
[18:00:53:691] [5514:5518] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[18:00:53:691] [5514:5518] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[18:00:53:691] [5514:5518] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[18:00:53:705] [5514:5518] [INFO][com.freerdp.core] - FIPS Compliant encryption level.
[18:00:53:753] [5514:5519] [INFO][com.freerdp.channels.rdprd.client] - Loading device service drive (static)
[18:00:54:955] [5514:5519] [INFO][com.freerdp.channels.rdprd.client] - registered device #1: transferencia (type=8 id=1)

[18:00:58:748] [5514:5518] [ERROR][com.freerdp.core] - ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
(b) Session key creation using Standard RDP Security mechanisms (section 5.3.5) failed.
[18:00:58:748] [5514:5518] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

Here is a tcpdump log to see who is sending the last package:
lucho@pcluis:~$ sudo tcpdump -lni eth0 host 192.168.39.1 and port 3389 and 'tcp[13] & 1 == 1'
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
18:00:53.685033 IP 192.168.39.112.33006 > 192.168.39.1.3389: Flags [F.], seq 305757313, ack 2045800113, win 229, options [nop,nop,TS val 3156675 ecr 113953270], length 0
18:00:53.686743 IP 192.168.39.112.33007 > 192.168.39.1.3389: Flags [F.], seq 203160576, ack 1935378508, win 229, options [nop,nop,TS val 3156676 ecr 113953270], length 0

---

Many thanks!! Freerdp is a great tool! I'm very happy with it, but this issue is making my work harder...

(sorry if my english is is not good)

**Comment by akallabeth** [comment]
Is this still an issue (or is it a client issue at all?)

**Comment by lemonmojo** [comment]
@akallabeth This issue is actually as old as FreeRDP itself. Many customers reported it to me and I've seen it happen myself from time to time. Unfortunately it's not easily reproducible and I haven't yet found a way to reproduce it on demand.
The last customer report mentioning this issue was in November of 2017, probably because Server 2003/XP is finally on its way out...
Anyway, you should be able to reproduce it when working for many hours inside a 2003 session. Sometimes I've seen it happen a few seconds after connecting, sometimes it takes hours to show up.

**Comment by akallabeth** [comment]
@lemonmojo read somewhere that it may be a fastpath related bug, and `-fast-path` works around those buggy server implementations. so can anyone confirm this?

**Comment by lemonmojo** [comment]
@akallabeth Yes, I'm pretty certain it's a server side issue. However, I have never seen it using MS's own clients. To be honest, at this point, in 2018 I don't care much. ;-)

**Comment by lemonmojo** [comment]
Also see https://github.com/FreeRDP/FreeRDP/issues/433.

**Comment by zlaxy** [comment]
Same issue with Windows 2008 SP2 32 bit sessions. With latest freerdp2-x11_2.0.0~git201805221422-0+remmina201805230936.re90184c.d29dd283~ubuntu17.10.1_armhf on Armbian.
```
device service drive [USB] (static)
[11:02:50:934] [31221:31227] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: USB (type=8 id=1)
[12:32:46:986] [31221:31222] [INFO][com.freerdp.core] - ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
(b) Session key creation using Standard RDP Security mechanisms (section 5.3.5) failed.
```
This error occurs in a random, sometimes several times a day.

Is there any known solution?

**Comment by zlaxy** [comment]
> Is there any known solution?

It looks like running session with `-fast-path` parameter solves this problem in my case. 1,5days of stable working now.

**Comment by PadreAdamo** [comment]
*POSSIBLE SOLUTION* Oddly enough "Disabled Fast-Path" is so far working for me over the past 30 minutes.

**Comment by apath001** [comment]
I meet this issue too, it occurs in a random, sometimes several times an hour. My RDP Server is Win7 Ultimate SP1, 64bit.  Sometimes server send this pdu(ERRINFO_DECRYPT_FAILED, 0x00001192) before disconnection, sometimes server just cut connection directly without any notification.  I don't t think the  parameter -fast-path can slove this issue in my case.

**Comment by akallabeth** [comment]
@apath001 Could you post your command line? This issue is only affecting very old RDP protocol methods, so you seem to have an interesting one ;)

**Comment by apath001** [comment]
@akallabeth My FreeRDP is an old version  (12/2014). Is it the reason? Newer version has sloved this issue?  and I use FreeRDP in RemoteApp mode:  /v:server ip /u:username /p:password /bpp:32 /app:"||appname". My RDP Server is Win7 Ultimate SP1, 64bit.

**Comment by akallabeth** [comment]
@apath001 then I'd try the current nightlies. Adding `/rfx` for windows 7 could also help (as well as `/gfx:avc444` or `/gfx` for builds without h264)
