### ISSUE TITLE
License connection sequence aborted

### ISSUE THREAD

**Issue by muflone** [FreeRDP/FreeRDP#2196]
Hi

I'm unable to connect to any Windows 2003 SP2 server running Terminal Services with no additional security, no NLA, no SSL certificates.

```
$ xfreerdp  /v:192.168.41.3 /cert-ignore -sec-nla -nego -sec-tls
[12:30:19:189] [23313:-1170782464] [ERROR][com.freerdp.core.connection] - license connection sequence aborted.
[12:30:19:190] [23313:-1170782464] [ERROR][com.freerdp.core] - freerdp_set_last_error 0x2000D
```

The same command works fine when I try to connect to a Windows 2012 Server.

Testing environment:
- Arch Linux x64_64 (package freerdp-git)
- xfreerdp version: This is FreeRDP version 1.2.0-beta1 (git 6cd55a5)
- Destination host: many Windows 2003 SP2 servers

The previous freerdp 1.1.0-beta1 works fine with the same command line.

**Comment by sitano** [comment]
Can't connect to the Windows Server 2012, still getting license connection sequence abort:
https://gist.github.com/sitano/bdf2ce7f2af949c960204689df6e77b6 .

FreeRDP /version: `This is FreeRDP version 2.0.0-dev (git 3586e33)`

**Comment by olegon-ru** [comment]
Can't connect to Windows 2008R2, because of Terminal licensing server is disconnected. :(
But rdesktop and mstsc.exe connected without any problem (with notification in tray only).
/admin solved the problem, but I would like to connect without /admin, if I can do it by the same script...

**Comment by BlackBlade1632** [comment]
I simply solved it using sudo.

**Comment by akallabeth** [comment]
@BlackBlade1632 please do not post such advice, using `sudo` with `FreeRDP` is a sign you do something wrong.

**Comment by BlackBlade1632** [comment]
@akallabeth I never used sudo until this happend. I started using sudo because stopped working.
