### ISSUE TITLE
RDPEUDP DTLS handshake fail

### ISSUE THREAD

**Issue by chance-tsai** [FreeRDP/FreeRDP#2218]
I want to create udp channel to work with server.
Lossy UDP need to use SSL_CTX_new(DTLSv1_client_method());
I use BIO_new_bio_pair to get SSL handshake information, and add FEC header, then send to server.
But Message Analyzer can't decode DTLS packet, which I generated. Server didn't reply dtls packet.
What's procedure I need to do for DTLS handshake?
ctx=SSL_CTX_new(DTLSv1_client_method());
ssl = SSL_new(ctx);
BIO_new_bio_pair(internel_bio,BUFF_LEN,app_bio,BUFF_LEN);
ssl_bio=BIO_new(BIO_f_ssl());
SSL_set_connect_state(ssl);
SSL_set_bio(ssl,internel_bio,internel_bio);
BIO_set_ssl(ssl_bio,ssl,BIO_NOCLOSE);

SSL_do_handshake(ssl);
waitread=BIO_ctrl_pending(app_bio);	
readbytes = BIO_read(app_bio, s->buffer, waitread); 

//add FEC header

//udp sendto

**Comment by hardening** [comment]
IIRC you also need to set the preshared secret on the DTLS.
Anyway I'm closing the issue as it's not something about FreeRDP.
