### ISSUE TITLE
numlock out of sync

### ISSUE THREAD

**Issue by mfernau** [FreeRDP/FreeRDP#2219]
I've sometimes the problem that my numlock-state is not correctly synced between me and the target host. 
It seems that mainly windows 2003 server as the target host is affected and in this case the numlock sometimes behaves like the opposite from my local state.

I use debian jessie with freerdp 1.1.0~git20140921.1.440916e+dfsg1-2+b1

**Comment by Vladimir-csp** [comment]
+1. Numlock state should be somehow double-checked on connect and enforced.

**Comment by hardening** [comment]
@mfernau @Vladimir-csp any chance that you try with latest master (using the pre builds or compiling yourself) ?

**Comment by Vladimir-csp** [comment]
I will try to rebuild debian package with current master sources.

**Comment by Vladimir-csp** [comment]
It seems that debian freerdp package build rules are outdated, lots of failed tests.
I will try to build freerdp without a package later.

**Comment by bmiklautz** [comment]
@Vladimir-csp you can give our nightly packages a try https://ci.freerdp.com/job/freerdp-nightly-binaries/

**Comment by Vladimir-csp** [comment]
No packages for Stretch or Sid there. BTW, site's cert has expired yesterday.
Anyway with latest master, numlock sync seems to work properly, including when reconnecting to existing session. #2104 also seems to be fixed.

**Comment by bmiklautz** [comment]
@Vladimir-csp thanks for the feedback. You might have hit the server shortly before we updated the certificate ;). I don't think we will create packages for sid but stretch is definitely on my todo list.

@mfernau if you still hit by this problem could you also verify that it is fixed for you with the latest master builds (or nightly packages https://ci.freerdp.com/job/freerdp-nightly-binaries/?)

**Comment by bmiklautz** [comment]
@mfernau any update on this from your side?

**Comment by mfernau** [comment]
I've just updated to the nightly builds and it looks promising. No async state so far!

**Comment by bmiklautz** [comment]
@mfernau thank you for the feedback. I'll close the issue. Please re-open if the problem still exists.
