### ISSUE TITLE
AudioQualityMode Command-Line Switch Not Accepted

### ISSUE THREAD

**Issue by vddsd** [FreeRDP/FreeRDP#2230]
I'm using version 1.2 of FreeRDP and I wish to utilize the AudioQualityMode command-line switch in order to increase the audio quality. The 'dynamic' audio quality (the default setting) produces 'thinny' sounding audio and is laggy. The same thinny sounding audio is produced by the Windows client, but when the client-side audioqualitymode:i:2 parameter is passed, the audio quality is greatly enhanced.

Is this a supported parameter in FreeRDP? If so, how so I use it? If not, any chance it can be supported in a later release?

Thanks!

**Comment by akallabeth** [comment]
`2.0.0-rc3` supports the setting.
