### ISSUE TITLE
freerdp-1.0.1-99.git - centos6/6.5/6.6 -  incorrect & Incomplete  BuildRequires - patch attached

### ISSUE THREAD

**Issue by hvenzke** [FreeRDP/FreeRDP#2249]
This patch fix the centos el6 spec file BuildRequires / Requires

<pre>
--- freerdp-1.0.1-99.git.el6.src.spec-orig      2014-11-27 02:23:55.000000000 +0100
+++ freerdp.spec        2014-12-04 12:22:32.000000000 +0100
@@ -34,7 +34,6 @@
 %if 0%{?fedora}%{?fedora_version}
 BuildRequires:  alsa-lib-devel
 %endif
-BuildRequires:  pulseaudio-libs-devel
 BuildRequires:  libX11-devel
 BuildRequires:  libXext-devel
 BuildRequires:  libXinerama-devel
@@ -43,6 +42,31 @@
 BuildRequires:  libXcursor-devel
 BuildRequires:  libxkbfile-devel
 %endif
+%if 0%{?centos_version}
+BuildRequires: pulseaudio-libs-devel
+BuildRequires: pulseaudio-libs
+BuildRequires: alsa-plugins-pulseaudio
+BuildRequires: alsa-lib
+BuildRequires: alsa-lib-devel
+BuildRequires: libX11-devel
+BuildRequires: libXau-devel
+BuildRequires: libxcb-devel
+BuildRequires: xorg-x11-proto-devel
+BuildRequires: libxkbfile-devel
+BuildRequires: libXinerama-devel
+BuildRequires: libXcursor-devel
+BuildRequires: libXv-devel
+Requires: pulseaudio-libs
+Requires: alsa-plugins-pulseaudio
+Requires: alsa-lib
+Requires: libX11
+Requires: libXau
+Requires: libxcb
+Requires: libxkbfile
+Requires: libXinerama
+Requires: libXcursor
+Requires: libXv
+%endif

 #common deps
 BuildRequires:  cups-devel

</pre>

**Comment by hardening** [comment]
If someone has the opportunity to test it would be great to include that patch.

**Comment by bmiklautz** [comment]
The top level spec file was removed altogether since it wasn't maintained anymore.
However we do have a spec file we build the nighties from but this doesn't support centos.
