### ISSUE TITLE
xfreerdp rendering issues with rail plugin

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#2250]
![screenshot from 2014-12-03 17 30 44](https://cloud.githubusercontent.com/assets/1051384/5298579/03d51920-7bbe-11e4-83bf-06fa7f426a59.png)
Hey,

I'm facing with rendering issues on xfreerdp (1.2.0-beta1) when using rail plugin. I'm using Fedora 21 and connecting to Windows Server 2008 SP2 if applicable. It seems to be working correctly on Fedora 20 with xfreerdp 1.0.2. 

There is also screencast showing what is wrong:
http://webmshare.com/play/1Lyma

There are black "border" when I move/resize window. For example it isn't possible to click on close button where I see it if there are black "borders", but I have to click on right top corder where it should be. Also there are problems with "subwindows". You can see it in the screencast, changes I made in Font dialog are applied, but not visible...

Can I provide some debug output or help somehow with solving this issue?

Regards

Ondrej

**Comment by DejavuDmitry** [comment]
Another bugs in the last GIT- version. Awakecoding, please tell us a little information about the work on this problem ...
╚⋗ $ ~/build/FreeRDP/client/X11/xfreerdp -version
This is FreeRDP version 1.2.0-dev (git df79781)
![2015-01-13-200637_1024x768_scrot](https://cloud.githubusercontent.com/assets/9697445/5725995/8a0f13b2-9b60-11e4-8d37-0d3d92bd07d1.png)
![2015-01-13-200543_1024x768_scrot](https://cloud.githubusercontent.com/assets/9697445/5725996/8a10bb7c-9b60-11e4-86a3-ac3895c3e6fd.png)

**Comment by akallabeth** [comment]
Seems fixed on current master,
reopen if still reproducible.
