### ISSUE TITLE
question / feature request:  .conf for defaults

### ISSUE THREAD

**Issue by meoso** [FreeRDP/FreeRDP#2254]
is there a .conf file that i can set defaults?  for instance i always want +clipboard (and current remmina seems not to handle it)
if not, can this be a new feature?

**Comment by masaeedu** [comment]
Is it possible to read a simple ini file from an appropriate XDG config directory instead of having to alias `xfreerdp`?

**Comment by akallabeth** [comment]
@masaeedu currently not, but pull requests are welcome.

**Comment by meoso** [comment]
OMG this is so old.
I no longer seem to have issue.  but this was my solution at one time (no longer):
https://gist.github.com/meoso/9b58f68736bc438c5ce00a9118891e99
maybe you can play/customize. basically i put all my hosts/params in a csv file and only rdp'd from cli.
 i retired this method and use remmina these days
