### ISSUE TITLE
The above X.509 certificate could not be verified

### ISSUE THREAD

**Issue by zhibudao** [FreeRDP/FreeRDP#2260]
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@           WARNING: CERTIFICATE NAME MISMATCH!           @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
The hostname used for this connection (192.168.1.103) 
does not match the name given in the certificate:
zhenhua-PC
A valid certificate for the wrong name should NOT be trusted!
Certificate details:
    Subject: CN = zhenhua-PC
    Issuer: CN = zhenhua-PC
    Thumbprint: 57:db:9e:dd:04:d1:c3:b8:63:47:f4:f8:1c:55:b4:a8:98:c7:67
The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the documentation on how to create local certificate store for a private CA.
Do you trust the above certificate? (Y/N) y
SSL_read: Failure in SSL library (protocol error?)
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
zhenhua@ubuntu:~$ ^C
zhenhua@ubuntu:~$ /usr/local/bin/xfreerdp 192.168.1.103 -u zhenhua-PC -f -no nla 
connected to 192.168.1.103:3389
Password: 
SSL_read: Failure in SSL library (protocol error?)
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.

How could I solve this problem？

**Comment by informatimago** [comment]
This is not an issue with FreeRDP, but as the error message clearly states, this is an issue with your certificate.  When you generate your own certificate, you must concatenate the CA chain, up to a known CA, or your self-signed CA root.

See for example: https://raymii.org/s/tutorials/OpenSSL_command_line_Root_and_Intermediate_CA_including_OCSP_CRL%20and_revocation.html
