### ISSUE TITLE
does not grok DNS round robin setups

### ISSUE THREAD

**Issue by Zugschlus** [FreeRDP/FreeRDP#2264]
When I try connecting to a host name which resolves to two IP addresses, I keep getting host key mismatches if both hosts on those IP addresses have different host keys.

Putting two lines with the same host name into known_hosts does not help, only the first one works. Putting two keys on the same line makes none work.

A possible solution would be to use and document either method to have multiple host keys in known_hosts.

Greetings
Marc

**Comment by hardening** [comment]
@bmiklautz perhaps we should close the issue ?

**Comment by bmiklautz** [comment]
@hardening I kept it open since I thin thought known_hosts could use some improvements like support multiple hosts and/or ports. But we can close this one and create a feature issue.

**Comment by akallabeth** [comment]
We have `/cert:fingerprint` now to provide accepted fingerprints.
