### ISSUE TITLE
RDP clients render black when freerdp-shadow server runs on Windows 7.

### ISSUE THREAD

**Issue by siraj** [FreeRDP/FreeRDP#2267]
FreeRDP server isn't working like on Linux when I run it on windows. not sure if this the current state of rendering code on windows or a bug. 

How to reproduce : 
1.) compile and run freerdp-shadow on windows from git. 
2.) connect to the server from another pc using any RDP client.

Expected:
Use should be able to control the remote desktop with a RDP client. and renders the remote desktop.

Observed:
Mouse Events and keyboard events are received on the server side.
Client doesn't render the remote desktop only a black background.

<code>c:\rdp\bin>freerdp-shadow.exe
[00:35:36:634] [4544:4548] [ERROR][com.freerdp.server.shadow.win] - IRDPSRAPISha
ringSession::put_ColorDepth() failure: 0x80070057
[00:35:36:634] [4544:4548] [INFO][com.freerdp.server.shadow.win] - width: 0 heig
ht: 0
[00:35:36:650] [4544:4548] [INFO][com.freerdp.core.listener] - Listening on :::3
389
[00:35:36:650] [4544:4548] [INFO][com.freerdp.core.listener] - Listening on 0.0.
0.0:3389
</code>

Other:
tested with Microsoft visual studio express 2010 (SP1), and 2012

**Comment by akallabeth** [comment]
Outdated, create a new issue if still relevant.
