### ISSUE TITLE
Printer redirection driver defaults to "MS Publisher Imagesetter" even when specified

### ISSUE THREAD

**Issue by hydrajump** [FreeRDP/FreeRDP#2269]
Using master branch and compiling on Mac OS X 10.9.5 with the following,

```
cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" \
"-DWITH_CUPS=ON" . \
&& make
```

The following tests were done connecting to a vanilla Windows Server 2012 R2 server. I've also tested with Windows 7 and Windows XP and got the same results.

## Reference printer drivers installed by default

Before **any** printer redirection the following printer drivers are present on the server.
![screen shot 2014-12-10 at 18 34 49](https://cloud.githubusercontent.com/assets/6806679/5381850/6cbce8d2-80a5-11e4-8b41-dc74aaf9a822.png)

## Test 1 - Printer Redirection without specifying driver

```./MacFreeRDP /printer:HP_LaserJet_P3010_Series```

In this case FreeRDP uses the "MS Publisher Imagesetter" driver, which gets installed automatically on the server.

![screen shot 2014-12-10 at 18 36 06](https://cloud.githubusercontent.com/assets/6806679/5381877/abe9f2b6-80a5-11e4-9b5c-968c15737f79.png)

## Test 2 - Printer Redirection specifying driver

```./MacFreeRDP /printer:HP_LaserJet_P3010_Series,"HP LaserJet P3011/P3015 PCL6 Class Driver"```

In this case FreeRDP causes two drivers to be installed: "MS Publisher Imagesetter" and the specified driver "HP LaserJet P3011/P3015 PCL6 Class Driver".

However, the "MS Publisher Imagesetter" driver is the one used for the redirected printer and **not** the specified HP printer driver.

![screen shot 2014-12-10 at 19 57 38](https://cloud.githubusercontent.com/assets/6806679/5382022/da060a9e-80a6-11e4-83a6-2787b58508cd.png)

## Workaround

By hardcoding the correct printer driver I have got printer redirection working as intended, e.g. the correct driver is installed and set for the printer.

This is done by changing the following line,
https://github.com/FreeRDP/FreeRDP/blob/master/channels/printer/client/printer_cups.c#L228

```
diff --git a/channels/printer/client/printer_cups.c b/channels/printer/client/printer_cups.c
index 0d6fcbe..5507031 100644
--- a/channels/printer/client/printer_cups.c
+++ b/channels/printer/client/printer_cups.c
@@ -225,7 +225,7 @@ static rdpPrinter* printer_cups_new_printer(rdpCupsPrinterDriver* cups_driver, c
        cups_printer->printer.id = cups_driver->id_sequence++;
        cups_printer->printer.name = _strdup(name);
        /* This is a generic PostScript printer driver developed by MS, so it should be good in most cases */
-       cups_printer->printer.driver = "MS Publisher Imagesetter";
+       cups_printer->printer.driver = "HP LaserJet P3011/P3015 PCL6 Class Driver";
        cups_printer->printer.is_default = is_default;
 
        cups_printer->printer.CreatePrintJob = printer_cups_create_printjob;
```

## Solution

Ideally when specifying a specific printer driver, e.g.

```./MacFreeRDP /printer:HP_LaserJet_P3010_Series,"HP LaserJet P3011/P3015 PCL6 Class Driver"```

FreeRDP would a) not install "MS Publisher Imagesetter" and b) set the printer driver to that which was specified

Also, although I have used `MacFreeRDP` for my testing I get the exact same results when just using `xfreerdp`.

**Comment by i92guboj** [comment]
Is this officially solved? I am still getting this problem and I have been hitting against the wall for weeks, thinking that it was Windows 2012r2 acting up again as it always does, until I thought "oh well lets look somewhere else".

Is there a proper way to work around this issue without having to recompile a custom  client for each pos workstation?

**Comment by DejavuDmitry** [comment]
Also not work from the first run of the instance. Here is screencast of my tries to redirect driver:
[![IMAGE ALT TEXT](http://img.youtube.com/vi/ZBJx65Kd52Q/0.jpg)](https://www.youtube.com/watch?v=ZBJx65Kd52Q "FreeRDP Printer redirection driver  issue")

**Comment by ForumSchlampe** [comment]
Why isnt this fix in the main branch?

**Comment by hardening** [comment]
@ForumSchlampe because it was just a fix to test, not the real fix...

**Comment by ForumSchlampe** [comment]
@hardening 
yea but the fix works so far and doesnt break anything or did i miss something?
