### ISSUE TITLE
Chinese character file name for Drive redirection.

### ISSUE THREAD

**Issue by hyacinthes** [FreeRDP/FreeRDP#2274]
Hi all,

There is a strange phenomenon. I can rename a folder or file name with Chinese character with Drive redirection. Then I plug the USB storage in other win8 PC, the folder or file name would be mojibake.

Then I plug the USB storage back again to system and run RDP with Drive redirection, I can see the folder or file name with correct Chinese character.

Any help is very appreciate.

**Comment by akallabeth** [comment]
Drive redirection has been rewritten.
Reopen if still an issue.
