### ISSUE TITLE
Clipboard Redirection Is Stripping All But One Character

### ISSUE THREAD

**Issue by reverendj1** [FreeRDP/FreeRDP#2287]
After playing around more with the latest version, it appears the fix for this bug https://github.com/FreeRDP/FreeRDP/issues/2209 has caused another issue. When copying from Linux to Windows, only the first character is copied.

Version:

```
xfreerdp --version
This is FreeRDP version 1.2.0-dev (git 3b332e7)
```

I use this script to install FreeRDP onto my Ubuntu 14.04 desktops (I've had the same results with several):

```
#!/bin/bash
apt-get install -y build-essential git-core cmake libssl-dev libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxdamage-dev libxv-dev libxkbfile-dev libasound2-dev libcups2-dev libxml2 libxml2-dev libxrandr-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libxi-dev libavutil-dev libavcodec-dev libcunit1-dev libdirectfb-dev xmlto doxygen libxtst-dev
git clone git://github.com/FreeRDP/FreeRDP.git /tmp/FreeRDP
cd /tmp/FreeRDP
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .
make
make install
echo "/usr/local/lib/freerdp" > /etc/ld.so.conf.d/freerdp.conf
ldconfig
```

I then connect from my Ubuntu machine to a Windows machine (I've tried this on several Windows Server 2003 and 2008 servers), like so:

```
xfreerdp +clipboard /v:$MY_WINDOWS_SERVER /cert-ignore
```

Now, say I copy the text "Amazon" in Ubuntu. When I paste it into Windows, it shows up as "A". Copying from Windows to Ubuntu works fine though.

**Comment by reverendj1** [comment]
@awakecoding I'm just curious, do you know when this might get merged with the master? Thanks again.

**Comment by nfedera** [comment]
@awakecoding there is a new issue (similar to issue #2209) when copying from windows calculator to local (linux) libre office writer:
1.) in rdp session open calc, enter the number  12345 and ctrl+c
2.) on client side open libre office and do a ctrl-v and you get 12345########################...

**Comment by akallabeth** [comment]
Copy paste of text is working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef from linux to windows and vice versa.
Reopen if you still experience this bug.

**Comment by Defenso-QTH** [comment]
I am affected by this on 3.9.0.
Host: FreeBSD 14.2
Guest: Windows 11

Same with or without `+clipboard`.

**Comment by Defenso-QTH** [comment]
@akallabeth I do not know how to reopen the ticket, it seems to stay closed after my comment. Should I open a new issue?

**Comment by akallabeth** [comment]
@Defenso-QTH retest with master branch.

**Comment by akallabeth** [comment]
> I just tried again, and now it works. I think `+clipboard` caused that behaviour, and then it was only fixed after I rebooted. Just restarting the session without `+clipboard` was not enough.

does not make any sense.
the option is on by default, no difference between none and `+clipboard`
