### ISSUE TITLE
freerdp should store by ip/port the key and not only by ip

### ISSUE THREAD

**Issue by allan-simon** [FreeRDP/FreeRDP#2288]
Our company has several server  with one public ip address so we have 

IP:portA -> sever A
IP:portB ->  server B

and freerdp will refuse to connect to the second , as he think server B is not legit

**Comment by realdreams** [comment]
I ran into this issue with Remmina. The error message does not say why. The workaround is to create different FQDNs for each connection, which is really stupid.

**Comment by akallabeth** [comment]
Already implemented.
