### ISSUE TITLE
USB device redirection library "urbdrc" not found.

### ISSUE THREAD

**Issue by shweng** [FreeRDP/FreeRDP#2289]
FreeRDP-1.2 master git USB device redirection function failed due to lack of urbdrc library liburbdrc-client.so.
My envirorment:
[root@localhost home]# xfreerdp --version
This is FreeRDP version 1.2.0-dev (git 3b332e7)
client OS:
CentOS 7 x86_64  /Fedora 18 x86_64bit  
command:
xfreerdp /u:administrator /p:password /usb:id:0930:6544 /network:lan /v:192.168.1.152
and
xfreerdp /u:administrator /p:password /dvc:urbdrc,id,dev:0930:6544 /network:lan /v:192.168.1.152
could not redirect usb storage stick device to windows7 guest.
there is xfreerdo error message:
[ERROR][com.winpr.library] - LoadLibraryA: /usr/local/lib64/freerdp/liburbdrc-client.so: cannot open shared object file: No such file or directory
[10:29:06:622] [7166:-215566592] [ERROR][com.freerdp.channels.dvcman.client] - ChannelId 9 not found!
[10:29:06:637] [7166:-215566592] [ERROR][com.freerdp.channels.dvcman.client] - ChannelId 10 not found!

code is git from FreeRDP-master.
CMAKE param follow the reference  https://github.com/FreeRDP/FreeRDP/issues/864.
-DWITH_PCSC=ON -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DWITH_CHANNELS=ON -DSTATIC_CHANNELS=OFF

there is message from Cmake:
.............
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- FreeRDP GIT
-- Finding recommended feature XKBFile for X11 keyboard (X11 keyboard file extension)
--     Disable feature XKBFile using "-DWITH_XKBFILE=OFF"
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding device channel client server "serial": Serial Port Virtual Channel Extension
-- Adding dynamic channel client server "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding device channel client server "parallel": Parallel Port Virtual Channel Extension
-- Adding device channel "printer": Print Virtual Channel Extension
-- Adding dynamic channel client server "rdpei": Input Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding dynamic channel client server "tsmf": Video Redirection Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding dynamic channel client server "urbdrc": USB Devices Virtual Channel Extension
-- libudev stable: 1
-- Found UDev: /usr/lib64/libudev.so
--  include: /usr/include
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib64/libusb.so
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding device channel client server "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- FreeRDP GIT
-- Finding required feature XShm for X11 shared memory (X11 shared memory extension)
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
..........................................
we could found cmake attempt to build urbdrc library "urbdrc",after make && make install successful.I could found all channel library are generated except urbdrc channel library file liburbdrc-client.so.
please help to investiagate this issue.
thanks in advance.

**Comment by masalla** [comment]
Hi,
have the same issue here.
Im using freerdp 1.1 and compiled with these options:
sudo cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DCHANNEL_RDPSND_CLIENT=ON -DWITH_ALSA=ON -DWITH_PULSE=ON -DCHANNEL_URBDRC_CLIENT=ON -DWITH_PCSC=ON

I installed the following packages:
apt-get install uuid-dev
apt-get install libdbus-glib-1-dev
apt-get install dbus-*-dev
apt-get install libpcsclite-dev libusb-1.0-0-dev

When i try to redirect the usb device (USB-DVD-Drive) i get urbdrc not found.

Did somebody manage to get this running?

**Comment by korjavin** [comment]
same here

**Comment by akallabeth** [comment]
Have you tried adding ```-DCHANNEL_URBDRC=ON``` to the CMake command line?

**Comment by akallabeth** [comment]
Looks like a compile issue, closing.
Support via IRC and mailing list.

**Comment by sinva** [comment]
apt-get install libusbx-devel
