### ISSUE TITLE
Middle mouse click autoscroll problem - Server 2008 R2

### ISSUE THREAD

**Issue by takenit2far** [FreeRDP/FreeRDP#2291]
When clicking on the mouse wheel in a 2008 R2 RDP sessoin,  autoscroll is activated in Chrome and Excel as expected.  Although it's not possible to release the scroll, or control the speed.      In Chrome control is released once the web page scrolls to the end,  this autoscrolls at the slowest imaginable speed so this can take a while.

Workaround disable mouse button 2 with XInput command before launching session. 

Server 2012 is not affected.    All the usual methods of turning off caches,  async-update and async-sync or not effective.

**Comment by akallabeth** [comment]
Closing due to lack of information.
