### ISSUE TITLE
WaitForSingle/MultipleObject improvements for process handles

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#2292]
Process handles don't have a real good support in WaitForSingle/MultipleObject:
- WaitForSingleObject doesn't support a timeout which might cause the calling process to block
- WaitForMultipleObject doesn't support process handles at all

Some (not complete) implementation ideas:
- use eventfd, with SIGCHLD unmasked, and use select
- use WNOHANG for waitpid and sleep until the timeout (in this case we should check multiple times until the set wait timeout to minimize delays)

**Comment by hardening** [comment]
This has been implemented months ago.
