### ISSUE TITLE
Build fails on MAC OS X 10.10(Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) )

### ISSUE THREAD

**Issue by EmiyaShilong** [FreeRDP/FreeRDP#2294]
compiling env: Mac OS X 10.10
SDK:iPhoneOS8.1
cmake version: 3.1.0

when I use Mac os compile the FreeRDP-master , FreeRDP.xcodeproj has appears,but can not build. 
Build error:
iFreeRDP.build/Debug-iphoneos/iFreeRDP.build/Objects-normal/armv7/iFreeRDP normal armv7

clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/client/common/Debug-iphoneos/libfreerdp-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/winpr/libwinpr/Debug-iphoneos/libwinpr.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/libfreerdp/Debug-iphoneos/libfreerdp.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/audin/client/Debug-iphoneos/libaudin-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/disp/client/Debug-iphoneos/libdisp-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/echo/client/Debug-iphoneos/libecho-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rdpei/client/Debug-iphoneos/librdpei-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rdpgfx/client/Debug-iphoneos/librdpgfx-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/tsmf/client/Debug-iphoneos/libtsmf-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/cliprdr/client/Debug-iphoneos/libcliprdr-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/drdynvc/client/Debug-iphoneos/libdrdynvc-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/encomsp/client/Debug-iphoneos/libencomsp-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rail/client/Debug-iphoneos/librail-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rdpdr/client/Debug-iphoneos/librdpdr-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rdpsnd/client/Debug-iphoneos/librdpsnd-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/remdesk/client/Debug-iphoneos/libremdesk-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/drive/client/Debug-iphoneos/libdrive-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/parallel/client/Debug-iphoneos/libparallel-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/serial/client/Debug-iphoneos/libserial-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/smartcard/client/Debug-iphoneos/libsmartcard-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/libfreerdp/Debug-iphoneos/libfreerdp.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/winpr/libwinpr/Debug-iphoneos/libwinpr.a'

iFreeRDP.build/Debug-iphoneos/iFreeRDP.build/Objects-normal/arm64/iFreeRDP normal arm64
 
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/client/common/Debug-iphoneos/libfreerdp-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/winpr/libwinpr/Debug-iphoneos/libwinpr.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/libfreerdp/Debug-iphoneos/libfreerdp.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/audin/client/Debug-iphoneos/libaudin-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/disp/client/Debug-iphoneos/libdisp-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/echo/client/Debug-iphoneos/libecho-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rdpei/client/Debug-iphoneos/librdpei-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rdpgfx/client/Debug-iphoneos/librdpgfx-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/tsmf/client/Debug-iphoneos/libtsmf-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/cliprdr/client/Debug-iphoneos/libcliprdr-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/drdynvc/client/Debug-iphoneos/libdrdynvc-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/encomsp/client/Debug-iphoneos/libencomsp-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rail/client/Debug-iphoneos/librail-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rdpdr/client/Debug-iphoneos/librdpdr-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/rdpsnd/client/Debug-iphoneos/librdpsnd-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/remdesk/client/Debug-iphoneos/libremdesk-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/drive/client/Debug-iphoneos/libdrive-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/parallel/client/Debug-iphoneos/libparallel-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/serial/client/Debug-iphoneos/libserial-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/channels/smartcard/client/Debug-iphoneos/libsmartcard-client.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/libfreerdp/Debug-iphoneos/libfreerdp.a'
clang: error: no such file or directory: '/Users/Emiya/Desktop/FreeRDP-master/winpr/libwinpr/Debug-iphoneos/libwinpr.a'

When i run cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode , it compile:

-- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Git Revision n/a
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Failed
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Failed
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Failed
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Failed
-- Performing Test Wno-builtin-macro-redefined
-- Performing Test Wno-builtin-macro-redefined - Failed
-- Performing Test Wno-builtin-macro-redefinedCXX
-- Performing Test Wno-builtin-macro-redefinedCXX - Failed
-- Looking for pthread_tryjoin_np in pthread
-- Looking for pthread_tryjoin_np in pthread - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - not found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - not found
-- Looking for include file poll.h
-- Looking for include file poll.h - not found
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/lib/libz.dylib (found version "1.2.5") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /Users/Emiya/Desktop/FreeRDP-master/external/openssl/lib/libssl.a;/Users/Emiya/Desktop/FreeRDP-master/external/openssl/lib/libcrypto.a (found version "1.0.0e") 
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Skipping optional feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Enable feature FFmpeg using "-DWITH_FFMPEG=ON"
-- Skipping disabled feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
-- Skipping disabled feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Adding iOS client
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/Emiya/Desktop/FreeRDP-master

**Comment by wwwzys** [comment]
try add param 
```
-DPKG_CONFIG_EXECUTABLE=your pkg-config executable path and file 
```
If you want to compile iFreeRDP, i think you should read the file:
```
docs/README.ios
```

good luck

**Comment by EmiyaShilong** [comment]
@wwwzys thanks,i have comp compile it  according to README.ios，and add the pkg-config path，but the problem also appears.Do you complie iFreeRDP successfully?

**Comment by bmiklautz** [comment]
@EmiyaShilong the build error you are hitting isn't related to pkg-config.
You shouldn't need pkg-config when you compile for ios/osx. If it really was required cmake would stop with an error.

I'm not yet sure what problem you exactly hit but could you try with a cmake version < 3.0?

**Comment by EmiyaShilong** [comment]
@wwwzys I have worked successfully,thanks very much.

**Comment by EmiyaShilong** [comment]
@bmiklautz  I have worked successfully,thanks very much.

**Comment by bmiklautz** [comment]
@EmiyaShilong for reference it would be interesting how you fixed your problem? - Was it cmake related or something else?
