### ISSUE TITLE
SIGBUS on big endian machine

### ISSUE THREAD

**Issue by vanloswang** [FreeRDP/FreeRDP#2295]
Program received signal SIGBUS, Bus error.
[Switching to Thread 0xf709bb70 (LWP 11627)]
0xf7d8c350 in RleDecompress16to16 () from /home/vdp/trunk/apps/3p/FreeRDP-stable-1.1/src/xoutput/libfreerdp/codec/libfreerdp-codec.so.1.1

after trace in code, I find it is in Bitmap_decode.c at function bitmap_decompress. anyone has suggestions?

**Comment by bmiklautz** [comment]
@vanloswang did you solve this problem?
