### ISSUE TITLE
Title in Xwindows seems to be set after window is realized

### ISSUE THREAD

**Issue by alaricljs** [FreeRDP/FreeRDP#2296]
FVWM does it's window 'styling' (decorations and other window specific config) based on the discoverable data when a window is realized (or when FVWM is forced to reprobe via a config reload).

When freerdp is called with /t:'something' it realizes the window first and then changes the window title to match 'something'  This causes FVWM to be unable to match 'something' in order to behave differently according to different freerdp sessions with different window titles without also forcing FVWM to reload the config every time freerdp is called.  That's annoying and innefficient and means certain behaviors are very difficult to force without an inordinate amount of scripting.

Please set the X window title prior to realizing the freerdp window.

I'm running freerdp on Arch:  ~> xfreerdp -version
This is FreeRDP version 1.2.0-beta1 (git n/a)

**Comment by akallabeth** [comment]
Fixed with #5023
