### ISSUE TITLE
it isn't possible to specify application parameters

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#2298]
Hey, I'd like to run remote application with parameters. E.g. run notepad with open file test.txt, but following cmdline doesn't work for me:
xfreerdp /app:"||notepad" /app-cmd:"%SYSTEMDRIVE%\test.txt" ...

I have tried different paths, and also /app-file options, however everytime it opens notepad with untitled file.

Am I doing anything wrong? Or /app-cmd isn't determined to specify application parameters? Or it is broken? Thanks for answer...

**Comment by wwwzys** [comment]
you can try:

```
xfreerdp /app:"||notepad"
```
do not add param  /app-cmd

**Comment by ondrejholy** [comment]
But I want to open the file, so I need to specify it somehow...

**Comment by bmiklautz** [comment]
@ondrejholy not sure if it works but did you try specifying a cmd script or so? - Where you call your program plus parameters?

**Comment by ondrejholy** [comment]
I don't want to open same file everytime, therefor cmd script to call app with parameters (if it is possible) doesn't help me if it will be located on server. 

What `/app-cmd` (or `/app-file`) option should do?

**Comment by bmiklautz** [comment]
@ondrejholy if you use xfreerdp /app-cmd should work to pass parameters:
xfreerdp /app:notepad.exe /app-cmd:'c:\temp\test.txt'

I did some test with latest master and it worked.

Make sure that you quote the path properly. In case you don't use ' you might need double backslash (\\). Also I'm not sure if %SYSTEMDRIVE% substitution works at that point (at least didn't work on my test machine)

**Comment by bmiklautz** [comment]
@wwwzys why not adding the /app-cmd? It's a valid option.

**Comment by ondrejholy** [comment]
@bmiklautz Thanks for testing and response that it should work. It helps me find what is wrong.

I'm sorry, **server has to have allowed arguments explicitly**, or allowed unlisted programs on initial connections...

However it would be good to fail (or print notification) if arguments aren't allowed and /app-cmd is used. It is pretty confusing when /app-cmd is just ignored. At least it would be good to add note into man pages (and/or wiki).

**Comment by bmiklautz** [comment]
@ondrejholy thanks for pointing that out. What was needed to get it running. Do you have any documentation pointers - our wiki is open ;).

**Comment by ondrejholy** [comment]
@bmiklautz Ok, I've made a note about on [RemoteApp](https://github.com/FreeRDP/FreeRDP/wiki/RemoteApp) page.

I've just tried also `/app-name` and `/app-icon` and it seems it doesn't work either :confused: I suppose `/app-icon` doesn't work probably because the code is commented out in `xf_window.h/.c`, however `/app-name` should work probably, but `RAIL:000F00AE` is shown instead.

I wanted to try it on older version, but can't find relevant commandline arguments, was those options supported by the old syntax?

**Comment by azhel12** [comment]
Hi people, a have fail when i want to run any program. I setup /app:"notepad" and other variant and always get black screen (~30sec), then see "logout" and form closing.
P.S. Sorry for my English:)

**Comment by akallabeth** [comment]
Tried it today with `2.0.0-rc4` and it was working for windows 7 but not windows 10.
Might be a configuration issue though.
#5095 also reports that it is not working for server 2012

**Comment by loumt** [comment]
I  come from #5095

I tested the latest code on **master** on Centos7.(At 2018.12.10)
```
xfreerdp --version
This is FreeRDP version 2.0.0-rc4

xfreerdp /v:192.168.0.1  /port:3389 /u:administrator /d:test.com /p:123456 /app:c:\\windows\\system32\\notepad.exe   /app-cmd:c:\\1.txt
```
**Unfortunately, as you test, you can only open the application and not the file.**

Thanks a lot.

**Comment by akallabeth** [comment]
working with 3.x
