### ISSUE TITLE
Can't compile freerdp 1.1.0 for RHEL6.5

### ISSUE THREAD

**Issue by martinmaletti** [FreeRDP/FreeRDP#2304]
When I issue this command in the terminal

cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON

 I get a message saying the following and cannot continue with the compilation of RPM
-- Configuring incomplete, errors occurred!

--------------------------------------------------Terminal--------------------------------------------------
[maletti@oc2372360552 FreeRDP]$ cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON
-- The CXX compiler identification is unknown
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
-- FreeRDP GIT
-- Git Revision df79781
-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Skipping recommended feature Wayland for Wayland (Wayland client)
-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Skipping optional feature OpenSLES for multimedia (OpenSLES audio / video)
--     Enable feature OpenSLES using "-DWITH_OPENSLES=ON"
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Skipping optional feature Pulse for sound (audio input, audio output and multimedia redirection)
--     Enable feature Pulse using "-DWITH_PULSE=ON"
-- Skipping optional feature Cups for printing (printer device redirection)
--     Enable feature Cups using "-DWITH_CUPS=ON"
-- Skipping optional feature PCSC for smart card (smart card device redirection)
--     Enable feature PCSC using "-DWITH_PCSC=ON"
-- Skipping recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
--     Enable feature GStreamer_0_10 using "-DWITH_GSTREAMER_0_10=ON"
-- Skipping recommended feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- FreeRDP GIT
-- Finding recommended feature XKBFile for X11 keyboard (X11 keyboard file extension)
--     Disable feature XKBFile using "-DWITH_XKBFILE=OFF"
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- FreeRDP GIT
-- Could NOT find DocBook XSL stylesheets (missing:  DOCBOOKXSL_DIR) 
CMake Warning at client/X11/CMakeLists.txt:113 (message):
  WITH_MANPAGES was set, but xsltproc was not found.  man-pages will not be
  installed
  -- Finding required feature XShm for X11 shared memory (X11 shared memory extension)
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Finding recommended feature Xcursor for cursor (X11 cursor extension)
--     Disable feature Xcursor using "-DWITH_XCURSOR=OFF"
-- Finding recommended feature Xv for video (X11 video extension)
--     Disable feature Xv using "-DWITH_XV=OFF"
-- Skipping recommended feature Xi for input (X11 input extension)
-- Finding recommended feature Xrender for rendering (X11 render extension)
--     Disable feature Xrender using "-DWITH_XRENDER=OFF"
-- Finding recommended feature Xfixes for X11 xfixes extension (Useful additions to the X11 core protocol)
--     Disable feature Xfixes using "-DWITH_XFIXES=OFF"
-- Configuring incomplete, errors occurred!
[maletti@oc2372360552 FreeRDP]$
-------------------------------------------------------------------------------------------------------------------------------

I'm a rookie on Linux OS and I would really appreciate any help on this.

Thanks

**Comment by bmiklautz** [comment]
@martinmaletti the problem you are hit is
```
 CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found. Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
```

Do you have a c++ compiler installed e.g. (g++).

**Comment by martinmaletti** [comment]
Thanks for your answer bmiklautz, but I already found how to solve my issue.
Here is what I did.

- Download the source code from here:
http://pkgs.fedoraproject.org/repo/pkgs/freerdp/freerdp-1.1.0-beta1.tar.gz/90bcc00031ad7c3000640eb000f38c6a/

- Uncompress, open terminal and change the directory location to "freerdp-1.1.0-beta1.tar.gz".

- Issue the following command: git clone git://github.com/FreeRDP/FreeRDP.git
   If you are asked to download some file say YES.

- Issue the following command: 
sudo yum install gcc cmake openssl-devel libX11-devel libXext-devel libXinerama-devel libXcursor-devel \
  libXdamage-devel libXv-devel libxkbfile-devel alsa-lib-devel cups-devel ffmpeg-devel glib2-devel

- Issue the following command:
   cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON 

- Issue the following command: 
   sudo make install 

- After launching FreeRDP for first time, ~/.freerdp will be created to store known hosts: ---------This step is only informative, you have to do nothing.
Example:
awake@envy:~/.freerdp$ ls
cacert  known_hosts

- Issue the following command to delete the known_hosts store file.
rm ~/.freerdp/known_hosts

- Finally, test connection to any Linux/Unix/Windows cliente/server.
