### ISSUE TITLE
command line compatibility appears to be completely broken in master

### ISSUE THREAD

**Issue by opoplawski** [FreeRDP/FreeRDP#2306]
command line compatibility appears to be completely broken in 1.2.0-beta1-android9 and master.  Commit 1fb028fc9f92c0f50eb1df756d9bacefb661257a appears to be part, but not all of the issue.  With compat options, posix_cli_status is negative and so compatibility is always false:

       if (posix_cli_status <= COMMAND_LINE_STATUS_PRINT)
              return compatibility;

but even with that removed, I can't get it to work.  That may be because windows_cli_count and posix_cli_count are both 0.  I just can't make sense of the code.

**Comment by opoplawski** [comment]
-       if (windows_cli_count >= posix_cli_count)
+       if (windows_cli_count && (windows_cli_count >= posix_cli_count))

That seems to fix compat detection.  But then /version is broken still.  But I'm not sure of the proper fix for that.

**Comment by akallabeth** [comment]
@opoplawski Your pull does not fix the compatibility parsing. Got the fix in https://github.com/akallabeth/freerdp/tree/compatibility_cmdline_fix, could you check if it works now?

**Comment by opoplawski** [comment]
That seems to work for me.  Thanks!

**Comment by bmiklautz** [comment]
@opoplawski thank you for your feedback and effort.
