### ISSUE TITLE
Error while running "make" command in ubuntu.

### ISSUE THREAD

**Issue by shubham0703** [FreeRDP/FreeRDP#2308]
Hello,
I have compiled the code using the command different from the one that has been stated in the Readme.android. The command that i ran is as follows,

cmake -DCMAKE_TOOLCHAIN_FILE=cmake/AndroidToolchain.cmake
 -DANDROID_NDK="ndk path" \
-DFREERDP_EXTERNAL_SSL_PATH="open ssl path in external folder of FreeRDP" \
 -DOPENSSL_INCLUDE_DIR="Include folder path of FreeRDP" \
-DOPENSSL_LIBRARIES="Library folder path in Openssl" \ 
-DANDROID_SDK="sdk path" -DCMAKE_BUILD_TYPE=Debug \
-DANDROID_BUILD_JAVA=OFF

Even though i have compiled the code but when i run "make" command, the execution process never goes beyong 1%.  The error that I get is,

[  1%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/synch/address.c.o
arm-linux-androideabi-gcc: error: unrecognized command line option '-msse2'
make[2]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/synch/address.c.o] Error 1
make[1]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/all] Error 2
make: *** [all] Error 2

Please if anybody can help me in this then do write a solution. Your help will b highly appreciated.

Regards,
Shubham Singhal

**Comment by shubham0703** [comment]
Resolved the issue by following the process from the following link,  

http://android-amit.blogspot.in/

**Comment by zenix98** [comment]
I Too resoled the issue with the same link shared by shubham0703 thank for sharing.
