### ISSUE TITLE
User-defined bulk data transportation over a virtual channel is unstable!

### ISSUE THREAD

**Issue by dsyou20** [FreeRDP/FreeRDP#231]
Using the freerdp, we added a our own virtual channel for specific data, USB Device Redirection  which is from Incentve. 
A virtual channel connection is ok, but almost of all the RDP connection was disconnected saying that "connection reset by server" after few seconds. 
I wondering if there is any QoS related parameters in order to support this kind of data exchage. further more Can I configure the freerdp for tolerance of bulk data through a virtual channel.

We have used a windows 2003 server and Incentive's USB Device Redirector. 
If only use Incentive's USB Redirect standalone server S/W and there host software, It was working well.

Thanks for any advance.

**Comment by hardening** [comment]
@dsyou20 any news with @bmiklautz suggestion ?

**Comment by akallabeth** [comment]
Fixed with #5745
