### ISSUE TITLE
Create Certificate Store

### ISSUE THREAD

**Issue by KenHolloway** [FreeRDP/FreeRDP#2318]
When I try to connect to a server that has a valid certificate, I am getting the following message:

The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the documentation on how to create local certificate store for a private CA.

I suspect that I need to create a certificate store, but I am unable to find any documentation on how. Is this process documented somewhere?

**Comment by bmiklautz** [comment]
@KenHolloway can you give us more information? Maybe the version you are using and the type of host you are connecting to. Also the command line would help.
Is this the full message?

**Comment by KenHolloway** [comment]
xfreerdp --version
This is FreeRDP version 1.0.2

Connecting to Windows Server 2008 R2.

xfreerdp --from-stdin -a 24 -T CCS-DC2.I-removed-this.com -g 1024x768 --disable-menu-animations --disable-wallpaper --plugin cliprdr --plugin rdpsnd --plugin rdpdr --data disk:Home:/home/KHolloway -- -d I-removed-this.com -u KenHolloway --certificate-name *.I-removed-this.com CCS-DC2.I-removed-this.com
loading plugin cliprdr
loading plugin rdpsnd
loading plugin rdpdr
password: 
connected to CCS-DC2.I-removed-this.com:3389
Certificate details:
        Subject: OU = Domain Control Validated, CN = *.I-removed-this.com
        Issuer: C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", OU = http://certs.starfieldtech.com/repository/, CN = Starfield Secure Certificate Authority - G2
        Thumbprint: fd:0e:a6:bd:cd:42:09:f3:11:00:1b:33:e7:04:a6:54:ce:25:e1
The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the documentation on how to create local certificate store for a private CA.
Do you trust the above certificate? (Y/N)
 
 
This server is using a valid public wildcard certfificate. I am trying to "look at the documentation on how to create local certificate store", but I can not find the documentation.

**Comment by WarheadsSE** [comment]
Check the validity of the certificate from outside freerdp:

```
openssl s_client -connect server:port -showcerts </dev/null
```

If that manages to verify your certificate, it is not the certificate that is the problem, or your system CA. (hint: you might need to add ``-CAPath /etc/ssl/certs`` to the above command)

I have seen something similar recently with a wildcard cert, and you will notice that the SubjectName/CN does not match the name of the value passed to ``/v:``, which I have found to be a very annoying prompt, yet valid at the same time. What is needed is for it to check for the acceptance of this valid cert with a mis-matched name.

**Comment by KenHolloway** [comment]
Can someone pleasee tell me where is "the documentation on how to create local certificate store for a private CA."?

I tried the command:

openssl s_client -connect CCS-DC2.--omitted--.com:3389 -showcerts </dev/null

CONNECTED(00000003)
depth=2 C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", CN = Starfield Root Certificate Authority - G2
verify return:1
depth=1 C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", OU = http://certs.starfieldtech.com/repository/, CN = Starfield Secure Certificate Authority - G2
verify return:1
depth=0 OU = Domain Control Validated, CN = *.--omitted--.com
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=*.--omitted--.com
   i:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./OU=http://certs.starfieldtech.com/repository//CN=Starfield Secure Certificate Authority - G2
-----BEGIN CERTIFICATE-----
--omitted--
-----END CERTIFICATE-----
 1 s:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./OU=http://certs.starfieldtech.com/repository//CN=Starfield Secure Certificate Authority - G2
   i:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Root Certificate Authority - G2
-----BEGIN CERTIFICATE-----
--omitted--
-----END CERTIFICATE-----
---
Server certificate
subject=/OU=Domain Control Validated/CN=*.--omitted--.com
issuer=/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./OU=http://certs.starfieldtech.com/repository//CN=Starfield Secure Certificate Authority - G2
---
No client certificate CA names sent
---
SSL handshake has read 2825 bytes and written 631 bytes
---
New, TLSv1/SSLv3, Cipher is AES128-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES128-SHA
    Session-ID: --omitted--
    Session-ID-ctx: 
    Master-Key: --omitted--
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1421811723
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
DONE



I do not really understand all of the output, but I do not see anything that looks like an error. So, where does FreeRDP get its certificate store, and how do I add certficates to it?

**Comment by KenHolloway** [comment]
Hmmm. This system did some "interesting" things with some of the text in that output. Is there a way to tell it "text only", so it doesn't mess up the content?

**Comment by WarheadsSE** [comment]
Yup, wrap the entire block in three backticks (https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown)

**Comment by WarheadsSE** [comment]
Now then, from the looks of it, the wildcard cert is OK according to your system's ca-certificates (and bound openssl, which FreeRDP uses) and this is indeed SubjectName/CN != provided server name.

**Comment by KenHolloway** [comment]
Since I included "--certificate-name *.--omitted--.com" on the command line, shouldn't the certificate be compared against *.--omitted--.com, which is the name on the certficate?

Also, you are implying that FreeRDP uses the openssl certificate store - is that correct? What is the "certs" directory under ~/.freerdp for?

**Comment by WarheadsSE** [comment]
If the certificate not present in it's own ``~/.freerdp/certs`` directory, FreeRDP will make use of the system certificates.

Which version of freerdp are you using? I am using the /cert-name:fqdn and that appears to operate for me without the wildcard. I will check with a wildcard shortly.

**Comment by WarheadsSE** [comment]
Testing with a wildcard cert here, I do get hostname vs CN mismatch warnings. I can then approve the acceptance of this cert, and it is cached to ``~/.freerdp/{certs|server}`` somewhere for future use. The inability to make use of wildcard certs however, is definitively a problem.

**Comment by KenHolloway** [comment]
I am running:

xfreerdp --version
This is FreeRDP version 1.0.2

The error I am getting is NOT a certificate name mismatch. (I do get a name mismatch if I do not specify --certificate-name=*.--omitted--.com.) I am getting a "certificate could not be verified, possibly because you do not have the CA certificate in your certificate store" error.

Is there any documentation on create/modify/verify local certificate store?

When I answer "Y" to "Do you trust the above certificate?", it connects, and never warns about the certificate again. The only file that exists in my .freerdp directory is known_hosts, which has the certificate name, and what looks like a thumbprint. If I delete known_hosts, it asks if I trust the certificate again. I have never seen any files in the .freerdp/certs directory.

Is there any documentation on manipulating the certificate store for FreeRDP???

**Comment by WarheadsSE** [comment]
At this point, the good news is: your openssl certificate chains include the necessary root certificate, and it validates.

The bad news is that your freerdp doesn't seem to be making use of that. It should be.

**Comment by KenHolloway** [comment]
Is there any documentation on manipulating the certificate store for FreeRDP???

**Comment by KenHolloway** [comment]
In case anyone else is trying to do this:

1) Convert the .crt certificate into a .pem certificate, and store in the certs directory:
```
openssl x509 -inform DESC -in Private-CA.crt -out ~/.config/freerdp/certs/Private-CA.pem
```
2) Create the hash of the certificate:
```
ln -s ~/.config/freerdp/certs/Private-CA.pem ~/.config/freerdp/certs/`openssl x509 -hash -noout -in ~/.config/freerdp/certs/Private-CA.pem`.0
```

It may be useful to use strace to see what certificate file(s) FreeRDP is trying to open:
```
strace -ff -e open,stat,stat64 xfreerdp ...
```

**Comment by WarheadsSE** [comment]
As a heads up, I did fix this in master. Wildcard certs, cert chains, and fqdn case-insensitive.
