### ISSUE TITLE
wayland 1.2.1 undefined reference

### ISSUE THREAD

**Issue by awakecoding** [FreeRDP/FreeRDP#2323]
With wayland 1.2.1 development headers, the build fails with the following errors:

In function `wlf_DestroyInput':
undefined reference to `wl_pointer_release'
undefined reference to `wl_keyboard_release'

I do not intend to use the wayland client, it just turns out I have the development headers installed on my machine and the wayland client got automatically built. Quick googling shows the correct functions may be wl_pointer_destroy and wl_keyboard_destroy, but I do not know in which version the change took place.

**Comment by bmiklautz** [comment]
@awakecoding having it recommended and therefor automatically detected will be required for packaging (nightmare don't ask ;) if you really don't want it just hard disable it with -DWITH_WAYLAND=off.

Anyway when the headers are installed in the correct version the build should work maybe I've just set the minimum required version wrong.

Could you add the message cmake prints out when detecting the wayland libs?

**Comment by bmiklautz** [comment]
@awakecoding btw what os version where you on that I can try?
