### ISSUE TITLE
ifreerdp supports remote app about opening remote file

### ISSUE THREAD

**Issue by wwwzys** [FreeRDP/FreeRDP#2324]
now i know ifreerdp support remote app, but if I want to open remote file by notepad.exe (just example: notepad.exe "d:\\myfile\program file\1.txt"). I don't sure it support or not. If it supports, I should how to config it.

```
remote program: notepad
working directory: "d:\\myfile\program file\1.txt"
```
because the directory may have some blanks, I really do not how to set it.

### interface following 
![Image of Yaktocat](https://camo.githubusercontent.com/33e7e94634bebcafc08b87e8287aa252537d98e2/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f363734333535362f323233323434322f33336264643961322d396231632d313165332d393534662d3365363035393131353535322e504e47)

**Comment by DonMag** [comment]
Remote Program: 
```
    notepad.exe d:\myfile\program file\1.txt
```
Leave Working Directory blank

**Comment by wwwzys** [comment]
@DonMag thanks very much. it works.
