### ISSUE TITLE
Wrong window possition in remote app

### ISSUE THREAD

**Issue by DejavuDmitry** [FreeRDP/FreeRDP#2331]
I have caught some bug in the positioning of the child window on my laptop.
I have use MS WORD as remoteapp and just pressed ALT-F4 to close file.

> $ ~/build/FreeRDP/client/X11/xfreerdp -version
> This is FreeRDP version 1.2.0-dev (git b73e61d)
> $ uname -a
> Linux dejavu-ThinkPad-T61 3.16.0-30-generic #40-Ubuntu SMP Mon Jan 12 22:07:27 UTC 2015 
> i686 GNU/Linux

![2015-01-24-102521_1024x768_scrot](https://cloud.githubusercontent.com/assets/9697445/5886745/71b71f3a-a3b7-11e4-9d04-96a5c31f3283.png)

**Comment by DejavuDmitry** [comment]
Any suggestions?

**Comment by akallabeth** [comment]
Rails has been greatly improved in the 2.0 release candidates.
Create a new issue if still not solved.
