### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by greavette** [FreeRDP/FreeRDP#2334]
Hello,

Where can we find the logs for the FreeRDP connection?  If our connection drops I'm hoping the logs will help determine why.

Thank you.

**Comment by bmiklautz** [comment]
@greavette no logs. What version of FreeRDP do you use?

**Comment by greavette** [comment]
Hello,

Thank you for the reply.

We use xFreeRDP 1.10.

Thank you.

**Comment by bmiklautz** [comment]
With 1.1.0 you can try to set WLOG_LEVEL=DEBUG in your xfreerdp process environment. There will be a lot of output produces so you might want to redirect the output to a file. If the time until the connection drops is long make sure you have enough disk space ;).

**Comment by greavette** [comment]
Thank you very much for this information.  

I'm sorry but I'm unsure where to add this WLOG_LEVEL=DEBUG too?  Which file to I add it too and do you  have an example of how to write this out to a file?

Thank you.

**Comment by bmiklautz** [comment]
It's an environment variable.
Either you do
```
WLOG_LEVEL=DEBUG xfreerdp /u:xx /v:xx ...
```
you you export it in in your shell before you run xfreerdp
```
export WLOG_LEVEL=DEBUG
xfreerdp ...
```

**Comment by bmiklautz** [comment]
@greavette also please not that this is an issue tracker.
For help drop by in our irc channel (#freerdp on freenode) or write an mail to the mailing list.
Thanks.

**Comment by greavette** [comment]
Thank you.  I will use the irc channel for future questions.
