### ISSUE TITLE
Re:  Issue 2334 - Where to add debug for logging?

### ISSUE THREAD

**Issue by greavette** [FreeRDP/FreeRDP#2336]
Hello,

I'm not sure how to add a comment to an issue that has been closed so I'll ask it here in a new issue:

Thank you very much for this information.

I'm sorry but I don't know where to add this WLOG_LEVEL=DEBUG too? Which file do I add it too and do you have an example of how to write this out to a file?

Thank you.

**Comment by bmiklautz** [comment]
@greavette I've seen you comment in issue #2334 and have responded.
Really no need for a new issue.
