### ISSUE TITLE
`make` fails trying to parse `docbook.xsl` in another directory

### ISSUE THREAD

**Issue by mbaz** [FreeRDP/FreeRDP#2341]
I'm trying to build freerdp master with

```
cmake -DCMAKE_INSTALL_PREFIX=/usr \
            -DCMAKE_INSTALL_LIBDIR=lib \
            -DWITH_PULSE=ON \
            -DWITH_SERVER=ON \
            .
    make
```

from directory `~/Sources/AUR/freerdp-git`. It fails with

```
[ 95%] Generating xfreerdp.1
warning: failed to load external entity "/home/miguel/Sources/julia/manpages/docbook.xsl"
cannot parse /home/miguel/Sources/julia/manpages/docbook.xsl
```

Why is `make` trying to parse files that are outside its own repository?

**Comment by bmiklautz** [comment]
docbook.xsl is the stylesheet used  to create the manage which is usually part of a package called docbook-xsl. It looks like it is tried to build the manage even if docbook.xsl wasn't found.

**Comment by mbaz** [comment]
I have docbook.xsl 1.78.1 installed, and a bunch of docbook.xsl files under
/usr/share/xml/docbook/.

On Thu, Jan 29, 2015 at 3:15 PM, Bernhard Miklautz <notifications@github.com

**Comment by bmiklautz** [comment]
@mbaz could you add the part of your cmake output related to manages?
And you do have a "manpages/docbook.xsl" so the docbooks style for manages?

**Comment by mbaz** [comment]
I'm sorry, I don't understand what exactly do you mean by 'the part of the
cmake output related to manpages'. Is it a file, or the output of the cmake
command?

I do have a manpages/docbook.xsl:

$ ls -l /usr/share/xml/docbook/xsl-stylesheets-1.78.1/manpages/docbook.xsl
-rw-r--r-- 1 root root 15230 Apr 17  2013
/usr/share/xml/docbook/xsl-stylesheets-1.78.1/manpages/docbook.xsl

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
