### ISSUE TITLE
crash because of double free or corruption (fasttop)

### ISSUE THREAD

**Issue by vanloswang** [FreeRDP/FreeRDP#2351]
*** glibc detected *** ./xfreerdp: double free or corruption (fasttop): 0x00007fc2fc1a92e0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3cc0875366]
libfreerdp-cache.so.1.1(update_process_glyph_fragments+0x2ac)[0x7fc31044b16c]
libfreerdp-cache.so.1.1(update_gdi_fast_index+0xd9)[0x7fc31044b529]
libfreerdp-core.so.1.1(update_recv_primary_order+0x1b0)[0x7fc31020b460]
libfreerdp-core.so.1.1(+0x441be)[0x7fc3102181be]
libfreerdp-core.so.1.1(fastpath_recv_updates+0x297)[0x7fc310218677]
libfreerdp-core.so.1.1(+0x42a87)[0x7fc310216a87]
libfreerdp-core.so.1.1(transport_check_fds+0xa3)[0x7fc310219623]
libfreerdp-core.so.1.1(freerdp_check_fds+0x17)[0x7fc31020bcf7]
libxfreerdp-client.so.1.1(xf_thread+0x480)[0x7fc310cf62c0]
/lib64/libpthread.so.0[0x3cc0c07851]
/lib64/libc.so.6(clone+0x6d)[0x3cc08e767d]

this crash happends when running xfreerdp for more than 30 minutes, and open a lot of windows. more info will be added after I trace it .

**Comment by akallabeth** [comment]
@vanloswang which version of freerdp are you using?

**Comment by vanloswang** [comment]
@akallabeth I am using FreeRDP-stable-1.1
