### ISSUE TITLE
Annoying artifacts in the microsoft office suite

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#2362]
Hi, I'm using frdp to connect to sessions of Microsoft Office proplus on a machine running Windows server 2012R2. I'm using Linux mint 17 with the default cinnamon DE.

frdp works beautifully, handling the latest office suite with little to no quirks, but one annoying glitch that makes tooltips and certain menus look like this:

![screenshot from 2015-02-04 12 49 37](https://cloud.githubusercontent.com/assets/1800830/6039300/4aba2ff2-ac6e-11e4-881a-a81d65482534.png)

I tinkered a bit with the options but didn't find a configuration to solve the problem.

My current command line is:

```
xfreerdp <rdp file> /d: /u: /p: +aero /gdi:hw +async-update /workarea /span /multimon
```

the rdp file contains the following options:

```
redirectclipboard:i:1                                                                              
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
span monitors:i:1
use multimon:i:1
remoteapplicationmode:i:1
server port:i:<redacted>
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:1
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:<redacted>
alternate shell:s:||WINWORD
remoteapplicationprogram:s:||WINWORD
gatewayhostname:s:<redacted>
remoteapplicationname:s:Word 2013
remoteapplicationcmdline:s:
workspace id:s:<redacted>
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Full_Desktop
alternate full address:s:<redacted>
signscope:s:Full Address,Alternate Full Address,Use Redirection Server Name,Server Port,GatewayHost
signature:s:<redacted>
```

I would really like to solve this, It would eliminate my need to ever switch to Windows entirely.

**Comment by DejavuDmitry** [comment]
Also some bugs: https://github.com/FreeRDP/FreeRDP/issues/2250#issuecomment-69790804

**Comment by hardening** [comment]
@leadrevolver could you give a try with latest master release please (you may also find some nighly builds around)

**Comment by bmiklautz** [comment]
See for nightly builds https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by leadrevolver** [comment]
Thanks for taking notice. I'll test it again soon, I'm experiencing some authentication problems atm.

**Comment by akallabeth** [comment]
working in current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef (```/gdi:sw```)
