### ISSUE TITLE
Xfreerdp - Artifacts in Access 2010 on Server 2008 R2

### ISSUE THREAD

**Issue by takenit2far** [FreeRDP/FreeRDP#2370]
Tested with Ubuntu 14.04 with  AMD, Hyper-V and Intel video hardware

When maximizing a MS Access 2010 window, elements from the desktop or window behind remain on screen

I'm using xfreerdp /u: /p: /d: /f  /v:rds

See screenshots

![accessartifact](https://cloud.githubusercontent.com/assets/5838113/6106404/fa39be8c-b058-11e4-96e8-aed9fe45fb45.PNG)
![desktop](https://cloud.githubusercontent.com/assets/5838113/6106405/fbac2d36-b058-11e4-9aed-20ee746563b3.PNG)

**Comment by bmiklautz** [comment]
@takenit2far would you add the version you tested with?

**Comment by takenit2far** [comment]
Hello, it was today's master,  1.2.1-dev (git ed3d952)

**Comment by takenit2far** [comment]
Although the bug has been present since at least mid December..

**Comment by bmiklautz** [comment]
@takenit2far thanks.

**Comment by stlorenz** [comment]
I can confirm this behaviour on Windows 10 and WIn7 with Office 2013 and Chrome. There are often artifacts in other parts of the screen.

Base System: Ubuntu 14.10 with xorg-edgers and nvidia-346 on nvidia KVM 1000

Just did a fresh build 5 minutes ago.

**Comment by akallabeth** [comment]
working on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
