### ISSUE TITLE
Printer redirect. Auto change drivers printers through 5 sec after logon.

### ISSUE THREAD

**Issue by fedsed** [FreeRDP/FreeRDP#2382]
xfreerdp /version
This is FreeRDP version 1.2.1-dev (git n/a) (11.02.2015)

Syntax run:
xfreerdp +clipboard /u:"" /bpp:16 /t:SERVER /size:800x600 /d:MYDOMAIN /printer:HP-LaserJet-4050,"HP LaserJet 4050 Series PCL6" /sec:rdp /v:server.name

![freerdp_print1](https://cloud.githubusercontent.com/assets/1212506/6148887/dcc5f780-b215-11e4-9ebe-62f1aa6f026d.jpg)

after 5 sec

![freerdp_print2](https://cloud.githubusercontent.com/assets/1212506/6148892/e4df8eb8-b215-11e4-9387-f984cc0cf2c5.jpg)

**Comment by akallabeth** [comment]
Fixed with #3165

**Comment by akallabeth** [comment]
#2269
