### ISSUE TITLE
iOS: Resolution and Screen color

### ISSUE THREAD

**Issue by rodanie** [FreeRDP/FreeRDP#2387]
Xcode 6.1.1
Mac 10.10.2 Yosemite
CMAKE 3.1.2
Connecting to Windows 2008 R2 and/or Win 2012 R2

Build iOS 7.1 Simulator based on 8.1 SDK.

I have tried 16, 24, and 32 bit color depth, low and high resolution and get the same results shown in screenshot below.  Any suggestions would be appreciated.

![screenshot 2015-02-12 09 15 12](https://cloud.githubusercontent.com/assets/4340584/6163970/5722262e-b299-11e4-9da5-2b66e1299098.png)

Connection to test server.
![screenshot 2015-02-12 09 31 26](https://cloud.githubusercontent.com/assets/4340584/6164027/309e6ed0-b29a-11e4-931c-4f181a1932c2.png)

**Comment by DonMag** [comment]
@rodanie - See: https://github.com/FreeRDP/FreeRDP/issues/2152
