### ISSUE TITLE
Problems with serial redirection

### ISSUE THREAD

**Issue by StephanKrieger** [FreeRDP/FreeRDP#2389]
Hi @all,

i hope this is the right place for my questions.

I am from germany and wants to use FreeRDP to connect from Linux-ThinClients to a Windows Terminal Server. Starting a RDP Session is not the problem.

I have problems to use the serial ports after the serial port redirection.
I tried two different installations with two different Problems.

First one:
Installed FreeRDP.git like the Compilation-Guide said. 
When i now ridirect the port and will open it on the Windows Terminal Server, Windows says in german: "Die Anforderung wird nicht unterstützt"
And when i close the session, the Linux also says "Attempt to use the unsupported SERIAL_XOFF_CONTINUE"
Can somebody say to me, what thats means?

Second one:
I get a Special vendor package for a Hardware Plattform with an angstrom Distribution.
When i now start there the redirection, My program based on .Net Framwork says in german:
„Error: Fehler beim Öffnen des Waagen-ComPorts - Fehler: System.ArgumentException: Der angegebene Anschlussname ist ungültig. Es kann ein gültiger Anschluss sein, aber kein serieller Anschluss.
Parametername: portName
   bei System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   bei System.IO.Ports.SerialPort.Open()"
Did somebody know the message and how i can resolve it?

Greetz from germany
Stephan

**Comment by eledoux** [comment]
@StephanKrieger when you says two different installations, do you mean two different devices?

First issue:
That's means your application tried to setup the SERIAL_XOFF_CONTINUE feature that is not supported by the current implementation of the serial port redirection. You can get a bit of information here: https://msdn.microsoft.com/en-us/library/jj680685%28v=vs.85%29.aspx

Second issue:
This looks similar to the first issue. Your program doesn't succeed to setup the port as it would like and returns the error.

If this prevents you to use the serial port you can try to complete the xfreerdp's command line by using for each port something like: /serial:COM1,/dev/ttyS0,Serial,permissive. This turns on a more permissive mode which will pretend a feature such as SERIAL_XOFF_CONTINUE is well supported by the redirection. 

Anyway, in both cases, it'd be interesting to know whether your devices and/or programs work correctly or not with the Windows RDP client (mstsc.exe)?

**Comment by StephanKrieger** [comment]
@eledoux First thanks for your replay.

To your first question towards the Issues:
Yes there are two different devices. The first one is a ubuntu desktop Installation on a normal Laptop and second one is a embedded Linux on an Industrie Mainboard. The one for the industrie is that device that is important for me. The ubuntu system is just for parallel testing freerdp, maybe i have a chance to make a cross-installation.

I just tried your tip to complete the xfreerdp's command. But maybe i understand it wrong:
I type after starting the plugin: --data serial:COM1:/dev/ttyHS1,serial,permissive
When i try to open it in Windows i get this error:
Warning serial_tty_new (462): failed to open device /dev/ttyHS1,serial,permissive
Warning serial_process_irp_create (102): failed to create

To your question with mstsc.exe:
Yes there i can use the serial ports in normal way with the applications.

Further informations:
The second issue remembers me to rdesktop and a problem with the "SERIAL_GET_PROPERTIES". Don't know if this could be interesting.

**Comment by StephanKrieger** [comment]
I just take more tests towards your description.

At first i maybe find out where my "fault" was with the "permissive" extension.
I use freerdp like this:
xfreerdp -u USER -p PW -d DOM --plugin pdrdr --data serial:COM1:/dev/ttyS0 -- SERVER

I think i have to use the following:
xfreerdp /u:USER /p:PW /d:DOM /serial:... /v:SERVER

But when i use the second one i get on both devices the error:
protocol security negotiation error

**Comment by eledoux** [comment]
@StephanKrieger yes the correct syntax, using a recent version of xfreerdp from the master branch, is well: xfreerdp /u:USER /p:PW /d:DOM /serial:COM1,/dev/ttyS0,Serial,permissive /v:SERVER

Thanks for the tests with mstsc.exe. I'm just curious, what kind of device or peripheral do you use on the serial port? 

If you still get the issue, more details like the version of the Windows server would be interesting as well. By the way and if possible for you, recent versions of Windows should be less problematic.

The security negotiation error doesn't sound like an error specific to the serial port redirection. You better have to double check your command line and the server's configuration. Possibly open a separate issue if you identify an issue.

**Comment by StephanKrieger** [comment]
@eledoux I just recognize on both devices i use an old version (1.0.2) of xfreerdp. With the recent version and the "new" syntax on the first device everything seems OK at the moment.

I can't test it right know with the correct device, because i have to make a cross Installation to the embedded system. I hope this will be a happy end :)

Maybe we can let this issue open until this will really be the solution ;)

To your question:
The peripheral is a weighing device on a industrie board with embedded Linux.

I get the "security negotiation" error also on this new version of xfreerdp, but i will test it further more before i will open a separate issue.

**Comment by StephanKrieger** [comment]
I have tried out everything the last days and still have Problems.
I want to send continuous data from the weighing device to the remote session.
After a short time the data stops to send and i get the following Messages on linux:
"[ERROR][com.winpr.thread] - function called, but no matching entry in thread list!

In the remote session the comport isn't avaible anymore. I must restart the session.

The time between starting the data send and the error is everytime different.

**Comment by eledoux** [comment]
@StephanKrieger the message about the thread is more likely a consequence rather than the cause. Are there some other messages on the standard output that could help?

**Comment by StephanKrieger** [comment]
@eledoux i just tried again and have written out what messages appears.

First here the command i use for xfreerdp:
xfreerdp /u:user /p:pwd /d:dom /cert-ignore /serial:COM1,/dev/ttyS0,Serial,permissive /v:IP

When i connect to the remote mashine i first get this:
[18:39:32:043] [3982:-870230272] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[18:39:32:043] [3982:-870230272] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[18:39:33:153] [3982:-878622976] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service serial (static)
[18:39:34:046] [3982:-878622976] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: COM1 (type=1 id=1)

When i open the serial port on the remote machine i directly get this messages:
[18:40:03:148] [3982:-903801088] [WARN][com.winpr.comm] - ErrorChar='?' (0x3f) cannot be set (unsupported).
[18:40:03:148] [3982:-903801088] [WARN][com.winpr.comm] - BreakChar='?' (0x3f) cannot be set (unsupported).
[18:40:03:148] [3982:-903801088] [WARN][com.winpr.comm] - [permissive]: whereas it failed, made to succeed IoControlCode=[0x1B005C] IOCTL_SERIAL_SET_CHARS, last-error: 0x32
[18:40:03:150] [3982:-903801088] [WARN][com.winpr.comm] - Attempt to use the unsupported SERIAL_XOFF_CONTINUE feature.
[18:40:03:150] [3982:-903801088] [WARN][com.winpr.comm] - [permissive]: whereas it failed, made to succeed IoControlCode=[0x1B0064] IOCTL_SERIAL_SET_HANDFLOW, last-error: 0x32

At least when i start to send data after a while the message with the thread appears:
[18:40:30:638] [3982:-914385152] [ERROR][com.winpr.thread] - function called, but no matching entry in thread list

Is this helpful to know what happened?

**Comment by eledoux** [comment]
@StephanKrieger thanks for the output messages. Since some data are sent continuously, everything about the flow control is the ideal suspect but this is the fact the COM port is not available anymore after an error happened that bothers me the most.

It should be possible to get more info by typing before the xfreerdp command:
export WLOG_LEVEL=DEBUG

Possibly redirect the xfreerdp's output in a file xfreerdp /u:... /v:myserver > mylog.log   

I also usually use: xfreerdp /u:... /v:myserver | grep serial

@all I didn't succeed to correctly setup WLOG_FILTER, but my practices about logs might be out-of-date

**Comment by StephanKrieger** [comment]
@eledoux Is there something different between use xfreerdp with or without the DEBUG Level before it?
I started the data send for about 25 minutes and i get no error. The last days the maximum time was about two minutes before the error.

After a reboot and using only the xfreerdp command without DEBUG i get the error after one minute.

Strange!?!

**Comment by eledoux** [comment]
@StephanKrieger that makes xfreerdp slower but the amount of data to transit on the serial line should be the same.

Just to know, is there any chance to adjust some settings between your application and your serial device? Is it for instance possible to change the flow control from "software" to "hardware"?

**Comment by StephanKrieger** [comment]
@eledoux I tried a second time with DEBUG and also get an error after about 35 minutes. The last message i get is:
[com.freerdp.channel.serial.client] - 1 IRP thread(s) not yet terminated

I use Docklight to communicate to the serial device so i can change settings you want.

Do you mean the settings from the weighing device?

**Comment by eledoux** [comment]
@StephanKrieger Yes it is important to have the same communication settings set on the weighing device and the application. Docklight looks like an interesting tool by the way.

My understanding is that you use Docklight which is directly connected to the weighing device. This latter device continuously sends some data but no data is sent to the device. Basically xfreerdp only reads some data from the serial port but writes nothing, is that right?

https://gist.github.com/ permits to share some files, it'd be great you post the log (mylog.log) and maybe a capture of the traffic as seen by Docklight

**Comment by StephanKrieger** [comment]
@eledoux The settings have to be the same, otherwise i could not start a connection to the weighing device as far as i know. I just know the device runs on 57600,8,n,1. 

Docklight runs on the remote machine and opens the redirected ComPort from the weighing device. Then i trigger the device to send me data continuously and Docklight just listen on the port.
Finally i have to write and read to the device, but just listening is much easier for these tests.

The Log-File will be very big without "grep serial"... but i will test both now and share the important parts of the log-file.

**Comment by StephanKrieger** [comment]
@eledoux The whole day i get no error but just after a restart i get it and uploaded the whole logfile (without grep serial).
The thing i have changed before getting the error was to Switch from WLAN to LAN with the Notebook.

Here is the log:
https://gist.githubusercontent.com/StephanKrieger/39673390ac8a027d375b/raw/freerdp_all.log

I can't really say when the error appears, but i think when the first message like this is shown:
[com.freerdp.channel.serial.client] - 1 IRP thread(s) not yet terminated

Where is the fault?

**Comment by StephanKrieger** [comment]
@all I have search for the message and the "error" appears in the serial_main.c towards this function:
static void create_irp_thread(SERIAL_DEVICE *serial, IRP *irp)
http://code.metager.de/source/xref/FreeRDP/channels/serial/client/serial_main.c
Line 458

In Line 524 i found the related message. Maybe someone can help me?

**Comment by eledoux** [comment]
@StephanKrieger I didn't forget this issue but I've got a busy week and it's not always easy to get an hour or so.

Thanks for the log it gave a few ideas where to check the code. More precisely the error message is here: https://github.com/FreeRDP/FreeRDP/blob/master/channels/serial/client/serial_main.c#L524

If at some point I'd like you to make a test with more debug information or to test a fix, will it be easy for you to make build from this branch https://github.com/eledoux/FreeRDP/tree/ports ?

**Comment by StephanKrieger** [comment]
@eledoux No problem. I don't want you to rush. I just had a few minutes on my own to search for the error and found it in the serial_main.c. I am very grateful you help me with this issue :)
I hoped that someone else can help and not only your time is "waste" ;)

I will test to make build from the branch in the next days and will post the result.

**Comment by StephanKrieger** [comment]
@eledoux I have just made a build from the branch. I get the same "error". Should i run the "new" branch with Debug or how should i test with more debug informations?

**Comment by eledoux** [comment]
@StephanKrieger Yes a build with -DCMAKE_BUILD_TYPE=Debug could be interesting. There are a few assertions in the code that could stop the xfreerdp's execution when something not expected happens.

Otherwise I'm focusing on the synchronization of the threads and the usage of WaitForSingleObject() in serial_main.c.

**Comment by eledoux** [comment]
@StephanKrieger I'm speculating on a fix that I didn't test. I committed it on the branch: https://github.com/eledoux/FreeRDP/tree/ports

I won't be able to investigates more today. On your side, can you do a test after to get an up to date copy of the 'ports' branch?

**Comment by StephanKrieger** [comment]
@eledoux Thx for the fix. I will test the up to date copy of the 'ports' branch and will build it directly with "-DCMAKE_BUILD_TYPE=Debug". It can take one day or two... i will post the result after testing.

**Comment by eledoux** [comment]
@StephanKrieger you likely also noticed that I lost my speculative bet! I could do a quick test and in appearance the result was not good. I got some invalid thread handles. However I didn't understand the root cause yet and I'm still thinking there could have an issue around thread_list.

I also realized I introduced an issue by fixing #2333 too quickly. On the 'ports' branch I pushed a more proper fix for this latter issue and added the timeouts values in the log. 

I'm interested to get your own timeouts values to see whether your use case is sensible to the issue I recently introduced. Can you please generate a new log file, just the beginning of the log is interesting?

For instance this case below was problematic. Read operations was retuning immediately instead of blocking. 

[08:14:34:881] [13855:13947] [DEBUG][com.freerdp.channel.serial.client] - CommDeviceIoControl: CompletionId=1, IoControlCode=[0x1B001C] IOCTL_SERIAL_SET_TIMEOUTS
[08:14:34:881] [13855:13947] [DEBUG][com.winpr.comm] - CommDeviceIoControl: IoControlCode: 0x001b001c
[08:14:34:881] [13855:13947] [DEBUG][com.winpr.comm] - ReadIntervalTimeout 1
[08:14:34:881] [13855:13947] [DEBUG][com.winpr.comm] - ReadTotalTimeoutMultiplier 0
[08:14:34:881] [13855:13947] [DEBUG][com.winpr.comm] - ReadTotalTimeoutConstant 0
[08:14:34:881] [13855:13947] [DEBUG][com.winpr.comm] - WriteTotalTimeoutMultiplier 0
[08:14:34:881] [13855:13947] [DEBUG][com.winpr.comm] - WriteTotalTimeoutConstant 0

**Comment by StephanKrieger** [comment]
@eledoux Thanks for the update. I think i can get the logs and the next Informations for you on the weekend.

**Comment by StephanKrieger** [comment]
@eledoux I made a first test yesterday with the "older" 'ports' branch. The test with the "newer" branch is still in Progress.
What part of the log you need? The log from the first test is about 35.000.000 lines because i didn't use the grep-command.

btw.: Is the grep-command to seperate the serial commands always enough? So i can work with smaller logs :)

**Comment by eledoux** [comment]
@StephanKrieger Do you mean 35 million lines of mostly the error message "1 IRP thread(s) not yet terminated"? Or some regular debug messages?

For the moment, I'd just need the lines around IOCTL_SERIAL_SET_TIMEOUTS as above.

the grep-command won't be good for this test but you don't need to wait long. These log messages appear at the beginning once you start to use the port. :)

**Comment by StephanKrieger** [comment]
@eledoux The whole log is 35 million lines... so with regular debug messages also.
I waited until the error occours... so if you need more informations, no problem :)

I added the lines around "IOCTL_SERIAL_SET_TIMEOUTS" just here:
https://gist.github.com/StephanKrieger/38983666a161bf9eb365
I cut it from both tests. I hope it is enough for you :)

**Comment by eledoux** [comment]
@StephanKrieger thanks for your tests. According the timeouts values, your use case was well impacted by the regression but I'm afraid the resolution of the regression (already on the branch) won't be enough to resolve your issue. You confirm you still get your initial issue with a build from the branch?

The next step will be to make sure the thread_list is either way correctly updated or not

**Comment by StephanKrieger** [comment]
@eledoux Yes the problem still occurs. The second part from the logs i posted was from a test with the build from the branch.
It is just a feeling, but maybe i get the error a little bit later now...

Can i test something else or help you with other informations?

**Comment by StephanKrieger** [comment]
@eledoux I hope it is OK to ask after these days. Do you think the error can be fixed?
Hope to hear from you :)

**Comment by eledoux** [comment]
@StephanKrieger no problem. The issue should be fixable since I "just" expect a synchronization problem. The thing is that I'm running out of time and/or energy to work on it. I'd like to write a couple unit tests to validate or not the doubts I have about the thread_list.

I noticed though some recent changes on the master branch about WaitForSingleObject that could have a positive impact on this issue. So it might be worthy to make a try even if I don't expect yet a fix.

**Comment by StephanKrieger** [comment]
@eledoux I just testet it with the master branch.
As i know i get it from "git://github.com/FreeRDP/FreeRDP.git"... is that right?

With this branch the error still occurs.

Do you have some new informations towards it?

**Comment by StephanKrieger** [comment]
@eledoux For your Information: I have made to more tests today.

First Test: I send every 250ms a command over the com-port and get an answer from the weighing device. So i have no continous sending of data. Result: Same Error

Second Test: One of our software engineer wrote me a little programm. With this pogramm the following procedure is given: Open the com-port --> get data from the weighing device --> Close the com-port
Between closing and opening the com-port are 1.000ms.
Result: Same Error

Maybe this can help you for more detailed Information?

**Comment by eledoux** [comment]
@StephanKrieger There is a good chance the issue to be fixed on this branch: https://github.com/eledoux/FreeRDP/tree/thread_list

You can also wait for the pull request #2646 to be merge on master by the project's owners.

I well identified the issue previously but its resolution brought its own issue at this time! You may notice I'm proposing about the same resolution.

**Comment by StephanKrieger** [comment]
@eledoux Thanks for this informations. I will test it this week i think.
I really hope this will fix my problems. 

I will give a feedback after testing.

**Comment by StephanKrieger** [comment]
@eledoux I just wanted to test your branch.
I used the same command to start the FreeRDP:
xfreerdp /u:xxx /p:xxx /d:xxx /serial:COM1,/dev/ttyS0,Serial,permissive /cert-ignore /v:xxx

But i get the following errors:
[16:09:19:737] [2689:2690] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[16:09:19:737] [2689:2690] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[16:09:19:750] [2689:2690] [ERROR][com.freerdp.crypto] - error creating directory '/root/.config/freerdp'
[16:09:19:751] [2689:2690] [ERROR][com.freerdp.crypto] - certificate store initialization failed
[16:09:19:751] [2689:2690] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED $
[16:09:19:751] [2689:2690] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection f$
[16:09:19:753] [2689:2690] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1

Do you maybe know what is wrong now?

**Comment by StephanKrieger** [comment]
@eledoux I have tested the new brach... and the issue seems to be fixed.
I didn't get any error after more then two days of permanent data transfer.

Is it right that the fix is now also integrated in the master branch?

**Comment by eledoux** [comment]
@StephanKrieger yes the fix is now merged in the master branch. Thanks a lot for the feedback, you may now close the issue.

**Comment by StephanKrieger** [comment]
@eledoux I will test the master branch over the weekend. If this test is positive, i will close this issue.
Thanks a lot for your help.

**Comment by StephanKrieger** [comment]
@eledoux The test with the master branch was positive, so the issue is now close.

**Comment by bmiklautz** [comment]
@eledoux thanks for the efforts!
