### ISSUE TITLE
com.freerdp.gdi error - PatBlt: unknown rop: 0x00500325

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#2390]
Hey All,

Just got this error in the console while in a Windows Server 2008 R2 box. While in SQL Server Management Studio if I produced a sql statement with an error in it, this error gets printed out in the console over and over until I fix the error ([ERROR][com.freerdp.gdi] - PatBlt: unknown rop: 0x00500325).  The default behavior is that a red squiggle underline shows up where the error is in SSMS. (On my Windows 8.1 machine I can do this and not receive the error in the console window). 

Thanks! You guys are awesome

**Comment by akallabeth** [comment]
working in current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
