### ISSUE TITLE
Mouse click holding bug

### ISSUE THREAD

**Issue by Testinos** [FreeRDP/FreeRDP#2391]
Have problem with mouse click, some random time if click to (url, text, window) mouse dont clickup and  holding down the mouse. 
Usage option 

```
xfreerdp /f /multimon +fonts /cert-ignore /bpp:32 /d:AT /sound:sys:pulse /microphone:sys:pulse /kbd:0x00000409 -wallpaper /sec:tls /u:USER /v:win2012-server +auto-reconnect /gfx +gfx-progressive /rfx +async-input +async-update +gfx-h264
```

any idea how fix it?

**Comment by bmiklautz** [comment]
@Testinos could you please add what version of FreeRDP you are using and what system you are connecting to?

**Comment by Testinos** [comment]
@bmiklautz i am using lates version from git, and openh264 lates version from git, Connect to Win server 2012R2. 
I am not sure but i think this bug have only with +gfx-h264 parameter.
I can use xfreerdp without this option but this option significantly increases the speed RDP.

**Comment by Testinos** [comment]
I am very sorry that I do not know с++ code, but i have more question about xfreerdp. 
have next bug with +gfx-h264 parameter
after watch youtube >1 min have bug litle black box image artifacts.

Where can I go to address these issues?

**Comment by hardening** [comment]
@Testinos can you try latest master and see if #2747 fixed the problem for you ?
Thank you

**Comment by Testinos** [comment]
@hardening 
bug still have (after 2 hour work have 2 time this bug)
if open youtube have error in console
```
[13:18:36:092] [7419:7427] [ERROR][com.freerdp.client.x11] - h264_decompress failure: -1
[13:18:36:117] [7419:7427] [ERROR][com.freerdp.client.x11] - h264_decompress failure: -1
[13:18:36:137] [7419:7427] [ERROR][com.freerdp.client.x11] - h264_decompress failure: -1
[13:18:36:164] [7419:7427] [ERROR][com.freerdp.client.x11] - h264_decompress failure: -1
[13:18:36:223] [7419:7427] [ERROR][com.freerdp.client.x11] - h264_decompress failure: -1
```
and this bug appears increasingly

**Comment by akallabeth** [comment]
Closing as GFX AVC modes have improved. If still an issue with current master please reopen.
