### ISSUE TITLE
Windows Media Player would be stopped after re-login

### ISSUE THREAD

**Issue by hyacinthes** [FreeRDP/FreeRDP#2396]
Hi all,

Does anyone found that the Windows Media Player stopped after re-login.
How to reproduce:
1. Connect to server, and play a video with Windows Media Player.
2. Then logout and login again, the Windows Media Player stopped.
3. Close the Windows Media Player and reopen the video file, then it plays well.

**Comment by akallabeth** [comment]
Not enough information.
Closing, create a new issue or use the mailing list for support if still an issue.
