### ISSUE TITLE
xfreerdrp Crashes with segfault in find_keyboard_layout_in_xorg_rules

### ISSUE THREAD

**Issue by octoquad** [FreeRDP/FreeRDP#2399]
Hi,

I completed compiling just the freerdrp package on Ubuntu Gnome 15.04, using this guide: https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-14.04-and-14.10. The build was successful only after adding libgstreamer-plugins-base1.0-dev as a dependency. I can add this in the page, just let me know.

This particular problem has been around since 2011 and has been reported on Launchpad: https://bugs.launchpad.net/ubuntu/+source/remmina/+bug/753520. Both GDB and Valgrind logs are attached to the bug report. In summary xfreerdp fails to load if the keyboard XKBLAYOUT is set to "za" or "mao" in /etc/default/keyboard, but setting it to "us" seems to make it work again. 

This particular problem is fairly trivial to reproduce, but if you need more information let me know. Just using xfreerdp built from source produces:

```text
(gdb) run +clipboard /sound:rate:44100,channel:2 /v:<ip/host> /u:<user>
Starting program: /usr/local/bin/xfreerdp +clipboard /sound:rate:44100,channel:2 /v:<ip/host> /u:<user>
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffecbf1700 (LWP 27493)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffecbf1700 (LWP 27493)]
0x00007ffff5d13232 in find_keyboard_layout_in_xorg_rules (layout=0x7fffe801ad70 "za", variant=0x7fffe801aff0 "") at /home/bruce/dev/desktop/FreeRDP/libfreerdp/locale/xkb_layout_ids.c:913
913				for (j = 0; xkbLayouts[i].variants[j].variant != NULL && strlen(xkbLayouts[i].variants[j].variant) > 0; j++)
(gdb) bt
#0  0x00007ffff5d13232 in find_keyboard_layout_in_xorg_rules (layout=0x7fffe801ad70 "za", variant=0x7fffe801aff0 "") at /home/bruce/dev/desktop/FreeRDP/libfreerdp/locale/xkb_layout_ids.c:913
#1  0x00007ffff5d13514 in detect_keyboard_layout_from_xkbfile (display=0x7fffe800e5a0, keyboardLayoutId=0x7fffecbf082c) at /home/bruce/dev/desktop/FreeRDP/libfreerdp/locale/keyboard_xkbfile.c:409
#2  0x00007ffff5d13373 in freerdp_keyboard_init_xkbfile (keyboardLayoutId=0x7fffecbf082c, x11_keycode_to_rdp_scancode=0x7ffff6047540 <X11_KEYCODE_TO_VIRTUAL_SCANCODE>) at /home/bruce/dev/desktop/FreeRDP/libfreerdp/locale/keyboard_xkbfile.c:347
#3  0x00007ffff5d11bcd in freerdp_keyboard_init (keyboardLayoutId=0) at /home/bruce/dev/desktop/FreeRDP/libfreerdp/locale/keyboard.c:112
#4  0x00007ffff7b49118 in xf_keyboard_init (xfc=0x60f000) at /home/bruce/dev/desktop/FreeRDP/client/X11/xf_keyboard.c:116
#5  0x00007ffff7b4fae8 in xf_pre_connect (instance=0x60ed20) at /home/bruce/dev/desktop/FreeRDP/client/X11/xf_client.c:971
#6  0x00007ffff5d47575 in freerdp_connect (instance=0x60ed20) at /home/bruce/dev/desktop/FreeRDP/libfreerdp/core/freerdp.c:75
#7  0x00007ffff7b515dd in xf_thread (param=0x60ed20) at /home/bruce/dev/desktop/FreeRDP/client/X11/xf_client.c:1467
#8  0x00007ffff760c3e3 in thread_launcher (arg=0x695ad0) at /home/bruce/dev/desktop/FreeRDP/winpr/libwinpr/thread/thread.c:259
#9  0x00007ffff55770a5 in start_thread (arg=0x7fffecbf1700) at pthread_create.c:309
#10 0x00007ffff72c090d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) quit
```

Thanks

**Comment by bmiklautz** [comment]
@octoquad what version of FreeRDP are you using? Latest git master?

**Comment by octoquad** [comment]
@bmiklautz Yes. This was originally reported here https://github.com/FreeRDP/Remmina/issues/441 roughly a month ago.

**Comment by hardening** [comment]
@octoquad I'm looking at the code and I suspect what's going on

**Comment by hardening** [comment]
@octoquad https://github.com/FreeRDP/FreeRDP/issues/2511 should fix your bug

**Comment by octoquad** [comment]
@hardening, thanks. Can you confirm if this also fixes the mao (Maori) layout as well? I didn't see it in the patch. When I get a chance, I'll test your patch and confirm if everything is good.

Thanks for taking the time fix this :)

**Comment by hardening** [comment]
Hum it should not crash with Maori, but if you want the "good keyboard" (tm) you may give me the kind of keyboard that is used for maori.

**Comment by octoquad** [comment]
Works fine. Thanks :)

**Comment by hardening** [comment]
@octoquad but do you get the correct keyboard, I mean do you have the right keys ?

**Comment by octoquad** [comment]
I can't confirm mao, but I will check za. I was confirming that the xfreedrp doesn't crash on any command provided with XKB_LAYOUT set to za, which is what was happening before this fix. ZA and US layouts are pretty similar.

**Comment by cgholam** [comment]
Mchrfin

**Comment by bmiklautz** [comment]
@cgholam what do you mean with "Mchrfin" ?

**Comment by cgholam** [comment]
Orido.zawj
بتاريخ Apr 10, 2015 10:12 AM، كتبها "Bernhard Miklautz" <
notifications@github.com>:

**Comment by octoquad** [comment]
Hi,

Apologies for the late response. Yes all keys work correctly.

Thanks
