### ISSUE TITLE
iFreeRDP corrupted display

### ISSUE THREAD

**Issue by vifajardo** [FreeRDP/FreeRDP#2412]
I encountered an issue when i built and compiled iFreeRDP. My scenario is:
- Successfully built iFreeRDP master branch using latest Feb 12, 2015 commit.
- Dev platform XCode 6.1.1 on Yosemite (10.10.2)
- Run the build on iPad2 iOS 8.1.3

I then tried to connect to a Win2012 Server using default settings for iFreeRDP. It seems to successfully login but it displays a corrupted screen as shown below.

![img_0389](https://cloud.githubusercontent.com/assets/11096965/6309883/846356f8-b91f-11e4-970a-d4ea6aedda32.jpg)

I did try the iFreeRDP version distributed from the Apple App store and that version is working fine and has no display problems. So is there any settings, changes or update that I need to get my local iFreeRDP to display properly ?

**Comment by kaizirlewagen** [comment]
@vifajardo How do you compile it for arm64 -> for the iPad2?

To fix the graphic issue you can try #2152 
The fix worked for me. But i can not compile it for the iPad2.

**Comment by vifajardo** [comment]
@kaizirlewagen Thx very much for the reference. That actually helped.
