### ISSUE TITLE
Microphone Redirection doesn't working

### ISSUE THREAD

**Issue by sheynandr** [FreeRDP/FreeRDP#2418]
Hi. I'm compile FreeRDP from source yesterday, but microphone redirection doesn't working. Sound redirection working stable.

System (lsb_release)
>Distributor ID:	LinuxMint
>Description:	Linux Mint 17.1 Rebecca
>Release:	17.1
>Codename:	rebecca

System(uname -a)
>Linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

FreeRDP version
>This is FreeRDP version 1.2.1-dev (git c3bbe70)

Any Ideas?

**Comment by Testinos** [comment]
@sheynandr check it https://github.com/FreeRDP/FreeRDP/issues/2347
