### ISSUE TITLE
[android] Client hang on disconnect

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#2419]
When selecting disconnect from menu, the client hangs.

**Comment by awakecoding** [comment]
@akallabeth we have observed this issue as well last week

**Comment by PS83** [comment]
I came across similar problem reported in another ticket #1540 (where the RDP session hangs on disconnect). But not sure if this is related to that issue (as I am new to FreeRDP).

**Comment by jlafontaine-devolutions** [comment]
Disabling async channels lets me disconnect successfully again.

**Comment by shaunsphere** [comment]
@jlafontaine-devolutions: How to disable async channels for aFreeRDP (android) ?

**Comment by jlafontaine-devolutions** [comment]
@shaunsphere I had to modify android_freerdp.c:445, set all async channels to false and then recompile from source.

**Comment by shaunsphere** [comment]
I also found an alternative way in Java/Eclipse to avoid recompile.
Just set debugSettings.setAsyncChannel(sharedPrefs.getBoolean("bookmark.async_channel", false));
in BookmarkBase.java
Thanks

**Comment by mvojjala** [comment]
I am also facing client hang on disconnecting the session. As suggested disabling, async channels to false fixes the issue. However, I would like to understand the impact of disabling the async channels ? I Can some body say the purpose of the async channels?  What effect does disabling async channels  have on performance ?

**Comment by akallabeth** [comment]
@mvojjala I'm currently working on getting the android client up to date, have a look here: https://github.com/akallabeth/freerdp/tree/android_api_upgrade_v3
Not ready for primetime yet but on its way.

As for the async channel options, it just processes all channel data in a separate thread.

**Comment by akallabeth** [comment]
This should be fixed on master since #3097, could anyone confirm?

**Comment by mvojjala** [comment]
I just took the latest code (March 8th).  Without disabling these options, session is immediately disconnected after connect. Unable to connect the session without disabling these options.

**Comment by akallabeth** [comment]
@mvojjala This is #3134, just disable async options in debug settings.

**Comment by akallabeth** [comment]
@mvojjala Could you tell if the hang on disconnect still occurs? (just disable async-transport for that test)

**Comment by akallabeth** [comment]
closing due to lack of feedback and not being able to reproduce anything that is not covered by #3238
