### ISSUE TITLE
Segmentation fault (core dumped)  on startup.

### ISSUE THREAD

**Issue by diepes** [FreeRDP/FreeRDP#2425]
I tried my ubuntu distribution xfreerdp, when that core dumped, i cloned and compiled the xfreerdp from github. (2015-02-24)

On startup i get a coredump.
~/Downloads/FreeRDP$ /usr/local/bin/xfreerdp /u:user@domain  /v:10.1.1.1
Segmentation fault (core dumped)
~/Downloads/FreeRDP$

**Comment by bmiklautz** [comment]
@diepes do you have any freerdp package installed from your distribution - in that case it might be that a wrong library is used.  
Can you provide a ldd /usr/local/bin/xfreerdp and a crash dump if possible?
For the crash dump just run in gdb (gdb --args /usr/local/bin/xfreerdp /u:user@domain /v:10.1.1.1) and paste the output of bt if the segfault happens.

You can also try our nightly packages https://ci.freerdp.com/job/freerdp-nightly-binaries/ to see if you hit the same problem.

**Comment by hardening** [comment]
@diepes is it possible that you would have an exotic keyboard configuration ?

**Comment by bmiklautz** [comment]
@diepes could you try if 
```
/usr/local/bin/xfreerdp /u:user /d:domain /v:10.1.1.1
```
leads to the same result? In that case it is possible to provide us with a back trace or similar?

**Comment by diepes** [comment]
I used xfreerdp now, and it  is working fine.

$ xfreerdp /version
This is FreeRDP version 1.2.1-dev (git 1fd5508)
