### ISSUE TITLE
UPN Suffix doesn't work at all

### ISSUE THREAD

**Issue by Edlanta** [FreeRDP/FreeRDP#2427]
Hi,

i noticed that FreeRDP isn't able to authenticate with a UPN Suffix at all.
If i connect through a TS Gateway Server the following message is displayed:

rts_connect error! Status Code: 401
HTTP/1.1 401 Unauthorized
Content-Type: text/plain
Server: Microsoft-IIS/8.5
WWW-Authenticate: Negotiate
WWW-Authenticate: NTLM
WWW-Authenticate: Basic realm="GATEWAY-SERVER"
X-Powered-By: ASP.NET
Date: Wed, 25 Feb 2015 16:12:26 GMT
Content-Length: 13

rts_connect error!
rpc_connect failed!
Error: protocol security negotiation or connection failure

Without TS Gateway the following message is displayed:

credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure

I compiled the current version from git as described at "Compilation".

I think this has something to do with username parsing. FreeRDP is splitting the username at the @ symbol and uses the string before @ as username and the string after @ as domainname.
For example:   
UPN Suffix: 123456@TEST.test 
will become
Username: 123456
domain: TEST.test

This is the right behaviour if you use Kerberos, but not the right behaviour if you will logon with UPN Suffix.

I changed the username parsing in the following way (freerdp_parse_username() in cmdline.c):
If a domain AND username is given we shouldn't split the username.
If ONLY the username is given we should split the username at the @ sign. And everything before the @ will become settings->Username, and everything after the @ will become settings->Domain
This change will get UPN Suffix working with a normal server, but unfortunately not with TS Gateway.

I will take a look into the NTLM implementation, because i think there is something wrong with Username handling as well.

Can somebody check if this behaviour is reproducible?

I have checked if this is working with a RDP Client from WIndows 7, and indeed it works, with and without TS Gateway.

**Comment by Edlanta** [comment]
Hi,

i found a solution for this problem. If we are using NTLM in combination with a UPN Suffix, we need to make sure that we don't send the Domain in the NTLM authentication mechanism.

Here is the diff of my changes:

diff --git a/winpr/libwinpr/sspi/sspi.c b/winpr/libwinpr/sspi/sspi.c
index f9ec6a7..47aadc5 100644
--- a/winpr/libwinpr/sspi/sspi.c
+++ b/winpr/libwinpr/sspi/sspi.c
@@ -310,7 +310,9 @@ void sspi_SetAuthIdentity(SEC_WINNT_AUTH_IDENTITY* identity, char* user, char* d
                identity->UserLength = 0;
        }
 
-       if (domain)
+       //      edited this line for handling UPN Suffixes. 
+       //      If Username is in UPN format we shouldn't send the Domain in NTLM authentication
+       if (domain && (strstr(user, "@")) == NULL)
        {
                identity->DomainLength = ConvertToUnicode(CP_UTF8, 0, domain, -1, &identity->Domain, 0) - 1;
        }


diff --git a/client/common/cmdline.c b/client/common/cmdline.c
index a894a94..fe588ad 100644
--- a/client/common/cmdline.c
+++ b/client/common/cmdline.c
@@ -1094,6 +1094,10 @@ int freerdp_client_settings_parse_command_line_arguments(rdpSettings* settings,
        DWORD flags;
        BOOL compatibility;
        COMMAND_LINE_ARGUMENT_A* arg;
+       char* username = NULL;
+       char* gw_username = NULL;
+       char* user;
+       char* domain;
 
        compatibility = freerdp_client_detect_command_line(argc, argv, &flags);
 
@@ -1311,6 +1315,8 @@ int freerdp_client_settings_parse_command_line_arguments(rdpSettings* settings,
 
                        settings->Username = user;
                        settings->Domain = domain;
+
+                       username = _strdup(arg->Value);
                }
                CommandLineSwitchCase(arg, "d")
                {
@@ -1358,6 +1364,7 @@ int freerdp_client_settings_parse_command_line_arguments(rdpSettings* settings,
                        settings->GatewayUsername = user;
                        settings->GatewayDomain = domain;
 
+                       gw_username = _strdup(arg->Value);
                        settings->GatewayUseSameCredentials = FALSE;
                }
                CommandLineSwitchCase(arg, "gd")
@@ -1749,6 +1756,31 @@ int freerdp_client_settings_parse_command_line_arguments(rdpSettings* settings,
                CommandLineSwitchEnd(arg)
        }
        while ((arg = CommandLineFindNextArgumentA(arg)) != NULL);
+       
+
+       // Check if Username is set and Domain is missing.
+       // If this is the case we should split Username and Domain at the @ sign (e.g. for Kerberos)
+       // Else we should let the username string as it is (e.g. for UPN Suffix)
+       if (username && !settings->Domain)
+       {
+         freerdp_parse_username(username, &user, &domain);
+         
+         settings->Username = user;
+         settings->Domain = domain;
+       }
+       else
+         settings->Username = username;
+       
+       // Same as above for Gateway Username and Domain.
+       if (gw_username && !settings->GatewayDomain)
+       {
+         freerdp_parse_username(gw_username, &user, &domain);
+         
+         settings->GatewayUsername = user;
+         settings->GatewayDomain = domain;
+       }
+       else
+         settings->GatewayUsername = gw_username;
 
        freerdp_performance_flags_make(settings);
 




These changes are working for me. I can now logon with UPN Suffix to a win2012r2 Server and additionally to a win2012r2 Server which is behind a 2012 TS Gateway Server.
But this changes have some restrictions:
- If you want to use UPN Suffix Logon, you MUST enter a domain name with /d: even if this 
  domain name doesn't exist at all.
- If you want to use UPN Suffix Logon with TS Gateway, you MUST additionally enter a Gateway 
  domain name with /gd: even if this domain name doesn't exist at all.

This restrictions are necessary, because this is the only way we can decide if the username is for Kerberos authentication or for normal authentication with UPN suffix. I explained this in the previous post.


Can somebody try my changes and give some feedback if this is working for you?

You can set a UPN suffix for a user in your Domain Controller.

**Comment by Edlanta** [comment]
Hi,

i found a solution for this problem. If we are using NTLM in combination with a UPN Suffix, we need to make sure that we don't send the Domain in the NTLM authentication mechanism.

Can somebody explain how to post an output of "git diff FILE" ?

The "+" signs in the diff output are doing some strange formatting, so i'm not sure how to do this correctly.

Best Regards

**Comment by akallabeth** [comment]
@Edlanta Does UPN suffix work for you now?

**Comment by akallabeth** [comment]
closing due to lack of feedback.

**Comment by Edlanta** [comment]
Yes this fixed the problem.
