### ISSUE TITLE
freerdp on arm freeze keyboard and mouse when playing a video

### ISSUE THREAD

**Issue by docblock** [FreeRDP/FreeRDP#2429]
Hello,
I compiled freerdp master and 1.2.0-beta1+android9 on a raspberry pi 2 as well as on a cubieboard 2.
Both are using a Cortex-a7 arm cpu. The error is always the same. 
The display connected is 1080p HDMI. The client is Windows 7 64 Bit.
When I start to play a video (in browser as well as in Windows media player) the keyboard  and mouse stops working after few seconds. Same in windowed and fullscreen mode. In windowed mode I can only move the complete freerdp window, but I cannot close the window by the close button. Only strg C on command line works when a video is playing.
I tried many Switches:
-offscreen-cache has no influence
+compression, and  +async-input seems to improve but do not solve completely the issue
that means, when the window with the video is small enough, I can interact with mouse and Keyboard.
On raspberry pi2 the cpu usage never is over 70%.
The issue depends a little bit on the window manager. When I use LXDE very small Video Windows leads to a freeze. When I use XFCE, only big videos windows leads to the freeze.
The situation is getting worse, when I compile Freerdp with gstreamer1.0. In this situation even small video windows leads to the freeze.
In most tests I used bpp=16 and Network=lan as connection parameters. bpp=32 leads to a slide show, when playing a Video.
Do you have any suggestions, what I can do?
Thanks,
Andreas

**Comment by docblock** [comment]
Hello,
I did some more research about the issue. The size of the video is not so important. When there is only a few movement, also big video windows react normal. If there is much movement, also small Video windows have the issue. So the amount of data transferred is important.
The switch +async-input is important. If it is set, the rest of the xwindow system works. I can also close a not responding rdp window from console with strg+c.
I looked a little bit inside the code. It seems as if the main loop in xf_client.c   stops, while playing a video. For testing, I inserted in xf_unlock_x11 a call to xf_event_process. So I can see, that fastpath_send_input_pdu is called immediately after some action. But the reaction of the screen is delayed for about 5 seconds. 
Thanks,
Andreas

**Comment by docblock** [comment]
Hello,
I found the reason. The problem is the function transport_check_fds in file transport.c. It is indirectly called in xf_client_thread of file xf_client.c. In transport_check_fds is a loop, which reads all available PDUs. On my platform the data from network is delivered so fast but processed so slowly, that the loop never ends. A partly working solution is the experimental switch +async-transport. With this switch the GUI is responsive even when a video is played. There is a little problem with this switch. The mouse pointer is not stable. It sometimes disappears. It reappears when the user moves the mouse.
Thanks,
Andreas

**Comment by justbalance** [comment]
+async-transport is very buggy on my arm linux boxes. I have found that if I set the LAN connection to 10/half duplex and use the +async-update +async-input switches that the clients do not freeze anymore but video and audio streaming have glitches.

**Comment by akallabeth** [comment]
Current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef has great improvements. Input is still laggy if the CPU is under heavy load but it reacts after a short delay.
Closing.
