### ISSUE TITLE
Implementation of errors listed in error.h

### ISSUE THREAD

**Issue by tomas-korec** [FreeRDP/FreeRDP#2432]
Hi, I use FreeRDP with Remmina and I think this combination is much better than Windows RDP Client. So good job! :) However, there are som things I didn't like that much, so I decided to tell you about them, so FreeRDP and Remmina can improve.

I think that informing user about errors that happens can be improved. I have created this issue: https://github.com/FreeRDP/Remmina/issues/498 and giox069 (his comment: https://github.com/FreeRDP/Remmina/issues/498#issuecomment-75594933 ) discovered that FreeRDP returns the same error code for any type of error. Could you implement more error codes, so Remmina can inform user about type of error that happened?

Thank you!
Tomas

**Comment by weberhofer** [comment]
see also #4555

**Comment by akallabeth** [comment]
We're quite limited in finding out what exactly caused an error, but #4555 is a first step and has been integrated today.

**Comment by akallabeth** [comment]
this has improved, closing.
