### ISSUE TITLE
OSX 10.10 Yosemite, can't find binary?

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#2444]
Hey all,

So after downloading the latest code from github, making, and installing freerdp. I can't seem to run it. On linux I use the command xfreerdp, however, when I run that it can't find the command. Any hints?

Quick update, if I search for it in spotlight I can see a folder in the freerdp source directory client/Mac/cli/MacFreeRDP.app. 

Thanks

**Comment by hardening** [comment]
This kind of question is not an issue, go and ask on IRC or the FreeRDP mailing list.
