### ISSUE TITLE
Certficate Name Check Should be Case-INsensitive

### ISSUE THREAD

**Issue by KenHolloway** [FreeRDP/FreeRDP#2445]
Since DNS names are not case sensitive, the comparison of the certificate names to the host name (or the certificate name specified on the command line) should also be case-insensitive - www.google.com should match www.Google.com.

**Comment by WarheadsSE** [comment]
I've been hitting this horribly as well. Looking into it at the moment, as I now have people clamoring (rightfully) about this.

**Comment by WarheadsSE** [comment]
This should now be closable.
