### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ivan-83** [FreeRDP/FreeRDP#2449]
Crash then music is playing and press  CTRL+ALT+ENTER to exit full screen mode.
Without +async-update +async-input - no crashes.

xfreerdp /sec:nla -encryption /bpp:24 +decorations +window-drag +aero /multimedia /gdi:sw /f /network:lan +async-update +async-input /u:XXX /p:YYY /v:192.168.0.5 /sound:sys:alsa,format:1
[01:37:23:516] [40255:0d007400] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[01:37:23:516] [40255:0d007400] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[01:37:23:570] [40255:0d007400] [WARN][com.freerdp.core.gcc] - Server uses non-advertised encryption method 0x00000000
[01:37:23:605] [40255:0d007400] [ERROR][com.freerdp.locale] - Unable to detect time zone
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
ALSA lib pcm.c:7905:(snd_pcm_recover) underrun occurred
Segmentation fault (core dumped)
Exit 139
rim@rimwks# gdb /home/rim/docs/Progs/FreeRDP/client/X11/xfreerdp ./xfreerdp.core                                                                                GNU gdb 6.1.1 [FreeBSD]
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-marcel-freebsd"...
Core was generated by `xfreerdp'.
Program terminated with signal 11, Segmentation fault.
Reading symbols from /usr/local/lib/libxfreerdp-client.so.1.2...done.
Loaded symbols for /usr/local/lib/libxfreerdp-client.so.1.2
Reading symbols from /usr/local/lib/libXinerama.so.1...done.
Loaded symbols for /usr/local/lib/libXinerama.so.1
Reading symbols from /usr/local/lib/libXcursor.so.1...done.
Loaded symbols for /usr/local/lib/libXcursor.so.1
Reading symbols from /usr/local/lib/libXv.so.1...done.
Loaded symbols for /usr/local/lib/libXv.so.1
Reading symbols from /usr/local/lib/libXrender.so.1...done.
Loaded symbols for /usr/local/lib/libXrender.so.1
Reading symbols from /usr/local/lib/libXfixes.so.3...done.
Loaded symbols for /usr/local/lib/libXfixes.so.3
Reading symbols from /usr/local/lib/libfreerdp-client.so.1.2...done.
Loaded symbols for /usr/local/lib/libfreerdp-client.so.1.2
Reading symbols from /usr/local/lib/libavcodec.so.55...done.
Loaded symbols for /usr/local/lib/libavcodec.so.55
Reading symbols from /usr/local/lib/libavutil.so.52...done.
Loaded symbols for /usr/local/lib/libavutil.so.52
Reading symbols from /usr/local/lib/libgstreamer-1.0.so.0...done.
Loaded symbols for /usr/local/lib/libgstreamer-1.0.so.0
Reading symbols from /usr/local/lib/libglib-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libglib-2.0.so.0
Reading symbols from /usr/local/lib/libgobject-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgobject-2.0.so.0
Reading symbols from /usr/local/lib/libgstbase-1.0.so.0...done.
Loaded symbols for /usr/local/lib/libgstbase-1.0.so.0
Reading symbols from /usr/local/lib/libgstapp-1.0.so.0...done.
Loaded symbols for /usr/local/lib/libgstapp-1.0.so.0
Reading symbols from /usr/local/lib/libgstvideo-1.0.so.0...done.
Loaded symbols for /usr/local/lib/libgstvideo-1.0.so.0
Reading symbols from /usr/local/lib/libXext.so.6...done.
Loaded symbols for /usr/local/lib/libXext.so.6
Reading symbols from /usr/local/lib/libfreerdp.so.1.2...done.
Loaded symbols for /usr/local/lib/libfreerdp.so.1.2
Reading symbols from /usr/local/lib/libX11.so.6...done.
Loaded symbols for /usr/local/lib/libX11.so.6
Reading symbols from /usr/local/lib/libxkbfile.so.1...done.
Loaded symbols for /usr/local/lib/libxkbfile.so.1
Reading symbols from /usr/local/lib/libwinpr.so.1.1...done.
Loaded symbols for /usr/local/lib/libwinpr.so.1.1
Reading symbols from /usr/lib/librt.so.1...done.
Loaded symbols for /usr/lib/librt.so.1
Reading symbols from /usr/local/lib/libssl.so.8...done.
Loaded symbols for /usr/local/lib/libssl.so.8
Reading symbols from /usr/local/lib/libcrypto.so.8...done.
Loaded symbols for /usr/local/lib/libcrypto.so.8
Reading symbols from /lib/libz.so.6...done.
Loaded symbols for /lib/libz.so.6
Reading symbols from /lib/libm.so.5...done.
Loaded symbols for /lib/libm.so.5
Reading symbols from /usr/lib/libexecinfo.so.1...done.
Loaded symbols for /usr/lib/libexecinfo.so.1
Reading symbols from /lib/libthr.so.3...done.
Loaded symbols for /lib/libthr.so.3
Reading symbols from /usr/local/lib/libasound.so.2...done.
Loaded symbols for /usr/local/lib/libasound.so.2
Reading symbols from /lib/libc.so.7...done.
Loaded symbols for /lib/libc.so.7
Reading symbols from /usr/local/lib/libswresample.so.0...done.
Loaded symbols for /usr/local/lib/libswresample.so.0
Reading symbols from /usr/local/lib/libva.so.1...done.
Loaded symbols for /usr/local/lib/libva.so.1
Reading symbols from /usr/local/lib/libxvidcore.so.4...done.
Loaded symbols for /usr/local/lib/libxvidcore.so.4
Reading symbols from /usr/local/lib/libx265.so.43...done.
Loaded symbols for /usr/local/lib/libx265.so.43
Reading symbols from /usr/local/lib/libx264.so.142...done.
Loaded symbols for /usr/local/lib/libx264.so.142
Reading symbols from /usr/local/lib/libvpx.so.1...done.
Loaded symbols for /usr/local/lib/libvpx.so.1
Reading symbols from /usr/local/lib/libvorbisenc.so.2...done.
Loaded symbols for /usr/local/lib/libvorbisenc.so.2
Reading symbols from /usr/local/lib/libvorbis.so.0...done.
Loaded symbols for /usr/local/lib/libvorbis.so.0
Reading symbols from /usr/local/lib/libtheoraenc.so.1...done.
Loaded symbols for /usr/local/lib/libtheoraenc.so.1
Reading symbols from /usr/local/lib/libtheoradec.so.1...done.
Loaded symbols for /usr/local/lib/libtheoradec.so.1
Reading symbols from /usr/local/lib/libschroedinger-1.0.so.0...done.
Loaded symbols for /usr/local/lib/libschroedinger-1.0.so.0
Reading symbols from /usr/local/lib/libopus.so.0...done.
Loaded symbols for /usr/local/lib/libopus.so.0
Reading symbols from /usr/local/lib/libgsm.so.1...done.
Loaded symbols for /usr/local/lib/libgsm.so.1
Reading symbols from /usr/local/lib/libaacplus.so.2...done.
Loaded symbols for /usr/local/lib/libaacplus.so.2
Reading symbols from /usr/local/lib/libgmodule-2.0.so.0...done.
Loaded symbols for /usr/local/lib/libgmodule-2.0.so.0
Reading symbols from /usr/local/lib/libintl.so.8...done.
Loaded symbols for /usr/local/lib/libintl.so.8
Reading symbols from /usr/local/lib/libicui18n.so.53...done.
Loaded symbols for /usr/local/lib/libicui18n.so.53
Reading symbols from /usr/local/lib/libiconv.so.2...done.
Loaded symbols for /usr/local/lib/libiconv.so.2
Reading symbols from /usr/local/lib/libpcre.so.3...done.
Loaded symbols for /usr/local/lib/libpcre.so.3
Reading symbols from /usr/local/lib/libffi.so.6...done.
Loaded symbols for /usr/local/lib/libffi.so.6
Reading symbols from /usr/local/lib/liborc-0.4.so.0...done.
Loaded symbols for /usr/local/lib/liborc-0.4.so.0
Reading symbols from /usr/local/lib/libxcb.so.1...done.
Loaded symbols for /usr/local/lib/libxcb.so.1
Reading symbols from /usr/lib/librpcsvc.so.5...done.
Loaded symbols for /usr/lib/librpcsvc.so.5
Reading symbols from /usr/lib/libelf.so.1...done.
Loaded symbols for /usr/lib/libelf.so.1
Reading symbols from /lib/libgcc_s.so.1...done.
Loaded symbols for /lib/libgcc_s.so.1
Reading symbols from /usr/lib/libc++.so.1...done.
Loaded symbols for /usr/lib/libc++.so.1
Reading symbols from /lib/libcxxrt.so.1...done.
Loaded symbols for /lib/libcxxrt.so.1
Reading symbols from /usr/local/lib/libogg.so.0...done.
Loaded symbols for /usr/local/lib/libogg.so.0
Reading symbols from /usr/local/lib/libfftw3f.so.3...done.
Loaded symbols for /usr/local/lib/libfftw3f.so.3
Reading symbols from /usr/local/lib/libicuuc.so.53...done.
Loaded symbols for /usr/local/lib/libicuuc.so.53
Reading symbols from /usr/local/lib/libicudata.so.53...done.
Loaded symbols for /usr/local/lib/libicudata.so.53
Reading symbols from /usr/local/lib/libXau.so.6...done.
Loaded symbols for /usr/local/lib/libXau.so.6
Reading symbols from /usr/local/lib/libpthread-stubs.so.0...done.
Loaded symbols for /usr/local/lib/libpthread-stubs.so.0
Reading symbols from /usr/local/lib/libXdmcp.so.6...done.
Loaded symbols for /usr/local/lib/libXdmcp.so.6
Reading symbols from /usr/local/lib/alsa-lib/libasound_module_ctl_oss.so...done.
Loaded symbols for /usr/local/lib/alsa-lib/libasound_module_ctl_oss.so
Reading symbols from /usr/local/lib/alsa-lib/libasound_module_pcm_oss.so...done.
Loaded symbols for /usr/local/lib/alsa-lib/libasound_module_pcm_oss.so
Reading symbols from /libexec/ld-elf.so.1...done.
Loaded symbols for /libexec/ld-elf.so.1
#0  0x0000000805cd3e1a in thr_kill () from /lib/libc.so.7
[New Thread 80ec1a400 (LWP 100927/xfreerdp)]
[New Thread 80dc68000 (LWP 100838/xfreerdp)]
[New Thread 80dc67c00 (LWP 100687/xfreerdp)]
[New Thread 80dc67800 (LWP 100629/xfreerdp)]
[New Thread 80dc67400 (LWP 100569/xfreerdp)]
[New Thread 80d007400 (LWP 100392/xfreerdp)]
[New Thread 80d006400 (LWP 100350/xfreerdp)]
(gdb) bt
#0  0x0000000805cd3e1a in thr_kill () from /lib/libc.so.7
#1  0x0000000803cd5056 in fatal_handler (signum=11) at /home/rim/docs/Progs/FreeRDP/libfreerdp/utils/signal.c:68
#2  0x000000080576347a in swapcontext () from /lib/libthr.so.3
#3  0x0000000805763062 in sigaction () from /lib/libthr.so.3
#4  <signal handler called>
#5  0x0000000804099092 in XPutImage () from /usr/local/lib/libX11.so.6
#6  0x000000080083f893 in xf_sw_end_paint (context=0x80d053000) at /home/rim/docs/Progs/FreeRDP/client/X11/xf_client.c:316
#7  0x0000000803d8d697 in update_message_process_update_class (proxy=0x80dcc5800, msg=0x7fffdf9fae38, type=2)
    at /home/rim/docs/Progs/FreeRDP/libfreerdp/core/message.c:1093
#8  0x0000000803d87d04 in update_message_process_class (proxy=0x80dcc5800, msg=0x7fffdf9fae38, msgClass=1, msgType=2)
    at /home/rim/docs/Progs/FreeRDP/libfreerdp/core/message.c:1899
#9  0x0000000803d87c67 in update_message_queue_process_message (update=0x80d08da00, message=0x7fffdf9fae38)
    at /home/rim/docs/Progs/FreeRDP/libfreerdp/core/message.c:1945
#10 0x0000000803d8c021 in update_message_proxy_thread (arg=0x80d08da00) at /home/rim/docs/Progs/FreeRDP/libfreerdp/core/message.c:2194
#11 0x0000000804642251 in thread_launcher (arg=0x80dd242c0) at /home/rim/docs/Progs/FreeRDP/winpr/libwinpr/thread/thread.c:259
#12 0x000000080575e4f5 in pthread_create () from /lib/libthr.so.3
#13 0x0000000000000000 in ?? ()

**Comment by hardening** [comment]
@ivan-83 do you get something interesting with valgrind ?

**Comment by bmiklautz** [comment]
I'm not sure but I think this (or a similar) problem was fixed on master recently

**Comment by ivan-83** [comment]
yes, that fixed
