### ISSUE TITLE
RemoteFX not working

### ISSUE THREAD

**Issue by docblock** [FreeRDP/FreeRDP#2451]
Hello,
I compiled freerdp master without gstreamer, without FFMPEG with openH264 on a raspberry pi 2.
It is using a Cortex-a7 arm cpu. The client is a virtual machine on a Win2K12R2 Server. The virtual machine is Windows 7 Enterprise 32 Bit. RemoteFX is working when I use mstsc from Microsoft.
The command line, I used is:
xfreerdp /v:cobramt004 /cert-ignore  /bpp:32 /u:username /d:domain /network:lan /rfx +aero /sec:nla

The connection establishes without any problems. But when I start a 3D Benchmark, the session crashes. Additionally I have a Program, which needs a real graphic card. This program doesn't find the graphic card.

Thanks,
Andreas

**Comment by hardening** [comment]
@docblock I don't see the relation between remoteFx and the 3D benchmark. Could you elaborate ?

**Comment by nfedera** [comment]
@docblock please also elaborate on "the session crashes".  Disconnect? Segfault? Any errors printed?

**Comment by docblock** [comment]
I hope I am not too late.
@hardening: remoteFx simulates a 3D graphics card. With remotFX I can run DirectX-Applications. The 3D benchmark tries to open a direct surface, what fails.
@nfedera : The session disconnects. It displays: Failed to check FreeRDP file descriptor

**Comment by hardening** [comment]
@docblock  AFAICT 3D and remoteFx aren't related

**Comment by alantm2** [comment]
Hi, I am getting the same error (Failed to check FreeRDP file descriptor) under similar circumstances.

Please note that #2819 appears to be the same issue although the disconnects occur shortly after starting playing back video (youtube) -- the same issue I am having.
Please note that #2850 appears to be the same issue although the target system is a windows client.

**Comment by akallabeth** [comment]
working in current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
