### ISSUE TITLE
Unable to copy files from a remote RDP server (fully updated Windows 2008) to a Linux PC

### ISSUE THREAD

**Issue by birdie-github** [FreeRDP/FreeRDP#2454]
I'm running freerdp-1.2.0-0.4.beta.1.

The remote server is a Windows 2008 server with all updates installed. Some recent Windows update or freerdp update has broken files copying from the server to my Linux PC.

The most I can copy is 10MB of data. Then connection gets lost.

**Comment by hardening** [comment]
could you give a try with last master ? Thank you.
