### ISSUE TITLE
Unable to compile FreeRDP on Raspbery Pi 2 Model B 1GB on raspbian

### ISSUE THREAD

**Issue by jasjitchopra** [FreeRDP/FreeRDP#2464]
I am running the following command and getting these errors while compiling FreeRDP on raspberry pi 2 model B 1GB running raspbain:
cmake -DTARGET_ARCH=ARM -DWITH_NEON=OFF .

What am I doing wrong here? I am fairly new to Linux.

-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- FreeRDP GIT-dirty
-- Git Revision 5d3fa29
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Success
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Success
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Success
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Success
-- Performing Test Wimplicit-function-declaration
-- Performing Test Wimplicit-function-declaration - Success
-- Performing Test Wredundant-decls
-- Performing Test Wredundant-decls - Success
-- Performing Test Wno-builtin-macro-redefined
-- Performing Test Wno-builtin-macro-redefined - Success
-- Performing Test Wno-builtin-macro-redefinedCXX
-- Performing Test Wno-builtin-macro-redefinedCXX - Success
-- Looking for include file /usr/include/fcntl.h
-- Looking for include file /usr/include/fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found.
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found.
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found.
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found.
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for pthread_tryjoin_np in pthread
-- Looking for pthread_tryjoin_np in pthread - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Found X11: /usr/lib/arm-linux-gnueabihf/libX11.so  
-- Finding recommended feature Wayland for Wayland (Wayland client)
--     Disable feature Wayland using "-DWITH_WAYLAND=OFF"
-- checking for module 'wayland-client'
--   package 'wayland-client' not found
-- Could NOT find WAYLAND (missing:  WAYLAND_LIBRARY WAYLAND_INCLUDE_DIR) 
CMake Warning at cmake/FindWayland.cmake:57 (message):
  Couldn't detect wayland version - no version check is done
Call Stack (most recent call first):
  cmake/FindFeature.cmake:25 (find_package)
  CMakeLists.txt:560 (find_feature)

CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature Wayland was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:560 (find_feature)

-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /usr/lib/arm-linux-gnueabihf/libz.so (found version "1.2.7") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (found version "1.0.1e") 
-- Skipping optional feature OpenSLES for multimedia (OpenSLES audio / video)
--     Enable feature OpenSLES using "-DWITH_OPENSLES=ON"
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Could NOT find ALSA (missing:  ALSA_LIBRARY ALSA_INCLUDE_DIR) 
CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature ALSA was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:570 (find_feature)

-- Skipping optional feature Pulse for sound (audio input, audio output and multimedia redirection)
--     Enable feature Pulse using "-DWITH_PULSE=ON"
-- Skipping optional feature Cups for printing (printer device redirection)
--     Enable feature Cups using "-DWITH_CUPS=ON"
-- Skipping optional feature PCSC for smart card (smart card device redirection)
--     Enable feature PCSC using "-DWITH_PCSC=ON"
-- Finding recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Disable feature FFmpeg using "-DWITH_FFMPEG=OFF"
-- checking for module 'libavcodec'
--   package 'libavcodec' not found
-- checking for module 'libavutil'
--   package 'libavutil' not found
-- Could NOT find FFmpeg (missing:  AVUTIL_FOUND AVCODEC_FOUND) 
Note: To build libavcodec version >= 0.8 (API >= 53.25.0) is required
CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature FFmpeg was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:576 (find_feature)

-- Skipping optional feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
--     Enable feature GStreamer_0_10 using "-DWITH_GSTREAMER_0_10=ON"
-- Finding recommended feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
--     Disable feature GStreamer_1_0 using "-DWITH_GSTREAMER_1_0=OFF"
-- checking for module 'glib-2.0'
--   package 'glib-2.0' not found
Glib_INCLUDE_DIR=Glib_INCLUDE_DIR-NOTFOUND
GlibConfig_INCLUDE_DIR=GlibConfig_INCLUDE_DIR-NOTFOUND
Glib_LIBRARY=Glib_LIBRARY-NOTFOUND
Gobject_LIBRARY=Gobject_LIBRARY-NOTFOUND
CMake Error at cmake/LibFindMacros.cmake:74 (message):
  Required library Glib NOT FOUND.

  Install the library (dev version) and try again.  If the library is already
  installed, use ccmake to set the missing variables manually.
Call Stack (most recent call first):
  cmake/FindGlib.cmake:41 (libfind_process)
  cmake/FindGStreamer_1_0.cmake:80 (find_package)
  cmake/FindFeature.cmake:25 (find_package)
  CMakeLists.txt:579 (find_feature)

-- Configuring incomplete, errors occurred!

**Comment by psraju** [comment]
It seams you don't have some packages installed. try to build after installing these packages glib-2.0,libavutil, wayland-client and alsa

**Comment by jasjitchopra** [comment]
Same exact errors after installing glib-2.0 and alsa.

sudo apt-get install was not able to find packages libavutil and wayland-client

**Comment by hardening** [comment]
@jasjitchopra that doesn't look like a FreeRDP bug but more like something you may do on your installation. Have you tried setting values as suggested by the cmake output ?

**Comment by macarthor** [comment]
you should install "development" package for each software you are missing. if you are on ubuntu, you should try: sudo apt-get install libglib2.0-dev libasound2-dev libpulse-dev. NOTE: what i am typing may not be exact the software name, use TAB key in apt-get to get the correct package name.

PS: better read the freerdp wiki before you build your own version of freerdp :)
