### ISSUE TITLE
ARM Linux Video Play  Issue 

### ISSUE THREAD

**Issue by tobewalker** [FreeRDP/FreeRDP#2471]
I have run stable-v1.1 on my ARM Board ,
Every thing is OK ,but I can't  paly 1080P video smoothly on server ,
My board can play this video well on local video player ,such as vlc  
Does FreeRDP support OpenGL/OpenGLES ?
I think gpu on board is not worked ,
Any suggestion  ? thanks !

**Comment by WarheadsSE** [comment]
Videos are not played with GL/GLES anyways. Your best bet is a proper gst backend for freerdp to pass the video to.
