### ISSUE TITLE
iOS Client black screen after keyboard show

### ISSUE THREAD

**Issue by kaizirlewagen** [FreeRDP/FreeRDP#2477]
I use the latest FreeRDP version with Mac OS X 10.9.5 64-Bit and XCode 6.1 SDK 8.1. The iFreeRDP app has some problems with the screen if the keyboard is shwon. In landscape mode if the rdp session is established and i click to show the keyboard, the screen will be black. 

![ok](https://cloud.githubusercontent.com/assets/8393808/6684189/ff58c12c-cc8e-11e4-929e-807f151c39b6.jpg)

After a click on the keyboard button
![error](https://cloud.githubusercontent.com/assets/8393808/6684192/04bc6c72-cc8f-11e4-89df-bbc4ed8c74e2.jpg)

In portrait mode the rdp desktop will be pushed upwards if the keyboard is shown, but after hiding the keyboard the screen has some black parts at the bottom.

Do you have an idea for this issue?

**Comment by phongleq** [comment]
This happened because the scrollview calculation for moving the RDP view is off. It is moving it higher than it should. I believe its currently moving it out side of the screen scope.

**Comment by lanscene** [comment]
@phongleq you got it
@kaizirlewagen the keyboard layout calculation in RDPSessionViewController.m(master branch) is wrong,  you have to use source code slice in stable-1.1 branch. you should replace related functions with keyboardWillShow/keyboardDidShow/keyboardWillHide/keyboardDidHide in stable-1.1 branch.

**Comment by kaizirlewagen** [comment]
@phongleq 
@lanscene 

Thank you for the answer, i will check it out.
