### ISSUE TITLE
Does FreeRDP store RDS Per-Device CALs?

### ISSUE THREAD

**Issue by greensolid** [FreeRDP/FreeRDP#2495]
I have the issue that each freerdp client gets multiple per-device CALs issued, although it's the same device with the same MAC, DNS and IP.
If I read the code correctly, freerdp uses the MAC as hardware id, so the only question that remains is, does freerdp also store temporary / permanent RDS CALs?

My source:
http://www.virtualizationadmin.com/articles-tutorials/terminal-services/licensing/terminal-services-cal-allocation-process-part2.html

Thanks

**Comment by dbungert** [comment]
I looked into this problem some months back.  FreeRDP doesn't attempt to cache the license.  I experimented with saving off a copy and sending it back per RDPELE spec, but I never saw any difference in behavior.  That said, I never observed a case where multiple licenses were being issued to one device - the license server always sent me the same bits and the license manager didn't report multiple licenses for that device.

If you're still observing this problem, please report back on what Server OS is in use, as the license server behavior varies between 2003/2008/2012.

**Comment by T3N4K4** [comment]
@dbungert, could you please send me a reference to your code where you tried to save off a copy?
I have a similar problem and want to try if your experiment helps me.

**Comment by geiseri** [comment]
@dbungert did you ever get feedback?  I have two configurations that are exhibiting this issue.  Is there a way to log these "bits" that could further diagnose this?

**Comment by IT-Alex-2016** [comment]
I have this issue with a 2008 R2 Session Host with a 2012 R2 License Server. It is remote sites with the license servers ran centrally, so there is possibility for the WAN link to be down. When this happens any freerdp clients refuse to connect as they don't cache the cal as expected. Thankfully we don't have many of these left as we have been steadily repolacing with rdesktop as this does work correctly

**Comment by akallabeth** [comment]
#4979 should address these issues.
