### ISSUE TITLE
USB redirection is broken in master

### ISSUE THREAD

**Issue by TaGUNil** [FreeRDP/FreeRDP#2496]
Resetting dynamic channel count in commit b621c542c4da5ea3d02043439b86a85c079a4f8e discards all dynamic channels added while parsing command line, such as urbdrc.

**Comment by TaGUNil** [comment]
I can't propose a fix, because I don't understand what was the purpose of this change.

**Comment by akallabeth** [comment]
@TaGUNil The purpose was to allow reconnecting. Would it be possible to separate command line parsing from actually loading channels?

**Comment by bmiklautz** [comment]
@TaGUNil would you add the command line you are using?

**Comment by bmiklautz** [comment]
@TaGUNil this is already fixed on master. Please your git branches.

**Comment by TaGUNil** [comment]
@bmiklautz ah, sorry. I'll check again if it is my mistake.

**Comment by TaGUNil** [comment]
So, it was just reverted in that monstrous OSS commit. And what about the reconnecting?

**Comment by bmiklautz** [comment]
@TaGUNil the fix was broken anyway. I think for xfreerdp that shouldn't matter.
