### ISSUE TITLE
Update my older freerdp commit

### ISSUE THREAD

**Issue by shattars3d** [FreeRDP/FreeRDP#2500]
hey, i was just wondering if i was working on a older commit of freerdp, and i can update it to the latest master without having over writing my fixes i had for the older freerdp core files..?

is that possible?..     

this url link is the comparison of the master and the one i am using..

https://github.com/FreeRDP/FreeRDP/compare/90936e64845195e5bea396ed90c63635cce2f0a3...master

**Comment by bmiklautz** [comment]
@shattars3d I would recommend to read some howto or book on git.
Depending on what you want todo you can either just merge the latest master changes ore rebase your changes onto master. In both cases if there a conflicting changes you need to resolve the conflict.

If you need help join our irc channel or send a mail to the mailing list but pleas don't use the issue tracker as help forum.
