### ISSUE TITLE
If it's possible, please add hi dpi support

### ISSUE THREAD

**Issue by Alysko** [FreeRDP/FreeRDP#2504]
Since RDP 8.1 and with Win7, Win 8 and Server 2012 R2, hi dpi scaling is possible on RDP, which is necessary for full HD display on 13'' or 4K on 27''.
Thanks.

**Comment by bmiklautz** [comment]
@Alysko I'm not exactly sure what you mean? Can you give more details? E.g. what currently doesn't work and what client your are talking about?

**Comment by Alysko** [comment]
All works fine. It's not a bug, it's a feature :) See that http://blogs.msdn.com/b/rds/archive/2013/12/16/resolution-and-scaling-level-updates-in-rdp-8-1.aspx

**Comment by colemickens** [comment]
You want #2438.

**Comment by akallabeth** [comment]
Implemented in current master (scaling command line options)

**Comment by Alysko** [comment]
Great :+1:
