### ISSUE TITLE
Can't compile on xCode6.1

### ISSUE THREAD

**Issue by interator** [FreeRDP/FreeRDP#2518]
After running the following comand:
cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode
I was able to create the xCode project file, but can't compile the project.
I have about 60 errors, most of them because of unsupported architecture.
WhT Should i define in the Build setting architecture, valid architecture, and active architecture?

**Comment by bmiklautz** [comment]
@interator for iOS currently only i386 and arm are supported properly. Are you using one of those and what are the errors you are getting?

**Comment by interator** [comment]
My Errors:
CompileC /Users/asafinterator/desktop/FreeRDP-master/channels/cliprdr/client/FreeRDP.build/Debug-iphonesimulator/cliprdr-client.build/Objects-normal/i386/cliprdr_format.o channels/cliprdr/client/cliprdr_format.c normal i386 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/asafinterator/Desktop/FreeRDP-master
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch i386 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O2 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug-iphonesimulator\" -DHAVE_CONFIG_H -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -fexceptions -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -g -Wno-sign-conversion -mios-simulator-version-min=7.1 -I/Users/asafinterator/desktop/FreeRDP-master/channels/cliprdr/client/Debug-iphonesimulator/include -I/Users/asafinterator/desktop/FreeRDP-master -I/Users/asafinterator/desktop/FreeRDP-master/include -I/Users/asafinterator/desktop/FreeRDP-master/winpr/include -I/Users/asafinterator/desktop/FreeRDP-master/channels/cliprdr/client/FreeRDP.build/Debug-iphonesimulator/cliprdr-client.build/DerivedSources/i386 -I/Users/asafinterator/desktop/FreeRDP-master/channels/cliprdr/client/FreeRDP.build/Debug-iphonesimulator/cliprdr-client.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/asafinterator/desktop/FreeRDP-master/channels/cliprdr/client/Debug-iphonesimulator -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -DWINPR_EXPORTS -DFREERDP_EXPORTS -fPIC -MMD -MT dependencies -MF /Users/asafinterator/desktop/FreeRDP-master/channels/cliprdr/client/FreeRDP.build/Debug-iphonesimulator/cliprdr-client.build/Objects-normal/i386/cliprdr_format.d --serialize-diagnostics /Users/asafinterator/desktop/FreeRDP-master/channels/cliprdr/client/FreeRDP.build/Debug-iphonesimulator/cliprdr-client.build/Objects-normal/i386/cliprdr_format.dia -c /Users/asafinterator/Desktop/FreeRDP-master/channels/cliprdr/client/cliprdr_format.c -o /Users/asafinterator/desktop/FreeRDP-master/channels/cliprdr/client/FreeRDP.build/Debug-iphonesimulator/cliprdr-client.build/Objects-normal/i386/cliprdr_format.o

In file included from /Users/asafinterator/Desktop/FreeRDP-master/channels/cliprdr/client/cliprdr_format.c:25:
In file included from /Users/asafinterator/desktop/FreeRDP-master/winpr/include/winpr/crt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/stdio.h:64:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/cdefs.h:680:2: error: Unsupported architecture
#error Unsupported architecture
 ^
In file included from /Users/asafinterator/Desktop/FreeRDP-master/channels/cliprdr/client/cliprdr_format.c:25:
In file included from /Users/asafinterator/desktop/FreeRDP-master/winpr/include/winpr/crt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/stdio.h:67:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/_types.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
#error architecture not supported
 ^
In file included from /Users/asafinterator/Desktop/FreeRDP-master/channels/cliprdr/client/cliprdr_format.c:25:
In file included from /Users/asafinterator/desktop/FreeRDP-master/winpr/include/winpr/crt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/stdio.h:67:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/_types.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_dev_t;         /* dev_t */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'
typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'
typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'
typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
        ^
In file included from /Users/asafinterator/Desktop/FreeRDP-master/channels/cliprdr/client/cliprdr_format.c:25:
In file included from /Users/asafinterator/desktop/FreeRDP-master/winpr/include/winpr/crt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/stdio.h:71:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types/_va_list.h:31:9: error: unknown type name '__darwin_va_list'; did you mean '__builtin_va_list'?
typedef __darwin_va_list va_list;
        ^
note: '__builtin_va_list' declared here
In file included from /Users/asafinterator/Desktop/FreeRDP-master/channels/cliprdr/client/cliprdr_format.c:25:
In file included from /Users/asafinterator/desktop/FreeRDP-master/winpr/include/winpr/crt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/stdio.h:72:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types/_size_t.h:30:9: error: unknown type name '__darwin_size_t'; did you mean '__darwin_ino_t'?
typedef __darwin_size_t        size_t; 
        ^
In file included from /Users/asafinterator/Desktop/FreeRDP-master/channels/cliprdr/client/cliprdr_format.c:25:
In file included from /Users/asafinterator/desktop/FreeRDP-master/winpr/include/winpr/crt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/stdio.h:67:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/_types.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types.h:64:26: note: '__darwin_ino_t' declared here
typedef __darwin_ino64_t __darwin_ino_t;        /* [???] Used for inodes */
                         ^
In file included from /Users/asafinterator/Desktop/FreeRDP-master/channels/cliprdr/client/cliprdr_format.c:25:
In file included from /Users/asafinterator/desktop/FreeRDP-master/winpr/include/winpr/crt.h:23:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/stdio.h:436:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk/usr/include/sys/_types/_ssize_t.h:30:9: error: unknown type name '__darwin_ssize_t'
typedef __darwin_ssize_t        ssize_t; 
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

**Comment by hardening** [comment]
@interator 
#error architecture not supported => looks quite self explanary, isn't it ?
