### ISSUE TITLE
Wsgate not starting

### ISSUE THREAD

**Issue by believeyourself** [FreeRDP/FreeRDP#2523]
I was trying to install freerdp-webconnect in ubuntu 12.04 following the link http://www.freerdp.net/download.html. Atlast when I have tried to start the wsgate daemon by using sudo /etc/init.d/wsgate start , the command executes with no errors. But when i check the wsgate status , it was showing wsgate not running.

**Comment by bmiklautz** [comment]
@believeyourself this is the wrong place for this issue please add this issue to the webconnect issue tracker: https://github.com/FreeRDP/FreeRDP-WebConnect/issues
