### ISSUE TITLE
Smartcard forwarding: wrong string passed to server 

### ISSUE THREAD

**Issue by stefanbaur** [FreeRDP/FreeRDP#2524]
Situation: Trying to forward a smartcard plugged into a REINER SCT cyberJack e-com USB smartcard reader to a Windows 8.1 machine.

xfreerdp from Debian Jessie - which is Version 1.1.0.-beta1 - works, if I specify /smartcard:cyberJack as parameter.  If I try the same with the latest xfreerdp from the nightly builds (1.2.1-dev), strange things happen.

With the Version from Debian Jessie, if I start the "cyberJack device manager" on the windows machine, the reader is displayed as "REINER SCT cyberJack pp_a2 (9043559343) 00 00" and everything works fine. The same with the nightly build returns a reader name of "cyberJack pp_a2 0" and it doesn't pass all the tests in the cyberJack device manager (CTAPI fails, then the device becomes completely inaccessible).

Did you add some kind of input validation for the name string, and made it a little too restrictive, so it hiccups on the "()"'s, maybe? Or what causes the truncated name?

Kind Regards,
Stefan
(sendspamhere ät stefanbaur döt de)

**Comment by akallabeth** [comment]
#4312 fixed a bunch of smartcard related issues bringing it to a usable state again.
Reopen, if your specific issue was not fixed.
