### ISSUE TITLE
RemoteApp causes "double free or corruption (fasttop)" crash

### ISSUE THREAD

**Issue by Rainmaker52** [FreeRDP/FreeRDP#2525]
I have installed freerdp 1.2.1+0~20150408014830.88~1.gbp35892c on Ubuntu 15.04 b2, and am trying to get RemoteApp to work. However, when a menu is opened, the freerdp session crashes with:
*** Error in `./xfreerdp': double free or corruption (fasttop): 0x00007f16340a3140 ***

(the reason I'm using nightly is that the version my distribution comes with, has some serious problems with mouse position; if I click in the right of the window, a button on the left reacts. The GIT version does seem to have that issue fixed).

I am not proficient enough with C to correct the error, but it seems to be caused by the "free" call in  this snippit in libfreerdp/core/window.c:
>        new_str = (BYTE*) realloc(unicode_string->string, new_len);
>        if (!new_str)
>        {
>                free (unicode_string->string);
>                unicode_string->string = NULL;
>                return FALSE;
>        }

Full GDB session:
> (gdb) file /opt/freerdp-nightly/bin/xfreerdp
> Reading symbols from /opt/freerdp-nightly/bin/xfreerdp...Reading symbols from /usr/lib/debug/.build-id/b0/063a7790fab3f27dde7d5bbdbbd587ea4a3212.debug...done.
> done.
> (gdb) run /u:myUser /p:myPass /d:. /v:192.168.56.201 /app:"||calc"
> Starting program: /opt/freerdp-nightly/bin/xfreerdp /u:myUser /p:myPass /d:. /v:192.168.56.201 /app:"||calc"
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> [16:35:21:960] [7209:7210] [INFO][com.freerdp.client.common.cmdline] - loading channel rail
> *** Error in `/opt/freerdp-nightly/bin/xfreerdp': double free or corruption (fasttop): 0x00007fffe40af660 ***
> [New Thread 0x7fffe923c700 (LWP 7211)]
> [New Thread 0x7fffe9a3d700 (LWP 7210)]
> 
> Program received signal SIGABRT, Aborted.
> [Switching to Thread 0x7fffe9a3d700 (LWP 7210)]
> 0x00007ffff7232267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
> 55	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
> (gdb) bt
> #0  0x00007ffff7232267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
> #1  0x00007ffff7233eca in __GI_abort () at abort.c:89
> #2  0x00007ffff7275c53 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7ffff738e1a8 "*** Error in `%s': %s: 0x%s ***n")
> at ../sysdeps/posix/libc_fatal.c:175
> #3  0x00007ffff727dc69 in malloc_printerr (ptr=<optimized out>, str=0x7ffff738e270 "double free or corruption (fasttop)", action=1) at malloc.c:4965
> #4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3834
> #5  0x00007ffff728189c in __GI___libc_free (mem=<optimized out>) at malloc.c:2950
> #6  0x00007ffff5de27e2 in rail_read_unicode_string (s=0x7fffe4081ec0, unicode_string=unicode_string@entry=0x64cb60)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/window.c:49
> #7  0x00007ffff5de32a1 in update_read_window_state_order (s=0x7fffe4081ec0, orderInfo=orderInfo@entry=0x64cb40,
> windowState=windowState@entry=0x64cb50) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/window.c:213
> #8  0x00007ffff5de3492 in update_recv_window_info_order (update=0x645250, s=<optimized out>, orderInfo=0x64cb40)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/window.c:385
> #9  0x00007ffff5de3e94 in update_recv_altsec_window_order (update=update@entry=0x645250, s=<optimized out>)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/window.c:574
> #10 0x00007ffff5db6628 in update_recv_altsec_order (update=0x645250, s=<optimized out>, flags=<optimized out>)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/orders.c:3530
> #11 0x00007ffff5db6dad in update_recv_order (update=update@entry=0x645250, s=s@entry=0x7fffe4081ec0)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/orders.c:3552
> #12 0x00007ffff5dd682e in fastpath_recv_orders (fastpath=0x1, s=0x7fffe4081ec0)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/fastpath.c:205
> #13 fastpath_recv_update (fastpath=fastpath@entry=0x64d400, updateCode=<optimized out>, size=size@entry=88, s=s@entry=0x7fffe4081ec0)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/fastpath.c:265
> #14 0x00007ffff5dd6ef8 in fastpath_recv_update_data (fastpath=fastpath@entry=0x64d400, s=s@entry=0x7fffe40a5930)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/fastpath.c:410
> #15 0x00007ffff5dd7663 in fastpath_recv_updates (fastpath=0x64d400, s=s@entry=0x7fffe40a5930)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/fastpath.c:528
> #16 0x00007ffff5dd3b85 in rdp_recv_fastpath_pdu (s=0x7fffe40a5930, rdp=0x6329e0)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/rdp.c:1167
> #17 rdp_recv_pdu (rdp=rdp@entry=0x6329e0, s=s@entry=0x7fffe40a5930)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/rdp.c:1175
> #18 0x00007ffff5dd3e1b in rdp_recv_callback (transport=<optimized out>, s=0x7fffe40a5930, extra=0x6329e0)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/rdp.c:1276
> #19 0x00007ffff5dda135 in transport_check_fds (transport=transport@entry=0x640420)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/transport.c:752
> #20 0x00007ffff5dd41c8 in rdp_check_fds (rdp=0x6329e0)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/rdp.c:1328
> #21 0x00007ffff5db6e48 in freerdp_check_fds (instance=0x62cf00)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/freerdp.c:208
> #22 0x00007ffff5db6f0c in freerdp_check_event_handles (context=context@entry=0x62d1e0)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/libfreerdp/core/freerdp.c:242
> #23 0x00007ffff7b50e18 in xf_client_thread (param=0x62cf00)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/client/X11/xf_client.c:1453
> #24 0x00007ffff7629b10 in thread_launcher (arg=0x66f260)
> at /tmp/buildd/freerdp-nightly-1.2.1+0~20150408014830.88~1.gbp35892c/winpr/libwinpr/thread/thread.c:297
> #25 0x00007ffff56076aa in start_thread (arg=0x7fffe9a3d700) at pthread_create.c:333
> #26 0x00007ffff7303eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
>

**Comment by sonicflare** [comment]
Same issue on Ubuntu 14.10 with this build
http://pub.freerdp.com/repositories/deb/utopic/pool/main/f/freerdp-nightly/freerdp-nightly_1.2.1%2b0~20150414014834.90~1.gbp1487de_amd64.deb

```
~"#0  0x00007fc02c6f0e37 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56\n"
>~"#1  0x00007fc02c6f2528 in __GI_abort () at abort.c:89\n"
>~"#2  0x00007fc02c731f74 in __libc_message (do_abort=do_abort@entry=1, fmt=fmt@entry=0x7fc02c83af00 \"*** Error in `%s': %s: 0x%s ***\\n\") at ../sysdeps/posix/libc_fatal.c:175\n"
>~"#3  0x00007fc02c739586 in malloc_printerr (ptr=<optimized out>, str=0x7fc02c83b0c8 \"double free or corruption (fasttop)\", action=1) at malloc.c:4996\n"
>~"#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840\n"
>~"#5  0x00007fc02b29fbf2 in rail_read_unicode_string (s=0x7fc0180815f0, unicode_string=unicode_string@entry=0x1687b50) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/window.c:49\n"
>~"#6  0x00007fc02b2a06b1 in update_read_window_state_order (s=0x7fc0180815f0, orderInfo=orderInfo@entry=0x1687b30, windowState=windowState@entry=0x1687b40) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/window.c:213\n"
>~"#7  0x00007fc02b2a08a2 in update_recv_window_info_order (update=0x1680180, s=<optimized out>, orderInfo=0x1687b30) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/window.c:385\n"
>~"#8  0x00007fc02b2a12a4 in update_recv_altsec_window_order (update=update@entry=0x1680180, s=<optimized out>) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/window.c:574\n"
>~"#9  0x00007fc02b2738f8 in update_recv_altsec_order (update=0x1680180, s=<optimized out>, flags=<optimized out>) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/orders.c:3530\n"
>~"#10 0x00007fc02b27407d in update_recv_order (update=update@entry=0x1680180, s=s@entry=0x7fc0180815f0) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/orders.c:3552\n"
>~"#11 0x00007fc02b293c2e in fastpath_recv_orders (fastpath=0x1, s=0x7fc0180815f0) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/fastpath.c:205\n"
>~"#12 fastpath_recv_update (fastpath=fastpath@entry=0x16883f0, updateCode=<optimized out>, size=size@entry=88, s=s@entry=0x7fc0180815f0) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/fastpath.c:265\n"
>~"#13 0x00007fc02b2942f8 in fastpath_recv_update_data (fastpath=fastpath@entry=0x16883f0, s=s@entry=0x167b5a0) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/fastpath.c:410\n"
>~"#14 0x00007fc02b294a63 in fastpath_recv_updates (fastpath=0x16883f0, s=s@entry=0x167b5a0) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/fastpath.c:528\n"
>~"#15 0x00007fc02b290f85 in rdp_recv_fastpath_pdu (s=0x167b5a0, rdp=0x166d750) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/rdp.c:1198\n"
>~"#16 rdp_recv_pdu (rdp=rdp@entry=0x166d750, s=s@entry=0x167b5a0) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/rdp.c:1206\n"
>~"#17 0x00007fc02b29121b in rdp_recv_callback (transport=<optimized out>, s=0x167b5a0, extra=0x166d750) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/rdp.c:1307\n"
>~"#18 0x00007fc02b297545 in transport_check_fds (transport=transport@entry=0x167b240) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/transport.c:756\n"
>~"#19 0x00007fc02b2915c8 in rdp_check_fds (rdp=0x166d750) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/rdp.c:1359\n"
>~"#20 0x00007fc02b274118 in freerdp_check_fds (instance=0x1667c70) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/freerdp.c:208\n"
>~"#21 0x00007fc02b2741dc in freerdp_check_event_handles (context=context@entry=0x1667f50) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/libfreerdp/core/freerdp.c:242\n"
>~"#22 0x00007fc02d007e18 in xf_client_thread (param=0x1667c70) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/client/X11/xf_client.c:1453\n"
>~"#23 0x00007fc02cae0b10 in thread_launcher (arg=0x16ae8f0) at /tmp/buildd/freerdp-nightly-1.2.1+0~20150414014834.90~1.gbp1487de/winpr/libwinpr/thread/thread.c:297\n"
>~"#24 0x00007fc02aac70a5 in start_thread (arg=0x7fc01f31f700) at pthread_create.c:309\n"
>~"#25 0x00007fc02c7b3cfd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111\n"
>103^done
```

**Comment by Rainmaker52** [comment]
When doing 
export MALLOC_CHECK_=0
before running xfreerdp, the program does not dump core (obviously).

However, instead of dumping core, the connection is reset, and one needs to reconnect.

**Comment by hardening** [comment]
@Rainmaker52 @sonicflare any chance that one of you could run the same under valgrind instead of gdb ?

**Comment by Rainmaker52** [comment]
Ran valgrind --track-origins=yes --log-file=valgrind.log -- /opt/freerdp-nightly/bin/xfreerdp /u:MyUser /p:MyPass /v:192.168.56.201 /app:"||word".
FreeRDP version is freerdp-nightly_1.2.1+0~20150507014834.104~1.gbp063c1b_amd64

Last log:
==16152== Conditional jump or move depends on uninitialised value(s)
==16152==    at 0x4C308CE: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16152==    by 0x6C41B54: update_read_pointer_color (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C41C38: update_read_pointer_new (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3B1CA: fastpath_recv_update (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3B917: fastpath_recv_update_data (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3C082: fastpath_recv_updates (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C38564: rdp_recv_pdu (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C387FA: rdp_recv_callback (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3ED94: transport_check_fds (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C38BA7: rdp_check_fds (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C1B367: freerdp_check_fds (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C1B43B: freerdp_check_event_handles (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==  Uninitialised value was created by a stack allocation
==16152==    at 0xA53CC37: ??? (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==16152== 
==16152== Invalid free() / delete / delete[] / realloc()
==16152==    at 0x4C2CE10: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16152==    by 0x6C47FC1: rail_read_unicode_string (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C48AA0: update_read_window_state_order (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C48C91: update_recv_window_info_order (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C1AB47: update_recv_altsec_order (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3B24D: fastpath_recv_update (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3B917: fastpath_recv_update_data (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3C082: fastpath_recv_updates (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C38564: rdp_recv_pdu (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C387FA: rdp_recv_callback (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3ED94: transport_check_fds (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C38BA7: rdp_check_fds (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==  Address 0x13f788a0 is 0 bytes inside a block of size 8 free'd
==16152==    at 0x4C2CE10: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16152==    by 0x4C2DEF9: realloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==16152==    by 0x6C47F71: rail_read_unicode_string (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C48AA0: update_read_window_state_order (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C48C91: update_recv_window_info_order (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C1AB47: update_recv_altsec_order (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3B24D: fastpath_recv_update (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3B917: fastpath_recv_update_data (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3C082: fastpath_recv_updates (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C38564: rdp_recv_pdu (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C387FA: rdp_recv_callback (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152==    by 0x6C3ED94: transport_check_fds (in /opt/freerdp-nightly/lib/libfreerdp.so.1.2.3)
==16152== 
==16152== 
==16152== HEAP SUMMARY:
==16152==     in use at exit: 195,956 bytes in 3,820 blocks
==16152==   total heap usage: 13,347 allocs, 9,528 frees, 15,256,204 bytes allocated
==16152== 
==16152== LEAK SUMMARY:
==16152==    definitely lost: 3,136 bytes in 54 blocks
==16152==    indirectly lost: 24,709 bytes in 52 blocks
==16152==      possibly lost: 4,676 bytes in 83 blocks
==16152==    still reachable: 163,435 bytes in 3,631 blocks
==16152==         suppressed: 0 bytes in 0 blocks
==16152== Rerun with --leak-check=full to see details of leaked memory
==16152== 
==16152== For counts of detected and suppressed errors, rerun with: -v
==16152== ERROR SUMMARY: 6394031 errors from 944 contexts (suppressed: 338 from 3)

Full output (1.3 MB) is at https://drive.google.com/file/d/0B3cy7T35WlrNMzR6TGxESzJXY2M/view?usp=sharing

**Comment by hardening** [comment]
This PR https://github.com/FreeRDP/FreeRDP/pull/2603 should fix your bug.

**Comment by XSlicer** [comment]
To weigh in on this problem, as I had exactly the same, this fix worked for me. Thanks!

**Comment by hardening** [comment]
@Rainmaker52 if it fixes it for you I will close the issue (note: the PR has been merged upstream)

**Comment by Rainmaker52** [comment]
I already cherry-picked the patch and compiled it :)

Yes, that patch fixes it. Thanks!
