### ISSUE TITLE
Dotted Text Selection Mouse Cursor new one bug

### ISSUE THREAD

**Issue by DejavuDmitry** [FreeRDP/FreeRDP#2529]
I found an interesting bug with mouse cursor: 
```bash
dejavu@oit-d-iliukhin:~/build$ xfreerdp --version
This is FreeRDP version 1.2.1-dev (git b33bba0)

xfreerdp +clipboard /cert-ignore /size:${X_RES}x${Y_RES} /drive:FLASH,/media/"$USER" /drive:HOME,"$HOME" /u:"$REMOTE_USER" /p:"$REMOTE_PASS" /v:"$REMOTE_HOST" /printer:
```
![2015-04-09-175625_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9697445/7069860/dcf95512-dee3-11e4-9689-98c3bf5ea217.png)

![2015-04-09-175605_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9697445/7069865/e46e3448-dee3-11e4-9a8c-10cc5403b61c.png)

![2015-04-09-175529_1920x1080_scrot](https://cloud.githubusercontent.com/assets/9697445/7069870/e8549cfa-dee3-11e4-8f92-ac645f73c439.png)

**Comment by bmiklautz** [comment]
@cgholam I start wondering what you are doing? - A lot of issues do have an empty reply of yours. Pleas stop that.

**Comment by DejavuDmitry** [comment]
Any suggestions?

**Comment by bmiklautz** [comment]
@DejavuDmitry I haven't observed this behavior yet. What version of windows and word are you using?

**Comment by DejavuDmitry** [comment]
Okay, everything looks good with latest build. Thks.

**Comment by bmiklautz** [comment]
@DejavuDmitry if master works can we close the issue?

**Comment by DejavuDmitry** [comment]
@bmiklautz Yes.
