### ISSUE TITLE
Press "/" (numeric keypad) and appear ";"

### ISSUE THREAD

**Issue by mateusmzw** [FreeRDP/FreeRDP#2533]
I found a bug, when you press "/" (numeric keypad) and appear ";". Tested in more than one version of Windows. Language: PT-BR.

**Comment by bmiklautz** [comment]
@mateusmzw can you provide more details? - It would be interesting what version of FreeRDP you are using

**Comment by mateusmzw** [comment]
Version 1.0.1 - Ubuntu 12.04
Version 1.0.2 - Ubuntu 14.04

Tested in more than one version of freerdp and windows, but the problem continues.

**Comment by sinva** [comment]
Hello,

I have same problem. when you press "/" (numeric keypad) and appear "-".
This problems is in all version of windows, (windows 7, windows xp, windows 8.1 and windows 2012)

Ubuntu 12.04.5 / Freerdp 1.0.1
Centos 6.5 / Freerdp version unknown
Centos 7 / Freerdp version unknown

**Comment by mateusmzw** [comment]
@sinva
Only different key! xD
I thought only I suffered this bad!

@bmiklautz 
It seems that the bug appear in more than one type of keyboard.

**Comment by bmiklautz** [comment]
@mateusmzw this issue is already fixed for versions > 1.0.2 but those are not available on ubuntu.
But you can try a nightly build and see if it fixes your problem (https://github.com/freerdp/freerdp/wiki/PreBuilds).

For references on this issue see #811

**Comment by mateusmzw** [comment]
@bmiklautz 
Excuse my ignorance, but how do I install this PreBuilds?
Thanks!

**Comment by bmiklautz** [comment]
@mateusmzw depends on your distribution. If you visit the link from above, click the link for your distribution you get more information on how to install..

**Comment by mateusmzw** [comment]
@bmiklautz 
Ubuntu 12.04

I was able to install this package as links:
-Page: https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=precise,label=pkg-deb/
-deb: https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=precise,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_1.2.1+0~20150429014832.99~1.gbpbfccc0_amd64.deb

So that the installation is in / opt / freerdp-nightly / ...
And the old version of freerdp is already installed.

I have another doubt too, as I install this new version to work with LTSP?

**Comment by bmiklautz** [comment]
@mateusmzw the nightly builds are supposed to be in /opt/freerdp-nightly in order to not conflict with the distribution package. If you want to keep  the nightly you could for example remove the distributions package and create a link from /opt/freerdp-nigtly/bin/xfreerdp to your systems binary path.

**Comment by mateusmzw** [comment]
@bmiklautz
Incredible! Very good tip!
I always forget the links! xD

bmiklautz, you know how to integrate this new version of freerdp the LTSP? LTSP uses a own version of freerdp and not installed on the system.

Thank you very much!

**Comment by bmiklautz** [comment]
@mateusmzw sorry can't help with LTSP but maybe you ask anyone from them for help.

**Comment by mateusmzw** [comment]
@bmiklautz 
Thank you very much!
Continue with the great job!
freerdp is an optimal tool!
[]'s
