### ISSUE TITLE
keyboard events for capital letters

### ISSUE THREAD

**Issue by ferasd** [FreeRDP/FreeRDP#2534]
hey, 
what is the right way to send capital letters using  SendInputKeyboardEvent ?? is there any build in mechanism for doing that ??  
each rdp scan code is 8 bit while the input code of the function is uint32_t .
is there any prefix that should be added to the higher bits in order to identify capital letters , or i have to send manually shift key before sending the rdp scan code .

thanks

**Comment by hardening** [comment]
@ferasd This kind of question is more for IRC or the FreeRDP mailing list.
