### ISSUE TITLE
RemoteApp - Menus are black

### ISSUE THREAD

**Issue by sonicflare** [FreeRDP/FreeRDP#2540]
![remoteapp](https://cloud.githubusercontent.com/assets/7475460/7144007/4f4509f8-e2eb-11e4-994a-b133179a3840.png)

`xfreerdp /u:Administrator /p:password /app:"||notepad" /v:192.168.122.172`

### Version
`This is FreeRDP version 1.2.1-dev (git n/a)`

### System
`Linux 3.16.0-34-generic #45-Ubuntu SMP Mon Mar 23 17:21:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`
Ubuntu 14.10 on Unity
### Remote
Windows Server 2012 R2 (x64)

**Comment by hardening** [comment]
The git version would help. Do you still have the issue with updated git master ?

**Comment by sonicflare** [comment]
was having problem with menus crashing aswell. 
With compile from git version and your latest patch, everything works!
