### ISSUE TITLE
Freeze with cell selection in LibreOffice Calc if RFX enable or in fullscreen mode

### ISSUE THREAD

**Issue by e-gaulue** [FreeRDP/FreeRDP#2549]
When connecting to the server with rfx enable. Rfx is well enable (seen in the event logger) and video on youtube are good. But, as soon as I try to select cells under the bottom (or right) edge in LibreOffice Calc, the system goes in a never ending loop trying to get all the cells under (or on the right). This freeze the client machine X session as much as the only solution is to change of tty in order to kill the xfreerdp process.

Without Rfx, I don't observe this trouble in LibreOffice any more but videos on Internet are falling once out of two (mostly because of the sound).

When connecting to the server in fullscreen mode I observe the same trouble than when I activate rfx. So I think it's not link to rfx.

Can anybody check and reproduce this? If confirmed, any workaround to get them both (rfx + LibreOffice)?
- Client: Rpi with yesterday freerdp from github 1.2.1-dev (423b151)
- Server: windows 2008 R2 SP1 with RFX enable
- Software: LibreOffice stable 4.3.6.2

**Comment by hardening** [comment]
@e-gaulue is it possible that the updates that results from the LibreOffice screen update would kill the Rpi with too much pictures to render ? Perhaps you could activate some debug options (graphical oriented ones) to see what's going on during the freeze...

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
Btw, the RPi (even RPi3) is too slow for real time operation with 1920x1080 as FreeRDP currently only supports software rendering.
