### ISSUE TITLE
was built for x86_64 which is not the architecture being linked (i386)

### ISSUE THREAD

**Issue by southmeadows** [FreeRDP/FreeRDP#2550]
Not sure where to go next on this. Below is the start of the Link process. Ending up in a failure at the end. 
Not sure what to change?

Linking C executable ../xfreerdp
ld: warning: ld: warning: ld: warning: ignoring file /opt/local/lib/libXinerama.dylib, file was built for x86_64 which is not the architecture being linked (i386): /opt/local/lib/libXinerama.dylibld: warning: ignoring file /opt/local/lib/libXcursor.dylib, file was built for x86_64 which is not the architecture being linked (i386): /opt/local/lib/libXcursor.dylibignoring file /opt/local/lib/libXv.dylib, file was built for x86_64 which is not the architecture being linked (i386): /opt/local/lib/libXv.dylib
ignoring file /opt/local/lib/libXext.dylib, file was built for x86_64 which is not the architecture being linked (i386): /opt/local/lib/libXext.dylib
...
...
...
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [client/X11/xfreerdp] Error 1
make[1]: *** [client/X11/cli/CMakeFiles/xfreerdp-cli.dir/all] Error 2
make: *** [all] Error 2

**Comment by bmiklautz** [comment]
@southmeadows this is OS X Yosemite?

**Comment by southmeadows** [comment]
Yes Yosemite.  I was trying everything to make this work before I posted here so who knows what I might have messed up

**Comment by bmiklautz** [comment]
@southmeadows I wonder why you are building for i386? - What hardware are you on?

**Comment by southmeadows** [comment]
Macbook pro. I was wondering the same thing. Arent those libraries part the the X11?  I didnt compile xquartz.... I downloaded a preset pkg that installed itself

**Comment by bmiklautz** [comment]
Yes those are usually part of Xquartz. But if I interpret your error message right you are building for i386 and the linker complains that the libraries you are linking against are x86_64. So for me it seems there is either something wrong with your build or with your setup ;(.

**Comment by bmiklautz** [comment]
@southmeadows just a side note I build several times a week on Yosemite without any problems.

**Comment by bmiklautz** [comment]
@southmeadows can you add the build procedure you were using?

**Comment by southmeadows** [comment]
I copied the exact sequence you gave me in the other issue

**Comment by southmeadows** [comment]
cmake -DWITH_X11=ON
maybe elimimate the X11?

**Comment by bmiklautz** [comment]
@southmeadows that's really odd. What does uname -a say on your machine?
You can build without X11 if you plan to use the native mac client (which unfortunately isn't so advanced as the X11 client).

**Comment by southmeadows** [comment]
what other parmameters should I have with cmake? by itself it doesnt work

**Comment by southmeadows** [comment]
14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64

**Comment by southmeadows** [comment]
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .
I just redid cmake and then did make and that didnt help...

**Comment by southmeadows** [comment]
seems to me some of the libraries that are X are compile somehow for 386. I probably did that with the many things I did to try and make this work.  The question now is how do I reinstall the proper versions for X libraries

**Comment by southmeadows** [comment]
Or maybe I am confused even more... which of these are wrong? Maybe I am backwards. the X is correct and is x64 but whatever we are compiling (FreeRDP) is being compiled for 386.  So why would that be?

ld: warning: ignoring file /opt/local/lib/libXext.dylib, file was built for x86_64 which is not the architecture being linked (i386): /opt/local/lib/libXext.dylib

**Comment by southmeadows** [comment]
Getting further, just wild guessing. I ran this cmake and then make. still error. Is there a way I can just get the binary?

cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" . 

make error at the end:

Linking C executable ../xfreerdp
Undefined symbols for architecture x86_64:
  "_ERR_remove_thread_state", referenced from:
      _winpr_CleanupSSL in libwinpr.a(ssl.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [client/X11/xfreerdp] Error 1
make[1]: *** [client/X11/cli/CMakeFiles/xfreerdp-cli.dir/all] Error 2
make: *** [all] Error 2

**Comment by southmeadows** [comment]
this works. you need the path I guess:
brew install homebrew/x11/freerdp

this says its already linked: Note you do not need the sudo as mentioned on the install page
brew link freerdp

However, all done... now how to I run it? LOL

**Comment by bmiklautz** [comment]
@southmeadows simple form xfreerdp /v:yourrdphost. First run will launch XQuarz and might take a little.

**Comment by jmdevince** [comment]
This is still a problem when compiling from source on El Capitan. 

Building using:
make -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" -DOPENSSL_INCLUDE_DIR=/usr/local/Cellar/openssl/1.0.2e/include/ -DOPENSSL_LIBRARIES=/usr/local/Cellar/openssl/1.0.2e/lib/ . && make

Specified SSL since cmake was unable to find / utilize the system's built in SSL.

Undefined symbols for architecture x86_64:
  "_ERR_remove_thread_state", referenced from:
      _winpr_CleanupSSL in libwinpr.a(ssl.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [client/Mac/MacFreeRDP.framework/Versions/1.1.0/MacFreeRDP] Error 1
make[1]: *** [client/Mac/CMakeFiles/MacFreeRDP-library.dir/all] Error 2
make: *** [all] Error 2

**Comment by bmiklautz** [comment]
@jmdevince your issue is unrelated to this issue. Please look more carefully when commenting and reporting bugs. I've created a new issue (#3027) with your problem.
