### ISSUE TITLE
Error: No available formula for freerdp 

### ISSUE THREAD

**Issue by southmeadows** [FreeRDP/FreeRDP#2551]
brew install freerdp 
Error: No available formula for freerdp 

does not work.

**Comment by bmiklautz** [comment]
@southmeadows works for me (tm). But this is not really a FreeRDP issue we can do something about. If you having problems with brew please report this in the homebrew issue tracker. Thank you.

**Comment by bmiklautz** [comment]
@southmeadows just to make sure you have activated the homebrew/x11 tap?
