### ISSUE TITLE
Foreground window leaves trace on background window

### ISSUE THREAD

**Issue by danatela** [FreeRDP/FreeRDP#2561]
I have made a [small video](http://www.youtube.com/watch?v=26kHBTo2Ogg) that demonstrates what's wrong.

As you can see, I had success in getting my RemoteApp window to work on Ubuntu Linux desktop. You can find instructions here: https://bmullan.wordpress.com/2012/09/17/howto-integrate-windows-apps-into-the-ubuntu-linux-desktop-using-windows-remoteapp/

As far, I have noticed several expectable glitches. The most annoying is that foreground window leaves it's trace on background window when you start moving it. Also, when you maximize window, it doesn't behave like maximized. You can resize it and move. Also, there are some glitches that I didn't show. For example, when you resize window, it doesn't redraw it's content immediately, only after you release left mouse button. I also noticed those glitches in original Alex Stanev's video, but he doesn't demonstrate them.

The command used in background is (kinda of)

```
xfreerdp -u UserID -p WinPasswd --app --plugin rail --data “||MultiPlug2.exe” -- server.local
```

**Comment by hardening** [comment]
@danatela can you give us some version details (xfreerdp, windows version) ? Thank you.

**Comment by danatela** [comment]
At the time I did the report, `xfreerdp` version was 1.02, Windows was 2008 Server Standard Edition. Now I have `xfreerdp` 1.1.0~git20140921.1.440916e+dfsg1-2ubuntu1, and I cannot even start the program. It fails with "RAIL exec error: execResult=RAIL_EXEC_E_NOT_IN_ALLOWLIST NtError=0x15".  The front-end application (winconn) also doesn't work though for another reason (incompatibility issues). Sorry, I cannot give you more feedback details, and I also can't reproduce the error anymore.

**Comment by hardening** [comment]
About the error you're seeing https://github.com/FreeRDP/FreeRDP/issues/595 contains tips to solve it.
