### ISSUE TITLE
freerdp-shadow on Solaris and cursor keys issue

### ISSUE THREAD

**Issue by psumbera** [FreeRDP/FreeRDP#2563]
freerdp-shadow on Solaris (latest dev). When connection to it from another Solaris or Ubuntu Linux (both also dev builds) cursor keys doesn't work...

When I tried older rdesktop binary bundled with Solaris then cursor keys are working (but only part of screen is shown). 

Please help how to debug or where shall I look in source code...

**Comment by bmiklautz** [comment]
@xsumbe00 we don't do any build/function testing on Solaris. For cursor handling it seems that the xfixes extension is required. Have a look at server/shadow/X11/x11_shadow.c around line 402.

**Comment by xsumbe00** [comment]
I meant cursor keys (plus del, home, end, ..). Not mouse pointer.... Any pointer for that?

**Comment by bmiklautz** [comment]
@xsumbe00 ahh sorry. I just read cursor ;). That's possibly just a missing/wrong key mapping. You can might want to start looking at server/shadow/X11/x11_shadow.c line 222 function x11_shadow_input_keyboard_event.

**Comment by xsumbe00** [comment]
Thank you! I have working cursor UP key with following:
if (keycode == 111) keycode= 80;
In x11_shadow_input_keyboard_event(). Not sure why it's different than in Linux... And where to put the mapping...
