### ISSUE TITLE
Graphical Artifacts

### ISSUE THREAD

**Issue by BenGant** [FreeRDP/FreeRDP#2565]
I've try to use xfreerdp client. Everything is fine, but youtube has graphical artifacts. I've tried to disable bitmap-cache, change bpp, and result was the same. Artifacts  disappears only when I use bpp 8. The original Windows Remote Desktop has the same artifacts. How can I fix this issue? 
![print](https://cloud.githubusercontent.com/assets/10243371/7270214/1ad09a68-e8e3-11e4-94ab-919990037703.png)

**Comment by bmiklautz** [comment]
@BenGant what server are you connecting to and what command line parameters did you use with xfreerdp?

Usually when mstsc has the same artifacts it's not an FreeRDP issue.

**Comment by BenGant** [comment]
I used:  ./client/X11/xfreerdp /u:login /p:password /sec:rdp /v:remote /w:1024 /h:768 /port:3389 +clipboard -bitmap-cache -offscreen-cache -glyph-cache -decorations.
Server is Windows Server 2008 R2.

**Comment by hardening** [comment]
If the artifact is also visible with mstsc, it's definitely something related to your server installation. Closing the bug.
