### ISSUE TITLE
Dropdown not working

### ISSUE THREAD

**Issue by edgar-silva** [FreeRDP/FreeRDP#2567]
![snapshot1](https://cloud.githubusercontent.com/assets/7161594/7280519/313da3b2-e91b-11e4-8063-7a89f0446a83.png)

The drop down appears and disappears after pressed like in this video
https://www.youtube.com/watch?v=pqmVvfAheqk

Need help please,
Thnks!

**Comment by bmiklautz** [comment]
@edgar-silva can you give more information please? For example like FreeRDP version, Windows version you are connecting to - see https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by edgar-silva** [comment]
Hello here i'm again 
On ubuntu and this is FreeRDP version 1.0.2
Server 2012, i tried many things but always end up on non working dropdown
Thnks for help!

**Comment by hardening** [comment]
@edgar-silva could you give a try with the master version, if you wish there's prebuilt version here => https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by akallabeth** [comment]
No feedback, closing.
