### ISSUE TITLE
C#, manual method call.

### ISSUE THREAD

**Issue by z668** [FreeRDP/FreeRDP#2574]
Hello. 

I am using FreeRDP Sharp (https://github.com/FreeRDP/FreeRDP-Sharp) and latest version FreeRDP x32, but there is an error when calling Connect() method (https://github.com/FreeRDP/FreeRDP-Sharp/blob/master/FreeRDP/Core/RDP.cs). 

Marshal.GetLastWin32Error() return error code 2. Sniffer nothing shows, packets to the server are not sent.

Tell me the sequence of method calls before calling Connect() and would love to hear your ideas why the error in the method Connect().

Thank you.

**Comment by bmiklautz** [comment]
@z668 I'm not sure how up2date the c# bindings are but I would think they weren't updated to latest master yet.

**Comment by z668** [comment]
@bmiklautz, yes you are right. FreeRDP Sharp not updated 3 year. But I have no choice, no alternative but ActiveX from MS. I would be grateful for any hints FreeRDP initialization. Both libraries same author (https://github.com/awakecoding). Do not think it will be difficult to determine the cause or give a direction in which to dig.

**Comment by hardening** [comment]
@z668 this issue should be reported to the FreeRDP-Sharp project, and as you've probably read, nobody's working on it at the moment. Try to go on IRC if you want directions to inquiry on your bug.
