### ISSUE TITLE
Question on Keyboard Shortcuts (Hotkeys) interaction

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#2585]
My current environment is Ubuntu Gnome (15.04) with Gnome 3.16, this question still resides for Ubuntu Gnome (14.10) with Gnome 3.14. 

I work everyday out of a Windows 8.1 cloud based VM that I RDP into using FreeRDP. What I struggle with sometimes is ALT+TAB interactions with Windows vs Ubuntu. There are times when I am in Windows RDP session with keyboard and mouse focus in the FreeRDP window. However, I want to grab attention to an Ubuntu window with my keyboard. 

Currently the only way I can pull up the ALT+TAB list of windows in Ubuntu is to move the mouse cursor outside the bounds of the RDP window that FreeRDP creates. Is there a hidden shortcut for that? I tried looking in client/Windows/wf_event.c to see if I could figure it out but no dice. This is more of a feature request/question rather than an issue.

**Comment by binki** [comment]
+1

**Comment by bmiklautz** [comment]
@meanbunny just to get it right you are using xfreerdp on Ubuntu to connect to a windows 8.1?
Disabling keyboard grabbing with "-grab-keyboard" doesn't help you?

**Comment by binki** [comment]
I think the OP likes the keyboard grabbing (because his window manager responds to ALT+TAB and without grabbing it would be impossible/hard to send ALT+TAB to the RDP server) but wants to be able to ungrab without using the mouse. For example, VirtualBox’s viewer allows pressing the “host key” once to ungrab the keyboard. Does xfreerdp have a shortcut to accomplish this?

**Comment by bmiklautz** [comment]
@binki what's the OP? FreeRDP does have some functionality to run a command/script on keypress (it's called action script) but currently there is no configurable way to ignore or pass key sequences otherwise.

**Comment by binki** [comment]
[OP expands to “Original Poster”](http://www.catb.org/jargon/html/O/thread-OP.html).

How do I get xfreerdp to grab/ungrab the window while it’s running with the keyboard? I know that, for example, ctrl+alt+enter switches to/from fullscreen, and that is even findable in the source code. How do these action scripts work and where are they defined?

**Comment by Rudedog9d** [comment]
@meanbunny @binki Check out [FreeRDP/FreeRDP-old#49](https://github.com/FreeRDP/FreeRDP-old/issues/49)

**Comment by jpeg729** [comment]
A fix has been merged in #3622 so this issue can be closed.

Press Right-Ctrl to ungrab temporarily. Any interaction causes the keyboard to be grabbed again, so you have to do Alt-Tab (if that is what you want) right after pressing Right-Ctrl.

**Comment by Flexximilian** [comment]
> is it possible to change Right-Ctrl grab hotkey? It conflicts when using Jupyter Ctrl-Enter shortcut.

You could just patch the source and recompile...
