### ISSUE TITLE
Which cipher suites are supported by FreeRDP?

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#2591]
When locking down one of my Win2k12 R2 Core server's ciphers, I get to the point where I'm unable to connect with FreeRDP, while mstsc still works.

Here's a screenshot of that configuration:
![capturfiles_2](https://cloud.githubusercontent.com/assets/186198/7469407/80dbcece-f313-11e4-94e9-590e5dd69dd6.png)

Now if I add the following 3 ciphers back to the list I'm able to connect again:
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P521
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P384
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA_P256

Question: Which cipher suites are supported by FreeRDP currently and are there any settings that allow control over this?

**Comment by bmiklautz** [comment]
@lemonmojo If I'm not mistaken there are no limitations per default and all available ciphers of the underlying openssl versions are used. Have a look at the tls-ciphers command line parameter. It allows you to set the list of accepted ciphers.

**Comment by bmiklautz** [comment]
@lemonmojo whats the tool on the screenshot you are using for enabling/disabling ciphers?

**Comment by lemonmojo** [comment]
@bmiklautz thx for the info! The tool is [IIS Crypto](https://www.nartac.com/Products/IISCrypto/).

**Comment by bmiklautz** [comment]
@lemonmojo related to this there have already been discussion on limiting the cipher strings used to improve security - see #2365.

**Comment by bmiklautz** [comment]
@lemonmojo do you have enough information and can this issue be closed?

**Comment by lemonmojo** [comment]
@bmiklautz Yep, can be closed! thx!
