### ISSUE TITLE
Freerdp iOS issue 

### ISSUE THREAD

**Issue by shattars3d** [FreeRDP/FreeRDP#2593]
When compiling the freerdp master build for the iOS client of freerdp, I'm getting the issue of the freerdp settings not being loaded before connecting into the rdp. When running on an iOS device and selecting a server to connect to, xcode has a memory issue at the line     free(inst->settings->HomePath); in the iOS_freerdp.m file.

**Comment by lgqiang** [comment]
The newest code has bug. I have made some change to fix the bug:

**Comment by lgqiang** [comment]
2 files need to change:

freerdp.c line 501, change to below:

	if (!ret) 
		return TRUE;

gdi.c, line 1357, change to below:

if (!instance->context->cache) {
		if (!(cache = cache_new(instance->settings)))
			goto fail_cache;
        instance->context->cache = cache;
    }

after make those change, you can run the program with no crash.

**Comment by hardening** [comment]
@lgqiang if so can you submit a PR with these changes. Thanks.

**Comment by lgqiang** [comment]
@hardening sorry, I don't known how to submit a PR.

**Comment by shattars3d** [comment]
@lgqiang  thanks, always thought the master would be stable ;) but its not lol

**Comment by shattars3d** [comment]
@lgqiang  

when i try to connect to the test server "test service.freerdp.com", it gives me this in the Xcode debugger….

2015-05-14 12:00:33.452 iFreeRDP[2458:60b] Reachability Flag Status: -R ------- networkStatusForFlags
failed to connect to testservice.ifreerdp.com
[12:00:34:430] [2458:04739000] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[12:00:34:430] [2458:04739000] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
[12:00:34:430] [2458:04739000] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
2015-05-14 12:00:34.998 iFreeRDP[2458:6307] ios_run_freerdp: inst->rdp_connect failed

**Comment by YangLi20** [comment]
hello,when i user cmake build freerdp,i met a error ,the reason is " unknown cmake command "set_complex_link_libraries" " , why ?  thank you,my cmake version is 3.3.2

**Comment by shattars3d** [comment]
if your using the mac OS X el captian, the cmake will give you issues. theres a local folder the el captian has removed. i had an issue with that but i fixed it by coping the folder that  cmake writes in the yosemite local folder.. that could be an issue.   

also i am using came 2.8.12.1 for freerdp..  not using the latest cmake

**Comment by akallabeth** [comment]
working with `cmake-3.0` and later.
