### ISSUE TITLE
Connection errors are issued on stdout and not stderr

### ISSUE THREAD

**Issue by robled** [FreeRDP/FreeRDP#2595]
I develop a python [application](https://github.com/robled/rocket-depot) that uses subprocess.Popen to start xfreerdp via the CLI and then retrieve any error messages from stderr.  When a connection error occurs the error text is sent to stdout and not stderr, which strikes me as unusual.

**Comment by bmiklautz** [comment]
@robled this issue should be resolved with the pull request mentioned above. Can you verify that this problem is solved for you. If you have Debian, Ubuntu, Fedora or OpenSuse you can use our nightly builds for testing https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by bmiklautz** [comment]
Should be fixed on master and no feedback for a while.
