### ISSUE TITLE
Something wrong with my keyboard!

### ISSUE THREAD

**Issue by huangjunsong** [FreeRDP/FreeRDP#2606]
At first,the keyboar is same as usual.But after I pressed the toggleExtKeyboard button and the keyboard became first responder again.The keyboard became like the ![image](https://github.com/huangjunsong/MyGit/blob/master/ImageFolder/IMG_0572.jpg).Can someone tell me what happened.How to fix it?

**Comment by bmiklautz** [comment]
@huangjunsong is this iOS or Android? Did you compile yourself? If so can you add the version you are using?

**Comment by huangjunsong** [comment]
@bmiklautz It's iOS.And I compile it with the README.ios. I also compile freeRDP and openSSL for arm64.I am using XCode6.3.

**Comment by shattars3d** [comment]
@huangjunsong  are you having any issues connecting to a rdp session in the iOS freerdp? with the latest master off freerdp?

**Comment by huangjunsong** [comment]
@shattars3d no,My connecting is work well.

**Comment by shattars3d** [comment]
@hunangjunsong. Whicn freerdp master commit is your project on your Mac

**Comment by shattars3d** [comment]
@huangjunsong Whicn freerdp master commit is your project on your Mac?

**Comment by huangjunsong** [comment]
I don't know what you mean.If you want to know my FreeRDP master version.I don't remember that.How can I see the version.

**Comment by lanscene** [comment]
@bmiklautz @shattars3d I have the same problem, and it exists both in IFreeRDP Release at AppStore and self-building app which I fetch from the master branch in github. It seems there is a keyboard overlap   
in such situation.

**Comment by jun66j5** [comment]
Same here. The AdvancedKeyboardView doesn't work.

**Comment by shattars3d** [comment]
You might have to through the code and find out where it is giving the issue.  Try a different iOS  try iOS 6 or iOS 7. Could be iOS version issues.

**Comment by glitchphan** [comment]
It might be an iOS version issue because this doesn't happen on iPad 3 iOS 6.1.2, but it happens on iPad Air 2 iOS 8.4 and 9.0.2. Both running same version from the App Store. Also I can't type non-alphanumeric characters into Pidgin for some reason, but that's probably a separate issue. I wish bt keyboard fully worked and was enabled all the time :).

**Comment by VinodJagtap** [comment]
What is the progress now....Is it working fine?
