### ISSUE TITLE
Mac OS X native client : 100% CPU usage even when session is idle

### ISSUE THREAD

**Issue by nfedera** [FreeRDP/FreeRDP#2609]
Seen with current master (692df124c60ffbfdd51cd576bc3c7cf2735b712a) on OS X 10.9.5.
Does not seem to be related to a specific codec ( /rfx /gfx ...)

**Comment by shattars3d** [comment]
hey I'm having trouble compiling the mac OS X version for the rdp client.. can i get some help off u?. thanks..

**Comment by nfedera** [comment]
Ok the issue is related to +async-transport which is hardcoded in the mac native client.
It also happens with ```xfreerdp /v:host +async-transport```

**Comment by nfedera** [comment]
Created related/root issue #2610

**Comment by bmiklautz** [comment]
@shattars3d please only add comments related to the issues problem. Your build problems are not related to this in any way. Thank you!

**Comment by nfedera** [comment]
Should be fixed via #2611 and #2621
