### ISSUE TITLE
[iOS] Build failed when using xcodebuild with code sign error

### ISSUE THREAD

**Issue by mchozhang** [FreeRDP/FreeRDP#2614]
I read README.ios to build the project with
cmake 3.2.2
iPhoneOS SDK 8.2
Xcode 6.2

here are my steps:
1.download and build the openssl simply with
```
./scripts/OpenSSL-DownloadAndBuild.command
```
2.create Xcode project with
```
cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode
```

3.build the project with
```
xcodebuild -project FreeRDP.xcodeproj -configuration Debug -sdk iphoneos8.2
```
but then i got this
```
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.2'

** BUILD FAILED **
```
I tried to modify the Code Signing Identity to iOS developer ,but made no difference.
It is possible that I should use lower version cmake or sdk?

**Comment by lgqiang** [comment]
You can use the Xcode to compile the code. Before you compile, you should set the code signing

**Comment by mchozhang** [comment]
ok, i guess i solved this problem.
First of all, we should have a provisioning profile which is created in apple member center.
Before we use "xcodebuild" to build the project, modify the code signing identity and provisioning profile in build setting in xcode to the profile we create. If you don't have a provisioning profile ,it's useless to change it to anything else.
Then we can build the project with "xcodebuild" successfully.

**Comment by YangLi20** [comment]
When compiling the iOS code, I met a mistake does not support architecture，Have met or know?The following is the error log

-- Configuring incomplete, errors occurred!
See also "/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeOutput.log".
See also "/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeError.log".



yangli:FreeRDP-1.1.0-beta1-ios4 yangli$ cat /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeError.log
Determining if files fcntl.h exist failed with the following output:

Source:
/* */
#include <fcntl.h>


int main(){return 0;}

Determining if files unistd.h exist failed with the following output:

Source:
/* */
#include <unistd.h>


int main(){return 0;}

Determining if files stdint.h exist failed with the following output:

Source:
/* */
#include <stdint.h>


int main(){return 0;}

Determining if files inttypes.h exist failed with the following output:

Source:
/* */
#include <inttypes.h>


int main(){return 0;}

Determining if files sys/modem.h exist failed with the following output:

Source:
/* */
#include <sys/modem.h>


int main(){return 0;}

Determining if files sys/filio.h exist failed with the following output:

Source:
/* */
#include <sys/filio.h>


int main(){return 0;}

Determining if files sys/strtio.h exist failed with the following output:

Source:
/* */
#include <sys/strtio.h>


int main(){return 0;}

Performing C SOURCE FILE Test HAVE_TM_GMTOFF failed with the following output:

Source file was:

#include <time.h>

int main()
{
   struct tm* tmp;
   tmp->tm_gmtoff;
  return 0;
}

Determining if files pthread.h exist failed with the following output:

Source:
/* */
#include <pthread.h>


int main(){return 0;}

Performing C SOURCE FILE Test Wno-unused-but-set-variable failed with the following output:
Change Dir: /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp

Run Build Command:/usr/local/bin/cmakexbuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTryCompileExec1847124611 -configuration Debug
2015-11-19 20:15:13.385 xcodebuild[1188:39790] warning:  The file reference for "CMakeLists.txt" is a member of multiple groups ("ALL_BUILD" and "cmTryCompileExec1847124611"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
=== BUILD TARGET cmTryCompileExec1847124611 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
/bin/mkdir -p /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64
write-file /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/cmTryCompileExec1847124611.LinkFileList

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/src.o src.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug/include -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/DerivedSources/x86_64 -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug -Wall -Wno-unused-result -DWno-unused-but-set-variable -Wno-unused-but-set-variable -MMD -MT dependencies -MF /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/src.d --serialize-diagnostics /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/src.dia -c /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/src.c -o /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/src.o
warning: unknown warning option '-Wno-unused-but-set-variable'; did you mean '-Wno-unused-const-variable'? [-Wunknown-warning-option]
In file included from <built-in>:326:
<command line>:2:12: warning: ISO C99 requires whitespace after the macro name [-Wc99-extensions]
#define Wno-unused-but-set-variable 1
           ^
2 warnings generated.

Ld Debug/cmTryCompileExec1847124611 normal x86_64
    cd /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug -F/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug -filelist /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/cmTryCompileExec1847124611.LinkFileList -mmacosx-version-min=10.11 -Wl,-headerpad_max_install_names -Xlinker -dependency_info -Xlinker /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec1847124611.build/Objects-normal/x86_64/cmTryCompileExec1847124611_dependency_info.dat -o /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug/cmTryCompileExec1847124611

** BUILD SUCCEEDED **


Source file was:
int main(void) { return 0; }
Determining if files sys/eventfd.h exist failed with the following output:
Change Dir: /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp

Run Build Command:/usr/local/bin/cmakexbuild -project CMAKE_TRY_COMPILE.xcodeproj build -target cmTryCompileExec663028920 -configuration Debug
2015-11-19 20:15:14.662 xcodebuild[1230:39897] warning:  The file reference for "CMakeLists.txt" is a member of multiple groups ("ALL_BUILD" and "cmTryCompileExec663028920"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
=== BUILD TARGET cmTryCompileExec663028920 OF PROJECT CMAKE_TRY_COMPILE WITH CONFIGURATION Debug ===

Check dependencies

Write auxiliary files
/bin/mkdir -p /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64
write-file /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/cmTryCompileExec663028920.LinkFileList

CompileC CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.o CheckIncludeFiles.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch x86_64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0** BUILD FAILED **


The follow -Wno-trigraphs -fpascal-strings -O2 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Debug\" -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -fasm-blocks -fstrict-aliasing -Wdeprecated-declarations -mmacosx-version-min=10.11 -g -Wno-sign-conversion -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug/include -I/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/DerivedSources/x86_64 -I/Users/yangli/Documents/src/Freing build coeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/Debug -Wall -Wno-unused-result -Wno-deprecated-declarations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -DWINPR_EXPORTS -DFREERDP_EXPORTS -MMD -MT dependencies -MF /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.d --serialize-diagnostics /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.dia -c /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CheckIncludeFiles.c -o /Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMmmands failed:
akeTmp/CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.o
clang: warning: no such sysroot directory: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk'
/Users/yangli/Documents/src/FreeRDP-1.1.0-beta1-ios4/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: 'sys/eventfd.h' file not found
#include <sys/eventfd.h>
         ^
1 error generated.

	CompileC CMAKE_TRY_COMPILE.build/Debug/cmTryCompileExec663028920.build/Objects-normal/x86_64/CheckIncludeFiles.o CheckIncludeFiles.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

Source:
/* */
#include <sys/eventfd.h>


int main(){return 0;}

yangli:FreeRDP-1.1.0-beta1-ios4 yangli$

**Comment by bmiklautz** [comment]
@YangLi20 please stop adding the same comment on different issues. If you got a problem create a new issue *once*.

**Comment by YangLi20** [comment]
ok,thank you

**Comment by hardening** [comment]
closing as it was solved.

**Comment by YangLi20** [comment]
ok,
