### ISSUE TITLE
Mac OS X: CMakeList.txt prefixes MacPorts include directories

### ISSUE THREAD

**Issue by nfedera** [FreeRDP/FreeRDP#2617]
Since commit a35f1e81 /opt/local/include is the first element in the include path when compiling on Mac OS X. This causes severe issues.
One example is openssl: Although OPENSSL_INCLUDE_DIR is set to /usr/include the sources include the ssl headers from /opt/local and FreeRDP is linked against the system libraries. If linking is successful at all there might still be runtime errors.
And this issue also annihilates our tests against the OPENSSL_VERSION_NUMBER.
@awakecoding any reason to keep this and what was the reason in the first place ?

**Comment by watkipet** [comment]
I'm able to work around this by using the cmake prefix path option:
`cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" -DCMAKE_PREFIX_PATH=/opt/local .`
This still uses the MacPorts headers, but it also pulls the actual dylibs from MacPorts as well. I'm still not saying the /opt/local headers should stay at their present location, though.

**Comment by computerion** [comment]
Has there been a update to resolve this? I'm still experiencing the linking issue.
