### ISSUE TITLE
MacFreeRDP.framework link failure

### ISSUE THREAD

**Issue by bigelectricccat** [FreeRDP/FreeRDP#2619]
Bulding from master f219d34 using a MacPorts-supplied OpenSSL library and CMake fails when linking MacFreeRDP.framework This affects the OS X 10.10 target when building with Xcode 6.3.1.

Linking C shared library MacFreeRDP.framework/MacFreeRDP
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -dynamic -dylib -arch i386 -dylib_install_name @executable_path/../Frameworks/MacFreeRDP.framework/Versions/1.1.0/MacFreeRDP -macosx_version_min 10.10.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -o /var/folders/31/1447m3sn5h9b58wj4d7d7xycc44hhy/T/-4bdc28.out -L/opt/local/lib -headerpad_max_install_names CMakeFiles/MacFreeRDP-library.dir/__/common/client.c.o CMakeFiles/MacFreeRDP-library.dir/main.m.o CMakeFiles/MacFreeRDP-library.dir/mf_client.m.o CMakeFiles/MacFreeRDP-library.dir/MRDPCursor.m.o CMakeFiles/MacFreeRDP-library.dir/MRDPView.m.o CMakeFiles/MacFreeRDP-library.dir/Keyboard.m.o CMakeFiles/MacFreeRDP-library.dir/Clipboard.m.o CMakeFiles/MacFreeRDP-library.dir/PasswordDialog.m.o -framework Cocoa -framework Foundation -framework AppKit -framework IOKit ../common/libfreerdp-client.a ../../winpr/libwinpr/libwinpr.a ../../libfreerdp/libfreerdp.a ../../channels/audin/client/libaudin-client.a ../../channels/disp/client/libdisp-client.a ../../channels/echo/client/libecho-client.a ../../channels/rdpei/client/librdpei-client.a ../../channels/rdpgfx/client/librdpgfx-client.a ../../channels/tsmf/client/libtsmf-client.a ../../channels/cliprdr/client/libcliprdr-client.a ../../channels/drdynvc/client/libdrdynvc-client.a ../../channels/encomsp/client/libencomsp-client.a ../../channels/rail/client/librail-client.a ../../channels/rdpdr/client/librdpdr-client.a ../../channels/rdpsnd/client/librdpsnd-client.a ../../channels/remdesk/client/libremdesk-client.a ../../channels/drive/client/libdrive-client.a ../../channels/parallel/client/libparallel-client.a ../../channels/serial/client/libserial-client.a ../../channels/smartcard/client/libsmartcard-client.a ../../libfreerdp/libfreerdp.a ../../winpr/libwinpr/libwinpr.a -lm /usr/lib/libssl.dylib /usr/lib/libcrypto.dylib /usr/lib/libz.dylib -rpath "\$ORIGIN/../lib:\$ORIGIN/.." -rpath /opt/local/lib -arch_multiple -final_output MacFreeRDP.framework/Versions/1.1.0/MacFreeRDP -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0/lib/darwin/libclang_rt.eprintf.a /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/6.1.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture i386:
  "_ERR_remove_thread_state", referenced from:
      _winpr_CleanupSSL in libwinpr.a(ssl.c.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: **\* [client/Mac/MacFreeRDP.framework/Versions/1.1.0/MacFreeRDP] Error 1
make[1]: **\* [client/Mac/CMakeFiles/MacFreeRDP-library.dir/all] Error 2
make: **\* [all] Error 2

The stable-1.1 branch builds with the CMake flag -DWITH_CLANG:BOOL=ON, but throws a spurious error about the compiler path. The CMake script in master ignores WITH_CLANG to avoid another compilation issue.

**Comment by watkipet** [comment]
This is the same error I get when cmake picks up OpenSSL headers from MacPorts put picks the dylibs from /usr/llib. See [this issue](https://github.com/FreeRDP/FreeRDP/issues/2617).

**Comment by akallabeth** [comment]
Builds on mac are working with current master, closing.
