### ISSUE TITLE
Does FreeRDP support RDS broker config?

### ISSUE THREAD

**Issue by mvojjala** [FreeRDP/FreeRDP#2629]
In out set up we are using a RDS broker with two hosts. No Gateway is used. My problem is  hitting RDS broker is not redirecting us to the RDS host, connection is initiated for RDS broker itself.  

I am assuming that RDS broker is directly supported and no need of any flag/settings enabling. Any hints or clues on  where to start debugging or any pointers ?

**Comment by HenryJacques** [comment]
Hi,

Instead of using the parameter /v:broker (which I assume you're using), use a rdp file generated by your broker (that can generally be downloaded using a browser in http(s)://broker/rdweb)
Then use the command line $xfreerdp myrdpfile.rdp
without passing the /v argument

Bye
