### ISSUE TITLE
FreeRDP website link

### ISSUE THREAD

**Issue by antenore** [FreeRDP/FreeRDP#2641]
Can you please update the Remmina link on FreeRDP.com?

It should point to www.remmina.org or, at least to http://github.com/FreeRDP/Remmina.

This is quite important and urgent because people goes to Source Forge and we get continuously tickets for the wrong version. A version that cannot even work with your new FreeRDP API.

Thanks!

@giox069  FYI

**Comment by antenore** [comment]
@awakecoding 
Should I report this somewhere else? Thanks in advance!

**Comment by akallabeth** [comment]
Closing as fixed, reopen if still an issue.
