### ISSUE TITLE
tmp flaw in freeRDP

### ISSUE THREAD

**Issue by kurtseifried** [FreeRDP/FreeRDP#2655]
Filed a CVE request on oss-security

http://www.openwall.com/lists/oss-security/2015/05/26/17

./channels/drdynvc/tsmf/tsmf_media.c:			snprintf(buf, sizeof(buf), "/tmp/FreeRDP_Frame_%d.ppm", frame_id);
                /* Dump a .ppm image for every 30 frames. Assuming the frame is in YUV format, we
                   extract the Y values to create a grayscale image. */
                static int frame_id = 0;
                char buf[100];
                FILE * fp;
                if ((frame_id % 30) == 0)
                {
                        snprintf(buf, sizeof(buf), "/tmp/FreeRDP_Frame_%d.ppm", frame_id);
                        fp = fopen(buf, "wb");
                        fwrite("P5\n", 1, 3, fp);
                        snprintf(buf, sizeof(buf), "%d %d\n", sample->stream->width, sample->stream->height);
                        fwrite(buf, 1, strlen(buf), fp);
                        fwrite("255\n", 1, 4, fp);
                        fwrite(sample->data, 1, sample->stream->width * sample->stream->height, fp);
                        fflush(fp);
                        fclose(fp);
                }
                frame_id++;
#endif
        }
}

**Comment by hardening** [comment]
On master this is guarded by a #if 0...
So I guess this is for previous versions

**Comment by bmiklautz** [comment]
@kurtseifried what version or package are you referring to? - Both "tmp flaws" you have reported need either be activated on purpose (as in for debugging) or are not enabled at all (#if 0). Can you give more details were you see the actual problem?
I personally don't consider it a flaw if some debug code, that *isn't* enabled by default, is distributed in a release tarball.

**Comment by bmiklautz** [comment]
* The reported tsmf_media.c code exists in stable-1.0, stable-1.1 and master but is disabled by "#if 0"
* the tile related code (gdi.c) exists in stable-1.0 and stable-1.1 but is only enabled if DUMP_REMOTEFX_TILES is set explicitly.

**Comment by hardening** [comment]
Closing according to http://www.openwall.com/lists/oss-security/2015/05/27/8
