### ISSUE TITLE
can no longer connect to gateway 0x2000D is back :(

### ISSUE THREAD

**Issue by elangelo** [FreeRDP/FreeRDP#2656]
Running latest git:
$ xfreerdp --version
This is FreeRDP version 1.2.4-dev (git 58b1995)

$ xfreerdp /v:MACHINE /d:DOMAIN /u:USERNAME /p:PASSWORD /g:GATEWAY /gd:GATEWAYDOMAIN /cert-ignore /gu:GATEWAYUSERNAME /gp:GATEWAYPASSWORD /multimon:force /f /gfx +gfx-progressive
[08:42:41:081] [6315:6316] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
[08:42:42:931] [6315:6316] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[08:42:42:931] [6315:6316] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1

**Comment by LGLumi** [comment]
Same for me. Authentication in 1.2.4 through GW does not seem to work properly. Same (kinda long) command line that worked for 1.2.0 didn't work for 1.2.4, then I shorten it to something like you have and it didn't work aswell. This error seems to be that you wrong authentication, but I know pretty sure that in my case I have it right... no idea what is going on.

**Comment by LGLumi** [comment]
I've tried it on just installed machine and it worked (Debian Wheezy - same as the problematic PC) and I also tried it on Ubuntu 14.04 LTS and it worked aswell. I don't understand what does kill the connection for me. It might be another app or something on network? I used exactly the same way to build the package and it works somewhere else which is quite weird for me. I mean, I did just try copy that compiled dir from one Wheezy to another and it worked... strange.

**Comment by LGLumi** [comment]
@elangelo Try using -sec-nla /sec:rdp /gt:rpc where -sec-nla is quite nessesary when you connect to Windows 2012 servers, /sec:rdp (security type) and in last version /gt:rpc is nessesary for Windows 2012 GWs. So, try /gt:rpc for sure and if it won't work then add other two then.

**Comment by elangelo** [comment]
/gt:rpc did the trick. Thnx! 
Didn't have to add the -sec-nla or /sec:rdp

**Comment by LGLumi** [comment]
@elangelo You are welcome. :) Don't forget to close the issue. ;)
