### ISSUE TITLE
FreeRDP closes while running RemoteApp, but server session stays the same.

### ISSUE THREAD

**Issue by DarkWebster** [FreeRDP/FreeRDP#2657]
Hello. Bear with me as I don't understand all the technicalities of Linux, but i'll try to help as much as I can.

The bug that occurs is that FreeRDP closes for no apparent reason while running a RemoteApp. I've managed to replicate this running Word 2016 Preview (and it also happens on another software on our company). On Word it happens when on New File I try to create a new file from template. On the other software (which i'm not able to access at the moment, probably only next week) it does the same when the program tries to load a list from the database.

However if I reopen it works proper until I try to create a template. For the other app I'll also try to get crash info when I'm able to use it again.

Command line used: xfreerdp /v:REDACTED /d:REDACTED.pt.local /load-balance-info:tsv://VMResource.1.Col_WIndows_81 /u:pedro.flores /p:REDACTED /app:||explorer /app-name:Explorer /cert-ignore +fonts -themes -wallpaper /network:lan
(It's called from explorer, and on explorer I open Word. It also crashes if I directly open the app).

The server is running Windows Server 2012 R2 with RDS running on VDI mode. The hosts are also 2012 R2.

Version: This is FreeRDP version 1.2.4-dev (git 58b1995)

OS running FreeRDP: Xubuntu 15.04 amd64, kernel 3.19.0-16-generic, fully patched as of May 27.

CMake parameters: -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON

**Comment by DarkWebster** [comment]
Can't paste the whole valgrind log, so I paste what I think it's more useful to you.

==28386== 
==28386== Use of uninitialised value of size 8
==28386==    at 0x53EA6D0: HashTable_Remove (HashTable.c:322)
==28386==    by 0x4E4BE93: xf_rail_window_delete (xf_rail.c:524)
==28386==    by 0x6CDB171: update_recv_window_info_order (window.c:389)
==28386==    by 0x6CDC068: update_recv_altsec_window_order (window.c:584)
==28386==    by 0x6C95EB4: update_recv_altsec_order (orders.c:3530)
==28386==    by 0x6C95F5B: update_recv_order (orders.c:3552)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC589F: fastpath_recv_update_data (fastpath.c:410)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386==    by 0x6CC09C4: rdp_recv_pdu (rdp.c:1213)
==28386== 
==28386== Use of uninitialised value of size 8
==28386==    at 0x6D10DA0: ExtractRunLength (interleaved.c:151)
==28386==    by 0x6D125EC: RleDecompress16to16 (bitmap.c:408)
==28386==    by 0x6D14A17: interleaved_decompress (interleaved.c:321)
==28386==    by 0x4E56E55: xf_Bitmap_Decompress (xf_graphics.c:169)
==28386==    by 0x6C4C2E3: update_gdi_cache_bitmap_v2 (bitmap.c:140)
==28386==    by 0x6C94CF2: update_recv_secondary_order (orders.c:3377)
==28386==    by 0x6C95F7F: update_recv_order (orders.c:3554)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC61D8: fastpath_recv_update_data (fastpath.c:502)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386== 
==28386== Use of uninitialised value of size 8
==28386==    at 0x6D125FD: RleDecompress16to16 (bitmap.c:410)
==28386==    by 0x6D14A17: interleaved_decompress (interleaved.c:321)
==28386==    by 0x4E56E55: xf_Bitmap_Decompress (xf_graphics.c:169)
==28386==    by 0x6C4C2E3: update_gdi_cache_bitmap_v2 (bitmap.c:140)
==28386==    by 0x6C94CF2: update_recv_secondary_order (orders.c:3377)
==28386==    by 0x6C95F7F: update_recv_order (orders.c:3554)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC61D8: fastpath_recv_update_data (fastpath.c:502)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386==    by 0x6CC09C4: rdp_recv_pdu (rdp.c:1213)
==28386== 
==28386== Use of uninitialised value of size 8
==28386==    at 0x6D1260F: RleDecompress16to16 (bitmap.c:412)
==28386==    by 0x6D14A17: interleaved_decompress (interleaved.c:321)
==28386==    by 0x4E56E55: xf_Bitmap_Decompress (xf_graphics.c:169)
==28386==    by 0x6C4C2E3: update_gdi_cache_bitmap_v2 (bitmap.c:140)
==28386==    by 0x6C94CF2: update_recv_secondary_order (orders.c:3377)
==28386==    by 0x6C95F7F: update_recv_order (orders.c:3554)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC61D8: fastpath_recv_update_data (fastpath.c:502)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386==    by 0x6CC09C4: rdp_recv_pdu (rdp.c:1213)
==28386== 
==28386== Conditional jump or move depends on uninitialised value(s)
==28386==    at 0x4C3084C: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28386==    by 0x5A92671: ??? (in /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0)
==28386==    by 0x5A92B49: XPutImage (in /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0)
==28386==    by 0x4E56A6E: xf_Bitmap_New (xf_graphics.c:87)
==28386==    by 0x6C4C31D: update_gdi_cache_bitmap_v2 (bitmap.c:149)
==28386==    by 0x6C94CF2: update_recv_secondary_order (orders.c:3377)
==28386==    by 0x6C95F7F: update_recv_order (orders.c:3554)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC61D8: fastpath_recv_update_data (fastpath.c:502)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386== 
==28386== Conditional jump or move depends on uninitialised value(s)
==28386==    at 0x4C30702: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28386==    by 0x5A92671: ??? (in /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0)
==28386==    by 0x5A92B49: XPutImage (in /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0)
==28386==    by 0x4E56A6E: xf_Bitmap_New (xf_graphics.c:87)
==28386==    by 0x6C4C31D: update_gdi_cache_bitmap_v2 (bitmap.c:149)
==28386==    by 0x6C94CF2: update_recv_secondary_order (orders.c:3377)
==28386==    by 0x6C95F7F: update_recv_order (orders.c:3554)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC61D8: fastpath_recv_update_data (fastpath.c:502)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386== 
==28386== Conditional jump or move depends on uninitialised value(s)
==28386==    at 0x4C30716: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28386==    by 0x5A92671: ??? (in /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0)
==28386==    by 0x5A92B49: XPutImage (in /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0)
==28386==    by 0x4E56A6E: xf_Bitmap_New (xf_graphics.c:87)
==28386==    by 0x6C4C31D: update_gdi_cache_bitmap_v2 (bitmap.c:149)
==28386==    by 0x6C94CF2: update_recv_secondary_order (orders.c:3377)
==28386==    by 0x6C95F7F: update_recv_order (orders.c:3554)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC61D8: fastpath_recv_update_data (fastpath.c:502)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386== 
==28386== Conditional jump or move depends on uninitialised value(s)
==28386==    at 0x6C7EE29: update_read_coord (orders.c:185)
==28386==    by 0x6C86720: update_read_memblt_order (orders.c:1370)
==28386==    by 0x6C93CA0: update_recv_primary_order (orders.c:3244)
==28386==    by 0x6C95F98: update_recv_order (orders.c:3556)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC589F: fastpath_recv_update_data (fastpath.c:410)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386==    by 0x6CC09C4: rdp_recv_pdu (rdp.c:1213)
==28386==    by 0x6CC0FE2: rdp_recv_callback (rdp.c:1314)
==28386==    by 0x6CCAB19: transport_check_fds (transport.c:783)
==28386== 
==28386== Use of uninitialised value of size 8
==28386==    at 0x6C7EE3D: update_read_coord (orders.c:188)
==28386==    by 0x6C86720: update_read_memblt_order (orders.c:1370)
==28386==    by 0x6C93CA0: update_recv_primary_order (orders.c:3244)
==28386==    by 0x6C95F98: update_recv_order (orders.c:3556)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC589F: fastpath_recv_update_data (fastpath.c:410)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386==    by 0x6CC09C4: rdp_recv_pdu (rdp.c:1213)
==28386==    by 0x6CC0FE2: rdp_recv_callback (rdp.c:1314)
==28386==    by 0x6CCAB19: transport_check_fds (transport.c:783)
==28386== 
==28386== Conditional jump or move depends on uninitialised value(s)
==28386==    at 0x6C4309E: gdi_InvalidateRegion (region.c:384)
==28386==    by 0x4E45777: xf_gdi_memblt (xf_gdi.c:826)
==28386==    by 0x6C4BF25: update_gdi_memblt (bitmap.c:51)
==28386==    by 0x6C93D7B: update_recv_primary_order (orders.c:3247)
==28386==    by 0x6C95F98: update_recv_order (orders.c:3556)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC589F: fastpath_recv_update_data (fastpath.c:410)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386==    by 0x6CC09C4: rdp_recv_pdu (rdp.c:1213)
==28386==    by 0x6CC0FE2: rdp_recv_callback (rdp.c:1314)
==28386== 
==28386== Conditional jump or move depends on uninitialised value(s)
==28386==    at 0x6C7EE01: update_read_coord (orders.c:183)
==28386==    by 0x6C86720: update_read_memblt_order (orders.c:1370)
==28386==    by 0x6C93CA0: update_recv_primary_order (orders.c:3244)
==28386==    by 0x6C95F98: update_recv_order (orders.c:3556)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC589F: fastpath_recv_update_data (fastpath.c:410)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386==    by 0x6CC09C4: rdp_recv_pdu (rdp.c:1213)
==28386==    by 0x6CC0FE2: rdp_recv_callback (rdp.c:1314)
==28386==    by 0x6CCAB19: transport_check_fds (transport.c:783)
==28386== 
==28386== Invalid read of size 1
==28386==    at 0x4C2F122: strlen (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==28386==    by 0x4E5A68D: xf_SetWindowText (xf_window.c:577)
==28386==    by 0x4E4BC72: xf_rail_window_common (xf_rail.c:473)
==28386==    by 0x6CDB34F: update_recv_window_info_order (window.c:404)
==28386==    by 0x6CDC068: update_recv_altsec_window_order (window.c:584)
==28386==    by 0x6C95EB4: update_recv_altsec_order (orders.c:3530)
==28386==    by 0x6C95F5B: update_recv_order (orders.c:3552)
==28386==    by 0x6CC4CE2: fastpath_recv_orders (fastpath.c:205)
==28386==    by 0x6CC4F65: fastpath_recv_update (fastpath.c:265)
==28386==    by 0x6CC589F: fastpath_recv_update_data (fastpath.c:410)
==28386==    by 0x6CC62E1: fastpath_recv_updates (fastpath.c:536)
==28386==    by 0x6CC095E: rdp_recv_fastpath_pdu (rdp.c:1205)
==28386==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==28386== 
==28386== 
==28386== HEAP SUMMARY:
==28386==     in use at exit: 14,452,041 bytes in 5,999 blocks
==28386==   total heap usage: 34,530 allocs, 28,531 frees, 62,717,227 bytes allocated
==28386== 
==28386== LEAK SUMMARY:
==28386==    definitely lost: 4,030 bytes in 289 blocks
==28386==    indirectly lost: 16,034 bytes in 16 blocks
==28386==      possibly lost: 6,522,404 bytes in 491 blocks
==28386==    still reachable: 7,909,573 bytes in 5,203 blocks
==28386==         suppressed: 0 bytes in 0 blocks
==28386== Rerun with --leak-check=full to see details of leaked memory
==28386== 
==28386== For counts of detected and suppressed errors, rerun with: -v
==28386== Use --track-origins=yes to see where uninitialised values come from
==28386== ERROR SUMMARY: 17179401 errors from 1621 contexts (suppressed: 228 from 3)

**Comment by hardening** [comment]
Any chance you would recompile with WITH_VALGRIND_MEMCHECK activated, this will drastically reduce the errors you will have.
Could you also run with the variable env WLOG_LEVEL=debug ? Thank you.

**Comment by hardening** [comment]
@DarkWebster perhaps this https://gist.github.com/hardening/bffdb7bde6370d482806 could help with your case.

**Comment by DarkWebster** [comment]
I have no idea where to put WITH_VALGRIND_MEMCHECK on cmake, could you explain?
The environment variable I know how to set.

However I've rebuilt FreeRDP with your diff and it doesn't crash anymore.

**Comment by hardening** [comment]
It would have been a cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_VALGRIND_MEMCHECK=ON. But if my gist fixes it, then we have it.
