### ISSUE TITLE
Full screen not works - black screen

### ISSUE THREAD

**Issue by michelepetrazzo** [FreeRDP/FreeRDP#266]
Trying the full screen mode (-f) into a win2k8, win2k3 server, the unique thing that I see it's a black full screen.
Without the -f switch or -g 1024x768 it works correctly.

With old 0.8.2 version on the same hosts, full screen mode works.

**Comment by si458** [comment]
I currently also have this issue with latest build from git repo ?
any idea how to fix or way of debugging to find the fix?

**Comment by awakecoding** [comment]
@si458 pull again from master, fullscreen was broken this morning, I fixed it about an hour ago: https://github.com/FreeRDP/FreeRDP/pull/2378

**Comment by si458** [comment]
compiling now on my raspberry pi, will let you know results :)
