### ISSUE TITLE
printer redirection bug

### ISSUE THREAD

**Issue by mega-hertz** [FreeRDP/FreeRDP#2663]
Hello, i can't find my printer in windows, the redirection don't work.
In terminal it say

LoadLibraryA: /usr/local/lib/freerdp/printer-client.so: cannot open shared object file: No such file or directory

Ubuntu vivid and last freerdp

can you help me?
thanks

**Comment by hardening** [comment]
Looks very much like #2664 is a duplicate, is it ?

**Comment by mega-hertz** [comment]
Yes, I'm sorry

**Comment by feres123** [comment]
No problem
