### ISSUE TITLE
printer redirection bug

### ISSUE THREAD

**Issue by mega-hertz** [FreeRDP/FreeRDP#2664]
Hello, i can't find my printer in my RDP with xfreerdp

I have ubuntu vivid and lastest freerdp

terminal say 
LoadLibraryA: /usr/local/lib/freerdp/libprinter-client.so

thanks

**Comment by hardening** [comment]
@mega-hertz I'd say that you have not compiled with printer redirection. Check your cmake configuration using "ccmake ." in the FreeRDP top directory

**Comment by mega-hertz** [comment]
I don't understand, i'm sorry.

I tried again to reinstall freerdp with method ifconfig.dk/freerdp

when I type
mega@mega-desktop:~/FreeRDP$ cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON

install bug :

-- FreeRDP GIT
-- Git Revision 29de9b6
-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Skipping recommended feature Wayland for Wayland (Wayland client)
-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Skipping optional feature OpenSLES for multimedia (OpenSLES audio / video)
--     Enable feature OpenSLES using "-DWITH_OPENSLES=ON"
-- Finding recommended feature OSS for sound (audio input, audio output and multimedia redirection)
--     Disable feature OSS using "-DWITH_OSS=OFF"
-- Found OSS Audio
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Finding optional feature Pulse for sound (audio input, audio output and multimedia redirection)
-- checking for module 'libpulse'
--   package 'libpulse' not found
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find Pulse (missing: PULSE_INCLUDE_DIR PULSE_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindPulse.cmake:11 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/FindFeature.cmake:31 (find_package)
  CMakeLists.txt:608 (find_feature)


-- Configuring incomplete, errors occurred!
See also "/home/mega/FreeRDP/CMakeFiles/CMakeOutput.log".
See also "/home/mega/FreeRDP/CMakeFiles/CMakeError.log".

**Comment by hardening** [comment]
@mega-hertz this is quite trivial compilation bug, did you follow the wiki to install your compilation env ? Obviously you're missing the pulseaudio dev headers, either disable pulse support or install the corresponding packages.

**Comment by mega-hertz** [comment]
I find in internet a new method
    sudo apt-add-repository ppa:freerdp-team/freerdp
    sudo apt-get update
    sudo apt-get install freerdp-x11 

and It's good ! Printer and gateway ! I'm so happy, 3 days... i go in my bed!

**Comment by bmiklautz** [comment]
@mega-hertz nice it worked for you. However I just wonder what version you are using now? - Since it looks like the ppa wasn't update for a while.
