### ISSUE TITLE
[Ubuntu14.04] Freerdp 1.2.4 usb redirection udevman

### ISSUE THREAD

**Issue by gazzer3000** [FreeRDP/FreeRDP#2667]
Hello everyone,

im using ubuntu 14.04 XFCE 32bit and build xfreerdp from here.

What i did so far is to download the latest freerdp-master.zip. After this i installed some packeges:
apt-get install uuid-dev
apt-get install libdbus-glib-1-dev
apt-get install dbus-*-dev
apt-get install libpcsclite-dev, libusb-1.0-0-dev
apt-get install libusb-1.0-0-dev
[Edit1]
I missed apt-get install libudev-dev

My actual cmake build looks like this:
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DWITH_PCSC=ON -DSTATIC_CHANNELS=OFF -DCHANNEL_RDPSND_CLIENT=ON -DWITH_ALSA=ON -DWITH_PULSE=ON 

After this i do a make and at the end a make install.

So far without any problems but when i try to redirect a usb device for example a Benq usb DVD burner or something else like a keyboard or mouse i get alway this:

xfreerdp /sec:rdp /dvc:urbdrc,id,dev:046d:c019 /v:SERVER

[14:37:49:980] [25671:25672] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
[14:37:49:981] [25671:25672] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: user
[14:37:49:190] [25671:25672] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel urbdrc
[14:37:49:191] [25671:25672] [ERROR][com.winpr.library] - LoadLibraryA: /usr/local/lib/i386-linux-gnu/freerdp/liburbdrc-client.so: cannot open shared object file: No such file or directory

Even if i try to run the command as root nothing changes.

Is something still missing? Hope you can help.

Best regards

[Edit2]
Finally its working but i cant redirect anything. I always get 

[WARN][com.freerdp.channels.urbdrc.client] - bus:3 dev:2 not exist in udevman

I tried a usb mouse, usb networkdevice and a usb wlan. Always the same trouble with udevman.

**Comment by HenryJacques** [comment]
How did you get it working? By adding -DCHANNEL_URBDRC=ON ?

Did you try as root?
(the udevman error seems to be irrelevant, see issue #2113)

**Comment by gazzer3000** [comment]
I got it working after i installed the last missing package.

So far i needed:
apt-get install uuid-dev
apt-get install libdbus-glib-1-dev
apt-get install dbus-*-dev
apt-get install libpcsclite-dev, libusb-1.0-0-dev
apt-get install libusb-1.0-0-dev
apt-get install libudev-dev

And built it with this:

cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DWITH_PCSC=ON -DSTATIC_CHANNELS=OFF -DCHANNEL_RDPSND_CLIENT=ON -DWITH_ALSA=ON -DWITH_PULSE=ON 

-DCHANNEL_URBDRC_CLIENT=ON => is the critical one if you want use the usb redirection.

**Comment by bmiklautz** [comment]
@gazzer3000 if your basic issue (build) is resolved can we close the issue?

**Comment by meanbunny** [comment]
Thank you so much for showing what libraries needed to be installed. This should be described in the documentation somewhere

**Comment by akallabeth** [comment]
Fixed with #5745
