### ISSUE TITLE
rail plugin show no window

### ISSUE THREAD

**Issue by michelepetrazzo** [FreeRDP/FreeRDP#267]
If I try the rail plugin with:
./client/X11/xfreerdp -d DOMAIN -u user  --app --plugin channels/rail/rail.so --data "||winword" -- serverip
loading plugin channels/rail/rail.so
connected to serverip:3389
Password:  -> passwd typed

I see no window on the screen. The only thing that I see it's a new "program" on my task bar that show me correctly (for winword in this case) "untitled document".

enabling the rail debug, when I press on the task bar on the new "program" I see:

DBG_X11 xf_event_process (655): FocusIn Event: wnd=0x4000015
DBG_RAIL rail_send_pdu (115): Sending Activate PDU, length:9
DBG_X11 xf_event_process (655): KeymapNotify Event: wnd=0x0000
DBG_RAIL window_state_update (143): ownerWindowId:0x0001004E
DBG_RAIL window_state_update (147): windowId=0xD00C0 ownerWindowId=0x1004E
Window Styles:
{
        WS_CLIPSIBLINGS
        WS_DISABLED
        WS_POPUP
        WS_VISIBLE
}
Extended Window Styles:
{
        WS_EX_TOPMOST
}
DBG_RAIL window_state_update (163): ShowState:5
0000 4d 00 53 00 49 00 4d 00 45 00 5f 00 50 00 6f 00 M.S.I.M.E._.P.o.
0010 70 00 75 00 70 00 4d 00 65 00 73 00 73 00 61 00 p.u.p.M.e.s.s.a.
0020 67 00 65 00                                     g.e.
DBG_RAIL window_state_update (183): Client Area Offset: (0, 0)
DBG_RAIL window_state_update (192): Client Area Size: (153, 89)
DBG_RAIL window_state_update (211): Window Offset: (0, 0)
DBG_RAIL window_state_update (220): Window Client Delta: (0, 0)
DBG_RAIL window_state_update (229): Window Size: (153, 89)
DBG_RAIL window_state_update (246): Window Rect #0: left:7 top:0 right:145 bottom:1
DBG_RAIL window_state_update (246): Window Rect #1: left:4 top:1 right:148 bottom:2
DBG_RAIL window_state_update (246): Window Rect #2: left:3 top:2 right:149 bottom:3
DBG_RAIL window_state_update (246): Window Rect #3: left:2 top:3 right:150 bottom:4
DBG_RAIL window_state_update (246): Window Rect #4: left:1 top:4 right:151 bottom:7
DBG_RAIL window_state_update (246): Window Rect #5: left:0 top:7 right:152 bottom:65
DBG_RAIL window_state_update (246): Window Rect #6: left:1 top:65 right:151 bottom:68
DBG_RAIL window_state_update (246): Window Rect #7: left:2 top:68 right:150 bottom:69
DBG_RAIL window_state_update (246): Window Rect #8: left:3 top:69 right:149 bottom:70
DBG_RAIL window_state_update (246): Window Rect #9: left:4 top:70 right:148 bottom:71
DBG_RAIL window_state_update (246): Window Rect #10: left:7 top:71 right:145 bottom:72
DBG_RAIL window_state_update (246): Window Rect #11: left:8 top:72 right:18 bottom:74
DBG_RAIL window_state_update (246): Window Rect #12: left:8 top:74 right:17 bottom:76
DBG_RAIL window_state_update (246): Window Rect #13: left:8 top:76 right:16 bottom:77
DBG_RAIL window_state_update (246): Window Rect #14: left:8 top:77 right:15 bottom:79
DBG_RAIL window_state_update (246): Window Rect #15: left:8 top:79 right:14 bottom:80
DBG_RAIL window_state_update (246): Window Rect #16: left:8 top:80 right:13 bottom:82
DBG_RAIL window_state_update (246): Window Rect #17: left:8 top:82 right:12 bottom:84
DBG_RAIL window_state_update (246): Window Rect #18: left:8 top:84 right:11 bottom:85
DBG_RAIL window_state_update (246): Window Rect #19: left:8 top:85 right:10 bottom:87
DBG_RAIL window_state_update (246): Window Rect #20: left:8 top:87 right:9 bottom:88
DBG_RAIL window_state_update (256): Window Visible Offset: (-2147483648, 2147483647)
DBG_RAIL window_state_update (147): windowId=0x1004E ownerWindowId=0xFFFFFFFE
Window Styles:
{
        WS_CLIPSIBLINGS
        WS_DISABLED
        WS_POPUP
        WS_VISIBLE
}
Extended Window Styles:
{
        WS_EX_NOACTIVATE
        WS_EX_TOOLWINDOW
        WS_EX_TOPMOST
}
DBG_RAIL window_state_update (163): ShowState:5
DBG_RAIL window_state_update (273): Visibility Rect #0: left:0 top:0 right:1 bottom:1
DBG_X11 xf_event_process (655): MapNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): VisibilityNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): Expose Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_RAIL rail_send_pdu (115): Sending System Command PDU, length:10
DBG_X11 xf_event_process (655): VisibilityNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): MapNotify Event: wnd=0x4000017
DBG_RAIL rail_send_pdu (115): Sending System Command PDU, length:10
DBG_X11 xf_event_process (655): VisibilityNotify Event: wnd=0x4000017
DBG_X11 xf_event_process (655): Expose Event: wnd=0x4000017
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): FocusOut Event: wnd=0x4000015
DBG_RAIL rail_send_pdu (115): Sending Activate PDU, length:9
DBG_X11 xf_event_process (655): UnmapNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): DestroyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_X11 xf_event_process (655): PropertyNotify Event: wnd=0x400002B
DBG_RAIL window_state_update (147): windowId=0x1004E ownerWindowId=0xFFFFFFFE
Window Styles:
{
        WS_DISABLED
        WS_POPUP
}
Extended Window Styles:
{
        WS_EX_TOOLWINDOW
        WS_EX_TOPMOST
}
DBG_RAIL window_state_update (163): ShowState:0
DBG_X11 xf_event_process (655): UnmapNotify Event: wnd=0x4000017

but however, no window.

**Comment by bmiklautz** [comment]
Should work with the current master. If the problem still exists please re-open this issue or create a new one.
