### ISSUE TITLE
debian 8 jessie, freerdp 1.1.0 - problem with num lock

### ISSUE THREAD

**Issue by unix196** [FreeRDP/FreeRDP#2671]
Good day. 
Debian GNU/Linux 8.0 (jessie)
Linux  3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) i686 GNU/Linux

All packet from stable repo.
dpkg -l | grep freerdp-x11
ii  freerdp-x11                           1.1.0~git20140921.1.440916e+dfsg1-4 i386

Terminal server: Windows server 2008 R1 64. 

Don't properly work NumLock. Description: first I enable NumLock, can write digit in browser, text editor. Connect to Terminal Server. Key on keyboard on right don't work (bulb on keyboard is broil), Disable NumLock key - can write digit in terminal.

**Comment by akallabeth** [comment]
This issue has been fixed on master (upcoming 2.0)
