### ISSUE TITLE
Is it possible to specify the %CLIENTNAME% variable?

### ISSUE THREAD

**Issue by zbonjourdhcu** [FreeRDP/FreeRDP#2677]
When connecting to a Windows server, the clientname variable is assigned as the hostname of my connecting machine.  Is there a way to change this behavior?  Something like "/clientname:bogus-name"?

**Comment by HenryJacques** [comment]
Almost ;) Use "/client-hostname:bogus-name"

**Comment by zbonjourdhcu** [comment]
Awesome!  I don't see that in the Wiki.  Shouldn't it be added?
https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface

**Comment by HenryJacques** [comment]
It should yes. But it is in the command line help (xfreerdp /help)
