### ISSUE TITLE
Please do/update a github release

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#2678]
Could you please update the [Github FreeRDP Release Page](https://github.com/FreeRDP/FreeRDP/releases) with a newer release ? The last one dates back on September 12 of last year.
Some linux/*BSD distributions will update the ther repos only when that page will be updated.
Thank you.

**Comment by CyberBotX** [comment]
I would like to second this, as I am trying to update FreeBSD's Remmina port but the latest FreeRDP release is too old to allow that to happen.

**Comment by antenore** [comment]
:+1:

**Comment by bmiklautz** [comment]
There wasn't a official release since then. We will update the release page when there is actually a new release we are happy with.

**Comment by CyberBotX** [comment]
Can you give any timeline to when they might happen? The 1.2.0-beta1+android9 release isn't sufficient to update Remmina to their 1.2 releases.

**Comment by bmiklautz** [comment]
@CyberBotX there is no fixed timeline at the moment. Sorry to say but it's ready when it's ready.

**Comment by dktrkranz** [comment]
@bmiklautz please try to agree on a code freeze ASAP. Software developers using FreeRDP in their codebase would benefit a lot having a stable API/ABI for a while to release their new releases.

I know this could be difficult, but I think all FreeRDP ecosystem will have a benefit of a stable FreeRDP version.

**Comment by bmiklautz** [comment]
@dktrkranz we are working on it.

**Comment by antenore** [comment]
@hubbitus

**Comment by Hubbitus** [comment]
Maintain stable API should not be so difficult just accuracy required. Sometimes bacward capability may be painfull... But at least clear API/ABI (bump .so-name on breacking changes) versioning highly appreciated! Very thanks for your work!

**Comment by weberhofer** [comment]
Is there any news on that? I'm highly waiting for updating the openSUSE packages, as the all the current versions of FreeRDP and Remmina are much better that the current stable ones since a while!

**Comment by bmiklautz** [comment]
#2839
