### ISSUE TITLE
Mouse cursor disappears when using specific apps like notes in remote session

### ISSUE THREAD

**Issue by endriu0** [FreeRDP/FreeRDP#2679]
Hi,

Been struggling with this for a while now - mouse cursor would disappear when going over options in databases etc. Seems that the cursor disappears when it's supposed to change to a small hand. Issue exists on the latest commit as well but not in remmina. 

Attaching photos as screenshots do not show the cursor.... - is that something that can be checked ? I can do any testing if required. 

Explanation of pics :  
1 - normal pointer on freerdp when not hovering over any of the options
2 - when hovering over any of the options in freerdp pointer disappears. 
3 - normal pointer on remmina when not hovering over any of the options
4 - when hovering over any of the options in remmina pointer changes to a small hand. 

Both connections are done to the same server / virtual machine. End machine is a Windows 7 one. 
System am on : Fedora 22
Kernel : 4.0.4-303.fc22.x86_64

![freerdp 1](https://cloud.githubusercontent.com/assets/7290785/8002580/f69b8e76-0b67-11e5-8253-d7af1bf818f4.jpg)
![freerdp 2](https://cloud.githubusercontent.com/assets/7290785/8002581/f69bda02-0b67-11e5-8e19-15e77de97fb3.jpg)
![remmina 1](https://cloud.githubusercontent.com/assets/7290785/8002582/f69e965c-0b67-11e5-9d5a-05cd2144e172.jpg)
![remmina 2](https://cloud.githubusercontent.com/assets/7290785/8002583/f6a0537a-0b67-11e5-81be-bf7d62eceeee.jpg)

**Comment by hardening** [comment]
@endriu0 could you try to recompile with -DWITH_DEBUG_RAIL=ON and send the output.

**Comment by endriu0** [comment]
Ok will try it tomorrow.  Thanks

**Comment by endriu0** [comment]
Hi, checked now - after loading newest master and compiling with the above option here's the output :

[proxychains] config file found: /etc/proxychains.conf
[proxychains] preloading /usr/lib/libproxychains4.so
[proxychains] DLL init: proxychains-ng 4.8.1
[09:44:05:916] [27731:27734] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[09:44:05:916] [27731:27734] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[09:44:05:916] [27731:27734] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[proxychains] Random chain  ...  xxx...  xxxx  ...  OK
[09:44:06:975] [27731:27735] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive (static)
[09:44:27:588] [27731:27735] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: X (type=8 id=1)
[09:45:24:432] [27731:27734] [ERROR][com.freerdp.color] - failed to convert from 16 bpp to 32 bpp
[09:45:26:611] [27731:27734] [ERROR][com.freerdp.color] - failed to convert from 16 bpp to 32 bpp

The 2 messages about converting appeared the moment I tried to click into any of the options as per above screenshots and the pointer disappeared.

**Comment by hardening** [comment]
@endriu0 ok I see the problem, conversion for 16bpp cursor is not implemented.
@nfedera I know you are our local expert for cursors conversion, it would be so nice if you could implement it.

**Comment by nfedera** [comment]
@hardening re WITH_DEBUG_RAIL ? This problem is not specific to rail - right ?
@endriu0 Which program/software can be installed to reproduce the issue ?

**Comment by endriu0** [comment]
Seen this issue mainly in Lotus Notes 9 but will check other apps as well
tomorrow and give you a list.

**Comment by endriu0** [comment]
@nfedera sorry double checked today and can only see the issue in Lotus Notes 8.5.2 and 8.5.3. All the other apps I tried seem to work ok and sometimes also seen the issue when using mstsc from my windows host to another one before. 

I will keep trying other apps just to see is there anything else that you can update.

**Comment by hardening** [comment]
@nfedera yep you're right, it has nothing RAIL specific

**Comment by nfedera** [comment]
Just saw that we do already have an existing issue #2460 for this

**Comment by endriu0** [comment]
PR now Merged - issue solved. Closing.
