### ISSUE TITLE
arm64 Build OpenSSL

### ISSUE THREAD

**Issue by phongleq** [FreeRDP/FreeRDP#2680]
How would I go at making a the ssl for arm64?

**Comment by bmiklautz** [comment]
@phongleq this is more a openssl than FreeRDP specific question. If you search the web you can find a lot of references on this topic.

**Comment by phongleq** [comment]
Thanks for the response. I did tried different version of openssl that would compile a arm64 version of it. My problem was that after doing so I would never be able to connect with it like I would with the script provided in FreeRDP. I know that there is a patch that is applied to the openssl in FreeRDP and wasn't sure if there was something special I would need to do to get a different version of OpenSSL to work with the project.

**Comment by bmiklautz** [comment]
@phongleq the applied patch was only a work around in order to build openssl. Can you test if the branch ios/openssl in my repository fixes your problem? -https://github.com/bmiklautz/FreeRDP/tree/ios/openssl

**Comment by phongleq** [comment]
Cool it works perfectly! Though I am having issues with building the project for ARM64. I added to the arm64 to the iOSToolchain.cmake file like so:

```set (IOS_ARCH arm64 armv7 armv7s)```

Im not sure if there is more to do than that , but I do get a crash with winpr library. It crashes at the line with this:

```*pType = wHandle->Type;```

in the handler.h file

**Comment by phongleq** [comment]
Ok nevermind I found out that you could do this https://github.com/FreeRDP/FreeRDP/issues/2162

**Comment by phongleq** [comment]
So I got it setup using the new script and ran into a issue when trying to connect to a remote desktop

```[11:13:09:971] [219:6119f000] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
2015-06-10 11:13:09.543 iFreeRDP[219:7104] ios_run_freerdp: inst->rdp_connect failed```

**Comment by akallabeth** [comment]
Current master script builds OpenSSL for arm64
