### ISSUE TITLE
how to call aFreeRDP in another Android APP to connect to a remote App ? 

### ISSUE THREAD

**Issue by cloudfirst** [FreeRDP/FreeRDP#2720]
I am working in an android app that get the hostname, user name and password, as well as remote program name, and use intent mechanism to invoke session activity in aFreeRDP.

however, I can't find any tech document on how to finish this invocation .
can any one help on this ?

**Comment by bmiklautz** [comment]
@cloudfirst there is no real documentation on the Android client at the moment. Have a look to FreeRDP/client/Android/FreeRDPCore to see how the intent(s).

If you have further questions visit our irc channel (#freerdp on freenode) or write a mail to the mailing list but please don't add questions in the issue tracker.
