### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by chrisdavis925** [FreeRDP/FreeRDP#2726]
Hi,

I've been observing XfreeRDP (build from the latest master today) and saw that the session started at 87.8MB of memory usage. One hour later, it's at 90.4MB. It slowly climbs overtime, but never goes down. 

Is this by design? Will it eventually flush from memory? 

I am considering deploying XfreeRDP as a thin client solution, but my concern is that memory usage will continue to climb without ever being flushed out. 
Any one have any insight?

**Comment by akallabeth** [comment]
@chrisdavis925 A few huge pulls have been merged today and some smaller ones are going to be merged soon fixing issues like small leaks. You can either try to merge outstanding pulls with memory leak fixes yourself and test again or wait for upstream to merge them.
If you need something a little more stable you can also try out the stable branch.

**Comment by hardening** [comment]
@chrisdavis925 there's all kind of caches in RDP, perhaps it's just the cache that getting filled... IIRC a server-side RDP sessions takes 100MB of cache.

**Comment by akallabeth** [comment]
@chrisdavis925 Closing due to lack of feedback. If you still think this is an issue let me know.
