### ISSUE TITLE
Problems connecting through GW

### ISSUE THREAD

**Issue by LGLumi** [FreeRDP/FreeRDP#2743]
Connecting to Windows Server 2012 through GW. I have actually option to go there through GW and not, so I could easily test it without GW and it works, Windows RDP does work through this GW. I tried standard build and even different options. Ver: 1.2.4 Why? 1.2.x version in general have problem with GW stability, so I tried to build latest, but without success to connect through GW.

/opt/freerdp-git/bin/xfreerdp -sec-nla /cert-ignore /rfx /gdi:hw /f /v:(host server) /g:(gateway) /gd:(gw-domain) /gu:(gw-user) /u:"" /gp:(gw-password) 

[10:48:14:900] [29194:29195] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_TLS_CONNECT_FAILED [0x20008]
[10:48:14:901] [29194:29195] [ERROR][com.freerdp.core.gateway.tsg] - rpc_connect error!
[10:48:14:901] [29194:29195] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[10:48:14:901] [29194:29195] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[10:48:14:901] [29194:29195] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1

No matter what have I tried, I end up with this error. Any solutions? 

Thank you very much.

Henry

**Comment by LGLumi** [comment]
Okay, it is quite odd but I did manage to run it with absolutely same steps on two another computers, one with same distr. (Debian Wheezy) and on one with Ubuntu 14.04 LTS. Strange is on two machines I just simply cannot get it to work. It looks like a problem with another software while two those Debian machines that it actually works on are clean installations.

**Comment by LGLumi** [comment]
In the end I have resolved that problem was just on one machine which kinda makes this almost invalid. I am closing this issue. If I would encounter something more "massive", I will post issue.

**Comment by audhen** [comment]
I have the problem too in use with Royal TSX on Mac OSX. No connection will work...

**Comment by bmiklautz** [comment]
@audhen you maybe want to report the issue directly there...
