### ISSUE TITLE
Remote control session termination freezes

### ISSUE THREAD

**Issue by awakecoding** [FreeRDP/FreeRDP#2744]
This happens with 2008 R2 SP1. In order to reproduce, connect twice to the same terminal server, go in Remote Desktop Services Manager, select the session to shadow, click Remote Control. If the user in the other session denies access, or if the prompt timer expires (30 seconds), then FreeRDP will freeze. If the user accepts, it works, but FreeRDP will freeze when the shadowing session is over instead of going back to the original session. This has been tested with the latest xfreerdp, mileage may vary with other clients.

**Comment by bmiklautz** [comment]
@awakecoding I've seen that too a while back. I don't remember exactly but I think changing the compression level helped with that problem.

**Comment by Fred1979** [comment]
I'm having the same issue, any update on this ?

**Comment by Fred1979** [comment]
@bmiklautz When activating compression with the -z switch the problem seem solved.   Thanks a lot !

**Comment by awakecoding** [comment]
@Fred1979 this actually disables it. I found out experimentally that the problem only affects RDP6.1 compression, using /compression-level:2 should also work.

**Comment by perkerk** [comment]
The RDP6.1 decompression looks broken. The mppc_decompress and xcrush_decompress_l1 functions for don't quite work right together. The MatchHistoryOffset entry should be there for every match, instead mppc_decompress writes literals in the match offset position and xcrush_decompress_l1 tries to interpret the literal as an offset

![rdp6 1-bc-decompression](https://user-images.githubusercontent.com/4057100/33608519-6345a4a6-d98a-11e7-942d-0167e65609ee.png)
