### ISSUE TITLE
Connecting for ArchLinux to a Windows 8 host

### ISSUE THREAD

**Issue by masterkorp** [FreeRDP/FreeRDP#2746]
Hello,

I am trying to connect to a windows 8, the computers are both in the same LAN

```
$ xfreerdp /cert-ignore /v:192.168.1.130 /u:myuser /p:mypass /sec:rdp
[01:17:31:697] [9532:9533] [ERROR][com.freerdp.legacy] - Property 474 does not
exist
[01:17:46:712] [9532:9533] [ERROR][com.freerdp.legacy] - freerdp_set_last_error
0x2000C

[01:17:46:712] [9532:9533] [ERROR][com.freerdp.legacy] - Error: protocol
security negotiation or connection failure
```
I added ``/cert-ignore`` and ``/sec:rdp`` in a [futile attempt](http://unix.stackexchange.com/questions/119880/make-freerdp-prompt-user-for-username-and-password) to make the error go away.

```
$ pacman -Qi freerdp 
Name           : freerdp
Version        : 1:1.2.0_beta1+android9-1
````

Any suggestions would be welcome.

**Comment by LGLumi** [comment]
I've had this kind of problem with gateway on debian wheezy. It looks like authentification was not correct. Have you tried -sec-nla ? That is like "must" for Windows 2012 and perhaps aswell for Windows 8.

**Comment by masterkorp** [comment]
@LGLumi Nevermind me.

I just discovered that [Windows 8 base does not actually have RDP](http://www.eightforums.com/network-sharing/25879-remote-desktop-not-working-windows-8-a.html) 
Shame on me, but that *Remote assistance is really misleading*.
