### ISSUE TITLE
Cursor doesn't change properly when hovering over things (regression)

### ISSUE THREAD

**Issue by jeremyvisser** [FreeRDP/FreeRDP#2755]
Inside an RDP session, if you hover over a text box or link, your cursor will change accordingly.

However, recently, this has stopped, where the cursor will either be invisible, or will be "stuck" on the cursor that was set when you first log on, and almost never changes after that.

Running `git bisect`, I have found that the regression occurred in one of the commits 1f414ec9e71de5ea7627267752d14edeb5afd667, 7c3f8f33abcca6587146298595534ca591d23510, or 5de0e02c6122b38567a34c181b05e0560e7fe778, however I am unable to test them individually as they crash for unrelated reasons and I had to `git bisect skip` them:

```
$ git bisect skip
There are only 'skip'ped commits left to test.
The first bad commit could be any of:
1f414ec9e71de5ea7627267752d14edeb5afd667
7c3f8f33abcca6587146298595534ca591d23510
5de0e02c6122b38567a34c181b05e0560e7fe778
We cannot bisect more!
```

**Comment by bmiklautz** [comment]
@jeremyvisser can you give some details on how to reproduce or test? - I've tested with the nightly build from today. If I for example open an editor and move the mouse over the text it changes as expected.

**Comment by jeremyvisser** [comment]
Client machine is Fedora 22 with GNOME 3 and Intel graphics with git versions of FreeRDP and Remmina installed. I use FreeRDP through Remmina. I haven't tried to reproduce through xfreerdp.

Remote machines tested are all running Server 2012 R2 with 32bpp colour and maximum experience settings (e.g. animations, font smoothing, etc.)

**Comment by bmiklautz** [comment]
@jeremyvisser could you try directly with xfreerdp and see if the problem is reproduce able with it too?

**Comment by jeremyvisser** [comment]
I have tried to reproduce with xfreerdp today and afraid I have not been able to reproduce at all. I'm not sure whether that is because Remmina uses different settings to xfreerdp, but I have experimented with various quality and encoding settings, and xfreerdp works properly every single time.

So whatever this bug is, is specific to its interaction with Remmina.

**Comment by bmiklautz** [comment]
@jeremyvisser please open an issue with Remmina. We have done quite a lot of changes lately and it might be that the latest master doesn't work with Remmina at the moment since the API could have changed a little.

**Comment by jeremyvisser** [comment]
Fair enough. Looks like this bug that was reported in Remmina just now may be related: https://github.com/FreeRDP/Remmina/issues/598

**Comment by Supermathie** [comment]
Please re-open, I just built from master version 1.2.5-dev (git 17834af) and am getting this same problem.

Even after reducing CLI options down to:

    xfreerdp /u:michael@realm /v:target

The cursor is unchanging.

It changes properly with the system version of freerdp (1.1.0~git20140921.1.440916e+dfsg1-2ubuntu1)

**Comment by bmiklautz** [comment]
@Supermathie for xfreerdp can you add some notes how you've tested? - I tried to reproduce this against windows 7 and windows 10 but couldn't find any problem.
If you've compiled yourself did you compile with xcursor support (WITH_XCURSOR, package libxcursor-dev on debian and ubuntu).

My test scenario:
* connect to the machine
* open notepad
* put the focus on notepad
  * the cursor should change to the text select cursor
* open a file explorer and move the mouse over the folders/navigation on the left
  * the cursor should change to a hand
* start some "big" program that takes a little to startup or do something else that occupies the system a little
  * the cursor should change to the busy or "working in background" cursor

I've tested with the latest master of today (d9711164577772db71ab0a92b4b8d94b67ed2d4d).

**Comment by hardening** [comment]
@Supermathie a commit improving mouse cursor in some situation has just been committed. Would you mind give a try with last master ?

**Comment by Supermathie** [comment]
@hardening Tried updating to latest (4626f17) and it didn't affect anything - the problem was actually I missed XCURSOR as @bmiklautz noted.

After installing the dev library and doing some cursory tests it works just fine! Thanks.
