### ISSUE TITLE
Authentication Failure Does Not Set LastError to FREERDP_ERROR_AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by itsmikeeng** [FreeRDP/FreeRDP#2760]
Providing credentials with bad password sets context->LastError to FREERDP_ERROR_CONNECT_TRANSPORT_FAILED instead of expected FREERDP_ERROR_AUTHENTICATION_FAILED after call to freerdp_connect().

Using wfreerdp, the code reached the nla_client_begin() method in core\transport.c but succeeds and doesn't call freerdp_set_last_error(context, FREERDP_ERROR_AUTHENTICATION_FAILED);

**Comment by giox069** [comment]
See also issue #2434 (and #2432).

**Comment by bjcollins** [comment]
I encountered the same thing with xfreerdp when using NLA, after researching the spec I found that the server sends a TLS ALERT for ACCESS DENIED. It looks like the server code in the freerdp sources will set this alert, but there is no client side catching of the alert to set the error appropriately. I do not have the resources to work on wfreerdp, but I will try to post a pull request soon which addresses this same issue for xfreerdp.

**Comment by bjcollins** [comment]
https://github.com/FreeRDP/FreeRDP/pull/2824

**Comment by giox069** [comment]
@itsmikeeng: I think it's fixed with merged PR #2824.

**Comment by akallabeth** [comment]
Can we close this?

**Comment by giox069** [comment]
Yes, it works, thank you. You can close it.
There is a related issue to test: if you compile with -DWITH_SANITIZE_ADDRESS=on, you will notice that when an authentication error is correctly detected, the library does not correctly deallocate a lot of memory objects.

**Comment by akallabeth** [comment]
@giox069 Will have a look at it. Is there already a bug entry for that? Anyway, closing this one as the deallocation stuff is a different matter.

**Comment by giox069** [comment]
@akallabeth I never opened an issue for that, and never searched.
