### ISSUE TITLE
Ubuntu 14.04 Server Compile Error

### ISSUE THREAD

**Issue by rspringer** [FreeRDP/FreeRDP#2769]
Trying to build the server
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_Server=ON .
make
Any help would be appreciated !!!!
Thanks

result:
[ 37%] Built target winpr
[ 37%] Built target winpr-hash
[ 37%] Built target winpr-makecert-tool
[ 38%] Built target winpr-makecert
[ 76%] Built target freerdp
[ 78%] Built target rdtk
[ 79%] Built target tsmf-client
[ 79%] Built target tsmf-client-ffmpeg-decoder
[ 80%] Built target tsmf-client-oss-audio
[ 81%] Built target parallel-client
[ 81%] Built target rail-client
[ 81%] Built target serial-client
[ 82%] Built target echo-client
[ 82%] Built target echo-server
[ 83%] Built target cliprdr-client
[ 83%] Built target cliprdr-server
[ 83%] Built target rdpgfx-client
[ 83%] Built target drive-client
[ 83%] Built target audin-client
[ 83%] Built target audin-client-oss
[ 83%] Built target audin-server
[ 84%] Built target smartcard-client
[ 85%] Built target drdynvc-client
[ 85%] Built target drdynvc-server
[ 85%] Built target encomsp-client
[ 85%] Built target encomsp-server
[ 86%] Built target rdpdr-client
[ 87%] Built target rdpdr-server
[ 87%] Built target disp-client
[ 88%] Built target rdpsnd-client
[ 88%] Built target rdpsnd-client-oss
[ 88%] Built target rdpsnd-server
[ 88%] Built target rdpei-client
[ 89%] Built target rdpei-server
[ 89%] Built target remdesk-client
[ 90%] Built target remdesk-server
[ 90%] Built target freerdp-channels-server
[ 91%] Built target freerdp-client
[ 91%] Built target generate_argument_docbook
[ 94%] Built target xfreerdp-client
[ 95%] Built target xfreerdp.manpage
[ 95%] Built target xfreerdp-cli
[ 96%] Built target freerdp-server
[ 96%] Building C object server/shadow/CMakeFiles/freerdp-shadow.dir/X11/x11_shadow.c.o
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c: In function â€˜x11_shadow_validate_regionâ€™:
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c:542:47: error: â€˜x11ShadowSubsystemâ€™ has no member named â€˜xdamage_regionâ€™
  XFixesSetRegion(subsystem->display, subsystem->xdamage_region, &region, 1);
                                               ^
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c:543:2: warning: implicit declaration of function â€˜XDamageSubtractâ€™ [-Wimplicit-function-declaration]
  XDamageSubtract(subsystem->display, subsystem->xdamage, subsystem->xdamage_region, None);
  ^
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c:543:47: error: â€˜x11ShadowSubsystemâ€™ has no member named â€˜xdamageâ€™
  XDamageSubtract(subsystem->display, subsystem->xdamage, subsystem->xdamage_region, None);
                                               ^
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c:543:67: error: â€˜x11ShadowSubsystemâ€™ has no member named â€˜xdamage_regionâ€™
  XDamageSubtract(subsystem->display, subsystem->xdamage, subsystem->xdamage_region, None);
                                                                   ^
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c: In function â€˜x11_shadow_screen_grabâ€™:
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c:700:14: error: â€˜x11ShadowSubsystemâ€™ has no member named â€˜xshm_gcâ€™
     subsystem->xshm_gc, 0, 0, subsystem->width, subsystem->height, 0, 0);
              ^
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c: In function â€˜x11_shadow_xinerama_initâ€™:
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c:947:2: warning: implicit declaration of function â€˜XDamageQueryVersionâ€™ [-Wimplicit-function-declaration]
  if (!XDamageQueryVersion(subsystem->display, &major, &minor))
  ^
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c: In function â€˜x11_shadow_xshm_initâ€™:
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c:1062:11: error: â€˜x11ShadowSubsystemâ€™ has no member named â€˜xshm_gcâ€™
  subsystem->xshm_gc = XCreateGC(subsystem->display, subsystem->root_window,
           ^
/home/rolf/FreeRDP/server/shadow/X11/x11_shadow.c:1065:44: error: â€˜x11ShadowSubsystemâ€™ has no member named â€˜xshm_gcâ€™
  XSetFunction(subsystem->display, subsystem->xshm_gc, GXcopy);
                                            ^
make[2]: *** [server/shadow/CMakeFiles/freerdp-shadow.dir/X11/x11_shadow.c.o] Error 1
make[1]: *** [server/shadow/CMakeFiles/freerdp-shadow.dir/all] Error 2
make: *** [all] Error 2

**Comment by bmiklautz** [comment]
@rspringer looks like you are building with damage support but it wasn't properly detected/installed. What did you cmake run say?

**Comment by rspringer** [comment]
Thanks for responding so quickly.
This is a clean new Ubuntu install and all I did was installing the dependencies and git clone (all today).
Then cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_Server=ON .
running it again I get this:
 -- FreeRDP GIT
-- Git Revision 358289f
-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Skipping recommended feature Wayland for Wayland (Wayland client)
-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Skipping optional feature OpenSLES for multimedia (OpenSLES audio / video)
--     Enable feature OpenSLES using "-DWITH_OPENSLES=ON"
-- Finding recommended feature OSS for sound (audio input, audio output and multimedia redirection)
--     Disable feature OSS using "-DWITH_OSS=OFF"
-- Found OSS Audio
-- Skipping recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping optional feature Pulse for sound (audio input, audio output and multimedia redirection)
--     Enable feature Pulse using "-DWITH_PULSE=ON"
-- Skipping optional feature Cups for printing (printer device redirection)
--     Enable feature Cups using "-DWITH_CUPS=ON"
-- Skipping optional feature PCSC for smart card (smart card device redirection)
--     Enable feature PCSC using "-DWITH_PCSC=ON"
-- Finding recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Disable feature FFmpeg using "-DWITH_FFMPEG=OFF"
-- Skipping optional feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
--     Enable feature GStreamer_0_10 using "-DWITH_GSTREAMER_0_10=ON"
-- Skipping recommended feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- FreeRDP GIT
-- Skipping recommended feature XKBFile for X11 keyboard (X11 keyboard file extension)
-- FreeRDP GIT
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Finding required feature XShm for X11 shared memory (X11 shared memory extension)
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Skipping recommended feature Xcursor for cursor (X11 cursor extension)
-- Skipping recommended feature Xv for video (X11 video extension)
-- Finding recommended feature Xi for input (X11 input extension)
--     Disable feature Xi using "-DWITH_XI=OFF"
-- Skipping recommended feature Xrender for rendering (X11 render extension)
-- Finding recommended feature Xfixes for X11 xfixes extension (Useful additions to the X11 core protocol)
--     Disable feature Xfixes using "-DWITH_XFIXES=OFF"
-- Finding recommended feature PAM for authentication (user authentication)
--     Disable feature PAM using "-DWITH_PAM=OFF"
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Finding recommended feature XShm for X11 shared memory (X11 shared memory extension)
--     Disable feature XShm using "-DWITH_XSHM=OFF"
-- Finding recommended feature XTest for X11 input event injection (X11 input event injection extension)
--     Disable feature XTest using "-DWITH_XTEST=OFF"
-- Finding recommended feature Xfixes for X11 region (X11 region fix extension)
--     Disable feature Xfixes using "-DWITH_XFIXES=OFF"
-- Warning: Property DESCRIPTION for package Xfixes already set to "Useful additions to the X11 core protocol", overriding it with "X11 region fix extension"
-- Skipping recommended feature XRandR for X11 resize, rotate and reflect (X11 resize, rotate and reflect extension)
-- Skipping recommended feature Xdamage for X11 region damage (X11 region damage extension)
-- Skipping recommended feature Xcursor for cursor (X11 cursor extension)
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rolf/FreeRDP

**Comment by bmiklautz** [comment]
@rspringer if you look at your cmake output you will see that the most "features" are disabled because they are not found. Try to install the following packages:
```
apt-get install  libx11-dev libxrender-dev libxfixes-dev libxdamage-dev libxtst-dev
```

**Comment by rspringer** [comment]
thanks - no chance, still the same compile error
libxrender, libx11, libxdamage were installed, the other ones were up to date 
I have no idea how to link a feature to a missing dependency.....

**Comment by bmiklautz** [comment]
@rspringer intresting. Building it almost everyday with -DWITH_Server=ON and never saw this issue.

**Comment by rspringer** [comment]
OK - solved - classic rookie mistake. RTFM. All required dependencies are documented in https://github.com/awakecoding/FreeRDP-Manuals/blob/master/Developer/FreeRDP-Developer-Manual.markdown (quite a few were missing). Most important: you have to delete the CMake cache file (rm CMakeCache.txt) after installing dependencies (that was the main problem). Thanks for the help - it did contain the clue !
