### ISSUE TITLE
Please re-allow certificates with CN different to hostname to be saved after prompting to the user

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#2776]
I'm trying to connect to some Windows 7 machines via an hostname which is different from the certificate CN. Hostname for the machines are WIN1 and WIN2.
```
# Connect to 1st windows 7 via a public IP
xfreerdp /v:externalip.publicdomain.com:27077 /u:myuser /d:mydomain
# Connect to 2nd windows 7 via a public IP
xfreerdp /v:externalip.publicdomain.com:27078 /u:myuser /d:mydomain``
```
Up to FreeRDP commit 2204DE9 all worked as expected (like Microsoft client does): the first time I connect, to WIN1 and WIN2, xfreerdp complains for invalid certificate hostname, and then prompt the user to save the host:port certificate into ~/.config/freerdp/known_hosts.

Now the connection is refused and the result is:
```
[23:02:57:516] [19754:19755] [ERROR][com.freerdp.crypto] - certificate not trusted, aborting.
[23:02:57:516] [19754:19755] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_CANCELLED [0x2000B]
[23:02:57:516] [19754:19755] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[23:02:57:516] [19754:19755] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
```
Using `/cert-ignore` is a workaround to make FreeRDP connect, but I don't think it's the safest way to make it work.

**Comment by giox069** [comment]
mmm... after deleting host from known_hosts2 it worked, I apologize for opening this issue. I also noticed that remmina and xfreerdp saves different hostnames into know_hosts2, because originally FreeRDP did not saved the port number.
I'm closing this issue now, I will reopen it if necessary.
@antenore

**Comment by akallabeth** [comment]
@giox069 Looks like you fell victim of a little bug of mine, could you check if it works after merging #2774?

**Comment by giox069** [comment]
Hi @akallabeth, thank you for answering.

I did some testing, but I can't understand what's really going wrong.

How to reproduce the problem today: (using the latest FreeRDP, without #2774):

 1. Remove the host you are connecting to from both known_hosts and known_hosts2
 2. Connect to the host with xfreerdp, a new clean entry will be created into known_hosts2
 3. Disconnect
 4. Manually edit known_hosts2, and just change one hex digit of the certificate fingerprint for the host we are connecting. This should emulate a server certificate change.
 5. Retry to connect, and you cannot connect. This is the output.

```
[10:50:46:644] [9374:9375] [ERROR][com.freerdp.crypto] - certificate not trusted, aborting.
[10:50:46:644] [9374:9375] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_CANCELLED [0x2000B]
[10:50:46:644] [9374:9375] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[10:50:46:644] [9374:9375] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
```

Same test after applying PR #2744:

```
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - The host key for myhostname.myhost.com:3389 has changed
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - Someone could be eavesdropping on you right now (man-in-the-middle attack)!
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - It is also possible that a host key has just been changed.
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - The fingerprint for the host key sent by the remote host is29:8a:22:a2:d1:ff:f7:0a:39:78:d8:4b:37:fb:11:8a:e7:d8:1c:30
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - Please contact your system administrator.
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - Add correct host key in /home/giovanni/.config/freerdp/known_hosts2 to get rid of this message.
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - Host key for pfmitsrv01.pfm.it has changed and you have requested strict checking.
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - Host key verification failed.
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.crypto] - certificate not trusted, aborting.
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_CANCELLED [0x2000B]
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[11:17:47:026] [13951:13952] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
```
And still can't connect. I need to manually remove myhostname.myhost.com line from known_host2 to connect again.

**Comment by giox069** [comment]
Edit: I modified the previous post to hide sensitive data (hostname :)).

**Comment by akallabeth** [comment]
@giox069 Pull #2774 fixes an issue where on a changed fingerprint the original entry is not replaced. If you would like to have the client ask to accept the new certificate, you should also have a look at #2710. The second pull changes the callback API and implements the changed certificate callbacks.

**Comment by giox069** [comment]
I tested your personal cert_temp_accept_v2 branch (which should be FreeRDP pull request #2710, I think). Now when I manually change an hex digit on known_hosts2 and try to reconnect, I get the following message and prompt:
```
Certificate details:
	Subject: CN = myhostname.myhost.com
	Issuer: CN = myhostname.myhost.com
	Thumbprint: 29:8a:22:a2:d1:ff:f7:0a:39:78:d8:4b:37:fb:11:8a:e7:d8:1c:30
The above X.509 certificate could not be verified, possibly because you do not have
the CA certificate in your certificate store, or the certificate has expired.
Please look at the documentation on how to create local certificate store for a private CA.
Do you trust the above certificate? (Y/T/N) Y

```
and this is very good.
But now, when I press Y, the myhostname.myhost.com line in known_hosts2 is not overwritten and a new line is added, so the result is
```
# known_hosts2
myhostname.myhost.com 3389 19:8a:22:a2:d1:ff:f7:0a:39:78:d8:4b:37:fb:11:8a:e7:d8:1c:30 ...
myhostname.myhost.com 3389 29:8a:22:a2:d1:ff:f7:0a:39:78:d8:4b:37:fb:11:8a:e7:d8:1c:30 ...
myhostname.myhost.com 3389 29:8a:22:a2:d1:ff:f7:0a:39:78:d8:4b:37:fb:11:8a:e7:d8:1c:30 ...
myhostname.myhost.com 3389 29:8a:22:a2:d1:ff:f7:0a:39:78:d8:4b:37:fb:11:8a:e7:d8:1c:30 ...
```
the last three lines are generated launching xfreerdp and answering "Y". All four lines contains exactly the same base64 encoded text which I removed.

**Comment by bmiklautz** [comment]
@giox069 could you try if the latest master fixes this problem for you?

**Comment by akallabeth** [comment]
@giox069 Pull #2710 does not contain the fixes from #2778 (redone #2774). So, if you rebase #2710 (or merge it to master) it should work.

**Comment by giox069** [comment]
Wonderful ! Pull #2710 merged to master seems to work! I have seen that the certificate notification client API has changed a bit, so I should update also Remmina when you will merge #2710.

Colud you please also help us (remmina developers) in solving the 2nd problem explained here ? https://github.com/FreeRDP/Remmina/issues/604
It's a problem with the port number stored in the known_hosts2 file. When remmina is using an ssh tunnel, it asks to freerdp to connect to the local ssh tunnel port, not the remote server port. So you are storing into known_hosts2 the current ssh port and not the real remote server port. Is there a way in which the client (remmina) can pass you the real server port to store in known_hosts2 ?
Thank you in advance for all.

**Comment by giox069** [comment]
Hi, I can unfortunately see that Pull#2710 has not been merged and cannot longer be merged.

The problem is currently the following:

when an old hostname is left on the old "known_hosts" file, and its certificate changes, xfreerdp refuses to connect with the following misleading error:

```
giovanni@unox:~$ xfreerdp /v:genesi.mydom.lan /v:giovanni /d:mydom
[12:38:28:176] [4691:4692] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: giovanni
[12:38:28:262] [4691:4692] [ERROR][com.freerdp.core] - getaddrinfo: Nome o servizio sconosciuto
[12:38:28:262] [4691:4692] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[12:38:28:262] [4691:4692] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
[12:38:28:262] [4691:4692] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[12:38:28:262] [4691:4692] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
```

The workaround of deleting the host from ~/.config/freerdp/known_hosts works fine.

**Comment by giox069** [comment]
whoops... .wrong cut & paste, will repost in few minutes :-1:

**Comment by giox069** [comment]
The problem is currently the following:

when
1. an old hostname is left on the old "known_hosts" file
AND
2. the same hostname is not in known_hosts2
AND
3. host certifcate has changed

xfreerdp refuses to connect with the following misleading error (ERRCONNECT_CONNECT_CANCELLED):

```
giovanni@unox:~/.config/freerdp$ xfreerdp /v:genesi.mydom.lan /u:giovanni /d:mydom
[12:58:57:800] [10211:10212] [ERROR][com.freerdp.crypto] - certificate not trusted, aborting.
[12:58:57:800] [10211:10212] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_CANCELLED [0x2000B]
[12:58:57:800] [10211:10212] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[12:58:57:801] [10211:10212] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
```

The workaround of deleting the host from ~/.config/freerdp/known_hosts works fine.

**Comment by bmiklautz** [comment]
@giox069 I'd assume this behavior is correct. If the certificate is in one of the known_host files and has changed no connection should be made. The error is on the other hand absolutely miss leading. I'd suggest opening a new issue on this subject.

**Comment by giox069** [comment]
Suppose a user is migrating from freerdp 1.1 (known_hosts based) to 1.2 (known_hosts2 based). He has a lot of expired certs on known_hosts file (like I have): he will not be able to connect to all of these hosts.

Yes, with a better error description and a google search, a user can come here and find to delete the known_hosts file... but it's a bit uncomfortable.

**Comment by bmiklautz** [comment]
@giox069 no doubt that the error is not suitable. But still imho the behavior is correct. If the certificate is invalid/changed/expired (regardless of which known_host file is used) the connection attempt shouldn't get through. Otherwise this would render the known_host file(s) useless. If a newer version lives in known_hosts2 this should be used.

If the certificate is expired it needs to be removed and get accepted on the next connection attempt (like it needs to be done for ssh). If the user doesn't want any certificate handling /cert-ignore still can be used.

**Comment by akallabeth** [comment]
@giox069 For changed certificates there is the ```VerifyChangedCertificate``` callback, which is currently not implemented for ```xfreerdp```.

**Comment by giox069** [comment]
Yes, I was investigating and I came to the same callback. Remmina (and maybe the Android FreeRDP client) use VerifyChangedCertificate callback to alert the user of the changed certificate. And there is no VerifyChangedCertificate call inside xfreerdp sources.
So my tests with xfreerdp are not very useful here.
I will do some other testing with remmina: it seems that when the expired cert is in the older known_hosts, VerifyChangedCertificate is not called. So the remmina user only gets the misleading ERRCONNECT_CONNECT_CANCELLED error and not the correct prompt. But... I have to test it better. I will post results today or tomorrow.
In the meanwhile... thank your for answering and for your support :+1:

**Comment by bmiklautz** [comment]
@giox069 Have a look at https://github.com/FreeRDP/FreeRDP/pull/2710

**Comment by giox069** [comment]
Tested again, and I can reproduce the problem:
when all the following contitions are true
a) the hostname of the server is in ~/config/.freerdp/known_hosts
b) the hostname of the server is not in ~/config/.freerdp/known_hosts2
c) the key in known_host has been changed

VerifyChangedCertificate callback is not called and libfreerdp retunrns ERRCONNECT_CONNECT_CANCELLED

PR #2710 does not help.

**Comment by giox069** [comment]
The 1st half of the problem is at line193 of libfreerdp/crypto/certificate.c
```
match = strcmp(pline, certificate_data->fingerprint);
```
should be fixed with
```
match = (strcmp(pline, certificate_data->fingerprint) == 0) ? 0 : -1;
```
but it's not enough...

**Comment by giox069** [comment]
The second part is that certificate_data_replace() in ./libfreerdp/crypto/certificate.c is unable to add a new certificate line at the end of know_hosts2 when the hostname is missing from known_hosts2 (because it was on known_hosts).
Should I try to do a pull request ?

**Comment by antenore** [comment]
On 09/11/2015 09:21 PM, Giovanni Panozzo wrote:
>
> The second part is that certificate_data_replace() in 
> ./libfreerdp/crypto/certificate.c is unable to add a new certificate 
> line at the end of know_hosts2 when the hostname is missing from 
> known_hosts2 (because it was on known_hosts).
> Should I try to do a pull request ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/FreeRDP/FreeRDP/issues/2776#issuecomment-139637509>.
>
Ti serve una mano (tecnica, politica, mediatica, ...) ?

**Comment by giox069** [comment]
Mah. Vediamo cosa dicono. Ho già preparato la fix nel mio repo giox069/FreeRDP, sono 4 righe. Se mi chiedono la pull request, si tratta di premere un bottone.

Scusa ma non sono riuscito a testare la tua roba ssh. Mi sembra che hai fatto già il merge, bene. Testerò semplicemente... usandolo ! :) (non prima di domani)


Il 11 settembre 2015 22:33:31 CEST, Antenore Gatta <notifications@github.com> ha scritto:
>On 09/11/2015 09:21 PM, Giovanni Panozzo wrote:
>>
>> The second part is that certificate_data_replace() in 
>> ./libfreerdp/crypto/certificate.c is unable to add a new certificate 
>> line at the end of know_hosts2 when the hostname is missing from 
>> known_hosts2 (because it was on known_hosts).
>> Should I try to do a pull request ?
>>
>> —
>> Reply to this email directly or view it on GitHub 
>>
><https://github.com/FreeRDP/FreeRDP/issues/2776#issuecomment-139637509>.
>>
>Ti serve una mano (tecnica, politica, mediatica, ...) ?
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/FreeRDP/FreeRDP/issues/2776#issuecomment-139655429

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by antenore** [comment]
On 09/11/2015 11:39 PM, Giovanni Panozzo wrote:
>
> Mah. Vediamo cosa dicono. Ho già preparato la fix nel mio repo 
> giox069/FreeRDP, sono 4 righe. Se mi chiedono la pull request, si 
> tratta di premere un bottone.
>
> Scusa ma non sono riuscito a testare la tua roba ssh. Mi sembra che 
> hai fatto già il merge, bene. Testerò semplicemente... usandolo ! :) 
> (non prima di domani)
Non ho fatto il merge... troppo rischioso.

Meglio cosi, sto cercando di aggiungere l'autenticazione vi 
ssh_userauth_agent. Sperando che funzioni perché ho sonno.

**Comment by akallabeth** [comment]
@giox069 No need for that, updated the pull with a fix for your issues.

**Comment by giox069** [comment]
Ok thank you.
Please check your new certificate.c at line 476 you added a "goto end;" inside the loop which rewrites the full known_hosts2. Will this leave known_hosts2 incomplete and delete all certificates store after the line to replace ?

**Comment by akallabeth** [comment]
@giox069 Thx, did break that part. Updated with a new commit, should work now.

**Comment by akallabeth** [comment]
Should be resolved, closing.
If you re encounter the issue, please let me know.
