### ISSUE TITLE
Smart Card redirection on OS X 10.8.5 to Windows Server 2012 R2

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#2780]
One of my customers reported an issue to me with smart card redirection on OS X 10.8.5 connecting to Windows Server 2012 R2, while it works fine against Windows Server 2008 R2.

Here are the last few lines from the log (read from bottom to top):

```
fatal_handler: signum=11
fmszReaderNamesIsNULL: 0 cchReaderLen: -1 cbAtrLen: 0
hCard: 0x06A4020000000000 (8)
hContext: 0x0C610301FFFFFFFF (8)
StatusW_Call {
SCardStatusW (0x000900CC) FileId: 1 CompletionId: 1
}
[0]: cbAtr: 26 rgbAtr: 3BDF960081B1FE451F838073CC91CBF9A0000003080000100079
[0]: dwEventState: SCARD_STATE_CHANGED | SCARD_STATE_PRESENT | SCARD_STATE_INUSE (0x00000122)
[0]: dwCurrentState: SCARD_STATE_UNAWARE (0x00000000)
cReaders: 1
ReturnCode: SCARD_S_SUCCESS (0x00000000)
GetStatusChangeW_Return {
}
[0]: dwEventState: SCARD_STATE_UNAWARE (0x00000000)
[0]: dwCurrentState: SCARD_STATE_UNAWARE (0x00000000)
[0]: szReader: SCM SCR 355 0 cbAtr: 0
dwTimeOut: 0x00000000 cReaders: 1
hContext: 0x0C610301FFFFFFFF (8)
GetStatusChangeW_Call {
SCardGetStatusChangeW (0x000900A4) FileId: 1 CompletionId: 1
}
cbAtrLen: 26 pbAtr: 3BDF960081B1FE451F838073CC91CBF9A0000003080000100079
cBytes: 30 mszReaderNames: SCM SCR 355 0
dwState: SCARD_SPECIFIC (0x00000006) dwProtocol: SCARD_PROTOCOL_T1 (0x00000002)
ReturnCode: SCARD_S_SUCCESS (0x00000000)
```

This is the chain of events:
1) The RDP connection is established and the dark blue Windows screen displaying the
company's standard "monitoring" banner message with an OK button shows up. Windows 
2012 R2 is shown at the bottom.
2) When the OK button of the banner is clicked, the RDP session terminates.

Any idea what's going on here?

**Update**: Multiple customers now reported this issue to me and they all seem to have a Banner Message/Security Warning at the Windows Logon dialog. It doesn't seem to be related to a specific Windows version.

**Comment by frazier-evans** [comment]
I am seeing the same thing when using Windows 2008 R2.  It could be the "Monitoring" message not being handled properly.  Unfortunately I do not have a server I can test this idea with.

**Comment by sconstantine** [comment]
Any progress or updates to smart card redirection?

**Comment by bmiklautz** [comment]
Should be fixed on master now. If you still see this issue please re-open or recreate a new one.
