### ISSUE TITLE
Connection to Windows Server 2012 without password failed

### ISSUE THREAD

**Issue by rchovan** [FreeRDP/FreeRDP#2783]
Hi, 
I can't connect from Linux or Windows with xfreerdp or wfreerdp client to Windows Server 2012 with users without password:
`````
xfreerdp /v:server2012 /u:manager /p:
Password: 
[08:14:34:920] [2824:2825] [ERROR][com.winpr.utils] - Could not open SAM file!
[08:14:34:920] [2824:2825] [ERROR][com.winpr.utils] - Could not open SAM file!
[08:14:35:930] [2824:2825] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[08:14:35:930] [2824:2825] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
`````
Connection with different username + passwod does work
`````
xfreerdp /v:server2012 /u:username /p:password
[08:16:26:993] [3381:3382] [WARN][com.freerdp.client.x11] - Server does not support XI 2.2
[08:16:26:996] [3381:3382] [ERROR][com.freerdp.client.x11] - Error loading X Fixes extension
[08:18:26:617] [3381:3382] [ERROR][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
[08:18:26:618] [3381:3382] [ERROR][com.freerdp.core.rdp] - DisconnectProviderUltimatum: reason: 3
`````

xfreerdp downloaded from GitHub today and compiled from source
`````
xfreerdp --version
This is FreeRDP version 1.2.4-dev (git c12bc0e)
`````

**Comment by bmiklautz** [comment]
@rchovan did this work before? As far as I know you need to have extra policy settings to allow empty passwords on 2012.

**Comment by rchovan** [comment]
Hi, I don't know if it work before, because we switched from older Windows
version. Do you have any other info/link about policy?

Thank you

Dňa pi, 17. júl 2015 12:55 Bernhard Miklautz <notifications@github.com>
napísal(a):

**Comment by HenryJacques** [comment]
@rchovan See here https://technet.microsoft.com/en-us/library/cc956966.aspx and https://technet.microsoft.com/en-us/library/cc956977.aspx

**Comment by bmiklautz** [comment]
@HenryJacques thanks.
@rchovan easiest is to quickly test with mstsc and see if it works without password in general.

**Comment by rchovan** [comment]
Hi, 
I think, that all is in GPO enabled, because I can login localy without password, and I can connect with mstsc.exe without password. Where shoudl I look for problem ? 
@HenryJacques , @bmiklautz

**Comment by bmiklautz** [comment]
@rchovan if it does work with mstsc then it's looks definitely like a FreeRDP bug.

**Comment by lemonmojo** [comment]
I ran into the same issue today and can confirm that passwordless logins with NLA seem to be unsupported by FreeRDP at the moment. It's possible to work around this with /sec:rdp if the remote host is configured to allow non-NLA connections though.

**Comment by realjiangms** [comment]
I ran into same issue with Win7 as server which is configured as allow empty password. The non-NLA sec works. However it is definitely a regression as the freerdp 1.0.1 - 1.0.2 don't have this issue.
It seems stable-1.1 also have this issue. 

I can understand that it try to find password in SAM if a password is not specified, but it doesn't make sense to try to access SAM file if an empty password is specified explicitly. 

When I touch an empty SAM file /etc/winpr/SAM, it still try to find the user and report entry not found:

[02:11:58:375] [23120:23121] [ERROR][com.winpr.sspi.NTLM] - Error: Could not find user in SAM database


Some related issue reported
#1350 #2907 #1591 #1936

**Comment by realjiangms** [comment]
It works after running winpr-hash with empty password.
winpr/tools/hash/winpr-hash -f sam -u <username> -p '' -v 1 > /etc/winpr/SAM

However it doesn't make sense as I've already specified the empty password in command line:
xfreerdp /cert-ignore /u:<username> /p:'' /v:<server ip>
