### ISSUE TITLE
Windows XP display issue on Android and iOS client

### ISSUE THREAD

**Issue by mchozhang** [FreeRDP/FreeRDP#2787]
I am trying to connect to a windows XP remote desktop on Android and iOS client.
I guess I compile the FreeRDP successfully and use iFreeRDP and aFreeRDP code as library.
Everything is fine when connect to windows 7, but it displays oddly when connect to windows XP.

![2015-07-16 3 42 09](https://cloud.githubusercontent.com/assets/8019025/8717826/626392a0-2bd1-11e5-8879-6f935ea996a0.png)

This is what it displays on ipad simulator when connect to windows XP(the same on ipad or android device), the screen is just stuck there,only the tool bar can work.

I also tried use old version and newest version FreeRDP, and used them on Android and iOS client ,but they display all the same.
I uesd openssl 1.0.2d and cmake2.8-9, iOS sdk 8.2.

Do anyone has the same issue or has ideas what may cause this?
I can't figure out where the problem is since window 7 works fine.

P.S.  I connect to some other XP desktops successfully this morning, but still failed to connect to an XP VM

**Comment by bmiklautz** [comment]
@mchozhang what SP of XP are you using?

**Comment by wangfuda** [comment]
@mchozhang when i try to porting the iFreeRDP to my app, i meet too many error.
can you give me some experience for that?
thanks for anvance.

**Comment by akallabeth** [comment]
More or less rewritten in current master.
Reopen if still an issue.
