### ISSUE TITLE
Black screen with some colored noize when connected to VirtualBox RDP from linux machine

### ISSUE THREAD

**Issue by imShara** [FreeRDP/FreeRDP#2792]
![955459052-hgqirhbevariztprjyalnbgggswivhfy](https://cloud.githubusercontent.com/assets/4913196/8754005/e3cd47da-2cc8-11e5-82c9-f0e504194829.png)

But remote control works. How to fix this?

**Comment by bmiklautz** [comment]
@imShara can you give us more details? - FreeRDP version, VirtualBox Version. Please also add the command line you are using.

**Comment by imShara** [comment]
@bmiklautz, of course

```bash
xfreerdp /version
This is FreeRDP version 1.2.0-beta1 (git n/a)

virtualbox --help
Oracle VM VirtualBox Manager 4.3.28_OSE

xfreerdp /v:127.0.0.1:3389
```

**Comment by akallabeth** [comment]
still an issue?

**Comment by akallabeth** [comment]
Closing, no feedback.

**Comment by imShara** [comment]
Wow. Necropost. I forgot about this
