### ISSUE TITLE
VMware Windows7 VMs disconnecting 

### ISSUE THREAD

**Issue by nascarqwazy** [FreeRDP/FreeRDP#2795]
We have had all the users that have Windows 7 VMs have an issue with their VMs disconnecting various times throughout the day.  The following error is displayed:

ERRINFO_RPC_INITIATED_DISCONNECT (0x00000001)
The disconnection was initiated by an administrative tool on the server in another session.

We have tried the few things that we've seen that we Googled, but none of them have seemed to fix the issue.

**Comment by bmiklautz** [comment]
@nascarqwazy what FreeRDP version are you using and what command line with xfreerdp?

**Comment by nascarqwazy** [comment]
We're using 1.0.2-1, even moved up to 1.0.2-2.

We are using this command:
xfreerdp  -g 1900x1150 --no-nla -a 24 -T VM --plugin cliprdr --plugin rdpsnd --data rdpsnd_pulse.so 1.2.3.4

I even went back to my command I used before and it still happens:
xfreerdp --plugin cliprdr --no-nla -a 32 -g 1900x1150 -d <domain> -u <user> 1.2.3.4

**Comment by bmiklautz** [comment]
@nascarqwazy may I ask what distribution you are using?

**Comment by nascarqwazy** [comment]
Do you mean the version of freerdp?  I put it in there, 1.0.2-1 and have tried 1.0.2-2 on one system.

**Comment by bmiklautz** [comment]
@nascarqwazy Linux distribution like Debian/Ubuntu...

**Comment by nascarqwazy** [comment]
Ahhh, RedHat 6u3

**Comment by lmeinecke** [comment]
I see this issue is 2yrs old but was it ever fixed? Our native RHEL 6.x hosts disconnect to our Win7 VMs with this error pretty frequently.  

Using freerdp-1.0.2-5

**Comment by bmiklautz** [comment]
@lmeinecke I think it's already fixed on master. 1.0.2 is pretty old.

**Comment by lmeinecke** [comment]
This version is the newest available from RHEL. I can only use RPMs from RHEL channels in my environment. Anyone know how to promote getting newer freerdp builds into there?

On Jul 4, 2017, at 07:15, Bernhard Miklautz <notifications@github.com<mailto:notifications@github.com>> wrote:


@lmeinecke<https://github.com/lmeinecke> I think it's already fixed on master. 1.0.2 is pretty old.

-
