### ISSUE TITLE
mouse cursor 'skipping back' problem

### ISSUE THREAD

**Issue by psumbera** [FreeRDP/FreeRDP#2796]
While using both server and client I see on client following issue. When moving move from one side of screen to another it looks like it's skipping back.

The 'skipping back' problem could always be reproduced in poor network environment.

The problem disappear when I comment out the only call to x11_shadow_pointer_position_update in server/shadow/X11/x11_shadow.c (the server side mouse position would never be sent to client side).

We should have enhancement that the server should not send back the mouse position to the client where user is moving the cursor.

I think the idea to update the mouse position to clients is to notify the clients which are just 'observers'. In multi-client scenario, usually there should be only one 'operator' who is move the mouse or click it. We only need to update the mouse position to the 'observers'.

**Comment by realjiangms** [comment]
Thanks @psumbera 
I'll create a PR when I finish the fix

**Comment by realjiangms** [comment]
Almost a year later, I start to implement a fix. Sorry for late.
The problem could be easily reproduced on client-server where ping reply time > 200ms

**Comment by realjiangms** [comment]
@psumbera I just checked in fix for this issue. Can we close it?

**Comment by bmiklautz** [comment]
Should be fixed on master but no feedback for a while. Closing this issue. Please re-open or create a new one if the problem still exists for you.
