### ISSUE TITLE
client exclusive server mode

### ISSUE THREAD

**Issue by psumbera** [FreeRDP/FreeRDP#2797]
It would be nice to have mode where just one client is connected. Something what does VNC. When I connect from another place, my original client session is terminated. It's kind of security feature.

**Comment by bmiklautz** [comment]
@psumbera please give more details.

**Comment by psumbera** [comment]
My use case is like this. At office I connect to my desktop session. When I go home I leave it on with just screen lock running in the desktop session. At home I might decide to continue in work. The problem is that the client at work is still active...

**Comment by bmiklautz** [comment]
@psumbera just to clarify you are talking about freerds-shadow?

**Comment by psumbera** [comment]
Yes. freerdp-shadow.

**Comment by hardening** [comment]
This had been implemented recently, closing.
