### ISSUE TITLE
xfreerdp does not work in zsh

### ISSUE THREAD

**Issue by janhieber** [FreeRDP/FreeRDP#2800]
xfreerdp shows me only the help informations when i start it from zsh.
In bash its working fine.

system: Arch Linux x64
freerdp 1.2.0-beta1 (git n/a)
zsh 5.0.8-1 with oh-my-zsh
CMD: xfreerdp /admin /u:user1 /d:domain1 /v:server1

Even "xfreerdp /version" is not working in zsh. Something seems to be wrong with the command line.

**Comment by bmiklautz** [comment]
I'm using zsh myself (without oh-my-zsh) and never had any problems with it:

```
$ echo $ZSH_VERSION
4.3.17
$ freerdp-nightly /version
This is FreeRDP version 1.2.4-dev (git n/a)
```
@janhieber did you already try with a "plain" zsh without oh-my-zsh? Maybe there is some problem in your configuration with the / try using -- instead for testing..

**Comment by janhieber** [comment]
Hi.
Sorry, did not try plain zsh because in bash it works. I think this can be closed.
if you still want to investiage further why its not working in my zsh, i can do more testing, let me know.

Best regards
Jan
