### ISSUE TITLE
the sound and video are not synchronized

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#2803]
Hello, 
 Have strange issue, every time if xfreerdp write to console message 
 ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred 
 audio latency increase,After a few minutes, the sound and video are not synchronized

How this fix?

Connect option 
./xfreerdp  /f /sound:sys:alsa /microphone:sys:alsa /rfx  +async-input  +async-update /u:xxx /p:xxx  /v:xxx

**Comment by akallabeth** [comment]
basically too slow to play back the remote stream.
