### ISSUE TITLE
ifreerdp crash and found that the struct 'PCtxtHandle' was null when run in arm64 phone(ok in armv7)

### ISSUE THREAD

**Issue by wangfuda** [FreeRDP/FreeRDP#2805]
the ifreerdp run normal in armv7,such as iphone 5c,iphone 5, but crash when run in arm64,such as iphone 5s, iphone 6p.
and I found the crash cause by pointer's address is null, now show the crash code:
![v t nsw xi l3nfi 04gh2](https://cloud.githubusercontent.com/assets/3206178/8905684/e94c7ee0-349a-11e5-82a7-e37b48c4d3d9.jpg)

I follow the func stack and the code,found the null pointer's address cause by the null struct 'PCtxtHandle'

Thanks for advance

**Comment by bmiklautz** [comment]
@wangfuda although arm64 is out there for quite some time the FreeRDP iOS port still doesn't officially support it.  Please have a look to issue #2685

**Comment by wangfuda** [comment]
why the version of ifreeRDP(iOS) in offical web site (http://www.freerdp.com/) can run normal in arm64 such as iphone 5s, iphone 6p?
