### ISSUE TITLE
+gfx-h264 Error, Fail to create h264 codec context

### ISSUE THREAD

**Issue by gareks** [FreeRDP/FreeRDP#2806]
I currently using latest master 1.2.4.dev and I'm not able to use +gfx-h264
The screen became crappy and on the console:
ERROR com.freerdp.core.codecs - Failed to create h264 codec context.

Please help

**Comment by bmiklautz** [comment]
@gareks in order to use h264 you need the openh264 library (https://github.com/cisco/openh264) during compile and runtime. At the moment it is possible to build without libopenh264 and still have the command line option available. In this case the error you are describing is reported.

**Comment by gareks** [comment]
Could you please give me some hints the steps on getting the openh264 work with freerdp?
How to compile openh264 and which commend to be use during freerdp compile?

**Comment by bmiklautz** [comment]
Compile libopenh264 and install it for example in /opt/h264 (or whatever you prefer).
When you configure FreeRDP add the cmake parameter -DWITH_OPENH264=ON. In order to make cmake find the library you might need to also set a search path for cmake like -DCMAKE_PREFIX_PATH=/opt/h264

**Comment by wentao786** [comment]
when i set /gfx-h264 and /gfx , client can't fetch H264 data , could you tell me why? thank you

**Comment by wentao786** [comment]
server is windows server 2008 R2,please help me ,this problem has trouble me very much

**Comment by hardening** [comment]
@wentao786 this bug is closed, if you have some troubles please start by inquiring yourself, and if the bug is still there => https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
