### ISSUE TITLE
Slow mouse or keyboard input with +gfx during YouTube playback

### ISSUE THREAD

**Issue by gareks** [FreeRDP/FreeRDP#2807]
I found that when the option +gfx is on.
Mouse and keyboard input getting slow during YouTube playback.
But there's no error show on console
Version is 1.2.4.dev

**Comment by bmiklautz** [comment]
@gareks per default FreeRDP handles input and gfx in one thread which might have the effect that input processing is "slower".  Can you try if the options  +async-input +async-update (maybe also +async-channels and +async-channels) improve that problem?

**Comment by RexFan** [comment]
@bmiklautz I work with @gareks . I have tried +async parameters but it doesn't help. Any other suggestions? The command we use is xfreerdp -sec-nla /cert-ignore /u: /f /drive:*,hotplug /network:modem /rfx /gfx +gfx-h264 +gfx-thin-client -offscreen-cache +fonts /v:192.168.0.1. Please advise. Thanks.

**Comment by akallabeth** [comment]
#3364 addresses input starvation.
