### ISSUE TITLE
Support for Remote Desktop Gateway PAA

### ISSUE THREAD

**Issue by rassie** [FreeRDP/FreeRDP#2808]
There is something called [Remote Desktop Gateway Pluggable Authentication and Authorization](https://code.msdn.microsoft.com/windowsdesktop/Remote-Desktop-Gateway-517d6273), which seems to be unsupported by FreeRDP, but becomes more common. In my case, our private cloud provider uses Azure Pack, which is like Azure Cloud but on-premise, and has PAA enabled, which leads to the following `.rdp` files (slighly redacted, access tokens removed):

```
full address:s:hv01.provider.net
gatewaycredentialssource:i:5
gatewayprofileusagemethod:i:1
endpointfedauth:s:XXXXXXXXXXXXXXXXXXXXX.....
pcb:s:0DB667C1-712E-401B-B5AE-47C76A7FC955
server port:i:2179
gatewayusagemethod:i:2
gatewayhostname:s:gateway.provider.net
gatewayaccesstoken:s:XXXXXXXXXXXXXXXXXXXXX.....
enablecredsspsupport:i:0
userdstls:i:1

```

Any chance that this will be supported in near future?

**Comment by bmiklautz** [comment]
@rassie there are no plans on that as far as I know.

**Comment by Hopedream** [comment]
I have tried many versions of the code, and found that the code is all in support of March 26, 2015, after that, until now are not supported, I do not know what is the reason

![1](https://cloud.githubusercontent.com/assets/13480468/9455962/e5e0bca6-4b03-11e5-8430-83023222f997.jpg)

**Comment by akallabeth** [comment]
@Hopedream So, ```29e2b1f763c01bbf05edeadc86bc581d3e2ff384``` is the last commit working for you and ```aa2181dcf2dd98693767ba738c5b2ad8c3d742d4``` the first one broken?

**Comment by Hopedream** [comment]
yes !

**Comment by Hopedream** [comment]
@akallabeth  Yes !!!

**Comment by akallabeth** [comment]
@Hopedream Are you sure? The diff only shows changes in error code to string conversions (only used for debug output). Maybe you could post the output of a connection attempt with ```WLOG_LEVEL=trace``` set to get more detailed error information.

**Comment by bmiklautz** [comment]
@Hopedream how is you list related to this initial issue "Support for Remote Desktop Gateway PAA"? 
And can you give more details on how you are testing..

**Comment by Hopedream** [comment]
@akallabeth  Ok,I will test again with  WLOG_LEVEL=trace now .

**Comment by Hopedream** [comment]
@bmiklautz I just test the connection through gateway whether it can be sucessed .

**Comment by bmiklautz** [comment]
@Hopedream so your problem is rather a new issue than related to this one, or?

**Comment by Hopedream** [comment]
@bmiklautz  yes,I'm sorry. I think I'm wrong,my problem is that the gateway connection failed

**Comment by Hopedream** [comment]
@akallabeth How to uses this parameter WLOG_LEVEL=trace ?

**Comment by bmiklautz** [comment]
@Hopedream please open a new issue on your problem.

**Comment by Hopedream** [comment]
@bmiklautz  I have done,but no ones browing .[my problem](https://github.com/FreeRDP/FreeRDP/issues/2834)

**Comment by akallabeth** [comment]
There have been additions, is this fixed now?

**Comment by p-pautov** [comment]
@akallabeth Yes, FreeRDP now supports "gatewayaccesstoken" RDP file property (aka PAA).
