### ISSUE TITLE
CMAKE commend and required lib for 1.2.4

### ISSUE THREAD

**Issue by gareks** [FreeRDP/FreeRDP#2809]
Could you guys give us (noob) some hints on which CMAKE option and required lib is necessary to run 1.2.4?
Many Thanks

**Comment by bmiklautz** [comment]
@gareks if you just run cmake without any options you will get an error if something required for basic operation is missing. The exact requirements are depending on the distribution and on the features you want to enable. A basic overview about compilation can be found at https://github.com/FreeRDP/FreeRDP/wiki/Compilation (although possibly a little outdated).

If you have further questions please don't use the issue tracker but the mailing list or our irc channel instead. Thank you.
