### ISSUE TITLE
option /cert-ignore not working anymore

### ISSUE THREAD

**Issue by BUGgs** [FreeRDP/FreeRDP#2810]
On today master, the option /cert-ignore seems to not be applied, the mismatche certificate is always prompted to be accepted or refused...

**Comment by bmiklautz** [comment]
@BUGgs can you add more information or a test case for you problem?
I just tried to reproduce this with master without success. My simple command line was
```
xfreerdp /v:testhost /cert-ignore
```
When I added /cert-ignore I wasn't prompted for the certificate (on a new connection) and when I changed the fingerprint in ~/.config/freerdp/known_hosts2 to not match the hosts fingerprint it worked as well. I also tried different combinations of ~/.config/freerdp/known_hosts2  and ~/.config/freerdp/known_hosts.

**Comment by BUGgs** [comment]
It seems that the issue is with .rdp files, like:
xfreerdp myfile.rdp /cert-ignore

**Comment by HenryJacques** [comment]
With latest master, using rdp file, xfreerdp doesn't warn me about the certificate, *never* (with or without /cert-ignore). And yes I don't have already the fingerprint in ~/.config/freerdp/

**Comment by HenryJacques** [comment]
@bmiklautz I confirm this issue with latest master and yes it only happens with rdp files that have `authentication level:i:[1|2]` (see #3199)

**Comment by akallabeth** [comment]
Closing as duplicate, #3199 has a better description.
