### ISSUE TITLE
Send unicode not working.

### ISSUE THREAD

**Issue by c64cosmin** [FreeRDP/FreeRDP#2812]
I have a problem with the API call freerdp_input_send_unicode_keyboard_event(...);

I'm using it as so
freerdp_input_send_unicode_keyboard_event(rdpInput, KBD_FLAGS_DOWN, 49);
freerdp_input_send_unicode_keyboard_event(rdpInput, KBD_FLAGS_RELEASE, 49);

I should get a '1' character on the other side, but I'm getting a 'n' character instead.
49 is the unicode for '1' character.
Looking up on the scancodes, 49 is the [N] key, so as far as I can see, the unicode function call is actually doing a regular scancode keyboard event.

I'm using the stable-1.1 branch.

I also tried the why documented here : https://github.com/awakecoding/FreeRDP-Manuals/blob/master/Developer/FreeRDP-Developer-Manual.markdown
of using 0 instead of KBD_FLAGS_DOWN, still have the same result.

**Comment by bmiklautz** [comment]
@c64cosmin where do you use it like that? freerdp_input_send_unicode_keyboard_event doesn't do any conversions and sends it directly out to the server.
Did you try with specifying the hex code?

**Comment by bmiklautz** [comment]
I've just tested with master as well as with stable-1.1 when calling the exact code from above
```
freerdp_input_send_unicode_keyboard_event(rdpInput, KBD_FLAGS_DOWN, 49);
freerdp_input_send_unicode_keyboard_event(rdpInput, KBD_FLAGS_RELEASE, 49);
```

I get 1 on the server side. Tested with a notepad on Windows 7.

**Comment by c64cosmin** [comment]
I use it with Hyper-V on a Windows Server VM and a Ubuntu VM, both of them have the same result. Could it be that the Hyper-V is doing something to the RDP event request?

**Comment by c64cosmin** [comment]
I've did a test using a bare-metal machine and seems to work fine. Apparently this is not a issue with freeRDP but it's a Hyper-V issue.

**Comment by hardening** [comment]
IIRC there's a capability stating if the server supports unicode input, is it set with Hyper-V ?

**Comment by bmiklautz** [comment]
@hardening very good point. However FreeRDP doesn't use/evaluate this client side at the moment.
@c64cosmin If you add the following to your code you will see if unicode is generally supported. If so and you still have issues with Hyper-V that might really be a problem there then ;(.
```
diff --git a/libfreerdp/core/capabilities.c b/libfreerdp/core/capabilities.c
index 5f507e3..6539e09 100644
--- a/libfreerdp/core/capabilities.c
+++ b/libfreerdp/core/capabilities.c
@@ -1241,6 +1241,8 @@ BOOL rdp_read_input_capability_set(wStream* s, UINT16 length, rdpSettings* setti
                        /* server does not support fastpath input */
                        settings->FastPathInput = FALSE;
                }
+               if (inputFlags &  INPUT_FLAG_UNICODE)
+                       printf("Unicode support\n");
        }
        return TRUE;
 }

```

**Comment by c64cosmin** [comment]
@bmiklautz Thanks a lot.

Apparently this is a issue just with the Linux VMs. Thanks people, this helped a lot, the issue can be closed.

**Comment by bmiklautz** [comment]
@c64cosmin just out of interest you only have problems if linux installed in a Hyper-V?

**Comment by c64cosmin** [comment]
@bmiklautz Yes, sending unicode behaves as described above.

**Comment by bmiklautz** [comment]
@c64cosmin and does Hyper-V report back that it supports unicode?
