### ISSUE TITLE
Unused variable in RegQueryValueExA()

### ISSUE THREAD

**Issue by HenryJacques** [FreeRDP/FreeRDP#2826]
Hi,

I didn't want to pull a unjustified request for that, but I don't think the **reg** variable in *winpr/libwinpr/registry/registry.c* is of any utility because it is not used in the rest of the function any more

```
LONG RegQueryValueExA(HKEY hKey, LPCSTR lpValueName, LPDWORD lpReserved, LPDWORD lpType, LPBYTE lpData, LPDWORD lpcbData)
{
       Reg* reg;
       RegKey* key;
       RegVal* pValue;

       key = (RegKey*) hKey;
       reg = RegGetInstance();

       pValue = key->values;
       [...]
}
```

Bye

**Comment by bmiklautz** [comment]
@HenryJacques pull requests are always welcome.

**Comment by HenryJacques** [comment]
all right ;)

**Comment by HenryJacques** [comment]
PR #2827
