### ISSUE TITLE
TLS 1.2

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#2828]
I'm currently trying to get a TLS 1.2 only connection working using FreeRDP.
The target machine is Windows Server 2012 R2 Core and I've deselected TLS 1.0 and TLS 1.1 using IIS Crypto (https://www.nartac.com/Products/IISCrypto).

I'm able to connect from a Windows 8.1 box using mstsc and I've verified that TLS 1.2 is indeed being used by enabling Schannel logging on the target machine (https://support.microsoft.com/en-us/kb/260729).

Unfortunately, I can't say the same about FreeRDP. Just compiled master with OpenSSL 1.0.2d (also tried 1.0.2a) and here's the output I get when trying to connect: https://gist.github.com/lemonmojo/a6f7f3b7680555b2bd1a

On the server there are no Schannel related event entries so it seems to fail early on.

**Comment by dbungert** [comment]
Hey Lemonmojo,

A small tweak to libfreerdp/crypto/tls.c should do it.
You could do this to force it to 1.2

    diff --git a/libfreerdp/crypto/tls.c b/libfreerdp/crypto/tls.c
    index b33bb51..91a4330 100644
    --- a/libfreerdp/crypto/tls.c
    +++ b/libfreerdp/crypto/tls.c
    @@ -753,7 +753,7 @@ int tls_connect(rdpTls* tls, BIO* underlying)
             */
            options |= SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS;
    
    -       if (!tls_prepare(tls, underlying, TLSv1_client_method(), options, TRUE))
    +       if (!tls_prepare(tls, underlying, TLSv1_2_client_method(), options, TRUE))
                    return FALSE;
    
            return tls_do_handshake(tls, TRUE);`

Or this should let it negotiate TLS version.

    diff --git a/libfreerdp/crypto/tls.c b/libfreerdp/crypto/tls.c
    index b33bb51..760dc54 100644
    --- a/libfreerdp/crypto/tls.c
    +++ b/libfreerdp/crypto/tls.c
    @@ -753,7 +753,7 @@ int tls_connect(rdpTls* tls, BIO* underlying)
             */
            options |= SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS;
    
    -       if (!tls_prepare(tls, underlying, TLSv1_client_method(), options, TRUE))
    +       if (!tls_prepare(tls, underlying, TLS_client_method(), options, TRUE))
                    return FALSE;
    
            return tls_do_handshake(tls, TRUE);

**Comment by lemonmojo** [comment]
@dbungert: First of all, thanks for the pointers!

I can confirm that using the first version (forcing TLS 1.2) does indeed work, but obviously kills compatibility with all other TLS versions (most RDP servers).

So I'd like to get the second variant (negotiate TLS version) going.
I'm having issues with the linker however. It seems like the `TLS_client_method` method is newer than the current OpenSSL release (1.0.2d).

Did you verify that this compiles using the latest OpenSSL release or did/do you use an OpenSSL version compiled from the current source?

**Comment by dbungert** [comment]
@lemonmojo I should have clarified that this was pure speculation on my part, that I didn't actually compile either variant.  :smile: You may well need to adjust the one in schannel_openssl_client_init as well.

So while this document references TLS_client_method https://www.openssl.org/docs/ssl/TLSv1_server_method.html, that also fails to compile for me.  I think your best bet for now is to force 1.2 until someone figures out what is happening with the negotiate client method.

**Comment by dbungert** [comment]
"TLS_server_method and TLS_client_method were introduced in OpenSSL 1.1.0."

OK, there's your answer.  Upgrade to OpenSSL 1.1.0 or for TLS1.2.

**Comment by lemonmojo** [comment]
@dbungert Bummer! Since I need this for my clients who need to be able to connect to all kinds of RDP servers It's not feasible to compile for TLS 1.2 only.
But I'll give 1.1.0 a shot! If I can get it to compile on OS X, that is... ;)

Thx for looking into this and all the pointers!

**Comment by lemonmojo** [comment]
FYI: Just successfully compiled OpenSSL 1.1.0. Unfortunately there are lots of linker errors when compiling FreeRDP against it. Looks like the OpenSSL guys removed a lot of previously deprecated functions which are still in use by FreeRDP.

The only other feasible option for me would be to make this a user-configurable setting (Force TLS Version 1.0, 1.1 or 1.2). But obviously this would only be kind of a band-aid.

Any future-proof option in sight from your point of view?

**Comment by bmiklautz** [comment]
@lemonmojo the warning should only appear when compiling on OS X with the version they ship. or?

**Comment by lemonmojo** [comment]
@bmiklautz Not sure which warnings and which version you're referring to...
I've previously used a pre-compiled OpenSSL through MacPorts (version 1.0.2d and 1.0.2a) which works perfectly fine, just not with TLS 1.2.

Then I compiled the current development snapshot of OpenSSL 1.1.0 to get the TLS negotiation feature as suggested by @dbungert. The OpenSSL build is fine, but compiling FreeRDP against this OpenSSL version results in a lot of errors since many of previously deprecated functions have now been removed.

So I guess to be future-ready, those function calls will have to be replaced with new versions, otherwise FreeRDP won't be compatible with new OpenSSL versions.
There might be a way to re-enable those deprecated functions when compiling OpenSSL from source but this, again, would be kind of a band-aid and can't be expected from users of FreeRDP.

**Comment by zonywhoop** [comment]
@lemonmojo @dbungert Just my .02 as this problem is affecting us as well, PCI DSS 3.1 is requiring that TLS 1.0 and sometimes (auditor preference it seems) TLS 1.1 be disabled by default.  This currently breaks all but the latest RDP client on windows (MS Mac Client does not currently work with TLS 1.2 - probably for the same reason FreeRDP is having issues).  Having a check box to force TLS 1.2 would be fine in our circumstance as it's the only method enabled.  Since 3.1 went into affect on 6/30/15 I imagine this problem/bug is going to be getting much bigger as more companies come under and go through the PCI 3.1 spec and audits.

**Comment by sthen** [comment]
You can just use SSLv23_client_method. Despite the name this will connect using the best version available (TLSv1.2 if supported by the server). If you want to explicitly disable SSLv2/3 (though libraries are moving to disable these anyway) you can use SSL_OP_NO_SSLv2 and SSL_OP_NO_SSLv3 options.

**Comment by lemonmojo** [comment]
@sthen That's an awesome find! I just tested this and it seems to work fine. Are you aware of any other consequences switching to this method might have?

**Comment by internetstaff** [comment]
Any progress on this?  This is a major concern now that we're in the final days of TLS 1.0 and 1.1.

Thanks.

**Comment by lemonmojo** [comment]
@internetstaff I'm using the tweak @sthen suggested since a few beta versions of my product now and have had only positive feedback.
That being said, I don't know if it's the right way to "fix" the issue and whether it needs to be applied to additional places, like [`here`](https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/sspi/Schannel/schannel_openssl.c#L78).

**Comment by imp1sh** [comment]
How do I use SSLv23_client_method ?

**Comment by imp1sh** [comment]
Could someone please help. I am indeed not able to connect to a server that supports TLS 1.2 only.

**Comment by lemonmojo** [comment]
@imp1sh What worked for me is replacing `TLSv1_client_method` in [tls.c](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/crypto/tls.c#L801) with `SSLv23_client_method` just like @sthen suggested.

**Comment by imp1sh** [comment]
Couldn't the project just serve a solution instead of relying on the users to mud in the code?

**Comment by hardening** [comment]
What is a developper: a user that mud in the code... It's up to everyone to become one, instead of relying on others to do the job.

**Comment by imp1sh** [comment]
I was more thinking of a better quality approach. In my mind a developer is someone who is already capable of developing, not the apprentice type of guy.
In my opinion it is totally fine to rely on others. That's what the community and open source is all about. When everybody is working in its field of expertise, we get best results.

**Comment by bmiklautz** [comment]
@imp1sh if you "just" can provide a solution that satisfies everyone we'll gladly accept it ;). Joke beside. Just wildly changing the client method without in depth testing might break connections to other and/or old servers. The main problem is that most currently servers use TLS < 1.2 changing the client method to SSLv23_client_method should basically work but isn't tested in depth (yet). And since TLS  < 1.2 is the (unfortunately) majority at the moment it's still better to have some people that get their hands dirty than a lot of ...
If it's really such a big problem for you to apply this patch I gladly prepare a special branch where this is applied -( until it was tested and added on master).

**Comment by zonywhoop** [comment]
Just for reference, I'm using RoyalTSX with the SSLv23_client_method enabled and connecting to servers using 2008 through 2012R2 and clients using Windows 7 - 10 with no problems.  This is both in environments where we enforce TLS 1.2 (and disable all others) and where no changes have been made to Windows.

Just my bitcoin :)

--
Ed McLain
ed@edmclain.com

**Comment by lemonmojo** [comment]
I've released a beta version of Royal TSX and the FreeRDP plugin that includes the previously mentioned [change](https://github.com/FreeRDP/FreeRDP/issues/2828#issuecomment-152764715) by @sthen on the 13th of November. So it's in the hands of brave beta users now since almost a month and I haven't had a single complain.

I've also positively tested this against several very old machines including Windows 2000 Advanced Server, Windows XP and Windows Server 2003 R2 as well as several different RDP Gateway configurations and didn't notice any problems.
Note that these are all pretty much clean VMs that I just use for testing RDP, so there's no custom configuration on them.

So from my experience and environment it looks like a pretty save change but I obviously can't test every single configuration out there.
I still don't know what role the [schannel_openssl_client_init](https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/sspi/Schannel/schannel_openssl.c#L78) function plays but I haven't touched it in my FreeRDP builds.
I'd appreciate if someone with deeper FreeRDP knowledge could shine some light on this particular method.

**Comment by bmiklautz** [comment]
@lemonmojo thanks for your feedback.

**Comment by mbbush** [comment]
I made the change @sthen suggested and it works great for me. I also submitted a pull request #3036 with the change, but I don't know enough about this project's testing procedures or policy on PRs from random people to know if it's likely to be accepted or not. In the meantime, feel free to compile from my fork of the project, which has just the change suggested by @sthen

**Comment by bmiklautz** [comment]
Fixed with PR #3046
