### ISSUE TITLE
Multimonitor issue

### ISSUE THREAD

**Issue by elangelo** [FreeRDP/FreeRDP#2833]
I have 3 monitors connected to my linux machine (xrandr) with which i connect to my windows rdp session: one 17 inch, one 24 inch and then another 17 inch
So the resolutions are: 1280*1024 - 1920*1200 - 1280*1024.
When i just tell xfreerdp to use all monitors and calculate the size all by itself it gets something of a 4480*1024. (see picture attached)

![multimonxfreerdp](https://cloud.githubusercontent.com/assets/1935881/9324526/9566bab4-458b-11e5-8a94-04a0ce7b03a8.jpg)

As you can see on the left monitor i get a black area above my full screen firefox window. On the middle one I get 2 bars where my original desktop
background is 'shining' through (the blue bars). But in the left bottom corner you can see the start menu opening (so the start button is way lower).
Also notice that the screens look correct in display settings of windows and then on the right exactly the same behaviour as on the left one.

Weird thing is this is all fixed by just manually specifying the size:
So i add /size:4480x1200 and everything looks fine

**Comment by bmiklautz** [comment]
@elangelo did you use master for your tests?

**Comment by elangelo** [comment]
Afaik I'm using master. (might be a couple of days old now)

$ xfreerdp --version
This is FreeRDP version 1.2.4-dev (git e45ebd8)

**Comment by bjcollins** [comment]
@elangelo Can you provide the command line you use in the broken and working cases? Is the only difference between the two adding the extra size parameter or did you also remove some other options as well? 

Also, please provide what linux distribution you are using as that could have an impact on the behavior that you are seeing.

**Comment by elangelo** [comment]
@bjcollins I just updated my freerdp (running now 1.2.5-dev (git 2d641c4)) and everything works as expected. So I no longer need to add the /size parameter.

For reference I was using following commands:

xfreerdp /v:SERVER /d:DOMAIN /u:USERNAME /p:PASSWORD /g:GATEWAY_SERVER /gd:GATEWAY_DOMAIN /cert-ignore /gu:GATEWAY_USERNAME /gp:GATEWAY_PASSWORD /multimon:force /f /gt:rpc +multitransport
This resulted in the 2 bars you see in the picture in my opening post.
Adding /size:4480x1200 fixed the issue:
xfreerdp /v:SERVER /d:DOMAIN /u:USERNAME /p:PASSWORD /g:GATEWAY_SERVER /gd:GATEWAY_DOMAIN /cert-ignore /gu:GATEWAY_USERNAME /gp:GATEWAY_PASSWORD /multimon:force /f /gt:rpc +multitransport /size:4480x1200

**Comment by bjcollins** [comment]
@elangelo Good news. I am not sure what changed between your last checkout that fixed this issue, but glad to hear it is no longer causing you problems.
