### ISSUE TITLE
OSX - Invalid RDP Key File

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#2836]
Hey All,

I am getting the following error when trying to run freerdp-shadow on a mac as a server and then try to connect from my ubuntu machine with FreeRDP as a client.. This is the latest code. 

`Unable to open RSA key file /Users/meanbunny/Library/Application Support/freerdp/freerdp/shadow/shadow.key No such file or directory` 

Any hints as to what this could be? The file is indeed missing.

**Comment by akallabeth** [comment]
@meanbunny you have to create a server certificate. have a look at the ```winpr-makecert``` tool.
