### ISSUE TITLE
Please make a release of FreeRDP based on git master for applications to target against

### ISSUE THREAD

**Issue by Conan-Kudo** [FreeRDP/FreeRDP#2839]
Could you guys please make a release of FreeRDP 1.2.x-dev that applications can target, specifically applications like [Guacamole](http://guac-dev.org/), who won't update their code because [your API changes too much for them to track git master](https://glyptodon.org/jira/browse/GUAC-1130). Without a release, it's not possible to update FreeRDP for other programs that share usage of the FreeRDP libraries because I need Guacamole, too.

Please, put out a 1.2.x release based on git master that applications can target.

**Comment by hardening** [comment]
@Conan-Kudo I'm adding your issue to the 2.0 milestone

**Comment by Hubbitus** [comment]
Hi.
Sorry, but do you have any milestone date estimations? When 2.0 should out?

**Comment by bmiklautz** [comment]
@Hubbitus no fixed schedule. The version will be increased the next days. The API as it is on master will be further stabilized and cleaned up but for the core the shouldn't be much changes.

**Comment by scaronni** [comment]
Hello, any news on this? I'm the package maintainer in Fedora and we're planning a rebase in Fedora to fix a lot of issues. Thanks!

**Comment by bmiklautz** [comment]
@scaronni we are working hard on stabilizing the API towards a 2.0 release but we can't give any time estimations yet. For packaging I'd suggest using the current master. The API and the functionality is rather stable already.

**Comment by mike-jumper** [comment]
> ... we are working hard on stabilizing the API towards a 2.0 release

@bmiklautz, does this mean that the API *following* 2.0 will be stable, or are you referring strictly to in-progress changes (and anticipate breaking backward compatibility post-release)?

Let's say, hypothetically, that I work on a downstream project which has historically been unable to support any unreleased / untagged version of FreeRDP because of the constantly changing API.

If I were to bring that project up-to-date with the current FreeRDP git, would that effort be for naught? Or would I be able to expect that API changes which break compatibility are now rare, made only when necessary, and in any case documented?

**Comment by Conan-Kudo** [comment]
@mike-jumper I believe it refers to the latter case (the API should be stable up to the 2.0 release, and after 2.0, they will be more willing to break the API). Unless I'm misinterpreting @bmiklautz, you should be in the clear until after 2.0 is released.

**Comment by bmiklautz** [comment]
@mike-jumper @Conan-Kudo the split of the libraries (server, client, ...) won't change any more but the  API itself can't be considered as (completely) stable until the 2.0 release. There will be some changes but not that kind of completely renaming libraries or moving around everything..

Once we've released we'll try to maintain the stable API. If breaking changes are necessary we'll split of a stable branch (where we'll keep the API and plan to back port fixes and improvements (if possible)) and on master the API would be pumped.

The current plan is to freeze the API/ABI some when around July and do a -rc soon afterwards.

**Comment by d3xt3r01** [comment]
Any news ? I can't seem to have remmina and guacamole at the same time on gentoo.

**Comment by scaronni** [comment]
Hello, sorry to bother; Is there any plan for the 2.0-rc1 release, maybe even without closing all 18 bugs pending? The problem with other applications still not able to target agains FreeRDP remains.

Thanks & regards.

**Comment by bmiklautz** [comment]
@scaronni today the last API changes were merged. 2.0 is quite close now. I'll see if we manage to create a time line.

**Comment by scaronni** [comment]
Any update on this? Other months have passed.... it's still a problem to update or link against FreeRDP for most software relying on it.

Thanks.

**Comment by diogocp** [comment]
@bmiklautz it's been more than 9 months since you last message. Two years since the issue was opened. What's holding this up? It's not like we are asking for any new features. We just need a release that applications can target and distributions can package.

**Comment by hardening** [comment]
@diogocp we have plans for a release, the major problem we're facing is the lack of man power to achieve that. We have lotsof people complaining about the lack of releases, using FreeRDP for their softwares, but very few that contributes. So it's up to you to fasten a stable release ;)

**Comment by bmiklautz** [comment]
Work in progress - https://github.com/FreeRDP/FreeRDP/releases/tag/2.0.0-rc0 - http://www.freerdp.com/2017/07/24/2_0_0_rc0-released

**Comment by shadowbq** [comment]
I don't understand the logic here. When there is security vulnerability/breaking change in Microsoft RDP Server (#4486), and FreeRDP master branch 2.x must be changed to adapt to the Microsoft changes, why is there not a RC cut? The downstream distro have to create deb packages pinned to git revs. You can not reasonably think that other software vendors (Apache) will pin to a master rev. Please someone explain this. 

This should not be happening. 
```
2.0.0~git201803141334-0+remmina201803141402.rf8baeb7.d29dd283~ubuntu17.10.1
xfreerdp --version
This is FreeRDP version 2.0.0-dev2 (n/a)
```

**Comment by akallabeth** [comment]
Closing this as new git tags are available.
Still not final 2.0, but at least something you can target.
