### ISSUE TITLE
Null Character Appearing at the End of Copied Strings

### ISSUE THREAD

**Issue by Enverex** [FreeRDP/FreeRDP#2841]
A user is reporting that when they copy and paste text from a remote Windows box (to their local Linux client) it's not working correctly.

After some investigation it appears that for some reason when the text is copied from the Windows server and then pasted to the Linux client, a null character (%00) is appended to the end of the string (it's not there if they paste within the RDP session, only if they paste to the Linux client). It was hard to track this down as most programs and sites strip characters like this so it didn't affect everything.

The RDP server is Windows 2012 R2 and the client is Arch Linux (Kernel 4.1.5, FreeRDP 1.2.0-beta1).

**Comment by ilammy** [comment]
Actually, sometimes it's not a single character, but a bunch of them (see #2287). I have no idea why Windows does this, but apparently UTF8_STRING format must not include terminating null characters. At least, according to [this draft spec](http://www.pps.univ-paris-diderot.fr/~jch/software/UTF8_STRING/UTF8_STRING.text) (we all know how _well_ X11 is standardized).

I am working on some clipboard improvements in X11 client. ilammy/FreeRDP@a3a72169f86a47474ccb8b146ccfad14dfe91111 should fix the issue with null characters.

**Comment by Enverex** [comment]
Have you submitted that as a pull-request?

**Comment by ilammy** [comment]
Not yet. I am going to submit this together with other clipboard-related changes from that branch so that they can be reviewed in one place.

**Comment by Enverex** [comment]
This isn't happening as of current GIT so can now be closed as resolved.
