### ISSUE TITLE
Use unicode to correct work

### ISSUE THREAD

**Issue by coreline** [FreeRDP/FreeRDP#2843]
To correct work in any languages the fields Domain, Username, Password and ServerHostname must be in unicode. 
	ALIGN64 char* ServerHostname; /* 20 */
	ALIGN64 char* Username; /* 21 */
	ALIGN64 char* Password; /* 22 */
	ALIGN64 char* Domain; /* 23 */
must replace on
	ALIGN64 wchar_t* ServerHostname; /* 20 */
	ALIGN64 wchar_t* Username; /* 21 */
	ALIGN64 wchar_t* Password; /* 22 */
	ALIGN64 wchar_t* Domain; /* 23 */
Also need to replace the corresponding dependence. Unfortunately, I do not have sufficient programming skills to fix the error.

**Comment by bmiklautz** [comment]
@coreline can you give some information on what "the error" this fixes is?

**Comment by coreline** [comment]
If login or password has not latin chars you can't logon. For example login will be админ (russian).

**Comment by bmiklautz** [comment]
@coreline are you entering the password/username on the prompt or passing it as option with /p or /u?

**Comment by coreline** [comment]
@bmiklautz i enter in code

	settings->ServerHostname = strdup("host");
	settings->Username = _wcsdup(L"админ");
	settings->Password = _wcsdup(L"123456789");

**Comment by bmiklautz** [comment]
@coreline ok. I see the problem you are having but did you try simply with xfreerdp as well?

**Comment by coreline** [comment]
@bmiklautz what is the xfreerdp? I use FreeRDP in Visual studio 2013.

**Comment by bmiklautz** [comment]
@coreline ok so you use FreeRDP as library and create you own client?

**Comment by coreline** [comment]
@bmiklautz yes

**Comment by coreline** [comment]
@bmiklautz I made a version that takes the Cyrillic alphabet. It works, but it is bad. I can send it to you for analysis to understand what the problem is.

**Comment by akallabeth** [comment]
@coreline FreeRDP mostly uses UTF-8 internally, so you could check if it works for you to just use ```ConvertFromUnicode(CP_UTF8, 0, wchar_string, -1, &utf-8-string, 0, NULL, NULL)``` (from the top of my mind, check arguments if they are correct)

**Comment by coreline** [comment]
@bmiklautz it work. Thank you.

**Comment by akallabeth** [comment]
@coreline So if this is solved for you, could you close the issue?

**Comment by gonzalobarbitta** [comment]
@coreline I am facing a similar issue. I have umlaut (german - äöü) in the password and connection fails. It does work when using wfreerdp, but does not when using FreeRDP as a library with my own client. I would very much appreciate if you could send me the version that takes the Cyrillic alphabet and point me in the right direction as to what the change would be.
