### ISSUE TITLE
a lot of errors during connecting 

### ISSUE THREAD

**Issue by cleric333** [FreeRDP/FreeRDP#2845]
I followed the build instruction to make XfreeRDP and I have 

I5 4670T + AMD R7 250 + 8G for the host (Hyper-V) with remotefx setup correctly 

tow cores with 2GB for the virtual machine and all needed scripts installed

but during the connecting session a lot of errors posted on command line screen and sometime it breaks the connection (That's why I could find out). and the experience was very bad, I could barely watch a video even with crap low quality... 

the errors are like 

[20:16:07:999][2035:2036][ERROR][com.freerdp.codec] - no rects. clip whole session.
[20:16:07:241][2035:2036][ERROR][com.freerdp.codec] - no rects. clip whole session.
........
.............
......................

it runs a lot of, countless, is there anybody faced the same problem and would like to share some tips, many many thanks...

**Comment by cleric333** [comment]
forgot to say the virtual machine runs windows 7 ultimate

**Comment by bmiklautz** [comment]
@cleric333 could you add the command line you are using?

**Comment by jojonewnew** [comment]
Could you try this method?
https://github.com/SBoyNumber1/FreeRDP/commit/f8c9f7a486bdbbb951eb2aa4991dbc8e0946592b

**Comment by cleric333** [comment]
I use something like, xfreerdp /u:111.111.111.111 /p:password /f /rfx, nothing special

**Comment by bmiklautz** [comment]
@cleric333 just to make sure you are connecting directly to the virtualized windows or to hyper-v?

**Comment by cleric333** [comment]
yes I connect directly from client ( Celeron 1037U, 1G, Ubuntu 14 with newest XfreeRDP) to virtuallized windows 7

**Comment by cleric333** [comment]
to make clear

Host: I5 4670T, 8G with windows server 2012 enterprise with Hyper-V and RemoteFX setup

virtual machine: 2 cores with 2G with windows 7 ultimate and RemoteFX graphic card, dxdiag shows all 3D accelerations are OK

client: Celeron 1037U with 1G with Ubuntu 14 and XfreeRDP setup followed build up instruction and works without errors without /rfx

**Comment by akallabeth** [comment]
@cleric333 Hmm, looks like some specific settings on your machine cause this. The error message you get tells that the RFX frame from the server does not contain any update regions, therefore it tries to update the whole screen (which can be quite time consuming). Just tried to connect to a Win7 Ultimate machine and I don't get these errors. (used FreeRDP 9101135e522e4023a3975dddd132afb2f6f34fe7)
Can you try, if this also occurs if you add ```/gfx``` to the command line?

**Comment by cleric333** [comment]
only /gfx without /rfx?

**Comment by cleric333** [comment]
and I tried raspberry Pi 2, exactly the same problem, it seems the error is from the server end

**Comment by cleric333** [comment]
where should I check for the server end?

**Comment by akallabeth** [comment]
@cleric333 both options, ```/gfx /rfx``` This enables the GFX channel. As for the server I can not help there :/

**Comment by ilammy** [comment]
> SBoyNumber1@f8c9f7a
>
> Unfortunately, it isn't documented.
> It seems that server asks to clip whole session when numRects = 0.

By the way, this _is_ documented now, with the latest RDP spec update for Win 10:

> [[MS-RDPRFX] 2.2.2.3.3 TS_RFX_REGION](https://msdn.microsoft.com/en-us/library/ff635233.aspx)
>
> **numRects (2 bytes):** A 16-bit, unsigned integer. Specifies the number of [TS_RFX_RECT (section 2.2.2.1.6)](https://msdn.microsoft.com/en-us/library/ff635241.aspx) structures present in the **rects** field. _If this value is zero, the decoder MUST generate a rectangle with coordinates (0, 0, width, height) that reflects the width and height of the channel's frame (section [2.2.2.1.3](https://msdn.microsoft.com/en-us/library/ff635313.aspx))._

**Comment by bmiklautz** [comment]
@ilammy nice! Thanks for the hint I've update the comment in the code and removed the warning. Should be on master once #2852 is merged.

@cleric333 except the "no rects. clip whole session." do you still have other errors?

**Comment by cleric333** [comment]
too many lines of the same errors, I can only find what I reported.

AND

today I have reloaded windows 2008 enterprise, setup remoteFX, used the same client machine with XfreeRDP without any fix, everything went OK, and the experience of using the virtual machine is much much better

AND 

I reloaded windows 2012 again, the problem remains

**Comment by cleric333** [comment]
it seems the problem is only for windows 2012

**Comment by cleric333** [comment]
it seems the problem is only for windows 2012 host

**Comment by akallabeth** [comment]
Log message no longer on master, closing.
Please reopen if still an issue.
