### ISSUE TITLE
freerdp connect fail through gateway

### ISSUE THREAD

**Issue by Hopedream** [FreeRDP/FreeRDP#2848]
I don't know if it's a bug，here are some of my problems and solutions .

* 1.I can't connect through gateway with the latest code(e45ebd871e23152661babfacddd0fb4179a767d3)
![1](https://cloud.githubusercontent.com/assets/13480468/9514801/ac02c394-4ccf-11e5-9184-51842bdd6579.jpg)

* 2.but connect through gateway with old code is ok(3b332e7829c165aae59ee026a53dece723cccee9)
![2](https://cloud.githubusercontent.com/assets/13480468/9514896/3c38b3c4-4cd0-11e5-90cc-1c8986a9a001.jpg)

* 3.When I raised the question, no one helped me.so find some old code, start testing
![7](https://cloud.githubusercontent.com/assets/13480468/9514955/b3b3c4fc-4cd0-11e5-9e3c-bafb5fcb3223.jpg)

* 4.Through the test I compare the code[73f0153bb6363428de8ffe1e915bc2f91e476134] of the code[1b6ef84b5f9f6960c5e6a25164998821edac2a8e],as follows

![4](https://cloud.githubusercontent.com/assets/13480468/9515056/6d1a8228-4cd1-11e5-9688-e1990500ec56.jpg)
![5](https://cloud.githubusercontent.com/assets/13480468/9515057/6d69103c-4cd1-11e5-96a1-21240a8ff0fe.jpg)
![6](https://cloud.githubusercontent.com/assets/13480468/9515058/6d996548-4cd1-11e5-811d-2dd2a2c465ad.jpg)

* 5.[73f0153bb6363428de8ffe1e915bc2f91e476134]is the last can work and [1b6ef84b5f9f6960c5e6a25164998821edac2a8e] the first one broken

* 6.I tried to restore the [1b6ef84b5f9f6960c5e6a25164998821edac2a8e] submission in the latest code .after the re compile, test success
![8](https://cloud.githubusercontent.com/assets/13480468/9515269/daac0572-4cd2-11e5-910a-937e8d424d2d.jpg)

* 7.I don't know whether it's a bug or I take a mistake again,and my English is very poor, have any questions please help me to point out, thank you

**Comment by akallabeth** [comment]
@Hopedream Thx for the detailed analysis, but this 'fix' was introduced to prevent possible endless loops when SSL errors occur. Looks like this needs some more brainpower to resolve for gateway connectivity. So, if this fix works for you please use the patched version for the time being until a proper fix can be introduced.

**Comment by Hopedream** [comment]
Ok,thank you very much !
