### ISSUE TITLE
ifreerdp build compilation environment issues with OpenSSL-DownloadAndBuild.command

### ISSUE THREAD

**Issue by Hopedream** [FreeRDP/FreeRDP#2849]
## scripts/OpenSSL-DownloadAndBuild.command has some problems ##
* 1.There is no openssl-1.0.2a on this site [openssl](http://www.openssl.org/source),but the script reads as follows
![1](https://cloud.githubusercontent.com/assets/13480468/9519904/7517214c-4cf5-11e5-8f3c-4e613ce4799c.jpg)

* 2.I have change it to 1.0.2d and mark the following script
```sh
 if [ ! "$CS" = "$MD5SUM" ]; then
 echo "Download failed or invalid checksum. Have a nice day."
 exit 1
 fi
```
I hope you are concerned

**Comment by akallabeth** [comment]
@Hopedream The sources for all versions of OpenSSL can be found here: ftp://ftp.openssl.org/source/
As for the (not current) version, if you prefer a newer one just change the ```OPENSSLVERSION``` and ```MD5SUM``` values according to the version you prefer.
The scripts do not always contain the most recent versions as they are only updated when used ;)

**Comment by Hopedream** [comment]
I see,but /scripts/OpenSSL-DownloadAndBuild.command'code as follow
```sh
cd openssl
CS=`md5 -q "openssl-$OPENSSLVERSION.tar.gz" 2>/dev/null`
if [ ! "$CS" = "$MD5SUM" ]; then
    echo "Downloading OpenSSL Version $OPENSSLVERSION ..."
    rm -f "openssl-$OPENSSLVERSION.tar.gz"
    curl -o "openssl-$OPENSSLVERSION.tar.gz" http://www.openssl.org/source/openssl-$OPENSSLVERSION.tar.gz

    CS=`md5 -q "openssl-$OPENSSLVERSION.tar.gz" 2>/dev/null`
    if [ ! "$CS" = "$MD5SUM" ]; then
	echo "Download failed or invalid checksum. Have a nice day."
	exit 1
    fi
fi
```
you can check it,commit code(e45ebd871e23152661babfacddd0fb4179a767d3)
Whether the link is wrong?

**Comment by akallabeth** [comment]
@Hopedream Yes, you are right. OpenSSL project just has the most recent versions on their http site. The link is OK, you just have to change the version to one of the currently supported ones (including MD5SUM)
