### ISSUE TITLE
[GFX H264] decoder issues

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#2850]
* connect to Win8.1 RDP using h264 (openH264)
* resolution preferrably ```640x480``` (with this resolution the error occurs most often)
* ```DecodeFrame2``` fails with ```dsDataErrorConcealed``` bit set. (not always but often)

**Comment by akallabeth** [comment]
Update:
This only applies to ```RDPGFX_CAPVERSION_81```. With ```RDPGFX_CAPVERSION_8``` the frames get decoded properly.

**Comment by alantm2** [comment]
Hi, are there any updates please?

Please note that https://github.com/FreeRDP/FreeRDP/issues/2819 appears to be the same issue although the target system is a windows server.

**Comment by akallabeth** [comment]
Workaround implemented with #2865, MS RDP 8.1 implementation sends invalid H264 data :/
