### ISSUE TITLE
Default behavior  wallpaper cmdline option

### ISSUE THREAD

**Issue by giovannitarter** [FreeRDP/FreeRDP#2853]
On the linux client, the 

-wallpaper (default:on)     Wallpaper

option is not on by default.
If I launch xfreerdp without any option, the wallpaper is disabled. To enable it I have to launch xfreerdp with +wallpaper option.

Thanks

**Comment by bmiklautz** [comment]
@giovannitarter you are right the help documentation is wrong and in reality Wallpaper is disabled per default. I'll create a pull request that enables the wallpaper per default as the documentation says.
