### ISSUE TITLE
X_Putlmage problem

### ISSUE THREAD

**Issue by cleric333** [FreeRDP/FreeRDP#2857]
when I use XfreeRDP to connect Hyper-V, if I add /rfx, the system gives a error 

major opcode of failed request ：72（X_Putlmage）

Serial number of failed request : 126

Current serial number in output stream :637

I have found somethings related from FreeRDP's issues page

https://github.com/FreeRDP/FreeRDP/issues/694

but I am not able to find libxrendr-dev in Raspbian as they suggested in the post, are there somebody faced the same problem on Raspberry?

**Comment by akallabeth** [comment]
don't you mean ```libxrandr-dev```? According to http://archive.raspbian.org/raspbian/pool/main/libx/libxrandr/ it is part of raspbian ;)

**Comment by cleric333** [comment]
then that is super weird... any suggestion?

**Comment by akallabeth** [comment]
@cleric333 did you check the spelling? you have written it wrong ;)
