### ISSUE TITLE
FreeRDP  graphic acceleration?

### ISSUE THREAD

**Issue by uforgetmenot** [FreeRDP/FreeRDP#2858]
I'm using xfreerdp in gfx mode on ubuntu pc based on a intel celeron N2807 cpu, then find it is really slow when playing a 1080p video on the remote side. 
I notice that the cpu's usage is very high but the gpu almost does nothing.
I think that using glx or opengl may help.
How can improve the performance？ Any ideas?
Thanks!

**Comment by akallabeth** [comment]
@uforgetmenot FreeRDP currently uses software decoding for all GFX modes.
 To use the GPU to do decoding it would be necessary to implement the drawing callbacks.
This is quite some work, so if you are interested, have a look at the following routines (no gurantee for completeness):

* GDI and RFX 7.1 modes: 
 * ```update->SurfaceBits```
 * ```update->SurfaceFrameMarker```
 * ```update->altsec->FrameMarker```
 * ```update->BeginPaint```
 * ```update->EndPaint```
 * ```update->DesktopResize```
* GFX modes:
 * ```gfx->ResetGraphics```
 * ```gfx->StartFrame```
 * ```gfx->EndFrame```
 * ```gfx->SurfaceCommand```
 * ```gfx->DeleteEncodingContext```
 * ```gfx->CreateSurface```
 * ```gfx->DeleteSurface```
 * ```gfx->SolidFill```
 * ```gfx->SurfaceToSurface```
 * ```gfx->SurfaceToCache```
 * ```gfx->CacheToSurface```
 * ```gfx->CacheImportReply```
 * ```gfx->EvictCacheEntry```
 * ```gfx->MapSurfaceToOutput```
 * ```gfx->MapSurfaceToWindow```

**Comment by uforgetmenot** [comment]
Thanks for your advice!
