### ISSUE TITLE
evor question 

### ISSUE THREAD

**Issue by FreeRDPDerek** [FreeRDP/FreeRDP#2860]
Hi everyone,
      I found a phenomenon about evor.
      when OS turns on and plays video by the media player or VLC player first time, the player will be showed up late. and sometimes, there is an error "cannot find the file" happened.
      but after first time, OS opens the player immediately and there is no that error happened.
      why is there this difference?

Thanks,
Derek

**Comment by bmiklautz** [comment]
@FreeRDPDerek I'm not aware of evor how is this related to FreeRDP?
For questions please use our irc channel or the mailing list but not the issue tracker.
