### ISSUE TITLE
Monitor Detection and Size Issue (GIT)

### ISSUE THREAD

**Issue by Enverex** [FreeRDP/FreeRDP#2863]
The "/monitors" flag in xfreerdp didn't historically appear to follow XOrg's own ordering. For example if I have VGA1 to the left of HDMI1, in xfreerdp HDMI1 will be monitor 0 and VGA1 will be monitor 1 (where as in XOrg the better connection always takes priority, so HDMI1 will have been the leftmost monitor and VGA1 will have been on the right). As of current GIT this has changed and freerdp now seems to follow XOrg's ordering, so after telling XOrg that I wans HDMI1 to the right of VGA1, VGA1 (leftmost monitor) is now 0 and HDM1 is now monitor 1. That's not an issue in itself but is part of the issue below:

As of current GIT, if I tell xfreerdp to use fullscreen (/f) on the second monitor, it displays fullscreen on the second monitor, but at the size of the leftmost monitor. For example: Monitor 1 (left) is 1280x1024, Monitor 2 (Right) is 1920x1080. If I tell xfreerdp to display fullscreen on the right monitor (/f /monitors:1) it will open fullscreen on the right-hand monitor, but the RDP session will only be 1280x1024 in size.

**Comment by Enverex** [comment]
Just to update this, I'm now running a build from 7th of Jan and the behaviour is different again.

Regardless of what I set with the "monitors" flag, e.g. "/monitors:0" or "/monitors:1", etc. FreeRDP always appears on the left monitor. Previously the options above would cause it to appear on the left or right respectively. This is a problem when paired with the fullscreen option.

**Comment by hardening** [comment]
@Enverex which WM are you running ?

**Comment by hardening** [comment]
WM as window manager

**Comment by Enverex** [comment]
I'm running XFCE4 on them (always have been).

**Comment by Enverex** [comment]
Any movement on this? It's a nightmare having to manage users with this current problem.

In case it's related, I noticed I can Ctrl+Alt+Enter to fullscreen on the left-most monitor and then press it again to un-fullscreen it. But if I try that on the second monitor (the one that I can't get FreeRDP to open on initially in the first place) it'll fullscreen, but it won't unfullscreen. It just flickers and stays fullscreened.

**Comment by bmiklautz** [comment]
@Enverex the problem still occurs with the latest master?

**Comment by Enverex** [comment]
Rolling out a GIT version of the package onto the machines currently using it will be virtually impossible so I may not be able to test that.

I'll see if I can work something out and will report back here if successful.

**Comment by Enverex** [comment]
Just tested with a build from GIT master, the following issues persist:

The main issue: Trying to select the second monitor via /monitors:1 has no effect, it still just appears on the primary monitor (I tried 0, 1 and 2, it always appeared on the main/left monitor). Doing /monitor-list showed both monitors correctly so it is seeing them.

Fullscreening the window (via Ctrl+Alt+Enter) works, but then trying to unfullscreen it (via Ctrl+Alt+Enter again) just flickers the window and it doesn't unfullscreen. Note that I CAN move the window around if I right click the window in the XFCE4 active Windows bar and select Move.

**Comment by Kal42** [comment]
Hi, 

I use version [7534876209b49239909828e289de6664a668428b](https://github.com/FreeRDP/FreeRDP/commit/7534876209b49239909828e289de6664a668428b), And I have pretty similar issue.
I use also xfce4.

I have 2 icons on monitors 0 and 2 icons monitors 1 to try all configuration possible.
I also try launch it from ssh.

The two commande line for each icons :  
`xfreerdp /cert-ignore /v:192.168.200.11 /monitors:1 -sec-nla`
`xfreerdp /cert-ignore /v:192.168.200.11 /monitors:0 -sec-nla`

All my test :
- If monitor 0 and monitor 1 have the same resolution.
The RDP appears on the screen where the mouse pointer is.
 If mouse pointer is on _monitor 0_ all rdp go to _monitor 0_.
 If  mouse pointer is on _monitor 1_ all rdp go to _monitor 1_.

- If monitor 0 and monitor 1 haven't the same resolution.
  -  If mouse pointer is on _monitor 0_ :
     It's work only in fullscreen (with /f)
  -  If mouse pointer is on _monitor  1_ :
      All the RDP appears on the _monitor 1_

**Comment by Enverex** [comment]
Ok, I've just rebuilt from GIT to test this and it's still broken but in a very weird way. Slightly different from Kal above:

If the monitors are different resolutions then FreeRDP appears on the monitor that I've asked it to appear on.

If the monitors are the same resolution then it always just appears on the left (first) monitor, regardless of which monitor it was asked to appear on. This is where the mouse is so it could simply be appearing on the monitor on which the mouse currently resides.

Not sure how this bug has gone on for so long. I'm having to use a build nearly a year old now because of this, which is far from ideal.

**Comment by WarheadsSE** [comment]
@Enverex  is the left monitor also Primary in xrandr?

**Comment by Enverex** [comment]
Yes.

**Comment by WarheadsSE** [comment]
@Enverex please switch which monitor is primary, and try again. If it follows the Primary monitor, then I have seen a similar behavior in xfwm4 & Citrix. xfwm4 makes use of the GTK monitors list, which is different from the Xinerama/XRandR layouts.

**Comment by Enverex** [comment]
I can't test that unfortunately, as I've had to roll-back the systems that were being tested. These machines are running XFCE4 (thus XFWM) though so it sounds like the same issue.

**Comment by WarheadsSE** [comment]
@Kal42 this behavior you describe is due to window placement policy in xfwm4. I can attest that it is the exact case I have w/ XFCE bug open.

**Comment by akallabeth** [comment]
Closing as not our fault :)
