### ISSUE TITLE
Connecting after a reboot fails consistently

### ISSUE THREAD

**Issue by colemickens** [FreeRDP/FreeRDP#2876]
``` shell
$ xfreerdp \
        /cert-ignore \
        /v:localhost:33890 \
        /size:2560x1650 \
        /u:USERNAME \
        /p:PASSWORD \
        /scale-device:140 \
        /scale-desktop:140 \
        +fonts \
        +compression \
        +toggle-fullscreen \
        -wallpaper

[19:03:02:028] [25056:25057] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
[19:03:02:028] [25056:25057] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1
```

If I login to the machine and then try to connect, it simply works, after closing the FreeRDP window, the complete output is:

``` shell
[19:04:18:662] [25130:25131] [INFO][com.freerdp.client.x11] - Closed from X11
```

**Comment by colemickens** [comment]
I don't know how to get more debugging info or more verbose output, but am happy to do so if it's possible...

**Comment by akallabeth** [comment]
@colemickens You can set the environment variable ```WLOG_DEBUG=trace``` (or  ```WLOG_DEBUG=debug``` for a bit less) debug output.

**Comment by colemickens** [comment]
Hm, that didn't get me any additional output in my scenario.

**Comment by akallabeth** [comment]
@colemickens So, what OS is the remote machine running?

**Comment by colemickens** [comment]
It's Windows 10, and I'm trying to RDP into an account from the domain the machine is joined to.

**Comment by akallabeth** [comment]
Ah, sorry just now realized my typo, should be ```WLOG_LEVEL``` and not ```WLOG_DEBUG```, should not write before first coffee ;)

**Comment by colemickens** [comment]
So, I'm getting more output with that. With a custom built version, I see the actual NTLMSSP tokens printed out. With xfreerdp from Arch repos, I get less output, but it stills fails. On my custom build, the plaintext readable portions of the NTLMSSP tokens seem to be the same between a bad login and a good one.

Also, rdesktop is able to connect, but it doesn't count as a "first login". I still have to physically login to the machine before xfreerdp will connect.

**Comment by colemickens** [comment]
Interesting!

I've noticed that if I log in from another machine that is in the domain... after a reboot, it forces me to manually enter my password instead of using the stored one... and then subsequent logins use the stored password.

Still can't figure out why `rdesktop` will work but `freerdp` doesn't, but my workaround is working well enough of logging in with rdesktop, killing it after 10 seconds and then reconnecting with freerdp.

**Comment by colemickens** [comment]
This now affects every single one of my Windows 10 machines. FreeRDP continues to not connnect unless I:

1. Manually login to the device, then xfreerdp works.

2. Login via `rdesktop`, then reconnect with xfreerdp.

**Comment by simon04** [comment]
I had a similar issue (could not connect to / login on Windows 10 machine). Adding `-sec-nla` did the trick for me: now instead of supplying the password on the command line, I enter it within the RDP session and connect successfully.

**Comment by akallabeth** [comment]
so closing as fixed?
reopen/create a new one if still not solved.
