### ISSUE TITLE
remoteapps, mouse doesn't work correctly

### ISSUE THREAD

**Issue by Scordy** [FreeRDP/FreeRDP#2884]
I've recently installed Ubuntu Gnome and it is working great, however there are certain Windows applications that I still need to use on a day-to-day basis.

I had an 'older' computer laying around, on which I installed windows 10.
I Then came across a webpage which explained Remoteapps on ubuntu.

Using internet acquired knowledge, I used this command to try and connect to my remote computer:
xfreerdp /v:192.168.1.xxx:3389 /u:xxx /p:xxx /rfx "/app:||explorer" +fonts +aero +menu-anims +smart-sizing +compression +clipboard +window-drag

This worked except that my mouse wasn't tracked right on the screen. Their website told me to add /workspace to my big command. It did not work.
My mouse on my ubuntu screen does not equal the mouse on the Windows rdp connection. 

Any help would be appreciated.

**Comment by hardening** [comment]
@Scordy can you give us which version of FreeRDP you're running ? And giving the page with the instructions you followed could help us too.

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
