### ISSUE TITLE
pdutype bad still happens

### ISSUE THREAD

**Issue by piovisqui** [FreeRDP/FreeRDP#2885]
I still get "pdutype bad" when connecting to Windows 2012 R2 Remote Desktop Gateway. It happens after I type the password. Please, solve it =]

xfreerdp -d faculdade -u username example.com
Password: 
pduType bad

^C

**Comment by bmiklautz** [comment]
@piovisqui can you please give as some more information about the FreeRDP version you are using?

**Comment by piovisqui** [comment]
xfreerdp  --version
This is FreeRDP version 1.0.2
 cat /etc/issue
Welcome to openSUSE 13.2 "Harlequin" - Kernel \r (\l).

**Comment by piovisqui** [comment]
@bmiklautz My lame bug report is better now

**Comment by bmiklautz** [comment]
@piovisqui you can try our nightly packages for SUSE (https://ci.freerdp.com/view/Packaging/job/freerdp-nightly-rpm-build/). Those are based on the latest master and I think they fix your problem.

**Comment by piovisqui** [comment]
I tried. After I type the password, I don't see "pdutype  bad", but this:
[20:31:53:952] [29068:29069] [ERROR][com.freerdp.core] - WSAEventSelect returned 00002734
[20:31:53:952] [29068:29069] [ERROR][com.freerdp.core] - WSAEventSelect returned 00002734

**Comment by bmiklautz** [comment]
@piovisqui if you use a gateway I wonder why you don't use the "gateway parameters" like /gu or /g

**Comment by piovisqui** [comment]
The /g option produces the same results.

**Comment by bmiklautz** [comment]
@piovisqui you tried with /g:"your gateway ip" ?

**Comment by piovisqui** [comment]
@bmiklautz wow, it worked.

/opt/freerdp-nightly/bin/xfreerdp -u user -d domain -g 200.x.x.x rds.com.br 
/opt/freerdp-nightly/bin/xfreerdp -version
This is FreeRDP version 1.2.5-dev (git n/a)

Using the ip adress instead of the hostname even works with the older version.
xfreerdp --version
This is FreeRDP version 1.0.2 

Can you still fix it to work with the hostname?

**Comment by Hopedream** [comment]
@piovisqui, It is ok to make the following revision
FreeRDP- xxx\libfreerdp\crypto\tls.c
## 1、static int bio_rdp_tls_write(BIO* bio, const char* buf, int size)
case SSL_ERROR_SYSCALL:
BIO_set_flags(bio,(BIO_FLAGS_WRITE|BIO_FLAGS_SHOULD_RETRY));
//BIO_clear_flags(bio, BIO_FLAGS_SHOULD_RETRY);

## 2、static int bio_rdp_tls_read(BIO* bio, char* buf, int size)
case SSL_ERROR_SYSCALL:
	BIO_set_flags(bio, (BIO_FLAGS_READ | BIO_FLAGS_SHOULD_RETRY));
	//BIO_clear_flags(bio, BIO_FLAGS_SHOULD_RETRY);

**Comment by bmiklautz** [comment]
@Hopedream I'm not convinced that this is still required with the latest master did you try?
@piovisqui ".. fix it tow work with the hostname?" That should work if your DNS works.

/opt/freerdp-nightly/bin/xfreerdp /u:user /d:domain /g:your.gateway.domain /v:rds.com.br 

If you use a version > 1.0 I'd suggest using the new command line syntax style.

**Comment by piovisqui** [comment]
@bmiklautz The DNS are working, Windows clients on the same network does not have any problem. 

I tried today and got the error again (with and without hostname) :\

[18:37:45:672] [18994:18995] [INFO][com.freerdp.client.x11] - Do you trust the above certificate? (Y/N) 
y
Password: 
[18:38:08:969] [18994:18995] [ERROR][com.freerdp.core] - WSAEventSelect returned 00002734
[18:38:08:969] [18994:18995] [ERROR][com.freerdp.core] - WSAEventSelect returned 00002734
[18:40:01:210] [18994:18995] [ERROR][com.freerdp.core.transport] - error when flushing outputBuffer
[18:40:01:210] [18994:18995] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[18:40:01:210] [18994:18995] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
[18:40:01:210] [18994:18995] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[18:40:01:210] [18994:18995] [ERROR][com.freerdp.client.x11] - Authentication only, exit status 1



If you check the times, it hangs for a while after the password insertion than gives an error.

**Comment by Hopedream** [comment]
@bmiklautz I have try,it's ok  with the latest master

**Comment by akallabeth** [comment]
Is this still an issue or is it fixd? @Hopedream

**Comment by piovisqui** [comment]
I couldn't connect. I was going to try version 2.0, but got stuck in the dependencies.

`(1/2) Installing: libcrypto34-2.2.1-2.10.1 .......................................................................................................................................................................................[done]
(2/2) Installing: libssl33-2.2.1-2.10.1 ..........................................................................................................................................................................................[done]
linux-roo # rpm -ivh freerdp-nightly-2.0-0+0~20160226033818.179~1.git16ba8f3.x86_64.rpm 
error: Failed dependencies:
	libcrypto.so.10()(64bit) is needed by freerdp-nightly-2.0-0+0~20160226033818.179~1.git16ba8f3.x86_64
	libcrypto.so.10(libcrypto.so.10)(64bit) is needed by freerdp-nightly-2.0-0+0~20160226033818.179~1.git16ba8f3.x86_64
	libssl.so.10()(64bit) is needed by freerdp-nightly-2.0-0+0~20160226033818.179~1.git16ba8f3.x86_64
	libssl.so.10(libssl.so.10)(64bit) is needed by freerdp-nightly-2.0-0+0~20160226033818.179~1.git16ba8f3.x86_64
`

**Comment by akallabeth** [comment]
@piovisqui Which OS are you using?

**Comment by akallabeth** [comment]
@piovisqui Oh, sorry missed the suse part ^^ Do you have openssl installed?

**Comment by piovisqui** [comment]
Yes, I have openssl.

**Comment by akallabeth** [comment]
@piovisqui Which RPM are you using? I see only fedora builds are recent, the suse ones are disabled currently.

**Comment by piovisqui** [comment]
I downloaded this: https://ci.freerdp.com/view/Packaging/job/freerdp-nightly-rpm-mock/architecture=x86_64,distribution=23,label=pkg-rpm-mock/lastSuccessfulBuild/artifact/freerdp-nightly-2.0-0+0%7E20160227033815.180%7E1.git9d21117.x86_64.rpm 
From this page: https://ci.freerdp.com/view/Packaging/job/freerdp-nightly-rpm-mock/architecture=x86_64,distribution=23,label=pkg-rpm-mock/

**Comment by akallabeth** [comment]
@piovisqui So you are using the fedora builds on suse? Better try to compile yourself, the redhat world is quite different from suse...

**Comment by bmiklautz** [comment]
@akallabeth @piovisqui we do (did) basically have builds for opensuse https://ci.freerdp.com/job/freerdp-nightly-rpm-build/ - however I didn't come around to fix the build after the update to leap 42.1. But's on my list.
In the meanwhile you can try one of the older builds - they are still more recent than 1.x

**Comment by hardening** [comment]
lack of activity, let's close it
