### ISSUE TITLE
+auth-only option not woking  with windows xp and windows server 2003

### ISSUE THREAD

**Issue by IBqZWEBoGMqa7** [FreeRDP/FreeRDP#2893]
Hi, I want to  write a python script to brute force rdp username and passwrod using freerdp.
so i user following command to check  username and password is correct or not  in kali linux. just auth only.
/usr/bin/xfreerdp /v:192.168.237.138 /u:administrator  /p:123456  +auth-only /cert-ignore

when i test in windows server 2008 and windows 7. if the username and password is correct.
the output is :
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:692: Authentication only. Don't connect to X.
connected to 192.168.237.138:3389
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/libfreerdp/core/freerdp.c:95: Authentication only, exit status 0
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:1278: Authentication only, exit status 0

the exit  status is 0

if the username and password is not correct , the output is :
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:692: Authentication only. Don't connect to X.
connected to 192.168.237.138:3389
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:SSL3_READ_BYTES:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/libfreerdp/core/freerdp.c:95: Authentication only, exit status 1
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:1278: Authentication only, exit status 1

Authentication failure, the exit status is 1.

so i think the exit status 0 means auth success, while  exit status 1 means fail.

but when i test in windows server 2003 and windows xp:
even the username and password is not correct, the the exit status is always 0. 
so i can figure out  whether the username and password is correct or not.

is my understanding of exit status wrong or something else?

**Comment by LiarBing** [comment]
with markdown.

Hi, I want to write a python script to brute force rdp username and passwrod using freerdp.
so i user following command to check username and password is correct or not in kali linux. just auth only.
```
/usr/bin/xfreerdp /v:192.168.237.138 /u:administrator /p:123456 +auth-only /cert-ignore
```

when i test in windows server 2008 and windows 7. if the username and password is correct.
the output is :
```
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:692: Authentication only. Don't connect to X.
connected to 192.168.237.138:3389
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/libfreerdp/core/freerdp.c:95: Authentication only, exit status 0
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:1278: Authentication only, exit status 0
```
the exit status is 0

if the username and password is not correct , the output is :
```
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:692: Authentication only. Don't connect to X.
connected to 192.168.237.138:3389
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:SSL3_READ_BYTES:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/libfreerdp/core/freerdp.c:95: Authentication only, exit status 1
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:1278: Authentication only, exit status 1
```
Authentication failure, the exit status is 1.

so i think the exit status 0 means auth success, while exit status 1 means fail.

but when i test in windows server 2003 and windows xp:
even the username and password is not correct, the the exit status is always 0. 
so i can figure out whether the username and password is correct or not.

is my understanding of exit status wrong or something else?

**Comment by astro-train** [comment]
I have the same issue. No matter what credentials where provided to wfreerdp.exe with +auth-only it always returns 0 when connecting to Windows XP SP3. With Windows Server 2008 everything works properly.

**Comment by anthraxx** [comment]
any developer comment on this one? Its quite annoying not being able to get a result of an authentication attempt

**Comment by bmiklautz** [comment]
I'd guess that you see the login screen when the attempt isn't successful. So if connected without +auth-only do you get a login screen?
Can/did you also already try with +sec-nla?

**Comment by hardening** [comment]
If the authentication succeeds you may receive a SaveSessionInfo PDU, but it's not guaranteed. So you have no deterministic way to know that the authentication failed or succeeded.

**Comment by Oliver-Luo** [comment]
I think by definition the security protocol rdp/tls does not check the correctness of username/password, while protocol nla/ext does check. The following part is from MS ducoment(Remote Desktop Protocol: Basic Connectivity and Graphics Remoting):

> Network Level Authentication (NLA): Refers to the usage of CredSSP (as defined in [MS-CSSP]) within the context of an RDP connection to **authenticate the identity of a user at the network layer before the initiation of the RDP handshake**. The use of NLA ensures that server resources are only committed to authenticated users.

So if you input the wrong username/password, in rdp/tls mode the connection is established and you will see a new GUI window informing that the username/password is wrong. However, in nla/ext mode the check will be done before the establishment of the connection, so you will get the output directly without the new GUI window.

**Comment by akallabeth** [comment]
ok, closing this as
* XP and 2003 are EOL
* the problem with authentication modes was already explained above by @hardening

**Comment by affectalways** [comment]
I encountered the problem and solved it.
Python: 3.7.4 Freerdp: 2.2.0
Freerdp USES the wrong username and password to burst and will automatically shut down within 50 seconds.Use the correct username and password for the burst, and the connection will be closed for much longer than 50 seconds.
You can judge whether the user name and password of blasting are correct according to the above characteristics (only applicable to Windows 2003 and XP, because it is time-consuming).

**Comment by affectalways** [comment]
Another solution, Use the following command: WLOG_APPENDER=FILE WLOG_FILEAPPENDER_OUTPUT_FILE_PATH=`log_directory` WLOG_FILEAPPENDER_OUTPUT_FILE_NAME=`log_name` xfreerdp /v:****:**** /u:**** /p:**** /cert-ignore +sec-nla /admin +drives /drive:****,**** /t:****
Then monitor the generated log. If the log content contains shared directory name and Registered device, the connection is successful.  If the log contains "logon Error info session_id", the connection fails
