### ISSUE TITLE
aFreeRDP can't disconnect

### ISSUE THREAD

**Issue by Hopedream** [FreeRDP/FreeRDP#2894]
## Disconnect application error, the following figure(In the picture red word is translated)
![1](https://cloud.githubusercontent.com/assets/13480468/9927741/9cd09bbe-5d53-11e5-96e0-487c0411a909.png)
![2](https://cloud.githubusercontent.com/assets/13480468/9927742/9cea1fb2-5d53-11e5-8d90-b7ab0c29a24a.png)

**Comment by shaunsphere** [comment]
same thing happens here, it was good until I rebuild and replace new lib file (libfreerdp-android.so).
I got some new cool features but crash when disconnect

**Comment by binglinoioij** [comment]
Hello All:
I have the same problem, did you solve it?

**Comment by sanmeng** [comment]
@binglinoioij no,I think it is due to waitforobject(by source code) timeout when disconnect

**Comment by binglinoioij** [comment]
@sanmeng , But it have no this problem,  If you download the app in google play.

**Comment by sanmeng** [comment]
@binglinoioij Using older code to compile will not have this problem . You can view the source code to compare the two versions .Google may be an earlier version

**Comment by binglinoioij** [comment]
@sanmeng Do you know what the version is?

**Comment by sanmeng** [comment]
You can try it(3b332e7829c165aae59ee026a53dece723cccee9), maybe earlier, I have tested more than 50 versions。test details I can not find, you can look at my other ID(The current problem of the moderator) provides the details .

**Comment by Hopedream** [comment]
@binglinoioij 
![d862ef4c-4b47-11e5-8aee-1c699df6d3d6](https://cloud.githubusercontent.com/assets/13480468/12713969/c85193d6-c90c-11e5-9a99-897a5d07a651.jpg)

code submission time and version | author | I test the date | result

**Comment by akallabeth** [comment]
Reworked the whole aFreeRDP project in #3097 
This also fixes the disconnect issue.
If you want to continue using the old client project you need to remove ```WaitForSingleObject(ctx->thread, INFINITE);``` in ```android_freerdp.c:737``` which leads to a deadlock.

**Comment by Hopedream** [comment]
@akallabeth ok,tks

**Comment by binglinoioij** [comment]
@sanmeng @akallabeth  tks!
