### ISSUE TITLE
xFreeRDP session stops responding to mouse clicks

### ISSUE THREAD

**Issue by cmotionless** [FreeRDP/FreeRDP#2902]
Hi there,

Recently at my company we started using Intel NUC's running Ubuntu 15.04, with FreeRDP to connect to our Server with RDP - a Windows Server 2008R2 Enterprise server. xFreeRDP has proved very good for our users, running multimonitor setups, however since version 1.1 they have experienced an issue where, completely randomly, the session will appear to freeze - however the user is not disconnected from the main server, and a user can still alt-tab between tasks, mouse clicks however stop responding, and the cursor freezes on the last application they were using (for example, when the users are using google maps, the cursor will freeze as the arrow symbol).

We are now running version 1.2.5, however the issue has still occurred - I've looked through the internet and there hasn't been any conclusive solution to this bug, is anyone able to provide suggestions?

Thanks.

**Comment by gnshkl1** [comment]
try 1.2.1 or master GIT

**Comment by akallabeth** [comment]
@cmotionless The versions found on ubuntu are quite old. You can try our nightly builds or build from source. (There is also a 2.0 package in debian sid)

**Comment by bmiklautz** [comment]
@cmotionless https://ci.freerdp.com/job/freerdp-nightly-binaries/ the link to our nightly binaries.
