### ISSUE TITLE
no way to securely handle passwords from the command line

### ISSUE THREAD

**Issue by jasonblewis** [FreeRDP/FreeRDP#2904]
there should be a way to securely pass the login password from the command line. if you use the /p:password option this can leave the password visible in the process list.

would it be possible to have a way of passing the password via stdin or another file descriptor perhaps?

**Comment by akallabeth** [comment]
@jasonblewis You could try using the command line argument ```/from-stdin```

**Comment by bmiklautz** [comment]
@jasonblewis what version of FreeRDP are you using? The password shouldn't be visible on the command line but instead be replaced with '*'.

**Comment by Link-Satonaka** [comment]
I also had this question, and I shared the solution I came up with here: https://github.com/FreeRDP/FreeRDP/issues/1358#issuecomment-184537537

I don't know what security concerns this brings up. You can't select text in dmenu, nor can you copy from the input in any way that I know of. xprop can't see it and xwininfo doesn't betray any information about what is typed. It sends the password via standard output, but sudo's manpage says ASK_PASS does that too. dmenu wasn't designed to be an ASK_PASS type thing, but I don't see any obvious issue here. I can't see any info in /proc/$PID for dmenu or the script running dmenu.

I know that on Windwows you can get the text content of a window programatically- if the same can be done in X11 then this isn't bulletproof (though a fork of dmenu, dmenu2, has masked '*' input support). But as a way to type in passwords when someone is looking over your shoulder, this should be fine, no?

**Comment by akallabeth** [comment]
@Link-Satonaka Your example has the same issue @jasonblewis wants to avoid (you pass the password with the ```/p:yourpassword``` argument. A more secure way would be to use ```/from-stdin``` and pipe the password to start freerdp (like ```echo password | xfreerdp /v:your.host /u:your_user /from-stdin```)

**Comment by jasonblewis** [comment]
yep, I've been doing that and it works fine. should have closed this ages ago. sorry.

**Comment by Link-Satonaka** [comment]
@akallabeth ah thanks for the tip, I tried using /from-stdin a while back, but couldn't get it to work before. Seems to be working fine now!

**Comment by rkeene** [comment]
This doesn't really help since if you use "from-stdin" you are not able to accept the certificate of the remote host.

```
The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the documentation on how to create local certificate store for a private CA.
Do you trust the above certificate? (Y/N) 
Error: Could not read answer from stdin. - Run without parameter "--from-stdin" to set trust
```

**Comment by Link-Satonaka** [comment]
Granted, you need to use a terminal for that "first time setup" for every new host. Shouldn't be too difficult to detect that error, relaunch in a terminal.

**Comment by Link-Satonaka** [comment]
(that in my example shell script)

**Comment by rkeene** [comment]
A much simpler solution is to accept reading the password from the environment in a manner similar to OpenSSL:

```
--- FreeRDP-1.0.2.orig/libfreerdp-utils/args.c  2013-01-02 15:46:59.000000000 -0600
+++ FreeRDP-1.0.2-passwordviaenviron/libfreerdp-utils/args.c    2016-03-29 12:07:16.043139496 -0500
@@ -165,7 +165,12 @@
                                printf("missing password\n");
                                return FREERDP_ARGS_PARSE_FAILURE;
                        }
-                       settings->password = xstrdup(argv[index]);
+
+                       if (strncmp(argv[index], "ENV:", 4) == 0) {
+                               settings->password = xstrdup(getenv(argv[index] + 4));
+                       } else {
+                               settings->password = xstrdup(argv[index]);
+                       }
                        settings->autologon = 1;
 
                        /*
```
