### ISSUE TITLE
keyboard /kbd:French FR UTF8 OR ISO-8859 ?

### ISSUE THREAD

**Issue by mecalectro91** [FreeRDP/FreeRDP#2905]
Hello, I have a problem with a barcode scanner and keybord mapping freerdp. I am French and I think freerdp uses fr_FR.utf8 when I add the options / kbd: French. but I like to use ISO-8859-1 en_US, how can we do?

**Comment by hardening** [comment]
I have not checked but in my memory /kbd was expecting a RDP keymap code not a string name.

**Comment by mecalectro91** [comment]
CommandLineInterface the documentation says:

/ kbd: 0x <layout id> or <layout name> Keyboard layout

I was wrong in my previous message!

I like to use ISO-8859-1 fr_FR  instead of fr_FR.utf-8, but I do not know how ... there is an option?
I think he must miss an additional layout for France

**Comment by hardening** [comment]
So at the end it's not an issue. Next time, go and ask (and wait a significant time for an answer) before submitting an issue.
