### ISSUE TITLE
Passwordless (blank password) login with NLA

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#2907]
With Microsoft's Remote Desktop Clients it is possible to use both, NLA and a passwordless (blank password) login.
This doesn't seem to be the case for FreeRDP though as all my attempts to authenticate with such a user failed.

Is this supposed to be supported and broken right now or has there never been support for this scenario in FreeRDP?

**Comment by HenryJacques** [comment]
See #2783

**Comment by lemonmojo** [comment]
@HenryJacques Thx for the pointer!
I'm closing this issue as it's a duplicate of the mentioned #2783.
