### ISSUE TITLE
Compilation error FreeRDP Android

### ISSUE THREAD

**Issue by SeethalakshmiAR** [FreeRDP/FreeRDP#2915]
I am trying to compile FreeRDP stable 1.1
I have followed the same steps as in Readme.Android

When I execute the "make" command I get the below error

[ 18%] Built target winpr-input
[ 18%] Building C object winpr/libwinpr/rpc/CMakeFiles/winpr-rpc.dir/rpc.c.o
/Users/lakshmi/Documents/FreeRDP1.1/FreeRDP-stable-1.1/winpr/libwinpr/rpc/rpc.c:31:26: fatal error: openssl/rand.h: No such file or directory
 #include <openssl/rand.h>
                          ^
compilation terminated.
make[2]: *** [winpr/libwinpr/rpc/CMakeFiles/winpr-rpc.dir/rpc.c.o] Error 1
make[1]: *** [winpr/libwinpr/rpc/CMakeFiles/winpr-rpc.dir/all] Error 2
make: *** [all] Error 2

Can anyone please help in resolving the error?

**Comment by bmiklautz** [comment]
@SeethalakshmiAR it seems you are missing openssl. Have a look into docs/README.android on how to install openssl.
