### ISSUE TITLE
Latest openssl version in FreeRDP

### ISSUE THREAD

**Issue by SeethalakshmiAR** [FreeRDP/FreeRDP#2916]
I am trying to compile freeRDP stable1.1 using latest version of openSSL for my Android client. 
When I try to follow the steps in README.Android, it works for fine for the openssl in the link given. 

Could anyone let me know on how to compile the latest openssl and use it in FreeRDP?

**Comment by bmiklautz** [comment]
@SeethalakshmiAR first of please use the mailing list or our irc channel for questions.
Regarding openssl:
You can basically use every statically build version of openssl that can be used with android. A lot of descriptions and howtos on how build openssl for android are floating around in the Internet. 
The openssl repositories and script referenced in README.Android are "prepared" to build exactly those required version. stable-1.1 is already quite old and therefore those scripts are not up to date.
If you have a look at the master branch you will find a script called android_setup_build_env.sh (in scripts) which prepares a rather recent build environment. I didn't try if this script works for stable-1.1 out of the box but you can use it as a starting point to build a recent openssl version. I think the referenced repository https://github.com/akallabeth/openssl-android.git supports the latest openssl version as well.

**Comment by SeethalakshmiAR** [comment]
When I build FreeRDP master, while trying to build the openSSL using the script in FreeRDP master scripts folder I get the following error. 

----------------------------------------
MBP-Retina-13-Mavericks:FreeRDP-master lakshmi$ ./scripts/android_setup_build_env.sh
Missing command line argument, current directory as root.
Using '/Users/lakshmi/Documents/OpenSSLCompile1/FreeRDP-master/external' as root.
Preparing OpenSSL...
Cloning into '/Users/lakshmi/Documents/OpenSSLCompile1/FreeRDP-master/external/openssl-build'...
remote: Counting objects: 138, done.
remote: Total 138 (delta 0), reused 0 (delta 0), pack-reused 138
Receiving objects: 100% (138/138), 22.18 KiB | 0 bytes/s, done.
Resolving deltas: 100% (60/60), done.
Checking connectivity... done.
Note: checking out '1.0.1h-fips-2.0.7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 2797897... Fixed wrong fips version in setenv-android-4.1.sh Now using gcc-4.8 toolchain to compile.
rm -rf openssl-fips-2.0.7
rm -rf openssl-1.0.1h
rm -rf fips
mkdir fips
wget http://www.opensslfoundation.com/fips/2.0/platforms/android/fipsld-crosscompile-fix
make: wget: No such file or directory
make: *** [fipsld-crosscompile-fix] Error 1
Failed to execute make command [2]

-----------------------------

Could you please help me resolve the error?

**Comment by bmiklautz** [comment]
@SeethalakshmiAR I think the script was only used and developed on Linux. On OS X either install wget or replace wget uses with curl.

**Comment by SeethalakshmiAR** [comment]
Thanks a lot for the support. I had tried the script with both FreeRDP master and stable 1.1, It works perfectly fine.
