### ISSUE TITLE
The issue of multimedia redirection

### ISSUE THREAD

**Issue by lumm** [FreeRDP/FreeRDP#2921]
There is a issue of mutimedia redirection.
When I connected my rdp server of windows 2008 server, played a mp4 media source. it could work well. I forced to disconnect the network, then re-login the rdp server. playing the same mp4 media source. it could not work well and the windows system sound can't be used. After I logout the windows server and login again. It could work well then.

**Comment by bmiklautz** [comment]
@lumm in order to get help you must provide us more information. Please have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting.
We at least need to know the following:
* What version are you using?
* What command line?
* Are you using ffmpeg or gstreamer?

**Comment by lumm** [comment]
1、I am using freerdp version 1.2.4-dev (git e45ebd8).
2、Command line is "xfreerdp -offscreen-cache /cert-ignore /f /network:lan /u:administrator /p:smartcloud +wallpaper +window-drag +menu-anims +themes +bitmap-cache /kbd:0x00000409 +compression /multimedia:sys:alsa /bpp:24 /printer /sound:sys:alsa,format:1 /microphone:sys:alsa /v:192.168.10.3（this is my rdp server）"
3、I am not sure ffmpeg or gstreamer used. How can I detect ffmpeg or gstreamer used. I alsa want to know what is the different of them.

**Comment by bmiklautz** [comment]
@lumm gstreamer and ffmpeg just two different "backend" implementation for the media redirection. If you build yourself check your build log what you've enabled and compiled in.

On the windows side what are you using for playing the mp4 back?

**Comment by lumm** [comment]
I think default is using ffmpeg.  I am not very sure because it was't built by myself.

On the windows side, I am using Windows Media Player which version is 12.0.7601.18840.

**Comment by lumm** [comment]
I am very sory for my mistake. The issue I posted a few hours ago. I said the command line is "xfreerdp -offscreen-cache /cert-ignore /f /network:lan /u:administrator /p:smartcloud +wallpaper +window-drag +menu-anims +themes +bitmap-cache /kbd:0x00000409 +compression /multimedia:sys:alsa /bpp:24 /printer /sound:sys:alsa,format:1 /microphone:sys:alsa /v:192.168.10.3".
 Actually, I am wrong. The command line is "xfreerdp -offscreen-cache /cert-ignore /f /network:lan /u:administrator /p:smartcloud +wallpaper +window-drag +menu-anims +themes +bitmap-cache /kbd:0x00000409 +compression /multimedia /bpp:24 /printer /sound:sys:alsa,format:1 /microphone:sys:alsa /v:192.168.10.3". When I add "sys:alsa" for "/multimedia" . The question is soluted.

Now my question is what is the different between "/multimedia" and "/multimedia:sys:alsa" ??

**Comment by jojonewnew** [comment]
Specified "sys:alsa" parameter would clearly let tsmf plugin to choose using ALSA as it's audio process device.

**Comment by lumm** [comment]
@bmiklautz @jojonewnew  Thank you very much for soluting my question. :)
