### ISSUE TITLE
rdp freezes

### ISSUE THREAD

**Issue by areal23** [FreeRDP/FreeRDP#2923]
Hello! sorry for my English...

When working in the FreeRDP sometime happened freezes pictures. That unfreezes need press ctrl+alt+del (task manager).

Our structures:
ON the thinclient 5.4 is a programs: freeRDP and vuescaner. FreeRDP connected to WindServer 2008.
That to go to the Scanner need press ctrl+alt+F4, after scanning scan, that to go to the FreeRDP neeed press ctrl+alt+F5....sometimes have freezes.  why???? That unfreezes need press ctrl+alt+del (task manager).

config rdp: /rfx /cert-ignore /sound:pulse +fonts /kbd:0x419 -bitmap-cache:off -offscreen-cache:off -glyph-cache:off"

**Comment by bmiklautz** [comment]
@areal23 what version of FreeRDP are you running on the thin client and what brand is it?

**Comment by areal23** [comment]
i enter the command by Putty: xfreerdp -version:
print:
....  [ERROR] com.freerdp.client.x11]....
This is FreeRDP version 1.2.1-dev (git d86124f)

**Comment by bmiklautz** [comment]
@areal23 could you paste the complete error?

**Comment by areal23** [comment]
xfreerdp -version
[18:54:01:610] [6207:6207] [ERROR][com.freerdp.client.x11] - failed to open display:
[18:54:01:610] [6207:6207] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.
This is FreeRDP version 1.2.1-dev (git d86124f)

**Comment by areal23** [comment]
@bmiklautz 
I left only option config rdp: /cert-ignore, freezes is not observed.  why?

**Comment by areal23** [comment]
freezes due to option - /rft

**Comment by hardening** [comment]
Lack of activity, let's close it.
