### ISSUE TITLE
Microphone redirection doesn't work

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#2931]
I am using FreeRDP (1.2.0_beta1+android9-1) on an Arch-based Linux distribution, GNOME 3 desktop environment and using Pulseaudio sound server. I am trying to connect to Windows 10 Enterprise RDP server. Audio redirection works fine after a while. Remote Audio is displayed both for audio recording and audio playing device. The microphone redirection is enabled in the group policy of the target machine.

I connect using command:

`xfreerdp /v:<server>:<port> /u:<user> /size:1366x768 /microphone /sound /rfx +decorations +wallpaper +fonts`

The following output is displayed on console:

`[15:34:41:201] [3221:3222] [ERROR][com.freerdp.legacy] - loading channel rdpdr`

`[15:34:41:201] [3221:3222] [ERROR][com.freerdp.legacy] - loading channel rdpsnd`

`[15:34:41:201] [3221:3222] [ERROR][com.freerdp.legacy] - loading channel drdynvc`

After logging in the following is being output:

`[15:47:46:030] [4233:4241] [ERROR][com.freerdp.channels.legacy] - Loading Dynamic Virtual Channel audin`

No futher messages are displayed when trying to use microphone.

**Comment by akallabeth** [comment]
Working on master (tested windows, X11, mac, android)
Can you confirm?

**Comment by BUGgs** [comment]
Not working if using /microphone:sys:alsa
Error: LoadLibraryA: /usr/local/lib/freerdp2/libaudin-client.so: cannot open shared object file: No such file or directory
Tried with today master.

**Comment by bmiklautz** [comment]
@BUGgs can you re-try with the last merges (some minutes ago)? - I just tested alsa and pulse and worked fine.

**Comment by akallabeth** [comment]
@BUGgs When compiling with dynamic channels, you need to do a ```make install``` too.

**Comment by BUGgs** [comment]
Just recompiled...still an error:
LoadLibraryA: /usr/local/lib/freerdp2/libaudin-client-.so: cannot open shared object file: No such file or directory
freerdp_load_channel_addin_entry did not return any function pointers for
audin_load_device_plugin alsa failed with error 1

**Comment by akallabeth** [comment]
@BUGgs What is your command line? How did you configure / install? Tested on debian jessie here, works nicely (all .so installed)

**Comment by akallabeth** [comment]
@BUGgs Ok, I can reproduce your issue now, check your cmake settings. Looks like you compiled without support for your desired audio backend.

**Comment by akallabeth** [comment]
closing due to lack of feedback.

**Comment by shaunsphere** [comment]
Recent Builds for Android: Microphone redirection doesn't work 
Before Aug 2016, it worked.
Ex: built from commit 90877f5acb61bdba5bf5a3cc4e7f42f42b0c51a2 (JAN 2017)
instal aFreeRDPl for samsung tablets, everything OK except Microphone Redirection.
