### ISSUE TITLE
Laggy video FreeRDP not responding

### ISSUE THREAD

**Issue by xgimp** [FreeRDP/FreeRDP#2935]
Hello, and sorry for my english

I have installed version 1.2.5-dev (git-d277346). sefcompiled with 

cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_X11=ON -DWITH_XINERAMA=ON -DWITH_CUPS=ON -DCHANNEL_PRINTER=ON . on Raspberry Pi 2 with Raspbian (ex. 2015-09-24-raspbian-jessie)

when I play YouTube video, picture is very laggy and freerdp not responding until end of video.

my script is:
xfreerdp /u:user /p:password /sec:nla /bitmap-cache /kbd:0x405 /v:serverIP

(Raspbian's version 1.1.0-beta1 is OK, however in this version fullscrean doesn't work.. Thats why I try compile newer version)

Have any Idea, what's wrong?

Thanks

**Comment by abma** [comment]
for me disabling bitmap-cache with: -bitmap-cache made it a lot more responsive and heavily reduced cpu load. does that help?

**Comment by xgimp** [comment]
thank for your response.
Yes it's little bit better. But still not ideal. I think it's maybe because of Raspberry Pi 2 performance?

**Comment by Hopedream** [comment]
没看懂

**Comment by Hopedream** [comment]
没看懂

**Comment by Hopedream** [comment]
没看懂

**Comment by Hopedream** [comment]
没看懂

**Comment by akallabeth** [comment]
Current master c325ec5325d0a7836ef706ee6872976be6a12850 has seen a lot of improvements (SSE and NEON optimized assembly to increase performance) but a raspberry will be too slow to decode 1920x1080 video data.
That is currently out of scope (requires hardware decoder support).

Oh, btw, always build with ```-DCMAKE_BUILD_TYPE=Release``` if you require performance.
