### ISSUE TITLE
FreeRDP disconnects Immediately after auth

### ISSUE THREAD

**Issue by thefonzz2625** [FreeRDP/FreeRDP#2937]
After successful auth, I recieve this message after I see the session launch for half a second.

I know this as I've tried with dummy credentials and I don't get this far.

[18:06:34:593] [25666:25667] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[18:06:34:593] [25666:25667] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[18:06:34:593] [25666:25667] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[18:06:34:219] [25666:25668] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive (static)
[18:06:34:219] [25666:25668] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service smartcard (static)
[18:06:34:219] [25666:25668] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer (static)
[18:06:34:219] [25666:25668] [ERROR][com.winpr.library] - LoadLibraryA: /usr/local/lib64/freerdp/libprinter-client.so: cannot open shared object file: No such file or directory
[18:06:34:219] [25666:25668] [INFO][com.freerdp.channels.rdpdr.client] - freerdp_load_channel_addin_entry failed!
[18:06:34:219] [25666:25668] [ERROR][com.freerdp.channels.rdpdr.client] - devman_load_device_service failed with error 1359!
[18:06:34:219] [25666:25668] [ERROR][com.freerdp.channels.rdpdr.client] - rdpdr_process_connect failed with error 1359!
[18:06:34:219] [25666:25667] [ERROR][com.freerdp.core] - rdpdr_virtual_channel_client_thread reported an error. Error was 1359
[18:06:34:219] [25666:25667] [INFO][com.freerdp.client.x11] - Network disconnect!
[18:06:34:219] [25666:25667] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

**Comment by bmiklautz** [comment]
@thefonzz2625 please have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting and add more details.

**Comment by thefonzz2625** [comment]
Invoked as: 

xfreerdp *rdp file from RDP server* /u:*username* /d:*domain* +clipboard /size:1600x850 /p:$(zenity --entry --title="Domain Password" --text="Enter your _password:" --hide-text) /cert-ignore /v:*host*

Connecting to Windows server 2013 

[andrew@localhost ~]$ xfreerdp --version
This is FreeRDP version 1.2.5-dev (git 7aca1e0)

Linux x64

cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_DEBUG_RDP=ON .



Let me know if you'd like any more detail.

**Comment by jojonewnew** [comment]
Hi, have you tried disable printer option?
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_DEBUG_RDP=ON -DCHANNEL_PRINTER=OFF -DCHANNEL_PRINTER_CLIENT=OFF

**Comment by thefonzz2625** [comment]
I hadn't. But I did just now. Even removed the old build, cloned a fresh build and tried it. Still tries to load the printer-client library for some reason. Although I'm not sure that's the source of the problem. I've seen it complain about that previously on other working systems and then load successfully.

Output is identical to first post.

**Comment by bmiklautz** [comment]
@thefonzz2625 if you see 
```
[18:06:34:219] [25666:25668] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer (static)
```
a later error like 
```
[18:06:34:219] [25666:25668] [ERROR][com.winpr.library] - LoadLibraryA: /usr/local/lib64/freerdp/libprinter-client.so: cannot open shared object file: No such file or directory
```
can safely be ignored.

**Comment by thefonzz2625** [comment]
Alright. The real problem is that the RDP session comes up for about half a second and then q

**Comment by thefonzz2625** [comment]
Do you need any other output?

**Comment by thefonzz2625** [comment]
It runs with the latest commit if I sudo it.

**Comment by bmiklautz** [comment]
@thefonzz2625 that sounds weird. So latest master works for you but only as root?

**Comment by thefonzz2625** [comment]
That is correct.

**Comment by bmiklautz** [comment]
@thefonzz2625 would you re-paste your complete command line please?

**Comment by thefonzz2625** [comment]
xfreerdp rdesktop.rdp /u:*Myusername* /w:1224 /h:650 /v:*rdphostname*

**Comment by thefonzz2625** [comment]
I have that in a .sh file, then I sudo rdeskop.sh .


Also, I have

xfreerdp /version
This is FreeRDP version 1.2.0-beta1 (git 1.2.0-beta1+android7-108-g9e17)

on another computer that does not suffer from this limitation. It was
cloned from git several months ago.

**Comment by bmiklautz** [comment]
@thefonzz2625 for me it sounds more like there is some installation/build problem on that particular computer. Could you also paste the content of your .sh file and the .rdp file for completeness?

**Comment by thefonzz2625** [comment]
[andrew@Andrew-PC ~]$ cat desktop.sh
#!/bin/bash
 xfreerdp rdesktop.rdp /u:*username* /w:1224 /h:650 /v:*hostname*
[andrew@Andrew-PC ~]$

[andrew@Andrew-PC ~]$ cat rdesktop.rdp
redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:0
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:0
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:*hostname*
workspace id:s:*hostname*
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.SessionCollectio
use multimon:i:0
alternate full address:s:*hostname*
signscope:s:Full Address,Alternate Full Address,Use Redirection Server
Name,Server
Port,GatewayUsageMethod,GatewayProfileUsageMethod,GatewayCredentialsSource,PromptCredentialOnce,RedirectDrives,RedirectPrinters,RedirectCOMPorts,RedirectSmartCards,RedirectClipboard,DevicesToRedirect,DrivesToRedirect,LoadBalanceInfo
signature:s:*signature*

**Comment by savingschampion** [comment]
Getting same error on Arch Linux using freerdp-git

**Comment by derekjc** [comment]
I'm facing the same issue. I changed the rdp file so that

    redirectprinters:i:1

becomes

    redirectprinters:i:0

and it works as expected. Perhaps that will help.

**Comment by bmiklautz** [comment]
@derekjc "libprinter-client.so" is buld if you have CUPS enabled read -DWITH_CUPS=ON.

Could you verify if this issue still exists with the current master branch or in the nightly packages (https://ci.freerdp.com/job/freerdp-nightly-binaries/ for Ubuntu and Debian).

**Comment by derekjc** [comment]
@bmiklautz Just tested the latest nightly for wily. Seems to work great! Let me test on another box running jessie in a bit

**Comment by derekjc** [comment]
@bmiklautz Tested in Jessie, works great!

Just to be sure, @thefonzz2625 can you also verify?

**Comment by agowa338** [comment]
I just cloned the repository and I'm having the same problem. If the rdp file contains the line "redirectprinters:i:1" it fails with exactly the same error message.
I followed this instructions to build it: https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-14.04
I'm using debian 9.0

**Comment by akallabeth** [comment]
Working on master, therefore closing.
@agowa338 seems to have compiled without printer support.
