### ISSUE TITLE
RDP protocol auth

### ISSUE THREAD

**Issue by John1984** [FreeRDP/FreeRDP#2942]
sorry for posting in issues.
i'm trying to understand how RDP protocol works.

can u tell me at what moment of connection sequence it's possible to understand that auth (user/passwd from CLIENT INFO PDU, auto-logon flag) failed?

i specify absolutely any data there and RDP servers eats it with no problem and give me response.

**Comment by hardening** [comment]
As someone told you on IRC there's a mailing list for such questions, the issue tracker is not the place. 
The answer can be found by reading the RDP specs, and "it depends". If you're doing NLA the authentication is done at the transport level so a failure will be notified by the fact that you can not establish the lower layer. With other transports, it's a little after during the negociation.
