### ISSUE TITLE
RemoteApp mode seg faults after connection, fails to connect in debug mode

### ISSUE THREAD

**Issue by tenspd137** [FreeRDP/FreeRDP#2943]
Hello,

I seem to be having trouble with app mode connecting to Windows 7.  I set up Windows 7 following http://geekswithblogs.net/twickers/archive/2009/12/18/137048.aspx and configuring the registry on my laptop for cmd.exe.

On my desktop Linux box (Gentoo amd64) when I try:

xfreerdp /u: <uname> /p: <pass> /app:"||cmd" or xfreerdp /u: <uname> /p: <pass> "/app:||cmd"

the session starts, I see the cmd.exe window very quickly and then get:
segmentation fault xfreerdp /u: <uname> /p: <pass> /app:"||cmd"

If I build with debug turned on, I get a bunch of trace data and it ends with:

 xfreerdp: /var/tmp/portage/net-misc/freerdp-1.2.1_pre20150326-r1/work/freerdp-1.2.1_pre20150326/client/X11/xf_client.c:600: xf_create_window: Assertion `!xfc->gc' failed.

abort xfreerdp /u: <uname> /p: <pass> /app:"||cmd"

I was hoping I would just get a "DOS prompt" but in both cases it failed.

my version of xfreerdp is:   FreeRDP version 1.2.1-dev (git n/a)

I am hoping that is enough - please let me know if you need other info.

**Comment by hardening** [comment]
This bug smells like something we have fixed some time ago, would you mind give a try with latest master ?

**Comment by tenspd137** [comment]
Sure - when I get a chance I'll get the latest source and do a build and give it a try.  I'll let you know what happens.

**Comment by tenspd137** [comment]
Aha - latest stuff works - thanks!

**Comment by tenspd137** [comment]
Quick question though - is there a way to run multiple remote apps?  It appears that when I connect to a second, it wants to stop the first.
