### ISSUE TITLE
urbdrc-client.so on ARM

### ISSUE THREAD

**Issue by xgimp** [FreeRDP/FreeRDP#2944]
Hello,

I'm using FreeRDP version 1.1.0-beta1 (git n/a) on Raspberry Pi 2 under Raspbian Wheezy. 

Linux raspberrypi 4.1.7-v7+ #817 SMP PREEMPT Sat Sep 19 15:32:00 BST 2015 armv7l GNU/Linux

It work well, but if I use /usb:auto, FreeRDP return this:

LoadLibraryA: /usr/lib/arm-linux-gnueabihf/freerdp/urbdrc-client.so: cannot open shared object file: No such file or directory

and yes. This library missing. So I checked this issue https://github.com/FreeRDP/FreeRDP/issues/864 and sucessfully compiled FreeRDP master with:

cmake -DCMAKE_BUILD_TYPE=Debug -DCHANNEL_URBDRC_CLIENT=ON .

However, library urbdrc-client.so still missing. It's there any way to get this library?

Thank you

**Comment by lumm** [comment]
you need to make sure that you have install the usb library to compile, like libudev and libuuid.

libudev stable: 1
-- Found UDev: /usr/local/lib/libudev.so
-- include: /usr/local/include
-- Found UUID: /usr/lib/i386-linux-gnu/libuuid.so
-- Found libusb-1.0:
-- - Includes: /usr/include/libusb-1.0
-- - Libraries: /usr/lib/i386-linux-gnu/libusb-1.0.so
-- Found all URBDRC dependencies

only you find this that means your dependencies are completed.

**Comment by dd-jacks** [comment]
All necessary libs are listed in #2667

**Comment by xgimp** [comment]
Thank you @dd-jacks. Now It works
