### ISSUE TITLE
RemoteApp window minimizes when on an inactive deskop

### ISSUE THREAD

**Issue by ariscop** [FreeRDP/FreeRDP#2946]
[video](https://youtu.be/PFNzbvk2wUM), Command line:
`./xfreerdp /v:[server] /clipboard /u:[domain user] /app:C:\\Windows\\System32\\cmd.exe`
Tested with the version in fedora 22 and current master

This happens for all applications, not just powershell
Interestingly though, while a command is writing to powershell it wont minimize

**Comment by akallabeth** [comment]
still an issue?

**Comment by akallabeth** [comment]
Closing, no feedback.
