### ISSUE TITLE
XFreeRDP: graphic output hangs, but mouse and keyboard input still works

### ISSUE THREAD

**Issue by frp** [FreeRDP/FreeRDP#2956]
## My system

```
$ xfreerdp --version
This is FreeRDP version 1.2.0-beta1 (git n/a)
```

This is the version from Fedora 22 repository.

Connecting to Windows 7 Professional with all last updates, using the following command:

```
$ xfreerdp /sec:rdp /v:<here-was-my-host> /f
```

(this is the minimal set of options with which I run it, adding clipboard and sound redirection options which I often use don't make any difference)
## The problem

Xfreerdp graphic output randomly hangs (sometimes it works all day well, sometimes it hangs every 10 minutes) in a pretty unusual way: graphic output is stuck, but whatever actions I do using my keyboard or mouse, are actually done on the remote computer, which means the TCP connection isn't broken. I mean, if it hang when I was typing some text in some field, and I continue typing, after reconnecting, I'll see all the text.

**Comment by thefonzz2625** [comment]
Yeah. I'm having the same problem. I have another issue open where I need to sudo in order to connect.

Version: This is FreeRDP version 1.2.5-dev (git b83356a)

Can't attach strace -- even after tar.gz'ing it -- 55mb.

**Comment by bmiklautz** [comment]
@frp @thefonzz2625 can you verify if this problem also exists with the current master. Package for Fedora is available from https://ci.freerdp.com/job/freerdp-nightly-rpm-mock/

**Comment by thefonzz2625** [comment]
So far so good. The real test is whether it will last between several
reboots. I'll be sure to let you know.

Thanks :)

On Tue, Nov 17, 2015 at 7:19 AM, Bernhard Miklautz <notifications@github.com

**Comment by frp** [comment]
Seems good, I didn't get a problem in a while. Thanks :+1:
