### ISSUE TITLE
is it possible to use Linux as a FreeRDP server?

### ISSUE THREAD

**Issue by jawz101** [FreeRDP/FreeRDP#2960]
I see vague reference to it and very sparce instructions on various Ubuntu forums.  If it's even possible the instructions I've seen (elsewhere) are several years old.  If it is indeed possible- even in an experimental state- can some documentation be written up somewhere?  Not "read the source code" I mean legitimate documentation.  Even if it isn't up to snuff it would be nice to see how it does in its current state because Linux needs a remote control solution that doesn't suck.

**Comment by bmiklautz** [comment]
@jawz101 for questions please don't use the issue tracker but rather our mailing list or the irc channel.

Anyways. FreeRDP comes with a shadow server that can be used to share a already running X11 session. But it is not a full featured RDP server that also launches x11/... session.
There are currently two projects xrdp and FreeRDS that (partially) use FreeRDP and are a full RDP server for Linux.

**Comment by jawz101** [comment]
Thanks.  Sorry for the improper question
