### ISSUE TITLE
corrupted text with long lines / duplicate lines (glyph-cache)

### ISSUE THREAD

**Issue by abma** [FreeRDP/FreeRDP#2967]
xfreerdp sometimes corruptes screen / char(s):

screenshot taken from xfreerdp from the host:
![screen-corruption](https://cloud.githubusercontent.com/assets/301564/10970371/861bbb3c-83ce-11e5-9513-f9ca6fd75a23.png)

thats how it should look like (screenshot taken from inside session)
![screenshot-insidesession](https://cloud.githubusercontent.com/assets/301564/10970378/8d85469a-83ce-11e5-83a1-20b38983e2f9.png)

it seems that it happens more likely when lines are very long and duplicate lines occur.

initially found in a putty window, but seems to be reproduceable in most text applications.

text used here was:

[Thu Nov 05 13:08:11.192212 2015] [access_compat:error] [pid 13037] [client 127.0.0.1:47955] AH01797: client denied by server configuration: /var/www/snom715/

(for copy and paste)

**Comment by bmiklautz** [comment]
@abma what version you are reporting this issue for?

**Comment by abma** [comment]
16069e69e5f0bcae76f280c4bdde89a825d1f8c1, but seems to happen in current master version, too.

**Comment by bmiklautz** [comment]
@abma could you re-try with the different caches disabled?
```
-bitmap-cache  -glyph-cache -offscreen-cache
```

**Comment by abma** [comment]
with -glyph-cache it seems to work without curruption, the other parameters have no effect.

**Comment by abma** [comment]
related to #2922 / maybe a duplicate

**Comment by abma** [comment]
can't reproduce with current version.

https://github.com/FreeRDP/FreeRDP/commit/bd7ed27f92747adbd13f5f89e7abcf4cffa07386

**Comment by bmiklautz** [comment]
@abma can this issue be closed then?

**Comment by abma** [comment]
yep

**Comment by HenryJacques** [comment]
@abma does it still work with the different caches enabled?
(with +bitmap-cache  +glyph-cache +offscreen-cache)
