### ISSUE TITLE
(minor) memleak in /libfreerdp/core/orders.c:1815

### ISSUE THREAD

**Issue by abma** [FreeRDP/FreeRDP#2969]
addresssanitizer reports a small memleak on exit:

==2884==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    0 0x7f871fbc5d2a in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98d2a)
    1 0x7de1fb in update_read_polygon_cb_order FreeRDP/libfreerdp/core/orders.c:1815
    2 0x7f2747 in update_recv_primary_order FreeRDP/libfreerdp/core/orders.c:3381
    3 0x7f6688 in update_recv_order FreeRDP/libfreerdp/core/orders.c:3722
    4 0x66175e in fastpath_recv_orders FreeRDP/libfreerdp/core/fastpath.c:205
    5 0x661cc1 in fastpath_recv_update FreeRDP/libfreerdp/core/fastpath.c:265
    6 0x6630a6 in fastpath_recv_update_data FreeRDP/libfreerdp/core/fastpath.c:432
    7 0x664701 in fastpath_recv_updates FreeRDP/libfreerdp/core/fastpath.c:563
    8 0x65c5c7 in rdp_recv_fastpath_pdu FreeRDP/libfreerdp/core/rdp.c:1263
    9 0x65c6b0 in rdp_recv_pdu FreeRDP/libfreerdp/core/rdp.c:1271
    10 0x65d3d2 in rdp_recv_callback FreeRDP/libfreerdp/core/rdp.c:1387
    11 0x66f0a8 in transport_check_fds FreeRDP/libfreerdp/core/transport.c:780
    12 0x65dacc in rdp_check_fds FreeRDP/libfreerdp/core/rdp.c:1444
    13 0x63bd5b in freerdp_check_fds FreeRDP/libfreerdp/core/freerdp.c:220
    14 0x63c22b in freerdp_check_event_handles FreeRDP/libfreerdp/core/freerdp.c:262
    15 0x466423 in xf_client_thread FreeRDP/client/X11/xf_client.c:1595
    16 0x935623 in thread_launcher FreeRDP/winpr/libwinpr/thread/thread.c:315
    17 0x7f871b6d26a9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76a9)

**Comment by bmiklautz** [comment]
@abma thanks for the report but unfortunately this is not really helpful for us without the version (git), command line (maybe also valgrind) and the server you are connecting to. Often the leaks happen only in special situations or combinations..

**Comment by abma** [comment]
thats from the most recent commit in master branch...

**Comment by bmiklautz** [comment]
@abma not something one could guess from the report though ;)

**Comment by abma** [comment]
yeah, sorry, to make it useful in the future with a git hash:
https://github.com/FreeRDP/FreeRDP/blob/b83356a0b3a6cd6d82588824c5b428638337934a/libfreerdp/core/orders.c#L1815

**Comment by bmiklautz** [comment]
@abma thanks. Can you give some details on how to reproduce this. I just tried to reproduce this leak somehow but without success.

**Comment by abma** [comment]
to reproduce, i have to start it:

    $ xfreerdp /v:server /sec:tls -glyph-cache

and then logout inside the session.

[20:26:54:177] [5676:5677] [ERROR][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
[20:26:54:177] [5676:5677] [ERROR][com.freerdp.core.rdp] - DisconnectProviderUltimatum: reason: 3

i don't always get this memleak always, only sometimes. i guess the longer the session, the chance is higher...

**Comment by abma** [comment]
"long" is a minute

**Comment by akallabeth** [comment]
Fixed on current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
