### ISSUE TITLE
Dual Screen not working correctly

### ISSUE THREAD

**Issue by davidleake** [FreeRDP/FreeRDP#2977]
I recently updated the version of FreeRDP that we are using.  In the process I found that Dual screen operation is broken.  The 2nd monitor does not show what should be on the desktop.  I can drag an Icon or window on to the other screen but it is not visible.  I found that the check in 719a0fd3e9877cc9f0c2031d0e68fc5680834c9c  (Thu Mar 12 07:27:29 2015 -0400) is where the break happens.

**Comment by bmiklautz** [comment]
@davidleake did you test with the latest master already? There were recent changes regarding multimon.

**Comment by nfedera** [comment]
@davidleake in case it fails with current master please also let us know which window manager you're using, to which rdp server you're connection (the remote Windows version/edition) and your exact xfreerdp command line.

**Comment by davidleake** [comment]
I have tried it with the current master.  We are using a derivative of the icewm as our WM.  I have connected to Server 2008R2, Windows 8, and Server 2012 all with the same results.

command line is 
xfreerdp /t:rdp-win8fx /v:win8fx -grab-keyboard /gdi:hw /sound:sys:alsa /microphone:sys:alsa /cert-ignore -sec-nla -toggle-fullscreen /drive:TCshare-sdb1,/media/sdb1 /bpp:24 /network:lan +aero +window-drag +menu-anims +compression /multimon /monitors:0,1 /f

I have also tried just to
xfreerdp /t:rdp-win8fx /v:win8fx  /multimon /monitors:0,1 /f

**Comment by nfedera** [comment]
@davidleake I think this is a dulicate of issue #2707. Icewm does not support the NET_WM_FULLSCREEN_MONITORS property.
For a detailed explanation see https://github.com/FreeRDP/FreeRDP/issues/2707#issuecomment-153721965)
