### ISSUE TITLE
Issue with Connection Broker Redirection Windows Server 2012 R2 Remote Desktop Services

### ISSUE THREAD

**Issue by niu-cbeard** [FreeRDP/FreeRDP#2978]
Hello,

We have identified an issue with freerdp when connecting to a Windows Server 2012 R2 RDS Cluster. In our environment we are connecting from a RHEL6.7 server to two Server 2012 servers in a collection, serving a number of remoteapps. Whenever a redirect event occurs due to a load balancing decision or to connect a user to an existing cached session we see the connection establish followed by the below stack trace:
[freeRDP.txt](https://github.com/FreeRDP/FreeRDP/files/36490/freeRDP.txt)

We have configured the broker role on a single server and on both servers and see the same behaviour in both cases. Restarting the RDS Connection Manager allows freerdp to successfully connect to either server, any attempts following this behave as described above. We believe this shows that the RDS collection is correctly handling the connection but redirection is not being handled by freerdp.

Would it be possible for someone to advise whether freerdp supports redirection of RDP connections in this case?

Best Regards,

Chris

**Comment by bmiklautz** [comment]
@niu-cbeard what version of FreeRDP are you using?

**Comment by niu-cbeard** [comment]
Hi, Originally we were using the version in RHEL's yum repo 1.0.2-2. We have upgraded to the latest pre-release 1.1.0-beta1 but we are still seeing the same issue.

**Comment by bmiklautz** [comment]
@niu-cbeard if you compiled yourself give master a try. We currently don't have any nightly RHEL packages due to the lack of RHEL build machines ;(

**Comment by niu-cbeard** [comment]
@bmiklautz Ok, we'll give that a go. We have put a work around in place in the short term by configuring each RDS server as a connection broker with their own collections and sending requests directly to each node. To do this we have implemented some very basic load balancing within our application, this isn't as scalable as we would like it to be though. I'll post again once we have some results back from using the current master. Many thanks for your help!

**Comment by username-is-already-taken2** [comment]
Hi there, does anyone know if this issue has now been resolved?  Thanks in advance

**Comment by hardening** [comment]
@username-is-already-taken2 we're waiting for feedback too ;)

**Comment by akallabeth** [comment]
The segfault should long be gone and with #4548 redirection should be working properly.

**Comment by akallabeth** [comment]
Connection Broker setups are working with server 2016 setups we have running, assuming fixed.
