### ISSUE TITLE
Cannot install package with vlc on Ubuntu 14.04

### ISSUE THREAD

**Issue by OxyOss** [FreeRDP/FreeRDP#2985]
Hi there,

I'm having an issue where I want the latest FreeRDP from the PPA, and I can either install that or the VLC packages from Ubuntu - but not both.

I'm continually seeing that there is a dependency issue between FreeRDP packages and vlc-nox - libfreerdp1 is not able to be installed due to the available versions.

Can this be fixed easily?  My Google foo has been poor with this. :(

This is using the PPA from here:
deb http://ppa.launchpad.net/ikuya-fruitsbasket/freerdp/ubuntu trusty main

Regards,

Russell.

**Comment by bmiklautz** [comment]
@OxyOss that's nothing we can do much about. I doubt the PPA you are using is official and if it does daily builds dependencies will break.
If you don't have any special requirement for this special PPA you can use your nightly builds (https://ci.freerdp.com/job/freerdp-nightly-binaries/). Those are based on master and are installed in /opt/freerdp-nightly and therefore shouldn't cause any dependency problems.
