### ISSUE TITLE
RemoteApp gives me only a black screen (RemoteDesktop works fine)

### ISSUE THREAD

**Issue by Utini2000** [FreeRDP/FreeRDP#2988]
Hey there, I am on Arch Linux running a Windows 7 Ultimate VM in QEMU/KVM.
FreeRDP version: https://www.archlinux.org/packages/community/x86_64/freerdp/

I can connect to it with the following command just fine:
sudo xfreerdp /u:Vbox /p:pw_here /admin /cert-ignore +clipboard /v:192.168.122.149  

But this gives me only a big black screen:
sudo xfreerdp /u:Vbox /p:pw_here /admin /cert-ignore +clipboard /app:||calc /v:192.168.122.149  

I also tried creating the registry "fAllowUnlistedRemotePrograms" but still no luck.

Any ideas? :/ Thanks

**Comment by bmiklautz** [comment]
@Utini2000 may I ask why you are using sudo? I'd also suggest to use ' (single quotes) around the app like /app:'||calc'

Also could you add what version of xfreerdp you are using?

**Comment by Utini2000** [comment]
You are right, I shouldn't use sudo and don't even know why I used it. Thanks !
Version: freerdp 1:1.2.0_beta1+android9-1 ... from: https://www.archlinux.org/packages/community/x86_64/freerdp/

Running: xfreerdp /u:Vbox /p:lala /admin /cert-ignore +clipboard /app:'||calc' /v:192.168.122.149 
Still gives me the same problem.
I made a video showing what is happening: http://files.bestmail.ws/simplescreenrecord1.mp4

**Comment by Utini2000** [comment]
@bmiklautz nothing? :(

**Comment by Utini2000** [comment]
Oh und liebe grüße aus wien 22 ;P

**Comment by bmiklautz** [comment]
@Utini2000 I did a similar test against windows 7 with the latest nightly (the machine runs in Hyper-V but that shouldn't actually matter):
```
xfreerdp /u:user /p:password /admin /cert-ignore +clipboard /app:'calc.exe' /v:win7-test
```
 Worked for me as expected.

**Comment by Utini2000** [comment]
@bmiklautz well I tried it again today:

xfreerdp /u:Vbox /p:lala /admin /cert-ignore +clipboard /app:'calc.exe' /v:192.168.122.149

gives me just a big black screen... did you set/change anything in windows 7 itself ?

Thanks !

**Comment by bmiklautz** [comment]
@Utini2000 no stock windows 7. No change at all. But as said I've tested with the latest nightly build that  I guess is more recent than the 1.2.x in arch.

**Comment by Utini2000** [comment]
@bmiklautz  Hmm I asked the arch package maintainer to update the package.. maybe he will do it. Anything else I can try or help troubleshooting ? :/ Thanks again !

**Comment by bmiklautz** [comment]
@Utini2000 unfortunately we don't have any nightly packages for Arch. But you could try to compile yourself and test if the latest master fixes the problem for you.

**Comment by admiralakber** [comment]
@Utini2000 What desktop environment are you using? I am using the same set up as you, and can repeat this issue if I use MATE - other desktop environments work for me. See: https://github.com/FreeRDP/FreeRDP/issues/3000

**Comment by Utini2000** [comment]
@admiralakber oh please let this be the key to this problem... I am on Arch + GNOME.. Is GNOME causing the troubles? :(

**Comment by Utini2000** [comment]
Today there was an update for freerdp on Archlinux... it fixed the problem ! :)

**Comment by bmiklautz** [comment]
@Utini2000 would you add the version that fixes this problem for you on Archlinux (xfreerdp --version)?
This means the issue can be closed?

**Comment by Utini2000** [comment]
Version: freerdp 1:1.2.0_20160107-2
Link: https://www.archlinux.org/packages/community/x86_64/freerdp/

Yes this issue can be closed ! I am glad that it finally works ;)

**Comment by fread2281** [comment]
I'm having a similar issue, it seems to be https://serverfault.com/questions/220437/remote-desktop-connection-screen-is-totally-black-but-server-is-working-perfectl, not unique to freerdp. `-bitmap-cache` fixes it for me

**Comment by pohlt** [comment]
I had a similar issue (black screen) with KDE, freerdp 2.2.0.
My observation: Sometimes it takes a few minutes(!) until the black screen is replaced with the expected content and everything works fine after this delay.
