### ISSUE TITLE
xfreerdp give me a black screen

### ISSUE THREAD

**Issue by ygqzwl** [FreeRDP/FreeRDP#2990]
the client
1. xfreerdp -version
This is FreeRDP version 2.0.0-dev (git c63928f)

2.uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
3. linux system is centos7

4.use Multimedia Redirection, gstreamer_0_10

the server
1.system is  windows_7_enterprice on kvm-qemu
2.use windows media player,   playbak xxx.wmv

when i run the command  :  ./xfreerdp -u usename -p password --plugin drdynvc --data tsmf -- ip

it only gives me a black screen...

**Comment by ygqzwl** [comment]
add

when i run the command : ./xfreerdp -u usename -p password --plugin drdynvc --data tsmf -- ip

and used window media player playback xxx.wmv, it only gives me a black screen

**Comment by hardening** [comment]
Hum it's possible that the remote codec is not supported locally, would you mind activate the TSMF debug in your build ?
Other possibility: a bug with gstreamer_0_10, it's the old version isn't it ?

**Comment by ygqzwl** [comment]
1.how to activate the TSMF debug on my build? where can search the debug logs?

2.when I use gst-launch playback xxx.wmv, it works,so i donot think it is the gstreamer problem...

**Comment by ygqzwl** [comment]
when I playbak the xxx.wmv, appear debug errors:

[ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PLAYING) GST_STATE_CHANGE_ASYNC.
[19:06:26:904] [3715:3780] [ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PAUSED) GST_STATE_CHANGE_ASYNC.
[19:06:26:904] [3715:3780] [ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PLAYING) GST_STATE_CHANGE_ASYNC.
[19:06:26:904] [3715:3780] [ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PAUSED) GST_STATE_CHANGE_ASYNC.
[19:06:26:904] [3715:3780] [ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PLAYING) GST_STATE_CHANGE_ASYNC.

how to deal it ?

**Comment by Mandar-Shinde** [comment]
@ygqzwl you can try with below command

 ./xfreerdp -u usename -p password --plugin drdynvc --data tsmf:decoder:gstreamer -- IP
