### ISSUE TITLE
freerdp making me crazy,tried everything ...

### ISSUE THREAD

**Issue by Prostu2** [FreeRDP/FreeRDP#2992]
[ 44%] Building C object libfreerdp/locale/CMakeFiles/freerdp-locale.dir/keyboard_xkbfile.c.o
/home/x/freerdp/FreeRDP/libfreerdp/locale/keyboard_xkbfile.c:41:36: fatal error: X11/extensions/XKBfile.h: No such file or directory
compilation terminated.
make[2]: *** [libfreerdp/locale/CMakeFiles/freerdp-locale.dir/keyboard_xkbfile.c.o] Error 1
make[1]: *** [libfreerdp/locale/CMakeFiles/freerdp-locale.dir/all] Error 2
make: *** [all] Error 2

**Comment by bmiklautz** [comment]
@Prostu2 I don't know what version you are trying to compile and on what distribution but I'm fairly sure you miss a build dependency. On Debian/Ubuntu the required package is called libxkbfile-dev.
