### ISSUE TITLE
Problems with /dualmon after ctrl + alt + enter

### ISSUE THREAD

**Issue by emssik** [FreeRDP/FreeRDP#2993]
Hi,

From:
Ubuntu 15.10,
4.2.0-18-generic #22-Ubuntu SMP Fri Nov 6 18:25:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
NVIDIA binary driver 352.63
FreeRDP version 1.1.0-beta1 (git n/a)

To:
Windows 10 Pro

By:
xfreerdp /u:xxx /multimon /v:yyy /network:broadband-low -wallpaper -themes /bpp:16bit /compression
or only xfreerdp /u:xxx /multimon /v:yyy no matter really.

Connection is ok, I can work correctly on both monitors, till I use ctrl+alt+enter for back to a "window mode". In this moment, screens from my both monitors are compressed and rescaled to the only 1/2 size of my first monitor. They are stay this way, after I use ctrl+alt+enter again, for resize to a full screen mode.

Regards

Daniel Roziecki

**Comment by bmiklautz** [comment]
@emssik can you please redo your test with the latest nightly builds (https://ci.freerdp.com/job/freerdp-nightly-binaries/)?

**Comment by emssik** [comment]
Now is ok, thx,

Regards

Daniel Roziecki

2015-11-30 11:45 GMT+01:00 Bernhard Miklautz <notifications@github.com>:
