### ISSUE TITLE
VIDEO: (PAUSED) GST_STATE_CHANGE_ASYNC

### ISSUE THREAD

**Issue by ygqzwl** [FreeRDP/FreeRDP#2994]
the client
1. xfreerdp -version
This is FreeRDP version 2.0.0-dev (git c63928f)

2.uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
3. linux system is centos7

4.use Multimedia Redirection, gstreamer_0_10

the server
1.system is windows_7_enterprice on kvm-qemu
2.use windows media player, playbak xxx.wmv

when i run the command : ./xfreerdp -u usename -p password --plugin drdynvc --data tsmf -- ip

and used window media player playback xxx.wmv, it gived me the run errors:
VIDEO: (PAUSED) GST_STATE_CHANGE_ASYNC.
[09:19:19:128] [8075:8079] [ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PLAYING) GST_STATE_CHANGE_ASYNC.
[09:19:19:129] [8075:8079] [ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PLAYING) GST_STATE_CHANGE_ASYNC.

and gives me a black screen,   how to deal the run errors???

**Comment by hardening** [comment]
I have tested here, and I can't reproduce the black screen (video playing normally).
Anyway, if I pause and stop the video, I can't get rid of the last picture, the only way is to kill window media player. Perhaps that's related to what you're experimenting ?

**Comment by ygqzwl** [comment]
@hardening   can you tell me how to test it?
1.what gstreamer plugins need to installed if i want to use the gstreamer to playback???
2.makefile or cmakelist is need to modify???
3. what is "the run error VIDEO: (PLAYING) GST_STATE_CHANGE_ASYNC.  " means??? 


can you provide me your test steps and installed rpms ?(the more detailed the better)

thanks a lot.

**Comment by ygqzwl** [comment]
@hardening 
can you share me the detail steps you tested???
1.which rpms need to install?
2.which code source or makefile need to modify?
3.which rpms need to install on the server?
thanks a lot for you help

**Comment by hardening** [comment]
@ygqzwl I'm running (the client) on Ubuntu so I don't have the rpm list in mind, but you may find what is needed on the FreeRDP wiki. Configuration is done by either giving flags to cmake (-Dflags=value) or (my favorite method) by using ccmake. 
Are you sure you have a compiled backend in your FreeRDP, that would explain easily the black screen ;)

**Comment by ygqzwl** [comment]
@hardening 
 today, I use it to playback xxx1.mp4, it can works, but it is very nonfluency.
when i play another xxx2.mp4, it gives me the black screen.
i feel it so difficult to use Multimedia Redirection...

**Comment by Mandar-Shinde** [comment]
@ygqzwl playing media on regular hardware wont get you any boost. If you play normal video of 144p or 320p your video may work fine, but as you go to higher range HD or 4K it will just give up.

also check
https://github.com/FreeRDP/FreeRDP/issues/2990
