### ISSUE TITLE
xfreerdp--- Multimedia Redirection---running errors

### ISSUE THREAD

**Issue by ygqzwl** [FreeRDP/FreeRDP#2995]
the client
1. xfreerdp -version
This is FreeRDP version 2.0.0-dev (git c63928f)

2.uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
3. linux system is centos7

4.use Multimedia Redirection, gstreamer_0_10

the server
1.system is windows_7_enterprice on kvm-qemu
2.use windows media player, playbak xxx.wmv

when i run the command : ./xfreerdp -u usename -p password --plugin drdynvc --data tsmf -- ip

and used window media player playback xxx.wmv, and gives me a black screen, and it gived me the run errors:
[09:19:19:128] [8075:8079] [ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PLAYING) GST_STATE_CHANGE_ASYNC.
[09:19:19:129] [8075:8079] [ERROR][com.freerdp.channels.tsmf.client] - VIDEO: (PLAYING) GST_STATE_CHANGE_ASYNC.

used window media player playback xxx.mp4, and gives me only the first frame?

**Comment by Mandar-Shinde** [comment]
@ygqzwl Please check https://github.com/FreeRDP/FreeRDP/issues/2990
