### ISSUE TITLE
smartcard not working when trying to connect to windows 2012 server

### ISSUE THREAD

**Issue by jjgalvez** [FreeRDP/FreeRDP#2999]
I am on Linux 14.04
using libccid version 1.4.20 and the nightyly build of freerdp (currently 2.0.0+0~20151204024832.193~1.gbpb58807)
I am trying to connect with the following command: /opt/freerdp-nightly/bin/xfreerdp /d:<domain> /u:<user> /size:1920x1130 /smartcard: /v:<url>

when I connect I am given the option to sign with with my smartcard which works, it read the credentials and logs me in, however as soon as I log in I get teh following error [23:33:45:516] [30888:31292] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardConnectW (0x000900B0), status: SCARD_E_NO_SMARTCARD (0x8010000C) 
and I can't use the smartcard to access anything with IE.  If I do the same thing through windows10 (virtualbox) it works as expected.

What can I do to get this to work directly from linux

**Comment by jjgalvez** [comment]
ping? any way to get smartcards working?

**Comment by akallabeth** [comment]
@jjgalvez 
* Did you try ```/smartcard``` without ```:``` at the end?
* You can enable more extensive logging by setting the ```export WLOG_LEVEL=trace``` to get some more details on your specific issue.
*  There are 2 pull requests for smartcards pending (#2749 and  #2959) which may improve smartcard support for you. This will require you to build yourself from source

**Comment by jjgalvez** [comment]
Thank you I'll try those
Jose

**Comment by jjgalvez** [comment]
would those pull requests be in any of the nightly builds?

**Comment by akallabeth** [comment]
no, nightlies are build from current master only.
you would have to compile your own version to get these.

**Comment by jjgalvez** [comment]
got it thanks I'll give compiling it a try
Jose

**Comment by jjgalvez** [comment]
compiled it and I'm still getting the sharing violation error. I really 
don't know how to debug this. is there anything you want me to do to help?

Jose

**Comment by akallabeth** [comment]
#4312 fixed a bunch of smartcard related issues bringing it to a usable state again.
Reopen, if your specific issue was not fixed.
