### ISSUE TITLE
RemoteApp not working with MATE

### ISSUE THREAD

**Issue by admiralakber** [FreeRDP/FreeRDP#3000]
### Background

OS: Arch Linux
DE: MATE
Kernel: `4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux`
FreeRDP version: `This is FreeRDP version 1.2.0-beta1 (git n/a)`
RDP Host: Windows 7 Ultimate 64 bit in KVM
### Issue

Command: `xfreerdp /u:user /p:pass /app:'explorer.exe' /v:server`

Command works and gives a nice explorer window in desktop environments: GNOME 3, i3, and 'xterm' i.e. startx with nothing. In MATE, it does not.
### Detail

If I am logging in (via RDP) for the first time using the above command in MATE, a maximized black FreeRDP window hangs. It does not reduce to an explorer window. 
Also, unlike in other window managers the command reports back:
`Server does not support XI 2.2`

However, once logged in but simply disconnected, once running the above command again does not produce any windows.

**Comment by Utini2000** [comment]
I have exactly the same issue on Arch + GNOME :/ I also have bumblebee installed if that changes anything.

**Comment by bmullan** [comment]
I'm facing this problem also with RemoteApps not working correctly.
Ubuntu 15.10 amd64 
32GB ram
8core cpu
standard ubuntu unity 7 desktop environment.

this works okay and presents a full workable desktop...
xfreerdp /u:userID /p:userPWD  /v:IP_of_Win7Ultimate_VM

this does **not** ...
xfreerdp /u:userID /p:userPWD  /app:'explorer.exe' /v:IP_of_Win7Ultimate_VM

It **does** bring up Explorer in its own window but the mouse does **not** work in the remoteapp window?

$ xfreerdp --version
This is FreeRDP version 1.1.0-beta1

**Comment by hardening** [comment]
@admiralakber, @Utini2000 it's quite hard to debug anything when we don't have the git version that Arch is shipping... Perhaps you could give a try with latest master (recompiled) and tell us if things are better.

@bmullan we have made significant changes since 1.1, would you give a try with the latest version ?

**Comment by bmullan** [comment]
@hardening - thanks... I'd gotten the prev from the download off the freerdp page
but pulling the latest from github & building it resulting in a v2.0 dev release and that **does** work for freerdp remoteapp .. thanks!

**Comment by hardening** [comment]
@Utini2000 @admiralakber anything new ? @bmullan seems happy with upstream...

**Comment by akallabeth** [comment]
Closing as resolved.
Reopen if still an issue.
