### ISSUE TITLE
xfreerdp--gstreamer---playback is not smooth

### ISSUE THREAD

**Issue by ygqzwl** [FreeRDP/FreeRDP#3002]
the client
1. xfreerdp -version
This is FreeRDP version 2.0.0-dev (git c63928f)

2.uname -a
Linux localhost.localdomain 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
1. linux system is centos7

4.use Multimedia Redirection
1. use gstreamer_0_10

the server
1.system is windows_7_enterprice on kvm-qemu
2.use windows media player, playbak xxx.mp4

when i run the command : ./xfreerdp -u usename -p password --plugin drdynvc --data tsmf -- ip      and used window media player playback xxx.mp4:

1.playback is not smooth

2.playback screen is vague

3.I print the ON_SAMPLE messages, and  the startTime and endTime is not time sequence, for example:
sample1-- start_time : 0        end_time:100
sample2-- start_time : 200    end_time:300
sample3-- start_time : 100    end_time:200

the gstreamer-playback  use the message : sample1--->sample2-->sample3

**Comment by Mandar-Shinde** [comment]
@ygqzwl please check solution on
https://github.com/FreeRDP/FreeRDP/issues/2990
