### ISSUE TITLE
Error message for an expired password with NLA

### ISSUE THREAD

**Issue by HenryJacques** [FreeRDP/FreeRDP#3003]
Hello,

When connecting to a Windows host using NLA and if the password has expired, the error is the same as if the password was wrong.
That seems "reasonable" because the authentication happens at the network level even before the session starts.

However, wouldn't it be possible to get a more specific message if the password has expired? Is the error code received from the Windows host at least different from the message if the password is wrong?

The ticket #1510 was quickly closed because the user switched back to RDP security but that's not possible on my Windows 2012-R2 RDS farm (and besides it doesn't solve the initial problem, which is to detect that the password is expired and not wrong)

On what I saw on internet about this subject, the conversation immediately goes to "even on Windows 7 or 2008 you cannot change an expired password with NLA" (https://support.microsoft.com/en-us/kb/2648397)
Yes right, I know you cannot change the password with NLA and that is not what I want to do. I only want FreeRDP to give to an consistent error message. Is this doable?

Thanks in advance :)

**Comment by hardening** [comment]
Looks like https://github.com/FreeRDP/FreeRDP/pull/2824 is related, as we possibly get a different SSL error code in this case.

**Comment by HenryJacques** [comment]
I'm using compiled version of xfreerdp and the patch in #2824 but when connecting to a Windows 7 or 2012-R2 with an account that has an expired password I got the following error:
ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]

**Comment by hardening** [comment]
@HenryJacques could modify the patch to print the error in libfreerdp/core/transport.c (ssl callback), so that we possibly have more values for the ret arg ?

**Comment by HenryJacques** [comment]
@hardening I'd love to but I'm really not sure where to put this... :(

**Comment by HenryJacques** [comment]
@hardening All right, I think i get it. In ```transport_ssl_cb``` you want me to print the ```transport->LastError``` value?

**Comment by hardening** [comment]
@HenryJacques nope, in _transport_ssl_cb_ I'd like to see the _where_ and _ret_ values.

**Comment by HenryJacques** [comment]
@hardening sorry for the delay:
where: 4004 -> SSL_CB_READ_ALERT        (SSL_CB_ALERT|SSL_CB_READ)
ret: 592 -> " IE "/"internal error"  (see http://linux.die.net/man/3/ssl_alert_type_string)

**Comment by akallabeth** [comment]
Error handling has improved (kerbero shandling, etc).
Reopen if still an issue.
