### ISSUE TITLE
USB redirection error processing arguments

### ISSUE THREAD

**Issue by cleric333** [FreeRDP/FreeRDP#3004]
system shows 

com.freerdp.channels.urbdrc.client error processing arguments

somebody experienced the same issue? Some ideas?

**Comment by HenryJacques** [comment]
What was the command line you've used?

**Comment by cleric333** [comment]
nothing special just add /usb:auto

**Comment by cleric333** [comment]
the USB device was mounted automatically, and I am able to control all data in the folder

**Comment by cleric333** [comment]
![20151208175039](https://cloud.githubusercontent.com/assets/13984061/11652712/3bdda7b8-9dd4-11e5-9223-505acf87c72b.jpg)

**Comment by HenryJacques** [comment]
I am not sure that /usb:auto is authorized (in fact I'm 99% sure it's not).
If it is a USB drive you're trying to redirect, use the /drive parameter and not /usb which is reserved for all USB "raw" devices like scanners, webcams, etc.

Try using /drive:*,hotplug
See issue #1648

**Comment by akallabeth** [comment]
Fixed with #5745
