### ISSUE TITLE
smartcard stopped working

### ISSUE THREAD

**Issue by Hobby-Student** [FreeRDP/FreeRDP#3005]
Hey guys,

don't know when smartcard stopped working, but this is the current output:
![wp_20151206_004](https://cloud.githubusercontent.com/assets/6012744/11653921/f7aa1f7c-9da1-11e5-9f8c-c94794c55dc3.jpg)

when Smartcard is not plugged in before connecting

```
SCardListReadersW failed with error 2148532270
```

is repeated until smartcard is plugged in

This is the last version working (for me):
![wp_20151206_005](https://cloud.githubusercontent.com/assets/6012744/11653961/4dfaf2e8-9da2-11e5-80c8-d7fe2afaf0bb.jpg)
(I have the 18th of October 2015 as date of build)

Working on:
Debian 7 x86 (Thinclients)
connect to Windows Server 2008 R2 x64 (Terminalserver)
Smartcard via PC/SC with middleware on server

The weird thing:
current master is working on some clients when smartcard is plugged in at connection time (stops working when pulled out and plugged back in while connected). But on 2 clients it won't work with this "trick". And yes, all is the same hardware (ZOTAC CA320 nano).

More infos needed?

**Comment by Hobby-Student** [comment]
will try to have a look in the source the next days.. but I don't even know where to start... :(

@awakecoding are you around?

**Comment by bmiklautz** [comment]
@Hobby-Student maybe you can find out what is causing the problems by doing a git bisect.

**Comment by Hobby-Student** [comment]
@bmiklautz will try this as soon as possible...

**Comment by trentasis** [comment]
Hi @bmiklautz do you have any news about smartcard problems with windows 2012R2, this error and https://github.com/FreeRDP/FreeRDP/issues/3431 are reproduced also in windows 2012r2 with multiple smartcard reader and tested with latest versions  of pcscd and ccid.

Can you help or give information about how to help to solve this issue?

Thanks

**Comment by HenryJacques** [comment]
@trentasis what latest versions of pcscd and ccid did you use? Directly from https://pcsclite.alioth.debian.org/ccid.html and https://pcsclite.alioth.debian.org/ ?
Or are they from your Linux distribution?
I also suggest you try the latest version of pcsclite.

**Comment by HenryJacques** [comment]
@trentasis OK. I was asking because on my platform (Ubuntu 14.04) I had to upgrade the CCID/PCSC libraries and it solved most of my problems with smartcards.

**Comment by trentasis** [comment]
Can you give information about parameters used to compile freerdp with master branch... I like to reproduce your environment... 
thanks

**Comment by HenryJacques** [comment]
I am not using the latest master but the master from 2016 June 08th.

`cmake -DWITH_X11=ON -DWITH_SSE2=ON -DWITH_CUPS=ON -DWITH_PCSC=ON -DWITH_ALSA=ON -DWITH_PULSE=ON -DCHANNEL_URBDRC=ON -DCHANNEL_URBDRC_CLIENT=ON -DBUILD_SHARED_LIBS=OFF -DWITH_MANPAGES=OFF -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DWITH_OPENH264=ON`

**Comment by Hobby-Student** [comment]
perhaps this is the (quick) solution for this special problem...?!

https://github.com/FreeRDP/FreeRDP/issues/3431#issuecomment-271242300

**Comment by trentasis** [comment]
Hi @Hobby-Student , Tried without success... any suggestion to solve this issue?

Thanks

**Comment by Hobby-Student** [comment]
@trentasis 
I don't have any further information. the mentioned changes "fixed" it for me (hot plug is not working perfectly, but reader and smartcard are usable inside rdp session). So I can't tell you, why it is not working in your environment.

**Comment by trentasis** [comment]
As you say when smartcard reader is detected works, but problems is that sometimes smartcard reader is not detected, and until you logout and start another freerdp session to rdp server this doesn't works... and sometimes you have to retry some attempts...

**Comment by trentasis** [comment]
additional information about some tests https://github.com/FreeRDP/FreeRDP/pull/3686

**Comment by akallabeth** [comment]
#4312 fixed a lot of smartcard usability errors.
Reopen if still an issue.
