### ISSUE TITLE
Printer channel driver name "hardwired"

### ISSUE THREAD

**Issue by szolnoki** [FreeRDP/FreeRDP#3007]
I tested "This is FreeRDP version 2.0.0-dev (git n/a)" version.

I started freerdp with option:
/a:printer,HP4650_PCL,"HP Universal Printing PCL 6"

But HP_4650_PCL always use "Microsoft Publisher Imagesetter" driver on remote Windows. 
("HP Universal Printing PCL 6" installed on remote Windows.)

My hotfix: 
I changed "printer_cups.c"...
From:
cups_printer->printer.driver = "MS Publisher Imagesetter";
To:
cups_printer->printer.driver = "HP Universal Printing PCL 6";

And now, HP_4650 works at remote Windows with the "HP Universal Printing PCL 6" driver! :):):)
My solution works, but not nice... Why not use the specified driver name in command line, instead of default "Imagesettler"...

Why printer drive name "hardwired", when I set this option in command-line?
This problem is independent from printer type.

I would be better, if freerdp use the given driver name if specified instead of "Imagesettler".

**Comment by bmiklautz** [comment]
@szolnoki did you try with the /printer command line already? 
```
/printer:<device>,<driver>
```
I'm not sure that that the "addin syntax" (using /a) parses additional parameters if an extra parameter (like /printer) exists.

**Comment by szolnoki** [comment]
I have tested. But not working. Absolutely same effect as "/a:printer". :(
Driver name only changed, when I modify the source code...
I think not possible to change driver name any other way. Because I searched "printer.driver" string in all source codes. "printer.driver" variable is set only one place, see the "hardwired" line above.

**Comment by szolnoki** [comment]
I continue to investigate this problem, and I found this.
Compiled with cmake options:
-DWITH_CUPS=ON -DCHANNEL_PRINTER=ON

Version: 2.0.0-dev (git df81e84)

Started the xfreerdp with option again and again:
/printer:HP4650_PCL,"HP Universal Printing PCL 6"

In remote Windows Devices&Printer settings, I see:
1. The HP4650_PCL appear with driver "HP Universal Printing PCL 6"
2. Some seconds later HP4650_PCL above disappear
3. Some seconds later HP4650_PCL appear again, but with "MS Publisher Imagesetter" driver.
:(:(:(:(

I added some extra logging "printf" to freeRDP printer channel driver, and I found the problem:
1. I see in log: "[INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer (static)"
2. Calls GetPrinter for "HP4650_PCL"
3. Calls printer_cups_new_printer for "HP4650_PCL"
4. I see in log again:  "[INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer (static)"
5. Calls EnumPrinters
6. Calls printer_cups_new_printer for "HP4650_PCL"
7. Calls printer_cups_new_printer for other printers...

I think, freeRDP calls the printer registration twice. First within driver->GetPrinter, when I specify a driver with "/printer" option. And again when try to enumerate all printers (driver->EnumPrinters). This last enumartion is destroys the initilaized printers and driver names, and use the default "MS Imagesettler" driver_name. 

I made a quick test (and a fix for Me):
I commented out the total "if (name && name[0])" "else" code block in "DeviceServiceEntry" function.
With this change, I knocked out the whole enumaration process. But HP4650_PCL appear only in remote Windows when I specified "/printer:HP4650_PCL,...", but use the given driver. And printer appear only once, not twice

I think, freeRDP printer handling is broken, because always enumerate (and "overwrite") all printers, regardess given as "/printer:name,driver" option.

**Comment by szolnoki** [comment]
I dig a little deeper:
I start freeRDP only with this "device":
/printer:HP4650_PCL,xxxx

But in rdpr_process_connect, settings->DeviceCount is 2 ! 
DeviceArray[0]: Id=0, Type=4, Name="HP4650_PCL"
DeviceArray[1]: Id=0, Type=4, Name=NULL

The DeviceArray[1] is fire the 2nd printer_DeviceServiceEntry, wich calls the EnumPrinters later, and re-install all printers with defult "MS Imagsettler" driver.

**Comment by trentasis** [comment]
any news about this issue, it seems that this issue persist with imagesetter...
thanks

**Comment by trentasis** [comment]
Hi bmiklautz ,

Tried with  /printer:<device>,<driver> and not working, always appears iamgesetter, also tried with 'driver'

Waht can I do?

thanks

**Comment by hardening** [comment]
@trentasis I confirm that the driver name is ignored and hardwired. I gave a look at the printer channel and it would need some love to fix that. I'll treat this when I'll have some time.

**Comment by fedsed** [comment]
Tell when to expect patches? Really need this feature.

**Comment by akallabeth** [comment]
Does my pull work for you?

**Comment by fedsed** [comment]
System: Ubuntu 14.04 Linux lxmsk38 3.13.0-77-generic #121-Ubuntu SMP Wed Jan 20 10:50:59 UTC 2016 i686 i686 i686 GNU/Linux

Download last github master.zip. 

Compile switch:
cmake -DWITH_WAYLAND=OFF -DCMAKE_INSTALL_PREFIX=/opt/freerdp2 -DWITH_CUPS=ON -DWITH_CHANNELS=ON -DSTATIC_CHANNELS=ON -DCHANNEL_URBDRC=ON -DCHANNEL_URBDRC_CLIENT=ON -DWITH_GSTREAMER_1_0=OFF .

Run command:
/opt/freerdp2/bin/xfreerdp +clipboard /sec:rdp /v:ferma.alliance.ru /printer:HP-LaserJet-4050,"HP LaserJet 4050 PCL 6

[13:18:19:503] [32323:32324] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[13:18:19:503] [32323:32324] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[13:18:19:503] [32323:32324] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr

Segfault

Syslog:
Feb 29 13:03:05 localhost whoopsie[968]: Parsing /var/crash/_opt_freerdp2_bin_xfreerdp.65542.crash.
Feb 29 13:03:05 localhost whoopsie[968]: Uploading /var/crash/_opt_freerdp2_bin_xfreerdp.65542.crash.
Feb 29 13:03:10 localhost whoopsie[968]: Sent; server replied with: No error
Feb 29 13:03:10 localhost whoopsie[968]: Response code: 200
Feb 29 13:03:10 localhost whoopsie[968]: Got command: OOPSID
Feb 29 13:03:19 localhost whoopsie[968]: Parsing /var/crash/_opt_freerdp2_bin_xfreerdp.65542.crash.
Feb 29 13:03:19 localhost whoopsie[968]: Uploading /var/crash/_opt_freerdp2_bin_xfreerdp.65542.crash.
Feb 29 13:03:22 localhost whoopsie[968]: Sent; server replied with: No error
Feb 29 13:03:22 localhost whoopsie[968]: Response code: 200
Feb 29 13:03:22 localhost whoopsie[968]: Got command: OOPSID

I can provide file crash.

**Comment by akallabeth** [comment]
@fedsed Please test with pull #3171 merged, there is a known regression introduced with #3156 or wait until it has been reviewed and merged to master.

**Comment by fedsed** [comment]
Include #3171. 

Run command:
/opt/freerdp2/bin/xfreerdp +clipboard /sec:rdp /v:ferma.domain.local /printer:HP-LaserJet-4050,"HP LaserJet 4050 Series PCL6"

Printer redirected with the right drivers. Print test page OK.

Thank you for your work!

**Comment by akallabeth** [comment]
@fedsed Good to know it works now :)
closing as resolved.
