### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by sirio81** [FreeRDP/FreeRDP#3008]
Hi All, could you explain why there are no releases since 10 July 2013?
The project has been very active judging from the commits (from 4838 of the last release till 9317 of today).

Because of that, distribution like Debian are still packing v1.1 that is more than 2 years old.

Thank you.

**Comment by hardening** [comment]
The issue tracker is obviously the wrong place to ask such question, and for your information we have a 2.0 version that is quietly maturing => https://github.com/FreeRDP/FreeRDP/milestones/2.0
