### ISSUE TITLE
RemoteApp connection termination

### ISSUE THREAD

**Issue by timomenger** [FreeRDP/FreeRDP#3010]
Hello, 

we're using RemoteApp to connect to some Apps via VPN. Connection is established from Igel Thin Clients with an implemented Igel RDP Client (based on Free RDP Client 1.1).

Unfortunately there are severall disconnects during a working day and we don't have any starting points to resolve this issue. This is what we've done so far:

- Checked logs on our connection broker
--> RDS Event 97 and 102; seems to be any issue with FreeRDP and RemoteFX, but there isn't any chance to disable RemoteFX
- Checked logs (messages and freerdp) of any of those Thin Clients
--> nothing to see except the normal connection setup
- disabled RemoteFX in a test environment
--> no more terminations, but in productive environment no chance to disable it
- next step is to implement new firmware (5.08.1 RC)

Are there any ideas or clues how to analyze this problem?

**Comment by hardening** [comment]
@timomenger what do you expect from us ? It seems that the source code of the Igel client is not publicly available, so it's hard to see what changes they have made...

**Comment by bmiklautz** [comment]
@timomenger if you use the client that comes with the Igel thin client nothing we can do about. If it's based on 1.1 it's rather old. I'd suggest you contact the Igel support and file an issue there.
