### ISSUE TITLE
Toggle full-screen restore on different monitor

### ISSUE THREAD

**Issue by szolnoki** [FreeRDP/FreeRDP#3011]
Hi,

I tested, the  "+toggle-fullscreen" option. It's  minimize the remote desktop when I pressing CTRL+ALT+ENTER. That's OK.

But when I restore this window, It's restored on the different desktop. I use two monitor with different geometry/resolution. I started the freerdp on the 2nd (bigger) monitor. When I try to restore from minimized, it's restore always on the 1st (smaller) monitor. After that, remote desktop unusable, becasue clipped, and not moveable.

Toggle fullscren would be better, when the restore would happen to the original monitor/desktop.

**Comment by bmiklautz** [comment]
@szolnoki there were recent changes on this. What version of FreeRDP did you test with?

**Comment by szolnoki** [comment]
I tested "This is FreeRDP version 2.0.0-dev (git n/a)" version.

**Comment by bmiklautz** [comment]
@szolnoki what window manager are you working with?

**Comment by szolnoki** [comment]
LXDM maybe, I will check tomorow.
OS: Ubuntu 12.04 LTS

**Comment by Enverex** [comment]
This seems to be working now. Switching to full-screen (via Ctrl+Alt+Enter) now fullscreens the window on the monitor that the window was in, rather than the monitor that it first started on.

**Comment by akallabeth** [comment]
According to @Enverex fixed.
