### ISSUE TITLE
Configuring incomplete, errors occurred!----IOS  complie

### ISSUE THREAD

**Issue by allenwen1** [FreeRDP/FreeRDP#3018]
os：10.11.1
xcode：7.1-beta
cmake：2.8.11
openssl：1.0.2a

-- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.1.sdk
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Git Revision n/a
-- Looking for pthread_mutex_timedlock in pthread
-- Looking for pthread_mutex_timedlock in pthread - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - not found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - not found
-- Looking for include file poll.h
-- Looking for include file poll.h - not found
-- Looking for ceill
-- Looking for ceill - not found
-- Finding recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
--     Disable feature libsystemd using "-DWITH_LIBSYSTEMD=OFF"
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Could NOT find libsystemd (missing:  LIBSYSTEMD_LIBRARY LIBSYSTEMD_INCLUDE_DIR) 
CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature libsystemd was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:623 (find_feature)

-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
CMake Error at /Applications/CMake.app/Contents/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.5")
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /Applications/CMake.app/Contents/share/cmake-2.8/Modules/FindZLIB.cmake:85 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:639 (find_feature)

-- Configuring incomplete, errors occurred!

I don't know why。please help me

**Comment by cloudecker** [comment]
You need to specify the pkg- config path.(run cmake with the additional parameter  -DPKG_CONFIG_EXECUTABLE="your pkg-config path").

**Comment by hardening** [comment]
@allenwen1 anything better with @cloudecker suggestion ?

**Comment by shattars3d** [comment]
@allenwen1 you using el captain,  el captain has issues with cmake, Apple removed some header files... try to downgrade your osx.. to yosemite which works../

**Comment by akallabeth** [comment]
Apple is shipping some libraries in a new format (tbd).
They can not be found by older versions of cmake, but recent releases should cover support for those.
Can you check your version of cmake in use with ```cmake --version```?
From what I have found versions ```> 3.3.1``` should work.

**Comment by akallabeth** [comment]
Closing due to lack of feedback. Feel free to reopen if the issue still persists.

**Comment by VHurricaner** [comment]
I have this problem, too 
os: 10.12.6
xcode:8.3.3
cmake:3.9.1
openssl:1.0.2L
