### ISSUE TITLE
is that possible to login to the local session

### ISSUE THREAD

**Issue by cleric333** [FreeRDP/FreeRDP#3019]
I need to add USB devices remotely to the computer I am using, 

is that possible to use freeRDP to login (or somehow work with)the local session and plugin the USB devices remotely and I can use them from my computer, the reason I am not using the USB redirection devices is that all I can find which needs a host to get the usb from the guest, it seems the freeRDP way of doing this is better (over RDP)

many many thanks, or are there somethings work like this?

**Comment by cleric333** [comment]
there are many products for using local USB for remote sessions over RDP, but I can't find anything does using the remote USB from local session, and if I use freeRDP to connect my local machine, windows will create a remote session for it, not share it with the local session.

**Comment by cleric333** [comment]
I found this command line /admin Admin (or console) session

does this do what I need? Haven't got a linux machine on hand >: 0

**Comment by hardening** [comment]
@cleric333 I'm quite confused by your questions.
So you're asking that for example a USB webcam connected on the RDP server could be used locally by other apps ? So the scenario would be that you connect on the remote server using xfreerdp for example, a new USB device would appear on the host running xfreerdp and then you could "use" that USB device.

If this is what you expect it looks a lot appealing but unfortunately AFAICT we don't do this.
