### ISSUE TITLE
Problem with mouse pointer

### ISSUE THREAD

**Issue by ramses-15** [FreeRDP/FreeRDP#3023]
Hi all,

i have a problem with my mouse pointer (s. attached screenshot).

Each time, if i make RDP connection to WinXP, 2008, 2012 etc. - Server , it show me in background (around of mouse pointer; ca. 1x1 cm) the content from windows, which is BELOW the FreeRDP-Window!

My OS: openSUSE Leap 42.1, x64 (SuSE 13.3 - same Problem)
FreeRDP:  2.0.0-dev (with 1.0.2 is the same Problem)

Did you have any ideas, why my mouse is sick? :-)

Thank you in advance!

BR,
Ramon

P.S.: all options under "-x .." was already tested.
![20151222_112443](https://cloud.githubusercontent.com/assets/16399909/11953459/a661d70e-a8a0-11e5-8966-1e755086e05c.jpg)

**Comment by bmiklautz** [comment]
@ramses-15 you build xfreerdp yourself? - If so did you compile in xcursor (libXcursor-devel on openSUSE)

**Comment by ramses-15** [comment]
Yes, libXcursor-devel was present on my system:
libXcursor-devel-1.1.14-6.1.x86_64

**Comment by ramses-15** [comment]
Here is short output of "grep -Ri libXcursor *":
...
CMakeCache.txt:XCURSOR_LIBRARY:FILEPATH=/usr/lib64/libXcursor.so
CMakeCache.txt:xfreerdp-client_LIB_DEPENDS:STATIC=general;/usr/lib64/libX11.so;general;dl;general;/usr/lib64/libXinerama.so;general;/usr/lib64/libXext.so;general;/usr/lib64/libXcursor.so;general;/usr/lib64/libXv.so;general;/usr/lib64/libXi.so;general;/usr/lib64/libXrender.so;general;/usr/lib64/libXfixes.so;general;freerdp;general;freerdp-client;
CMakeCache.txt:FIND_PACKAGE_MESSAGE_DETAILS_Xcursor:INTERNAL=[/usr/lib64/libXcursor.so][/usr/include][v()]
...
> ldd /usr/lib64/libXcursor.so
        linux-vdso.so.1 (0x00007ffc9c54a000)
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007fee271ba000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007fee26fb3000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007fee26c75000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fee268ce000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007fee266ad000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fee264a9000)
        /lib64/ld-linux-x86-64.so.2 (0x000055d1835bf000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007fee262a5000)

Thank you in advance!

**Comment by bmiklautz** [comment]
@ramses-15 can you add the full command line you are using?

**Comment by ramses-15** [comment]
Yes, sure:
/usr/local/bin/xfreerdp /f /u:user /d:domain /monitors:1 /v:192.168.x.y

In additional here is my output of "ldd  /usr/local/bin/xfreerdp":
 >     linux-vdso.so.1 (0x00007ffe37ad2000)
        libxfreerdp-client.so.2.0 => /usr/local/bin/../lib64/libxfreerdp-client.so.2.0 (0x00007f506d214000)
        libXinerama.so.1 => /usr/lib64/libXinerama.so.1 (0x00007f506cfec000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f506cdda000)
        libXcursor.so.1 => /usr/lib64/libXcursor.so.1 (0x00007f506cbcf000)
        libXv.so.1 => /usr/lib64/libXv.so.1 (0x00007f506c9c9000)
        libXi.so.6 => /usr/lib64/libXi.so.6 (0x00007f506c7b9000)
        libXrender.so.1 => /usr/lib64/libXrender.so.1 (0x00007f506c5af000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f506c3a8000)
        libfreerdp-client.so.2.0 => /usr/local/bin/../lib64/libfreerdp-client.so.2.0 (0x00007f506c0e2000)
        libfreerdp.so.2.0 => /usr/local/bin/../lib64/libfreerdp.so.2.0 (0x00007f506bd11000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f506b9d2000)
        libxkbfile.so.1 => /usr/lib64/libxkbfile.so.1 (0x00007f506b7ad000)
        libwinpr.so.1.1 => /usr/local/bin/../lib64/libwinpr.so.1.1 (0x00007f506b4a2000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f506b299000)
        libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007f506b031000)
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007f506ac3e000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f506a93c000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f506a71f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f506a51b000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f506a304000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f5069f5d000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f5069d3c000)
        /lib64/ld-linux-x86-64.so.2 (0x00005634539f4000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f5069b38000)

**Comment by bmiklautz** [comment]
@ramses-15 if you got suse 13.3 could you try if this problem also happens with our nightly packages: https://ci.freerdp.com/job/freerdp-nightly-rpm-build/ - They are not exactly master but quite close (just updating the build system to support 42.1 as well..)

**Comment by ramses-15** [comment]
Sorry - a small mistake in the description: i use OpenSUSE 13.2 and here always work fine. So, i does not have any problem with FreeRDP on suse 13.2 at the moment.

Unfortunately repository for 42.1 is missing under https://ci.freerdp.com/job/freerdp-nightly-rpm-build/ at the moment.

So, i got the last freerdp-nightly - package for 13. 2 now (freerdp-nightly-1.2.1-0%2b0~20151112033818.139~1.gitbe8f8f7.x86_64.rpm) an installed it on my 42.1 system. Unfortunately , the problem still - mouse pointer is still ugly.



But on 42.1.

**Comment by bmiklautz** [comment]
@ramses-15 the same version you are using on 13.2 works but on 14.2 not?

**Comment by ramses-15** [comment]
Yes, correct: on 13.2 always work fine, but on 42.1 not.

**Comment by bmiklautz** [comment]
@ramses-15 just to be completely sure - same FreeRDP Version/Package? - In that case I'd guess that some of the newer libraries/dependencies in 42.1 cause the troubles.

Regarding a 42.1 package - I already started on this but hadn't time to finish it yet. So it's work in progress.

**Comment by ramses-15** [comment]
Yes, i confirm - on OpenSuSE 13.2 always working ok. Here more details to my 13.2 environment:
# /opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 2.0.0-dev (git n/a)

 # rpm -qa | grep free
freerdp-nightly-1.2.1-0+0~20151112033818.139~1.gitbe8f8f7.x86_64

# cat /etc/os-release
NAME=openSUSE
VERSION="13.2 (Harlequin)"
VERSION_ID="13.2"
PRETTY_NAME="openSUSE 13.2 (Harlequin) (x86_64)"
...

Thank you!

**Comment by ramses-15** [comment]
Hi,

I think, we can close this issue as false positive, sorry:
today i replace my default nouveau driver with last stable driver from NVIDIA and ta-da  - everything work fine! 

I really don't understand, why my mouse pointer was so purge only in FreeRDP-Sessions and in all another windows on my desktop it was ok, but the main thing that goes correct now.

Thank you again for your support.

BR,
Ramon

**Comment by bmiklautz** [comment]
@ramses-15 good to know ;). Thank you for the feedback.
