### ISSUE TITLE
No stdout with wfreerdp.exe windows

### ISSUE THREAD

**Issue by mkrusen** [FreeRDP/FreeRDP#3024]
When connecting using wfreerdp.exe there is no output to stdout, no matter if the connection is successful or not your prompt will return without giving you any output.

I am using wfreerdp.exe from 
https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=windows/lastSuccessfulBuild/artifact/build/wfreerdp.exe

**Comment by akallabeth** [comment]
@mkrusen Windows detaches started GUI applications from the terminal. https://stackoverflow.com/questions/54536/win32-gui-app-that-writes-usage-text-to-stdout-when-invoked-as-app-exe-help has quite a good explanation. If you require the logging output, configure WLog to write to a file or modify the windows startup code to create the process without ```DETACHED_PROCESS``` flag.

**Comment by hardening** [comment]
We can close this one I think, @akallabeth ?

**Comment by akallabeth** [comment]
@hardening agree.
