### ISSUE TITLE
Problem with FFmpeg on IOS

### ISSUE THREAD

**Issue by cloudecker** [FreeRDP/FreeRDP#3025]
FFmpeg verison 2.8.4
Xcode 7.2
os X 10.10.5

I try to open ffmepg on freerdp and cmake has been completed.
When compile xcode ifreerdp errors as follows:

 "_swr_close", referenced from:
_opus_decode_packet in libavcodec.a(opusdec.o)
_opus_decode_flush in libavcodec.a(opusdec.o)
 "_swr_alloc", referenced from:
 _opus_decode_init in libavcodec.a(opusdec.o)
 "_iconv_open", referenced from:
 _avcodec_open2 in libavcodec.a(utils.o)
"_swr_is_initialized", referenced from:
_opus_decode_packet in libavcodec.a(opusdec.o)
"_swr_init", referenced from:
_opus_decode_packet in libavcodec.a(opusdec.o)
"_swr_convert", referenced from:
_opus_decode_packet in libavcodec.a(opusdec.o)
"_swr_free", referenced from:
_opus_decode_close in libavcodec.a(opusdec.o)
"_iconv_close", referenced from:
_avcodec_open2 in libavcodec.a(utils.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I have been in the ffmepg source to opusdec. c find _swr_close, _swr_alloc, _swr_alloc, but didn't find it. So  what should I do? Thank you very much

**Comment by cloudecker** [comment]
I just want to realize freerdp sound redirection, when cmake, i don't know which feature to enable, a lot of features note that on the redirection of sound and video . I try to enable ffmepg first, but the above problems. So..

**Comment by bmiklautz** [comment]
@cloudecker for sound redirection you don't need ffmepg try to disable it during configuration time (run cmake with the additional parameter -DWITH_FFMPEG=OFF).

**Comment by cloudecker** [comment]
@bmiklautz  thanks,i will try it again .
