### ISSUE TITLE
i2d_PublicKey failing with OpenSSL 1.0.2e

### ISSUE THREAD

**Issue by jmdevince** [FreeRDP/FreeRDP#3028]
Running Hyper-V Server 2012 R2. Does not appear to be able to complete the TLS handshake. 

```
xfreerdp /u:[REDACTED] /p:[REDACTED] /vmconnect:cf176063-662e-4acd-bf84-[REDACTED] /v:[REDACTED]
[13:13:31:236] [22979:00081000] [INFO][com.freerdp.client.x11] - Property 296 does not exist
[13:13:32:288] [22979:00081000] [ERROR][com.freerdp.crypto] - i2d_PublicKey() failed
[13:13:32:288] [22979:00081000] [ERROR][com.freerdp.crypto] - crypto_cert_get_public_key failed to return the server public key.
[13:13:32:288] [22979:00081000] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_TLS_CONNECT_FAILED [0x20008]
[13:13:32:288] [22979:00081000] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[13:13:32:288] [22979:00081000] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[13:13:32:288] [22979:00081000] [ERROR][com.freerdp.client.x11] - Freerdp connect error exit status 1
```

**Comment by jmdevince** [comment]
Build cannot connect to any server using TLS.

**Comment by lemonmojo** [comment]
See https://github.com/FreeRDP/FreeRDP/issues/2421

**Comment by jmdevince** [comment]
Thanks. It seems to affect more than just Hyper-V Server. I've commented in the other issue.

**Comment by jmdevince** [comment]
This appears to be unreleated to #2421. 

Using openssl 1.0.2e on MacOSX results in i2d_PublicKey returning 0 during negotiation.

OpenSSL 1.0.2e 3 Dec 2015
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM

I've even tried reverting a significant number of commits of FreeRDP to see if previous versions worked, they do not. This points to a behavior change in OpenSSL.

**Comment by jmdevince** [comment]
Compiling against OpenSSL 0.9.8 seems to fix this. So there is a behavior change in OpenSSL 1.0.x that seems to break FreeRDP. I've tested with 1.0.1 and 1.0.2

**Comment by bmiklautz** [comment]
@jmdevince related to issue #3027 are you sure your build is correct? Proper headers and libraries linked to?

**Comment by jmdevince** [comment]
Yes, I'm sure. When compiling against a 1.0.x version of OpenSSL otool shows linked against the 1.0.x libcrypto library. 0.9.8 headers using a 1.0.x library and vice-versa would result in build errors. (Like the one shown in #3027). 

I'm sure someone else with a Mac platform could try and reproduce this.

**Comment by bmiklautz** [comment]
@jmdevince I'm OS X but don't have a Hyper-V to test

**Comment by jmdevince** [comment]
It's not just Hyper-V, it affects anything using NLA or TLS. So you should be able to test w/o a problem.

**Comment by bmiklautz** [comment]
@jmdevince using master almost daily without problems (TLS as well as NLA).

**Comment by bmiklautz** [comment]
@jmdevince could you do a counter test with the xfreerdp from homebrew?
Just install it with:
```
brew install homebrew/x11/freerdp --HEAD
```
Run with 
```
$(brew --prefix)/bin/xfreerdp --version
```

**Comment by bmiklautz** [comment]
@jmdevince would you also paste the otool  output of the xfreerdp you've built?
```
otool -l xfreerdp  | grep name | grep -v sectname | grep -v segname
```

**Comment by jmdevince** [comment]
Looks like it's building against the proper libcrypto but not the proper libssl.

I tried using 
```
brew install homebrew/x11/freerdp --HEAD
```

and it does work properly (minus the /vmconnect issue I'm trying to patch). So, the manual build documentation (as I've said before) for Mac is incorrect.

**Comment by bmiklautz** [comment]
@jmdevince incorrect documentation, true, that definitely needs updating.
Given that the master branch works (--HEAD) when built with brew your i2d_PublicKey seems to be build related. I suggest doing a complete clean build (git clean -fdx) with the PKG_CONFIG_PATH set as described in #3027.

**Comment by akallabeth** [comment]
Seems fixed,
reopen if still an issue.
