### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by bsiegert** [FreeRDP/FreeRDP#3029]
The "download" button on freerdp.com leads directly to this github project. According to the "Releases" tab, there has been no stable release at least since 2013; all releases on there are tagged "beta". 

pkgsrc is still at version 1.0.2, which contains none of the hardening work and is quite vulnerable. I noticed that Debian seems to be packaging git snapshots but I would like to avoid that if possible.

In short: can we have a stable release, please?

**Comment by bmiklautz** [comment]
@bsiegert there are multiple issues regarding this topic. Please have a look to #2678 for example.

We are currently working on a 2.0 release. The base for 2.0 is the current master branch. For now I can only suggest to use a git snapshot of the current branch (if you build yourself). If you want finished packages you can use our nightly builds https://ci.freerdp.com/job/freerdp-nightly-binaries/ (Debian/Ubuntu) or https://ci.freerdp.com/job/freerdp-nightly-rpm-mock/ (Fedora).
Regarding the official Debian package we are working closely together with the maintainers to update the package for the upcoming release (working on this right this moment).

In short: There will be a 2.0 release but we can't give a fixed schedule.

**Comment by bsiegert** [comment]
It is weird that there are all these "beta" tags in github but no non-beta release. I saw some 1.1 betas, 1.2 betas, etc. We do not usually package snapshots, and 1.0.2 has lots of security bugs. This is a really bad situation :/

**Comment by bmiklautz** [comment]
@bsiegert The "betas" where recently discussed on the mailing list http://sourceforge.net/p/freerdp/mailman/message/34705731/. Back then the beta and the creation of the stable-1.1 was done quite premature because people wanted a new release.

 I'm very well aware that the situation is not "optimal" (to say it nicely) but I can assure you that we do our best to solve this.
