### ISSUE TITLE
Could NOT find PkgConfig error while building using cmake

### ISSUE THREAD

**Issue by ANANTHU-R-NATH** [FreeRDP/FreeRDP#3033]
i know i have to run cmake with an extra parameter '-DPKG_CONFIG_EXECUTABLE=' to correct this but  what path to what is to be given here,
i am new to linux please help me

**Comment by bmiklautz** [comment]
@ANANTHU-R-NATH this is rather a cmake than FreeRDP issue as it looks for me. Please use the the mailing list or our irc channel for help.
