### ISSUE TITLE
android afreerdp rdpdr usually occur "\\tsclient\Android is not accessible"

### ISSUE THREAD

**Issue by jinlong0813** [FreeRDP/FreeRDP#3034]
I use freerdp_set_drive_redirection(inst, "/mnt/usbhost1"); to redirect the USB storage, but It is work fine only for a few time, then it happens "\tsclient\Android is not accessible". And I have test to redirect other folder in the android system(like /data/data) also have the same problem.
when it happens this error, there isnot any error information in log. 
I donot know why, really need your help!
Thanks
![img_20160106_170741](https://cloud.githubusercontent.com/assets/16506647/12159434/29730022-b51d-11e5-9075-3ca7f2631904.jpg)

**Comment by bmiklautz** [comment]
@jinlong0813 the image didn't work. When you tested did you reconnect to the windows session or logged off and started a new one?

**Comment by jinlong0813** [comment]
After reconnect, it works again. but the problem will apear soon.

**Comment by jinlong0813** [comment]
I have used the lastest version on gitbub. I have already retransmission the image file. Thanks for your reply.

**Comment by jinlong0813** [comment]
@bmiklautz  I have tested the release version "1.2.0-beta1+android9", It works fine. But the lastest code have the problem.

**Comment by jinlong0813** [comment]
@bmiklautz @awakecoding We have try many commits. And make user the error is begin at commit b184a75 on Jan 20, 2015. The previous commit 8e7b80b is OK. Can you help to find the error

**Comment by bmiklautz** [comment]
@jinlong0813 this is quite a large and old change set. Just to make sure the behavior you are reporting happens with the master branch? If so I'd recommend trying to redirect a drive to the same server with xfreerdp to find out if this is only android specific or a generic problem of the drive channel. Did you test with different servers or always the same?

**Comment by jinlong0813** [comment]
@bmiklautz  I have test on several PC.  I met another question. When I redirect a USB storage on aFreerdp. After start up, I open the USB path, and stay at the folder of USB path. then I remove the USB storage, the afreerdp will crash without any log. Both the lastest version and old version of code have the problem. The probability is 100%.

**Comment by bmiklautz** [comment]
@jinlong0813 you are trying drive redirection with an usb drive but not USB redirection, right?

**Comment by jinlong0813** [comment]
@bmiklautz Yes, I use drive redirection with an usb drive. The problem is, if the USB is removed when it is be using. afreerdp doesn't close the fd, the android system cannot unmount the usb, then system will kill the afreerdp then unmount the usb. What is the feature of USB redirection you mentioned? How to use it? Does it support hot plug of USB storage? I want to realize the function of after the afreerdp have login the windows, I can insert the USB storage and redirect to the windows system? Do you know how to do it? Thanks very much!

**Comment by bmiklautz** [comment]
@jinlong0813 USB redirection is redirecting a device on USB level but it's not fully working - that's why I asked. As for your problem, FreeRDP doesn't handle hotplug for devices on android. Although it would theoretically be possible it isn't implemented. Therefore I'd suggest to not directly redirect the usb drive but rather the directory above. This way you have kind of hotplug (in case all devices are mounted in the same directory).
For example if you want to redirect "/media/usb1" just redirect /media instead.

**Comment by pedjaman** [comment]
I'm not sure if I should open new issue but sale or similar is happening in this case:

Connecting from Linux machine to Windows machine and sharing some folder from Linux machine which is mount point of custom FUSE file system.

After browsing couple of folders in Windows Explorer from remote windows machine, share becomes inaccessible. I'm making a note that FUSE filesystem is working well after that, so it shouldn't be a direct cause of the problem.

I need to note that browsing folders from Total Commander takes more time to reproduce issue and using cmd and cd and dir commands takes even more time to reproduce.

I've noticed that Windows Explorer does a read ahead when you hover over folder so it retrieve folder list in advance even before you click on it. Therefore, it is doing a lot of folder reading, much more than TC or CMD.

It seems that issue happens after some amount of reading is performed.

No debug info is produced by library.

**Comment by bmiklautz** [comment]
@pedjaman your problem is with the android client as well?

**Comment by pedjaman** [comment]
No it happens also with regular windows rdp client which is connecting to
custom server written with FreeRDP.

FreeRDP library reportserrors and disconnects the share.

**Comment by bmiklautz** [comment]
@pedjaman then this is not related to this issue I'd think.

**Comment by pedjaman** [comment]
@bmiklautz Well, if it happens in same manner on other platform it might point out that problem is not Android only and can be reproduced on other platforms. That way team could know it is somewhere in general FreeRDP library code and not Android specific one.

That was the purpose of my comment. I apologize if it doesn't help

**Comment by akallabeth** [comment]
Drive redirection was refactored in target release.
