### ISSUE TITLE
FREERDP  via command line on android

### ISSUE THREAD

**Issue by ANANTHU-R-NATH** [FreeRDP/FreeRDP#3035]
is it posible to start freerdp with specific ip and port from command line in android ?

**Comment by bmiklautz** [comment]
@ANANTHU-R-NATH not really. However you should be able to launch aFreeRDP by creating/downloading/.. a .rdp file and trying to open that.

**Comment by bmiklautz** [comment]
@ANANTHU-R-NATH please also note that this is a issue tracker and *not* a help forum. For questions please try the mailing list or visit our irc channel.
