### ISSUE TITLE
RDPDR crashes on windows

### ISSUE THREAD

**Issue by melanholy** [FreeRDP/FreeRDP#3037]
When I try to use redirected drive on the remote desktop, the following exception occurs:
```
Unhandled exception at 0x779AE41B (ntdll.dll) in wfreerdp.exe: 0xC0000005: Access violation writing location 0x00000000.
```
The funny thing that this is not the constant behavior. After a few crashes redirection starts to work normally. But when I try to use another build of freerdp(I have four), crashes appear again, and again they disappear after a while.

Also crashes are guaranteed if I try to use "dir \\tsclient\drive". But read and copy of one file doesn't always fail.

I'm trying to connect to windows server 2012. My command line is:
```
wfreerdp /v:address /u:user /p:pass -wallpaper /drive:drive,C:\folder
```
I'm using latest version of FreeRDP, downloaded it today. My operating system is Windows 7 x64. Compiled FreeRDP in Visual Studio 2015(and 2013 for one of the builds).

**Comment by bmiklautz** [comment]
@melanholy can you try to verify if this behavior is also reproducible with our nightly build from https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=windows/lastSuccessfulBuild/artifact/build/wfreerdp.exe

**Comment by melanholy** [comment]
Doesn't crash with this build. Is this build stable? Can I use for my work?

**Comment by bmiklautz** [comment]
@melanholy those builds are built nightly if a commit happened during the day. It's based on the master branch if a build works for you you can use it for work.
