### ISSUE TITLE
No task bar icons for Citrix Apps windows in seamless mode of Windows 7 RemoteApp

### ISSUE THREAD

**Issue by archont00** [FreeRDP/FreeRDP#3040]
Hi,

it seems that the task bar of Ubuntu 15.10 is not able to show icons for windows, in which the Citrix applications are run.

Summary:
- Client is Ubuntu 15.10 or Arch Linux MATE.
- RDP host is Windows 7 run as a guest in KVM, accessible by IP address on LAN.
- Internet Explorer is published as a RemoteApp (for this, icon is wrong but at least it is shown on Ubuntu task bar).
- Any Citrix app window, which was run from IE launchers, gets icon on Ubuntu task bar.
- Some Citrix app windows show wrongly position of the mouse pointer by the width of Ubuntu task bar and top bar (Adobe Acrobat, MS Excel, MS Word), while in other apps the mouse pointer position is correct (MS Outlook, Windows Explorer). This is a minor issue since it can be resolved by hiding the Ubuntu panels (task and top bars).
- There are also some other minor glitches: e.g. in Desktop mode of Windows 7, there appears the keyboard notification panel as a floating window. In FreeRDP there is only a black frame shown (not reacting on mouse clicks). This is a minor issue.

The FreeRDP client was [compiled](https://github.com/FreeRDP/FreeRDP/wiki/Compilation) on clean install of Ubuntu 15.10 from GitHub master:

```
$ xfreerdp -u 'User' -p 'pswd' --f --app --plugin rail --data "||IE" -- 10.11.13.61
```

The same happens on Arch Linux with MATE desktop. On Arch, I use multiple workspaces - if I switch the workspaces back and forth, all the Citrix windows even disappear completely.

If other logs are needed, I can do so.

**Comment by milankni** [comment]
Example of missing task bar icons for Citrix windows:
![Missing Icons in task bar](https://github.com/milankni/FreeRDP-bugs/raw/master/missing-icons-for-windows-opened-via-citrix-launchers.png)

Example of offset between mouse pointer and actual active location:
![Offset between mouse pointer and actual location](https://github.com/milankni/FreeRDP-bugs/raw/master/adobe-acrobat.wrong-offset-of-mouse-pointer.png)

Logs by xwininfo and xprop for Citrix window - MS Outlook (no offset for mouse pointer, no icon in task bar):
````
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x28009dc "Inbox - XXXX - Microsoft Outlook - \\Remote"

  Absolute upper-left X:  152
  Absolute upper-left Y:  34
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1089
  Height: 870
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +152+34  -39+34  -39-120  +152-120
  -geometry 977x843-29+24
````
````
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 112 by 27
		program specified maximum size: 1292 by 1036
		program specified resize increment: 1 by 1
_NET_WM_ICON_GEOMETRY(CARDINAL) = 5, 415, 54, 54
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_STICK, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_NAME(UTF8_STRING) = "Inbox - XXXX - Microsoft Outlook - \\\\Remote"
WM_NAME(STRING) = "Inbox - XXXX - Microsoft Outlook - \\Remote"
_NET_WM_PID(CARDINAL) = 20312
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x0, 0x0, 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
WM_CLASS(STRING) = "RAIL", "RAIL:000300F8"
````

Logs by xwininfo and xprop for Citrix window - Adobe Acrobat (offset for mouse pointer, no icon in task bar):
````
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x2809d52 "ZFI_TAX_REPORT_ALV - RE-Reports - Accounting - ALV Adv. Ret. f - \\Remote"

  Absolute upper-left X:  65
  Absolute upper-left Y:  24
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1215
  Height: 870
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +65+24  -0+24  -0-130  +65-130
  -geometry 1215x870--10+14
````
````
_NET_WM_ICON_GEOMETRY(CARDINAL) = 5, 415, 54, 54
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 0, 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_STICK, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
_NET_WM_NAME(UTF8_STRING) = "ZFI_TAX_REPORT_ALV - RE-Reports - Accounting - ALV Adv. Ret. f - \\\\Remote"
WM_NAME(STRING) = "ZFI_TAX_REPORT_ALV - RE-Reports - Accounting - ALV Adv. Ret. f - \\Remote"
_NET_WM_PID(CARDINAL) = 20312
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x0, 0x0, 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
WM_CLASS(STRING) = "RAIL", "RAIL:000300D0"
````

**Comment by hardening** [comment]
@milankni I may have missed something but you haven't given the FreeRDP version you're running. If it's not master (and so pre 2.0) would you mind giving a try with lastest master (either by recompiling or using pre-builds) ?

**Comment by milankni** [comment]
@hardening Yes, it is compiled from master. I added the info to the OP now.

**Comment by hardening** [comment]
Ok so the bug with icons has a very simple cause: we treat the rail messages for icons but we don't do anything with them.

**Comment by milankni** [comment]
This sounds promising to me ;-)

**Comment by Nobel3D** [comment]
Pull request #4374 should partially fix it adding /wm-skip-taskbar:0 to CLI. Anyway the RemoteApp icon image isn't processed, so is shown the default XORG icon.
