### ISSUE TITLE
RemoteApp Photoshop.exe makes Photoshop freeze

### ISSUE THREAD

**Issue by Utini2000** [FreeRDP/FreeRDP#3041]
Hey there, 
when running the following command, Photoshop will start, be in fullscreen, but freezes and making it not clickable:

xfreerdp /u:Vbox /p:lala /admin /cert-ignore +clipboard /app:'calc.exe' /v:192.168.122.149

All other apps (calculatore, explorer, etc) will work. 
Without RDP (e.g. when running windows with virt manager) I guess run photoshop just fine.

Any ideas? Thanks !

**Comment by Utini2000** [comment]
Also same problem when running explorer.exe, manually going to photoshop.exe and executing it:

Photoshop loads but as soon as it finished loading I see photoshop but can't click anywhere.

**Comment by hardening** [comment]
@Utini2000 what version are you running and what is your platform ?

**Comment by Utini2000** [comment]
Archlinux + freerdp 1:1.2.0_20160107-2

https://www.archlinux.org/packages/community/x86_64/freerdp/

For once I managed to get it working but not sure how. After a reboot of the VM I am back to the same problem. After several re-trying to run photoshop it seems to work again.

**Comment by Utini2000** [comment]
Ah okay, I found out that "photoshop.exe is not reacting" in windows itself. It just seems to take ages for it to load although the VM has 8cpu's + 8gb RAM :S

**Comment by bmiklautz** [comment]
@Utini2000 if this doesn't seem to be a FreeRDP problem can we close the issue?

**Comment by Utini2000** [comment]
Yes, it seems to be a windows / photoshop problem rather than freerdp. Thanks again !
