### ISSUE TITLE
Fullscreen escape key sequence (Ctrl+Alt+Enter) not working

### ISSUE THREAD

**Issue by mlawren** [FreeRDP/FreeRDP#3047]
My build of commit 1210421 on a Debian stretch/sid mix seems to have a broken fullscreen escape sequence. The last version I built where it worked was df81e842a. Actual command line I'm using is this:

    xfreerdp /u:mark /p:****** /compression /fonts /f /v:[fe80::1dfd:e0c9:9d86:d7bf%eth0] /toggle-fullscreen /drive:x,/home/mark/work/ins

**Comment by abma** [comment]
oops, sorry didn't see this issue.

duplicate of #3051

**Comment by abma** [comment]
https://github.com/FreeRDP/FreeRDP/pull/3052 should fix this

**Comment by abma** [comment]
should be fixed!

https://github.com/FreeRDP/FreeRDP/commit/2db8c7e1079e2160301299de082e854cb4c63479

**Comment by bmiklautz** [comment]
@mlawren can you verify that this problem is fixed on the latest master?

**Comment by mlawren** [comment]
Current master commit (2db8c7e) works for me. Thanks for the quick response and the overall FreeRDP effort.
