### ISSUE TITLE
non-ASCII symbols in login/password

### ISSUE THREAD

**Issue by melanholy** [FreeRDP/FreeRDP#3053]
I'm trying to connect to the remote desktop that has non-ascii symbols(cyrillic) in it's login. And debug console says that there is an error: **ERRCONNECT_CONNECT_TRANSPORT_FAILED**. 

mstsc.exe works perfectly with this remote desktop.

I'm using windows 7 and the latest version of FreeRDP.

**Comment by bmiklautz** [comment]
@melanholy how do you supply the username/password?

**Comment by melanholy** [comment]
wfreerdp.exe /v:1.2.3.4:3390 /u:Менеджеры /p:123

**Comment by Mandar-Shinde** [comment]
can you try with 
wfreerdp.exe /v:1.2.3.4:3390 /u:"Менеджеры" /p:123
or
wfreerdp.exe /v:1.2.3.4:3390 /u:'Менеджеры' /p:123

**Comment by melanholy** [comment]
both don't work.

**Comment by bofh80** [comment]
i am unsure for windows, but for passwords with similar issues on linux, make it prompt instead. so /p:  (not sure about the ":") should make it prompt. Or maybe try without /u: /p: etc.
wfreerdp.exe /v:1.2.3.4:3390 /u: /p:
wfreerdp.exe /v:1.2.3.4:3390 /u /p
wfreerdp.exe /v:1.2.3.4:3390
etc, whatever makes this version of the client prompt for username and password instead.

**Comment by akallabeth** [comment]
@melanholy The windows client command line unicode support is non existent. Would need some patching to read in the unicode arguments and convert them to utf-8 for internal use.
See https://msdn.microsoft.com/en-us/library/windows/desktop/ms683156%28v=vs.85%29.aspx and https://msdn.microsoft.com/en-us/library/bb776391%28VS.85%29.aspx

**Comment by akallabeth** [comment]
@melanholy Try #3116, that should fix it.

**Comment by melanholy** [comment]
it works, thank you! now waiting for merge
