### ISSUE TITLE
the newest release compiled error 

### ISSUE THREAD

**Issue by ygqzwl** [FreeRDP/FreeRDP#3056]
system is  centos 7

I download the newest code , but it errors when i use the commands
" cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON ." 

 it happened some errors:

CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "disp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "echo-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpei-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpgfx-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "cliprdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drdynvc-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "encomsp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rail-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "remdesk-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drive-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "parallel-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "serial-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "smartcard-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client-oss" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client-alsa" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client-oss" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client-alsa" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-ffmpeg-decoder" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-gstreamer-decoder" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-oss-audio" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-alsa-audio" that is not in the export set.

**Comment by hardening** [comment]
Is it a fresh git clone, or is there any CMakeCache.txt floating around ?

**Comment by ygqzwl** [comment]
@hardening 
1.download code use    git clone git://github.com/FreeRDP/FreeRDP.git

2.the code directoty is:
   -rwxrwxrwx  1 root root   358 1月  15 14:54 buildflags.h.in
-rwxrwxrwx  1 root root  2742 1月  15 14:54 ChangeLog
drwxrwxrwx 23 root root  4096 1月  15 14:54 channels
drwxrwxrwx  3 root root    35 1月  15 14:54 ci
drwxrwxrwx 11 root root  4096 1月  15 14:54 client
drwxrwxrwx  6 root root  4096 1月  15 14:54 cmake
-rwxrwxrwx  1 root root  3884 1月  15 14:54 CMakeCPack.cmake
-rwxrwxrwx  1 root root   345 1月  15 14:54 CMakeCPackOptions.cmake.in
-rwxrwxrwx  1 root root 27925 1月  15 14:54 CMakeLists.txt
-rwxrwxrwx  1 root root  2448 1月  15 14:54 config.h.in
drwxrwxrwx  2 root root   133 1月  15 14:54 docs
drwxrwxrwx  2 root root    19 1月  15 14:54 external
drwxrwxrwx  3 root root    53 1月  15 14:54 include
drwxrwxrwx 11 root root  4096 1月  15 14:54 libfreerdp
-rwxrwxrwx  1 root root 11358 1月  15 14:54 LICENSE
drwxrwxrwx  5 root root    56 1月  15 14:54 packaging
drwxrwxrwx  5 root root   139 1月  15 14:54 rdtk
-rwxrwxrwx  1 root root  1245 1月  15 14:54 README
drwxrwxrwx  2 root root  4096 1月  15 14:54 resources
drwxrwxrwx  2 root root  4096 1月  15 14:54 scripts
drwxrwxrwx  7 root root  4096 1月  15 14:54 server
drwxrwxrwx  2 root root    56 1月  15 14:54 third-party
drwxrwxrwx  6 root root  4096 1月  15 14:54 winpr
