### ISSUE TITLE
the newest code compiled error

### ISSUE THREAD

**Issue by ygqzwl** [FreeRDP/FreeRDP#3058]
using centos 7 system
1.git clone git://github.com/FreeRDP/FreeRDP.git
2.the code directoty is:
-rwxrwxrwx 1 root root 358 1月 15 14:54        buildflags.h.in
-rwxrwxrwx 1 root root 2742 1月 15 14:54      ChangeLog
drwxrwxrwx 23 root root 4096 1月 15 14:54    channels
drwxrwxrwx 3 root root 35 1月 15 14:54          ci
drwxrwxrwx 11 root root 4096 1月 15 14:54    client
drwxrwxrwx 6 root root 4096 1月 15 14:54     cmake
-rwxrwxrwx 1 root root 3884 1月 15 14:54     CMakeCPack.cmake
-rwxrwxrwx 1 root root 345 1月 15 14:54       CMakeCPackOptions.cmake.in
-rwxrwxrwx 1 root root 27925 1月 15 14:54   CMakeLists.txt
-rwxrwxrwx 1 root root 2448 1月 15 14:54     config.h.in
drwxrwxrwx 2 root root 133 1月 15 14:54      docs
drwxrwxrwx 2 root root 19 1月 15 14:54        external
drwxrwxrwx 3 root root 53 1月 15 14:54         include
drwxrwxrwx 11 root root 4096 1月 15 14:54   libfreerdp
-rwxrwxrwx 1 root root 11358 1月 15 14:54    LICENSE
drwxrwxrwx 5 root root 56 1月 15 14:54         packaging
drwxrwxrwx 5 root root 139 1月 15 14:54       rdtk
-rwxrwxrwx 1 root root 1245 1月 15 14:54      README
drwxrwxrwx 2 root root 4096 1月 15 14:54     resources
drwxrwxrwx 2 root root 4096 1月 15 14:54     scripts
drwxrwxrwx 7 root root 4096 1月 15 14:54     server
drwxrwxrwx 2 root root 56 1月 15 14:54         third-party
drwxrwxrwx 6 root root 4096 1月 15 14:54     winpr

3.cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .

the errors:
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "disp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "echo-client" that is not in the export set.

**Comment by akallabeth** [comment]
@ygqzwl Please don't spam the issue tracker (#3057, #3057) but use a single issue for your problem.

As to your error description, it is a bit sparse, but could you check if
* You start from a clean checkout (```git clean -xdf``` will remove all files not in git)
* All required dependencies are installed

If it still fails, please provide some more details (the output of cmake would help ;))

**Comment by ygqzwl** [comment]
@akallabeth  
it is still has errors:
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /bin/cc
-- Check for working C compiler: /bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /bin/c++
-- Check for working CXX compiler: /bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /bin/pkg-config (found version "0.27.1") 
-- FreeRDP GIT-dirty
-- Git Revision 2db8c7e
-- Looking for __x86_64__
-- Looking for __x86_64__ - found
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Success
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Success
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Success
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Success
-- Performing Test Wimplicit-function-declaration
-- Performing Test Wimplicit-function-declaration - Success
-- Performing Test Wredundant-decls
-- Performing Test Wredundant-decls - Success
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - not found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for pthread_mutex_timedlock in pthread
-- Looking for pthread_mutex_timedlock in pthread - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for eventfd_read
-- Looking for eventfd_read - found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for ceill
-- Looking for ceill - found
-- Finding recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
--     Disable feature libsystemd using "-DWITH_LIBSYSTEMD=OFF"
-- Could NOT find libsystemd (missing:  LIBSYSTEMD_LIBRARY LIBSYSTEMD_INCLUDE_DIR) 
CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature libsystemd was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:650 (find_feature)


-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Found X11: /usr/lib64/libX11.so  
-- Finding recommended feature Wayland for Wayland (Wayland client)
--     Disable feature Wayland using "-DWITH_WAYLAND=OFF"
-- checking for module 'wayland-client'
--   package 'wayland-client' not found
-- Could NOT find WAYLAND (missing:  WAYLAND_LIBRARY WAYLAND_INCLUDE_DIR) 
CMake Warning at cmake/FindWayland.cmake:57 (message):
  Couldn't detect wayland version - no version check is done
Call Stack (most recent call first):
  cmake/FindFeature.cmake:25 (find_package)
  CMakeLists.txt:660 (find_feature)


CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature Wayland was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:660 (find_feature)


-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e") 
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping optional feature OpenSLES for multimedia (OpenSLES audio / video)
--     Enable feature OpenSLES using "-DWITH_OPENSLES=ON"
-- Finding recommended feature OSS for sound (audio input, audio output and multimedia redirection)
--     Disable feature OSS using "-DWITH_OSS=OFF"
-- Found OSS Audio
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Found ALSA: /usr/lib64/libasound.so (found version "1.0.28") 
-- Skipping optional feature Pulse for sound (audio input, audio output and multimedia redirection)
--     Enable feature Pulse using "-DWITH_PULSE=ON"
-- Skipping optional feature Cups for printing (printer device redirection)
--     Enable feature Cups using "-DWITH_CUPS=ON"
-- Skipping optional feature PCSC for smart card (smart card device redirection)
--     Enable feature PCSC using "-DWITH_PCSC=ON"
-- Finding recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Disable feature FFmpeg using "-DWITH_FFMPEG=OFF"
-- checking for module 'libavcodec'
--   found libavcodec, version 57.15.100
-- checking for module 'libavutil'
--   found libavutil, version 55.7.100
-- Found FFmpeg: TRUE  
-- Skipping optional feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
--     Enable feature GStreamer_0_10 using "-DWITH_GSTREAMER_0_10=ON"
-- Finding recommended feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
--     Disable feature GStreamer_1_0 using "-DWITH_GSTREAMER_1_0=OFF"
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.42.2
-- Found Glib 
-- checking for module 'gstreamer-1.0 >= '
--   found gstreamer-1.0 , version 1.0.7
-- checking for module 'gstreamer-base-1.0 >= '
--   found gstreamer-base-1.0 , version 1.0.7
-- checking for module 'gstreamer-app-1.0 >= '
--   found gstreamer-app-1.0 , version 1.0.7
-- checking for module 'gstreamer-audio-1.0 >= '
--   found gstreamer-audio-1.0 , version 1.0.7
-- checking for module 'gstreamer-fft-1.0 >= '
--   found gstreamer-fft-1.0 , version 1.0.7
-- checking for module 'gstreamer-pbutils-1.0 >= '
--   found gstreamer-pbutils-1.0 , version 1.0.7
-- checking for module 'gstreamer-video-1.0 >= '
--   found gstreamer-video-1.0 , version 1.0.7
-- Found GSTREAMER_1_0: /usr/lib64/libgstreamer-1.0.so  
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- FreeRDP GIT-dirty
-- Finding recommended feature XKBFile for X11 keyboard (X11 keyboard file extension)
--     Disable feature XKBFile using "-DWITH_XKBFILE=OFF"
-- Found XKBFile: /usr/lib64/libxkbfile.so  
-- FreeRDP GIT-dirty
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Finding required feature XRandR for X11 randr (X11 randr extension)
-- Found XRANDR: /usr/lib64/libXrandr.so  
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Found Xext: /usr/lib64/libXext.so  
-- Found DocBookXSL: /usr/share/sgml/docbook/xsl-stylesheets  
-- Finding required feature XShm for X11 shared memory (X11 shared memory extension)
-- Found XShm: /usr/lib64/libXext.so  
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
-- Found Xinerama: /usr/lib64/libXinerama.so  
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Finding recommended feature Xcursor for cursor (X11 cursor extension)
--     Disable feature Xcursor using "-DWITH_XCURSOR=OFF"
-- Found Xcursor: /usr/lib64/libXcursor.so  
-- Finding recommended feature Xv for video (X11 video extension)
--     Disable feature Xv using "-DWITH_XV=OFF"
-- Found Xv: /usr/lib64/libXv.so  
-- Finding recommended feature Xi for input (X11 input extension)
--     Disable feature Xi using "-DWITH_XI=OFF"
-- Found Xi: /usr/lib64/libXi.so  
-- Looking for XITouchClass
-- Looking for XITouchClass - found
-- Finding recommended feature Xrender for rendering (X11 render extension)
--     Disable feature Xrender using "-DWITH_XRENDER=OFF"
-- Found Xrender: /usr/lib64/libXrender.so  
-- Finding recommended feature Xfixes for X11 xfixes extension (Useful additions to the X11 core protocol)
--     Disable feature Xfixes using "-DWITH_XFIXES=OFF"
-- Found Xfixes: /usr/lib64/libXfixes.so  
-- Configuring done
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "disp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "echo-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpei-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpgfx-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "cliprdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drdynvc-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "encomsp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rail-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "remdesk-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drive-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "parallel-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "serial-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "smartcard-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client-oss" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client-alsa" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client-oss" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client-alsa" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-ffmpeg-decoder" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-gstreamer-decoder" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-oss-audio" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-alsa-audio" that is not in the export set.
-- Generating done
-- Build files have been written to: /home/admin/workCode/new_freerdp/FreeRDP

**Comment by bmiklautz** [comment]
@ygqzwl what version of cmake are you using?

**Comment by ygqzwl** [comment]
@bmiklautz 
cmake version 2.8.11

**Comment by bmiklautz** [comment]
@ygqzwl the problem you are reporting *only* happens exactly with cmake version 2.8.11.
There is a pending pull request that fixes this #3062

**Comment by bmiklautz** [comment]
@ygqzwl can you verify that the current master fixes your problem?

**Comment by lucadistefano** [comment]
tried with cmake version 3.5.1 and options
-DMONOLITHIC_BUILD=ON -DBUILD_SHARED_LIBS=OFF -DWITH_SSE2=ON -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_JPEG=ON -DWITH_PCSC=ON -DWITH_OSS=OFF -DWITH_MBEDTLS=ON

....
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "cliprdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drdynvc-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "remdesk-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "encomsp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rail-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "echo-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "disp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpgfx-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpei-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drive-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "smartcard-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "serial-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "parallel-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "printer-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client-alsa" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client-pulse" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-ffmpeg-decoder" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-gstreamer-decoder" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-alsa-audio" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client-pulse-audio" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client-alsa" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client-pulse" that is not in the export set.
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    MONOLITHIC_BUILD

**Comment by bmiklautz** [comment]
@lucadistefano this is a "known" issue when you build with cmake > 3.4 and use -DBUILD_SHARED_LIBS=OFF

**Comment by mbroadst** [comment]
@bmiklautz is there a workaround for it then?

**Comment by bmiklautz** [comment]
@mbroadst for now the workaround is to use cmake < 3.5. I'll have a look once I get around do it.

**Comment by bmiklautz** [comment]
@mbroadst I've created an issue for that #3350
