### ISSUE TITLE
xfreerdp : which gstreamer's version need to install on the newest freerdp codes?

### ISSUE THREAD

**Issue by ygqzwl** [FreeRDP/FreeRDP#3064]
I want to use the newest codes, but i cannot know to use which gstreamer's version ? 

1. I installed the gstreamer version   gstreamer-0.10.36-7.el7.x86_64
2. when I use the multimedia redirection , some errors happended: (Failed to create new pipe)

**Comment by akallabeth** [comment]
default is gstreamer 1 by now, there is a cmake option to reactivate 0.10. there may still be some issues, look at the pull requests pending for tsmf.

**Comment by akallabeth** [comment]
@ygqzwl Are your issure resolved?
