### ISSUE TITLE
the newest freerdp codes support which RDP protocol?  RDP8.0 or RDP 8.1?

### ISSUE THREAD

**Issue by ygqzwl** [FreeRDP/FreeRDP#3065]

**Comment by kekkeme** [comment]
We want to use SSO but msdn documentation says it should be at least RDP 8.0 protocol. Does freerdp support for RDP 8.0 protocol

Thanks

**Comment by hardening** [comment]
The issue tracker is not the place for asking questions.

I think we support RDP 8.0 and 8.1, even if I don't know if you can find somewhere a document giving the requirement for a given RDP version...
