### ISSUE TITLE
Cannot exit from full screen mode (/f flag) Ubuntu 12.04

### ISSUE THREAD

**Issue by mr-wong** [FreeRDP/FreeRDP#3071]
Hi. Here is problem: after suspend-resume wifi reconnected but rdp window still in front in hanged state - no reaction to keyboard/mouse nor trying to exit. So, I cannot switch to any other window since rdp stealing any input and remains unresponsible. Tried to bind shortcut with xdotool for killing foreground window with no success, but any other windows work well. In these situations I have no choice than reset X via Ctrl-Alt-Bksp what driving me crazy.

**Comment by akallabeth** [comment]
@mr-wong Have you tried ```ctrl + alt + enter```? this should switch back to normal window mode.

**Comment by mr-wong** [comment]
Uhh, didn't know about that shortcut, thanks!! I will try when another hang occurs. Anyway, rdp should exit itself on lost connection at suspend (those issues occurs only on suspend-resume cycle).

**Comment by akallabeth** [comment]
@mr-wong Did the error occur again? Do you use auto reconnect? Otherwise FreeRDP should exit on connection loss.

**Comment by mr-wong** [comment]
@akallabeth I've just tried now to simulate - it hangs, no response to ctrl+alt+enter, nor anything else like Alt-F1/F2 Unity menus. So I left it open as is and sat to another laptop. After 10-15 minutes connection at last dropped and console flooded with messages:

>[...many skipped here...]
>[20:47:04:888] [25863:25864] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken pipe
>[20:47:04:889] [25863:25864] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken pipe
>[20:47:04:890] [25863:25864] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken pipe
>[20:47:04:890] [25863:25864] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken pipe
>[20:47:04:890] [25863:25864] [ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken pipe
>[20:47:04:938] [25863:25864] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 11: Resource temporarily unavailable
>[20:47:04:938] [25863:25864] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
>[20:47:04:938] [25863:25864] [INFO][com.freerdp.client.x11] - Network disconnect!
>[20:47:04:938] [25863:25864] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor`

Version, updated today:
> xfreerdp --version
>This is FreeRDP version 2.0.0-dev (git b769d84)

Connection string:
>xfreerdp /u:---- /p:---- /v:----:---- +clipboard +auto-reconnect -decorations /f /bpp:15 +compression /compression-level:2 +bitmap-cache +offscreen-cache +async-update +aero +fonts /gdi:hw

**Comment by akallabeth** [comment]
@mr-wong Which version of OpenSSL (or ubuntu for that matter) do you use?

**Comment by mr-wong** [comment]
@akallabeth I have reduced encryption to Low level (56 bit) inside Group Policy trying to gain max performance on previous very weak laptop, using in 'friendly' environment, so not bothering about security. Anyway, version of libssl is:

>dpkg -l |grep -i libssl
>ii  libssl-dev                                1.0.1-4ubuntu5.33                     SSL development libraries, header files and documentation
>ii  libssl-doc                                1.0.1-4ubuntu5.33                     SSL development documentation documentation
>ii  libssl1.0.0                               1.0.1-4ubuntu5.33                     SSL shared libraries
>ii  libssl1.0.0:i386                          1.0.1-4ubuntu5.33                     SSL shared libraries

Ubuntu 12.04 Unity x64.

**Comment by akallabeth** [comment]
@mr-wong Does this also occur if you use less exotic encryption settings?

**Comment by mr-wong** [comment]
@akallabeth Yes, still persists after I reset all encryption-related settings in GP. Once I was able to push ctrl+alt+enter immediately after resume, then keyboard locked after couple seconds - no response in Ubuntu too, only mouse. Closed terminal tab with rdp and all released, seems rdp hard stealing keyboard input in such conditions.

**Comment by akallabeth** [comment]
Looks like this is caused by #4511
