### ISSUE TITLE
winpr/wtypes.h and winpr/version.h are not created during build

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#3074]
Currently I can not build remmina as the above mentioned files are not created and included for installation.

**Comment by akallabeth** [comment]
@weberhofer Ok, could you give some details on where during the build this fails?
Can generate a working configuration from current master 3e19791bb7ab186568d5f2c8478763d63fdb0305 on debian jessie.

**Comment by weberhofer** [comment]
The build doesn't fail, but the remmina build:

[  146s] make[2]: Entering directory '/home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20160117/build'
[  146s] [ 88%] Building C object remmina-plugins/rdp/CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o
[  146s] cd /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20160117/build/remmina-plugins/rdp &amp;&amp; /usr/bin/cc  -DFREERDP_REQUIRED_MAJOR=2 -DFREERDP_REQUIRED_MINOR=0 -DFREERDP_REQUIRED_REVISION=0 -DHAVE_LIBAVAHI_CLIENT -DHAVE_LIBAVAHI_UI -DHAVE_LIBGCRYPT -DHAVE_LIBSSH -Dremmina_plugin_rdp_EXPORTS -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -DNDEBUG -Wall -fPIC -Wno-unused-result -Wno-unused-but-set-variable -Wno-unused-function -fPIC -I/home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20160117/. -I/home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20160117/remmina/include -I/home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20160117/remmina-plugins -I/usr/include/gtk-3.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/atk-1.0 -I/usr/include/freerdp2 -I/usr/include/winpr1    -o CMakeFiles/remmina-plugin-rdp.dir/rdp_plugin.c.o -c /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20160117/remmina-plugins/rdp/rdp_plugin.c
[  146s] In file included from /usr/include/freerdp2/freerdp/freerdp.h:43:0,
[  146s]                  from /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20160117/remmina-plugins/rdp/rdp_plugin.h:40,
[  146s]                  from /home/abuild/rpmbuild/BUILD/Remmina-1.1.99.git.20160117/remmina-plugins/rdp/rdp_plugin.c:36:
[  146s] /usr/include/freerdp2/freerdp/types.h:24:26: fatal error: winpr/wtypes.h: No such file or directory
[  146s]  #include &lt;winpr/wtypes.h&gt;
[  146s]                           ^
[  146s] compilation terminated.

**Comment by david-geiger** [comment]
Hi,

I have encountered the same issue and I have to patch the CMakeLists.txt from winpr to make installable this two files:

--- winpr/include/CMakeLists.txt.orig	2016-01-02 11:31:39.000000000 +0100
+++ winpr/include/CMakeLists.txt	2016-01-14 08:40:56.000000000 +0100
@@ -20,4 +20,6 @@
 
 file(GLOB WINPR_HEADERS "winpr/*.h")
 install(FILES ${WINPR_HEADERS} DESTINATION include/winpr COMPONENT headers)
+install(FILES ${CMAKE_CURRENT_BINARY_DIR}/winpr/version.h DESTINATION include/winpr COMPONENT headers)
+install(FILES ${CMAKE_CURRENT_BINARY_DIR}/winpr/wtypes.h DESTINATION include/winpr COMPONENT headers)
 install(DIRECTORY winpr/tools DESTINATION include/winpr COMPONENT headers FILES_MATCHING PATTERN "*.h")

Using this snapshot commit: 9b8b1d6480245cc3dbe14d3899a5deb323e5bfe5

**Comment by akallabeth** [comment]
Ah, ok. Looks like we missed something, #3075 should fix that.

**Comment by akallabeth** [comment]
@weberhofer Does this fix your issue?

**Comment by david-geiger** [comment]
Also there is the same issue with two other files on hash and makecert that are compiled but not installed, here the patch that I use to fix this:

--- winpr/tools/makecert/cli/CMakeLists.txt.orig	2015-12-14 10:07:49.057140510 +0100
+++ winpr/tools/makecert/cli/CMakeLists.txt	2015-12-14 10:08:41.961142646 +0100
@@ -45,5 +45,7 @@
 
 target_link_libraries(${MODULE_NAME} ${${MODULE_PREFIX}_LIBS})
 
+install(TARGETS ${MODULE_NAME} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT winpr)
+
 set_property(TARGET ${MODULE_NAME} PROPERTY FOLDER "WinPR/Tools")
 
--- winpr/tools/hash/CMakeLists.txt.orig	2015-12-14 10:15:19.350158690 +0100
+++ winpr/tools/hash/CMakeLists.txt	2015-12-14 10:15:29.123159085 +0100
@@ -43,4 +43,6 @@
 
 target_link_libraries(${MODULE_NAME} ${${MODULE_PREFIX}_LIBS})
 
+install(TARGETS ${MODULE_NAME} RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR} COMPONENT winpr)
+
 set_property(TARGET ${MODULE_NAME} PROPERTY FOLDER "WinPR/Tools")

**Comment by akallabeth** [comment]
@david-geiger The install targets in your last diff are already on master, do you have an old checkout?

**Comment by david-geiger** [comment]
Same snapshot commit as before: 9b8b1d6480245cc3dbe14d3899a5deb323e5bfe5

**Comment by akallabeth** [comment]
Ok, this and some more stuff has already been fixed and merged to master.

**Comment by weberhofer** [comment]
The problem is fixed with #3075, however it's not yet merged to master. Thank you all!
