### ISSUE TITLE
State the copyright owner of FreeRDP in LICENSE file

### ISSUE THREAD

**Issue by ramiromagalhaes** [FreeRDP/FreeRDP#3095]
In line 190 of the LICENSE file, we read:
` Copyright [yyyy] [name of copyright owner]`

The community should clearly state, in this file, who owns the FreeRDP copyright, and state it in this file.

**Comment by bmiklautz** [comment]
@ramiromagalhaes I might be mistaken but as I read line 190 it is just an example for a how APL is applied. If you look into libfreerdp/core/freerdp.c this is used with the copyright section added.

**Comment by ramiromagalhaes** [comment]
True. My bad. Shouldn't that apendix be removed then?

**Comment by bmiklautz** [comment]
@ramiromagalhaes I think the appendix is quite helpful and also provides a nice template. Also it is often contained in LICENSE files as far as I know.
