### ISSUE TITLE
OpenSSL 1.1 compatibility

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#3098]
Tried to compile FreeRDP against the current OpenSSL master (1.1)
Looks like this will be quite a beast to tame,
- many structures are now opaque
- The direct data structure access in `tls.c` is no longer working.

TODO:
- [ ] Merge `libfreerdp` and `winpr` function wrappers for SSL in `winpr`
- [ ] Add `winpr` implementations for the function wrapper for OpenSSL 1.0
- [ ] Add `winpr` implementations for the function wrapper for OpenSSL 1.1
- [ ] Add `winpr` implementations for the function wrapper for MBEDTLS
- [ ] Add `winpr` implementations for the function wrapper for OSX security framework #3022
- [ ] Add `winpr` implementations for the function wrapper for ...

**Comment by hardening** [comment]
Making the struct opaque is quite nice, anyway we needed some internal access to set the error code when shutting down with TLS. I hope they have added a public method to do it...

**Comment by petterreinholdtsen** [comment]
Failing to build with OpenSSL 1.1 is now a release critical bug in Debian, see https://bugs.debian.org/828142 .

**Comment by petterreinholdtsen** [comment]
A draft patch to gain OpenSSL 1.1 compatibility is now available in the Debian bug report.  I believe it need some more work before it is ready.

**Comment by akallabeth** [comment]
@petterreinholdtsen Thank you for the update, unfortunately the main issue with OpenSSL 1.1 compatibility is the use of BIO in tls.c and tcp.c. That will need some work.

**Comment by petterreinholdtsen** [comment]
[akallabeth]
> @petterreinholdtsen Thank you for the update, unfortunately the main
> issue with OpenSSL 1.1 compatibility is the use of BIO in tls.c and
> tcp.c. That will need some work.

OK.  I did not notice any build errors in that part, so I did not have a
look.  Glad to know you are on the case. :)

-- 
Happy hacking
Petter Reinholdtsen

**Comment by akallabeth** [comment]
Great news, @nfedera fixed it with #3615
