### ISSUE TITLE
dfreeRDP screen artifacting (w/ pics)

### ISSUE THREAD

**Issue by disturbedfuel15** [FreeRDP/FreeRDP#3106]
Hello,

I work for a medium size global manufacturing company and here at our U.S. branch, we are trying to implement the raspiTC in order to allow users to remote in to their desktops from the conference room. We have found the only RDP client with acceptable speed to be dFreeRDP. I created a script which I attached a picture of. The point of the script is to change the dfreerdp.server file to the user's desktop, named 'gus-Dxxx' (where xxx is the users desktop number). This way, the user does not have to edit the dfreerdp.server file manually (this would be way too complex for them).

Here is my question: I have tried everything under the sun to get these screen artifacts to disappear. Nine times out of ten, within the first few seconds of logging in to their desktop from dfreerdp, the screen turns into an 'etch-a-sketch' mode, where you can see the entire RPITC desktop, but when you move the mouse, the trail shows the current remote session. I attached a picture for reference, because it is hard to describe. I thought maybe it was the terminal trying to output messages, which could cause this, but even after attempting to suppress the messages with 'nohup' in the command, it still happens. I am lost and I want to be able to use this OS because it truly is thin and fast for our project managers and engineers. I appreciate your time! 
![20160202_114749](https://cloud.githubusercontent.com/assets/17050864/12791245/3b7a7522-ca74-11e5-8de7-59a9051ad25c.jpg)
![20160202_112827](https://cloud.githubusercontent.com/assets/17050864/12791246/3b7b0f6e-ca74-11e5-9228-8dccbdb5bf5d.jpg)

**Comment by hardening** [comment]
Well the DirectFB client really needs love and I think nobody touched it from a quite long time.
I'm surprised that other clients weren't fast enough, can you elaborate on your setup. Optionally knowing which version you're running could help too.

**Comment by disturbedfuel15** [comment]
I tried using dfreerdp included in the Raspberry Pi Thin Client v1.99 package (link included for reference), http://rpitc.blogspot.com/2016/01/rpitc2-release-199-out.html and I also tried an older build (from November I believe).

So we have about 150 Dell Precision workstations which engineers use to create designs in autocad and solidworks.  Each workstation has a massively expensive nvidia quadro graphics card to handle the designs.  So when a customer wants to see progress on the drawing, or whatever, they will all sit in the conference room and the engineer will remote into his desktop from the raspberry pi, hooked up to the 60" TV.

I don't know if it matters, but the drawings are pulled from a server in the server closet, and they can be fairly large.  Also, one project manager has mentioned the problem seems much more consistent when the customer is not physically present, but when they have to have a virtual meeting (desktop sharing with the customer).  I am not sure this at all matters, but I wanted to elaborate.

Also, I tried the other clients but there was way too much lag when the engineers would scroll/pan/rotate the models.  This one was the only one which has MINIMAL lag.  Of course, 1080p video streaming is still out of the question, but dfreerdp works fine for viewing models.

Thank you again!

**Comment by hardening** [comment]
You're not the first that reports lags on the raspberryPi. From previous discussion, it seems that the biggest problem is the poor performance of the Xorg driver.

**Comment by akallabeth** [comment]
@disturbedfuel15 The dfreerdp package is quite out of date and would need some love, on current master it does not compile any more.

**Comment by disturbedfuel15** [comment]
That's really too bad, because it is literally the fastest RDP client to date.  I tried a fresh debian install and regular freerdp-x11, and the lag is so bad, autoCAD and solidworks are out of the question.  There is almost no lag with dfreerdp.

**Comment by akallabeth** [comment]
@disturbedfuel15 Well, it is probably just a matter of adjusting the client API to the FreeRDP2 changes but it would require someone to look after the client.

**Comment by disturbedfuel15** [comment]
I understand.  I also understand it would require some dedicated work from experienced programmers.  For now, I have a workaround  for the users, but just disconnecting and reconnecting.

**Comment by akallabeth** [comment]
@disturbedfuel15 Good to know it works for you, I hope someone will find the time to update the client.

**Comment by bmiklautz** [comment]
@disturbedfuel15 freerdp-x11 in debian is unfortunately really old. For testing give our nightly builds a try they are based on master. https://ci.freerdp.com/job/freerdp-nightly-binaries/. There is also a long standing pull request for  dfreerdp on 1.0 that, according to the author, fixes problems on the rasberry pi: https://github.com/FreeRDP/FreeRDP/pull/2129
So if the nightlies are no good for you, you can try this one.

**Comment by disturbedfuel15** [comment]
If anyone wants to know the solution, 'admin' from the armTC forums replied with the answer.

> The problem is in the FrameBuffer/Xorg surface layer. You have to avoid to have multiple surface rendering active at the same time. If you run dfreedrp from a terminal in the desktop you will see this effect (2 layer active, rendering the terminal in Xorg and the dfreerdp session in the framebuffer layer). If you run the dfreerdp from a icon shortcut or by using the autostart script without a terminal there is no xorg layer to render and you will not see the artifacts.
