### ISSUE TITLE
Won't create .xcodeproj file.

### ISSUE THREAD

**Issue by fraannk** [FreeRDP/FreeRDP#3117]
Hi. I can't get it to create the .xcodeproj file. The error is something to do with openssl. Does anyone have a "already put together" project file/folder I can have. I'm looking to do some optimizations for iPad Pro. Thank you.

**Comment by akallabeth** [comment]
@fraannk You need OpenSSL with development headers installed for your environment. Without the dependencies you will not be able to compile anything. Easiest way currently is probably homebrew or you have to compile OpenSSL yourself.

**Comment by bmiklautz** [comment]
@fraannk as @akallabeth says you will need to compile openssl. Have a look to scripts/OpenSSL-DownloadAndBuild.command

**Comment by fraannk** [comment]
OpenSSL has been compiled successfully, I just needed to redirect the command file to another location. Had to use cmake 3.4.3 to build the project as well. Works now! But it seems like the iOS part hasn't been updated in a loooong time. There's a lot of errors to go through! :)
