### ISSUE TITLE
Option to use the local keyboard layout

### ISSUE THREAD

**Issue by tobia** [FreeRDP/FreeRDP#3121]
The manual says:

> Keyboard mapping is done on the remote end, so the local keyboard layout is ignored. Instead, a Windows keyboard layout id is provided at connection time to tell the server which keyboard layout to use.

This poses a problem in many cases, for example when the local keyboard layout is not present on the remote side (GNU/Linux supports many more locales and specialized keyboard layouts than Windows) or when there are issues with the RDP protocol that prevent setting the remote keyboard ID.

It would be useful to have a "local keyboard" option as a fallback, where the user can tell FreeRDP what the remote keyboard layout is supposed to be and the software translates local symbols to remote scan codes, according to that layout.

For example, if such an option was enabled and set to US keyboard, then:
- a keyboard event that generates "A" in the local keyboard layout would be read by FreeRDP as the symbol "A", ignoring the original scan code;
- FreeRDP would translate it into a scan code of (say) 0x1E, based on the chosen remote layout (US)
- the scan code 0x1E would be sent through RDP.

Therefore, to the remote OS it would look like the "A" key of an US keyboard was pressed, when in reality a completely different key might have generated the "A" symbol in the local keyboard layout.

Does this make sense? Would it be technically feasible?

**Comment by bmiklautz** [comment]
@tobia just to make sure are you hitting a real problem with your setup?

**Comment by tobia** [comment]
In my case I wouldn't say problem, it's just a nuisance.

I use the [Programmer Dvorak](http://www.kaufmann.no/roland/dvorak/) keyboard layout (included in X11 as the "dvp" variant of "us" layout) and apparently there's no way to make it go through FreeRDP, it always ignores my layout and uses Windows keyboard layouts.

I figured this might be a problem for people using a lot of the other locales and layouts available on X11.

I don't know if this is a "feature" of RDP, but in general I think it would be more useful to keep the local keyboard layout, instead of sending raw scan codes. For example, SSH has no concept of "remote keyboard layout", thankfully.

**Comment by tsdh** [comment]
@bmiklautz This is in fact the single problem why I keep on using rdesktop instead of freerdp.

I use a German Dvorak Type II layout (which is available by default on Linux/X11 but not Windows).  When I connect to some remote Windows machine, I think I get a US Dvorak layout where, e.g., the T and the R, are on different positions than in the German variant.  I can hardly type anything.

With rdesktop and without any special option, I can just type my usual local layout which seems to get translated transparently.

**Comment by hardening** [comment]
The supported RDP layout are there:
https://technet.microsoft.com/en-us/library/cc766503%28WS.10%29.aspx

Can you find yours here ?

**Comment by hardening** [comment]
it would be interesting to see the output of setxkbmap -print

**Comment by tsdh** [comment]
@hardening Nope, it's not on that list.  There's just US Dvorak and US Dvorak for right hand.  `xfreerdp /kbd-list` list also " United States-Dvorak for left hand" and "United States-Programmer Dvorak", so it seems freerdp already supports more layouts than those on this list.

And here's the `setxkbmap -print` output:

```
% setxkbmap -print
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwertz)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+de(dvorak)+us:2+inet(evdev)+ctrl(nocaps)"	};
	xkb_geometry  { include "pc(pc104)"	};
};
```

As you can see, I also made CapsLock a third Ctrl (Emacs user ;-)).  However, I can easily live without that on remotes.  With rdesktop, CapsLock also behaves as CapsLock on remotes.

**Comment by metalight** [comment]
+1
This is number 1 issue with FreeRDP!

My keymap layout is defined with xmodmap.
It is a customized "danish-ized" Dvorak layout - it does not exist anywhere as a standard, it is not "danish dvorak".

I have been using this for 12 years.
It is completely ignored by FreeRDP.

I would love to kick the aging and glitching rdesktop - and start using FreeRDP, but this is simply not an option for me now, as I would have to learn a (for me) sub-optimal "standard keymap" first.

**Comment by huguesdk** [comment]
Same here. I’m using a customized version of the French Dvorak layout called [BÉPO](http://bepo.fr/) with some remapped modifiers. It works correctly with rdesktop.

**Comment by ensc** [comment]
alternatively: is there some way to define own layouts?  (Very) old maillist postings mention definitions in `/usr/share/freerdp/keymaps` but this directory does not seem to exist anymore.

**Comment by qralston** [comment]
I swap my ```Ctrl``` and ```Caps Lock``` keys in my keyboard layout. When I use rdesktop, it obeys the swapped keys, but xfreerdp does not.

I can appreciate, from a technical perspective, that xfreerdp's behavior may be more correct. I get it. But simply put: _I don't care_. From my perspective—the user perspective; the most important perspective—xfreerdp's keyboard behavior is broken, and rdesktop's is not.

I can also appreciate that xfreerdp is a better RDP client than rdesktop in almost every way. I would like to switch from rdesktop to xfreerdp. But the broken keyboard handling is a dealbreaker.

Surely there must be some way to resolve this long-standing issue. How can we help?

**Comment by cizra** [comment]
It's mighty unlikely that the FreeRDP project will accept my contribution, on the grounds of insufficient humility towards PEOPLE WHO LOVE TO USE ALL CAPS, but here's a PR with a fix:

https://github.com/FreeRDP/FreeRDP/pull/5301

**Comment by akallabeth** [comment]
@cizra the reason is more like you break an existing working implementation because your use case is not supported.
The way I see it you have 2 options:
1. Implement a keyboard handling similar to the one of `aFreeRDP` and use the unicode input path.
  * Does not allow switch layouts remotely
  * Limited support for target operating systems (you need to test which ones work correctly)
1. Implement a reverse mapping similar to the one used by rdesktop
  * quite error prone and really a lot of work

Either way, it is more than a code change of 1 line ;)
Pull requests welcome, but this kind of mapping is not my use case and I simply don´t have the time to test this.

**Comment by cizra** [comment]
It works for me, so I'll just continue rebasing my fork. Indeed it breaks caps lock but it's only useful for toggling run in FPSes anyway.

**Comment by mojomojomojo** [comment]
In my case, I have caps as another ctrl on both the local linux machine and on the remote Windows machine (kb scan code map). Xfreerdp treats it like a caps lock. )-8

**Comment by ensc** [comment]
Here, `meta` and `alt` are swapped; `left ctrl` ist "mode switch" (e.g. used to create umlauts), `shift` + `left ctrl` is `caps lock`.  Works perfectly with rdesktop but is a blocker for using xfreerdp.

**Comment by kris7t** [comment]
I am using a custom Xkb layout (US english keyboard + Caps Lock as a thrid-level modifier + accented characters from the languages I usually write in. Hence, the existing approach of letting Windows take care of the keyboard layout is quite inconvenient, and, as far as I know, reverse mapping a la rdesktop is not sufficient (there is no WIndows keyboard layout with precisely the symbols I want). Hence, I would be quite interested in using the Unicode input path. How would one go about implementing such a feature? Any pointers to source files worth looking at?

**Comment by akallabeth** [comment]
@kris7t Feel free to experiment.
Pointers here:
* `include/freerdp/input.h` contains the relevant functions
* `freerdp_input_send_keyboard_event` and `freerdp_input_send_keyboard_event_ex` send scancodes (= the codes a key generates when pressed)
* `freerdp_input_send_unicode_keyboard_event` sends unicode events (`UCS2`, 16 bit only)

Sending everything from local symbols is quite easy, only issue we have (and why we never moved forwared) is that windows requires certain stuff to be sent as `scancode` input (most system key combinations et al)

**Comment by kris7t** [comment]
@akallabeth Thanks! I'll take a look when I'll have some free time. :)

**Comment by lemoinem** [comment]
Wouldn't something simpler be easier to implement in the mean time? something like an option with a pair of keys for the map? map key1 to newkey1, key2 to newkey2, etc.?

It wouldn't break anyone not using it and definitely solve the issue of "my caps lock is a control and I want my Pause/Break to be an additional escape or something".

It's not a replacement to @kris7t's solution (which I like quite a bit as well, but solves a different problem, I think).

It's something that's been asked for a long time (at least 2011) and offering the user a way to customize their keyboard would probably help a lot of people, without bothering anyone not caring about that.)

@akallabeth would you be open with this kind of PR? If yes, I'll try to have a look at it.

**Comment by itkfm** [comment]
> GNU/Linux supports many more locales and specialized keyboard layouts than Windows

My biggest problem with this is that Windows will then default to the EN/US layout which is sometimes pretty incompatible to your local layout.
For example, if you're using let's say `at-nodeadkeys` (which is a *QWERZ* layout), you'll get *EN/US* on Windows (a *QWERTY* layout; pretty different). This causes essential keystrokes to be completely different (e.g. `\`, `:` (actually almost all non alpha-numeric keys)),

**Comment by lhzw** [comment]
I changed ESC with caps-lock, it's okay with rdesktop, but with xfreerdp, it's disgusting, very inconvenient.

**Comment by akallabeth** [comment]
@lemoinem that sounds a lot like you try to supply your own keymap (aka map local keys to scancodes) ;) as mentioned, pr welcome.

@itkfm have a look at the `/kbd:` option, that way you can tell the remote windows system which layout to use. (of course, these are only layouts supported by the remote windows system)

**Comment by itkfm** [comment]
@akallabeth doesn't seem to work here.
`xfreerdp /kbd:0x00010407 -u USERNAME -d MYDOMAIN IP.ADD.RES.S` still gives me *EN/US* in Windows. (*German* layout is installed, machine default and select-able in the taskbar, though.) Am I doing something wrong here?

**Comment by akallabeth** [comment]
@itkfm depends on your server os and client version (there have been some changes in newer windows versions that require a client update)

**Comment by cornfeedhobo** [comment]
Maybe the feature request would be to send character codes instead of keycodes? This would effectively translate any client configurations transparently to the server and eliminate all this hassle.

cc @akallabeth @bmiklautz

**Comment by akallabeth** [comment]
@cornfeedhobo well, appeal at microsoft ;)
there is the ability to send unicode charachters, but these are ignored for certain things in windows RDP servers (e.g. `<ctrl>+c` or similar)

**Comment by cornfeedhobo** [comment]
@akallabeth then how come this works with rdesktop and others?

**Comment by cornfeedhobo** [comment]
> there is the ability to send unicode charachters

@akallabeth then this should be implemented. If you read the messages here, people are actively choosing `rdesktop` because of this limitation, which sounds tolerable at first, but please consider that many GUI tools don't allow the user to pick other backends. I have servers that virtualize VMs, and to use FreeRDP in it's current form, I would have to configure multiple components server-side, or I can just use rdesktop and not worry about clobbering a client's configuration.

Please reconsider your stance here. A toggle would not impact the current functionality.

**Comment by akallabeth** [comment]
@cornfeedhobo Nothing against a `unicode keyboard input` switch, pull requests welcome. Just be aware of the above limitation, so some special care should be taken for system key combinations.

As for `rdesktop`, either you´re speaking of something slightly different than the thread is about or they changed their input handling?
As far as I know they only send scancodes and also do not have a unicode input.

**Comment by akallabeth** [comment]
@cornfeedhobo you might check the keyboard layout manipulation functions of FreeRDP, maybe there is already something for your use case:

```
/kbd:0x<id> or <name>             Keyboard layout
    /kbd-lang:0x<id>                  Keyboard active language identifier
    /kbd-fn-key:<value>               Function key value
    /kbd-list                         List keyboard layouts
    /kbd-lang-list                    List keyboard languages
    /kbd-subtype:<id>                 Keyboard subtype
    /kbd-type:<id>                    Keyboard type
```

Anyway, checked the source of `rdesktop`, they do not use unicode keyboard input so the same limitations as for FreeRDP apply.

**Comment by cornfeedhobo** [comment]
@akallabeth It's very possible I'm confused - I'm no RDP expert - I'm an average user at best. However, as [others](https://github.com/FreeRDP/FreeRDP/issues/3121#issuecomment-218441670) [have](https://github.com/FreeRDP/FreeRDP/issues/3121#issuecomment-256730240) [pointed](https://github.com/FreeRDP/FreeRDP/issues/3121#issuecomment-477095607) [out](https://github.com/FreeRDP/FreeRDP/issues/3121#issuecomment-507644432), `rdesktop` does this out of the box by default. I have no idea by what mechanism it's achieving that, but I assume it's not sending scan codes.

**Comment by cornfeedhobo** [comment]
I also played around with keyboard modifications, and like others above in this issue describe, it has 0 affect.

**Comment by akallabeth** [comment]
@cornfeedhobo so which layout does your server use when you use `rdesktop`?

**Comment by cornfeedhobo** [comment]
@akallabeth Locally US dvorak, server is US Qwerty (default), and so is the VM running on that server.

With `rdesktop` I can just connect and go. Things like `alt+tab` don't work, which is fine.

With `xfreerdp` I can change the server's locality manually, but then when I type in the VM console, it too is stuck using qwerty. I have not tested `ctrl/alt+` combinations.

**Comment by akallabeth** [comment]
@cornfeedhobo ok, just tried `rdesktop`, they do some other translation, but even a simple `german` to `english` translation is quite screwed up, whereas `/kbd:0x00000407` selects the proper keyboard layout remote (note: only works with a new session, so you always need to `logout` first)

**Comment by akallabeth** [comment]
@cornfeedhobo Maybe one of these will help you:

```
0x00010409	United States - Dvorak
0x00030409	United States-Dvorak for left hand
0x00040409	United States-Dvorak for right hand
0x00010409	United States-Dvorak
0x00030409	United States-Dvorak for left hand
0x00040409	United States-Dvorak for right hand
0x19360409	United States-Programmer Dvorak
```

**Comment by cornfeedhobo** [comment]
@akallabeth unfortunately setting `0x00010409` only works on the server being logged into and has no affect on things running inside it or things it connects to. For example, it's common for corporate servers to host RDP "workstations" and then expect you to RDP into clients. `rdesktop` made this very smooth by making the translation transparent.

**Comment by cornfeedhobo** [comment]
> ok, just tried rdesktop, they do some other translation

Well this is sad :(

I appreciate you looking into this. Hopefully someone comes up with an elegant solution soon. `rdesktop` is showing it's age.

**Comment by akallabeth** [comment]
@cornfeedhobo you might want to have a look at `FreeRDP` from `master` branch.
That one has an additional option`/kbd-remap` which might be applicable to your use case.
You can supply a list of `<local scancode>=<remote scancode>` values which allow remapping of keys.

**Comment by ensc** [comment]
it is not only the layout. `rdesktop` works fine with custom `~/.Xmodmap` setup.  E.g. swapping `ctrl-l` and `caps-lock`

```
keycode 66  = Control_L
keycode 37  = Mode_switch Caps_Lock
```

I do not think that there exists a keyboard layout which can be specified with `/kbd-XXX`

**Comment by akallabeth** [comment]
Ok, I had a look at this and created #7284.
That one works against windows RDP servers, `ogon` and at least `xrdp` 0.9.12

It takes the local key pressed and does not send the scancode, but the symbol as unicode.
That way the local keyboard layout is used while ignoring what is installed on the server.

Please test it, as it requires fallback for some symbols (e.g. `Return` must be send as scancode as well as `ctrl` et al)

**Comment by cornfeedhobo** [comment]
@akallabeth Sorry I didn't see this sooner. Unfortunately I don't have a good host to compile on at the moment. Is there any CI that drops artifacts from HEAD? If not, I can probably build in a VM.

**Comment by akallabeth** [comment]
@cornfeedhobo the current nightly builds should already contain this fix. Just add `/kbd-unicode`

**Comment by cornfeedhobo** [comment]
Unfortunately I have been unable to get the newest version to run at all. I keep getting linking errors on opensuse.

**Comment by Outtay** [comment]
@akallabeth I have (of course) another system configuration. I use a German specialized keyboard layout called "Neo2". I've tried the solution with the `/kbd-unicode` switch and it's probably a good solution for most people. For my specific case the problem is that my Backspace isn't working now and the "Backspace" character is now inserted.
Furthermore, my layout has multiple layers: the "third" layer can be activated via Caps Lock or with the "hashtag"-symbol key that's on German Keyboards next to the Return key. Now if I want to use the third layer via the hashtag-symbol, it works but also writes a "hashtag" every time I want to just activate the layer. 
Furthermore, I can activate a fourth layer with the right "Alt"-Modifier where I have arrow keys accessible with esdf (next to WASD) and those don't work at all.
All those things work flawlessly with rdesktop, but rdesktop is currently unusable for me as it either takes 5+ times to connect or it won't connect at all, and the latter case seems to happen more frequently now.

But generally speaking: probably a good solution for most people with that problem.

**Comment by cornfeedhobo** [comment]
I ended up getting the newer release running and `/kbd-unicode` does nothing to change my situation with dvorak. I'll try again if anyone has suggestions.

**Comment by RolKau** [comment]
@tobia 
Sorry to barge in on this very old thread; I don't know if this is still a problem, but I happened to stumble over this and just wanted to comment on the following:

> I use the Programmer Dvorak keyboard layout (included in X11 as the "dvp" variant of "us" layout) and apparently there's no way to make it go through FreeRDP, it always ignores my layout and uses Windows keyboard layouts.

RDP only sends scan codes. When you connect, you can set the (Windows) ID of the keyboard layout that you prefer at the server end. FreeRDP is supposed to map from the local Xkb setting into a set of known layouts to send, but you can anyway override/ensure this with for instance `/kbd:0x19360409` option to get Programmer Dvorak. For this to be successful, the layout must be installed on the server, i.e. there must be a keyboard layout with that ID.

**Comment by dnso86** [comment]
> RDP only sends scan codes. When you connect, you can set the (Windows) ID of the keyboard layout that you prefer at the server end. FreeRDP is supposed to map from the local Xkb setting into a set of known layouts to send, but you can anyway override/ensure this with for instance `/kbd:0x19360409` option to get Programmer Dvorak. For this to be successful, the layout must be installed on the server, i.e. there must be a keyboard layout with that ID.

This helps @RolKau, thank you for sharing!
FWIW in version 3.15.0, it seems the syntax of the option in the Programmer Dvorak example would look like `/kbd:layout:0x19360409`
