### ISSUE TITLE
when I am trying to execute MacMinis-Mac-mini:FreeRDP-master macmini$ cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode  getting compiling issues

### ISSUE THREAD

**Issue by VinodJagtap** [FreeRDP/FreeRDP#3125]
mac osx 10.11
xcode 7.2
when is execute  MacMinis-Mac-mini:FreeRDP-master macmini$ cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode 
-- FreeRDP GIT
-- Git Revision n/a
-- Skipping recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature OSS for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Skipping optional feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Enable feature FFmpeg using "-DWITH_FFMPEG=ON"
-- Skipping disabled feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
-- Skipping disabled feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- FreeRDP GIT
-- FreeRDP GIT
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Adding iOS client
-- Configuring done
-- Generating done

**Comment by akallabeth** [comment]
@VinodJagtap And what is the issue? looks like ```cmake``` generated the Xcode project just fine...

**Comment by VinodJagtap** [comment]
yes working but when I am compiling freeRDP.xcodeproj generated by cmake command its giving error about stdio.h,_mingw.h files not found, when I am adding that also not working...Is that issue of .xcodeproj not get generated properly?

**Comment by akallabeth** [comment]
@VinodJagtap I'd recommend reading ```docs/README.ios``` and prepare the environment accordingly.

**Comment by VinodJagtap** [comment]
I have followed same steps mentioned in docs/README.ios  still not working...what can be the issues?

**Comment by akallabeth** [comment]
@VinodJagtap Hard to guess without some hints ;)

**Comment by akallabeth** [comment]
@VinodJagtap Just compiled it, the OpenSSL build script needs some love (update version, use ```shasum``` instead of md5) and select target iOS device, simulator targets do not work.

**Comment by VinodJagtap** [comment]
Are you getting  issues related .c files not found...? and I am using latest OpenSSL

**Comment by akallabeth** [comment]
@VinodJagtap No issues at all, just a bunch of warnings during compile. Please start with a clean checkout, build OpenSSL and the open in XCode. Select the iOS target there (NOT the simulator target selected by default!)

**Comment by VinodJagtap** [comment]
worked fine but getting linker error
clang: error: linker command failed with exit code 1 (use -v to see invocation)


ld: in /Users/macmini/desktop/ifreeRDP/FreeRDP-master/external/openssl/lib/libcrypto.a(bio_lib.o), building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

**Comment by akallabeth** [comment]
@VinodJagtap looks like you built openssl for the wrong architecture. anyway, this is a issue tracker not a support forum. use the irc channel for that.
