### ISSUE TITLE
Compiling FreeRDP on Linux for Windows

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#3132]
Hey all,

I am working on a new cross platform applet for freerdp/ssh/vnc and I am trying to follow the wiki compilation instructions on how to compile the executable for Windows on Linux. 

I am running Arch Linux
I have the latest source code from this repository and have the latest from master
I have compiled / installed openssl for Windows already on Linux and have confirmed that the openssl.exe binary works on Windows
I created my build directory mingw64_build in my cloned root source folder

Below is the cmake command I ran

cmake -DCMAKE_SYSTEM_NAME="Windows" \
      -DCMAKE_C_COMPILER="/usr/bin/x86_64-w64-mingw32-gcc" \
      -DCMAKE_RC_COMPILER="/usr/bin/x86_64-w64-mingw32-windres" \
      -DCMAKE_INSTALL_PREFIX="/opt/mingw64" \
      -DBUILD_SHARED_LIBS=OFF \
      -DCMAKE_C_FLAGS="-DFREERDP_EXPORTS -Dsprintf_s=snprintf" \
      -DCMAKE_EXE_LINKER_FLAGS="-L/opt/mingw64/lib" \
      -DWITH_SSE2=OFF \
      -DWITH_SSE2_TARGET=OFF \
      -DOPENSSL_INCLUDE_DIR="/opt/mingw64/include" \
      -DLIB_EAY="/opt/mingw64/lib/libcrypto.a" \
      -DSSL_EAY="/opt/mingw64/lib/libssl.a" \
      ..

Below is my output from the configuration process. 

Determining if the C compiler works failed with the following output:
Change Dir: /mnt/storage/source/FreeRDP/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4e843/fast"
/usr/bin/make -f CMakeFiles/cmTC_4e843.dir/build.make CMakeFiles/cmTC_4e843.dir/build
make[1]: Entering directory '/mnt/storage/source/FreeRDP/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_4e843.dir/testCCompiler.c.o
/usr/bin/x86_64-w64-mingw32-gcc     -o CMakeFiles/cmTC_4e843.dir/testCCompiler.c.o   -c /mnt/storage/source/FreeRDP/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_4e843
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_4e843.dir/link.txt --verbose=1
/usr/bin/x86_64-w64-mingw32-gcc       CMakeFiles/cmTC_4e843.dir/testCCompiler.c.o  -o cmTC_4e843 -rdynamic
x86_64-w64-mingw32-gcc: error: unrecognized command line option ‘-rdynamic’
CMakeFiles/cmTC_4e843.dir/build.make:97: recipe for target 'cmTC_4e843' failed
make[1]: *** [cmTC_4e843] Error 1
make[1]: Leaving directory '/mnt/storage/source/FreeRDP/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_4e843/fast' failed
make: *** [cmTC_4e843/fast] Error 2

**Comment by bmiklautz** [comment]
@meanbunny I'm sorry to say but as far as I'm aware of we don't officially support mingw.
Besides some mingw options itself (as you describe above) there are several other problems. As far as I remember mingw has some defines that usually only set on unix/linux. So for the build there are there are Unix/Linux and Windows specific options and definitions enabled which leads to  re-definitions and other effects. And since there is a native working client nobody took on and cleaned this up (I think this will require a lot of extra checks in the code to support mingw cleanly).
My suggestion would be to do native windows build.

**Comment by meanbunny** [comment]
Ok gotcha, is there a good resource for compiling for FreeRDP natively on Windows? I just tried using cmake gui for Windows to generate the configuration files but got errors on generating the make files. Looks like I got some missing dependencies

**Comment by bmiklautz** [comment]
@meanbunny basically you need a pre-compiled openssl (I think also requires perl for building), git, cmake and visual studio.
* Build openssl for 64 bit (perl Configure VC-WIN64A)
* FreeRDP itself is then quite easy just run cmake.exe -G "NMake Makefiles" -DBUILD_SHARED_LIBS=OFF -DMSVC_RUNTIME=static -DWITH_SSE2=ON form a "Visual Studio x64 Cross Tools Command Prompt"
