### ISSUE TITLE
Latest Android disconnecting from session

### ISSUE THREAD

**Issue by mithunkundu1983** [FreeRDP/FreeRDP#3134]
02-15 18:21:32.235 18547-18547/com.freerdp.afreerdp V/HomeActivity: Clicked on item id 1 in section Manual Connections
02-15 18:21:32.270 18547-18547/com.freerdp.afreerdp V/HomeActivity: HomeActivity.onPause
02-15 18:21:32.316 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onCreate
02-15 18:21:32.328 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onStart
02-15 18:21:32.329 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onResume
02-15 18:21:32.336 18547-18547/com.freerdp.afreerdp V/SessionView: 0x0
02-15 18:21:32.336 18547-18547/com.freerdp.afreerdp V/SessionView: 0x0
02-15 18:21:32.355 18547-18547/com.freerdp.afreerdp V/SessionView: 0x0
02-15 18:21:32.355 18547-18547/com.freerdp.afreerdp V/SessionView: 0x0
02-15 18:21:32.360 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Screen Resolution: automatic
02-15 18:21:32.375 18547-8666/com.freerdp.afreerdp D/com.freerdp.client.common.cmdline: [pid=18547:tid=9e990930] - windows: 0/1 posix: -1000/0 compat: -1000/0
02-15 18:21:32.376 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android: [pid=18547:tid=9e4f2930] - Start...
02-15 18:21:32.376 18547-8667/com.freerdp.afreerdp D/com.freerdp.channels.cliprdr.client: [pid=18547:tid=9e4f2930] - VirtualChannelEntry
02-15 18:21:32.376 18547-8667/com.freerdp.afreerdp I/com.freerdp.client.common.cmdline: [pid=18547:tid=9e4f2930] - loading channel cliprdr
02-15 18:21:32.376 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - java_callback: OnPreConnect ((I)V)
02-15 18:21:32.376 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - android_java_callback: attaching current thread
02-15 18:21:32.376 18547-8667/com.freerdp.afreerdp V/GlobalApp: OnPreConnect
02-15 18:21:32.377 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - Enabling security layer negotiation: TRUE
02-15 18:21:32.377 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - Enabling restricted admin mode: FALSE
02-15 18:21:32.377 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - Enabling RDP security: TRUE
02-15 18:21:32.377 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - Enabling TLS security: TRUE
02-15 18:21:32.377 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - Enabling NLA security: TRUE
02-15 18:21:32.377 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - Enabling NLA extended security: FALSE
02-15 18:21:32.377 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - state: NEGO_STATE_NLA
02-15 18:21:32.377 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - Attempting NLA security
02-15 18:21:32.391 18547-18547/com.freerdp.afreerdp V/SessionView: 0x0
02-15 18:21:32.391 18547-18547/com.freerdp.afreerdp V/SessionView: 0x0
02-15 18:21:32.439 18547-18591/com.freerdp.afreerdp D/OpenGLRenderer: endAllStagingAnimators on 0xb4da3200 (ListView) with handle 0x9b309a10
02-15 18:21:32.883 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.transport: [pid=18547:tid=9e94f930] - Asynchronous transport thread started
02-15 18:21:32.884 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - RequestedProtocols: 3
02-15 18:21:33.291 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - RDP_NEG_RSP
02-15 18:21:33.291 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - selected_protocol: 2
02-15 18:21:33.291 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - state: NEGO_STATE_FINAL
02-15 18:21:33.291 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - Negotiated NLA security
02-15 18:21:33.292 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nego: [pid=18547:tid=9e4f2930] - nego_security_connect with PROTOCOL_NLA
02-15 18:21:34.522 18547-8667/com.freerdp.afreerdp D/com.winpr.sspi: [pid=18547:tid=9e4f2930] - InitSecurityInterfaceExA
02-15 18:21:34.522 18547-8667/com.freerdp.afreerdp V/com.freerdp.core.nla: [pid=18547:tid=9e4f2930] -  InitializeSecurityContext status SEC_I_CONTINUE_NEEDED [00090312]
02-15 18:21:34.522 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nla: [pid=18547:tid=9e4f2930] - Sending Authentication Token
02-15 18:21:34.527 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nla: [pid=18547:tid=9e4f2930] - 0000 4e 54 4c 4d 53 53 50 00 01 00 00 00 b7 82 08 e2 NTLMSSP.........
02-15 18:21:34.527 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nla: [pid=18547:tid=9e4f2930] - 0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................
02-15 18:21:34.527 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nla: [pid=18547:tid=9e4f2930] - 0020 06 01 b1 1d 00 00 00 0f                         ........
02-15 18:21:34.930 18547-8667/com.freerdp.afreerdp V/com.freerdp.core.nla: [pid=18547:tid=9e4f2930] - InitializeSecurityContext  SEC_I_COMPLETE_NEEDED [00090313]
02-15 18:21:34.930 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.nla: [pid=18547:tid=9e4f2930] - Sending Authentication Token
02-15 18:21:35.750 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.gcc: [pid=18547:tid=9e4f2930] - Server rdp encryption method: NONE
02-15 18:21:38.823 18547-8667/com.freerdp.afreerdp E/com.freerdp.locale: [pid=18547:tid=9e4f2930] - Unable to detect time zone
02-15 18:21:39.437 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e4f2930] - recv Monitor LayoutFrameAcknowledge Data PDU (0x37), length: 42
02-15 18:21:40.253 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e4f2930] - recv Synchronize Data PDU (0x1F), length: 22
02-15 18:21:40.254 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e4f2930] - recv Control Data PDU (0x14), length: 26
02-15 18:21:40.254 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e4f2930] - recv Control Data PDU (0x14), length: 26
02-15 18:21:40.256 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e4f2930] - recv Font Map Data PDU (0x28), length: 26
02-15 18:21:40.256 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - java_callback: OnSettingsChanged ((IIII)V)
02-15 18:21:40.256 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - android_java_callback: attaching current thread
02-15 18:21:40.260 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - java_callback: OnConnectionSuccess ((I)V)
02-15 18:21:40.260 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - android_java_callback: attaching current thread
02-15 18:21:40.263 18547-8667/com.freerdp.afreerdp V/GlobalApp: OnConnectionSuccess
02-15 18:21:40.267 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.transport: [pid=18547:tid=9e94f930] - connectedEvent event triggered
02-15 18:21:40.268 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e94f930] - AltSecFrameMarker: action: Begin (0)
02-15 18:21:40.268 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e94f930] - AltSecFrameMarker: action: End (1)
02-15 18:21:40.270 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e94f930] - AltSecFrameMarker: action: Begin (0)
02-15 18:21:40.270 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e94f930] - CacheBitmapCompressedV2
02-15 18:21:40.271 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e94f930] - CacheBitmapCompressedV2
02-15 18:21:40.274 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android: [pid=18547:tid=9e4f2930] - AsyncInput=1
02-15 18:21:40.274 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: OnConnectionSuccess
02-15 18:21:40.274 18547-18547/com.freerdp.afreerdp V/SessionActivity: bindSession called
02-15 18:21:40.275 18547-8893/com.freerdp.afreerdp D/com.freerdp.client.android: [pid=18547:tid=9c8d1930] - input_thread Start.
02-15 18:21:40.276 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e94f930] - MemBlt
02-15 18:21:40.276 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e94f930] - MemBlt
02-15 18:21:40.287 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - AltSecFrameMarker: action: Begin (0)
02-15 18:21:40.288 18547-8892/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9c9d0930] - java_callback: OnGraphicsUpdate ((IIIII)V)
02-15 18:21:40.290 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e94f930] - MemBlt
02-15 18:21:40.290 18547-8892/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9c9d0930] - android_java_callback: attaching current thread
02-15 18:21:40.291 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - CacheBitmapCompressedV2
02-15 18:21:40.291 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - MemBlt
02-15 18:21:40.291 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - CacheBitmapCompressedV2
02-15 18:21:40.292 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - MemBlt
02-15 18:21:40.296 18547-18547/com.freerdp.afreerdp V/SessionView: 3378x2112
02-15 18:21:40.296 18547-18547/com.freerdp.afreerdp V/SessionView: 3378x2112
02-15 18:21:40.313 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - MemBlt
02-15 18:21:40.313 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - CacheBitmapCompressedV2
02-15 18:21:40.314 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - MemBlt
02-15 18:21:40.314 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - MemBlt
02-15 18:21:40.314 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - MemBlt
02-15 18:21:40.314 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.update: [pid=18547:tid=9e4f2930] - MemBlt
02-15 18:21:41.318 18547-8892/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9c9d0930] - java_callback: OnGraphicsUpdate ((IIIII)V)
02-15 18:21:41.319 18547-8892/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9c9d0930] - android_java_callback: attaching current thread
02-15 18:21:41.484 18547-8667/com.freerdp.afreerdp E/com.freerdp.core.fastpath: [pid=18547:tid=9e4f2930] - Stream_GetRemainingLength() < size
02-15 18:21:41.484 18547-8667/com.freerdp.afreerdp E/com.freerdp.core.fastpath: [pid=18547:tid=9e4f2930] - fastpath_recv_update_data() fail
02-15 18:21:41.484 18547-8684/com.freerdp.afreerdp E/com.freerdp.core.update: [pid=18547:tid=9e94f930] - invalid xorBpp 19723
02-15 18:21:41.484 18547-8684/com.freerdp.afreerdp E/com.freerdp.core.fastpath: [pid=18547:tid=9e94f930] - FASTPATH_UPDATETYPE_POINTER - update_read_pointer_new()
02-15 18:21:41.484 18547-8684/com.freerdp.afreerdp E/com.freerdp.core.fastpath: [pid=18547:tid=9e94f930] - fastpath_recv_update() - -1
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp E/com.freerdp.core.fastpath: [pid=18547:tid=9e94f930] - fastpath_recv_update_data() fail
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e94f930] - CONNECTION_STATE_ACTIVE - rdp_recv_pdu() - -1
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp E/com.freerdp.core.transport: [pid=18547:tid=9e94f930] - transport_check_fds: transport->ReceiveCallback() - -1
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e94f930] - transport_check_fds() - -1
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp D/com.freerdp.core: [pid=18547:tid=9e94f930] - rdp_check_fds() - -1
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp E/com.freerdp.core: [pid=18547:tid=9e94f930] - freerdp_check_fds() failed - 0
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp E/com.freerdp.core.transport: [pid=18547:tid=9e94f930] - freerdp_check_event_handles()
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp I/com.freerdp.core: [pid=18547:tid=9e94f930] - ERRINFO_PEER_DISCONNECTED (0x00001196):The peer connection was lost.
02-15 18:21:41.485 18547-8684/com.freerdp.afreerdp D/com.freerdp.core.transport: [pid=18547:tid=9e94f930] - Terminating transport thread
02-15 18:21:41.486 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e4f2930] - CONNECTION_STATE_ACTIVE - rdp_recv_pdu() - -1
02-15 18:21:41.486 18547-8667/com.freerdp.afreerdp E/com.freerdp.core.transport: [pid=18547:tid=9e4f2930] - transport_check_fds: transport->ReceiveCallback() - -1
02-15 18:21:41.486 18547-8667/com.freerdp.afreerdp D/com.freerdp.core.rdp: [pid=18547:tid=9e4f2930] - transport_check_fds() - -1
02-15 18:21:41.486 18547-8667/com.freerdp.afreerdp D/com.freerdp.core: [pid=18547:tid=9e4f2930] - rdp_check_fds() - -1
02-15 18:21:41.486 18547-8667/com.freerdp.afreerdp E/com.freerdp.core: [pid=18547:tid=9e4f2930] - freerdp_check_fds() failed - 0
02-15 18:21:41.486 18547-8667/com.freerdp.afreerdp E/com.freerdp.client.android: [pid=18547:tid=9e4f2930] - Failed to check FreeRDP file descriptor
02-15 18:21:41.486 18547-8667/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=18547:tid=9e4f2930] - Prepare shutdown...
02-15 18:21:41.486 18547-8893/com.freerdp.afreerdp D/com.freerdp.client.android: [pid=18547:tid=9c8d1930] - input_thread Quit.
02-15 18:21:41.489 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - java_callback: OnDisconnecting ((I)V)
02-15 18:21:41.489 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - android_java_callback: attaching current thread
02-15 18:21:41.490 18547-8667/com.freerdp.afreerdp V/GlobalApp: OnDisconnecting
02-15 18:21:41.493 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: OnDisconnected
02-15 18:21:41.497 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - java_callback: OnDisconnected ((I)V)
02-15 18:21:41.497 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android.callback: [pid=18547:tid=9e4f2930] - android_java_callback: attaching current thread
02-15 18:21:41.498 18547-8667/com.freerdp.afreerdp V/GlobalApp: OnDisconnected
02-15 18:21:41.498 18547-8667/com.freerdp.afreerdp D/com.freerdp.client.android: [pid=18547:tid=9e4f2930] - Quit.
02-15 18:21:41.505 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onPause
02-15 18:21:41.509 18547-18547/com.freerdp.afreerdp V/HomeActivity: HomeActivity.onResume
02-15 18:21:41.850 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onStop
02-15 18:21:41.850 18547-18547/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onDestroy

**Comment by bmiklautz** [comment]
@mithunkundu1983 thanks for the log but without more detail information it's not much of a use ;(.
* what exact git commit are you using?
* what server did you connect do
* which settings did you use?

**Comment by mithunkundu1983** [comment]
what exact git commit are you using? - 2a3e999
what server did you connect do - Windows 2013 erver
which settings did you use? - basic setup. Only host & password.

**Comment by mithunkundu1983** [comment]
02-16 12:58:55.036 5638-21578/com.freerdp.afreerdp E/com.freerdp.core.rdp: [pid=5638:tid=9db7f930] - rdp_recv_fastpath_pdu: rdp_decrypt() fail
02-16 12:58:55.036 5638-21578/com.freerdp.afreerdp E/com.freerdp.core.transport: [pid=5638:tid=9db7f930] - transport_check_fds: transport->ReceiveCallback() - -1
02-16 12:58:55.038 5638-21578/com.freerdp.afreerdp E/com.freerdp.core: [pid=5638:tid=9db7f930] - freerdp_check_fds() failed - 0
02-16 12:58:55.038 5638-21578/com.freerdp.afreerdp E/com.freerdp.core.transport: [pid=5638:tid=9db7f930] - freerdp_check_event_handles()
02-16 12:58:55.044 5638-21561/com.freerdp.afreerdp E/com.freerdp.codec.mppc: [pid=5638:tid=9dd3f930] - history buffer index out of range
02-16 12:58:55.044 5638-21561/com.freerdp.afreerdp E/com.freerdp.core: [pid=5638:tid=9dd3f930] - Decompression failure!
02-16 12:58:55.044 5638-21561/com.freerdp.afreerdp E/com.freerdp.core.fastpath: [pid=5638:tid=9dd3f930] - bulk_decompress() failed
02-16 12:58:55.045 5638-21561/com.freerdp.afreerdp E/com.freerdp.core.fastpath: [pid=5638:tid=9dd3f930] - fastpath_recv_update_data() fail
02-16 12:58:55.045 5638-21561/com.freerdp.afreerdp E/com.freerdp.core.transport: [pid=5638:tid=9dd3f930] - transport_check_fds: transport->ReceiveCallback() - -1
02-16 12:58:55.046 5638-21561/com.freerdp.afreerdp E/com.freerdp.core: [pid=5638:tid=9dd3f930] - freerdp_check_fds() failed - 0
02-16 12:58:55.047 5638-21561/com.freerdp.afreerdp E/com.freerdp.client.android: [pid=5638:tid=9dd3f930] - Failed to check FreeRDP file descriptor
02-16 12:58:55.047 5638-21561/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=5638:tid=9dd3f930] - Prepare shutdown...
02-16 12:58:55.047 5638-21658/com.freerdp.afreerdp D/com.freerdp.client.android: [pid=5638:tid=9c720930] - input_thread Quit.


Looks like Decompression failure! causing failure.
Its connecting. Then showing screen momentarily. Then disconnecting.

**Comment by akallabeth** [comment]
@mithunkundu1983 could you check which settings are active by default and try to enable / disable them? specially the async options, maybe there is a bug with one of them.

**Comment by mithunkundu1983** [comment]
Putting off Debug options works perfectly.

-------------------------------------------------------------------
Thanks & Regards
Mithun Kundu

**Comment by akallabeth** [comment]
@mithunkundu1983 Could you point out the option that did fix the disconnects for you?

**Comment by akallabeth** [comment]
@mithunkundu1983 #3160 fixes an issue with async-update. Can you confirm your issue is with async-update?

**Comment by mvojjala** [comment]
@akallabeth 

I took the latest code base (as of March 8th, top of the tree commit id: 30325f189).   I still see this issue.    Session disconnects immediately after connect. 

Disabling the "Async Channel" and "Async transport",  works perfectly.

Can you help me the performance sideeffects of disabling these options. May be these options allows data to be processed on separate  threads. Will there be significant performance hit observed by disabling these options ?

Thanks

**Comment by akallabeth** [comment]
@mvojjala To my knowledge only async-transport has issues. As for performance, this depends highly on your devices, so I can't tell for sure.

**Comment by akallabeth** [comment]
This is probably caused by #3238
