### ISSUE TITLE
Compiling FreeRDP on Windows

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#3135]
Hey All,

So I have downloaded the latest source from master on my Windows machine. Pre-compiled OpenSSL for 64 bit windows.

Ran the following command under Visual Studio 2013 Command Line Tools

C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64>"c:\Program Files (x86)\CMake\bin\cmake.exe" D:\source\Meanbunny\FreeRDP -G "NMake Makefiles" -DBUILD_SHARED_LIBS=OFF -DMSVC_RUNTIME=static -DWITH_SSE2=ON -DOPENSSL_ROOT_DIR=D:\source\Meanbunny\openssl -DOPENSSL_LIBRARIES=D:\source\Meanbunny\openssl\ssl

Got the following output down here. Says it could not find openssl but then says it found version 1.0.2f. Any hints??

-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- FreeRDP GIT
-- Git Revision 2a3e999
-- Use the MSVC static runtime option carefully!
-- OpenSSL uses /MD by default, and is very picky
-- Random freeing errors are a common sign of runtime issues
-- MSVC: using statically-linked runtime (/MT and /MTd).
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Skipping disabled feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES) (found
  version "1.0.2f")
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpenSSL.cmake:307 (find_package_handle_standard_args)
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:660 (find_feature)

-- Configuring incomplete, errors occurred!

**Comment by hardening** [comment]
This is an issue tracker, not a help forum. You have IRC or the mailing list for that.
