### ISSUE TITLE
multimon spans monitors depending on the monitors selected

### ISSUE THREAD

**Issue by jasonblewis** [FreeRDP/FreeRDP#3137]
If I launch with

```
xfreerdp +clipboard -grab-keyboard /multimon /monitors:0,1 /u:jason /v:somehost
```

Windows 10 sees the display as one large desktop, spanning both monitors.
if I launch with 

```
xfreerdp +clipboard -grab-keyboard /multimon /monitors:1,2 /u:jason /v:somehost
```

Windows 10 sees the display as 2 monitors, and correctly spans them

```
xfreerdp --version
This is FreeRDP version 2.0.0-dev (git 2a3e999)
```

I have 3 monitors commected to this computer.

```
xfreerdp /monitor-list
      * [0] 1920x1080   +3840+120
        [1] 1920x1200   +0+0
        [2] 1920x1200   +1920+0
```

**Comment by nikolay-n** [comment]
I have the same issue but in my case it doesn't matter which monitors I choose (0,1 or 2) Windows 7 sees the display always as one large desktop.
```
$xfreerdp -version
This is FreeRDP version 2.0.0-dev (git c3ce0c3)
```

```
$xfreerdp /monitor-list
      * [0] 1920x1080	+3840+0
        [1] 1920x1080	+1920+0
        [2] 1920x1080	+0+0
```

**Comment by vkovalchuk** [comment]
I am using also +smart-sizing, does it help?

**Comment by patrick-hill** [comment]
I'm also having this issue. Triple monitors but only want to use 2nd and 3rd. Using /multimon grabs all three (which is great) but adding which monitors forces the display to span those monitors.

`xfreerdp /multimon /monitors:1,2 /d:xxx /u:xxx /v:xxx +smart-sizing`

**Comment by akallabeth** [comment]
There are the pull requests #4187 and #4186 . Do they solve this issue?

**Comment by akallabeth** [comment]
Looks like this is the same as #3993 so you created a duplicate ^^
The bug you describe here works on current nightly (as long as threre are no gaps between monitors), so closing this.
Rest tracked in the newer issue.

**Comment by Thomish** [comment]
I found a solution that works for me.
Install ARandR
Use that to position the display so that the RDP works.
Then save it and add your FreeRDP command line.
Now you have a launcher that fixes the positions and starts the RDP connection.
