### ISSUE TITLE
iOS freerdp  rdpdr_process_connect failed with error 1359!

### ISSUE THREAD

**Issue by cloudecker** [FreeRDP/FreeRDP#3141]
This error? I'm missing?

**Comment by akallabeth** [comment]
@cloudecker Without further information this issue is useless. If you need basic information on how to use FreeRDP please use the mailing list and / or IRC channel first.

**Comment by cloudecker** [comment]
My latest cmake ifreerdp. Ifreerdp has three problems
1, there is no sound redirection
2, when I redirect the clipboard or printer, there will be a 1359 error code
3, RDP connection time over a certain period of time (about 1 hour or so), will be interrupted, the reason for the error:
Rdp_check_fds failed
I then ifreerdp, has done the following Settings:
Settings - > DeviceRedirection = YES;
Settings - > SupportDynamicChannels = YES;
Settings - > RemdeskVirtualChannel = YES;
Settings - > AudioPlayback = YES;
Settings - > AudioCapture = YES;
Settings - > RedirectClipboard = NO.
Settings - > RedirectPrinters = NO.
Settings - > RedirectSmartCards = NO.
Settings - > RedirectDrives = YES;
Settings - > RedirectHomeDrive = NO.
Settings - > DynamicDaylightTimeDisabled = YES;
And, after the success of landing RDP, log shows:
[17:17:57:119] [1170:40421000] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[17:17:57:120] [1170:40421000] [INFO][com.freerdp.client.common.cmdline] - loading channel remdesk
[17:17:57:121] [1170:40421000] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[17:17:57:122] [1170:40421000] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
I'm troubled, I do not know why. Thank you for your effective reply.

**Comment by akallabeth** [comment]
@cloudecker iOS client has not seen many updates in recent months, it may be required to adjust / fix support for anything beyond simple RDP connections.

**Comment by DieselV** [comment]
@cloudecker do you have any idea how to enable sound redirection and printer device redirection?

**Comment by akallabeth** [comment]
easiest way is to ditch the manual setting of settings struct and just use ```freerdp_client_settings_parse_command_line``` with the same command line options as xfreerdp / wfreerdp / ...

**Comment by DieselV** [comment]
I am working with freerdp iOS client(iFreeRDP)...your solution will work with iOS?

**Comment by cloudecker** [comment]
@DieselV sorry..i have no idea. IOS cilent can work without sound redirection.

**Comment by DieselV** [comment]
yeah..I works without sound redirection But i want redirect sound
But it shows message while compiling ...skipping disabled feature ALSA(sound redirection)

**Comment by bmiklautz** [comment]
@DieselV there isn't any alsa on iOS. What you are looking for is channels/rdpsnd/client/ios

**Comment by lobojoy** [comment]
@cloudecker How you  made following settings -Settings - > DeviceRedirection = YES;
Settings - > SupportDynamicChannels = YES;
Settings - > RemdeskVirtualChannel = YES;
Settings - > AudioPlayback = YES;
Settings - > AudioCapture = YES;
Settings - > RedirectClipboard = NO.
Settings - > RedirectPrinters = NO.
 means Have you used any cmake command for it or any coding changes?
If you have some clues then please help.

**Comment by akallabeth** [comment]
@lobojoy You have to dig into the code in ```client/iOS/**`` and change the initialisation accordingly. Have a look at the android client for reference (the main loop and initialisation in that client was updated recently)

**Comment by lobojoy** [comment]
Did you mean 	android_channels_init() function ,I have to change accordingly for ios client?
Thanks!

**Comment by akallabeth** [comment]
there are a couple of functions, mainly the pre, post and disconnect functions as well as the main loop. oh and don't forget the function calling parse arguments ;)

**Comment by lobojoy** [comment]
I have added additional settings to freerdp iOS client e.g audio redirection ,Device redirection but still I facing problem related sound redirection. The audio at the Server side is enabled but it does not redirects sound.

**Comment by akallabeth** [comment]
hard to tell without you providing some code / wip branch to have a look at.

**Comment by lobojoy** [comment]
currently I am looking at the files channels/rdpsnd/client/ios/rdpsnd_ios.c ,TPCircularBuffer.c  ,
but not sure working properly or not?

**Comment by lobojoy** [comment]
@akallabeth @cloudecker  stuck at audio/sound redirection for freeRDP iOS client. Do you guys have any updates about files that I have mentioned in earlier comment rdpsnd_ios.c and tpcircularbuffer.c?

**Comment by aysenkilic** [comment]
do you have any update or solution about this issue? i also wonder why ifreerdp android app has redirection settings, but iOS app does not.

**Comment by akallabeth** [comment]
@aysenkilic Because nobody stepped up to do a pull for that feature ;) @lobojoy never gave a branch to look at, so no help can be provided.

**Comment by bzyp** [comment]
Is there a solution to this problem now?i want redirect sound for ios

**Comment by bzyp** [comment]
> I have added additional settings to freerdp iOS client e.g audio redirection ,Device redirection but still I facing problem related sound redirection. The audio at the Server side is enabled but it does not redirects sound.

How did you make it, please?

**Comment by NEXTUSD** [comment]
Any updates on the audio redirection issue on iOS free rdp?

Is audio redirection available on iOS?
