### ISSUE TITLE
please correctly spell "occurred"

### ISSUE THREAD

**Issue by sunweaver** [FreeRDP/FreeRDP#3142]
The word "occurred" is spelled with double-"r". Please use its correct spelling in FreeRDP...

[mike@minobo FreeRDP (master)]$ grep -ri occured
winpr/libwinpr/comm/comm_serial_sys.c:		/* FIXME: "is 80 percent full" from the specs is ambiguous, need to track when it previously occured? */
winpr/include/winpr/nt.h:#define STATUS_MCA_OCCURED						((NTSTATUS)0xC000036A)
winpr/include/winpr/error.h:#define ERROR_MCA_OCCURED							0x0000028B
channels/drive/client/dirent.h:         /* the very last entry has been processed or an error occured */
channels/urbdrc/client/urbdrc_main.c:				WLog_ERR(TAG,  "No Device from receive_device(). An error occured.");
libfreerdp/core/tcp.c:		WLog_ERR(TAG, "an error occured when writing (num: %d)", num);
libfreerdp/core/errconnect.c:		"A undefined connection error occured."
client/common/cmdline.c:					WLog_ERR(TAG, "A problem occured while mapping the layout name to id");
client/Android/Studio/freeRDPCore/src/main/java/com/freerdp/freerdpcore/presentation/BookmarkActivity.java:		// if an error occured - display toast and return false

**Comment by hardening** [comment]
These ones became API typos, but not from us:
winpr/include/winpr/nt.h:#define STATUS_MCA_OCCURED ((NTSTATUS)0xC000036A)
winpr/include/winpr/error.h:#define ERROR_MCA_OCCURED 0x0000028B

see https://www.winehq.org/pipermail/wine-patches/2006-September/030453.html

**Comment by bmiklautz** [comment]
@hardening it's actually the same spelling as in the windows headers ;)

**Comment by hardening** [comment]
@bmiklautz yeah that was my point, we won't correct these ones as it's the way they are supposed to be spelt the microsoft way :)
