### ISSUE TITLE
about mac client

### ISSUE THREAD

**Issue by cloudecker** [FreeRDP/FreeRDP#3146]
hi all,
freerdp a framework is obtained by cake to compile a MAC version, but there was no Xcode source code. I use the iOS client source code?

**Comment by akallabeth** [comment]
@cloudecker Could you repeat the question in english please?

**Comment by cloudecker** [comment]
@akallabeth  I compiled freerdp MAC client, I got a framework, not a MAC client source code. My question, whether the MAC client also uses the iOS client source code?

**Comment by cloudecker** [comment]
@akallabeth Compile MAC version freerdp, I get the information as follows. Attached image
![11](https://cloud.githubusercontent.com/assets/16411660/13238198/36f0dd78-da0c-11e5-9bfd-e7f529576441.jpg)

**Comment by akallabeth** [comment]
@cloudecker The clients are separate (the stuff in ```client/*``` is just the GUI) but they share some code (audio support, etc). But please do not post duplicate questions like in #2950
As for compiliation there is a .app bundle created (```MacFreeRDP.app``` in ```client/Mac/cli```).
The frameworks are built before as the client consists of a couple of them ;)

**Comment by cloudecker** [comment]
@akallabeth  Thank you for your patience reply.
I mean, mac client only a framework and some GUI layout file. mac  client does not actually run the RDP connection.
In the ios client, there are a lot of RDP connection Settings file. But the MAC client without these files.

**Comment by akallabeth** [comment]
@cloudecker The MAC client is very rudimentary, it can only be started with command line, so there is no nice GUI for connection settings. The iOS client on the other hand has such an interface.

**Comment by cloudecker** [comment]
@akallabeth  thank  you very much，i will try it again!
