### ISSUE TITLE
New tag or release?

### ISSUE THREAD

**Issue by colemickens** [FreeRDP/FreeRDP#3154]
I'd like to use a newer version of FreeRDP in NixOS, but I don't feel comfortable pinning the package to a random git revision of FreeRDP. Is there any chance that FreeRDP would tag a new beta soon? It looks like the most recent relevant tag is from Sept 2014.

Apologies if I've missed a discussion about how releases/tags are handled, I did look around.

**Comment by bmiklautz** [comment]
@colemickens please have a look to #2678 or #2839. As described we are working on getting everything ready for 2.0 but as resources are rare there is no fixed schedule.
