### ISSUE TITLE
Troubles with compilation for Windows XP from Visual studio 2013 Update 4

### ISSUE THREAD

**Issue by zoccolo** [FreeRDP/FreeRDP#3158]
Good day!

I compile freerdp on windows 7 x64 with Visual Studio 2013 Update 4. If i execute wfreerdp.exe on Windows XP SP3 i got the following error:

> InitOnceExecuteOnce not found in "KERNEL32.dll"

**Some infos about the compiling:**

- Latest version from git
- CMake version: 2.8.12
- CMake command line: cmake . -DMONOLITHIC_BUILD=ON -DBUILD_SHARED_LIBS=OFF -G “Visual Studio 12″ -T v120_xp -DCMAKE_WINDOWS_VERSION=WINXP -DMSVC_RUNTIME=static -DWITH_SSE2=ON
- Compiler: Visual Studio 2013 Update 4
- Visual Studio Toolset: v120_xp (For compatibility with Xp / 2003)
- Configuration: Release / Debug (no matter)

But when i replace cmakelists.txt strings from "DWIN32_WINNT=0x0501" to "D_WIN32_WINNT=0x0501" (i think that it is correct flag to select Windows version) i have many (more than 2000) error like this:

> Error	35	error C2059: syntax error : '('	synch.h	300	1	cliprdr-client

All erors in synch.h file.

Please tell me, is it possible to compile freerdp to run on windows xp?

Best regards!

***  a problem similar to https://github.com/FreeRDP/FreeRDP/issues/2029
So i copy small part of description style from this post =)

**Comment by mfleisz** [comment]
WIN32_WINNT is definitely wrong - it should be _WIN32_WINNT - you are using quite an old version of cmake - maybe you can update to something more recent? (latest is currently 3.4.3)

**Comment by zoccolo** [comment]
Thanks for answer, mfleisz!

Now I installed the latest version of cmake. Nevertheless, I still have a lot of errors in synch.h file while compile (and of course i use  _WIN32_WINNT flag instead of WIN32_WINNT). In other words, nothing has changed).

Please tell me whether there is a way to correct build freerdp for Windows XP?

Thank you!

**Comment by mfleisz** [comment]
@zoccolo I don't have a XP machine here to check the resulting binary but this command line builds without problem:

```cmake -G "Visual Studio 12 2013" -T v120_xp -D_WIN32_WINNT=0x0501 .```

**Comment by zoccolo** [comment]
Yes, cmake works without any problems, but in this case _WIN32_WINNT flag is ignored by cmake:

> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     _WIN32_WINNT

And compilation process run without any problems. But when I try to run executable file from Windows XP, I have this error:

> The procedure entry point GetTickCount64 could not be located in the dynamic link library KERNEL32.dll

I think there's a reason for that in this case does not turn on winpr GetTickCount64 code?

Second situation.

If I try to set _WIN32_WINNT manually in cmakelists.txt file, i still have many errors in synch.h file.

**Comment by akallabeth** [comment]
@zoccolo yes, the winpr implementation is not activated and the function is only available from vista onward.

**Comment by akallabeth** [comment]
@zoccolo You can check ```winpr.dll``` if it exports ```GetTickCount64``` with ```depends.exe```

**Comment by zoccolo** [comment]
@akallabeth yes, and i don't understand how to fix it up.

Cause when i try to compile freerdp without _WIN32_WINNT i have not errors, but this executable can't run on Windows XP.

And when i try to compile it with _WIN32_WINNT, i have many errors.

=(

Is there an easy way to compile freerdp under windows XP?

**Comment by bmiklautz** [comment]
@zoccolo can you quickly verify if our nightly build https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win32,label=windows/lastSuccessfulBuild/artifact/build/wfreerdp.exe works for you?

**Comment by zoccolo** [comment]
@bmiklautz 

> wfreerdp.exe is not a valid win32 application

or you have offered to build your version?

**Comment by bmiklautz** [comment]
@zoccolo that is really weird using the daily builds quite regularly. Just tried the link from above works fine for me ;(.

**Comment by bmiklautz** [comment]
@zoccolo correction works fine for me everywhere except on xp ;).

**Comment by zoccolo** [comment]
... and it is the main problem =\

**Comment by mfleisz** [comment]
AFAIK the CI build is being built with Visual Studio 2013 and therefore won't run on XP: https://blogs.msdn.microsoft.com/vcblog/2012/06/15/targeting-windows-xp-with-c-in-visual-studio-2012/

I start to think that there is a problem with certain MS SDK/Compiler combos - when I try to build with _WIN32_WINNT=0x0501 I also get lots of errors due to InitializeCriticalSectionEx being redefined by WinPR. Looking at winbase.h in the Windows SDK (7.1A) you can see this:

```
#if (_WIN32_WINNT >= 0x0403)
...
WINBASEAPI
BOOL
WINAPI
InitializeCriticalSectionEx(
    __out LPCRITICAL_SECTION lpCriticalSection,
    __in  DWORD dwSpinCount,
    __in  DWORD Flags
    );
...
#endif
```

Which is clearly wrong since InitializeCriticalSectionEx is only supported since Vista ...

**Comment by bmiklautz** [comment]
@mfleisz Visual Studio 2013 yes but the problem here is that we use nmake/jom builder and ther you can't set the subsystem ;(. (I thought I updated it back then but seems I didn't).

**Comment by bmiklautz** [comment]
@mfleisz you are saying the SDK is broken in that case?

**Comment by mfleisz** [comment]
@bmiklautz Seems so ... the Win8 SDK headers have a correct definition (>= 0x0600).

**Comment by mfleisz** [comment]
@bmiklautz I guess this is a special case where this error becomes obvious - because we define the function if it is not present - normal apps would compile just fine (even though they would also compile if they incorrectly referenced InitializeCriticalSectionEx)

**Comment by zoccolo** [comment]
@mfleisz 
@bmiklautz 

So... Is there a way to compile code under XP, to get a running program? =)

Should I try to use different versions of Microsoft Visual Studio?

**Comment by akallabeth** [comment]
@zoccolo Use one of the suggested SDK versions or fix the visual studio header containing ```InitializeCriticalSectionEx```

**Comment by mfleisz** [comment]
@zoccolo You could try to compile FreeRDP with an older Visual Studio version (i.e. 2010).

**Comment by zoccolo** [comment]
**Thanks for answer!**
