### ISSUE TITLE
Sound / Microphone redirection choppy

### ISSUE THREAD

**Issue by meanbunny** [FreeRDP/FreeRDP#3166]
Hey All,

1.) I am running Arch Linux with Gnome
2.) Have the latest from master hash (4f22682ed22a1c1202103e30971f5dc23cb16f9d)
3.) Built FreeRDP with Pulse and Alsa
4.) Remoting into a Windows 10 VM running on QEMU
5.) Parameters to my session : +clipboard +aero +menu-anims +window-drag /gdi:sw +fonts /sound:sys:pulse /microphone:sys:pulse

The microphone and the sound both redirect and I can hear audio pretty well. However, when I do a Skype call the end user claims that its very choppy. I know how many loops the system is going through just to send my input to the end user but wasn't sure if there is a way to improve the performance of the call and the user hearing my input. 

Thanks!

**Comment by akallabeth** [comment]
@meanbunny Just had a look, the microphone plugin ignores the command line, could you try with a build only supporting alsa and one only supporting pulse to see which backend has these issues?

**Comment by akallabeth** [comment]
@meanbunny Fixed the argument parsing witn #3173 so now you can check which backend (or all?) have this issue.

**Comment by meanbunny** [comment]
Yeah sure let me do that, i'll post the feedback here in a little while

Thanks,
Steven Combs
Meanbunny LLC, Owner
423-799-0365

**Comment by meanbunny** [comment]
Awesome!

Thanks,
Steven Combs
Meanbunny LLC, Owner
423-799-0365

**Comment by akallabeth** [comment]
@meanbunny You're welcome. Does it work now?

**Comment by meanbunny** [comment]
Sorry for the late reply. So I just did a quick make with FreeRDP only including Alsa no Pulse in the build configuration. It is actually failing to redirect my mic for some reason. I can RDP into the Windows machine; however, as soon as I open up the tray applet for Sound and click on the Recording tab (microphone tab). It kills the session and says the following. About to build pulse only and see what happens. 
`
[17:04:31:670] [12611:12612] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[17:04:31:670] [12611:12612] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[17:04:31:670] [12611:12612] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[17:04:31:670] [12611:12612] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
[17:04:31:752] [12611:12612] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel audin
[17:04:32:510] [12611:12620] [INFO][com.freerdp.channels.audin.client] - open: /dev/dsp
[17:04:32:510] [12611:12620] [ERROR][com.freerdp.channels.audin.client] - sound dev open failed: 2 - No such file or directory

[17:04:32:510] [12611:12612] [ERROR][com.freerdp.core] - audin_oss_thread_func reported an error. Error was 1359
[17:04:32:510] [12611:12612] [INFO][com.freerdp.client.x11] - Network disconnect!
[17:04:32:510] [12611:12612] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
`

**Comment by meanbunny** [comment]
Just built it with Pulse only, it let me get back into the RDP session. Placed a call using Skype and it was very choppy. Sounds like I probably hear about 1 letter out of each word.

**Comment by akallabeth** [comment]
@meanbunny your test 1 was using the oss plugin, not alsa. so you have tested 2 out of 3 now ^^

**Comment by meanbunny** [comment]
Ah gotcha, I didn't even know that was another option. So I removed that from the build configuration and rebuilt. I was able to get into the machine with no problem this time. 

When I did the call using Skype Alsa was worse than Pulse. At first I could at least here a letter or so within the word but then the call just overrode with flutters of sound and I couldn't here anything on the other end.

**Comment by Hobby-Student** [comment]
@meanbunny have you tried
```
/sound:sys:pulse,format:1,quality:high
```
?

**Comment by giovannitarter** [comment]
I sperimented a similar problem. Audio playback is almost fine but audio recording is really choppy. With audacity, when I record for example 5 seconds, I get an audio track of 1 second (more or less). Then the playback is accelerated and chopped.

Thanks,
Giovanni

**Comment by meanbunny** [comment]
@Hobby-Student that actually fixed my problem. I used my Pulse compiled
FreeRDP and added that in as a parameter and it worked. I can now Skype
screen share and video call inside my VM. Thank you!!

Thanks,
Steven Combs
Meanbunny LLC, Owner
423-799-0365

**Comment by yermulnik** [comment]
I do apologize resurrecting this old thread, but how do I build FreeRDP with Pulse?
```
[21:52:56:136] [143718:0002317f] [ERROR][com.winpr.library] - [LoadLibraryA]: failed with /opt/FreeRDP/lib/freerdp3/librdpsnd-client-pulse.so: cannot open shared object file: No such file or directory
```
Thanks.

**Comment by yermulnik** [comment]
FWIW: https://github.com/FreeRDP/FreeRDP/issues/1054#issuecomment-14549868
