### ISSUE TITLE
Segfault after latest git update

### ISSUE THREAD

**Issue by mr-wong** [FreeRDP/FreeRDP#3170]
Hi.

Reverted with 'git reset --hard 7c5fcc9' and all seems fine again. My git reflog now:

> # git reflog
>7c5fcc9 HEAD@{0}: reset: moving to 7c5fcc9
>9d21117 HEAD@{1}: pull git://github.com/FreeRDP/FreeRDP.git: Fast-forward
>7c5fcc9 HEAD@{2}: pull git://github.com/FreeRDP/FreeRDP.git: Fast-forward
>4d85ade HEAD@{3}: pull git://github.com/FreeRDP/FreeRDP.git: Fast-forward
>...
>df81e84 HEAD@{12}: clone: from git://github.com/FreeRDP/FreeRDP.git

output (same with empty params):

>[22:49:58:892] [26546:26548] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
>[22:49:58:925] [26546:26548] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
>[22:49:58:941] [26546:26548] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
>./w.sh: line 3: 26546 Segmentation fault      (core dumped) xfreerdp /u:--- /p:--- /v:---:--- +clipboard -decorations /f /bpp:15 +compression /compression-level:2 +bitmap-cache +offscreen-cache +async-update +aero +fonts /gdi:hw

**Comment by akallabeth** [comment]
@mr-wong Could you compile with debug symbols and run the command with GDB to get some idea where the crash occurs? Just tested here, running as expected.

**Comment by mr-wong** [comment]
Here it is. Not sure how correctly I did all:

(gdb) run
Starting program: /usr/local/bin/xfreerdp /u:--- /p:--- /v:---:--- +clipboard -decorations /f /bpp:15 +compression /compression-level:2 +bitmap-cache +offscreen-cache +async-update +aero +fonts /gdi:hw
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff3c35700 (LWP 18962)]
[00:29:03:130] [18958:18962] [INFO][com.freerdp.client.common.cmdline] - loading channel cliprdr
[00:29:03:153] [18958:18962] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[00:29:03:165] [18958:18962] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3c35700 (LWP 18962)]
0x00007ffff4c68090 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0

**Comment by akallabeth** [comment]
@mr-wong Well, type in ```bt``` when the crash occurs, then you get a stack trace.

**Comment by akallabeth** [comment]
@mr-wong btw, your git log looks strange, better start wit a clean clone, maybe there is some code left.

**Comment by mr-wong** [comment]
I made clean clone too in separate folder, with same result. Left reverted version to use RDP somehow.

Okay, here is stack trace (clean clone):

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3c35700 (LWP 32542)]
0x00007ffff4c68090 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
(gdb) bt
#0  0x00007ffff4c68090 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
#1  0x00007ffff7589f4c in winpr_RC4_Init (ctx=0x0, 
    key=0x6088d7 "\346\322\312b\021\216\367o\333\244'|\327\031\225c\"pzT\344{\231\037\066Jg\202\020\347\325\270\346\322\312b\021\216\367o\333\244'|\327\031\225c\"pzT\344{\231\037\066Jg\202\020\347\325\270", keylen=16)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/winpr/libwinpr/crypto/cipher.c:49
#2  0x00007ffff5d0864d in rdp_client_establish_keys (rdp=0x608800)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/libfreerdp/core/connection.c:516
#3  0x00007ffff5d0921d in rdp_client_connect_mcs_channel_join_confirm (rdp=0x608800, s=0x6168f0)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/libfreerdp/core/connection.c:722
#4  0x00007ffff5d157a9 in rdp_recv_callback (transport=0x616590, s=0x6168f0, extra=0x608800)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/libfreerdp/core/rdp.c:1353
#5  0x00007ffff5d2029a in transport_check_fds (transport=0x616590)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/libfreerdp/core/transport.c:854
#6  0x00007ffff5d15e4d in rdp_check_fds (rdp=0x608800)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/libfreerdp/core/rdp.c:1444
#7  0x00007ffff5d07bc7 in rdp_client_connect (rdp=0x608800)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/libfreerdp/core/connection.c:301
#8  0x00007ffff5cea009 in freerdp_connect (instance=0x603010)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/libfreerdp/core/freerdp.c:99
#9  0x00007ffff7b4f780 in xf_client_thread (param=0x603010)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/client/X11/xf_client.c:1507
#10 0x00007ffff75c8f82 in thread_launcher (arg=0x645b10)
    at /home/wong/Desktop/storage/wplace/freerdp2/FreeRDP/winpr/libwinpr/thread/thread.c:315
---Type <return> to continue, or q <return> to quit---
#11 0x00007ffff5512182 in start_thread (arg=0x7ffff3c35700) at pthread_create.c:312
#12 0x00007ffff726d47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

**Comment by akallabeth** [comment]
@mr-wong Ok, got it. Could you try #3171?

**Comment by mr-wong** [comment]
@akallabeth Thanks, no crashes now!
Aren't that was caused because I maybe messed with encryption settings on host side? I've configured everything a long time ago and can't remember what exactly changed, but tried to revert as mentioned before (suspend hang). However, no serious issues for last about half year.
(close this issue if you consider necessary)

**Comment by akallabeth** [comment]
@mr-wong you triggered a bug introduced with #3156

**Comment by giox069** [comment]
It just happened to me after my last pull: when connecting to Windows 2003 servers. The backtrace output from the address sanitizer is similar to the one of gdb, but not identical:
```
giovanni@unox:~/remmina_devel$ xfreerdp /v:a-2003-server.mydomain.it /u:giovanni /d:mynbdomain
[15:00:42:957] [5078:5079] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[15:00:43:197] [5078:5079] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
ASAN:SIGSEGV
=================================================================
==5078==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x7fbd48ee5110 bp 0x7fbd40c04140 sp 0x7fbd40c04118 T1)
    #0 0x7fbd48ee510f  (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0xaa10f)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ??:0 ??
Thread T1 created by T0 here:
    #0 0x7fbd4cf626a3 in pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x366a3)
    #1 0x7fbd4c4cbcca in winpr_StartThread /home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/thread/thread.c:345
    #2 0x7fbd4c4cc6c2 in CreateThread /home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/thread/thread.c:455
    #3 0x7fbd4cc95c55 in xfreerdp_client_start /home/giovanni/remmina_devel/FreeRDP/client/X11/xf_client.c:1748
    #4 0x7fbd4c859a05 in freerdp_client_start /home/giovanni/remmina_devel/FreeRDP/client/common/client.c:109
    #5 0x40116d in main /home/giovanni/remmina_devel/FreeRDP/client/X11/cli/xfreerdp.c:71
    #6 0x7fbd4bfd7a3f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x20a3f)

==5078==ABORTING

```

**Comment by akallabeth** [comment]
@giox069 Does pull #3171 resolve the issue for you too?

**Comment by giox069** [comment]
Yes, PR #3171 does solve it.

**Comment by akallabeth** [comment]
fix merged.
