### ISSUE TITLE
openSUSE: build of wayland client fails with: wayland-client.h: No such file or directory

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#3174]
I try to build the current master as of 27. February with "-DWITH_WAYLAND=ON" but it fails:
`[   66s] [ 95%] Building C object client/X11/CMakeFiles/xfreerdp-client.dir/xf_gdi.c.o
[   66s] In file included from /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/Wayland/wlf_input.h:25:0,
[   66s]                  from /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/Wayland/wlf_input.c:26:
[   66s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/uwac/include/uwac/uwac.h:26:28: fatal error: wayland-client.h: No such file or directory
[   66s] compilation terminated.
[   66s] client/Wayland/CMakeFiles/wlfreerdp.dir/build.make:86: recipe for target 'client/Wayland/CMakeFiles/wlfreerdp.dir/wlf_input.c.o' failed
[   66s] make[2]: *** [client/Wayland/CMakeFiles/wlfreerdp.dir/wlf_input.c.o] Error 1
[   66s] make[2]: *** Waiting for unfinished jobs....
[   66s] In file included from /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/Wayland/wlfreerdp.h:26:0,
[   66s]                  from /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/Wayland/wlfreerdp.c:28:
[   66s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/uwac/include/uwac/uwac.h:26:28: fatal error: wayland-client.h: No such file or directory
[   66s] compilation terminated.
[   66s] client/Wayland/CMakeFiles/wlfreerdp.dir/build.make:62: recipe for target 'client/Wayland/CMakeFiles/wlfreerdp.dir/wlfreerdp.c.o' failed
[   66s] make[2]: *** [client/Wayland/CMakeFiles/wlfreerdp.dir/wlfreerdp.c.o] Error 1
` 

The header file exists in /usr/include/wayland and FindWayland.cmake sets the variable for the wayland include dir to /usr/include/wayland.

btw.: I had to add:
BuildRequires:  libxkbcommon-devel
to the spec file.

**Comment by hardening** [comment]
This looks good to me, can you make a PR of this ?

**Comment by hendwolt** [comment]
I created my very first PR : #3178.

**Comment by hendwolt** [comment]
Fixed with merge of #3178.
