### ISSUE TITLE
shared-lib-calls-exit: uwac/libuwac/uwac-utils.c

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#3188]
`Exit()` must not be called in a shared library. Instead allocation failures should be handled in the calling functions `uwac-input.c` and `uwac-display.c`

`void *xzalloc(size_t s)` is not used at all.

**Comment by hardening** [comment]
True, anyway these ones are quite tricky to handle correctly as they are called in a void callback called by wayland.
I will have a look to see how I can remove these.

**Comment by weberhofer** [comment]
I'm sure it's tricky. I had a look at the sources...

**Comment by weberhofer** [comment]
Is there any news on this issue? RPMLINT still complains about that.

**Comment by bmiklautz** [comment]
@weberhofer as @hardening already mentioned the functions pointers that are passed need to be void so it's either exit or just return nothing as no failure can be indicated. For now I think there is not much we can do here if we don't want to return when an error happened ;(.

Just as record the following file/functions are affected:
* uwac-display.c/cb_shm_format
* uwac-display.c/registry_handle_global

**Comment by weberhofer** [comment]
@bmiklautz thank you for your reponse. It's just a warning, so I will not ship a rpmlint file to be reminded in the future, too.

**Comment by akallabeth** [comment]
Since we can´t do much here, I´ll close this.
