### ISSUE TITLE
Compile fails on FreeBSD due to "undeclared identifier 'UTIME_OMIT'"

### ISSUE THREAD

**Issue by antenore** [FreeRDP/FreeRDP#3189]
Compiling FreeRDP on FreeBSD, with the latest commits, fails with the following errors:

```
/home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/file.c:387:21: 
error: use of undeclared identifier 'UTIME_OMIT'
                 times[0].tv_sec = UTIME_OMIT;
                                   ^
/home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/file.c:388:22: 
error: use of undeclared identifier 'UTIME_OMIT'
                 times[0].tv_nsec = UTIME_OMIT;
                                    ^
/home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/file.c:421:21: 
error: use of undeclared identifier 'UTIME_OMIT'
                 times[1].tv_sec = UTIME_OMIT;
                                   ^
/home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/file.c:422:22: 
error: use of undeclared identifier 'UTIME_OMIT'
                 times[1].tv_nsec = UTIME_OMIT;
                                    ^
/home/giovanni/remmina_devel/FreeRDP/winpr/libwinpr/file/file.c:449:7: 
warning: implicit declaration of function 'futimens' is invalid in C99 
[-Wimplicit-function-declaration]
         rc = futimens(fileno(pFile->fp), times);
              ^
1 warning and 4 errors generated.
```

Is it possible to avoid the UTIME_OMIT identifier (at least on FreeBSD) ?
What about the C99 warning? Can we safely ignore it?

@akallabeth I'm not sure I can find a quick fix as quickly as you would..  Thanks in advance!!!

**Comment by antenore** [comment]
@giox069 FYI

**Comment by akallabeth** [comment]
@antenore Don't have a bsd to test here right now, could you check if the attached patch works for you?
[0001-BSD-test-fix.patch.zip](https://github.com/FreeRDP/FreeRDP/files/156552/0001-BSD-test-fix.patch.zip)

**Comment by antenore** [comment]
Thanks! :+1: 
I'll do it this evening (CET).

**Comment by antenore** [comment]
I've modified it a little bit and I still have a warning because I don't know well how to fix it

[0001-BSD-test-fix_antenore.patch.gz](https://github.com/FreeRDP/FreeRDP/files/157859/0001-BSD-test-fix_antenore.patch.gz)

```sh
/usr/home/tmow/remmina_devel/FreeRDP.patched/winpr/libwinpr/file/file.c:445:34: warning: incompatible pointer types passing 'struct timespec [2]' to parameter of type 'const struct timeval *'
      [-Wincompatible-pointer-types]
        rc = futimes(fileno(pFile->fp), times);
                                        ^~~~~
/usr/include/sys/time.h:483:40: note: passing argument to parameter here
int     futimes(int, const struct timeval *);
                                           ^
```
http://www.unix.com/man-page/freebsd/2/futimes/

futimes expect timeval

More over my patch I think it brakes the rest of your code :-(

At least FreeBSD is compiled at the end.

**Comment by akallabeth** [comment]
@antenore ah, then I know which ones I can use ^^ Just checked the online manuals, looks like FreeBSD is the only one lacking POSIX ```futimens``` support *except for apple and android of course)
Got a fix here: https://github.com/akallabeth/FreeRDP/tree/file_bsd_fix

**Comment by antenore** [comment]
Thanks! I don't know when I'll be able to test it, I hope very soon

**Comment by antenore** [comment]
I'm testing and trying to fix as well.

https://github.com/antenore/FreeRDP/commit/cb990e8c1ead0b0f6970d66f00b9cd2b6ad7a5ea

So far I'm trying to fix this:

```
winpr/libwinpr/file/file.c:386:29: error: no member named 'st_mtimensec' in 'struct stat'
                timevals[0].tv_usec = buf.st_mtimensec / 1000UL;
                                      ~~~ ^
```

**Comment by antenore** [comment]
Thanks a lot guys :-) :+1:
