### ISSUE TITLE
Error when opening RDP session with sound enabled 

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#3195]
With a newly built version I get the following error opening an RDP session to windows (using remmina) having sound enabled.

[ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_rdpsnd_client_subsystem_entry: /usr/lib64/freerdp2/librdpsnd-client-alsa.so: undefined symbol: freerdp_rdpsnd_client_subsystem_entry

It might be related to the change in #3192.

**Comment by bmiklautz** [comment]
@weberhofer I doubt that. As it seems to find the path :). I would guess that this is related to a recent chance with static channels. (I assume you've built with -DSTATIC_CHANNELS=OFF?

**Comment by weberhofer** [comment]
You are right, I have built with 've built with -DSTATIC_CHANNELS=OFF.

**Comment by bmiklautz** [comment]
Will be fixed with #3196
