### ISSUE TITLE
Implement auth-only in Python

### ISSUE THREAD

**Issue by pplanel** [FreeRDP/FreeRDP#3201]
This is a very nice repository! Good job all!
My question is, if I want to implement the auth-only functionality in Python, where should I look at?
Thanks!

**Comment by bmiklautz** [comment]
If you want to implement it in plain python you might have to re-implement the whole RDP spec in python. However you could also use libfreerdp via ctypes in python. Have a look client/X11 to see how "authonly" is implemented in xfreerdp and just make the required calls from python.
For the future please ask questions like this on in the irc channel or use our mailing list.
