### ISSUE TITLE
iFreeRDP - Extended Keyboard is not working

### ISSUE THREAD

**Issue by DieselV** [FreeRDP/FreeRDP#3205]
MAC OSX 10.11
Xcode 7.2
Extended keyboard is not working for windows server

**Comment by bmiklautz** [comment]
@DieselV could you, please add more information on this?
* FreeeRDP version
* what exactly is the problem
* how to reproduce?
* ...

Thank you.

**Comment by DieselV** [comment]
FreeRDP version I don't know but I am running latest github code..
Problem is I am looking for Advanced Keyboard (Functions keys,Arrows,shift) but Its not working
just run iFreeRDP app
I am not sure that that functionality implemented in this latest version

**Comment by bmiklautz** [comment]
@DieselV ok you are talking about iFreeRDP - that wasn't obvious from your initial issue report!

**Comment by DieselV** [comment]
And I am running iFreeRDP using iphone 5s

**Comment by DieselV** [comment]
Is their any way to show Keyboard and Extended at a same time on screen
?
