### ISSUE TITLE
windows --authonly

### ISSUE THREAD

**Issue by melanholy** [FreeRDP/FreeRDP#3211]
FreeRDP returns errorlevel 0 no matter what in windows 7. How can I detect if I have successfully connected to the remote desktop when --authonly option is present?

I tried both "wfreerdp [options] && echo %errorlevel%" and "start /wait wfreerdp [options] && echo %errorlevel%"

**Comment by akallabeth** [comment]
@melanholy wfreerdp is a windows gui application which detaches from the terminal. you have to modify it to a console app if you want to do that.

**Comment by melanholy** [comment]
Did this. Still the same
![image](https://cloud.githubusercontent.com/assets/10682553/13644748/2fdad32e-e649-11e5-9afe-89214d7b129e.png)

**Comment by akallabeth** [comment]
@melanholy you're right, the windows client always returns 0 (see wf_client.c:852) and overall lacks return value checks :/
Currently no windows machine near me, so I can't fix it but I hope this info helps.
