### ISSUE TITLE
smart-sizing doesn't work

### ISSUE THREAD

**Issue by sabbia001** [FreeRDP/FreeRDP#3216]
Hi,

I need to connect to a Windows 10 pc (from Ubuntu 15.10) and I need to increase screen size (the destination pc has a 4k resolution). I've used smart-sizing but it doesn't work:

xfreerdp /v:IP /size:1920x1080 /u:USER /p:PASSWORD /smart-sizing:640x480 +compression /sound /bpp:15 -themes

Did I anything wrong?

**Comment by bmiklautz** [comment]
@sabbia001 do you have installed the xrender development files? - smart sizing requires xrender.

**Comment by bmiklautz** [comment]
@sabbia001 also may I ask to provide more information?! "but it doesn't work" isn't something we can  help with. Please have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by akallabeth** [comment]
@sabbia001 And you want to switch the resolutions for ```/size``` and ```/smart-sizing```. The first is the desktop resolution of your remote machine, the latter is the local window size.

**Comment by sabbia001** [comment]
@bmiklautz  Hi everyone, I'll try to be clearer, sorry.

Using Ubuntu 15.10 and connecting to Windows 10.
On both systems I have a 3840x2160 resolution (on Ubuntu I use a scale factor x1,88 in order to have fonts/icons bigger). On Windows I don't use a scale factor.

:~$ xfreerdp --version
This is FreeRDP version 1.1.0-beta1 (git n/a)

I use this command (but I tried every combination of /size, /smart-sizing, +smart-sizing, inverting resolutions etc...):

xfreerdp /v:IP /size:2560x1440 /u:USER /p:PASSWORD /smart-sizing:640x480 +compression /sound /bpp:15 -themes
 
I've noticed that /size corresponds to the local window dimension. /smart-sizing doesn't produce anything. What I would like to get is a big window (2560x1440 it's ok) on local pc (Ubuntu 15.10), showing a "zoomed" resolution compared to the too small 3840x2160 remote resolution. So I thought that smart-sizing could force a remote change resolution.

Remmina has a specific feature to do that: "Resize window to adapt to the remote resolution" (but I have sound problems with Remmina)

@akallabeth , in my case /size is no doubt the local windows size.

**Comment by hardening** [comment]
1.1.0 is a quite old version, can you give a try with a nightly build (https://github.com/FreeRDP/FreeRDP/wiki/Prebuilds) ?

**Comment by sabbia001** [comment]
@hardening got it! Thank you
./xfreerdp --version
This is FreeRDP version 2.0.0-dev (git n/a)

/size and /smart-sizing are inverted compared to the previous version and now, as @akallabeth said, the first is the remote desktop resolution, the other is the local window size.

Thank you very much

**Comment by nfedera** [comment]
@sabbia001 See https://github.com/FreeRDP/FreeRDP/wiki/Quality-Assurance-(QA)#smart-sizing

**Comment by mailinglists35** [comment]
commenting just so I can find this easily later, I want to do the opposite of OP, the remote has lower resolution that I want upscaled on local larger display:

`/size:1920x1080 /smart-sizing`

requires v2 (ubuntu: https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/freerdp-daily)
