### ISSUE TITLE
suggest check WAYLAND_FOUND when compile wayland client

### ISSUE THREAD

**Issue by comicfans** [FreeRDP/FreeRDP#3219]
wlfreerdp needs libuwac to build, but libuwac only build when WAYLAND_FOUND is true.
this makes WITH_WAYLAND=true && WAYLAND=false not built due to uwac can not be linked
so I suggest  replace client/CMakeLists.txt

 if(WITH_WAYLAND)

to

 if(WITH_WAYLAND AND WAYLAND_FOUND)

**Comment by bmiklautz** [comment]
@comicfans makes sense. Thanks for the feedback.
@hardening any objections?

**Comment by hardening** [comment]
makes sense

**Comment by hardening** [comment]
@comicfans would you make a PR of this ? Thank you.

**Comment by hardening** [comment]
Fixed in https://github.com/FreeRDP/FreeRDP/pull/3223
