### ISSUE TITLE
Fedora 23 lxde. Сompile error 

### ISSUE THREAD

**Issue by impuls-proton** [FreeRDP/FreeRDP#3220]
System: **Fedora 23 LXDE**
Kernel and CPU: Linux 4.4.3-300.fc23.i686+PAE on i686

I use instruction https://github.com/FreeRDP/Remmina/wiki/Compile-on-Fedora-20

Configure FreeRDP for compilation and compile:
```
# cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_PULSE=ON -DWITH_CUPS=on -DWITH_WAYLAND=off -DCMAKE_INSTALL_PREFIX:PATH=/opt/remmina_devel/freerdp .
...

# make
[  0%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/synch/address.c.o
...
Scanning dependencies of target generate_argument_docbook
[ 96%] Building C object client/X11/CMakeFiles/generate_argument_docbook.dir/generate_argument_docbook.c.o
[ 96%] Linking C executable generate_argument_docbook
/lib/libavcodec.so.56: undefined reference to `deflateBound@ZLIB_1.2.0'
/lib/libcups.so.2: undefined reference to `inflateCopy@ZLIB_1.2.0'
/lib/libdw.so.1: undefined reference to `gzdirect@ZLIB_1.2.2.3'
collect2: error: ld execution failed with return code 1
сlient/X11/CMakeFiles/generate_argument_docbook.dir/build.make:102: recipe for target «client/X11/generate_argument_docbook» failed
make[2]: *** [client/X11/generate_argument_docbook] Error 1
CMakeFiles/Makefile2:3722: recipe for target  «client/X11/CMakeFiles/generate_argument_docbook.dir/all» failed
make[1]: *** [client/X11/CMakeFiles/generate_argument_docbook.dir/all] Error 2
Makefile:149: recipe for target «all» failed 
make: *** [all] Error 2
 
```
Help me, please!
What is the problem?

**Comment by bmiklautz** [comment]
@impuls-proton do you have the zlib development files installed (zlib-devel)?

**Comment by bmiklautz** [comment]
@impuls-proton it should basically compile fine on Fedora 23 as we create nightly packages on it (https://ci.freerdp.com/job/freerdp-nightly-rpm-mock/)

You can also have a look to packaging/rpm/freerdp-nightly.spec to check what dependencies are required.

**Comment by impuls-proton** [comment]
@ #3221 
Yes, installed zlib-1.2.8-9.fc23.i686 and zlib-devel-1.2.8-9.fc23.i686

**Comment by impuls-proton** [comment]
I used the rpm packages. (https://ci.freerdp.com/job/freerdp-nightly-rpm-mock/)
Very well! I have a connection to the Terminal Server! 

But why these errors: _Error: SSL_NOT_ALLOWED_BY_SERVER_
and _Unable to get current timezone rule_

```
# ./xfreerdp /v:10.2.13.11 /u:u_sidin /p:***********
[13:11:06:988] [23123:23124] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[13:11:06:989] [23123:23124] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[13:11:06:993] [23123:23124] [ERROR][com.winpr.timezone] - Unable to get current timezone rule
```

**Comment by bmiklautz** [comment]
@impuls-proton you can ignore the "Unable to get current timezone rule".  The first error messages is quite what it says "ssl is not allowed by your server". What's your command line parameters?

**Comment by impuls-proton** [comment]
ОК. _ssl_ is not problem for me at now.

I can connect to a remote desktop to the Terminal Server 2003.
Next step. I need connect to remote application program, for example "C:\Program Files (x86)\Microsoft Office\OFFICE11\WINWORD.EXE" 
We have option
`/app:||<alias> or <executable path> Remote application program`
Bat I don't understand how to use this option.  I can't find the exact reference information about this option. https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface

**Comment by bmiklautz** [comment]
@impuls-proton for me it seems your initial problem got solved. Please keep the tracker for issues only and use the mailing list or visit our irc channel help.
