### ISSUE TITLE
Ubuntu 15.10 audio problems workaround

### ISSUE THREAD

**Issue by sabbia001** [FreeRDP/FreeRDP#3222]
Hi,

I don'k know it this could be useful. I use xfreerdp (version 1.1.0-beta1) on Ubuntu 15.10 , and I got these messages:

LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/rdpsnd-client-pulse.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/rdpsnd-client-alsa.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/rdpsnd-client-macaudio.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
LoadLibraryA: /usr/lib/x86_64-linux-gnu/freerdp/rdpsnd-client-winmm.so: impossibile aprire il file oggetto condiviso: File o directory non esistente
Warning rdpsnd_process_connect (690): no sound device.

So I did this:
sudo cp librdpsnd-client-alsa.so rdpsnd-client-alsa.so
sudo cp librdpsnd-client-pulse.so rdpsnd-client-pulse.so

And now I can hear audio via xfreerdp.

Thank you very much for your great software!

**Comment by bmiklautz** [comment]
@sabbia001 did you build yourself? Or you using the Ubuntu provided version? - In the later case that's something you should report because it needs fixing in the Ubuntu package.

**Comment by bmiklautz** [comment]
@sabbia001 I just checked this works perfectly fine with the package that comes with Debian Jessie and the file naming looks good for me on Ubuntu 15.10 as well.

**Comment by sabbia001** [comment]
@bmiklautz  sorry, I'n not an expert: I'm quite sure that it was a problem of the Ubuntu package, but after that I made a lot of craps installing/reinstalling freerdp and remmina packages, stable and unstable, so now I can't replicate that situation. I just know that Remmina gave me the same error.
Sorry I can't tell you more.
