### ISSUE TITLE
Trouble multimon

### ISSUE THREAD

**Issue by marawu** [FreeRDP/FreeRDP#3228]
good afternoon. I use free rdp to connect to the video server. I also use multimon function to connect two monitors. After connecting to the server and opening cameras (about 40 pieces) I have ceased to operate a keyboard and mouse. Sometimes it works, but it often does not work. How can I solve this problem?

**Comment by hardening** [comment]
Please refer to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting for bug reporting. Thank you.
