### ISSUE TITLE
freerdp Windows Server 2008 R2 - Barcode Scanner USB - missing double characters 

### ISSUE THREAD

**Issue by ropetry** [FreeRDP/FreeRDP#3229]
Hello, we are using freerdp 2.0.0-dev with our 2008 R2 Terminal Servers. Attached to the Linux Device is a USB Barcode scanner from OPTICON.
If we scan Barcodes with Double Numbers via freerdp , like
02612295 or 02422288 we are loosing in 9 from 10 scans the double 22 or 88.. It just prints only one 2 or one 8.
Label:
02422288
barcode scan:
024228

.. If i do this on the Linux client in a xterm it works without a problem.. also rdesktop works without any problems. it seeams to be a timing issue ? i already has configured the usb barcode reader to use a bigger delay between the intercharacters, but it doesn´t help.

Output of dmesg:
[12396.196149] usb 1-1: USB disconnect, device number 2
[12402.708041] usb 1-1: new full-speed USB device number 3 using uhci_hcd
[12403.089079] usb 1-1: New USB device found, idVendor=065a, idProduct=0001
[12403.089088] usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[12403.089094] usb 1-1: Product: USB Code Reader
[12403.089099] usb 1-1: Manufacturer: Optoelectronics Co., Ltd.
[12403.097724] input: Optoelectronics Co., Ltd. USB Code Reader as /devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1:1.0/0003:065A:0001.0009/input/input13
[12403.098422] hid-generic 0003:065A:0001.0009: input,hidraw0: USB HID v1.00 Keyboard [Optoelectronics Co., Ltd. USB Code Reader] on usb-0000:00:1d.0-1/input0
~ #
output of the second reader:

Kernel is 3.16.7-29

if i change the opticon device and use an other usb barcode device the behavior is the same..
[12672.608058] usb 1-1: new low-speed USB device number 4 using uhci_hcd
[12672.969091] usb 1-1: New USB device found, idVendor=040b, idProduct=6543
[12672.969099] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[12672.984681] hid-generic 0003:040B:6543.000A: hiddev0,hidraw0: USB HID v1.10 Device [HID 040b:6543] on usb-0000:00:1d.0-1/input0
[12673.013627] input: HID 040b:6543 as /devices/pci0000:00/0000:00:1d.0/usb1/1-1/1-1:1.1/0003:040B:6543.000B/input/input14
[12673.014283] hid-generic 0003:040B:6543.000B: input,hidraw6: USB HID v1.10 Keyboard [HID 040b:6543] on usb-0000:00:1d.0-1/input1

Anyone here who can give me an advice what i can try to solve this ? some more debugs needed ? if so please ask..
thanks a lot..

**Comment by ropetry** [comment]
We use the following command line to start the session
/opt/freerdp/bin/xfreerdp -grab-keyboard /t:RemoteSessionname /workarea +compression /cert-ignore -nego /sec:rdp +clipboard /sound:sys:pulse /drive:USB /media /v:servername

**Comment by bmiklautz** [comment]
@ropetry just to clarify the reader is a regular HID device and you losing input on each scan when connected with xfreerdp?

**Comment by ropetry** [comment]
@bmiklautz  yes it´s a normal hid device as seen by the dmesg output i think.. and yes on all scans.. 9 of 10 are wrong.. anything i can do ??

**Comment by bmiklautz** [comment]
@ropetry I quickly tried to reproduce your behavior with the only barcode scanner I had at hand here but without success. Can you try to stick a debug message in libfreerdp/core/input.c functions input_send_keyboard_event and input_send_unicode_keyboard_event to see what is actually send out?
You might also want to check check the repeat rate on the windows side.

**Comment by HenryJacques** [comment]
@ropetry Is your command line complete? 
What is the `/media` argument you're using?
Is your purpose to use your USB scanner in your 2008 R2 environment (using USB redirection)? If yes, I don't see the `/usb:id` parameter...

**Comment by ropetry** [comment]
@bmiklautz : thats sad as i just have tested it again and i can replicate it with two different readers on our 2008 r2 ts farm.. i have now checked it also with a windows 7 rdp server and a normal 2008r2 server.. (without rdp termianl server) just remote administration.. and i have no errors.. the barcode scanners work.. i have to test this again on monday... i checked the repeating rate so far, but i don´t see a cause there..
i will move one terminal server away from all group policy settings and check it again..
on the other side i would like to do the debug you said, what should i insert into the code ?

thanks roman
and sorry for answering so late, i was off the work for 2 days..

**Comment by ropetry** [comment]
@HenryJacques : hi.. i have only usb media redirection enabled.. the barcode scanner -hid device should be only connected as a normal keyboard. it emulates a keyboard..
i can try to use the way you suggested if you can give me some more advice on it..
thanks
roman

**Comment by HenryJacques** [comment]
@ropetry Ok, I didn't know it emulates a keyboard. I should have suspected it thanks to your output of dmesg...
That said, if you compiled xfreerdp with URBDRC support, you could try to redirect it to Windows using the `/usb:id,dev:065a:0001`
However, I don't know if it makes sense since it is a HID device.

**Comment by bmiklautz** [comment]
@ropetry  any update on this? - Could you add what scanner you are actually using?

**Comment by fadeer** [comment]
We had same issue in freerdp 1.1.0, no test in freerdp 2.0.0-dev.

"missing double characters" happens because some USB scanner send two key_press and one key_release to rdp windows. *2_press*, *2_press*, *2_release*, so in windows, it show just one 2, some times.

Our workaround is, send *key_release* before 2nd key press. in `client/X11/xf_event.c`:

``` c
static BOOL xf_event_KeyPress(xfContext* xfc, XEvent* event, BOOL app)
{
	KeySym keysym;
	char str[256];

	XLookupString((XKeyEvent*) event, str, sizeof(str), &keysym, NULL);

+++	// release key before send
+++	if(NoSymbol != xfc->pressed_keys[event->xkey.keycode]){
+++		xf_kbd_unset_keypress(xfc, event->xkey.keycode);
+++		xf_kbd_send_key(xfc, FALSE, event->xkey.keycode);
+++	}

	xf_kbd_set_keypress(xfc, event->xkey.keycode, keysym);
```

**Comment by ropetry** [comment]
@bmiklautz : sorry, but i was in holidays: i tried again with our terminal servers and with a clean installed terminal server. just server 2008 and role terminal server added.. of 20 scan´s i get only 1 wrong. i´m just checking if we have changed something else at our server side.. but i don´t think so. in the meantime i will try to test the patch of @fadeer .. 
anyway. could you please point me to a little bit more into the right debug messages or functions i could change to get more infos as you have written in one of your first post. thanks

**Comment by bmiklautz** [comment]
@ropetry Can you try to stick a debug message in libfreerdp/core/input.c functions input_send_keyboard_event and input_send_unicode_keyboard_event to see what is actually send client side.

**Comment by ropetry** [comment]
@bmiklautz : hello bmiklautz, tried this now but my messages doesn´t appear. i compiled it and freerdp works.. 
after that i did a make clean , changed some code and made again a new compiler run, but my changes are not in the generated code.. is make clean not the right thing ?
 i think he still uses some cached code/objects..
thanks roman

**Comment by ropetry** [comment]
@fadeer : i tried to change your patch to match the new "objects/methodes" style. but had no luck so far.. still trying.to figure it out

**Comment by bmiklautz** [comment]
@ropetry what was your exact change?

**Comment by ropetry** [comment]
solved so far with some of the latest commits..
Using Commit GIT Version 1dbd2d2 ..
