### ISSUE TITLE
Trouble FreeRDP + Devline

### ISSUE THREAD

**Issue by marawu** [FreeRDP/FreeRDP#3232]
good afternoon. I have a problem when opened in rdp Surveillance System (Windows Server 2008R2 + DevLine (http://www.devline.ru/software/)). the problem is that I do not work a keyboard and mouse. and the problem does not occur systematically, but in 80% of cases.

Reconnecting I as follows: xfreerdp / v: server / u: user / p: password / multimon / monitors: 0,1 / cert-ignore (Linux Mint 17.3 Rosa + FreeRDP version 2.0.0-dev (git da9d9ed))

After connecting everything works fine, but as soon as I open the video surveillance system, which shows the image from about 40 cameras at me to stop responding keyboard and mouse, as in the rdp-session, and on the local machine. sometimes it happens that correspond to the keyboard and mouse are delayed for 3-4 minutes.

using 1 monitor this problem has not been seen.

**Comment by hardening** [comment]
Is it the "native" RDP server (as in the one shipped by ms) or something specific to DevLine ?

**Comment by marawu** [comment]
This is a standard server Microsoft running on it software. The problem arises as the time you run the software Devline in multimon mode


Rgds, Nikita Spickiy
Skype - n.spickiy@outlook.com

Novosibirsk, UTC +6


________________________________
От: Hardening <notifications@github.com>
Отправлено: 16 марта 2016 г. 13:08
Кому: FreeRDP/FreeRDP
Копия: marawu
Тема: Re: [FreeRDP] Trouble FreeRDP + Devline (#3232)


Is it the "native" RDP server (as in the one shipped by ms) or something specific to DevLine ?

-

**Comment by akallabeth** [comment]
Sounds like a configuration issue (maybe the thinclient is too busy)?
Anyway, closing for being ancient.
