### ISSUE TITLE
Warning: rdp.c: In function 'rdp_recv_tpkt_pdu':

### ISSUE THREAD

**Issue by CHERTS** [FreeRDP/FreeRDP#3235]
When build (branch master) Warning message:

```
/ts/ports/opt/freerdp/work/src/FreeRDP/libfreerdp/core/rdp.c: In function 'rdp_recv_tpkt_pdu':
/ts/ports/opt/freerdp/work/src/FreeRDP/libfreerdp/core/rdp.c:1216:38: warning: 'securityFlags' may be used uninitialized in this function [-Wmaybe-uninitialized]
   return rdp_recv_message_channel_pdu(rdp, s, securityFlags);
                                      ^

```

Fix it please.

**Comment by bmiklautz** [comment]
@CHERTS thanks for reporting the issue however the warnings depend on the compiler therefore your report doesn't make any sense without compiler information.

**Comment by bmiklautz** [comment]
@CHERTS please add some additional infomation:
* system compiled on
* compiler and compiler version used
* cmake configuration

**Comment by CHERTS** [comment]
I compile freerdp from thinstation (master branch)
gcc (Thinstation) 4.8.4
cmake version 3.2.2

**Comment by akallabeth** [comment]
Is this still an issue?

**Comment by akallabeth** [comment]
Closing due to lack of feedback
