### ISSUE TITLE
[async-transport] Current implementation broken

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#3238]
Async transport just fires up a thread doing the client main thread handling there (check and process freerdp events)
There are these issues with this approach:
- There is no (clean) way to provide additional event handles and process callbacks to freerdp (think async-input)
- The client main thread can not be notified of changes (2 threads waiting on the same events and processing 
- The exported get_event_handles functions function should only return the handles not already handled by async transport

**Comment by hardening** [comment]
+1 I think async transport is a bad idea, and not sure it really offers some real performance gains. Anyway if we choose to keep async transport that means all RDP reads _and_ writes should be done there.
