### ISSUE TITLE
iOS project complied error

### ISSUE THREAD

**Issue by mangorui** [FreeRDP/FreeRDP#3241]
I download the  newest  code,  followed README.ios step by step. but it errors when i execute "cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode" 

CMake version:3.5.0

-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT-dirty
-- Git Revision 80cd647
-- Skipping recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature OSS for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Skipping optional feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Enable feature FFmpeg using "-DWITH_FFMPEG=ON"
-- Skipping disabled feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
-- Skipping disabled feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT-dirty
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT-dirty
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Adding iOS client
-- Configuring done
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "disp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "echo-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpei-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpgfx-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "cliprdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drdynvc-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "encomsp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rail-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "remdesk-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drive-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "parallel-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "serial-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "smartcard-client" that is not in the export set.
-- Generating done
-- Build files have been written to: /Users/zoey/work/RDP/FreeRDP

**Comment by bmiklautz** [comment]
@mangorui do you have a git commit for your newest code?

**Comment by mangorui** [comment]
I have not changed the code。
I download it again , and complied, the error accours:

 git clone https://github.com/FreeRDP/FreeRDP.git

cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode
-- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Git Revision 75ae3f5
-- Looking for pthread_mutex_timedlock in pthread
-- Looking for pthread_mutex_timedlock in pthread - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - not found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - not found
-- Looking for include file poll.h
-- Looking for include file poll.h - not found
-- Looking for ceill
-- Looking for ceill - not found
-- Finding recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
--     Disable feature libsystemd using "-DWITH_LIBSYSTEMD=OFF"
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Could NOT find libsystemd (missing:  LIBSYSTEMD_LIBRARY LIBSYSTEMD_INCLUDE_DIR) 
CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature libsystemd was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:626 (find_feature)


-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.2.sdk/usr/lib/libz.tbd (found version "1.2.5") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /Users/zoey/work/RDP/FreeRDP/external/openssl/lib/libssl.a;/Users/zoey/work/RDP/FreeRDP/external/openssl/lib/libcrypto.a (found version "1.0.2g") 
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature OSS for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Skipping optional feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Enable feature FFmpeg using "-DWITH_FFMPEG=ON"
-- Skipping disabled feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
-- Skipping disabled feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Adding iOS client
-- Configuring done
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "audin-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "disp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "echo-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpei-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpgfx-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "tsmf-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "cliprdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drdynvc-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "encomsp-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rail-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpdr-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "rdpsnd-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "remdesk-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "drive-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "parallel-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "serial-client" that is not in the export set.
CMake Error: install(EXPORT "FreeRDP-ClientTargets" ...) includes target "freerdp-client" which requires target "smartcard-client" that is not in the export set.
-- Generating done
-- Build files have been written to: /Users/zoey/work/RDP/FreeRDP

**Comment by bmiklautz** [comment]
@mangorui as the build files have been written building should work fine.

**Comment by mangorui** [comment]
I have resovled this issue: I changed CMake version from 3.5.0 to 3.4.3, then it works fine

**Comment by bmiklautz** [comment]
@mangorui thank for the feedback. Possible that 3.5.0 has new features we aren't compatible with atm.
