### ISSUE TITLE
master cmake error,when complie with gstreamer 0.10

### ISSUE THREAD

**Issue by lifeblong** [FreeRDP/FreeRDP#3244]
platform: ARMv7  RK3288
system:ubuntu 15.10

I got a warning when cmake master version with -DWITH_GSTREAMER_0_10 flag

!!!!GStreamer:WARNING:interface library not found!!!!

but i have install gstreamer and it's plugins on ubuntu....

who can help me...

**Comment by bmiklautz** [comment]
@lifeblong if available use gstreamer 1.0 instead (packages libgstreamer-plugins-base1.0-dev,libgstreamer1.0-dev)

**Comment by lifeblong** [comment]
Think you very much! I miss libgstreamer-plugins-base0.10-dev.
