### ISSUE TITLE
Crash while connecting to Win-8 server with gfx enabled on Android client

### ISSUE THREAD

**Issue by mvojjala** [FreeRDP/FreeRDP#3245]
These is the crash log.

03-17 16:48:19.576 30026 13700 E com.freerdp.gdi: [pid=30026:tid=93f34930] - Failed to process RemoteFX message
03-17 16:48:19.577 30026 13700 E com.freerdp.channels.rdpgfx.client: [pid=30026:tid=93f34930] - context->SurfaceCommand failed with error 1359
03-17 16:48:19.577 30026 13700 E com.freerdp.channels.rdpgfx.client: [pid=30026:tid=93f34930] - rdpgfx_decode failed with error 1359!
03-17 16:48:19.577 30026 13700 E com.freerdp.channels.rdpgfx.client: [pid=30026:tid=93f34930] - rdpgfx_recv_wire_to_surface_1_pdu failed with error 1359!
03-17 16:48:19.577 30026 13700 E com.freerdp.channels.rdpgfx.client: [pid=30026:tid=93f34930] - Error while parsing GFX cmdId: RDPGFX_CMDID_WIRETOSURFACE_1 (0x0001)
03-17 16:48:19.577 30026 13700 E com.freerdp.channels.rdpgfx.client: [pid=30026:tid=93f34930] - rdpgfx_recv_pdu failed with error 1359!
03-17 16:48:19.577 30026 13700 E com.freerdp.channels.drdynvc.client: [pid=30026:tid=93f34930] - drdynvc_order_recv failed with error 1359!
03-17 16:48:19.578 30026 13685 E com.freerdp.core: [pid=30026:tid=9c158930] - drdynvc_virtual_channel_client_thread reported an error. Error was 1359
03-17 16:48:19.578 30026 13685 E com.freerdp.client.android: [pid=30026:tid=9c158930] - Failed to check FreeRDP file descriptor
03-17 16:48:19.578 30026 13685 I com.freerdp.client.android: [pid=30026:tid=9c158930] - Prepare shutdown...
03-17 16:48:19.578 30026 13702 D com.freerdp.client.android: [pid=30026:tid=93d36930] - input_thread Quit.
03-17 16:48:19.581 30026 13685 V GlobalApp: OnDisconnecting
03-17 16:48:19.584 30026 30026 V FreeRDP.SessionActivity: OnDisconnected

Trying to connect to Win-8 machine with today's master code from an Android device. I have enabled gfx from the perfornamce settings.

Trying out  graphics pipeline feature on aFreeRDP app. I am facing the above crash and also few times the screen just stays blank after connecting. Jut want to check if there are any knows issues with the graphics pipeline feature 

Thanks,
Mahesh

**Comment by akallabeth** [comment]
@mvojjala The GFX feature itself is working except that there are some color conversion issues open and android bugs like #3238

**Comment by akallabeth** [comment]
Many improvements in current master.
Reopen if this is still an issue.
