### ISSUE TITLE
cmake error,XRandR wasn't  found

### ISSUE THREAD

**Issue by lifeblong** [FreeRDP/FreeRDP#3246]
plateform:armv7 rk3288
system:ubuntu 15.10

Warning 
Disabling tsmf gstreamer because XRandR wasn't found!

i have installed:
libxrandr-dev
libxrandr2
libxrandr2-dbg
lxrandr
lxrandr-dbg

but it's without effect....

**Comment by bmiklautz** [comment]
@lifeblong try x11proto-randr-dev. Please don't use the issue tracker for questions. 
Drop by in our irc channel or sent an e-mail to our mailing list.
