### ISSUE TITLE
higher CPU usage GFX Windows 10

### ISSUE THREAD

**Issue by drewer** [FreeRDP/FreeRDP#3251]
hi @all 

today i have make a new build (my last was befor two weeks... the CPU Usage was normal 40-60% on a thinclient 1,8 Ghz)

when i start youtube and watch a video the cpu usage goes up to 100% and the quality is bad..
before 2 weeks the video was clear and doesnt studdering

System: Debian 7 amd64 and also on 8 i386

**Comment by akallabeth** [comment]
@drewer With #3215 the new AVC444 format support of windows 10 was added. Software decoding of that codec requires more performance (and is currently less optimized than the old codecs are), looks like your system can not handle that properly and causes lag (which in turn reduces video quality). So either turn off this new codec on the windows 10 machines or disable the feature support announcement in ```channels/rdpgfx/client/rdpgfx_main.c:[94-104]```.

**Comment by ilammy** [comment]
Maybe FreeRDP should provide an option to disable AVC444 while keeping AVC420 enabled.

There is another reason for this except for excess CPU usage. Windows 10 systems without [the update which adds AVC444 support](https://support.microsoft.com/en-us/kb/3118754) do not send AVC420 data when FreeRDP advertises AVC444 support.

**Comment by akallabeth** [comment]
@ilammy Just started working on that ;)

**Comment by akallabeth** [comment]
@ilammy Ok, #3254 implements what you are looking for ;)
Would be nice if someone could find the time to add accelerated H264 decoding in FreeRDP though. (sadly I don't have that)

**Comment by ilammy** [comment]
@akallabeth, I ain't a SIMD wizard, but I spent a couple hours staring into the MS-RDPEGFX spec and the list of SSE2 instructions... Well, now 2xYUV420 → YUV444 and YUV444→RGBA888 conversions seem to be sort of straightforward (yet convoluted) to vectorize with SSE. I may give it a shot.

**Comment by akallabeth** [comment]
@ilammy Would be a great addition!

**Comment by akallabeth** [comment]
#3767 and others implement NEON and SSE optimisations for RFX/GFX/AVC modes.
