### ISSUE TITLE
xfreerdp not working for non-root users.

### ISSUE THREAD

**Issue by scottsisco** [FreeRDP/FreeRDP#3255]
Hi,

I am running Ubuntu 14.04 Mate. I have followed the installation guide for Debian located at https://github.com/FreeRDP/FreeRDP/wiki/Compilation.

The issue I am having is a strange one. I can use xfreerdp without any issues as root our by using sudo to run the xfreerdp command. However, if I try to run xfreerdp as a normal user I get this error "xfreerdp: error while loading shared libraries: libxfreerdp-client.so.2: cannot open shared object file: No such file or directory" and I can't seem to figure out what is going on.

Running the command "which xfreerdp" always results in /usr/local/bin/xfreerdp, which I believe to be the correct location, no matter what my user privilege is (root, sudoer, non-sudoer), but for some reason any user that does not have root privileges can not use xfreerdp.

Any pointers would be greatly appreciated.

Thanks!
Scott

**Comment by hardening** [comment]
Well this is an issue tracker, not a help forum. But I'd bet that a directory in /usr/local/lib is not executable by other persons than root, or that the library itself cannot be read. a ldd /usr/local/bin/xfreerdp.
Go and ask on IRC or use the mailing list for that kind of help.
