### ISSUE TITLE
Compile without any OpenSSL RC4 support

### ISSUE THREAD

**Issue by sofar** [FreeRDP/FreeRDP#3256]
In ClearLinux, we compile OpenSSL without rc4 support (it's not just disabled, we remove it) due to the inherent insecureness of that cipher.

I'd like to be able to compile FreeRDP without manually patching RC4 support out manually myself, bu just by doing a quick -DENABLE_RC4=off or similar.

Right now there are not many distributions removing RC4 support, but this will likely become a growing problem, so, it may be worth considering sooner rather than later.

**Comment by bmiklautz** [comment]
@sofar it would be nice to completely disable RC4 however it's required by some parts of the protocol and it might not be possible to connect to some servers (when RDP security, or licensing is required) if disabled.

**Comment by sofar** [comment]
I'm perfectly okay with losing functionality to connect to some servers. As it stands, ClearLinux won't ever be able to run any FreeRDP session. 

RC4 should be disabled everywhere, so this project can help by making it easy to disable.

**Comment by bjcollins** [comment]
@sofar I agree that RC4 is insecure and it would be nice to disable it everywhere, but have you done a security analysis of the use of RC4 in RDP?

There are some uses of RC4 in the RDP protocol that are relics of the legacy RDP protocol vs. sticking around purely for security reasons. Licensing is a case where RC4 is always needed, however the licensing data is already encrypted and you can enforce strong algorithms at a higher level negating the fact that RC4 is insecure in this case.

Still to this day, the use of RC4 is required for RDP licensing and I think part of the reason for this is that if you are ensuring strong connection security that the use of RC4 is not there to provide security but instead just to maintain the same legacy packet structure. MD5 hashes are used for this same purpose also.

In an overall analysis, I think a better approach than removing RC4 completely would be to allow an alternative RC4 implementation in FreeRDP then only cripple the functionality where RC4 is being relied on for security. I guess it comes down to the use of RDP you expect in ClearLinux - but crippling RDP licensing seems like it would be very limiting to the end user.

I did not have the issue of OpenSSL without RC4 compiled in, but I did have to use OpenSSL in FIPS mode and provide RC4/MD5 overrides with justification in my PR #3904, there is also an earlier PR by someone else #3877 for that same issue.

**Comment by timofonic** [comment]
Any news about this? What happened with RC4?
