### ISSUE TITLE
clipboard redirect on windows

### ISSUE THREAD

**Issue by melanholy** [FreeRDP/FreeRDP#3261]
Recently I discovered that clipboard redirection in windows is actually working, half of it, at least. It works only one way: from remote desktop to me, not vice versa.
Is this a problem of FreeRDP or am I doing something wrong?

My command line is: wfreerdp.exe /v:[addr] /u:[user] /p:[pass] /cert-ignore +clipboard

**Comment by akallabeth** [comment]
@melanholy which git revision did you test and also which os? current master works both ways (x11) for basic text/html/image, have not tested the other clients recently.

**Comment by melanholy** [comment]
Latest master doesn't work either. I'm using windows 7.

**Comment by mikhaXD** [comment]
i also have problem with clipboard. used latest version from here https://ci.freerdp.com/job/freerdp-nightly-windows/

im using win 8.1 x64, tried x64 and x32 versions. Clipboard redirect  working when i copy text from my pc to rdp. 
But after copying from rdp to my pc, - copying in both sides stop working. I cannot copy text from my pc to rdp, but all text is sucessfly copied from RDP to my pc. so only one side copying works RDP >> Client PC. But ClientPC >> RDP not working. 

Reconecting can solve the problem, but after copying from rdp to PC = clipboard redirection stops work again(( 
Tried for all rdps ( Win7, Win8, 2008, 2012) everywhere this same problem. also tried different builds of freerdp. - no result(( please fix this.

**Comment by mikhaXD** [comment]
Seems i found the source of this problem.

if opened teamviewer, other rdp connection, vmware or other software - using the clipboard - we will see the problems with two way clipboard transfering (only one way stay works).
also problem exists if freerdp.exe used to connect inside other rdp, clipboard also stops works. 

if no other programs opened - clipboard redirection works in two ways long time without any problems.

is it can be fixed?

**Comment by wangchuanguo** [comment]
i also have problem with clipboard. used the master.
i'm useing win7 x64, remote is win server2008.
It works only one way: from remote desktop to me.

**Comment by wangchuanguo** [comment]
i also have problem with clipboard. used the master.
i'm useing win7 x64, remote is win server2008.
It works only one way: from remote desktop to me.

**Comment by wangchuanguo** [comment]
i also have problem with clipboard. And i find a solution, add one line before 
+ case WM_DRAWCLIPBOARD:
   case WM_CLIPBOARDUPDATE:

The reason is that:  xp have not AddClipboardFormatListener, can not get WM_CLIPBOARDUPDATE.
----My local OS is xp.

**Comment by akallabeth** [comment]
Working with current master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
Reopen if you experience differently.
