### ISSUE TITLE
drivestoredirect parameter in rdp file is not correctly parsed

### ISSUE THREAD

**Issue by HenryJacques** [FreeRDP/FreeRDP#3267]
Using latest master and a rdp file containing the `drivestoredirect`parameter.
As stated in MS' specifications, if no value is specified the client must not redirect any drives.
Using mstc, the following line has the effect to not redirect any drive:

> drivestoredirect:s:

However FreeRDP redirects the root "/" even if no drive is specified.

**Comment by bmiklautz** [comment]
@HenryJacques would you add the rdp file your resting with for reference?

**Comment by HenryJacques** [comment]
@bmiklautz of course:

> redirectclipboard:i:0
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:0
redirectdrives:i:0
drivestoredirect:s:
session bpp:i:32
prompt for credentials on client:i:1
span monitors:i:1
use multimon:i:1
remoteapplicationmode:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:0
videoplaybackmode:i:1
audiocapturemode:i:0
gatewayusagemethod:i:0
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:MYBROKER.MYDOM
alternate shell:s:||iexplore
remoteapplicationprogram:s:||iexplore
remoteapplicationname:s:MyApp
remoteapplicationcmdline:s:-k http://myapp.mydom/
workspace id:s:MYBROKER.MYDOM
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.MYAPP
alternate full address:s:MYBROKER.MYDOM

**Comment by AlexDarkf0x** [comment]
I can confirm I have the same issue. Master with commit  a0d9969
Removing the line from .rdp file, works for me.
