### ISSUE TITLE
build warning: WARNING: XML failed validation against built-in DTD

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#3269]
For a little while I get these warnings:
[   83s] [ 76%] Generating xdg-shell-client-protocol.h
[   83s] Scanning dependencies of target audin-client
[   83s] %3Cstdin%3E:342: element entry: validity error : Element entry content does not follow the DTD, expecting (description)?, got (CDATA)
[   83s] %3Cstdin%3E:346: element entry: validity error : Element entry content does not follow the DTD, expecting (description)?, got (CDATA)
[   83s] %3Cstdin%3E:350: element entry: validity error : Element entry content does not follow the DTD, expecting (description)?, got (CDATA)
[   83s] %3Cstdin%3E:356: element entry: validity error : Element entry content does not follow the DTD, expecting (description)?, got (CDATA)
[   83s] *******************************************************
[   83s] *                                                     *
[   83s] * WARNING: XML failed validation against built-in DTD *
[   83s] *                                                     *
[   83s] *******************************************************
[   83s] Scanning dependencies of target audin-client-oss
[   83s] [ 76%] Generating xdg-shell-protocol.c
[   83s] [ 76%] Building C object channels/audin/client/CMakeFiles/audin-client.dir/audin_main.c.o
[   83s] Scanning dependencies of target rdtk
[   83s] %3Cstdin%3E:342: element entry: validity error : Element entry content does not follow the DTD, expecting (description)?, got (CDATA)
[   83s] %3Cstdin%3E:346: element entry: validity error : Element entry content does not follow the DTD, expecting (description)?, got (CDATA)
[   83s] %3Cstdin%3E:350: element entry: validity error : Element entry content does not follow the DTD, expecting (description)?, got (CDATA)
[   83s] %3Cstdin%3E:356: element entry: validity error : Element entry content does not follow the DTD, expecting (description)?, got (CDATA)
[   83s] *******************************************************
[   83s] *                                                     *
[   83s] * WARNING: XML failed validation against built-in DTD *
[   83s] *                                                     *
[   83s] *******************************************************
[   83s] [ 77%] Building C object channels/audin/client/oss/CMakeFiles/audin-client-oss.dir/audin_oss.c.o

I'm not sure, what this means. Otherwise the build completes and the version works for my use cases.

**Comment by akallabeth** [comment]
could you give some details to your os and cmake configuration? pretty hard to guess without these details what could be wrong ;)

**Comment by hendwolt** [comment]
I use SUSE's Open Build Service to build freerdp for different openSUSE versions and Arch Linux. I checked all build logs and these warnings occur only on openSUSE Tumbleweed. No other versions are affected.
For the configuration I attached my spec file.

[freerdp.spec.zip](https://github.com/FreeRDP/FreeRDP/files/207201/freerdp.spec.zip)

**Comment by bmiklautz** [comment]
@hendwolt can you provide the link to obs project page?

**Comment by bmiklautz** [comment]
@hendwolt the reported error is related to wayland. I'd assume when the protocol is "compiled".
@hardening any ideas?

**Comment by hendwolt** [comment]
The project page:
https://build.opensuse.org/package/show/home:hendwolt/freerdp

**Comment by hendwolt** [comment]
"Somewhere on the internet" I found a wayland.dtd and found errors in xdg-shell.xml.

[xdg_shell_xml.patch.zip](https://github.com/FreeRDP/FreeRDP/files/210436/xdg_shell_xml.patch.zip)

**Comment by hendwolt** [comment]
fixed with #3408
