### ISSUE TITLE
RemoteApp - no window button on taskbar for Adobe Photoshop

### ISSUE THREAD

**Issue by jacob019** [FreeRDP/FreeRDP#327]
RemoteApp does not display a window button for Adobe Photoshop.  I suspect it is inheriting this from the splash screen.

Here's a screenshot:
http://www.jacobstoner.com/screenshot.jpg

Curious behavior with child windows: 
-disable the photoshop option "open documents as tabs" so that documents get their own window
-create a new document (get's it's own window, no application button at this point)
-drag the new document window... application icon appears (still no button for main photoshop window)

Environment:
-latest master (3e029a10e0)
-windows 2008 (not R2)
-tested with both xfce and gnome, with and without a composting window manager, consistent behavior

**Comment by hardening** [comment]
@jacob019 could you give a try with latest master ?

**Comment by akallabeth** [comment]
no response in a very long time, closing.
