### ISSUE TITLE
compile error with openh264

### ISSUE THREAD

**Issue by Thermaltake** [FreeRDP/FreeRDP#3270]
Hello.
An error occurred while compiling.

error log
https://gist.github.com/Thermaltake/b076bccc1535cc48b13536e1f9dcd92b

cmake https://gist.github.com/Thermaltake/a0016250c5aede6fb2cd9b12be1219dd#file-cmake-L39

without openh264 compilation goes without error.

use ubuntu-mate on raspberry pi 2.
and https://github.com/cisco/openh264/commit/eb9f56584fae81eab9be6ab999040ed5e4a7cfcd

What am I doing wrong?
Sorry for bad english. I use google translate.

**Comment by bmiklautz** [comment]
@Thermaltake try using v1.5.1 of openh264.

**Comment by Thermaltake** [comment]
Thanks for the help.
Good. Compile happened.

I tested a job /ghx-h264:AVC420 and AVC444.% CPU load close to 100% when playing youtube video in a small window. Videos with the brakes. Moreover, the load goes to the processor core, but they are not fully loaded.
http://s009.radikal.ru/i309/1604/7e/d26133af5c3d.jpg

If use /ghx:RFX, the CPU 300-350% load when playing the same video, the processor cores load close to full. But the video works a bit better.
http://s002.radikal.ru/i198/1604/ed/6112d8ea25ab.jpg

How can using the /gfx-h264 use a kernel fully, ensuring smooth video playback?

As it is possible to reduce the load on the CPU, using h264?

**Comment by bmiklautz** [comment]
@Thermaltake as you initial issue seems to be resolved I'll close this issue. Regarding your question AVC444 was added recently and does currently don't have any optimized version. At least for h264 performance there are multiple open issues. If you have other questions visit us in the irc channel or contact the mailing list.
