### ISSUE TITLE
I can't build freerdp-android under mac osx 

### ISSUE THREAD

**Issue by xyz8808** [FreeRDP/FreeRDP#3272]
I got the following error:
[  1%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/synch/wait.c.o
/android/FreeRDP-master/winpr/libwinpr/synch/wait.c:108:12: error: static declaration of 'pthread_mutex_timedlock' follows non-static declaration
 static int pthread_mutex_timedlock(pthread_mutex_t *mutex, const struct timespec *timeout)
            ^
In file included from /android/FreeRDP-master/winpr/libwinpr/synch/synch.h:50:0,
                 from /android/FreeRDP-master/winpr/libwinpr/synch/wait.c:44:
/android/android-ndk/platforms/android-L/arch-arm/usr/include/pthread.h:208:5: note: previous declaration of 'pthread_mutex_timedlock' was here
 int pthread_mutex_timedlock(pthread_mutex_t*, const struct timespec*) __nonnull((1, 2));
     ^
make[2]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/synch/wait.c.o] Error 1
make[1]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/all] Error 2
make: *** [all] Error 2

**Comment by bmiklautz** [comment]
@xyz8808 without more information we won't be able to help. Have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by xyz8808** [comment]
The problem is solved.  Replace android ndk r10b to r9d ,and then it passed.
