### ISSUE TITLE
debug wiki page is obsolete

### ISSUE THREAD

**Issue by wtfrank** [FreeRDP/FreeRDP#3277]
I haven't been able to find information about turning on debugging, and the wiki page concerning debugging is marked as obsolete.

https://github.com/FreeRDP/FreeRDP/wiki/Debug-System

**Comment by bmiklautz** [comment]
@wtfrank that's obviously true. Basic debugging can be enabled by setting the environment variable WLOG_LEVEL=DEBUG or TRACE (in the latter case also packages are dumped (to /tmp/.wlog iirc).

**Comment by wtfrank** [comment]
Ok I've put a small note on that wiki page with your comment in.

**Comment by akallabeth** [comment]
Updated the debug wiki to the current implementation.
