### ISSUE TITLE
Windows console does not update correctly

### ISSUE THREAD

**Issue by ppanhoto78** [FreeRDP/FreeRDP#3278]
FreeRDP (1.0.2-9.1 on OpenSuSE leap) is showing problems both Windows or MinGW consoles (git bash, in my case). This happens a VirtualBox native RDP server and WindowsXP server, Remmina and KRDC, xFreeRDP were the clients with the same results.

Windows Console:
![freerdp-console](https://cloud.githubusercontent.com/assets/17730373/14442973/e36c6e10-0012-11e6-9129-554ebf7b0c24.png)

When the prompt is larger than the console size, the background is not refreshed correctly.
Steps to reproduce:

1. run cmd.exe
2. go to a very long path, greater than the terminal length. 
3. Minimise and then restore the console window. 
That should show as the image above.
To "fix" the window, just drag the window as it'll redraw entirely.

MinGW bash window:
![freerdp-mingw](https://cloud.githubusercontent.com/assets/17730373/14443096/8baa6d48-0013-11e6-8722-d493f92d45ee.png)

Apparently it never redraws the background except when the window is dragged.
Steps to reproduce:
1. Install git/git bash
2. start git bash.
It look like the background is transparent. If you run any command that prints to screen, (ls, for example), everything will get painted on top of.
Dragging the window forces the background to repaint.

**Comment by hardening** [comment]
xfreerdp 1.0 is really old, do you experiment the same kind of behaviour with last versions (hint: you can download pre-built packages) ?

**Comment by ppanhoto78** [comment]
No. I haven't yet. Tried to compile the libraries and got stuck at this point, though:

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GSTREAMER_1_0_APP_LIBRARIES
    linked by target "tsmf-client-gstreamer-decoder" in directory /home/paulo/src/FreeRDP/channels/tsmf/client/gstreamer
GSTREAMER_1_0_VIDEO_LIBRARIES
    linked by target "tsmf-client-gstreamer-decoder" in directory /home/paulo/src/FreeRDP/channels/tsmf/client/gstreamer

Don't know which package provides these files.

**Comment by ppanhoto78** [comment]
Installed a nightly build and it appears to be working.

**Comment by andreasstieger** [comment]
A note from your friendly distribution maintainers... As you just labeled your latest stable release as "really old"... why not make a bugfix release every once in a while to deliver your fixes to distros? Everything newer is "beta" and "tech preview" or "nightly".

**Comment by tigerfoot** [comment]
Also what version 1.0 1.1 1.2 ?

**Comment by bmiklautz** [comment]
@andreasstieger easy to say ;). If you search the issue tracker there are multiple issues regarding a new release.  I'm aware that the current release "management" is a horror for distributions but starting with 2.0 we'll try to do bug fix releases or new more often. But we first need to get to a state where we can say this is stable (especially the ABI/API). We don't just want to define the current code as stable and create a release out of it and have API/ABI changed again later on..

**Comment by bmiklautz** [comment]
@tigerfoot next, and current master is 2.0.

**Comment by tigerfoot** [comment]
@bmiklautz thanks for the informations.

**Comment by tigerfoot** [comment]
@ppanhoto78 
With the package we have in oss for openSUSE (Tumbleweed) I can work with no trouble against xp, win7, win8.1, win2008 win2012 include sharing disk, having sound and on long cmd.exe terminal

![screenshot_20160413_112027](https://cloud.githubusercontent.com/assets/788864/14488752/fd34cd9e-0169-11e6-8682-d38fd7066f49.png)

So I can't even reproduce it.

**Comment by ppanhoto78** [comment]
@tigerfoot Tumbleweed and Leap use different versions. Can you try that with git (or MinGW) bash?

**Comment by tigerfoot** [comment]
@ppanhoto78 nope 13.1, 13.2, 42.1 and tumbleweed all use 1.0.2 version (I know it because I'm doing the packaging :-)

I will try git bash but I need 2 days, I can't pollute a production machine I will try on my personnal windows 10.

**Comment by ppanhoto78** [comment]
Leap appears as 1.0.2-_9.1_ and Tumbleweed appears as 1.0.2-_9.4_
http://download.opensuse.org/distribution/leap/42.1/repo/oss/suse/x86_64/freerdp-1.0.2-9.1.x86_64.rpm
http://download.opensuse.org/tumbleweed/repo/oss/suse/x86_64/freerdp-1.0.2-9.4.x86_64.rpm
Only difference I can tell is that one works and the other doesn't.

**Comment by ppanhoto78** [comment]
I've upgraded my packages to tumbleweed's and I've got different results than the first reported: if the  RDP server is an actual windows system, the terminals get correctly updated. 
The problem still exists when the server is a VirtualBox' RDP server on linux.
