### ISSUE TITLE
android afreerdp h264 connect win10 have many white blocks

### ISSUE THREAD

**Issue by jinlong0813** [FreeRDP/FreeRDP#3279]
Dear ALL,
 I want to use android afreerdp connect to windows 10 with h264. I have checked on RemoteFX, GFX and H264. when I login the win10, there are many white blocks. If I turn off the H264, it works fine. I don't know where is wrong, need your help! 
Thanks very much!
![h264](https://cloud.githubusercontent.com/assets/16506647/14451733/de1b6e08-00bb-11e6-84a1-3c57ee104a82.jpg)

**Comment by akallabeth** [comment]
color converstion for different codecs does not always respect the target order. I'm working on it but will take some time as it is a rather major change.

**Comment by guokai0828** [comment]
Try to change the uv order when yuv2rgb in H264 decompress maybe fix the color issue. 
But how to display the right image in the white blocks area?

**Comment by jinlong0813** [comment]
Dear akallabeth, we don't care the background color, it looks like the it should reverse the position of U and V on android. The most important problem for me it the white blocks. The white blocks looks like not from the Open H264 frame data. It's the most headache problem for us. Really need your help. Thanks.

**Comment by akallabeth** [comment]
is most likely clearcodec. but if you want to try https://github.com/akallabeth/FreeRDP/tree/color_conversion_fix 
it is mostly done, except some issues with drawing orders and missing 8bit color legacy support.

**Comment by chandramouligoru** [comment]
I am facing the same issue with aFreeRDP connecting to Win08 then I tried the color_conversion_fix_v3 branch to check how it looks. color conversion has gone haywire in this as well. Kindly check the screenshot.
![device-2016-04-27-124959](https://cloud.githubusercontent.com/assets/17047692/14844667/a445ec1e-0c76-11e6-8fdd-9a15c370425e.png)


@jinlong0813 For me Gfx pipeline wouldn't work without enabling H264. Have you done any other changes to make it work with Gfx pipeline?. I am getting the same error as reported https://github.com/FreeRDP/FreeRDP/issues/3245

**Comment by akallabeth** [comment]
@chandramouligoru looks like I've mixed up the color initialisation. Should be ```PIXEL_FORMAT_RGBA32``` for ```gdi_init```, the clear codec stuff is not properly decoding anyhow.

**Comment by akallabeth** [comment]
@chandramouligoru Oh, and for the time being ```-DWITH_SSE=OFF -DWITH_NEON=OFF``` is required until the optimisations for colour conversion have been adapted.

**Comment by chandramouligoru** [comment]
@akallabeth those flags dint work. Probably I should wait till you get it to master.

**Comment by chandramouligoru** [comment]
@akallabeth do you have any update on this?

**Comment by akallabeth** [comment]
@chandramouligoru My work has been delayed by other duties. Will need some time to be finished.

**Comment by chandramouligoru** [comment]
@akallabeth I am still kinda looking for an update on this. Do you have one?

**Comment by akallabeth** [comment]
@chandramouligoru Sorry, this will still take some time.

**Comment by akallabeth** [comment]
@chandramouligoru So, started working on that branch again https://github.com/FreeRDP/FreeRDP/tree/color_conversion_fix_v4
It is already quite usable but needs testing (some GDI quirks are currently bugging me)

**Comment by akallabeth** [comment]
@chandramouligoru Color conversion patches have been merged. One remaining issue is a very specific bug in ClearCodec (clear_decompress) which I did not find time to trace back.

**Comment by chandramouligoru** [comment]
@akallabeth 
I just tried latest master RDPing to Windows 2008 machine by enabling GFX/ H264 and I could still see the color issues. Below is a screen grab.

![device-2016-10-21-111946](https://cloud.githubusercontent.com/assets/17047692/19588052/adb65672-9780-11e6-9ba1-700f6ed86683.png)

**Comment by akallabeth** [comment]
what specific issue is there? wrong color of fonts? did you compile with openh264? and could you give some details about connection settings?

**Comment by chandramouligoru** [comment]
Here is the actual screen grab without Gfx/ H264.
![device-2016-10-21-142342](https://cloud.githubusercontent.com/assets/17047692/19592628/43116586-979a-11e6-9328-f78fad08aa01.png)

Yes. I did compile with openh264.

**Comment by akallabeth** [comment]
@chandramouligoru Could you check logcat for RFX/GFX decoding messages (please activate logging in the bookmark first). Looks a lot like there is no GFX used.

**Comment by akallabeth** [comment]
Just for reference, #3527 duplicates this.

**Comment by akallabeth** [comment]
Closing as current master has seen decoder refinements.
Reopen if still an issue.
