### ISSUE TITLE
compile error with latest version

### ISSUE THREAD

**Issue by trentasis** [FreeRDP/FreeRDP#3280]
During compile we receive:

-- Finding recommended feature OSS for sound (audio input, audio output and multimedia redirection)
--     Disable feature OSS using "-DWITH_OSS=OFF"
-- Found OSS Audio
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Found ALSA: /usr/lib/libasound.so (found version "1.0.29")
-- Finding optional feature Pulse for sound (audio input, audio output and multimedia redirection)
-- checking for module 'libpulse'
--   found libpulse, version 6.0
-- Found Pulse: /usr/include
-- Finding optional feature Cups for printing (printer device redirection)
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Cups (missing: CUPS_LIBRARIES CUPS_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindCups.cmake:74 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/FindFeature.cmake:31 (find_package)
  CMakeLists.txt:681 (find_feature)

-- Configuring incomplete, errors occurred!
See also "/ts/ports/opt/freerdp/work/src/FreeRDP/CMakeFiles/CMakeOutput.log".
See also "/ts/ports/opt/freerdp/work/src/FreeRDP/CMakeFiles/CMakeError.log".

With git 45ab979 was working without any problems with same build command:

cmake .	-DCMAKE_INSTALL_PREFIX=/usr \
		-DCMAKE_INSTALL_LIBDIR=lib \
		-DDOCBOOKXSL_DIR=/usr/share/sgml/docbook/xsl-ns-stylesheets \
		-DCMAKE_BUILD_TYPE=Release \
		-DWITH_PCSC=ON \
		-DBUILD_SHARED_LIBS=ON \
		-DWITH_CHANNELS=ON \
		-DWITH_CHANNELS_PRINT=ON \
		-DWITH_SERVER=OFF \
		-DWITH_CLIENT=ON \
		-DWITH_PULSE=ON \
		-DWITH_ALSA=ON \
		-DWITH_CUPS=ON \
		-DWITH_FFMPEG=ON \
		-DCHANNEL_URBDRC_CLIENT=ON \
		-DWITH_GSTREAMER=ON \
		-DWITH_DIRECTFB=OFF \
		-DWITH_XINERAMA=ON \
		-DWITH_CUNIT=OFF \
		-DWITH_JPEG=ON \
		-DWITH_IPP=OFF \
		-DWITH_NPP=OFF \
		-DWITH_MANPAGES=ON \
		-DWITH_SAMPLE=ON

Thanks

**Comment by bmiklautz** [comment]
@trentasis  have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting for the next time.
Anyway... You specified -DWITH_CUPS=ON  but you are missing the cups devel package
```
-- Finding optional feature Cups for printing (printer device redirection)
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
Could NOT find Cups (missing: CUPS_LIBRARIES CUPS_INCLUDE_DIR)
Call Stack (most recent call first):
/usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
/usr/share/cmake-3.2/Modules/FindCups.cmake:74 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
cmake/FindFeature.cmake:31 (find_package)
CMakeLists.txt:681 (find_feature)
```
On Debian/Ubuntu install libcups2-dev, crm your CMakeCache.txt  and rerun cmake.
