### ISSUE TITLE
merge #3274 missed the pulse directories

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#3281]
When I build the latest source including #3274, and with "-DWITH_PULSE=ON" I get errors like "undefined reference to `WLog_Get'".

It seems this fix missed some directories.

**Comment by bmiklautz** [comment]
@hendwolt could you please add more information like:
* complete cmake options
* where exactly do you get the error?

**Comment by hendwolt** [comment]
This is my cmake configuration:
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX:PATH=%{_prefix} \
    -DCMAKE_INSTALL_LIBDIR:PATH=%{_lib} \
    -DCMAKE_SKIP_INSTALL_RPATH=ON \
    -DWITH_CUPS=ON \
    -DWITH_CLIENT=ON \
    -DWITH_PCSC=ON \
    -DWITH_ALSA=ON \
    -DWITH_PULSE=ON \
    -DWITH_DIRECTFB=OFF \
    -DWITH_FFMPEG=OFF \
    -DWITH_JPEG=ON \
    -DWITH_GSM=ON \
    -DWITH_GSTREAMER_1_0=ON \
    -DWITH_IPP=OFF \
    -DWITH_OPENSSL=ON \
    -DWITH_CHANNELS=ON \
    -DWITH_X11=ON \
    -DWITH_XCURSOR=ON \
    -DWITH_XEXT=ON \
    -DWITH_XKBFILE=ON \
    -DWITH_XI=ON \
    -DWITH_XINERAMA=ON \
    -DWITH_XRENDER=ON \
    -DWITH_XV=ON \
    -DWITH_ZLIB=ON \
    -DSTATIC_CHANNELS=OFF \
    -DWITH_SERVER=OFF \
    -DWITH_SSE2=ON \
    -DWITH_DEBUG_SCARD=OFF \
    -DWITH_SMARTCARD_INSPECT=ON \
    -DWITH_WAYLAND=ON \
    -DWITH_LIBSYSTEMD=ON \
    -DCMAKE_NO_BUILTIN_CHRPATH=ON \
    .

For the errors see the attached file.
[free_rdp_pulse_undef_ref_errors.txt](https://github.com/FreeRDP/FreeRDP/files/217371/free_rdp_pulse_undef_ref_errors.txt)

If I set WITH_PULSE=OFF I get no errors.

**Comment by bmiklautz** [comment]
@hendwolt with you cmake command line I can reproduce the problem. Pulse wasn't tested with -DSTATIC_CHANNELS=OFF (as our ci usually only builds with static channels). I'll prepare a fix.

**Comment by nfedera** [comment]
@hendwolt fixed by @bmiklautz via #3287
