### ISSUE TITLE
Sound redirection delay error

### ISSUE THREAD

**Issue by seesky** [FreeRDP/FreeRDP#3283]
Hello ,i have a problem with sound redirection. i design a thin client to connect windows vm with freerdp:
        cpu:rk3288
        sound card:wm8960 with alsa
        os:linux
   In addition to the sound redirection,the others are perfect.When i connect win7 with command:
        xfreerdp /f /usb:auto /gestures /multitouch /sec:nla +async-update /v:'192.168.1.101' /u:administrator /p:"123456" /t:test0 /bpp:32 /port:3389 /sound:sys:pulse /microphone:sys:pulse +fonts +aero /rfx
   When i set sampling rate of wm8960 to 48000Hz, I can hear the sound from win7 vm,but when i play a video,the sound delay(video and sound Cannot synchronize).
When i set sampling rate of wm8960 to 44100Hz,I can hear the sound from win7 vm,there is no sound delay,but I get little stutters every five second,and got error:
ALSA Lib pcm.c:7905 (snd_pcm_recover) underrun occurred
    I have test spice protocl and local play,every thing is ok.
    I don't know what happened.My English is so so,I am sorry.....

**Comment by WarheadsSE** [comment]
Your problem is not FreeRDP, but with your re-sampling configuration for Pulse Audio.

**Comment by seesky** [comment]
I get this error from alsa when I get little stutters every five second.
ALSA lib /home/phoenix/Deskpool/Client/Sabre/Yocto/new/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/alsa-lib/1.0.26-r0/alsa-lib-1.0.26/src/pcm/pcm.c:7339:(snd_pcm_recover) underrun occurred
ALSA lib /home/phoenix/Deskpool/Client/Sabre/Yocto/new/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/alsa-lib/1.0.26-r0/alsa-lib-1.0.26/src/pcm/pcm.c:7339:(snd_pcm_recover) underrun occurred
ALSA lib /home/phoenix/Deskpool/Client/Sabre/Yocto/new/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/alsa-lib/1.0.26-r0/alsa-lib-1.0.26/src/pcm/pcm.c:7339:(snd_pcm_recover) underrun occurred
ALSA lib /home/phoenix/Deskpool/Client/Sabre/Yocto/new/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/alsa-lib/1.0.26-r0/alsa-lib-1.0.26/src/pcm/pcm.c:7339:(snd_pcm_recover) underrun occurred
ALSA lib /home/phoenix/Deskpool/Client/Sabre/Yocto/new/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/alsa-lib/1.0.26-r0/alsa-lib-1.0.26/src/pcm/pcm.c:7339:(snd_pcm_recover) underrun occurred
ALSA lib /home/phoenix/Deskpool/Client/Sabre/Yocto/new/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/alsa-lib/1.0.26-r0/alsa-lib-1.0.26/src/pcm/pcm.c:7339:(snd_pcm_recover) underrun occurred

I try set buffer size in /etc/asound.conf,but it dons't work.
How to configuration pulse audio to fix this error... @WarheadsSE   thank you very much!

**Comment by akallabeth** [comment]
#4453 did fix a lot of delay/codec/feature related issues.
closing this, reopen/create a new one if you still experience a problem.

**Comment by lhzw** [comment]
/sound:sys:alsa,format:1,quality:high
works for me, thanks a lot!!

With this package:
https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/
freerdp-nightly_2.0.0+0~20191115024827.726~1.gbp6bf949_amd64.deb
