### ISSUE TITLE
/gdi:hw in windows

### ISSUE THREAD

**Issue by melanholy** [FreeRDP/FreeRDP#3286]
When /gdi:hw option is set(and this is default), colors on remote machines become strange. Also there is some buffering problems(changes on the screen doesn't show while there is few of them). And one very big problem is that sometimes remote machine stucks on welcome screen.
Here is some screenshots:

![untitled](https://cloud.githubusercontent.com/assets/10682553/14556858/b886a2ca-0313-11e6-8fbe-181802c59d27.png)
This welcome message won't go away.
![untitled](https://cloud.githubusercontent.com/assets/10682553/14556877/d5643b00-0313-11e6-9dea-d74fe020f8bb.png)

I use widnows 7 and the latest version of freerdp. With /gdi:sw colors are normal, but welcome screen problem stays.

**Comment by Chrispy111** [comment]
I had this Problem too.  It appears that freeRDP Colors were switched to x11 Colors without any regard to Windows and the /gdi:sw is too slow and broken when it Comes to scaling.  It would be nice if the Colors were handled differently for each System.  If you want to put it back check out orders.c and Color.c, they both have inverted reading of Color and Bitmaps, plus in wf_gdi.c they switched tofreerdp_color_convert_var_rgb when it was freerdp_color_convert_var_bgr.

**Comment by langazov** [comment]
I had the same problem also.
Regards,
Emil

**Comment by akallabeth** [comment]
GDI mode working on master 3c7cc555a5a5f02366918be7eb935bb1f22115ef
