### ISSUE TITLE
Some programs do not work

### ISSUE THREAD

**Issue by Tacioandrade** [FreeRDP/FreeRDP#3290]
Hello everyone, this week made a FreeRDP test to run applications via RemoteApp on a Windows Server 2008R2, however even after publishing several applications in the same way, I could only make Winrar worked properly, the other gave an error message as if it was not published correctly.
The strange thing is that on a Windows computer 10 here in my lab, I could run via coretamente RemoteApp already in Ubuntu 14.04, I could only making any application, even unposted could be executed (which in a real environment would not to release).
Does anyone know what could be?

**Comment by hardening** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
