### ISSUE TITLE
host notifications break rdp session focus

### ISSUE THREAD

**Issue by hombibi** [FreeRDP/FreeRDP#3291]
I had posted this bug already at ubuntu launchpad, as comment with an existing bug. But that one is idle for a long term. Probably I should have posted here in the first place.

I run Xfreerdp on Ubuntu Gnome, X64, 15.10. I use  standard xfreerdp to maintain a rdp session to a Windows 10 machine on the local network, primarily in full screen mode, for long periods of time. To start the session I use a simple bash script with the following command:

`xfreerdp /v:"${remotechoice}.domain" /u:username /f /bpp:32 /gdi:hw /audio /microphone:sys:alsa /sound:sys/alsa /fonts /menu-anims`

Several times per day my keyboard becomes unresponsive, and/or the mouse stops working or does only work on some parts of the screen.

When this happens I find that Ubuntu has generated a notification message on the ubuntu desktop: Updates available, mail notifications, or calendar notifications (geary, thunderbird + lightning) mostly. It seems as if the focus is lost and can't be switched back to the RDP session anymore. I do see the terminal from where the rdp session was started react to keyboard input though.
Most often CTRL+Enter does not work anymore in this situation, but if it does it is enough to regain the focus. More often I have to resort to CTRL+C will end the session.

Please let me know if I can be of further help.
Hombibi.

**Comment by bmiklautz** [comment]
@hombibi what version of FreeRDP are you using?

**Comment by hombibi** [comment]
Ah, of course, apologies. I run the standard version from ubuntu repo:
"xfreerdp /version"
"This is FreeRDP version 1.1.0-beta1 (git n/a)"

**Comment by bmiklautz** [comment]
@hombibi would you try one of our nightly builds and see if the problem still exists?
https://ci.freerdp.com/job/freerdp-nightly-binaries/

**Comment by hombibi** [comment]
@bmiklautz All right, I'll give that a try. I'll update this thread with my findings.

**Comment by hombibi** [comment]
@bmiklautz The nightly build installed 2.0.0-dev. So far, so good. An ubuntu "software updates available" notification has not affected the rdp session as it used to, so that's great. I'll keep using it to see if it holds up.
As a side note, the full screen mode now ignores ubuntu gnome's top left "hot corner" that displays all running applications. I very much appreciate that while working on a remote desktop, so a second plus. The 2.0.0-dev version seems to build up screens faster, but that may be perception.
I suppose I run a very unstable version now, and even though it seems to be fine at the moment, would it be advisable to continue to use nightly builds as they become available?

**Comment by hardening** [comment]
We're currently freezing FreeRDP to release a 2.0, so the nighly you're running is very near from the final version, and most probably of better quality than the one that is shipped by you distribution.

**Comment by hombibi** [comment]
I believe my issue is solved in that case. Thank you for your help.
