### ISSUE TITLE
tried to enable ALSA but its not working..

### ISSUE THREAD

**Issue by DieselV** [FreeRDP/FreeRDP#3292]
I am executing freeRDP on mac OS 10.11 and Xcode 7.3 
I am tring to enable ALSA feature to be ON but its not working?

FreeRDP-master macmini$ cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode -DIOS_PLATFORM=SIMULATOR -DWITH_MBEDTLS=ON -DWITH_ALSA=ON
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Git Revision n/a
-- Skipping recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Finding optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature OSS for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Skipping optional feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Enable feature FFmpeg using "-DWITH_FFMPEG=ON"
-- Skipping disabled feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
-- Skipping disabled feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Adding dynamic channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding static channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding dynamic channel client "disp": Display Update Virtual Channel Extension
-- Adding static channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding device channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding dynamic channel client server "echo": Echo Virtual Channel Extension
-- Adding static channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding device channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding static channel client "rail": Remote Programs Virtual Channel Extension
-- Adding static channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding dynamic channel client "rdpei": Input Virtual Channel Extension
-- Adding dynamic channel client "rdpgfx": Graphics Pipeline Extension
-- Adding static channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding static channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding device channel client "serial": Serial Port Virtual Channel Extension
-- Adding device channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding dynamic channel client "tsmf": Video Redirection Virtual Channel Extension
-- Adding iOS client
-- Configuring done
-- Generating done

**Comment by DieselV** [comment]
If somebody have idea how to enable sound/audio and printer redirection then help me.
Thanks

**Comment by akallabeth** [comment]
@DieselV alsa is the LINUX sound backend, you will not have much luck on OS X with that ;)

**Comment by akallabeth** [comment]
@DieselV Use ccmake or the GUI edition of cmake to find configuration options available to you. Sound (CHANNEL_RDPSND) and microphone (CHANNEL_AUDIN) redirection are what you are looking for.
