### ISSUE TITLE
iFreeRDP:After compilation using cmake -DWITH_IOSAUDIO=ON ...audio redirection is not working

### ISSUE THREAD

**Issue by DieselV** [FreeRDP/FreeRDP#3295]
os- mac OSX 10.11
Xcode 7.3
after compiling code using cmake command for sound redirection actually iFreeRDP supposed to redirect sound but its not working

**Comment by akallabeth** [comment]
did you actually activate the audio redirection? To my knowledge the iOS client does not implement that currently. You have to add the required settings yourself.

**Comment by DieselV** [comment]
I used cmake -DWITH_IOSAUDIO=ON ...static library is generated for it...I know iOS client currently doesn't have any UI to make sound enable...Is their cmake command to enable it manually or what parameters to be passed to session to enable sound?
Thanks

**Comment by akallabeth** [comment]
@DieselV Have a look at what the command line parser is doing with ```/sound``` and add these settings to the iOS client. Or you have a look at the Android client and update the iOS FreeRDP event loop with a similar one.

**Comment by akallabeth** [comment]
@DieselV Does the issue persist with current master?

**Comment by akallabeth** [comment]
closing due to lack of feedback.
Reopen if still an issue.
