### ISSUE TITLE
Printer redirections always getting the "Publisher" driver

### ISSUE THREAD

**Issue by AlexDarkf0x** [FreeRDP/FreeRDP#3297]
Hi

I'm using freerdp to connect to a farm 2012, thru a broker2012.
Freerdp version is 2.0 branch, with all commits until Mar 31, 2016.

I've also read the issues bellow, so I think its supposed be fixed, but I'm still getting it.
#3165 Printer fix
[https://github.com/FreeRDP/FreeRDP/issues/2269](url)

Still, using the command bellow, still gets me the Publisher default driver.
`xfreerdp farmhcv.rdp /f /log-level:DEBUG /d:JMS /heartbeat /cert-ignore /serial:COM3,/dev/ttyS0 /u:$usern /p:$userp /drive:"Removable Media",/media /smartcard /printer:nowhere:"Generic / Text Only"`

![20-04-2016 09-07-40](https://cloud.githubusercontent.com/assets/18486080/14667507/8a40a5d8-06d7-11e6-819c-f94dc0fd3357.png)

He even tried to map the printer driver on the server, with no luck : [https://technet.microsoft.com/en-us/library/ff519149%28v=ws.10%29.aspx](url)

I can see in the logs the printer getting redirected with the correct driver

`[09:06:28:489] [4809:4811] [DEBUG][com.freerdp.channel.serial.client] - initializing
[09:06:28:489] [4809:4811] [DEBUG][com.freerdp.channel.serial.client] - Defining COM3 as /dev/ttyS0
[09:06:28:489] [4809:4811] [DEBUG][com.freerdp.channel.serial.client] - Server's serial driver: (nil) (id: 1)
[09:06:28:489] [4809:4811] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [Removable Media] (static)
[09:06:28:489] [4809:4811] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer [nowhere:Generic / Text Only] (static)`

Also tried with other drivers listed on the print server, with no luck.
Connecting directly not using the broker, same result.

**Comment by akallabeth** [comment]
@AlexDarkf0x Your command line is wrong, should be ```/printer:nowhere,"Generic / Text Only"```

**Comment by AlexDarkf0x** [comment]
Hello, 

My mistake, i've tried it like that and works like a charm. 
Tnx.
