### ISSUE TITLE
Some questions about freerdp options

### ISSUE THREAD

**Issue by AlexDarkf0x** [FreeRDP/FreeRDP#3298]
Hi, 

Can someone help me with some questions, not sure if they are issues or not.

Using master 2.0 branch (commit a0d9969).

1) Using `/printer` alone, doesn't redirect all printers, in fact doesn't redirect any printer, should it ?
2) Using multiple /printer options only redirects the first one on the list. Can freerdp redirect more than 1 printer ?
3) On cable or network error, freerdp freezes the image, never closing. Is there any flag so that when a network error occurs, freerdp closes itself, or something like that ?
4) On Windows2012 RDS infrastructure, in freerdp, is there any flag for specifying the RDS pool you want to connect ? On an .rds file, we use `workspace id:s:MYRDSPOOL.mydomain.com` for that.
5) Using NLA, is there any way to identify if a failed connexion was due to a locked account, a expired password, or simple bad credentials, using the debug output of freerdp ?
 
Tnx.

**Comment by akallabeth** [comment]
@AlexDarkf0x
1) Using ca2d015d7afab8af9523f0313b6846a3cd59f305 here with xfreerdp redirects all local printers as expected with ```/printer```
2) Using multiple ```/printer:name,driver``` options works as well. Could you check, if the required drivers are installed on your windows machines? It may take some time until windows recognises the printers.
3) Network connection issues should end the session after some time (10 seconds it is currently, do not remember exactly)

As for your other questions, I don't know, maybe somebody else could answer them.

**Comment by AlexDarkf0x** [comment]
I remake Q4 and Q5, they were a bit confusing. Hope it helps to better understand them.
About Q3, gonna retry it, till now our tests were made by removing the cable from the client machine, will give feedback later on.

**Comment by hardening** [comment]
Q4: I had a quick search, andfound nothing that speaks of workspace id in the specs

Q5: is asked quite usually but I forgot the answer. IIRC there were some PR recently for CredSSP v3 that allows to distinguish this

**Comment by AlexDarkf0x** [comment]
Q4 : I'll try to add my colleagues from our windows admin team to this talk, as they can help you better than me in explaining or providing microsoft links about this item. 
The best I can explain is : In win2012, you can have multiple rds pools (each pool has its own servers), using a single broker (Or HA broker), and the local RDS file defines to which pool of servers the client will be connected.

On Q5, i will try to do a better search, but so far my tests resulted in : 
```
# Errors on user / password wrong
#[18:24:12:373] [10204:[18:24:13:390] [10204:10205] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_AUTHENTICATION_FAILED [0x20009]
#[18:24:13:391] [10204:10205] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094419:SSL routines:SSL3_READ_BYTES:tlsv1 alert access denied
```

```
# Error on password expired / account expired / **Other connection errors**
#[19:12:58:784] [10444:[19:12:59:812] [10444:10445] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error
#[19:12:59:812] [10444:10445] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]
```

The prob is that **#Other connection errors**.

My idea, was when it was detected that the password is expired, a new session not using NLA would be make allowing the user to change its password, but the same error appears with other situations also.

**Comment by AlexDarkf0x** [comment]
Forgot to push the update coment before. Q4 and Q5 updated on top.

**Comment by AlexDarkf0x** [comment]
Update on Q2 : 
Still redirecting only 1st printer. Not sure if is because i'm using file uri's printers, but right now i dont have access to multiple physical printers on a physical system.

Printers : 

```
device for lp0: /tmp/out.txt
device for lp1: /dev/null
device for nowhere: /dev/null
```
```
printer lp0 is idle.  enabled since Fri 22 Apr 2016 10:01:27 AM WEST
printer lp1 is idle.  enabled since Fri 22 Apr 2016 10:01:23 AM WEST
printer nowhere is idle.  enabled since Fri 22 Apr 2016 09:38:44 AM WEST
```
Command used : 
`xfreerdp farmhcv.rdp /f /log-level:DEBUG /d:JMS /heartbeat /cert-ignore /serial:COM3,/dev/ttyS0 /u:$usern /p:$userp /drive:"Removable Media",/media /smartcard /printer:lp0,"Generic / Text Only" /printer:lp1,"Generic / Text Only" /printer:nowhere,"Generic / Text Only"`

Result, only the 1st printer is redirected. I can redirect any of them individually, but together, only the 1st one goes. I can see both being redirected on the logs.

Logs : 
```
[13:20:59:880] [2756:2758] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [Removable Media] (static)
[13:20:59:880] [2756:2758] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer [lp0] (static)
[13:20:59:881] [2756:2758] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer [lp1] (static)
[13:20:59:881] [2756:2758] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer [nowhere] (static)
[13:20:59:881] [2756:2758] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service smartcard (static)
```

**Comment by akallabeth** [comment]
freerdp uses cups for printer redirection, those are cups printers or not?

**Comment by AlexDarkf0x** [comment]
@akallabeth 

All printers are cups printers.

I'm gonna remake using latest master, and will see if the issue still exists after #ca2d015

@hardening 
The best they could provide me about the pool conections (Collections they call it), was this [link.](https://community.spiceworks.com/topic/1241193-connection-broker-in-2012-r2)

**Comment by AlexDarkf0x** [comment]
Update : Tested the printers issues with usb printers, problems remains, opened https://github.com/FreeRDP/FreeRDP/issues/3310 just for the printer issues, and will close this issue.
