### ISSUE TITLE
Segmentation fault with option /multimedia:codec:ffmpeg

### ISSUE THREAD

**Issue by bjoernv** [FreeRDP/FreeRDP#3299]
I tried to get multimedia (video) redirection working. xfreerdp crashes with a "segmentation fault" when using the option "/multimedia:codec:ffmpeg":

`gdb /usr/local/freerdp/bin/xfreerdp`
`(gdb) run run /u:myusername /v:mybox /cert-ignore /multimedia:codec:ffmpeg`
`[Thread debugging using libthread_db enabled]`
`Using host libthread_db library "/lib64/libthread_db.so.1".`
`[New Thread 0x7fffe83c2700 (LWP 23193)]`
`[13:51:17:080] [23189:23193] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr`
`[13:51:17:080] [23189:23193] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd`
`[13:51:17:080] [23189:23193] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc`
`Password:`
`[New Thread 0x7fffe7bc1700 (LWP 23195)]`
`[New Thread 0x7fffe73c0700 (LWP 23196)]`
`[13:51:20:995] [23189:23193] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel tsmf`
`[13:51:20:995] [23189:23193] [ERROR][com.freerdp.channels.drdynvc.client] -` `drdynvc_virtual_channel_event_connected failed with error 13`

`Program received signal SIGSEGV, Segmentation fault.`

RDP server
- Windows 10 Pro

FreeRPD client
- FreeRDP version 2.0.0-dev (git ca2d015) (GIT master branch from 2016-04-20)
- FFmpeg 3.0.1
- compiled with:
  `mkdir build && cd build;`
  `cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/freerdp -DWITH_CUPS:BOOL:BOOLE=ON -DWITH_PULSE:BOOL:BOOLE=ON  -DWITH_X11:BOOL:BOOLE=ON  -DWITH_XCURSOR:BOOL:BOOLE=ON -DWITH_XEXT:BOOL:BOOLE=ON -DWITH_DIRECTFB:BOOL=OFF -DWITH_FFMPEG:BOOL:BOOLE=ON -DWITH_SSE2:BOOL:BOOLE=ON -DWITH_JPEG:BOOLE=ON  -DWITH_X264:BOOLE=ON -DWITH_OPENH264:BOOLE=ON -DWITH_GSM:BOOLE=ON -DWITH_IPP=OFF -DWITH_PCSC:BOOLE=ON ..`

**Comment by akallabeth** [comment]
@bjoernv TSMF with FFMPEG did not see much attention lately, either use gstreamer or ditch multimedia redirection entirely and use /gfx (or /gfx-h264 if you compiled against openh264)

**Comment by hardening** [comment]
@bjoernv if you ran it in gdb, it would have been nice to give us the stack trace (something like bt show all) :)

**Comment by bjoernv** [comment]
Here is the stack trace:
[ffmpeg-codec-crash.txt](https://github.com/FreeRDP/FreeRDP/files/235464/ffmpeg-codec-crash.txt)

**Comment by bjoernv** [comment]
The /gfx-h264 option seems to work. The image quality of a test video (1024x576, 2207 kBit/s, 25 fps) is relatively poor, but works. Is it possible to log encoding / decoding details?

**Comment by akallabeth** [comment]
@bjoernv you can play with the /log-level and /log-filters parameters for advanced log output. as for /gfx-h264, windows 10 defaults to a new mode currently less optimized, you can force the old one with /gfx-h264:avc420 (if I remember correctly)

**Comment by akallabeth** [comment]
@bjoernv Oh, and the X264 cmake flag is useless right now, you have to compile against OpenH264.

**Comment by hardening** [comment]
I guess that accessing a null ListDictionnary easily explains the segfault ;)

**Comment by hardening** [comment]
Am I the only one to think that #3305 does not fix the real problem, as it's quite strange to call ListDictionary_GetItemValue on a NULL ListDictionnary, so adding checks in listdictionnary only hides the real problem...

**Comment by bmiklautz** [comment]
@hardening yes sure it "hides" the problem. But checking if the ListDictionnary is NULL is a good check nevertheless.
