### ISSUE TITLE
Num lock weirdness with remoteapp

### ISSUE THREAD

**Issue by jacob019** [FreeRDP/FreeRDP#330]
I'm experiencing some weird num lock behavior with remoteapp.

When connecting to the remote app, it behaves as if num lock is off at the time of connection.  If I connect with num lock off, then it behaves as expected. But if I connect with num lock on, then I get inverse behavior between my local desktop and the remote app--in the remote app numpad keys act like arrows with numlock on and numbers with num lock off.  Also caps lock has no effect on remote apps.  Regular sessions work fine.

I am using windows server 2008.  Can anyone reproduce?

**Comment by hardening** [comment]
no feedback, closing
