### ISSUE TITLE
RD Gateway / Session Host Issue (Server 2012 / Thin Clients)

### ISSUE THREAD

**Issue by Boseley01** [FreeRDP/FreeRDP#3301]
Hi,
Hopefully someone can help. We are using Fujitsu Futro S520 thin clients to connect to a 2012 RD Farm.

We are using FreeRDP on them to connect from the internal network, and this works fine. 

We have a 2012 RDCB server and 5 Session Hosts and are using a session collection called "Full Desktop".

The command internally that works is as follows:
FreeRdpParams= /cert-ignore /v:rdp.ourdomain.com /load-balance-info:"tsv://MS Terminal Services Plugin.1.Full_Desktop.NBI"

Externally, we can RDP from a windows machine straight to the farm with no issues at all, however from an external thin client it fails.

I've tried many different switches and just cannot get it to work using the gateway. From what I can tell it is authenticating with the gateway but then doing nothing, please could anyone shed some light on this.

(Externally we are using port 443, 3389 is closed which works fine from windows).

Command used on external thin client:
xfreerdp /u:myaccount /p:mypassword /d:clientdomain /v:rdp.ourdomain.com /g:rdp.ourdomain.com /cert-ignore /load-balance-info:"tsv://MS Terminal Services Plugin.1.Full_Desktop.NBI".

The output I see from the command line is:
Connected to rdp.ourdomain.com:443
Connected to rdp.ourdomain.com:443
TS Gateway Connection Success
Got stub length 4 with flags 3 and callid 7.
Got stub length 4 with flags 3 and callid 6.

This sits here for a while and then adds this line on the end:
rpc_client_frag_read: error reading heading

Any help would be greatly appreciated, thank you.

**Comment by hardening** [comment]
Which version of freerdp are you using ?

**Comment by Boseley01** [comment]
Hi,
The version listed is: 1.1.0-beta1 (git 1.1.0-beta+2013071101-236-ge840).

This is the package that comes with the elux thin clients, thanks.

Kind Regards,
Christopher Boseley

**Comment by hardening** [comment]
That was I was afraid of. So you should contact elux to get some support from them (as they don't ship their sources, we don't know which changes they have made to FreeRDP). Another solution would be to compile yourself xfreerdp for your thinclient.

Anyway 1.1 is quite old and we have done some improvements with connecting through TS gateway since.

**Comment by Boseley01** [comment]
Ok well that's useful to know. I was trying to test it on my windows PC
using freerdp for windows but struggled to get it to display on the remote
screen. I did also try afreerdp on my android but it had the same response
and did not connect.

I've raised a support request with Elux, sadly they are quite slow to
respond. I appreciate the response though.

Kind Regards,
Christopher Boseley

**Comment by Boseley01** [comment]
are you able to advise of the latest version of free rdp? I can see support
with elux for V1.1.0.2-6.

I would have to change a lot but I may be able to upgrade to that if it
would help.

Kind Regards
Chris Boseley

**Comment by akallabeth** [comment]
Closing as not freerdp specific.
