### ISSUE TITLE
Files copying issue

### ISSUE THREAD

**Issue by mikhaXD** [FreeRDP/FreeRDP#3302]
If copy file from PC to a RDP = its works fine. But when from RDP to PC - file is copied but size is 0bytes. No data inside. 
Im using latest windows nightly build

**Comment by bmiklautz** [comment]
Please have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting and add more information.

**Comment by akallabeth** [comment]
Closing due to lack of feedback.

**Comment by ilammy** [comment]
That's actually a feature request: #3532

**Comment by akallabeth** [comment]
@ilammy Ah, ok :) Sorry, did update a lot of issues and misread that one. But since there is already a more precisely formulated issue let's keep this one closed.
