### ISSUE TITLE
Using the /multimon switch, /h is not honored

### ISSUE THREAD

**Issue by GreyGnome** [FreeRDP/FreeRDP#3304]
I have a Fedora 22 laptop and run xfreerdp 1.2.0-beta1. My screen resolution is 1600x900.

When I connect a second monitor (resolution 1600x1200) and then use xfreerdp to connect to my remote machine like this:

xfreerdp /u:loginid /multimon /w:3200 /h:900

the window came in fullscreen, at 1200 pixels high, so that I could not open my Windows menu in my laptop screen. 

I haven't been able to find hotkeys for xfreerdp, so this required me to do a hard reset of my laptop... nothing would get me back to my local environment.

**Comment by akallabeth** [comment]
@GreyGnome Try <ctrl>+<alt>+<enter>

**Comment by GreyGnome** [comment]
The ctrl-alt-enter didn't work. Nothing happened.

Does /multimon imply full screen, so that the /h is not honored?

**Comment by akallabeth** [comment]
@GreyGnome Ok, had to dig this up myself, but /multimon indeed implies fullscreen.

**Comment by GreyGnome** [comment]
Thanks.

**Comment by akallabeth** [comment]
@GreyGnome Well, that will be the case if you leave out /multimon ;) Then you only get a window with the appropriate size. Multimon allows you to use multiple screens for a RDP session (so that the server knows there are multiple screens and can adjust its behaviour accordingly)

**Comment by GreyGnome** [comment]
I understand. But with two screens of different sizes, which one is appropriate...?

**Comment by akallabeth** [comment]
@GreyGnome Sorry, forgot about this thread, mea culpa. If you have two screens you can just use ```/multimon``` without additional arguments and the local multimonitor setup will be reflected. (even different resolutions)
