### ISSUE TITLE
FreeRDP make failed

### ISSUE THREAD

**Issue by daiqifan** [FreeRDP/FreeRDP#3306]
I complied FreeRdp with cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_FFMPEG=ON .

Then an error came out when i did make:
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libavcodec.a(allcodecs.o): relocation R_X86_64_32 against `ff_a64multi_encoder' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libavcodec.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[2]: **\* [client/common/libfreerdp-client.so.2.0.0] Error 1
make[1]: **\* [client/common/CMakeFiles/freerdp-client.dir/all] Error 2

I had installed ffmpeg-3.0.1 and modified the config.mak file with -fPIC option.
My linux version is CentOS 6.5 (64 bit) and specific information as below:
Linux version 2.6.32-573.22.1.el6.x86_64 (mockbuild@c6b8.bsys.dev.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) )

Why it still thrown the same error?   Would someone help me,please?

**Comment by akallabeth** [comment]
@daiqifan Hmm, looks like you're trying to link against a static build of FFMPEG?

**Comment by daiqifan** [comment]
@akallabeth So what can i do to solve this problem?  That i have configured FFMPEG with --enable-pic.

**Comment by akallabeth** [comment]
@daiqifan Good question, never tried to link statically. You can of course always try to compile FFMPEG dynamically and link to the so.

**Comment by bmiklautz** [comment]
@daiqifan your self compiled lib was installed in /usr/lib? So the one found by cmake is the correct one?

**Comment by akallabeth** [comment]
Closing due to lack of feedback. No crash with current nighlies experienced.
