### ISSUE TITLE
Crashing of the static build of wfreerdp

### ISSUE THREAD

**Issue by zoccolo** [FreeRDP/FreeRDP#3307]
Hi all,

I make a static build of small project which use freerdp (for windows), OpenSSL also built statically (with /MTd flag). My project also use /MTd flag.

However, there are random memory freeing errors.

For example, in the function 

`void freerdp_client_common_free (freerdp * instance, rdpContext * context);`

In this place:

`pEntryPoints-> ClientFree (instance, context);`

I have errors like this (mostly - when memory freeing functions is calling) very frequently.

Is there a way to fix these errors? Thank you!

**Comment by bmiklautz** [comment]
@zoccolo what version of FreeRDP are you using? If you use your nightly binaries (also static) can you observe the same problems?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
