### ISSUE TITLE
OS X 10.11.4 rdesktop v1.8.3 WARNING: Not compiled with smartcard support

### ISSUE THREAD

**Issue by mindisfree** [FreeRDP/FreeRDP#3317]
I install rdesktop v 1.8.3 as it stated support for smart card and windows 2012 r2. I could have missed some thing. I just ran sudo port install rdesktop no error on install and no broken files.

rdesktop -x m -r scard IPHERE
WARNING: Not compiled with smartcard support
Autoselected keyboard map en-us
Failed to connect, CredSSP required by server.

**Comment by bmiklautz** [comment]
@mindisfree you are in the wrong issue tracker this is the FreeRDP project and **not** rdesktop
