### ISSUE TITLE
Missing libxfreerdp-client.so in nightly build Ubuntu Xenial repo?

### ISSUE THREAD

**Issue by hombibi** [FreeRDP/FreeRDP#3320]
A little while ago I had some issues with the default build for Ubuntu (Gnome, x64), hence I was suggested to move to the nightly builds.  That has been working very well but today I found I can not start an rdp session anymore.

The error message is "/opt/freerdp-nightly/bin/xfreerdp: error while loading shared libraries: libxfreerdp-client.so: cannot open shared object file: No such file or directory", and indeed there is no such file in the /opt/freerdp-nigthly/lib directory on my pc.

Since I last used the rdp client (a few days ago) I have upgraded Ubuntu to Ubuntu Gnome Xenial, and updated the repositories. freerdp-nightly has been updated, the installed version is now 2.0.0+0~20160504014838.255~1.gbpf82859

Anything I can do to help or solve the issue?

**Comment by docsmooth** [comment]
`$ ldd /opt/freerdp-nightly/bin/xfreerdp
        linux-vdso.so.1 =>  (0x00007ffd2ebd0000)
        libxfreerdp-client.so => not found
        libfreerdp-client.so.2 => /opt/freerdp-nightly/bin/../lib/libfreerdp-client.so.2 (0x00007f2dbbb38000)
        libwinpr.so.2 => /opt/freerdp-nightly/bin/../lib/libwinpr.so.2 (0x00007f2dbb84b000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2dbb482000)
        libfreerdp.so.2 => /opt/freerdp-nightly/bin/../lib/../lib/libfreerdp.so.2 (0x00007f2dbb140000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f2dbb120000)
        libcups.so.2 => /usr/lib/x86_64-linux-gnu/libcups.so.2 (0x00007f2dbaea0000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2dbac82000)
        libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f2dbaa6a000)
        libgsm.so.1 => /usr/lib/x86_64-linux-gnu/libgsm.so.1 (0x00007f2dba85c000)
        libavcodec-ffmpeg.so.56 => /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56 (0x00007f2db9431000)
        libavutil-ffmpeg.so.54 => /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54 (0x00007f2db91c2000)
        libgstreamer-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 (0x00007f2db8e98000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f2db8b86000)
        libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f2db8933000)
        libgstbase-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so.0 (0x00007f2db86cf000)
        libgstapp-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstapp-1.0.so.0 (0x00007f2db84c0000)
        libgstvideo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so.0 (0x00007f2db823b000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f2db7f01000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f2db7cee000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2db7ae6000)
        libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f2db77e6000)
        libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f2db7596000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f2db732d000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f2db6ed1000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2db6bc8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2db69c4000)
        /lib64/ld-linux-x86-64.so.2 (0x000055dc00da3000)
        libxkbfile.so.1 => /usr/lib/x86_64-linux-gnu/libxkbfile.so.1 (0x00007f2db679d000)
        libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f2db6544000)
        libgssapi_krb5.so.2 => /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f2db62f9000)
        libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f2db5fc8000)
        libavahi-common.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-common.so.3 (0x00007f2db5dbc000)
        libavahi-client.so.3 => /usr/lib/x86_64-linux-gnu/libavahi-client.so.3 (0x00007f2db5baa000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2db5990000)
        libswresample-ffmpeg.so.1 => /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1 (0x00007f2db5773000)
        libva.so.1 => /usr/lib/x86_64-linux-gnu/libva.so.1 (0x00007f2db5557000)
        libzvbi.so.0 => /usr/lib/x86_64-linux-gnu/libzvbi.so.0 (0x00007f2db52cc000)
        libxvidcore.so.4 => /usr/lib/x86_64-linux-gnu/libxvidcore.so.4 (0x00007f2db4fb8000)
        libx265.so.79 => /usr/lib/x86_64-linux-gnu/libx265.so.79 (0x00007f2db4398000)
        libx264.so.148 => /usr/lib/x86_64-linux-gnu/libx264.so.148 (0x00007f2db3ff4000)
        libwebp.so.5 => /usr/lib/x86_64-linux-gnu/libwebp.so.5 (0x00007f2db3d98000)                                                          [7/274]
        libwavpack.so.1 => /usr/lib/x86_64-linux-gnu/libwavpack.so.1 (0x00007f2db3b6e000)
        libvpx.so.3 => /usr/lib/x86_64-linux-gnu/libvpx.so.3 (0x00007f2db374a000)
        libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f2db34a1000)
        libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f2db3274000)
        libtwolame.so.0 => /usr/lib/x86_64-linux-gnu/libtwolame.so.0 (0x00007f2db3051000)
        libtheoraenc.so.1 => /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1 (0x00007f2db2e12000)
        libtheoradec.so.1 => /usr/lib/x86_64-linux-gnu/libtheoradec.so.1 (0x00007f2db2bf7000)
        libspeex.so.1 => /usr/lib/x86_64-linux-gnu/libspeex.so.1 (0x00007f2db29de000)
        libsnappy.so.1 => /usr/lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f2db27d6000)
        libshine.so.3 => /usr/lib/x86_64-linux-gnu/libshine.so.3 (0x00007f2db25c8000)
        libschroedinger-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0 (0x00007f2db22f3000)
        libopus.so.0 => /usr/lib/x86_64-linux-gnu/libopus.so.0 (0x00007f2db20a9000)
        libopenjpeg.so.5 => /usr/lib/x86_64-linux-gnu/libopenjpeg.so.5 (0x00007f2db1e85000)
        libmp3lame.so.0 => /usr/lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f2db1c10000)
        libcrystalhd.so.3 => /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3 (0x00007f2db19f5000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f2db17d2000)
        libgmodule-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0 (0x00007f2db15ce000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f2db135d000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f2db1155000)
        liborc-0.4.so.0 => /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0 (0x00007f2db0ed4000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f2db0cb2000)
        libjson-c.so.2 => /lib/x86_64-linux-gnu/libjson-c.so.2 (0x00007f2db0aa7000)
        libpulsecommon-8.0.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so (0x00007f2db082c000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f2db05e0000)
        libkrb5.so.3 => /usr/lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f2db030d000)
        libk5crypto.so.3 => /usr/lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f2db00de000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f2dafeda000)
        libkrb5support.so.0 => /usr/lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f2dafcce000)
        libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f2dafa69000)
        libidn.so.11 => /usr/lib/x86_64-linux-gnu/libidn.so.11 (0x00007f2daf836000)
        libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f2daf622000)
        libnettle.so.6 => /usr/lib/x86_64-linux-gnu/libnettle.so.6 (0x00007f2daf3ec000)
        libhogweed.so.4 => /usr/lib/x86_64-linux-gnu/libhogweed.so.4 (0x00007f2daf1b9000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f2daef38000)
        libsoxr.so.0 => /usr/lib/x86_64-linux-gnu/libsoxr.so.0 (0x00007f2daecd3000)
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f2daeaad000)
        libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f2dae8a2000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2dae520000)
        libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f2dae316000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2dae100000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f2dadefb000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f2dadcf5000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f2dadc70000)
        libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007f2dada65000)
        libsndfile.so.1 => /usr/lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007f2dad7fc000)
        libasyncns.so.0 => /usr/lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007f2dad5f6000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f2dad3f1000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f2dad1d6000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f2dacfb3000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f2dacd91000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f2dacaaf000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f2dac896000)
        libFLAC.so.8 => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007f2dac621000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f2dac40c000)
$ sudo updatedb && locate libxfreerdp-client
/var/lib/dpkg/info/libxfreerdp-client1.1:amd64.list
/var/lib/dpkg/info/libxfreerdp-client1.1:amd64.postrm
$ sudo apt-cache search libxfreerdp
libxfreerdp-client-dbg - RDP client for Windows Terminal Services (xfreerdp-client debug symbols)
libxfreerdp-client1.1 - Free Remote Desktop Protocol library (xfreerdp-client library)
$ sudo apt-cache show libxfreerdp-client1.1
Package: libxfreerdp-client1.1
Priority: optional
Section: libs
Installed-Size: 844
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Mike Gabriel <sunweaver@debian.org>
Architecture: amd64
Source: freerdp
Version: 1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1
Replaces: libfreerdp1 (<< 1.1.0~git20140921.1.440916e+dfsg-1)
Depends: libc6 (>= 2.15), libfreerdp-cache1.1 (>= 1.1.0~beta1+git20130629), libfreerdp-client1.1 (>= 1.1.0~beta1+git20130629), libfreerdp-codec1.1 (>= 1.1.0~beta1+git20130629), libfreerdp-core1.1 (>= 1.1.0~git20140808.1.7b5cd86), libfreerdp-gdi1.1 (>= 1.1.0~beta1+git20130629), libfreerdp-locale1.1 (>= 1.1.0~beta1+git20130629), libfreerdp-rail1.1 (>= 1.1.0~beta1+git20130629), libfreerdp-utils1.1 (>= 1.1.0~beta1+git20130629), libwinpr-crt0.1 (>= 1.1.0~beta1+git20130629), libwinpr-handle0.1 (>= 1.1.0~beta1+git20130629), libwinpr-synch0.1 (>= 1.1.0~beta1+git20130629), libwinpr-thread0.1 (>= 1.1.0~beta1+git20130629), libwinpr-utils0.1 (>= 1.1.0~beta1+git20130629), libx11-6 (>= 2:1.2.99.901), libxcursor1 (>> 1.1.2), libxext6, libxi6 (>= 2:1.2.99.4), libxinerama1, libxrender1, libxv1
Suggests: freerdp-x11
Breaks: libfreerdp1 (<< 1.1.0~git20140921.1.440916e+dfsg-1)
Filename: pool/main/f/freerdp/libxfreerdp-client1.1_1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1_amd64.deb
Size: 58180
MD5sum: 91b448f089687029230f7aea1dc7c636
SHA1: d2e99f201c49c799cd740d80aecd2214f30bfaca
SHA256: 106f438fb0f6bd841b25a16b6b70e7606a323b4574f89d04e206cf1e13fa1297
Description-en: Free Remote Desktop Protocol library (xfreerdp-client library)
 FreeRDP is a libre client/server implementation of the Remote
 Desktop Protocol (RDP).
 .
 This package contains the xfreerdp-client shared library.
Description-md5: 3c5507a9aa5676ba1681887fc0041707
Multi-Arch: same
Homepage: http://www.freerdp.com/
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu
Supported: 3y
Task: kubuntu-desktop, kubuntu-full
`
so that one's wrong.

**Comment by bmiklautz** [comment]
@docsmooth thanks for your analysis but the "regular" packages don't have anything todo with the nightly packages. In fact they are not compatible that's why the nightly packages are installed into /opt.
@hombibi thank you for the report. I'll have a look.

**Comment by bmiklautz** [comment]
@hombibi once #3321 is merged and the nightly built is run the problem should be solved.

**Comment by bmiklautz** [comment]
Until the package is re-build just install freerdp-nightly-dev as work around for now. This should fix the issue.

**Comment by hombibi** [comment]
@bmiklautz As work around I switched back to the package from the original ubuntu repo. That will do for now, looking forward to the next nightly build. Thank you very much for looking into the issue.

**Comment by bmiklautz** [comment]
@hombibi @akallabeth merged the PR a minute ago and the nightly packages are building right now. Sorry for the delay.

**Comment by hombibi** [comment]
Installed the new nightly build an hour ago, it appears to work great again. Thanks very much. Closing the issue.
