### ISSUE TITLE
Does FreeRDP work with TLS 1.0 disabled?

### ISSUE THREAD

**Issue by sergsalo** [FreeRDP/FreeRDP#3322]
When I disable TLS 1.0 on my windows server 2012 R2, and enable NLA - I can't connect to that machine anymore. When TLS 1.0 is enabled and NLA is enabled FreeRDP v 1.1 (latest stable) seems to be working fine, but latest from master isn't working. If I disable NLA - and connect via /sec:rdp - latest from master works.

Client: Windows Server 2012 R2
Target: Windows Server 2012 R2
/sec:nla

--Latest Stable 1.1
           NLA Enabled
           TLS 1.0 Disabled
           Result: does not work

--Latest Stable 1.1
           NLA Enabled
           TLS 1.0 Enabled
           Result: works

--Latest from master
           NLA Enabled
           TLS 1.0 Disabled
           Result: does not work

--Latest from master
           NLA Enabled
           TLS 1.0 Enabled
           Result: does not work

**Comment by sergsalo** [comment]
--Latest from master
NLA Disabled
TLS 1.0 Disabled (TLS 1.2 enabled)
Result: works

**Comment by byteboon** [comment]
Does it work if you try to connect using the machine's IP address instead of the hostname?

**Comment by sergsalo** [comment]
yes! works with IP. Is this a bug?

**Comment by byteboon** [comment]
I think so, but haven't filed it yet because I'm trying to see if I can figure out what's happening. The symptom for us is that it only happens when using hostname on a domain connected computer. Maybe I'll go ahead and file now so I can add more details.

**Comment by sergsalo** [comment]
yes, i have exactly the same symptoms - only for domain connected computers.

**Comment by byteboon** [comment]
I have submitted a new bug with the details I know so far. #3323

**Comment by sergsalo** [comment]
cool, thank you! so, according to your findings NTLM is used instead of Kerberos when IP address is used instead of hostname?

**Comment by byteboon** [comment]
Yes, I can see the negoToken starts with NTLMSSP when using IP (or non-domain).

I found this page with a pretty graphic of the DC's decision tree: https://sqlactions.com/2013/10/22/lets-drill-why-you-cannot-generate-sspi-context/

**Comment by sergsalo** [comment]
thank you! this http://www.darkoperator.com/blog/2012/3/17/configuring-network-level-authentication-for-rdp.html also helped me to grasp some of this NLA stuff.

**Comment by byteboon** [comment]
Just found this today... http://serverfault.com/questions/691247/how-do-i-disable-tls-1-0-without-breaking-rdp which links to a Sept 2015 patch from Microsoft for Win7 and 2008 for TLS >1.0 (https://support.microsoft.com/en-us/kb/3080079)

**Comment by byteboon** [comment]
@sergsalo does my patch on #3323 resolve this for you?

**Comment by sergsalo** [comment]
yes, it works!
