### ISSUE TITLE
NLA Connection fails when using hostname on domain connected machines

### ISSUE THREAD

**Issue by byteboon** [FreeRDP/FreeRDP#3323]
If you use a hostname to attempt to connect to a domain connected machine from a domain connected machine on the same domain, the connection is dropped. If you attempt the same connection using the IP address, it succeeds.

Here's what we know so far:
- using the hostname in this scenario (two domain connected machines) causes SPNEGO to use Kerberos because the SPN is known to the domain controller (verified by no NTLMSSP header in the outgoing negoToken)
- using the IP address generates a SPN unknown to the DC, so it follows the NTLM path instead and works fine
- FreeRDP 1.x series works fine because it was hardcoded to always use NTLM
- the connection is dropped when the public key is echoed back to the server (last stage of NLA_STATE_NEGO_TOKEN)
- on the server, we sometimes see a TermDD event 56 "The Terminal Server security layer detected an error in the protocol stream and has disconnected the client" with error 0x8009030F which seems to map to TLS1_ALERT_BAD_RECORD_MAC (https://msdn.microsoft.com/en-us/library/windows/desktop/dd721886(v=vs.85).aspx) 

stderr log shows:
[16:08:57:715] [8760:000003a4] [ERROR][com.freerdp.core.transport] - BIO_read returned an error: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error
[16:08:57:715] [8760:000003a4] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x2000D]

**Comment by byteboon** [comment]
In the server's RemoteDesktopServices-RdpCoreTS/Operational event log I see:
`The server security layer detected an error (0x80004005) in the protocol stream and the client (Client IP:10.200.1.15) has been disconnected.`

**Comment by byteboon** [comment]
I found the bug... will submit a patch soon.

**Comment by sergsalo** [comment]
that's great! we implemented workaround to resolve to IP, but it would be much better when we don't need to hack around it! thanks

**Comment by byteboon** [comment]
Fixed is now merged to master.

**Comment by bmiklautz** [comment]
@byteboon thank you.
