### ISSUE TITLE
Build FreeRDP-Android on Ubuntu 14.04 

### ISSUE THREAD

**Issue by BrianChangchien** [FreeRDP/FreeRDP#3324]
I want to build FreeRDP for android in Ubuntu14.04 64bit

my NDK : android-ndk-r11c and SDK : r24.4.1  

I reference https://www.youtube.com/watch?v=vGOcPH5UXJM  the video to construct the library

so i git clone https://github.com/bmiklautz/android-external-openssl-ndk-static to /home/user/WorkPrj/android-external-openssl-ndk-static 
  
and run ndk-build. then it generate libcrypto.a and libssl.o in /home/user/WorkPrj/android-external-openssl-ndk-static/obj/local/armeabi

and then git clone https://github.com/FreeRDP/FreeRDP to /home/user/WorkPrj/FreeRDP-master

and open terminal to local to /home/user/WorkPrj/FreeRDP-master, key in 

cmake -DCMAKE_TOOLCHAIN_FILE=cmake/AndroidToolchain.cmake -DANDROID_NDK="/home/user/NDK/android-ndk-r11c" 
-DFREERDP_ANDROID_EXTERNAL_SSL_PATH="/home/user/WorkPrj/android-external-openssl-ndk-static" -DCMAKE_BUILD_TYPE=Debug

but terminal show error message 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
 
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR 
(missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):

  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)

  cmake/FindOpenSSL.cmake:317 (find_package_handle_standard_args)
  
cmake/FindFeature.cmake:16 (find_package)
 
 CMakeLists.txt:674 (find_feature)

can you find out the issue to solve the problem

another , Does anyone have a process to construct freeRDP-android success to build aFreeRDP apk

**Comment by akallabeth** [comment]
@BrianChangchien Have a look at ```docs/README.android``` in the FreeRDP git repo. There are already convenience scripts to generate the Android Studio project and all required native libraries. You have been following an outdated howto.

**Comment by BrianChangchien** [comment]
Hi akallabeth

I have question about setting SCRIPT_PATH in android-build.conf problem

if my FreeRDP-master locate in /home/WorkPrj/FreeRDP-master/

how do i set realpath ?

SCRIPT_PATH=$(dirname "${BASH_SOURCE[0]}")

SCRIPT_PATH=$(realpath "$SCRIPT_PATH")




2016-05-10 17:01 GMT+08:00 akallabeth <notifications@github.com>:

**Comment by akallabeth** [comment]
@BrianChangchien Just leave it as it is ;) It will always point to the path of the file

**Comment by BrianChangchien** [comment]
So i don`t modify the file, is it right?
2016年5月10日 下午9:02於 "akallabeth" <notifications@github.com>寫道：

**Comment by BrianChangchien** [comment]
Hi akallabeh,

when i run ./scripts/android-build-freerdp.sh --ndk <ANDROID_NDK> --sdk
<ANDROID_SDK>
i can build openh264.so openssl.so libcrypto.so in jniLibs/armeabi
but when run Build and install the library , will show msgs

[RUN] cd /home/user/WorkPrj/FreeRDP-master
[RUN] mkdir -p ./scripts/../build/freerdp-build/armeabi
[RUN] cd ./scripts/../build/freerdp-build/armeabi
[RUN] export ANDROID_NDK=/home/user/NDK/android-ndk-r11c
[RUN] cmake -DANDROID_NDK=/home/user/NDK/android-ndk-r11c
-DANDROID_NATIVE_API_LEVEL=android-12
-DCMAKE_TOOLCHAIN_FILE=./scripts/../cmake/AndroidToolchain.cmake
-DCMAKE_INSTALL_PREFIX=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs
-DCMAKE_BUILD_TYPE=Debug
-DFREERDP_EXTERNAL_PATH=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs
-DWITH_OPENH264=ON -DANDROID_ABI=armeabi ./scripts/..
CMake Error: The source directory
"/home/user/WorkPrj/FreeRDP-master/build/freerdp-build/armeabi" does not
appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
[ERROR] cmake -DANDROID_NDK=/home/user/NDK/android-ndk-r11c
-DANDROID_NATIVE_API_LEVEL=android-12
-DCMAKE_TOOLCHAIN_FILE=./scripts/../cmake/AndroidToolchain.cmake
-DCMAKE_INSTALL_PREFIX=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs
-DCMAKE_BUILD_TYPE=Debug
-DFREERDP_EXTERNAL_PATH=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs
-DWITH_OPENH264=ON -DANDROID_ABI=armeabi ./scripts/.. retured 1

so i try FreeRDP-master.zip unzip to
"/home/user/WorkPrj/FreeRDP-master/build/freerdp-build/armeabi

and run again

will show below msg

[RUN] cd /home/user/WorkPrj/FreeRDP-master
[RUN] mkdir -p ./scripts/../build/freerdp-build/armeabi
[RUN] cd ./scripts/../build/freerdp-build/armeabi
[RUN] export ANDROID_NDK=/home/user/NDK/android-ndk-r11c
[RUN] cmake -DANDROID_NDK=/home/user/NDK/android-ndk-r11c
-DANDROID_NATIVE_API_LEVEL=android-12
-DCMAKE_TOOLCHAIN_FILE=./scripts/../cmake/AndroidToolchain.cmake
-DCMAKE_INSTALL_PREFIX=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs
-DCMAKE_BUILD_TYPE=Debug
-DFREERDP_EXTERNAL_PATH=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs
-DWITH_OPENH264=ON -DANDROID_ABI=armeabi ./scripts/..
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE)
-- FreeRDP GIT
-- Git Revision n/a
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Success
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Success
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Success
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Success
-- GCC default symbol visibility: hidden
-- Performing Test Wimplicit-function-declaration
-- Performing Test Wimplicit-function-declaration - Success
-- Performing Test Wredundant-decls
-- Performing Test Wredundant-decls - Success
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - not found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for pthread_mutex_timedlock in pthread
-- Looking for pthread_mutex_timedlock in pthread - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for eventfd_read
-- Looking for eventfd_read - found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - not found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for ceill
-- Looking for ceill - found
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB:
/home/user/NDK/android-ndk-r11c/platforms/android-12/arch-arm/usr/lib/libz.so
(found version "1.2.3")
-- Finding required feature OpenSSL for cryptography (encryption,
certificate validation, hashing functions)
CMake Error at
/usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108
(message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315
(_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpenSSL.cmake:317 (find_package_handle_standard_args)
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:674 (find_feature)

-- Configuring incomplete, errors occurred!
See also
"/home/user/WorkPrj/FreeRDP-master/build/freerdp-build/armeabi/CMakeFiles/CMakeOutput.log".
See also
"/home/user/WorkPrj/FreeRDP-master/build/freerdp-build/armeabi/CMakeFiles/CMakeError.log".
[ERROR] cmake -DANDROID_NDK=/home/user/NDK/android-ndk-r11c
-DANDROID_NATIVE_API_LEVEL=android-12
-DCMAKE_TOOLCHAIN_FILE=./scripts/../cmake/AndroidToolchain.cmake
-DCMAKE_INSTALL_PREFIX=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs
-DCMAKE_BUILD_TYPE=Debug
-DFREERDP_EXTERNAL_PATH=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs
-DWITH_OPENH264=ON -DANDROID_ABI=armeabi ./scripts/.. retured 1

could you help me point how to finish to build a success freerdp android
library , thank a lot


2016-05-10 21:24 GMT+08:00 Brian Chang-Chien <brian.changchien@gmail.com>:
