### ISSUE TITLE
Run android-build-freerdp.sh error on Ubuntu 14.04

### ISSUE THREAD

**Issue by BrianChangchien** [FreeRDP/FreeRDP#3326]
Hi, All
when i run ./scripts/android-build-freerdp.sh --ndk <ANDROID_NDK> --sdk <ANDROID_SDK> 
i can build openh264.so openssl.so libcrypto.so in jniLibs/armeabi
but when run Build and install the library , will show msgs

[RUN] cd /home/user/WorkPrj/FreeRDP-master
[RUN] mkdir -p ./scripts/../build/freerdp-build/armeabi
[RUN] cd ./scripts/../build/freerdp-build/armeabi
[RUN] export ANDROID_NDK=/home/user/NDK/android-ndk-r11c
[RUN] cmake -DANDROID_NDK=/home/user/NDK/android-ndk-r11c -DANDROID_NATIVE_API_LEVEL=android-12 -DCMAKE_TOOLCHAIN_FILE=./scripts/../cmake/AndroidToolchain.cmake -DCMAKE_INSTALL_PREFIX=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DWITH_OPENH264=ON -DANDROID_ABI=armeabi ./scripts/..
CMake Error: The source directory "/home/user/WorkPrj/FreeRDP-master/build/freerdp-build/armeabi" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
[ERROR] cmake -DANDROID_NDK=/home/user/NDK/android-ndk-r11c -DANDROID_NATIVE_API_LEVEL=android-12 -DCMAKE_TOOLCHAIN_FILE=./scripts/../cmake/AndroidToolchain.cmake -DCMAKE_INSTALL_PREFIX=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DWITH_OPENH264=ON -DANDROID_ABI=armeabi ./scripts/.. retured 1

so i try FreeRDP-master.zip unzip to "/home/user/WorkPrj/FreeRDP-master/build/freerdp-build/armeabi and run again , will show below msg

[RUN] cd /home/user/WorkPrj/FreeRDP-master
[RUN] mkdir -p ./scripts/../build/freerdp-build/armeabi
[RUN] cd ./scripts/../build/freerdp-build/armeabi
[RUN] export ANDROID_NDK=/home/user/NDK/android-ndk-r11c
[RUN] cmake -DANDROID_NDK=/home/user/NDK/android-ndk-r11c -DANDROID_NATIVE_API_LEVEL=android-12 -DCMAKE_TOOLCHAIN_FILE=./scripts/../cmake/AndroidToolchain.cmake -DCMAKE_INSTALL_PREFIX=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DWITH_OPENH264=ON -DANDROID_ABI=armeabi ./scripts/..
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Git Revision n/a
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Success
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Success
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Success
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Success
-- GCC default symbol visibility: hidden
-- Performing Test Wimplicit-function-declaration
-- Performing Test Wimplicit-function-declaration - Success
-- Performing Test Wredundant-decls
-- Performing Test Wredundant-decls - Success
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - not found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for pthread_mutex_timedlock in pthread
-- Looking for pthread_mutex_timedlock in pthread - not found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for eventfd_read
-- Looking for eventfd_read - found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - not found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for ceill
-- Looking for ceill - found
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /home/user/NDK/android-ndk-r11c/platforms/android-12/arch-arm/usr/lib/libz.so (found version "1.2.3") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpenSSL.cmake:317 (find_package_handle_standard_args)
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:674 (find_feature)

-- Configuring incomplete, errors occurred!
See also "/home/user/WorkPrj/FreeRDP-master/build/freerdp-build/armeabi/CMakeFiles/CMakeOutput.log".
See also "/home/user/WorkPrj/FreeRDP-master/build/freerdp-build/armeabi/CMakeFiles/CMakeError.log".
[ERROR] cmake -DANDROID_NDK=/home/user/NDK/android-ndk-r11c -DANDROID_NATIVE_API_LEVEL=android-12 -DCMAKE_TOOLCHAIN_FILE=./scripts/../cmake/AndroidToolchain.cmake -DCMAKE_INSTALL_PREFIX=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=./scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DWITH_OPENH264=ON -DANDROID_ABI=armeabi ./scripts/.. retured 1

could anyone help me point how to finish to build a success freerdp android library , thank a lot

**Comment by akallabeth** [comment]
@BrianChangchien Just tested on a fresh 14.04 installation:
* You need ```realpath```, ```cmake``` and ```git``` installed
* Just clone ```git clone https://github.com/freerdp/freerdp```
* Run ```./scripts/android-build-freerdp.sh --ndk <path to your NDK> --sdk <path to your SDK>```
* Continue with android studio

So best retry with a clean workspace.
If you still have issues, please use the FreeRDP IRC or mailing list for support, as this is obviously not a but.

**Comment by BrianChangchien** [comment]
Hello , akallabeth

Thanks your response
Could you show me how to set realpath, or how to edit a success cmd about
SCRIPT_PATH=$(realpath "$SCRIPT_PATH") plz.......



2016-05-11 16:00 GMT+08:00 akallabeth <notifications@github.com>:

**Comment by akallabeth** [comment]
```apt-get install realpath```

**Comment by BrianChangchien** [comment]
Yes,thx
2016年5月11日 下午8:57於 "akallabeth" <notifications@github.com>寫道：

**Comment by BrianChangchien** [comment]
Hi akallabeth

I can build aFreeRD.apk to install to android phone, thx your great help
but I meet connect failed issue now
I prepare a Win7 PC and open RDP protocal , the Win7 PC can remoted by
another PC
then I use aFreeRDP to  setConnectionInfo() and  connect
it will response event OnConnectionFailure(inst) ,How do i log what problem
to connectfailure , could you tell me how to find problem , thx your great
help !!


2016-05-11 22:20 GMT+08:00 Brian Chang-Chien <brian.changchien@gmail.com>:

**Comment by xiamianyu** [comment]
@BrianChangchien 
i have the same issue with you, however, i apt-install realpath successfully and clone FreeRDP, run script `./scripts/android-build-freerdp.sh --ndk <ANDROID_NDK> --sdk <ANDROID_SDK>` ，this issue still happens.

**my develop environment configuration**
```txt
OS: Ubuntu 14.04 
Git version: 1.9.1
JDK version: 1.8.0_111
cmake version: 2.8.12.2
```

**the following is the error log**
```txt
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Git Revision 2a6dbab
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Failed
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Failed
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Failed
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Failed
-- GCC default symbol visibility: hidden
-- Performing Test Wimplicit-function-declaration
-- Performing Test Wimplicit-function-declaration - Failed
-- Performing Test Wredundant-decls
-- Performing Test Wredundant-decls - Failed
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - not found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - not found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - not found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - not found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - not found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - not found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Failed
-- Looking for include file pthread.h
-- Looking for include file pthread.h - not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindThreads.cmake:166 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:533 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/parallels/Android/workspace/FreeRDP/build/freerdp-build/armeabi/CMakeFiles/CMakeOutput.log".
See also "/home/parallels/Android/workspace/FreeRDP/build/freerdp-build/armeabi/CMakeFiles/CMakeError.log".
[ERROR] cmake -DANDROID_NDK=/home/parallels/Android/android-ndk-r13 -DANDROID_NATIVE_API_LEVEL=android-21 -DCMAKE_TOOLCHAIN_FILE=/home/parallels/Android/workspace/FreeRDP/scripts/../cmake/AndroidToolchain.cmake -DCMAKE_INSTALL_PREFIX=/home/parallels/Android/workspace/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=/home/parallels/Android/workspace/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DANDROID_ABI=armeabi -DCMAKE_INSTALL_PREFIX=/home/parallels/Android/workspace/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_INSTALL_LIBDIR=armeabi /home/parallels/Android/workspace/FreeRDP/scripts/.. retured 1
```

could you tell me what reason is?

**Comment by codaris** [comment]
I'm also having this problem on Ubuntu:

-- Looking for include file pthread.h
-- Looking for include file pthread.h - not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Threads (missing: Threads_FOUND)

Can't seem to figure out what the problem is.

**Comment by codaris** [comment]
I get a similar error on  Ubuntu and I'm not able to build:

-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Git Revision 05f6dac
-- GCC default symbol visibility: hidden
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.2/Modules/FindThreads.cmake:204 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:540 (find_package)
