### ISSUE TITLE
Possibility of embedding FreeRDP clients in custom application?

### ISSUE THREAD

**Issue by DatBewar** [FreeRDP/FreeRDP#3327]
Hi, i'm currently on the implementation of FreeRDP within a [Sip VoIP software](https://github.com/BelledonneCommunications/linphone-desktop/tree/dev_screensharing).
I would like to know if you plan to ship FreeRDP clients(xfreerdp, wayland) so that one can use them from within his/her own application like the shadow server?

**Comment by bmiklautz** [comment]
@DatBewar I'm not exactly what you mean with ship like shadow server. Currently you can use the xfreerdp functionality quite simply by running cmake with -DWITH_CLIENT_INTERFACE=ON -DCLIENT_INTERFACE_SHARED=ON  all you then need to do is add some "glue" code like in client/X11/cli/xfreerdp.c.

**Comment by DatBewar** [comment]
@bmiklautz I install FreeRDP library in a custom prefix first and then build my software, searching FreeRDP as a system dependency from that prefix.
But even with `-DWITH_CLIENT_INTERFACE=ON -DCLIENT_INTERFACE_SHARED=ON`, it seems that FreeRDP clients do not install their header files. For instance I believe that xFreeRDP should install `xf_client.h` but that's not the case.
Am I doing it wrong or clients cannot be used as system depencies yet?

**Comment by byteboon** [comment]
The source code for the clients (the code in the clients directory) is intended to create stand alone executables. These source files are not part of libfreerdp, but are consumers of it that may be used as examples for how you can create your own clients or embed a client within your own application. You will need to make extensive modifications to the client code to embed them in another application.

**Comment by DatBewar** [comment]
Thanks for the confirmation, i will do like that.

**Comment by bmiklautz** [comment]
@byteboon what you say is not entirely true. It is in fact possible to use (when built with the above's cmake defines)  libxfreerdp-client by using the RdpClientEntry entry point. That's why I referred to client/X11/cli/xfreerdp.c because it's basiaclly the same what the cli does.

**Comment by byteboon** [comment]
Ah thanks, @bmiklautz ... I learned something new 👍
