### ISSUE TITLE
Session problem since commit a0630de

### ISSUE THREAD

**Issue by vp1981** [FreeRDP/FreeRDP#3334]
Hello,
I see some strange problem: previously (yesterday) I was using freerdp compiled from commit f828595 and it worked fine, today I have built freerdp from commit 967c53c and remmina segfaults when I'm scrolling a web page in Firefox on Windows box (Windows 2012 r2 server).

I compiled freerdp with `CMAKE_BUILD_TYPE=Debug` and ran `xfreerdp` in `gdb`, opened a web page and `xfreerdp` window was frozen, though `xfreerdp` was still running and loading at maximum a core. I didn't get any output in `gdb` so after `^C` and `bt` I saw that it stuck on `poll` called by `WaitOnFd`.

Running `xfreerdp` built without `Debug` in `gdb` I see segfault on `freerdp_check_fd` in `libfreerdp.so` in the middle of stack, other symbols are '??'.

So I tried to use `xfreerdp` compiled with reverted commit a0630de and it works fine.

**Comment by hardening** [comment]
@vp1981 interesting, would you mind running in valgrind so that we have a more precise idea of what's going on ? (BTW it's rather strange that gdb doesn't resolve symbols)

**Comment by hardening** [comment]
@awakecoding I think https://github.com/FreeRDP/FreeRDP/commit/a0630dee07ecf3f84686eb5f77b126fd45f9f457 is yours isn't it ?

**Comment by vp1981** [comment]
@hardening thank for suggestion to run under `valgrind`, I forgot to do so.

I was eager and ran `xfreerdp` with six different parameters (as `valgrind` suggested):
1. without any parameters https://gist.github.com/vp1981/c2cf8e7995645f222914bf8d7c112bb8 ;
2. with `--track-origins=yes` https://gist.github.com/vp1981/af0df267d77a8e19575bb7f33c62eae4 ;
3. `2.` + `--leak-check=full` https://gist.github.com/vp1981/3359c61a2ef75f8e1a0541b9e11dfe0a ;
4. `3.` + `--show-leak-kinds=all` https://gist.github.com/vp1981/4f292b2337f11659be5d6529d87de408 ;
5. `4.` + `-v` https://gist.github.com/vp1981/ff49a9b2dfdf7a289d85753048c2c246 ;
6. `5.` + `--error-limit=no` https://gist.github.com/vp1981/7675e3d2f40c0ee5d3b3f4cc03b68b66 .

Also I ran `xfreerdp` in `gdb` as previously and this time it is segfaulted, so now I have "clean" gdb output, https://gist.github.com/vp1981/e3414a54f43061bbe947fbd46dd186a3 .

As for you wonder why gdb didn't show any symbols, it was my fault: I compiled 'freerdp' with `CMAKE_BUILD_TYPE=Debug` but package build tool of my distribution (makepkg and Archlinux) stripped debug symbols. After I changed that and now the 'freerdp' has all necessary symbols.

**Comment by hardening** [comment]
@vp1981 Sorry I forgot to tell to compile with valgrind helpers option, or the valgrind traces are unusable.

**Comment by awakecoding** [comment]
@hardening yes it is mine, but I fail to see what could cause such issues. It is a relatively simple commit, the main difference being that we now correctly reset the context on PACKET_FLUSHED. Maybe there is something wrong with the context flushing itself.

**Comment by vp1981** [comment]
@hardening , okey, next round. Now I compiled freerdp with following additional options:
```
-DCMAKE_BUILD_TYPE=Debug    \
-DWITH_VALGRIND_MEMCHECK=ON \
-DWITH_DEBUG_ALL=ON
```
Now I have run `xfreerdp` on other host but still it segfaults. These are results:
1. running bare `xfreerdp` in terminal, output: https://gist.github.com/vp1981/1517d1f166808d2855bc26a6808d728b ;
2. running `xfreerdp` in `gdb`:
  https://gist.github.com/vp1981/f0d55f17d5a26605d53cd8ae8cfc1b75 ;
3. (the following corresponds to items 1.—6. above):
https://gist.github.com/vp1981/5d51a8a1d5b513faf26bed42c4aeddb2
4.
https://gist.github.com/vp1981/8b1700509328eaab7e3e7f40d6510f3a
5.
https://gist.github.com/vp1981/6f4fd939a32420a52734c078749737c5
6.
https://gist.github.com/vp1981/3d66b2fc3b16245cc2716d03fafe7add
7.
https://gist.github.com/vp1981/6f65859a4fedc662db6504bbaa725e6c
8.
https://gist.github.com/vp1981/53c3c0aee462375dc31dce85643ace6c

The only difference is that now `xfreerdp` when run under `valgrind` don't open a windows.

Tomorrow (is about 12-14 hours from now) I'll compile and run `xfreerdp` on the first host.

Hope this will help.

**Comment by awakecoding** [comment]
@vp1981 I have a temporary fix here: https://github.com/FreeRDP/FreeRDP/pull/3339

**Comment by vp1981** [comment]
@awakecoding , yes, that "fix" fixes the problem.

**Comment by vp1981** [comment]
I confirm that freerdp after commit a75d89d works as usually fine.
