### ISSUE TITLE
freerdp Windows Server 2008 R2 - Excel - infinite scroll --> session unusable

### ISSUE THREAD

**Issue by ropetry** [FreeRDP/FreeRDP#3338]
Hello we are facing some performance issues with freerdp. i can reproduce the behavior verry easy, perhaps you to.it was already there with 1.1 and 2.0 has it also.
i use a thinclient with Atom D525 @1,80GHz,m 4 GB Ram: Resolution 1680x1050 or 1920x1200.
Connect in fullscreen mode to a server 2008 r2. start excel.
How to reproduce:
if i have several rows on the screen with some entrys in every column i can select several complete rows, and if i still hold down the button it will select more rows and mark them blue. if i move the mouse up and down it selects and deselects rows and marks them blue.if i reach the screen end, excel scrolls down the rows. if i do this if happens verrry often that excel scrolls down infinite. session hangs . can´t press anything but the screen gets refreshed. i see new rows appearing but it scrolls down infinite.
After some time i reached row 32000 and after soem more thime the connection get closed.

even if i unplug the lan cable he still scrolls down for several minutes..  screen updates are cached i think.

anyone has seen this behavior or can reproduce it ?
looks like this bug: #2193 could be the same ?

thanks roman

**Comment by akallabeth** [comment]
yes, yours is a duplicate. closing for that reason.

**Comment by ropetry** [comment]
@akallabeth : no problem, but all workarounds listed so far are not working.  (+async-update )and this is an issue for 2.x version. is there a way we can work on it.
thanks 
roman

**Comment by hardening** [comment]
As noted in #2193 I did an experiment in https://github.com/hardening/FreeRDP/tree/limit_frames Does it improve things for you ?

**Comment by ropetry** [comment]
@hardening : yes.. big difference on my thinclients 8-).. Thanks..
Just to crosslink for others.. this is the pull request to fix this so far.. 
#3364
