### ISSUE TITLE
video not clear with openh264

### ISSUE THREAD

**Issue by jinlong0813** [FreeRDP/FreeRDP#3342]
Dear Developers,
I use openh264 to login windows 10. When I play high-definition video, the picture is very fuzzy. It's not as clear as it should be. Are there any settings on client or on server side can make it more clear?
![img_20160513_105524](https://cloud.githubusercontent.com/assets/16506647/15236834/3cc02a8c-18fb-11e6-833d-fe75bafd276a.jpg)

**Comment by akallabeth** [comment]
@jinlong0813 the video quality highly depends on processing latency.  windows 10 also introduces a new video mode (AVC444) which is currently less optimised. you can switch between the two modes with /gfx-h264:avc420 and /gfx-h264:avc444 (check the command line help, pulled this from memory)

**Comment by akallabeth** [comment]
AVC444 mode is now implemented.
