### ISSUE TITLE
rdp_read_bitmap_cache_v2_capability_set  getting failed

### ISSUE THREAD

**Issue by shekhu025** [FreeRDP/FreeRDP#3343]
I am using lync client 2010 with RDP to share content. When lync client try to share content it set some capabilities according to client . At that time , rdp_read_bitmap_cache_v2_capability_set capability is getting failed because it expect length 40 but it receive the length 28. Due to length mismatch it getting failed.
This capabilities are present in /libfreerdp/core/capabilities.c
My query is:
1) What should be the length received for this capability set?
2) Is it necessary to received length is always 40?
3) why the length recieved is 28 in case of lync 2010?

**Comment by akallabeth** [comment]
See `[MS-RDPBCGR]`
