### ISSUE TITLE
wlfreerdp does not have a man page

### ISSUE THREAD

**Issue by sunweaver** [FreeRDP/FreeRDP#3345]
The Wayland FreeRDP client is probably very identical to the X11 FreeRDP client regarding information provided on their man pages.

Currently, the Wayland FreeRDP client does not have a man page. My recommendation is to ship one man page for both packages and symlink wlfreerdp -> xfreerdp. The man page would only need minor changes, e.g. in the NAME field, the SYNOPSIS field,  the DESCRIPTION field and maybe at a few other locations.

Those changes should mention both application names, e.g.:

```
SYNOPSIS
       xfreerdp [file] [options] [/v:server[:port]]
```

->

```
SYNOPSIS
       xfreerdp [file] [options] [/v:server[:port]]
       wlfreerdp [file] [options] [/v:server[:port]]
```

For Debian, the policy prescribes to ship man pages for every executable ending up in a package. At best, those man pages are provided by upstream.

**Comment by bmiklautz** [comment]
@sunweaver I'll initially add a small extra man page with basic information and a reference to the xfreerdp man page for the command line.

**Comment by sunweaver** [comment]
Hi Bernhard,

On  Mi 11 Jan 2017 10:34:55 CET, Bernhard Miklautz wrote:

> @sunweaver I'll initially add a small extra man page with basic  
> information and a reference to the xfreerdp man page for the command  
> line.

If the usage is very similar, simply add all info to the xfreerdp man  
page, ship it as freerdp.1, symlink xfreerdp.1 to it and wlfreerdp.1

See man page of grep, egrep, fgrep, etc. for example.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de

**Comment by bmiklautz** [comment]
@sunweaver the xfreerdp man page is automatically generated (generate_argument_docbook creates a docbook out of the cmd line information) and a part of the X11 client (also directory wise) at the moment. Until this is split out and/or we find a better solution having an extra small wlfreerdp.1 man that references xfreerdp is much simpler.

**Comment by sunweaver** [comment]
On  Mo 16 Jan 2017 09:34:59 CET, Bernhard Miklautz wrote:

> @sunweaver the xfreerdp man page is automatically generated  
> (generate_argument_docbook creates a docbook out of the cmd line  
> information) and a part of the X11 client (also directory wise) at  
> the moment. Until this is split out and/or we find a better solution  
> having an extra small wlfreerdp.1 man that references xfreerdp is  
> much simpler.

Ack.

Mike
-- 

DAS-NETZWERKTEAM
mike gabriel, herweg 7, 24357 fleckeby
mobile: +49 (1520) 1976 148
landline: +49 (4354) 8390 139

GnuPG Fingerprint: 9BFB AEE8 6C0A A5FF BF22  0782 9AF4 6B30 2577 1B31
mail: mike.gabriel@das-netzwerkteam.de, http://das-netzwerkteam.de
