### ISSUE TITLE
freerdp-shadow-cli does not have a man page

### ISSUE THREAD

**Issue by sunweaver** [FreeRDP/FreeRDP#3347]
The executable freerdp-shadow-cli does not have a man page. I'd highly welcome having one provided by upstream.

```
W: freerdp2-shadow-x11: binary-without-manpage usr/bin/freerdp-shadow-cli
```

Thanks!

**Comment by marcosps** [comment]
+1

**Comment by bmiklautz** [comment]
Already merged and on master.
