### ISSUE TITLE
feature request: hidpi client

### ISSUE THREAD

**Issue by awb99** [FreeRDP/FreeRDP#3351]
I am on a hidpi display (Lenovo Yoga 3)  and rdp into a win7 virtual machine. The windows are really small; it would be great feature to have a zoom in, so say you double all pixels, so that the 
remote screen is better readabe.

**Comment by Hobby-Student** [comment]
try "/f /smart-sizing:1920x1080" or another desired resolution...

**Comment by akallabeth** [comment]
There is the option @Hobby-Student mentioned or there are the `/scale*` options to enable high dpi features of the server.
