### ISSUE TITLE
unclosed file descriptors

### ISSUE THREAD

**Issue by m0ntana** [FreeRDP/FreeRDP#3355]
How to reproduce:
freerdp_new();
freerdp_context_new();
freerdp_client_load_addins();
freerdp_connect();
freerdp_disconnect();
freerdp_context_free();
freerdp_free();

No memory leaks but freerdp leaves opened file descriptors.
"too many opened files" error occurs if in loop.

**Comment by bmiklautz** [comment]
@m0ntana would you please add more information? https://github.com/FreeRDP/FreeRDP/wiki/BugReporting at least the version you are testing with is required.
Also can you give a running example?

**Comment by m0ntana** [comment]
Using freerdp as library for my own project
I have a loop
http://www.heypasteit.com/clip/2O22

Building my project on 
Linux m0ntana-lu 3.19.0-15-generic #15-Ubuntu SMP Thu Apr 16 23:32:01 UTC 2015 i686 i686 i686 GNU/Linux
DISTRIB_DESCRIPTION="Ubuntu 15.04"
and
Linux nothing 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

On every iteration of loop freerdp leaves unclosed fds. But I can't find what this fds about (maybe connection fd or communication to openssl). So I made workaround class that closes unused fd.

Cloned from git repo at this point:
commit ca2d015d7afab8af9523f0313b6846a3cd59f305
Merge: 8110435 8917a3d


PS:
When looping in this way it is very high CPU usage
 %CPU %MEM     TIME+
60,5  1,0 365:20.91

if i comment out freerdp_connect() from loop - no cpu usage at all. I think SSL uses CPU time on authentication.

**Comment by bmiklautz** [comment]
@m0ntana it seems like on each iteration two fds are leaked. As it seems they are eventfd related I'd guess some thread doesn't cleanup correctly.

When running in a loop having a high CPU load like that shouldn't surprise you. You doing a lot of initialization work each time, connect and disconnect without any break..

**Comment by m0ntana** [comment]
Yeah, a saw that is eventfd related. But I didn't find what does not close this fds inside freerdp lib

In my loop QThread::sleep() present. But it does not make sense. freerdp_connect() makes high CPU usage.
Maybe, is there any way to not initialize many things in freerdp_connect? So it just try to login and return immidiatly? instance->settings->AuthenticateOnly=true does not help.

**Comment by m0ntana** [comment]
By the way. The same code running windows 7 x64 does not have unclosed fds as I can see in task manager

**Comment by bmiklautz** [comment]
@m0ntana could you give my branch https://githhub.com/bmiklautz/FreeRDP/tree/eventfd_leak a try. The last commit on this branch ce2554310970e2a7896660987bdfaba2845ea556 fixed the behavior. It's not a clean fix yet but at least we know where the leak happens.

**Comment by m0ntana** [comment]
okay! I'll try it in an hour

**Comment by m0ntana** [comment]
Seems to be ok now.
Letting it run for all night. I'll tell you result tomorrow.

**Comment by bmiklautz** [comment]
@m0ntana if this fixes the problem I'll have a look next week to see how to properly fix this.

**Comment by m0ntana** [comment]
yep. I think it is 99% fix problem.

**Comment by bmiklautz** [comment]
@m0ntana I'm fairly sure there are multiple todos in the code. If you remember at some point what exact problem you fixed we can have a look.. In case it crashes again a gdb backtrace would be interesting.
