### ISSUE TITLE
Clipboard doesn't work from the client to the server

### ISSUE THREAD

**Issue by spimenov** [FreeRDP/FreeRDP#3358]
wfreerdp.exe (master built locally with VS2015) was used to connect from Windows 10 to Windows 2012R2:
"wfreerdp.exe /v:<host> +clipboard" : clipboard works from the server (Windows 2012R2) to the client (Windows 10) only. Doesn't work other way.
Clipboard was used to copy plain text from notepad to notepad.

**Comment by mateuf** [comment]
me too

**Comment by akallabeth** [comment]
Working with 3c7cc555a5a5f02366918be7eb935bb1f22115ef
