### ISSUE TITLE
Viewport is not changing in fullscreen when VM changes it's resolution (WS 2008 R2)

### ISSUE THREAD

**Issue by mnowaksuse** [FreeRDP/FreeRDP#3362]
I connect to a VM running on Hyper-V from Windows Server 2008 R2 via `/vmconnect:GUID`:

```
xfreerdp /u:Administrator /p:'pass' /v:IP /cert-ignore /f /jpeg /jpeg-quality:100 /fast-path:1 /bpp:32 /vmconnect:1B58D70E-A9D6-44DB-8543-D491838B8409
```

First the resolution is set by the Hyper-V BIOS to 640x480 px, then Grub loads and changes it to 800x600 px but the viewport of xfreerdp does not change, so the output is cropped to 640x480 px. Then resolution is changed in Grub manually to 1024x768 px but the viewport is kept as well so the output is cropped etc.

This does not happen for non-fullscreen mode (but then I need to at some point send 'ctrl-alt-return' when all resolution changes were performed to workaround it).

I use: `openSUSE Leap 42.1` with xfreerdp from https://build.opensuse.org/package/show/home:hendwolt/freerdp, code is from 20th-21st May 2016 git master.

The above scenario in fullscreen works for WS 2012 R2 just fine.

Similar issues: https://github.com/FreeRDP/FreeRDP/issues/2986 and https://github.com/FreeRDP/FreeRDP/issues/2166.
Figures: (1) 640x480, (2) 800x600, (3) 1024x768.
![640x480](https://cloud.githubusercontent.com/assets/16148464/15501743/65193048-21af-11e6-9d2b-5530410af565.png)
![800x600](https://cloud.githubusercontent.com/assets/16148464/15501742/6519533e-21af-11e6-8993-9ef64fb9a274.png)
![1024x768](https://cloud.githubusercontent.com/assets/16148464/15501744/651a4e10-21af-11e6-8086-7252acd0b63f.png)

**Comment by TheOpenDevProject** [comment]
Maybe #3360 related?

**Comment by mnowaksuse** [comment]
Not using Windows Server 2008 R2 anymore, haven't seen it anywhere else.
