### ISSUE TITLE
Toggling fullscreen causes hang

### ISSUE THREAD

**Issue by PhibreOptix** [FreeRDP/FreeRDP#3366]
Hi,

I'm using version 1.1.0-beta1 on ubuntu mate 16.04.
Connecting to laptop with the following switches:
xfreerdp \
        /cert-ignore \
        /multimon \
        +fonts \
        /bpp:32 \
        /sound \
        -themes \
        -wallpaper \
        +decorations \
        /u:xxxx \
        /d:xxx
        /p:xxx \
        /v:192.168.0.198

This correctly loads full screen across both my monitors.
When I press CTRL+ALT+Enter to toggle fullscreen, my window decorations become available, however the FreeRDP process appears to be hung.
Both remote monitors shrink in size and I need to use CTRL+ALT+F1 to get to a tty to kill xfreerdp, I've attached a screenshot to demonstrate the issue.

![selection_004](https://cloud.githubusercontent.com/assets/788893/15522382/60aa19f4-2255-11e6-8f74-f946a0a97292.png)

**Comment by bmiklautz** [comment]
@PhibreOptix could you try our nightly builds and see if this problem still happens:
https://ci.freerdp.com/job/freerdp-nightly-binaries/

**Comment by PhibreOptix** [comment]
Issue is not occurring with nightly build, functioning as expected.

**Comment by bmiklautz** [comment]
@PhibreOptix thank you for your feedback.

**Comment by vatshat** [comment]
> @PhibreOptix could you try our nightly builds and see if this problem still happens:
> https://ci.freerdp.com/job/freerdp-nightly-binaries/

Worked like a charm on Ubuntu 16.04 running Unity. 
Just in case anyone struggles like I did to install this "special" build, here's what I did to install 

``` bash
wget -O - http://pub.freerdp.com/repositories/ADD6BF6D97CE5D8D.asc | sudo apt-key add -
sudo sh -c 'echo "deb http://pub.freerdp.com/repositories/deb/$(lsb_release -cs)/ freerdp-nightly main" >> /etc/apt/sources.list.d/freerdp-nightly.list'

sudo apt-get update
sudo apt-get install -y freerdp-nightly

/opt/freerdp-nightly/bin/xfreerdp /u:thabile /v:1.2.3.4  
```
Here's a referece [link](https://github.com/FreeRDP/FreeRDP/issues/2665) which helped me
