### ISSUE TITLE
it needs long time to connect to terminal server by gateway

### ISSUE THREAD

**Issue by RexFan** [FreeRDP/FreeRDP#3368]
Hello, I find it should wait a long time (15 ~ 25s)while connecting to microsoft windows 2012r2 terminal server by gateway.

I use raspberry pi 3 as client, rasbian jessie (debian jessie version 8) with kernel 4.4.9.

xfreerdp version: 2.0.0-dev (git 4e66df7)

xfreerdp command: 
xfreerdp /sec:rdp /cert-ignore /u: /f /fonts /drive:*,hotplug /network:modem /sound:sys:pulse /microphone:sys:pulse /v:10.10.10.10 /g:1.1.1.1 /gu:xxx /gp:xxx /gd:xxx

compile command: sudo cmake -DTARGET_ARCH=ARM

Installed package: build-essential git-core cmake xsltproc libssl-dev libx11-dev libxext-dev libxinerama-dev libxcursor-dev libxdamage-dev libxv-dev libxkbfile-dev libasound2-dev libcups2-dev libxml2 libxml2-dev libxrandr-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev libxi-dev libgstreamer-plugins-base1.0-dev libavutil-dev libavcodec-dev fonts-droid fonts-nanum

Can anyone help?

Many thanks.

**Comment by hardening** [comment]
And do you experiment something different using the official MS client ?

**Comment by RexFan** [comment]
Sorry, it should be the server issue. I tested it with another server and it works fine. Thanks.

**Comment by ccpp** [comment]
Sounds like a duplicate of #3602. Two questions:
- Does it work with `/gt:rpc`?
- What happens when you hit Enter just after launching xfreerdp (after connection to the gateway is established)?
