### ISSUE TITLE
Fullscreen Mode Appears on Wrong Monitor

### ISSUE THREAD

**Issue by Enverex** [FreeRDP/FreeRDP#3395]
I'm not sure if this is a bug with Marco (MATE's Window Manager) or FreeRDP so I'll log it here first.

In a multiple monitor situation (whilst using FreeRDP on only one monitor), under certain circumstances, FreeRDP will appear on the wrong monitor.

The specific situation I've encountered where this happens: If you have 2 monitors connected, with the left as the primary and the right as the secondary, as well as the left monitor having a higher resolution than the right, then when FreeRDP starts fullscreen (with monitor 2 selected as the monitor to use) - it will appear fullscreen on monitor one. BUT, if you then use Ctrl+Alt+Enter to window FreeRDP and then Ctrl+Alt+Enter to fullscreen it again, jump to being fullscreen on the correct monitor.

This behavior doesn't happen if both monitors are the same resolution or if monitor 2 is a higher resolution than monitor 1. In those cases it works as it should.

**Comment by Enverex** [comment]
This issue is still present in current GIT.

**Comment by Enverex** [comment]
Still present as of today.

**Comment by akallabeth** [comment]
There have been some fullscreen fixes recently and it works on my test machines (debian based)
Closing as resolved, reopen if still an issue.
