### ISSUE TITLE
Synchronizing media playback via rdpegfx and rdpsnd

### ISSUE THREAD

**Issue by ilammy** [FreeRDP/FreeRDP#3398]
Hi,

Currently with `/gfx` enabled it is possible to get audio and video desynchronized during multimedia playback. This happens mostly due to latency of drawing order processing.

There is such thing as [[MS-RDPEVOR]: Remote Desktop Protocol: Video Optimized Remoting Virtual Channel Extension](https://msdn.microsoft.com/en-us/library/hh554658/) which should allow FreeRDP to synchronize H.264 video stream received via _rdpegfx_ with the audio stream received via _rdpsnd_ by using common timestamps provided by these protocols.

Did anybody try it? Or is anybody working on this already by chance? What's your thoughts on this?

**Comment by uplusplus** [comment]
I have been spending a month on RDPEVOR，and will be finished basically now.
@ilammy

**Comment by bmiklautz** [comment]
@ilammy would be nice to have but from our side nobody is actively working on.
@uplusplus you are actively working on this and will do a pull request then?
