### ISSUE TITLE
Local machine desktop freezes

### ISSUE THREAD

**Issue by urtus** [FreeRDP/FreeRDP#3401]
Thank you for making this great piece of software. I am using xfreerdp for a year now. I did come across this software to connect the server with a gateway (of my former employer).  I am using it now for a regular RDP-session. 

Here's my problem:
When I want to return to my local machine I use [CTRL] + [ALT] + [ENTER]. That works just fine.
But after a few minutes I can't use my local desktop environment anymore. It has been frozen. I can't select any other local program. As a workaround I kill the xfreerdp session on a virtual consoles (CTRL+ALT+F1). Then I am able to use my desktop environment. Can somebody help me with this issue?

I use the folling command line to connect with the server of my employer:
sudo xfreerdp /v:remote.work.nl /u:richard /d:work /cert-ignore -f +auto-reconnect +toggle-fullscreen

Local OS: Linux Mint 17.3 Cinnamon 64-bit
Connecting to Windows 2012 Server R2 (terminalserver)

I have installed freerdp according to this tutorial http://ifconfig.dk/freerdp/
FreeRDP version: 2.0.0-dev (git 8bbbbf3)

Greetings,
Richard 
The Netherlands

**Comment by Virp** [comment]
I have same problem.
Local OS: Linux Mint 18 Cinnamon 64-bit
Connecting to Windows 2012 Server R2 (terminalserver)
FreeRDP version 2.0.0-dev (git 5d7027a)

**Comment by akallabeth** [comment]
There were some autreconnect related issues that are fixed with `2.0.0-rc4` which could result in such a behaviour.
