### ISSUE TITLE
Screen sharing with Microsfot Application

### ISSUE THREAD

**Issue by cpalludetti** [FreeRDP/FreeRDP#3409]
I´m developing an application to share my Desktop with the MS Application.
I´m using the branch stable-1.1 (hash commit = 770c67d340d5f0a7b48d53a1ae0fc23aff748fc4).
When I use 32-bit and NSCCodec, MS Application receives the presentation and shows my desktop, but, after some random time (minutes) the RDP connection is dropped with the reason = 3080.
When I use 16-bit and NSCCodec, MS Application receives the presentation, but does not show my desktop, and after some random time the RDP connection is dropped with the reason = 3080.
If I use 32 or 16-bits with no compression, there is no problem, MS Application shows my Desktop without dropping the RDP connection.

After some research I figured out that the reason = 3080 means:

CUccApplicationViewerChannel2::OnConnectionTerminated - RDP connection has terminated - lDiscReason=3080 lExtendedInfo=0
the page https://msdn.microsoft.com/en-us/library/aa382170(v=vs.85).aspx

shows that the Disconnect Reason 3080 means:
disconnectReasonClientDecompressionError (3080 (0xC08)) - Decompression error.

Which would be a reason to give this error in decompression?

Any help would be very appreciated.

BR,

Claudio

**Comment by bmiklautz** [comment]
@cpalludetti there are a some issues in stable-1.1 that are already fixed on the master branch (upcoming 2.0). I'd recommend using master instead of 1.1 as there won't be any updates.

**Comment by cpalludetti** [comment]
It is working very well with the master branch.
When the 2.0 will be released?

**Comment by bmiklautz** [comment]
@cpalludetti we don't have a fixes schedule but I think Q4 is resonable.
