### ISSUE TITLE
How to set old style -n <hostname> option in new style options ?

### ISSUE THREAD

**Issue by cheech1440** [FreeRDP/FreeRDP#3413]
Hi !

How to set old style option `-n <hostname>` with a new style options ?

I'm using FreeRDP version 1.1.0-beta1 in Ubuntu-mate 16.04 and I trying various settings:
`-n <hostname>` - not working
`/n:<hostname>` - not working
`--n <hostname>` - not working

Please help me.

**Comment by hendwolt** [comment]
Try: `/client-hostname:<name>`

**Comment by bmiklautz** [comment]
@cheech1440 /client-hostname:<hostname> is the correct parameter from 1.1 onward. Just verified and on master this works as expected. I also tried with the legacy command line and it works too.

Here the command lines used for testing


```
xfreerdp /v:192.168.50.32 /client-hostname:new-style
```
```
xfreerdp -n legacy testbox
```

Could you try our nightly packages if the problem exists there for you as well?
https://ci.freerdp.com/job/freerdp-nightly-binaries/

**Comment by cheech1440** [comment]
@bmiklautz thanx for your answer !

Okey, just see the video: [https://youtu.be/znBC2MgBteo](url)

> Could you try our nightly packages if the problem exists there for you as well?
https://ci.freerdp.com/job/freerdp-nightly-binaries/

I add this line to end of sources.list file: `deb http://pub.freerdp.com/repositories/deb/DIST/ freerdp-nightly main`, then I enter the command in mate-terminal: `wget -O - http://pub.freerdp.com/repositories/ADD6BF6D97CE5D8D.asc | sudo apt-key add - `
After this I just enter command: `sudo apt-get update` and I get this error:
`Чтение списков пакетов… Готово`
`W: The repository 'http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly Release' does not have a Release file.`
`N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.`
`N: See apt-secure(8) manpage for repository creation and user configuration details.`
`E: Failed to fetch http://pub.freerdp.com/repositories/deb/DIST/dists/freerdp-nightly/main/binary-amd64/Packages  404  Not Found [IP: 212.232.26.215 80]`
`E: Некоторые индексные файлы не скачались. Они были проигнорированы или вместо них были использованы старые версии.`

What I doing wrong ?

P.S. Please, sorry for bad English :-/

**Comment by bmiklautz** [comment]
@cheech1440 the video returns a 404.
Did you replace "DIST" in the url with the actual distribution you are using as described?

**Comment by cheech1440** [comment]
@bmiklautz thanx for your answer !

> the video returns a 404

Sorry ( I correct the link.

> Did you replace "DIST" in the url with the actual distribution you are using as described?

OMG. Sorry for my inattention (
I replace "DIST" with xenial and completely install freerdp-nightly ! Thnx ! And more:
nightly package works fine with option: `/client-hostname:<hostname>`

**Comment by bmiklautz** [comment]
@cheech1440 also did you try with my above's snippets? - In you video it seems you do have a space between /client-hostname and the hostname itself but this should be a ':'

**Comment by bmiklautz** [comment]
@cheech1440 also can you please paste your the **exact** you are using?

**Comment by cheech1440** [comment]
@bmiklautz copy-paste from my command line: 
`xfreerdp /bpp:16 +compression +fonts /client-hostname:ADS11001 +smart-sizing /cert-ignore -themes -wallpaper /gdi:sw /audio-mode:1 +clipboard /drive:DuckBook,/home/cheech/RDP_Shared /size:1358x720 /d:MEDKAM /u:pikalov.dv /v:10.37.10.40` where option `/client-hostname:ADS11001` - not working.

And command with using freerdp-nightly package:
`/opt/freerdp-nightly/bin/xfreerdp /bpp:16 +compression +fonts /client-hostname:ADS11001 +smart-sizing /cert-ignore -themes -wallpaper /gdi:sw /audio-mode:1 +clipboard /drive:DuckBook,/home/cheech/RDP_Shared /size:1358x720 /d:MEDKAM /u:pikalov.dv /v:10.37.10.40` where option `/client-hostname:ADS11001` - working fine.

As you can see - no space between /client-hostname and the hostname. 

> @cheech1440 also did you try with my above's snippets?

what do you mean ?

**Comment by bmiklautz** [comment]
@cheech1440 ok so if it works with the nightly package it's a problem with the package ubuntu ships.

In the video it looked like there is a space in between. So I was wondering ;).
I'd recommend to either use our nightly packages for now and/or file an upstream report with Ubuntu.

**Comment by cheech1440** [comment]
@bmiklautz thank you for your help !
