### ISSUE TITLE
Wayland Clipboard support

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#3414]
The full version:

`wlfreerdp /u:<myusername> +clipboard  /v:192.168.0.59
[17:21:46:392] [6451:6451] [ERROR][com.winpr.library] - LoadLibraryA: /usr/lib/freerdp2/libcliprdr-client.so: cannot open shared object file: No such file or directory
`

This happens with the current version in HEAD on openSUSE Tumbleweed with Gnome 3.20 "on Wayland".

The file libcliprdr-client.so does not exist. 
The wlfreerdp was build on OBS with these options:
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX:PATH=%{_prefix} \
    -DCMAKE_INSTALL_LIBDIR:PATH=%{_lib} \
    -DCMAKE_SKIP_INSTALL_RPATH=ON \
    -DWITH_CUPS=ON \
    -DWITH_CLIENT=ON \
    -DWITH_PCSC=ON \
    -DWITH_ALSA=ON \
    -DWITH_PULSE=ON \
    -DWITH_DIRECTFB=OFF \
    -DWITH_FFMPEG=OFF \
    -DWITH_JPEG=ON \
    -DWITH_GSM=ON \
    -DWITH_GSTREAMER_1_0=ON \
    -DWITH_IPP=OFF \
    -DWITH_OPENSSL=ON \
    -DWITH_CHANNELS=ON \
    -DWITH_X11=ON \
    -DWITH_XCURSOR=ON \
    -DWITH_XEXT=ON \
    -DWITH_XKBFILE=ON \
    -DWITH_XI=ON \
    -DWITH_XINERAMA=ON \
    -DWITH_XRENDER=ON \
    -DWITH_XV=ON \
    -DWITH_ZLIB=ON \
    -DSTATIC_CHANNELS=OFF \
    -DWITH_SERVER=OFF \
    -DWITH_DEBUG_SCARD=OFF \
    -DWITH_SMARTCARD_INSPECT=ON \
    -DWITH_WAYLAND=ON \
    -DWITH_LIBSYSTEMD=ON \
    -DCMAKE_NO_BUILTIN_CHRPATH=ON \

**Comment by pedjaman** [comment]
Any update on this?

**Comment by hardening** [comment]
clipboard is not implemented for wayland so...

**Comment by pedjaman** [comment]
I had same issue on OpenSUSE. I've just solved by issuing
`freerdp_register_addin_provider(freerdp_channels_load_static_addin_entry, 0)`

**Comment by myfreeweb** [comment]
Looks like clipboard is default now? Upgraded to 2.0.0rc1, have to explicitly specify `-clipboard` to avoid instant crash after logon. FreeBSD 12-CURRENT, Weston git master

**Comment by akallabeth** [comment]
Wayland clipboard API https://wayland.freedesktop.org/docs/html/ch04.html#sect-Protocol-data-sharing
