### ISSUE TITLE
USB redirection not working Fedora 24; liburbdrc-client.so not found

### ISSUE THREAD

**Issue by rene51** [FreeRDP/FreeRDP#3424]
I run Fedora 24 and freerdp-2.0.0-5 and cannot redirect usb. Old probel seems to persist. Is there any work around?

[rene@V2-PH1 ~]$ xfreerdp /u:rene /sound:sys:alsa /usb:id,dev:091e:2459 /v:192.168.178.19
[16:41:29:423] [2972:2973] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpdr
[16:41:29:423] [2972:2973] [INFO][com.freerdp.client.common.cmdline] - loading channel rdpsnd
[16:41:29:423] [2972:2973] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
Password: 
[16:41:41:505] [2972:2973] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel urbdrc
[16:41:41:505] [2972:2973] [ERROR][com.winpr.library] - LoadLibraryA: /usr/lib64/freerdp/liburbdrc-client.so: cannot open shared object file: No such file or directory

**Comment by akallabeth** [comment]
@rene51 which version did you use and which compile flags? usb support needs to be compiled in.

**Comment by rene51** [comment]
went back to Fedora 23. same problem.
used latest version from Git. cmake -DWITH_PCSC=ON -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON

**Comment by rene51** [comment]
also used this (and some other variations) but none worked for usb redirection
cmake -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DCHANNEL_URBDRC=ON

**Comment by akallabeth** [comment]
@rene51 Looks like there have been some issues with the cmake find scripts, can you give https://github.com/akallabeth/FreeRDP/tree/uuid_find_fix a try?

**Comment by rene51** [comment]
[root@v2-ph1 FreeRDP]# cmake -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DCHANNEL_URBDRC=ON
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28") 
-- FreeRDP GIT
-- Git Revision 7439299
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Success
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Success
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Success
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Success
-- Performing Test Wno-builtin-macro-redefined
-- Performing Test Wno-builtin-macro-redefined - Success
-- Performing Test Wno-builtin-macro-redefinedCXX
-- Performing Test Wno-builtin-macro-redefinedCXX - Success
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for pthread_tryjoin_np in pthread
-- Looking for pthread_tryjoin_np in pthread - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Found X11: /usr/lib64/libX11.so  
-- Finding recommended feature Wayland for Wayland (Wayland client)
--     Disable feature Wayland using "-DWITH_WAYLAND=OFF"
-- Could NOT find WAYLAND (missing:  WAYLAND_LIBRARY WAYLAND_INCLUDE_DIR) 
CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature Wayland was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:535 (find_feature)


-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.2h") 
-- Skipping optional feature OpenSLES for multimedia (OpenSLES audio / video)
--     Enable feature OpenSLES using "-DWITH_OPENSLES=ON"
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Found ALSA: /usr/lib64/libasound.so (found version "1.1.1") 
-- Skipping optional feature Pulse for sound (audio input, audio output and multimedia redirection)
--     Enable feature Pulse using "-DWITH_PULSE=ON"
-- Skipping optional feature Cups for printing (printer device redirection)
--     Enable feature Cups using "-DWITH_CUPS=ON"
-- Skipping optional feature PCSC for smart card (smart card device redirection)
--     Enable feature PCSC using "-DWITH_PCSC=ON"
-- Finding recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Disable feature FFmpeg using "-DWITH_FFMPEG=OFF"
-- Checking for module 'libavcodec'
--   Package 'libavcodec' not found
-- Checking for module 'libavutil'
--   Package 'libavutil' not found
-- Could NOT find FFmpeg (missing:  AVUTIL_FOUND AVCODEC_FOUND) 
Note: To build libavcodec version >= 0.8 (API >= 53.25.0) is required
CMake Warning at cmake/FindFeature.cmake:46 (message):
      feature FFmpeg was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
  CMakeLists.txt:551 (find_feature)


-- Skipping optional feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
--     Enable feature GStreamer_0_10 using "-DWITH_GSTREAMER_0_10=ON"
-- Finding recommended feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
--     Disable feature GStreamer_1_0 using "-DWITH_GSTREAMER_1_0=OFF"
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.46.2
-- Found Glib 
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.6.4
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.6.4
-- Checking for module 'gstreamer-app-1.0'
--   Found gstreamer-app-1.0, version 1.6.4
-- Checking for module 'gstreamer-audio-1.0'
--   Found gstreamer-audio-1.0, version 1.6.4
-- Checking for module 'gstreamer-fft-1.0'
--   Found gstreamer-fft-1.0, version 1.6.4
-- Checking for module 'gstreamer-pbutils-1.0'
--   Found gstreamer-pbutils-1.0, version 1.6.4
-- Checking for module 'gstreamer-video-1.0'
--   Found gstreamer-video-1.0, version 1.6.4
-- Found GSTREAMER_1_0: /usr/lib64/libgstreamer-1.0.so  
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- FreeRDP GIT
-- Finding recommended feature XKBFile for X11 keyboard (X11 keyboard file extension)
--     Disable feature XKBFile using "-DWITH_XKBFILE=OFF"
-- Found XKBFile: /usr/lib64/libxkbfile.so  
CMake Error at channels/client/CMakeLists.txt:27 (list):
  list sub-command REMOVE_DUPLICATES requires list to be present.


-- FreeRDP GIT
-- Found DocBookXSL: /usr/share/sgml/docbook/xsl-stylesheets  
-- Finding required feature XShm for X11 shared memory (X11 shared memory extension)
-- Found XShm: /usr/lib64/libXext.so  
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
-- Found Xinerama: /usr/lib64/libXinerama.so  
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Found Xext: /usr/lib64/libXext.so  
-- Finding recommended feature Xcursor for cursor (X11 cursor extension)
--     Disable feature Xcursor using "-DWITH_XCURSOR=OFF"
-- Found Xcursor: /usr/lib64/libXcursor.so  
-- Finding recommended feature Xv for video (X11 video extension)
--     Disable feature Xv using "-DWITH_XV=OFF"
-- Found Xv: /usr/lib64/libXv.so  
-- Finding recommended feature Xi for input (X11 input extension)
--     Disable feature Xi using "-DWITH_XI=OFF"
-- Found Xi: /usr/lib64/libXi.so  
-- Looking for XITouchClass
-- Looking for XITouchClass - found
-- Finding recommended feature Xrender for rendering (X11 render extension)
--     Disable feature Xrender using "-DWITH_XRENDER=OFF"
-- Found Xrender: /usr/lib64/libXrender.so  
-- Finding recommended feature Xfixes for X11 xfixes extension (Useful additions to the X11 core protocol)
--     Disable feature Xfixes using "-DWITH_XFIXES=OFF"
-- Found Xfixes: /usr/lib64/libXfixes.so  
-- Configuring incomplete, errors occurred!
See also "/root/FreeRDP/CMakeFiles/CMakeOutput.log".
See also "/root/FreeRDP/CMakeFiles/CMakeError.log".

**Comment by rene51** [comment]
[CMakeError.txt](https://github.com/FreeRDP/FreeRDP/files/334748/CMakeError.txt)
[CMakeOutput.txt](https://github.com/FreeRDP/FreeRDP/files/334749/CMakeOutput.txt)

**Comment by akallabeth** [comment]
@rene51 looks like you're missing some development libraries. check if you have all required ```-devel``` packages installed. Should be in the README and the spec file for the RPM package.

**Comment by rene51** [comment]
all required -devel packages are installed.  Only after I commented out this line:
#list(REMOVE_DUPLICATES CHANNEL_STATIC_CLIENT_ENTRIES)
in /channels/client/CMakeLists.txt
I could run 'make install'.  
CMakeError.log gives still errors (not well understood by me) see: attached file
running xfreerdp now gives this error: (everything works apart from usb!)
[root@v2-ph1 FreeRDP]# xfreerdp /u:rene /usb:id,dev:091e:2459 /v:192.168.178.19
[17:46:00:939] [13452:199264000] [ERROR][com.winpr.library] - LoadLibraryA: /usr/local/lib64/freerdp/libdrdynvc-client.so: kan gedeeld objectbestand niet openen: Bestand of map bestaat niet
Password:
----
/usr/local/lib64/freerdp  does not exist at all.
[CMakeError.txt](https://github.com/FreeRDP/FreeRDP/files/335301/CMakeError.txt)

**Comment by bmiklautz** [comment]
@rene51 would you please add the cmake version that is used on Fedora 24?

**Comment by rene51** [comment]
I did not compile under F24 but installed freerdp from fedora repo. Started compiling only when same error appeared under F23.

**Comment by bmiklautz** [comment]
Can you give our nightly packages a try. We don't provide them yet for F24 but F23 is available. https://ci.freerdp.com/job/freerdp-nightly-rpm-mock/

**Comment by rene51** [comment]
[root@v2-ph1 ~]# /opt/freerdp-nightly/bin/xfreerdp /u:rene /usb:id,dev:091e:2459 /v:192.168.178.19
[19:51:50:570] [20714:20715] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
Password: 
[19:51:55:792] [20714:20715] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel urbdrc
[19:51:55:793] [20714:20715] [ERROR][com.winpr.library] - LoadLibraryA: /opt/freerdp-nightly/lib64/freerdp2/liburbdrc-client.so: kan gedeeld objectbestand niet openen: Bestand of map bestaat niet

**Comment by rene51** [comment]
directory  ' /opt/freerdp-nightly/lib64/freerdp2/  '  does not exist

**Comment by akallabeth** [comment]
@rene51 Looks like the USB channel has an issue with ```BUILTIN_CHANNELS=OFF```. Don't have that error when enabled.

**Comment by rene51** [comment]
compiled with:
[root@V2-PH1 FreeRDP]# cmake -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DCHANNEL_URBDRC=ON -DBUILTIN_CHANNELS=ON -DCMAKE_BUILD_TYPE=Debug 

error still comes up:
[root@V2-PH1 FreeRDP]# xfreerdp /u:rene  /usb:id,dev:091e:2459 /v:192.168.178.29
[21:46:31:273] [20214:20215] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
Password: 
[21:46:34:423] [20214:20215] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel urbdrc
[21:46:34:423] [20214:20215] [ERROR][com.winpr.library] - LoadLibraryA: /usr/local/lib64/freerdp2/liburbdrc-client.so: cannot open shared object file: No such file or directory

**Comment by akallabeth** [comment]
@rene51 Looks like I shouldn't post before coffee, confused ```ON``` with ```OFF```. With ```BUILTIN_CHANNELS=OFF``` the desired so file is build.

**Comment by rene51** [comment]
Haha, one shouldn't even work before coffee!
liburbdrc-client.so file is now generated.
However get some errors on the USB devices:
[18:49:44:177] [9813:9814] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
Password: 
[18:49:49:346] [9813:9814] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel urbdrc
[18:49:49:347] [9813:9814] [ERROR][com.freerdp.channels.urbdrc.client] - error processing arguments
[18:49:49:357] [9813:9814] [WARN][com.freerdp.channels.urbdrc.client] - bus:0 dev:0 not exist in udevman
[18:49:49:358] [9813:9814] [INFO][com.freerdp.channels.urbdrc.client] - VID: 0x091E, PID: 0x2459
[18:49:49:364] [9813:9814] [ERROR][com.freerdp.channels.urbdrc.client] -     Device is not supported!!
[18:49:49:365] [9813:9814] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel urbdrc
[18:49:49:365] [9813:9814] [ERROR][com.freerdp.channels.urbdrc.client] - error processing arguments
[18:49:49:365] [9813:9814] [WARN][com.freerdp.channels.urbdrc.client] - bus:0 dev:0 not exist in udevman
[18:49:49:365] [9813:9814] [INFO][com.freerdp.channels.urbdrc.client] - VID: 0x1307, PID: 0x0165
[18:49:49:371] [9813:9814] [ERROR][com.freerdp.channels.urbdrc.client] -     Device is not supported!!
[18:49:49:371] [9813:9814] [ERROR][com.freerdp.channels.urbdrc.client] - existing device, abort.

**Comment by rene51** [comment]
[root@V2-PH1 FreeRDP]# lsusb
Bus 001 Device 010: ID 091e:2459 Garmin International GPSmap 62/78 series
Bus 001 Device 009: ID 1307:0165 Transcend Information, Inc. 2GB/4GB/8GB Flash Drive
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 
Bus 005 Device 003: ID 0cf3:3005 Atheros Communications, Inc. AR3011 Bluetooth
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 
Bus 004 Device 002: ID 04d9:2517 Holtek Semiconductor, Inc. 
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 
Bus 002 Device 001: ID 1d6b:0001 Linux Foundation

**Comment by rene51** [comment]
This was the xfreerdp command:
[root@V2-PH1 FreeRDP]# xfreerdp /u:rene  /usb:id,dev:091e:2459 /usb:id,dev:1307:0165 /v:192.168.178.30

**Comment by akallabeth** [comment]
@rene51 mass storage devices are blocked by the plugin. either use drive redirection for that (faster) or patch out the filter for the vid.

**Comment by gnshkl1** [comment]
@akallabeth i am having the same issue with mass redirection so need to know how to patch it for same.
Also drive redirection and usb redirection is different and having different usage.

**Comment by akallabeth** [comment]
Closing as the initially reported issue is a build problem and the mass storage discussion won't help as servers block this too.
