### ISSUE TITLE
In Windows we can get frerdp through connection broker.

### ISSUE THREAD

**Issue by ChandrasekharSurathi** [FreeRDP/FreeRDP#3425]
Hi,
I'm using windows machine, From windows machine i want to get remote  desktop from collection through connection broker in windows by passing the collection name as a parameter to load-balance-info.

"Is it possible to get freerdp of the collection desktop through connection broker in windows".

Pls provide the your suggestion ASAP.

**Comment by bmiklautz** [comment]
This is an issue tracker. For questions like this please use irc or our mailing list. Thank you.

**Comment by ChandrasekharSurathi** [comment]
Ok , Thanks for your support.
