### ISSUE TITLE
Very long lags on filetransfers

### ISSUE THREAD

**Issue by RubenKelevra** [FreeRDP/FreeRDP#3427]
We use a OpenVPN tunnel over a 10/1 mbit/s dsl connection. Over this connection we establish some rdp connections with Remmina.

First of all, this isn't a network issue, we use cake with traffic shaping on the router and fq_codel on the client, so there is no bufferbloat on the network-side.

The rtt to the rdp server is min/avg/max/mdev = 44/55/170/16 msec.

Everything works fine with around one dozen rdp sessions over this uplink/vpn, until you try to upload a file over the folder-share option of remmina which shares an local folder to the remote server. When you start the upload the session hung for several seconds (like 30-60) after this time the screen refreshes once and stall again.

With a different connection on a different thinclient are not roubles at the same time, else the ping to terminal server from this host does not indicate any troubles.

So I think the freerdp sends very large chunks of traffic over the rdp connection which blocks everything else than the filetransfer.

As workaround I use an smb-server on the thinclient which works fluently.

Please give us some details about the systems you are using:
- Client (OS name and version): Arch Linux latest
- Remmina version (remmina --version): 1.2.0
- Desktop environment (GNOME, Unity, KDE, ..): lxde
- Connecting to (OS and version): Windows Server 2012 R2
- Connecting via (RDP, VNC, ...): RDP
- RDP issues only, freerdp version (xfreerdp --version): 2.0.0-dev (git 6e15931)

`$ xfreerdp --version
This is FreeRDP version 2.0.0-dev (git 6e15931)
[11:29:56:426] [16306:16306] [ERROR][com.winpr.sync.mutex] - pthread_mutex_destroy failed with Das Gerät oder die Ressource ist belegt [16]`

Original created here: https://github.com/FreeRDP/Remmina/issues/908

**Comment by HenryJacques** [comment]
I confirm that I have the same issue as well (FreeRDP 2.0 on a Ubuntu 14.04 64 bits)

**Comment by RubenKelevra** [comment]
cc @kevin-olbrich

**Comment by lemonmojo** [comment]
I'm also seeing these issues on macOS 10.11 El Capitan and 10.12 Sierra DP using https://github.com/FreeRDP/FreeRDP/commit/0d7a6b5596d2fa2cf7350ff91548fc80b39dd144.

**Comment by kevin-olbrich** [comment]
@RubenKelevra and I can confirm that this is reproducible for Win 2012 and 2012 R2.
Using built-in Windows RDP (Windows 10, which supports Proto 10.0) as the client to 2012 or 2012 R2 also shows some small lags but UI remains responsive where FreeRDP freezes up. FreeRDP starts uploading the file, the UI freezes and disconnect is only possible by killing the process.

**Comment by hartois** [comment]
I also confirm this bug with freerdp 2.0 (Fedora 26) on windows 2008 r2 and windows 2012 r2 without vpn.
No problems on download (from terminal to shared folder) - only on upload (from shared folder to terminal).

**Comment by hartois** [comment]
Any news on this issue?
