### ISSUE TITLE
aFreeRDP RemoteApp shows black screen

### ISSUE THREAD

**Issue by aildermi** [FreeRDP/FreeRDP#3430]
Hi,
I am trying to run a RemoteApp on a Windows Server 2012 R2. After connection established, LogonUI appears, and then, only desktop background (black screen) is shown, without any errors or anything! Taskbar and Desktop Icons are not shown, and also remote application is not executed.
I can connect to then server without RemoteApp option, but when adding "app=||[app-name]" screen goes black!
I tested the RemoteApp using other applications as Remmina and aFreeRDP 1.1.0-dev (1.0.1-1813-g9f8d0) and it is fine!
What am I doing wrong?
I am using following Uri for connection:
`freerdp://[username]@[host]:[port]/connect?port=[port]&p=[password]&size=[width]x[height]&bpp=16&wallpaper=-&window-drag=-&menu-anims=-&themes=-&fonts=-&aero=-&async-channels=-&async-transport=-&async-input=-&async-update=-&clipboard=+&audio-mode=0&sound=&log-level=TRACE&sec=nla&cert-ignore&a=rail&app=||[app-name]`
Thanks

**Comment by bmiklautz** [comment]
@aildermi just to make sure: you trying to run RemoteApp on Android (aFreeRDP is the Android client)?

**Comment by aildermi** [comment]
@bmiklautz I forgot to mention that. Yes, I am trying to use RemoteApp on Android.

**Comment by bmiklautz** [comment]
@aildermi the Android client doesn't support RemoteApp as it doesn't implement the client side part of the rail channel.  Initially the "app" parameter you pass with the URI was used to set the an alternative shell but seems that mistakenly got changed at some point.

**Comment by aildermi** [comment]
@bmiklautz Thanks for your fast reply. What I wanted was to run an application right after connection. So I was mistakenly using "app" instead of "shell" parameter. Your last response was very helpful.
Thanks :+1:

**Comment by shailendrapundhir** [comment]
Its 29th August 2017, does the android port support remoteApp now? I need to start some remote applications through remote app parameter only. Using shell its not possible for some apps.

**Comment by bmiklautz** [comment]
@shailendrapundhir no the Android port doesn't support remote app (RAILS).
