### ISSUE TITLE
Windows 10 Professional + Hyper-V = KO

### ISSUE THREAD

**Issue by virtman** [FreeRDP/FreeRDP#3432]
Hello,

Let's make example, downloaded image
http://www.pwrusr.com/downloads
CentOS 6.2 X64 minimal VHD…
it is 187 MB -- Centos-6.2-x86_64-minimal-dist.7z
And imported this machine and than started with
wfreerdp.exe /cert-ignore /u:myuser /p:mypass /vmconnect:A6B9BF58-27DA-4633-9C0F-CA5FE9CA9805 /v:127.0.0.1:2179

It looks like it is
1. passing preconnection blob successfully
2. passing ntlm auth successfully
3. exits shortly after sending client capatibilties

Checked it with fresh windows nightly build from today.

However it starts fine with Microsoft tool
VmConnect.exe" "domain" "1" -G "A6B9BF58-27DA-4633-9C0F-CA5FE9CA9805" -C "0"
Windows 10 Professional

Thank you in advance!

**Comment by virtman** [comment]
From what I saw, after succeed precblob and ntlm auth Microsoft seems to dislike some passed parameters (which one???) and send forced end of session with ERRINFO_RPC_INITIATED_DISCONNECT 

When I set in sent bitmap caps desktopResize to 0 and 
in rdp.c -> rdp_recv_tpkt_pdu
continue to read packets instead to exit, I get conitnuous image from that hyper-v instance, but I can not send mouse events and keyboard events, however I can still send controls via vmconsole that looses its control and stopped image update, but still accepts key inputs where display changes are visible than in freerdp, also strange bug too. What I did is not solution and can not be reused, but may lead to point where to look..
I assume, Microsoft began to use some new protocol or anything else that makes it impossible to reuse FreeRDP for Hyper-v now..

**Comment by akallabeth** [comment]
still an issue?

**Comment by virtman** [comment]
Hello,

hard to answer by good reason.
As mentioned, the Microsoft's client VmConnect.exe worked fine before too, but some time after, probably a month Microsoft created a patch for server side that made it working fine for FreeRDP too.
Therefore if you ask me, if it was fixed, i answer of course no idea, probably new FreeRDP still wouldn't work with old Microsoft server version. However i believe i know what was difference why Microsoft vmconnect client worked. It has sent inside its pdu desktopResizeFlag set always to zero despite of server support. When i have forcibly set it to zero then it worked fine with FreeRDP too. But nowdays it is anyway not necessary.

**Comment by akallabeth** [comment]
@virtman ok, thank you. will close this issue for now.
