### ISSUE TITLE
Remoteapp not reparented

### ISSUE THREAD

**Issue by darkweaver87** [FreeRDP/FreeRDP#3437]
Hello,

It seems that using together /parent-window:<xid> and /app:<path_to_exe> is not working as expected (app launched in the parent window). I'm trying to write a patch but I never did X11 programming :-(

Thanks for your help.

Rémi

**Comment by bmiklautz** [comment]
@darkweaver87 reparenting is only supported for regular (desktop) windows but not for RemoteAPP. One of the reasons is that remote apps might have multiple windows.

**Comment by darkweaver87** [comment]
Then, users have to specify multiple parentWindows or application will throw an error in those case :-)
But I understand your point :-)

Rémi
