### ISSUE TITLE
multiple issues with fullscreen mode on two monitors

### ISSUE THREAD

**Issue by nshustov** [FreeRDP/FreeRDP#3439]
xfreerdp /multipon /u:&lt;skipped&gt; /v:&lt;skipped&gt;

Ubuntu 16.04 LTS (Kubuntu) x64
2 monitors

Both in  the latest stable and nightly builds of freerdp:

freerdp-nightly          2.0.0+0~20160707014830.282~1.gbp89c252       amd64
freerdp-x11              2.0.0~dev~git20160331+dfsg-0xenial3                   amd64
1. Client does not span on multiple monitors in full screen mode - it just sticks to one monitor. 
   It behaves this way with both same resolution monitors and different resolution monitors. **It used to work some time ago (sorry, not sure what package upgrade broke it).**
2. When switched to windowed mode, an attempt to move the window makes it minimized and there is no way to restore the window/maximize it.
3. After window went minimized as described in the above step (and has active input focus) attempting to go full screen mode (via keyboard shortcut) crashes freerdp with the following diagnostics:

(nightly build):

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Value in failed request:  0x0
  Serial number of failed request:  24794
  Current serial number in output stream:  24797

(stable):

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Value in failed request:  0x0
  Serial number of failed request:  61016
  Current serial number in output stream:  61019

**Comment by vadimseyn** [comment]
I have the same problem as you on OpenSUSE 42.1

**Comment by FragsterAt** [comment]
same in freerdp-2.0.0~git.1463131968.4e66df7 precompiled for opensuse 42.1
on server side (win 10m win server 2012 etc) there are 2 monitors, but freerdp window show only "primary"

**Comment by T3N4K4** [comment]
Have you tried the parameters "/span" or "/multimon:force"?
Or the combination of both "/f /multimon /span"?
Maybe it even helps to give the actual size of both monitors together to "/size:<width>x<height>".

And I don't know if it is relevant, but it sometimes worked for me to explicitly enable tls "+sec-tls".

**Comment by FragsterAt** [comment]
with /span remote system thinks that I have a big monitor,  but freerdp displays one full screen window on one of the monitors and a half of "big" screen
Other combinations, including +sec-tls, /monitors:0,1 etc, do not work

freerdp /monitor-list returns an correct result:
      * [0] 1920x1200   +0+0
        [1] 1920x1200   +1920+0

$ xfreerdp /multimon:force /sec:rdp /v:server
outputs to the console

[16:40:10:008] [6140:6141] [ERROR][com.freerdp.core.gcc] - WARNING: true multi monitor support was not advertised by server!
[16:40:10:009] [6140:6141] [ERROR][com.freerdp.core.gcc] - Sending multi monitor information anyway (may break connectivity!)

but older releases of freerdp running well on the same server
older - 1.0.2 from opensuse 42.1 release, but there are other issues with drive and sound redirection

**Comment by caramorsimon** [comment]
multimon & span are conflicting options. Span is where you are trying to use several local displays but present one display the remote server to display on. 
Multimon is where you are trying to pass several client displays so the server understands there are multiple displays for it. 
xenial/gnome/xfreerdp master build as of 6th oct works ok with multimon, I have not tried span.
I  also use /monitors:0,1 to pass selected monitors over to the server. 
By default multimon comes up fullscreen & the keyboard shortcut toggles to a window - I'm using smart sizing so it just scales a bit oddly]
There are some problems - notably with workspaces & I see that I am also getting some odd disconnections (possibly related) whereby the client is quietly disconnected & the screen remains painted but frozen. [disconnect/reconnect resumes behaviour - haven't turned debug on to see what is really happening yet]

**Comment by FragsterAt** [comment]
this command didn't work on my system with prebuld freerdp-nightly-2.0-0+0~20161007033816.244~1.git267dea9.x86_64:
/opt/freerdp-nightly/bin/xfreerdp /multimon /monitors:0,1 /u:user /d:domain /v:server

**Comment by snugam** [comment]
I noticed on XUbuntu in the screen settings - the dual monitors were not lined-up.  I discovered this because the day before the two independent monitors worked fine, when I used the same command again - the desktop was stretched.  I quickly realized it was because I had shifted the alignment.  

As soon as I aligned them horizontally again - the desktop was no longer stretched.  /multimon:force is not really required, just /multimon

**Comment by FragsterAt** [comment]
@snugam , after connecting with /multimon, i have one 1920*1200 window with picture from "primary" remote monitor. In KDE preferences monitors aligned fine. Freerdp option /span + /size works, but it is not usable for me.
```
xfreerdp -monitor-list
[13:46:54:611] [32681:32681] [INFO][com.freerdp.utils] - Registering signal hook...
      * [0] 1920x1200   +0+0
        [1] 1920x1200   +1920+0
```

**Comment by axkibe** [comment]
With "/f /monitors 0"
it works on one monitor in full screen, but on the wrong monitor, its not the one listed as 0 in -monitor-"list /f /monitors 1" -- results in the same thing on the same monitor (but that one would be correct)
```
~$ xfreerdp -monitor-list
      * [0] 1920x1080	+1440+0
        [1] 1440x900	+0+0
```

**Comment by T3N4K4** [comment]
@axkibe I guess it is /f /multimon (which should include /f) /monitors:0,1 or something like that.
So maybe you can try ```/multimon /monitors:0,1 or /multimon /monitors:1,0```

**Comment by jasonblewis** [comment]
```
jason@quartz:~$ xfreerdp -monitor-list
      * [0] 1920x1200	+1920+0
        [1] 1920x1200	+0+0
        [2] 1920x1200	+3840+0
```
Main monitor is always the far left no matter which combination of ```/monitors:2,1,0``` I launch with. ie, its als othe same for 0,1,2 and 1,2,0 etc.

**Comment by hardening** [comment]
Hi guys, could you give a try to https://github.com/FreeRDP/FreeRDP/pull/4187 ?

**Comment by akallabeth** [comment]
Is this resolved with the latest merges?

**Comment by Ortega-Dan** [comment]
just in case Multimon is working great now
in Ubuntu 18.04 in my case
xfreerdp /multipon /u:<skipped> /v:<skipped>

**Comment by drjacka** [comment]
I had a very similar case to this and found killing Latte dock resolved FeeRDP multi monitor starting on the incorrect monitor and spanning off to a screen that didn't exist
