### ISSUE TITLE
View bug

### ISSUE THREAD

**Issue by zuriy** [FreeRDP/FreeRDP#3440]
I'm use 1.2.0-rcgit.14 (git n/a) and ubuntu 16.04(x86) FreeRDP version 2.0.0-dev (git n/a)

When i'm working on windows 2008 r2 on RDP I have visualuzation problem:
http://storage1.static.itmages.com/i/16/0707/h_1467914793_1005195_25b72a7ef8.png
This is not very big problem, but when insert end line. On video 
https://yadi.sk/i/vLEI6mZEt6apw
and 
https://yadi.sk/i/Ys5ROpxXt6aqA
When I connect to this session from windows rdp all work correct.

redirected from https://github.com/FreeRDP/Remmina/issues/920

**Comment by zuriy** [comment]
Have you find this bug?

**Comment by akallabeth** [comment]
@zuriy GDI and color conversion have been rewritten, so the possibility of this issue still being current are quite low (as I've not seen any of the issues you described)
Should the issue persist contrary to expectations feel free to reopen. (but please add a command line so it is easier to reproduce)
