### ISSUE TITLE
Popup window not showing

### ISSUE THREAD

**Issue by anoteng** [FreeRDP/FreeRDP#3444]
One of the remoteapps I'm using is a webapp I have to use internet explorer for. The server is win2012. When I try to view documents in the webapp I would normally get a popup asking which program to open the pdf in. This popup shows as a black square when running through xfreerdp, and I'm unable to choose anything, thus also unable to do anything besides killing the connection.

**Comment by ushni** [comment]
Have a similar problem. Missing interface elements (menus, pop-ups windows and tooltips ...) in remoteapp. 
Instead of empty space.
Ubuntu 16.04
freerdp-nightly builds (trusty)

**Comment by bmiklautz** [comment]
@anoteng @ushni would you try to connect with /rfx?

**Comment by ushni** [comment]
@bmiklautz 
Tried, not working. Command line is:
/opt/freerdp-nightly/bin/xfreerdp /rfx /rfx-mode:image -sec-nla /cert-ignore /app:"||iexplore" /v:192.168.2.226

**Comment by anoteng** [comment]
After switching PPAs (see issue #3443) xfreerdp no longer connects to any servers. Adding the /rfx flag seems to correct this, but i can only see a still image of the app, and I am unable to do anything (move/resize window, enter text, push buttons).

**Comment by akallabeth** [comment]
@anoteng Remote app channel has seen some fixes and is working for our test cases.
Since this issue is quite old, I'm closing it, but if you still experience issues reopen/create a new one.
