### ISSUE TITLE
No release version tagged in 3+ years

### ISSUE THREAD

**Issue by ardichoke** [FreeRDP/FreeRDP#3453]
FreeRDP has not had an actual release tagged, as far as I can tell, in over 3 years. This makes it difficult for users who want to submit/update bugs to the project to tell if they have already been fixed, but are just not in the package for our distribution since everything shows up as 2.0.0-dev, and it's hard to tell what commit the build is based off of. Providing tagged milestones for packagers to work off of will make it much easier to identify if fixes for specific bugs are or are not present in the packaged version a user is using.

Even if you just arbitrarily choose a stable point in the tree, increment the minor version number and tag it, that would be a huge improvement over the current system of never having a new "stable" release and constantly working off of unversioned nightly builds.

**Comment by bmiklautz** [comment]
@ardichoke thare are multiple issues regarding this subject. Please have a look to #2839

**Comment by ardichoke** [comment]
Sorry, a lot of results came up when I was searching for an existing issue that this would fall under. Must have missed that.
