### ISSUE TITLE
User inputs are not recognized when video playback is running

### ISSUE THREAD

**Issue by jobraun** [FreeRDP/FreeRDP#3454]
First some specs about the machine which was used to start remote session:
- Ubuntu 13.10
- CPU: AMD G-T44R Single Core 1.2 GHz 
- GPU: Integrated Radeon HD 6250
- RAM: 1 GB
- Ethernet: 1 GBit
- Command line: `xfreerdp /v:<remote server> /p:<passwd> /u:<user> /d:<domain> /f -grab-keyboard -compression /sound:sys:pulse`

My last freerdp version I used was build from stable-1.1 branch. The overall performance with this build was great. I was able to watch youtube videos. Also Big Bug Bunny 480p runs smooth without multimedia redirection.

Yesterday I tried the current development HEAD (freerdp 2.0) and the overall remote performance decreased noticeably. Youtube videos are running, but with laggs. The remote session is not controlable when a video was started in the remote session, e.g. Big Bug Bunny,

Then I made some profiling with valgrind. I started xfreerdp with `valgrind --tool=callgrind xfreerdp` and saw that there are a lot of calls into libssl and libcrypto.
Freerdp 2.0 is able to connect via TLS 1.2. When TSL 1.2 is used, a lot of `SHA256_Transform` calls in libcryto.so are done. Whereas Freerdp 1.1 only connects to TLS 1.0 and therefore only `SHA1_Transform` is called. These SHA256_Transform calls are 43 percent of the overall workload.

The other difference I mentioned is that Freerdp 2.0 does call libcrypto functions. This results in `EVP_Cipher` calls which did 24 percent of workload. Is this only for key calculation or for certificate handling?

I also tried some parameters without success.
- `-bitmap-cache`: Does improve the performance, but artefacts are drawn in my remote firefox browser. Artefacts are also drawn into Chrome browser.

- `/rfx`: No effect, cause host windows does not run in Microsoft Hyper-v.

- `/gfx`: Video playback breaks RDP session with the following error log:
`[12:21:03:894] [18025:18026] [INFO][com.freerdp.client.common.cmdline] - loading channel drdynvc
Password: 
[12:21:08:461] [18025:18026] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[12:21:09:593] [18025:18035] [ERROR][com.freerdp.channels.drdynvc.client] - ChannelId 10 not found!
[12:21:09:594] [18025:18035] [ERROR][com.freerdp.channels.drdynvc.client] - drdynvc_order_recv failed with error 1359!
[12:21:09:882] [18025:18026] [ERROR][com.freerdp.core] - drdynvc_virtual_channel_client_thread reported an error. Error was 1359
[12:21:09:882] [18025:18026] [INFO][com.freerdp.client.x11] - Network disconnect!
[12:21:09:882] [18025:18026] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor`

Are there any parameters (Freerdp cmd line or CMAKE) or configurations which will help to increase the performace with current Freerdp version 2.0? Or do I have to stick with the older freerdp?

Thanks Jo

**Comment by T3N4K4** [comment]
As far as I know you don't need to run your windows in Hyper-V to enable rfx.
I configured myself rfx on windows server 2008 sp1 and windows server 2012r2 (both virtual machines without hyper-v) which makes the sessions more controllable with freerdp /rfx.

Maybe this blog / website helps you (gpedit.msc settings):
http://blog.tedd.no/2011/04/28/optimizing-rdp-for-casual-use-windows-7-sp1-remotefx/

If it is enabled and still lagging, try setting "+async-input" and "+async-update".

**Comment by jobraun** [comment]
> As far as I know you don't need to run your windows in Hyper-V to enable rfx.
> I configured myself rfx on windows server 2008 sp1 and windows server 2012r2 (both virtual machines without hyper-v) which makes the sessions more controllable with freerdp /rfx.
> 
> Maybe this blog / website helps you (gpedit.msc settings):
> http://blog.tedd.no/2011/04/28/optimizing-rdp-for-casual-use-windows-7-sp1-remotefx/

Sadly /rfx didn't improve the performance. 


> Edit: Also try setting the "Limit maximum color depth" to 32 bit on windows.

Also did reduce the color depth via parameter `/bpp` but the result wasn't a noticable performance boost.


> If it is enabled and still lagging, try setting "+async-input" and "+async-update".

When I read your answer, I hoped to improve speed by adding `+async-input` and `+async-update`. But there was no improvement.


As I said in my first post, a lot of cpu load is produced due to ssl lib calls (`SHA256_Transform` and `EVP_Cipher`).

**Comment by T3N4K4** [comment]
With  
> Edit: Also try setting the "Limit maximum color depth" to 32 bit on windows.
I meant the setting in the group policy. If I remember correctly it said on one page that you have to set this setting in order to be able to use rfx. Not with the /bpp setting.

async-input and async-update did help us only with rfx enabled.

To the ssl lib calls I guess a developer has to get into it.
Maybe @bmiklautz (Just trying to help)

**Comment by bmiklautz** [comment]
@jobraun there is not much you can do about the ssl library call but to try connecting with RDP security (disable nla and tls security) but this is "less" secure than. There is also a pending pull request that should improve input handling when a lot of data is transferred (like when watching a video).
I'd suggest re-trying the current master quite some GDI changes have been integrated lately. Maybe it also helps you.

**Comment by soar** [comment]
I can confirm this problem. Running even YouTube 480p video in small box causes interface lag. Session becoming unusable, I can't press any interface button, only kill xfreerdp process.

When FreeRDP 1.1 works nice on 1 GHz CPU, FreeRDP 2.0 on same processor looks very slow. On a 2-cores 2.5 GHz CPU all works nicely.

**Comment by akallabeth** [comment]
Should be fixed with #3364 or am I wrong with that assumption?

**Comment by soar** [comment]
@akallabeth should I use `max-loop-time` parameter for testing?

**Comment by hardening** [comment]
If all the complains in this issue are fixed by #3364, let's close it. Bug reporters any objection ?

**Comment by soar** [comment]
Today I've got client crash on a6f4117 - browser was opened with YouTube video playback (about ~10 minutes after login).

```
# xfreerdp /v:example.com +decorations +fonts +aero +window-drag +menu-anims +themes +wallpaper +compression /bpp:32 /kbd:US /sound:sys:pulse /microphone:sys:pulse /multimedia:sys:pulse /drive:USB,/mnt/usbdevice /smartcard /d:EXAMPLE /u:'' /w:1900 /h:1000 /rfx /gdi:hw
...
[13:53:33:602] [5557:5558] [ERROR][com.freerdp.core.fastpath] - FASTPATH_UPDATETYPE_SURFCMDS - update_recv_surfcmds() - -1
[13:53:33:602] [5557:5558] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data: fastpath_recv_update() - -1
[13:53:33:602] [5557:5558] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[13:53:33:602] [5557:5558] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[13:53:33:602] [5557:5558] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[13:53:33:602] [5557:5558] [INFO][com.freerdp.client.x11] - Network disconnect!
[13:53:33:602] [5557:5558] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[13:53:33:675] [5557:5570] [ERROR][com.freerdp.channels.rdpsnd.client] - VirtualChannelWrite failed with CHANNEL_RC_NOT_CONNECTED [00000004]
[13:53:33:675] [5557:5570] [ERROR][com.freerdp.channels.rdpsnd.client] - error confirming wave
```

I don't see this bug on previous builds and I think it can be related to this change. Checked on Windows Server 2012 with enabled RemoteFX.

[freerdp-crash-a6f4117.txt](https://github.com/FreeRDP/FreeRDP/files/544241/freerdp-crash-a6f4117.txt)

**Comment by akallabeth** [comment]
@soar Are you using any of the async command line options?

**Comment by soar** [comment]
@akallabeth Nope. I provided command line options exactly as I use it.

**Comment by akallabeth** [comment]
@soar Ok, checked the code. The only reason this function may fail is if it receives a unexpected command. (short remaining data) Could you check if it works without compression?

**Comment by akallabeth** [comment]
closing this issue as the initial error reported is resolved. Continuing the disconnection issue in #3518
