### ISSUE TITLE
Window is not filled up

### ISSUE THREAD

**Issue by kallekutta** [FreeRDP/FreeRDP#3455]
Hello,

I have a problem. The issue occurred suddenly, after I connected a third monitor. Here is the command:
`xfreerdp /v:1.2.3.4 /size:1728x972 /kbd:0x0000041D /u:username /p:password`

This worked fine before now there is a problem with the window having black bars and not fill up. I have included a picture of my problem. Anyone have a clue?
![picture](https://cloud.githubusercontent.com/assets/20796399/17331581/d4796ca2-58cb-11e6-9595-58256c240bc9.png)

**Comment by bmiklautz** [comment]
@kallekutta can you give more information on "it worked fine before"? Can you provide some version information or build details?

**Comment by kallekutta** [comment]
What I mean was that the remote desktop was using the whole window. As you can see in the picture it is smaller and up in the left corner. There should be no black bars. If there hasn't been any new version since 16 days ago then it is the latest version running on Ubuntu 16.04.1.

**Comment by sirianni** [comment]
I am seeing a similar issue.  For me any `/size` width above 1600 width yields black bars, whereas `size` below 1600 width works as expected.  Not only is there a black bar on the right (at the 1600px cap), but one on the bottom as well.  My guess is that FreeRDP is trying to preseve the same aspect ratio given by my size parameter but within the 1600px constrained width, thus shrinking the height.  This also triggers the scaling feature which makes the performance poor and yields blurry visuals.

I am running xfreerdp from the Ubuntu 16.04 repository.
```
$ xfreerdp /version 
This is FreeRDP version 1.1.0-beta1 (git n/a)
```

This worked for me on Ubuntu 14.04 prior to upgrading (not sure what xfreerdp version that was).
Same Windows 10 remote server in both cases.

**Comment by sirianni** [comment]
I am running in a dual monitor setup (laptop and external display).  The smaller screen has a width of 1600px.  This may be related to the bug...

**Comment by akallabeth** [comment]
can not reproduce with 2.0 release candidates / current master.
