### ISSUE TITLE
Ipv6 pub.freerdp.com broken

### ISSUE THREAD

**Issue by ruben-herold** [FreeRDP/FreeRDP#3458]
hi,
pub.freerdp.com  reloved to 

ruben@work:[~] > host pub.freerdp.com 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

pub.freerdp.com has address 212.232.26.215
pub.freerdp.com has IPv6 address a02:1b8:badc:ab1e::f8ee
ruben@work:[~] > 

Would say this broken...

**Comment by bmiklautz** [comment]
@ruben-herold thanks for pointing that out. It seems a digit got missing with the last update. I corrected the address now and once DNS is refreshed it should work again.
