### ISSUE TITLE
[iOS] Can't build with xcodebuild

### ISSUE THREAD

**Issue by computerion** [FreeRDP/FreeRDP#3459]
The README for this is a bit old as it suggests using iOS 6.1 :
```
xcodebuild -project FreeRDP.xcodeproj -configuration Debug -sdk iphoneos6.1
```
Executing the command with `iphoneos9.3` instead gives the error:
```
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include/emmintrin.h:27:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include/xmmintrin.h:27:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.3.0/include/mmintrin.h:45:12: error: invalid conversion between vector type
      '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
```

Any ideas?

**Comment by akallabeth** [comment]
could you try running cmake with the sdk parameter? changing later does not always work

**Comment by computerion** [comment]
Sorry for the late reply, which parameter would that be? Could you elaborate on how to do that please?

**Comment by akallabeth** [comment]
@computerion I've recently updated a lot of stuff, you should try #3450 
It contains updated OpenSSL build scripts and some improvements to the FreeRDP library as well as the iOS client.

As for building:

1. Build OpenSSL with the provided script (ensure the SDK version matches the one you want to use later on)
2. Run CMake as suggested in the README. (Add ```-DIOS_PLATFORM=SIMULATOR``` if you intent to run it there)
3. Open XCode and select target ```iFreeRDP```
4. Ready to go...
