### ISSUE TITLE
freerdp2 library names conflict with older versions

### ISSUE THREAD

**Issue by floppym** [FreeRDP/FreeRDP#3460]
It looks like some attempt was made to allow the libraries from freerdp 2 to be installed alongside the libraries from older versions (freerdp 1.2.x). For the most part this works, with the exception of the bare so symlinks that get installed in the system libdir.

For example, here is the output when one tries to install freerdp-1.2.5 and freerdp-2.0.0 simultaneously on Gentoo Linux.

```
 * Detected file collision(s):
 * 
 *      /usr/lib64/libfreerdp-shadow.so
 *      /usr/lib64/libfreerdp-server.so
 *      /usr/lib64/libfreerdp-client.so
 *      /usr/lib64/libfreerdp.so
 *      /usr/lib64/libwinpr.so
 * 
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * net-misc/freerdp-2.0.0_pre20160722:0::gentoo
 *      /usr/lib64/libfreerdp-client.so
 *      /usr/lib64/libfreerdp-server.so
 *      /usr/lib64/libfreerdp-shadow.so
 *      /usr/lib64/libfreerdp.so
 *      /usr/lib64/libwinpr.so
 * 
 * Package 'net-misc/freerdp-1.2.5_pre20151104' NOT merged due to file
```

One way to avoid this would be to rename the libraries to include the major version as part of the library name before the .so, ie `libfreerdp2.so -> libfreerdp2.so.2`.

I suppose another way to avoid it would be to install the libraries into separate libdirs when building, but that's not something a Linux distro would typically do.

**Comment by bmiklautz** [comment]
@floppym I really wonder what 1.2.5 actually is in terms of git version. It looks like it is something between 1.1 and 2.0...

**Comment by floppym** [comment]
In this case, 1.2.5 is 1ba4f9b67ff77b1d28aac8bb3d1de83f71e24c2a. I tried to find the last commit before the major version was bumped in CMakelists.

**Comment by bmiklautz** [comment]
@floppym from my point of view it should be possible to have them installed in parallel as long as you don't have the "development" files (which should include the .so link). I'm fairly sure FreeRDP is not the only project that causes this problem on gentoo. Anyway I see your point and we'll discuss this.

**Comment by floppym** [comment]
If you only wanted to allow for the non-devel files to be installed concurrently, then why would you install the header files *.h in a versioned directory? It just seems kind of pointless/inconsistent.
