### ISSUE TITLE
List of freerdp return codes?

### ISSUE THREAD

**Issue by FragsterAt** [FreeRDP/FreeRDP#3462]
Where is full list of freerdp return codes?
for something like this:
#! /bin/bash

freerdp ....

CODE=$?
case $CODE in
    0|5|11|12)
        exit 0
        ;;
    *)
        kdialog --msgbox "$CODE $RES"
        ;;
esac

**Comment by T3N4K4** [comment]
Is this what you are looking for?
https://github.com/FreeRDP/FreeRDP/blob/90b3bf4891e426d422ddb0581560450013832e5e/client/X11/xfreerdp.h

**Comment by FragsterAt** [comment]
Exellent! Thank you!
