### ISSUE TITLE
How can I crosscompile the newest FreeRDP on arm-linux

### ISSUE THREAD

**Issue by StevenYou** [FreeRDP/FreeRDP#3465]
I try to change the c/c++ compiler in CMakeLists and I also try to change the C/C++ compiler in MakeFile , But it doesn't work. 
I don't find any  instruction in Wiki to tell me how to do this. In Compilation of Wiki it only tell me how to compile in Linux , Mac OS and Windows.

**Comment by akallabeth** [comment]
@StevenYou This is a issue tracker, not a support forum.
Nonetheless, here is a starting point http://www.vtk.org/Wiki/CMake_Cross_Compiling
