### ISSUE TITLE
Try to read a second smartcard fails.

### ISSUE THREAD

**Issue by DanCasier** [FreeRDP/FreeRDP#3474]
Situation:
Server 2012R2 as terminal server. 
Users using FreeRDP to log on and running an application.
Using  wfreerdp /f /v:cloud.compufit.be /u:domainname\username /p:*******\* /a:smartcard,"OMNIKEY 3x21"

Problem:
Reading for the first time a smartcard is ok. But after removing the card and input the same or another one it is not possible to read the card. The software to read the card is shown up so you can verify to read the card. The window disappear but nothing happens. 
Same problem on OSX.
Only disconnecting and reconnecting helps. 
No errors displayed or found in logs.

Using another remote desktop program like RDP plus, Remote Desktop Connection manager 2.7 or MTSC does not give problems with the smartcard or smartcard reader.

It looks like this is a bug.

**Comment by akallabeth** [comment]
#4312 fixed a bunch of smartcard related issues bringing it to a usable state again.
Reopen, if your specific issue was not fixed.
