### ISSUE TITLE
freerdp and Win2012r2 TS farm with round robin

### ISSUE THREAD

**Issue by trentasis** [FreeRDP/FreeRDP#3477]
Hi,

I'm trying to configure a ts farm with windows 2012 r2 using dns round
robin+connectionbroker and 2 session brokers and freerdp

We have configured and tested from windows 10 machine and works great ,
putting one machine offline  ping and rdp is only redirected to server that is online.

Our problem is that failover from linux with freerdp, ping and freerdp connection
is not working correctly when one machine is offline, it seems that with
linux/freerdp is not managing failover as windows.

Tried +auto-reconnect, but seems that this is for reconnecting after initial connection, when it fails tries 20 attempts...

command used is xfreerdp /v:server +auto-reconnect /cert-ignore

anybody has  implemented a full automatic failover for ts farm with windows
2012? or where I can implement an automatic reconnect in this situations
(normally with 3 or 4 attemps reconnect to correct server correclty)?

Thanks

**Comment by bmiklautz** [comment]
@trentasis if "ping" is not working when the server is offline it might be a different issue. Maybe the old DNS name is still cached and the timeout you seeing is the cache timeout? What TTL is set in DNS?

**Comment by trentasis** [comment]
not sure, same dns and config with windows and mstc works and traffic is
redirected.
what config I have to use to read information about session hosts are up
from connection broker?

thanks

2016-10-14 12:17 GMT+02:00 Bernhard Miklautz <notifications@github.com>:

**Comment by akallabeth** [comment]
There have been redirection specific pull requests lately, this might already be solved.
Please confirm.

**Comment by trentasis** [comment]
Thanks, I'll try to test and report the results

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
local tests successful so far.
