### ISSUE TITLE
Dropdown lists issue

### ISSUE THREAD

**Issue by L-Eugene** [FreeRDP/FreeRDP#3480]
Dropdown list contents does not displayed.

Command line:
`./xfreerdp /u:user /p:pass /app:"||swriter" /v:192.168.4.200`

Server: Windows 2008 R2
Client: Linux Mint Debian Edition (both 32 and 64-bit), FreeRDP version 2.0.0-dev (installed from freerdp-nightly repo)

![shot](https://cloud.githubusercontent.com/assets/21239508/17967187/626ebfe4-6ace-11e6-9a31-842bdbcbb117.jpg)
![shot 2](https://cloud.githubusercontent.com/assets/21239508/17967243/aa21ed52-6ace-11e6-8ee9-50d61ca8e4af.jpg)

**Comment by bmiklautz** [comment]
@L-Eugene can you please re-try with the latest nightly if the problem still exists?

**Comment by L-Eugene** [comment]
Yes, the problem still exists.
```
Package: freerdp-nightly                 
Version: 2.0.0+0~20161014014832.300~1.gbp5a5f09

```

**Comment by bmiklautz** [comment]
@L-Eugene do you have the same problem as well if you run without remote app?

**Comment by L-Eugene** [comment]
No, problem exists only in remote app mode.

**Comment by tomich** [comment]
Just to add. I have the same issue. It happens with some dropdown menus (Example: Internet explorer, clicking on the address bar to see previous pages) and also on some hover texts (hovering buttons in apps shows a transparent sqare that shows the linux application behind or the desktop).

Im using 2.0.0~dev201701161718

**Comment by bmiklautz** [comment]
@tomich can you verify if this still happens with the latest nightly build?

**Comment by akallabeth** [comment]
duplicate
