### ISSUE TITLE
Problem with setRedirectMicrophone(boolean) setRedirectSound(int)

### ISSUE THREAD

**Issue by russian-studios** [FreeRDP/FreeRDP#3484]
Hello, I need setRedirectMicrophone(boolean) setRedirectSound(int) methods. But when I make ckeckout to stable-1.1 (for using in Eclipse), this methods is underfind. But in master branch this methods are current. How solve this problem?

**Comment by akallabeth** [comment]
@russian-studios stable-1.1 branch is unmaintained, if you really want to use that you're on your own. Otherwise use master (which is going to be 2.0 as soon as we can fix the color decoding issues)
