### ISSUE TITLE
I have a question about MPL

### ISSUE THREAD

**Issue by seyoung-hyun** [FreeRDP/FreeRDP#3486]
Hi, I'm Seyoung.

I want to refer to the FreeRDP/client/Android/Studio/freeRDPCore/src/main/java/com/freerdp/freerdpcore/utils/ButtonPreference.java file in my commercial app.
And I find the license "MPL" not "Apache" at top of the code.
Please let me know I must comply MPL license to use the code or can comply Apache license.

**Comment by bmiklautz** [comment]
@seyoung-hyun FreeRDP is generally APL. However some parts, including the Android Client, do have different licenses. If a different license is stated in the file header it does apply.
In your case if you are working an aFreeRDP based application you need to comply to APL for the user interface part.
