### ISSUE TITLE
mouse position error correction feature

### ISSUE THREAD

**Issue by shalnoff** [FreeRDP/FreeRDP#3489]
Hi! First of all, thank you for great RDP client!

It would be great to have command-line option to add horizontal and vertical error correction coefficient for position of mouse pointer.

This feature would be really helpful for remote control of guest VM on devices with the touch screen (which makes impractical to use guest OS mouse pointer, which is shifted)

Additional info: 
normally it looks like a (linear) shifting coefficient from the center of the screen (i.e. the host and guest mouse pointers are coinciding in the center, but diverging on distance), but theoretically the center of screen can be shifted as well (for example if someone using separate touch panel). So it would be great to have center coordinates parameters as well. 

Something like --pointershift<Xcoeff><Ycoeff><CenterXshift><XenterYshift>.

**Comment by shalnoff** [comment]
Sorry, parser kills the last line: 
--pointershift Xcoeff Ycoeff XcenterShift YcenterShift

**Comment by bmiklautz** [comment]
@shalnoff when do you have shifted mouse pointer? Can you give an example?

**Comment by akallabeth** [comment]
no feedback, closing.
