### ISSUE TITLE
[freerdp-master][#3435][3586e3][Android] a problem with the color screen when ouput.

### ISSUE THREAD

**Issue by m3053574** [FreeRDP/FreeRDP#3495]
- different background color and many block.
  ![device-2016-09-09-170224](https://cloud.githubusercontent.com/assets/5018453/18379846/86dacb92-76af-11e6-8438-04c9c9061ead.png)
- window button icon color
  ![device-2016-09-09-170342](https://cloud.githubusercontent.com/assets/5018453/18379847/86dd6618-76af-11e6-9b57-de2e678afa23.png)
- my account icon on windows7
  ![device-2016-09-09-170404](https://cloud.githubusercontent.com/assets/5018453/18379848/86dfc7fa-76af-11e6-82a1-cf9d8f5d2ece.png)

**Comment by m3053574** [comment]
I use build script.

export ANDROID_NDK_HOME=/Users/hyunseokjeong/Downloads/android-ndk-r10d
export ANDROID_SDK_HOME=/Users/hyunseokjeong/Library/Android/sdk
export PATH=$PATH:/Users/hyunseokjeong/Library/Android/sdk/tools:/Users/hyunseokjeong/Library/Android/sdk/platform-tools:/Users/hyunseokjeong/Downloads/android-ndk-r10d
sudo ./scripts/android-build-freerdp.sh --ndk $ANDROID_NDK_HOME --sdk $ANDROID_SDK_HOME --jpeg --openh264 --openssl --debug --build-deps

**Comment by akallabeth** [comment]
@m3053574 I've fixed some of these issues with pull #3450 Will rebase it soon to allow merging with current master but would appreciate some feedback on remaining issues ;)

**Comment by akallabeth** [comment]
#3500 is merged, any news on this issue?

**Comment by akallabeth** [comment]
Many color decoding related fixes in current master.
If this is still an issue reopen.
