### ISSUE TITLE
aFreeRDP connection problem on some devices

### ISSUE THREAD

**Issue by aildermi** [FreeRDP/FreeRDP#3498]
I'm developing an app using aFreeRDP (Android client) as a library.
Application worked perfect on almost all devices. But I faced an error which I forgot to report it sooner. There was a strange link error on some devices (like galaxy grand prime 2):

`07-28 17:59:31.160 W/dalvikvm(13044): No implementation found for native Lcom/freerdp/freerdpcore/services/LibFreeRDP;.freerdp_new (Landroid/content/Context;)I
07-28 17:59:31.160 D/AndroidRuntime(13044): Shutting down VM
07-28 17:59:31.160 W/dalvikvm(13044): threadid=1: thread exiting with uncaught exception (group=0x40c3b1f8)
07-28 17:59:31.160 E/AndroidRuntime(13044): FATAL EXCEPTION: main
07-28 17:59:31.160 E/AndroidRuntime(13044): java.lang.UnsatisfiedLinkError: freerdp_new
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.freerdp.freerdpcore.services.LibFreeRDP.freerdp_new(Native Method)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.freerdp.freerdpcore.services.LibFreeRDP.newInstance(LibFreeRDP.java:114)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.freerdp.freerdpcore.application.GlobalApp.createSession(GlobalApp.java:134)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.freerdp.freerdpcore.presentation.SessionActivity.connect(SessionActivity.java:798)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.freerdp.freerdpcore.presentation.SessionActivity.processIntent(SessionActivity.java:735)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.freerdp.freerdpcore.presentation.SessionActivity.access$1700(SessionActivity.java:71)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.freerdp.freerdpcore.presentation.SessionActivity$5.onGlobalLayout(SessionActivity.java:565)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:566)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1741)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2649)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at android.os.Handler.dispatchMessage(Handler.java:99)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at android.os.Looper.loop(Looper.java:137)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at android.app.ActivityThread.main(ActivityThread.java:4507)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at java.lang.reflect.Method.invokeNative(Native Method)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at java.lang.reflect.Method.invoke(Method.java:511)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
07-28 17:59:31.160 E/AndroidRuntime(13044):     at dalvik.system.NativeStart.main(Native Method)
07-28 17:59:31.160 W/ActivityManager(  185):   Force finishing activity r.intent.getComponent().flattenToShortString()
07-28 17:59:31.170 W/ActivityManager(  185):   Force finishing activity r.intent.getComponent().flattenToShortString()`
I managed to fix this issue by changing "winpr/libwinpr/CMakeLists.txt":
changed
`set(WINPR_LIBS "")`
to
`set(WINPR_LIBS "-l:libgcc.a")`
which fixed my problem. That's for the report!
## My Current Issue

After that, I haven't faced any runtime errors or any exceptions. But till recently, I found out that there is a connection issue on some devices, users are reporting the same problem, which can be categorized using their devices (Galaxy S3, Galaxy Note 3)
Users get stocked in Connecting page. After SessionActivity is loaded, A progress dialog is shown, asking user to wait until the connection is established, but after some time (around 2-3 minutes), connection fails. This is a rare issue, that only some of users reported. All others (thousands of users) are just fine! I've uploaded the logcat file [HERE](http://198.27.70.69/logcat.txt)

As you can see, there is a long gap after 
"Server rdp encryption method: NONE"
which happend at 22:00:03.854, and the next message from FreeRDP
"BIO_should_retry returned a system error 104: Connection reset by peer"
which happend at 22:02:39.664

My server is a "Windows Server 2012 R2" and I'm trying to connect using following URI:
`freerdp://${host-uname}@${host-ip-address}:${host-port}/connect?port=${host-port}&p=${host-upass}&size=${width}x${height}&bpp=16&wallpaper=-&window-drag=-&menu-anims=-&themes=-&fonts=-&aero=-&async-channels=-&async-transport=-&async-input=+&async-update=+&clipboard=+&audio-mode=0&sound=&log-level=TRACE&sec=nla&cert-ignore`

Many Thanks,
Armin

**Comment by akallabeth** [comment]
@aildermi Did you use the android compile script or did you compile yourself?

**Comment by aildermi** [comment]
@akallabeth I used the android compile script.

**Comment by akallabeth** [comment]
@aildermi Try without ```async-update``` or ```async-transport```, there seems to be some sync issue with one of those. Couldn't pinpoint the exact cause :/

**Comment by aildermi** [comment]
@akallabeth Unfortunately removing async-update and async-transport didn't fix the issue on those devices. I think the problem must be caused by something else, because I face the error (mentioned in logcat) before connection.

**Comment by akallabeth** [comment]
@aildermi Thought a bit about your issue, could it be related to aggressive power management killing the TCP connection?

**Comment by aildermi** [comment]
@akallabeth Unfortunately it isn't. Actually the problem happens before connection establishment, and also power management mode is disabled.

**Comment by akallabeth** [comment]
ok, got it. freerdp uses a simple comparison of server certificates. the crash in logcat happens there.

**Comment by aildermi** [comment]
@akallabeth If you can tell me the approximate location of the code block causing this problem, I can do some tests.

**Comment by akallabeth** [comment]
should be near the location VerifyCertificate et al are called. it tries to find stored certificates first.

**Comment by aildermi** [comment]
@akallabeth I completely ignored the certificate verification parts, but the problem remained the same. But I managed to trace down the problem. It seems the problem starts at "libfreerdp/core/transport.c" inside `transport_write` function. After `BIO_write` is called, returned value is negative, so `BIO_should_retry` is called and the error message "BIO_should_retry returned a system error 104: Connection reset by peer" is shown and the disconnection starts.
Why would something like this happen?
Since the old logcat file is not available now, I've uploaded a new logcat on Samsung Galaxy Grand2 device [here](http://185.116.162.176/logcat.txt)
Thanks

**Comment by akallabeth** [comment]
@aildermi Interesting, according to your logcat ```getprop``` in ```winpr_get_unix_timezone_identifier_from_file``` crashes for some reason. Maybe that is the point it starts to fall apart? Could you try to hard code a time zone there and see if it connects then?

**Comment by akallabeth** [comment]
@aildermi Oh, the output of ```adb shell getprop persist.sys.timezone``` would be nice to have too.

**Comment by MrCsabaToth** [comment]
@aildermi Do you think this is related? See `BIO_should_retry returned a system error 32: Broken pipe`
http://pastebin.com/wQz0UCsa
I have a Verizon Galaxy Note 3

**Comment by akallabeth** [comment]
#3705 should fix a lot of issues related with OpenSSL
Closing this as being resolved, should this reoccur please reopen.
