### ISSUE TITLE
RDP project

### ISSUE THREAD

**Issue by LitCooker** [FreeRDP/FreeRDP#3504]
hi 
   could  someone  give  a  project  about FreeRDP?  thanks!

**Comment by akallabeth** [comment]
wtf?

**Comment by LitCooker** [comment]
Hi !
	I am a beginner of iOS engineer.We need to use FreeRDP for this open source in our project，but I can't compile it into a static library.Could you give me a learning material or a demo for testing？
We are looking forward to your reply！Once again, I would like to offer my sincere thanks！

**Comment by akallabeth** [comment]
@LitCooker Ah ok, now I've got a clue what you're talking about ;) Look at ```docs/README.ios``` in the source tree. There is a small howto for compiling the project for iOS. As for similar questions please pot them in the IRC channel.
