### ISSUE TITLE
Dotted selection cursor

### ISSUE THREAD

**Issue by masepi** [FreeRDP/FreeRDP#3505]
I connect overt tsg and get dotted selection cursor
desktop os: openSuse Tumbleweed
remote os: Windows 10 Pro x64
This is FreeRDP version 2.0.0-dev (git n/a)

**Comment by bmiklautz** [comment]
@masepi  please have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting and add more information like command line, client you are using, program you have the problem with, a screenshot to illustrate the issue..
