### ISSUE TITLE
Quotes in /printer

### ISSUE THREAD

**Issue by Mogaba** [FreeRDP/FreeRDP#3506]
I don't know if this is a freerdp problem or my poor understanding of bash, but here's my problem:

This works:
```shell
PRINTER=/printer:HP-LaserJet-P2014,'HP LaserJet P2014'
xfreerdp $PRINTER
```

This works too:
```shell
PRINTER="/printer:HP-LaserJet-P2014,HP LaserJet P2014"
xfreerdp $PRINTER
```

This also works:
```shell
PRINTER="/printer:'HP-LaserJet-P2014',HP LaserJet P2014"
xfreerdp $PRINTER
```

But this does not work:
```shell
PRINTER="/printer:HP-LaserJet-P2014,'HP LaserJet P2014'"
xfreerdp $PRINTER
```
What's wrong with those quotes?
I'm using version 1.1.0~git20140921.1.440916e+dfsg1-4 from Debian 8.5

**Comment by akallabeth** [comment]
@Mogaba well, that looks like an expansion issue related to your shell. Just do a ```echo $PRINTER``` and see what the difference is. Btw, please use the IRC channel for such support questions.
