### ISSUE TITLE
32 bit colour depth issue

### ISSUE THREAD

**Issue by shattars3d** [FreeRDP/FreeRDP#3507]
Having a issue with the iOS client. When i connect in with 32 bpp for colour depth the iOS freerdp client crashes. Also, the server is set to 32 bpp colour depth. 

If I set the server side to 24 app or under connects in a session fine "using freerdp iOS client".. 

the errors from Xcode compiler are:

gdi_Bitmap_Decompress: Bitmap Decompression Failed
gdi_Bitmap_Decompress: Bitmap Decompression Failed
freerdp_bitmap_planar_decompress_plane_rle: too many pixels in scanline
gdi_Bitmap_Decompress: Bitmap Decompression Failed
freerdp_bitmap_planar_decompress_plane_rle: too many pixels in scanline
gdi_Bitmap_Decompress: Bitmap Decompression Failed
freerdp_bitmap_planar_decompress_plane_rle: too many pixels in scanline
gdi_Bitmap_Decompress: Bitmap Decompression Failed
gdi_Bitmap_Decompress: Bitmap Decompression Failed
gdi_Bitmap_Decompress: Bitmap Decompression Failed

Any one have any ideas?

**Comment by akallabeth** [comment]
@shattars3d Are you using current FreeRDP master? You could also check out #3500 which fixes a lot of bitmap decoding related issues.

**Comment by shattars3d** [comment]
@akallabeth  I found a work around the issue.. the gdi_Bitmap_Decompress method is graphics.c just have to re write some code.. but thanks i will look into that to.

**Comment by akallabeth** [comment]
@shattars3d Ok, closing the issue for now. Would be great to know if the issue persists with #3500 though.
