### ISSUE TITLE
Incorrect time stamps with drive redirection

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#3508]
When using drive redirection to copy files from a Windows machine to the host machine (ie. Windows -> macOS) the timestamps are incorrect. They are however correct if copying the other way around (from the host machine to the target (ie. macOS -> Windows)).

In my case, the timestamps seem to be sometime around 2011 all the time even if the copied file has just been created before copying.

I reproduced the issue with both, the X11 client as well as my own macOS based implementation.

For reference, please see the following two screenshots:

Original:
![Original](https://royaltsx-v3.royalapplications.com/temp/FreeRDP_DriveRedirection_Original.png), 

After Copy:
![After Copy](https://royaltsx-v3.royalapplications.com/temp/FreeRDP_DriveRedirection_Copied.png)

**Comment by akallabeth** [comment]
@lemonmojo Your host OS is OSX in both cases?

**Comment by lemonmojo** [comment]
Yes, I'm testing on macOS Sierra 10.12.1.

**Comment by akallabeth** [comment]
Looks like a conversion issue in ```FileSetFileTime``` in ```winpr/libwinpr/file/file.c```

**Comment by lemonmojo** [comment]
Possible. Any idea on how to fix it?

**Comment by lemonmojo** [comment]
@akallabeth Unfortunately that didn't fix it for me. In fact, after applying the patch, the timestamps are now gone completely. See the following screenshots:

Original:
![Original](https://royaltsx-v3.royalapplications.com/temp/FreeRDP_DriveRedirection_Patch_Original.png)

After Copy:
![After Copy](https://royaltsx-v3.royalapplications.com/temp/FreeRDP_DriveRedirection_Patch_Copied.png)

On the Mac:
![On the Mac](https://royaltsx-v3.royalapplications.com/temp/FreeRDP_DriveRedirection_Patch_Mac.png)

**Comment by akallabeth** [comment]
@lemonmojo Interesting, worked fine on my test mac. Got 10.11.6 here though.

**Comment by lemonmojo** [comment]
@awakecoding Why did you close the issue and merge the PR? At least for me the fix didn't work.

**Comment by awakecoding** [comment]
@lemonmojo I'm sorry, I went a bit too fast. A user reported a similar issue and the pull request looked fine, but I hadn't seen the original issue thread where it is clear that the fix in the pull request wasn't ready.

**Comment by djmannion** [comment]
I am also having this problem, but from a Windows -> Linux direction. It seems to occur particularly for Word documents. For example, if I (in Windows) create a new Word document in a folder on my Linux computer it has the correct time stamp information - but when I modify the file, the time stamp information changes to sometime in 2011 (such as 1 August 2011).

**Comment by Rainmaker52** [comment]
Confirmed on Linux (using latest git checkout).

The issue has been there for a while. Just never really bothered me before.

**Comment by flega68** [comment]
Same problem here.
I have this for a year now. The last version that worked (for me):
This is FreeRDP version 2.0.0-dev (git b02943a)
