### ISSUE TITLE
Help on fullscreen mode should document how to leave fullscreen

### ISSUE THREAD

**Issue by jondo** [FreeRDP/FreeRDP#3509]
It was difficult to me to find out about Ctrl-Alt-Enter. (I finally found it in #1036).

So I suggest to extend the corresponding help line to

> /f                      Fullscreen mode (leave with Ctrl-Alt-Enter)

**Comment by jondo** [comment]
See https://github.com/FreeRDP/FreeRDP/issues/3071#issuecomment-173616053 for someone else with the same problem.

**Comment by duhow** [comment]
I think this can be closed, as `-toggle-fullscreen` shows this.

**Comment by jondo** [comment]
@duhow, thanks for the hint, I was not aware of that!
However, I suggest to also add this text (`Alt+Ctrl+Enter toggles fullscreen`) to the help of `/f`, for better discoverability.
