### ISSUE TITLE
Improve example for drive redirection

### ISSUE THREAD

**Issue by stigok** [FreeRDP/FreeRDP#3513]
When reading the examples for drive redirection, I was confused due to the wording and the actual example. It made me think the `/drive` option had something to do with the home drive itself. I could find no better information about the option in either the man or `--help`, but the wiki explains it way better:

> `/drive:<sharename>,<path>` : Redirect <path> as share <sharename>

Proposing an update to the man and `--help` and I am happy to make a pull request for this if this makes sense to someone else as well.

References:
https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface#plugins
https://github.com/FreeRDP/FreeRDP/blob/90b3bf4891e426d422ddb0581560450013832e5e/client/X11/xfreerdp-examples.1.xml#L34-L39

**Comment by ArthurBorsboom** [comment]
+1

**Comment by one-more-alex** [comment]
+1
