### ISSUE TITLE
Feature request: A keybord shortcut to lock the client desktop session

### ISSUE THREAD

**Issue by jondo** [FreeRDP/FreeRDP#3516]
I am usually in a Windows fullscreen session via a LinuxMint-Cinnamon client.
In order to lock my client's Cinnamon session, I always have to leave fullscreen mode, move the keyboard focus out of the FreeRDP window, then hit Ctrl+Alt+L. If I just hit Windows-L, only the remote Windows session is locked.

I would like to be able lock the local Cinnamon session by hitting either of these combinations directly in fullscreen mode.

**Comment by akallabeth** [comment]
out of scope.
