### ISSUE TITLE
Segfault in normal session when using cliprdr in RemoteApp session

### ISSUE THREAD

**Issue by alex04103** [FreeRDP/FreeRDP#3517]
My setup consists of a Windows Server 2012 installation with some published remote apps.
The problematic situation occurs under the following circumstances:

Two simultaneous FreeRDP sessions, the first one being a normal desktop session, the second one a RemoteApp session.

While the first session was open, I tried to use the clipboard redirection in the second session.
This resulted in a segfault in the first session and in a "App not respoding"-state in the second one.

As I read after my initial attempts, i found out that the combination of rail and cliprdr is not supported. Still, at least any segfaults should be fixed per issue #1513 resp. #171, but unfortunately this doesn't seem to be correct under all circumstances.

Beside of this issue, which in theory is not relevant until one can actually use rail + cliprdr: Is there any schedule for implementation of this feature?

**Comment by bmiklautz** [comment]
@alex04103 I can't give you any schedule. However if you can provide back traces or a core file and/or a detailed instructions howto reproduce we can have a look at the segfault.

**Comment by akallabeth** [comment]
Tested with #4322 , no crash and clipboard works both ways.
