### ISSUE TITLE
Unable to connect to a terminal server when license model is for per-device

### ISSUE THREAD

**Issue by Mr-LZG** [FreeRDP/FreeRDP#3519]
four prerequisites 
1. The terminal server was configured to function in per-device license mode.
2. The terminal server have more than one  license server.
3. and one license server is not activationed.
4. The license server search mode is set to automatic.
If the above condition is met, i can't use freerdp connected to terminal server. But it is ok to use MSTSC  to   connected.

but if I specify the license server is a license server has been activated , then i can connect to the terminal server .

How can I solve this problem ?

**Comment by akallabeth** [comment]
Licensing was refactored with #4979 
Closing.
Reopen if still an issue.
