### ISSUE TITLE
Android client crashed

### ISSUE THREAD

**Issue by uplusplus** [FreeRDP/FreeRDP#3520]
error:
 java.lang.NoSuchMethodError: no static method with name='OnVerifyChangedCertificate' signature='(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I' in class Lcom/freerdp/freerdpcore/services/LibFreeRDP;

patch:
diff --git a/client/Android/android_freerdp.c b/client/Android/android_freerdp.c
index b3a548d..501426d 100644
--- a/client/Android/android_freerdp.c
+++ b/client/Android/android_freerdp.c
@@ -466,7 +466,7 @@ static DWORD android_verify_changed_certificate(freerdp* instance,
     jstring jstr5 = (*env)->NewStringUTF(env, old_issuer);
     jstring jstr6 = (*env)->NewStringUTF(env, old_fingerprint);
 
-    jint res = freerdp_callback_int_result("OnVerifyChangedCertificate",
+    jint res = freerdp_callback_int_result("OnVerifyCertificate",
             "(ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;"
             "Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I",
             instance, jstr0, jstr1, jstr2, jstr3, jstr4, jstr5, jstr6);

**Comment by akallabeth** [comment]
@uplusplus Fixed in #3500

**Comment by akallabeth** [comment]
@uplusplus closing as the callback has been fixed with pull #3500. Reopen if you still experience issues.
