### ISSUE TITLE
screen distortion in current master

### ISSUE THREAD

**Issue by marrowsuck** [FreeRDP/FreeRDP#3526]
I get some graphical artifacts when I connect to a windows server (2008/ windows7).
This is my command:
xfreerdp -grab-keyboard +clipboard -wallpaper /kbd:0x00000407 /printer /w:1920 /h:1160 /u:USER /v:IP:PORT
When I use the /gdi:sw flag, the artifacts disappear.
![screenshot-1475828930](https://cloud.githubusercontent.com/assets/1490076/19184406/3c5088a8-8c7d-11e6-9cfb-f978d817ed69.png)

![Uploading screenshot-1475828930.png…]()

**Comment by heymen61** [comment]
I'm experiencing similar problems since last fridays update. Distortion are mainly in upper left corner and sometimes spreading to a larger area making RDP life pretty hard.

**Comment by akallabeth** [comment]
@marrowsuck will have a look at it tomorrow. just to be sure, the artifacts are entirely gone with /gdi:sw?

**Comment by heymen61** [comment]
Yes, they are gone. So far seen no problem. Except that some colors seem to be different.

**Comment by heymen61** [comment]
Ok, now I've witnessed some distortions again. However it nothing compared to running without the /gdi:sw flag.

**Comment by marrowsuck** [comment]
Okay, they are not gone with /gdi:sw. However there's a lot less screen distortion and they only seem to be font related.

**Comment by akallabeth** [comment]
Ok, found it. I've missed the default initialisation of GlyphSupportLevel. Should have been disabled due to (lots) of drawing issues. Try running with ```-glyph-cache```, it should be a lot better then.

**Comment by heymen61** [comment]
Well for me it works I guess. Hopefully marrowsuck experiences the same. Thanks akallabeth. From your reaction I guess there might be some changes coming up concerning this issue. Or not ?

**Comment by akallabeth** [comment]
@heymen61 Good to know. Will create a pull to (properly) disable glyph cache for the time being.

**Comment by marrowsuck** [comment]
Can confirm. No issues so far with -glyph-cache. Thanks!

**Comment by akallabeth** [comment]
Should be fixed with #3533

**Comment by akallabeth** [comment]
@heymen61 Are you referring to the cursor colors? Looks like there is a color format mixup with that left.

**Comment by heymen61** [comment]
I'm a developer also and use Eclipse a lot also via RDP. It seems lately to have strange pink boxes around several areas of the java perspective. When selecting a specific field in the code it outlines all occurences thereof in a vertical bar. Normally all occurences are mark with little yellow rectangles, but they have also have a pink border lately. I'm not experiencing real problems, but the look has changed since last week's update.

**Comment by akallabeth** [comment]
@heymen61 interesting. Could you give some more details? Just tried with eclipse neon (java) on windows 10 and I could not see any of that. (16bit color depth)

**Comment by marrowsuck** [comment]
Hi there! The distortions are not entirely gone. Greyed out text is displayed differently and colors in the cmd.exe are sometimes inverted.

**Comment by bmiklautz** [comment]
@marrowsuck could you re-try with the latest master?

**Comment by akallabeth** [comment]
@heymen61 Could you test only with ```/gdi:sw```>, ```/gdi:hw``` still has distortions with ```+glyph-cache``` but I couldn't reproduce them  when disabling it.

**Comment by marrowsuck** [comment]
Here is the side-by-side comparison. First one with /gdi:hw, second with /gdi:sw. The cmd-glitch only happens sometimes.
![screenshot-1476552642](https://cloud.githubusercontent.com/assets/1490076/19412130/2eb27f2e-930f-11e6-8095-67b2b0077679.png)
![screenshot-1476552662](https://cloud.githubusercontent.com/assets/1490076/19412131/33de1468-930f-11e6-8ee3-2e9e60268fc9.png)

**Comment by marrowsuck** [comment]
And I get these color distortions with `/gdi:sw`.
![screenshot-1476554839](https://cloud.githubusercontent.com/assets/1490076/19412334/da51ddbc-9313-11e6-9770-37748837d578.png)

**Comment by akallabeth** [comment]
@marrowsuck Interesting. Could you find out which ROP are responsible for that? A logging entry in ```gdi_BitBlt``` should do the trick. I've not seen such glitches when testing locally, so maybe I'm missing something.

**Comment by akallabeth** [comment]
@marrowsuck Still failing to reproduce your specific issue. Could you give some example setup to reproduce?

**Comment by marrowsuck** [comment]
Hello there! Sorry for the delay.
I have compiled freerdp against the latest checkout from ffmpeg-git. RDP-Hosts are Windows 7 and Windows Server 2008.
[Uploading freerdp_log.txt…]()

**Comment by ettorer** [comment]
Hello,
I compiled the master of 27th Jannuary 2017 under Linux 32bit. I'm connecting to a Windows server 2008 R2 with a simple command line (xfreerdp /cert-ignore /u:ettorer /d:flyd /v:<ip>). The menus disabled options are shown as the left side of the image.
The problem disappears (right side of image) with /gdi:sw or disabling the cache with -bitmap-cache.  
![xfreerdp-gdi-problem-w2k8r2](https://cloud.githubusercontent.com/assets/1669856/22436849/070ca182-e726-11e6-98bb-ef313b11a244.PNG)
