### ISSUE TITLE
several disconnection

### ISSUE THREAD

**Issue by dreamadv** [FreeRDP/FreeRDP#3528]
We have some problem with several 3-6 disconnection at work day 8h with on current Master, with stable-1.1 this problem don't exist. We use client on debian 8 and connect to our Windows 2003 x32 server.

Debug log:
[15:13:30:568] [5887:5889] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[15:13:30:649] [5887:5889] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[15:13:30:649] [5887:5889] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
[15:13:30:649] [5887:5889] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[15:13:35:703] [5887:5889] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[15:13:35:704] [5887:5889] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure

**Comment by akallabeth** [comment]
@dreamadv Without some information it is hard to tell. Command line and client? Maybe also a git revision would be very helpful.

**Comment by dreamadv** [comment]
xfreerdp /gdi:hw /rfx /v:192.168.35.1 /w:1200 /h:900 /bpp:32 /kbd:0x00000419 +compression +clipboard +fonts -window-drag -menu-anims -themes +auto-reconnect +heartbeat -glyph-cache 

git version master - 16 aug 2016

**Comment by akallabeth** [comment]
@dreamadv did you check if connections succeed when expilcitly connecting with ```/sec:<rdp|tls|nla|ext>```?

**Comment by bmiklautz** [comment]
@dreamadv on the first glance this feels more like a timeout/networking issue where FreeRDP doesn't like the network behavior for any reason and disconnects. How are you connected to your server?

**Comment by dreamadv** [comment]
@akallabeth i do some additional test of it. @bmiklautz we connected to cloud server (VMWare) via VPN (Kerio Control tunnel) it can be some net lag for 1-2 sec ping(don't response) timeout. May be exist some defference in network settings between source code revision, because we don't have disconnects on stable 1.1 revision. And can't use stable 1.1 with out of sync numlock bug.

**Comment by dreamadv** [comment]
@bmiklautz ok we will test same copy of VM in LAN, i will post result some later.

**Comment by bmiklautz** [comment]
@dreamadv thanks!

**Comment by dreamadv** [comment]
So long time we continue use 1.1 freerdp version, in last git master problem still exist. May be we can produce some additional debug info of this problem ? For more information of this problem ? Some custom modules with additional console log ? 1.1 now is too old to use and has annoying bugs like num lock out sync and some graphics problems.

**Comment by akallabeth** [comment]
Any news on this one? Some test machine would be nice to see what is goning on, or at least some feedback on current nightlies.

**Comment by akallabeth** [comment]
Can no longer reproduce (and NLA has changed significantly).
Closing, if still an issue create a new one.
