### ISSUE TITLE
Implement Clipboard filesharing

### ISSUE THREAD

**Issue by lanoxx** [FreeRDP/FreeRDP#3532]
Opening this issue here as a prerequirement of this issue FreeRDP/Remmina/issues/323

I would like to ask that freedrp implements support for file sharing via the clip board. This is a feature that has long been possible in the windows implementation.

I want to take any file on Windows and copy it to the clip board (e.g. with CTRL+C) and then I want to paste it on Linux (e.g. into nautilus). This should also work the other way around.

I am not sure whats required to support this but it would be pretty awesome if this worked. This feature it currently the only reason why I still keep a Windows 10 VM around, because I often need to copy a file and using FTP or some other tool is often to complicated, when I just want to quickly copy a single file. Besides I have many remote windows servers where no FTP or other file sharing services are installed.

**Comment by akallabeth** [comment]
duplicate
