### ISSUE TITLE
android-build-freerdp.sh  dont work on mac os 

### ISSUE THREAD

**Issue by masterbender** [FreeRDP/FreeRDP#3549]
./scripts
android-build.common.sh
android-build-openh264.sh
android-build-openssl.sh

they are using the -r parameter on the cp command , it should be -R (capital) to work on mac 

also osX it not capable of using realpath -> workaround : 
$ git clone https://github.com/harto/realpath-osx.git
$ cd realpath-osx
$ make
$ sudo make install

**Comment by bmiklautz** [comment]
@masterbender thanks for the feedback. But the android build scripts are mainly targeted on linux (I don't think we ever used them on OSX) as we use them for our CI builds. We don't plan to "port" them to OS X. But we would gladly accept a pull request that does so ;)
