### ISSUE TITLE
Using api in other application with CanvasID

### ISSUE THREAD

**Issue by aliufukyaman** [FreeRDP/FreeRDP#3550]
Hi to all.

I looked around the api but couldn't find any answer to my question, so asking you.
I would like to use the FreeRdp built in C language and use it in my Java application. Occasionally I prefer it for some reason and perform it by providing a CanvasID to the application, thus a "C/C++" program can be run as an external executable and give the needed screen to my application. 
I need this to do also but couldn't find the related part in code if it exist, I am not that familiar with WINAPI.

If is it possible to handle this issue in such a way, could you kindly point the way ? 

Thanks in advance.

**Comment by akallabeth** [comment]
you can have a look at the android client jni api if that helps

**Comment by akallabeth** [comment]
closing as answered. if you have more specific issues ask on the mailing list or via IRC
