### ISSUE TITLE
Order update with smart-sizing error after the color conversion fix

### ISSUE THREAD

**Issue by realjiangms** [FreeRDP/FreeRDP#3551]
This might be another regression, but I can't find out why.
Tested with Virtualbox 5.0.26, winXP, autocad2010.
See following picture, xfreerdp command line is:
xfreerdp /v:192.168.3.21:3394 /cert-ignore /bpp:32 /gdi:hw /smart-sizing:800x600
Actual guest screen resolution is 1024x768

![image](https://cloud.githubusercontent.com/assets/4299660/19317295/27c33116-90d7-11e6-91c0-998890033621.png)

It looks like, some image/order is updated to scaled windows instead of the primary pixmap.

The issue doesn't exist before Oct 6 color conversion fix.

The issue doesn't exist with gdi:sw
The issue doesn't exist without smart-sizing
The issue doesn't exist if I disable NEG_GLYPH_INDEX_INDEX NEG_FAST_INDEX_INDEX NEG_FAST_GLYPH_INDEX in xf_pre_connect

**Comment by akallabeth** [comment]
@realjiangms Does this issue persist when running with ```-glyph-cache```? If not it is #3539

**Comment by realjiangms** [comment]
The issue still exists with -glyph-cache.

xfreerdp /v:192.168.3.21:3394 /smart-sizing:800x600 /bpp:32 /gdi:hw -glyph-cache

**Comment by akallabeth** [comment]
Is this still an issue with current nightlies / release candidates?

**Comment by realjiangms** [comment]
@akallabeth I'll try it with latest 2.0.0-rc2

**Comment by akallabeth** [comment]
Glyph cache is disabled by default now.
