### ISSUE TITLE
Open ssl issue 

### ISSUE THREAD

**Issue by shattars3d** [FreeRDP/FreeRDP#3555]
I am building the FreeRDP iOS client, i getting no where past:
Xcode 8

test-Mac-Pro:FreeRDP-master mac$ ./scripts/OpenSSL-DownloadAndBuild.command 
shasum: openssl-1.0.2h.tar.gz: 
Downloading OpenSSL Version 1.0.2h ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5150k  100 5150k    0     0  2469k      0  0:00:02  0:00:02 --:--:-- 2470k
Unpacking OpenSSL ...

Building openssl-1.0.2h for iPhoneSimulator 10.0 i386 (min SDK set: 9.3)
 Please wait ... Done. Build log saved in BuildLog.darwin-i386.txt
Building openssl-1.0.2h for iPhoneSimulator 10.0 x86_64 (min SDK set: 9.3)
 Please wait ... mac-Mac-Pro:FreeRDP-master mac $ 

Stops there, doesn't compile rest of the build.

A week ago it working great, latest commits are causing build issues...

**Comment by akallabeth** [comment]
@shattars3d Could you check your build log ```BuildLog.darwin-i386.txt``` for issues? It may also help to remove previous build files before running the script.

**Comment by shattars3d** [comment]
@akallabeth  Hey, where do i locate that text file BuildLog.darwin-i386.txt? Also how do i remove the previous build files?

**Comment by shattars3d** [comment]
@akallabeth  Hey, i have checked the BuildLog.darwin-x86_64.txt text file, this is the error


clang: warning: using sysroot for 'MacOSX' but targeting 'iPhone'
ld: building for iOS simulator, but linking against dylib built for OSX (/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libSystem.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang: **error**: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [link_app.] **Error** 1
make[1]: *** [openssl] **Error** 2
make: *** [build_apps] **Error** 1
**error** with make

**Comment by akallabeth** [comment]
@shattars3d Check your setting of ```SDK_VERSION``` , ```CROSS_TOP```, ```CROSS_SDK``` and ```CC``` maybe something with autodetection is failing on your setup.

**Comment by shattars3d** [comment]
@akallabeth  Where do configure these settings? SDK_VERSION , CROSS_TOP, CROSS_SDK and CC

**Comment by akallabeth** [comment]
edit the build script and check the function compiling the code.

**Comment by shattars3d** [comment]
@akallabeth fixed the issue, had to update macports and open ssl 
Also, in OpenSSL-DownloadAndBuild.command you should make MIN_SDK_VERSION="", no version number.
