### ISSUE TITLE
Unsupported ROP3: 0x00E20746 when starting very old windows apps

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#3558]
version: current master of 15.10.2016
client: xfreerdp on openSUSE 42.1
remote: tested with Windows7 Prof. and Windows Server 2008

When I start very old windows programs I get "Unsupported ROP3: 0x00E20746".
I guess this is related to a rendering problem with menu points that should be "greyed out", but get painted distorted. See the attached screen shot for an example.
![sqladv_screenshot](https://cloud.githubusercontent.com/assets/12591752/19408211/ee762188-92b7-11e6-92e0-b867491297ef.png)

**Comment by akallabeth** [comment]
@hendwolt Try ```/gdi:sw```, this implements all ROP. ```/gdi:hw``` does not.

**Comment by hendwolt** [comment]
That works for me, thanks!
