### ISSUE TITLE
Android client blocked

### ISSUE THREAD

**Issue by uplusplus** [FreeRDP/FreeRDP#3564]
static int android_freerdp_run(freerdp* instance){
......
WLog_INFO(TAG, "Prepare shutdown...");

	if (async_input && inputThread)
	{
		WaitForSingleObject(inputThread, INFINITE);
		CloseHandle(inputThread);
	}

WaitForSingleObject blocked after logoff.

parameters:
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[0]=LibFreeRDP
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[1]=/gdi:sw
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[2]=/v:10.1.63.124
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[3]=/port:3389
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[4]=/u:admin
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[5]=/p:123456
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[6]=/size:1280x720
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[7]=/bpp:32
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[8]=/rfx
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[9]=/gfx
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[10]=+wallpaper
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[11]=+window-drag
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[12]=+menu-anims
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[13]=+themes
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[14]=+fonts
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[15]=+aero
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[16]=-glyph-cache
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[17]=+async-channels
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[18]=-async-transport
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[19]=+async-input
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[20]=+async-update
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[21]=/clipboard
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[22]=/audio-mode:0
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[23]=/sound
10-17 08:50:03.360 31459-31613/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=31459:tid=5dcc3460] - arg[24]=/log-level:OFF

build type:debug with GPROF

**Comment by akallabeth** [comment]
@uplusplus Deactivate async-input for the time being. Async modes need some love.

**Comment by uplusplus** [comment]
@akallabeth without async-input,it will automatically stop:
10-18 02:41:18.570 13602-13602/com.freerdp.afreerdp I/PROFILING: start profiling shared library libfreerdp-android.so
10-18 02:41:18.580 13602-13602/com.freerdp.afreerdp I/PROFILING: process 'libfreerdp-android.so', base = 0x0, lo = 0x5d717000, hi = 0x5d724000
10-18 02:41:18.580 13602-13602/com.freerdp.afreerdp I/PROFILING: process 'libfreerdp-android.so', base = 0xc000, lo = 0x5d724000, hi = 0x5d725000
10-18 02:41:18.580 13602-13602/com.freerdp.afreerdp I/PROFILING: process 'libfreerdp-android.so', base = 0xd000, lo = 0x5d725000, hi = 0x5d726000
10-18 02:41:18.580 13602-13602/com.freerdp.afreerdp I/PROFILING: Profile libfreerdp-android.so, pc: 0x5d717000-0x5d724000, base: 0x0
10-18 02:41:18.590 13602-13602/com.freerdp.afreerdp I/PROFILING: Maximum number of samples per second: 100
10-18 02:41:18.590 13602-13602/com.freerdp.afreerdp I/PROFILING: Specified frequency: 200
10-18 02:41:18.590 13602-13602/com.freerdp.afreerdp I/PROFILING: Specified sample rate is too large, using 100
10-18 02:41:18.600 13602-13602/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Screen Resolution: fitscreen
10-18 02:41:18.630 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[0]=LibFreeRDP
10-18 02:41:18.630 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[1]=/gdi:sw
10-18 02:41:18.630 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[2]=/v:10.1.63.124
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[3]=/port:3389
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[4]=/u:admin
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[5]=/p:123456
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[6]=/size:1280x720
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[7]=/bpp:32
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[8]=/rfx
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[9]=/gfx
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[10]=+wallpaper
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[11]=+window-drag
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[12]=+menu-anims
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[13]=+themes
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[14]=+fonts
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[15]=+aero
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[16]=-glyph-cache
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[17]=+async-channels
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[18]=+async-transport
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[19]=-async-input
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[20]=+async-update
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[21]=/clipboard
10-18 02:41:18.640 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[22]=/audio-mode:0
10-18 02:41:18.650 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[23]=/sound
10-18 02:41:18.650 13602-9909/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5df39418] - arg[24]=/log-level:OFF
10-18 02:41:18.650 13602-9910/com.freerdp.afreerdp I/com.freerdp.client.common.cmdline: [pid=13602:tid=5dfc5ad8] - loading channel rdpdr
10-18 02:41:18.650 13602-9910/com.freerdp.afreerdp I/com.freerdp.client.common.cmdline: [pid=13602:tid=5dfc5ad8] - loading channel rdpsnd
10-18 02:41:18.650 13602-9910/com.freerdp.afreerdp I/com.freerdp.client.common.cmdline: [pid=13602:tid=5dfc5ad8] - loading channel cliprdr
10-18 02:41:18.650 13602-9910/com.freerdp.afreerdp I/com.freerdp.client.common.cmdline: [pid=13602:tid=5dfc5ad8] - loading channel drdynvc
10-18 02:41:18.650 13602-9910/com.freerdp.afreerdp V/GlobalApp: OnPreConnect
10-18 02:41:18.700 13602-13602/com.freerdp.afreerdp V/SessionView: 0x0
10-18 02:41:18.700 13602-13602/com.freerdp.afreerdp V/SessionView: 0x0
10-18 02:41:20.400 13602-9910/com.freerdp.afreerdp D/dalvikvm: GC_FOR_ALLOC freed 389K, 41% free 11527K/19260K, paused 14ms, total 14ms
10-18 02:41:20.400 13602-9910/com.freerdp.afreerdp I/dalvikvm-heap: Grow heap (frag case) to 14.827MB for 3686416-byte allocation
10-18 02:41:20.410 13602-9910/com.freerdp.afreerdp D/dalvikvm: GC_FOR_ALLOC freed <1K, 22% free 15127K/19260K, paused 14ms, total 14ms
10-18 02:41:20.410 13602-9910/com.freerdp.afreerdp V/GlobalApp: OnConnectionSuccess
10-18 02:41:20.420 13602-9910/com.freerdp.afreerdp E/com.freerdp.client.android: [pid=13602:tid=5dfc5ad8] - Failed to check FreeRDP file descriptor
10-18 02:41:20.420 13602-9910/com.freerdp.afreerdp I/com.freerdp.client.android: [pid=13602:tid=5dfc5ad8] - Prepare shutdown...
10-18 02:41:20.420 13602-13602/com.freerdp.afreerdp V/FreeRDP.SessionActivity: OnConnectionSuccess
10-18 02:41:20.420 13602-13602/com.freerdp.afreerdp V/FreeRDP.SessionActivity: bindSession called
10-18 02:41:20.420 13602-9910/com.freerdp.afreerdp V/GlobalApp: OnDisconnecting
10-18 02:41:20.430 13602-9910/com.freerdp.afreerdp V/GlobalApp: OnDisconnected
10-18 02:41:20.440 13602-13602/com.freerdp.afreerdp V/SessionView: 1280x720
10-18 02:41:20.440 13602-13602/com.freerdp.afreerdp V/SessionView: 1280x720
10-18 02:41:20.460 13602-13602/com.freerdp.afreerdp V/FreeRDP.SessionActivity: OnDisconnected
10-18 02:41:20.480 13602-13602/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onPause
10-18 02:41:20.490 13602-13602/com.freerdp.afreerdp V/HomeActivity: HomeActivity.onResume
10-18 02:41:20.520 13602-13602/com.freerdp.afreerdp W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0d003f}
10-18 02:41:20.520 13602-13602/com.freerdp.afreerdp W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0d0042}
10-18 02:41:20.520 13602-13602/com.freerdp.afreerdp W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0d003f}
10-18 02:41:20.530 13602-13602/com.freerdp.afreerdp W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0d0042}
10-18 02:41:20.530 13602-13602/com.freerdp.afreerdp W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0d003f}
10-18 02:41:20.530 13602-13602/com.freerdp.afreerdp W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0d0042}
10-18 02:41:20.880 13602-13602/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onStop
10-18 02:41:20.880 13602-13602/com.freerdp.afreerdp V/FreeRDP.SessionActivity: Session.onDestroy
10-18 02:41:20.890 13602-13602/com.freerdp.afreerdp I/PROFILING: Sampling frequency: 100
10-18 02:41:20.890 13602-13602/com.freerdp.afreerdp I/PROFILING: moncleanup, writing output to /sdcard/gmon.out

**Comment by akallabeth** [comment]
@uplusplus Does this also happen without gprof? Profiling is only meant to be used to get a estimate of cost of functions, not for flawless operation.

**Comment by uplusplus** [comment]
@akallabeth It works after I updated the code. Thanks for your help.

**Comment by akallabeth** [comment]
Ok, glad it worked.
