### ISSUE TITLE
How to install freerdp under linux 11SP3

### ISSUE THREAD

**Issue by deity6473** [FreeRDP/FreeRDP#3573]
Hi All,

I tried to install freerdp under linux 11SP3 but got many dependency packages there, and didn`t find corrent dependencies package, how can i install it properly: 

linux:~ # rpm -ivh freerdp-nightly-2.0-0+0-20161020033818.252-1.gitf5a6645.x86_64.rpm
error: Failed dependencies:
        libc.so.6(GLIBC_2.14)(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libc.so.6(GLIBC_2.15)(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libcrypto.so.1.0.0()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libgsm.so.1()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libgstapp-1.0.so.0()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libgstbase-1.0.so.0()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libgstreamer-1.0.so.0()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libgstvideo-1.0.so.0()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libjpeg.so.8()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libjpeg.so.8(LIBJPEG_8.0)(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libpulse.so.0()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libpulse.so.0(PULSE_0)(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        libssl.so.1.0.0()(64bit) is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64
        rpmlib(TildeInVersions) <= 4.10.0-1 is needed by freerdp-nightly-2.0-0+0~20161020033818.252~1.gitf5a6645.x86_64

**Comment by bmiklautz** [comment]
@deity6473 I'm sorry but the nightly packages don't support SLES. You will need to build/package it on yourself.
