### ISSUE TITLE
CommandLine Parser buggy

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#3574]
- Channels can not provide extensions without modifications in libfreerdp core
- Parser is not checking for duplicates
- Option descriptions are out of date and would need some more detailed explanations

**Comment by hardening** [comment]
Lot of work has been done on the cmdline parser, shall we close the issue ?

**Comment by akallabeth** [comment]
yes, most of the stuff has been fixed (except that we still have a custom parser)
