### ISSUE TITLE
RemoteApp Cisco Jabber moving out of screen when resized

### ISSUE THREAD

**Issue by erenoglu** [FreeRDP/FreeRDP#3575]
Hi, it's a tough bug to describe. I have the following multi-monitor configuration:

```
Screen 0: minimum 8 x 8, current 1920 x 2160, maximum 32767 x 32767
eDP1 connected 1440x960+0+1200 (normal left inverted right x axis y axis) 250mm x 170mm
HDMI1 connected primary 1920x1200+0+0 (normal left inverted right x axis y axis) 540mm x 350mm
```

eDP1 is below HDMI1 in physical layout.  I start Cisco Jabber in a virtual machine with this:
`xfreerdp "/app:||jabber" /v:xxxx /u:xxxxx /p:xxxx +fonts +clipboard /sound:sys:pulse /microphone:sys:pulse -themes -wallpaper -grab-keyboard /multimon /monitors:1`

The /multimon and /monitors:1 are parameters I tried to fix the problem with no solution, they do not seem to have any effect on RemoteApp mode, but they work for a full Desktop session. 

What happens is that Cisco Jabber starts, sometimes in the top HDMI1 monitor, sometimes in below eDP1 monitor. If it starts on HDMI1, I move it down to eDP1. But if I try to resize its window using top line of the window (other corners or sides do not work!), the window is resized and becomes taller, but once I leave the mouse button, it starts to shrink back to its original size and also move slowly to the right, and then dissapears from the screen. It is not possibility to recover this window to a "visible" area anymore. The window sits there, invisible, as I can see it from the Gnome3 application switcher (ie mouse to top left hot corner). 

I believe it moves to the space between the 1440 width of eDP1 and the 1920 width of  space, that 480x960 pixel invisible area.

I would be happy if there was at least a way to limit RemoteApp windows to a monitor, using the /multimon and /monitors:1 parameters... Maybe then the Jabber window would not escape :)

**Comment by erenoglu** [comment]
I also tried to set /size: parameters, /w: parameter to limit available width, those didn't work neither. 
Btw, while the window is moving to the right to dissapear from view, if I catch it with the mouse, I can pull it back to where I want, until the next time it starts to move.

**Comment by erenoglu** [comment]
Here is the Window moving out of view. I managed to capture a video of it: 

[window_moving_out_of_view.zip](https://github.com/FreeRDP/FreeRDP/files/548757/window_moving_out_of_view.zip)

and here is the picture of the hidden window in Gnome Zoom out mode, after it's gone:

![20161024_232429](https://cloud.githubusercontent.com/assets/2230575/19660618/9755999c-9a41-11e6-8de6-454aa02c35f6.jpg)

Hope it's more clear.

**Comment by akallabeth** [comment]
Is this still an issue with current nightly or release candidates?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
