### ISSUE TITLE
Android “Bitmap too large to be uploaded into a texture”

### ISSUE THREAD

**Issue by fengqi-wang** [FreeRDP/FreeRDP#3582]
I'm having difficulty to show large remote screens to my local 1080p monitor, with the error "Bitmap too large to be uploaded into a texture". and am curious there is no special code in the Android Freerdp client to handle large Session Bitmap?

**Comment by akallabeth** [comment]
limitations are device specific, but there are is currently nothing implemented. resizing the image before upload may help but it costs performance...
