### ISSUE TITLE
clear_decompress failure

### ISSUE THREAD

**Issue by LemonZou** [FreeRDP/FreeRDP#3583]
I check out the master git freerdp source code and compiled and run on my ubuntu 16.04 AMD64 PC or ubuntu 14.04 ARMHF platform, the server is win8 or win10, the command line is:
-sec-nla /rfx /rfx-mode:video /codec-cache:rfx /gfx:AVC420 /gfx-h264:AVC420
the error is:
[11:18:29:885] [6180:6189] [ERROR][com.freerdp.gdi] - clear_decompress failure: -1

I follow the code, the error is at clear_decompress_bands_data@clear.c:
			if (vBarEntry->count != vBarHeight)
				return FALSE;
Because there will be more than one surface, so clear codec instance will be more than one, 
so there will be more than one VBarStorage array and many VBarStorageCursor, when 
SHORT_VBAR_CACHE_MISS update VBarStorage, the data in different place, but the server
send the vBarIndex is sequential order, so when VBAR_CACHE_HIT, we can't get the correct
VBarStorage place by vBarIndex, so vBarEntry->count != vBarHeight and clear_decompress.
My understanding is correct?

**Comment by akallabeth** [comment]
Duplicates #3527
