### ISSUE TITLE
Unable to build libraries for Android API 15

### ISSUE THREAD

**Issue by m-georgi** [FreeRDP/FreeRDP#3585]
Im an unable to use the freerdp-client library on a device running Android API Version 15.
I changed the NDK_TARGET to 15 in scripts/android-build.conf and disabled all BUILD_ARCHs apart from armeabi-v7a.
After building the libraries using scripts/android-build-freerdp.sh and the APK using Android Studio / Gradle I get the following errors upon startup of aFreeRDP:

```
D/dalvikvm: Trying to load lib /data/data/com.freerdp.afreerdp/lib/libwinpr.so 0x41026090
E/LibFreeRDP: Failed to load library winpr: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1285]:    37 cannot locate '__aeabi_ldiv0'...
V/LibFreeRDP: Trying to load library freerdp from LD_PATH: /vendor/lib:/system/lib
D/dalvikvm: Trying to load lib /data/data/com.freerdp.afreerdp/lib/libfreerdp.so 0x41026090
E/LibFreeRDP: Failed to load library freerdp: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1936]:    37 could not load needed library 'libwinpr.so' for 'libfreerdp.so' (find_library[1199]:    37 'libwinpr.so' failed to load previously)
V/LibFreeRDP: Trying to load library freerdp-client from LD_PATH: /vendor/lib:/system/lib
D/dalvikvm: Trying to load lib /data/data/com.freerdp.afreerdp/lib/libfreerdp-client.so 0x41026090
E/LibFreeRDP: Failed to load library freerdp-client: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1936]:    37 could not load needed library 'libfreerdp.so' for 'libfreerdp-client.so' (find_library[1199]:    37 'libfreerdp.so' failed to load previously)
V/LibFreeRDP: Trying to load library freerdp-android from LD_PATH: /vendor/lib:/system/lib
D/dalvikvm: Trying to load lib /data/data/com.freerdp.afreerdp/lib/libfreerdp-android.so 0x41026090
E/LibFreeRDP: Failed to load library freerdp-android: java.lang.UnsatisfiedLinkError: Cannot load library: link_image[1936]:    37 could not load needed library 'libfreerdp-client.so' for 'libfreerdp-android.so' (find_library[1199]:    37 'libfreerdp-client.so' failed to load previously)
```

Am I missing something that I should be doing to build libwinpr correctly?
These errors occurr both on an actual device with API 15, as well as in an emulator.

**Comment by akallabeth** [comment]
@m-georgi Should work like that.
 * Are you sure the library was rebuild with the appropriate flags? (e.g. did you remove old build files first) 
 * Does this also occur when using ```armeabi``` target?

**Comment by akallabeth** [comment]
Master is working, tested the following:
* compiled master (f910bbe7b4d0d6badae4952c4a4613371329b802)
* Tested on x86 and armeabi-v7a targets
* without modification (minimum API 14)
* with API 16 (native and build.gradle modified)

All combinations worked just as expected when starting on device and in emulator.
Therefore closing this issue.

**Comment by m-georgi** [comment]
Alright, thanks for looking into it. 
I will try to find out what is going wrong on my system.
