### ISSUE TITLE
Clipboard not working! 

### ISSUE THREAD

**Issue by mikhaXD** [FreeRDP/FreeRDP#3586]
Windows Build 266 from here https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=windows/lastStableBuild/ , clipboard not working, or working only in one side, from my PC to a RDP, but from rdp to my pc - not working. 
Tried many times at different PCs and OS, (from win7 to server 2016 ) - that same result. Without correct clipboard redirection freerdp client is useless. 

Fix it please. Thanks.

**Comment by akallabeth** [comment]
Working with 3c7cc555a5a5f02366918be7eb935bb1f22115ef
