### ISSUE TITLE
Reopening multiple apps not working - consulting opportunity

### ISSUE THREAD

**Issue by Antonyaa** [FreeRDP/FreeRDP#3587]
Hi there:

I am reopening this issue:

https://github.com/FreeRDP/FreeRDP/issues/3032

in the hope of finding someone who would be interested in solving this problem on a consulting basis. Thank you for pointing me in the right direction.  

Regards,
Antony

**Comment by akallabeth** [comment]
Closing this for being stale, we're tracking the issue as #498
