### ISSUE TITLE
Fullscreen mode doesnt work with RPI 3

### ISSUE THREAD

**Issue by jaiabishek** [FreeRDP/FreeRDP#3588]
i have install freerdp in my RPI 3 using
apt-get install freerdp
installed version: 1.1.0-beta1
os:  raspbian-jessie

when i try to connect an session using /f nothing happens, without /f i am successfully able to connect the session.
can someone help me out.

**Comment by Nikita352** [comment]
Hello 
Do you have solved your issue? 
I have same issue and when I try to connect an session /f nothing happens. Full Screen Mode works only a session is opened without this option and push on Ctrl + Alt + Enter for put in Full Screen.

Many Thanks

**Comment by akallabeth** [comment]
unfortunately raspberry pi packages are quite old. we currently do not provide builds for arm based systems, so the only way is compiling from source. 
there is an update due for debian sid, so you can also build the source package.

**Comment by akallabeth** [comment]
Closing for now, reopen if the bug is still there on newer versions.

**Comment by LouisOuellet** [comment]
Hi,
I am running version 2.0.0-dev5 and I am also having issues with fullscreen on a Pi 4. If I use a multi monitor setup, no problem. But if I use a single monitor. Then nope. It opens the connection minimized at the bottom. and not in fullscreen.

Any idea?
