### ISSUE TITLE
Trouble with scrolling-bars

### ISSUE THREAD

**Issue by Guichard-informatique** [FreeRDP/FreeRDP#3589]
we have a problem with the full screen of the main window display, scrolling-bars appear on the sides of the window when it is minimized and maximized.
Can you help us ?
thank you

Version: wfreerdp.1.1
parameters: / f / v: host / p: test / u: test
windows 7

**Comment by akallabeth** [comment]
@Guichard-informatique 1.1 is a bit outdated, could you give the nightlies a try? They can be found for here: https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by akallabeth** [comment]
No feedback, closing.
Reopen if still an issue with current nightlies.
