### ISSUE TITLE
Drawing problem with software rendering

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#3592]
This may be a regression problem after Oct6 big update: running xfreerdp with /gdi:sw I have blue internal background of progress bar in Acronis Backup and Recovery 10 (under Win2008):

![freerdp mail ipablapieve it_012](https://cloud.githubusercontent.com/assets/5477803/20240643/c7615bfe-a91d-11e6-98b7-4911f0c4408a.png)

Using hardware rendering (without /gdi:sw) all is perfect:

![freerdp mail ipablapieve it_013](https://cloud.githubusercontent.com/assets/5477803/20240648/e0e37f9e-a91d-11e6-9dbc-b250f31d37e6.png)

**Comment by giox069** [comment]
Also on "File Server Resource Manager" of Windows Server 2008:

broken /gdi:sw
![freerdp mail ipablapieve it_014](https://cloud.githubusercontent.com/assets/5477803/20240975/57560da0-a927-11e6-89e7-6a58ee6e1687.png)

/gdi:hw
![freerdp mail ipablapieve it_016](https://cloud.githubusercontent.com/assets/5477803/20240977/66561822-a927-11e6-824a-bdbcf0b64cd0.png)

**Comment by akallabeth** [comment]
@giox069 Maybe there is another way to diagnose the issue. Could you add logging to the callbacks registered in ```gdi_register_update_callbacks``` and shortly connect to a screen where the color issue occurs? That could narrow down the issue.

**Comment by akallabeth** [comment]
@giox069 Does #3680 fix this issue for you?

**Comment by giox069** [comment]
The problem with "File Server Resource Manager", the second post, seems to be already fixed in the past.
And yes, #3680 or one of the last 3-5 days commits also fixes the main issue with Acronis TrueImage on 1st post.
Thank you! :+1:
