### ISSUE TITLE
Screen resize does resizes the frame but not the content

### ISSUE THREAD

**Issue by demarcop** [FreeRDP/FreeRDP#3596]
I had been using an older version and it worked great.  I just upgraded my command line switches to the new /size: type switches.   Now the frame is still the correct size, but the content in the frame is considerably smaller than the frame.

Thank you.

**Comment by akallabeth** [comment]
@demarcop Could you elaborate? A few details on your setup and versions used are required to answer your questions.

**Comment by demarcop** [comment]
yes.   so I'm doing a xfreerdp /d:domain /u:thatsme /p:'mypass' /size:1920x1025 /v:192.168.1.69
My current version is 1.1.0-beta1
I'm using my work computer as a server running windows.

and unfortunately, the usable screen is actually much smaller than the frame itself.    I'm sorry, but I don't know the prior version. but the command line prior was:
xfreerdp -d domain -u thatsme -p 'mypass' -g 1920x1025 192.168.1.69

and that used to work great.

If there's some other information, I can get for you... I will do that.

Thanks for looking into it.

**Comment by akallabeth** [comment]
1.1.0 is quite old, could you give our nightlies a try? 
https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by demarcop** [comment]
Works great again.   Thanks.
