### ISSUE TITLE
RemoteApp mouse pointer doesn't appear

### ISSUE THREAD

**Issue by juniorcesar** [FreeRDP/FreeRDP#3599]
Hello, I am using xfreerdp through terminal linux for open RemoteApp Application, but the mouse pointer appear with the X when I use the xfreerdp that I compiled. 
When I use the xfreerdp downloaded from the repository debian, works correctly.

I tried to open the application with the following code:

xinit /usr/local/bin/xfreerdp  /v:MYSERVER /p:PASSWORDH /u:USER /rfx /f +fonts /cert-ignore /app:"||MYAPPLICATION"

Somebody already saw this problem?

![cursor x](https://cloud.githubusercontent.com/assets/2955629/20348513/ece2c0d0-abec-11e6-9e1f-64edaba640f1.jpg)

**Comment by bmiklautz** [comment]
@juniorcesar when compiling did you have the Xcursor development files installed (libxcursor-dev on Debian/Ubuntu). My guess would be that you miss those.

**Comment by juniorcesar** [comment]
@bmiklautz  Thanks for your help!

I installed the libxcursor-dev, I compiled and tested but doesn't works.

In the moment that I set the parameters, I received that libxCursor was found. 

It is necessary set the same parameter for enable cursor?

![screen shot 2016-12-01 at 10 15 36](https://cloud.githubusercontent.com/assets/2955629/20794077/633a6998-b7b1-11e6-9d05-5a2a44150e7d.png)

**Comment by bmiklautz** [comment]
@juniorcesar two questions:
* does it work if you run it within a regular window manager (in a already started X session not with xinit)
* does it work if you don't use remote app (just connect to a server)

**Comment by juniorcesar** [comment]
@bmiklautz  Yes, works in both cases;

Only doesn't works, if I use with xinit.

**Comment by juniorcesar** [comment]
@bmiklautz I need to use the FreeRDP with xinit, because my devices doesn't have space in the disk to install window manager!

If I install the FreeRDP through repository Debian, works the mouse cursor. But the screen resolution doesn't works correctly. 

If I compile works fine the resolution. Only the X cursor thats not working!

Do you have some sugestion than be?

**Comment by akallabeth** [comment]
no feedback, closing.
