### ISSUE TITLE
How to disable sound?

### ISSUE THREAD

**Issue by jackmcmorrow** [FreeRDP/FreeRDP#3604]
Sorry if this is written somewhere else, but I have a problem where a certain program stops sound recording if I RDP into it with sound enabled (even Windows RDP does that). There's a console audio option in the help (-o) but not in the man page, so I searched the web and found no way to be certain sound is disabled in my rdp session.

Can anyone help a brother out?

**Comment by akallabeth** [comment]
@jackmcmorrow This is an issue tracker, not a support forum. Please use the mailing list or IRC for that.
