### ISSUE TITLE
Incomplete g_Subsystem_dummy initialization in libfreerdp/codec/h264.c

### ISSUE THREAD

**Issue by nebiun** [FreeRDP/FreeRDP#3606]
Hi,
Missing value for field Compress in H264_CONTEXT_SUBSYSTEM g_Subsystem_dummy structure.
I suggest to add the new dummy subroutine:

`static int dummy_compress(H264_CONTEXT* h264, BYTE** ppDstData, UINT32* pDstSize, 
UINT32 plane)   {  return -1; }`

and modify the initilization code as:

`static H264_CONTEXT_SUBSYSTEM g_Subsystem_dummy =
{
        "dummy",
        dummy_init,
        dummy_uninit,
        dummy_decompress,
        dummy_compress
};`

**Comment by bmiklautz** [comment]
See #3607  for details
