### ISSUE TITLE
h264 add libavcodec encoding support

### ISSUE THREAD

**Issue by nebiun** [FreeRDP/FreeRDP#3607]
Hi,
Missing value for field Compress in H264_CONTEXT_SUBSYSTEM g_Subsystem_libavcodec structure.
It is needs to add the code for the libavcodec_compress subroutine.

**Comment by akallabeth** [comment]
libavcodec encoding support is currently not implemented. Use OpenH264 for the time being.
Pull requests for a fix are welcome.
