### ISSUE TITLE
High Network usage over 40 mbit!

### ISSUE THREAD

**Issue by morphinz** [FreeRDP/FreeRDP#3609]
If network bandwidth is less than 40 mbit, xfreerdp dont work well.  
I tried 2015-11, 2016-07 and latest versions. I dont know exactly git commit but both version doesn't work good under 40mbit.  
The strange part is: i'm watching with network monitor it doesnt really use this much. Without Video & Audio Xfreerdp using under 1mbit for real!  
But when i limit network to under 40 mbit, just doesnt work well!!!  
*Microsoft can work with 3mbit with Video & Audio.  
  
I'm using Raspberry Pi 3 with this config:
```My config="-sec-nla /cert-ignore +compression /f /drive:test,/mnt +auto-reconnect +wallpaper -window-drag -menu-anims +fonts /multimedia /sound:sys:alsa,format:1,quality:high +async-input +async-update"```  
I tried almost all parameters, and only this config works if connection ++40mbit.
   
How can i pull usage under 5mbit? 

I will try anything for you, just let me know.

**Comment by akallabeth** [comment]
you need to use gfx or h264 options, but they are currently software decoding only. this means 720p at most on a raspberry, maybe less with smooth video.

**Comment by akallabeth** [comment]
@morphinz You may want to try #3619. It fixes some performance bottlenecks with ```/gfx``` related modes.

**Comment by bmiklautz** [comment]
@morphinz what server are you connecting too? - Depending on the codec and available bandwidth the server (tries) to choose a proper setting. If there is bandwidth available it will be used when required. However you can limit it by using the /network option (this might also influence the codec used from the server). The following options are available:
* modem
* broadband
* broadband-low
* broadband-high
* wan
* lan
* autodetect, auto, detect

If it's a rather resent server also try enabling the echo channel with /dvc:echo.

**Comment by realjiangms** [comment]
You can also try with /rfx. It has full quality image and should cost less than 20mbit

**Comment by akallabeth** [comment]
closing due to lack of feedback.

**Comment by roms2000** [comment]
I did some test with the big buck bunny 720p with VLC windowed (my screen is 1920x1080 or 1600x1200 or 1280x720) : 
 - with FreeRDP (linux) : network usage with a 2016 srv is near 17Mbit/s to 40Mbit/s with FreeRDP git.
 - If I test from a Win10 rdp client to the 2016 srv, network usage is between 5Mbit/s to 10Mbit/s.

The switch /network does not seem to do anything for me except with /network:modem where theme disappear, but network usage get the same.
command line used : 
```
/usr/local/bin/xfreerdp /sec:rdp /sound:sys:alsa,format:1,quality:high /gfx /v:myserver /u:myuser /p:mypass /f /network:broadband-low /multimedia:sys:alsa,decoder:gstreamer -bitmap-cache /dvc:echo
/usr/local/bin/xfreerdp /sec:rdp /sound:sys:alsa,format:1,quality:high /gfx /v:myserver /u:myuser /p:mypass /f /network:broadband-high /multimedia:sys:alsa,decoder:gstreamer -bitmap-cache /dvc:echo
/usr/local/bin/xfreerdp /sec:rdp /sound:sys:alsa,format:1,quality:high /gfx /v:myserver /u:myuser /p:mypass /f /network:wan /multimedia:sys:alsa,decoder:gstreamer -bitmap-cache /dvc:echo
/usr/local/bin/xfreerdp /sec:rdp /sound /gfx /v:myserver /u:myuser /p:mypass /f 
/usr/local/bin/xfreerdp /sec:rdp /sound /rfx /v:myserver /u:myuser /p:mypass /f 
```

I also tried with a limited network bandwidth (10Mb/s) and it's using all the available link, video lag but it's nearly ok, sound is good.

Could FreeRDP use less bandwidth ? If yes, how can we do ?

**Comment by BloodyIron** [comment]
I'm seeing substantial bandwidth usage on my end too, and I'm not even doing audio redirect. I'm just scrolling up and down a graphically rich page and the xrdp server is sending at 60mbit at peak. Considering the content that's ludicrous how much bandwidth is being used. Such a default is completely intolerable for multi-user implementations, especially over the internet!

I am unsure if it's the client, or server, but so far I have not found a way to cut down the bandwidth used.

**Comment by hardening** [comment]
@BloodyIron what do you get when you connect with mstsc instead of xfreerdp ?

**Comment by BloodyIron** [comment]
I get a similar amount of bandwidth usage. I haven't been able to find any parameters to bring the bandwidth usage down, so at some point here I'm going to revisit what protocol version is being used on the server-end (xrdp + x11rdp).

What kind of bandwidth usage are you folks seeing? When you scroll down a graphically rich page (images, not videos).

The bandwidth used doesn't seem to change much between bit rate (bpp) or resolution.

**Comment by morphinz** [comment]
I already tried everything guys, There is no  solution...  
Now I'm using Spice.  Redirection and Video quality better and spice can work under 1 mbit.   
  
BTW The config (coneection parameters) was the best quality & Network usage.
config="-sec-nla /cert-ignore +compression /f +auto-reconnect +wallpaper -window-drag -menu-anims +fonts /multimedia /sound:sys:alsa,format:1,quality:high +async-input +async-update"

Also you can try these 2 config either.   
# OK_config="-sec-nla /cert-ignore +fonts +compression /f +auto-reconnect /gdi:sw +wallpaper -window-drag -menu-anims +fonts +glyph-cache +async-channels +async-transport +async-input +async-update /clipboard /audio-mode:0 /sound /log-level:INFO"

# xfree_git-config="-sec-nla /cert-ignore +fonts +compression /f +auto-reconnect /gdi:sw +wallpaper -window-drag -menu-anims +fonts +glyph-cache +async-channels +async-transport +async-input +async-update /log-level:INFO"

**Comment by hardening** [comment]
@BloodyIron so I guess this is an issue that should be addressed to the xrdp project then

**Comment by realjiangms** [comment]
For test from @roms2000, it is expected to have 17Mbit/s to 40Mbit/s network usage when connecting to win2016 or very updated win10 with xfreerdp because /gfx doesn't actually take effect and it is fail back to clear codec or RFX.

It seems win2016 removed support for AVC420 in gfx, but we can enable AVC444 with proper group policy.

Try /gfx:AVC444 instead of /gfx. If it still use 17-40Mbit/s, try to consult some documentation from $MS to enable AVC444 encoding.

**Comment by BloodyIron** [comment]
Considering all this bandwidth usage, how exactly is this normally achieved for lots of people accessing over the internet?

**Comment by moiseiisus** [comment]
Is there a fix for this issue? Anyone solved this problem?

**Comment by akallabeth** [comment]
@moiseiisus properly configure your server so that it does not send plain bitmap data ;)
other than that, use `/gfx:avc444 /rfx /network:auto` to help the server decide bandwidth and quality.

**Comment by moiseiisus** [comment]
> @moiseiisus properly configure your server so that it does not send plain bitmap data ;)
> other than that, use `/gfx:avc444 /rfx /network:auto` to help the server decide bandwidth and quality.

So, what should I do to configure my server 2012R2/2016 properly? Is there any manuals?

**Comment by yuanzhanghu** [comment]
Found similar situation, how should i configure freerdp-server to not send plain bitmap data ? 

> @moiseiisus properly configure your server so that it does not send plain bitmap data ;)

**Comment by akallabeth** [comment]
@yuanzhanghu join IRC or send a mail to the mailing list detailing your setup. Without any information it is just guessing. (assuming you have followed the advice for the client options)

**Comment by moiseiisus** [comment]
> @yuanzhanghu join IRC or send a mail to the mailing list detailing your setup. Without any information it is just guessing. (assuming you have followed the advice for the client options)

Dear @yuanzhanghu, what mailing list should I send the message?
