### ISSUE TITLE
How to exit xfreerdp when connection can not be established or disconnects?

### ISSUE THREAD

**Issue by deblauwetom** [FreeRDP/FreeRDP#3611]
The subject says most of it :)
With xfreerdp from commit 17834af7bb378f85a3b3cc4dcadaa5125a337e16 which is present in the latest buildroot, I get a different behaviour when the connection is lost in comparison to version 1.0.2. In the old version the program would exit, and I would connect to another server as a backup solution. But now in the newer versions, the program xfreerdp just waits and does nothing anymore.
I am simulating the behaviour by connecting to a windows 8.1 in a virtualbox and then setting the attached network cable in the virtualbox disconnected. It just sits there indefinitely waiting. Is it possible to restore the old behaviour with a commandline switch or maybe a source code adjustment?
Best regards
Tom,

**Comment by akallabeth** [comment]
the exit behavior should still be the same. which commandline are you using? with /log-level:trace you can also get additional debug output.

**Comment by deblauwetom** [comment]
Thanks for the clarification that it should still work like that! I found what the problem was... The problem was that I was using the feature under "advanced" in virtualbox whereby you can forward ports from the guest OS to the host OS. I was using that to forward port 3389 to 4389. So virtualbox always accepts  connections to 4389, even if the port on the guest OS(3389) is not open. So in other words xfreerdp was always able to connect and remained connected, even when the virtual network cable was unplugged or plugged back in. So that gave me the wrong impression that it was hanging.
