### ISSUE TITLE
gfx channel: performance extremely decreased

### ISSUE THREAD

**Issue by nfedera** [FreeRDP/FreeRDP#3616]
I don't have the exact numbers right now but with ```/gfx``` or ```/gfx /rfx``` or ```/gfx-h264``` xfreerdp is slower by a factor of 10 compared to a build from march this year.

Will bisect to find the culprit when I have time ...

**Comment by nfedera** [comment]
I quickly bisected only the merge commits and the extreme performance decrease started with the following pull request: https://github.com/FreeRDP/FreeRDP/pull/3500

**Comment by akallabeth** [comment]
@nfedera Found the culprit. ```freerdp_image_copy``` considers ```PIXEL_FORMAT_BGRX32``` and ```PIXEL_FORMAT_BGRA32``` distinct formats and uses the converting copy functions instead of ```memcpy```

**Comment by ropetry** [comment]
@akallabeth  WOW.. If this works.. Verry fast .. can´t test at the moment..
