### ISSUE TITLE
RDP settings are overwritten with unitialized values

### ISSUE THREAD

**Issue by ztesch** [FreeRDP/FreeRDP#3627]
After reading rdp fájl user and gwUser variables are overwrites the settings->Username and settings->GatewayUsername parameters in client/common/cmdline.c:2454
I suggest to modify the code in the following way:
+        if(user) {
                free(settings->Username);

                if (!settings->Domain && user)
                {
                        BOOL ret;
                        free(settings->Domain);
                        ret = freerdp_parse_username(user, &settings->Username, &settings->Domain);
                        free(user);

                        if (!ret)
                                return COMMAND_LINE_ERROR;
                }
                else
                        settings->Username = user;
  +      }

 +       if(gwUser) {
                free(settings->GatewayUsername);

                if (!settings->GatewayDomain && gwUser)
                {
                        BOOL ret;
                        free(settings->GatewayDomain);
                        ret = freerdp_parse_username(gwUser, &settings->GatewayUsername,
                                                     &settings->GatewayDomain);
                        free(gwUser);

                        if (!ret)
                                return COMMAND_LINE_ERROR;
                }
                else
                        settings->GatewayUsername = gwUser;
+        }
The modification will ensure that the parameters set in the rdp file will be overwritten only if /u or /gu command line options are set. If not set, the username parameter of the RDP file will be used for authentication.

**Comment by akallabeth** [comment]
@ztesch Could you create a pull for these changes?
