### ISSUE TITLE
Ipv6 from http://pub.freerdp.com/repositories/deb/stretch timeout

### ISSUE THREAD

**Issue by ruben-herold** [FreeRDP/FreeRDP#3630]
hi,

the Ipv6 from pub.freerdp.com  timeouted since weeks:

ruben@work:[~] > host pub.freerdp.com
pub.freerdp.com has address 212.232.26.215
pub.freerdp.com has IPv6 address 2a02:1b8:badc:ab1e::f8ee

ruben@work:[~] > mtr --report 2a02:1b8:badc:ab1e::f8ee
Start: Mon Nov 28 19:56:35 2016
HOST: work                        Loss%   Snt   Last   Avg  Best  Wrst StDev
  1.|-- kr-net-fw001-v100.dus.via  0.0%    10    0.2   0.2   0.2   0.3   0.0
  2.|-- 2a01:9820:0:1::2           0.0%    10    1.6   1.5   1.5   1.6   0.0
  3.|-- ge-1-1-5-0.dus2-j2.core.v  0.0%    10    1.8   2.2   1.7   4.0   0.5
  4.|-- ge-0-3-0-0.dus2-j.mcbone.  0.0%    10    1.7   2.5   1.7   8.1   1.9
  5.|-- xe-1-0-1-0.ffm3-j.mcbone.  0.0%    10    5.6   5.6   5.6   5.7   0.0
  6.|-- te3-3.edge01.ix.fra.nessu  0.0%    10    6.5   6.9   6.1  12.4   1.9
  7.|-- 2a02:1b8::18:1             0.0%    10   34.7  69.3  19.1 285.4  88.4
  8.|-- 2a02:1b8::14:1             0.0%    10   19.7  56.2  19.2 215.6  66.5
  9.|-- 2a02:1b8::19:2             0.0%    10   27.6  34.0  19.4  81.1  24.2
 10.|-- ???                       100.0    10    0.0   0.0   0.0   0.0   0.0
ruben@work:[~] >

**Comment by bmiklautz** [comment]
@ruben-herold thanks for the report. It is reachable from the other ipv6 hosts I tested from but I'll check with our provider.

**Comment by bmiklautz** [comment]
@ruben-herold should work again. Sorry for the inconvenience.
