### ISSUE TITLE
aFreeRDP: unable to connect because of negotiation problems

### ISSUE THREAD

**Issue by MrCsabaToth** [FreeRDP/FreeRDP#3631]
I compiled aFreeRDP smoother than ever following the steps required.
When trying to connect to the test connection already listed from a debugged app I get:

> I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3cbd3090 time:1433285916
> E/com.freerdp.core.transport: [pid=23946:tid=af943080] - BIO_should_retry returned a system error 32: Broken pipe
> E/com.freerdp.core.nego: [pid=23946:tid=af943080] - Protocol Security Negotiation Failure
> E/com.freerdp.core: [pid=23946:tid=af943080] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
> E/com.freerdp.core.connection: [pid=23946:tid=af943080] - Error: protocol security negotiation or connection failure

http://pastebin.com/U7Lwbc4q

I set up an RDP provided by a VirtualBox VM (VirtualBox feature). Authentication method is set to null.

> E/com.freerdp.core.nego: [pid=4180:tid=9f41a080] - Error: SSL_CERT_NOT_ON_SERVER
> E/com.freerdp.core.nego: [pid=4180:tid=9f41a080] - Error: SSL_CERT_NOT_ON_SERVER

http://pastebin.com/HyX7kdGA

At the same time, if I install FreeRDP from the Android store, I can connect to the RDP session. What can be the problem?

**Comment by akallabeth** [comment]
@MrCsabaToth Are you using the android emulator or are you using a device shipping OpenSSL? I've seen some broken library loading behavior just yesterday preferring system provided libraries over application provided ones when using ```dlopen```. Still investigating how that can be solved.

**Comment by MrCsabaToth** [comment]
@akallabeth I debugged on my Galaxy Note 3. Tonight I'll check how it runs in the emulator. I'll also look how well the OpenSSL compiled. I see the `ndk` lib (`com.freerdp.core.nego`) which spits the `SSL_CERT_NOT_ON_SERVER`. How can I check which OpenSSL is loaded? As I mention, the Android store FreeRDP works fine, I noticed though that it has a top menu bar while the compiled one doesn't.

I'm on Ubuntu 16.04 BTW if that matters.

**Comment by MrCsabaToth** [comment]
Here is my debug apk, simply renamed to apk.zip (so it's not double zipped, just renamed). You can see this way if internally things built and linked as expected.
[aFreeRDP-debug.apk.zip](https://github.com/FreeRDP/FreeRDP/files/623731/aFreeRDP-debug.apk.zip)

I'm trying to repro with an emulator, but apparently I cannot run an x86 AVD emulator instance while VirtualBox is running, which is a problem, because the VirtualBox VM would provide the RDP in my case.

**Comment by MrCsabaToth** [comment]
The emulator had similar problem with the test server:

> E/com.freerdp.core: [pid=2215:tid=8fb7a920] - failed to connect to testservice.afreerdp.com
> E/com.freerdp.core.nego: [pid=2215:tid=8fb7a920] - Protocol Security Negotiation Failure
> E/com.freerdp.core: [pid=2215:tid=8fb7a920] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
> E/com.freerdp.core.connection: [pid=2215:tid=8fb7a920] - Error: protocol security negotiation or connection failure

http://pastebin.com/Cz8apm7v

Now I notice the library load error of libjpeg and openh264. This reminds me that I went with r10e-rc4 NDK, following the aFreeRDP recommendation so there would be H264 support. r10 NDK is kinda old, maybe H264 is not important for me, would you advise to update my NDK?

**Comment by akallabeth** [comment]
your apk looks good. if you want to use h264, you just need to set the variable in scripts/something.conf to 1

**Comment by akallabeth** [comment]
you can use any ndk you like btw

**Comment by MrCsabaToth** [comment]
I was using r10e because of this: https://github.com/FreeRDP/FreeRDP/blob/master/docs/README.android#L17
I only followed this guide, `android-build-freerdp.sh` seemed to take care of everything. Should I install any `-dev` package mentioned in the desktop compilation docs? https://github.com/FreeRDP/FreeRDP/wiki/Compilation

**Comment by akallabeth** [comment]
Ah, ok ^^
That needs some update.

**Comment by akallabeth** [comment]
@MrCsabaToth Oh, and your question regarding OpenSSL: Currently there is no check implemented, but you can easily add a ```WLog_INFO(TAG, "OpenSSL_Version=%s", SSLeay_version())```

**Comment by akallabeth** [comment]
@MrCsabaToth Ok, tried it myself now. You need to disable ```async transport``` and ```async update``` in debug settings. Apart from that I was able to connect to VirtualBox provided RDP stuff.

**Comment by MrCsabaToth** [comment]
Oh, that sounds excellent. I'll try it tonight.

**Comment by MrCsabaToth** [comment]
I tried, finally I turned the other two async option off also, and switched the DEBUG log level to TRACE. I still cannot connect to the RDP of my VirtualBox, although I can connect to it with Remmina or the Adnroid Store app. I'm running the VM on my localhost and doing a adb reverse proxy to my tethered debug phone.

http://pastebin.com/WZYksSS5

Does this part look fine?

> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Enabling security layer negotiation: TRUE
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Enabling restricted admin mode: FALSE
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Enabling RDP security: TRUE
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Enabling TLS security: TRUE
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Enabling NLA security: TRUE
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Enabling NLA extended security: FALSE
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - state: NEGO_STATE_NLA
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Attempting NLA security
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - RequestedProtocols: 3
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - RDP_NEG_FAILURE
> E/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Error: SSL_CERT_NOT_ON_SERVER
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - state: NEGO_STATE_FAIL
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - state: NEGO_STATE_TLS
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Attempting TLS security
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - RequestedProtocols: 1
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - RDP_NEG_FAILURE
> E/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Error: SSL_CERT_NOT_ON_SERVER
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - state: NEGO_STATE_RDP
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Attempting RDP security
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - RequestedProtocols: 0
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - RDP_NEG_RSP
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - selected_protocol: 0
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - Negotiated RDP security
> D/com.freerdp.core.nego: [pid=19259:tid=af125d00] - nego_security_connect with PROTOCOL_RDP
> D/com.freerdp.core.gcc: [pid=19259:tid=af125d00] - Server rdp encryption method: 128BIT

The RDP of the VM is set to NULL authentication.

**Comment by MrCsabaToth** [comment]
Same with the freerdp test connection.
http://pastebin.com/wQz0UCsa

> 
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - Enabling security layer negotiation: TRUE
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - Enabling restricted admin mode: FALSE
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - Enabling RDP security: TRUE
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - Enabling TLS security: TRUE
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - Enabling NLA security: TRUE
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - Enabling NLA extended security: FALSE
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - state: NEGO_STATE_NLA
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - Attempting NLA security
> V/SessionView: 0x0
> V/SessionView: 0x0
> D/OpenGLRenderer: endAllStagingAnimators on 0xafb06e00 (ListView) with handle 0xa21756f0
> I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@15b3234f time:11041360
> D/com.freerdp.core.nego: [pid=31705:tid=af14c080] - RequestedProtocols: 3
> E/com.freerdp.core.transport: [pid=31705:tid=af14c080] - BIO_should_retry returned a system error 32: Broken pipe
> E/com.freerdp.core.nego: [pid=31705:tid=af14c080] - Protocol Security Negotiation Failure
> E/com.freerdp.core: [pid=31705:tid=af14c080] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x2000C]
> E/com.freerdp.core.connection: [pid=31705:tid=af14c080] - Error: protocol security negotiation or connection failure
> V/GlobalApp: OnDisconnected

What am I doing wrong?

**Comment by akallabeth** [comment]
@MrCsabaToth The async modes are a bit flaky (#3238 and others) and the android client needs to cut some rough edges. As for your setup I have actually no further ideas. Did you check the OpenSSL version actually used?

**Comment by MrCsabaToth** [comment]
This might be #3498 related, I have Galaxy Note 3 (my OnePlus 3t is on the way to me, it will be a salvation, my Note 3 is also Verizon, which has it's own added security policies and stuff). I'll keep you updated and check OpenSSL version too. The async transport is also a build configuration option? Maybe I should disable it there?

**Comment by akallabeth** [comment]
@MrCsabaToth Async transport is badly broken as #3238 suggests ;)

**Comment by MrCsabaToth** [comment]
News: my OnePlus 3t also cannot connect to the test freerdp connection, but it can connect to my local VirtualBox VM RDP server (with async update and async transport off) . So there's something with the Note 3.

**Comment by akallabeth** [comment]
@MrCsabaToth Ok, good to know. As far as I know ```test.freerdp.com```` is no longer operating. As for success/failure on the devices it now is really down to the OpenSSL version used.
Therefore closing this issue and tracking the OpenSSL related stuff with #3646
