### ISSUE TITLE
What's "Property 347"?

### ISSUE THREAD

**Issue by bentinata** [FreeRDP/FreeRDP#3634]
xfreerdp always log:
```
[INFO][com.freerdp.client.x11] - Property 347 does not exist
```

**Comment by ilammy** [comment]
347 is the value of an atom with the name of some X11 property. This warning is printed from `xf_GetWindowProperty()` in client/X11/xf_window.c. You can use something like this to print the actual name of the property:

```c
if (actual_type == None)
{
	char *name = XGetAtomName(xfc->display, property);
	WLog_INFO(TAG, "Property %lu (%s) does not exist", (unsigned long) property, name);
	if (name)
		XFree(name);
	return FALSE;
}
```

Unfortunately, atom values are not fixed, they are specific to your client machine, so I have no idea what that property is :(

**Comment by bentinata** [comment]
Thanks. That code location really help.
