### ISSUE TITLE
ERRINFO_GRAPHICS_SUBSYSTEM_FAILED

### ISSUE THREAD

**Issue by uplusplus** [FreeRDP/FreeRDP#3644]
server: Hyper-V server with vGPU enabled.
client: ubuntu x64

command line:
xfreerdp /u:admin /p:123456 /w:1366 /h:768 /v:10.1.45.30:3389 /rfx /gfx-h264

log:
[18:15:44:349] [27065:27066] [INFO][com.freerdp.core] - ERRINFO_GRAPHICS_SUBSYSTEM_FAILED (0x0000112F):The server-side graphics subsystem is in an error state and unable to continue graphics encoding.
[18:15:44:349] [27065:27066] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: 连接被对方重设
[18:15:44:349] [27065:27066] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0

**Comment by akallabeth** [comment]
@uplusplus looks like your server setup has issues. Does it work with other clients and H264?

**Comment by uplusplus** [comment]
Do you know how to setup h264 option of mstsc?

**Comment by akallabeth** [comment]
@uplusplus Don't have a Hyper-V setup around, but the H264 options `` /gfx:avc420``` and ```/gfx:avc444``` work (where supported) with windows 8.1, 10 and the server variants. (your command line is a alias for ```/gfx:avc420```). From that I conclude that it is most likely missing support for something server side, but to be sure a test with a different client (mstsc?) would be required.

**Comment by uplusplus** [comment]
@akallabeth Does your server enable vGPU?
I dont kown how to setup h264 with mstsc,so how to test with mstsc....

And Chrome can not work on virtual desktop with vGPU enabled.
I have test with win7/8/10.
It seams that it is a bug of hyper-v server.

**Comment by akallabeth** [comment]
@uplusplus Ok, closing this issue since you're experiencing configuration issues. If this is a real bug, please reopen. For support questions use the mailing list or IRC channel.

**Comment by uplusplus** [comment]
Did you test this command line

```
xfreerdp /u:admin /p:123456 /w:1366 /h:768 /v:10.1.45.30:3389 /rfx /gfx-h264
```

with hyper-v server?

server: Hyper-V server with vGPU enabled.

**Comment by bmiklautz** [comment]
@uplusplus I might have over read it but what version of xfreerdp are you using?

**Comment by uplusplus** [comment]
@bmiklautz 
master branch
build on ubuntu:
CMAKE_BUILD_TYPE=Debug
BUILD_ARCH="x86_64"

CMAKE_CMD_ARGS="-DCMAKE_INSTALL_PREFIX=$BUILD_DST \
	-DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE \
	-DFREERDP_EXTERNAL_PATH=$BUILD_DST \
	-DWITH_SSE2=ON \
	-DWITH_PCSC=ON \
	-DWITH_CUPS=ON \
	-DCPACK_BINARY_STGZ=OFF \
	-DCPACK_BINARY_TZ=OFF \
	-DCPACK_SOURCE_TBZ2=OFF \
	-DCPACK_SOURCE_ZIP=OFF \
	-DWITH_PULSE=ON \
	-DWITH_FFMPEG=ON \
	-DWITH_GSTREAMER_0_10=OFF\
	-DWITH_GSTREAMER_1_0=ON\
       -DWITH_OPENH264=ON \
        -DWITH_X264=ON \
	-DWITH_ALSA=ON \
	-DWITH_CLIENT=ON \
	-DWITH_MANPAGES=OFF \
	-DWITH_CHANNELS=ON \
	-DSTATIC_CHANNELS=ON \
	-DBUILD_SHARED_LIBS=OFF \
	-DWITH_XTEST=OFF"
