### ISSUE TITLE
How to create installer .deb FreeRDP

### ISSUE THREAD

**Issue by juniorcesar** [FreeRDP/FreeRDP#3649]
Hi, how to create an installer .deb of FreeRDP? 
I already create with checkinstall on debian, but I can't create with libraries dependences!

Thanks!

**Comment by bmiklautz** [comment]
@juniorcesar that's not really something related to FreeRDP more on "howto build a .deb package".
However have a look to packaging/deb/freerdp-nightly. Those are the files we use for our nightly packages (https://ci.freerdp.com/job/freerdp-nightly-binaries/) we build.
You can also have a look to the package that might be integrated in Debian soon (https://anonscm.debian.org/cgit/pkg-remote/freerdp2.git/tree/debian).
In both cases you'll see the dependencies in the control files.
