### ISSUE TITLE
auto-reconnect not work.

### ISSUE THREAD

**Issue by sbsa** [FreeRDP/FreeRDP#3650]
Client: Ubuntu 14.04 x64 FreeRDP version 2.0.0+0~20161207024949.319~1.gbpd1e0d4
Server: 2008 r2
[log.txt](https://github.com/FreeRDP/FreeRDP/files/639083/log.txt)

**Comment by akallabeth** [comment]
@sbsa authentication failure? Does the connection work at all? Please provide some basic information. The basics are explained here https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by sbsa** [comment]
xfrerdp running in terminal with params: /v:192.168.1.5 /u:Administrator +auto-reconnect /log-level:DEBUG
I test the auto-reconnection function using: iptables -A INPUT -s srv_ip_address. When xfreerdp ends timeout I allow connection via iptables -D INPUT -s srv_ip_address. Thereafter freerdp makes another attempt to reconnect and falls.
sorry for my English )

**Comment by sbsa** [comment]
Work fine with 2.0.0~dev201609090916+dfsg-1ubuntu0~git1855e36~trusty from [https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/remmina-next](url)

**Comment by sbsa** [comment]
Broken after merge pull request [#3500](https://github.com/FreeRDP/FreeRDP/pull/3500) from akallabeth/color_conversion_fix_v6.

**Comment by akallabeth** [comment]
@sbsa Just verified your issue. The commit at fault is ```f2d7766db6cad8ef37b80db478e8edf4fdb5f323```.
