### ISSUE TITLE
FreeRDP rendering regression

### ISSUE THREAD

**Issue by Ghost99** [FreeRDP/FreeRDP#3678]
After updating from nightly 20160301 to nightly 20161229 I have issues with rendering in some old applications in Windows 7, for example OpenOffice-3.3.0. In previous version of FreeRDP rendering in such applications works fine.
With /gdi:sw rendering works better, but some redundant black outline persists.

Here is a screenshot example of rendering artifacts with /gdi:hw:
![xfreerdp bug](https://cloud.githubusercontent.com/assets/2134112/21754772/3d7053a0-d618-11e6-944b-7a90b58260ad.png)

**Comment by akallabeth** [comment]
@Ghost99 Could you add the git revision and command lines you're using? Tried with current master (90877f5acb61bdba5bf5a3cc4e7f42f42b0c51a2) and ```/gdi:hw /size:1800x1000```, ```/gdi:sw /size:1800x1000``` and could not reproduce. Am I missing a step?

**Comment by Ghost99** [comment]
Did you test it with OpenOffice-3.3.0?
I can't tell you exact commit it built from, /version tells version 2.0.0-dev (git n/a). Here is package names:
`freerdp-nightly-2.0.0+0~20161229025121.322~1.gbp90877f` - it have rendering problem.
`freerdp-nightly-2.0.0+0~20160301024826.232~1.gbpb4b823` - it have no such problems.
Command line: `/opt/freerdp-nightly/bin/xfreerdp /t:MainTerminal /size:1600x820 /vc:rdpsnd /u:my_login -wallpaper /v:my_address`

**Comment by akallabeth** [comment]
@Ghost99 Weired. Used OpenOffice 3.3 en_US without success, then realized you use cyrillic (russian?) and now I have the issue too.

**Comment by Ghost99** [comment]
Yes, I'm using russian version of OpenOffice-3.3.0. Glad you can reproduce it.

**Comment by akallabeth** [comment]
@Ghost99 Ok, got the issue with ```/gdi:hw```. ROP ```GDI_PATCOPY``` is broken. Which issues do you experience with ```/gdi:sw```?

**Comment by akallabeth** [comment]
@Ghost99 For ```/gdi:hw``` #3680 should do the trick.

**Comment by Ghost99** [comment]
With /gdi:sw rendering works better, but still some redundant black outlines persists.
Here is a screenshot:
![screenshot at 2017-01-09 17 16 28](https://cloud.githubusercontent.com/assets/2134112/21770108/e37c873a-d692-11e6-921e-4c856de07f3a.png)

**Comment by akallabeth** [comment]
@Ghost99 Ok, also got the software GDI rendering bug.

**Comment by Ghost99** [comment]
In latest nightly build version 2.0.0-20170110 rendering works fine, no artifacts in OpenOffice-3.3.0 ru_RU with both /gdi:hw and /gdi:sw.
Thanks.
