### ISSUE TITLE
build warnings: passing argument 3 of 'PubSub_OnChannelAttached' from incompatible pointer type

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#3683]
I got a number of such warnings with the latest master version (as of 2017-01-09 20:00 CET) in libfreerdp/core/client.c.
Built with: 
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX:PATH=%{_prefix} \
    -DCMAKE_INSTALL_LIBDIR:PATH=%{_lib} \
    -DCMAKE_SKIP_INSTALL_RPATH=ON \
    -DWITH_CUPS=ON \
    -DWITH_CLIENT=ON \
    -DWITH_PCSC=ON \
    -DWITH_ALSA=ON \
    -DWITH_PULSE=ON \
    -DWITH_DIRECTFB=OFF \
    -DWITH_FFMPEG=OFF \
    -DWITH_JPEG=ON \
    -DWITH_GSM=ON \
    -DWITH_GSTREAMER_1_0=ON \
    -DWITH_IPP=OFF \
    -DWITH_OPENSSL=ON \
    -DWITH_CHANNELS=ON \
    -DWITH_X11=ON \
    -DWITH_XCURSOR=ON \
    -DWITH_XEXT=ON \
    -DWITH_XKBFILE=ON \
    -DWITH_XI=ON \
    -DWITH_XINERAMA=ON \
    -DWITH_XRENDER=ON \
    -DWITH_XV=ON \
    -DWITH_ZLIB=ON \
    -DBUILTIN_CHANNELS=OFF \
    -DWITH_SERVER=OFF \
    -DWITH_DEBUG_SCARD=OFF \
    -DWITH_SMARTCARD_INSPECT=ON \
    -DWITH_WAYLAND=ON \
    -DWITH_LIBSYSTEMD=ON \
    -DCMAKE_NO_BUILTIN_CHRPATH=ON 

on for openSUSE Tumbleweed.

I attached the build log.

[osTWbuild_20170109_2000.zip](https://github.com/FreeRDP/FreeRDP/files/694426/osTWbuild_20170109_2000.zip)

**Comment by akallabeth** [comment]
Merged fix, closing. Reopen if not resolved.
