### ISSUE TITLE
Smartcard Redirection On Windows Server 2008R2

### ISSUE THREAD

**Issue by firstcause** [FreeRDP/FreeRDP#369]
I've been doing some testing and have found that Smartcard redirection works fine with Windows Server 2003, but fails with Windows Server 2008R2.

Does anyone else have the same result?

Does anyone else know what magic sauce is needed to get WS2008R2 to allow FreeRDP Smartcard auth to work?

Is there a particular fix or version of PCSC?

If you have successfuly connected using a Smartcard to WS2008R2 could you please provide specs on your config?

ie. FreedRDP version, libpcsc version, Server side settings, etc, etc.

I know my WS2008R2 server-side config is good because it works great with all the Windows RDP clients.

**Comment by hardening** [comment]
@firstcause A lot of work has been done on smartcard redirection, could you give a try on last master please ?

**Comment by firstcause** [comment]
Guys, I'm not involved any more.

**Comment by bmiklautz** [comment]
As mentioned I believe this is already fixed on master (1.2.2+). I'll close the issue. Pleas re-open or create a new issue in case you encounter see this problem at some point.
