### ISSUE TITLE
cmake build error

### ISSUE THREAD

**Issue by sufidu** [FreeRDP/FreeRDP#3690]
I got the below error after run 

> ./scripts/android-build-freerdp.sh

 or 

> ./scripts/android-build-freerdp.sh --ndk $ANDROID_NDK --sdk $ANDROID_SDK

**_Output in terminal:_**

```
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ANDROID_ABI
    CMAKE_TOOLCHAIN_FILE


-- Build files have been written to: /home/sufi/FreeRDP
/home/sufi/FreeRDP/build/freerdp-build/armeabi
[RUN] cmake --build . --target install
Error: could not load cache
[ERROR] cmake --build . --target install retured 1
```

What have I missed?

Also I got the same issue as [#3691](https://github.com/FreeRDP/FreeRDP/issues/3691)

**I have one more question, how can I build for x86 devices?**

**Comment by akallabeth** [comment]
This is an issue tracker, please ask support questions on the mailing list or IRC.

**Comment by huzhifeng** [comment]
@sufidu 
I got the same problem and fix it by delete "CMakeCache.txt"
you can have a try, hope this will be helpful

Reference: 
[Cmake Error: could not load cache](http://stackoverflow.com/questions/16319292/cmake-error-could-not-load-cache)

**Comment by sufidu** [comment]
@huzhifeng 
Thanks a lot. I can't express how much I grateful to you. 
You saved my day.

Thanks again.

**Comment by USSTJerry** [comment]
i have the same question,but i can not find the CMakeCache.txt file in my project
