### ISSUE TITLE
How to build android version use ndk-r13 and boringssl?

### ISSUE THREAD

**Issue by qinlicang** [FreeRDP/FreeRDP#3706]
in AndroidToolchain.cmake
# NDK search paths
set( ANDROID_SUPPORTED_NDK_VERSIONS ${ANDROID_EXTRA_NDK_VERSIONS} -r10d -r10c -r10b -r10 -r9d -r9c -r9b -r9 -r8e -r8d -r8c -r8b -r8 -r7c -r7b -r7 -r6b -r6 -r5c -r5b -r5 "" )

can I modify the file to use ndk-r13? thinks!

**Comment by akallabeth** [comment]
setting the ANDROID_NDK variable is enough. As for boringssl, currently we only support OpenSSL. Patches are of course welcome, but be aware we use custom BIO implementations that would need adjustments.

**Comment by qinlicang** [comment]
OK, thank you!
