### ISSUE TITLE
"Do you want to save changes..." PopUp disappears (RemoteApp)

### ISSUE THREAD

**Issue by UnbendingSpirit** [FreeRDP/FreeRDP#3712]
Hi,

I use FreeRDP on a Raspberry with Raspbian (Compiled the git source, a installation with apt have a mouse position bug) for RemoteAPP to a Windows 2012 R2 Server with several apps.

I use xfreerdp /d: /u: /p: "/app:||Excel" /v: for that purpose.

When I write something i.e. Word or Excel or whatever and don´t save the file before I close the application, the "Do you want to save changes..." Popup shows up for  second and disappears behind the application window, so it´s impossible to exit the RemoteApp and a taskkill from another session is necessary to close the session from the raspberry.

Other Windows/Popups like save/save as are shown normally as it should be.

**Comment by randadinata** [comment]
I had this problem before. Its the window manager used in Raspbian. Try xfce desktop instead. Its quite light. It has better window manager.

**Comment by UnbendingSpirit** [comment]
Thanks for your answer!
But that didn´t help me.

I installed a new jessie based raspbian with xfce4

When I install freerdp through the repositories, my mouse cursor is buggy sometimes (Didn´t have a function) but the problem with the popup is fixed.

On the other hand, the compiled source still have the popup issue, but the mouse-cursor is working as it should be...

regards

**Comment by akallabeth** [comment]
Is this still an issue with the current `2.0.0-rc2` or the nightly builds?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
Repoen / create a new issue if still reproducible.
