### ISSUE TITLE
RemoteApp Banner logon timeout

### ISSUE THREAD

**Issue by shrukn** [FreeRDP/FreeRDP#3720]
I'm using remoteapp to launch an application and remoteapp has a logon banner configured.
Once clicking Ok remoteapp connection proceeds.
I see that a 2 minute timeout is configured automatically and remoteapp disconnects after 2 minutes if "Ok" is not clicked on logon banner.
Was looking if there a way to configure and increase the timeout ?

**Comment by jcrespo-asg** [comment]
Maybe on the Session Collection properties of your WinServer?
![sessioncollection](https://cloud.githubusercontent.com/assets/23072242/22920700/b6b09cbc-f296-11e6-861b-c0ffc36605a1.png)
