### ISSUE TITLE
Restrict users from accepting certificates

### ISSUE THREAD

**Issue by jtaylor87** [FreeRDP/FreeRDP#3730]
Hi
 Is there a way to prevent a user from accepting new certificates when connecting for the first time? I am using a valid certificate for the correct RDP connections but want to prevent users from accepting untrusted certificates.
 Thanks
 J

**Comment by akallabeth** [comment]
@jtaylor87 currently only manual fingerprint verification is implemented, assuming you're using xfreerdp.

**Comment by ilammy** [comment]
@jtaylor87 I guess you could use the `--from-stdin` command-line flag to prevent FreeRDP from asking the user to manually verify a certificate. It will only trust the ones already trusted by OpenSSL and will reject any other automatically.
