### ISSUE TITLE
Disabled menu options problem

### ISSUE THREAD

**Issue by ettorer** [FreeRDP/FreeRDP#3732]
Hello,
I compiled the master of 27th Jannuary 2017 under Linux 32bit. I'm connecting to a Windows server 2008 R2 with a simple command line (xfreerdp /cert-ignore /u:ettorer /d:flyd /v:IPADDRESS). The menu's disabled options are shown as the left side of the image.
The problem disappears (right side of image) with /gdi:sw or disabling the cache with -bitmap-cache.
![xfreerdp-gdi-problem-w2k8r2](https://cloud.githubusercontent.com/assets/1669856/22444153/15bfb8a6-e742-11e6-9f66-bc4fe2b6c41a.PNG)

**Comment by akallabeth** [comment]
Continuing in #3907 as it is the same issue (and some investigation was already done there)
