### ISSUE TITLE
smart-sizing not working

### ISSUE THREAD

**Issue by axos88** [FreeRDP/FreeRDP#3738]
Neither of: 
```
xfreerdp  +clipboard  --plugin rdpsnd --plugin rdpdr /size:1600x1400 +smart-sizing   /network:broadband /u:*** /v:*** /p:*** 
xfreerdp  +clipboard  --plugin rdpsnd --plugin rdpdr /size:1600x1400 +smart-sizing:3200x2800   /network:broadband /u:*** /v:*** /p:*** 
xfreerdp  +clipboard  --plugin rdpsnd --plugin rdpdr  /size:1600x1400 +smart-sizing:800x7000 /network:broadband /u:*** /v:*** /p:*** 
```

Seem to do any scaling. Moreover
`xfreerdp  +clipboard  --plugin rdpsnd --plugin rdpdr +smart-sizing:800x7000 /network:broadband /u:*** /v:*** /p:*** `

Does not make the window resizable.
I am using the latest version in the ubuntu repos:
`This is FreeRDP version 1.1.0-beta1 (git n/a)`

Support for smart-sizing should've been addedd in 2014, so this should work, right?

**Comment by akallabeth** [comment]
The syntax is ```/smart-sizing:<width>x<height>```.
Your version is also quite old, maybe you can give https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds a try.
