### ISSUE TITLE
Invalid parameters are silently ignored

### ISSUE THREAD

**Issue by axos88** [FreeRDP/FreeRDP#3739]
Invalid parameters are silently ignored. This makes it harder to track down typos:

```
xfreerdp  /u:*** /v:*** /p:*** /oeijfoiewji
connected to ***:***
Closed from X11
```

**Comment by akallabeth** [comment]
Assuming you're using the same version as in #3738 you're using an outdated version.
This bug has since been addressed.
Please try our nightly builds https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by axos88** [comment]
Seems like no AMD64 builds?

$ echo deb http://pub.freerdp.com/repositories/deb/DIST/ freerdp-nightly main | sudo tee /etc/apt/sources.list.d/xfreerdp.list
deb http://pub.freerdp.com/repositories/deb/DIST/ freerdp-nightly main
$ sudo apt-get update
Hit:1 http://download.virtualbox.org/virtualbox/debian xenial InRelease
Ign:2 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly InRelease                                            
Hit:3 http://archive.canonical.com/ubuntu xenial InRelease                                                              
Hit:4 http://archive.ubuntu.com/ubuntu xenial InRelease                                                                 
Hit:5 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu xenial InRelease                                             
Ign:6 http://dl.google.com/linux/chrome/deb stable InRelease                                                            
Ign:7 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly Release                                              
Hit:8 http://archive.ubuntu.com/ubuntu xenial-updates InRelease                                                         
Hit:9 http://ppa.launchpad.net/videolan/master-daily/ubuntu xenial InRelease                                            
Ign:10 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main amd64 Packages                                 
Ign:11 http://dl.google.com/linux/talkplugin/deb stable InRelease                                                       
Hit:12 http://archive.ubuntu.com/ubuntu xenial-backports InRelease                                                      
Hit:13 http://ppa.launchpad.net/wine/wine-builds/ubuntu xenial InRelease                                                
Ign:14 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main i386 Packages                                  
Ign:15 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main all Packages                                   
Hit:16 https://repo.skype.com/deb stable InRelease                                                                  
Hit:17 http://dl.google.com/linux/chrome/deb stable Release                                                         
Ign:18 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en_US                          
Hit:19 http://security.ubuntu.com/ubuntu xenial-security InRelease                                                   
Ign:20 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en                              
Ign:10 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main amd64 Packages        
Hit:21 http://dl.google.com/linux/talkplugin/deb stable Release                               
Ign:22 http://packages.linuxmint.com sarah InRelease                                          
Ign:14 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main i386 Packages
Ign:15 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main all Packages
Ign:18 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en_US
Ign:20 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en
Ign:10 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main amd64 Packages
Ign:14 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main i386 Packages
Hit:23 http://packages.linuxmint.com sarah Release
Ign:15 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main all Packages
Ign:18 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en_US
Ign:20 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en
Ign:10 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main amd64 Packages
Ign:14 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main i386 Packages
Ign:15 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main all Packages
Ign:18 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en_US
Ign:20 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en
Ign:10 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main amd64 Packages
Ign:14 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main i386 Packages
Ign:15 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main all Packages
Ign:18 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en_US
Ign:20 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en
Err:10 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main amd64 Packages
  404  Not Found [IP: 212.232.26.215 80]
Ign:14 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main i386 Packages
Ign:15 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main all Packages
Ign:18 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en_US
Ign:20 http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly/main Translation-en
Hit:27 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
Reading package lists... Done 
W: The repository 'http://pub.freerdp.com/repositories/deb/DIST freerdp-nightly Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://pub.freerdp.com/repositories/deb/DIST/dists/freerdp-nightly/main/binary-amd64/Packages  404  Not Found [IP: 212.232.26.215 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
$ sudo apt-get install freerdp-nightly
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package freerdp-nightly

**Comment by bmiklautz** [comment]
@axos88 as stated on https://ci.freerdp.com/job/freerdp-nightly-binaries/ DIST needs to be replaced with the distribution you are actually using.

**Comment by axos88** [comment]
:)

**Comment by axos88** [comment]
Confirmed it's working. Thanks. 
Please close the issue

**Comment by axos88** [comment]
Confirmed it's working. Thanks.
Please close the issue
