### ISSUE TITLE
Display problem on C++ applications

### ISSUE THREAD

**Issue by timotebx** [FreeRDP/FreeRDP#3742]
Hi,
I use freerdp for thin client and I noticed some displaying problems on apps compiled with C++ builder 10, Borlan, Delphi and visual basic.
In case where there is a table like this : 
![image](https://cloud.githubusercontent.com/assets/5254214/22513065/48391cfa-e89b-11e6-9e09-2efa8a458d80.png)
When an other windows pass over it, there is a problem with the cache and the table become illegible like this : 
![image](https://cloud.githubusercontent.com/assets/5254214/22513183/a9030960-e89b-11e6-9c73-7e55510951df.png)
This is append only with this table object there is no problem with exel for exmple.
I tried to change cache settings by differents method but no positive result happend.
I tried too with other RDP client (and the bug not append) but with other RDP systems i can't use multi-screen.
Thanks for all and sorry for my bad english,
Timotebx

**Comment by akallabeth** [comment]
@timotebx Please provide some basic information as command line used and versions of FreeRDP, host and remote OS.

**Comment by timotebx** [comment]
Hi @akallabeth,
Commande use :  
`xfreerdp /multimon /cert-ignore /v:$server /u:$userlogin /p:$userpasswd`
Return of  "dpkg-query --list | grep freerdp-x11"
`freerdp-x11 - 1.1.0~git20140921.1.440916e+dfsg1-4 i386 - RDP client for Windows Terminal Services (X11 client)`
Remote OS : 
`Windows serveur 2008R2`

Thanks a lot

**Comment by akallabeth** [comment]
@timotebx sorry for the delay. the version in debian stable is quite old and most of these issues have been fixed. we've updated the version in sid to what will be 2.0. either install that or try our nightly builds.

**Comment by timotebx** [comment]
@akallabeth thanks for the feedback, I will try the SID version.
Thanks again

**Comment by timotebx** [comment]
@akallabeth Hi, the nightly build freerdp-nightly-dbg_2.0.0+0~20170206024827.339 works !
Thanks for all !
