### ISSUE TITLE
Add command line option to override action script path.

### ISSUE THREAD

**Issue by volth** [FreeRDP/FreeRDP#3744]
Path of the action script is [hardcoded](https://github.com/FreeRDP/FreeRDP/blob/master/client/X11/xf_keyboard.c#L62) as ```"/usr/share/freerdp/action.sh"```.
It is inconvenient when there is no ```/usr/share``` (e.g. on [NixOS](http://nixos.org)) or it is not writable by the user.

It would be nice to have a command line option overriding this path.

PS. also, listing the option in help&man would promote a bit this useful but hard to find feature.

**Comment by bmiklautz** [comment]
@volth thanks for the feedback. The feature isn't mentioned as it initially was just added for development and isn't well tested.

**Comment by volth** [comment]
It works very good mostly, except of some short periods of time (I suspect it is when freerdp does autoreconnect of an aborted connection).

**Comment by akallabeth** [comment]
Ok, since your pull is merged I'l close this one.
