### ISSUE TITLE
ERRINFO_GRAPHICSSUBSYSTEMFAILED

### ISSUE THREAD

**Issue by uplusplus** [FreeRDP/FreeRDP#3745]
When I connected to windows running on Hyper-V 2012, and try to play a video, freerdp throw an error:
[09:38:42:893] [14120:14124] [INFO][com.freerdp.core] - ERRINFO_GRAPHICS_SUBSYSTEM_FAILED (0x0000112F):The server-side graphics subsystem is in an error state and unable to continue graphics
 encoding.

**Comment by akallabeth** [comment]
@uplusplus please provide a minimum set of information about your client too. As for the error, your commandline requests features the server can not provide. of course I can only guess what that is if you do not tell ;)

**Comment by uplusplus** [comment]
Sorry for that.

server: Hyper-V server with vGPU enabled.
client: ubuntu x64

command line:
xfreerdp /u:admin /p:123456 /w:1366 /h:768 /v:10.1.45.30:3389 /rfx /gfx-h264

There are two server:
ServerA: PC + HyperV2012 + windows8
ServerB: Server + HyperV2012 + Windows8/Windows10

freerdp + ServerA => OK
freerdp + ServerB => ERRINFO_GRAPHICSSUBSYSTEMFAILED

mstsc + ServerA => OK
mstsc + ServerB => OK

**Comment by hardening** [comment]
@uplusplus we don't have the xfreerdp involved (which ubuntu version ?). Perhaps you give a try to our last nighly build and see if it improve things for you.

Apart from that, is there any significant difference between server A and server B ? You could also try with just /rfx or /gfx-h264...

**Comment by uplusplus** [comment]
I also want to know what is the 'significant difference'.
 
Crash only when using
/gfx-h264

**Comment by akallabeth** [comment]
@uplusplus what crash are you talking about now?
As for the differences:
* Configuration
* Hardware (does HyperV use graphics dependent stuff?)

**Comment by bmiklautz** [comment]
@uplusplus without /rfx and /gfx-h264 it works?

**Comment by akallabeth** [comment]
Ok, have an understanding of what is going on now. ``` ERRINFO_GRAPHICS_SUBSYSTEM_FAILED``` tells us that the resolution (h264 context) is too large for the server to work with. 
I don't exactly know how the server side does encoding, but I'd assume they use some hardware acceleration for that.
So do the machines have different graphics cards?
And if so, which ones?

**Comment by akallabeth** [comment]
@uplusplus Did you find out what was going on?

**Comment by akallabeth** [comment]
closing as a configuration issue.
Feel free to reopen if you find any evidence this is FreeRDP related.
