### ISSUE TITLE
SEGV + backtrace

### ISSUE THREAD

**Issue by joakim-tjernlund** [FreeRDP/FreeRDP#3749]
I reported a SEGV to Remmina but perhaps the problem lies in freerdp instead?
Have a look at https://github.com/FreeRDP/Remmina/issues/1107

**Comment by akallabeth** [comment]
@joakim-tjernlund From a fast look at the corresponding code 2 options come to mind:
* The destination buffer settings are invalid / broken (that is ouside the scope of FreeRDP and Remmina has to fix)
* The server sends RFX tiles that contain data after the last line of the remote desktop resolution (The function does not check that boundary)

The latter I'll fix today. If that resolves your issue then we nailed the cause, if not only the Remmina glue code remains to be checked.

**Comment by joakim-tjernlund** [comment]
Thanks, I will test again later today when you have fixed the freerdp part and see what that does.

**Comment by joakim-tjernlund** [comment]
I just tested with your fix included and I get the same crash :(

**Comment by joakim-tjernlund** [comment]
Even changed the code to read:
```
if (nXDst + nWidth > dstWidth)
	nWidth = dstWidth;

if (nYDst + nHeight > dstHeight)
	nHeight = dstHeight;
```
did not help. I suspect the problem is a mixup of dimensinons.
The sending side has 1920x1200 and the crashing laptop has 1920x1080

**Comment by joakim-tjernlund** [comment]
When the new code fails we have:
dstHeight=1080, nYDst=1088 and nHeight=64
then this blows up:
if (nYDst + nHeight > dstHeight)
    	nHeight = MAX(0, dstHeight - nYDst);

if I change 
 nYDst = updateRects[j].top;
to
 nYDst = MIN(updateRects[j].top, dstHeight);
it works!
But I really don't know what I am doing.

**Comment by joakim-tjernlund** [comment]
Below  and works, but I am not happy with this:
UINT32 nXSrc = nXDst - updateRect.left;
UINT32 nYSrc = nYDst - updateRect.top;
as this can wrap too, so maybe a MIN() there too?
```
				UINT32 nXDst = MIN(updateRects[j].left, dstWidth);
				UINT32 nYDst = MIN(updateRects[j].top, dstHeight);
				UINT32 nXSrc = nXDst - updateRect.left;
                                UINT32 nYSrc = nYDst - updateRect.top;
				UINT32 nWidth = MIN(64, updateRects[j].right - updateRects[j].left);
				UINT32 nHeight = MIN(64, updateRects[j].bottom - updateRects[j].top);

				if (nXDst + nWidth > dstWidth)
                                    nWidth = dstWidth - nXDst;

				if (nYDst + nHeight > dstHeight)
                                    nHeight = dstHeight - nYDst;

**Comment by joakim-tjernlund** [comment]
This is better(revert your fix too):
			updateRect.left = MIN(left + tile->x, dstWidth);
			updateRect.top = MIN(top + tile->y, dstHeight);
			updateRect.right = MIN(updateRect.left + 64, dstWidth);
			updateRect.bottom = MIN(updateRect.top + 64, dstHeight);

Works anyway and now I am done :)

**Comment by akallabeth** [comment]
@joakim-tjernlund Better talk with the Remmina people about that. The GDI framebuffer must have the dimensions of the current session otherwise there is no way this will ever work.

**Comment by joakim-tjernlund** [comment]
I get the feeling that the GDI buffer has the correct dimensions(dstWidth X dstHeight) but Remmina
is trying to draw outside it which is why freerdp must clip the rectangle to proper dimensions.
Feels like Remmina is using dimensions which are a multiple of 64.

**Comment by joakim-tjernlund** [comment]
Let me show you some variables from gdb when it SEGV:
```
(gdb) info locals
nYSrc = 0
nWidth = 64
nHeight = 64
stride = 256
nXDst = 0
nYDst = 1088
nXSrc = 0
updateRect = {left = 0, top = 1088, right = 64, bottom = 1152}
tile = 0x7fffcc8684f0
i = 510
clippingRects = {extents = {left = 0, top = 0, right = 1920, bottom =
1200}, data = 0x7fffcc49e940}
formatSize = 4
j = 0
nbUpdateRects = 1
updateRects = 0x7fffcc49e8b0
dstWidth = 1920
pos = 622618
updateRegion = {extents = {left = 0, top = 1088, right = 64, bottom =
1152}, data = 0x7fffcc49e8a0}
blockLen = 8
blockType = 52421
message = 0x7fffcc04dac0
s = 0x7fffcc04da80
ok = 1
expectedDataBlockType = 52420
__FUNCTION__ = "rfx_process_message"
```
Here you can see that nYDst = 1088 which is bigger than the receiving screen(1920x1080)
and this is what is causing the SEGV.
nYDst comes from top + tile->y(0 + 1088),   17*64=1088(1088 is a multiple of 64 but the actual
screen is 1080)
Can you work out what the actual problem is?
Someone needs to clip tile-y to the actual screen size and maybe both remmina and freerdp should?
freerdb could/should sanitize its arguments

**Comment by joakim-tjernlund** [comment]
Here is my latest findings in patch form:
```
From 2ec1dd6cb98e34ba1d5a890ede7e397eb65160dc Mon Sep 17 00:00:00 2001
From: Joakim Tjernlund <joakim.tjernlund@infinera.com>
Date: Fri, 10 Feb 2017 10:24:35 +0100
Subject: [PATCH] Correct and Optimize region to update

The update region is constructed from tile(x,y) which can spill over
the actual region dimension. Clip updateRect to actual dimension.

This allows us to remove the extra check in the inner loop which also
was incomplete and could case SEGV down the line.
---
 libfreerdp/codec/rfx.c | 18 ++++++------------
 1 file changed, 6 insertions(+), 12 deletions(-)

diff --git a/libfreerdp/codec/rfx.c b/libfreerdp/codec/rfx.c
index 16daad0..4a7c65e 100644
--- a/libfreerdp/codec/rfx.c
+++ b/libfreerdp/codec/rfx.c
@@ -1168,10 +1168,10 @@ BOOL rfx_process_message(RFX_CONTEXT* context, const BYTE* data, UINT32 length,
 		{
 			RECTANGLE_16 updateRect;
 			const RFX_TILE* tile = rfx_message_get_tile(message, i);
-			updateRect.left = left + tile->x;
-			updateRect.top = top + tile->y;
-			updateRect.right = updateRect.left + 64;
-			updateRect.bottom = updateRect.top + 64;
+			updateRect.left = MIN(left + tile->x, dstWidth);
+			updateRect.top = MIN(top + tile->y, dstHeight);
+			updateRect.right = MIN(updateRect.left + 64, dstWidth);
+			updateRect.bottom = MIN(updateRect.top + 64, dstHeight);
 			region16_init(&updateRegion);
 			region16_intersect_rect(&updateRegion, &clippingRects, &updateRect);
 			updateRects = region16_rects(&updateRegion, &nbUpdateRects);
@@ -1183,14 +1183,8 @@ BOOL rfx_process_message(RFX_CONTEXT* context, const BYTE* data, UINT32 length,
 				UINT32 nYDst = updateRects[j].top;
 				UINT32 nXSrc = nXDst - updateRect.left;
 				UINT32 nYSrc = nYDst - updateRect.top;
-				UINT32 nWidth = MIN(64, updateRects[j].right - updateRects[j].left);
-				UINT32 nHeight = MIN(64, updateRects[j].bottom - updateRects[j].top);
-
-				if (nXDst + nWidth > dstWidth)
-					nWidth = MAX(0, dstWidth - nXDst);
-
-				if (nYDst + nHeight > dstHeight)
-					nHeight = MAX(0, dstHeight - nYDst);
+				UINT32 nWidth = updateRects[j].right - updateRects[j].left;
+				UINT32 nHeight = updateRects[j].bottom - updateRects[j].top;
 
 				if (!freerdp_image_copy(dst, dstFormat, dstStride,
 				                        nXDst, nYDst, nWidth, nHeight,
-- 
2.10.2

```
What do you think?

**Comment by akallabeth** [comment]
@joakim-tjernlund Could you check if ```gdi_init_ex``` is called with the correct stride and that that value is still unchanged in ```rfx_process_message```?
FreeRDP respects image buffers where width != stride, so maybe it is just an init problem.

**Comment by joakim-tjernlund** [comment]
both stride and buffer are zero, which can be seen in gdi_init

**Comment by joakim-tjernlund** [comment]
BTW, if that was 100% true, why do you already have code trying to compensate for just that?

I have merely moved that code higher up the chain and plugged the holes in it.

**Comment by akallabeth** [comment]
@joakim-tjernlund Ok, so the GDI buffer must be the same as when using xfreerdp with ```/gdi:sw```. Does this issue occur with that too? (best compile with ```WITH_SANITIZE_ADDRESS``` to uncover out of bound writes)

**Comment by joakim-tjernlund** [comment]
I am using Remmina, not xfreerdp. Also I cannot control options as Remmina is started from Pidgin

**Comment by akallabeth** [comment]
@joakim-tjernlund too bad. Would really want to know if the server is sending rectangles outside the visible session or if the GDI buffer has invalid sizes.
Anyway, I've created a branch with a slightly modified version of your patch here:
https://github.com/akallabeth/FreeRDP/tree/rfx_tile_crash

If that fixes it for you, I'll submit a pull for that.

**Comment by joakim-tjernlund** [comment]
branch tested and works for my use case.

Just to clarify(as earlier mentioned), if I tell pidgin to use xfreerdp there is no crash.

**Comment by joakim-tjernlund** [comment]
The main reason to use Remmina when sharing screen is the resizeable window Remmina has.
Will xfreedrp get that feature too?

**Comment by akallabeth** [comment]
@joakim-tjernlund Ok, thank you. This confirms my suspicion that Remmina is at fault for not providing properly aligned buffers. Sadly I currenlty lack the time to write a patch for the plugin, but maybe one of the Remmina devs has some time to look at that.
As for the resizable window, well nobody is actively working on that (I mostly work on squashing bugs in the core library) but pull requests are always welcome.

**Comment by joakim-tjernlund** [comment]
Keep squashing them bugs :) A real release of freerdp 2.0 is need.
