### ISSUE TITLE
assorted build warning on Linux (oS TW) of 2017-02-11

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#3757]
There are a number of build warnings in the current master branch. Many of the are probably "just" warnings, like "defined but not used", but some may be worth checking, like "expected ‘char *’ but argument is of type ‘BYTE * {aka unsigned char *}".

summary:

"defined but not used": 17
"warning: assignment discards ‘const’ qualifier from pointer target type": 2
"warning: ‘visibility’ attribute ignored on non-class types": 2
"warning: pointer targets in passing ... differ in signedness": 1
[make_tw.warnings.zip](https://github.com/FreeRDP/FreeRDP/files/769171/make_tw.warnings.zip)
[make_logs.zip](https://github.com/FreeRDP/FreeRDP/files/769172/make_logs.zip)

The logs were created on openSUSE Tumbleweed with this configuration:
cmake     -DCMAKE_BUILD_TYPE=Release     -DCMAKE_SKIP_INSTALL_RPATH=ON     -DWITH_CUPS=ON     -DWITH_CLIENT=ON     -DWITH_PCSC=ON     -DWITH_ALSA=ON     -DWITH_PULSE=ON     -DWITH_DIRECTFB=OFF     -DWITH_JPEG=ON     -DWITH_GSM=ON     -DWITH_GSTREAMER_1_0=OFF     -DWITH_IPP=OFF     -DWITH_OPENSSL=ON     -DWITH_CHANNELS=ON     -DWITH_X11=ON     -DWITH_XCURSOR=ON     -DWITH_XEXT=ON     -DWITH_XKBFILE=ON     -DWITH_XI=ON     -DWITH_XINERAMA=ON     -DWITH_XRENDER=ON     -DWITH_XV=ON     -DWITH_ZLIB=ON     -DBUILTIN_CHANNELS=OFF     -DWITH_SERVER=OFF     -DWITH_DEBUG_SCARD=OFF     -DWITH_SMARTCARD_INSPECT=ON     -DWITH_WAYLAND=ON     -DWITH_LIBSYSTEMD=ON     -DCMAKE_NO_BUILTIN_CHRPATH=ON     .

But I see these warnings on other Linux versions too.

**Comment by akallabeth** [comment]
@hendwolt Thank you for the report, I'm already working on fixing these. That said, the warnings are just that. There are some variable assignments left where the destination type discards const but does not actually do anything harmful with that.

**Comment by akallabeth** [comment]
Fixed most of the variable and type warnings with #3772

**Comment by akallabeth** [comment]
Current master 4065581c9895ba4f331a4b49651c1dd22831de21 fixes the issues except "defined but not used"
