### ISSUE TITLE
Android Studio Compilation

### ISSUE THREAD

**Issue by Wildregar** [FreeRDP/FreeRDP#3759]
Hi, I want to compile the library for running the sample project on Android. 
I'm on Mac.

I'm following this guide: https://github.com/FreeRDP/FreeRDP/blob/master/docs/README.android

I have installed cmake via the command:
`brew install cmake`

Downloaded sdk and ndk in documents folder.

Now I run the script via the command (from the project root):
`./scripts/android-build-freerdp.sh --ndk /Users/Wildregar/android-ndk-r10e --sdk /Users/Wildregar/android-sdks`

After 2 minutes of compiling I got this error:
`[ERROR] cp -L -r /Users/Wildregar/Documents/FreeRDP/scripts/../build/openssl/include/openssl /Users/Wildregar/Documents/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/include/ retured 1`
`[ERROR] bash /Users/Wildregar/Documents/FreeRDP/scripts/android-build-openssl.sh --src /Users/Wildregar/Documents/FreeRDP/scripts/../build/openssl --dst /Users/Wildregar/Documents/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --ndk /Users/Wildregar/android-ndk-r10e --arch armeabi --target 21 --tag OpenSSL_1_1_0c retured 1`

where am I doing wrong?

**Comment by akallabeth** [comment]
@Wildregar The android scripts are tested linux only, what I can tell you is that mac has some differences in provided unix tools like cp. From a quick look at the man pages I assume the ```cp -r``` should be replaced with ```cp -R``` but I don't know if that is enough.
If you succeed though some feedback is welcome to refine the build scripts.

**Comment by Wildregar** [comment]
Yeah, that's right.

File: `android-build-openssl.sh`

changed this line:
`common_run cp -L -r $BUILD_SRC/include/openssl $BUILD_DST/include/`

with this line:
`common_run cp -L -R $BUILD_SRC/include/openssl $BUILD_DST/include/`

and it compile. Thanks.

**Comment by akallabeth** [comment]
@Wildregar Ok, added the fix to #3754 closing this issue.
