### ISSUE TITLE
Android RDP Connection Security Negotiation Failure

### ISSUE THREAD

**Issue by Wildregar** [FreeRDP/FreeRDP#3761]
Hi, i'm running aFreeRDP on Android and after creating my connection, I tried to connect to it, but the error that gives me is as follows:

`10759-10843/com.freerdp.afreerdp E/com.freerdp.core: [pid=10759:tid=574fa440] - failed to connect to 1xx.xx.xxx.xx`
`10759-10843/com.freerdp.afreerdp E/com.freerdp.core.nego: [pid=10759:tid=574fa440] - Protocol Security Negotiation Failure`
`10759-10843/com.freerdp.afreerdp E/com.freerdp.core: [pid=10759:tid=574fa440] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]`
`10759-10843/com.freerdp.afreerdp E/com.freerdp.core.connection: [pid=10759:tid=574fa440] - Error: protocol security negotiation or connection failure
`

The host, username and password are correct, because I can connect to the machine through remote desktop on windows.

**Comment by akallabeth** [comment]
You can try to disable the async transport and input options in debug settings, there have been issue reports involving these.
If available it would also be helpful to know if a connection using xfreerdp is working (both are using the same library, so if one is working the other just needs to be configured accordingly to also work)

**Comment by Wildregar** [comment]
Disabled async transport and input Options, but not working.

How can I test with xfreerdp?

It is possible to obtain a test connection? to understand what data is to be entered and to test.

**Comment by akallabeth** [comment]
@Wildregar Connection problems ususally boil down to these main points of failure:
* Invalid credentials of some kind
* Invalid features activated the server can not provide
* A real bug in FreeRDP/aFreeRDP

To get an idea what is going on it would be nice if you could simply run ```xfreerdp /v:<host|IP> /u:<user> /p:<password>``` and optionally ```/d:<domain>``` assuming you have a linux machine to test.

**Comment by Wildregar** [comment]
I run the script like this:
`xfreerdp /v:xxx.xx.xxx.xx /u:utente /p:password /d:domain`
and
`xfreerdp /v:xxx.xx.xxx.xx /u:utente /p:password`

and I get this error:

`Warning xf_GetWindowProperty (140): Property 296 does not exist
transport_connect: getaddrinfo (nodename nor servname provided, or not known)
Error: protocol security negotiation failure`

The machine has Windows not linux. Can I connect to Windows machine?

**Comment by akallabeth** [comment]
@Wildregar Of course you can connect to every RDP server compatible ;)
But from the output I can conclude you have some kind of network issue with the machine, it can not even connect to the remote host. Do you have some firewall/routing in between the machines?

**Comment by Wildregar** [comment]
I just talked to the systems analyst who told me that access is not directed on port 3389 as I thought, but it passes through a gateway. I can handle this type of connection?

**Comment by mfleisz** [comment]
@Wildregar See the gatway options /g (gateway hostname and port) /gu/gp/gd (username, password, domain). For aFreeRDP there should be gateway settings available in the connection's bookmark (under Advanced/Enable Gateway and Gateway Settings).

**Comment by akallabeth** [comment]
Closing as resolved (configuration, no freerdp bug)
