### ISSUE TITLE
Why wfreerdp can not redirect printer?

### ISSUE THREAD

**Issue by redsunxin** [FreeRDP/FreeRDP#3778]
I'm using wfreerdp printer redirection,I build wfreerdp by vs2013.my printer can be redirected in mstsc,but I can't redirect in wfreerdp.
my printer shows in my terminal,the model is DPK750-USB and Fujitsu DPK750.I found the driver name in the printer property page.
I tried very hard,but the printer can't seen in the remote terminal.
my command line is:   

1. wfreerdp.exe /printer:DPK750-USB,DPK750-USB
2. wfreerdp.exe /printer:"Fujitsu DPK750","Fujitsu printer"
and so on,I tried so many command lines.

**Comment by akallabeth** [comment]
@redsunxin does it work with only ```/printer```?

**Comment by redsunxin** [comment]
@akallabeth 
just now I tried the command line:
wfreerdp.exe /printer
it doesn't work.I still can't see the printer in device and printer.
but the log changed.registered PRN1 PRN2 PRN3 PRN4.

**Comment by akallabeth** [comment]
@redsunxin Did you activate printer redirection in your build? what does ```wfreerdp.exe /buildconfig``` tell you?

**Comment by redsunxin** [comment]
@akallabeth I used cmake-gui to generate my vs2013 sln.CHANNEL_PRINTER, CHANNEL_PRINTER_CLIENT, CHANNEL_PRINTER_SERVER was on.And I can see printer-client project in my sln.

**Comment by akallabeth** [comment]
could you run with ```/log-level:trace``` and redirect the output to a file? That way you should get some meaningful debug information.

**Comment by akallabeth** [comment]
@redsunxin Ok, found the issue. The printer driver was not properly converted between UTF16 and UTF8. If you try #3780 it should work.

**Comment by redsunxin** [comment]
@akallabeth thanks.
Now I try use the new code.use this command line:wfreerdp.exe /printer:DPK750-USB,DPK750-USB
`	if (drivername)
		status = ConvertFromUnicode(CP_UTF8, 0, drivername, -1, &win_printer->printer.driver, 0, NULL, NULL);
	else
		status = ConvertFromUnicode(CP_UTF8, 0, prninfo->pDriverName, -1, &win_printer->printer.driver, 0, NULL, NULL);

	WLog_INFO(TAG, "win_printer->printer.driver:%s", win_printer->printer.driver);`
I add a log,the win_printer->printer.driver is DPK750-USB.but I still can't see my printer in remote terminal.

**Comment by redsunxin** [comment]
@akallabeth I try the system printer Microsoft XPS Document Writer, command line is
wfreerdp.exe /printer:"Microsoft XPS Document Writer","Microsoft XPS Document Writer"
it works.
but my printer can't.I only succeed by using mstsc.

**Comment by akallabeth** [comment]
tried it on my end, works with a brother printer as well as the virtual ones. are you sure the printer driver is spelled correctly (same as in windows)? Does it work when omitting the driver name? This works here too.

**Comment by akallabeth** [comment]
as a reference, does it work with our nightly builds?

**Comment by redsunxin** [comment]
@akallabeth I checked my spell many times,it is correct. I try:
wfreerdp.exe /printer
the command line you teach me.it still can't work.I'll try different printer.

**Comment by redsunxin** [comment]
@akallabeth thanks for your help.
my printer can be redirected by using mstsc, this prove my printer is good.Can your printer print a test page at the remote terminal?

**Comment by akallabeth** [comment]
yes (at least the virtual ones I tested). Did you try our nightly builds as a reference?

**Comment by redsunxin** [comment]
yes,I tried your nightly builds again.the win32 wfreerdp.exe size is 2.52MB.my printer can not seen at the remote terminal(at device and printer).only Microsoft XPS Document Writer and Fax redirected can be seen.

**Comment by redsunxin** [comment]
@akallabeth I have tried your nightly buids.you mean the virtual ones.have you tested a real printer.what is the virtual ones name?

**Comment by akallabeth** [comment]
@redsunxin Ok, will have to check that, maybe there is still something wrong. As for my virtual printers, I have several PDF printers installed.

**Comment by redsunxin** [comment]
@akallabeth thanks a lot.
by the way,another questions.
1.can urbdrc module be used in wfreerdp?I want to redirect cameras.
2.can remotefx usb redirection be used in wfreerdp?HID devices.

**Comment by akallabeth** [comment]
the usb redirection is currently linux/bsd only. needs some cleanup then it should also work on windows.

**Comment by redsunxin** [comment]
@akallabeth recently, do you have a plan to develop the urbdrc and printer on wfreerdp?

**Comment by akallabeth** [comment]
@redsunxin Not on my immediate roadmap. Windows is quite low on my personal one (don't use it, so I only have access at work) but URBDRC is on the roadmap, I just have to finally find some time.
So if someone wants to pick any of those up, go ahead!
