### ISSUE TITLE
#ifndef or #ifdef ?

### ISSUE THREAD

**Issue by chipitsine** [FreeRDP/FreeRDP#3802]
I see the following test failing on Linux

https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/io/test/TestIoDevice.c#L9

should it be "#ifdef" here ?

**Comment by chipitsine** [comment]
same to https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/sspi/test/TestInitializeSecurityContext.c

it is not guarded with "#ifdef _WIN32", it fails on Linux

should we guard it ?

**Comment by chipitsine** [comment]
same to https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/sspi/test/TestNTLM.c
it fails on Linux

I doubt if sspi will ever work on Linux. how it is supposed to work ?

**Comment by akallabeth** [comment]
@chipitsine Please ask questions on the mailing list or IRC.
