### ISSUE TITLE
ios 64-bit support

### ISSUE THREAD

**Issue by jensonBuzz** [FreeRDP/FreeRDP#3803]
Since Apple seems to drop support for 32-bit apps (http://www.cultofmac.com/464817/apple-prepares-drop-support-32-bit-ios-apps/), i was wondering if there is any update for supporting arm64.

I've read about patching openSSL ([#2685](https://github.com/FreeRDP/FreeRDP/issues/2685)), yet maybe there's an update on the way?

**Comment by akallabeth** [comment]
freerdp support for openssl 1.1 has been merged, the android version builds for all supported platforms. looks like somebody should just give it a try ;)

**Comment by l937928908** [comment]
/However, the view found no 64-bit support, is my compilation problem? /mac/Downloads/FreeRDP-2.0.0-rc1/client/common/Debug-iphoneos/libfreerdp-client2.a are: armv7 armv7s

**Comment by akallabeth** [comment]
@l937928908 Someone needs to create a decent toolchain file for iOS that uses the 64bit compiler...
the core is 64bit compatible, but nobody stepped up writing the necessary howto and testing that.
Pull requests welcome!
