### ISSUE TITLE
Tooltip does not appear in RDP session from Android client

### ISSUE THREAD

**Issue by ns50254** [FreeRDP/FreeRDP#3804]
When RDP session is initiated mouse hovering on any image of webpage containing tooltip does not appear.When RDP from windows machine it works fine.I have worked with file GestureDectector.java MotionEvent.ACTION_MOVE but it does not transfer mouse event to remote desktop (Windows machine).Could anyone help me to address this issue?

**Comment by akallabeth** [comment]
@ns50254 Well, you don't have a mouse on android, so you can not send the position there. If you use the aFreeRDP mode with this local pointer representation that is different though

**Comment by ns50254** [comment]
If I attach physical keyboard with android device I can get mouse pointer and click event is fired in RDP session(Windows 10 machine).I am using aFreeRDP source but could not figure out how to send mouse hovering event to remote session.

**Comment by akallabeth** [comment]
@ns50254 Special treatment of hardware devices is currently not implementd see #3561 and tooltips work with touch pointer mode.
Therefore closing this one.

**Comment by ns50254** [comment]
I have tested touch pointer mode which shows the tooltip when placed on appropriate location.I want to sync touch pointer view with hardware mouse cursor so that they will be glued together and move along with cursor. What could be the way to achieve this feature?

**Comment by akallabeth** [comment]
you send mouse position updates to the server whenever the position changes. see libfreerdp java glue code for the appropriate function name

**Comment by minenlink** [comment]
excuse me.i want to show the remote (rdp server) mouse cursor on my android client,how should i do?could you give me some suggestion? @ns50254 @akallabeth

**Comment by ns50254** [comment]
@akallabeth I am already calling native method freerdp_input_send_mouse_event(); to remote server to send mouse event.What else I need to do here?

**Comment by akallabeth** [comment]
that is enough. just check yiu're using the correct flags
