### ISSUE TITLE
Windows client language?

### ISSUE THREAD

**Issue by VladMarius** [FreeRDP/FreeRDP#3808]
Is the Windows client written either with Win32, .NET, Windows Forms or COM ? If not, then what API?

I ask this to understand if it would be possible to port the Windows client to the Windows store..

Thanks.

**Comment by akallabeth** [comment]
@VladMarius Plain Win32. But please ask questions in the mailing list or IRC.

**Comment by hardening** [comment]
And most important: look yourself before asking, taking 5 minutes of your time would have bring you the answer.
