### ISSUE TITLE
GetColor clashes with Carbon.framework

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#3810]
The `GetColor` function defined in [color.h](https://github.com/FreeRDP/FreeRDP/blob/e0382e01b89efb61115d3a73e5724df9fb02b15d/include/freerdp/codec/color.h#L530) clashes with a [definition of the same name](https://github.com/phracker/MacOSX-SDKs/blob/master/MacOSX10.6.sdk/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/Headers/ColorPicker.h#L467) in macOS' Carbon.framework.
This is problematic for me as I need to link against FreeRDP and Carbon in my FreeRDP client.

Error message when compiling:
```Static declaration of 'GetColor' follows non-static declaration```

**Comment by akallabeth** [comment]
@lemonmojo Good to know this issue exists. As for your project, is it possible to just not include the corresponding header in the files you require the carbon framework?

**Comment by lemonmojo** [comment]
@akallabeth Unfortunately no, Cocoa frameworks are not designed to be partially included. If you meant the other way around (not including the specific freerdp header) I don't think that's possible either as I need to include freerdp/gdi/gdi.h which in turn includes freerdp/codec/color.h.

**Comment by lemonmojo** [comment]
Any news on this? I just updated to master and was surprised to still see this issue.

**Comment by bmiklautz** [comment]
@lemonmojo no news. The GetColor function(s) were initially modeled after the similar functions on windows and are part of our external API since quite some time and might be used by other applications.

**Comment by lemonmojo** [comment]
Well that's unfortunate since it breaks my app and potentially anyone's using Carbon and FreeRDP in the same project. For now, I can work around the issue by just commenting out the method in FreeRDP's headers after compiling FreeRDP but that's obviously very hacky.

Wouldn't it make sense to address this before the 2.0 release?

**Comment by bmiklautz** [comment]
@lemonmojo I know at least two project that use this functionality (all non carbon) renaming would mean doing this in FreeRDP but also for all projects that use it.

**Comment by bmiklautz** [comment]
@hardening @akallabeth what do you think?

**Comment by lemonmojo** [comment]
I'm aware of the consequences. But projects calling this method can simply be refactored to use the new name. While Carbon, being a system framework can not simply be changed to not clash with FreeRDP's method naming.

**Comment by bmiklautz** [comment]
@lemonmojo I absolutely do get your point but this breaks the API (which is already in some distributions). - I'll see if we find a nice solution that makes it usable with carbon as well.

**Comment by lemonmojo** [comment]
I'd certainly appreciate it so thx for looking into it!

**Comment by hardening** [comment]
@diget @akallabeth I'm not aware of projects using GetColor, so I don't see which project it would bother
