### ISSUE TITLE
Extra error message when closing the xfreerdp window

### ISSUE THREAD

**Issue by hardening** [FreeRDP/FreeRDP#3814]
Since the kerberos error printing, I'm seeing that error when closing the xfreerdp window:

```
[15:44:37:546] [20383:20384] [WARN][com.freerdp.core.transport] - Unhandled SSL error (where=16392, ret=256 [warning, close notify])
```

**Comment by akallabeth** [comment]
@hardening looks like the switch needs another case for this one, found a explanation here:
https://security.stackexchange.com/questions/133575/ssl3-alert-readwarningclose-notify

**Comment by akallabeth** [comment]
@hardening Are these messages gone now? (cold no longer reproduce locally)

**Comment by hardening** [comment]
No messages now, closing thank you @akallabeth
