### ISSUE TITLE
FreeRDP crashes with hostnames > 31 characters

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#3815]
I just had a long debugging session with a customer and found out that FreeRDP currently crashes when a hostname with 32 or more characters is used on the machine it is being run on.

This hard limit is defined in [sysinfo.h](https://github.com/FreeRDP/FreeRDP/blob/master/winpr/include/winpr/sysinfo.h#L292), used in [settings.c](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/settings.c#L255) and the actual problem occurs in [sysinfo.c](https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/sysinfo/sysinfo.c#L410).

Not sure about Windows or Linux but on the Mac it's totally possible to have hostnames with 32 characters or more (way more actually). Just do this on a terminal and watch FreeRDP cry like a baby: `sudo scutil --set HostName "abcdefghijklmnopqrstuvwxyz012345"`

**Comment by akallabeth** [comment]
@lemonmojo The 31 character limit is a limitation of the RDP protocol. The error handling for the default is broken though, need a sensible fallback for that.

**Comment by lemonmojo** [comment]
@akallabeth I already suspected that. Any ideas for a proper fix? I'd also take a quick fix as I need to get this out to customers as soon as possible.

**Comment by akallabeth** [comment]
@lemonmojo For a quick fix just truncate the hostname in ```GetComputerNameA``` instead of returning an error

**Comment by hardening** [comment]
Yeah I've hit that bug too some weeks ago with a Ubuntu 14.04 host, who's name was generated from the chip and co and so was way longer than 31 characters. Quite a long debugging to figure that freerdp_settings_new() was failing, and to find that GetComputerNameA was at fault.

**Comment by lemonmojo** [comment]
@akallabeth Just implemented the quick fix, works wonders!
@hardening I didn't even have debugging tools on the customer's machine so that was quite a challenge... ;)

**Comment by akallabeth** [comment]
@lemonmojo Does current master fix the issue as well?

**Comment by lemonmojo** [comment]
@akallabeth 32+ characters hostname works fine with master.
