### ISSUE TITLE
Seg fault when connecting from Win10

### ISSUE THREAD

**Issue by wordempire** [FreeRDP/FreeRDP#3817]
I built current master branch of FreeRDP server (the shadow thing) with the following options:
```
         "-DWITH_PULSE=ON"
         "-DWITH_OPENH264=ON"
         "-DWITH_SERVER=ON"
         "-DWITH_CUPS=ON"
```

When connecting from the windows 10 remote desktop client to the freerdp server, it briefly connects. 
The backtrace shows:
```
#0  0x00007ffff7227450 in __memmove_avx_unaligned_erms () from /gnu/store/iwgi9001dmmihrjg4rqhd6pa6788prjw-glibc-2.24/lib/libc.so.6
#1  0x00007ffff602422b in rdpgfx_write_surface_command () from /home/jelle/Documents/hack/FreeRDP/build/server/common/libfreerdp-server2.so.2
#2  0x00007ffff602476b in rdpgfx_send_surface_frame_command () from /home/jelle/Documents/hack/FreeRDP/build/server/common/libfreerdp-server2.so.2
#3  0x00007ffff79c45be in shadow_client_thread () from /home/jelle/Documents/hack/FreeRDP/build/server/shadow/libfreerdp-shadow2.so.2
#4  0x00007ffff772e756 in thread_launcher () from /home/jelle/Documents/hack/FreeRDP/build/winpr/libwinpr/libwinpr2.so.2
#5  0x00007ffff5019404 in start_thread () from /gnu/store/iwgi9001dmmihrjg4rqhd6pa6788prjw-glibc-2.24/lib/libpthread.so.0
#6  0x00007ffff71e752f in clone () from /gnu/store/iwgi9001dmmihrjg4rqhd6pa6788prjw-glibc-2.24/lib/libc.so.6
```

Some initial exploration makes it seem that the `avc420->data` pointer consistently points to an invalid address (0x30 for me). Any ideas on what this could be?

**Comment by akallabeth** [comment]
@wordempire Looks like a preference issue, the H264 component ranks ```FFMPEG``` over ```OpenH264``` but ```FFMPEG``` is missing the encoder implementation. Try with ```-DWITH_FFMPGE=OFF```

**Comment by akallabeth** [comment]
@wordempire Did this solve your issue?

**Comment by wordempire** [comment]
Yes, it was indeed what you suggested. Thanks again!

On Mar 17, 2017 1:04 PM, "akallabeth" <notifications@github.com> wrote:

@wordempire <https://github.com/wordempire> Did this solve your issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/FreeRDP/FreeRDP/issues/3817#issuecomment-287337354>,
or mute
the thread
