### ISSUE TITLE
how to show the remote mouse cursor

### ISSUE THREAD

**Issue by minenlink** [FreeRDP/FreeRDP#3820]
I used freerdp 1.1.0 on my android device.

now ,i want my client app can show the remote(rdp server) mouse cursor.what should i do? 

could you give me some suggestion?

look forward to your reply.

**Comment by akallabeth** [comment]
Please ask questions in IRC or on the mailing list.

**Comment by minenlink** [comment]
sorry sir.could you give me some suggestion about this issue?or Rreerdp-- v1.1.0,not support this feature?


![default](https://cloud.githubusercontent.com/assets/25025688/23393326/0669d684-fdbd-11e6-9dfb-09b55abb4535.png)

**Comment by minenlink** [comment]
@akallabeth 
look forward to your reply .

**Comment by minenlink** [comment]
i have already send the question to mailing list , but no feedback . so could you help me ? i can't see any other way round it... @akallabeth
