### ISSUE TITLE
Xfreerdp memory leak

### ISSUE THREAD

**Issue by yueyihua** [FreeRDP/FreeRDP#3822]
When I connected to my hyper-v VM useing xfreerdop, I played a mp4 video, but after 32mins, xfreerdp aborted, and i can not see any error. But when I use free command to check total memory, all has been used. This is my usage:
xfreerdp /v:10.1.40.175 /u:yyh_user /p:1adgj6 /cert-ignore /size:1920x1080 /usb:auto /drive:USB-Disk,/media /rfx /multimedia:sys:pulse,decoder:ffmpeg /sound:sys:pulse /microphone:sys:pulse /gfx-h264:AVC420 +gfx-thin-client +async-update

**Comment by akallabeth** [comment]
which version are you using? does this also happen if you do not use /usb?

**Comment by yueyihua** [comment]
My version is 2.0.0-dev (git 046417f)
This always happen, if i don not use /usb, it also happen.

**Comment by akallabeth** [comment]
@yueyihua That version does not exist. If you have a clone from something different than FreeRDP I can't help.

**Comment by akallabeth** [comment]
@yueyihua Oh, and please stop creating duplicate bugs like #3821

**Comment by akallabeth** [comment]
Closing as this obviously occurred on a fork.
Reopen if you can reproduce this with upstream FreeRDP.

**Comment by bmiklautz** [comment]
@yueyihua can you try if the current master (FreeRDP/FreeRDP) shows the same behavior?

**Comment by yueyihua** [comment]
@bmiklautz I have resolved a memory leak for my code, it is my reason. But when I use valgrind to check the running xfreerdp, it also has memory leak, but it is slowly.
==2693== LEAK SUMMARY:
==2693==    definitely lost: 95,472 bytes in 1,720 blocks
==2693==    indirectly lost: 4,406,407 bytes in 1,509 blocks
==2693==      possibly lost: 14,230,904 bytes in 573 blocks
==2693==    still reachable: 55,838,597 bytes in 6,558 blocks
==2693==                       of which reachable via heuristic:
==2693==                         newarray           : 1,536 bytes in 16 blocks
==2693==         suppressed: 0 bytes in 0 blocks
==2693== 
==2693== For counts of detected and suppressed errors, rerun with: -v
==2693== Use --track-origins=yes to see where uninitialised values come from
==2693== ERROR SUMMARY: 13930 errors from 1042 contexts (suppressed: 0 from 0)

**Comment by yueyihua** [comment]
@akallabeth When I use FreeRDP version 2.0.0-dev (git 0540e18), if I play the video, or not play anything just openning the Windows Media Player, the memory is leaking slowly, average 0.5M/min, after one night, 240M disappeared.

**Comment by akallabeth** [comment]
@yueyihua Does this also occur when removing ```/multimedia``` from your command line?

**Comment by hardening** [comment]
IIRC you may see which part of the code is leaking using ```--leak-check=full```

**Comment by yueyihua** [comment]
@akallabeth Yes, this also occur when removing /multimedia.

**Comment by yueyihua** [comment]
@hardening How i can send my log file to you?

**Comment by hardening** [comment]
@yueyihua yeah pastebin it
