### ISSUE TITLE
xfreerdp (v. 2.0.0~dev) corrupts date and time with Windows 7 and 10

### ISSUE THREAD

**Issue by hanakemt** [FreeRDP/FreeRDP#3828]
xfreerdp (FreeRDP version 2.0.0~dev (git n/a)) corrupts date and time with Windows 7 and Windows 10 while it works well with Windows 2008. Same is true with remmina (Version 1.2.0-rcgit-18 (git rcgit-18)) that relies on the FreeRDP library.

A previous version of xfreerdp (FreeRDP version 1.1.0-beta1 (git n/a), downloaded from the Ubuntu 16.04 repo) handles correctly the date and time with all the above mentioned Windows variants.

See <https://github.com/FreeRDP/Remmina/issues/934>.

**Comment by akallabeth** [comment]
@hanakemt Please be a bit more detailed in your bug reports. I guess you're talking about the drive redirection? That one has been fixed on current master. Could you please confirm?

**Comment by hanakemt** [comment]
@akallabeth: Sorry for omitting that detail. Yes, the error effects shared folders (aka drive redirection: "/drive:hanak,/home/hanak").

Good news that it is fixed on the current master. As I am using the remmina ppa (http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu/dists/xenial/main/) I hope it willalso  be updated soon. Thanks!
