### ISSUE TITLE
the android client cannot show the remote mouse cursor.

### ISSUE THREAD

**Issue by minenlink** [FreeRDP/FreeRDP#3832]
I used freerdp v1.1.0 on my android device.
now ,i want my client app can show the remote(rdp server) mouse cursor(shown in the screenshot below).
what should i do?

![0669d684-fdbd-11e6-9dfb-09b55abb4535 1](https://cloud.githubusercontent.com/assets/25025688/23501893/be85b51c-ff70-11e6-8aa0-c18da4795f85.png)

i have already send the question to mailing list , but no feedback . 

could anybody give me some suggestion?or android Rreerdp, not support this feature?

**Comment by akallabeth** [comment]
@minenlink Please stop spamming this issue tracker. If nobody answers your requests on the mailing list then maybe you need some patience or provide a few more details and give a recent version of FreeRDP a try (1.1 is quite old)
Other than that this looks like you need to do some coding to get this new mouse mode working.

**Comment by minenlink** [comment]
sorry for that.
the recent version looks like is the same about this.
i will try to do more coding .
Again, sorry.
