### ISSUE TITLE
Fullscreen Mode Bug

### ISSUE THREAD

**Issue by sieveni91** [FreeRDP/FreeRDP#3835]
Hello,

I searched for that kind of Problem, but didn't find any solution. When I add the /f to the command, freerdp does not show the remote connection, but only flashes for a second. I use Raspbian Jessie. Can somebody give me a hint please?

With regards
Nils

**Comment by hardening** [comment]
Can you give us a hint too => https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by sieveni91** [comment]
Sorry, of course I can explain it more detailed:

I use _xfreerdp /v:XX.XX.XX.XX /u:XXXXX /w:1920 /h:1200_ and the session is opening. After that I am able to get into Fullscreen mode with Strg + Alt + F. 

If i wanted to start the session into Fullscreen mode directly with _xfreerdp /v:XX.XX.XX.XX /u:XXXXX /w:1920 /h:1200 **/f**_, there is only a short display flash happening, returning to terminal without any opened session.

**Comment by hardening** [comment]
Just an idea, but I guess that if you're in the same situation as #3588 and that the bug is closed then it's because your xfreerdp is just too old.

**Comment by sieveni91** [comment]
You're totally right! I setup the pi yesterday and wasn't expecting that the package isn't up to date, even after installing it via apt-get. Sorry about that. I tried the current git Version, and it works like a charm. Thanks for your help.
