### ISSUE TITLE
Getting exit status 0 on wrong credentials

### ISSUE THREAD

**Issue by mctracker** [FreeRDP/FreeRDP#3840]
I am using xfreerdp to checking validity of rdp accounts. But often It return status 0 on wrong credentials:

```
u1@server$ xfreerdp /v:1.2.3.4 /u:user /port:3389 /p:pass +auth-only -sec-nla /cert-ignore
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:692: Authentication only. Don't connect to X.
connected to 1.2.3.4:3389
Unable to get current timezone rule
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/libfreerdp/core/freerdp.c:95: Authentication only, exit status 0
/build/freerdp-xUV4hy/freerdp-1.1.0~git20140921.1.440916e+dfsg1/client/X11/xf_client.c:1278: Authentication only, exit status 0
```

At the same time I cant log in with this credentials on target machine, as I getting error (incorrect credentials). What could it be and how to fix it?

**Comment by akallabeth** [comment]
@mctracker when using rdp security level every connect succeeds as the authentication is done by the greeter within the session. Only when using authentication that is done pre session this can succeed.
