### ISSUE TITLE
How to fix hardcoded values for NTLM/Kerberos SecPkgContext_Sizes structure ?

### ISSUE THREAD

**Issue by dodo040** [FreeRDP/FreeRDP#3848]
In the function : 

`SECURITY_STATUS SEC_ENTRY ntlm_QueryContextAttributesW(PCtxtHandle phContext, ULONG ulAttribute, void* pBuffer)`

we have the following : 
`

		SecPkgContext_Sizes* ContextSizes = (SecPkgContext_Sizes*) pBuffer;
		ContextSizes->cbMaxToken = 2010;
		ContextSizes->cbMaxSignature = 16;
		ContextSizes->cbBlockSize = 0;
		ContextSizes->cbSecurityTrailer = 16;

`

Where do the values 2010, 16, 0 and 16 come from ? 

Let's take for example cbMaxSignature. The link (https://msdn.microsoft.com/en-us/library/windows/desktop/aa380097) says that cbMaxSignature "specifies the maximum size of the signature created by the MakeSignature function." But in FreeRDP this function is not supported : 

`SECURITY_STATUS SEC_ENTRY ntlm_MakeSignature(PCtxtHandle phContext, ULONG fQOP, PSecBufferDesc pMessage, ULONG MessageSeqNo) {
        return SEC_E_UNSUPPORTED_FUNCTION;
}`

Then, why do we set cbMaxSignature to 16 ?

Is there a way not to assign hard-coded values but make automatic assignment instead ?

Besides, given the work of tc-anssi (https://github.com/tc-anssi/FreeRDP/tree/kerberos), I want to implement the same QueryContextAttributes function but for Kerberos.
The problem is, I don't know or it's not clear to me, apart from cbMaxToken, which values I have to assign to cbMaxSignature, cbSecurityTrailer and cbBlockSize. 
I set cbMaxToken to 48,000 since for Windows Server 2012 the default value of the MaxTokenSize registry entry is 48,000 bytes.
If someone could help me to understand what these parameters are supposed to store. 

Finally for both, NTLM and Kerberos, I'm listening if someone is considering some solution or maybe has already come up with a solution to this problem of hardcoded values.

**Comment by hardening** [comment]
@dodo040 you're right there's good things that we should take from https://github.com/tc-anssi/FreeRDP/tree/kerberos . If you want to submit such improvements as a PR we'll be glad to review it.

**Comment by dodo040** [comment]
@hardening yes sure I'll submit a PR very soon. Before I've a few things to improve or update including this issue.

**Comment by akallabeth** [comment]
Kerberos support has been merged, assume this is fixed? Reopen if not.
