### ISSUE TITLE
Compile errors caused by missing inttypes.h macros

### ISSUE THREAD

**Issue by bjoernv** [FreeRDP/FreeRDP#3857]
On openSUSE Tumbleed (tested with version 20170213, default compiler: GCC 6.3.1) FreeRDP Git master can't be compiled since some weeks. All inttypes.h macros like PRIu32 cause errors. E.g.

```
[  3%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/synch/wait.c.o
In file included from /var/soft/FreeRDP/winpr/libwinpr/synch/../log.h:23:0,
                 from /var/soft/FreeRDP/winpr/libwinpr/synch/wait.c:49:
/var/soft/FreeRDP/winpr/libwinpr/synch/wait.c: In function ‘WaitForMultipleObjects’:
/var/soft/FreeRDP/winpr/libwinpr/synch/wait.c:343:42: error: expected ‘)’ before ‘PRIu32’
   WLog_ERR(TAG, "invalid handles count(%"PRIu32")", nCount);
                                          ^
/var/soft/FreeRDP/winpr/include/winpr/wlog.h:117:56: note: in definition of macro ‘WLog_Print’
                      __LINE__, __FILE__, __FUNCTION__, __VA_ARGS__ ); \
                                                        ^~~~~~~~~~~
/var/soft/FreeRDP/winpr/libwinpr/synch/wait.c:343:3: note: in expansion of macro ‘WLog_ERR’
   WLog_ERR(TAG, "invalid handles count(%"PRIu32")", nCount);
   ^~~~~~~~
/var/soft/FreeRDP/winpr/libwinpr/synch/wait.c:450:39: error: expected ‘)’ before ‘PRIu32’
    WLog_ERR(TAG, "poll() handle %d (%"PRIu32") failure [%d] %s", index, nCount, errno,
                                       ^
/var/soft/FreeRDP/winpr/include/winpr/wlog.h:117:56: note: in definition of macro ‘WLog_Print’
                      __LINE__, __FILE__, __FUNCTION__, __VA_ARGS__ ); \
                                                        ^~~~~~~~~~~
/var/soft/FreeRDP/winpr/libwinpr/synch/wait.c:450:4: note: in expansion of macro ‘WLog_ERR’
    WLog_ERR(TAG, "poll() handle %d (%"PRIu32") failure [%d] %s", index, nCount, errno,
    ^~~~~~~~
```

cmake does not report any problems. HAVE_INTTYPES_H is set in auto-generated config.h.

**Comment by akallabeth** [comment]
@bjoernv ```inttypes.h``` is included in the generated ```wtypes.h```.  Could you check if that is the case with your builds? ``` #if !defined(_MSC_VER) || _MSC_VER >= 1900
 /* Microsoft's inttypes.h is broken before MSVC 2015 */
 #define WINPR_HAVE_INTTYPES_H
 #endif``` is the part you should be looking for.

**Comment by hendwolt** [comment]
@bjoernv 
I have no problems compiling on openSUSE Tumbleweed. But I use a more recent source version.
Which cmake config do you use?

**Comment by bjoernv** [comment]
For testing I used no options: "`mkdir build; cd build; cmake ..`".

**Comment by akallabeth** [comment]
@bjoernv Is your source directory clean (aka did you run cmake at any time there)? Asking because cmake does not like out of tree builds when there are leftovers directly in the source directory.

**Comment by hendwolt** [comment]
I can't reproduce it.

::
rm -r FreeRDP-master
unzip FreeRDP-master.zip 
cd FreeRDP-master/
cmake .
make

--> success

cat /etc/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20170314"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20170314"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20170314"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
