### ISSUE TITLE
{Would appreciate some feedback at this point}[Found Workaround]Can't write any curly or square brackets (Windows 7 Client to Windows 10 Host connection)

### ISSUE THREAD

**Issue by Rusk85** [FreeRDP/FreeRDP#3859]
I just started using FreeRDP in order to be able to use all shortcuts of ReSharper (especially CTRL+ALT+ARROW) which now finally after looking for a solution on and off for months works now.
But after connecting to my host I am completely unable to type any curly or square brackets `[]{}`. I am connecting from a highly restricted (company) Windows 7 64bit Enterprise client using a desktop shortcut for connection to a Windows 10 64bit Professional host. This is my command for connecting as it is used in my Windows shortcut:

    D:\some-path\wfreerdp.exe +clipboard /f /v:main.muncic.local 
    (as for the domain I set up my own domain at home so don't be suprised you can't find an official .local TLD ;))

I used this version: [Download the portable WFreeRDP master branch binaries (continuous build)](http://bit.ly/ZIQoFZ)

When trying to type the brackets I tried both `AltGr` and `CTRL + ALT`. Interestingly enough other characters such as `@` I can write using both combinations. In addition since I am using a Germany keyboard layout Umlauts (`üöä`) work just as expected to.
All in all I can't make any sense of this.

**Comment by Rusk85** [comment]
I made a big discovery after writing long-winded Autohotkey scripts to overcome this issue. I was actually able to type all brackets with Autohotkey but at my last attempt to restore original functionality with `AltGr + 7` e.g. (open curly braces) it failed and out of annoyance I pressed it multiple times and suddenly the bracket appeared. At first I attributed it to fault in my script but after disabling it and holding `AltGr` and double-tapping `7` `{` miraculously appeared. I still don't know whats going on but at least I can continue work with only a minor blow to my convenience.

**Comment by Rusk85** [comment]
Well in the meantime I have installed `arch linux` on my private notebook with `kde` and `FreeRDP`. There I have no issues with the hotkeys at all. Interestingly enough now on my work notebook using freerdp shortcuts are broken completely now meaning not even double-tapping as described above works anymore. So I have resorted to this Autohotkey script:

	; CTRL + ALT + 7 => {
	<^!7:: Send, {{}

	; CTRL + 8 => [
	<^!8:: Send, [

	; CTRL + 9 => ]
	<^!9:: Send, ]

	; CTRL + 0 => }
	<^!0:: Send, {}}

It works but is obviously less than optimal. And all this while not having changed freerdp version on my work notebook which is running W7 x64 Enterprise except for the codec. So my cmd looky like this now:

    CD /D D:\Programme\wfreerdp-1.1
    wfreerdp.exe +clipboard /smart-sizing:1920x1080 /f /v:main.muncic.local:3389 /u:Sven /p:customi8 /network:lan /rfx /gdi:hw /rfx-mode:video

And just noticed clipboard gave out as well so had to resort to native Windows RDP. Might have to restart the Windows notebook. Still to this day sadly the best fix for Windows machines.

**Comment by akallabeth** [comment]
@Rusk85 The windows client has not received much attention beside some code refactoring. I can only point you to ```wf_ll_kbd_proc``` which is the function that is processing keyboard events. As for the version you're using, not shortening links could help others to guess the actual location.

**Comment by Rusk85** [comment]
Well it's possible I downloaded a very old version. As for the url shortening, wasn't done by me.
![wasn't done by me](http://i.imgur.com/7U2fMGS.png)
At work I found the link to the jenkins CI server offering the nightlies which I can't use because the Symantec crap running on my corp notebook on which I am an unprivileged user, won't allow me to use it. It explicitly states the binary as most likely not harmful but because only 5 other Symantec users have "experience" with it, it's rejecting its execution and immediately deletes it. As for testing it on another machine my only other notebook, while it is my own, is running arch linux with KDE where FreeRDP works as a charm. And can't be bothered to install a Win7 VM just for testing because no point since in the end corp policy set in Symantec still wouldn't allow me to use it. What now?

**Comment by akallabeth** [comment]
@Rusk85 Well, we only provide the nightly builds from https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by byteboon** [comment]
I'll take a drive-by shot at this...  I haven't looked at the windows client keyboard code, however the need to type the key twice sounds like you're generating a 'dead key' -- that is a key that is used to add an accent to an subsequent key. The first hit of the key is dead (stored accent) and the second hit is either the accented character if valid, or the actual second key if invalid. Dead keys are very dependant on keyboard layout settings, so you may want to consider what keyboard layouts you are using on both the client and what the remote machine thinks the layout is.  You may need to look into using the /kbd setting for wfreerdp to set the layout appropriately.
