### ISSUE TITLE
Can't use redirected Device

### ISSUE THREAD

**Issue by morphinz** [FreeRDP/FreeRDP#3860]
Hello.

I have an Epson TM-L500A printer and im redirect it with RemoteFX.
I can see the printer in Device list but i can't see with "Epson virtual port assignment tool - Ver.8.40"
Because of this problem i can't use my device...

You can see the Epson device installed and we can see in device list But the Epson Virtual Port Assignment tool can not find it.
![490a340c-e6cc-47f6-826d-43f1d131622e](https://cloud.githubusercontent.com/assets/11850235/23853001/47b9befc-07f3-11e7-8e82-351fa0c3e243.jpg)

IN local machine its looking like that: 
![82d02eae-865c-45eb-8d3e-d0b8531cc46d](https://cloud.githubusercontent.com/assets/11850235/23853290/9084aec0-07f4-11e7-9459-04aa7b736a41.jpg)

If i redirect with Citrix or Vmware protocol OR any Redirection program i can use the printer...
Citrix: 
![d252cee5-f75c-4c38-bef6-07f97b888cd7](https://cloud.githubusercontent.com/assets/11850235/23853295/9c063dfe-07f4-11e7-8b6b-1a457ce0dc18.jpg)

Redirection program: 
![85bfa40c-d8a8-4b38-81e2-6b921ba21549](https://cloud.githubusercontent.com/assets/11850235/23853298/a1524f46-07f4-11e7-8637-ec75d13581af.jpg)

I can't use the printer with Windows RDP too... I can see redirected printer as a NONE:
![winrdp](https://cloud.githubusercontent.com/assets/11850235/23854252/42c4d6ec-07f9-11e7-9067-3ec08e844c1d.jpg)

When i look Windows Registry (regedit) I found something different with RDP..

Local machine registry: 
![e7591742-4ca5-431a-b65b-e989c0aa0b59](https://cloud.githubusercontent.com/assets/11850235/23854174/e64ff432-07f8-11e7-8fbe-fe41ed547e97.jpg)

Citrix registry: 
![39f33f00-ec86-4ff0-b8f5-d084604034e0](https://cloud.githubusercontent.com/assets/11850235/23853415/1d6841bc-07f5-11e7-8560-a397a33984aa.jpg)

RDP registry:
![f758d436-702e-4259-8f2a-c29ceae67445](https://cloud.githubusercontent.com/assets/11850235/23854103/85cafed6-07f8-11e7-955c-8368bc280fdf.jpg)

With RDP the registry field looking strange. BTW Citrix + Default machine "Capabilities REG_DWORD" value 148 but RDP value 134.

I'm stuck and i dont know what can i do..

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Some details please

**Comment by morphinz** [comment]
Added, sorry about that.

**Comment by akallabeth** [comment]
@morphinz better, but your command line would be appreciated ;)

**Comment by morphinz** [comment]
sudo xfreerdp /sec:nla /u:test /p:1 /f /cert-ignore /v:1.1.1.1 /log-level:INFO /usb:auto,dev:04b8:0202

Compile parameters..
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DWITH_PCSC=ON -DCHANNEL_RDPSND_CLIENT=ON  
  
Also i tried stable version.

**Comment by bmiklautz** [comment]
@morphinz haven't tried to redirect printer directly with USB but you could try the printer redirection (/printer)

**Comment by morphinz** [comment]
@bmiklautz I have to redirect as a device because "Epson Virtual Port Assignment tool" converting the device to com port.. If i redirect as a printer, i can't use it.

**Comment by bmiklautz** [comment]
@morphinz is the printer works locally it should also work remotely.

**Comment by morphinz** [comment]
@bmiklautz Don't think like a printer. This is a device and needs to be convert as com port.

**Comment by morphinz** [comment]
unfortunately its not :(

**Comment by akallabeth** [comment]
@morphinz Did you compile with CUPS support? That is required for ```/printer``` to work.

**Comment by morphinz** [comment]
@akallabeth I didnt.. Because i dont use printer redirection.
My system really simple.
I have a program and its only use "com" port.
Because of this dependency Epson has usb device to com port emulator. 
I need to give usb device to this program. If i redirect as a printer, the program can't emulate because has no device.
Because of these dependencys i can't use printer redirection...

Also i alredy see in device list my program. This means i can redirect this device...
But Epson can not find the device.. This means i can't redirect like Citrix, Vmware or any other redirection program...  
Also Windows RDP can't do this too... This is the weird part.. This means you're using something smilar for redirection method like Windows.
I think RDP changes something like "Port ID, usb Serial number vs..." 
If i can find What changes, maybe i will fix it. But i don't know what is the difference.. 

Sorry for my english.

**Comment by hardening** [comment]
@morphinz the support for USB redirection in FreeRDP really needs love, that's why @akallabeth and @bmiklautz were suggesting to use your printer as a redirected printer.

**Comment by morphinz** [comment]
@hardening I'm a big and desperet Lover. Just tell me how can i love it.. :)   
You really don't understand or you cant accept what i'm saying.   
USB redirection working and i can use it. I'm able to reach this device with xfreerdp.  
  
But Windows RDP and Xfreerdp changs something while attaching the device.   
The simplest way to see that, examine the pictures.   
In regedit registry: Capabilities "Reg_dword" value at local computer, citrix, vmware and any other redirection program value is: 148  
  
When i redirect with RDP or Xfreerdp This value is 134 and we have no USB serial number...  
I think my real problem is rdp not bring Usb serial number with direction.

**Comment by akallabeth** [comment]
@morphinz That is exactly the issue with the USB channel ;) It is 'working' sometimes but not others. Kind of unstable and not really up to do what you would expect.

**Comment by akallabeth** [comment]
Fixed with #5745
