### ISSUE TITLE
NUM Lock state and led not synced

### ISSUE THREAD

**Issue by trentasis** [FreeRDP/FreeRDP#3868]
Hi,

I have detected with latest versions (master branch) that in some situations (random and not easy to reproduce) num lock is not  synced, and after some time led appear on but num lock is not working, and to recover this features we have to disable num lock (off) and then numeric pad works....

I have detected that when is not working you restart freerdp client then num lock sync is restored automatically, but after some time fails...

I have searched issues related with num lock sync, but any clear information is detected, environment used is latest freerdp (with /kbd:0x0000040A /bpp:16 /u:'' /d:domain /smartcard /cert-ignore /sec:tls +auto-reconnect), keyboard spanish, windows 2012r2 + session broker 

Additional information, I have tried with rdesktop 1.8.3 and with this versions works correctly

Some bugs related with this issue and not solved:
https://github.com/FreeRDP/FreeRDP/issues/794
https://github.com/FreeRDP/FreeRDP/issues/2219
https://github.com/FreeRDP/FreeRDP/issues/2671
https://github.com/FreeRDP/FreeRDP/issues/2083
https://github.com/FreeRDP/FreeRDP/issues/773

What can I do? Anybody can help?

Thanks

**Comment by bmiklautz** [comment]
@trentasis what are you using server side? - Do you have a way to reproduce?

**Comment by trentasis** [comment]
server side is windows 2012r2, do you need any additional information?
It is not easy I'trying to reproduce... If I can reproduce what do you need to debug this issue?

thanks

**Comment by trentasis** [comment]
hi @bmiklautz 

I think that I have found how to reproduce this error:
Environment 
- 3 rdesktop server with windows 2012 r2
- 1 session host with windows 2012 r2
- 3 rdesktop server balanced by round robin dns

To reproduce error with latest freerdp:
- Try to connect to dns name (round robin) and then asks user for server 1, but after this session hosts redirects this session to other hosts, for example server 2 o 3, and then when is redirected to a second auth in this server then num lock is in reverse order, num lock led is on but num keypad is not working, if you shutdown num lock led, then numericla keypad works...
- If sessions hosts doesn't make any additional redirection to a second server num lock sync works, only fails when a server redirection is made and fail since initial rdp login and inside rdp session

I have tried to make some change with https://github.com/trentasis/FreeRDP/commit/ed97d8418b1551ade95f4b5df723351f590a41b7

add a third xf_keyboard_focus_in(xfc);

as it was described in a previous/simialr issue https://github.com/FreeRDP/FreeRDP/pull/1470, but without success

Can you help?

thanks

**Comment by trentasis** [comment]
hi @bmiklautz 

Do you have any news about this issue?

Thanks

**Comment by jidet** [comment]
Hi,
To synchronize the LEDs of the keyboard it is necessary to press twice on "VerMaj"
Have you found another solution?
Thanks

**Comment by trentasis** [comment]
not, while is not solved we are using rdesktop. We are waiting a solution,
this bug is a handicap for users...

El divendres, 28 d’abril de 2017, jidet <notifications@github.com> va
escriure:

**Comment by akallabeth** [comment]
Does adding ```freerdp_set_focus(instance);```  at the end of ```xf_post_connect``` solve the issue for you?

**Comment by jidet** [comment]
Sorry, I'm a novice, can you explain how to add it?
Thanks

**Comment by gnshkl1** [comment]
any update on above issue

**Comment by akallabeth** [comment]
@gnshkl1 Well, waiting for feedback...

**Comment by trentasis** [comment]
Hi,

This "Does adding freerdp_set_focus(instance); at the end of xf_post_connect solve the issue for you? "

Was applied in master branch and can be tested with latest version?

Thanks

**Comment by akallabeth** [comment]
@trentasis No, as I'm lacking resources to test the described scenario it would be great to get some feedback first before blindly committing something to master.

**Comment by gnshkl1** [comment]
@trentasis any update on this issue,have you verified it?

**Comment by trentasis** [comment]
OK, I'll try to test and reports the results
Thanks

**Comment by akallabeth** [comment]
any update?

**Comment by trentasis** [comment]
OK, I'll try to check and validate if this is solved

2018-05-03 14:58 GMT+02:00 akallabeth <notifications@github.com>:

**Comment by akallabeth** [comment]
No feedback, closing.
Note: Redirection handling has been overhauled, this might actually have fixed the issue, but without proper feedback this is just a guess.
