### ISSUE TITLE
choppy microphone input

### ISSUE THREAD

**Issue by geiseri** [FreeRDP/FreeRDP#3872]
I am using Windows 10 and trying to use Skype.  It is very strange, I get great webcam performance with USB redirection and can stream 1080p videos from youtube and play pandora.  For the life of me though I cannot get the microphone to smoothly connect.  Every time I try to record audio I get only bits and pieces of the recording.  When I try to use skype its all choppy.

This is my build configuration:
```
[geiseri@luna ~]$ xfreerdp /buildconfig
This is FreeRDP version 2.0.0-dev (git 7d6f9581c)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=ON WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RELWITHDEBINFO
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -msse2
Compiler:            GNU, 6.3.1
Target architecture: x64
```
and here are my connection arguments:
```
xfreerdp /v:10.0.5.31 /u:usbtest /d:development /size:90% /usb:id,dev:04f2:b451 /sound:sys:pulse /multimedia:sys:pulse /echo /network:lan /gfx:AVC444 /disp +clipboard /bpp:32 /nsc /microphone:sys:pulse
```

I am also using Arch linux, but I have duplicated this on Ubuntu as well as other PCs.  I am also using pulse audio, but even when I try to use alsa directly I get the same choppy input.

**Comment by akallabeth** [comment]
does it work with /microphone:sys:alsa ?

**Comment by geiseri** [comment]
I tried it with ```/microphone:sys:alsa``` but Skype and Google Hangouts are still choppy and scrambled.

**Comment by geiseri** [comment]
I just noticed that on my system if I set ```PULSE_LATENCY_MSEC``` to a value of 60 then I get something that I can at least make out sounds on the other end.  Is it possible that there is some sort of issue with how FreeRDP reads from pulse?

**Comment by akallabeth** [comment]
@geiseri Ok, will investigate. Sadly my headset just broke, will take a day or two ;)

**Comment by geiseri** [comment]
As an update with alsa, I did notice on my configuration alsa is routed via pulse so it may have not been a good test.  I am going to try on a system with pulse disabled completely and use alsa.  This is not ideal for my final configuration since I rely on pulse for my desktop, but it might narrow down the root cause.

**Comment by akallabeth** [comment]
@geiseri Ok, tried it locally. Working without glitches, but I suspect there is a bandwidth issue with your setup. USB redirection is quite demanding, so does the sound redirection also have these issues when not using USB redirection?

**Comment by akallabeth** [comment]
@geiseri Oh, did try ```pulse``` and ```alsa``` just for reference.

**Comment by geiseri** [comment]
What OS are you on?

**Comment by akallabeth** [comment]
@geiseri Using debian jessie with backports. CPU/RAM is quite negligible for this (except when trying to run 4k monitors). Audio is ```Audio device: Intel Corporation 82801JI (ICH10 Family) HD Audio Controller```
Remote end is a windows 10 machine connected with 1Gbit lan.

**Comment by geiseri** [comment]
@akallabeth Did you make any changes to your pulse/daemon.conf and pulse/default.pa?  Also what desktop environment are you running if any?

**Comment by geiseri** [comment]
@akallabeth on the remote host, is that a physical machine, or a virtual machine?

**Comment by akallabeth** [comment]
@geiseri
 * Running gnome or cinnamon (tested both).
 * The remote end is a physical windows 10 machine.
 * Default configuration of debian for pulse

**Comment by geiseri** [comment]
I have an interesting experiments.  The first thing I did was set ```load-module module-udev-detect tsched=0``` in my ```/etc/pulse/default.pa```.  This seemed to radically help sound input quality.  

Then I tried setting the format to different types.  One commandline is:
```xfreerdp /v:10.0.5.xx /u:xxx /p:xxx  /size:90% /microphone:sys:pulse,format:17 /sound:sys:pulse,format:17 /multimedia:sys:pulse /echo /network:lan /gfx:rfx /disp +clipboard /bpp:32 +compression +gfx-thin-client +async-input -aero -themes -wallpaper /gdi:sw /usb:id,dev:04f2:b451```
the other is:
```xfreerdp /v:10.0.5.xx /u:xxx /p:xxx  /size:90% /microphone:sys:pulse /sound:sys:pulse /multimedia:sys:pulse /echo /network:lan /gfx:rfx /disp +clipboard /bpp:32 +compression +gfx-thin-client +async-input -aero -themes -wallpaper /gdi:sw /usb:id,dev:04f2:b451```

I have attached the resulting files from Voice Recorder.
[automatic format selection recording.zip](https://github.com/FreeRDP/FreeRDP/files/861520/automatic.format.selection.recording.zip)
This one is smoother, but has random drops.

[0x11 format selection recording.zip](https://github.com/FreeRDP/FreeRDP/files/861521/0x11.format.selection.recording.zip)
This one lacks the random drops, but has audio artifacts.

**Comment by akallabeth** [comment]
@geiseri Ok, I think I got it. Currently microphone is only redirecting PCM, ADPCM and A/ULAW compressed format. In https://www.ietf.org/rfc/rfc2361.txt possible formats are listed, but only those above (high bandwidth/high quality and low bandwidth/low quality) are supported. Something covering the middle ground is currently not implemented, so it is quite prone glitches.

**Comment by geiseri** [comment]
If I use A/ULAW (format:6/format:7 I think) I do not get any audio input or output.  If I set it to format:1 is this the same as not setting format at all?  Also I noticed in the auidin_pulse.c:252 there is a switch on 8 or 16bits.  How is that propagated?  Or do you think going from 16 to 8 bits won't matter.

**Comment by akallabeth** [comment]
@geiseri the formats there are only the ones the client supports. Forcing a specific format if the server has that one disabled will result in no audio at all.

**Comment by aszlig** [comment]
@akallabeth: Why was this issue closed? Is there a fix for it and if yes, where do I find it? Tried the current `master` version and can confirm that the issue is still persisting.

**Comment by akallabeth** [comment]
@aszlig Ok, after going through this issue, I've opened #4309 as a feature request (which covers the issue you have with microphone redirection)

**Comment by aszlig** [comment]
@akallabeth: I'm not sure this is really related to just codec support, because after setting the latency to 100ms in [audio_pulse_open](https://github.com/FreeRDP/FreeRDP/blob/876a7697be2efb2d22ac300a4e80c68f9ee86831/channels/audin/client/pulse/audin_pulse.c#L466) and using the `tsched=0` workaround mentioned in https://github.com/FreeRDP/FreeRDP/issues/3872#issuecomment-288398788, the input still has some artifacts but now voice input is at least recognizable.
