### ISSUE TITLE
xfreerdp hangs when connecting to virtual machine, which is being restored from snapshot (checkpoint)

### ISSUE THREAD

**Issue by mnowaksuse** [FreeRDP/FreeRDP#3876]
I connect to the Windows Server 2012 R2 Hyper-V server via `/vmconnect:$vmguid` option. When I run `Restore-VMSnapshot -VMName $vmname -Name $snapname -Confirm:$false` on the server, the RDP connection is closed (which is OK). However, when I try to re-connect it often happens, that `xfreerdp` is hung - won't fail, won't connect either.

It easily reproducible with following shell script:
```shell
while true; do
  xfreerdp /vmconnect:$GUID ...
done
```

How to reproduce: Run `Restore-VMSnapshot` on host, RDP connection closes, the scripts re-iterates (will fails couple of dozen times, but eventually hungs in limbo).

Happens with freerdp-2.0.0~git.1463131968.4e66df7-2.18.x86_64 from openSUSE Leap 42.2 as well as with current FreeRDP master from https://build.opensuse.org/package/show/home:hendwolt/freerdp (revision 79).

**Comment by byteboon** [comment]
Sounds like what I'd expect if the VM's listening socket is no longer actively refusing connections (immediate fail) and is now just not responding (long ~2 minute fail).  Does it eventually fail after two minutes or so?  If it does, this is normal TCP/IP behaviour...

**Comment by mnowaksuse** [comment]
@byteboon Thanks for the hint. I'll try the 2 minutes timeout then.

**Comment by mnowaksuse** [comment]
@byteboon It did not fail even after 5 minutes for me. Attaching strace logs in hope that they are are of some relevance:

[strace.log.5407.txt](https://github.com/FreeRDP/FreeRDP/files/905729/strace.log.5407.txt)
[strace.log.5406.txt](https://github.com/FreeRDP/FreeRDP/files/905730/strace.log.5406.txt)

**Comment by akallabeth** [comment]
Not much we can do here (if the connection is not established, it will end, but if it can connect but nothing happens, well...)
