### ISSUE TITLE
something wrong with GetComputerNameA or Test_GetComputerName ?

### ISSUE THREAD

**Issue by chipitsine** [FreeRDP/FreeRDP#3881]
https://travis-ci.org/chipitsine/FreeRDP/jobs/215059966#L5853

tests fails because computername returned by GetComputerNameA is longer than 32
should we modify the function to truncate computername to the 32 chars ?
or should we disable this test ?

**Comment by ilammy** [comment]
These are definitely related: #3815,  #3816

**Comment by chipitsine** [comment]
so, should we set hostname to 33 chars _before_ running the test ?

**Comment by akallabeth** [comment]
Looks like there is still an issue with the ```GetComputerName``` function.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724220%28v=vs.85%29.aspx has details on what should be returned. Still need to find a proper way to map computer names to netbios names (the limitations of the MS world do not apply to the rest)

**Comment by akallabeth** [comment]
the limitations are not required for our use case, we just take any length returned and do not assume anything.
