### ISSUE TITLE
Connection to RDP Server via Connection Broker asks twice for credentials

### ISSUE THREAD

**Issue by Bottson** [FreeRDP/FreeRDP#3885]
Hello,

i am using FreeRDP version 1.1.0-beta1 (git n/a).
I would like to connect to a TS with command: xfreerdp /v:IPADRESS /u:User /d:Domain /sec:tls

After entering my password now in RDP Session i get redirected from broker to a server.
Until now everything works fine. After redirecting me it asks me again for my credentials. 

Using command: xfreerdp /v:IPADRESS /u:User /d:Domain /sec:nla everything works normally, but i have to enter my credentials through command line. I would like to enter my credentials in RDP Session. So its easier for my Users. 

Is there any possibility that i reach to enter credentials once in RDP Session? I google now for days and tried mostly anything found on the internet. 

Thanks for support.

**Comment by akallabeth** [comment]
Please have a look at https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Since you're also using quite an old version try https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds
