### ISSUE TITLE
hi, 安装ios手册步骤进行安装 出错

### ISSUE THREAD

**Issue by Jianghaibo7815** [FreeRDP/FreeRDP#3887]
The target system is: Darwin - 1 - armv7
The host system is: Darwin - 16.4.0 - x86_64

请问下 这个要怎么解决！

**Comment by akallabeth** [comment]
@Jianghaibo7815 Sorry, the tracker language is english.
See https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by weihaigang** [comment]
都是英文看不懂  就一个中文顶起  让大神来拯救我们吧
