### ISSUE TITLE
ALT-CLICK does not work

### ISSUE THREAD

**Issue by roms2000** [FreeRDP/FreeRDP#3888]
In remote desktop, ALT-TAB is working like expected, but if I do ALT-TAB, keep pressing ALT then select a running app from list with a mouse click, it does not work : I have to do ALT-SHIFT-CLICK instead of ALT-CLICK.
In FreeRDP 1.1, ALT-TAB then ALT-CLICK was working well.

This issue was tested on 2008r2 and 2016 srv with both version of FreeRDP (1.1 and latest git).

I have tested the simple ALT-CLICK without ALT-TAB on a text editor and the result is the same

Can we change this and revert back to the working combinaison ?

**Comment by nfedera** [comment]
Just tested this, issue confirmed.

**Comment by abma** [comment]
in photoshop this key combination is needed for the clone stamp tool. in an older version of freerdp this worked, in 2.0.0-dev this doesn't work any more.

i couldn't find a workarround for this, +unmap-buttons doesn't change behaviour.

**Comment by ilammy** [comment]
Could you please clarify the steps? Because I am not able to reproduce the issue with my Windows 7 VM with the latest master and the default command line (running in GNOME 3 environment of Debian 8).

1. Open three windows (A, B, C). A is currently active.
2. Press Alt, press Tab, release Tab, keep Alt pressed. B gets selected in the Alt-Tab list.
3. Click C. At this point Alt-Tab menu disappears and C gets activated.

What am I doing wrong?

The event sequences sent to the RDP server seems sane in my case, as expected: press Alt, press Tab, release Tab, press Mouse1, release Mouse1, (later) release Alt. No keyboard resets or whatever.

**Comment by nfedera** [comment]
@ilammy for me it was easy to reproduce (and still is).
- open notepad, calc and cmd 
- minimize all windows
- press alt, keep it pressed
- press and release tab (alt still down)

Now the taskswitcher appers like this:

![image](https://cloud.githubusercontent.com/assets/670606/26543226/55b6de62-445d-11e7-8cc0-726107c18602.png)

Now with alt still down left-click on e.g. the calc icon and there is no reaction with current xfreerdp.

**Comment by ilammy** [comment]
I have managed to reproduce it with XFCE :tada: but not with GNOME 3. So this may be some window manager stupidity. Logging the events shows that FreeRDP window does not receive mouse press-release events when Alt is held down. XFCE has reserved this combination as a feature for moving windows, so I don't think that FreeRDP can do something about it (at least without ugly hacks).

@nfedera, @roms2000, what window manger do you use?

**Comment by abma** [comment]
oh, indeed. I'm using lxde which uses openbox as windomanager.

when i disable all mouse-bindings it seems to work (=delete all contents inside the <mouse> </mouse> section):

http://openbox.org/wiki/Help:Bindings#Mouse_bindings

in my case the config file is ~/.config/openbox/lxde-rc.xml

**Comment by roms2000** [comment]
This is the same for me (lxde / icewm).

But, note with FreeRDP 1.1 and the same environment, ALT+CLICK is working well but not with FreeRDP git version.

**Comment by akallabeth** [comment]
@roms2000 That is what ```+unmap-buttons``` is for.  When adding that to the command line the behaviour is the same as with 1.1 version.
Other than that, it is working here with gnome and openbox, along with the response from @abma I'll consider this fixed.
