### ISSUE TITLE
Support /shadow

### ISSUE THREAD

**Issue by amluto** [FreeRDP/FreeRDP#3889]
mstsc can shadow directly using /shadow.  Could you add this to xfreerdp?

**Comment by bmiklautz** [comment]
@amluto this was recently discussed on our development mailing list. 

The /shadow parameter unfortunately involves other protocols and interfaces than RDP (SMB/RPC/..) and is to difficult to support.
For details have a look to the mailing list thread regarding this: https://sourceforge.net/p/freerdp/mailman/message/35679299/
