### ISSUE TITLE
Private CA error message gives user invalid instructions

### ISSUE THREAD

**Issue by mikenor** [FreeRDP/FreeRDP#3890]
I am using a private CA. FreeRDP gives me the following error message:

> The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the documentation on how to create local certificate store for a private CA.

I looked at the documentation (man page) and it does not say anything about how to create a local certificate store. The error message seems to be giving invalid instructions (i.e., it is telling the user to read documentation that does not actually exist).

**Comment by bmiklautz** [comment]
Currently FreeRDP doesn't have an extra certificate store and uses the systems (openssl) certificate store. If you add your ca certificate to the systems store the verification should work (assuming the hostname matches).

**Comment by bmiklautz** [comment]
@mikenor and just to note it: the warning is really misleading (and wrong ;).

**Comment by mikenor** [comment]
Thanks, adding the CA cert to the openssl store worked great - once I knew that that's what I needed to do. ;-) Would be nice to see the error message adjusted to reflect reality.
