### ISSUE TITLE
ClearCodec error when connecting windows8.1 with remoteFX

### ISSUE THREAD

**Issue by wizwizcao** [FreeRDP/FreeRDP#3893]
Logs -

```c
[11:25:12:969] [80313:b031d000] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[11:25:13:497] [80313:b05a7000] [WARN][com.freerdp.gdi] - avc420_decompress failure: 0, ignoring update.
[11:25:14:360] [80313:b05a7000] [ERROR][com.freerdp.codec.clear] - vBarEntry->count 25 != vBarHeight 8
[11:25:14:361] [80313:b05a7000] [ERROR][com.freerdp.codec.clear] - clear_decompress_bands_data failed!
[11:25:14:361] [80313:b05a7000] [ERROR][com.freerdp.gdi] - clear_decompress failure: -1
[11:25:14:363] [80313:b05a7000] [ERROR][com.freerdp.channels.rdpgfx.client] - context->SurfaceCommand failed with error 1359
[11:25:14:363] [80313:b05a7000] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_decode failed with error 1359!
[11:25:14:363] [80313:b05a7000] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_recv_wire_to_surface_1_pdu failed with error 1359!
[11:25:14:364] [80313:b05a7000] [ERROR][com.freerdp.channels.rdpgfx.client] - Error while parsing GFX cmdId: RDPGFX_CMDID_WIRETOSURFACE_1 (0x0001)
[11:25:14:364] [80313:b05a7000] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_recv_pdu failed with error 1359!
[11:25:14:364] [80313:b05a7000] [ERROR][com.freerdp.channels.drdynvc.client] - drdynvc_order_recv failed with error 1359!
```

Checked the similar issue #3527 , it looks the same issue is still there? Tested on the latest version. Connected from an iOS client, does it matter? 
@akallabeth

**Comment by akallabeth** [comment]
@wizwizcao Could you please clarify what ```latest version``` is and what you mean by ```iOS client```? Did you use the iOS client of FreeRDP or did you use FreeRDP as the server?

**Comment by wizwizcao** [comment]
@akallabeth Thanks for the quick response. For <code>latest version</code>, it just means the current code of FreeRDP. For <code>iOS client</code>, use the iOS client. The server is windows 8.1. And one more thing to clarify is this issue is occurred when GFX is enabled, not remoteFX actually. It is running fine with remoteFX but no GFX.

**Comment by wizwizcao** [comment]
Patching some logging, and it shows this would happen in the "VBAR_CACHE_HIT" process right after a "SHORT_VBAR_CACHE_MISS".

**Comment by akallabeth** [comment]
@wizwizcao Ok, that clarifies a bit, but ```current code``` is you compiled the client yourself from ```master``` branch? A git commit would clarify that ;) Oh, and just to check, did you restart the windows 8.1 machine, I've seen it behaving 'strange' sometimes even when using MSTSC

**Comment by wizwizcao** [comment]
@akallabeth I didn't try any git clone or git commit yet. Just download the code and compile. First run the openssl script to setup the libraries, and then run command <code>cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -DIOS_PLATFORM=SIMULATOR -DWITH_IOSAUDIO=ON -GXcode</code> to build the Xcode project. Then open the project in Xcode, build and test.

It was working fine with either remoteFX or gfx enabled. But when I turned both of them on, the errors occurred.

I've tried restart the windows8.1 but did not work :-|

**Comment by akallabeth** [comment]
@wizwizcao Ok, downloaded from where? Please be more specific, otherwise I can just guess what is going on.

**Comment by wizwizcao** [comment]
@akallabeth from the [git home](https://github.com/FreeRDP/FreeRDP). I guess I'd better do a clone to make sure everything is up-to-date;)

**Comment by akallabeth** [comment]
@wizwizcao Oh, just scrolled though your logs again, did you activate AVC420/H264?

**Comment by wizwizcao** [comment]
@akallabeth Oh yes, I did some test with AVC420/H264 activated. And some test with no AVC420/H264. This issue could happen in both scenarios.

**Comment by wizwizcao** [comment]
@akallabeth Tried aFreeRDP and no clear codec problem. Noticed that android has no h264 in default. So, this issue is caused by the AVC420/H264 activated in iOS side? Is there any work around to iOS h264 for now?

**Comment by akallabeth** [comment]
@wizwizcao ClearCodec/H264 use both the same paths. There must be some different issue leading to this. Since a similar issue has been solved some months ago I assume you have an older version (maybe 1.1 branch?) but I can not be entirely sure.

**Comment by wizwizcao** [comment]
@akallabeth not exactly. Right after this issue detected, the current master has been git-cloned to my machine. Went through the same building steps, and the issue reproduced. Steps as following:
1. git clone the master code
2. run OpenSSL-DownloadAndBuild.command to build the openssl libraries
3. run `cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -IOS_PLATFORM=SIMULATOR -GXcode`
4. open the Xcode project (Xcode v8.2.1)
5. set executable scheme iFreeRDP
6. build and run
7. add a connection/bookmark for a windows 8.1 host
8. in the `Performance` configuration, enable `remoteFX`, `GFX`, `H264`
9. connecting

The connection itself is ok, I can hear the music is playing, but just no pictures. And the error messages will come out, e.g.
```
24:41:194] [32837:006b8000] [ERROR][com.freerdp.codec.clear] - vBarEntry->count 10 != vBarHeight 16
[19:24:41:196] [32837:006b8000] [ERROR][com.freerdp.codec.clear] - clear_decompress_bands_data failed!
[19:24:41:198] [32837:006b8000] [ERROR][com.freerdp.gdi] - clear_decompress failure: -1
[19:24:41:202] [32837:006b8000] [ERROR][com.freerdp.channels.rdpgfx.client] - context->SurfaceCommand failed with error 1359
[19:24:41:203] [32837:006b8000] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_decode failed with error 1359!
[19:24:41:203] [32837:006b8000] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_recv_wire_to_surface_1_pdu failed with error 1359!
[19:24:41:204] [32837:006b8000] [ERROR][com.freerdp.channels.rdpgfx.client] - Error while parsing GFX cmdId: RDPGFX_CMDID_WIRETOSURFACE_1 (0x0001)
[19:24:41:204] [32837:006b8000] [ERROR][com.freerdp.channels.rdpgfx.client] - rdpgfx_recv_pdu failed with error 1359!
[19:24:41:204] [32837:006b8000] [ERROR][com.freerdp.channels.drdynvc.client] - drdynvc_order_recv failed with error 1359!
```

Not sure if someone else can try to reproduce this issue.

---

Btw, in Android client, if enable the h264 with openh264, there will be numbers of white or black blocks. Just like some frame data get lost.
If do some update on the iOS code to prevent the clearcodec function breaking, i.e. comment out the return FALSE;
```
if (vBarEntry->count != vBarHeight)
{
    WLog_ERR(TAG, "vBarEntry->count %"PRIu32" != vBarHeight %"PRIu32"", vBarEntry->count,
				         vBarHeight);
    //return FALSE;
}
```
The screen view can be rendered, with numbers of white or black blocks, just like Android with openh264 ;(

**Comment by akallabeth** [comment]
@wizwizcao Does it work in MSTSC? There are some artefacts that seem to be server related.

**Comment by akallabeth** [comment]
@wizwizcao And what kind of H264 decoder do you use? OpenH264 is required for iOS too.

**Comment by wizwizcao** [comment]
@akallabeth Good catch! OpenH264 is not included in iOS. Let me figure out. Any guide docs would be great appreciated.
Btw, the MSTSC client is working fine, connecting the same windows 8.1. But it seems no AVC/H.264 codec processing? Checked the bandwidth.

**Comment by wizwizcao** [comment]
Hi @akallabeth ,
The issue is still there after OpenH264 enhanced in iOS.
And it also can be reproduced when connecting to windows 10.
And it happens just in random. Sometime everything is working fine, which looks really weird to me.

**Comment by akallabeth** [comment]
@wizwizcao and only on iOS, no others?

**Comment by wizwizcao** [comment]
@akallabeth so far, yes. 'cause I only checked iOS and Android. Not sure if Android is 100% ok, I've seen its screen get into mess sometime ago, need some time and more test to confirm.

**Comment by wizwizcao** [comment]
@akallabeth What's happening is, for somehow, the clearcodec bitmap stream sent to client just like: 
```
A...PDU#0
A...PDU#1
A...PDU#2
A...PDU#3
B...PDU#0
B...PDU#1
B...PDU#2
B...PDU#3
```
And this error occurred after the `B...PDU#0`(or could be any following `B...PDUs`) received.

Well, in debugging, we can find the **VBarStorage** and the **ShortVBarStorage** have been enriched by the `A...PDUs`, stored in the same **clear**. However, the `B...PDUs` seems recount the **VBAR_CACHE_HIT** vBarIndex from zero. Thus, it take some `A...PDU` by mistake, and that's why this error came out.

If simply add a code logic to reset the **V-Bar Storage Cursor** and the **Short V-Bar Storage Cursor** to zero once a **zero sequenceNumber** received, this issue looks not there any more. Please note this is just a test to verify, not a fix.

I assume the `B...PDUs` would contain a **CLEARCODEC_FLAG_CACHE_RESET** flag to indicate the **V-Bar Storage Cursor** and the **Short V-Bar Storage Cursor** should be reset to zero, but actually not.

So, currently, I am curious that is this kind of PDU data/messages correct? If correct, is this a bug in current clearcodec? If not correct, how to let the host send the right version?

**Comment by akallabeth** [comment]
@wizwizcao Ok, that could explain the issue. I've reread the spec [MS-RDPEGFX] but nowhere I could find that kind of reset mentioned there. Maybe I'm missing something or you just found the bug. (I assume your server end is windows 8.1 as mentioned earlier?)

**Comment by wizwizcao** [comment]
@akallabeth agreed. [MS-RDPEGFX] just mentioned the cursors need to be reset when the flag **CLEARCODEC_FLAG_CACHE_RESET** meet, i.e. section**2.2.4.1**. And the FreeRDP implementation is ok according to this doc.

What's happening is, the remote connections I am doing these days just tell me these kind of `B...PDUs` recounted the VBarIndex from 0, with no **CLEARCODEC_FLAG_CACHE_RESET** flag. And I noticed this issue only occurred in the first-time rendering the desktop, right after the remote connection established. If the first-time rendering is ok, then the following operations/processes would be fine.

And yes, my server end is windows8.1, and windows10 has been tested too. This issue could happen in both.

**Comment by akallabeth** [comment]
@wizwizcao You could try reverting ```6fec7e591d06dc6375e83688e55baf538001b8f5``` and see if it works for you. There was an issue with resetting at that time, maybe this patch just hid another issue.

**Comment by wizwizcao** [comment]
@akallabeth Reverting `6fec7e591d06dc6375e83688e55baf538001b8f5` could work for me for now, for both windows8.1 and windows10.

Actually, I've seen the similar issue as #3642 when connecting to a windows8.1 virtualized on a windows server 2012 r2. I guess there is something not on the right way, but `6fec7e591d06dc6375e83688e55baf538001b8f5` may not be a thoroughly fix.

**Comment by wizwizcao** [comment]
One quick update, when GFX+H.264 are working, turning off remoteFX and this issue is no longer there. And we'd better **not** reverting the `6fec7e591d06dc6375e83688e55baf538001b8f5`.

**Comment by realjiangms** [comment]
I also met clear code error with following error (but no vbar errors), on latest master(1dbd2d28d94f0ac21b3b000eaaa8fa9d1fb638e4) 
>>> /opt/freerdp-nightly/bin/xfreerdp /v:192.168.1.70 /u:Administrator /p:ldap4$ /rfx /f /gfx-h264
[11:04:46:124] [5173:5174] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[11:04:46:479] [5173:5174] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[11:04:46:479] [5173:5174] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[11:04:46:523] [5173:5174] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[11:04:46:565] [5173:5174] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[11:04:49:538] [5173:5183] [ERROR][com.freerdp.gdi] - clear_decompress failure: -1

However, it works fine with /gdi:sw.

**Comment by akallabeth** [comment]
still an issue?

**Comment by akallabeth** [comment]
Codecs have been hardened, should artifacts still apply after `2.0.0-rc4` please reopen/create a new issue.
