### ISSUE TITLE
error C2440:error c2440: type cast cannot convert from __m128i to char

### ISSUE THREAD

**Issue by whxloveyrh** [FreeRDP/FreeRDP#3898]
error file name:prim_YUV_opt.c
error line number: 58,65,71

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by bmiklautz** [comment]
@whxloveyrh please have a look at the page @akallabeth pointed out and provide more information otherwise this issues is completely useless for us :).

**Comment by anilbrowserstack** [comment]
I got the same error, environmental details mentioned below:
- Visual Studio 2013 Premium
- Windows 7 Professional 64-bit Operating system
- Intel(R) Xeon(R) CPU ES-2620 v2 @2.10GHz 2.10 GHz (2 processors)
- Dell
- Git code used: FreeRDP git Latest commit a1270ec

Issue: Compilation of Freerdp code succeeded, building it using Visual studio 2013 failed
Error C2440: 'initializing' : cannot convert from '__m128i' to 'char', File: prim_YUV_opt.c +58
Error C2440: 'initializing' : cannot convert from '__m128i' to 'char', File: prim_YUV_opt.c +65
Error C2440: 'initializing' : cannot convert from '__m128i' to 'char', File: prim_YUV_opt.c +71

**Comment by anilbrowserstack** [comment]
Need a clarification: I am able to build by disabling this conversion

If I disable the code block which does this conversion for visual studio versions > 2010 -> what is the net effect? Will I lose some critical functionalities?

**Comment by akallabeth** [comment]
@anilbrowserstack sounds like some troubles with includes. Check your configuration, the code compiles fine here on various versions of windows and visual studio.
