### ISSUE TITLE
pointer conversion issue in libwinpr/file/generic.c

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#3903]
I get 2 warnings in libwinpr/file/generic.c when compiling the current master with Open Build Service:

[   60s] [  7%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/file/generic.c.o
[   60s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/file/generic.c: In function 'GetFileAttributesExA':
[   60s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/file/generic.c:478:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
[   60s]   if ((hFind = FindFirstFileA(lpFileName, &findFileData) != INVALID_HANDLE_VALUE))
[   60s]              ^
[   60s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/file/generic.c: In function 'FindNextFileA':
[   60s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/file/generic.c:976:53: warning: right shift count >= width of type [-Wshift-count-overflow]
[   60s]     lpFindFileData->nFileSizeHigh = fileStat.st_size >> 32;
[   60s]                                                      ^~

The first one (line 478) makes the portability checks of OBS fail. Therefore it's not possible, to build this version on OBS.

The second one (line 976) occurs only in 32 bit builds.

[osTWbuild_log_20170406.zip](https://github.com/FreeRDP/FreeRDP/files/903549/osTWbuild_log_20170406.zip)

**Comment by akallabeth** [comment]
Already solved with #3902

**Comment by akallabeth** [comment]
Pull merged, closing. Reopen if still an issue.
