### ISSUE TITLE
[X11 hw gdi] render inactive elements wrong

### ISSUE THREAD

**Issue by verbavolant** [FreeRDP/FreeRDP#3907]
Hello, 

freerdp-nightly_2.0.0+0~20170405014834
ubuntu LTSP
windows 2008r2

xfreerdp-nightly /f /cert-ignore /sec:rdp +auto-reconnect +heartbeat /smartcard:THRC /drive:USB-Local,/media/root /sound:sys:pulse /microphone:sys:pulse /bpp:24 +fonts /v:xx.xx.xx.xx /usb:rules:allow /audio-mode:0 /mic /gfx /g
fx-thin-client

**Grey options are reproduced with wrong colours.**

"inserisci" word must be grey not black with double word. If i use snipping tool utility they're reproduced correctly.

Thanks

Marco

![image](https://cloud.githubusercontent.com/assets/27216842/24864399/5deff2dc-1e04-11e7-9d84-9bc275bf9f06.png)

**Comment by bmiklautz** [comment]
@verbavolant Ubuntu 16.04? -  The latest nightly should be 	
```
freerdp-nightly_2.0.0+0~20170407014828.373~1.gbp9fd397
```
can you please try updating and see if the problem is fixed. If it isn't would you please try with /gdi:sw as additional parameter?

**Comment by verbavolant** [comment]
@bmiklautz Ubuntu 16.10.

Installed last nightly, **it works** with /gdi:sw parameter! Thanks!
Is it a bug? a local driver problem?
(It seems slowly now).

thanks again

**Comment by akallabeth** [comment]
Looks like a bug in the X11 client code path. Are you using ```GFX``` in this setup (aka does the server actually send ```GFX``` data) or does it negociate old RDP GDI? Guess it is the latter but please confirm.

**Comment by verbavolant** [comment]
@akallabeth with or without GFX the problem remains.

@bmiklautz  it's the same onto:
Ubuntu 16.10 LTSP client
Debian stable LTSP client
Fedora 25 normal pc, not LTSP client

32 or 24 bpp

**Comment by akallabeth** [comment]
@verbavolant Can you give a list of programs you see this issue with?

**Comment by verbavolant** [comment]
@akallabeth try Total Commander, menù "Configuration->Options" for example.
Thanks

**Comment by akallabeth** [comment]
Ok, got it. ```GDI_PSDPxax``` mapping to X11 functions is wrong. Looks like there is no easy mapping, so this will require some investigations. Anyone time for that?

**Comment by ettorer** [comment]
Hi, I think this problem is the same as: [https://github.com/FreeRDP/FreeRDP/issues/3732](url)
Thanks

**Comment by frispete** [comment]
Hi, somebody with sufficient permissions might want to rename this issue in order to raise chances of locating it independently. Here's my suggestion: 

**X11 disabled font rendering problem**

Thanks and Cheers

**Comment by akallabeth** [comment]
This is an issue with mapping legacy RDP operations to X11 operations.
Just remove `/gdi:hw` and the issue is fixed.
