### ISSUE TITLE
Hard coded automount paths for disk redirection

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#3909]
#3864 introduced better disk redirection support (naming, ...) but introduced a hard coded ```/media``` check. This path is more or less ubuntu only. @DavBfr Could you have a look at the ```udisks2``` documentation to get the proper path for the distribution used?

**Comment by akallabeth** [comment]
Had a look at ```udisks2```, looks like the paths are hard coded to ```/media/<username>``` or ```/run/media/<username>```

**Comment by akallabeth** [comment]
And then there is ```gvfs``` which mounts to ```/run/user/<uid>/gvfs```

**Comment by DavBfr** [comment]
@akallabeth, #3864 made no change on /media, it is checked only if you use the hotplug system to mount/umount removable disks.
Command line /drive:*

**Comment by akallabeth** [comment]
ok. just recognised that this path is distribution dependent. may need some additional locations to catch all automount options.
