### ISSUE TITLE
Large black rectangle with /gfx in multi-monitor setup

### ISSUE THREAD

**Issue by T3N4K4** [FreeRDP/FreeRDP#3910]
Is it normal that I get a large black rectangle on my second monitor when using /gfx (it does not matter which gfx option I use)?
This only happens when I use /f /multimon:force to force the windows session (windows 2012r2) to be extended instead of stretched (<=which works).

xfreerdp /u: /p: /d: /v: /gdi:hw /f /multimon:force /bpp:32 -sec-tls +sec-nla /gfx:RFX -bitmap-cache /sound:sys:pulse,quality:high,latency:50 -compression /network:lan -fonts -aero -window-drag -menu-anims -themes +wallpaper -clipboard

I see the mouse on the second monitor but I cannot see any application which opens there or is moved on the second screen.

**Comment by nfedera** [comment]
@T3N4K4 That's definitely not normal. Does it work with `/gdi:sw` instead of `/gdi:hw` ?

**Comment by T3N4K4** [comment]
@nfedera Yes it works with /gdi:sw.

**Comment by nfedera** [comment]
@T3N4K4 I can reproduce the issue and have already identified the culprit. A fix is in progress.

**Comment by T3N4K4** [comment]
@nfedera Thank you :)

**Comment by nfedera** [comment]
@T3N4K4 The fix is in master now. Please confirm and close the issue if it works for you.

**Comment by T3N4K4** [comment]
@nfedera Thank you for your very fast response, works for me.
