### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Jianghaibo7815** [FreeRDP/FreeRDP#3914]
Hi, 
    I try to compile FreeRDP from master with Mac OS Sierra 10.12.3 64-Bit and XCode 8.2.1 SDK 10.2  CMake 3.2.1
    I use the following commands: 
 ./scripts/OpenSSL-DownloadAndBuild.command     
 cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode -DIOS_PLATFORM=SIMULATOR

the shell ouput:
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk/usr/lib/libz.dylib (found version "1.2.8") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
CMake Error at /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpenSSL.cmake:325 (find_package_handle_standard_args)
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:740 (find_feature)

-- Configuring incomplete, errors occurred!
See also "/Users/haibo/Desktop/FreeRDP/CMakeFiles/CMakeOutput.log".
See also "/Users/haibo/Desktop/FreeRDP/CMakeFiles/CMakeError.log".

and CMakeOutput.log  content is : 
The target system is: Darwin - 1 - i386
The host system is: Darwin - 16.4.0 - x86_64

How to solve it ? Please give me a hand !

**Comment by VHurricaner** [comment]
I have this problem, too
os: 10.12.6
xcode:8.3.3
cmake:3.9.1
openssl:1.0.2L

How did you solve the problem? Can you please share?
Thanks!

**Comment by adityasood11** [comment]
After adding the folder FreeRDP-2.0.0-rc2 , i am getting the error 
" Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error at C:\Users\Mickey\Downloads\FreeRDP-2.0.0-rc2\FreeRDP-2.0.0-rc2\CMakeLists.txt:477 (message):
  Unknown generator Ninja	FreeRDP	C:\Users\Mickey\Downloads\FreeRDP-2.0.0-rc2\FreeRDP-2.0.0-rc2\CMakeLists.txt	477
