### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by Jianghaibo7815** [FreeRDP/FreeRDP#3915]
Hi,
I try to compile FreeRDP from master with Mac OS Sierra 10.12.3 64-Bit and XCode 8.2.1 SDK 10.2 CMake 3.2.1
I open iFreeRDP.xcodeproj  with xcode  and compile target iFreeRDP 

get Linker Error:
clang: error: no such file or directory: '/Users/haibo/Desktop/FreeRDP/client/common/Debug-iphonesimulator/libfreerdp-client2.a'
clang: error: no such file or directory: '/Users/haibo/Desktop/FreeRDP/winpr/libwinpr/Debug-iphonesimulator/libwinpr2.a'
...

how to solve it?

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by Jianghaibo7815** [comment]
I use the following commands:
./scripts/OpenSSL-DownloadAndBuild.command
cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode -DIOS_PLATFORM=SIMULATOR

after finished  I find  iFreeRDP.xcodeproj file  added  in   ios  dir.
then open it with xcode and compile
got 20 linker errors

how can I get the lib files  linked by the project ?
thinks!

**Comment by akallabeth** [comment]
Please ask questions on the mailing list or on IRC.
This is an issue tracker!
