### ISSUE TITLE
ios linker error 

### ISSUE THREAD

**Issue by Jianghaibo7815** [FreeRDP/FreeRDP#3916]
Hi,
I try to compile FreeRDP from master with Mac OS Sierra 10.12.3 64-Bit and XCode 8.2.1 SDK 10.2 CMake 3.2.1

I use the following commands:
./scripts/OpenSSL-DownloadAndBuild.command
cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode -DIOS_PLATFORM=SIMULATOR

after finished I find iFreeRDP.xcodeproj file added into ios dir.
then I open it with xcode and compile
got 20 linker errors

how can I get the lib files linked by the project ?
thinks!

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
