### ISSUE TITLE
Printing PDF via FreeRDP and share local Printers on Linux Mint doesnt work

### ISSUE THREAD

**Issue by FFS1** [FreeRDP/FreeRDP#3917]
Hello,

as written in Remmina https://github.com/FreeRDP/Remmina/issues/1158

I am facing troubles in printing PDF documents with FreeRDP.

What can i do to contribute more Informaitons to this error?

**Comment by FFS1** [comment]
I am using Version,

This is FreeRDP version 2.0.0~dev (git n/a)

And i google for freerdp install ubuntu and came to this Thread:

http://askubuntu.com/questions/501113/how-do-i-install-xfreerdp-11-on-to-ubuntu-12-04

Is there any other way i should go installing xfreerdp?

I am not a daily linux user, but looking out for another system than Win10, so Linux Mint is a quite good choice at this moment, except the problem with PDF printing from Terminalserver.

**Comment by akallabeth** [comment]
If you tell us which version of ubuntu you're using and if you use the provided xfreerdp that would help.
Other than that you could try if https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds is working.

**Comment by akallabeth** [comment]
@FFS1 Oh, and when you try xfreerdp the whole command line you use to connect (strip passwords, of course)

**Comment by FFS1** [comment]
I am using this command to connect xfreerdp /f /v:IP ADRESS /printer:HP-LaserJet-M402dn

I am using Linux Mint 18 Sarah, and 4.4.0-21-generic GNU/Linux

**Comment by FFS1** [comment]
Other than that you could try if https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds is working.

thank you, i have run this command:

sudo sh -c 'echo "deb http://pub.freerdp.com/repositories/deb/$(lsb_release -cs)/ freerdp-nightly main" >> /etc/apt/sources.list.d/freerdp-nightly.list'

But with apt-get update i receive the message Sarah is not available, i dont know which DEB is Linux Mint Sarah.

Can you reproduce the problem i am facing?

I have tried connecting to another Terminalserver with another Acrobat Version, and tried connecting to another Windows 10 Computer over RDP, but both boxes i get an error message that i cant connect, Firewall settings is OK, this is going to be a major failure if PDF printing is not working, would be really sad not to be able to use Linux instead of Windows, i want this change away from Win10.

**Comment by akallabeth** [comment]
@FFS1 Does it work when using ```/printer:<name>,<driver>```? Sounds like the default driver used (```MS Publisher Imagesetter``` is not what you want.

**Comment by FFS1** [comment]
What does i Need to enter for <Driver>?

**Comment by FFS1** [comment]
Just to make sure, as written in Remmina Thread, Documents with Word, Excel or Outlooks works fine, ist only the PDF which is not working

**Comment by FFS1** [comment]
Anything new about this? Am i the only one who is facing this Problem?

**Comment by akallabeth** [comment]
@FFS1 Did you figure it out? The driver name is the one in windows details tab. Needs to be installed on the machine though...
