### ISSUE TITLE
wfreerdp nightly, printer redirection not working

### ISSUE THREAD

**Issue by mnordstr** [FreeRDP/FreeRDP#3921]
Hi,

I've been trying to get printer redirection working from a Windows 7 (64) PC to W12R2 TS server but the nightly build and stable nightly does not seem to do anything regarding printers. Is printing supported on the nightlies?

Build:
`This is FreeRDP version 2.0.0-dev (git 736675a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSTREAMER_0_10=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_X264=OFF
Build type:          Release
CFLAGS:               /DWIN32 /D_WINDOWS  /Gd /W3
Compiler:            MSVC, 18.0.40629.0
Target architecture: x64
`

Log with trace gives only following if I try to connect with /printer:"Microsoft XPS Document Writer":
`[13:09:51:708] [4000:000009e4] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer [Microsoft XPS Document Writer] (static)
[13:09:51:708] [4000:000008bc] [DEBUG][com.freerdp.core.update] - Frame Marker Alternate Secondary Drawing Order (0x0D)
[13:09:51:708] [4000:000008bc] [DEBUG][com.freerdp.core.update] - Frame Marker Alternate Secondary Drawing Order (0x0D)
[13:09:51:710] [4000:000008bc] [DEBUG][com.freerdp.client.windows] - Main thread exited.
[13:09:51:710] [4000:0000057c] [DEBUG][com.freerdp.client.windows] - Keyboard thread exited.
`

That's the end of the log, it flashes the screen but does not connect to the terminal. If I only enter /printer it connects but with no printer redirection, and the relevant log line is only:
`[INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer (static)`

No printers detected or anything similar in the log.

**Comment by akallabeth** [comment]
@mnordstr Sorry for the late reply. Printing is supported and working with the nightlies. Looks like you have a command line error (the syntax is ```/printer:<device>,<driver>``` where printer is the name in windows and driver the driver name from the details tab.
