### ISSUE TITLE
Drive redirection shows big files instead of folders

### ISSUE THREAD

**Issue by T3N4K4** [FreeRDP/FreeRDP#3922]
State of freerdp: only missing the last two commits 4be62f7 and 736675a

CommandLine: xfreerdp /u: /p: /d: /v: +sec-nla /drive:"U","/shares/all" /cert-ignore to Server 2012R2

In /shares/all there are two folders (one link to an empty folder):
test -> /shares/devices/test

and one link to a mountpoint of a USB-drive:
JetFlash_Transcend8GB_sdb_1 -> /shares/local/JetFlash_Transcend8GB_sdb_1

When I now connect to the server and look up the "drive" U in the explorer I get two files.
One named after the link to the empty folder (76GB of size) and one named after the link of the mountpoint (in this case the name of the usb-drive => JetFlash_Transcend8GB_sdb_1) (176GB of size).
I cannot access the contents of the folders since they are both files with incorrect size.

**Comment by akallabeth** [comment]
so you have issues with links?

**Comment by T3N4K4** [comment]
I don't know if it is a problem with links.. but before the rework those links / folders were redirected.
I'll test it tomorrow with just the mountpoints instead of links.

**Comment by akallabeth** [comment]
I'll have a look.

**Comment by akallabeth** [comment]
@T3N4K4 Ok, verified. Links are not handled properly.

**Comment by akallabeth** [comment]
@T3N4K4 Ok, added it to the already pending drive hotplug fixes. Works for me, could you confirm?

**Comment by T3N4K4** [comment]
@akallabeth works for me. Thank you :)
