### ISSUE TITLE
Parameter /app-file isn't used

### ISSUE THREAD

**Issue by FPawlak2** [FreeRDP/FreeRDP#3933]
Hi guys,
is it possible to open local file in remoteapp? I think the argument "/app-file" is for it but can't make it.

I tried this without success - everytime notepad opens new file:
```shell
xfreerdp /v:192.168.56.99 /u:FPawlak /app:"||Notepad" /app-file:test.txt
xfreerdp /v:192.168.56.99 /u:FPawlak /app:"||Notepad" ~/app-file:test.txt
xfreerdp /v:192.168.56.99 /u:FPawlak /app:"||Notepad" /home/fpawlak/app-file:test.txt
```

as workaround I can use:
```shell
xfreerdp /v:192.168.56.99 /u:FPawlak /app:"||Notepad" /home-drive /app-cmd:z:\test.txt
```
But it will be nice if I can open the file directly without network drives

I ran above command on Linux Mint 18.1 Serena with xfreerdp from Mint package and xfreerdp from git

Version from Linux Mint package
```shell
fpawlak@FPawlak-Lap ~ $ xfreerdp /version
This is FreeRDP version 1.1.0-beta1 (git n/a)
```

Version from GIT
```shell
fpawlak@FPawlak-Lap ~ $ xfreerdp /version
This is FreeRDP version 2.0.0-dev (git 38ca328)
```

**Comment by ilammy** [comment]
@FPawlak2 I believe that's not possible in a way other than using disk drive redirection. Remote apps work by opening the same RDP session as always, the application executes on the remote machine, and FreeRDP just does some fancies to draw only the application window, without the desktop. There you _need_ something to access your local file system from the remote machine, that is disk drive redirection.

The `/app-file` command line argument does not seem to be used anywhere. From the context I can infer that it was intended for storing path to the remote application to run, not to the local file to pass to that application. However, it's not used anywhere except for the argument parsing code and settings file maintenance.

It could be possible to add a special case in the command line which will automatically enable disk drive redirection, redirect appropriate directory to the remote machine, and fixup the path to the file, but that seems 1) kinda overkill and redundant, 2) possibly insecure in case you don't intend to share other files. So I would recommend to simply use disk drive redirection in the way you are currently using it.

**Comment by bmiklautz** [comment]
@FPawlak2 as @ilammy said /app-file isn't really used (it was introduced when .rdp file support was added). 
Opening a file from the client without network drive redirection isn't possible. So please simply use /drive:sharename,directory.
