### ISSUE TITLE
Possible to expose binary serialization methods?

### ISSUE THREAD

**Issue by rossbrower** [FreeRDP/FreeRDP#3935]
I am trying to send order messages (e.g. memblt) over a socket with as little code (and as fast) as possible. I noticed libfreerdp\core\orders.h has a bunch of serialization methods. Can these be exposed or is there another way to serialize the orders for binary transport? Can I attach to a queue somewhere? Otherwise I need to subscribe to all of these update callbacks and copy the serialization code over to my project. Any help would be appreciated.

**Comment by bmiklautz** [comment]
@rossbrower for help please use the irc channel or the mailing list.
What functions in orders.h you are referring too?
When you receive the function they are kind of serialized. You could just forward them over the socket and parse them directly there.
