### ISSUE TITLE
Failed to run RemoteApp with full path

### ISSUE THREAD

**Issue by jixuyang** [FreeRDP/FreeRDP#3936]
1. I have read [issue 998](https://github.com/FreeRDP/FreeRDP/issues/998) and [issue 927](https://github.com/FreeRDP/FreeRDP/issues/927).
2. I have build it with the [latest freerdp-master source code] (https://github.com/FreeRDP/FreeRDP/commit/38ca328739dd2c6fc8befcfdf8caf7eaa2557bca), and try to launch a remote app with the following command line:
wfreerdp.exe /v:192.168.65.144 /u:myusername /p:mypassword /gdi:sw  /app:"C:\Windows\System32\cmd.exe"
3. And "C:\Windows\System32\cmd.exe" has added into allowed remote list. But the command line NOT work above, the error message is:

[10:13:28:264] [9824:000014cc] [DEBUG][com.freerdp.core.rdp] - recv Set Error Info Data PDU (0x2F), length: 22
[10:13:28:264] [9824:000014cc] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off his or her session on the server.
[10:13:28:264] [9824:000014cc] [DEBUG][com.freerdp.core.rdp] - DisconnectProviderUltimatum: reason: 3
[10:13:28:273] [9824:000014cc] [DEBUG][com.freerdp.client.windows] - Main thread exited.
[10:13:28:277] [9824:00001ae8] [DEBUG][com.freerdp.client.windows] - Keyboard thread exited.

4.  Then according to issue 998, I enabled "[group policy]
Computer Configuration/Administrative Templates/Windows Components/Remote Desktop Services/Remote Desktop Session Host/Connections/Allow remote start of unlisted programs", it works. 
5. Then according to issue 927, I changed full path into alias, it also works.

So my question is: why full path NOT work, it is a bug?
Thanks.

**Comment by jixuyang** [comment]
Using the following command line, it works:
wfreerdp.exe my.rdp /v:192.168.65.144 /u:myusername /p:mypassword /gdi:sw

And for my.rdp file, it just contains the following single line:
alternate shell:s:C:\Windows\System32\cmd.exe

**Comment by jixuyang** [comment]
Using the following command line to fix the problem:
wfreerdp.exe /shell:C:\Windows\System32\cmd.exe /v:192.168.65.144 /u:myusername /p:mypassword /gdi:sw

**Comment by adityasood11** [comment]
The current freerdp server which is working on my system is freerdp-shadow-cli which shares a running X display like with VNC but using the RDP instead. Now what i want is whenever a rdp client connects to my server , the user will get access to an application ( lets say notepad ) and he can work on that particular application. Other than that he should not get access to any other files.

Does your issue satisfy my issue @jixuyang ?

And can you please elaborate what you have done.

**Comment by akallabeth** [comment]
@adityasood11 please stop spamming the issue tracker, last warning.
As already told, please use the mailing list (and wait a bit, not everybody will jump when you ask)

**Comment by refusal** [comment]
@adityasood11 Did you find any solution for this? I have the same problem now.
