### ISSUE TITLE
Remote files are listed with huge wrong size under 32bit client platforms

### ISSUE THREAD

**Issue by AngelNone** [FreeRDP/FreeRDP#3939]
Good day. There was a problem. When you connect to RDP from Linux Mint, the files on the attached drive from the local computer increase the size from 2 bytes to 8 gigabytes. What is the problem with this problem? We use the latest version. When connecting with xreerdp the same problem, I attach a screenshot it may be easier to understand what is happening.

You can also view the reference on the link https://github.com/FreeRDP/Remmina/issues/1166 where the screenshots of the problem are indicated

**Comment by giox069** [comment]
I have been able to reproduce it on intel 32bit platforms. Not on 64bits.

**Comment by AngelNone** [comment]
On a 64 bit system, everything works well. There are no comments, only there is a 32 bit bit.

**Comment by ilammy** [comment]
I'd reckon this has to do something with the disk drive redirection refactoring in #3864.

**Comment by AngelNone** [comment]
I'm unfortunately not familiar with the internal mechanisms of the RDP client. Tell me how to solve this problem?

**Comment by giox069** [comment]
@AngelNone I don't think you can fix it by yourself if you are not a C programmer.
You should wait that someone of the FreeRDP team will fix it, and then we will push the fix to the Remmina PPA.

**Comment by akallabeth** [comment]
May be related to #3913. Fixed in https://github.com/akallabeth/FreeRDP/tree/shift_warn_fix
Can anyone give it a try and report back?

**Comment by AngelNone** [comment]
@akallabeth I'm new to Linux. I downloaded the folder from the link. Unzip it ... Then went to the link https://github.com/FreeRDP/FreeRDP/wiki/Compilation and step by step done what is said there except download. I made these steps from the folder in which I unzipped the downloaded archive. Everything went smoothly. But the problem did not dare I do not deny that maybe something did wrong.

**Comment by antenore** [comment]
@AngelNone maybe you can follow our guide? 

https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-16.04
Just change the FreeRDP repository with the akallabeth one.

Be sure to remove any previous version of FreeRDP and Remmina you have installed.

I don't have a 32bit platform so I cannot test myself and I think Giovanni is busy now.

**Comment by AngelNone** [comment]
When executing the command `cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_CUPS=on -DWITH_WAYLAND=off -DWITH_PULSE=on -DCMAKE_INSTALL_PREFIX:PATH=/opt/remmina_devel/freerdp .`  an error was raised
[CMakeError.txt](https://github.com/FreeRDP/FreeRDP/files/975591/CMakeError.txt)

**Comment by hardening** [comment]
@AngelNone please use IRC for build errors.

**Comment by AngelNone** [comment]
@hardening Sorry, did not quite understand what you want from me. Can be more simple language. I've worked very, very little with Linux, so it's very hard.
`user@nb310 ~/remmina_devel/FreeRDP $ sudo cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_CUPS=on -DWITH_WAYLAND=off -DWITH_PULSE=on -DCMAKE_INSTALL_PREFIX:PATH=/opt/remmina_devel/freerdp .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- FreeRDP GIT
-- Git Revision 7439299
-- Performing Test Wno-unused-result
-- Performing Test Wno-unused-result - Success
-- Performing Test Wno-unused-but-set-variable
-- Performing Test Wno-unused-but-set-variable - Success
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Success
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Success
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for pthread_tryjoin_np in pthread
-- Looking for pthread_tryjoin_np in pthread - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Finding recommended feature X11 for X11 (X11 client and server)
--     Disable feature X11 using "-DWITH_X11=OFF"
-- Found X11: /usr/lib/i386-linux-gnu/libX11.so  
-- Skipping recommended feature Wayland for Wayland (Wayland client)
-- Skipping optional feature DirectFB for DirectFB (DirectFB client)
--     Enable feature DirectFB using "-DWITH_DIRECTFB=ON"
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.8") 
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /usr/lib/i386-linux-gnu/libssl.so;/usr/lib/i386-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Skipping optional feature OpenSLES for multimedia (OpenSLES audio / video)
--     Enable feature OpenSLES using "-DWITH_OPENSLES=ON"
-- Finding recommended feature ALSA for sound (audio input, audio output and multimedia redirection)
--     Disable feature ALSA using "-DWITH_ALSA=OFF"
-- Found ALSA: /usr/lib/i386-linux-gnu/libasound.so (found version "1.1.0") 
-- Finding optional feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Checking for module 'libpulse'
--   Found libpulse, version 8.0
-- Found Pulse: /usr/include  
-- Finding optional feature Cups for printing (printer device redirection)
-- Found Cups: /usr/lib/i386-linux-gnu/libcups.so (found version "2.1.3") 
-- Skipping optional feature PCSC for smart card (smart card device redirection)
--     Enable feature PCSC using "-DWITH_PCSC=ON"
-- Finding recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Disable feature FFmpeg using "-DWITH_FFMPEG=OFF"
-- Checking for module 'libavcodec'
--   Found libavcodec, version 56.60.100
-- Checking for module 'libavutil'
--   Found libavutil, version 54.31.100
-- Found FFmpeg: TRUE  
-- Skipping optional feature GStreamer_0_10 for multimedia (multimedia redirection, audio and video playback, gstreamer 0.10 version)
--     Enable feature GStreamer_0_10 using "-DWITH_GSTREAMER_0_10=ON"
-- Finding recommended feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
--     Disable feature GStreamer_1_0 using "-DWITH_GSTREAMER_1_0=OFF"
-- Checking for module 'glib-2.0'
--   Found glib-2.0, version 2.48.2
-- Found Glib 
-- Checking for module 'gstreamer-1.0'
--   Found gstreamer-1.0, version 1.8.3
-- Checking for module 'gstreamer-base-1.0'
--   Found gstreamer-base-1.0, version 1.8.3
-- Checking for module 'gstreamer-app-1.0'
--   Found gstreamer-app-1.0, version 1.8.3
-- Checking for module 'gstreamer-audio-1.0'
--   Found gstreamer-audio-1.0, version 1.8.3
-- Checking for module 'gstreamer-fft-1.0'
--   Found gstreamer-fft-1.0, version 1.8.3
-- Checking for module 'gstreamer-pbutils-1.0'
--   Found gstreamer-pbutils-1.0, version 1.8.3
-- Checking for module 'gstreamer-video-1.0'
--   Found gstreamer-video-1.0, version 1.8.3
-- Found GSTREAMER_1_0: /usr/lib/i386-linux-gnu/libgstreamer-1.0.so  
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- FreeRDP GIT
-- Finding recommended feature XKBFile for X11 keyboard (X11 keyboard file extension)
--     Disable feature XKBFile using "-DWITH_XKBFILE=OFF"
-- Found XKBFile: /usr/lib/i386-linux-gnu/libxkbfile.so  
CMake Error at channels/client/CMakeLists.txt:27 (list):
  list sub-command REMOVE_DUPLICATES requires list to be present.


-- FreeRDP GIT
-- Found DocBookXSL: /usr/share/xml/docbook/stylesheet/docbook-xsl  
-- Finding required feature XShm for X11 shared memory (X11 shared memory extension)
-- Found XShm: /usr/lib/i386-linux-gnu/libXext.so  
-- Finding recommended feature Xinerama for multi-monitor (X11 multi-monitor extension)
--     Disable feature Xinerama using "-DWITH_XINERAMA=OFF"
-- Found Xinerama: /usr/lib/i386-linux-gnu/libXinerama.so  
-- Finding recommended feature Xext for X11 extension (X11 core extensions)
--     Disable feature Xext using "-DWITH_XEXT=OFF"
-- Found Xext: /usr/lib/i386-linux-gnu/libXext.so  
-- Finding recommended feature Xcursor for cursor (X11 cursor extension)
--     Disable feature Xcursor using "-DWITH_XCURSOR=OFF"
-- Found Xcursor: /usr/lib/i386-linux-gnu/libXcursor.so  
-- Finding recommended feature Xv for video (X11 video extension)
--     Disable feature Xv using "-DWITH_XV=OFF"
-- Found Xv: /usr/lib/i386-linux-gnu/libXv.so  
-- Finding recommended feature Xi for input (X11 input extension)
--     Disable feature Xi using "-DWITH_XI=OFF"
-- Found Xi: /usr/lib/i386-linux-gnu/libXi.so  
-- Looking for XITouchClass
-- Looking for XITouchClass - found
-- Finding recommended feature Xrender for rendering (X11 render extension)
--     Disable feature Xrender using "-DWITH_XRENDER=OFF"
-- Found Xrender: /usr/lib/i386-linux-gnu/libXrender.so  
-- Finding recommended feature Xfixes for X11 xfixes extension (Useful additions to the X11 core protocol)
--     Disable feature Xfixes using "-DWITH_XFIXES=OFF"
-- Found Xfixes: /usr/lib/i386-linux-gnu/libXfixes.so  
-- Configuring incomplete, errors occurred!
See also "/home/user/remmina_devel/FreeRDP/CMakeFiles/CMakeOutput.log".
See also "/home/user/remmina_devel/FreeRDP/CMakeFiles/CMakeError.log".`
Perhaps you had it in mind...

**Comment by akallabeth** [comment]
@AngelNone you're using the wrong sources

**Comment by antenore** [comment]
Later I'll have 32bit system where to test the patch and I'll connect on irc to discuss if I won't be able to fix myself.

**Comment by antenore** [comment]
Later I'll have 32bit system where to test the patch and I'll connect on irc to discuss if I won't be able to compile it myself.

**Comment by antenore** [comment]
@akallabeth the patch works fine (tested by @AngelNone ), thanks

**Comment by giox069** [comment]
@AngelNone please change the title with something less generic, like "Remote files are listed with huge wrong size under 32bit client platforms"
@akallabeth we had another user reporting the problem in Remmina. I also tested your branch 'shift_warn_fix' and it fixes the problem, as reported by @antenore.
