### ISSUE TITLE
/shell and /app-cmd command not taking additional argument

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#3944]
/shell and /app-cmd not taking additional argument and whole command fails and xfreerdp help is shown.

This is FreeRDP version 2.0.0-dev (git 9fd3974)

xfreerdp /cert-ignore  -toggle-fullscreen /title:xx  /bpp:32 /f    +clipboard /network:lan   /kbd:0x00000409  "/shell:test.exe 1 2"    /d:xx  /u:"xx" /p:xxxx  /v:172.17.2.10:3389

xfreerdp /cert-ignore  -toggle-fullscreen /title:xx  /bpp:32 /f    +clipboard /network:lan   /kbd:0x00000409   "/app:||test"  /app-cmd:'1  2  3'   /d:xx  /u:"xx" /p:xxxx  /v:172.17.2.10:3389

**Comment by loumt** [comment]
I have this issue.
Not use RemoteApp.(RemoteApp is running normal.)
Just a normal application.
Such as Notepad.
#Command: 
  xfreerdp /v:xxx /p:xxx /u:xxx /port:xxx /d:xxxx /app:c:\\windows\\system32\\notepad.exe /app-cmd:c:\\1.txt

Open file in 2008 but not in 2012R2
