### ISSUE TITLE
Latency-based booting of logged-in user

### ISSUE THREAD

**Issue by Riebart** [FreeRDP/FreeRDP#3960]
I have been using freerdp to perform auth-only connections to a Windows Server 2016 base, to test whether or not the password for a specific user has been changed.

The issue I have is that when the connection is initiated over a 'long' (>100ms or so) link, the freerdp process successfully authenticates, without booting any existing RDP session for the logged in user. *However* when the freerdp connection occurs over a 'short' link (<5ms), there are additional Security events logged in the Windows server that causes it to punt the logged in RDP session.

The freerdp command in use is: `xfreerdp /v:34.205.9.108 '/p:@G;d9tuqw?gB2nR*p5&nRamote.' /u:Administrator +auth-only /cert-ignore` (That's a sample IP and password, attempting to use them won't get you anywhere. ;))

I used tc to test the link latency, and using queueing discipliens on the interface of 100ms was sufficient to get it to 'work' (not boot the existing logged in session).

The tc command I am using is: `tc qdisc add dev eth0 root netem delay 180ms`

The most confusing part of this behaviour, though, is that it isn't a guarantee, it only increases the likelihood that the freerdp command won't punt the workstation. It seems to happen at a rate of about 1% with 180ms delay.

I tried using all of the `/network` options (without the added latency) to see if it was an auto-detected connection experience thing, but those didn't change the behaviour (all options for `/network` resulted in the logged in RDP session getting booted).

Any and all help here would be appreciated.

**Comment by Riebart** [comment]
*Bump* Has anyone got any input on this?

**Comment by bmiklautz** [comment]
@Riebart the 'long' and the 'short' link test were made against the same server/host?

**Comment by bmiklautz** [comment]
@Riebart in case of auth-only xfreerdp does a regular connect but closes the connection right after the authentication was done. No real difference to a "regular" session is made there. I'd guess the behavior you observe has todo with different timings on the server side. I'm fairly sure the /network options don't help on this because they shouldn't matter in the beginning.

**Comment by Riebart** [comment]
I apologize for my delay in replying, thanks for picking this up.

So this was reproducible very consistently using `tc` to add networking delay on the client side (not the server side). The server in all cases was the same Windows Server 2016 EC2 instance, and the client was a Linux EC2 instance in the same subnet (availability zone).

Typical (unmodified) RTT was on the order of 0.1ms, and when attempts to perform an auth-only connection with that RTT were done, they booted the logged in RDP session for that user. When the RTT was raised on the client side with `tc` to > 100ms, the disconnects were infrequent, and beyond 150ms, stopped almost entirely.

@bmiklautz Is your theory that it's the Windows server-side doing changing the behaviour? There was definitely a different set of behaviours in the Windows Event Logs, and the 'short' and 'long' links produced fundamentally different streams of events past a certain point.

**Comment by lookat23** [comment]
I also encountered the same problem. RDP session still exists after /auth-only test.
![u6 _ pyxg a9 e0 l ul r](https://user-images.githubusercontent.com/7019178/38710865-ee4459ec-3ef4-11e8-850d-ca2bbd4cb1d1.png)

**Comment by akallabeth** [comment]
@Riebart Yes, as @bmiklautz said, the `auth-only` option initiates a normal RDP session that is immediately disconnected.
How the server reacts (creating a new session or not) is up to the implementation.
Closing this as we can do nothing about it.
