### ISSUE TITLE
Minimized window restores to one monitor, not two

### ISSUE THREAD

**Issue by OriginalFlavor** [FreeRDP/FreeRDP#3961]
When I restore a minimized window, the restored window only fills one monitor, not both.

I am using ubuntu 17.04 with two monitors.
An rdp session is launched from the terminal 
xfreerdp /multimon /u:username /v:remote.server.com
A fullscreen window spanning both monitors opens.
I minimize the session using ctrl+alt+enter
When I click on the icon in the task bar to restore the session, the double-wide window is scaled into only one monitor.
How can I minimize and restore to two monitors?

**Comment by hardening** [comment]
What does it give if you add /f on the command line ?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
