### ISSUE TITLE
xfreerdp hangs indefinitely with invalid load balance info and NLA enabled

### ISSUE THREAD

**Issue by bjcollins** [FreeRDP/FreeRDP#3968]
I noticed when testing against a Windows 2012R2 Connection Broker using NLA that if I pass in an invalid /load-balance-info string that xfreerdp just hangs when it should actually be disconnecting and closing. Connecting without NLA enabled will work.

My command-line argument is:
xfreerdp /v:x.x.x.x /u:myusername /p:mypassword /d:mydomain /load-balance-info:tsv://mytsvstring

My output shows that I get ERRINFO_CB_CONNECTION_ERROR_INVALID_SETTINGS from the server and then get a DisconnectProviderUltimatum at which point the application just hangs. 

Upon some debugging I think the problem is in "transport_check_fds" function inside of the "libfreerdp/core/transport.c". The disconnect is requested while freerdp is still waiting to get to the CONNECTION_STATE_ACTIVE state and is looping calling "rdp_check_fds" which calls "transport_check_fds". I believe that "transport_check_fds" should give a non-zero return value when freerdp_shall_disconnect() returns True to signal that something went wrong to its caller.  I am not sure making a change there to address this issue will cause other problems, but it does address the problem noted in this issue.

**Comment by bjcollins** [comment]
After some more testing, I see that my "fix" does indeed cause other issues. I believe I am creating a race condition since transport_check_fds giving a bad return value causes freerdp to return that the connection had failed even when the user logs off normally. Maybe the tight loop waiting for CONNECTION_STATE_ACTIVE in rdp_client_connect() should just check freerdp_shall_disconnect() itself instead to break from the loop?

**Comment by hardening** [comment]
I really think we have a problem with the treatment of DisconnectProviderUltimatum, I remember someone complaining about infinite loop on reactivation...

**Comment by akallabeth** [comment]
@bjcollins We've merged a lot of gateway and redirection related fixes. does this still happen with current nightlies?

**Comment by akallabeth** [comment]
should be fixed since feca6d9750be21d89f3b071a8eab25eaaae7f935
