### ISSUE TITLE
Would like a toolbar when running fullscreen

### ISSUE THREAD

**Issue by figueroadavid** [FreeRDP/FreeRDP#3970]
I would like to request an option to get a toolbar when running fullscreen.  The primary goal is to be able to perform connection options like a disconnect, and to be able to minimize/convert to a window (or be able to go fullscreen with) the connected session..  
Other options might be to connect external devices on the fly.

Thank you, 

David F.

**Comment by hardening** [comment]
Unfortunately having a toolbar implies using a graphical toolkit to handle it, and the FreeRDP project doesn't will to depend on a toolkit for now.

**Comment by figueroadavid** [comment]
Fair enough.. thank you,


David F.

**Comment by ilammy** [comment]
@figueroadavid, but I guess you could use Remmina to get a toolbar. It uses FreeRDP for RDP connections, but their version is not in sync with the latest branch of FreeRDP.

**Comment by figueroadavid** [comment]
Thank you :-) I was looking into that.. turns out my Ubuntu 16.10 has Remmina 1.10, so I'm working on upgrading to Remmina 1.20 (or whatever is current) to get that toolbar.. 

There are *tons* of RDP managers to choose from for Windows, and they virtually all have the toolbars if they support full screen mode, and they all have an embedded window interface, which I've also struggled with..

David F.
