### ISSUE TITLE
I can't  execute  remote app on Android FreeRDP ..... HELP ME 

### ISSUE THREAD

**Issue by umhahahahapu** [FreeRDP/FreeRDP#3971]
Ubuntu16.04 can excute remote app, and exactly same command to android .
However I can't android freerdp app , as aFreeRDP can't excute remote app ....I met all black screen 
I confirm my command , remote app command '||EX' (EX is registered WindowRemoteApp tool)

What can I do ? 
/v: 192.x.x.x /u:aaa /p:1111 /app:'||EX'

But I can't excute remote app.....please help me..

**Comment by akallabeth** [comment]
sorry, what? The android client does not support remote app, how did you add a command line there?

**Comment by umhahahahapu** [comment]
I filled the line 'Advanced tab and Remote Program.  
   The command is "||EX" &lt;-- app ailias..
 
   Can't connect from Android phone "aFreeRDP" my Remote program on my PC ?
 
    
-----Original Message-----

**Comment by akallabeth** [comment]
The setting is for starting an application on connection not for remote app.
