### ISSUE TITLE
Cannot connect with usernames containing underscores.

### ISSUE THREAD

**Issue by Bardaravine** [FreeRDP/FreeRDP#3972]
I am unable to connect via RDP when a username contains an underscore.
I created two new accounts, testuser and test_user. 
Connecting with testuser works as expected.
Connecting with test_user gives the following error messages.
`SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied
credssp_recv() error: -1
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
Error: protocol security negotiation or connection failure`
I am using  version 1.1.0-beta1 from the Ubuntu 16.04 repository.

**Comment by hardening** [comment]
what about with latest master ? (https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds may help)

**Comment by Bardaravine** [comment]
This issue is fixed in the latest master. 
It is also fixed in the most recent release of freerdp2 at https://ci.freerdp.com/job/freerdp2-binaries/. 

Thanks for your help.
