### ISSUE TITLE
Feature Request - Headless operation

### ISSUE THREAD

**Issue by Matterdor** [FreeRDP/FreeRDP#3973]
We have a bank of machines that we use for testing. Windows Remote Desktop requires a RDP connection to be active otherwise it won't create handles for controls. It would be great if FreeRDP had a mode of operation with no desktop, keyboard or mouse connected. Where it would just eat all of the messages from the RDP session. That would keep the RDP sessions functioning but not require any resources on the controller side and would let us start as many concurrent sessions as we needed.

**Comment by hardening** [comment]
The sample client does that kind of thing, at least it's a good template if you wanna write such a program.

**Comment by Matterdor** [comment]
I am still getting into the code. The idea is to either create a single application that has multiple tabs with threads for each of the connections and only the active one paints or alternatively open a background process for each tab by calling the FreeRDP sample client with some command line parameters. Obviously the second on is much easier which is why I asked the question.

**Comment by Arinerron** [comment]
@Matterdor Did you ever figure this out?

**Comment by gerardo-junior** [comment]
+1 for rdp2tcp use

**Comment by albert-a** [comment]
Headless operation would be useful
