### ISSUE TITLE
FreeRDP client vulnerability

### ISSUE THREAD

**Issue by regiwils** [FreeRDP/FreeRDP#3975]
The Cisco Talos team found a security vulnerability impacting FreeRDP customers. As this is a sensitive security issue, please provide email contact and PGP to send the reports.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. http://www.cisco.com/web/about/security/psirt/vendor_vulnerability_policy.html

Please CC vulndev at cisco.com on all correspondence related to this issue.

**Comment by bmiklautz** [comment]
@regiwils thanks for the report so far. I'll handle the communication for the FreeRDP Team.
Please use the following E-Mail for contact:
bernhard dot miklautz at shacknet dot at
The corresponding public GPG key is: '3B57 CBBD D2B7 9ED8 50E4  9CB8 6FA8 7A15 232F A178' and can be found on the key server or download from:
https://pub.freerdp.com/people/bmiklautz/232FA178.asc

**Comment by bmiklautz** [comment]
Fixed with PR #4055

**Comment by bmiklautz** [comment]
@regiwils and thank you!
