### ISSUE TITLE
I want to see android android_freerdp.c file's log..  

### ISSUE THREAD

**Issue by umhahahahapu** [FreeRDP/FreeRDP#3981]
I read the Android.doc and complied after import android studio.

but I didn't see android_freerdp.c log..

LOGD is already defined and I typed LOGD in function jni_freerdp_parse_arguments API..

And I re-complied success and restart..
But I didn't see.... 

What is the problem ??..
Anyone suggest to me....

**Comment by akallabeth** [comment]
Plase use the mailing list or IRC for support questions.
