### ISSUE TITLE
Compilation for REL 6 or an rpm installer for latest release

### ISSUE THREAD

**Issue by richardmat** [FreeRDP/FreeRDP#3984]
The documentation for compiling freerdp on REL/Centos 6 on this site are incomplete. Is there a document that fully describes the process?

Also, is there a pre-built rpm of the latest release available for REL/Centos 6?

Thanks

**Comment by bmiklautz** [comment]
@richardmat there isn't any pre-build RPM atm for RedHat/Centos as we currently don't have any build machine prepared for that. But have a look to packaging/rpm/freerdp-nightly.spec that's the one we use for our nightly packages and it works on Fedora. Best case you can directly use it without modification to build a package.

**Comment by tukusejssirs** [comment]
This is still an issue. Although I have not tested it on EL6 nor EL7, on CentOS 8 I had to install a few more packages. And also I have installed some additional, non-required packages, see below. I have created a guide to install Remmina from source, which requires FreeRDP to be build from source too, and it is [here](https://gitlab.com/Remmina/Remmina/-/wikis/Compilation/Compilation-guide-for-CentOS).

```bash
# Repositories
# epel: required for `openjpeg2-devel`, `openssl-devel`
# rpmfusion-free-updates: required for `ffmpeg-devel`
# PowerTools repo is needed on CentOS 8+
sudo yum -y install epel-release \
  https://download1.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %centos).noarch.rpm

if [ $(rpm -E %centos) = 8 ]; then
  sudo dnf config-manager --set-enabled PowerTools
fi

# Official guide (src: https://github.com/FreeRDP/FreeRDP/wiki/Compilation [rhel based])
gcc cmake ninja-build openssl-devel libX11-devel libXext-devel libXinerama-devel libXcursor-devel \
  libXi-devel libXdamage-devel libXv-devel libxkbfile-devel alsa-lib-devel cups-devel ffmpeg-devel \
  glib2-devel libusb-devel
# I had to install these at least on CentOS 8, but they are probably required on CentOS 7 too;
#   otherwise the build failed
make gcc-c++ pulseaudio-libs-devel libXrandr-devel
# Recommended: these are required to build man pages
libxslt libxslt-devel docbook-style-xsl
# Recommended: for multimedia redirection, audio and video playback
gstreamer1-devel gstreamer1-plugins-base-devel
# Recommended: for some X11 addon
xorg-x11-server-utils
# Recommended: at build-time, FreeRDP states that this is 'required by virtual:world'
cairo-devel
```

**Comment by akallabeth** [comment]
there is the nightly rpm in repo https://github.com/FreeRDP/FreeRDP/tree/master/packaging/rpm and https://github.com/FreeRDP/FreeRDP/wiki/Compilation#linux-specifics
