### ISSUE TITLE
dropdown menus appear black when launching rdp file from terminal but not from file manager.

### ISSUE THREAD

**Issue by mattonm** [FreeRDP/FreeRDP#3990]
Just wondering if anyone can shed some light on this issue...
If I double click on an rdp file in a file manager or on the desktop, a terminal window appears and I'm prompted for credentials, which I enter and the application launches and everything is normal (no black dropdown menus!).

If I open a terminal window, then run xfreerdp myapp.rdp, the application launches after I supply my credentials, but the dropdown menus now appear as black boxes.
Where is the difference?

**Comment by bmiklautz** [comment]
@mattonm what drop downs are exactly black? What FreeRDP version you are using. Can you give an example of the .rdp file?

**Comment by mattonm** [comment]
Thanks for responding...
Any windows application that has been launched using an rdp file from a terminal window, will display dropdown menus in black.  Using the same rdp file by clicking on it from dolphin or from within a desktop folder will present the windows application and menus as normal (no black dropdown menus).  I've tried turning off compositing, changing color depth, and anything else graphics related but results are consistent. When I click on File to drop down the File menu, the menu is visible for a split second, then becomes black.  
This isn't a big issue, since I have rdp files associated to freerdp, which allows me to click on an rdp file sitting on my desktop or in a directory.  I never see black menus when launching rdp files in that manner.  Also, rdp files launched from a web browser via RDweb function correctly.

**Comment by bmiklautz** [comment]
@mattonm ok so this happens with remote apps. Do you have the same problem if you do a "regular" connection (no remote app)? - If you can I'd try a more recent version as it might contains fixes for remote apps.

**Comment by mattonm** [comment]
Sorry, I thought 1.2.0 was the latest version.  I'll upgrade it to the latest.  
There's no problems whatsoever with full desktop sessions except for maybe short idle timeouts sometimes).  Freerdp with the gateway feature has been a blessing for me since I'm a lone linux user in a totally Microsoft Windows environment.  
I'll try a different distro to see if I get the same results when launching an rdp file from a terminal window.
Thanks!

**Comment by mattonm** [comment]
Yes, version 2.0.0 does resolve this issue.  I did have version 2.0.0 installed but it installed to the opt directory and version 1.2 was still in /usr/bin.  I'll try to get that sorted.
Cheers,

**Comment by bmiklautz** [comment]
@mattonm the issue can be closed then?

**Comment by mattonm** [comment]
Yes, thanks for your time and sorry about the 1.2.0  / 2.0.0 mixup on my end.
