### ISSUE TITLE
Unable to generate a XCode project

### ISSUE THREAD

**Issue by KiranJasvanee** [FreeRDP/FreeRDP#3994]
Unable to generate a XCode project using following command -

cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode

![screen shot 2017-06-06 at 10 17 33](https://cloud.githubusercontent.com/assets/6015870/26814222/80a4d1ac-4aa1-11e7-916e-79dddea35a35.png)

**Comment by akallabeth** [comment]
Please read the howto in ```docs/README.ios```

**Comment by KiranJasvanee** [comment]
I already went through it, infect the procedure which I already followed mentioned on `docs/README.ios`, You should try it in Mac Sierra first before closing this.
You can check in screenshot that I able to set INCLUDE folder of OpenSSL, but I'm unable to set OPENSSL_ROOT_DIR and OPENSSL_LIBRARY.

**Comment by akallabeth** [comment]
@KiranJasvanee Did you build OpenSSL and is it in the correct path? Looks like it is not from your text snippet.

**Comment by KiranJasvanee** [comment]
Ya, You can check I've provided correct path for OPENSSL INCLUDE, It's found. for OPENSSL_ROOT_DIR and OPENSSL_LIBRARY, I've set perfect path for 100 times but still it generates same error. 

`CMakeCache.txt`
```
//Path to a file.
OPENSSL_INCLUDE_DIR:PATH=/usr/local/opt/openssl/1.0.2l/include

//No help, variable specified on the command line.
OPENSSL_LIBRARIES: PATH =/usr/local/opt/openssl

//No help, variable specified on the command line.
OPENSSL_ROOT_DIR:PATH=/usr/local/opt/openssl/1.0.2l/lib
```

It's mentioned in comment above this variables `No help, variable specified on the command line.` So I've tried to set those manually via command line. Still there is no progress.

**Comment by akallabeth** [comment]
WTF are you doing? You build for iOS and link against the OSX openssl? Please read and UNDERTAND the readme I pointed you to.

**Comment by KiranJasvanee** [comment]
Please mind your language, I've tried your way too, which I followed initially. I've tried to set path of below directory generated by following commands mentioned in REDMI. Still it shows same error. 

It's just I showed you where I set PATH. At least you should react politely without knowing the context. 

![screen shot 2017-06-06 at 14 07 24](https://cloud.githubusercontent.com/assets/6015870/26820877/1080e6b0-4ac2-11e7-9109-ec0860e60091.png)
![screen shot 2017-06-06 at 14 10 21](https://cloud.githubusercontent.com/assets/6015870/26820881/137f8d30-4ac2-11e7-86be-9fd499a1ffe2.png)

**Comment by KiranJasvanee** [comment]
have you guys even tried once in MAC sierra?

**Comment by akallabeth** [comment]
@KiranJasvanee Sorry about that, I was just puzzled by the fact you try to link against system SSL (which is the wrong/missing architecture for iOS builds). In fact our build machines are Mac OS 10.12, so yes. Maybe you should try again with a clean checkout (no CMake or other files, clean git) and just run the commands from the readme. This is working quite fine and does only depend on XCode not the Mac OS version at all.

**Comment by KiranJasvanee** [comment]
I'm getting blank `include` and `lib` folder after `./scripts/OpenSSL-DownloadAndBuild.command` command in root folder. 

![screen shot 2017-06-06 at 15 12 26](https://cloud.githubusercontent.com/assets/6015870/26823289/b5128366-4aca-11e7-9f76-808fb906cb3b.png)

**Comment by akallabeth** [comment]
@KiranJasvanee Then you have the culprit. See the output of the build command (that is written to a log file ```external/openssl/openssltmp/openssl-1.0.2h/BuildLog.darwin-$ARCH.txt```) and fix whatever is going wrong there.

**Comment by KiranJasvanee** [comment]
Hi @akallabeth I solved this issue. Before executing FreeRDP OpenSSL script - `./scripts/OpenSSL-DownloadAndBuild.command`, I had to reset my XCode command line tools to be initialized.
Reset XCode command-line tool using -
`$ sudo xcode-select --reset`

Then, I executed FreeRDP script and it worked perfect.
```
shasum: openssl-1.0.2h.tar.gz: 
Downloading OpenSSL Version 1.0.2h ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5150k  100 5150k    0     0   425k      0  0:00:12  0:00:12 --:--:--  531k
Unpacking OpenSSL ...

Building openssl-1.0.2h for iPhoneSimulator 10.2 i386 (min SDK set: 9.3)
 Please wait ... Done. Build log saved in BuildLog.darwin-i386.txt
Building openssl-1.0.2h for iPhoneSimulator 10.2 x86_64 (min SDK set: 9.3)
 Please wait ... Done. Build log saved in BuildLog.darwin-x86_64.txt
Building openssl-1.0.2h for iPhoneOS 10.2 armv7 (min SDK set: 9.3)
 Please wait ... Done. Build log saved in BuildLog.darwin-armv7.txt
Building openssl-1.0.2h for iPhoneOS 10.2 armv7s (min SDK set: 9.3)
 Please wait ... Done. Build log saved in BuildLog.darwin-armv7s.txt
Building openssl-1.0.2h for iPhoneOS 10.2 arm64 (min SDK set: 9.3)
 Please wait ... Done. Build log saved in BuildLog.darwin-arm64.txt
Copying header files ...

Combining to unversal binary
Finished. Please verify the contens of the openssl folder in "external" 
```
After that I tried below CMake command to generate XCode project, and it worked just fine.

`cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode`

**Thanks for spotting me culprit area**

**Comment by ysnnzlcn** [comment]
@KiranJasvanee After reseting xcode comand line, build log complained about missing files. So i reinstalled development tools with `xcode-select --install` then finally it worked.
