### ISSUE TITLE
Drive redirection shows files with pentabyte size (folder shows exabyte size)

### ISSUE THREAD

**Issue by T3N4K4** [FreeRDP/FreeRDP#3995]
@akallabeth 
I guess it is almost the same problem as with #3922, but this time it is dependent on USB 3.0. 
With USB 2.0 all is fine. It is still a sym-linked folder and the same command line to a windows terminal server 2012r2.

In my opinion there is some calculation wrong, a 8GB USB Stick gets the size of 7,85EB on the windows terminal server. 4GB are then 3,79EB.

**Comment by akallabeth** [comment]
@T3N4K4 Just had a look. ```FileFullDirectoryInformation``` seems to invert the high and low words of the file size, could you change that and try if that fixes the issue for you?

**Comment by T3N4K4** [comment]
@akallabeth that was it. It works for me with USB 3.0 and USB 2.0.
