### ISSUE TITLE
Redirect usb Elatec Legic RFID reader

### ISSUE THREAD

**Issue by shining01** [FreeRDP/FreeRDP#4002]
Hello,

i would like to redirect the Elatec Legic RFID reader on a raspberry pi 3. I have installed freerdp from debian repository (apt-get install freerdp)

i get the following USB List with lsusb:

`root@raspberrypi:/home/pi/FreeRDP# lsusb
Bus 001 Device 007: ID 0eef:0001 D-WAV Scientific Co., Ltd eGalax TouchScreen
Bus 001 Device 006: ID 04d9:1603 Holtek Semiconductor, Inc. Keyboard
Bus 001 Device 005: ID 0461:4e66 Primax Electronics, Ltd
Bus 001 Device 004: ID 09d8:0320
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`

I would like to redirect the device Bus 001 Device 004: ID 09d8:0320 with the following command:

`xfreerdp /u:xxx /p:xxx /d:xxx /v:terminalserver /f /usb:id,dev:09d8:0320`

but i get still the following error:

`loading channel drdynvc
connected to terminalserver2:3389
Unable to find a match for unix timezone: Etc/UTC
Loading Dynamic Virtual Channel urbdrc
LoadLibraryA: /usr/lib/arm-linux-gnueabihf/freerdp/urbdrc-client.so: cannot open shared object file: No such file or directory
`

**Comment by akallabeth** [comment]
This is an issue tracker. please ask such questions on the mailing list or IRC.

**Comment by nieshaokang** [comment]
where is mailing list ?

**Comment by bmiklautz** [comment]
@nieshaokang ... https://github.com/FreeRDP/FreeRDP/blob/master/README
