### ISSUE TITLE
/printer is making xfreerdp crash

### ISSUE THREAD

**Issue by jfha73** [FreeRDP/FreeRDP#4004]
Hey guys,

For some reason every time I add /printer to the xfreerdp command, it crashes creating a core dump.

I'm using Ubuntu 16.04 and I have sent the crash report to Ubuntu, but it's something you might want to take a look at.

Thanks.

**Comment by hardening** [comment]
Can you try the nightlies (https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds) as the FreeRDP shipped in Ubuntu 16.04 is slightly old.

**Comment by jfha73** [comment]
I just did, tried 2.0.0+0~20170615014828.396~1.gbp117f57 and got a
segmentation fault error message when I added /printer.




=============
Jorge Hernandez

**Comment by bmiklautz** [comment]
@jfha73 tried the latest version here as well and couldn't observe the described behavior. Any further output if before you get the segfault?

**Comment by jfha73** [comment]
Never mind that, I noticed I was still using the old version.


Jorge F. Hernandez

**Comment by akallabeth** [comment]
@jfha73 So this is fixed/not an issue?

**Comment by jfha73** [comment]
Yes it is fixed. Thanks.


Jorge F. Hernandez
