### ISSUE TITLE
Serial port redirection to a linux server

### ISSUE THREAD

**Issue by StephanKrieger** [FreeRDP/FreeRDP#4005]
Hello,

i have maybe a very simple question, but did not find any answer right now.
I have to redirect a serial port to a linux machine.. so like to ttyS0.

Till now i just had to redirect to a windows machine like this:
/serial:COM1,/dev/ttyHS1,Serial,permissive

Can anyone help me to find the right syntax?
I imagine: /serial:/dev/ttyS0,/dev/ttyhS1,Serial,permissive

But that seems not be the right one

Best regards
Stephan

**Comment by glengillman** [comment]
Hi All,


  1.  I was wondering if someone could help explain the difference between the parameters:  bitmap-cache and offscreen-cache
  2.  Do these parameters result in saving files on a hard disk drive somewhere ?
  3.  What about the parameters for /jpeg --- does that result in saving images to the hard disk drive ?

Thank you.

Glen

**Comment by StephanKrieger** [comment]
Hi Glen,

just wondering... how does that fit about my question to the "serial port redirection"?!

Best Regards
Stephan

**Comment by glengillman** [comment]
Hi Stephan,

I apologize.  I was in a hurry and obviously posted this in the wrong location.  I hope everyone is able to provide the assistance you need.

Thanks.
Glen

**Comment by T3N4K4** [comment]
@StephanKrieger I don't know exactly if this helps. But the syntax for the command line seems to be still the same:
Serial Port Redirection: /serial:<name>,<device>,[SerCx2|SerCx|Serial],[permissive]
Serial Port Redirection: /serial:COM1,/dev/ttyS0

Maybe for your example something like this could work (I don't know if the second /serial overwrites the first one):
/serial:COM1,/dev/ttyHS1,Serial,permissive /serial:COM2,/dev/ttyS0,Serial,permissive

**Comment by StephanKrieger** [comment]
@T3N4K4 Thx for your reply, i will test it once again as you say.

Let me ask a further question:
So you think that COM1 will be redirected to /dev/ttyS0 (or other tty) on Linux?
COM1 sounds for me like the term for windows.

**Comment by T3N4K4** [comment]
@StephanKrieger As I understand it COM1 is just the name of the device how it will appear / show up on the (receiving) server. So you could just name it how you like (cat or dog for example instead of COM1).

**Comment by akallabeth** [comment]
Seems resolved, reopen if not.
