### ISSUE TITLE
parameters:   bitmap-cache/offscreen-cache

### ISSUE THREAD

**Issue by glengillman** [FreeRDP/FreeRDP#4006]
Hi All,

  1.  I was wondering if someone could help explain the difference between the parameters:  bitmap-cache and offscreen-cache
  2.  Do these parameters result in saving files on a hard disk drive somewhere ?
  3.  What about the parameters for /jpeg --- does that result in saving images to the hard disk drive ?

Thank you.

Glen

**Comment by hardening** [comment]
Well obviously this is an issue tracker and not an assistance forum. For such questions be patient and go on IRC, or post the mailing list.
