### ISSUE TITLE
Building FreeRDP - Failing

### ISSUE THREAD

**Issue by glengillman** [FreeRDP/FreeRDP#4009]
Hi All,

I have been trying to exhaust all efforts before posting here.  Any help is appreciated.  I've searched for similar issues and tried the recommendations, unfortunately none of them have resolved the issue I'm seeing.

Steps:
- downloaded OpenSSL version 1.1 - have successfully configured it with Visual Studio 2010 / Windows SDK and it built, and all the tests passing, libraries and binaries generated
- downloaded latest FreeRDP code from github

Folder structure:
![2017-06-14_12h55_18](https://user-images.githubusercontent.com/29120512/27147053-0e18a45e-5101-11e7-8379-b202286f417e.png)
![2017-06-14_12h55_55](https://user-images.githubusercontent.com/29120512/27147068-18ea1bc4-5101-11e7-8476-867de507f280.png)

CMake - configuration and error:
![2017-06-14_12h54_55](https://user-images.githubusercontent.com/29120512/27147139-4d0be680-5101-11e7-9005-f55c82102bf3.png)

Any assistance will be helpful.  If I use an older version of OpenSSL it is working fine.   But I'm trying to use version 1.1 because it is more secure and I want to leverage the latest updates/changes.   I must be missing something very easy.  As you can see I added those properties for OPENSSL manually to help it find the OpenSSL files necessary

Thank you
Glen

**Comment by akallabeth** [comment]
@glengillman Well, it looks like it can not find the OpenSSL libraries. Where are the ```dll``` files of your custom build? I remember something that they are in ```<OpenSSL_ROOT>/bin``` on windows, maybe that is the reason

**Comment by akallabeth** [comment]
No feedback, closing.
