### ISSUE TITLE
Kerberos support status

### ISSUE THREAD

**Issue by adocampo** [FreeRDP/FreeRDP#4010]
I compiled the sources with -DWITH_KRB5=ON in the hope freerdp could connect to a Windows (or even better, xrdp) server using the kerberos ticket.
It compiled, but I see no way to connect with kerberos, it still ask for a password, so, am I missing something or the support is still incomplete?

**Comment by hardening** [comment]
-DWITH_KRB5=ON just allows to have a nice message when you're connecting using nla and t the reason why you can't login is because you must change your password.

There's a Kerberos login branch here:
https://github.com/FreeRDP/FreeRDP/pull/3954

**Comment by adocampo** [comment]
Thanks.

I don't understand when you say "I must change my password", The linux box is inside a Windows domain and I can't change the user password (and I really don't understand why I would need to do it).

This branch would allow to SSO? in other words, to connect to another machine without the need to enter any credentials, using the kerberos ticket I already have?

**Comment by akallabeth** [comment]
#3791 did add kerberos support.
