### ISSUE TITLE
invalid UnicodeFlag value: 0x0067006F

### ISSUE THREAD

**Issue by pedjaman** [FreeRDP/FreeRDP#4015]
Hello,

rdpdr is emitting this and stop.
Any idea what is the cause?

[15:34:56:237] [20100:20136] [ERROR][rdpdr.server] - invalid UnicodeFlag value: 0x0067006F
[15:34:56:237] [20100:20136] [ERROR][rdpdr.server] - rdpdr_server_receive_client_name_request failed with error 13!
[15:34:56:237] [20100:20136] [ERROR][rdpdr.server] - rdpdr_server_receive_pdu failed with error 13!

Thanks :)

**Comment by pedjaman** [comment]
I propose removing following code as it works well without (client name is well detected) and will fail with such code in place:

```
	if (UnicodeFlag > 1) /* must be 0x00000000 or 0x00000001 */
	{
		WLog_ERR(TAG, "invalid UnicodeFlag value: 0x%08"PRIX32"", UnicodeFlag);
		return ERROR_INVALID_DATA;
	}

```

**Comment by bmiklautz** [comment]
@pedjaman what parameters are you connecting with and what version of FreeRDP?

**Comment by pedjaman** [comment]
Trunk version.
What kind of aprameters are you interested in?


On Wed, Jun 28, 2017 at 3:10 PM, Bernhard Miklautz <notifications@github.com

**Comment by bmiklautz** [comment]
@pedjaman command line parameters and the environment you are running on.

**Comment by pedjaman** [comment]
It was server library used in my application. Connection was from standard
Windows remote desktop application to Linux server application. Rdpdr was
exiting his own loop because of that peace of code as value is not 0 or 1
as expected. Nevertheless, after removing this peace of code, computer name
was properly detected without problems. So I think problem is in
expectations to have this value as 0 or 1. It should be 0 or else.
