### ISSUE TITLE
How to I implement android rail? without X11, Xlib...... 

### ISSUE THREAD

**Issue by umhahahahapu** [FreeRDP/FreeRDP#4016]
I wonder about how can I implements rail channel in Android without X11, Xlib..

 Is it possible???

I analyze code but between X11 and android are different , X11 Window ... 
And Android have no Xlib. X11.. 

please guide to me..

**Comment by ilammy** [comment]
> I wonder about how can I implements rail channel in Android without X11,
> Xlib..
>
> Is it possible???
>
Do you really need RAIL on Android? It's not possible to get a remote app
running over other activities. You may find that single-app mode does what
you need to do. You need to launch your app as the remote session shell
(instead of explorer.exe), then the app will be the only thing in the
remote session, no task bar, start menu, desktop, etc.

**Comment by umhahahahapu** [comment]
Thank you, and I need to RAIL channel on Android so I planed to porting RAIL channel on Android. But is it impossible thing???  I want to direct show remote program on Android. 
Is it impossible porting RAIL channel on Android? 

I think 'shell' is working directory but I test now it is not work.
What does mean 'instead of explorer.exe??

**Comment by ilammy** [comment]
> Thank you, and I need to RAIL channel on Android so I planed to porting
> RAIL channel on Android. But is it impossible thing??? I want to direct
> show remote program on Android.
> Is it impossible porting RAIL channel on Android?
>
It is definitely possible.

I assumed you wished to add RAIL support to some fullscreen RDP client. If
you're still going to show the whole remote session, or if the application
window will be the only thing visible to the user, then you do not really
need RAIL. Just set the desktop resolution to whatever the Android device
has (or whatever the window size you need) and maximize the application.

However, if you need to do something fancy then you might need it. As I
recall, it's not possible without RAIL to launch the application in already
maximized state, or to switch it to maximized state without having the user
to manually tap the maximize button.

But you do not really need to have Xlib or deal with X11 on Android to
implement RAIL. The Xlib code in XFreeRDP mostly deals with presentation of
remote application windows in local windows. On don't really need that on
Android. You can still use the same drawing code and display the remote
session exactly as it is displayed now, and use RAIL callbacks and commands
only to control the remote application windows and get notifications about
various events. Just ignore all X window management in XFreeRDP code when
using it as a reference.

I think 'shell' is working directory but I test now it is not work.
> What does mean 'instead of explorer.exe??
>
I was referring to the `/shell` command line argument of XFreeRDP. It is
used to set an alternate shell to use on the remote server (the default one
is the usual explorer.exe). If you set that to some other application then
the remote session should contain only it, without any other Windows stuff
you see.

**Comment by umhahahahapu** [comment]
Thank you for your advices. 
I try to RAIL Channels on Android . 
Now, display clipboard way on Android and I try to as it way and add to RAIL here. 
Thank you!!!

**Comment by akallabeth** [comment]
Question, not an issue.
