### ISSUE TITLE
why ifreerdp android app has redirection settings, but iOS app does not?

### ISSUE THREAD

**Issue by aysenkilic** [FreeRDP/FreeRDP#4017]
hi, i'm working on sound redirection on my iOS app by using iFreeRDP but i can not. I make some research about iFreeRDP store applications. i saw the redirection settings on Android app, but not on iOS app. This means it is not possible to redirect sound on iOS?

**Comment by akallabeth** [comment]
Please ask questions on the mailing list or IRC.
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
