### ISSUE TITLE
gst_x_overlay_set_window_handle not yet supported on RHEL 6

### ISSUE THREAD

**Issue by scroogie** [FreeRDP/FreeRDP#4019]
In /channels/tsmf/client/gstreamer/tsmf_X11.c line 112 gst_x_overlay_set_window_handle() is called. However, this function is only available since gstreamer 0.10.31. RHEL doesn't provide this. 
Could you maybe consider to call 

gst_x_overlay_set_xwindow_id(hdl->overlay, hdl->subwin);

instead? This makes it compile on RHEL6 for me.

Cheers
André

**Comment by bmiklautz** [comment]
@scroogie no gstreamer 1.0 available either?

**Comment by scroogie** [comment]
Nope, not on RHEL 6, there 0.10.29 is the latest. RHEL 7.x has gstreamer1-* packages, though.

**Comment by bmiklautz** [comment]
@scroogie maybe you can create a pull request that uses the working code path depending on the installed gstreamer version. If < 0.10.31 use your suggestion the current version otherwise.

**Comment by bmiklautz** [comment]
closed with PR #4021
