### ISSUE TITLE
Cannot run specific remoteApp - XCreateWindow 0x0

### ISSUE THREAD

**Issue by dimmyk13** [FreeRDP/FreeRDP#4020]
Hello!

First of all congrats for making this great effort. We are working on an alternative to deliver remote apps to our environment, with the goal to replace windows clients with linux. 
So far the testing is successfull; all apps run smoothly without any major problem. However, one specific app cannot be executed (and this app is the most important!). here are the details:

Tested on : Ubuntu 16.04 & CentOS 7.
Freerdp --v : 2.0.0-dev (git 9904c32). Tried also with stable v1
Command used : xfreerdp /u:username /p:password /app:"||appname" /v:app.server.net

The error i get:

X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  1 (X_CreateWindow)
  Value in failed request:  0x0
  Serial number of failed request:  4110
  Current serial number in output stream:  4121

Note that, initially, the login window of the app opens. After entering credentials, the loading bar appears, and then comes the error. 
Note also, that if this app is already open on the background, and i try to call another app, it will fail with the same errors.

I'm not sure if it related with the X server or the freerdp. Any help would be much appreciated.

Thanks,
Dimitris

**Comment by dimmyk13** [comment]
Hello,

Any comment / ideas on this? Apologies in case the post require more information.

Thanks,
Dimitris

**Comment by hardening** [comment]
@dimmyk13 I guess it happens with a proprietary app. There may be something wrong with our rail implementation, but without more details it's hard to say. Perhaps you could recompile with WITH_DEBUG_RAIL and run with WLOG_LEVEL=TRACE...

**Comment by dimmyk13** [comment]
@hardening Thank you for your reply. Yes it is a proprietary app and i'm also trying to find a solution with them if it's possible.
I tried to compile with:
cmake -DCMAKE_BUILD_TYPE=Debug WITH_DEBUG_RAIL=ON -DWITH_SSE2=ON .

and run with:
xfreerdp /log-level:TRACE /u:user@domain.local /p:password /app:"||appname" /v:apps.domain.net

I attached the output. Thank you in advance for you help!
[log.txt](https://github.com/FreeRDP/FreeRDP/files/1121856/log.txt)

**Comment by hardening** [comment]
@dimmyk13 I guess it's breaking around client/X11/xf_window.c:645, it would be really neat if you could dump the arguments that are passed to XCreateWindow() (mostly the value of *appWindow)

**Comment by dimmyk13** [comment]
@hardening I added a printf just before XCreateWindow to print appWindow values: 

X is: 0
y is: 0
width is: 1
height is: 1

X is: 846
y is: 298
width is: 490
height is: 301

X is: 739
y is: 237
width is: 441
height is: 134

X is: 0
y is: 0
width is: 0
height is: 0

I might try some more debugging to understand the reason, however you might have a better view of the issue :)

Thanks again

**Comment by hardening** [comment]
I guess that a window with 0,0 as dimension doesn't make it for X ;)

**Comment by dimmyk13** [comment]
@hardening Thanks! I will communicate this to the software provider. Cheers

**Comment by hardening** [comment]
I guess you could give a try to modify width/height to (1,1) when they're given to (0,0), that would make the window exist for X and would allow the app to run correctly.

**Comment by dimmyk13** [comment]
@hardening Thats what i did and it works :)

if (appWindow->width == 0 && appWindow->height == 0)
        {
                appWindow->width=1;
                appWindow->height=1;
        }

**Comment by bmiklautz** [comment]
@hardening @dimmyk13 nice finding. Would be nice to have this fixed in master as well. Would someone create a pull request for it?

**Comment by bmiklautz** [comment]
@dimmyk13 should be fixed on the current muster. Would you verify that?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
Reopen if still an issue.
