### ISSUE TITLE
new build warnings of 2017-06-29

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#4026]
I skip the "defined but not used" and "visibility" warnings and the "maybe-uninitialized".
The interesting ones:

`osTWbuild.log:[   38s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/core/update.c:2159:3: warning: implicit declaration of function 'update_free_window_icon_info'; did you mean 'update_free_window_state'? [-Wimplicit-function-declaration]

osTWbuild.log:[   47s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/drive/client/drive_file.c:187:17: warning: assignment discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]

osTWbuild.log:[   48s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/drive/client/drive_main.c:869:13: warning: passing argument 1 of 'drive_free' from incompatible pointer type [-Wincompatible-pointer-types]

`
[osTWbuild.log_20170629.zip](https://github.com/FreeRDP/FreeRDP/files/1113249/osTWbuild.log_20170629.zip)

Builds are done with the latest master of 2017-06-29 for different openSUSE versions; 32 and 64 bit.
For details see the attached log.

**Comment by bmiklautz** [comment]
@hendwolt what compiler was used?

**Comment by hendwolt** [comment]
@bmiklautz 
gcc in different versions (from 4.8 to 7.1).

**Comment by hendwolt** [comment]
All the "interesting" warnings are fixed with today's master (2017-07-24).

**Comment by bmiklautz** [comment]
@hendwolt thanks for testing.
