### ISSUE TITLE
AVC444 stream is low quality compared to a Windows client

### ISSUE THREAD

**Issue by mmeyer724** [FreeRDP/FreeRDP#4030]
While playing around with Microsoft's new h.264 AVC444 codec I noticed that FreeRDP was receiving a much lower quality video stream compared to Microsoft's RDP client.

I've done some light digging into the FreeRDP code and [MS-RDPEGFX PDF](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-RDPEGFX/[MS-RDPEGFX].pdf) but I have not found anything concrete yet. So far I've tried:
* Forcing FreeRDP to send QOE ACKs
* Compiling FreeRDP with OpenH264 instead of libavcodec
* Many different command line options (always including `/gfx-h264:AVC444`)

None of these troubleshooting steps had a noticeable affect on quality.

I took some screen recordings to show you what I mean by 'lower quality'. Unforunately QuickTime decided to record the Windows client in 60 FPS instead of 30 FPS like it did for FreeRDP. Both of them still do a very good job at showing the quality differences though:
FreeRDP: https://www.youtube.com/watch?v=prEzYrLvUR0
Windows 10: https://www.youtube.com/watch?v=7e24kUHxWgk

For both of these tests the RDP server was a Windows 10 machine with an NVIDIA GTX960 being used for hardware encoding (Terminal Services). I also verified that AVC444 was in fact negotiated by watching event viewer: http://imgur.com/a/cUWDe.

I would love to contribute a fix for this myself, but I'm not exactly sure where to go from here. Considering this is a significant issue for me, so I am willing to provide any and all information required to figure this out including packet dumps, experimental testing, debug output, etc.

**Comment by hardening** [comment]
Is it me or on the youtube videos I can't see any significant difference (although that could be me or a youtube artifact) ?

**Comment by mmeyer724** [comment]
@hardening This part of the video shows the blockiness rather well: https://youtu.be/prEzYrLvUR0?t=24 (windows: https://youtu.be/7e24kUHxWgk?t=22)

In 1080p fullscreen I can definitely see a major difference between them. I also recommend watching the network metrics on the right -- terminal services is consistently sending way more data over the wire for the windows client.

**Comment by akallabeth** [comment]
@mmeyer724 Best you play around with the bandwidth measurement mode arguments. MS is relying on bandwidth measurement results for quality estimation and falls back to the worst quality available if not activated.

**Comment by mmeyer724** [comment]
@akallabeth thank you for the hint! The magic combination for me is _both_ `/multitransport` and `/network:auto`. These options greatly improve the frame quality.

Next up however is getting terminal services to throttle the frame rate as necessary, which is controlled by frame acks (section 3.2.5.13 of MS-RDPEGFX):
>... if the queueDepth field is in the range 0x00000001 to 0xFFFFFFFE the server SHOULD
use this value to determine how far the client is lagging in terms of graphics decoding and then
attempt to throttle the graphics frame rate accordingly.

Unfortunately FreeRDP does not know how to send proper frame acks right now, it can only suspend them (queueDepth 0xFFFFFFFF) or claim that the data is unavailable (queueDepth 0x00000000).

But that doesn't apply to this issue, so I will create another issue (or pull request) at some point in the near future. 👍
