### ISSUE TITLE
RdpdrServerContext::DriveReadFile issues

### ISSUE THREAD

**Issue by pedjaman** [FreeRDP/FreeRDP#4031]
Hello,

calling RdpdrServerContext::DriveReadFile issues
causes this error:

[00:05:49:381] [14719:14748] [ERROR][rdpdr.server] - not enough data in stream!
[00:05:49:381] [14719:14748] [ERROR][rdpdr.server] - rdpdr_server_receive_device_io_completion failed with error 13!
[00:05:49:381] [14719:14748] [ERROR][rdpdr.server] - rdpdr_server_receive_pdu failed with error 13!

After some debugging in rdpdr_main.c file this is the result:
`length = SIZE_OF_FILE`
`Stream_GetRemainingLength(s)` is returning 4080.

Any idea what can cause such problem?

**Comment by hardening** [comment]
@pedjaman errno=ECONTEXT

**Comment by pedjaman** [comment]
Thanks. What is that telling us?

**Comment by hardening** [comment]
@pedjaman well that when you report a bug, you need to add some context like specified in https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
AFAIC we don't have any C++ code in FreeRDP...

**Comment by pedjaman** [comment]
OK,

I'm apologize for using C++ syntax. Let me try to be more precise as there are new moments related to this potential bug. Please ignore my first explanation and check this one:

I was making custom RDP server on linux (opnsuse 13.2 64-bit) using FreeRDP as library and it works well. Now, when I attempt to add rdpdr to accept drives shared by client this problem emerged:

My init code:
```
// Init
    RdpdrServerContext * m_ctx = rdpdr_server_context_new(m_vcm);
    m_ctx->data = this;

    m_ctx->supportsDrives = TRUE;
    m_ctx->supportsPorts = FALSE;
    m_ctx->supportsPrinters = FALSE;
    m_ctx->supportsSmartcards = FALSE;

    // Implementation
    // Drive callbacks
    m_ctx->OnDriveCreate = OnDriveCreate;
    m_ctx->OnDriveDelete = OnDriveDelete;
    m_ctx->OnDriveCreateDirectoryComplete = OnDriveCreateDirectoryComplete;
    m_ctx->OnDriveDeleteDirectoryComplete = OnDriveDeleteDirectoryComplete;
    m_ctx->OnDriveQueryDirectoryComplete = OnDriveQueryDirectoryComplete;
    m_ctx->OnDriveOpenFileComplete = OnDriveOpenFileComplete;
    m_ctx->OnDriveReadFileComplete = OnDriveReadFileComplete;
    m_ctx->OnDriveWriteFileComplete = OnDriveWriteFileComplete;
    m_ctx->OnDriveCloseFileComplete = OnDriveCloseFileComplete;
    m_ctx->OnDriveDeleteFileComplete = OnDriveDeleteFileComplete;
    m_ctx->OnDriveRenameFileComplete = OnDriveRenameFileComplete;

    UINT uiRet = m_ctx->Start(m_ctx); //  returned CHANNEL_RC_OK

```

callback `m_ctx->OnDriveCreate` was called for each shared device from client.

After calling
`m_ctx->DriveOpenFile(m_ctx, NULL, device_id, path, GENERIC_READ, OPEN_EXISTING) //  returned CHANNEL_RC_OK`
callback `m_ctx->OnDriveOpenFileComplete` is triggered and provided a file_id. (ioStatus = 0)

device_id and file_id are used here:
`m_ctx->DriveReadFile(m_ctx, NULL, device_id, file_id, size, offset)//  returned CHANNEL_RC_OK`
callback `m_ctx->OnDriveReadFileComplete` is triggered and returned 
ioStatus=3221225506 (0xC0000022) which is STATUS_ACCESS_DENIED

Connection to server is made through regular Windows RDP client running as user member of Administrators group on Windows 7 system.
It has access to the files attempted to read.

Does this help or I need to provide something else?

**Comment by pedjaman** [comment]
OK after replacing GENERIC_READ with FILE_GENERIC_READ I've overcome the problem.
I will close this issue and open new one I've detected.

Thank you guys
