### ISSUE TITLE
xscreensaver and xfreerdp in keyboard grabbing competition

### ISSUE THREAD

**Issue by freerdp-github** [FreeRDP/FreeRDP#4036]
On a fresh Debian 9 install with the latest xfreerdp master, when xfreerdp connects to a W2K12R2 RDS Server and the xscreensaver (blank screen, 10 minutes) kicks in, the screen goes black with the following message in yellow at the top of the screen:

xscreensaver: hh:mm:ss: couldn't grab the keyboard!  (AlreadyGrabbed)

Now, realizing there is a tug-of-war going on with X, I disabled the keyboard grabbing (-grab-keyboard) on the xfreerdp command line. This fixes the problem; however, I would like to know what the side-effects of this action are if any on the Windows application side or any other for that matter. This is probably not a xfreerdp issue but I wanted to ask.

Thanks

**Comment by akallabeth** [comment]
@freerdp-github Keyboard grabbing allows redirecting keys otherwise reserved for system use. Other than that nothing changes.

**Comment by hardening** [comment]
and you always the possibility to launch xfreerdp with -grab-keyboard
