### ISSUE TITLE
I porting RAIL channel on Android , But I have a trouble.... 

### ISSUE THREAD

**Issue by umhahahahapu** [FreeRDP/FreeRDP#4037]
I would like to execute remote application on my android directly so I porting rail channels on Android.
However I'm confused of How to I execute remote application ....????

 X11 use excute app window* or winodw but Android has no variable window, app window*
  (because Android has no X11)

 How to Android app excute remote application ??? I implement RAIL channels .......

**Comment by hardening** [comment]
Hi @umhahahahapu, unfortunately an issue tracker is not the place to ask questions, for that you have IRC or the mailing list. Please go and discuss there.
