### ISSUE TITLE
iOS OpenSSL 1.1.0e Build Issue

### ISSUE THREAD

**Issue by mhoskin** [FreeRDP/FreeRDP#4046]
I've been trying to build FreeRDP with OpenSSL 1.1.0e and SDK 10.3, but have been struggling trying to get this built to create a 64-bit compliant app. I've tried building the libraries separately through OpenSSL for iOS and loading them, but get an error with libwinpr.a not being built with bitcode and also by modifying the DownloadAndBuild command to download the 1.1.0e OpenSSL version, but it seems to fail building each arm (I only see the lib crypto and libssl libraries in the 386 formats).

I'm using Xcode 8.3.1 and MacOS 10.12.4. Could anyone point me in the right direction with this problem?

**Comment by akallabeth** [comment]
This is an issue tracker, see https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Please use IRC or mailing list for such questions.
