### ISSUE TITLE
Remote App on Android just shows a black screen

### ISSUE THREAD

**Issue by mohaqeq** [FreeRDP/FreeRDP#4048]
I compiled the latest version with android ndk 15 on ubuntu and every thing works fine but when I try to specify a remote application I just get a black screen. It seems connected but nothing shows up.

**Comment by bmiklautz** [comment]
@mohaqeq remote app is not supported on Android. The only thing supported is to specify a startup application. Is this what you meant?

**Comment by mohaqeq** [comment]
at least the released application on Google Play supports this feature.

**Comment by mohaqeq** [comment]
So, you mean if I use /shell instead of /app it will solve the "Remote Program" problem?

**Comment by bmiklautz** [comment]
@mohaqeq should do, yes.

**Comment by mohaqeq** [comment]
Thanks, It solved.

**Comment by bmiklautz** [comment]
Still on master an in aFreeRDP in google play. Needs fixing.
