### ISSUE TITLE
Brew installs an old version of FreeRDP

### ISSUE THREAD

**Issue by tww0003** [FreeRDP/FreeRDP#4049]
Using the command `brew install freerdp` installs version 1.0.2 of freeRDP. This version appears to have different syntax than the current version and results in the examples not working properly.  
  
The instructions found on freerdp.com give this command and says optionally to use `brew install freerdp --HEAD` which is misleading for user, who thought that using `brew install freerdp` would install the most current, stable, release.

**Comment by bmiklautz** [comment]
@tww0003 as far as I know brew instralles the latest stable version and officially 1.0.2 is the current stable release. The next release will follow soon then this issue should be resolved.
