### ISSUE TITLE
Parent-Window and Keyboard

### ISSUE THREAD

**Issue by Jeffrey-73** [FreeRDP/FreeRDP#4051]
I'm toying around with wfreerdp.exe and the /parent-window argument to pass in a window handle from a WinForms panel or control. This works great except that keyboard input doesn't work. Mouse input works as expected though. Can someone provide guidance on how to handle or forward keyboard input?

**Comment by akallabeth** [comment]
@Jeffrey-73 Please use the mailing list / IRC for such questions, this is an issue tracker.
