### ISSUE TITLE
Can't build FreeRDP using iOS Readme

### ISSUE THREAD

**Issue by mhoskin** [FreeRDP/FreeRDP#4058]
I've been trying to build FreeRDP using the default project and SDK 10.3, but I've yet to get it built properly.  I built the OpenSSL libraries separately using OpenSSL for iOS using version 1.0.2k (listed as the working version for SDK 10.2), copied them to the /external/openssl directory and ran the iOSToolchain command to create the Xcode project, but the Xcode project does not compile as I get errors indicating that all of the libraries are not built:

clang: error: no such file or directory: '~/client/common/Release-iphoneos/libfreerdp-client2.a'
clang: error: no such file or directory: '~/client/common/Release-iphoneos/libwinpr2.a'

And 20 other similar errors in total.  I have the iFreeRDP project selected as the main scheme and "Generic iOS Device" as the device target and was just attempting to build the project. 

Could I get some assistance on what I'm doing wrong?  Or if someone has a working compiled version of the project, I would appreciate that as well.

**Comment by akallabeth** [comment]
@mhoskin As already mentioned, please use mailing list or IRC (and stay online so you can get a response ;) Looks like we are in different time zones). As for the rest, it is hard to tell with that little information, so maybe you better start with a clean checkout.
