### ISSUE TITLE
Cannot use multitransport connection with H.264

### ISSUE THREAD

**Issue by cbosys** [FreeRDP/FreeRDP#4059]
Hello
I want to use H.264 video compression using UDP transport protocol.
When launching command line : 
`xfreerdp /v:xxxx /u:xxxx /p:xxxx /multitransport /gfx-h264:AVC420`,
I have a black screen (5-6 seconds) and the session opens.
When i check the event viewer on my terminal server, I have events : 

> RDP_UDP: An error was encountered when transitioning from UdpStateProcessTransportHandshake in response to UdpEventErrorOnMtReqComplete (error code 0x800705B4).

> The multi-transport connection finished for tunnel: 1, its transport type set to TCP: Reason Code: 4 (UDP Handshake Timeout).

> RDP_UDPLOSSY: An error was encountered when transitioning from UdpLossyStateProcessTransportHandshake in response to UdpEventErrorOnMtReqComplete (error code 0x800705B4).

> The multi-transport connection finished for tunnel: 3, its transport type set to TCP: Reason Code: 4 (UDP Handshake Timeout).

And my RDP session falls into TCP mode only.

Multitransport mode seems to work with the following command line : 
`xfreerdp /v:XXXX /u:XXXX /p:XXXX /multitransport`

Using FreeRDP branch 2.0.0-beta1+android11
Server Windows Server 2012 R2

**Comment by akallabeth** [comment]
@cbosys UDP support has not been implemented, so this is expected behaviour.
