### ISSUE TITLE
RemoteApp Not Responding during a refresh then crashes

### ISSUE THREAD

**Issue by Lastwolf** [FreeRDP/FreeRDP#4062]
The App hangs when it needs to refresh the page, then it shuts down with the message

[6866:6867] [INFO][com.freerdp.client.x11] - Property 309 does not exist

**Comment by bmiklautz** [comment]
@Lastwolf the INFO  you have pasted is really just an information that some x property doesn't exist but should't cause a crash. What version of FreeRDP are you running? What's the command line you are using. Could you provide more information about the crash?
