### ISSUE TITLE
Multimedia Redirection for iOS!

### ISSUE THREAD

**Issue by SuperKingKang** [FreeRDP/FreeRDP#4065]
Hi,I had realized the video redirection with "libopenh264.a" and "libjpeg.a".But the audio redirection is not.
So what should i do to complete it? Is it supported the audio redirection by the latest version of FreeRDP?
Waiting for the reply,thanks.（PS:Sorry for my poor english level!）

**Comment by akallabeth** [comment]
@SuperKingKang Seems like you get a few things mixed up here. Video redirection is something entirely different than the GFX channel (which uses openH264 or ffmpeg). Better consult the mailing list/IRC for clarification, here we try to have an issue tracker, not a support forum.
