### ISSUE TITLE
[FreeRDP 1.0.3] Pause sends Pause, Control (WTS2012R2) and not Pause / CTRL + NUMLOCK

### ISSUE THREAD

**Issue by T3N4K4** [FreeRDP/FreeRDP#4068]
Is there the possibility to get a fix for FreeRDP 1.0.3 that Pause sends only Pause in a Windows Terminal Server session on 2012R2 / 2016 and not "Pause, Control"? This way the left windows key + pause would work again.

If not, could you give me a hint where to look ?
I found the parts where CTRL + NUMLOCK is sent to emulate the mstsc behavior. But this code looks almost the same as in the latest master. Even though the latest master does it correctly.

I tried with both 0x407 and 0x409 with both having the same result.

Command line:
/usr/bin/xfreerdp -x m --gdi hw -f --no-bmp-cache -a 32 -k 0x409 -T "Test" --no-tls --no-rdp --plugin rdpsnd --data pulse -- -z --disable-menu-animations --disable-full-window-drag --plugin rdpdr --data -- --ignore-certificate -u -p -d  [SERVER]

Buildconfig:
Standard

**Comment by ilammy** [comment]
As I recall, there was some code inside libfreerdp (as opposed to xfreerdp client) which handled some peculiar key presses. I can't remember exactly where, maybe someone else has some ringing bells?

**Comment by T3N4K4** [comment]
I tried different combinations ... even the old "E1 1D 45 E1 9D C5". But everytime it is Pause, Control which is received in the session ... :(

**Comment by T3N4K4** [comment]
@akallabeth @hardening is there a chance for a fix ?

**Comment by bmiklautz** [comment]
@T3N4K4 we won't do any fixes/updates for 1.0 anymore. What distribution you are using?

**Comment by T3N4K4** [comment]
@bmiklautz I guess it does not matter which distribution I use. I just tested with ubuntu 14.04, 15.10 and 16.04.
Tried to fix it for myself but everytime control + numlock is sent, it gets pause,control in the session.

Even when I tried to introduce the [MS-RDPBCGR] KBDFLAGS_EXTENDED1 which seems to be used instead of KBDFLAGS_EXTENDED it did not work.

**Comment by bmiklautz** [comment]
@T3N4K4 are you seeing the same problem with the nightly builds (master) as well?

**Comment by T3N4K4** [comment]
@bmiklautz no as I said in current master it is working.

**Comment by bmiklautz** [comment]
@T3N4K4 sorry, my bad over read that part :). Using the nighties or is not an option for you?

**Comment by T3N4K4** [comment]
@bmiklautz no problem ;)
The problem is that the current master / nightlies disconnect very often while working inside a session or looking youtube videos (best test-case ever :-/). 
The 1.0.3 has no such problems... therefore we are currently offering FreeRDP 1.0.3 and FreeRDP-master. In my opinion the current master is very good except the disconnects only we or our customers are experiencing.

**Comment by T3N4K4** [comment]
I am closing this, since FreeRDP 2.x is now in a state where this change for 1.0.x is not needed anymore ;-)
