### ISSUE TITLE
FreeRDP server doesn't provide mouse and keyboard input

### ISSUE THREAD

**Issue by cbosys** [FreeRDP/FreeRDP#4073]
FreeRDP server : latest master
FreeRDP client : latest master
 
Server on Debian  8 Jessie
Clients on Debian 8 Jessie/Raspberry Pi 3

BUILD command line for server : 
$ cmake -DWITH_SSE2=ON -DWITH_SERVER=ON -DWITH_LIBAVCODEC=OFF -DWITH_OPENH264=ON -DCMAKE_BUILD_Type=Release

BUILD command line for client : 
$ cmake -DWITH_SSE2=ON

FREERDP server command line : 
$ freerdp-shadow-cli

FREERDP client command line : 
$ xfreerdp /v:XXXX /u:XXXX /p:XXXX /cert-ignore /gfx-h264=AVC420

the client connect successfuly but I cannot use client mouse or keyboard.

EDIT : same issue when using MSTSC as RDP client.

**Comment by realjiangms** [comment]
You might need to confirm that your build environment has libxtst-dev

**Comment by bmiklautz** [comment]
@cbosys you are testing on the same x or on different systems?

**Comment by Nachtgast** [comment]
fedora 25  mouse and keyboard  input not working , no interaction with desktop

**Comment by akallabeth** [comment]
@Nachtgast could you post the output of ```xfreerdp /buildconfig```? Tried with nightlies and a custom build on fedora 26 here and input is working...

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
Reopen or create a new one if still an issue.
