### ISSUE TITLE
Copy more than 2g files

### ISSUE THREAD

**Issue by earcg** [FreeRDP/FreeRDP#4075]
/drive:usb,/mnt/udisk/   Copy more than 2g files to u disk failed

freerdp Version :  https://github.com/FreeRDP/FreeRDP
Command line : xfreerdp -f /rfx /size:1920x1080 /drive:usb,/mnt/udisk/ /u:test5 /p:5 /v:192.168.1.124:3389 /bpp:16 /vc:rdpsnd,sys:alsa,dev:default,rate:44100,channel:2

when i copy files (the file size more than 2GB )from usb disk to server desktop , the client failed , and the file offset value is -2147483648

**Comment by akallabeth** [comment]
Please provide some basic information. Versions? Command line? Server?

**Comment by earcg** [comment]
freerdp Version : https://github.com/FreeRDP/FreeRDP
Command line : xfreerdp -f /rfx /size:1920x1080 /drive:usb,/mnt/udisk/ /u:test5 /p:5 /v:192.168.1.124:3389 /bpp:16 /vc:rdpsnd,sys:alsa,dev:default,rate:44100,channel:2

when i copy files (the file size more than 2GB )from usb disk to server desktop , the client failed , and the file offset value is -2147483648

**Comment by earcg** [comment]
@akallabeth  This version still doesn't solve my problem.

**Comment by akallabeth** [comment]
@earcg Can copy 5G of data here just fine with current master, are you sure you are using the correct source for your test?
If that is the case, could you append ```xfreerdp /buildconfig``` output, maybe there is something with the build flags on your end preventing proper operation.

**Comment by earcg** [comment]
@akallabeth 
This is FreeRDP version 2.0.0-dev (git 80ed237)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_JPEG=OFF WITH_KRB5=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NEON=ON WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU, 4.8.4
Target architecture: ARM

**Comment by akallabeth** [comment]
@earcg And you get the same error messages? Can you eliminate the USB drive (which filesystem?) as source of the error?

**Comment by akallabeth** [comment]
@earcg Ok, found the issue, we did use ```fseek``` and ```ftell``` which are limited to 32bit signed offset values on 32bit operating systems.

**Comment by earcg** [comment]
@akallabeth  Thank you for solving this problem。
