### ISSUE TITLE
Flashing Black Boxes when using RemoteFX

### ISSUE THREAD

**Issue by Enverex** [FreeRDP/FreeRDP#4078]
After adding RemoteFX to the client VM, FreeRDP starts flashing black boxes over most items when hovered as though it's not redrawing properly. This only seems to happen when the container has a the RemoteFX adapter added.

Here's an example of it happening - https://www.youtube.com/watch?v=YuunSqZnMtA (sorry about the quality, phone really didn't like the monitor moire and for some reason YouTube flipped it upside down).

Performance is relatively OK, you can load a fullscreen video and it'll run mostly smoothly, but obviously this massive glitching when hovering over anything makes it completely unusable.

I've tried disabling the glyph, bitmap and offscreen caches to no effect.

Let me know if you need any more specific info.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Need a bit more of information to guess what is going on.
Since you seem to have a very specialized setup, does this flickering also occur with other RDP clients?

**Comment by Enverex** [comment]
The setup is rather unique unfortunately and all the thin-client machines are isolated or air-gapped from the actual internet so getting real details is quite a faff, I'll try though.

Distro is Arch, package is freerdp 1:2.0.0_rc0-3 (dated 2017-07-25 10:25 UTC).
The containers that the RDP client is connecting in to are Hyper-V based running Windows 10 Enterprise (Creators Update). The server itself is set up with 4 Nvidia GRID cards which it's using for RemoteFX.

EDIT: Gah, this is happening with an actual Windows RDP client so it's not a FreeRDP issue. Sorry guys.
