### ISSUE TITLE
xfreerdp execute remoteapp but some of apps opened two windows......

### ISSUE THREAD

**Issue by umhahahahapu** [FreeRDP/FreeRDP#4080]
I used xfreerdp remote app,(windows 10 Pro)
But , some of apps running two display windows and some of the other apps running one display windows well....

I didn't find something wrong .....................diffrence normal and abnormal ...

For example, remote word app running display shows two, but remote app ppt (power point) running display shows only one. (normal) 
What caused that ???

**Comment by hardening** [comment]
Could you give look at https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

Honestly I can't see what's wrong in what you're reporting. Don't forget that this is an issue tracker not an help forum, for that you have IRC or the mailing list.
