### ISSUE TITLE
Broken Pipe and Protocol Security Negotiation Failure

### ISSUE THREAD

**Issue by jpmelnik** [FreeRDP/FreeRDP#4082]
System Config
Ubuntu 16.04
Remmina
FreeRDP 2.0.0~dev

>[com.freerdp.core.transport] - BIO_should_retry returned a system error 32: broken pipe
[com.freerdp.core.nego] - Protocol Security Negotiation Failure
[com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED
[com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[com.freerdp.client.x11] - Freerdp connect error exit status 1

**Comment by T3N4K4** [comment]
Which command line / which protocol are you using ? I often get this error when I forget to set +sec-nla.

**Comment by bmiklautz** [comment]
@jpmelnik what system you are connecting to?

**Comment by jpmelnik** [comment]
I've forgotten to change my router local ip.

Router: 192.168.2.1
VPN: 192.168.1.1

Thanks you guys.
