### ISSUE TITLE
How to solve the problem of voice and video are not synchronized？

### ISSUE THREAD

**Issue by OldTianDeZiLiuDi** [FreeRDP/FreeRDP#4086]
After connected RDP, broadcast video, play the longer, the more serious the voice delay.
Connection configuration as follows：
xfreerdp -f /rfx /bpp:32 /workarea /client-hostname:$HOSTNAME  /sec:rdp  /network:lan /frame-ack:1 /size:$REMOTEGEOMETRY /vc:rdpsnd,sys:alsa,dev:default,rate:44100,channel:2,latency:200 /microphone:sys:alsa,dev:default /drive:usb,/mnt/udisk/ /u:$REMOTEUSERNAME /p:$REMOTEPASSWD  /v:$REMOTEIP:3389

**Comment by akallabeth** [comment]
@OldTianDeZiLiuDi That can only be solved by finding a configuration your hardware can handle. Depending on the target OS you may want to add ```/network:auto``` and ```/gfx:avc444``` to allow H264 modes and automatic bandwidth adjustment. For further questions please consult the mailing list or IRC as this is an issue tracker.
