### ISSUE TITLE
Possible to lock an remoteapp on one monitor if i two?

### ISSUE THREAD

**Issue by boospy** [FreeRDP/FreeRDP#4090]
I use windowsprogramms over the rdp appfeature. I can't find infos about that i can lock the location of the application on one specific screen. Is there a possible action, or maybe it is possible to use the windowdecorations of the used windowmanager like kwin? I use the actual git version as DEB-Package. My cmd this time is:
`xfreerdp /d:iteas.local /u:$USER /p:secret +fonts  +clipboard  /cert-ignore   /v:hostname /app:"||StepsExplorer" /jpeg /jpeg-quality:100 /gdi:hw +window-drag  /disp /drive:HOME,/home/$USER/Downloads /printer`

**Comment by akallabeth** [comment]
Window placement ishandled by the local window manager, nothing we can do here.
