### ISSUE TITLE
Use freerdp to pair-program between 2 Gnome Wayland

### ISSUE THREAD

**Issue by DamienCassou** [FreeRDP/FreeRDP#4093]
My computer is running F26 on Xorg because I need a way to pair-program with friends remotely (I'm using TeamViewer). I would like to move to Wayland and stop using TeamViewer (proprietary software and Xorg only). Is FreeRDP a possible solution?

**Comment by bmiklautz** [comment]
@DamienCassou as already mentioned in IRC FreeRDP has an "shadow" server where you can share a running X session via RDP. There is also a basic client for wayland.
You could use some virtual X server like xvfb and run a virtual xserver with gnome where all people connect to with the wayland client. 

Please not that this is an **issue tracker** and not an help forum. For help please use IRC or the mailing list.
