### ISSUE TITLE
Freerdp not full screen build 20170815

### ISSUE THREAD

**Issue by michaelschefczyk** [FreeRDP/FreeRDP#4096]
So far, on a Debian stretch PC with gnome, the following command led to a full screen rdp connection (similar with /f instead of /multimon):

/opt/freerdp-nightly/bin/xfreerdp /multimon /u:... /d:... /v:...

This did work up to build #4​13 Aug 11, 2017 3:49 AM (freerdp-nightly_2.0.0+0~20170811014837.412~1.gbpb34b32_amd64.deb and -dbg). From build #4​14
Aug 15, 2017 3:48 AM (freerdp-nightly_2.0.0+0~20170815014830.413~1.gbp790c48_amd64.deb and -dbg), the screen is no longer full screen. There is rather a visible frame with decoration.

**Comment by abma** [comment]
https://github.com/FreeRDP/FreeRDP/compare/b34b32...790c48

https://github.com/FreeRDP/FreeRDP/commit/6b7b60237042a891221d71a596fc683d850bcb4e looks suspicious

**Comment by hardening** [comment]
bug confirmed.

**Comment by hardening** [comment]
We should revert https://github.com/FreeRDP/FreeRDP/commit/6b7b60237042a891221d71a596fc683d850bcb4e as it breaks fullscreen on both openbox and other WM

**Comment by T3N4K4** [comment]
Thats interesting. It works for me though in xfce / xfwm4 and openbox. But I'm happy to check it again.

**Comment by hardening** [comment]
@T3N4K4 from my debugging session, checking the X window property always returns False (as it has not been set before), so that's not the proper way to detect the old fullscreen behaviour.

**Comment by T3N4K4** [comment]
@hardening isn't https://github.com/FreeRDP/FreeRDP/blob/master/client/X11/xf_client.c#L1783 supposed to set the property ?

https://tronche.com/gui/x/xlib/window-information/XInternAtom.html

**Comment by hardening** [comment]
@T3N4K4 https://github.com/FreeRDP/FreeRDP/blob/master/client/X11/xf_client.c#L1783 just retrieves the atom associated with the name _NET_WM_FULLSCREEN_MONITORS.

I'm not sure it makes sense to test that property on the root window...

**Comment by T3N4K4** [comment]
@hardening I'll look into it again.. just revert the patch first. Maybe I am missing something .. but then almost no atom / property is initialized. Either way, I'll look again if I can create the version again which worked for me.

**Comment by gh-user-7392** [comment]
Having this problem as well with the latest build of master on Lubuntu 16.04.3 with LXDE and openbox. When running, have been getting X11 Property 476 does not exist as well as other properties missing errors.

**Comment by T3N4K4** [comment]
@hardening and @nfedera  some more notes on this:
When I start freerdp (custom debug), I get the following for the first few Atoms ->
property _NET_CURRENT_DESKTOP
actual_type 6
actual_format 32
nitems 3015282416
bytes 3015282420
property _NET_WORKAREA
actual_type 6
actual_format 32
nitems 3015282416
bytes 3015282420
[10:34:02:391] [17043:17052] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[10:34:02:392] [17043:17052] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
property _NET_WM_FULLSCREEN_MONITORS
actual_type 0
actual_format 0
nitems 3015282304
bytes 3015282308

_NET_CURRENT_DESKTOP and _NET_WORKAREA are read out the same way as is _NET_WM_FULLSCREEN_MONITORS. And all three of them are read out from the DefaultRootWindow ..
But even if the property does exist, it throws me that it does not exist.

With my manual way of adding the +openbox in combination with -decorations I get the result I wanted ... so either way if _NET_WM_FULLSCREEN_MONITORS exists it returns None / 0, if it does not exist it still returns None / 0.

**Comment by gh-user-7392** [comment]
As noted above (Lubuntu 16.04.3 with LXDE and openbox), this is happening to us using simply the /f command line switch. We do not use multiple monitors. Although I can appreciate the openbox commit, I really don't think the user should have to select options based on what window manager they are using. Many would not even know what a WM is and turn off to FreeRDP because it does not work correctly. I think this is a bad idea from a long time user of FreeRDP. General WM issues such as -decorations or /wm-class options are warranted but targeting specific WM problems should be avoided. Please get back to the normal /f functionality.

**Comment by jasonblewis** [comment]
On Gnome, with multiple monitors. if you open the xfreerdp window on a monitor with no top bar, it goes full screen as expected. if you open it on the monitor with the top bar, it stays windowed as described above.

debian stretch
This is FreeRDP version 2.0.0-dev (git 9a81531cb)

**Comment by akamuza** [comment]
Ubuntu 16.04, still the same issue with /f option after the latest update of nightly build.

> [com.freerdp.client.x11] - Property 468 does not exist

**Comment by abma** [comment]
which version? you need at least 5258a980f50f3c3536e4482a158554d7514951e7 which was commited an hour ago. IDK how often the "nightly" builds are created: i guess its once nightly so wait at least 24 hours :-P

**Comment by bmiklautz** [comment]
@abma @akamuza the nightly builds are created once a day (in the night some when around 2h UTC)

**Comment by akamuza** [comment]
After today's nightly update /f flag works as expected, thanks. (Ubuntu 16.04, 1 monitor)
