### ISSUE TITLE
Problem with 16 bit and /rfx

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#4101]
If the local X server is started with 16 bit and /rfx is used then the resulting session is distorted (artifacts and half of the screen is black). This happens with sw and hw GDI.

Steps to reproduce:
* start a X server with 16 bit (e.g. Xephyr :200 -screen 1024x768x16)
* launch xfreerdp on this xserver with /rfx

**Comment by akallabeth** [comment]
Fixed ```/gdi:sw``` RFX decoding, with ```/gdi:hw``` there are distortions left, but they seem to originate from some other callback.
