### ISSUE TITLE
-- Configuring incomplete, errors occurred!   -- MacOS Sierra  (iOS)

### ISSUE THREAD

**Issue by VHurricaner** [FreeRDP/FreeRDP#4105]
OS:10.12.6
Xcode:8.3.3
cmake:3.9.1
openssl: 1.0.2L

========
hurricaner-3:FreeRDP hurricaner$ cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode
CMake Deprecation Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/CMakeForceCompiler.cmake:69 (message):
  The CMAKE_FORCE_C_COMPILER macro is deprecated.  Instead just set
  CMAKE_C_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/iOSToolchain.cmake:51 (CMAKE_FORCE_C_COMPILER)
  CMakeFiles/3.9.1/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:23 (project)

CMake Deprecation Warning at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/CMakeForceCompiler.cmake:83 (message):
  The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  cmake/iOSToolchain.cmake:52 (CMAKE_FORCE_CXX_COMPILER)
  CMakeFiles/3.9.1/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:23 (project)

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- FreeRDP GIT
-- Git Revision f9a47a346
-- Skipping recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature DirectFB for DirectFB (DirectFB client)
-- Finding required feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindOpenSSL.cmake:325 (find_package_handle_standard_args)
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:750 (find_feature)

-- Configuring incomplete, errors occurred!
See also "/Users/hurricaner/Documents/FreeRDP/CMakeFiles/CMakeOutput.log".
See also "/Users/hurricaner/Documents/FreeRDP/CMakeFiles/CMakeError.log".

**Comment by bmiklautz** [comment]
@VHurricaner did you build openssl for ios? Have a look to docs/README.ios

**Comment by VHurricaner** [comment]
Yes,I did
=======
hurricaner-3:FreeRDP hurricaner$  ./scripts/OpenSSL-DownloadAndBuild.command
