### ISSUE TITLE
USB redirect issue

### ISSUE THREAD

**Issue by revo1059** [FreeRDP/FreeRDP#4106]
I'm running cmake on a Pi to get FreeRDP running using the following commands (after installing all the prerequisite packages)

cmake DTARGET_ARCH_ARM -DWITH_NEON=OFF -DCHANNEL_URB_CLIENT=ON -DCHANNEL_URBDRC=ON -DBUILTIN_CHANNELS=OFF

when I run FreeRDP with the switch for a device I get:

/usr/local/lib/freerdp2/liburbdrc-client.so no such file

I'm probably missing some package but I have no idea what.

The following packages are installed:

apt-get install uuid-dev
apt-get install libdbus-glib-1-dev
apt-get install dbus-*-dev
apt-get install libpcsclite-dev, libusb-1.0-0-dev
apt-get install libusb-1.0-0-dev
apt-get install libudev-dev

**Comment by revo1059** [comment]
Re-installing worked. Closing case.

**Comment by mark-hahn** [comment]
I'm getting the same `/usr/local/lib/freerdp2/liburbdrc-client.so no such file`.   I'm compiling the github master branch using ...

```
cmake -DWITH_SSE2=ON -DCHANNEL_URBDRC_CLIENT=ON -DCHANNEL_URBDRC=ON -DBUILTIN_CHANNELS=OFF -DCMAKE_BUILD_TYPE=Debug
```

I've installed many times with variations.  Any ideas?

**Comment by mark-hahn** [comment]
I forgot to say I'm using 

```
Distributor ID:	Ubuntu
Description:	GalliumOS 2.1
Release:	16.04
Codename:	xenial
```

**Comment by mark-hahn** [comment]
I fixed it by installing a bunch of mysterious (to me) libraries.  I think most were already installed so I don't know which one fixed it...

```
uuid-dev
libdbus-glib-1-dev
libpcsclite-dev
libudev-dev
uuid-dev
libusb-1.0-0-dev
libdbus-glib-1-dev
libavcodec-dev -y
```

I got many of these from http://www.programering.com/a/MzNyMzNwATA.html.

**Comment by ahmedkaballo** [comment]
Hi
Can I use USB Redirection with windows 10 VM via freerdp without RemoteFx USB Redirection?
