### ISSUE TITLE
multiple freerdp-shadow-cli

### ISSUE THREAD

**Issue by Elaci0** [FreeRDP/FreeRDP#4108]
Hello there and thanks for this great piece of software!
I was wondering if the "freerdp-shadow-cli" , once run, could act like the Microsoft's RDP server to allow multiple connections and screens sharing for multiple users.
Thanks,
 E.

**Comment by bmiklautz** [comment]
@Elaci0 thanks for your feedback glad to hear :).
freerdp-shadow-cli is not a full featured RDP server. It can rather be compared with vnc where you can share a running session. However it is possible that multiple users can connect to the *same*  xsession.

As this is an issue tracker please use IRC or our mailing list for questions in future. Thanks.

**Comment by adityasood11** [comment]
@bmiklautz  Hi. I am only able to run freerdp-shadow-cli but not the main wfreerdp application. 
Am i missing some cmake build options while generating the solution file. These are my current build options
`cmake –DWITH_SERVER=ON -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib`

Please reply. I need to run the main freerdp server on windows.
