### ISSUE TITLE
Can't change primary display

### ISSUE THREAD

**Issue by jtremblaytdst** [FreeRDP/FreeRDP#4109]
I cant change primary display when multimonitor ?

**Comment by bmiklautz** [comment]
Is that a question or a finding?
Please have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting and add more information.

**Comment by jasonblewis** [comment]
If you have a 3 monitor setup and connect to Windows 10, using ```/f /multimon /monitors:0,1,2``` the "main" desktop in Windows 10 is always the far left (or monitor 0 in my case). I'm not sure how to control this but in Windows if you right click the windows desktop and select Display Settings, there is no option to alter the "main" display. 
![win10 rdp display options](https://user-images.githubusercontent.com/129165/31641564-4b93cccc-b331-11e7-9b35-a4bfd70a521d.PNG)

it would be great if there was a way to set which display should be considered the "main" display.

I'm using FreeRDP version 2.0.0-dev (git 5258a980f)

**Comment by bmiklautz** [comment]
@jasonblewis I wonder if this actually is possible for remote session at all. Did you try if it's possible with Microsoft's client?

**Comment by jtremblaytdst** [comment]
Microsoft client take the client primary display to be the primary display. Freerdp always take the right screen to be the primary display. This is the difference. Freerdp need to check which screen is the primary to send it to the host after.

**Comment by hardening** [comment]
@jtremblaytdst can you try https://github.com/FreeRDP/FreeRDP/pull/4187 ?

**Comment by akallabeth** [comment]
Working here now, reopen if still an issue.

**Comment by aperomsik** [comment]
For me, with Ubuntu 18.10, this is working on X but not on Wayland -- on Wayland the wrong monitor is considered primary by remote Windows.
