### ISSUE TITLE
No full screen ver 20170827014832

### ISSUE THREAD

**Issue by OriginalFlavor** [FreeRDP/FreeRDP#4110]
Full screen across multiple monitors stopped working after upgrading to 20170827014832.

The unity-panel remains visible when the FreeRDP window is "full screen".

The system is running Ubuntu 17.04.

**Comment by underwor44** [comment]
Same with Ubuntu 16.04.

**Comment by hardening** [comment]
we have the fix in the wire, it's in https://github.com/FreeRDP/FreeRDP/pull/4104 .

**Comment by OriginalFlavor** [comment]
@hardening 
Can you direct me to a guide for implementing the fix. This is the first time I ever used Git.
I have been relying on the package manager (http://pub.freerdp.com/repositories/deb/zesty/freerdp-nightly).
Regardless, thank you for your help.

**Comment by bmiklautz** [comment]
@OriginalFlavor wait until tomorrow and you can use the nightly package that should contain the fix.

**Comment by OriginalFlavor** [comment]
The status bar remains visible, above the freerdp window, even when freerdp is in "full" screen.
Upgrade to 2.0.0+0~20170830014829.417~1.gbp5258a9 did not fix the problem.

Command line:
`xfreerdp /bpp:32 /multimon /u:USERNAME /v:SERVER.com +clipboard /sound:sys:alsa /f`
Connecting to Windows Server 2008 R2 Standard

I expected to connect fullscreen across two monitors. As I had connected up to last weekend.
What actually happened is the window opened, the connection began, but the Ubuntu status bar remained visible at the top and the bottom of the window, equal to the height of the status bar, was off screen.
My OS is ubuntu 17.04 64-bit
freerdp version 2.0.0+0~20170830014829.417~1.gbp5258a9

**Comment by underwor44** [comment]
Fix in nightly build 2.0.0+0 20170831014829.418 1.gbp5115ec seems to work for me. Ubuntu 16.04.

**Comment by OriginalFlavor** [comment]
@akallabeth 
The fullscreen issue remains after upgrading to 2.0.0+0~20170831014829.418~1.gbp5115ec
Ubuntu 17.04 64-bit

**Comment by akallabeth** [comment]
@OriginalFlavor Ok, reopening. Strange that your results differ from @underwor44.

**Comment by OriginalFlavor** [comment]
@akallabeth @bmiklautz My issue with the status bar persists.

Is there a way to get more detailed information to post for troubleshooting?

I saw the following in my terminal when logging in.

```
[08:24:31:451] [8557:8558] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[08:24:31:451] [8557:8558] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[08:24:31:460] [8557:8558] [INFO][com.freerdp.client.x11] - Property 449 does not exist
[08:24:31:462] [8557:8558] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[08:24:31:747] [8557:8558] [INFO][com.freerdp.client.x11] - Logon Error Info SESSION_ID [LOGON_MSG_SESSION_CONTINUE]
[08:24:56:894] [8557:8558] [INFO][com.freerdp.client.x11] - Property 449 does not exist
[08:25:05:175] [8557:8558] [INFO][com.freerdp.client.x11] - Property 449 does not exist
[08:26:46:230] [8557:8558] [INFO][com.freerdp.client.x11] - Property 449 does not exist
```

**Comment by hardening** [comment]
@OriginalFlavor are you sure to run the up to date version ? As the log you're showing was the one we were seeing with older (buggy) versions.

**Comment by OriginalFlavor** [comment]
@hardening 
Do I have to do anything different to launch the daily update?

To launch the daily update is the following correct?

`$ xfreerdp /multimon /u:USERNAME /v:remote.mydomain.com /f`

The version tag outputted the following:

```
$ xfreerdp /version
This is FreeRDP version 2.0.0-dev (git n/a)
```

Does that version output indicate that I am not running the daily release?

The files in /opt/freerdp-nightly appear to have the most recent daily version.

**Comment by hardening** [comment]
Well it should be ok if you don't have another versions deployed in locations that are before in the PATH.

**Comment by OriginalFlavor** [comment]
I checked the directories in the $PATH.
Only one directory had an xfreerdp file: usr/bin/xfreerdp.  The file xfreerdp was last modified on August 18, 2017.
Does that help?

**Comment by hardening** [comment]
@OriginalFlavor I merged the fix on August 29, 2017. That may explain...

**Comment by OriginalFlavor** [comment]
First, I installed the package:
sudo apt-get install freerdp2-x11

Then, I installed the nightly update package
sudo apt-get install freerdp2-x11

The package webpage (https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds) says that "the nightly builds can be installed in parallel with distributions regular freerdp package."

Does that mean I could run the regular freerdp package? How?
Does that mean I could choose to run the nighly package? how?

**Comment by hardening** [comment]
That means that you must:
* update your nightly package (download the new version and install it);
* launch the xfreerdp in /opt/freerdp-nightly/bin

**Comment by OriginalFlavor** [comment]
@hardening @akallabeth Specifying the path for the version to launch worked! The freeRDP in /opt/freerdp-nightly/bin worked perfectly. The issue with the status bar being visible even in full screen is resolved. Thank you for all of your help.

**Comment by hardening** [comment]
@OriginalFlavor was the last blocker, closing.
