### ISSUE TITLE
Freerdp graphics problem with 15bpp

### ISSUE THREAD

**Issue by blexen** [FreeRDP/FreeRDP#4111]
Hello! 
Help me please.
Connecting with ubuntu 16 to windows server 2008 r2 there was a problem with the graphics In libreoffice
command: `xfreerdp  /u:user /p:pass /cert-ignore /f /bpp:24 /v:192.168.1.1`
Freerdp from the ubuntu repository:
![freerdp1](https://user-images.githubusercontent.com/31433202/29812878-ce22c226-8cb0-11e7-968a-08270612205b.jpg)
Compilation `https://github.com/FreeRDP/FreeRDP/wiki/Compilation` freerdp 2.0.0-dev
Inactive lines  were selected in the context menu:
![freerdp2](https://user-images.githubusercontent.com/31433202/29813010-45adbba2-8cb1-11e7-9412-5dac1aa98123.jpg)
In remmina everything is good:
![remmina](https://user-images.githubusercontent.com/31433202/29813376-89af81f4-8cb2-11e7-91c0-bacd6418f79d.jpg)

**Comment by akallabeth** [comment]
@blexen Please use the mailing list or IRC for support. This is an issue tracker.
From the top of my head, it may help adding ```/gdi:sw``` as X11 accelerated GDI is not implementing all operations.

**Comment by akallabeth** [comment]
@blexen Read your comment in IRC, but am unable to reproduce. Using libreoffice portable in russian (to get the same drawing routines triggered) but libreoffice UI looks fine.
The other bug with the color issue of deactivated menu entries you pointed out disappears when using ```/gdi:sw```
So here my question: Did you use the remmina version shipped with ubuntu or their ppa?

**Comment by blexen** [comment]
Hello!
I found the problem.
On the windows 2008 server, the color depth is set to 15 bits

Connection via remmina **15 bit** everything is fine
![remmina_15bit](https://user-images.githubusercontent.com/31433202/29862140-5dcaa204-8d74-11e7-906c-c63316913857.jpg)

Connection with **/ bpp: 15**: ` xfreerdp  /u:admin /p:pass /cert-ignore /f /gdi:sw /bpp:15 /v:192.168.1.1
`
![freerdp_15bit](https://user-images.githubusercontent.com/31433202/29861988-dc430cb2-8d73-11e7-9e7f-4395974f3ff4.jpg)


Connection with **/ bpp: 16**: `xfreerdp  /u:admin /p:pass /cert-ignore /f /gdi:sw /bpp:16 /v:192.168.1.1`
![freerdp_16bit](https://user-images.githubusercontent.com/31433202/29861995-e74d07ca-8d73-11e7-9cdf-42ce3ba51478.jpg)

**Comment by akallabeth** [comment]
@blexen Thank you for the analysis, can reproduce it now too.

**Comment by akallabeth** [comment]
@blexen One thing though, which version of remmina are you testing with?

**Comment by blexen** [comment]
Remmina 1.1.2
