### ISSUE TITLE
Disable window decoration does'n work if I change -D to -decoration (xfreerdp/ubuntu)

### ISSUE THREAD

**Issue by vovchok70** [FreeRDP/FreeRDP#4113]
xfreerdp -D -u user -p pass -g 1024x744 server:port
This command works normally - the terminal window hasn't title/border and all the space under linux taskbar is a remote Windows desktop.
(freerdp version 1.1.0-beta1, monitor 1024x768, linux taskbar height 24p.)
But if I changing -D to -decoration (as recommended), or skip this option (because -decoration is ostensibly set by default), I see the terminal window with title/border, that occupy useful screen space and a Windows taskbar can't fit on the screen. 
Does it's look like an error?
How can I disable title/border of the freerdp window without using deprecated command-line interface?

**Comment by vovchok70** [comment]
ps: As it turned out it works fine in freerdp2... And freerdp2 can redirect a local linux printer to the remote windows server - it's really cool!

**Comment by akallabeth** [comment]
@vovchok70 Try the command line help  ;) you have a typo, it should be ```-decorations```

**Comment by vovchok70** [comment]
In the help '-decorations' present, but it not working in freerdp-x11!
In freerdp2-x11 it work fine, but this version of freerdp not present in the ubuntu repository below ubuntu 17.04 (but it possible to install freerdp-nightly version from the official site).

**Comment by akallabeth** [comment]
@vovchok70 Ah, ok, so that was not your problem, good to know. Sorry, looks like I was a bit confused by the description. If it is fixed in freerdp2 that is good to know, so leaving this closed.
