### ISSUE TITLE
Unparsable x terminal password /p

### ISSUE THREAD

**Issue by chutburind** [FreeRDP/FreeRDP#4115]
my command is "xfreerdp +clipboard /u:myusername /p:@xxx^&|xx /v:192.168.2.55 /size:1440x900"

password with the following do not work

![ss](https://image.ibb.co/f1n1ia/Screenshot_from_2017_09_02_11_09_26.png)

**Comment by Tahvok** [comment]
And it shouldn't - it's a bash limitation, not xfreerdp.
Use single quotes around your password: ```/p:'@xxx^&|xx'```

**Comment by akallabeth** [comment]
Not a bug
