### ISSUE TITLE
bgr vs rgb color (regression)

### ISSUE THREAD

**Issue by mpicjohn** [FreeRDP/FreeRDP#4118]
I compiled 2.0.0-dev (git 3b83526) on a Solaris 11.3 (x86). I see inverted colors (red and blue swapped). Seems to be a regression of issue #297 (xfreerdp displays inverted colors).

Any suggestion how to fix that are really appreciated.

Thx

Carsten

**Comment by akallabeth** [comment]
@mpicjohn check ```xf_get_local_color_format``` it seems to detect the wrong local color format in your case.

**Comment by mpicjohn** [comment]
Hi  akallabeth,

thanks for the hint. I could fix the issue by hard coding

DstFormat = PIXEL_FORMAT_RGBX32;

in xf_graphics.c

works for me at the moment. I will try to figure out why DstFormat is not detected correctly when I find some time...

thx

Carsten

**Comment by akallabeth** [comment]
@mpicjohn Glad it works. Would be great to find the autodetection issue with your configuration, so hope to hear from you :)
