### ISSUE TITLE
freerdp reutrned error bio read returned error ssl routines : ssl3_read_bytes:tlsv1 alert access denied 

### ISSUE THREAD

**Issue by umhahahahapu** [FreeRDP/FreeRDP#4124]
I want remoteapp on 
:windows7 enterprise 32bit 

but I can't execute remote app but meet  error..

what is this???

I want to connect windows7 enterprise 32bit remoteapp

and command

./xfreerdp /v : xxx /u: /p: /app:

I can run win10 pro but I can't win7 enterprise 32bit
and I can connect win7 desktop but I can't connect win7 remote app 

please help me....

**Comment by akallabeth** [comment]
Please read https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Your issue is imho better suited for mailing list or IRC
