### ISSUE TITLE
freerdp from android failed because protocol security negotiation win7

### ISSUE THREAD

**Issue by umhahahahapu** [FreeRDP/FreeRDP#4125]
I using freerdp from android to win10pro 
It works well but WIN7 enterprise didn't work..

same app but it didn't work.

error msg is protocol securiy negotiation fail 

How can I connect my win7 from my android freerdp app

**Comment by akallabeth** [comment]
Please read https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Questions like yours are imho better suited for mailing list or IRC,
