### ISSUE TITLE
Server 2012 crashes when multiple computers connect with usb devices using /dvc:urbdrc,dev:046d:082d 

### ISSUE THREAD

**Issue by laughingguffly** [FreeRDP/FreeRDP#4130]
We have 30 machines in the office all running Ubuntu 16.04  and connecting to Windows Server 2012 using xfreerdp 2.0RC

Everything has been working great until the client wanted to connect USB webcams.

I've got the connection strings working along with the permissions for the usb device and everything appears to work great on the RDP session (webcam is recognised and displays images)

Unfortunately when I deployed it I received a BSOD twice on server 2012.

Analysing the minidump. There appears to a problem with tsusbhub.sys experiencing a PNP_DETECTED_FATAL_ERROR due to Duplicate PDO.

Now reading up about this error it appears that windows does not like having 2 devices with the same device id, unique id and then serial number? connected to the same hub.

Unfortunately my knowledge stops a understanding the device id and unique id. I presume windows should be able to cope with multiple devices with the same device id and unique id. I presume what is happening is some how during reconnects from xfreerdp perhaps duplicate PDOs exist on the server and it crashes?

Is there anything I can do with Xfreerdp to get around this?

Here is further analysis of  BSOD:

PNP_DETECTED_FATAL_ERROR (ca)
PnP encountered a severe error, either as a result of a problem in a driver or
a problem in PnP itself.  The first argument describes the nature of the
problem, the second argument is the address of the PDO.  The other arguments
vary depending on argument 1.
Arguments:
Arg1: 0000000000000001, Duplicate PDO
	A specific instance of a driver has enumerated multiple PDOs with
	identical device id and unique ids.
Arg2: ffffe001cf21b240, Newly reported PDO.
Arg3: ffffe001d36f32e0, PDO of which it is a duplicate.
Arg4: 0000000000000000

Debugging Details:
------------------

TRIAGER: Could not open triage file : e:\dump_analysis\program\triage\modclass.ini, error 2

BUGCHECK_STR:  0xCA_1

DEVICE_OBJECT: ffffe001cf21b240

DRIVER_OBJECT: ffffe001cb425760

IMAGE_NAME:  tsusbhub.sys

DEBUG_FLR_IMAGE_TIMESTAMP:  593dc69e

MODULE_NAME: tsusbhub

FAULTING_MODULE: fffff800971cb000 tsusbhub

CUSTOMER_CRASH_COUNT:  1

DEFAULT_BUCKET_ID:  WIN8_DRIVER_FAULT_SERVER

PROCESS_NAME:  System

CURRENT_IRQL:  0

LOCK_ADDRESS:  fffff8011bb56020 -- (!locks fffff8011bb56020)

Resource @ nt!PiEngineLock (0xfffff8011bb56020)    Available

WARNING: SystemResourcesList->Flink chain invalid. Resource may be corrupted, or already deleted.

WARNING: SystemResourcesList->Blink chain invalid. Resource may be corrupted, or already deleted

**Comment by hardening** [comment]
So I guess you have in your hand a CVE targeting 2k12 servers: you can remote crash a whole server by just sending the right packet sequence !

**Comment by laughingguffly** [comment]
So is this a limitation of the server 2012 OS and I should contact Microsoft or will say they the crash is down to an incorrect implementation of the RDP library?

**Comment by bmiklautz** [comment]
@laughingguffly the server shouldn't crash in any circumstances even if the implementation is incorrect or has problems. (Even worse if it is remote).

**Comment by laughingguffly** [comment]
Ok I've reached out to Microsoft.
https://social.technet.microsoft.com/Forums/ie/en-US/cf961173-d704-4efa-83f0-792cae021ee0/bsod-pnpdetectedfatalerror-when-using-usb-redirection-over-rdp?forum=winserver8gen

I'll see what they say..

**Comment by lwahonen** [comment]
Wow, that microsoft support is worse than Dell firstline helpdesk

**Comment by x86** [comment]
Hi folks,

Please install KB4025335 on Windows Server 2012 R2. There's no fix for 2016 yet.

After it, do this:
- Go to the registry location SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations.
- Create a new DWORD value “fUniqueInstanceID” (without quotes ofc.).
- Set the value to “1”.
- Reboot after setting this registry.

:-)

**Comment by hardening** [comment]
From what I've read in the thread it seems like the crash is related to your AVG antivirus...

**Comment by akallabeth** [comment]
So, is this really a FreeRDP bug or can it be closed?

**Comment by laughingguffly** [comment]
I can confirm that is was a bug with Windows Server and NOT freerdp.

Implementing x86s comments fixed the issue for us.

**Comment by akallabeth** [comment]
@laughingguffly Thanks for the clarification.
