### ISSUE TITLE
xfreerdp doesn't work correctly with /bpp:32 on X11 with 32 depth 

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#4134]
Wallpaper/background color is not shown (regardless ` /wallpaper`) and the window is transparent instead, there are some other glitches also, see toolbar in the attachment:

![screenshot](https://user-images.githubusercontent.com/1051384/30482339-e74c30d2-9a22-11e7-9ede-feff626f55a5.png)

```
[15:43:05:916] [32126:32127] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_RGBA32
[15:43:05:916] [32126:32127] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGBA32
```

Tested on Fedora rawhide (with X11 `DefaultDepth 32`) with system version and freerdp master. Just `xfreerdp /u:... /p:... /v:... /bpp:32 `, nothing special (/gdi:sw/hw is same). Tested against Windows 7 server.

**Comment by akallabeth** [comment]
@ondrejholy oh, real transparency :) Does this issue disappear when using ```PIXEL_FORMAT_RGBX32``` as local framebuffer format?

**Comment by hardening** [comment]
Yeah, I guess most of us would not complain about full transparency working so well :)

**Comment by ondrejholy** [comment]
@akallabeth If I recall correctly, it didn't help, but I will try again for sure...

**Comment by ondrejholy** [comment]
Nope, it doesn't help...
```
[09:13:54:329] [8773:8774] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[09:13:54:329] [8773:8774] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
```

**Comment by akallabeth** [comment]
@ondrejholy Sorry for the delay. Wanted to ask if you could also try other formats (```PIXEL_FORMAT_ARGB32```, ```PIXEL_FORMAT_XRGB32``` et al)

**Comment by ondrejholy** [comment]
So, I've tried all 32 bpp color formats from color.h for sure. Same situation for all of them except the unwanted color shifts. However, I've just realized that depth 32 is probably something non-standard. I've tried "DefaultDepth 32" in my xorg.conf and X server refused to start consequently because the driver doesn't support this depth. I used "vncserver -depth 32" for testing in order to avoid rebooting last time. However,  "man vnc" says: "Default is 24.  Other possible values are 8, 15 and 16 - anything else is likely to cause strange behavior by applications." and man xorg.conf says: "Note: depth means the number of bits in a pixel that are actually used to determine the pixel color. 32 is not a valid depth value. Most hardware that uses 32 bits per pixel only uses 24 of them to hold the color information, which means that the color depth is 24, not 32. " But then I am not sure why I see "supported pixmap formats:  ...  depth 32, bits_per_pixel 32, scanline_pad 32" in xdpyinfo output on my system. Maybe the if-clause for 32 is redundant in xf_get_local_color_format and this bug report is bullshit... Isn't here any X11 expert?

**Comment by akallabeth** [comment]
@ondrejholy So, how did you end up with a transparent background then?

**Comment by ondrejholy** [comment]
Thanks to vnc using `vncserver :32 -depth 32 && vncviewer localhost:32` with `gnome-session &` in `~/.vnc/xstartup`.

**Comment by akallabeth** [comment]
@ondrejholy I may be mistaken, but that sounds more like an issue with vncserver

**Comment by ondrejholy** [comment]
Maybe, but other applications seem to work correctly in that mode. I was just trying to test all possible color conversions and was confused by the 32-bit case in xf_get_local_color_format which is probably redundant.  However, let's close this since I am not able to start X server with Depth 32 properly and sorry for the chaos.

**Comment by bmiklautz** [comment]
@ondrejholy what was the test setup? xfreerdp within vncviewer to the local vncserver?

**Comment by ondrejholy** [comment]
@bmiklautz Yes, I tested xfreerdp within vnc session to local vncserver with 32-bit depth so I could test it with 32-bit local framebuffer pixel format and the problem with transparent window appeared only with /bpp:32.
