### ISSUE TITLE
Strange Keyboard Issues - Wrong behavior of some keys,sometimes

### ISSUE THREAD

**Issue by ropetry** [FreeRDP/FreeRDP#4137]
Hello, i have an odd issue with freerdp and keyboard layout. 
We switched from rdesktop to freerdp GIt Version 1dbd2d2 in our new deployment. 

We connect to a Windows Server 2008 R2 Farm and sometimes the Keyboard Layout is different.. 
The Cursor keys left / right doesn´t have a function. Cursor down has the same behavior as enter.. 

I checked Num-Lock and so on. But i can´t get it working by pressing some keys..

If i do a disconnect and connect back again the problem is gone. From 100 Connections i would say the problem only occurse 1-2 times. It is really strange. The sad thing is that i can´t reproduce it.. it´s really random..
As it appears also with an initial connetion the problem can´t be a sync problem with a redirected session i would guess.

Has someone seen this behavior in the past ? I could try to enable debug mode on all Clients but i thing i will have more problems / performance Issues than before ? 
Is there a way to get better diag/debug data for this special case ? 

we use freerdp with the following paramaters on all of our thinclients.
xfreerdp grab-keyboard +compression /cert-ignore +nego /sec:rdp +clipboard +bitmap-cache +fonts +heartbeat /disp /echo +auto-reconnect /frame-ack:4 /max-loop-time:1000 /rfx /v:ServerName

Buildoptiosn as follows:
This is FreeRDP version 2.0.0-dev (git 1dbd2d2)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1
HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=
HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1
 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1
WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF
WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF
WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF
WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF
WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF
WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF
WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1
WITH_FFMPEG=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=OFF WITH_IPP=OFF WITH_JPEG=OFF
WITH_KRB5=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON
WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON
WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1
WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF
WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON
WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector
-funwind-tables -fasynchronous-unwind-tables -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations
-fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -msse2
Compiler:            GNU, 4.8.3
Target architecture: x64

Thanks so far for viewing and commenting on this issue 8-)
bye
roman

**Comment by ropetry** [comment]
Some more "wrong" keys are:
Insert print a /
Del has no function
Cursor down makes a CR/LF 
8-)
bye
roman

**Comment by T3N4K4** [comment]
@ropetry I don't know if this is relevant for freerdp, but have you tried evdev or are you using evdev?

**Comment by ropetry** [comment]
@T3N4K4 Thanks for this info. But no special driver / tool or special Keyboard is used..

**Comment by ropetry** [comment]
Hello again. Still investigating at this issue. But i need some advice.

If i enable only the debug_keyboard option at compiling time, should there be much overhead ?
Or what´s the best way now with the new dubug system?
WLOG_LEVEL=DEBUG  ? It will debug everything ? or can i limit it to keyboard ?
thanks
bye
roman

**Comment by T3N4K4** [comment]
@ropetry there are those two options / command line flags now:
```
/log-level:[OFF|FATAL|ERROR|WARN|INFO|DEBUG|TRACE]	Set the default log level, see wLog(7) for details
/log-filters:<logger tag>:<log level>[, <logger tag>:<log level>][, ...]]	Set logger filters, see wLog(7) for details
```
But I think you have to compile with WITH_DEBUG_KBD=ON

**Comment by bmiklautz** [comment]
@ropetry when the problem occurs did you check if the server side layout is set correct?

**Comment by ropetry** [comment]
@bmiklautz Thanks for asking. yes, we checked the layout and it still says german so it looks o.k but the keyboard layout is broken.
![grafik](https://user-images.githubusercontent.com/2862409/30914037-82888438-a392-11e7-8a97-9a550c7b05b8.png)

**Comment by ropetry** [comment]
Hello and back again. Just to get this up again 8-).. 
We still have those strange layout problems in the meantime we did a new build with latest GIT Version but it doesn´t help
Latest commit was..
commit 3c45a6089adc75a1545062960ec3e2d6c43a7a19
Merge: 30ed6aa 91280b3
Author: Bernhard Miklautz <bmiklautz@users.noreply.github.com>
Date:   Wed Jan 17 19:31:29 2018 +0100

    Merge pull request #4367 from akallabeth/android_version_next

So i would like to start again the debug.

**Comment by bmiklautz** [comment]
@ropetry what is the local keyboard set to?
```
setxkbmap -print
```

**Comment by ropetry** [comment]
Hello @bmiklautz 
thanks for answering 8-)..
xkb_keymap {
        xkb_keycodes  { include "evdev+aliases(qwertz)" };
        xkb_types     { include "complete"      };
        xkb_compat    { include "complete"      };
        xkb_symbols   { include "pc+de+inet(evdev)+terminate(ctrl_alt_bksp)"    };
        xkb_geometry  { include "pc(pc105)"     };
};

**Comment by bmiklautz** [comment]
@ropetry I tested with the same local and remote layout but couldn't reproduce this issue. If you built yourself did you build with libxkbfile? If you on any system we do have pre-builds for (https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds) I would suggest to give them a try and see if it also happens.

**Comment by ropetry** [comment]
@bmiklautz : i even can´t reproduce it here..100 starts, 3-4 fails..
 we did the test with an own build . cmake settings was, without special libxkbfile settings.
`cmake \
        -DCMAKE_C_FLAGS="$RPM_OPT_FLAGS" \
        -DCMAKE_INSTALL_PREFIX=/opt/freerdp \
        -DCMAKE_SKIP_INSTALL_RPATH=ON \
        -DSTATIC_CHANNELS=OFF \
        -DWITH_ALSA=OFF \
        -DWITH_FFMPEG=OFF \
        -DWITH_GSTREAMER_0_10=ON \
        -DWITH_GSTREAMER_1_0=OFF \
        -DWITH_PULSE=ON \
        -DWITH_SSE2=ON \
`

today we start completly new with an original opensuse tumbleweel rpm with this spec file..
Specfile settings -->
[https://build.opensuse.org/package/view_file/X11:RemoteDesktop/freerdp/freerdp.spec?expand=1]

tihs has settings active for keyboard.. hope this solves it.. it´s rc1 based.
i hope this will solve it now..

**Comment by samoring** [comment]
OS: opensuse 15.0.  The letter "c" stops working after a bit of use, the letter "a" get's changed to an "a-grave" eg., " à "...

Using "freerdp-2.0.0~rc4-lp150.2.3.1.x86_64"

Not sure how I'd go about doing diagnostic gathering, anyone have any suggestions?  Does this give some more clues?

**Comment by ropetry** [comment]
we fixed our Keyboard Problems by using the -k Option to set a specific Keyboard layout...
if i remember correctly..
bye
roman

**Comment by samoring** [comment]
Roman,
On Thu, 2019-04-04 at 02:54 -0700, ropetry wrote:
> we fixed our Keyboard Problems by using the -k Option to set a
> specific Keyboard layout...
> 
> if i remember correctly..
> 
> bye
> 
> roman
> 
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

Thinking one of these?
 /kbd:0xid or name           Keyboard layout
       /kbd-fn-key:value           Function key value
       /kbd-list           List keyboard layouts
       /kbd-subtype:id           Keyboard subtype
       /kbd-type:id           Keyboard type
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c
> 55493e4bb","name":"GitHub"},"entity":{"external_key":"github/FreeRDP
> /FreeRDP","title":"FreeRDP/FreeRDP","subtitle":"GitHub
> repository","main_image_url":"https://github.githubassets.com/images
> /email/message_cards/header.png","avatar_image_url":"https://github.
> githubassets.com/images/email/message_cards/avatar.png","action":{"n
> ame":"Open in GitHub","url":"https://github.com/FreeRDP/FreeRDP"}},"
> updates":{"snippets":[{"icon":"PERSON","message":"@ropetry in #4137:
> we fixed our Keyboard Problems by using the -k Option to set a
> specific Keyboard layout...\r\nif i remember
> correctly..\r\nbye\r\nroman"}],"action":{"name":"View Issue","url":"
> https://github.com/FreeRDP/FreeRDP/issues/4137#issuecomment-47983145
> 0"}}}
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "https://github.com/FreeRDP/FreeRDP/issues/4137#issuecomme
> nt-479831450",
> "url": "https://github.com/FreeRDP/FreeRDP/issues/4137#issuecomment-
> 479831450",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]

**Comment by ropetry** [comment]
i think we used  
/kbd:0xid or name           Keyboard layout
with the right number..
