### ISSUE TITLE
When inserting a udisk, freerdp triggers the keyboard F5 event

### ISSUE THREAD

**Issue by earcg** [FreeRDP/FreeRDP#4149]
freerdp Version : https://github.com/FreeRDP/FreeRDP
Command line : xfreerdp -f /rfx /size:1920x1080 /drive:usb,/mnt/udisk/ /u:xx /p:x /v:xxx.xxx.x.x:3389 /bpp:16 /vc:rdpsnd,sys:alsa,dev:default,rate:44100,channel:2

When inserting a udisk, freerdp triggers the keyboard F5 event。
In the state of the F5 event that does not affect the keyboard, How to disable this event?

**Comment by akallabeth** [comment]
@earcg What do you mean 'triggers the keyboard F5 event'? I highly doubt that FreeRDP does syntesize keyboard events when changing disks, do you mean that some automount procedure is triggered by the os?

**Comment by earcg** [comment]
@akallabeth  		
xf_evnet.c
BOOL xf_event_process(freerdp* instance, XEvent* event)
case KeyPress:
			status = xf_event_KeyPress(xfc, event, xfc->remote_app);

When inserting a udisk,the event->xkey.keycode 's value is 71.The webpage that I originally opened or the application is refreshed.

**Comment by akallabeth** [comment]
@earcg That function is called from X11, so your wm/system is generating the event when inserting something. FreeRDP is just forwarding that.

**Comment by earcg** [comment]
@akallabeth Thanks,

**Comment by akallabeth** [comment]
@earcg You're welcome. I'll close this issue, reopen or create new ones if required.
