### ISSUE TITLE
[ERROR][com.freerdp.client.x11] - failed to open display: :0.0

### ISSUE THREAD

**Issue by Cenzor** [FreeRDP/FreeRDP#4158]
Hi. I connected to a server over ssh, when i execute in terminal "xfreerdp" appears  the error:

[ERROR][com.freerdp.client.x11] - failed to open display: :0.0
[ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.

Patator using the xfreerdp and when i execute "./patator.py ......", by itself, the error appears again.

i connected to win/linux and etc.
freerdp version - when i run "xfreerdp --version", the error appears again, i download latest version 28/09/2017.
Linux linux 2.6.32-042stab120.6,  x86_64 GNU/Linux, Debian GNU/Linux 7.8 (wheezy)

Please, help me.

**Comment by akallabeth** [comment]
@Cenzor Well, you're executing an X11 application without X11 forwarding then?
Please ask questions such as these on the mailing list or IRC.

**Comment by Likid77** [comment]
I had this problem when running xfreerdp as root (under Kali Linux).
when running as normal user (without or without sudo), it works perfectly.

**Comment by jedai47** [comment]
interesting, any way to make it work with the root account ?
