### ISSUE TITLE
Unable to compile and install FreeRDP on Centos 7 : Warnings and freerdp plugings are not installed.

### ISSUE THREAD

**Issue by coolkingh** [FreeRDP/FreeRDP#4168]
Warnings after running this command  cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .

> CMake Warning at client/X11/CMakeLists.txt:92 (message):
>   GAD_LIBS: freerdp-client;winpr-utils;freerdp-core;freerdp-utils

>  CMake Warning (dev) in client/common/CMakeLists.txt:
>   Policy CMP0022 is not set: INTERFACE_LINK_LIBRARIES defines the link
>   interface.  Run "cmake --help-policy CMP0022" for policy details.  Use the
>   cmake_policy command to set the policy and suppress this warning.

After install and make install  these plugins are not installed in any of the directories.

>  cliprdr.so  disk.so  drdynvc.so  printer.so  rail.so  rdpdbg.so  rdpdr.so  rdpsnd_alsa.so  rdpsnd.so

Please look into it and help to resolve the issue.

**Comment by akallabeth** [comment]
Please read https://github.com/FreeRDP/FreeRDP/wiki/BugReporting and add the missing pieces or better, ask on the mailing list/IRC.
