### ISSUE TITLE
Crash app in Multi-Window mode

### ISSUE THREAD

**Issue by aleksei-klv** [FreeRDP/FreeRDP#4169]
Bug in Multi-Window mode (since Android N). Tested on Samsung Galaxy S8 and Note 8. 
- start the app and open new session
- open Multi-Window mode: tap overview button (task switch), then long tap on title of the app to activate the mode
- close window by cross

![screenshot_20171009-112421](https://user-images.githubusercontent.com/28042554/31330157-dcd72424-ace5-11e7-937e-c40e91aa4788.jpg)
![screenshot_20171009-112605](https://user-images.githubusercontent.com/28042554/31330173-ea9a62b0-ace5-11e7-8e0c-2b0c946eb37a.jpg)

**Comment by akallabeth** [comment]
Should be fixed with #4179, could you confirm?

**Comment by akallabeth** [comment]
Reopen if still an issue.
