### ISSUE TITLE
date/time incorrect by some minutes in shared \\tsclient files

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#4173]
See remmina issue [#1310](https://github.com/FreeRDP/Remmina/issues/1310)

I'm connecting to Windows 10 or 2008 server with
```xfreerdp /v:192.168.156.2 /u:giovanni /d:mydom /drive:doc,/home/giovanni/Documenti```
All files on \\tsclient\doc at the windows side have last modification time different than under the linux client by some minutes.
Example: under windows
![immagine](https://user-images.githubusercontent.com/5477803/31456679-cc04fb86-aeba-11e7-9385-d725bbcbc912.png)
and under linux
```
giovanni@uno:~/Documenti$ LANGUAGE=C stat "Stemma Messico.odg" 
  File: 'Stemma Messico.odg'
  Size: 380137    	Blocks: 744        IO Block: 4096   regular file
Device: 802h/2050d	Inode: 923445      Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/giovanni)   Gid: ( 1000/giovanni)
Access: 2017-10-11 19:15:56.610503469 +0200
Modify: 2017-04-23 14:10:48.576056344 +0200
Change: 2017-04-23 14:10:48.576056344 +0200
 Birth: -
Creazione: -
```
As you can see, there are a bit more than 4 minutes from "Modify:" and "Ultima modifica" (last modification).
Some files have six or seven minutes of difference.

**Comment by akallabeth** [comment]
@giox069 The issue you link to references FreeRDP 1.1, correct? Does this also apply for the current master (upcoming 2.0)?

**Comment by giox069** [comment]
I don't think that remmina 1.2.0-rcgit.20 can work with libfreerdp before 2.0... so the user has both installed (remmina->libfreerdp2 xfreerdp->libfreerdp1). But my tests were done with your master branch. Ok, now I can see a fix, I will test it as soon as I can.

**Comment by giox069** [comment]
It works (tested on master branch)!
Thank you vey much @akallabeth :+1: :+1:

**Comment by cnzhx** [comment]
@akallabeth Thank you very much. I installed a packaged FreeRDP stating with "#4175 Fixed file timestamps" [built 4 days ago](https://build.opensuse.org/package/show/home%3Ahendwolt/freerdp) from software.opensuse.org in my openSUSE Tumbleweed box and it worked very well.
