### ISSUE TITLE
Blank screen after login. 

### ISSUE THREAD

**Issue by AngelNor** [FreeRDP/FreeRDP#4178]
I am trying to login to a remote desktop for work, but over the weekend, when trying to login to server it just comes up with a blank screen and doesn't show any icons. This is on both the LG G6 and Tab S3. Up until this point, it was working. This is not my server, it is for work and they do not have any answers for me. I need this to put in my notes, any help would be appreciated.

**Comment by akallabeth** [comment]
Without further information not much can be done. (aka we don't know your setup, options, OS)
In the future, please use the mailing list or IRC for support questions.
