### ISSUE TITLE
Mouse cursor does not accept click in Remote Desktop

### ISSUE THREAD

**Issue by whande1992** [FreeRDP/FreeRDP#4180]
When I use particular application in remote desktop some actions cause the mouse cursor no longer accept any click, I can move it but I can not click on any window, either within the Remote Desktop and even in my station, I can only use through the keyboard, and close the Remote Desktop window everything back to normal.

My PC: Ubuntu Mate
Server: Windows 2008 R2

**Comment by akallabeth** [comment]
Duplicate #2363
