### ISSUE TITLE
FreeRDP2-X11 spoiled a date/time while copying files/folders into the home-drive.

### ISSUE THREAD

**Issue by vovchok70** [FreeRDP/FreeRDP#4181]
I checked Ubuntu17.04 (32&64bit), freerdp2-x11 git2016113 (from repository) with win7/win10 terminal.
For example the file with the date/time 2017-10-14 13:48:08 has become 2011-09-03 10:48:40. And it so in all cases while a files copying by Windows Explorer to a Linux homedrive!

ps: Maybe anybody knows - how to make the win7explorer hide the files/folders with a dot first on the linux home-drive? (as win10explorer does it)

**Comment by akallabeth** [comment]
@vovchok70 This is a known issue and has been fixed upstream some time ago. Could you try our nightly builds https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds and check if it is correct with them?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.

**Comment by vovchok70** [comment]
Yes - the new version work fine. But why this new version of the freerdp2-x11 so long time not present on Ubuntu repository instead the old version with this error?

**Comment by akallabeth** [comment]
@vovchok70 The packaging is up to ubuntu. Open a issue in their tracker for getting things packaged, don't know their current rules on that.
