### ISSUE TITLE
Add code 0xC0000224 - password must be changed

### ISSUE THREAD

**Issue by duhow** [FreeRDP/FreeRDP#4182]
When trying to login into server with NLA, with the user flag "user must change password on next logon", FreeRDP gives this error with Unknown class:

```
[11:07:38:212] [7721:7722] [ERROR][com.freerdp.core.nla] - SPNEGO failed with NTSTATUS: 0xC0000224
[11:07:38:212] [7721:7722] [ERROR][com.freerdp.core] - freerdp_set_last_error Unknown error class [0xC0000224]
```

0xC0000224 | STATUS_PASSWORD_MUST_CHANGE | 1. User has the “user must change password at next logon flag set. Time to change your password! 2. Active Directory Replication may not be complete

Using version 2.0.0-dev (git e6d66d9d8)

**Comment by bmiklautz** [comment]
@duhow Thanks for the report. Could you add a the reference where you have the code from?

**Comment by duhow** [comment]
https://blogs.technet.microsoft.com/askpfeplat/2013/01/28/quick-reference-troubleshooting-netlogon-error-codes/#_Toc345694552

**Comment by duhow** [comment]
As I see in `include/freerdp/error.h` the code used is:
```
#define ERRCONNECT_PASSWORD_EXPIRED                                     0x0000000E
```

Also, in file `winpr/include/winpr/nt.h` the line is commented, not sure if this is the issue?
```
#define STATUS_PASSWORD_MUST_CHANGE                                     ((NTSTATUS)0xC0000224L)
............
//#define STATUS_PASSWORD_MUST_CHANGE                                   ((NTSTATUS)0xC0000224)
```
