### ISSUE TITLE
when I using xfreerdp remoteapp, size option or w, h option not working 

### ISSUE THREAD

**Issue by umhahahahapu** [FreeRDP/FreeRDP#4184]
I used xfreerdp remoteapp but I want set size 
so I command line /w:100 , /h:100 , or /smart-sizing 100 x 100,
but I thinked that this command not worked.

My com ubuntu 16.04 LTS, 
And I debug my code but code is normal.

Is it right ?

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
please ask on the mailing list or irc.
