### ISSUE TITLE
key repeat not working

### ISSUE THREAD

**Issue by urielz** [FreeRDP/FreeRDP#4188]
I searched for this issue but couldn't find anything. When a key is hold pressed no key repetition is shown on the screen. Is this the expected default behavior?

I'm using freerdp version 1.1.0-beta1 via macports to connect to a windows 10 machine with these arguments:

_/opt/local/bin/xfreerdp /v:srv /u:usr /p:pwd /f +clipboard_

Any help appreciated. Thanks.

**Comment by akallabeth** [comment]
Key repeat is a feature of the server os, so nothing we can support here.

**Comment by urielz** [comment]
Thanks for the reply
