### ISSUE TITLE
Wrong title encoding

### ISSUE THREAD

**Issue by sergeyadppd** [FreeRDP/FreeRDP#4191]
![2017-10-18 13-14-47](https://user-images.githubusercontent.com/32869000/31707808-c39db2ac-b406-11e7-895c-697dd65e0fcd.png)
Sorry for my english. Help please with the header of the box. need a Russian text, and I get what's on the screenshot.

**Comment by dreamadv** [comment]
https://github.com/FreeRDP/FreeRDP/pull/4197

**Comment by akallabeth** [comment]
@sergeyadppd Should be fixed with #4206 , could you please confirm?

**Comment by akallabeth** [comment]
Seems to be fixed, reopen if still an issue.
