### ISSUE TITLE
/multimonitor in fullscreen seems to be broken

### ISSUE THREAD

**Issue by marknow22** [FreeRDP/FreeRDP#4192]
Hi,
since yesterday /multimon does not work any longer in fullscreen. It just uses one of my monitors. My system is Ubuntu Xenial with nvidia drivers

I have used

`xfreerdp /t:$Title /multimon /toggle-fullscreen /d:$Domain /u:$Username /p:$Password /f /cert-ignore /wallpaper /v:$Server /log-level:DEBUG`

in my shell script.

It toggles fullscreen but just on one monitor, using CTRL+ALT+ENTER does show that the client has connected with all three monitors.

The only thing I have changed, is to change drivers from nvidia-340 to nvidia-375, however reverting to nvidia-340 does not help.

I attach what has been dumped to my console, however I do not see anything related to /multimon.

I have used FreeRDP version 2.0.0-dev and have now installed the nightly from here:

https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=xenial,label=pkg-deb/

`freerdp-nightly_2.0.0+0~20171018014844.433~1.gbp16d910_amd64.deb`

Kind regards
Markus

[xfreerdp.log](https://github.com/FreeRDP/FreeRDP/files/1394081/xfreerdp.log)

**Comment by akallabeth** [comment]
There has been the pull requests #4187 merged. The primary monitor should now be correctly detected (next nightlies will include that fix)

**Comment by marknow22** [comment]
Just downloaded the source (master), compiled and installed 2.0.0-dev (5189814)

[xfreerdp.log](https://github.com/FreeRDP/FreeRDP/files/1457759/xfreerdp.log)

UNfortunately, still no multimonitor in fullscreen across all three screens.

Kind regards
Markus

**Comment by hardening** [comment]
@marknow22 Just curious aren't you using one of these funky WM that have broken full screen support ?

**Comment by marknow22** [comment]
Hi, I am using a Windows 8.1 machine and a Windows Server 2012

**Comment by hardening** [comment]
@marknow22 by WM I was meaning your window manager (or DE, Desktop environment), from your previous comment I guess w8 and wk12 are the host you're connecting to ?

**Comment by marknow22** [comment]
Ah, okey. I thought WM is for WIndows Machines. Mea Culpa! As window manager I am using LXDE and when I try to connect to w8 AND to wk12, i am receiving both errors. Do you need my X11 log as well?

**Comment by akallabeth** [comment]
Looks like it is #2707 then, closing this as duplicate.
