### ISSUE TITLE
Time(de)synchonisation

### ISSUE THREAD

**Issue by vdhorsttom** [FreeRDP/FreeRDP#4193]
We have a problem with the time...
When I log in to our remote server with FreeRDP (1.1.0-beta1) is sets the time back, 1 hour.
But keeps the correct timezone.

The time on the client is correct, also the correct time zone.
We have time synchronization on, this because some of our users work in different time zones.

A Strange thing is when I use the FreeRDP from the master, there is no problem with the time...

Info:
Client: Lubuntu 16.04.3 LTS 64Bit
FreeRDP: 1.1.0-beta1
Server: Windows Server 2008 R2

_Edit: spelling_

**Comment by vdhorsttom** [comment]
Looks like it has problems with Daylight Saving Time... I guess when it turn back/off it will be correct... But that isn't a solution...

**Comment by akallabeth** [comment]
@vdhorsttom Try our nightly builds, they receive timezone updates on a regular basis. We don't do backports ourselves, so maybe the package you're using did not receive these.

**Comment by vdhorsttom** [comment]
@akallabeth I have installed it but does not seem to work... When I try xfreerdp -version, freerdp -version or freerdp-nightly -version, I says that the command is not found.

**Comment by akallabeth** [comment]
@vdhorsttom The binaries are installed under ```/opt/freerdp-nightly/bin```, which is (most likely) not in your path. You need to call it with absolute path.

**Comment by vdhorsttom** [comment]
@akallabeth Ahh I see... But now I have the strange graphical glitch that I also have with the Master and stable 1.0, some of the text is in bold text. Mostly the right click options.

**Comment by akallabeth** [comment]
@vdhorsttom So the time zone stuff is fixed? As for the rest, command line? Anyhow, ```/gdi:sw``` is most likely the solution for your issues, if you use legacy GDI operations.

**Comment by vdhorsttom** [comment]
@akallabeth Indeed, the time is correct! Thanks! But not everything is okay,
![img_20171019_124447](https://user-images.githubusercontent.com/31983843/31767477-89515520-b4cb-11e7-9c8d-9dbe0487ccdd.jpg)
 I also see, when I open Office Word, it gives the document more grayish look and only the line I write is the normal white color...

**Comment by akallabeth** [comment]
Ok, closing this issue then. As for the other stuff, please use IRC or mailing list for that. (command line appreciated, otherwise it could be many reasons)
