### ISSUE TITLE
Length of filename or path problem

### ISSUE THREAD

**Issue by cnzhx** [FreeRDP/FreeRDP#4199]
Hi there,

I mount a local folder in Linux remotely to a Windows 7 desktop. And I notice that the length of a file in the folder has a limit of 130 characters on the remote Windows 7 desktop. It is the same whether the file is put into sub-folder or not. 

So my question is "Is this designed on purpose?"

When I use a very long file name for the testing file, such as `abcdefghijklmnopqrstuvwxyzAabcdefghijklmnopqrstuvwxyzBabcdefghijklmnopqrstuvwxyzCabcdefghijklmnopqrstuvwxyzDabcdefghijklmnopqrstuvwxyzE.txt`, which has 140 characters including the extension, it shows only up to `Dabcdefghijklmnopqrstuv` (totally 130 characters) with the rest `wxyzE.txt` being trimmed out. If I put this file in a sub-folder named `test`, its name is still trimmed to that same position.

If I use this 140 characters with `.txt` removed (136 then) to name a directory and put the 140-character-named file into that folder, then on the remote Windows 7, the folder is shown with name `abcdefghijklmnopqrstuvwxyzAabcdefghijklmnopqrstuvwxyzBabcdefghijklmnopqrstuvwxyzCabcdefghijklmnopqrstuvwxyzDabcdefghijklmnopqrstuv` (130 characters). And no file in that folder (I think it is because this folder is treated as new folder other than the long name one).

Thanks a lot!

**Comment by akallabeth** [comment]
@cnzhx Would be interesting to know the version of FreeRDP you're using since there have been many changes to the drive channel recently. Anyway, support questions are better suited for the mailing list or IRC.

**Comment by cnzhx** [comment]
Sorry I forgot to include the version detail. But I think this is a bug considering the supported filename length is 260 characters.

I am using a package for openSUSE Tumbleweed built from git source. The version is 2.0.0-dev (86bb1e07a).

After being updated to the version built from git on 20171030 which indicates version 2.0.0-dev (86bb1e07a), freerdp still sees this issue.

Sorry to bother if this is not a bug. Anyway, it has no severe impact given the normal usage scenario.

**Comment by akallabeth** [comment]
@cnzhx Sorry, that was too fast on my side, looks like a valid issue still occurring.

**Comment by akallabeth** [comment]
@cnzhx Ok, found the culprit, should be merged within the next couple of days and then available via nightly builds.

**Comment by cnzhx** [comment]
@akallabeth You are amazingly quick! Thank you for dealing with it.

BTW, I do not understand what you said about "too fast on my side". But I guess it does not matter any more, does it?

**Comment by akallabeth** [comment]
@cnzhx Sorry, my english is not always the best ;) I meant I was too quick in closing this issue, although it affected the current master

**Comment by cnzhx** [comment]
@akallabeth My English is not good so I asked :-) And I do not know programming too much. I am not familiar with the workflow or convention of dealing with such kind of communications.

Thank you again for the fix 👍
