### ISSUE TITLE
NLA Authentication error handling broken

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#4209]
Since https://github.com/FreeRDP/FreeRDP/commit/367bddd7adbb2f93f8ceca72d83e0281a30aaf5d error handling for NLA is pretty much broken. The problem is that instead of just passing on the NLA error code to `freerdp_set_last_error`, the generic `FREERDP_ERROR_CONNECT_FAILED` is now used in most cases (all errors except for password must change, password expired and account disabled).

This presents a huge problem because it makes it impossible to differentiate between authentication errors (except for the few handled in the switch statement) and, say, a more generic failure like the remote host couldn't be resolved.

In the connection result handler of my FreeRDP implementation I have the following code (which now doesn't work anymore):

```
if (conErrorCode == 0 &&
    result != 0 &&
    lastErrorCode != 0) {
    if (lastErrorCode == STATUS_LOGON_FAILURE) {
        conErrorCode = STATUS_LOGON_FAILURE;
    } else if (lastErrorCode == STATUS_WRONG_PASSWORD) {
        conErrorCode = STATUS_WRONG_PASSWORD;
    } else if (lastErrorCode == STATUS_PASSWORD_EXPIRED) {
        conErrorCode = STATUS_PASSWORD_EXPIRED;
    } else if (lastErrorCode == STATUS_PASSWORD_MUST_CHANGE) {
        conErrorCode = STATUS_PASSWORD_MUST_CHANGE;
    } else if (lastErrorCode == STATUS_ACCESS_DENIED) {
        conErrorCode = STATUS_ACCESS_DENIED;
    } else if (lastErrorCode == STATUS_ACCOUNT_DISABLED) {
        conErrorCode = STATUS_ACCOUNT_DISABLED;
    } else if (lastErrorCode == STATUS_ACCOUNT_RESTRICTION) {
        conErrorCode = STATUS_ACCOUNT_RESTRICTION;
    } else if (lastErrorCode == STATUS_ACCOUNT_LOCKED_OUT) {
        conErrorCode = STATUS_ACCOUNT_LOCKED_OUT;
    } else if (lastErrorCode == STATUS_ACCOUNT_EXPIRED) {
        conErrorCode = STATUS_ACCOUNT_EXPIRED;
    } else if (lastErrorCode == STATUS_LOGON_TYPE_NOT_GRANTED) {
        conErrorCode = STATUS_LOGON_TYPE_NOT_GRANTED;
    } else if (lastErrorCode == ERRCONNECT_CONNECT_TRANSPORT_FAILED) {
        conErrorCode = ERRCONNECT_CONNECT_TRANSPORT_FAILED;
    }
}
```

So this catches a lot more cases. And most importantly, it lets me identify any kind of authentication error because of `STATUS_LOGON_FAILURE` which in turn makes it possible to present the user with an appropriate dialog, i.e. for selecting alternative credentials.

Please re-evaluate the error handling changes in https://github.com/FreeRDP/FreeRDP/commit/367bddd7adbb2f93f8ceca72d83e0281a30aaf5d as right now, this is actually making matters worse in most cases than being an improvement.

**Comment by akallabeth** [comment]
@lemonmojo The issue with the error handling previously was that two different kinds of error codes were passed on to ```freerdp_set_last_error``` which did collide under certain conditions.
So, no restoring the previous state is not really an option, but extending the mapping (and maybe add some way to access the ```raw NTSTATUS``` code) would be possible.

**Comment by lemonmojo** [comment]
@akallabeth I'm fine with the changes in https://github.com/FreeRDP/FreeRDP/pull/4210.

However, I'd still like to see some improvements in this area. Right now, if an NLA error occurs that is not caught by the switch statement in [nla.c](https://github.com/akallabeth/FreeRDP/blob/7a73a0eb1b85d2e58402c45481058de013f68c43/libfreerdp/core/nla.c#L1627), the generic `FREERDP_ERROR_CONNECT_FAILED` is used instead. So in this case, implementations of FreeRDP can't tell the difference between an unknown authentication error and a more generic connection error.

**Comment by akallabeth** [comment]
@lemonmojo Would suggest to add missing mappings just like with this pull directly to the core library.
If you really need direct access to the NTSTATUS code we need a different function to retrieve that for NLA authentication only (which may be a good idea for future versions)

**Comment by lemonmojo** [comment]
@akallabeth I don't need direct access to the NTSTATUS code but I'd like to be able to differentiate between an authentication/NLA error (even if we're missing a mapping for the specific error) and a general connection error. Basically what I'd like to see is to change [this](https://github.com/akallabeth/FreeRDP/blob/7a73a0eb1b85d2e58402c45481058de013f68c43/libfreerdp/core/nla.c#L1671) to return something like `FREERDP_ERROR_CONNECT_AUTHENTICATION_FAILED`.

**Comment by akallabeth** [comment]
@lemonmojo Ah, well that sounds reasonable. Time to create a pull?

**Comment by akallabeth** [comment]
@lemonmojo Ok, changed the return. Hope that is what you were asking?
Reopen if still an issue.

**Comment by lemonmojo** [comment]
@akallabeth That's exactly what I was looking for. Thx!
