### ISSUE TITLE
New RC overdue

### ISSUE THREAD

**Issue by joakim-tjernlund** [FreeRDP/FreeRDP#4213]
Seems like FreeRDP could use a new RC since there has been quite alot of changes since
the last one.

**Comment by joakim-tjernlund** [comment]
That list seems to be a mess, stuff from 2014, IPV6 support etc are blockers

**Comment by akallabeth** [comment]
@joakim-tjernlund There are old issues in there that need to be confirmed fixed (which requires testing), sure.
IPv6 related fixes are currently targeted at the release after this one.

**Comment by joakim-tjernlund** [comment]
@akallabeth Since rc1 is way improved over rc0 I think you should defer everything to rc2
and put out a rc1 now. Only way to get some better/more feedback what has improved/regressed with
high confidence.

**Comment by ccpp** [comment]
@akallabeth Can #4242 be added to rc1 milestone, so that the new version can be actually released on F-Droid?

**Comment by akallabeth** [comment]
bugs have been fixed and wait for review/merge.
