### ISSUE TITLE
citrix receiver does not support selected encryption

### ISSUE THREAD

**Issue by gilbertrebeiro** [FreeRDP/FreeRDP#4216]
Hi - I have a ubuntu  16.04 and freerdp 1.1 - 
I have 2 users on this system - when we use freerdp to connect to a windows 8.1 system all is perfect from both accounts for general use
 when we try and launch the citrix remote desktop from one account we get an error   the version of citrix receiver does not support selected encryption. Please contact your administrator [Error 1046: The Virtual Driver is not loaded] - when we use the other user account everything works - I am really baffled - any suggestions?

What details would be required to help?

The command line that is used to get to the remote system is:
xfreerdp /v:192.168.123.145  /u:user /d:localdomain.local /f

**Comment by gilbertrebeiro** [comment]
just to be clear

linux user A connects to PC x using:
xfreerdp /v:192.168.123.145 /u:user /d:localdomain.local /f
and successfully launches the citrix RDP no error message

on the same linux box
linux user B connects to PC  X using
xfreerdp /v:192.168.123.145 /u:user /d:localdomain.local /f
and get's 
 the version of citrix receiver does not support selected encryption. Please contact your administrator [Error 1046: The Virtual Driver is not loaded]

**Comment by akallabeth** [comment]
Sure you're not affected by https://discussions.citrix.com/topic/388782-citrix-receiver-does-not-support-selected-encryption/?

**Comment by gilbertrebeiro** [comment]
I'm confused as to how it would work from one user from the same machine with all the same software and it just doesn't work with another linux user.

Does this make sense?
Did you read my entire post?

**Comment by akallabeth** [comment]
@gilbertrebeiro I've read your post. Assuming you're the same as in IRC, try current nightly builds or rdesktop and have a proper cross check. As already mentioned, there is no notion of state that is persistent across sessions (xfreerdp, same arguments used that is) but there are many options on the other end.
