### ISSUE TITLE
Question: How would I go about making this browser based?

### ISSUE THREAD

**Issue by sdyarnell** [FreeRDP/FreeRDP#4217]
Ideally, I would just send a h264 stream across the network and receive it in my browser.

Is this possible with FreeRDP?

**Comment by hardening** [comment]
* This is an issue tracker not a forum. Go on IRC or on the mailing list for such questions;
* smart people try to search (at least a little) before asking;
* RDP has H264 encoding but the general answer is no;

**Comment by sdyarnell** [comment]
Hi David,
I guess thanks for responding? Next time, have some tact in your response. 

- You should update https://sourceforge.net/projects/freerdp/support if this is not the medium for my question, as the following is quoted directly:
"FreeRDP says the best way to get help with its software is by visiting https://github.com/FreeRDP/FreeRDP/issues."

- This second bullet is not helpful. Also, "smart people try" is a direct insult. Again, have some tact. The github issues search doesn't provide an answer. Using google seems to get me lost in nonsense. Searching where? A link to a previous discussion since it seems you can find one by searching just a little would be extremely helpful.

- Thanks for the 3rd bullet. It was at least helpful.

**Comment by hardening** [comment]
- I was not even aware of the sourceforge page, anyway it points you on the FreeRDP wiki which is crystal clear on this subject => https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
- about tact, how do you consider people asking question that could get the answer by taking 15 minutes of __their__ time looking at the code, while it's us that use __our__ time writing an answer ? Yes my answer was rude, anyway being helpful is not something that is due.
