### ISSUE TITLE
dual monitor with different resolution issue

### ISSUE THREAD

**Issue by handrake0724** [FreeRDP/FreeRDP#4221]
hi,

I am running dual monitor. 
main monitor has resolution 1920x1200 and second monitor has resolution 1680x1050.
The setting I use is as follows:
`
xfreerdp /monitors:0,1 /u:<skip> /p:<skip> /bpp:32 +clipboard /gdi:hw /v:60.106.3.129
`

Then, xfreerdp assumes there are two 1920x1200 monitors so the window is cropped in the second monitor. 

Is it not possible that each monitor keeps its own resolution so that any windows fit to each monitor without cropping or trespassing neighbor monitor.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Please ask on the mailing list or IRC
