### ISSUE TITLE
USB scanner redirection

### ISSUE THREAD

**Issue by sudosusudo** [FreeRDP/FreeRDP#4245]
Hello everybody. 
At first I want to say "Thank you!" to developers of FreeRdp for that great product.
At second I want to ask for help, because I can't redirect USB scanner. 

test11@debian:~$ lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 03f0:1705 Hewlett-Packard ScanJet 5590
Bus 001 Device 002: ID 80ee:0021 VirtualBox USB Tablet
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

There is my connection parameters:
/opt/freerdp-nightly/bin/xfreerdp /v:192.168.1.10 /f /bpp:32 /kbd:0x00000419 +menu-anims +window-drag +clipboard +auto-reconnect /gdi:sw +fonts /usb:id,dev:03f0:1705 /u:"test11" /p:"testpass"

I'm trying to connect from Debian 8 to Windows 2008 R2 server, all works fine except scanner forwarding. I can't see any unrecognised devices in Device manager in Windows.

Any suggestion?

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Please use the mailing list or IRC for support questions.
Also try our nightly builds first, distribution packages are often quite old.
