### ISSUE TITLE
Feature Request - Command Line Option to Only Connect if Cert is OK

### ISSUE THREAD

**Issue by adambprotiviti** [FreeRDP/FreeRDP#425]
Right now, if there is an unknown cert, there is a prompt to add it (y/n).

This is problematic for scripting, because freerdp gets stuck here.

I would request that we define a new error level for "Unknown Signer" or something and also a command line option --require-trusted-cert.

If --require-trusted-cert is there, then freerdp should not prompt, and instead just exit with the errorlevel for "Unknown Signer".

... if there are other error conditions I'm not thinking about that would be better error levels, that is fine too.

**Comment by hardening** [comment]
The option switch for this exists now, closing the issue.
