### ISSUE TITLE
Graphical artifacts/mosiac patterns after Nvidia driver update

### ISSUE THREAD

**Issue by gh-user-7392** [FreeRDP/FreeRDP#4250]
Using the latest statically linked release build of FreeRDP and connecting to a W2K12R264 RDS server with a Nvidia K2200 GPU (Driver version 377.48) all is working great. As soon as I update the Nvidia driver version to their newer 385.XX series drivers I get strange mosaic patterns when starting applications up like File Explorer or Symantec Endpoint Protection. I attached a 20 second video showing this issue. I apologize if this is not a FreeRDP problem but I thought the experts here would understand what I am seeing and help. After this strange pattern flashes the application starts and displays normally. It looks to me like the -menu-anims is not working and the ghosting is a result of that. Around the 17/18 second mark in the video this can be seen. When I revert back to the older driver the artifacts disappear. I am not seeing any reports of problems from Nvidia forums and logging on at the console does not present these issues.

Any help would be appreciated.

// command line

/usr/local/freerdp/bin/xfreerdp /u:Administrator /p:******* -menu-anims /size:1300x700 +clipboard /admin /sec:nla /cert-ignore /v:RDS-SERVER

// buildconfig

$ /usr/local/freerdp/bin/xfreerdp /buildconfig
This is FreeRDP version 2.0.0-dev (b5d2578)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -msse2
Compiler:            GNU, 5.4.0
Target architecture: x64

[cut.mp4.zip](https://github.com/FreeRDP/FreeRDP/files/1485969/cut.mp4.zip)

**Comment by akallabeth** [comment]
This seems to be a server side issue, if I'm not mistaken? Or did you upgrade the driver on the machine you're running xfreerdp on?
Anyway, if you add ```/gdi:sw``` you can definitely rule out issues with your local X11 (that does all RDP operations in software only)

**Comment by gh-user-7392** [comment]
@akallabeth you are correct, this is a server side issue as the Nvidia driver update was done on the server. I was just hoping that someone has seen this before and knew what it was. I don't even know what to call this: graphical artifacts, corruption, mosaic, etc. I will close this issue, thanks for trying.

**Comment by gh-user-7392** [comment]
@akallabeth I just wanted to mention that after commit #4349 was applied, I no longer see the mosaic artifacts/patterns as described in the original comment. Thank you very much, I thought it was a Nvidia driver issue. But this fixed it!
