### ISSUE TITLE
Slow usb drive write speed

### ISSUE THREAD

**Issue by teplovdi** [FreeRDP/FreeRDP#4259]
I try to map usb flash with /drive option with command line /drive:flash,/flash when i connect to server 2012R2.
When i write to flash speed is 300kb/sec, when i read from flash speed is 20MB/sec.
I use last version from PPA

**Comment by akallabeth** [comment]
@teplovdi Just for comparison, what are the speeds locally?

**Comment by akallabeth** [comment]
@teplovdi Ok, did some testing against win10 and 2012R2.
Drive performance is ~50MB/sec on my setup in both directions.
Please verify you're not affected by a slow flash card or something like that.

**Comment by akallabeth** [comment]
@ted-gould btw, which PPA are you referring to? We only provide the nightly builds herre https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds
