### ISSUE TITLE
Dynamic Resolution Update for RDP

### ISSUE THREAD

**Issue by GerhardMB** [FreeRDP/FreeRDP#4265]
With pull request 1292 dynamic resolution update was implemented for remmina. I need the same feature for xfreerdp.
My company is willing to pay for this project. Please contact me by email if interested.

**Comment by metalefty** [comment]
ref. https://github.com/FreeRDP/Remmina/pull/1292

**Comment by hardening** [comment]
email sent.

**Comment by GerhardMB** [comment]
We accepted the offer by hardening, this will be done soon.

**Comment by GerhardMB** [comment]
First tests successful!

**Comment by metalefty** [comment]
The issue should be kept open until the feature is merged into master branch.

**Comment by metalefty** [comment]
@akallabeth The feature is not available in master, right?

**Comment by GerhardMB** [comment]
Reopened on request of metalefty until hardening will commit the change @hardening: Please close when done.

**Comment by akallabeth** [comment]
Dynamic resolution support has been merged with #4313 and #4318
