### ISSUE TITLE
[Win8] GFX artifacts

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#4266]
GFX channel with windows 8 server shows artifacts
![bildschirmfoto von 2017-11-22 11-55-29](https://user-images.githubusercontent.com/3472254/33124017-156b2d5e-cf7c-11e7-9380-e209c5eac322.png)

Initial reports and screenshots in #4260

**Comment by gh-user-7392** [comment]
@akallabeth out of curiousity and because I am very interested in the progressive codec results, what was your command line when you noticed this. Do you see this with W2K12R2 server as well? I am really getting great results with CAD right now using the /gfx +gfx-progressive options.

**Comment by akallabeth** [comment]
Only win8 so far, only option was /gfx

**Comment by akallabeth** [comment]
With #5383 we've implemented the most recent version of the GFX spec.
It seems there are some corner cases (e.g. `640x480` with AVC444) which the server side does not handle gracefully, nothing we can do about that.
Therefore closing this as nothing we can fix
