### ISSUE TITLE
USB wacom tablet freeze

### ISSUE THREAD

**Issue by johnsonelectric** [FreeRDP/FreeRDP#4279]
Hello, I am running into an issue with a wacom Bamboo tablet. Host OS is Ubuntu 14.04 x64 using FreeRDP version 1.0.2 to log into a Windows 7 x64 running Macromedia Flash Pro.

The tablet runs fine on the Ubuntu 14.04 host when drawing in GIMP, etc. But when I start drawing in the FreeRDP session to Windows within a few paint strokes Flash starts to become unresponsive and all RDP input freezes.

A few moments later the entire RDP session freezes, and moments after that the keyboard in the Ubuntu 14.04 host also freezes. The mouse still works. If I unplug the tablet the RDP session comes back to normal.

Other than that FreeRDP give me a great RDP session.

to connect I use:

$ xfrerdp -g 1280x800 -u user 192.168.x.x

Any suggestions? Thanks.

**Comment by hardening** [comment]
1.0.2 is so damn old, given your Ubuntu version I guess that your tablet appears as some kind of mouse. Would you mind giving a try with our nightly builds ? (https://github.com/FreeRDP/FreeRDP/wiki/Prebuilds)

**Comment by akallabeth** [comment]
Fixed with #5745
