### ISSUE TITLE
-g workarea cuts the taskbar of W2k8R2

### ISSUE THREAD

**Issue by gotsiboon** [FreeRDP/FreeRDP#428]
Hi developers,

the option "-g workarea" cuts the windows taskbar of my W2k8 R2 and only the upper half of the aero-taskbar is shown (for instance the START button and minimized windows are only half visible, etc.). It seems that exactly the ~20 pixel are missing which are used to display window decoration of freerdp.

xfreerdp -g workarea -u user -p pass server

Best regards & thanks for all the great work,
gotsiboon.

PS: Anyway, the idea behind -g workarea is very helpful. Especially when using dual monitors as the login isn't between the monitor-frames anymore. But it would be nice to have a complete taskbar (which may be even more important than to have a perfect looking login screen).
;-)

**Comment by akallabeth** [comment]
Can not reproduce with `2.0.0-rc4` and following.

**Comment by varunatarcon** [comment]
I am using freerdp-2.0.0-rc4. While taking RDP with /g workarea of Windows 7 Enterprise from Red Hat Enterprise Linux 7.5, window does not scale properly, taskbar is hidden and there is no way get there. Please fix this.

![freerdp-bug](https://user-images.githubusercontent.com/38517888/60168270-247d1d00-9822-11e9-8896-9da99db00282.jpg)

**Comment by akallabeth** [comment]
Looks like we need to subtract `_NET_REQUEST_FRAME_EXTENTS` from `_NET_WORKAREA`

**Comment by varunatarcon** [comment]
@akallabeth , post downloading & building latest build (freerdp-2.0.0-rc4) on Ubuntu 16.04.5 LTS, I have noticed that using /dynamic-resolution & /workarea starts freerdp in maximized mode by default, thus setting a proper resolution with all the desktop elements visible. [i.e. issue appears to be more or less resolved for Ubuntu 16.04 LTS]
But issue still exists for RHEL 7.5. xfreerdp in RHEL still hides the taskbar. Please fix it for RHEL.
Here is a screenshot for **FreeRDP version 2.0.0-dev5 (85eae46)**
![rhel-freerdp](https://user-images.githubusercontent.com/38517888/60178079-2a7df880-9838-11e9-88dc-86f0cc462d72.jpg)
