### ISSUE TITLE
[android] NDK r16 changed include paths

### ISSUE THREAD

**Issue by aldopa** [FreeRDP/FreeRDP#4285]
Hi,
I'm trying to compile the library for running the sample project on Android.
I'm on Debian 8 with standard develop environment installed on.
I'm following this https://github.com/FreeRDP/FreeRDP/blob/master/docs/README.android

I have SDK and NDK installed as "/home/dev/Android/Sdk/ndk-bundle" and "/home/dev/Android/Sdk"

I've installed cmake from debian repository.

When I run the script

./scripts/android-build-freerdp.sh --ndk "/home/dev/Android/Sdk/ndk-bundle" "/home/dev/Android/Sdk/"

it stops with error during compilation of openssl

crypto/aes/aes_core.c:39:20: fatal error: assert.h: No such file or directory
 #include <assert.h>

following the complete output of the script

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
./scripts/android-build-freerdp.sh --ndk "/home/dev/Android/Sdk/ndk-bundle" "/home/dev/Android/Sdk/"                                                                                                                           
[RUN] mkdir -p /home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../build                                                               
[RUN] bash /home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/android-build-openssl.sh --src /home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../build/openssl --dst /home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --ndk /home/dev/Android/Sdk/ndk-bundle --arch armeabi --target 21 --tag OpenSSL_1_1_0e                                                      
[RUN] export CROSS_SYSROOT=/home/dev/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm                                              
[RUN] export ANDROID_DEV=/home/dev/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm/usr                                            
[RUN] export CROSS_COMPILE= arm-linux-androideabi-                                                                                    
[RUN] export PATH=/home/dev/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/local/bin:/home/dev/bin:/home/dev/Android/Sdk/platform-tools:/opt/java/64/jdk1.8.0_144//bin                                                                                                                         
CONFIG=android                                                                                                                        
ARCH_PREFIX=arm-linux-androideabi-                                                                                                    
DST_PREFIX=armeabi                                                                                                                    
TOOLCHAIN_PREFIX=arm-linux-androideabi-                                                                                               
PLATFORM_PREFIX=arch-arm                                                                                                              
CROSS_SYSROOT=/home/dev/Android/Sdk/ndk-bundle/platforms/android-21/arch-arm                                                           
CROSS_COMPILE= arm-linux-androideabi-                                                                                                 
PATH=/home/dev/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/sbin:/usr/local/bin:/home/dev/bin:/home/dev/Android/Sdk/platform-tools:/opt/java/64/jdk1.8.0_144//bin
[RUN] cd /home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../build/openssl                                                             
[RUN] ./Configure --config=/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/openssl-mips64.conf --openssldir=/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi android no-shared                                 
Configuring OpenSSL version 1.1.0e (0x1010005fL)                                                                                      
    no-asan         [default]  OPENSSL_NO_ASAN                                                                                        
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG                                                                              
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE                                                          
    no-dynamic-engine [forced]                                                                                                        
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128                                                                  
    no-egd          [default]  OPENSSL_NO_EGD                                                                                         
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL                                                                                    
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER                                                                            
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS                                                                                  
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)                                                                              
    no-msan         [default]  OPENSSL_NO_MSAN                                                                                        
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)                                                                              
    no-sctp         [default]  OPENSSL_NO_SCTP                                                                                        
    no-shared       [option]                                                                                                          
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE                                                                                   
    no-ssl3         [default]  OPENSSL_NO_SSL3                                                                                        
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD                                                                                 
    no-ubsan        [default]  OPENSSL_NO_UBSAN                                                                                       
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST                                                                                   
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS                                                                        
    no-zlib         [default]                                                                                                         
    no-zlib-dynamic [default]                                                                                                         
Configuring for android                                                                                                               
CC            = arm-linux-androideabi-gcc                                                                                             
CFLAG         =-Wall -O3 -pthread -mandroid -fPIC --sysroot=$(CROSS_SYSROOT) -Wa,--noexecstack                                        
SHARED_CFLAG  =-fPIC -DOPENSSL_USE_NODELETE                                                                                           
DEFINES       =DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_DYNAMIC_ENGINE OPENSSL_PIC                                    
LFLAG         =                                                                                                                       
PLIB_LFLAG    =                                                                                                                       
EX_LIBS       =-ldl                                                                                                                   
APPS_OBJ      =                                                                                                                       
CPUID_OBJ     =mem_clr.o                                                                                                              
UPLINK_OBJ    =                                                                                                                       
BN_ASM        =bn_asm.o                                                                                                               
EC_ASM        =                                                                                                                       
DES_ENC       =des_enc.o fcrypt_b.o                                                                                                   
AES_ENC       =aes_core.o aes_cbc.o                                                                                                   
BF_ENC        =bf_enc.o                                                                                                               
CAST_ENC      =c_enc.o                                                                                                                
RC4_ENC       =rc4_enc.o rc4_skey.o                                                                                                   
RC5_ENC       =rc5_enc.o                                                                                                              
MD5_OBJ_ASM   =                                                                                                                       
SHA1_OBJ_ASM  =                                                                                                                       
RMD160_OBJ_ASM=                                                                                                                       
CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o                                                                                      
MODES_OBJ     =                                                                                                                       
PADLOCK_OBJ   =                                                                                                                       
CHACHA_ENC    =chacha_enc.o                                                                                                           
POLY1305_OBJ  =                                                                                                                       
BLAKE2_OBJ    =                                                                                                                       
PROCESSOR     =                                                                                                                       
RANLIB        =true                                                                                                                   
ARFLAGS       =                                                                                                                       
PERL          =/usr/bin/perl                                                                                                          

THIRTY_TWO_BIT mode                                                                                                                   
BN_LLONG mode                                                                                                                         
RC4 uses unsigned char                                                                                                                

Configured for android.                                                                                                               
[RUN] make CALC_VERSIONS=SHLIB_COMPAT=; SHLIB_SOVER= depend                                                                           
[RUN] make CALC_VERSIONS=SHLIB_COMPAT=; SHLIB_SOVER= build_libs                                                                       
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \                                                                                   
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _build_libs
make[1]: Entering directory '/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/build/openssl'
make[1]: Leaving directory '/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/build/openssl'
make[1]: Entering directory '/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/build/openssl'
arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_NGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniibs/armeabi\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot=/home/dev/Android/Sdk/ndk-budle/platforms/android-21/arch-arm -Wa,--noexecstack  -fPIC -DOPENSSL_USE_NODELETE -c -o crypto/aes/aes_cbc.o crypto/aes/aes_cbc.c
arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_NGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniibs/armeabi\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot=/home/dev/Android/Sdk/ndk-budle/platforms/android-21/arch-arm -Wa,--noexecstack  -fPIC -DOPENSSL_USE_NODELETE -c -o crypto/aes/aes_cfb.o crypto/aes/aes_cfb.c
arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_NGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniibs/armeabi\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot=/home/dev/Android/Sdk/ndk-budle/platforms/android-21/arch-arm -Wa,--noexecstack  -fPIC -DOPENSSL_USE_NODELETE -c -o crypto/aes/aes_core.o crypto/aes/aes_core.c
crypto/aes/aes_core.c:39:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.
Makefile:672: recipe for target 'crypto/aes/aes_core.o' failed
make[1]: *** [crypto/aes/aes_core.o] Error 1
make[1]: Leaving directory '/home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/build/openssl'
Makefile:129: recipe for target 'build_libs' failed
make: *** [build_libs] Error 2
[ERROR] make CALC_VERSIONS=SHLIB_COMPAT=; SHLIB_SOVER= build_libs retured 2
[ERROR] bash /home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/android-build-openssl.sh --src /home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/sripts/../build/openssl --dst /home/dev/DEV/FreeRDP/2017.11.28/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --dk /home/dev/Android/Sdk/ndk-bundle --arch armeabi --target 21 --tag OpenSSL_1_1_0e retured 1
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

but file assert.h is on standard include dir /usr/include

Note that compilation of FreeRDP for linux with the same source work fine, it fails on the Android client compilation.

Where is the error ?

**Comment by akallabeth** [comment]
Check your command line ;) you don't set the SDK path.
Please use IRC or mailing list for support in the future.

**Comment by aldopa** [comment]
Hi akallabeth, it's a copy error, I had set the SDK path|!
The command I used is

./scripts/android-build-freerdp.sh --ndk "/home/dev/Android/Sdk/ndk-bundle" --sdk "/home/dev/Android/Sdk/"

**Comment by akallabeth** [comment]
@aldopa Ok, looks like google changed the NDK layout (once again) so that the includes are not found. Try with a NDK before r16.

**Comment by aldopa** [comment]
Great ! Now It's ok with NDK r15c

Tanks akallabeth

**Comment by akallabeth** [comment]
@aldopa Good it works for you, we still need to fix support for newer versions ;)

**Comment by aldopa** [comment]
I hope to help you reporting a fix I made to iOS version.
In landscape iFreeRDP less rdp session (only the view part, RDP session remain opened but screen is black) when I request keyboard, at time keyboard appear the screen become black and when keyboard hide all the screen remain black.

I fix it and all work properly changing the func  shiftKeyboard: (NSNotification*)notification

in file /client/iOS/Controllers/RDPSessionViewController.m

Changing following lines 

if( [self isLandscape] ) {
		// landscape has the keyboard based on x, so x can go negative
		_keyboard_last_height = keyboardEndFrame.size.width + keyboardEndFrame.origin.x;
	} else {
		// portrait has the keyboard based on the difference of the height and the frames y.
		CGFloat height = [[UIScreen mainScreen] bounds].size.height;
		_keyboard_last_height = height - keyboardEndFrame.origin.y;
	}

with

CGFloat height = [[UIScreen mainScreen] bounds].size.height;
_keyboard_last_height = height - keyboardEndFrame.origin.y;

all works properly

**Comment by akallabeth** [comment]
@aldopa Better create a pull request/separate issue for that. This issue handles the android NDK stuff, please keep on topic.

**Comment by farhanarrafi** [comment]
Hello is there any fix for this issue yet?

**Comment by akallabeth** [comment]
@farhanarrafi no

**Comment by andreatondelli** [comment]
Probably I don't understand something but now it does not work with any version of the NDK. I have tried 14, 15 and 16 without success.
Why @aldopa says that it works with version 15c? It means that it has worked with that version only for a while? There is no chance to compile now the  Android version? Thanks.

**Comment by akallabeth** [comment]
@andreatondelli building quite fine here with 15c, so what are your settings?

**Comment by andreatondelli** [comment]
Sorry guys, you are right. I had a mistake with scripts and when you ask me to post configuration and i check all the toolchain i found the error (I was using the latest version of the NDK).
Thank you @akallabeth

**Comment by laoyao** [comment]
@andreatondelli I meet the same problem. What should I do?

➜  FreeRDP-2.0.0-rc2 ./scripts/android-build-freerdp.sh --ndk ~/Library/Android/ndk/android-ndk-r17b --sdk ~/Library/Android/sdk
[RUN] mkdir -p /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../build
[RUN] bash /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/android-build-openssl.sh --src /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../build/openssl --dst /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --ndk /Users/yaowu/Library/Android/ndk/android-ndk-r17b --arch armeabi --target 21 --tag OpenSSL_1_1_0g
Preparing checkout...
[RUN] cd /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2
[RUN] cd /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../build/openssl
[RUN] git fetch
[RUN] git reset --hard HEAD
HEAD is now at b2758a2292 Prepare for 1.1.0g release
[RUN] git checkout OpenSSL_1_1_0g
HEAD is now at b2758a2292... Prepare for 1.1.0g release
[RUN] cd /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2
[RUN] export CROSS_SYSROOT=/Users/yaowu/Library/Android/ndk/android-ndk-r17b/platforms/android-21/arch-arm
[RUN] export ANDROID_DEV=/Users/yaowu/Library/Android/ndk/android-ndk-r17b/platforms/android-21/arch-arm/usr
[RUN] export CROSS_COMPILE= arm-linux-androideabi-
[RUN] export PATH=/Users/yaowu/Library/Android/ndk/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/:/Users/yaowu/.nvm/versions/node/v8.11.2/bin:/Users/yaowu/Library/Android/ndk/android-ndk-r17b:/usr/local/opt/go/libexec/bin:/Users/yaowu/Documents/Dev/flutter/bin:/anaconda3/bin:/Users/yaowu/Library/Android/sdk/tools:/Users/yaowu/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
CONFIG=android
ARCH_PREFIX=arm-linux-androideabi-
DST_PREFIX=armeabi
TOOLCHAIN_PREFIX=arm-linux-androideabi-
PLATFORM_PREFIX=arch-arm
CROSS_SYSROOT=/Users/yaowu/Library/Android/ndk/android-ndk-r17b/platforms/android-21/arch-arm
CROSS_COMPILE= arm-linux-androideabi-
PATH=/Users/yaowu/Library/Android/ndk/android-ndk-r17b/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/:/Users/yaowu/.nvm/versions/node/v8.11.2/bin:/Users/yaowu/Library/Android/ndk/android-ndk-r17b:/usr/local/opt/go/libexec/bin:/Users/yaowu/Documents/Dev/flutter/bin:/anaconda3/bin:/Users/yaowu/Library/Android/sdk/tools:/Users/yaowu/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[RUN] cd /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../build/openssl
[RUN] git clean -xdf
Removing Makefile
Removing configdata.pm
Removing crypto/aes/aes_cbc.d
Removing crypto/aes/aes_cbc.o
Removing crypto/aes/aes_cfb.d
Removing crypto/aes/aes_cfb.o
Removing crypto/include/internal/bn_conf.h
Removing crypto/include/internal/dso_conf.h
Removing include/openssl/opensslconf.h
[RUN] ./Configure --config=/Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/openssl-mips64.conf --openssldir=/Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi android no-shared
Configuring OpenSSL version 1.1.0g (0x1010007fL)
    no-asan         [default]  OPENSSL_NO_ASAN
    no-crypto-mdebug [default]  OPENSSL_NO_CRYPTO_MDEBUG
    no-crypto-mdebug-backtrace [default]  OPENSSL_NO_CRYPTO_MDEBUG_BACKTRACE
    no-dynamic-engine [forced]
    no-ec_nistp_64_gcc_128 [default]  OPENSSL_NO_EC_NISTP_64_GCC_128
    no-egd          [default]  OPENSSL_NO_EGD
    no-fuzz-afl     [default]  OPENSSL_NO_FUZZ_AFL
    no-fuzz-libfuzzer [default]  OPENSSL_NO_FUZZ_LIBFUZZER
    no-heartbeats   [default]  OPENSSL_NO_HEARTBEATS
    no-md2          [default]  OPENSSL_NO_MD2 (skip dir)
    no-msan         [default]  OPENSSL_NO_MSAN
    no-rc5          [default]  OPENSSL_NO_RC5 (skip dir)
    no-sctp         [default]  OPENSSL_NO_SCTP
    no-shared       [option]
    no-ssl-trace    [default]  OPENSSL_NO_SSL_TRACE
    no-ssl3         [default]  OPENSSL_NO_SSL3
    no-ssl3-method  [default]  OPENSSL_NO_SSL3_METHOD
    no-ubsan        [default]  OPENSSL_NO_UBSAN
    no-unit-test    [default]  OPENSSL_NO_UNIT_TEST
    no-weak-ssl-ciphers [default]  OPENSSL_NO_WEAK_SSL_CIPHERS
    no-zlib         [default]
    no-zlib-dynamic [default]
Configuring for android
CC            = arm-linux-androideabi-gcc
CFLAG         =-Wall -O3 -pthread -mandroid -fPIC --sysroot=$(CROSS_SYSROOT) -Wa,--noexecstack
SHARED_CFLAG  =-fPIC -DOPENSSL_USE_NODELETE
DEFINES       =DSO_DLFCN HAVE_DLFCN_H NDEBUG OPENSSL_THREADS OPENSSL_NO_DYNAMIC_ENGINE OPENSSL_PIC
LFLAG         =
PLIB_LFLAG    =
EX_LIBS       =-ldl
APPS_OBJ      =
CPUID_OBJ     =mem_clr.o
UPLINK_OBJ    =
BN_ASM        =bn_asm.o
EC_ASM        =
DES_ENC       =des_enc.o fcrypt_b.o
AES_ENC       =aes_core.o aes_cbc.o
BF_ENC        =bf_enc.o
CAST_ENC      =c_enc.o
RC4_ENC       =rc4_enc.o rc4_skey.o
RC5_ENC       =rc5_enc.o
MD5_OBJ_ASM   =
SHA1_OBJ_ASM  =
RMD160_OBJ_ASM=
CMLL_ENC      =camellia.o cmll_misc.o cmll_cbc.o
MODES_OBJ     =
PADLOCK_OBJ   =
CHACHA_ENC    =chacha_enc.o
POLY1305_OBJ  =
BLAKE2_OBJ    =
PROCESSOR     =
RANLIB        =true
ARFLAGS       =
PERL          =perl

THIRTY_TWO_BIT mode
BN_LLONG mode
RC4 uses unsigned char

Configured for android.
[RUN] make CALC_VERSIONS=SHLIB_COMPAT=; SHLIB_SOVER= depend
[RUN] make CALC_VERSIONS=SHLIB_COMPAT=; SHLIB_SOVER= build_libs
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
perl "-I." -Mconfigdata "util/dofile.pl" \
	    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
/Applications/Xcode.app/Contents/Developer/usr/bin/make depend && /Applications/Xcode.app/Contents/Developer/usr/bin/make _build_libs
arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot=/Users/yaowu/Library/Android/ndk/android-ndk-r17b/platforms/android-21/arch-arm -Wa,--noexecstack  -fPIC -DOPENSSL_USE_NODELETE -MMD -MF crypto/aes/aes_cbc.d.tmp -MT crypto/aes/aes_cbc.o -c -o crypto/aes/aes_cbc.o crypto/aes/aes_cbc.c
arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot=/Users/yaowu/Library/Android/ndk/android-ndk-r17b/platforms/android-21/arch-arm -Wa,--noexecstack  -fPIC -DOPENSSL_USE_NODELETE -MMD -MF crypto/aes/aes_cfb.d.tmp -MT crypto/aes/aes_cfb.o -c -o crypto/aes/aes_cfb.o crypto/aes/aes_cfb.c
arm-linux-androideabi-gcc  -I. -Icrypto/include -Iinclude -DDSO_DLFCN -DHAVE_DLFCN_H -DNDEBUG -DOPENSSL_THREADS -DOPENSSL_NO_DYNAMIC_ENGINE -DOPENSSL_PIC -DOPENSSLDIR="\"/Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi\"" -DENGINESDIR="\"/usr/local/lib/engines-1.1\"" -Wall -O3 -pthread -mandroid -fPIC --sysroot=/Users/yaowu/Library/Android/ndk/android-ndk-r17b/platforms/android-21/arch-arm -Wa,--noexecstack  -fPIC -DOPENSSL_USE_NODELETE -MMD -MF crypto/aes/aes_core.d.tmp -MT crypto/aes/aes_core.o -c -o crypto/aes/aes_core.o crypto/aes/aes_core.c
crypto/aes/aes_core.c:39:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.
make[1]: *** [crypto/aes/aes_core.o] Error 1
make: *** [build_libs] Error 2
[ERROR] make CALC_VERSIONS=SHLIB_COMPAT=; SHLIB_SOVER= build_libs retured 2
[ERROR] bash /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/android-build-openssl.sh --src /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../build/openssl --dst /Users/yaowu/Downloads/FreeRDP-2.0.0-rc2/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --ndk /Users/yaowu/Library/Android/ndk/android-ndk-r17b --arch armeabi --target 21 --tag OpenSSL_1_1_0g retured 1

**Comment by laoyao** [comment]
@andreatondelli Give me some advise! Thanks!

**Comment by andreatondelli** [comment]
@laoyao i think you are using latest NDK version (17b)

**From your post**
> FreeRDP-2.0.0-rc2 ./scripts/android-build-freerdp.sh --ndk ~/Library/Android/ndk/**android-ndk-r17b** --sdk ~/Library/Android/sdk

You must download the 15c version from here:
> https://developer.android.com/ndk/downloads/older_releases

Click the button "I Agree to the terms", download the zip file of Android NDK Revision 15c (July 2017) for your platform and extract **where_you_want**.

Then, run the script using

> FreeRDP-2.0.0-rc2 ./scripts/android-build-freerdp.sh --ndk **where_you_want** --sdk ~/Library/Android/sdk

**Comment by laoyao** [comment]
@andreatondelli Thanks. Change NDK to 15c, it works.

**Comment by akallabeth** [comment]
looks like with more modern sdk/ndk it works also this way:
1. Install NDK and CMAKE in android studio
1. Add the path to the SDK-cmake and Ninja 
1. Run `cmake -G"Ninja" -DANDROID_ABI=x86_64 -DBUILD_SHARED_LIBS=ON -DOPENSSL_ROOT_DIR=<somepath> -ANDROID_NDK=<ndk path> -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=<NDK base path>/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=23 -DANDROID_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=<current install path>`
1. Repeat that for each architecture

**Comment by smtcrms** [comment]
all ndk is deprecated
