### ISSUE TITLE
CMAKE Error (Unable to Generate makefile)

### ISSUE THREAD

**Issue by boxboi1471** [FreeRDP/FreeRDP#4289]
When trying to compile using 

`cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .`

on Raspbian 8 (Jessie)  I get the floowing Error:

> cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .
FREERDP_VERSION=2.0.0-dev2
-- Git Revision 2f15b80
-- GCC default symbol visibility: hidden
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find Threads (missing: Threads_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindThreads.cmake:178 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:577 (find_package)

-- Configuring incomplete, errors occurred!
See also "/root/FreeRDP/CMakeFiles/CMakeOutput.log".
See also "/root/FreeRDP/CMakeFiles/CMakeError.log".

**Comment by akallabeth** [comment]
Please use IRC or the mailing list for support questions.
