### ISSUE TITLE
on iOS RDP window become black in landscape when rise keyboard

### ISSUE THREAD

**Issue by aldopa** [FreeRDP/FreeRDP#4295]
Tested on iPad Air with iOS 11.0.3 and iOS 11.1 with iFreeRDP RC0 and RC1 compiled with Xcode 9.1
In landscape iFreeRDP "less" RDP window (session remain active), the RDP window become black when keyboard rise, and when keyboard hide the RDP window remain black.

I fix it and all work properly changing the func shiftKeyboard: (NSNotification*)notification

in file /client/iOS/Controllers/RDPSessionViewController.m

Changing following lines

if( [self isLandscape] ) {
    // landscape has the keyboard based on x, so x can go negative
    _keyboard_last_height = keyboardEndFrame.size.width + keyboardEndFrame.origin.x;
} else {
    // portrait has the keyboard based on the difference of the height and the frames y.
    CGFloat height = [[UIScreen mainScreen] bounds].size.height;
    _keyboard_last_height = height - keyboardEndFrame.origin.y;
}

with

CGFloat height = [[UIScreen mainScreen] bounds].size.height;
_keyboard_last_height = height - keyboardEndFrame.origin.y;

all works properly

**Comment by reverseAndroid** [comment]
@akallabeth Hello, I put forward a while ago aFreeRDP2.0 (Android version) The problem and the problem is the same, horizontal screen, pop-up keyboard will cause a white screen problem, hide the keyboard back to normal. This problem is only part of the test phone.
