### ISSUE TITLE
drive redirection - raise an error if the directory can't be founde

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#4296]
Currently one can pass any path to /drive even invalid ones. The code handles those errors correctly however if the directory is invalid the redirected drive would just be empty on the server side. The parser, or channel, should at least print a warning when the redirected path is invalid.

**Comment by miked1428** [comment]
Hi,
Allowing the /drive string to map to invalid directories (in our case it is /drive:'USB,/mnt/usbdevice') gave us the option for users to connect with or without a usb drive plugged in. Now they can't connect without a drive inserted. Is there a work around to allow access to /mnt/usbdevice regardless of whether there is a drive plugged in or not?
