### ISSUE TITLE
[RDPEI] Implement AAC and MP3 encoders

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#4309]
Like #4165 but for microphone redirection improved format support is desired.

**Comment by BornToDrink** [comment]
I can confirm the same problem.
A little hint that could help:
On RDP session to Windows 8 and latest skype - it's very choppy.
On RDP session to Windows 10 and latest skype - works perfect.

Skype version up to 7.21 was working perfect on Windows 8 as well, but after the update it was disaster.

Also with Slack and Hangout via Chrome it's always choppy. So basically on chrome-based apps, no matter what version of Windows.

**Comment by akallabeth** [comment]
@BornToDrink This is a feature request, so nothing that has ever been implemented in FreeRDP.

**Comment by BornToDrink** [comment]
@akallabeth Yes it's clear, I just wanted to give some hints based on our experience.
Can't wait for that feature! :)

**Comment by akallabeth** [comment]
#4453 provided the framework, it is now a matter of creating a test setup and trying out which codecs work and which don't.

**Comment by akallabeth** [comment]
Backend options with FFMPEG and FAAD/FAAC available.

**Comment by stilyan** [comment]
@akallabeth thanks for your work. Please provide more info on usage.
Having laggy, robotic voice over Slack calls, Skype is fine with latest master.
How do I pass the decoder ? /multimedia:decoder:XXX ?
Any other suggestions on microphone param tweaks ? Like format? Dev?

**Comment by akallabeth** [comment]
@stilyan Compile time only so far, `WITH_DSP_FFMPEG=ON`

**Comment by stilyan** [comment]
@akallabeth thanks.
While configuring
`
-- Looking for LIBAVCODEC_VERSION_MAJOR
-- Looking for LIBAVCODEC_VERSION_MAJOR - found
-- Looking for LIBAVCODEC_VERSION_MINOR
-- Looking for LIBAVCODEC_VERSION_MINOR - found
-- Looking for LIBAVCODEC_VERSION_MICRO
-- Looking for LIBAVCODEC_VERSION_MICRO - found
FFmpeg version detected .. is too old. (Require at least 57.48.101 for sound). Deactivating
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
`
The distribution repository had them too old so I compiled and installed from their git repo.
Those are versions of FFmpeg and related libs
`
ffmpeg version N-91790-g23fe072e43 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7 (Ubuntu 7.3.0-16ubuntu3)
configuration: --enable-avresample
libavutil      56. 19.100 / 56. 19.100
libavcodec     58. 27.101 / 58. 27.101
libavformat    58. 17.106 / 58. 17.106
libavdevice    58.  4.101 / 58.  4.101
libavfilter     7. 26.100 /  7. 26.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  2.100 /  5.  2.100
libswresample   3.  2.100 /  3.  2.100
`
I'm still getting the warning on configuration despite having newer version.
Can you please help out on this?

By the way, libavresample is deprecated, supposedly merged into and to be replaced with libswresample.
I had to manually enable it during ffmpeg configuration and was warned because of the depreciation.

**Comment by akallabeth** [comment]
@stilyan you've most likely installed in `/usr/local`? Uninstall the system packages and add the new installation path to the search path for cmake.
As for `avresample` that is a good idea. Still need to figure out how to properly wrap ffmpeg (their API is more unstable than ours ^^)

**Comment by stilyan** [comment]
@akallabeth 
Thanks. Installation path is default, yes, /usr/local.
I did remove the ffmpeg libs that were system packages.
During configuration I see the following:
`
-- Finding recommended feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Disable feature FFmpeg using "-DWITH_FFMPEG=OFF"
-- Checking for module 'libavcodec'
--   Found libavcodec, version 58.27.101
-- Checking for module 'libavutil'
--   Found libavutil, version 56.19.100
-- Checking for module 'libavresample'
--   Found libavresample, version 4.0.0
-- Found FFmpeg: TRUE
`

So at this point it acknowledges libavcodec is found and is 58.27.101

Afterwards I see the following:
`
-- Looking for LIBAVCODEC_VERSION_MAJOR
-- Looking for LIBAVCODEC_VERSION_MAJOR - found
-- Looking for LIBAVCODEC_VERSION_MINOR
-- Looking for LIBAVCODEC_VERSION_MINOR - found
-- Looking for LIBAVCODEC_VERSION_MICRO
-- Looking for LIBAVCODEC_VERSION_MICRO - found
FFmpeg version detected .. is too old. (Require at least 57.48.101 for sound). Deactivating
`

Looking at CMakeCache.txt I see correct paths:
AVCODEC_INCLUDE_DIR:PATH=/usr/local/include
AVCODEC_LIBRARY:FILEPATH=/usr/local/lib/libavcodec.a

Looking at the message I find this part disturbing - ".. is too old"
It doesn't actually show the version it detects, and from what I see in CMakeLists.txt it should do it.

`
check_symbol_exists(LIBAVCODEC_VERSION_MAJOR "libavcodec/version.h" AVCODEC_VERSION_MAJOR)
        check_symbol_exists(LIBAVCODEC_VERSION_MINOR "libavcodec/version.h" AVCODEC_VERSION_MINOR)
        check_symbol_exists(LIBAVCODEC_VERSION_MICRO "libavcodec/version.h" AVCODEC_VERSION_MICRO)
        if (AVCODEC_VERSION_MAJOR LESS 57 OR AVCODEC_VERSION_MINOR LESS 48 OR AVCODEC_VERSION_MICRO LESS 101)
                message("FFmpeg version detected ${}.${}.${} is too old. (Require at least 57.48.101 for sound). Deactivating")
                set(WITH_DSP_FFMPEG OFF)
        endif()
`

I really don't know how to get around this except for deleting this validation or changing flag to ON in buildflags.h and trying like that.
Advices?

**Comment by akallabeth** [comment]
@stilyan ok, you just found a bug in my version check, pr incoming.

**Comment by stilyan** [comment]
@akallabeth thanks.
Now while compiling with WITH_DSP_FFMPEG=ON from your branch https://github.com/akallabeth/FreeRDP/tree/avcodec_version_check_fix I got
`
[303/457] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/dsp_ffmpeg.c.o
libfreerdp/codec/dsp_ffmpeg.c: In function ‘freerdp_dsp_ffmpeg_decode’:
libfreerdp/codec/dsp_ffmpeg.c:596:24: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  context->packet->data = data;
                        ^
[342/457] Linking C shared library libfreerdp/libfreerdp2.so.2.0.0
FAILED: libfreerdp/libfreerdp2.so.2.0.0
: && /usr/bin/cc -fPIC -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -O3 -DNDEBUG   -shared -Wl,-soname,libfreerdp2.so.2 -o libfreerdp/libfreerdp2.so.2.0.0 libfreerdp/CMakeFiles/freerdp.dir/utils/passphrase.c.o libfreerdp/CMakeFiles/freerdp.dir/utils/pcap.c.o libfreerdp/CMakeFiles/freerdp.dir/utils/profiler.c.o libfreerdp/CMakeFiles/freerdp.dir/utils/ringbuffer.c.o libfreerdp/CMakeFiles/freerdp.dir/utils/signal.c.o libfreerdp/CMakeFiles/freerdp.dir/utils/stopwatch.c.o libfreerdp/CMakeFiles/freerdp.dir/utils/msusb.c.o libfreerdp/CMakeFiles/freerdp.dir/common/addin.c.o libfreerdp/CMakeFiles/freerdp.dir/common/settings.c.o libfreerdp/CMakeFiles/freerdp.dir/common/assistance.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/bitmap.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/brush.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/clipping.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/dc.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/drawing.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/line.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/pen.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/region.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/shape.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/graphics.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/gfx.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/video.c.o libfreerdp/CMakeFiles/freerdp.dir/gdi/gdi.c.o libfreerdp/CMakeFiles/freerdp.dir/cache/brush.c.o libfreerdp/CMakeFiles/freerdp.dir/cache/pointer.c.o libfreerdp/CMakeFiles/freerdp.dir/cache/bitmap.c.o libfreerdp/CMakeFiles/freerdp.dir/cache/nine_grid.c.o libfreerdp/CMakeFiles/freerdp.dir/cache/offscreen.c.o libfreerdp/CMakeFiles/freerdp.dir/cache/palette.c.o libfreerdp/CMakeFiles/freerdp.dir/cache/glyph.c.o libfreerdp/CMakeFiles/freerdp.dir/cache/cache.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/er.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/der.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/ber.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/per.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/base64.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/certificate.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/crypto.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/tls.c.o libfreerdp/CMakeFiles/freerdp.dir/crypto/opensslcompat.c.o libfreerdp/CMakeFiles/freerdp.dir/locale/keyboard_layout.c.o libfreerdp/CMakeFiles/freerdp.dir/locale/keyboard.c.o libfreerdp/CMakeFiles/freerdp.dir/locale/locale.c.o libfreerdp/CMakeFiles/freerdp.dir/locale/keyboard_x11.c.o libfreerdp/CMakeFiles/freerdp.dir/locale/xkb_layout_ids.c.o libfreerdp/CMakeFiles/freerdp.dir/locale/keyboard_xkbfile.c.o libfreerdp/CMakeFiles/freerdp.dir/core/bulk.c.o libfreerdp/CMakeFiles/freerdp.dir/core/activation.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gcc.c.o libfreerdp/CMakeFiles/freerdp.dir/core/mcs.c.o libfreerdp/CMakeFiles/freerdp.dir/core/nla.c.o libfreerdp/CMakeFiles/freerdp.dir/core/nego.c.o libfreerdp/CMakeFiles/freerdp.dir/core/info.c.o libfreerdp/CMakeFiles/freerdp.dir/core/input.c.o libfreerdp/CMakeFiles/freerdp.dir/core/license.c.o libfreerdp/CMakeFiles/freerdp.dir/core/errinfo.c.o libfreerdp/CMakeFiles/freerdp.dir/core/errbase.c.o libfreerdp/CMakeFiles/freerdp.dir/core/errconnect.c.o libfreerdp/CMakeFiles/freerdp.dir/core/security.c.o libfreerdp/CMakeFiles/freerdp.dir/core/settings.c.o libfreerdp/CMakeFiles/freerdp.dir/core/orders.c.o libfreerdp/CMakeFiles/freerdp.dir/core/freerdp.c.o libfreerdp/CMakeFiles/freerdp.dir/core/graphics.c.o libfreerdp/CMakeFiles/freerdp.dir/core/client.c.o libfreerdp/CMakeFiles/freerdp.dir/core/server.c.o libfreerdp/CMakeFiles/freerdp.dir/core/codecs.c.o libfreerdp/CMakeFiles/freerdp.dir/core/metrics.c.o libfreerdp/CMakeFiles/freerdp.dir/core/capabilities.c.o libfreerdp/CMakeFiles/freerdp.dir/core/certificate.c.o libfreerdp/CMakeFiles/freerdp.dir/core/connection.c.o libfreerdp/CMakeFiles/freerdp.dir/core/redirection.c.o libfreerdp/CMakeFiles/freerdp.dir/core/autodetect.c.o libfreerdp/CMakeFiles/freerdp.dir/core/heartbeat.c.o libfreerdp/CMakeFiles/freerdp.dir/core/multitransport.c.o libfreerdp/CMakeFiles/freerdp.dir/core/timezone.c.o libfreerdp/CMakeFiles/freerdp.dir/core/rdp.c.o libfreerdp/CMakeFiles/freerdp.dir/core/tcp.c.o libfreerdp/CMakeFiles/freerdp.dir/core/proxy.c.o libfreerdp/CMakeFiles/freerdp.dir/core/tpdu.c.o libfreerdp/CMakeFiles/freerdp.dir/core/tpkt.c.o libfreerdp/CMakeFiles/freerdp.dir/core/fastpath.c.o libfreerdp/CMakeFiles/freerdp.dir/core/surface.c.o libfreerdp/CMakeFiles/freerdp.dir/core/transport.c.o libfreerdp/CMakeFiles/freerdp.dir/core/update.c.o libfreerdp/CMakeFiles/freerdp.dir/core/message.c.o libfreerdp/CMakeFiles/freerdp.dir/core/channels.c.o libfreerdp/CMakeFiles/freerdp.dir/core/window.c.o libfreerdp/CMakeFiles/freerdp.dir/core/listener.c.o libfreerdp/CMakeFiles/freerdp.dir/core/peer.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/tsg.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/rdg.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/rpc.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/rpc_bind.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/rpc_client.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/rpc_fault.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/rts.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/rts_signature.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/ntlm.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/http.c.o libfreerdp/CMakeFiles/freerdp.dir/core/gateway/ncacn_http.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/dsp.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/color.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/audio.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/planar.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/bitmap.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/interleaved.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/progressive.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/rfx_decode.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/rfx_dwt.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/rfx_encode.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/rfx_quantization.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/rfx_rlgr.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/rfx.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/region.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/nsc.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/nsc_encode.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/ncrush.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/xcrush.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/mppc.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/zgfx.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/clear.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/jpeg.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/h264.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/yuv.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/rfx_sse2.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/nsc_sse2.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/dsp_ffmpeg.c.o libfreerdp/CMakeFiles/freerdp.dir/codec/h264_ffmpeg.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_add.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_andor.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_alphaComp.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_colors.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_copy.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_set.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_shift.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_sign.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_YUV.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_YCoCg.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/primitives.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_colors_opt.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_set_opt.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_add_opt.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_alphaComp_opt.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_andor_opt.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_shift_opt.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_sign_opt.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_YCoCg_opt.c.o libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_YUV_ssse3.c.o  -Wl,-rpath,/home/celtis/akallabeth/FreeRDP/winpr/libwinpr: -lpthread -lssl -lcrypto -lX11 -lxkbfile -lfaad -lfaac /usr/local/lib/libavcodec.a /usr/local/lib/libavutil.a /usr/local/lib/libavresample.a winpr/libwinpr/libwinpr2.so.2.0.0 && :
/usr/bin/x86_64-linux-gnu-ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
[344/457] Building C object channels/drive/client/CMakeFiles/drive-client.dir/drive_file.c.o
ninja: build stopped: subcommand failed.`

Should I open new issue on this?

**Comment by akallabeth** [comment]
@stilyan Does this happen with a fresh checkout (or clean up after `git clean -xdf`)?

**Comment by akallabeth** [comment]
@stilyan btw, looks like your ffmpeg has only static libraries installed (`.a`)? That might explain it as we're either using full static (everything in one file) or dynamic linking.

**Comment by akallabeth** [comment]
@stilyan better switch to mailing list or IRC the remaining stuff smells like compilation related and no issues in freerdp.

**Comment by stilyan** [comment]
@akallabeth thanks.
Static libs are default for typical ffmpeg installations
I recompiled with --enable-shared --enable-pic --disable-static
Afterwards I successfully compiled freerdp

Thanks.

**Comment by JackZ0** [comment]
/usr/bin/ld: /usr/local/lib/libavcodec.a(vc1dsp_mmx.o): relocation R_X86_64_PC32 against symbol `ff_pw_9' can not be used when making a shared bad value
 object; recompile with -fPIC
/usr/bin/ld: link: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libfreerdp/CMakeFiles/freerdp.dir/build.make:2282：libfreerdp/libfreerdp2.so.2.0.0] 

how can i deal with this ?
