### ISSUE TITLE
Domain authentication - ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED 

### ISSUE THREAD

**Issue by c-lillini** [FreeRDP/FreeRDP#4310]
Hi,
in the version 2.0 of FreeRDP, I have problem with domain authentication. 
The following command
/v:xxxxxx /d:xxxxxx /u:xxxxxx /p:xxxxxxxxxx /cert-ignore
produces 
ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED
but the password is correct and has not expired. If I use administrator account, it works!
I'm trying to connect to Win2012 Server, with wfreerdp.
In version 1.1 of FreeRDP, authentication works perfectly.
Any idea?

Thanks!

**Comment by akallabeth** [comment]
Please use the mailing list or IRC for support.
As this is a user specific behaviour (by your description) chances are there is something else wrong.
