### ISSUE TITLE
Connection fails when kerberos fails

### ISSUE THREAD

**Issue by luizluca** [FreeRDP/FreeRDP#4311]
I'm using 2.0.0-rc1 on OpenSUSE Tumbleweed. Since some recent changes, the same cmdline that I used to use now gives me a connection failure.

```
$ xfreerdp -g 1240x800 --plugin cliprdr --plugin rdpdr --data disk:luiz:$HOME/Downloads/ -- -d mydomain -u administrator srv2k8r2
...
[19:09:19:602] [1529:1530] [INFO][com.winpr.sspi.Kerberos] - Authenticated to Kerberos v5 via login/password
[19:09:19:616] [1529:1530] [ERROR][com.winpr.sspi.Kerberos] - Init GSS security context failed : can't use Kerberos
[19:09:19:616] [1529:1530] [WARN][com.winpr.sspi] - InitializeSecurityContextA status SEC_E_INTERNAL_ERROR [0x80090304]
[19:09:19:616] [1529:1530] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_AUTHENTICATION_FAILED [0x00020009]
[19:09:19:616] [1529:1530] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[19:09:19:616] [1529:1530] [ERROR][com.freerdp.client.x11] - Freerdp connect error exit status 1
```

It seems that now it tries to use kerberos for authentication. Note that it did authenticated. I managed to connect when I specified FQDN instead of only the server name. This happens with kerberos services. The problem is that xfreerdp did not try alternative authentication methods, specially as password was validated.

**Comment by dodo040** [comment]
@luizluca I would need more traces to debug. Please can you set DEBUG_NLA to ON and export KRB5_TRACE=/dev/stdout. But here my guess is that your server was not found in Kerberos database.
I advice you to take a look at all the tests that have been done at this link :
https://github.com/FreeRDP/FreeRDP/pull/3954
The thing is when you are authenticated against Kerberos with a TGT and can't get TGS, the program just stops and currently doesn't fall back on NTLM. We fall back on NTLM only if we can't get TGT. 
If you want to use NTLM just unset the GSSAPI flag in cmake.

**Comment by luizluca** [comment]
@dodo040 , xfreerdp did not get TGS because I needed to supply FQDN. This is not the issue, this is how kerberos works. From your comment, xfreerdp did what it was programmed to do. I guess there is no need for a trace.

IMHO, xfreerdp should try to fallback to NTLM (or, at least, allow it using cmd options). Change build flags isn't very user friendly.

I see a couple of (more) problems here.

1) xfreerdp is equivalent to a kinit

I noticed that xfreerdp do request a "global" TGT when it is used. It's not desired. I guess the user does not expected that:

```
$ klist
klist: No credentials cache found (filename: /tmp/krb5cc_33822_FilX5X)
$ xfreerdp -u administrator xxxx.DOMAIN
...
$ klist
Ticket cache: FILE:/tmp/krb5cc_33822_FilX5X
Default principal: Administrator@DOMAIN

Valid starting       Expires              Service principal
12-12-2017 16:07:27  13-12-2017 02:07:27  krbtgt/DOMAIN@DOMAIN
        renew until 19-12-2017 16:07:27
12-12-2017 16:07:27  13-12-2017 02:07:27  TERMSRV/vms022w.DOMAIN@DOMAIN
        renew until 19-12-2017 16:07:27
```

Any following program that can use kerberos will use this Administrator@DOMAIN identity. This is a security issue.

2) xfreerdp tries to use current TGT even if username does not match

```
$ klist
Ticket cache: FILE:/tmp/krb5cc_33822_FilX5X
Default principal: luizluca@DOMAIN
$ xfreerdp -g 1240x800 --plugin cliprdr --plugin rdpdr --data disk:luiz:$HOME/Downloads/ -- -d redetresc -u administrator vms022w.DOMAIN
[16:11:41:146] [24258:24259] [INFO][com.freerdp.core] - ERRINFO_SERVER_INSUFFICIENT_PRIVILEGES (0x00000009):The user cannot connect to the server due to insufficient access privileges.
```

I really wanted to keep my TGT as it was. In order to connect, I need to destroy my TGT, connect using xfreerdp, and destroy the new TGT for user Adminsitrator (or simply request a new TGT for user luizluca).

3) xfreerdp still asks for a password even with a valid TGT

When TGT user and -U user matches and TGT is valid and server is referenced using FQDN
What's the point of using kerberos if I need to still use a password? If I supply a blank password, xfreerdp do connects but fails to login. I guess windows does two authentication in a RDP connection. Isn't kerberos supported for login as well?

4) xfreerdp does not fallback to NTLM if kerberos failed
I see multiple cases where kerberos will fail. In fact, kerberos will only work correctly in a specific situation (and it will still ask for a password). xfreerdp must fallback to NTLM. If NTLM is not desired, the user must explicitly disable it (using a non-existing command line option).

**Comment by bmiklautz** [comment]
@luizluca unrelated hint I'd suggest to use the *new* command line syntax. The old might be removed at some point:
```
xfreerdp /size:1240x800 +clipboard /drive:luiz,$HOME/Downloads/ /d:mydomain /u:administrator /v:srv2k8r2
```

**Comment by dodo040** [comment]
@luizluca Yes no need for traces. Your issue is basically the way xfreerdp is currently working.

Thanks for your remarks. About them :

> xfreerdp does not fallback to NTLM if kerberos failed

I will add the possibility to fall back on NTLM even after getting a TGT. But I will also add a command line option /no-ntlm if we only want Kerberos and no fallback on NTLM even if a failure occurred. And I will add as well a option /ntlm-only to use xfreerdp without Kerberos even if WITH_GSSAPI build flag is set.

> xfreerdp is equivalent to a kinit

Not entirely true. TGS getting part is missing in your equivalence : xfreerdp = kinit + kvno (MIT).

> I noticed that xfreerdp do request a "global" TGT when it is used. It's not desired.

What do you mean by "global TGT" ? What do you think the user expects ?

> Any following program that can use kerberos will use this Administrator@DOMAIN identity. This is a security issue.

You could give specific permissions to the folder where the credentials are stored. Note you can define the file used to store credentials by exporting KRB5CCNAME.

> xfreerdp tries to use current TGT even if username does not match

Yes it looks at credentials cache first and if tickets don't match with username, xfreerdp asks new tickets for username.

> I really wanted to keep my TGT as it was.

If you want to keep others TGT/TGS on the filesystem you could also use KRB5CCNAME here. This is how I'm doing currently. I'll take a look if it can be done differently.

> In order to connect, I need to destroy my TGT, connect using xfreerdp, and destroy the new TGT for user Adminsitrator (or simply request a new TGT for user luizluca).

This part is not clear to me. Normally xfreerdp is able to clear cache by itself and then get new tickets for the new expected users like I said previously.

> xfreerdp still asks for a password even with a valid TGT

I still advise you to take a look at #3954.

**Comment by luizluca** [comment]
@dodo040 ,

> I will add the possibility to fall back on NTLM even after getting a TGT. But I will also add a command line option /no-ntlm if we only want Kerberos and no fallback on NTLM even if a failure occurred. And I will add as well a option /ntlm-only to use xfreerdp without Kerberos even if WITH_GSSAPI build flag is set.

That would be nice.


> xfreerdp is equivalent to a kinit
> 
> Not entirely true. TGS getting part is missing in your equivalence : xfreerdp = kinit + kvno (MIT).
> What do you mean by "global TGT" ? What do you think the user expects ?
> Any following program that can use kerberos will use this Administrator@DOMAIN identity. This is a security issue.

"Global", I mean a TGT that is visible for other process. Imagine a user that is not aware of kerberos. After a connection using xfreerdp, a following smbclient might reuse the same authentication that xfreerdp used.
Normally kerberos programs (smbclient, browsers, ldap*) do not request TGT. If there is a TGT avaiable, use it. If not, simply fail (or fallback to NTLM). If kerberos is more secure than NTLM, xfreerdp could get a TGT but it should hide it from other process. In current situation a malicious process with nothing but user file access could monitor kerberos cache and wait for a user use xfreerdp with a admin privilegies.

Anyway, I still think that the best way to deal with kerberos is to never request a TGT inside xfreerdp.

> You could give specific permissions to the folder where the credentials are stored. Note you can define the file used to store credentials by exporting KRB5CCNAME.

Yes, I do use that. Anyway, the security issue and confusion for those that are not aware about kerberos remains.

> I still advise you to take a look at #3954.
OK. The fact that we still need to supply a password breaks SSO. Well, I hope this improves in the future.

**Comment by abunimeh** [comment]
I am having the same issue, however, I couldn't get it to work even when using FQDN.

I am running Fedora 27 and the issue exists on 
freerdp.x86_64                                                      2:2.0.0-35.20171220gitbfe8359.fc27
remmina.x86_64                                                     1.2.0-0.44.rcgit.26.fc27

Thanks!

**Comment by cheese1** [comment]
same here with fedora27 and freerdp-2.0.0-36.20180119git3c45a60 (self compiled).

**Comment by abunimeh** [comment]
my issue is resolved now.
I am using
freerdp.x86_64                          2:2.0.0-36.20180115git8f52c7e.fc27
freerdp-libs.x86_64                     2:2.0.0-36.20180115git8f52c7e.fc27
remmina-plugins-rdp.x86_64              1.2.0-0.45.20180107.git.d70108c.fc27

**Comment by weberhofer** [comment]
This issue might be related to #4348 and #4363

**Comment by hardening** [comment]
The fallback to NTLM is implemented now and we have a stabilized kerberos support.
