### ISSUE TITLE
minimum xrandr lib dependency raised to 1.5

### ISSUE THREAD

**Issue by frispete** [FreeRDP/FreeRDP#4314]
Commit https://github.com/FreeRDP/FreeRDP/commit/e064aa6a99f4396a15dc02b039a94d200bf5287b raised the minimum dependency level for xrandr, which in turn is not tested in cmake.

`XRRQueryExtension()` is available with xrandr >= 1.5 only. Older systems do not provide this.

It might be a good idea to handle a lower xrandr lib version more gracefully...

**Comment by akallabeth** [comment]
@frispete As far as I see it, only features depending on XRandr 1.5 are deactivated when compiled on older systems, as they will not work anyway.

**Comment by frispete** [comment]
When compiled on older systems with a lower xrandr (1.3.2 in my case), the build fails (due to the missing XRRQueryExtension). The xrandr detection only checks for xrandr existence, not a specific feature, AFAICS.

I was able to sort this out in my build by adding xrandr 1.5 to my project, but this is a significant intervention, and I thought, it is worth a note.

**Comment by frispete** [comment]
I've tried to reproduce this issue, but failed. 

Sorry for the noice.

**Comment by frispete** [comment]
I've tried to reproduce this issue, but failed. 

Sorry for the noice.

**Comment by akallabeth** [comment]
@frispete Seems your issue was already solved with #4305

**Comment by frispete** [comment]
I must have pulled it between those commits.

You guys rock!
