### ISSUE TITLE
Dynamic resolution feature is broken for me since ec027bf

### ISSUE THREAD

**Issue by argonym** [FreeRDP/FreeRDP#4330]
Since merging the "Dynamic resolution improvements" #4318 (commit: ce89a90 / merge commit: ec027bf) the new `/dynamic-resolution` feature effectively stopped working. After connection the window is initially marked as re-sizable, but the first resize attempt seems not to be carried out, instead the resize capabilities get removed from the window.

* Running xfreerdp on Gnome 3.26 under Wayland
* Connecting to Server2016
* Cmdline:
```
xfreerdp /kbd:German +fonts +window-drag +decorations -themes -wallpaper +clipboard +auto-reconnect /disp /dynamic-resolution /workarea \
        /drive:"rdp_exchange,$HOME/rdp_exchange" +compression /sec:nla /bpp:16 /rfx /gfx +gfx-progressive -bitmap-cache +multitransport \
        /t:"$rdp_title" /u:"$rdp_user" /cert-name:"$rdp_title" /v:$rdp_host:$rdp_port /p:"$rdp_password" /cert-ignore /log-level:DEBUG
```

* Attached [xfreerdp-bfe8359b5.log](https://github.com/FreeRDP/FreeRDP/files/1583197/xfreerdp-bfe8359b5.log) (working, commit before the problematic one) and [xfreerdp-ec027bf.log](https://github.com/FreeRDP/FreeRDP/files/1583198/xfreerdp-ec027bf.log) (broken as described). In both cases I opened a session, attempted to resize the window once the session was ready, and quickly afterwards closed the window/session.

**Comment by hardening** [comment]
@argonym ok I see what's going on, when using egfx there's no reactivation sequence but only a RESETGRAPHICS message in the egfx channel. I'll treat this one.

**Comment by argonym** [comment]
Using #4332, /dynamic-resolution now works (again) for me. Thank you.
Great feature BTW. :-)

P.S.: As I don't know how to draw your (devs) attention to it otherwise, please allow me to abuse this issue to point you to a long-standing (bitmap) cache issue that makes e.g. some editor applications hardly usable when connected to RDP<8 servers: https://github.com/FreeRDP/FreeRDP/issues/1612#issuecomment-350280272
