### ISSUE TITLE
Make GFX mode default for windows 10 and up

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#4341]
As mentioned in #4326 newer windows 10 versions do no longer support legacy RDP modes.
Change FreeRDP to announce GFX by default.

Unitl #4266 is resolved it may be a good idea to only announce 10.2 capabilities by default.

**Comment by lemonmojo** [comment]
FYI: As mentioned in https://github.com/FreeRDP/FreeRDP/issues/4326, newer Insider builds (I tested 17093 and 17101) don't require egfx anymore, so it might make sense to postpone switching GFX on by default.

**Comment by akallabeth** [comment]
Fixed with https://github.com/FreeRDP/FreeRDP/pull/6786
