### ISSUE TITLE
1.0.2 dies with "xrealloc: null pointer given" if clipboard buffer has too much data

### ISSUE THREAD

**Issue by PenelopeFudd** [FreeRDP/FreeRDP#4343]
## To save time and help us identify the issue a bug report should at least contain the following:
  * a useful description of the bug - "It's not working" isn't good enough - you must try harder ;)
Xfreerdp 1.0.2 crashes if there's some bad data in the clipboard, copied from Firefox or Chrome with Ctrl-A/Ctrl-C.

  * the steps to reproduce the bug
1. On a Ubuntu 14.04.5 LTS machine, start Firefox 57.0.3 (64-bit) or Chrome 63.0.3239.132 (Official Build) (64-bit) and Xfreerdp 1.0.2
2. Load a page containing of text and images -- (seems I have a special page)
3. Select it all (ctrl-A) and copy it (ctrl-C) -- (14982 bytes)
4. Click on Xfreerdp window
5. Notice Xfreerdp crashes with "xrealloc: null pointer given" (most of the time)
6. Restart Xfreerdp
7. Notice Xfreerdp crashes right after login, with "xrealloc: null pointer given" (every time)
8. Clear the clipboard by copying something smaller
9. Restart Xfreerdp
10. Notice that it doesn't crash now

Notes: Typing 'xclip -selection clipboard -o > bad-data.txt' saves the *text* of the buffer that's causing the problem, but 'xclip -selection clipboard -i < bad-data.txt' doesn't recreate the problem; I have to copy from Firefox or Chrome.

  * command line you have used
xfreerdp --from-stdin -g 1600x900 -u $username -d $domain --plugin cliprdr $server

  * to what system did you connect to? (win8, 2008, ..)
Windows 10

  * what did you expect to happen?
No crashing
  * what actually happened?
Crashing

  * freerdp version (e.g. xfreerdp --version) or package version or git commit
xfreerdp --version
This is FreeRDP version 1.0.2

  * freerdp configuration (e.g. xfreerdp --buildconfig)
xfreerdp --buildconfig
invalid option: --buildconfig
failed to parse arguments.

```
# gdb xfreerdp
(gdb) r -g 1600x900 -u chowes -d ANT --plugin cliprdr YVR-1850005188.ant.amazon.com
Password: 
[New Thread 0x7ffff3530700 (LWP 3487)]
xrealloc: null pointer given

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3f35700 (LWP 3444)]
__memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
35	../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: No such file or directory.
```

  * operating System, architecture, distribution e.g. linux, amd64, debian
Ubuntu 14.04.5 LTS, x86_64, Ubuntu

  * if you built it yourself add some notes which branch you have used, also your cmake parameters can help
  * extra information helping us to find the bug
How can I record what's in my clipboard so that I can replicate this?  The page contains confidential information, so I'd like to sanitize it and ideally find a minimum-size test case for your consideration.

_Thank you for reporting a bug!_

**Comment by akallabeth** [comment]
Could you try our nightly builds https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds ?
1.0 is quite old and does not recieve much attention nowadays.
