### ISSUE TITLE
MacFreeRDP.app is crashing

### ISSUE THREAD

**Issue by hwyl7676** [FreeRDP/FreeRDP#4346]
Hello ~

When running the MacFreeRDP App that was Built and generated freerdp 2.0.0-rc1, i kindly ask you for the errors generated.

Build environment

     osx: 10.11.4

     Xcode: Version 7.3

The occurrence file and the location of occurrence are changed to bold.

file
    FreeRDP-master/libfreerdp/core/connection.c

function
    BOOL rdp_client_connect(rdpRdp* rdp)

    if (settings->FIPSMode || winpr_FIPSMode())
    {
        settings->NlaSecurity = FALSE;
        settings->EncryptionMethods = ENCRYPTION_METHOD_FIPS;
    }

Thanks.

log

2018-01-09 12:26:02.066 MacFreeRDP[65209:127461] void * _Nullable NSMapGet(NSMapTable * _Nonnull, const void * _Nullable): map table argument is NULL
[12:26:02:876] [65209:00323000] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
dyld: lazy symbol binding failed: Symbol not found: _FIPS_mode
Referenced from: /Users/AcidOrange/Desktop/kth/FreeRDP-master/_bin/winpr/libwinpr/Debug/libwinpr2.2.dylib
Expected in: flat namespace

dyld: Symbol not found: _FIPS_mode
Referenced from: /Users/AcidOrange/Desktop/kth/FreeRDP-master/_bin/winpr/libwinpr/Debug/libwinpr2.2.dylib
Expected in: flat namespace

(lldb)

**Comment by hwyl7676** [comment]
OpenSSL 1.0.2n  7 Dec 2017 and 1.0.2j

**Comment by akallabeth** [comment]
Looks like you have some compilation issue, could build and connect here. (There seems to be some kind of race with OpenSSL setup though)

Steps to compile:
* ```export PKG_CONFIG_PATH=$(brew --prefix)/opt/openssl/lib/pkgconfig```
* ```cmake .```
* ```cmake --build .```

**Comment by hwyl7676** [comment]
I use Cmake 3.7.0 GUI.

Then, proceed to add entry PKG_CONFIG_PATH = $ (brew - prefix) / opt / openssl / lib / pkgconfig and delete and cd to .bash_profile export PKG_CONFIG_PATH = $ (brew - prefix) / opt / openssl / lib / pkgconfig, configure and build it,

The results are the same.

**Comment by hwyl7676** [comment]
I use Cmake 3.7.0 GUI.

so,

1. Add Entry, PKG_CONFIG_PATH = $ (brew - prefix) / opt / openssl / lib /

2. Delete 1, and cd to ~ .bash_profile with export PKG_CONFIG_PATH = $ (brew - prefix) / opt / openssl / lib / pkgconfig and run configure and build

I did 1 or 2 times

The results are the same.

**Comment by akallabeth** [comment]
did you clean your git branch with ```git clean -xdf``` first? this sometimes gives issues.

**Comment by hwyl7676** [comment]
i did not use git clean because you cloned it using GitHub Desktop.

**Comment by hwyl7676** [comment]
Did I said the wrong answer?

**Comment by hwyl7676** [comment]
one more question, I wonder if 2.0.0-dev supports file clipboard.

**Comment by akallabeth** [comment]
@hwyl7676 does not matter, it is just to remove all files not found in git (cmake build config and stuff)

**Comment by hwyl7676** [comment]
Yes, I'll try and let you know the results.

**Comment by hwyl7676** [comment]
Thanks, It works without errors.
Does not the file clipboard work in 2.0.0?

**Comment by hwyl7676** [comment]
Thank you ~
It works without errors.
Does not the file clipboard work in 2.0.0?
Local-to-remote file clipping for xfreerdp #3905

**Comment by hwyl7676** [comment]
The reason for upgrading from 1.0.2 to 2.0 is due to the file clipboard.

**Comment by akallabeth** [comment]
@hwyl7676 That is xfreerdp only at this time.

**Comment by hwyl7676** [comment]
i See. Thank you for your kind answer.
