### ISSUE TITLE
There are many problems when importing "Studio" into Android Studio.

### ISSUE THREAD

**Issue by reverseAndroid** [FreeRDP/FreeRDP#4352]
After compiling "FreeRDP" and importing "Studio" into Android Studio, there were a lot of problems I didn't know how to solve.
[idea.log](https://github.com/FreeRDP/FreeRDP/files/1621310/idea.log)

**Comment by akallabeth** [comment]
This is an issue tracker not a support forum.
Please set up your development environment properly and read the documentation.
