### ISSUE TITLE
freerdp dumps core after connection failure

### ISSUE THREAD

**Issue by AloisSteindl** [FreeRDP/FreeRDP#4354]
The new release of xfreerdp dumps core after failing to  open a connection.
(For one server I regularly obtain the response 
[ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C],
but usually every third attempt succeeds.) 
If this error message appears - or if I supply an invalid password for a different server -, the program crashes with a core dump. I already unsuccessfully tried to send the core dump. It seems to happen immediately after unsuccessful connection attempts.

Steps to reproduce: Most simply: Try to connect to some server and give a wrong password.

command line: 
xfreerdp +clipboard /u:USERNAME /size:1400x950 /v:HOSTADDRESS

Connection to a Windows 10 system (works without problem for correct passwords)
The other machine is a Windows Server 2012 R2; here I usually have problems with the protocol security negotiation.

I expect to obtain some error message, but no crash with core dump.

This is FreeRDP version 2.0.0-dev2 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ONITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF TH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEOFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDPFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITDEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_MF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVEZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=OFF WITH_GFX_H26OFF WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=ON WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_U=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITHPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON TH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF TH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITHMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WH_XSHM=ON WITH_XTEST=OFF WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptis -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/reat/redhat-hardened-cc1 -m64 -mtune=generic -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-varble -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-cls -msse2
Compiler:            GNU, 7.2.1
Target architecture: x64

It is a fedora core 27, x64 system.

I hope that I provided sufficient information to resolve the issue.
With kind regards
Alois Steindl

PS.: The problem with the frequently occuring protocol negotiation is somewhat nastier; the funny thing is, that the connection succeeds quite precisely every third attempt.

**Comment by akallabeth** [comment]
Sounds like an issue recently fixed, could you check if the nightlies https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds are affected too?

**Comment by AloisSteindl** [comment]
Thank you,
that works now perfectly.
Just a remark: I had some trouble with installing the package: After creating the repo file, I obtained the error message, that the cache for that repo could not be refreshed (retranslated from german). Even a "dnf clean all" didn't help. It turned out, that there is not yet a directory for version 27, the rpms are still sitting in the directory for Fedora 26.
With best wishes
Alois

**Comment by bmiklautz** [comment]
@AloisSteindl thanks for the feedback. We haven't come around to update the Fedora build machines so we don't build them yet. But good to know that the 26 version work on 27 for now as well.

If the problem seems to be fixed on master (latest nightly) I'll close the issue.
