### ISSUE TITLE
No window decoration / CTRL+ALT-RETURN not working any more

### ISSUE THREAD

**Issue by abma** [FreeRDP/FreeRDP#4356]
to reproduce:

1. install freerdp-nightly from the official repository on debian 9.3 i386 with openbox:

freerdp-nightly                       2.0.0+0~20180109024828.469~1.gbpe1cc60 i386 

2. connect to a windows 2008 R2 server

xfreerdp /v:server /f /sec:rdp

press CTRL+ALT+RETURN

-> nothing happens. with an older version this made the window decorated.

xfreerdp /v:server /sec:rdp

the window decoration is missing to.

just a wild guess is #4319

**Comment by akallabeth** [comment]
@abma Tested with current nightly on openbox (debian stretch), no such issue at all...

**Comment by abma** [comment]
ah, i had this snipped in the openbox config:

` <applications>
       <application class="xfreerdp">
       <fullscreen>yes</fullscreen>
       </application>
</applications>`

in the older version of xfreerdp CTRL+ALT-RETURN etc. worked with the current version it failed with the config. removing the config made the current xfreerdp work as excepted.

**Comment by akallabeth** [comment]
@abma Ah, good to know it is working now and was a config error, would be a pain to rewrite the fullscreen detection yet again ^^
