### ISSUE TITLE
Procedures after compilation?

### ISSUE THREAD

**Issue by joshuaTTL** [FreeRDP/FreeRDP#4361]
Hi, guys

I'm pretty new to this and I'm just trying to get started. I followed the procedure to compile the files on my Mac, and then when I opened the MacFreeRDP, it's just a blank window with "ERROR" on the top and I can't do anything. Is there anything I possibly did wrong? And is there any instruction to follow after the compilation? I'm trying to connect my Mac with my Windows PC. Thanks so much!

**Comment by akallabeth** [comment]
Well, the client needs some parameters to start up correctly (just like the other clients)
Please use mailing list and/or IRC for further questions.
