### ISSUE TITLE
Connecting via RDP wipes out my kerberos credential cache

### ISSUE THREAD

**Issue by jmontleon** [FreeRDP/FreeRDP#4363]
While connecting to a Windows 10 system using Remmina on Fedora 27 x86_64 I noticed that each time I connected it wiped out my kerberos credential cache. Initially I filed a bug against Remmina ( https://github.com/FreeRDP/Remmina/issues/1439 ), but after further investigation I found that it was also happening using xfreerdp.

I rebuilt the freerdp packages with GSSAPI=OFF to fix a separate issue ( https://github.com/FreeRDP/FreeRDP/issues/4348 ) and found upon also reinstalling libwinpr it also stopped wiping out my credential cache on each reconnect.

rpm -q freerdp-libs freerdp libwinpr
freerdp-libs-2.0.0-35.20171220gitbfe8359.fc27.x86_64
freerdp-2.0.0-35.20171220gitbfe8359.fc27.x86_64
libwinpr-2.0.0-35.20171220gitbfe8359.fc27.x86_64

**Comment by scaronni** [comment]
Fix coming:

https://src.fedoraproject.org/rpms/freerdp/c/a876205f1737ecbb5a6f71e3db2da64bccbb3eca?branch=master

**Comment by scaronni** [comment]
I will close this issue as is specific to Fedora.

https://github.com/FreeRDP/FreeRDP/issues/4363

**Comment by scaronni** [comment]
#4348

**Comment by scaronni** [comment]
#4348 #

**Comment by letnab** [comment]
it doesn't work for me. 
Alt Linux
 xfreerdp cmd.rdp
[08:51:49:409] [8340:8341] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[08:51:49:409] [8340:8341] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[08:51:49:409] [8340:8341] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[08:51:49:409] [8340:8341] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rail
[08:51:49:410] [8340:8341] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: testuser
Domain:
Password:
[08:51:51:729] [8340:8341] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_LOGON_FAILURE [0x00020014]
[08:51:51:729] [8340:8341] [ERROR][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[08:51:51:729] [8340:8341] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[testuser@wstlinux Desktop]$ xfreerdp --buildconfig
This is FreeRDP version 2.0.0-dev2 (14997f9)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=OFF WITH_XRENDER=OFF WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU, 4.8.2
Target architecture: x64

**Comment by akallabeth** [comment]
@letnab Please check if they are at least somehow connected before posting. And please also do not post `me too` kind of stuff.

**Comment by sdrik** [comment]
The problem still exist on Archlinux with freerdp 2.0.0-rc4

**Comment by akallabeth** [comment]
kerberos rewritten for 3.0, closing.
