### ISSUE TITLE
FreeRDP Segfault 

### ISSUE THREAD

**Issue by Onoro** [FreeRDP/FreeRDP#4368]
I have a problem with FreeRDP. It's crashing during moving big parts of tables in MS Excell.
Server - Windows 7 x64
Clients - Debian 8 x64 

> Linux debian11 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
> This is FreeRDP version 2.0.0-dev2 (8f52c7ed8)

As you can see it's last version from your repository.
Launching command:
> /opt/freerdp-nightly/bin/xfreerdp /v:192.168.1.2 /f /bpp:32 /kbd:0x00000419 +menu-anims +window-drag +clipboard +auto-reconnect /gdi:sw +fonts /u:"user24" /p:"passs" 

log file
[free_m.log](https://github.com/FreeRDP/FreeRDP/files/1639070/free_m.log)

**Comment by Onoro** [comment]
And there are is second example, conditions are the same, but it's was an attempt to use old version of Freerdp.
FreeRDP version 2.0.0-dev2 (2f15b806f)

Commandline is 
/opt/freerdp-nightly/bin/xfreerdp /v:192.168.1.2 /f /bpp:32 /kbd:0x00000419 /u:"user24" /p:"passs" > /home/user24/free3.log

It's crashing while ctrl+c or right mouse button click> copy in MS Excell.

[free3.log](https://github.com/FreeRDP/FreeRDP/files/1639215/free3.log)

**Comment by akallabeth** [comment]
@Onoro Could you install ```apt-get install freerdp-nightly-dbg gdb``` and run your command line prefixed with ```gdb --args /opt/freerdp...```?
If the crash occurs the output of ```bt``` in ```gdb``` would help.

**Comment by Onoro** [comment]
ok, I'll do that tomorrow.

**Comment by hardening** [comment]
@Onoro you forgot ```bt``` to have the full stack trace

Anyway your backtrace is extremely strange as it's not possible to end-up in ```xf_cliprdr.c:1427``` with ```context=0x0,formatDataResponse=0x0```, we would have crashed long before.
So my guess is that in misc memory operations before line 1427, we trash the stack ending up with these zeros written at place where arguments are stored. It would be nice to add a breakpoint at the beginning of ```xf_cliprdr_server_format_data_response```, and check that before the segfault, context and formatDataResponse were correct...

Or perhaps you could do a run with valgrind, that may find the problematic line very quickly.

**Comment by akallabeth** [comment]
@Onoro Could you repost your trace, this time with the output after you typed ```bt```?
As for reproducibility, does it also occur when ```-clipboard``` is added to your command line?

**Comment by Onoro** [comment]
I can't provide any additional information because of strange thing.
When I'm trying to get backtrace log, PC freezes up and only way to fix it to reboot. 
Sequence of commands:
> gdb
> file /opt/freerdp-nightly/bin/xfreerdp
> set args /v:192.168.1.2 /f /bpp:32 /kbd:0x00000419 +menu-anims +window-drag /gdi:sw +fonts /u:"user24" /p:"passss"
> show args
> run

And after executing "run" and couple attempts to copy-past something in MS Excell, PC freezes up.
So I can't use 
> bt  

and have to reboot PC.
Any ideas how to get bt log?

I installed Reminna, as temporary solution of problem and it works fine.

**Comment by akallabeth** [comment]
Oh, that is bad, the keyboard is still captured by the application :/
Would still be interesting if ```-clipboard``` does fix the issue for you (your first gdb output suggests something like that)

**Comment by Onoro** [comment]
I'm sorry for late response, it looks like -clipboard helped to fix problem with my colleague's PC. 
So I'll wait couple days and close that issue if everything will be all right.
