### ISSUE TITLE
On the part of the Android mobile phone, when the mobile phone is flat screen, the system keyboard pops up to cause the activity black screen problem.

### ISSUE THREAD

**Issue by reverseAndroid** [FreeRDP/FreeRDP#4370]
In the afreerdp1.1 version, a problem was found. After connecting to the desktop, the keyboard pops up for the first time, no problem. However, if the keyboard is clicked for the second time. It will cause a black screen problem for the entire interface. When the keyboard is turned off, the page will return to normal. This problem only occurs on some phones. I compared the height of the keyboard pop-up of the Android I used to be higher than that of the other phones, which I think might be part of the reason.When SessionActivity creates a pop-up keyboard for the first time, it doesn't have a problem, it only happens the second time it pops up.

![132](https://user-images.githubusercontent.com/25810748/35087997-1ca8c5ea-fc6d-11e7-9d60-395e6d2e8cf7.jpg)

**Comment by akallabeth** [comment]
@reverseAndroid What do you mean by ```afreerdp1.1```? FDroid or google play builds or custom?

**Comment by reverseAndroid** [comment]
FreeRDP的1.1版本。就是“1.1 series second technology preview”这个版本中的android客户端。 @akallabeth

**Comment by reverseAndroid** [comment]
@akallabeth  @The 1.1 version of FreeRDP. It is the Android client in this version of "1.1 series second technology preview".

**Comment by reverseAndroid** [comment]
@akallabeth The 1.1 version of FreeRDP. It is the Android client in this version of "1.1 series second technology preview".

**Comment by akallabeth** [comment]
@reverseAndroid Ok, so please be a bit more specific. Which build? FDroid/Google/Custom?

**Comment by reverseAndroid** [comment]
@akallabeth At present, this Android client is a version of my own compilation, and it is not in the application store.

**Comment by akallabeth** [comment]
@reverseAndroid Ok, so does this also happen with current master/2.0 release candidates? 1.1 is quite old and will be obsolete soon.

**Comment by reverseAndroid** [comment]
Hello, I compiled version 2.0 does not work, so I use version 1.1. So I want to ask you to tell me how to correct this problem.

**Comment by akallabeth** [comment]
@reverseAndroid 2.0 is working fine and available via F-Droid, better go with that. (they have the build instructions too, if you encounter issues)
Fixing bugs in 1.1, you're on your own.

**Comment by reverseAndroid** [comment]
@akallabeth Hello, may I ask F-Droid is a forum or a software. I am sorry, I do not know what the F-Droid is.

**Comment by akallabeth** [comment]
https://f-droid.org an installation/management/update mechanism for open source software.

**Comment by reverseAndroid** [comment]
@akallabeth alright, thank you very much.

**Comment by reverseAndroid** [comment]
@akallabeth Hello, I have successfully run version 2.0, but there will still be a black screen problem. (In 2.0 should be called a white screen problem)The same test machine, and only appear on this kind of test machine.

**Comment by akallabeth** [comment]
@reverseAndroid Do you use the default settings? Deactivating all async options under debug might help (if not already done, there were some issues regarding those)

**Comment by reverseAndroid** [comment]
What does it mean? Is that I need to cancel all the properties in the settings?

**Comment by reverseAndroid** [comment]
@akallabeth What does it mean? Is that I need to cancel all the properties in the settings?
