### ISSUE TITLE
Many [-Wincompatible-pointer-types] in capabilities.c with latest master

### ISSUE THREAD

**Issue by gh-user-7392** [FreeRDP/FreeRDP#4372]
In latest master git version source file: libfreerdp/core/certificate.c has many warnings about incompatible pointer types in the certificate_read_x509_certificate() function. Not sure if you want to eliminate them by typecasting &length with (void*) or create a new typecast once.

FreeRDP version 2.0.0-dev2 (3c45a60)
Lubuntu 16.04.3
gcc version 5.4.0 20160609

**Comment by akallabeth** [comment]
Ok, didn't see your issue, but #4373 should be what you re looking for.
