### ISSUE TITLE
Client desktop taskbar stays on top of session when xfreerdp toggles full-screen after maximize 

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#4377]
Toggle full-screen using CTRL-ALT-ENTER and then minimizing the session works. However, when restoring the session and then toggling full-screen again shows the client taskbar on top of the remote session. Using the Layer menu of the UI decorations and forcing it to be on top solves the problem. However, this is not the correct behavior. 

Latest master git version does this. I have went back to a known working git version:
FreeRDP-097f8edd97735bc8df4bce6ee1605a4ac16b20e3

Lubuntu 14.04.5/16.04.3, amd64, openbox/xfce

/usr/local/freerdp/bin/xfreerdp /gfx +gfx-progressive /u:user /p:xyz -themes -wallpaper /f +clipboard /d:DOMAIN /sec:nla /cert-ignore /v:RDS-SERVER

Connecting to W2K12R2 RDS Server

This issue is also referenced in #4371 because the GFX mods causing the black screen may have something to do with this.

**Comment by gh-user-7392** [comment]
Update: with the latest commit (c276005), the original issues still exist using LXDE-based client Linux.
