### ISSUE TITLE
Nigthly build fails, seems related to PR 4328

### ISSUE THREAD

**Issue by Fantu** [FreeRDP/FreeRDP#4378]
Today I tried to build latest nightly build on rpi 3 with debian Stretch but it fails:
`
...
[100%] Generating xfreerdp.1
cd "/home/pi/Downloads/freerdp-nightly-2.0.0+0~20180124024836.476~1.gbp32cc6e/obj-arm-linux-gnueabihf/client/X11" && "/home/pi/Downloads/freerdp-nightly-2.0.0+0~20180124024836.476~1.gbp32cc6e/obj-arm-linux-gnueabihf/client/X11/generate_argument_docbook"
==6324==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
client/X11/CMakeFiles/xfreerdp.manpage.dir/build.make:67: set di istruzioni per l'obiettivo "client/X11/xfreerdp.1" non riuscito
make[3]: *** [client/X11/xfreerdp.1] Errore 1
`

I suppose is related to the commit 32cc6e16ef6e7148dac90502cb074366075f820d that probably need further additions.
From a fast search I not found other solution that manually add libasan path to LD_PRELOAD on debian/rules that FWIK is not a good idea.

Thanks for any reply and sorry for my bad english.

**Comment by bmiklautz** [comment]
@Fantu try disabling '-DWITH_SANITIZE_ADDRESS=ON' in packaging/deb/freerdp-nightly/rules

**Comment by akallabeth** [comment]
Building again.
