### ISSUE TITLE
In Nightly build,  the "/drive:*,hotplug" parameter no found.  

### ISSUE THREAD

**Issue by potatofamily** [FreeRDP/FreeRDP#4384]
In Nightly build,  the "/drive:*,hotplug" parameter no found.  and I use +drives , in "My Computer", I found a "media" directory, but nothing in it. parameter changed?

**Comment by akallabeth** [comment]
@potatofamily Looks like we broke the hotplug enable detection. ```+drives``` should work with the referenced pull.

**Comment by potatofamily** [comment]
@akallabeth thanks your reply, I will try it.
