### ISSUE TITLE
aFreeRDP2.0 paste problem

### ISSUE THREAD

**Issue by reverseAndroid** [FreeRDP/FreeRDP#4390]
I found it on aFreeRDP2.0 can not paste, I went to debug See SesssionActivity OnRemoteClipboardChanged (String data) this method, its data is a value, but I copy or cut the end of the string there will always be two Special characters. The point is that when I comment out the mClipboardManager.setClipboardData (data) in the OnRemoteClipboardChanged method, I have no problems with the paste.

**Comment by hardening** [comment]
I gues that kind of questions should be asked either on IRC or on the mailing list..

**Comment by reverseAndroid** [comment]
@hardening Well, I'm sorry, I am a novice and do not know where else to submit the questions.

**Comment by akallabeth** [comment]
@reverseAndroid Can past to the running session quite fine, could you elaborate under which conditions exactly does this behavior occur?

**Comment by reverseAndroid** [comment]
@akallabeth When using the mouse to copy and cut are no problem, but the paste is not paste, click paste has been blank. (Using the aFreeRDP function keyboard  Ctrl + c and Ctrl + x is no problem ,using Ctrl + v the same situation).

**Comment by reverseAndroid** [comment]
@akallabeth When using the mouse to copy and cut no problem, but the paste is not acceptable, click paste, the mouse cursor has been in place, no string paste up. (Using aFreeRDP keyboard Ctrl + c and Ctrl + x is no problem, use Ctrl + v will appear the same paste, the cursor has been in place, no string paste up).

**Comment by akallabeth** [comment]
@reverseAndroid Ah, ok now I get what you mean.
The direction android -> remote is working, but remote -> android has issues, is that correct?

**Comment by reverseAndroid** [comment]
@akallabeth Maybe, I am a novice, only know java this layer of things, little understanding of FreeRDP, I think it may be OnRemoteClipboardChanged and JNI interact in the emergence of the problem.

**Comment by akallabeth** [comment]
@reverseAndroid Looks like I found the bug, the terminating characters from the raw data were added in the UTF to java string conversion.

**Comment by reverseAndroid** [comment]
@akallabeth I do not really understand what you are saying. My ability is limited and I can not give you any more clues. very sorry.

**Comment by reverseAndroid** [comment]
@akallabeth I do not quite understand what you are saying. My ability is limited, I can not give you more clues. very sorry.
