### ISSUE TITLE
xfreerdp-gui

### ISSUE THREAD

**Issue by wyllianbs** [FreeRDP/FreeRDP#4399]
# [xfreerdp-gui](https://github.com/wyllianbs/xfreerdp-gui)

![xfreerdp-gui](https://user-images.githubusercontent.com/7172494/35774006-22c0c0b0-094a-11e8-8009-64f4d83904c1.png)

**URL:** https://github.com/wyllianbs/xfreerdp-gui

**Adapted from:** https://github.com/FreeRDP/FreeRDP/issues/1358#issuecomment-175075061

**Comment by akallabeth** [comment]
Nice one, did add my comments in https://github.com/wyllianbs/xfreerdp-gui/issues/1

**Comment by akallabeth** [comment]
@wyllianbs Anyway, closing this as it is not really an issue related to freerdp.
