### ISSUE TITLE
iOS  when create rdp session,session is nil and crush

### ISSUE THREAD

**Issue by MjzDk** [FreeRDP/FreeRDP#4401]
if(bookmark != nil)
		{	            
			// create rdp session
            RDPSession* session = [[[RDPSession alloc] initWithBookmark:bookmark] autorelease];
            UIViewController* ctrl = [[[RDPSessionViewController alloc] initWithNibName:@"RDPSessionView" bundle:nil session:session] autorelease];
            [ctrl setHidesBottomBarWhenPushed:YES];
            [[self navigationController] pushViewController:ctrl animated:YES];
            [_active_sessions addObject:session];
        }

When I was in the debug，I found session is nil, and the program crash.
iphone version 11.0.2  
ipad version 9.3.1

**Comment by aldopa** [comment]
I had the same problem using "Automatic" as screen size, that choice set width and height to 0 and during check of parameters fails one check on widht and height, as conseguence the session returned is nil and the app crashes

**Comment by Daintly** [comment]
@aldopa @MjzDk My question is still this question. Can you solve it? Xcode 9.4

**Comment by weihaigang** [comment]
顶 同样的问题

**Comment by saberge** [comment]
same problem

**Comment by akallabeth** [comment]
iOS is currently unmaintained, but pull requests are very welcome.

**Comment by maki0315** [comment]
same problem
