### ISSUE TITLE
cannot compile myrtille Freerdp

### ISSUE THREAD

**Issue by elich913** [FreeRDP/FreeRDP#4402]
H,

Hi, I get following error when building FreeRdp

2>tls.obj : error LNK2019: unresolved external symbol _BIO_meth_new referenced in function _BIO_s_rdp_tls
2>tcp.obj : error LNK2001: unresolved external symbol _BIO_meth_new
2>tsg.obj : error LNK2001: unresolved external symbol _BIO_meth_new
2>rdg.obj : error LNK2001: unresolved external symbol _BIO_meth_new
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_set_data referenced in function _transport_bio_buffered_new
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_get_data referenced in function _transport_bio_buffered_ctrl
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_set_init referenced in function _transport_bio_buffered_new
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_get_init referenced in function _transport_bio_simple_ctrl
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_set_shutdown referenced in function _transport_bio_simple_ctrl
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_get_shutdown referenced in function _transport_bio_simple_ctrl
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_set_next referenced in function _transport_bio_buffered_free
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_meth_set_write referenced in function _BIO_s_buffered_socket
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_meth_set_read referenced in function _BIO_s_buffered_socket
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_meth_set_puts referenced in function _BIO_s_buffered_socket
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_meth_set_gets referenced in function _BIO_s_buffered_socket
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_meth_set_ctrl referenced in function _BIO_s_buffered_socket
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_meth_set_create referenced in function _BIO_s_buffered_socket
2>tcp.obj : error LNK2019: unresolved external symbol _BIO_meth_set_destroy referenced in function _BIO_s_buffered_socket
2>certificate.c.obj : error LNK2019: unresolved external symbol _RSA_get0_key referenced in function _key_new_from_content

Please help

**Comment by bmiklautz** [comment]
@elich913 on the first glance it looks like you miss openssl. Please have a look to https://github.com/freerdp/freerdp/wiki/BugReporting and provide more information..

**Comment by elich913** [comment]
OK, thank you.
I installed free OpenSSL Win32OpenSSL-1_0_2n.exe
and checked the library path and SSL errors  disappeared
( I have OpenSSL before but another version)

but this BIO_meth_... error still remained, may be it depends of some other library ?

**Comment by akallabeth** [comment]
@elich913 No, these are part of OpenSSL. Check if the version detected is correct.
For further assistance please use IRC or mailing list.

**Comment by elich913** [comment]
OK, thank you, I just succeeded.
I compiled zip version of FreeRDP first 
it became OK after I did git clone...
