### ISSUE TITLE
How to install FreeRDP extensions

### ISSUE THREAD

**Issue by elich913** [FreeRDP/FreeRDP#4403]
Hi,

I cannot compile Myrtille FreeRDP and I see 
in Preprocessor definitions 
EXT_PATH="C:/Program Files (x86)/FreeRDP/lib/freerdp2/extensions"

Can somebody explain what is this and how to install these extensions.
I am missing them on my PC and may this cause to build problem

**Comment by hardening** [comment]
This is an issue tracker, for help or questions go on IRC or the mailing list.
