### ISSUE TITLE
ConvertColor broken: FreeRDPFreeRDPConvertColor

### ISSUE THREAD

**Issue by rozhuk-im** [FreeRDP/FreeRDP#4404]
https://github.com/FreeRDP/FreeRDP/commit/57958cb17827e1274b7c08c315e998b3b9050a8a#diff-8e0e0765a55abda4dfb8d2e186c1e42cR886

diff --git a/include/freerdp/codec/color.h b/include/freerdp/codec/color.h
index 59214cf2b..7e439522b 100644
--- a/include/freerdp/codec/color.h
+++ b/include/freerdp/codec/color.h
@@ -883,7 +883,7 @@ FREERDP_API BOOL freerdp_image_fill(BYTE* pDstData, DWORD DstFormat,
#if !defined(__APPLE__)
#define GetColorFormatName FreeRDPGetColorFormatName
#define GetColor FreeRDPGetColor
-#define ConvertColor FreeRDPFreeRDPConvertColor
+#define ConvertColor FreeRDPConvertColor
#endif

#ifdef __cplusplus

**Comment by bmiklautz** [comment]
@rozhuk-im thanks for the fix. Where did you hit this problem?

**Comment by hardening** [comment]
@rozhuk-im it would be so nice if you could submit a PR for that...

**Comment by rozhuk-im** [comment]
@hardening FreeRDP-WebConnect is very legacy, I do many changes that you may not accept and our git history in not well/clean - we try to make working prototype as fast as we can.
IMHO there is need to be rewritten at least 80% of all code.
Java code looks good (I do not dig dipper), but c++ part is ugly, especially communications with libfreerdp (ex.: sleep() in loop in per client thread, select() not used to pool fd).
IMHO, FreeRDP-WebConnect has no future as stand alone project/repo, it should be reworked to another one libfreerdp frontend and placed to FreeRDP repo.

For now, we have discussed it with my boss, he has no objections to publish our changes, but there is some things that unneeded in FreeRDP-WebConnect: windows support is dropped, cloudbase/EHS moved inside repo, cloudbase api replaced to ours private,... fixed some crashes and display issues. 
Same time on FreeBSD I can build FreeRDP-WebConnect using only cmake, without any strange bash scripts. Ubuntu requires that user some how install freerdp2 (not exist in default repos). cpprestsdk and boost also required for both OS.

As work around we will use:
#define FreeRDPFreeRDPConvertColor FreeRDPConvertColor

**Comment by hardening** [comment]
@rozhuk-im ha ha ha nice answer, anyway I was talking of a PR only containing the patch you showed us above :)

**Comment by rozhuk-im** [comment]
#4406

**Comment by akallabeth** [comment]
Merged your pull, thank you again.
