### ISSUE TITLE
Invoking 'ClipCursor' returned succ but seems do not take effect in wf_pre_connect

### ISSUE THREAD

**Issue by gifur** [FreeRDP/FreeRDP#4407]
I compile the wfreerdp-client on Windows x86 platform, and try to edit the code to achieve my own purpose. 

When I use `ClipCursor` api to resist the movable area of my mouse, the api return succ but take no effect. Then I create and run a simple executable program which only run `ClipCursor` api, it take effect. 

Keeping the simple program running, I run the wfreerdp.exe, What make me suprised is that the resitriction of cursor disappears ! What does the wfreerdp.exe do with the cursor position, I can't find out any significant api that **restore** the resistance like `SetCursorPos` , `SetCursor` 

Please help and reponse if you know something about that, Thank!

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
