### ISSUE TITLE
a number of warings in current master (2018-02-07): discards 'const' qualifier, incompatible pointer type

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#4410]
When I build the current master (a4a151aa1) for openSUSE (Tumbleweed with gcc 7.3 and Leap 42.3 with gcc 4.8) I get a number of warnings about "discards 'const' qualifier" and "incompatible pointer type". For details see the attached files.
The "incompatible pointer type" warnings are also caused by "const" vs. "not const".
[const_warnings.txt](https://github.com/FreeRDP/FreeRDP/files/1704092/const_warnings.txt)
[osTWbuild.log.20180207.zip](https://github.com/FreeRDP/FreeRDP/files/1704093/osTWbuild.log.20180207.zip)

**Comment by akallabeth** [comment]
Fixed with #4910
