### ISSUE TITLE
Single Linux Remote Application over FreeRDP

### ISSUE THREAD

**Issue by athenaNK** [FreeRDP/FreeRDP#4422]
Hello, 

I am new in FreeRDP and remote desktop. 
The last weeks I try to find if there is a way to run single Linux app over FreeRDP. 
Actually I need the same functionality as Windows RemoteApp offer. 

Just to mention that I use Apache Guacamole and I am interested in exposing just a single Linux app on the browser.

Thank you in advance!

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
