### ISSUE TITLE
transport_connect: getaddrinfo error

### ISSUE THREAD

**Issue by daivdedibuduo** [FreeRDP/FreeRDP#4424]
Today my xfreerdp complied from git has stopped working with the message

transport_connect: getaddrinfo (Errore temporaneo nella risoluzione del nome)                                                                                                                                     
Error: protocol security negotiation failure.
This happens whatever server i try to connect to (w2k3, w2008, w7)

Curiously if i try to connect with the "old" syntax it's all ok

example:
**xfreerdp /v:192.168.1.15**                                                                                                                                                   
Warning xf_GetWindowProperty (140): Property 433 does not exist                                                                                                                                                   
transport_connect: getaddrinfo (Errore temporaneo nella risoluzione del nome)                                                                                                                                     
Error: protocol security negotiation failure

**xfreerdp 192.168.1.15**
Warning xf_GetWindowProperty (140): Property 433 does not exist
connected to 192.168.1.15:3389
connected to 192.168.1.15:3389
connected to 192.168.1.15:3389

freerdp compiled from git on a pclinuxos machine fully updated.
I've recompiled freerdp but the problem is still here.

**Comment by akallabeth** [comment]
@daivdedibuduo That is strange, there is no such message `transport_connect: getaddrinfo` on current master, you sure you have the correct branch?

**Comment by akallabeth** [comment]
Best add the output of `xfreerdp /version` and `xfreerdp /buildconfig`

**Comment by daivdedibuduo** [comment]
AAAARRGHH !!! i've just noticed that on pclinuxos the install of vlc brings behind the installation of freerdp as a dependency (god knows why). But the pclinuxos freerdp version is 1.0.2 so i wasn't running the git version.
Really really excuse me for the noise, i'm really ashamed.
