### ISSUE TITLE
Missing and cut graphics

### ISSUE THREAD

**Issue by pachuco** [FreeRDP/FreeRDP#4439]
In certain programs, graphics will be cut or missing. Here, I used old windows Xchat and winXP MSPaint.
Expected behaviour: https://imgur.com/a/WzkiZ
Actual behaviour: https://imgur.com/a/DotAN

In Xchat, the activity indicator in the scrollback is cut short.
In MSPaint, the symbols/sizes for the other brushes are missing.

Host OS: Windows POSReady 2009(XP SP3 derivate) x86
Host RDP protocol supported: v7.0
Client OS: Windows 8 x86
Command used: wfreerdp profile.rdp /v:address:port /gdi:sw
Profile used: https://pastebin.com/60cNrpLd
Free RDP version: https://ci.freerdp.com/job/freerdp-nightly-windows/ win32, nr444 and nr446

**Comment by akallabeth** [comment]
That is commit 13be71381c2d1b9eb83b413e016e000bd75a9fc2
