### ISSUE TITLE
wfreerdp: incorrect fulscreen/window behaviour

### ISSUE THREAD

**Issue by pachuco** [FreeRDP/FreeRDP#4443]
1. After minimizing fullscreen wfreerdp and restoring it, pesky scrollbars appear on sides of the window.
The scrollbars offer scrolling for the extra width added by themselves.
This is averted if I click 'restore down' then 'maximize' before minimizing. No pests will appear.

2. Clicking 'restore down' while fullscreen produces an odd, undecorated window.
If you have the scrollbars from point 1 present and do the above, the window will be decorated instead.

Host OS: Windows POSReady 2009(XP SP3 derivate) x86
Host RDP protocol supported: v7.0
Client OS: Windows 8 x86
Command used: wfreerdp profile.rdp /v:address:port /gdi:sw
Profile used: https://pastebin.com/60cNrpLd
Free RDP version: https://ci.freerdp.com/job/freerdp-nightly-windows/ win32, nr446

**Comment by macron0** [comment]
This still happens in 3.0. Is there a fix?

**Comment by akallabeth** [comment]
@macron0 no, the windows client is still looking for a maintainer/tester
