### ISSUE TITLE
iFreeRDP on iPhone X / iPhone 8

### ISSUE THREAD

**Issue by aldopa** [FreeRDP/FreeRDP#4452]
Hi,
I tried to use iFreeRDP on iPhone X (iOS 11.2.2).
To have an accettable resolution I tried the /smart-sizing option but it doesn't work because the check params function require /w and /h options setted to positive values, but in that case the resolution is w x h dimension.

I used trunk version commit c276005 (pull request #4448)

Without  /smart-sizing iFreeRDP is unusable on iPhone X due to  view.bounds.size in landscape 568 x 320 that's an unusable resolution for a rdp.

Please help

**Comment by akallabeth** [comment]
`/smart-sizing` allows the output window to be scaled up/down. Of course you need to tell the RDP session the desired resolution with `/size:<width>x<height>` or `/w:<width> /h:<height>` to have internally.

**Comment by aldopa** [comment]
@akallabeth yes I used /smart-sizing with /size but iFreeRDP (iOS version) seems doesn't work perperly

I try to explain you with an example using xfreerdp on linux and iOS (iPhone X):

I used on linux xfreerdp /v:rdpserver /u:user /p:password /smart-sizing:568x320 /w:1136 /h:640
I obtain a session as expected, as you can see in image  session_freerdp_on_linux


![session_freerdp_on_linux](https://user-images.githubusercontent.com/34056780/36416322-0a5ec12a-1629-11e8-8196-0e15c71a70e9.jpg)

I used the same params on iOS version /smart-sizing:568x320 /w:1136 /h:640 but the session seems ignore /smart-sizing as you can see in session_freerdp_on_ios image. As you can see the desktop resolution is correct but doesn't fit on the device's dimensions (note where is the chrome icon, at the top left on ios instead on half lect as in linux session). It's the same as I use only /w:1136 /h:640 without /smart-sizing:568x320 (image session_freerdp_on_ios_without_smart)

![session_freerdp_on_ios](https://user-images.githubusercontent.com/34056780/36416544-930d58a6-1629-11e8-8d8f-31d639048bcd.jpeg)

![session_freerdp_on_ios_without_smart](https://user-images.githubusercontent.com/34056780/36416958-ebaf57b0-162a-11e8-86b1-635729231e12.jpeg)

**Comment by aldopa** [comment]
@akallabeth yes I used /smart-sizing with /size but iFreeRDP (iOS version) seems doesn't work perperly

I try to explain you with an example using xfreerdp on linux and iOS (iPhone X):

I used on linux xfreerdp /v:rdpserver /u:user /p:password /smart-sizing:568x320 /w:1136 /h:640
I obtain a session as expected, as you can see in image  session_freerdp_on_linux

![session_freerdp_on_linux](https://user-images.githubusercontent.com/34056780/36417178-7d28bdee-162b-11e8-93f5-9081c3d6e50d.jpg)

I used the same params on iOS version /smart-sizing:568x320 /w:1136 /h:640 but the session seems ignore /smart-sizing as you can see in session_freerdp_on_ios image. As you can see the desktop resolution is correct but doesn't fit on the device's dimensions (note where is the chrome icon, at the top left on ios instead on half lect as in linux session). It's the same as I use only /w:1136 /h:640 without /smart-sizing:568x320 (image session_freerdp_on_ios_without_smart). The output window is not scaled down

![session_freerdp_on_ios](https://user-images.githubusercontent.com/34056780/36417204-8efafd98-162b-11e8-9ea1-714740df5e47.jpeg)

![session_freerdp_on_ios_without_smart](https://user-images.githubusercontent.com/34056780/36417219-9612ad4c-162b-11e8-8e3b-09d4f919b7c3.jpeg)

**Comment by akallabeth** [comment]
@aldopa ah, that is what you mean. Well, if the iOS does not implement this function, then it would be great if someone could fix that.

**Comment by aldopa** [comment]
@akallabeth do you know if the smart-sizing is missing at all in ios version of freeRDP or if there is a bug to fix ? I ask this because the option smart-sizing is accepted from code, this sound me as an implementation of that option.
More generally, I noticed that problem with use of iFreeRDP is not limited to last iPhone models but it's present on all iPhone (not iPad). All iPhone have a dimension of screen in Points (used from iFreeRDP screen dimension) really poor, but they have the Rendered Pixels dimension that is Points dimension multiplied 2 or 3. On iPhone iFreeRDP appear with session resolution poor, equal to Points dimension. As you can see on following image the resolution (Points) used by iFreeRDP is too poor

![schermata 2018-02-21 alle 11 11 59](https://user-images.githubusercontent.com/34056780/36475085-e5c15e28-16f9-11e8-801d-5aa1f627dc3b.jpeg)

To increment the resolution I thought to smart-sizing, could you suggest me other ?

**Comment by akallabeth** [comment]
@aldopa From what I've seen from a short glance at the code that option is nowhere implemented (the command line/settings stuff is only a flag, the implementation must be done by the client)
iFreeRDP is currently not well maintained, so there are probably lots of bugs to fix.

**Comment by aldopa** [comment]
@akallabeth ok I understood. Could you tell me where I can find some documents about the structure of project (suppose I would find where is the part of code where it needs change to solve my problem). Just another question: do you know if is it possible to change dpi of the screen user by iFreeRDP ?

**Comment by akallabeth** [comment]
There are not a lot of documents for freerdp.
What you should keep in mind is:
* the `gdi` keeps a image (the content of the RDP session) and that is then somehow drawn by the client.
* `rdpSettings` contain all settings added by command line, etc
* `ios_freerdp.m` contains the callbacks the client must implement (mostly settings) along with the main loop
* `ios_freerdp_ui.m` keeps another set of callbacks, these are responsible for drawing and user input

other documentation is in the `docs` folder in the project root.

Most importantly, though, the XCode project files will always be generated by `CMake` so if you need to change settings, change them in `CMakeLists.txt` or `cmake/*` files.

**Comment by akallabeth** [comment]
@aldopa Yes, but please use IRC or mailing list for that.

**Comment by l937928908** [comment]
How do you get it to run on 64-bit systems? I've been testing unsuccessful at 11.2

**Comment by aldopa** [comment]
@l937928908 to compile for ios 11.2 (arm64) you must configure build settings for all target with "valid architecures" arm64 and "Architectures" arm64 and ios 11.2 (or anyway >= 10)

**Comment by arunkrishnamurthy** [comment]
Hi, could you please share the steps to build iFreeRDP app on macOS HighSierra with Xcode 9.2 version?

I tried the following steps:
1. cmake -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl" -DOPENSSL_LIBRARIES="/usr/local/opt/openssl/lib/" -DFOUNDATION_FRAMEWORK="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks" -DCOREGRAPHICS_FRAMEWORK="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks" -DSECURITY_FRAMEWORK="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks" -DUIKIT_FRAMEWORK="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks" -DSYSTEMCONFIGURATION_FRAMEWORK="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks" -DAPPLE=true -DIOS=true -Wno-dev -DREMOVE_DUPLICATES="" .
Output : -- Build files have been written to: /Users/user1/Desktop/FreeRDP2
2. make
Output:
Scanning dependencies of target winpr
[  0%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/synch/address.c.o
clang: warning: no such sysroot directory: '-g' [-Wmissing-sysroot]
In file included from /Users/krishnakumarcn/Desktop/FreeRDP2/winpr/libwinpr/synch/address.c:24:
/Users/krishnakumarcn/Desktop/FreeRDP2/winpr/include/winpr/synch.h:25:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
         ^~~~~~~~~
1 error generated.
make[2]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/synch/address.c.o] Error 1
make[1]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/all] Error 2
make: *** [all] Error 2

Could anyone help me to build this app?

**Comment by akallabeth** [comment]
@arunkrishnamurthy You need to add OpenSSL to your compile steps, using the one from MacOS will not work.

**Comment by arunkrishnamurthy** [comment]
@akallabeth I'm not using the OpenSSL which is preloaded with MacOS. I've downloaded, build and installed it from https://www.openssl.org/.

The issue is not while configuring the build using 'cmake'.

The issue comes when I try to build the binary using the 'make' command.

The error log is as below : 

Scanning dependencies of target winpr
[ 0%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/synch/address.c.o
clang: warning: no such sysroot directory: '-g' [-Wmissing-sysroot]
In file included from /Users/krishnakumarcn/Desktop/FreeRDP2/winpr/libwinpr/synch/address.c:24:
/Users/krishnakumarcn/Desktop/FreeRDP2/winpr/include/winpr/synch.h:25:10: fatal error: 'stdio.h' file not found
#include <stdio.h>
^~~~~~~~~
1 error generated.
make[2]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/synch/address.c.o] Error 1
make[1]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/all] Error 2
make: *** [all] Error 2

**Comment by informatimago** [comment]
It looks like you replaced the whole include list with the include for your OpenSSL. Did you use the -isysroot or -sysroot option? You should specify libraries includes adding a -I option.

**Comment by akallabeth** [comment]
@arunkrishnamurthy There are no iOS related downloads for OpenSSL, so you need to compile. There is a helper script in the `scripts` folder of `FreeRDP` but your mileage may vary. Read the stuff in the `docs` folder to get an idea.

**Comment by arunkrishnamurthy** [comment]
@akallabeth @informatimago Thanks for the support, I was able to cmake the project for Xcode. But I'm facing issues in building the project in Xcode. 

When I tried to build the project on the Xcode version 9.1, there were target issues. Please find the image below:
![screen shot 2018-04-03 at 10 35 38 am](https://user-images.githubusercontent.com/5329881/38230433-777e7f34-372b-11e8-979c-243c6161d55f.png)

When I tried to build the project on the Xcode version 7.3.1, there was some error in the system libraries. Please find the image below:
![screen shot 2018-04-03 at 10 10 54 am](https://user-images.githubusercontent.com/5329881/38230469-a9754374-372b-11e8-9508-157b2abb5cb0.png)

Any help is appreciated.

**Comment by aldopa** [comment]
@arunkrishnamurthy as you can see in first image (xcode 9) you ask to compile for arch i386 (-arch i386) but you use SDK 11.1 and apple stop support i386 architecture since 11.0, last ios version supporting 1386 is the 10.x (see http://iossupportmatrix.com).

You have simply set building options to build for arc x64 if you have target ios 11.x and use SDK 11.1.
If you want support older ios and arch i386 you must use an SDK version 10 (max) and have target ios 10

**Comment by mailinglists35** [comment]
>  aldopa commented on Feb 19 
> Please help

Microsoft's native free RDP client for IOS keeps the remote resolution and also gives you a zoom button.

**Comment by wangyukun** [comment]
hello.I want to get your help. I am from China. Can I contact you via email or WeChat.

**Comment by wangyukun** [comment]
> @arunkrishnamurthy as you can see in first image (xcode 9) you ask to compile for arch i386 (-arch i386) but you use SDK 11.1 and apple stop support i386 architecture since 11.0, last ios version supporting 1386 is the 10.x (see http://iossupportmatrix.com).
> 
> You have simply set building options to build for arc x64 if you have target ios 11.x and use SDK 11.1.
> If you want support older ios and arch i386 you must use an SDK version 10 (max) and have target ios 10

hello.I want to get your help. I am from China. Can I contact you via email or WeChat.

**Comment by wangyukun** [comment]
@aldopa hello.I want to get your help. I am from China. Can I contact you via email or WeChat.
