### ISSUE TITLE
FreeRDP 2.0 random disconnect - log included

### ISSUE THREAD

**Issue by frondlu** [FreeRDP/FreeRDP#4456]
Hey guys,

Before writing this new ticket, I made sure to checkout the exising bugs.  This particular issue has similarities with ticket #3518; however, the logs are not identical.

Decription of the bug:  
Users will be in connected to a windows server 2016 Datacenter V1607 Build 14393.2035 64bit server with a freeRDP 2.0 connection that is configured via a stratodesk OS (2.40.2356d-EEfs-k404_amd64-171123) and all of a sudden, the connection will disconnect.  The logs can be found in the logs section below.

Connection settings in stratodesk:
FreeRDP version: 2.0
Disable NLA: on
Disable Standard RDP encryption: on
Color Depth: 32bit
Remote FX: on
Remote FX mode: default
Enable NSCodec: on

Logs:
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:128] [4454:4456] [ERROR][com.winpr.timezone] - Unable to find a match for unix timezone: Canada/Atlantic 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [11:02:46:904] [4454:4456] [ERROR][com.freerdp.core.fastpath] - FASTPATH_UPDATETYPE_SURFCMDS - update_recv_surfcmds() - -1 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [11:02:46:904] [4454:4456] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data: fastpath_recv_update() - -1 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [11:02:46:904] [4454:4456] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [11:02:46:904] [4454:4456] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [11:02:46:904] [4454:4456] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [11:02:46:904] [4454:4456] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:098] [4454:4456] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:098] [4454:4456] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:098] [4454:4456] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:111] [4454:4456] [INFO][com.freerdp.crypto] - creating directory /root/.config/freerdp 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:111] [4454:4456] [INFO][com.freerdp.crypto] - creating directory [/root/.config/freerdp/certs] 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:111] [4454:4456] [INFO][com.freerdp.crypto] - created directory [/root/.config/freerdp/server] 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:218] [4454:4456] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:218] [4454:4456] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:224] [4454:4456] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:225] [4454:4461] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service printer [lab-dymo] (static)
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:225] [4454:4461] [INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [Z] (static) 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:33:232] [4454:4462] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:57:996] [4454:4461] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: PRN1 (type=4 id=1) 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [14:19:57:996] [4454:4461] [INFO][com.freerdp.channels.rdpdr.client] - registered device #2: Z (type=8 id=2) 
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: [11:02:46:904] [4454:4456] [INFO][com.freerdp.client.x11] - Network disconnect!
Feb 12 11:02:46 NTD00012E4C34F6 user.notice root: FreeRDP's Exitcode: 0 Feb 12 11:03:20 NTD00012E4C34F6 daemon.info ntpd[2940]: Soliciting pool server 209.87.233.53 
Feb 12 11:04:26 NTD00012E4C34F6 daemon.info ntpd[2940]: Soliciting pool server 209.87.233.53 
Feb 12 11:05:30 NTD00012E4C34F6 daemon.info ntpd[2940]: Soliciting pool server 209.87.233.53 
Feb 12 11:06:34 NTD00012E4C34F6 daemon.info ntpd[2940]: Soliciting pool server 209.87.233.53

**Comment by T3N4K4** [comment]
Seems still to be the /rfx - fastpath error.

**Comment by frondlu** [comment]
Note:

The logs date back to February 12th,  that's when I contacted Stratodesk and haven't heard from them since.  I've pasted the logs from the ticket I've submitted to them.  The same error logs happen regularly.

**Comment by akallabeth** [comment]
Just like @T3N4K4 said, this is the same protocol error which we can not locate exactly (or even if it is a server or client issue).
That said, why are you using `/rfx` with server 2016, `/gfx` options should be the far superior option (and they use a different code path, so it may be a solution for your specific issue too)

**Comment by akallabeth** [comment]
Ok, this is a dupliacte (the logs/issue are the same with some changes done over time)
See #3518 for updates.
