### ISSUE TITLE
Audio problem

### ISSUE THREAD

**Issue by aleSBT** [FreeRDP/FreeRDP#4460]
We have a problem with audio in xfreerdp using X2goclient.
We use the /audio:sys:alsa in parameter, connecting to a win server 2012, but when we start sound on the remote desktop, we hear nothing. changing and returning to console (Cctrl-alt-F1) enable the sound. Seems that sound doesn't work with the xmode enabled. Suggests?

**Comment by akallabeth** [comment]
You're using it wrong ^^
`/audio-mode:<mode>` takes a number as argument (0 ... local, 1 ... remote or 2 ... off)
`/sound` enables sound playback on the client (preferred)

there is no parameter `/audio` at least not with freerdp from this repo.
