### ISSUE TITLE
Freerdp 2.0 Dev Sound Recording Choppy in 3CXPhone SoftPhone

### ISSUE THREAD

**Issue by ppokhriyal** [FreeRDP/FreeRDP#4465]
While passing the below command i am not able to make smooth recording in SIP phone 3CXPhone

xfreerdp /cert-ignore /u:xxx /p:xxx /d:xxx /sound:sys:pulse /microphone:sys:pulse /v:xxx

**Comment by akallabeth** [comment]
Please provide a minimal amount of information.
The command line is a good start, but that you activated sound and microphone redirection is a given.

**Comment by ppokhriyal** [comment]
@akallabeth 

i am using Jack Head-Seats.even passing the sound and microphone parameters,still i find glitches in 3CX SIP Phone sound recording test.

**Comment by akallabeth** [comment]
@ppokhriyal You could provide a few details of your setup.
* Software versions
* Network connection
* ...

**Comment by ppokhriyal** [comment]
FreeRDP Version 2.0.0 Dev-2
FreeRDP Session Windows Server 2012 TS
3CXPhone application is installed on the WIN-2K12 TS
Network Connection : LAN

After taking the freerdp session of WIN-2K12 TS using the above mentioned parameters,

Follow the following steps

Invoke 3CXPHONE and dial *777
After dialing ,if you start to speak you fill  hear lots of echo and glitches from your Jack HeadSeat

*Note : If i make recording through default sound recorder of windows i don't find any difficulties.

**Comment by akallabeth** [comment]
@ppokhriyal Ok, that is some information we can work with.
Can you / have you tested the same setup using another windows machine and MSTSC?
Does local recordings (where you run `xfreerdp`) also have these glitches/echo?
This would be a good test to narrow down the possible sources of the issue.

**Comment by ppokhriyal** [comment]
> With WIN-10 MSTSC its working fine with minor disturbances.
> Local recording is working fine
I am using Logitech Analog Headsets

**Comment by akallabeth** [comment]
Ok, then the surroundings are sound.
I've been working on improving the sound channels with #4453, maybe you can give it a try.
It is not completed yet, but working fine with some limitations on my test machines.
(There are some combinations of client/server that are still not working, so be aware of that)

**Comment by akallabeth** [comment]
@ppokhriyal any update?

**Comment by ppokhriyal** [comment]
@akallabeth NO LUCK..tried with rc1
