### ISSUE TITLE
Windows 8 and 10 (color pointers) cursors are drawn inverted (black) in wfreerdp

### ISSUE THREAD

**Issue by perkerk** [FreeRDP/FreeRDP#4474]
Windows 8, Windows 10 and custom pointers are not drawn correctly in wfreerdp. These cursors have the transparent background correct, but the pointer color is drawn black.

The problem is 32bpp color cursors are not rendered correctly in wf_Pointer_New. The most obvious issue is the _aligned_malloc of the xor data uses GetBitsPerPixel() instead of GetBytesPerPixel() to calculate scanline length which allocates a buffer 8x too big, so the flip of the scanlines in freerdp_image_copy_from_pointer_data() creates an xor-image that does not align with the monochrome and-mask data.

Also, not using PIXEL_FORMAT_BGRX32 for 32bpp in freerdp_image_copy_from_pointer_data() may cause problems with the xorPixel checks later for transparent or inverted pixels.

**Comment by perkerk** [comment]
It looks like the other problem is CreateBitmap isn't creating bitmaps for the cursor that are compatible with the display. CreateDIBSection does work

**Comment by akallabeth** [comment]
@perkerk Is this fixed with #4552?

**Comment by perkerk** [comment]
@akallabeth Yes that was the fix. I'll go ahead and close this. Is there any protocol for closing issues (other than just closing them)?

**Comment by akallabeth** [comment]
Just reference the issue in the commit message or pull request description
