### ISSUE TITLE
The frame in Android app is low when i use anim in Windows.

### ISSUE THREAD

**Issue by mandome** [FreeRDP/FreeRDP#4479]
Hi, i use this lib in android device. And i play a ppt in windows which has some switch animations. In version 1.1.0, it's normal, but in newest version, it's too slow. Can you help me solve this problem?

**Comment by akallabeth** [comment]
@mandome Would need a lot more information from your setup.
Please use the mailing list/IRC to get into contact.

**Comment by mandome** [comment]
@akallabeth  I find the reason but don't know how to solve.When PowerPoint has some animations, the old version can current detect the x, y, width, height on method: void OnGraphicsUpdate(int x, int y, int width, int height).But in newest version, it always return x:0, y:0, width:1920, height:1080.
I just run the default apk on F-Droid and not setting any parameters.
My android device is Android TV,1920x1080,version 21.

**Comment by mandome** [comment]
@akallabeth  Can you give me the newest .so file? I cann't build the project well.Thanks.
