### ISSUE TITLE
can not skip some frame and end the anim immediately

### ISSUE THREAD

**Issue by mandome** [FreeRDP/FreeRDP#4484]
I play a windows PowerPoint on Android device, i want to touch the screen and end the anim immediately.But it only ends when all the animations are finished.
I run the demo on https://github.com/huzongyao/aFreeRDP, it's ok but no sound.
How can i set?
My android device : arm64, api21.
PC : win7 and no graphics.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
