### ISSUE TITLE
New Milestone 2.0-rc2

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#4489]
Lot's of things have been fixed since the last milestone, esp. #4486. Would be great to have a new version for integrating into distributions!

**Comment by shadowbq** [comment]
We really need an RC tag for Apache Guacamole Integration.

https://issues.apache.org/jira/browse/GUACAMOLE-249

**Comment by joakim-tjernlund** [comment]
yes please, the RC's are too few and long apart

**Comment by akallabeth** [comment]
Trying to get a `2.0.0-rc2` out, but would need some feedback to open pull requests targeted at that milestone.
So, to anyone who can help, feedback is appreciated and can speed up things a lot ;)
