### ISSUE TITLE
Use aFreeRDP2.0 to connect win7 operating system, the desktop display is white.

### ISSUE THREAD

**Issue by reverseAndroid** [FreeRDP/FreeRDP#4492]
Use aFreeRDP2.0 to connect win7 operating system, the desktop display is white, point to open the system's other function window, in addition to the icons are white, it affects the user, I ask this is the underlying code problem?

**Comment by akallabeth** [comment]
Please be a bit more descriptive of your issue.
As a start, please read https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by reverseAndroid** [comment]
I seem to find the root cause of the problem, because I have enabled the GFX attribute, win7 does not seem to support this attribute, so led to abnormal screen display, is normal under win10.
