### ISSUE TITLE
Multimon option does not work with .rdp config file

### ISSUE THREAD

**Issue by rsclafani** [FreeRDP/FreeRDP#4496]
**Host OS:** Ubuntu 16.04.4 LTS // 4.4.0-116-generic // x86_64
**Target OS:** Windows 7 Ultimate
**FreeRDP version:** 2.0.0-dev2 (n/a)
Installed via `apt-get upgrade`

**Command:** `xfreerdp /home/user/remote.rdp /multimon`
**Expected behavior:** Use `.rdp` config file with `/multimon` option to open connection on multiple monitors. Behavior worked before upgrade to `2.0.0-dev2`.
**Actual behavior:** Terminal presents usage/help text with no clear exception information

(Redacted) Content of `remote.rdp`:
```
username:s:domain.local\rsclafani
disable wallpaper:i:0
full address:s:name.domain.local
```

**Command:** `xfreerdp /home/user/remote.rdp` works as expected. Opens in small window version

**Command:** `xfreerdp /multimon /v:name.domain.local /u:domain.local\\rsclafani` works as expected. Opens in multi-monitor full screen.

**Command:** `xfreerdp /multimon /v:name.domain.local /d:domain.local /u:rsclafani` also works as expected. 

**Command:** `xfreerdp /home/user/remote2.rdp /multimon` does not work -- returns usage text
`/home/user/remote2.rdp`:
```
username:s:rsclafani
domain:s:domain.local
full address:s:name.domain.local
```

**Comment by akallabeth** [comment]
#4477 should address your issues.
