### ISSUE TITLE
freerdp-nighly repository outdated

### ISSUE THREAD

**Issue by trekkie3k** [FreeRDP/FreeRDP#4500]
The repository at least for Debian stretch of freerdp-nightly is outdated.

Information on the repositories and latest builds can be found here: https://ci.freerdp.com/job/freerdp-nightly-binaries/

The latest build for Debian stretch right now is

freerdp-nightly_2.0.0+0~20180320024828.499~1.gbp103686_amd64.deb

The Debian repository, mentioned on the same page, does not have this build but was last updated on the 15th of February, more than a month ago.

**Comment by rene1977** [comment]
Looks like disk space is full.

Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE

Thats really .... because of the CredSSP patch.

**Comment by bmiklautz** [comment]
@rene1977 wrong guess ;). We recently added bionic to our nightly builds and it still doesn't build through. And if not all packages work we don't updated the repositories.
@trekkie3k thank you for the report. We aware on it and fixit asap.

**Comment by akallabeth** [comment]
nightlies are back up again, thanks to @bmiklautz
