### ISSUE TITLE
auto-reconnect channels broken

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#4511]
Currently the autoreconnect is broken for channels.
This can even lead to segmentation faults.

**Comment by mmorvai** [comment]
We are observing different problems with the current build with different channels. We get segfaults with serial port redirection, have problems with the audio channel and some custom channel drivers. It could be related with this issue, but I am not sure. Could you explain the problem in a bit more detail and how we could make sure that our problems are related?

Thanks.

**Comment by akallabeth** [comment]
@mmorvai 
There are 2 issues:
1. `freerdp_reconnect` does not properly disconnect and reconnect the channels, so the state is not restored after a reconnect
1. The channels do not handle `connect` `disconnect` events properly (there may be several disconnect events) and frees up resources twice
1. The channel disconnect functions do sometimes clean up resources that should be available during the init/terminate scope

**Comment by akallabeth** [comment]
@mmorvai So, to fix the `connect` and `disconnect` channel related issues you need to check the `OpenHandle` is actually valid and that resources allocated in `connect` are cleaned up in `disconnect` and `initialize` allocated stuff eliminated in `terminate`
