### ISSUE TITLE
unable to connect to windows domain joined host using Kerberos

### ISSUE THREAD

**Issue by lazyruss** [FreeRDP/FreeRDP#4525]
connecting with IP address (which implies NTLM) is fine
connecting with hostname or FQDN fails after commit #7bbc3cb8b799fe046bbf63c9a9cb74776d7786a7 
traces from server indicate that freerdp  sends AcceptCompleted, and server responds with Alert(21) 

i'm attaching logs for both cases
[fqdn_with_rc2_03212018.txt](https://github.com/FreeRDP/FreeRDP/files/1864987/fqdn_with_rc2_03212018.txt)
[ip_with_rc2_03212018.txt](https://github.com/FreeRDP/FreeRDP/files/1864988/ip_with_rc2_03212018.txt)

**Comment by akallabeth** [comment]
Looks a lot like the recent NLA update related issues.
Does this also occur with current master?

**Comment by lazyruss** [comment]
I was bisecting it week ago, so up to 3/23 for sure.

**Comment by akallabeth** [comment]
@lazyruss commit? #4510 did fix the nla stuff

**Comment by lazyruss** [comment]
iirc, commit ff59cf028c6a85566be0471451c0329906e1f718 works.
next merge broke it. Its probably not the exact commit mentioned - but that's what I got by git bisect

**Comment by akallabeth** [comment]
@lazyruss so, did you try with a version that contains #4510? Ms did fix some NLA security issue and that pull fixes that in FreeRDP.
The bisect stuff you mentioned are not really authentication specific and I can't check that from mobile.

**Comment by lazyruss** [comment]
happens with latest master (commit #e03333477a98f4e39f0a68be63157b6e7879b055)

**Comment by akallabeth** [comment]
Ok, so this is different.
Since we tested with domain machines there are 2 options:
1. #4519 is pending merge and is related
1. your setup has something we did not cover. If you can please add a description of your setup? Will check against our setup tomorrow

**Comment by lazyruss** [comment]
my setup is typical windows based corpnet, with freerdp code running on windows 10. and targets are various domain joined windows servers, and windows 10 too.

**Comment by mfleisz** [comment]
@lazyruss As @akallabeth already pointed out - can you give #4519 a try and see if it works with that fix applied. Looking at the failing log I think it might fix your issue.

**Comment by lazyruss** [comment]
@mfleisz tested with up-to-date code (up to #807fe0413b2cfc4cd0f4baf43a2c9bbc7483c52c), getting same error.

**Comment by akallabeth** [comment]
@lazyruss had a look at your logs again. seems like you're testing with a custom client? so, could you check if it work with plain `xfreerdp` to ensure we're not hitting something else here?

**Comment by lazyruss** [comment]
@akallabeth I was using wfreerdp lately since it's quicker

**Comment by bmiklautz** [comment]
@lazyruss would you be so kind and post us a the `xfreerdp /buildconfig`

**Comment by lazyruss** [comment]
@bmiklautz wfreerdp /buildconfig - had to run in debugger since redirect did not work
This is FreeRDP version 2.0.0-dev2 (09334981)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_X264=OFF
Build type:          Debug
CFLAGS:               /DWIN32 /D_WINDOWS  /utf-8 /MP /Gd /W3 /Zi
Compiler:            MSVC, 19.12.25835.0
Target architecture: x86

**Comment by lazyruss** [comment]
@bmiklautz wfreerdp /buildconfig (had to run it in debugger since redirecting stdout/stderr did not work)
This is FreeRDP version 2.0.0-dev2 (09334981)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_X264=OFF
Build type:          Debug
CFLAGS:               /DWIN32 /D_WINDOWS  /utf-8 /MP /Gd /W3 /Zi
Compiler:            MSVC, 19.12.25835.0
Target architecture: x86

**Comment by akallabeth** [comment]
@lazyruss that commit does not exist, could you try with an actual build from our repo? or better yet, try that with our nightly builds if possible.

**Comment by lazyruss** [comment]
This is FreeRDP version 2.0.0-dev2 (55973288f)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=ON WITH_DEBUG_CAPABILITIES=ON WITH_DEBUG_CERTIFICATE=ON WITH_DEBUG_CHANNELS=ON WITH_DEBUG_CLIPRDR=ON WITH_DEBUG_DVC=ON WITH_DEBUG_KBD=ON WITH_DEBUG_LICENSE=ON WITH_DEBUG_MUTEX=ON WITH_DEBUG_NEGO=ON WITH_DEBUG_NLA=ON WITH_DEBUG_NTLM=ON WITH_DEBUG_RAIL=ON WITH_DEBUG_RDP=ON WITH_DEBUG_RDPDR=ON WITH_DEBUG_RDPEI=ON WITH_DEBUG_REDIR=ON WITH_DEBUG_RFX=ON WITH_DEBUG_RINGBUFFER=ON WITH_DEBUG_SCARD=ON WITH_DEBUG_SND=ON WITH_DEBUG_SVC=ON WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=ON WITH_DEBUG_TIMEZONE=ON WITH_DEBUG_TRANSPORT=ON WITH_DEBUG_TSG=ON WITH_DEBUG_TSMF=ON WITH_DEBUG_WND=ON WITH_DEBUG_X11=ON WITH_DEBUG_X11_CLIPRDR=ON WITH_DEBUG_X11_LOCAL_MOVESIZE=ON WITH_DEBUG_XV=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_X264=OFF
Build type:          Release
CFLAGS:              /DWIN32 /D_WINDOWS  /Gd /W3
Compiler:            MSVC, 19.12.25835.0
Target architecture: x86

**Comment by akallabeth** [comment]
@lazyruss Log please? It is hard to guess since you do not provide any more details to your setup and you only provided a log at the beginning (corresponding to which version?)

**Comment by akallabeth** [comment]
@lazyruss Oh, and before I forget, which version of OpenSSL are you using? It may not be a freerdp but a openssl issue (too old/wrong cipher spec/...)

**Comment by akallabeth** [comment]
Ok, verified, current nightly builds use a very outdated OpenSSL version.
Compiling with a newer one does resolve this issue.
@bmiklautz could you update the OpenSSL version for the windows build machine?

**Comment by lazyruss** [comment]
i was using OpenSSL 1.0.2n (whatever was available in vcpkg) Updating to 1.0.2o made no difference.
same failure after sending SEC_E_OK token.

**Comment by akallabeth** [comment]
@lazyruss @haklin0816 Could you check the following entries in your `CMakeCache.txt`:
* `OPENSSL_INCLUDE_DIR`
* `OPENSSL_ROOT_DIR`
* `LIB_EAY_*`
* `SSL_EAY_*`

They should point to the directory you have your openssl build in.
If you don't use static OpenSSL, ensure that during runtime the correct library is used.

**Comment by lazyruss** [comment]
@akallabeth 
Points to:
Package: openssl
Version: 1.0.2o-1
Architecture: x86-windows

**Comment by haklin0816** [comment]
Win32 OpenSSL v1.1.0h From http://slproweb.com/products/Win32OpenSSL.html

**Comment by akallabeth** [comment]
So, could you please post the actual content of these variables? Testing with the SSL version from @haklin0816 reveals that it is NOT detected automatically.

**Comment by haklin0816** [comment]
Hi,
I'm starting to wonder if these two issues are even related? This issue, and my closed one  #4537.
My problem is not so much related to what I'm connecting to, but more from what. I can connect to hosts from  windows 7/10 that fails windows server 2012r2/2016 using same wfreerdp and switches. A failed example below using "/log-level:DEBUG > c:\temp\log.txt" from a Windows 2012 R2 server. Notice the "Main thread exited with 131075". Is this the same error you get @lazyruss?

[13:42:14:484] [956:00000578] [DEBUG][com.freerdp.core.gcc] - Server rdp encryption method: NONE
[13:42:14:689] [956:00000578] [DEBUG][com.freerdp.core.rdp] - recv Synchronize Data PDU (0x1F), length: 22
[13:42:14:689] [956:00000578] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
[13:42:14:689] [956:00000578] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
[13:42:14:689] [956:00000578] [DEBUG][com.freerdp.core.rdp] - recv Font Map Data PDU (0x28), length: 26
[13:42:14:689] [956:00000578] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[13:42:14:689] [956:00000578] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[13:42:14:703] [956:00000578] [DEBUG][com.freerdp.client.windows] - Main thread exited with 131075
[13:42:14:703] [956:00001240] [DEBUG][com.freerdp.client.windows] - Keyboard thread exited.

**Comment by lazyruss** [comment]
@akallabeth 
OPENSSL_ROOT_DIR - not in cmakecache.txt
( set externally before running cmake, i.e.:
```
set OPENSSL_ROOT_DIR=C:\Git\vcpkg\packages\openssl_x86-windows
C:\Git\vcpkg\downloads\cmake-3.10.2-win32-x86\bin\cmake.exe .

```)
```
OPENSSL_INCLUDE_DIR:PATH=C:/Git/vcpkg/packages/openssl_x86-windows/include
LIB_EAY_DEBUG:FILEPATH=C:/Git/vcpkg/packages/openssl_x86-windows/lib/libeay32.lib
LIB_EAY_RELEASE:FILEPATH=C:/Git/vcpkg/packages/openssl_x86-windows/lib/libeay32.lib
SSL_EAY_DEBUG:FILEPATH=C:/Git/vcpkg/packages/openssl_x86-windows/lib/ssleay32.lib
SSL_EAY_RELEASE:FILEPATH=C:/Git/vcpkg/packages/openssl_x86-windows/lib/ssleay32.lib
```

only ssl 1.0.1 can be used because SSL 1.1.0 library names are not recognized

**Comment by akallabeth** [comment]
@lazyruss And how did you use `1.0.2o-1`? `1.1.0` versions work fine (with FreeRDP) looks like it is necessary to adjust the `NAMES` in `cmake/FindOpenSSL.cmake` `FIND_LIBRARY` for windows builds.
Anyway, which version were you now actually using? `1.0.1` (which?), `1.0.2o-1`?

**Comment by lazyruss** [comment]
@akallabeth 1.0 vs 1.1, to be exact. As I said, started building with 1.0.2o about a week ago, before that - 1.0.2n

**Comment by akallabeth** [comment]
@lazyruss Took some time, but the nightlies are up and running again (for windows that is). Could you check against current build #481 if that is still an issue for you?

**Comment by lazyruss** [comment]
@akallabeth still failing, looks like at the same point. On the target, there is an error message in one of TS event logs:
The server security layer detected an error (0x80004005) in the protocol stream and the client (Client IP:10.60.1.24) has been disconnected.

**Comment by akallabeth** [comment]
@lazyruss so your client says `This is FreeRDP version 2.0.0-dev3 (7eb12bb02)`?

**Comment by akallabeth** [comment]
Ok, found the issue. Looks like we had different domain settings and therefore I've never got the extended first authentication token.
Can reproduce now too with the new setup.

**Comment by mihaivirag** [comment]
Will this bug be fixed soon?

**Comment by akallabeth** [comment]
@mihaivirag not on my high priority list, but pull requests are welcome. For the time being, it should suffice to force nla or tls authentication

**Comment by akallabeth** [comment]
Further tracking with #4311
