### ISSUE TITLE
xfreerdp return codes have changed since 2d58e96

### ISSUE THREAD

**Issue by gh-user-7392** [FreeRDP/FreeRDP#4526]
Since commit 2d58e96dcc334083dc7634522cfeec7c58c3a32c from 2/11, xfreerdp return codes have changed. I use a bash script to launch xfreerdp and check return codes when disconnects occur for debugging. A normal disconnect returns with an 11 when X'ing out of a minimized window, or an abnormal disconnect returns a 12 when there is a network problem. I believe since the 2/11 commit, the return codes are always 0 on any type of disconnect.

Area of interest in client/X11/cli/xfreerdp.c at line 82:

return winpr_exit(xf_exit_code_from_disconnect_reason(dwExitCode));

Not sure if this is by design, just thought I would mention it.

**Comment by akallabeth** [comment]
See #4482
