### ISSUE TITLE
/f not work,but /w:1920 /h:1080 works well

### ISSUE THREAD

**Issue by sherwinkh** [FreeRDP/FreeRDP#4534]
I download the latest FreeRDP @807fe04 Merge pull request #4519 from mfleisz/cssp_nonce_fix.
When I start rdp with this cmdline: ”xfreerdp /sec:rdp /v:$USERIP  /u:$USERNAME /p:$PASSWORD /f",
the screen is black;
start rdp with "xfreerdp /sec:rdp /v:$USERIP  /u:$USERNAME /p:$PASSWORD /w:1920 /h:1080" works well.
    My remote server is win7, someone encounter this issue？

**Comment by akallabeth** [comment]
@sherwinkh Everything working as expected with current nightly builds here. (that is, kde/plasma on fedora 27)
could you give some details on your setup? WM/distro/... could have influence here.

**Comment by sherwinkh** [comment]
RDP server： Windows 7 Ultimate SP1
terminal（an arm board） ：Linaro 13.08 \n \l

**Comment by sherwinkh** [comment]
RDP server： Windows 7 Ultimate SP1
terminal（an arm board） ：Linaro 13.08 \n \l

**Comment by akallabeth** [comment]
Sorry, not familiar with `Linaro`, what window manager / display system are they using?
The output of `/buildconfig` would also be nice, as your issue sounds like a compilation issue.

**Comment by sherwinkh** [comment]
This is FreeRDP version 2.0.0-dev2 (807fe04)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 WITH_ALSA=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_JPEG=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NEON=ON WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=OFF WITH_XINERAMA=ON WITH_XKBFILE=OFF WITH_XRANDR=OFF WITH_XRENDER=OFF WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -mfloat-abi=hard  -march=armv7-a -mfpu=neon -mthumb -Wl,--hash-style=sysv  -g -funwind-tables -rdynamic -I/home/x5/x5_rfx/rdp/include -L/home/x5/x5_rfx/rdp/lib -lxcb -lavcodec -lavutil -lasound -lXau -lXrender -lXfixes -lXv -L/home/x5/x5_rfx/lib-msc/libsndfile/lib -lsndfile -L/home/x5/x5_rfx/lib-msc/jsonc12/lib -ljson-c -L/home/x5/x5_rfx/lib-msc/pulse6/lib/pulseaudio -lpulsecommon-6.0   -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU, 
Target architecture: ARM

**Comment by akallabeth** [comment]
Looks like your compile is broken. You're missing a lot of X11 related flags (`WITH_XI=OFF WITH_XRANDR=OFF WITH_XRENDER=OFF`)

**Comment by akallabeth** [comment]
If your system is debian based, it may be a good idea to just build the nightly package for comparison (the debian package configuration is in `packaging/deb/freerdp-nightly/`)

**Comment by sherwinkh** [comment]
Looks like your compile is broken
==》if my compiler is broken，with “/w:1920 /h:1080” should not work will.
but "/w:1920 /h:1080" works well

**Comment by akallabeth** [comment]
@sherwinkh read again, I said `compile`. You're compiling without a lot of X11 related flags, so many functions will only partially work

**Comment by sherwinkh** [comment]
but with the same compile environment， build early FreeRDP ver ，/f  works  well.
I don't understand.
