### ISSUE TITLE
iOS FreeRDP compiling issues

### ISSUE THREAD

**Issue by shattars3d** [FreeRDP/FreeRDP#4541]
Running:
Xcode 8.3.3
CMake 2.8.12.2

I have posted in IRC chat, been a week no answer so,
this is the issue I am having.
 
when i run, cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode
 i get these errors.

![screen shot 2018-04-06 at 11 29 15 am](https://user-images.githubusercontent.com/2119331/38429961-ef72f9de-398d-11e8-9069-8fa1d9aaf20b.png)

**Comment by akallabeth** [comment]
Are you serios? `-bash: vmake: command not found` is quite obvious. You're missing cmake in `PATH`
