### ISSUE TITLE
SMB Shared Folder Mapping in XfreeRDP 2.0 RDWEB .rdp 

### ISSUE THREAD

**Issue by ppokhriyal** [FreeRDP/FreeRDP#4545]
Hello,

I am not able to Map the SMB share folder,using the below command

xfreerdp xyz.rdp /cert-ignore /u:xxxx /d:xxxx /p:xxxxx /drive:/media/smb,B /v:x.x.x.x

**Comment by akallabeth** [comment]
Try the other way around (or reading the manpage)
