### ISSUE TITLE
XfreeRDP 2. 0 session does not exit after Session Logout

### ISSUE THREAD

**Issue by ppokhriyal** [FreeRDP/FreeRDP#4546]
Hi,

After longing out from the session, the xfreerdp command stucks.

xfreerdp /cert-ignore /u:xx /d:ddd /p:dsds /vc:vcvc /v:d.d.d.d

Message : **The disconnect was initiated by the user logging off his or her session on the server** *

Stuck on the above message

**Comment by ppokhriyal** [comment]
@akallabeth 
i have created my own virtual channel . so while passing **"/vc:my_virtual_channel_name"** i am able to connect to the session but after logout from the session, i get the message of "**The disconnect was initiated **by** the user logging off his or her session on the server** " and get stuck to this message only.

**Comment by akallabeth** [comment]
Yes, got that. But does freerdp work when you don't use your channel?

**Comment by ppokhriyal** [comment]
Yes, without passing the "/vc" it works fine.

**Comment by akallabeth** [comment]
Then I'd strongly suggest checking your channel cleanup, it is most likely blocking shutdown
