### ISSUE TITLE
Android where to set the hostname

### ISSUE THREAD

**Issue by khaleids** [FreeRDP/FreeRDP#4553]
Hello,

As it said in this pull request, 
That's there is possiblty to set the hostname from android app, question is where and how to set it, there is advanced options but no field related to hostname to add it.
Thank you in advance  

https://github.com/FreeRDP/FreeRDP/pull/4092

**Comment by khaleids** [comment]
Client name

**Comment by akallabeth** [comment]
yes, the client name it is.

**Comment by khaleids** [comment]
I need to set client name from android app, but from where? there is no textbox in android app said "Client Name" !!!

**Comment by khaleids** [comment]
I already set Device "HostName"
 [net.hostname]: [MYPHONENAME] 
but FreeRDP Android app, didn't use it as client name, FreeRDP it set "LocalHost" I don't know why!!,  so I need Ethier use Device "HostName" or set it, from the client side as mentioned here >> https://github.com/FreeRDP/FreeRDP/pull/4092

**Comment by akallabeth** [comment]
how about you looking into the settings?

**Comment by khaleids** [comment]
there is nothing 
<img width="878" alt="freerdp" src="https://user-images.githubusercontent.com/23697904/38553201-c1de9440-3cbe-11e8-99e2-f64afedc9259.png">

**Comment by bmiklautz** [comment]
@khaleids you installed from app store?

**Comment by khaleids** [comment]
yes

**Comment by khaleids** [comment]
Version
![image](https://user-images.githubusercontent.com/23697904/38553852-dc93e70c-3cc0-11e8-9f57-e2499d26dd18.png)

**Comment by bmiklautz** [comment]
@khaleids now is all clear. aFreeRDP (latest development) does already support this but the version in the app store doesn't. I can't tell when it will be updated the next time but I hope after the 2.0 release.
