### ISSUE TITLE
wfreerdp to windows 10 target: capabilities exchanged 30-60 times

### ISSUE THREAD

**Issue by lazyruss** [FreeRDP/FreeRDP#4556]
i've build freerdp (rev #04b29575feb35a158e5813f9a2e19799c4b78ec8) with DEBUG_ALL=ON and noticed that freerdp and target perform capability exchange way too many times (30, 40, even 60).
my command line: 
`wfreerdp.exe /v:10.60.130.118 /w:1900 /h:980 /gdi:sw /tls-ciphers:netmon`
cannot post buildconfig since redirect does not work.
it's pretty much default configuration with the exception of DEBUG_ALL=ON.
compiler is VS 2017, build host is Windows 10.

**Comment by akallabeth** [comment]
* How do you know if output redirection does not work?
* which capabilities are at fault? Some log maybe?

**Comment by akallabeth** [comment]
@lazyruss As for the redirection, did you properly redirect `stdout` and `stderr`? See https://stackoverflow.com/questions/1420965/redirect-windows-cmd-stdout-and-stderr-to-a-single-file

**Comment by akallabeth** [comment]
Ok, checked. You did interpret the messages wrong.
There is more than one capability and each capability is negociated on its own. (mostly they consist of a capability Request and a Response message).
With the command line you provided that amounts to that amount of capability messages.

**Comment by lazyruss** [comment]
@akallabeth redirecting stdout and/or stderr does not work because wfreerdp creates its own console window.
negotiating capabilities for 16 seconds seems quite bizarre to me. I've traced it in the past, and never seen request/response happening that many times (see attached log)
[log-sw-ip.zip](https://github.com/FreeRDP/FreeRDP/files/1899979/log-sw-ip.zip)

**Comment by akallabeth** [comment]
@lazyruss No, redirecting works quite fine with the nightly builds. No console window started whatsoever.
Despite the (still too old) ssl version (hopefully fixed soon) I can not reproduce your issue at all.

**Comment by lazyruss** [comment]
@akallabeth release build could be redirected. debug (like mine) could not, due to
```
#if defined(WITH_DEBUG) || defined(_DEBUG)
	wf_create_console();
#endif
```
