### ISSUE TITLE
Tsmf/X11  error X Error:  BadImplementation

### ISSUE THREAD

**Issue by sherwinkh** [FreeRDP/FreeRDP#4566]
play a mp4 video（supported by media redirection） with Windows Media Player，I can hear the sound，but can't see the video，error：
X Error:  BadImplementation
  Request Major code 147 (XVideo)
  Request Minor code 19 ()
  Error Serial #1265
  Current Serial #1267
X Error:  BadImplementation
  Request Major code 147 (XVideo)
  Request Minor code 19 ()
  Error Serial #1335
  Current Serial #1336
X Error:  BadImplementation
  Request Major code 147 (XVideo)
  Request Minor code 19 ()
  Error Serial #1345
  Current Serial #1346
X Error:  BadImplementation
  Request Major code 147 (XVideo)
  Request Minor code 19 ()
  Error Serial #1408
  Current Serial #1409

Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS= WITH_ALSA=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NEON=ON WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_LEAK_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=OFF WITH_XKBFILE=OFF WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
Compiler:            GNU, 
Target architecture: ARM

**Comment by akallabeth** [comment]
@sherwinkh Could you please add your distribution and way of building? Looks like this could have several reasons for failing (TSMF-Backend, missing build dependencies, ...)
`/tsmf` is not really well maintained. Anyway, `/video` is the better replacement (but sadly only available with recent versions of windows)

**Comment by sherwinkh** [comment]
#!/bin/sh
export CROSSTOOL=arm-linux-gnueabihf
export CXX=$CROSSTOOL-g++ 
export CC=$CROSSTOOL-gcc 
export AR=$CROSSTOOL-ar 
export AS=$CROSSTOOL-as 
export RANLIB=$CROSSTOOL-ranlib
export LD=$CROSSTOOL-ld

export CFLAGS=" -mfloat-abi=hard  -march=armv7-a -mfpu=neon -mthumb -Wl,--hash-style=sysv -g -funwind-tables -rdynamic \
-I/home/r1/r1_rfx/lib-msc/xorg/xi/include \
-L/home/r1/r1_rfx/lib-msc/libsndfile/lib -lsndfile \
-L/home/r1/r1_rfx/lib-msc/jsonc12/lib -ljson-c \
-L/home/r1/r1_rfx/lib-msc/pulse6/lib/pulseaudio -lpulsecommon-6.0 \
-L/home/r1/r1_rfx/lib-msc/xorg/x11/lib -lX11 -lX11-xcb \
-L/home/r1/r1_rfx/lib-msc/xorg/xcb/lib -lxcb \
-L/home/r1/r1_rfx/lib-msc/xorg/xau/lib -lXau \
-L/home/r1/r1_rfx/lib-msc/xorg/xfixes/lib -lXfixes \
-L/home/r1/r1_rfx/lib-msc/xorg/xv/lib -lXv \
-L/home/r1/r1_rfx/lib-msc/xorg/xi/lib -lXi\
"

export PKG_CONFIG_PATH=\
/home/r1/r1_rfx/lib-msc/xorg/xproto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xcb-proto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/pthread-stubs/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xau/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/inputproto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/kbproto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xextproto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xcb/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xextproto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xtrans/share/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/videoproto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/x11/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xv/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xrender/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/randrproto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xrandr/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/pulse6/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/zlib/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/libffi/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/pcre/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/glib/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/ffmpeg/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/fixesproto/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xfixes/lib/pkgconfig:\
/home/r1/r1_rfx/lib-msc/xorg/xcursor/lib/pkgconfig
#/home/r1/r1_rfx/lib-msc/gstream/lib/pkgconfig:\
#/home/r1/r1_rfx/lib-msc/openssl/lib/pkgconfig:\
rm -rf build/ Rfx-install/
if [ -d build ] ; then
	echo "dir build exist!"
else
	mkdir build
    echo "dir build not exist,create build dir now!"
fi
if [ -d Rfx-install ] ; then
    echo "dir Rfx-install  exist!"
else
    mkdir Rfx-install
    echo "dir Rfx-install not exist,create Rfx-install dir now!"
fi

cd build
rm -rf *
cmake  .. \
-DWITH_DEBUG_ALL=OFF \
-DWITH_XRENDER=OFF \
-DWITH_JPEG=OFF \
-DTARGET_ARCH=ARM \
-DWITH_DEBUG_DVC=OFF \
-DWITH_DEBUG_CHANNELS=OFF \
-DCHANNEL_URBDRC_CLIENT=OFF \
-DCHANNEL_URBDRC=OFF \
-DWITH_XRANDR=ON \
-DWITH_XINERAMA=OFF \
-DWITH_XRENDER=ON \
-DWITH_XI=ON \
-DWITH_XCURSOR=ON \
-DWITH_XKBFILE=ON \
-DWITH_X11=ON \
-DWITH_FFMPEG=ON \
-DWITH_PULSE=ON \
-DWITH_XV=ON \
-DWITH_NEON=ON \
-DWITH_ALSA=OFF \
-DCMAKE_BUILD_TYPE=Release \
-DWITH_SSE2=OFF \
-DWITH_XKBFILE=OFF \
-DWITH_LIBSYSTEMD=OFF \
-DWITH_WAYLAND=OFF \
-DWITH_MANPAGES=OFF \
-DCMAKE_INSTALL_PREFIX=../Rfx-install \
-DX11_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/x11/lib \
-DX11_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/x11/include \
-DXRANDR_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/xrandr/lib \
-DXRANDR_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/xrandr/include \
-DXEXT_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/xext/lib \
-DXEXT_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/xext/include \
-DXSHM_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/xshmfence/lib \
-DXSHM_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/xshmfence/include \
-DXV_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/xv/lib \
-DXV_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/xv/include \
-DXFIXES_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/xfixes/lib \
-DXFIXES_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/xfixes/include \
-DOPENSSL_ROOT_DIR=/home/r1/r1_rfx/rdp/depend_pack/openssl-1.0 \
-DOPENSSL_LIBRARIES=/home/r1/r1_rfx/rdp/depend_pack/openssl-1.0/lib \
-DOPENSSL_INCLUDE_DIR=/home/r1/r1_rfx/rdp/depend_pack/openssl-1.0/include \
-DXCURSOR_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/xcursor/lib \
-DXCURSOR_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/xcursor/include \
-DXRENDER_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/xrender/lib \
-DXRENDER_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/xrender/include \
-DXI_LIBRARY=/home/r1/r1_rfx/lib-msc/xorg/fixesproto/lib \
-DXI_INCLUDE_DIR=/home/r1/r1_rfx/lib-msc/xorg/fixesproto/include

**Comment by akallabeth** [comment]
For TSMF there is the following to consider:
* `GStreamer` is the best working backend, `FFMPEG` not so much
* You're missing `X11 xinerama` development headers (we use that extension for some features, not to be confused with X11 xinerama mode)

**Comment by sherwinkh** [comment]
@akallabeth ，I will rebuild with X11 xinerama

**Comment by sherwinkh** [comment]
@akallabeth , I have rebuilded FreeRDP with xinerama，encounter the same error.
Could you give me some other suggestions？

**Comment by akallabeth** [comment]
@sherwinkh Depends on what you try to achieve (what is your server OS?) `/gfx:avc444 /video` should be the better options.
Other than that we're happy to integrate fixes if you find out what exactly the issue is ;)

**Comment by sherwinkh** [comment]
@akallabeth building whith gstreamer，encounter this error：
-- Finding recommended feature GStreamer_1_0 for multimedia (multimedia redirection, audio and video playback)
--     Disable feature GStreamer_1_0 using "-DWITH_GSTREAMER_1_0=OFF"
-- checking for module 'glib-2.0'
--   found glib-2.0, version 2.50.1
-- Found Glib 
-- checking for module 'gstreamer-1.0 >= 1.0.5'
--   found gstreamer-1.0 , version 1.12.2
-- checking for module 'gstreamer-base-1.0 >= 1.0.5'
--   found gstreamer-base-1.0 , version 1.12.2
-- checking for module 'gstreamer-app-1.0 >= 1.0.5'
--   package 'gstreamer-app-1.0 >= 1.0.5' not found
-- checking for module 'gstreamer-audio-1.0 >= 1.0.5'
--   package 'gstreamer-audio-1.0 >= 1.0.5' not found
-- checking for module 'gstreamer-fft-1.0 >= 1.0.5'
--   package 'gstreamer-fft-1.0 >= 1.0.5' not found
-- checking for module 'gstreamer-pbutils-1.0 >= 1.0.5'
--   package 'gstreamer-pbutils-1.0 >= 1.0.5' not found
-- checking for module 'gstreamer-video-1.0 >= 1.0.5'
--   package 'gstreamer-video-1.0 >= 1.0.5' not found

Could you give a link to download tarballs of these packages？
