### ISSUE TITLE
Sometimes getting: Error: protocol security negotiation failure

### ISSUE THREAD

**Issue by bakytn** [FreeRDP/FreeRDP#457]
Hi! Using FreeRDP 1.0.1 and FreeRDP 1.0

If I just try to connect to Windows XP machine with

xfreerdp -u user IP

it shows: 

Error: protocol security negotiation failure
if I run the same command again and again for about 3 times for the fourth time it would connect.

Sometimes (after couple of failures) I provide --no-tls but it works.

But when I use --no-tls initially it would show (again, sometimes): Error: protocol security negotiation failure

I am having to run the same command again and again until it works.

**Comment by caengcjd** [comment]
just sudo  it
