### ISSUE TITLE
X11 Client Ctrl+Alt+Enter does not toggle full screen

### ISSUE THREAD

**Issue by andreesteve** [FreeRDP/FreeRDP#4579]
I am not able to go full screen with /f nor toggle full screen with Crtl+Alt+Enter.

Tested on local build off commit b228deb998aa4751bf14f571a1843f9e00cb1321 on master

Hitting ctl+alt+enter gives this log message

```
[17:17:50:584] [6796:6797] [INFO][com.freerdp.client.x11] - Property 322 does not exist
```

Window manager is i3 (but hasn't change, i.e. fullscreen keyboard shortcut was working before).

I'll try to do some more digging on the weekend to get more details.

**Comment by akallabeth** [comment]
@andreesteve could you post the output of `/buildconfig` and try with our nightly builds as a reference?

**Comment by andreesteve** [comment]
I'll try the nightly build tonight.
Is there a specific build config that enables full screen?
Maybe me and my distro package maintainer just forgot to include that one?

```
This is FreeRDP version 2.0.0-dev3 (b228deb99)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Debug
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
Compiler:            GNU, 7.3.1
Target architecture: x64
```

**Comment by akallabeth** [comment]
If you feel comfortable, in `xf_SetWindowFullscreen` there are 2 paths setting fullscreen, maybe your wm is doing something different and the detection fails. (great, another one, X11 is really annoying in regard to that)

**Comment by andreesteve** [comment]
I really don't know anything about X. I don't know how much of this problem is due to my window manager (i3). What I see:

1. If I don't start with /f, then the window is a floating one (no tilling) - but if I toggle full screen (crtl+alt+enter) the window vanishes! The process is still alive :(
2. When I start with /f it opens tilled (before, it used to just open full screen). In this situation, toggling does nothing.

When I tried debugging and had a breakpoint on the toggle full screen function, I lost all keyboard input everywhere, has anyone else experienced that? I think the xfreedrp process captures all input and cannot release it because I have the debugger attached and the process on hold. I guess my WM is not brute enough to just steal it back.

I guess I will have to find a GUI for gdb and see if I can debug purely with the mouse or figure out how to recover keyboard input when debugging. Any tips are really welcomed!

**Comment by nikkez** [comment]
I have the same issue with dwm window manager.

**Comment by geiseri** [comment]
I also see this with the "matchbox" window manager.  It is a strange bird because it forces all top-level windows to be maximized. This did work properly in the past though.

**Comment by andreesteve** [comment]
@nikkez , @geiseri would you guys be able to help testing my [proposed fix](https://github.com/FreeRDP/FreeRDP/pull/4600) ?

**Comment by geiseri** [comment]
@andreesteve I will test it.  I am not sure I follow the logic, but will this also work for multiple monitors?

**Comment by nikkez** [comment]
@andreesteve I just tested the proposed fix and it works on the dwm window manager.

**Comment by andreesteve** [comment]
@nikkez , thank you!
@geiseri I am not sure we will have to test. I would expect your WM to not have support for _NET_WM_FULLSCREEN_MONITORS but still allow a window spamming two monitors (this is assuming it worked for you before). i3 doesn't do either it seems and gnome supports the former. So the code path that I believe would run for your WM is the one I didn't have a way to test (also I did not change anything there, so the prospect is grim :( ). If you can share any screenshots of problems you run into, let me know I can try to have a look.

**Comment by geiseri** [comment]
@andreesteve it tested out fine in matchbox.  It shouldn't impact "normal" window managers with dual screen, right?

**Comment by andreesteve** [comment]
@geiseri I've tested this extensively in gnome (fair to assume that if there is a WM that implements the heck out of X extensions, it would be it :) and it works fine on my 3 screen (i.e. I couldn't find any regressions).

When building WITH_XRANDR=ON, there is a bug when using multi monitor fullscreen when selecting a subset of monitors (e.g. full screen on monitor 0 and 1 but not 2). It fails to correctly order the screens. But that is the case with or without my changes (i.e. my change is not fixing that).

**Comment by mmattes** [comment]
I am having similar issues on my notebook (one screen only) running Linux Mint 19 with Cinnamon 3.8.8 with both, the nightly Build and a self generated build from the PR #4600. I do start freerdp with `xfreerdp -u user@domain -f host`, trying to get out of the full screen mode by pressing CTRL+ALT+ENTER vanishes the freerdp window, but it seems to still grab all inputs as I am not able to do anything in linux, what i am seeing, anymore.

**Comment by nitso** [comment]
Same problem as @mmattes described earlier. Debug log shows nothing interesting, just drawing messages.
