### ISSUE TITLE
FFMPEG Multimedia redirection fails

### ISSUE THREAD

**Issue by lilyhepp** [FreeRDP/FreeRDP#4584]
I am running on Ubuntu 16.04 LTS,
I have compiled the latest FreeRDP-2.0.0-rc2 and when i try to use xfreerdp with multimedia redirection I get the following message when using the /multimedia:sys:alsa,decoder:ffmpeg option
GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /mnt/lib/rdplib2/lib/freerdp2/libtsmf-client-ffmpeg-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[WARN][com.freerdp.addin] - Failed to load channel tsmf [ffmpeg]
[ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /mnt/lib/rdplib2/lib/freerdp2/libtsmf-client-gstreamer-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[WARN][com.freerdp.addin] - Failed to load channel tsmf [gstreamer]
[ERROR][com.winpr.library] - GetProcAddress: could not find procedure freerdp_tsmf_client_subsystem_entry: /mnt/lib/rdplib2/lib/freerdp2/libtsmf-client-ffmpeg-decoder.so: undefined symbol: freerdp_tsmf_client_subsystem_entry
[WARN][com.freerdp.addin] - Failed to load channel tsmf [ffmpeg]
/mnt/lib/rdplib2/lib/freerdp2/libtsmf-client-ffmpeg-decoder.so is existed

I have compiled with the following options affecting the channels
cmake . 
-DWITH_WAYLAND=OFF 
-DCMAKE_BUILD_TYPE:STRING=Release 
-DCMAKE_INSTALL_PREFIX=/mnt/lib/rdplib2 
-DSTATIC_CHANNELS=OFF 
-DWITH_NEON=OFF -DWITH_SSE2=OFF 
-DWITH_JPEG=ON 
-DWITH_DIRECTFB=OFF 
-DWITH_CUPS=OFF 
-DWITH_PCSC=OFF 
-DWITH_FFMPEG=ON 
-DWITH_GSTREAMER=ON 
-DWITH_X264=OFF 
-DWITH_OPENH264=ON 
-DWITH_XRANDR=ON 
-DWITH_XV=ON 
-DCHANNEL_URBDRC_CLIENT=ON \

I find in https://github.com/FreeRDP/FreeRDP/issues/2094 

 There is a bug with WMV I had forgotten to create a pull for, see here: https://github.com/akallabeth/FreeRDP/tree/tsmf-windows-media-fix

when I open https://github.com/akallabeth/FreeRDP/tree/tsmf-windows-media-fix,and show 404 error codes.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
