### ISSUE TITLE
wfreerdp fully transparent in fullscreen mode (behind the desktop)

### ISSUE THREAD

**Issue by klezgt** [FreeRDP/FreeRDP#4585]
Wfreerdp doesn't show remote desktop in fullscreen mode. It Just shows green bar on the top of the screen. 
But it becomes ok in window mode if I hit "ctrl+alt+enter"
client : windows 7 x 64
server: windows server 2012 r2
wfreerdp, nightly build 473 x64 
command line: wfreerdp.exe /bpp:32  /f +clipboard +fonts +window-drag +themes +aero /rfx /v:xxx.xxx.xxx.xxx

**Comment by akallabeth** [comment]
Does it work if you add `/cert-tofu` or `/cert-ignore`?

**Comment by raid2000** [comment]
same problem, but only with 1366x768 resolution
