### ISSUE TITLE
/multimonitor doesn't work with /vmconnect

### ISSUE THREAD

**Issue by JairoMarques** [FreeRDP/FreeRDP#4594]
Using FreeRDP version 1.1 in Ubuntu 16.04 as follow:
xfreerdp  /v:dsf09 /f /dpp:32 /u:Jairo /d:mydomain.com /vmconnect:a0a23c9b-11ec-4740-82c5-2e0cf55674f4 /multimon

Only using one monitor.

Works if I use (using two monitors):
xfreerdp  /v:dsp12 /f /dpp:32 /u:Jairo /d:mydomain.com / /multimon

Using Hyper-V Server 2016.
My VM is Windows 10 Enterprise

**Comment by JairoMarques** [comment]
I tried with xfreerdp 2.0.0 Dev version too without success.

I'll try with nightly build too.

**Comment by akallabeth** [comment]
No feedback, closing.
