### ISSUE TITLE
FreeBSD strtol() behaves different -- /network:lan doesn't work

### ISSUE THREAD

**Issue by adriaandegroot** [FreeRDP/FreeRDP#4597]
FreeBSD's strtol() and family behave differently from (Linux) GLibC implementations. This affects the way they set (or don't re-set) errno on erroneous input, and then parameter handling by the freerdp executable throws an error, leading to .. well, "no worky". This is most obvious with the /network option, since that has both numeric and non-numeric (e.g. "lan") values to handle.

There are downstream bugs at
 - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225099
 - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=225559

There are patches (by me) attached to the latter bug, which fix **some** of the issues, but not all of them. I don't have much to test with / against, so basically I'm chasing down-downstream bug reports and running the freerdp with various command-line options until it stops giving me command-line-parsing errors.

The affected version is 2.0.0-rc1; I haven't tried -rc2.

```
xfreerdp /network:lan /port:3389 /v:127.0.0.1
```

This produces -- on FreeBSD -- output that indicates that the command-line parameters are wrong. Removing the /network option fixes it (in the sense that it then doesn't give an error about command-line parameters, and goes on to try to connect to an RDP server I don't have).

The main issue is that errno isn't reset by successful calls to strtol(), while it is with (Linux) GLibC. I'll see if I can whip up an example program to show that.

**Comment by kevans91** [comment]
I mention this in the mentioned PR 225559, but all of the strtol, stroul, strold usage throughout FreeRDP should be corrected to set errno beforehand if they're going to do an errno check after the fact, as per POSIX recommendations [1]. POSIX [1] also backs up Adriaan's last statement as POSIXly correct behavior- "These functions shall not change the setting of errno if successful."

Whipping something up with Coccinelle to correct these invocations throughout FreeRDP might be a good thing to do given the number of calls- a quick `grep` seemed to indicate that they all basically follow the same pattern of fail if `errno != 0` without having reset errno beforehand.

[1] http://pubs.opengroup.org/onlinepubs/9699919799/functions/strtol.html
