### ISSUE TITLE
How to use Linux title bar, and window boarder when using remote app?

### ISSUE THREAD

**Issue by relink2013** [FreeRDP/FreeRDP#4604]
I am using FreeRDP nightly for its remote app feature. How can I go about having my remote apps run within a Linux window frame? Some of my remote apps are a pain to resize and maximize, and I think that having the app contained within a Linux window might help.

I am running Ubuntu 16.04, so my DE is Gnome.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
