### ISSUE TITLE
xfreerdp issue connecting in -rc2

### ISSUE THREAD

**Issue by kevans91** [FreeRDP/FreeRDP#4615]
Now that I've upstreamed all of our patches that we used on -rc1... something happened between -rc1 and -rc2 that causes xfreerdp to be basically non-functional but not in a verbose way. With the following invocation:

```
$ xfreerdp /v:<host> /u:<domain>\\<user>
```

I get the fairly expected output:
```
[13:20:48:805] [95372:0858c500] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[13:20:50:754] [95372:0858c500] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[13:20:50:754] [95372:0858c500] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[13:20:50:781] [95372:0858c500] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
```

The window then draws for a split second and FreeRDP exits for no apparent reason and without any core dump. On the remote side, nothing appears to have happened whether I'm currently logged in and actively using the remote or not.

I attempted to bisect, but sometime before April the WaitableTimer implementation apparently became mandatory and things started to get hairy trying to port some of these patches to each commit I was testing.

What else can I do to help diagnose this? FreeRDP is a beast that I'm not all too familiar with =)

**Comment by bmiklautz** [comment]
@kevans91 on what system/distribution you have the problem?

**Comment by kevans91** [comment]
Ah, sorry, I omitted this. =) I run FreeRDP on FreeBSD.

**Comment by kevans91** [comment]
After a lot longer than I'm proud to admit and too many printfs, I narrowed it down to the fcntl failing on the timer fd because of how our epoll wraps kevent -- the resulting fd isn't quite that flexible, but the timerfd flag for nonblock works just fine. After the referenced PR, -rc2 is functional for me again.
