### ISSUE TITLE
131085 error using wfreerdp with domain user and NLA

### ISSUE THREAD

**Issue by mihaivirag** [FreeRDP/FreeRDP#4621]
Hi,

I am trying to connect to a 2012 R2 Windows server using this command line:

wfreerdp.exe /d:test_domain /u:test_user /p:test_password /v:test_machine /cert-ignore > out.txt

You can see the error in out.txt file.

With normal Windows RDC it is working.

Server settings are in the ServerSettings.png file.

It is working if the NLA is not activated (checked).

I build manually the wfreerdp exe. I have tryied with different versions. The current one is 2-4 weeks old. Normal build, added MONOLITHIC_BUILD - TRUE and BUILD_SHARED_LIBS – FALSE and Checked WITH_GSSAPI. Using OpenSSL 1.0.2o and MIT Kerberos 

Thanks,
Mihai Virag

PS. If I want to use NLA, do I have to use Kerberos?
[out.txt](https://github.com/FreeRDP/FreeRDP/files/1970844/out.txt)
![serversettings](https://user-images.githubusercontent.com/38915055/39576732-71a84060-4edf-11e8-90e5-6bbc9a8f0450.PNG)

**Comment by akallabeth** [comment]
there have been some issues with the `GSS_API` implementation, does it work if you compile without?

**Comment by akallabeth** [comment]
btw, you should add `2>&1` to your command line, your output file is missing the actual error.

**Comment by mihaivirag** [comment]
No. Is the same with or without GSS_API

**Comment by akallabeth** [comment]
You compiled fips compliant? does it work if you disable that requirement on the server?

**Comment by mihaivirag** [comment]
If I set from FIPS Compliant to Client Compatible is the same

**Comment by akallabeth** [comment]
@mihaivirag so, what exactly is the error then (your `out.txt` was missing the error messages)

**Comment by mihaivirag** [comment]
If I debug with Visual Studio 2017 I got this:

[15:25:56:869] [148488:000239c8] [DEBUG][com.freerdp.core.nla] - 0920 2f 7f f6 3a 79 25 61 7a 1c 40 18 ec 28 57 e5 6b /..:y%az.@..(W.k
[15:25:56:869] [148488:000239c8] [DEBUG][com.freerdp.core.nla] - 0930 c7 e2 ce af e0 49 ff 06 19 cc e6 74 2d 05 cc 22 .....I.....t-.."
[15:25:56:869] [148488:000239c8] [DEBUG][com.freerdp.core.nla] - 0940 93 6f 7e 5e ba 93 70 70 44 f9 86 91 3d 57 12 d2 .o~^..ppD...=W..
[15:25:56:869] [148488:000239c8] [DEBUG][com.freerdp.core.nla] - 0950 1d e9 04 02 07 3c ec df 6a 99 89 1d 41 3b b9 9c .....<..j...A;..
[15:25:56:869] [148488:000239c8] [DEBUG][com.freerdp.core.nla] - 0960 0c 05 1c d1 0d e3 4c 29 1f 0d 88 04 b5 0c 53 ef ......L)......S.
[15:25:56:872] [148488:000239c8] [TRACE][com.freerdp.core.nla] - InitializeSecurityContext  SEC_E_OK [0x00000000]
'wfreerdp.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptdll.dll'. Module was built without symbols.
'wfreerdp.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\cryptdll.dll'
'wfreerdp.exe' (Win32): Loaded 'C:\Windows\SysWOW64\cryptdll.dll'. Cannot find or open the PDB file.
[15:25:56:891] [148488:000239c8] [ERROR][com.freerdp.core.nla] - EncryptMessage status2 SEC_E_INVALID_TOKEN [0x80090308]
[15:26:01:818] [148488:000239c8] [ERROR][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[15:26:01:818] [148488:000239c8] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[15:26:02:075] [148488:000239c8] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
[15:26:02:075] [148488:000239c8] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[15:26:02:075] [148488:000239c8] [DEBUG][com.freerdp.client.windows] - Main thread exited with 131085

**Comment by akallabeth** [comment]
@mihaivirag Are you sure you have an up to date version? I can not find some of the log messages. What does `wfreerdp /buildconfig` tell you?

**Comment by akallabeth** [comment]
@mihaivirag and windows is picky where to put the `2>&1`, try it after the `>log.txt`

**Comment by mihaivirag** [comment]
[17:00:54:773] [148704:000247a0] [DEBUG][com.freerdp.client.common.cmdline] - windows: -2004/1 posix: -1000/0 compat: 1/0
This is FreeRDP version 2.0.0-dev3 (fc6780a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_X264=OFF
Build type:          Release
CFLAGS:              /DWIN32 /D_WINDOWS  /Gd /W3
Compiler:            MSVC, 19.13.26129.0
Target architecture: x86

**Comment by mihaivirag** [comment]
[out.txtt.txt](https://github.com/FreeRDP/FreeRDP/files/1973401/out.txtt.txt)
New log file, with the error

**Comment by akallabeth** [comment]
@mihaivirag Ok. This error is caused in `nla_encrypt_public_key_hash` which is quite strange.
Could you check the following:
1. Which OpenSSL are you testing with? Please check that the library used during runtime is the same version you compile with. (maybe do a full static build to ensure you've got the correct one)
1. Does it work with version 1.1 (you mentioned 1.0.2o above)

**Comment by akallabeth** [comment]
@mihaivirag `MONOLITHIC_BUILD` is a relic that has not been used in years, and `BUILD_SHARED_LIBS` is only relevant for freerdp itself. We use `-T v120_xp -DCMAKE_WINDOWS_VERSION=WINXP -DBUILD_SHARED_LIBS=OFF -DMSVC_RUNTIME=static` to get a fully static build with our nightly builder.

**Comment by akallabeth** [comment]
could you try if `diff --git a/libfreerdp/core/nla.c b/libfreerdp/core/nla.c
index 7d3b70d7d..8adb60343 100644
--- a/libfreerdp/core/nla.c
+++ b/libfreerdp/core/nla.c
@@ -348,7 +348,7 @@ static int nla_client_init(rdpNla* nla)
        nla->packageName = nla->pPackageInfo->Name;
        WLog_DBG(TAG, "%s %"PRIu32" : packageName=%ls ; cbMaxToken=%d", __FUNCTION__, __LINE__,
                 nla->packageName, nla->cbMaxToken);
-       nla->status = nla->table->AcquireCredentialsHandle(NULL, NLA_PKG_NAME,
+       nla->status = nla->table->AcquireCredentialsHandle(NULL, nla->packageName,
                      SECPKG_CRED_OUTBOUND, NULL, nla->identity, NULL, NULL, &nla->credentials,
                      &nla->expiration);`
fixes your issues?

**Comment by mihaivirag** [comment]
no
[out.txt](https://github.com/FreeRDP/FreeRDP/files/1974452/out.txt)

**Comment by akallabeth** [comment]
Nightly builder has been updated, starting with build #481 the connection to domains and windows machines with the CredSSP patches work again.

**Comment by mihaivirag** [comment]
Any news?

**Comment by mihaivirag** [comment]
Can we reopen this case? I tried with today's build and it is still not working. The CredSSP is there.
[out.txt](https://github.com/FreeRDP/FreeRDP/files/2001300/out.txt)

**Comment by akallabeth** [comment]
Interesting. Your server has been properly patched? There are reports of connection issues if some update is missing. Tested to server 2016 myself today and that build was working. Will check 2012 tomorrow.

**Comment by akallabeth** [comment]
@mihaivirag please also add the output of `wfreerdp.exe /buildconfig` so we can be sure we're talking about the correct build here.

**Comment by akallabeth** [comment]
seems to be the same issue as #4525
