### ISSUE TITLE
How to exclude key combinations?

### ISSUE THREAD

**Issue by Bebef** [FreeRDP/FreeRDP#4633]
Using xfreerdp in fullscreen (`/f`) I would like to exclude CTRL+ALT+[arrowkey] as this is the key combination to switch Workspaces.

Is there a way to do so?

Using freerdp version 2.0.0~git20170725.1.1648deb+dfsg1-7

Thanks 😄

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by Bebef** [comment]
> Please don't "report" questions as bugs

Like the document says: I didn't report a bug, I asked a question.

If you don't want people to ask questions trough the issue tracker, maybe you should say "Please don't ask questions on the GitHub issue tracker" instead. Maybe all bugs are issues, but not all issues are bugs... </hint>
