### ISSUE TITLE
Unknown Generator Ninja

### ISSUE THREAD

**Issue by adityasood11** [FreeRDP/FreeRDP#4635]
****I have Microsoft Visual Studio 2017 which has Cmake Inbuilt. 
I tried adding the folder  FreeRDP-2.0.0-rc2 to Visual Studio 2017. 
Getting the following error.****

****NOTE : I am working on Windows 10****

> " Severity	Code	Description	Project	File	Line	Suppression State
> Error		CMake Error at C:\Users\Mickey\Downloads\FreeRDP-2.0.0-rc2\FreeRDP-2.0.0-rc2\CMakeLists.txt:477 (message):
>   Unknown generator Ninja	FreeRDP	C:\Users\Mickey\Downloads\FreeRDP-2.0.0-rc2\FreeRDP-2.0.0-rc2\CMakeLists.txt	477

**This code is part of root CMakeLists.txt. Getting error in Line 477 as mentioned above.**
```
if(WIN32)
	add_definitions(-DUNICODE -D_UNICODE)
	add_definitions(-D_CRT_SECURE_NO_WARNINGS)
	add_definitions(-DWIN32_LEAN_AND_MEAN)
	add_definitions(-D_WINSOCK_DEPRECATED_NO_WARNINGS)
        set(CMAKE_USE_RELATIVE_PATH ON)
	if (${CMAKE_GENERATOR} MATCHES "NMake Makefile*")
		set(CMAKE_PDB_BINARY_DIR ${CMAKE_BINARY_DIR})
	elseif (${CMAKE_GENERATOR} MATCHES "Visual Studio*")
		set(CMAKE_PDB_BINARY_DIR "${CMAKE_BINARY_DIR}/\${CMAKE_INSTALL_CONFIG_NAME}")
	else()
		message(FATAL_ERROR "Unknown generator ${CMAKE_GENERATOR}")
	endif()
```

**Comment by adityasood11** [comment]
I am having problems understanding the project.
As we are working on Remote Desktop Protocol , we need to have a server in
one system and client in another.
We have files for both client and server in the main folder.
Do we need to build both separately or we have to build them together as a
whole.
Need clarification on this. I am not able to understand the working of
FreeRDP

**Comment by adityasood11** [comment]
How to set debug symbol paths on windows?

**Comment by akallabeth** [comment]
@adityasood11 You're mixing up quite a lot here. Cross compilers are a completely different story (like compiling windows executables on a linux machine, or arm code on x86). `if (${CMAKE_GENERATOR} MATCHES "NMake Makefile*")
		set(CMAKE_PDB_BINARY_DIR ${CMAKE_BINARY_DIR})
endif()`
is setting the debug path for `NMake`. Similar will be the one for `Ninja` but I don't know where the `.pdb` files are put with that generator.

**Comment by adityasood11** [comment]
Seems like i did not configure openssl first. 
First i configured Openssl
`cmake -DOPENSSL_ROOT_DIR=/usr/local/ssl -DOPENSSL_LIBRARIES=/usr/local/ssl/lib`
Then i specified the generator on Command Prompt.

`cmake . -G "Visual Studio 15 2017"`

Also i did not use VISUAL STUDIO IDE , instead i started working on Developer Command Prompt for VS 2017.

These steps seem to have eradicated my issue.
