### ISSUE TITLE
Need an API call to know if H264 is compiled in

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#4639]
Unfortunately, some distributions cannot have libavutil/libavcodec shipped by default, so the stock libfreerdp2 provided by the distro does not support newer GFX modes.
This is the case for Remmina and Ubuntu 18.04: Ubuntu 18.04 libfreerdp2 package, which is a copy of the Debian package, is compiled with -DWITH_FFMPEG=off, because FFmpeg package in ubuntu is in a different ~~place~~ archive area than the libfreerdp2 package.
As remmina developers we only can know this absence only after a connection to a RDP server: if instance->context->codecs->h264 is null, there is no H264 and we warn users to lower color depth.
But... ubuntu has a huge amount of different users, and some of them cannot understand the phrase "Please check Color Depth settings.", see our issue [1584](https://github.com/FreeRDP/Remmina/issues/1584). I will change that with "Please use 32bpp or less bpp color depth", but I'm sure there will be users that will not understand.
So, what I'm asking, is a way to know, via an API call, if GFX AVC (H264) modes are available on libfreerdp, but before connecting. And better if also before initializing libfreerdp (some static return).
Is it possible ?
Cc: @antenore

**Comment by akallabeth** [comment]
@giox069 with `/buildconfig` you could get that with current builds, but it may be a good idea to extend #2966 accordingly to avoid using unsupported options.

**Comment by giox069** [comment]
Thank you. I checked /buildconfig, and it calls freerdp_get_build_config(). Now I'm parsing freerdp_get_build_config() output to get WITH_GFX_H264 value.

**Comment by akallabeth** [comment]
@giox069 Just be aware that you also have to check for an available H264 backend (ffmpeg or openh264)

**Comment by giox069** [comment]
@akallabeth, it seems it's already checked on CMakeLists.txt: https://github.com/FreeRDP/FreeRDP/blob/master/CMakeLists.txt#L921
WITH_GFX_H264 is defined only when a vaild H264 backend is found... if I'm not wrong.

**Comment by akallabeth** [comment]
ah, great, did forget that check. well, then you're good to go for that :)
