### ISSUE TITLE
wfreerdp.exe immediately exits after launching showing no window.

### ISSUE THREAD

**Issue by adityasood11** [FreeRDP/FreeRDP#4641]
wfreerdp.exe is created in the release folder with other .lib , .dll and .exp files. I tried launching wfreerdp.exe but i am not getting any console output.  After going through a few articles , i got to know that i might be missing command line paramters. Need help regarding command line parameters for wfreerdp.exe.

**Comment by akallabeth** [comment]
Please do not double post (spam) the issue tracker.
