### ISSUE TITLE
About app command

### ISSUE THREAD

**Issue by sliencestorm-wyw** [FreeRDP/FreeRDP#4644]
Hello，I'm trouble in using the command  about “app command”
1：
system: CentOs 7.4  
command：xfreerdp  /u: myuser /p: mypassward  /v:myserver   /app:"notepad(example)"
command is successful,but when I closeing  the windows,  xfreerdp is not disconnect and some seconds
[INFO][com.freerdp.core] - ERRINFO_RPC_INITIATED_DISCONNECT_BY_USER (0x0000000B):The disconnection was initiated by an administrative tool on the server running in the user's session.
[15:23:58:191] [44034:44035] [ERROR][com.freerdp.core.rdp] - rdp_recv_tpkt_pdu: rdp_recv_deactivate_all() fail
[15:23:58:191] [44034:44035] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
I read some Issues ，this problem is solved，or  it's other problem cause it？

2.  After I useing xfreerdp  /u: myuser /p: mypassward  /v:myserver   /app:"notepad(example)"
I open a new tap ， try to using the same cmd to open app , but the previous will disconnet 
info：
[INFO][com.freerdp.core] - ERRINFO_DISCONNECTED_BY_OTHER_CONNECTION (0x00000005):Another user connected to the server, forcing the disconnection of the current connection.
I'm puzzle with it, why did it disconnet .APP command isn't  independent of each other？
If I want the app command independent each other and don't disturb each other . 
What should I do ? 
Thank you very much.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
