### ISSUE TITLE
Segmentation Fault - MS S2012R2 - after Update, related to 4449, 4502, 4510

### ISSUE THREAD

**Issue by UnbendingSpirit** [FreeRDP/FreeRDP#4650]
Hi everyone.

our company deployed the ms update from march to our farm last weekend, so we got the error with the expired password, everything was fine before the update.

So I downloaded the latest source and compiled it with Release, but I get a "segmentation fault" when I connect via NLA.

3 of our servers are still unpatched and the connection to them works fine.
Unfortunately, NLA is the only method to connect to the patched servers.

When I try to connect to one of the patched ones with tla or rdp, the connection gets refused after I enter the credentials and I get a new logon screen from the server I´ve been redirected to.

We use raspberries with raspbian stretch as thin client to connect via freerdp to the different servers behind a load balancer.
I nightly build is not available for arm, unfortunately.

**Comment by akallabeth** [comment]
Duplicate of #4629, fixed with #4631 
As for the nightly packages, a `ln -s packaging/deb/freerdp-nightly debian && dpkg-buildpackage` should give you a nightly for arm.
