### ISSUE TITLE
"failed to open display:" error when running, installed via macports on macOS 10.13.4

### ISSUE THREAD

**Issue by vladxdev** [FreeRDP/FreeRDP#4652]
Installed freerdp with fresh macports(just installed), installation was long and seems like was successful. 
When trying to run:
xfreerdp --version
I got:
[15:57:27:868] [63282:b5944380] [ERROR][com.freerdp.client.x11] - failed to open display: 
[15:57:27:872] [63282:b5944380] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.

What value should I assign for $DISPLAY on macOS ?
Do I need any other installation to be able to run xfreerdp? Is there any article/description on how to fully setup freerdp on mac via macports, brew or even by compiling sources?

macOS 10.13.4

Thank you.

**Comment by akallabeth** [comment]
@vladxdev Don't know exactly, but I assume you need to start `xfreerdp` from the `X11` Terminal. Anyway, please consult the macports specific issue trackers, we don't know exactly how they compile/distribute/...

**Comment by vladxdev** [comment]
Well.. sorry, but I don't understand this. On your github pages and on http://www.freerdp.com/ you have instructions to compile/install/run on macOS, for example:
MacPorts includes freerdp as well: sudo port install FreeRDP.
And this instruction is not working. This is the problem. 

I don't see any "X11 Terminal" in my macOS - do you have it in your macOS? 

On this page https://github.com/FreeRDP/FreeRDP/wiki/Compilation  you have instructions to compile under macOS. 
So, let's say I did compile freerdp from sources(I'll try that later) on macOS. What _another_ software/settings are required to run xfreerdp on macOS?
Does it expect some 3rd party X11 server implementation running on my macOS or does it use macOS built-in featured to draw window etc?

You advertise macOS support for your project, so I believe there should be some help when one is trying to use FreeRDP on macOS. Otherwise it is logical that you should not mention macOS support, so there will be no questions for your github project. 

Thanks for clarifications.

**Comment by akallabeth** [comment]
@vladxdev I think this is your issue https://support.apple.com/en-us/HT201341 you need to install that to run X11 applications.

**Comment by vladxdev** [comment]
Thank you for additional info, I really appreciate this.

1. about MacPorts. I understand. But I believe the initial question is not related to macports, but for using of FreeRDP on mac, which I assume is a correct question here, as FreeRDP project mentions the support of macOS officially.

2. Yes, I was installing "freerdp" in macports, but the executable name is "xfreerdp". Again, as user of macOS, I know almost nothing about "X11 environment" and just want to use freerdp to connect to Windows system. I believe it will be good for FreeRDP project to have more detailed information about compilation/using/configuration/setup/etc of freerdp on modern mac and keep that information correct after macOS updates. Or again, it will be honest to say on pages "we are not checking how FreeRDP is working now on macOS, we have some obsolete instructions, find detailed or up-to-date information somewhere else". Just my opinion, don't want to look rude, I appreciate your(and others) work on this project. 
Just want to show how the situation looks like from my point of view - a macOS user who decided to install and try FreeRDP to connect to Windows system.

3. Didn't know about mFreeRDP, will check its details. Thank you. 

4. About XQuartz, thank you, will check. So, it seems like I have to install another one part(x-server) in addition to freerdp? 
So, freerdp will connect to that X-Server to show a local GUI, and also will connect to RDP server to "get" the screen of remote PC. 
I saw mentions that FreeRDP could be compiled for iOS/Android and wander if X-Server also should be running these also?

**Comment by vladxdev** [comment]
@akallabeth Thank you for your time, really :-) But using your kindness, I'd ask to help me to understand that relationship between FreeRDP/xFreeRDP/mFreeRDP/X11 and iOS/Android GUI. 
Probably this can help another one like me and you can drop him the link to this thread and don't spend your time :-)

Is xFreeRDP actually some "base" FreeRDP + some X11 "frontend" module compiled together to show GUI via X11 server? 

Is mFreeRDP a same "base" FreeRDP but with "native macOS" frontend module to show GUI? 
And so, in iOS/Android there is a special "iOS native" & "Android native" frontend modules used during the compilation?

Also, do I understand correctly, that actually it is better to install X11 server and use xFreeRDP (more mature and more active development) than trying mFreeRDP? Hope you can help here. Thanks again.

**Comment by akallabeth** [comment]
You got it quite right.
The rdp protocol and network related stuff is in a core library.
Each platform has some frontend (client)

And yes, if you can live with what mFreeRDP provides, it might be the better choice, otherwise the X11 route is currently the only way to go

**Comment by vladxdev** [comment]
mFreeRDP - is it https://github.com/FreeRDP/FreeRDP/blob/master/client/Mac/
?

**Comment by vladxdev** [comment]
I mean https://github.com/FreeRDP/FreeRDP/tree/master/client/Mac  ?
If so, is it possible to ask for some help/comments on how I can try to build it ? Are there some notes/comments for this?
Or does it exist in binary form for mac ?

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/tree/master/docs

**Comment by vladxdev** [comment]
@akallabeth Thank you again! If I'll be able to, I will contribute back for mFreeRDP (detailed instructions, probably fixes in code etc). 

Having an opportunity to asking you, please allow to ask regarding openssl when compiling FreeRDP and mFreeRDP in particular. 

I was trying to compile xFreeRdp (not mFreeRDP) on macOS earlier, and as was said, Apple don't provide openssl on Mac anymore, and so we need to install it from brew or from macports. But! Currently FreeRDP tries to access "FIPS" extensions in openssl when on linking stage, and as I can say after some research - nor homebrew nor macports provides opeenssl with FIPS extensions, just openssl without FIPS. Even more, I was reading that openssl project don't recommend/provide to enable/compile FIPS on macOS system - in their PDF document macOS was not in list of systems that could use FIPS. 
(Sorry for not exact terms, I don't understand the details yet, just common things regarding this FIPS and openssl on mac)

So, could you recommend the workaround for this situation? Can I somehow disable using of "FIPS" in FreeRDP so "usual" openssl could be used to build? If so, will that break some compatibility with Microsoft RDP server on Windows? If we really need FIPS in FreeRDP but openssl don't provide/recommed/etc FIPS on macOS platform - what we can do? 
I saw that you are trying to create/use your own encryption layer which will internally use different "backends" like openssl or other system. Is there any progress in using Apples's native encryption libs  instead of openssl on mac(& ios?) platform? I assume this will be a real "solution" for the issue.

I appreciate any comment on this or even simple link to help me move forward on this problem.

**Comment by akallabeth** [comment]
@vladxdev would suggest moving the discussion to IRC or mailinglist.
As for the fips stuff, that is untested on mac, so maybe there is only a preprocessor directive missing disabling it.

**Comment by vladxdev** [comment]
@akallabeth OK, will try mailinglist, hope you can help there also :-) Just sent the initial mail into the list.
