### ISSUE TITLE
wfreerdp can't fullscreen on 1366x768 resolution

### ISSUE THREAD

**Issue by raid2000** [FreeRDP/FreeRDP#4656]
hi, everyone

When the Client screen resolution is 1366x768 or change to 1366x768, wfreerdp can't display the remote desktop by running with option '/f'，only have the green bar on the top. I can switch it to window mode, the remote desktop can be showed.

It can be 100% reproduced, I've tried a lot of version, builds from cloudbase and ci.freerdp.com, and I also tried in different environment Win7, win10, Laptop, PC, even in VM.

Other resolution like 1920x1080 1024x768, even 1360x768 is working fine in full screen mode.

Is there anyone have same issue, or have any idea to resolve this?

Thanks
Ray

**Comment by raid2000** [comment]
This is very common resolution of laptop, does anyone can confirm this problem and fix it?

thanks

**Comment by anilgmaipady** [comment]
I launched the FreeRDP with resolution 1366x768 using command:

wfreerdp.exe /v:127.0.0.1 /u:user3 /p:Test123# /size:1366x768 /cert:ignore /log-level:TRACE 

and it looks like the screen resolution actually setting set is 1368x786

I have  verified this using:
- Get the session id using "query session" 
- Capture the screenshot using - PsExec.exe -s -i <FreeRDP-Session-ID> nircmd savescreenshot C:\Windows\Temp\sc.png 
- The resolution of sc.png is 1368x768 not 1366x786 
- If I use mstc.exe and launch with 1366x768 the screenshot will have resolution 1366x786 Is there a work around to get the 1366x768 working ?

**Comment by GeniusbutLazy** [comment]
Ok fixed the issue just had the comment the following line ( FreeRDP\Client\Windows\wf_client.c)
desktopWidth = (desktopWidth+3) & (`3);
Hope it helps
