### ISSUE TITLE
Protocol Security Negotiation Failure and Memory leaks

### ISSUE THREAD

**Issue by 2f6465762f6e756c6c** [FreeRDP/FreeRDP#4663]
Hi

I'm not sure if this behavior is due to a bug or configuration issue on client or server side.  
That said i would still appreciate tipps if its not a bug.

My client runs Xenial Xerus and the connection that can't be established is to a RDS Farm with gateway and load balancer. I got reports that it works fine with red hat.  

I Compiled version 2.0.0rc2 on the 14. may on my own.  
The Debug output of the connection looks fine up to this point:
```
[13:46:23:550] [4616:4617] [DEBUG][com.freerdp.core.gateway.rdg] - Channel error 800759da  
[13:46:23:550] [4616:4617] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure  
[13:46:23:551] [4616:4617] [ERROR][com.freerdp.core] - freerdp_set_last_error  ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]  
[13:46:23:551] [4616:4617] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure  
[13:46:23:551] [4616:4617] [DEBUG][com.freerdp.core.transport] - transport_check_fds: transport_read_pdu() - -1  
[13:46:23:551] [4616:4617] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1  
```

I then tested the nightly build and got these additional errors at the end:
==6242==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 112 byte(s) in 1 object(s) allocated from:
```
#0 0x7f12721ea602 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98602)
#1 0x7f126cf97e77 in CRYPTO_malloc (/lib/x86_64-linux-gnu/libcrypto.so.1.0.0+0x62e77)
```

SUMMARY: AddressSanitizer: 112 byte(s) leaked in 1 allocation(s).

/opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 2.0.0-dev3 (1cb14010a)

**Comment by akallabeth** [comment]
@2f6465762f6e756c6c could you post your command line, `xfreerdp /buildconfig` and setup details?
from the message I see you have a gateway, so maybe try our nightlies first too, as there have been some fixes since rc2 regarding gateway.

**Comment by 2f6465762f6e756c6c** [comment]
@akallabeth 
The buildconfig for the version that i compiled myself is:
This is FreeRDP version 2.0.0-dev3 (c5b84db)  
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=on WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=on WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=off WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Debug  
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g  
Compiler:            GNU, 5.4.0  
Target architecture: x64

I already tested it with a nightly build too with this buildconfig:
This is FreeRDP version 2.0.0-dev3 (1cb14010a)  
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo  
CFLAGS:              -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fno-omit-frame-pointer  
Compiler:            GNU, 5.3.1  
Target architecture: x64

The parameters that i used for both are:
xfreerdp -clipboard /log-level:TRACE /g:$GatewayFQDN /v:$TargetFQDN /d:$Domain /u:$Username /cert-ignore /load-balance-info:"tsv://MS Terminal Services Plugin.1.Sci"

**Comment by akallabeth** [comment]
Ok, you don't by chance have the version on redhat that is working?

**Comment by 2f6465762f6e756c6c** [comment]
The information that i have on it is:
OS: Red hat Linux 6  
xfreerdp: compiled end of march  
same parameters used for connection.

**Comment by drickeALP** [comment]
Same error here, also using Xenial. 
```
~$ /opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 2.0.0-dev3 (9460f4292)
```

**Comment by p-pautov** [comment]
```
[13:46:23:550] [4616:4617] [DEBUG][com.freerdp.core.gateway.rdg] - Channel error 800759da
```
According to [this table](https://msdn.microsoft.com/en-us/library/hh881151.aspx) it's `E_PROXY_RAP_ACCESSDENIED`. Try connect with "allow any host" RAP (Resource Authorization Policy) configured on the RD Gateway.

**Comment by 2f6465762f6e756c6c** [comment]
@p-pautov 
Thanks for the useful return code table link.  
I don't have the permissions to modify the RAP of the Gateway myself, but I'll write to the people in charge.

**Comment by 2f6465762f6e756c6c** [comment]
I can confirm that Channel error 800759da is due to the RAP  configuration of the Gateway.
The policy was temporary modified to allow any and it worked.

**Comment by sebastianuw** [comment]
I've been getting the same 

`[ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure  
[ERROR][com.freerdp.core] - freerdp_set_last_error  ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]  
[ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure  `

when connecting to Windows 2016 RDS farms. I've experienced this on both Centos 7.4 and 7.5. 

The problem began with commit f8c3918, before that freerdp connected happily.

**Comment by 2f6465762f6e756c6c** [comment]
I think this issue should get added to the 2.0-rc3 milestone.
If i can do further tests to narrow the scope of the bug please let me know.
In my case the RDS SessionHosts, ConnectionBrokers and Gateways all run on Windows Server 2012 btw.

**Comment by akallabeth** [comment]
So, is this issue resolved as 'not our fault' or do I misread this thread?

**Comment by 2f6465762f6e756c6c** [comment]
@akallabeth I wouldn't say that, the error that me and 2 others received is due to RAP policy on the gateway. But the same policy doesn't fail when using 2.0.0-rc2 so a change to FreeRDP since then is at fault if you ask me.

**Comment by UnitedMarsupials** [comment]
FWIW, upgrading to 2.0.0r3 helped me -- had to remove the `/sec:rdp` from the command line, though.

**Comment by sebastianuw** [comment]
I pulled in the latest, and the problem looks to be resolved. Thanks!

**Comment by Olen** [comment]
Getting the same error, even with latest nightly.

It works with freerdp-2.0.0-41.20180405gita9ecd6a.fc28.x86_64 but no rpms after that.

FWIW I also tried adding -sec-rdp to the command line but that seemingly does not change anything.

Unfortunately I am unable to change anything on the servers, as this is a hosted solution run by a 3. party.

**Comment by Olen** [comment]
@gsacre Did you test the latest nightly?
Are you experiencing the same issue as i describe in #5069 ?

**Comment by gsacre** [comment]
@Olen, I have tried with RC4 compiled on my machine: no luck.
I cloned the repository, use commit e7a44bc437258dd3734ea7a7a710d709d4c6e11b: **it worked!**

Well done guys, this is really fantastic! It's working, it's stable (with RC2, I was getting random disconnects, here, a whole hour without issue before I logged off).

Thanks!

**Comment by akallabeth** [comment]
@gsacre Good to know, thx for the feedback.
