### ISSUE TITLE
wfreerdp-server is not getting created on windows10

### ISSUE THREAD

**Issue by adityasood11** [FreeRDP/FreeRDP#4666]
Its very much possible that this is a bug. I am trying to create wfreerdp-server using the build option 
-DWITH_SERVER=ON but still no sign of wfreerdp-server.exe in the debug folder.
 
freerdp-shadow-cli.exe is created when i use -DWITH_SERVER=ON as a build option.
Also if i add -DWITH_SAMPLE=ON i am able to create sfreerdp-server.exe

But i am not able to create wfreerdp-server.exe.

@bmiklautz  @awakecoding  thoughts?

OS : Windows 10 64bit

**Comment by adityasood11** [comment]
I can see that after successful building my solution file. 
The final build result is 
44 Succeeded , 0 failed and 2 SKIPPED.

I am guessing that the build getting skipped might contain my wfreerdp-server file.

**Comment by adityasood11** [comment]
The two projects that are getting skipped are 
INSTALL AND PACKAGE (my guess is they are of root directory containing the main solution file)

**Comment by adityasood11** [comment]
I have somehow been able to build the remaining 2 projects.
 After successfully building all the projects , stll i am NOT able to generate SERVER file for WINDOWS.

**Comment by adityasood11** [comment]
These are the files that are created after the final building of solution file

![image](https://user-images.githubusercontent.com/30553910/40408741-2d1d8dfe-5e86-11e8-9e4c-360c689c4962.png)

![image](https://user-images.githubusercontent.com/30553910/40408783-50cf66fa-5e86-11e8-89b2-9592c300a716.png)

**Comment by finepeilei** [comment]
i have not bulit the wfreerdp-server on windows,the server is deploy according to the windows rdp server!

**Comment by adityasood11** [comment]
@finepeilei So you are just connecting your freerdp client to microsoft's server?

**Comment by finepeilei** [comment]
@adityasood11 yes~

**Comment by adityasood11** [comment]
@finepeilei Any idea how to build wfreerdp-server on window 10 64bit ?|

I have already created wfreerdp(client) , freerdp-shadow-cli and sample server on my system.

**Comment by adityasood11** [comment]
![image](https://user-images.githubusercontent.com/30553910/40538076-427cd232-602e-11e8-91a2-c2697e8879b2.png)

**Comment by lgenius777** [comment]
Hi, I have a same problem as your.
Since I modify sever part's  cmakelist "add_subdirectory(Windows)", and modify some define in windows server's source code. The wfreedp-server.exe can be compiled but can not run right.
How about yours? Can your server accept client and run right?
