### ISSUE TITLE
xfreerdp crashed when copy files that bigger than about 8MB from usb disk to server via gateway connection.

### ISSUE THREAD

**Issue by VizXu** [FreeRDP/FreeRDP#4667]
bug reproduce:
1. Ubuntu14.04 as a client while server2012 or server2016 as a gateway.
2. extend the usb disk as file system to redirect to server.
3. copy a big file, which about 8MB or bigger, from usb disk to server.
4. the xfreerdp crashed immediately.

some personal opinions:
1. xfreerdp has no send flow control acknowledges mechanism implement when sending data to server
2. the current xfreerdp gateway implement should be re-designed?

**Comment by akallabeth** [comment]
Which version did you use? Nightly/self compiled/...

**Comment by akallabeth** [comment]
Yes, this seems like a serious issue.
Still, the info about the client requested in the issue template would be highly appreciated as it cuts down time for analysis/fix/test etc.

**Comment by VizXu** [comment]
thank for you reply, I really appreciate you can fix the bug as soon as possible.

**Comment by VizXu** [comment]
it there any update of this issue?

**Comment by VizXu** [comment]
any updates？

**Comment by akallabeth** [comment]
@VizXu Please stop spamming this thread, the issue will be fixed when there is time.

**Comment by VizXu** [comment]
@akallabeth  I added usleep and send_flow_control acknowledge in this thread and it seems work, but when I copy big file, for example 3GB，it also will be cut off. Besides, the mouse and keyboard input event will be delay and the windows seems to be frozen. So this maybe not a resolution but just a work-around.
Maybe your people have a well understand about rdp protocol and could give a resolution.
Thanks.

**Comment by akallabeth** [comment]
works with 3.x (although could be faster)
