### ISSUE TITLE
Right control doesn't release keyboard grab

### ISSUE THREAD

**Issue by charlesg99** [FreeRDP/FreeRDP#4668]
Hi, not sure if this was intended, but I can't find a mention of it. Since I upgraded from 2.0.0_rc2-1 to 2.0.0_rc2-2, the right ctrl key doesn't release the keyboard anymore, so the host shortcuts aren't accessible when in fullscreen. This seems like a regression to me. I'm connecting to a Windows 2012 R2 machine. Thanks!

**Comment by akallabeth** [comment]
Please clarify, which versions arr you talking about?

**Comment by charlesg99** [comment]
Sorry I was using the arch package names... It doesn't work on 2.0.0-rc2, but it worked on 2.0.0-rc1.
Thanks

**Comment by Zjemm** [comment]
I have the same thing:

**Comment by codemuse** [comment]
I have the same issue, downgrading back to 2.0.0-rc1 didn't help for me either, so maybe it is a combination with another package upgrade. I'm on Arch Linux, if I can find what other upgrade broke it I'll report back.

**Comment by akallabeth** [comment]
Just did a diff between these versions (rc1 and rc2), the X11 client did not receive any keyboard related changes.

**Comment by akallabeth** [comment]
So, can this be closed?

**Comment by codemuse** [comment]
I would not think so, it seems that right ctrl ungrab doesn't work in combination with the latest xorg update. I guess that is not a bug in Xorg, but probably something that changed in Xorg that is problematic for FreeRDP, not?

I would propose someone else test with the latest Xorg to see if the issue is reproducable on other distributions. @charlesg99 seems to be on Arch Linux as well, what about @Zjemm?

**Comment by akallabeth** [comment]
@codemuse wouldn't think that that is the case. We only check flags in xevents, so if that actually changed a lot of software is in deep trouble. Maybe some packaging issue with the latest version?

**Comment by codemuse** [comment]
Maybe. I filed https://bugs.archlinux.org/task/58756 in the Arch Linux bugtracker.

**Comment by Zjemm** [comment]
I'm also on arch and did a rollback xorg-server-common and rebooted my system. but it did not fix the issue

**Comment by Zjemm** [comment]
so a patch is underway?
