### ISSUE TITLE
Unknown key with X keycode

### ISSUE THREAD

**Issue by sliencestorm-wyw** [FreeRDP/FreeRDP#4669]
When I used a software（VNC protocol） to using freerdp. when I used local keyboard's input method.
It will print “Unknown key with X keycode xxxxxx”.Just use English input is right. The windows system code is unicode . But the linux is utf-8. Is it not incompatible with the unicode ? Or  it must use utf-8？

**Comment by akallabeth** [comment]
This is #4215, there seems to be no proper solution.
