### ISSUE TITLE
Devel: where is the script processing rdpSettings?

### ISSUE THREAD

**Issue by informatimago** [FreeRDP/FreeRDP#4673]
Sorry to ask here; I subscribed to freerdp-devel@sourceforget.net, but my emails get rejected for "unknown user" (and yes, I checked that I was sending them from the same address as in my sourceforge account).  In the meantime, could you tell me:

In settings.h, there's a section of \#defines with a comment indicating that it is generated automatically by a script parsing the rdpSettings data structure.

But I cannot find (grep) this script in the sources. Does it exist? Where is it?

**Comment by informatimago** [comment]
Note, if it doesn't exist, I just wrote one; it'll be commited soon and PR'ed later.

**Comment by akallabeth** [comment]
No, currently there is none.
Would welcome a pull for your addition! Thx

**Comment by akallabeth** [comment]
generator script `scripts/update-rdpSettings` in repo.
