### ISSUE TITLE
askina

### ISSUE THREAD

**Issue by goshavart** [FreeRDP/FreeRDP#4676]
Здравствуйте. Давно слежу за продвижением вашего проекта, который мне сразу понравился.
и поскольку свой уже закончил решил дать вам несколько советов, которые, на мой взгляд, 
вам помогут.

К сожалению, необходимо менять структуру проекта.
Вот например как сделал я:
1) BitBlt, CGContextDraw и прочее во внутренние хранилище (1600х900=5mg)
2) сверка изменений.
3) wic, gdi и прочее для кодирования в нужный вам формат (jpeg, png и прочее).
4) отправка клиенту.

FreeRDP-WebConnect
Нельзя допустить чтобы изображение заходило в blob! Не один браузер не выдержит даже 
30 секунд. Даже минимум в формете jpg: 300kb*24(кадра в секунду)*10(секунд)=72mg.
Для примера: если обычный компьютер прекрасно работает для 24-х кадров в секунду, то android или ipad выдерживают без blob только 15-18 кадров в секунду.

В любом случае, желаю вам успеха, и уверен всё у вас ПОЛУЧИТСЯ!
https://www.youtube.com/watch?v=PGd9fkZXNOc
https://www.youtube.com/watch?v=-9kyF4a2xnA
https://www.youtube.com/watch?v=cpgeDCnOe4s

**Comment by hardening** [comment]
@goshavart spoken language for the FreeRDP project is English, please report issues in English.

**Comment by goshavart** [comment]
Hello. For a long time I've been following the progress of your project, which I immediately liked.
and since I've already finished I decided to give you some advice that, in my opinion,
you will be helped.

Unfortunately, it is necessary to change the structure of the project.
For example, as I did:

BitBlt, CGContextDraw and so on in internal storage (1600х900 = 5mg)
verification of changes.
wic, gdi and so on to encode into the format you need (jpeg, png and so on).
shipping to the customer.
FreeRDP-WebConnect
You can not allow the image to go into a blob! Not one browser can not stand even
30 seconds. Even a minimum in the jpg format: 300kb * 24 (frames per second) * 10 (seconds) = 72mg.
For example: if a normal computer works fine for 24 frames per second, then android or ipad can withstand only 15-18 frames per second without blob.

In any case, I wish you success, and I am sure everything will be GONE!
https://www.youtube.com/watch?v=PGd9fkZXNOc
https://www.youtube.com/watch?v=-9kyF4a2xnA
https://www.youtube.com/watch?v=cpgeDCnOe4s
