### ISSUE TITLE
/dynamic-resolution is broken

### ISSUE THREAD

**Issue by andicheesi** [FreeRDP/FreeRDP#4679]
The dynamic resolution feature is broken. Resizing windows results in unforeseen resize behavior. Especially at switching from fullscreen to smaller window and back.
One behavior are the drawing artifacts coming from resizing window from fullscreen to small resolution. So the screen content of fullscreen will stay in background
Other behavior is resizing from small resolution to fullscreen or other direction several times. Sometimes it will result in  a behavior FreeRDP will resize back to previous size without interaction

1. Start with xfreerdp /u:user /p:password /d:DO /dynamic-resolution /v:hostname
2. Switch to fullscreen and back several times
3. Resizing window manually 
Steps 2 and 3 will result in described errors after some tries

**Expected behavior**
Resize should stay as choosen.
No screen artefacts should be visible. I have just removed some internal icons

**Screenshots**
This shows the behavior after resize from fullscreen to smaller resolution
![artefacts](https://user-images.githubusercontent.com/39732114/40657923-cfc87c9a-6349-11e8-983a-7142896df548.png)
* Version of FreeRDP
Latest master : Commit e90184cc593d722eaabbad8a7e53b252c18462c2
* Command line used
xfreerdp /u:user /p:password /d:DO /dynamic-resolution /v:hostname
* output of `/buildconfig`
[buildconfig.log](https://github.com/FreeRDP/FreeRDP/files/2048120/buildconfig.log)
* OS version connecting to
Windows 10 Enterprise 64Bit
Version 1703
Build 15063.1088
[xfreerdp_screenartifact.log](https://github.com/FreeRDP/FreeRDP/files/2048109/xfreerdp_screenartifact.log)
[xfreerdp_wrongresize.log](https://github.com/FreeRDP/FreeRDP/files/2048110/xfreerdp_wrongresize.log)

` 

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by akallabeth** [comment]
Could you check if this is indeed a client error?
I've seen such a screenshot once and the reason was that the server side graphics driver was in a faulty state.
(we might have to tune the frequency of resolution updates if that is the case)

**Comment by andicheesi** [comment]
If I disable the the timer in xf_disp.c  and so I always call the  xf_disp_sendResize then I would get a much better behavior and display will be not distorted. The only problems then are : 
- the slow performance
- if I cause a lot of resizing and then do fullscreen this event will come not as the last resize event

I fear the order of the x-events ( fullscreen and resize) is not garantueed.

**Comment by hardening** [comment]
and if you remove the timer it may also crash win2k12 (the server itself) when we send too many resizes.

**Comment by andicheesi** [comment]
I see one bug now. 
All events within the timeout will be blocked. And the problem is that all events after the last accepted resize events will be not done.  E.g. Resizing the the window several times and then press fullscreen --- very often the fullscreen will be ignored because it will be within the ignore timeout

**Comment by hardening** [comment]
@andicheesi yes I was not completely happy with the way I've managed resizes (so that we don't get too many of them). I guess I should have a look again on this.

**Comment by andicheesi** [comment]
I just did a rough prototype where I changed 3 things:
1. When I get a ConfigureNotify I do a XCheckTypedWindowEvent for this windows and just send out only the last one
2. I disabled all checks for timer and disabled all "delayed resize" code
3. I just sleep for 200ms after each xf_disp_sendResize if I am within the RESIZE_MIN_DELAY
Then everything works fine

**Comment by andicheesi** [comment]
I wanted to hear about your opinion about such approach. And I have no clue what is "delayed resize" implementation is good for. 
The problem with my solution is I will sleep always after getting a resize notification.
