### ISSUE TITLE
Informing the user about error

### ISSUE THREAD

**Issue by ekorneechev** [FreeRDP/FreeRDP#4687]
Add informing the user at startup xfreerdp when an error occurs in the option or a non-existent option
And do not just display usage.... 
Because if there are many options in the startup command, you have to delete one each to search for an error ...

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by ekorneechev** [comment]
This is FR!! Please, reopen.
