### ISSUE TITLE
USB key detection

### ISSUE THREAD

**Issue by rike50** [FreeRDP/FreeRDP#4688]
Hi,

here is my configuration :

- Clients : different type of thin client igel, OS : Linux LX 10.04.100.01 (latest firmware) based on kernel 4.15.15, also tested with multiple previous firmware did not help
- Server : VM 2012 R2 Std (TSE)

- igelrdp 2.2 (shown with --version) is used (based on freerdp) with /usb:'rules:allow'. I can't use --buildconfig (maybe is there another option ?)

- Issue : Every USB key connected on IGEL OS is detected, but some of them are not detected on the remote sessions with freerdp (anyway it's FAT32, NTFS...)
If i use these keys with any windows client and remote desktop connection, they are detected on the remote sessions (same server)

I don't know if it's a bug or a missconfiguration or a compatibility issue, i'm totally lost about this. I know that as it's igelrdp and not really freerdp, maybe i 'll not get help here. But igel assistance didn't help me so i try here.

Tell me if you need more informations.

Thank you very much

**Comment by hardening** [comment]
As you can guess we have enough with our bugs, we don't support the IGEL client even if it's based on FreeRDP.
