### ISSUE TITLE
Developer Documentation: creation of a new test directory?

### ISSUE THREAD

**Issue by informatimago** [FreeRDP/FreeRDP#4691]
**Is your feature request related to a problem? Please describe.**

I created a new test directory with a new test (eg. channels/smartcard/client/test/); I created a CMakeLists.txt file in there listing my test sources.  However, those tests don't get compiled and run. What shall I do to register them? (I tried to grep other test names or test directory parent names without finding obvious references).

**Describe the solution you'd like**

A documentation paragraph in the developer documentation (or the wiki) indicating how to proceed would be nice.  Thanks.

**Describe alternatives you've considered**
I've considered asking on irc, but I'm at work, behind a firewall that doesn't allow irc. :-(

**Additional context**

[CMakeLists.txt](https://github.com/FreeRDP/FreeRDP/files/2062544/CMakeLists.txt)

**Comment by informatimago** [comment]
I found that adding: 
```
if(BUILD_TESTING)
	add_subdirectory(test)
endif()
```
in the CMakeLists.txt of the parent directory made it compile the tests.  Is that the right way to do it?

**Comment by informatimago** [comment]
Also needed in test/CMakeLists.txt specifying the library of the module to link with, eg. smartcard-client in this example:
```
target_link_libraries(${MODULE_NAME} ${${MODULE_PREFIX}_LIBS} smartcard-client)
```

**Comment by hardening** [comment]
@informatimago there's some nice web interface for IRC...

**Comment by informatimago** [comment]
Hi!
I've added a wiki page documenting this procedure.  
https://github.com/FreeRDP/FreeRDP/wiki/Add-a-new-test-subdirectory
I guess you may close the issue now.
Thanks.
