### ISSUE TITLE
ChromeOS (Crostini) multi-monitor not working

### ISSUE THREAD

**Issue by nathankurtyka** [FreeRDP/FreeRDP#4692]
Hello!

I'm attempting to use FreeRDP on ChromeOS/Crostini, and have found that multi-monitor support doesn't work. /monitor-list will correctly list the monitors, but I'm unable to get 2 displays.

I'm definitely in the minority using Crostini, but there will probably be more of us once Google promotes the feature from their Dev channel.

Let me know what data I can provide. But below are the version and output of the monitors list:

This is FreeRDP version 2.0.0-dev3 (73588bc2b)

 /monitor-list
        [0] 3424x2285   +0+0
        [1] 3840x2160   +0+0

**Comment by hardening** [comment]
Hum, for some reason both of your monitors are in (0,0), that may explain your issue...

**Comment by nathankurtyka** [comment]
Interesting! FWIW, I believe that 0,0 is how Crostini will report all displays. 

Is there any workaround if that's the data returned by the OS?

**Comment by hardening** [comment]
well it looks like a crostini bug in their Xrandr or Xinerama implementation (don't know which one we're using in this case)

**Comment by nfuchs21** [comment]
Has anyone figured this out or made any advances in troubleshooting?

**Comment by Alexfebbraio** [comment]
I have the same problem. is there a solution?

**Comment by fazleskhan** [comment]
Trying to configure multimon client with xfreerdp on Chromeos 107.0.5 in a Debian GNU/Linux 11 (bullseye) vm and am having the same issue as the OP

:~$ xrandr
Screen 0: minimum 16 x 16, current 2560 x 1440, maximum 32767 x 32767
XWAYLAND0 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 677mm x 381mm
   2560x1440     59.96*+
XWAYLAND1 connected 2560x1440+0+0 (normal left inverted right x axis y axis) 677mm x 381mm
   2560x1440     59.96*+

:~$ xfreerdp /monitor-list
        [0] 2560x1440   +0+0
        [1] 2560x1440   +0+0

Is there a way to correct the +0+0 configuration of the second monitor?
