### ISSUE TITLE
microphone issue with alsa and pulse backend  commit:-73588bc2b51a722d31acb81f905063cf896294c8

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#4693]
client OS :- Xubuntu  16.04 _x86
server OS :- windows 2016

xfreerdp /cert-ignore -toggle-fullscreen /title:xxxx  /bpp:32 /f    /sound /microphone:sys:alsa  /d:xxx /u:xxxx  /v:xxxx  /p:xxx
[14:11:05:269] [2967:2968] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[14:11:05:269] [2967:2968] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[14:11:05:269] [2967:2968] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[14:11:05:269] [2967:2968] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[14:11:06:367] [2967:2968] [ERROR][com.winpr.timezone] - Unable to find a match for unix timezone: Asia/Kolkata
[14:11:06:003] [2967:2968] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[14:11:06:003] [2967:2968] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[14:11:06:069] [2967:2968] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[14:11:06:088] [2967:2968] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel audin
[14:11:06:088] [2967:2968] [INFO][com.freerdp.channels.audin.client] - Loaded alsa backend for audin
[14:11:06:108] [2967:2981] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd
Segmentation fault

**Comment by gnshkl1** [comment]
no microphone input working either with alsa or pulse backend 
Floating point exception with pulse backend 
it was working with commit version :-This is FreeRDP version 2.0.0-dev (git 2.0.0-rc0)

**Comment by akallabeth** [comment]
Nightly self compiled or system package? Output of /buildconfig?

**Comment by akallabeth** [comment]
Also check with nightly if already fixed (if not already done)

**Comment by alexus26** [comment]
xfreerdp /buildconfig
This is FreeRDP version 2.0.0-dev3 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=off HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=on WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=on WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=on WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=OFF WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wno-format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wno-format-security  -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
Compiler:            GNU, 5.4.0
Target architecture: x64

I have same trouble after latest update =(

**Comment by akallabeth** [comment]
Looks like a bug in `freerdp_dsp_encode_ms_adpcm`
