### ISSUE TITLE
There is no way to ignore proxy in env.var 

### ISSUE THREAD

**Issue by cubic599** [FreeRDP/FreeRDP#4697]
I added "no_proxy" in env.var and tried use freerdp with "/proxy:" but i could not connect to the RDP Server.

My situation is:

I have a proxy in my LAN and I set it as env.var

admin@dt1:~$ cat /etc/environment 
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
no_proxy=127.0.0.1,localhost
http_proxy=http://192.168.2.253:3128/
https_proxy=http://192.168.2.253:3128/

Then I connected to a remote host via ssh with port forward
ssh user@123.456.789.147 -L13389:192.168.1.44:3389

I tried to connect to RDP server
xfreerdp /v:127.0.0.1 /port:13389 /u:user

I got

[11:42:50:309] [5705:5706] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[11:42:50:653] [5705:5706] [INFO][com.freerdp.client.x11] - Property 269 does not exist
[11:42:50:807] [5705:5706] [INFO][com.freerdp.core.proxy] - Parsed proxy configuration: http://192.168.2.253:3128
[11:42:50:809] [5705:5706] [ERROR][com.freerdp.core.proxy] - HTTP Reply headers too long.
[11:42:50:809] [5705:5706] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[11:42:50:809] [5705:5706] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[11:42:50:809] [5705:5706] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure

tcpdump showed me that freerdp sent packets to proxy not to the port 13389 on localhost.

admin@dt1:~$ xfreerdp /version
This is FreeRDP version 2.0.0-dev3 (n/a)

admin@dt1:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

admin@dt1:~$ xfreerdp /buildconfig
This is FreeRDP version 2.0.0-dev3 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=off HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=on WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=on WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=on WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=OFF WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wno-format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wno-format-security  -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
Compiler:            GNU, 5.4.0
Target architecture: x64

**Comment by hardening** [comment]
Yeah we don't implement anything regarding the `no_proxy` env var.
I've always think that using http_proxy without specifing anything was not a good idea BTW. You can workaround the "behaviour" (bug ?) by unsetting the `http_proxy` and `https_proxy` env variables.

**Comment by pingunaut** [comment]
+1

**Comment by svetoi1985** [comment]
For some reason, the xfreerdp connection does not work, freerdp /sec:tls / used to workv:xxx.xxx.xxx.xxx /cert-ignore /f
[16:09:52:225] [1311:1312] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[16:09:52:225] [1311:1312] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[16:09:52:260] [1311:1312] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[16:09:52:260] [1311:1312] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[16:09:52:261] [1311:1312] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: root
[16:09:52:586] [1311:1312] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[16:09:52:690] [1311:1312] [INFO][com.freerdp.core.proxy] - Parsed proxy configuration: http://10.55.1.4:3128
[16:09:52:690] [1311:1312] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[16:09:52:690] [1311:1312] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[16:09:52:696] [1311:1312] [ERROR][com.freerdp.core.proxy] - HTTP Reply headers too long: HTTP/1.1 407 Proxy Authentication Required
[16:09:52:697] [1311:1312] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[16:09:52:697] [1311:1312] [ERROR][com.freerdp.core] - rdp_client_connect:freerdp_set_last_error_ex ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[16:09:52:697] [1311:1312] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
root@server:~# xfreerdp /buildconfig
This is FreeRDP version 2.3.0 (2.3.0)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type: RelWithDebInfo
CFLAGS: -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler: GNU, 10.2.1
Target architecture: x64
Debian 11
Proxy is configured without it I can't
I tried everything, maybe the script is what it is.
help

**Comment by piotr-dobrogost** [comment]
I was also surprised by FreeRDP not respecting `NO_PROXY` when using KRDC – https://discuss.kde.org/t/how-to-make-rdp-connection-not-using-http-proxy-in-krdc-freerdp/32315?u=piotr_dobrogost

**Comment by akallabeth** [comment]
@piotr-dobrogost which version? this was solved ages ago.

**Comment by piotr-dobrogost** [comment]
```
$ dnf list --installed 'freerdp2*'
Installed packages
freerdp2-libs.x86_64 2.11.7-5.fc41 <unknown>
```

**Comment by akallabeth** [comment]
@piotr-dobrogost ok, so old freerdp 2.x.
and your `NO_PROXY` variable value?

**Comment by akallabeth** [comment]
ok, just checked:
1. `export HTTPS_PROXY=https://foo.bar:8080/gaga`
2. `export NO_PROXY=*` or  `export NO_PROXY=somehost,otherhost,rdphost`
3. connect `xfreerdp /v:rdphost`

getting in both cases with both, freerdp 2.x and 3.x
```
[proxy_parse_uri]: Parsed proxy configuration: http://foo.bar:8080
[proxy_read_environment]: deactivating proxy: build03 [NO_PROXY=*]
```

**Comment by piotr-dobrogost** [comment]
Actually I have both `freerdp 3` and `freerdp 2 libs` installed:
```
$ dnf list --installed '*freerdp*'
Installed packages
freerdp.x86_64       2:3.12.0-1.fc41 updates
freerdp-libs.x86_64  2:3.12.0-1.fc41 updates
freerdp2-libs.x86_64 2.11.7-5.fc41   <unknown>```
```

and I thought `wlfreerdp` uses `freerdp 2 libs` but apparently not:

```
$ echo $(which wlfreerdp) && $_ --version
/usr/bin/wlfreerdp
(…)
This is FreeRDP version 3.12.0 (n/a)```
```

```
$ dnf provides '/usr/bin/wlfreerdp'
Updating and loading repositories:
Repositories loaded.
freerdp-2:3.12.0-1.fc41.x86_64 : Free implementation of the Remote Desktop Protocol (RDP)
Repo         : @System
Matched From :
Filename     : /usr/bin/wlfreerdp

freerdp-2:3.12.0-1.fc41.x86_64 : Free implementation of the Remote Desktop Protocol (RDP)
Repo         : updates
Matched From :
Filename     : /usr/bin/wlfreerdp

freerdp-2:3.8.0-1.fc41.x86_64 : Free implementation of the Remote Desktop Protocol (RDP)
Repo         : fedora
Matched From :
Filename     : /usr/bin/wlfreerdp```
```

```
$ dnf repoquery --requires freerdp
Updating and loading repositories:
Repositories loaded.
freerdp-libs(x86-64) = 2:3.12.0-1.fc41
freerdp-libs(x86-64) = 2:3.8.0-1.fc41
(…)
```

```
$ env | grep -i proxy
HTTP_PROXY=http://proxy.company.local:8080
http_proxy=http://proxy.company.local:8080
HTTPS_PROXY=http://proxy.company.local:8080
https_proxy=http://proxy.company.local:8080
NO_PROXY=localhost, 127.0.0.1, 0.0.0.0, 10.92, 10.93, 192.168, company.local
no_proxy=localhost, 127.0.0.1, 0.0.0.0, 10.92, 10.93, 192.168, company.local
$ wlfreerdp /v:demon.company.local
(…deprecation info…)
[21:34:43:161] [2771862:002a4b96] [INFO][com.freerdp.core.proxy] - [proxy_parse_uri]: Parsed proxy configuration: http://proxy.company.local:8080
[21:34:43:173] [2771862:002a4b96] [ERROR][com.freerdp.core.proxy] - [http_proxy_connect]: Failed reading reply from HTTP proxy (BIO_read returned zero)
[21:34:43:173] [2771862:002a4b96] [ERROR][com.freerdp.core.nego] - [nego_connect]: Failed to connect
[21:34:43:173] [2771862:002a4b96] [ERROR][com.freerdp.core] - [rdp_client_connect]: ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[21:34:43:173] [2771862:002a4b96] [ERROR][com.freerdp.core.connection] - [rdp_client_connect]: Error: protocol security negotiation or connection failure
[21:34:43:175] [2771862:002a4b96] [ERROR][com.freerdp.client.wayland] - [wlfreerdp_run]: Failed to connect(…)
```

**Comment by akallabeth** [comment]
ok, there it is.
`NO_PROXY` is a *comma*  separated list. not a *comma space* separated one.

**Comment by piotr-dobrogost** [comment]
> NO_PROXY is a comma separated list. not a comma space separated one.
> you can use * as wildcard, but currently not *.company.local
> the host must match, you don't have a match in your NO_PROXY list

Could you please provide any reference for such a strict interpretation?

For comparison the same `NO_PROXY` works with curl:
```
$ curl -v host.company.local
* Uses proxy env variable no_proxy == 'localhost, 127.0.0.1, 0.0.0.0, 10.92, 10.93, 192.168, company.local'
* Host host.company.local:80 was resolved.
(…)

$ curl -v google.com             
* Uses proxy env variable no_proxy == 'localhost, 127.0.0.1, 0.0.0.0, 10.92, 10.93, 192.168, company.local'
* Uses proxy env variable http_proxy == 'http://proxy.company.local:8080'
* Host proxy.company.local:8080 was resolved.
(…)
```
Related https://github.com/curl/curl/issues/1208 and [We need to talk: Can we standardize NO_PROXY?](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/)

**Comment by akallabeth** [comment]
@piotr-dobrogost because it was implemented like that (and as you referenced yourself there is no standard for this)
