### ISSUE TITLE
static const literals used to initialize non-const, dynamically allocated fields.

### ISSUE THREAD

**Issue by informatimago** [FreeRDP/FreeRDP#4702]
There's a problem with the structure literals declared in
winpr/libwinpr/sspi/NTLM/ntlm.c: they have non-const fields that are
initialized with static const literals, and furthermore, there is a
deallocating function that calls free on those fields.  So instead of
initializing them with static literals, we should need a function to
initialize them dynamically, to be called early in the program
initialization.

**Comment by akallabeth** [comment]
This should be fixed with your changes in #4711 correct?
