### ISSUE TITLE
\multimon work but inverted display order

### ISSUE THREAD

**Issue by licarigianluca** [FreeRDP/FreeRDP#4704]
Hi,

there is a way to change monitor order when we are connecting with the \multimon option?
I connect from Debian to Win 10 and the monitor order is inverted: windows first display is shown onlinux second display and windows second display is shown on linux first display.

Thank You,
G.

**Comment by yoyz** [comment]
This will swap your window if you have both and use /multimon

$ xfreerdp /monitor-list
      * [0] 1920x1080	+1920+0
        [1] 1920x1080	+0+0

$ xfreerdp /multimon:force /u:YYYYY /p:XXXXX /audio-mode:1   /monitors:1,0 /v:192.168.1.Z
