### ISSUE TITLE
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"

### ISSUE THREAD

**Issue by sherwinkh** [FreeRDP/FreeRDP#4708]
I encounter this issue，and FreeRdp disconnected，log as below：
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0.0"
      after 92945 requests (92945 known processed) with 0 events remaining.

- [rdp version： ] 
commit dad6b7a5347a3d42228a82b92a2f49b76c387095
Merge: 73588bc 2d69e36
Author: David Fort <rdp.effort@gmail.com>
Date:   Mon Jun 4 11:29:01 2018 +0200

    Merge pull request #4694 from akallabeth/mic_crash_fix
    
    Fixed #4693: Fix integer underflow in encoder loop.
This is FreeRDP version 2.0.0-dev3 (dad6b7a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NEON=ON WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=OFF WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -mfloat-abi=hard  -march=armv7-a -mfpu=neon -mthumb -Wl,--hash-style=sysv  -g -funwind-tables -rdynamic -I/home/r1/r1_rfx/rdp/include -L/home/r1/r1_rfx/rdp/lib -lxcb -lavcodec -lavutil -lasound -lXau -lXrender -lXfixes -lXv -L/home/r1/r1_rfx/lib-msc/libsndfile/lib -lsndfile -L/home/r1/r1_rfx/lib-msc/jsonc12/lib -ljson-c -L/home/r1/r1_rfx/lib-msc/pulse6/lib/pulseaudio -lpulsecommon-6.0   -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU, 
Target architecture: ARM

- [device： ] 
Linux X5 3.0.36+ #407 SMP PREEMPT Sun Feb 25 10:00:41 CST 2018 armv7l armv7l armv7l GNU/Linux

- [ server：] 
win server 2008 R2 Standard Sp1

someone can help me？

**Comment by akallabeth** [comment]
hmm, is your system up to date? only references to this I can find is some x library issues

**Comment by sherwinkh** [comment]
I have tried this：
git reset --hard commiID（the commitID is 2017/6,2016/6,2015/6）
in the 3 tests, also encounter the same error。

**Comment by sherwinkh** [comment]
@akallabeth ，BTW，can I know the Remote server version info（xp or win7 or server 2008 and so on）in FreeRDP？Maybe in Capabilities Exchange？

**Comment by akallabeth** [comment]
@sherwinkh so, what do you mean with the previous comment? The error suggests some issue with your X11.
as for remote server versions, sorry, there is no (reliable) way to get that info. not part of the protocol.

**Comment by sherwinkh** [comment]
@akallabeth  Thank you for the reply. Could you give me some suggestion for this X11 issue？

**Comment by akallabeth** [comment]
@sherwinkh found https://stackoverflow.com/questions/5560173/xlib-fatal-io-error-11-resource-temporarily-unavailable
so, to debug this it would be nice if you could add some information what you were doing (and what you expect as a result)

**Comment by sherwinkh** [comment]
@akallabeth instead of starting Xorg，I startup Xfbdev,then start xfreerdp, solve this problem.

- [my cmd of starting Xfbdev] 
Xfbdev  vt01 -br -mouse /dev/input/mice,5 -fp /work/cc/X11R6/lib/X11/fonts/misc/ -co /work/cc/X11R6/lib/X11/rgb &
