### ISSUE TITLE
Passwords are visible for sometime when using ps with grep

### ISSUE THREAD

**Issue by varunatarcon** [FreeRDP/FreeRDP#4712]
**Describe the bug**

Passwords are visible during sometime at startup. One can run the below script and get the password.
We need a better masking for this.

**To Reproduce**

```
tell application "Terminal"
	activate
	set shell to do script "echo freerdp" in window 1
	repeat 100 times
		do script "ps aux | grep freerdp" in shell
	end repeat
end tell
```
**Here is the output:** 

> Last login: Wed Jun 20 10:47:39 on ttys003
> imac:~ testdevelopment$ echo freerdp
> freerdp
> ps aux | grep freerdp
> imac:~ testdevelopment$ ps aux | grep freerdp
> ps aux | grep freerdp
> ps aux | grep freerdp
> .
> .
> cropped text
> .
> .
> .
> .
> ps aux | greps aux | gtestdevelopment  2112   0.0  0.0  4267752    808 s004  S+   10:47AM   0:00.00 grep freerdp
> imac:~ testdevelopment$ ps aux | grep freerdp
> testdevelopment  2114   0.0  0.0  4267752    808 s004  S+   10:47AM   0:00.00 grep freerdp
> imac:~ testdevelopment$ ps aux | grep freerdp
> ps aux | grep freerdp
> ps aux | grep freerdp
> .
> .
> .
> cropped output
> .
> .
> .
> ps aux | grep freerdp
> ps aux | grep freerdp
> ps aux | greps aux | grep freerdp
> ps aux | gtestdevelopment  2116   0.0  0.0  4267752    808 s004  S+   10:47AM   0:00.00 grep freerdp
> imac:~ testdevelopment$ ps aux | grep freerdp
> ps aux | grep freerdp
> ps aux | grep freerdp
> ps aux | grep freerdp
> .
> .
> .
> cropped output
> .
> .
> .
> ps aux | grep freerdp
> ps aux | greps aux | gtestdevelopment  2117   1.4  0.0  4265952    392   ??  S    10:47AM   0:00.00 /usr/local/bin/xfreerdp -u nj -p admin2009 -d 192.168.2.5 -v 127.0.0.1:5997 -t test WindowsRDP: 192.168.2.5@nj -smart-sizing -size 1600x900 -cert-ignore -clipboard -drives -home-drive -fonts -aero -offscreen-cache -bpp 24
> testdevelopment  2119   0.0  0.0  4267752    808 s004  S+   10:47AM   0:00.00 grep freerdp
> imac:~ testdevelopment$ ps aux | grep freerdp
> ps aux | grep freerdp
> ps aux | grep freerdp
> .
> .
> .
> cropped output
> .
> .
> .
> ps aux | grep freerdp
> ps aux | greps aux | gtestdevelopment  2117   1.4  0.1  4285476   4552   ??  R    10:47AM   0:00.01 /usr/local/bin/xfreerdp -u nj -p ********* -d 192.168.2.5 -v 127.0.0.1:5997 -t test WindowsRDP: 192.168.2.5@nj -smart-sizing -size 1600x900 -cert-ignore -clipboard -drives -home-drive -fonts -aero -offscreen-cache -bpp 24
> testdevelopment  2121   0.0  0.0  4267752    808 s004  S+   10:47AM   0:00.00 grep freerdp
> 
You can see password is exposed in line number 44.

**Expected behavior**

Password must masked from stage 1.

**Application details**
* Version of FreeRDP:  2.0.0-dev3 
* Command line used: xfreerdp -u nj -p admin2009 -d 192.168.2.5 -v 127.0.0.1:5997 -t test WindowsRDP: 192.168.2.5@nj -smart-sizing -size 1600x900 -cert-ignore -clipboard -drives -home-drive -fonts -aero -offscreen-cache -bpp 24
* output of `/buildconfig`
> This is FreeRDP version 2.0.0-dev3 (n/a)
> Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_FLAG_SEARCH_PATHS_FIRST=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB= HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H= HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H= HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS= WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=ON WITH_MACAUDIO_AVAILABLE=1 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=OFF WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
> Build type:          Release
> CFLAGS:               -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations
> Compiler:            Clang, 9.1.0.9020039
> Target architecture: x64
> 

* OS version connecting to: N/A

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]:  Mac OS X
 - Version [e.g. 22]: 10.13.5 Build 17F77

_Thank you for reporting a bug!_

**Comment by akallabeth** [comment]
use `/from-stdin` if you don't want that, otherwise there is no way to prevent this.

**Comment by varunatarcon** [comment]
But we don't have passwords! It comes from the another application. And we want to keep it secure?

**Comment by akallabeth** [comment]
then pass it via `stdin` instead of command line argument.
Like `echo foo | xfreerdp /v:<url> /u:<user> /from-stdin:force`, then the password is read from stdin (the `echo foo` in this case)
