### ISSUE TITLE
Getting segfault when enabling home drive and printer simultanously

### ISSUE THREAD

**Issue by ehoffman2** [FreeRDP/FreeRDP#4714]
Mixing _+home-drive_ along with _/printer_ cause segfault.

`xfreerdp /u:<user...> /p:<password...> /v:<ip...> +home-drive /printer`

xfreerdp v1.1.0-beta1 (in kubuntu 18.04)
Connecting to Windows 7.

Having any 2 of those options separately does work as intended.  Mixing them cause segfault.

Regards,
Eric

**Comment by akallabeth** [comment]
The version in ubuntu is rather outdated, I'd suggest using our nightly builds https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds or the remmina ppa snap or flatpak (they also ship a more recent version of `xfreerdp`).
