### ISSUE TITLE
MacOS window scrolling support by making resolution static.

### ISSUE THREAD

**Issue by nishkarshjain** [FreeRDP/FreeRDP#4718]
**Is your feature request related to a problem? Please describe.**
- When using smart-sizing, the changing resolution on macOS is really bad.
- The text on smaller window is not visible at all, to continue working.
- Microsoft Remote Desktop app provides scrollbar when window size is changed.

**Describe the solution you'd like**
- Horizontal and vertical scrollbar can be enable along with 'smart-sizing' and 'size' parameters.
- Example: If the default size is set to "1600x900", during window re-size using smart-sizing, the resolution should not change and only the window size should change, by enabling vertical and horizontal scrollbar.

**Describe alternatives you've considered**
- Currently, there is no alternative other than scrollbars.

**Additional context**
- Screenshots about the feature request is attached along, comparing Freerdp and MS Remote Desktop apps.
![screen shot 2018-06-29 at 10 35 34 am](https://user-images.githubusercontent.com/9007278/42074225-a35983a0-7b88-11e8-8954-d1faa77d707a.png)
.

**Comment by akallabeth** [comment]
So, what exactly is your issue? `/smart-sizing` does what it tells, if you want a static resolution just don't...
(you're using `xfreerdp` I assume from the screenshots?)

**Comment by nishkarshjain** [comment]
I'm looking to change window size along with static resolution. If I don't use smart sizing, I can't resize window.

MS RDP does that.

**Comment by akallabeth** [comment]
Ok, now I get it. Did you try `/dynamic-resolution`? Not exactly what you're looking for but maybe better than smart sizing in your case.

**Comment by nishkarshjain** [comment]
Also, I doubt that dynamic-resolution on macos does anything at all. Not able to understand it's use.
The resolution of the destination server also, cannot be changed.
![screen shot 2018-06-29 at 2 09 07 pm](https://user-images.githubusercontent.com/9007278/42082617-17cc6f32-7ba6-11e8-9aca-bac5d90da96f.png)

**Comment by akallabeth** [comment]
ah, ok. windows 7 does not support resolution switch in rdp, so no for you it will not help.
