### ISSUE TITLE
Error when trying to build APK in Android Client

### ISSUE THREAD

**Issue by khaleids** [FreeRDP/FreeRDP#4720]
Hello,

When I trying to build APK for Android client, I got these two errors, please I want the recommended environment tools to work with FreeRDP Android development
I have 
Ubuntu OS with 16.04 LTS
Java 
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
NDK
android-ndk-r15c
CMake 3.5.2

  | Correctness
-- | --
1 | warning UnusedAttribute: Attribute unused on older versions
  | Security
1 | warning ExportedContentProvider: Content provider does not require permission
2 | warning AllowBackup: AllowBackup/FullBackupContent Problems
  | Performance
2 | warning UnusedResources: Unused resources
  | Usability:Icons
1 | warning IconLocation: Image defined in density-independent drawable folder
1 | warning IconMissingDensityFolder: Missing density folder
  | Usability
2 | error AppLinkUrlError: URL not supported by app for Firebase App Indexing
  | Disabled Checks (23)

![image](https://user-images.githubusercontent.com/23697904/42094930-79756382-7bb1-11e8-9af0-2fd41fc97430.png)

**Comment by akallabeth** [comment]
@khaleids The android java side code is quite old and would benefit from a refactoring to current android API.
As for the environment, that seems reasonable.

**Comment by akallabeth** [comment]
Since we're currently not building for play store the firebase errors are not an issue.
