### ISSUE TITLE
new build warnings from gcc8 (mostly -Wstringop-truncation)

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#4721]
When building the current master (version 2.0.0-dev3 (b34e3bcf7)
) for openSUSE Tumbleweed, which uses gcc in version 8 as the default compiler, I get a couple of new warnings. For details see the attached build log.

[   41s] [ 17%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/utils/trio/trionan.c.o
[   41s] In function 'trio_copy_max',
[   41s]     inlined from 'internal_duplicate_max' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:201:7,
[   41s]     inlined from 'trio_duplicate' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:576:10:
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:554:9: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
[   41s]    (void)strncpy(target, source, max - 1);
[   41s]          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c: In function 'trio_duplicate':
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:369:10: note: length computed here
[   41s]    return strlen(string);
[   41s]           ^~~~~~~~~~~~~~
[   41s] In function 'trio_copy_max',
[   41s]     inlined from 'internal_duplicate_max' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:201:7,
[   41s]     inlined from 'trio_duplicate_max' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:608:10:
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:554:9: warning: 'strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
[   41s]    (void)strncpy(target, source, max - 1);
[   41s]          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c: In function 'trio_duplicate_max':
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:369:10: note: length computed here
[   41s]    return strlen(string);
[   41s]           ^~~~~~~~~~~~~~
[   41s] In function 'trio_copy_max',
[   41s]     inlined from 'internal_duplicate_max' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:201:7,
[   41s]     inlined from 'trio_xstring_set' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:576:10:
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:554:9: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
[   41s]    (void)strncpy(target, source, max - 1);
[   41s]          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c: In function 'trio_xstring_set':
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:369:10: note: length computed here
[   41s]    return strlen(string);
[   41s]           ^~~~~~~~~~~~~~
[   41s] [ 17%] Building C object winpr/libwinpr/CMakeFiles/winpr.dir/utils/wlog/wlog.c.o
[   41s] In function 'trio_copy_max',
[   41s]     inlined from 'internal_duplicate_max' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:201:7,
[   41s]     inlined from 'trio_xstring_duplicate' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:1989:23:
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:554:9: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
[   41s]    (void)strncpy(target, source, max - 1);
[   41s]          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c: In function 'trio_xstring_duplicate':
[   41s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/trio/triostr.c:369:10: note: length computed here
[   41s]    return strlen(string);
[   41s]           ^~~~~~~~~~~~~~
....
[   51s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/common/addin.c: In function 'freerdp_load_dynamic_addin':
[   51s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/common/addin.c:191:3: warning: passing argument 1 to restrict-qualified parameter aliases with argument 4 [-Wrestrict]
[   51s]    sprintf_s(pszRelativeFilePath, relPathLen, "%s", pszRelativeFilePath);
[   51s]    ^~~~~~~~~
....
[   60s] [ 53%] Building C object libfreerdp/CMakeFiles/freerdp.dir/core/proxy.c.o
[   60s] In function 'freerdp_uds_connect',
[   60s]     inlined from 'freerdp_tcp_connect' at /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/core/tcp.c:1115:12:
[   60s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/core/tcp.c:749:2: warning: 'strncpy' specified bound 108 equals destination size [-Wstringop-truncation]
[   60s]   strncpy(addr.sun_path, path, sizeof(addr.sun_path));
[   60s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
....
   61s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/core/listener.c: In function 'freerdp_listener_open_local':
[   61s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/core/listener.c:183:2: warning: 'strncpy' specified bound 108 equals destination size [-Wstringop-truncation]
[   61s]   strncpy(addr.sun_path, path, sizeof(addr.sun_path));
[   61s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
....
[   75s] [ 81%] Building C object channels/rdpei/client/CMakeFiles/rdpei-client.dir/rdpei_main.c.o
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c: In function 'rdpdr_server_drive_rename_file':
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c:2570:2: warning: 'strncpy' specified bound 256 equals destination size [-Wstringop-truncation]
[   75s]   strncpy(irp->PathName, oldPath, sizeof(irp->PathName));
[   75s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c:2571:2: warning: 'strncpy' specified bound 256 equals destination size [-Wstringop-truncation]
[   75s]   strncpy(irp->ExtraBuffer, newPath, sizeof(irp->ExtraBuffer));
[   75s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c: In function 'rdpdr_server_drive_delete_file':
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c:2420:2: warning: 'strncpy' specified bound 256 equals destination size [-Wstringop-truncation]
[   75s]   strncpy(irp->PathName, path, sizeof(irp->PathName));
[   75s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c: In function 'rdpdr_server_drive_open_file':
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c:2093:2: warning: 'strncpy' specified bound 256 equals destination size [-Wstringop-truncation]
[   75s]   strncpy(irp->PathName, path, sizeof(irp->PathName));
[   75s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c: In function 'rdpdr_server_drive_query_directory':
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c:2019:2: warning: 'strncpy' specified bound 256 equals destination size [-Wstringop-truncation]
[   75s]   strncpy(irp->PathName, path, sizeof(irp->PathName));
[   75s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c: In function 'rdpdr_server_drive_delete_directory':
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c:1851:2: warning: 'strncpy' specified bound 256 equals destination size [-Wstringop-truncation]
[   75s]   strncpy(irp->PathName, path, sizeof(irp->PathName));
[   75s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c: In function 'rdpdr_server_drive_create_directory':
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpdr/server/rdpdr_main.c:1740:2: warning: 'strncpy' specified bound 256 equals destination size [-Wstringop-truncation]
[   75s]   strncpy(irp->PathName, path, sizeof(irp->PathName));
[   75s]   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
....
   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/common/cmdline.c: In function 'freerdp_command_line_parse_comma_separated_values_ex':
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/common/cmdline.c:596:5: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
[   81s]      strncpy(dst, name, len);
[   81s]      ^~~~~~~~~~~~~~~~~~~~~~~
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/common/cmdline.c:588:17: note: length computed here
[   81s]     size_t len = strlen(name);
[   81s]                  ^~~~~~~~~~~~
....
[   84s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/X11/xf_keyboard.c: In function 'xf_keyboard_execute_action_script':
[   84s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/X11/xf_keyboard.c:408:46: warning: '%s' directive output may be truncated writing up to 1023 bytes into a region of size 1019 [-Wformat-truncation=]
[   84s]   sprintf_s(command, sizeof(command), "%s key %s",
[   84s]                                               ^~
[   84s]             xfc->context.settings->ActionScript, combination);
[   84s]                                                  ~~~~~~~~~~~
[   84s] In file included from /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/include/winpr/crt.h:30,
[   84s]                  from /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/X11/xf_keyboard.c:28:
[   84s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/include/winpr/string.h:174:20: note: 'snprintf' output 6 or more bytes (assuming 1029) into a destination of size 1024
[   84s]  #define  sprintf_s snprintf
[   84s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/client/X11/xf_keyboard.c:408:2: note: in expansion of macro 'sprintf_s'
[   84s]   sprintf_s(command, sizeof(command), "%s key %s",
[   84s]   ^~~~~~~~~
....
[osTWbuild.log.20180629.zip](https://github.com/FreeRDP/FreeRDP/files/2150314/osTWbuild.log.20180629.zip)

**Comment by hendwolt** [comment]
update:
Most of the warnings are gone, except the ones in:
winpr/libwinpr/utils/trio/triostr.c

**Comment by akallabeth** [comment]
ok, closing as the warnings in `triostr.c` are not really fixable.
