### ISSUE TITLE
connection timeout value

### ISSUE THREAD

**Issue by armin884** [FreeRDP/FreeRDP#4723]
**Is your feature request related to a problem? Please describe.**
When the remote host is offline or when rdp port is not open or any other network error freerdp stops connecting due to timeout. I am using freerdp under windows and time was about 15s the connection was closed.

**Describe the solution you'd like**
An option to increase the time before closing the connection. Remote Desktop Plus client from donkz.nl has an command line option /t[:seconds]	Try to connect to the computer indefinitely or for the specified amount of seconds until a connection is established.

**Comment by trentasis** [comment]
Try reconnect option

**Comment by akallabeth** [comment]
Agree with @trentasis to use autoreconnect instead. Increasing the tcp timeout has unwanted side effects (long hangs if the connection drops, ...)
