### ISSUE TITLE
please show version in windows file properties 

### ISSUE THREAD

**Issue by jol64** [FreeRDP/FreeRDP#4730]
when I select an application in windows explorer and display the properties and go to the details tab, then for many application it will show the product and file versions and sometimes additional information.
Unfortunatelty that information is missing for wfreerdp.exe. One only gets type "application", size and (download) date.
Can you please add information about the specific version (like it outputs with --version), ideally also whether it is a 32bit or 64bit version?
This can simplify automated updates a lot. It can also simplify support, as novice windows users will probably have difficulties to get at the version number via the console.
Thanks, Joachim

**Comment by akallabeth** [comment]
Pull requests are welcome.

**Comment by jol64** [comment]
I tried to build wfreerdp.exe with visual studio but bet a different build result than I obtained from https://ci.freerdp.com/job/freerdp-nightly-windows/. Local build result in wfreerdp.exe plus lots of .dlls (and at least that wfreerdp.exe has a version), and optionally an installer, whereas from https://ci.freerdp.com/job/freerdp-nightly-windows/ I get a wfreerdp.exe that runs directly (obviously includes all the dlls). 
How can I build the same "package" as https://ci.freerdp.com/job/freerdp-nightly-windows?

**Comment by akallabeth** [comment]
`-T v120_xp -DCMAKE_WINDOWS_VERSION=WINXP -DBUILD_SHARED_LIBS=OFF -DMSVC_RUNTIME=static -DWITH_SSE2=ON` are the options we use for the build.

To add version information there is already `macro(add_channel_client_library _module_prefix _module_name _channel_name _dynamic _entry)` which adds a corresponding resource file for channel libraries.

**Comment by jol64** [comment]
I am using Visual Studio 2015 (and 2017). On 2015 I get the error message 

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: The build tools for v120_xp (Platform Toolset = 'v120_xp') cannot be found. To build using the v120_xp build tools, please install v120_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\Joachim\Git\FreeRDP\CMakeFiles\3.11.0-rc4\VCTargetsPath.vcxproj]

Googling tells me I would need to install 2013, but that is no longer available for download. Upgrading the project to 2015 is likely something you won´t like. Looks like I am stuck.

**Comment by akallabeth** [comment]
@jol64 that part is only for backward compatibility with older windows versions, just skip these options
