### ISSUE TITLE
iOS 11 and lower iOS versions issue

### ISSUE THREAD

**Issue by ysnnzlcn** [FreeRDP/FreeRDP#4732]
Hey everyone, when i create project for ios 11 i get these errors: 
` no such sysroot directory: 
invalid iOS deployment version -mios-simulator-version-min=11.3, iOS 10 is the maximum deployment target for 32-bit targets [-Winvalid-ios-deployment-target]
`
from cliprdr-client, encomsp-client, drdynvc-client libraries.

Also i don't want to build for iOS 11 but when i try to set `SDK_VERSION="9.3"` like this, it wont create openssl library because of this error:
`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk`

Xcode only creates simulator sdk for latest version and i couldn't find a way to change it to lower version.

Did anyone encountered with this issue before?

**Comment by akallabeth** [comment]
This is an issue tracker no support forum.
Please use the mailing list or IRC.
