### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by oliverav2cloud** [FreeRDP/FreeRDP#4737]
I use Ubuntu 18.04. I installed libgstreamer-plugins-base1.0-dev | libgstreamer-plugins-base0.10-dev
manually. I still get this error when trying to compile:

pkg-buildpackage: info: source package freerdp-nightly
dpkg-buildpackage: info: source version 2.0.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by FreeRDP <team@freerdp.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build FreeRDP
dpkg-checkbuilddeps: error: Unmet build dependencies: libgstreamer-plugins-base1.0-dev | libgstreamer-plugins-base0.10-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
as a hint, read what `dpkg` is telling you
