### ISSUE TITLE
FreeRDP / Remmina keeps disconnecting /crashing after update. 

### ISSUE THREAD

**Issue by mvankammen** [FreeRDP/FreeRDP#4751]
Hi,

Multiple of our users are randomly getting disconnected from their remote desktop sessions after the latest update:

libwinpr2-2:amd64 (2.0.0~git20170725.1.1648deb+dfsg1-7~bpo9+1, 2.0.0~git20180411.1.7a7b1802+dfsg1-2~bpo9+1), libfreerdp2-2:amd64 (2.0.0~git20170725.1.1648deb+dfsg1-7~bpo9+1, 2.0.0~git20180411.1.7a7b1802+dfsg1-2~bpo9+1), libfreerdp-client2-2:amd64 (2.0.0~git20170725.1.1648deb+dfsg1-7~bpo9+1, 2.0.0~git20180411.1.7a7b1802+dfsg1-2~bpo9+1)

The message that we could find in the logging:

StatusNotifier/Appindicator support: not supported by desktop. libappindicator will try to fallback to GtkStatusIcon/xembed Running under Gnome Shell version 3.22.3 Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged. [07:43:43:787] [24627:24630] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr [07:43:43:787] [24627:24630] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd [07:43:43:787] [24627:24630] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr [07:43:43:787] [24627:24630] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc [07:43:48:916] [24627:24630] [INFO][com.freerdp.gdi] - Local framebuffer format PIXEL_FORMAT_BGRA32 [07:43:48:916] [24627:24630] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16 [07:43:48:917] [24627:24630] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx [07:43:48:917] [24627:24630] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp [07:43:48:918] [24627:24640] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd

(remmina:24627): Gtk-WARNING **: Allocating size to remmina-cw-viewport 0x557aab296420 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

Assertion 'pa_atomic_load(&(o)->_ref) >= 1' failed at pulse/stream.c:1804, function stream_get_timing_info_callback(). Aborting. Aborted

When searching for the pa_atomic_load it seems to relate to something with sound.. When the remote desktop software is trying to send a sound back to the client it seems to crash. When disabling the sound in the Remmina client it seems to stay stable. 

This seems to be related to issue https://github.com/FreeRDP/FreeRDP/issues/4750 .

**Comment by akallabeth** [comment]
@mvankammen Can you reproduce with `xfreerdp` and/or set log level to trace?

**Comment by mvankammen** [comment]
We weren't able to reproduce it in xfreerdp, it seems to happen only in Remmina with the sound enabled.

**Comment by akallabeth** [comment]
I'm working on some sound/microphone related fixes but none of them are crashing bugs (just invalid/erroneous packets sent leading to no sound/sound distortions with microphone mostly)
The issue seems to be something with `pulse` audio backend. 
You could test the following:
* Use another backend (alsa, oss, ...)
* Check if the local pulse installation is working correctly

**Comment by wharthog69** [comment]
i had a similar problem.  Changing sound from "Local - {High|Medium|Low} Quality" to "Local" only seems to have fixed the problem.

**Comment by akallabeth** [comment]
Sound and microphone have been heavily refactored.
There is #4791 but no crashes regardless of backend.
Create a new issue if this can be reproduced with additional information.

**Comment by lingfish** [comment]
Hi, what was this fixed in, version-wise?
