### ISSUE TITLE
Connection Bar for xfreerdp same as windows mstsc client

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#4756]

**Comment by mmattes** [comment]
I started to work on this. See https://github.com/mmattes/FreeRDP/tree/feature/fullscreen-bar for an initial version. It already can do close, minimize or toggle full-screen and resizing and dragging it around also works. I still do have stuff to do on it to get it ready to be pulled in e.g. auto-hide or make sure that i fulfill the coding guidelines of the project. 

BTW: this is actually the first time i am coding something in C. Any feedback if i made somewhere major mistakes in regards to coding in C would be appreciated.

**Comment by akallabeth** [comment]
@mmattes Looks good overall, just 2 little hints:
* We try to stay compatible with older compilers, so no C++ comments or variable declarations mid code
* Use `./scripts/format_code.sh` (astyle) script which formats code according freerdp standards

**Comment by gnshkl1** [comment]
@mmattes Good work can you make it configurable from freerdp commandline

**Comment by gnshkl1** [comment]
@mmattes active by default and command line switch to disable it will be good option

**Comment by mmattes** [comment]
@gnshkl1 have a look at https://github.com/mmattes/FreeRDP/commit/37d84751b331cac1e53f3bac66f2a0b382f1131c where i added a new option to disable the floatbar. But i got some queries. 
- settings.h seems to be, at least partially, auto generated. I couldn't figure out in detail ho,  why i am not sure if the new option i added is correct?
- cmdline.h seems to be common for all clients, i have seen that there is a floatbar in the windows client why i also implemented changes there to apply the new option, but I cant verify them. See commit https://github.com/mmattes/FreeRDP/commit/20316cacdeeacb8f9825a11244418ebdea387397

**Comment by mmattes** [comment]
Totally forgot, i have no devices to test if my floatbar implementation within the X11 client is working properly in multimonitor mode and not shown at all when it is a RemoteApp. Can anyone verify that?

**Comment by drnuriev** [comment]
Hi. How to disappear connection bar on Thinstation (xfreerdp)? Is there some parametr? Thanks.
