### ISSUE TITLE
FreeRDP 2.0.0-dev3 The mouse pointer is doesn't appearing on windows server 2012

### ISSUE THREAD

**Issue by piter1993vc** [FreeRDP/FreeRDP#4767]
Mouse cursor disappears with Windows 2012r2 Server OS.

Steps:
# Create a Windows 2012r2 Server VM 
# Install tools on VM.
# Enable Remote Desktop Connection.
# Launch RDP session.
# Observer if mouse cursor appears or not?

Observation:
Mouse cursor disappears with Windows 2012r2 Server OS.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Please try a bit harder with describing what is going on.
