### ISSUE TITLE
Shift and Ctrl key have incorrect behaviour in some cases for MacOSX

### ISSUE THREAD

**Issue by Mandar-Shinde** [FreeRDP/FreeRDP#4769]
**Bugs**
1. Special character gets printed only after pressing shift key **twice** in remote windows machine.
2. "Ctrl+ C" do not copy text on remote windows machine.

**Expected behaviour**
1. Special character should print on pressing shift key once in remote. (works with mac mstsc)
2. "Ctrl+ C" key combination should copy text in remote machine. (works with mac mstsc)

**Observation**
1. If windows "osk" is running in remote machine then printing special characters works as expected.
2. KBD debug logs are not printed in mac freerdp.

**Configuration**
_Host:_ MacOSX 10.13.5
_Remote:_ Windows Server 2012 R2

**Checked with** 
FreeRDP version 2.0.0-dev3
FreeRDP version 2.0.0-RC2

**Application details**
 _./MacFreeRDP  /cert-ignore /log-level:debug      /kbd:0x00000409      /v:xxx  +async-input +async-update /buildconfig_
This is FreeRDP version 2.0.0-dev3 (n/a)\
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_FLAG_SEARCH_PATHS_FIRST=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB= HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H= HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H= HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=ON WITH_CUPS=OFF WITH_DEBUG_ALL=ON WITH_DEBUG_CAPABILITIES=ON WITH_DEBUG_CERTIFICATE=ON WITH_DEBUG_CHANNELS=ON WITH_DEBUG_CLIPRDR=ON WITH_DEBUG_DVC=ON WITH_DEBUG_KBD=ON WITH_DEBUG_LICENSE=ON WITH_DEBUG_MUTEX=ON WITH_DEBUG_NEGO=ON WITH_DEBUG_NLA=ON WITH_DEBUG_NTLM=ON WITH_DEBUG_RAIL=ON WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=ON WITH_DEBUG_RDPEI=ON WITH_DEBUG_REDIR=ON WITH_DEBUG_RFX=ON WITH_DEBUG_RINGBUFFER=ON WITH_DEBUG_SCARD=ON WITH_DEBUG_SND=ON WITH_DEBUG_SVC=ON WITH_DEBUG_SYMBOLS=ON WITH_DEBUG_THREADS=ON WITH_DEBUG_TIMEZONE=ON WITH_DEBUG_TRANSPORT=ON WITH_DEBUG_TSG=ON WITH_DEBUG_TSMF=ON WITH_DEBUG_WND=ON WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=ON WITH_MACAUDIO_AVAILABLE=1 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=ON WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_X11=OFF WITH_X264=OFF WITH_XEXT=OFF WITH_XRANDR=OFF WITH_ZLIB=OFF\
Build type:          Release\
CFLAGS:               -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations\
Compiler:            Clang, 9.1.0.9020039\
Target architecture: x64

**Comment by loicV2Cloud** [comment]
We were able to reproduce it also.
Is someone can help?

**Comment by damonwilliam** [comment]
Any update or additional info on this problem that one could use to potential help with a fix.

It seems like there is an issue with the active state of the modifier key being overridden by the following key press. One the user press and holds shift, they must wait a short period before the following key is pressed or the next key press seems to override the active state of the SHIFT key. 

It seems related to the pub-sub system handling key input events.

**Comment by qiandahao** [comment]
@akallabeth hey there! I am working on the Mac version and I found sync_keyboard_state in MRDPView.m resets the modifier key status. So when you fiirst time hit the shift or control key they won't work at all. After removing this function, the FreeRDP works good for me. But I am just wondering where I can find any api infomation so I can get a better understand about this synchronize thing. Thanks!

**Comment by qiandahao** [comment]
By they way, I didn't see other platform version is using this function(freerdp_input_send_synchronize_event).

**Comment by akallabeth** [comment]
@qiandahao has to do with mac keyboard handling, the `freerdp_input_send_synchronize_event` synchronizes local modifers with remote ones.
the way RDP keyboard redirection works is not really easy to implement on mac for all corner cases.
pull requests with improving the behaviour are welcome but I can tell it takes quite some testing to get all the pitfalls right :/
