### ISSUE TITLE
sporadic screen redraw issues when display compositing is enabled

### ISSUE THREAD

**Issue by schadsey** [FreeRDP/FreeRDP#4780]
I'm running xfreerdp from `freerdp-nightly 2.0.0+0~20180731014836.540~1.gbp88474a` on xubuntu 17.10, x86_64.  My window manager is Xfce. Occasionally when I am working in a remote desktop session, the screen will not be fully redrawn, leaving square artifacts of previous windows on the screen.  E.g. if I move a window, part of the window will still be drawn in the old location.  Sometimes launching a new window will only draw the window border, leaving the background windows visible.  Whenever this happens, I can get the screen to redraw properly in a couple of different ways:
1. drag remote windows all over the desktop to initiate a redraw
2. click on a local window
3. When in windowed mode, clicking the top of the freerdp window and dragging/jiggling the window

If I go into Settings > Window Manager Tweaks > Compositor and uncheck "Enable display compositing", the issue is not reproducible. 

This happens both in full screen mode and windowed mode.

I've reproduced it on several previous builds, but I didn't note their versions.  I updated to the latest nightly yesterday and was able to reproduce it.  

I've captured a screencast of the issue, and interestingly when I play it back, the screen redraw issue isn't visible!

Also, this is almost certainly the same issue as https://github.com/FreeRDP/FreeRDP/issues/814 which was closed due to no feedback.

** Application details
* Version of FreeRDP: This is FreeRDP version 2.0.0-dev3 (88474af92)
* Command line used: 
** Fullscreen: /opt/freerdp-nightly/bin/xfreerdp /cert-ignore /clipboard /drive:Share,/home/stevec/Share /f /sound:sys:alsa /microphone:sys:alsa /u:stevec /p:******************* /f /v:hostname
** Windowed: /opt/freerdp-nightly/bin/xfreerdp /cert-ignore /clipboard /drive:Share,/home/stevec/Share /u:Administrator /p:******* /size:80% /v:hostname
* output of `/buildconfig`
```
This is FreeRDP version 2.0.0-dev3 (88474af92)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=FALSE WITH_FFMPEG=FALSE WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp-nightly-2.0.0+0~20180731014836.540~1.gbp88474a=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer
Compiler:            GNU, 7.2.0
Target architecture: x64
```
* OS version connecting to: Windows Server 2012 R2; Windows 10 Enterprise
* log output from a run with `/log-level:trace` : see attached

**Desktop (please complete the following information):**
 - OS: Linux Xubuntu 17.10 x86_64
 - Browser: Firefox 61.0.1
[xfreerdp.log](https://github.com/FreeRDP/FreeRDP/files/2249974/xfreerdp.log)

Please let me know any other info that you require to triage this.

**Comment by akallabeth** [comment]
@schadsey Does this also happen with `/rfx /gfx:avc444` enabled?

**Comment by schadsey** [comment]
@akallabeth It seems the `/gfx:avc444` option isn't recognized - when I add those two options to my command line, I get a usage message.
If I add `/rfx`, the issue remains.

I forgot to mention other flags I've tried in the past with no luck:
`/offscreen-cache`
`/bitmap-cache`
`/gfx +gfx-progressive`

Mostly these were just stabs in the dark.

**Comment by schadsey** [comment]
If this were a local configuration issue, then one thing I thought might make a difference was the video driver.  I was using the nvidia driver, `384.130-0ubuntu0.17.10.1`.  I removed it to use the nouveau driver.
```
$ dpkg -l |egrep nouveau
ii  libdrm-nouveau2:amd64                                       2.4.83-1                                 amd64        Userspace interface to nouveau-specific kernel DRM services -- runtime
ii  libdrm-nouveau2:i386                                        2.4.83-1                                 i386         Userspace interface to nouveau-specific kernel DRM services -- runtime
ii  xserver-xorg-video-nouveau                                  1:1.0.15-2                               amd64        X.Org X server -- Nouveau display driver
```
After rebooting, I tried both xfreerdp and xtightvncviewer and although it's only been about 30 minutes, I haven't yet seen any screen drawing/redrawing/repainting issues with compositing enabled.

**Comment by akallabeth** [comment]
Ok, closing as we can't help with buggy drivers :/
Reopen if this assessment is wrong.
