### ISSUE TITLE
Authentication fails when connecting through RD Gateway

### ISSUE THREAD

**Issue by helgef** [FreeRDP/FreeRDP#4781]
I commented under issue #4337 but since that is closed I suspect that will go unnoticed.

When attempting to connect to a connection that has worked in the past using remmina, I now suddenly got a generic "Could not establish RDP connection" error message.

In order to dig a little deeper and hopefully get a better error message I decided to install freerdp from the repository and attempt to connect using xfreerdp. This also failed. I even tried adding the nightly build repo and use that, and build from source, but that also failed. The message I'm getting currently (using nightly build) is this:

[20:43:11:219] [22406:22407] [INFO][com.freerdp.core.gateway.rdg] - RD Gateway does not support HTTP transport.
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.rpc] - error! Status Code: 401
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - HTTP/1.1 401 Unauthorized
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - Content-Type: text/plain
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - Server: Microsoft-IIS/7.5
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - WWW-Authenticate: Negotiate
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - WWW-Authenticate: NTLM
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - WWW-Authenticate: Basic
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - X-Powered-By: ASP.NET
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - Date: Sun, 05 Aug 2018 18:43:11 GMT
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.http] - Content-Length: 13
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_AUTHENTICATION_FAILED [0x00020009]
[20:43:11:426] [22406:22407] [ERROR][com.freerdp.core.gateway.tsg] - tsg_check failure

Any ideas?

**Comment by helgef** [comment]
Worth mentioning that I have no issues connecting using mstsc from windows.

**Comment by akallabeth** [comment]
Commandline please? Looks like you use the wrong gateway parameters, try /gt: options

**Comment by helgef** [comment]
Thanks,

I tried several mutations of the command line, /gt did not seem to do anything.

I was however able to connect when using both the /gd and the /d parameter. I had first used them only as part of the /u and /gu parameter (DOMAIN\user). Setting them explicitly seems to work.

So now I'm able to connect through xfreerdp. That still leaves my issues with Remmina, but I assume this is the wrong place to report that

**Comment by akallabeth** [comment]
Glad to hear. Well, then closing as resolved.

**Comment by akallabeth** [comment]
@antenore does specifying /gt:<type> help? Autodetection sometimes does not work :/

**Comment by antenore** [comment]
@akallabeth I've tried with rpc and it didn't help, but I haven't tried with http yet, should I?

**Comment by antenore** [comment]
@akallabeth no, with `http` it doesn't 

If you can help yes, I'll appreciate it, also because I don't know that much where to look. The error message it's quite generic, so it's hard to understand where is the problem.

Don't hesitate to ping me for any tests and if you need access to that gateway let me know, I'll see with the owner, but it should be feasible (maybe drop me an email in that case).

Thanks!!!!

```sh
[21:28:54:622] [17510:17511] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[21:28:54:622] [17510:17511] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: tmow
[21:28:54:656] [17510:17511] [INFO][com.freerdp.client.x11] - Property 452 does not exist
[21:28:55:881] [17510:17511] [INFO][com.freerdp.core.gateway.rdg] - RD Gateway does not support HTTP transport.
[21:28:55:881] [17510:17511] [ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[21:28:55:881] [17510:17511] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[21:28:55:881] [17510:17511] [ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
```

**Comment by akallabeth** [comment]
@antenore ok, looks like you have a configuration still not working :/
Well, then... Could you post the output with log-level debug or is it possible to connect with a demo account to the system?

**Comment by akallabeth** [comment]
@antenore Just a small question, your command line only contains user, domain and password for the gateway, is the host reachable without authentication?

**Comment by antenore** [comment]
@akallabeth I'm asking to share the user with you. 

I think the host is not reachable.

We have a couple of issues opened for the same error, so I've asked a test account on an RD gateway (no need to access directhly the server).

One of them provided me an RD gateway with user and password to test, but no access to the final destination (we don't have an account) and I think it's probably behind a firewall.

**Comment by antenore** [comment]
@akallabeth I've added you to the Remmina member on GitLab and created a snippet that only us (the members) can see, with those server/user/password to test.

[RD Gateway snippet](https://gitlab.com/Remmina/Remmina/snippets/1751383) .

**Comment by akallabeth** [comment]
@antenore ok, checking. really interested in what is going wrong.

**Comment by akallabeth** [comment]
@antenore Ok, have at least the place it fails.
The outgoing tls connection can not be authenticated (the incoming seems to work fine though)

**Comment by antenore** [comment]
@akallabeth I see the certificate is multi-domain (with * in the hostname), may be an issue somehow?

**Comment by akallabeth** [comment]
No, we use openssl validation and/or pinning. It fails after the tls connection is established and the ntlm tokens are exchanged

**Comment by akallabeth** [comment]
@antenore Are you sure the setup works? Connecting with `mstsc` yields the same error (authentication failed on gateway)

**Comment by antenore** [comment]
@akallabeth it's what the dude who gave us this gw have told me. I'm going to ask.

**Comment by antenore** [comment]
He have tested with mstsc and it works. He highlighted that we don't have access to the final windows server, but only on the RDP gateway. If needed he can give us the rights for that server as well.

**Comment by akallabeth** [comment]
@antenore looks like a tough one, could not find anything wrong with the message sequence, might be some byte / lenght is off, but couldn't spot that so far :/

**Comment by antenore** [comment]
@akallabeth I see... If I can do anything let me know, and obviously no rush (as usual)

**Comment by akallabeth** [comment]
@antenore Currently working on #4843 maybe I'll accidentally fix it while refactoring :)

**Comment by antenore** [comment]
Ah! Really cool !

**Comment by akallabeth** [comment]
@antenore Just a little question, during debugging the server announces `NTLM`, `Basic` and `Negociate` authentication method support.
We currently only try `NTLM`, is this allowed by the server?

**Comment by antenore** [comment]
@akallabeth I'll ask. In the meanwhile I've tried with another GW server and I was able to connect to it with Remmina.
On our side the Gateway Transport Type was not fully implemented, and now it works as expected.

I'll come back to you with the answer to your question. Thanks!

**Comment by antenore** [comment]
Hey @akallabeth a good news, the issues seems to be solved, you can close this.

Regarding the reason why it works, we really don't have any clues...

Thanks a lot for your support!

**Comment by seanw2020** [comment]
This worked for me:
```
    xfreerdp /gt:http /sec:tls /v:server.company.com /u:me@company \
      /p:'NLMw&h5i23f' /g:gateway.company.com /cert-ignore \
       /auto-reconnect-max-retries:0 /log-level:info &>> ~/xfreerdp.log &
```
We use a Microsoft Windows Active-Directory setup with RDP Gateway over `https` (`/gt:http`), so it makes sense to use `TLS` security.

**Comment by FelixZhang** [comment]
> This worked for me:
> 
> ```
>     xfreerdp /gt:http /sec:tls /v:server.company.com /u:me@company \
>       /p:'NLMw&h5i23f' /g:gateway.company.com /cert-ignore \
>        /auto-reconnect-max-retries:0 /log-level:info &>> ~/xfreerdp.log &
> ```
> We use a Microsoft Windows Active-Directory setup with RDP Gateway over `https` (`/gt:http`), so it makes sense to use `TLS` security.
@seanw2020 Please make sure that's not your real world password getting leaked.
