### ISSUE TITLE
xfreerdp with TS brokers

### ISSUE THREAD

**Issue by leeryanrs** [FreeRDP/FreeRDP#4802]
I'm trying to deploy an RDS farm with brokers to load balance. The application can connect and get the login page, however once you enter your credentials to login and press login, the app freezes on the "Welcome" page. 

I've tested with the stable 1.1 and also with the 2.0 rc3.

I've been looking around old issues and I can see that some people have had this issue before, however no solid solution from what I can see.

It seems it cannot handle the re-direction packet somehow, since upon login it will connect to a broker and depending on session, throw you to a different IP. I did a wireshark trace and it would start out on for example 192.168.25.3 but end up on 192.168.25.4, this is where it crashes. If it were to reply with the same IP, it would work. ( Tested this theory by also disabling the other RDS members forcing the only broker/rds server to reply with same IP )

Running a thin client on Ubuntu 16.04
Windows Server 2012 R2

**Comment by akallabeth** [comment]
please use the mailing list or irc for support questions.

**Comment by leeryanrs** [comment]
I'm reporting a bug..

**Comment by akallabeth** [comment]
@leeryanrs Since you do not provide any of the details requested in the issue form and I'm using freerdp with load balancers it seems to be a support question.
