### ISSUE TITLE
Allow decoding to be disabled while connection is active.

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#4804]
**Is your feature request related to a problem? Please describe.**
Allow decoding to be turned off while the connection is active.

**Describe the solution you'd like**
Please allow decoding to be deactivated while the connection is active.

**Describe alternatives you've considered**
I'm not sure of any great alternatives. The solution as stated would would help reduce CPU load on the client while keeping the desktop active on the server side.

It might also be good to implement screen muting that the server recognizes as well. If I remember correctly, the Microsoft-provided ActiveX control for RDP stops screen network traffic and server side desktop rendering when minimized.

**Comment by akallabeth** [comment]
There is suppress output which is a server side feature allowing that. Stopping decoding client side has unwanted side effects (garbage on screen on resume, ...)

**Comment by R030t1** [comment]
Does Microsoft's default implementation of RDP prevent draw events from being dispatched to applications when the server suppresses screen output? I am fairly sure it does, and that is the thing that I am attempting to work around with this feature request.

Is there no way to resynchronize the display stream? If not it would be fine to me to disconnect but leave the session running and then reconnect. Would this course of action require input be sent to the remote session to disconnect, or is there an API call for it?
