### ISSUE TITLE
Freerdp 2.0.0-rc2 keyboard layout issue

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#4807]
Client OS :- Ubuntu 12.04_x86
Server OS – Windows 10 Enterprise – 64 bit
Goal: Keyboard layout to be set from xfreerdp on Windows VM

Steps: Add languages from Settings on Windows VM

    Turkmen
    Fillipino
 
Working - Turkmen
Commandline - xfreerdp /u:admin /p:******* /kbd:0x0464 /d:xx /v:x.x.x.x  /log-level:debug >> turkmen.log
 
Not Working – Fillipino
Commandline - xfreerdp /u:ptpladmin /p:propalms@123 /kbd:0x0464 /d:ptplqa /v:10.0.8.212 /log-level:debug >> fillipino.log

-bash-4.3# xfreerdp -buildconfig
This is FreeRDP version 2.0.0-rc2 (2.0.0-rc2)

Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LIBAVCODEC=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_OPENH264=ON WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
Compiler:            GNU,
Target architecture: x86
[turkmen.log](https://github.com/FreeRDP/FreeRDP/files/2304876/turkmen.log)
[fillipino.log](https://github.com/FreeRDP/FreeRDP/files/2304877/fillipino.log)

**Comment by akallabeth** [comment]
@gnshkl1 Ok, sorry missed the first hint.
With the `/kbd` parameter you set the desired layout (this value will be also send to the server)
Since in your example it is always `0x0464` it will always be the same (See https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values for details)

**Comment by arc-nim** [comment]
@akallabeth thanks for the update.
I have tried without /kbd parameter but did not work.
Steps are as below:
1. -bash-4.3# setxkbmap ph
2. -bash-4.3# setxkbmap -query
rules:      base
model:      pc105
layout:     ph
3. xfreerdp /u:abc /p:abc /d:abc /v:x.x.x.x /log-level:debug >> test2.log

I have checked the link, on my VM there is no key for keyboard layout for 0x0464.
Though, if I take mstsc of this VM from windows Client, my IME of VM changed to FIL ( Fillipino).

Please suggest
[test2.log](https://github.com/FreeRDP/FreeRDP/files/2305729/test2.log)

**Comment by akallabeth** [comment]
@gnshkl1 @architav Ok, you seem to mix up locale identifier (`0x464`) with keyboard layout identifier.

**Comment by akallabeth** [comment]
@architav I've no idea what the keyboard identifier for filipino is, but `0x0464` is the language identifier...
they are NOT the same!
