### ISSUE TITLE
~20 character password length limit?

### ISSUE THREAD

**Issue by kfiresmith** [FreeRDP/FreeRDP#4819]
It appears that xfreerdp 1.0.2 on RHEL 7 has a password limit that is some number of characters higher than 19 but lower than 24.  A user reported to me that his 24 character password wasn't working from Vinagre or from xfreerdp on the command line.  We found the same type of bug reported for Vinagre here:  https://bugzilla.redhat.com/show_bug.cgi?id=1569552

I was not able to determine the exact length due to not being able to easily set up a lab environment to do further testing with a password of each character length between known good (18char) and known-bad (24char).  

The remote systems tested were Windows 10 and Windows Server 2008.  Based on our observations we suspect it's overwhelmingly likely to be a freeRDP issue.

To reproduce, assuming you have a lab environment where you can change passwords repeatedly, try creating an AD account that uses a 24 character password.  You should see this message when the xfreerdp command dies:
``
connected to ts.college.edu:3389
Password:
SSL_read: Failure in SSL library (protocol error?)
$
``
Here is a sanitized version of the command line used and which works when the password length is 18 or less characters:

``
$ xfreerdp -d COLLEGENET -g 1680x1020 -u jimbob --plugin cliprdr --plugin rdpsnd --plugin drdynvc --data tsmf:audio:pulse – ts.college.edu
``

I ran a few open/closed issues searches on here and came up empty - apologies in advance if this is a known limitation with the client code that is already being worked on.

**Comment by akallabeth** [comment]
@kfiresmith Are you sure it is not a simple timeout of the ssl socket waiting for completiong (it should be something about ~20 seconds if I remember correctly

**Comment by kfiresmith** [comment]
Hello @akallabeth  - that message seems to be something of an unintentional catch-all message that appears when nearly anything goes sideways.  The exact same environment & command with a 18char password works.  The fact that this is the last message that a user sees for many different unrelated problems points to the need for better error catching and messaging in the xfreerdp client in general, but that's a problem for a different bugreport :)

There is a password length gremlin in xfreerdp that we appear to be able to tickle with a 24 character password, and that's what this bugreport is for. 

Thanks!

**Comment by akallabeth** [comment]
@kfiresmith Agree with the error handling, but that is (mostly) a protocol issue...
(the error status is not very detailed, specially with invalid user and passwords - but that is a security feature, ssh is similar in that regard)
* Is this bug `1.0.2` only or does it also affect `2.0` release candidates?
* Are you sure this is not triggered by a timeout?
* Which authentication scheme are you using server side? `ntlm`, `tls`, `nla`, ...?

**Comment by kfiresmith** [comment]
Hi @akallabeth  - thanks for the reply!
 - I'll have to see if I can find a pre-build of the 2x branch for RHEL 7
 - Everything is the same except for the actual password length so I'm going to assert no for now
 - NLA against WS2008, W10 Desktop

Thanks!

**Comment by kfiresmith** [comment]
AFAICT there are no builds for xfreerdp 2x branch for RHEL 7, and I actually don't have an easy way to test anyhow since I can't get an arbitrary AD account in my operating environment to set a 20+ char password.

**Comment by akallabeth** [comment]
@kfiresmith There is a `spec` file in the repo in `packaging/rpm` we use for our nightly builds. Don't know if that will work with RHEL 7, but the main dependencies should be compatible enough.

**Comment by kfiresmith** [comment]
@akallabeth  - unfortunately I won't be able to do further testing on this issue (I can't create the environment needed to test), I mostly wanted to raise the issue should others discover they cannot connect for the same reason.  We've already worked around the issue for the affected user.

Thanks again!

**Comment by ondrejholy** [comment]
By the way, there is an unofficial copr repository with freerdp 2 packages for RHEL which might be useful for testing:
https://copr.fedorainfracloud.org/coprs/mikedep333/freerdp-backport/
