### ISSUE TITLE
Covscan defects

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#4820]
I've fixed multiple defects reported by covscan as a part of https://github.com/FreeRDP/FreeRDP/pull/4813. However, there are still some remaining defects which I am unsure about their solution and thus I am not going to propose any fixes for them. Some of them look like false-positives, but some of them seem to be worth looking at, e.g. the one with `USE_AFTER_FREE`. Here is the list of important defects on top of the mentioned pull request: [scan-results-imp.err](https://github.com/FreeRDP/FreeRDP/files/2315544/scan-results-imp.err.txt).

**Comment by ondrejholy** [comment]
Btw there is also a list containing much more issues, which are not marked as important: [scan-results.err](https://github.com/FreeRDP/FreeRDP/files/2315551/scan-results.err.txt). There is also a lot of interesting defects, e.g. `NO_EFFECT`, `DEADCODE`. If I find some time I will propose a fix for some of those also.

**Comment by akallabeth** [comment]
@ondrejholy We've fixed a lot of warnings (and bugs) in the last weeks, so I assume we can close this one?

**Comment by ondrejholy** [comment]
The scan based on the current master (commit d3c1db1746b99c05d515de626d2c515e49debfdd) revealed more issues than the previous one. There is still the `USE_AFTER_FREE` defect, which would be nice to fix, but I am not sure how. I don't see anything else very important. See [scan-results-imp.err](https://github.com/FreeRDP/FreeRDP/files/2514439/scan-results-imp.err.txt) and [scan-results.err](https://github.com/FreeRDP/FreeRDP/files/2514438/scan-results.err.txt) for details.

**Comment by akallabeth** [comment]
@ondrejholy looks like there were some socket leaks handling error cases of `tcp_connect`.
The `USE_AFTER_FREE` is currently harmless, but @hardening is changing the return there to a seat ID to avoid the confusion (both, developer and compiler)

**Comment by ondrejholy** [comment]
Thanks that you took look at those defects. The seat id defect is not still fixed, see my comment on https://github.com/FreeRDP/FreeRDP/pull/4970. I can confirm that some socket leaks disappeared. If you are interested see updated [scan-results-imp.err](https://github.com/FreeRDP/FreeRDP/files/2553667/scan-results-imp.err.txt) and [scan-results.err](https://github.com/FreeRDP/FreeRDP/files/2553665/scan-results.err.txt).

**Comment by akallabeth** [comment]
Ok, the wayland related stuff is merged and we're currently fixing some remaining scanbuild warnings.
closing this for now.
