### ISSUE TITLE
Bypass Legal notice popup in windows server.

### ISSUE THREAD

**Issue by rajdeinno** [FreeRDP/FreeRDP#4821]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.  I am getting a legal notice every time when I log in to windows server through FreeRDP. Of course, there are some settings made in windows server. But how can I bypass this legal notice pop up through FreeRDP?

**Describe the solution you'd like**
I want to bypass this legal notice through FreeRDP.

**Describe alternatives you've considered**

**Additional context**

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
