### ISSUE TITLE
minimized window not show

### ISSUE THREAD

**Issue by szlbwhj** [FreeRDP/FreeRDP#4824]
**Describe the bug**
version: FreeRDP-2.0.0-rc3, wfreerdp for windows
remote server is windows server 2016
when I use below cmd:
 "wfreerdp.exe /d:xxx /u:xxx /p:xxx  /v:192.168.11.173 /size:1024x768 /echo /app:"||POWERPNT""
When I minimized the PPT, the minimized window disappeared. I can't restore the ppt window to the normal state, but windows server2012 does not.

**To Reproduce**
1. open remote app user cmd **wfreerdp.exe /d:xxx /u:xxx /p:xxx  /v:192.168.11.173 /size:1024x768 /echo /app:"||POWERPNT"**
2. minimize PPT window
3. Observing the desktop, the PPT's minimized window not show

**Expected behavior**
show minimized windows of PPT

**Screenshots**
![image](https://user-images.githubusercontent.com/9426515/44579703-d34b6980-a7c9-11e8-8381-723d500cfbb1.png)
![image](https://user-images.githubusercontent.com/9426515/44579713-dcd4d180-a7c9-11e8-83e4-6b764a4fff1a.png)

** Application details
* Version of FreeRDP: FreeRDP-2.0.0-rc3 ,wfreerdp for windows
* Command line used `wfreerdp.exe /d:xxx /u:xxx /p:xxx  /v:192.168.11.173 /size:1024x768 /echo /app:"||POWERPNT"`
* OS version connecting to  windows server 2016

**Comment by akallabeth** [comment]
Does it work with `/gdi:sw`?

**Comment by szlbwhj** [comment]
I did not use this option, is it the default for windows server 2016?

**Comment by szlbwhj** [comment]
@akallabeth I know, I really didn't use this option.

**Comment by akallabeth** [comment]
And what happens if you use it?

**Comment by szlbwhj** [comment]
Same as not using this option,still no minimized window

**Comment by huazq** [comment]
same question with me, and  it does not work with /gdi:sw
