### ISSUE TITLE
Screen Artefacts / glitches - Ghosted Menu looks bold with default (gdi:hw rendering)

### ISSUE THREAD

**Issue by ropetry** [FreeRDP/FreeRDP#4830]
We have a new Issue with Freerdp 2.0.0-rc2. 
There are some screen / graphic glitches i think if we use a special screen resolution. Terminal Server is 2008r2.. Server 2016 looks o.k with this resolution..
If i start my RDP Session with 1920x1200 Screen resolution everything is fine. if i change the resolution via xrandr to 1920x1080 some menu´s settings ,which should be ghosted, appears bold and so on.. will attach a screenshot..

bye
roman

**Comment by akallabeth** [comment]
@ropetry Could you please answer the questions of the issue template? Hard to reproduce with half the information missing (specially which RDP mode you're using, aka command line)

**Comment by ropetry** [comment]
![freerdp-ghost](https://user-images.githubusercontent.com/2862409/44705530-30337200-aa9f-11e8-9139-d73bfab016bb.jpg)

**Comment by akallabeth** [comment]
@ropetry Ok, that is the glitch, which RDP mode (command line) are you using?

**Comment by ropetry** [comment]
@akallabeth  .. sorry.. of course..
command-line: xfreerdp /v servername

Build-Options:
~ # cat /tmp/buildconf.txt
This is FreeRDP version 2.0.0-rc2 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIE -pie -DNDEBUG -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g
Compiler:            GNU, 7.3.1
Target architecture: x86
~ #

OS- Custom own Builded Thinclient O.S based on Suse Linux

Screenresolution with error:
~ # cat /tmp/xrandr
Screen 0: minimum 320 x 200, current 1920 x 1080, maximum 16384 x 16384
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 518mm x 324mm
   1920x1200     59.95 +
   1920x1080     60.00*   50.00
   1680x1050     59.88
   1600x900      60.00
   1280x1024     60.02
   1440x900      59.90
   1280x800      59.91
   1280x720      60.00    50.00    59.94
   1024x768      60.00
   800x600       60.32    56.25
   720x576       50.00
   720x480       60.00    59.94
   640x480       60.00    59.94
DVI-0 disconnected 1920x1080+0+0 (normal left inverted right x axis y axis) 0mm x 0mm
   1920x1080_60  60.00*
~ #

Just connect to the Server2008r2 System. Logon and press the right Mouse Button to get the contect menu on the desktop.. Normally "create link/shortcut" is ghosted and not selectable..

Will ry to attach the debug logfile.. 
Anything elsr missing ?
bye
roman

x

**Comment by akallabeth** [comment]
Thank you. Might be a known issue then, could you try:
* Does it disappear with `/gdi:sw`?
* Might be a good idea to switch to modern RDP (`/rfx` (windows 7) and `/gfx` (windows 8 and newer) or `/gfx:avc444` (windows 8 and newer, compiled with a H264 decoder))

**Comment by akallabeth** [comment]
Would suggest using `/gdi:sw` (already considering to make it default).
It is the more complete implementation (and there is little to no speed difference as most content is bitmap anyway)
`/gdi:hw` has some operations that can not be properly mapped to X11 counterparts (that is what you see)

**Comment by ropetry** [comment]
@akallabeth : o.k i will try to use this as new default setting. hopefully this setting don´t impact the performance on the "atom" driven thinclients or via c7 based machine too much.. cpu performance is "slow" compared to a i3 or so 8-)..so every cpu cycle hurts 8-)

**Comment by akallabeth** [comment]
@ropetry Didn't see much difference on a raspberry pi 2 ;)

**Comment by ropetry** [comment]
thanks.. @akallabeth if you like you can close this 8-)..

**Comment by ropetry** [comment]
thanks for help..
