### ISSUE TITLE
Add kerberos single sign-on support

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#4832]
It would be nice to support single sign-on experience over Kerberos in order to prevent the need password each time. I know that this was discussed earlier with the resolution that it is not possible, but it should be possible now over Remote Credential Guard, see:
https://social.msdn.microsoft.com/Forums/en-US/da074f0f-0887-4151-88ea-19a671ed91d9/is-it-possible-to-do-true-kerberos-sso-using-rdp-?forum=os_windowsprotocols#ab8e1d14-a541-4948-87b5-54b22af8a510

**Comment by akallabeth** [comment]
Related #4311

**Comment by informatimago** [comment]
Note: I have not found any documentation yet about the contents of the TSRemotePackageCred (package name, cred buffer). So this development is stalled until we have more information about this part of the protocol.

**Comment by ofiriluz** [comment]
Hi,

Anything new on this?

**Comment by FranckGoirand** [comment]
> nything new on this?

+ 1

**Comment by akallabeth** [comment]
Started https://github.com/FreeRDP/FreeRDP/pull/6661 to fix basic kerberos support, but I do not have enough time to do the whole testing (still need to set error codes in winpr similar to windows SSPI)

**Comment by akallabeth** [comment]
kerberos support now upstream, closing.
