### ISSUE TITLE
RC3: fastpath_recv_updates fails when BeginPaint/EndPaint are not defined

### ISSUE THREAD

**Issue by lazyruss** [FreeRDP/FreeRDP#4835]
regression in RC3 vs RC2.
BeginPaint/EndPaint must be defined:

	if (!IFCALLRESULT(FALSE, update->BeginPaint, update->context))
		return -2;

should it be 	if (!IFCALLRESULT(TRUE, update->BeginPaint, update->context))
instead?

**Comment by akallabeth** [comment]
No, why? if it is not there it should fail.

**Comment by lazyruss** [comment]
@akallabeth i've got service that does not paint,  so it did not make sense.

**Comment by akallabeth** [comment]
@lazyruss ok, could you describe that a bit more? Might be a good idea to know the use case to avoid such issues.

**Comment by hardening** [comment]
I kinda agree, why `BeginPaint/EndPaint` are mandatory ?

**Comment by akallabeth** [comment]
@hardening Reopened, as mentioned, would be a good idea to write up what is required by the described scenario to take that into account for future error check enhancements.
Might also be a good idea to add a debug option to the `IFCALL` defines to print a error/warning when a callback is not set.

**Comment by lazyruss** [comment]
@akallabeth it's a service, like WebConnect.

**Comment by akallabeth** [comment]
@lazyruss Ok, got that much. Intended to get the information which callbacks are optional in your case. (WebConnect et al still need at least `EndPaint` callback if you want to support someting older than windows 8.1/10 (which were the first ones with h264 support)
