### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [FreeRDP/FreeRDP#4841]
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by akallabeth** [comment]
@LeandroStanger Would suggest you look at https://remmina.org/
FreeRDP is client side a command line utility which does (currently) not really work great for that use case and server side needs access to stuff that is (currently) not exposed in the flatpak sandbox

**Comment by akallabeth** [comment]
Initial version in #5156

**Comment by akallabeth** [comment]
Ok, a basic flatpak is now available on master.
Using `xfreerdp` on X11 and `wlfreerdp` on wayland.
