### ISSUE TITLE
X11 Client Black Border around remoteapp window that appears on all workspaces

### ISSUE THREAD

**Issue by mj-sakellaropoulos** [FreeRDP/FreeRDP#4846]
**Describe the bug**
Black border renders above (most) other windows and appears on all workspaces. Only occurs during remoteapp connection to Windows 10 host (Education) running Visual Studio 2017.

**To Reproduce**
1. RemoteApp Visual Studio 2017 setup on Windows 10 with RemoteAppTool
2. Execute command line
3. Splash screen has no border
4. Slightly after the main application window appears, the black border appears
5. Drag other windows onto border and border overlaps them
6. Switch to another work space and the black border is still rendered (not consistent, sometimes the remoteapp window minimizes/disappears on workspace switch)
7. Mouse can still interact with border (aka resize) when it is overlapping another window or on a different desktop.

**Expected behavior**
No black border that renders above all other windows on all workspaces

**Screenshots**
![image](https://user-images.githubusercontent.com/36081545/45228112-43f58a00-b290-11e8-87cf-0fe4d44573b7.png)
![image](https://user-images.githubusercontent.com/36081545/45230002-7655b600-b295-11e8-9174-3519b3d7f160.png)

**Linux Environment**
* Distro: Manjaro (latest)
* Kernel 4.17
* Window manager: bug occurs on both i3 and MATE

**Application details**
* Affected Version of FreeRDP
FreeRDP version 2.0.0-rc3 (n/a)
FreeRDP version 2.0.0-dev4 (c2e2eb910) [latest as of now]
* Command line used
xfreerdp /u:user /app:"||vs17" /v:hostname
* output of `/buildconfig`
Not sure where this is.
* OS version connecting to
Windows 10 Education Version 10.0.16299.611
* log level trace
https://gist.github.com/mj-sakellaropoulos/3099b0c1b6bddc0850ccc79074bc25ff

**xwininfo & xprop of window**
```
xwininfo: Window id: 0x3c0015b "Start Page - Microsoft Visual Studio "
  Absolute upper-left X:  1803
  Absolute upper-left Y:  19
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1258
  Height: 2085
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +1803+19  -779+19  -779-56  +1803-56
  -geometry 1058x1885+1803+19

~ >>> xprop                                                                                                  
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 200 by 200
		program specified maximum size: 3854 by 2174
		program specified resize increment: 1 by 1
_NET_WM_DESKTOP(CARDINAL) = 0
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_NAME(UTF8_STRING) = "Start Page - Microsoft Visual Studio "
WM_NAME(STRING) = "Start Page - Microsoft Visual Studio "
_NET_WM_PID(CARDINAL) = 10948
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x0, 0x0, 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
WM_CLASS(STRING) = "RAIL", "RAIL:000202EC"
```

**xwininfo & xprop of border**
```
xwininfo: Window id: 0x3c001b1 (has no name)
  Absolute upper-left X:  1922
  Absolute upper-left Y:  710
  Relative upper-left X:  1922
  Relative upper-left Y:  710
  Width: 1908
  Height: 9
  Depth: 24
  Visual: 0x20
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x22 (installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +1922+710  -10+710  -10-1441  +1922-1441
  -geometry 1798x65516-10+710

~ >>> xprop                                                                                                  
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 110 by 29
		program specified maximum size: 3854 by 2174
		program specified resize increment: 1 by 1
_NET_WM_NAME(UTF8_STRING) = 
WM_NAME(STRING) = 
_NET_WM_PID(CARDINAL) = 10948
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_POPUP
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_PAGER, _NET_WM_STATE_SKIP_TASKBAR
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x0, 0x0, 0x0
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
WM_CLASS(STRING) = "RAIL", "RAIL:00040210"
```

**Comment by mj-sakellaropoulos** [comment]
Update: Apparently each edge of the "border" is a window. Running ```xdotool windowunmap $border_part_win_id``` removes that edge of the border.

**Comment by mj-sakellaropoulos** [comment]
Cause: The bug is caused by the border windows being designated as "override redirect" windows. The only way to solve this is to properly detect these border windows and not apply the "override redirect" designation. ref /client/X11/xf_window.c function xf_SetWindowStyle.
I have dug as far as I can with my little experience, the rest is up to someone else.

**Comment by mj-sakellaropoulos** [comment]
Cause for being drawn on top of everything: 
- The 4 VisualStudioGlowWindow (s) have the WS_EX_TOOLWINDOW style applied to them, which cause freerdp to set them as "override redirect" (xf_window.c line 648). 
- They also have the style WS_POPUP, which triggers xf_SetWindowUnlisted to add the _NET_WM_STATE_SKIP_PAGER hint.
Cause for the border being larger than expected: I suspect those windows normally have an alpha applied to them on Windows, causing only the 1px purple/grey stip to be visible. The windows always have a 9px width, they are just normally transparent.
I hope my sleuthing can help resolve this.

**Comment by akallabeth** [comment]
@mj-sakellaropoulos Thank you for the analysis, hope to find time to fix that

**Comment by mj-sakellaropoulos** [comment]
I've been able to repro this on the official windows remoteapp client, the black border will appear on any window that has the "Metro Border" aka drop shadows, glows, etc. The only bug unique to FreeRDP is the border rendering above other windows. The broken alpha channel seems to be common to many platforms.

**Comment by akallabeth** [comment]
I've tried to fix it with #4891 but don't know if all corner cases are fixed (or just my setup)
could anyone verify that?

**Comment by akallabeth** [comment]
Note, the fix should only remove the fact that the window is above the currently active one, the transparency issue is a harder beast.

**Comment by mj-sakellaropoulos** [comment]
![image](https://user-images.githubusercontent.com/36081545/46155961-73bc0000-c246-11e8-91e0-3fdf4e0d774e.png)
No improvements on my end
Not sure I'm doing this right? I'm testing (same build config) on the "rail_fixes" branch on the fork referenced by PR. I'm also getting intermittent crashes opening notepad with rail and this message is getting printed repeatedly: ` [INFO][com.freerdp.client.x11] - Property 337 does not exist`. I can also no longer interact with the visual studio window (clicking, etc).

**Comment by warreq** [comment]
I'm experiencing the exact same issue as @mj-sakellaropoulos described. The black borders are rendered on top of other windows.

This happens for me on both the release version of FreeRDP on Ubuntu 18.04 as well as in the [nightly build](https://ci.freerdp.com/job/freerdp-nightly-source/652/).

![freerdp-vs-blackborder](https://user-images.githubusercontent.com/2846522/57199792-7cff0f00-6f83-11e9-9dae-c129ab25a4eb.png)

The issue only occurs when Visual Studio is windowed -- the 1-pixel focus border is not drawn when maximized.

```
Windows 10 version 1809
Visual Studio 2017 & Visual Studio 2019

$ /opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 2.0.0-dev5 (f867c90e4)
```

@akallabeth should I create a new issue or would you re-open this one?

**Comment by serefarikan** [comment]
I can confirm that I'm having the exact same issue as described by @warreq 

```
Windows Server 2016
Visual Studio 2017

$ /opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 2.0.0-dev5 (4a6b843f1)
```

**Comment by ofir150** [comment]
I can also confirm the crash issue @mj-sakellaropoulos mentioned still persists as of latest FreeRDP version available in the git.

In my case I am using the remoteappmode of FreeRDP in order to open Microsoft Outlook application remotely. The outlook application opens normally but then we have an authentication window pop up and as a result both the authentication window and the outlook application crash. When looking at the output in the terminal I see the message “[INFO] [com.freerdp.client.x11] Property 304 (_NET_WM_STATE) does not exist” (I added the atom property name in the brackets by printing it from the code). 

This issue was tested on Ubuntu 16.04 + 18.04 , Arch Linux 5, Mint 18 and CentOS 6+7 but was only occurring on Ubuntu 18.04 and CentOS 7.  
This issue happens in both the latest FreeRDP release (v 2.0.0 rc4) and in the master version (v 2.0.0-dev5).

@akallabeth Do you have any suggestion for us on how to solve this issue? I can also create a new issue if required.

Thanks!

**Comment by Ninlives** [comment]
Still have this issue on 2.1.2

**Comment by marcussacana** [comment]
Yes, 2.2.0 with this bug as well

**Comment by thrifty-txt** [comment]
Might be time to reopen this issue as it still exists with 2.3.2 on i3wm.

**Comment by rod-laycock** [comment]
Issue still persists.

Guest: Windows 10.
App: Visual Studio 2022 Community

Host: Ubuntu 22.04, Wayland
XFreeRDP: 2.6.1

Command:
xfreerdp /u:$RDP_User /p:$RDP_Password /v:$RDP_IP /gdi:hw +clipboard /dynamic-resolution /bpp:32 /cert:ignore /app:"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe" 

Only when running Visual Studio does it leave a border when a native window is brought into the foreground and VS 2022 sent to background.

Any other app running on the guest seems fine.

**Comment by nan4k7** [comment]
> Issue still persists.
> 
> Guest: Windows 10. App: Visual Studio 2022 Community
> 
> Host: Ubuntu 22.04, Wayland XFreeRDP: 2.6.1
> 
> Command: xfreerdp /u:$RDP_User /p:$RDP_Password /v:$RDP_IP /gdi:hw +clipboard /dynamic-resolution /bpp:32 /cert:ignore /app:"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe"
> 
> Only when running Visual Studio does it leave a border when a native window is brought into the foreground and VS 2022 sent to background.
> 
> Any other app running on the guest seems fine.

Also having this issue on same setup. Any news?
