### ISSUE TITLE
Memory leaks: application memory usage grows until it crashes

### ISSUE THREAD

**Issue by v-odin** [FreeRDP/FreeRDP#4847]
**Description**
The memory usage continuously grows using wfreerdp on WIndows.
As an example after around 30 minutes app occupied ~650MB.
It grows till it reaches 2GB and then crashes (32bit)

**To Reproduce**
On remote machine run the web browser with video. E.g some YouTube video.
./wfreerdp.exe -u:_user_ -p:_pass_ -w:1800 -h:900 -v:_IP_
Watch the memory usage of the app

**Expected behavior**
The growth should stop at around 150MB since there is a pool for frames caching

**Screenshots**
![1](https://user-images.githubusercontent.com/3415477/45257935-c96f5c00-b3ae-11e8-8e03-89a9dba263c0.png)

**Application details**

- FreeRDP version 2.0.0-dev4 (c2e2eb910)
- Command: ./wfreerdp.exe -u:_user_ -p:_pass_ -w:1800 -h:900 -v:_IP_
- Connect to  Windows 10
- Original log is 540MB. Attaching reduced: [RDPreduced.log](https://github.com/FreeRDP/FreeRDP/files/2363682/RDPreduced.log)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Comment by akallabeth** [comment]
@v-odin Does this also happen with `/gdi:sw`?

**Comment by v-odin** [comment]
@akallabeth, that changed the behavior completely. Now it is something around 80MB.
Are there valuable cons using /gdi:sw?

**Comment by v-odin** [comment]
@akallabeth got it. Many thanks for your help!
