### ISSUE TITLE
Enabling the (settings->AllowFontSmoothing in FreeRDP) or (/fonts in xfreerdp) does not reflected in remote Windows machine(ClearType).

### ISSUE THREAD

**Issue by Jagadeesh1210** [FreeRDP/FreeRDP#4860]
I am trying to connect to a windows 10 machine using the xfreerdp and it provides an option /fonts or +fonts which should enable the flag 'Turn on ClearType'. We can check this flag in control panel in which this setting named 'Adjust ClearType Text'.

Here is the command line used to connect:
xfreerdp /u:username /p:password /microphone /sound /fonts /g:gateway /v:hostname

by default font smoothing is disabled, i enabled it by sending the /fonts in command line. But still i am not able to see it enabled in remote machine.

P.S: Let me know if anybody has any information regarding this. Thanks!

**Describe the bug**
I am trying to connect to a windows 10 machine using the xfreerdp and it provides an option /fonts which should enable the opton in remote machine 'Turn on ClearType'. We can check this flag in control panel in which this setting named 'Adjust ClearType Text'.

**To Reproduce**
Here is the command line used to connect:
xfreerdp /u:username /p:password /microphone /sound /fonts /g:gateway /v:hostname

By default font smoothing is disabled, i enabled it by sending the /fonts in command line. But still i am not able to see it enabled in remote machine. And make sure the ClearType is disabled in remote machine.

**Expected behavior**
'Turn on ClearType' should be enabled by sending the /fonts options in xfreerdp.

**Screenshots**
<img width="1018" alt="screen shot 2018-09-18 at 2 31 46 pm" src="https://user-images.githubusercontent.com/5877963/45676885-79338f00-bb50-11e8-9e06-e23c4fe094af.png">
<img width="692" alt="screen shot 2018-09-18 at 2 31 58 pm" src="https://user-images.githubusercontent.com/5877963/45676886-79cc2580-bb50-11e8-96db-e1eaff6acbbd.png">

** Application details

* Version of FreeRDP
This is FreeRDP version 2.0.0-dev4 (0b7b9c0)
* Command line used
xfreerdp /u:username /p:password /microphone /sound /fonts /g:gateway /v:hostname
* output of `/buildconfig`
BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_FLAG_SEARCH_PATHS_FIRST=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB= HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H= HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H= HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=ON WITH_MACAUDIO_AVAILABLE=1 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations
Compiler:            Clang, 9.1.0.9020039
Target architecture: x64
* OS version connecting to
Windows 10

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device:Mac

**Additional context**

** Please remove this text before submitting your issue!

_Thank you for reporting a bug!_

**Comment by Jagadeesh1210** [comment]
I am trying to connect to a windows 10 machine using the xfreerdp and it provides an option /fonts or +fonts which should enable the flag 'Turn on ClearType'. We can check this flag in control panel in which this setting named 'Adjust ClearType Text'. 

Here is the command line used to connect:
xfreerdp  /u:username /p:password /microphone /sound /fonts /g:gateway /v:hostname

by default font smoothing is disabled, i enabled it by sending the /fonts in command line. But still i am not able to see it enabled in remote machine.

P.S: Let me know if anybody has any information regarding this. Thanks!

**Comment by akallabeth** [comment]
@Jagadeesh1210 The flag works as expected (using it daily).
It is a RDP protocol feature and does not necessarily represent the default windows desktop settings.
You can check by connecting without the flag (fonts are really bad) and with the flag (fonts are smoother)

**Comment by akallabeth** [comment]
You might want to add `/network:auto` and/or `+aero` for newer windows versions as the protocol they use works different from older systems. They render more stuff server side so the flag might not do what you expect it does.

**Comment by Jagadeesh1210** [comment]
I have tried to connect to windows(10) machine from mac using the freeRDP in which i have enabled the flag(AllowFontSmoothing) and it is not worked. So used xfreerdp from mac in which i have added the option /fonts to enable font smoothing but not worked. 

Just tried by adding the /network:auto | +aero . But no luck.

**Comment by akallabeth** [comment]
@Jagadeesh1210 check your server policy settings. As mentioned, the flags are sent to the server but it is up to the server to use them.
As for windows 10/server 2016 I'd recommend the `/gfx` series of flags as that enables the new graphics remoting (which might be what you're looking for as the 'old' RDP stuff is being phased out)

**Comment by Jagadeesh1210** [comment]
I have checked the Windows-10 policy details and remote access permissions are clear. And tried /gfx but no luck. And testing this with latest free rdp version(FreeRDP version 2.0.0-dev4 (0b7b9c0)).

Command used: 
xfreerdp /gfx /fonts +aero /network:auto  /u:user /p:password /microphone /sound /g:gateway /v:hostname

**Comment by akallabeth** [comment]
@Jagadeesh1210 Are you sure your test case is correct? I can confirm the RDP flag is sent to the server, but I don't know if your assumption about the menu you check is correct.

**Comment by Jagadeesh1210** [comment]
@akallabeth  Thanks for the information. I can see the difference in font quality by using the /fonts as you  suggested.
But my requirement is that i need to enable the 'clearType' in remote machine from freeRDP.
I can do it by using the windows MSTSC. In which if we select the 'font smoothing' option then remote machine enables the 'clearType'
<img width="412" alt="screen shot 2018-09-19 at 10 02 01 pm" src="https://user-images.githubusercontent.com/5877963/45767627-4d033580-bc58-11e8-8d06-b98fdf4b6eee.png">

Note: And i haven't found this option in Mac MSTSC. If you have any idea how can i achieve this in freerdp, Please let me know. Thanks.

**Comment by akallabeth** [comment]
@Jagadeesh1210 Just checked to my win10 test machine. The setting for cleartype also works when connecting without the RDP `+fonts` flag. Looks like your issue is something different (this setting is not influenced by that flag)

**Comment by Jagadeesh1210** [comment]
@akallabeth I do understand from observations that the flag and cleartype setting are independent.
Is there any other way to set(clearType) from using freerdp. OR can i create seperate issue for that. Thanks.

**Comment by akallabeth** [comment]
@Jagadeesh1210 No, there is no other option specified in the (base) protocol.
Of course, RDP protocol is always evolving, so if you manage to find a spec that provides such a feature feel free to create an issue with a link to that.

**Comment by VPanteleev-S7** [comment]
Hi, not sure if this is a known issue or actionable, but just wanted to report that I have been unable to get ClearType (font antialiasing) to work at all. I'm trying to use xfreerdp on X11 and am connecting to a Windows 10 VM.

I've tried:

- Adding `+fonts` as per https://github.com/FreeRDP/FreeRDP/issues/4860#issuecomment-422313103
- Adding `/network:auto` or `/network:lan` as per https://github.com/FreeRDP/FreeRDP/issues/4860#issuecomment-422322937
- Adding `+aero` as per the same comment
- Adding `/gfx` as per https://github.com/FreeRDP/FreeRDP/issues/4860#issuecomment-422336193
- Adding `/gdi:sw` as per https://github.com/FreeRDP/FreeRDP/issues/4331#issuecomment-353938532

However, fonts remain aliased, and the ClearType Text Tuner always says "ClearType can't be turned on from this remote session".

It does look fine in the VM's emulated graphics card; the problem happens only with RDP.

**Comment by akallabeth** [comment]
@VPanteleev-S7 the only options available via RDP protocol are the `+fonts` flag and `/network:auto`. If you are unsure if this is a `FreeRDP` bug try these two options with `mstsc` (the microsoft RDP client) and check if the behaviour is different. if not, there is nothing we can do.

**Comment by VPanteleev-S7** [comment]
Thanks. After a long hunt, I discovered that `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\fNoFontSmoothing` was set to `1`.
