### ISSUE TITLE
enable h264 support for ubuntu

### ISSUE THREAD

**Issue by ukos-git** [FreeRDP/FreeRDP#4863]
In ubunutu:bionic, remmina tries to allow the h264 option in the drop-down menu but it is not activated in the freerdp lib.

![screenshot from 2018-09-18 15-48-58](https://user-images.githubusercontent.com/16167358/45692240-98371e80-bb5a-11e8-9e9d-4a4acb2fe2eb.png)

selecting this option leads to the following error:

![screenshot from 2018-09-18 15-54-04](https://user-images.githubusercontent.com/16167358/45692471-23181900-bb5b-11e8-9fd7-6cd70dbb8d66.png)

I'm not sure why h264 support is disabled on default so I built a docker container which produces `*.deb` files with h264 enabled and I do not seem to have problems with it on ubuntu:bionic.

It is a [simple change](https://github.com/ukos-git/docker-freerdp/blob/master/Dockerfile#L92) to the [debian/rules](https://github.com/FreeRDP/FreeRDP/blob/master/packaging/deb/freerdp-nightly/rules#L9) file which adds the `-DWITH_GFX_H264=ON` flag.

docker container for building the deb file is here:
https://github.com/ukos-git/docker-freerdp

why not enable the h264 support for the deb files? Is it because of legal issues of the codec?

**Comment by akallabeth** [comment]
We only provide nightly builds and disabled it there because of dependency issues 14.04 et al don't like it)

**Comment by akallabeth** [comment]
Are you talking about the deb from the official repos? Don't know their package policies, they use their own recipies ;) as for the nightlies, that might happen at some point (when all debian/ubuntu versions support ffmpeg recent enough)

**Comment by ukos-git** [comment]
I just see that they have their own [debian/rules](https://salsa.debian.org/debian-remote-team/freerdp2/blob/master/debian/rules) file. Thank you for clarifying.

@bmiklautz Maybe the debian maintainers can do something about it at their repo, but I'm not sure how legal issues are for H264. Maybe only add it for ubuntu?

**Comment by akallabeth** [comment]
Closing this as it is only relevant for building.
