### ISSUE TITLE
Broken compilation on freerdp android

### ISSUE THREAD

**Issue by shailendrapundhir** [FreeRDP/FreeRDP#4877]
Tried compilation of freerdp on linux for android . Followed the steps in wiki. All mentioned dependencies installed.

When executing this command : ./scripts/android-build-freerdp.sh --ndk "path to ndk" --sdk "path to sdk", 

the build fails while compiling openssl, giving the following error : 
clang error: unknown argument '-mandroid' 

This step was working around an year ago. 
Environment : Fresh install ubuntu 16.04 LTS, 4gb ram, 2 cores intel processor, dependencies mentioned in wiki installed, updated, upgraded, ndk r18.
However the issue is not limited to this environment , it is consistent on every platform( also tried on ubuntu 18, centos 7).

**Comment by shailendrapundhir** [comment]
Any help / workaround in the scripts to make compilation work again would be appreciated. Need to do this because freerdp does not connect to windows 10 update 1803(released in march 2018), gives ERRCONNECT_PASSWORD_CERTAINLY_EXPIRED error code. However, to my knowledge reading the forums and issues in freerdp, it seems the issue has been fixed in freerdp, but to make it work in android we need to fix the broken compilation for android in linux. Thanks again.

**Comment by akallabeth** [comment]
@shailendrapundhir Android NDK 16 and up are currently not working, try with an older one.

**Comment by shailendrapundhir** [comment]
Thanks for the info. Will try with newer version and let you know. Thanks.
