### ISSUE TITLE
newer versions of freerdp do not allow remoteApp

### ISSUE THREAD

**Issue by lpuglia** [FreeRDP/FreeRDP#4886]
I setupt my remote machine using:

[https://bmullan.wordpress.com/2012/09/17/howto-integrate-windows-apps-into-the-ubuntu-linux-desktop-using-windows-remoteapp/](https://bmullan.wordpress.com/2012/09/17/howto-integrate-windows-apps-into-the-ubuntu-linux-desktop-using-windows-remoteapp/)

then i tried to connect to it using my Fedora 27 machine with `freerdp 2.0.0 rc2` with the following command:

`xfreerdp /u:user  /v:host /app:"||Paint" /log-level:"Debug"`

and i get the following messages:

```
...
[16:59:50:943] [19008:19009] [DEBUG][com.freerdp.core.update] - Frame Marker Alternate Secondary Drawing Order (0x0D)
[16:59:50:947] [19008:19009] [DEBUG][com.freerdp.core.rdp] - recv Set Error Info Data PDU (0x2F), length: 22
[16:59:50:947] [19008:19009] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off their session on the server.
[16:59:50:078] [19008:19009] [DEBUG][com.freerdp.core.rdp] - DisconnectProviderUltimatum: reason: 3
[16:59:50:078] [19008:19009] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
[16:59:50:078] [19008:19009] [DEBUG][com.freerdp.core] - rdp_check_fds() - -1
```

The problem is confirmed for a separate Ubuntu 16.04 machine with `freerdp 1.1.0` and the command:

`xfreerdp -u user --app --plugin rail --data "||Paint" -- host`

I was giving up but then i tried on another machine with Centos 7 and `freerdp 1.0.2` and surprise surprise: it works! any idea why this is happening?

**Comment by akallabeth** [comment]
You are always connecting to the same server? Sounds more like the app is not allowed to be redirected...

**Comment by akallabeth** [comment]
Note: using remote app regularily, so it is working with win 7 up to 10

**Comment by akallabeth** [comment]
Ok, just verified with current master to a windows 10 host with `xfreerdp /v:host /p:pass /u:user /app:"||Notepad"` is working, `xfreerdp /v:host /p:pass /u:user /app:"||Notepad.exe"` results in the error you describe.
So definitely a configuration issue server side.
Check `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Terminal Server\TSAppAllowList\Applications` which apps are exported with which name.

But thanks to you I've found an unrelated issue fixed with #4887 :)

**Comment by lpuglia** [comment]
> Ok, just verified with current master to a windows 10 host with `xfreerdp /v:host /p:pass /u:user /app:"||Notepad"` is working, `xfreerdp /v:host /p:pass /u:user /app:"||Notepad.exe"` results in the error you describe.
> So definitely a configuration issue server side.
> Check `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Terminal Server\TSAppAllowList\Applications` which apps are exported with which name.
> 
> But thanks to you I've found an unrelated issue fixed with #4887 :)

Of course i'm always connecting to the same server, the application is correctly set, otherwise i would be not able to connect from CentOS7, any suggestion?

**Comment by lpuglia** [comment]
Ok, this is definitvely some problem on the CLIENT side, i just copied xfreerdp from my CENTOS machine (it works on it) and put it on my Fedora machine:
```
scp CentOS7:/usr/lib64/libfreerdp-cache.so.1.0.2 .
scp CentOS7:/usr/lib64/libfreerdp-channels.so.1.0.2
scp CentOS7:/usr/lib64/libfreerdp-channels.so.1.0.2 .
scp CentOS7:/usr/lib64/libfreerdp-codec.so.1.0.2 .
scp CentOS7:/usr/lib64/libfreerdp-core.so.1.0.2 .
scp CentOS7:/usr/lib64/libfreerdp-gdi.so.1.0.2 .
scp CentOS7:/usr/lib64/libfreerdp-kbd.so.1.0.2 .
scp CentOS7:/usr/lib64/libfreerdp-rail.so.1.0.2 .
scp CentOS7:/usr/lib64/libfreerdp-utils.so.1.0.2 .
```
then i run it and I got the SAME ERROR with a different format:

```
LD_LIBRARY_PATH=. ./xfreerdp -u user --app --plugin rail --data "||Paint" -- host                                                                                                                      loading plugin rail
freerdp_load_library_symbol: failed to open /usr/lib64/freerdp/rail.so: /usr/lib64/freerdp/rail.so: cannot open shared object file: No such file or directory
freerdp_load_plugin: failed to load rail/VirtualChannelEntry
connected to lpuglia-IVM.ger.corp.intel.com:3389
creating directory /home/lpuglia/.freerdp/certs
Certificate details:
	Subject: CN = lpuglia-IVM.ger.corp.intel.com
	Issuer: CN = lpuglia-IVM.ger.corp.intel.com
	Thumbprint: d8:74:ad:1e:7d:fe:7e:4c:58:47:e4:91:4d:0c:b3:2f:b6:03:3e
The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the documentation on how to create local certificate store for a private CA.
Do you trust the above certificate? (Y/N) y
Password: 
ERRINFO_UNKNOWN 0x0000000C: Unknown error.
```
then i notice the missing library error and i did:
```
scp CentOS7:/usr/lib64/freerdp/rail.so .
```
after that i got it working!!!!! this so weird that i need an explanation.

**Comment by akallabeth** [comment]
My guess is a broken build.
