### ISSUE TITLE
Remote Desktop password field doesn't have focus on Server 2016

### ISSUE THREAD

**Issue by fonk** [FreeRDP/FreeRDP#4892]
Hi!

When connecting to a Windows Server 2016 Box (Version 1607; Build 14393.2485) with /sec:tls, the username field ist focused (with correct username prefilled). At least https://superuser.com/questions/1264343/remote-desktop-password-field-doesnt-have-focus states, that this can be fixed for Windows clients with a clientside patch. I would expect that also a freerdp patch is required to get the password field focused after connect.

Best regards,
Frank

**Comment by akallabeth** [comment]
@fonk could you please explain your issue in a little more detail? The referenced link is sparse with information and we have little control over where the server sets the initial focus in the rdp session.

**Comment by fonk** [comment]
Well, unfortunately I don't have more information either... My concern is in fact the initial focus and I thought that it's servercontrolled unless I found that post, that a Client-Upgrade fixed the issue for Windows-Users... But if the protocol doesn't have controls for which field is focused on connect, i understand that you can't do a lot...
