### ISSUE TITLE
clipboard broken on fresh build

### ISSUE THREAD

**Issue by drocsid** [FreeRDP/FreeRDP#4895]
**Describe the bug**
clipboard doesn't work

**To Reproduce**
Build software via https://github.com/FreeRDP/FreeRDP/wiki/Compilation for debian
https://github.com/FreeRDP/FreeRDP/wiki/Compilation

./tmp/opt/freerdp-nightly/bin/xfreerdp +clipboard /u:my-username /v:remotehost.net /w:1400 /h:1000 /drive:schemas,/tmp/schemas

**Expected behavior**
Select text in application, copy and it should be accessible from my linux desktop when I chose paste or middle click paste.

** Application details

* Version of FreeRDP
./tmp/opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 2.0.0-dev4 (d0612151f)

* Command line used
./tmp/opt/freerdp-nightly/bin/xfreerdp +clipboard /u:my-username /v:remotehost.net /w:1400 /h:1000 /drive:schemas,/tmp/schemas

* output of `/buildconfig`
This is FreeRDP version 2.0.0-dev4 (d0612151f)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/home/colin/build/FreeRDP=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer

Compiler:            GNU, 8.2.0
Target architecture: x64

* OS version connecting to

Windows Server 2012 R2

* If available the log output from a run with `/log-level:trace` 

**Desktop (please complete the following information):**
 - OS: debian 
 - Version sid / buster

**Comment by drocsid** [comment]
A trace log gzipped but with personal information removed

[trace-log.gz](https://github.com/FreeRDP/FreeRDP/files/2421589/trace-log.gz)

**Comment by akallabeth** [comment]
@drocsid Seems I need some additional info regarding this and #4896 
I can see you have started `/tmp/opt/freerdp-nightly/bin/xfreerdp` instead of `/opt/freerdp-nightly/bin/xfreerdp` which is the default path used by the nightly package build (I assume you used that one?)
If you didn't install it there might be issues with parts of the required libraries not being found.

**Comment by drocsid** [comment]
Hi @akallabeth ,

I tried this 3X yesterday. 

First with the debian package provided in debian buster. 

Then with a daily package found on your build server. 

Finally I built the daily because the one on your build server https://ci.freerdp.com/job/freerdp-nightly-binaries/ was not a daily but built a week ago. It looked like changes related to the clipboard had been pushed to git recently but not in the daily build since it hasn't been built there in a week.

I mentioned this in the #freerdp irc channel.

The final example I built the daily as explained above: 

```
Steps to reproduce the behavior:
Build software via https://github.com/FreeRDP/FreeRDP/wiki/Compilation for debian
https://github.com/FreeRDP/FreeRDP/wiki/Compilation
```
I used the debian package builder but i ran on the compiled binary...

**Comment by akallabeth** [comment]
@drocsid And you are sure clipboard redirection allowed by the server you connect to?

**Comment by akallabeth** [comment]
@drocsid FYI: Did a fresh build on my debian stretch today, clipboard is working flawlessly against windows 7, 8, 81. and 10

**Comment by drocsid** [comment]
@akallabeth I wasn't aware that clipboard redirection could be disabled by the server. Then how do we check the windows server 2012 configuration to see if it's enabled or not?

**Comment by drocsid** [comment]
https://social.technet.microsoft.com/Forums/Azure/en-US/778e1cb3-f3d0-4143-9b03-67a50cb3a3de/windows-2012r2-remoteapp-amp-clipboard-redirection-doesnt-work?forum=winserverTS suggests that there is a gateway config that would define this policy. I'm not sure I have the authority to check it or how to do so. If you have a suggestion if I can check it from the host or if it requires greater AD access, I can check it if possible.

**Comment by akallabeth** [comment]
@drocsid sorry, missed these posts.
Check `Computer Configuration -> Administrative templates -> Windows components -> Remote Desktop Session Host` in `gpedit.msc`

**Comment by akallabeth** [comment]
Closing this, assuming it is the configuration error.
Reopen/create a new issue if it is something else.

**Comment by drocsid** [comment]
> @drocsid sorry, missed these posts.
> Check `Computer Configuration -> Administrative templates -> Windows components -> Remote Desktop Session Host` in `gpedit.msc`

Thanks for sharing that. I will double check, but I assume you're correct that it's a configuration issue. Sorry for my lack of knowledge regarding that.
