### ISSUE TITLE
Use of deprecated ffmpeg library

### ISSUE THREAD

**Issue by vp1981** [FreeRDP/FreeRDP#4897]
**Is your feature request related to a problem? Please describe.**
The commit "[Rewrite of sound and microphone channels](https://github.com/FreeRDP/FreeRDP/commit/f89c1857b9773fe0a472caf95bc533f43abad48d)" introduces to FreeRDP the deprecated library --- libavresample, see "[lavr: deprecate the entire library ](https://github.com/FFmpeg/FFmpeg/commit/c29038f3041a4080342b2e333c1967d136749c0f#diff-c43509f01080b70b6126c9fa7682e9f3)", though it was deprecated (on Dec 25 2017) almost at the same time as the mentioned commit (on Feb 20 2018).

Now it is impossible to build FreeRDP with FFMPEG support on systems where libavresample library is dropped from FFMPEG package (I know only about Archlinux which I use).

**Describe the solution you'd like**
According to commit message of "[lavr: deprecate the entire library ](https://github.com/FFmpeg/FFmpeg/commit/c29038f3041a4080342b2e333c1967d136749c0f#diff-c43509f01080b70b6126c9fa7682e9f3)"  the libswresample is considered as replacement for libavresample. Is it time to use that library instead of libavresample?

**Describe alternatives you've considered**
Now I build FreeRDP package for my distribution (Archlinux) without FFMPEG

**Comment by akallabeth** [comment]
FFMPEG / libav are really some pice of work regarding their API
Happy to accept a patch adding the option to use `swresample` though.

**Comment by hymer-up** [comment]
So is this because of this library conflict I have no sound from the server?  Build an old Freerdp/FFmpeg version from 2017 would be a temp workaround for #4845 ?

**Comment by vp1981** [comment]
@akallabeth , will do but not sure how quick it will be.

@hymer-up , I'm not sure. What OS do you use? What versions of libraries (are they distro provided or self-compiled)? Please answer in #4845.

**Comment by akallabeth** [comment]
Hi, best do a pull request. Testing is easy, just enable sound and redirection and listen to something.
Thank you for this.

**Comment by akallabeth** [comment]
@hymer-up Building without `WITH_DSP_FFMPEG` should be sufficient

**Comment by akallabeth** [comment]
@vp1981 Hi, any news on your patch?

**Comment by vp1981** [comment]
Hello,
I'm not fan of github way to work with git repositories, I prefer plain patches and ML. I did all necessary steps to make a pull request but might do some errors. Please check my PR: #4911 .

**Comment by akallabeth** [comment]
Closing as resolved (now prefer libswresample if it is available with fallback to avresample)
