### ISSUE TITLE
option to disable internal thread pool

### ISSUE THREAD

**Issue by sss123next** [FreeRDP/FreeRDP#4908]
**Is your feature request related to a problem? Please describe.**
in high load multi-user applications using internal thread pool for each rdp instance is suboptimal

**Describe the solution you'd like**
thread pool created inside libfreerdp/codec/rfx.c in RFX_CONTEXT* rfx_context_new(BOOL encoder) function and already have option to disable it.
this optioin need to be accessible via rdpSettings or any other api exported to end user.

**Additional context**

here is quicj and dirty patch to hard disable thread pool

```
diff --git a/libfreerdp/codec/rfx.c b/libfreerdp/codec/rfx.c
index b7b08738d..64ae36bf5 100644
--- a/libfreerdp/codec/rfx.c
+++ b/libfreerdp/codec/rfx.c
@@ -262,7 +262,7 @@ RFX_CONTEXT* rfx_context_new(BOOL encoder)
        if (!priv->BufferPool)
                goto error_BufferPool;
 
-#ifdef _WIN32
+/*#ifdef _WIN32
        {
                BOOL isVistaOrLater;
                OSVERSIONINFOA verinfo;
@@ -275,7 +275,8 @@ RFX_CONTEXT* rfx_context_new(BOOL encoder)
        }
 #else
        priv->UseThreads = TRUE;
-#endif
+#endif */
+       priv->UseThreads = FALSE;
        GetNativeSystemInfo(&sysinfo);
        priv->MinThreadCount = sysinfo.dwNumberOfProcessors;
        priv->MaxThreadCount = 0;

```

**Comment by akallabeth** [comment]
Pull requests welcome

**Comment by akallabeth** [comment]
Ok, just had a look at the code, thread pool can already be configured. Just set your desired number of threads and you're done.
