### ISSUE TITLE
FreeRDP crash on startup in Windows when started in service mode

### ISSUE THREAD

**Issue by MarcelBB** [FreeRDP/FreeRDP#4909]
**Description of the bug**

When FreeRDP is started from a service (SYSTEM user) it crashes with access violation on startup.
The crash happens in function **wfreerdp_client_global_init** (client\Windows\wf_client.c) on

strcat(home, getenv("HOMEDRIVE"));

as getenv returns NULL.

As SYSTEM user there is no HOME, HOMEDRIVE, HOMEPATH environment variables by default.

**To Reproduce**
1. Start FreeRDP from a service to just login a user

**Expected behavior**
Proper check of environment variables that does not exist

** Application details
* Latest version of FreeRDP (3Oct2018)
* OS version connecting to is Windows 8.1

**Desktop (please complete the following information):**
 - OS: Windows 8.1

**Comment by akallabeth** [comment]
Sounds like a bad idea to start a user process as service. (=root on unix ;))

Anyhow, the missing null check is definitely a bug.
