### ISSUE TITLE
Question: CredSSP fix for breaking change in March

### ISSUE THREAD

**Issue by bergmeister** [FreeRDP/FreeRDP#4919]
I am aware that there was a breaking change to CredSSP by a Windows update (March rollup [KB4088776](https://support.microsoft.com/en-us/help/4088776/windows-10-update-kb4088776)) this year that broke our private fork of freerdp v1.
Since an upgrade to the current v2 would be quite complex, we would ideally like to just cherry-pick the commit(s) that fixed it.
As far as I could see, this PR fixed the CredSSP issue: https://github.com/FreeRDP/FreeRDP/pull/4510
Can someone please confirm that and if they are aware of other commits that we would need to cherry-pick? Is there anything else to be aware of in terms of breaking changes since March?
Many thanks

**Comment by akallabeth** [comment]
@bergmeister You're most likely better off checking a diff between current and before the change and creating a patch for v1 on that and the appropriate credssp spec as the code changed significantly between v1 and v2.
(Note: I remember that there were 2 or 3 pulls as in the first approach some issues were found)
