### ISSUE TITLE
centos build error，，help！！！

### ISSUE THREAD

**Issue by w0rhost** [FreeRDP/FreeRDP#4923]
ninja: warning: phony target 'CheckIncludeFiles.c' names itself as an input; ignoring [-w phonycycle=warn]
[1/2] Building C object CMakeFiles/cmTryCompileExec217609347.dir/CheckIncludeFiles.c.o
FAILED: CMakeFiles/cmTryCompileExec217609347.dir/CheckIncludeFiles.c.o 
/usr/bin/cc   -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls  -fPIE -o CMakeFiles/cmTryCompileExec217609347.dir/CheckIncludeFiles.c.o   -c CheckIncludeFiles.c
CheckIncludeFiles.c:2:23: error: sys/modem.h: No such file or directory
cc1: warning: unrecognized command line option "-Wno-unused-result"
ninja: build stopped: subcommand failed.

Source:
/* */
#include <sys/modem.h>

int main(){return 0;}

Determining if files sys/filio.h exist failed with the following output:
Change Dir: /FreeRDP/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/ninja-build cmTryCompileExec700576346
ninja: warning: phony target 'CheckIncludeFiles.c' names itself as an input; ignoring [-w phonycycle=warn]
[1/2] Building C object CMakeFiles/cmTryCompileExec700576346.dir/CheckIncludeFiles.c.o
FAILED: CMakeFiles/cmTryCompileExec700576346.dir/CheckIncludeFiles.c.o 
/usr/bin/cc   -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls  -fPIE -o CMakeFiles/cmTryCompileExec700576346.dir/CheckIncludeFiles.c.o   -c CheckIncludeFiles.c
CheckIncludeFiles.c:2:23: error: sys/filio.h: No such file or directory
cc1: warning: unrecognized command line option "-Wno-unused-result"
ninja: build stopped: subcommand failed.

**Comment by akallabeth** [comment]
For support please use irc or the mailing list.
Don't forget to add some details, the ones provided here are not enough to diagnose.
