### ISSUE TITLE
Hang and jumbled display after running for a few hours

### ISSUE THREAD

**Issue by kavanst** [FreeRDP/FreeRDP#4928]
The issue is that wfreerdp hangs and displays a jumbled desktop after running for a few hours. No mouse or keyboard input is able to restore the application to usable state. I had to close it and connect the rdp connection again.

Windows 10 Pro connecting to Windows Server 2016.
Running commandline: c:\wfreerdp.exe /v:192.168.33.20 /size:3820x620 /audio-mode:0
Using the rolling release downloaded one month ago.

**Comment by akallabeth** [comment]
There have been significant changes in default settings in the last month, is this still an issue with up to date nightly?

**Comment by kavanst** [comment]
On the website https://cloudbase.it/freerdp-for-windows-nightly there are two versions:
1) WFreeRDP master branch (continuous build)
2) WFreeRDP stable 1.1 (continuous build)

I tried the stable 1.1 (continuous build) two weeks ago as it is recommended for production use and also encountered the issue above.

Can I check if the stable 1.1 (continuous build) do not contain the significant changes in Oct 2018?

**Comment by akallabeth** [comment]
There is only master with new commits, 1.1 is in maintainance
