### ISSUE TITLE
Centos 7.5 ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by ng0177** [FreeRDP/FreeRDP#4929]
On Centos 7.5 Linux 3.10.0-862.14.4.el7.x86_64, I get the below error when executing

`git clone git://github.com/FreeRDP/FreeRDP.git
cd FreeRDP
cmake -GNinja -DCHANNEL_URBDRC=OFF -DWITH_DSP_FFMPEG=OFF -DWITH_CUPS=OFF -DWITH_PULSE=OFF .
cmake --build .
cmake --build . --target install
`
.....
`[424/424] Linking C executable client/X11/xfreerdp
[th6mas@freckle75 FreeRDP]$ 
[th6mas@freckle75 FreeRDP]$ cmake --build . --target install
[1/1] Install the project...
FAILED: CMakeFiles/install.util 
cd /home/th6mas/FreeRDP && /usr/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /usr/local/share/man/man7/wlog.7
CMake Error at winpr/cmake_install.cmake:36 (FILE):
  file INSTALL cannot copy file "/home/th6mas/FreeRDP/winpr/wlog.7" to
  "/usr/local/share/man/man7/wlog.7".
Call Stack (most recent call first):
  cmake_install.cmake:37 (INCLUDE)

ninja: build stopped: subcommand failed.
`

**Comment by akallabeth** [comment]
Please use the mailing list or IRC for support questions.
The tracker is reserved for issues.

**Comment by ng0177** [comment]
I subscribed to the mailing list but cannot see how to post or create a thread. Thanks!

**Comment by akallabeth** [comment]
Ng0177 write a mail to the list?

**Comment by ng0177** [comment]
Sorry, my mistake: the welcome e-mail went into the wrong folder...
