### ISSUE TITLE
[CrossCompiling] Fix build and update wiki for MinGW compilation

### ISSUE THREAD

**Issue by jhonesk** [FreeRDP/FreeRDP#4930]
I followed this instructions (https://github.com/FreeRDP/FreeRDP/wiki/Compilation) for cross compiling FreeRDP to be used on windows hosts. I'm running Arch Linux. 

I compiled OpenSSL and MingGw just as the wiki suggests, and on the final step, when I try to cmake, the compilation fails and I receive the following message:

ps: Yes, I made sure that all the paths are correct before issuing the command.
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
FREERDP_VERSION=2.0.0-dev4
-- Git Revision 00af869cd
-- GCC default symbol visibility: hidden
CMake Error at CMakeLists.txt:490 (message):
  Unknown generator Unix Makefiles

-- Configuring incomplete, errors occurred!
See also "/home/jcruz/FreeRDP/mingw_build/CMakeFiles/CMakeOutput.log".
See also "/home/jcruz/FreeRDP/mingw_build/CMakeFiles/CMakeError.log".
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

I get this from the FreeRDP/CMakeLists.txt -> Line 490;

****************************************************************************************
   if (${CMAKE_GENERATOR} MATCHES "NMake Makefile*" OR ${CMAKE_GENERATOR} MATCHES "Ninja*")
		set(CMAKE_PDB_BINARY_DIR ${CMAKE_BINARY_DIR})
	elseif (${CMAKE_GENERATOR} MATCHES "Visual Studio*")
		set(CMAKE_PDB_BINARY_DIR "${CMAKE_BINARY_DIR}/\${CMAKE_INSTALL_CONFIG_NAME}")
	else()
		message(FATAL_ERROR "Unknown generator ${CMAKE_GENERATOR}")
	endif()
********************************************************************************************

And this from the /home/jcruz/FreeRDP/mingw_build/CMakeFiles/CMakeError.log : 

********************************************************************************************
Building C object CMakeFiles/cmTC_01eb5.dir/CheckIncludeFile.c.obj
/opt/mingw64/bin/x86_64-w64-mingw32-gcc   -DFREERDP_EXPORTS -Dsprintf_s=snprintf -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls    -o CMakeFiles/cmTC_01eb5.dir/CheckIncludeFile.c.obj   -c /home/jcruz/FreeRDP/mingw_build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/home/jcruz/FreeRDP/mingw_build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:21: fatal error: pthread.h: Arquivo ou diretório inexistente
 #include <pthread.h>
                     ^
compilation terminated.
make[1]: *** [CMakeFiles/cmTC_01eb5.dir/build.make:66: CMakeFiles/cmTC_01eb5.dir/CheckIncludeFile.c.obj] Error 1
make[1]: Leaving directory '/home/jcruz/FreeRDP/mingw_build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_01eb5/fast] Error 2

********************************************************************************************

I did not get anything that I judged useful from the /home/jcruz/FreeRDP/mingw_build/CMakeFiles/CMakeOutput.log.

I can see that it is probably related to the CMake Generator being used, but though I read about it, it is not clear to me where does one specifies which one to use; so I'm a bit dazed here.

Any help would be appreciated.

**Comment by jhonesk** [comment]
> Check your `CMakeCache.txt` for which dependencies have been detected and which symbols are defined.
> The cross compile wiki is a bit out of date :/ sorry

I do not see anything specifying dependencies neither I understand what you mean by  "which symbols are defined" in the CMakeCache file. Sorry for the ignorance, but I'm quite blind here!

**Comment by jhonesk** [comment]
Is there by any chance, a updated guide of some sort, to compile and use FreeRDP within Windows? I also tried compiling inside windows os using this tutorial (https://github.com/FreeRDP/FreeRDP/wiki/Build-on-Windows-Visual-C---2012-(32-and-64-bit)) but faced a bunch of errors as well.

**Comment by akallabeth** [comment]
@jhonesk windows builds are quite easy nowadays, just compile/install openssl and use vs2017 (they support CMake natively)

**Comment by jhonesk** [comment]
Thanks for your help. I think was able to compile it succesfully with CMake GUI using vs2017, once I got no error messages of any kind. But I am not sure what I should expect now. I have this directory that was populated after the build, but I have no executable or CLI binary. What am I missing?


![capture](https://user-images.githubusercontent.com/34694158/47095017-b8620800-d202-11e8-9e4f-f87ab1dc5630.PNG)

**Comment by akallabeth** [comment]
@jhonesk Better use the mailing list or IRC for support questions.
I'll keep this issue open as cross compilation and the wiki for that are definitely out of date.

**Comment by Neustradamus** [comment]
Have you progressed on it?

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/pull/9240 allows building freerdp on debian 12 (exception are our C++ components SDL-client and proxy modules due to the compiler/standard library lacking features)

wiki is updated at https://github.com/FreeRDP/FreeRDP/wiki/Compilation#compiling-for-mingw

consider this completed so far, closing.

**Comment by akallabeth** [comment]
@Neustradamus it is not a debian issue but the compiler does not support the syntax we use with the C++ components (e.g. C++ 17)

**Comment by akallabeth** [comment]
@Neustradamus did compile it on fedora 38 with SDL client today and that worked quite nice, will check debian later again, might be I did miss something.
(only issue encountered is a `cJSON` path not picked up automatically, but that is a todo for an upstream fix)
