### ISSUE TITLE
Request for release of 2.0.0-rc4

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#4931]
As you have integrated lots of important fixes since last RC it would be great to see another RC to be integrated in our openSUSE repository...

**Comment by akallabeth** [comment]
Working on it.
The remaining issues and pull requests need some review, any help appreciated.

**Comment by weberhofer** [comment]
Thanks, @akallabeth. I know how much work a "simple" release is. I'm looking forward to update our sources in openSUSE as many issues have been fixed again!

**Comment by akallabeth** [comment]
@weberhofer looks like you'll get your wish

**Comment by weberhofer** [comment]
Cool.

**Comment by bmiklautz** [comment]
Here we go #5032.
