### ISSUE TITLE
Requesting for password in the terminal or remote window?

### ISSUE THREAD

**Issue by mahmoodn** [FreeRDP/FreeRDP#4935]
I use xfreerdp to connect to two windows 10 machines. All things are good. However, for one of them, I have to enter the password locally in the terminal while on the other, I have to enter the password in the in the remote window. Please see below

```
$ xfreerdp --plugin rdpsnd --plugin rdpdr --data disk:home:/home/mahmood --  -u mahmood 10.1.1.198
loading plugin rdpsnd
loading plugin rdpdr
connected to 10.1.1.198:3389
Password: 
```
After that I can see the remote window. The other is:
```
$ xfreerdp --plugin rdpsnd --plugin rdpdr --data disk:home:/home/mahmood --  -u mahmood 10.1.1.199
loading plugin rdpsnd
loading plugin rdpdr
connected to 10.1.1.199:3389
connected to 10.1.1.199:3389
connected to 10.1.1.199:3389
```
and I see the remote window.

Is that normal?

**Comment by akallabeth** [comment]
yes. depends on the authentication mode. NLA requires authentication before connection, rdp and tls allow to connect first and authenticate later.
btw, you're using a deprecated command line syntax.

**Comment by mahmoodn** [comment]
Thank you. May I know what is the latest options and syntax?
