### ISSUE TITLE
BitBlt corrupted

### ISSUE THREAD

**Issue by openconcerto** [FreeRDP/FreeRDP#4944]
The display is corrupted since the latest patch related to order crash for BitBlt 
![xfreerdp](https://user-images.githubusercontent.com/1234263/47151165-4a3c4480-d2d9-11e8-8cba-49ad1ce61435.png)
 See #4925

The patch is not correct.
Server used : xrdp
Client : xfreerdp /relax-order

**Comment by akallabeth** [comment]
@openconcerto could you give a short description of how you configured `xrdp`?
I've been running various sessions with current `0.9.8` and different backends without much problems so far (`0.9.8` that is), might help to have the same setup to check against.

**Comment by akallabeth** [comment]
@openconcerto Checked against very old versions too (ubuntu 14.04 and debian wheezy), can not reproduce your issue. (configuration default from installation) so definitely need some more information about the server configuration

**Comment by openconcerto** [comment]
It's not related to the server but the way you "sanitized" the parameter of the blit with negative values.

If you prefer smoke testing instead of unit testing, here are the interesting parts of the xrdp.ini 
```
ini_version=1
bitmap_cache=yes
bitmap_compression=yes
allow_channels=true
max_bpp=16
fork=yes
new_cursors=yes
allow_multimon=true
use_fastpath=both
```

**Comment by akallabeth** [comment]
@openconcerto thx for the config, as for the tests, pull requests welcome.

**Comment by openconcerto** [comment]
@akallabeth I would be pleased to fix it, to write tests and to pull but I have no spare time yet. My daily job is software development and my employer is not convinced I should work for free during my day job.

**Comment by akallabeth** [comment]
@openconcerto Then you can understand why I'm not entirely convinced investing really a `LOT` of time figuring out the differences between spec and `xrdp` (and old ms servers for that matter) for parts of the protocol that are by all means legacy.

The pressing issue (memory corruption) is fixed and for everything else I will try to allocate time and fix it (but it is currently not the most important stuff on my list)
(btw, good luck writing a test for every order with all possible input combinations and every possible state the client can be in, that will take a lot of CPU to run through, if you manage to complete such an endeavor - I'd really welcome that but have found no proper way to get coverage to real worls scenarios - the base routines already have some test coverage)

So, to fix this regression with `xrdp`, some log snippets from the orders that are processed would help a lot in that regard (`BitBlt` is kind of a swiss army knife, does not tell much).

**Comment by bmiklautz** [comment]
@openconcerto could you please provide us a client debug log?
```
WLOG_LEVEL=DEBUG xfreerdp /relax-order-checks YOUROTHERPARAMETERS
```
In order to track your problem down could you also provide more information about your server side setup (we simply can't reproduce the issue easily aka at all):
* distribution
* xrdp version
* connection method (any brokers/gateways involved)?

**Comment by bmiklautz** [comment]
@openconcerto Thanks for your efforts.

As for "I don't understand why you stay focused on finding a server configuration to reproduce the issue". I do respect your opinion however we are trying to keep as close to the specifications as possible and we don't see this issue anywhere else (even not with the xrdp installation we tested with) except with your configuration/setup that's why we want to have a "smoke test" (as you like to call it). Once we know why it is that way, and see that is really a problem in the implementation we can do a proper fix (just adding a band aid fix to a possible wrong behavior isn't a proper fix imho ;)

**Comment by openconcerto** [comment]
Here is the addhoc patch which solves 100% of the display related issues I saw.  

```
case GDI_SRCCOPY :
                        if (!hdcSrc)
                                return FALSE;
                        hSrcBmp = (HGDI_BITMAP) hdcSrc->selectedObject;
                        hDstBmp = (HGDI_BITMAP) hdcDest->selectedObject;

                        if (!hSrcBmp || !hDstBmp)
                                return FALSE;

                        if(((int)nYSrc)<0){
                                nYSrc=0;
                                nHeight=nHeight+ ((int)nYSrc);
                        }
                        if(((int)nXSrc)<0){
                                nXSrc=0;
                                nWidth=nWidth+ ((int)nXSrc);
                        }
                        if( hSrcBmp->width< ((int)nXSrc+(int)nWidth) ){
                               nXSrc=hSrcBmp->width-(int)nWidth;
                        }
                        if( hSrcBmp->height < ((int)nYSrc+(int)nHeight) ) {
                                nYSrc=hSrcBmp->height-(int)nHeight;
                        }
                        
                        if(((int)nHeight)>0 && ((int)nWidth)>0){
                                if (!freerdp_image_copy(hDstBmp->data, hDstBmp->format, hDstBmp->scanline,
                                                nXDest, nYDest, nWidth, nHeight,
                                                hSrcBmp->data, hSrcBmp->format, hSrcBmp->scanline, nXSrc, nYSrc, palette, FREERDP_FLIP_NONE))
                                return FALSE;
                        }
```

Of course, I removed the `freerdp_primary_adjust_rect` and `freerdp_adjust_point` from core/order.c

I would be please to know how you can validate fixes without having tests for them.
"it works here, I promise" is bad pratice and lead to huge long term issues, AFAIK FreeRDP has a long story with random crash and security issues related to the lack of testing.

Anyway, you have now the fix to make it works better with xrdp. I agree that xrdp is not perfect, but it's not an excuse to provide an rdp client which misbehaves when the MS Remote Desktop runs just fine.

Feel free or not to correct other orders handling and write tests for them. 
I cannot spend more time on this for free.

**Comment by openconcerto** [comment]
Nice to see UINT32 are gone, are you working on clipping?

**Comment by akallabeth** [comment]
@openconcerto Currently not, got other stuff with more priority.

**Comment by openconcerto** [comment]
the issue is fixed
