### ISSUE TITLE
Keys being "stuck" when switching desktops

### ISSUE THREAD

**Issue by StewPedassle** [FreeRDP/FreeRDP#4966]
Hi All,

I'm rather inexperienced when it comes to reporting/tracing bugs, so please bear with me (feel free to treat me like a toddler when it comes to making/fetching logs etc.)

I've found a bug or two on my machine.  I am submitting these both under one because they appear to be intertwined behaviors.  

First unexpected behavior: I can switch workspaces while xfreerdp is active using only "Lctrl+alt+[U/D]" (i.e., I don't have to hit my escape key -- Rctrl).  Of course, the expected behavior is for xfreerdp/windows to do nothing with this combination unless I hit Rctrl before. 

Second unexpected behavior: switching workspaces back to xfreerdp's workspace with "Lctrl+alt+[U/D]" will cause xfreerdp to capture certain keys.  E.g., "c" is non-functional and "enter" alone will toggle fullscreen of xfreerdp until xfreerdp receives either a Rctrl or an enter.  Again, expected behavior is obvious.

** Additional Context ** 
- This behavior does not occur when switching back to the workspace using other means to navigate (e.g., Super+home or Super + mouse to select workspace)
- After switching, hitting "enter" alone will behave like "ctrl+alt+enter" (toggle fullscreen).  This will happen only once.  It will not happen if I have hit enter or Rctrl after switching.
- After switching, I will lose all use of the "c" key without losing any other character keys.  This is remedied once I hit Rctrl or enter.
- The on-screen keyboard on the remote machine does not indicate anything is being activated until I actually press keys (except "c" won't show actuation, of course).
- I don't know exactly what update caused this to happen.  I have been experiencing issues with copy/paste for a month or more (fixed with reboot of remote machine), and our IT service may or may not have updated our server recently (xfreerdp started displaying the computer name in a tab at the top without any changes to my login file)

** Application details **
* OS: Ubuntu 18.04.1 LTS
* Version of FreeRDP:  2.0.0-dev4 (d3c1db174)
* Command line used:  GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
* OS version connecting to: Windows 7
* output of `/buildconfig`:
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp-nightly-2.0.0+0~20181024014846.579~1.gbpd3c1db=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 7.3.0
Target architecture: x64

**Comment by akallabeth** [comment]
@StewPedassle 
* Were did you get the idea only the right control is escaped? Currently some `<ctrl>+<alt>` combos are allowed too. (Does some documentation need an update?)
* I can't reproduce this here (debian 9 and fedora 28 with various window managers). Might be some optional feature? (Lets compare command lines ;))

**Comment by nfedera** [comment]
I can't reproduce it either, please post your command line and tell us which window manager and/or desktop environment you're using.

**Comment by StewPedassle** [comment]
@akallabeth @nfedera 

> * Were did you get the idea only the right control is escaped? ... (Does some documentation need an update?)

I cannot recall exactly where I got it from.   It was likely some combination of Remmina's functioning, and forum discussions when I first started using FreeRDP.  I started RDP using Remmina, and switched to the nightlies a year or two ago when our admin set up an RD Gateway.  I haven't really had issues since then, so I haven't had to dive into documentation or further troubleshooting.

> command line and window manager / desktop.

I'm running vanilla Ubuntu.  The details are:
- OS: Ubuntu 18.04.1 LTS
- Architecture: 64-bit
- Manager: GNOME Shell 3.28.3


My command line is just an alias because I like to rely on the RDP file for the arguments.  Below is the command line, and I've attached an edited version of the RDP file.

`/opt/freerdp-nightly/bin/xfreerdp ~/Downloads/RDP\ testing/testing-comments.rdp

There's nothing out of order in the command line output, but let me know if there's some way to run a log and purge the identifying info.

[works-mein (copy).txt](https://github.com/FreeRDP/FreeRDP/files/2527520/works-mein.copy.txt)

**Comment by amosbird** [comment]
same issue in Archlinux and bspwm. "c" gets stuck

**Comment by amosbird** [comment]
commenting out this fixes it https://github.com/FreeRDP/FreeRDP/blob/master/client/X11/xf_keyboard.c#L145

**Comment by StewPedassle** [comment]
Thanks Amos, but I'm way too green to be effective at following your comments.  I tried over the holiday, but even that didn't give me enough time.

I have no idea where to start with editing and compiling the source code.  

I've also come to find that I have no clue how to properly install the release candidates.  Here's what I've managed to do so far:
-- I've downloaded and unpacked the tarballs for rc3 and rc4, and I think I'm supposed to follow the instructions on https://github.com/FreeRDP/FreeRDP/wiki/Compilation.  
-- I followed the instructions until the Debian apt-get command, but I cannot download two of the base dependencies (specifically libgstreamer0.10-dev and libgstreamer-plugins-base0.10-dev).  The closest things that I get from apt-cache search libgstreamer are libgstreamer1.0-dev and libgstreamer-plugins-base1.0-dev.  I presume from the similarity that 1.0 is meant instead of 0.10, but I'm too chicken to go away from explicit instructions.
--Also, I'm too scared to just move onto the rest of the instructions because it looks as though I may overwrite the nightly that I am currently using, but is imperative for me to be able to connect as my rdp connection isn't simply for convenience.

I'll try to respond more promptly in the future.

**Comment by akallabeth** [comment]
@StewPedassle Just use our nightlies https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds or follow the instructions to build a nightly package.

**Comment by samoring** [comment]
OS: opensuse 15.0.  The letter "c" stops working after a bit of use, the letter "a" get's changed to an "a-grave" eg., " à "...

Using "freerdp-2.0.0~rc4-lp150.2.3.1.x86_64"

Not sure how I'd go about doing diagnostic gathering, anyone have any suggestions?

**Comment by ibisis** [comment]
The "c" key doesn't work in full screen mode.  When I use CTL-ALT-ENTER to leave full screen mode, the "c" key works.

OS: FreeBSD 12.0-RELEASE-p3
desktop: MATE 1.20.3
vm: Windows 10 Pro 1809
freerdp: 2.0.0.r4_1
command: xfreerdp /monitors:0,1 /span "/u:xxx" /p:yyy  /v:192.168.0.26

**Comment by samoring** [comment]
I second this, my options:
/cert-ignore -sec-nla /multimon /sound /toggle-fullscreen +clipboard
+fonts +compression +heartbeat
