### ISSUE TITLE
xfreerdp Remote application,taskbar cannot display icon

### ISSUE THREAD

**Issue by wwcy** [FreeRDP/FreeRDP#4981]
Who can help me, I do not know whether I set parameters or not.Please look at the next picture.

![s](https://user-images.githubusercontent.com/31535843/47978023-49d3e400-e0f6-11e8-8810-9979003fc9df.png)
No icon for this application is displayed.

**Comment by bmiklautz** [comment]
Can you please provide more information? The issue doesn't say much...
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
