### ISSUE TITLE
Remote application icon display error

### ISSUE THREAD

**Issue by wwcy** [FreeRDP/FreeRDP#4984]
Hi,
 
   The taskbar of Ubuntu 18.04 can not display the icon of the Windows application.

Summary:
  
  1. The client is Ubuntu 18.04 and runs in VirtualBox.
  2. RDP host is Windows Server 2008 R2 x64.
  3. Internet Explorer is published as a RemoteApp (It is displayed on the Ubuntu taskbar, but the icon is wrong).
  4. The FreeRDP client was compiled on clean install of Ubuntu 18.04 from GitHub master.
`This is FreeRDP version 2.0.0-dev (git n/a)`
  5. Command line parameters.
`xfreerdp /u:user /p:pwd /cert-ignore /v:192.168.90.11 /app:"iexplore" /app-name:"IE" /app-icon:"C:\\icon.png"`

Taskbar Error Icon instance.
![ss](https://user-images.githubusercontent.com/31535843/48039845-a34d1900-e1b1-11e8-9331-0e02557eb90a.png)

**Comment by ilammy** [comment]
Some pointers for developers trying to implement this:

- xfreerdp receives application icon orders from the server, but [they are stubbed out at the moment](https://github.com/FreeRDP/FreeRDP/blob/cf43406dc30258bb0c3736bce07ce0ac4366ca26/client/X11/xf_rail.c#L534-L599) and do nothing.
- X11 property for window icons is called [_NET_WM_ICON](https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html), it contains an array of ARGB bitmaps.
- Older versions of Unity and GNOME tend to disregard _NET_WM_ICON and use static icons defined in *.desktop files, but with GNOME 3 the situation may have improved.

**Comment by wwcy** [comment]
@ilammy Thank you for your help.

**Comment by ilammy** [comment]
I've managed to get the icon display more or less working. I was also able to reproduce the issue with application name: Ubuntu 18.04 shows `RAIL:01234567` while Ubuntu 14.04 shows the correct name. Please stand by for a pull request.

The `/app-name` and `/app-icon` command-line arguments seem to be ignored as of now. I did not dig into git blame too deeply, but I kinda doubt that they ever worked. Can anybody explain their intent? Placeholders for the case when the server does not send us a name or an icon?

**Comment by ilammy** [comment]
@wwcy, here you go: #5003. Could you please test that PR in your environment?

**Comment by wwcy** [comment]
@ilammy The icon has already been displayed. The name is still wrong.
![image](https://user-images.githubusercontent.com/31535843/48387191-bd49a700-e72f-11e8-82dd-56d836dc8462.png)
Is it because of this code?
![image](https://user-images.githubusercontent.com/31535843/48387329-5bd60800-e730-11e8-9bcf-3cb025168a1d.png)

**Comment by akallabeth** [comment]
@wwcy can not reproduce your issue, which os and window manager are you using? (ubuntu 18.04 defaults as mentioned initially?)

**Comment by akallabeth** [comment]
@wwcy Also check the server settings, from my tests with #5003 the name is set by RDP, but only if the server sends a name.

**Comment by wwcy** [comment]
@akallabeth 1.The client is Ubuntu 18.04 and runs in VirtualBox.
                     2.RDP host is Windows Server 2008 R2 x64.
                     3.Command line parameters.
                      `xfreerdp /u:Administrator /p:vesystem123! /v:192.168.50.160 /port:3389 /app:"iexplore"`

**Comment by akallabeth** [comment]
Pull merged, remaining issue is mentioned in the comments there, case of a WM bug
