### ISSUE TITLE
Remote Assistance asks for credentials and does not connect

### ISSUE THREAD

**Issue by fodinabor** [FreeRDP/FreeRDP#4987]
FreeRDP does not connect when using Remote Assistance feature, but instead asks for NLA credentials.

**To Reproduce**
1. Generate a Remote Support Invitation from the windows control center
2. Send this file to another computer
3. Try to connect by using wfreerdp.exe invitation.msrcIncident /assistance:<Password>
4. NLA asks for credentials

**Expected behavior**
FreeRDP should connect to my other machine to provide Remote Support.

**Screenshots**
Instead of connecting I am asked for credentials:
![image](https://user-images.githubusercontent.com/5982050/48077201-1de45b80-e1e7-11e8-9f32-b6029e507dfd.png)

**Application details**
* Version of FreeRDP: Myrtille's latest and also latest nightly (2.0.0-dev4)
* Command line used: wfreerdp.exe invitation.msrcIncident /assistance:xxx
* OS version connecting to: Win 10 64bit (currently local network)
* `/log-level:trace`: where do I find the resulting log?
* `/buildinfo`:
```
This is FreeRDP version 2.0.0-dev4 (2fe2bc35f)                                                                          
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_FAAC=OFF WITH_FAAD2=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_X264=OFF                                                                                   
Build type:          Release                                                                                            
CFLAGS:              /DWIN32 /D_WINDOWS  /Gd /W3 -DWINPR_DLL                                                            
Compiler:            MSVC, 19.12.25834.0                                                                                
Target architecture: x86
```

**Desktop:**
 - OS: Windows 10 64bit

**Additional context**
We want to use this with a customized Myrtille version, to provide remote support from the web.

**Comment by akallabeth** [comment]
Just verified, there seem to be indeed 2 issues with remote assistance:
1. The one you described above (looks like a broken username / password initialization from the `msrcIncident` file)
1. The newer format for windows vista and newer with encrypted data in `LHTICKET` is not supported

**Comment by fodinabor** [comment]
The decryption code for number 2 seems to be there though... LHTicket is just not used anywhere: https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/common/assistance.c#L653

**Comment by akallabeth** [comment]
@fodinabor thx for the hint, I'll have a look at it.
