### ISSUE TITLE
Can't connect to remoteapp with error RAIL_EXEC_E_SESSION_LOCKED

### ISSUE THREAD

**Issue by MurzNN** [FreeRDP/FreeRDP#4990]
When I try connect to Windows 10 remoteapp from Linux using this cli agruments:
```
xfreerdp -u murz -p [censored] --app --plugin rail --data "cmd"  -- 192.168.1.3
```
I got the error:
```
-p ****** -> /p:******
-u murz -> /u:murz
--app -> /app + program name or alias
192.168.1.3 -> /v:192.168.1.3
loading channel rail
connected to 192.168.1.3:3389
connected to 192.168.1.3:3389
connected to 192.168.1.3:3389
Unable to get current timezone rule
RAIL exec error: execResult=RAIL_EXEC_E_SESSION_LOCKED NtError=0x15
```
On Windows using same credentials and command name - I connects normally. 

When I remove `--app` argument - I succesfully connects to full RDP session (full desktop).

FreeRDP version is 1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1 on Ubuntu 18.10 system.

Maybe I need to set some additional arguments to xrdp for solve this problem?

**Comment by MurzNN** [comment]
@akallabeth sorry, I add additional info to first post.

**Comment by MurzNN** [comment]
If I convert `--data "cmd"` to `--data "||cmd"` - this error is disappear, I see that new X window created on short time, but after this - window disappear with no output to console.

**Comment by akallabeth** [comment]
@MurzNN Ok, from what I see you should
* do what the log messages suggest (use the new command line syntax)
* Check your windows machine is configured appropriately (you need to `ALLOW` each single application and user!)
* check if it works with a newer version (be aware, there are currently some issues on master, but 2.0-rc tags work)

If you need further support, please use our mailing list or IRC channel.

**Comment by MurzNN** [comment]
Thanks, seems this issue is solved via adding `||` to app string, about nothing showed I'll try to debug and if will not solve - post new separate issue for investigate.
