### ISSUE TITLE
Copy/paste issue under MAC RDP

### ISSUE THREAD

**Issue by qiandahao** [FreeRDP/FreeRDP#4995]
When I do copy/paste under mac RDP version (not the Prebuilt version), the last character of the copied content is missing. Did anyone get the same issue?

**Comment by hardening** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by qiandahao** [comment]
My question is "Did u guys have this issue?". So you can give it a try and probably it takes 3 seconds. Then let me know if I posted a stupid issue. All I have to say about your comment is "Does it take 3 seconds to find and copy this link?" But w/e I am gonna collect more info to post here for u time saver.

**Comment by qiandahao** [comment]
* a useful description of the bug: Copy/paste is not working functionally (Basically it's a clipboard issue)
  * the steps to reproduce the bug: 1) Copy a paragraph (like "Hello World") inside or outside the rdp 2) Paste the content inside the rdp 3) The last character is missing (so it shows "Hello Worl", 'd' is missing)
  * to what system did you connect to?: win10
  * freerdp version: FREERDP_VERSION=2.0.0-dev4
  * freerdp configuration (e.g. xfreerdp --buildconfig)
  * operating System: macOS High Sierra 10.13.6
  * if you built it yourself add some notes which branch you have used, also your cmake parameters can help: cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" . && make

**Comment by akallabeth** [comment]
@qiandahao sorry, took me some time, but checked on my available mac. (also 10.13.6) seems like you found a really interesting one. As for the comment from @hardening I assume it was due to you not specifying which client you're using (you can also use `xfreerdp` on mac ;))

**Comment by qiandahao** [comment]
@akallabeth  Really appreciate it!
