### ISSUE TITLE
The latest version build from master branch doesn't work on the mac mojave

### ISSUE THREAD

**Issue by vjeson** [FreeRDP/FreeRDP#5004]
The latest version build from master branch doesn't work on the mac mojave (10.14) 
when connected to win10 , the screen is black.
build with command : cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" . && make
call cmd: ./MacFreeRDP /cert-ignore /v:192.168.102.199 /u:test /p:123456 /w:1024 /h:800

![1542110434771](https://user-images.githubusercontent.com/2101082/48412287-315f6b80-e77f-11e8-8781-880ae0030c38.jpg)

**Comment by akallabeth** [comment]
could you add a little more information about your build?
This can be anything from a configuration issue to a broken build...

**Comment by vjeson** [comment]
No special configuration，I build on mac 10.14, With the build running on 10.13 is right

**Comment by betterjason365** [comment]
I meet the same problem on mac. 
client system version 10.14.1. 
rdp system version winserver 2016 datacenter.

![image](https://user-images.githubusercontent.com/45125292/48662337-c33ae180-eabb-11e8-91bb-f7550a3d6423.png)

After connected, i type the keyboard,  i login in the win server 2016, i can see what i just typed.
But the screen is black

**Comment by betterjason365** [comment]
freerdp version is master version

**Comment by qiandahao** [comment]
@akallabeth Any progress? I got the same issue. Thank you!
