### ISSUE TITLE
/client-hostname doesn't appear to do anything.

### ISSUE THREAD

**Issue by nonamebrand06** [FreeRDP/FreeRDP#5007]
/client-hostname argument doesn't appear to do anything.   Regardless of what I configure the Workstation name that appears in logs is the system hostname.  

Current workaround is to launch FreeRDP in a UTS namespace.

OS: Debian
Version:2.0.0-rc2

**Comment by bmiklautz** [comment]
@nonamebrand06 can you please give more information on your problem? 
The argument does what it is supposed to do. To verify:
1. connect to a windows machine (I've tested with windows 10) with /client-hostname: set
1. start a cmd
1. echo %CLIENTNAME%
1. you will see the client name you have set

You can also see this when using the task manager: "Users" Tab (possibly you need to show the "Client Name" column).

One thing: if you reconnect (so you haven't logged out) you need to close the cmd and open a new one to get the new client name. This also applies to applications that don't use the windows side API to  retrieve the client hostname.

**Comment by nonamebrand06** [comment]
@bmiklautz 
%CLIENTNAME% shows to configured hostname like it should.
Task manager also shows the client name correctly.
I didn't know to look there so I didn't see those two locations.

Where I'm seeing the incorrect client hostname is in the security logs.  EventID 4624 under workstation name.  The incorrect hostname is being sent somewhere and that's what is registering in the audit logs.  This is on Server 2016.

This might be expected behavior, I was just expecting the host name to change for the whole connection with the /client-hostname argument.

**Comment by hardening** [comment]
@nonamebrand06 I've looked at the calls to `GetComputerNameA` and the 'real' hostname may come from the fact that the connection is done with NLA and NTLM, can you confirm that ?

**Comment by nonamebrand06** [comment]
Yes, NLA and NTLM authentication.

**Comment by akallabeth** [comment]
@nonamebrand06 As the command line does what it is supposed to do I'll close this issue.
If you have questions regarding your use case please use the mailing list or join us in our IRC channel.

**Comment by hardening** [comment]
Reopening as I found that with NLA + NTLM

![getcomputernameexa](https://user-images.githubusercontent.com/3237998/48778891-aa5a4800-ecd6-11e8-832f-456dc37d7442.png)

**Comment by hardening** [comment]
In this case the provided hostname is not used, but instead we use the one from the host.

**Comment by akallabeth** [comment]
@hardening Is this the desired behaviour?
The `%CLIENTNAME%` variable set during a RDP session is not relevant for authentication, but changing it there too might break it due to some policies.
Agree on that being a nice feature though.
