### ISSUE TITLE
Single Sign-On on TS Broker doesn't work

### ISSUE THREAD

**Issue by qcguytech** [FreeRDP/FreeRDP#501]
Hi folks,

I run FreeRDP 1.0.1 on HP ThinOS (Debian Lenny) and I'm  very close to deploy our new servers and one little thing is making me crazy.

We're using 3 Windows 2008 R2 Enterprise in a TS Farm with DNS Round-Robin, when I try to connect with my tests users they are required to enter the password a second if they are redirected to another server.

On Windows I have no problems at all with the latest client.

Thanks for your help

**Comment by Bottson** [comment]
Hello,

still the same problem. RDP Server is asking twice login. Freerdp 1.1.0-beta1.
Command is: xfreerdp --sec tls -v ip.adress.ip.address -u user.user@domain.tld 
I can connect correctly when leaving away --sec tls. But then it asks for my password in command line.
If its possible i wont let user enter their passwort on the command line. 

Is there any fix or possibility it runs without asking twice for login?

**Comment by akallabeth** [comment]
@Bottson Does it work with https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds?

**Comment by Bottson** [comment]
Hello akallabeth,

i am still trying to install the nightly build. I have to say that i am new to raspberry and all Linux based OS.

First i enter on terminal: sudo nano /etc/apt/sources.list
Than i add: deb http://pub.freerdp.com/repositories/deb/jessie/ freerdp-nightly main
Afterwards i enter on the terminal: wget -O - http://pub.freerdp.com/repositories/ADD6BF6D97CE5D8D.asc | sudo apt-key add -

and than i try to make a sudo apt-get update.

Error I am getting is:
W: Fehlschlag beim Holen von http://pub.freerdp.com/repositories/deb/jessie/dists/freerdp-nightly/InRelease  Erwarteter Eintrag »main/binary-armhf/Packages« konnte in Release-Datei nicht gefunden werden (falscher Eintrag in sources.list oder missgebildete Datei).

**Comment by akallabeth** [comment]
@Bottson There are no ARM builds available. You have to compile FreeRDP from source. Here is a starting point for doing that: https://github.com/FreeRDP/FreeRDP/wiki/Compilation

**Comment by Bottson** [comment]
Hello,
thank you for your help. I reached now to install the PreBuild.
When i make xfreerdp --version it shows: This is a freerdp version 2.0.0.-dev (git 5cae1d1)
When running: 
1. xfreerdp -v ip.adress -u username -d domain --sec tls there is still the same problem with double login.
2. xfreerdp -v ip.adress -u username -d domain --sec nla it asks my passwort in command line but not in rdp session.
3. xfreerdp -v ip.adress -u username -d domain --sec rdp same thing as with tls. Double login in rdp session.
4. xfreerdp -v ip.adress -u username -d domain Same thing as with --sec nla. Asks Password in command line, not in RDP Session. 

So i think there is no chance to get this run with login in terminal session?

Thank you all for your help. Very nice from all of you.

**Comment by akallabeth** [comment]
with latest master I can connect to a session broker setup with proper redirection login.
(sorry about the kerberos tag, actually not really part of this)
