### ISSUE TITLE
Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the   system variable OPENSSL_ROOT_DIR 

### ISSUE THREAD

**Issue by VenkateshPS** [FreeRDP/FreeRDP#5011]
**Found a bug? - We would like to help you and smash the bug away.**

Getting error when execute **cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode**
CMake Error at /usr/local/Cellar/cmake/3.12.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
**Describe the bug**

**To Reproduce**
Used  Mac book Pro.
1 ./scripts/OpenSSL-DownloadAndBuild.command 

2 cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode

running second step throws could not find OpenSSL error.

**Expected behavior**

**Screenshots**

** Application details
* Version of FreeRDP
* Command line used
* output of `/buildconfig`
* OS version connecting to
* If available the log output from a run with `/log-level:trace` 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

** Please remove this text before submitting your issue!

_Thank you for reporting a bug!_

**Comment by akallabeth** [comment]
`docs/README.ios`

**Comment by VenkateshPS** [comment]
I followed the document 

executed (./scripts/OpenSSL-DownloadAndBuild.command )below command which works fine but when i run **cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode** I get the error.

cmake version 3.12.4

**Comment by whatsdis** [comment]
why is this still closed? getting this issue
