### ISSUE TITLE
Can Free RDP be used to share screen from one  iOS device  to another 

### ISSUE THREAD

**Issue by VenkateshPS** [FreeRDP/FreeRDP#5014]
**Is your feature request related to a problem? Please describe.**
**Can Free RDP be used to share screen from one  iOS device  to another.
I want to integrate this in an existing App so that I can share my screen with other users using the same app.**
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
