### ISSUE TITLE
/log-level:OFF doesn't suppress all messages

### ISSUE THREAD

**Issue by ileGITimo** [FreeRDP/FreeRDP#5024]
If I run xfreerdp (on linux to windows) with "**/log-level:OFF**" I still get (at least) one [INFO] message (date/time tag removed):

    [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr

This comes from the line:

    WLog_INFO(TAG, "loading channelEx %s", name);

in _client/common/cmdline.c:freerdp_client_load_static_channel_addin_

I'm not sure I completely understand the reasoning for all the checks for FilterLevel and Level in    _WLog_GetLogLevel [winpr/libwinpr/utils/wlog/wlog.c]_ which currently reads:

    if (log->FilterLevel < 0)
      log->FilterLevel = WLog_GetFilterLogLevel(log);
    if ((log->FilterLevel >= 0) && (log->FilterLevel != WLOG_LEVEL_INHERIT))
      return log->FilterLevel;
    else if (log->Level == WLOG_LEVEL_INHERIT)
      log->Level = WLog_GetLogLevel(log->Parent);
    return log->Level;

What causes the spurious [INFO] message is this line

    else if (log->Level == WLOG_LEVEL_INHERIT)

(It is interesting that, if this check turns out to be true, the code unconditionally recurses on _log->Parent_ without checking for a NULL parent.  Maybe the "logic" would make that not happen, but ...)

As the message above arrives with _FilterLevel = 65535 = WLOG_LEVEL_INHERIT_ and a _Level = 2_
it is eventually printed.

Some other messages arrive at _WLog_GetLogLevel_ with both _FilterLevel_ and _Level_ set to _WLOG_LEVEL_INHERIT_,

I changed that line to be

      else if (log->FilterLevel == WLOG_LEVEL_INHERIT && log->Parent)

and the spurious [INFO] message goes away.

I can still set **/log-level** to other levels, like _DEBUG_ and get all those messages.  
Didn't check the behavior with any **/log-filters** options. 
 I'm also worried that on some cases one my actually need to check for _Level == WLOG_LEVEL_INHERIT_.

Can anyone familiar with winpr's log facility comment on this?

**Comment by akallabeth** [comment]
@ileGITimo Yes, this is currently a bug in the implementation.
The reason is the following:
1. To speed up logging every logger caches the log level in case it is `INHERIT` after it is first used
1. Command line parser comes after the first one or two messages
1. The loggers used will not be updated to the new logger settings

As a workaround for the time being use `WLOG_LEVEL=OFF xfreerdp /v:<url> ...`

**Comment by ileGITimo** [comment]
> As a workaround for the time being use `WLOG_LEVEL=OFF xfreerdp /v:<url> ...`

This works (and it doesn't add to the noise  in my xsession error log).  I'll sync and test once this is merged in.  Thanks!
