### ISSUE TITLE
Exiting Full Screen Mode When Network Has Reliability Issues

### ISSUE THREAD

**Issue by fifothekid** [FreeRDP/FreeRDP#5028]
I'm building from the latest master version and everything is working perfectly. The only problem that I always have is that my connection has some reliability issues and it frequently suffers from delays and dropped connections. Unfortunately, when that happens while I'm in full screen mode it would stop accepting any commands, not even Ctrl+Shift+F works. This would force me to restart the computer!
I think that Ctrl + Shift + F should work regardless of the state of the connection, right?

**Comment by akallabeth** [comment]
The command to leave fullscreen mode is `ctrl + alt + enter` and works on current master. (In case of connectivity issues it might be handled with a short delay)
This is a freerdp internal key combination as it is similar to how virtualbox et al handle keyboard grabbing and therefore disable all window manager / system keybindings.

**Comment by fifothekid** [comment]
I meant to say Ctrl + Alt + Enter sorry
When I have network problems and timouts the application just hangs and I cannot exit full screen
