### ISSUE TITLE
Not able to use Display Variable with freerdp

### ISSUE THREAD

**Issue by nkv16786** [FreeRDP/FreeRDP#5034]
Hi,

I have two containers, one is vnc container and other is simple centos container.

When i install freerdp in vnc container n execute freerdp command it is successfull.

Now i wanted to invoke this rdp session from centos container, as it doesn`t have gui i am not able to.

So, i found out that using DISPLAY variable i can divert freerdp session to vnc container.

So i ran the following commands inside centos container,
```
export DISPLAY=10.x.x.x:0.0
xfreerdp /v:10.x.x.x /u:xxxxxx /p:xxxxxxx

```
But i am getting the following error,

```
xf_pre_connect: failed to open display: 10.x.x.x:0.0
Please check that the $DISPLAY environment variable is properly set.
freerdp_pre_connect failed
```

Note:-  I have tried 10.x.x.x:0.1 as well but same result.

So, what exactly needs to be done for using this DISPLAY variable , like what port needs to be opened,etc.

Thanks.

**Comment by akallabeth** [comment]
Please do not misuse the issue tracker for support questions.
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

As for using X11 application questions additionally please consult some X11 help resource.

For your specific question, just as the error message suggests, something in your setup is broken. `xfreerdp` respects the variable, using it here without issues.
