### ISSUE TITLE
Freerdp-2.0.0-rc4 keyboard extra key mapping to remote server (audio keys)

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#5044]
Client OS :- Xubuntu-12.04_x86
Server OS :- Windows 8.1_x64

Commandline:-
xfreerdp /cert-ignore -toggle-fullscreen /title:TestClient /bpp:32 /f /sound:sys:pulse +compression /network:lan /kbd:0x00000409 +auto-reconnect /d:xyz /u:"xxx" /p:xxxx /v:x.x.x.x /gdi:hw +auto-reconnect /auto-reconnect-max-retries:0 /gfx

Logs:-
[12:23:02:427] [10011:10012] [ERROR][com.freerdp.client.x11] - Unknown key with X keycode 0xae
[12:23:02:555] [10011:10012] [ERROR][com.freerdp.client.x11] - Unknown key with X keycode 0xae

**Comment by akallabeth** [comment]
Might have to do with your command line forcing `/kbd:0x00000409`
Does it work without that one?

**Comment by gnshkl1** [comment]
@akallabeth not working without /kbd option also

**Comment by akallabeth** [comment]
@gnshkl1 working here, so it might be your X11 configuration. Check `xev` and which key is reported when you press the keys

**Comment by gnshkl1** [comment]
@akallabeth its working with ubuntu 16.04 may be some configuration issue with ubuntu 12.04 xorg.
closing same for now
