### ISSUE TITLE
Installing FreeRDP and hit to make install error: field ‘des3_ctx’ has incomplete type

### ISSUE THREAD

**Issue by harigist** [FreeRDP/FreeRDP#5050]
I was trying to install FreeRDP server using the link : https://github.com/FreeRDP/Remmina/wiki/Compile-on-Ubuntu-16.04

I hit to the below error during 

> `make && sudo make install`

    [ 25%] Building C object libfreerdp-codec/CMakeFiles/freerdp-codec.dir/nsc.c.o
    [ 26%] Building C object libfreerdp-codec/CMakeFiles/freerdp-codec.dir/rfx_sse2.c.o
    [ 26%] Linking C shared library libfreerdp-codec.so
    [ 26%] Built target freerdp-codec
    Scanning dependencies of target freerdp-core
    [ 27%] Building C object libfreerdp-core/CMakeFiles/freerdp-core.dir/activation.c.o
    In file included from /home/hari/openuds/freerdp/FreeRDP-1.0.2/libfreerdp-core/tls.h:23:0,
                     from /home/hari/openuds/freerdp/FreeRDP-1.0.2/libfreerdp-core/transport.h:33,
                     from /home/hari/openuds/freerdp/FreeRDP-1.0.2/libfreerdp-core/mcs.h:24,
                     from /home/hari/openuds/freerdp/FreeRDP-1.0.2/libfreerdp-core/rdp.h:23,
                     from /home/hari/openuds/freerdp/FreeRDP-1.0.2/libfreerdp-core/activation.h:23,
                     from /home/hari/openuds/freerdp/FreeRDP-1.0.2/libfreerdp-core/activation.c:20:
    /home/hari/openuds/freerdp/FreeRDP-1.0.2/libfreerdp-core/crypto.h:67:17: error: field ‘des3_ctx’ has incomplete type
      EVP_CIPHER_CTX des3_ctx;
                     ^~~~~~~~
    /home/hari/openuds/freerdp/FreeRDP-1.0.2/libfreerdp-core/crypto.h:72:11: error: field ‘hmac_ctx’ has incomplete type
      HMAC_CTX hmac_ctx;
               ^~~~~~~~
    libfreerdp-core/CMakeFiles/freerdp-core.dir/build.make:62: recipe for target 'libfreerdp-core/CMakeFiles/freerdp-core.dir/activation.c.o' failed
    make[2]: *** [libfreerdp-core/CMakeFiles/freerdp-core.dir/activation.c.o] Error 1
    CMakeFiles/Makefile2:494: recipe for target 'libfreerdp-core/CMakeFiles/freerdp-core.dir/all' failed
    make[1]: *** [libfreerdp-core/CMakeFiles/freerdp-core.dir/all] Error 2
    Makefile:151: recipe for target 'all' failed
    make: *** [all] Error 2

Could you please help me to resolve this issue?

Thanks,
Harry

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/Compilation

Try the nightly package instructions first, it will complain about the dependencies missing.

**Comment by akallabeth** [comment]
Oh, btw, 1.0 is old, with that you better just use the provided packages from ubuntu.

**Comment by harigist** [comment]
Hi @akallabeth,

I installed the package as per this link https://github.com/FreeRDP/FreeRDP/wiki/Compilation

after successful installation

> cmake --build . --target install

I see an error performing following,

hari@hari-virtual-machine: /openuds/freerdp/FreeRDP$ which xfreerdp
/usr/local/bin/xfreerdp
hari@hari-virtual-machine: /openuds/freerdp/FreeRDP$ xfreerdp /buildconfig
**[16:05:12:862] [16468:16468] [ERROR][com.freerdp.client.x11] - failed to open display: 
[16:05:12:862] [16468:16468] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.**
hari@hari-virtual-machine:~/openuds/freerdp/FreeRDP$ 

Am I missing something?

**Comment by akallabeth** [comment]
you must run the client in a `X11` environment of course.
For further support questions please use the mailing list or our IRC channel.
