### ISSUE TITLE
How to connect windows IRDPSRAPISharingSession by wfreerdp-client.exe

### ISSUE THREAD

**Issue by aijyo** [FreeRDP/FreeRDP#5079]
Just as the title:
I'm now created a IRDPSRAPISharingSession listen on port(i.e 3389) with a invatation created as follow image:

![image](https://user-images.githubusercontent.com/7956449/49211471-9a3f1880-f3fa-11e8-85b1-71e620164f25.png)

Can anyone tell how to connect the invatation with twfreerdp-client.exe

![image](https://user-images.githubusercontent.com/7956449/49211524-ba6ed780-f3fa-11e8-88ae-a45b0710c36a.png)

**Comment by akallabeth** [comment]
@aijyo I'm not too familiar with that, but is it the same as the `.msrcIncident` files created for remote support? Then just use these as first argument to `wfreerdp.exe`

**Comment by aijyo** [comment]
It seems effective, but how...can  provide with a msrcIncident file and full command?...

**Comment by akallabeth** [comment]
@aijyo Well, how is the workflow for this API? Do you connect with user/password, can you create some kind of invitation file?
Would suggest you write to the mailing list or join us on IRC to discuss this ;)

**Comment by aijyo** [comment]
> @aijyo Well, how is the workflow for this API? Do you connect with user/password, can you create some kind of invitation file?
> Would suggest you write to the mailing list or join us on IRC to discuss this ;)

I'll learn how join IRC later...(not family with it)...
IRDPSRAPISharingSession work flow as follow(only connect string is needed when connect to server):

Init:
![image](https://user-images.githubusercontent.com/7956449/49213602-9c57a600-f3ff-11e8-931b-5f28e7aa4a15.png)

SetParam:
![image](https://user-images.githubusercontent.com/7956449/49213652-b8f3de00-f3ff-11e8-95bd-2a3961ab9585.png)

open:
![image](https://user-images.githubusercontent.com/7956449/49213698-d0cb6200-f3ff-11e8-962a-b3977d171883.png)


create a invatation:
![image](https://user-images.githubusercontent.com/7956449/49213735-e8a2e600-f3ff-11e8-8027-1b4425902c47.png)


client side(connecte to the server, username, passwd is not necessary, can be any string,) :
![image](https://user-images.githubusercontent.com/7956449/49213794-0bcd9580-f400-11e8-85b5-792f177d8d5c.png)

**Comment by aijyo** [comment]
> @aijyo Well, how is the workflow for this API? Do you connect with user/password, can you create some kind of invitation file?
> Would suggest you write to the mailing list or join us on IRC to discuss this ;)

I use freerdp to connect IRDPSRAPISharingSession is because I find freerdp use it on windows(int win_wds.c::int win_shadow_wds_init(winShadowSubsystem* subsystem)). So I think is possible  use freerdp client connect to my RDPSession...

**Comment by akallabeth** [comment]
@aijyo Ah, so how does this string look like? Is it simply some RDP file format or what? (sorry, as already said, not familiar with that one)

**Comment by aijyo** [comment]
> @aijyo Ah, so how does this string look like? Is it simply some RDP file format or what? (sorry, as already said, not familiar with that one)
when a create a invatation:
![image](https://user-images.githubusercontent.com/7956449/49218250-ec883580-f40a-11e8-985b-b700995dcffb.png)

connectstring as follow(some info relpaced by "**"):
<E><A KH="rNOdFflS6iHJn8KIM63ZXWGufhA=" KH2="sha256:/8PRsXHTSTSVmGsC/fr1jWfcX9ATvHAdkNy59vKsO0A=" ID="Trial"/><C><T ID="1" SID="0"><L P="9792" N="f**::e**0:2**a:3**8:4**9%3"/><L P="9793" N="f**0::1**b:d**8:5**0:a**5%6"/><L P="9794" N="2**1:0:9**8:6**8:1**b:d**8:5**0:a**5"/><L P="9795" N="1**.1**.**0.1**"/><L P="26697" N="1**.1**.1**.2**"/></T></C></E>

**Comment by akallabeth** [comment]
@aijyo And where is the `STRING`? You just call an API here, where is the output?

**Comment by aijyo** [comment]
> @aijyo And where is the `STRING`? You just call an API here, where is the output?
github bug..connot show the following string:
![image](https://user-images.githubusercontent.com/7956449/49218483-7afcb700-f40b-11e8-9a8f-c016af420347.png)

![image](https://user-images.githubusercontent.com/7956449/49218459-70422200-f40b-11e8-82a4-5a2dd61221ab.png)

**Comment by aijyo** [comment]
> @aijyo And where is the `STRING`? You just call an API here, where is the output?
full demo code as follow, I using outputdebugstring got the  connectionstring 
![image](https://user-images.githubusercontent.com/7956449/49218524-95369500-f40b-11e8-9dd7-a5a0f91d9908.png)

**Comment by akallabeth** [comment]
@aijyo Ok, this is the assistance file format. Just save that invitation to a file and use it as first argument `wfreerdp.exe filename.msrcIncident` and it should work.

**Comment by aijyo** [comment]
> @aijyo Ok, this is the assistance file format. Just save that invitation to a file and use it as first argument `wfreerdp.exe filename.msrcIncident` and it should work.

I find the assitance file parse function now: the connectstring seems not match the msrcIncident...
![image](https://user-images.githubusercontent.com/7956449/49264272-92c65080-f488-11e8-96ec-ab743eed7606.png)

So  how to join the group with IRC

**Comment by aijyo** [comment]
> > @aijyo Ok, this is the assistance file format. Just save that invitation to a file and use it as first argument `wfreerdp.exe filename.msrcIncident` and it should work.
> 
> Thanks, I'll test it tomorrow, and learn how to use IRC..

I'm now find a function that trans connectstring to assistance file struct in assistance.c, but some key value  seems to be ignored...(KH2, CE):
![image](https://user-images.githubusercontent.com/7956449/49275462-51e53080-f4b6-11e8-9614-ce4dcfda85db.png)

**Comment by aijyo** [comment]
> freerdp
@akallabeth  Thank you very much...
And more  there is question(https://github.com/FreeRDP/FreeRDP/issues/5089), what I realy anxious to know is : wfreerdp-server-cli.exe is workable？
