### ISSUE TITLE
Freerdp-2.0.0-rc4 dynamic-resolution window border disappear issue

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#5086]
Freerdp version : 2.0.0.rc4
Client OS :- Xubuntu-16.04_x86
Server OS :- Windows 10

xfreerdp /cert-ignore  /title:test  /bpp:32  -wallpaper   -bitmap-cache  -themes    -floatbar  /dynamic-resolution        /gdi:sw   /kbd:0x00000409   /d:test /u:"abc" /v:x.x.x.x   /p:xxx +toggle-fullscreen /f

Steps:-
1:-take session with above command
2:-ALT+CTL+ENTER (2 times) (do not resize)

Result :- 
1:- window border disappear (so cannot resize session)

It should be unmaximize in first ALT+CTL+ENTER

**Comment by akallabeth** [comment]
Please add additional information, can not be reproduced with the steps provided.

**Comment by gnshkl1** [comment]
@akallabeth windows frame border is hidden ,so not able to resize window frame .
what additional details required.

**Comment by akallabeth** [comment]
Since your response only occured in my mailbox:
I can not reproduce the issue with the steps you provided. Fullscreen toggling works just as expected. Please provide a more detailed description of your setup to reproduce.

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
