### ISSUE TITLE
Freerdp-2.0.0-rc4 /orientation not working

### ISSUE THREAD

**Issue by gnshkl1** [FreeRDP/FreeRDP#5088]
Freerdp version : 2.0.0.rc4
Client OS :- Xubuntu-16.04_x86
Server OS :- Windows 10

xfreerdp /cert-ignore /title:test /bpp:32 -wallpaper -bitmap-cache -themes -floatbar /dynamic-resolution /gdi:sw /kbd:0x00000409 /d:test /u:"abc" /v:x.x.x.x /p:xxx +toggle-fullscreen /f /orientation:270

**Comment by akallabeth** [comment]
User error. The capability in `[MS-RDPBCGR] 2.2.1.3.2 Client Core Data (TS_UD_CS_CORE)` is correctly sent, configure your server.
