### ISSUE TITLE
[assistance] unsupported options KH2 and others

### ISSUE THREAD

**Issue by aijyo** [FreeRDP/FreeRDP#5089]
Just as the title, I have try to shared my windows client as a server, and connnect and view it on some linux device, but when I run wfreerdp-client.exe and try to connect to the freerdp-shadow-cli.exe  something went wrong...(I'll show the error later, what is not my concern now).

I have already read a part of  "freerdp-shadow-cli" code , and found it implement with IRDPSession by convert IRDPSession connectstring to msrcIncident file.  

When I use wfreerdp-client.exe connect to a windows server with msrcIncident file, everything is okay.

When I use IRDPViewer connect to the freerdp-shadow-cli.exe server (use connectionstring that I hooked from the win_wds.c::int win_shadow_wds_init(winShadowSubsystem* subsystem)) everthing is okay.
![image](https://user-images.githubusercontent.com/7956449/49350546-58f48480-f6ea-11e8-8d38-696d76ab7c35.png)

**What I really concern  is : If it is possible to connect to the IRDPSession use freerdp-client  and if it is possible connect to the shared windows by connectionstring  created by IRDSession not only .msrcIncident  file or .rdp file...**

**So the problem that cannot be connected currently is simply because it has not been developed yet or because it cannot be supported at all...**

**Comment by aijyo** [comment]
server:
freerdp-shadow-cli.exe without any param;

client:
First attempt:
.\wfreerdp.exe -w:800 -h:600 /u:Shadow /p:Shadow123!  -v:172.16.60.76:3389
(I got some connection error or auth error)

Second attempt:
-w:800 -h:600 -v:172.16.60.76:40000
I found the IRDPSession portid has been set to 40000, so I wanna connect to it...
I got a login dialog,  **but username "Shadow" , passwd "Shadow123!" is wrong**, what I found in IRDPSession init code...  If is possible to connect, what's the username and what's the passwd... where I can found it...
![image](https://user-images.githubusercontent.com/7956449/49355826-471fdb00-f704-11e8-9e43-994fcf0802be.png)

**Comment by akallabeth** [comment]
@aijyo Looks like you're asking the wrong question here ;)
The `shadow` server is working as expected (and as you probably noticed due to the hard coded credentials is kind of a demo application)
What you're seeing here is a unsupported version of assistance string (or some missing headers).
Would check with `mstsc` as client first to ensure your assistance file is correct and the server up and running before trying to connect with freerdp here.
One problem at a time ;)

**Comment by aijyo** [comment]
> @aijyo Looks like you're asking the wrong question here ;)
> The `shadow` server is working as expected (and as you probably noticed due to the hard coded credentials is kind of a demo application)
> What you're seeing here is a unsupported version of assistance string (or some missing headers).
> Would check with `mstsc` as client first to ensure your assistance file is correct and the server up and running before trying to connect with freerdp here.
> One problem at a time ;)

I donnot konw how email U, so I comment here.
I find msra.exe is  implement by  IRDPSession( CoCreateInstance(9B78F0E6-3E05-4A5B-B2E8-E743A8956B65, ... )) , And find a class Named CRATicket, what used to generate msrcIncident file.

It seems that there is no direct interface to generate the msrcIncident file, which requires us to generate it ourselves through the connectionstring.

Because I am not familiar with the protocol (I will slowly become familiar with it), can you take the time to implement this function as soon as possible (I will try to achieve it during this time), I am grateful.

**Comment by aijyo** [comment]
> @aijyo Looks like you're asking the wrong question here ;)
> The `shadow` server is working as expected (and as you probably noticed due to the hard coded credentials is kind of a demo application)
> What you're seeing here is a unsupported version of assistance string (or some missing headers).
> Would check with `mstsc` as client first to ensure your assistance file is correct and the server up and running before trying to connect with freerdp here.
> One problem at a time ;)

I find we just need a function named freerdp_assistance_encrypt2 to encrypt connectinstring2 ,  which is the opposite function of freerdp_assistance_decrypt2. And then we can convert connectionstring2 to remote assistance file.
I have tried it, but it failed. I am not familiar with Openssl encryption and decryption...
I am currently trying various ways to solve this problem....including replying to you here.

**Comment by akallabeth** [comment]
@aijyo pull requests welcome, but please stop asking the same question all over the place.
This is kind of annoying and won't help your cause.

**Comment by aijyo** [comment]
> @aijyo pull requests welcome, but please stop asking the same question all over the place.
> This is kind of annoying and won't help your cause.

Thank you for your reply.
Can you take a moment to implement the encryption function? I think that after doing this, we  can connect using connectionstring...
