### ISSUE TITLE
File timestamps are incorrect when reading directory entries ("dir")

### ISSUE THREAD

**Issue by arlied-google** [FreeRDP/FreeRDP#5113]
When I use drive redirection, the "dir" command in Windows shows completely bogus file timestamps.

For example, when I run "dir" against a redirected drive, I get:

01/14/13651  11:21 PM    <DIR>          home
01/01/1601  12:00 AM    <DIR>          numa
01/23/4418  03:17 PM    <DIR>          Downloads
11/27/19458  08:47 PM    <DIR>          winddk-samples
01/01/1601  12:00 AM    <DIR>          pub
01/01/1601  12:00 AM    <DIR>          panic
12/11/26697  03:22 PM             1,363 NOTES.txt
01/01/1601  12:00 AM    <DIR>          Videos
01/01/1601  12:00 AM    <DIR>          bazel-bin
01/01/1601  12:00 AM    <DIR>          .
01/01/1601  12:00 AM    <DIR>          bazel-genfiles
02/20/19707  09:34 AM    <DIR>          Desktop

The 01/01/1601 timestamps are obviously 0, represented in FILETIME.  The rest are some other bogus values.

I tried looking up the code in FreeRDP which handles scanning directories, so I found channels/drive/client/drive_file.c. I added printf() calls inside the drive_file_query_directory() function, and printed the 64-bit FILETIME values. They looked quite reasonable.

So, somewhere after the point where the response to the "query directory information" is written to the output stream, things are getting corrupted. I haven't had a chance to dig deeper than that, though.

My server is running Windows Server 2016.  My client is a variant of Ubuntu. I just pulled (on December 6, 2018), rebuilt, and re-tested, and the problem is still happening.

To reproduce: 
1) Enable drive redirection:  xfreerdp ... /drive:h,$HOME
2) Log in
3) dir \\tsclient\h
4) See lots of files, but with bogus timestamps.

FreeRDP version is sync'd from Dec 6, 2018.  Output of xfreerdp /buildconfig:

This is FreeRDP version 2.0.0-dev5 (8c7f8eb39)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=OFF WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=OFF WITH_XKBFILE=ON WITH_XRANDR=OFF WITH_XRENDER=OFF WITH_XSHM=ON WITH_XV=OFF WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 7.3.0
Target architecture: x64

I tried running with /log-level:trace, but it didn't show any information relevant to drive redirection.

**Comment by akallabeth** [comment]
@arlied-google Indeed interesting, looking at the same location with explorer shows the correct timestamps :/

**Comment by arlied-google** [comment]
Thank you so much!  I pulled, built, and verified the fix, and it looks great.
