### ISSUE TITLE
Zoom-in/scale-up when remoting from HiDPI

### ISSUE THREAD

**Issue by markd89** [FreeRDP/FreeRDP#5114]
My machine that I sit at and remote **from** has a 3840x2160 display.

I'd like to RDP **to** a windows host using a window that is 1280x900  **but** have that window up-scaled so that each pixel uses 4 pixels on my HiDPI display. 

Put another way, if I run my display at 1920x1080 and connect to the windows host at 1280x900, everything is fine. I want to run my display at 3830x2160 and have that windows host window take up the same number of inches of screen.

I suspect that such a capability already exists, but I haven't found the magic combination of options yet.

I have tried /scale:200, scale-desktop:200 but these don't seem to do anything.

Any help with what I'm missing much appreciated!
Mark

**Comment by akallabeth** [comment]
/smart-scaling /size:1280x900
Please use IRC or the mailing list for support.

**Comment by chrisdone** [comment]
FWIW to anyone else trying to get xfreerdp working on high DPI, the suggested solution here doesn't work. Nor do any of the other suggested solutions on other issues. The screen remains tiny.

I tried out Remmina and it works out of the box.

**Comment by markd89** [comment]
This works for me:
/w:1280 /h:920  /smart-sizing

note not *smart-scaling* but *smart-sizing*

**Comment by volth** [comment]
> This works for me:
> /w:1280 /h:920 /smart-sizing
> 
> note not _smart-scaling_ but _smart-sizing_

But this scaling is blurry :(

**Comment by gnattu** [comment]
@volth use the `scale` switch if you want to have retina resolution
`/scale:180 /scale-desktop:200`  is my current flags and it works fine w/o smart-sizing

**Comment by volth** [comment]
@gnattu I fixed  that already https://github.com/FreeRDP/FreeRDP/pull/5595

**Comment by markd89** [comment]
Hi, is this fix in the nightly binaries?

Thanks!

**Comment by ProgrammerIn-wonderland** [comment]
> @volth use the `scale` switch if you want to have retina resolution `/scale:180 /scale-desktop:200` is my current flags and it works fine w/o smart-sizing

This works on my surface book (3000x2000) display really well!! thanks so much!!

For KRDC users you can simply add the flags to "Extra Options"
![image](https://user-images.githubusercontent.com/30693865/141600393-101386ad-9f13-49eb-835d-a80665d785c2.png)

**Comment by akallabeth** [comment]
@gfhdhytghd 
1. `/smart-sizing` and `/scale*` options are mutually exclusive (client side vs server side scaling)
2. `wlfreerdp` does not support remote app, only `xfreerdp` does at this point in time
3. you better start using the `3.0.0-rc0` version as remote app has been improved quite a bit since 2.0

**Comment by gfhdhytghd** [comment]
> @gfhdhytghd 
> 
> 1. `/smart-sizing` and `/scale*` options are mutually exclusive (client side vs server side scaling)
> 
> 2. `wlfreerdp` does not support remote app, only `xfreerdp` does at this point in time
> 
> 3. you better start using the `3.0.0-rc0` version as remote app has been improved quite a bit since 2.0

Mouse(Touchpad) doesn't work on freerdp3(either x or wl),and the smart sizing still look not good, so I won't use that instantly

**Comment by akallabeth** [comment]
@gfhdhytghd for scaling, just tested locally (`wlfreerdp`) it does what it is supposed to do.
(e.g. `/scale:180 /scale-device:180 /scale-desktop:200` will let the remote scale the UI to 2x)

> Mouse(Touchpad) doesn't work on freerdp3(either x or wl),and the smart sizing still look not good, so I won't use that instantly

`-v` please? never heard of such an issue, and I use `xfreerdp` daily

**Comment by paravz** [comment]
I have a 4k monitor scaled 150% on Linux client and wanted to see the same 150% scale while remoting into windows (since standalone windows also uses 150% display scale). This worked for me:
```
xfreerdp /dynamic-resolution /workarea /scale:140
```

**Comment by ivanjermakov** [comment]
`/scale` is limited to 1.5x and 2x scaling. `/scale-desktop` can be used to set fractional scale:

> /scale-desktop:percentage
>     Scaling factor for desktop applications (value between 100 and 500) (default:100)
