### ISSUE TITLE
Artifacts when connecting to windows 2003 server and width (/w:) is an odd value

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#5119]
Using xfreerdp (or remmina). Connecting to remote windows 2003 server with a non even resolution width (i.e.: /w:1025)

Here is the result:

![immagine](https://user-images.githubusercontent.com/5477803/49684954-9044a600-fadb-11e8-87f4-b7f420d6d511.png)

**Comment by akallabeth** [comment]
@giox069 Looks very much like a problem of server 2003 and input validation.
Getting the value back from the server but the image is distorted, so it is lying to us about the actual resolution.
Also not getting this issue with newer versions of windows (7 and up).
So, as we're currently very busy with getting the final 2.0 out (this time hopefully for real ;)) I'm setting this to wontfix, but if anyone is willing to dive into this pull requests are welcome.

**Comment by giox069** [comment]
Just to add some info: with an even width resolution there are still artifacts problems:

**Comment by giox069** [comment]
Just to add some info: with an even width resolution there are still artifacts problems:

![immagine](https://user-images.githubusercontent.com/5477803/57064846-e4893600-6cc7-11e9-94de-87643488191d.png)

The workaround is to set width as multiple of 4.

**Comment by giox069** [comment]
Never mind, I apologize. Problem disappeared after connecting one single time with a microsoft remote desktop client form windows 10. Some internal state of RDP server was not correctly setup/cleared by xfreerdp?

**Comment by akallabeth** [comment]
fyi: with `FreeRDP 3` this works (but keep away from `/gdi:hw` or `/cache:glyph`
