### ISSUE TITLE
Using /smart-sizing with dual monitor setup minimizes the xfreerdp screen to fit a single display instead of both

### ISSUE THREAD

**Issue by stilyan** [FreeRDP/FreeRDP#5129]
Initially found here, https://github.com/FreeRDP/FreeRDP/issues/5047#issuecomment-441166522 and reported separately per developer's recommendation.

Dual monitor setup, both 1680x1050
FreeRDP build from latest git source
Built like this
`cmake -GNinja -DCMAKE_INSTALL_PREFIX=/opt/freerdp -DWITH_DSP_FFMPEG=ON -DWITH_PULSE=ON
`
Running like this
`#!/bin/sh /opt/freerdp-nightly/bin/xfreerdp \ -window-drag \ -menu-anims \ -themes \ +fonts \ /bpp:32 \ /f \ /smart-sizing \ -decorations \ -compression \ /audio-mode:0 \ /mic:format:1 \ /sound:latency:50 \ /multimon \ -floatbar \ /v:$1 \ /u:$2 \ /p:$3`

FreeRDP is on Ubuntu 18.04.1 LTS with default desktop env - gnome , version .. idk which package to look for, but versions 3.28.1 and 3.28.3 are dominating in output from `dpkg --list |grep gnome`
Remote VM is Windows Server 2016.

**The issue**
/smart-sizing works as expected on single monitor setups
Using smart-sizing with dual monitor setups however minimizes the RDP screen to fit a single display instead of both displays when smart-sizing is not used.

**Comment by akallabeth** [comment]
@stilyan Can not reproduce, but maybe we're talking about different things:
* I can start in dual monitor fullscreen, ok that is expected
* I can leave fullscreen, then I get a maximized window (gnome defaults to single monitor maximization)
* Then I can resize the window like any other
* When I reenter fullscreen again both monitors are used.

**Comment by akallabeth** [comment]
@stilyan Could you add some details? Will close the issue otherwise as not reproducible.

**Comment by stilyan** [comment]
Surely, tomorrow. I'm not close to the setup at this point. Thanks.

**Comment by stilyan** [comment]
@akallabeth 

I start dual monitor setup like so:
`echo Y | /opt/freerdp/bin/xfreerdp \
-window-drag \
-menu-anims \
-themes \
+fonts \
/bpp:32 \
/f \
/smart-sizing \
-decorations \
-compression \
/audio-mode:0 \
/mic:format:1 \
/sound:latency:50 \
/multimon \
-floatbar \
/v:$1 \
/u:$2 \
/p:$3`

Going through your points one by one:

- I can start in dual monitor fullscreen, ok that is expected
I can do it too. It's fine.
- I can leave fullscreen, then I get a maximized window (gnome defaults to single monitor maximization)
I too get a maximized window **(gnome defaults to single monitor maximization)** **- this is my problem. I don't want single monitor maximization because content in windows becomes unreadable pretty much. I want maximization on both screens.**
- Then I can resize the window like any other
I can't do this unfortunately. It's like my window doesn't have a header so once I drag it somewhere - that's it. I can't do it again. When I try - I'm messing with content inside the window itself, not moving or resizing it.
- When I reenter fullscreen again both monitors are used.
Same for me, no problem there.

**Comment by akallabeth** [comment]
Ok, so the you want maximization part can't be handled by freerdp, you need some external tool/script for that.
As for you no longer can drag the window around, that is indeed strange. I've tried this too and it works (but only have debian and fedora to test with dual screen)

**Comment by akallabeth** [comment]
So, the initial issue is resolved as `not how the option works`, remains the dragging thing. Can not reproduce, could you give details?
