### ISSUE TITLE
About assistance::freerdp_assistance_generate_pass_stub error

### ISSUE THREAD

**Issue by aijyo** [FreeRDP/FreeRDP#5130]
Just as the title, assistance::freerdp_assistance_generate_pass_stub is used to init a passstub(can be find int remote assistance file).
Current implement is : 	
/**
	 * PassStub generation:
	 *
	 * Characters 0 and 5-13 are from the set A-Z a-z 0-9 * _
	 * Character 1 is from the set !@#$&^*()-+=
	 * Character 2 is from the set 0-9
	 * Character 3 is from the set A-Z
	 * Character 4 is from the set a-z
	 *
	 * Example: WB^6HsrIaFmEpi
	 */

But from the document (https://blogs.msdn.microsoft.com/openspecification/2011/10/31/password-encryption-in-establishing-a-remote-assistance-session-of-type-1/) and my disassembly( to verify this is still work for remote-assistance-session-of-type-2), the correct implement  may be:
All of the 14 characters are ASCII characters.

Characters 1-2 and 7-14 are from the set A-Z a-z 0-9 * _

Character 3 is from the set !@#$&^*()-+=

Character 4 is from the set 0-9

Character 5 is from the set A-Z

Character 6 is from the set a-z

Some thing like:
![image](https://user-images.githubusercontent.com/7956449/49786533-20465200-fd5f-11e8-80bb-def718c70309.png)

**Comment by akallabeth** [comment]
This is not a support forum.

**Comment by aijyo** [comment]
> This is not a support forum.
So where should I submit this question, I want to implement somthing like msra.exe based on the current freerdp-shadow-cli code, I think the original intention of freerdp-shadow-cli is also like this.
Or freerdp-shadow-cli is just a toy, freerdp is not going to implement it.

**Comment by akallabeth** [comment]
as already mentioned, please write a mail with a proper explanation to the mailing list.
If you describe your problem and what you want to do you'll get an answer.
And please don't write something like this issue where everyone has to guess quite a lot to only grasp what this is about.

Currently `freerdp-shadow-cli` is a simple tool to mirror the current session of a user, no session management or other stuff planned, but we're happy about pull requests for any such feature.

**Comment by aijyo** [comment]
> as already mentioned, please write a mail with a proper explanation to the mailing list.
> If you describe your problem and what you want to do you'll get an answer.
> And please don't write something like this issue where everyone has to guess quite a lot to only grasp what this is about.
> 
> Currently `freerdp-shadow-cli` is a simple tool to mirror the current session of a user, no session management or other stuff planned, but we're happy about pull requests for any such feature.

Thanks for your replay and explanation.
