### ISSUE TITLE
USB Keyboard SmartCard Authentication issue

### ISSUE THREAD

**Issue by ppokhriyal** [FreeRDP/FreeRDP#5132]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by ppokhriyal** [comment]
XfreeRDP Version 2.0.0-RC2
Server to Connect Windows Server 2008 R2
SmartCARD : LENOVO KEYBOARD SMARTCARD

I want to use the above mentioned Lenovo Keyboard Smart card for authentication.But when i got the session of the server it gets stuck on **"Please unlock the smart card with external device"**.

**Comment by akallabeth** [comment]
Support questions please via IRC or mailing list.

**Comment by informatimago** [comment]
You should get the reader doc: 
https://download.lenovo.com/pccbbs/options/usb_smartcard_kb_en.pdf
That message doesn’t come from FreeRDP, but from the card driver.  Check the leds and the doc. My guess is that it requests that you type the PIN on the keypad.
