### ISSUE TITLE
Seamless window has limited desktop

### ISSUE THREAD

**Issue by chrislong** [FreeRDP/FreeRDP#5136]
**Describe the bug**
When launching an application in seamless mode, the window does not repaint outside of a region smaller than the whole screen, approximately 2524x1358. If any part of the window is farther from the origin than that, that part of the window does not repaint nor do mouse clicks register there. For example, my laptop monitor has resolution 3840x2160, so I need to keep remote apps in the top left area of the screen or they don't work.

**To Reproduce**
1. Launch xrdp in seamless mode, such as `xfreerdp /v:remotewindowsmachine /u:user /p:password /app:'%windir%\explorer.exe'`
2. Move the window far away from the origin (so at least part of it is farther than 2524x1358)
3. Click in the far away part and see nothing happen
4. Move another window over it and then reveal it and see it not repaint

**Expected behavior**
I should be able to drag a remote window anywhere on my desktop (currently 9600x2160 pixels) and they should function properly.

**Screenshots**
The screenshot below shows a window not repainting itself.
![image](https://user-images.githubusercontent.com/430183/49821025-6bed0180-fd47-11e8-9b82-078466572885.png)

** Application details
* Version of FreeRDP
2.0.0-dev5 (531b1b63e)
* Command line used
`xfreerdp /v:remotewindowsmachine /u:user /p:password /app:'%windir%\explorer.exe'`
* output of `/buildconfig`
`This is FreeRDP version 2.0.0-dev5 (531b1b63e)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 5.3.1
Target architecture: x64`
* OS version connecting to
Windows 10 Pro
* If available the log output from a run with `/log-level:trace` 
It's very long so I'm not including it right now. I could attach it if desired.

**Desktop (please complete the following information):**
 - OS: Linux - Ubuntu
 - Browser N/A
 - Version 18.04

**Additional context**
I tried using the `/size` parameter, but it didn't seem to affect this issue. I didn't see any other params that looked applicable.

**Comment by chrislong** [comment]
Some extra info that might be relevant: When I run `xfreerdp /monitor-list`, the output is
>       * [0] 2560x1440   +5440+0
>        [1] 3840x2160   +0+0
>        [2] 1600x1200   +8000+0
>        [3] 1600x1200   +3840+0

The dimensions of monitor 0 are simliar to the limitations I see for window repainting and event handling, so I think this multi-monitor setup may have something to do with what I'm seeing.

**Comment by chrislong** [comment]
I've discovered a partial workaround. Adding `/span` lets windows work over most of my desktop, but if I drag a window too far right it grows itself really big.

**Comment by akallabeth** [comment]
You might have hit one of these https://social.technet.microsoft.com/wiki/contents/articles/31983.remote-desktop-protocol-maximum-supported-resolutions.aspx although I don't see which one (should be well in range for windows 10 as server)

**Comment by akallabeth** [comment]
Does your server enforce some kind of resolution limit? Check the remote desktop settings with `gpedit.msc`

**Comment by chrislong** [comment]
I found a setting "Limit maximum display resolution" (in Computer Configuration->Administrative Templates->Windows Components->Remote Desktop Services->Remote Desktop Session Host->Remote Session Environment), and it is "not configured". Is there another setting I should check?

**Comment by akallabeth** [comment]
That just means use policy default, whatever it is. Try to set to off if possible

**Comment by hardening** [comment]
@chrislong IIRC we check the 8192 value because it is given in the official specs.

**Comment by akallabeth** [comment]
@hardening that is out of date iirc, newer servers have higher limits
