### ISSUE TITLE
/drive:hotplug,* flag errors with "No match".

### ISSUE THREAD

**Issue by sebastianuw** [FreeRDP/FreeRDP#5137]
With build 0b7b9c0 I run xfreerdp with the flag "/drive:hotplug,*" with no issues, on newer builds (including today's) I get the error: "No match" when I try starting xfreerdp with it.

**Comment by jphein** [comment]
How does the flag "+drives" work?

**Comment by akallabeth** [comment]
@sebastianuw please clarify. I can run a session perfectly fine with `xfreerdp /v:<host> /u:<user> /p:<pwd> /drive:hotplug,*`

**Comment by akallabeth** [comment]
@jphein Support questions please via IRC or mailing list

**Comment by akallabeth** [comment]
Closing as not reproducible.
Create a new issue with additional information if you can reproduce.
