### ISSUE TITLE
Can't write symobls in login or password fields in app mode

### ISSUE THREAD

**Issue by svarog181** [FreeRDP/FreeRDP#5141]
Describe:
I have Windows Server 2016 with specific app on him and ALTLinux Workstation 8 or OpenSUSE 15.
When I open rdp session in app mode from Linux to Windows with this specific app, I can't write any symbols in login and password fields. If start another app in the same time on the same Linux (notepad, calc, etc), symbols start to be written. In remote desktop mode, all working.

To Reproduce:
1. On Linux, in shell, command:
   /usr/bin/xfreerdp /u:xxxx@xx.xxx /p:xxxxxx /v:address:3389 /size:1920x1080 /app:"C:\Program Files 
   (x86)\xxxx\xxxx\xxxx.exe" /cert-tofu /drive:home,/home/user -compression +aero 
2. Windows with app opens, but I can't write any symbols.
3. Command 
   /usr/bin/xfreerdp /u:xxxx@xx.xxx /p:xxxxxx /v:address:3389 /size:1920x1080  
   /app:"C:\Windows\system32\notepad.exe" /cert-tofu /drive:home,/home/user -compression +aero  
  and symbols are written in both apps.

Expected behavior
I expect that the characters typed on the keyboard will be typed in the login and password fields

Application details
  Version of FreeRDP; 2.0.0 rc2
  OS version connecting to: Windows 2016

**Comment by svarog181** [comment]
> Does it work with more recent versions?
 
I try with various builds of 2.0.0 (rc1, rc2, ALT builds), everywhere some problem

**Comment by akallabeth** [comment]
@svarog181 What do you mean with `ALT builds` and why not more recent `rc` versions as `2.0.0-rc4`?
