### ISSUE TITLE
Not setting "-K" option only applies to keyboard, but not to mouse + keyboard combinations

### ISSUE THREAD

**Issue by unknownError** [FreeRDP/FreeRDP#5153]
Hi 

I am Trying to use the keyboard's "alt" key and different mouse buttons, but events are not sent to the remote windows machine as expected. The same is also partly reported in #3888. The mentioned +unmap-buttons does not influence the behaviour.

I tried nightly build and ubuntu 16.04 stock version of freerdp: 2.0.0-dev5 (faff639ad) and 
1.1.0-beta1. 

Reading through the report #3888 which is only concerning clicking, also dragging does not work and i also noticed that some window manager mouse + keyboard gestures aren't properly overridden as they should be when the "-K" option is not used. (at least i think the -K should include keyboard and mouse, not only keyboard if possible)

e.g. on my linux host i can switch between applications of a desktop using alt + middle mouse click (very similar to alt tab). I think this comes from the default xfce configuration that I'm using. Or it is even an x11 standard? i don't know). So when I have 2 windows open on my linux machine, one is a freerdp window (full-screen), the other one a small shell window. After alt + middle click the shell window gets shown. 

Other method to reproduce an unexpected behavior showed up when tried to implement some mouse + keyboard gestures in the windows machine like alt + left-mouse-drag (to drag windows in linux style). The command apparently just gets ignored. Neither the xrdp window on the linux machine receives the commands (the window doesn't move on the linux machine) nor does the window in the remotely connected windows machine.  the two expected behaviors for alt + drag left mouse:
*  move the xrdp window on the linux client desktop
*  keystroke +  mouse movement are reported to the remotely accessed machine.

**Comment by akallabeth** [comment]
@unknownError You're using the legacy command line (`-K -> -grab-keyboard`) and are inverting the meaning.
You effectively disable the keyboard low level grabbing and your window manager is handling these events.

**Comment by akallabeth** [comment]
No feedback, closing.
