### ISSUE TITLE
Window drag outline is not drawn

### ISSUE THREAD

**Issue by paniksystem** [FreeRDP/FreeRDP#5154]
From the latest master:
xfreerdp /v:host /u:user /p:pass /cert-ignore /w:1024 /h:768

When dragging a window with the mouse, a black outline should be drawn to simulate the window movement. This seems to no longer be the case.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by paniksystem** [comment]
I don't what else to say,
xfreerdp built from latest master from ubuntu 16.04 and 18.04
connecting to a Windows 10 desktop

**Comment by akallabeth** [comment]
Ok, windows 10. no changes on our side, does this work with mstsc?

**Comment by paniksystem** [comment]
Good call! Even with mstsc the drag outline is not present, i guess this is related to Windows 10 then.
Closing. Thank you. Sorry for wasting your time.

**Comment by paniksystem** [comment]
Funny story, for anyone interested, the last Windows Update on the Windows 10 desktop seems to have fixed the issue.

**Comment by akallabeth** [comment]
@paniksystem looks like we're not the only ones with issues :)
