### ISSUE TITLE
wayland fullscreen shell support

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#5162]
https://cgit.freedesktop.org/wayland/wayland-protocols/tree/unstable/fullscreen-shell

**Comment by hardening** [comment]
@akallabeth the link you sent is not fullscreen support, IIRC it's a specific shell that displays a surface as the content of the screen.

**Comment by akallabeth** [comment]
@hardening Might still be handy for terminal clients, so the session is actually the whole shell.

**Comment by akallabeth** [comment]
Implemented with #5209
