### ISSUE TITLE
Wayland multimonitor support

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#5163]
Add support for multimonitor in wayland client

**Comment by caseif** [comment]
Are there any plans to implement this in the near future? I don't intend to pester; I'm just curious whether it's still on the radar.

**Comment by akallabeth** [comment]
@caseif currently we´re busy refactoring the core library, client / server improvement is scheduled after that is fixed.
Help is, of course, always appreciated.

**Comment by caseif** [comment]
@akallabeth Got it, I appreciate the reply. I have considered trying to contribute an implementation, but unfortunately I don't really have the requisite knowledge right now to know where to begin.

**Comment by akallabeth** [comment]
wayland client will be deprecated and replaced with sdl-client.
