### ISSUE TITLE
Add an "% screen" parameter for xfreerdp

### ISSUE THREAD

**Issue by FurtadoPires** [FreeRDP/FreeRDP#5171]
I would like to know if it's possible to size the screen based on the percentage of the monitor (like in rdesktop using the parameter "-g 90%" which opens a window based on 90 percent of the resolution) for example. So it would be easier to configure an script without worry about the resolution of the user monitor.

And if not, if it would be possible to implement in a future update.

Thank you!

**Comment by bmiklautz** [comment]
@FurtadoPires that's already implemented on master and will be part of the 2.0 version.
Maybe it is also interesting for you that you can now use the percentage of width or height only if required.

From the commit  (4592deee724e2be837c5c3439ed78f16f2c797e9)  message:
```
    If the size parameter is used with a percentages like /size:50% now
    an additional 'w' or 'h' can be appended (like /size:50%w) to specify
    where the percentage should be applied. If both or none are set the
    behavior is like it was before and the percentage is applied to width
    and height.
```
