### ISSUE TITLE
Redirect local usb microphone and audio fail

### ISSUE THREAD

**Issue by suichangyin** [FreeRDP/FreeRDP#5179]
Hello,
I'm trying to redirect my usb microphone and audio to a remote Windows machine.however there are no devices under the Windows Sound Recording Devices tab.

I've tried connecting using the following commands as well without success:
/opt/freerdp-nightly/bin/xfreerdp  /rfx /cert-ignore /sound:sys:pulse,format:1,quality:high,latency:200 /microphone:sys:pulse +async-update +drives +async-input -floatbar /u:user /p:111111 /v:10.0.40.184

The session establishes but there is only remote recording device but no usb recording device and the usb microphone and audio does not work.

And i try to redirect the usb microphone and audio by /usb:id,dev:7750:8195,but it also does not work,and the log print:
[13:37:43:175] [4162:4173] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded pulse backend for rdpsnd
[13:37:45:788] [4162:4163] [INFO][com.freerdp.channels.audin.client] - Loaded pulse backend for audin
[13:37:45:788] [4162:4163] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel urbdrc
[13:37:45:788] [4162:4163] [ERROR][com.freerdp.channels.urbdrc.client] - error processing arguments
[13:37:45:795] [4162:4163] [WARN][com.freerdp.channels.urbdrc.client] - bus:0 dev:0 not exist in udevman
[13:37:45:796] [4162:4163] [INFO][com.freerdp.channels.urbdrc.client] - VID: 0x7750, PID: 0x8195
[13:37:45:803] [4162:4163] [WARN][com.freerdp.channels.urbdrc.client] - hub was not found!
[13:37:45:803] [4162:4163] [ERROR][com.freerdp.channels.urbdrc.client] - USB init: Error to get HUB handle!!
[13:37:45:804] [4162:4163] [WARN][com.freerdp.channels.urbdrc.client] - bus:2 dev:9 not exist in udevman

the lsusb output is below:
# lsusb
Bus 002 Device 009: ID 7750:8195
Bus 002 Device 008: ID 0d8c:013c C-Media Electronics, Inc. CM108 Audio Controller
Bus 002 Device 007: ID 1a40:0101 Terminus Technology Inc. 4-Port HUB 

Any idea what else I might try?

Here are some details about my setup:

Client (OS name and version): Ubuntu 14.04 for armhf
Connecting to (OS and version): Windows 2007 SP1
Connecting via (RDP, VNC, ...): RDP
RDP issues only, freerdp version (xfreerdp --version): 2.0.0-rc4

Here is buildconfig:
# xfreerdp /buildconfig
This is FreeRDP version 2.0.0-rc4 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NEON=ON WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 4.8.2
Target architecture: ARM

**Comment by akallabeth** [comment]
Is mic redirection enabled on the server?

**Comment by suichangyin** [comment]
> Is mic redirection enabled on the server?

The 3.5mm mic and audio work fine.
Now,only the usb mic and audio does not work.

**Comment by akallabeth** [comment]
You're using pulse audio locally? Try to set the default microphone for that application.
We only forward the default device for an application.

**Comment by akallabeth** [comment]
USB redirection for certain devices is blocked by MS RDP servers, so `/usb` will not work.
As for the USB microphone, check your local audio mixer and select the proper device, then you'll have that one redirected properly. (Just do `/microphone`)
