### ISSUE TITLE
Freerdp's rdpSettings structure has an AlternateShell field length limit of 255

### ISSUE THREAD

**Issue by chencjfeng** [FreeRDP/FreeRDP#5181]
When I try to connect to Windows Server 2008 R2 32-bit system with freerdp, the AlternateShell in the setting structure fills in a cmd command to start some programs of the target host. After the length of this command exceeds 255, it will be automatically truncated by freerdp, which leads to my target. The host program receives the missing parameters. Do you have any good way to solve this problem for me? Thank you!

**Comment by akallabeth** [comment]
That is a protocol limitation, you're out of luck.
You could, of course, just start a script server side doing all the commands...
