### ISSUE TITLE
Very poor perfomance while forward X

### ISSUE THREAD

**Issue by olegon-ru** [FreeRDP/FreeRDP#5203]
This is FreeRDP version 2.0.0-rc4 (n/a)
Linux hostX 4.19.13-300.fc29.x86_64 #1 SMP Sat Dec 29 22:54:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
I connected via LTE 25 Mbit/s or some WiFi by 
ssh -X hostX
and run xfreerdp from hostX (forwarded it to my notebook, because access opened only for hostX). FreeRDP is verrrry slooow... I compared with rdesktop - it faster, at least two times, suppose 5x-10x.
I tried all options of freerdp, GDI sh/hw and diffferent async options without success... Is any way to make it faster through XForward?

**Comment by akallabeth** [comment]
Don't run the rdp client on the remote but locally and tunnel the rdp session though ssh via port forward?

**Comment by olegon-ru** [comment]
Unfotunately it's more than 40 scripts with RDP connections definitions (many RDP hosts) there and I connecting not only from notebook, but from other hosts, so, it'll make me crazy to remember all this structure. I prefer xfreerdp because of +auth-only options, so I can check all connections with the same 40+ scripts.

**Comment by akallabeth** [comment]
You might be lucky with /gdi:hw and disabling all modern protocol features, but that version of rdp is being phased out.
Anyway, closing as not really a bug.

**Comment by olegon-ru** [comment]
I tried to use GDI as I wrote above... And I forget to said, that locally from hostX, it's works perfect. Suppose it's some troubles with renderer, not version of RDP-protocol. May be you can consider to include some option to change renderer behaviour? Perfomance differ dramatically...
