### ISSUE TITLE
Black screen using remote apps with three monitor setup using /multimon without /span

### ISSUE THREAD

**Issue by goguda** [FreeRDP/FreeRDP#5206]
**Describe the bug**

With a three monitor setup, using the /multimon flag without using /span produces a black window when accessing a remote app. This occurs no matter what the remote app specified is. The remote app shows correctly when /span is specified with /multimon.

(I noticed this as well with my old dual monitor setup, but you could fix it by either reconnecting or pressing CTRL+SHIFT+ESC to open task manager for a second)

**To Reproduce**

1. Run xfreerdp with /app flag, specifying a remote app to open.
2. Add /multimon flag and execute command (seems to cause an intermittent issue on dual monitors, a permanent issue on triple monitors).

**Expected behavior**

The remote app window should be shown properly.

**Screenshots**

Image is of Microsoft Word (but all apps do the same thing):

![image](https://user-images.githubusercontent.com/26887502/51435818-9f785100-1c4e-11e9-98c7-45b893c3d06b.png)

** Application details

* Version of FreeRDP: 2.0.0-rc4
* Command line used: `xfreerdp /v:servername /u:DOMAIN\\username /p:password /app:"||WINWORD" -sec-nla /multimon`
* output of `/buildconfig`: 
`Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -fPIE -pie -DNDEBUG -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 8.2.1
Target architecture: x64`
* OS version connecting to: Windows Server 2016 Standard
* Log output from a run with `/log-level:trace`: 
[xfreerdp_debug.log](https://github.com/FreeRDP/FreeRDP/files/2776330/xfreerdp_debug.log)

**Desktop (please complete the following information):**

 - OS: openSUSE Tumbleweed

**Additional context**

I've tried all the other common fixes for the black screen issue (logging out/back in, /gdi flag, CTRL+SHIFT+ESC, playing around with effects flags, etc.) with no luck.

**Comment by akallabeth** [comment]
@goguda The `/multimon` flag is not really applicable for `/app` mode.
In `/app` mode there are certain limits regarding full resolution and they depend on the remote OS being used. (the minimum value is `8192x8192` , see https://social.technet.microsoft.com/wiki/contents/articles/31983.remote-desktop-protocol-maximum-supported-resolutions.aspx)
Be sure you're not violating one of these first.

**Comment by goguda** [comment]
Hm... the ‘/multimon’ flag does seem to be applicable for ‘/app’ mode... if you don’t specify it you can’t drag the app across all monitors (i.e. it will only run on one monitor). It’s to my understanding that the full workspace resolution still has to be passed to the server in order for the app to render correctly in any area of the monitor(s) on the client, making ‘/multimon’ needed in this case, but I could be wrong.

I’m also certainly not even getting close to those maximum resolutions; all three monitors are 1080p.

**Comment by akallabeth** [comment]
@goguda Ok, so you're using at least `2008r2`? What I meant is (could be wrong, just from memory) that in `app` mode we currently just send as one large monitor, which might explain the issue.

**Comment by goguda** [comment]
@akallabeth Ah okay, I see what you're saying. Sorry I should have specified, I'm running Server 2016. Just weird it works with `/span` after `/multimon`... wouldn't that send as one large monitor as well?

**Comment by akallabeth** [comment]
@goguda Ok, that is indeed interesting, adding it to the list of things to do for fixing rails properly

**Comment by Fmstrat** [comment]
I'm running into this problem, too. With `/multimon` and `/span` on a three monitor system it seems to work, however maximizing always maximizes on the third monitor.
```
xfreerdp /u:User /v:192.168.122.29 +auto-reconnect +home-drive -wallpaper /app:"C:\Program Files\Microsoft Office\Office16\WINWORD.EXE" /multimon /span
```

**Comment by Hyperspeed1313** [comment]
What was the fix for this? I'm experiencing the exact same problem in 2023 (using winapps as an overlay). If I do both /mulitmon and /span then maximizing will maximize the window across all 3 monitors at once
