### ISSUE TITLE
Mac Osx Keyboard problems

### ISSUE THREAD

**Issue by Bob590** [FreeRDP/FreeRDP#5214]
**Found a bug? - We would like to help you and smash the bug away.**
1. __Please don't "report" questions as bugs. For these (questions/build instructions/...) please use one of the following means of contact:__
   * We are reachable via IRC _#freerdp on freenode_
   * We are reachable via mailing list <freerdp-devel@lists.sourceforge.net>
   * Try our mailing list for discussions/questions
1. Before reporting a bug have a look into our issue tracker to see if the bug was already reported and you can add some additional information.
1. If it's a __new__ bug - create a new issue.
1. For more details see https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Application details
* Version of FreeRDP
* Command line used
* output of `/buildconfig`
* OS version connecting to
* If available the log output from a run with `/log-level:trace` 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

** Please remove this text before submitting your issue!

_Thank you for reporting a bug!_

**Comment by Bob590** [comment]
File winpr\libwinpr\input\keycode.c

I have made a Mac Osx Client using Qt5 and the freerdp library.
In order to make the keyboard type the correct characters I have commented these lines:

DWORD KEYCODE_TO_VKCODE_APPLE[256] =
{                     
#ifdef OLD_ORIGINAL_CODE  // Bug fix by Bob for Mac-Osx
	0, /* 0 */
	0, /* 1 */
	0, /* 2 */
	0, /* 3 */
	0, /* 4 */
	0, /* 5 */
	0, /* 6 */
	0, /* 7 */
#endif

I don't know if this is the right way to correct this bug... but now you know there is a problem there!
:-)

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
Please do not misuse the issue tracker for support questions.

**Comment by Bob590** [comment]
From my point of view this is a BUG. I don't need ANY support sir!

**Comment by akallabeth** [comment]
@Bob590 Sorry, that was not meant as offence :)
But since you're implementing your own client and this works with the default mac os client (and some private Qt5 based one I know), I assume this is more of a support (aka how to implement this with my client) question.

**Comment by Bob590** [comment]
Please can you point me to the DEFAULT mac osx client?
Please give a me a link to it.
Thank you.

**Comment by Bob590** [comment]
I have found it at client\Mac in the source code tree.
Thank you.
