### ISSUE TITLE
enabling compression freezes xfreerdp

### ISSUE THREAD

**Issue by terrible-broom** [FreeRDP/FreeRDP#522]
I'm using git version of freerdp (from Mar 27, 2012). My command-line is:

xfreerdp --no-nla --ignore-certificate -u user -p pass -z rd-farm01.study.tst

Very often (but not always) it leads to black session screen and grabbed keyboard (I can't type anything in another windows on my linux desktop). Ctrl+C don't help to terminate freerdp, only changing the virtual terminal (Ctrl+Alt+F2) and using 'kill' helps. 
Without '-z' option freerdp seems to work OK.
My connection point is a farm consisting of 2 Windows 2008R2 servers.

**Comment by bmiklautz** [comment]
This should already be fixed on master. Please re-open or create a new issue if this problem still exists.
