### ISSUE TITLE
RDS Licensing

### ISSUE THREAD

**Issue by crink1960** [FreeRDP/FreeRDP#5229]
FYI  to whoever is attempting to add RDS licensing support to the library.  You need to be consistent with the device name used to request the  license otherwise the license server continues to issue temporary  licenses and eventually runs out. Using the MAC of the adapter being  used to connect to the server combined with a shortened ClientHostName  is pretty reliable.

**Comment by crink1960** [comment]
FYI to whoever is attempting to add RDS licensing support to the library. You need to be consistent with the device name used to request the license otherwise the license server continues to issue temporary licenses and eventually runs out. Using the MAC of the adapter being used to connect to the server combined with a shortened ClientHostName is pretty reliable.

**Comment by akallabeth** [comment]
Could you fix the issue please? You still have the templatetext and I have no idea what you're trying to tell.

**Comment by hardening** [comment]
@crink1960 Hi, it would be nice if we could discuss of that on IRC #freerdp on freenode

**Comment by crink1960** [comment]
After reviewing the issue in more detail it can be fixed in the native application. Simply set the ClientHostName to a consistent value for each device. In our case we used the MAC of the WiFi adapter. The ClientHostName is used by the library when requesting a new license. The license server uses that unique name to look up a previously issued CAL. If the name exists in the store then the same CAL is re-issues as long as it is not expired. If the name does not exist then a temporary CAL is issues until the next time the device logs in at which time the temporary CAL becomes permanent.
