### ISSUE TITLE
Drive redirection and Google Drive File Stream

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#5231]
Several Royal TSX customers reported an issue with our FreeRDP plugin and Google Drive File Stream. I reproduced this and can confirm that at least on macOS, FreeRDP's drive redirection implementation currently doesn't work with Google Drive File Stream volumes. The redirected drive appears in the remote session but never shows any files.

I debugged this and found the culprit to be the way `FindFirstFileA` is implemented. Specifically, the problem is in [line 867 of winpr/libwinpr/file/generic.c](https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/file/generic.c#L867). To locate the first file or folder, the search pattern "." is used and passed to [`FindNextFileA`](https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/file/generic.c#L1066) which iterates over all files and folders using `readdir`.

Unfortunately, Google Drive File Stream volumes never return a "." or ".." directory entry at least when iterated with `readdir`.

**Comment by akallabeth** [comment]
@lemonmojo interesting, so you can´t do a `ls` from a terminal too?

**Comment by lemonmojo** [comment]
@akallabeth I can, and if I do `ls -la` it also shows the "." and ".." entries. `readdir` never returns those entries though.

**Comment by lemonmojo** [comment]
@akallabeth To reproduce, you can use the following small program and point it at your drive file stream directory: https://gist.github.com/lemonmojo/c83e09c9b58af4dd8390fe0b9365a9e1

**Comment by akallabeth** [comment]
@lemonmojo don´t have a google account to test with ;)
I can´t find the docs for that, but it seems fishy that the entries `.` and `..` are missing.

**Comment by lemonmojo** [comment]
@akallabeth File Steam is fishy as a whole! Doesn't keep people from using it unfortunately...

**Comment by greg99999** [comment]
Any update on this issue? Other Mac RDP clients are able to navigate Google Drive folder, but the FreeRDP based clients are not (Royal TSX for example).

**Comment by akallabeth** [comment]
closing as we don´t plan to fix this.
pull requests welcome though.
