### ISSUE TITLE
android can not include .h file

### ISSUE THREAD

**Issue by f987002856** [FreeRDP/FreeRDP#5233]
Hello,when use ./scripts/android-build-freerdp.sh --ndk <ANDROID_NDK> --sdk <ANDROID_SDK> to build,I get the problem.

![errorinfo](https://user-images.githubusercontent.com/12999173/52042859-33b0b500-2579-11e9-8541-ac806101888e.png)

Is there any package I have not installed?
OS: 18.04 x64
cmake: 3.12.2
android-ndk: r10b
android sdk: target-26

**Comment by f987002856** [comment]
Hello,when use ./scripts/android-build-freerdp.sh --ndk <ANDROID_NDK> --sdk <ANDROID_SDK> to build,I get the problem.
![cvrew p 9w_so4oiyl uvk](https://user-images.githubusercontent.com/12999173/52042362-f39d0280-2577-11e9-9bd7-ca0765ec84fe.png)
Is there any package I have not installed?
OS: 18.04 x64
cmake: 3.12.2
android-ndk: r10b
android sdk: target-26

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
