### ISSUE TITLE
Not able to resize the remote desktop content dynamically(Auto resize) in the same session.

### ISSUE THREAD

**Issue by thecrazyonestherebels** [FreeRDP/FreeRDP#5238]
**Describe the bug**
Auto resize is not working in active session even though the 'freerdp->settings->DesktopWidth' and 
'freerdp->settings->DesktopHeight' changed with in same session. So the content got scale up or shrink down and gives bad experience. Is there any way to achieve dynamic auto resize without restarting the freerdp session.

**Screenshots**
This image shows default content.
<img width="1679" alt="remotedesktopwithoutresize" src="https://user-images.githubusercontent.com/41958166/52322613-d052d700-29ff-11e9-853b-5ffa81fad5cf.png">

This image shows shrinked content after resizing.
<img width="1657" alt="remotedesktopwithresize" src="https://user-images.githubusercontent.com/41958166/52322614-d052d700-29ff-11e9-8a64-b81cfc0fe9a8.png">

**Comment by thecrazyonestherebels** [comment]
I checked the smart-sizing and found that it is not related to resizing content.

**Comment by hardening** [comment]
Hi,
first of all this is not the place for questions, you have the mailing list or IRC for that.
Secondly `/dynamic-resolution` may be the option you're looking for..

**Comment by thecrazyonestherebels** [comment]
Hi, Thanks for the response.

You mean 'settings->DynamicResolutionUpdate' right by enable it not given any results. Still able to see the scaling instead of resizing.

**Comment by hardening** [comment]
@thecrazyonestherebels this is why we put a template asking people to describe the bug they're having, version, context and so on. 
My guess is that you're not using the xfreerdp client itself but the FreeRDP lib. As you can see here: https://github.com/FreeRDP/FreeRDP/blob/master/client/common/cmdline.c#L1824, you need to set the `settings->SupportDisplayControl` flag to load the corresponding channel.

**Comment by thecrazyonestherebels** [comment]
Hi I am new to freeRDP protocol pardon me for the lack of details.
I disabled SmartSizing and set below parameters before starting the session.
    freerdp->ssettings->DesktopResize = TRUE;
    freerdp->ssettings->DynamicResolutionUpdate = TRUE;
    freerdp->ssettings->SupportDisplayControl = TRUE;

After connecting i am resizing the window then changing the below parameters.
    freerdp->settings->DesktopWidth = size.width;
    freerdp->settings->DesktopHeight = size.height;
    // Resize the GDI surface.
    gdi_resize(self.freerdp->context->gdi, size.width, size.height);

And then creating the bitmap image with rdpContext->gdi. 
But it didn't worked for me. Any details further will be helpful. Thanks in advance.

**Comment by akallabeth** [comment]
Check #5159

**Comment by tomlucas** [comment]
Hi, I'm having the same exact issue have you ever resolved it?
