### ISSUE TITLE
re-login fails for same user

### ISSUE THREAD

**Issue by rgloor** [FreeRDP/FreeRDP#5247]
After dis-connection (disconnect, either manually closing connection with logged in user, or due to bad internet), one cannot reconnect to rdp host (workstation) with the same login / account.

Reproduction (what works):
1.) Starting the selected rdp with remmina works -> Login screen shows.
2.) First login works -> rdp session starts as expected
3.) Disconnecting or closing the session (either keeping the user logged in and disconnect the connection to continue work there at a later state, or loosing the connection due to weak internet, or logout of session) -> re-login does not work anymore  -> authentification / login fails.
The connection to the rdp host works: Login screen appears  -> but user can not login
=> it always shows 
  3.1) Welcome (Willkommen) 
  3.2) Then black screen with -> reconnection attempt 1 of 20... 
        (Wiederherstellung der Verbindung. Versuch 1 von 20...)
  3.3) then fails and returns to the login screen

This or a similar issue was experienced in a certain rc2 version.
Seemed fixed in a rc 3 version.
But is broken again with rc4.

Present setup:
using openSUSE LEAP 15 fully patched.
unsing from repositor 
http://download.opensuse.org/repositories/X11:/RemoteDesktop/openSUSE_Leap_15.0/
- freerdp-2.0.0~rc4-lp150.106.1.x86_64.rpm
- libfreerdp2-2.0.0~rc4-lp150.106.1.x86_64.rpm
- remmina-1.3.2-lp150.87.1.x86_64.rpm
- remmina-plugin-rdp-1.3.2-lp150.87.1.x86_64.rpm

While freerdp-2.0.0~rc3 (in the above opensuse leap directory) was working quite fine, after upgrading to rc4 is broken again.

~Work around:
- returning to the freerdp-2.0.0~rc2 (Version of LEAP OSS repo, not above RemoteDesktop repo)
- closing session and later re-conneting / re-login works
- it often looses the connection and often also closes complete remmina
- but re-conneting / re-login with the logged-in user at least works

**Comment by akallabeth** [comment]
@rgloor Hi, thank you for the report.
Could you check if it works with current master? (there have already been various fixes since `rc4`)
You can try our nightly builds https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds, the remmina flatpak should ship with a very recent FreeRDP or you can compile the current master (either rpm or flatpak, see https://github.com/FreeRDP/FreeRDP/wiki/Compilation)
