### ISSUE TITLE
freerdp-2.0.0_rc4: TestNTLM, TestFreeRDPCodecInterleaved fail on ppc64

### ISSUE THREAD

**Issue by ernsteiswuerfel** [FreeRDP/FreeRDP#5250]
Gentoo downstream bugreport (ppc): [https://bugs.gentoo.org/672744](url)

Re-tested on a Talos II (ppc64) with git-master. _cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON . && make -j34 && ctest -j 34 --test-load 32_:
```
[...]
99% tests passed, 2 tests failed out of 186

Total Test time (real) =  21.54 sec

The following tests FAILED:
	110 - TestNTLM (Failed)
	169 - TestFreeRDPCodecInterleaved (Failed)
Errors while running CTest
```
Output of the 2 failing tests:
```
 # ./Testing/TestFreeRDPCodec TestFreeRDPCodecInterleaved
 # ./Testing/TestSspi TestNTLM
NTLM_NEGOTIATE (length = 40):
[20:46:23:036] [29262:29262] [WARN][com.winpr.sspi] - AcceptSecurityContext status SEC_E_INTERNAL_ERROR [0x80090304]
AcceptSecurityContext status: SEC_E_INTERNAL_ERROR (0x80090304)
test_ntlm_server_authenticate failure
 # ./Testing/TestFreeRDPCodec TestFreeRDPCodecInterleaved
 # 
```

**Comment by akallabeth** [comment]
@ernsteiswuerfel big endian I assume? we lack proper hardware to test that and qemu is quite slow for that kind of emulation. (still surprised that only that few tests fail ;))

**Comment by akallabeth** [comment]
@ernsteiswuerfel for the `TestFreeRDPCodecInterleaved` issue the culprit is buffer to `UINT16` and `UINT32` casts.
If you have the opportunity, could you fix the `GETPIXEL16`, `GETPIXEL32`  macros for your endianess and check?

**Comment by ernsteiswuerfel** [comment]
Yes, Big Endian. ;)

So I replaced the funtions in _libfreerdp/codec/bitmap.c_. I think you forgot some "(" here, or else it won't build:
return (((UINT32)((const BYTE*)d)[0]) << 24) | **"("**((UINT32)((const BYTE*)d)[1]) << 16) | **"("**((UINT32)((const BYTE*)d)[2]) << 8) | ((const BYTE*)d)[3];

But the tests still fail the same way:
```
 # ./Testing/TestSspi TestNTLM
NTLM_NEGOTIATE (length = 40):
[13:55:25:628] [10814:10814] [WARN][com.winpr.sspi] - AcceptSecurityContext status SEC_E_INTERNAL_ERROR [0x80090304]
AcceptSecurityContext status: SEC_E_INTERNAL_ERROR (0x80090304)
test_ntlm_server_authenticate failure
 # ./Testing/TestFreeRDPCodec TestFreeRDPCodecInterleaved
```

**Comment by akallabeth** [comment]
@ernsteiswuerfel created a pull with the correct codec fix, please try that one.

**Comment by ernsteiswuerfel** [comment]
Thanks! **TestFreeRDPCodecInterleaved** passes now, **TestNTLM** still fails:
```
# ./Testing/TestSspi TestNTLM
NTLM_NEGOTIATE (length = 40):
[15:15:34:788] [1764:1764] [WARN][com.winpr.sspi] - AcceptSecurityContext status SEC_E_INTERNAL_ERROR [0x80090304]
AcceptSecurityContext status: SEC_E_INTERNAL_ERROR (0x80090304)
test_ntlm_server_authenticate failure
```

**Comment by akallabeth** [comment]
@ernsteiswuerfel That one is harder, would be great if you could step through the test case and check where it fails (and which error occurs)

**Comment by ernsteiswuerfel** [comment]
I can try. But how to do that?

**Comment by akallabeth** [comment]
* compile the project with `-DCMAKE_BUILD_TYPE=Debug` 
* Run with `gdb --args ./Testing/TestSspi TestNTLM` (or use a graphical debugger like `nemiver`)
* `b TestNTLM`
* `r`
* `s` to step into a function call, `n` to run the next step

**Comment by ernsteiswuerfel** [comment]
```
# gdb --args ./Testing/TestSspi TestNTLM
GNU gdb (Gentoo 8.1 p1) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "powerpc64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./Testing/TestSspi...done.
(gdb) b TestNTLM
Breakpoint 1 at 0x40bc: file /root/build/FreeRDP/winpr/libwinpr/sspi/test/TestNTLM.c, line 471.
(gdb) r
Starting program: /root/build/FreeRDP/Testing/TestSspi TestNTLM
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Breakpoint 1, TestNTLM (argc=1, argv=0x3fffffffeed0) at /root/build/FreeRDP/winpr/libwinpr/sspi/test/TestNTLM.c:471
471	{
(gdb) s
476		BOOL DynamicTest = TRUE;
(gdb) s
480		client = test_ntlm_client_new();
(gdb) s
test_ntlm_client_new () at /root/build/FreeRDP/winpr/libwinpr/sspi/test/TestNTLM.c:271
271		ntlm = (TEST_NTLM_CLIENT*) calloc(1, sizeof(TEST_NTLM_CLIENT));
(gdb) s
NTLM_NEGOTIATE (length = 40):
[16:26:12:779] [2473:2473] [WARN][com.winpr.sspi] - AcceptSecurityContext status SEC_E_INTERNAL_ERROR [0x80090304]
AcceptSecurityContext status: SEC_E_INTERNAL_ERROR (0x80090304)
test_ntlm_server_authenticate failure
[Inferior 1 (process 2473) exited with code 0377]
```

**Comment by akallabeth** [comment]
@ernsteiswuerfel yes, that I could read from the initial report, interesting would be where in `AcceptSecurityContext` the error occurs. (that is quite a call stack down)

**Comment by ernsteiswuerfel** [comment]
Sorry, my fault! I misread your post. Here's the hopefully better gdb output.
[debug01.txt](https://github.com/FreeRDP/FreeRDP/files/2861043/debug01.txt)

**Comment by akallabeth** [comment]
@ernsteiswuerfel There is some `s` missing for the actual error code to be set...

**Comment by ernsteiswuerfel** [comment]
Hope this output is more helpful.
[debug02.txt](https://github.com/FreeRDP/FreeRDP/files/2867529/debug02.txt)
