### ISSUE TITLE
Allow Custom Scale Values With the /scale Switch

### ISSUE THREAD

**Issue by aecooper** [FreeRDP/FreeRDP#5253]
Please allow custom scale percentages other than just 100, 140 and 180. Ideally let the user decide on the scale factor, or allow factors divisible by 10. For higher DPI monitors these course values either mean the font text is too small or too large.

When I manage to change the remote desktop's DPI scaling value by using the MSTSC client and then changing the scaling value in the remote desktop (which is then honoured) this is ignored when using xfreerdp2. Thus I have to use the /scale:140 switch. Ideally I would want to use /scale:120 as 140 is far too large and 100 is far too small.

Many thanks in advance,

Tony.

**Comment by akallabeth** [comment]
Not possible, the protocol does not allow that. You might find the /smart-sizing option interesting though.

**Comment by akallabeth** [comment]
See `[MS-RDPEDISP]` for details.

**Comment by aecooper** [comment]
I was afraid  that might be the case. Many thanks for your reply. I did try the smart-sizing option but it didn't seem to do anything, do you just supply it on it's own or do you have to specify other switches relating to it (i.e. will it only work if you specify a workspace size etc).

**Comment by akallabeth** [comment]
@aecooper just resize the window or use it with a resolution argument and the /size parameter.

**Comment by aecooper** [comment]
Thankl you :-).

**Comment by mojoba** [comment]
The /w /h and /smart-sizing together with /f doesn't work. It ignores the width and height in fullscreen. Any other way to achieve custom scale factor?

**Comment by akallabeth** [comment]
@mojoba what are you talking about? `xfreerdp /f /smart-sizing:1280x768 ...` works like a charm here on a full HD monitor

**Comment by zx2c4** [comment]
> Not possible, the protocol does not allow that. You might find the /smart-sizing option interesting though.

`/smart-sizing` doesn't have the server render at higher resolution but just does a low quality upscale locally, which is suboptimal.

If 1.8x is the highest it can go -- not 2x -- any idea what Microsoft's own RDP client is doing to work well in HiDPI scenarios?

**Comment by akallabeth** [comment]
look at the other `/scale-desktop` option, it might be the one you are looking for

**Comment by zx2c4** [comment]
That one has no discernable effect.

**Comment by akallabeth** [comment]
then you can check https://learn.microsoft.com/en-us/openspecs/windows_protocols/MS-RDPBCGR/5073f4ed-1e93-45e1-b039-6e30c385867c for clues, as these are the only options that are available. Might be some magic values need to be set so that these variable has any effect.
