### ISSUE TITLE
How to determine when connection is terminated in android client?

### ISSUE THREAD

**Issue by deputat007** [FreeRDP/FreeRDP#5254]
When connection is dropped the application freezes(or  it hangs on a black screen) and doesn't return to the main connection screen.
I want to handle when connection is dropped and try to reconnect or return to the main connection screen. Thanks.
In log I can see Prepare shutdown... but disconnection does not occur

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

Please use IRC or mailing list for such questions (and add a few more details. your description leaves too much room for interpretation)
