### ISSUE TITLE
Performance and user experience - raspberry pi 3 B+

### ISSUE THREAD

**Issue by skunkr** [FreeRDP/FreeRDP#5257]
Hello Everyone,
I am not reporting a bug, I just asking for some help based on your experience.
I am running FreeRDP version 2.0.0-dev5 (2693389a+debian) on small and pretty PI's  as a clients for a couple of  windows7/10  vms.
Performance is not very good,  and video streaming ( youtube ) is very laggy,  pretty much without any difference if it's connected to win7 or win10.
Bandwidth is not a problem, all the network devices have 1gb/s connections. 
Here is my running command:

/usr/bin/xfreerdp /cert-ignore /f /size:1024x768 /bpp:16 /gdi:hw /sec:tls /v:$server_ip +compression +fonts +decorations +auto-reconnect -menu-anims /workarea /sound:sys:alsa,format:1,quality:high /multimedia:sys:alsa /auto-reconnect-max-retries:0 /drive:usb,/media/pi/

(Pulseaudio does not working anymore for some reason,  so going with alsa for the minute) 

- Is there something I can do to improve overall performance for a good user desktop experience ?
- Should it be different options for win7/win10 ?
- Some users are using usb certificate tokens. What would it be the procedure to map them to the connected vm ?
I would really appreciate any help.
Thank you very much !

**Comment by akallabeth** [comment]
Please use the mailing list or irc for support.
You might want to repeat tests with /rfx /gfx:avc444 added and these modes enabled on the server.

**Comment by akallabeth** [comment]
And check your /buildconfig
