### ISSUE TITLE
RDP Client Error: Could note create connection

### ISSUE THREAD

**Issue by Gvaneck** [FreeRDP/FreeRDP#5259]
A HP Thin Client T630 with version FreeRDP 1.1.1-HP14.4 could not connect to  Windows 2012 Terminal Server Park. 

Warning xf_getWindowPrperty (332); Property298 does not exist
Error: protocol security negotiation or connection failure
check_host_and_port:getaddrinfo(rds,3389,0xa2)
=0(errno=0)
attempt_connect max 1000ms took 0ms
Starting xfreerdp to rds:3389
xfreerdp exit:pid0963, sig=0(none), status=0xc

Other Thin Clients with Windows do not have any problems
Ubuntu Laptop with Remina Remote Desktop client is running fine

**Comment by akallabeth** [comment]
Please try with our builds and provide the requested minimum information for your setup (just read the template for issues)
