### ISSUE TITLE
Can't download FreeRDP builds for windows

### ISSUE THREAD

**Issue by redbrain17** [FreeRDP/FreeRDP#5282]
Tried to download a pre-compiled setup file for windows. But there is a dead link.

I go to the main project page and click on the provided Download Button:

http://www.freerdp.com/ 

This redirects me to:

 https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

But here is nothing to download.

**Comment by akallabeth** [comment]
Thank you for reporting this.
Looks like @huitc and @se-al did some vandalizing.
Restored previous state.

**Comment by bmiklautz** [comment]
@redbrain17 thank you for the report.
