### ISSUE TITLE
rdpsnd channel doesn't produce audio sometimes

### ISSUE THREAD

**Issue by krandhir895** [FreeRDP/FreeRDP#5284]
Hi All,
 
I am running freerdp client on ubuntu 16.04 64-bit and accessing rdp server on window 7 64-bit.
I observed that sometimes freerdp client doesn't receive audio from rdp server.

I tried to look in code for this issue and found that rdpsnd thread waits forever on function **WaitForMultipleObjects.** and never breaks.
This function is in file channels/rdpsnd/client/rdpsnd_main.c
**const DWORD status = WaitForMultipleObjects(ARRAYSIZE(events), events, FALSE, INFINITE);**

I am using this command to start freerdp session.
**xfreerdp /v:192.168.5.95 /u:NCR /p:root123 /t:session-0 /sound:sys:pulse /microphone:sys:pulse /audio-mode:0 /bpp:32 /gfx-h264:AVC420 -clipboard /drive:hotplug,* /dynamic-resolution**

On running this command if audio receiving starts once, it will play forever.
If fails to receive audio then it will never play audio for that session ( due to continous waiting on WaitForMltipleObjects() funciton I think).

I am playing audio in gaana.com in chrome browser in the freerdp session.
I have downloaded and compiled freerdp code from following  link.
https://github.com/FreeRDP/FreeRDP/wiki/Compilation
I run freerdp from master branch and stable-1.0 branch as well, both showing same behavious for this issue.

Please help to fix this issue

Thanks and Regards,
Randhir

**Comment by akallabeth** [comment]
@krandhir895 well, if no data is received it will not be possible to process it...
in other words, are you receiving any sound related data from the server? If not it is not the clients fault not playing something that was not sent.

**Comment by krandhir895** [comment]
@akallabeth Thanks for quick reply.
I will test this issue with different rdp server machines and will update you later.

Regards,
Randhir

**Comment by krandhir895** [comment]
Hi @akallabeth ,

I have tested it further on windows10 and windows7 and found that with windows10 rdp host, freerdp is running perfectly with no audio issue. With windows7 rdp host, feerdp sometimes can't play audio.

Thanks and Regards,
Randhir

**Comment by akallabeth** [comment]
Ok, that might be a simple server issue.
Did you use disconnect/reconnect or did you log out of a session?
I can remember that with windows 7 there were audio issues when reconnecting (but that was also the case when using mstsc to connect)

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
