### ISSUE TITLE
keyboard shortcuts documentation

### ISSUE THREAD

**Issue by nelaaro** [FreeRDP/FreeRDP#5290]
**Is your feature request related to a problem? Please describe.**
I am looking for a list of the default keyboard short cuts and how to change them.
I want to do simple things like toggle full scree, grab and release input.
I can't find and documentation describing what these shortcuts are or how to change them. 

**Describe the solution you'd like**
In the user manual a section on the default keyboard shortcuts and possibly how to configure them.

**Describe alternatives you've considered**
I am going to start working through the code to see if I can Identify these so they can be added to the documentation.

**Additional context**

**Comment by nelaaro** [comment]
I found the following source files that would reference keyboard shortcuts.
Next step is to put this in to the wiki. 
I will work on that a bit later. 

https://github.com/FreeRDP/FreeRDP/blob/f002c7429b8e1ddb9198945ca329a4da1464b8dd/client/X11/xf_keyboard.c
https://github.com/FreeRDP/FreeRDP/tree/f002c7429b8e1ddb9198945ca329a4da1464b8dd/client

**Comment by akallabeth** [comment]
part of 3.x manpages for xfreerdp and sdl-freerdp
