### ISSUE TITLE
[freerdp-shadow-cli] Client disconnects immediately

### ISSUE THREAD

**Issue by oofnikj** [FreeRDP/FreeRDP#5302]
I'm trying to mirror my X11 session with `freerdp-shadow-cli -auth` running on Ubuntu 16.04 to Windows 10 using native client `mstsc.exe /v:<server:port>`. The client connects, the remote screen is visible for a split second, and then disconnects with the following error message on client:
>     Failed to reconnect to your remote session.
>     Please try to connect again

Log output from the host:

> [23:22:51:313] [15736:15737] [ERROR][com.winpr.thread] - Thread running, setting to detached state!
> [23:22:51:326] [15736:16021] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
> [23:22:51:326] [15736:16021] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:1
> [23:22:51:327] [15736:16021] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
> [23:22:51:358] [15736:16021] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
> [23:22:51:358] [15736:16021] [ERROR][com.freerdp.client.shadow] - Failed to check FreeRDP file descriptor
> [23:22:52:234] [15736:15737] [ERROR][com.winpr.thread] - Thread running, setting to detached state!
> [23:22:52:237] [15736:16023] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
> [23:22:52:237] [15736:16023] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:1
> [23:22:52:238] [15736:16023] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
> [23:22:52:244] [15736:16023] [INFO][com.freerdp.core.connection] - Accepted client: <client>
> [23:22:52:244] [15736:16023] [INFO][com.freerdp.core.connection] - Accepted channels:
> [23:22:52:244] [15736:16023] [INFO][com.freerdp.core.connection] -  rdpdr
> [23:22:52:244] [15736:16023] [INFO][com.freerdp.core.connection] -  rdpsnd
> [23:22:52:244] [15736:16023] [INFO][com.freerdp.core.connection] -  cliprdr
> [23:22:52:244] [15736:16023] [INFO][com.freerdp.core.connection] -  drdynvc
> [23:22:52:244] [15736:16023] [INFO][com.freerdp.core.gcc] - Active rdp encryption level: NONE
> [23:22:52:244] [15736:16023] [INFO][com.freerdp.core.gcc] - Selected rdp encryption method: NONE
> [23:22:52:256] [15736:16023] [INFO][com.freerdp.client.shadow] - Client from 10.0.0.132 is activated (1920x1200@32)
> [23:22:52:308] [15736:16023] [INFO][com.freerdp.client.shadow] - Gfx Pipeline Opened
> [23:22:52:380] [15736:16030] [ERROR][com.freerdp.channels.rdpgfx.server] - Unexpected gfx pdu end: Actual: 66, Expected: 94
> [libx264 @ 0x7f6ad4b3f0e0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
> [23:22:52:408] [15736:16029] [ERROR][com.freerdp.channels.audin.server] - WTSVirtualChannelQuery failed
> [libx264 @ 0x7f6ad4b3f0e0] profile High, level 5.0
> [23:22:52:484] [15736:16023] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
> [23:22:52:485] [15736:16023] [ERROR][com.freerdp.client.shadow] - Failed to check FreeRDP file descriptor
> [libx264 @ 0x7f6ad4b3f0e0] frame I:2     Avg QP:19.61  size: 66212
> [libx264 @ 0x7f6ad4b3f0e0] mb I  I16..4: 43.8% 41.1% 15.1%
> [libx264 @ 0x7f6ad4b3f0e0] final ratefactor: 23.54
> [libx264 @ 0x7f6ad4b3f0e0] 8x8 transform intra:41.1%
> [libx264 @ 0x7f6ad4b3f0e0] coded y,uvDC,uvAC intra: 15.8% 19.1% 14.6%
> [libx264 @ 0x7f6ad4b3f0e0] i16 v,h,dc,p: 68% 26%  5%  1%
> [libx264 @ 0x7f6ad4b3f0e0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 57% 11% 22%  2%  1%  1%  1%  1%  2%
> [libx264 @ 0x7f6ad4b3f0e0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 23% 20%  3%  3%  3%  4%  3%  3%
> [libx264 @ 0x7f6ad4b3f0e0] i8c dc,h,v,p: 80% 10%  9%  1%
> [libx264 @ 0x7f6ad4b3f0e0] kb/s:15891.00

Using version `2.0.0~git201903080944-0+remmina201903122327.r6e2cfef.d59a18ed~ubuntu16.04.1` from Remmina PPA.

Also tried compiling from git today (`6e2cfef5a3`) with same results.

Thanks for any help.

**Comment by akallabeth** [comment]
@oofnikj could you run the server with `export WLOG_LEVEL=debug` set? Would be nice to know which GFX command is responsible for this.

**Comment by oofnikj** [comment]
Sure:

> $ WLOG_LEVEL=debug freerdp-shadow-cli /port:3390 -auth


> [14:02:46:293] [25628:25628] [INFO][com.freerdp.server.shadow.x11] - X11 Extensions: XFixes: 1 Xinerama: 1 XDamage: 0 XShm: 0
> [14:02:46:299] [25628:25628] [INFO][com.freerdp.core.listener] - Listening on 0.0.0.0:3390
> [14:03:43:254] [25628:25629] [ERROR][com.winpr.thread] - Thread running, setting to detached state!
> [14:03:43:268] [25628:25725] [DEBUG][com.freerdp.core.nego] - RDP_NEG_REQ: RequestedProtocol: 0x0000000B
> [14:03:43:268] [25628:25725] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
> [14:03:43:268] [25628:25725] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:1
> [14:03:43:268] [25628:25725] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
> [14:03:43:296] [25628:25725] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
> [14:03:43:296] [25628:25725] [DEBUG][com.freerdp.core.transport] - transport_check_fds: transport_read_pdu() - -1
> [14:03:43:296] [25628:25725] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
> [14:03:43:296] [25628:25725] [ERROR][com.freerdp.client.shadow] - Failed to check FreeRDP file descriptor
> [14:03:44:171] [25628:25629] [ERROR][com.winpr.thread] - Thread running, setting to detached state!
> [14:03:44:188] [25628:25726] [DEBUG][com.freerdp.core.nego] - RDP_NEG_REQ: RequestedProtocol: 0x0000000B
> [14:03:44:188] [25628:25726] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
> [14:03:44:188] [25628:25726] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:1
> [14:03:44:188] [25628:25726] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
> [14:03:44:199] [25628:25726] [INFO][com.freerdp.core.connection] - Accepted client: <client>
> [14:03:44:199] [25628:25726] [INFO][com.freerdp.core.connection] - Accepted channels:
> [14:03:44:199] [25628:25726] [INFO][com.freerdp.core.connection] -  rdpdr
> [14:03:44:199] [25628:25726] [INFO][com.freerdp.core.connection] -  rdpsnd
> [14:03:44:199] [25628:25726] [INFO][com.freerdp.core.connection] -  cliprdr
> [14:03:44:199] [25628:25726] [INFO][com.freerdp.core.connection] -  drdynvc
> [14:03:44:199] [25628:25726] [INFO][com.freerdp.core.gcc] - Active rdp encryption level: NONE
> [14:03:44:199] [25628:25726] [INFO][com.freerdp.core.gcc] - Selected rdp encryption method: NONE
> [14:03:44:384] [25628:25726] [DEBUG][com.freerdp.core.info] - rdp client address: [10.0.0.132]
> [14:03:44:384] [25628:25726] [DEBUG][com.freerdp.core.info] - rdp client dir: [C:\WINDOWS\system32\mstscax.dll]
> [14:03:44:391] [25628:25726] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x1f size=37 channelId=1009)
> [14:03:44:391] [25628:25726] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x14 size=41 channelId=1009)
> [14:03:44:391] [25628:25726] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x14 size=41 channelId=1009)
> [14:03:44:392] [25628:25726] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x28 size=41 channelId=1009)
> [14:03:44:392] [25628:25726] [INFO][com.freerdp.client.shadow] - Client from 10.0.0.132 is activated (1920x1200@32)
> [14:03:44:446] [25628:25728] [DEBUG][com.freerdp.channels.rdpsnd.server] - Client requested sound quality: 0x0000
> [14:03:44:453] [25628:25726] [INFO][com.freerdp.client.shadow] - Gfx Pipeline Opened
> [14:03:44:548] [25628:25734] [DEBUG][com.freerdp.channels.rdpgfx.server] - cmdId: RDPGFX_CMDID_CAPSADVERTISE (0x0012) flags: 0x0000 pduLength: 94
> [14:03:44:548] [25628:25734] [ERROR][com.freerdp.channels.rdpgfx.server] - Unexpected gfx pdu end: Actual: 66, Expected: 94
> [14:03:44:554] [25628:25733] [ERROR][com.freerdp.channels.audin.server] - WTSVirtualChannelQuery failed
> [libx264 @ 0x7fbd4890a100] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 AVX2 LZCNT BMI2
> [libx264 @ 0x7fbd4890a100] profile High, level 5.0
> [14:03:44:637] [25628:25726] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
> [14:03:44:637] [25628:25726] [DEBUG][com.freerdp.core.transport] - transport_check_fds: transport_read_pdu() - -1
> [14:03:44:637] [25628:25726] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
> [14:03:44:637] [25628:25726] [ERROR][com.freerdp.client.shadow] - Failed to check FreeRDP file descriptor
> [libx264 @ 0x7fbd4890a100] frame I:2     Avg QP: 8.93  size: 21615
> [libx264 @ 0x7fbd4890a100] mb I  I16..4: 66.2% 30.2%  3.6%
> [libx264 @ 0x7fbd4890a100] final ratefactor: 15.46
> [libx264 @ 0x7fbd4890a100] 8x8 transform intra:30.2%
> [libx264 @ 0x7fbd4890a100] coded y,uvDC,uvAC intra: 2.4% 3.5% 3.3%
> [libx264 @ 0x7fbd4890a100] i16 v,h,dc,p: 87%  8%  5%  0%
> [libx264 @ 0x7fbd4890a100] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 96%  2%  2%  0%  0%  0%  0%  0%  0%
> [libx264 @ 0x7fbd4890a100] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 26% 33% 26%  2%  3%  3%  2%  3%  3%
> [libx264 @ 0x7fbd4890a100] i8c dc,h,v,p: 92%  6%  2%  0%
> [libx264 @ 0x7fbd4890a100] kb/s:5187.60
>

**Comment by oofnikj** [comment]
Tested PR by @m4ntis and it works! Client is able to hold connection. Thanks!

Possibly unrelated issue - image quality is quite a lot worse with AVC444 mode vs. AVC420 (compression artifacts, text is fuzzy):
![artifact](https://user-images.githubusercontent.com/25017173/54391209-e1e96780-46ac-11e9-9ac3-8f6432d17d4d.png)


If I understand correctly Windows 10 RDP client removed support for AVC420.
Any workaround to this? Maybe disabling AVC support when building the server to force client to use legacy RDP mode?
