### ISSUE TITLE
Issues using flatpak-builder. cannot create regular file '/usr/lib/systemd/system/pcscd.service': Read-only file system

### ISSUE THREAD

**Issue by Rossosaurus** [FreeRDP/FreeRDP#5305]
I'm trying to compile freerdp but I can't run `flatpak-builder <build dir> packaging/flatpak/com.freerdp.FreeRDP.json` without it spewing errors.

`/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/pcscd.service': Read-only file system`
`/usr/bin/install: cannot create regular file '/usr/lib/systemd/system/pcscd.socket': Read-only file system`
`make[2]: *** [Makefile:360: install-systemdsystemunitDATA] Error 1`
`make[2]: Leaving directory '/run/build/pcsc/etc'`
`make[1]: *** [Makefile:432: install-am] Error 2`
`make[1]: Leaving directory '/run/build/pcsc/etc'`
`make: *** [Makefile:447: install-recursive] Error 1`
`Error: module pcsc: Child process exited with code 2`

I'm following the wiki page on compiling on linux. I was getting the same errors with /usr/lib/systemd/system/udev-control.socket and some other udev stuff in systemd/system/ but I fixed that by downloading and replacing shared-modules with the latest version from github.

**Comment by caio-vinicius** [comment]
Same here, can't compile from source using flatpak

**Comment by akallabeth** [comment]
@caio-vinicius works here on `ubuntu/debian/fedora` with `master` branch. check that you start with a clean build directory.
