### ISSUE TITLE
disconnect in logon screen after 10 seconds

### ISSUE THREAD

**Issue by andicheesi** [FreeRDP/FreeRDP#5312]
*  the steps to reproduce the bug:
     Try to log on with wrong password
     And windows pop up with "other user" "The user name or password is incorrect. Try again"
     Waiting for about 10 seconds and xfreerdp disconnects

  * command line you have used
 xfreerdp /u:Messe /p:rtrtrt /gfx /sec:tls /v:IPC6641
  * to what system did you connect to? (win8, 2008, ..)
Microsoft Windows 10 Enterprise 2016 LTSB
  * what did you expect to happen?
xfreerdp should not disconnect
  * what actually happened?
xfreerdp disconnects after 10 seconds
  * freerdp version (e.g. xfreerdp --version) or package version or git commit
current master from 2019/03/18
  * freerdp configuration (e.g. xfreerdp --buildconfig)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER=ON WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_GTK=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NEON=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_RDPDR=ON WITH_RDPSND_DSOUND=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_TSMF=ON WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WIN8=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -m32  -ggdb -Wa,--noexecstack  -Wl,-z,noexecstack -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 4.8.5
Target architecture: x86
  * operating System, architecture, distribution e.g. linux, amd64, debian
linux64 with multiarch
  * if you built it yourself add some notes which branch you have used, also your cmake parameters can help
-DWITH_GTK=ON \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_TSMF=ON \
    -DWITH_GSTREAMER_1_0=ON \
    -DWITH_SERVER=ON \
    -DWITH_SSE2=ON \
    -DWITH_RDPDR=ON \
    -DWITH_JPEG=ON \
    -DWITH_WIN8=ON \
    -DWITH_FFMPEG=OFF \
    -DWITH_IPP=OFF \
    -DWITH_NEON=OFF \
    -DWITH_GSTREAMER=ON \
    -DBUILTIN_CHANNELS=ON \
    -DWITH_CHANNELS=ON \
    -DWITH_LIBSYSTEMD=OFF \
    -DWITH_RDPSND_DSOUND=ON \
    -DWITH_XRANDR=ON  \
    -DWITH_XV=ON \
    -DWITH_XRENDER=ON \
    -DWITH_XEXT=ON \
    -DWITH_XFIXES=ON \
    -DCHANNEL_URBDRC_CLIENT=ON \
    -DCHANNEL_URBDRC=ON
  * extra information helping us to find the bug

* output xfreerdp
[15:13:16:327] [11117:11118] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[15:13:16:327] [11117:11118] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[15:13:16:327] [11117:11118] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[15:13:16:327] [11117:11118] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[15:13:16:575] [11117:11118] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[15:13:16:575] [11117:11118] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[15:13:16:596] [11117:11118] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[15:13:16:606] [11117:11118] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[15:13:16:608] [11117:11157] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
[15:13:48:531] [11117:11118] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off their session on the server.
* output Windows EventViewer in from oldest newest
Log Name:      Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational
Source:        Microsoft-Windows-RemoteDesktopServices-RdpCoreTS
Date:          3/18/2019 3:12:22 PM
Event ID:      228
Task Category: RemoteFX module
Level:         Warning
Keywords:      
User:          NETWORK SERVICE
Computer:      IPC6641
Description:
Disconnect trace:CUMRDPConnection Disconnect trace:'calling spGfxPlugin->PreDisconnect()' in CUMRDPConnection::PreDisconnect at 4477 err=[0xc], Error code:0xC

* Output WIndows in Eventviewer
 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-RemoteDesktopServices-RdpCoreTS" Guid="{1139C61B-B549-4251-8ED3-27250A1EDEC8}" />
    <EventID>228</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>4</Task>
    <Opcode>19</Opcode>
    <Keywords>0x4000000000000000</Keywords>
    <TimeCreated SystemTime="2019-03-18T14:12:22.194937400Z" />
    <EventRecordID>29595</EventRecordID>
    <Correlation ActivityID="{F4209DE4-ACA8-4DD7-BE3F-0A5CF0140000}" />
    <Execution ProcessID="584" ThreadID="1556" />
    <Channel>Microsoft-Windows-RemoteDesktopServices-RdpCoreTS/Operational</Channel>
    <Computer>IPC6641</Computer>
    <Security UserID="S-1-5-20" />
  </System>
  <EventData>
    <Data Name="ComponentName">CUMRDPConnection</Data>
    <Data Name="Message">Disconnect trace:'calling spGfxPlugin-&gt;PreDisconnect()' in CUMRDPConnection::PreDisconnect at 4477 err=[0xc]</Data>
    <Data Name="ErrorCode">12</Data>
  </EventData>
</Event>

*RDP Windows settings for timeout 
  all timeouts are explicitely set to "never"

**Comment by akallabeth** [comment]
Server configuration, nothing we can do here.
