### ISSUE TITLE
Request for release of 2.0.0-rc5

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#5316]
It would be great to see another RC before finishing 2.0.0.

**Comment by akallabeth** [comment]
have a lot of pull requests pending, but it looks like nobody has time for reviewing them :/

**Comment by bmiklautz** [comment]
@weberhofer I sincerely hope we can get 2.0.0 out of the door soon. As @akallabeth mentioned there are basically some PRs that needs merging before the release. Hope we can get around that soon.

**Comment by weberhofer** [comment]
It would really be great to see a new version, no matter if RC or release. Hope somebody has time to review. I really like freerdp!

**Comment by bmiklautz** [comment]
Tracking this under #5608
