### ISSUE TITLE
client closes when a remoteapp window disappears

### ISSUE THREAD

**Issue by garbb** [FreeRDP/FreeRDP#5321]
**Describe the bug**
FreeRDP client terminates during connection to remoteapp on RDP server

**To Reproduce**
Connect to a remoteapp on an RDP server with
`wfreerdp.exe /v:192.168.0.25 /drives /app:"||APPNAME"`
Prompt for credentials, input credentials
Wait for connection
Windows "welcome message appears in window"
![image](https://user-images.githubusercontent.com/4453789/55520739-74d54c00-5632-11e9-859e-1201e2f0c7c7.png)

Because the username I am using for logon does not currently have a profile on this server, the windows server creates one and the "personalizing settings" small window briefly appears and then disappears
![image](https://user-images.githubusercontent.com/4453789/55520769-97676500-5632-11e9-82aa-9f72abb0b8af.png)
Immediately after the "personalizing settings" window disappears, all freeRDP client windows disappear and the freeRDP client process terminates.

**Expected behavior**
In the regular windows mstsc client, after the "personalizing settings" window disappears, there is a brief delay of a few seconds and then the window for the remoteapp appears. This is the behavior I would expect from freeRDP.

Note that I have tried connecting to an identical server with an identical remoteapp on which my username **does** already have a profile and the "personalizing settings" window does not appear and the remoteapp window appears as expected.
My guess is that the behavior of the freeRDP client is that it is seeing one single window (the "personalizing settings" window) and then when this window disappears it assumes that the remoteapp has closed and ends the session. May I suggest that the behavior of freeRDP be changed when connecting to a remoteapp such that it is the same as the mstsc client which will not end the session until a remoteapp window or tray icon does not exist for 20 seconds.
See:
https://cloudblogs.microsoft.com/enterprisemobility/2007/09/27/terminal-services-remoteapp-session-termination-logic/

** Application details
* Version of FreeRDP
win64,vs2013 (Mar 29, 2019 2:45:08 AM) build #611 from
https://ci.freerdp.com/job/freerdp-nightly-windows/lastBuild/arch=win64,label=vs2013/
* Command line used
`wfreerdp.exe /v:192.168.0.25 /drives /app:"||APPNAME"`
* OS version connecting to
windows 7
* If available the log output from a run with `/log-level:trace`
used this command line param for the windows build and I am not seeing any logging in the console??

**Desktop (please complete the following information):**
Windows 7 x64

**Comment by akallabeth** [comment]
Did you allow remoteapp and the specified app for this user?

**Comment by akallabeth** [comment]
tested against windows 7 with the appropriate settings and it is working with `2.0.0-dev5 (52bce4745)`

**Comment by garbb** [comment]
I know this is closed, but I wanted to answer the question:

> Did you allow remoteapp and the specified app for this user?

Yes I tried connecting to the same server with the same user and the same remoteapp with the windows builtin mstsc.exe client and it worked, so yes the specified user has access to the remoteapp.

**Comment by garbb** [comment]
I know this is closed, but I wanted to answer the question:

> Did you allow remoteapp and the specified app for this user?

Yes I tried connecting to the same server with the same user and the same remoteapp with the windows builtin mstsc.exe client and it worked, so yes the specified user has access to the remoteapp.
