### ISSUE TITLE
[win] -grab-keyboard not supported

### ISSUE THREAD

**Issue by kavanst** [FreeRDP/FreeRDP#5324]
After a successful login, the keyboard is stuck in the remote desktop window until the mouse click inside the remote desktop window and then outside. Is it possible to disable this as the user may not intend for the keyboard to be in the new Remote Desktop window until the mouse click inside. For my scenario, I am running a script to open two FreeRDP windows, so two log in prompts will appear. After the first log in, naturally the user will want to type on the second log in prompt, however the keyboard is now stuck in the first RDP window.

This is using the wfreerdp.exe nightly build downloaded on 13 Mar 2019.

Client is running Windows 10 Professional. The RDP server is running Windows Server 2016.

**Comment by akallabeth** [comment]
Please use the mailing list or IRC for support questions.
Keyboard behaviour is configurable via command line switches.

**Comment by MahmutYaman** [comment]
I have the same issue. This is an important bug. Please fix it :(

**Comment by krusli** [comment]
I also have the same issue. Tested using build 980 (https://ci.freerdp.com/job/freerdp-nightly-windows/980/) built on 7 Sep 2021. #6265 also seems to be related.

Client and server are both running Windows 10 Pro.

**Comment by akallabeth** [comment]
windows client will be replaced with `sdl-freerdp`. that one supports keyboard grab
