### ISSUE TITLE
Buttons on floating toolbar do not work

### ISSUE THREAD

**Issue by cixonline** [FreeRDP/FreeRDP#5326]
**Describe the bug**
Using Arch Linux as the client and installing the freerdp package 2.0.0.rc4, I connect to my Windows 10 desktop using username and password as login. This works fine and the desktop appears. However the floating blue toolbar at the top with the pin, IP address, minimize, restore and close buttons do not work at all. The only way to disconnect is to use the Disconnect option from the Windows 10 Start menu.

**To Reproduce**
1. Run xfreerdp and connect to a Windows 10 machine. I used the following options although they make no difference to the issue:

xfreerdp /v:<ipaddress> /w:1680 /h:1050 /f /u:<username> /p:<password> -wallpaper -themes /printer /clipboard

2. When the Windows 10 desktop appears, attempt to close by clicking the 'X' on the right of the floating toolbar at the top.

**Expected behavior**
XFreeRdp to disconnect.

** Application details
* Version of FreeRDP - 2.0.0.rc4
* Command line used: see above
* output of `/buildconfig`
* OS version connecting to: Windows 10 v1809
* If available the log output from a run with `/log-level:trace` 

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser [e.g. chrome, safari] - None
 - Version [e.g. 22]  4.20.13-arch1-1-ARCH

**Comment by akallabeth** [comment]
@cixonline please try our nightly builds, this was already addressed.

**Comment by cixonline** [comment]
Tried with version 2.0.0-dev5 (e0d60a031) and the same issue is present. xfreerdp --version reports the dev5 version so I'm sure I'm running the latest.

The source was built using https://aur.archlinux.org/packages/freerdp-git/ as there are no Arch Linux nightly builds listed here.

**Comment by akallabeth** [comment]
@cixonline tried it on fedora 29 and debian 10 today, working as expected. Are you maybe missing some x11 dev package? Could you check /buildconfig?
