### ISSUE TITLE
For OldLicenseBehavior, don't call saveCal since we never call loadCal

### ISSUE THREAD

**Issue by byteboon** [FreeRDP/FreeRDP#5329]
license_answer_license_request() will not call loadCal() if OldLicenseBehaviour is true, but license_read_new_or_upgrade_license_packet() will always call saveCal() even if the paths have not be set up correctly -- and therefore fail to save and bail the connection. No need to save if you never load.  

I'm not sure if failure to save should be fatal, since failure to load isn't. I'll leave that question to someone else.

**Comment by hardening** [comment]
makes sense

**Comment by akallabeth** [comment]
Fixed with #5330
