### ISSUE TITLE
How to create freeRDP.xcodeproj for iOS 12.1 & Xcode 10.1

### ISSUE THREAD

**Issue by cogphone** [FreeRDP/FreeRDP#5332]
Hi,

I am try to compile FreeRDP from master with IOS. but missing  FreeRDP.xcodeproj project file .

how to solve it?, please explain step by step?.

**Comment by akallabeth** [comment]
docs/README.ios
For further help please use the mailing list or IRC, this is an issue tracker not a support forum.
