### ISSUE TITLE
cursor turns into a black box when enable cursor shadow in windows 2012 and 2016

### ISSUE THREAD

**Issue by buptcaicai** [FreeRDP/FreeRDP#5334]
When cursor shadow is enabled in windows 2012 and 2016, the cursor turns to a black box.  I tried to disable cursor shadow in xrdp-neutrinordp.c, and it did not help.

instance->settings->performance_flags = PERF_DISABLE_FULLWINDOWDRAG | PERF_DISABLE_MENUANIMATIONS | PERF_DISABLE_THEMING | PERF_DISABLE_CURSOR_SHADOW;

**Comment by akallabeth** [comment]
Please add the required information requested in the issue template.
Until such data has been added this issue will stay closed.
