### ISSUE TITLE
mouse cursor turn black box when "pointer shadow" is enabled in win2012 and 2016

### ISSUE THREAD

**Issue by buptcaicai** [FreeRDP/FreeRDP#5337]
I used NeutrinoRDP and freerdp to connect windows 2012 server. When I enabled pointer shadow, the cursor turn to a black box. When I disabled pointer shadow, the cursor turn normal.

Open Mouse Properties in Control Panel, click "Enable pointer shadow" and apply. The cursor immidiately turns a black box. If untick the "Enable pointer shadow", the cursor will turn normal.

Windows 2016 server has the same issue.

I tried enable the "PERF_DISABLE_CURSOR_SHADOW" flag in instance->settings->performance_flags in xrdp-neutrinordp.c, and it did not help.

![screenShotSmall](https://user-images.githubusercontent.com/49482868/55957818-5d3b3a80-5ca6-11e9-9599-16d31b9e66bd.jpg)

**Comment by akallabeth** [comment]
Same as #5334.
Please add the information requested by the issue template.
Since this is your second attempt, the missing and most important information is WHICH version of FREERDP are you using? (`/buildconfig` just as requested by the issue template)

**Comment by akallabeth** [comment]
Additionally: does it work with our nightly builds?

**Comment by akallabeth** [comment]
Just checked against windows 8.1 and 10, no such issue with current nightly builds.
If it is reproducible please provide at least:
* Version you tested with (/buildconfig)
* Command line (complete)
* Remote systems

**Comment by buptcaicai** [comment]
I was using FreeRDP 0.9.1, and NeutrinoRDP, which a fork of FreeRDP 1.0.1. We also tested the lastest version and it still has the same problem. The command line is ./xrdp -nd

I think windows 8.1 and 10 is fine to me too. It only happens with windows 2012 and 2016.

**Comment by akallabeth** [comment]
Sorry, that are versions we have not much to do with.
You might try our nightly builds (upcoming 2.0 version) https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds
Xrdp is a different project though ;)
