### ISSUE TITLE
Random session disconnects FreeRDP 2.0 (6be3ba4) when using RDGW 2012R2 connecting to 2016TS RDS cluster

### ISSUE THREAD

**Issue by monkeytreehosting** [FreeRDP/FreeRDP#5344]
I've seen similar issues in some old threads, however I'm seeing what I believe to be this error but with 2012R2 Gateways; this seems to be very easy to replicate, however I can only find a couple of others having reported it online.

Setup:

OS: Ubuntu 18.04.2 LTS
Connection: Remmina via official PPA

OS: NoTouch Desktop (tested on both k413 on HP T520 Thin Client and k419 on Rpi3B+)
Connection: FreeRDP version 2.0 (6be3ba4)

Connecting to:

2016 Windows TS cluster, via 2012R2 Gateway Cluster
I have only seen this disconnecting scenario since testing these linux based clients, both of which use FreeRDP. The below is from the error shown when the session dies in NoTouch Desktop using FreeRDP:

[ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer.
[ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[INFO][com.freerdp.client.common] - Network disconnect!
FreeRDP Exitcode: 131
ErrorLevel: 131

When Remmina has issues, it reattempts connection and comes back in, however this happens about 5-10 times a day; sometimes the session just terminates.

To cause the disconnection, and thus replicate, I initiate a connection and then leave it with no input for a period of time; I've seen rare disconnects within 2mins, but generally see the disconnect following either 10-12mins, or 20-25mins. If input is given to the session, the connection is kept active and I have not experienced disconnect while actively working, however some other test clients have reported disconnects while typing away.

To confirm, we've been connecting to this hosted platform for 4-years without issue by using either Windows or Mac clients without issue.

I have just found another user, using remmina build with FreeRDP, who is experiencing the same issue too: https://www.reddit.com/r/Remmina/comments/bb5qh5/remmina_closes_connection_randomly/

I have also searched through the GitHub issues and only found a couple of examples, all referencing 2008 gateways, however a common theme here seems to be the RDP gateway.
#5048 

We're currently in the process of implementing RDGW 2019, however this will be about a month before complete and able to test.

Any help, or advice would be greatly appreciated!

Thanks,

David

**Comment by akallabeth** [comment]
Could you attach the command line you're using?
Remmina uses the same library, so to have similar behaviour you need to activate the same switches.

As for the issue itself, try to activate heartbeat, sounds like the gateway is configured to discard idle connections. (Network:auto might help too)

**Comment by monkeytreehosting** [comment]
Thanks for the response; I'm currently using NoTouch OS so I'm not aware of how to export the command line from there? However I'm attaching screenshots for you if that's ok?

How would I go about enabling heartbeat?

In the meantime, yes the gateway is configured to the following session state changes:
• Active to Idle - 2mins of inactivity
• Idle to Disconnected - 3hrs of inactivity
• Disconnected to Signed Out - 3hrs of inactivity

**Comment by monkeytreehosting** [comment]
*Note, I have emailed Stratodesk support asking how to activate heartbeat; I have also asked how to extract the exact command string so I can inspect and also paste it here!

**Comment by monkeytreehosting** [comment]
<img width="1300" alt="Screenshot 2019-04-14 at 17 39 14" src="https://user-images.githubusercontent.com/10866383/56096183-b8ef0900-5edc-11e9-9492-92b9536751ed.png">
<img width="1304" alt="Screenshot 2019-04-14 at 17 39 27" src="https://user-images.githubusercontent.com/10866383/56096184-b8ef0900-5edc-11e9-9ee3-22a3ef2a2db2.png">
<img width="1302" alt="Screenshot 2019-04-14 at 17 39 39" src="https://user-images.githubusercontent.com/10866383/56096185-b9879f80-5edc-11e9-8e2a-a0676f40a5b2.png">
<img width="1291" alt="Screenshot 2019-04-14 at 17 39 52" src="https://user-images.githubusercontent.com/10866383/56096186-b9879f80-5edc-11e9-9ef7-f4eaebb36b31.png">
<img width="1293" alt="Screenshot 2019-04-14 at 17 40 05" src="https://user-images.githubusercontent.com/10866383/56096188-b9879f80-5edc-11e9-8c4c-f6a3cbebce73.png">
<img width="1297" alt="Screenshot 2019-04-14 at 17 40 16" src="https://user-images.githubusercontent.com/10866383/56096189-b9879f80-5edc-11e9-80b1-65fff4a93a65.png">
<img width="1300" alt="Screenshot 2019-04-14 at 17 40 26" src="https://user-images.githubusercontent.com/10866383/56096190-b9879f80-5edc-11e9-8138-36e94fd9f10b.png">

**Comment by monkeytreehosting** [comment]
I've just tried with +heartbeat and unfortunately it's disconnected again after 14mins

Without heartbeat enabled, I have had a couple of 1hr+ sessions with zero input, however they also end in disconnection.

All disconnections shown with the same error as mentioned above

**Comment by monkeytreehosting** [comment]
Testing now with the addition of:

+heartbeat +auto-reconnect /network:auto

**Comment by monkeytreehosting** [comment]
After enabling heartbeat auto-reconnect and network auto, this has stabilized the connection, however seemingly hidden the issue?

Screen photos of the error logs on disconnection show the disconnections are still happening, randomly, but now being reconnected in the background
![Original connection](https://user-images.githubusercontent.com/10866383/56111214-1a4fc000-5f4f-11e9-934e-aefbf287e10c.jpeg)
![test box1 - +heartbeat +auto-reconnect networkauto ](https://user-images.githubusercontent.com/10866383/56111215-1ae85680-5f4f-11e9-9b73-129c1df17646.jpeg)
![test box2 - +heartbeat +auto-reconnect networkauto ](https://user-images.githubusercontent.com/10866383/56111216-1ae85680-5f4f-11e9-8bab-bfb8339cf893.jpeg)

While this is a great step forward, (thank you @akallabeth for reminding me I could add my own switches) do we have any idea why this is occurring?

I don't see this at all with windows/mac clients, however this could simply be hidden and not logged as clearly as FreeRDP?

**Comment by AndrK189100** [comment]
I have same problem(wrote about this on reddit).
All 29 machines have this problem with last version of Remmina. "Clean" FreeRDP works fine.

Server: Windows Server 2016(all updates installed)
Client: Linux Mint 19.1(aka Ubuntu 18.04). Remmina - 1.3.4 (git n/a)
Direct connect to server, without gateway

Log:
[ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer.

remmina --full-version
==============
NAME TYPE DESCRIPTION PLUGIN AND LIBRARY VERSION

RDP Protocol RDP - Remote Desktop Protocol RDP Plugin: 1.3.4 (git n/a), Compiled with FreeRDP lib: 2.0.0-dev5 (n/a), Running with FreeRDP lib: 2.0.0-dev (rev n/a), H264: No

RDPF File RDP - RDP File Handler RDP Plugin: 1.3.4 (git n/a), Compiled with FreeRDP lib: 2.0.0-dev5 (n/a), Running with FreeRDP lib: 2.0.0-dev (rev n/a), H264: No

RDPS Preference RDP - Preferences RDP Plugin: 1.3.4 (git n/a), Compiled with FreeRDP lib: 2.0.0-dev5 (n/a), Running with FreeRDP lib: 2.0.0-dev (rev n/a), H264: No

SFTP Protocol SFTP - Secure File Transfer 1.3.4

SSH Protocol SSH - Secure Shell 1.3.4

Build configuration: HAVE_ARPA_INET_H=1 HAVE_ERRNO_H=1 HAVE_FCNTL_H=1 HAVE_NETDB_H=1 HAVE_NETINET_IN_H=1 HAVE_NETINET_TCP_H=1 HAVE_SYS_SOCKET_H=1 HAVE_SYS_UN_H=1 HAVE_TERMIOS_H=1 HAVE_UNISTD_H=1 WITH_APPINDICATOR=ON WITH_AVAHI=ON WITH_FREERDP=ON WITH_GCRYPT=ON WITH_GETTEXT=ON WITH_IPP=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSECRET=ON WITH_LIBSSH=ON WITH_LIBVNCSERVER=ON WITH_MANPAGES=ON WITH_SPICE=ON WITH_SSE2=ON WITH_TELEPATHY=ON WITH_TRANSLATIONS=ON WITH_VTE=ON

Build type: None

CFLAGS: -g -O2 -fdebug-prefix-map=/build/remmina-XEhQ1f/remmina-1.3.4+ppa201903130044.r494903e.d3617f3c~ubuntu18.04.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -g

Compiler: GNU, 7.3.0

Target architecture: x64
=====================

connection settings

![1](https://user-images.githubusercontent.com/49432572/56189650-2613b300-6031-11e9-8eb8-8a4216224330.jpg)

![2](https://user-images.githubusercontent.com/49432572/56189658-2ad86700-6031-11e9-8549-f849d32e27c6.jpg)

![3](https://user-images.githubusercontent.com/49432572/56189669-2f048480-6031-11e9-9545-ad57c13f4cb8.jpg)
