### ISSUE TITLE
wfreerdp does not work with macro or hotkey programs

### ISSUE THREAD

**Issue by user999430212** [FreeRDP/FreeRDP#5346]
Macro programs on windows are very popular like typeitin and autohotkey. Both feature hotkeys to trigger scripts as well as "hotstrings". The former, for example would be hitting ctrl-F1 to type out "hello world". The latter would be if you defined the characters "hw" as "hello world" it would expand them when it sees them typed.

Neither hotkeys nor hotstrings work in wfreerdp.

**To Reproduce**
Neither hotkeys nor hotstrings work in wfreerdp.

**Expected behavior**
Hotkeys and hotstrings should work, or there should be a command line option to enable them.

It seems to exist on all versions of wfreerdp that I have tried.

**Comment by user999430212** [comment]
For anyone who is interested, to fix this you need to update wf_event.c function wf_ll_kbd_proc to change each "return 1" to "return 0".
Is there a reason for this behavior or can we put this into the main build?

**Comment by connected201** [comment]
hi, error in program persist, i cannot use macro expert, or run this program using vbs script, only cmd!

**Comment by akallabeth** [comment]
@user999430212 sorry for the late reply, looks like I´ve missed this one.
Yes, pull requests fixing windows client behaviour are very welcome.
I think https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-setwindowshookexa and https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644975(v=vs.85) is describing how it should be implemented.

**Comment by connected201** [comment]
hi @user999430212, can you share compiled version? i have same trouble with hotkeys, best regards
