### ISSUE TITLE
Trapezoid top menu gone in debian package

### ISSUE THREAD

**Issue by michaelschefczyk** [FreeRDP/FreeRDP#5349]
Dear All,

In the latest freerdp2-x11 debian stretch-backports package (2.0.0), the trapezoid top menu of the RDP desktop is suddenly gone. It used to be there for a few years and I found it very helpful. Very likely, it can be toggled via the configuration. However, I am unable to find the right syntax. I am even unable to find the right name for the blue trapezoid "thing" which is in the top middle of typical windows RDP screens. It would be good, if that was clearly mentioned in the documentation - at least if my assumption is correct that the user does have control.

If this is a bug beyond mere documentation, I will specify the exact debian package version where this did occur.

Regards,

Michael

**Comment by bmiklautz** [comment]
@michaelschefczyk I think the feature you are looking for is "floatbar".
From the help:
```
    /floatbar[:sticky:[on|off],default:[visible|hidden],show:
               [always|fullscreen||window]]
                                      floatbar is disabled by default (when
                                      enabled defaults to sticky in fullscreen
                                      mode)
```
