### ISSUE TITLE
Unable to use H264 (AVC420 or AVC444) with resolution higher than 2048x2048

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#5351]
Discovered this while using the FreeRDP library on a project, but was able to reproduce on the FreeRDP example client for Windows (wfreerdp.exe).

Using latest FreeRDP compiled from Git.

Client is running on Windows 10, server is Windows Server 2012 R2.

When using the client with options "/gfx:AVC420" or "/gfx:AVC444", I can only connect to the server using a resolution lower than 2048x2048. If I use a resolution with either dimension (width or height) 1 or 2 pixels above, I get an error a few seconds after connecting. Using only "/gfx" works fine, so it's related to the "GfxH264" setting, not to "SupportGraphicsPipeline".

The error I get is this:

```
...
[15:21:54:444] [2208:00002b70] [DEBUG][com.freerdp.core.rdp] - recv Set Error Info Data PDU (0x2F), length: 22
[15:21:54:489] [2208:00002b70] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 2: No such file or directory
[15:21:54:489] [2208:00002b70] [DEBUG][com.freerdp.core.transport] - transport_check_fds: transport_read_pdu() - -1
[15:21:54:489] [2208:00002b70] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
[15:21:54:489] [2208:00002b70] [DEBUG][com.freerdp.core] - rdp_check_fds() - -1
[15:21:54:489] [2208:00002b70] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[15:21:54:489] [2208:00002b70] [INFO][com.freerdp.client.common] - Network disconnect!
[15:21:54:489] [2208:00002b70] [ERROR][com.freerdp.client.windows] - Failed to check FreeRDP file descriptor
[15:21:54:489] [2208:00000fa4] [DEBUG][com.freerdp.channels.rdpsnd.client] - Device already closed
[15:21:54:490] [2208:00001848] [DEBUG][com.freerdp.channels.rdpgfx.client] - OnClose
[15:21:54:499] [2208:00001848] [DEBUG][com.freerdp.channels.drdynvc.client] - close_channel_iface: id=6
[15:21:54:500] [2208:00002b70] [DEBUG][com.freerdp.channels.rdpgfx.client] - Terminated
[15:21:54:541] [2208:00002b70] [DEBUG][com.freerdp.client.windows] - Main thread exited with 0
[15:21:54:549] [2208:000049e0] [DEBUG][com.freerdp.client.windows] - Keyboard thread exited.
```

I can test with other options, if needed, and I can provide additional logs. However, I think this should be easy to reproduce.

**Comment by vscfreire** [comment]
It doesn't seem to happen when connecting to a Windows Server 2016 server. I can use higher resolutions with the "/gfx:AVC420", for example, with no problems.

**Comment by hardening** [comment]
IIRC the spec give some limitations on the maximum resolution...

**Comment by vscfreire** [comment]
According to [this TechNet article](https://social.technet.microsoft.com/wiki/contents/articles/31983.remote-desktop-protocol-maximum-supported-resolutions.aspx), ever since Server 2012 that resolutions up to 8192x8192 are supported (for each monitor, in a multi-monitor scenario you can go above that).

Additionally, this problem is not present when not using H.264 modes, even if the Graphics Pipeline is enabled. So it appears to be something specific to H.264 modes (AVC420/AVC444). Also, this not happening on Windows Server 2016 must have some meaning...

Also, a quick read of MS-RDPBCGR and MS-RDPEGFX finds no mention of any resolution limits...

**Comment by akallabeth** [comment]
@vscfreire your h264 decoder may impose additional limits.
Check which protocol version (gfx) is used with your server. Then you know the limits as well.

**Comment by akallabeth** [comment]
@vscfreire your connection log with `/log-level:debug` and `/buildconfig` might give a hint which decoder is used.

**Comment by vscfreire** [comment]
The client/library is compiled with WITH_MEDIA_FOUNDATION=ON. That's what's being used for H.264 decoding, right? libx264 is not implemented yet, and I'm having trouble compiling OpenH264 for MSVC (which is the compiler I'm using).

The weird thing is that "/gfx:AVC420" works fine on Windows Server 2016, with any resolution, so it looks like the decoder supports it. Only when connecting to Windows Server 2012 R2 with a resolution above 2048 does it fail.

On the server side, the logs on Event Viewer appear exactly the same, when connecting with "/gfx:AVC420", using a resolution below or above 2048, but above (eg. 2052) it gives these errors at some point:
`RDP_GFX: An error was encountered when transitioning from PipeStateEncoding in response to PipeEventOnProtocolClosedFailed (error code 0x8000000A).`
`RDP_GFX: An error was encountered when transitioning from PipeStateError in response to PipeEventOnError (error code 0x8000000A).`
`The RDP protocol component WD detected an error (303) in the protocol stream and the client was disconnected.`

**Comment by akallabeth** [comment]
@vscfreire there is no support for avc420 for that os and it falls back to rfx codec.
Try openh264 (you just need to set OPENH264_ROOT_DIR to the path to lib and include base dir)
Media foundation backend success varies with os used.

**Comment by vscfreire** [comment]
But there is support for H.264 (AVC420) on Windows Server 2012 R2. When I connect using "/gfx:AVC420", FreeRDP sets "settings->GfxH264" to TRUE and I get this line on the Windows Event Log:

`The client supports version 0x80105 of the RDP graphics protocol, client mode: 2, H264 enabled: 1`

When I only use "/gfx", FreeRDP only sets "settings->SupportGraphicsPipeline" to TRUE, not "settings->GfxH264", and I get this line on the Windows Event Log:

`The client supports version 0x80105 of the RDP graphics protocol, client mode: 1, H264 enabled: 0`

So, H.264 is supported correctly on Windows Server 2012 R2, it's not falling back to RFX.

I'll try once again to use OpenH264, as you suggested. I'll post back the results so that we can make sure that this problem is related to the Media Foundation decoder.

**Comment by vscfreire** [comment]
I successfully rebuilt FreeRDP with OpenH264 (also disabling Media Foundation), and the behavior is the same (disconnects when connecting to Server 2012 R2 using resolutions above 2048 pixels wide or high), so it doesn't seem related to the H.264 decoder.

**Comment by akallabeth** [comment]
@vscfreire ok, tried with a lot of systems, but was not able to configure 2012r2 to send H264 data (2016 and 2019 as well as windows 10 were successful)
All of these do connect using H264 AVC444 mode though, but they work with large resolutions.
Since resolution support is independent of codecs (maximum decoder limitations aside) I doubt this is a freerdp issue.
You still might want to try #5383, where I've pumbed the GFX support to current spec levels.

**Comment by akallabeth** [comment]
Reading your initial post again, it could actually be an encoder limitation server side (I think the encoding is done by your graphics card?)

**Comment by darkguy2008** [comment]
@vscfreire can you please provide me an OpenH264-enabled build for me to test something on Windows? I'm having this issue https://github.com/FreeRDP/FreeRDP/issues/5430 and it seems that the binaries out there are statically linked, so using an OpenH264 library from the internet doesn't work. Would you kindly help me with this request? Thanks!

**Comment by vscfreire** [comment]
Here's a binary which uses OpenH264 (Windows, MSVC 2017, x64). I've included OpenSSL DLLs, let me know if you need any additional DLL...

(PS: this version is to be used for tests ONLY, see https://www.openh264.org/faq.html)

**Comment by vscfreire** [comment]
Forgot to attach the file.
[FreeRDP-OpenH264.zip](https://github.com/FreeRDP/FreeRDP/files/3400991/FreeRDP-OpenH264.zip)

**Comment by darkguy2008** [comment]
Hello @vscfreire kindly thanks a lot for your help! Unfortunately it didn't help my case though :( using the 64-bit version and/or renaming it to OpenH264.dll, I still get this blocky output. How come you are having a different bug - are you using Linux/OSX instead, maybe?

![image](https://user-images.githubusercontent.com/6304136/61367297-85f44280-a848-11e9-95f8-038f7ce5335d.png)

**Comment by akallabeth** [comment]
@darkguy2008 build with `-DWITH_MEDIAFOUNDATION=OFF` (and use openh264 instead)

**Comment by akallabeth** [comment]
Closing this as hardware limitation, with OpenH264 client side this is not limited, only options are:
1. Server side (hardware encoder?)
1. Client side `Windows Media Foundation` is utilizing hardware decoders, but they might have such limitations.
