### ISSUE TITLE
MSRA (Remote Assistance) CTRL + ALT + C Not work

### ISSUE THREAD

**Issue by ylmw0131** [FreeRDP/FreeRDP#5352]
MSRA (Remote Assistance) CTRL + ALT + C Not work

According to https://github.com/FreeRDP/FreeRDP/wiki/Quality-Assurance-(QA)#remote-assistance-protocol

xfreerdp Invitation.msrcIncident /assistance:XXXXXXXXXXXX
If everything works as expected the remote assistance should start and the mirrored display should be shown.
To test "remote control" press "ctrl+alt+c" in xfreerdp the shadowed session should get a prompt to allow control. If it works it's possible to control the desktop in xfreerdp.

I see there is mentioned a feature to request a "Full Control" and will prompt communicates with MSRA.

But I try to do this on MacOS and Windows, both not work, and don't see any remark mentions on how to "Request for a Full Control".

Without full control, I am just able to view the screen.

Please advise on it.

Thank you.

**Comment by akallabeth** [comment]
@ylmw0131 sorry for the late response.
With current master it is working (just created an assistance session to a windows 10 machine and could activate input control)
windows and mac clients are not have all features of `xfreerdp`

**Comment by LordOfTheRats** [comment]
We have the same issue without using the remote assistance feature.

Nightly build #689 (15.08.2019 03:49:03) for bionic connecting to a Windows Server 2016 or a Windows Server 2012 R2.

Ctrl+Alt+V (for example) works. So far only Ctrl+Alt+C does not work.

**Comment by garbb** [comment]
Sorry, but do you mean that currently the windows and/or macOS clients do not have remote control upon pressing ctrl+alt+c for remote assistance sessions implemented?

**Comment by mfleisz** [comment]
@garbb exactly - these clients lack the implementation for processing Ctrl+Alt+C.

**Comment by garbb** [comment]
I made a fork with "/auto-request-control" command line option working with windows client (not the ctrl+alt+c keyboard shortcut yet...
https://github.com/garbb/FreeRDP

**Comment by garbb** [comment]
I also should note:
I was debugging keyboard shortcuts with windows client and I found that checking CTRL and ALT key states with `GetAsyncKeyState(VK_CONTROL)` and `(GetAsyncKeyState(VK_MENU)` inside of `wf_ll_kbd_proc()` always returns zero which is why keyboard shortcuts are not working.

I think `GetAsyncKeyState()` cannot be used within keyboard hook proc function?:
[LowLevelKeyboardProc callback function](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms644985(v=vs.85)):
> Note  When this callback function is called in response to a change in the state of a key, the callback function is called before the asynchronous state of the key is updated. Consequently, the asynchronous state of the key cannot be determined by calling [GetAsyncKeyState](https://msdn.microsoft.com/en-us/library/ms646293(v=vs.85)) from within the callback function.
