### ISSUE TITLE
Both the builds on https://cloudbase.it/freerdp-for-windows-nightly-builds/ fail

### ISSUE THREAD

**Issue by chrisjj** [FreeRDP/FreeRDP#5356]
On Windows 7 64-bit Pro, each one does nothing upon .exe launch.

Anyone know where a known-working Windows build can be found?

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

Please be a bit more specific, this is a 'does not work for me but I don't tell you what I am doing' kind of bug report.
Hint: Windows does not allow redirecting `stdout` to console for non console applications.
try `wfreerdp.exe <your arguments> >file.txt` and `type file.txt` to get the output.

**Comment by chrisjj** [comment]
> this is a 'does not work for me but I don't tell you what I am doing' kind of bug report.

What I'm doing is (as I said) launching the .exe. I downloaded, and clicked on the .exe. I tried both offered builds. 

What more info would you like?

> Hint: Windows does not allow redirecting stdout to console for non console applications.

You've lost me there. Why should I care?

**Comment by akallabeth** [comment]
Because wfreerdp must be started by a script or from cmd with proper arguments?

**Comment by chrisjj** [comment]
> Because wfreerdp must be started by a script or from cmd with proper
arguments?

Where can I find the docs for the proper arguments?

None found at https://github.com/FreeRDP/FreeRDP/tree/master/docs .

--
Chris

**Comment by akallabeth** [comment]
(Incomplete) listing here:
https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface

Or you call wfreerdp.exe from cmd (with the aforementioned redirection to file) and have the help printed to that file.
