### ISSUE TITLE
Failed to find arm-linux-androideabi-gcc

### ISSUE THREAD

**Issue by amratsingh** [FreeRDP/FreeRDP#5357]
I get reference from these links:
https://github.com/FreeRDP/FreeRDP/blob/master/docs/README.android
https://github.com/awakecoding/FreeRDP-Manuals/blob/master/Developer/FreeRDP-Developer-Manual.markdown

After setting locations in [setenv-android.sh](https://wiki.openssl.org/images/7/70/Setenv-android.sh) I run it but it giving me error and showing message "Failed to find arm-linux-androideabi-gcc".

![image](https://user-images.githubusercontent.com/15189911/56580329-f1cf6200-65ef-11e9-9601-359821c09342.png)

**Comment by akallabeth** [comment]
Firstly, better use docs from freerdp.com or github.com/freerdp/freerdp, others are usually outdated.

Secondly, if you are using recent android ndk install their cmake, add it to path and follow the standalone toolchain howto with their toolchain file.
Did not have time to update docs for that,
Any help appreciated.

**Comment by vjeson** [comment]
You can't build android version with latest ndk ,such as ndk 19c , Because the latest ndk compiler has changed from gcc to clang . I build successful the android version with ndk r14b

**Comment by akallabeth** [comment]
@vjeson you can utilizing the ndk toolchain file instead of the one supplied by freerdp.

Need to run cmake manually though, no nice script doing that for you at this point in time...

**Comment by SwapnilBhosale** [comment]
NDK version 15c works like charm.
No erroors and warning.

**Comment by amratsingh** [comment]
> You can't build android version with latest ndk ,such as ndk 19c , Because the latest ndk compiler has changed from gcc to clang . I build successful the android version with ndk r14b

I am able to proceed further but this time it is showing an fatal error in which it is unable to found some files(stdio.h, stdlib.h etc. ).

**Comment by amratsingh** [comment]
I am closing this because main issue is resolved.

**Comment by MrCsabaToth** [comment]
@akallabeth 
> @vjeson you can utilizing the ndk toolchain file instead of the one supplied by freerdp.
> 
> Need to run cmake manually though, no nice script doing that for you at this point in time...

Do you have any pointers about running the cmake manually?
I also got https://pastebin.com/y4uLEgz5
Then I created a toolchain:

```
csaba@asus:~/Android/Sdk/ndk-bundle/build/tools$ ./make-standalone-toolchain.sh --platform=android-29 --install-dir=/home/csaba/toolchains/arm-linux-androideabi-4.9 --toolchain=arm-linux-androideabi-4.9
HOST_OS=linux
HOST_EXE=
HOST_ARCH=x86_64
HOST_TAG=linux-x86_64
HOST_NUM_CPUS=16
BUILD_NUM_CPUS=32
Auto-config: --arch=arm
Toolchain installed to /home/csaba/toolchains/arm-linux-androideabi-4.9.
```

But then
https://pastebin.com/0WaPQjNj

Looks like I'm missing `android` lib or something, I was not sure if this is due to clang changes, or you say I need to run cmake manually. Is there a way to just modify the existing files to make them work?

**Comment by MrCsabaToth** [comment]
> I am closing this because main issue is resolved.

Could you share what steps did you make?

**Comment by MrCsabaToth** [comment]
If I can make it work on my system I'll try to update the docs.
