### ISSUE TITLE
Android Issue - Change Package name 

### ISSUE THREAD

**Issue by jass90** [FreeRDP/FreeRDP#5359]
When i changed the package name "com.freerdp.freerdpcore" to "com.myname.freerdpcore", gettting the below mentioned JNI error in logcat:

**JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.freerdp.freerdpcore.services.LibFreeRDP" on path: DexPathList**

I want to change the package name, please suggest. Thank you.

**Comment by bmiklautz** [comment]
@jass90 if you change the package name you will need to change it everywhere where "com.freerdp.freerdpcore"
