### ISSUE TITLE
Password supplied on command line is not replaced with "****" on wfreerdp

### ISSUE THREAD

**Issue by morten-torp-meiling** [FreeRDP/FreeRDP#5362]
I have seen this bug reported by others and it is set as fixed, but I still have this issue on both the 1.1 build of wfreerdp (from here: https://cloudbase.it/freerdp-for-windows-nightly-builds/) and the latest (as of time of writing, they don't show any info on what the basis of the build is but it seems to be latest master) from the 2.0 branch.
Is this an issue specific to the windows version?

Also, is there a way to pipe the password to wfreerdp? I can only get a GUI prompt for user/pass and that is no good for me since I need this in an automated setup - to log in a given user.

**Comment by akallabeth** [comment]
@morten-torp-meiling yes, that is specific to windows. (don't know if that is fixable)
as for other ways to supply command line parameters, the `/from-stdin` method should also work on windows

**Comment by morten-torp-meiling** [comment]
Thanks for the reply. The /from-stdin does not seem to work, though: it simply results in the GUI dialog being shown (and as far as I know, we cannot pipe into a GUI dialog!). Also both username and password is missing in the dialog, even though only the password was not passed to the command.

**Comment by akallabeth** [comment]
replacement of `argv` after a program is started is error prone. (e.g. if you have any task manager running it will keep the version initially supplied)
anyhow, #8931 should make this work just as with `xfreerdp` and #8976 allows to supply the whole command line from a file or `stdin`.
