### ISSUE TITLE
C# GUI

### ISSUE THREAD

**Issue by easywind** [FreeRDP/FreeRDP#5365]
I have already install FreeRPD-Sharp  0.1 using NuGet  for C#, But I can not know how to use the freerpd to connect windows for window form GUI.

I tested the FreeRDP-Sharp demo , and I can connect windows use the NFreeRPD, but I can not see any thing, It's thread. I can not see the GUI， I can not find any demo for C# GUI develop.  

Who can help me for the GUI connect windows GUI demo using C#?

thanks a lot.

**Comment by akallabeth** [comment]
@easywind project for C# bindings is https://github.com/FreeRDP/FreeRDP-Sharp
but I don't know if anyone is still using that.
