### ISSUE TITLE
Two finger sliding to scroll is not working on Mac

### ISSUE THREAD

**Issue by qiandahao** [FreeRDP/FreeRDP#5366]
The FreeRDP window is totally frozen when you slide with two finger to scroll.

Mac machine and OS: Macbook pro 15 and mojave
FreeRDP: the latest master branch
Remote OS: window 10

**Comment by akallabeth** [comment]
Xfreerdp or the native mac client? Former requires proper x11 extensions (not sure how awful the mac version is nowadays) the latter does not implement forwarding touch events.

**Comment by qiandahao** [comment]
The latter one. Thank you!

**Comment by loicV2Cloud** [comment]
The same thing happen when using the mouse wheel also.

**Comment by amazingfate** [comment]
> The same thing happen when using the mouse wheel also.

#6502 shoud have fixed the mouse wheel issue
