### ISSUE TITLE
Android Client Crash: Application Crash 

### ISSUE THREAD

**Issue by aamitgupta** [FreeRDP/FreeRDP#5369]
Hi team,
I am running the android client after code setup, application launch and gets crash with following error. we are running on the Mac.

> Pending exception java.lang.NoSuchMethodError: no static or non-static method "Lcom/freerdp/freerdpcore/services/LibFreeRDP;.freerdp_send_unicodekey_event(JI)Z"
> at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
> at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:1072)
> at void java.lang.Runtime.loadLibrary0(java.lang.ClassLoader, java.lang.String) (Runtime.java:987)
> at void java.lang.System.loadLibrary(java.lang.String) (System.java:1530)
> at void com.freerdp.freerdpcore.services.LibFreeRDP.<clinit>() (LibFreeRDP.java:44)

**Comment by akallabeth** [comment]
Looks like the signature registered is wrong.
Client/Android/android_freerdp.c:1148, change to (JIZ)Z

Currently afk, so I'd appreciate someone creating a pull I can merge ;)

**Comment by akallabeth** [comment]
ok, #5371 is merged.
reopen if still an issue.
