### ISSUE TITLE
flashing blocks on screen

### ISSUE THREAD

**Issue by stu247** [FreeRDP/FreeRDP#5370]
When windows are changing, sometimes FreeRDP will leave around blocks of color that slowly flash.  For example, when a window is maximized.  It appears to be blocks that were valid and never got redrawn when the window changed.  So it flashes back and forth with the old image and new image.  Video of the flashing blocks are at [https://youtu.be/3n9qDb9WAok](url)
The command line is:
xfreerdp /v:host.com /u:user /d:domain /size:1920x1080 /multimon /sound /clipboard
The system I connect to is Windows 10 Enterprise.  FreeRDP is version is 1.1.0-beta1 on Ubuntu 18.04 x86_64.

**Comment by akallabeth** [comment]
Please check if the issue is gone after using a more recent version (2.0.0 release candidates)

**Comment by stu247** [comment]
Is there an Ubuntu deb package of the latest 2.0.0 release candidate?  I have not been able to find one.  Thanks.

**Comment by akallabeth** [comment]
@stu247 don't know what ubuntu is shipping currently, but you can try our nightly packages https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by stu247** [comment]
I tried the nightly package and it worked fine.  I will close the issue.  It would be good to issue 2.0.0 officially so that all the distributions get the latest.  More people can enjoy the fruits of your hard work!  Thanks for creating and maintaining FreeRDP.
