### ISSUE TITLE
Bad colours on 30bit desktop

### ISSUE THREAD

**Issue by cehoyos** [FreeRDP/FreeRDP#5379]
I tested xfreerdp 2.0.0-rc4 on a desktop set to 30bit in /etc/X11/xorg.conf (both DefaultDepth and Depth set to "30"), colours look bad:
![30bit desktop](https://user-images.githubusercontent.com/3754917/57198446-49b48400-6f73-11e9-8352-bc1afa2f5698.png)
The blue window is what I saw, the other window is how it was supposed to look like.

**Comment by bmiklautz** [comment]
@cehoyos what does xfreerdp show for 'Local framebuffer format' and 'Remote framebuffer format' in it's messages? It would also be helpful if you add you xfreerdp commandline as well as the output of xdpyinfo

**Comment by pjanx** [comment]
Same, only:
```
[20:29:20:437] [1107368:1107369] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[20:29:20:437] [1107368:1107369] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
```
the only argument to xfreerdp is the server's FQDN.
