### ISSUE TITLE
Removed.

### ISSUE THREAD

**Issue by AIVIIVIAL** [FreeRDP/FreeRDP#5380]
Removed.

**Comment by akallabeth** [comment]
@AIVIIVIAL thank you for the report.
Could you attach your command line too?
Do you have a more verbose stack trace available?

**Comment by bmiklautz** [comment]
@AIVIIVIAL just tried:
```
python -c "print 'A' * 22000" > file
xfreerdp $(cat file)
```

Without proxychains and no problem.
As far as I'm aware of proxychains does only set a LD_PRELOAD library and replace some functions. From your report is is not clear if this is really a xfreerdp issue or a proxychains issue. How did your proxychains.conf look like?

**Comment by bmiklautz** [comment]
@AIVIIVIAL just tested with proxychains 3.1 and latest master. And couldn't reproduce the issue.

**Comment by AIVIIVIAL** [comment]
You may close/delete this advisory. Turns out this behavior is a function of libc in some way or another when provided with overly long command line input. proxychains valgrind nmap $(python -c "print 'A' * 23000") produces similar output as does proxychains valgrind ncat $(python -c "print 'A' * 23000").
