### ISSUE TITLE
KeyboardPauseEvent is not raised in server side

### ISSUE THREAD

**Issue by kubistika** [FreeRDP/FreeRDP#5401]
Hey!

While working on the proxy I noticed that Winkey+PauseBreak is not working when using the proxy. I looked into the library and RDPBCGR and understood that PauseBreak is a sequence of four events:

```A PAUSE key press and release MUST be sent as the following sequence of keyboard events:
CTRL (0x1D) DOWN
NUMLOCK (0x45) DOWN
CTRL (0x1D) UP
NUMLOCK (0x45) UP
The CTRL DOWN and CTRL UP events MUST both include the KBDFLAGS_EXTENDED1 flag.
```

I thought maybe the function `fastpath_recv_input_event_scancode` could be changed like this:
```diff
static BOOL fastpath_recv_input_event_scancode(rdpFastPath* fastpath, wStream* s, BYTE eventFlags)
{
	rdpInput* input;
	UINT16 flags;
	UINT16 code;

	if (!fastpath || !fastpath->rdp || !fastpath->rdp->input || !s)
		return FALSE;

	input = fastpath->rdp->input;

	if (Stream_GetRemainingLength(s) < 1)
		return FALSE;

	Stream_Read_UINT8(s, code); /* keyCode (1 byte) */
	flags = 0;

+      if ((code == RDP_SCANCODE_LCONTROL) && (eventFlags & FASTPATH_INPUT_KBDFLAGS_PREFIX_E1))
+      {
+	   /* PAUSE-BREAK sequence started */
+         if (!IFCALLRESULT(TRUE, input->KeyboardPauseEvent, input))
+            return FALSE;
+      }
	
	if ((eventFlags & FASTPATH_INPUT_KBDFLAGS_RELEASE))
		flags |= KBD_FLAGS_RELEASE;
	else
		flags |= KBD_FLAGS_DOWN;

	if ((eventFlags & FASTPATH_INPUT_KBDFLAGS_EXTENDED))
		flags |= KBD_FLAGS_EXTENDED;

	return IFCALLRESULT(TRUE, input->KeyboardEvent, input, flags, code);
}
```

What do you think about this addition?
* It is important to note that the same addition (with a different flag, called KBDFLAGS_EXTENDED1) has to be added to slowpath input.
* I'll be glad to submit a PR for this addition :)

**Comment by hardening** [comment]
Seem reasonable to me.

**Comment by akallabeth** [comment]
shouldn't it be sufficient to pass on the `FASTPATH_INPUT_KBDFLAGS_PREFIX_E1` flag in `KeyboardEvent`?

**Comment by kubistika** [comment]
> shouldn't it be sufficient to pass on the `FASTPATH_INPUT_KBDFLAGS_PREFIX_E1` flag in `KeyboardEvent`?

@akallabeth It can be sufficient, but as `KeyboardPauseEvent` is a callback that can be registered outside the library, as a client of the library I'd expect it to raise it in server side. It's up to you :) Let me know and I'll open a PR

**Comment by akallabeth** [comment]
the `KeyboarPauseEvent` currently is a client side convenience function to send a pause sequence.
this change would give it a server side meaning too (with quite a different application).
I'd prefer not to do that to avoid confusion.

**Comment by kubistika** [comment]
@akallabath Okay, but the thing is that the flag is different between slow/fast path input, so as a client of the library I'll have to check if the event flags contains 2 different flags. I find it a little ugly...

**Comment by akallabeth** [comment]
@kubistika you just found a bug ;)
but as far as I see you can just use one flag in both cases (it does not matter if you receive slow or fastpath events, you just need the information)

**Comment by kubistika** [comment]
> @kubistika you just found a bug ;)
> but as far as I see you can just use one flag in both cases (it does not matter if you receive slow or fastpath events, you just need the information)

@akallabeth I know, I'll fix it later.
However, I can't see how as a user of the library I can use one flag.
The slowpath adds KBD_FLAGS_EXTENDED1 (0x0200) and fastpath adds flag FASTPATH_INPUT_KBDFLAGS_PREFIX_E1 (0x04). So, in order to determine if PAUSE was pressed, I have to check if any of them is presented...

**Comment by akallabeth** [comment]
@kubistika sorry, I don't follow.
The callback we're talking about has as argument the flags and the scancode.
You don't need to know if fast or slow path, that part should already be abstracted.

**Comment by kubistika** [comment]
@akallabeth I think there is a misunderstanding between us.

Yes, there is a parameter called flags, but currently the flag which indicates whether a pause sequence is presented is added only in fastpath input.

According to the spec, in fasthpath, its value is 0x4, and in slowpath 0x0200. In freerdp, nor the slowpath or fastpath recv implementation adds the flag.

Again, according to the spec, the flag which indicates pause sequence has different value and name. This is why we can't just push one of those flags.

**Comment by akallabeth** [comment]
@kubistika yes, correct. currently the flag is not set before the callback.
But this can be added as there are already 2 functions reading (one for slow, one for fastpath) as is already done with the key press and key release.

**Comment by kubistika** [comment]
Thanks @akallabeth
