### ISSUE TITLE
Android Issue: FreeRDP gives JNI DETECTED ERROR IN APPLICATION

### ISSUE THREAD

**Issue by cogandroid** [FreeRDP/FreeRDP#5407]
When i changed the package name "com.freerdp.freerdpcore" to "com.myname.freerdpcore", gettting the below mentioned JNI error in logcat:

**JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception java.lang.ClassNotFoundException: Didn't find class "com.freerdp.freerdpcore.services.LibFreeRDP" on path: DexPathList**

I want to change the package name, please suggest. Thank you.

**Comment by akallabeth** [comment]
Please use the mailing list or irc for support.
Thank you
