### ISSUE TITLE
Geometry fields in RAIL_WINDOW_MOVE_ORDER should be signed

### ISSUE THREAD

**Issue by chrislong** [FreeRDP/FreeRDP#5409]
I have not seen this issue manifest as a bug. However, I think it could and it's an easy fix, so I thought I'd report it.

I just noticed that the geometry fields (`left`, `top`, `right`, `bottom`) in `RAIL_WINDOW_MOVE_ORDER` (in `include/freerdp/rail.h`) are defined as `UINT16`. However, these values derive from `windowOffsetX` and `windowOffsetY` in `WINDOW_STATE_ORDER`, which are signed (and which should be, per [2.2.1.3.1.2.1 of MS-RDPERP](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdperp/2d36758d-3fb5-4823-8c4b-9b81a9c8ff3e)). So the geometry fields of `RAIL_WINDOW_MOVE_ORDER` should also be signed.

`RAIL_WINDOW_MOVE_ORDER` also truncates the values from 32 to 16 bits. As long as these fields are being changed, I think they should be made 32-bit just to future-proof it, but I think it's much less an issue.

**Comment by mfleisz** [comment]
`RAIL_WINDOW_MOVE_ORDER` is specified in [2.2.2.7.4 Client Window Move PDU](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdperp/495acc38-df83-42ec-8ed1-b8d58c047262) with left, top, right, bottom being unsigned 16-bit integers. So the struct is defined correctly according to the MS specs.

**Comment by chrislong** [comment]
Thanks for the quick reply. I didn't realize that was why it was that way. It looks to me like a bug in the protocol because coordinates can be negative on Windows desktops. But we can't fix the protocol, so I guess there's nothing to do about it in FreeRDP.

**Comment by akallabeth** [comment]
@chrislong yes, the coordinate confusion is really a hard to handle.
In this case only the client can do that, so closing this as `can´t fix`.
