### ISSUE TITLE
smartcard authentication to farm

### ISSUE THREAD

**Issue by terrible-broom** [FreeRDP/FreeRDP#541]
Git version of xfreerdp (from Apr 3, 2012).
Connection point is a farm consisting of 2 Windows 2008R2 servers.

Command-line:

xfreerdp --no-nla --ignore-certificate --plugin rdpdr --data scard:scard -- kkdb-rdfarm01.kkdb.local

Sometimes smartcard authentication works OK, but sometimes not (may be when the redirection is performed).

Log when failed:
loading plugin rdpdr
connected to kkdb-rdfarm01.kkdb.local:3389
registered device #1: SCARD (type=32 id=1)
connected to 10.0.63.41:3389
registered device #1: SCARD (type=32 id=1)

I type the PIN for smartcard, and then Windows only show "Reading smartcard" message.

Last line of pcscd debug log:

00000080 winscard.c:272:SCardConnect() Waiting for release of lock

Screenshot (sorry for russian language, letters under right icon with smartcard mean "Reading smartcard"):
http://oi43.tinypic.com/2ze9q3d.jpg

After some time (about 30 seconds) freerdp closes.

**Comment by bmiklautz** [comment]
A lot of fixes have been done regarding smart card on the latest master (2.0.0-rc0+). Closing this issue. Please re-open or create a new one if you still hit that problem.
