### ISSUE TITLE
Android aFreeRDP client slow response

### ISSUE THREAD

**Issue by amratsingh** [FreeRDP/FreeRDP#5410]
After I connect a remote windows system on android, whenever I touch on screen to select an application on desktop it is responding very slow and even I don't able to open application by double click on application icon. I don't know what is the reason behind the performance issue.

**Comment by akallabeth** [comment]
which build do you use?

**Comment by amratsingh** [comment]
> which build do you use?

I used `android-build.conf`file to build.

**Comment by akallabeth** [comment]
@amratsingh That is a debug configuration ;) check the variables set.

**Comment by akallabeth** [comment]
@amratsingh Open the file with a text editor and check the variables. you might want to do a `Release` build.

**Comment by amratsingh** [comment]
@akallabeth Are you talking about CMAKE_BUILD_TYPE variable changing it from Debug to Release. Right?

**Comment by dragonuaix** [comment]
This is an old issue, here is a fix
https://github.com/FreeRDP/FreeRDP/issues/4571
