### ISSUE TITLE
Windows 10 Remote App Immediatly Closes

### ISSUE THREAD

**Issue by KevinGage** [FreeRDP/FreeRDP#5419]
I apologize if I am doing something wrong but I think this is a bug.  I have a  Win10 Enterprise Version 1809 machine with remote desktop enabled and Remote App Tool installed to publish remote apps.  I am able to connect via RDP to the desktop and to the remote apps from other Windows machines.  Using the command `xfreerdp /u:{user@domain}  /v:{hostname}` I am able to connect to the full desktop fine.  Using the command `xfreerdp /u:{user@domain} /app:"||Notepad" /v:{hostname}` a notepad window quickly flashes open and then immediately closes.  Here is the output that I see in the terminal

```
[12:10:09:381] [16675:16676] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[12:10:09:381] [16675:16676] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rail
Password: 
[12:10:13:468] [16675:16676] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[12:10:13:468] [16675:16676] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[12:10:13:471] [16675:16676] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[12:10:16:755] [16675:16676] [INFO][com.freerdp.client.x11] - Closed from X11
```

I've tried other remote apps and in all cases I can connect from Windows machines but not using freerdp.  They all open and close before I have a chance to react.

`xfreerdp /u:{user@domain} /app:"||Notepad" /v:{hostname}`

Expected behavior
The remote app should open and allow me to interact with it

Desktop:
    OS: Pop_OS 19.04

FreeRdp Version:
  This is FreeRDP version 2.0.0-dev5 (2693389a+debian)

**Comment by akallabeth** [comment]
Working with current nightly (just checked) so maybe we´re missing the faulty ingredient in the description?

**Comment by akallabeth** [comment]
Ok, looks like a bug in the debian version.
Most likely getting fixed once we can release the stable 2.0

**Comment by KevinGage** [comment]
Okay thanks.  Does that imply that I might be able to install a newer release candidate and have better luck?  Would you recommend that I try following the compile from source instructions in the wiki to run a newer version?  Or would it just be best for me to wait for the 2.0 release?  I assume that's a ways off.
In the meantime if there is anything else that I can provide to be of any help just let me know.  Thanks!

**Comment by akallabeth** [comment]
@KevinGage you can use our nightly builds for the time being (install in `/opt/freerdp-nightly`)
as for the release, that just depends on when we have sufficient time to run the final tests and create the release :/

**Comment by KevinGage** [comment]
Nightly is looking good.  Thanks a million.  What a great project you guys have put together!
