### ISSUE TITLE
+print-reconnect-cookie option doesn't appear to do anything

### ISSUE THREAD

**Issue by wdormann** [FreeRDP/FreeRDP#5425]
**Describe the bug**
https://www.mankier.com/1/xfreerdp#+print-reconnect-cookie seems to imply that there is a +print-reconnect-cookie option that will print the base64 reconnect cookie after connecting.

However, in my testing, it is not printed.  Furthermore, the rdp_read_server_auto_reconnect_cookie() function is present in /libfreerdp/core/info.c , but I can't see any evidence that it's called from anywhere.

**To Reproduce**
1. Run xfreerdp with the +print-reconnect-cookie option
2. Look for the reconnect cookie printed out

**Expected behavior**
Reconnect cookie printed in base64

** Application details
* Version of FreeRDP
FreeRDP version 2.0.0-dev5 (4a6b843f1)

**Comment by kubistika** [comment]
I'm pretty sure xfreerdp doesn't use the reconnect cookie for reconnection, but reconnects using a while loop that calls freerdp_connect x times (the configured max reconnection attempts in settings).

**Comment by akallabeth** [comment]
@wdormann Please don´t reference external sites, `freerdp.com`, this github project and the documentation printed by `xfreerdp` and others are the one and only relevant and up to date documentation.
As for your question: `rdp_recv_logon_info_extended` is the place you´re looking for...
Might simply be your server configuration not sending that specific message.
The message is sent in `rdp_write_extended_info_packet` which is part of `rdp_send_client_info` that is sent in `CONNECTION_STATE_MCS_CHANNEL_JOIN`
