### ISSUE TITLE
wlfreerdp /monitor-list not working

### ISSUE THREAD

**Issue by cizordj** [FreeRDP/FreeRDP#5426]
**Describe the bug**
When I type `wlfreerdp /monitor-list` it doesn't show any of my monitors number, or when I use `wlfreerdp /monitors:1` it doesn't use the right monitor.

**To Reproduce**
1. Install Debian Buster (GNOME interface)
2. Log into your session using wayland
3. Install freerdp with
`apt install freerdp2-wayland`
4. Run this command
`wlfreerdp /monitor-list`

**Expected behavior**
I expected this:

cezar@tec-seguranca:~$ wlfreerdp /monitor-list
        [0] 1920x1080	+0+0
        [1] 1366x768	+1920+312

**Screenshots**

![wlfreerdp](https://user-images.githubusercontent.com/32869222/59109937-634f3f80-8914-11e9-9a98-6fe39a6c3d5d.png)

** Application details
* Version of FreeRDP
This is FreeRDP version 2.0.0-dev5 (2693389a+debian)
* Command line used
`wlfreerdp /monitor-list`
* output of `/buildconfig`

[buildconfig.txt](https://github.com/FreeRDP/FreeRDP/files/3266266/buildconfig.txt)

* OS version connecting to
Windows server 2012
* If available the log output from a run with `/log-level:trace` 
I tried with
`wlfreerdp /monitor-list /log-level:trace`
and it doesn't show anything, am I doing this right?
**Desktop (please complete the following information):**
 - OS: Debian Buster
 - Browser: Epiphany
 - Version: 3.32.1.2

**Additional context**

I have a linux computer in my work with two monitors and a Windows server which I have to connect using RDP protocol. One screen is big and another is very small, I always use the small one to connect to the server while I use the bigger one for my local operations.
When I use Xorg server and xfreerdp to connect, I have this alias configured for my connection:
`alias xfreerdp='xfreerdp /kbd:0x00000416 /monitors:1 /f'`
so wherever I type the command it will always use the smallest monitor. I would like to do the same in wayland. Thanks for your awesome work with freerdp.

If you need more information, I'm at work  from Mondays to Fridays.

**Comment by akallabeth** [comment]
Wayland client dors currently not support many multi monitor related features.

**Comment by cizordj** [comment]
Alright, I'll keep with the X client instead.

**Comment by emmedve1** [comment]
Is wfreerdp (Windows client) expected to have working multi-monitor features?

**Comment by emmedve1** [comment]
I should have been looking at #3396 for insight

**Comment by Nolij** [comment]
Any known workarounds for this issue?

**Comment by cizordj** [comment]
@Nolij No, in the meantime just use the X version. That's what I did.

**Comment by Nolij** [comment]
> @Nolij No, in the meantime just use the X version. That's what I did.

That is unfortunately incredibly buggy on Wayland. Guess I'll see if I can convince my employer to let me set up a VNC server or something.

**Comment by akallabeth** [comment]
@Nolij interesting, which bugs do you have with `xfreerdp` on `xwayland`? Running it now for over a year on `gnome/wayland` on `debian 11` and did not have any issues so far.

**Comment by Erbureth** [comment]
@akallabeth I was just bit by https://github.com/FreeRDP/FreeRDP/issues/3475 for example

**Comment by manio** [comment]
I am using the wlfreerdp since it was introduced. Now over a time it works quite stable for me for a daily usage. Having multiple monitor support on wayland would be really cool feature which I am currently missing :)

**Comment by rogtheotech** [comment]
Is there any plans for implementing multiple monitors on wlfreerdp?

**Comment by akallabeth** [comment]
no, we no longer (actively) add new features to wayland client.
it has been deprecated in favor of the SDL client.

**Comment by cizordj** [comment]
@akallabeth then it means that I should close this issue?

**Comment by akallabeth** [comment]
@cizordj you can leave it open, we accept pull requests fixing/adding such stuff.

**Comment by akallabeth** [comment]
client deprecated, not planned.
`/list:monitor` is working though, but that is of little help I guess
