### ISSUE TITLE
Can't open more than one session RDP in remmina

### ISSUE THREAD

**Issue by przerada** [FreeRDP/FreeRDP#5434]
I can only one session in remmina, to get new connection to other server I need to close opened connection, close remmina and open remmina again and connect to server.

** Application details
* Version of FreeRDP - 1:2.0.0_rc4-5 - installed 11.06.2019 (DD/MM/YYYY)
* Version of Remmina - 1:1.3.4-1 - installed 14.03.2019 (DD/MM/YYYY)
* OS version connecting to MS Server 2008R2, MS Server 2012R2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Antergos, kernel 5.1.9-arch1-1-ARCH

**Comment by akallabeth** [comment]
Not much we can do here, you might want to report at https://gitlab.com/Remmina/Remmina
