### ISSUE TITLE
sizeof on pointer in process_uri()

### ISSUE THREAD

**Issue by ekse** [FreeRDP/FreeRDP#5441]
In process_uri, sizeof(prefix) returns the size of a char*, whereas the intent was clearly to get the size of the string.

https://github.com/FreeRDP/FreeRDP/blob/master/winpr/libwinpr/clipboard/posix.c#L424

```c
	const char* prefix = "file://";
	BOOL result = FALSE;
	char* name = NULL;
        const size_t prefixLen = strnlen(prefix, sizeof(prefix));
```

A potentatil fix this would be to declare prefix as a char array.

**Comment by hardening** [comment]
good catch
