### ISSUE TITLE
RemoteApp don´t work

### ISSUE THREAD

**Issue by 51319** [FreeRDP/FreeRDP#5444]
I am testing FreeRDP under the current Debian Testing. I have the following packages installed.
freerdp2-x11
freerdp2-wayland

(freerdp version 2.0.0-dev5)
freerdp buildconfig
```
This is FreeRDP version 2.0.0-dev5 (2693389a+debian)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RELWITHDEBINFO
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp2-Bj0zA6/freerdp2-2.0.0~git20190204.1.2693389a+dfsg1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 8.2.0
Target architecture: x64
```

I connect to a Microsoft Server 2012 R2. I've installed a clean server for this test without any restrictions through Group Policy.

I have already tested the following syntax. I did this in the standard debian terminal.
```
xfreerdp /v:ServerIP /u:USER /p:PASSWORD /d:DOMAIN /app:"||iexplore"
/app:"iexplore"
/app:"iexplore.exe"
/app:"c:\Program Files\Internet Explorer\iexplore.exe"
```

I get the following error message:
```
[09:27:44:353] [12661:12662] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[09:27:44:353] [12661:12662] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rail
[09:27:44:610] [12661:12662] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[09:27:44:610] [12661:12662] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[09:27:44:612] [12661:12662] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[09:27:44:052] [12661:12662] [INFO][com.freerdp.client.x11] - Logon Error Info LOGON_WARNING [LOGON_MSG_SESSION_CONTINUE]
[09:27:46:501] [12661:12662] [INFO][com.freerdp.client.x11] - Closed from X11
```
Many Thanks

**Comment by akallabeth** [comment]
Hi @51319 
I´ve just tested against our test machines and it is working as expected.
It might be a configuration issue,  so here some hints:

1. please verify that your server has been configured for remote app support (and maybe test with a known good configuration first)
1. You can start freerdp also with RDP files (if you have a working configuration it will work here too)
1. `/app:"someprog"` only works if the specific application has been published with that name
1. `/app:"c:\\somepath\\app.exe"` is the correct syntax for full path (single backslash will not work)
1. `/log-level:debug` will give you additional information when having issues (but will spam and slow down a normal connection, so only use for debugging)
1. If nothing helps, check if it works with our nightly builds (https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds) - they install binaris in `/opt` so be sure to call the correct one ;)

If you have further questions please use the mailing list or irc.

**Comment by 51319** [comment]
Hi akallabeth

 

1. I can start my RemoteApp from my windows clients. Does something special have to be set here for Linux?

2. When I use my RDP file, a normal RDP desktop connection is established. Not my app.

3. I checked that.

4. The double backslash will return the same error.

5. I did not get any further with the extended log. I had already tested that.

 


Mit freundlichem Gruß / Best regards

Jochen Sauer

**Comment by akallabeth** [comment]
ok, back on my debian machine I realized I´ve tried with our nightly only.
The debian package indeed has an issue with remote app.

**Comment by 51319** [comment]
Good to know. Thanks for the information.

When will the nightly build be rolled out into the current debian?

 


Mit freundlichem Gruß / Best regards

Jochen Sauer 



Registergericht Aschaffenburg HRA 3666
Pers. haft. Ges: ems e-mediaservice Verwaltungs-GmbH, Steuernummer: 20415758007, USt-IdNr: DE 211395854
Registergericht Aschaffenburg HRB 7826, Geschäftsführer: Helmut Kraft, Stefan Glaab

Diese E-Mail, inklusive sämtlicher Anhänge, kann vertrauliche Informationen enthalten und ist ausschließlich für oben genannte(n) Empfänger bestimmt. Jegliche unautorisierte Nutzung, Veröffentlichung oder Verbreitung ist strikt untersagt. Sollten Sie diese E-Mail irrtümlich erhalten haben, so benachrichtigen Sie bitte umgehend den Absender und löschen Sie diese von Ihrem System. Trotz unserer großen Sorgfalt bei der Minimierung des Risikos einer Verbreitung bedrohlichen Inhalts wird die Verwendung von Sicherheitssoftware Ihrerseits zur Prüfung dieser Mail empfohlen. Wir übernehmen keinerlei Haftung für Schäden oder Verluste jeglicher Art, verursacht durch Software oder E-Mails mit schädlichen Inhalten, außer im Fall nachweislichen Vorsatzes oder grober Fahrlässigkeit.

This e-mail, including any attachments, may contain confidential information and is intended exclusively for the recipient(s) named above. Any unauthorized use, disclosure or dissemination is strictly prohibited. If you have received this e-mail in error, please inform the sender immediately and delete it from your system. Despite our taking great care in minimizing the risk of spreading malicious content, the use of security software on your behalf to check this mail is recommended. In any case we assume no liability for damages and losses of any kind caused by software or e-mails carrying harmful content, except in case of provable criminal intent or gross negligence.

**Comment by akallabeth** [comment]
hard to tell, need some spare time for a proper `2.0` freerdp release but currently a bit busy :/

**Comment by 51319** [comment]
No problem. I'll just wait for a patch soon.

I just wanted to test the nightly. I have uninstalled the freerdp2-x11 and installed the freerdp-nightly. How can I test the input. what is the new syntax? xfreerdp is no longer available.

 

thanks for everything and for your time!

 


Mit freundlichem Gruß / Best regards

Jochen Sauer 



Registergericht Aschaffenburg HRA 3666
Pers. haft. Ges: ems e-mediaservice Verwaltungs-GmbH, Steuernummer: 20415758007, USt-IdNr: DE 211395854
Registergericht Aschaffenburg HRB 7826, Geschäftsführer: Helmut Kraft, Stefan Glaab

Diese E-Mail, inklusive sämtlicher Anhänge, kann vertrauliche Informationen enthalten und ist ausschließlich für oben genannte(n) Empfänger bestimmt. Jegliche unautorisierte Nutzung, Veröffentlichung oder Verbreitung ist strikt untersagt. Sollten Sie diese E-Mail irrtümlich erhalten haben, so benachrichtigen Sie bitte umgehend den Absender und löschen Sie diese von Ihrem System. Trotz unserer großen Sorgfalt bei der Minimierung des Risikos einer Verbreitung bedrohlichen Inhalts wird die Verwendung von Sicherheitssoftware Ihrerseits zur Prüfung dieser Mail empfohlen. Wir übernehmen keinerlei Haftung für Schäden oder Verluste jeglicher Art, verursacht durch Software oder E-Mails mit schädlichen Inhalten, außer im Fall nachweislichen Vorsatzes oder grober Fahrlässigkeit.

This e-mail, including any attachments, may contain confidential information and is intended exclusively for the recipient(s) named above. Any unauthorized use, disclosure or dissemination is strictly prohibited. If you have received this e-mail in error, please inform the sender immediately and delete it from your system. Despite our taking great care in minimizing the risk of spreading malicious content, the use of security software on your behalf to check this mail is recommended. In any case we assume no liability for damages and losses of any kind caused by software or e-mails carrying harmful content, except in case of provable criminal intent or gross negligence.

**Comment by 51319** [comment]
we have a quick question. Is there a possibility of telephone availability? 

We would like to work with you and offer financial support for your project. Maybe this would be helpful in the development.

 

Would you give us a phone number and an appointment for accessibility in the coming week?

 


Mit freundlichem Gruß / Best regards

Jochen Sauer | Administration / Support

 

e.ms e-mediaservice GmbH & Co. KG

Johann-Dahlem-Str. 50/52

D-63814 Mainaschaff

Registergericht Aschaffenburg HRA 3666
Pers. haft. Ges: ems e-mediaservice Verwaltungs-GmbH, Steuernummer: 20415758007, USt-IdNr: DE 211395854
Registergericht Aschaffenburg HRB 7826, Geschäftsführer: Helmut Kraft, Stefan Glaab

Diese E-Mail, inklusive sämtlicher Anhänge, kann vertrauliche Informationen enthalten und ist ausschließlich für oben genannte(n) Empfänger bestimmt. Jegliche unautorisierte Nutzung, Veröffentlichung oder Verbreitung ist strikt untersagt. Sollten Sie diese E-Mail irrtümlich erhalten haben, so benachrichtigen Sie bitte umgehend den Absender und löschen Sie diese von Ihrem System. Trotz unserer großen Sorgfalt bei der Minimierung des Risikos einer Verbreitung bedrohlichen Inhalts wird die Verwendung von Sicherheitssoftware Ihrerseits zur Prüfung dieser Mail empfohlen. Wir übernehmen keinerlei Haftung für Schäden oder Verluste jeglicher Art, verursacht durch Software oder E-Mails mit schädlichen Inhalten, außer im Fall nachweislichen Vorsatzes oder grober Fahrlässigkeit.

This e-mail, including any attachments, may contain confidential information and is intended exclusively for the recipient(s) named above. Any unauthorized use, disclosure or dissemination is strictly prohibited. If you have received this e-mail in error, please inform the sender immediately and delete it from your system. Despite our taking great care in minimizing the risk of spreading malicious content, the use of security software on your behalf to check this mail is recommended. In any case we assume no liability for damages and losses of any kind caused by software or e-mails carrying harmful content, except in case of provable criminal intent or gross negligence.

**Comment by akallabeth** [comment]
Hi, to answer your question (missed that one):
Nightlies are installed in `/opt/freerdp-nightly` to the binaries are most likely not in your path.

As for support, please see http://www.freerdp.com/support for contact addresses.
(issue trackers are not the best place to exchange phone numbers)
