### ISSUE TITLE
Redirect local microphone fails when setting the Sound to Local related to related to issue#3988

### ISSUE THREAD

**Issue by ehaparna** [FreeRDP/FreeRDP#5448]
I don't know how to re-open issue #3988
So if anyone finds how to do that, it would be great.

My main machine is ubuntu 18.4

Running  remote desktop to a Windows 10 PC.

The problem is that that the microphone sound is not going through to the linux machine.

The remote desktop shows the microphone on the PC grayed out. 

I'm using the this script 
xfreerdp +clipboard /sound:sys:pulse,format:1,quality:high /microphone:sys:pulse /multimon /u:egonh@xxx.com /v:${PCIP} +toggle-fullscreen "

I have exctly the same issue , but the mitigation there is possible for Windows Server.

What seemd to work for hyperion1209 

Quote from #3988 
"
1. Set the Allow audio recording redirection in Computer Configuration\Policies\Administrative Templates\Windows Components\Remote Desktop Services\Remote Desktop Session Host\Device and Resource Redirection to Not-configured.
2. Under Server Manager add the Remote Desktop Services Role and configure the Audio recording redirection on the Configure Client Experience page in the Add Roles Wizard.
"

I didn't find an equivalent for step 2 on Windows 10. 

Please advise.

**Comment by akallabeth** [comment]
@ehaparna this is a windows server configuration issue.
please use IRC or mailing list for support, this is an issue tracker for bugs/features of freerdp.
