### ISSUE TITLE
Broken Start Menu Search after Windows 10 1903 Upgrade

### ISSUE THREAD

**Issue by Arakis** [FreeRDP/FreeRDP#5450]
**Describe the bug**
Latest Windows 10 Update (V1903, Build 18362.175) broke Start Menü Search with xfreerdp. Using Windows without rdp (accessing the virtual machine from the libvirt console, the "real" screen), the start menu is ok! It's possible to click on the panel, the items are "there", but simply not visible. For example, clicking 100 px from the top will start the explorer.

**To Reproduce**
- Press Win-Key
- Search for an app
- The list is always empty except the auto completation text field

**Expected behavior**
See a list of results

**Screenshots**
Accessing with xfreerdp:
![image](https://user-images.githubusercontent.com/1831942/60178660-57241700-981c-11e9-908d-ce2f9cf5e80a.png)

via libvirt, the native console of the virtual mchine manager (no xfreerdp):
![image](https://user-images.githubusercontent.com/1831942/60179278-9f900480-981d-11e9-83c6-2cfe280e0fea.png)

** Application details
* Version of FreeRDP
1.1.0-beta1 (git n/a)
* Command line used
`xfreerdp /v:192.168.122.197 /u:sebastian +clipboard /cert-ignore /multimon +toggle-fullscreen /kbd:0x00010407`
* output of `/buildconfig`
(debian default)
* OS version connecting to
Debian 9
* If available the log output from a run with `/log-level:trace` 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version V1903, Build 18362.175

**Comment by akallabeth** [comment]
Not a FreeRDP issue. (everything you see is done server side and just displayed locally)

**Comment by Arakis** [comment]
Ok, so this is a windows side problem. But do you have "any" idea what this could occur?
