### ISSUE TITLE
Android: not generating required SO files

### ISSUE THREAD

**Issue by mithunkundu1983** [FreeRDP/FreeRDP#5451]
For Android running following command
./scripts/android-build-freerdp.sh --ndk $ANDROID_NDK --sdk $ANDROID_HOME --conf ./scripts/android-build-32.conf doesn't generate required following files in jnilibs

libfreerdp-openssl.so
libopenh264.so
libsqlcipher.so
libjpeg.so
Without libopenh264 & libpng
args.add("/gfx:AVC444") will not be triggered for AVC444

LibFreeRDP.java line 37 says
final String h264 = "openh264";
final String[] libraries = {
h264, "freerdp-openssl", "jpeg", "winpr2",
"freerdp2", "freerdp-client2", "freerdp-android2"};

Which are the libraries need to be included as so.
If we not include h264. h264 will not work. I am specifically looking for h264 & AVC444

**Comment by akallabeth** [comment]
Please use the mailing list or irc for support.
This is working, so either provide details or stop opening issues.

**Comment by mithunkundu1983** [comment]
Probably you are not in a mood to really go through my problem description. I am not a stupid person to raise defect without validating it. I am trying to do something very specific.

**Comment by akallabeth** [comment]
Then add some information as already requested twice.

**Comment by mithunkundu1983** [comment]
I have updated the original issue statement. Please let me know if I need to add anything else?

**Comment by akallabeth** [comment]
Sorry, could you be a bit more precise? This is still far too generic...

* Is the build failing?
* which external components do you use?
* do you actually use the correct configuration? (The few variables should be mostly self explanatory)

Some problem description with steps that are reproducible (or logs that can be analyzed) might help to answer your question...

**Comment by mithunkundu1983** [comment]
I tried to made thinks ore precise & clear please let me know if anything else is required. Thanks in advance for your time.

**Comment by akallabeth** [comment]
Ok, let me interpret:
* the build is working but you're missing one of the deps?
-> Check the CONTENT of the SAMPLE config files please
As for 'libjpeg' just skip it, not required and only for some old xrdp extension

**Comment by mithunkundu1983** [comment]
But libopenh264.so is also required. That is also not present.

**Comment by akallabeth** [comment]
Open the config file and check it finally, is that so hard?

**Comment by mithunkundu1983** [comment]
I have checked the config file & all other places.
Its simply not building libopenh264.so. 2.0.0RC4 has that file in JNI. If you think its not a error condition, I have nothing to say.

**Comment by akallabeth** [comment]
Ok,
tested with debian and fedora,
if the config file is properly configured it builds.
Add something, this is only a guessing game due to lack of information (you provide really not much to work with)

**Comment by mithunkundu1983** [comment]
I don't know how to fix this. But here is the reference
https://github.com/FreeRDP/FreeRDP/commit/2ff19597dcd4abc486dbd311b551f0c22369177c#diff-f9718a3d8692c33256c8bee3fb17debf

fix scripts to build with ndk r15c,

cache dependancies so we are not hitting github often
update android dependancies to latest and compile.
./android-build-freerdp.sh --ndk ~/Programming/android-ndk-r15c --relWithDebug --jpeg
Still an error compiling openh264
Can @wintersandroid can have a look on this?
