### ISSUE TITLE
Microphone redirection doesn't work

### ISSUE THREAD

**Issue by BenjaminBoutrois** [FreeRDP/FreeRDP#5455]
Hi,

**Bug description**
The microphone redirection doesn't seem to be working. When activating `/sound:sys:alsa` and `/microphone:sys:alsa`, the sound is working but not the microphone.

We are using FreeRDP rc4 on a Slackware 14.0 connecting to a Windows Server 2008 R2 Enterprise.

Before connecting, we tested the microphone with alsamixer, and we were able to hear the microphone output.
Once connected to FreeRDP, we tested on skype and an audio recorder, with no success.

We tried FreeRDP rc2 and rc3 :
- rc2 : it works
- rc3 : same problem

**Output of /buildconfig**
<pre><code>This is FreeRDP version 2.0.0-rc4 (2.0.0-rc4)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 4.7.1
Target architecture: x86</code></pre>

**Output of a run with /log-level:trace**
During this run, we tried to use the microphone with skype.
Here is the full output : 
[connection.log](https://github.com/FreeRDP/FreeRDP/files/3358618/connection.log)

Thanks in advance

**Comment by akallabeth** [comment]
You might try with adding `/microphone:sys:alsa,format:1` to force microphone channel to use `PCM` only.
Might be some incompatibility for the `ALAW` or `ULAW` encodings used in your log.

**Comment by akallabeth** [comment]
just a note though, `pulse` backend is currently the one yielding best results in our tests.
with alsa there are sometimes glitches we can´t exactly pinpoint.

**Comment by BenjaminBoutrois** [comment]
We tried `/microphone:sys:alsa,format:1` and it did work.
For `pulse`, when we add `/microphone:sys:pulse`, we get a black screen.

**Comment by akallabeth** [comment]
Ok, so this is more of a compilation / configuration issue then.
Glad the option works for you, so closing.

As for pulse, if you get a black screen it definitely has nothing to do with the `audin` channel (it may only disconnect if there is an error)
Did you compile with pulse support (I think autodetection is off)

**Comment by BenjaminBoutrois** [comment]
For the logs I sent you earlier, we did not compile with pulse support.
However, we did try to compile with it but we had the same result, black screen.

**Comment by fdutheil** [comment]
Hi,
Wow. `/microphone:sys:alsa,format:1` did it too in my case (on Windows 10 Pro v1909).
Except I only use ALSA and no PA, I couldn't get the microphone redirection to work unless `format:1` was added to the mic redirection.
Is there a documentation about this option?
Additionally is there anything I can do to help troubleshooting this if needed?

Regards.
