### ISSUE TITLE
SCardEstablishContext fails after termination of RDP session

### ISSUE THREAD

**Issue by wicow** [FreeRDP/FreeRDP#5456]
SCardEstablishContext fails on server side with SCARD_E_NO_SERVICE after termination of RDP session on client side.
SCardEstablishContext works in normal mode, if you finish a session using "Start->Sign out" on server side.

I open RDP-session using command ./xfreerdp /u:user_name /d:domain /v:server_ip /sec:rdp /smartcard. Call SCardEstablishContext and SCardReleaseContext on server side. Then I use Ctrl+C in terminal for termination RDP-session.
Then I repeat this actions several times (from 1 to 10 times). And at some moment SCardEstablishContext fails with SCARD_E_NO_SERVICE on currnet RDP-session and all the following RDP-sessions.
Restart SmartCard service doesn't help. I use Windows Sign Out to fix it for next session.

Version of FreeRDP 2.0.0-dev5 (2da425a)

Client is Ubuntu 16.04.2 LTS
Server is Windows Server 2012 R2 Datacenter

**Comment by akallabeth** [comment]
So, you did managet to screw up server side smartcard state?
don´t see any freerdp bug here or did you want to add something specific?

**Comment by wicow** [comment]
Sorry, I forgot to specify Windows-to-Windows case. If I use default Windows utility mstsc to connect to same machine after I get SCardEstablishContext error in xfreerdp session, SCardEstablishContext inside mstsc's session always suceeds. That's why I believe there might be an issue in freerdp connection routine - looks like it doesn't always connect properly to already started smartcard service in Windows user session.

**Comment by akallabeth** [comment]
@wicow thank you for the additional info.
Will have a look as soon as I have time.

**Comment by akallabeth** [comment]
@wicow An additional question:
* You kill `mstsc` just like `xfreerdp`? (disconnect cable, use task manager to kill)
* `mstsc` is resuming the same session on the server or does it have a different one? 

If not it might be helpful information what happens if `mstsc` resumes a session `xfreerdp` is complaining about before.

**Comment by wicow** [comment]
1) I tried to kill mstsc process and tried to close RDP Window, but SCardEstablishContext always succeeds in mstsc afterwards
2) mstsc is resuming the last session
3) after I get error with smartcard in xfreerdp and resume this session via mstsc, SCardEstablishContext doesn't fail
