### ISSUE TITLE
Bluetooth keyboard not working - IOS

### ISSUE THREAD

**Issue by cogphone** [FreeRDP/FreeRDP#5464]
Bluetooth keyboard is not working, during FreeRDP session in IOS.
How I can Fix this issue, Please Suggest. 

I'm grateful for any help,
 Thanks.

**Comment by akallabeth** [comment]
Ios client is lacking a maintainer.
Pull requests for new features are welcome.

**Comment by cogphone** [comment]
Thanks for your reply akallabeth.
Now Hardware Keyboard is working fine. All the keys Like Shift key, Delete key, alphabet keys and number keys etc. working perfectly.
Only the Hardware keyboard Cursors Keys (arrow keys) are not working inside the MS Word (ifreerdp session).

How I can Fix this issue, Please Suggest.

Thanks.

**Comment by wangyukun** [comment]
Can freeRDP work properly?may i consult you by email?thank you
