### ISSUE TITLE
How to Ensure File Transfer Completeness

### ISSUE THREAD

**Issue by nightHunterVN** [FreeRDP/FreeRDP#5465]
I used freerdp-2.0.0-rc4 on Debian GNU/Linux 9 and connected to window 10.
I copied some files from Windows to directories. When the copy is finished, unplug the U disk and insert it into Windows system. It is found that there are no newly copied files on the U disk.
Does the caching mechanism of Linux system cause it? Then how can we ensure that data can be written to U disk?

**Comment by akallabeth** [comment]
Please use the mailing list or IRC for support questions.
As for your setup, please describe that in a bit more detail as it is not really clear how you are using freerdp and where the files are stored.
