### ISSUE TITLE
NUM Lock state and led not synced after sometime on TS 2012R2

### ISSUE THREAD

**Issue by Sven-bml** [FreeRDP/FreeRDP#5466]
**Describe the bug**
On 2012R2 Termianlserver the NUM Lock state and led are not synced after sometime.
We have one Sessionbroker and five Sessionhosts.

**To Reproduce**
Log in -> and work. After sometime the NUM Lock change his Status and is reverse

**Expected behavior**
Switching should not be automatic.

** Application details
freerdp-git (2019.0.2) included in Openthinclient 2019

**Desktop (please complete the following information):**
 - OS: 2012R2 Terminalserver

**Comment by akallabeth** [comment]
@Sven-bml What is ` freerdp-git (2019.0.2) included in Openthinclient 2019` ? Can you run with ` /buildconfig` argument to get some specific ID?
Additionally it would be helpful to know something more about your local window manager / setup.
This looks like some focus issue as the state of numlock and others is synchronized whenever there is a focus change.

**Comment by Sven-bml** [comment]
> What is freerdp-git (2019.0.2) included in Openthinclient 2019 ? Can you run with /buildconfig argument to get some specific 
I don't now where i can do this. I have searched in the Filesystem. I found this:
![Bildschirmfoto 2019-07-10 um 15 04 40](https://user-images.githubusercontent.com/52741447/60971354-43040d80-a324-11e9-8505-a081e9322145.png)

My Setup:
I have some old PCs where i run OpenThinclient over PXE. This is a Mate Desktop an in the Configuration i can add a "Application" like Citrix or in my case RDP.

![Bildschirmfoto 2019-07-10 um 15 08 54](https://user-images.githubusercontent.com/52741447/60971524-ab52ef00-a324-11e9-9470-eec3607c1a80.png)

i have one 2012r2 connectionbroker and five Sessionhosts, also 2012r2.
Software is MS-Office and Komalog.

**Comment by akallabeth** [comment]
Ok, so you only work in the RDP session or you do some stuff in local applications too?

**Comment by Sven-bml** [comment]
Yes on this Thinclient is no local Application. I only use FreeRDP to work on a Terminalserver-session.

**Comment by akallabeth** [comment]
Ok, would still need the version you're using.
Can you call xfreerdp /buildconfig from a terminal?

**Comment by Sven-bml** [comment]
Is this Helpful?
<img width="537" alt="Bildschirmfoto 2019-07-10 um 21 07 46" src="https://user-images.githubusercontent.com/52741447/60997422-10bfd380-a357-11e9-9d7f-3b46181b7385.png">

**Comment by Sven-bml** [comment]
<img width="526" alt="Bildschirmfoto 2019-07-10 um 21 47 48" src="https://user-images.githubusercontent.com/52741447/60999899-88dcc800-a35c-11e9-96d2-6ac382c7a922.png">

**Comment by akallabeth** [comment]
@Sven-bml Thank you, yes. Got the exact version now.

**Comment by akallabeth** [comment]
@Sven-bml A simple test that might help:
If you click outside the application (focus out) and back in (focus in) is the state fixed?

**Comment by Sven-bml** [comment]
The Application is Running in Fullscreen. I have to reconfigurer one Client and Try.

**Comment by Sven-bml** [comment]
One user is now testing. The problem is to reproduce this. Unfortunately, it only appears after a while. I hope it occurs in the next few hours.

**Comment by Sven-bml** [comment]
@akallabeth 
My testuser just called me to his Workstation. The Num Lock has just changed to reverse.
I minimized the RDP Session and go back. Now the Num Lock ist synced again and is working.

**Comment by akallabeth** [comment]
@Sven-bml ok, thought so.
that means that the state is somehow `lost` and no focus in / out happens.
Any hint on when this happens? As in what is the user doing, is it always similar or not?

Can think of 3 remaining options for this issue:
1. our special key handling (`<ctrl>+<alt>` might screw up)
1. `xf_keyboard_get_toggle_keys_state` or `xk_keyboard_update_modifier_keys` is not working properly
1. the server is changing / loosing its state

1. The first one can be checked with disabling the functions `xf_keyboard_handle_special_keys` and `xf_keyboard_handle_special_keys_release`
1. can be checked by pressing `CAPSLOCK` (if starting state is disabled, press it twice). This will force a state sync with the server similar to the focus in/out.
1. No idea how to rule out that one

**Comment by Sven-bml** [comment]
I have talked to an other user with this problem.
he says it is arbitrary. even within an application, the status changes.

a certain key combination does not push the user bevor this issue. they click with the mouse in a field. go through the input mask with tab and type numbers and letters.

Of course, sometimes the app is changed but not actually within the process.

Is the "xf_keyboard_handle_special_keys" and "xf_keyboard_handle_special_keys_release" a additional parameter for the connection?

**Comment by akallabeth** [comment]
@Sven-bml Sadly these are functions you need to comment out (requires a recompile, will disable the fullscreen toggle and other key combinations to escape the window)

**Comment by Sven-bml** [comment]
so there is actually no fix 2012r2 :-/
(i have heard about the same problem on 2019 Server in the Openthinclient-Mailings)

**Comment by akallabeth** [comment]
@Sven-bml so does this work then?
If nobody gives feedback you will never see a fix ;)

**Comment by Sven-bml** [comment]
I don't know to recompile and use it on the Openthinlcient System.
I Think that is someting what the developer from Openthinclient have to do.

**Comment by MarkoD** [comment]
Hi, I can confirm this bug (using xfreerdp included in OpenThinClient 2019 beta), a workaround is to turn off /gfx:

![gfx-settings](https://user-images.githubusercontent.com/904050/62430215-bb8a9e00-b719-11e9-8309-5172757e3114.png)

It seems related to issue #2822.

**Comment by akallabeth** [comment]
@MarkoD so, when disabling `/gfx` everything is working? Damn, that sounds like a server side bug :/
Are you able to compile your own version? would be interesting to know the state the client thinks the server has in `xf_keyboard_send_key`
(local state can be read with `xf_keyboard_get_toggle_keys_state`)
Remote state changes should be reflected by `xf_keyboard_set_indicators`, but only if not locally triggered

**Comment by Sven-bml** [comment]
unfortunately, after I disabled rfx / gfx in my environment, the sessions crash. Both in the beta and in the final release.

I had to turn the option on again so that users do not fly out of the session every few minutes.

**Comment by akallabeth** [comment]
@Sven-bml define crash (sorry, the word seems to be used to describe various things)

**Comment by Sven-bml** [comment]
Hello, with me the program crashes. So that meant in my case that the window just closes. In the picture you can see the error message after the crash. I also add the server events.
![Ohne Titel](https://user-images.githubusercontent.com/52741447/62847752-35052c00-bcd8-11e9-8e4c-6d5c672baeaf.jpg)
[Bildschirmfoto 2019-08-09 um 10.44..pdf](https://github.com/FreeRDP/FreeRDP/files/3491152/Bildschirmfoto.2019-08-09.um.10.44.pdf)

**Comment by akallabeth** [comment]
@Sven-bml ah, ok, expected disconnect (server does not like connection settings)
but since you mention it, can you try the same with our nightly builds from a normal pc?

**Comment by Sven-bml** [comment]
I just had another call of an affected user. I activated Capslock once and deactivated it again. After that, the NUM Lock was switched on again.

Unfortunately, I have never tested the Nightly Build like this before. But I can try it. Should I do that also from a Linux system?

**Comment by akallabeth** [comment]
@Sven-bml yes, please a linux build (the clients all have their own sync logic :/)
Don´t know the exact differences to a desktop os and the openthinclient environment, so if it is reproducible on a default os it is much easier to debug.

**Comment by MarkoD** [comment]
Disabling `/gfx` works for me without crashing (I'm connecting to Windows 8.1), I'm using the same OpenThinClient version as @Sven-bml. However it causes a major decline in performance, so it's a no-go for me.

I've since experimented with this issue a little more and so far I've come to the following 3 workarounds:
1. [Only in a window-based session] Click outside the FreeRDP window, then back inside
2. Press Caps Lock during the RDP session
3. Simulate a Num Lock keypress using PowerShell:
```powershell -Command "$s = New-Object -ComObject WScript.Shell;$s.SendKeys('{NUMLOCK}')"```

I'm using the third option because it doesn't require anything from the user and can be automated 
via Task Scheduler in Windows. I've created a task and I'm running it when the user logs in. You can easily import the [this XML file](https://github.com/FreeRDP/FreeRDP/files/3493998/Sync.Num-Lock.zip).

Note that this bug only happens when connecting to a new RDP session, so the scheduled task only needs to run when a user logs in and doesn't need run when he reconnects into an existing session.

**Comment by Sven-bml** [comment]
@MarkoD Do you have a 2012r2 terminalserver? What connection settings do you have on the server side?

Your 3 workarounds only work conditionally with me.

1 - does not work, because I use the application in full screen.
2 - Works already, but then I can just press the NUM button. That works, too, just the LED is reverse.
3 - Will not do much with me as the condition changes during the session.

I hope I can setup a Linux system tomorrow morning and test it. Otherwise I will be back in the office from thursday. I'll contact you as soon as I have something new.

**Comment by MarkoD** [comment]
I have Windows 8.1 Pro, which is based on the same kernel, so it should be similar. I'm using the following settings:

![OpenThinClient Beta 2019, FreeRDP Settings](https://user-images.githubusercontent.com/904050/62896215-d92ab980-bd50-11e9-9946-a6cf63c0e5e5.png)

Regarding the workarounds:
2. There's a difference, at least in my case - if I press Caps Lock (once) in fullscreen, Num Lock synces correctly (LED gets "unreversed", i.e. keyboard LED is on and remote Num Lock goes from off to on).
3. The PowerShell command needs to be run only once after login, Num Lock (including LED) stays in sync during the rest of the session.

For me, option 3 works okay, only downside is that a PowerShell window is briefly visible after login and gets hidden after half a second.

**Comment by akallabeth** [comment]
I´ve created a branch that synchronizes the keyboard LED state on all `FocusIn` events (mouse enters the window) as well as `EnterNotify` (e.g. fullscreen floatbar)
see https://github.com/akallabeth/FreeRDP/tree/keyboard_sync_ext

So, if you still have this specific issue with this branch, it is really a server bug and we have to find some kind of workaround for that.

**Comment by Sven-bml** [comment]
apologies for the late reply i was very busy.
I now have a computer with Ubuntu and would like to test it once. What do I have to do to get the customized version?

if that works, i hope openthinclient will take over that soon.

**Comment by akallabeth** [comment]
@Sven-bml check out the branch and build a nightly package like described here https://github.com/FreeRDP/FreeRDP/wiki/Compilation

**Comment by SnejPro** [comment]
@Sven-bml 
I have similiar problems with openthinclient and Windows Server 2012 R2. Did you solve the problem?

**Comment by Sven-bml** [comment]
@SnejPro 
No. I have not try it with the nightly build, but our openthinclient has updated the free RDP to this and the problem is still there. So our user are frustrated but I can not solve it.

![Bildschirmfoto 2020-02-28 um 12 18 15](https://user-images.githubusercontent.com/52741447/75544539-7961da80-5a24-11ea-8227-7f4d29748c7f.png)

**Comment by freisei** [comment]
same issue here.

```
ser@XP102:~$ xfreerdp /buildconfig
This is FreeRDP version 3.0.0-dev (bb6c1ed8a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_STRNDUP=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_FUSE=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 9.3.0
Target architecture: x64
```

could be workarounded with marcoDs hint 
` powershell -Command "$s = New-Object -ComObject WScript.Shell;$s.SendKeys('{NUMLOCK}')"`

i ve added a additonal trigger when reconnecting session for all users.
