### ISSUE TITLE
unresolved symbol gdi_send_suppress_output

### ISSUE THREAD

**Issue by rtde** [FreeRDP/FreeRDP#5467]
**Describe the bug**

freerdp always crashes right after starting with message "xfreerdp: symbol lookup error: xfreerdp: undefined symbol: gdi_send_suppress_output"

* Version of FreeRDP

2.0.0

* Command line used

xfreerdp

**Desktop (please complete the following information):**

OpenSuse Tumbleweed, Kernel 5.1.10-1, x86_64
KDE Plasma 5.16.2

Firefox 67.0.4

**Comment by akallabeth** [comment]
Compilation issue.
Can you reproduce with our nightly builds?
Otherwise please inform your distributor (whoever built the package)
Might be a simple version inconsistency (libfreerdp/xfreerdp not both at the same build)

**Comment by akallabeth** [comment]
Oh, and before I forget, try updating your system first, if it is a inconsistency it might already be resolved.

**Comment by rtde** [comment]
Am 10.07.19 um 20:11 schrieb akallabeth:
>
> Compilation issue.
> Can you reproduce with our nightly builds?
>

Your nightly build works properly, so it seems to be a problem of my distribution.


> Might be a simple version inconsistency (libfreerdp/xfreerdp not both at the same build)
>

libfreerdp and xfreerdp had the same version.


> Otherwise please inform your distributor (whoever built the package)
>

I will do it.
Thanks for helping.


Best regards.
rtde
