### ISSUE TITLE
Freerdp with UPN

### ISSUE THREAD

**Issue by edavgnon** [FreeRDP/FreeRDP#5470]
Hi,

got a question with Freerdp on thinpro 7, i'm able to use a username, but not able to use the email address, can you help me with that?

**Comment by akallabeth** [comment]
Support questions please via mailing list or irc.
Adding a version might help in your case to answer the question.

**Comment by edavgnon** [comment]
whats the email address?

Le jeu. 11 juil. 2019 à 15:00, akallabeth <notifications@github.com> a
écrit :

**Comment by akallabeth** [comment]
https://www.freerdp.com/support
