### ISSUE TITLE
server: proxy: use freerdp_settings_clone() instead of a custom function

### ISSUE THREAD

**Issue by kubistika** [FreeRDP/FreeRDP#5474]
As discussed with @akallabeth, instead of using a custom function to copy the client settings, we should use the library function `freerdp_settings_clone`. The problem is that it copies some fields that shouldn't be copied, for example, the certs.

**Comment by akallabeth** [comment]
https://github.com/akallabeth/FreeRDP/tree/proxy_use_settings_clone contains an     initial implementation, needs some refinement (some settings must be overridden by proxy)
