### ISSUE TITLE
RemoteApp window unresponsive after maximizing

### ISSUE THREAD

**Issue by jbenderjb** [FreeRDP/FreeRDP#5479]
Published application is displayed correctly, initially.  Can resize, move, and maximize it.  The application functions as expected when maximized.  However, after the window size is restored to a smaller size, the window interactions no longer function; minimize, maximize, close, resize, and drag all do not work.  Alt-Tab can be used to move focus to another window, and back again to regain some control.  Mouse interactions in the  application appear to be "offset" when window is not maximized, perhaps as if the window is still maximized.

xfreerdp 2.0.0-rc4
RHEL 8.0
GNOME Version 3.28.2
Windows Server 2016 RDS

Command Line:
```
xfreerdp /v:server /d:domain /cert-ignore "app:||alias"
```

**Comment by akallabeth** [comment]
@jbenderjb does it occur with our nightly builds too? https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by clcrutch** [comment]
While I am not the OP, I can repro this using a build from the master branch the git repo.

In addition to the issues above, Gnome seems to always act like I'm right-clicking.  The only way that I can restore functionality is to close the RemoteApp.

I am running Ubuntu 18.04 and would be happy to help debug if you are interested.
