### ISSUE TITLE
Build does not fail if x11 is not installed on build machine

### ISSUE THREAD

**Issue by matthiasbeyer** [FreeRDP/FreeRDP#5483]
**Describe the bug**

When building xfreerdp (version 2.0.0-rc4 in my case), the build did not fail (what I would have expected) when not finding the x11 dependencies in the system.

The build setup only built the library parts of the package, but not the actual `xfreerdp` binary.
There was no error that x11 dependencies where missing.

**To Reproduce**
1. Spin up a VM/container/whatever without x11 installed at all (in my case I used a centos6.7, but I'm positive that this might also happen on other unices without x11 installed)
2. Try the default `./configure && make` or `cmake` build 
3. try to find the `xfreerdp` binary. I didn't.

**Expected behavior**

A clear error and failed build because building a X binary without X development libraries installed on the system can never(?) work?

** Application details
* Version of FreeRDP: v2.0.0-rc4
* Command line used: not applicable
* output of `/buildconfig`: No such file or directory
* OS version connecting to: Not applicable

**Desktop (please complete the following information):**
Not applicable

**Smartphone (please complete the following information):**
Not applicable

**Comment by akallabeth** [comment]
@matthiasbeyer Could you give some more detailed data on your build? (e.g. cmake run output)?
1. On a sidenote, there is not `./configure && make` for freerdp...
1. `X11` is not strictly required to build freerdp (only if you try to build e.g. `xfreerdp`)
