### ISSUE TITLE
Bluetooth Keyboard Arrow Keys not Working - IOS

### ISSUE THREAD

**Issue by cogphone** [FreeRDP/FreeRDP#5488]
Hardware keyboard Cursors Keys and Ctrl  not working inside the MS Word (afreerdp session).
Other keys like Shift, Delete etc. working perfectly.

How I can Fix this issue, Please Suggest.

I'm grateful for any help,
Thanks.

**Comment by akallabeth** [comment]
That tells something completely different than your own #5464 
#5468 also sounds very familiar.
Also very interested in how you can get afreerdp running on iOS...
Considering this as spam, please stop or be banned.
