### ISSUE TITLE
Question: intel-media-va-driver enabled/useable?

### ISSUE THREAD

**Issue by johndoe7000** [FreeRDP/FreeRDP#5502]
Debian Buster ships now the "intel-media-va-driver" and "intel-media-va-driver-non-free" to accellerate video decode/encode.

Do the nighly builds for Debian Buster use this automatically or would this need a special compile option?

Kind regards
Darius

**Comment by akallabeth** [comment]
Maybe indirectly, the `H264` modes of RDP use either `openh264` or `ffmpeg` to decode. (depends on compile options)
So, if your `ffmpeg` uses them we do so too.
Sadly this is not the part most of the processing power is required :/
