### ISSUE TITLE
Can't display VirtualBox guest (BIO_read returned a system error 0: Error 0)

### ISSUE THREAD

**Issue by Mno-hime** [FreeRDP/FreeRDP#5504]
**Describe the bug**

I try to connect from OpenIndiana 2019.04 desktop with FreeRDP e873e4f0042dd157f68ae99adb4dc9dcd167ca29 (the latest as of today) to a VirtualBox 6.0.8 guest running on a different OpenIndiana 2019.04 host, the guest is OpenIndiana 2019.04 as well:
```
xfreerdp /v:192.168.1.235:5912
```

On the VirtualBox host I have the Oracle extension pack 6.0.8 with VRDP installed and VRDP enabled in the guest. (I am able to connect to the guest via `rdesktop` 1.8.3 but not the latest `rdesktop` `HEAD`).

But the connection fails in about a second. For a second I can see the guest as expected. The error seems to be:

```
[18:31:46:498] [28099:00000002] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 0: Error 0
[18:31:46:498] [28099:00000002] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[18:31:46:498] [28099:00000002] [INFO][com.freerdp.client.common] - Network disconnect!
[18:31:46:498] [28099:00000002] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
```

Also tried version 2.0.0 RC4 but it manifests the same.

Connection from Fedora 30 (5e672d474e0d8fb5560f1068d4b83328fd8e41ca / 20190918) to the guest worked fine. Tried this revision as well but no luck.

**Application details**
* Version of FreeRDP: e873e4f0042dd157f68ae99adb4dc9dcd167ca29 & 2.0.0 RC4
* Command line used: `xfreerdp /v:192.168.1.235:5912`
* output of `/buildconfig`:

```
This is FreeRDP version 2.0.0-dev5 (5bc8da79e)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF= HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -m64 -O3 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 6.5.0
Target architecture: 
```

* OS version connecting to: OpenIndiana 2019.04 with VirtualBox 6.0.8 (host & guest)
* If available the log output from a run with `/log-level:trace` : 

[xfreerdp.debug.txt](https://github.com/FreeRDP/FreeRDP/files/3443280/xfreerdp.debug.txt)
[xfreerdp.trace.txt](https://github.com/FreeRDP/FreeRDP/files/3443281/xfreerdp.trace.txt)
[xfreerdp.truss.txt](https://github.com/FreeRDP/FreeRDP/files/3443375/xfreerdp.truss.txt)

**Comment by Mno-hime** [comment]
It works fine with `-pthread` like this (GCC used here):
```patch
--- FreeRDP-e873e4f0042dd157f68ae99adb4dc9dcd167ca29/CMakeLists.txt	2019-07-29 10:07:13.000000000 +0000
+++ FreeRDP-e873e4f0042dd157f68ae99adb4dc9dcd167ca29/CMakeLists.txt.new	2019-07-29 19:21:24.823354515 +0000
@@ -263,6 +263,7 @@ if(CMAKE_COMPILER_IS_GNUCC)
 
 	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")
 
+	set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread")
 	CHECK_C_COMPILER_FLAG (-Wno-unused-result Wno-unused-result)
 	if(Wno-unused-result)
 		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-result")
```

**Comment by akallabeth** [comment]
@Mno-hime the diff is strange, might that be a bug in your system?
We link `pthread` privately to `WinPR` and `xfreerdp` which are the places we use it.
What does your `CMakeLists.txt` say about pthread detection?

**Comment by akallabeth** [comment]
@Mno-hime and more importantely, is `openssl` properly linked against `pthread` in your system?

**Comment by pyhalov** [comment]
It's not related to pthread library, it's about -D_REENTRANT flag set by GCC when '-pthread' is passed to it. This clearly fixes something. Would be good to find out what exactly :)

**Comment by btaroli** [comment]
Just adding another voice here to let folks know that those of us using VirtualBox still rely upon these things, and it seems even the latest releases are so affected. I managed to find a older build of the Windows client from July that works, but the latest ones definitely do not. I'm OK sticking with an older build for now, but in some cases (like Linux repos) this may not be possible. May have to try and find older sources to  build from if possible.

I should also point out that rdesktop project has seen connection issues past 1.8.4, as they work to freshen things up for new RDP features. There may be common thread. That said, if anyone knows of a way to adjust the VBox VRDE/VRDP configuration to better work with more recent freerdp builds, I'm definitely game for that.
