### ISSUE TITLE
USB redirection not working to Windows 8.1 VM

### ISSUE THREAD

**Issue by kevxlreee** [FreeRDP/FreeRDP#5516]
Running xfreerdp from apt universe repository on Ubuntu 18.04 LTS. Trying to redirect the USB camera device which `lsusb` identifies as: `Bus 001 Device 005: ID 04f2:b52c Chicony Electronics Co., Ltd` to a Windows 8.1 VM in RDS 2016 virtual machine based deployment.

Running `xfreerdp /v:10.1 /cert-ignore /u:user /d:d /p:p /load-balance-info:”tsv://VMResource.1.lbi” /f /sound /rfx /dvc:urbdrc,id,dev:04f2:b52c` appears to run properly as no `dvc` or urbdrc errors appear, but the Windows VM does not recognize any USB devices that should be redirected.

The Windows VM is configured to allow all USB redirection, RemoteFX USB devices, etc, as detailed here: [https://stackoverflow.com/a/34723097](https://stackoverflow.com/a/34723097)

Is there any specific direction I should be focus on troubleshooting?

FreeRDP log:
```
loading channel rdpdr
loading channel rdpsnd
loading channel drdynvc
connected to 10.1:3389
creating directory /root/.config/freerdp
creating directory /root/.config/freerdp/certs
creating directory /root/.config/freerdp/server
certificate_store_open: error opening [/root/.config/freerdp/known_hosts] for writing
Unable to find a match for unix timezone: Etc/UTC
expected PDU_TYPE_DEMAND_ACTIVE 0001, got 000a
connected to 10.1:3389
creating directory /root/.config/freerdp
creating directory /root/.config/freerdp/certs
creating directory /root/.config/freerdp/server
certificate_store_open: error opening [/root/.config/freerdp/known_hosts] for writing
Unable to find a match for unix timezone: Etc/UTC
Loading Dynamic Virtual Channel urbdrc
VID: 0x04F2 PID: 0xB52C
Regist Device: Vid: 0x04F2 Pid: 0xB52C InterfaceClass = 0xE
Closed from X11
```

**Comment by akallabeth** [comment]
Try freerdp2 from the repos or our nightly builds.

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
Working on current nightly with my setup at least.
Please add some additional information to get this reopened.
