### ISSUE TITLE
Webex Teams: app window not listed in taskbar

### ISSUE THREAD

**Issue by tirolerstefan** [FreeRDP/FreeRDP#5546]
We have a terminal server Windows 2012 R2 where we connect with our Linux workstations to.

We use freerdp for running our Windows apps in our environment which really works well for most of them.
Now we introduced "Webex Teams" as new collaboration tool and when starting this one as remote app, it won't be listed as window in the window manager (e.g. no entry in the panel, window switching not possible, no window decoration).

Our invocation:
`xfreerdp /cert-tofu /u:[user...] /p:[pass...] /d:[domain...] /kbd:0x00000407 /bpp:32 /home-drive /app:"||CiscoCollabHost" /v:[server...]`

After a look into the code (of current master) and some debugging I found out that the application got the window style "**WS_POPUP**" which leads to this behaviour because popups get unlisted and undecorated.

```
void xf_SetWindowStyle(xfContext* xfc, xfAppWindow* appWindow, UINT32 style,
                       UINT32 ex_style)
[...]
	else if (style & WS_POPUP)
	{
        /* this includes dialogs, popups, etc, that need to be full-fledged windows */
        appWindow->is_transient = TRUE;
        window_type = xfc->_NET_WM_WINDOW_TYPE_DIALOG;
        xf_SetWindowUnlisted(xfc, appWindow->handle);
	}
[...]
```

So, this doesn't work for all applications, so maybe there is a way to support such applications to be listed, too?

**Comment by akallabeth** [comment]
First question here is does this work as you expect with mstsc?

**Comment by tirolerstefan** [comment]
I did a test with with the Microsoft RDC tool (mstsc) and could start Webex Teams as "Start Program". It will be displayed within an own frame (RDC connection frame) with listing in the Windows task bar.
