### ISSUE TITLE
type cast cannot convert from __m128i to char  

### ISSUE THREAD

**Issue by tooheart-19811105** [FreeRDP/FreeRDP#5550]
sorry  my english is not good  

 environmental details mentioned below:
•Visual Studio 2012
•Windows 7 Professional 64-bit Operating system

I  build  FREERDP by Visual Studio 2012 for windows 
and error below
 Error C2440: 'initializing' : cannot convert from '__m128i' to 'char', 
files is FreeRDP\libfreerdp\primitives\prim_YUV_ssse3.c
code below 
 	const __m128i mapY[] =
	{
		_mm_set_epi32(0x80800380, 0x80800280, 0x80800180, 0x80800080),
		_mm_set_epi32(0x80800780, 0x80800680, 0x80800580, 0x80800480),
		_mm_set_epi32(0x80800B80, 0x80800A80, 0x80800980, 0x80800880),
		_mm_set_epi32(0x80800F80, 0x80800E80, 0x80800D80, 0x80800C80)
	};
	const __m128i mapUV[] =
	{
		_mm_set_epi32(0x80038002, 0x80018000, 0x80808080, 0x80808080),
		_mm_set_epi32(0x80078006, 0x80058004, 0x80808080, 0x80808080),
		_mm_set_epi32(0x800B800A, 0x80098008, 0x80808080, 0x80808080),
		_mm_set_epi32(0x800F800E, 0x800D800C, 0x80808080, 0x80808080)
	};
	const __m128i mask[] =
	{
		_mm_set_epi32(0x80038080, 0x80028080, 0x80018080, 0x80008080),
		_mm_set_epi32(0x80800380, 0x80800280, 0x80800180, 0x80800080),
		_mm_set_epi32(0x80808003, 0x80808002, 0x80808001, 0x80808000)
	};

how can I build it ,  or I used wrong Visual Studio ?

**Comment by akallabeth** [comment]
Either deactivate ` -DWITH_SSE2=OFF` or use a newer compiler
