### ISSUE TITLE
audin for freerdp-master (a9ecd6a6) fails to load on RHEL7

### ISSUE THREAD

**Issue by liverwust** [FreeRDP/FreeRDP#5554]
We appreciate many of the new features of FreeRDP 2 in our environment, and so we rebuild the Fedora 28 version on our RHEL7 systems. The f28 version is currently based on master, commit a9ecd6a6 to be precise. We just upgraded to this from our older build, which was based on b9073240.

Now that we have upgraded, the audin plugin fails to load. See below:
`[11:16:29:544] [24631:24659] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr`
`[11:16:29:544] [24631:24659] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd`
`[11:16:29:547] [24631:24659] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure VirtualChannelEntryEx: /usr/lib64/freerdp2/libaudin-client.so: undefined symbol: VirtualChannelEntryEx`
`[11:16:29:549] [24631:24659] [WARN][com.freerdp.addin] - Failed to load channel audin [(nil)]`
`[11:16:29:552] [24631:24659] [ERROR][com.winpr.library] - GetProcAddress: could not find procedure VirtualChannelEntry: /usr/lib64/freerdp2/libaudin-client.so: undefined symbol: VirtualChannelEntry`
`[11:16:29:554] [24631:24659] [WARN][com.freerdp.addin] - Failed to load channel audin [(nil)]`
`[11:16:29:554] [24631:24659] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_PRE_CONNECT_FAILED [0x00020001]`
`[11:16:29:554] [24631:24659] [ERROR][com.freerdp.core] - freerdp_pre_connect failed`

This happens when attempting to load a .RDP file which contains the following directive:

> audiocapturemode:1:1

We believe that commit b4e1e9a1 may be related to this problem, given that it changed the way that the audin channel plugin is loaded and given that the error messages are related to the plugin entry point (_VirtualChannelEntryEx_, versus audin's _DVCPluginEntry_).

**Comment by akallabeth** [comment]
@liverwust thank you for the report, looks as if I´ve used the wrong loader function.
Should be fixed in #5555
