### ISSUE TITLE
dynamic-resolution does not work properly

### ISSUE THREAD

**Issue by mfernau** [FreeRDP/FreeRDP#5559]
I connect to my server with the following command:
`$> xfreerdp "/t:Terminalserver" +wallpaper +menu-anims +window-drag +compression +clipboard +decorations /cert-ignore +fonts /v:10.0.0.7 /dynamic-resolution /u:martin.fernau /p:xxx /log-level:trace`

After resizing the window the remote systems is not reflecting the resolution changes:
![Screenshot_20190830_143458](https://user-images.githubusercontent.com/9843274/64021173-a562d880-cb33-11e9-86e5-ea14c9cb4b81.png)

**Expected behavior**
I expect that the remote resolution is adjusted to reflect my new windows size

** Application details
* Version of FreeRDP
-> FreeRDP version 2.0.0-dev5 (2693389a+debian)
* Command line used
-> see above
* output of `/buildconfig`
-> [build-config.txt](https://github.com/FreeRDP/FreeRDP/files/3559911/build-config.txt)

* OS version connecting to
-> Windows Server 2012
* If available the log output from a run with `/log-level:trace` 
-> [trace.log](https://github.com/FreeRDP/FreeRDP/files/3559932/trace.log)

**Desktop (please complete the following information):**
-> Ubuntu 19.04

-> Chrome

-> 76.0.3809.132

**Comment by akallabeth** [comment]
Is the server side support for dynamic resolution activated?

**Comment by mfernau** [comment]
Can you please tell me how to check this settings? I goggled around but could not find an information how to enable/disable dynamic resolution for windows server.

Maybe I misunderstand this feature at all. I hoped that I'm able to start my session with defined width/height, switch to fullscreeen later and have resized the remote screen to my host resolution.

**Comment by akallabeth** [comment]
@mfernau sorry, forgot this one. I actually don´t know the exact setting, sorry. but I can confirm this works against server 2012r2 standard. (default settings, if that helps)
As for the feature, it requires server side support to switch the resolution during a session and client side support to report the resolution/dpi/... to the server.
