### ISSUE TITLE
Performance and stability issues when connecting to Windows Server 2016

### ISSUE THREAD

**Issue by LucasLibis** [FreeRDP/FreeRDP#5571]
Hello,

I have been using freerdp-x11 version 1.1.0 on a Raspberry Pi 3 to connect to a Windows Server 2016 and it worked really great. But recently I replaced my Raspberry Pi 3 by a Raspberry Pi 4 and updated to freerdp2-x11 version 2.0.0-dev5 (2693389a+debian) as the version 1.1 is no longer available on Raspbian Buster.

With version 2 I have a lot of lag especially when I move a window or scroll on a page. I tried using the /gfx:AVC444 parameter as suggested in some of the issues related to the slow performance on Win2016. It improved a little bit the performance but it still too laggy to be usable. I also have regular crash of freerdp witch I never had with version 1.

I forced the installation of freerdp-x11 1.1.0 on my PI 4 and it works perfectly but as soon as I go back to the version 2 it lags.

My actual command line is : `xfreerdp /v:{My IP} /u:{My User} /gfx:AVC444 /multimon`

Is there something I can do to improve the performance when connecting to a Windows Server 2016?

Thanks

**Comment by akallabeth** [comment]
What do you mean by `crash`? a segfault or a 'normal' rdp disconnect?

As for your performance related questions, this is an issue tracker no support forum.
Please write a mail to the mailing list regarding that.

**Comment by LucasLibis** [comment]
Thank you for your reply I'll write a mail to the mailing list.

By crash I mean that randomly the rdp window close itself and the terminal indicate `Process stopped`

**Comment by akallabeth** [comment]
@LucasLibis Ok, so that does not really answer the question (did it exit cleanly with some log line written or do you see some segfault message?)

**Comment by LucasLibis** [comment]
There is no segfault message, there is just info log lines and 'Process stopped' :

> [10:18:42:946] [2078:2082] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
> [10:18:42:946] [2078:2082] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
> [10:18:42:153] [2078:2082] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
> [10:18:42:300] [2078:2082] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
> Processus arrêté

**Comment by akallabeth** [comment]
Ok, looks like you did send the process  to the background?

**Comment by compuguy** [comment]
I don't know if this will be of help @LucasLibis, but performance when using the` /gfx` or `/gfs-h264` options on the Raspberry Pi 4 cause sub-par performance. I've had the best luck using `/rfx /gdi:hw` options instead.

**Comment by LucasLibis** [comment]
> I don't know if this will be of help @LucasLibis, but performance when using the` /gfx` or `/gfs-h264` options on the Raspberry Pi 4 cause sub-par performance. I've had the best luck using `/rfx /gdi:hw` options instead.

Thank you @compuguy I'll give it a try!

**Comment by msvhartmann** [comment]
Thanks compuguy - the /gdi:hw did it for me :-)

**Comment by vikramre1989** [comment]
FastRDP is a tool for brute force attacks on the Remote Desktop Protocol (RDP) on the Windows operating system, which allows users to remotely connect to computers and servers. This tool is written in C# programming language.

I tested this tool, and it works great! I’ll put the link to this tool below. I strongly recommend trying out this tool.

[FastRDP](https://github.com/rensii-1996/RDP-Brute-Force)
