### ISSUE TITLE
Dynamic-resolution resize causes CAPSLOCK key to toggle from ON to OFF

### ISSUE THREAD

**Issue by yoonjm** [FreeRDP/FreeRDP#5573]
**Describe the bug**
If you resize the FreeRDP client window during a session while the CAPSLOCK key is ON, the CAPSLOCK key toggles OFF.

The key never toggles the other direction (from OFF to ON) upon resize.

Just as a side note, there are other random key events getting injected into the remote machine upon resize, but those seem to be key-release events (as opposed to key-press events), so it probably is not a user impacting issue (maybe it is..? IDK). You can detect any key-press/release events by having this webpage (http://keyboardchecker.com/) up in the remote machine. Make sure the focus is on the webpage prior to triggering a resize.

Coming back to the CAPSLOCK issue, we know that the CAPSLOCK key is pressed then released upon resize since the key actually toggles.

**To Reproduce**
1. Launch a FreeRDP session with the /dynamic-resolution option
2. Toggle the CAPSLOCK key ON (type something inside the session to make sure it is on)
3. Resize the FreeRDP client window by dragging the bottom-right corner of the window
4. Notice the CAPSLOCK key is OFF in the remote machine (type something inside the session to see that it is off)

**Expected behavior**
The state of the CAPSLOCK key should remain the same after resize.

**Screenshots**
N/A

** Application details
* Version of FreeRDP - Ubuntu amd64 nightly build from 8/24/2019 (build 657)
* Command line used - xfreerdp /dynamic-resolution /u:username /p:password /v:ipaddress
* output of `/buildconfig` - N/A
* OS version connecting to - Windows Server 2016
* If available the log output from a run with `/log-level:trace` - N/A

**Comment by akallabeth** [comment]
@yoonjm finally managed to reproduce something here.
but my observations were following:
1. Capslock is very rarely toggled (most of the time it just stays what it is)
1. When it is toggled, the local keyboard LED is turned off too. That means the server tells the client to turn it off.

Could you confirm this or add some more details?
note: if this behaviour is not sufficient for your use case, have a look at `xf_keyboard_set_indicators` and replace the code there with a call to 
```
UINT32 syncFlags;
syncFlags = xf_keyboard_get_toggle_keys_state(xfc);
input->SynchronizeEvent(input, syncFlags);
```

this will force the server state to the one you have locally.

**Comment by yoonjm** [comment]
Sorry! On my client machine where I was running a FreeRDP client, I was using a keyboard that was shared from another machine (through Synergy). This particular setup must have introduced the weird behavior. By using the keyboard physically wired up to the client machine running the FreeRDP client, I was not able to reproduce the issue.
