### ISSUE TITLE
Error 133 error LNK1181: cannot open input file 'dxguid.lib' FreeRDP\server\Windows\LINK wfreerdp-server

### ISSUE THREAD

**Issue by FredLaffitte** [FreeRDP/FreeRDP#5575]
Hi all, I try to compile using MS Visual C++ Express 2010, but I am receiving this error:
Error 133 error LNK1181: cannot open input file 'dxguid.lib' FreeRDP\server\Windows\LINK wfreerdp-server

Anyone can help-me, please?
Other question:
If I compile under Windows 7 x64, may can I use the dlls under Windows 10 x64 or I need to compile a Windows 10 x64 version and also, if I use under Windows 10 x86, can I use tha same dlls or I need to compile each specific versions?

Thanks in advance.

Best regards.

**Comment by akallabeth** [comment]
Support questions please via irc or the mailing list.
Thx
