### ISSUE TITLE
SessionView graphic update problem

### ISSUE THREAD

**Issue by amratsingh** [FreeRDP/FreeRDP#5576]
We are using FreeRDP library in our android project to use a windows application through remote. Whenever we tap button on windows application, it get hang on clicked button state. It only get changed when we tap on any other button. Although it is not the case every time but it happens frequently.

We have tried optimizing options as well but result was same. It looks like graphics are not updating or refreshing the SessionView sometimes after button touch.

**Comment by akallabeth** [comment]
Please provide some more details (what do you use, afreerdp does not support rails).

Support questions please via irc or the mailing list.
Thx

**Comment by amratsingh** [comment]
> Please provide some more details (what do you use, afreerdp does not support rails).
> 
> Support questions please via irc or the mailing list.
> Thx

But we it is working fine on iOS which is older version of FreeRDP (1.2.0-beta1+android9).

We are not talking about rails and also we have already posted in mailing list but no reply.

![button_states](https://user-images.githubusercontent.com/15189911/64552137-40d62380-d354-11e9-9e62-c400e5bd57ac.png)

**Comment by akallabeth** [comment]
Sorry, learn some patience!
Your mail is not even 5 hours old!

Annoying by spamming all channels will get you answers later ;)

**Comment by amratsingh** [comment]
> Sorry, learn some patience!
> Your mail is not even 5 hours old!
> 
> Annoying by spamming all channels will get you answers later ;)

Trying all sources is not spamming.
