### ISSUE TITLE
ERROR Could NOT find OpenH264

### ISSUE THREAD

**Issue by Zoson** [FreeRDP/FreeRDP#5579]
Is there any way to set up openh264?  I have download the library and all files in "include" of openh264 ,and set up X264_INCLUDE_DIR and X264_LIBARAY ! But when I run "cmake -DWITH_OPENH264 .." I get these errors, as follows:

[CMake] -- Skipping optional feature x264 for codec (use x264 library)
 [CMake] --     Enable feature x264 using "-DWITH_X264=ON"
[CMake] -- Finding optional feature OpenH264 for codec (use OpenH264 library)
 [CMake] CMake Error at D:/xxx/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
 [CMake]   Could NOT find OpenH264 (missing: OPENH264_LIBRARY OPENH264_INCLUDE_DIR)
 [CMake] Call Stack (most recent call first):
 [CMake]   D:/xxxx/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.14/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
 [CMake]   **cmake/FindOpenH264.cmake**:28 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
 [CMake]   cmake/FindFeature.cmake:31 (find_package)
 [CMake]   CMakeLists.txt:870 (find_feature)

Does It seem like I need the version of cmake of openh264? But I didn't find out.

**Comment by akallabeth** [comment]
I'd try setting the openh264 variables instead of x264 ;)
Support questions please on irc or the mailing list.

**Comment by Zoson** [comment]
@akallabeth sorry, but yes, I really set the openh264 variable "ON", but it didnt find the openh264 through "findopenh264.cmake" ,it seems like it's required to setup openh264 in cmake!?

**Comment by akallabeth** [comment]
Yes, then read the header of the findopenh264 and use those variables.

**Comment by Zoson** [comment]
@akallabeth Thanks  ;)

**Comment by Zoson** [comment]
@akallabeth I realize I pose a very stupid question！

**Comment by akallabeth** [comment]
@Zoson happens ^^ everyone has such days
