### ISSUE TITLE
Clipboard returns first character only

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#5594]
**Describe the bug**
When copy and pasting a line of text from notepad on the remote session to the local host, only the first character of the line is returned. 

**To Reproduce**
1. Remote to W2K12 R2 RDS Server from Debian Buster using xfreerdp with clipboard enabled. Start notepad and enter a line of text. Return back to the local host to paste only to find that just the first character of the line is transmitted through the channel.

**Expected behavior**
The complete line of text should be returned to the local host.

**Screenshots**
N/A

** Application details
* Version of FreeRDP
This is the latest nightly snapshot as of 09/12/2019
This is FreeRDP version 2.0.0-dev5 (ac8be3cdc)
* Command line used
/opt/freerdp-nightly/bin/xfreerdp /gfx +gfx-progressive +old-license /u:Administrator /p:xxxxxx /size:1600x800 +clipboard /drive:Temp,/home/user/Temp /d:DOMAIN /admin /sec:nla /cert-ignore /v:192.168.0.XX
* output of `/buildconfig`
This is FreeRDP version 2.0.0-dev5 (ac8be3cdc)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp-nightly-2.0.0+0~20190912014826.699~1.gbpac8be3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 8.3.0
Target architecture: x64
* OS version connecting to
Windows 2012 R2 Server Standard with RDS role.
* If available the log output from a run with `/log-level:trace` 

**Desktop (please complete the following information):**
Debian 10 Buster (Gnome using Wayland)
N/A

**Additional context**
Copy and pasting of text works the other way, i.e., from local Linux host back to remote notepad app.

**Comment by akallabeth** [comment]
just tested on `debian buster`, all current updates applied with 
`
xfreerdp /version
This is FreeRDP version 2.0.0-dev5 (2693389a+debian)
`
as well as
`
/opt/freerdp-nightly/bin/xfreerdp /version
This is FreeRDP version 2.0.0-dev5 (f5e749f04)
`

all works as expected.
You don´t have, by chance, some clipboard manager in use?
would check that first, with some settings there might interfere here (at least that has always been the case when such issues have been reported previously)

**Comment by user-72632** [comment]
No, I do not have any clipboard manager running other than the standard install. After rebooting the Linux host the next day and retrying it, it seems to work now. This happens occasionally if I have had my Linux host up all day doing many remote connections to different servers. In any event, I can't seem to recreate it so this issue can be closed.

I do have one other quick question, when did the change happen with drive redirection naming. That is, if you use the drive redirection syntax such as:  /drive:Temp,/home/user/Temp
then the remote drive would show up as "Temp on COMPUTERNAME". Now it shows up as:
_home_user_Temp on COMPUTERNAME, is this correct now?

**Comment by akallabeth** [comment]
@user-72632 ok, closing this then.
Drive naming shouldn't have changed, you're using current nightly?

**Comment by user-72632** [comment]
@akallabeth yes that is correct. I will also try my compile of the latest master but I am pretty sure it just started doing this for a month or two.

**Comment by user-72632** [comment]
@akallabeth as a followup, my latest compile of 2.0.0-dev5 (f5e749f04) also shows this naming convention for drive redirection. HTH

**Comment by akallabeth** [comment]
Strange, just tried with current master and don't have that. What is your remote os?

**Comment by user-72632** [comment]
Several Windows 2012 R2 Servers, Standard with RDS role installed with the latest Windows Updates applied. Again, this just started several months ago. Probably a Windows Update change to RDS somewhere along the way.
