### ISSUE TITLE
Does FreeRDP work on 32-bit architecture?

### ISSUE THREAD

**Issue by philippemnoel** [FreeRDP/FreeRDP#5599]
Specifically I am trying to use FreeRDP from a Raspberry Pi 4B using Raspbian Buster, but when I tried to compile the nightly build it says that the architecture is not compatible. The Pi 4B board has a 64-bit processor, but Raspbian Buster is 32-bit, is there a way to make it work at all?

**Comment by akallabeth** [comment]
Hi, sorry for the delayed response, was afk for this week.
yes, it does, architecture should not matter as long as all dependencies are installed for the compile.
