### ISSUE TITLE
Changes to settings of redirected printers not retained on server

### ISSUE THREAD

**Issue by ipitcher** [FreeRDP/FreeRDP#560]
I know this is seemingly a server-side issue, but I just tested with MSTSC (version 6.1.7601.17514) on a Windows 7 client connecting to both a Windows 2003 Server and a Windows 7 Professional machine, and changes to the settings persisted across sessions.  Any settings made while connecting with FreeRDP 1.0.1 (current git master branch as of a few hours ago) were lost upon logout or disconnection.

Note, I was sure to heed the information here:  http://support.microsoft.com/kb/243942

Otherwise, the redirected printers work great.  Not too much use though, unless I can work this out.

**Comment by akallabeth** [comment]
@ipitcher Is this still an issue with master?

**Comment by bmiklautz** [comment]
Closing du to inactivity. Please re-open or create a new issue if this problem still exists on the current mater branch.

**Comment by hardening** [comment]
I'm quite sure the issue is still there as we don't handle the message to handle the printer configuration
