### ISSUE TITLE
Remote apps launched from within an RDP session not displaying correctly on Windows Server 2019

### ISSUE THREAD

**Issue by sebastianuw** [FreeRDP/FreeRDP#5600]
If I connect to a Windows 2019 session server through xfreerdp and launch a RemoteApp ( RDP file with “remoteapplicationmode:i:1” set ) with mstsc.exe (on the session server), the remote app does not display. It will show up in the taskbar, but the remote app’s window will either not display or if the remote app starts maximized it will be shrunk to an unreadable state. 
If I change the remoteapp’s rdp file to “remoteapplicationmode:i:0” the application loads correctly in a full session window.

This only applies to FreeRDP (if I connect to the session server with the Microsoft Windows and Mac clients, remote apps work fine). This problem does not exist on Windows 2016 server, only 2019.

I checked out the latest FreeRDP from the git repo today, and still experience this problem.

**Comment by sebastianuw** [comment]
I am connecting to the session server with the following flags: /cert-ignore /f /u: /gu /p: /gp: /drive:hotplug,* /sound:sys:pulse,format:1,quality:high /microphone:sys:pulse,format:1,quality:high /gt:http +auto-reconnect /network:lan

With this RDP file for the session server:
redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:0
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:1
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:gatewayserver.com
gatewayhostname:s:gatewayserver.com
workspace id:s:gatewayserver.com
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.Box
use multimon:i:1
alternate full address:s:gatewayserver.com

The remoteapp rdp file generated by Microsoft's tools looks like this:
redirectclipboard:i:1
redirectprinters:i:1
redirectcomports:i:0
redirectsmartcards:i:1
devicestoredirect:s:*
drivestoredirect:s:*
redirectdrives:i:1
session bpp:i:32
prompt for credentials on client:i:1
span monitors:i:1
use multimon:i:1
remoteapplicationmode:i:1
server port:i:3389
allow font smoothing:i:1
promptcredentialonce:i:1
videoplaybackmode:i:1
audiocapturemode:i:1
gatewayusagemethod:i:1
gatewayprofileusagemethod:i:1
gatewaycredentialssource:i:0
full address:s:gatewayserver.com
alternate shell:s:||EPSSpreadsheet
remoteapplicationprogram:s:||EPSSpreadsheet
gatewayhostname:s:gatewayserver.com
remoteapplicationname:s:EPS-Excel-Spreadsheet
remoteapplicationcmdline:s:
workspace id:s:gatewayserver.com
use redirection server name:i:1
loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.RemoteApps
alternate full address:s:gatewayserver.com

**Comment by sebastianuw** [comment]
Here is an example of a remote app not loading its window:

![remoteappnotstarting](https://user-images.githubusercontent.com/16311354/64991239-5aacc480-d886-11e9-97c0-99e647b3883f.jpg)

And here is an example of a maximized remote app being shrunk:

![remoteappstartingsmall](https://user-images.githubusercontent.com/16311354/64991422-afe8d600-d886-11e9-9885-4444bf5190a1.jpg)

The app still works in term of input, but not exactly usable. This example is with a bat file, but it also applies to Photoshop and other programs we have set up as remote apps.

**Comment by sebastianuw** [comment]
After some investigation, I found disabling the following on the remote app server resolved the issue:

Configure H.264/AVC hardware encoding for Remote Desktop Connections

Prioritize  H.264/AVC 444 graphics mode for Remote Desktop Connections

**Comment by akallabeth** [comment]
Ok, just wanted to answer.
Depending on settings ms has still some isdues with rails.
Specifically networkautodetect/bandwithautodetect trigger it with freerdp (it enables gfx with avc444)

**Comment by akallabeth** [comment]
So, closing as we can not do more than wait until they fix it (or disable server side)
