### ISSUE TITLE
Strange UI behavior when moving File Explorer window with context menus

### ISSUE THREAD

**Issue by user-72632** [FreeRDP/FreeRDP#5601]
First, I apologize if this is not FreeRDP related, I just need to rule it out. When using any FreeRDP version from RC4 to present and connecting to Win 8/10/2012 I have a strange UI issue that I was hoping others might see as well. Here is the scenario:

After a FreeRDP connection is established to a Windows 8/10/2012 machine, I start the File Explorer. Then I try to move the window using the following method: right-click the toolbar to bring up the context menu, left-click to select Move. When the All-Direction mouse pointer appears and then I try to use the mouse (left-click) to move the window. The expected behavior is to move the window. None of my three versions of Windows allow me to move the window. I can manually move the window using the arrow keys but not using the mouse. I used an old version of Windows 7 to see what it does and the expected behavior works.

Has anyone else seen this behavior? Again, I apologize if this is not related to this group. If not, I will submit as a bug to Microsoft.

**Comment by user-72632** [comment]
Can anyone confirm they are or are not seeing this Windows behavior as well please?

**Comment by akallabeth** [comment]
Sorry for the delay, but I was afk this week.
As for your question, you should add some details to what you are actually using (xfreerdp? wfreerdp? ...)
Anyway, it may be better to use the mailing list or IRC for such questions as this does not seem to be a 'bug' but rather a question.
