### ISSUE TITLE
RDP-Gateway using websocket transport

### ISSUE THREAD

**Issue by liorlevtov** [FreeRDP/FreeRDP#5602]
**Is your feature request related to a problem? Please describe.**
Currently, as I see, the FreeRDP and all dependent projects (reminna, xfreerdp) supports RDP-Gateway with HTTP Polling (RDG_IN_DATA, RDG_OUT_DATA), a more modern approach for Gateway transport is using Websocket which both IN and OUT are multiplexed on the same connection.

**Describe the solution you'd like**
support the client to initiate RDP-Gateway connection with WebSocket.
that way we can use this awesome tool for connecting our RDP-gateway.

**Comment by hardening** [comment]
AFAICT this kind of transport is not supported by MS servers, or do you have a link to some specs ?

**Comment by liorlevtov** [comment]
sure,
[from [MS-TSGU].pdf](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tsgu/0007d661-a86d-4e8f-89f7-7f77f8824188)
1.3.2.1.1 Connection Setup and Authentication Phase
The connection setup and authentication phase only involves the exchange of HTTP header information and consists of three operations:

- Create OUT channel: An HTTP1.1 connectionisestablished**.If the RDG server and client both support the WebSocket protocol ([RFC6455]), then this connection is used for duplex communication between the RDG client and server;** otherwise, this connection is used only for outbound communication from the RDG server.<5> WebSocket support is negotiated using the Opening Handshake as specified in [RFC6455] section 1.3.


- CreateINchannel: A second HTTP 1.1 connection is established for inbound communication to the RDG server if the RDG server and client don't support the WebSocket protocol. In this case, the OUT channel is used only for outbound communication.

**Comment by hardening** [comment]
@liorlevtov I'd be interested by a capture of this traffic.

**Comment by liorlevtov** [comment]
tcp.stream eq 7


[ms-client-to-rdp-gw-2.pcapng.zip](https://github.com/FreeRDP/FreeRDP/files/3630195/ms-client-to-rdp-gw-2.pcapng.zip)

**Comment by hardening** [comment]
@liorlevtov no promise, but I may have a look at implementing it.

**Comment by hardening** [comment]
@liorlevtov no promise, but I may have a look at implementing it.

**Comment by liorlevtov** [comment]
anyhow much appreciated!

**Comment by michdu** [comment]
This would definitely be super useful!

**Comment by hardening** [comment]
If some of you guys want to finance that, I would implement it with pleasure ;)

**Comment by bolkedebruin** [comment]
I have created a implementation of the gateway protocol here: https://github.com/bolkedebruin/rdpgw . It supports both websockets and the legacy protocol.

The websockets protocol is pretty much the same as the HTTP protocol, except that it is obviously bi-directional over one channel.

**Comment by akarl10** [comment]
I have implemented this feature, but since I have only limited servers to try out if all works well it would be nice if someone wants to try it.
its here: https://github.com/akarl10/FreeRDP/tree/websocket

It is based on #6731, so i intend to open a push request after that gets merged. In the mean time it would certainly help if my websocket implementation gets tested by someone.

**Comment by bolkedebruin** [comment]
I can have a look

**Comment by akarl10** [comment]
#6752

**Comment by akarl10** [comment]
> I can have a look

have you already tested if this websocket implementation works with your setup(s)?

**Comment by akallabeth** [comment]
@akarl10 sorry, was on vacation, still cleaning up my backlog
