### ISSUE TITLE
Drive Redirection naming convention has changed.

### ISSUE THREAD

**Issue by user-72632** [FreeRDP/FreeRDP#5603]
Using the RC4 release from November, if you use drive redirection with the following syntax: /drive:Temp,/home/user/Temp  then the remote drive would show up as "Temp on COMPUTERNAME". As of the current release from master, it now shows up as:
_home_user_Temp on COMPUTERNAME. I don't have time to bisect this right now but I wanted to let the developers know that something has changed since then. I use a variety of Linux distros to connect to Windows 8/10/2012 VMs, all with the same result.

**Comment by user-72632** [comment]
Update: I have an Ubuntu 16.04.6 LTS client that still exhibits the correct behavior with the latest master, so something has changed on the client side of Linux, i.e., Ubuntu 18.04 and Debian 10 Wayland.

**Comment by akallabeth** [comment]
@user-72632 are you sure you´re testing on master? with 02a65840e8016762afbdcadf18303d641ec1c15d it is working as expected.
Which version did you test with?

**Comment by user-72632** [comment]
This one has me confused. I used the latest master on three different Linux distros: Ubuntu 16.04 LTS, Ubuntu 18.04 LTS, and Debian 10 Buster/Wayland. The only one that shows the correct drive redirection format is 16.04. Both 18 and Buster show the "_home_user_Temp on COMPUTERNAME". I really don't know what to say other than maybe a package I am compiling with has changed somewhere. Without really knowing the correct dependencies (I think the ones from the WiKi are old), I can't be sure where to look. I have not found an easy way to parse the dependencies out of the nightly build configuration. Feel free to close this if you are seeing the correct format; I just thought I would bring it up in case anyone else has seen this as well.

**Comment by akallabeth** [comment]
@user-72632 ok, strange. This is not dependent on libraries but core functionality.
Do you use self compiled versions, our nightlies or distro packages?
The distro versions might be a bit older.

**Comment by user-72632** [comment]
I use both the nightlies and my self-compiled versions. I attached the latest buildconfig from the Ubuntu 16.04 (self compile) that works and the Debian Buster (self compile) that does not. HTH
[buildconfig.txt](https://github.com/FreeRDP/FreeRDP/files/3643780/buildconfig.txt)

**Comment by akallabeth** [comment]
Ok, both to the same target server with the same commandline?
(Need to find the diff)

**Comment by akallabeth** [comment]
You mind checking if there is a folder that has the same name as the name for the drive in your workingdirectory? (Maybe some misdetection...)

**Comment by user-72632** [comment]
Here is my command line that I use to connect in all situations and to the same target:
$FBIN/xfreerdp /f /drive:home,/home/$user "/printer:MFC-8910DW,Brother MFC-8910DW Printer" \
                      /network:auto /gfx +gfx-progressive +old-license /d:BCS /sec:nla /cert-ignore \
                      -themes -wallpaper +clipboard /u:$user /p:$pass /v:$IP /log-level:info >> $LOG 2>&1

I have done the following testing with these results: In ALL situations, when the following command line is used:  /drive:home,/home/$user  the result is everything looks fine on ALL distros. That is, the redirected drive shows up as: "home on COMPUTERNAME". In ALL distros, when the command line such as this: /drive:Temp,/home/$user/Temp  is used, then ALL distros report the problematic format with underscores. I checked for duplicate names and also renamed the "Templates" directory to make sure there was no clash.

So it would appear the standard /home/user syntax shows correctly and whenever you append a nther level directory, it shows the underscores.

**Comment by akallabeth** [comment]
You did start from /hom/user? Does /drive:xxx,/home/$user/Temp work?

**Comment by akallabeth** [comment]
Oh, and a stupid question, $user is defined? On my machines username is $USER

**Comment by akallabeth** [comment]
Ok, got it.
If both parameters are valid paths (`Temp` is a valid path in your working directory `/home/user`, `/home/user/Temp` is the absolute path then the what is the name what is the path algorithm takes the first match.

**Comment by user-72632** [comment]
I just tried your commit with my self-compile and it did not work for me. I also found out something I never new about the /drive syntax. That is, I always thought that you needed to have both the <name> and the <path> in the /drive syntax to form a correct mapping on the command line. I did not realize that you can just put the <name> and it would also work correctly. I just tried this with master and nightly and it works using just:
/drive:Temp shows correctly as "Temp on COMPUTERNAME". Just for fun I also tried /drive:/home/user/Temp which resulted in the same incorrect format with underscores. Here is another strange case, if you just use a different <name> other than the real relative name then it also works. For example, I used on master, /drive:mytemp,/home/user/Temp  and it works correctly by showing "mytemp on COMPUTERNAME". So, it looks like the path algo does not like when the <name> component of the command line has the same name as the last part in the actual <path>. I like just using only the relative name such as /drive:Temp on the command line as long as it exists. Again, I tried all this with both master and the latest nightly without your commit integrated to check this out on the existing implementation.

**Comment by akallabeth** [comment]
@user-72632 yes, need that to allow the relaxed handling from rdp files. The syntax with _ is for all cases a full path is also used for the name.

**Comment by user-72632** [comment]
OK, I just compiled your akallabeth:drive_prefer_absolute_path  branch and it does work as expected.  Don't know why my self-compile did not work the first time unless I picked up too early of a fix. Thanks for your help on this.  Is it considered improper form to use just the name on the /drive command line or should I continue to use the full name and path syntax?
