### ISSUE TITLE
Printer Redirection broken after #5569 Pull Request

### ISSUE THREAD

**Issue by user-72632** [FreeRDP/FreeRDP#5606]
The series of commits associated with PR #5569 has broken my longstanding Printer Redirection configuration using the following command line syntax:  

"/printer:MFC-8910DW,Brother MFC-8910DW Printer"

If any specific logs are needed then please advise.

**Comment by mfleisz** [comment]
@user-72632 a debug log (using `/log-level:debug` or `trace`) would indeed help a lot. Thanks!

**Comment by user-72632** [comment]
I have attached one text file containing the /log-level:DEBUG of the situation in error and when it completes correctly. Interestingly, when the redirection fails it errors with a 131 or NLA error which is not correct. HTH
[freerdp-logs-printer-redirection-errors.txt](https://github.com/FreeRDP/FreeRDP/files/3631680/freerdp-logs-printer-redirection-errors.txt)

**Comment by mfleisz** [comment]
@user-72632 Just a quick shot - can you give it a try with `/printer:MFC-8910DW,Brother MFC-8910DW Printer:cups`?

**Comment by user-72632** [comment]
Yes, I can confirm that the syntax:  "/printer:MFC-8910DW,Brother MFC-8910DW Printer:cups"  does work! Did I miss a documented change somewhere - apologies if I did.

Thanks

**Comment by mfleisz** [comment]
The problem is that no default backend is chosen when none is specified and therefore no driver is loaded by the channel so this is definitely a bug ... but at least we have a workaround :-)

**Comment by user-72632** [comment]
Thanks for the explanation; the FreeRDP developers and this software is truly amazing.
We use this software everyday and I don't think we say this enough - appreciate the hard work all of you put into this software to make it great!

**Comment by mfleisz** [comment]
Thanks for the kind words @user-72632! :-)

**Comment by akallabeth** [comment]
@user-72632 looks like this was my fault. #5609 should fix that.

**Comment by user-72632** [comment]
Sorry for the delay, but I just wanted to say that I tested #5606 out on our systems and it does in fact correct this bug. Thanks again.
