### ISSUE TITLE
FreeRDP Reading Windows Desktop Screen

### ISSUE THREAD

**Issue by philippemnoel** [FreeRDP/FreeRDP#5607]
Hi,

I'm trying to understand the source code -- where does FreeRDP read the server desktop screen and encode it? I can't seem to find the file(s) doing that.

Thanks!

**Comment by akallabeth** [comment]
This is an issue tracker, for such matters please use the mailing list or the IRC channel.

Additionally, please rephrase your question, it is not really easy to understand what you want.
