### ISSUE TITLE
Redirecting USB Microphone

### ISSUE THREAD

**Issue by cocorocho** [FreeRDP/FreeRDP#5627]
Have a weird issue. I have 3 linux distros and been using FreeRDP to redirecting Microphone through a USB Soundcard, however on Raspbian Stretch my Mic stopped working but on Lubuntu and Ubuntu Mate my mic still works.

On Lubuntu, Using FreeRDP 1.1.0 - Using /sound /microphone:sys:alsa  > it works,
On Mate, Using FreeRDP 1.1.0 - Using /sound /microphone:sys:alsa > it works,
On Raspbian Stretch, Using FreeRDP 1.1.0 - Using /sound /microphone:sys:alsa > **it worked but for some reason not anymore.**
On Raspbian Buster, Using FreeRDP 2.0 - Using /sound /microphone:sys:alsa > doesn't work

Tried almost all options like (/microphone, /microphone:sys:alsa, /microphone:sys:pulse etc.) but no luck.

Odd thing is redirection seems to be okay, i can see both redirected output and input device, i can get sound with no problem but mic doesn't capture any sound.

**Comment by akallabeth** [comment]
Please use the mailing list or irc for support.
