### ISSUE TITLE
Remoteapp on win10, force close without error

### ISSUE THREAD

**Issue by rootSectornet** [FreeRDP/FreeRDP#5631]
when remoteapp in win 10 to win 8 force close

WindowUpdate windowId=0x2228372 [ex]style=<0x80000000, 0x88 popup toolWindow topMost> show=hidden
WindowUpdate: WindowId: 0x00220094
{
	Style: 0x80000000 ExtendedStyle: 0x00000088
	Window Styles:	{
		WS_POPUP
	Extended Window Styles:	{
		WS_EX_TOOLWINDOW
		WS_EX_TOPMOST
	ShowState: 0
}

log stack on here

**Comment by akallabeth** [comment]
It looks like there is something missing here?

**Comment by rootSectornet** [comment]
I don't know, I get this log when app force close

**Comment by akallabeth** [comment]
fine. and we should guess what you are doing and using?
sorry, please provide a minimum set of information that we can at least imagine ;)

**Comment by rootSectornet** [comment]
i run this command
_wfreerdp.exe_  /v:192.168.60.17:3389 /u:user01@dexip /p:Rp123456 /cert-ignore /app:"winword.exe" +clipboard -bitmap-cache -offscreen-cache /f /gdi:sw /sec:rdp +auto-reconnect /gfx +glyph-cache_


and when the application is open, when I move the mouse directly force close

**Comment by akallabeth** [comment]
ok, and which version? self compiled, nightly, something from the depths of the internet? (`/buildconfig` should help, use `wfreerdp /buildconfig >log.txt 2>&1`)
what are you connecting to? (sorry, can't figure out if it is windows 10 or 8 from the description...)

**Comment by rootSectornet** [comment]
i get from https://cloudbase.it/freerdp-for-windows-nightly-builds/

and I use win 10 remote to win 8

**Comment by akallabeth** [comment]
Ok, checked locally. Seems to be a bug in the current windows builds.

**Comment by rootSectornet** [comment]
this issue is solved?

**Comment by pinonpierre** [comment]
> this issue is solved?

Just tested and it still doesn't work

**Comment by akallabeth** [comment]
@pieterjanc pull requests welcome.
