### ISSUE TITLE
WITH_CUPS redefinition in latest master compile

### ISSUE THREAD

**Issue by user-72632** [FreeRDP/FreeRDP#5635]
Getting a redefinition of WITH_CUPS in latest compile of master on Debian Buster. Sorry for the noise, not sure if any dev picked this up yet during the latest printer redirection updates
.......
Scanning dependencies of target printer-client-cups
[ 73%] Building C object channels/printer/client/cups/CMakeFiles/printer-client-cups.dir/printer_cups.c.o
In file included from /usr/local/src/FreeRDP/channels/printer/client/cups/printer_cups.c:24:
/usr/local/src/FreeRDP/build/config.h:39: warning: "WITH_CUPS" redefined
 #define WITH_CUPS
<command-line>: note: this is the location of the previous definition
[ 73%] Linking C static library libprinter-client-cups.a
[ 73%] Built target printer-client-cups
.............

**Comment by akallabeth** [comment]
Thanks for pointing that one out.
The referenced pr should fix that.
