### ISSUE TITLE
Application exits on new terminal

### ISSUE THREAD

**Issue by DWA-Sean** [FreeRDP/FreeRDP#5637]
**Describe the bug**

When running xfreerdp from a linux cli, the application will close if I spawn a new terminal.  This happens if I create a new pane in tmux, or if I launch terminal separately.

**To Reproduce**
1. Use xfreerdp
2. Click on 'terminal' launcher or 'ctrl-b' n in tmux
3. freerdp window closes immediately with a killed message on the command line

**Expected behavior**
I expect freerdp to keep operating while I create new terminals.

**Application details**
* freerdp-2.0.0-1.rc4.el7.x86_64
* Command line used
  * xfreerdp /d:animation /size:1280x1024 /u:USER /v:remotehost

* OS version connecting to
  * Windows 10

**Comment by akallabeth** [comment]
Sounds like an issue with your setup or distro.
Freerdp does not have such a 'feature'.
Using it daily on fedora 30, debian buster and never seen that...

**Comment by akallabeth** [comment]
Ok, just confirmed on fedora 30 with tmux.
can create a new terminal sesssion, even detach and xfreerdp is still running.
