### ISSUE TITLE
ctrl/caps swap: keyboard layout not supported (+general proposal)

### ISSUE THREAD

**Issue by m1027** [FreeRDP/FreeRDP#5649]
I've swapped the keys Ctrl / Caps on the local keyboard.

There is no keyboard layout in freerdp supporting this. Thus, either the
remote system does not receive Ctrl-C properly (but capital "C") or the local
system swaps to caps lock when not wanted...

Is there any solution?

If not: I see A LOT of annoying keyboard issues with freerdp. Why not have
an option to simply send the host's keys (like rdesktop)? I believe that
would help lifting the burden of keyboard layout maintainment.

**Comment by akallabeth** [comment]
@m1027 FreeRDP uses the approach to get the correct scancode for a local key pressed. Since that can not be done easily a reverse mapping is required.

As for the way rdesktop does it, it just opens another can of worms.
(to which keyboard layout do you translate, the scancodes are converted to real symbols server side again, keyboard shortcuts of the target OS start to fail, ...)

So, long story short, there is no solution that can satisfy everybody.

**Comment by akallabeth** [comment]
@m1027 Only solution for you might be to grab the keyboard entirely so that at least the host keyboard changes are ignored.

**Comment by m1027** [comment]
@akallabeth "no solution that can satisfy everybody": Thanks, I totally understand. But that's where selectable options come into play! :-) Seriously, besides all you mentioned: Personally I consider a keyboard not behaving as expected as a real issue.

Concerning +grab-keyboad: It grabbed indeed all, however, did not help with ctrl/caps swap. This still does not work.

**Comment by akallabeth** [comment]
for ` ctrl/caps` it does redirect the keys properly without changing local state and you just get the `ctrl` and `caps` just like without local modifications, correct?

btw, not behaving as expected depends a lot on your expectations ;)

we accept pull requests for such stuff, but I can assure you it is a lot of work generating and checking keyboard layout mappings :/ (there is no 'direct'  translation that works with all servers)

**Comment by m1027** [comment]
Unfortunatelly it's worse:

- run freerdp to a windows box
- press win-r (works) to run powershell
- type something: small letters as expected
- press ctrl-c (the physical ctrl which is mapped to caps locally): ctrl-c executed in powershell, however locally, caps lock gets enabled, little led on my caps key is lit
- press caps lock (the physical caps lock which is mapped to ctrl locally): in powershell I get captital letters from then on
- pressing caps lock again: captial letters in powershell STILL appear (caps lock not switched off never again)
- logging out from rdp session
- borked keyboard locally (need to press caps/ctrl several times to restore everything)

So, there is no simple workaround here, e.g. to train myself to use the physical ctrl/caps in a RDP session...

**Comment by cgull** [comment]
Yes, the disconnect between FreeRDP keyboard actions and X11 shift states causes a lot of pain.  FreeRDP really should be smarter about handling its interaction with X11 input.  I ended up hacking in a hardcoded fix:
https://github.com/cgull/FreeRDP/tree/swap-caps-ctrl-hack

**Comment by m1027** [comment]
> I ended up hacking in a hardcoded fix:
> https://github.com/cgull/FreeRDP/tree/swap-caps-ctrl-hack

Man, this hack is awesome!! Added as a permanent user patch on my Gentoo box.

@akallabeth: Reading such keycode swappings from a config file would do the trick for everybody.

**Comment by akallabeth** [comment]
@m1027 pull requests welcome ;)

**Comment by RIscRIpt** [comment]
Couldn't this problem be solved by `/kbd-remap` feature added in d7bf6553c558db64e5e3108b08f8ee1d394d1393 ?

**Comment by cgull** [comment]
It is!  For me on a US keyboard:  `/kbd-remap:29=58,58=29`

My hack is now obsolete.

**Comment by m1027** [comment]
Confirmed here, too! Great news. Thanks a lot.
