### ISSUE TITLE
freerdp-shadow-cli.exe error when receive incoming connection

### ISSUE THREAD

**Issue by TeguhPratala** [FreeRDP/FreeRDP#5651]
commit ade6b1007bd1de9c936a73780c1fb52f7a81e808
Refrence #5642

1. I Start freerdp-shadow-cli.exe -port:3390 -sec:rdp ( OS : Windows 10 ), it is run and listening for incoming connection
2. In Other Comp (OS : Windows 8 ), I Run mtsct and try to connect to no 1 P2P using lan cable
3. And I got an error [Error Log](https://drive.google.com/open?id=1uxsg8itu7LL28SGykSUNiTQdSiEx9A90)

**Error**
<img width="460
" alt="error" src="https://user-images.githubusercontent.com/52810065/66388425-4cb71300-e9f0-11e9-8cba-b5be37abc056.png">
<img width="460" alt="exception" src="https://user-images.githubusercontent.com/52810065/66388448-56d91180-e9f0-11e9-98b9-2e367f8febf0.png">

**Stacktrace**
<img width="469" alt="stacktrace" src="https://user-images.githubusercontent.com/52810065/66388469-6b1d0e80-e9f0-11e9-928f-5b3686503e63.png">

**How i build**
cmake .. -G "Visual Studio 16" -DWITH_SERVER:BOOL=on -DBUILTIN_CHANNELS:BOOL=on -A"x64"
[CMake Build Log](https://drive.google.com/open?id=155aQA290SPN2v6AAMqu06plkU7CKXzJk) , [Visual Studio Build Log](https://drive.google.com/open?id=1Q5gXEu4Jn21GBC44hRdasubtb3G0x36Q)

**Question**
1. Is Openh264, Cairo dependency is require or optional?
2. Am i missing dependency ?
3. Can i get some advice for fix this error ?

**Comment by akallabeth** [comment]
1. If `WITH_GFX_H264` is set a H264 backend must be available. (OpenH264, ffmpeg, ...) so check with `cmake` if that option is set
1. `Cairo` or `swscale` are optional (but you lose some high dpi capabilities)

**Comment by akallabeth** [comment]
Please use the mailing list or IRC for such support questions.

**Comment by dashingvik** [comment]
@TeguhPratala are you able to run this as shadow server ?

**Comment by TeguhPratala** [comment]
Yes i can, but when i use android client but still bugy. Like sudenly lose
connection.
When i use windows client, always error when recieve client incomming
connection

**Comment by dashingvik** [comment]
@TeguhPratala Can you help me with cmake parameters (which are needed) and how to build that  because I am still facing the same issue. My requirement is for windows as of now. If you could help that would be great for me.

**Comment by TeguhPratala** [comment]
cmake .. -G "Visual Studio 16" -DWITH_SERVER:BOOL=on
-DBUILTIN_CHANNELS:BOOL=on -A"x64" -DBUILD_SHARED_LIBS=ON
 -DMONOLITHIC_BUILD:BOOL=on -DWITH_SAMPLE=ON -DCMAKE_TOOLCHAIN_FILE=F:\
Programing_Data\Lib\vcpkg\scripts\buildsystems\vcpkg.cmake

DCmaketoolchain is cairo dependency, u can ignore it

**Comment by dashingvik** [comment]
@TeguhPratala And to build it which is generated by the cmake command
`cmake --build </path/to/folder>` right ? or anything else is also required ?

**Comment by TeguhPratala** [comment]
I run cmake on cmd, when build .exe i use visual studio 2019. U can choose
what u want to build.

**Comment by dashingvik** [comment]
@TeguhPratala Tried with both cmake as well as build.exe (VS command prompt) but still facing same issue. How can I check with h264 codec is installed in my PC ? 
I have downloaded and installed the DemoForge Mirage Driver for it. Any advice ?

**Comment by TeguhPratala** [comment]
I didnt use h264 lib, cz it optional. I only use openssl and ciaro. And i
used android client. Free RDP android client u can get from playstore
