### ISSUE TITLE
USB Redirectin Dedicated Update

### ISSUE THREAD

**Issue by AzureusNation** [FreeRDP/FreeRDP#5658]
This isn't a bug report as such but would it be possible for a focus on USB device redirection within FreeRDP?

I understand that the whole USB Redirection needs to be rewritten. Could i be rude enough to ask if more focus could be put on to this as from looking through and from myself there are a lot of things that we use that require usb redirection.

Many thanks

**Comment by akallabeth** [comment]
Fixed with #5745

**Comment by AzureusNation** [comment]
You my friend deserve a pay rise... @akallabeth thank you soo much for this. My thin client project at work will benifit greatly from this and so will all the staff and students across the trust.
