### ISSUE TITLE
iOS Client Issue - ERRCONNECT_DNS_NAME_NOT_FOUND

### ISSUE THREAD

**Issue by cogandroid** [FreeRDP/FreeRDP#5661]
When we connect to our gateway it shows below mentioned error
"[ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]"
Please let me know how we can fix this issue and I also want to know this issue is related to iOS Developer side issue or at server backend side issue.

Thanks

**Comment by akallabeth** [comment]
Which version are you using?
(Assuming self compiled as there was no update to store for ages?)

But from the error I assume some mismatch between the name you connect to and its dns name (or is it simply not resolvable?)

**Comment by akallabeth** [comment]
no feedback, most likely outside configuration issue, closing.
