### ISSUE TITLE
FreeRDP fails to build on Windows 10 64-bit with errors referring winpr

### ISSUE THREAD

**Issue by carsondwilber** [FreeRDP/FreeRDP#5662]
Pulling my hair out here. I have been struggling with this for hours.

**Describe the bug**
FreeRDP fails to build with various errors about winpr includes and undefined types.

**To Reproduce**
1. Install requirements (OpenSSL 1.1.1d, NASM, ActiveState Perl 5.28.1, OpenH264)
2. Clone FreeRDP/master
3. Configure build with
`cmake -GNinja -B -DCMAKE_C_COMPILER=path/to/gcc.exe -DCMAKE_CXX_COMPILER=path/to/g++.exe -DCMAKE_INSTALL_PREFIX=build -DOPENSSL_ROOT_DIR=path/to/openssl -DCMAKE_BUILD_TYPE=Release .`
4. `cmake --build . --target install`

**Expected behavior**
FreeRDP should build successfully.

**Screenshots**
Build configure:
[Configure-1](https://i.imgur.com/Zy5YJtI.png)
[Configure-2](https://i.imgur.com/q1XyY48.png)

Attempt to build:
[Build-1](https://i.imgur.com/dtPNx5Z.png)
(this goes on and on for a while)

**Application details**
* FreeRDP/master
* Command line: x64 Native Tools Command Prompt for VS2017

**Desktop:**
 - OS: Windows 10 64-bit

**Additional context**
All other lights are green, just cannot for the life of me get FreeRDP to build.

**Comment by akallabeth** [comment]
We never tried gcc on windows, use the ms compilers.
