### ISSUE TITLE
[RAILS] positioning and resize positions are off

### ISSUE THREAD

**Issue by matty-r** [FreeRDP/FreeRDP#5663]
**Description**
When connecting to either a Windows 7 or Windows 10 VM, RemoteApp performance is slow and can create a number of graphical artifacts/issues within the application window after resizing.  Also when making application fullscreen it will not want to leave fullscreen at all despite restoring and resizing by grabbing the edge of the application window. I've tried a number of different connection settings, however performance had not significantly improved. 

On the other hand, not using RemoteApp works perfectly and I encounter zero issues when using that on it's on.

**To Reproduce**
1. Connect to the Windows VM  /app:'outlook'
2. Resize a window
3. Move a window
4. Snap a window to either side of the desktop, or make full screen

**Expected behavior**
Application windows should move about freely, without graphical issues, and with reasonable performance.

**Screenshots**
Blurred personal data
![image](https://user-images.githubusercontent.com/9965448/67264188-b43f8900-f4ed-11e9-863f-81e8da8b5b5a.png)

![image](https://user-images.githubusercontent.com/9965448/67264032-3f6c4f00-f4ed-11e9-9101-9653b4897a0d.png)

![image](https://user-images.githubusercontent.com/9965448/67264166-a68a0380-f4ed-11e9-80cd-5bbd84a39f3b.png)

** Application details
* Version of FreeRDP
freerdp-git 2.0.0.rc4.r659.g4a6b843f1-2
* Command line used
xfreerdp /u:user /p:pass /app:'outlook' /cert-ignore /v:192.168.122.45 /bpp:16 /network:modem /compression -themes -wallpaper /clipboard /audio-mode:1 /auto-reconnect -glyph-cache -offscreen-cache /rfx -menu-anims -bitmap-cache

* OS version connecting to
Windows 7 / Windows 10

**Desktop **
 - OS: Arch Linux
 - Browser N/A
 - Version N/A

**Comment by matty-r** [comment]
Likely related to #5479 and #5343

**Comment by akallabeth** [comment]
@matty-r thx for the references.
Does it work with a more recent build from master?

**Comment by matty-r** [comment]
> @matty-r thx for the references.
> Does it work with a more recent build from master?

I tried earlier to get a nightly installed, but wasn't able to get it work sorry. I'll try from Master in a few hours and report back.

Thanks

**Comment by akallabeth** [comment]
@matty-r also, it is always recommended to add `/gfx` (or `/gfx:avc444` if compiled with h264 support) to utilize modern graphics pipeline (usually less glitches and bandwidth usage ;))

**Comment by akallabeth** [comment]
also, you´re using kde/plasma with a single monitor setup? (rails is quite picky regarding window managers and their positioning behaviour)

**Comment by matty-r** [comment]
> @matty-r also, it is always recommended to add `/gfx` (or `/gfx:avc444` if compiled with h264 support) to utilize modern graphics pipeline (usually less glitches and bandwidth usage ;))

Ok, will do. Still got to get around to doing that tonight.

> also, you´re using kde/plasma with a single monitor setup? (rails is quite picky regarding window managers and their positioning behaviour)

Kinda.. it's a laptop with an external monitor - however the laptop monitor is disabled. With that said, I'm experiencing the same issues on my desktop which is a single monitor setup.

**Comment by matty-r** [comment]
> also, you´re using kde/plasma with a single monitor setup? (rails is quite picky regarding window managers and their positioning behaviour)

@akallabeth I was able to build from Master (as below), wasn't 100% sure on the build flags to use. Performance wasn't noticeably better, and maximizing to full screen would result in sporadic behaviour: I noticed that when going to fullscreen and then restoring back down, as soon as it lost focus to another window it would go to fullscreen again.

```
This is FreeRDP version 2.0.0-dev5 (40463bb2f)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 9.2.0
```

**Comment by matty-r** [comment]
@akallabeth I built from the nightly "amd64,buster,pkg-deb #718" on Ubuntu Mate and I had the same, if not worse experience than before.

``This is FreeRDP version 2.0.0-dev5 (5cc5aa98e)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=ON WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp-nightly-2.0.0+0~20191019014825.713~1.gbp5cc5aa=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fsanitize=address -fsanitize-address-use-after-scope -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 8.3.0
Target architecture: x64``

**Comment by akallabeth** [comment]
@matty-r what do you mean with 'I built from the nightly "amd64,buster,pkg-deb #718" '?

Debian built package on ubuntu? Sorry, I just don't understand what you mean :/

As for 'worse' could you describe that? Easier to fix if we know what to look for ;)

Most rail issues are caused by local interaction with the window manager creating unwanted feedback loops, so some details on that might also help.

**Comment by matty-r** [comment]
> @matty-r what do you mean with 'I built from the nightly "amd64,buster,pkg-deb #718" '?
> 
> Debian built package on ubuntu? Sorry, I just don't understand what you mean :/
> 
> As for 'worse' could you describe that? Easier to fix if we know what to look for ;)
> 
> Most rail issues are caused by local interaction with the window manager creating unwanted feedback loops, so some details on that might also help.

That's just the package that came up.. ha ha. What debug commands can I run that would be useful for you?

**Comment by akallabeth** [comment]
@matty-r ok, then better use https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds and the correct distro name
As for commands, just run your session (with `/log-level:debug`, `2>&1 |tee log.txt` the output and record the session with a screen recorder so that the stuff that is wrong can be seen and we have a corresponding log.

**Comment by matty-r** [comment]
> @matty-r ok, then better use https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds and the correct distro name
> As for commands, just run your session (with `/log-level:debug`, `2>&1 |tee log.txt` the output and record the session with a screen recorder so that the stuff that is wrong can be seen and we have a corresponding log.

Sweet, I'll get that for you tonight then.

**Comment by matty-r** [comment]
@akallabeth 
Log file and screen capture below:
[log.txt](https://github.com/FreeRDP/FreeRDP/files/3762023/log.txt)

[Screen Capture](https://youtu.be/hA8IJynPSZ8)

**Comment by akallabeth** [comment]
@matty-r might I ask for your command line? Looks like you still do not use `/rfx /gfx` and with the old win xp age protocol that remains slowness is expected ;)

**Comment by matty-r** [comment]
> @matty-r might I ask for your command line? Looks like you still do not use `/rfx /gfx` and with the old win xp age protocol that remains slowness is expected ;)

Sorry, I forgot to include that. I saw this same behavior even with Windows 10. 

`
xfreerdp /u:matt /p:password /app:'outlook' /cert-ignore /v:192.168.122.198 /gfx:avc444 /log-level:debug 2>&1 |tee log.txt`

I also compiled with (Maybe there is something else I should add):

`cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON .`

**Comment by akallabeth** [comment]
@matty-r ok, so we are talking about a coordinate mapping issue here (windows do not match contents offsets correctly, mouse clicks are strangely off, ...) right?

**Comment by matty-r** [comment]
@akallabeth Sounds about right - it all turns into a mess after going fullscreen. My resolution on that display is 3440 x 1440.

**Comment by rootSectornet** [comment]
i also have the same problem as this, with the debian os remote apps autocad on windows 8
