### ISSUE TITLE
[ANNOUNCEMENT] Upcoming code base reformatting

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#5667]
It has been a while now since #4350 was merged.
Since 2.0 should be released (finally) we will be enforcing these rules in an upcoming pull request before release.

Changes to be aware of:
* We will switch to a `.clang-format` file (slightly different from previouse style, but enforcable by `clang-format`)
* After the upcoming PR is merged, we will add a format checker to the pull request tester failing every pr that does not conform! So check your changes with `clang-format` before submission!

You can already start using it with e.g. https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format
then a `git clang-format origin/master` from your feature branch will format all your changes with the new style.

**Comment by kubistika** [comment]
#5598
Waited for that :)

**Comment by akallabeth** [comment]
Done with #5703
