### ISSUE TITLE
Unable to build without libcairo

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#5669]
I want to compile FreeRDP without libcairo support. So I specify `-DWITH_CAIRO=OFF` in my cmake args. Unfortunately that doesn't seem to be enough as cmake still looks for it and unfortunately finds it `-- Found Cairo: /usr/local/lib/libcairo.dylib`.

Any way to get `-DWITH_CAIRO=OFF` to actually work and force it to be disabled?

thx,
felix

**Comment by akallabeth** [comment]
@lemonmojo thx for the info. Fixed the dependency (it was detected as part of some other dependency and we only checked if it was available, not if it was requested)

**Comment by lemonmojo** [comment]
@akallabeth Just saw the PR coming in. Thx for the quick fix!
