### ISSUE TITLE
Certificate checks & port forwards

### ISSUE THREAD

**Issue by kvdveer** [FreeRDP/FreeRDP#567]
We have a linux gateway which forwards a large number of rdp ports from various windows servers in a protected network. Unfortunately, xfreerdp reports a possible man-in-the-middle attack all but one of those ports, presumably because certificates are cached based on hostname instead of hostname + port.

**Comment by scott-idem** [comment]
This issue was referenced on a commit but I am not sure that it was fixed?

We also use port forwarding to handle multiple workstations behind one host name. We would like to ask that you please add the port to the known_hosts. We would prefer not to ignore the certificate.

**Comment by akallabeth** [comment]
This has been implemented in current master (freerdp 2.0)
