### ISSUE TITLE
Error in this command: ./OpenSSL-DownloadAndBuild.command

### ISSUE THREAD

**Issue by cogandroid** [FreeRDP/FreeRDP#5671]
Hi,

Please Help
I am running this command **"./OpenSSL-DownloadAndBuild.command"** 
on Mac terminal to setup FreeRDP iOS project on Mac
1. My internet connection is working
2. I am using **Xcode 10.3**  on **MacOS 10.14.6**
3. I am using latest **CMake version 3.16.0**
4. I am running all commands on **Terminal**
5. I downloaded the **Latest FreeRDP SDK from GITHUB**
But even after **waits for many hours with multiple attempts** its showing **please wait**  after couple of lines mentioned below:

**MAC-006:~ macuser$ cd /Users/rrajput/Desktop/FreeRDP-master 
MAC-006:FreeRDP-master macuser $ cd scripts
MAC-006:scripts macuser$ ./OpenSSL-DownloadAndBuild.command
./OpenSSL-DownloadAndBuild.command: line 105: cd: external: No such file or directory
shasum: openssl-1.0.2q.tar.gz: 
Downloading OpenSSL Version 1.0.2q ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5220k  100 5220k    0     0  5283k      0 --:--:-- --:--:-- --:--:-- 5278k
Unpacking OpenSSL ...

Building openssl-1.0.2q for iPhoneSimulator 12.4 i386 (min SDK set: 10.0)
 Please wait ...MAC-006:scripts macuser$**

When I press enter in goes to next line with this
**MAC-006:scripts macuser$**
then I enter CMake build project command **cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode -DPKG_CONFIG_EXECUTABLE=/usr/local/bin/pkg-config** it shows config error please reply asap.

Regards
Rahul

**Comment by akallabeth** [comment]
Please use the mailing list or irc for support.
This is an isdue tracker.
