### ISSUE TITLE
/multitransport not working with audio

### ISSUE THREAD

**Issue by benedikt-bartscher** [FreeRDP/FreeRDP#5677]
When using /multitransport audio isn't working any more!

Version of FreeRDP: 2.0.0-dev5 (2693389a+debian)
Command line used: xfreerdp /u:user /p:**** /v:192.168.2.***/sec:tls /multimon /sound:sys:alsa,format:1,quality:high /multitransport
OS version connecting to: Win10 1809

**Comment by akallabeth** [comment]
can not reproduce. sure it is not something else that is blocking audio?

**Comment by benedikt-bartscher** [comment]
No, i can switch audio on/off with /multitransport

**Comment by akallabeth** [comment]
@benedikt-bartscher well, let me restate my last question:
I can use audio (with your command line, from a debian buster installation) with and without multitransport
* against win10 (multiple versions)
* against win 8.1
* against win 8
* against win7
* against win server 2008-2019

so, could you check your server config, it might be necessary to find the config setting responsible to identify what is going on here.

**Comment by akallabeth** [comment]
Not reproducible, no feedback.
closing.

**Comment by hardening** [comment]
FYI I'm currently having a look at multitransport
