### ISSUE TITLE
Clipboard Client to Server stops working after CB_FORMAT_LIST_RESPONSE (3), msgFlags: 2

### ISSUE THREAD

**Issue by NiKiZe** [FreeRDP/FreeRDP#568]
I mentioned in Issue #387 that there seems to be a issue sometimes when copying from client to Server.

My test case is copying text from firefox on the client side, and pasting in "new message" in outlook 2010 or sometimes just moving the cursor over outlook and then the clipboard on the server stops receiving clipboard data from the client. And you paste the old no longer wanted data.

Here is related debug info... (last line most interesting)
DBG_X11_CLIPRDR xf_cliprdr_get_requested_targets (476): type=4 format=32 length=12 bytes_left=0
DBG_CLIPRDR cliprdr_process_receive (205): msgType: CB_FORMAT_LIST_RESPONSE (3), msgFlags: 1 dataLen: 0
DBG_CLIPRDR cliprdr_process_receive (205): msgType: CB_FORMAT_DATA_REQUEST (4), msgFlags: 0 dataLen: 4
DBG_X11_CLIPRDR xf_cliprdr_process_cb_data_request_event (427): format 53264
DBG_X11_CLIPRDR xf_cliprdr_process_cb_data_request_event (450): target=594
DBG_X11_CLIPRDR xf_cliprdr_get_requested_data (717): type=594 format=8 bytes=8 request_index=7
DBG_CLIPRDR cliprdr_process_receive (205): msgType: CB_FORMAT_DATA_REQUEST (4), msgFlags: 0 dataLen: 4
DBG_X11_CLIPRDR xf_cliprdr_process_cb_data_request_event (427): format 13
DBG_X11_CLIPRDR xf_cliprdr_process_cb_data_request_event (450): target=359
DBG_X11_CLIPRDR xf_cliprdr_get_requested_targets (476): type=359 format=8 length=0 bytes_left=3
DBG_X11_CLIPRDR xf_cliprdr_get_requested_data (717): type=359 format=8 bytes=3 request_index=1
DBG_X11_CLIPRDR xf_cliprdr_get_requested_targets (476): type=4 format=32 length=12 bytes_left=0
DBG_CLIPRDR cliprdr_process_receive (205): msgType: CB_FORMAT_LIST_RESPONSE (3), msgFlags: 2 dataLen: 0

http://msdn.microsoft.com/en-us/library/cc241120%28v=prot.10%29.aspx
When activating the disabled code parts this works a few times more, but not always, and a lot of chatter between client and server appears in those cases.

To be able to copy text from client to server again I copy anything on the server, and then redo the copy operation from the client.
But this is starting to become a bit tedious at times. (worst is when you paste a few values and after several pastes notices that there is a few incorrect ones)

**Comment by bmiklautz** [comment]
Closing du to inactivity. Please re-open or create a new issue if this problem still exists on the current mater branch.
