### ISSUE TITLE
RDP can't play sound on device

### ISSUE THREAD

**Issue by MyNameDDQ** [FreeRDP/FreeRDP#5682]
Hello 
When I use the iOS project,I have a tricky problem..
In the RDPSession.m,-initWithBookmark: method I add this code: 

 if (!addArgument(&argc, &argv, "/audio-mode:%d", AUDIO_MODE_REDIRECT))
        goto out_free;
    
 if (!addArgument(&argc, &argv, "/sound"))
        goto out_free;

In -connect method I add this code:
settings->DeviceRedirection = TRUE;

Codec use the default fake channel,

The remote volume of the desktop also shows the maximum volume.
But after setting it up,still can't play the sound.

What should I do?
Best Regard

**Comment by akallabeth** [comment]
Well, the `fake` output is what the name tells you. Try it with the `ios` backend.
For further support questions please use the mailing list or IRC.

**Comment by MyNameDDQ** [comment]
Hello


Thank you for your reply, I have solved this problem with the ios client.
But now there is also a new problem that will be very good when playing. I set it up:
Settings-&gt;CompressionEnabled = TRUE;
Settings-&gt;SupportVideoOptimized = TRUE;
But the effect is still not obvious. What else can I do?



Best Regards




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"akallabeth"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 下午4:03
收件人:&nbsp;"FreeRDP/FreeRDP"<FreeRDP@noreply.github.com&gt;;
抄送:&nbsp;"我叫咚咚枪"<869795924@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FreeRDP/FreeRDP] RDP can't play sound on device (#5682)




Well, the fake output is what the name tells you. Try it with the ios backend.
 For further support questions please use the mailing list or IRC.
