### ISSUE TITLE
the "new" CLI options are horrible

### ISSUE THREAD

**Issue by dtkerns** [FreeRDP/FreeRDP#5691]
This is an "issue", not a bug. (well, the bug is not in the code, but rather in the developer's head that would even consider making this kind of change)

For those of you NOT familiar with stability and reliability; Redhat has what they call Enterprise Linux. It purposely lags the bleeding edge so that their customers can have a reliable and stable OS from which to run their applications and commerce (you know, make LOTs of money).

Recently, they (redhat) rolled out an update to xfreerdp (mid stream RHEL7) forcing upon us (via a myriad of "WARNING using deprecated interface" messages) some hair boned idea of how command line options should be passed to an application... throwing 35 plus years of Unix/Linux commonality to the wind.

Imagine my astonishment when I discovered these changes went in 5 years ago. Obviously, no one's going to change it back now, but I'm very disappointed in "The Community" that this kind of change would make it in unchallenged.

Please don't flame me. I'm not looking to flame any one here. I did want to document the non-conformity for anyone else that gets broadsided by a bunch of WARNING messages. (I searched the issues and found nothing)

thanks for your (continued) work.

**Comment by informatimago** [comment]
Yes, unfortunately, FreeRDP is a MS-Windows program that has been ported to Linux.  Happily, it runs on Linux.  But indeed, it would be nicer to be able to use unix-like options on unix systems.

**Comment by dtkerns** [comment]
hmmm... is/was freerdp different then xfreerdp? ... the v1.X version I was running for the last few years used -s (short) and --long options, now with the v2 everything has to be /option ... "feels wrong" from a bash prompt.

**Comment by hardening** [comment]
@informatimago ah ah ah fun, FreeRDP is more a linux program that has been ported to windows (BTW the windows port needs love as you can see in the issues). But to ease porting to different platform, Marc-André Moreau chose years ago to take the windows API as a base API, and so he created winPR that emulates win32 calls for linux or MacOs. It's some kind of windows compatibility layer but at the source level (for some time it was even shipped as an independent library). Some of the developers (including me) think that it was not a wise choice, but years later with tons of code written on top of this it's really hard to come back on that choice.

**Comment by akallabeth** [comment]
@hardening did quite a nice sum-up, so I´m afraid this is a `wont-fix` :/
