### ISSUE TITLE
link error: undefined reference to `rdpgfx_client_context_new in proxy code

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#5693]
When building the current master for openSUSE (Tumbleweed and Leap 15.*) I get linker errors:
[   75s] [100%] Linking C shared library libfreerdp-shadow-subsystem2.so
[   75s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/freerdp-proxy.PN3vbj.ltrans0.ltrans.o: in function `pf_OnChannelConnectedEventHandler':
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/server/proxy/pf_rdpgfx.c:459: undefined reference to `rdpgfx_client_context_new'
[   75s] /usr/lib64/gcc/x86_64-suse-linux/9/../../../../x86_64-suse-linux/bin/ld: /tmp/freerdp-proxy.PN3vbj.ltrans0.ltrans.o: in function `pf_OnChannelDisconnectedEventHandler':
[   75s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/server/proxy/pf_channels.c:149: undefined reference to `rdpgfx_client_context_free'
[   75s] collect2: error: ld returned 1 exit status
[   75s] make[2]: *** [server/proxy/CMakeFiles/freerdp-proxy.dir/build.make:313: server/proxy/freerdp-proxy] Error 1
[   75s] make[1]: *** [CMakeFiles/Makefile2:4921: server/proxy/CMakeFiles/freerdp-proxy.dir/all] Error 2

For details see the attached build log.
[osTWbuild_linkerror.log.gz](https://github.com/FreeRDP/FreeRDP/files/3795411/osTWbuild_linkerror.log.gz)

**Comment by kubistika** [comment]
cmake --build . --clean-first

**Comment by hendwolt** [comment]
That doesn't help.
I'm using the OBS (Open Build Service of openSUSE) and the first thing, this tool does, is removing the old directories.
I'm not a cmake expert, but I think, as the proxy code uses (now ?) client functions, it needs to be linked with the client libs. And that might be missing.

**Comment by hendwolt** [comment]
After some more experimenting I found the culprit:
"-DBUILTIN_CHANNELS=OFF"
After setting this switch to ON linking worked again.
