### ISSUE TITLE
Incorrect keyboard mapping

### ISSUE THREAD

**Issue by symcbean** [FreeRDP/FreeRDP#5695]
I am using 

Ubuntu 18.0.4.3
freerdp-x11 1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.3
MS-Windows 10
A UK keyboard layout

I am running xfreerdp with /kbd:0x00000809 (UK keyboard).

Using programs on the Linux host, the keyboard behaves as expected, however within a xfreerdp session, applications on the MS-Windows host behave **_as if_** a US layout keyboard had been configured.

The MS Windows host shows the keyboard type as "ENG" and requesting a on-screen keyboard returns the same layout as my physical keyboard. However when I press (for example) shift + 2, I expect a double quote (") to appear in Microsoft notepad.exe, instead I get an AT symbol (@). There are many other keys which are different between the UK layout and the way this behaves. see also https://en.wikipedia.org/wiki/British_and_American_keyboards 
Note I have not confirmed that this is definitely behaving as a US keyboard - but the mappings I tried seem to match up. 

Using the example of shift+2, xev reports the following:

KeyRelease event, serial 48, synthetic NO, window 0x1200001,
      root -x268, subw 0x1200002, time 1838558268, (36,31), root:(233,411),
      state 0x11, keycode 48 (keysym 0x22, quotedbl), same_screen YES,
      XLookupString gives 1 bytes: (22) """
      XFilterEvent returns: False

This may be the same issue as reported in #3383, #2170 ?

**Comment by akallabeth** [comment]
@symcbean does this apply to our nightlies too? https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by akallabeth** [comment]
@symcbean the referenced issues are similar but for different a os.
The keyboard symbol mapping is 2 staged:
1. Get the scancode for the key pressed
1. The server converts the scancode back to the symbol desired.

So, your local keyboard layout is ignored (only the 'which key is pressed' part is used) and you can change the server side layout and still get the correct key.
If that does not work for you, there are the following possibilities:
1. Your server side layout is not available
1. Your local layout reverse mapping does report the wrong scancode for a key

Due to security concerns there are no log messages written for that (you could get sensitive information from that)
But if you want to check which scancode is used, you could print it in `freerdp_input_send_keyboard_event` so you know if the key pressed matches the scancode expected

**Comment by byteboon** [comment]
I believe the issue he is seeing (keyboard layout setting to default for the keyboard language) is because the CodePage is hardcoded to zero in rdp_write_info_packet

See https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/461923d0-24b6-4208-b7bf-d8ec39d2a051

**Comment by akallabeth** [comment]
@byteboon from the referenced documentation I read that the code page is used to determine the layout if `KeyboardLayout = 0` only.

**Comment by byteboon** [comment]
Hi @akallabeth... unfortunately you're not reading it correctly. We have this working in production.

We added a setting to hold and pass the codepage in rdp_write_info_packet:
`Stream_Write_UINT32(s, settings->KeyboardCodepage & 0x0000FFFF); /* CodePage (4 bytes) */`

And then we detect the local keyboard info and pass it along:
```
	// pass along an initial keyboard
	WCHAR KLID[KL_NAMELENGTH];
	if (GetKeyboardLayoutName(KLID)) {
		settings->KeyboardLayout = HexStringToInt(KLID);
		settings->KeyboardCodepage = LOWORD(GetKeyboardLayout(0));
	}
	else {
		settings->KeyboardLayout = LOWORD(GetKeyboardLayout(0));
		settings->KeyboardCodepage = 0;
	}
```

We only use FreRDP as a library, so I don't have a full patch to provide... just the additional setting and that one line change in rdp_write_info_packet.

An example would be setting your local system to English + US-International ... without my patch the remote will be set to English + US English, and with my patch it will be set to English + US-International to match.  Note that it appears the keyboard is only set upon initial login, and not when reconnecting to an existing login session.

**Comment by byteboon** [comment]
Now looking at the original report, my comments may not actually be related... but hopefully they contribute something anyway.  ¯\_(ツ)_/¯

**Comment by akallabeth** [comment]
@symcbean does #5707 help with your issue?
