### ISSUE TITLE
development package for xfreerdp

### ISSUE THREAD

**Issue by sam0x17** [FreeRDP/FreeRDP#5701]
**Is your feature request related to a problem? Please describe.**
Trying to add rail channel support to Remmina. There doesn't seem to be any packages I can find that include the development headers for `xfreerdp` e.g. `xfreerdp.h` etc. 

**Describe the solution you'd like**
A `libxfreerdp-dev` package in the debian repositories and wherever else makes sense.

**Describe alternatives you've considered**
Manually importing the source files from the freerdp project.

**Additional context**
https://gitlab.com/Remmina/Remmina/issues/1998#note_239338125

**Comment by sam0x17** [comment]
for more context, I need to call `xf_init_rail` within Remmina.

**Comment by akallabeth** [comment]
@sam0x17 there is a reason that headers are not shipped.
You're doing X11 window mapping in a gtk applikation, better take the rails implementation and port it to gtk.
(Look at the rails spec at https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdperp/485e6f6d-2401-4a9c-9330-46454f0c5aba )

**Comment by akallabeth** [comment]
Some context: what you do is a little hack that tries to forcefully start xfreerdp rails that will corrupt the remmina data structures.
The client parts are specific to the client implementation and must not be used outside
