### ISSUE TITLE
FreeRDP connections via VPN in macOS 10.15 Catalina

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#5705]
This is more of an FYI than a bug report or feature request, although I have some suggestions for future improvements which I'll outline at the end of the comment.

## Introduction

Over the last couple of weeks (since the official release of macOS 10.15 Catalina) I've been getting dozens of issue reports from [Royal TSX](https://www.royalapps.com/ts/mac) users who suffer from spontaneous RDP disconnects. Lots of troubleshooting, setting up a test environment and a couple of changes in FreeRDP's core libraries later, I finally found the reason for these disconnects and am able to reproduce them locally.

## Problem Description

Users reported to me that they're connected to a remote RDP host and as long as they're interacting with the session everything's fine. As soon as they stop using the connection though, sending it into an idle state, the connections would drop after a couple seconds up to a few minutes. The error message in all of these cases was always: `BIO_read returned a system error 60: Operation timed out`.

After a lot of back and forth, I was able to find the common denominator for all of these users: They are all connected to the remote host through a VPN, using the VPN client built into macOS.

Since I didn't have a working VPN server here to test with, I first started adjusting the [keep alive settings](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/tcp.c#L994) in FreeRDP (`TCP_KEEPIDLE`, `TCP_KEEPCNT`, etc.) and sent the affected users customized FreeRDP builds.

Quickly it became clear that increasing the values also increased the time users managed to stay connected. Eventually the connections still dropped though so it became pretty clear that the issue was definitely related to TCP keep alive packets. Also, it more and more looked like not a single one of the sent keep alive packets would arrive at their destination.

## Reproducing the problem

I then set out to find a way to reproduce the problem myself to do further troubleshooting. So I installed an [L2TP VPN server](https://github.com/hwdsl2/setup-ipsec-vpn) on an Ubuntu host, created the VPN connection on my Mac and connected to a Windows Server 2008 R2 machine behind the VPN.

I was instantly able to reproduce the problem. Basically, I just connected, let the session sit idle for a couple of seconds and suddenly it would just drop with the same error message previously reported by the affected users.

Next, I fired up Wireshark and started monitoring the connection. Sure enough, it immediately became clear that all keep alive packets were dropped although the actual connection was perfectly alive and happy to send screen updates and receive input when not idle.

I then increased `TCP_KEEPCNT` to rule out partial packet loss. I stopped at 50. All of those 50 keep-alive packets were dropped. So from this point on it was clear that the problem was definitely macOS dropping all keep alive packets and thus breaking the connection while idle.

Here's what this looks like in Wireshark:

<img width="1629" alt="wireshark" src="https://user-images.githubusercontent.com/186198/68380908-04a32180-0151-11ea-8fd9-fd317c0fceb6.png">

Unfortunately I wasn't able to find out what exactly causes these packets to be dropped. The only thing I know is that it doesn't happen when not connected through a VPN.
It also doesn't seem to be related to a specific VPN server type since the affected users run different kinds of VPN servers. They are all using the built-in VPN client in macOS though. And they're all on 10.15 or 10.15.1.

## Further Steps

* I published a blog post which explains the problem to my users. It's available [here](https://www.royalapps.com/blog/rdp-connections-via-vpn-in-macos-10-15-catalina).
* I will also soon submit a bug report to Apple.
* And of course I wanted to let the FreeRDP community know about this by posting here in your issue tracker.

## Suggestions for the FreeRDP library

One of the most irritating things during debugging was that Microsoft Remote Desktop for Mac never dropped the connection. Of course, once I inspected the traffic using Wireshark it became clear why: They just never send keep-alive packets and thus don't suffer from the bug.

Obviously, for users this isn't very convincing: "It works with MSRDP, why doesn't it work with Royal TSX/FreeRDP?". For me, the technical differences are clear, for users it just either works or doesn't work.

So, what I would like to suggest is to at least make the values in [`freerdp_tcp_set_keep_alive_mode`](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/tcp.c#L994) configurable through `rdpSettings` or other means so that library integrators can decide themselves whether or not they want to use keep-alive and at which intervals/timeouts.

Although I think this should be enabled by default, I also think it should be configurable for either the client developer or even the user. Hardcoding makes it hard for debugging too.

Hope this makes sense and the information revealed is useful to other FreeRDP users.

**Comment by akallabeth** [comment]
@lemonmojo thx for the heads up.
Added the configuration options in #5706

**Comment by lemonmojo** [comment]
FYI: Just published a small repro case as [Gist](https://gist.github.com/lemonmojo/1b7f957aed60a65c121e8067d5d93483).
Also, submitted bug report to Apple. Copy of the [radar is here](https://openradar.appspot.com/7432718).

**Comment by usscarter** [comment]
This also seems to occur if the RDP server is behind a nat.

**Comment by akallabeth** [comment]
@usscarter which one? Maybe file a bug with them too ;)

**Comment by usscarter** [comment]
The failure symptoms and everything discussed in this post, occur if the RDP host is behind a nat.

Im not sure a duplicate report is nessecary for it as the reproduction and sharks will show the exact same. He talks about using it over L2TP tunnels, I was adding, that it appears to occur that if the host is behind a nat as well.

**Comment by akallabeth** [comment]
@usscarter ok, so you're not extending this beyond a bug in the tcp stack of macos? (your comment could be read as happens because of some NAT, maybe even with other os as client)

**Comment by usscarter** [comment]
Sorry for confusion. No I believe what he reported is the correct bug, and recreation. I was adding that in our environment we traced it down to what I believe is the same thing, when the host is behind a nat.

**Comment by akallabeth** [comment]
@usscarter ok, thank you for the clarification.

**Comment by lemonmojo** [comment]
@usscarter You should definitely file a bug report with Apple as doing so greatly increases the chances of this getting fixed.
