### ISSUE TITLE
[FYI] Build and runtime warnings

### ISSUE THREAD

**Issue by user-72632** [FreeRDP/FreeRDP#5708]
In the hopes of making the 2.0 release build clean, I wanted to bring some light on the fact that I am seeing -Wpragmas and -Wdiscarded-qualifiers warnings in the logs of the latest nightly builds for Ubuntu 16.04 LTS (xenial). I also am seeing runtime warnings for ffmpeg/x264 such as those shown below.

[14:42:27:950] [6555:6670] [WARN][com.freerdp.channels.cliprdr.common] - [cliprdr_packet_format_list_new] called with invalid type 00000000
[h264 @ 0x7f3a6dfc8f20] Overread SPS by 8 bits
[h264 @ 0x7f3a6dfc8f20] sps_id 32 out of range
[h264 @ 0x7f3a6dfc8f20] Overread SPS by 8 bits
[h264 @ 0x7f3a6dfc8f20] data partitioning is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[h264 @ 0x7f3a6dfc8f20] If you want to help, upload a sample of this file to ftp://upload.ffmpeg.org/incoming/ and contact the ffmpeg-devel mailing list. (ffmpeg-devel@ffmpeg.org)
[14:42:24:289] [6555:6626] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr

**Comment by akallabeth** [comment]
@user-72632 the build warnings we are working on, but the ffmpeg one we can't change as the server os creates the h264 stream and we only pass it on.

**Comment by user-72632** [comment]
I should have known you guys were on it already! Sorry for the noise.... Close at will.
