### ISSUE TITLE
connection error  (xfreerdp on solaris 11)

### ISSUE THREAD

**Issue by tschoenemann** [FreeRDP/FreeRDP#571]
I just checked out the latest version and compiled it on solaris11
with 
-DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_FFMPEG=OFF -DWITH_ALSA=OFF 

but when i try to connect to any of our RDP servers i always get:

xfreerdp   citrixserver 
connected to citrixserver:3389
recv: Resource temporarily unavailable
[1]    18382 exit 131   xfreerdp 

With "truss" i see this:
/2:	write(1, " c o n n e c t e d   t o".., 31)	= 31
/2:	getsockname(9, 0xFE68EB88, 0xFE68EB98, SOV_DEFAULT) = 0
/2:	setsockopt(9, tcp, TCP_NODELAY, 0xFE68EBFC, 4, SOV_DEFAULT) = 0
/2:	getsockopt(9, SOL_SOCKET, SO_RCVBUF, 0xFE68EBFC, 0xFE68EBF8, SOV_DEFAULT) = 0
/2:	setsockopt(9, SOL_SOCKET, SO_KEEPALIVE, 0xFE68EBA8, 4, SOV_DEFAULT) = 0
/2:	send(9, "03\0\0130EE0\0\0\0\0\001".., 19, 0)	= 19
/2:	recv(9, "03\0\0\v06D0\0\012 4\0", 16384, 0)	= 11
/2:	fcntl(9, F_GETFL)				= 2
/2:	fcntl(9, F_SETFL, FWRITE|FNONBLOCK)		= 0
/2:	brk(0x0813AF48)					= 0
/2:	brk(0x0813CF48)					= 0
/2:	brk(0x0813CF48)					= 0
/2:	brk(0x08140F48)					= 0
/2:	send(9, "03\001 x02F0807F e8201 l".., 376, 0)	= 376
/2:	pollsys(0xFE68EA90, 1, 0xFE68EB28, 0x00000000)	= 0
/2:	recv(9, 0x080BAFD8, 16384, 0)			Err#11 EAGAIN
recv/2:	write(2, " r e c v", 4)				= 4
: /2:	write(2, " :  ", 2)				= 2
Resource temporarily unavailable/2:	write(2, " R e s o u r c e   t e m".., 32)	= 32

So, xfreerdp seem to open the connection , send some data to the RDP server and then the 
recv() fails.

Can someone give me a hint?
Is xfreerdp supposed to work on solaris11?

thomas

**Comment by bmiklautz** [comment]
Please re-open or create a new issue if this problem still exists on the current mater branch.
