### ISSUE TITLE
Password using --from-stdin broken with whitespace in password

### ISSUE THREAD

**Issue by rriggs** [FreeRDP/FreeRDP#5725]
I have been using --from-stdin to pass my password to xfreerdp using secret-tool for a long time with no problems.  Yesterday I changed my password to a passphrase which included spaces.  xfreerdp no longer parses my password correctly.

**To Reproduce**
1. Set a password in secret-tool without spaces.
2. run bash -c "secret-tool lookup user xxx domain xxx | xfreerdp -g 1024x786 --plugin cliprdr --plugin rail  --sec nla -u user@DOMAIN --ignore-certificate --from-stdin -K -x lan HOSTNAME"
3. Note that the login works.
4. Change your password to one that includes spaces.
5. Update your password in secret-tool.
6. Re-run command at step 2.

**Expected behavior**
I expect that the RDP session is established.

**Screenshots**
Terminal output from xfreerdp:
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.

** Application details
* Version of FreeRDP: freerdp-1.0.2-10.el7.x86_64
* Command line used: see above
* output of `/buildconfig` -- NA
* OS version connecting to: Windows 10

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.4.1708 (Core) 

**Additional context**
I can work around the problem for now by using -p "$(secret-tool ...)" but would prefer that the --from-stdin functionality works with spaces.

**Comment by akallabeth** [comment]
2.0.0 was released, 1.0 no longer in support.
