### ISSUE TITLE
Allow connection through vsocks

### ISSUE THREAD

**Issue by hardening** [FreeRDP/FreeRDP#5726]
It would be interesting for FreeRDP to add the capability to connect over vsocks, xrdp supports such feature.
TLDR; vsock allows a direct communication between a host and its VMs, without even that the VM have network access.

We should add a way to specify a vsock connection, for example: `xfreerdp /v:vsock://4:3389` to connect on VM with cid `4` on port `3389`

**Comment by s-heinzel** [comment]
@hardening Please let me know, if the PR is missing anything :)

**Comment by rbeede** [comment]
I attempted this with the /vmconnect option using wfreerdp.exe. The window appears, but then xfreerdp just freezes and my keyboard stops responding to anything unless I kill the freerdp task.

**Comment by rbeede** [comment]
I tried the nightly builds from:
https://ci.freerdp.com/job/freerdp-nightly-windows/lastStableBuild/arch=win64,label=vs2017/

Both wfreerdp.exe and sdl-freerdp.exe  did avoid the hard freeze of the keyboard, but the connect window only showed a white box.

**Comment by akallabeth** [comment]
@rbeede could you attach a log file along with your command line? might be helpful to find out what is going wrong.
