### ISSUE TITLE
"winpr-makecert -rdp" does not produce $device.crt

### ISSUE THREAD

**Issue by juanitotc** [FreeRDP/FreeRDP#5735]
Using freerdp-2.0rc4 compiled natively on linux.

I expected the command "winpr-makecert -rdp" to produce two files:

$device.key
$device.crt

..but it only produces $device.key and does not give any error messages.

Similarly, "winpr-makecert -format crt" only produces a file named $device.key.

I understand that I need the following command to start a freerdp session using weston, but I cannot create $device.crt and $device.key.

weston --backend=rdp-backend.so --rdp-tls-cert=$device.crt --rdp-tls-key=$device.key
--width=1024 --height=768 --socket=wayland-1

**Comment by akallabeth** [comment]
@juanitotc syntax is `winpr-makecert -rdp -path <absolute path>` (note: path must exist and be writeable)

**Comment by juanitotc** [comment]
Ah - thanks, that works

**Comment by comicfans** [comment]
I hope the [wiki](https://github.com/awakecoding/FreeRDP-Manuals/blob/master/Configuration/FreeRDP-Configuration-Manual.markdown) page also update with this change 
```
To generate a default self-signed RDP certificate, use the -rdp option:

winpr-makecert -rdp
...
so the generated files are system76.crt and system76.key.
```

and winpr-makecert -help shows 
```
-rdp     Unsupported - Generate certificate with required options for RDP usage
```

what does Unsupported mean?

**Comment by akallabeth** [comment]
@comicfans that means that the command line option is `unused`

**Comment by comicfans** [comment]
@akallabeth OK... so even I don't pass '-rdp', just type
```
winpr-makecert -path $PWD
```
will generate needed key/crt files. maybe such confusing argument description can be improved ...
