### ISSUE TITLE
[Remote Assistance] command line option to immediately request control (like pressing Ctrl-Alt-C)

### ISSUE THREAD

**Issue by boom1** [FreeRDP/FreeRDP#5740]
I would like to have a command line parameter that immediately requests sharing of mouse and keyboard of the Remote Assistance session, instead of having to press Ctrl-Alt-C.

In essence I use Remote Assistance, because I cannot use RDP, but want to have one mouse and keyboard for two computers. 
I start the session (with a script) on the Windows machine, then go to Linux to request shared control (with Ctrl-Alt-C), need to go to Windows again to accept shared control, and finally go to Linux again (the main machine in my case).

With the new command line parameter this would be simplified to:
Start the session on the Windows machine and accept shared control, then go to Linux.

**Comment by akallabeth** [comment]
pull requests welcome, but we´re currently busy cleaning up.

**Comment by boom1** [comment]
If I find the time, I will try something.
What would be a good name for the parameter? I could not find anything similar in msra.exe.
Is "/requestcontrol" OK?

**Comment by boom1** [comment]
@akallabeth Do you have any recommendation or hint, e.g which function is called when the novice side has agreed to share the screen?

**Comment by akallabeth** [comment]
@boom1 `xf_toggle_control` is the function called to request input when `ctrl+alt+c` is pressed.

**Comment by boom1** [comment]
@akallabeth Thanks.
I added a call to xf_toggle_control() in xf_encomsp_participant_created(), when the message flags are MAY_VIEW, but not MAY_INTERACT.

Here is the patch (against master branch of today):
[request-control.patch.zip](https://github.com/FreeRDP/FreeRDP/files/3880389/request-control.patch.zip)

**Comment by boom1** [comment]
Works fine in master branch.
