### ISSUE TITLE
32bit warning: 'strnlen' specified bound 4294967295 exceeds maximum object size 2147483647 [-Wstringop-overflow=]

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#5741]
I'm not sure, how many people are still using the x86_32 (i586) platform, but the ones who do, see the following warnings in current master (8e195c469) builds:

/home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/registry/registry.c:300:14: warning: 'strnlen' specified bound 4294967295 exceeds maximum object size 2147483647 [-Wstringop-overflow=]
/home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/wlog/BinaryAppender.c:128:19: warning: 'strnlen' specified bound 4294967295 exceeds maximum object size 2147483647 [-Wstringop-overflow=]
/home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/wlog/BinaryAppender.c:129:23: warning: 'strnlen' specified bound 4294967295 exceeds maximum object size 2147483647 [-Wstringop-overflow=]
/home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/utils/wlog/BinaryAppender.c:130:21: warning: 'strnlen' specified bound 4294967295 exceeds maximum object size 2147483647 [-Wstringop-overflow=]

build config for openSUSE Tumbleweed i586:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=lib -DCMAKE_SKIP_INSTALL_RPATH=ON -DWITH_CUPS=ON -DWITH_CLIENT=ON -DWITH_PCSC=ON -DWITH_ALSA=ON -DWITH_PULSE=ON -DWITH_OSS=OFF -DWITH_DIRECTFB=OFF -DWITH_JPEG=ON -DWITH_GSM=ON -DWITH_GSTREAMER_1_0=ON -DWITH_IPP=OFF -DWITH_OPENSSL=ON -DWITH_CHANNELS=ON -DWITH_X11=ON -DWITH_XCURSOR=ON -DWITH_XEXT=ON -DWITH_XKBFILE=ON -DWITH_XI=ON -DWITH_XINERAMA=ON -DWITH_XRENDER=ON -DWITH_XV=ON -DWITH_ZLIB=ON -DWITH_KRB5=ON -DBUILTIN_CHANNELS=ON -DWITH_SERVER=ON -DWITH_SSE2=ON -DWITH_DEBUG_SCARD=OFF -DWITH_SMARTCARD_INSPECT=ON -DWITH_ICU=ON -DWITH_FFMPEG=ON -DWITH_DSP_FFMPEG=ON -DWITH_WAYLAND=ON -DWITH_SANITIZE_ADDRESS=OFF -DWITH_LIBSYSTEMD=ON -DCMAKE_NO_BUILTIN_CHRPATH=ON -DWITH_LAME=ON -DWITH_CAIRO=ON .

**Comment by akallabeth** [comment]
@hendwolt ok, thought `UINT32_MAX` is a sensible limit, turns out it is not ^^

**Comment by bmiklautz** [comment]
@freerdp-bot test

**Comment by bmiklautz** [comment]
@freerdp-bot test
