### ISSUE TITLE
./usr/bin/freerdp-proxy: not found: librdpgfx-client.so

### ISSUE THREAD

**Issue by sibskull** [FreeRDP/FreeRDP#5742]
After commit acad36465d freerdp-proxy links with librdpgfx-client.so library placed to plugin subdirectory (%_libdir/freerdp2), our verify_elf script cannot find librdpgfx-client.so. I try to build with
    -DCMAKE_SKIP_RPATH=FALSE \
    -DCMAKE_SKIP_BUILD_RPATH=FALSE \
    -DCMAKE_SKIP_INSTALL_RPATH=FALSE \
    -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
but without success.
I build with 
    -DWITH_CHANNELS=ON \
    -DBUILTIN_CHANNELS=OFF \

**Comment by akallabeth** [comment]
running `cmake -GNinja -DCMAKE_INSTALL_PREFIX=/tmp/test  -DBUILTIN_CHANNELS=OFF .` followed by a `cmake --build . --target install` is working here.
Sure you started from a clean checkout?

**Comment by akallabeth** [comment]
locations here (fedora):
* `./channels/rdpgfx/client/librdpgfx-client.so` (from build dir)
* `/tmp/test/lib64/freerdp2/librdpgfx-client.so` (absolute install dir)

**Comment by sibskull** [comment]
This is build without freerdp-proxy and it cannot reproduce issue.

**Comment by akallabeth** [comment]
@sibskull sorry, what? I thought the issue was that `librdpgfx-client.so` was not found? of course you have to add `-DWITH_SERVER=ON` to enable build/installation of `freerdp-proxy` binary.

**Comment by sibskull** [comment]
[builder@localhost freerdp-2.0.0]$ ldd /tmp/test/bin/freerdp-proxy | grep fou
        librdpgfx-client.so => not found
[builder@localhost freerdp-2.0.0]$ chrpath /tmp/test/bin/freerdp-proxy 
/tmp/test/bin/freerdp-proxy: RPATH=$ORIGIN/../lib64:$ORIGIN/..

RPATH does not contain $ORIGIN/../lib64/freerdp2 and librdpgfx-client.so not found.

**Comment by akallabeth** [comment]
@sibskull ok. got the issue.
Any specific reasons you build with `-DBUILTIN_CHANNELS=OFF`?
I´d just not use that, then it should work. (the default has better test coverage and this specific setting is not really useful except for certain thinclient only use cases)

**Comment by sibskull** [comment]
Thanks. Possible -DBUILTIN_CHANNELS=OFF got from https://src.fedoraproject.org/rpms/freerdp/blob/master/f/freerdp.spec#_158
I try to build with BUILTIN_CHANNELS=ON.

**Comment by akallabeth** [comment]
@sibskull ah, ok. this only controls if the (client) channels are built as separate libraries or part of the core and client library.
