### ISSUE TITLE
Proper Kerberos support

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#5746]
Freerdp Kerberos authentication support is currently in quite a sad state.
See #5258 #4832 #4770 #4559 #4467 #4363 #4348 #4311 and also blocks implementation of #3239

What needs to be done?
* Review current basic kerberos implementation available in FreeRDP and fix the ticket retrieval and authentication negitiation
* Encapsulate authentication in freerdp better to allow easily switching out the mechanism (NTLM/NLA/...)

**Comment by BryannaM** [comment]
Given there is no indication of this on github was hoping mentioning it here might help get more attention, but I did put up a 500$ bounty for this feature. I understand the complexity of kerberos means its not something easy to do. I also put 50$ up before for the Protected Group support which requires kerberos.
https://app.bountysource.com/issues/84220084-proper-kerberos-support

**Comment by hardening** [comment]
I guess we're gonna share the bounty with @sss123next as we've both worked hard on Kerberos last months !

**Comment by sss123next** [comment]
sorry, i skip this, for now, i have other urgent tasks,  my main goal for now is external io and external resource management (threading)

**Comment by hardening** [comment]
Sorry @sss123next I was meaning @fifthdegree

**Comment by hardening** [comment]
Closing as now we have full functional Kerberos support with both regular Kerberos and user2user.
