### ISSUE TITLE
Explicitly set output device in rdpsnd Mac backend

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#5747]
A Royal TSX customer recently alerted me of the fact that [Micro Snitch](https://www.obdev.at/products/microsnitch), a microphone monitoring tool for macOS reported that his microphone was active when playing (NOT recording) audio in an RDP session. That happens even when the audin channel is not even loaded so it's definitely a false positive.

I did some debugging and was able to reproduce the behavior. I then found the culprit in [this commit](https://github.com/FreeRDP/FreeRDP/commit/52af56d956e4e725f62030b6c990683158de5733#diff-81bf742aadc5d6ed432a42c812d1af2fL157).

The problem basically is this: If the output device is NOT explicitly set, AVAudioEngine activates both, input and output channels leading to the behavior that CoreAudio sends notifications of the activation of both devices, even if no audio is recorded through the input channel.

A demo project demonstrating the issue is [available here](https://github.com/lemonmojo/AVTest).

The fix is quite easy: Bring back the code that explicitly sets the output device to the default audio output device. Code for this can be found either in the FreeRDP commit I mentioned above or my [sample project](https://github.com/lemonmojo/AVTest/blob/master/AVTest/AppDelegate.m#L171).

**Comment by lemonmojo** [comment]
@mfleisz @akallabeth Unfortunately I have to re-open this issue.
After pulling in the changes from https://github.com/FreeRDP/FreeRDP/commit/4d8a4d39ba566f8a5e5f592fcb9559afad8dd42a I'm unable to get any sound output from FreeRDP.

As soon as I comment out the line which explicitly sets the output device (https://github.com/FreeRDP/FreeRDP/commit/4d8a4d39ba566f8a5e5f592fcb9559afad8dd42a#diff-81bf742aadc5d6ed432a42c812d1af2fR170) it starts working again.

I have no clue what's wrong as the code looks good to me and is pretty much the same as before and as in my sample project.

Can you guys reproduce this or do you get sound output with the changes in place?

**Comment by akallabeth** [comment]
@lemonmojo currently no `10.15` machine available (only 10.14) but it is working on these for me.

**Comment by mfleisz** [comment]
@lemonmojo can you give https://github.com/mfleisz/FreeRDP/tree/mac_rdpsnd_fix a try and see if this works for you? I checked on my Macbook and audio works after adding the AudioUnitGetProperty call (not sure why this fixes the problem but I guess it initializes something internally which is required by the following AudioUnitSetProperty call).

**Comment by mfleisz** [comment]
Hm on my Macbook it looks like sound is sometimes working and sometimes it doesn't with this PR. So back to debugging ... :-/

**Comment by lemonmojo** [comment]
@mfleisz Just tried it but on my iMac Pro I cannot get any sound to play at all using your patch. With an older FreeRDP build (before https://github.com/FreeRDP/FreeRDP/commit/52af56d956e4e725f62030b6c990683158de5733#diff-81bf742aadc5d6ed432a42c812d1af2fL157) the same connection and same audio file plays fine.

**Comment by mfleisz** [comment]
@lemonmojo for now I merged a small workaround (https://github.com/FreeRDP/FreeRDP/pull/5811) until we figure a proper way to disable the microphone on Catalina.

**Comment by lemonmojo** [comment]
@mfleisz Yeah, better than no sound at all. Unfortunately I don’t have enough time to debug this further at the moment. Might be able to continue in a couple of weeks.

**Comment by drewwats** [comment]
I just submitted a ticket for the same issue to the Royal TS team but was referred here. I definitely view it as a potential privacy concern and would love to know that it's not an issue. Any update or plans to roll out the bug fix?

**Comment by mfleisz** [comment]
@drewwats unfortunately we currently have no working fix for this issue and I can't tell you when someone of us gets time to have a look at this - sorry ... :-/

**Comment by drewwats** [comment]
> @drewwats unfortunately we currently have no working fix for this issue and I can't tell you when someone of us gets time to have a look at this - sorry ... :-/

I see 3 minor updates since the OP's post and not a single item on the release notes should be as high priority as users mic being involuntarily activated. "Visual artifacts" and "improved logging" aren't borderline illegal surveillance.

I use and appreciate your product but I'm also a person that cares about privacy. Please consider getting this moved up on the backlog and possibly requesting mic permissions to cover liability in the meantime.

**Comment by lemonmojo** [comment]
@mfleisz @akallabeth So I think I found a fix for this. If I move the call to `rdpsnd_mac_set_format` after creating the `AVAudioPlayerNode`, sound is playing again and there's no false positive regarding microphone activation.

Could you please check out [this patch](https://gist.github.com/lemonmojo/a962397acc4191fa62c7f46364f0931a) and see if it works on your hardware as well?

**Comment by lemonmojo** [comment]
@mfleisz @akallabeth After further testing, this only fixes the problem sometimes. Seems to be some kind of timing problem as I'm sometime able to get sound output and sometimes not.

**Comment by mfleisz** [comment]
@lemonmojo I had similar things happen with my initially proposed fix - sometimes it worked but then sometimes it didn't ... :-/

**Comment by lemonmojo** [comment]
@mfleisz @akallabeth Had another go at this today and think I finally came up with a workable solution.

I stumbled over the following hack on SO: https://stackoverflow.com/a/39936853/1025706
And indeed, if I put a sleep just before starting the `AVAudioEngine`, sound was playing again and the microphone wasn't activated. So it appears that the engine needs some time for the configuration to "sink in" before starting it and playing anything. Unfortunately, the way it currently works is that the rdpsnd module is only initialized on-demand just before playing a sound, so putting an artificial delay here is not the best idea. ;-)

So I continued debugging. I set a breakpoint in `rdpsnd_mac_start` and immediately noticed that the engine's [isRunning](https://developer.apple.com/documentation/avfoundation/avaudioengine/1388591-isrunning) property returned `NO` which, obviously, is not good if we're just about to play sound.

While I'm still not 100% sure why that happens, I have a workaround which at least on my machine works all the time.
I added a check for `AVAudioEngine.isRunning` in `rdpsnd_mac_start` before starting the player and if the engine is not running for whatever reason, I start it "again" at that point. After making that change I have not been able to reproduce the issue anymore. Tried at least 30 times on 3 different Windows hosts and sound started playing every single time.

Here's the patch with the changes: https://gist.github.com/lemonmojo/fb5342e370c331e2c5f6059fae912ba3
Can you please verify if this works for you too?

For a proper fix it would make sense to initialize the rdpsnd module early, before attempting to play any sound to give it enough time to properly start. But for now I guess my solution does the trick.

**Comment by mfleisz** [comment]
@lemonmojo Nice finding! I will give the patch a go as soon as I get my hands on my Mac development machine and let you know if it works for me as well!

**Comment by lemonmojo** [comment]
@mfleisz Thx! FYI: Just tested against some more Windows hosts and on another Mac and still haven't been able to reproduce the issue.

**Comment by mfleisz** [comment]
Sounds great - hope this is finally fixed with your patch! 👍

**Comment by lemonmojo** [comment]
@mfleisz @akallabeth Did you get the chance to test my patch? Would love to see this being fixed for good...

**Comment by mfleisz** [comment]
@lemonmojo Finally had time to give this a go - works like a charm! Can you submit a PR so we can get this finally fixed? Thanks a lot for your contribution! 👍

**Comment by lemonmojo** [comment]
@mfleisz Here ya go: https://github.com/FreeRDP/FreeRDP/pull/6467
