### ISSUE TITLE
Crashes when I copy URL on Google Chrome

### ISSUE THREAD

**Issue by lyndmi** [FreeRDP/FreeRDP#5749]
**Describe the bug**
RDP crashes when you copy a URL on Google Chrome browser. Works fine if you copy elsewhere like in Notepad++

**To Reproduce**
1. Open Chrome
2. Visit any websites
3. Copy the URL

**Expected behavior**
I expect that it can copy to clipboard and clipboard redirection works without any problems

**Screenshots**

** Application details
* Version of FreeRDP:  2.0.0-dev5 (3aa6047b3)mentation
* Command line used: `wfreerdp.exe /u:Administrator /p:Password /w:1280 /h:768 /v:192.168.xxx.xxx /f `
* output of `/buildconfig`:
```
[09:01:50:463] [7800:0000055c] [INFO][com.freerdp.client.windows] - Debug console created.
This is FreeRDP version 2.0.0-dev5 (3aa6047b3)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_FAAC=OFF WITH_FAAD2=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_WINPR_TOOLS=ON WITH_X264=OFF
Build type:          Release
CFLAGS:               /DWIN32 /D_WINDOWS  /Gd /W3
Compiler:            MSVC, 18.0.40629.0
Target architecture: x86
```
* OS version connecting to: Win Server 2008 RC2 (Running in VM in my QNAP TS-451)
* If available the log output from a run with `/log-level:trace`: The log is obviously too long so i took a part where the crash occured
```
[08:41:12:119] [6328:00001fe0] [DEBUG][com.freerdp.channels.cliprdr.client] - ServerFormatList: numFormats: 5
[08:41:12:123] [6328:00001fe0] [DEBUG][com.freerdp.channels.cliprdr.client] - ServerFormatList: numFormats: 5
[08:41:12:128] [6328:00001248] [DEBUG][com.freerdp.channels.cliprdr.client] - ClientFormatDataRequest
[08:41:12:136] [6328:00001fe0] [ERROR][com.freerdp.channels.cliprdr.client] - ServerFormatList failed with error 1359
[08:41:12:140] [6328:00001fe0] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_format_list failed with error 1359!
[08:41:12:147] [6328:00001fe0] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_order_recv failed with error 1359!
[08:41:12:151] [6328:000015b4] [ERROR][com.freerdp.core] - cliprdr_virtual_channel_client_thread reported an error. Error was 1359
[08:41:12:155] [6328:000015b4] [ERROR][com.freerdp.core] - checkChannelErrorEvent() failed - 0
[08:41:12:160] [6328:000015b4] [INFO][com.freerdp.client.common] - Network disconnect!
[08:41:12:163] [6328:000015b4] [ERROR][com.freerdp.client.windows] - Failed to check FreeRDP file descriptor
[08:41:12:180] [6328:000015b4] [DEBUG][com.freerdp.client.windows] - Main thread exited with 0
[08:41:12:195] [6328:000018e0] [DEBUG][com.freerdp.client.windows] - Keyboard thread exited.
```

**Desktop (please complete the following information):**
 - OS: Windows 10 x86
 - Browser: Chrome
 - Version: 78.0.3904.108

**Smartphone (please complete the following information):**
 - Device: iPhone 5
 - OS: iOS 10.3.4
 - Browser: Safari
 - Version: Unknown

**Comment by akallabeth** [comment]
can´t see a crash there, looks like proper shutdown on a error condition?
requires further input, this seems to be a local issue with the clipboard, is anything else accessing it?

**Comment by lyndmi** [comment]
Turns out it was Google Remote Desktop issue that had access to clipboard. I was securely remoting to my main pc then remote to my NAS running Win 2008 VM using RDP
Funnily it works perfectly on build-in RDP software by Microsoft but I like FreeRDP better
Clipboard redirection is not really important so I will just disable it using `-clipboard`
Should the issue be closed?

**Comment by akallabeth** [comment]
@lyndmi ok, that explains the error. Could you check if the built in rdp clipboard works or if has isdues too ?

**Comment by lyndmi** [comment]
It does work perfectly. It was able to share clipboard though RDP and then though Google Remote Desktop at the same time lol

**Comment by lyndmi** [comment]
Alright I will try it later. I need to setup compliation to compile this commit

**Comment by lyndmi** [comment]
Can you compile this commit for me if you don't mind?
I'm faling to setup compliation on Windows and getting more headache dealing with errors. I'm not expert in compliation sadly hehe
Clipboard redirection is not a big deal anyway

**Comment by akallabeth** [comment]
@lyndmi just wait until the pr is merged, the next day it is part of the nightly builds.

**Comment by lyndmi** [comment]
Thanks for merging, It actually works without crashes!
