### ISSUE TITLE
wfreedrp.exe does nothing on windows

### ISSUE THREAD

**Issue by Peeeeeeee** [FreeRDP/FreeRDP#5754]
Have tried downloading both cloud versions for windows and the latest stable nightly version #699.  I have tried running the executables as admin with both a windows 7 and windows 10 system.  Windows 10 is 1903 and I have checked firewalls and antivirus programs but there are no logs anywhere of anything blocking it.  I have created a text log detailing the current version of wfreerdp after nothing happens and it just says it isn't a recognizable batch or command, so it really is doing nothing.  I don't even see it doing anything from the system monitor.  I feel infinitely stupid that I can't even download and run the executable correctly.  Are there some prerequisites like Visual Studio that are required for this application to run?  I don't see anything in any documentation on needing to do special activities with the executable and I was hoping to avoid cloning the source and self-compiling.  What stupid thing am I doing wrong here?  Both systems are 64.

**Comment by akallabeth** [comment]
Please use the mailing list or irc for support.
As for wfreerdp, it is a command line app, you can create a lig with wfreerdp.exe <your args> >log.txt 2>&1
