### ISSUE TITLE
Can't switch back to Windows host from remote Linux session.

### ISSUE THREAD

**Issue by svak** [FreeRDP/FreeRDP#5770]
host: Windows 10
remote: archlinux

In Windows:
1) wfreerdp.exe /v:... /u:... /p:... /floatbar /f
(This is FreeRDP version 2.0.0-dev5 (d96a61d8c))

Remote session works fine, but I can't switch to Windows host.
1) No float toolbar visible
2) Right Ctrl does not work
3) Ctrl+Alt+Enter does not work
4) Ctrl+Alt+Del is work. I can kill wfreerdp. But CAD is sent to archlinux, and KDE session is closed.

What would I expect:
1) Right Ctrl switch focus to windows host.
2) Ctrl+Alt+Enter toggle fullscreen
3) Floatbar is visible and operable (minimize, close, pin/unpin)
4) Ctrl+Alt+Del does not sent to remote session

**Comment by akallabeth** [comment]
@svak Hi, does it work with a newer build? `d96a61d` is already a few months old and we ironed out a lot of issues since then.

**Comment by svak** [comment]
@akallabeth 
Installed https://ci.freerdp.com/job/freerdp-nightly-windows/704/
and /floatbar is visible now. Thank you!
Although shortcuts does not work anyway :(
