### ISSUE TITLE
Can't setup display resolution for Linux remote session.

### ISSUE THREAD

**Issue by svak** [FreeRDP/FreeRDP#5773]
host: Windows 10
remote: archlinux

In Windows:

$ wfreerdp.exe /v:... /u:... /p:... **/size:1920x1080** /floatbar /f
(This is FreeRDP version 2.0.0-dev5 (00eabb2c9))

Remote session opens with (i think) size 1366x768. Scaled to 1920x1080 (my notebook native resolution), and is very blury.
If I open that session with Microsoft Remote Desktop then screen resolution will be 1920x1080.

I expect that session will be with 1920x1080 screen resolution.

**Comment by akallabeth** [comment]
Please use mailing list or IRC for support questions.
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
