### ISSUE TITLE
freerdp-shadow-cli - where to specify authentication option?

### ISSUE THREAD

**Issue by Trouble123** [FreeRDP/FreeRDP#5774]
When you start freerdp-shadow-cli.exe on windows, with +auth, how is the client authenticating? 

What username/password does the client need to send, or more importantly how do we set the username/password on the server(freerdp-shadow-cli) end?

Thanks

**Comment by akallabeth** [comment]
@Trouble123 windows shadow server currently does not support authentication. See `shw_authenticate`
