### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by sufidu** [FreeRDP/FreeRDP#5779]
I tried to build FreeRDP on Ubuntu 18.04.3 version.
I did everything mentioned in [compilation](https://github.com/FreeRDP/FreeRDP/wiki/Compilation) page.
When I run below command:

`flatpak-builder ~/Android/compile/FreeRDP packaging/flatpak/com.freerdp.FreeRDP.json`

I got error like [this issue](https://github.com/FreeRDP/FreeRDP/issues/5654).

Then I 

> replace the packaging/flatpak/shared-modules folder with git@github.com:flathub/shared-modules.git

 like below (mentioned in that issue)

```
cd packaging/flatpak
rm -rf shared-modules
git clone https://github.com/flathub/shared-modules
```

And the run below commands

```
ln -s packaging/deb/freerdp-nightly debian
dpkg-buildpackage
```

And got below error:
```
make[1]: Leaving directory '/home/stellarplex/Android/main_source/FreeRDP'
   dh_installdeb -O--parallel
   dh_gencontrol -O--parallel
   dh_md5sums -O--parallel
   dh_builddeb -O--parallel
dpkg-deb: building package 'freerdp-nightly' in '../freerdp-nightly_2.0.0_amd64.deb'.
dpkg-deb: building package 'freerdp-nightly-dev' in '../freerdp-nightly-dev_2.0.0_amd64.deb'.
dpkg-deb: building package 'freerdp-nightly-dbg' in '../freerdp-nightly-dbg_2.0.0_amd64.deb'.
 dpkg-genbuildinfo
 dpkg-genchanges  >../freerdp-nightly_2.0.0_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build FreeRDP
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
 signfile freerdp-nightly_2.0.0.dsc
gpg: skipped "FreeRDP <team@freerdp.com>": No secret key
gpg: dpkg-sign.5Yd2wSua/freerdp-nightly_2.0.0.dsc: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc file
```

Then try to run `cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON .` command and got 

```
-- Finding optional feature FAAD2 for codec (FAAD2 AAC audio codec library)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find FAAD2 (missing: FAAD2_INCLUDE_DIR FAAD2_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindFAAD2.cmake:6 (find_package_handle_standard_args)
  cmake/FindFeature.cmake:31 (find_package)
  CMakeLists.txt:876 (find_feature)

-- Configuring incomplete, errors occurred!
```

And for `cmake --build .` command the output is `ninja: error: loading 'build.ninja': No such file or directory` though ninja is installed (1.8.2)

What is the solution? Expected your reply. Thanks.

**Comment by akallabeth** [comment]
@sufidu you should stick to one method of compilation ;)
1. The flatpack method has the issue you referenced
1. If you try to build it using the debian packaging system then you were successful ;) the error is for a package that was not signed, so look around for some `.deb` files that have been created
1. If you try to compile yourself, I´d check you have development headers installed (the message is quite clear, you have no `faad2` development headers installed.

**Comment by sufidu** [comment]
@akallabeth thank you very much for your help. 
I found those `.deb` files. Now I need KeyID to sign. Where can I found it? Can you help?

Two more thing.
I am going to build for android version. 
1. My system has `openssl 1.1.1` which was built on Sep 2018. Do I need to manually update it??
2. Do I need to install `https://github.com/akallabeth/jpeg8d` this repository also??

Thanks in advance. Waiting to hear from you.

**Comment by sufidu** [comment]
Here is the latest error log:

```
make[1]: Leaving directory '/home/stellarplex/Android/main_source/FreeRDP'
   dh_installdeb -O--parallel
   dh_gencontrol -O--parallel
   dh_md5sums -O--parallel
   dh_builddeb -O--parallel
dpkg-deb: building package 'freerdp-nightly-dev' in '../freerdp-nightly-dev_2.0.0_amd64.deb'.
dpkg-deb: building package 'freerdp-nightly' in '../freerdp-nightly_2.0.0_amd64.deb'.
dpkg-deb: building package 'freerdp-nightly-dbg' in '../freerdp-nightly-dbg_2.0.0_amd64.deb'.
 dpkg-genbuildinfo
 dpkg-genchanges  >../freerdp-nightly_2.0.0_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build FreeRDP
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
 signfile freerdp-nightly_2.0.0.dsc
gpg: skipped "FreeRDP <team@freerdp.com>": No secret key
gpg: dpkg-sign._dk1GtB8/freerdp-nightly_2.0.0.dsc: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc file
```

How can I find the secret key?

**Comment by sufidu** [comment]
> @sufidu you should stick to one method of compilation ;)
> 
>     1. The flatpack method has the issue you referenced
> 
>     2. If you try to build it using the debian packaging system then you were successful ;) the error is for a package that was not signed, so look around for some `.deb` files that have been created
> 
>     3. If you try to compile yourself, I´d check you have development headers installed (the message is quite clear, you have no `faad2` development headers installed.

Here is the latest error log:

```
make[1]: Leaving directory '/home/stellarplex/Android/main_source/FreeRDP'
   dh_installdeb -O--parallel
   dh_gencontrol -O--parallel
   dh_md5sums -O--parallel
   dh_builddeb -O--parallel
dpkg-deb: building package 'freerdp-nightly-dev' in '../freerdp-nightly-dev_2.0.0_amd64.deb'.
dpkg-deb: building package 'freerdp-nightly' in '../freerdp-nightly_2.0.0_amd64.deb'.
dpkg-deb: building package 'freerdp-nightly-dbg' in '../freerdp-nightly-dbg_2.0.0_amd64.deb'.
 dpkg-genbuildinfo
 dpkg-genchanges  >../freerdp-nightly_2.0.0_amd64.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --after-build FreeRDP
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
 signfile freerdp-nightly_2.0.0.dsc
gpg: skipped "FreeRDP <team@freerdp.com>": No secret key
gpg: dpkg-sign._dk1GtB8/freerdp-nightly_2.0.0.dsc: clear-sign failed: No secret key

dpkg-buildpackage: error: failed to sign .dsc file
```

How can I find the secret key?

**Comment by akallabeth** [comment]
@sufidu you create one.
Further reading for this can be found here: https://wiki.debian.org/Packaging

**Comment by sufidu** [comment]
> @sufidu you create one.
> Further reading for this can be found here: https://wiki.debian.org/Packaging

Thanks again. I have skipped this part and able to build libraries for android.
But this source only runs in device with API >= 21.
Can we build it for API >= 19 by any chance? I need it urgently.
