### ISSUE TITLE
another set of lto-type-mismatch warnings

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#5789]
In the current master I found a new set of lto-type-mismatch warnings:
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:100:13: warning: type of 'pulse_freerdp_audin_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/pulse/audin_pulse.c:479:6: note: return value type mismatch
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/pulse/audin_pulse.c:479:6: note: type 'UINT' should match type 'void'
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:99:13: warning: type of 'alsa_freerdp_audin_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/alsa/audin_alsa.c:404:6: note: return value type mismatch
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/alsa/audin_alsa.c:404:6: note: type 'UINT' should match type 'void'
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:105:13: warning: type of 'fake_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/fake/rdpsnd_fake.c:131:6: note: return value type mismatch
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/fake/rdpsnd_fake.c:131:6: note: type 'UINT' should match type 'void'
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:104:13: warning: type of 'proxy_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/proxy/rdpsnd_proxy.c:120:6: note: return value type mismatch
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/proxy/rdpsnd_proxy.c:120:6: note: type 'UINT' should match type 'void'
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:103:13: warning: type of 'pulse_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/pulse/rdpsnd_pulse.c:575:6: note: return value type mismatch
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/pulse/rdpsnd_pulse.c:575:6: note: type 'UINT' should match type 'void'
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:102:13: warning: type of 'alsa_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/alsa/rdpsnd_alsa.c:526:6: note: return value type mismatch
[  144s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/alsa/rdpsnd_alsa.c:526:6: note: type 'UINT' should match type 'void'
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:100:13: warning: type of 'pulse_freerdp_audin_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/pulse/audin_pulse.c:479:6: note: return value type mismatch
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/pulse/audin_pulse.c:479:6: note: type 'UINT' should match type 'void'
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:99:13: warning: type of 'alsa_freerdp_audin_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/alsa/audin_alsa.c:404:6: note: return value type mismatch
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/alsa/audin_alsa.c:404:6: note: type 'UINT' should match type 'void'
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:105:13: warning: type of 'fake_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/fake/rdpsnd_fake.c:131:6: note: return value type mismatch
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/fake/rdpsnd_fake.c:131:6: note: type 'UINT' should match type 'void'
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:104:13: warning: type of 'proxy_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/proxy/rdpsnd_proxy.c:120:6: note: return value type mismatch
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/proxy/rdpsnd_proxy.c:120:6: note: type 'UINT' should match type 'void'
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:103:13: warning: type of 'pulse_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/pulse/rdpsnd_pulse.c:575:6: note: return value type mismatch
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/pulse/rdpsnd_pulse.c:575:6: note: type 'UINT' should match type 'void'
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:102:13: warning: type of 'alsa_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/alsa/rdpsnd_alsa.c:526:6: note: return value type mismatch
[  187s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/alsa/rdpsnd_alsa.c:526:6: note: type 'UINT' should match type 'void'

As usual I build for openSUSE (Tumbleweed) with the following settings:
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_SKIP_INSTALL_RPATH=ON -DWITH_CUPS=ON -DWITH
_CLIENT=ON -DWITH_PCSC=ON -DWITH_ALSA=ON -DWITH_PULSE=ON -DWITH_OSS=OFF -DWITH_DIRECTFB=OFF -DWITH_JPEG=ON -DWITH_GSM=ON -DWITH_GSTREAMER_1_0=ON -DWITH_IPP=OFF -D
WITH_OPENSSL=ON -DWITH_CHANNELS=ON -DWITH_X11=ON -DWITH_XCURSOR=ON -DWITH_XEXT=ON -DWITH_XKBFILE=ON -DWITH_XI=ON -DWITH_XINERAMA=ON -DWITH_XRENDER=ON -DWITH_XV=ON
 -DWITH_ZLIB=ON -DWITH_KRB5=ON -DBUILTIN_CHANNELS=ON -DWITH_SERVER=ON -DWITH_SSE2=ON -DWITH_DEBUG_SCARD=OFF -DWITH_SMARTCARD_INSPECT=ON -DWITH_ICU=ON -DWITH_FFMPE
G=ON -DWITH_DSP_FFMPEG=ON -DWITH_WAYLAND=ON -DWITH_SANITIZE_ADDRESS=OFF -DWITH_LIBSYSTEMD=ON -DCMAKE_NO_BUILTIN_CHRPATH=ON -DWITH_LAME=ON -DWITH_CAIRO=ON

**Comment by akallabeth** [comment]
@hendwolt thanks for the reminder, this one will have to stay for a bit (this was previously hidden due to some C black magic)

**Comment by akallabeth** [comment]
Should be fixed with #5896

**Comment by hendwolt** [comment]
Don't think so:
`[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:100:13: warning: type of 'pulse_freerdp_audin_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[   81s]   100 | extern void pulse_freerdp_audin_client_subsystem_entry(void);
[   81s]       |             ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/pulse/audin_pulse.c:479:6: note: return value type mismatch
[   81s]   479 | UINT freerdp_audin_client_subsystem_entry(PFREERDP_AUDIN_DEVICE_ENTRY_POINTS pEntryPoints)
[   81s]       |      ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/pulse/audin_pulse.c:479:6: note: type 'UINT' should match type 'void'
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/pulse/audin_pulse.c:479:6: note: 'pulse_freerdp_audin_client_subsystem_entry' was previously declared here
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:99:13: warning: type of 'alsa_freerdp_audin_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[   81s]    99 | extern void alsa_freerdp_audin_client_subsystem_entry(void);
[   81s]       |             ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/alsa/audin_alsa.c:404:6: note: return value type mismatch
[   81s]   404 | UINT freerdp_audin_client_subsystem_entry(PFREERDP_AUDIN_DEVICE_ENTRY_POINTS pEntryPoints)
[   81s]       |      ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/alsa/audin_alsa.c:404:6: note: type 'UINT' should match type 'void'
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/audin/client/alsa/audin_alsa.c:404:6: note: 'alsa_freerdp_audin_client_subsystem_entry' was previously declared here
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:105:13: warning: type of 'fake_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[   81s]   105 | extern void fake_freerdp_rdpsnd_client_subsystem_entry(void);
[   81s]       |             ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/fake/rdpsnd_fake.c:127:6: note: return value type mismatch
[   81s]   127 | UINT freerdp_rdpsnd_client_subsystem_entry(PFREERDP_RDPSND_DEVICE_ENTRY_POINTS pEntryPoints)
[   81s]       |      ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/fake/rdpsnd_fake.c:127:6: note: type 'UINT' should match type 'void'
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/fake/rdpsnd_fake.c:127:6: note: 'fake_freerdp_rdpsnd_client_subsystem_entry' was previously declared here
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:104:13: warning: type of 'proxy_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[   81s]   104 | extern void proxy_freerdp_rdpsnd_client_subsystem_entry(void);
[   81s]       |             ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/proxy/rdpsnd_proxy.c:116:6: note: return value type mismatch
[   81s]   116 | UINT freerdp_rdpsnd_client_subsystem_entry(PFREERDP_RDPSND_DEVICE_ENTRY_POINTS pEntryPoints)
[   81s]       |      ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/proxy/rdpsnd_proxy.c:116:6: note: type 'UINT' should match type 'void'
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/proxy/rdpsnd_proxy.c:116:6: note: 'proxy_freerdp_rdpsnd_client_subsystem_entry' was previously declared here
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:103:13: warning: type of 'pulse_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[   81s]   103 | extern void pulse_freerdp_rdpsnd_client_subsystem_entry(void);
[   81s]       |             ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/pulse/rdpsnd_pulse.c:586:6: note: return value type mismatch
[   81s]   586 | UINT freerdp_rdpsnd_client_subsystem_entry(PFREERDP_RDPSND_DEVICE_ENTRY_POINTS pEntryPoints)
[   81s]       |      ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/pulse/rdpsnd_pulse.c:586:6: note: type 'UINT' should match type 'void'
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/pulse/rdpsnd_pulse.c:586:6: note: 'pulse_freerdp_rdpsnd_client_subsystem_entry' was previously declared here
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/client/tables.c:102:13: warning: type of 'alsa_freerdp_rdpsnd_client_subsystem_entry' does not match original declaration [-Wlto-type-mismatch]
[   81s]   102 | extern void alsa_freerdp_rdpsnd_client_subsystem_entry(void);
[   81s]       |             ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/alsa/rdpsnd_alsa.c:526:6: note: return value type mismatch
[   81s]   526 | UINT freerdp_rdpsnd_client_subsystem_entry(PFREERDP_RDPSND_DEVICE_ENTRY_POINTS pEntryPoints)
[   81s]       |      ^
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/alsa/rdpsnd_alsa.c:526:6: note: type 'UINT' should match type 'void'
[   81s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/channels/rdpsnd/client/alsa/rdpsnd_alsa.c:526:6: note: 'alsa_freerdp_rdpsnd_client_subsystem_entry' was previously declared here`

**Comment by akallabeth** [comment]
@hendwolt true, sorry, mixed that one up with a few other warnings fixed.
