### ISSUE TITLE
SCardListReadersW failed with error -2146435043

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#5791]
**Describe the bug**
Smartcard redirection seems to work properly with #5499, however one of our customers see `[15:21:32:565] [18068:18191] [ERROR][com.freerdp.channels.smartcard.client] - SCardListReadersW failed with error -2146435043` in the log every 2 ms anyway when connecting to Windows 10. Any idea what is wrong?

**To Reproduce**
1. Connect to Windows 10 using `--no-nla --plugin rdpsnd  --plugin rdpdr --data scard: --` options. (They use an old syntax for some reason, but it seems that it is correctly translated to `-no-nla` and `/smartcard` options).
2. `SCardListReadersW failed with error -2146435043` is printed every 2 ms.

**Application details**
It has been tested on RHEL 7/8 with rc4 including #5499. It has been tried with several other smartcard fixes from master, but without any success.

**Comment by akallabeth** [comment]
@ondrejholy just stumbled over this:
`[MS-RDPESC] 1.7 Versioning and Capability Negotiation`
you might want to try to increase the number sent in `settings->ClientBuild`

**Comment by bmiklautz** [comment]
@akallabeth interesting that they use the build number exactly for this as this must not be set at all. It's something the client chooses. Definitely worth a try.

**Comment by ondrejholy** [comment]
That sounds promising, I will pass build with the modified `ClientBuild` number (https://github.com/FreeRDP/FreeRDP/pull/5793/commits/6482a638f456c158bf83c2e31e2c20e3d29654c8) to our customers for testing and let you know...

**Comment by akallabeth** [comment]
@ondrejholy ok, was able to reproduce it when uninstalling `pcscd` on my ubuntu test machine.
Without it the smartcard channel can not create a context with `system` scope and returns this failure.
If it is running the error disappears.

**Comment by akallabeth** [comment]
@ondrejholy as for the `ClientBuild` I´ve run some tests and I think I found the core issue.
See `[MS-RDPESC] 1.7 Versioning and Capability Negotiation` for version limits, but if you keep the number `< 7865` the service should be working.
If it is larger the channel assumes `SCREDIR_VERSION_WINDOWS_8` capabilities and requires a few more calls to be implemented `SCardGetDeviceTypeId` et al.

**Comment by ondrejholy** [comment]
> @ondrejholy ok, was able to reproduce it when uninstalling `pcscd` on my ubuntu test machine.
> Without it the smartcard channel can not create a context with `system` scope and returns this failure.
> If it is running the error disappears.

Hmm, I would think that without `pcscd` the smartcard redirection would not work at all, but it works for them, just they see those errors. But I will ask them to check whether `pcscd` is running.

**Comment by ondrejholy** [comment]
> @ondrejholy as for the `ClientBuild` I´ve run some tests and I think I found the core issue.
> See `[MS-RDPESC] 1.7 Versioning and Capability Negotiation` for version limits, but if you keep the number `< 7865` the service should be working.
> If it is larger the channel assumes `SCREDIR_VERSION_WINDOWS_8` capabilities and requires a few more calls to be implemented `SCardGetDeviceTypeId` et al.

Yay, that's it, but it also seems that `SCREDIR_VERSION_LONGHORN` requires functions that are not implemented like SCARD_IOCTL_GETTRANSMITCOUNT, SCARD_IOCTL_READCACHEW, SCARD_IOCTL_READCACHEA, SCARD_IOCTL_WRITECACHEW, and SCARD_IOCTL_WRITECACHEA... or does it work to you?

**Comment by akallabeth** [comment]
@ondrejholy works with basic stuff, but needs another pr. (the functions you mentioned)

**Comment by akallabeth** [comment]
@ondrejholy ok, added all the required stuff in #5830 which allows
1. Setting the `ClientBuild` from command line
1. Implements the required functions for newer protocol versions (still needs some testing though)

**Comment by akallabeth** [comment]
I´ve created #5884 to improve smartcard data read/write.
Tested through all functions so far (with the small test program and a few real applications) and the new functions are working so far.

**Comment by ondrejholy** [comment]
@akallabeth, thanks for your work on this. I will provide a testing build to our customer and let you know.
