### ISSUE TITLE
CentOS reboots when trying full screen with Ctrl+Alt+Enter

### ISSUE THREAD

**Issue by Easwer** [FreeRDP/FreeRDP#5799]
**Environment:**

~]$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

~]$ xfreerdp /version
This is FreeRDP version 2.0.0-rc4 (n/a)

**Command to launch:**

~]$ xfreerdp /u:User /v:win-machine9 /gd:networks '/p:Password'

The new window is launching properly. When I try to get a full screen of the window using **_Ctrl+Alt+Enter_** then the user in the system gets logged off and redirected to the CentOS login page as a new boot. All running applications were killed.

**Comment by akallabeth** [comment]
I´d check the local key bindings of your WM. Sounds a lot like there is a mapping for what you see.

**Comment by akallabeth** [comment]
No feedback, closing.

**Comment by akallabeth** [comment]
oops, sorry, wrong issue ^^
