### ISSUE TITLE
Using sound in windows leads to client crash after some time.

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#5804]
**Description**
Using sound in windows leads to client crash after some time.

**To Reproduce**
1. Connect to a server with sound support using the /sound switch.
2. Open a really long youtube video
3. Wait for some time. I can consistently reproduce the crash after about 1 hour, sometimes less, sometimes more.

** Application details
* Nightly build 710, win32, vs2013
* Windows Server 2016

**Desktop:**
 - OS: Windows 10

**Additional context**
Came across these bug while testing for issue #5514

**Comment by akallabeth** [comment]
#5818 should fix the issues (and your sound problems in general).
Looks like a buffer was freed up prematurely

**Comment by vscfreire** [comment]
Testing nightly build 718: The sound is much improved but the client freezes after a while.

**Comment by akallabeth** [comment]
@vscfreire well, some log would be interesting ;)

**Comment by vscfreire** [comment]
@akallabeth unfortunately the log isn't very helpful as the client freezes, requiring to force close it. This looks like something between the client and the sound backend because until I force close it, I can't even open Windows volume mixer.

**Comment by akallabeth** [comment]
@vscfreire I´m closing this as resolved, should you experience another sound related hang feel free to create a new issue.
