### ISSUE TITLE
Redirected drives apear as empty when using the +drives switch. 

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#5805]
**Description**
Redirected drives appear as empty when using the +drives switch. 

**To Reproduce**
1. Connect to a server using the +drive switch.
2. Open the redirected C drive in explorer.
3. The drive (or any other redirected drives) appears empty.

** Application details
* Nightly build 710, win32, vs2013
* Windows Server 2016

**Desktop:**
 - OS: Windows 10

**Comment by akallabeth** [comment]
@vscfreire thx for the hint, hope the pr fixes it.

**Comment by vscfreire** [comment]
Testing nightly build 718: The drives appear and the files are correctly listed, even with a USB drive if I start freerdp with the drive plugged. If I unplug and plug it again with the session opened, I cant list that drive contents anymore but it still reappears.
