### ISSUE TITLE
freerdp 2.0.0-rc4 (well any v2) authonly not working

### ISSUE THREAD

**Issue by paulmorrisprodec** [FreeRDP/FreeRDP#5814]
I have been using FreeRDP xfreerdp version 1.0.2 to authenticate/test an RDP session absolutely fine but with the introduction of TLS1.1/1.2/1.3 it means that I need an updated version of xfreerdp.

I have installed 2.0.0-rc4 (centos) from repos and also tried to build other v2 versions from source - all exhibit the same issue:

The "authenticate only" option does not work purely on the command line (i.e. no GUI). If I run "xfreerdp /version" I get errors about the DISPLAY variable, but it shouldn't be trying to open a window - just display the version on the command line. This would be the same as authonly - it shouldn't try to open up a window, just open a session to the remote computer, login with the supplied credentials, then exit out with a good/bad status) - all on the command line. There is also some confusion about the option to use (the man page says +auth-only but I have tried various combinations - none of which work.

Am I doing something wrong or is this a bug?

**Comment by akallabeth** [comment]
looks like you found a bug (some X11 function seems to be used before a display is necessary)

**Comment by akallabeth** [comment]
the `auth-only` should work if you start it from a `X11` environment though

**Comment by paulmorrisprodec** [comment]
And that is the issue, I only need it to test RDP service on remote servers (via an unattended script) - there is no user intervention, no need for a full blown X11 environment. I know I can test port 3389 is open and even that I get a TLS session established but that isn't the same as testing the authentication method.

**Comment by akallabeth** [comment]
@paulmorrisprodec yes, that was understood. only want to know if the `auth-only` option works for you too if you have `X11` available.

**Comment by paulmorrisprodec** [comment]
I wouldn't know - I presume it would - however the server that will run xfreerdp won't have X windows installed as it doesn't need it. I know that from googling, lots of people try and use xfreerdp in the same way to test rdp from command line (my use case is using it to monitor servers using zabbix so will run a batch script to run the command unattended).

**Comment by akallabeth** [comment]
@paulmorrisprodec yes, but it is some work and testing.
Does have kind of low priority as I have a few other things to fix first, but pull requests are always welcome.

**Comment by paulmorrisprodec** [comment]
Ah brill - thank you!

**Comment by noglue** [comment]
We experience the same problem. We use xfreerdp on a scan server with no X11 env and the update broke our workflow. A fix would be greatly appreciated - Thanks!

**Comment by paulmorrisprodec** [comment]
@akallabeth do you need me to do anything for the pull request? I would quite happily review but I know I had issues doing a test compile on a centos box.

**Comment by akallabeth** [comment]
@paulmorrisprodec ok, found a simpler solution.
Added the `/auth-only` option to the sample client `sfreerdp` in #5882 
This way you can simply replace `xfreerdp` with `sfreerdp` for your use case and don´t need `X11` around.

**Comment by paulmorrisprodec** [comment]
I'm trying to compile (following the guide) but just getting errors - udev 175 - seems that all the code for udev/*.c is incorrect lines such as 

prefix, major(statbuf.st_dev)
prefix, minor(statbuf.st_dev)

I get warning: implicit declaration of function "...." did you mean mknod and then it seems to spiral till I get
Makefile:xxx :udev/udevd Error1
Waiting for unfinished jobs....
....

Error: module udev: Child process exited with code 2

What do I need to do?

**Comment by paulmorrisprodec** [comment]
Is there just a way of compiling sfreerdp?

**Comment by paulmorrisprodec** [comment]
I see there is a new version of the flatpak thing (whatever that is) - 19.08 which I've installed (replacing the 18.08 in the instructions) but still fails.

**Comment by paulmorrisprodec** [comment]
I've tried taking the udev compilation out (by amending the json) but then it fails trying to find libudev.h which I'm guessing gets compiled in udev

**Comment by akallabeth** [comment]
@paulmorrisprodec need to update the flatpak build description (you need to update the flatpak shared-modules, we only copied it to avoid having git submodules, but every time there is an update it breaks)
As for simply compiling, you can just add `-DWITH_SAMPLE=ON` to your build (`debian/rules` if you build the nightly)

**Comment by paulmorrisprodec** [comment]
How do I update the shared-modules? Googling I found someone that did a git clone (git clone https://github.com/flathub/shared-modules) and replaced the directory within the flatpak dirs of your source code. However this doesn't have a udev directory or json file so compilation fails when I run the flatpak-builder command to compile. If I copy that udev file back in I'm back to square one and the compilation fails due to the source code issues above.

I'm not really a programmer or understand what flatpak is, so I need a bit more of a handhold I'm afraid (as will others that are possibly trying to follow in my footsteps).

**Comment by paulmorrisprodec** [comment]
However I've managed to compile the sample bit of it (once I got a C++ compiler installed). However I get undefined symbols as the binary uses the libs in a different dir so I'll have to pick them up and move to the target machine to test.

**Comment by paulmorrisprodec** [comment]
@akallabeth as I only need to do authonly, --sec nla and openssl (for certs) what are the bare minimum of the modules that I need to run cmake with?

**Comment by akallabeth** [comment]
@paulmorrisprodec which distro? For debian based do
1. apt build-dep freerdp to get a build environment.
1. run cmake followed by ccmake (edit the install path and WITH_SAMPLE)
1. cmake --build . --target install

**Comment by paulmorrisprodec** [comment]
I'm using CentOS/RHEL, I don't mean how to install it, I mean the cmake options, so to build with SAMPLE on, I would do:-

cmake -DWITH_SAMPLE=ON
cmake --build ,

By default lots of modules are switched on (for instance ffmpeg). I'm just trying to build with the smallest possible of dependencies on libs but not really conversant with all the modules (for instance SSE2, Neon, Cairo, etc etc) hence conversing with someone that knows what they are and what they do. I just need to be able to run sfreerdp with authonly, the sec option and openssl (for TLS).

I can run ccmake to list all the options that cmake discovers, but there has to be a subset that absolutely must be switched on in order for the build to work. Or am I misunderstanding that Sample is just a sub-module so nothing I do would for example stop the dependency on libavcodec.so.56 (why would I need AV or ffmpeg?)

For the moment I'll just compile with the default set of modules on my build machine and wade my way through symbol errors when I run sfreerdp (which are going to be declared in shared objects) and transfer them to the target machine so that I can test.

I do really appreciate the time you are taking over this by the way!

**Comment by paulmorrisprodec** [comment]
OK so I've built it turning off CAIRO, FFMPEG, WINPR amongst other things. I still needed the libwinpr (despite it being turned off) and I can run it on the target machine if I copy over the compiled libfreerdp-client2 and libwinpr2 shared objects and set LD_LIBRARY_PATH (to keep the shared objects away from the normal /lib64:/usr/lib64 libs).

Initial testing good - if the users password is incorrect the debug info that comes out on stdout says Segmentation fault but does says exit status 1 in the stdout/stderr, $? comes out as 139. If correct password is used no seg fault, exit status says 0, $? comes out as 0. If cert if untrusted I get the same as bad password.  Bad destination the same. If the user does not have permission, the same. So if the exit status is 0, we're good, otherwise there is a username/password/permissions/network failure. Tested connection to server only offering TLS 1.2 - working. So I'm happy and will be able to use sfreerdp to test RDP connections.

**Comment by paulmorrisprodec** [comment]
Would be good to know how to get the flatpak side of things working (and documented!), and to get the /authonly working in the proper version.... but I guess there are other priorities!

**Comment by paulmorrisprodec** [comment]
Thank you @akallabeth for your help!

**Comment by akallabeth** [comment]
@paulmorrisprodec better not copy manually, set CMAKE_INSTALL_PREFIX and run cmake --build . --target install.
And please do not disable any winpr related stuff (that is your srgfault)

**Comment by akallabeth** [comment]
Or better, if you are familiar with rpm building, use `packaging/rpm/freerdp-nightly.spec` and just add the `-DWITH_SAMPLE=ON`  there and build.
It will install just like the nightly packages to `/opt/freerdp-nightly`.

**Comment by paulmorrisprodec** [comment]
@akallabeth - thanks for the info. I, like many others, would not have a compiler on a production machine. I'm actually building the binaries/libs on a build machine and then transferring the binaries/libs to the production machine. Though having the spec file is handy to build an RPM, I only need the sfreerdp binary and dependent libs (the target machine does not have X11 and does not need a full blown RDP client so the rest of the binaries are not required). I also only need to do this once to get a working version of sfreerdp and want to keep the libraries separate from live production ones. Handy to know that it is the winpr that causes the seg fault so I'll recompile with that switched on (I had to have the libwinpr shared lib anyway). I'll also detail the steps taken so that others can follow in my footsteps to get an authonly version working without X11.

**Comment by akallabeth** [comment]
@paulmorrisprodec ok, then you best add `-DWITH_WINPR_TOOLS=OFF -DWITH_WAYLAND=OFF -DWITH_CAIRO=OFF -DWITH_ALSA=OFF -DWITH_PULSE=OFF -DWITH_OSS=OFF -DWITH_FFMPEG=OFF -DWITH_GSTREAMER_1_0=OFF -DWITH_MANPAGES=OFF -DWITH_X11=OFF -DCHANNEL_TSMF=OFF -DWITH_SAMPLE=ON` 
The sample binaries you have to copy manually, we currently have no `CMake` installation set for those.

**Comment by paulmorrisprodec** [comment]
To follow in my footsteps (I'm using CentOS as a build machine):-

Do a minimal install
Transfer the makeit.txt file to the server to / directory
Run the following:-
cd /
mv makeit.txt makeit
chmod 755 makeit
./makeit
This script will create directories, yum the required packages, do a git clone, run cmake setting options for the make to work, runs make, and copies the sfreerdp binary and a cpio archive of the library files to /software/sfreerdp. If you need other libraries install these before running makeit.
Transfer the files in /software/sfreerdp to your target machine into a separate directory and then run:-
chmod 755 sfreerdp
cpio -ivdmu <./sfreerdp_libs.cpio

To run sfreerdp set the environment variable library path in your script/environment before running sfreerdp:-
export LD_LIBRARY_PATH=/<your_sfreerd_directory>:/lib64:/usr/lib64:$LD_LIBRARY_PATH

If the RDP works, the environment variable $? will be 0, if it failed $?>0

[makeit.txt](https://github.com/FreeRDP/FreeRDP/files/4219334/makeit.txt)

**Comment by akallabeth** [comment]
@paulmorrisprodec why that complicated? Just running `cmake --build . --target install` with a proper `CMAKE_INSTALL_PREFIX` set and you don´t need to copy anything.
Along with the arguments I mentioned before you might only need to remove the `include` folder that gets installed.
(btw, installing `ninja` build tool and running `cmake -GNinja ...` will speed up things a lot)

**Comment by akallabeth** [comment]
@paulmorrisprodec and that way you don´t need the `LD_LIBRARY_PATH` hack.

**Comment by akallabeth** [comment]
@paulmorrisprodec and as far as documentation goes, try to add specifics to https://github.com/FreeRDP/FreeRDP/wiki/Compilation ;)

**Comment by paulmorrisprodec** [comment]
@akallabeth I have a server called BUILD and a server called PRODUCTION. I build binaries using the server called BUILD and this can have compilers and is a scratch machine that gets trashed after building something as it will get very messy with lots of rubbish/failed compilations/installed tools/libs. The server PRODUCTION CANNOT have compilers/build tools/rubbish on it. Running the make on BUILD does not install the binaries onto the machine called PRODUCTION. Normally I would build an RPM on BUILD if there is a spec file and then transfer it to the machine PRODUCTION and install it (or if there is no spec file some other way). For this particular thing, I want to keep the libs well away from production ones as I'm hoping that once /authonly is added to master branch then I can make a proper RPM and install that onto PRODUCTION without affecting the sfreerdp build. I can then move things back over to xfreerdp in a controlled manner.... Very happy to help contributing in anyway in order to repay using the app so I'll have a go at adding it to the wiki...

**Comment by akallabeth** [comment]
@paulmorrisprodec you misunderstand the whole reason to use cmake install ;)
It will set the library paths up correctly so you just need to copy that from build to production and don't need any this and that with that ldlibrarypath...

**Comment by akallabeth** [comment]
And the patch has already been merged ;)

**Comment by paulmorrisprodec** [comment]
If you use LD_LIBRARY_PATH then you can put the libs wherever you wish (people might put them in other directories)...but I understand what you mean now!

So xfreerdp should be able to do /authonly? I'll recompile into a package if that is the case!

**Comment by akallabeth** [comment]
@paulmorrisprodec no, but current master has all stuff merged that you can add `-DWITH_SAMPLE=ON` to your rpm spec and have `sfreerdp` installed along with it.
