### ISSUE TITLE
Windows 10 - mf_init failure

### ISSUE THREAD

**Issue by michell-la** [FreeRDP/FreeRDP#5817]
Hi, i'm trying to use freeRDP on Window10 to connect to a Window2016 Terminal Server

I keep getting an error "mf_init" followed by a "Failed to create h264 codec context" message...

I have FreeRDP working on my Mac, but on Window10 machine...

Any thoughts? I'm using the nightly build

**Comment by akallabeth** [comment]
well, hard to tell if you don´t provide the information requested ;)

**Comment by akallabeth** [comment]
no feedback, closing.
Please use IRC or mailing list for questions.
