### ISSUE TITLE
FreeRDP not connecting to Win 10 virtualBox VM 

### ISSUE THREAD

**Issue by Blastertoad** [FreeRDP/FreeRDP#5820]
I have been trying unsuccessfully for a few days to get FreeRDP to connect to a Win 10 VM. I can get a connection via Rdesktop and Windows remote desktop tool however FreeRDP continues to give the following output:
`[ERROR][com.freerdp.core.transport] - BIO_should_retry returned a system error 32: Broken pipe
[ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]
[ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure`

Our setup:
Host: Ubuntu Server LTS 18.04 running VirtualBox VMs guest system Windows 10 Pro
Client: Zero clients using OpenThinClient os pxe booted from Ubuntu server.
FreeRDP 2.0.0-dev5 (3aa6047b3) as included in OpenThinClient server package 2019.1.3.

On the VM side:
VirtualBox VMs set up with individual ports for rdp. Each instance has static ip being enforced by router to VM's MAC address.
Windows 10 Pro configured for RDP with admin user and secondary remote login user profile.
Windows firewall currently disabled during testing.

RDP connection is over LAN, no external access.

Troubleshooting steps:
Attempted FreeRDP connection with auto negotiated security as well as manually setting TLS, nla, and RDP. 
Have disabled nla requirement on windows VM.
In VirtualBox tried both null and guest options for RDP security.
Connection attempts have all been made using ip and port, no host name.
Tried connecting with '-sec-nla' arguments.

Just to reiterate, I can connect with no issues from a windows machine using default RDP client and from OpenThinClient os Rdesktop client. Server and VMs are all fresh os installs setup new in the last month.

**Comment by akallabeth** [comment]
@Blastertoad Can you give some details on connection parameters (command line)? Sounds like some mode is required but not enabled. (buildconfig would also be nice, don´t know the build options used with openthinclient)

**Comment by Blastertoad** [comment]
@akallabeth OpenThinClient handles configuration in a web manager ui. The zero client os runs a script that queries the config and parses arguments to run command. At least this is what I am gathering from looking at the script file. An option to run the script in debug is provided and this is the output I get
`> /opt/freerdp-git/tcos/launcher 'Windows test - FreeRDP' w

11:58:55.960 /opt/freerdp-git/tcos/launcher:305 [DEBUG] Setting color depth
(auto detection): 24

11:58:56.511 /opt/freerdp-git/tcos/launcher:694 [DEBUG] Not activating usbrdr
VC (usbsrvd is not running).

11:58:56.514 /opt/freerdp-git/tcos/launcher:702 (DEBUG] CMD: LD_LIBRARY_PATH=/opt/freerdp-nightly/lib/freerdp2/philips/libUsr:/opt/freerdp-nightly/lib:${LD_LIBRARY_PATH} /opt/freerdp-nightly/bin/xfreerdp /bpp
:24 /kbd:0x00000409 "/drive:media,/media" -clipboard +wallpaper +themes +fonts -aero -windows-drag +menu-anims -encription -compression async-update /rfx /gfx:avc444 +gfx-thin-client -decorations /f /multimon:force /d;" /port:4750 /v:MY-IP /u:MY-USR /p:MY-PSWD /cert-ignore

11:58:56.794 /opt/freerdp-git/tcos/launcher:713 [DEBUG] xfeerdp pid: 2280

11:58:57.454 lopt/freerdp git/tcos/launcher:736 [DEBUG] EXIT CODE: 133

11:58:57.455 fopt/freerdp git/tcos/launcher:7737 DEBUG] STDOUT:<<<

[11:58:56:584] [2280:2281] [INFO][Com.freerdp.client.common.cmdline] - loading
channelEx rdpdr

[11:58:56:584] [2280:2281] [INFO][com.freerdp.client.common.cmdline] - loading
channelEx rdpsnd

[11:58:56:584] [2280:2281] [INFO][com.freerdp.client.common.cmdline] - loading
channelEx drdynvc

[11: 58: 57: 130] [2280: 2281] [INFO] [com.freerdp.primitives] - Primitives
autodetect, using generic

[11:58:57:142] [2280:2281] [INFO][com.freenrdp.core]- freerdp_set_last_error
resetting error state

[11:58:57:142] [2280:2281] [INFO][com.freerdp.core] - freerdp_set_last_error
resetting error state

>>>

11:58:57.455 /opt/freerdp-git/tcos/launcher:738 [DEBUG] STDERR:<<<<

[11:58:57:142] [2280:2281] [ERROR][com.freerdp.core.transport] -
BIO_should_retry returned a system error 32: Broken pipe

[11:58:57:143] [2280:2281] [ERROR][com.freerdp.core.nego] - Protocol Security
Negotiation Failure

[11:58:57:143] [2280:2281] [ERROR][Com.freerdp.core] - freerdp_set_last_error
ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED [0x0002000C]

[11:58:57:143] [2280:2281] [ERROR][com.freerdp.core.connection] - Error:
protocol security negotiation or connection failure

>>>

11:58:57.456 /opt/freerdp-git/tcos/launcher:748 [ERROR] Error Code: 133, Error
Nane: unknown`

Please forgive small errors as this output has been captured by a camera and passed through ocr. Of course I removed username, password and ip

**Comment by akallabeth** [comment]
@Blastertoad thx for the log. All there that might help. Nothing unusual at first sight, so would be interesting if it works from a normal system with our nightly builds (just want to rule out some build/config issue)

**Comment by Blastertoad** [comment]
I downloaded pre-built windows client as linked here: https://ci.freerdp.com/job/freerdp-nightly-windows/

I get the following output:

wfreerdp.exe /u:MY-USR /p:MY-PSWD /v:MY-IP /port:4750

C:\Users\Jaden>[09:42:52:727] [5332:00002934] [INFO][com.freerdp.client.windows]
 - Debug console created.
[09:42:52:729] [5332:00002010] [INFO][com.freerdp.core] - freerdp_connect:freerd
p_set_last_error_ex resetting error state
[09:42:52:729] [5332:00002010] [INFO][com.freerdp.client.common.cmdline] - loadi
ng channelEx rdpdr
[09:42:52:730] [5332:00002010] [INFO][com.freerdp.client.common.cmdline] - loadi
ng channelEx rdpsnd
[09:42:52:731] [5332:00002010] [INFO][com.freerdp.client.common.cmdline] - loadi
ng channelEx cliprdr
[09:42:52:829] [5332:00002010] [INFO][com.freerdp.primitives] - primitives autod
etect, using generic
[09:42:52:837] [5332:00002010] [INFO][com.freerdp.core] - freerdp_tcp_is_hostnam
e_resolvable:freerdp_set_last_error_ex resetting error state
[09:42:52:838] [5332:00002010] [INFO][com.freerdp.core] - freerdp_tcp_connect:fr
eerdp_set_last_error_ex resetting error state
[09:42:53:840] [5332:00002010] [ERROR][com.freerdp.core.transport] - BIO_should_
retry returned a system error 0: No error
[09:42:53:840] [5332:00002010] [ERROR][com.freerdp.core] - transport_write:freer
dp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[09:42:53:851] [5332:00002010] [INFO][com.freerdp.core] - freerdp_tcp_is_hostnam
e_resolvable:freerdp_set_last_error_ex resetting error state
[09:42:53:851] [5332:00002010] [INFO][com.freerdp.core] - freerdp_tcp_connect:fr
eerdp_set_last_error_ex resetting error state
[09:42:54:853] [5332:00002010] [ERROR][com.freerdp.core.transport] - BIO_should_
retry returned a system error 0: No error
[09:42:54:853] [5332:00002010] [ERROR][com.freerdp.core] - transport_write:freer
dp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[09:42:54:854] [5332:00002010] [ERROR][com.freerdp.core] - freerdp_post_connect
failed

**Comment by Blastertoad** [comment]
@akallabeth Following further testing I accidentally skipped inputting the port argument. Without the port the connection is established fine. I confirmed the port I previously specified (4750) is the correct port as set up in VirtualBox and is what I am using in the currently working Rdesktop configuration. I am glad to have this working but am wondering why specifying the port ends in failure over lan with VirtualBox VMs. Any thoughts?

**Comment by akallabeth** [comment]
@Blastertoad well, no idea, really. maybe some redirection you set up? I mean if you skip the port argument, then `3389` is used...

**Comment by akallabeth** [comment]
Assuming this was a configuration issue as local debian test machine is working.
Closing, reopen or recreate if not resolved.
