### ISSUE TITLE
[GFX] planar codec chroma subsampling not implemented

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#5822]
Reported via IRC by `suikka`:
```
Hello everyone, I came here to ask help with my possible freerdp problem.. Im using 18.04 ubuntu with latest update.  freerds is from here: http://ppa.launchpad.net/sipe-collab/ppa/ubuntu/ .. my problem is with pidgin using sipe. I can share my desktop to others but I cannot see others shared dekstop (Im using remmina). The error Im getting is
this:
[ERROR][com.freerdp.codec] - Chroma subsampling unimplemented
[ERROR][com.freerdp.core.fastpath] - Fastpath update Bitmap [1] failed, status 0
[ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data: fastpath_recv_update() - -1
[ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() failed
[ERROR][com.freerdp.core.transport] -
transport_check_fds: transport->ReceiveCallback() - -3
[ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
```

progressive decoder currently aborts when chroma subsampling is required as it is not implemented.

**Comment by suikula** [comment]
Hello, 

I'm the original reporter of this issue and I'm still waiting for somekind of feedback/resolution for this.
I have tried with pidgin from official ubuntu repos and pidgin from sipe collab https://launchpad.net/~sipe-collab. Also tried with remmina-ppa-team-ubuntu-freerdp-daily-bionic and remmina-ppa-team-ubuntu-remmina-next-bionic but haven't solve this problem.

I have tried all the possible settings on remmina including all color depths, security, gateway transport types, with/without glyph cache and relax order checks. Everytime I got this same error.

This use to work but not working anymore and I don't know exact time when this stopped working, but I think this started about 2-3 weeks ago. My ubuntu (18.04) has latest updates.

**Comment by akallabeth** [comment]
@suikula depending on your build it may be possible to use `RFX` or other `GFX` modes, which use some newer (and less exotic options) as codecs.
May I ask what the server software is in this case?

**Comment by akallabeth** [comment]
@suikula the reason for this error not being detected by anyone else is that in your case `[MS-RDPBCGR] 2.2.7.1.2 Bitmap Capability Set (TS_BITMAP_CAPABILITYSET)` flag `DRAW_ALLOW_COLOR_SUBSAMPLING` is ignored by the server. (it is deactivated in freerdp)

**Comment by suikula** [comment]
Thank you for replying..
https://launchpad.net/~sipe-collab/+archive/ubuntu/ppa?field.series_filter=bionic 

$ dpkg --list | grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp | awk '/^ii/{print $2,$3}'

freerdp2-x11 2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1
gstreamer1.0-nice:amd64 0.1.15+sipe-1+201812302006~ubuntu18.04.1
libfarstream-0.2-5:amd64 0.2.8+sipe+collab-1+201812302234~ubuntu18.04.1
libfreerdp-client2-2:amd64 2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1
libfreerdp-server2-2:amd64 2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1
libfreerdp-shadow-subsystem2-2:amd64 2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1
libfreerdp-shadow2-2:amd64 2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1
libfreerdp2-2:amd64 2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1
libnice10:amd64 0.1.15+sipe-1+201812302006~ubuntu18.04.1
libwinpr-tools2-2:amd64 2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1
libwinpr2-2:amd64 2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1
pidgin 1:2.12.0-1ubuntu4
pidgin-data 1:2.12.0-1ubuntu4
pidgin-libnotify 0.14-9ubuntu2
pidgin-sipe 1.24.0+sipe-0+201812302131~ubuntu18.04.1
remmina 1.3.10+ppa202001081611.r855d285.d7af32e7~ubuntu18.04.1
remmina-common 1.3.10+ppa202001081611.r855d285.d7af32e7~ubuntu18.04.1
remmina-plugin-rdp:amd64 1.3.10+ppa202001081611.r855d285.d7af32e7~ubuntu18.04.1
remmina-plugin-secret:amd64 1.3.10+ppa202001081611.r855d285.d7af32e7~ubuntu18.04.1
remmina-plugin-spice:amd64 1.3.10+ppa202001081611.r855d285.d7af32e7~ubuntu18.04.1
remmina-plugin-vnc:amd64 1.3.10+ppa202001081611.r855d285.d7af32e7~ubuntu18.04.1

Hopefully this helps out.

**Comment by akallabeth** [comment]
@suikula yes, but if I don´t misunderstand then `Remmina` and `sipe` are the client side software here connecting to some server.
Which server that is would be of interest.

**Comment by suikula** [comment]
Oh, yes, sorry I missunderstood. I'm using this setup on my work environment any my employer is using Office 365/Lync.

**Comment by akallabeth** [comment]
@suikula and for testing purposes, you could comment out
```
if (cs)
		{
			WLog_ERR(TAG, "Chroma subsampling unimplemented");
			return FALSE;
		}
```
in `planar_decompress` and see if it works (graphics might look a bit greasy, the algorithm is still not implemented)

**Comment by suikula** [comment]
Im trying to follow these compilation guidelines but I'm having this problem when I try to install dependencies:
The following packages have unmet dependencies:
 libpulse-dev : Depends: libpulse0 (= 1:11.1-1ubuntu7.4) but 1:11.1-1ubuntu7.5 is to be installed
                Depends: libpulse-mainloop-glib0 (= 1:11.1-1ubuntu7.4) but 1:11.1-1ubuntu7.5 is to be installed
E: Unable to correct problems, you have held broken packages.

I'm not able to compile the freerdp at the moment.

**Comment by suikula** [comment]
Is there any other way to test this out ?

**Comment by akallabeth** [comment]
@suikula sorry, no. you can only find out why the server is sending buggy data (yes, you read correct ^^)
we already announce we do not support that feature but the server is ignoring that :/

**Comment by suikula** [comment]
Ok, Im progressing little bit.. 
I used this command to create makefile:
cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=OFF -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON -DWITH_OSS=OFF .

 -DWITH_PULSE=OFF  will get rid of the problem with libpulse-dev dependency problem.. let see where this will ends up.

**Comment by suikula** [comment]
```
$ which xfreerdp
/usr/local/bin/xfreerdp
```

```
$ xfreerdp /buildconfig
This is FreeRDP version 2.0.0-dev5 (15909af76)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 7.4.0
Target architecture: x64

```
I commented the lines you mentioned:
```
/*if (cs)
                {
                        WLog_ERR(TAG, "Chroma subsampling unimplemented");
                        return FALSE;
                } */

```


Now I tried to open desktop share with pidgin and I end up with the same error:
```

(org.remmina.Remmina:10635): GLib-CRITICAL **: 12:54:19.796: g_str_has_prefix: assertion 'str != NULL' failed
[12:54:19:890] [10635:11094] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[12:54:19:890] [10635:11094] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[12:54:19:890] [10635:11094] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[12:54:19:890] [10635:11094] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[12:54:19:890] [10635:11094] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[12:54:19:890] [10635:11094] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[12:54:19:890] [10635:11094] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[12:54:20:210] [10635:11094] [WARN][com.freerdp.core.gcc] - Server uses non-advertised encryption method 0x00000000
[12:54:21:777] [10635:11094] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[12:54:21:777] [10635:11094] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[12:54:21:777] [10635:11094] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
[12:54:21:777] [10635:11094] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
[12:54:22:265] [10635:11094] [ERROR][com.freerdp.codec] - Chroma subsampling unimplemented
[12:54:22:265] [10635:11094] [ERROR][com.freerdp.core.fastpath] - Fastpath update Bitmap [1] failed, status 0
[12:54:22:265] [10635:11094] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data: fastpath_recv_update() - -1
[12:54:22:265] [10635:11094] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[12:54:22:265] [10635:11094] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
[12:54:22:265] [10635:11094] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
Could not check FreeRDP file descriptor

```

**Comment by suikula** [comment]
I even made symlink from /usr/local/bin/xfreerdp to /usr/bin/xfreerdp so that nothing can use the original binary, but still I get the same result.

**Comment by akallabeth** [comment]
@suikula looks like you are not using `xfreerdp` but only the `libfreerdp` `so` files. check if they are linked as well.
Additionally I´ve created #5835 to fix 50% of the subsampling thing missing

**Comment by suikula** [comment]
I manged to change my setup so that this is where I'm at the moment:

```
(remmina:21942): GLib-CRITICAL **: 13:24:02.377: g_str_has_prefix: assertion 'str != NULL' failed
[13:24:02:475] [21942:21966] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[13:24:02:808] [21942:21966] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[13:24:02:809] [21942:21966] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[13:24:02:809] [21942:21966] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[13:24:02:809] [21942:21966] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[13:24:02:809] [21942:21966] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[13:24:02:814] [21942:21966] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[13:24:02:814] [21942:21966] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[13:24:03:151] [21942:21966] [WARN][com.freerdp.core.gcc] - Server uses non-advertised encryption method 0x00000000
[13:24:04:465] [21942:21966] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRA32
[13:24:04:465] [21942:21966] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[13:24:04:466] [21942:21966] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
[13:24:04:466] [21942:21966] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
[13:24:04:891] [21942:21966] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -4
[13:24:04:891] [21942:21966] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
```

**Comment by akallabeth** [comment]
@suikula Ok, i´ve checked, they are calling the binary directly.
Maybe it is a good idea to replace `/usr/bin/xfreerdp` with a shell script that
1. Logs each call to a file with all arguments
1. Adds some connection flags so you can try around a bit with different options (`/gfx, /rfx, /network:auto` come to mind)

**Comment by suikula** [comment]
Do  you happen to have any examples on your mind for the script ?
My mind is not capable to come up with that kinda script. thanks

**Comment by akallabeth** [comment]
Well, something in the way of
```
#!/bin/bash
echo "sipe called with $@" >/tmp/sipe.log
/path/to/your/install/xfreerdp $@ /gfx
```

the `/gfx` is just as an example for additional arguments you can try

**Comment by akallabeth** [comment]
don´t forget a `chmod +x` ;)

**Comment by suikula** [comment]
thanks

**Comment by suikula** [comment]
I must thank you at this point already. You have been super patient.

I totally get what you are trying to achieve here, but for some weird reason I cannot understand what pidgin/sipe is calling (xfreerdp). I have made scripts as you helped out to /usr/bin/xfreerdp and /usr/local/bin/xfreerdp - both are calling actual xfreerdp script but looks like pidgin/sipe never calls those scripts and I cannot understand why or what it is calling.

Im baffled at the moment. Looks like pidgin is calling something very distinct freerdp (which is not in path /usr/bin/xfreerdp or /usr/local/bin/xfreerdp). Is this even possible ?

**Comment by suikula** [comment]
`$ which xfreerdp`


`$ xfreerdp
-su: /usr/local/bin/xfreerdp: No such file or directory`

but when trying to open shared presentation from pidgin I get:
```
(remmina:3570): GLib-CRITICAL **: 14:36:19.133: g_str_has_prefix: assertion 'str != NULL' failed
[14:36:19:261] [3570:4414] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[14:36:19:261] [3570:4414] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[14:36:19:261] [3570:4414] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[14:36:19:261] [3570:4414] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[14:36:19:261] [3570:4414] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[14:36:19:265] [3570:4414] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[14:36:19:265] [3570:4414] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[14:36:19:595] [3570:4414] [WARN][com.freerdp.core.gcc] - Server uses non-advertised encryption method 0x00000000
[14:36:20:961] [3570:4414] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRA32
[14:36:20:961] [3570:4414] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[14:36:20:961] [3570:4414] [INFO][com.freerdp.channels.rdpsnd.client] - Loaded fake backend for rdpsnd
[14:36:20:961] [3570:4414] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
[14:36:21:271] [3570:4414] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -4
[14:36:21:271] [3570:4414] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
Failed to check FreeRDP event handles
```


If I remove both xfreerdp scripts I still get very same error. lol

**Comment by akallabeth** [comment]
@suikula which remmina do you use? they usually ship their own build of freerdp

**Comment by suikula** [comment]
At the moment Im using the remmina which comes from the sipe-collab repo.
http://ppa.launchpad.net/sipe-collab/ppa/ubuntu/pool/main/r/remmina/
I have tried out the one from here
https://launchpad.net/~remmina-ppa-team/+archive/ubuntu/freerdp-daily
but no changes in end result.

`$ dpkg -l | grep -e remmina

ii  freerdp2-x11                                    2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1 amd64        RDP client for Windows Terminal Services (X11 client)
ii  libfreerdp-client2-2:amd64                      2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-server2-2:amd64                      2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow-subsystem2-2:amd64            2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1 amd64        FreeRDP Remote Desktop Protocol shadow subsystem libraries
ii  libfreerdp-shadow2-2:amd64                      2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp2-2:amd64                             2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libwinpr-tools2-2:amd64                         2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1 amd64        Windows Portable Runtime Tools library
ii  libwinpr2-2:amd64                               2.0.0~git202001131441-0+remmina202001131518.r326a448.d287a1e7~ubuntu18.04.1 amd64        Windows Portable Runtime library
ii  remmina                                         1.2.0-rcgit.29+dfsg-1ubuntu1                                                amd64        GTK+ Remote Desktop Client
ii  remmina-common                                  1.2.0-rcgit.29+dfsg-1ubuntu1                                                all          Common files for Remmina
ii  remmina-plugin-rdp:amd64                        1.2.0-rcgit.29+dfsg-1ubuntu1                                                amd64        RDP plugin for Remmina
ii  remmina-plugin-secret:amd64                     1.2.0-rcgit.29+dfsg-1ubuntu1                                                amd64        Secret plugin for Remmina
ii  remmina-plugin-spice:amd64                      1.2.0-rcgit.29+dfsg-1ubuntu1                                                amd64        Spice plugin for Remmina
ii  remmina-plugin-vnc:amd64                        1.2.0-rcgit.29+dfsg-1ubuntu1                                                amd64        VNC plugin for Remmina
`

**Comment by akallabeth** [comment]
@suikula ok, so sipe is using remmina to launch instead of freerdp. and remmina has their own freerdp.

**Comment by akallabeth** [comment]
@suikula ok, I´ve fixed `planar` codec with #5835 now completely

**Comment by suikula** [comment]
> @suikula ok, so sipe is using remmina to launch instead of freerdp. and remmina has their own freerdp.

This is absolutely true.

**Comment by suikula** [comment]
> @suikula ok, I´ve fixed `planar` codec with #5835 now completely

I'm sorry, but what does this actually mean? Is this problem somehow now gone? Does this affect to my problem somehow ?

**Comment by akallabeth** [comment]
@suikula well, it fixes the error you reported with your first log.
If it fixes everything I don't know.

**Comment by suikula** [comment]
So, now remmina has to implement this patch to their code too to fix this in my case.

**Comment by antenore** [comment]
@suikula the remmina version you're referring to is ancient. As soon as the fix will be merged, you'll have to update both Remmina and FreeRDP. As of now, the latest remmina is v1.3.10 and the one available when FreeRDP will #5835, will be probably 1.4.0

**Comment by antenore** [comment]
@suikula note that for this particular fix, we have nothing to implement in the Remmina code.

The only thing you need is a recent Remmina, built against the FreeRDP codebase that implement that fix

**Comment by antenore** [comment]
Reading better the code I see that probably we will have to implement that enhancement as well, but yet @suikula you must get rid of Remmina rcgit29

**Comment by suikula** [comment]
@antenore thank you for clearing this out. Im using latest remmina at the moment, but I need to wait for https://github.com/FreeRDP/FreeRDP/pull/5835 to be available and compile freerdp and remmina. Hopefully this will fix this issue. Of course I would like to see these fixes impelemented in ppa packages but this will take some time.. thank again.

**Comment by antenore** [comment]
@suikula we have the remmina-next-daily PPA that is built against the latest master of both remmina and freerdp ;-)

Still, we will have to add some FreeRDP parameters to make this working

**Comment by akallabeth** [comment]
@antenore are you sure? this should be automatically working if you use `freerdp_settings_new`

**Comment by antenore** [comment]
@akallabeth honestly not sure. I'll check
I don't think we are using ´freerdp_settings_new´

**Comment by antenore** [comment]
@akallabeth ah, if we are using a recent FreeRDP, we are using`freerdp_settings_new`

So it's just a matter of waiting for the merge, thanks!!!

**Comment by suikula** [comment]
> @suikula we have the remmina-next-daily PPA that is built against the latest master of both remmina and freerdp ;-)
> 
> Still, we will have to add some FreeRDP parameters to make this working

ok, well I have this in use already. Hopefully merge will happen soon.

**Comment by akallabeth** [comment]
@suikula next nightly ;)

**Comment by suikula** [comment]
Hello guys, should I be able to test now with latest packages from remmina-next-daily ? And not only test but can I expect different end results than yesterday ?

**Comment by suikula** [comment]
Well, I just tested and looks like it is working. Colours are little bit funky as you @akallabeth expected but I don't care at this point. Thank you very much guys for help and patience.

**Comment by akallabeth** [comment]
@suikula if you don´t mind, a screenshot would be appreciated to check which color stuff is not working on your side.

**Comment by suikula** [comment]
No, I don't mind.. You guys helped so much with my problem.

Actually I just tried and looks like all the color which was somehow funky yesterday is ok at the moment.  Don't know why, I haven't change the setting in any way.

Here is screenshot of shared screen:
![zabbix](https://user-images.githubusercontent.com/34090397/72601872-f0cd2600-391e-11ea-8229-4fe17c69ee7a.png)

and here is screenshot of same window from my own pc:
![zabbix-oma](https://user-images.githubusercontent.com/34090397/72601875-f165bc80-391e-11ea-93b9-bbaa51dec913.png)

There is not issues (other than my theme is dark and on the other theme is light).
Don't know what happened, but looks good now.

**Comment by akallabeth** [comment]
@suikula ok, thank you.
that is related to rdp and how windows handles theming for remote desktop.
I´ve fixed the remaining color conversion issues with YCoCg before the pull was merged, therefore I was curious.

**Comment by suikula** [comment]
Don't know what was happening yesterday. I was in fact seeing this exact and very same window yesterday during meeting and colors were off.. The green showing on these screenshots had more orange/yellow hue on them, but everything looks fine and dandy now.

**Comment by suikula** [comment]
@akallabeth, Im at the meeting again and here is screenhots of the funky colors.

First one is from my own screen and this is the way the colors should be:
![screenshot2](https://user-images.githubusercontent.com/34090397/72718692-1b1d1e80-3b7f-11ea-90b9-d35ea731b0e0.png)

second one is from the shared screen:
![screenshot1](https://user-images.githubusercontent.com/34090397/72718694-1b1d1e80-3b7f-11ea-919e-f5fbacf88c29.png)

I did not change any settings and I haven't even booted my computer between last meeting and this meeting.
