### ISSUE TITLE
xscreensaver causes FreeRDP window to permanently grab keyboard

### ISSUE THREAD

**Issue by elitak** [FreeRDP/FreeRDP#5826]
When I have a FreeRDP session in focus in xmonad, and xscreensaver locks my screen, after unlocking the screen, my keyboard no longer works, neither in the remote session nor locally, until I use the mouse to disconnect from the remote session. When the FreeRDP window is out of focus and xscreensaver locks the screen, this is not a problem.

OS: NixOS
xmonad 0.15
FreeRDP 2.0.0-rc4
xscreensaver 5.43
xmobar 0.32

**Comment by akallabeth** [comment]
Could not reproduce.
1. Tested withh gnome, xfce4, openbox and kde plasma on my test machines.
1. Mouse focus in and out of `xfreerdp`
1. Keyboard working immediately.
1. Tested with `debian 10`, `fedora 31` (sorry, don´t have yours ;))

Please add additional information to get this issue reopened.
