### ISSUE TITLE
code error in the function libavcodec_get_format 

### ISSUE THREAD

**Issue by jingshaoqi** [FreeRDP/FreeRDP#5839]
in founction  libavcodec_get_format of file h264_ffmpeg.c
H264_CONTEXT_LIBAVCODEC* sys = (H264_CONTEXT_LIBAVCODEC*)h264->subsystem;
should be changed to 
H264_CONTEXT_LIBAVCODEC* sys = (H264_CONTEXT_LIBAVCODEC*)h264->pSystemData;

**Comment by akallabeth** [comment]
@jingshaoqi nice catch, thank you
