### ISSUE TITLE
Graphical Artifacts with xfreerdp

### ISSUE THREAD

**Issue by qcguytech** [FreeRDP/FreeRDP#584]
Many of my tests users are reporting different level of graphicals artifacts when working with differents softwares.

My command line is:

xfreerdp -d domain.local -f -k 0x00001009 -u USERNAME -p PASSWORD -x m --ignore-certificate --gdi hw --no-bmp-cache ts.domain.local

I can't use --gdi sw or remove --no-bmp-cache

If you need a screenshot I will do ASAP

**Comment by akallabeth** [comment]
Closing due to being ancient. If you encounter this issue with current builds feel free to reopen.
