### ISSUE TITLE
Some inverted color while dumping image in PNG format

### ISSUE THREAD

**Issue by dashingvik** [FreeRDP/FreeRDP#5845]
I am using **proxy server** with capture session set to "ON".
In pf_capture.c under _pf_capture_save_frame(...)_, we have _winpr_bitmap_write(...)_ which saves the captured bytes in BMP. Single image takes memory upto 5MB which is too heavy hence I am using _lodepng_encode_memory(...)_ which saves the image in PNG but with some distorted color as follows :

![101](https://user-images.githubusercontent.com/56148491/72593242-83bf8d80-392a-11ea-9ccd-9f9419a5db3f.png)

I have checked all values of struct LodePNGColorType against with all possible bitdepth values (2,4,8,16,32) but i am not able to capture actual image.

**Comment by akallabeth** [comment]
@dashingvik please use mailing list or IRC for support.
This looks like you have a RGB/BGR kind of issue.

**Comment by dashingvik** [comment]
@akallabeth Can you guide me to mailing list or IRC for support ? Also I have tried with BGR format but results were same.
