### ISSUE TITLE
proxy default config.ini incompatible

### ISSUE THREAD

**Issue by cocoon** [FreeRDP/FreeRDP#5848]
**Describe the bug**
This change to not compile demo modules for the proxy causes the current default config.ini to cause an error:
https://github.com/FreeRDP/FreeRDP/commit/e3728c1822f041f9d8725afae93b481dcd491155

Error caused by Required Plugin statement:
https://github.com/FreeRDP/FreeRDP/blob/master/server/proxy/config.ini#L44

**To Reproduce**
1. compile with:
`cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON -DWITH_SERVER=on`
2. start freerdp-proxy
3. See error:
```
[12:51:43:891] [48322:48322] [ERROR][proxy.modules] - FindFirstFile failed!
[12:51:43:891] [48322:48322] [ERROR][proxy.server] - failed to initialize proxy plugins!
```

**Expected behavior**
freerdp-proxy should be able to start with default config.ini

** Application details
* Version of FreeRDP
`git log
commit 706e32982ecafce069d34c8b2015caac0bb3038d (HEAD -> master, origin/master, origin/HEAD)
`

* Command line used

* output of `/buildconfig`
`xfreerdp /buildconfig
[12:48:30:508] [48299:48299] [ERROR][com.freerdp.client.x11] - failed to open display:
[12:48:30:508] [48299:48299] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.
`

**Desktop (please complete the following information):**
 - OS: 
`.4.0-9-generic #12-Ubuntu SMP Mon Dec 16 22:34:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu Focal Fossa (development branch)"
`

**Comment by kubistika** [comment]
It is caused because the directory does not exists. I’ll upload a patch tomorrow, thanks

**Comment by cocoon** [comment]
Hi thanks for the quick fix.

I have one more, I compiled it now with "-DWITH_PROXY_MODULES=ON"

but commented the Demoplugin line in the config, but it is still oading the demo module.

 

Cheers

 

Gesendet: Montag, 20. Januar 2020 um 21:09 Uhr
Von: "Kobi" <notifications@github.com>
An: FreeRDP/FreeRDP <FreeRDP@noreply.github.com>
Cc: cocoon <cocoon@wolke7.net>, Author <author@noreply.github.com>
Betreff: Re: [FreeRDP/FreeRDP] proxy default config.ini incompatible (#5848)


It is caused because the directory does not exists. I’ll upload a patch tomorrow, thanks

**Comment by kubistika** [comment]
This is the expected behaviour. The proxy loads all modules under the modules directory.
The required plugins, as written in the comment, is used to make sure that the proxy won't start if it doesn't have specific modules loaded.

**Comment by kubistika** [comment]
@cocoon just from interest, may I ask which scenarios you're using the proxy for?
And regarding that problem, I'll think about it. Maybe adding a cli flag to override the default plugins dir will be enough.

**Comment by cocoon** [comment]
Sure. 
I would want to use it as a gateway into different lab environments that will be started from an web interface. So I want to have multiple individual processes that I can monitor and use multiple cpu cores.

Currently I use neutrinordp for it and have it compiled multiple times with different fixed config dirs.
So this is a bit of a pain that would be greatly reduced if I only need one compiled freerdp-proxy and can use it with multiple different configurations.

Additionally I monitor each instance using fireqos and netdata, have written an won restapi that I trigger using my web portal to start, stop and write configurations, using cron to automatically stop everything at the end of a week. That is a brief overview of my setup.

**Comment by kubistika** [comment]
@cocoon like https://guacamole.apache.org/ ?
And, will it be okay if we'll add an option to override the plugins dir in cli? for Example, freerdp-proxy /config:config.ini /plugins-dir:plugins2

**Comment by cocoon** [comment]
yes similar to guacamole.

The only downside with using the cli option is, that one would need to "copy" multiple times the plugins if only some of them would be used.

To only use one copy of files would be able if you can configure in the ini file what plugin(s) to use from one single directory.

**Comment by kubistika** [comment]
@cocoon #5853 now you'll be able to specify which modules to load in config.

**Comment by cocoon** [comment]
Impressive, you are on fire! Thanks!
