### ISSUE TITLE
server: proxy: Proxy visibly drops video frames

### ISSUE THREAD

**Issue by inverse-t** [FreeRDP/FreeRDP#5860]
Hi,

We build a smalle eval environment.
Windows 10 machine <-> amd64 Ubuntu 19.10 with FreeRdp Proxy <-> amd64 Ubuntu 19.10 with FreeRdp Client
As a side by side comparison we have a clone of this setup without the proxy. We play a test video on the win 10 host in fullscreen. The video renders @~30hz.

client cli: 
./xfreerdp /v:xxx.xxx.xxx.xxx /u:xxx /p:xxx /gfx-h264:AVC444 /network:lan /w:2560 /h:1440

The connection that utilizes the proxy visible drops several frames per second in comparison to the direct connection.

Additionally we monitored the proxy with iftop: It's noteworthy that the proxy receives more data from the win10 machine, than it sends out to the client. For ~8Mb incoming we have ~7.5Mb outgoing, so half a Mb in data lost - which would explain the frame drops?
***Edit this is wrong information, the outgoing data-rate is 0.5Mb higher than the incoming.**

We also replaced the proxy with a debian 10 machine and got the same results. It's also independent of the proxy host being virtualized or not.

This seems to be visibly noteworthy for resolutions > HD. We tested with 2560x1440.

the built is done with git master commit: 706e32982ecafce069d34c8b2015caac0bb3038d

proxy built with: cmake -DWITH_SERVER=ON -DWITH_PROXY_MODULES=ON -DCMAKE_BUILD_TYPE=Release

client built with: cmake -DWITH_CHANNELS=ON -DWITH_LIBSYSTEMD=ON -DWITH_FFMPEG=ON -DWITH_JPEG=ON -DCMAKE_BUILD_TYPE=Release

config.ini: 
[Server]
Host = xxx.xxx.xxx.xxx
Port = 3389

[SessionCapture]
Enabled = FALSE
CapturesDirectory = "captures"

[Target]
UseLoadBalanceInfo = FALSE
Host = xxx.xxx.xxx.xxx
Port = 3389

[Input]
Mouse = TRUE
Keyboard = TRUE

[Security]
ServerTlsSecurity = TRUE
ServerRdpSecurity = FALSE
ClientTlsSecurity = TRUE
ClientRdpSecurity = FALSE
ClientNlaSecurity = TRUE
ClientAllowFallbackToTls = TRUE

[Channels]
GFX = TRUE
DisplayControl = TRUE
Clipboard = FALSE
AudioOutput = TRUE
RemoteApp = TRUE

[Clipboard]
TextOnly = FALSE
MaxTextLength = 10 # 0 for no limit.

[Plugins]

**Comment by inverse-t** [comment]
Update: 
The measurement of the incoming/outgoing datarate of the proxy a mistake, the data sent to the client is half a Mb higher then received by the server.

Additionally:
The connection for the direct client is ~16Mb incoming, whereas the connection via the proxy is @~7.5Mb incoming on the proxy. Tried the /network:lan and /network:auto functions but this changed nothing:

why does the proxy have so much lower packet rate?

Can anyone explain how rdp establishes the datarate if NetworkAutoDetect=FALSE?

**Comment by kubistika** [comment]
First of all, please make sure that the statistics are correct because it is very hard to debug it. How are you measuring it? The proxy incoming is 7.5Mb? or the "real client" receives from the proxy 7.5Mb? Who gets 16Mb? Quite hard to understand. I measured it using tcpdump on the client both with direct/proxy connections and it was the same rate.

Please also note that the proxy does not support some things that are supported when you're connecting directly using mstsc (for example, **udp transport**, gdi orders, etc.), so that might be a reason for the video/packet rate to be lower.

**Comment by inverse-t** [comment]
@kubistika sorry for the confusion.

It turns out the issue was not with freerdp, but with the windows machines. One of the was configured wrong and therefore did not generate the desired framerate.
