### ISSUE TITLE
return code testing is at the wrong place

### ISSUE THREAD

**Issue by qunying** [FreeRDP/FreeRDP#5864]
In libfreerdp/core/nla.c, line 657~667
```
		if (SecIsValidHandle(&nla->credentials))
		{
			nla->table->FreeCredentialsHandle(&nla->credentials);
			SecInvalidateHandle(&nla->credentials);
		}

		if (nla->status != SEC_E_OK)
		{
			WLog_ERR(TAG, "FreeCredentialsHandle status %s [0x%08" PRIX32 "]",
			         GetSecurityStatusString(nla->status), nla->status);
		}
```
nla->status is not update by calling of FreeCredentialsHandle(), I thinks it should be:
```
                if (SecIsValidHandle(&nla->credentials))
		{
			nla->status = nla->table->FreeCredentialsHandle(&nla->credentials);
			SecInvalidateHandle(&nla->credentials);
                 	if (nla->status != SEC_E_OK)
		        {
			        WLog_ERR(TAG, "FreeCredentialsHandle status %s [0x%08" PRIX32 "]",
			         GetSecurityStatusString(nla->status), nla->status);
		        }
		}

```

**Comment by akallabeth** [comment]
True, the check is redundant and can be removed.
Is that better in #5757 ? I´ve been preparing that one but I think it could need some more scrutiny before being integrated.

**Comment by qunying** [comment]
Hi @akallabeth  In your #5757 pull request, in function nla_client_recv_pub_key_auth(), the return code are still not updated like the old code.

BTW, the old code has some special handling for Kerberos, is that not needed?
