### ISSUE TITLE
FreeRDP not working in RemoteApp mode.

### ISSUE THREAD

**Issue by Panchraj** [FreeRDP/FreeRDP#5872]
Hi,
I want to use FreeRDP-2.0(Wfreerdp) to start a remote desktop application and tried with below command:
wfreerdp /u:Demo /p:abcd@def /app:"E:\DesktopApps\OFM.exe" /app-name:"E:\DesktopApps\OFM.exe" /w:1366 /h:768 /v:1.23.1.55
it displays a black screen for approx. 10 seconds and then disappeared.

Thanking you.

**Comment by akallabeth** [comment]
Please use the mailing list or IRC for support (see https://freerdp.com)
As for `wfreerdp.exe` and RAILS it works, but has quite a few flaws. 
Improvements (as in pull requests) are very welcome.
