### ISSUE TITLE
USB redirection is not working and some strange error!

### ISSUE THREAD

**Issue by ertos12** [FreeRDP/FreeRDP#5873]
I built freerdp-2.0.0-dev5 as follows:

$ cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DWITH_WAYLAND=OFF -DWITH_CPUS=ON -DWITH_SSE2=ON -DWITH_CHANNELS=ON -DWITH_CLIENT_CHANNELS=ON -DWITH_CLIENT=ON -DWITH_CLIENT_INTERFACE=ON -DBUILD_SHARED_LIBS=ON -DBUILTIN_CHANNELS=OFF -DCHANNEL_URBDRC=ON -DCHANNEL_URBDRC_CLIENT=ON -DCMAKE_INSTALL_PREFIX:PATH=/opt/freerdp_devel/freerdp .

$ make && sudo make install

Then create "/etc/ld.so.conf.d"freerdp-devel.conf" file with follows contents:
"/opt/freerdp_devel/freerdp/lib"
"/opt/freerdp_devel/freerdp/lib/freerdp2"

And, 
$sudo ldconfig

I ran xfreerdp to check the usb redirection function as follows:
./xfreerdp /v:192.168.0.128 /u:S01 /p:1 /rfx /usb:auto

RDP connection is OK.
When I inserted the USB Memory into the USB, xfreerdp hangs with the following error message:

./xfreerdp: symbol lookup error: /opt/remmina_devel/freerdp/lib/freerdp2/liburbdrc-client-libusb.so: undefined symbol: add_device

What's problem? I don't know exactly..

**Comment by akallabeth** [comment]
@ertos12 please use the mailing list or IRC for support questions, you seem to have mixed some settings with previous compiles.
