### ISSUE TITLE
accept certificate is broken on Windows - and what about alternatives?

### ISSUE THREAD

**Issue by jol64** [FreeRDP/FreeRDP#5878]
**Describe the bug**
Prompt whether to accept certificate is broken on Windows (didn´t test on linux).

**To Reproduce**

Using wfreerdp version 2.0.0-dev5 (245fc6014) and connecting to a hyper-v VM using a command line like
 
wfreerdp.exe" /v:hyper-v-host "/t:test" /u:Joachim /p:*** /vmconnect:fa0a83c1-5ac4-4355-8020-cfc75898beeb /audio-mode:0

I get a prompt whether to accept certificate 

Certificate details for vyper2019.samba.lindenberg.one:2179 (RDP-Server):
        Common Name: Vyper2019.samba.lindenberg.one
        Subject:     CN = Vyper2019.samba.lindenberg.one
        Issuer:      CN = Vyper2019.samba.lindenberg.one
        Thumbprint:  00:82:42:6a:56:0b:98:e7:b7:82:f2:b9:bc:d1:3d:ed:8d:93:81:f1
The above X.509 certificate could not be verified, possibly because you do not have
the CA certificate in your certificate store, or the certificate has expired.
Please look at the OpenSSL documentation on how to add a private CA to the store.
Do you trust the above certificate? (Y/T/N) Y
Der Befehl "Y" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

Obviously my system is German. With English I get:
Do you trust the above certificate? (Y/T/N) Y
'Y' is not recognized as an internal or external command,
operable program or batch file.

wfreerdp just does not accept any of the options offered (and also not the German equivalent Ja). To me it looks like the prompt is broken on Windows.

**Expected behavior**
Fix prompt or remove it..

**Alternatives**
Thinking about it... in my use case I do have the option of providing the thumbprint or certificate up front. 
- What about adding a command line option, what thumbprint to expect/accept (not ignoring subject etc of course)? If you print the thumbprint, a user could actually validate it and then supply it on next invocation
- or alternatively what keystore would I have to prepopulate? on windows?

Thanks, Joachim

**Comment by akallabeth** [comment]
Yes, that is known (windows and stdin/stdout is a bit of a mess).
Try /cert-tofu which uses a trust on first use style approach.

**Comment by akallabeth** [comment]
As for fingerprint from cmd, I don't remember if the windows version supports it but there is something for one client, need to check tomorrow.

**Comment by jol64** [comment]
> Yes, that is known (windows and stdin/stdout is a bit of a mess).
> Try /cert-tofu which uses a trust on first use style approach.
Because of the "mess" I am automating user interaction to the extent possible. /cert-tofu requires some user interaction. Moreover, normal users have no clue how and also likely no authorizations to look up the fingerprint.
If you could sketch how, I might be able to put together a PR.

**Comment by akallabeth** [comment]
@jol64 for your use case it might be best (currently) to use a custom build with `wf_create_console` disabled / commented out.
That way you have the old behaviour and graphical user/certificate dialogs.

**Comment by akallabeth** [comment]
Ok, this one is fixed with the current nightly (we use the graphic prompts).
#5879 is another beast though.
