### ISSUE TITLE
windows output/error redirection

### ISSUE THREAD

**Issue by jol64** [FreeRDP/FreeRDP#5879]
**Describe the bug**
it is no longer possible to redirect error

**To Reproduce**

wfreerdp.exe" /v:vyper2019.samba.lindenberg.one "/t:teset" /u:dd /p:dd /vmconnect:fa0a83c1-5ac4-4355-8020-cfc75898beeb /audio-mode:0 2>x.out

**Expected behavior**
all diagnostics in x.out. Not the case with version 2.0.0-dev5 (245fc60). Occurs on command line (which is not visible to the user in my use case, nor would the user like to copy that manually).
I tested with the older version 2.0.0-dev3 (b34e3bcf7) and redirection works with that.

**Comment by akallabeth** [comment]
Yes, we need to fix that with some kind of switch (need to see output and allow redirect)
If someone has an idea how to fix that, a pr is welcome. Will have a look again when time permits, but that won't be soon, sorry.

**Comment by jol64** [comment]
with switch you imply, not using > but a command line switch that implements sort of linux tee command, that outputs to console plus a file?

**Comment by akallabeth** [comment]
Basically a version of https://www.tillett.info/2013/05/13/how-to-create-a-windows-program-that-works-as-both-as-a-gui-and-console-application/ that actually works.
Alternatively just disable the console support altogether.

**Comment by jol64** [comment]
by accident I came accross this before and failed to get this reliable (can be my time box of course). Actually there is probably not a lot input wfreerdp.exe needs to get (I know about that certificate prompt and a password dialog), and for usability real dialogs are better anyway. 
My suggestion would be to do away with the console, and log to a directory like C:\Programdata\freerdp instead, or allow to specify a log file explicitly.
If  wf_create_console (https://github.com/FreeRDP/FreeRDP/issues/5878#issuecomment-585202715) does the trick, then what about making this a (windows specific) command line option? I really prefer nightly builds rather then my home grown..

**Comment by jol64** [comment]
most recent nightly build (https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=vs2013/) cannot output anything to console with --version or --help.
Probably due to https://github.com/FreeRDP/FreeRDP/pull/5881.

**Comment by akallabeth** [comment]
@jol64 exactly, now it is a default windows program again.

**Comment by jol64** [comment]
windows <> console? i.e. no output at all except where dialogs exist? How do you plan to get debugging output in case connections fail? Planning to add a log file switch?

**Comment by akallabeth** [comment]
@jol64 redirect to a file.

**Comment by jol64** [comment]
I´d not call this intuitive. And one has to redirect both 1 and 2 to see both diagnostics and error messages.

**Comment by akallabeth** [comment]
@jol64 well, then you need to find a way to reattach stdin to console if you run from one...
