### ISSUE TITLE
Can't use usb webcam in Windows remote host (Windows 10) from ubuntu vm

### ISSUE THREAD

**Issue by myjimmy** [FreeRDP/FreeRDP#5887]
**Describe the bug**
I installed Ubuntu 18.04 64 bit virtual machine in VMware 15.0.4 and Windows 10 64bit.
Also, I installed Windows 10 64bit virtual machine as a remote host.
I plugged the USB webcam on my computer and connected it to ubuntu virtual machine.
![attach-webcam](https://user-images.githubusercontent.com/52309150/74639414-8a823000-5176-11ea-937b-331f9ab2d3e6.png)

In ubuntu vm, I run the following command:
`$ sudo xfreerdp /v:192.168.77.134 /u:ptc /dvc:urbdrc,dev:1908:2311`
192.168.77.134 is Windows 10 virtual machine.
![terminal-command](https://user-images.githubusercontent.com/52309150/74639686-fcf31000-5176-11ea-99b0-efd7a5660a2a.png)

**Error**
Then, I get the following error:
```
... ... ...
VID: 0x1908, PID: 0x2311
libusb_set_configuration: error LIBUSB_ERROR_OTHER [-99]
Set interface altsetting get error num -99
libusb_control_transfer LIBUSB_ERROR_PIPE [-9]
... ... ...
```

![terminal-error](https://user-images.githubusercontent.com/52309150/74641516-19447c00-517a-11ea-94f7-8631815bce15.png)

I can see the webcam item on the camera page of Chrome web browser in about 20s.
![chrome-camera-page](https://user-images.githubusercontent.com/52309150/74642001-e64eb800-517a-11ea-873f-baa5c10258d5.png)

But I can't use this device in the webRTC sample pages such as the following pages:
https://simpl.info/getusermedia/sources/
https://webrtc.github.io/samples/src/content/getusermedia/gum/
![webrtc-sample-page](https://user-images.githubusercontent.com/52309150/74642202-39286f80-517b-11ea-9aa9-9e1dd0019ac7.png)

** Application details
* Version of FreeRDP : latest version of master branch
* Command line used : sudo xfreerdp /v:192.168.77.134 /u:ptc /dvc:urbdrc,dev:1908:2311

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 64bit

Thanks for any help.

**Comment by akallabeth** [comment]
Hi @myjimmy 
A few things:
* Never run `xfreerdp` with `sudo` ;)
* Does the webcam work locally with e.g. `cheese`?
* Could you check the USB device with `lsusb -v -d <vid>:<pid>` which configuration descriptors the device announces?
* Could you run with `/log-filters:com.freerdp.channels.urbdrc.client:debug` for some details on where the redirection is not working?

**Comment by akallabeth** [comment]
Oh, and default command line for USB redirection is `/usb:<args>`, see `xfreerdp /?`

**Comment by akallabeth** [comment]
on a 3rd look, it might be a simple misues of command line arguments, try `/usb:id,dev:<vid>:<pid>` just like the help suggests.

**Comment by myjimmy** [comment]
> Hi @myjimmy
> A few things:
> 
> * Never run `xfreerdp` with `sudo` ;)
I know it.
However, if I run it without sudo, I got the following error:
![access-denied](https://user-images.githubusercontent.com/52309150/74648712-e359c480-5186-11ea-922f-793618a510bc.png)

> * Does the webcam work locally with e.g. `cheese`?
Yes, I do. Cheese work with the webcam.
![cheese-webcam](https://user-images.githubusercontent.com/52309150/74648960-506d5a00-5187-11ea-90de-7a0cacdf5ea7.png)

> * Could you check the USB device with `lsusb -v -d <vid>:<pid>` which configuration descriptors the device announces?
I have uploaded the log file of this command.
[lsusb-log.txt](https://github.com/FreeRDP/FreeRDP/files/4213374/lsusb-log.txt)

> * Could you run with `/log-filters:com.freerdp.channels.urbdrc.client:debug` for some details on where the redirection is not working?
I have attached the log.
![detail-log](https://user-images.githubusercontent.com/52309150/74649394-1c466900-5188-11ea-8099-ad251634493f.png)

@akallabeth  Thanks for your reply.

**Comment by myjimmy** [comment]
> on a 3rd look, it might be a simple misues of command line arguments, try `/usb:id,dev:<vid>:<pid>` just like the help suggests.

I used the command line format like `/usb:id,dev:<vid>:<pid>`, but the error is the same.
![terminal-usb-command-line](https://user-images.githubusercontent.com/52309150/74657988-08a3fe00-519a-11ea-89ce-d40df898cecb.png)

**Comment by akallabeth** [comment]
hmm, ok, intersting.
The setup sequence looks good, so it is not a `xfreerdp` error.
You might want to check https://github.com/libusb/libusb/wiki/FAQ for setting up libusb correctly or try running with a newer libusb altogether.
`libusb_set_configuration: error LIBUSB_ERROR_OTHER [-99]` is what worries me, because that is something from the USB device
(this is a low level USB protocol function where the appropriate `configuration` is chosen as every USB device can have multiple of these. This happens on the server side, the windows USB driver)

So, from what I see here there are the following options:
1. `libusb` has an issue and can not set the device configuration properly
  * This can be tested by updating `libusb` or searching their issue tracker
1. something is blocking the device preventing the configuration change
  * Doubtful, but maybe test with a very simple setup (`XTerm` only session or similar)
1. there is some bug on the device itself
  * Hard to debug as we don´t know exactly what is triggering it

I might still have missed something, but that is what comes to mind after thinking a bit about it.

**Comment by myjimmy** [comment]
@akallabeth Thanks for your help.
I'll try again according to your options.
If I find something, I'll comment on it.

Thanks again.

**Comment by myjimmy** [comment]
> hmm, ok, intersting.
> The setup sequence looks good, so it is not a `xfreerdp` error.
> You might want to check https://github.com/libusb/libusb/wiki/FAQ for setting up libusb correctly or try running with a newer libusb altogether.
> `libusb_set_configuration: error LIBUSB_ERROR_OTHER [-99]` is what worries me, because that is something from the USB device
> (this is a low level USB protocol function where the appropriate `configuration` is chosen as every USB device can have multiple of these. The source is on the server side, the windows USB driver)
> 
> So, from what I see here there are the following options:
> 
> 1. `libusb` has an issue and can not set the device configuration properly
> 
> * This can be tested by updating `libusb` or searching their issue tracker
#### I'm using Ubuntu 18.04 64bit. Ubuntu 18.04 has libusb-1.0.21-2.
#### Also, the latest version of libusb is 1.0.23.
#### I don't know how to update libusb.
#### @akallabeth Please tell me how to update libusb.

> 1. something is blocking the device preventing the configuration change
> 
> * Doubtful, but maybe test with a very simple setup (`XTerm` only session or similar)
#### I don't know how to test it with XTerm.
#### @akallabeth Please tell me how to test it with XTerm.

> 1. there is some bug on the device itself
> 
> * Hard to debug as we don´t know exactly what is triggering it
> 
> I might still have missed something, but that is what comes to mind after thinking a bit about it.

**Comment by akallabeth** [comment]
@myjimmy simplest way would be to install a newer ubuntu on an USB stick and install the freerdp nightly there, then you have another system you can test with.
Another option is to install a newer version from https://packages.ubuntu.com but since they are ususally compiled for newer versions of ubuntu your results may vary.
As for the simpler session `apt install openbox` and select that at next login (there should be a gear wheel or similar to choose the session you want to log into)

**Comment by akallabeth** [comment]
Closing this, as this seems to be a device or libusb bug/incompatibility. (more of a device thing actually)
see https://github.com/libusb/libusb/issues/694 maybe they can find a solution, but from the RDP side of things there is nothing we can do.

**Comment by myjimmy** [comment]
@akallabeth 
I have a question.
Does FreeRDP support "[Remote Desktop Protocol: Video Capture Virtual Channel Extension](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpecam/92af6790-b79c-4813-9c07-7c545bed0242)"?

**Comment by akallabeth** [comment]
@myjimmy Id have a look at the issues first before asking such questions ;)
There are 3 of them pinned and one will answer it.

**Comment by akallabeth** [comment]
@myjimmy #4971 is what you´re looking for.

**Comment by myjimmy** [comment]
Thanks.
Do you let me know when you plan to implement it?
