### ISSUE TITLE
Most of RDP conformance tests (RDPBCGR) failed

### ISSUE THREAD

**Issue by ligurio** [FreeRDP/FreeRDP#5893]
**Describe the bug**

Some time ago Microsoft opened an RDP specifications and then published testsuites for testing RDP client implementations (conformance tests) - https://github.com/Microsoft/WindowsProtocolTestSuites. I ran tests in testsuite RDPBCGR against xfreerdp and half of them are failed.

**To Reproduce**
1. Setup test stand as described in documentation: https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/RDP_ClientUserGuide.md, https://github.com/Microsoft/WindowsProtocolTestSuites/blob/staging/TestSuites/RDP/Client/docs/RDP_Overview_ClientTestDesignSpecification.md
2. Build XFreeRDP client and run [Python wrapper](https://github.com/microsoft/WindowsProtocolTestSuites/tree/staging/TestSuites/RDP/RDPSUTControlAgent/Python) on Linux machine
3. Start testing on Windows machine
4. See failed tests in a report generated by Windows Test Manager

**Actual behavior**

Passed BVT_ConnectionTest_BasicSettingExchange_PositiveTest_ExtendedClientDataSupported
Failed BVT_ConnectionTest_CapabilityExchange_PositiveTest
Passed BVT_ConnectionTest_ChannelConnection_PositiveTest
Failed BVT_ConnectionTest_ConnectionFinalization_PositiveTest_BitmapHostCacheSupported
Passed BVT_ConnectionTest_ConnectionInitiation_PositiveTest
Failed BVT_ConnectionTest_Disconnection_PositiveTest_ServerInitiated
Passed BVT_ConnectionTest_SecurityExchange_PositiveTest
Failed BVT_ReactivationTest_PositiveTest_BitmapHostCacheSupported
Passed S1_ConnectionTest_BasicSettingExchange_NegativeTest_InvalidClientReaquestedProtocols
Passed S1_ConnectionTest_BasicSettingExchange_NegativeTest_InvalidEncodedLength
Failed S1_ConnectionTest_BasicSettingExchange_NegativeTest_InvalidEncryptionMethod
Passed S1_ConnectionTest_BasicSettingExchange_NegativeTest_InvalidH221NonStandardkey
Passed S1_ConnectionTest_BasicSettingExchange_NegativeTest_InvalidServerCertificate
Passed S1_ConnectionTest_BasicSettingExchange_NegativeTest_InvalidServerRandomLen
Passed S1_ConnectionTest_BasicSettingExchange_NegativeTest_MCSConnectResonseFailure
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_EncryptionMethodandLevel
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_ExtendedClientDataNotSupported
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_MCSChannelIdOfServerMessageChannelData_LessMaxValue
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_MCSChannelIdOfServerMessageChannelData_MaxValue
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_MCSChannelIdOfServerMessageChannelData_ONE
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_MCSChannelIdOfServerMessageChannelData_ZERO
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_MCSChannelIdOfServerNetworkData_LessMaxValue
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_MCSChannelIdOfServerNetworkData_ONE
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_MCSChannelIdOfServerNetworkData_ZERO
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_RnsUdScDynamicDstSupported
Failed S1_ConnectionTest_BasicSettingExchange_PositiveTest_V10Server
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_V1andV2RnsUdScEdgeActionsSupported
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_V1RnsUdScEdgeActionsSupported
Passed S1_ConnectionTest_BasicSettingExchange_PositiveTest_V2RnsUdScEdgeActionsSupported
Passed S1_ConnectionTest_CapabilityExchange_NegativeTest_DemandActive_IncorrectSignature
Passed S1_ConnectionTest_CapabilityExchange_NegativeTest_DemandActive_InvalidMCSLength
Passed S1_ConnectionTest_CapabilityExchange_NegativeTest_DemandActive_InvalidPDULength
Passed S1_ConnectionTest_CapabilityExchange_NegativeTest_DemandActive_InvalidTKPKLength
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCacheHostSupportCapSet_NotPresent
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCapSet_24ColorDepth
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCapSet_DesktopResizeNotSupported
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCapSet_DrawingFlagsNotSet
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCapSet_MaxDesktopHeight
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCapSet_MaxDesktopWidth
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCodecsCapSet_BitmapCodecCount_LargeValue
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCodecsCapSet_BitmapCodecCount_MaxValue
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCodecsCapSet_NoBitmapCodec
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_BitmapCodecsCapSet_NotPresent
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_DesktopCompositionCapSet_CompositionNotSupport
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_DesktopCompositionCapSet_NotPresent
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_FontCapSet_NotPresent
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_GeneralCapSet_FPOutputNotSupported
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_GeneralCapSet_OSTypeUnspecified
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_GeneralCapSet_OSTypeWindowsRT
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_GeneralCapSet_RefreshRectNotSupported
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_GeneralCapSet_SuppressOutputNotSupported
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_InputCapSet_OnlySupportScanCodes
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_LargePointerCapSet_LargePointerNotSupport
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_LargePointerCapSet_NotPresent
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_MultifragmentUpdateCapSet_MaxRequestSizeLargeValue
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_MultifragmentUpdateCapSet_NotPresent
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_OrderCapSet_ExtraFlagNotValid
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_OrderCapSet_SolidPatternBrushOnly
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_PointerCapSet_ColorPointerCacheSize_0
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_PointerCapSet_PointerCacheSize_0
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_SurfaceCommandsCapSet_NotPresent
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_SurfaceCommandsCapSet_StreamSurfaceBitsNotSupported
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_VirtualChannelCapSet_CompressionNotSupport
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_VirtualChannelCapSet_MaxVCChunkSize
Failed S1_ConnectionTest_CapabilityExchange_PositiveTest_VirtualChannelCapSet_VCChunkSizeNotPresent
Passed S1_ConnectionTest_ChannelConnection_NegativeTest_MCSAttachUserConfirm_Failure
Passed S1_ConnectionTest_ChannelConnection_NegativeTest_MCSAttachUserConfirm_InitiatorNotPresent
Passed S1_ConnectionTest_ChannelConnection_NegativeTest_MCSAttachUserConfirm_InvalidTPKTLength
Passed S1_ConnectionTest_ChannelConnection_NegativeTest_MCSChannelJoinConfirm_ChannelIdNotPresent
Passed S1_ConnectionTest_ChannelConnection_NegativeTest_MCSChannelJoinConfirm_Failure
Passed S1_ConnectionTest_ChannelConnection_NegativeTest_MCSChannelJoinConfirm_InvalidChannelId
Passed S1_ConnectionTest_ChannelConnection_NegativeTest_MCSChannelJoinConfirm_InvalidTPKTLength
Failed S1_ConnectionTest_ConnectionFinalization_PositiveTest_BitmapHostCacheNotSupported
Failed S1_ConnectionTest_ConnectionFinalization_PositiveTest_BitmapHostCacheSupported_sequenceTest_1
Failed S1_ConnectionTest_ConnectionFinalization_PositiveTest_BitmapHostCacheSupported_sequenceTest_2
Failed S1_ConnectionTest_ConnectionFinalization_PositiveTest_BitmapHostCacheSupported_sequenceTest_3
Passed S1_ConnectionTest_ConnectionInitiation_NegativeTest_InvalidRDPNegData
Passed S1_ConnectionTest_ConnectionInitiation_NegativeTest_InvalidTPKTHeader
Passed S1_ConnectionTest_ConnectionInitiation_NegativeTest_RDPNegotiationFailure
Passed S1_ConnectionTest_ConnectionInitiation_PositiveTest_FlagsOfRdpNegRsp_SupportAllProtocols
Inconclusive S1_ConnectionTest_ConnectionInitiation_PositiveTest_HybridEXSelected
Passed S1_ConnectionTest_ConnectionInitiation_PositiveTest_RDPNegotiationFailure
Failed S1_ConnectionTest_Disconnection_NegativeTest_MCSDisconnectProviderUltimatum_InvalidTPKTLength
Passed S1_ConnectionTest_SecurityExchange_NegativeTest_LicenseError_InvalidFlag
Passed S1_ConnectionTest_SecurityExchange_NegativeTest_LicenseError_InvalidMCSLength
Passed S1_ConnectionTest_SecurityExchange_NegativeTest_LicenseError_InvalidSignature
Passed S1_ConnectionTest_SecurityExchange_NegativeTest_LicenseError_InvalidTKPKLength
Failed S10_FastPathOutput_PositiveTest_CachedPointer_WithColorPointer
Failed S10_FastPathOutput_PositiveTest_CachedPointer_WithNewPointer
Failed S10_FastPathOutput_PositiveTest_CachedPointer_WithNewPointer_MultiCachedPointers
Failed S10_FastPathOutput_PositiveTest_CachedPointer_WithNewPointer_ReuseCacheIndex
Failed S10_FastPathOutput_PositiveTest_ColorPointer_HotSpotOnTheBorderOfPointer
Failed S10_FastPathOutput_PositiveTest_ColorPointer_InitPointer
Failed S10_FastPathOutput_PositiveTest_ColorPointer_MaxAllowedCacheIndex
Failed S10_FastPathOutput_PositiveTest_ColorPointer_MaxAllowedWidthHeightLargePointerNotSupported
Failed S10_FastPathOutput_PositiveTest_ColorPointer_OddWidth
Failed S10_FastPathOutput_PositiveTest_ColorPointer_UpdatePointer
Failed S10_FastPathOutput_PositiveTest_NewPointer_HotSpotOnTheBorderOfPointer
Failed S10_FastPathOutput_PositiveTest_NewPointer_InitPointer
Failed S10_FastPathOutput_PositiveTest_NewPointer_MaxAllowedCacheIndex
Failed S10_FastPathOutput_PositiveTest_NewPointer_MaxAllowedWidthHeightLargePointerNotSupported
Failed S10_FastPathOutput_PositiveTest_NewPointer_OddWidth
Failed S10_FastPathOutput_PositiveTest_NewPointer_UpdatePointer
Failed S10_FastPathOutput_PositiveTest_NewPointer_XorBpp_32
Failed S10_FastPathOutput_PositiveTest_PointerHidden
Failed S10_FastPathOutput_PositiveTest_PointerPosUpdate_PointerMove
Failed S10_FastPathOutput_PositiveTest_PointerPosUpdate_PointerOnTheBorderOfScreen
Failed S2_ReactivationTest_PositiveTest_BitmapHostCacheNotSupported
Failed S4_SlowPathInputTest_NegativeTest_ServerToClientSlowPath_InvalidEncryptFlag
Failed S4_SlowPathInputTest_NegativeTest_ServerToClientSlowPath_InvalidMCSLength
Passed S4_SlowPathInputTest_NegativeTest_ServerToClientSlowPath_InvalidSignature
Failed S4_SlowPathInputTest_NegativeTest_ServerToClientSlowPath_InvalidTotalLenth
Failed S4_SlowPathInputTest_NegativeTest_ServerToClientSlowPath_InvalidTPKTLength

**Expected behavior**
All tests are passed

**Application details**
* Version: FreeRDP 6bf94972b1e47d938a1ae8f911d4494c8e5c236c
* output of `/buildconfig`:

```
This is FreeRDP version 2.0.0-dev5 (6bf94972b)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 7.4.0
Target architecture: x64
```

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux, Windows 7 Enterprise SP1 x86_64
```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

**Additional context**

RDPBCGR specification
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/5073f4ed-1e93-45e1-b039-6e30c385867c

**Comment by akallabeth** [comment]
@ligurio thank you for the report.
We´ll have a look at it.
As for `/buildconfig` that is a command line option of the clients. It prints out compilation options, some of which are in the header you mentioned.

One question though, as some of the failed tests reference stuff that is by default deactivated from `xfreerdp`, does adding `+bitmap-cache`, `+offscreen-cache` et al fix these?

**Comment by ligurio** [comment]
@akallabeth 

> As for /buildconfig that is a command line option of the clients. It prints out compilation options, some of which are in the header you mentioned.

Added output to the description.

> One question though, as some of the failed tests reference stuff that is by default deactivated from xfreerdp, does adding +bitmap-cache, +offscreen-cache et al fix these?

XFreeRDP usage shows that boath options are ON by default:
```
    -bitmap-cache (default:on)  bitmap cache
    -offscreen-cache (default:on)       offscreen bitmap cache
```

**Comment by akallabeth** [comment]
@ligurio thanks for the update. Missed that you were using a version from last november.

**Comment by hardening** [comment]
It looks super interesting, could you post the detailed log of the test suite somewhere ?

**Comment by akallabeth** [comment]
@nfedera fixed the first batch of issues: https://github.com/microsoft/WindowsProtocolTestSuites/pull/219

**Comment by nfedera** [comment]
With FreeRDP/pull/5901 applied all MS-RDPBCGR tests succeeded except `S1_ConnectionTest_CapabilityExchange_PositiveTest_LargePointerCapSet_LargePointerNotSupport`, which I'll check another time.
