### ISSUE TITLE
RemoteApp Window Size unable to change

### ISSUE THREAD

**Issue by KeepHell** [FreeRDP/FreeRDP#5909]
if you start a RemoteApp for example:

xfreerdp /v:<SERVER> /d:DOMAIN /u:USER /p:'PW'  -floatbar /cert-ignore /rfx /gdi:hw +clipboard +aero +fonts /app:"||APP"

RemoteApp start as expected, but its not possible to handle the window, you could resize it to half of the monitor, so if you click anywhere other than the RemoteApp Window, the RemoteApp window  gets maximized...
 
Issue only exist in Plasma, Gnome is working.
thanks.

**Comment by akallabeth** [comment]
Well, which version did you try, which distro?
Did you give our nightly builds a try? https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds
