### ISSUE TITLE
USB Redirection

### ISSUE THREAD

**Issue by AzureusNation** [FreeRDP/FreeRDP#5910]
When using RemoteFX usb redirection the first time a usb device is plugged in it redirects fine. You take the device out and it is removed from the device manager on the remote server as expected. However, if you go to plug the device in again it no longer redirects but is picked up on the OS of the computer. Running both as a normal user and as root causes this to happen.

**Comment by akallabeth** [comment]
please provide a small idea of how you use it.
this might be a simple user error or some bug in the channel, but with that description it is only guessing...

**Comment by AzureusNation** [comment]
Sorry, im using the /usb:auto flag when running freerdp on linux. Once the session has started i have plugged the device in. FreeRDP registers it and redirects correctly to the remote machine and is displayed in device manager. If i unplu the device it is removed correctly. i would then expect if i plugged the device back in again for it to automaticly redirect to the remote machine again but it doesn't. However if you remove the usb device FreeRDP sends a message to the server to update the device manager as that refreshes when removing the device.

**Comment by AzureusNation** [comment]
Can I put another related issue to this one on this issue?

**Comment by AzureusNation** [comment]
Working with the ThinStation project it has a script that uses the udev rules to then automaticly mount the usb flash drives to a specific folder. This all works fine when FreeRDP isnt open but when FreeRDP is open it is then unable to run the script as I think FreeRDP is quicker grabbing the device before the udev rules.

I have found that this is only when using the /usb:auto arguments but I do need this argument to be able to load usb devices plugged in after starting freerdp. Could there be a /usb:<something> argument that doesn't load usb flash drives or hard disks?

**Comment by AzureusNation** [comment]
Sorry, still not working on second device plugins. Will get trace reports for you.

**Comment by AzureusNation** [comment]
[log.txt](https://github.com/FreeRDP/FreeRDP/files/4280328/log.txt)
