### ISSUE TITLE
RemoteApp session opens for a brief moment then autocloses with "Closed from X11"

### ISSUE THREAD

**Issue by tsucevic** [FreeRDP/FreeRDP#5924]
Hi, 
I'm currently working on using a Raspberry Pi as a server terminal for a server application.
My Raspberry Pi Zero W is running buster and the server is running Windows Server 2008 R2.
The freeRDP version is 2.0.0-dev5.

Now to the issue, whenever I try to connect to the remote app using the syntax:
`xfreerdp /app"||calc" /v:<server name> /d:<domain>`

The app opens briefly (for max 1-2 seconds) then it closes with
```
[09:01:00:213] [1109:1110] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[09:01:00:214] [1109:1110] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[09:01:01:517] [1109:1110] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[09:01:16:930] [1109:1110] [INFO][com.freerdp.client.x11] - Closed from X11
```

I tried installing a nightly build but it said it doesn't support ARM processors (I'm a complete linux AND raspberryPi noob so I might've been doing something wrong). 

How can I fix the problem I have?

**Comment by akallabeth** [comment]
@tsucevic you can try building the debian nightly (see https://github.com/FreeRDP/FreeRDP/wiki/Compilation ) yourself.
* running with `/log-level:debug` might help too to get an idea of what is going on.
* checking that the remote app is actually allowed with another system might help eliminate a lot of possible error sources

**Comment by tsucevic** [comment]
@akallabeth 

> running with /log-level:debug might help too to get an idea of what is going on.
I tried that now, these are the last couple of lines https://pastebin.com/zDigT9uE 

> checking that the remote app is actually allowed with another system might help eliminate a lot of possible error sources
I can connect to the remote app through my windows machine (using the .rdp file that the server generates) without any problems. 

As for nightly build compilation. I don't really feel competent enough to do that. I tried using:
```
wget -O - http://pub.freerdp.com/repositories/ADD6BF6D97CE5D8D.asc | sudo apt-key add -
sudo sh -c 'echo "deb http://pub.freerdp.com/repositories/deb/buster/ freerdp-nightly main" >> /etc/apt/sources.list.d/freerdp-nightly.list'
sudo apt-get update
sudo apt-get install -y freerdp-nightly
```
And after I run the last command it says 
`E: Unable to locate package freerdp-nightly`

**Comment by akallabeth** [comment]
@tsucevic there are no prebuilt packages for arm, but you can compile with the 2 line instructions on the wiki for the debian `dpkg-buildpackage` instructions

**Comment by tsucevic** [comment]
@akallabeth Hmm... I tried executing these:
```
sudo apt build-dep freerdp2-x11
ln -s packaging/deb/freerdp-nightly debian
dpkg-buildpackage
```
The first one says
 `E: You must put some 'source' URIs in your sources.list`
The second one has no output, I don't know if it should.
The third one has this error
`dpkg-buildpackage: error: cannot open file debian/changelog: No such file or directory`

Does the remote app feature work better in nightly?

**Comment by akallabeth** [comment]
@tsucevic enable `Source code` in your `software & updates` utility and rerun. (alternatively edit `/etc/apt/sources.list`, copy all `deb http...` lines and replace `deb` with `dep-src` for the copied lines.

**Comment by tsucevic** [comment]
@akallabeth okay so I did these steps
Before all that, I had cloned the git as stated in the compilation wiki
1. edited both sources.list and sources.list.bak to add deb-src
2. sudo apt build-dep freerdp2-x11
it started reading package lists then picked freerdp2 as source package instead of freerdp2-x11
3. there was some installing time
4. `ln -s packaging/deb/freerdp-nightly debian`
this did basically nothing and said "File exists" probably because I already did it several times before 
5. `dpkg-buildpackage`
the output was this.
```
pi@tinpizero:~/FreeRDP $ dpkg-buildpackage
dpkg-buildpackage: info: source package freerdp-nightly
dpkg-buildpackage: info: source version 2.0.0
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by FreeRDP <team@freerdp.com>
dpkg-buildpackage: info: host architecture armhf
 dpkg-source --before-build .
dpkg-checkbuilddeps: error: Unmet build dependencies: cdbs libcairo2-dev libxml2-dev
dpkg-buildpackage: warning: build dependencies/conflicts unsatisfied; aborting
dpkg-buildpackage: warning: (Use -d flag to override.)
```

Should this work now or is it still not properly installed? How do I run it?

**Comment by akallabeth** [comment]
@tsucevic no, `dpkg-checkbuilddeps: error: Unmet build dependencies: cdbs libcairo2-dev libxml2-dev` states it is still missing some dependencies. Install these packages and retry.
This will create `.deb` packages you can then install. The binaries will be under `/opt` so you need to start with `/opt/freerdp-nightly/bin/xfreerdp`

**Comment by tsucevic** [comment]
@akallabeth I probably did this wrong but it didn't work.
```
pi@tinpizero:~/FreeRDP $ sudo apt-get install cdbs libcairo2-dev libxm12-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libxm12-dev
```

**Comment by akallabeth** [comment]
@tsucevic typo ;) libxml2-dev not libxm12-dev

**Comment by tsucevic** [comment]
@akallabeth the lib installs worked this time. 
But the dpkg-buildpackage returned an error
```
 fakeroot debian/rules binary
dh binary --parallel
   dh_testroot
   dh_prep
   dh_auto_install
dh_auto_install: mkdir debian/freerdp-nightly: File exists
make: *** [debian/rules:32: binary] Error 255
dpkg-buildpackage: error: fakeroot debian/rules binary subprocess returned exit status 2
pi@tinpizero:~/FreeRDP $ 

```

**Comment by akallabeth** [comment]
@tsucevic try with a fresh checkout (or run `git clean -xdf`) and start anew.
looks like you have a dirty working directory

**Comment by tsucevic** [comment]
@akallabeth Hey, I compiled the nightly version and I still have the same problem while using nightly. The remote app opens for a second and closes immediately with "Closed from X11"

**Comment by akallabeth** [comment]
@tsucevic this is really interesting as that specific message should not occur with the settings you run.
1. Sure you ran the binary `/opt/freerdp-nightly/bin/xfreerdp`?
1. Could you compile a nightly with `-DWITH_DEBUG_X11=ON \` added to `DEB_CMAKE_EXTRA_FLAGS` in `packaging/deb/freerdp-nightly/rules`
1. run with `/log-level:debug` and check which event triggered that. (look for log entries like `%s Event(%d): wnd=0x%08lX"`, e.g. `KeyPress Event(2): wnd=0x1234ABCDE`)

**Comment by tsucevic** [comment]
1. Yes, I ran xfreerdp from the freerdp-nightly/bin fodler.
2. I do not understand what to do.
3. I ran it with the debug and didn't find any such event in the last second of it running. Here's the copy of the last second running. https://pastebin.com/m2Gfiejv

**Comment by akallabeth** [comment]
@tsucevic add the text in the rules file and dpkg-buildpackage a new nightly

**Comment by tsucevic** [comment]
@akallabeth hi, I tried running with the debug. I searched the document for anything with "event", and there was nothing showing up. Here's the full debug log https://pastebin.com/tciE5XQc

**Comment by Ash6978** [comment]
I am also experiencing this same issue with 2.0.0-dev5 (2693389a+debian).

Closed from X11.  However I did find this on our Terminal Server that corresponds with this closing.

![image](https://user-images.githubusercontent.com/63299187/78675210-b8e8d580-78b2-11ea-9710-749d2d980fec.png)

Thanks,

Ash

**Comment by akallabeth** [comment]
@Ash6978 so, is the remote app allowed to be used and the server set up?

**Comment by Ash6978** [comment]
Yes this works from Windows via published app.  Just in case I had another user that uses windows for the published app and they were not able to get the app to run from Raspberry either.  He did let me know that he gets the same error when he connects via the app from windows too, so its not a smoking gun.

Thanks,

Ash
