### ISSUE TITLE
two finger scrool bug in version 2

### ISSUE THREAD

**Issue by tarikaltuncu** [FreeRDP/FreeRDP#5926]
Hello,

I use freerdp to connect a specific server using two mac OS computers.

One has version 1.0.2, the other 2.0.

When connected using version 1.0.2, both mouse scrool up and scrool down functions work great.

However, on version 2, scrool up works while scrool down does not.

This is interesting. The logs on command line does not report anything unusual as it does when I try horizontal scrooling as below:

```
[11:15:38:651] [74684:0325b000] [WARN][com.freerdp.core] - skip mouse event 0x0 flags=0x0578, no horizontal mouse wheel supported
[11:15:38:651] [74684:0325b000] [WARN][com.freerdp.core] - skip extended mouse event 1227x571 flags=0x0001, no extended mouse events supported
```

The system I'm trying to connect is running xrdp on Red Hat 4.4.7-17

**Comment by akallabeth** [comment]
This is no client bug. `xrdp` has some issues with not announcing what is supported and with FreeRDP2 we have tightened protocol checks.

The server announces that it does not support horizontal mouse wheel and extended mouse events (Mouse buttons 4 and 5)

**Comment by tarikaltuncu** [comment]
I see. Sorry for reopening the issue for a follow up question. Does version 1 have a scaling parameter to increase dpi? Similar to the /scale: option in the version 2.

Thanks for maintaining this project.

**Comment by akallabeth** [comment]
no
