### ISSUE TITLE
Slow performance (cache missess?) with /gfx-h264:AVC444

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#5927]
Hi, I usually use xfreerdp (and remmina) with slow internet links (1Mbps or less), so I use /gfx-h264:AVC444

I noticed that the microsoft mstsc.exe client does a better job in caching bitmaps. The remote server is Windows 10 last version, local client could be linux with xfreerdp master branch or windows 10.

On the remote server I open a fullscreen firefox with 2 tabs on 2 static images pages. An I click on those tabs to switch page.
Using mstsc.exe (and old version of xfreerdp), the 1st tab refresh takes a lot of time: 2 seconds. All other tab switches are immediate. It seems that the local RDP client cached the bitmaps of the rendered pages.

When using a recent version of xfreerdp, switching to another firefox tab on remote windows 10 firefox takes 2 seconds at every attempt. No caching seems to be performed.

I did a bit of bisecting with freerdp, the commit that introduced the slowdown seems to be https://github.com/FreeRDP/FreeRDP/commit/3b7e46fb0ecf8132201cfdaf6fd0f4184fe17f91

Cc: @antenore

**Comment by akallabeth** [comment]
@giox069 hmm, might be related to the alpha channel fix.
Could you try with gdi_apply_alpha commented out?

**Comment by giox069** [comment]
Tested commenting the call to gdi_apply_alpha(), but unfortunately it's still "uncached".

**Comment by akallabeth** [comment]
ok, the only other explanation with the referenced commit is that it has to do with the GFX version announced.
you could experiment with `/gfx:mask=0xXXXX` values and check if there is any difference.
That will force the server to send data in older formats.

(Note, the value is a bitmask filtering out the ones set. See `rdpgfx_is_capability_filtered` for used bits)

**Comment by akallabeth** [comment]
@giox069 oh, and a question: the `xfreerdp` build is `Release` or `Debug` ? We had accidentally set the build type to `Debug` for debian based nightly (resulting in degraded performance)

**Comment by akallabeth** [comment]
1. Got another question: Do you use `/network:auto` in your command line?
Announcing that activates a lot of stuff server side and will influence test results.

1. A second thought, with `gfx:avc444` there is no `cache` only the H264 decoder (and the reference frames it uses)
so, maybe changing the decoder (`ffmpeg` and `openh264` are available but need to be chosen at compile time) yields different results.

1. Since the reference is `mstsc` and we don´t exactly know what it is using in your case, it might help experimenting with different `/rfx` and `/gfx` options and see if something changes.

**Comment by giox069** [comment]
0. I will try /gfx:mask. All my test builds are Debug, including the "bisecting" ones.
1. no, never used /network:auto. I will test this too.
2. ok, so it's not a caching problem but could be some kind of "pointing" to the wrong reference frame? (I'm not H264 expert)
3. I already did only one test in the past days: /gfx:rfx. It's slower in the logon phase, when all the remote desktop changes frequently. But after this initial slowness, switching "cached" tabs in firefox seems to be faster (tested with current master) than /gfx:avc444.

I will do other testing later this night. Thank you for all the info.

**Comment by akallabeth** [comment]
0. Ok, should not really matter that much (just uses more CPU, nothing changes with bandwidth)
2. just a wild guess, don´t think it will change much, but maybe one of the decoders does not understand some parts of h264 (the gfx version changes profiles used)

**Comment by giox069** [comment]
After some testing, nothing of real interest:

1.  `/gfx:rfx` I re-tested it. It works quite well, also on master branch. So... yes, I will use /gfx:rfx in the next days to better test it.
2. I'm using ffmpeg (libavcodec). I tryed OpenH264 from their master branch, but AVC444 is totally broken (artifacts), and AVC420 is slower than /gfx:rfx
3. Release vs Debug: I did only one test in Release mode, no improvements. Maybe I should do more testing here.
4. `/network:auto` no improvements
5. `/gfx:mask:0xXXXX` no improvements. Only a value of 0xffff seems to bring performances similar to /gfx:rfx in cached ff tab switch, but it's slower to refresh full screen. See the above table.

Here are some comparisons with measured traffic on a 1920x1080 remote desktop to win10
|Commit|Switch|Bytes [1]|Bytes [2]|
|---|---|---|---|
|master|/gfx:rfx| 310KB|19K|
|master|/gfx-h264:AVC444 /gfx:<zero-width space>mask:0xffff|430KB|14K|
|master|/gfx-h264:AVC444 [4]|310KB|295KB|
|pre 3b7e46fb|/gfx-h264:AVC444|310KB|27K|

[1]: Bytes transferred from connect time to when firefox fullscreen tab is shown
[2]: Bytes transferred when switching firefox tab 2 times after it's "cached"
[4]: with no mask and other values of mask like 0xff00, 0xfff0, 0xfffe, 0x000f
Bytes count is quite approximate, due to mouse movements and other traffic.

**Comment by akallabeth** [comment]
@giox069 I´d test with masks from `0x01` to `0x1E` as the value you tested with just disables `gfx` altogether. The purpose of the mask is to selectively disable `gfx` capability versions (`8, 8.1, 10, 10.2, 10.3, 10.4, 10.5, 10.6` where `bit 0` is capability `8` etc)

**Comment by akallabeth** [comment]
@giox069 so, specifically `/gfx:avc444,mask=0xf0` should yield the same results as the old versions. This disables the `10.3, 10.4, 10.5 and 10.6` caps
