### ISSUE TITLE
Resize docked window doesn't work in RemoteApp Visual Studio.

### ISSUE THREAD

**Issue by Tachiorz** [FreeRDP/FreeRDP#5945]
Can't resize docked windows in Visual Studio 2019 Community used via RemoteApp.

1. Use Visual Studio 2019 Community installed on Win 10 via RemoteApp.
2. Try to resize docked window.
3. Docked window border flash on button press and nothing happens. 

Build f65c79e
`cmake -DWITH_SSE2=ON -DWITH_ALSA=ON -DWITH_PULSE=ON -DWITH_GFX_H264=ON -DWITH_FFMPEG=ON -DWITH_DSP_EXPERIMENTAL=ON -DCHANNEL_RAIL=ON -DCHANNEL_RAIL_CLIENT=ON -DCHANNEL_RDPGFX_CLIENT=ON -DWITH_DEBUG_RAIL=ON -DWITH_DEBUG_RDP=ON -DWITH_DEBUG_CHANNELS=ON -DWITH_DEBUG_X11=ON -DWITH_DEBUG_X11_LOCAL_MOVESIZE=ON -DWITH_DEBUG_WND=ON .`

Linux Mint 19.3 Tricia
xfce4 4.12.4

Video: [2020-03-04_17-41-05.zip](https://github.com/FreeRDP/FreeRDP/files/4288241/2020-03-04_17-41-05.zip)

[TRACE_VS_resize_docked_fail.log](https://github.com/FreeRDP/FreeRDP/files/4288257/TRACE_VS_resize_docked_fail.log)
[TRACE_TC_resize_panel_works.log](https://github.com/FreeRDP/FreeRDP/files/4288258/TRACE_TC_resize_panel_works.log)

**Comment by akallabeth** [comment]
Already mentioned in various similar issues (e.g. #5663, #4934, #2082)
Requires some investigation into windows and X11 window management behaviour and testing.
