### ISSUE TITLE
rail plugin issue

### ISSUE THREAD

**Issue by jacobpiao** [FreeRDP/FreeRDP#595]
I installed freeRDP on ubantu11 and CentOS5,5 and tested it.
When I am using the rail plug in to run a executable file, the blow error was found.
# xfreerdp -u Domain -p Password --app --plugin rail.so --data "||cmd" -- <IP>

loading plugin rail.so
Warning xf_GetWindowProperty (140): Property 237 does not exist
connected to <IP>:3389
connected to <IP>:3389
connected to <IP>:3389
RAIL exec error: execResult=RAIL_EXEC_E_NOT_IN_ALLOWLIST NtError=0x15

I tried to connect to the both of win7 and wk2008, but the same error found.

How to solve this issue?

**Comment by Okloks** [comment]
@sunds, publishing cmd doesn't work.
Allowing launching all apps remotely is not secure solution.
Win server 2008 R2 x64
