### ISSUE TITLE
[INFO][com.freerdp.utils] - Caught signal 'Segmentation fault'

### ISSUE THREAD

**Issue by MarkLTZ** [FreeRDP/FreeRDP#5956]
Hello,
starting xfreerdp /u:user /p:password /v:hostname via VNC I have a Segmentation fault if the vncviewver area size is less than the xfreerdp one.

Could someone help me to solve this issue?
Thanks

**Comment by akallabeth** [comment]
with this description, no.

**Comment by MarkLTZ** [comment]
ok I will add more information asap.

**Comment by akallabeth** [comment]
closing due to lack of information.
please add at least the versions you use next time.
(for note, tried with current master, and a session size larger than the `X11` session and I do not have any issue. Might be a bug in your vnc server
