### ISSUE TITLE
FreeRDP Header Check Error when connecting to XRDP

### ISSUE THREAD

**Issue by Nexarian** [FreeRDP/FreeRDP#5960]
**Describe the bug**
Latest build on MacOS X Catalina 10.15.3: FreeRDP no longer connects to recent build of XRDP.

**To Reproduce**
Running automator script:

/usr/local/bin/xfreerdp /u:[user] /p:[password] /ipv6 /bpp:32 /v:[hostname]:3389 /rfx /rfx-mode:video +multitransport /compression-level:2 /codec-cache:rfx /w:2560 /h:1395 +glyph-cache +offscreen-cache +bitmap-cache /video +clipboard +compression +fonts /network:lan /sec:rdp

**Expected behavior**
Should connect

**Error Message**

The action “Run Shell Script” encountered an error: “sh: xprop: command not found
sh: xprop: command not found
[12:55:58:243] [10710:088fb000] [ERROR][com.freerdp.core.channels] - Header length 20 != actual length 12
[12:55:58:243] [10710:088fb000] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
[12:55:58:243] [10710:088fb000] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[12:55:58:243] [10710:088fb000] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor”

**Comment by akallabeth** [comment]
@Nexarian thanks for the report. could you add version details for xrdp?

**Comment by akallabeth** [comment]
And for freerdp too ;)

**Comment by Nexarian** [comment]
`/usr/local/bin/xfreerdp`: `This is FreeRDP version 2.0.0-dev5 (c58db76e4)`

`sudo xrdp -v`:

```
xrdp 0.9.12
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-fuse
      --enable-ipv6
      --enable-rfxcodec
      --enable-pixman
      --enable-tjpeg
      --enable-jpeg
      --enable-mp3lame
      --enable-sound
      --enable-opus
      --enable-fdkaac
```

**Comment by akallabeth** [comment]
Ok, looks like xrdp interpretation of ms-rdpbcgr 3.1.5.2.2 and ours differ.
Will check tomorrow.

**Comment by adeutscher** [comment]
Also observed on Linux with 2.0.0-dev5 (5690780bd).
