### ISSUE TITLE
cliprdr_packet_format_list_new error after fix for 5960

### ISSUE THREAD

**Issue by Nexarian** [FreeRDP/FreeRDP#5966]
**Describe the bug**
Latest build on MacOS X Catalina 10.15.3: FreeRDP no longer connects to recent build of XRDP.

**To Reproduce**
Running automator script:

/usr/local/bin/xfreerdp /u:[user] /p:[password] /ipv6 /bpp:32 /v:[hostname]:3389 /rfx /rfx-mode:video +multitransport /compression-level:2 /codec-cache:rfx /w:2560 /h:1395 +glyph-cache +offscreen-cache +bitmap-cache /video +clipboard +compression +fonts /network:lan /sec:rdp

**Expected behavior**
Should connect

**Error Message**

The action “Run Shell Script” encountered an error: “sh: xprop: command not found
sh: xprop: command not found
[14:40:45:207] [43502:06e6b000] [WARN][com.freerdp.channels.cliprdr.common] - [cliprdr_packet_format_list_new] called with invalid type 00000000
[14:40:45:590] [43502:06535000] [ERROR][com.freerdp.core] - rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_LOGOFF_BY_USER [0x0001000C]”

**Versions**
FreeRDP: ```This is FreeRDP version 2.0.0-dev5 (6313cccb6)```

XRDP:

```
xrdp 0.9.12
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2018 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-fuse
      --enable-ipv6
      --enable-rfxcodec
      --enable-pixman
      --enable-tjpeg
      --enable-jpeg
      --enable-mp3lame
      --enable-sound
      --enable-opus
      --enable-fdkaac
```

**Comment by akallabeth** [comment]
This is only a warning, reason is the server logged the session off...
