### ISSUE TITLE
wlfreerdp touch implementation

### ISSUE THREAD

**Issue by chakuzo** [FreeRDP/FreeRDP#5967]
I use wlfreerdp and have noticed that touch screens are not supported

I have seen that in the libuwac the touch signals from Wayland are already received and started a rudimentary touch implementation. 
5d30b1160855553b66a68daea52de078d392eb4d

Currently there are still some problems with clicks that hang. It would be good if someone with experience in the project could take a look at them and give some feedback.

**Comment by akallabeth** [comment]
@chakuzo yes, wayland client is currently nowhere as complete as X11.

**Comment by chakuzo** [comment]
@akallabeth I've seen you do a lot of the work on the Wayland link. 

My current problem is that touch events arrive and are accepted by Windows, but the long press events get stuck. You can see that by the white transparent rectangles on the desktop. 

I don't know if you could give me a hint what this could be.

**Comment by akallabeth** [comment]
@chakuzo yes, did some fixes for wayland, but no idea what is wrong there.
Does wayland interpret touch events, aka does it do something to detect long press?
the RDP redirection should intercept all events and just forward them, and do no interpretation whatsoever (except coordinate mapping maybe)

**Comment by chakuzo** [comment]
I found the problem. The touch-up event was shifted by one coordinate, which caused this problem during a long press. I now remember the last position and use this position for the Touch-Up as well.

Meanwhile the touch-up implementation is running quite well. 

There is still a problem with the login screen, but the same problem with xfreerdp is that the login screen does not support touch. In the implementation, touch events are therefore turned into mouse clicks when the channel is not active. Only when Windows is locked, I have no possibility to use touch. In this case there is a RdpeiClientContext but the touch events do not arrive.

Latest Implementation: 1229f697b826088261ff6e8e1c0ed6da88a79815

**Comment by akallabeth** [comment]
@chakuzo ok, could you create a pull request for that?  or at least a branch? hard to review if it does not show up in normal git use.

**Comment by chakuzo** [comment]
I have started a pull request.

**Comment by chakuzo** [comment]
In the future I will probably make some improvements resulting from testing, but for now the issue is finished with the merge of the pull request.

Thanks a lot @akallabeth
