### ISSUE TITLE
--gdi sw: segfault in gdi_mem3blt

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#597]
Latest git clone 05/16/2012 version 1.0.1
Connect to W2K3 server and let session go to locked screensaver (blank)
Awaken session, starts to come out of screensaver to show locked logon dialog then seg faults.
Below is the gdb trace.

user@hostname:~$ gdb xfreerdp 
GNU gdb (GDB) 7.2-ubuntu
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/bin/xfreerdp...done.
(gdb) run --plugin rdpdr --data disk:home:/home/user printer:MFCXXXXDN:"Brother MFC-XXXXDN Printer" -- -0 -K -u administrator -a 15 -g 1280x960 --gdi sw 10.1.0.207
Starting program: /usr/local/bin/xfreerdp --plugin rdpdr --data disk:home:/home/user printer:MFCXXXXDN:"Brother MFC-XXXXDN Printer" -- -0 -K -u administrator -a 15 -g 1280x960 --gdi sw 10.1.0.207
[Thread debugging using libthread_db enabled]
[New Thread 0xb7dc1b70 (LWP 6169)]
loading plugin rdpdr
connected to 10.1.0.207:3389
connected to 10.1.0.207:3389
connected to 10.1.0.207:3389
[New Thread 0xb710db70 (LWP 6170)]
[New Thread 0xb690cb70 (LWP 6171)]
[New Thread 0xb610bb70 (LWP 6172)]
registered device #1: home (type=8 id=1)
registered device #2: PRN1 (type=4 id=2)
incorrect PDU type: 0x6F3D
incorrect PDU type: 0x6F3D
incorrect PDU type: 0x6F3D
incorrect PDU type: 0x6F3D
incorrect PDU type: 0x6F3D

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb7dc1b70 (LWP 6169)]
0x001a9951 in gdi_mem3blt (context=0x80e28f8, mem3blt=0x80b04f8) at /usr/local/src/FreeRDP/libfreerdp-gdi/gdi.c:649
649			gdi_BitBlt(gdi->drawing->hdc, mem3blt->nLeftRect, mem3blt->nTopRect,
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x0012e416 in __kernel_vsyscall ()
(gdb) c
Continuing.
[Thread 0xb690cb70 (LWP 6171) exited]
[Thread 0xb710db70 (LWP 6170) exited]
[Thread 0xb7dc1b70 (LWP 6169) exited]
[Thread 0xb610bb70 (LWP 6172) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb)

**Comment by akallabeth** [comment]
Closing due to being ancient. Reopen if this is still the case with 2.0
