### ISSUE TITLE
FreeRDP border issues with other a Table Software

### ISSUE THREAD

**Issue by MHGuser** [FreeRDP/FreeRDP#5970]
We have a  Problem with FreeRDP,
our Customer have to work with a Table Software (not Excel).
When he clicks on a box he should get a black frame around the box.
But with the FreeRDP connection he doesnt see the frame.
When he takes a screenshot on FreeRDP(where he don see the frame) it shows the frame, so the bug have definitly nothing to do with the software.

Fun fact: on excle, he can see the frame

![grafik](https://user-images.githubusercontent.com/62143260/76625493-a5f31780-6537-11ea-8f98-24e6cbf4a5ac.png)

On the screenshot is the frame visible but not when we are on the client with FreeRDP

**Comment by akallabeth** [comment]
@MHGuser could you please add a minimum of information we can work with? Telepathy is nothing we have available ;)

**Comment by MHGuser** [comment]
OS: Stratodesk "No Touch OS" on the thinClient
Terminalserver: Windowsserver 2008 R2
Table Software: ABAS

**Comment by akallabeth** [comment]
Freerdp version and commandline please

**Comment by akallabeth** [comment]
closing due to lack of information.
