### ISSUE TITLE
rdp client disconnect when send file to printer

### ISSUE THREAD

**Issue by pwflamy** [FreeRDP/FreeRDP#5978]
1) when sending any file for printing, the connection crashes
![изображение](https://user-images.githubusercontent.com/45737605/76851074-b4a03e00-6859-11ea-83d1-e2eee5cb366e.png)
2) xfreerdp -a 16 -u username -g 1024x768 --plugin rdpdr --data printer:M1005 -- 192.168.1.8
3) Windows server 2008 R2 Enterprise
4) This is FreeRDP version 2.0.0-dev5
5) Linux Mint 19 Cinnamon

P.S> Initially, the problem appeared a week ago. Our company uses remmina as an rdp client. The problem appeared on all machines that were updated with ppa: remmina-next-daily. After reinstalling with ppa: remmina-next the problem is gone.
However, today, on one of the computers, the problem returned (remmina version 1.4.1). Since remmina uses FreeRDP, I downloaded freerdp2-x11 from the repository and got the same error

**Comment by akallabeth** [comment]
@pwflamy could you please add your build configuration and retry with latest master?
This looks a lot like a few closed issues who forgot to update before filing an issue.

**Comment by pwflamy** [comment]
Complete cleaning and reinstallation from http://ppa.launchpad.net/remmina-ppa-team/remmina-next/ubuntu bionic / main amd64 freerdp2-x11 amd64 2.0.0 ~ git202002281153-0 + remmina202003012216.r3318d15.d287a1e7 ~ ubuntu18. 04.1 solve the problem
