### ISSUE TITLE
Sound forwarding resulting in a Floating point exception

### ISSUE THREAD

**Issue by gcm-explo1t** [FreeRDP/FreeRDP#5983]
When connecting from a Linux Mint 19.1 with the FreeRDP client 2.0.0-dev5 to a remote Windows Server 2019 and the sound is forwarded from the remote system, i get a Floating point exception (core dumped) the moment any sound plays.

1. FreeRDP command: xfreerdp /sound:sys:alsa /microphone:sys:alsa /dynamic-resolution /smartcard +home-drive +aero +clipboard <redacted login and server>
2. Play sound on remote Windows server
3. Hear parts of the remote sound
4. Crash

The freerdp client should just play the sound without crashing.

* Version of FreeRDP
2.0.0-dev5 (n/a)
* Command line used
xfreerdp /sound:sys:alsa /microphone:sys:alsa /dynamic-resolution /smartcard +home-drive +aero +clipboard <redacted login and server>
* output of `/buildconfig`
This is FreeRDP version 2.0.0-dev5 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RELWITHDEBINFO
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp2-dLZMDb/freerdp2-2.0.0~git202002211036=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 7.4.0
Target architecture: x64
* OS version connecting to
Windows Server 2019 (Standard)
* If available the log output from a run with `/log-level:trace` 
When run with this i get a segfault:
[09:59:42:571] [7509:7533] [DEBUG][com.freerdp.utils] - fatal_handler: signum=11
Segmentation fault (core dumped)

 - OS: Linux Mint 19.1 Tessa
- Alsa: alsa-base    1.0.25+dfsg-0ubuntu5
alsa-utils  1.1.3-1ubuntu1
gstreamer1.0-alsa:amd64  1.14.5-0ubuntu1~18.04.1

**Comment by akallabeth** [comment]
* Please add a bit more from the log, the last line is not very helpful.
* Which version of `libgsm`, `ffmpeg` et al?
* Can you try our nightly builds https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds and check if the issue persists?

**Comment by akallabeth** [comment]
Additionally, did you build the package yourself?
The configuration is a bit odd and might lead to troubles down the way (no resampler library, no image scaling support, ...)

**Comment by gcm-explo1t** [comment]
Full Log:
[log.txt](https://github.com/FreeRDP/FreeRDP/files/4354265/log.txt)


> Additionally, did you build the package yourself?
> The configuration is a bit odd and might lead to troubles down the way (no resampler library, no image scaling support, ...)
No did not package it by myself i loaded it from ppa:remmina-ppa-team/remmina-next

>     * Which version of `libgsm`, `ffmpeg` et al?
libgsm1:amd64 1.0.13-4build1
ffmpeg 7:3.4.6-0ubuntu0.18.04.1


As i didn't build it myself i don't have the toolchain here. I can try tonight.

**Comment by akallabeth** [comment]
@gcm-explo1t are you sure that is the full log? All warnings and errors are missing.
`xfreerdp <yourargs>  2>&1 |tee log.txt` generates a full log.

**Comment by gcm-explo1t** [comment]
Now called with your options:
[log.txt](https://github.com/FreeRDP/FreeRDP/files/4358710/log.txt)

**Comment by akallabeth** [comment]
@gcm-explo1t ok, not much better :/
could you try the whole thing with our nightly builds? ( https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds )

**Comment by gcm-explo1t** [comment]
OK, the nightly build (freerdp-nightly_2.0.0+0~20200305024836.778~1.gbpf65c79_amd64.deb) works, with this I get the audio from the remote maschine. However, the microphone does not work :/ It shows up in the settings as remote Microphone, but the sound is not transferred.

Log can be seen here:
[log.txt](https://github.com/FreeRDP/FreeRDP/files/4370641/log.txt)

**Comment by akallabeth** [comment]
@gcm-explo1t any reason you´re using alsa over pulse?
looks like you did not set the proper input device for mic.

**Comment by akallabeth** [comment]
closing this as it is a build issue.

**Comment by gcm-explo1t** [comment]
@akallabeth I tried pulse with the same result, the right microphone is selected, as it works in the native linux. Command line argument: /microphone:sys:pulse
It shows up in the options in the Windows Server, but it transmits no sound.
Any ideas?

**Comment by akallabeth** [comment]
@gcm-explo1t assuming you´re using the nightly build,
* did you check the volume levels (in pulse and remote windows)?
* Run with `/log-filters:com.freerdp.channels.audin.client:debug` and open the application using the microphone, the log should be flooded with messages, check which codec is used, which sample rater, ...
