### ISSUE TITLE
FreeRDP + NoTouch OS + Raspberry Pi 4 Video issue

### ISSUE THREAD

**Issue by edlarini** [FreeRDP/FreeRDP#5984]
Hi everyone,

we are testing Raspi 4 to use as Thin Client, but we have this "lag" issue since then. Can be considered a bug?

NoTouch OS 3.1.254
FreeRDP c 1 5 7 0 6 7 c c f  (according NoTouch Release Notes)

This not happen on other Thin Clients (HP, VXL), only with Raspi 4.

As you can see on video, the problem is only inside the session.

[https://youtu.be/iQ8PLOzDEyE](url)

**Comment by akallabeth** [comment]
@edlarini the video looks a lot like you´re not using optimal connection settings for a windows 10.
But most issues we encountered so far are problems with the graphics driver and bandwidth limitation between CPU and GPU on raspberry.
Another way to check for possible issues is, if you could try with `xfreerdp` manually and check which options (e.g. `/network:auto /rfx /gfx:avc444`) improve the situation?

**Comment by edlarini** [comment]
@akallabeth actually it´s Windows Server 2016, should I use these settings? Thanks.

**Comment by akallabeth** [comment]
@edlarini does not matter, it is more or less the same. yes, try them (maybe remove the `avc444` if it is slow, so you can trade bandwidth for CPU)

**Comment by edlarini** [comment]
ok tks, will give a try

**Comment by edlarini** [comment]
I tried. It didn´t work as user parameter, but it works in display settings as a graphic driver, very fast, perfect!. However the OS starts in safe mode, which is bad. I contacted Stratodesk about the safe mode issue and had this answer: 
_"we can't use any alternative driver, that solution would then only work for freeRDP but would severely hurt the performance of the enterprise clients from Citrix and VMware, so the legacy driver is no option in our case."_

:(

**Comment by akallabeth** [comment]
@edlarini so then you have the cause of the issue. can´t do much about stratodesk though.
