### ISSUE TITLE
wfreerdp Windows executable fails to launch

### ISSUE THREAD

**Issue by jdunne525** [FreeRDP/FreeRDP#5986]
Windows 10.  
Simply run the wfreerdp.exe and nothing shows up and no error messages are shown.  I ran the Jenkins build #755.
revision: cf2f674283e17c06e1bda8183186603885066527

**Comment by akallabeth** [comment]
This is a command line application, you need to provide connection arguments or start a .rdp file with it.
Running with wfreerdp.exe <your args>  >log.txt 2>&1 will write the output to a file (sorry, windows cmd limitation)

**Comment by jdunne525** [comment]
Would it kill you to add a readme.txt?  This application doesn't even pop up a console window, indicating that it is a console application,
