### ISSUE TITLE
multimon limited to 2 displays?

### ISSUE THREAD

**Issue by MikaelBertze** [FreeRDP/FreeRDP#5990]
A few weeks ago, my freeRdp install (nightly-build) stoped supporting multimon on 3 dispays. 

xfreerdp /monitor-list
      * [0] 1920x1200	+0+0
        [1] 1920x1200	+1920+0
        [2] 1920x1200	+3840+0

Previously, connecting with /multimon would automatically use my 3 displays, now it will only use display 0 and 1 default. I've tried the /monitors:0,1,2 but it still uses only 2 displays.

/monitors: 0,1,2 show remote desktop on display 0 and 1).

/monitors:1,2,0 show remote desktop on display 1 and 2.

Version: 2.0.0-dev5 (f65c79ec5)
CommandLine: 
  xfreerdp .... /multimon /monitors:0,1,2
  xfreerdp .... /multimon

* OS version connecting to: Win10

**Desktop:**
 - OS: Ubuntu 18.04

**Comment by akallabeth** [comment]
Works like a charm form me (tested win7 and win 10 remotes)

**Comment by MikaelBertze** [comment]
some time ago, monitor 0 got its resolution changed by a full screen app. I think thats when it stoped working. The resolution of monitor 0 was changed back (as can be seen in the /monitor-list output).

**Comment by akallabeth** [comment]
@MikaelBertze yes, point being it looks like there is something with your local setup that is causing this I can´t reproduce on my 2 machines here.

**Comment by MikaelBertze** [comment]
Some more info:
If i exit full screen, I see 3 desktops with resolution set to my displays resolution. When moving over to fullscreen only monitor 0 and 1 gets displayed.

IUf you can't reproduce I guess my system is messed up in some way. I'll post if I find something.
