### ISSUE TITLE
neither swscale nor libcairo detected, compiling without image scaling   support

### ISSUE THREAD

**Issue by MarkLTZ** [FreeRDP/FreeRDP#5999]
Compiling on Centos8 I have this warning:

-- Checking for module 'cairo'
--   Found cairo, version 1.15.12
-- Found Cairo: /usr/lib64/libcairo.so  
CMake Warning at libfreerdp/CMakeLists.txt:102 (message):
  neither swscale nor libcairo detected, compiling without image scaling
  support!

#dnf list installed cairo cairo-devel
Installed Packages
cairo.x86_64                                                                1.15.12-3.el8                                                           @AppStream
cairo-devel.x86_64                                                          1.15.12-3.el8                                                           @AppStream

Could you please help me?

Thanks,
Mark

**Comment by akallabeth** [comment]
@MarkLTZ install `libcairo2` or `libswcale` development heraders.
Please use the mailing list or IRC for support questions.

**Comment by MarkLTZ** [comment]
@akallabeth libaciro2 or libswcale are not available for Centos8 or RHEL8

[root@localhost ~]# dnf list libcairo2
Last metadata expiration check: 0:34:53 ago on Fri 27 Mar 2020 03:53:05 PM CET.
Error: No matching Packages to list
[root@localhost ~]# dnf --enablerepo=* --disablerepo=c8-media-BaseOS --disablerepo=c8-media-AppStream whatprovides */libcairo2*
Last metadata expiration check: 0:34:54 ago on Fri 27 Mar 2020 03:53:22 PM CET.
Error: No Matches found
[root@localhost ~]# dnf --enablerepo=* --disablerepo=c8-media-BaseOS --disablerepo=c8-media-AppStream list *cairo2*
Last metadata expiration check: 0:35:34 ago on Fri 27 Mar 2020 03:53:22 PM CET.
Error: No matching Packages to list

**Comment by akallabeth** [comment]
Then you have no image scaling support (high dpi related stuff)
Nothing we can change here ;)
