### ISSUE TITLE
"SSL_CTX_use_RSAPrivateKey_file failed" and segfault

### ISSUE THREAD

**Issue by yblein** [FreeRDP/FreeRDP#600]
Hi,

I have an issue with the server on client connection :
<pre>
$ ./xfreerdp-server
Listening on 0.0.0.0 port 3389.
bind: Address already in use
We've got a client 127.0.0.1
Requested protocols: TLS(Y) NLA(n) RDP(n)
SSL_CTX_use_RSAPrivateKey_file failed
Failed to check freerdp file descriptor
Client 127.0.0.1 disconnected.
zsh: segmentation fault  ./xfreerdp-server
</pre>

I'm under Archlinux `Linux harlie 3.3.6-1-ARCH #1 SMP PREEMPT Sun May 13 10:52:32 CEST 2012 x86_64 GNU/Linux`, running the latest FreeRDP client/server from Github and my OpenSSL version is `1.0.1c 10 May 2012`. I didn't find out how to get it working.

Here is the gdb stacktrace:
<pre>
#0  0x00002aaaac74e221 in SSL_shutdown () from /usr/lib/libssl.so.1.0.0
#1  0x00002aaaab53580d in tls_disconnect (tls=0x2aaab0050c40) at /tmp/freerdp-1.0.1/libfreerdp-core/tls.c:125
#2  0x00002aaaab5387a2 in transport_disconnect (transport=0x2aaab0002700) at /tmp/freerdp-1.0.1/libfreerdp-core/transport.c:74
#3  0x00002aaaab53e305 in freerdp_peer_disconnect (client=0x607150) at /tmp/freerdp-1.0.1/libfreerdp-core/peer.c:287
#4  0x0000000000404189 in xf_peer_main_loop (arg=0x607150) at /tmp/freerdp-1.0.1/server/X11/xf_peer.c:697
#5  0x00002aaaacd86e0e in start_thread () from /lib/libpthread.so.0
#6  0x00002aaaad4a91ed in clone () from /lib/libc.so.6
</pre>

Also I had another issue that I solved: with the NVidia proprietary driver, you need to add
<pre>	Option		"AllowSHMPixmaps"	"1"</pre>
in your xorg.conf in order to squeeze an error with SHM pixels on the server.

**Comment by hardening** [comment]
@tfar the server in FreeRDP has not the goal to be a production RDP server. It's more a toy to test server-side components.

**Comment by bmiklautz** [comment]
@hardening I believe this segfault is already fixed on master (but I'll verify that to be sure). Even if it isn't aimed to be a production ready server  it shouldn't segfault :) but should at least print an error message.

**Comment by akallabeth** [comment]
@hardening @bmiklautz Any news on this?

**Comment by hardening** [comment]
AFAICT it has been fixed, but feel free to reopen if the bug still occurs.
