### ISSUE TITLE
No audio via FreeRDP but works on Remmina 

### ISSUE THREAD

**Issue by maciey** [FreeRDP/FreeRDP#6000]
Guys please help me enabling audio via xfreeRdp. It works for me better then remmina. Only issue I have is audio

I can hear remote (Windows 7) PC audio on my Linux box only when Im connecting via remmina. Can manage same via xfreeRdp command line. 

Is there any way to see what params Remmina passes to xfreerdp ?
any other options I shoudl try ?

Im using v.1.1.0-beta1

what I've tried:

/audio-mode:1
/sound:sys:alsa 
/sound 
--plugin drdynvc --data audin -- server
--plugin rdpsnd --data pulse -- server
/sound /microphone:sys:alsa

Nothing of above was working...

PS my linux laptop is My laptop is Lenovo x220

**Comment by akallabeth** [comment]
* Where did you get freerdp from?
* Did you try a newer version, e.g. version 2 release candidates?
* Did you try our nightly builds?

**Comment by maciey** [comment]
I just executed below command on my Mint box:
sudo apt-get install freerdp-x11
I think It came from standard repositories 

How I can get version 2 / nightly ? Is there any repo or I need compile it from sources

**Comment by akallabeth** [comment]
@maciey can't tell about mint, but debian package works.
/sound is the correct option.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by maciey** [comment]
Thank you!
Version 2 seems working now!

**Comment by akallabeth** [comment]
Ok, good to know.
