### ISSUE TITLE
Cannot connect using rdesktop

### ISSUE THREAD

**Issue by maordadush** [FreeRDP/FreeRDP#6001]
**Describe the bug**
I am attempting to connect to Windows 2019 machine over freerdp proxy When I use rdesktop with hostname parameter, but the connection is failing.
I got this error:
[ERROR][com.freerdp.core.tpkt] - [mcs_recv_erect_domain_request] **Received invalid TPKT header length 12, 1 bytes too long!**
[14:31:05:832] [54493:54649] [ERROR][com.freerdp.core.peer] - peer_recv_callback: CONNECTION_STATE_MCS_CONNECT - rdp_server_accept_mcs_erect_domain_request() fail 

One important thing to notice, when I am using freerdp old version the connection succeeds.  thats way I assume that the issue is related to latest commits.

**To Reproduce**

1. Use rdesktop with minimal configuration
2. Observe result

**Expected behavior**
RDP session opens as expected.

**Actual behavior**
RDP session failed.

**Application details**

Version of rdesktop: 1.9.0
Command line used: rdesktop `/<host>`
OS version connecting to: Windows server 2019

OS: Kali Linux

**Comment by akallabeth** [comment]
Which version of freerdp do you use?
There was an issue solved a month back, so this might be important.

**Comment by maordadush** [comment]
I'm using the latest master version.

**Comment by akallabeth** [comment]
@maordadush looks like a bug in `rdesktop`.
The `[MS-RDPBCGR] 4.1.5 Client MCS Erect Domain Request PDU` sample data is `03 00 00 0c f0 80 04 01 00 01 00` but we receive `03 00 00 0c f0 80 04 00 01 00 01`

According to `2.2.1.5 Client MCS Erect Domain Request PDU` the whole packet must be 12 bytes long.

So, when reading the input data the encoded PER integer values are short and therefore parsing is aborted.

**Comment by AndreyBarmaley** [comment]
[RDPBCGR]2.2.1.6 - mcsEDrq 5 bytes. (one byte id + two bytes height + two bytes interval)
wrong in mcs_recv_erect_domain_request/mcs_send_erect_domain_request:
```
        if (!per_read_integer(s, &subHeight)) /* subHeight (INTEGER) */
                return FALSE;

        if (!per_read_integer(s, &subInterval)) /* subInterval (INTEGER) */
                return FALSE;
```
I think it is necessary to use: per_read_integer16

**Comment by akallabeth** [comment]
@AndreyBarmaley 
No, from `ITU-T T125`:
```
ErectDomainRequest  ::=  [APPLICATION 1] IMPLICIT SEQUENCE 
{ 
 subHeight    INTEGER (0..MAX), 
      --  height in domain of the MCSPDU transmitter 
 subInterval    INTEGER (0..MAX) 
      --  its throughput enforcement interval in milliseconds 
}
```

**Comment by AndreyBarmaley** [comment]
how about:
```
The [MS-RDPBCGR] 4.1.5 Client MCS Erect Domain Request PDU sample data is 03 00 00 0c 02 f0 80 04 01 00 01 00
```

**Comment by akallabeth** [comment]
Confirms my argument. The `length` of the integer is `1` , the value `0`

**Comment by akallabeth** [comment]
@AndreyBarmaley filed a bug with `rdesktop`, nothing we can fix.

**Comment by AndreyBarmaley** [comment]
I sent them pull request. Thank you.
