### ISSUE TITLE
freeRDP: Black screen / rDesktop works well

### ISSUE THREAD

**Issue by maciey** [FreeRDP/FreeRDP#6002]
Hello

I have issue with one of my remote PC - almost every time Im connecting using **freeRDP** it shows me **black screen**. No matter I did (i tried different  depth of colours, glyph cashing, disable reconnection etc). I spent few hrs experimenting. I had similar problems with Remmina 

But I don't have such issues when Im using **rDesktop** command line.

Difference Ive noticed is **rDesktop** displays Windows Welcome (login) screen where I can select user and type password, but freeRDP forces me to pass user name via script and type password in terminal window.

> So is there any option do force similar behaviour  (to rDesktop) ?

I think PC im connecting have issue with slow login, so displaying login window gives protocol / apps some extra time.

Im using latest (2nd) version of FreeRdp

**Comment by akallabeth** [comment]
@maciey could you please add your command line, what you are connecting to and the output of /buildconfig?
The description is a bit vague to answer it ;)
Btw, rdesktop does not use nla, maybe you have an issue with that?

**Comment by maciey** [comment]
Below commands I use connecting to other PCs

> xfreerdp +clipboard /size:1440x900 /cert-ignore -themes -wallpaper /bpp:16 /u:user_name /v:PC_IP
> xfreerdp +clipboard /f /cert-ignore -themes -wallpaper /bpp:16 /u:user_name /v:PC_IP
> 

regarding rDesktop - no matter what extra options I put - works every time. Now Im using this:
> rdesktop -f PC_IP

However my main question was if it would be possible to do not enter any user name / password via terminal but display Windows Login screen and select user /  type pass there - as it happens with rDesktop ?

I meant this one:

![image](https://user-images.githubusercontent.com/5410448/77888952-53bb3180-726d-11ea-9b92-3ffd6dcc10fa.png)

**Comment by akallabeth** [comment]
@maciey yes, that is the security option ;)
you have:
* NLA
* TLS
* RDP

So, NLA requires credentials to connect, the others do not.

**Comment by akallabeth** [comment]
so, since this looks like a support issue, I´m closing this.

**Comment by maciey** [comment]
Oh Ive never looked into security option ! Thanks!

**Comment by maciey** [comment]
Unfortunately this didnt help .. :( 

Ive tried NLA security option but freeRdp still asks me in terminal for user password
