### ISSUE TITLE
Add vcpkg installation instructions 

### ISSUE THREAD

**Issue by NancyLi1013** [FreeRDP/FreeRDP#6004]
`freerdp `is available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `freerdp `and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `freerdp`, ready to be included in their projects.

We also test whether our library ports build in various configurations (dynamic, static) on various platforms (Linux, Windows: x86, x64) to keep a wide coverage for users.

I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/freerdp/portfile.cmake). We try to keep the library maintained as close as possible to the original library.

I'm trying to add vcpkg installation instructions but I couldn't find the related docs in code item except for on `Wiki` page.

Could you please help add the following contents to this port?

Installing and building freerdp via vcpkg

You can download and install freerdp using the [vcpkg](https://github.com/Microsoft/vcpkg) dependency manager:

      git clone https://github.com/Microsoft/vcpkg.git
      cd vcpkg
      ./bootstrap-vcpkg.sh
      ./vcpkg integrate install
      vcpkg install freerdp

The freerdp port in vcpkg is kept up to date by Microsoft team members and community contributors. If the version is out of date, please [create an issue or pull request](https://github.com/Microsoft/vcpkg) on the vcpkg repository.

Thanks,
Nancy

**Comment by akallabeth** [comment]
@NancyLi1013 well, add something to the wiki ;)

**Comment by NancyLi1013** [comment]
@akallabeth 
Thanks for your so quick response.
