### ISSUE TITLE
Remoteapp windows (A drop down menu window) does not refresh properly

### ISSUE THREAD

**Issue by akklaw** [FreeRDP/FreeRDP#6015]
**Describe the bug**
I have an application that is initialized as "WS_EX_NOACTIVATE || WS_EX_TOOLWINDOW" type and there is a system tray icon in windows OS.  If I launch the application as remoteapp, there is a tab menu inside the application, when navigate the tab menu, the application window does not refresh.  If the same application launch inside a Remote desktop session, the same tab menu navigation does refresh the application window properly.

**To Reproduce**
1) launch an remoteapp  as WS_EX_TOOLWINDOW || WS_EX_NOACTIVATE type window in xf_window.c, 
2) The remoteapp contains tab menu within the application
3) navigate the tab menu to refresh the content within the window

**Expected behavior**
The content within the window refresh 
Actual: the content within the window does not refresh.
If the application is launched within a remote desktop session, it refresh properly.

**Application details**
* Version of FreeRDP - master branch as of 3/31/2020
* OS version connecting to - windows server 2016

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - RHEL 7.6
 - Browser [e.g. chrome, safari] firefox
 - Version [e.g. 22] RHEL 7.6

**Comment by akallabeth** [comment]
Duplicates #498
