### ISSUE TITLE
Session binding option for the same user in remoteapp

### ISSUE THREAD

**Issue by akklaw** [FreeRDP/FreeRDP#6016]
**Is your feature request related to a problem? Please describe.**
I would like to see if we can launch remoteapp with session binding mode.  This means when an user launch a remoteapp, a new session is created. If the same user launch second app, can we reuse the same session to launch application.  The problem I am trying to address is that when an smartcard app is launch, another app can be launched and make uses of smartcard data/PIN etc.

**Describe the solution you'd like**
**Describe alternatives you've considered**
This seems to be not a problem with remote desktop session, I can launch application within RD and the session binding can be achieved.  However this does not help in remoteapp case.

**Comment by akallabeth** [comment]
Duplicates #498
