### ISSUE TITLE
wl_display@1: error 1: invalid arguments for wl_surface@10.attach

### ISSUE THREAD

**Issue by chakuzo** [FreeRDP/FreeRDP#6018]
I found a possible bug in uwac-input.c in the function set_cursor_image(...). 

The problem is that this function is called twice before the on_buffer_release(...) is called. I tested it with a boolean which I set after wl_surface_commit(...) and reset after wl_buffer_destroy(...).

This can happen with particularly fast touch movements on different surfaces. 

Error output:
proxy 0x8129fc0 already has listener
wl_display@1: error 1: invalid arguments for wl_surface@10.attach

I'm a little unsure how to fix this. I don't know, if there is a smarter way than to set a boolean as reminder if the buffer is already destroyed.

**Comment by chakuzo** [comment]
When I check if a listerner is already registered and make no wl_surface_attach anymore, this fix the situation for me.

Commit: 249dce954e896aa3ff135b7882c56ff35a3384b6

The problem always comes if the seat->pointer_type is 0. Because this buffer will be not destroyed.

**Comment by akallabeth** [comment]
@chakuzo would be nice if you could create a pr, github is a bit messy with showing which fork the commit is from.
