### ISSUE TITLE
Date for 2.0.0-rc5 or 2.0.0

### ISSUE THREAD

**Issue by timtas** [FreeRDP/FreeRDP#6020]
Since the latest release, 2.0.0-rc4 is 16 months old and about 1500 commits have been made to master since then, I wanted to ask if there are any plans for a new release?

I would however like to state that I'm generally very happy with 2.0.0-rc4 and want to thank all the contributors to this project.

**Comment by bmiklautz** [comment]
Tracking this under #5608.
