### ISSUE TITLE
media play

### ISSUE THREAD

**Issue by lugeliu** [FreeRDP/FreeRDP#6032]
When I use freerdp to connect to win7, the full-screen playback of win7 local video is not good. When I play the local video on small screen, the effect is very good.why?

**Comment by lugeliu** [comment]
my freerdp version is 2.0.0-dev5
xfreerdp -u xxx -p xxx -v xxx -f -sound

**Comment by hardening** [comment]
Can you give us more details, what do you mean by "is not good" ? What is your screen resolutions, your hardware ? We need more information to give an accurate answer.

**Comment by lugeliu** [comment]
When I use freerdp to connect to win7, the local video of win7 is very stuttering when playing in full screen, but not when playing in small screen
My win7 resolution is 1920*1080
