### ISSUE TITLE
http does not redirect to https

### ISSUE THREAD

**Issue by Neustradamus** [FreeRDP/FreeRDP#6037]
Can you redirect to https?
- http://freerdp.com/
- http://www.freerdp.com/

It does not work (cert problem):
- https://freerdp.com/

It is better to have the website in https://freerdp.com/ without www.
And 3 automatic redirections to.

**Comment by bmiklautz** [comment]
@Neustradamus thanks for the feedback.
We are using github pages for our homepage and have enforced https for www.freerdp.com now.
As for the the apex domain I'll see if I found a solution.

**Comment by bmiklautz** [comment]
For now we stick with www.freerdp.com. But all sites are now redirected to https://www.freerdp.com:
* http://freerdp.com
* https://freerdp.com
* http://www.freerdp.com

Would you verify this from your site?

**Comment by Neustradamus** [comment]
@bmiklautz: Thanks for your changes!
It is not possible to have the main website in https://freerdp.com/ instead of https://www.freerdp.com/?

Currently there is always a cert problem -> https://freerdp.com/

**Comment by agowa338** [comment]
The Certificate problem is appears to be fixed (at least over here, hard to tell because of the nature of cdns). Could you explain why you think without the www is better? I mean google chrome does strip it automatically anyway, so most people will never see it anyway.

**Comment by Neustradamus** [comment]
@agowa338: Thanks for your reply!

All browsers have an option to keep all the link.

And it is better to promote and for SEO...

**Comment by bmiklautz** [comment]
@Neustradamus the initial issue is fixed. http is redirected to https and https://freerdp.com works now as well.
Thank you for your issue report and input.

**Comment by Neustradamus** [comment]
@bmiklautz: Thanks but there are always some problems:
- http://freerdp.com/ is redirected to https://www.freerdp.com/ instead of https://freerdp.com/
- http://www.freerdp.com/ is not redirected
- https://freerdp.com/ is redirected to https://www.freerdp.com/ (the base must be https://freerdp.com/)
- https://www.freerdp.com/ is not redirect to https://freerdp.com/

Please reopen before the complete solution to https://freerdp.com/.

**Comment by Neustradamus** [comment]
@bmiklautz: Have you looked all problems that I have noted previously?

**Comment by bmiklautz** [comment]
@Neustradamus 

> * http://freerdp.com/ is redirected to https://www.freerdp.com/ instead of https://freerdp.com/
On purpose. This saves one redirect.

> * http://www.freerdp.com/ is not redirected
Please retry. HTTPs is enforced for the github page. So I would be surprised if that doesn't work.

> * https://freerdp.com/ is redirected to https://www.freerdp.com/ (the base must be https://freerdp.com/)
Same as above. I don't see any reason this *must* be https://freerdp.com

> * https://www.freerdp.com/ is not redirect to https://freerdp.com/
> Please reopen before the complete solution to https://freerdp.com/.
As explained above we stick with www.freerdp.com (at least for now).

**Comment by Neustradamus** [comment]
@bmiklautz: Thanks, http://www.freerdp.com/ is now redirected to https://www.freerdp.com/ !

I will open a new ticket to remove "www.".
