### ISSUE TITLE
Multimedia Rederection additional codec support: FLV

### ISSUE THREAD

**Issue by shwarmy** [FreeRDP/FreeRDP#604]
What are the plans for adding additional codecs to freerdp for MMR?

**Comment by hardening** [comment]
mkv is a container, and flash is supported by ffmpeg but not listed here: https://msdn.microsoft.com/en-us/library/windows/desktop/dd757532%28v=vs.85%29.aspx so I guess it doesn't have an guid...

Can we close this issue ?

**Comment by shwarmy** [comment]
yes

On Thu, May 7, 2015 at 3:18 PM, Hardening <notifications@github.com> wrote:

> mkv is a container, and flash is supported by ffmpeg but not listed here:
> https://msdn.microsoft.com/en-us/library/windows/desktop/dd757532%28v=vs.85%29.aspx
> so I guess it doesn't have an guid...
>
> Can we close this issue ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FreeRDP/FreeRDP/issues/604#issuecomment-100005063>.
>



-- 

*______________________________________*


* Nick Swanzy*

Email:    shwarmy@gmail.com

Google Talk: shwarmy@gmail.com


Phone:   (979) 255-0585

*______________________________________*
