### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by lugeliu** [FreeRDP/FreeRDP#6042]
![image](https://user-images.githubusercontent.com/51041230/78972429-560c6e00-7b40-11ea-866b-7898611925dd.png)

**Comment by hardening** [comment]
Well just don't compile with opensles support if you don't have it...

**Comment by lugeliu** [comment]
can you tell me the reason

**Comment by hardening** [comment]
@lugeliu we took time creating a bug reporting form, why haven't you take from _your_ time, filing the information we need to answer questions ?
More informations here => https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by lugeliu** [comment]
ok.i am just a student,i  don't know how to find what I need.sorry
