### ISSUE TITLE
Investigate OpenH264 use of DecodeFrameNoDelay

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#6051]
#6045 reported issues (and there have been some reports before that) that openH264 has issues with newer GFX modes.

Reading through https://github.com/cisco/openh264/issues/3079 gave the impression it may be necessary to use `DecodeFrameNoDelay` instead of `DecodeFrame2`

If that does not work, it may be required to limit `GFX` capability announcement by backend

**Comment by ganeshjkale** [comment]
@akallabeth /gfx-h264 Quality of video play on youtube performance has been degraded (10-20 percent) after 2.0.0-dev5 (00eabb2c9)
H264 version :- openh264-1.8.0
verified with 2.2.0 and Master branch also ( commit e96ef524c5e8fd3018f55104fe3a30463e7cff85)

**Comment by akallabeth** [comment]
@ganeshjkale please do not hijack issues for your questions, use IRC or mailing list if you have such.

**Comment by akallabeth** [comment]
https://github.com/cisco/openh264/pull/3319
