### ISSUE TITLE
vision impairment feature request

### ISSUE THREAD

**Issue by shwarmy** [FreeRDP/FreeRDP#606]
I would like to see if in a future revision support for vision impairment could be added.  In windows 7 a feature was added to allow users to change DPI.  After some research i have found that microsoft intentionally left the feature out the allow users to change DPI when connecting via RDP.  The work around I have been able to find on the windows thin client was to manually set the maximum screen resolution to a lower resolution before connecting to the machine with RDP.

I humbly request the following feature.

I would like to be able to set the full screen resolution to a lower resolution in the command line settings for freerdp.  Currently if i set full screen in the command line section it by default use's the monitors native resolution.  If i specify the resolution to a lower then native resolution the rdp window is not full screen.  

Thank you for your time.

**Comment by bmiklautz** [comment]
I think ` /smart-sizing[:<width>x<height>]  Scale remote desktop to window size` is what have asked for. In combination with the  `/size` parameter you can scale 'up' or 'down'.
