### ISSUE TITLE
Recommend disabling spin lock on macOS: RFX thread pool spends all CPUs in spin loops

### ISSUE THREAD

**Issue by trishume** [FreeRDP/FreeRDP#6066]
**Describe the bug**
This spin loop in winpr's EnterCriticalSection performs terribly on macOS, I recommend disabling the spin loop on macOS [in the same way/place it's disabled on Linux](https://github.com/FreeRDP/FreeRDP/blob/71feb974ac9854a6df390ed17715080f12dd1ad0/winpr/include/winpr/synch.h#L133). xfreerdp consumes all my CPU cores when scrolling in the RDP session stuck in millions of `sched_yield` syscalls because of the `EnterCriticalSection` on the queue used for the RFX thread pool.

**To Reproduce**
I haven't minimized which of these pieces are necessary to reproduce.
1. Start a 4k xrdp session with `/rfx` and `/gfx`
2. Open a maximized Chrome window and scroll a Wikipedia page

**Expected behavior**
xfreerdp spends time doing useful work not syscalls.

**Screenshots**

![Screen Shot 2020-04-12 at 1 07 03 PM](https://user-images.githubusercontent.com/887610/79075294-ef15c300-7cbf-11ea-9d18-dc3dba2ae96e.png)
![Screen Shot 2020-04-12 at 1 08 30 PM](https://user-images.githubusercontent.com/887610/79075297-f6d56780-7cbf-11ea-8a7f-2921e377635f.png)

**Application details**
* Version of FreeRDP: 2.0.0-rc4 from homebrew
* Command line used: `xfreerdp /v:192.168.247.128 /rfx /gfx /u:tristan +glyph-cache /geometry /f /w:3840 /h:2160`
* OS version connecting to: NixOS xrdp

**Desktop (please complete the following information):**
 - OS: macOS Catalina

**Comment by akallabeth** [comment]
Akready on that, there seems to be another issue with clang11 inserting illegal instructions under certain circumstances for the spinloop.

**Comment by trishume** [comment]
Cool. Is it not a good idea to just disable the spin loop on macOS like it's disabled for Linux?

I must say I was pleased to discover that FreeRDP uses a thread pool for RFX decoding, even if it doesn't work properly on macOS. I know xrdp doesn't use one for encoding, and I think the Windows RDP server might not use one either. I'm curious whether the Windows RDP client does.
