### ISSUE TITLE
Problem detecting libcairo while building

### ISSUE THREAD

**Issue by weberhofer** [FreeRDP/FreeRDP#6067]
Building version 2.0.0 on different openSUSE versions shows the following lines while configuring, looks like a bug:
```
-- Checking for module 'cairo'
--   Found cairo, version 1.16.0
-- Found Cairo: /usr/lib64/libcairo.so  
CMake Warning at libfreerdp/CMakeLists.txt:102 (message):
   neither swscale nor libcairo detected, compiling without image scaling
   support!
```

**Comment by akallabeth** [comment]
The message is a bit misleading, yes. 
Should be more in the lines of `-DWITH_CAIRO=OFF -DWITH_SWSCALE=OFF`

**Comment by weberhofer** [comment]
Thanks, @akallabeth for reponding!
