### ISSUE TITLE
No sound redirection in iOS

### ISSUE THREAD

**Issue by bzyp** [FreeRDP/FreeRDP#6083]
I tried the following Settings，But it doesn't work

Settings - > DeviceRedirection = YES;
Settings - > SupportDynamicChannels = YES;
Settings - > RemdeskVirtualChannel = YES;
Settings - > AudioPlayback = YES;
Settings - > AudioCapture = YES;
Settings - > RedirectClipboard = NO.
Settings - > RedirectPrinters = NO.
Settings - > RedirectSmartCards = NO.
Settings - > RedirectDrives = YES;
Settings - > RedirectHomeDrive = NO.
Settings - > DynamicDaylightTimeDisabled = YES;

I noticed these files in the project，Can they work?
rdpsnd_ios.c   TPCircularBuffer.c

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
