### ISSUE TITLE
Argparse mixup

### ISSUE THREAD

**Issue by stdedos** [FreeRDP/FreeRDP#6084]
**Describe the bug**
```console
→ xfreerdp "/drives" "/drive:Downloads,${HOME}/Downloads" "/clipboard" "/dynamic-resolution" 192.168.1.2 | head
[20:03:46:465] [29059:29059] [ERROR][com.winpr.commandline] - Failed at index 1 [/drives]: Invalid sigil
```

When it should be: Cannot find server / file to connect to (?)

**Expected behavior**

Writing `/v:192.168.1.2` instead works fine

**Application details**
* Version of FreeRDP
  ```
  This is FreeRDP version 2.0.0-dev5 (f65c79ec5)
  ```
**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu bionic

**Comment by akallabeth** [comment]
Problem is legacy command line here, once we dump that we can print out better errors.

**Comment by stdedos** [comment]
Are you planning to accept "typical" argument separators, like `-/--`, or will they always inherit of Windows?

**Comment by akallabeth** [comment]
@stdedos there is some limited support, but we need to be careful here.
The last change did stir up a lot of discussion and detecting which syntax is used is very error prone.
We´ll most likely stick to one syntax for good to avoid a lot of issues (and wasted time) like this one.

**Comment by rustamabdullaev-maandag** [comment]
`xfreerdp` arguments format is very peculiar... Please make it more UNIX-like :) And let's phase out the legacy syntax already.

**Comment by akallabeth** [comment]
error handling was improved with 3.x series.
reopen or create a new issue if there are still issues.
