### ISSUE TITLE
Inconsistent mouse wheel scroll behavior on Wayland

### ISSUE THREAD

**Issue by yol** [FreeRDP/FreeRDP#6087]
**Describe the bug**
Mouse wheel scrolling is wrong on Wayland. Scrolling down works perfectly, but scrolling up only scrolls about a quarter of the way it would scroll down. Very annoying :-) Everything is fine on X11 (even with Xwayland)

**To Reproduce**
1. Connect to RDP server with wlfreerdp
2. Open a document
3. Use the mouse wheel to scroll down a few times
4. Use the mouse wheel to scroll up a few times

**Expected behavior**
Scrolling down and up scrolls by the same amount of lines.

**Screenshots**
-

**Application details**
* FreeRDP git 971be4fe9
* `wlfreerdp /u:<user> /v:<host>`
* `This is FreeRDP version 3.0.0-dev (971be4fe9)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=ON WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 9.3.0
Target architecture: x64
`
* Server is Windows 10 Version 1903
* [wlfreerdp-log.txt](https://github.com/FreeRDP/FreeRDP/files/4485221/wlfreerdp-log.txt)

**Desktop (please complete the following information):**
 - OS: Linux Manjaro

**Comment by yol** [comment]
I get +-10 "steps" on scrolling with the axis event, which does not seem to be enough for Windows to behave appropriately.

When I override with 0x78 (the value on X11) here:

https://github.com/FreeRDP/FreeRDP/blob/7733fe7a8a7d96b42699690d6a8d07d782f084a8/client/Wayland/wlf_input.c#L174

It works as expected. Not a nice solution though.

**Comment by akallabeth** [comment]
@yol looks like a correct patch, can you create a pr for that?

**Comment by yol** [comment]
Not sure it is the way to go though - it would degrade the scrolling experience with touch pads, for example, because they are continuous and don't send only discrete steps.

**Comment by akallabeth** [comment]
@yol what dou you mean wit continoous? Everything in a computer is discrete ;)
Already getting smaller/bigger numvers depending on hw and acceleration

**Comment by yol** [comment]
Well, scrolling via touchpad is arguably more continuous than discrete wheel steps (which are discrete also in the real world, while for touchpad this is not the case). So for wheel scrolling, you will get 10 or 15 as value on Wayland (depending on the compositor...). For touchpad scrolling, you'll get significantly smaller values depending on how "fast" you are scrolling, but you will get lots more of those events.

Touchpad scrolling over RDP will probably be horrible if you just replace the value with 0x78 without further adjustments. How does Windows handle this natively?

**Comment by akallabeth** [comment]
Ah, I thought you found a fux with abs values?

**Comment by akallabeth** [comment]
Other than that, you might want to scale (range of wayland events to rdp event range)

**Comment by akallabeth** [comment]
https://wayland.freedesktop.org/libinput/doc/latest/development.html#using-libinput-as-library has some information about the event and how to use it.

**Comment by geext-dk** [comment]
I have the same problem, both with a touchpad and a mouse wheel.
