### ISSUE TITLE
Error Keyboard mapping - [ERROR][com.freerdp.client.x11] Unknown key with X keycode

### ISSUE THREAD

**Issue by loziomangra** [FreeRDP/FreeRDP#6093]
I'm using 

CentOS 6
freerdp (ver. 2.0.0)
TigerVNC server (ver. 1.1.0)
websockyfi (ver. 0.6.0)
MS-Windows 7 and later
An Italian keyboard layout

During a xfreerdp session, launched by xvnc starter, applications on the MS-Windows hosts behave as if a US or ENG layout keyboard had been bad configured so that, if I expect a o grave (ò) to appear in any Microsoft text application, I get nothing (with the error "[16:31:58:063] [13618:13640] [ERROR][com.freerdp.client.x11] - Unknown key with X keycode 0xff" on the vnc logs).
As well as, if I expect an AT symbol (@) I get a double quote and so on for many symbols and characters.

**Comment by akallabeth** [comment]
duplicates #4215
