### ISSUE TITLE
Replace Misleading 'certificate changed' warning and help user to compare fingerprints

### ISSUE THREAD

**Issue by stsichler** [FreeRDP/FreeRDP#6099]
**Is your feature request related to a problem? Please describe.**
Commit 9c999b7135401b15d6fe81bceb7fec269aa72bdb changed fingerprint generation from SHA1 to SHA256. As the changelog already states, this invalidated all entries in the known_hosts2 file.
As these entries are not deleted, but still persist with SHA1 fingerprints, a warning is presented to the user at the next connection attempt, stating that _"the certificate of the server **changed** (...) This may indicate that the certificate has been tampered with. Please contact the administrator (...)"_ implying that this may be caused by a man-in-the-middle attack. 
**This is misleading and terrifying the user for no reason**, because not the certificate itself changed, but only the local fingerprint hashing algorithm changed.
In addition, only the SHA256 fingerprint of the server certificate is presented to the user.
Unfortunately **Windows 10's Certificate Manager is only capable of presenting SHA1 fingerprints to the user**. so it is not obvious in the first place, whether the certificate still matches the one of the RDP server or not.
 
**Describe the solution you'd like**
If a (SHA256) fingerprint mismatch is detected, FreeRDP could check whether the SHA1 fingerprint of the server certificate still matches the entry in known_hosts2. If so, and _only_ in this case, the terrifying warning could be replaced by some smoother warning like
_"the fingerprint entry in our database of known hosts needs to be updated from SHA1 to SHA256, please check whether the server certificate is still correct"_.
In addition, both the SHA256 **and** SHA1 fingerprints of the certificate could be printed. This simplifies checking whether the server certificate may still be correct. Of course, the user would still have to check whether the SHA256 fingerprint also matches to be really sure.

**Describe alternatives you've considered**
An alternative would be to remove all SHA1 entries from known_hosts2 or ignore them as if the host was completey unknown.
But this would also make the user feel unsure at the next connection attempt when the user still believes that he is connecting to a well-known host.

**Additional context**
Plase consider that the freerdp2 update may be automatic, so the user never read the changelog and is not aware of the change in fingerprint representation from SHA1 to SHA256 and its consequences.

**Comment by stsichler** [comment]
@akallabeth Wow, you're very fast! THANK YOU!

**Comment by akallabeth** [comment]
@stsichler found an easy solution that does not break API for 2.0 releases, you´re lucky. If you could test it and report back if it works (best answer below the pr) that would be great.
