### ISSUE TITLE
OpenIndiana version 2.0.0 build fails (2.0.0-rc4 had no problems)

### ISSUE THREAD

**Issue by 3eka** [FreeRDP/FreeRDP#6105]
Hi all,

I was able to compile (w/o any intervention) version 2.0.0-rc4 on OpenIndiana, with GCC 9 compiler suite (only 32 bit one).
Now, I have tried 2.0.0 - andfaced with compilation problem....

**Describe the bug**
C program channels/rdpdr/client/rdpdr_main.c, line 583 contains
```
#include <mntent.h>
```
So, first failure was missing header file. On OpenIndiana it could be found with:
```
#include <sys/mntent.h>
```
Then (with that changed), compilation fails with:
```
[ 75%] Building C object channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/rdpdr_main.c.o
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c: In function 'handle_hotplug':
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c:666:16: warning: implicit declaration of function 'getmntent' [-Wimplicit-function-declaration]
  666 |  while ((ent = getmntent(f)) != NULL)
      |                ^~~~~~~~~
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c:666:14: warning: assignment to 'struct mntent *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  666 |  while ((ent = getmntent(f)) != NULL)
      |              ^
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c:669:25: error: dereferencing pointer to incomplete type 'struct mntent'
  669 |   const char* path = ent->mnt_dir;
      |                         ^~
gmake[2]: *** [channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/build.make:89: channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/rdpdr_main.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2727: channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
```

**Application details**
* Version of FreeRDP
2.0.0
* Command line used
```
export CC=/usr/gcc/9/bin/gcc
export CXX=/usr/gcc/9/bin/g++
export CFLAGS='-m32 -I/usr/include -I/usr/gnu/include -I/usr/include/readline -I/usr/include/ncurses'
export CXXFLAGS='-m32 -I/usr/include -I/usr/gnu/include -I/usr/include/readline -I/usr/include/ncurses'
export 'LDFLAGS=-m32 -R/usr/gnu/lib -R/usr/lib -L/usr/gnu/lib -L/usr/lib'
rm -rf bld && mkdir bld && cd bld
cmake .. -DWITH_THIRD_PARTY=ON -DWITH_SERVER=ON -DCMAKE_INSTALL_PREFIX=/pz/SFW -DWITH_LIBSYSTEMD=OFF -DWITH_WA
YLAND=OFF -DWITH_PULSE=ON -DWITH_ALSA=OFF
```
* output of `/buildconfig`
```
[ 75%] Building C object channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/rdpdr_main.c.o
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c:583:10: fatal error: mntent.h: No such file or directory
  583 | #include <mntent.h>
      |          ^~~~~~~~~~
compilation terminated.
```
After fixing include directive, error shown above
* OS version connecting to
```
OpenIndiana /hipster distribution (OpenSolaris fork)
```
* If available the log output from a run with `/log-level:trace` 
N/A

**Desktop (please complete the following information):**
```
:; uname -rosv
SunOS 5.11 illumos-a16250662f illumos
```
N/A
N/A

**Comment by akallabeth** [comment]
@3eka we have no way to test solaris, but if you are interested, we welcome pull requests.

**Comment by 3eka** [comment]
Hi, somethings is still missing:

```
:; git clone https://github.com/FreeRDP/FreeRDP.git
:; cd FreeRDP
:; find . -type f -name '*.c' | xargs grep mntent.h
./channels/rdpdr/client/rdpdr_main.c:#include <mntent.h>
```
Maybe I have missed something?
Thanks for fast reaction. That was really nice & friendly!
Regards.

**Comment by akallabeth** [comment]
@3eka this patch does not change the source files, but fixes the missing include path on the `CMake` side of things.

**Comment by 3eka** [comment]
Hi @akallabeth ,
I am using following compile procedure:
```
    git clone https://github.com/FreeRDP/FreeRDP.git
    cd FreeRDP

  myBLD=64
  export CFLAGS="-m${myBLD}   -I/usr/include -I/usr/gnu/include -I/usr/include/readline -I/usr/include/ncurses"
  export CXXFLAGS="-m${myBLD} -I/usr/include -I/usr/gnu/include -I/usr/include/readline -I/usr/include/ncurses"
  export LDFLAGS="-m${myBLD}  -R/usr/gnu/lib -R/usr/lib -L/usr/gnu/lib -L/usr/lib"
  export LIBS="-lresolv -lsocket -lnsl -lm -lintl -lpthread"
  unset LD_OPTIONS
  unset LD_CONFIG
  unset LD_RUN_PATH

  [[ -d bld ]] && rm -rf bld
  mkdir bld && cd bld
  cmake .. \
    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
    -DWITH_OPENSSL=ON \
    -DWITH_THIRD_PARTY=ON \
    -DWITH_SERVER=ON \
    -DWITH_LIBSYSTEMD=OFF \
    -DWITH_WAYLAND=OFF \
    -DWITH_PULSE=ON \
    -DWITH_ALSA=OFF
  gmake
```
But still, get this error:
```
Scanning dependencies of target rdpdr-client
[ 75%] Building C object channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/irp.c.o
[ 75%] Building C object channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/devman.c.o
[ 75%] Building C object channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/rdpdr_main.c.o
/nobackup/SFW_build/FreeRDP/channels/rdpdr/client/rdpdr_main.c:583:10: fatal error: mntent.h: No such file or directory
  583 | #include <mntent.h>
      |          ^~~~~~~~~~
compilation terminated.
gmake[2]: *** [channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/build.make:89: channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/rdpdr_main.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2727: channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
```
What I am doing wrong? 
Just a note: was able to compile 2.0.0-rc4 w/o any trouble

Does it support OpenSSL 1.1.1? I did not managed to get so far in compiling...

**Comment by akallabeth** [comment]
@3eka ah, you might want to check out https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html et al.
that way all the `find_file` and `find_library` will be able to properly detect what they are looking for.

**Comment by 3eka** [comment]
Hi @akallabeth 

like this (before **cmake** command)?
```
export CMAKE_PREFIX_PATH="/usr/include;/usr/gnu/include;/usr/include/readline;/usr/include/ncurses;/usr/include/sys"
```
It seems it does not work.

**Comment by akallabeth** [comment]
@3eka ok, that is strange, can you check the build log and have a look with which include paths the compiler was called? the detection works fine here on linux and mac build machines (that is the `find_file`)
as for openssl 1.1.1, yes, supported.

**Comment by 3eka** [comment]
In https://github.com/FreeRDP/FreeRDP/pull/6111#discussion_r413537266 you (@akallabeth) said that mntent.h is "not required on all platforms". 
If I remove include, building still fails, trying to use functions from mntent.h file.

BTW, mtnent.h is very different (when comparing it) on linux and openindiana

**Comment by akallabeth** [comment]
according to https://cmake.org/cmake/help/latest/command/find_path.html the search order should be correct.
Could you check what you have locally?
as for differences, as long as `struct mntent*` and `getmntent` are defined there that is fine.

**Comment by 3eka** [comment]
Well @akallabeth,

I tried with brute force:
```
sed -i "s|^#include <mntent.h>|#include <sys/mntent.h>|g" channels/rdpdr/client/rdpdr_main.c
```
And, it finds it, but still fails to compile:
```
[ 75%] Building C object channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/rdpdr_main.c.o
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c: In function 'handle_hotplug':
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c:666:16: warning: implicit declaration of function 'getmntent' [-Wimplicit-function-declaration]
  666 |  while ((ent = getmntent(f)) != NULL)
      |                ^~~~~~~~~
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c:666:14: warning: assignment to 'struct mntent *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  666 |  while ((ent = getmntent(f)) != NULL)
      |              ^
/nobackup/SFW_build/freerdp-2.0.0/channels/rdpdr/client/rdpdr_main.c:669:25: error: dereferencing pointer to incomplete type 'struct mntent'
  669 |   const char* path = ent->mnt_dir;
      |                         ^~
gmake[2]: *** [channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/build.make:89: channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/rdpdr_main.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2727: channels/rdpdr/client/CMakeFiles/rdpdr-client.dir/all] Error 2
gmake: *** [Makefile:152: all] Error 2
```
I have attached OI mntent.h file

[mntent.h.zip](https://github.com/FreeRDP/FreeRDP/files/4527761/mntent.h.zip)

P.S: I  have to study CMAKE variables

**Comment by akallabeth** [comment]
@3eka ok, got it. We removed the manual `/etc/mtab` parsing, if you don´t have `getmntent` you may have `getmntinfo`
Since I have no system to check that it would be great if you could create a pr.

**Comment by 3eka** [comment]
I will try to create zone and give to you ssh access.

It is not only mnttent which generates problem. OpenIndiana has OpenSSL 1.0.2 installed and it seems that GStreamer (both 0.10 and 1.0 was tighted to it, so if using OpenSSL 1.1.1 - I also must disable gstreamer use,, etc)

Will let you know if I have managed something, so you can try yourself...

**Comment by akallabeth** [comment]
@3eka gstreamer is only requires for `tsmf` channel which has been disabled by default (and was only used by windows 7 in very specific configurations)

**Comment by 3eka** [comment]
Hi @akallabeth ,

thanks. May I kindly ask you to share (somehow) cmake (ant other compiler related) options you use to build it on any unix like OS?.
I am using versions:
```
:; :; cmake --version
cmake version 3.15.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

:; /usr/gcc/9/bin/gcc --version
gcc (OpenIndiana 9.3.0-oi-0) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

:; /usr/gcc/9/bin/g++ --version
g++ (OpenIndiana 9.3.0-oi-0) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### System default compiler is 
:; gcc --version
gcc (OpenIndiana 7.5.0-il-0) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I can provide more s/w info, if you want ...
Regards.

**Comment by akallabeth** [comment]
@3eka `ccmake` is quite nice to get an overview of the configuration options of freerdp.
the options for our nightly packages can be found in the build files in `packaging` subfolder.

Basically you need:
* `libusb1` for usb redirection
* `pcsc` for smartcard redirection
* `cups` for printer redirection
* `libswscale` or `cairo2` for image scaling support
* `ffmpeg` or various codecs (`faac`, `faad`, `gsm`, `openh264`, ...) for audio/video related stuff.

**Comment by 3eka** [comment]
Just update:
version 2.1.2 has same mntent.h issue.

I still did not give up to create Zone for you, so you can try to compile it (my PC has crashed, reinstalled -- but due to current situation, I am bit slow). 
Regards.

**Comment by 3eka** [comment]
@akallabeth - I have created OpenIndidana zone and prepared it for freerdp build. I can give to you ssh access (you can send RSA ssh key to my primary address in github) - if you still want to test compilation on latest OI...
Regards.

**Comment by akallabeth** [comment]
@3eka nice, but I can not see your mail anywhere, your commits use a noreply.github.com address :/

**Comment by 3eka** [comment]
@akallabeth - I will enable e-mail visibility for next hour or so, so try then

**Comment by mvwieringen** [comment]
@3eka I just made a pull request and that got integrated into the current development branch and seems it will also be backported to the stable branch. For me this fixes the compile on OpenIndiana I did see the original pull request there got closed by the stale bot. I now run xfreerdp you may also try Remmina which also compiles on OpenIndiana only has some problems with building the language files. For now I have hand installed things but having them as supported packages would be preferred.

**Comment by 3eka** [comment]
Hi @mvwieringen ,

Thanks! It compiles (from git source) w/o problems (using same compile commands as I have mentioned earlier).

Running shows another one (tried to get console output from VirtualBox headless guest, with RDP enabled). 
```
xfreerdp +clipboard /sec:rdp /geometry /w:1024 /h:768 /kbd:German /dynamic-resolution /compression-level:2 /t:Title /v:host:50401
```
opens window, and then quits:
````
[09:47:26:090] [11367:00000002] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[09:47:26:091] [11367:00000002] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[09:47:26:092] [11367:00000002] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[09:47:26:092] [11367:00000002] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[09:47:26:092] [11367:00000002] [INFO][com.freerdp.client.common.cmdline] - loading channelEx drdynvc
[09:47:26:092] [11367:00000002] [INFO][com.freerdp.client.x11] - No user name set. - Using login name: predrag_zecevic
[09:47:29:827] [11367:00000002] [INFO][com.freerdp.client.x11] - Property 245 does not exist
[09:47:29:048] [11367:00000002] [INFO][com.freerdp.primitives] - primitives autodetect, using generic
[09:47:29:176] [11367:00000002] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[09:47:29:178] [11367:00000002] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[09:47:31:184] [11367:00000002] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[09:47:31:184] [11367:00000002] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[09:47:31:984] [11367:00000002] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[09:47:32:627] [11367:00000002] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[09:47:32:628] [11367:00000002] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel disp
[09:47:32:629] [11367:00000002] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel geometry
[09:47:37:382] [11367:00000002] [ERROR][com.freerdp.core.transport] - BIO_read returned a system error 0: Error 0
[09:47:37:382] [11367:00000002] [ERROR][com.freerdp.core] - transport_read_layer:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[09:47:37:382] [11367:00000002] [INFO][com.freerdp.client.common] - Network disconnect!
```
Same time, this works:
```
rdesktop -k de -T Title -g 1024x768 -a 16 -r clipboard:PRIMARYCLIPBOARD -r disk:PZ=/nobackup/Downloads node:50401
```
Any hints (there is no certificate on sevrer side)?

One more time, thanks for fix!
Regards.

**Comment by mvwieringen** [comment]
@3eka Yeah that is the next problem you need the following hack:

> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index fef59ede7..f1f39b4e3 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -263,6 +263,7 @@ if(CMAKE_COMPILER_IS_GNUCC)
>  
>         set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall")
>  
> +       set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -pthread")
>         CHECK_C_COMPILER_FLAG (-Wno-unused-result Wno-unused-result)
>         if(Wno-unused-result)
>                 set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wno-unused-result")
> 

For whatever reason things need the extra flag as then things are compiled with re-entrant support.
If you google on the error e.g. 'BIO_read returned a system error 0: Error 0' you find the hack I applied myself.

**Comment by viscountn7557** [comment]
[]()open issues
Bug report
Need help

**Comment by viscountn7557** [comment]
https://drive.google.com/file/d/1Rddr4Yit_qWTCOVBX4TPnUOmwcxGbbW9/view?usp=drivesdk$ rpm -q --whatprovides java

**Comment by viscountn7557** [comment]
<!DOCTYPE html>
<html>
<head>
<title>Page Title</title>
</head>
<body>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>

</body>
</html>
HTML Examples
At the end of the HTML tutorial, you can find more than 200 examples.

With our online editor, you can edit and test each example yourself.

Example
<img src="w3schools.jpg" alt="W3Schools.com" width="104" height="142"><!DOCTYPE html>
<html>
<body>

<p>Hello World!</p>

<p>The DOM is very useful!</p>

<p id="demo"></p>

<script>
var myNodelist = document.getElementsByTagName("p");
document.getElementById("demo").innerHTML =
"The innerHTML of the second paragraph is: " +
myNodelist[1].innerHTML;
</script>

</body>
</html>
<!DOCTYPE html>
<html>
<body>

<p>Hello World!</p>

<p>The DOM is very useful!</p>

<p id="demo"></p>

<script>
var myNodelist = document.getElementsByTagName("p");
document.getElementById("demo").innerHTML =
"The innerHTML of the second paragraph is: " +
myNodelist[1].innerHTML;
</script>

</body>
</html>
<!DOCTYPE html>
<html>
<body>

<p>Hello World!</p>

<p>The DOM is very useful!</p>

<p id="demo"></p>

<script>
var myNodelist = document.getElementsByTagName("p");
document.getElementById("demo").innerHTML =
"The innerHTML of the second paragraph is: " +
myNodelist[1].innerHTML;
</script>

</body>
</html>
content://com.google.android.apps.docs.storage.legacy/enc%3DiNPrk_3099k0Et9BGGGnXLPStOXRHJKTDxXYYrLcvTJimtA9BeUaGsSlJwLL_NAD5xYifxfAQsvN%0ATCIYdAex-5-PX0wN2f37JFK71D-6crgoxthFnpc8PYgs1nSpaUAWcYTScMM25Swp8WU3NzxrmhFY%0AX5c%3D%0Ahttps://drive.google.com/file/d/1UsXuDu0CVZAFH_nsvSheEjSlJkWqKVBN/view?usp=drivesdk<!DOCTYPE html>
<html>
<body>

<p>Hello World!</p>

<p>The DOM is very useful!</p>

<p id="demo"></p>

<script>
var myNodelist = document.getElementsByTagName("p");
document.getElementById("demo").innerHTML =
"The innerHTML of the second paragraph is: " +
myNodelist[1].innerHTML;
</script>

</body>
</html>
https://play.google.com/store/apps/details?id=awdc.androidsdkcheckerhttps://www.github.com/actions/starter-workflows/tree/master/automation%2Fstale.yml

**Comment by 3eka** [comment]
I have fixed that with following change:
From
```
export CFLAGS="-m64   -I/usr/include -I/usr/gnu/include -I/usr/include/readline -I/usr/include/ncurses"
```
To
```
export CFLAGS="-m64   -I/usr/include -I/usr/gnu/include -I/usr/include/readline -I/usr/include/ncurses -pthread"
```

Seems that has worked. Will double check.
Regards.

**Comment by 3eka** [comment]
Yes, works fine. Even drive is now mounted. I will need few more days to check everything...

**Comment by 3eka** [comment]
Dear all,
OI Team has brought FreeRDP to OpenIndiana (https://pkg.openindiana.org/hipster/info/0/desktop%2Fremote-desktop%2Ffreerdp%402.2.0%2C5.11-2020.0.1.0%3A20200727T163206Z)


I guess, we can close this issue.
Many thanks to everyone
Regards.

**Comment by mvwieringen** [comment]
@3eka yes I worked with the OI Team and got both FreeRDP and Remmina upstreamed.
