### ISSUE TITLE
Cursor crashes Windows client.

### ISSUE THREAD

**Issue by dmdo** [FreeRDP/FreeRDP#6121]
Hi,
I'd like to report issue with Cursor/Pointer.
We have captured a Access Violation error and Windows client crash, when RDP session tries to set custom pointer\cursor.

File: wf_graphics.c
Method: static BOOL wf_Pointer_New(rdpContext* context, const rdpPointer* pointer)
Line: 		if (!freerdp_image_copy_from_pointer_data(
		        pdata, gdi->dstFormat, 0, 0, 0, pointer->width, pointer->height,
		        pointer->xorMaskData, pointer->lengthXorMask, pointer->andMaskData,
		        pointer->lengthAndMask, pointer->xorBpp, &gdi->palette))
		{
			goto fail;
		}

Crash happens because of pixel format mismatch, where
gdi->dstFormat = PIXEL_FORMAT_BGRX32
and pdata is created with call:
		info.hbmColor = wf_create_dib((wfContext*)context, pointer->width, pointer->height,
		                              srcFormat, NULL, &pdata);
where srcFormat = PIXEL_FORMAT_BGR24

We are not able to reproduce issue, as it seems it depend on cursor used within RDP session. It was reported by a user.

Thank you.

**Comment by akallabeth** [comment]
Already fixed with https://github.com/FreeRDP/FreeRDP/pull/6106

**Comment by dmdo** [comment]
Just to clarify.
With those fixes it means pointer->xorBpp pixel format will be always matching gdi->dstFormat ?
I'm referring 'wf_graphics.c' file and wf_Pointer_New 

Thanks.

**Comment by akallabeth** [comment]
Sorry, mixed this pointer issue up with the before referenced one.

**Comment by dmdo** [comment]
Thanks for taking care of this!
