### ISSUE TITLE
Weird segfault in freerdp-proxy (libfreerdp code)

### ISSUE THREAD

**Issue by maordadush** [FreeRDP/FreeRDP#6139]
**Describe the bug**
I have an environment that works with FreeRDP proxy. 
I don't have a whole lot of detail. This just randomly happens after several weeks while users connect to terminal servers. There doesn't appear to be any specific cause that triggers this.
@kubistika @akallabeth 

**To Reproduce**
Connect to RDP server using FreeRDP proxy
Work as normal
Seg fault every few weeks

**Expected behavior**
No seg faults!

**Additional Info:**
I'm sorry that I had to upload screenshots, this is an air gap network

![0C9AE3F1-D572-4A5B-9DFC-BA2153ACCFED](https://user-images.githubusercontent.com/8192075/80957485-dbb3ce80-8e0b-11ea-8e3f-0f9fec04f8e0.JPG)
![ABE26166-AE0F-44C3-A8D4-6B3662DC017C](https://user-images.githubusercontent.com/8192075/80958184-43b6e480-8e0d-11ea-94b7-a2b2cada3aab.JPG)

**Comment by akallabeth** [comment]
@madsensh do you have the version and buildconfig of the server available?

**Comment by akallabeth** [comment]
@madsensh and if it is possible, could you run a version with address sanitizer activated?
That is more reliable in detecting any memory access fault and pointing to the reason of the issue (keep in mind, this consumes much more memory)
It looks like here we only see the result of some corruption that happened long before.

**Comment by maordadush** [comment]
Ok, I'll try it and keep you posted

**Comment by akallabeth** [comment]
@maordadush and, if you end up in a gdb again, could you dump the `StreamPool` as well as the `wStream` structs?

**Comment by maordadush** [comment]
Attached the address sanitizer output
@akallabeth @kubistika 
![IMG-8458](https://user-images.githubusercontent.com/8192075/81812506-e7e80c00-952e-11ea-9285-52bbd8d522cc.jpg)
![IMG-8460](https://user-images.githubusercontent.com/8192075/81812520-ed455680-952e-11ea-8ca6-cad7d7693327.jpg)
![IMG-8461](https://user-images.githubusercontent.com/8192075/81812535-f1717400-952e-11ea-9f3e-5bb7dd85c50a.jpg)
![IMG-8459](https://user-images.githubusercontent.com/8192075/81812548-f6362800-952e-11ea-9e17-4155b95e401f.jpg)

**Comment by kubistika** [comment]
@maordadush @akallabeth I think I know what happend here. There was a disconnection between peer <> proxy server, while the client thread was trying to connect (in freerdp_connect), and the server freed the client already. I'm uploading a sync-fix and we'll try it

**Comment by kubistika** [comment]
@akallabeth first log looks weird, looks like there are two threads calling GetTimezoneInformation with the same rdpSettings instance. I guess that's a race in the proxy, but can't seem to find it yet

**Comment by akallabeth** [comment]
@kubistika maybe 2 clients connecting? `rdp_send_client_info` is the only place it is called from during capability negotiation

**Comment by kubistika** [comment]
@akallabeth yes, but i can't understand how this function is called with the same rdpSettings* struct.

**Comment by akallabeth** [comment]
@kubistika can´t help you there.
