### ISSUE TITLE
release 2.0.1

### ISSUE THREAD

**Issue by trentasis** [FreeRDP/FreeRDP#6141]
Hi

Can you release 2.0.1 if bug related with smartcard is solved? Seems that with 2.0.0 is not working smartcard

Thanks

**Comment by akallabeth** [comment]
@trentasis duplicate, please read the issue tracker.

**Comment by trentasis** [comment]
hi,

sorry, but I can't fins duplicate issue.
Do you know if problems with smartcard and sound on freerdp 2.0.0 are sovled? when will be relased on 2.0.1?

Thanks

**Comment by akallabeth** [comment]
for smartcard see #6068 (you need a command line switch, which solves the smartcard stuff)

**Comment by trentasis** [comment]
correct, but my question was related when will be released on 2.0.1, because with 2.0.0 smartcard is not working and for distributions is needed, I think
any scheduled date?

thanks

**Comment by akallabeth** [comment]
@trentasis so, `/client-build-number:2600` does not work for you like mentioned in #6068?
As for a new version, we are preparing one.
