### ISSUE TITLE
monitor-list empty

### ISSUE THREAD

**Issue by xochilpili** [FreeRDP/FreeRDP#6142]
Hello everyone, 

OS: Fedora31
xfreerdp: This is FreeRDP version 2.0.0-dev5 (n/a)

Two issues: 
1.- xfreerdp /monitor-list : outputs empty
2.- xfreerdp /v:my_vdi /d:my_domain /g:mycompany.contoso.com /u:myUser /gu:myGatewayUser /gd:myGatewayDomain /sec:rdp : 
ask for my password, then i have 2FA using mobile app, then when i authorize, should ask again for my password, which is not, and then i have this error: 

freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
[ERROR][com.freerdp.core.gateway.rdg] - channel response errorCode=E_PROXY_RAP_ACCESSDENIED [0x800759DA], fieldsPresent= [0000]
[ERROR][com.freerdp.core] - rdg_process_channel_response:freerdp_set_last_error_ex E_PROXY_RAP_ACCESSDENIED [0x800759DA] [0x800759DA]

Using Remmina im able to access, but not using xfreerdp
Is there anything im doing wrong?

**Comment by akallabeth** [comment]
1. Please try with our nightly builds first.
1. Not much we can help here without further setup descriptions.
1. Please use mailing list or IRC for support questions. https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
