### ISSUE TITLE
Certificate Checking Recently Broke

### ISSUE THREAD

**Issue by KenHolloway** [FreeRDP/FreeRDP#6148]
A recent update to FreeRDP broke the checking of SSL certificates used by RDP (at least those signed by Starfield Technologies, Inc.). With the new version, connecting to these servers returns:

[19:49:36:178] [32096:32097] [WARN][com.freerdp.crypto] - Certificate verification failure 'certificate rejected (28)' at stack position 2
[19:49:36:178] [32096:32097] [WARN][com.freerdp.crypto] - C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", CN = Starfield Root Certificate Authority - G2
Certificate details for <removed>.<removed>.com:3389 (RDP-Server):
        Common Name: <removed>.<removed>.com
        Subject:     OU = Domain Control Validated, CN = <removed>.<removed>.com
        Issuer:      C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", OU = http://certs.starfieldtech.com/repository/, CN = Starfield Secure Certificate Authority - G2
        Thumbprint:  68:3a:<removed>:39:0c
The above X.509 certificate could not be verified, possibly because you do not have
the CA certificate in your certificate store, or the certificate has expired.
Please look at the OpenSSL documentation on how to add a private CA to the store.

Up until a few of days ago, this was working. This computer is openSUSE Leap 15.1, running FreeRDP version 3.0.0-dev (27f2eb13c). I have another nearly identical computer that I have not updated FreeRDP on recently - it is still running FreeRDP version 2.0.0-dev5 (07605b028) - and it connects without any certificate warning.

**Comment by akallabeth** [comment]
@KenHolloway the only change that happened is `X509_PURPOSE_SSL_SERVER` to `X509_PURPOSE_ANY` in `X509_STORE_CTX_set_purpose` file `libfreerdp/crypto/crypto.c`

Could you verify this is the cause?

**Comment by akallabeth** [comment]
could you also add the `X509v3` elements in the output of `openssl x509 -in yourcert.pem -text`?

**Comment by KenHolloway** [comment]
I changed X509_PURPOSE_ANY back to X509_PURPOSE_SSL_SERVER, recompiled, and it is happy with the certificates again. Thank you for your quick response, and all you do with FreeRDP!

The X509x3 extensions on the certificate are:
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 CRL Distribution Points: 

                Full Name:
                  URI:http://crl.starfieldtech.com/sfig2s1-141.crl

            X509v3 Certificate Policies: 
                Policy: 2.16.840.1.114414.1.7.23.1
                  CPS: http://certificates.starfieldtech.com/repository/
                Policy: 2.23.140.1.2.1

            Authority Information Access: 
                OCSP - URI:http://ocsp.starfieldtech.com/
                CA Issuers - URI:http://certificates.starfieldtech.com/repository/sfig2.crt

            X509v3 Authority Key Identifier: 
                keyid:25:45:81:68:50:26:38:3D:3B:2D:2C:BE:CD:6A:D9:B6:3D:B3:66:63


Let me know if there is any more information that would be helpful.

**Comment by akallabeth** [comment]
@KenHolloway If you remove the function altogether, does it work then? (aka is the check for purpose skipped?)
 (the openssl docs are not entirely clear or I couldn´t find the location for that)

**Comment by akallabeth** [comment]
@KenHolloway also what does the verification with `openssl` binary tell you?

**Comment by KenHolloway** [comment]
When I comment out "X509_STORE_CTX_set_purpose(csc, X509_PURPOSE_SSL_SERVER);", it goes back to not trusting the certificate.


"openssl s_client -connect RDS.<removed>.com:443" seems to be perfectly happy with the certificate:

CONNECTED(00000003)
depth=2 C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", CN = Starfield Root Certificate Authority - G2
verify return:1
depth=1 C = US, ST = Arizona, L = Scottsdale, O = "Starfield Technologies, Inc.", OU = http://certs.starfieldtech.com/repository/, CN = Starfield Secure Certificate Authority - G2
verify return:1
depth=0 OU = Domain Control Validated, CN = *.<removed>.com
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=*.<removed>.com
   i:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./OU=http://certs.starfieldtech.com/repository//CN=Starfield Secure Certificate Authority - G2
 1 s:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./OU=http://certs.starfieldtech.com/repository//CN=Starfield Secure Certificate Authority - G2
   i:/C=US/ST=Arizona/L=Scottsdale/O=Starfield Technologies, Inc./CN=Starfield Root Certificate Authority - G2
---
