### ISSUE TITLE
Sound causes connection to drop on 2.0.0

### ISSUE THREAD

**Issue by RonaldDuncan** [FreeRDP/FreeRDP#6149]
Connections started dropping after I upgraded to 2.0.0
removing the +sound /microphone:sys:alsa makes the connection stable
The machine I am connecting too with sound is running Windows 10
My standard parameters were
/w:1920 /h:1080 +clipboard +sound /microphone:sys:alsa +drives
/w:1920 /h:1080 +clipboard  +drives
Is stable after the upgrade.

When the connection fails the last message is 
[aac @ 0x7f6b2c12e940] Qavg: -nan
[aac @ 0x7f6b2c12e940] 2 frames left in the queue on closing

Sometimes it recovers and carries on without dropping for a while.
[16:56:12:176] [171058:171076] [INFO][com.freerdp.channels.rdpdr.client] - registered device #1: home (type=8 id=1)
[aac @ 0x7f6b2c003580] Qavg: 214.491
[aac @ 0x7f6b2c003580] 2 frames left in the queue on closing
[aac @ 0x7f6b2c004f80] Qavg: 215.341
[aac @ 0x7f6b2c004f80] 2 frames left in the queue on closing
[aac @ 0x7f6b2c12e940] Input contains (near) NaN/+-Inf
[16:57:31:756] [171058:171121] [ERROR][com.freerdp.dsp.ffmpeg] - Error submitting the packet to the encoder Invalid argument [-22]
[16:57:31:756] [171058:171121] [ERROR][com.freerdp.channels.audin.client] - audin_alsa_thread_receive failed with error 1359
[16:57:31:756] [171058:171059] [ERROR][com.freerdp.core] - audin_alsa_thread_func reported an error. Error was 1359
[16:57:31:756] [171058:171059] [ERROR][com.freerdp.core] - checkChannelErrorEvent() failed - 0
[16:57:31:756] [171058:171059] [INFO][com.freerdp.client.common] - Network disconnect!
[16:57:31:756] [171058:171059] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
[aac @ 0x7f6b2c12e940] Qavg: -nan
[aac @ 0x7f6b2c12e940] 2 frames left in the queue on closing

May be related to Sound stuttering in 2.0 compared to 2.0-rc4 #6043 since I found  the same Qavg: -nan and that gave me the hint to turn off sound.

xfreerdp --version
This is FreeRDP version 2.0.0 (n/a)
xfreerdp --buildconfig
This is FreeRDP version 2.0.0 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=ON WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 9.3.0
Target architecture: x64

**Comment by akallabeth** [comment]
@RonaldDuncan the error is from the microphone option and has something to do with your ffmpeg build. We deactivated aac support there on master.

**Comment by akallabeth** [comment]
As for sound stuttering, master has already fixes.
