### ISSUE TITLE
generated xfreerdp.1 man page is badly formatted

### ISSUE THREAD

**Issue by tinywrkb** [FreeRDP/FreeRDP#6155]
FreeRDP 2.1.0
Archlinux with
* xmlto 0.0.28
* docbook-xsl
* docbook-xml 4.5
* libxslt 1.1.34
* libxml2 2.9.10

[Here's the bug report for archlinux](https://bugs.archlinux.org/task/64814). ATM the archlinux package carries the suggested changes for FindDocBookXSL.cmake.

Only xfreerdp.1 is affected, all other man pages are fine (tested: freerdp-shadow-cli.1 winpr-hash.1 winpr-makecert.1 wlfreerdp.1 wlog.7).

[man_xfreerdp_errors.txt](https://github.com/FreeRDP/FreeRDP/files/4599047/man_xfreerdp_errors.txt)
[man_xfreerdp_output.txt](https://github.com/FreeRDP/FreeRDP/files/4599048/man_xfreerdp_output.txt)

**Comment by akallabeth** [comment]
@tinywrkb I´ve just compiled current `FreeRDP` master fd5bdee8b3b1e985e201e9cd0c7426456ee028a1on ubuntu 20.04 and debian 10, the man page is just like as it should be. This looks like an error on the `arch` end

**Comment by tinywrkb** [comment]
I can't reproduce on Debian unstable and from the Debian docbook-xml dokbook-xsl packaging patches nothing stands out.  
As it's not possible for me to reproduce on a distro with similar versions of packages I'm closing this issue.
