### ISSUE TITLE
Possible race in `security_encrypt`

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#6156]
`security_encrypt` updates the encryption key for the old style RDP encryption when sending more than 4096 packets.
Since the function might be used from different threads a race might occur.

See mailing list `[FreeRDP-devel] ERRINFO_DECRYPT_FAILED error` from `2020-05-08 22:36` for initial report.

**Comment by markonikolic** [comment]
I have updated the function you have mentioned in the mailing list (as well a few other in input.c), but no success.

Maybe I did something wrong, I have created a module level mutex, create it in input_new() and destroy in input_free(). Each of the functions:

- input_send_fastpath_mouse_event
- input_send_extended_mouse_event
- input_send_fastpath_keyboard_event
- input_send_fastpath_unicode_keyboard_event

are updated like in this one https://gist.github.com/markonikolic/1849b50830bfaf5f5ff919e3d4ed5462


Is this the proper approach? I did all changes on top of 2.1.0 release.


In further testing, it seems that the combination of mouse movement and clicking triggers the issue. Only movement or clicking alone does not trigger it, or at least much less frequent. It seems odd...

**Comment by akallabeth** [comment]
@markonikolic better add the mutex down where the encryption happens, there are other things sent back too.

**Comment by markonikolic** [comment]
I have checked the version 2.1.1 which includes fix for this bug.

However, I observe the same behavior. When the mouse is moved rapidly, or fast typing on the keyboard, the error ERRINFO_DECRYPT_FAILED happens and the connection is broken. 

We have a partial workaround, but the solution is not long term. In our application, we have added mutex lock / unlock around all calls that deal with mouse and keyboard events. This synchronizes all input to the library, something similar to what you have proposed above, but implemented in our app, not in the freerdp library.

However, although we don't have disconnects and ERRINFO_DECRYPT_FAILED error, there is clearly visible lagging when typing, even sometimes there are lost key events, so in the long term, it is not a viable solution.

The following freerdp calls are wrapped with mutex_lock / mutex_unlock in our workaround:

-
- input_send_fastpath_mouse_event
- input_send_mouse_event
- input_send_fastpath_keyboard_event
- input_send_keyboard_event
- input_send_fastpath_unicode_keyboard_event
- input_send_unicode_keyboard_event
- input_send_fastpath_synchronize_event
- input_send_synchronize_event
- freerdp_check_event_handles
- disp_send_monitor_layout
- 

Do you have some more ideas about how this error can be fixed or prevented? Or maybe how we can avoid the lagging?

**Comment by hardening** [comment]
This look much like an architectural problem with threading, FreeRDP is not safe when called from multiple threads at the same time.

**Comment by akallabeth** [comment]
@hardening true, it is a race, but that is because I introduced the lock only on `security_encrypt`. #6242 should address this for `security_decrypt` too.
@markonikolic can you confirm?
