### ISSUE TITLE
Unable to connect to Windows 10 machines over RDP since v2.1.0 upgrade

### ISSUE THREAD

**Issue by nlyan** [FreeRDP/FreeRDP#6168]
**Describe the bug**
Since upgrading to v2.1.0 I've been unable to connect to any of my Windows 10 machines via Remmina.

Log is here: https://gist.github.com/nlyan/753897188a4dab850c8f42682a476681

This seems to be related to https://github.com/FreeRDP/FreeRDP/issues/5491

**To Reproduce**
Unknown

**Environment (please complete the following information):**
Arch Linux

[andrew@ziggy ~]$ xfreerdp --version
This is FreeRDP version 2.1.0 (n/a)

[andrew@ziggy ~]$ openssl version
OpenSSL 1.1.1g  21 Apr 2020`

**Comment by nlyan** [comment]
Confirmed rolling back to FreeRDP 2.0.0 solved the issue:

https://gist.github.com/nlyan/69c1a756a3169d5c8d9536ef473686d5

Remmina was compiled againt 2.0.0 it seems, if that makes any difference.

**Comment by akallabeth** [comment]
Duplicates #6148 
Currently not entirely sure where the issue resides (certificate or the check) as we actually widened the allowed certificate purpose (`ANY` in contrast to `SERVER` in previous versions)
