### ISSUE TITLE
Duplicated conditions in if expression inside uwac-display.c

### ISSUE THREAD

**Issue by qarmin** [FreeRDP/FreeRDP#6169]
https://github.com/FreeRDP/FreeRDP/blob/1a058ed8f650ff5cb748767608a9c265f90fd934/uwac/libuwac/uwac-display.c#L423

**Comment by hardening** [comment]
What's wrong with the fact that we wanna do 2 round trips ?

**Comment by qarmin** [comment]
It may be a bug(but in this case, based on your comment, it is not).
Also some analyzers like Sonarcloud(which I used) may think that is probably wrong.

So if in this line is everything fine, then nothing needs to be changed, but it could be changed to prevent similar reports in the future.

**Comment by akallabeth** [comment]
Ok, closing as not an issue.
