### ISSUE TITLE
Typo: " * ASN.1 Packed Encoding Rules (BER)"

### ISSUE THREAD

**Issue by JonathanWilbur** [FreeRDP/FreeRDP#6185]
https://github.com/FreeRDP/FreeRDP/blob/329332432a27e9ddc7f2f732577bfcbdf5c92221/libfreerdp/crypto/per.c#L3

**Comment by akallabeth** [comment]
Pull request welcome, otherwise no issue for this required, will be fixed on next touch of the file (which might take some years ;))
