### ISSUE TITLE
drdynvc segfault after drdynvc's changes

### ISSUE THREAD

**Issue by maordadush** [FreeRDP/FreeRDP#6190]
Build: freerdp master
Screenshots: 
![IMG-8575](https://user-images.githubusercontent.com/8192075/82220869-e603bb80-9927-11ea-8861-22fae251da64.jpg)
@kubistika @akallabeth

**Comment by akallabeth** [comment]
@maordadush already preparing a pr for that, found that during a test session only an hour ago, good catch!
