### ISSUE TITLE
Possible usage of null pointer in disp_main.c

### ISSUE THREAD

**Issue by qarmin** [FreeRDP/FreeRDP#6194]
`disp` is checked if is null, but later is used without checking

https://github.com/FreeRDP/FreeRDP/blob/6a811db69cbad86fba0b0dd0a149b8137749229f/channels/disp/client/disp_main.c#L325-L335

**Comment by qarmin** [comment]
Also similar fragment with `geometry` is here
https://github.com/FreeRDP/FreeRDP/blob/6a811db69cbad86fba0b0dd0a149b8137749229f/channels/geometry/client/geometry_main.c#L430-L441

**Comment by qarmin** [comment]
And here
https://github.com/FreeRDP/FreeRDP/blob/6a811db69cbad86fba0b0dd0a149b8137749229f/channels/rdpei/client/rdpei_main.c#L600-L609

**Comment by akallabeth** [comment]
true, the NULL check could be removed in these cases, but not necessary.
