### ISSUE TITLE
Always true ret condition in libusb_udevice.c

### ISSUE THREAD

**Issue by qarmin** [FreeRDP/FreeRDP#6196]
if `ret < 4`, then  is always true that `ret <= 0`

https://github.com/FreeRDP/FreeRDP/blob/822ed3d7ff5f4b7686b3edf4a1ab6e73445fbbb2/channels/urbdrc/client/libusb/libusb_udevice.c#L789-L790

**Comment by akallabeth** [comment]
Not always, the firs two could be combined.
