### ISSUE TITLE
Freeing null pointer in cmdline.c

### ISSUE THREAD

**Issue by qarmin** [FreeRDP/FreeRDP#6198]
Maybe ! should be removed?

https://github.com/FreeRDP/FreeRDP/blob/c11939e32579cb77534933b4e63132586555a893/client/common/cmdline.c#L3282-L3285

https://github.com/FreeRDP/FreeRDP/blob/c11939e32579cb77534933b4e63132586555a893/client/common/cmdline.c#L3300-L3303

**Comment by akallabeth** [comment]
No, why?

**Comment by qarmin** [comment]
Inside if statement `settings->GatewayDomain` is null, so there is unnecessary to free null memory.
Maybe better is to remove `free(settings->GatewayDomain)` statement?

**Comment by akallabeth** [comment]
No, there are cases it might not be null
