### ISSUE TITLE
error /usb

### ISSUE THREAD

**Issue by trentasis** [FreeRDP/FreeRDP#6214]
hi,

with latest master version /usb no working, for example:

/usb:id,dev:046d:0819

[16:21:35:979] [18170:18170] [ERROR][com.winpr.commandline] - Failed at index 4 [/usb:id,dev:046d:0819]: Unexpected keyword

If you remove /usb... then works

With previous versions was working

Thanks

**Comment by akallabeth** [comment]
@trentasis no, this is working on current master 6dbee147d87a79ca646f53a7de0af4302e1fe92d

**Comment by akallabeth** [comment]
same for current `stable-2.0` branch, run `xfreerdp /v:<url> /usb:id,dev:1234:5678` is working.

**Comment by trentasis** [comment]
Hi,

I think that I have found the issue:

compiled using https://github.com/FreeRDP/FreeRDP/wiki/Compilation and now working after installing libfaac-dev, sorry.

additional comment packages libgstreamer-plugins-base0.10-dev libgstreamer0.10-dev are not available on debian and I understand that are replaced byt 1.0, or not? It is needed to remove from wiki this packages? 

Thanks
