### ISSUE TITLE
Freerdp-2.1.1 Windows 2016 Remote app reconnect getting segfault

### ISSUE THREAD

**Issue by ganeshjkale** [FreeRDP/FreeRDP#6218]
Client OS:- Xubuntu-18.04_x86
Server OS:- Windows 2016
Freerdp Build Machine:- Xubuntu 16.04_x86

Note:-
1:-Client machine is on vmware workstation v15
2:-Issue reproducible on Freerdp-2.1.0 also

Scenario:-
1:-Launch remote app
2:-disconnect client machine network (unplug cable)
3:-after some seconds session got disconnected with on one or two reconnect retries
4:-got segmentation fault in last line of log

cmdline:-
/opt/freerdp2/bin/xfreerdpbin /cert-ignore /title:AccopsClient  /bpp:32   +gfx-progressive  /sound:quality:dynamic /audio-mode:0  +clipboard  +compression   +window-drag  +menu-anims  +wallpaper +aero  +bitmap-cache  +fonts  +themes   +auto-reconnect  /auto-reconnect-max-retries:20 +floatbar  /dynamic-resolution  /f  +toggle-fullscreen    /video  /gdi:sw   /kbd:0x00000409  "/app:||AppLauncher" /app-cmd:'2 0 92ea74aa-7bb7-4107-b0a4-250189645afd 352bafd2-7506-42a4-a5b4-1f6e7607e5c1 cb2118f7-b277-4d4d-9211-65560ccd3cff"  /microphone:sys:alsa,format:1  /d:ptplqa.local /u:"qasp1" /v:172.26.7.103:3389 /tune:FreeRDP_TcpKeepAlive:TRUE,FreeRDP_TcpKeepAliveRetries:3,FreeRDP_TcpKeepAliveDelay:5,FreeRDP_TcpKeepAliveInterval:2,FreeRDP_TcpAckTimeout:9000 /log-level:TRACE

Build config:-

This is FreeRDP version 2.1.1
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=ON WITH_LIBAVCODEC=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type: Release
CFLAGS: -march=i686 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler: GNU, 5.4.0
Target architecture: x86

Freerdp Trace Logs are as attached.
[rem_app.log](https://github.com/FreeRDP/FreeRDP/files/4658218/rem_app.log)

**Comment by akallabeth** [comment]
@ganeshjkale please try to reproduce with a `minimal` command line first.
Secondly, don´t forget to redirect error messages! `xfreerdp >2&1 |tee log.txt` will redirect everything to a file
Third, could you retry this with a debug build, best add `-DWITH_SANITIZE_ADDRESS=ON`, so we have a proper stack trace in the logs?

**Comment by ganeshjkale** [comment]
@akallabeth 

cmdline:- 
`/opt/freerdp2/bin/xfreerdpbin  /cert-ignore   /network:auto   +auto-reconnect "/app:||AppLauncher" /app-cmd:'2 0 782d9b44-3e5f-4c5c-bac7-948ea5877660 352bafd2-7506-42a4-a5b4-1f6e7607e5c1 a0a9bae9-22a1-4b69-bd75-30a784d16eb8'   /d:test.local /u:"test" /v:x.x.x.x:3389 /p:test@123 /f /log-level:TRACE  2>&1 |tee rem_dis.txt`

Attaached logs without debug build:- 
[rem_dis.txt](https://github.com/FreeRDP/FreeRDP/files/4667311/rem_dis.txt)

**Comment by akallabeth** [comment]
@ganeshjkale this is neither a debug build nor a segfault

**Comment by ganeshjkale** [comment]
@akallabeth  now trying with latest nightly build

**Comment by ganeshjkale** [comment]
@akallabeth 
Reproduced segfault issue with freerdp nightly build:- 
freerdp-nightly_2.0.0+0_20200521014825.818_1.gbp8fb633_i386.deb                                                                                                                                              
freerdp-nightly-dbg_2.0.0+0_20200521014825.818_1.gbp8fb633_i386.deb 

cmdline:- 
`/opt/freerdp-nightly/bin/xfreerdp  /cert-ignore   /network:auto   +auto-reconnect "/app:||AppLauncher" /app-cmd:'2 0 d07ccc71-1245-4949-9faa-71c73fed92cc 352bafd2-7506-42a4-a5b4-1f6e7607e5c1 b38a66d5-b441-4e5d-96fa-5bbfdedd3553'   /d:ptplqa.local /u:"test" /v:x.x.x.x:3389 /p:test@123 /f /log-level:TRACE  /gfx-h264  2>&1 |tee rem_dis_debug_nightly.txt`

Attached TRACE logs with nightly debug:-
[rem_dis_debug_nightly.txt](https://github.com/FreeRDP/FreeRDP/files/4667639/rem_dis_debug_nightly.txt)

**Comment by akallabeth** [comment]
@ganeshjkale that is (much) better, still missing proper stack trace. Could you build a nightly locally the following way:
1. change `-DCMAKE_BUILD_TYPE=RelWithDebInfo`  to `-DCMAKE_BUILD_TYPE=Debug` in `packaging/deb/freerdp-nightly/rules`
1. `ln -s packaging/deb/freerdp-nightly debian`
1. `dpkg-buildpackage`
1. Run your test case

**Comment by ganeshjkale** [comment]
@akallabeth will try and let you know

**Comment by ganeshjkale** [comment]
@akallabeth with minimal commandline not able to reproduce segfault but reconnection issue still exists.

cmdline:-
/opt/freerdp-nightly/bin/xfreerdp /cert-ignore /network:auto +auto-reconnect "/app:||AppLauncher" /app-cmd:'2 0 d07ccc71-1245-4949-9faa-71c73fed92cc 352bafd2-7506-42a4-a5b4-1f6e7607e5c1 b38a66d5-b441-4e5d-96fa-5bbfdedd3553' /d:ptplqa.local /u:"test" /v:x.x.x.x:3389 /p:test@123 /f /log-level:DEBUG  /gfx-h264 2>&1 |tee rem_dis_debug_nightly_mine_debug.txt

Below is Debug log from debug build of 2.1.1 as per your guidance.

Attached Debug Logs:-
[rem_dis_debug_nightly_mine_debug.txt](https://github.com/FreeRDP/FreeRDP/files/4675464/rem_dis_debug_nightly_mine_debug.txt)

**Comment by akallabeth** [comment]
@ganeshjkale ok, hat you run into reconnect means you have a really slow and/or lossy connection? Testing locally with adding package loss or breaking connection altogether successfully reestablishes the connection without a crash.

**Comment by ganeshjkale** [comment]
@akallabeth yes i am testing over internet with 18mbps on  wan network.
Tried same today on same network.
My question is windows 2016 session is re-connected in same network with same scenario but not remote app.

**Comment by akallabeth** [comment]
@ganeshjkale might be a server side policy in place, no idea there. we do the same in both cases, remote app is on a higher level.
Reproducing the segfault would be great, as this is a real bug in freerdp we can not reproduce.
