### ISSUE TITLE
Bugs found by static tests

### ISSUE THREAD

**Issue by tester7632** [FreeRDP/FreeRDP#6224]
Sonarqube revealed some potential bugs that should get a closer look.

Most of the results this tools produces are not really relevant or simply "not best practice" but the linked "Blocker" issues tend to include some valid bugs.

https://sonarcloud.io/project/issues?id=FreeRDP_allfeatures&resolved=false&severities=BLOCKER&types=BUG

**Comment by akallabeth** [comment]
@tester7632 looked through the issues and only one or 2 are really relevant (annoying local command line crash) the rest looks (mostly) like false positives. (e.g. all creators are flagged as resource leaks)
