### ISSUE TITLE
enter toggles full screen after moving workspace with ctrl+alt+arrow keys

### ISSUE THREAD

**Issue by jasonblewis** [FreeRDP/FreeRDP#6227]
**Found a bug? - We would like to help you and smash the bug away.**
1. __Please don't "report" questions as bugs. For these (questions/build instructions/...) please use one of the following means of contact:__
   * We are reachable via IRC _#freerdp on freenode_
   * We are reachable via mailing list <freerdp-devel@lists.sourceforge.net>
   * Try our mailing list for discussions/questions
1. Before reporting a bug have a look into our issue tracker to see if the bug was already reported and you can add some additional information.
1. If it's a __new__ bug - create a new issue.
1. For more details see https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Describe the bug**
when I connect to a remote desktop with 
xfreerdp +clipboard -grab-keyboard /smart-sizing /multimon /monitors:0,1 /u:jason /v:hostname

pressing enter in the remote desktop works as expected.
then if i change my gnome workspace by pressing ctrl+alt+down, then back to the rdp with ctrl+alt+up,
<enter> in the rdp now acts as though I pressed ctrl+alt+enter, and toggles full screen mode. this seems to continue until I restart the freerdp session.

**To Reproduce**
0. log in to X wayland gnome (debian 10.4)
1. log on to a remote host using freerdp
2. note that <enter> behaves correctly in the RDP session
3. press ctrl+alt+down arrow then ctrl+alt+up arrow to switch to a new workspace and back
4. press <enter> again in the RDP session, now the FreeRDP window toggles full screen

**Expected behavior**
I expect enter would not toggle full screen

* FreeRDP version (`xfreerdp /version`)
This is FreeRDP version 3.0.0-dev (0cb7ada6d)
* Command line used
xfreerdp +clipboard -grab-keyboard /smart-sizing /multimon /monitors:0,1 /u:jason /v:hostname

* Output of `xfreerdp /buildconfig`

```
$ xfreerdp /buildconfig
This is FreeRDP version 3.0.0-dev (0cb7ada6d)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_STDINT_H=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=ON WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_GDI=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_ORDERS=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=1 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_LEAK=OFF WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Debug
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 8.3.0
Target architecture: x64
```
* OS version connecting to (server side)
windows 2k16
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]
Linux
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]
Debian 10.4
 - Architecture: [amd64, arm]:
x64
**Additional context**
this seems to be a new bug. I didn't used to have this problem with older versions.
not sure which version changed it. I may be able to do a git bisect to work it out

**Comment by jasonblewis** [comment]
After trying to bisect the issue, I've narrowed it down to something to do with the compile options.
If I build with 
`time cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_DSP_FFMPEG=OFF -DWITH_FFMPEG=OFF -DWITH_SSE2=ON .`

then the problem goes away.
build again with
`cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON .`
and the problem comes back.

**Comment by jasonblewis** [comment]
In further testing I was able to reproduce the bug with or without the FFMPEG options above. so it's not that.

**Comment by jasonblewis** [comment]
this seems to be reported in a few other issues.

https://github.com/FreeRDP/FreeRDP/issues/4966
https://github.com/FreeRDP/FreeRDP/issues/5092
https://github.com/FreeRDP/FreeRDP/issues/3491

As at 2021-01-14 it still is an issue for me. Is there anything we can do to assist in diagnosing and solving this?

**Comment by akallabeth** [comment]
@jasonblewis 
1. check `xf_keyboard_release_all_keypress` is called when the window loses or gains focus
2. check all state variables used in `xf_keyboard_handle_special_keys` are reset when focus is lost / received
