### ISSUE TITLE
Repositories https://pub.freerdp.com/repositories/deb/ not updated

### ISSUE THREAD

**Issue by stdedos** [FreeRDP/FreeRDP#6230]
It used to be so that packages https://pub.freerdp.com/repositories/deb/xenial/ were updated, but it does not appear to be the case anymore.

I noticed when 2.1.0 was released, that I am not offered any updates.

**Comment by akallabeth** [comment]
fixed

**Comment by stdedos** [comment]
```
freerdp-nightly/                                   03-Jun-2020 07:36                   -
	freerdp-nightly_2.0.0+0~20200603014841.822~1.gb..> 03-Jun-2020 07:07             2159770
freerdp2/                                          22-Nov-2018 11:21                   -
```

Are we also expecting release builds?

**Comment by akallabeth** [comment]
we only provide nightly builds

**Comment by bmiklautz** [comment]
@stdedos as @akallabeth mentioned currently we only provide nightly builds of the master branch. We possibly will have release builds in the future but for now on please use the tested builds from your distribution.

**Comment by stdedos** [comment]
> @stdedos as @akallabeth mentioned currently we only provide nightly builds of the master branch.

I guess that would be fine too. Except, the nightlies are at 2.0.0, and you are in 2.1.1.
So, either I have a different idea what a nightly's version should be, your automation needs time to catch up (from the first missing package until today), or something entirely else.

> We possibly will have release builds in the future but for now on please use the tested builds from your distribution.

`tested builds from your distribution` sounds hilarious:
```
Package freerdp-x11
xenial (16.04LTS) (x11): RDP client for Windows Terminal Services (X11 client)
1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.3 [security]: amd64 i386
1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1 [ports]: arm64 armhf powerpc ppc64el s390x
```

I mean, I understand _why_ supporting them yourself is painful - but `freerdp 1.1.0` is ages old.
