### ISSUE TITLE
freerdp-shadow-cli on macOS - black screen if connecting from iOS MS RD Client 

### ISSUE THREAD

**Issue by CataIin** [FreeRDP/FreeRDP#6234]
Connecting from iOS MS RD Client to freerdp-shadow-cli (2.1.1) running on macOS 10.15.4 I got the screen for 1 second then went black. 

[14:43:33:217] [48766:1445edc0] [INFO][com.freerdp.core.listener] - Listening on [::]:3389
[14:43:56:230] [48766:02f3d000] [DEBUG][com.winpr.thread] - Thread running, setting to detached state!
[14:43:56:240] [48766:02e37000] [DEBUG][com.freerdp.core.nego] - RDP_NEG_REQ: RequestedProtocol: 0x0000000B
[14:43:56:240] [48766:02e37000] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
[14:43:56:240] [48766:02e37000] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:1
[14:43:56:240] [48766:02e37000] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
[14:44:06:702] [48766:02e37000] [INFO][com.freerdp.core.connection] - Accepted client: Catalin’s iPhone
[14:44:06:702] [48766:02e37000] [INFO][com.freerdp.core.connection] - Accepted channels:
[14:44:06:702] [48766:02e37000] [INFO][com.freerdp.core.connection] -  rdpdr
[14:44:06:702] [48766:02e37000] [INFO][com.freerdp.core.connection] -  rdpsnd
[14:44:06:702] [48766:02e37000] [INFO][com.freerdp.core.connection] -  cliprdr
[14:44:06:702] [48766:02e37000] [INFO][com.freerdp.core.connection] -  drdynvc
[14:44:06:702] [48766:02e37000] [INFO][com.freerdp.core.gcc] - Active rdp encryption level: NONE
[14:44:06:702] [48766:02e37000] [INFO][com.freerdp.core.gcc] - Selected rdp encryption method: NONE
[14:44:06:770] [48766:02e37000] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x1f size=37 channelId=1009)
[14:44:06:770] [48766:02e37000] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x14 size=41 channelId=1009)
[14:44:06:771] [48766:02e37000] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x14 size=41 channelId=1009)
[14:44:06:771] [48766:02e37000] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x28 size=41 channelId=1009)
[14:44:06:771] [48766:02e37000] [INFO][com.freerdp.client.shadow] - Client from ::ffff:192.168.0.215 is activated (1920x1080@32)
[14:44:06:774] [48766:02e37000] [DEBUG][com.freerdp.client.shadow] - initializing NSCodec encoder
[14:44:06:843] [48766:03043000] [DEBUG][com.freerdp.channels.rdpsnd.server] - Client requested sound quality: 0x0000
[14:44:06:843] [48766:02e37000] [INFO][com.freerdp.client.shadow] - Gfx Pipeline Opened
[14:44:06:897] [48766:03149000] [DEBUG][com.freerdp.client.shadow] - initializing H.264 encoder
[14:44:06:223] [48766:02e37000] [INFO][com.freerdp.primitives] - openCL: using platform=Apple device=Intel(R) HD Graphics 630
[14:44:06:233] [48766:02e37000] [DEBUG][com.freerdp.primitives] - primitives benchmark result:
[14:44:06:468] [48766:02e37000] [DEBUG][com.freerdp.primitives] -  * generic= 4
[14:44:07:674] [48766:02e37000] [DEBUG][com.freerdp.primitives] -  * optimized= 6
[14:44:07:831] [48766:02e37000] [DEBUG][com.freerdp.primitives] -  * opencl= 46
[14:44:07:831] [48766:02e37000] [INFO][com.freerdp.primitives] - primitives autodetect, using opencl
[OpenH264] this = 0x0x604000024010, Warning:ParamValidation(), AdaptiveQuant(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x604000024010, Warning:ParamValidation(), BackgroundDetection(1) is not supported yet for screen content, auto turned off
[OpenH264] this = 0x0x604000024010, Warning:bEnableFrameSkip = 0,bitrate can't be controlled for RC_QUALITY_MODE,RC_BITRATE_MODE and RC_TIMESTAMP_MODE without enabling skip frame.
[OpenH264] this = 0x0x604000024010, Warning:Change QP Range from(0,51) to (26,35)

**Comment by akallabeth** [comment]
Please provide some build information, there are lots of openh264 related errors in the log

**Comment by CataIin** [comment]
I'm running freerdp-shadow-cli 2.1.1 compiled with:

WITH_SSE2 "ON"
WITH_SANITIZE_ADDRESS "ON"
WITH_SERVER "ON"
WITH_X11 "OFF"
WITH_WAYLAND "OFF"
WITH_CUPS "OFF"
CHANNEL_URBDRC "OFF"
WITH_JPEG "OFF"
WITH_OPENH264 "ON"
WITH_OPENCL "ON"
WITH_SWSCALE "ON"
WITH_CAIRO "ON"
WITH_LIBSYSTEMD "OFF"
WITH_PAM "OFF"
WITH_FFMPEG "OFF"

-- The C compiler identification is AppleClang 11.0.3.11030032
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working C compiler: /Volumes/Data/Development/XCode/v11/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Volumes/Data/Development/XCode/v11/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Volumes/Data/Development/XCode/v11/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Volumes/Data/Development/XCode/v11/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
FREERDP_VERSION=2.1.1
-- Git Revision n/a
-- Performing Test Wno-deprecated-declarations
-- Performing Test Wno-deprecated-declarations - Success
-- Performing Test Wno-deprecated-declarationsCXX
-- Performing Test Wno-deprecated-declarationsCXX - Success
-- Performing Test fno-omit-frame-pointer
-- Performing Test fno-omit-frame-pointer - Success
-- Performing Test fsanitize-address
-- Performing Test fsanitize-address - Success
-- Performing Test fsanitize-blacklist
-- Performing Test fsanitize-blacklist - Success
-- Performing Test fsanitize-address-use-after-scope
-- Performing Test fsanitize-address-use-after-scope - Success
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Looking for pthread_mutex_timedlock
-- Looking for pthread_mutex_timedlock - not found
-- Looking for pthread_mutex_timedlock in pthread
-- Looking for pthread_mutex_timedlock in pthread - not found
-- Looking for pthread_mutex_timedlock in pthreads
-- Looking for pthread_mutex_timedlock in pthreads - not found
-- Looking for include file aio.h
-- Looking for include file aio.h - found
-- Looking for include file sys/eventfd.h
-- Looking for include file sys/eventfd.h - not found
-- Looking for include file sys/timerfd.h
-- Looking for include file sys/timerfd.h - not found
-- Looking for include file poll.h
-- Looking for include file poll.h - found
-- Looking for ceill
-- Looking for ceill - found
-- Skipping recommended feature libsystemd for systemd journal appender (allows to export wLog to systemd journal)
-- Skipping optional feature X11 for X11 (X11 client and server)
-- Enable feature X11 using "-DWITH_X11=ON"
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Finding required feature ZLIB for compression (data compression)
-- Found ZLIB: /usr/lib/libz.a (found version "1.2.11")
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: /Volumes/Data/Work/FreeRDP-2.1.1/external/macOS/openssl/lib/libssl.a;/Volumes/Data/Work/FreeRDP-2.1.1/external/macOS/openssl/lib/libcrypto.a (found version "1.1.1g")
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
-- Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature OSS for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Finding recommended feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Disable feature Pulse using "-DWITH_PULSE=OFF"
-- Checking for module 'libpulse'
-- No package 'libpulse' found
-- Could NOT find Pulse (missing: PULSE_INCLUDE_DIR PULSE_LIBRARY)
CMake Warning at cmake/FindFeature.cmake:46 (message):
feature Pulse was requested but could not be found! ON / FALSE
Call Stack (most recent call first):
CMakeLists.txt:845 (find_feature)

-- Skipping recommended feature Cups for printing (printer device redirection)
-- Finding recommended feature PCSC for smart card (smart card device redirection)
-- Disable feature PCSC using "-DWITH_PCSC=OFF"
-- Found PCSC: /Volumes/Data/Development/XCode/v11/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/PCSC.framework
-- Skipping optional feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
-- Enable feature FFmpeg using "-DWITH_FFMPEG=ON"
-- Skipping optional feature JPEG for codec (use JPEG library)
-- Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
-- Enable feature x264 using "-DWITH_X264=ON"
-- Finding optional feature OpenH264 for codec (use OpenH264 library)
-- Found OpenH264: /usr/local/Cellar/openh264/2.1.1/lib/libopenh264.dylib
-- Found OpenH264: /usr/local/Cellar/openh264/2.1.1/lib/libopenh264.dylib
-- Finding optional feature OpenCL for codec (use OpenCL library)
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: /Volumes/Data/Development/XCode/v11/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenCL.framework (found version "1.2")
-- Skipping optional feature GSM for codec (GSM audio codec library)
-- Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature LAME for codec (lame MP3 audio codec library)
-- Enable feature LAME using "-DWITH_LAME=ON"
-- Skipping optional feature FAAD2 for codec (FAAD2 AAC audio codec library)
-- Enable feature FAAD2 using "-DWITH_FAAD2=ON"
-- Skipping optional feature FAAC for codec (FAAC AAC audio codec library)
-- Enable feature FAAC using "-DWITH_FAAC=ON"
-- Skipping optional feature soxr for codec (SOX audio resample library)
-- Enable feature soxr using "-DWITH_SOXR=ON"
-- Skipping optional feature GSSAPI for auth (add kerberos support)
-- Enable feature GSSAPI using "-DWITH_GSSAPI=ON"
-- Using OpenSSL Version: 1.1.1g
using default plugins location
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for timer_create
-- Looking for timer_create - not found
-- Looking for timer_delete
-- Looking for timer_delete - not found
-- Looking for timer_settime
-- Looking for timer_settime - not found
-- Looking for timer_gettime
-- Looking for timer_gettime - not found
-- Checking for module 'cairo'
-- Found cairo, version 1.16.0
-- Found Cairo: /usr/local/Cellar/cairo/1.16.0_3/lib/libcairo.dylib
-- Checking for module 'libswscale'
-- Found libswscale, version 5.5.100
-- Found SWScale: /usr/local/include
-- Adding STATIC channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding DYNAMIC channel client "video": Video optimized remoting Virtual Channel Extension
-- Adding DEVICE channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding DEVICE channel client "serial": Serial Port Virtual Channel Extension
-- Adding STATIC channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding STATIC channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding DYNAMIC channel client "rdpgfx": Graphics Pipeline Extension
-- Adding DYNAMIC channel client "rdpei": Input Virtual Channel Extension
-- Adding STATIC channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding STATIC channel client "rdp2tcp": Tunneling TCP over RDP
-- Adding STATIC channel client "rail": Remote Programs Virtual Channel Extension
-- Adding DEVICE channel client "parallel": Parallel Port Virtual Channel Extension
-- Adding DYNAMIC channel client "geometry": Geometry tracking Virtual Channel Extension
-- Adding STATIC channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding DYNAMIC channel client server "echo": Echo Virtual Channel Extension
-- Adding DEVICE channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding DYNAMIC channel client "disp": Display Update Virtual Channel Extension
-- Adding STATIC channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding DYNAMIC channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Adding post-build NIB file generation event for MacFreeRDP-library
-- Adding post-build NIB file generation event for MacFreeRDP
-- Skipping recommended feature PAM for authentication (user authentication)
-- Configuring done
-- Generating done
-- Build files have been written to: /Volumes/Data/Work/FreeRDP-2.1.1
