### ISSUE TITLE
error due connecting from centos to Win10

### ISSUE THREAD

**Issue by coal1231525** [FreeRDP/FreeRDP#6235]
can't connect to win10Pro from CentOS 8

xfreerdp /size:1980x1024 /u:... /p:... +clipboard /f /bpp:32 /v:1.1.1.1 /log-level:trace
[21:36:19:203] [8457:8458] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[21:36:19:203] [8457:8458] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[21:36:19:204] [8457:8458] [DEBUG][com.freerdp.client.x11] - Searching for XInput pointer device
[21:36:19:204] [8457:8458] [DEBUG][com.freerdp.client.x11] - Pointer device: 6
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: FALSE
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: TRUE
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: TRUE
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core.nego] - Attempting NLA security
[21:36:19:206] [8457:8458] [DEBUG][com.freerdp.core] - connecting to peer 1.1.1.1
[21:36:34:222] [8457:8458] [ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_CONNECT_FAILED [0x00020006]
[21:36:34:222] [8457:8458] [ERROR][com.freerdp.core] - failed to connect to 1.1.1.1

This is FreeRDP version 2.0.0-rc4 (n/a)

xfreerdp /buildconfig
This is FreeRDP version 2.0.0-rc4 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=OFF WITH_SHADOW_MAC=OFF WITH_SHADOW_X11=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=OFF WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL
Compiler:            GNU, 8.2.1
Target architecture: x64

amd64

**Comment by akallabeth** [comment]
I´d check your firewall and see if the server and port are actually reachable from your end. this specific error occurs mostly due to dns lookup issues (which you don´t have due to using an IP) or tcp connect issues (not reachable destination)

**Comment by coal1231525** [comment]
> 
> 
> I´d check your firewall and see if the server and port are actually reachable from your end. this specific error occurs mostly due to dns lookup issues (which you don´t have due to using an IP) or tcp connect issues (not reachable destination)

the wireshark detects incoming packets to 3389 port

**Comment by akallabeth** [comment]
@coal1231525 and outgoing? If I´m not mistaken the thing you captured are `TCP` retransmissions which means the reply was not received...

**Comment by coal1231525** [comment]
> @coal1231525 and outgoing? If I´m not mistaken the thing you captured are `TCP` retransmissions which means the reply was not received...

fw settings on client (centos) is:
iptables -A FORWARD -d 192.168.1.70 -p tcp --dport 3389 -j ACCEPT

**Comment by akallabeth** [comment]
@coal1231525 ok, no, you need that on the server side...
