### ISSUE TITLE
Freerdp-2.1.1 Rail app name issue on Ubuntu 18.04/20.04

### ISSUE THREAD

**Issue by ganeshjkale** [FreeRDP/FreeRDP#6243]
Client OS:- Ubuntu-18.04_x64/Ubuntu-20.04_x64
Server OS:- Windows 2016
Freerdp Build Machine:- Xubuntu 16.04_x86

Note:-
1:-Client machine is on vmware workstation v15
2:-Tried /app-name no success

Scenario:-
1:-Launch remote app
2:-minimize ,maximize remote app
3:-observe remote app name in taskbar (RAIL:00050124)

cmdline:- 
/opt/freerdp2/bin/xfreerdpbin /cert-ignore /title:test   "/app:||AppLauncher" /app-cmd:'2 0 4dad55b1-5c79-4dc3-9829-da88056354cf 352bafd2-7506-42a4-a5b4-1f6e7607e5c1 3ee59afb-9aea-459d-9bab-96c0e9baa35e'  /d:test  /u:"test" /v:x.x.x.x:3389 /p:test@123 /log-level:TRACE 2>&1 |tee rail_issue.txt

Attached Trace log:- 
[rail_issue.txt](https://github.com/FreeRDP/FreeRDP/files/4700291/rail_issue.txt)

Attached Screenshot:-
![Screenshot_2020-05-29_13-09-51](https://user-images.githubusercontent.com/8046158/83234403-d0a35280-a1ad-11ea-921f-e7d82bd541c4.png)

**Comment by akallabeth** [comment]
Currently not implemented, pull requests welcome.
