### ISSUE TITLE
smart-sizing AND full screen not working

### ISSUE THREAD

**Issue by marria05** [FreeRDP/FreeRDP#6249]
I'm trying to make the smart-sizing function work when a client is in full screen mode. I have a windows 10 virtual machine that I'm trying to connect to from a Debian 10 host. If I enter the following:

`xfreerdp /u:username /p:password /v:192.168.0.101 /f /size:1024x768 /smart-sizing:1600x1200`

I get a full screen session, but the remote resolution is then set to the local resolution of the Debian host. If I omit the `/f` then the scaling works as it should, with the remote session running at 1024x768 but scaled up to 1600x1200, but I then have an annoying titlebar at the top of the screen from FreeRDP. If I hit Ctrl-Alt-Enter, the client then goes full screen and works as anticipated.

I've tried the version of FreeRDP as supplied by the distro **(2.0.0-dev 5 2693389a+debian)** and I've also compiled a version from the git master and they both behave in the same way.

What am I doing wrong? I'm calling the client from a script, so I could potentially fake the Ctrl-Alt-Enter after startup, but that's a horrible idea.

**Comment by akallabeth** [comment]
@marria05 that functionality is just not there. You might use rdp high dpi support instead (see the scale options) to tell the remote end you have a high dpi monitor

**Comment by marria05** [comment]
@akallabeth, sorry, I don't understand. It seems to me that this functionality is there, but for some reason it's overridden on startup. If specifying `/f` on the command is meant to override the smart scaling functionality, why then, does it work if I omit the command line argument and then enable fullscreen during runtime by pressing Ctrl+Alt+Enter or sending an `xdotool search --class "freerdp" key Ctrl+Alt+Enter`. Surely there's a discrepancy here?

I ended up modifying `xf_pre_connect`:

```
diff --git a/client/X11/xf_client.c b/client/X11/xf_client.c
index 146c7feea..ef0c833f5 100644
--- a/client/X11/xf_client.c
+++ b/client/X11/xf_client.c
@@ -1211,7 +1211,7 @@ static BOOL xf_pre_connect(freerdp* instance)

        xf_detect_monitors(xfc, &maxWidth, &maxHeight);

-       if (maxWidth && maxHeight)
+       if (maxWidth && maxHeight && !settings->Fullscreen && settings->SmartSizing)
        {
                settings->DesktopWidth = maxWidth;
                settings->DesktopHeight = maxHeight;
@@ -1223,13 +1223,13 @@ static BOOL xf_pre_connect(freerdp* instance)
         * If /f is specified in combination with /smart-sizing:widthxheight then
         * we run the session in the /smart-sizing dimensions scaled to full screen
         */
-       if (settings->Fullscreen && settings->SmartSizing && settings->SmartSizingWidth &&
+/*     if (settings->Fullscreen && settings->SmartSizing && settings->SmartSizingWidth &&
            settings->SmartSizingHeight)
        {
                settings->DesktopWidth = settings->SmartSizingWidth;
                settings->DesktopHeight = settings->SmartSizingHeight;
        }
-
+*/
 #endif
        xfc->fullscreen = settings->Fullscreen;
        xfc->decorations = settings->Decorations;
```

This stops the client setting the remote resolution to the local resolution when you specify full screen from the command line while using smart scaling.

I suppose I could add an additional command line option to enable a `/scaledfullscreen` option. So that `/f` still operates as was.

**Comment by akallabeth** [comment]
@marria05 ok, reread your first post and realized I misinterpreted. you just use it wrong ^^
`/smart-sizing:<width>x<height>` is activating `smart-sizing` and the resolution is the `remote` resolution, now what you locally have.
Help could use some better wording to explain that.

**Comment by calvinkevin14** [comment]
Hi,

I have the same problem.
This change finally got published?

**Comment by akallabeth** [comment]
@calvinkevin14 you mean just leaving out `/size:<width>x<height>` to not override the `/smart-sizing` resolution?
something like `xfreerdp /v:<host> /u:<user> /p:<pwd> /smart-sizing:1400x1080 /f` works mighty fine ;)

**Comment by bluegroper** [comment]
xfreerdp /v:<host> /u:<user> /p:<pwd> **/size:100%** 
Seems to work nicely too.  YMMV
