### ISSUE TITLE
webcam audio

### ISSUE THREAD

**Issue by trentasis** [FreeRDP/FreeRDP#6254]
Hi,

I have problem with audio from a webcam, audio is not valid on both sides, but in same RDP session if you run a youtube video works greats, but seems that sound with mic on a webcam not working..

Tried multiple options like but all failing 

 xfreerdp /cert-ignore /sec:tls /vc:ftrdpbr /v:10.10.10.2 /u:user /d:dom /f /sound /mic

also tried
 xfreerdp /cert-ignore /sec:tls /vc:ftrdpbr /v:10.10.10.2 /u:user /d:dom /f /sound /mic /microphone
 xfreerdp /cert-ignore /sec:tls /vc:ftrdpbr /v:10.10.10.2 /u:user /d:dom /f /sound:sys:alsa /mic:sys:alsa
 xfreerdp /cert-ignore /sec:tls /vc:ftrdpbr /v:10.10.10.2 /u:user /d:dom /f /sound:sys:pulse /mic:sys:pulse

Any suggestion how to solve this audio issues with webcam?

Thanks

**Comment by akallabeth** [comment]
All local sound devices work if they work locally. Check if you selected the correct input device.
(Only exception is if you use `/usb` which redirects the whole USB device to the server before the local os can do anything with it)
