### ISSUE TITLE
crash on smartcard auth to Win 2008 R2 farm (and ugly workaround)

### ISSUE THREAD

**Issue by jaroslawp** [FreeRDP/FreeRDP#626]
Hello,

freerdp crashes with a segfault while using scard auth against Win 2008 R2 farm (works OK connecting to W 2003 one ...),
on Red Hat Enterprise Linux 6.2.

After some tracing I've discovered it happens in handle_Transmit() stream_read_uint32(irp->input, map[6]) in scard_operations.c, commenting it out fixes the problem for me and does not seem to affect smart card operation in any way.

Now .. this is rather an quite ugly workaround, not a real fix, but  ... I'm not able to figure out what is it trying to read .. and this data seems unused .. perhaps somebody knows real solution ??

Jarek

```
   if (map[4] & SCARD_INPUT_LINKED)
    {
            /* recvPci */
            stream_read_uint32(irp->input, linkedLen);

            stream_read_uint32(irp->input, pioRecvPci.dwProtocol);
            stream_seek(irp->input, linkedLen - 4);

            sc_input_repos(irp, linkedLen);

/*              stream_read_uint32(irp->input, map[6]); */ 
            map[6]=NULL;
            if (map[6] & SCARD_INPUT_LINKED)
            {
                    /* not sure what this is */
                    stream_read_uint32(irp->input, linkedLen);
                    stream_seek(irp->input, linkedLen);

                    sc_input_repos(irp, linkedLen);
            }
            pioRecvPci.cbPciLength = sizeof(SCARD_IO_REQUEST);
            pPioRecvPci = &pioRecvPci;
   }
    else
```

**Comment by sconstantine** [comment]
Any progress or updates to smart card redirection?  (different from authentication which works fine for me, talking about the actual redirection of the card services into the RD session)

**Comment by frispete** [comment]
Well, I do this since ages - but I'm still on 1.0 with the applied workaround using a pretty common USB device (here in Germany) called mIDentity. For reference, you can find my builds here:
https://build.opensuse.org/project/show/home:frispete:RemoteDesktop
Be aware, that the 1.1 and 1.2 codebase is outdated. Every time, I tried to went upstairs, hard to track down stability problems dropped me back. Unfortunately, I'm too time restricted to dive deeper..

**Comment by sconstantine** [comment]
Thanks for the reply @frispete; is there a way I can use your builds on OS X?  Pardon my inexperience here...

**Comment by frispete** [comment]
Well, I'm not experienced enough for this kind of stuff in the OS X eco system. Sorry.

**Comment by sconstantine** [comment]
Update:  Purchased the Omni 3021 and Smartcard redirection works with a custom build of developer Felix's LMFreeRDPClient on OS X 10.11.2.  It is, however, still broken for me within Royal TSX and FreeRDP v2.2.1.1

**Comment by lemonmojo** [comment]
@sconstantine In the regular Royal TSX release I'm still using an old version of FreeRDP that doesn't include the recent changes to the smart card stuff because of other issues.
I will however try to integrate a current FreeRDP release into the first Royal TSX V3 beta.

**Comment by lemonmojo** [comment]
@sconstantine The first Royal TSX V3 beta is now available at https://www.royalapplications.com/ts/osx/features-beta

**Comment by bmiklautz** [comment]
@lemonmojo @sconstantine please use the Royal TSX forum/list/.. for Royal TSX related stuff.
Thank you.

**Comment by lemonmojo** [comment]
@bmiklautz Sorry, didn't want to turn this into a Royal TSX thread...

**Comment by bmiklautz** [comment]
@lemonmojo no prob just mentioned it ;)

**Comment by jaroslawp** [comment]
looks like nobody cares since FIVE years.

**Comment by bmiklautz** [comment]
@jaroslawp smard code was rather re-written since the initial report. Did you try with a recent version lately?
