### ISSUE TITLE
Fullscreen "-floatbar" issues (focus, rendering) in version 2.0.0

### ISSUE THREAD

**Issue by jgehrig** [FreeRDP/FreeRDP#6261]
A recent change has broken `-floatbar`, and there are focus issues with this option.

I first noticed this machine on my Gentoo Box. I could "resolve" the issue with a package version block/downgrade. The first version I blocked was `net-misc/freerdp-2.0.0-r1`

**To Reproduce**
1. Run command `xfreerdp -floatbar {SOME_MACHINE_IP}
2. Notice there is no floatbar when you hover over the top part of the screen.
3. Enter fullscreen mode with `Ctrl + Alt + Enter`
4. Hover over the top edge of the screen, where the floatbar would be. The floatbar may intermittently appear. Buttons may be missing. Dependent on mouse speed?
5. Notice focus is lost. Losing focus can cause a panel/window to overlap the floatbar. Bug.
6. Notice the floatbar is rendererd despite `-floatbar`. Bug.

**Expected behavior**
Moving the mouse near the top of the screen should not cause focus loss. This can block the floatbar from being used.

The floatbar should never appear with `-floatbar`.

**Screenshots**
Here is an MP4 screen recording: [Screen Capture.zip](https://github.com/FreeRDP/FreeRDP/files/4731911/Screen.Capture.zip)

Sorry for the bad recording. My usual tool doesn't capture full screen well.

At first I am slowly moving my mouse up against the top edge of the screen. The toolbar does not appear.

After that I rapidly bump my mouse up against the top edge of the screen. The toolbars go wild, and the popup menu appears button by button (strange).

The remote machine (Win10) has Chrome open in FullScreen mode. You can tell my mouse is up against of the edge when the X appears.

**Application details**
```
$ xfreerdp /version
This is FreeRDP version 2.1.1 (2.1.1)
```
```
This is FreeRDP version 2.1.1 (2.1.1)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=OFF WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Gentoo
CFLAGS:              -march=native -O2 -pipe -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 9.3.0
Target architecture: x64
* FreeRDP version (`xfreerdp /version`)
* Command line used
* Output of `xfreerdp /buildconfig`
* OS version connecting to (server side)
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help
```
Full Command Used (user info omitted):
```
xfreerdp +auto-reconnect +clipboard +compression +smart-sizing -floatbar -glyph-cache -themes -wallpaper /audio-mode:0 /bpp:8 /compression-level:1 /jpeg /jpeg-quality:85% /network:autodetect /sec:tls /smart-sizing:1920x1080 /w:1920 /h:1080 /v:{IP_OMITTED} /u:{USER_OMITTED} /d:{DOMAIN_OMITTED}
```

**Comment by akallabeth** [comment]
@jgehrig please check the help output of `xfrerdp` regarding `floatbar`.
A few years ago the flag was changed during development from a `flag` to an `optional value` type

**Comment by jgehrig** [comment]
@akallabeth Thanks for the quick response!

Sorry, I can't figure out an equivalent for `-floatbar` from the man page. Is adding nothing the correct option in this case?

The `--help` message doesn't seem to have a `show:never` option or equivalent:
```
/floatbar[:sticky:[on|off],default:[visible|hidden],show:[always|fullscreen||window]]
```

Also, `-floatbar` still appears to have an impact... The behavior of: no `floatbar` argument, `/floatbar:{options}`, and `-floatbar` all behave differently?

Second. I think you've still got a focus issue with the floatbar feature.
![image](https://user-images.githubusercontent.com/11207308/83895292-7d3a8280-a720-11ea-9282-fa4d22bc1709.png)

Notice my Plasma Panel overlaps the floatbar. This issue does not occur in other fullscreen programs (Chrome for example). This looks like a real bug to me.

Also, is the floatbar supposed to render like this with only some buttons?
![image](https://user-images.githubusercontent.com/11207308/83896231-cd661480-a721-11ea-82b4-62a3957ff881.png)

**Comment by akallabeth** [comment]
@jgehrig yes, if you don´t want it, just don't add it. As for the `-` ambiguity, there is still a bug in the command line design, so that is annoying but expected.
As for focus and drawing, need to check with plasma, using mostly gnome/cinnamon/openbox here

**Comment by jgehrig** [comment]
@akallabeth 

> yes, if you don´t want it, just don't add it. As for the - ambiguity, there is still a bug in the command line design, so that is annoying but expected.

Sounds fine to me. Thanks for the clarification!

> As for focus and drawing, need to check with plasma, using mostly gnome/cinnamon/openbox here

Let me know where to look in the codebase, and I can try to diagnose the issue on my KDE/Plasma machine.
