### ISSUE TITLE
BadLength (poly request too large or internal Xlib length error)

### ISSUE THREAD

**Issue by hpschry** [FreeRDP/FreeRDP#6264]
when using xfreerdp with Windows 10 and using the gadwin screen capture tool xfreerdp consistently fails with BadLength X error.

**To Reproduce**
1. Connect to Windows 10 
2. Use the gadwin screen capture tool on the windows 10 host
3. Try to capture part of the screen, move the rectangle around or resize or directly click the accept check mark *on the windows host to that I'm connected to with xfreerdp* 
4. Error in xfreerdp (on ubuntu): 
X Error of failed request:  BadLength (poly request too large or internal Xlib length error)
  Major opcode of failed request:  18 (X_ChangeProperty)
  Serial number of failed request:  46592253
  Current serial number in output stream:  46592254
Note: there might be other opcodes, however they are always related  to BadLength.
5. Interestingly, when I reconnect to the windows host I can complete the screen capture operation on the windows host in most cases.

**Expected behavior**
Continue operation, don't crash.

**Application details**
* This is FreeRDP version 2.1.1 (n/a)
* xfreerdp /multimon /u:$user /v:$host /bpp:16 +auto-reconnect /auto-reconnect-max-retries:20 +clipboard 
* Output of `xfreerdp /buildconfig`
This is FreeRDP version 2.1.1 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RELWITHDEBINFO
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp2-Se4yPM/freerdp2-2.1.1+dfsg1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler:            GNU, 9.3.0
Target architecture: x64

* OS version connecting to (server side) 
Windows 10 Enterprise LTSC 

* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
(will be attached or can be provided)

**Environment (please complete the following information):**
 - OS: Ubuntu 
 - Version/Distribution: 20.04
 - Architecture: amd64

**Comment by hpschry** [comment]
[log.txt](https://github.com/FreeRDP/FreeRDP/files/4736526/log.txt)

**Comment by akallabeth** [comment]
This sounds a lot like something regarding the screen capture tool interferes with `X11`.
Can only find references to faulty graphics drivers on a fast search for this issue.
did you check with the people from the screen capture tool?

**Comment by hpschry** [comment]
Hmm, the screen capture tool is run on the windows host, xfreerdp run from my ubuntu machine.

**Comment by hpschry** [comment]
[log.txt](https://github.com/FreeRDP/FreeRDP/files/4739866/log.txt)

**Comment by akallabeth** [comment]
@hpschry ah, ok, then it has nothing to do with the issue at all. I´d check local hardware and drivers (as the message suggests this is something related to internal X11 stuff)
`xfreerdp` is more or less only drawing a video locally, so I´d check if the error goes away if you use `/rfx` or `/gfx` or both (I doubt it, but you never know)

**Comment by hpschry** [comment]
Hi, it has to do with the issue as using this on the windows host reliably causes the crash on the ubuntu side. However, I'll try the options you recommend.

**Comment by akallabeth** [comment]
@hpdevx well, then we have a good way to reproduce.
but drawing operations are done to a bitmap internally in any case and only changed rectangles are drawn via X11 bitmaps to screen.
biggest difference could be using `/gdi:hw` which switches on direct mapping of `gdi` operations to `X11` operations (disabled by default because it has some drawbacks regarding function support)

So, if there is a crash like this it means that your local driver can not handle some operation (maybe a too large bitmap as you´re using `/multimon`?)

**Comment by hpschry** [comment]
/gdi:hw seems to make it slightly better, but after some resizing it crashed again. In general the bitmaps to be captured are only part of one screen. Happens also  with small screen sections.
/rfx the same
/gfx the same
/rfx and /gfx combined the same

**Comment by akallabeth** [comment]
@hpschry so, any details on your client side hardware as the other lead is graphics drivers / X11 related stuff?

**Comment by hpschry** [comment]
(let me know, if the following is sufficient or what else you might need)

26:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef) (prog-if 00 [VGA controller])
        Subsystem: Sapphire Technology Limited Radeon RX 570 Pulse 4GB
        Flags: bus master, fast devsel, latency 0, IRQ 81
        Memory at e0000000 (64-bit, prefetchable) [size=256M]
        Memory at f0000000 (64-bit, prefetchable) [size=2M]
        I/O ports at e000 [size=256]
        Memory at fce00000 (32-bit, non-prefetchable) [size=256K]
        Expansion ROM at fce40000 [disabled] [size=128K]
        Capabilities: [48] Vendor Specific Information: Len=08 <?>
        Capabilities: [50] Power Management version 3
        Capabilities: [58] Express Legacy Endpoint, MSI 00
        Capabilities: [a0] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [100] Vendor Specific Information: ID=0001 Rev=1 Len=010 <?>
        Capabilities: [150] Advanced Error Reporting
        Capabilities: [200] Resizable BAR <?>
        Capabilities: [270] Secondary PCI Express
        Capabilities: [2b0] Address Translation Service (ATS)
        Capabilities: [2c0] Page Request Interface (PRI)
        Capabilities: [2d0] Process Address Space ID (PASID)
        Capabilities: [320] Latency Tolerance Reporting
        Capabilities: [328] Alternative Routing-ID Interpretation (ARI)
        Capabilities: [370] L1 PM Substates
        Kernel driver in use: amdgpu
        Kernel modules: amdgpu

dmesg is saying:
[drm] Detected VRAM RAM=8192M, BAR=256M

**Comment by hpschry** [comment]
What else could I provide?

**Comment by akallabeth** [comment]
@hpschry sorry, thought I answered this, nothing I could find.
My money is still on a problem with your hardware/driver combination, something `internal` as the name suggests.
just don´t have any idea what we could do on our side.

**Comment by niikoo** [comment]
Happens when I use ´/multimon´ and the screen resolution is high on both screens.

**Comment by akallabeth** [comment]
might be of interest, #8737 works around such an issue for `XChangeProperty` if the `Xlib` does not like the size of data. May not be the same, but still of interest.

**Comment by akallabeth** [comment]
@battjt still a x11 limitation :/
