### ISSUE TITLE
[wfreerdp] -grab-keyboard does not work on Windows client

### ISSUE THREAD

**Issue by casper** [FreeRDP/FreeRDP#6265]
**Describe the bug**
-grab-keyboard does not work on the Windows client. The keyboard is grabbed regardless of the +-grab-keyboard switch.

**To Reproduce**
wfreerdp /u:xxx /p:xxx -grab-keyboard /v:xxx

**Expected behavior**
Work like the Windows native RDC, where key combinations are sent to the host and not to the remote server.

**Application details**
FreeRDP version 2.1.1 (2.1.1)

Built with MSVC 2010:

-DBUILD_SHARED_LIBS=OFF -DWITH_X264=OFF -DWITH_OPENH264=OFF -DWITH_MEDIA_FOUNDATION=OFF -DWITH_FFMPEG=OFF -DWITH_GFX_H264=OFF -DCHANNEL_URBDRC=OFF -DMONOLITHIC_BUILD=ON -DWITH_SSE2=ON -DBUILD_TESTING=OFF
   
Build type:          Release
CFLAGS:              /DWIN32 /D_WINDOWS  /Gd /W3
Compiler:            MSVC, 16.0.40219.1
Target architecture: x86

**Comment by akallabeth** [comment]
windows client will be replaced with `sdl-freerdp`. that one supports keyboard grab
