### ISSUE TITLE
Using winpr library headers with clang

### ISSUE THREAD

**Issue by paluke** [FreeRDP/FreeRDP#6271]
I'm trying to port some big program from Windows to Linux and I want to use winpr library. The program compiles with clang and I have some problems with winpr headers.

In spec.h threre is `#define __declspec(e) __attribute__((e))`
I need __declspec for other purposes, so I remore this define, and modify define DECLSPEC_NORETURN:

```
#ifndef DECLSPEC_NORETURN
#if (defined(__GNUC__) || defined(__clang__))
#define DECLSPEC_NORETURN __attribute__((noreturn))
#elif defined(_MSC_VER)
#define DECLSPEC_NORETURN __declspec(noreturn)
#else
#define DECLSPEC_NORETURN
#endif
#endif /* DECLSPEC_NORETURN */


```
The functions _rotr and _rotl are declared in crt.h but clang has built-in functions with such names that lead to compilation errors.

I replaced this snippet with the following:

```
#ifndef __has_builtin
  #define __has_builtin(x) 0  // Compatibility with non-clang compilers.
#endif

#if !defined(_rotl) && !__has_builtin(_rotl)
static INLINE UINT32 _rotl(UINT32 value, int shift)
{
	return (value << shift) | (value >> (32 - shift));
}
#endif

#if !defined(_rotl64) && !__has_builtin(_rotl64)
static INLINE UINT64 _rotl64(UINT64 value, int shift)
{
	return (value << shift) | (value >> (64 - shift));
}
#endif

#if !defined(_rotr) && !__has_builtin(_rotr)
static INLINE UINT32 _rotr(UINT32 value, int shift)
{
	return (value >> shift) | (value << (32 - shift));
}
#endif

#if !defined(_rotr64) && !__has_builtin(_rotr64)
static INLINE UINT64 _rotr64(UINT64 value, int shift)
{
	return (value >> shift) | (value << (64 - shift));
}
#endif
```

And also, in wtypes.h defined types __int8, __int16, __int32 and __int64, which are built-in types in clang. I just replace them with int8_t ... int64_t, but not sure if this is the right way.

**Comment by akallabeth** [comment]
@paluke please use the mailing list or IRC for support.
`clang` can compile the library quite fine (in fact the pull request tester just does that), you´re just lacking the right `CMake` definitions for your platform I assume?
