### ISSUE TITLE
https://pub.freerdp.com/ invalid cert

### ISSUE THREAD

**Issue by blshkv** [FreeRDP/FreeRDP#6279]
the cert has expired last year, users are unable to download the release:
https://pub.freerdp.com/releases/freerdp-2.1.1.tar.gz

**Comment by bmiklautz** [comment]
@blshkv the autorenewal didn't work after a server upgrade. The certificate is invalid since `Friday, 12. June 2020`

**Comment by bmiklautz** [comment]
Fixed. Thank you for brining that up. I've added a monitoring for the certificate now.

**Comment by blshkv** [comment]
Sorry, didn't check the message properly. Thanks!
