### ISSUE TITLE
Freerdp-2.1.1 (and -current) build failed - fatal error LNK1169

### ISSUE THREAD

**Issue by CataIin** [FreeRDP/FreeRDP#6280]
C:\FreeRDP\build-x64>cmake -Wno-dev -DBUILD_SHARED_LIBS=OFF -DWITH_X264=OFF -DWITH_OPENH264=OFF -DWITH_MEDIA_FOUNDATION=OFF -DWITH_FFMPEG=OFF -DWITH_GFX_H264=OFF -DCHANNEL_URBDRC=OFF -G "Visual Studio 14 2015 Win64" -DMSVC_RUNTIME="static" -DWITH_SSE2=ON -DBUILD_TESTING=OFF -DWITH_SERVER=ON -DOPENSSL_ROOT_DIR="c:\FreeRDP\external\windows\openssl" ..

C:\FreeRDP\build-x64>cmake --build .
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  winpr.vcxproj -> C:\FreeRDP\build-x64\Debug\winpr2.lib
  freerdp.vcxproj -> C:\FreeRDP\build-x64\Debug\freerdp2.lib
  audin-client.vcxproj -> C:\FreeRDP\build-x64\Debug\audin-client.lib
  audin-client-winmm.vcxproj -> C:\FreeRDP\build-x64\Debug\audin-client-winmm.lib
  audin-server.vcxproj -> C:\FreeRDP\build-x64\Debug\audin-server.lib
  cliprdr-client.vcxproj -> C:\FreeRDP\build-x64\Debug\cliprdr-client.lib
  cliprdr-server.vcxproj -> C:\FreeRDP\build-x64\Debug\cliprdr-server.lib
  disp-client.vcxproj -> C:\FreeRDP\build-x64\Debug\disp-client.lib
  disp-server.vcxproj -> C:\FreeRDP\build-x64\Debug\disp-server.lib
  drdynvc-client.vcxproj -> C:\FreeRDP\build-x64\Debug\drdynvc-client.lib
  drdynvc-server.vcxproj -> C:\FreeRDP\build-x64\Debug\drdynvc-server.lib
  drive-client.vcxproj -> C:\FreeRDP\build-x64\Debug\drive-client.lib
  echo-client.vcxproj -> C:\FreeRDP\build-x64\Debug\echo-client.lib
  echo-server.vcxproj -> C:\FreeRDP\build-x64\Debug\echo-server.lib
  encomsp-client.vcxproj -> C:\FreeRDP\build-x64\Debug\encomsp-client.lib
  encomsp-server.vcxproj -> C:\FreeRDP\build-x64\Debug\encomsp-server.lib
  freerdp-channels-server.vcxproj -> C:\FreeRDP\build-x64\Debug\freerdp-channels-server.lib
  geometry-client.vcxproj -> C:\FreeRDP\build-x64\Debug\geometry-client.lib
  printer-client.vcxproj -> C:\FreeRDP\build-x64\Debug\printer-client.lib
  printer-client-win.vcxproj -> C:\FreeRDP\build-x64\Debug\printer-client-win.lib
  rail-client.vcxproj -> C:\FreeRDP\build-x64\Debug\rail-client.lib
  rdp2tcp-client.vcxproj -> C:\FreeRDP\build-x64\Debug\rdp2tcp-client.lib
  rdpdr-client.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpdr-client.lib
  rdpei-client.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpei-client.lib
  rdpgfx-client.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpgfx-client.lib
  rdpsnd-client.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpsnd-client.lib
  rdpsnd-client-fake.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpsnd-client-fake.lib
  rdpsnd-client-proxy.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpsnd-client-proxy.lib
  rdpsnd-client-winmm.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpsnd-client-winmm.lib
  remdesk-client.vcxproj -> C:\FreeRDP\build-x64\Debug\remdesk-client.lib
  smartcard-client.vcxproj -> C:\FreeRDP\build-x64\Debug\smartcard-client.lib
  video-client.vcxproj -> C:\FreeRDP\build-x64\Debug\video-client.lib
  freerdp-client.vcxproj -> C:\FreeRDP\build-x64\Debug\freerdp-client2.lib
  rail-server.vcxproj -> C:\FreeRDP\build-x64\Debug\rail-server.lib
  rdpdr-server.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpdr-server.lib
  rdpei-server.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpei-server.lib
  rdpgfx-server.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpgfx-server.lib
  rdpsnd-server.vcxproj -> C:\FreeRDP\build-x64\Debug\rdpsnd-server.lib
  remdesk-server.vcxproj -> C:\FreeRDP\build-x64\Debug\remdesk-server.lib
  freerdp-server.vcxproj -> C:\FreeRDP\build-x64\Debug\freerdp-server2.lib
rail-client.lib(rail_orders.obj) : error LNK2005: rail_send_pdu already defined in rail-server.lib(rail_main.obj) [C:\FreeRDP\build-x64\server\proxy\fr
eerdp-proxy.vcxproj]
     Creating library C:/FreeRDP/build-x64/Debug/freerdp-proxy.lib and object C:/FreeRDP/build-x64/Debug/freerdp-proxy.exp
C:\FreeRDP\build-x64\Debug\freerdp-proxy.exe : fatal error LNK1169: one or more multiply defined symbols found [C:\FreeRDP\build-x64\server\proxy\freer
dp-proxy.vcxproj]
  rdtk.vcxproj -> C:\FreeRDP\build-x64\Debug\rdtk.lib
  winpr-tools.vcxproj -> C:\FreeRDP\build-x64\Debug\winpr-tools2.lib
  freerdp-shadow.vcxproj -> C:\FreeRDP\build-x64\Debug\freerdp-shadow2.lib
  freerdp-shadow-subsystem.vcxproj -> C:\FreeRDP\build-x64\Debug\freerdp-shadow-subsystem2.lib
  freerdp-shadow-cli.vcxproj -> C:\FreeRDP\build-x64\Debug\freerdp-shadow-cli.exe
  freerdp-shadow-cli.vcxproj -> C:/FreeRDP/build-x64/Debug/freerdp-shadow-cli.pdb (Full PDB)
  wfreerdp-client.vcxproj -> C:\FreeRDP\build-x64\Debug\wfreerdp.exe
  wfreerdp-client.vcxproj -> C:/FreeRDP/build-x64/Debug/wfreerdp.pdb (Full PDB)
  wfreerdp-server.vcxproj -> C:\FreeRDP\build-x64\Debug\wfreerdp-server.lib
LINK : fatal error LNK1149: output filename matches input filename 'C:\FreeRDP\build-x64\Debug\wfreerdp-server.lib' [C:\FreeRDP\build-x64\server\Window
s\cli\wfreerdp-server-cli.vcxproj]
  winpr-hash.vcxproj -> C:\FreeRDP\build-x64\Debug\winpr-hash.exe
  winpr-hash.vcxproj -> C:/FreeRDP/build-x64/Debug/winpr-hash.pdb (Full PDB)
  winpr-makecert.vcxproj -> C:\FreeRDP\build-x64\Debug\winpr-makecert.exe
  winpr-makecert.vcxproj -> C:/FreeRDP/build-x64/Debug/winpr-makecert.pdb (Full PDB)

C:\FreeRDP\build-x64>

**Comment by akallabeth** [comment]
Sorry, picking random `CMake` flags and just expecting it works will not do ;)

Please use mailing list or IRC for build support.
