### ISSUE TITLE
Windows runtime bug

### ISSUE THREAD

**Issue by flacman** [FreeRDP/FreeRDP#6281]
**Describe the bug**
Sorry, i'm a bit new in this github submiting issues stuff. 
While running on windows, no connections can't be made becasue sockets are not initialized. (WSAStartup)

**To Reproduce**
Just compile on windows and run any version.

**FIX**

Line 1063: method int freerdp_tcp_connect(rdpContext* context, rdpSettings* settings, const char* hostname, int port, int timeout)
Add at the begining:

#ifndef _WIN32
WSADATA wsaData;
WSAStartup(MAKEWORD(2, 2), &wsaData);
#endif

Also, as another fix for compatibility, replace functions like sscanf to sscanf_s, sprintf to sprintf_s, etc. (just in windows, while compiling with VS2015+)

Hope this helps, i have a full working version compiled if you need more info.

**Comment by akallabeth** [comment]
sorry, what did you start?
`WSAStartup` is called by all clients and servers implemented so there is something else wrong here...
