### ISSUE TITLE
freerdp will not open on kali 

### ISSUE THREAD

**Issue by chrisreddersen** [FreeRDP/FreeRDP#6288]
I am attempting to use FreeRDp on Kali 2020.2
I run command :
![image](https://user-images.githubusercontent.com/39147103/84816539-886b9900-afd1-11ea-9efd-ab6dc03b1831.png)
After install : 
xfreedrp --version (or any command for that matter) 
xfreerdp: symbol lookup error: /lib/x86_64-linux-gnu/libfreerdp-client2.so.2: undefined symbol: msusb_msconfig_write
I have looked all over for a solution but cannot find one. Any help would be appreaciated.

**Comment by bmiklautz** [comment]
@chrisreddersen that looks like an packaging/build issue. Possibly some missing dependencies. 

Please report that in your distributions issue tracker.
Otherwise there is unfortunately not much we can do.
