### ISSUE TITLE
Need an easy way to express gratitude for this awesome software

### ISSUE THREAD

**Issue by old-o** [FreeRDP/FreeRDP#6292]
**Is your feature request related to a problem? Please describe.**

I wanted to express my gratitude for this awesome software. I use xfreerdp on Debian stable to connect to my work desktop (Win 10) and everything works flawlessly. I love it!

**Describe the solution you'd like**

Maybe publish an email address for giving positive feedback (praise, kudos, success stories) to the developers? I am sure you could also add a little section on the freerdp website to quote samples from that feedback. It might feel good to highlight some of those messages of appreciation.

**Describe alternatives you've considered**

I know about the mailing list, but since I wasn't planning to join development, I decided not to subscribe.

I have no experience with IRC, that's why I didn't use that channel.
 
**Additional context**

I love xfreerdp and use it every day.

**Comment by akallabeth** [comment]
@odoepner thank you for the praise. We´ll look into that as we are already preparing some more feedback options (for security reports as well)

**Comment by roms2000** [comment]
Same here :)
This is an awesome software and growing fast !
My users (more than 210) are using it every day and they even don't know that is FreeRDP !

**Comment by akallabeth** [comment]
so, it is 2024 now and we have:
* matrix channel to get into contact
* security contact mail address
* and, of course, github discussions

hope that is good enough :)
