### ISSUE TITLE
Support RandR to query for attached monitors

### ISSUE THREAD

**Issue by yringler** [FreeRDP/FreeRDP#6293]
**Is your feature request related to a problem? Please describe.**
xfreerdp multimon doesn't work with i3, and I don't think lxqt either, and probably more. Maybe moving to RandR from Xinerama would help.

**Describe the solution you'd like**
xfreerdp moves to RandR

**Describe alternatives you've considered**
1. Using lxde. Lxde (or openbox) supports NET_WM_FULLSCREEN_MONITORS - but it's an older DE, and in general it's annoying to have to switch DEs for one program
2. Starting up i3 with xinerama - i3 won't work as well, and it's one more thing to configure, sometimes starting xinerama, sometimes starting with RandR

**Additional context**
First of all, xfreerdp is incredible! Thank you for creating/maintaining it.
I think this is something which has been discussed before, on both this repository (possibly https://github.com/FreeRDP/FreeRDP/issues/2707) and on the [i3](https://github.com/i3/i3l) repository (https://github.com/i3/i3/issues/2116), so I apologize if this is just creating noise.
However, I felt that it would be appropriate to bring the issue up, perhaps more explicitly.

I opened an issue https://github.com/i3/i3/issues/4118, and the TL;DR was
>  NET_WM_FULLSCREEN_MONITORS requires Xinerama while i3 uses the more modern RandR.

[Something similar](https://bugs.kde.org/show_bug.cgi?id=391778#c3) came from the KDE team (referenced in https://github.com/FreeRDP/FreeRDP/issues/2707#issuecomment-372481326
> Now there is just no xinerama extension used anymore. Today we use xrandr to configure multiple screens. I have no idea what these indices are that FreeRDP uses, but KWin (and probably any other window manager) doesn't know anything of Xinerama.

I am not a C programmer (although that was my first language, many moons ago), and certainly X11 internals are way above my stratosphere. I suspect that moving from Xinerama to xrandr would be a huge effort, especially considering that freerdp is very complete, mature software. However, I would recommend, with all the authority of someone who is unabashedly completely ignorant insofar as the problem under discussion is concerned can muster, that there be a discussion about whether it would be beneficial to this project to migrate to a newer ~~x11 thing~~ X Window System extension.
Also, perhaps it would be productive to try to talk to WM maintainers directly, such as @Airblader and @stapelberg. I suspect that specializing in WM development vs application development brings about different perspectives and priorities, and an open discussion would be beneficial to everyone.

**Comment by hardening** [comment]
xfreerdp do support RandR, that's the way, we're using by default to get the monitor's size.
So what's do you mean with `xfreerdp multimon doesn't work with i3, and I don't think lxqt either, and probably more` ? What kind of behaviour are you observing ?

**Comment by Airblader** [comment]
Reading through some of the old discussions again, I'm even afraid there just isn't a way to solve this. 

My understanding is that FreeRDP uses _NET_WM_FULLSCREEN_MONITORS to inform the window manager which outputs to fullscreen (should it be multiple). This atom works with Xinerama indices, which is why some window managers don't support it as they don't support Xinerama. FreeRDP correctly checks for support for this atom and then does nothing with it if unsupported (which is fine). 

What's missing here is doing it in a "RandR-y" way. I don't think there's any specification with which this can be described, however(?)

**Comment by akallabeth** [comment]
@Airblader maybe https://stackoverflow.com/questions/36966900/xcb-get-all-monitors-ands-their-x-y-coordinates might be what you are looking for?

**Comment by Airblader** [comment]
@akallabeth The answer on that question is by me ;-) That question is about querying RandR monitors. What we need here is a way for a client to fullscreen covering a specific (sub-)set of outputs, though.

**Comment by yringler** [comment]
Fascinating. GTK [reached the same conclusion](https://gitlab.gnome.org/GNOME/gtk/blob/9f6deab88cfbcfd7ebf5431495453adcab9f0639/gdk/gdkwindow.c#L10912) - full screen over multiple monitors needs Xinerama, if that's not available don't bother.

```
 * If the XINERAMA extension is not available or not usable, this function
 * has no effect.
```

There really seems to be no way to do this without Xinerama, which basically means that there's no way to do this.

I opened up [an issue](https://gitlab.freedesktop.org/xorg/lib/libxrandr/-/issues/9) with xrandr, but IDK if that bug list is monitored.

How big a deal is it to... write a little X11 extension to do this?

I wounder if it would be easier to support an X11 alternative like wayland.

**Comment by Airblader** [comment]
> How big a deal is it to... write a little X11 extension to do this?

It doesn't even require an extension as such, but rather just a specification to agree on. However that is probably a close to impossible task at worst, and takes years to propagate at best, as can be seen by KDE and others creating proprietary specifications over time. X is not a fast moving world. :-(

**Comment by stapelberg** [comment]
> However that is probably a close to impossible task at worst, and takes years to propagate at best, as can be seen by KDE and others creating proprietary specifications over time. X is not a fast moving world. :-(

While this may be accurate, as a first step, we just need a draft and then make both i3 and freerdp implement it.

If this implementation works well, we can encourage others to adopt the draft, too.

I think it could work out in practice :)

**Comment by akallabeth** [comment]
reading through this whole thread it sounds more like a bug in `i3` not supporting the atoms defined in the `xinerama` specification properly than anything else.
Don´t see a reason to create a new spec if there is a properly working one available ;)
Note: There is a difference between the `xinerama` `X11` extension and the multi window management mode commonly referred to as `xinerama`.
While the latter is nowadays more or less abandoned, the extension is still providing essential configuration for multimonitor modes.

**Comment by Airblader** [comment]
@akallabeth If it were that easy, that'd be great. Can you give us a pointer on how we can map the Xinerama screen indices to RandR outputs perhaps?

**Comment by stapelberg** [comment]
I think with https://github.com/i3/i3/issues/4118#issuecomment-649989138, we’d already cover most users.

**Comment by akallabeth** [comment]
@Airblader sadly not, I´d love to fix this but I´m mostly working on the other side of the API here so my knowledge for implementing that on the wm side are limited.
