### ISSUE TITLE
Android client build error

### ISSUE THREAD

**Issue by Snotra-p** [FreeRDP/FreeRDP#6294]
I tried the manual of android docs.

./scripts/android-build-freerdp.sh --ndk ~~~/android-ndk-r21 --sdk /Android/Sdk --conf 
./scripts/android-build-64.conf

The installation of openssl went well, but during the progress of the cmake --build --target install the following error was obtained

[RUN] cmake --build . --target install
Error: could not load cache
[ERROR] cmake --build . --target install retured 1

i try to remove CmakeCache.txt  and retry but  same error occured

What should I do? help me plz

my environment
ubuntu 18.04
ndk version r21

  Path                 | Version | Description                    | Location
  -------              | ------- | -------                        | -------
  build-tools;28.0.3   | 28.0.3  | Android SDK Build-Tools 28.0.3 | build-tools/28.0.3/
  emulator             | 30.0.12 | Android Emulator               | emulator/
  patcher;v4           | 1       | SDK Patch Applier v4           | patcher/v4/
  platform-tools       | 30.0.2  | Android SDK Platform-Tools     | platform-tools/
  platforms;android-28 | 6       | Android SDK Platform 28        | platforms/android-28/

**Comment by akallabeth** [comment]
* Please start with a clean checkout
