### ISSUE TITLE
remoteapp is disconnecting when i show a tooltip the second time

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#6302]
**Describe the bug**
remoteapp is disconnecting when i show a tooltip in a dialog the second time. Is a native program.

**To Reproduce**

Launch remoteapp
Open a dialog
Show tooltip one time
Again
See error:
[10:43:45:039] [25488:25497] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x00] Switch Surface
[10:43:45:039] [25488:25497] [ERROR][com.freerdp.core.update] - [0x00] Switch Surface - SERVER BUG: The support for this feature was not announced! Use /relax-order-checks to ignore
[10:43:45:039] [25488:25497] [ERROR][com.freerdp.core.update] - order flags 00 failed
[10:43:45:039] [25488:25497] [ERROR][com.freerdp.core.fastpath] - Fastpath update Orders [0] failed, status 0
[10:43:45:039] [25488:25497] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update() - -1
[10:43:45:039] [25488:25497] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[10:43:45:039] [25488:25497] [DEBUG][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_ACTIVE - rdp_recv_pdu() - -3
[10:43:45:039] [25488:25497] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
[10:43:45:039] [25488:25497] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
[10:43:45:039] [25488:25497] [DEBUG][com.freerdp.core] - rdp_check_fds() - -1
[10:43:45:039] [25488:25497] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[10:43:45:039] [25488:25497] [INFO][com.freerdp.client.common] - Network disconnect!
[10:43:45:039] [25488:25497] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

**Expected behavior**
Continue operation, don't disconnecting.

**Application details**

This is FreeRDP version 3.0.0-dev (d31a98336)

/u:test /app:"||native_users_manage" /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100% /log-level:TRACE /cert-ignore

Output of xfreerdp /buildconfig
This is FreeRDP version 3.0.0-dev (d31a98336)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=OFF WITH_ZLIB=ON
Build type: Debug
CFLAGS: -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler: GNU, 8.3.0
Target architecture: x64

**OS version connecting to (server side)**
Windows Server 2008 R2

**Environment (please complete the following information):**

OS: Debian
Version/Distribution: 10 with XFCE
Architecture: amd64

**Comment by akallabeth** [comment]
@FutureKidBuu ok, this was another interesting on. Reread the spec and relaxed the check a bit, could you verify the fix in #6304 works for you?

**Comment by FutureKidBuu** [comment]
@akallabeth Unfortunately not, I get the same result

**Comment by akallabeth** [comment]
@FutureKidBuu ok, and with `+offscreen-cache` ?

**Comment by FutureKidBuu** [comment]
@akallabeth same

**Comment by FutureKidBuu** [comment]
Also I have tried several configurations with the same result.

**Comment by akallabeth** [comment]
@FutureKidBuu ok, that is indeed strange, need to dig deeper here.
Anyway, with `/rfx /gfx:avc444` there should be no such issue (given that also the server has activated these options)

**Comment by FutureKidBuu** [comment]
@akallabeth Just for your information and if it is useful to you:

Debugging the code you did, if I am right, only enter if _settings-> OffscreenSupportLevel_ variable is _FALSE_, but by default it is _TRUE_ and both if I put it with _+offscreen-cache_ or _-offscreen-cache_ that variable will be _TRUE_. If I modify the code and build so that _settings->OffscreenSupportLevel_ is _FALSE_ then if it goes into condition of _check_order_activated_

```
case ORDER_TYPE_SWITCH_SURFACE:
			if (!settings->OffscreenSupportLevel)
			{
				if (altsec->switch_surface.bitmapId != SCREEN_BITMAP_SURFACE)
				{
					check_order_activated(update->log, settings, orderName, FALSE);
					return FALSE;
				}
			}
```

In any case, the application disconnection continues

**Comment by akallabeth** [comment]
@FutureKidBuu ok, that means the server is deactivating support for it (the client just tells the server `I can do that` and the server tells the client `No, don´t want that`)
It is still problematic as the server tells to deactivate the cache and then tries to draw into the non existing cache.
Could you check what happens if you just `return TRUE` in that case?

**Comment by FutureKidBuu** [comment]
@akallabeth 
![image](https://user-images.githubusercontent.com/25820234/85681616-c05a9680-b6cb-11ea-93ec-97b0152b71ec.png)

It seems that the  tooltip is not drawn in full

**Comment by akallabeth** [comment]
@FutureKidBuu ok, managed to reproduce, but by adding `+offscreen-cache` I can reproducibly eliminate the issue. (you´re using a specific RDP version/configuration which requires offscreen caches to be enabled)

**Comment by FutureKidBuu** [comment]
@akallabeth with `+offscreen-cache` I get this error:

```
[08:50:51:856] [12851:12869] [ERROR][com.freerdp.cache.offscreen] - invalid offscreen bitmap at index: 0x00000055
[08:50:51:856] [12851:12869] [WARN][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x00] Switch Surface failed
[08:50:51:856] [12851:12869] [ERROR][com.freerdp.core.update] - order flags 00 failed
```

**Comment by akallabeth** [comment]
@FutureKidBuu ok, you really have an interesting setup. The server tries to set a surface that was not created?
Could you tell how the server was configured? Can not reproduce this one here locally.

**Comment by FutureKidBuu** [comment]
@akallabeth I suspect it is the native application that is causing it but I would like to get away from that problem.

Anyway, it is very curious, the second time the tooltip is displayed it enters the `offscreen_cache_get` method twice, one time the index value is 0 and the next 85, and when it is not found, disconnection happens.

I show you that it actually enters twice because this

[10:13:19:654] [19972:20001] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x00] Switch Surface
[10:13:20:519] [19972:20001] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x00] Switch Surface

And then, is the error `invalid offscreen bitmap at index: 0x00000055`

Would it be possible to avoid it?

**Comment by akallabeth** [comment]
@FutureKidBuu well, not using legacy RDP would be one step (`/rfx /gfx:avc444` client side, enable `rfx` and `gfx` server side)

**Comment by FutureKidBuu** [comment]
@akallabeth I have no possibility to enable those options, what I have seen is that if I launch with the local administrator i do not have this issue, but with domain users ...

Keep investigating!

**Comment by FutureKidBuu** [comment]
In case you have any idea, that windows server does not act as a domain controller, it would be on another server.

**Comment by FutureKidBuu** [comment]
@akallabeth 
If I prevent it from caching...

```
case ORDER_TYPE_SWITCH_SURFACE:
			rc = TRUE;//IFCALLRET(altsec->SwitchSurface, rc, context, &(altsec->switch_surface));
			break;
```
Later enters the UNKNOW order

![image](https://user-images.githubusercontent.com/25820234/95199134-a1949180-07dc-11eb-9acd-fd7f2814dd49.png)

Why? This is pretty crazy.

**Comment by akallabeth** [comment]
@FutureKidBuu well, can you add your command line for this? If you already modified code and/or are running with `/relax-order-checks` then this might just be random data

**Comment by FutureKidBuu** [comment]
ok, `echo "clave" | xfreerdp /u:"usuario" /app:"||app"  /title:"App" /cert-ignore /from-stdin /v:localhost:3389 /size:100% -decorations /log-level:debug /smartcard`

**Comment by akallabeth** [comment]
@FutureKidBuu did you try `/rfx`? server 2008 already supports that. as for the rectangle, I have to check the docs, but this looks like a protocol violation (rectangles must hold `top <= bottom` and `left <= right`)

**Comment by FutureKidBuu** [comment]
> @FutureKidBuu did you try `/rfx`? server 2008 already supports that. as for the rectangle, I have to check the docs, but this looks like a protocol violation (rectangles must hold `top <= bottom` and `left <= right`)

Yes I enabled the rfx option on the server, confirming the same situation although visually there were differences.
Something remarkable that I have been able to detect is that with the _-fonts_ parameter the situation occurs less often.
