### ISSUE TITLE
2.1.2 fails to build on Linux

### ISSUE THREAD

**Issue by david-geiger** [FreeRDP/FreeRDP#6305]
Hi,

I tried on Mageia Cauldron to build latest 2.1.2 release but it fails to build with:

> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:30:22: warning: missing terminating " character
   30 | #define GIT_REVISION "[RUN] echo 2.1.2
      |                      ^
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:31:1: error: too many decimal points in number
   31 | 2.1.2"
      | ^~~~~
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:31:1: error: expected identifier or '(' before numeric constant
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:31:6: warning: missing terminating " character
   31 | 2.1.2"
      |      ^
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:31:6: error: missing terminating " character
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/winpr/libwinpr/utils/winpr.c: In function 'winpr_get_build_revision':
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:30:22: error: missing terminating " character
   30 | #define GIT_REVISION "[RUN] echo 2.1.2
      |                      ^~~~~~~~~~~~~~~~~
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/winpr/libwinpr/utils/winpr.c:63:9: note: in expansion of macro 'GIT_REVISION'
   63 |  return GIT_REVISION;
      |         ^~~~~~~~~~~~
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/winpr/libwinpr/utils/winpr.c:63:2: warning: 'return' with no value, in function returning non-void [-Wreturn-type]
   63 |  return GIT_REVISION;
      |  ^~~~~~
/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/winpr/libwinpr/utils/winpr.c:61:13: note: declared here
   61 | const char* winpr_get_build_revision(void)
      |             ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/build.make:762: winpr/libwinpr/CMakeFiles/winpr.dir/utils/winpr.c.o] Error 1
make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build'
make[2]: *** Waiting for unfinished jobs....

Regards,
David

**Comment by akallabeth** [comment]
Already fixed with #6301 
For the time being remove the additional strings from `source_version`, sorry for the inconvenience

**Comment by bmiklautz** [comment]
The release archives were re-uploaded to fix this issue. Please download them again.

**Comment by david-geiger** [comment]
Yes it is fixed now, thank you :)

**Comment by viscount7557** [comment]
> Hi,
> 
> I tried on Mageia Cauldron to build latest 2.1.2 release but it fails to build with:
> 
> > /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:30:22: warning: missing terminating " character
>    30 | #define GIT_REVISION "[RUN] echo 2.1.2
>       |                      ^
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:31:1: error: too many decimal points in number
>    31 | 2.1.2"
>       | ^~~~~
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:31:1: error: expected identifier or '(' before numeric constant
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:31:6: warning: missing terminating " character
>    31 | 2.1.2"
>       |      ^
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:31:6: error: missing terminating " character
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/winpr/libwinpr/utils/winpr.c: In function 'winpr_get_build_revision':
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build/winpr/include/winpr/version.h:30:22: error: missing terminating " character
>    30 | #define GIT_REVISION "[RUN] echo 2.1.2
>       |                      ^~~~~~~~~~~~~~~~~
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/winpr/libwinpr/utils/winpr.c:63:9: note: in expansion of macro 'GIT_REVISION'
>    63 |  return GIT_REVISION;
>       |         ^~~~~~~~~~~~
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/winpr/libwinpr/utils/winpr.c:63:2: warning: 'return' with no value, in function returning non-void [-Wreturn-type]
>    63 |  return GIT_REVISION;
>       |  ^~~~~~
> /home/iurt/rpmbuild/BUILD/freerdp-2.1.2/winpr/libwinpr/utils/winpr.c:61:13: note: declared here
>    61 | const char* winpr_get_build_revision(void)
>       |             ^~~~~~~~~~~~~~~~~~~~~~~~
> make[2]: *** [winpr/libwinpr/CMakeFiles/winpr.dir/build.make:762: winpr/libwinpr/CMakeFiles/winpr.dir/utils/winpr.c.o] Error 1
> make[2]: Leaving directory '/home/iurt/rpmbuild/BUILD/freerdp-2.1.2/build'
> make[2]: *** Waiting for unfinished jobs....
> 
> 
> Regards,
> David
