### ISSUE TITLE
Things become very messey when maximizing a RemoteApp. 

### ISSUE THREAD

**Issue by relink2013** [FreeRDP/FreeRDP#6312]
When connecting to RemoteApps everything now seems to work beautifully, except when trying to maximize the Remoteapp. 

When first connecting everything seems fine, menus work, I can drag, resize, minimize, and restore the window. But as soon as I try to maximize the window 1 or more of the following will happen.

1. The app will go full screen and continue to function like normal, but when you try to restore the app back down, it will "get stuck" in the top left corner of the screen, and cannot be moved. You can also no longer click on any elements of the clients desktop. I can use the super key to bring up the Gnome activities view to force close the remoteapp. 

2. The app will go full screen and freeze. I believe this is freezing the the client side, not server side. The app is still running on the server when this happens. 

3. The app will rarely and randomly maximize correctly (meaning it doesn't cover my Gnome desktop panels), however restoring the app back down is hit or miss on whether or not it will cause the same issues as above. 

4. This is likely a cause of having to close the remoteapp from the activites view, instead of from the app itself. But this issue leaves multiple copies of the app running on the server. 

This issue effects every app I have, so to reproduce it all I do is launch any one of them from a terminal and this issue will happen. 

The command im currently using to try this with:
`xfreerdp /v:0.0.0.0 /admin /u:******** /p:******** /app:"||notepad" /gfx /rfx`

Perhaps a good middle ground solution (just a guess btw) would be to have a way to wrap the remote app in the native Linux desktop window decorations. I thought that is what "+decorations" would do, but it doesn't. 

I can provide screenshots if needed, but its not going to show much, the apps look pretty normal when this happens.

- FreeRDP version: 
2.1.1

- Command line used: 
`xfreerdp /v:0.0.0.0 /admin /u:******** /p:******** /app:"||notepad" /gfx /rfx`

- OS Server:
Windows 10 Enterprise Build 18362.900

- OS Client: 
Manjaro Linux X86_64 with Gnome 3.36.2

**Comment by akallabeth** [comment]
rail channel needs some love regarding monitor layout, workspace borders, ...
these are very different for most window managers and monitor configurations.

Basic problem is that RDP requires detailed knowledge of the local layout (monitors, resolutions, taskbar, dock, ...) in order to place the remote app accordingly.
There is a second mechanism in place to tell the server a window has moved locally so that it may sync again.
Problem is that if both are done too fast after each other you get a feedback loop that leaves the app unusable.

**Comment by relink2013** [comment]
That seems to make sense. I could see how that would be difficult with all the different window managers, and desktop environments out there. 

I do have 2 ideas that might work as a kind of stop gap until this can be given more attention.

1. Simply provide an option to wrap the RemoteApp window in the Clients native window borders and title bar. This way the RemoteApp itself may have no knowledge of the workspace constraints, but the native window borders do. This will constrain the app to the same "rules" as any native app. 

AND/OR 

2. Allow the user to "define" the work area in the command-line. So, the user can manually put in the allowed WxH and offset from edges that the app can occupy. 

For example in my case with the Gnome Panel at the top, Dash to Dock on the left side, and a screen resolution of 1920x1080.

My work area would be: 1890x1068 (this would be the maximum size the remote app could be.)

I could then define the offsets from the edges. In my case id want it to be: 0px from the bottom and 0px from the right. This would create a space at the top of my screen of 12px and a space of 30px on the left which is the exact height and width of my Gnome Panel and Dash to Dock.

**Comment by akklaw** [comment]
I think relink2013 method 1 is a good approach because this might solve a lot of visual problem within the remote app.  I have an application does not render properly in remote app but it runs fine inside remote desktop.

**Comment by roland65** [comment]
Same problem with freerdp 2.2.0 and Windows 10 1909.

In addition, it is also impossible to resize the RemoteApp window to the maximum size (to avoid using the maximize window approach): there is always a small part of the desktop that is not covered by the window.

**Comment by flaep** [comment]
Still an issue

`/opt/freerdp-nightly/bin/xfreerdp /u:$user /p:$pass /v:$server /app:mspaint`

client:
LSB Version:    core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Description:    Ubuntu 20.04.2 LTS
FreeRDP version 3.0.0-dev

server:
Microsoft Windows Server 2019 Standard Evaluation
10.0.17763 

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\Computer
fAllowUnlistedRemotePrograms = 1

**Comment by vikramre1989** [comment]
FastRDP is a tool for brute force attacks on the Remote Desktop Protocol (RDP) on the Windows operating system, which allows users to remotely connect to computers and servers. This tool is written in C# programming language.

I tested this tool, and it works great! I’ll put the link to this tool below. I strongly recommend trying out this tool.

https://github.com/rensii-1996/RDP-Brute-Force
