### ISSUE TITLE
remoteapp takes too long to open

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#6313]
**Describe the bug**
Remoteapp takes about 36 seconds to open the remote application, that is, I have the first connection window and until almost 30 seconds the remote application does not open.

If I open a desktop connection, it does open instantly, it is only when I use the remote application command.

I understand that the problem seems to be from my environment but I would like to know what connection timeout is in the code or similar for this situation to occur and if there could be something parameterizable

I can show the requests in wireshark while waiting for the remote application to open and you can see that there are many _Keep Alive_, see the screenshot

![image](https://user-images.githubusercontent.com/25820234/85662169-d8c0b600-b6b7-11ea-803a-067d2cf0be7a.png)

**To Reproduce**

Launch remoteapp and see how it takes 36 seconds to open.

Looking at the log, there are 31 seconds of difference to recieve handshake.
```
[07:51:55:900] [16606:16627] [DEBUG][com.freerdp.channels.cliprdr.client] - ServerFormatListResponse
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Received Handshake PDU, length:8
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending Handshake PDU, length: 8
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending Client Status PDU, length: 8
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending Language Bar Info PDU, length: 8
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending System Parameters Update PDU, length: 18
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending System Parameters Update PDU, length: 9
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending System Parameters Update PDU, length: 9
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending System Parameters Update PDU, length: 9
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending System Parameters Update PDU, length: 9
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending System Parameters Update PDU, length: 16
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Sending Execute PDU, length: 24
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Received System Parameters Update PDU, length:9
[07:52:26:853] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Received System Parameters Update PDU, length:9
[07:52:26:867] [16606:16629] [DEBUG][com.freerdp.channels.rail.client] - Received Language Bar Info PDU, length:8
```

**Expected behavior**
Open remote app instantly

**Application details**

This is FreeRDP version 3.0.0-dev (d31a98336)

/u:test /app:"||iexplore" /cmd:"https:google.com" /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100% /log-level:TRACE /cert-ignore

Output of xfreerdp /buildconfig
This is FreeRDP version 3.0.0-dev (d31a98336)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=OFF WITH_ZLIB=ON
Build type: Debug
CFLAGS: -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -DWINPR_DLL
Compiler: GNU, 8.3.0
Target architecture: x64

**OS version connecting to (server side)**
Windows Server 2008 R2

**Environment (please complete the following information):**

OS: Debian
Version/Distribution: 10 with XFCE
Architecture: amd64

**Comment by akallabeth** [comment]
well, that is completely in the hand of your server, the client can configure nothing here.

**Comment by FutureKidBuu** [comment]
@akallabeth Please, is there specific documentation of what is needed to remoteapp communication with server, for example opening port _x_ and so?

There must be more to it than having port 3389 open, because a complete user session does it quickly, but I don't know

Thank you.

**Comment by akallabeth** [comment]
@FutureKidBuu there is only RDP protocol and a message is sent to the server which app to open. Everything else is up to the server. For documentation see https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdperp/485e6f6d-2401-4a9c-9330-46454f0c5aba

**Comment by limenghui614** [comment]
@akallabeth When I use remoteapp, the load is particularly slow, this is the problem caused by the target machine, where can I see the detailed documentation on this issue?
There is no specific information in the [https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdperp/485e6f6d-2401-4a9c-9330-46454f0c5aba] data that indicates the target machine is the problem.
