### ISSUE TITLE
USB redirection broke in the 2.0.0 release

### ISSUE THREAD

**Issue by LordOfTheRats** [FreeRDP/FreeRDP#6337]
USB redirection seems to have been broken in commit 0927d7aa50c76b671b55c33e0f06c950d1f08e9a (possibly 210b40a54fa302ef88c0d9fa2565905fe6873fe9 or 15ad496bbad8037300501ccb6dfc14aa582b5083, but both those commits won't compile). The device, a Logitech webcam C310, does not show up in the servers device manager. This issue persists in the 2.1.2 release.
In a37851161779f91e8e79b22400ffd822ff714c32 and prior the webcam shows up and can be used without issues.
I found the commit using git bisect on the stable-2.0 branch.

The client is running on Ubuntu 18.04 64bit and connecting to a Windows Server 2012R2. The issue seems to be independent of the server version.
We use the parameter `/usb:id,dev:046d:081b` to enable redirection. FreeRDP is run as root to prevent permission issues while testing. Full command line is included in the trace logs. Buildconfig is the same for both versions.

[FreeRDP (a37851161) trace log with working USB redirection](https://gist.github.com/LordOfTheRats/bf31925fbdb63a30816b8962d8526e3f)
[FreeRDP (0927d7aa5) trace log with broken USB redirection](https://gist.github.com/LordOfTheRats/fc4bcaf4abd7fbd69390bfb4fc7c4e05)
[FreeRDP buildconfig](https://gist.github.com/LordOfTheRats/a26c9a9bd3be0c17cb0867bf390c4c0c)

Is anyone able to confirm this?

**Comment by akallabeth** [comment]
@LordOfTheRats seems the newer versions differ in the response size to
```
 [READ ] TRANSFER_IN_REQUEST               [proxy|server] [00000105] InterfaceId=40000015, MessageId=00000000, FunctionId=00000105, length=32
[15:28:14:084] [8797:8808] [DEBUG][com.freerdp.channels.urbdrc.client] - URB TS_URB_GET_DESCRIPTOR_FROM_DEVICE[u]
[15:28:14:241] [8797:8805] [DEBUG][com.freerdp.channels.cliprdr.client] - ServerFormatListResponse
[15:28:14:287] [8797:8808] [DEBUG][com.freerdp.channels.urbdrc.client] - [WRITE] URB_COMPLETION                    [proxy|client] [00000101] InterfaceId=40000000, MessageId=00000000, FunctionId=00000101, length=2502
[15:28:14:287] [8797:8808] [DEBUG][com.freerdp.channels.drdynvc.client] - write_data: ChannelId=9 size=2502
```

could you dump the request buffer?

**Comment by LordOfTheRats** [comment]
Sure!

I'm not sure how, though :>

Thank you for having a look at this! Much appreciated.

**Comment by akallabeth** [comment]
@LordOfTheRats 
1. dump the length of the input data stream in `urbdrc_on_data_received`.
1. Check for the entry with `write_data: ChannelId=9 size=2502` (broken revision)
  1. Note the length of the next packet received
1. Check for the entry in the working revision
  1. Note the length of the next packet there (`Size=2562 InterfaceId=0x5 Mask=0x1` as far as I can see)

**Comment by LordOfTheRats** [comment]
I've added this line to `urbdrc_on_data_received` above `if (Stream_GetRemainingLength(data) < 12)` in the broken revision (0927d7aa5):

```
WLog_Print(urbdrc->log, WLOG_TRACE, "Size=%d", Stream_GetRemainingLength(data));
```

There does not seem to be any packet with the necessary length:
```
[13:56:33:433] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=16
[13:56:33:480] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=12
[13:56:33:481] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=24
[13:56:33:481] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=12
[13:56:33:528] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=16
[13:56:33:542] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=12
[13:56:33:542] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=24
[13:56:33:543] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=12
[13:56:33:573] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=20
[13:56:33:589] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=20
[13:56:33:605] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=20
[13:56:33:605] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=32
[13:56:33:612] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=28
[13:56:33:624] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=32
[13:56:33:639] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=32
[13:56:33:870] [16484:16502] [TRACE][com.freerdp.channels.urbdrc.client] - Size=16
```
[Full log](https://gist.github.com/LordOfTheRats/c53f2f092e05ccef6fd143f554caf630)


This is the packet in the working revision (a37851161):
```
[13:13:43:362] [8137:8340] [DEBUG][com.freerdp.channels.drdynvc.client] - write_data: ChannelId=8 size=2502
[13:13:43:379] [8137:8189] [DEBUG][com.freerdp.channels.drdynvc.client] - order_recv: Cmd=0x2, Sp=1 cbChId=0
[13:13:43:380] [8137:8189] [DEBUG][com.freerdp.channels.drdynvc.client] - process_data_first: Sp=1 cbChId=0, ChannelId=8 Length=2562
[13:13:43:380] [8137:8189] [DEBUG][com.freerdp.channels.drdynvc.client] - order_recv: Cmd=0x3, Sp=1 cbChId=0
[13:13:43:380] [8137:8189] [TRACE][com.freerdp.channels.drdynvc.client] - process_data: Sp=1 cbChId=0, ChannelId=8
[13:13:43:380] [8137:8189] [TRACE][com.freerdp.channels.urbdrc.client] - Size=2562 InterfaceId=0x5 Mask=0x1
[13:13:43:380] [8137:8189] [TRACE][com.freerdp.channels.urbdrc.client] - InterfaceId 0x5 Start matching devices list
[13:13:43:380] [8137:8341] [DEBUG][com.freerdp.channels.urbdrc.client] - urbdrc_process_udev_data_transfer: >>TRANSFER_IN_REQUEST<<0x105
[13:13:43:380] [8137:8341] [DEBUG][com.freerdp.channels.urbdrc.client] - URB_Func: URB_FUNCTION_SELECT_CONFIGURATION
```
[Full log](https://gist.github.com/LordOfTheRats/c74ab9842392db4d4107652bb23ed43f)

Thank you for your help !

**Comment by akallabeth** [comment]
@LordOfTheRats I think you misunderstood.
Please dump the data in the received `wStream` in `urbdrc_on_data_received` in the old and new revisions.
The packet with `2502` response length is there, the next received packet as well but there the whole thing gets haywire.

**Comment by LordOfTheRats** [comment]
Oh I'm sorry. I hope `winpr_HexDump()` is the right thing to do.

[Trace with data (broken)](https://gist.github.com/LordOfTheRats/00268959b8ecf7e5767445fa1a54fbd3)
[Trace with data (working)](https://gist.github.com/LordOfTheRats/7c931f1fd053e140c5d23032de565f2f)

**Comment by akallabeth** [comment]
@LordOfTheRats Still not enough :/
Also need the response messages, full hex dump.
Looks like we have an endianess issue here (conversion from/to network data) but I need to do a full compare.

**Comment by LordOfTheRats** [comment]
Will a hex dump in `urbdrc_process_capability_request`, `urbdrc_process_channel_create`, `urdbrc_send_virtual_channel_add`, `urdbrc_send_usb_device_add` above the `channel->Write`s suffice?

**Comment by trentasis** [comment]
One question before 2.0.0 was working webcam with windowd remote desktop sesssion ,video , sound and mic was ok?

Thanks

**Comment by LordOfTheRats** [comment]
@trentasis I haven't tested all of them at once recently, but all of them should work in the repository state from 26.08.2019.

@akallabeth I think I managed to dump all the data sent in urbdrc_main.c. I tweaked the output a little bit to prepend "Sending packet" or "Received packet" before the hex dump. Just let me know if you need anything else.

[Trace with data (broken)](https://gist.github.com/LordOfTheRats/898aa47e9becf0c08bbc622e88a7dc0f)
[Trace with data (working)](https://gist.github.com/LordOfTheRats/bea1b7a59937cefc338e98abb1bacaa3)

**Comment by akallabeth** [comment]
@LordOfTheRats looks like you dump with an offset error, the broken ones start 2 bytes before the working ones.

**Comment by akallabeth** [comment]
@LordOfTheRats ok, the interesting messages are sadly missing.
1. Please check the dump, there is a 2 byte offset between old and new dumps
1. `URB_FUNCTION_GET_DESCRIPTOR_FROM_DEVICE` responses are not dumped
1. `/log-filters:com.freerdp.channels.urbdrc.client:trace` will filter out unwanted log messages so the dumps are more easy to compare

**Comment by LordOfTheRats** [comment]
1. Oh. I think I used Stream_Buffer where I should have used Stream_Pointer. Should be fixed, now it looks like it fits. I hope this was the right direction.

2. Ah this is in data_transfer.c. I added the hex dump to all channel->Writes there as well in both versions.

3. Indeed

[Trace with data, filtered (broken)](https://gist.github.com/LordOfTheRats/9373207a57ddaef8ad31e02271cdd000)
[Trace with data, filtered (working)](https://gist.github.com/LordOfTheRats/872d162c7c757f677ffb7d0e7bcdaff6)

**Comment by akallabeth** [comment]
@LordOfTheRats are the tests done on the same machine or 2 different ones?

**Comment by LordOfTheRats** [comment]
Same machine, same server, same command line. I just swap (all) the binaries for testing.

**Comment by akallabeth** [comment]
Ok, here are the preliminary diffs:
1. In `urdbrc_send_usb_device_add`
  1. `pdev->get_UsbDevice(pdev)`: `5` vs `0x15`
  1. `strInstanceId` differs
  1. `pdev->getPath(pdev)` differs

**Comment by akallabeth** [comment]
Ok, I´ve created `https://github.com/FreeRDP/FreeRDP/pull/6341` with a bit of debugging and a possible fix for the diff in `urbdrc_process_query_device_text`

**Comment by LordOfTheRats** [comment]
I'll give it a spin.

**Comment by LordOfTheRats** [comment]
No luck yet.

[Trace with data (urbdrc_debug)](https://gist.github.com/LordOfTheRats/9fd261e361ad26dee5d1ab2e84ed771c)

**Comment by akallabeth** [comment]
@LordOfTheRats I´ve updated a few log messages and it is working for my devices (no change there).
So, could you use this branch and set `-DWITH_DEBUG_URBDRC=ON` without your custom logging? That should print all debug info required (and hopefully with less diff to the working revision)

**Comment by LordOfTheRats** [comment]
Sorry, I just noticed your new compile flag as well. :D Running a new test right now.

**Comment by LordOfTheRats** [comment]
Alright there we go: [Trace](https://gist.github.com/LordOfTheRats/ec7829bc6d2a134655f4c11cb88e288a)

Slight issue in your code, though :blush:
```
winpr_HexDump(log, WLOG_TRACE, Stream_Buffer(s), length);
```
should be
```
winpr_HexLogDump(log, WLOG_TRACE, Stream_Buffer(s), length);
```

**Comment by akallabeth** [comment]
@LordOfTheRats do a git pull, updated that hours ago ;)

**Comment by akallabeth** [comment]
@LordOfTheRats Ok, fixed most of the diff from the logs, the last remaining is in `urdbrc_send_usb_device_add`
Could you check the device initialization in `udev_init`? Specifically the `pdev->isCompositeDevice` setting which differs for some reasone between the old and new version.

It looks like the device is started up with a different configuration and therefore not working as expected.

**Comment by akallabeth** [comment]
@LordOfTheRats I´ve identified a big difference in `udev_init` between the old version and the new (a constant was wrong).
Could you retry and post the trace? Thanks.

**Comment by LordOfTheRats** [comment]
Here you go [Trace](https://gist.github.com/LordOfTheRats/8ef4b58332146e9b8b16e94eb5161f14). 

Do you still want me to dump `pdev->isCompositeDevice` in `udev_init`?

**Comment by akallabeth** [comment]
@LordOfTheRats and another one, this should fix the difference in the coded addresses

**Comment by LordOfTheRats** [comment]
You are a genius! The cam is showing up in the device manager and I was able to get a video feed from it. Performance feels terrible (lots of lag in the video), but I figure this is probably because of the debug output. I'll repeat the test with disabled debug.

[Trace](https://gist.github.com/LordOfTheRats/049cc149b7ab6f093d82dce7252a04f6)

**Comment by LordOfTheRats** [comment]
Even with disabled debug logs (the cmake option and the /log-filters option) performance is notably worse (lower framerate) that in a37851161, but maybe it is not "terrible".

In any case this is a huge step in the right direction. Thank you very much for your help with this!

**Comment by akallabeth** [comment]
@LordOfTheRats quantify `worse`. Some regression is expected due to the many CVE fixes (mostly additional input validation checks)

**Comment by LordOfTheRats** [comment]
New [Trace](https://gist.github.com/LordOfTheRats/ed16759f1db66aac78f73e7c1bbd74f9) using your newest version (637470009)

Quantifying the performance is a bit tricky. I made two videos hoping to show the difference, but now I don't see it anymore. Must have been an imaginary performance hit after all. I'll see if I can measure the webcam FPS to get some more reliable numbers.

[Old version (a37851161)](https://nextcloud.vhtec.de/s/ji3fEQCswozgnWs)
[New version (637470009)](https://nextcloud.vhtec.de/s/YW2nLGgxQK6Z5BN)

**Comment by LordOfTheRats** [comment]
Measuring FPS resulted in no relevant difference between the versions. So I guess we are good :)

**Comment by akallabeth** [comment]
@LordOfTheRats ok, thank you for testing. Please add a note in the pr thread so other reviewers know it has been tested.

**Comment by LordOfTheRats** [comment]
I found a SEGFAULT while doing some more thorough testing. This time I'm using a Microsoft LifeChat LX-3000 and `/audio-mode:1`

637470009 SEGFAULTs as soon as some sound is going to be played / the audio output stream is opened (just letting the mixer do his "pling").
a37851161 works fine, I can even play music with minimal stutter.

Headsets might not be the best use for USB redirection, is probably not really supported and I don't expect the stutter to go away completely, but SEGFAULT is SEGFAULT, right?

[Trace with data (working)](https://gist.github.com/LordOfTheRats/b60349c59afc114526007686c8656e73)
[Trace with data (broken)](https://gist.github.com/LordOfTheRats/a5a50014869178dda33b7a50ebe8581f)

**Comment by akallabeth** [comment]
@LordOfTheRats could you build with `-DWITH_SANITIZE_ADDRESS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo` or run in a debugger to get a stack trace?

**Comment by akallabeth** [comment]
and no, audio devices can not be redirected, the servers do not allow that

**Comment by akallabeth** [comment]
Oh, and please add `/buildconfig` as many issues depend on compile time options.
Create a new issue for that if possible.

**Comment by LordOfTheRats** [comment]
> @LordOfTheRats could you build with `-DWITH_SANITIZE_ADDRESS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo` or run in a debugger to get a stack trace?

Will do.



> and no, audio devices can not be redirected, the servers do not allow that

At least ours allow it, since I see the device in both cases and can play music over it in the old build if `/audio-mode:1` is set.


> Create a new issue for that if possible.

Can do of course. I'd still count it as regression from a37851161, though.

**Comment by LordOfTheRats** [comment]
[Trace with stacktrace on SEGFAULT](https://gist.github.com/LordOfTheRats/a1761872e485d6c6ec48c6872dc36967)

I'm still setting up remote debugging for my environment so I can have a closer look at the variable in question.
