### ISSUE TITLE
Timeout with satellite internet

### ISSUE THREAD

**Issue by TupaNegreiros** [FreeRDP/FreeRDP#6356]
On newer versions I'm unable to connect to RDP servers using high latency internet connection (ie satellite).

It worked fine at least with freerdp1 and remmina 1.3.x. and stopped working. I've tried with two different computers, using Linux Mint 19.3 and Ubuntu 20.04. When I use another internet connection, they work fine.

Running freerdp2 via bash, only get error "Timeout waiting for activation".

I couldn't find any config to increase timeout period, nor instructions how to compile it myself.
Please consider someone that eventually uses satellite internet, when he/she needs to access a server in a hurry, but before need to compile freerdp and remmina.

Please verify if there are any benefits reducing this timeout time. If possible, go back to the previous limit, or analyze if another error occurs. At least leave this limit configurable. I am available for more information and to test whatever is necessary.

**Comment by akallabeth** [comment]
@TupaNegreiros well, the timeout is already 15 seconds, so this is quite long. the `/timeout:<time in ms>` might be what you´re looking for (just run `xfreerdp` without arguments, then you get that one.

**Comment by TupaNegreiros** [comment]
@akallabeth Thanks for your reply.

Could you confirm that default timeout value is 15000? Using any value >= 11000 ms I could connect (Although my internet delay isn't so big).

**Comment by robertw1686** [comment]
I have the same problem.  Pressed go on Update Mgr and spent the next 2 days trying to get Remmina to connect to a Windows box.  It turns out it's just my slow satellite internet  (HughesNet) - unbelieveable...    Is there a workaround?

**Comment by TupaNegreiros** [comment]
@robertw1686 try on bash:
xfreerdp /u:username /v:servername /timeout:20000

Or else I use another computer with Windows, a Windows virtual machine or even a Raspberry with Remmina. 🤷‍♂️️
