### ISSUE TITLE
borken build on freebsd in 9f3adf10f85f0ab51c5ed67dc2a8cb3b0d519ebb

### ISSUE THREAD

**Issue by sss123next** [FreeRDP/FreeRDP#6377]
borken build on freebsd in 9f3adf10f85f0ab51c5ed67dc2a8cb3b0d519ebb

<mntent.h> does not exists on freebsd, even with gnulib installed.

**Comment by bmiklautz** [comment]
@sss123next thanks for the report. We don't have any *BSD builders for our CI so this one slipped through.

**Comment by akallabeth** [comment]
@sss123next if you know the equivalent of getting current mount points on `FreeBSD` we could fix this easily (there was a similar report for solaris) but we lack the test environments.

**Comment by sss123next** [comment]
unfortunately i don't, but i can investigate, we have freebsd people, so i think someone should know something, also here is another problem in client channels on FreeBDSM, related to libusb, i will create separate ticket later.

**Comment by rozhuk-im** [comment]
```
#include <sys/mount.h>

	int mntsize;
	size_t idx;
	struct statfs *mntbuf = NULL;

	mntsize = getmntinfo(&mntbuf, MNT_NOWAIT);
	for (idx = 0; idx < (size_t)mntsize; idx ++) {
		printf("%s - %s, local = %i, f_type = %i",
		    mntbuf[idx].f_mntonname, mntbuf[idx].f_fstypename,
		    (int)(0 != (MNT_LOCAL & mntbuf[idx].f_flags)),
		    mntbuf[idx].f_type);
	}
	free(mntbuf);
```

**Comment by akallabeth** [comment]
@rozhuk-im looks promising, are you able to create a pull request for that (sorry, lacking a test env here)

**Comment by rozhuk-im** [comment]
@akallabeth sorry, I'm going to trip in next day and have no time, @sss123next ask me for help and will handle it.

**Comment by sss123next** [comment]
ah.., me again ( ok, ok .... i will handle this...
