### ISSUE TITLE
Forwarding Serial Port From Raspberry Pi3 To My Window Thin Client

### ISSUE THREAD

**Issue by Luseun** [FreeRDP/FreeRDP#6378]
I can access the serial port of my Raspberry pi3 through Putty software /dev/ttyS0 . Now i installed FreeRDP on my Raspberry pi and login into my windows thin client, but when i am on my thin client my Raspberry pi can not forward my Serial port. Please can anyone show me how to edit the bash file to make it forward my serial port from my Raspberry to my Windows thin client?

Thank you.

**Comment by akallabeth** [comment]
Please use IRC or mailing list for support questions.
