### ISSUE TITLE
Improve Documentation of /network setting

### ISSUE THREAD

**Issue by GeoMarkou** [FreeRDP/FreeRDP#6384]
**Is your feature request related to a problem? Please describe.**
I read the documentation at the page [here](https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface) but I don't fully understand the scope of this option. I understand "LAN" is probably "highest quality but uses most bandwidth and is probably affected by latency a lot". But what is the difference between WAN, Broadband, and Modem?

**Describe the solution you'd like**
Add more information to this options so I can choose one that fits my situation.

**Describe alternatives you've considered**
Guessing and fruitless Google searches.

**Additional context**
I'm trying to connect to a computer that is very close to my physical location, and I have a great connection and low latency. But it's not a "LAN" connection.

**Comment by akallabeth** [comment]
@GeoMarkou this is mostly only relevant for older windows XP style RDP connections. `/network:auto` should be sufficient for all types.
