### ISSUE TITLE
Lenovo TIO24 Gen3 monitor inbuilt camera shows Black screen in Teams/Zoom Application

### ISSUE THREAD

**Issue by ppokhriyal** [FreeRDP/FreeRDP#6385]
Currently, I am using the FreeRDP Dev5 version

When I pass the **VID** and **PID** of inbuilt web camera of monitor  **/usb:id,dev:xxx:yyy**  and connecting to the server and using the camera in Teams Application or Zoom it shows the black screen or sometimes faded shadows.

**Comment by akallabeth** [comment]
@ppokhriyal you might want to try out #6363 as we fixed a few issues identified by @LordOfTheRats

**Comment by akallabeth** [comment]
Closing as targeting an old version.
