### ISSUE TITLE
Scrolling and keyholding behaviour 

### ISSUE THREAD

**Issue by kayfoe** [FreeRDP/FreeRDP#6388]
We use Gentoo and the Wayland version of FreeRDP and there are two bug that we found.
They only appear in Wayland and not in X.
1. Scrolling:
Even it got a lot better so far, the scrolling still is not like in regular Windows or with the X version of FreeRDP.
It is just too slow compared to Windows scrolling.

2. Keyholding:
When you press a key and hold it then normally it will repeat the letter over and over again, but with wlfreerdp they just don't.
It is just one single letter for a single press, no matter how long you hold the key.

We really like Your product so far and hope it will get even better.
Sincerly Kay

Edit:
We also tried it with Ubuntu to make sure that it's not a Gentoo problem but the bugs still occurred.

**Comment by ReubenM** [comment]
Adding myself to follow changes to this.

Interacting with a text terminal on remote windows box using wayland is awful compared to X11.

**Comment by compilenix** [comment]
Same here on Fedora 33 (`freerdp-2.2.0-4.fc33`).

**Comment by manio** [comment]
Only my two cents:
I also had two described problems: "slow" scrolling and lack of key repeat on wayland+swaywm, but after recently update on my Arch distro to package:
```freerdp 2:2.3.0-1```
then those two problems are gone, so maybe this issue is now obsolete?
