### ISSUE TITLE
Nvidia Opengl RDP

### ISSUE THREAD

**Issue by lixaotec** [FreeRDP/FreeRDP#6389]
Dear folks,

What did Nvidia launched, that turned RDP to suppor OpenGL?

In windows, now I can use programs like Blender with rdp, thats very nice!

Is it possible to support such with freerdp? 

https://developer.nvidia.com/designworks
https://developer.nvidia.com/nvidia-opengl-rdp

Thanks

**Comment by akallabeth** [comment]
@lixaotec check out https://github.com/ogon-project/ogon which implements a RDP server for linux. Currently no dedicated support for opengl/vulkan but should be possible to add support there.
