### ISSUE TITLE
[URBDRC] How to use the latest version of USB redirection

### ISSUE THREAD

**Issue by yunforum** [FreeRDP/FreeRDP#6396]
Using the latest version 2.2.0, USB parameters have changed
USB Device Redirection: / usb:id :054c:0268#4669:6e6b, addr:04 0C
addr  What does it mean and how to confirm the addr of the device

**Comment by akallabeth** [comment]
@yunforum changed from which version?
The syntax has been quite stable the last couple of years, so please give some more details.

**Comment by nbsoftware** [comment]
I confirm this:

% xfreerdp --version
This is FreeRDP version 2.2.0 (n/a)

% xfreerdp | grep -i usb
%

i.e. gives nothing
And any attempt to use /usb option gives an error

Can't it be related to https://github.com/FreeRDP/FreeRDP/issues/6461 ?
