### ISSUE TITLE
Possible broken heap in buffer_release

### ISSUE THREAD

**Issue by chakuzo** [FreeRDP/FreeRDP#6398]
It is possible to destroy the heap in the function UwacWindowShmAllocBuffers. 

If the xrealloc allocates more storage, it is possible that the pointer to the storage will be changed. If that happen, in the function buffer_release the uwacBuffer->used = false will write into unknown memory. I am a little bit unsure to fix it. I think the best way is to use a list instead of an array maybe. I am using in the moment a bigger fixed size array. 

I have debugged it with valgrind.

**Comment by akallabeth** [comment]
@hardening might be able to shed some light there.

**Comment by gschwind** [comment]
Hello,

It seems to be fixed by cbc6b666ae40b1f6a1634612f8bd5bc599eec42b

Best regards.
