### ISSUE TITLE
crash in ConvertFromUnicode

### ISSUE THREAD

**Issue by kubistika** [FreeRDP/FreeRDP#6399]
While testing the proxy, it crashed in function `ConvertFromUnicode` called in `rdp_recv_client_info`.
There's [ASAN output](https://trello-attachments.s3.amazonaws.com/5d8c4c79c3c6d06e79627361/5f17feb1e2e7e1412a4d1b03/0a9f18da3b053f969ac441533ab40e8b/WhatsApp_Image_2020-07-22_at_11.45.43.jpeg).

**Comment by akallabeth** [comment]
@kubistika thanks, looks like I already found the bug.
