### ISSUE TITLE
Laggy connection to Server 2019 w/ poor rendering (StratoDesk)

### ISSUE THREAD

**Issue by monkeytreehosting** [FreeRDP/FreeRDP#6406]
## To save time and help us identify the issue a bug report should at least contain the following:

I user StratoDesk NoTouch OS to connect into our hosted server environment, within this, we utilise FreeRDP; this has been working beautifully for ages, however recently when I went to test connections to Server 2019 boxes, it really didn't like it.

Upon connecting, it's giving a very laggy experience, and rendering is poor; a completely unusable experience.
Testing this connection on Windows, Mac, Ubuntu (Remmina) or FreeRDP as standard, works without issue, so there must be something NoTouch  OS is implimenting which is different.

Using the exact same configuration and build, connection to 2016 clusters, via gateway works flawlessly.

My connection details:

- Gateway in use
- cluster name
- FreeRDP 2.0 | 2.0-c11939e325
- Flags: +heartbeat,+auto-reconnect,/network:auto,+multitransport,/gfx,+gfx-thin-client

Can someone assist and point me in the right direction here please? Pleas do ask if you need any further information; I've provided all I can think of above.

I'm also trying to get Stratodesk to diagnose and assist also, so will post any further developments on here also

**Comment by akallabeth** [comment]
@monkeytreehosting not much we can help here, only thing you might want to try is `/gfx:avc444` if you have h264 support compiled in.

**Comment by monkeytreehosting** [comment]
Hi Akallabeth, thanks for the notes, appreciate it's a tricky one to diagnose.

I've received the build details from Stratodesk themselves:

----------------------

please find the build config attached, it's the following GIT commit currently:

4831373d58

# xfreerdp /buildconfig
This is FreeRDP version 3.0.0-dev (4831373)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=ON WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=ON WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 5.4.0
Target architecture: x64

-----------------------------------

I've further tested this on a basic Ubuntu machine without issue, simply running the following:

xfreerdp /v:*** /g:**** /u:xxx@Xxx.com /gu:xxx@xxx..com /w:1500 /h:1000

This works without issue, without any flags also.

I have sent all this information back to Stratodesk to review also, however any assistance to the right direction for me, or to pass over to Stratodesk, would be much appreciated!

Thanks,

David

**Comment by monkeytreehosting** [comment]
Hi,

Just to report back after some testing and changing things around, the strangest resolution...

I removed /network:auto from the flag options... and this is all working perfectly again now.

Has something changed for this to happen, or am I doing something wrong? This was (and is currently with 500+ clients) working perfectly on MS Svr 2016 and 2012R2

Thanks,

David

**Comment by StratoUser** [comment]
Hi,
Is there a setting in stratodesk NoTouch Center to remove this flag?

Br,

Bent

**Comment by akallabeth** [comment]
@monkeytreehosting I´d doubt that that flag can have that influence. (fyi: `/network:auto` is the default for some time now, as long as no `/rfx`, `/bpp`, `/gfx` or `/network` option is used)
can you verify with a vanilla/nightly build of ours just to be sure that it is not a bug introduced externally?
