### ISSUE TITLE
Failed to compile 2.2.0 on MacOS

### ISSUE THREAD

**Issue by zhangwenjian** [FreeRDP/FreeRDP#6407]
According to https://github.com/FreeRDP/FreeRDP/wiki/Compilation, I download code with 2.2.0 tag and compile on MacOS. I get these errors:

Determining if the pthread_mutex_timedlock exist failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_3e453/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_3e453.dir/build.make CMakeFiles/cmTC_3e453.dir/build
Building C object CMakeFiles/cmTC_3e453.dir/CheckSymbolExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_3e453.dir/CheckSymbolExists.c.o   -c /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckSymbolExists.c:8:19: error: use of undeclared identifier 'pthread_mutex_timedlock'; did you mean 'pthread_mutex_trylock'?
  return ((int*)(&pthread_mutex_timedlock))[argc];
                  ^~~~~~~~~~~~~~~~~~~~~~~
                  pthread_mutex_trylock
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/pthread.h:390:5: note: 'pthread_mutex_trylock' declared here
int pthread_mutex_trylock(pthread_mutex_t *);
    ^
1 error generated.
make[1]: *** [CMakeFiles/cmTC_3e453.dir/CheckSymbolExists.c.o] Error 1
make: *** [cmTC_3e453/fast] Error 2

File /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_mutex_timedlock
  return ((int*)(&pthread_mutex_timedlock))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_mutex_timedlock exists in the pthread failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_b4a1a/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_b4a1a.dir/build.make CMakeFiles/cmTC_b4a1a.dir/build
Building C object CMakeFiles/cmTC_b4a1a.dir/CheckFunctionExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -DCHECK_FUNCTION_EXISTS=pthread_mutex_timedlock -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_b4a1a.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_b4a1a
/usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b4a1a.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -DCHECK_FUNCTION_EXISTS=pthread_mutex_timedlock -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_b4a1a.dir/CheckFunctionExists.c.o  -o cmTC_b4a1a -lpthread 
Undefined symbols for architecture x86_64:
  "_pthread_mutex_timedlock", referenced from:
      _main in CheckFunctionExists.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_b4a1a] Error 1
make: *** [cmTC_b4a1a/fast] Error 2

Determining if the function pthread_mutex_timedlock exists in the pthreads failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c6e24/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_c6e24.dir/build.make CMakeFiles/cmTC_c6e24.dir/build
Building C object CMakeFiles/cmTC_c6e24.dir/CheckFunctionExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -DCHECK_FUNCTION_EXISTS=pthread_mutex_timedlock -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_c6e24.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_c6e24
/usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c6e24.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -DCHECK_FUNCTION_EXISTS=pthread_mutex_timedlock -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_c6e24.dir/CheckFunctionExists.c.o  -o cmTC_c6e24 -lpthreads 
ld: library not found for -lpthreads
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_c6e24] Error 1
make: *** [cmTC_c6e24/fast] Error 2

Determining if files sys/modem.h exist failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_dc376/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_dc376.dir/build.make CMakeFiles/cmTC_dc376.dir/build
Building C object CMakeFiles/cmTC_dc376.dir/CheckIncludeFiles.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_dc376.dir/CheckIncludeFiles.c.o   -c /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
/Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: 'sys/modem.h' file not found
#include <sys/modem.h>
         ^~~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_dc376.dir/CheckIncludeFiles.c.o] Error 1
make: *** [cmTC_dc376/fast] Error 2

Source:
/* */
#include <sys/modem.h>

int main(void){return 0;}

Determining if files sys/strtio.h exist failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_4d870/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_4d870.dir/build.make CMakeFiles/cmTC_4d870.dir/build
Building C object CMakeFiles/cmTC_4d870.dir/CheckIncludeFiles.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_4d870.dir/CheckIncludeFiles.c.o   -c /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
/Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: 'sys/strtio.h' file not found
#include <sys/strtio.h>
         ^~~~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_4d870.dir/CheckIncludeFiles.c.o] Error 1
make: *** [cmTC_4d870/fast] Error 2

Source:
/* */
#include <sys/strtio.h>

int main(void){return 0;}

Determining if files sys/eventfd.h exist failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_dc8df/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_dc8df.dir/build.make CMakeFiles/cmTC_dc8df.dir/build
Building C object CMakeFiles/cmTC_dc8df.dir/CheckIncludeFiles.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_dc8df.dir/CheckIncludeFiles.c.o   -c /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
/Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: 'sys/eventfd.h' file not found
#include <sys/eventfd.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_dc8df.dir/CheckIncludeFiles.c.o] Error 1
make: *** [cmTC_dc8df/fast] Error 2

Source:
/* */
#include <sys/eventfd.h>

int main(void){return 0;}

Determining if files sys/timerfd.h exist failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_79b42/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_79b42.dir/build.make CMakeFiles/cmTC_79b42.dir/build
Building C object CMakeFiles/cmTC_79b42.dir/CheckIncludeFiles.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer  -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_79b42.dir/CheckIncludeFiles.c.o   -c /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckIncludeFiles.c
/Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:2:10: fatal error: 'sys/timerfd.h' file not found
#include <sys/timerfd.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [CMakeFiles/cmTC_79b42.dir/CheckIncludeFiles.c.o] Error 1
make: *** [cmTC_79b42/fast] Error 2

Source:
/* */
#include <sys/timerfd.h>

int main(void){return 0;}

Determining if the function timer_create exists failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_bd11b/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_bd11b.dir/build.make CMakeFiles/cmTC_bd11b.dir/build
Building C object CMakeFiles/cmTC_bd11b.dir/CheckFunctionExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DWINPR_DLL -DWINPR_EXPORTS -DCHECK_FUNCTION_EXISTS=timer_create -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_bd11b.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_bd11b
/usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_bd11b.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DWINPR_DLL -DWINPR_EXPORTS -DCHECK_FUNCTION_EXISTS=timer_create -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_bd11b.dir/CheckFunctionExists.c.o  -o cmTC_bd11b -lrt 
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_bd11b] Error 1
make: *** [cmTC_bd11b/fast] Error 2

Determining if the function timer_delete exists failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6095c/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_6095c.dir/build.make CMakeFiles/cmTC_6095c.dir/build
Building C object CMakeFiles/cmTC_6095c.dir/CheckFunctionExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DWINPR_DLL -DWINPR_EXPORTS -DCHECK_FUNCTION_EXISTS=timer_delete -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_6095c.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_6095c
/usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6095c.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DWINPR_DLL -DWINPR_EXPORTS -DCHECK_FUNCTION_EXISTS=timer_delete -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_6095c.dir/CheckFunctionExists.c.o  -o cmTC_6095c -lrt 
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_6095c] Error 1
make: *** [cmTC_6095c/fast] Error 2

Determining if the function timer_settime exists failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_d97f4/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_d97f4.dir/build.make CMakeFiles/cmTC_d97f4.dir/build
Building C object CMakeFiles/cmTC_d97f4.dir/CheckFunctionExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DWINPR_DLL -DWINPR_EXPORTS -DCHECK_FUNCTION_EXISTS=timer_settime -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_d97f4.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_d97f4
/usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d97f4.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DWINPR_DLL -DWINPR_EXPORTS -DCHECK_FUNCTION_EXISTS=timer_settime -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_d97f4.dir/CheckFunctionExists.c.o  -o cmTC_d97f4 -lrt 
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_d97f4] Error 1
make: *** [cmTC_d97f4/fast] Error 2

Determining if the function timer_gettime exists failed with the following output:
Change Dir: /Users/zhangwenjian/Downloads/FreeRDP-2.2.0/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_206f3/fast"
/Library/Developer/CommandLineTools/usr/bin/make -f CMakeFiles/cmTC_206f3.dir/build.make CMakeFiles/cmTC_206f3.dir/build
Building C object CMakeFiles/cmTC_206f3.dir/CheckFunctionExists.c.o
/Library/Developer/CommandLineTools/usr/bin/cc   -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DWINPR_DLL -DWINPR_EXPORTS -DCHECK_FUNCTION_EXISTS=timer_gettime -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fPIE   -o CMakeFiles/cmTC_206f3.dir/CheckFunctionExists.c.o   -c /usr/local/Cellar/cmake/3.10.1/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_206f3
/usr/local/Cellar/cmake/3.10.1/bin/cmake -E cmake_link_script CMakeFiles/cmTC_206f3.dir/link.txt --verbose=1
/Library/Developer/CommandLineTools/usr/bin/cc  -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL -DWINPR_DLL -DWINPR_EXPORTS -DCHECK_FUNCTION_EXISTS=timer_gettime -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_206f3.dir/CheckFunctionExists.c.o  -o cmTC_206f3 -lrt 
ld: library not found for -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [cmTC_206f3] Error 1
make: *** [cmTC_206f3/fast] Error 2

**Comment by akallabeth** [comment]
Need a few more details on this one.
Just ran `cmake  -D"CMAKE_OSX_ARCHITECTURES:STRING=x86_64" .` on a clean checkout and the detection runs smooth.
