### ISSUE TITLE
Keyboard layout problem

### ISSUE THREAD

**Issue by weirdfishes9** [FreeRDP/FreeRDP#6409]
There is a ubuntu18:04 docker container in which I install the client `freerdp2-x11` and` tightvncserver`. I connect to this container using Remmina with the VNC protocol, and then, after entering the password, I connect to a Windows 10 remote desktop. Remote desktop connection parameters are passed to the container as environment variables (`-e` option).
 
Container run code:
```
docker run -d --rm --name main-check -e USER=**** -e RDP_IP=***.***.**.** -e VNC_RESOLUTION=1920x1080 -p 5901:5901 test-main:latest
```
But after the RDP-connection, the keyboard layout gets lost (for example, 'h' is printed instead of 'f'). Everything is fine inside the container, and after connecting via VNC, the password is entered without problems. So most likely the problem is in the RDP-connection. Please tell me what can be done in this situation? (Option / kbd: 0x\<id\> didn't help).

Script in `ENTRYPOINT`:
```
#!/bin/bash
set -e

###VNC settings
VNC_OPTIONS="-depth ${VNC_DEPTH} -geometry ${VNC_RESOLUTION} ${DISPLAY}"

DIRECTORY="$HOME/.vnc"
if [ ! -d "$DIRECTORY" ]; then
  mkdir -p "$DIRECTORY"
fi
umask 0077
chmod go-rwx "$HOME/.vnc"
vncpasswd -f <<<"$VNC_PASSWORD" >"$DIRECTORY/passwd"
VNC_IP=$(ip addr show eth0 | grep -Po 'inet \K[\d.]+')
echo ${VNC_OPTIONS}
vncserver -kill ${DISPLAY} || rm -rfv /tmp/.X*-lock /tmp/.X11-unix \
|| echo "remove old vnc locks to be a reattachable container"
mkdir /root/.Xsession
/usr/bin/vncserver ${VNC_OPTIONS}

###Password window
read_password() {
PROFILE_PASSWD=$(yad --width 300 --center --entry --hide-text \
--image "dialog-password" \
--text "Enter password \n <b>$1</b>:" \
--title " " --button=gtk-ok)
echo "$PROFILE_PASSWD"
}

USER_PASSWD=$(read_password $USER)
RDP_WIDTH=$(awk -F'[x]' '{print $1}' <<< $VNC_RESOLUTION)
RDP_HEIGHT=$(awk -F'[x]' '{print $2}' <<< $VNC_RESOLUTION)
echo $RDP_WIDTH
echo $RDP_HEIGHT

###Start RDP
xfreerdp /u:$USER /p:$USER_PASSWD /v:$RDP_IP:$RDP_PORT /cert-ignore \
/w:$RDP_WIDTH /h:$RDP_HEIGHT
```
List of environment variables in Dockerfile:
```
ENV DISPLAY=:1 \
    VNC_PORT=5901 \
    USER=root \
    VNC_DEPTH=24 \
    VNC_RESOLUTION=1280x1024 \
    VNC_PASSWORD=password \
    RDP_PORT=3389 \
    RDP_IP=
```

**Comment by akallabeth** [comment]
@weirdfishes9 this will never work as the VNC server causes the keyboard detection to fail. There simply is no way to get the correct layout with this setup, so you will have to live with that.
