### ISSUE TITLE
Allow multiple freerdp windows with only one local monitor

### ISSUE THREAD

**Issue by mox-mox** [FreeRDP/FreeRDP#6421]
**Is your feature request related to a problem? Please describe.**
I tired to get multi-monitor support to work under sway. It worked once but then I could not write anything, i.e. the keyboard would not work. And then I thought that it might be nice to detach the remote screens from the screens actually present on my laptop.

**Describe the solution you'd like**
I would like to have a way to open multiple freerdp windows. On my local computer, these should be normal windows that I can move around, etc. For the remote windows-computer these should be multiple monitors of one session.

**Example**
Currently, I'm using this:
```
xfreerdp +fonts -grab-keyboard /monitors:1,0 /multimon:force /dynamic-resolution /u:$USERNAME /v:$IP:$PORT /p:"$PASSWORD"
```
which -- if the second monitor is connected -- _sometimes_ gives me two windows. I would like to change this to e.g.
```
xfreerdp +fonts -grab-keyboard /fake-monitors:3 /dynamic-resolution /u:$USERNAME /v:$IP:$PORT /p:"$PASSWORD"
```
which would open 3 windows corresponding to 3 (virtual) monitors on the windows machine.

**Describe alternatives you've considered**
I tried to use the multi-monitor support. But this works only sometimes and obviously not when I do not have the second monitor attached. And I would like to put different monitors on different workspaces.

**Comment by akallabeth** [comment]
Sorry, this is a bit out of scope.
There is `Xephyr` and other X-Servers that can simulate that.
