### ISSUE TITLE
Option /network:auto breaks /bpp:24

### ISSUE THREAD

**Issue by daj92109** [FreeRDP/FreeRDP#6422]
I need to use /bpp:24 to get FreeRDP to work with my xrdp server on linux.  When I also set /network:auto the bpp value of 24 is set to 32.  This causes problems with my connection to my xrdp server.

It looks like this is caused by code in FreeRDP/client/common/cmdline.c lines 1156/1157 which then reset the bpp value at line 3366.

I can't follow the logic of the code in this file so I decided to report it rather than submit a pull request.

I am using FreeRDP version 2.2.0 (c72055d74) on a Raspery Pi 4.

**Comment by akallabeth** [comment]
Not a bug, this is required for network autodetection. (enables bandwidth measurement and setting of connection mode automatically, so do not rely on manual settings here)
