### ISSUE TITLE
Chrome blocks Windows nightlies as dangerous

### ISSUE THREAD

**Issue by simplesalt** [FreeRDP/FreeRDP#6434]
The [windows version](https://ci.freerdp.com/job/freerdp-nightly-windows/) cannot be downloaded on Chrome because Chrome [thinks it's probably a virus.](https://support.google.com/webmasters/answer/3258249)  If distribution on windows is something you want to invest in, you may consider running their analysis toolpak to resolve this issue.

**Comment by qarmin** [comment]
Also I see this warning on Firefox
This is virustotal results - https://www.virustotal.com/gui/file/e73369bced229175f393a01dae941d89c26bd92653fe7d4c73e8c0bae23f2503/detection

**Comment by akallabeth** [comment]
Duplicates #6336 
Please report to these 'malware' detection tools that they should check what they are doing.
