### ISSUE TITLE
How to set frame type to rdp server

### ISSUE THREAD

**Issue by SongKeTong** [FreeRDP/FreeRDP#6438]
Releated pull request for master: 
I use freerdp on linux to connet windows server. I want to get H.264 data and render myself.

Now I can get H.264 data before decompress,  I want to control the frame type from windows server, How to set frame type?

Such as I want to reset frame type ,so I need next frame type is I frame.

**Comment by akallabeth** [comment]
you can not control this from the client side.
The function to render is part of `SurfaceCommand` in `RdpgfxClientContext`
For further questions please ask using IRC or mailing list.

**Comment by SongKeTong** [comment]
hmmm... How about framerate? Can I control it?

**Comment by SongKeTong** [comment]
and bitrate?
