### ISSUE TITLE
Android build fails with error that openh264 is in the wrong file format

### ISSUE THREAD

**Issue by iiordanov** [FreeRDP/FreeRDP#6439]
**Description:**

Android build fails with error that openh264 is in the wrong file format. Error is:

[ 61%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/nsc_encode.c.o
/tmp/FreeRDP/libfreerdp/codec/nsc_encode.c:421:15: warning: ‘nsc_compute_byte_count’ defined but not used [-Wunused-function]
 static UINT32 nsc_compute_byte_count(NSC_CONTEXT* context, UINT32* ByteCount, UINT32 width,
               ^~~~~~~~~~~~~~~~~~~~~~
[ 61%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/ncrush.c.o
[ 62%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/xcrush.c.o
[ 62%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/mppc.c.o
[ 62%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/zgfx.c.o
[ 62%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/clear.c.o
[ 62%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/jpeg.c.o
[ 63%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/h264.c.o
[ 63%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/yuv.c.o
[ 63%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/rfx_sse2.c.o
[ 63%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/nsc_sse2.c.o
[ 64%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/h264_openh264.c.o
[ 64%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_add.c.o
[ 64%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_andor.c.o
[ 64%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_alphaComp.c.o
[ 64%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_colors.c.o
[ 65%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_copy.c.o
[ 65%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_set.c.o
[ 65%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_shift.c.o
[ 65%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_sign.c.o
[ 66%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_YUV.c.o
[ 66%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_YCoCg.c.o
[ 66%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/primitives.c.o
[ 66%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_colors_opt.c.o
[ 66%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_set_opt.c.o
[ 67%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_add_opt.c.o
[ 67%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_alphaComp_opt.c.o
[ 67%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_andor_opt.c.o
[ 67%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_shift_opt.c.o
[ 67%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_sign_opt.c.o
[ 68%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_YCoCg_opt.c.o
[ 68%] Building C object libfreerdp/CMakeFiles/freerdp.dir/primitives/prim_YUV_ssse3.c.o
[ 68%] Linking C shared library libfreerdp3.so
../../../../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a/libopenh264.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
libfreerdp/CMakeFiles/freerdp.dir/build.make:3922: recipe for target 'libfreerdp/libfreerdp3.so.3.0.0' failed
make[2]: *** [libfreerdp/libfreerdp3.so.3.0.0] Error 1
CMakeFiles/Makefile2:1251: recipe for target 'libfreerdp/CMakeFiles/freerdp.dir/all' failed
make[1]: *** [libfreerdp/CMakeFiles/freerdp.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
[ERROR] cmake --build . --target install retured 2

**Steps to reproduce:**

1) Cloning and checking out master or stable-2.0 branch.

2) Enable OPENH264

diff --git a/scripts/android-build.conf b/scripts/android-build.conf
index cd07da0db..e852d912d 100644
--- a/scripts/android-build.conf
+++ b/scripts/android-build.conf
@@ -9,8 +9,8 @@
-WITH_OPENH264=0
+WITH_OPENH264=1
 WITH_OPENSSL=1
 BUILD_DEPS=1
 DEPS_ONLY=0

3) Attempt a build of FreeRDP with NDK r15c (I tried r16b and r17c as well):

export ANDROID_NDK=/path/to/android-ndk-r15c/
export CMAKE_PROGRAM=/usr/bin/cmake
./scripts/android-build-freerdp.sh 

**Expected behavior**

Successful build.

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Ubuntu 18.04
 - Architecture: [armeabi-v7a]:

**Comment by akallabeth** [comment]
current build scripts work fine. ( 9ebbefa5fe70fd0d702bcbdff365a622997f67dd ) and ubuntu 18.04 is out of support
