### ISSUE TITLE
undefined reference to `mappedGeometryUnref'  

### ISSUE THREAD

**Issue by SongKeTong** [FreeRDP/FreeRDP#6441]
I want to build a static library ,and this is my cmake code : 
cmake -DCMAKE_BUILD_TYPE=Release   -DCMAKE_INSTALL_PREFIX=./xietong-release-install    -DBUILD_SHARED_LIBS=OFF   -DWITH_SSE2=ON   -DWITH_CLIENT_INTERFACE=ON   -DWITH_OPENSSL=ON   -DWITH_SAMPLE=OFF   -DWITH_X11=ON   -DWITH_XT=ON   -DWITH_XKBFILE=OFF   -DWITH_OSS=OFF   -DWITH_ALSA=OFF   -DWITH_FFMPEG=OFF   -DWITH_OPENH264=OFF   -DWITH_X264=OFF   -DWITH_XCURSOR=OFF   -DWITH_XEXT=ON   -DWITH_XFIXES=OFF   -DWITH_XI=OFF   -DWITH_XINERAMA=OFF   -DWITH_XRANDR=OFF   -DWITH_XRENDER=OFF   -DWITH_XSHM=OFF   -DWITH_XV=OFF   -DWITH_WAYLAND=OFF -DCHANNEL_GEOMETRY=ON DWITH_CHANNELS=ON ..

but I get an error : 

../../../channels/video/client/libvideo-client.a(video_main.c.o): In function `video_onMappedGeometryClear':
video_main.c:(.text+0x302): undefined reference to `mappedGeometryUnref'
../../../channels/video/client/libvideo-client.a(video_main.c.o): In function `VideoFrame_free':
video_main.c:(.text+0x617): undefined reference to `mappedGeometryUnref'
video_main.c:(.text+0x66e): undefined reference to `mappedGeometryUnref'
../../../channels/video/client/libvideo-client.a(video_main.c.o): In function `video_data_on_data_received':
video_main.c:(.text+0xe54): undefined reference to `mappedGeometryRef'
video_main.c:(.text+0xf36): undefined reference to `mappedGeometryUnref'
../../../channels/video/client/libvideo-client.a(video_main.c.o): In function `video_plugin_terminated':
video_main.c:(.text+0x125d): undefined reference to `mappedGeometryUnref'
../../../channels/video/client/libvideo-client.a(video_main.c.o): In function `video_timer':
video_main.c:(.text+0x1711): undefined reference to `mappedGeometryUnref'
../../../channels/video/client/libvideo-client.a(video_main.c.o): In function `video_control_on_data_received':
video_main.c:(.text+0x1f77): undefined reference to `mappedGeometryUnref'
video_main.c:(.text+0x20d9): undefined reference to `mappedGeometryUnref'
video_main.c:(.text+0x2313): undefined reference to `mappedGeometryRef'
../../../channels/geometry/client/libgeometry-client.a(geometry_main.c.o): In function `geometry_DVCPluginEntry':
geometry_main.c:(.text+0x13f8): undefined reference to `mappedGeometryUnref'
collect2: error: ld returned 1 exit status
client/X11/cli/CMakeFiles/xfreerdp-cli.dir/build.make:131: recipe for target 'client/X11/xfreerdp' failed
make[2]: *** [client/X11/xfreerdp] Error 1
CMakeFiles/Makefile2:3782: recipe for target 'client/X11/cli/CMakeFiles/xfreerdp-cli.dir/all' failed

**Comment by akallabeth** [comment]
you´re trying to build `xfreerdp` statically which we do not support currently.
(and you´re setting flags that should be autodetected, like the whole `WITH_X*` stuff)
