### ISSUE TITLE
Freerdp-2.2.0 smartcard redirection issue

### ISSUE THREAD

**Issue by ganeshjkale** [FreeRDP/FreeRDP#6444]
Server :- windows server 2016
Client :- Ubuntu-18.04_x64
Hardware:- AutoePass2003 usb token

Note:-
1:-smartcard is redirected for 1 second and then disconnected and this goes on (no usb port issue on laptop verified)
2:-Tried with additional command /client-build-number:2600 or /client-build-number:5000 but same issue.

Commandline:-
xfreerdp /u:administrator /p:xxxx /v:192.168.0.x /f +floatbar /gfx-h264 /smartcard /log-level:TRACE 2>&1 |tee smartcard_issue.txt

sudo opensc-tool --list-readers
# Detected readers (pcsc)
Nr.  Card  Features  Name
0    Yes             FT ePass2003Auto 00 00

xfreerdp /buildconfig
This is FreeRDP version 2.2.0 (2.2.0)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=ON WITH_LIBAVCODEC=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 5.4.0
Target architecture: x64

Attached Trace Log files:-
[smartcard_issue.txt](https://github.com/FreeRDP/FreeRDP/files/5102796/smartcard_issue.txt)

**Comment by akallabeth** [comment]
@ganeshjkale you will not like the answer, currently nothing we can do.
You might try a different reader (brand/model) and check if it works better, but we only redirect what `pcsc-lite` provides.
From your log it is not an issue with missing functions but a supported one aborting with an error condition.

If you are capable to, you could try to check differences in the `ATR` string sent from `pcsc-lite / freerdp` and `mstsc` maybe we can add something there.

**Comment by ganeshjkale** [comment]
@akallabeth  pcscd daemon logs for ATR value is below :- 

> 00000162 hotplug_libudev.c:297:get_driver() Looking for a driver for VID: 0x096E, PID: 0x080A, path: /dev/bus/usb/001/010
> 00000013 hotplug_libudev.c:436:HPAddDevice() Adding USB device: FT ePass2003Auto
> 00000053 readerfactory.c:1075:RFInitializeReader() Attempting startup of FT ePass2003Auto 00 00 using /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Linux/libccid.so
> 00000272 readerfactory.c:950:RFBindFunctions() Loading IFD Handler 3.0
> 00000031 ifdhandler.c:1961:init_driver() Driver version: 1.4.29
> 00000730 ifdhandler.c:1978:init_driver() LogLevel: 0x0003
> 00000012 ifdhandler.c:1989:init_driver() DriverOptions: 0x0000
> 00000188 ifdhandler.c:110:CreateChannelByNameOrChannel() Lun: 0, device: usb:096e/080a:libudev:1:/dev/bus/usb/001/010
> 00000014 ccid_usb.c:302:OpenUSBByName() Using: /usr/lib/pcsc/drivers/ifd-ccid.bundle/Contents/Info.plist
> 00000705 ccid_usb.c:320:OpenUSBByName() ifdManufacturerString: Ludovic Rousseau (ludovic.rousseau@free.fr)
> 00000012 ccid_usb.c:321:OpenUSBByName() ifdProductString: Generic CCID driver
> 00000009 ccid_usb.c:322:OpenUSBByName() Copyright: This driver is protected by terms of the GNU Lesser General Public License version 2.1, or (at your option) any later version.
> 00009535 ccid_usb.c:656:OpenUSBByName() Found Vendor/Product: 096E/080A (FT ePass2003Auto)
> 00000015 ccid_usb.c:658:OpenUSBByName() Using USB bus/device: 1/10
> 00000015 ccid_usb.c:717:OpenUSBByName() bNumDataRatesSupported is 0
> 00003709 ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFB3, usb:096e/080a:libudev:1:/dev/bus/usb/001/010 (lun: 0)
> 00000017 readerfactory.c:396:RFAddReader() Using the reader polling thread
> 00000383 ifdhandler.c:381:IFDHGetCapabilities() tag: 0xFAE, usb:096e/080a:libudev:1:/dev/bus/usb/001/010 (lun: 0)
> 00000027 ifdhandler.c:476:IFDHGetCapabilities() Reader supports 1 slot(s)
> 00000812 ifdhandler.c:1154:IFDHPowerICC() action: PowerUp, usb:096e/080a:libudev:1:/dev/bus/usb/001/010 (lun: 0)
> 00004382 eventhandler.c:287:EHStatusHandlerThread() powerState: POWER_STATE_POWERED
> 00000036 Card **ATR: 3B 9F 95 81 31 FE 9F 00 66 46 53 05 10 04 31 71 DF 00 00 06 00 00 20** 
> 05003239 ifdhandler.c:1154:IFDHPowerICC() action: PowerDown, usb:096e/080a:libudev:1:/dev/bus/usb/001/010 (lun: 0)
> 00000372 eventhandler.c:480:EHStatusHandlerThread() powerState: POWER_STATE_UNPOWERED
> 

Freerdp Debug logs also shows same ATR value :- 

> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] - GetStatusChangeW_Return {
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] -   ReturnCode: SCARD_S_SUCCESS (0x00000000)
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] -   cReaders: 2
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: dwCurrentState: SCARD_STATE_UNAWARE (0x00000000)
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: dwEventState: SCARD_STATE_UNAWARE (0x00000000)
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] -     [0]: cbAtr: 0 rgbAtr: {  }
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] -     [1]: dwCurrentState: SCARD_STATE_UNAWARE (0x00000000)
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] -     [1]: dwEventState: SCARD_STATE_CHANGED | SCARD_STATE_PRESENT (0x00010022)
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] -     [1]: cbAtr: 23 rgbAtr: { 3B9F958131FE9F006646530510043171DF000006000020 }
> [15:22:29:881] [16133:16175] [DEBUG][com.freerdp.channels.smartcard.client] - }
>

**Comment by akallabeth** [comment]
@ganeshjkale ok, maybe I was not being specific enough.
The difference between a `mstsc` connecting and `xfreerdp` connecting (dumping the `ATR` server side)
I´ve seen some modifications there but never had enough time to analyze this.

**Comment by ganeshjkale** [comment]
@akallabeth  ok i will check with mstsc on server side ,can you guide me where to check logs on windows other than event logs or any tool for same

**Comment by akallabeth** [comment]
@ganeshjkale https://github.com/FreeRDP/FreeRDP/issues/6420 has some references.
the cyberjack tool should work well enough for this.

**Comment by ganeshjkale** [comment]
@akallabeth issue is happening due to TIMEOUT

**Comment by akallabeth** [comment]
Closing, #6792 fixes lots of smartcard related issues, create a new issue if not resolved.
