### ISSUE TITLE
Bug in parsing of console parameters

### ISSUE THREAD

**Issue by benesjan** [FreeRDP/FreeRDP#6445]
After updating from Ubuntu [amd64] 18.04 to 20.04 and along with it updating FreeRDP to version 2.1.1 I am getting the following error:

> [21:45:40:742] [47530:47530] [ERROR][com.winpr.commandline] - Failed at index 1 [/cert:ignore]: Invalid sigil,

when I run xfreerdp with the following parameters:
> xfreerdp /cert:ignore /u:username /p:password /v:IP /size

I didn't modify the command and the connection to the target IP works fine from other devices which leads to my suspicion that there is a bug in this version. 

Thank you,
Jan

**Comment by akallabeth** [comment]
Please read command line help output ;)
`/size:<width>x<height> or <percent>%[wh] Screen size`
