### ISSUE TITLE
NUM Lock state and led not synced everytime when GFX is on (TS2012)

### ISSUE THREAD

**Issue by felkcir** [FreeRDP/FreeRDP#6449]
**Describe the bug**
NUM Lock state not synced with the following combination: current nightly build with /gfx on and 2012 Terminal Server
While logging in, the numlock state (server side) is off even when it is enabled on client side
If GFX is off, NUM lock state sync works properly

**To reproduce:**
easy to reproduce as it happens everytime:
xfreerdp /v:ADDRESS /u:USER /p:PW /d:DOMAIN /gfx

it does sync again as soon as the windows loses focus and regains it (minimize -> open)
it does also sync after pressing Capslock when logged into the session

**freeRDP Version**
FreeRDP version 3.0.0-dev (68c7bcc65) 
newest 2.0 and 2.1 aswell

**OS connecting to**
Windows Server 2012 R2

**OS connecting from**
Ubuntu 20.04

**Comment by akallabeth** [comment]
Duplicates #5466
