### ISSUE TITLE
How to get h264 data when set avc420

### ISSUE THREAD

**Issue by SongKeTong** [FreeRDP/FreeRDP#6450]
I want to get h264 data from freerdp, 
I found that when I set avc444, I can get h264 in function  gdi_SurfaceCommand_AVC444 in  file gdi.c .
But when I set type avc420, it didn't run into gdi_SurfaceCommand_AVC420 but gdi_SurfaceCommand_RemoteFX, how can I get h264 in this function?

**Comment by akallabeth** [comment]
Please use the mailing list or IRC for support questions.

**Comment by SongKeTong** [comment]
how to use the mailing list or IRC for support questions.

**Comment by hardening** [comment]
Take some of _your_ time googling "freerdp mailing list" or "freerdp irc", and you should find out.
