### ISSUE TITLE
aFreeRDP Client stopped functioning and started freezing - Android

### ISSUE THREAD

**Issue by cogphone** [FreeRDP/FreeRDP#6451]
Hello FreeRDP Team,
 
I have used the freeRDP Android client in my Android app and my client stopped functioning and started freezing.
And I am getting the below mentioned error In the Android Studio Logs:

E/com.freerdp.core.transport: [pid=4603:tid=8fdea920] - BIO_read returned a system error 104: Connection reset by peer
E/com.freerdp.core: [pid=4603:tid=8fdea920] - freerdp_check_fds() failed - 0
E/com.freerdp.client.android: [pid=4603:tid=8fdea920] - Failed to check FreeRDP file descriptor
2020-08-27 09:59:29.064 4603-8581/com.vd/com.freerdp.client.android: [pid=4603:tid=8fdea920] - Prepare shutdown...

How I can Fix this issue, Please Suggest.

I'm grateful for any help,
Thanks.

**Comment by akallabeth** [comment]
The connection was ended by the server. If you use the library in your own client you most likely forgot to handle that case.

**Comment by cogphone** [comment]
Thanks for your reply.

can you tell me, how we can handle that case ?
