### ISSUE TITLE
Check Session connected or disconnected - Android

### ISSUE THREAD

**Issue by cogphone** [FreeRDP/FreeRDP#6452]
Hello FreeRDP Team,

Can you tell me, which method is used to check the session is connected or disconnected in aFreeRDP?

I want to exit from the SessionActivity screen when session disconnected. 

Please Suggest.

Thanks,

**Comment by akallabeth** [comment]
Please use the mailing list or IRC for support (just as suggested in the issue template).
Please also be a bit more specific in your questions, this is a bit too generic.
