### ISSUE TITLE
freerdp 2.2.0 playing sound stopped when mouse move to the top of the screen and trigger floatbar show

### ISSUE THREAD

**Issue by amazingfate** [FreeRDP/FreeRDP#6460]
here it the command to connect:
xfreerdp /multimon /sound:sys:pulse,channel:2,quality:dynamic,format:1 /microphone:sys:pulse /cert:ignore /rfx /video /gfx:AVC444 /floatbar /gdi:hw /v:192.168.15.51 /u:local.jfliu /p:*
server is win10p 2005

when playing music the floatbar is hidden, then I move the cursor to the top and the floatbar start to show, at the same time music stopped for about 1 second.

**Comment by akallabeth** [comment]
Is this reproducible? Sounds more like a transient network thing

**Comment by amazingfate** [comment]
my fault, I add ```sleep(1);```before the floatbar start to show, whitch is the root cause
