### ISSUE TITLE
No /usb commandline on stable-2.0 branch (missing URBDRC channel)

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#6461]
Hi, I think there is a problem on cmake configuration when compiling stable-2.0 branch:

```
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_CUPS=on -DWITH_PULSE=on -DCMAKE_INSTALL_PREFIX:PATH=/opt/remmina_devel/freerdp .
```

The produced executable does not have usb support:
```
xfreerdp /? | fgrep usb
```
outputs nothing.

I can see
```
CHANNEL_URBDRC:BOOL=ON
CHANNEL_URBDRC_CLIENT:BOOL=ON
```
on  CmakeCache.txt

But then config.h
```
config.h:/* #undef CHANNEL_URBDRC */
config.h:/* #undef CHANNEL_URBDRC_CLIENT */
config.h:/* #undef CHANNEL_URBDRC_SERVER */
config.h:/* #undef WITH_DEBUG_URBDRC */
```

(discovered from remmina user "unable to redirect usb camera" here https://gitlab.com/Remmina/Remmina/-/issues/2265#note_404332434)

**Comment by nbsoftware** [comment]
Compiling FreeRDP from HEAD resolves this.
Can this fix be release?
