### ISSUE TITLE
local drive does not mount

### ISSUE THREAD

**Issue by ng0177** [FreeRDP/FreeRDP#6465]
FreeRDP version 2.2.0
`xfreerdp /drive:home /u:user /v:site` yields
`[11:41:15:725] [57353:57353] [ERROR][com.winpr.commandline] - Failed at index 1 [/drive:home]: PostFilter rule could not be applied`

**Comment by akallabeth** [comment]
`xfreerdp /?` lists the syntax, please read it.
```
 /drive:<name>,<path>              Redirect directory <path> as named share
                                      /drive:hotplug,*. This argument provides
```

**Comment by ng0177** [comment]
I read too fast, works well!

**Comment by ng0177** [comment]
Not under FreeRDP version 3.0.0-dev (616af2d):
`flatpak run com.freerdp.FreeRDP /drive:name,/mnt/name /u:user /v:site`
```
X11 /app/bin/xfreerdp
[13:29:28:937] [4:4] [ERROR][com.winpr.commandline] - Failed at index 1 [/drive:BWTS-EXT,/mnt/06a53ec5-9ce1-4c1f-a284-f070b5bb858c/STORE/DATA-EXT/BWTS-EXT]: PostFilter rule could not be applied
```

**Comment by akallabeth** [comment]
@ng0177 I´d check the flatpak chapter about permissions ;)
