### ISSUE TITLE
Windows 2008 R2  does not respond to the mouse movement PDU after about 5 minutes of frequent mouse movement

### ISSUE THREAD

**Issue by Jim-Zhang** [FreeRDP/FreeRDP#6472]
**Describe the bug**
In some windows 10 using xfreerdp to access some windows 2008 r2 server through x11, after about 5 minutes of frequent mouse movement, the server does not respond to the mouse movement PDU, but can respond to keyboard events (such as CTRL+ALT+DEL).

**To Reproduce**
1. Use xshell to use ssh protocol to access linux, type xfreerdp command（/usr/bin/xfreerdp -u administrator -p Administrator@01 -n 172.22.130.136 172.22.130.136）
2. Mouse move about 5 minutes
3. Do not reponsed to mouse movement PDU

**Expected behavior**
Mouse move event is normal.

**Screenshots**

**Application details**
* FreeRDP: freerdp 0.8/1.1.0-beta1(git c959)/2.0.0-RC4 
* Command line used (freerdp-0.8.2-1.mga1.x86_64.rpm): /usr/bin/xfreerdp -u administrator -p Administrator@01 -n 172.22.130.136 172.22.130.136
* Output of `xfreerdp /buildconfig`: 
* OS version connecting to (server side): Windows 2008 R2
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: CentOS 7.7.1908
 - Architecture: x86_64

**Comment by akallabeth** [comment]
Please test with more recent versions.
Also ensure this is not a server side issue (can this be reproduced with other clients as well?)

**Comment by Jim-Zhang** [comment]
Compile the freerdp 2.2.0 windows client, and use the compiled wfreerdp.exe to connect to the target Windows Server. After a period of operation, the mouse cannot be moved.
But using MobaXterm and mstsc to connect to the target Windows Server, there is no such phenomenon.

**Comment by Jim-Zhang** [comment]
> Please test with more recent versions.
> Also ensure this is not a server side issue (can this be reproduced with other clients as well?)

Compile the freerdp 2.2.0 windows client, and use the compiled wfreerdp.exe to connect to the target Windows Server. After a period of operation, the mouse cannot be moved.
But using MobaXterm and mstsc to connect to the target Windows Server, there is no such phenomenon.

**Comment by akallabeth** [comment]
@Jim-Zhang since you still use self compiled versions (and not the nightly) could you add your compilation options and/or try with the nightly builds please?

**Comment by Jim-Zhang** [comment]
@akallabeth 
I will try with the nightly builds. https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=vs2013/
**compilation options:**
/GS /W3 /Zc:wchar_t /I"C:\Program Files\OpenSSL-Win64\include" /I"C:\Users\shterm\Desktop\freerdp\freerdp22\FreeRDP-2.2.0.build" /I"C:\Users\shterm\Desktop\freerdp\freerdp22\FreeRDP-2.2.0.build\include" /I"C:\Users\shterm\Desktop\freerdp\freerdp22\FreeRDP-2.2.0\include" /I"C:\Users\shterm\Desktop\freerdp\freerdp22\FreeRDP-2.2.0\winpr\include" /I"C:\Users\shterm\Desktop\freerdp\freerdp22\FreeRDP-2.2.0.build\winpr\include" /I"C:\Users\shterm\Desktop\freerdp\freerdp22\FreeRDP-2.2.0\rdtk\include" /I"C:\Users\shterm\Desktop\freerdp\freerdp22\FreeRDP-2.2.0.build\rdtk\include" /I"C:\Users\shterm\Desktop\freerdp\freerdp22\FreeRDP-2.2.0\client\Windows" /Gm- /O2 /Ob2 /Fd"wfreerdp-client.dir\Release\vc141.pdb" /Zc:inline /fp:precise /D "WIN32" /D "_WINDOWS" /D "WINPR_DLL" /D "NDEBUG" /D "_AMD64_" /D "UNICODE" /D "_UNICODE" /D "_CRT_SECURE_NO_WARNINGS" /D "WIN32_LEAN_AND_MEAN" /D "_WINSOCK_DEPRECATED_NO_WARNINGS" /D "WINVER=0x0601" /D "_WIN32_WINNT=0x0601" /D "WINPR_EXPORTS" /D "FREERDP_EXPORTS" /D "WITH_OPENSSL" /D "HAVE_CONFIG_H" /D "CMAKE_INTDIR=\"Release\"" /errorReport:prompt /WX- /Zc:forScope /Gd /MT /Fa"wfreerdp-client.dir\Release\" /nologo /Fo"wfreerdp-client.dir\Release\" /Fp"wfreerdp-client.dir\Release\wfreerdp.pch" /diagnostics:classic

**Comment by Jim-Zhang** [comment]
Finally, it was identified as a server-side issue where the mouse would freeze if moved quickly.
@akallabeth Thanks.
