### ISSUE TITLE
Possible usage of null pointer in transport.c

### ISSUE THREAD

**Issue by qarmin** [FreeRDP/FreeRDP#6474]
`transport` is used, but later is checked if is equal to null

https://github.com/FreeRDP/FreeRDP/blob/cf2daeb01d3325a9de97348047caf4b8974f2b76/libfreerdp/core/transport.c#L875-L881

and 

https://github.com/FreeRDP/FreeRDP/blob/cf2daeb01d3325a9de97348047caf4b8974f2b76/libfreerdp/core/transport.c#L502-L504

**Comment by akallabeth** [comment]
@qarmin thank you for checking.
