### ISSUE TITLE
Smartcard is not redirected after reconnection

### ISSUE THREAD

**Issue by pestoffne** [FreeRDP/FreeRDP#6476]
Server : Windows Server 2012 amd64 with Remote Desktop Services
Client : Debian 8 i386 with XFCE (gcc 4.9.2)
FreeRDP : version 2.2.0
Smartcard: Rutoken Lite

**To Reproduce**
1. Connect to Server
./xfreerdp /v:10.0.2.2:8189 /smartcard /u:'Terminal_1' /p:'P@ssw0rdd' /cert-ignore /log-level:trace
2. Smartcard is redirected to the server succesfully (see Picture 1).
3. Do not use keyboard and mouse and wait util disconnected. (`Set time limit for active but idle Remote Desktop Services sessions` policy should be Enabled on Server)
4. Immediately after reconnect using same command. Reconnection should be while the Windows session for user "Terminal_1" is still open.
5. I expect the smartcard to be reconnected to the server as in step №2. But the server does not actually see the smartcard (see Picture 2).

There is no such issue on FreeRDP version 1.2.4-dev (git 9101135).

**Logs**
Step 1 log. Smartcard is forwarded to the server succesfully.
[log1.zip](https://github.com/FreeRDP/FreeRDP/files/5209176/log1.zip)
Step 4 log. Failed to forward smartcard to the server after reconnection.
[log4.zip](https://github.com/FreeRDP/FreeRDP/files/5209178/log4.zip)

Picture 1. The rutoken readers combobox contains a redirected smartcard. Success.
![token-in-list](https://user-images.githubusercontent.com/12718711/92930986-01fa1280-f46d-11ea-964a-f32949dad971.PNG)

Picture 2. The rutoken reades combobox is empty. Failed to redirect.
![empty-combo-box](https://user-images.githubusercontent.com/12718711/92931326-7d5bc400-f46d-11ea-8364-af2db221511c.PNG)

**Comment by akallabeth** [comment]
Could you check out if `/client-build:number:2600` helps? We added newer smartcard redirection protocol support and that might not be supported properly by your server.

**Comment by pestoffne** [comment]
I added this parameter. Issue is still reproducing.

Step 1 log on FreeRDP 2.2.0 with `/build-client-number:2600` [log1-build-number-client-2600.zip](https://github.com/FreeRDP/FreeRDP/files/5217385/log1-build-number-client-2600.zip)
Step 4 log on FreeRDP 2.2.0 with `/build-client-number:2600` [log4-build-number-client-2600.txt](https://github.com/FreeRDP/FreeRDP/files/5217387/log4-build-number-client-2600.txt)

---
P.S.: Also may be usefull.
Step 1 log on FreeRDP 1.2.4 [log1-on-1.2.4.txt](https://github.com/FreeRDP/FreeRDP/files/5217342/log1-on-1.2.4.txt)
Step 4 log on FreeRDP 1.2.4 [log4-on-1.2.4.txt](https://github.com/FreeRDP/FreeRDP/files/5217343/log4-on-1.2.4.txt)

**Comment by akallabeth** [comment]
@pestoffne I´ve had a look at the logs and the diff in the source. could not spot a difference, but that may be hardware dependent (have some gemalto readers here to test)
any more information you could provide?
Also, could you run a build with `-DWITH_SMARTCARD_INSPECT=ON`? Might reveal some more details on what is going on.
If possible, please attach full logs with `/log-level:tracee 2>&1 |tee log.txt` so we can search for differences.

**Comment by pestoffne** [comment]
Server changed to: Windows 10 Enterprise amd64 10.0.18363
Client changed to: Debian 10 amd64
FreeRDP : version 2.2.0
Smartcard: Rutoken Lite

Issue is reproducible on new configuration.

Flag `-DWITH_SMARTCARD_INSPECT=ON` was added.

First connection with successful redirection.
`./xfreerdp /v:192.168.54.146 /u:Toster /p:11111111 /cert-ignore /smartcard /log-level:trace | tee log-3a.txt`
[log-3a.txt](https://github.com/FreeRDP/FreeRDP/files/5941269/log-3a.txt)

Second connection where the redirected smartcard is not recognized by the rutoken software. 
[log-3b.txt](https://github.com/FreeRDP/FreeRDP/files/5941270/log-3b.txt)

I bet this is not reproducible with gemalto.

What information can I provide?
Server and client virtual machines were created to reproduce issues like that. So I can provide any logs, like windows event log or pcscd output. 
I am not affiliated with Aktiv, so the rutoken control panel for me is a closed-source black box.

**Comment by akallabeth** [comment]
@pestoffne did a bug hunt and found a few issues with smartcard, could you try #6792 ?

**Comment by pestoffne** [comment]
I think this is not FreeRDP problem. The smartcard software communicates with the smartcard hardware via RDP. The smartcard software just loses hardware without closing the session properly (SCardDisconnect) when I disconnect from the RDP server.
After reconnecting, I can restart the smartcard software. After that it works properly.
