### ISSUE TITLE
Sound rattles from Windows to Linux (xrdp) or Windows Server (RDS)

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#6490]
Using the latest FreeRDP 2.2.0 in Windows (10), compiled with ffmpeg (4.2.4), enabling WAVE_FORMAT_AAC_MS (0xa106) and connecting to either Linux (xrdp 0.9.10) or Windows Server (RDS 2016) results in sound rattling frequently, although it stays in sync. This problem had been fixed in the past.

**Comment by akallabeth** [comment]
@vscfreire sadly there are quite a few factors influencing this.
1. server os and encoder
1. client decoder
1. bandwidth and latency

* so, can you point to something that works for your case with only changing one element?
* Do you get some warnings/errors from ffmpeg? (there have been versions that did not like the AAC stream sometimes)

**Comment by vscfreire** [comment]
1. server os and encoder
The Linux xrdp server is also using the same ffmpeg version but if that wasn't the case, Windows Server 2016 and Linux worked in the past. If I change freerdp code to the last merge I did, the rattles are gone to both servers.
2. client decoder
I have been using ffmpeg 4.2 with freerdp for some time now, and the rattles and the skips had been fixed. If I use it with freerdp 2.2.0, the rattles are back (but not the skips).
3. bandwidth and latency
I tried changing the network conditions but the rattles are similar (they dont get worse or better).

If you compile freerdp 2.2.0 with ffmpeg and force the AAC format I suppose you will get the same result.

This are the comments I have in my freerdp version that works fine:
23/12/2019 12:18 FreeRDP: 
* use rdpsnd_winmm.c from upstream commit 18e4245791189075833b718781037ed657530f6b (before WinMM backend remake); 
* use latest rdpsnd_main.c (from upstream commit 6e6dfc3e2a315cbfdd1f1b29c8501cc8cb20bf00).

**Comment by vscfreire** [comment]
Just to let you know that I also tried compiling the same client environment (freerdp 2.2.0 with ffmpeg and force the AAC format) for Raspberry Pi 4 and I get the same sound rattle while it worked perfectly before. So this is not specific to the Windows sound FreeRDP backend.

**Comment by vscfreire** [comment]
@akallabeth Tested with latest master and stable2.0 and the issue is fixed.

**Comment by akallabeth** [comment]
@vscfreire thank you, closing then.
