### ISSUE TITLE
Graphical feedback while trying to reconnect (Linux)

### ISSUE THREAD

**Issue by ricklefe** [FreeRDP/FreeRDP#6495]
**Is your feature request related to a problem? Please describe.**
While automatic reconnect is enabled and the connection aborts, there is no information about the current status. It looks like the session is frozen. 
You can see the reconnect trys in the logs (20 times like in Windows with an interval of 20 seconds)

**Describe the solution you'd like**
Some graphical feedback about the current status 

**Additional context**
freeRDP 2.0 in Linux

**Comment by hardening** [comment]
Interesting issue, a part of the problem is that we don't want to rely on a toolkit, so if we want to show reconnection progress, we will have to write these graphics component ourself.

**Comment by akallabeth** [comment]
implemented for sdl-freerdp, xfreerdp is command line only, so only text output.
