### ISSUE TITLE
Mac mousewheel vertical / horizontal is flipped. Mouse flags are incorrect.

### ISSUE THREAD

**Issue by kjohnstonadept** [FreeRDP/FreeRDP#6502]
I am on OSX Catalina. I noticed the mousewheel was acting very strangely in a windows 10 VM.

The scrollWheel method in MRDPView.mm is using dy for the horizontal mouse and dx for the vertical mouse, which seemed backwards.

After fixing that I noticed that scrolling down was working fine but scrolling up was not. I found this fix for wayland: https://github.com/FreeRDP/FreeRDP/pull/6133.

I applied the same fix to MRDPview.m and it now works as well.

You can see my fix here: https://github.com/FreeRDP/FreeRDP/compare/master...adept-at:master

**Comment by akallabeth** [comment]
@kjohnstonadept thank you for the fix.
I´ve created a pull request.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/pull/6535
