### ISSUE TITLE
Teaking FreeRDP for a developper workstation accross seas?

### ISSUE THREAD

**Issue by ravenlost** [FreeRDP/FreeRDP#6504]
I need to use FreeRDP to connect **overseas** to a windows desktop located in Canada (I live in Belgium). Now, I also need to connect **through an OpenVPN** connection first before using RDP.

Issue I'm having is that I have a lag when moving around on the remote desktop. As a developper, it makes it quite frustrating to do my work.

Here's a video link demo'ing this lag: [https://www.youtube.com/watch?v=cpO26YUF2qg](https://www.youtube.com/watch?v=cpO26YUF2qg)

This is the command I use to connect :

`xfreerdp /u:username /v:192.168.x.x /bpp:8 -grab-keyboard -wallpaper`

I tried various bpp settings and it doesn't seem to change much.

Is there a way I could tweak the RDP connection even more ? I need this just to code in IDEs, manage databases, etc. I **do not need** super high-quality graphics or anything (I won't be playing videos from here ;)). I think 256 colors should be fine, but wondering if they are other compression settings I could use?

While I'll have done everything I can with the RDP, my lan admin is also looking into tweaking the VPN connection...

Thanks a million for your time. Pat

**Comment by akallabeth** [comment]
most of the time `/network:auto` is the best option, but if you can live with `8bpp` colors that might even be smaller.
(usually `/gfx:avc444` is best quality and bandwidth with modern applications due to older RDP transmitting bitmaps whenever no drawing primitive can be used)
