### ISSUE TITLE
Warning, password or account expired

### ISSUE THREAD

**Issue by wrobin68** [FreeRDP/FreeRDP#6510]
Hi,

I'm using think client "IGEL" and I'm connecting to an RDS FARM with different collection on it.
I have one farm runing on 2012r2 and one under 2016. both have the same issue.

I use profile in the UMS that create an RDP shortcut on the desktop of the IGEL.
When I first deploy the profile, the connection work, but when I disconnect I get this error, "Password or Account expired":
libva info: VA-API version 1.5.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /services/hwva/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_5
libva info: va_openDriver() returns 0

If I reboot the IGEL I get an error at the login and I'm not able to connect to the farm anymore, same title name "Password or Account expired" but the body is different : 

[ERROR][com.freerdp.core] - freerdp_set_last_error ERRCONNECT_UNKNOW [0x2007F]
[ERROR][com.freerdp.core.transport] - BIO_read returned a system error 104: Connection reset by peer
[ERROR][com.freerdp.core.nego] - Protocol Security Negotiation Failure
[ERROR][com.freerdp.core.connection] - Error: protocol security negotiation or connection failure
[ERROR][com.freerdp.client.x11] - Server required stronger protocol, than client has selected

What is very stange is that the first time it works... 

Thanks for your time, tell me if you need more information :)

**Comment by akallabeth** [comment]
@wrobin68 well, hard to tell ;)
can you simply try with our nightly builds?
