### ISSUE TITLE
missing return in read_order_field_uint32 (orders.c)

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#6515]
When I build the current master for openSUSE Tumbleweed, I get this error message:
[   58s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/core/orders.c: In function 'read_order_field_uint32':
[   58s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/core/orders.c:1128:1: error: control reaches end of non-void function [-Werror=return-type]
[   58s]  1128 | }
[   58s]       | ^

This function is missing a return at the end.

**Comment by akallabeth** [comment]
@hendwolt thank you (again) for being that thorough. Looks like this slipped though.

**Comment by hendwolt** [comment]
With #6516 the problem is gone.
