### ISSUE TITLE
Application on Internet

### ISSUE THREAD

**Issue by rider8581** [FreeRDP/FreeRDP#6530]
Good day.

While exploring Github, I found this awesome project, 
perfect and easy to use.

Now I wanna use this application on the internet where the remote server doesn't have a public IP address.
I think by setting port forwarding on the server-side and the server port on the client-side, I can resolve this issue.

Could you kindly guide me on how I can do this kind of configuration?

Yeah, this is not the bug of this project and I just wanna extend the feature. Kindly let me know how I can use it for my purpose.

Thank you very much.

**Comment by oezingle** [comment]
You probably want to use a DNS server so you don't lose your public IP constantly. I would also consider using a VPN into your own network for better security

**Comment by akallabeth** [comment]
just like any other service you need a public reachable address (ipv4/ipv6), with ds-lite or provider side NAT you are out of luck. (you may work around that by using a VPN that has a public address)
just as @oezingle suggested, do not expose directly to the internent, use a VPN or ssh tunnel.

**Comment by rider8581** [comment]
Thank you for your comments. 
Could you kindly let me know if I can use port forwarding in NAT?
So I would set port forwarding in the NAT on the server-side and configure the client to access the forwarded port of NAT.
Do you think this kind of approach makes it possible to use this application on the Internet?

**Comment by akallabeth** [comment]
@rider8581 yes, rdp is using TCP over 3389 by default. (FreeRDP does not implement the additional UDP transport)

**Comment by rider8581** [comment]
@akallabeth so I am thinking to set port forwarding for local port 3389 on server-side NAT and configure client to access NAT's IP and forwarded port.
Will it work?
