### ISSUE TITLE
multimon

### ISSUE THREAD

**Issue by wkmdd** [FreeRDP/FreeRDP#6531]
Releated pull request for master: 

Problems in xfreerdp with /multimon

Two screens should be used in the xfreerdp.
A full bid should work on both screens.
The two full screens should be displayed immediately after starting.
A solution approach described below cannot be reasonable for inexperienced users in the long term.

When I use /f there is full screen on Monitor1. The local (extended) desktop is visible on Monitor2.

If I now enter ctrl + alt + enter I have the rdp session on both screens in window mode.
Unfortunately then the taskbar of the RDP server (W2kR2) is barely visible in the height!
In order to access the taskbar to some extent in the RDP session, I have to move the window up as far as possible

push. When working, the window can often be moved unintentionally.

The /dynamic-resolution switch is only effective when using one screen.

How can I achieve my goal?

**Comment by akallabeth** [comment]
I don´t know your problem, but if I start with `xfreerdp /v:<server> /u:<user> /p:<pwd> /multimon` all my monitors are used and the session has the correct layout.
