### ISSUE TITLE
Canadian Multilingual Keyboard not "fully" working on remote ?

### ISSUE THREAD

**Issue by ravenlost** [FreeRDP/FreeRDP#6536]
Hello,

I have a Canadian Multilingual Standard Keyboard Layout. See: [http://charsetplus.tripod.com/Keyboard/Latin/ENFR-CAN.htm](http://charsetplus.tripod.com/Keyboard/Latin/ENFR-CAN.htm).

![Untitled](https://user-images.githubusercontent.com/62449156/97404651-bbfeee00-18f6-11eb-8c6c-e87fd0885c86.png)

I'm running xfreerdp to connect to my works Windows 10 desktop. Problem I'm having is that only 2 keys are swapped with one another: **the slash key (/) is reversed with the ugrave key (ù)**. I've setup my remote windows  desktop to have only the Canadian Multilingual Standard KB. If I use a Windows workstation to connect to it, then the KB is fine. However, from Linux (Manjaro/Arch Linux), the two keys are swapped. 

**Note 2 things:** 

1. I've tried forcing the KB layout with the /kbd option: `"/kbd:Canadian Multilingual Standard"`or `/kbd:0x11009`, but that didn't change a thing.

2. In Linux, I also in the past had the same problem. To fix it, I had to remap the keys like so:
`sudo xmodmap -e "keycode  94 = slash backslash slash backslash bar brokenbar"`
`sudo xmodmap -e "keycode  49 = ugrave Ugrave ugrave Ugrave notsign notsign"`

Outputs from my Linux desktop:
```
[user@host ~]$ localectl
   System Locale: LANG=en_US.UTF-8
       VC Keymap: /usr/local/share/kbd/keymaps/csa.map
      X11 Layout: ca
       X11 Model: pc105
     X11 Variant: multix

[user@host ~]$ setxkbmap -print
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+ca(multix)+inet(evdev)+terminate(ctrl_alt_bksp)"	};
	xkb_geometry  { include "pc(pc105)"	};
``` 

For one thing I never understood why I had to remap with xmodmap in Linux, but that's another thing. 

It seems to me the problem is that it is my **Linux's** keyboard layout that is sent over to my remote windows machine, so kinda like without those xmodmap modifications. I don't know. Is there a way I could tell freerdp to use only what KB layout is installed on the remote host? If not, any suggestions on a fix here? Being a web programmer, that misplaced slash is reaaaaalllly annoying. Surely, I must not be the only one to use a canadian multilingual kb layout with freerdp from Linux ;)

Thanks a million for your time.

Cheers,
Pat

**Comment by akallabeth** [comment]
The issue you experience is a hard to solve one.
1. In RDP there is no keyboard layout, there are only `scancodes` (numbers for each key).
1. From X11 you do not get scancodes, so we need to reverse map the keyboard symbols to scancodes. Any modification on the local keyboard layout will result in the same modification remote (whatever the layout there is)
1. `/kbd:xxxx` only tells the server how to map the scancodes it receives (aka the default keyboard mapping used for the session)

**Comment by ravenlost** [comment]
> The issue you experience is a hard to solve one.
> 
>     1. In RDP there is no keyboard layout, there are only `scancodes` (numbers for each key).
> 
>     2. From X11 you do not get scancodes, so we need to reverse map the keyboard symbols to scancodes. Any modification on the local keyboard layout will result in the same modification remote (whatever the layout there is)
> 
>     3. `/kbd:xxxx` only tells the server how to map the scancodes it receives (aka the default keyboard mapping used for the session)

Euhhh ok. I didn't quite understand what you are saying here.. `I need to reverse map the keyboard symbols to scancodes` ?

**Comment by akallabeth** [comment]
@ravenlost no, that is what freerdp does, it tries to guess the correct scancode from your current keyboard layout.
If you need to remap it locally, it means that this mapping will have the same issue.

**Comment by ravenlost** [comment]
> @ravenlost no, that is what freerdp does, it tries to guess the correct scancode from your current keyboard layout.
> If you need to remap it locally, it means that this mapping will have the same issue.

So there wouldn't be a way to send over those new mappings to rdp? Would my only way to fix this be a remapping of the keys INSIDE my Windows RDP workstation? With a tool like Sharpkeys: https://github.com/randyrants/sharpkeys ?

**Comment by akallabeth** [comment]
that or you recompile freerdp.
check `KEYCODE_TO_VKCODE_EVDEV` and `XKB_KEY_NAME_SCANCODE_TABLE`

**Comment by ravenlost** [comment]
Oh lord...  fully recompiling freerdp ? That would mean I'd need to recompile for every freerdp updates... or the ones I care about at least. I've downloaded the FreeRDP-Master complete repository ZIP file. Looking into it, it isn't the "standard" ./configure && make && make install ? And honestly, I have no clue by what you mean in _"check `KEYCODE_TO_VKCODE_EVDEV` and `XKB_KEY_NAME_SCANCODE_TABLE`"_  .... Environment variables I need to set ?

**Comment by akallabeth** [comment]
@ravenlost yes, it uses `CMake`. Not easy nor really usable for you as it seems. You might have more luck playing around with remapping keys locally, other than that there is no easy fix

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/pull/6537 allows remapping detected scancodes with the ones you desire.
you´ll need to compile from source though, this will take some time until this will land.

**Comment by ravenlost** [comment]
> @ravenlost yes, it uses `CMake`. Not easy nor really usable for you as it seems. You might have more luck playing around with remapping keys locally, other than that there is no easy fix

Awesome !!

**Comment by ravenlost** [comment]
> #6537 allows remapping detected scancodes with the ones you desire.
> you´ll need to compile from source though, this will take some time until this will land.

Awesome !! That was quick fix :))

I've cloned the FreeRDP repository to my local machine and placed myself on kbd_remap branch you've created with the changes. 

I'm not (yet) sure how to recompile it all, with proper options (since I just know a little with regular make (./configure && make), to also be able to install it separately from my current version, normally with --prefix.... Just need to google and learn about cmake now to figure it all out... Will update once I'm able to test it. Thanks a million for your assistance with this :)

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/Compilation
