### ISSUE TITLE
transport_connect_tls:freerdp_set_last_error_ex 

### ISSUE THREAD

**Issue by mbevc1** [FreeRDP/FreeRDP#6544]
**Describe the bug**
After upgrading from F32 to F33 started to receive Error using Remmina connecting to RDP: Check that client and server support common TLS version.

**To Reproduce**
1. F32 + Remmina + freerdp
2. upgrade to F33
3. try to connect to RDP

**Expected behavior**
Successful connection.

**Screenshots**
```
ERROR][com.freerdp.core] - transport_connect_tls:freerdp_set_last_error_ex ERRCONNECT_TLS_CONNECT_FAILED [0x00020008]
```

**Application details**
* FreeRDP version (`xfreerdp /version`): freerdp-libs-2.2.0-4.fc33.x86_64
* OS version connecting to (server side): win7

**Environment (please complete the following information):**
 - OS: Linux Fedora 33
 - Architecture: [amd64, arm]: x86_64

**Comment by akallabeth** [comment]
Sounds like a fedora bug. Check openssl policy.
As you can imagine `2.2.0` did not become a different release since fedora 32

**Comment by mbevc1** [comment]
Hi, thanks for a quick response. Yeah, makes sense. Which policies do you have in mind? Seems `openssl` package was bumped, but I do also have `compat-` installed as well.

**Comment by akallabeth** [comment]
@mbevc1 look at the cipher configuration, maybe they are too strict (and the server you are connecting to requires older ssl)

**Comment by mbevc1** [comment]
Got it, F33 restricted default policy and switching back to `update-crypto-policies --set DEFAULT:FEDORA32` works as win7 seems to be still using TLS 1.0

**Comment by arthusu** [comment]
is solved by adding: `/tls-seclevel:0 /timeout:80000`

**Comment by shahidaliabbasi** [comment]
Here's the solution:
https://youtu.be/lkZ5gs2-x5I?si=fPs3UJijfcdsLt1G

**Comment by renozion** [comment]
> Here's the solution: https://youtu.be/lkZ5gs2-x5I?si=fPs3UJijfcdsLt1G

Thank u sir!

**Comment by jarkko-hautakorpi** [comment]
Seems like also /etc/gnutls/config has an effect, in 24.04 it has:
disabled-version = tls1.0
disabled-version = tls1.1
disabled-version = dtls0.9
disabled-version = dtls1.0
removing these can get you in some servers and then the /tls-seclevel:0 parameter in KRDC can get u to those TLS1.0 servers.
