### ISSUE TITLE
rdpsnd Mac prevents sleep

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#6547]
The rdpsnd_mac channel currently prevents Macs from entering sleep mode once a sound has been played at least once.
This behavior can be observed by following these steps:
* Open Activity Monitor
* Switch to the "Energy" tab
* Launch an RDP session using FreeRDP with audio redirection enabled
* Check Activity Monitor's "Preventing Sleep" column
* If no audio has been played yet, it should say "No"
* Now play any sound in the RDP session
* "Preventing Sleep" now switches to "Yes" in Activity Monitor
* Wait for the audio to finish playing
* Unfortunately, from now on, sleep is prevented for the rest of the RDP session, no matter if audio continues to play or not

I guess to fix this, the `AVAudioEngine` probably needs to be stopped once audio playback is finished, and resumed once the next audio playback session starts. This is just a guess though as I haven't yet had the time to verify this.

**Comment by dbaileyut** [comment]
Hi I feel like this is a security issue because it unexpectedly prevents the screensaver from activating and therefore the Mac never locks due to an idle timeout. The Microsoft Remote Desktop client does not exhibit this behavior.
