### ISSUE TITLE
Mac Client lacking connection UI

### ISSUE THREAD

**Issue by shh230** [FreeRDP/FreeRDP#6553]
Releated pull request for master: 

![crash](https://user-images.githubusercontent.com/38716757/98344548-5de8ae00-204e-11eb-8015-db3e0a992ea9.gif)

Compiled on mac, click to run, it will crash.

**Comment by shh230** [comment]
![crash](https://user-images.githubusercontent.com/38716757/98344548-5de8ae00-204e-11eb-8015-db3e0a992ea9.gif)

Compiled on mac, click to run, it will crash.

**Comment by akallabeth** [comment]
the client is intended for scripting or opening with file association.
There is no direct UI for it.
Pull requests to change that welcome.

**Comment by shh230** [comment]
Do I need to configure anything in the remote computer via the command line? Are there relevant documents?
```
xfreerdp -f host:port -u username -p password 
```
