### ISSUE TITLE
Mac: monitor-list returns just one monitor

### ISSUE THREAD

**Issue by sleepless** [FreeRDP/FreeRDP#6559]
I have a multi-monitor setup with three monitors. The resolution of two of them is 1920 x 1200 and one is 3840 × 2160. 

Strangely enough monitor-list gives me the following output: 

`xfreerdp /monitor-list
        [0] 6400x1418	+0+0`

When I disable scaling on the 4K monitor, the output changes to:

`[0] 5760x1178	+0+0`

Version is 2.2.0. OS is Mac. Installed with homebrew.

Any idea what the issue could be?

**Comment by akallabeth** [comment]
yes, mac os.
`xfreerdp` is a X11 application and what you see is what mac os reports.
