### ISSUE TITLE
Connection failed

### ISSUE THREAD

**Issue by shh230** [FreeRDP/FreeRDP#6564]
vnc started connecting
vnc connecting to 127.0.0.1 5900
vnc tcp connected
vnc security level is 0 (1 = none 2 = standard)
vnc error - problem connecting
some problem

![image](https://user-images.githubusercontent.com/38716757/98656264-72dd7e00-237b-11eb-98b7-1aeb352f511b.png)

**Comment by akallabeth** [comment]
this is FreeRDP, not xrdp ;)
see https://github.com/neutrinolabs/xrdp
