### ISSUE TITLE
Tap and hold with touch screen takes too long before right click triggered

### ISSUE THREAD

**Issue by shady2k** [FreeRDP/FreeRDP#6566]
**Describe the bug**

Tap and hold with multitouch flag and touch screen takes about 4 seconds before right click triggered. In version 2.0.0-dev5 (2693389a+debian) tap and hold works as expected.

**To Reproduce**
1. Tap with touchscreen and hold
2. Circle appeared
3. After 4 seconds rectangle appears
4. Release finger
5 Context menu opened

**Expected behavior**
Context menu opened after holding finger < 1 second

**Application details**
* FreeRDP version (`xfreerdp /version`): 2.2.0
* Command line used: xfreerdp /v:192.168.0.xx /u:xxx /p:xxx +multitouch /f
* Output of `xfreerdp /buildconfig`:
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=ON WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NEON=ON WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 8.3.0
Target architecture: ARM
* OS version connecting to (server side): Windows 10
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Linux raspberrypi 5.4.72-v7+ #1356 SMP Thu Oct 22 13:56:54 BST 2020 armv7l GNU/Linux
 - Architecture: [amd64, arm]: arm

**Comment by shady2k** [comment]
After some tests: version with commit  1 Feb 2019 2693389a103394e035edc2a01055ca2c9ccccb21 works perfectly and version with commit 5ab2bed8749747b8e4b2ed431fd102bc726be684 (release 2.0.0) doesn't work anymore as well as the latest one.

**Comment by akallabeth** [comment]
@shady2k thank you for debugging, I´ve created https://github.com/akallabeth/FreeRDP/tree/rdpei_fix and cleaned up a bit.
Does that improve the situation or is it still not working properly?

**Comment by shady2k** [comment]
> @shady2k thank you for debugging, I´ve created https://github.com/akallabeth/FreeRDP/tree/rdpei_fix and cleaned up a bit.
> Does that improve the situation or is it still not working properly?

Thanks for your reply. I build this version and it does not work too. After some explorations, I've found that problem in commit at 18 Dec 2019: 947645520d6fb387df7d799d76c0246b0c2cfaf7
Commit at 17 Dec 2019: d044915a7e7163cdfc83fd8489ce336c1327bc2d still works.

**Comment by shady2k** [comment]
I was simply copied files channels/rdpei/client/rdpei_main.c and include/freerdp/client/rdpei.h from commit 17 Dec 2019 (d044915a7e7163cdfc83fd8489ce336c1327bc2d) to release 2.2.0 (d2ba84a6885f57674098fe8e76c5f99d880e580d) and it works!

**Comment by akallabeth** [comment]
@shady2k updated the pr, does it work for you now?

**Comment by shady2k** [comment]
> @shady2k updated the pr, does it work for you now?

I've got segfault:
[15:20:21:146] [5467:5468] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[15:20:21:355] [5467:5468] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[15:20:21:355] [5467:5468] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpei
[15:20:21:377] [5467:5476] [ERROR][com.freerdp.utils] - Caught signal 'Ошибка сегментирования' [11]

**Comment by akallabeth** [comment]
@shady2k sorry, did not push all changes. pushed these now and it is running. (can´t properly test multitouch, do not have a device setup)

**Comment by shady2k** [comment]
> @shady2k sorry, did not push all changes. pushed these now and it is running. (can´t properly test multitouch, do not have a device setup)

Yes, it finally worked! Thank you! Can you make changes for stable release 2.2.0?

**Comment by akallabeth** [comment]
@shady2k thank you for the feedback. as for stable backports, most likely not (breaks the abi)
