### ISSUE TITLE
winpr_HexLogDump does not print when compiled using VS 2013

### ISSUE THREAD

**Issue by lazyruss** [FreeRDP/FreeRDP#6567]
**Describe the bug**
I've compiled latest sources (as of Nov 10, 2020) using VS 2013 with almost all debugging enabled.
however when i execute wfreerdp, there are no buffer dumps printed

**To Reproduce**
wfreerdp /v:target /log-level:trace > trace.log
connect, login, exit
check trace.log - there are no buffer dumps whatsoever

**Expected behavior**
when wfreerdp compiled by VS 2019, buffers are printed.

**Application details**
I've attached debugger and it seems that TrioParseQualifiers is failing to parse formats, usually ending at 
case QUALIFIER_FIXED_SIZE:
...
  return TRIO_ERROR_RETURN(TRIO_EINVAL, offset);

apparently format definitions such as 
#define PRIuz		"Iu"
are not compatible with trio.c

**Comment by akallabeth** [comment]
@lazyruss I´d update the compiler to something that is `C99` compilant.
Of course, if you are at it pull requests are welcome ;)

**Comment by lazyruss** [comment]
@akallabeth its not vs version actually, its platform toolset. im forced to use v120 for compatibility reasons.
BTW, night builds from https://ci.freerdp.com/job/freerdp-nightly-windows exhibit same behavior.

**Comment by akallabeth** [comment]
@lazyruss I do understand. But this is a compiler/toolchain bug and the fallback library does not support that, so you´re back to square 1.
