### ISSUE TITLE
Install xfreerdp 

### ISSUE THREAD

**Issue by wkmdd** [FreeRDP/FreeRDP#6579]
Hello Forum,

I installed version 2.2.0 from the package manager with xfreerdp, under
FossaPupp64 problems. The main problem is the multimon support. These
Problems should be solved under the development version 3.0-dev.

I downloaded the binary package for this:
https://ci.freerdp.com/job/freerdp-nightly-source/880/label=pkg-deb/

Does anyone manage to get this to work under FossaPupp64? If so can
someone give me a detailed description of what to do.

Unfortunately, my knowledge is not sufficient.

Thank you.
Siegfried

**Comment by akallabeth** [comment]
@wkmdd is this ubuntu based? from the description it sounds like it, follow the `deb http://...` line for ubuntu and check `/opt` for installed binaries.
