### ISSUE TITLE
Freerdp with guacamole 1.2.0 audio mic redirection problem

### ISSUE THREAD

**Issue by Merlyno979** [FreeRDP/FreeRDP#6581]
Hi.
I have a problem with freerdp audio mic redirection.
I installed guacamole 1.2.0 on CentOS 8 with this guide:
https://www.byteprotips.com/?p=2486

But I have releved 1 problem with microphone redirection:

In my case the mic redirection work, but the audio is very bad.
I'm read this post: https://github.com/FreeRDP/FreeRDP/issues/4779
The case is similar: I'm no use a Mac but I have a Windows10  for connect to a page of guacamole, and the remote machine used from freerdp is a vitual macchine.

In the post: https://github.com/FreeRDP/FreeRDP/issues/4779 the resolution was the "commented on 1 Aug 2018":  Try enabling the FFMPEG backend, then it will work. (WITH_DSP_FFMPEG=ON).
I understand out what to do but I don't know how to do it
Unfortunatly i do not know how to do, and not find a guide for this change.

The pachet and OS version ar:
freerdp.x86_64                      2:2.0.0-46.rc4.el8_2.2
Guacamole is version 1.2.0
OS is CentOS Linux release 8.2.2004 (Core)

Can you help my please?

**Comment by akallabeth** [comment]
@Merlyno979 check your freerdp buildflags (`/xfreerdp /buildflags`) to check how freerdp was compiled.

**Comment by Merlyno979** [comment]
I ave installed CentOS 8 core (no have installed gui is superflous).

If i run de command "xfreerdp /buildflags" with root user I have this result:

# xfreerdp /buildflags
[10:08:50:984] [1529:1529] [ERROR][com.freerdp.client.x11] - failed to open display:
[10:08:50:984] [1529:1529] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.

And if i run the list of pachet "freerdp" installed on the system:
dnf list installed | grep freerdp
freerdp.x86_64                      2:2.0.0-46.rc4.el8_2.2                  @AppStream
freerdp-devel.x86_64                2:2.0.0-46.rc4.el8_2.2                  @PowerTools
freerdp-libs.x86_64                 2:2.0.0-46.rc4.el8_2.2                  @AppStream

Have you a suggest for have a guild flag of xfreerdp?

Yes, i think that the problem are a codify thet xfreerdp apply to microphone packet, but i don't know change the flag for freerdp build.

I'm installed freerdp witch a simple "dnf install freerdp -y", I didn't do anything else

**Comment by akallabeth** [comment]
@Merlyno979 please NEVER run freerdp as root, you will always get issues like this, run as normal user and report the flags please.

**Comment by Merlyno979** [comment]
Ok.
I create another user with my name (isn't root), but the result is the same:

[vincenzo@GUACAMOLE ~]$ xfreerdp /buildflags
[10:59:07:652] [1765:1765] [ERROR][com.freerdp.client.x11] - failed to open display:
[10:59:07:652] [1765:1765] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.

i' not installed a gui on CentOS8, i use the core only.
I don't know if the problem for a command "xfreerdp /buildflags" is also this.

**Comment by akallabeth** [comment]
@Merlyno979 so you can not run any `X11` program? this is what the error message tells.

**Comment by Merlyno979** [comment]
No, i can't.
The e system isn't dotate of X11.
freerdp is used form guacamole only.

**Comment by Merlyno979** [comment]
Sorry, my english is bad... :-)
The sentence correct is:
freerdp is used only throught guacamole.

**Comment by Merlyno979** [comment]
How can I modify freerdp for resolv the mic redirection garantly a good audio?

**Comment by akallabeth** [comment]
@Merlyno979 compile your own version, preferrably with `FFMPEG` as audio backend.

**Comment by Merlyno979** [comment]
@akallabeth the problem is that I do not know how to do.
I'm follow this post for try to compile: https://jira.glyptodon.com/browse/GUAC-1112
but not have the flag actually used in freerdp download from dnf.
You have a idea for extrapolated that parameters in another way and not with the command "xfreerdp /buildflags"?

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki

**Comment by Merlyno979** [comment]
Follow your link..
You think that this section can help me tray to compile freerdp?
https://github.com/FreeRDP/FreeRDP/wiki/Compilation

**Comment by Merlyno979** [comment]
Ok, today I'm compiled a first version, but not work.
No problem, i'm happy dhe same! :-D
I was wrong compile the parameters with cmake.

the paramethers used of me are:
cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SSE2=ON -DWITH_PULSE=ON -DWITH_CUPS=on -DWITH_WAYLAND=off -DCMAKE_INSTALL_LIBDIR=/usr/lib64 -DCMAKE_INSTALL_PREFIX:PATH=/opt -DWITH_OPENH264=OFF -DWITH_X264=OFF -DWITH_FFMPEG=ON

In version installed from EPEL repository of CentOS8 I was just having trouble with the microphone.
That configuration was good, but the quality of mic redirection was very bad.
I whant use that same paramethers... I whant only add ffmpeg support, but i'm not have the build flag used for that pachet.
Can you halp me for this?

**Comment by Merlyno979** [comment]
Today i have used this parameters:

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_LIBDIR=/usr/lib64 -DCMAKE_INSTALL_PREFIX:PATH=/opt -DWITH_OPENH264=OFF -DWITH_X264=OFF -DWITH_DEBUG_ALL=OFF -DWITH_DEBUG_CAPABILITIES=OFF -DWITH_DEBUG_CERTIFICATE=OFF -DWITH_DEBUG_CHANNELS=OFF -DWITH_DEBUG_CLIPRDR=OFF -DWITH_DEBUG_DVC=OFF -DWITH_DEBUG_KBD=OFF -DWITH_DEBUG_LICENSE=OFF -DWITH_DEBUG_MUTEX=OFF -DWITH_DEBUG_NEGO=OFF -DWITH_DEBUG_NLA=OFF -DWITH_DEBUG_NTLM=OFF -DWITH_DEBUG_RAIL=OFF -DWITH_DEBUG_RDP=OFF -DWITH_DEBUG_RDPDR=OFF -DWITH_DEBUG_RDPEI=OFF -DWITH_DEBUG_REDIR=OFF -DWITH_DEBUG_RFX=OFF -DWITH_DEBUG_RINGBUFFER=OFF -DWITH_DEBUG_SCARD=OFF -DWITH_DEBUG_SND=OFF -DWITH_DEBUG_SVC=OFF -DWITH_DEBUG_SYMBOLS=OFF -DWITH_DEBUG_THREADS=OFF -DWITH_DEBUG_TIMEZONE=OFF -DWITH_DEBUG_TRANSPORT=OFF -DWITH_DEBUG_TSG=OFF -DWITH_DEBUG_TSMF=OFF -DWITH_DEBUG_WND=OFF -DWITH_DEBUG_XV=OFF -DWITH_DIRECTFB=OFF -DWITH_CCACHE=ON -DWITH_CHANNELS=ON -DWITH_CLIENT=ON -DWITH_CLIENT_AVAILABLE=1 -DWITH_CLIENT_CHANNELS=ON -DWITH_CLIENT_CHANNELS_AVAILABLE=1 -DWITH_CLIENT_COMMON=ON -DWITH_CLIENT_INTERFACE=OFF -DWITH_CUPS=ON -DWITH_EVENTFD_READ_WRITE=1 -DWITH_DSP_FFMPEG=ON -DWITH_FFMPEG=ON -DWITH_GPROF=OFF -DWITH_GSM=OFF -DWITH_GSSAPI=OFF -DWITH_GSTREAMER_0_10=ON -DWITH_GSTREAMER_1_0=ON -DWITH_ICU=OFF -DWITH_IPP=OFF -DWITH_JPEG=ON -DWITH_LIBRARY_VERSIONING=ON -DWITH_LIBSYSTEMD=OFF -DWITH_MACAUDIO=OFF -DWITH_MACAUDIO=OFF -DWITH_MACAUDIO_AVAILABLE=0 -DWITH_MANPAGES=ON -DWITH_MBEDTLS=OFF -DWITH_OPENH264=OFF -DWITH_OPENSLES=OFF -DWITH_OPENSSL=ON -DWITH_OSS=ON -DWITH_PAM=ON -DWITH_PCSC=ON -DWITH_PROFILER=OFF -DWITH_PULSE=ON -DWITH_SAMPLE=OFF -DWITH_SANITIZE_ADDRESS=ON -DWITH_SANITIZE_ADDRESS_AVAILABLE=1 -DWITH_SANITIZE_LEAK=OFF -DWITH_SANITIZE_LEAK=OFF -DWITH_SANITIZE_LEAK_AVAILABLE=0 -DWITH_SERVER=ON -DWITH_SERVER_CHANNELS=ON -DWITH_SERVER_INTERFACE=ON -DWITH_SMARTCARD_INSPECT=OFF -DWITH_SSE2=ON -DWITH_THIRD_PARTY=OFF -DWITH_VALGRIND_MEMCHECK=OFF -DWITH_VALGRIND_MEMCHECK=OFF -DWITH_VALGRIND_MEMCHECK_AVAILABLE=0 -DWITH_WAYLAND=OFF -DWITH_X264=OFF -DWITH_ZLIB=ON -DHAVE_AIO_H=1 -DHAVE_EXECINFO_H=1 -DHAVE_FCNTL_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_MATH_C99_LONG_DOUBLE=1 -DHAVE_POLL_H=1 -DHAVE_PTHREAD_MUTEX_TIMEDLOCK=ON -DHAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 -DHAVE_SYSLOG_H=1 -DHAVE_SYS_EVENTFD_H=1 -DHAVE_SYS_SELECT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_XI_TOUCH_CLASS=1

I have this error in compilation, but a don't understand why:

Scanning dependencies of target freerdp-shadow-subsystem
[ 96%] Building C object server/shadow/CMakeFiles/freerdp-shadow-subsystem.dir/shadow_subsystem_builtin.c.o
[ 96%] Building C object server/shadow/CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o
/root/freerdp/server/shadow/X11/x11_shadow.c: In function ‘x11_shadow_query_cursor’:
/root/freerdp/server/shadow/X11/x11_shadow.c:492:23: warning: unused variable ‘k’ [-Wunused-variable]
  int x = 0, y = 0, n, k;
                       ^
/root/freerdp/server/shadow/X11/x11_shadow.c:492:20: warning: unused variable ‘n’ [-Wunused-variable]
  int x = 0, y = 0, n, k;
                    ^
/root/freerdp/server/shadow/X11/x11_shadow.c: In function ‘x11_shadow_screen_grab’:
/root/freerdp/server/shadow/X11/x11_shadow.c:792:22: error: ‘x11ShadowSubsystem’ {aka ‘struct x11_shadow_subsystem’} has no member named ‘xshm_gc’
             subsystem->xshm_gc, 0, 0, subsystem->width, subsystem->height, 0, 0);
                      ^~
/root/freerdp/server/shadow/X11/x11_shadow.c: In function ‘x11_shadow_xshm_init’:
/root/freerdp/server/shadow/X11/x11_shadow.c:1132:11: error: ‘x11ShadowSubsystem’ {aka ‘struct x11_shadow_subsystem’} has no member named ‘xshm_gc’
  subsystem->xshm_gc = XCreateGC(subsystem->display, subsystem->root_window,
           ^~
/root/freerdp/server/shadow/X11/x11_shadow.c:1134:44: error: ‘x11ShadowSubsystem’ {aka ‘struct x11_shadow_subsystem’} has no member named ‘xshm_gc’
  XSetFunction(subsystem->display, subsystem->xshm_gc, GXcopy);
                                            ^~
At top level:
/root/freerdp/server/shadow/X11/x11_shadow.c:614:12: warning: ‘x11_shadow_blend_cursor’ defined but not used [-Wunused-function]
 static int x11_shadow_blend_cursor(x11ShadowSubsystem* subsystem)
            ^~~~~~~~~~~~~~~~~~~~~~~
/root/freerdp/server/shadow/X11/x11_shadow.c:594:13: warning: ‘x11_shadow_validate_region’ defined but not used [-Wunused-function]
 static void x11_shadow_validate_region(x11ShadowSubsystem* subsystem, int x, int y, int width,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/freerdp/server/shadow/X11/x11_shadow.c:461:12: warning: ‘x11_shadow_pointer_alpha_update’ defined but not used [-Wunused-function]
 static int x11_shadow_pointer_alpha_update(x11ShadowSubsystem* subsystem)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [server/shadow/CMakeFiles/freerdp-shadow-subsystem.dir/build.make:76: server/shadow/CMakeFiles/freerdp-shadow-subsystem.dir/X11/x11_shadow.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4714: server/shadow/CMakeFiles/freerdp-shadow-subsystem.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by Merlyno979** [comment]
Mmmmmm... i finded something...
If i use any softphone: skype, x-lite, MicroSIP or other throught guacamole, the audio mic is very bad...
But if recording the audio mic with "windows recorder", on the remote PC used from guacamole, the audio is good.
I don't know why this happens.

P.S. Isn't a problem network why remote PC and guacamole are in the same LAN segment and firewall is disables on guacamole and to remote machine.

**Comment by Merlyno979** [comment]
I find this problem with "myjimmy" repository:

https://github.com/apache/guacamole-server/pull/312#issuecomment-723833894&#010

I have create an packet for reduce the time for resolv: 
https://github.com/Merlyno979/GUACAMOLE_MicRedirect_FIX

Tks "akallabeth" ;-)

**Comment by akallabeth** [comment]
@Merlyno979 ah, ok, good to know there is a solution :)
