### ISSUE TITLE
Segmentation Fault when connection to a 2008R2 Session Broker 

### ISSUE THREAD

**Issue by gersondiesel** [FreeRDP/FreeRDP#659]
When I connect to a Remote Desktop in a 2008R2 session broker, if I am redirected to another server, a SEGFAULT occurs.

Freerdp version: 1.0.1 

I read Issue #412 and applied this patch:
https://github.com/FreeRDP/FreeRDP/commit/aa7b83ff1e97ac394f76b0968acc1d9f55a11d41 
but doesnt work.

I also download the last source code from github (clone), and segfault continue.

I use Round Robin DNS and IP redirect in session broker.

user@computer:/mnt$ /usr/local/bin/xfreerdp -a 24 -u user -d domain --ignore-certificate --no-nla --plugin rdpsnd --data alsa -- server & 
[1] 20472
ruser@computer:/mnt$ loading plugin rdpsnd
connected to server:3389
connected to server:3389
connected to <ip>:3389
connected to <ip>:3389
WARNING: invalid packet signature
Warning fastpath_recv_update (225): unknown updateCode 0xD
WARNING: invalid packet signature
WARNING: invalid packet signature
WARNING: invalid packet signature
Warning fastpath_recv_update (225): unknown updateCode 0x7
WARNING: invalid packet signature
Warning update_recv_surfcmds (100): unknown cmdType 0xDAC8
WARNING: invalid packet signature
WARNING: invalid packet signature
WARNING: invalid packet signature
WARNING: invalid packet signature
WARNING: invalid packet signature
WARNING: invalid packet signature
WARNING: invalid packet signature

[1]+  Falha de segmentação  /usr/local/bin/xfreerdp -a 24 -u user -d domain --ignore-certificate --no-nla --plugin rdpsnd --data alsa -- server

**Comment by akallabeth** [comment]
closing due to being ancient
