### ISSUE TITLE
Building with DWITH_VAAPI=ON causes Segmentation Fault when attempting to connect to VM

### ISSUE THREAD

**Issue by splabo** [FreeRDP/FreeRDP#6603]
**Describe the bug**
On Arch linux, when building freerdp and using the build option DWITH_VAAPI=ON, a Segmentation Fault is returned and I am unable to connect to a VM.

**To Reproduce**
1. Build freerdp with DWITH_VAAPI=ON, 
2. Connect to a VM
3. xfreerdp does not connect and returns "Segmentation Fault"

**Expected behavior**
Connect to the VM without any errors

**Application details**
- Version of FreeRDP: FreeRDP version 2.2.0 (af52503)
- Command line used: `xfreerdp /d:$localdomain /u:$user /v:$host /size:1280x720 /clipboard`
- Output of `xfreerdp /buildconfig`:
`Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=ON WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 10.2.0
Target architecture: x64`
- OS version connecting to (server side): Windows Server 2012 R2
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`:
`[12:11:52:046] [198931:198964] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[12:11:52:046] [198931:198964] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[12:11:52:046] [198931:198964] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[12:11:52:046] [198931:198964] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
[12:11:52:046] [198931:198964] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[12:11:52:047] [198931:198964] [INFO][com.freerdp.client.x11] - Property 346 does not exist
[12:11:52:049] [198931:198964] [DEBUG][com.freerdp.primitives] - primitives benchmark result:
[12:11:52:211] [198931:198964] [DEBUG][com.freerdp.primitives] -  * generic= 36
[12:11:52:362] [198931:198964] [DEBUG][com.freerdp.primitives] -  * optimized= 110
[12:11:52:362] [198931:198964] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
[12:11:52:363] [198931:198964] [INFO][com.freerdp.utils] - Caught signal 'Segmentation fault' [11]
Segmentation fault (core dumped)`

**Environment (please complete the following information):**
 - OS: Arch
 - Version/Distribution: 5.9.10-arch1-1
 - Architecture: [amd64, arm]: amd64

**Additional context**
I am building from Arch, everything works fine using freerdp-2:2.2.0-1 (PKGBUILD does not contain WITH_VAAPI=ON, see changes between versions here: https://github.com/archlinux/svntogit-community/commit/e00804fc2904c7e7c33be0e067133b46dbf1d252). I am not sure if I am missing a driver, I have an NVIDIA 1080 using proprietary drivers v455.38.

**Comment by akallabeth** [comment]
VAAPI is disabled by default for a reason.
You need a very specific setup that it will work (did not write this and don´t have the requirements at hand) and will fail horribly for a number of reasons (including resolutions not supported by hardware backend)

**Comment by splabo** [comment]
Thanks, I did not know it was disabled by default. For some reason on the Arch repo it is enabled by default causing my issue. Would you have any information on what the requirements are for VAAPI?

**Comment by akallabeth** [comment]
@splabo sorry, no. It was integrated for some thin-client setup that did have drivers and hardware readily available, but I don´t know what is required for generic use. That is most likely quite a time consuming job testing all possible hardware combinations ;)
Specifically if the resolutions supported may vary (think multimonitor setups, dynamic resolution changes, ...) that are not required for specific kiosk setups.

**Comment by splabo** [comment]
OK thank you for the information @akallabeth I will close this ticket and just compile freerdp without vaapi. thanks!
