### ISSUE TITLE
RDP Session pause/resume

### ISSUE THREAD

**Issue by xsumirx** [FreeRDP/FreeRDP#6615]
Hi All,

We been using FreeRDP for quite a long time in one of our product and its been going quite well. Now there has been a new requirement emerged which requires the FreeRDP to pause and resume the session.

What I mean by pausing and resuming the rdp session is that, the session should freeze on the server side whenever the pause command is issued. Freezing the session should essentially brings the cpu usage by that session at server end down to zero and everything should return to normal as soon as the server receives the resume command.

When the server will freeze, the network bandwidth would go down close to zero i.e, No Video/Audio stream transmitted from server to client, few heartbeat signal is fine to keep the session alive and that is our end goal.

Can anyone suggest if there is something like this already available in rdp spec which fulfils our requirement ? If not, what approach should we take to achieve the requirement ?

Any suggestions is helpful and welcomed.

**Comment by akallabeth** [comment]
there is the `suppress_output_pdu` which is already used when freerdp is minimized.

**Comment by xsumirx** [comment]
> there is the `suppress_output_pdu` which is already used when freerdp is minimized.

Thanks for sharing this very useful information. 

Just to clarify, will this stop all the updates like ( audio, various channel updates) or just the video updates from the server ?

Because our requirement is to pause every possible update from server.

**Comment by akallabeth** [comment]
depends a lot on the server, but mostly only video.
for everything else you need to disconnect and reconnect to the same session
