### ISSUE TITLE
[backport] remove unwanted log level set to debug in rfx 

### ISSUE THREAD

**Issue by Fantu** [FreeRDP/FreeRDP#6616]
Releated pull request for master: https://github.com/FreeRDP/FreeRDP/commit/a2308507aa7f6e086e7c21e4f81d599dbb4b73d6

already tested with 2.2: http://debomatic-armhf.debian.net/distribution#buster-backports/freerdp2/2.2.0+dfsg1-1~bpo10+1.1

**Comment by akallabeth** [comment]
#6432

**Comment by Fantu** [comment]
@akallabeth  I not tested only build but I'm using the build done with it and I already verified that solves the issue and I not found regression. (I saw the "fixed-waiting-test")

**Comment by akallabeth** [comment]
@Fantu that is the label we use for any issue that has a fix that was not merged ;)
