### ISSUE TITLE
Support remote application mouse position manipulation

### ISSUE THREAD

**Issue by bugspencor** [FreeRDP/FreeRDP#6635]
We have an application which manipulates the mouse pointer position in some cases (i.e. mouse pointer position is shifted). This manipulation does not work when the application is run over an FreeRDP session.

I'm not sure if this is intentional behavior (applications should not be allowed to manipulate the mouse position) or unintentional.

I checked with Windows 10 RDP client; the mouse pointer position is changed in that case.

Remote OS is Windows 10. Local OS is Ubuntu 20.04, Xorg, FreeRDP 2.2.0

The application can be downloaded here: http://download.synedra.com:8080/clientupdate/ViewPersonal?platform=win64&download=true
(it's free for personal/non-commercial/non-medical use)

Steps to reproduce:
- Open an image-file and double-click to load it in the viewer
- In the viewing area click close to the right border of the window to open the context menu
-> the mouse pointer should be shifted to the left to not interfere with the menu; but that does not happen with xfreerdp

I increased debug level to trace and could not find any hints to that action being received/processed.

**Describe the solution you'd like**
Several solutions would be possible:
- Always support and allow mouse position manipulation
- Make it configurable, either allow or deny by default

**Describe alternatives you've considered**

**Additional context**

**Comment by akallabeth** [comment]
No, the position can be modified, check `xf_Pointer_SetPosition`
Might be some issue with RAILS and wrong window handle, so if you can add some debug output and check what fails.

**Comment by akallabeth** [comment]
I´ve found a possible issue, check https://github.com/akallabeth/FreeRDP/tree/rail_pointer_set and test with that version. It is taking the correct window handle (for normal and rails operation) to manipulate the pointer, that might be the cause.

**Comment by bugspencor** [comment]
Thanks for looking into that so quickly! It might take some time for me to setup and compile from source. I will report when I have results.

**Comment by bugspencor** [comment]
I managed to configure (*), compile and run from your branch but the issue still persists.

What debug info could help to troubleshoot that, and how can I get the debug info?

(*) $ cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=OFF -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON .

**Comment by akallabeth** [comment]
@bugspencor ok. I´ve updated the branch with additional logging.
I also reread the docs https://tronche.com/gui/x/xlib/input/XWarpPointer.html and there is one issue that could happen:
The pointer can only be moved within the current window, not to another one (by design) and we will not be able to change that.

**Comment by bugspencor** [comment]
With the additional log messages I now see messages of that type when performing the action which triggers the mouse position manipulation:

`[10:47:16:847] [130552:130553] [WARN][com.freerdp.client.x11] - xf_Pointer_SetPosition: focus 0, handle92274689`

**Comment by akallabeth** [comment]
ok, then we have the culprit.
I´ve removed the focus check, that might fix your use case.
In case it does, pleas tell, then we can find a proper fix that works for all cases.

**Comment by bugspencor** [comment]
Great! That works; mouse position is shifted and the warning message is not logged anymore. I also tested another part of the program with setting pointer position; that works, too.

I will continue testing this version to see if there are any side effects and report results.

Thank you very much @akallabeth in the meantime!

**Comment by bugspencor** [comment]
After three days of work-from-home, the changes look good. I had some occasional errors (connection errors at the start of the session; one or two random segfaults); but I guess they are not related to the fixes.

And the reported issue is fixed as well for all cases I've found. Thanks again!

**Comment by akallabeth** [comment]
@bugspencor sorry, segfaults are never ok! please add some debug information (maybe build with debug symbols and WITH_SANITIZE_ADDRESS=ON) to get some more details.

**Comment by bugspencor** [comment]
I can try that. Can you tell me how to build with debug symbols? Also, what to do when a segfault occurs? (I did not find core-files from the previous segfault(s); maybe swallowed by Ubuntu?)

**Comment by bugspencor** [comment]
After approx. 50 hours of use I did not see any more segfaults occuring.
