### ISSUE TITLE
MS Word artifacts with window decorations and virtual desktops

### ISSUE THREAD

**Issue by arkenoi** [FreeRDP/FreeRDP#6640]
**Describe the bug**

When I run MS Word via freerdp, I get weird window frames that persist over virtual desktops.

**To Reproduce**

rdp to a windows wm from Linux VM on Qubes OS
run MS Word
watch this happening!

**Expected behavior**

"Normal" word window

**Screenshots**

![telegram-cloud-photo-size-4-5931390080075805761-y](https://user-images.githubusercontent.com/6000406/101194534-cb482880-3666-11eb-956a-48de3b7a572b.jpg)

**Application details**
* FreeRDP version (`xfreerdp /version`)

2.2.0

* Command line used

+auto-reconnect +clipboard +home-drive -wallpaper /scale:100 /dynamic-resolution /span /app:explorer.exe
also tried -decorations +aero and /gdi:sw

* Output of `xfreerdp /buildconfig`

This is FreeRDP version 2.2.0 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SHADOW_MAC=ON WITH_SHADOW_X11=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=ON WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 10.1.1
Target architecture: x64

* OS version connecting to (server side)

Win7 ESU

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]

Qubes OS

 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]

Qubes OS 4.0
xen4.8
dom0 kernel 5.8.16-1
guest VM fedora 32

 - Architecture: [amd64, arm]:

amd64

**Comment by akallabeth** [comment]
There are some (known) glitches with remote apps, but using `/rfx /gfx:avc444 /network:auto` can improve the situation.

**Comment by arkenoi** [comment]
Apparently, /gfx:avc444 is not available on my system. Other two options have no effect :(

**Comment by marmarek** [comment]
A bit of context why it's specifically visible on Qubes OS: Any window created by an application gets forced colorful border (signifying its origin). For normal windows, this is just window-manager created decoration. But windows with override-redirect flag set, by design, are not managed by window manager and thus Qubes draws colorful border there manually. Apparently MS Word uses something that makes FreeRDP to show an extra window frame built from thin windows with override-redirect flag set.

In non-Qubes case, those windows probably blends into the actual window frame, but in Qubes they are very much visible and quite annoying. Furthermore, windows with override-redirect flag are immune to workspace switch (they remain always visible). I'm not sure how it would work on non-Qubes, but on Qubes FreeRDP have no direct way to know when workspace switch occurs.

**Comment by akallabeth** [comment]
@marmarek thank you for the context.
Then `RAILS` (remote applications mode) will not (correctly) work at all with `xfreerdp`.
The way this mode works is that a local window (without any borders) is created and everything (mouse events, state, window borders, position, size ...) is managed server side. 
There is some (fragile) logic gluing this together and with such extra borders it is nearly impossible to implement without side effects.
Better use a normal desktop session in that case, that will result in less headache.

**Comment by DemiMarie** [comment]
> @marmarek thank you for the context.
> Then `RAILS` (remote applications mode) will not (correctly) work at all with `xfreerdp`.
> The way this mode works is that a local window (without any borders) is created and everything (mouse events, state, window borders, position, size ...) is managed server side.
> There is some (fragile) logic gluing this together and with such extra borders it is nearly impossible to implement without side effects.

Is that window a child window?  I have a patch for the GUI daemon that skips drawing the border for child windows.
