### ISSUE TITLE
..."core.update] - [0x01] PatBlt - update_read_dstblt_order() failed" & "...order flags 09 failed"

### ISSUE THREAD

**Issue by tbuitendyk** [FreeRDP/FreeRDP#6641]
Hope this is OK to post as a bug ... I'm trying to get this right.  This can be moved to another category if I've guessed wrong here with respect to Bug report vs. Question...

I'm running FreeRDP from an ancient Neoware CA19 thin client that I'm network booting with Tiny Core. I am getting the above errors, followed by

[ERROR][com.freerdp.core.fastpath] - Fastpath update Orders [0] failed, status 0
...core.fastpath] - fastpath_recv_update() - -1
...core.fastpath] - fastpath_recv_update_data() fail
...core.transport] - transport_check_fds() failed - 0
[INFO]...client.common] - Network disconnect!
[ERROR]...client.X11] - Failed to check FreeRDP file descriptor

I'm PXE loading the latest 11.x Tiny Core Linux build with the Tiny Core FreeRDP extension entitled "freerdp2.tcz", which indicates "Version: 2.1.2".  My target RDP server ("Terminal Services" actually, as it's non R2 Win Srv 2008) is working fine with RDP connections from other clients both over the Internet and via VPN tunnels and from the LAN.

Given the similarity of the errors noted above to "Can't connect to xrdp #5207" I've tried running the xfreerdp (as it's called in my Tiny Core extension) with lines like this:

sudo /tmp/tcloop/freerdp2/usr/local/bin/xfreerdp /u:<"domain\account"> /p:<"password"> / v:<public_ip_address> /port:<port_num> +glyph-cache /relax-order-checks

(All of the parameters except the glyph-cache and relax-order-checks are tested and working fine from Windows 7 -> Windows Server 2008 over the same network that fails with the Thin Client.)

The Thin Client's Tiny Core / FreeRDP set-up is confirmed to be working without issues when connections as per the above command line (without the glyph and order checks parameters) are made from the Thin Client to an RDP service running on a Windows 10 machine.

Here's some other notes that I left on a closed issue that probably will go unnoticed...hence this new report:

************************************************************************************
I've been busy the past few days building a PXE image to boot an ancient Neoware CA19 thin client with Tiny Core. I've got all of that working fine, and I've made a customized Tiny Core initrd with FreeRDP2 and all the .so dependencies that Tiny Core wants when running it. I'm running the latest Tiny Core 11.x with the freerdp2 extension in Tiny Core which includes version 2.1.2 of FreeRDP2.

(Not really relevant, but just to give a context: I'm building this for a doctor's office that's running an old Server 2008 for their Terminal Services. (Can't use the Neoware firmware as the RDP client version is 5.x and can't be upgraded -- RDP v.5.x can't connect to Server 2008 and newer, which is why I've built this network load option.))

With my test environment with RDP access against Windows 10 Pro desktop the thin client and freerdp2 runs 100% as far as I can see. My problem is that when I hit the doctor's Win 2008 Server the connection drops immediately after establishing. Some of the errors noted by others pop up: first Fastpath errors, starting with "Fastpath update Orders", Then there is the "transport_check_fds: transport->ReceiveCallback() - -3" error from com.freerdp.core.transport, and then "freerdp_check_fds() failed - 0" from com.freerdp.core, followed by the "Network disconnect!" error from freerdp.client.common and "Failed to check FreeRDP file descriptor" from freerdp.client.X11.

I've hunted around on github and elsewhere and have already tried the "+glyph-cache" and "/relax-order-checks" options on the xfreerdp call in my scripting...but to no avail at this point.
************************************************************************************

Is this a bug?  Or if not, can we move this where it should be and can you give any suggestions? Should I be going back to a 1.x version of freerdp? Would it be worthwhile trying to set-up a build environment to make some source code changes to try to compile a new binary?

I know I can go back to rdesktop with the Thin Client build but I would rather use FreeRDP.

Thank you.

**Comment by akallabeth** [comment]
Please test with current versions (and possibly try our nightlies as reference too):

* `2.1.2` has already been superseeded quite some time
* Please do not use `relax-order-checks` - that is a very specific workaround for `xrdp` and should not be used carelessly
* Please try to recreate this on a normal linux machine (the hardware is quite irrelevant for `xfreerdp` but you have it much easier to debug)

**Comment by tbuitendyk** [comment]
Thank you akallabeth for your guidance.  I'm researching how to build a Tiny Core extension with the latest release of xfreerdp ... it might be something I need to do on another Linux platform as you suggested.  Will get back with my results.

**Comment by tbuitendyk** [comment]
> Please test with current versions (and possibly try our nightlies as reference too):
> 
>     * `2.1.2` has already been superseeded quite some time
> 
>     * Please do not use `relax-order-checks` - that is a very specific workaround for `xrdp` and should not be used carelessly
> 
>     * Please try to recreate this on a normal linux machine (the hardware is quite irrelevant for `xfreerdp` but you have it much easier to debug)

Hello again akallabeth ... More or less following your advice, I tried to recreate the problem on another machine -- one running Ubuntu 20.  As I will likely need to build the 32-bit binaries from scratch I thought I would start by trying to build the binaries from the latest source.  I took the flatpak approach as per the instructions on the Compilation page ... had to add a bunch of missing pieces, but compiling seemed to work:

```
root@xxxx/FreeRDP# flatpak-builder --repo=repo FreeRDP-bld-dir packaging/flatpak/com.freerdp.FreeRDP.json
.
.
.
Content Bytes Written: 22219796 (22.2 MB)
Pruning cache

```
Then I did the installer build which also seemed to work:

`root@xxxx/FreeRDP# flatpak build-bundle repo com.freerdp.FreeRDP.flatpak com.freerdp.FreeRDP --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
`

And then ran the flatpak installer which also seemed to work:

```
root@xxxx/FreeRDP# flatpak install com.freerdp.FreeRDP.flatpak

Note that the directories 

'/var/lib/flatpak/exports/share'
'/root/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.


com.freerdp.FreeRDP permissions:
    ipc     network     fallback-x11     pulseaudio     wayland     x11     file access [1]

    [1] xdg-download


        ID                            Branch          Op          Remote                  Download
 1. [✓] com.freerdp.FreeRDP           master          i           freerdp-origin          0 bytes

Installation complete.

```
I hunted around for the binary, found a start-up script under my build dir, found the xfreerdp binary under files/bin, but can't run the binary as the environment doesn't seem to be in place (missing references to libraries, etc.):

```
root@xxxx/FreeRDP/FreeRDP-bld-dir/files/bin# cat freerdp.sh 
#!/bin/sh
if [ -z $XDG_SESSION_TYPE ];
then
	echo "XDG_SESSION_TYPE undefined"
	exit -1
elif [ "$XDG_SESSION_TYPE" = "wayland" ];
then
	echo "wayland $(which wlfreerdp)"
	wlfreerdp $@
elif [ "$XDG_SESSION_TYPE" = "x11" ];
then
	echo "X11 $(which xfreerdp)"
	xfreerdp $@
	exit $rc
else
	echo "XDG_SESSION_TYPE $XDG_SESSION_TYPE not handled"
	exit -1
fi
root@xxxx/FreeRDP/FreeRDP-bld-dir/files/bin# ./xfreerdp 
./xfreerdp: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory
root@xxxx/FreeRDP# find / -name libavcodec.so.58
/home/myob/thinstation/usr/lib/libavcodec.so.58
find: ‘/run/user/1000/doc’: Permission denied
find: ‘/run/user/1000/gvfs’: Permission denied
/var/lib/flatpak/runtime/org.freedesktop.Platform.ffmpeg-full/x86_64/19.08/b51c21e34c233787b1b136f15564f7706ed60f5b265701273c01d048c7656428/files/libavcodec.so.58
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/19.08/b05888992f5d9e089bc3eb115d0b2998b394c84af1a001044844aac1b180a929/files/lib/x86_64-linux-gnu/libavcodec.so.58
/var/lib/flatpak/runtime/org.freedesktop.Sdk/x86_64/19.08/ee4ecf9fbcf2de32d2c500e3c65e4460ada89ab91217e76a122c431cec63e54c/files/lib/x86_64-linux-gnu/libavcodec.so.58

```

I tried restarting my session at that point ... still can't run the FreeRDP I built.  Would like to get my newly compiled running on Ubuntu to test the binary before going forward and replicating the same on a TinyCore installation.  (I suppose I need to do another build on a full TinyCore set-up to get it compiled for the ancient CPU?  Unless there's an option I can use to compile for an i486 on my 64-bit Ubuntu platform...

If you could give any pointers on going forward here that would be great.  thanks a lot.

**Comment by akallabeth** [comment]
@tbuitendyk better stay with the `dpkg-buildpackage` instructions if you don´t know how flatpak works ;)

**Comment by tbuitendyk** [comment]
> @tbuitendyk better stay with the `dpkg-buildpackage` instructions if you don´t know how flatpak works ;)

Thank you.  I did get the 2.2.0 version to compile on a fresh Tiny Core installation on an old PC (instead of the thin client.)  That version seems to have taken care of the issue, as the RDP session stays connected now to the Windows Server 2008 machine.  I've just finished making the Tiny Core extension and it's working well.

thx for your help
