### ISSUE TITLE
Not able to create device context for client in wfreerdp-server

### ISSUE THREAD

**Issue by zhangleia** [FreeRDP/FreeRDP#6644]
Releated pull request for master:  
Operating system win7    Operating system win7 ： vs2010
In wf_mirage.c
BOOL wf_mirror_driver_map_memory(wfInfo* wfi)
{
	int status;
	//wfi->driverDC = CreateDC(wfi->deviceName, NULL, NULL, NULL);
	wfi->driverDC = CreateDC(L"DISPLAY", NULL, NULL, NULL);

	if (wfi->driverDC == NULL)
	{
		WLog_ERR(TAG, "Could not create device driver context!");
		{
			LPVOID lpMsgBuf;
			DWORD dw = GetLastError();
			FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM |
			                  FORMAT_MESSAGE_IGNORE_INSERTS,
			              NULL, dw, MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), (LPTSTR)&lpMsgBuf, 0,
			              NULL);
			// Display the error message and exit the process
			WLog_ERR(TAG, "CreateDC failed on device [%s] with error %lu: %s", wfi->deviceName, dw,
			         lpMsgBuf);
			LocalFree(lpMsgBuf);
		}
		return FALSE;
	}

	wfi->changeBuffer = calloc(1, sizeof(GETCHANGESBUF));

	if (!wfi->changeBuffer)
		return FALSE;

	status = ExtEscape(wfi->driverDC, dmf_esc_usm_pipe_map, 0, 0, sizeof(GETCHANGESBUF),
	                   (LPSTR)wfi->changeBuffer);
	
	if (status <= 0)
	{
		WLog_ERR(TAG, "Failed to map shared memory from the driver! code %d", status);
		return FALSE;
	}

	return TRUE;
}

ExtEscape always returns 0

**Comment by zhangleia** [comment]
＃5716  There is no solution in #5716. Has this problem been solved?

**Comment by akallabeth** [comment]
There is no solution for that bug, please do not create new issues but create a pull request if you have a solution.
