### ISSUE TITLE
Are those the best performance options/flags?

### ISSUE THREAD

**Issue by Utini2000** [FreeRDP/FreeRDP#6647]
Good evening,

I am on Arch and connect to a Windows 2008 R2 server via RDP. 
This happens via my home network and a VPN but also via the local company wifi in the office.
For both cases I am trying to figure out the best settings for performance and quality.

So far I came up with the following options:
xfreerdp /u:username /d:domain /v:server 
/f - for fullscreen
/bpp:32 - for decent colors
+fonts - for decent fonts
/rfx - no idea
/rf-mode: video
/gfx-h264:AVC444  - but I think onnly H264 is supported on the Server
/compression - I could enable this on home wifi and disable this on local company wifi?
/audio-mode:1 - Because I don't need it
/gdi:hw - no idea
/heartbeat
/nsc

Can anyone help/confirm me that those are the best possible options or should I consider something else?

Thanks!

**Comment by akallabeth** [comment]
Hi, please prefer the mailing list or our IRC for questions. ( https://github.com/FreeRDP/FreeRDP/wiki/BugReporting )
as for options, `/network:auto /rfx /gfx:avc444 /f` for windows 8 and up, `/bpp:32 /rfx /f` for windows 7 and older.
