### ISSUE TITLE
Can the multiple monitors be used for duplicate screen?

### ISSUE THREAD

**Issue by hlc926** [FreeRDP/FreeRDP#6648]
Hello,

Can the multiple monitors be used for duplicate screen?   I need two monitors to display the same, windows is better than fullscreen.

if yes, how to use? 

if no, will it have a plan? 

Thank you and great job!

**Comment by bmiklautz** [comment]
@hlc926 would you share more more details what you want to archive? - Connect two monitors to an RDP host?

**Comment by hlc926** [comment]
@bmiklautz yes, Connect two monitors to an RDP host.

**Comment by akallabeth** [comment]
@hlc926 no, that is a local setting only.

**Comment by hlc926** [comment]
@akallabeth I would want two monitors to display the same screen of an RDP host, would you have some good idea?

**Comment by akallabeth** [comment]
@hlc926 how about opening your systems monitor configuration tool and setting that to mirror?

**Comment by hlc926** [comment]
@akallabeth 
thank you very much. but this is not suitable for me. 

I need the extended screen for local,  duplicate screen for the RDP host.
so, for the RDP host, windows is better than fullscreen.
and the second windows for the RDP host, I only need a viewable screen, no need to operate anything on it, but this is not necessary.
