### ISSUE TITLE
LIBUSB_ERROR_ACCESS[-3] while connecting usb device

### ISSUE THREAD

**Issue by ultraSsak** [FreeRDP/FreeRDP#6651]
Hi, 
I'm doing this first time (posting an issue on github), so please don't throw tantrums at me..

I am trying to connect webcam through xfreerdp.
`xfreerdp /usb:auto`
But i get this Error (from title) everytime.
Output from xfreerdp:

`[21:42:00:421] [40481:40520] [DEBUG][com.freerdp.channels.urbdrc.client] - Hotplug add device VID=0x0C45,PID=0x6366 class UNKNOWN_DEVICE_CLASS
[21:42:00:421] [40481:40520] [DEBUG][com.freerdp.channels.urbdrc.client] - bus:1 dev:18
[21:42:00:421] [40481:40520] [DEBUG][com.freerdp.channels.urbdrc.client] -   Port: 4
[21:42:00:421] [40481:40520] [DEBUG][com.freerdp.channels.urbdrc.client] -   DevPath: 1-4
[21:42:00:421] [40481:40520] [DEBUG][com.freerdp.channels.urbdrc.client] -   Open hub: 1
[21:42:00:421] [40481:40520] [ERROR][com.freerdp.channels.urbdrc.client] - libusb_open: error LIBUSB_ERROR_ACCESS[-3]
[21:42:00:422] [40481:40520] [DEBUG][com.freerdp.channels.urbdrc.client] - Registered Device: Vid: 0x0C45 Pid: 0x6366 InterfaceClass = LIBUSB_CLASS_VIDEO
`
I tried to modify the permissions with udev:
`SUBSYSTEMS=="usb", ATTRS{idVendor}=="0c45", ATTRS{idProduct}=="6366", SYMLINK+="webcam", GROUP="wheel", MODE="0666"`
and the rule is executed successfully.
But this doesn't change anything :/

What else can I try to solve this issue?

**Comment by myjimmy** [comment]
@ultraSsak, please try to follow the below steps:

1. Run the following command:
`$ sudo chmod -R 777 /dev/bus/usb/`
2. Create the ’xx-local.rules’ file in /etc/udev/rules.d folder:
`$ sudo gvim /etc/udev/rules.d/100-local.rules`
3. Add the following content:
`SUBSYSTEM=="usb", ATTRS{idVendor}=="0c45",   ATTRS{idProduct}=="6366", OWNER="ubuntu",   GROUP="plugdev", TAG+="uaccess"`
where "ubuntu" is your username.
4. Add your user to the plugdev group (replace with your username):
`$ sudo adduser your_username plugdev`
5. Restart the udev rules:
`$ sudo udevadm control --reload-rules`
6. Unplug and plug the usb device.

Please see the following URL for detailed information:
https://askubuntu.com/questions/978552/how-do-i-make-libusb-work-as-non-root

**Comment by akallabeth** [comment]
@ultraSsak what @myjimmy posted is mostly the way to go, just skip the `chmod` stuff, the `udev` rule is sufficient. `OWNER` in the rule can stay `root` (you only need read/write access for the group)

**Comment by ultraSsak** [comment]
I have the rule already
After inspecting the issue it came to my attention that this thing cannot open the hub 
`Open hub: 1 [21:42:00:421] [40481:40520] [ERROR]`, not actual camera device.

tried @myjimmy 's solution to chmod 777, it worked! No more permission issue.
now i only have to know why :+1: 
Big thanks guys

**Comment by joelwass** [comment]
I had this issue trying to use Code Composer Studio on Ubuntu. LIBUSB_ERROR_ACCESS - turns out i just need to run `sudo chmod -R 777 /dev/bus/usb/` to grant permissions for non root users to access usb ports. thanks @myjimmy !
