### ISSUE TITLE
Bug report on Manjaro

### ISSUE THREAD

**Issue by LoSunny** [FreeRDP/FreeRDP#6663]
**Describe the bug**
I'm currently trying to remote desktop from my Macbook to my Manjaro machine

**To Reproduce**
1. Type `freerdp-shadow-cli -auth`
Here are the logs: https://hastebin.com/cuqojedoxu.md

**Expected behavior**
The remote desktop connection should establish and work

**Screenshots**
After I click connect, it popup an error for a second, and after I click ok. The screen shows up for a second and freezes, cannot click anywhere nor the screen is updating

**Application details**
* FreeRDP version (`xfreerdp /version`): `[com.freerdp.server.shadow] - FreeRDP version 2.2.0 (git n/a)`
* Command line used: `freerdp-shadow-cli -auth`
* Output of `xfreerdp /buildconfig`: https://hastebin.com/enuxacomud.md
* OS version connecting to (server side): Manjaro KDE Plasma 20.1
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`: I'm not sure what do you mean
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help: `I've tried to build it myself, but failed because of an error`: https://hastebin.com/urababalat.yaml

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]: `Manjaro KDE Plasma 20.1`
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]: `Manjaro KDE Plasma 20.1`
 - Architecture: [amd64, arm]: `intel, 64 bit`

**Comment by akallabeth** [comment]
1. But is most likely with H264 encoding as established via IRC, so try the build without FFMPEG
1. Your build error is you do not have parts of FFMPEG (`libswresample` or `libavresample`) installed, so you still build with FFMPEG

**Comment by akallabeth** [comment]
additionally I´d like to advice against using `freerdp-shadow-cli -auth` (this allows anyone without authorization access to your desktop!)

If you do not need to mirror your current session (remote assistance or similar) better use full powered RDP server like

* https://github.com/ogon-project/ogon-project
* https://github.com/neutrinolabs/xrdp

**Comment by LoSunny** [comment]
1. I've tried to build without FFMPEG by adding option WITH_FFMPEG=FALSE, but the build script still fails.
2. I'm using the `-auth` just for testing, in production, I'll apply some encryption or network authentication

**Comment by akallabeth** [comment]
your build is still referencing the mentioned libraries. Might be that you build audio against FFMPEG (`WITH_DSP_FFMPEG`)? In that cast just install the missing libraries.

**Comment by LoSunny** [comment]
Oh yeah, maybe that's the problem, I'll try it again with `WITH_DSP_FFMPEG ` set to `FALSE`
My build script now: ```cmake -GNinja -WITH_FFMPEG=OFF -WITH_OPENH264=ON -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=OFF -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON -DWITH_SERVER=ON .```

**Comment by LoSunny** [comment]
After building, it doesn't seem to fix the error and it's still there: https://hastebin.com/olecicogic.md

**Comment by akallabeth** [comment]
ok, did you build from master?
That version I´ve tested here and works quite nicely, so this seems to be something different.
Maybe you´re lacking some `X11` related development headers?

**Comment by LoSunny** [comment]
I believe I'm from master
```
$ git branch
* master
```
Anything I need to preinstall in manjaro with `X11` related development headers?
As I can't see any precompile instructions for arch distros

**Comment by akallabeth** [comment]
no idea, not really the arch guy :/

**Comment by LoSunny** [comment]
During the testing, I've also installed PopOS (Ubuntu) too, same build script, and still same error. I don't think it's because of the distro (Should I create a new issue for this?)

**Comment by akallabeth** [comment]
ok, got a ubuntu machine running, that is working nicely.
You are running a `X11` session there?

**Comment by akallabeth** [comment]
FYI, running packaged freerdp-shadow of ubuntu 20.04, so this looks like a bug in your scripts

**Comment by LoSunny** [comment]
Yep, it's an `X11` session

**Comment by LoSunny** [comment]
Here is the log file for the ubuntu distro: https://hastebin.com/xevewekuzu.md

**Comment by akallabeth** [comment]
ok, tried with `xfreerdp`, `mstsc` and mac rdp client now, can not reproduce.
How did you set up the ubuntu machine?
I´ve just used a default install image, added `apt install freerdp2-shadow-x11` and started it.
works in every case I´ve tried so far.

**Comment by LoSunny** [comment]
I just created a virtual machine with the operating system of freshly downloaded from the respected website of popos and manjaro

**Comment by akallabeth** [comment]
@LoSunny 
1. installation iso or some kind of already set up image?
1. How did you install freerdp? Self compiled / package / ?

**Comment by LoSunny** [comment]
1. I just download the iso from their website and freshly install freerdp
2. Both compile and packaged install method won't work

**Comment by akallabeth** [comment]
@LoSunny same result with our nightly builds? Setting up a PopOS (20.10) image now, checking if that may be the reason, but I can´t reproduce with debian bullseye or ubuntu 20.04

**Comment by akallabeth** [comment]
@LoSunny ok, set up a fresh PopOS (20.10) and installed freerdp shadow, running as expected.
sorry, there seems to be  something wrong on your end, tried this now on various VM and hardware as well as with different OS clients (linux/win/mac)

**Comment by LoSunny** [comment]
Here is the error log from popos: https://hastebin.com/osiquyurek.md

**Comment by akallabeth** [comment]
@LoSunny the log is utterly wrong, PopOS uses the package from ubuntu which has no H264 support compiled in. the log line `initializing H.264 encoder` can not happen (verified that) if you are using plain packages without modifications.
So, please remove the buggy/self compiled/ppa packages you use and retry.

**Comment by LoSunny** [comment]
I don't think that disabling H.264 encoder will solve the issue, here is the compile command
```
cmake -GNinja -WITH_FFMPEG=OFF -WITH_OPENH264=ON -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=OFF -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON -DWITH_SERVER=ON .
```
And error log: https://hastebin.com/uvamowemad.md

**Comment by akallabeth** [comment]
@LoSunny it just did (read the log)
Please do not tell that you tried with the `package` from `ubuntu` or `popos` if you did not.

**Comment by LoSunny** [comment]
No, I did not, I compile it with the source with the command in the previous comment, and do ```cmake --build . --target install``` to install it to my system

**Comment by LoSunny** [comment]
```
$ freerdp-shadow-cli -version
[19:33:53:655] [30647:30647] [INFO][com.freerdp.server.shadow] - FreeRDP version 3.0.0-dev (git fa218f79c)
```
