### ISSUE TITLE
Use `+clipboard`, Copy and paste does not work!

### ISSUE THREAD

**Issue by shh230** [FreeRDP/FreeRDP#6665]
Releated pull request for master: 

```
xfreerdp /v:ip /cert:ignore /u:username /p:%@ +window-drag +clipboard
```

Use `+clipboard`, Copy and paste does not work!

On Winodws Remote Desktop use `control c` only can work on windows remote desktop. Remote Desktop use `control + c` on windows and use `contorl + v` on mac， does not work.

Platform：MacOS 
MacOS version：10.15.6

**Comment by akallabeth** [comment]
1. well, `<ctrl>+v` will never work on a mac (they use the `apple` key)
1. you are using `xfreerdp` so check your local `X11` on mac os properly handles that.

**Comment by shh230** [comment]
Now, I am using `<ctrl>+c` or `<ctrl>+v` on a windows as server. sometime this key can work, sometime not work.
