### ISSUE TITLE
Shortcut keys do not take effect

### ISSUE THREAD

**Issue by shh230** [FreeRDP/FreeRDP#6673]
Releated pull request for master: 

```
xfreerdp /v:ip /cert:ignore /u:username /p:**** +clipboard
```

Enter a character for the first time, and then press `<ctrl+a>`, it cannot be selected.

After releasing the button, then press `<ctrl+a>` again that can be selected.

https://user-images.githubusercontent.com/38716757/102593721-2f331c80-4150-11eb-936a-d38e1f95bf14.mov

As video, all operation is <ctrl+a>

client platform: MacOS
server platform: windows
freerdp version:  3.0.0-dev

**Comment by akallabeth** [comment]
sorry, that is a mac os issue.
`xfreerdp` requires a properly working X11 environment, mac os has a limited one.
Try the native mac client.
