### ISSUE TITLE
version 2.2.0 is identified as a virus

### ISSUE THREAD

**Issue by antrobot-hw** [FreeRDP/FreeRDP#6674]
Freerdp.exe 2.2.0 downloaded from the official website is identified as a virus by multiple virus vendors. As a result, the freerdp.exe 2.2.0 is unavailable.

**Comment by akallabeth** [comment]
I assume you´re talking abour our nightly builds? Please notify the antivirus vendors about their screwup. Nothing we can do on our side here.
