### ISSUE TITLE
Multimon

### ISSUE THREAD

**Issue by wkmdd** [FreeRDP/FreeRDP#6677]
Surroundings:
Ubuntu 2010
xfreerdp 3.0.0-dev (42083c597)

I have a little problem with / multimon with two screens.
Switching from full screen / window mode / full screen works, but when I do this several times (5-10 times) in relatively short succession

do, the session is disconnected. Switch / reconnect means less frustration.
Can someone confirm the behavior and identify the causes.

Without / multimon, I couldn't find any separations when switching full screen / window mode / full screen.

**Comment by akallabeth** [comment]
sorry, without some basic information we can not tell you anyting.
At least your command line and log output would be required. The server os you´re connecting to would also be greatly appreciated.
