### ISSUE TITLE
 Failed to modify file when unplug the U disk and insert it again(use /drive:hotplug,*) .

### ISSUE THREAD

**Issue by ALEX-PSY** [FreeRDP/FreeRDP#6687]
I have met  some problem with drive redirection.
First, using "/dirve:hotplug,*"  arg to redirect my USB drive to the remote desktop(Win10);
Then, modified some files such as ‘temp.txt’ in remoted folder, save it.
Finally, unplug the USB drive then insert it again.
The result is that the 'temp.txt' has not been modified at all. I have tried many times, and each time it was the result.

I'm using freerdp on Ubuntu 18.04 and freerdp 2.0.0 rc4. But it's worked at previous version such as 1.2.1 before.

**Comment by akallabeth** [comment]
Please test our nightly builds and test if it works with these. https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

**Comment by ALEX-PSY** [comment]
> Please test our nightly builds and test if it works with these. https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

Thanks for your reply.
Do you mean the problem has been solved in that version?

**Comment by ALEX-PSY** [comment]
> Please test our nightly builds and test if it works with these. https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

The problem is still exist by use the master branch.

**Comment by ALEX-PSY** [comment]
> Please test our nightly builds and test if it works with these. https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

It is very confusing me. Can you test it by your own computor? Ubuntu to Win10, and the USB flash disk.

**Comment by akallabeth** [comment]
@ALEX-PSY ok, I can´t reproduce this issue at all (If I open and save a file then it is saved)
Do you have a sync issue with your USB stick maybe?

**Comment by akallabeth** [comment]
@ALEX-PSY best try an alternate redirected folder like your home drive? If it works there the issue is your OS or hardware.

**Comment by ALEX-PSY** [comment]
> @ALEX-PSY best try an alternate redirected folder like your home drive? If it works there the issue is your OS or hardware.
If not unplug the USB stick then it is saved. But if re-plug USB stick then open the file, it is same as before.

**Comment by akallabeth** [comment]
ok, then check your local mount options, this is a classic data not synced issue, which freerdp can not influence (hint: it is the duty of the operating system to do that)
