### ISSUE TITLE
2 servers menu

### ISSUE THREAD

**Issue by versus2** [FreeRDP/FreeRDP#6690]
How do I setup 2 choice menu (with 2 users and 2 servers)
I've tried this and and it didn't work

FREERDP_SELECT_SERVER = On
FREERDP_SERVER_0 = "Server 1"
FREERDP_SERVER_1 = "Server 2"

SESSION_0_TITLE = "Server 1"
SESSION_0_TYPE = freerdp
SESSION_0_FREERDP_SERVER = 192.168.0.11
SESSION_0_FREERDP_USER = "User1"
SESSION_0_FREERDP_OPTIONS = "-cert-ignore"
SESSION_0_AUTOSTART = On

SESSION_1_TITLE = "Server 2"
SESSION_1_TYPE = freerdp
SESSION_1_FREERDP_SERVER = 192.168.0.12
SESSION_1_FREERDP_USER = "User2"
SESSION_1_FREERDP_OPTIONS = "-cert-ignore"
SESSION_1_AUTOSTART = On

**Comment by akallabeth** [comment]
for support please at least try to explain what you´re trying to do.
Also prefer IRC or the mailing list for such matters, this is an issue tracker.
