### ISSUE TITLE
How to optimize for retina displays?

### ISSUE THREAD

**Issue by shh230** [FreeRDP/FreeRDP#6695]
How to optimize for retina displays?

Microsoft RDP  enable optimize for retina displays.
![Microsoft RDP:enable optimize for retina displays](https://user-images.githubusercontent.com/38716757/103256533-98c0ef80-49c8-11eb-9b98-bc83febc2002.jpg)

FreeRDP, how to optimize for retina displays?
![freerdp](https://user-images.githubusercontent.com/38716757/103256539-9bbbe000-49c8-11eb-9423-d38777d4bb91.jpg)

**Comment by akallabeth** [comment]
@shh230 what exactly do you want? There are 2 options:

1. You connect to a server supporting RDP-HighDPI, then use the `/scale*` options to tell the server your local screen config
2. Your remote os does not support that, then use `/size:<remote resolution> /smart-sizing` to do local scaling to whatever window size you desire

**Comment by MikeZTM** [comment]
this is not working as FreeRDP is running on X11 with does not support Retina/Scalling

**Comment by akallabeth** [comment]
@MikeZTM what does X11 HighDPI support have to do with that?

**Comment by MikeZTM** [comment]
@akallabeth the only X11 implementation on macOS is XQuartz. This thing does not support Retina Display.
It does display an image of arbitrary resolution but only in pixel-double mode that mean 1 pixel in X11 API is 2x2 pixels on screen.

It can never render a single pixel dot on a macOS retina screen.
As far as I checked XQuartz have no plan for Retina support in the foreseeable future so I'm looking for a different display backend for FreeRDP on macOS.

And if there's nothing else I can start implement a new backend for this and willing to contribute if the code meet the standard of the repo.

**Comment by akallabeth** [comment]
@MikeZTM ok, then that answers the question regarding `X11`.
A new mac backend would be awesome!
the current client is more or less `tech demo` but without anyone actively maintaining it.
If you have any questions, you can reach me (most) of the time in IRC or (same handle) on matrix.org
