### ISSUE TITLE
How to solve the problems in building IOS（macOS 10.15.6）

### ISSUE THREAD

**Issue by qaz1991815** [FreeRDP/FreeRDP#6697]
error: unable to resolve product type 'com.apple.product-type.tool' for platform 'iphoneos' (in target 'cmTC_4d9a1' from project 'CMAKE_TRY_COMPILE')

**Comment by akallabeth** [comment]
iOS build is currently unmaintained.
Please try to explain in a bit more words what you´re trying to do and what fails.
This is just not enough to give an answer.

**Comment by qaz1991815** [comment]
cmake：3.19.2
 xcode：12.0 
I'm using camke to build freerdp（https://github.com/FreeRDP/FreeRDP)，When I go to the last step enter: cmake - dcmake_ TOOLCHAIN_ FILE=cmake/ iOSToolchain.cmake -Gxcode, that's the problem. I don't know how to solve it
