### ISSUE TITLE
Mouse cursor always an arrow in RemoteApp

### ISSUE THREAD

**Issue by roland65** [FreeRDP/FreeRDP#6700]
In RemoteApp mode, under Linux (Ubuntu 20.04), the mouse cursor is always an arrow and doesn't adapt its shape to the application context. For example, the mouse cursor should become a hand when it is over a link. Or it should be a cross in Excel when it is above a cell, etc.

Here is a patch against freerdp 2.2.0 that fixes the issue.
[mouse-cursor.patch.gz](https://github.com/FreeRDP/FreeRDP/files/5754336/mouse-cursor.patch.gz)

**Comment by akallabeth** [comment]
@roland65 you might want to check out https://github.com/FreeRDP/FreeRDP/pull/6642 which is currently pending to be merged.
