### ISSUE TITLE
support for Microsoft AX Dynamics

### ISSUE THREAD

**Issue by Sy3Omda** [FreeRDP/FreeRDP#6703]
HI,
i'm using the current command to connect to ax dynamics
```
xfreerdp Ax1.rdp /u:user /p:password /f /v:10.0.0.150
```
and it works till i open another window and it hanging and refuse to open drop down menu in AX program
PS: the (Ax1.rdp) is the icon i created to allow users to connect to remoteapp (ax)

if i'm missing something here could you guide me
Thanks

**Comment by akallabeth** [comment]
Sounds like you have some trouble with `rails` (remote app)?
Please check https://github.com/FreeRDP/FreeRDP/issues?q=is%3Aopen+is%3Aissue+label%3Achannel%3Arail if any of the issues is what you experience.
