### ISSUE TITLE
Plugin for Remmina?

### ISSUE THREAD

**Issue by DAC324** [FreeRDP/FreeRDP#6706]
Hello all,

please accept my apologies if I have missed important information.

I am just wondering why the support for Remmina seems to have been dropped in the 3.x branch of FreeRDP. At least, I was not able to create the required plugin file from the available sources.

Thank you very much and kind regards.

**Comment by akallabeth** [comment]
https://gitlab.com/Remmina/Remmina

please check their build howto, they are already using freerdp master for development builds.

**Comment by antenore** [comment]
For reference answered here: https://gitlab.com/Remmina/Remmina/-/issues/2381
