### ISSUE TITLE
Printing sometimes produces a disconnect when using Apache Guacamole 1.2.0/1.3.0

### ISSUE THREAD

**Issue by myjimmy** [FreeRDP/FreeRDP#6708]
I found an issue that printing sometimes produces a disconnect when using Apache Guacamole 1.2.0/1.3.0.

**Environment**
The environment for this issue follows as below:

- Remote server: Windows 10 Pro N Version 1909 (18363.1256)
- Microsoft Office Professional Plus 2016 (Version 2011, Build 13426.20308)
- Google Chrome 87.0.4280.88 (Official Build) (64-bit)
- Guacamole Client: 1.2.0 / 1.3.0
- Guacamole Server: 1.2.0 / 1.3.0
- FreeRDP: stable-2.0 (39f56443)
- Connection parameters
![image](https://user-images.githubusercontent.com/52309150/104149307-5e028280-53de-11eb-915a-125d4c81e6dc.png)

**To Reproduce**
Test case for this issue follows as below:
1. Open MS Word / Notepad.
2. Create a new document.
3. Copy/paste or type any text in the document.
4. Press Ctrl + P to print this document.

When printing the document about 50 times, I encountered the disconnect issue.

The log of the guacamole server follows as below:
![image](https://user-images.githubusercontent.com/52309150/104149407-b174d080-53de-11eb-8709-15c55b6ee0f4.png)

I asked the Apache Guacamole support team about this issue.
They told me that this issue is an internal error within FreeRDP related to decrypting the traffic from the RDP server.
Please see [this link](https://issues.apache.org/jira/browse/GUACAMOLE-1240?focusedCommentId=17260167&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17260167) for more information.

**Note**
I think that this issue is related to the kind of security type.
I can't see this issue when the security type is "NLA", but I see it when the security type is "RDP".

**Comment by akallabeth** [comment]
@myjimmy this is a message from the server explaining why it is disconnecting the client.
Can you reproduce this with plain `xfreerdp`? 
The possible causes I can think of are:
1. Some internal error of freerdp
2. Some thread issue the way `guacamole` uses printing
3. Some error server side

So, if you can reproduce it with `xfreerdp` we can eliminate `guacamole` as origin of the fault and it is easier for us to reproduce

**Comment by myjimmy** [comment]
@akallabeth Thanks for your reply.
I used the following command, but I can't print any text file to pdf document.
`xfreerdp /v:192.168.32.129 /u:ptc /p:ptc /sec:rdp /log-level:DEBUG /printer:"Test Printer"`
* OS: Ubuntu 18.04 64bit
* Remote Server: Windows 10 Pro N Version 1909 (18363.1256)

Please let me know the command to test the printing feature of the xfreerdp.

**Comment by myjimmy** [comment]
@akallabeth 
I have added the PDF printer to the remote server via xfreerdp.
I used the following command to add the PDF printer in Ubuntu 18.04:
`sudo apt-get install cups-pdf`

I used the following command to attach the PDF printer to the remote server:
`xfreerdp /v:192.168.**.** /u:*** /p:*** /sec:rdp /log-level:DEBUG /printer:"PDF"`

**Comment by myjimmy** [comment]
@akallabeth When using xfreerdp, I can't see this issue.
I think that this issue is related to the different printing methods in the xfreerdp and the guacamole.
When printing, xfreerdp is printing sequentially the documents with a PDF printer and the printing manager of the operating system, and so, we can't see this issue.
But when printing, the guacamole receives directly the printing stream from the remote server and generates the pdf data by using Ghostscript(gs) and sends it to the browser, and lets a user download it as a PDF file.

I would like to know what is the difference between those printing methods from the point of view of the RDP specification.

**Comment by akallabeth** [comment]
@myjimmy well, the diff is none.
From the RDP side you receive a `postscritpt` file that you can directly store or process further.
If you send that to cups or ghostscript does not matter, so the issue must be something with the postprocessing chain.
I have not checked the `guacamole` implementation, but the printer channel already handles all that RDP specific part, so there can not be any diff there.

If they just implemented a backend (like the one for `cups`) then `printjob->Write(printjob, ptr, Length)` in `printer_process_irp_write` is the function providing the `ghostscript`
