### ISSUE TITLE
\d:DomainName is not prepended to the username when using -sec-nla

### ISSUE THREAD

**Issue by Pivert** [FreeRDP/FreeRDP#6716]
When using service with NLA disabled, xfreerdp do not prepend the DomainName\ in front of the username.
In fact, I found no possible way to prepend the domain name. For instance, none of those 2 ways actually works:

xfreerdp -sec-nla /d:CompanyAD /u:firstname.lastname@mycompany.com /v:rdpserver.mycompany.com
xfreerdp -sec-nla /u:CompanyAD\\firstname.lastname@mycompany.com /v:rdpserver.mycompany.com

It connects to the login screen, but the CompanyAD\ is never prepended to the username and/or the logon domain is never provided.

Regards,

**Comment by akallabeth** [comment]
Please add some information, can not reproduce.
which versions are you useing?

**Comment by Pivert** [comment]
Hi,
This is FreeRDP version 2.2.0 (2.2.0)

Strange that you can't reproduce. I can try to provide a screenshot of the windows login screen after executing those 2 examples.

**Comment by Pivert** [comment]
For instance, using the below command on my Windows10 Pro:
`xfreerdp -sec-nla /cert:ignore /d:MyAD /u:pivert.dubuisson@ext.test.com /v:10.0.0.1`
provides:
![image](https://user-images.githubusercontent.com/7798433/106304933-4ccdc880-625c-11eb-827d-db29f2b482ba.png)

The domain (MyAD) is not prepended to the username in the form MyAD\ nor taken as the domain name below the "Sign in to:"

**Comment by akallabeth** [comment]
@Pivert thank you. Indeed, there was a bug fixed with https://github.com/FreeRDP/FreeRDP/pull/2051
can you try with nightly builds and check if that works for you>

**Comment by Pivert** [comment]
Hi,

Tested on 
`This is FreeRDP version 3.0.0-dev (fab649a)`
This is exactly the same problem & behaviour.

**Comment by akallabeth** [comment]
@Pivert please clarify, just tested the command line from above with my credentials against a windows 10 setup and it works as expected.

**Comment by akallabeth** [comment]
@Pivert ok, retried, and it looks windows 10 has some (strange) automation that strips the domain with certain conditions.
Try something like `/u:.\\domain\\user@wherever.org` and it will always show correctly.

**Comment by Pivert** [comment]
Thanks Akallabeth,
I did a try on the Windows10 I had the issue, and it does not seem to pass with this trick.
I do not have access to this PC any more, so I cannot try further. But it definitely seems to work in the above configuration, when the username contains an @
