### ISSUE TITLE
Error while compiling with DWITH_SSE2=ON

### ISSUE THREAD

**Issue by ShiZNizZLe** [FreeRDP/FreeRDP#6717]
Hi,

Following the cmake compile guide i've tried numerous times to install freerdp/freerdp2 to use a smartcard which we need to connect to a windows server 2008 r2.

clien info:
raspberry 3b+ with raspbian os (deb)
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4
- freerdp 2.2.0
- connected is a uzi smartcard (detectable through pcsc_scan)
- used terminal

These are the steps that I've followed according to the build guide:
- Installed all standard and optional dependencies, the only one failing is libfaac-dev.
  (Doesn't exist as library) Don't know if we need it for this problem though.

- Download FreeRDP 2.2.0:
   wget https://github.com/FreeRDP/FreeRDP/releases/download/2.2.0/freerdp-2.2.0.tar.gz

- Extract the tar.gz:
   tar xvzf freerdp-2.2.0.tar.gz

- CD to folder:
  cd freerdp-2.2.0

- Generate cmake files:
   cmake -G Ninja -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON                                      -DWITH_CUPS=ON -DWITH_PULSE=ON -DWITH_FAAC=OFF -DWITH_FAAD2=ON -DWITH_GSM=ON -DWITH_PCSC=ON -DWITH_SSE2=ON 

- Build en installeer de applicatie met cmake:
  cmake --build . --target install
--------------------------------------------------
PROBLEM 1
what happened:

When building i get this error:
https://imgur.com/a/rGEiM2g

what i expected:
Not getting this error and a succesful build/install

When i disable the sse2 option like this: -DWITH_SSE2=OFF
the project builds & installs, after which i can do this:

- xfreerdp /smartcard:Alcor /rfx /sec:tls /u:xxx /p:xxx /v:xxx.xxx.xxx.xxx

Then i'm connected to the server and can do what i want, but when i test the smartcard for the things i need, i get this error:
----------------------------------------------------------------
PROBLEM 2
What happened:

16:17:29:959] [1653:1889] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INVALID_PARAMETER [-2146435068]
[16:17:29:959] [1653:1889] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INVALID_PARAMETER (0x80100004)

What i expected:
The program can see the card and doesnt give this error.

I don't know if problem 2 is a result of sse2 not being accessible, so it might be a good idea to tackle the first problem first

Cheers

**Comment by akallabeth** [comment]
`SSE` on an `ARM` computer? Please don´t tell me the result is surprising ;)
as for your second issue, you might try `/client-build-numer:2600` which uses an older version of the rdp smartcard channel, but if that does not work you´re out of luck currently.

**Comment by ShiZNizZLe** [comment]
Well if it wasn't surprising i wouldn't be here asking the question ;)
I don't know what sse2 does, only that it needs to be used for redirecting smartcards with freerdp according to various forums.
This together with -DWITH_PCSC=ON. So you say i don't neet sse2 then? Gonna try your flag first
