### ISSUE TITLE
The mouse cursor changes when there are multiple monitors

### ISSUE THREAD

**Issue by jens254** [FreeRDP/FreeRDP#6729]
**Describe the bug**
When using Freerdp with multiple monitors, the mouse cursor changes from white to black when you switch from one monitor to the next. It reverts to the original when you start a program like Firefox.

Since i use Ubuntu, i think the curser changed between windows and Ubuntu.

**Application details**
* i used 2 monitors
* FreeRDP version
  * The problem occurred with versions 3.0 and 2.2
* Command line used
  * `xfreerdp /u:XXXXXX /p:XXXXX /d:windows /cert:ignore /timeout:30000 /v:192.168.30.150:3389 /f /multimon:force`
* Output of `xfreerdp /buildconfig`
`This is FreeRDP version 3.0.0-dev (42129ae30)`
`Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=ON WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=ON WITH_URBDRC_CLIENT=ON WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON`
`Build type:          Release`
`CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL`
`Compiler:            GNU, 9.3.0`
`Target architecture: x64`
* OS version connecting to (server side)
  * windows server 2019

**Environment (please complete the following information):**
* Linux 5.4.0-62-generic #70-Ubuntu SMP Tue Jan 12 12:45:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* The problem also occurred with a new Ubuntu version
  * ubuntu-20.04.1-desktop-amd64.iso was used to generate the USB for booting

**Comment by akallabeth** [comment]
@jens254 sorry, what?
using the thing in multimon mode in home office for months now without ever having seen a wrong cursor shape.
could you describe the test setup in a little bit more detail?
you don´t, by chance, have something grabbing focus away from `xfreerdp` running/installed?

**Comment by jens254** [comment]
To test the problem, I have the following structure:
* 2 monitors
* USB boot medium with Ubuntu. Installation file used: ubuntu-20.04.1-desktop-amd64.iso
* Ubuntu started from the USB stick
* /etc/apt/sources.list adjusted, I just added `universe multiverse`
`deb cdrom:[Ubuntu 20.04.1 LTS _Focal Fossa_ - Release amd64 (20200731)]/ focal main restricted universe multiverse`
`deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse`
`deb http://security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse`
`deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse`
* `apt update` performed
* `dpkg -i freerdp-nightly_3.0.0+0~20210116024833.906~1.gbp037e00_amd64.deb`
  * download from `https://ci.freerdp.com/job/freerdp-nightly-binaries/902/architecture=amd64,distribution=focal,label=pkg-deb/`
* `apt install -f` performed
* `/opt/freerdp-nightly/bin/xfreerdp /u:XXXXX /p:XXXXX /d:windows /cert:ignore /timeout:30000 /v:192.168.30.150:3389 /f /multimon:force` performed

After Freerdp has started and connected to Windows Server 2019, the mouse is white in Windows according to the standard. There are no programs open in Windows.
When I switch from one monitor to the other with the mouse, the mouse pointer changes from the Windows white to the Ubuntu black.
If I now open the Firefox program inside the session, the mouse pointer turns white again. If I change the monitor with the mouse pointer again, it turns black again.

I have found that the mouse pointer will revert to the Windows mouse pointer when it updates on the Windows side. For example when changing the window size or when something is loaded.

I have executed freerdp with `/ log-level: trace 2> & 1 | tee log.txt`. Where should I upload this file?

**Comment by akallabeth** [comment]
@jens254 ok, that is indeed strange, one of my work machines is ubuntu 20.04.
I´m using a gnome session though (sometimes openbox) and have not observed it with these.
Could you try something similar on your setup (start a openbox or gnome session) and retest?
For me it still sounds like something is stealing focus from freerdp

**Comment by jens254** [comment]
I did a new test.
* Installed with the USB boot medium Ubuntu 20.04.
* after updates with `apt update` I installed and tested freerdp again. The problem reappeared.
* then I installed openbox with `apt install openbox`
* When testing in openbox I noticed that Openbox has the same white mouse pointer as the Windows mouse pointer. I didn't notice anything here during testing, because I don't see any difference between the Openbox and Windows mouse pointer
* after this test I installed gnome in Ubuntu with `apt install vanilla-gnome-desktop`
* Now I have logged in with `GNOME under Xorg`. Here I noticed that gnome has a black mouse pointer. After I started freerdp here, the same error occurred again. If I change the monitor with the mouse, the mouse pointer changes from white to black again

I think that you can only see the error if in the session where freerdp is started, the mouse pointer is different from the white Windows mouse pointer.
I could test this again in Openbox, but I don't know how to adjust the mouse pointer here.

**Comment by akallabeth** [comment]
@jens254 ok, tried today with my ubuntu 20.04 machine, also working as expected...

**Comment by akallabeth** [comment]
Ok, closing as `not reproducible on 2 machines with debian and ubuntu`
