### ISSUE TITLE
socket in nonblocking mode busy loop read takes 100% cpu

### ISSUE THREAD

**Issue by akarl10** [FreeRDP/FreeRDP#6730]
The socket(s) used for the connections thru a rdp gateway are set to nonblocking. This leads to 100% cpu usage if the rdg gateway server is slow while connecting since rdg_read_all turns into a "busy loop"

https://github.com/FreeRDP/FreeRDP/blob/f5177ca7e710a02eb700a01ab09350fb1ddb18ea/libfreerdp/core/gateway/rdg.c#L313

To me it seems that rdg_read_all must not be used with a nonblocking socket since a "short" read will always lead to 100% cpu usage until all data arrived, and since we are waiting for network this takes ages in cpu terms. In practice rdg_read_all blocks the calling thread so having the socket in blocking mode would make no difference except a huge cpu usage drop.

**Comment by akallabeth** [comment]
Fixed with #6734
