### ISSUE TITLE
Feature request: Implement chunked encoding in rdg.c RDG_OUT_DATA

### ISSUE THREAD

**Issue by akarl10** [FreeRDP/FreeRDP#6731]
When using nginx as reverse proxy in front of a remotedesktop gateway server by default nginx sends data using chunked encoding to the client if the application server does not a content-length and the client sent the request with "Connection: keep-alive"

This of course create problems when reading the RDG_IN_DATA channel and how I discovered https://github.com/FreeRDP/FreeRDP/issues/6730.

A workaround (and tecnically in spec with microsofts protocoll specefication) is setting
```
 location = /remoteDesktopGateway/ {
# turn off chunked encoding
  chunked_transfer_encoding off;
# allow sending data immediatly server->client
  proxy_buffering off;
# allow sending data immediatly client->server
  proxy_request_buffering off;
  proxy_pass <backend>;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection $connection_upgrade_keepalive;
  proxy_set_header Host $host;
  proxy_set_header X-Forwarded-For $remote_addr;
}

```

**Comment by akallabeth** [comment]
@akarl10 could you create a pull request with the required changes?

**Comment by akarl10** [comment]
Well, I can try...
Since this requires "messing" around with BIO_read(rdg->tlsOut->bio I will at least try making so that adding websocket support will be possible using some of this work (https://github.com/FreeRDP/FreeRDP/issues/5602)
