### ISSUE TITLE
SCARD_E_INVALID_PARAMETER

### ISSUE THREAD

**Issue by ShiZNizZLe** [FreeRDP/FreeRDP#6732]
Hi,

When using a smartcard to connect to windows server 2008 r2 with raspbian using freerdp everything succeeds.
When we open a program to load info from the card we're getting this message:

16:17:29:959] [1653:1889] [ERROR][com.freerdp.channels.smartcard.client] - SCardGetAttrib failed with error SCARD_E_INVALID_PARAMETER [-2146435068]
[16:17:29:959] [1653:1889] [WARN][com.freerdp.channels.smartcard.client] - IRP failure: SCardGetAttrib (0x000900D8), status: SCARD_E_INVALID_PARAMETER (0x80100004)

**Steps:**
These are the steps that I've followed according to the build guide:

- Install dependencies:
   sudo apt-get install ninja-build build-essential git-core debhelper cdbs dpkg-dev autotools-dev cmake pkg-config xmlto libssl-dev docbook-xsl xsltproc libxkbfile-dev libx11-dev libwayland-dev libxrandr-dev libxi-dev libxrender-dev libxext-dev libxinerama-dev libxfixes-dev libxcursor-dev libxv-dev libxdamage-dev libxtst-dev libcups2-dev libpcsclite-dev libasound2-dev libpulse-dev libjpeg-dev libgsm1-dev libusb-1.0-0-dev libudev-dev libdbus-glib-1-dev uuid-dev libxml2-dev libgstreamer1.0-dev libgstreamer0.10-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-base0.10-dev libfaad-dev libfaac-dev
   sudo apt-get install libavutil-dev libavcodec-dev libavresample-dev
   sudo apt-get install libcunit1-dev libdirectfb-dev xmlto doxygen libxtst-dev
   sudo apt install libpcsclite1 pcscd pcsc-tools libusb-1.0-0-dev
   sudo apt install opensc

  - Download FreeRDP 2.2.0:
    wget https://github.com/FreeRDP/FreeRDP/releases/download/2.2.0/freerdp-2.2.0.tar.gz

  - Extract the tar.gz:
    tar xvzf freerdp-2.2.0.tar.gz

  - CD to folder:
    cd freerdp-2.2.0

    Generate cmake files:
    cmake -G Ninja -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=OFF -DWITH_PULSE=OFF -DWITH_FAAC=OFF -DWITH_FAAD2=ON -DWITH_GSM=OFF -DWITH_PCSC=ON -DWITH_SSE2=OFF CMAKE_INSTALL_PREFIX CMAKE_EXTRA_FLAGS

   - Build and install:
    cmake --build . --target install

   - Connect to the server:
     xfreerdp /smartcard:Alcor /rfx /sec:tls /u:xxx /p:xxx /v:xxx.xxx.xxx.xxx

(Also tried /client-build-numer:2600 like advised in a previous bug, which didn't do anything)

**Expected behavior**
pcsc_scan succesfully shows the card
Can read data from the inserted UZI card.

**Actual behaviour**
pcsc_scan succesfully shows the card
When we press the button to get data from the card freerdp shows the error mentioned earlier.

**more info**

To further dig in on the problem we turned debugging on.
It seems that it's trying to get an attribute: SCARD_ATTR_ATR_STRING 
Which causes the error

We also turned on the debugging of pcsc_lite, 
both logs are added as an attachment.

**Screenshots**

**Application details**
* FreeRDP 2.2.0
* Terminal

**Environment (please complete the following information):**
raspberry 3b+ with raspbian os (deb) (buster)
processor : 0
model name : ARMv7 Processor rev 4 (v7l)
BogoMIPS : 38.40
Features : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant : 0x0
CPU part : 0xd03
CPU revision : 4

![freerdpbuildconfig](https://user-images.githubusercontent.com/15122459/105054184-fb5e5600-5a71-11eb-9cd8-6029e1714764.PNG)
[pcsc_lite logging.txt](https://github.com/FreeRDP/FreeRDP/files/5836759/pcsc_lite.logging.txt)
[Freerdp log.txt](https://github.com/FreeRDP/FreeRDP/files/5836761/Freerdp.log.txt)

**Comment by akallabeth** [comment]
@ShiZNizZLe well, looks like the parameter required by your application is not supported? (either from pcsc or your card or the driver of your card, ...)
you might try `/client-build-number:2600` to force older RDP smartcard protocol which often does not read such parameters (but some applications do not work)

**Comment by ShiZNizZLe** [comment]
@akallabeth I compared the debug output of one instance with /client-build-number:2600 and one instance without the flag.
The problem stays the same unfortunately.

**I also sent a message to Ludovic Rousseau, the guy from pcsc-lite and he came up with this:**
_I do not see any call to SCardGetAttrib() in the pcscd log.
So the call is rejected on the client side.
I guess that the FreeRDP client on Linux does not call
SCardGetAttrib() correctly._

Is SCARD_E_INVALID_PARAMETER a return value from freeRDP itself or do you get this when pcsc-lite says it can't do what you ask of it?

**Comment by akallabeth** [comment]
@ShiZNizZLe I´ve checked the whole call tree and the only thing I could find was that `pbAttr = NULL` failed `PCSC_SCardGetAttrib_Internal`.
While I did not observe a call of that wrapper with `NULL` arguments I´ve created a branch fixing that here:
https://github.com/akallabeth/FreeRDP/tree/smartcard_null_attrib

could you try that out? Just build with the `dpkg-buildpackage` method on https://github.com/FreeRDP/FreeRDP/wiki/Compilation#linux-specifics and you have a fresh nightly package ready to be installed.
(`/opt/freerdp-nightly/bin/xfreerdp`)

**Comment by ShiZNizZLe** [comment]
Thanks!

Although i might need some help with this, i tried to build it with that method before but i can't seem to find what i'm doing wrong.
Can you tell me what's going on?
![Uploading nightly.PNG…]()

**Comment by ShiZNizZLe** [comment]
since the ss doesn't upload: https://imgur.com/a/AD3JzOf

**Comment by akallabeth** [comment]
you´re using an ancient branch ;)

git checkout smartcard_null_attrib

and you´re ready to go

Am 20.01.21 um 16:14 schrieb ShiZNizZLe:

**Comment by ShiZNizZLe** [comment]
It says it isn't a git repository or it isn't found. Sorry i'm a bit of a noob when it comes to git
![nightly2](https://user-images.githubusercontent.com/15122459/105337905-38922780-5bdb-11eb-8888-193b71c91b7f.PNG)

**Comment by ShiZNizZLe** [comment]
Downloaded the zip, looks like it's building now, will update tomorrow

**Comment by ShiZNizZLe** [comment]
Hi,

I generated 2 TRACE logs:
In FreerdpDebugOutput.log freerdp sets up the connection and shows the desktop (logged out before on the win server)
In FreerdpDebugOutput2.log i press the button to read the card (and possibly the reconnection to the desktop, stayed logged in)

the normal output shows this message:
![nightly3](https://user-images.githubusercontent.com/15122459/105470256-a0a74300-5c99-11eb-8e6b-6009f641a832.PNG)
[FreerdpDebugOutput.log](https://github.com/FreeRDP/FreeRDP/files/5854818/FreerdpDebugOutput.log)
[FreerdpDebugOutput2.log](https://github.com/FreeRDP/FreeRDP/files/5854819/FreerdpDebugOutput2.log)

**Comment by akallabeth** [comment]
@ShiZNizZLe 
1. the logs are missing `stderr`, did you redirect with `2>&1 |tee log.txt`?
2. could you retest (redownload and compile), did add additional logs written whenever this specific error is set by `freerdp`

**Comment by ShiZNizZLe** [comment]
1. what do you mean? i now used wlog to export the log from freerdp 2x. Do you need the pcscd one too you mean?
2. I can redownload and compile, which logs do you need then specifically?

**Comment by akallabeth** [comment]
@ShiZNizZLe no, the `WLog` is missing all errors (that means you did not capture these) 
Just run `xfreerdp <yourargs> /log-level:debug 2>&1 |tee log.txt` and send me that one.

**Comment by ShiZNizZLe** [comment]
ah i get you, will do

**Comment by ShiZNizZLe** [comment]
steps:
unzip FreeRDP-smartcard_null_attrib.zip 
cd FreeRDP-smartcard_null_attrib/
ln -s packaging/deb/freerdp-nightly debian
sudo dpkg-buildpackage

xfreerdp /smartcard:Alcor /rfx /u:xxx /p:xxx /v:xxx.xxx.xxx.xxx /log-level:debug 2>&1 |tee log.txt

somewhere around 26:29 i open up the smartcard reader program

[log(2).txt](https://github.com/FreeRDP/FreeRDP/files/5855531/log.2.txt)

**Comment by akallabeth** [comment]
Ok,

I don´t see any of the freerdp log messages I added so the error is from 
the PCSC SCardGetAttrib function.


I´ll check the PCSC source of possible causes.

**Comment by ShiZNizZLe** [comment]
oh can you view the source code of pcsclite?
Good idea :)

**Comment by akallabeth** [comment]
@ShiZNizZLe looks like the error is from an invalid argument, but I fail to see where there is one.
I pushed another commit to the branch, could you download (yet) again and retry?

**Comment by ShiZNizZLe** [comment]
fresh and new ;)
[log_freerdp.txt](https://github.com/FreeRDP/FreeRDP/files/5866931/log_freerdp.txt)

I could also generate a new pcsc log if you want, don't know if that helps or not

**Comment by akallabeth** [comment]
@ShiZNizZLe ok, narrowed it down to a different call convention of `SCardGetAttrib` between windows and PCSC.
I´ve added a new log entry.
Retry and check for lines like `PCSC_SCardGetAttrib_Internal: pbAttr=<pointer>, cbAttrLen=<size>`

Then check these are valid:
1. if `pbAttr=null` then `cbAttrLen != 0xFFFFFFFF`
2. if `cbAttrLen == 0xFFFFFFFF` then `pbAttr != null`

**Comment by akallabeth** [comment]
@ShiZNizZLe ok, suspicion confirmed. See referenced pr #6751 for a fix.

**Comment by ShiZNizZLe** [comment]
so i have to wait till the merge request is completed?
and where do i need to download the package again after that?

**Comment by akallabeth** [comment]
@ShiZNizZLe just download the code from my branch https://github.com/akallabeth/FreeRDP/tree/smart_attr_fix (referenced in the pull request)

**Comment by ShiZNizZLe** [comment]
ah okay, didn't see that, thanks. 
Going to try it out this afternoon
