### ISSUE TITLE
SCARD_E_INVALID_PARAMETER

### ISSUE THREAD

**Issue by ShiZNizZLe** [FreeRDP/FreeRDP#6756]
The bug should be solved but still appears.
Downloaded the master branch, because i saw that the fix was merged and builded with cmake.
Just to be sure i also checked the modified date of smartcard_operations.c
which was 26-01-21 12;33 (3 hours ago) so that seems to be correct.
i clicked the check card button a few times resulting in the same error as far as i can see
Here's the log again:
[log_freerdp.txt](https://github.com/FreeRDP/FreeRDP/files/5874128/log_freerdp.txt)

**Comment by akallabeth** [comment]
@ShiZNizZLe tricky one. From the log I found a remaining issue, could you try https://github.com/akallabeth/FreeRDP/tree/smart_e_invalid ?

**Comment by ShiZNizZLe** [comment]
build it with these steps again:
unzip FreeRDP-smart_e_invalid.zip
cd FreeRDP-smart_e_invalid/
ln -s packaging/deb/freerdp-nightly debian
sudo dpkg-buildpackage

[log_freerdp.txt](https://github.com/FreeRDP/FreeRDP/files/5878639/log_freerdp.txt)

btw this is the button i need to press to check if the card is inserted:
![Knipsel](https://user-images.githubusercontent.com/15122459/105963710-9ca46800-6081-11eb-863c-31241508df99.PNG)

As you can see, it says: 
card in reader = false

This is a self made program used wether to check a dll that we're using can read the card.
through windows it all works fine but when using the raspberry workstations we have this problem right here.

**Comment by akallabeth** [comment]
are you sure you´re using the correct branch?

**Comment by ShiZNizZLe** [comment]
uhm, well i downloaded the zip of the link you sent: https://github.com/akallabeth/FreeRDP/tree/smart_e_invalid 
and then followed the steps i mentioned earlier. Don't know if  sudo dpkg-buildpackage gets files from another branch or something?
in other words: are the steps i took correct?

**Comment by ShiZNizZLe** [comment]
this is what the folder looks like after i installed everything;
![newtest](https://user-images.githubusercontent.com/15122459/106001925-d04ab680-60b0-11eb-9e10-f867d28c2988.PNG)
![newtest2](https://user-images.githubusercontent.com/15122459/106001928-d0e34d00-60b0-11eb-9407-ba4dd3ecf109.PNG)

**Comment by akallabeth** [comment]
@ShiZNizZLe ok, I´ve added a very prominent log message in https://github.com/akallabeth/FreeRDP/tree/smart_e_invalid2
could you retry with that one?
the steps you describe are fine (`dpkg-buildpackage` uses the sources you have locally) but I fail to see how you end up in that specific code path, so this might help

**Comment by ShiZNizZLe** [comment]
ah okay i get you.
Well i don't know exactly how the programming of the button works, as a collegue of mine designed that program.
That button is the trigger for the invalid parameter error i think. i can see if i can get you the functionality of the button if you need that.

But i'll try the the new branch first.
Although what i don't get:
why do the nightly files in the 1st screenshot appear after excecuting dpkg-buildpackage if it should only use the local files?

**Comment by ShiZNizZLe** [comment]
it even says building nightly, which i don't understand then
![afbeelding](https://user-images.githubusercontent.com/15122459/106004555-9e871f00-60b3-11eb-8a49-3496fae7473a.png)

**Comment by akallabeth** [comment]
@ShiZNizZLe because you´re building the nightly package ;)
that is the same we do on our build machines.
You installed the `.deb` files created, yes? (sorry, have to ask)

**Comment by akallabeth** [comment]
and yes, a small sample app that triggers the issue could help a lot as I then can reproduce locally and do not require your help for checking.

**Comment by ShiZNizZLe** [comment]
yes i see the deb files, i'm now gonna generate a log for you. 
Now i understand :)

Uhm well the problem is that you would also need the uzi smartcard (which we use) to test it yourself. I can ask if i can send you the important parts of the code, i think that comes in handy too or not?

**Comment by ShiZNizZLe** [comment]
[log_freerdp.txt](https://github.com/FreeRDP/FreeRDP/files/5881038/log_freerdp.txt)

here you go

**Comment by akallabeth** [comment]
@ShiZNizZLe as expected, the log message is missing.
how do you run the installed binary? nightly installs to `/opt/freerdp-nightly/bin/xfreerdp`

**Comment by ShiZNizZLe** [comment]
i think that link makes it complicated? 
i ran it from the folder in screenshot 2 because i thought that was were it would build.
i now think i have to go to

/home/pi/freerdpnightly/FreeRDP-smart_e_invalid2
then to the linked debian folder and then to the opt folder, which is here:
/home/pi/freerdpnightly/FreeRDP-smart_e_invalid2/debian/freerdp-nightly/opt/freerdp-nightly/bin

why is it in such a weird place?

**Comment by akallabeth** [comment]
@ShiZNizZLe I think you do it a bit weiredly.
1. Build the debian packages with `dpkg-buildpackage`
2. Install the `.deb` files generated with `dpkg -i <name>.deb`
3. Run `/opt/freerdp-nightly/bin/xfreerdp`

as for why we install in `/opt`, because the nightly should not override stable versions shipped with your distro.

**Comment by ShiZNizZLe** [comment]
well i just followed the instructions right here:
https://github.com/FreeRDP/FreeRDP/wiki/Compilation

so i just have to 
-cd to the extracted zip and then 
-dpkg-buildpackage
-install all debs
-run
?

**Comment by akallabeth** [comment]
@ShiZNizZLe yes.
please also paste the command line you use (strip passwords etc)

**Comment by ShiZNizZLe** [comment]
okay, i'll do that tomorrow morning!

**Comment by ShiZNizZLe** [comment]
well when i try it your way i get this?
haven't found a solution how to solve it
![afbeelding](https://user-images.githubusercontent.com/15122459/106106673-2b7ab880-6146-11eb-9aa2-4ec04ff3ee62.png)

here are the extracted files where im trying to do dpkg-buildpackage
![afbeelding](https://user-images.githubusercontent.com/15122459/106106744-48af8700-6146-11eb-82c7-21459657896f.png)

**Comment by akallabeth** [comment]
@ShiZNizZLe of course you need the `ln -s` step, I was just checking if you were calling the correct binary, because I´ve debugged the stuff yesterday and you were really using the wrong binary as the required log messages were missing.
I´ve created https://github.com/FreeRDP/FreeRDP/pull/6757 to address this now as I was able to create a test code that exposed the issue.
Please build that source:
1. Follow the steps from the `dpkg-buildpackage` in the wiki
2. install the resulting `.deb` packages
3. test with `/opt/freerdp-nightly/bin/xfreerdp`

**Comment by ShiZNizZLe** [comment]
do i also have to do this one then? because i didn't do that before or do i need to do the rest of the steps from your extracted branch like in the screenshot above?:
sudo apt build-dep freerdp2-x11

Sorry it isn't all that logical to me

**Comment by ShiZNizZLe** [comment]
finally,

did it without sudo apt build-dep freerdp2-x11
then unpacked freerdp-nightly_3.0.0_armhf.deb
then  freerdp-nightly-dbg_3.0.0_armhf.deb
and then freerdp-nightly-dev_3.0.0_armhf.deb

now i can run it from opt...
maybe handy to add the steps to the compilation wiki?
because i've always missed that i should depackage the debs

**Comment by ShiZNizZLe** [comment]
everything succeeded, only now the log seems nowhere to be found

![newtest3](https://user-images.githubusercontent.com/15122459/106119144-27a26280-6155-11eb-86e9-e205f94a0e16.PNG)

**Comment by ShiZNizZLe** [comment]
ah i could'nt write to the folder apparently, but here it is
[log.txt](https://github.com/FreeRDP/FreeRDP/files/5886594/log.txt)

**Comment by akallabeth** [comment]
@ShiZNizZLe ok, good. then we finally have a fix.

**Comment by akallabeth** [comment]
@ShiZNizZLe ok, now I see the error. you call the wrong `xfreerdp` binary!
calling without path (like `xfreerdp` ) will call the binary that is found in your `PATH`
either start with `/opt/freerdp-nightly/bin/xfreerdp` or (in your case from the same folder) with `./xfreerdp`

**Comment by ShiZNizZLe** [comment]
huh why do i have to put ./ before it even though i'm already in that folder, funny :')
gimme a sec

**Comment by ShiZNizZLe** [comment]
then i get this message:
![afbeelding](https://user-images.githubusercontent.com/15122459/106138212-1d3f9300-616c-11eb-92a0-82382d134a6d.png)

**Comment by ShiZNizZLe** [comment]
then i get this message 
![afbeelding](https://user-images.githubusercontent.com/15122459/106138278-347e8080-616c-11eb-941e-86a2a5a62c6a.png)

**Comment by akallabeth** [comment]
@ShiZNizZLe we are getting there.
check where your `libasan.so` is located (run `find /usr/lib -name "*asan*so*"` to get a list of files matching) and start with `LD_PRELOAD=<path_to_libasan>/libasan.so ./xfreerdp <yourargs>`
I´ve got 2 installed on my machine, so I get
```
/usr/lib/x86_64-linux-gnu/libasan.so.6
/usr/lib/x86_64-linux-gnu/libasan.so.6.0.0
/usr/lib/x86_64-linux-gnu/libasan.so.5.0.0
/usr/lib/x86_64-linux-gnu/libasan.so.5
```
and you need to check which one works on your machine.
obviously you will have different paths as you are on arm.

something similar to `/usr/lib/aarch64-linux-gnu/libasan.so.5`

**Comment by ShiZNizZLe** [comment]
i guess i have to pick the middle one then
![afbeelding](https://user-images.githubusercontent.com/15122459/106139783-292c5480-616e-11eb-9536-2018f36fcd97.png)

**Comment by ShiZNizZLe** [comment]
i get this when i opened up the connection. i see the desktop very shortly and closes immediately after 

![afbeelding](https://user-images.githubusercontent.com/15122459/106140621-4ada0b80-616f-11eb-8f73-51b00c137a68.png)

**Comment by akallabeth** [comment]
@ShiZNizZLe ok, good, the application is now finally running (and the correct version too, yea!)
1. So, first, you can ignore the `ASAN` warnings that have something with `X11` in it (these are from the way `X11` cleans up resources)
1. There seems to be an issue with your RDP server, try running with `/log-level:debug` to get some more information why this happens.
2. You might skip the last step and just add `/network:auto /gfx:avc444` and check if the connection works then. (RDP has some very very strange settings, so best try to set them to automatic detection whenever possible)

**Comment by akallabeth** [comment]
@ShiZNizZLe ok, there is an issue on current master, I´ve pushed a fix for that to the pull request branch

**Comment by ShiZNizZLe** [comment]
with option 3 it quits again
i'll get you a log file

**Comment by ShiZNizZLe** [comment]
[log_freerdp(1).txt](https://github.com/FreeRDP/FreeRDP/files/5887377/log_freerdp.1.txt)

**Comment by akallabeth** [comment]
@ShiZNizZLe I´ve already written it, I´ve pushed a fix for the thing you see to the branch, please redownload

**Comment by ShiZNizZLe** [comment]
this one right? https://github.com/akallabeth/FreeRDP/tree/smart_e_invalid2 (because i don't see a recent file change)

**Comment by akallabeth** [comment]
@ShiZNizZLe no, #6757 , the pull request

**Comment by ShiZNizZLe** [comment]
should i do something like this to do that? git fetch origin pull/6757/head:something
never pulled a request before either

**Comment by ShiZNizZLe** [comment]
sorry i really don't know how to get the files from there, could you guide me through it, this is all a bit new for me...

**Comment by ShiZNizZLe** [comment]
i think i got it gimme a sec

**Comment by akallabeth** [comment]
@ShiZNizZLe on the top there is a link to the source branch, wher you can download the zip, on the bottom there are instructions on how to check it out.

**Comment by ShiZNizZLe** [comment]
this one you mean right?
![afbeelding](https://user-images.githubusercontent.com/15122459/106155700-3e5eae80-6181-11eb-9396-cd8e0eda773a.png)

its a bit frustrating why i cant seem  to use git tho...
![afbeelding](https://user-images.githubusercontent.com/15122459/106156002-55050580-6181-11eb-9861-4fb3af986f5b.png)

**Comment by ShiZNizZLe** [comment]
works
![afbeelding](https://user-images.githubusercontent.com/15122459/106156352-b75e0600-6181-11eb-98de-6c3d8a12c75f.png)

**Comment by ShiZNizZLe** [comment]
lol now it does this again, i'm pretty sure i didn't miss anything right?
![afbeelding](https://user-images.githubusercontent.com/15122459/106157522-140df080-6183-11eb-9cd2-65cb14b3b53f.png)

**Comment by akallabeth** [comment]
@ShiZNizZLe 
1. you forgot `ln -s`
2. why `sudo dpkg-buildpackage`? building never requires root

**Comment by ShiZNizZLe** [comment]
1. oops sorry
2. because just to be sure i guess
3. i only see a link to the community guidelines on the pull request page

**Comment by akallabeth** [comment]
Ok, might be collapsed, but here:
![Screenshot from 2021-01-29 09-20-20](https://user-images.githubusercontent.com/3472254/106249943-46ffc500-6213-11eb-9d97-1acc1a742ea7.png)

**Comment by ShiZNizZLe** [comment]
ah, didn't trust clicking anywhere near merging, thanks!

**Comment by akallabeth** [comment]
@ShiZNizZLe no worries, you don´t have the permissions ;)

**Comment by ShiZNizZLe** [comment]
oh well thats the problem, can't click it :')
![afbeelding](https://user-images.githubusercontent.com/15122459/106250184-97772280-6213-11eb-9d64-e5c87a2c1c40.png)

**Comment by ShiZNizZLe** [comment]
also can't check out apparently
![afbeelding](https://user-images.githubusercontent.com/15122459/106250844-76fb9800-6214-11eb-9228-f8fed37aaff3.png)

**Comment by ShiZNizZLe** [comment]
building now,
hopefully this is fine

![afbeelding](https://user-images.githubusercontent.com/15122459/106274620-d49fdc80-6234-11eb-9b18-8ea3d6b00562.png)

**Comment by ShiZNizZLe** [comment]
got a new log for you :)
[log_freerdp(2).txt](https://github.com/FreeRDP/FreeRDP/files/5894329/log_freerdp.2.txt)

**Comment by ShiZNizZLe** [comment]
i can give you a zip with the solution and excecutable if you want?
the dll's are made by aet europe https://www.aeteurope.com/
the problem is that we can't see what we're doing wrong with these dll's, because we can't see the code.
I don't know if this will help you in any way?
The only problem is that you don't have the 'uzi' smartcard that we have to use.

**Comment by ShiZNizZLe** [comment]
In log_freerdp(2).txt we see a strange message. 
at .... SCardGetAttrib for dwAttrId: SCARD_ATTR_ATR_STRING is requested which is handled correctly. We don't see any problem in our own logs anymore.
but at ...  there is a SCardDisconnectS with  dwDisposition: SCARD_LEAVE_CARD.
We did not remove the card...
at ... there is message  SCardGetStatusChangeA failed with error SCARD_E_TIMEOUT [-2146435062]
