### ISSUE TITLE
Running on Windows, can't connect to a Windows server which uses per-device RDS licensing/CALs

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#6759]
**Describe the bug**
When using FreeRDP on Windows (Windows 10), and connecting to a Windows Server (2016) with per-device RDS licensing/CAL, the connection fails. The only error is `ERRCONNECT_CONNECT_TRANSPORT_FAILED`.

On the Windows server side, it even crashes some components ("The Windows logon process has unexpectedly terminated.").

On macOS and Linux, this behavior is not reproducible, everything is working fine.

The problem is primarily located in the `saveCal()` function on the `libfreerdp/core/license.c` file (see details below).

**To Reproduce**
1. Configure per-device CALs on the Windows Server RDS;
2. Connect to the server using a client which uses FreeRDP on Windows end-user device.
3. Can't login.

**Expected behavior**
When using per-device CALs, FreeRDP is supposed to receive the license/CAL information and store it as a file on the `ConfigDir/licenses` directory (on Windows: `%APPDATA%\freerdp\licenses`).

It first creates a file called `[long hex string].cal.new` where it stores the data it receives from the server, and then renames it to `[long hex string].cal` (removing the `.new` suffix).

It later uses this file to retrieve licensing information to use in the login process somehow (haven't investigated this part of the process).

**Screenshots**
n/a

**Application details**
* FreeRDP version: from the repository, branch stable-2.0
* OS version connecting to: Windows Server 2016

**Environment (please complete the following information):**
 - OS: Windows only (not on macOS/Linux, not tested on Android)
 - Version/Distribution: Windows 10
 - Architecture: amd64

**Additional context**
As stated above, the culprit is the `saveCal()` function on the `libfreerdp/core/license.c` file.

This function builds the path for the temporary and final file names by calling `GetCombinedPath()` on several occasions.

It then writes to the temporary file (with the `.new` suffix) and finally calls `MoveFileEx()` to rename the file from the temporary name to the final one.

On Linux/macOS this works fine, because `MoveFileEx()` is actually defined to be `MoveFileExA()` (ANSI version of the function).

On Windows, it uses `MoveFileExW()` (the Unicode version of the function), but uses the `char*` variables returned by `GetCombinedPath()` all the same. Later, `MoveFileExW()` calls `ConvertFromUnicode()` with these parameters, garbling the paths, and then calls `MoveFileExA()`, which finally calls `rename()` with the invalid values and fails with error 0x2 (`ERROR_FILE_NOT_FOUND`).

The CAL/license file is never renamed to the final name (without the `.new` extension), and it can't be used later on, causing the login to fail.

**Suggested action**

By changing the `saveCal()` function on the `libfreerdp/core/license.c` file to call `MoveFileExA()`, it fixes the problem.

Since all the values used inside `saveCal()` are `char` arrays, this will work correctly.

Linux and macOS will still work correctly since they already use `MoveFileExA()` indirectly.

**Comment by mfleisz** [comment]
@vscfreire can you give #6761 a try and see if this fixes your issue?

**Comment by vscfreire** [comment]
> 
> 
> @vscfreire can you give #6761 a try and see if this fixes your issue?

Just tested #6761 and it fixes the issue. It's now working correctly.

Thanks!
