### ISSUE TITLE
App on Windows not closing the xfreerdp process on Linux when it exits

### ISSUE THREAD

**Issue by JohnKendrick** [FreeRDP/FreeRDP#6773]
I am using freerdp to access a windows 10 virtual machine.  When I access the Windows desktop everything appears to work as I would expect.  However, when I access and app I see behaviour I dont quite understand.  

Lets say I am using excel. 

xfreerdp /d: /u:John /p:************ /v:192.168.122.62 +auto-reconnect +clipboard +home-drive -wallpaper /scale:100 /dynamic-resolution /span /wm-class:Microsoft Excel /app:C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE /app-icon:/home/john/.local/share/winapps/apps/excel-o365/icon.svg

This is successful and I can use the excel image succesfully.  However when I close excel, by hitting X, the linux command does not return.  This only happens if I am using the /app option.   In addition I see a small white rectangle on my screen, sometimes in the top left of my desktop and sometimes in the centre of the desktop.  This white rectangle appears just before the window running Excel appears, but it doesn't disappear when I close Excel.  It only goes when I kill the xfreerdp process.  This behaviour is seen with all apps I have tried.

The expected behaviour is to close the app and the shutdown the freerdp process on linux.  I also do not expect to see the little white rectangle.

I am running 3.0.0-dev version of freerdp (freerdp --version).  The operating system is ArchLinux.  My desktop is xfce.  I have tried both the AUR versions of freerdp and I have compiled the latest version myself.  Both give the same results.  Below is the information from git.

git describe --tags
2.0.0-582-g95b7f3b46

The version I compiled was made with;
cmake -DCMAKE_INSTALL_PREFIX='/usr' \  
        -DCMAKE_INSTALL_LIBDIR='lib' \
        -DCMAKE_BUILD_TYPE='None' \
        -DPROXY_PLUGINDIR='/usr/lib/freerdp2/server/proxy/plugins' \
        -DWITH_DSP_FFMPEG=ON \
        -DWITH_FFMPEG=ON \
        -DWITH_PULSE=ON \
        -DWITH_CUPS=ON \
        -DWITH_PCSC=ON \
        -DWITH_JPEG=ON \
        -DWITH_SERVER=ON \
        -DWITH_SWSCALE=ON \
        -DWITH_CHANNELS=ON \
        -DWITH_CLIENT_CHANNELS=ON \
        -DWITH_SERVER_CHANNELS=ON \
        -DWITH_VAAPI=ON \
        -DCHANNEL_URBDRC_CLIENT=ON \
        -Wno-dev \
        -B build \
        -S .

**Comment by JohnKendrick** [comment]
I think I understand more about this problem now.  It seems to me that this is not a client side problem, but rather a windows remote desktop server issue.  The small white rectangle I referred to in the original post is a result of the RemoteApp Marker Window that is created by the remote session.  It seems to stay there until the process disconnects on the Windows server.  (Disconnecting and Exiting are not the same; Exit takes place first)

One approach to getting the server process to disconnect is to follow this link;
https://techcommunity.microsoft.com/t5/microsoft-security-and/terminal-services-remoteapp-8482-session-termination-logic/ba-p/246566

More information can be obtained here; https://social.technet.microsoft.com/Forums/en-US/9c36889d-2cd7-4fc4-85dd-7a1711fb05f5/session-is-not-disconnected-after-closing-remoteapp?forum=winserverTS

I will close this bug.

**Comment by joezhouchenye** [comment]
Why only 4 options are shown? The last one "Set time limit for logoff of RemoteApp sessions" is not available.
