### ISSUE TITLE
Feature Request: Add command line option to pass time zone or UTC offset

### ISSUE THREAD

**Issue by camjcorley** [FreeRDP/FreeRDP#6780]
Issue:
I host an html5 wrapper for FreeRDP that allows users to connect via web browser. The FreeRDP software is executed on a server in a time zone that is different from some of the users. Because of this, the timezone always matches the server time and not the local time for the user.

Request:
Please provide the ability to pass the time zone or UTC offset as an option to the FreeRDP executable via command line. Specifically we use the wfreerdp.exe build because we host on a Windows server.

**Comment by akallabeth** [comment]
Pull requests are welcome, but we currently will not implement this ourselves.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/pull/10391
