### ISSUE TITLE
Freeze on welcome screen for a 5 minutes

### ISSUE THREAD

**Issue by pestoffne** [FreeRDP/FreeRDP#6790]
Server: Windows 10 Enterprise amd64 10.0.18363
Client: Debian 10 amd64
FreeRDP: version 2.2.0

**To Reproduce**
1. Connect to server
./xfreerdp /v:192.168.54.146 /u:Toster /p:11111111 /cert-ignore /log-level:trace | tee log.txt
2. Click "Start menu"->"Power"->"Disconnect"
3. Connect to server with same command

**Actual behavior**
It freezes on the welcome screen for 5 minutes. After this freeze, I can use remote computer and RDP connection is fine.

**Expected behavior**
Welcome screen disappears in less than 30 seconds.

**Windows event log**
There are no errors and no warnings, just a lot of successful logon and logoff messages while freezing.

**FreeRDP log**
There are a lot of duplicate lines in the FreeRDP log while freezing:
```
[23:59:24:431] [17907:17909] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
[23:59:24:431] [17907:17909] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
[23:59:24:446] [17907:17909] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
[23:59:24:446] [17907:17909] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
...
```

**Comment by pestoffne** [comment]
Full log of second connection
[deb-10-4-freerdp-log.zip](https://github.com/FreeRDP/FreeRDP/files/5931872/deb-10-4-freerdp-log.zip)

**Comment by akallabeth** [comment]
well, the log tells there is no freeze on the client side. this might be a server side issue (windows sometimes takes ages to log on, even if the session is still active)
the lines you mention just tell that the client is updating the screen with the most recent data from the server.

**Comment by pestoffne** [comment]
The issue has been resolved on server side by installing a few mandatory Windows updates and rebooting. Thank you.
