### ISSUE TITLE
I can redirect usb web camera?

### ISSUE THREAD

**Issue by DJs3000** [FreeRDP/FreeRDP#6800]
Sorry to ask a question here, but I do not know where to ask it. 
TS: Windows server 2019
RDP client on Linux(xubuntu 20.04): FreeRDP 2.2.0 (n/a)
Need redirect sound, microphone, and usb web camera. Sound and microphone work perfectly, but how you can throw the camera? What I just haven't tried. RDP v8 on Windows can natively redirect web camera. Help please.

**Comment by akallabeth** [comment]
Hi, you can use `/usb:dev,id:0000:1111` and hope it works.
`[MS-RDPECAM]`, that is high level camera stream redirection, is currently not supported.

**Comment by akallabeth** [comment]
See #4971
