### ISSUE TITLE
Testing FreeRDP /dynamic-resolution compatibility with an XRDP prototype, need debugging assistance.

### ISSUE THREAD

**Issue by Nexarian** [FreeRDP/FreeRDP#6801]
**Is your feature request related to a problem? Please describe.**
Yes. I've been working on implementing resize-on-the-fly (/dynamic-resolution) compatibility in XRDP: https://github.com/neutrinolabs/xrdp/issues/448

I have tested my branch here: https://github.com/Nexarian/xrdp/commits/devel with the new Microsoft Remote Desktop clients on Windows 10 (Note, not MSTSC, the version installed from the App Store) and the Mac OS client, and it works great! Dynamic resizing is close at hand with XRDP!

Unfortunately, it does not seem to work with the latest versions of FreeRDP. I've tested this on both Mac OS ->Ubuntu as well as pure Ubuntu (Two 20.04.2 VMs connecting to each other hosted on VirtualBox on Windows 10 Pro)

The first problem is a weird "oscillation" of FreeRDP -- The window will resize to what I resized the screen to, then flip back to what it was before I resized the window, and then back and forth. It'll either do this forever, or eventually disconnect.

Otherwise, after login, the screen may resize a couple times, or it may oscillate. Either way, you only get a handful of resize attempts before the client disconnects after a resize attempt. Sometimes, however, it does succeed, though it's not common.

**Describe the solution you'd like**
I'd like to work with the maintainers of FreeRDP to diagnose whether or not this is something that needs to be corrected on the XRDP side or if it needs to be fixed on the FreeRDP side before XRDP commits this feature.

**Describe alternatives you've considered**
Another option, since this works with two different Microsoft clients reliably, is to merge this into XRDP and then leave the debugging of the compatibility of `/dynamic-resolution`

**Additional context**
I've noticed that this issue is a lot less stable when I use `/sec-rdp` -- So I suspect this has something to do with the reliability of the network socket connections here. Possibly a threading issue

Also note that the XRDP session is undamaged by this. I can reconnect with either FreeRDP or the Microsoft Remote Desktop clients.

Here is a log of a recent attempt: [FreeRDP debug log.txt](https://github.com/FreeRDP/FreeRDP/files/5949044/FreeRDP.debug.log.txt)

**Comment by akallabeth** [comment]
Hi @Nexarian reach me at freerdp IRC or directly on my nick:matrix.org or any of the mail addresses in my commit messages.
from the rough description I´d check when the local resize is actually done, `freerdp` uses a `hack` to allow dynamic resizing in window mode (ignore changes for some time to prevent this feedback loop), so the processing delay might just be too high.

The following conditions trigger sending a `MonitorLayout PDU`:
1. Monitor layouts change (plug/unplug, reorder, ...)
2. The RDP connection reaches state `Activated`
3. With `GFX` active on `GraphicReset`
4. Periodic timer `OnTimer`

Easiest way to check if this is the reason, change `RESIZE_MIN_DELAY` in `xf_disp_sendResize` to something higher

**Comment by Nexarian** [comment]
I tried the following values with interesting results. At present it's set to 200 ms.

400 ms: No Effect, still just as unstable.
600 ms: More stable. Fails every so often but not terrible.
1000 ms: Now we're cooking! Very few oscillations and extremely stable. I had to play with it for several minutes before it exited.
1500 ms: This is actually somehow worse than 1000 ms...
5000 ms: This is about as stable as 1000 ms, but with more oscillations.

So I suspect the sweet spot here is somewhere around 800 - 1200 ms. However, it's not a perfect fix. As you mentioned, this is a hack.

I suspect some logic could be added here around "desired" window size. The reason these feedback loops can happen is if the server and the client differ. However, in 90% of cases that's not going to be a problem. So perhaps what we could do is have detection logic for if the server and the client agree that when the window dragging stops (that is the final resolution the client side is achieved) if the server EVER says it can support it, we stop the feedback loop.

Is there some change XRDP could make to make this more stable?

**Comment by hardening** [comment]
@Nexarian just curious, when you use mstsc what kind of resizing requests do you get ? Is every intermediate resolution sent or it's rather like what we're trying to do with freerdp and just send the final size ?

**Comment by hardening** [comment]
I think I know the answer as when freerdp was sending every intermediate sizes, it was just crashing the whole server (blue screen and login greeter stuck), but perhaps I'm wrong...

**Comment by Nexarian** [comment]
First off as best I can tell MSTSC doesn't support this feature. For some reason Microsoft never added it to the MSTSC we all know and love. You have to use "Microsoft Remote Desktop" which is something that comes from the Windows 10 App Store. Also similarly, "Microsoft Remote Desktop" available for Mac OS supports this as well.

I will check the logs and get back to you when I test the patch.

**Comment by Nexarian** [comment]
@hardening You're correct. It doesn't send the intermediate sizes, only the final size. Windows has some sort of final drag detection logic. Perhaps not technically ideal, but a far smoother user experience.

**Comment by Nexarian** [comment]
Just tested the PR. It's a massive improvement. Not quite as smooth as the Microsoft Remote Desktop client, but still very good!
