### ISSUE TITLE
Audio-mode is not stable

### ISSUE THREAD

**Issue by ugurkebir** [FreeRDP/FreeRDP#6808]
I'm using xfreerdp to login from linux to linux machine(Debian bullseye to Ubuntu 20.04). In order to redirect microphone and audio, I have to try "/audio-mode:0" then "/audio-mode:1". Sometimes I repeat this process several times. 

The commands that I use are as follows:
```
xfreerdp -sec-nla +clipboard -wallpaper /audio-mode:0|1 /sound /microphone /cert-ignore /u:<user /p:<pass> /v:192.168.5.8 /f
xfreerdp -sec-nla +clipboard -wallpaper /audio-mode:0|1 /sound /microphone /gfx:rfx /cert-ignore /u:<user /p:<pass> /v:192.168.5.8
xfreerdp -sec-nla +clipboard -wallpaper /audio-mode:0|1 /sound /microphone -bitmap-cache -offscreen-cache -glyph-cache /gfx:rfx /cert-ignore /u:<user /p:<pass> /v:192.168.5.8
```

After trying a few times by setting the / audio-mode command parameter to 0 and 1 in the commands, I can direct the sound and microphone. How can I get this stable?

**Comment by akallabeth** [comment]
well, that sounds like a server problem to me, have not observed such behavior until now against our windows and ogon test setups.
Maybe ask `xrdp` (I assume you use that server side?)

**Comment by ugurkebir** [comment]
Yes, I use xrdp. What should I use? Do you have any solution suggestions?
