### ISSUE TITLE
TLSv1 alert internal error

### ISSUE THREAD

**Issue by AdmiralNemo** [FreeRDP/FreeRDP#681]
I recently upgraded to FreeRDP 1.0.1 after using FreeRDP-old for quite some time, but I am no longer able to connect to any of my servers. They are all Windows Server 2008 R2 with NLA required. Whenever I try, I get the following error:

```
SSL_read: Failure in SSL library (protocol error?)
SSL_read: error:14094438:SSL routines:SSL3_READ_BYTES:tlsv1 alert internal error
```

I am using Gentoo Linux, OpenSSL 1.0.0j and FreeRDP git commit 9b6231c08830976abcbcb7cbf536f9c04411ce7f.

On my machine at home, I do not get this error. I tried building with the same environment (OpenSSL 1.0.0h, FreeRDP git commit 7fe240df119dcf585f97e3b696c863b49be44b9a), but still no luck.

What additional information can I provide to find the cause of this problem and hopefully get back to a working FreeRDP installation?

**Comment by flickerfly** [comment]
I found this can occur simply because of an expired password as well.

**Comment by bmiklautz** [comment]
@flickerfly haven't seen that one ;). Thanks or the hint!

**Comment by kiav** [comment]
I used /sec:tls to solve the problem.

`$ cat /etc/system-release 
ALT Linux 7.0.5 KDesktop  (Centaurea Montana)

$ rpm -qa | grep -F openssl
openssl-1.0.1u-alt0.M70P.1

$ rpm -qa | grep -F xfreerdp
xfreerdp-1.1.0-alt1.M70P.1.beta1`

**Comment by Karlomanio** [comment]
Thanks, this resolved my problem, too.
