### ISSUE TITLE
Remote application program(/app:) and command line(/app-cmd) parameter does not work on Ubuntu 20.04

### ISSUE THREAD

**Issue by ugurkebir** [FreeRDP/FreeRDP#6811]
I want to send commands to the bash of the remote Ubuntu machine with Freerdp, but I was not successful.

The command I use is as follows;

`xfreerdp -sec-nla +clipboard -wallpaper -themes /audio-mode:1 /sound /microphone /bpp:16 -bitmap-cache -offscreen-cache -glyph-cache /gdi:hw /gfx:rfx /cert-ignore /app:/bin/sh /app-cmd:"ls -li" /u:<user> /p:<pass> /v:192.168.5.8`

Connection was successful but I could not send any commands. Do you have any suggestion?

**Comment by akallabeth** [comment]
sorry, for what you´re trying you better stick to `ssh`.
the `/app*` family is for remote application mode.
That is instead of showing a whole remote desktop only an application window is shown.

**Comment by ugurkebir** [comment]
Okay, I got it. Thanks for the explanation.
