### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by rahulbelekar** [FreeRDP/FreeRDP#6815]
**Describe the bug**
We have built openSSL for arm 64 and created the libs. Used cmake to build iFreeRDP. After building our project, adding FreeRDP iOS Project we get the following errors

Undefined symbols for architecture arm64:
  "_OPENSSL_init_ssl", referenced from:
      __winpr_openssl_initialize in libwinpr2.a(ssl.o)
  "_EVP_MD_CTX_new", referenced from:
      _winpr_Digest_New in libwinpr2.a(hash.o)
  "_HMAC_CTX_free", referenced from:
      _winpr_HMAC_Free in libwinpr2.a(hash.o)
  "_EVP_CIPHER_CTX_reset", referenced from:
      _winpr_RC4_New_Internal in libwinpr2.a(cipher.o)
  "_BIO_set_next", referenced from:
      _bio_rdp_tls_ctrl in libfreerdp2.a(tls.o)
  "_BIO_meth_set_read", referenced from:
      _BIO_s_simple_socket in libfreerdp2.a(tcp.o)
      _BIO_s_buffered_socket in libfreerdp2.a(tcp.o)
      _BIO_s_rdg in libfreerdp2.a(rdg.o)
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
      _BIO_s_tsg in libfreerdp2.a(tsg.o)
  "_TLS_server_method", referenced from:
      _tls_accept in libfreerdp2.a(tls.o)
      _schannel_openssl_server_init in libwinpr2.a(schannel_openssl.o)
  "_OPENSSL_sk_num", referenced from:
      _sk_GENERAL_NAME_num in libfreerdp2.a(crypto.o)
      _sk_X509_num in libfreerdp2.a(tls.o)
  "_OPENSSL_sk_pop_free", referenced from:
      _sk_GENERAL_NAME_pop_free in libfreerdp2.a(crypto.o)
  "_HMAC_CTX_new", referenced from:
      _winpr_HMAC_New in libwinpr2.a(hash.o)
  "_BIO_up_ref", referenced from:
      _bio_rdp_tls_ctrl in libfreerdp2.a(tls.o)
  "_OPENSSL_sk_value", referenced from:
      _sk_GENERAL_NAME_value in libfreerdp2.a(crypto.o)
      _sk_X509_value in libfreerdp2.a(tls.o)
  "_BIO_set_data", referenced from:
      _transport_bio_simple_new in libfreerdp2.a(tcp.o)
      _transport_bio_simple_free in libfreerdp2.a(tcp.o)
      _transport_bio_buffered_new in libfreerdp2.a(tcp.o)
      _rdg_new in libfreerdp2.a(rdg.o)
      _bio_rdp_tls_new in libfreerdp2.a(tls.o)
      _bio_rdp_tls_free in libfreerdp2.a(tls.o)
      _tsg_connect in libfreerdp2.a(tsg.o)
      ...
  "_BIO_get_init", referenced from:
      _transport_bio_simple_ctrl in libfreerdp2.a(tcp.o)
      _transport_bio_simple_uninit in libfreerdp2.a(tcp.o)
      _bio_rdp_tls_free in libfreerdp2.a(tls.o)
  "_BIO_set_retry_reason", referenced from:
      _bio_rdp_tls_write in libfreerdp2.a(tls.o)
      _bio_rdp_tls_read in libfreerdp2.a(tls.o)
      _bio_rdp_tls_ctrl in libfreerdp2.a(tls.o)
  "_SSL_CTX_set_security_level", referenced from:
      _tls_prepare in libfreerdp2.a(tls.o)
  "_TLS_client_method", referenced from:
      _tls_connect in libfreerdp2.a(tls.o)
      _schannel_openssl_client_init in libwinpr2.a(schannel_openssl.o)
  "_BIO_get_shutdown", referenced from:
      _transport_bio_simple_ctrl in libfreerdp2.a(tcp.o)
      _transport_bio_simple_uninit in libfreerdp2.a(tcp.o)
      _bio_rdp_tls_ctrl in libfreerdp2.a(tls.o)
      _bio_rdp_tls_free in libfreerdp2.a(tls.o)
  "_SSL_CTX_set_options", referenced from:
      _tls_prepare in libfreerdp2.a(tls.o)
      _schannel_openssl_client_init in libwinpr2.a(schannel_openssl.o)
      _schannel_openssl_server_init in libwinpr2.a(schannel_openssl.o)
  "_OPENSSL_init_crypto", referenced from:
      _x509_verify_certificate in libfreerdp2.a(crypto.o)
  "_BIO_meth_set_puts", referenced from:
      _BIO_s_simple_socket in libfreerdp2.a(tcp.o)
      _BIO_s_buffered_socket in libfreerdp2.a(tcp.o)
      _BIO_s_rdg in libfreerdp2.a(rdg.o)
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
      _BIO_s_tsg in libfreerdp2.a(tsg.o)
  "_BIO_meth_set_write", referenced from:
      _BIO_s_simple_socket in libfreerdp2.a(tcp.o)
      _BIO_s_buffered_socket in libfreerdp2.a(tcp.o)
      _BIO_s_rdg in libfreerdp2.a(rdg.o)
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
      _BIO_s_tsg in libfreerdp2.a(tsg.o)
  "_BIO_meth_new", referenced from:
      _BIO_s_simple_socket in libfreerdp2.a(tcp.o)
      _BIO_s_buffered_socket in libfreerdp2.a(tcp.o)
      _BIO_s_rdg in libfreerdp2.a(rdg.o)
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
      _BIO_s_tsg in libfreerdp2.a(tsg.o)
  "_SSL_in_init", referenced from:
      _bio_rdp_tls_ctrl in libfreerdp2.a(tls.o)
  "_BIO_meth_set_create", referenced from:
      _BIO_s_simple_socket in libfreerdp2.a(tcp.o)
      _BIO_s_buffered_socket in libfreerdp2.a(tcp.o)
      _BIO_s_rdg in libfreerdp2.a(rdg.o)
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
      _BIO_s_tsg in libfreerdp2.a(tsg.o)
  "_EVP_MD_CTX_free", referenced from:
      _winpr_Digest_Free in libwinpr2.a(hash.o)
  "_BIO_set_init", referenced from:
      _transport_bio_buffered_new in libfreerdp2.a(tcp.o)
      _transport_bio_simple_uninit in libfreerdp2.a(tcp.o)
      _transport_bio_simple_init in libfreerdp2.a(tcp.o)
      _rdg_bio_new in libfreerdp2.a(rdg.o)
      _bio_rdp_tls_ctrl in libfreerdp2.a(tls.o)
      _bio_rdp_tls_free in libfreerdp2.a(tls.o)
      _transport_bio_tsg_new in libfreerdp2.a(tsg.o)
      ...
  "_BIO_meth_set_gets", referenced from:
      _BIO_s_simple_socket in libfreerdp2.a(tcp.o)
      _BIO_s_buffered_socket in libfreerdp2.a(tcp.o)
      _BIO_s_rdg in libfreerdp2.a(rdg.o)
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
      _BIO_s_tsg in libfreerdp2.a(tsg.o)
  "_BIO_set_shutdown", referenced from:
      _transport_bio_simple_ctrl in libfreerdp2.a(tcp.o)
      _transport_bio_simple_init in libfreerdp2.a(tcp.o)
      _bio_rdp_tls_ctrl in libfreerdp2.a(tls.o)
  "_BIO_meth_set_callback_ctrl", referenced from:
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
  "_BIO_get_data", referenced from:
      _transport_bio_simple_write in libfreerdp2.a(tcp.o)
      _transport_bio_simple_read in libfreerdp2.a(tcp.o)
      _transport_bio_simple_ctrl in libfreerdp2.a(tcp.o)
      _transport_bio_simple_free in libfreerdp2.a(tcp.o)
      _transport_bio_buffered_write in libfreerdp2.a(tcp.o)
      _transport_bio_buffered_read in libfreerdp2.a(tcp.o)
      _transport_bio_buffered_ctrl in libfreerdp2.a(tcp.o)
      ...
  "_OBJC_CLASS_$_OrderedDictionary", referenced from:
      objc-class-ref in Utils.o
      objc-class-ref in ProUtil.o
  "_BIO_meth_set_ctrl", referenced from:
      _BIO_s_simple_socket in libfreerdp2.a(tcp.o)
      _BIO_s_buffered_socket in libfreerdp2.a(tcp.o)
      _BIO_s_rdg in libfreerdp2.a(rdg.o)
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
      _BIO_s_tsg in libfreerdp2.a(tsg.o)
  "_BIO_meth_set_destroy", referenced from:
      _BIO_s_simple_socket in libfreerdp2.a(tcp.o)
      _BIO_s_buffered_socket in libfreerdp2.a(tcp.o)
      _BIO_s_rdg in libfreerdp2.a(rdg.o)
      _BIO_s_rdp_tls in libfreerdp2.a(tls.o)
      _BIO_s_tsg in libfreerdp2.a(tsg.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**To Reproduce**
1. Build OpenSSL 1.1.1i.
2. Run CMake script to build FreeRDP Xcode project.
3. Add Xcode project to client project and build
4. Errors.

**Expected behavior**
Should build without errors

**Screenshots**
NA

**Application details**
* FreeRDP version Stable 2.0 Branch.
* Branch: stable 2.0 , build command : cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode, Run in Xcode.
* OS version connecting to (server side)-  NA

**Environment (please complete the following information):**
 - OS: iOS
 - Version/Distribution: Xcode 12.4, iOS 14.1
 - Architecture: arm64

Are there any additional steps that are required to have a clean build? Please do let us know. Thank You

**Comment by akallabeth** [comment]
Most likely the toolchain file needs an updater, iOS is looking for a maintainer.

**Comment by rahulbelekar** [comment]
Does this mean that there is some updation needed to CMakeLists.txt file or IOSToolChain file? I haven't worked on eighteen of these but I will try to fix if possible. If you are able to guide me that will be of help.

**Comment by akallabeth** [comment]
@rahulbelekar only the toolchain file. The project compiles quite fine, but if it uses the wrong compiler/... then xcode will not pick up the generated libraries.
As for the iOS client, I don´t know if that still compiles, we deactivated it some time ago as maintaining it on the pr tester was quite a pain without a proper test setup to fix issues that arise.

**Comment by rahulbelekar** [comment]
Hi @akallabeth,

Thank you for your suggestion, I was able to compile FreeRDP with openssl 1.1.1i. The FreeRDP project still compiles, though I have come across some other issue. While creating the RDPSession the compiler shows some errors and we are unable to connect to the server. 

**Errors**
[18:54:35:812] [17511:6da5b000] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
[18:54:35:813] [17511:6da5b000] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
[18:54:35:814] [17511:6da5b000] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
[18:54:35:814] [17511:6da5b000] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
[18:54:36:595] [17511:6da5b000] [INFO][com.freerdp.primitives] - primitives autodetect, using generic
[18:54:36:603] [17511:6da5b000] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[18:54:36:603] [17511:6da5b000] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state


[18:54:37:122] [17511:6da5b000] [WARN][com.freerdp.core.nego] - Error: SSL_NOT_ALLOWED_BY_SERVER
[18:54:37:123] [17511:6da5b000] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
[18:54:37:123] [17511:6da5b000] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state

We were initially using openssl 1.0.2q, and the same connection request parameters, we are able to connect to the server but now its showing the above errors. Are you aware of any such issue or parameter change that is required?

**Comment by akallabeth** [comment]
this looks like the client is setting some strange authentication configuration that fails.
You could dump the command line generated in `RDPSession.m` of the client and check if that works with `xfreerdp`, then you have an easy way to test.

**Comment by rahulbelekar** [comment]
Hi @akallabeth, I was able to dump the command line and resolve all the issue. So the current status is that I am able to successfully login to RDP using OpenSSL 1.1.1i and FreeRDP 2.2.0. 

However the resultant screen displayed on the device is not rendering the colours correctly, Do you have any idea where I should start looking to fix the below issue?

Screenshot: https://ibb.co/VJXkhDM

**Comment by akallabeth** [comment]
@rahulbelekar ok, then I´m closing this.
As for the colors, looks like the setting for `gdi` color are wrong (`RGB/BGR` mismatch)

**Comment by libo198615** [comment]
@rahulbelekar I have the same questions, how you fix?

**Comment by rahulbelekar** [comment]
Hi @libo198615, Can you be more specific of the question? If it's the main issue where you're getting undefined symbol errors. For this you have to assign the search header paths in Xcode settings correctly.

**Comment by libo198615** [comment]
Undefined symbols for architecture arm64:
  "_CRYPTO_set_locking_callback", referenced from:
      __winpr_openssl_cleanup_locking in libwinpr3.a(ssl.o)
      __winpr_openssl_initialize_locking in libwinpr3.a(ssl.o)
  "_CRYPTO_get_dynlock_create_callback", referenced from:
      __winpr_openssl_cleanup_locking in libwinpr3.a(ssl.o)
      __winpr_openssl_initialize_locking in libwinpr3.a(ssl.o)
  "_CRYPTO_set_dynlock_create_callback", referenced from:
      __winpr_openssl_cleanup_locking in libwinpr3.a(ssl.o)
      __winpr_openssl_initialize_locking in libwinpr3.a(ssl.o)
  "_CRYPTO_get_dynlock_lock_callback", referenced from:
      __winpr_openssl_cleanup_locking in libwinpr3.a(ssl.o)
      __winpr_openssl_initialize_locking in libwinpr3.a(ssl.o)
  "_CRYPTO_set_dynlock_lock_callback", referenced from:
      __winpr_openssl_cleanup_locking in libwinpr3.a(ssl.o)
      __winpr_openssl_initialize_locking in libwinpr3.a(ssl.o)
      
it has arm64
     lipo -info  //  libwinpr3.a is architecture: arm64
I have update the FreeRDP. does it matter with the libssl.a

**Comment by libo198615** [comment]
I has find the reason, I have pod 'BaiduNaviKit' in my project, it update to 6.4.0 . I made id  6.0.0 . now it is ok, I do not know why , later to see
