### ISSUE TITLE
Mouse cursor jumps back when moving between monitors

### ISSUE THREAD

**Issue by vatec** [FreeRDP/FreeRDP#6832]
When using /multimon the cursor is jumping back when I move between the two RDP monitors. This isn't happening between my physical monitors (as can be seen in the imgur videos), so I believe it is related to freerdp and not my desktop.
I am using i3-gaps on Debian bullseye. Nouveau driver
I have tried -mouse-motion which allows me to jump between monitors without this issue, but causes other problems due to disabling the mouse motion

**To Reproduce**
Move cursor between two screens and it jumps back

**Screenshots**
https://imgur.com/a/IOJ0roi
Two short videos can be seen here. Video 1 shows the xfreerdp window not in line with the physical monitors, video 2 shows when they are in line. Same behaviour

FreeRDP 2.2.0
/gfx:rfx -grab-keyboard /monitors:0,2 /multimon
* Output of `xfreerdp /buildconfig` - its the debian bullseye apt install

 - OS: Linux 5.10
 - Version/Distribution: Debian bullseye
 - Architecture: amd64

**Comment by vatec** [comment]
I can confirm that this behaviour is still present on the nightly compile

**Comment by akallabeth** [comment]
Not a bug, this is normal behavior for (I assume you´re using `excel` in this spreadsheet example?)
What is happening is that the remote application is repositioning the pointer when crossing the `scroll` area
(`xf_Pointer_SetPosition` does execute that remote command locally) 

You will not see that with a plain desktop or e.g. notepad, correct?

**Comment by vatec** [comment]
> Not a bug, this is normal behavior for (I assume you´re using `excel` in this spreadsheet example?)
> What is happening is that the remote application is repositioning the pointer when crossing the `scroll` area
> (`xf_Pointer_SetPosition` does execute that remote command locally)
> 
> You will not see that with a plain desktop or e.g. notepad, correct?

It happens without any application there at all, so I dont believe that excel is doing it.
I have also noticed that when moving the cursor onto the edge of the xfreerdp window, it places it to the far left of the current rdp monitor (see video 1 on this example)

video 2 shows the same behaviour without any application
https://imgur.com/a/tNxXewQ

**Comment by akallabeth** [comment]
@vatec ok, so can you tell if the function I referenced has been called? That is the only place freerdp manipulates the mouse pointer, otherwise you should check your window manager/extension/whatever of your local desktop.

**Comment by vatec** [comment]
> @vatec ok, so can you tell if the function I referenced has been called? That is the only place freerdp manipulates the mouse pointer, otherwise you should check your window manager/extension/whatever of your local desktop.

Yes the function is being called, looks like this with /log-level:trace | grep xf_Pointer_SetPosition

`[09:10:55:874] [129552:129554] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_Pointer_SetPosition
[09:11:06:979] [129552:129554] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_Pointer_SetPosition`

**Comment by vatec** [comment]
> @vatec ok, good. so you need to check why your remote os wants the mouse to appear where it appears.
> Just to be sure, if you use a build with this function disabled, does the jumping stop?

Sorry how can I build with this disabled? Is there a build flag I need to set?
Is the function being called by the windows PC the remote desktop is being connected to? And freerdp is just doing what the windows says?

**Comment by vatec** [comment]
After some investigation i have determined that this issue is related to Windows rather than freerdp
https://superuser.com/questions/1580192/mouse-automatically-reverts-back-to-center-of-my-dual-display-when-i-navigate-fr
