### ISSUE TITLE
Touch scolling on Wayland (2.3)

### ISSUE THREAD

**Issue by frank-bell** [FreeRDP/FreeRDP#6839]
It seems that two-finger, natural scrolling on Wayland (via Apple Track Pad) has stopped working on v2.3. Scrolling still works when I plug in a mouse and use the scroll wheel. I have tried adding +-/gestures and +-/multitouch variations, which werent required on 2.2, but no difference. Downgrading to 2.2 restores functionality.

I hope that it is something that I am missing, but I did see that there was some recent work around Wayland scrolling.

**Steps to reproduce the behavior:**
1. Connect via command line "wlfreerdp /v:host"
2. Tap on any window with scrollable content
3. Scrolling up or down with two fingers on touch pad has no effect.

**Expected behavior**
The same scrolling behaviour as within the Wayland itself.

**Application details**
* FreeRDP version 
2.3.0 (n/a)
* Command line used 
wlfreerdp /v:host"
* Output of `xfreerdp /buildconfig`
This is FreeRDP version 2.3.0 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=ON WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -D_FORTIFY_SOURCE=2 -march=armv8-a -O2 -pipe -fno-plt -D_FORTIFY_SOURCE=2 -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 10.2.0
Target architecture:
* OS version connecting to (server side)
Windows 10 19042.804
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
Tried and checked output but couldn't see anything, happy to re-run and add if required.

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Version/Distribution: Rolling (kernel 5.10.12)
 - Architecture: arm64

**Comment by akallabeth** [comment]
@frank-bell which environment are you using? e.g. `gnome` is working fine, but we had reports from `kde` users that some events are still missing there.

**Comment by frank-bell** [comment]
Sorry, missed that. Using Wayfire WM, based on wlroots, the same as Sway.

**Comment by akallabeth** [comment]
ok. we did change the event source from `wl_pointer_listener::axis` source to `wl_pointer_listener::axis_discrete` as the former does vary too much depending on hardware/software combinations.
If it is not working with sway, check if they generate such events.

If you´re using arch, just add a patch in `wlfreerdp.c`:
```
diff --git client/Wayland/wlfreerdp.c client/Wayland/wlfreerdp.c
index aca734211..6a592c15e 100644
--- client/Wayland/wlfreerdp.c
+++ client/Wayland/wlfreerdp.c
@@ -357,12 +357,11 @@ static BOOL handle_uwac_events(freerdp* instance, UwacDisplay* display)
                                break;
 
                        case UWAC_EVENT_POINTER_AXIS:
+            if (!wlf_handle_pointer_axis(instance, &event.mouse_axis))
+                return FALSE;
                                break;
 
-                       case UWAC_EVENT_POINTER_AXIS_DISCRETE:
-                               if (!wlf_handle_pointer_axis(instance, &event.mouse_axis))
-                                       return FALSE;
-
+            case UWAC_EVENT_POINTER_AXIS_DISCRETE:
                                break;
 
                        case UWAC_EVENT_KEY:
```

note: you might still need to adjust the value for scrolling, but at least that should work until `sway` supports the event source.

**Comment by frank-bell** [comment]
Thanks, will give it a go later today.

**Comment by frank-bell** [comment]
The patch restored the scrolling, but caused it to jump to top/bottom of content. I think I saw some recent commit that multiplies the scroll factor by 8 so that could be it. Will revert back to 2.2 and check where wlroots is with support for wl_pointer_listener::axis_discrete.

**Comment by Xyene** [comment]
Hi @akallabeth, popping over from the wlroots thread and copying my comment here:

wlroots only passes off what it received from libinput, and libinput touchpads don't have discrete axis events by design.

See https://wayland.freedesktop.org/libinput/doc/latest/api/group__event__pointer.html#ga38d12fc6884c9943e261febdb2384b98:

> If the source is LIBINPUT_POINTER_AXIS_SOURCE_WHEEL, the discrete value correspond to the number of physical mouse wheel clicks.
> 
> If the source is LIBINPUT_POINTER_AXIS_SOURCE_CONTINUOUS or LIBINPUT_POINTER_AXIS_SOURCE_FINGER, **the discrete value is always 0.**

(A touchpad is typically `LIBINPUT_POINTER_AXIS_SOURCE_FINGER`.)

To be clear, FreeRDP should be using the value given in the non-discrete axis event if it wants to work with touchpads. See https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_pointer:

> This event carries the axis value of the wl_pointer.axis event in discrete steps (e.g. mouse wheel clicks).
> ...
> This event is optional; continuous scrolling devices like two-finger scrolling on touchpads do not have discrete steps and do not generate this event.

Separately from the discrete axis issue, as @progandy mentions in that thread,

> By the way, proper axis handling should probably cache the value in axis/axis_discrete and only choose the preferred operation during the wl_pointer_frame event.
>
> https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_pointer
> > *wl_pointer::frame - end of a pointer event sequence*
> > Indicates the end of a set of events that logically belong together. A client is expected to accumulate the data in all events within the frame before proceeding.

It looks like FreeRDP is currently ignoring the frame event. This is less of a visible issue since you can kind of get away with not doing this, but it's suboptimal: some devices send things like two motion events {(0, dy), (dx, 0)} per frame, so there'd be extra network chatter sending this without batching on the frame event.

**Comment by akallabeth** [comment]
@Xyene thank you for the references,
