### ISSUE TITLE
Weak wayland client drawing performance

### ISSUE THREAD

**Issue by manio** [FreeRDP/FreeRDP#6841]
Hi!
I want to describe a bug which I was unable to find in open issues so I think it is worth to mention this...
After fixing key-repeat recently I suffer from the last performance problem to have the wayland client in pair with x version:
The problem is that a performance of wayland client is not in pair with xfreerdp:

**Steps to reproduce**
1. Prepare a Windows10 session with two full screen apps:
- notepad
- web browser (eg chrome)
2. Connect to this session using xfreerdp
3. Alt-Tab between those two full-screen apps and notice the speed of the switching
4. Connect to the same Win10 session with wlfreerdp
5. Alt-Tab the same way and notice that there are two problems comparing to xfreerdp:
- alt-tabbed window is "drawed/refreshed" using rectangles
- there are bigger delays - sometimes the window is refreshed after about 1sec from alt+tab

**Application details**
* FreeRDP version (`xfreerdp /version`)
```This is FreeRDP version 2.3.0 (n/a)```
* Command line used
* ```wlfreerdp -grab-keyboard /v:[...] /kbd:0x00000415 /size:1918x1024```
* xfreerdp - same as above
* Output of `xfreerdp /buildconfig`
```This is FreeRDP version 2.3.0 (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=ON WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 10.2.0
Target architecture: x64
```

* OS version connecting to (server side):
Windows 10

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Arch
 - Architecture: amd64

**Comment by meklonets** [comment]
Hello,
I confirm the performance's lack.
Is there any chance the issue will be resolved?

**Comment by Blind55** [comment]
I am also experiencing severe performance reduction of wlfreerdp versus xfreerdp.

Executed command line:
`[wl,x]freerdp -authentication +clipboard +glyph-cache /relax-order-checks /size:1920x1080 /smart-sizing:1920x1080 /bpp:24 /v:[...]`

- OS: Linux
- Version/Distribution: Arch
- Architecture: x86_64
- WM: sway
- xfreerdp /version:
`This is FreeRDP version 2.4.1 (n/a)`
- xfreerdp /buildconfig:
`CFLAGS:              -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 11.1.0
Target architecture: x64`

Other symptoms:
- performance is extremely sluggish when compared to xfreerdp
- there intermittent lines in the drawn image
- keyboard configuration/grabbing seems to be a lot different from xfreerdp

Please let me know if I can help with testing.

**Comment by manio** [comment]
Just a complement: I am also using sway.

@Blind55 
By '_intermittent lines in the drawn image_' you mean this thing?
![image](https://user-images.githubusercontent.com/583157/147738166-a831346f-a45d-418d-9713-728a806046a7.png)

This is an empty data grid from one application. This grid should be in one single color, while I have an image as you can see above. Steps to reproduce in my case:
1. view some image (in this case it was a desktop wallpaper)
2. alt-tab to this application
3. you can see that in place of a solid grid is an image from previous screen

**Comment by Blind55** [comment]
@manio:
I am not sure. I don't run an application with repetitive lines, really. For me, it looks more like a window drawing issue:
the lines don't align with any line in the application, they are randomly arranged. Once I move the application window, the lines disappear in the current location and then move on to a different location in the wlfreerdp window. However, moving a window is an extremely tedious, slow process, making wlfreerdp unusable for at the moment.

**Comment by dR3b** [comment]
I also have performance problems with "wlfreerdp" only.

**Comment by a-m-joseph** [comment]
Much of the reason for this is the fact that wlfreerdp does not use any GPU acceleration at all.  This is particularly noticeable when there is scaling -- i.e. the wlfreerdp window is not exactly pixel-for-pixel the same size as the RDP server's display.  Wlfreerdp uses software to scale the image (and not a very optimized scaler at that), while xfreerdp uses XRENDER which is implemented with hardware GPU scaling.

If you want a wayland RDP client that performs well you'll need to use [remmina](https://en.wikipedia.org/wiki/Remmina) -- it uses gtk, which is able to take advantage of the GPU for simple scaling operations on wayland.

**Comment by a-m-joseph** [comment]
[Here](https://github.com/FreeRDP/FreeRDP/blob/e1e2eef4e1e6fd98bd428e21b8ddeb76979fa2cd/client/X11/xf_client.c#L209) is where xfreerdp uses XRENDER to draw scaled images.  Both Xorg and Xwayland implement these XRENDER calls using GPU acceleration.

[Here](https://github.com/FreeRDP/FreeRDP/blob/e1e2eef4e1e6fd98bd428e21b8ddeb76979fa2cd/client/Wayland/wlfreerdp.c#L729) is the corresponding line for wlfreerdp, which calls `freerdp_image_scale` which is implemented [here](https://github.com/FreeRDP/FreeRDP/blob/e1e2eef4e1e6fd98bd428e21b8ddeb76979fa2cd/libfreerdp/codec/color.c#L772).  If you're lucky you might have libswscale and get a small boost from CPU vector instructions, but there is no GPU offload there at all and even worse the upscaling (in the case where the client window is larger than the remote server's virtual monitor size) happens in the CPU, so not only are you more than tripling the CPU memory bandwidth requirements, you're then sending the *upscaled* image across the CPU->GPU bus (usually PCIe) which is slower than the memory bus.  The upscaled image is larger than the original image, so this puts even more pressure on the link.

In order to get decent performance from wlfreerdp, somebody needs to reimplement `wlf_copy_image()` using opengl calls.

**Comment by Dramcryx** [comment]
@a-m-joseph considering your info, I removed resolution options from my .rdp config because client/server resolutions are equal - it started working much faster. Thank you!

**Comment by Hi-Angel** [comment]
@akallabeth just to clarify, has this been fixed? I don't see a PR link nor comment explaining this, but considering [some projects may have to detect wlfreerdp](https://github.com/TibixDev/winboat/issues/646), performance is a reasonable question, because if it's okay in the current releases, I presume wlrfreerdp on Wayland sessions should be preferred.

**Comment by manio** [comment]
Just to clarify things a bit - I’m not 100% sure because it was quite some time ago, but as far as I remember, after I reported this issue I spent some time digging into the Wayland code and committed a few fixes. I know this code is deprecated, but I still use it practically every day (Wayland + swaywm), including on a HiDPI screen (the code even takes scaling into account).

Sorry, but SDL is still a no-go for me, so wlfreerdp is kind of a lifesaver here, and I absolutely need it for my work.

**Comment by akallabeth** [comment]
@Hi-Angel no, `wlfreerdp` is deprecated.
@manio well, some issue reports or help would be appreciated. which problems do you have?

**Comment by manio** [comment]
@akallabeth 
You misunderstood me - I only meant that this report was filed on **Feb 26, 2021**, and afterwards I simply fixed things myself in PRs: #9482 #9715 #9725 #10128.

Right now I don’t have any issues, and as I mentioned above, I’m using `wlfreerdp` daily on wayland 🙂

**Comment by akallabeth** [comment]
@manio 👍 
I was referring to `sdl-freerdp` though, as that is what we do use on wayland.
(there are some issues with `HighDPI` as `kde` and `gnome` use different scaling implementations that contradict each other (and `SDL` does not fully abstract that yet)

**Comment by manio** [comment]
It was some time ago but yeah, as far as I remember, the issue I had was related to scaling and also keyboard bindings/grabbing. My window manager (sway) uses scaling on a HiDPI display, and SDL was simply ignoring it. I want to use a full resolution available (eg 4K monitor) for a wayland window and the Windows OS is doing a scaling for me. So I have a crispy looking fonts. I just fixed/added this on the wayland client.
On top of that, I follow the KISS principle - why add an extra layer when freerdp window can be created and managed natively on Wayland itself so I just prefer native wlfreerdp than the SDL one.

So, since we’re on this topic and if I may ask one thing - please keep this code marked as deprecated for as long as possible and please don't drop this from the repo. I’m actively using it, and it would be great if it could stay that way.

As long as I’m using it, I’ll do my best to help maintain this wayland version.

**Comment by akallabeth** [comment]
@manio code will stay until we move to `FreeRDP 4`, then we'll drop all deprecated things.
