### ISSUE TITLE
Maximized RemoteApp windows issues with Windows 10 server

### ISSUE THREAD

**Issue by roland65** [FreeRDP/FreeRDP#6842]
Maximizing a RemoteApp window doesn't work as expected when the server is Windows 10:

- the whole desktop is recovered by the maximized window (including the desktop panel and dock)
- then interacting with the maximized window doesn't work most of the time (the window becomes unresponsive)

And trying to resize a RemoteApp window to fit the desktop (from unmaximized state) doesn't work well: there is always a small part of the desktop that is not covered. Moving the window to the left side always leave a small uncovered part.

I see these issues when the Windows 10 RDP display driver is either WDDM or XDDM.

All these things work without issue when the server is Windows 7.

Here are the details;

Server: Windows 10 20H2 (but 1904 shows the same issues)
Local: Ubuntu Linux 20.04 with Gnome Desktop

Freerdp version: 2.3.0

Command line;
xfreerdp /bpp:32 /u:<my_name> /p:<my_password>  /app:"C:\Windows\notepad.exe" /v:192.168.122.30

**Comment by akallabeth** [comment]
@roland65 ok, following results on my test machine:
I´m running:
1. `debian bullseye 11`  with a `gnome` desktop
2. 2 4k monitors
3. Remote is windows 10
4. Running `paint` and `wordpad` as test case

I can not see the maximized window covering the `gnome top bar`
What I can see is that the right border has a few pixels uncovered (e.g. the window is smaller than screen width) which is probably a corner case for handling the invisible resize borders

**Comment by roland65** [comment]
Ok, thanks for the test.
The issue is perhaps related to the Gnome version of Ubuntu 20.04. I'll do another test with a more recent version.
My monitor's resolution is 2560 x 1440.

**Comment by roland65** [comment]
I tested with a fresh Ubuntu 21.10 (latest version) and got *exactly the same issues*. FreeRDP version is 2.2.0 in Ubuntu 21.10 and Gnome Desktop is 3.38.
I tested with Notepad and Wordpad in remote Windows 10 20H2.

**Comment by roland65** [comment]
And I did another test with the upcoming Ubuntu 21.10 (to be released in April), with FreeRDP 2.3.0 and Gnome Desktop 3.38.3 and now, good news,  the "cover issue" has gone!

However, when the RemoteApp window (Notepad, Wordpad) is maximized, there is still a few pixels that are not covered on the right of the screen.

**Comment by akallabeth** [comment]
@roland65 ok, perfect, then it has improved :)
