### ISSUE TITLE
Link errors when using -DBUILD_SHARED_LIBS=OFF

### ISSUE THREAD

**Issue by user-36428** [FreeRDP/FreeRDP#6846]
Just thought I would bring this up again now that you are releasing some new versions. With the following cmake command:
cmake -L -DCMAKE_INSTALL_PREFIX:PATH=$DSTDIR -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ../
I am getting these link errors and have been for a long while.... Have not had a clean compile for a long time with no shared libs on both fully updated Debian Buster and LUbuntu 18.04.5
...
[ 99%] Linking C executable xfreerdp
/usr/bin/ld: ../../channels/video/client/libvideo-client.a(video_main.c.o): in function `video_onMappedGeometryClear':
video_main.c:(.text+0x122): undefined reference to `mappedGeometryUnref'
/usr/bin/ld: ../../channels/video/client/libvideo-client.a(video_main.c.o): in function `PresentationContext_unref':
video_main.c:(.text+0x5ea): undefined reference to `mappedGeometryUnref'
/usr/bin/ld: ../../channels/video/client/libvideo-client.a(video_main.c.o): in function `video_control_on_data_received':
video_main.c:(.text+0xd0d): undefined reference to `mappedGeometryRef'
/usr/bin/ld: ../../channels/video/client/libvideo-client.a(video_main.c.o): in function `VideoFrame_free':
video_main.c:(.text+0x1777): undefined reference to `mappedGeometryUnref'
/usr/bin/ld: video_main.c:(.text+0x17c6): undefined reference to `mappedGeometryUnref'
/usr/bin/ld: ../../channels/video/client/libvideo-client.a(video_main.c.o): in function `video_data_on_data_received':
video_main.c:(.text+0x25dc): undefined reference to `mappedGeometryRef'
/usr/bin/ld: video_main.c:(.text+0x2717): undefined reference to `mappedGeometryUnref'
/usr/bin/ld: ../../channels/geometry/client/libgeometry-client.a(geometry_main.c.o): in function `geometry_DVCPluginEntry':
geometry_main.c:(.text+0x14d6): undefined reference to `mappedGeometryUnref'
collect2: error: ld returned 1 exit status
make[2]: *** [client/X11/CMakeFiles/xfreerdp-client.dir/build.make:364: client/X11/xfreerdp] Error 1
make[1]: *** [CMakeFiles/Makefile2:3906: client/X11/CMakeFiles/xfreerdp-client.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
...
When I do a cmake like this:
cmake -L -DCMAKE_INSTALL_PREFIX:PATH=$DSTDIR -DCMAKE_BUILD_TYPE=Release ../
it's fine. What Iam I missing?

**Comment by akallabeth** [comment]
looks like you´re the first raising this question.
looks like there is some linker line missing as video channel requires geometry channel linked in

**Comment by user-36428** [comment]
Possibly related to the fix that was done in #6643

**Comment by akallabeth** [comment]
@user-36428 yes, looks like I did not backport that one.
