### ISSUE TITLE
multimonitor + plasma 5.21

### ISSUE THREAD

**Issue by gtiborcz** [FreeRDP/FreeRDP#6869]
Hi! 
I'm using Arch linux. My system is up to date with Plasma 5.21.2-1 and freerdp 2.3.1. I'm using X11.  Since plasma 5.21 /multimon support is not working correctly. I have 2/3 monitors usually. 
On RD system (windows  server 2016)  In "Windows display setting" multiple screens is working corretly on  RD system (windows  server 2016).  Both screen is appear,  I can manage it. BUT  ONLY IN THE SETTING because I don't really see it actually.
On linux is visible only one window (full-screen). Second RD window (and the rest) is invisible. I can see only linux desktop, not RD. If I downgrade to plasma 5.20.5 or earlier version, I can use /multimon perfectly. Visible all RD screen on linux.

https://pasteboard.co/JRkeqYR.png

You can see on this picture:
Windows have 2 screens. visible number "2" (left side) but invisible number "1" (right side)
I opened "Windows display setting", but window is invisible, because it is on screen number "1".

Thank you your help

**Comment by kayfoe** [comment]
We have the same problem with our Wayland version of FreeRDP.
In x11 there aren't these Issues.
The system detects both monitors but it can only display one.

**Comment by gtiborcz** [comment]
I tested with Wayland and many RD as well.  Problem is same with all.

**Comment by akallabeth** [comment]
@kayfoe well, that is expected, `wlfreerdp` does still not support multimon
@gtiborcz multimon did not change since `2.0.0` so could you check if that might be due to:
1. Your monitor configuration (spaces between layouts are not supported)
2. Your desktop (just try something else, e.g. `openbox` or whatever you can think of)

**Comment by gtiborcz** [comment]
Changed Plasma maybe.
1. No space, I  tested before I wrote bugriport. Everything working if I downgarde to Plasma 5.20 without any changes. Plasma 5.20 + /multimon  is correct with 2 and 3 monitors as well.
2. sorry, but I not tested, and I not want to test it, because I use my system to work. I try to test an other computer with Plasma 5.21. I will inform you about the result.

**Comment by gtiborcz** [comment]
Test machine: HP 470 G4 (1600x900) + Philips 223v (1920x1080) + Philips 223v(1092x1080)
Original (cli installed) Arch linux with Plasma

**Test 1**
I use only 2 external monitors in side by side:
Ext-1 0,0
Ext-2 1920,0

Plasma 5.20.x
Windows (RD):  recognized 2 screens. Screen1: 1920x1080, Screen2: 1920x1080  
In Linux:  On both monitors are the correct screen of windows.

Plasma 5.21.x
Windows (RD):  recognized 2 screens. Screen1: 1920x1080, Screen2: 1920x1080. I can move the opened window from screen1 to screen2, and vica versa.  
In Linux:  Visible only left windows screen (screen1). Windows Screen2 is invisible on the right linux monitor. 


**Test 2**
I inserted gap between 2 monitors
Ext-1: 0,0
gap inserted: 1920,0
Ext-2: 2000,0
Virtual screen size: 3920x1080  (1920+80+1920)

Plasma 5.20.x
You are true. /multimon not support gap between monitors.
Windows (RD):  recognized 1 screen. Size is 3920x1080.  
In Linux:  I see a long screen thru 2 monitors.

Plasma 5.21.x
Windows (RD): recognized one screen. Size is 3920x1080.  
In linux: I see a part of the long screen is only on left monitor. The right part of the long screen is hidden (invisible) on the right monitor.

**I can't run test another laptop or config now.**


Ui: 
not important which Windows do I use. Same result with Windows Server 2018 and Win10 as well.
not important how to use monitors.  beside each other, or below and above each other

I not told you freerdp is wrong, but I can see Plasma 5.21 + freerdp give me issue, however Plasma 5.20 + freerdp is working good.
Have you any idea what I have to fix it or change it?

**Comment by akallabeth** [comment]
@gtiborcz ok, this looks like an issue with `Plasma 5.21`:
Even the (single window) fullscreen mode is not shown on secondary monitor. Since even that is not working I can only guess, but maybe they have some config for handling multiple monitors?

**Comment by gtiborcz** [comment]
I can use "/monitors:x" on freerdp.
I have 3 monitors: 0,1,2
I can run a fullscreen whatever I want /monitors:0, /monitors:1, /monitors:2, but only one screen.
(Examples: /monitors:1,2 in not working correctly on Plasma 5.21)

I not remember extra settings. I'm using only KDE (Plasma) built-in config.

**Comment by meissnol** [comment]
I have the same issue in dwm on Manjaro with todays update on xfreerdp 2.3.1. Downgrading FreeRDP from 2.3.1 to 2.2.0 helped me out. In 2.3.1 xfreerdp /monitor-list gave no output, while 2.2.0 lists all 4 connected monitors correctly. /multimon (with or without :force) didnt make any change, always just one single monitor, while I need at least three monitors to do my work. I also figured out, that in 2.3.1 the keyboard-grabbing is not working. I use the windows-key as meta for the tiling window manager, so this behaviour is really annoying. 
Hope anyone will fix this, because I was spending couple of days trying to find a rdp-tool that works in dwm (keyboard and multimon).

**Comment by akallabeth** [comment]
@meissnol thanks for pointing me at `/monitor-list`, there was indeed a bug with that.
As for `grab-keyboard` and `multimon` what issues do you have? Just ran that on a `X11` and `XWayland` session and with both I could run multimon with keyboard grabbing...
Check your layout, spaces between monitors might be problematic

**Comment by gtiborcz** [comment]
I tested it in KDE 5.21 plasma fresh install.
I installed a fresh Arch system and it works fine on it.
Because when I use RD  I don't see the  linux windows behind full screen xfreerdp (multimon), I use window rules in KDE. One of the rules for xfreerdp is "Keep below". If I turn on this rule (or any rule for xfreerdp),  issue coming.
(Anyway, my own system  does not improve if I block the window rule )


I hope it is help for you.

**Comment by gtiborcz** [comment]
However Window Rule is working fine on Plasma 5.20

**Comment by meissnol** [comment]
> @meissnol thanks for pointing me at `/monitor-list`, there was indeed a bug with that.
> As for `grab-keyboard` and `multimon` what issues do you have? Just ran that on a `X11` and `XWayland` session and with both I could run multimon with keyboard grabbing...
> Check your layout, spaces between monitors might be problematic
> [edit] of course, not on plasma 5.21, but that is a different matter.

Ok, I guess I have to say sorry... The only problem I now see is the broken `/monitor-list` parameter. In the past I wrote a script that sets the `/monitor` value based on the output of `/monitor-list` to determine the connected monitors (host is a notebook, so not all monitors are always connected). The fallback, if the output of /monitor-list is not readable, is  `/monitors:1`. Getting rid of the dynamic and setting `/monitors:2,1,4` works like a charm, even in Version 2.3.1. The keygrabbing (I use `-grab-keyboard`) works, too. Just noticed, the script is setting `/wm-class` too, that explains the different behaviour of dwm :) So the only bug I see is the broken `/monitor-list`, but for now I can easily deal with it. Sorry again for making trouble ;) Oh, btw I'm on Xorg 1.20.10

**Comment by akallabeth** [comment]
Ok, so closing as resolved. Nag me if there still is something.

**Comment by gtiborcz** [comment]
@akallabeth : Why do you close this bugriport?  Original problem from me on Plasma 5.21 (not xdm as @meissnol wrote) He said sorry for his report, not mine :) 
Please open again.   
Ps. I will test some different system, with some different computer on a next few days. Then I will write for you how to generate a bug yourself.

**Comment by akallabeth** [comment]
@gtiborcz then I misread your comment with the `window rules` above, sorry

**Comment by gtiborcz** [comment]
@akallabeth
Many tests were last weekend. I identified the issue finally

As I wrote, I use window rules. Because I connect to 2 RDs usually, I'm using them different appearance. (Different desktop, different Arrangement & Access, etc) So I call them by different window title names. (with /t:<name>) The window rules identify according to the window title name. If name identification (“window title” rule - red rectangle in the picture) is included in any of the window rules, the multimonitor will not be displayed correctly. Not important “Window title” rule is on the actual rule or in one of the different rule.
My window rule examples with  problematic line in the red rectangle: https://pasteboard.co/JSKOuGr.png

How do you replace the issue?

1. Open an existing linux or install a new one with plasma 5.21
    (For examples: Original Arch, Calam Arch, Manjaro KDE, KDE Neon)
2. Install xfreerdp
3. Prepare a “window rule” to xfreerdp with “Window title” -> Substring Match” -> <some name> rule on.: System settings -> 
    Window Management -> Window Rule
    For example: https://pasteboard.co/JSKOuGr.png 
4. maybe need a restart
5. Connect 2 monitors (or +1 to laptop)
5. Run xfreerdp with /multimon /t:<name> parameter. 

RD recognizes 2 monitors on Windows,  but you can't see all RD screens on linux (only the left one).
I was tested on 2 different laptops, and 4 different linux with Plasma 5.21. 
Arch based distros: Original Arch  and “CalamOS” and “Manjaro”
Plasma 5.21+ xorg 1.20.10 + freerdp 2.3.1 and 2.2.0
Ubuntu based distro: KDE Neon + Plasma 5.21 + xorg 1.20.9 + freerdp 2.2.0

If you downgrade to Plasma 5.20, with no changes on other settings, everything is working well.
If you are using Plasma 5.21 and deleting the “Window Title” rule from all “window rule”, /multimon is working well.

Try please.

I hope it is help for you.

**Comment by akallabeth** [comment]
@gtiborcz ok, I just don´t get what I should do other than redirect you to the `plasma` developers, as you´ve clearly identified the problem yourself.
Closing this now as it is not a freerdp bug
