### ISSUE TITLE
FreeRDP compilation issue in windows

### ISSUE THREAD

**Issue by srivatsagowda** [FreeRDP/FreeRDP#6883]
Getting following error when i tried compiling 2.3.0 version of freeRDP using Visual studio 2019. I'm not sure how to resolve this issue. Please help.

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUSB_1_INCLUDE_DIR
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb
   used as include directory in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb
LIBUSB_1_LIBRARY
    linked by target "urbdrc-client-libusb" in directory E:/Freerdp/FreeRDP/channels/urbdrc/client/libusb

**Comment by akallabeth** [comment]
This is an issue tracker not a help forum.
Compilation see https://github.com/FreeRDP/FreeRDP/wiki
See github discussions, mailing list or irc.
