### ISSUE TITLE
Indirect smartcard support in MacOS

### ISSUE THREAD

**Issue by vscfreire** [FreeRDP/FreeRDP#6898]
**Description**
I have to use my company jump server to sign documents in another server with my national ID card. So, basically, I connect from my Mac to a Windows Server 2016 jump server and then, using the Microsoft RDP Client to a final signing server Windows Server 2016.

If I use my Windows laptop, this scenario works perfectly with FreeRDP. If I use my Mac, the jump server RDP client freezes when I try to use the signing application in the final signing server. If instead of FreeRDP, I use the Mac Microsoft RDP Client, to connect to the jump server, the signing in the final server doesn't freeze the connection.

**To Reproduce**
1. Connect to a RDP jump server with smartcard support from a Mac client device
2. From the jump server connect to the final RDP server with smartcard support
3. In the final server, try to use the smartcard connected to the Mac client to sign a document
4. The RDP connection from the jump server to the final server freezes (if I take the smartcard from the smartcard reader it unfreezes)

**Expected behavior**
Being able to use my smartcard even with indirect RDP connections with FreeRDP in MacOS. 
If I use Microsoft RDP client in my Mac or if I instead of a Mac, use FreeRDP from a Windows device, the indirection works.

**Application and Environment details**
* FreeRDP stable2.0 in MacOS Big Sur
* Jump server with Windows Server 2016 and Microsoft RDP client.
* Final server with Windows Server 2016

**Comment by akallabeth** [comment]
Thinking about this a bit and the fact we observed broken return data with `SCardGetAttrib` with `SCARD_AUTOALLOCATE` it might help to mange the buffer allocation in freerdp, will create a test branch soon

**Comment by akallabeth** [comment]
@vscfreire ok, created https://github.com/akallabeth/FreeRDP/tree/smart_no_auto which does not use `SCARD_AUTOALLOCATE` for `SCardGetAttrib`.
If my suspicion is correct, this should work better for your case.

**Comment by vscfreire** [comment]
@akallabeth Tested, and retested and the behavior is the same. I looked carefully to see if anything was diferente, even if it was blocking, but it's similar.

**Comment by vscfreire** [comment]
@akallabeth By the way, maybe this info is relevant: it sporadically works, even before this change. I would say, one in ten tries.

**Comment by akallabeth** [comment]
@vscfreire I think maybe #6913 will help you too, there was a nasty little bug hidden in `SCardGetAttrib` which might explain your sporadic issues

**Comment by vscfreire** [comment]
@akallabeth Just tested, unfortunately it doesn't change the behavior in Mac. 

One thing I found out last week is that besides working from Windows, it also works from Linux (9 out of 10). Only the Mac has this blocking effect most of the time.
