### ISSUE TITLE
Multimedia Redirection problem (audio redirection): flv (Youtube)

### ISSUE THREAD

**Issue by myhasti** [FreeRDP/FreeRDP#690]
Dear all

When I'm using below command for playing the "Big Buck Bunny" (or other movie) with Windows Media Player, I can hear audio on the client side, 

xfreerdp -u xxxx -p xxxx --plugin drdynvc --data tsmf -- x.x.x.x

But when I play a clip from the "youtube.com", video redirection is correctly worked but I can't hear anything.

**Comment by hardening** [comment]
no feedback, closing
