### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by emeraldservices** [FreeRDP/FreeRDP#6915]
Thanks for docs/README.android reference. I installed Cygwin64 Terminal to run 'bash ./scripts/android-build-freerdp.sh --ndk <ANDROID_NDK> --sdk <ANDROID_SDK>'

it ran and give me

find: '/cmake': No such file or directory which: no ccache in (/mingw64/bin:/usr/bin:/c/Users/w-t/bin:/c/Users/w-t/AppData/Local/Yarn/config/global/node_modules/.bin:/c/Users/w-t/AppData/Roaming/npm:/c/Users/w-t/AppData/Roaming/Composer/vendor/bin:/c/laragon/bin/laragon/utils:/c/laragon/bin/mysql/mysql-5.7.24-winx64/bin:/c/laragon/bin/php/php-7.2.19-Win32-VC15-x64:/c/laragon/bin/composer:/c/laragon/bin/apache/httpd-2.4.35-win64-VC15/bin:/c/laragon/bin/redis/redis-x64-3.2.100:/c/laragon/bin/nodejs/node-v12:/c/laragon/bin/nginx/nginx-1.16.0:/c/laragon/bin/notepad++:/c/laragon/bin/telnet:/c/laragon/bin/ngrok:/bin:/cmd:/usr/bin:/mingw64/bin:/c/laragon/bin:/c/laragon/usr/bin:/c/laragon/bin/putty:/c/laragon/bin/cmder/bin:/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/ProgramData/chocolatey/bin:/c/Program Files/Java/jdk1.8.0_181:/c/Program Files/Git/cmd:/c/Program Files/MongoDB/Server/4.2/bin:/c/WINDOWS/System32/OpenSSH:/c/Program Files/openssl/bin:/c/Program Files/nodejs:/c/Program Files (x86)/Yarn/bin:/c/Users/w-t/AppData/Local/Microsoft/WindowsApps:/c/Users/w-t/AppData/Local/Android/Sdk/platform-tools:/c/Users/w-t/AppData/Local/Android/Sdk/platforms:/c/Users/w-t/AppData/Local/Android/Sdk/tools:/c/Users/w-t/AppData/Local/Android/Sdk/tools/bin:/c/Users/w-t/AppData/Local/Android/Sdk/emulator:/c/Program Files/Java/jdk1.8.0_181/bin:/c/Users/w-t/AppData/Local/Programs/Microsoft VS Code/bin:/c/Users/w-t/AppData/Roaming/npm:/c/Users/w-t/AppData/Local/Yarn/bin:/c/Program Files/Git/usr/bin:/c/Program Files/Git/usr/share/vim/vim74:/c/laragon/bin/cmder) ./scripts/android-build-common.sh: line 30: [: too many arguments ./scripts/android-build-common.sh: line 34: [: too many arguments ./scripts/android-build-freerdp.sh: line 21: source: /d/alihaider/New: is a directory ./scripts/android-build-freerdp.sh: line 75: [: too many arguments ./scripts/android-build-freerdp.sh: line 80: [: too many arguments [RUN] mkdir -p /d/alihaider/New folder/New folder/FreeRDP-master ./scripts/android-build-freerdp.sh: line 152: [: -eq: unary operator expected ./scripts/android-build-freerdp.sh: line 152: [: -eq: unary operator expected ./scripts/android-build-freerdp.sh: line 152: [: -eq: unary operator expected ./scripts/android-build-freerdp.sh: line 152: [: -eq: unary operator expected Successfully build library for architectures armeabi-v7a x86 x86_64 arm64-v8a

But I did not find directory client/Android/Studio/freeRDPCore/src/main/jniLibs and library builds. Also the app crashed just as mentioned above.
Can you tell me what is the problem here?

**Comment by akallabeth** [comment]
windows is not supported.
also please stop double posting and opening issues for each response.

**Comment by emeraldservices** [comment]
Ok Sir I'm sorry.
