### ISSUE TITLE
Enable automatic updates to F-Droid repository?

### ISSUE THREAD

**Issue by gbakeman** [FreeRDP/FreeRDP#6916]
Apologies if this isn't the appropriate place for this. Thank you for quickly addressing my last issue #6900 . F-Droid apparently [supports automatically updating apps](https://f-droid.org/en/docs/Update_Processing/) when a new version is released in another repository, although the [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.freerdp.afreerdp.yml) does not have this enabled. In the interest of efficiency, could this be enabled?

Thank you!

**Comment by akallabeth** [comment]
@gbakeman we can consider this when the build process does not require that many 'hacks' (openh264 with old NDK, ...)
