### ISSUE TITLE
Graphical glitches connecting to XRDP egfx installation that has none with MSTSC

### ISSUE THREAD

**Issue by Nexarian** [FreeRDP/FreeRDP#6922]
When connecting to the in-progress `egfx` branch of XRDP using avc420, I see graphical glitches that I don't see with MSTSC. I'm nearly 100% certain MSTSC is also using AVC420 in this context as well due to the XRDP logs, so I suspect there is a problem with the way FreeRDP is processing AVC420 that may not be present in AVC444.

**Describe the bug**
There is a lot of ghosting and glitches. A lot of time the screen is monochrome. It looks like it might be some alignment issue.

**To Reproduce**
1. Build a VM with the `egfx` branch of XRDP
2. Connect to it with `/gfx:avc420`
3. Observe glitches.

**Expected behavior**
No glitches

**Screenshots**
![Screen Shot 2021-03-19 at 4 26 01 PM](https://user-images.githubusercontent.com/3752093/111844612-bd4aaa80-88d9-11eb-8ecb-bfe2dfa55fe3.png)

**Application details**
* FreeRDP version: `This is FreeRDP version 3.0.0-dev (fab649a1b)`
* Command line used: `/usr/local/bin/xfreerdp /bpp:32 /v:[IP ADDRESS]:3389 /u:[username] /p:[password] /w:1000 /h:1000 /gfx:avc420 /network:auto /log-level:debug`
* Output of `xfreerdp /buildconfig`
```
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_STRNDUP=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 9.3.0
Target architecture: x64
```
* OS version connecting to (server side): `Ubuntu 20.04.2`
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`  -- Attached

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Architecture: amd64

**Additional context**
Here is how to set up an XRDP VM (See this link as well https://github.com/neutrinolabs/xrdp/wiki/Building-on-Debian-8):

- Download and install VirtualBox version VirtualBox-6.1.18-142142
- Create the VirtualBox image based on Ubuntu 20.04.2.0:
	- https://releases.ubuntu.com/20.04.2.0/ubuntu-20.04.2.0-desktop-amd64.iso?_ga=2.115291975.13181609.1616648710-544801159.1616648710
	- Set network to Bridged Adapter

- `sudo apt install gcc make perl`

- Install the guest additions

- `sudo apt install net-tools openssh-server`

- Get the IP address using ifconfig (Check the non-lo adapter's IP address)

- Log out

- SSH into the IP address

- `sudo apt-get install git autoconf libtool pkg-config gcc g++ make  libssl-dev libpam0g-dev \
		 libjpeg-dev libx11-dev libxfixes-dev libxrandr-dev  flex bison libxml2-dev \
		 intltool xsltproc xutils-dev python-libxml2 g++ xutils libfuse-dev \
		 libmp3lame-dev nasm libpixman-1-dev xserver-xorg-dev libx264-dev gnome mate`
			 
- mkdir ~/xrdp-github

```
git clone --branch egfx --recursive https://github.com/jsorg71/xrdp.git
cd xrdp
./bootstrap
./configure --enable-x264
make clean all
sudo make install
```

```
git clone --branch egfx --recursive https://github.com/jsorg71/xorgxrdp.git
./bootstrap
./configure
make clean all
sudo make install
```

- sudo dpkg-reconfigure xserver-xorg-legacy
	- Set to "anybody"

```
- sudo systemctl enable xrdp
- sudo service xrdp restart
```

Try to connect to xrdp with xfreerdp using `/gfx:avc420`. You will likely get a blank screen. Run `sudo service xrdp restart` and try again

**Comment by akallabeth** [comment]
@Nexarian thank you for testing this. Just found the same issue yesterday while testing against windows 8.1.
I´m currently in favor of deactivating `AVC420` altogether as there is no working implementation anyway (there are graphical glitches even with `mstsc` and windows 8.1 is the only os I know of so far that even has this enabled)

**Comment by Nexarian** [comment]
That does make sense, though it would make development of AVC444 for XRDP more difficult. Also, could these glitches be a harbinger of bugs in the AVC420 implementation?

**Comment by akallabeth** [comment]
@Nexarian `AVC444` is independent of `AVC420` (just start with `luma` frames and ignore `chroma` and you have the same image quality as `AVC420`)
and no, the `AVC444` implementation did fix these stride related issues (at least the v2 chroma frames)

**Comment by Nexarian** [comment]
But AVC444 is a weaving together of two AVC420 packets, right? So in theory, you need to do 2x 420 compressions and link them together to make AVC444 (V1 and V2). If there were to be a flaw in the AVC420 encoding, then theoretically that could appear in the combined AVC444 output. Ergo, investigating bugs in 420 may improve 444.

What am I missing?

**Comment by akallabeth** [comment]
@Nexarian yes and no. the 'luma' frame component is just a simple avc420 frame, the chroma is the missing uv data. if you just ignore the chroma for a start you have a working implementation. also the avc420 mode wildly mixes codecs (clear codec, ...) which does no longer happen with avc444

**Comment by Nexarian** [comment]
@akallabeth The glitching began to be introduced with this commit: https://github.com/FreeRDP/FreeRDP/commit/50acf72615a00e8c6dc33507d3f9f51d4d116a00

The commit before does not have the same glitching and color distortion: https://github.com/FreeRDP/FreeRDP/commit/c67e4df96bf69c117d5b186653d6482b61c48ba6

**Comment by Nexarian** [comment]
I've discovered more. It was the removal of this function: `avc_yuv_to_rgb` -- If I add it back, the color distortion is gone.

**Comment by vscfreire** [comment]
@akallabeth I would recommend not to remove AVC420 support, there are Windows RDS server versions that don't support 444 and that are still widely used.

**Comment by akallabeth** [comment]
@vscfreire then the client just falls back to the other codecs in use just like mstsc does.

**Comment by vscfreire** [comment]
@akallabeth fallback is an option but if I remember correctly, from my testing a while ago, I had better experience with avc420 than with remotefx connecting to Windows Server 2012, for example.

**Comment by Nexarian** [comment]
Much SLOWER codecs. The speed of the H264 compression in my experience is as the Microsoft documentation puts it "nearly real time."

**Comment by Nexarian** [comment]
I'm still playing with the code to discern exactly what the difference is here. I haven't figured it out yet, but now that I've narrowed it down, it's only a matter of time.

**Comment by akallabeth** [comment]
@vscfreire that is most likely true. `H264` uses hardware backed encoding which does have speed benefits server side. Client wise avc420 is a poor envelope as it mixes different codecs which eliminates easy implementation with only a h264 decoder (which avc444 provides due to not mixing codecs)

**Comment by akallabeth** [comment]
@Nexarian did have a look at this, you´re right, the old yuv conversion routine works without glitches, with the new one I can see them too.
Code wise they look (nearly) identical (in the single thread case with the YUV decoder):
just decode one rectangle after another in a loop.
Only difference I can spot is the parameter struct, but I fail to find what differs.

**Comment by akallabeth** [comment]
@Nexarian ok, I have created a pr which fixes the artifacts for my test setup (still not entirely sure why, but it might have to do with compiler optimisations)

**Comment by Nexarian** [comment]
Yeah, could be compiler, could be an order of operations issue that is really hard to notice. Pointer arithmetic can be tricky :)

Anyway, I've confirmed this works with XRDP as well! Thank you for the fix. Hope to see it merged soon!
