### ISSUE TITLE
Two issues in Win7 as server

### ISSUE THREAD

**Issue by davidcao2000** [FreeRDP/FreeRDP#6923]
My server is Win7 SP1, client is Win10 20H2.  FreeRDP version is 2.3.2
client command:  wfreerdp /v:192.168.0.110 /u:xxx /p:xxx /w:1920 /h:1080 /cert-ignore /bpp:32
Everything is ok , but if I run AutoCAD2008 in server,  two issues occur:
1. the cursor is not the right one. Please see picture 1. The upper-left corner is the first cursor (cross), but the cross remained there after mouse has moved to the bottom right corner(arrow). The cross cursor should follow the mouse's movement, the arrow cursor should not appear.

![P1](https://user-images.githubusercontent.com/19923442/112454808-072d0800-8d94-11eb-8c8e-67d997ffe81b.jpg)

2. Afterimage effects(residual artifacts)?  If I draw a rectangle(press the left button of mouse and move to another position),
the border of the rectangle will follow the mouse, but the old image of border would not be wiped off.  Please see picture 2.
The blue block is the rectangle, the white lines is the rectangl's border.
![P2](https://user-images.githubusercontent.com/19923442/112454848-10b67000-8d94-11eb-9d99-4940a3ab4244.jpg)

Thank you.

**Comment by akallabeth** [comment]
we´re currently looking for a maintainer for the windows client, so your mileage may vary.

Things you could try: `/rfx` is supported by windows 7 and `/gfx` with some patches that might help with the artifacts.
