### ISSUE TITLE
#pragma GCC diagnostic ignored "-Wimplicit-fallthrough" warnings

### ISSUE THREAD

**Issue by user-36428** [FreeRDP/FreeRDP#6925]
Compiling Release version 2.3.2 on Ubuntu 16.04.7, I am getting several fallthrough pragma warnings at the following areas:

/usr/local/src/freerdp-2.3.2/winpr/libwinpr/utils/trio/trio.c:1372:9: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
/usr/local/src/freerdp-2.3.2/winpr/libwinpr/utils/trio/trio.c:1671:9: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
/usr/local/src/freerdp-2.3.2/winpr/libwinpr/crt/utf.c:45:9: warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wimplicit-fallthrough"

I understand these pragmas are not supported on GCC < 7 so I was wondering if Ubuntu 16.04 is still supported as it uses gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 

Apologies if no longer supported. Just wanted to mention that FreeRDP 2.3.2 is one of the best releases I have seen since the early 2.0 series. Thanks again for all the work you do on it.

**Comment by akallabeth** [comment]
well, we´re using newer compilers for our tests, and this is only a warning, so can be ignored.
