### ISSUE TITLE
Do not exit terminal session by ESC & session freezes when entering special accessibility on Windows Server 2019

### ISSUE THREAD

**Issue by muhamor2022** [FreeRDP/FreeRDP#6930]
When I connect to Windows 2019 terminal server from client under Ubuntu 18.04-20.04 I can't quit using ESC. Session hangs!
And when I go into Windows Server accessibility the session hangs! https://ibb.co/4NrYYg2

From my Ubuntu 18.04/20.04 I am using the following parameters:

xfreerdp /u: /kbd-type:en-us /f /bpp:16 /network:broadband /sec:tls /cert-ignore /wallpaper -themes /v:myserver
FreeRDP version 2.2.0 (n/a)
Ubuntu 20.04.2 LTS | Linux PC 5.4.0-42-generic

**Comment by akallabeth** [comment]
ok, check your server config?
this looks like the normal logon procedure so, please either add some information on why this is an RDP issue or I´ll keep this closed.
