### ISSUE TITLE
CMake compiling FreeRDP on Windows 

### ISSUE THREAD

**Issue by MrProper5050** [FreeRDP/FreeRDP#6940]
**I am following the tutorial on how to compile FreeRDP on windows for VS! I have installed all the extra layouts I need such as:** **meson**
**cmake
nasm**
**perl
openh264
openssl
freerdp......**

**And I got to the point of building the library through Cmake, and this is what I get when building:**

C:\Windows\System32>cmake` -GNinja -BC:\Users\zhilk\Desktop\testRDP\freerdpBuild -HC:\Users\zhilk\Desktop\testRDP\freerdp -DCMAKE_INSTALL_PREFIX=C:\Users\zhilk\Desktop\testRDP\freerdp -DCMAKE_BUILD_TYPE=Release
CMake Deprecation Warning at CMakeLists.txt:21 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is MSVC 19.28.29913.0
-- The CXX compiler identification is MSVC 19.28.29913.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx86/x86/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx86/x86/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
FREERDP_VERSION=3.0.0-dev
-- Git Revision aeba30a50
-- MSVC: using dynamically-linked runtime (/MD and /MDd).
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Looking for strndup
-- Looking for strndup - not found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - not found
-- Looking for include file execinfo.h
-- Looking for include file execinfo.h - not found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file sys/modem.h
-- Looking for include file sys/modem.h - not found
-- Looking for include file sys/filio.h
-- Looking for include file sys/filio.h - not found
-- Looking for include file sys/sockio.h
-- Looking for include file sys/sockio.h - not found
-- Looking for include file sys/strtio.h
-- Looking for include file sys/strtio.h - not found
-- Looking for include file sys/select.h
-- Looking for include file sys/select.h - not found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - not found
-- Performing Test HAVE_TM_GMTOFF
-- Performing Test HAVE_TM_GMTOFF - Failed
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping disabled feature ZLIB for compression (data compression)
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Found OpenSSL: C:/Program Files/OpenSSL-Win64/lib/libssl.lib;C:/Program Files/OpenSSL-Win64/lib/libcrypto.lib (found version "1.1.1j")
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature OSS for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Skipping disabled feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature OpenCL for codec (use OpenCL library)
--     Enable feature OpenCL using "-DWITH_OPENCL=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature LAME for codec (lame MP3 audio codec library)
--     Enable feature LAME using "-DWITH_LAME=ON"
-- Skipping optional feature FAAD2 for codec (FAAD2 AAC audio codec library)
--     Enable feature FAAD2 using "-DWITH_FAAD2=ON"
-- Skipping optional feature FAAC for codec (FAAC AAC audio codec library)
--     Enable feature FAAC using "-DWITH_FAAC=ON"
-- Skipping optional feature soxr for codec (SOX audio resample library)
--     Enable feature soxr using "-DWITH_SOXR=ON"
-- Skipping optional feature GSSAPI for auth (add kerberos support)
--     Enable feature GSSAPI using "-DWITH_GSSAPI=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- Using OpenSSL Version: 1.1.1j
using default plugins location
CMake Deprecation Warning at winpr/CMakeLists.txt:18 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for timer_create
-- Looking for timer_create - not found
-- Looking for timer_delete
-- Looking for timer_delete - not found
-- Looking for timer_settime
-- Looking for timer_settime - not found
-- Looking for timer_gettime
-- Looking for timer_gettime - not found
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find Cairo (missing: CAIRO_LIBRARIES CAIRO_INCLUDE_DIR)
CMake Warning at libfreerdp/CMakeLists.txt:102 (message):
  -DWITH_SWSCALE=OFF and -DWITH_CAIRO=OFF, compiling without image scaling
  support!

CMake Deprecation Warning at rdtk/CMakeLists.txt:18 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Adding STATIC channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding DYNAMIC channel client "video": Video optimized remoting Virtual Channel Extension
-- Adding DYNAMIC channel client "urbdrc": USB Devices Virtual Channel Extension
-- Adding DEVICE channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding STATIC channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding STATIC channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding DYNAMIC channel client "rdpgfx": Graphics Pipeline Extension
-- Adding DYNAMIC channel client "rdpei": Input Virtual Channel Extension
-- Adding STATIC channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding STATIC channel client "rdp2tcp": Tunneling TCP over RDP
-- Adding STATIC channel client "rail": Remote Programs Virtual Channel Extension
-- Adding DEVICE channel client "printer": Print Virtual Channel Extension
-- Adding DYNAMIC channel client "geometry": Geometry tracking Virtual Channel Extension
-- Adding STATIC channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding DYNAMIC channel client server "echo": Echo Virtual Channel Extension
-- Adding DEVICE channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding DYNAMIC channel client "disp": Display Update Virtual Channel Extension
-- Adding STATIC channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding DYNAMIC channel client server "audin": Audio Input Redirection Virtual Channel Extension
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.20/Modules/CPack.cmake:690 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'CPACK_BINARY_ZIP'.
Call Stack (most recent call first):
  CMakeCPack.cmake:102 (include)
  CMakeLists.txt:1106 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUSB_1_INCLUDE_DIR
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb
   used as include directory in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb
LIBUSB_1_LIBRARY
    linked by target "urbdrc-client-libusb" in directory C:/Users/zhilk/Desktop/testRDP/freerdp/channels/urbdrc/client/libusb

CMake Warning (dev) in channels/urbdrc/client/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "urbdrc-client":

    "LIBUSB_1_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in channels/urbdrc/client/libusb/CMakeLists.txt:
  Policy CMP0021 is not set: Fatal error on relative paths in
  INCLUDE_DIRECTORIES target property.  Run "cmake --help-policy CMP0021" for
  policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  Found relative path while evaluating include directories of
  "urbdrc-client-libusb":

    "LIBUSB_1_INCLUDE_DIR-NOTFOUND"

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**I searched the Internet for this error `CMake Generate step failed. Build files cannot be regenerated correctly.` but did not understand anything at all. I need help, I don't understand cmake at all ...**

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting
https://github.com/FreeRDP/FreeRDP/wiki/Compilation

**Comment by jspraul** [comment]
It seems like [libusb](https://github.com/libusb/libusb/releases) is required to build even when cmake is passed -DCHANNEL_URBDRC_CLIENT=off; example for VS2k17:

`cmake . -G"Visual Studio 15 Win64" -DLIBUSB_1_INCLUDE_DIR="c:\libusb-1.0.24\include\libusb-1.0" -DLIBUSB_1_LIBRARY="c:\libusb-1.0.24\VS2017\MS64\static\libusb-1.0.lib" -DCHANNEL_URBDRC_CLIENT=off`

**Comment by akallabeth** [comment]
@jspraul no it is not. If you use `-DCHANNEL_URBDRC=OFF` it works.
