### ISSUE TITLE
Multi-monitor issue freerdp 2.3.2

### ISSUE THREAD

**Issue by VictorKruger** [FreeRDP/FreeRDP#6946]
**Describe the bug**
FreeRDP is recognizing my 3 monitors as one large monitor. It will place the remote session on the left monitor in full screen.  When I exit full screen, the remote session spans across all 3 monitors.

**To Reproduce**
xfreerdp /d:<removed> /u:<removed> /v:192.168.0.64 /sound /microphone:sys:pulse /bpp:32 /w:1920 /h:1080 /f /monitors:0,2 /multimon /cert-ignore

**Expected behavior**
The command should create a full screen remote session on the middle and right screen.

**Application details**
*  FreeRDP version 2.3.2 (2.3.2)
* Command line used: see above
* Output of `xfreerdp /buildconfig`
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DISTCC=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=OFF WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=OFF WITH_XKBFILE=OFF WITH_XRANDR=OFF WITH_XRENDER=OFF WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 9.3.0
Target architecture: x64

* OS version connecting to Windows 10 Professional

* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

Used release branch version 2.3.2 - freerdp-2.3.2.tar.gz 
[CMakeCache.txt](https://github.com/FreeRDP/FreeRDP/files/6281158/CMakeCache.txt)

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Mint 20.1 Cinnamon
 - Architecture: amd64

**Additional context**
When I run xfreerdp /monitor-list I get the following result:  * [0] 5760x1080	+0+0

**Comment by akallabeth** [comment]
well, looks like your driver is reporting the setup as a single monitor?
ẁhat does `xrandr -q` tell you?

**Comment by VictorKruger** [comment]
Hello,

Below is the link to my xrandr info.  I also included the gpu info as well in a separate file. 

It does show at the top that the resolution is set to 5760 x 1080, however version 2.2 from the apt repository recognizes that I have 3 separate monitors.

Linux:~$ xfreerdp /monitor-list
      * [0] 1920x1080	+1920+0
        [1] 1920x1080	+0+0
        [2] 1920x1080	+3840+0
Linux:~$ xfreerdp /version
This is FreeRDP version 2.2.0 (n/a)

Package freerdp is a virtual package provided by:
  freerdp2-x11 2.2.0+git202007201338-0+remmina202102032151.rd2ba84a68.dfabe85c94~ubuntu20.04.1

Thanks,

[gpuinfo.txt](https://github.com/FreeRDP/FreeRDP/files/6287943/gpuinfo.txt)
[xrandrinfo.txt](https://github.com/FreeRDP/FreeRDP/files/6287911/xrandrinfo.txt)

**Comment by akallabeth** [comment]
@VictorKruger ok, missed it first, but your build is broken. `WITH_XINERAMA=OFF WITH_XKBFILE=OFF WITH_XRANDR=OFF WITH_XRENDER=OFF ` suggests not all required `X11` dependencies were used during build.
