### ISSUE TITLE
Smart-sizing broken in 2.3.2 (r569458)

### ISSUE THREAD

**Issue by konkovaa** [FreeRDP/FreeRDP#6952]
**Describe the bug**
Everything well without smart-sizing option, but with smart-sizing:

[ERROR][com.winpr.timezone] - Unable to get current timezone rule
[INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
[INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
[INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
[INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[INFO][com.freerdp.channels.rdpdr.client] - Loading device service drive [home] (static)
[WARN][com.freerdp.color] - SmartScaling requested but compiled without libcairo support!
[ERROR][com.freerdp.core.fastpath] - Fastpath update New Pointer [b] failed, status 0
[ERROR][com.freerdp.core.fastpath] - fastpath_recv_update() - -1
[ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
[ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[INFO][com.freerdp.client.common] - Network disconnect!
[ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor

**To Reproduce**
Just try using the smart-resizing option.

**Application details**
* FreeRDP version 2.3.2
* xfreerdp /u:<username> /v:<host:port> /size:<widthxheight> /smart-sizing +fonts +home-drive
* Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H=1 HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H=1 HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=false WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=false WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=false WITH_FAAD2=false WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=false WITH_GSSAPI=OFF WITH_GSSAPI_HEIMDAL=false WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=false WITH_ICU=true WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=false WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=true WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=false WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=false WITH_PROFILER=OFF WITH_PULSE=false WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=false WITH_SSE2=true WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=false WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -O2 -pipe -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            Clang, 11.0.1

* Windows Server 2008 R2 Standart

**Environment (please complete the following information):**
* OS FreeBSD 13.0-STABLE #0 stable/13-n245043-7590d7800c44
* Architecture: amd64

**Additional context**
Downgrading back to 2.2.0 (no other changes) solves the problem.
Both versions are built from FreeBSD ports.
See also FreeBSD PR #254914

**Comment by akallabeth** [comment]
1. `WITH_CAIRO=OFF  WITH_SWSCALE=OFF`
2.  [WARN][com.freerdp.color] - SmartScaling requested but compiled without libcairo support!

Please read the warnings/errors of `cmake` configure and the log you just posted ;)

**Comment by konkovaa** [comment]
>     1. `WITH_CAIRO=OFF  WITH_SWSCALE=OFF`
>     2. `[WARN][com.freerdp.color] - SmartScaling requested but compiled without libcairo support!`
> 
> Please read the warnings/errors of `cmake` configure and the log you just posted ;)

I've seen this, but, there is no libcairo option.
Build options:
	ALSA           : off
	CUPS           : off
	FAAC           : off
	FAAD           : off
	FFMPEG         : on
	GSM            : off
	GSTREAMER      : off
	ICU            : on
	KERBEROS       : off
	LAME           : off
	MANPAGES       : on
	OPENH264       : off
	PCSC           : off
	PULSEAUDIO     : off
	SOXR           : off
	SSE            : on
	WAYLAND        : off
	X11            : on

**Comment by VVD** [comment]
>     1. `WITH_CAIRO=OFF  WITH_SWSCALE=OFF`
> 
>     2. `[WARN][com.freerdp.color] - SmartScaling requested but compiled without libcairo support!`
> 
> 
> Please read the warnings/errors of `cmake` configure and the log you just posted ;)

Did you changed something in build system between 2.2.0 and 2.3.0?

**Comment by akallabeth** [comment]
@konkovaa where do you get these options from? Never seen these, so they are part of your build configuration scripts/ports. Check the `CMake` options, easiest with `ccmake` or manually in `CMakeFiles.txt` and `cmake` folder in source tree.

@VVD no, the same as for all `2.0` releases. There seems to be some misconception here, do you know why you use the build options you have? They do not map 1:1 to the ones we use and have sometimes never been used...

**Comment by konkovaa** [comment]
> @konkovaa where do you get these options from? Never seen these, so they are part of your build configuration scripts/ports. Check the `CMake` options, easiest with `ccmake` or manually in `CMakeFiles.txt` and `cmake` folder in source tree.
> 

According Handbook:
cd /usr/ports/net/freerdp/
make config <---- you can choose build options here
make install clean 

Anyway, there is something wrong with the build version 2.3.2.
I confirm there is a drag and drop issue as described in 2.3.2 # 6948, whereаs it works well in 2.2.0.

**Comment by akallabeth** [comment]
@konkovaa ok, then please file a bug report with `FreeBSD` as these are not `FreeRDP` options.

**Comment by konkovaa** [comment]
@akallabeth I've already done it - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254914
Thank you for your time and job!

**Comment by akallabeth** [comment]
@konkovaa ok. good luck with eliminating this nasty bug
