### ISSUE TITLE
Freerdp does not work without lowering security

### ISSUE THREAD

**Issue by sachinh1980** [FreeRDP/FreeRDP#6958]
Hello,

tried to setup freerdp on Sles 12 SP3 version which should connect to Windows 10 Server.  Initially it did not work 
simply by giving,

xfreerdp /v:1.7.X.X /u:admin

The suggestion from community was , to include following paramter,

xfreerdp /v:1.7.X.X /u:admin /sec:tls

This as well did not work. So I had to disable the option on Windows Server-RDP-Settings,  Link [ https://github.com/FreeRDP/FreeRDP/issues/3139 ]

wherein we have to disable  "Allow connections only from computers running Remote Desktop with Network Level Authentication (recommended)"

Then it opens up Windows login page.

Ok it works so but does it not mean that we are disabling the recommended settings for Remote-Connection on Windows Server and lowering the security? Is there a better secure solution? Please help.

**Comment by akallabeth** [comment]
@sachinh1980 sorry, but what? The referenced issue has been fixed ages ago, so could you please start by providing data to what you´re using and what the problem is (log files to the rescure;))

**Comment by akallabeth** [comment]
Closing until data is provided.
For help or discussion please use the mailing list or IRC.

**Comment by sachinh1980** [comment]
What we are using? 
We are trying to setup Remote-Desktop between SLES 12 SP3 and Windows 10 Professional.  For this we have installed, 
3 freerdp RPMs.

freerdp-devel-2.0.0~git.1463131968.4e66df7-11.69.x86_64
freerdp-2.0.0~git.1463131968.4e66df7-11.69.x86_64
libfreerdp2-2.0.0~git.1463131968.4e66df7-11.69.x86_64
The relevant debug logs are attached herewith. Please let me know if you require further information. Thanks.

[zrdb5b_freerdp.txt](https://github.com/FreeRDP/FreeRDP/files/6318027/zrdb5b_freerdp.txt)

**Comment by akallabeth** [comment]
your version is too old, before the big NLA change (NLA version 6) by MS (the one where they had the authentication handshake broken)
update your freerdp version.

**Comment by sachinh1980** [comment]
> your version is too old, before the big NLA change (NLA version 6) by MS (the one where they had the authentication handshake broken)
> update your freerdp version.

Okay I might do that. My specific question is whether disabling NLA lowers the security of Windows?

**Comment by akallabeth** [comment]
well, define `security` ;)

the difference is that `NLA` authenticates the user before connection establishment (authentication handshake)
`TLS` on the other hand establishes an anonymous `TLS` tunnel and shows the windows login screen.

So, while with `NLA` your (plaintext) password never leaves your computer you write it into the remote session with `TLS`, so if your server is compromised (or your DNS entry) you could expose the credentials of users logging on.

**Comment by sachinh1980** [comment]
Security is already defined by Windows as "Recommended Settings for RDP"  ;)

So difference between NLA and TLS is only how they handle the authentication. One prior to connection and the other one post connection?

**Comment by akallabeth** [comment]
@sachinh1980 basically yes. (there are some slight differences, but that is only relevant for protocol implementors)
For public accessible systems it is desired to not have anonymous access (which `TLS` is, the session is already running) as that allows (easier) denial of service (takes more resources than just failed authentication)

**Comment by sachinh1980** [comment]
Thanks but in that case it is difficult to convience management. :( 

Any other alternative  as in Remmina or so? For us important is to have remote-desktop connection from linux to Windows. Application is irrelevant.

**Comment by akallabeth** [comment]
update freerdp, no other way. (Remmina is using freerdp too ;))
