### ISSUE TITLE
cmake: no such file or directory

### ISSUE THREAD

**Issue by thunshell** [FreeRDP/FreeRDP#6966]
**cmd:**
root01@root01-PC:~/Downloads/FreeRDP/scripts$ ./android-build-freerdp.sh --ndk "/home/root01/Android/Sdk/ndk/22.1.7171670" --sdk "/home/root01/Android/Sdk" --openh264-ndk "/home/root01/Android/android-ndk-r15c" --conf android-build-release.conf
**find: ‘/cmake’: no such file or directory**
[RUN] mkdir -p /home/root01/Downloads/FreeRDP/scripts/../build
[RUN] bash /home/root01/Downloads/FreeRDP/scripts/android-build-openh264.sh --src /home/root01/Downloads/FreeRDP/scripts/../build/openh264 --dst /home/root01/Downloads/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --sdk /home/root01/Android/Sdk --ndk /home/root01/Android/android-ndk-r15c --arch armeabi-v7a --target 21 --tag v1.8.0
**find: ‘/cmake’: no such file or directory**
Preparing checkout...
[RUN] mkdir -p /home/root01/Downloads/FreeRDP/scripts/../cache
[RUN] rm -rf /home/root01/Downloads/FreeRDP/scripts/../build/openh264
. . . . . .
[RUN] cd /home/root01/Downloads/FreeRDP/scripts/../build/openssl
[RUN] ./Configure android-arm -D__ANDROID_API__=21
Configuring OpenSSL version 1.1.1h (0x1010108fL) for android-arm
Using os-specific seed configuration
$ANDROID_NDK_HOME=/home/root01/Android/Sdk/ndk/22.1.7171670 is invalid at (eval 10) line 37.
**[ERROR]** ./Configure android-arm -D__ANDROID_API__=21 retured 2
**[ERROR]** bash /home/root01/Downloads/FreeRDP/scripts/android-build-openssl.sh --src /home/root01/Downloads/FreeRDP/scripts/../build/openssl --dst /home/root01/Downloads/FreeRDP/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --sdk /home/root01/Android/Sdk --ndk /home/root01/Android/Sdk/ndk/22.1.7171670 --arch armeabi-v7a --target 21 --tag OpenSSL_1_1_1h retured 1

**But I can run:**
root01@root01-PC:~/Downloads/FreeRDP/scripts$ cmake --version
cmake version 3.13.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by akallabeth** [comment]
from `docs/README.android`:
```
 For the Android port some additional dependencies need to be fulfilled:
 
 * for JNI
 - CMake >= 3.0 (install CMake from Android SDK. It is part of the SDK Tools)
 - Android NDK (>= r15c)
 
 * for the Java GUI
 - Android SDK
```

**Comment by TECHDUSHYANT** [comment]
I am not able to run the script , can you please help me 

~/downloads/rdp/freerdp-master/scripts
$ ./android-build-freerdp.sh --sdk C:\Users\POI\AppData\Local\Android\Sdk --ndk C:\Users\POI\AppData\Local\Android\Sdk\ndk\20.1.5948944
find: ‘/cmake’: No such file or directory
which: no ccache in (/c/Users/POI/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/POI/bin:/c/Program Files/Common Files/Oracle/Java/javapath:/c/Program Files/Microsoft MPI/Bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/DTS/Binn:/c/Program Files/TortoiseGit/bin:/cmd:/c/Program Files/OpenSSL-Win64/bin:/c/Users/POI/AppData/Local/Android/Sdk/cmake/3.18.1/bin:/c/Program Files/CMake/bin:/c/Users/POI/AppData/Local/Microsoft/WindowsApps:/c/Users/POI/.dotnet/tools:/c/Users/POI/AppData/Local/Android/Sdk/cmake/3.18.1/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)
find: ‘C:UsersPOIAppDataLocalAndroidSdk/cmake’: No such file or directory
[RUN] mkdir -p /c/Users/POI/downloads/rdp/freerdp-master/scripts/../build
[RUN] bash /c/Users/POI/downloads/rdp/freerdp-master/scripts/android-build-openssl.sh --src /c/Users/POI/downloads/rdp/freerdp-master/scripts/../build/openssl --dst /c/Users/POI/downloads/rdp/freerdp-master/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --sdk C:UsersPOIAppDataLocalAndroidSdk --ndk C:UsersPOIAppDataLocalAndroidSdkndk20.1.5948944 --arch armeabi-v7a --target 21 --tag openssl-1.1.1s --hash c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa
find: ‘/cmake’: No such file or directory
which: no ccache in (/c/Users/POI/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/POI/bin:/c/Program Files/Common Files/Oracle/Java/javapath:/c/Program Files/Microsoft MPI/Bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/DTS/Binn:/c/Program Files/TortoiseGit/bin:/cmd:/c/Program Files/OpenSSL-Win64/bin:/c/Users/POI/AppData/Local/Android/Sdk/cmake/3.18.1/bin:/c/Program Files/CMake/bin:/c/Users/POI/AppData/Local/Microsoft/WindowsApps:/c/Users/POI/.dotnet/tools:/c/Users/POI/AppData/Local/Android/Sdk/cmake/3.18.1/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)
find: ‘C:UsersPOIAppDataLocalAndroidSdk/cmake’: No such file or directory
export ANDROID_NDK to point to your NDK location.
[ERROR] bash /c/Users/POI/downloads/rdp/freerdp-master/scripts/android-build-openssl.sh --src /c/Users/POI/downloads/rdp/freerdp-master/scripts/../build/openssl --dst /c/Users/POI/downloads/rdp/freerdp-master/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --sdk C:UsersPOIAppDataLocalAndroidSdk --ndk C:UsersPOIAppDataLocalAndroidSdkndk20.1.5948944 --arch armeabi-v7a --target 21 --tag openssl-1.1.1s --hash c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa retured 1

$ cmake --version
cmake version 3.25.0-rc4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
