### ISSUE TITLE
Coverity tool reports some possible defects

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#6981]
**Describe the bug**
Coverity tool reports some possible defects in the freerdp 2.2.0 version. There is a list of the important ones: [scan-results-imp.err](https://github.com/FreeRDP/FreeRDP/files/6384241/freerdp-2.2.0-scan-results-imp.err.txt). There is a list of all of them: [scan-results.err](https://github.com/FreeRDP/FreeRDP/files/6384244/freerdp-2.2.0-scan-results.err.txt). Few of them are already fixed in master. I am going to propose fixes for the important ones...

**Comment by ondrejholy** [comment]
Some more details for the [scan-results-imp.err](https://github.com/FreeRDP/FreeRDP/files/6384241/freerdp-2.2.0-scan-results-imp.err.txt):
- The `USE_AFTER_FREE` defects look like false-positives, but I modified the code to make covscan happy.
- The `BAD_FREE` defect looks like a false-positive as well, but I added a comment to suppress it as it is not obvious.
- The `CPPCHECK_WARNING` defects also look like false-positives, but they are obvious, so I kept the code untouched.
- The `RESOURCE_LEAK` are mostly valid, so I provided fixes for most of them in https://github.com/FreeRDP/FreeRDP/pull/6982.

**Comment by akallabeth** [comment]
@ondrejholy thank you for the effort.
If possible, can you add a `.github/workflow/coverity.yml` to automatically check in the future?

**Comment by ondrejholy** [comment]
Hmm, it would be ideal to make Coverity tool part of GitHub CI, but I don't have totally any experience with it and I can't spend more time on it right now. I got those reports from our infrastructure when submitting new builds...

**Comment by akallabeth** [comment]
@ondrejholy ok. Thought you had played with `coverity` and already know how to set it up. Also busy currently, but would be a nice to have thing in addition to already existing checkers.
@hardening @mfleisz @bmiklautz anyone time for playing with the `CI`?

**Comment by bmiklautz** [comment]
Just a note: Coverity is in the meanwhile fully integrated and runs daily see https://github.com/FreeRDP/FreeRDP/blob/master/.github/workflows/coverity.yml for details
