### ISSUE TITLE
Error while compiling the libraries for android using the scripts

### ISSUE THREAD

**Issue by f48** [FreeRDP/FreeRDP#6986]
Hi! , i was trying to compile the libraries using the following commandline on the root project ->
"
./scripts/android-build-freerdp.sh \
  --ndk <path_to_ndk> \
  --sdk <path_to_sdk> \
  --openh264-ndk <path_to_ndk_15c> \
  --conf android-build-release.conf
"

![ss](https://user-images.githubusercontent.com/57172092/116540389-6083dc00-a8ea-11eb-9297-a5d3c5364999.PNG)
But an error message appears under a neon support issue

i have tried different ndk versions but im lost :,)
 if anyone knows why the issue might be i would really apreciate the help

thanks in advance!

**Comment by akallabeth** [comment]
did you start with a clean checkout (`git clean -xdf`)?
I´ve seen such errors when there are build files around from previous tries

**Comment by f48** [comment]
that was it, thank you very much
