### ISSUE TITLE
Please use proper sonames based on ABI compatibility

### ISSUE THREAD

**Issue by mike-jumper** [FreeRDP/FreeRDP#6990]
**Is your feature request related to a problem? Please describe.**

The soname of a library is intended to describe ABI compatibility. In FreeRDP's case, however, it's just a copy of the release version. This leads to software built against a particular version of the ABI continuing to be linked against newer versions, even though this is unsafe.

https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html describes this well:

> _**Never**_ try to set the interface numbers so that they correspond to the release number of your package. This is an abuse that only fosters misunderstanding of the purpose of library versions. Instead, use the `-release` flag (see [Release numbers](https://www.gnu.org/software/libtool/manual/html_node/Release-numbers.html#Release-numbers), but be warned that every release of your package will not be binary compatible with any other release.

See also:

https://en.wikipedia.org/wiki/Soname
https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html

**Describe the solution you'd like**

The soname of FreeRDP libraries should be updated relative to ABI compatibility per convention and as described here: https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html

If the ABI or behavior of the library changes, the soname should be bumped appropriately. For example:

* If `freerdp_do_thing()` becomes `FreeRDP_DoThing()`, or `updates->SomeHook` starts accepting a new parameter and now returns a boolean, software using the older ABI will unexpectedly break, and that's worth a bump.
* If memory allocation fundamentally changes between one version of the ABI and the next, software built against the previous version will either start leaking or start segfaulting, and that's worth a bump.

**Describe alternatives you've considered**

There aren't any. Users that update their FreeRDP packages without rebuilding everything that linked against FreeRDP may encounter strange behavior, segfaults, or memory leaks. There is no way for users or the system linker to know this ahead of time.

**Comment by akallabeth** [comment]
@mike-jumper already the case for 2.x
If you have any problems please report them ;)

**Comment by mike-jumper** [comment]
Thanks, @akallabeth, that's great to hear. With that being the case, it sounds like the problems we're encountering are mainly due to downstream packaging of pre-2.0.0 git snapshots and RCs.

For example:

* Debian 10's current non-backport package of FreeRDP is "2.0.0~git20190204.1.2693389a" - a git snapshot prior to 2.0.0. The soname of that package matches the soname of their 2.3.0 package in backports, though they are not compatible.
* CentOS / RHEL provided packages of 2.0.0-rc4 before switching to 2.1.1. The sonames of those packages will match, though they are not compatible.

Perhaps the situation will improve as the downstream ecosystem gradually cleanses itself of pre-2.0.0 snapshots.

**Comment by akallabeth** [comment]
@mike-jumper ah, ok. yes, we did have a few breakages during development, but try to keep them away from stable releases (which we neglected for too long :/)
