### ISSUE TITLE
not able to build ios 14 Xcode12.4

### ISSUE THREAD

**Issue by joyharesh13** [FreeRDP/FreeRDP#6992]
cmake -DCMAKE_TOOLCHAIN_FILE=cmake/iOSToolchain.cmake -GXcode

not able to build from this ... it shows error as in screenshot

![Screenshot 2021-05-04 at 2 05 54 PM](https://user-images.githubusercontent.com/47550798/116978840-e08eb500-ace1-11eb-853f-9b1e8a6e9bfe.png)
![Screenshot 2021-05-04 at 2 05 58 PM](https://user-images.githubusercontent.com/47550798/116978857-e5536900-ace1-11eb-9b49-4247f70340f5.png)

**Comment by akallabeth** [comment]
1. `docs/README.ios`
2. iOS is looking for a maintainer, so help is limited.
