### ISSUE TITLE
Linux: RemoteWebAccess should ask to open RDP file with freerdp 

### ISSUE THREAD

**Issue by johndoe7000** [FreeRDP/FreeRDP#6995]
Hello devs,

it would be great to integrate FreeRDP into the Linux Desktop... not only via terminal.
I mean... when I use RemoteWebAccess any Linux DE should be able to show FreeRDP as a choice to open RDP file.
Currently only Remmina is shown as a possible app, not FreeRDP.

Downloading the RDP file and then execute freerdp to open the file from terminal is useless, sorry.
Did I miss something?

**Comment by akallabeth** [comment]
1. You can simply write a `.desktop` file for your needs, see https://freedesktop.org/wiki/Howto_desktop_files/ that associates `.rdp` files with `xfreerdp` (and take the one from remmina as a starting point)
2. Open With in your file manager of choice also works ;)
