### ISSUE TITLE
Clipboard of FreeRDP frequently breaks clipboard content on host (X11)

### ISSUE THREAD

**Issue by tromech** [FreeRDP/FreeRDP#6999]
**Describe the bug**
I frequently experience issues with the local clipboard (copy/paste) not working properly on my machine (Linux Mint 20.1). In particular, copied content regularly (feels like once every 3-10 times maybe) cannot not be pasted (Ctrl-V) anymore, as if the clipboard content got lost - and in such cases, applications I'm trying to paste into will even freeze for some seconds before reacting again (and then, not actually pasting anything, as if the clipboard had been empty).

After some testing, I am able to clearly pin this to FreeRDP, which I have usually running on the machine, connected to a Windows 10 server. Note that I have the copy/paste issues also if neither of them is related to the FreeRDP session (i.e., copy/pasting from/to other applications I have running on my local machine).

If I stop the FreeRDP session, the problems are gone. Likewise, it's also not a problem if I start the session with `-clipboard`.

I tried things with two versions:

1. default from mint repos: `2.2.0`
2. recent nightly build `3.0.0-dev (892cbe326)`

The symptoms are somewhat different between those versions (the "freeze" on paste only occurs with (1.) for me), but the general issue with "broken" clipboard content is present in both. Seems like some race condition to me.

**To Reproduce**
That took me some time, since it's not happening always / sometimes hard to pin down. Following steps are a bit artificial, but reproduce the issue very well for me now.

1. Open a terminal and run following command (to observe the 'content' / types of clipboard content). Keep that terminal visible on the side, to observe what it displays.
```
watch -t -n0.1 xclip -o -selection "clipboard" -t TARGETS
```
2. Open some other application to copy a piece of content in. I just use a simple text-editor (xed). Select a piece of text, press Ctrl+C and hold it for a few seconds (the holding is just to generate many keyboard events, which provokes the problem much more consistently)
3. Observe the content of the terminal / xclip-watch, esp. after letting Ctrl+C go again after some seconds

Without FreeRDP running (or with `-clipboard`), the content shown by `xclip` will never change for me after the first copy (across all the copy-events). What's shown depends on where we copy something from, for xed it usually looks like this for me:
```
TIMESTAMP
TARGETS
MULTIPLE
SAVE_TARGETS
GTK_TEXT_BUFFER_CONTENTS
application/x-gtk-text-buffer-rich-text
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/plain;charset=utf-8
text/plain
```

When running FreeRDP with clipboard, the shown content for me usually ends up at one of the following, when provoking the problem with many copy-events as explained above:
```
TIMESTAMP
TARGETS
UTF8_STRING
STRING
image/bmp
text/uri-list
x-special/gnome-copied-files
x-special/mate-copied-files
text/html
```
or
```
TIMESTAMP
TARGETS
UTF8_STRING
STRING
```

If the clipboard is in this state, its content seems broken; it is not possible to extract the real (copied) content anymore from it. An attempt to read the actual String-content via xclip leads to something like this:
```
$ xclip -o -selection "clipboard" -t STRING
Error: target STRING not available
```

So it seems that FreeRDP, in the process of capturing the copied content to also enable it for the RDP session, can also somehow break the clipboard content, probably caused by some race-condition. I can find some of the mime-types that are included in the "broken" xclip-output above (like `image/bmp`, `text/uri-list`, `x-special/gnome-copied-files`, `x-special/mate-copied-files`) also in the sources (`client/X11/xf_cliprdr.c`), though I don't understand the code well enough to be able to pinpoint this further.

**Expected behavior**
Copy/paste operations should not break the clipboard content.

**Additional context**
The log-output sometimes also shows following logs, which sounds like in https://github.com/FreeRDP/FreeRDP/issues/5997. Not sure if there is some relation to that issue here.
```
[00:00:32:036] [2238136:2238232] [INFO][com.freerdp.client.x11] - skipping, empty data detected!!!
[00:00:33:023] [2238136:2238232] [INFO][com.freerdp.client.x11] - skipping, empty data detected!!!
[00:00:33:308] [2238136:2238232] [INFO][com.freerdp.client.x11] - skipping, empty data detected!!!
[00:00:34:771] [2238136:2238232] [INFO][com.freerdp.client.x11] - skipping, empty data detected!!!
```

**Comment by akallabeth** [comment]
@tromech the behaviour you describe sounds a bit strange.
Some parts I can recreate, like if you hold `<ctrl>+c` in the remote session then windows sends a new format announcement every ~30ms.
While that does not break anything here it might be an issue if you are on a laggy/slow/lossy line (the data can not be transferred when required)

As for the formats, the TARGETS you describe are what they are supposed to be (text/image/url (files))

So, could you run with `/log-filters:com.freerdp.channels.cliprdr.client:trace` maybe that can show you something why there is no data transferred?

(as for local applications, I could not observe any issue when just copying between local applications, `xfreerdp` only announces the formats to the remote, but only transfers data if `<ctrl>+v` is pressed in the session)

**Comment by tromech** [comment]
@akallabeth - thanks for the notes, also helps me to understand the way this works internally.

The system I connect to is running Windows 10 Pro (20H2)

You also brought me to something else I didn't think about yet so far though, which could be part of the problem - or at least, may be inclined to make the problem more likely to appear: On the Win10 Server-side, there is also a VM running (VirtualBox with Ubuntu + Guest additions - so there's also exchange between the host/guest clipboards happening on that remote machine).

And in fact, when I stopped that VM on the remote for some quick-tests, I'm having a much harder time reproducing my problem. Note however that the issue still occurs in that case, but seems to happen *much* less often.

So I'm assuming the added delay here makes it more apparent, right? I.e. when I copy something locally, sync local clipboard -> Win10 clipboard, with an additional sync of the Win10 clipboard -> Ubuntu VM running in it required behind.

Unfortunately, I can't do without that VM, so still wondering if there's something to make this more "stable"...

**Comment by akallabeth** [comment]
ok, that is an interesting data point (and might explain why nobody complained before/we did not observe it other than `sometimes the clipboard sync fails, copy again`)

what could make this more stable (client wise) is adding some logic:
1. Avoid duplicate announcements (unless data has been requested)
1. Add a transmission delay, so ignore intermediate changes (e.g. `<500ms` since last change)

But there is also the remote end that should not do something nasty when things go south, but at least these options we have client wise.

**Comment by madorian** [comment]
After I quit xfreerdp, I have to kill xrdp-sesman to make the clipboard work. If I just start up xfreerdp, it's still borken. 
```
$pgrep -l rdp
1843 xrdp-sesman
$sudo pkill rdp
```

**Comment by PlinChen** [comment]
+1

**Comment by agnardo** [comment]
+1

Using Gentoo and FreeRDP 2.10.0-r3 

If I close the RDP session or run it without clipboard support, problems go away.

**Comment by bernd-wechner** [comment]
> Using Gentoo and FreeRDP 2.10.0-r3
> 
> If I close the RDP session or run it without clipboard support, problems go away.

On Mint (Cinnamon) and my clipboard started playing up. Pinned it to xfreerdp and ditto, was running it with /clipboard, took that off and all came good. This was a recent development though, I've been using it for years with no problem (I run it from a one line script so it logs in for me and all on a sing 'rdp' command).

I'm using:

```
$ xfreerdp --version
This is FreeRDP version 2.6.1 (2.6.1)
```

**Comment by jobs-git** [comment]
still a problem even on freerdp 3.0.0 beta4

**Comment by tobiasoed** [comment]
I have a fedora 40 system with mate running a single win 10 vm to use outlook (I'm lucky enough they let me run a linux !). I often do copy paste of screenshots (with shutter) from firefox (running on the fedora) to outlook via freerdp 3.6.2. Sometimes copy/paste stop working but it also breaks keyboard grab. If I copy an image and paste it into outlook I can continue type in the windows vm but if I click on another window in linux the keystrokes keep going to xfreerdp. If y ctrl-right the keyboard will leave xfreerdp but I cannot get it back there. I have to kill the xfreerdp session. It seeams to be related to the size of the image.
It use to work flawlessly until somtime in the spring (on fedora 39) !

**Comment by ehoffman2** [comment]
I have similar issue as OP posted.
Here, I can easily do it with many applications, even with simple text editor such as Kate.
In my case, the issue is when I copy data locally, and try to paste it either locally or remotely. 1/3 to 1/2 of the time, if I try to paste, nothing gets pasted.

If I paste remotely to some editor, the editor tells me "unable to get clipboard data".

If I paste locally (that is, I copy locally, paste locally), the local application which I try to paste to (can even be the same application I copied from) just freeze for 5 seconds.

That last one is *very* annoying, as I cannot really work locally while a RDP session is in the background (i.e. even if there's an RDP session opened in the background, that I don't even switch to, I have issue with local copy from/copy to).

One thing I noticed, this even occurs if I right-click and select context menu 'copy' and context menu 'paste', without touching a single key (just using mouse right-click).  So it's probably not a keyboard issue, but really a clipboard handling issue.

This is version 2.6.1

**Comment by akallabeth** [comment]
@ehoffman2 

> I have a fedora 40 system with mate running a single win 10 vm to use outlook (I'm lucky enough they let me run a linux !). I often do copy paste of screenshots (with shutter) from firefox (running on the fedora) to outlook via freerdp 3.6.2. Sometimes copy/paste stop working but it also breaks keyboard grab. If I copy an image and paste it into outlook I can continue type in the windows vm but if I click on another window in linux the keystrokes keep going to xfreerdp. If y ctrl-right the keyboard will leave xfreerdp but I cannot get it back there. I have to kill the xfreerdp session. It seeams to be related to the size of the image. It use to work flawlessly until somtime in the spring (on fedora 39) !

hmm, we did not change much regarding `xfreerdp` (and fedora keeps quite close to upstream)
maybe something related to your environment (or outlook)? clipboard managers (on both ends) might be problematic as every paste (that also includes clipboard manager sync) requires to transfer the data to/form the host

**Comment by akallabeth** [comment]
@ehoffman2 well, in your case I can only tell: update. even debian stable has 2.10

**Comment by ehoffman2** [comment]
I know, it may not be the latest, it's the one that comes packaged with Ubuntu 22.04.  I may try to update to 24.04 sometime.

However, one thing I noted is that when the pasting gives issue:
- It doesn't matter if I try to paste again (without copying another snippet), the application still freeze for 5~10 seconds.
- If I close RDP session, and I then paste (without doing a copy), then the text paste just fine (the text I originally copied).

Eric
