### ISSUE TITLE
Compilation on Raspberry Pi 4 gives ==28616==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

### ISSUE THREAD

**Issue by marlemion** [FreeRDP/FreeRDP#7009]
I followed the compilation instructions using dpkg-buildpackage on the compilation website.

The installed package resides in /opt/freerdp-nightly/

Executing xfreerdp in this directory yields:

==28616==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.

 ldd xfreerdp 
	linux-vdso.so.1 (0xbeb0c000)
	/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so => /usr/lib/arm-linux-gnueabihf/libarmmem-v7l.so (0xb6ed2000)
	libasan.so.5 => /usr/lib/arm-linux-gnueabihf/libasan.so.5 (0xb690d000)
	libX11.so.6 => /usr/lib/arm-linux-gnueabihf/libX11.so.6 (0xb67eb000)
	libXinerama.so.1 => /usr/lib/arm-linux-gnueabihf/libXinerama.so.1 (0xb67d8000)
	libXext.so.6 => /usr/lib/arm-linux-gnueabihf/libXext.so.6 (0xb67b9000)
	libXcursor.so.1 => /usr/lib/arm-linux-gnueabihf/libXcursor.so.1 (0xb67a0000)
	libXv.so.1 => /usr/lib/arm-linux-gnueabihf/libXv.so.1 (0xb678c000)
	libXi.so.6 => /usr/lib/arm-linux-gnueabihf/libXi.so.6 (0xb676e000)
	libXrender.so.1 => /usr/lib/arm-linux-gnueabihf/libXrender.so.1 (0xb6755000)
	libXrandr.so.2 => /usr/lib/arm-linux-gnueabihf/libXrandr.so.2 (0xb673c000)
	libXfixes.so.3 => /usr/lib/arm-linux-gnueabihf/libXfixes.so.3 (0xb6727000)
	libfreerdp-client3.so.3 => /opt/freerdp-nightly/bin/./../lib/libfreerdp-client3.so.3 (0xb6510000)
	libfreerdp3.so.3 => /opt/freerdp-nightly/bin/./../lib/libfreerdp3.so.3 (0xb60ed000)
	libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0xb606b000)
	librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0xb6054000)
	libwinpr3.so.3 => /opt/freerdp-nightly/bin/./../lib/libwinpr3.so.3 (0xb5de1000)
	libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0xb5db4000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xb5c66000)
	/lib/ld-linux-armhf.so.3 (0xb6ee7000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xb5c53000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xb5c29000)
	libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0xb5ae2000)
	libxcb.so.1 => /usr/lib/arm-linux-gnueabihf/libxcb.so.1 (0xb5ab3000)
	libusb-1.0.so.0 => /lib/arm-linux-gnueabihf/libusb-1.0.so.0 (0xb5a8e000)
	libcups.so.2 => /usr/lib/arm-linux-gnueabihf/libcups.so.2 (0xb5a0c000)
	libasound.so.2 => /usr/lib/arm-linux-gnueabihf/libasound.so.2 (0xb592b000)
	libpulse.so.0 => /usr/lib/arm-linux-gnueabihf/libpulse.so.0 (0xb58d5000)
	libcairo.so.2 => /usr/lib/arm-linux-gnueabihf/libcairo.so.2 (0xb57dc000)
	libssl.so.1.1 => /usr/lib/arm-linux-gnueabihf/libssl.so.1.1 (0xb575d000)
	libcrypto.so.1.1 => /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1 (0xb5543000)
	libxkbfile.so.1 => /usr/lib/arm-linux-gnueabihf/libxkbfile.so.1 (0xb5511000)
	libavcodec.so.58 => /usr/lib/arm-linux-gnueabihf/neon/vfp/libavcodec.so.58 (0xb4193000)
	libavutil.so.56 => /usr/lib/arm-linux-gnueabihf/neon/vfp/libavutil.so.56 (0xb410a000)
	libswresample.so.3 => /usr/lib/arm-linux-gnueabihf/neon/vfp/libswresample.so.3 (0xb40e4000)
	libsystemd.so.0 => /lib/arm-linux-gnueabihf/libsystemd.so.0 (0xb4047000)
	libXau.so.6 => /usr/lib/arm-linux-gnueabihf/libXau.so.6 (0xb4034000)
	libXdmcp.so.6 => /usr/lib/arm-linux-gnueabihf/libXdmcp.so.6 (0xb401f000)
	libudev.so.1 => /lib/arm-linux-gnueabihf/libudev.so.1 (0xb3fef000)
	libgssapi_krb5.so.2 => /usr/lib/arm-linux-gnueabihf/libgssapi_krb5.so.2 (0xb3fa5000)
	libgnutls.so.30 => /usr/lib/arm-linux-gnueabihf/libgnutls.so.30 (0xb3e02000)
	libavahi-common.so.3 => /usr/lib/arm-linux-gnueabihf/libavahi-common.so.3 (0xb3de7000)
	libavahi-client.so.3 => /usr/lib/arm-linux-gnueabihf/libavahi-client.so.3 (0xb3dc8000)
	libz.so.1 => /lib/arm-linux-gnueabihf/libz.so.1 (0xb3d9d000)
	libpulsecommon-12.2.so => /usr/lib/arm-linux-gnueabihf/pulseaudio/libpulsecommon-12.2.so (0xb3d1c000)
	libdbus-1.so.3 => /lib/arm-linux-gnueabihf/libdbus-1.so.3 (0xb3ccb000)
	libcap.so.2 => /lib/arm-linux-gnueabihf/libcap.so.2 (0xb3cb6000)
	libpixman-1.so.0 => /usr/lib/arm-linux-gnueabihf/libpixman-1.so.0 (0xb3bdb000)
	libfontconfig.so.1 => /usr/lib/arm-linux-gnueabihf/libfontconfig.so.1 (0xb3b93000)
	libfreetype.so.6 => /usr/lib/arm-linux-gnueabihf/libfreetype.so.6 (0xb3af0000)
	libpng16.so.16 => /usr/lib/arm-linux-gnueabihf/libpng16.so.16 (0xb3ab4000)
	libxcb-shm.so.0 => /usr/lib/arm-linux-gnueabihf/libxcb-shm.so.0 (0xb3aa1000)
	libxcb-render.so.0 => /usr/lib/arm-linux-gnueabihf/libxcb-render.so.0 (0xb3a86000)
	libvpx.so.5 => /usr/lib/arm-linux-gnueabihf/libvpx.so.5 (0xb3983000)
	libwebpmux.so.3 => /usr/lib/arm-linux-gnueabihf/libwebpmux.so.3 (0xb396b000)
	libwebp.so.6 => /usr/lib/arm-linux-gnueabihf/libwebp.so.6 (0xb3907000)
	liblzma.so.5 => /lib/arm-linux-gnueabihf/liblzma.so.5 (0xb38d6000)
	libmmal_core.so => /opt/vc/lib/libmmal_core.so (0xb38b8000)
	libmmal_util.so => /opt/vc/lib/libmmal_util.so (0xb3898000)
	libmmal_vc_client.so => /opt/vc/lib/libmmal_vc_client.so (0xb387d000)
	libbcm_host.so => /opt/vc/lib/libbcm_host.so (0xb3856000)
	libvcsm.so => /opt/vc/lib/libvcsm.so (0xb383c000)
	librsvg-2.so.2 => /usr/lib/arm-linux-gnueabihf/librsvg-2.so.2 (0xb342e000)
	libgobject-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgobject-2.0.so.0 (0xb33d1000)
	libglib-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libglib-2.0.so.0 (0xb32c1000)
	libzvbi.so.0 => /usr/lib/arm-linux-gnueabihf/libzvbi.so.0 (0xb323e000)
	libsnappy.so.1 => /usr/lib/arm-linux-gnueabihf/libsnappy.so.1 (0xb3227000)
	libaom.so.0 => /usr/lib/arm-linux-gnueabihf/libaom.so.0 (0xb2f2b000)
	libcodec2.so.0.8.1 => /usr/lib/arm-linux-gnueabihf/libcodec2.so.0.8.1 (0xb2ec2000)
	libgsm.so.1 => /usr/lib/arm-linux-gnueabihf/libgsm.so.1 (0xb2ea7000)
	libmp3lame.so.0 => /usr/lib/arm-linux-gnueabihf/libmp3lame.so.0 (0xb2e2b000)
	libopenjp2.so.7 => /usr/lib/arm-linux-gnueabihf/libopenjp2.so.7 (0xb2dcf000)
	libopus.so.0 => /usr/lib/arm-linux-gnueabihf/libopus.so.0 (0xb2d70000)
	libshine.so.3 => /usr/lib/arm-linux-gnueabihf/libshine.so.3 (0xb2d56000)
	libspeex.so.1 => /usr/lib/arm-linux-gnueabihf/libspeex.so.1 (0xb2d2f000)
	libtheoraenc.so.1 => /usr/lib/arm-linux-gnueabihf/libtheoraenc.so.1 (0xb2cee000)
	libtheoradec.so.1 => /usr/lib/arm-linux-gnueabihf/libtheoradec.so.1 (0xb2cc6000)
	libtwolame.so.0 => /usr/lib/arm-linux-gnueabihf/libtwolame.so.0 (0xb2c96000)
	libvorbis.so.0 => /usr/lib/arm-linux-gnueabihf/libvorbis.so.0 (0xb2c5f000)
	libvorbisenc.so.2 => /usr/lib/arm-linux-gnueabihf/libvorbisenc.so.2 (0xb2bcd000)
	libwavpack.so.1 => /usr/lib/arm-linux-gnueabihf/libwavpack.so.1 (0xb2b99000)
	libx264.so.155 => /usr/lib/arm-linux-gnueabihf/neon/vfp/libx264.so.155 (0xb294d000)
	libx265.so.165 => /usr/lib/arm-linux-gnueabihf/libx265.so.165 (0xb2693000)
	libxvidcore.so.4 => /usr/lib/arm-linux-gnueabihf/libxvidcore.so.4 (0xb25a3000)
	libva.so.2 => /usr/lib/arm-linux-gnueabihf/libva.so.2 (0xb2572000)
	libva-drm.so.2 => /usr/lib/arm-linux-gnueabihf/libva-drm.so.2 (0xb255f000)
	libva-x11.so.2 => /usr/lib/arm-linux-gnueabihf/libva-x11.so.2 (0xb254a000)
	libvdpau.so.1 => /usr/lib/arm-linux-gnueabihf/libvdpau.so.1 (0xb2536000)
	libdrm.so.2 => /usr/lib/arm-linux-gnueabihf/libdrm.so.2 (0xb2517000)
	libsoxr.so.0 => /usr/lib/arm-linux-gnueabihf/libsoxr.so.0 (0xb24b5000)
	liblz4.so.1 => /usr/lib/arm-linux-gnueabihf/liblz4.so.1 (0xb2489000)
	libgcrypt.so.20 => /lib/arm-linux-gnueabihf/libgcrypt.so.20 (0xb23af000)
	libbsd.so.0 => /usr/lib/arm-linux-gnueabihf/libbsd.so.0 (0xb2387000)
	libkrb5.so.3 => /usr/lib/arm-linux-gnueabihf/libkrb5.so.3 (0xb22cc000)
	libk5crypto.so.3 => /usr/lib/arm-linux-gnueabihf/libk5crypto.so.3 (0xb228a000)
	libcom_err.so.2 => /lib/arm-linux-gnueabihf/libcom_err.so.2 (0xb2277000)
	libkrb5support.so.0 => /usr/lib/arm-linux-gnueabihf/libkrb5support.so.0 (0xb225d000)
	libkeyutils.so.1 => /lib/arm-linux-gnueabihf/libkeyutils.so.1 (0xb2249000)
	libresolv.so.2 => /lib/arm-linux-gnueabihf/libresolv.so.2 (0xb2225000)
	libp11-kit.so.0 => /usr/lib/arm-linux-gnueabihf/libp11-kit.so.0 (0xb2120000)
	libidn2.so.0 => /usr/lib/arm-linux-gnueabihf/libidn2.so.0 (0xb20f4000)
	libunistring.so.2 => /usr/lib/arm-linux-gnueabihf/libunistring.so.2 (0xb1f78000)
	libtasn1.so.6 => /usr/lib/arm-linux-gnueabihf/libtasn1.so.6 (0xb1f58000)
	libnettle.so.6 => /usr/lib/arm-linux-gnueabihf/libnettle.so.6 (0xb1f14000)
	libhogweed.so.4 => /usr/lib/arm-linux-gnueabihf/libhogweed.so.4 (0xb1ed5000)
	libgmp.so.10 => /usr/lib/arm-linux-gnueabihf/libgmp.so.10 (0xb1e5a000)
	libX11-xcb.so.1 => /usr/lib/arm-linux-gnueabihf/libX11-xcb.so.1 (0xb1e48000)
	libICE.so.6 => /usr/lib/arm-linux-gnueabihf/libICE.so.6 (0xb1e22000)
	libSM.so.6 => /usr/lib/arm-linux-gnueabihf/libSM.so.6 (0xb1e0b000)
	libXtst.so.6 => /usr/lib/arm-linux-gnueabihf/libXtst.so.6 (0xb1df6000)
	libwrap.so.0 => /lib/arm-linux-gnueabihf/libwrap.so.0 (0xb1dde000)
	libsndfile.so.1 => /usr/lib/arm-linux-gnueabihf/libsndfile.so.1 (0xb1d62000)
	libasyncns.so.0 => /usr/lib/arm-linux-gnueabihf/libasyncns.so.0 (0xb1d4d000)
	libexpat.so.1 => /lib/arm-linux-gnueabihf/libexpat.so.1 (0xb1d0c000)
	libuuid.so.1 => /lib/arm-linux-gnueabihf/libuuid.so.1 (0xb1cf5000)
	libvcos.so => /opt/vc/lib/libvcos.so (0xb1cda000)
	libvchiq_arm.so => /opt/vc/lib/libvchiq_arm.so (0xb1cc4000)
	libgdk_pixbuf-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgdk_pixbuf-2.0.so.0 (0xb1c92000)
	libgio-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgio-2.0.so.0 (0xb1b16000)
	libpangocairo-1.0.so.0 => /usr/lib/arm-linux-gnueabihf/libpangocairo-1.0.so.0 (0xb1afb000)
	libpangoft2-1.0.so.0 => /usr/lib/arm-linux-gnueabihf/libpangoft2-1.0.so.0 (0xb1ad9000)
	libpango-1.0.so.0 => /usr/lib/arm-linux-gnueabihf/libpango-1.0.so.0 (0xb1a8c000)
	libcroco-0.6.so.3 => /usr/lib/arm-linux-gnueabihf/libcroco-0.6.so.3 (0xb1a4a000)
	libxml2.so.2 => /usr/lib/arm-linux-gnueabihf/libxml2.so.2 (0xb18cd000)
	libffi.so.6 => /usr/lib/arm-linux-gnueabihf/libffi.so.6 (0xb18b5000)
	libpcre.so.3 => /lib/arm-linux-gnueabihf/libpcre.so.3 (0xb183c000)
	libogg.so.0 => /usr/lib/arm-linux-gnueabihf/libogg.so.0 (0xb1827000)
	libgomp.so.1 => /usr/lib/arm-linux-gnueabihf/libgomp.so.1 (0xb17ef000)
	libgpg-error.so.0 => /lib/arm-linux-gnueabihf/libgpg-error.so.0 (0xb17c5000)
	libnsl.so.1 => /lib/arm-linux-gnueabihf/libnsl.so.1 (0xb17a1000)
	libFLAC.so.8 => /usr/lib/arm-linux-gnueabihf/libFLAC.so.8 (0xb1741000)
	libgmodule-2.0.so.0 => /usr/lib/arm-linux-gnueabihf/libgmodule-2.0.so.0 (0xb172d000)
	libmount.so.1 => /lib/arm-linux-gnueabihf/libmount.so.1 (0xb16ca000)
	libselinux.so.1 => /lib/arm-linux-gnueabihf/libselinux.so.1 (0xb1698000)
	libharfbuzz.so.0 => /usr/lib/arm-linux-gnueabihf/libharfbuzz.so.0 (0xb159a000)
	libthai.so.0 => /usr/lib/arm-linux-gnueabihf/libthai.so.0 (0xb1582000)
	libfribidi.so.0 => /usr/lib/arm-linux-gnueabihf/libfribidi.so.0 (0xb1558000)
	libicui18n.so.63 => /usr/lib/arm-linux-gnueabihf/libicui18n.so.63 (0xb130a000)
	libicuuc.so.63 => /usr/lib/arm-linux-gnueabihf/libicuuc.so.63 (0xb1184000)
	libicudata.so.63 => /usr/lib/arm-linux-gnueabihf/libicudata.so.63 (0xaf786000)
	libblkid.so.1 => /lib/arm-linux-gnueabihf/libblkid.so.1 (0xaf72e000)
	libgraphite2.so.3 => /usr/lib/arm-linux-gnueabihf/libgraphite2.so.3 (0xaf6fb000)
	libdatrie.so.1 => /usr/lib/arm-linux-gnueabihf/libdatrie.so.1 (0xaf6e5000)

LD_PRELOAD is empty

What is the problem?

**Comment by akallabeth** [comment]
Nightly builds are compiled with  `-DWITH_SANITIZE_ADDRESS=ON` to enable (advanced) memory sanitation checks at runtime and fail noisily if something is wrong.
So, possible reasons are:
1. `libasan` is not installed (the nightly is lax on dependency checks due to different distros naming them differently). Installing it might resolve the issue.
2. start with `LD_PRELOAD=/usr/lib/somepath/libasan.so /opt/freerdp-nightly/bin/xfreerdp` 
3. Recompile the nightly, First deacvivate asan in `packaging/deb/freerdp-nightly/rules` by setting ` SANATIZE_ADDRESS = -DWITH_SANITIZE_ADDRESS=OFF` then `dpkg-buildpackage`
