### ISSUE TITLE
FreeRDP with Virtual Desktop .rdpw files

### ISSUE THREAD

**Issue by matthew-jones-uk** [FreeRDP/FreeRDP#7011]
Is it possible to use FreeRDP to connect to [Windows Virtual Desktop machines](https://docs.microsoft.com/en-us/azure/virtual-desktop/overview) via the `.rdpw` files provided by the online interface? If I change the file to a `.rdp` file then I am prompted for a username, password, and domain name but it errors with `ERRCONNECT_SECURITY_NEGO_CONNECT_FAILED`. Is what I'm trying to do at all possible?

**Comment by Salohajj** [comment]
https://login.microsoftonline.com/{tenant}/adminconsent?client_id=fa4345a4-a730-4230-84a8-7d9651b86739&redirect_uri=https%3A%2F%2Frdweb.wvd.microsoft.com%2FRDWeb%2FConsentCallback

**Comment by magicse** [comment]
+

**Comment by akallabeth** [comment]
@hardening and @fifthdegree are working on getting kerberos authentication fully implemented, but until that is complete you can not use `NLA` with those.

**Comment by matejc** [comment]
@akallabeth Is there any ETA on this? I understand that this is an OSS project, so are there any open tickets so that someone could help with this issue?

**Comment by akallabeth** [comment]
@matejc kerberos is now mosly upstream, so you might give it a try.
the rdp file handling for kerberos proxy is currently missing, so you need a local kerberos realm configuration for it to work.
as for `rdpw` , I´ll create a patch (it is just the extension that is missing to detect it as `rdp` file)

**Comment by akallabeth** [comment]
@matejc ok, https://github.com/FreeRDP/FreeRDP/pull/8549 will fix the issue with the file not being recognized.

**Comment by matejc** [comment]
> @matejc kerberos is now mosly upstream, so you might give it a try. the rdp file handling for kerberos proxy is currently missing, so you need a local kerberos realm configuration for it to work. as for `rdpw` , I´ll create a patch (it is just the extension that is missing to detect it as `rdp` file)

Is there any documentation on this? I am struggling with local kerberos realm config.

**Comment by akallabeth** [comment]
@matejc no, that was done just recently and we are in progress of putting together some stuff. 
For client it basically is:
1. build with `-DWITH_SPNEGO=ON -DWITH_KRB5=ON`
2. configure your realm in `/etc/krb5.conf`
3. connect with `/v:<domainname> /u:<user> /d:<domain> /p:<pwd>`  and hope for the best. (you should have a valid kerberos ticket after the connection)

we are working on getting the configuration part eliminated so it 'just works' but not there yet.

**Comment by matejc** [comment]
I know this is not in the scope of this ticket, but does anyone has an idea how to configure krb5 for hosted WVD on Azure. I presume I only need admin_server and kdc, beside the domain.

**Comment by fifthdegree** [comment]
@matejc Assuming you're using a kdc proxy, you should add something like this:
```
DOMAIN.TLD = {
    kdc = https://host.domain.tld/KdcProxy
}
```
I am curious though, what happens if you pass the url to the `/kerberos:kdc-url:` argument?

**Comment by matejc** [comment]
@fifthdegree I have KDC (server with 88 port found by doing `nslookup -type=srv _kerberos._tcp.AD.DOMAIN.TLD` from inside the network), but its not available to the internet, I suppose I need to use the gateway option of FreeRDP also since the WVD VM is not available to outside world (I can get the gateway from cat-ing the rdpw file). But first, is there a way to find out the KdcProxy url somehow on my own, since I am not an admin to the AD?

**Comment by akallabeth** [comment]
@matejc there is a `KDC` proxy configured with some `RDP` gateways, so you might need to check the URL that that is using. (may be configured by default, I just have not looked to deep into this yet)

**Comment by fifthdegree** [comment]
@matejc I would assume the kdc proxy is on the same machine as the gateway

**Comment by matejc** [comment]
I tried instructions for Remote Desktop Client on Windows, and I needed to use Workspace and include the workspace url: https://client.wvd.microsoft.com , so I guess I need to continue here: https://github.com/FreeRDP/FreeRDP/issues/8515

**Comment by akallabeth** [comment]
we had contributions by @fifthdegree adding one authentication mode for this, might work with https://github.com/FreeRDP/FreeRDP/pull/8768 (already merged)

**Comment by matejc** [comment]
Is there any usage example?

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/FAQ
