### ISSUE TITLE
Disconnect from session when closing window

### ISSUE THREAD

**Issue by arielnmz** [FreeRDP/FreeRDP#7017]
**Is your feature request related to a problem? Please describe.**
Clicking on the close button of the window decoration causes input to freeze i.e. you can't type nor click in the remote desktop and clicking it a few more times will freeze the video or make the screen go black.

**Describe the solution you'd like**
The close button of the decoration:

![image](https://user-images.githubusercontent.com/24735547/118607088-0a79ba00-b76d-11eb-8897-f668d14f4b3f.png)

should do the same thing as the `x` button in the floatbar.

**Describe alternatives you've considered**
The floatbar works fine, but it sometimes gets in the way, specially when running applications in fullscreen mode in the remote desktop. You can also just `^C` in the terminal window or even get the pid of the window and `kill`ing it, but those are not very practical when running several desktops or the session was simply not started from a cli.

Also logging out from the desktop is not always the best solution, specially when I just need to _leave_ a window but plan to come back later to resume work.

**Example:**

https://user-images.githubusercontent.com/24735547/118609074-3f870c00-b76f-11eb-81d0-1488a5dde77e.mp4

**Environment info:**

**Command used:**

```
xfreerdp \
    /microphone:sys:pulse,format:1,quality:high \
    /sound:sys:pulse,format:1,quality:high \
    /rfx \
    +gfx-thin-client \
    +async-update \
    +async-input \
    +clipboard \
    /dynamic-resolution \
    +multitransport \
    /network:lan \
    -compression \
    /u:*** \
    /v:*** \
    /p:*** \
    /floatbar:default:visible,show:always
```

**Remote system info:**

Windows 10 Pro 20H2 Build 19042.985

**`freerdp --version`:**

This is FreeRDP version 2.3.2 (n/a)
Installed from the system repo with `dnf install xfreerdp`

**Running system:**

Fedora release 34 (Thirty Four)
Linux 5.11.19-300.fc34.x86_64

**Comment by akallabeth** [comment]
@arielnmz could you clarify your issue a bit?
I don´t exactly understand what you are working with (I assume something with fullscreen since you´re talking about floatbar?) and what environment you´re using.
The `Close` button of `xfreerdp` is working fine with my local installations, so some more information might help

**Comment by arielnmz** [comment]
I'm talking about the close button in the window's decorations. This one: 

![image](https://user-images.githubusercontent.com/24735547/118607088-0a79ba00-b76d-11eb-8897-f668d14f4b3f.png)

Nothing happens when I click it, and I expect it to close the window and disconnect the session (updated the OP with an example vid)

**Comment by akallabeth** [comment]
@arielnmz ok. mine does.
so could you please add some more information?

**Comment by akallabeth** [comment]
If you´re unsure what I mean with more information, see
https://github.com/FreeRDP/FreeRDP/wiki/BugReporting

**Comment by arielnmz** [comment]
Shoot, sorry I missed that

**Comment by akallabeth** [comment]
@arielnmz ok, found it. `+async-input` is the culprit.

**Comment by arielnmz** [comment]
Thanks! That was indeed the problem. Sorry I don't know where to look for docs on each option available
