### ISSUE TITLE
usb request failed with 0000054f - usb webcam problem

### ISSUE THREAD

**Issue by afroben0306** [FreeRDP/FreeRDP#7025]
Dear all,

We are trying to set up the USB webcam to an XfreeRDP on Linux with XFCE terminal emulator 0.8.9.1.

The webcam test on chromium browser works perfectly, but the problem is when we try to connect to it via usb with the sudo xfreerdp.

The error message displayed is "usb request failed with 0000054f"

The device is recognized and set up correctly.

Also, we alredy adjusted the gpo to allow incoming video:​https://stackoverflow.com/questions/33719489/how-to-enable-usb-redirection-in-windows-10/46628854

Any ideas on how to resolve this problem?

os: xubunto 20.04 freerdp version 2.2.0 string: ~$ sudo xfreerdp /v:20.52.176.2 /usb:id,dev:046d:0836 /sound /microphone

**Comment by akallabeth** [comment]
@afroben0306 
1. why are you running with `sudo`?
2. where does `usb request failed with 0000054f` occur?
3. Some logs please?

**Comment by afroben0306** [comment]
![IMG_20210520_113527_resized_20210520_113620740](https://user-images.githubusercontent.com/84500577/118957314-b3d4d180-b960-11eb-8fd3-709dda57b77c.jpg)

1. I shouldn't use sudo?
2-3. please see attached screenshot

**Comment by akallabeth** [comment]
1. No, never for a normal application
2. Ok, so looks like the device is either not compatible / has issues with libusb or you could try with more recent freerdp versions, maybe you´re running into a bug.

**Comment by akallabeth** [comment]
@afroben0306 there was #7109 which fixed a bug in usb channel.
Closing this, reopen/ping me if you still have issues.
