### ISSUE TITLE
Freerdp unable to connect to multiple remote monitors

### ISSUE THREAD

**Issue by sachinh1980** [FreeRDP/FreeRDP#7031]
Hello Community,

xfreerdp is being installed on SuSE 15SP2 "freerdp-2.0.0~rc4-13.2.x86_64". Works fine with remote desktop having Windows 10. 
but one of the remote windows system has 5 Monitors. And when we start remote sessions, it shows only one monitor display. I do not know how do I switch between multiple monitor display or if it is at all possible?
The command which we are using is as follows,

>/usr/bin/xfreerdp  /v:X.7.X.1 /u:admin /gt:rpc +gfx-small-cache /bpp:8 /multimon:force +smart-sizing

Kindly let us know if this is even possible. If yes, which parameters to use?
If you require additional information, kindly let us know.

Thanx.

**Comment by akallabeth** [comment]
what do you mean with `but one of the remote windows system has 5 Monitors.`?
`/multimon` just works with local monitors by announcing what you locally have and the remote will create a session accordingly.

`RDP` is not mirroring your server session, it is an entirely independent `output` (e.g. your server can have no monitor at all and you can still connect with multiple monitors)

**Comment by sachinh1980** [comment]
Thanks for the reply.
1. /multimon : I interepreted it incorrectly. I thought it is for the case if one has to connect to remote multiple monitors. Because that is what I wish to. The remote system in my case has multiple monitor setup. 5 Monitors are showing different output on remote setup. Please see the link below to know my remote desktop setup. 
![image](https://user-images.githubusercontent.com/50734534/119126234-0f6f8f80-ba33-11eb-8e45-a9fa7e728951.png)

Is it possible to get access to remote access to this remote system? Everytime I start a session I do not see any of the numbers displayed on these multiple monitors. Like you explained, it probably starts a completely new session.  :(   If it is not at all so possible, then how do I achieve this using RDP protocol? I am sure there are many softwares available on Internet but the problem is we are not allowed to install anything on the remote Windows System other than default windows softwares.  Hence we decided to use RDP.  

Kindly help us by giving directions.
Thanx again.

**Comment by akallabeth** [comment]
you might check how to use `rdp shadow`, but that is a server side feature. (you just connect with any rdp client to such a configured server)
did not do that though.

**Comment by sachinh1980** [comment]
Thanks for the explanation and help.
