### ISSUE TITLE
build FreeRdp Android faild

### ISSUE THREAD

**Issue by ligangcc** [FreeRDP/FreeRDP#7058]
I try to build FreeRdp Android in Ubuntu  according to the WiKi: 
https://github.com/FreeRDP/FreeRDP/wiki/Compilation#android-specifics 

![image](https://user-images.githubusercontent.com/5357175/120091917-d4abdc80-c141-11eb-8afa-44f7f666399b.png)

the sdk and ndk  used are (sdk is latest verison):

./scripts/android-build-freerdp.sh \
  --ndk ${HOME}/Android/android-ndk-r18b \
  --sdk ${HOME}/Android/Sdk \
  --openh264-ndk ${HOME}/Android/android-ndk-r15c \
  --conf android-build-release.conf

but at last, it failed with:

FREERDP_VERSION=3.0.0-dev
-- Git Revision 96c6f94e9
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Finding required feature ZLIB for compression (data compression)
CMake Error at /home/ligang/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.7")
Call Stack (most recent call first):
  /home/ligang/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/ligang/Android/Sdk/cmake/3.10.2.4988404/share/cmake-3.10/Modules/FindZLIB.cmake:112 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  cmake/FindFeature.cmake:16 (find_package)
  CMakeLists.txt:837 (find_feature)

-- Configuring incomplete, errors occurred!
See also "/home/ligang/work/FreeRDP/build/freerdp-build/x86_64/CMakeFiles/CMakeOutput.log".
See also "/home/ligang/work/FreeRDP/build/freerdp-build/x86_64/CMakeFiles/CMakeError.log".

Can anyone help get through   the problem:  "Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.7")"

**Comment by akallabeth** [comment]
Please start with a clean build environment (e.g. run `git clean -xdf` or with a fresh `git clone`)

**Comment by akallabeth** [comment]
Ok, just tested on `debian bullseye` with a fresh checkout, SDK and NDK installed, no environment variables set (`ANDROID_*`)
working as expected.
Check your SDK, NDK are properly installed.

**Comment by ligangcc** [comment]
My test was on Ubuntu,  I will test on debian.

**Comment by akallabeth** [comment]
@ligangcc distro does not matter, a clean source directory does.

**Comment by ligangcc** [comment]
dear akallabeth,

      can you kind enough to tell me what is the version of SDK and NDK you used?

**Comment by akallabeth** [comment]
Freshly installed, ndk I've used 22.3.something (but tried all from 15.* in the last months)

Am 31. Mai 2021 15:26:10 UTC schrieb "gang.li" ***@***.***>:
