### ISSUE TITLE
Windows 10 Certificate Bug

### ISSUE THREAD

**Issue by orionnelson** [FreeRDP/FreeRDP#7059]
[13:30:00:629] [3048:3049] [ERROR][com.freerdp.core] - rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_CLOSE_STACK_ON_DRIVER_FAILURE [0x00010011]

BUG: Connection Works fine after first handshake but then requires reset of both certificates.

Windows Version: 20H2

Unreasonable Fix:

sudo rm ~/.config/freerdp/known_hosts2 && xfreerdp /u:orion /p:**** /v:192.168.2.54 /size:1920x1080

Power Off and On Windows 10 Computer to reset certificate.

Connection works as expected.

Kali-Linux: Kali-Rolling R: 2021.1

FreeRDP version 2.3.0 

Keeping this chain short and sweet if you require more logs just ask.

**Comment by akallabeth** [comment]
sorry, your fix and the error have nothing in common.
`ERRINFO_CLOSE_STACK_ON_DRIVER_FAILURE` is set by the server long `after` the connection is established (and the certificates checked)

**Comment by orionnelson** [comment]
/network:auto  was one of the first things I tried it does not fix the issue, Is there any other reasons that I could be getting this error.

**Comment by akallabeth** [comment]
no, there is no other reason.
what you see is an error message sent from the server `after` the ssl connection is established.
Certifcates are `only` relevant during the `ssl` connection phase (they establish a `trust` for the connection) and not used anywhere else. (the file just holds a list of known remote certificate hashes)

**Comment by akallabeth** [comment]
but one thing strikes me as odd, why do you need `sudo` to remove that file?

**Comment by akallabeth** [comment]
fyi: https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/a21a1bd9-2303-49c1-90ec-3932435c248c defines the error codes.
See `ERRINFO_CLOSE_STACK_ON_DRIVER_FAILURE` for some details
