### ISSUE TITLE
Keyboard fails on relay

### ISSUE THREAD

**Issue by kieppie** [FreeRDP/FreeRDP#709]
I've set up a (VM) host for dedicated remote purposes: Ubuntu 12.04.1 64-bit (XFCE as DM), installed (updated/current) Remmina & FreeRDP from PPA - 1.0.1-1ubuntu2.1freerdp1~1

I remote into this support-relay host through VNC or remote-X (X over SSH) & fire up RDP via Remmina or CLI, the mouse pointer works fine, but no keyboard events are passed through to the remote host.

This is only an issue with FreeRDP (& by extension Remmina), as other apps, service & protocols like rdesktop (via CLI), PAC Manager, TeamViewer, etc are all OK - keyboard, mouse & clipboard.

So in essence the problem is:
FreeRDP drops keyboard events when used as/via remote session relay.

**Comment by rhendric** [comment]
I also encountered this with a basically identical setup to @rkarlsba. I got it to work by recompiling FreeRDP after editing the freerdp_keyboard_init function in libfreerdp/locale/keyboard.c to use the Apple init function and not the xkb or evdev ones. Clumsy but effective.

It would be nice to make enabling/disabling the different keyboard initializers a command-line option rather than a compile flag—supporting the Apple codes doesn't actually seem to depend on any OS X libraries or headers or anything.

**Comment by bmiklautz** [comment]
@rhendric yep would make sense to have this as an run time option.
Marked as feature.

**Comment by rkarlsba** [comment]
@rhendric Do you have a patch? I'd love to test this and perhaps add a runtime option

**Comment by bmiklautz** [comment]
@rakovs  in FreeRDP-master/libfreerdp/locale/keyboard.c function freerdp_keyboard_init. freerdp_keyboard_init_apple is only compiled in on apple at the moment.

**Comment by rkarlsba** [comment]
Having keyboard support when ssh'ing from a mac into linux and then starting freerdp, isn't really a "feature", it's elementary. Please mark this as a bug, not a feature.

**Comment by bmiklautz** [comment]
@rkarlsba issues are bugs ;)

**Comment by rhendric** [comment]
@rkarlsba My ‘patch’ (obviously not a fix, just a kludge):

https://gist.github.com/rhendric/099adb75edeb016328e9

**Comment by dscho** [comment]
@rhendric please note that your patch is white-space corrupted: it replaces tabs by spaces.

Aside from that, my use case (VNCing into an Xvnc4 instance and calling FreeRDP inside there, then type something in one of the RDP session windows) seems to be fixed in `master` (my Ubuntu ships only version `1.0.2`, the version that works here is `1.2.1-dev (git aa2181d)`).

**Comment by ny0** [comment]
Is there a new rpm (1.2.1-dev) for Centos 6?  Have the same problem with freerdp-1.0.2-2.el6.x86_64 when the linux host is connected from VNC and trying to RDP to Windows 2008.

**Comment by grufocom** [comment]
I am having the same problem with the nightly build (ubuntu - version 2.0.0-dev ) from yesterday - getting the error message "unknown key with x keycode 0x5c" when pressing "\".

My thin client is an ubuntu 16.04 system with pekwm as window manager and I use freerdp to connect to a windows machine, x11vnc runs in the background to connect to my thin client (client support issues).

When I try the "\" directly at the thin client machine everything is ok - the problem exists only when I am connected with a vnc client to the thin client.

It's not only the "\" - nearly every special character does produce a keycode error.

**Comment by aioobe** [comment]
Is there any news on this? I'm running into this issue as well. 

```
$ xfreerdp --version
This is FreeRDP version 1.1.0-beta1 (git n/a)
```

**Comment by ddombrowsky** [comment]
SImilar issue using `FreeRDP-2.0.0-rc1`.   Connects fine, but every keypress results in something like
```
[08:21:21:938] [16339:16340] [ERROR][com.freerdp.client.x11] - Unknown key with X keycode 0x24
```
I'm just connecting to a local machine from my linux box.  No forwarding or tunneling involved.  No idea what's going on.

**Comment by akallabeth** [comment]
@ddombrowsky Are you using a self compiled version or nightlies? `/buildconfig` would help to diagnose.

**Comment by ddombrowsky** [comment]
@akallabeth My fault.  It must have been a bad build.  When I ran with `/buildconfig`, I noticed that `WITH_X11` was turned off (not sure how I got it to come up at all with that off).  That ain't right.  Did a clean build and install and all is good.  

For the record, I built with 
```
$ cmake -DWITH_X11=ON .
$ make
$ sudo make install
```

**Comment by akallabeth** [comment]
@ddombrowsky good to know it was easy to solve.
