### ISSUE TITLE
The problem that IME of Japanese input is turned off without permission

### ISSUE THREAD

**Issue by ionlionsion** [FreeRDP/FreeRDP#7116]
https://user-images.githubusercontent.com/3740131/123185417-dd899700-d4d0-11eb-84d3-fd8783b80fd8.mp4

I am using winapps, but I think it is a case related to FREErdp, so I asked for it to be described here.

I am using it with Linuxmint 20, but I have a problem with Japanese input, so I posted it because I wanted to know the solution.

As I posted the video, when inputting Japanese with Notepad ++,
Even if I start typing with IME turned on, IME turns off automatically when I enter one character.

Notepad ++ is taken as an example, but when this symptomatism occurs and when it does not occur, it is as follows.

✔ Problem: Notepad ++, file name input field in save dialog of each application, when moving cells in Excel
✔Normal operation: Office Word, Office Power Point, Chrome, etc.

In other information, I thought it was a keyboard layout issue, so I added the command option to xfreerdp.
/ kbd: 0x00000411 / kbd-lang: 0x0c00
It didn't work even if I added.

Is there any solution?

If I start Windows with xfreerdp and start Notepad ++ in it, no problem will occur.
Also, xfreerdp had a problem that the mouse cursor was not changed, so I built and used freerdp-nightly.

```
■ HOST information
 $ xfreerdp --version
This is FreeRDP version 3.0.0-dev (670cf8512)

$ uname -r
5.8.0-55-generic

$ cat / etc / lsb-release
DISTRIB_ID = Linux Mint
DISTRIB_RELEASE = 20.1
DISTRIB_CODENAME = ulyssa
DISTRIB_DESCRIPTION = "Linux Mint 20.1 Ulyssa"

■ GUEST information
Windows 10
Occurs on both Google Japanese Input and Windows IME
Finally, I am sorry that the English is difficult to read because I use a translation tool.
```
I would be grateful if you could have useful information.

**Comment by akallabeth** [comment]
@ionlionsion interesting issue. We´d require some additional information to categorize:

1. Does this work if you use `mstsc` (e.g. the microsoft RDP client) the way you think it should?
2. Are you using desktop or RAILS mode? (e.g. do you have `/app` in your command line)?
1. Could you clarify `If I start Windows with xfreerdp and start Notepad ++ in it, no problem will occur.`? Sorry, not the best in interpreting

**Comment by ionlionsion** [comment]
Thank you for your response.

> 1. Does this work if you use `mstsc` (e.g. the microsoft RDP client) the way you think it should?

I'm sorry, but I haven't tried mstsc yet.

> 2. Are you using desktop or RAILS mode? (e.g. do you have `/app` in your command line)?

Yes, the command line contains `/ app`.
Here is the command that is being executed when the problem actually occurs.

`xfreerdp / d: "" / u: "tm" / p: "XXXXXXX" /v:192.168.122.XXX + auto-reconnect + clipboard + home-drive -wallpaper "" / scale: 100 / scale-desktop: " 115 "/ dynamic-resolution / span / wm-class:" Notepad ++: a free (GPL) source code editor "/ app:" C: \ Program Files (x86) \ Notepad ++ \ notepad ++. Exe "/ app-icon:" /home/XXX/.local/share/winapps/apps/notepad++.exe/icon.svg "/audio-mode:0/microphone/sound 1> / dev / null 2> & 1 &`


> 3. Could you clarify `If I start Windows with xfreerdp and start Notepad ++ in it, no problem will occur.`? Sorry, not the best in interpreting

I'm sorry it was hard to understand.
On the command line
 If you start Notepad ++ after starting Windows without including `/ app`, the problem does not occur.
I have a problem when I try to start Notepad ++ directly by including `/ app` on the command line.

**Comment by ionlionsion** [comment]
> > 1. Does this work if you use `mstsc` (e.g. the microsoft RDP client) the way you think it should?
> 
> I'm sorry, but I haven't tried mstsc yet.

I'm sorry to have kept you waiting.
I have Windows installed on KVM on linuxmint and I am connecting from host to guest with FreeRDP, but I don't know how to connect to Windows on KVM from outside using microsoft RDP client etc.

**Comment by akallabeth** [comment]
@ionlionsion ok, then can you try with https://flathub.org/apps/details/com.thincast.client ?
it also supports rails and is based on FreeRDP, so would be interesting to know if this is a `xfreerdp` issue or a generic `FreeRDP` bug.

**Comment by ionlionsion** [comment]
> @ionlionsion ok, then can you try with https://flathub.org/apps/details/com.thincast.client ?
> it also supports rails and is based on FreeRDP, so would be interesting to know if this is a `xfreerdp` issue or a generic `FreeRDP` bug.

Thank you for your suggestion.

I tried it at https://flathub.org/apps/details/com.thincast.client.
Typing in Japanese was successful in both "Remote Application" and "Desktop".

**Comment by akallabeth** [comment]
@ionlionsion ok, so it is a `xfreerdp` bug related to input handling :/
Thanks for the update.

**Comment by ionlionsion** [comment]
> @ionlionsion ok, so it is a `xfreerdp` bug related to input handling :/
> Thanks for the update.

Thank you for telling me a lot the other day.

When will this bug be fixed?
Or will it not be fixed?

**Comment by akallabeth** [comment]
@ionlionsion can´t give any schedule, but it will eventually be fixed.

**Comment by ionlionsion** [comment]
> @ionlionsion can´t give any schedule, but it will eventually be fixed.

Understood. Thank you very much.

**Comment by panda2134** [comment]
Hi! Are there any update on this issue in the past months?

**Comment by ionlionsion** [comment]
It looks similar to that problem, but I'm guessing that this problem is probably caused by the tooltips that appear during the IME conversion taking focus.
It seems that he hasn't solved this problem as of FreeRDP version 2.6.1.

**Comment by amazingfate** [comment]
It seems that the master branch has solved it, but I don't know which commit fixes this issue..

**Comment by ionlionsion** [comment]
I installed "freerdp-nightly-binaries ubuntu" today and it solved this problem.
https://ci.freerdp.com/job/freerdp-nightly-binaries/

I hope it also applies to the official version.

**Comment by amazingfate** [comment]
@ionlionsion Hello, I want to know how do you toggle the Japanese input method. Sometimes I can click the tray icon opened with the remote app window but sometimes there is not a tray icon, I can't toggle the IME using keyboard shortcut.

**Comment by ionlionsion** [comment]
> **[amazingfate](/amazingfate) ** commented [7 日前](#issuecomment-1196585245)
>I can't toggle the IME using keyboard shortcut.
⇒In my environment, I can switch Windows IME ON / OFF by using "half-width / full-width" （半角/全角） on the keyboard, so I don't know how to solve your problem.

**Comment by oicu** [comment]
安装第三方输入法，比如中文搜狗输入法(sougou pinyin)，在 remote app 模式里，可以用它自带快捷键 `Ctrl+,`切换。可以参考这个解决思路。

**Comment by philopatrick** [comment]
> winappsScreencast.2021-06-18.09.44.13.mp4
> 
> I am using winapps, but I think it is a case related to FREErdp, so I asked for it to be described here.
> 
> I am using it with Linuxmint 20, but I have a problem with Japanese input, so I posted it because I wanted to know the solution.
> 
> As I posted the video, when inputting Japanese with Notepad ++, Even if I start typing with IME turned on, IME turns off automatically when I enter one character.
> 
> Notepad ++ is taken as an example, but when this symptomatism occurs and when it does not occur, it is as follows.
> 
> ✔ Problem: Notepad ++, file name input field in save dialog of each application, when moving cells in Excel ✔Normal operation: Office Word, Office Power Point, Chrome, etc.
> 
> In other information, I thought it was a keyboard layout issue, so I added the command option to xfreerdp. / kbd: 0x00000411 / kbd-lang: 0x0c00 It didn't work even if I added.
> 
> Is there any solution?
> 
> If I start Windows with xfreerdp and start Notepad ++ in it, no problem will occur. Also, xfreerdp had a problem that the mouse cursor was not changed, so I built and used freerdp-nightly.
> 
> ```
> ■ HOST information
>  $ xfreerdp --version
> This is FreeRDP version 3.0.0-dev (670cf8512)
> 
> $ uname -r
> 5.8.0-55-generic
> 
> $ cat / etc / lsb-release
> DISTRIB_ID = Linux Mint
> DISTRIB_RELEASE = 20.1
> DISTRIB_CODENAME = ulyssa
> DISTRIB_DESCRIPTION = "Linux Mint 20.1 Ulyssa"
> 
> ■ GUEST information
> Windows 10
> Occurs on both Google Japanese Input and Windows IME
> Finally, I am sorry that the English is difficult to read because I use a translation tool.
> ```
> 
> I would be grateful if you could have useful information.

In standard version, you can toggle full screen, and this will be solved.
