### ISSUE TITLE
FreeRDP no longer builds with Ninja

### ISSUE THREAD

**Issue by etna** [FreeRDP/FreeRDP#7122]
I make weekly builds of FreeRDP and the last build I was able to make using Ninja was last week, on 19 Jun.

Today (26 Jun), when I pass the following parameters to cmake:
`cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/etna/Runtime/Applications/FreeRDP/<build date> -DCMAKE_BUILD_TYPE=Release -DCHANNEL_URBDRC=OFF -DWITH_WAYLAND=ON -DWITH_SERVER=ON ..`

the build process eventually fails with the following errors:
```
../winpr/libwinpr/synch/event.c:56:12: error: static declaration of 'eventfd_read' follows non-static declaration
static int eventfd_read(int fd, eventfd_t* value)
           ^
/usr/include/x86_64-linux-gnu/sys/eventfd.h:37:12: note: previous declaration is here
extern int eventfd_read (int __fd, eventfd_t *__value);
           ^
../winpr/libwinpr/synch/event.c:61:12: error: static declaration of 'eventfd_write' follows non-static declaration
static int eventfd_write(int fd, eventfd_t value)
           ^
/usr/include/x86_64-linux-gnu/sys/eventfd.h:40:12: note: previous declaration is here
extern int eventfd_write (int __fd, eventfd_t __value);
           ^
2 errors generated.
ninja: build stopped: subcommand failed.
```

Removing -GNinja and dropping back to regular make results in FreeRDP successfully being built.

Was able to produce this on both ninja 1.10.1, ninja 1.10.2 and the latest git version of ninja

Any help will be greatly appreciated.

**Comment by etna** [comment]
A little more information:

I found that commit 534d30beb39ea10a744add90765bc1c796c774ee broke the build.

Am on Debian 10 with custom built Ninja and Clang 9

**Comment by akallabeth** [comment]
@etna ok, strange. I just did a quick build of 8eff8259713ac6efae951c5ea66dd285cee504e6 on my ubuntu 20.04 and debian 11 machines and it is working nicely with ninja. (your exact command line, just the paths changed to match mine)

**Comment by akallabeth** [comment]
@etna could it be that there are some artifacts left from a previous build in your source directory? `git clean -xdf` might help.

**Comment by etna** [comment]
My source directory is cloned into tmpfs, so it's always clean with no artefacts.

I also umounted and created a new tmpfs with the same build results.

**Comment by etna** [comment]
If it helps, this is my full build command:

`LIBRARY_PATH=/home/etna/Runtime/opt/libunistring-0.9.10/lib:/home/etna/Runtime/opt/libtasn1-4.16.0/lib:/home/etna/Runtime/opt/p11-kit-0.23.22/lib:/home/etna/Runtime/opt/gmp-6.2.1/lib:/home/etna/Runtime/opt/nettle-3.6/lib64:/home/etna/Runtime/opt/gnutls-3.7.0/lib:/home/etna/Runtime/opt/libxml2-2.9.10/lib:/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/lib:/home/etna/Runtime/opt/sqlite-3.31.1/lib:/home/etna/Runtime/opt/libbz2-1.0.8/lib:/home/etna/Runtime/opt/Python3.9.0/lib:/home/etna/Runtime/opt/Python3.9.0/lib64:/home/etna/Runtime/opt/libssh2-1.9.0/lib:/home/etna/Runtime/opt/libnotify-0.7.8/lib:/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu:/home/etna/Runtime/lib:/home/etna/Runtime/lib/x86_64-linux-gnu:/home/etna/Runtime/lib64:$LIBRARY_PATH C_INCLUDE_PATH=/home/etna/Runtime/opt/libunistring-0.9.10/include:/home/etna/Runtime/opt/libtasn1-4.16.0/include:/home/etna/Runtime/opt/p11-kit-0.23.22/include:/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1:/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1/p11-kit:/home/etna/Runtime/opt/gmp-6.2.1/include:/home/etna/Runtime/opt/nettle-3.6/include:/home/etna/Runtime/opt/nettle-3.6/include/nettle:/home/etna/Runtime/opt/gnutls-3.7.0/include:/home/etna/Runtime/opt/gnutls-3.7.0/include/gnutls:/home/etna/Runtime/opt/libxml2-2.9.10/include:/home/etna/Runtime/opt/libxml2-2.9.10/include/libexslt:/home/etna/Runtime/opt/libxml2-2.9.10/include/libxml2:/home/etna/Runtime/opt/libxml2-2.9.10/include/libxslt:/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/include:/home/etna/Runtime/opt/sqlite-3.31.1/include:/home/etna/Runtime/opt/libbz2-1.0.8/include:/home/etna/Runtime/opt/Python3.9.0/include:/home/etna/Runtime/opt/Python3.9.0/include/python3.9:/home/etna/Runtime/opt/libssh2-1.9.0/include:/home/etna/Runtime/opt/libnotify-0.7.8/include:/home/etna/Runtime/opt/libnotify-0.7.8/include/libnotify:/home/etna/Runtime/include:$C_INCLUDE_PATH CPLUS_INCLUDE_PATH=/home/etna/Runtime/opt/libunistring-0.9.10/include:/home/etna/Runtime/opt/libtasn1-4.16.0/include:/home/etna/Runtime/opt/p11-kit-0.23.22/include:/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1:/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1/p11-kit:/home/etna/Runtime/opt/gmp-6.2.1/include:/home/etna/Runtime/opt/nettle-3.6/include:/home/etna/Runtime/opt/nettle-3.6/include/nettle:/home/etna/Runtime/opt/gnutls-3.7.0/include:/home/etna/Runtime/opt/gnutls-3.7.0/include/gnutls:/home/etna/Runtime/opt/libxml2-2.9.10/include:/home/etna/Runtime/opt/libxml2-2.9.10/include/libexslt:/home/etna/Runtime/opt/libxml2-2.9.10/include/libxml2:/home/etna/Runtime/opt/libxml2-2.9.10/include/libxslt:/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/include:/home/etna/Runtime/opt/sqlite-3.31.1/include:/home/etna/Runtime/opt/libbz2-1.0.8/include:/home/etna/Runtime/opt/Python3.9.0/include:/home/etna/Runtime/opt/Python3.9.0/include/python3.9:/home/etna/Runtime/opt/libssh2-1.9.0/include:/home/etna/Runtime/opt/libnotify-0.7.8/include:/home/etna/Runtime/opt/libnotify-0.7.8/include/libnotify:/home/etna/Runtime/include:$CPLUS_INCLUDE_PATH LD_LIBRARY_PATH=/home/etna/Runtime/opt/libunistring-0.9.10/lib:/home/etna/Runtime/opt/libtasn1-4.16.0/lib:/home/etna/Runtime/opt/p11-kit-0.23.22/lib:/home/etna/Runtime/opt/gmp-6.2.1/lib:/home/etna/Runtime/opt/nettle-3.6/lib64:/home/etna/Runtime/opt/gnutls-3.7.0/lib:/home/etna/Runtime/opt/libxml2-2.9.10/lib:/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/lib:/home/etna/Runtime/opt/sqlite-3.31.1/lib:/home/etna/Runtime/opt/libbz2-1.0.8/lib:/home/etna/Runtime/opt/Python3.9.0/lib:/home/etna/Runtime/opt/Python3.9.0/lib64:/home/etna/Runtime/opt/libssh2-1.9.0/lib:/home/etna/Runtime/opt/libnotify-0.7.8/lib:/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu:/home/etna/Runtime/lib:/home/etna/Runtime/lib/x86_64-linux-gnu:/home/etna/Runtime/lib64:$LD_LIBRARY_PATH PATH=/home/etna/Runtime/opt/libtasn1-4.16.0/bin:/home/etna/Runtime/opt/p11-kit-0.23.22/bin:/home/etna/Runtime/opt/p11-kit-0.23.22/libexec:/home/etna/Runtime/opt/nettle-3.6/bin:/home/etna/Runtime/opt/gnutls-3.7.0/bin:/home/etna/Runtime/opt/libxml2-2.9.10/bin:/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/bin:/home/etna/Runtime/opt/sqlite-3.31.1/bin:/home/etna/Runtime/opt/libbz2-1.0.8/bin:/home/etna/Runtime/opt/Python3.9.0/bin:/home/etna/Runtime/opt/libnotify-0.7.8/bin:/home/etna/Runtime/opt/gperf-3.1/bin:/home/etna/Runtime/bin:/home/etna/Runtime/libexec:$PATH PKG_CONFIG_PATH=/home/etna/Runtime/opt/libtasn1-4.16.0/lib/pkgconfig:/home/etna/Runtime/opt/p11-kit-0.23.22/lib/pkgconfig:/home/etna/Runtime/opt/gmp-6.2.1/lib/pkgconfig:/home/etna/Runtime/opt/nettle-3.6/lib64/pkgconfig:/home/etna/Runtime/opt/gnutls-3.7.0/lib/pkgconfig:/home/etna/Runtime/opt/libxml2-2.9.10/lib/pkgconfig:/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/lib/pkgconfig:/home/etna/Runtime/opt/sqlite-3.31.1/lib/pkgconfig:/home/etna/Runtime/opt/Python3.9.0/lib/pkgconfig:/home/etna/Runtime/opt/Python3.9.0/lib64/pkgconfig:/home/etna/Runtime/opt/libssh2-1.9.0/lib/pkgconfig:/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu/pkgconfig:/home/etna/Runtime/lib/pkgconfig:/home/etna/Runtime/lib/x86_64-linux-gnu/pkgconfig:/home/etna/Runtime/lib64/pkgconfig:$PKG_CONFIG_PATH LDFLAGS='-L/home/etna/Runtime/opt/libunistring-0.9.10/lib -L/home/etna/Runtime/opt/libtasn1-4.16.0/lib -L/home/etna/Runtime/opt/p11-kit-0.23.22/lib -L/home/etna/Runtime/opt/gmp-6.2.1/lib -L/home/etna/Runtime/opt/nettle-3.6/lib64 -L/home/etna/Runtime/opt/gnutls-3.7.0/lib -L/home/etna/Runtime/opt/libxml2-2.9.10/lib -L/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/lib -L/home/etna/Runtime/opt/sqlite-3.31.1/lib -L/home/etna/Runtime/opt/libbz2-1.0.8/lib -L/home/etna/Runtime/opt/Python3.9.0/lib -L/home/etna/Runtime/opt/Python3.9.0/lib64 -L/home/etna/Runtime/opt/libssh2-1.9.0/lib -L/home/etna/Runtime/opt/libnotify-0.7.8/lib -L/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu -L/home/etna/Runtime/lib -L/home/etna/Runtime/lib/x86_64-linux-gnu -L/home/etna/Runtime/lib64' CPPFLAGS='-I/home/etna/Runtime/opt/libunistring-0.9.10/include -I/home/etna/Runtime/opt/libtasn1-4.16.0/include -I/home/etna/Runtime/opt/p11-kit-0.23.22/include -I/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1 -I/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1/p11-kit -I/home/etna/Runtime/opt/gmp-6.2.1/include -I/home/etna/Runtime/opt/nettle-3.6/include -I/home/etna/Runtime/opt/nettle-3.6/include/nettle -I/home/etna/Runtime/opt/gnutls-3.7.0/include -I/home/etna/Runtime/opt/gnutls-3.7.0/include/gnutls -I/home/etna/Runtime/opt/libxml2-2.9.10/include -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libexslt -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libxml2 -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libxslt -I/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/include -I/home/etna/Runtime/opt/sqlite-3.31.1/include -I/home/etna/Runtime/opt/libbz2-1.0.8/include -I/home/etna/Runtime/opt/Python3.9.0/include -I/home/etna/Runtime/opt/Python3.9.0/include/python3.9 -I/home/etna/Runtime/opt/libssh2-1.9.0/include -I/home/etna/Runtime/opt/libnotify-0.7.8/include -I/home/etna/Runtime/opt/libnotify-0.7.8/include/libnotify -I/home/etna/Runtime/include' CC=/home/etna/Runtime/bin/clang CXX=/home/etna/Runtime/bin/clang++ CFLAGS='-L/home/etna/Runtime/opt/libunistring-0.9.10/lib -L/home/etna/Runtime/opt/libtasn1-4.16.0/lib -L/home/etna/Runtime/opt/p11-kit-0.23.22/lib -L/home/etna/Runtime/opt/gmp-6.2.1/lib -L/home/etna/Runtime/opt/nettle-3.6/lib64 -L/home/etna/Runtime/opt/gnutls-3.7.0/lib -L/home/etna/Runtime/opt/libxml2-2.9.10/lib -L/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/lib -L/home/etna/Runtime/opt/sqlite-3.31.1/lib -L/home/etna/Runtime/opt/libbz2-1.0.8/lib -L/home/etna/Runtime/opt/Python3.9.0/lib -L/home/etna/Runtime/opt/Python3.9.0/lib64 -L/home/etna/Runtime/opt/libssh2-1.9.0/lib -L/home/etna/Runtime/opt/libnotify-0.7.8/lib -L/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu -L/home/etna/Runtime/lib -L/home/etna/Runtime/lib/x86_64-linux-gnu -L/home/etna/Runtime/lib64 -I/home/etna/Runtime/opt/libunistring-0.9.10/include -I/home/etna/Runtime/opt/libtasn1-4.16.0/include -I/home/etna/Runtime/opt/p11-kit-0.23.22/include -I/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1 -I/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1/p11-kit -I/home/etna/Runtime/opt/gmp-6.2.1/include -I/home/etna/Runtime/opt/nettle-3.6/include -I/home/etna/Runtime/opt/nettle-3.6/include/nettle -I/home/etna/Runtime/opt/gnutls-3.7.0/include -I/home/etna/Runtime/opt/gnutls-3.7.0/include/gnutls -I/home/etna/Runtime/opt/libxml2-2.9.10/include -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libexslt -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libxml2 -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libxslt -I/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/include -I/home/etna/Runtime/opt/sqlite-3.31.1/include -I/home/etna/Runtime/opt/libbz2-1.0.8/include -I/home/etna/Runtime/opt/Python3.9.0/include -I/home/etna/Runtime/opt/Python3.9.0/include/python3.9 -I/home/etna/Runtime/opt/libssh2-1.9.0/include -I/home/etna/Runtime/opt/libnotify-0.7.8/include -I/home/etna/Runtime/opt/libnotify-0.7.8/include/libnotify -I/home/etna/Runtime/include -Wl,-rpath -Wl,/home/etna/Runtime/opt/libunistring-0.9.10/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libtasn1-4.16.0/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/p11-kit-0.23.22/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/gmp-6.2.1/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/nettle-3.6/lib64 -Wl,-rpath -Wl,/home/etna/Runtime/opt/gnutls-3.7.0/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libxml2-2.9.10/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/sqlite-3.31.1/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libbz2-1.0.8/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/Python3.9.0/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/Python3.9.0/lib64 -Wl,-rpath -Wl,/home/etna/Runtime/opt/libssh2-1.9.0/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libnotify-0.7.8/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu -Wl,-rpath -Wl,/home/etna/Runtime/lib -Wl,-rpath -Wl,/home/etna/Runtime/lib/x86_64-linux-gnu -Wl,-rpath -Wl,/home/etna/Runtime/lib64 -fPIC' CXXFLAGS='-L/home/etna/Runtime/opt/libunistring-0.9.10/lib -L/home/etna/Runtime/opt/libtasn1-4.16.0/lib -L/home/etna/Runtime/opt/p11-kit-0.23.22/lib -L/home/etna/Runtime/opt/gmp-6.2.1/lib -L/home/etna/Runtime/opt/nettle-3.6/lib64 -L/home/etna/Runtime/opt/gnutls-3.7.0/lib -L/home/etna/Runtime/opt/libxml2-2.9.10/lib -L/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/lib -L/home/etna/Runtime/opt/sqlite-3.31.1/lib -L/home/etna/Runtime/opt/libbz2-1.0.8/lib -L/home/etna/Runtime/opt/Python3.9.0/lib -L/home/etna/Runtime/opt/Python3.9.0/lib64 -L/home/etna/Runtime/opt/libssh2-1.9.0/lib -L/home/etna/Runtime/opt/libnotify-0.7.8/lib -L/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu -L/home/etna/Runtime/lib -L/home/etna/Runtime/lib/x86_64-linux-gnu -L/home/etna/Runtime/lib64 -I/home/etna/Runtime/opt/libunistring-0.9.10/include -I/home/etna/Runtime/opt/libtasn1-4.16.0/include -I/home/etna/Runtime/opt/p11-kit-0.23.22/include -I/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1 -I/home/etna/Runtime/opt/p11-kit-0.23.22/include/p11-kit-1/p11-kit -I/home/etna/Runtime/opt/gmp-6.2.1/include -I/home/etna/Runtime/opt/nettle-3.6/include -I/home/etna/Runtime/opt/nettle-3.6/include/nettle -I/home/etna/Runtime/opt/gnutls-3.7.0/include -I/home/etna/Runtime/opt/gnutls-3.7.0/include/gnutls -I/home/etna/Runtime/opt/libxml2-2.9.10/include -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libexslt -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libxml2 -I/home/etna/Runtime/opt/libxml2-2.9.10/include/libxslt -I/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/include -I/home/etna/Runtime/opt/sqlite-3.31.1/include -I/home/etna/Runtime/opt/libbz2-1.0.8/include -I/home/etna/Runtime/opt/Python3.9.0/include -I/home/etna/Runtime/opt/Python3.9.0/include/python3.9 -I/home/etna/Runtime/opt/libssh2-1.9.0/include -I/home/etna/Runtime/opt/libnotify-0.7.8/include -I/home/etna/Runtime/opt/libnotify-0.7.8/include/libnotify -I/home/etna/Runtime/include -Wl,-rpath -Wl,/home/etna/Runtime/opt/libunistring-0.9.10/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libtasn1-4.16.0/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/p11-kit-0.23.22/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/gmp-6.2.1/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/nettle-3.6/lib64 -Wl,-rpath -Wl,/home/etna/Runtime/opt/gnutls-3.7.0/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libxml2-2.9.10/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/ffmpeg-Build19Jun2021/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/sqlite-3.31.1/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libbz2-1.0.8/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/Python3.9.0/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/Python3.9.0/lib64 -Wl,-rpath -Wl,/home/etna/Runtime/opt/libssh2-1.9.0/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libnotify-0.7.8/lib -Wl,-rpath -Wl,/home/etna/Runtime/opt/libnotify-0.7.8/lib/x86_64-linux-gnu -Wl,-rpath -Wl,/home/etna/Runtime/lib -Wl,-rpath -Wl,/home/etna/Runtime/lib/x86_64-linux-gnu -Wl,-rpath -Wl,/home/etna/Runtime/lib64 -fPIC' cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/etna/Runtime/Applications/FreeRDP/<build date> -DCMAKE_BUILD_TYPE=Release -DCHANNEL_URBDRC=OFF -DWITH_WAYLAND=ON -DWITH_SERVER=ON ..`

**Comment by akallabeth** [comment]
@etna I´ve found a few (hidden) problems with the latest `CMake` refactoring. Could you check #7125 fixes your issues?

**Comment by etna** [comment]
@akallabeth  Yes, it builds now! Thanks very much for your help! ^_^

Will test out the build tomorrow to see if it functions as expected.
