### ISSUE TITLE
Segmentation fault on Windows 2003 terminal server farm redirect via connection broker

### ISSUE THREAD

**Issue by SteveDiG1** [FreeRDP/FreeRDP#713]
Running a Win2K3 TS farm on R2 Enterprise of course. This is behind an F5 load balancer and is using token based redirection with Win2K8 R2 connection broker providing this function. 

XfreeRdp 1.0.1 connects, authentication occurs and then we get a segfault on the redirection token. Commands executed and results below.

----allow sec protocol detection-----

command executed: 

xfreerdp -z -a 16 -g 1400x800 -d DomainName -u ${USER} --plugin cliprdr --plugin rdpdr --data disk:${USERNAME}:${HOME} -- server.subdomain.domain.com

result:

loading plugin cliprdr
loading plugin rdpdr
connected to server.subdomain.domain.com:3389
connected to server.subdomain.domain.com:3389
connected to server.subdomain.domain.com:3389
E
connected to server.subdomain.domain.com:3389
connected to server.subdomain.domain.com:3389
connected to server.subdomain.domain.com:3389
E
WARNING: invalid packet signature
Warning update_recv_surfcmds (86): unknown cmdType 0x39D8
WARNING: invalid packet signature
WARNING: invalid packet signature
WARNING: invalid packet signature
Warning update_recv_surfcmds (86): unknown cmdType 0x9D7B
WARNING: invalid packet signature
WARNING: invalid packet signature
WARNING: invalid packet signature
Segmentation fault

----specifying rdp security protocol---

command executed: 

xfreerdp -z -a 16 -g 1400x800 -d DomainName -u ${USER} --sec rdp --plugin cliprdr --plugin rdpdr --data disk:${USERNAME}:${HOME} -- server.subdomain.domain.com

result:

loading plugin cliprdr
loading plugin rdpdr
connected to server.subdomain.domain.com:3389
E
connected to server.subdomain.domain.com:3389
E
WARNING: invalid packet signature
Segmentation fault

------------

Redirection works like a charm with my Win2K8 and Win2K8 R2 TS Farms. All of them are also behind F5 load balancer with the same 2K8 R2 connection broker & token based redirection.

The Win2K3 server farm, which I have to run to support older Oracle developer tools (sigh), segfaults on redirect every time however.

**Comment by akallabeth** [comment]
closing for being inactive for a very long time. Reopen if still relevant.
