### ISSUE TITLE
Using a network key

### ISSUE THREAD

**Issue by amfogor** [FreeRDP/FreeRDP#7138]
I have a program using a network key as a licence key.

And when connecting with FreeRDP the program doesn't see the key.

Is there a way to make it work?

**Comment by hardening** [comment]
What do you mean by network key, is it a physical dongle ?

**Comment by amfogor** [comment]
@hardening yes. It is inserted in my PC in a USB port

**Comment by akallabeth** [comment]
@amfogor did you try to redirect with `/usb`?

**Comment by amfogor** [comment]
@akallabeth I'm sorry for not being clear. It is inserted in the PC I'm connecting to.

So if I use the PC physically, the program works. If I use the PC through FreeRDP, the program doesn't work.

**Comment by amfogor** [comment]
Oh, sorry, it's probably a restriction of the key.
