### ISSUE TITLE
Disabling wallpapers, themes, window dragging does not work 

### ISSUE THREAD

**Issue by lmolokin** [FreeRDP/FreeRDP#7147]
**Describe the bug**
Disabling wallpaper, themes, and window dragging does not work.

**Expected behavior**
No background wallpaper, themes, or redrawing of window contents while dragging.

**Screenshots**
Screencap from remote host:
![Alt Text](https://i.imgur.com/q655QQR.gif)

**Application details**
* FreeRDP version 2.3.2
* Command line used
`xfreerdp /u:$user /v:$host -wallpaper -themes`

* Output of `xfreerdp /buildconfig`
See log output...

* OS version connecting to: Ubuntu 21.04

* Output from /log-level:trace

> [11:42:45:316] [22323:22323] [DEBUG][com.freerdp.client.common] - This is Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
> Build type:          Release
> CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
> Compiler:            GNU, 10.3.0
> Target architecture: x64
> 
> [11:42:45:316] [22323:22326] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
> [11:42:45:316] [22323:22326] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpdr
> [11:42:45:316] [22323:22326] [INFO][com.freerdp.client.common.cmdline] - loading channelEx rdpsnd
> [11:42:45:316] [22323:22326] [DEBUG][com.freerdp.channels.cliprdr.client] - VirtualChannelEntryEx
> [11:42:45:316] [22323:22326] [INFO][com.freerdp.client.common.cmdline] - loading channelEx cliprdr
> [11:42:45:318] [22323:22326] [DEBUG][com.freerdp.primitives] - primitives benchmark result:
> [11:42:45:471] [22323:22326] [DEBUG][com.freerdp.primitives] -  * generic= 61
> [11:42:45:622] [22323:22326] [DEBUG][com.freerdp.primitives] -  * optimized= 191
> [11:42:45:622] [22323:22326] [INFO][com.freerdp.primitives] - primitives autodetect, using optimized
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core.nego] - Enabling security layer negotiation: TRUE
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core.nego] - Enabling restricted admin mode: FALSE
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core.nego] - Enabling RDP security: TRUE
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core.nego] - Enabling TLS security: TRUE
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core.nego] - Enabling NLA security: TRUE
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core.nego] - Enabling NLA extended security: FALSE
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_NLA
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core.nego] - Attempting NLA security
> [11:42:45:624] [22323:22326] [INFO][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex resetting error state
> [11:42:45:624] [22323:22326] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state
> [11:42:45:624] [22323:22326] [DEBUG][com.freerdp.core] - connecting to peer [hidden]
> [11:42:45:644] [22323:22326] [DEBUG][com.freerdp.core.nego] - RequestedProtocols: 3
> [11:42:45:696] [22323:22326] [DEBUG][com.freerdp.core.nego] - RDP_NEG_RSP
> [11:42:45:696] [22323:22326] [DEBUG][com.freerdp.core.nego] - selected_protocol: 1
> [11:42:45:696] [22323:22326] [DEBUG][com.freerdp.core.nego] - state: NEGO_STATE_FINAL
> [11:42:45:696] [22323:22326] [DEBUG][com.freerdp.core.nego] - Negotiated TLS security
> [11:42:45:696] [22323:22326] [DEBUG][com.freerdp.core.nego] - nego_security_connect with PROTOCOL_SSL
> [11:42:45:819] [22323:22326] [DEBUG][com.freerdp.core.gcc] - Server rdp encryption method: NONE
> [11:42:46:421] [22323:22326] [DEBUG][com.freerdp.core.info] - Client Info Packet Flags = INFO_MOUSE|INFO_DISABLECTRLALTDEL|INFO_AUTOLOGON|INFO_UNICODE|INFO_MAXIMIZESHELL|INFO_LOGONNOTIFY|INFO_COMPRESSION|INFO_ENABLEWINDOWSKEY|INFO_FORCE_ENCRYPTED_CS_PDU|INFO_LOGONERRORS|INFO_MOUSE_HAS_WHEEL|INFO_NOAUDIOPLAYBACK
> [11:42:46:421] [22323:22326] [DEBUG][com.winpr.timezone] - tz: Bias=300 sn='Eastern Standard Time' dln='Eastern Daylight Time'
> [11:42:46:622] [22323:22326] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x1f size=37 channelId=1002)
> [11:42:46:622] [22323:22326] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x14 size=41 channelId=1002)
> [11:42:46:622] [22323:22326] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x14 size=41 channelId=1002)
> [11:42:46:622] [22323:22326] [DEBUG][com.freerdp.core.rdp] - rdp_send_data_pdu: sending data (type=0x27 size=41 channelId=1002)
> [11:42:46:722] [22323:22326] [DEBUG][com.freerdp.core.rdp] - recv Synchronize Data PDU (0x1F), length: 22
> [11:42:46:722] [22323:22326] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
> [11:42:46:722] [22323:22326] [DEBUG][com.freerdp.core.rdp] - recv Control Data PDU (0x14), length: 26
> [11:42:46:722] [22323:22326] [DEBUG][com.freerdp.core.rdp] - recv Font Map Data PDU (0x28), length: 26
> [11:42:46:722] [22323:22326] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_BGRX32
> [11:42:46:722] [22323:22326] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_RGB16
> [11:42:46:750] [22323:22326] [INFO][com.winpr.clipboard] - initialized POSIX local file subsystem
> [11:42:46:751] [22323:22326] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from _xf_Pointer_GetCursorForCurrentScale
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from _xf_Pointer_GetCursorForCurrentScale
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_Pointer_Set
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_Pointer_Set
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from _xf_Pointer_GetCursorForCurrentScale
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from _xf_Pointer_GetCursorForCurrentScale
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_Pointer_Set
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_Pointer_Set
> [11:42:46:757] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:759] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:771] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:771] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:791] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:791] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:811] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:811] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:831] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:831] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:834] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:834] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:834] [22323:22353] [DEBUG][com.freerdp.channels.cliprdr.client] - ServerCapabilities
> [11:42:46:834] [22323:22353] [DEBUG][com.freerdp.channels.cliprdr.client] - MonitorReady
> [11:42:46:834] [22323:22353] [DEBUG][com.freerdp.channels.cliprdr.client] - ClientCapabilities
> [11:42:46:834] [22323:22353] [DEBUG][com.freerdp.channels.cliprdr.client] - ClientFormatList: numFormats: 9
> [11:42:46:834] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:834] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:834] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:834] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:834] [22323:22327] [DEBUG][com.freerdp.channels.rdpsnd.client] - [static] Server Audio Formats
> [11:42:46:834] [22323:22327] [DEBUG][com.freerdp.channels.rdpsnd.client] - [static] Client Audio Formats
> [11:42:46:834] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:834] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:835] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:835] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:835] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:835] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:836] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from _xf_Pointer_GetCursorForCurrentScale
> [11:42:46:836] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from _xf_Pointer_GetCursorForCurrentScale
> [11:42:46:836] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_Pointer_Set
> [11:42:46:836] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_Pointer_Set
> [11:42:46:836] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:836] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:850] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:850] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:850] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:850] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:851] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:851] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:852] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:852] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:852] [22323:22353] [DEBUG][com.freerdp.channels.cliprdr.client] - ServerFormatListResponse
> [11:42:46:853] [22323:22327] [DEBUG][com.freerdp.channels.rdpsnd.client] - [static] Training Request: wTimeStamp: 64316 wPackSize: 1024
> [11:42:46:853] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:853] [22323:22327] [DEBUG][com.freerdp.channels.rdpsnd.client] - [static] Training Response: wTimeStamp: 64316 wPackSize: 1024
> [11:42:46:853] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> [11:42:46:853] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
> [11:42:46:853] [22323:22326] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
> 
> truncated...

**Environment (please complete the following information):**
 - OS: Ubuntu 21.04 (issue also occurs with 20.04 LTS)
 - Architecture: amd64

**Additional context**
Connected to remote host network through VPN

**Comment by akallabeth** [comment]
Invalid.
The flags are `suggestions` the client sends to the server.
It is up to the server to honor or ignore these.
