### ISSUE TITLE
Option +font doesn't work on version 2.2.0

### ISSUE THREAD

**Issue by AlfredoLlaquet** [FreeRDP/FreeRDP#7153]
Ubuntu 20.04.2 LTS 64 bits connecting to Windows 10 64 bits. Fonts always appear without smoothing. Option +fonts seems to do nothing. Everything else works fine. My command line:

xfreerdp +aero +wallpaper +window-drag +clipboard +bitmap-cache +fonts +drives /gdi:hw /network:broadband-high /audio-mode:0 /multimon +auto-reconnect /auto-reconnect-max-retries:5 +gfx-progressive /video /d:xxxxxxx /u:xxxxx /p:xxxxx /v:xxxxxxx

**Comment by akallabeth** [comment]
Invalid.
This is a flag sent to the server. It is up to the server to honor it.
Best thing to do is just use `/network:auto` instead of all the specific options.
