### ISSUE TITLE
NEON problems in arm64 build

### ISSUE THREAD

**Issue by whitpa** [FreeRDP/FreeRDP#7158]
I encountered a couple of easily correctable build issues when attempting to compile FreeRDP 2.3.2 on a Debian 10 (Buster) arm64 platform.

- libfreerdp/CMakeLists.txt adds "-mcpu=neon" when WITH_NEON is defined.  gcc 8.3.0 for aarch64 rejects "-mfpu=neon" as an invalid option, so I had to remove that.  According to https://stackoverflow.com/questions/29851128/gcc-arm64-aarch64-unrecognized-command-line-option-mfpu-neon, this option is implied for aarch64 and therefore unncessary.
- libfreerdp/codec/rfx_neon.c guards NEON-specific code with "#if defined(\_\_ARM_NEON\_\_)", and for some reason that isn't defined by gcc 8.3.0 aarch64, which results in a link error due to "rfx_init_neon" being undefined.  I changed this to "#if defined(\_\_ARM_NEON\_\_) || defined(__ARM_NEON)" instead.

FYI the build command I used was:
cmake -DCMAKE_INSTALL_PREFIX=/opt/freerdp2 -DCMAKE_INSTALL_LIBDIR=lib \
        -DCMAKE_SKIP_RPATH=ON -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_SHARED_LINKER_FLAGS='-Wl,-rpath -Wl,/opt/freerdp2/lib' \
        -DCMAKE_EXE_LINKER_FLAGS='-Wl,-rpath -Wl,/opt/freerdp2/lib' \
        -DWITH_PULSE=ON -DWITH_CUPS=ON -DWITH_PCSC=ON -DWITH_JPEG=OFF \
        -DWITH_X264=OFF -DWITH_GSM=ON -DWITH_LAME=ON -DWITH_SOXR=ON \
        -DCHANNEL_URBDRC_CLIENT=ON -DWITH_FFMPEG=ON -DWITH_CAIRO=ON \
        -DWITH_SSE2=OFF -DWITH_NEON=ON -DWITH_GSTREAMER_1_0=OFF \
        -DWITH_WAYLAND=OFF -DWITH_OSS=OFF -DWITH_GSSAPI=OFF -DWITH_FUSE=ON

**Comment by whitpa** [comment]
N.B. That should read "____ARM_NEON____" rather than "__ARM_NEON__", as the editor interpreted the underscores as markdown for bold type.

**Comment by whitpa** [comment]
Sigh.  How about: <pre>__ARM_NEON__</pre> rather than __ARM_NEON__ .

**Comment by whitpa** [comment]
Sorry, some underscores got interpreted as markdown for bold type.

I meant to say:

```#if defined(ARM_NEON) || defined(__ARM_NEON)```

**Comment by whitpa** [comment]
Sorry, some underscores got interpreted as markdown for bold type.  I meant to say:

```#if defined(__ARM_NEON__) || defined(__ARM_NEON)```

**Comment by whitpa** [comment]
The fix works, although commit 1ee566810c74cd06eb5977c6105d8715b23d80a2 is not quite right for FreeRDP 2.3.2 at its release state, which is my specific interest.  Equivalent patch for 2.3.2 release attached.
[freerdp-2.3.2-arm64_fixup.txt](https://github.com/FreeRDP/FreeRDP/files/6780750/freerdp-2.3.2-arm64_fixup.txt)

**Comment by whitpa** [comment]
The fix works, although commit 1ee566810c74cd06eb5977c6105d8715b23d80a2 is not quite right for FreeRDP 2.3.2 at its release state, which is my specific interest.  Equivalent patch for 2.3.2 release attached.
[freerdp-2.3.2-arm64_fixup.txt](https://github.com/FreeRDP/FreeRDP/files/6780754/freerdp-2.3.2-arm64_fixup.txt)

**Comment by whitpa** [comment]
FreeRDP releases (up to and including  2.7.0) continue to require manual patching, so somehow the above fix has not been merged.

**Comment by akallabeth** [comment]
@whitpa thank you for the reminder.
best create a pull request if you want something in stable, that way it will get in faster.
