### ISSUE TITLE
Android Port Bug： When I send data to the remote host's clipboard, the last character is lost 

### ISSUE THREAD

**Issue by xiaoyvyv** [FreeRDP/FreeRDP#7164]
### Branches: master 2021/7/9
When I send ‘Hello World’ to the remote host's clipboard, the last character 'd' is lost. 
### LibFreeRDP.kt
```kotlin
private external fun freerdp_send_clipboard_data(inst: Long, data: String): Boolean
```

### android_freerdp.c
```c
static jboolean JNICALL jni_freerdp_send_clipboard_data(JNIEnv* env, jclass cls, jlong instance,
                                                        jstring jdata)
{
...
WLog_DBG(TAG, "send_clipboard_data: (%s)", data);
...
}
```
The output log of logcat is: **send_clipboard_data: (Hello World)**. But in fact, a character is missing when pasting on the remote host .

**Comment by akallabeth** [comment]
@xiaoyvyv fixed the missing '\0' termination. but where did you get a kotlin android client from?
