### ISSUE TITLE
Session frozen when you lose network for a few seconds (Unrecoverable)

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#7168]
**freerdp version** 2.3.2

I have used parameters such as **+auto-reconnect** and **/timeout** without result, the session is frozen.

**Use case:** Unplug the network wire for 15-20 seconds and plug it in again.

The log when the session has frozen but you already have a network connection:

![image](https://user-images.githubusercontent.com/25820234/125269174-be7c6900-e308-11eb-922b-3d0daafc04b7.png)

**Comment by akallabeth** [comment]
@FutureKidBuu 
1. does it recover after a few seconds?
2. The screenshot of the log is not very helpful ;)

**Comment by FutureKidBuu** [comment]
@akallabeth No, the current session is no longer recoverable, I have to close the window and relaunch freerdp.

**Comment by FutureKidBuu** [comment]
@akallabeth log, It can be hell ;) (due to xf_lock_x11_ methods
xf_unlock_x11_)
[trace_freerdp.log](https://github.com/FreeRDP/FreeRDP/files/6800509/trace_freerdp.log)

**Comment by akallabeth** [comment]
@FutureKidBuu ok, the log is missing quite a lot of stuff (and your compile did ignore lots of compile warnings about excessive/dangerous logging)

**Comment by akallabeth** [comment]
I´d try a `xfreerdp <yourargs> 2>&1 |tee log.txt` to get a consistent log with errors and warnings

**Comment by 2fly2** [comment]
client_auto_reconnect_ex 2nd prameter is NULL,  add windows message loop in window_events can fix it.

**Comment by akallabeth** [comment]
@2fly2 which version and client do you use?

**Comment by 2fly2** [comment]
@akallabeth  freerdp version 3.0.0-dev,  freerdp git version c1084c7, branch master.  on windows.   but is the same as linux.
for(x=0; x < 50; x++)
{
    if(!ICALLRESULT(TRUE, window_event,  instance))
        return FALSE;
    Sleep(100);
}

window_event will not run because it is NULL.

**Comment by akallabeth** [comment]
@2fly2 `xfreerdp` and `wlfreerdp` will call `handle_window_events` (wayland is just a stub though)
the windows client uses the version without callback though, there it might happen that the window is not updated until the session is reconnected

**Comment by 2fly2** [comment]
> @2fly2 `xfreerdp` and `wlfreerdp` will call `handle_window_events` (wayland is just a stub though) the windows client uses the version without callback though, there it might happen that the window is not updated until the session is reconnected

yes, you are right.   'xfreerdp' can reconnect normally, 'wfreerdp'  the window is not updated until the session is reconnected
