### ISSUE TITLE
floatbar button don't response on armhf platform terminal

### ISSUE THREAD

**Issue by xinjiezhu** [FreeRDP/FreeRDP#7170]
Freerdp version: 2.0.0-dev5
terminal platform : armhf

I use command as follows:
xfreerdp /v:xxx /u:xxx /p:xxx /f /cert-ignore /floatbar:default:visiable

Float bar is display, but when I clicked minimize button and close button ,  it is not response. What's wrong?

It is normal on X86 platform terminal , What's the difference?

**Comment by akallabeth** [comment]
update please ;)
`2.3.2` is current release, `2.0.0-dev5` at least several years behind.

**Comment by xinjiezhu** [comment]
You are right.
2.3.2 release have solved this question, thanks!
