### ISSUE TITLE
release 2.3.2 Multimedia Redirection(command line /video) do not work

### ISSUE THREAD

**Issue by xinjiezhu** [FreeRDP/FreeRDP#7171]
Releated pull request for master: release 2.3.2

I find new command line "/video" for Multimedia Redirection , but it does not work. What's wrong?
My command line as follows:
xfreerdp /v:xxx /u:xxx /p:xxx /f /cert-ignore /video

Before I update version to release 2.3.2, I use 2.0.0-dev5.
I use command line /multimedia:sys:alsa , it works fine.
My command line as follows:
xfreerdp /v:xxx /u:xxx /p:xxx /f /cert-ignore  /multimedia:sys:alsa

What's the difference?

**Comment by akallabeth** [comment]
`/video` implements https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpevor/a9947d55-9408-4cf8-b113-555b436bd3ce wheras `/multimedia` implements https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpev/ff2a9f63-cbcc-4615-849f-03752a2b440b

you need server support for this, so if `/video` does not work it might be disabled (note: only h264 redirection is currently implemented)
If you require `/multimedia` it is still there, but currently not maintained.
