### ISSUE TITLE
Screen dimension with 1366x786 not working

### ISSUE THREAD

**Issue by anilgmaipady** [FreeRDP/FreeRDP#7195]
When FreeRDP is launched with dimension 1366x768 using command 

wfreerdp.exe /v:127.0.0.1 /u:user3 /p:Test123# /size:1366x768 /cert:ignore /log-level:TRACE 
Then get the session id using "query session" 
Then capture - PsExec.exe -s -i  nircmd savescreenshot C:\Windows\Temp\sc.png the dimension of sc.png is 1368x768 not 1366x786 

If I use mstc.exe and launch with 1366x768 the screenshot will have dimension 1366x786 

This looks like a bug in FreeRDP.

This is FreeRDP version 2.3.2 (2.3.2)

* Output of `xfreerdp /buildconfig`*
This is FreeRDP version 2.3.2 (2.3.2)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_EXECINFO_H= HAVE_FCNTL_H=1 HAVE_INTTYPES_H=1 HAVE_SYSLOG_H= HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H= HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_TM_GMTOFF= HAVE_UNISTD_H= WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_FAAC=OFF WITH_FAAD2=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=ON WITH_NATIVE_SSPI=ON WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_WIN8=OFF WITH_WINMM=ON WITH_WINPR_TOOLS=OFF WITH_X264=OFF
Build type:          Release
CFLAGS:              /DWIN32 /D_WINDOWS  /Gd /W3
Compiler:            MSVC, 18.0.40629.0
Target architecture: x86

**Environment (please complete the following information):**
 - OS: Windows 10

**Comment by akallabeth** [comment]
yes, for simplicity of protocol requirement enforcement we limit resolutions to multiples of 4.
It could be adjusted, but requires some work & testing for each graphics mode and server out there

**Comment by akallabeth** [comment]
Duplicates #4656

**Comment by GeniusbutLazy** [comment]
is this fixed ?

**Comment by GeniusbutLazy** [comment]
Ok fixed the issue just had the comment the following line ( FreeRDP\Client\Windows\wf_client.c)
desktopWidth = (desktopWidth+3) & (`3);

**Comment by GeniusbutLazy** [comment]
> yes, for simplicity of protocol requirement enforcement we limit resolutions to multiples of 4. It could be adjusted, but requires some work & testing for each graphics mode and server out there

Thanks for above answer , 
I Fixed the issue just had the comment the following line ( FreeRDP\Client\Windows\wf_client.c)
desktopWidth = (desktopWidth+3) & (`3);
