### ISSUE TITLE
Wiki vandalism

### ISSUE THREAD

**Issue by ryannathans** [FreeRDP/FreeRDP#7203]
Wiki footer 

![image](https://user-images.githubusercontent.com/1307375/127575426-aa9d6413-2620-4210-81e3-58a57f82cd42.png)

**Comment by akallabeth** [comment]
@ryannathans thank you for reporting that.
@gpsukgov @derekcorwin @TheJoaqun please grow up, yes it is possible to edit a public wiki, who would have guessed.
