### ISSUE TITLE
Why is the /scale parameter limited to 140 and 180 ?

### ISSUE THREAD

**Issue by bubbleguuum** [FreeRDP/FreeRDP#7204]
I wished I could use /scale:200 on my 4K monitor. 180 is sort of fine, but I wonder why technically /scale is limited to 140 and 180.
IIRC man of old versions mention 200 and 300 as possible values.

**Comment by akallabeth** [comment]
you have to ask microsoft for that ;)
they only support that in RDP

**Comment by bubbleguuum** [comment]
Investigating a bit, I got the result I desired using `/scale-desktop:200 /scale-device:180`, for what looks like 200% scaling to me.
Both options need to be passed for anything to happen, which is confirmed by the last 2 paragraph of this spec:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/00f1da4a-ee9c-421a-852f-c19f92343d73?redirectedfrom=MSDN

**Comment by akallabeth** [comment]
@bubbleguuum it is a bit of a mystery to me too, but these are the settings windows supports. (e.g. server side scaling of contents)
There is also `/smart-sizing` which scales client side
