### ISSUE TITLE
How to solve this Error??

### ISSUE THREAD

**Issue by PiyushVerma545** [FreeRDP/FreeRDP#7225]
C:\Users\ASUS\FreeRDPtest\FreeRDP> cmake -G"Visual Studio 16 2019" -DMONOLITHIC_BUILD=ON -DMSVC_RUNTIME=static -DWITH_SSE2=ON -DWITH_SERVER=ON -DOPENSSL_ROOT_DIR="C:\Program Files\OpenSSL-Win64" -DLIBUSB_1_INCLUDE_DIR="C:\Users\ASUS\FreeRDPtest\libusb-win32-bin-1.2.6.0\include"
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.28.29914.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at cmake/ClangFormat.cmake:14 (message):
  clang-format not found in path! code format target not available.
Call Stack (most recent call first):
  CMakeLists.txt:55 (include)

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
FREERDP_VERSION=3.0.0-dev
-- Git Revision 67f3fff2c
-- MSVC: using statically-linked runtime (/MT and /MTd).
-- Skipping disabled feature X11 for X11 (X11 client and server)
-- Skipping disabled feature Wayland for Wayland (Wayland client)
-- Skipping optional feature ZLIB for compression (data compression)
--     Enable feature ZLIB using "-DWITH_ZLIB=ON"
-- Finding required feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Skipping disabled feature OpenSLES for multimedia (OpenSLES audio / video)
-- Skipping disabled feature OSS for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature ALSA for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Pulse for sound (audio input, audio output and multimedia redirection)
-- Skipping disabled feature Cups for printing (printer device redirection)
-- Skipping disabled feature PCSC for smart card (smart card device redirection)
-- Skipping optional feature FFmpeg for multimedia (multimedia redirection, audio and video playback)
--     Enable feature FFmpeg using "-DWITH_FFMPEG=ON"
-- Skipping optional feature JPEG for codec (use JPEG library)
--     Enable feature JPEG using "-DWITH_JPEG=ON"
-- Skipping optional feature x264 for codec (use x264 library)
--     Enable feature x264 using "-DWITH_X264=ON"
-- Skipping optional feature OpenH264 for codec (use OpenH264 library)
--     Enable feature OpenH264 using "-DWITH_OPENH264=ON"
-- Skipping optional feature OpenCL for codec (use OpenCL library)
--     Enable feature OpenCL using "-DWITH_OPENCL=ON"
-- Skipping optional feature GSM for codec (GSM audio codec library)
--     Enable feature GSM using "-DWITH_GSM=ON"
-- Skipping optional feature LAME for codec (lame MP3 audio codec library)
--     Enable feature LAME using "-DWITH_LAME=ON"
-- Skipping optional feature FAAD2 for codec (FAAD2 AAC audio codec library)
--     Enable feature FAAD2 using "-DWITH_FAAD2=ON"
-- Skipping optional feature FAAC for codec (FAAC AAC audio codec library)
--     Enable feature FAAC using "-DWITH_FAAC=ON"
-- Skipping optional feature soxr for codec (SOX audio resample library)
--     Enable feature soxr using "-DWITH_SOXR=ON"
-- Skipping optional feature GSSAPI for auth (add kerberos support)
--     Enable feature GSSAPI using "-DWITH_GSSAPI=ON"
-- Skipping optional feature IPP for performance (Intel Integrated Performance Primitives library)
--     Enable feature IPP using "-DWITH_IPP=ON"
-- Using OpenSSL Version: 1.1.1k
using default plugins location
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Finding recommended feature OpenSSL for cryptography (encryption, certificate validation, hashing functions)
--     Disable feature OpenSSL using "-DWITH_OPENSSL=OFF"
-- Skipping optional feature MbedTLS for cryptography (encryption, certificate validation, hashing functions)
--     Enable feature MbedTLS using "-DWITH_MBEDTLS=ON"
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
-- Could NOT find Cairo (missing: CAIRO_LIBRARIES CAIRO_INCLUDE_DIR)
CMake Warning at libfreerdp/CMakeLists.txt:102 (message):
  -DWITH_SWSCALE=OFF and -DWITH_CAIRO=OFF, compiling without image scaling
  support!

CMake Warning at libfreerdp/CMakeLists.txt:119 (message):
  Compiling without WITH_DSP_FFMPEG and WITH_FAAC, AAC encoder support
  disabled

-- Adding STATIC channel client server "drdynvc": Dynamic Virtual Channel Extension
-- Adding DYNAMIC channel client "video": Video optimized remoting Virtual Channel Extension
-- Adding DYNAMIC channel client "urbdrc": USB Devices Virtual Channel Extension
-- Adding DEVICE channel client "smartcard": Smart Card Virtual Channel Extension
-- Adding STATIC channel client server "remdesk": Remote Assistance Virtual Channel Extension
-- Adding STATIC channel client server "rdpsnd": Audio Output Virtual Channel Extension
-- Adding DYNAMIC channel client "rdpgfx": Graphics Pipeline Extension
-- Adding DYNAMIC channel client "rdpei": Input Virtual Channel Extension
-- Adding STATIC channel client server "rdpdr": Device Redirection Virtual Channel Extension
-- Adding STATIC channel client "rdp2tcp": Tunneling TCP over RDP
-- Adding STATIC channel client "rail": Remote Programs Virtual Channel Extension
-- Adding DEVICE channel client "printer": Print Virtual Channel Extension
-- Adding DYNAMIC channel client "geometry": Geometry tracking Virtual Channel Extension
-- Adding STATIC channel client server "encomsp": Multiparty Virtual Channel Extension
-- Adding DYNAMIC channel client server "echo": Echo Virtual Channel Extension
-- Adding DEVICE channel client "drive": Drive Redirection Virtual Channel Extension
-- Adding DYNAMIC channel client "disp": Display Update Virtual Channel Extension
-- Adding STATIC channel client server "cliprdr": Clipboard Virtual Channel Extension
-- Adding DYNAMIC channel client server "audin": Audio Input Redirection Virtual Channel Extension
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBUSB_1_LIBRARY
    linked by target "urbdrc-client-libusb" in directory C:/Users/ASUS/FreeRDPtest/FreeRDP/channels/urbdrc/client/libusb

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by bmiklautz** [comment]
@PiyushVerma545 the quick fix is to disable the usb channel with `-DCHANNEL_URBDRC=OFF` if you require usb channel you want to set `-DLIBUSB_1_LIBRARY=`, pointing to the directory where the libusb library resides in, along with  -DLIBUSB_1_INCLUDE_DIR="C:\Users\ASUS\FreeRDPtest\libusb-win32-bin-1.2.6.0\include"

**Comment by bmiklautz** [comment]
Similar issue #6940
