### ISSUE TITLE
Printer Redirection support network printer?

### ISSUE THREAD

**Issue by hxf3751** [FreeRDP/FreeRDP#7228]
Hi,

There's a printer in my computer, it's a network printer, I want to redirect the printer on remote computer. I typed the command as follow:
xfreerdp /v:ip /u:username /p:password /printer:"CUPS-BRF-Printer(Redirection)","CUPS-BRF-Printer".
but, it didn't work, is my command wrong? Or FreeRDP hasn't supported the network printer redirection?
Thanks!

**Comment by akallabeth** [comment]
From `xfreerdp` help: `/printer[:<name>[,<driver>]]      Redirect printer device`
I think you misinterpret the meaning of the fields, just omit the whole arguments and just use `/printer` for a start to redirect all local printers.
To redirect a specific one use `/printer:<name in cups>` and to use a specific `windows` driver use `/printer:<name in cups>,<windows driver name>`. The driver has to be one outputting a format cups can understand though, this is not a direct hardware redirection.
