### ISSUE TITLE
"Could not connect to RDP backend."

### ISSUE THREAD

**Issue by hoangdung245** [FreeRDP/FreeRDP#7229]
Hello,
I've installed the FreeRDP app on macOS and access from winOS to macOS but cannot connect.
On Mac, I've installed Xcode, MacPorts, and then installed FreeRDP (all of this was built in Terminal).
Could you please help solve this problem?
Many thanks,

**Comment by bmiklautz** [comment]
@hoangdung245 the information you provide is not sufficient to help. Please have a look to https://github.com/FreeRDP/FreeRDP/wiki/BugReporting and update your report.

**Comment by akallabeth** [comment]
Closing until there is sufficient information to work with.
