### ISSUE TITLE
When I use the service I see more traffic than Microsoft

### ISSUE THREAD

**Issue by Cc28256** [FreeRDP/FreeRDP#7234]
**Is your feature request related to a problem? Please describe.**
FreeRDP Server transfer data size is larger than Microsoft，It looks like an interlaced scan，
Is this the only algorithm？or Is there a faster way I haven't found?

**Describe the solution you'd like**
Get a look at how Microsoft implements it?

I look forward to your reply. Thank you

**Comment by Cc28256** [comment]
FreeRDP server, The screen picture data is very large,2mb / S.  But Microsoft 3389 only has 500kb/s

**Comment by Cc28256** [comment]
In the freeRDP service, I found that as soon as the left side of the screen changed a little bit, the whole line was sent

**Comment by Cc28256** [comment]
And there are changes on the far right side of the screen, and the data transmitted will be smaller

**Comment by akallabeth** [comment]
Mostly configuration and os dependent.
Note that the server parts in FreeRDP are meant as `demo`, e.g. they are only showing what the library can do.
For an optimized RDP server for linux/unix see https://github.com/ogon-project/ogon (based on freerdp)

**Comment by Cc28256** [comment]
好的，谢谢
