### ISSUE TITLE
"Could not connect to RDP backend."

### ISSUE THREAD

**Issue by hoangdung245** [FreeRDP/FreeRDP#7236]
I have an issue when trying to connect from WinOS to MacOS by FreeRDP:
- On Win 10, I've installed Cloudbase Solutions.
- On Mac Catalina, I've installed Xcode, MacPorts, and FreeRDP.
When I access from Win to Mac, it shows the notice "Could not connect to RDP backed."

![Screen Shot 2021-08-23 at 20 57 48](https://user-images.githubusercontent.com/69205882/130460079-3b24e9bf-338e-47ce-b130-ecc4732b3ece.png)

Could you help me to solve this problem?
Thank you,

**Comment by akallabeth** [comment]
just a guess, but does a RDP server run on your mac?
FreeRDP is client only on mac, so I doubt that.

**Comment by akallabeth** [comment]
No,
what you try is not going to work.
You need a rdp client to connect to a rdp server.
Windows has one built in, mac does not.

Freerdp is client only on mac.

Am 23. August 2021 13:58:54 UTC schrieb "Dung Truong" ***@***.***>:

**Comment by hoangdung245** [comment]
> No, what you try is not going to work. You need a rdp client to connect to a rdp server. Windows has one built in, mac does not. Freerdp is client only on mac. Am 23. August 2021 13:58:54 UTC schrieb "Dung Truong" ***@***.***>:
> […](#)
> I have an issue when trying to connect from WinOS to MacOS by FreeRDP: - On Win, I've installed Cloudbase Solutions. - On Mac, I've installed Xcode, MacPorts, and FreeRDP. When I access from Win to Mac, it shows the notice "Could not connect to RDP backed." ![Screen Shot 2021-08-23 at 20 57 48](https://user-images.githubusercontent.com/69205882/130460079-3b24e9bf-338e-47ce-b130-ecc4732b3ece.png) Could you help me to solve this problem? Thank you, -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #7236

You mean, I just can connect from Mac to Win, but can't connect from Win to Mac right?
