### ISSUE TITLE
Undefined symbol: cliprdr_serialize_file_list_ex

### ISSUE THREAD

**Issue by supernoi** [FreeRDP/FreeRDP#7237]
Releated pull request for master: 
Hello,

I installed freerdp from the Pop_Os repository, but it didn't work. I'm researching the error, but so far, I haven't found anything.
Has anyone had a similar error?

> noi@noilaptop:~$ xfreerdp 
xfreerdp: symbol lookup error: xfreerdp: undefined symbol: cliprdr_serialize_file_list_ex

>noi@noilaptop:~$ sudo apt policy freerdp2-x11 
freerdp2-x11:
  Installed: 2.3.0+dfsg1-1
  Candidate: 2.3.0+dfsg1-1
  Version table:
 *** 2.3.0+dfsg1-1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
        100 /var/lib/dpkg/status

>noi@noilaptop:~$ neofetch 
             /////////////                noi@noilaptop 
         /////////////////////            ------------- 
      ///////*767////////////////         OS: Pop!_OS 21.04 x86_64 
    //////7676767676*//////////////       Host: 20RA0016IX ThinkPad E14 
   /////76767//7676767//////////////      Kernel: 5.13.12-051312-generic 
  /////767676///*76767///////////////     Uptime: 19 mins 
 ///////767676///76767.///7676*///////    Packages: 3190 (dpkg), 34 (flatpak), 5 (snap) 
/////////767676//76767///767676////////   Shell: bash 5.1.4 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 3.38.4 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Pop 
///////////////7676////////////////////   Theme: Dracula [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: tilix 
   //////.7676767676767676767,//////      CPU: Intel i5-10210U (8) @ 4.200GHz 
    /////767676767676767676767/////       GPU: Intel CometLake-U GT2 [UHD Graphics] 
      ///////////////////////////         Memory: 4229MiB / 15682MiB 
         /////////////////////
             /////////////

**Comment by supernoi** [comment]
I installed a previous version (freerdp2-x11_2.2.0).
And it worked...

**Comment by akallabeth** [comment]
buildconfig?

**Comment by supernoi** [comment]
It only worked with version 2.2.0, version 2.3.0 returned an error.

>noi@noilaptop:~$ xfreerdp /buildconfig
This is FreeRDP version 2.2.0 (270e40e92)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=on WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=on WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Debug
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 10.2.0
Target architecture: x64

>noi@noilaptop:~$ sudo apt upgrade -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  freerdp2-x11
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/91,7 kB of archives.
After this operation, 5.120 B of additional disk space will be used.
(Reading database ... 503561 files and directories currently installed.)
Preparing to unpack .../freerdp2-x11_2.3.0+dfsg1-1_amd64.deb ...
Unpacking freerdp2-x11 (2.3.0+dfsg1-1) over (2.2.0+dfsg1-1) ...
Setting up freerdp2-x11 (2.3.0+dfsg1-1) ...
Processing triggers for man-db (2.9.4-2) ...

>noi@noilaptop:~$ xfreerdp /buildconfig
xfreerdp: symbol lookup error: xfreerdp: undefined symbol: cliprdr_serialize_file_list_ex

**Comment by akallabeth** [comment]
ok, then please post the `debian/rules` of your source package. it looks like there is something broken there.

**Comment by akallabeth** [comment]
ok, checked a fresh compile from tag 2.3.0 and 2.3.2.
`000000000005e9a0 g    DF .text	000000000000033b  Base        cliprdr_serialize_file_list_ex` is part of `libfreerdp-client2.so`
and `xfreerdp` links `NEEDED               libfreerdp-client2.so.2`
so this is most likely a packaging error of the ubuntu folks.
