### ISSUE TITLE
Backport urbdrc data write fix to stable-2.0

### ISSUE THREAD

**Issue by marchaefner** [FreeRDP/FreeRDP#7258]
We (openthinclient) have packed and published 2.3.2 and now 2.4.0 with #7094 with a simple
```
git cherry-pick 34413d948064b75c65cedb2f874d62caf0c1e941
```
before compiling.
This has been in the wild for over a month and is being used by hundreds of users (last time i checked the stats) without any complaints. We also see no side-effects in our internal tests.

I think it would be nice for non-openthinclient users to also have this fix available (since this works for all kinds of USB devices, not just Kuando Busylight).

(I did not create a pull request as this seems too trivial, but am willing to do so if this works better for you.)

**Comment by akallabeth** [comment]
@marchaefner would still be great if you could create it.

**Comment by marchaefner** [comment]
PR: #7261
