### ISSUE TITLE
Tooltip animation in remoteapp mode disconnects xfreerdp

### ISSUE THREAD

**Issue by vice** [FreeRDP/FreeRDP#7265]
**Description**
An application with animated tooltips crashes xfreerdp viewer in remoteapp mode. No issue in full desktop mode.

**To Reproduce**
1. Get a Windows Server 2008R2.
2. Enable tooltips visual effects either explicitly or by enabling _Adjust for best performance_.
![Tooltips Visual Effects enabled](https://user-images.githubusercontent.com/738830/131807337-a54c69ff-4ee9-458c-acf2-c2a803476c14.png)
(screenshot from a different Windows version)
3. Copy executable inside [tooltest.zip](https://github.com/FreeRDP/FreeRDP/files/7097074/tooltest.zip) to the Windows Server.
4. Configure this executable as a remote application.
5. Connect using xfreerdp and selecting `/network:lan` to warrant that all visual effects are transmitted.
6. Just play around with the application tooltbar that just shows tooltips in buttons. Tooltip animation could be seeing by entering slowly into the toolbar. Normally in just a few seconds, xfreerdp crashes.

**Expected behavior**
Maybe some visual glitch could be expected but not a forced exit.

**Application details**
* FreeRDP versions `This is FreeRDP version 2.3.0 (2.3.0)` and `This is FreeRDP version 3.0.0-dev (e80c98ebf)` from master
* Command line: `echo "password" | xfreerdp /u:"administrador" /app:"||tooltest" /title:"test" /cert-ignore /from-stdin /v:localhost:3389 /network:lan`
* Output of `xfreerdp /buildconfig`:
This is FreeRDP version 2.3.0 (2.3.0)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=ON WITH_DEBUG_CAPABILITIES=ON WITH_DEBUG_CERTIFICATE=ON WITH_DEBUG_CHANNELS=ON WITH_DEBUG_CLIPRDR=ON WITH_DEBUG_DVC=ON WITH_DEBUG_KBD=ON WITH_DEBUG_LICENSE=ON WITH_DEBUG_MUTEX=ON WITH_DEBUG_NEGO=ON WITH_DEBUG_NLA=ON WITH_DEBUG_NTLM=ON WITH_DEBUG_RAIL=ON WITH_DEBUG_RDP=ON WITH_DEBUG_RDPDR=ON WITH_DEBUG_RDPEI=ON WITH_DEBUG_RDPGFX=ON WITH_DEBUG_REDIR=ON WITH_DEBUG_RFX=ON WITH_DEBUG_RINGBUFFER=ON WITH_DEBUG_SCARD=ON WITH_DEBUG_SND=ON WITH_DEBUG_SVC=ON WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=ON WITH_DEBUG_TIMEZONE=ON WITH_DEBUG_TRANSPORT=ON WITH_DEBUG_TSG=ON WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=ON WITH_DEBUG_X11=ON WITH_DEBUG_X11_CLIPRDR=ON WITH_DEBUG_X11_LOCAL_MOVESIZE=ON WITH_DEBUG_XV=ON WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 10.2.1
Target architecture: x64

This is FreeRDP version 3.0.0-dev (e80c98ebf)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_BIG_ENDIAN=TRUE HAVE_CMAKE_SIZEOF_UNSIGNED_SHORT=TRUE HAVE_EVENTFD_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_LIMITS_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_NETDB_H=1 HAVE_PIXMAN_REGION=OFF HAVE_POLL_H=1 HAVE_PTHREAD_GNU_EXT=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_STDBOOL_H=1 HAVE_STDDEF_H=1 HAVE_STDINT_H=1 HAVE_STRNDUP=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_PARAM_H=1 HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKET_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_SYS_TYPES_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUNIT=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_GDI=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_ORDERS=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_FREERDP_DEPRECATED=OFF WITH_FUSE=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_NPP=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=OFF WITH_PULSEAUDIO=OFF WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SSE2_TARGET=OFF WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=ON WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=OFF WITH_ZLIB=ON
Build type:          Debug
CFLAGS:               -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer
Compiler:            GNU, 8.3.0
Target architecture: x64

* OS version connecting to (server side): Windows Server 2008R2
* The log output from two runs with `/log-level:trace 2>&1 | tee log.txt`:  [xfreerdp.logs.zip](https://github.com/FreeRDP/FreeRDP/files/7097669/xfreerdp.logs.zip)

**Environment (please complete the following information):**
 - OS: GNU/Linux
 - Version/Distribution: Ubuntu 21.04 and Debian 10 buster
 - Architecture: amd66

**Additional context**
Trying a legacy application running in a Windows Server 2008R2 environment connecting as a remoteapp, xfreerdp breaks and exits constantly, normally when showing a lot of animated tooltips. We compiled a simple test program and reproduced the problem in our own Windows Server 2008R2. [tooltest.zip](https://github.com/FreeRDP/FreeRDP/files/7097074/tooltest.zip). It was made in Visual Basic 6, because this is the original language used in the legacy application but we think that any animated tooltip could produce the bug. And maybe any other animation that updates the same screen zone constantly.

This is a very specific use case but may uncover a more general hard to find bug in code.

We also tried a Windows Server 2019 but even with all visual effects activated the tooltip animation is never shown in remoteapp mode. However in full desktop mode tooltip animation is rendered correctly.

**Comment by vice** [comment]
We think the relevant part from the log is:
```
[11:10:55:062] [13661:13663] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[11:10:55:062] [13661:13663] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x131174 visibilityRects=((0,0,929,70)(0,70,566,87)(602,70,929,87)(0,87,929,555))
[11:10:55:062] [13661:13663] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [1] from xf_UpdateWindowArea
[11:10:55:068] [13661:13663] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:    [0] from xf_UpdateWindowArea
[11:10:55:068] [13661:13663] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x0b] Windowing
[11:10:55:068] [13661:13663] [DEBUG][com.freerdp.core.update] - WindowUpdate windowId=0x196692 windowRects=() visibilityRects=[11:10:55:069] [13661:13663] [ERROR][com.freerdp.core.update] - [0x00] Switch Surface - SERVER BUG: The support for this feature was not announced! Use /relax-order-checks to ignore
[11:10:55:069] [13661:13663] [WARN][com.freerdp.core.update] - Adding +offscreen-cache might mitigate
[11:10:55:069] [13661:13663] [ERROR][com.freerdp.core.update] - order flags 00 failed
[11:10:55:069] [13661:13663] [ERROR][com.freerdp.core.fastpath] - Fastpath update Orders [0] failed, status 0
[11:10:55:069] [13661:13663] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update() - -1
[11:10:55:069] [13661:13663] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[11:10:55:069] [13661:13663] [WARN][com.freerdp.client.x11] - xf_lock_x11_:    [1] recursive lock from xf_UpdateWindowArea
[11:10:55:069] [13661:13663] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
[11:10:55:069] [13661:13663] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
[11:10:55:070] [13661:13663] [ERROR][com.freerdp.client.x11] - Failed to check FreeRDP file descriptor
()
[11:10:55:069] [13661:13663] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [1] from xf_UpdateWindowArea
[11:10:55:069] [13661:13663] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:    [0] from xf_UpdateWindowArea
[11:10:55:069] [13661:13663] [DEBUG][com.freerdp.core.update] - Primary Drawing Order [0x0a] OpaqueRect
[11:10:55:069] [13661:13663] [DEBUG][com.freerdp.core.update] - Primary Drawing Order [0x0a] OpaqueRect
[11:10:55:069] [13661:13663] [DEBUG][com.freerdp.core.update] - Alternate Secondary Drawing Order [0x00] Switch Surface
[11:10:55:069] [13661:13663] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [1] from xf_sw_end_paint
[11:10:55:069] [13661:13663] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [2] from xf_UpdateWindowArea
[11:10:55:069] [13661:13663] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:    [1] from xf_UpdateWindowArea
[11:10:55:069] [13661:13663] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:    [0] from xf_sw_end_paint
[11:10:55:069] [13661:13663] [DEBUG][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_ACTIVE - rdp_recv_pdu() - -3
[11:10:55:069] [13661:13663] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
[11:10:55:069] [13661:13663] [DEBUG][com.freerdp.core] - rdp_check_fds() - -1
[11:10:55:070] [13661:13663] [INFO][com.freerdp.client.common] - Network disconnect!
``` 
and `order flags 00 failed`.

Testing with `+offscreen-cache` make no difference. Same problems.

**Comment by akallabeth** [comment]
```
[ERROR][com.freerdp.core.update] - [0x00] Switch Surface - SERVER BUG: The support for this feature was not announced! Use /relax-order-checks to ignore
[11:10:55:069] [13661:13663] [WARN][com.freerdp.core.update] - Adding +offscreen-cache might mitigate
```
just always connect with `/network:auto` to avoid this.

**Comment by FutureKidBuu** [comment]
> ```
> [ERROR][com.freerdp.core.update] - [0x00] Switch Surface - SERVER BUG: The support for this feature was not announced! Use /relax-order-checks to ignore
> [11:10:55:069] [13661:13663] [WARN][com.freerdp.core.update] - Adding +offscreen-cache might mitigate
> ```
> 
> just always connect with `/network:auto` to avoid this.

It's very similar to my issue https://github.com/FreeRDP/FreeRDP/issues/6302

I test these app [https://github.com/FreeRDP/FreeRDP/files/7097074/tooltest.zip](url) and the same thing happens to me, the connection is broken just by looking at that kind of tooltips it seems. I think freerdp should avoid this situation.

**Comment by akallabeth** [comment]
@FutureKidBuu no, we are not going to hack because there are bugs with certain server configurations (server bugs that is ;))

**Comment by vice** [comment]
> just always connect with `/network:auto` to avoid this.

Sadly, connecting with `/network:auto` we have the same issue. See attached [xfreerdp.network.auto.log.zip](https://github.com/FreeRDP/FreeRDP/files/7147611/xfreerdp.network.auto.log.zip). We will try to decrease connection quality (or disable effects clients side) until it no longer fails. I will let you know  if its works. Thanks @akallabeth for the hard work and managing issues.
