### ISSUE TITLE
Choosing a monitor does not work

### ISSUE THREAD

**Issue by marlemion** [FreeRDP/FreeRDP#7266]
I am running xfreerdp 2.3.0 on Dedbian Bullseye since a few months without any problem connecting to a Windows 10 machine. The setup uses two monitors on the local side. So far I had three options working:

a) Fullscreen using both monitors via /f /multimon
b) Fullscreen using one monitor via /f
c) Window mode (no flag)

Now I would like to to choose the one specific monitor and display fullscreen on it.
```

xfreerdp /monitor-list

      * [0] 1920x1080	+0+0
        [1] 1920x1080	+1920+0
```

Perfect, so I added: /f /multimon /monitors:0 and fired xfreerdp up - works.

**BUT:** /f /multimon /monitors:**1** lets xfreerdp display on the **same** screen. Hence, I cannot choose the monitor using the numbers 0 or 1.

Maybe a problem with the WM? I am running lightdm with MATE.

**Comment by akallabeth** [comment]
@marlemion I´ve just tried on my `debian bullseye` with `gnome` and `mate` and it is working here.

```
 xfreerdp /monitor-list
      * [0] 3072x1728	+3072+0
        [1] 3072x1728	+0+0
```

Also tried on my office machine (same layout as you) and also working there.
