### ISSUE TITLE
Display issues with Manjaro KDE Plasma Raspberry Pi 4

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#7273]
Installed FreeRDP server via this command: pacman -S --noconfirm freerdp

Using Manjaro KDE Plasma ARM aarch64
Kernel 5.10.60-2-MANJARO-ARM

When using the Microsoft RDP Client for Android, I can get connected successfully, but the display is not right. I have attached an image.
![Screenshot_20210908-193419_Microsoft Remote Desktop](https://user-images.githubusercontent.com/80567988/132491087-bdfb126d-1dc3-42ba-bcc4-00f8a6944ccc.jpg)

Couldn't find anything online for a similar issue, so help would be appreciated :)

**Comment by akallabeth** [comment]
could you please add what you are using? `FreeRDP` is a colletion of various RDP related tools (clients, servers, ...)

**Comment by cheapaschimps** [comment]
> could you please add what you are using? `FreeRDP` is a colletion of various RDP related tools (clients, servers, ...)

Updated, but I'm using FreeRDP server

**Comment by akallabeth** [comment]
@cheapaschimps and which one? how do you configure it? please be a bit more verbose, otherwise we can not help.

**Comment by cheapaschimps** [comment]
> @cheapaschimps and which one? how do you configure it? please be a bit more verbose, otherwise we can not help.

I don't understand which one. I installed via terminal:
pacman -S --noconfirm freerdp
And to launch the server:
freerdp-shadow-cli
That's all I did to configure it on the host.

**Comment by akallabeth** [comment]
ok, so you use `shadow` server. do you connect with the correct resolution?
