### ISSUE TITLE
Unable to swap WIN and CAPS

### ISSUE THREAD

**Issue by sprnza** [FreeRDP/FreeRDP#7277]
**Describe the bug**
Unable to swap WIN-CAPS keys

**To Reproduce**
1. start `xfreerdp /size:1920x1060 /u:Administrator /p:Headp01nt /v:10.178.3.44 /kbd-remap:0x3a=0xe05b,0xe05b=0x3a`
2. No remaping performed

**Expected behavior**
Pressing CAPS send WIN key event to the remote host and vice versa.

**Application details**
* xfreerdp: 2.4.0
* Output of `xfreerdp /buildconfig`:
```
sdg-dell ➜  ~ xfreerdp /buildconfig
This is FreeRDP version 2.4.0 (bad6697)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF
WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON
WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls
-g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 11.1.0
Target architecture: x64
```
* Windows Server 2019
* Log output attached

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Architecture: amd64
[log.txt](https://github.com/FreeRDP/FreeRDP/files/7134269/log.txt)

**Comment by akallabeth** [comment]
Not part of `2.4.0` release, currently only available on master.

**Comment by sprnza** [comment]
Okay, now I run
```
FreeRDP version 3.0.0-dev (ba0da0421)
```
The issue is still there. What could be wrong? Scancode is correct I've checked with `showkey --scancodes`

**Comment by antenore** [comment]
@akallabeth I confirm this behavior in master, swapping other 'normal keys' (like z and y) works, but not with OEM keys (is it the right name??).

BTW are there any chance it will back-ported to stable?

**Comment by akallabeth** [comment]
@antenore thank you for the hint.
As for backports, If interest is there please create a backport pull request with `git cherry-pick -x` of the commits.
I´m mostly working on getting `master` in shape, we have a lot of stuff to fix there :/

**Comment by antenore** [comment]
@akallabeth it was already cherry-picked by Armin

```
commit 1c590a71e7c3cc2055d58c4da71c06adcbe85708
Author: Armin Novak <armin.novak@thincast.com>
Date:   Wed Oct 28 12:22:48 2020 +0100

    Added option to remap scancodes

    (cherry picked from commit d7bf6553c558db64e5e3108b08f8ee1d394d1393)

```

So it's in stable since tag: 2.3.0

**Comment by akallabeth** [comment]
@antenore thank you, seems like I mixed up something in my last response.

**Comment by akallabeth** [comment]
@antenore ok, just tried `/kbd-remap:0x1=0xf,0xf=0x1,0x1d=0x38,0x38=0x1d` which remaps `ctrl ->alt` and `alt -> ctrl` as well as `tab -> esc` and `esc -> tab` that seems to work with 2.3.0 from debian.
So, maybe this is not the most easy thing to use but it is working for all keys here.

**Comment by sprnza** [comment]
@akallabeth It does work for these keys for me too but it doesn't remap win key. Try this `win - >caps` `caps - >win` `/kbd-remap:0x3a=0xe05b,0xe05b=0x3a`

**Comment by akallabeth** [comment]
@sprnza you have the wrong scancode for the win key, scancodes are `<256`

**Comment by sprnza** [comment]
@akallabeth here is a single keypress
```
sdg-dell ➜  ~ sudo showkey --scancodes
press any key (program terminates 10s after last keypress)...
0x9c
0xe0 0x5b 0xe0 0xdb
0x1d
^Ccaught signal 2, cleaning up..
```
as fas as I understand `0xe0 0x5b` is for press  `0xe0 0xdb` is for release.

**Comment by akallabeth** [comment]
@sprnza terminology here is somewhat vague, but what you see is already a mapping. (somehow everything at that level is called `scancode` although everyone means something slightly different)

but you´re right, we remap `RDP scancodes` which are slightly different from `keyboard scancodes`. (so my last comment is wrong)

Try `/kbd-remap:0x3a=0x15b,0x15b=0x3a`

**Comment by sprnza** [comment]
Thank you it works!

**Comment by akallabeth** [comment]
@sprnza created https://github.com/FreeRDP/FreeRDP/pull/7283 to allow listing of scancodes and `VK_*` names. that might be helpful here, so if you (or anyone in this thread) has time to check the output please do so, the we can add this to freerdp.

**Comment by antenore** [comment]
Thanks @akallabeth !

Sorry to bother you.

I'm testing

**Comment by antenore** [comment]
@sprnza just in case

```
git fetch origin pull/7283/head:kbd_scancode_listing
git checkout kbd_scancode_listing
``` 

Compile and test.

On my side it works, now the challenge will be on my side to do something similar on Remmina :-)
