### ISSUE TITLE
missing return in transport_set_recv_callbacks (transport.c)

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#7280]
In the current master the function transport_set_recv_callbacks in libfreerdp/core/transport.c is missing the return.
I build for openSUSE Tumbleweed with:
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX:PATH=%{_prefix} \
    -DCMAKE_INSTALL_LIBDIR:PATH=%{_lib} \
    -DCMAKE_SKIP_INSTALL_RPATH=ON \
    -DWITH_CUPS=ON \
    -DWITH_CLIENT=ON \
    -DWITH_PCSC=ON \
    -DWITH_ALSA=ON \
    -DWITH_PULSE=ON \
    -DWITH_OSS=OFF \
    -DWITH_DIRECTFB=OFF \
    -DWITH_JPEG=ON \
    -DWITH_GSM=ON \
    -DWITH_GSTREAMER_1_0=ON \
    -DWITH_IPP=OFF \
    -DWITH_OPENSSL=ON \
    -DWITH_CHANNELS=ON \
    -DWITH_X11=ON \
    -DWITH_XCURSOR=ON \
    -DWITH_XEXT=ON \
    -DWITH_XKBFILE=ON \
    -DWITH_XI=ON \
    -DWITH_XINERAMA=ON \
    -DWITH_XRENDER=ON \
    -DWITH_XV=ON \
    -DWITH_ZLIB=ON \
    -DWITH_KRB5=OFF \
    -DWITH_GSSAPI=OFF \
    -DBUILTIN_CHANNELS=OFF \
    -DWITH_SERVER=ON \
    -DWITH_SSE2=ON \
    -DWITH_DEBUG_SCARD=OFF \
    -DWITH_SMARTCARD_INSPECT=ON \
    -DWITH_ICU=ON \
    -DWITH_FFMPEG=ON \
    -DWITH_DSP_FFMPEG=ON \
    -DWITH_WAYLAND=ON \
    -DWITH_SANITIZE_ADDRESS=OFF \
    -DWITH_LIBSYSTEMD=ON \
    -DCMAKE_NO_BUILTIN_CHRPATH=ON \
    -DWITH_LAME=ON \
    -DWITH_CAIRO=ON \
    -DCHANNEL_URBDRC_CLIENT=ON \
    -DCHANNEL_URBDRC=ON \
    -DWITH_SOXR=ON \
    -DWITH_FUSE2=ON \
    .

**Comment by akallabeth** [comment]
#7278 addresses that, @hendwolt you were too fast :)

**Comment by hendwolt** [comment]
@akallabeth : Sorry, but I don't see any changes of transport.c in #7278. The warning - that is treated as an error for openSUSE - is still there.

**Comment by hendwolt** [comment]
To clarify it, this change solves the issue for me:
`*** libfreerdp/core/transport_a.c	2021-09-09 17:43:23.712348040 +0200
--- libfreerdp/core/transport.c	2021-09-10 17:59:32.505652627 +0200
*************** BOOL transport_set_recv_callbacks(rdpTra
*** 1445,1450 ****
--- 1445,1451 ----
  	WINPR_ASSERT(transport);
  	transport->ReceiveCallback = recv;
  	transport->ReceiveExtra = extra;
+     return TRUE;
  }
  
  BOOL transport_get_blocking(rdpTransport* transport)
`

**Comment by akallabeth** [comment]
@hendwolt sorry, mixed it up with the other `missing return` in transport (header).
Should be fixed now.

**Comment by hendwolt** [comment]
Confirmed. It is fixed now. Thanks.
