### ISSUE TITLE
SSL_Read: Failure in SSL library (protocol error?) on Win2k8 hosts

### ISSUE THREAD

**Issue by askreet** [FreeRDP/FreeRDP#733]
Getting the following when connecting to Windows 2008 server with NLA enabled:

```
SSL_read: Failure in SSL library (protocol error?)
Authentication failure, check credentials.
If credentials are valid, the NTLMSSP implementation may be to blame.
```

Works fine against our Windows 2003 systems.  Using version 1.0.1 -- not sure where to begin troubleshooting.

**Comment by muhammadsufiyan** [comment]
@olegon-ru thanks your answer works like charm... `--sec rdp` :)

**Comment by ajupazhamayil** [comment]
Thank you soo much @olegon-ru .... It helped

**Comment by dhavalkamble** [comment]
@yurii-github Yes, it worked for me too. Thank you so much.

**Comment by qwipx94** [comment]
Thanks to all above.
-Adding the -sec rdp parameter alone didn't work.
-Putting the address at the end alone didn't work.
-Doing both worked like a charm.
:)
