### ISSUE TITLE
video channel yells geometry channel not ready - win32

### ISSUE THREAD

**Issue by alexandru-bagu** [FreeRDP/FreeRDP#7355]
This issue is present in 2.4.0 as well as in master.

This issue appears when:
1. you start wfreerdp with /video
2. you open a video (I tested youtube) in the remote session
3. leave the wfreerdp window be for a few seconds
After a few moments you will get "geometry channel not ready, ignoring request". 

I debugged this a bit on master and based on the Linux X implementation I can see that the events for dynamic channels for geometry, video control and video data are not handled on Windows.
Following the example of X I attempted to do this: https://github.com/alexandru-bagu/FreeRDP/commit/a7f66a654ff5b55bbeb8155caccb46bd8305d319

Now it no longer says anything about geometry but I get a black overlay over the video. 
I debugged a bit more and there is video data coming and it is being decoded properly (no errors from h264) however it seems it's not actually working as it should.

**Comment by akallabeth** [comment]
yes, this is currently only implemented with `xfreerdp`

**Comment by akallabeth** [comment]
#7357 adds support to wayland (not finished yet)

**Comment by alexandru-bagu** [comment]
The values that work correctly for me are these with a change to the `C` function `- 16L` instead of `- 0L` but that can be reverted and the table below updated
```
/**
 * | R |   ( | 298     0    409 | | Y - 16  | )
 * | G | = ( | 298   -100  -208 | | U - 128 | ) >> 8
 * | B |   ( | 298    517    0  | | V - 128 | )
 */
```

**Comment by akallabeth** [comment]
@alexandru-bagu no, same error on all backends.
The matrix is the one you referenced. all for fixing this, but need to be sure the matrix is the correct one.

**Comment by alexandru-bagu** [comment]
Checking it now but `C(V)` seems wrong in `YUV2R`.

**Comment by akallabeth** [comment]
@alexandru-bagu ok, indeed. the matrix seems to be wrong.
