### ISSUE TITLE
Crash or heap corruption when using clipboard from linux with emoji + accented vowels

### ISSUE THREAD

**Issue by giox069** [FreeRDP/FreeRDP#7363]
Start xfreerdp on linux
```xfreerdp /v:192.168.56.2 /u:user1 /d:pc1 +clipboard -grab-keyboard```

Copy the following UTF8 string in linux

😭😭èèàà

(don't copy from github, use this: ```echo -e '\xf0\x9f\x98\xad\xf0\x9f\x98\xad\xc3\xa8\xc3\xa8\xc3\xa0\xc3\xa0' | xclip -selection c```)

Paste it to windows 10 one or two times: xfreerdp will crash or freeze. According to some stack traces, the problem could be into ConvertToUnicode() or ConvertUTF8toUTF16()

Edit: tested on master, 2.4.0 and 2.3.2.

**Comment by akallabeth** [comment]
@giox069 do you have such a stack trace?
currently on fedora and can not reproduce here (build with `WITH_ICU=ON` which might influence this)

**Comment by antenore** [comment]
And I confirm with `-DWITH_ICU=ON` it doesn't crash.

Beside the fact that it shouldn't crash with ICU disabled, should be enabled by default?

Just to know if it's better we enable ICU in our flatpak and snap builds
