### ISSUE TITLE
Improper locking bug due to the unreleased lock?

### ISSUE THREAD

**Issue by ryancaicse** [FreeRDP/FreeRDP#7364]
Dear developers, it seems the lock `event_queue->mutex` is not released when `event_queue->count < 1`. Should it be a bug?
https://github.com/FreeRDP/FreeRDP/blob/fab649a1b9396ba37ae877ca8f1165754d407689/server/Mac/mf_event.c#L130-L143

**Comment by akallabeth** [comment]
most likely is.
the mac client is currently not well maintained, we´re looking for someone willing to check it from time to time.
