### ISSUE TITLE
Graphical Bug with FreeRDP

### ISSUE THREAD

**Issue by UniC0re** [FreeRDP/FreeRDP#7383]
Releated pull request for master: 
Hello,

we have a problem. I'm using FreeRDP on StratoDesk - i have that weird graphic bug when closing windows, they are still visible. When im moving the mouse, the window disappers slowly.

Don't know how to explain exactly.

Already contacted StratoDesk Support. They couldn't help me, so i'm here now..

**Video is attached.**

Thanks for your help!!

https://user-images.githubusercontent.com/92865455/138098287-314f3118-5dab-4c05-a180-2926be1763c3.mp4

**Comment by eronnen** [comment]
I have the same issues when using `OpenH264=1.8.0` and the server uses Nvidia NVENC, getting a lot of warning logs of
"avc444_decompress failure: 0, ignoring update"
"DecodeFrame2 state: 0x22"

**Comment by akallabeth** [comment]
@eronnen ok, the error is from `openh264` and means: `dsRefLost | dsDataErrorConcealed` so it looks like you have either a broken encoder or frame loss?
Might be another bug in `openH264` just like https://github.com/cisco/openh264/issues/3305 so if possible, try a build of `FreeRDP` against `FFMPEG` and without `openh264`

**Comment by eronnen** [comment]
@akallabeth The encoder is from NVIDIA's official driver, so I'm doubt that it's broken, and also it's successfuly decoded with microsoft's rdp client...

The bugs you had in [ cisco/openh264#3305](https://github.com/cisco/openh264/issues/3305) are solved in master? I tried to compile with `OpenH264=master` too and had worse decoding errors than `OpenH264=1.8.0`, so it might be a different decoding bug then

**Comment by akallabeth** [comment]
@eronnen ok, then wich profile is it using to encode?
The problem may result in a profile not properly supported by `openh264`. Does it work with `FFMPEG`?

**Comment by akallabeth** [comment]
> @akallabeth The encoder is from NVIDIA's official driver, so I'm doubt that it's broken, and also it's successfuly decoded with microsoft's rdp client...

ok, that is a good thing to know there is something that decodes that properly. Sadly everything deviating from the most commonly used paths (e.g. simple baseline decoding) has often subtle issues that needed to be addressed.
