### ISSUE TITLE
Floating bar title encoding is not correct

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#7392]
**Describe the bug**
Floating bar title encoding is not correct when I write a title with accents

**Screenshots**

![image](https://user-images.githubusercontent.com/25820234/138446703-501daae7-98cf-4dc5-8289-f05558faf48e.png)

**Application details**
This is FreeRDP version 3.0.0-dev (f66246a69)

xfreerdp /u:"user" /p:"password" /title:"Sesión" /cert-ignore /from-stdin /v:localhost:3389  /floatbar /f

It seems that the method used is 
```
XDrawString(display, floatbar->handle, gc, floatbar->width / 2 - len * 2, 15, floatbar->title,
	            len);
```

**Comment by amazingfate** [comment]
It's better to use XmbDrawString instead of XDrawString. I will create a pull request later.
