### ISSUE TITLE
FreeRDP stable-1.1.0 dynamic-resolution support

### ISSUE THREAD

**Issue by JSSSSSSSSSS** [FreeRDP/FreeRDP#7407]
I am trying to merge 80dab90f1 to FreeRDP stable-1.1.0.
Disp channel worked, and disp_caps_pdu received and handled correctly.
When I change my window's size, layout_pdu was sent successfully. but my window's image was not covered with the window, but be cut to its original size, and the increased part was filled with black rectangles.
![image](https://user-images.githubusercontent.com/58905687/139022994-f5ac05fd-a381-4731-8a02-3b5dfdbd180d.png)
I need help. Please.

**Comment by akallabeth** [comment]
upgrade.
