### ISSUE TITLE
audin on macOS 12 Monterey

### ISSUE THREAD

**Issue by lemonmojo** [FreeRDP/FreeRDP#7408]
macOS 12 Monterey is now out since Monday and bug reports from users of Royal TSX are starting to come in.
One of the bug reports we received indicated that microphone redirection doesn't work anymore. We were able to verify this on multiple Monterey installations.

The issue is that [AudioQueueNewInput](https://github.com/FreeRDP/FreeRDP/blob/master/channels/audin/client/mac/audin_mac.m#L255) fails with `kAudioFormatUnsupportedDataFormatError` while the same code works when run on Big Sur or earlier.

We were able to work around the issue by making adjustments to the `audin_mac_set_format` method like this:

```
static UINT audin_mac_set_format(IAudinDevice *device, const AUDIO_FORMAT *format,
                                 UINT32 FramesPerPacket)
{
	AudinMacDevice *mac = (AudinMacDevice *)device;

	if (!mac->isAuthorized)
		return ERROR_INTERNAL_ERROR;

	if (device == NULL || format == NULL)
		return ERROR_INVALID_PARAMETER;

	mac->FramesPerPacket = FramesPerPacket;
	mac->format = *format;
	WLog_INFO(TAG, "Audio Format %s [channels=%d, samples=%d, bits=%d]",
	          audio_format_get_tag_string(format->wFormatTag), format->nChannels,
	          format->nSamplesPerSec, format->wBitsPerSample);
	mac->audioFormat.mBitsPerChannel = format->wBitsPerSample;

	if (format->wBitsPerSample == 0)
		mac->audioFormat.mBitsPerChannel = 16;
	
	mac->audioFormat.mChannelsPerFrame = mac->format.nChannels;
	mac->audioFormat.mFramesPerPacket = 1;

	mac->audioFormat.mBytesPerFrame = mac->audioFormat.mChannelsPerFrame * (mac->audioFormat.mBitsPerChannel / 8);
	mac->audioFormat.mBytesPerPacket = mac->audioFormat.mBytesPerFrame * mac->audioFormat.mFramesPerPacket;
	
	mac->audioFormat.mFormatFlags = audin_mac_get_flags_for_format(format);
	mac->audioFormat.mFormatID = audin_mac_get_format(format);
	mac->audioFormat.mReserved = 0;
	mac->audioFormat.mSampleRate = mac->format.nSamplesPerSec;
	return CHANNEL_RC_OK;
}
```

Unfortunately we can't provide a PR at the moment because we're using an older version of FreeRDP and time doesn't permit it right now. But since this is a quick fix you should investigate yourself anyway before merging this.

**Comment by lemonmojo** [comment]
@akallabeth Just noticed that these changes were not backported to 2.x. Would you be able to do that?

**Comment by akallabeth** [comment]
@lemonmojo just request it or do a `git cherry-pic -x <commit>` and create a pr against `stable-2.0`. created https://github.com/FreeRDP/FreeRDP/pull/8286

**Comment by lemonmojo** [comment]
@akallabeth thx!
