### ISSUE TITLE
Cannot find OpenSSL on MACOS M1 chip

### ISSUE THREAD

**Issue by nocomeback95** [FreeRDP/FreeRDP#7434]
Hi guys,
I got this issue when try to build cmake file
`Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)`
  
I installed openssl@1.1 by brew command, and added config path in .zshrc file.
`export PATH="/opt/homebrew/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/openssl@1.1/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig"`
 
Could you help me please?
Thanks in advance

**Comment by akallabeth** [comment]
just as the message suggests, set `OPENSSL_ROOT_DIR` to `OpenSSL` root path or `OPENSSL_LIBRARIES` and `OPENSSL_INCLUDE_DIR` to the library and include path.
