### ISSUE TITLE
Possible big endian breakage in 2.4.1

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#7436]
**Describe the bug**
On the `stable-2.0` branch I see the following build warning:
```
/FreeRDP/libfreerdp/core/gateway/rdg.c: In function ‘rdg_handle_ntlm_challenge’:
/FreeRDP/libfreerdp/core/gateway/rdg.c:1218:65: warning: passing argument 4 of ‘crypto_base64_decode’ from incompatible pointer type [-Wincompatible-pointer-types]
 1218 |         crypto_base64_decode(token64, (int)len, &ntlmTokenData, &ntlmTokenLength);
      |                                                                 ^~~~~~~~~~~~~~~~
      |                                                                 |
      |                                                                 size_t * {aka long unsigned int *}
In file included from /FreeRDP/include/freerdp/crypto/tls.h:23,
                 from /FreeRDP/libfreerdp/core/gateway/rdg.h:33,
                 from /FreeRDP/libfreerdp/core/gateway/rdg.c:36:
/FreeRDP/include/freerdp/crypto/crypto.h:111:52: note: expected ‘int *’ but argument is of type ‘size_t *’ {aka ‘long unsigned int *’}
  111 |                                               int* res_length);
      |                                               ~~~~~^~~~~~~~~~
```
and the same for `rpc_ncacn_http_recv_in_channel_response` and `rpc_ncacn_http_recv_out_channel_response`. Although, it seems to be safe for little endian, I am pretty sure this might be a problem on big endian...

**Environment:**
 - OS: Linux
 - Version/Distribution: Fedora 35
 - Architecture: amd64

**Additional context**
This was introduced by https://github.com/FreeRDP/FreeRDP/pull/7366 resp. https://github.com/FreeRDP/FreeRDP/pull/7366/commits/f0a0683fa6a3f696c4bc5ba88c128bc781c54895.

This is not a problem on `master` as `crypto_base64_decode` really uses `size_t *` there.

**Comment by akallabeth** [comment]
@ondrejholy all occurrences should be fixed now, closing.

**Comment by ondrejholy** [comment]
Indeed, thanks.
