### ISSUE TITLE
Do freerdp not support http proxy that has username/password?

### ISSUE THREAD

**Issue by merlin82** [FreeRDP/FreeRDP#7447]
i see the code like this,  will support soon? thanks.

`BOOL proxy_connect(rdpSettings* settings, BIO* bufferedBio, const char* proxyUsername,
                   const char* proxyPassword, const char* hostname, UINT16 port)
{
	switch (freerdp_settings_get_uint32(settings, FreeRDP_ProxyType))
	{
		case PROXY_TYPE_NONE:
		case PROXY_TYPE_IGNORE:
			return TRUE;

		case PROXY_TYPE_HTTP:
			return http_proxy_connect(bufferedBio, hostname, port);

		case PROXY_TYPE_SOCKS:
			return socks_proxy_connect(bufferedBio, proxyUsername, proxyPassword, hostname, port);

		default:
			WLog_ERR(TAG, "Invalid internal proxy configuration");
			return FALSE;
	}
}`

**Comment by akallabeth** [comment]
currently not.
