### ISSUE TITLE
high cpu / no connection - infinite loop of 'Do you trust the above certificate? (Y/T/N)'

### ISSUE THREAD

**Issue by jpmorrison** [FreeRDP/FreeRDP#7453]
May be easier to replicate on a fresh install/account

cmd
`wfreerdp.exe /u:test /p:test /v:192.168.0.123:3389`

runs and nothing happens. High CPU in task manager.

`wfreerdp.exe /u:test /p:test /v:192.168.0.126:3389  /log-level:debug > freerdp.log`

```
-----END CERTIFICATE-----

        --------------------------------------
The above X.509 certificate could not be verified, possibly because you do not have
the CA certificate in your certificate store, or the certificate has expired.
Please look at the OpenSSL documentation on how to add a private CA to the store.
Do you trust the above certificate? (Y/T/N)
Do you trust the above certificate? (Y/T/N)
Do you trust the above certificate? (Y/T/N)
Do you trust the above certificate? (Y/T/N)
...
```
logfile fills up quickly 

`This is FreeRDP version 3.0.0-dev (e80c24e83)`    and `391f2f7c4` but not Freerdp2

I noticed this with cygwin/bash as well but I don't recall the certificate prompt. 
I checked a few machines - Win10/WIn11/Server 2016 and had the same issue.

**Comment by akallabeth** [comment]
Your build requires input from `stdin` to accept a (changed) certificate.
Which version do you use and does this happen when starting a `RDP` file too?

**Comment by akallabeth** [comment]
@jpmorrison ok. I´ve added some logging and disable console mode if not specifically build for it in #7458

**Comment by akallabeth** [comment]
Ok, #7458 is merged. Now only windows builds with `WITH_WIN_CONSOLE` defined use the command line input at all (which is not the case for nightly)
