### ISSUE TITLE
the problem of opening the window menu in RemApp 1Cv8.3

### ISSUE THREAD

**Issue by Z-Good** [FreeRDP/FreeRDP#7460]
Hello.
There is a problem when opening 1Cv8 Remap with Windows servers even through the newest xfreerdp 2.4. The drop-down list in the program and any drop-down menu does not work. IT flashes and disappears instantly.

I have tried all Ubuntu distributions and their derivatives. Connected all available PPA repositories and additional command line options.

Standard Windows programs (notepad) work without problems, and 1C v8 developers clearly have crooked hands. Full RDP also works without problems. But we must somehow defeat Remap. It looks like something is conflicting in X11 when running the animation. Although I tried disabling RFX on the server at all - it didn't help.

Maybe the delay is wrong or something like that.
OS Ubuntu 18 i386 - 20 i64
FreeRdp 2.0-2.4
RemApp for Windows Server 2008 - 2012

https://user-images.githubusercontent.com/94977215/143261978-ea1c88e2-dd9d-475f-96ac-5ed5e70d5d8e.mp4

**Comment by Z-Good** [comment]
From Windows system RemApp works without problems, as in a full RDP session with Linux, but we need RemApp from Linux to Windows.

**Comment by akallabeth** [comment]
1. only thing I can think of here is enable `rfx/gfx` server side and connect with `/network:auto` to the remote.
legacy rdp has quite a lot of issues (specifically in combination with `xfreerdp`)
1. There are some (FreeRDP based) RDP clients for linux that have reimplemented the modern remote app protocol we currently lack in `xfreerdp`, maybe you have better luck with that.

**Comment by Z-Good** [comment]
But in the old version of freerdp 1.1 on Ubuntu 16, I managed to launch this menu. Only after switching to another application, the RemApp window froze.
Have you removed something from the version 2?
And which Linux clients today are able to run a seamless run in RemoteApp?

**Comment by akallabeth** [comment]
@Z-Good well, the remote-app mode in `xfreerdp` stayed nearly the same from v1.
The other parts of the system did not, so now some issues that were previously overlooked are now easy to spot.

https://flathub.org/apps/search/remote%20desktop lists a few, some of which support remote app.

**Comment by krovostok-1c** [comment]
It is sad that this problem not solved over a 7-8 years :(
