### ISSUE TITLE
problem with rdpsnd channel plugin

### ISSUE THREAD

**Issue by tsol** [FreeRDP/FreeRDP#747]
Hello guys! Thanks for your great work on FreeRDP!

We have a strange sound redirection problems with FreeRDP. Here's what we get:
1. FreeRDP 0.8.2 version works perfectly with Windows 2003 server.
   With Windows Server 2008 R2 sound cracks all the time and gets really choppy.
   (NO sound quality switches observed).
2. With all older versions of FreeRDP 
   On windows 2003 server sound is very choppy and sound quality switches from HIGH to LOW all the time.
   On windows 2008 R2 sound is still choppy, but much better than on 2003. One could live with that, but
   sound quality also switches in random order! From HIGH to LOW and then back.

Any suggestions for that?

**Comment by ivan-83** [comment]
Fix: https://github.com/ivan-83/FreeRDP/commit/8d5825ee007a7889992d5a01e482d1589dd6a7ee
or use: /sound:sys:alsa,format:1,quality:high
