### ISSUE TITLE
Remoteapp open some application, there is black border around window.

### ISSUE THREAD

**Issue by a10155212722** [FreeRDP/FreeRDP#7470]
System type:  Ubuntu 21
when I open some app，there is black border around window. Then I check  2.2.0 to master，the black border also exists.
What's the reason of this appearance?
Is there a resolution to resolve this problem?

**Comment by akallabeth** [comment]
could you please add a little more information just as requested by the template you were presented?

**Comment by leoqingliu** [comment]
I made some tests and found the black borders appeared on electron based apps

**Comment by akallabeth** [comment]
@leoqingliu could you answer the question then?
find you can reproduce this, but sharing how (as in detailed enough someone else can create such a test setup) to do that might improve the chance this gets fixed.
