### ISSUE TITLE
State of runtime h264 support

### ISSUE THREAD

**Issue by frispete** [FreeRDP/FreeRDP#7477]
Hi,

what's the state of FreeRDP runtime detection of h264 codecs. 

To my knowledge, FreeRDP uses the openh264 codec, if compiled with it. As you probably know, this doesn't solve the license issue of that package. Which other h264 codecs does FreeRDP support by now?

Specifically, in the linux community, ffmpeg is used, when it comes to h264 support, but will this work, if FreeRDP is built with a version, that is missing h264 support during build time?

The idea is to compile FreeRDP in such a way, that it detects availability of h264 during runtime.

**Comment by akallabeth** [comment]
Currently we assume it must be there if compiled with it.
#7476 removes that requirement and should allow running in fallback mode (e.g. no `H264` codec but progressive or RFX)

**Comment by frispete** [comment]
Thanks @akallabeth, I kind of expected this. 

What would be needed to enable a full featured `H264` codec? 

But let's start with the basics: what's the preferred `H264` codec for FreeRDP? 
I'm under the impression, that `openh264` is the preferred one.
More specifically, are there any known caveats using the one from `ffmpeg`, which is `x264` to my knowledge?

@Vogtinator `ffmpeg` is a strong moving target. While they try to keep the APIs stable within a release, it **will** change with new releases. Next, there's the complexity of this this package. With your fix, we might get around the immediate error state, but will not get full `H264` support either. Given, we just build against `openh264`, but do not deliver it, would that impose any license issues?

@akallabeth Do you know, if this case is handled properly during runtime: build against some codec, but than missing during runtime? I know, that FreeRDP dynloads certain libraries, but that seems not to be the case with codec libs. Is this case tested already?

Any other ideas, how we get there?
