### ISSUE TITLE
rdg_tls_connect:freerdp_set_last_error_ex ERRCONNECT_TLS_CONNECT_FAILED [0x00020008]

### ISSUE THREAD

**Issue by rvigliotti-sf** [FreeRDP/FreeRDP#7484]
This is FreeRDP version 2.4.0 (n/a) on MacOS X

I'm randomly getting the following error while attempting to connect to my Windows Server 2019 RDS Environment (Gateway + Broker)

`xfreerdp /f /v:brokerVIP /g:gatewayVIP /load-balance-info:"tsv://MS Terminal Services Plugin.1.Collection"`

`
[12:02:40:918] [57094:0eb67000] [INFO][com.freerdp.core] - freerdp_tcp_connect:freerdp_set_last_error_ex resetting error state`
`[12:02:40:918] [57094:0eb67000] [DEBUG][com.freerdp.core] - connecting to peer 1.1.1.1`
`[12:02:41:584] [57094:0eb67000] [ERROR][com.freerdp.core] - rdg_tls_connect:freerdp_set_last_error_ex ERRCONNECT_TLS_CONNECT_FAILED [0x00020008]`

This error does not happen all the time: sometimes after 7/10 attempts I can establish the connection and this error sometimes happens before prompting password for the broker.

The same issues DOES NOT happen with the official MS Mac OS RDP Client where I can connect all the time.

I've tried almost all the switches available in the manual to toggle protocols, enforce NLA, disable NLA, force TLS protocols etc. Any hint?

**Comment by giovannifi** [comment]
Hi I have just reported a similar issue here: https://github.com/FreeRDP/FreeRDP/issues/8569. Would you be so kind to send me more detailed instructions to make it work using your method? Thanks

**Comment by rvigliotti-sf** [comment]
@giovannifi in my case the issue has been resolved server side where I had to enable the session stickiness on the load balancer. It depends on the infrastructure you are connecting to. 

However, looking at your other issue, I believe the might be different since you are saying that it works from some client whereas it doesn't from others.

**Comment by giovannifi** [comment]
yes you are right, the problem is with the client. I have two computers with two different linux mint OS versions and one works and the other does not. I tried to downgrade the software (xfreerdp and remmina, cause the old versions works with the old OS) but it seems that it is not possible to do that: the older versions of the programs are not available on the repository for the newer OS. I guess I have to manually compile them, but I am not an expert with that.
