### ISSUE TITLE
Geometry with percent (-g X%) creates visual artefacts

### ISSUE THREAD

**Issue by uzhoasit** [FreeRDP/FreeRDP#749]
When I use the geometry options with percent i get visual artefacts (xfreerdp -g 90%  SERVER):

http://s9.postimage.org/685m7tbcf/artefact1.png
http://s5.postimage.org/uydiwnbef/artefact2.png

Using --no-fastpath, --no-glyph-cache, --no-osb or --no-bmp-cache  makes it even worser:
http://s5.postimage.org/lt562s7zr/artecact3.png

When using fixed width and height (-g WxH) or workarea there are no artefacts.
Tested on latest Version in Master (FreeRDP-FreeRDP-1.0.1-1075-g7ef2ba8) under Ubuntu 12.04. 
The Remote Server is a Windows XP.

**Comment by bmiklautz** [comment]
On master I couldn't observer same/similar artifacts in my tests but the sizes aren't a multiple of four pixes (as @dpoe) suggests therefore it still might cause artifacts.

**Comment by weberhofer** [comment]
I have just tested with a recent version and don't get any artifacts using the following command-line:

```bash
xfreerdp -size:90% -v:win1

**Comment by bmiklautz** [comment]
Couldn't reproduce/observe any artefacts with the latest master. If the problem still exists for you please re-open the issue or create a new one.
