### ISSUE TITLE
Add flag to use same credentials used for Gateway when connecting to RDS Farm (Gateway and Brokers)

### ISSUE THREAD

**Issue by rvigliotti-sf** [FreeRDP/FreeRDP#7493]
**Is your feature request related to a problem? Please describe.**
Currently, when connecting to an RDS Farm (Gateway + Brokers) xfreerdp stores the username as it only asks for password at second prompt when connecting to the brokers. It would be great to re-use the password as well when using a specific flag

**Describe the solution you'd like**
add a flag that allows to use the same set of credentials used to auth against the the gateway when connecting to an RDS Farm (Brokers)

**Describe alternatives you've considered**
N/A

**Additional context**
When Connecting to a RDS farm behind a GW, the actual authentications are two as technically there might be two different domains or accounts used.

**Comment by akallabeth** [comment]
@rvigliotti-sf please clarify, redirection is already supported and a properly set up environment only requires one login

**Comment by rvigliotti-sf** [comment]
@akallabethmy the environment is properly setup as this works with the Microsoft RDP Client. I am not sure how to set this up in xfreerdp

![image](https://user-images.githubusercontent.com/64626085/146351020-61e50e1c-a746-4262-8c42-85a0551ae7c8.png)

**Comment by akallabeth** [comment]
Ok, 
* the `rdp-file` option `prompcredentialsonce:i:value` is respected by `FreeRDP`
* If you only add (any of) `/u:user /p:password /d:domain` then these are used for gateway and following login by default. Only when adding (any of) `/gu:gwuser /gd:gwdomain /gp:gwpwd` options this is not done.

**Comment by rvigliotti-sf** [comment]
> Ok,
> 
> * the `rdp-file` option `prompcredentialsonce:i:value` is respected by `FreeRDP`
> * If you only add (any of) `/u:user /p:password /d:domain` then these are used for gateway and following login by default. Only when adding (any of) `/gu:gwuser /gd:gwdomain /gp:gwpwd` options this is not done.

Thank you, that worked!
