### ISSUE TITLE
freerdp shadow multimonitor - second screen is blank

### ISSUE THREAD

**Issue by predkambrij** [FreeRDP/FreeRDP#7514]
Hi.

It appears that multimonitor configuration doesn't work with freerdp-shadow-cli server.

I successfully connected to Windows 10 RDP with the following command:
xfreerdp /multimon:force /v:192.168.0.100

But, when I connect to freerdp shadow server I get the second screen blank (see the screenshot). Mouse and keyboard appears to work on the second screen (when I move terminal in between the screens, I could click on it on the other screen too).

I started freerdp shadow server with the following commands:
freerdp-shadow-cli /monitors:0,1 -auth

I also tried with this one:
freerdp-shadow-cli -auth

I connect to the second monitor (only) if I start it with this command:
freerdp-shadow-cli /monitors:1,0 -auth

Environment:
Client and host are ubuntu 18.04 (which comes with 2.0.0-dev). I also tried with this Docker recipe.

    $ cat Dockerfile 
    from ubuntu:latest
    run apt-get update
    run apt-get install -y freerdp2-shadow-x11
    run useradd user
    run mkdir -p /home/user/.config/freerdp && chown user /home/user/.config/freerdp
    
    docker build -t freerdp-sha .
    docker run --user=user --network=host -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -it --rm freerdp-sh

That's ubuntu 20.04.3 with FreeRDP version 2.2.0 - with the same result.

![Screenshot from 2021-12-27 00-11-26](https://user-images.githubusercontent.com/1273258/147422289-24d1ff56-336d-4d22-9b51-b2e1be699b9c.png)

Best regards

**Comment by akallabeth** [comment]
Do you have a second monitor on the machine running shadow?
Shadow does (just as the name implies) shadow/clone your local session and the remote client must use the same resolution/monitor layout (or use `/smart-sizing`) to display what is shadowed.

**Comment by predkambrij** [comment]
Yes - it's a physical machine. The client has the second monitor with a bit higher resolution (1920x1200 rotated left), but I changed the resolution that matched rdp server's second monitor, but with the same result. I tried with /smart-sizing, but that just extended the first screen through both monitors (not displaying the second monitor).
