### ISSUE TITLE
impssible to install in Kubuntu Groovy Gorilla 20.10

### ISSUE THREAD

**Issue by juanpc2018** [FreeRDP/FreeRDP#7519]
downloaded all amd64 from here:
http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/?C=M;O=D
but some
dependencies Not meet.

> Err:1 http://archive.ubuntu.com/ubuntu groovy/main amd64 libfreerdp2-2 amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> Err:2 http://archive.ubuntu.com/ubuntu groovy/main amd64 libfreerdp-server2-2 amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> Err:3 http://archive.ubuntu.com/ubuntu groovy/main amd64 libwinpr-tools2-2 amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> Err:4 http://archive.ubuntu.com/ubuntu groovy/main amd64 libfreerdp-shadow2-2 amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> Err:5 http://archive.ubuntu.com/ubuntu groovy/main amd64 libfreerdp-shadow-subsystem2-2 amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> Err:6 http://archive.ubuntu.com/ubuntu groovy/main amd64 libfreerdp-client2-2 amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> Err:7 http://archive.ubuntu.com/ubuntu groovy/main amd64 libwinpr2-dev amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> Err:8 http://archive.ubuntu.com/ubuntu groovy/main amd64 winpr-utils amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> Err:9 http://archive.ubuntu.com/ubuntu groovy/main amd64 freerdp2-dev amd64 2.2.0+dfsg1-1
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 

muon, synaptic
No snap

> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/libfreerdp2-2_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/libfreerdp-server2-2_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/libwinpr-tools2-2_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/libfreerdp-shadow2-2_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/libfreerdp-shadow-subsystem2-2_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/libfreerdp-client2-2_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/libwinpr2-dev_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/winpr-utils_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/f/freerdp2/freerdp2-dev_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
> 
> W: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/f/freerdp2/freerdp2-wayland_2.2.0+dfsg1-1_amd64.deb
>   404  Not Found [IP: 2001:67c:1360:8001::23 80]
>

**Comment by akallabeth** [comment]
well, this is the wrong place for this ;)
try ubuntu support forums (or do `apt update`, it looks like there is something out of date)
