### ISSUE TITLE
Windows 365

### ISSUE THREAD

**Issue by madorian** [FreeRDP/FreeRDP#7523]
**Is your feature request related to a problem? Please describe.**

Currently, only Windows RDP Client can connect to Windows 365

**Describe the solution you'd like**

Connect to Windows 365

**Describe alternatives you've considered**

Running inside browser, which somehow works, but not all key combinations work and it's a bit slow. 

**Additional context**

**Comment by akallabeth** [comment]
This requires `kerberos` and some extensions to be implemented.
This is not going to happen soon as that is a lot of work, but you can disable `NLA` (and use `TLS`) authentication, then it should be possible to connect.

**Comment by madorian** [comment]
, but there's only a URL we can connect to and Remmina does not allow a URL to connect to

**Comment by akallabeth** [comment]
@madorian what are you talking about?

**Comment by Fantu** [comment]
@madorian I don't use windows 365 but from a fast search here a solution: https://techcommunity.microsoft.com/t5/windows-365-feature-requests/windows-365-support-for-linux-and-chrome-os-endpoints/idc-p/3056527/highlight/true#M197

**Comment by madewithpat** [comment]
> @madorian I don't use windows 365 but from a fast search here a solution: https://techcommunity.microsoft.com/t5/windows-365-feature-requests/windows-365-support-for-linux-and-chrome-os-endpoints/idc-p/3056527/highlight/true#M197

I'm not sure I follow exactly how this solves it

**Comment by madewithpat** [comment]
I don't think this is necessarily a freerdp issue, but does anyone have a solution that doesn't involve installing stuff on the windows365 VM?

**Comment by akallabeth** [comment]
@madewithpat only option still is using `TLS` security for authentication.
There was some progress regarding kerberos, but it is not there yet to enable `NLA` for the logon policies in place there.

**Comment by madewithpat** [comment]
@akallabeth that makes sense, but I was mainly referring to @madorian ‘s point - I just have a feed url, rather than a server address.

**Comment by akallabeth** [comment]
@madewithpat did not check the format yet (busy with other problems, sorry), but it is most likely a `RDP` file encoded `base64` (or even just a link to one)?
that might work out of the box if decoded, stored and given as command line arg to freerdp

**Comment by madewithpat** [comment]
I think there's a bit more to it than that.. the url just returns a 401, no idea how to authenticate to get a meaningful response

**Comment by orgcontrib** [comment]
> @madorian I don't use windows 365 but from a fast search here a solution: https://techcommunity.microsoft.com/t5/windows-365-feature-requests/windows-365-support-for-linux-and-chrome-os-endpoints/idc-p/3056527/highlight/true#M197

I would recommend folks upvote [here](https://feedbackportal.microsoft.com/feedback/idea/663e8ff7-cfc4-ec11-a7b5-0022482d3366). Most recent related issue (let's consolidate them) is #8515.

**Comment by akallabeth** [comment]
should already be implemented as part of https://github.com/FreeRDP/FreeRDP/issues/6529
