### ISSUE TITLE
xfreerdp 2.4.1 stopped connecting to 6to4 ipv6 hosts

### ISSUE THREAD

**Issue by muwlgr** [FreeRDP/FreeRDP#7524]
On Dec 14th 2021, freerdp package on my Ubuntu 22.04-dev.branch was updated from v 2.3.0 to v 2.4.1
After some time I noticed that is refuses to connect to 6to4 hosts (that is, when ipv6 packets are tunneled between 2 networks behind ipv4 routers).
In strace log, I see that connect(2) call to the required ipv6 address returns errno EINPROGRESS.
Tested rdesktop with the same remote host and connection parameters, it worked.
Can you please investigate the problem and find out whether it is Ubuntu packaging problem, or real FreeRDP issue, whether it affects 6to4 IPs only, or all IPv6, etc.

Thanks in advance for your help.
Ready to provide all additional information on your request.

**Comment by akallabeth** [comment]
@muwlgr I´ve checked the diff between the two versions you mentionied, and the `tcp` routines did not change between these releases.
Could you answer a few questions:
* Are you using direct or gateway connections?
* Do you connect using a DNS name or IP directly?
