### ISSUE TITLE
urbdrc CANCEL_REQUEST fails? USB device not re-assigned to Linux host after redirection

### ISSUE THREAD

**Issue by mp1994** [FreeRDP/FreeRDP#7527]
**Describe the bug**
USB devices are not available in the Linux host after redirection. If I redirect the internal webcam, for example, it works pretty well in Windows. When I close the RDP connection, if I try to use the webcam under Linux, both Cheese and MS Teams do not detect any webcam. I have also found this issue with usb-serial devices (Arduino / Raspberry Pi Pico). 

I have been debugging this a bit. I had the RPI Pico programmed to echo a message over serial every second. The connection over RDP is opened with:

`xfreerdp /d:**** /v:**** /u:**** /p:**** /usb:id:2e8a:000a /log-filters:com.freerdp.channels.urbdrc.client:debug`

This is the log output of FreeRDP:

> [16:48:24:939] [21846:21868] [DEBUG][com.freerdp.channels.urbdrc.client] - [READ ] CANCEL_REQUEST                    [proxy|server] [00000100] InterfaceId=40000005, MessageId=00000000, FunctionId=00000100, length=16
> [16:48:24:939] [21846:21868] [DEBUG][com.freerdp.channels.urbdrc.client] - CANCEL_REQUEST: CancelId=00000000
> [16:48:24:939] [21846:21868] [WARN][com.freerdp.channels.urbdrc.client] - USB request failed with 0000054f
> [16:48:24:274] [21846:21866] [DEBUG][com.freerdp.channels.urbdrc.client] - [WRITE] URB_COMPLETION                    [proxy|client] [00000101] InterfaceId=40000000, MessageId=00000000, FunctionId=00000101, length=49
> [16:48:24:275] [21846:21868] [DEBUG][com.freerdp.channels.urbdrc.client] - [READ ] **CANCEL_REQUEST**                    [proxy|server] [00000100] InterfaceId=40000005, MessageId=00000000, FunctionId=00000100, length=16
> [16:48:24:275] [21846:21868] [DEBUG][com.freerdp.channels.urbdrc.client] - **CANCEL_REQUEST: CancelId=00000001**
> [16:48:24:275] [21846:21868] [WARN][com.freerdp.channels.urbdrc.client] - **USB request failed with 0000054f**
> [16:48:27:016] [21846:21866] [DEBUG][com.freerdp.channels.urbdrc.client] - [WRITE] URB_COMPLETION_NO_DATA            [proxy|client] [00000102] InterfaceId=40000000, MessageId=00000000, FunctionId=00000102, length=36
> [16:48:27:016] [21846:21868] [DEBUG][com.freerdp.channels.urbdrc.client] - [READ ] TRANSFER_IN_REQUEST               [proxy|server] [00000105] InterfaceId=40000005, MessageId=00000000, FunctionId=00000105, length=44
> [16:48:27:016] [21846:21868] [DEBUG][com.freerdp.channels.urbdrc.client] - URB TS_URB_CONTROL_TRANSFER[u]
> [16:48:27:017] [21846:21868] [DEBUG][com.freerdp.channels.urbdrc.client] - [WRITE] URB_COMPLETION_NO_DATA            [proxy|client] [00000102] InterfaceId=40000000, MessageId=00000000, FunctionId=00000102, length=36
> ^C[16:49:30:799] [21846:21846] [INFO][com.freerdp.utils] - Caught signal 'Interrupt' [2]

I have highlighted the CANCEL_REQUEST's that are issued when I close the serial communication on Windows. It seems they fail and I guess that - as a consequence - the USB device is not "re-assigned" to the host?

In this situation, after closing FreeRDP (`pgrep xfreerdp` shows that it is indeed stopped), the USB device shows up in the output of `lsusb`. On the other hand, `ls /dev/ttyACM0` returns nothing: the USB device is not available on the host.

    $ lsusb
    Bus 001 Device 009: ID 2e8a:000a

    $ ls /dev/ttyACM0
    ls: cannot access '/dev/ttyACM0': No such file or directory

To solve this, I have to unplug and replug the USB device. It is not that inconvenient for the Pico, while it needs rebooting to fix the issue for the integrated webcam.

I have set the following udev rules for the USB device, in the file '/etc/udev/rules.d/60-win10rdp.rules`:

    SUBSYSTEM=="usb", ATTRS{idVendor}=="2e8a", ATTRS{idProduct}=="000a", TAG+="uaccess"

**To Reproduce**
1. Redirect any USB device
2. Interact with it on the guest side (Windows)
3. Close the RDP connection
4. The redirected USB device is not accessible under Linux (host)

**Expected behavior**
USB device should be available under Linux when the connection is closed.

**Application details**
* FreeRDP version 2.2.0 (n/a)
* Output of `xfreerdp /buildconfig`: 

> Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_0_10=OFF WITH_GSTREAMER_1_0=ON WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
> Build type:          RELWITHDEBINFO
> CFLAGS:              -g -O2 -fdebug-prefix-map=/build/freerdp2-aDuEDm/freerdp2-2.2.0+dfsg1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
> Compiler:            GNU, 7.5.0
> Target architecture: x64

* OS version connecting to: Windows 10 PRO

**Environment **
 - OS: Linux (5.4.0-91-generic)
 - Version/Distribution: Ubuntu 18.04 LTS
 - Architecture: [amd64, arm]: amd64

**Comment by akallabeth** [comment]
@mp1994 this should be done in `udev_free` which calls `udev->iface.attach_kernel_driver(idev);` ( implemented in `libusb_udev_attach_kernel_driver` )
so either this is not called or your os does not claim the device after it is released by `libusb`

**Comment by mp1994** [comment]
Hi @akallabeth, thanks for your answer!
Indeed, it looks like the call to `libusb_udev_attach_kernel_driver` results in the following error (when closing the FreeRDP window instead of killing with ^C):

> [09:58:39:947] [26425:26426] [INFO][com.freerdp.client.x11] - Closed from X11
> [09:58:40:235] [26425:26426] [DEBUG][com.freerdp.channels.urbdrc.client] - libusb_attach_kernel_driver if=0: error LIBUSB_ERROR_NOT_FOUND[-5]
> [09:58:40:235] [26425:26426] [DEBUG][com.freerdp.channels.urbdrc.client] - libusb_attach_kernel_driver if=1: error LIBUSB_ERROR_NOT_FOUND[-5]
> [09:58:40:235] [26425:26426] [DEBUG][com.freerdp.channels.urbdrc.client] - libusb_attach_kernel_driver if=2: error LIBUSB_ERROR_NOT_FOUND[-5]

How can I fix this? Should I try to implement a basic `libusb` example outside of FreeRDP?

**Comment by mp1994** [comment]
So, I have been debugging a bit and studying how `libusb` works. Here is what I found. 
I started with the example found [here](https://github.com/Mathias-L/STM32F4-libusb-example/blob/master/simple/test.c).
I have set up [this GitHub repository](https://github.com/mp1994/libusb-test) with my code to improve reproducibility.

Handling the interface `0x00` works! I can claim it and then release it and the kernel driver is re-attached successfully. Note that this is achieved automatically setting `libusb_set_auto_detach_kernel_driver(handle, 1)`.
On this interface though, reading data from the USB device does not work: I get the error -7 (timeout). The RPI Pico is programmed to print over the serial port a string every second. **I am not sure whether I can read this with a bulk transfer.** Probably that is not the case. How may I test USB communication? Should I try with a different peripheral? Should I try writing to the USB device?

The USB device I'm debugging has 3 interfaces (while the integrated webcam only has 2); I guess the interesting ones are for bulk transfer (synchronous) and interrupt transfer (asynchronous). This was found parsing the output of `lsusb -d 2e8a: -v`
I tried claiming the interface `0x01` (bulk transfer): doing this results in failure of re-attaching the kernel driver, while still not being able to read data. Apparently, the interface `0x00` is the only one that can trigger a kernel driver re-attach correctly ([source](https://stackoverflow.com/a/34713347/7084591)). Here is the full log with interface `0x00`:

> [ 0.008236] [0000297f] libusb: debug [libusb_get_device_list] 
> [ 0.008313] [0000297f] libusb: debug [libusb_get_device_descriptor] 
> [ 0.008324] [0000297f] libusb: debug [libusb_get_device_descriptor] 
> [ 0.008341] [0000297f] libusb: debug [libusb_get_device_descriptor] 
> [ 0.008358] [0000297f] libusb: debug [libusb_get_device_descriptor] 
> [ 0.008366] [0000297f] libusb: debug [libusb_get_device_descriptor] 
> [ 0.008379] [0000297f] libusb: debug [libusb_get_device_descriptor] 
> [ 0.008392] [0000297f] libusb: debug [libusb_open] open 1.18
> [ 0.277634] [0000297f] libusb: debug [usbi_add_pollfd] add fd 9 events 4
> [ 0.277690] [0000297f] libusb: debug [libusb_claim_interface] interface 0
> Interface claimed
> [ 0.278387] [0000297f] libusb: debug [libusb_alloc_transfer] transfer 0x558f5a3c9340
> [ 0.278411] [0000297f] libusb: debug [libusb_submit_transfer] transfer 0x558f5a3c9340
> [ 0.278424] [0000297f] libusb: debug [add_to_flying_list] arm timerfd for timeout in 3000ms (first in line)
> [ 0.278457] [0000297f] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
> [ 0.278510] [0000297f] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
> [ 0.278535] [0000297f] libusb: debug [handle_events] poll fds modified, reallocating
> [ 0.278563] [0000297f] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
> [ 3.278506] [0000297f] libusb: debug [handle_events] poll() returned 1
> [ 3.278536] [0000297f] libusb: debug [handle_events] timerfd triggered
> [ 3.278542] [0000297f] libusb: debug [libusb_cancel_transfer] transfer 0x558f5a3c9340
> [ 3.278652] [0000297f] libusb: debug [disarm_timerfd] 
> [ 3.278677] [0000297f] libusb: debug [handle_events] poll() 3 fds with timeout in 0ms
> [ 3.278685] [0000297f] libusb: debug [handle_events] poll() returned 1
> [ 3.278693] [0000297f] libusb: debug [reap_for_handle] urb type=3 status=-2 transferred=0
> [ 3.278698] [0000297f] libusb: debug [handle_bulk_completion] handling completion status -2 of bulk urb 1/1
> [ 3.278702] [0000297f] libusb: debug [handle_bulk_completion] abnormal reap: urb status -2
> [ 3.278706] [0000297f] libusb: debug [handle_bulk_completion] abnormal reap: last URB handled, reporting
> [ 3.278711] [0000297f] libusb: debug [usbi_handle_transfer_cancellation] detected timeout cancellation
> [ 3.278719] [0000297f] libusb: debug [disarm_timerfd] 
> [ 3.278723] [0000297f] libusb: debug [usbi_handle_transfer_completion] transfer 0x558f5a3c9340 has callback 0x7f18f78b9b30
> [ 3.278733] [0000297f] libusb: debug [sync_transfer_cb] actual_length=0
> [ 3.278747] [0000297f] libusb: debug [libusb_free_transfer] transfer 0x558f5a3c9340
> ERROR in bulk read: -7
> [ 3.278763] [0000297f] libusb: debug [libusb_alloc_transfer] transfer 0x558f5a3ca650
> [ 3.278766] [0000297f] libusb: debug [libusb_submit_transfer] transfer 0x558f5a3ca650
> [ 3.278770] [0000297f] libusb: debug [add_to_flying_list] arm timerfd for timeout in 3000ms (first in line)
> [ 3.278778] [0000297f] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
> [ 3.278793] [0000297f] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
> [ 3.278798] [0000297f] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
> [ 6.278857] [0000297f] libusb: debug [handle_events] poll() returned 1
> [ 6.278893] [0000297f] libusb: debug [handle_events] timerfd triggered
> [ 6.278902] [0000297f] libusb: debug [libusb_cancel_transfer] transfer 0x558f5a3ca650
> [ 6.279048] [0000297f] libusb: debug [disarm_timerfd] 
> [ 6.279063] [0000297f] libusb: debug [handle_events] poll() 3 fds with timeout in 0ms
> [ 6.279103] [0000297f] libusb: debug [handle_events] poll() returned 1
> [ 6.279124] [0000297f] libusb: debug [reap_for_handle] urb type=3 status=-2 transferred=0
> [ 6.279140] [0000297f] libusb: debug [handle_bulk_completion] handling completion status -2 of bulk urb 1/1
> [ 6.279155] [0000297f] libusb: debug [handle_bulk_completion] abnormal reap: urb status -2
> [ 6.279170] [0000297f] libusb: debug [handle_bulk_completion] abnormal reap: last URB handled, reporting
> [ 6.279180] [0000297f] libusb: debug [usbi_handle_transfer_cancellation] detected timeout cancellation
> [ 6.279194] [0000297f] libusb: debug [disarm_timerfd] 
> [ 6.279215] [0000297f] libusb: debug [usbi_handle_transfer_completion] transfer 0x558f5a3ca650 has callback 0x7f18f78b9b30
> [ 6.279231] [0000297f] libusb: debug [sync_transfer_cb] actual_length=0
> [ 6.279245] [0000297f] libusb: debug [libusb_free_transfer] transfer 0x558f5a3ca650
> ERROR in bulk read: -7
> [ 6.279282] [0000297f] libusb: debug [libusb_alloc_transfer] transfer 0x558f5a3c75f0
> [ 6.279293] [0000297f] libusb: debug [libusb_submit_transfer] transfer 0x558f5a3c75f0
> [ 6.279302] [0000297f] libusb: debug [add_to_flying_list] arm timerfd for timeout in 3000ms (first in line)
> [ 6.279329] [0000297f] libusb: debug [submit_bulk_transfer] need 1 urbs for new transfer with length 64
> [ 6.279360] [0000297f] libusb: debug [libusb_handle_events_timeout_completed] doing our own event handling
> [ 6.279375] [0000297f] libusb: debug [handle_events] poll() 3 fds with timeout in 60000ms
> ^C
> Interrupt signal received
> [ 7.109911] [0000297f] libusb: debug [libusb_release_interface] interface 0
> 
> Interrupt signal received1
> [ 7.112137] [0000297f] libusb: debug [libusb_close] 
> [ 7.112161] [0000297f] libusb: error [do_close] Device handle closed while transfer was still being processed, but the device is still connected as far as we know
> [ 7.112179] [0000297f] libusb: error [do_close] A cancellation hasn't even been scheduled on the transfer for which the device is closing
> [ 7.112194] [0000297f] libusb: debug [do_close] Removed transfer 0x558f5a3c75f0 from the in-flight list because device handle 0x558f5a3b38c0 closed
> [ 7.112217] [0000297f] libusb: debug [usbi_remove_pollfd] remove fd 9
> 
> Interrupt signal received2
> 
> Interrupt signal received3
> [ 7.112290] [0000297f] libusb: debug [libusb_exit] 
> [ 7.112302] [0000297f] libusb: debug [libusb_exit] destroying default context
> 
> Interrupt signal received

Let me know if there is something else I can try!

**Comment by akallabeth** [comment]
@mp1994 ok, thank you. but I don´t have access to your github repo ;)

**Comment by mp1994** [comment]
Ah, yeah, it was set to private. Now I have changed the visibility and made it public! 

> As for data transfer, that is not really required for the sample, only the detach/reattach of different configurations should suffice.

Ok, great. Let me know if I can do anything else!
