### ISSUE TITLE
[WIN] wFreeRDP 2.4.1  Redrawing issues with scrollarea

### ISSUE THREAD

**Issue by bxwpz** [FreeRDP/FreeRDP#7529]
**Describe the bug**

When dragging the scroll bar to the far right, right clicking on the desktop will not display the pop-up menu correctly

wFreeRDP 2.4.1 on windows10 .

https://user-images.githubusercontent.com/19303845/148665741-63803427-85f1-4e88-948d-c7f9bd2c4968.mp4

**Screenshots**
![image](https://user-images.githubusercontent.com/19303845/148665843-65e37560-a4a4-41f0-81e5-c5adb1bdc9ed.png)

_Thank you for reporting a bug!_

**Comment by akallabeth** [comment]
do you use `remote app/rails` mode or a desktop session?

**Comment by bxwpz** [comment]
I'm not  use remote app/rails mode or a desktop session.
Just like:
E:\_GIT\freerdp-2.0.0\0build\Debug\wfreerdp.exe /v:42.51.5.9:10086 /u:administrator /p:asdf33333 /w:1020 /h:760

**Comment by akallabeth** [comment]
Ok, reproduced:
1. The client must have scroll areas enabled, e.g. view is smaller than the desktop session
2. Drawing updates near the edge of the view do not properly refresh the whole changed area
