### ISSUE TITLE
freerdp_connect Set timeout

### ISSUE THREAD

**Issue by Doraemon959d** [FreeRDP/FreeRDP#7531]
I'm calling freerdp_connect During, if the target host does not return normal results, it will be blocked all the time. Can you set a timeout so that the function will return the result of connection failure after timeout

**Comment by akallabeth** [comment]
english please? Sorry, I don´t understand what you´re trying to ask.

**Comment by Doraemon959d** [comment]
I use freerdp in your API interface_ Connect method，When the host does not return normally, the function will block. I hope to set a timeout so that the function can exit normally.

**Comment by akallabeth** [comment]
you mean `freerdp_connect`?
you can set `FreeRDP_TcpConnectTimeout` in `rdpSettings` 
default should be `15 seconds`

**Comment by Doraemon959d** [comment]
The freerdp version I currently install in CentOS is 2.1.1. It seems that this option is not available. Can I set the timeout by updating to the latest version?

**Comment by akallabeth** [comment]
If you are on stable, you need commit 2a91afb0cf1be3ad765da11329ed0e5333da0bdc

**Comment by Doraemon959d** [comment]
Thank you for your answer!

**Comment by Doraemon959d** [comment]
I installed freerdp for 2.5.0, and then I tried to set the timeout to 1 second, but the function didn't end in a second.
![image](https://user-images.githubusercontent.com/46038802/149880429-be2d8198-3402-4a7e-9bd4-70740aa994ec.png)
![image](https://user-images.githubusercontent.com/46038802/149880462-7339afea-8fae-42ea-91ff-205946bc5e2c.png)

**Comment by akallabeth** [comment]
@Doraemon959d the variable unit is `ms` (milli seconds) and that works quite nice here with 2.5.0 (although you can´t set it from command line)

**Comment by Doraemon959d** [comment]
@akallabeth 
![image](https://user-images.githubusercontent.com/46038802/150044139-df3870de-9a82-4714-b180-c66d8fc7aeb3.png)
![image](https://user-images.githubusercontent.com/46038802/150044217-2cc8b05d-c398-43f8-8530-b4bac4852e2b.png)

But when I use the program to call it, there is no normal timeout. The program I use is https://github.com/vanhauser-thc/thc-hydra , after printing Hello, no word is printed after 1 second. I want to know how to set it.

**Comment by akallabeth** [comment]
@Doraemon959d try the sample client, add the line in `tf_pre_connect` and check.
looks like your init code does not properly set up the connection. (why do you have `hello` printed twice?)

**Comment by Doraemon959d** [comment]
In this case, it only occurs when the target server is installed with anti-virus software. Other situations can return normally. Printing multiple times hello is because there are multiple threads.

**Comment by Doraemon959d** [comment]
Is there a problem with calling the program like this? Why is an error reported?
![image](https://user-images.githubusercontent.com/46038802/150311556-d8a860d5-d64f-4cf7-9c1f-ee5c438f213f.png)

#include <stdio.h>
#include <freerdp/freerdp.h>

BOOL rdp_connect() {
    freerdp *instance;
    int32_t err=0;
    UINT32 port=3389;
    instance->settings->ServerPort = port;
    char* server="123";
    instance->settings->ServerHostname = server;
    char* login="administrator";
    char* password="test123";
    instance->settings->Username = login;
    instance->settings->Password = password;
    instance->settings->IgnoreCertificate = TRUE;
    instance->settings->AuthenticationOnly = TRUE;
    char* domain="192.168.5.45";
    instance->settings->Domain = domain;
    instance->settings->MaxTimeInCheckLoop = 100;
    instance->settings->TcpConnectTimeout = 1000;
    printf("hello\n");
    freerdp_connect(instance);
    printf("word\n");
    err = freerdp_get_last_error(instance->context);
    printf(err+"\n");
    return TRUE;
}



int main(){
    printf("Hello, World!\n");

    rdp_connect();
    return 0;
}

**Comment by akallabeth** [comment]
Please check the sample client and do not use an issue as help thread.
Provide some link (git repo?) and use our chat for such stuff ;)
See freerdp.com for details.
