### ISSUE TITLE
Advanced Mouse Input channel

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#7560]
During a discussion with @pnowack we´ve found something missing from the RDP core spec.
There is no (proper) way to send relative mouse input.

While the perfect approach would be to extend `[MS-RDPBCGR]` that might take too long to get accepted.

For the time being I´d propose a dynamic channel instead.
That would have the following properties:

1. Automatically loaded by `FreeRDP` based clients and used instead of mouse PDU if the server supports and opens it.
2. A module for windows RDP servers could be written reading the channel data and inserting it as mouse event using `SendInput`
3. `xrdp`, `ogon` and `gnome remote desktop` could implement it as well. Ogon might even be able to utilize the protocol parsing part of `FreeRDP` and only implement the actual backend mouse event injection

So, todo:
1. Implement a sample channel
2. Inform upstream of https://github.com/neutrinolabs/xrdp , https://github.com/ogon-project/ogon-project , https://gitlab.gnome.org/GNOME/gnome-remote-desktop , TODO: Who else? to also implement this

@pnowack @mfleisz @bmiklautz @hardening  what do you think, anything I missed?

**Comment by hardening** [comment]
Just a hint: if you plan to implement the channel for windows (server side), do not use winPR for WTS API as it's totally buggy for dynamic channels.

**Comment by akallabeth** [comment]
@hardening you can be sure we´re not trying to use that. Maybe it would even be better to implement that in `rust` (as MS is supporting that quite well and it is definitely nicer than the old C API)

**Comment by pnowack** [comment]
My general approach here would be to still have a capability exchange, as that would allow us to do changes in the future, if needed.

What I currently have in mind is the following approach (for capability exchange):
- The server side initiates the channel (unlike the graphics pipeline, where the client side starts with CapsAdvertise)
- The server sends, like the client side in the graphics pipeline, capability sets. These ones can have a variable length, where the length is specified in the header. (Unsupported capability sets will be skipped by a peer (via its length)).
- The capability sets don't have their own PDU type, but a PDU subtype (Type is capability set, subtype is the version of the capability set).
Reason is that we don't pollute the PDU types themselves with capability sets, in case of we add other PDUs for functionality later (and with that further capability sets).
- PDUs are versioned (have a suffix of e.g. _v1 for version 1)

For the PDUs, there will be one RelativeMouseInput_v1 PDU:
- Argument 1: `dx`: relative mouse motion in the x component
- Argument 2: `dy`: relative mouse motion in the y component

In mutters API (for gnome-remote-desktop), we use `double` for these values, but if we agree to use `UINT32` instead for the dynamic channel, that should be fine too, I think (, in case of `double` being unsuitable for clients or other servers).

**Comment by akallabeth** [comment]
@pnowack sorry, did miss your comment.
Already done some work in #7562 .
I´d skip capabilities and simply send a version from client and server (use semantic versioning to define what is available). Much simpler. (TBD in the pr)
