### ISSUE TITLE
Getting event 1111 error in server 2019 when using xfreerdp with printer driver specified

### ISSUE THREAD

**Issue by GavinDixon69** [FreeRDP/FreeRDP#7629]
Using this command on Mac Monterey
xfreerdp /u:xxxx /p:yyyy /v:13.239.82.109 /printer:HP_Color_LaserJet_Pro_MFP_M177fw,”HP\ Color\ LaserJet\ Pro\ MFP\ M177\ PCLmS” /client-hostname:mymac

Redirected printer not created

Seeing this error in event viewer:
Driver ”HP Color LaserJet Pro MFP M177 PCLmS” required for printer HP_Color_LaserJet_Pro_MFP_M177fw is unknown

If I log on to same server using WIndows 10 PC I see this redirected printer "HP Color LaserJet Pro MFP M177 PCLmS (redirected 6)" with driver "HP Color LaserJet Pro MFP M177 PCLmS" so the printer driver clearly exists on the server.

If I remove the printer driver option in the xfreerdp command a redirected printer is created with MS Publisher Imagesetter driver

Any suggestions?

Thank you

**Comment by akallabeth** [comment]
the quotes in your command line look wrong.
That, and that you need to escape spaces indicate you use some other unicode symbol instead of plain quotes
