### ISSUE TITLE
cannot connect to win11 ERRINFO_CLOSE_STACK_ON_DRIVER_IFACE_FAILURE

### ISSUE THREAD

**Issue by MarioIvancic** [FreeRDP/FreeRDP#7630]
Hello all.
I tried to connect to win11 box using command line xfreerdp /u: /p: /v: and after that failed xfreerdp /u: /p: /cert:ignore /v:.
I get the same error in both cases: ERRINFO_CLOSE_STACK_ON_DRIVER_IFACE_FAILURE
In tcp dump I see TLS is established and disconected soon after it.
I am using FreeRDP version 2.2.0 on Linux Mint 20.3 xfce
From win7 box I'm able to connect to the same win11 box.
I don't really know is this a bug or I'm doing something wrong but any help is welcomed.
Thank you,
Mario

**Comment by akallabeth** [comment]
This is a error message sent from the server. Something is ill configured there.
you may have success using `/network:auto`, `/rfx` or `/gfx` options (they trigger the use of a different graphics path server side)
