### ISSUE TITLE
ERROR when opening Websites with big images

### ISSUE THREAD

**Issue by UniC0re** [FreeRDP/FreeRDP#7631]
Hello,

im getting this Error when opening Websites with big images.. can someone help me solve this problem?

Thanks!

ERRINFO_GRAPHICS_SUBSYSTEM_FAILED (0x0000112F):The server-side graphics subsystem is in an
error state and unable to continue graphics encoding.
FreeRDP's Exitcode: 32
ErrorLevel: 32

**Comment by akallabeth** [comment]
your server does not support the resolution you use locally.
You might work around it by forcing specific graphic modes (try combinations of `/rfx`, `/gfx`, `/gfx:rfx` or `/gfx:avc444`)
