### ISSUE TITLE
when I use /admin and /shell:"cmd /c ipconfig" param in freerdp, /shell can not run.

### ISSUE THREAD

**Issue by cnxieyang** [FreeRDP/FreeRDP#7651]
when I use /admin and /shell:"cmd /c ipconfig" param in xfreerdp, /shell can not run
if remove /admin, It can run,
I want to know ,is it a bug?

**Comment by akallabeth** [comment]
no, `/admin` is a flag that changes the remote end (e.g. starts a `administrative` session which has limitations)
