### ISSUE TITLE
ndk:No such file or directory

### ISSUE THREAD

**Issue by nobodycan** [FreeRDP/FreeRDP#7656]
When I tried to use the FreeRDP of Android,I follow the docs, but some errors happened.
I use Mac OS 10.15.7,and the command line is ./scripts/android-build-freerdp.sh --ndk /Users/Tom/Library/Android/sdk/ndk/android-ndk-r15c --sdk /Users/Tom/Library/Android/sdk 
the error happens
./scripts/android-build-common.sh: line 71: -DANDROID_NDK=/Users/Tom/Library/Android/sdk/ndk/android-ndk-r15c: No such file or directory
[ERROR] -DANDROID_NDK=/Users/Tom/Library/Android/sdk/ndk/android-ndk-r15c -DANDROID_NATIVE_API_LEVEL=android-26 -DCMAKE_TOOLCHAIN_FILE=/Users/Tom/Library/Android/sdk/ndk/android-ndk-r15c/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=/Users/linzetian/Downloads/FreeRDP-master/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_MAKE_PROGRAM=make -DWITH_JPEG=OFF -DWITH_OPENH264=OFF -DWITH_FFMPEG=OFF -DANDROID_ABI=armeabi-v7a -DCMAKE_INSTALL_PREFIX=/Users/Tom/Downloads/FreeRDP-master/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a -DCMAKE_INSTALL_LIBDIR=. /Users/linzetian/Downloads/FreeRDP-master/scripts/.. retured 127
And I have tried different FreeRDP versions and different ndk versions, but all of them failed.

**Comment by akallabeth** [comment]
There are some issues with `bash` and `find` from mac os.
We´re mainly using the script on linux, but pull requests are welcome.

**Comment by nobodycan** [comment]
> 

I‘will try with Linux.Thanks!

**Comment by akallabeth** [comment]
@nobodycan ok, found the problem, but not that easy to solve: https://stackoverflow.com/questions/4458120/search-for-executable-files-using-find-command
