### ISSUE TITLE
dfreerdp

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#766]
hi,
     i am using dfreerdp.when i am trying to connect with dfreerdp to my windows VM like 
dfreerdp -u username -d domain --no-nla --no-tls --rfx ipaddress 
the remote  session is not connected and the keyboard is getting hanged.For that i have to restart my system again.
It is panic  to restart the system again and again.can anyone suggest me what to do.

**Comment by bmiklautz** [comment]
dfreerdp isn't maintained since a while and no further development was done since a while.
See   4d47514428536054d4676610a6bd554193610730 for details.
