### ISSUE TITLE
I can't copy the file to the server via the clipboard

### ISSUE THREAD

**Issue by chang1532** [FreeRDP/FreeRDP#7675]
I connect to the windows server through freerdp, using freerdp as a proxy, I use the code from the mater branch, when I update to this commit 4e6e5be6545a2be891005872a2844a29264b017b, I can't copy the file to the server via the clipboard, I don't know what happened。

Git commit: 4e6e5be6545a2be891005872a2844a29264b017b

SHA-1: 4e6e5be6545a2be891005872a2844a29264b017b

* Added proxy intercept channels

* New configuration to intercept certain channels
* Added rdpdr intercept implementation

**Comment by chang1532** [comment]
2022/02/26 10:06:17 [10:05:37:719] [2628494:2628494] [INFO][proxy.server] - freerdp-proxy version info:
2022/02/26 10:06:17 [10:05:37:719] [2628494:2628494] [INFO][proxy.server] -     FreeRDP version: 3.0.0-dev
2022/02/26 10:06:17 [10:05:37:719] [2628494:2628494] [INFO][proxy.server] -     Git commit: n/a
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] - Proxy configuration:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Server:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Host: 0.0.0.0
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Port: 3389
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Target:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             TargetHost: CustomHost
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             TargetPort: 3389
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Input:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Keyboard: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Mouse: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Multitouch: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Server Security:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ServerTlsSecurity: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ServerRdpSecurity: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Client Security:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ClientNlaSecurity: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ClientTlsSecurity: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ClientRdpSecurity: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ClientAllowFallbackToTls: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Channels:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             GFX: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             DisplayControl: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Clipboard: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             AudioOutput: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             AudioInput: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             DeviceRedirection: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             VideoRedirection: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             CameraRedirection: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             RemoteApp: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             PassthroughIsBlacklist: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Clipboard:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             TextOnly: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     GFXSettings:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             DecodeGFX: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Plugins/Modules:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Modules[x]: xrdp
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Plugins/Required:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             RequiredPlugins[x]: xrdp
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Certificates:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             CertificateFile: server.crt
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             CertificateContent: (nil)
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             PrivateKeyFile: server.key
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             PrivateKeyContent: (nil)
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             RdpKeyFile: rdp.key
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             RdpKeyContent: (nil)
2022/02/26 10:06:17 [10:05:37:722] [2628494:2628494] [INFO][proxy.modules] - Loaded plugins:
2022/02/26 10:06:17 [10:05:37:722] [2628494:2628494] [INFO][proxy.modules] -    Name: xrdp
2022/02/26 10:06:17 [10:05:37:722] [2628494:2628494] [INFO][proxy.modules] -    Description: this is a tencent plugin for bh
2022/02/26 10:06:17 [10:05:37:724] [2628494:2628494] [INFO][com.freerdp.core.listener] - Listening on [0.0.0.0]:3389
2022/02/26 10:06:18 [10:06:17:275] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_handle_peer]: new connection: proxy address: 0.0.0.0, client address: 10.99.17.133
2022/02/26 10:06:18 [10:06:17:285] [2628494:2629068] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
2022/02/26 10:06:18 [10:06:17:285] [2628494:2629068] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:0
2022/02/26 10:06:18 [10:06:17:285] [2628494:2629068] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
2022/02/26 10:06:18 [10:06:17:341] [2628494:2629068] [INFO][proxy.modules.xrdp] - server_peer_logon: 0
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] - Accepted client: XIAOZHCHAN-NB1
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] - Accepted channels:
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] -  rdpdr
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] -  rdpsnd
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] -  cliprdr
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] -  drdynvc
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.gcc] - Active rdp encryption level: NONE
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.gcc] - Selected rdp encryption method: NONE
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted client: XIAOZHCHAN-NB1
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted channel: rdpdr
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted channel: rdpsnd
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted channel: cliprdr
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted channel: drdynvc
2022/02/26 10:06:18 [10:06:18:500] [2628494:2629068] [INFO][proxy.modules.xrdp.session] - url:http://127.0.0.1:8008/QueryTicket, ticket:0ae38eac4b110a891bfe439ec58a91b27f870c02442f32ea5b38609cc72eddf20abe166d9858esz2
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629068] [INFO][proxy.modules.xrdp] - session_id:18db1bb266cdddd5bca280e5733d46610000090042554, user:xiaozhchang use ticket data passwd to 9.134.184.65
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629068] [INFO][proxy.modules.xrdp] - rdp proxy,session:18db1bb266cdddd5bca280e5733d46610000090042554 not set proxy
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: remote target is 9.134.184.65:3389
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629068] [INFO][proxy.modules.xrdp] - server_post_connect
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629068] [INFO][proxy.modules.xrdp] - server_peer_activate
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][proxy.modules.xrdp] - client_init_connect
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][proxy.client] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_client_connect]: connecting using client info: Username: administrator, Domain: (nil)
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][proxy.client] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_client_connect]: connecting using security settings: rdp=1, tls=1, nla=1
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][proxy.client] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_client_pre_connect]: Loading addins
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - channel_create: rdpdr
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - channel_create: rdpsnd
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - channel_create: cliprdr
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - channel_create: drdynvc
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - client_pre_connect

**Comment by chang1532** [comment]
2022/02/26 10:06:17 [10:05:37:719] [2628494:2628494] [INFO][proxy.server] - freerdp-proxy version info:
2022/02/26 10:06:17 [10:05:37:719] [2628494:2628494] [INFO][proxy.server] -     FreeRDP version: 3.0.0-dev
2022/02/26 10:06:17 [10:05:37:719] [2628494:2628494] [INFO][proxy.server] -     Git commit: n/a
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] - Proxy configuration:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Server:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Host: 0.0.0.0
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Port: 3389
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Target:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             TargetHost: CustomHost
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             TargetPort: 3389
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Input:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Keyboard: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Mouse: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Multitouch: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Server Security:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ServerTlsSecurity: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ServerRdpSecurity: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Client Security:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ClientNlaSecurity: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ClientTlsSecurity: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ClientRdpSecurity: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             ClientAllowFallbackToTls: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Channels:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             GFX: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             DisplayControl: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Clipboard: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             AudioOutput: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             AudioInput: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             DeviceRedirection: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             VideoRedirection: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             CameraRedirection: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             RemoteApp: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             PassthroughIsBlacklist: TRUE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Clipboard:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             TextOnly: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     GFXSettings:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             DecodeGFX: FALSE
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Plugins/Modules:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             Modules[x]: xrdp
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Plugins/Required:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             RequiredPlugins[x]: xrdp
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -     Certificates:
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             CertificateFile: server.crt
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             CertificateContent: (nil)
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             PrivateKeyFile: server.key
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             PrivateKeyContent: (nil)
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             RdpKeyFile: rdp.key
2022/02/26 10:06:17 [10:05:37:720] [2628494:2628494] [INFO][proxy.config] -             RdpKeyContent: (nil)
2022/02/26 10:06:17 [10:05:37:722] [2628494:2628494] [INFO][proxy.modules] - Loaded plugins:
2022/02/26 10:06:17 [10:05:37:722] [2628494:2628494] [INFO][proxy.modules] -    Name: xrdp
2022/02/26 10:06:17 [10:05:37:722] [2628494:2628494] [INFO][proxy.modules] -    Description: this is a tencent plugin for bh
2022/02/26 10:06:17 [10:05:37:724] [2628494:2628494] [INFO][com.freerdp.core.listener] - Listening on [0.0.0.0]:3389
2022/02/26 10:06:18 [10:06:17:275] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_handle_peer]: new connection: proxy address: 0.0.0.0, client address: 10.99.17.133
2022/02/26 10:06:18 [10:06:17:285] [2628494:2629068] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
2022/02/26 10:06:18 [10:06:17:285] [2628494:2629068] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:0
2022/02/26 10:06:18 [10:06:17:285] [2628494:2629068] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
2022/02/26 10:06:18 [10:06:17:341] [2628494:2629068] [INFO][proxy.modules.xrdp] - server_peer_logon: 0
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] - Accepted client: XIAOZHCHAN-NB1
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] - Accepted channels:
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] -  rdpdr
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] -  rdpsnd
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] -  cliprdr
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.connection] -  drdynvc
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.gcc] - Active rdp encryption level: NONE
2022/02/26 10:06:18 [10:06:17:412] [2628494:2629068] [INFO][com.freerdp.core.gcc] - Selected rdp encryption method: NONE
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted client: XIAOZHCHAN-NB1
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted channel: rdpdr
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted channel: rdpsnd
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted channel: cliprdr
2022/02/26 10:06:18 [10:06:18:499] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: Accepted channel: drdynvc
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629068] [INFO][proxy.server] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_server_post_connect]: remote target is 9.134.184.65:3389
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629068] [INFO][proxy.modules.xrdp] - server_post_connect
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629068] [INFO][proxy.modules.xrdp] - server_peer_activate
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][proxy.modules.xrdp] - client_init_connect
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][proxy.client] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_client_connect]: connecting using client info: Username: administrator, Domain: (nil)
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][proxy.client] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_client_connect]: connecting using security settings: rdp=1, tls=1, nla=1
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][com.freerdp.core] - freerdp_connect:freerdp_set_last_error_ex resetting error state
2022/02/26 10:06:18 [10:06:18:505] [2628494:2629069] [INFO][proxy.client] - [SessionID=492D78DE7938EFC361D809739E73FD09][pf_client_pre_connect]: Loading addins
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - channel_create: rdpdr
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - channel_create: rdpsnd
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - channel_create: cliprdr
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - channel_create: drdynvc
2022/02/26 10:06:18 [10:06:18:506] [2628494:2629069] [INFO][proxy.modules.xrdp] - client_pre_connect

**Comment by chang1532** [comment]
It was normal before, do I need to add any new configuration?

My configuration is as follows：

[Server]
Host = 0.0.0.0
Port = 3389

[Target]
; If this value is set to TRUE, the target server info will be parsed using the 
; load balance info setting at runtime. The format is
; "Cookie: msts=<target server>", and can be set in an rdp file for windows/mac,
; and the /load-balance-info: CLI option for xfreerdp. Otherwise, the server
; will always connect to the same target, using the configured values of `Host`
; and `Port`.
FixedTarget = TRUE
Host = CustomHost
Port = 3389

[Input]
Mouse = TRUE
Keyboard = TRUE

[Security]
ServerTlsSecurity = TRUE
ServerRdpSecurity = FALSE
ClientTlsSecurity = TRUE
ClientRdpSecurity = TRUE
ClientNlaSecurity = TRUE
ClientAllowFallbackToTls = FALSE

[Channels]
GFX = TRUE
DisplayControl = TRUE
Clipboard = TRUE
AudioOutput = TRUE
RemoteApp = FALSE
; a list of comma seperated static channels that will be proxied. This feature is useful,
; for example when there's a custom static channel that isn't implemented in freerdp/proxy, and is needed to be proxied when connecting through the proxy.
; Passthrough = "rdpdr"
PassthroughIsBlacklist = TRUE

[Certificates]
CertificateFile=server.crt
PrivateKeyFile=server.key
RdpKeyFile=rdp.key

[Clipboard]
TextOnly = FALSE
MaxTextLength = 0 # 0 for no limit.

[GFXSettings]
DecodeGFX = FALSE

[Plugins]
; An optional, comma separated list of paths to modules that the proxy should load at startup.
;
Modules = "xrdp"

; An optional, comma separated list of required plugins (names),
; that the proxy won't start without having them loaded.
;
Required = "xrdp"

**Comment by chang1532** [comment]
in pf_client.c
static BOOL sendQueuedChannelData(pClientContext* pc)

I revert changes，Change SendChannelData to SendChannelPacket，
I found that I can use the clipboard to copy files normally
Is there something I haven't noticed

**Comment by akallabeth** [comment]
@chang1532 thanks for the report, added to my backlog.
