### ISSUE TITLE
Is supported window auto size?

### ISSUE THREAD

**Issue by wangxiaoyan369** [FreeRDP/FreeRDP#7685]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by akallabeth** [comment]
please elaborate, I do not understand what you are asking for.

**Comment by phonixivan** [comment]
When I narrow or enlarge the window, the resolution can be adaptive

**Comment by phonixivan** [comment]
> When I narrow or enlarge the window, the resolution can be adaptive

Does it support this function?

**Comment by akallabeth** [comment]
Sorry, your question is still too vague.
Here a few hints that might help:
1. Which client? We have a couple of clients for different systems (windows/X11/mac/android/...)
2. Did you check the help output of your client (just run without arguments)?
