### ISSUE TITLE
Disable tls

### ISSUE THREAD

**Issue by EightLegs** [FreeRDP/FreeRDP#7688]
Is there any way to disable network traffic encryption (tls and so on) in order to watch and inspect network traffic? Tried changing registry files and using command line arguments but it didn't work

**Comment by akallabeth** [comment]
no. you can dump traffic in `xfreerdp` though or do the same on `freerdp-proxy`

**Comment by hardening** [comment]
If you wanna see in clear the RDP traffic, another possibility is to lower the crypto settings on the server to disable ciphers with PFS (somewhere in the registry in `SChannel` directory) and then set your own certificate/key. Invoking FreeRDP with lowered SSL parameters and Wireshark (at least last versions) shall be able to decrypt and interpret pretty well the traffic.
