### ISSUE TITLE
freerdp crash on autoreconnect

### ISSUE THREAD

**Issue by Fantu** [FreeRDP/FreeRDP#7695]
Connecting to a windows 10 after some minutes (or also more time, like one hour) disconnect (for issue server side seems) and on autoreconnect it crash.
Here the terminal output, latest lines probably can be useful, and backtrace: https://paste.debian.net/1232894/
I don't know if can be related but I spotted this trying to solve/workaround/debug another issue that make me going crazy recently: occasional disconnections from the windows 2019 terminal servers, it happens only on some servers (and also on clients with 2 servers "twins on one happens and on one does not"). No crash in that case and no useful info client side. Any help to debug is appreciated.

**Application details**
* FreeRDP version 2.6.0
* Command line used: launched from remmina
* OS version connecting to (server side): windows 10 pro v2004 build 19041.1415
* custom build based on debian packages: http://debomatic-armhf.debian.net/distribution#dpr-tc-buster-backports https://github.com/M2Rbiz/freerdp2-pkg https://github.com/M2Rbiz/remmina-pkg

**Environment (please complete the following information):**
 - OS: linux
 - Version/Distribution: Debian 10
 - Architecture: armhf
 - hardware: raspberry 4b

**Comment by akallabeth** [comment]
This looks like you´ve encountered a bug in `rdpsnd` channel cleanup code.
I´m surprised this was not discovered sooner, it is there for ages now (`2.1.0`)

1. The `dynamic` channel version creates a background thread decoding data with the events `CHANNEL_EVENT_INITIALIZED` and cleans them up with `CHANNEL_EVENT_TERMINATED`
The context variables are created in `CHANNEL_EVENT_CONNECTED` and cleaned up in `CHANNEL_EVENT_DISCONNECTED` This is a recipe for headaches.
1. There is also a `static` channel version which shares the context. Cleanup is done in a different function. This needs proper guards and variable invalidation, which is missing/only partly there.

**Comment by akallabeth** [comment]
@Fantu I´ve created a backport pull request #7698 which should address this. Can you confirm?
