### ISSUE TITLE
Aborting connection in the middle of creating a connection doesn't work

### ISSUE THREAD

**Issue by eronnen** [FreeRDP/FreeRDP#7696]
When calling `freerdp_abort_connect` it sets the `abortEvent` event, but there is a possible flow in the `freerdp_connect` function where it calls `freerdp_reconnect` which resets the `abortEvent` event. 
This means that if I call `freerdp_abort_connect` before the `freerdp_reconnect` function is being called inside `freerdp_connect` - then the connection will not be aborted.

**Comment by akallabeth** [comment]
@eronnen is this a theoretical analysis or did you run into that situation?
`freerdp_reconnect ` is only called on `FREERDP_ERROR_CONNECT_TRANSPORT_FAILED` (which happens if the network/ssl layer has some issue, connection loss, timeout, ...)

**Comment by eronnen** [comment]
Yes i have ran it and the connection was initiated after calling `freerdp_abort_connect`, although Im not sure why `freerdp_reconnect` was called, maybe because Im ignoring the crtificate or just bad connection
