### ISSUE TITLE
RDP through an http proxy that does not support socks5

### ISSUE THREAD

**Issue by rvigliotti-sf** [FreeRDP/FreeRDP#7723]
I am attempting to connect to a RDP host through a HTTP Public Proxy and from the xfreerdp manual it says I need to specify `socks5://` instead of `http:// `when attempting to connect to a HTTP proxy, but I've been told the proxy I'm connecting through does not support `socks5` - is there a way to force `xfreerdp` to use http proxies that uses `HTTP CONNECT` instead of `SOCKS` ? Thanks!

`This is FreeRDP version 2.1.1 (n/a)`

**Comment by akallabeth** [comment]
Which manual are you referring to? Here is help output for `xfreerdp`:
```
/proxy:[<proto>://][<user>:<password>@]<host>:<port>
                                      Proxy settings: override env. var (see
                                      also environment variable below). Protocol
                                      "socks5" should be given explicitly where
                                      "http" is default.
```

**Comment by rvigliotti-sf** [comment]
@akallabeth I'm referring to that manual, correct

**Comment by akallabeth** [comment]
@rvigliotti-sf please add some log, your usage of `crash` indicates you mean something different.
Also note that `2.1.1` is a very old release of the `2.0` series.

**Comment by rvigliotti-sf** [comment]
This is using SOCKS5

![image](https://user-images.githubusercontent.com/64626085/158159065-3fac18c4-a0af-47fc-8cb8-b2c4466c9815.png)

This is using HTTP (thats what I mean by crash)

![image](https://user-images.githubusercontent.com/64626085/158159321-6e01524f-3415-4890-8faf-ea277e822d94.png)

**Comment by akallabeth** [comment]
@rvigliotti-sf ok. You tried a newer release already? (there were 10 bugfix releases in between)

**Comment by rvigliotti-sf** [comment]
@akallabeth not yet, I will update this one once I've updated - thanks!

**Comment by akallabeth** [comment]
@rvigliotti-sf also please note for asking questions please contact us on matrix/irc first, it might already be answered elsewhere. (see https://freerdp.com for addresses)
