### ISSUE TITLE
Windows 11: missing taskbar, screen flickering

### ISSUE THREAD

**Issue by thecrazyonestherebels** [FreeRDP/FreeRDP#7724]
There are few issues after connecting to a Win 11 machine (fresh user session) through the RDP. Looks like they all have the same root cause:
- Taskbar is missing
- Mouse cursor shows progress indicator every ~3 seconds
- The OS is not hang completely, but it’s hard to open some app, everything lagging
- Screen flickering (screen flashes synced with the progress circle on mouse cursor).

<img width="1666" alt="Screen Shot 2022-03-09 at 15 44 53" src="https://user-images.githubusercontent.com/41958166/158178194-cd4c2f4f-0be9-4307-bb37-0bc7f7023beb.png">

## Environment

**Client**: FreeRDP client v2.3.0 - v2.5 (Mac, iOS, Android all have the same issue)
**Target machine**: Windows 11 from the very beginning beta versions till the most recent updates.

Notes:

Issue is not observed with the **MSTSC** client for Windows OS. If start a fresh RDP session (previously user was logged off) everything works fine. 
And even if reconnect to this session from a FreeRDP client it continue to work fine without the above problems.
But, once you start a fresh session from the FreeRDP client it’s “broken” and even if reconnect from the MSTSC same behaviour remains till the log off.

**Microsoft Remote Desktop client for macOS** v10.6.* has the same problem as FreeRDP clients. But, on the fresh version v10.7.* issue is gone.
⚠️ It could indicate that fix is somewhere on the client side (especially that there is no fixes from Windows 11 updates).

## Workaround

Somehow this behaviour relates to the client time zone.

Issue is not observed if disable the fEnableTimeZoneRedirection policy on the target VM.

Issue occurs whenever the RDP client includes the clientTimeZone ([TS_TIME_ZONE_INFORMATION](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/526ed635-d7a9-4d3c-bbe1-4e3fb17585f4) structure) within the [Extended Info Packet](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/05ada9e4-a468-494b-8694-eb806a0ecc89) ([TS_EXTENDED_INFO_PACKET](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/05ada9e4-a468-494b-8694-eb806a0ecc89)). Issue is not reproduced if comment the optional clientTimeZone field.

**Notes from research**:

- If manually check the time zone on the RDP host after connection it shows the correct time zone which was sent from the client. It means that server was able to handle it.
- Even if set the same time-zone on the RDP host and client we can reproduce the issue.
- Tried to add optional dynamicDSTTimeZoneKeyName and dynamicDaylightTimeDisabled fields in the Extended Info Packet (TS_EXTENDED_INFO_PACKET), but it also doesn’t help. Maybe I did something wrong.
- Also, tried different rdp_settings (performance, rendering, etc) but it doesn’t affect the behaviour. So, it’s definitely not a rendering / gfx issue.
- Also, didn't notice any protocol changes (e.g. from MS-RDPBCGR)

**Comment by akallabeth** [comment]
@thecrazyonestherebels ok, that is indeed some valuable information.
Could you check with `xfreerdp`, `wfreerdp` or whatever client fits the os you use anyway? (just to be sure we are chasing a problem in `FreeRDP` and not client side code)

**Comment by akallabeth** [comment]
@thecrazyonestherebels ok. the log is interesting, there seems to be something new in the protocol.
could you also check if `/network:auto` (default for newer versions) changes something?

**Comment by thecrazyonestherebels** [comment]
@akallabeth, ` /network:auto` has no effect.

Regarding the error:
`[15:46:11:274] [19571:01a23000] [WARN][com.freerdp.core.rdp] - pduType PDU_TYPE_DATA not properly parsed, 562 bytes remaining unhandled. Skipping.`
I did some debugging and "problematic" packet is `[DATA_PDU_TYPE_SAVE_SESSION_INFO][->INFO_TYPE_LOGON_LONG]`. According to the spec everything is fine but packet length which we read from the TS_SHARECONTROLHEADER is too long.
Anyways, packet is parsed and handled properly (rdp_recv_logon_info_v2 reads correct data). Just a weird packet length.

How this can be related to client time zone? As I mentioned, disabling the fEnableTimeZoneRedirection on target machine is a workaround. Same as skip the optional clientTimeZone from sending from the client.

**Comment by akallabeth** [comment]
@thecrazyonestherebels I´ve added a proper warning message for this unparsed thing on master with #7728 that might shed some light on that. (it is another message type that we do not handle, it is most likely not the one you think it is)
As for `fEnableTimeZoneRedirection` we still have not ruled out some server side bugs ;)

**Comment by akallabeth** [comment]
@thecrazyonestherebels ok, now that is strange, I´ve been made available a windows 11 test VM and I can connect without any graphical issues at all.
(used `master` and standard debian 11 installed `xfreerdp`)

**Comment by thecrazyonestherebels** [comment]
@akallabeth wow, could you please check the Windows build version? 
I'm on 22000.527 from 2022-02-15, but it seems there is a new update from 8th of March.

BTW, it's important for the issue to start a fresh session. Can you connect from the FreeRDP client to a fresh session after reboot? Do you see the taskbar ?
<img width="967" alt="Screen Shot 2022-03-17 at 13 49 13" src="https://user-images.githubusercontent.com/41958166/158811915-6ff06857-c2b9-4d68-a874-8c8657c9876c.png">

**Comment by thecrazyonestherebels** [comment]
> @thecrazyonestherebels I´ve seen this too, written a mail to microsoft about that, maybe we get some feedback.
So you also can reproduce the missed taskbar? 

Just checked on `22000.556` - same behaviour.

We also raised an issue with Microsoft. But so far MS just fixed their RDP client for macOS so it doesn't have this issue anymore :)

**Comment by akallabeth** [comment]
@thecrazyonestherebels no, I can connect just fine and have a normal session running.
Did not do much whith it though, except logging out again - from the taskbar ;)

**Comment by thecrazyonestherebels** [comment]
@akallabeth sorry for the late feedback.

May I ask you to confirm if issue is not reproduced when you start a fresh session, using xfreerdp client, after rebooting the VM?
Just wanted to re-check, as if you previously launch a session from MSTSC, then I also couldn't reproduce the issue.

I've also built the FreeRDP client for macOS from latest master, launched with a default command line and still see the missing taskbar issue. 

It's weird that issue is reproduced only on my environment. Then I wondering how the Microsoft Remote Desktop client for macOS has fixed this in the latest versions v10..7.*
