### ISSUE TITLE
failed to open display: :0

### ISSUE THREAD

**Issue by hanm2019** [FreeRDP/FreeRDP#7735]
**Found a bug? - We would like to help you and smash the bug away.**

**Describe the bug**

**To Reproduce**
1. install freeRDP by `sudo port install FreeRDP`
2. can not find start icon
3. run `xfreerdp` at shell
4. get 
```
[14:25:44:077] [91330:048e4580] [ERROR][com.freerdp.client.x11] - failed to open display: :0
[14:25:44:077] [91330:048e4580] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.
```

5. run `echo $DISPLAY`: 
```
echo $DISPLAY
:0
```

**Expected behavior**
open the FreeRDP client

**Screenshots**

![image](https://user-images.githubusercontent.com/56673361/159420964-d6ad3433-55c4-400c-b01c-cd5b30ad90fb.png)

**Application details**

**Environment (please complete the following information):**
 - OS: mac
 - Version/Distribution: 12
 - Architecture: arm

**Additional context**

** Please remove this text before submitting your issue!

_Thank you for reporting a bug!_

**Comment by akallabeth** [comment]
Please check you  have a `X11` server installed and running.

**Comment by IveMalfunctioned** [comment]
and how are you supposed to do that
