### ISSUE TITLE
Ninja build does not find libxkbfiles on Gentoo; need to make library directories portable

### ISSUE THREAD

**Issue by R030t1** [FreeRDP/FreeRDP#7739]
The build works using make, but I've found ninja builds far faster and prefer to use it with cmake when possible. Gentoo installs libxkbfiles (along with lots of other stuff) to `/usr/lib64` instead of `/usr/lib`, where ninja seems to look.

**Comment by akallabeth** [comment]
sorry, you seem to mix up what `CMake` does with what `Ninja` is responsible for.

**Comment by akallabeth** [comment]
FYI: this already works, compiling on `Fedora` daily (which also uses the `lib64` library directories) so the issue is somewhere with gentoo or your install.
