### ISSUE TITLE
Killing xfreerdp leaves a hanging FUSE directory

### ISSUE THREAD

**Issue by OLEGSHA** [FreeRDP/FreeRDP#7741]
**Describe the bug**
Terminating a running `xfreerdp` process with an interruption (read: ^C) leaves a temporary directory with a broken `/dev/fuse` mounted into it. Aside from the general garbage accumulation, in causes some file managers, e.g. Nautilus, to stop functioning whenever the directory would be displayed.

**To Reproduce**
1. Run `xfreerdp /u:admin /p:[password] /v:[host] /app:'||paint'`
2. Wait for the window to appear
3. Observe a directory like `/tmp/.xfreerdp.cliprdr.893399` appear
4. Kill the process with ^C
5. The process appears to terminate normally (stacktrace appears in stdout, I assume this is normal)
6. Observe the directory remain and become inaccessible

**Expected behavior**
The program should make an effort to unmount and remove the temporary directory whenever it shuts down, even abnormally.

**Details**
After the process is killed:
`ls -al /tmp/ | grep '.xfreerdp.clipdir.'`:
```
d?????????  ? ?        ?               ?            ?  .xfreerdp.cliprdr.893399
```
`ls -al /tmp/.xfreerdp.clipdir.*`:
```
ls: cannot access '/tmp/.xfreerdp.cliprdr.893399': Transport endpoint is not connected
```
`grep '/tmp/.xfreerdp.clipdir.' /etc/mtab`:
```
/dev/fuse /tmp/.xfreerdp.cliprdr.893399 fuse rw,nosuid,nodev,relatime,user_id=1000,group_id=1002 0 0
```

**Application details**
* FreeRDP version: nightly from freerdp.com (`3.0.0-dev (4f07e75ba)`)
* Complete log: https://windcorp.ru/other/xfreerdp-log-1.txt.gz

**Environment:**
 - OS: Linux
 - Version/Distribution: Debian 11
 - Architecture: amd64
 - DE: KDE on X11

**Comment by OLEGSHA** [comment]
To manually remove the entries in `/tmp`: `umount /tmp/.xfreerdp.cliprdr.* && rm -r /tmp/.xfreerdp.cliprdr.*`

**Comment by akallabeth** [comment]
ok, 3.x series of `FreeRDP` does handle termination signals for all clients now.
