### ISSUE TITLE
wfreerdp.exe /parent-window not working as expected

### ISSUE THREAD

**Issue by StefanKoell** [FreeRDP/FreeRDP#7747]
Hi,

**Describe the bug**
When using the wfreerdp.exe with the /parent-window argument and pass a window handle to it, the remote session is correctly rendered on the provided window. Mouse input is correctly recognized but **no keyboard input**.

Forgive my ignorance but since there's almost no documentation about the /parent-window argument (https://github.com/FreeRDP/FreeRDP/wiki/CommandLineInterface#other-options) like how it's supposed to work or how it can be used correctly, I'm assuming this is a bug - especially since mouse input works fine.

**To Reproduce**
1. In my case I have a simple C# WinForms application (which I can provide upon request) which opens a blank form.
2. Once the form has loaded, the window handle is available.
3. I simply start `wfreerdp.exe /v:[computername] /size:1024x768 /u:[username] /p:[password] /parent-window:[form-window-handle]`
4. Once the process is running, I can see the session on my window and can use the mouse but not the keyboard.

**Expected behavior**
The keyboard to be working.

**Application details**
* FreeRDP version build #1074: https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=vs2013/1074/
* Command line used: see above
* OS version connecting to (server side): not related to any server version. Tested with Windows 10 Professional 21H1 19043.1620

**Environment (please complete the following information):**
 - OS: Windows
 - Windows 11
 - Architecture: x64

**Additional context**
this has been reported at least two times:
https://github.com/FreeRDP/FreeRDP/issues/2881
https://github.com/FreeRDP/FreeRDP/issues/4051

Thanks!
Stefan

**Comment by akallabeth** [comment]
Yes, a bug indeed. But are you sure you are using a 11 year old version of freerdp?

**Comment by StefanKoell** [comment]
To be honest, I don't really know. I followed the download link here: https://www.freerdp.com/ and followed the link to the nightly builds. According to the link I posted, it was built on Mar 25th 2022. If I right-click the wfreerdp.exe and show the properties, there's no version number or anything which would indicate what version I'm using. If I type wfreerdp.exe --version I don't get anything (no output at all).

Am I downloading the wrong executable? Do I need to build from source? The zip from the https://github.com/FreeRDP/FreeRDP/releases page doesn't contain any binaries.

Thanks!

**Comment by akallabeth** [comment]
@StefanKoell ah, github automation ^^  `#1074` was your build number I assume? autocompleted to a very old pull request

**Comment by StefanKoell** [comment]
LOL! I see. Ok, so I guess I have a recent version in use. Is there anything I can do to help fixing the bug? Further logs, tests or a basic sample application to illustrate the issue? Since I'm not really a C/C++ specialist, I'm not sure where to look to fix that issue.

**Comment by akallabeth** [comment]
@StefanKoell well, it is an issue with either `wf_keyboard_thread` or ``
A compile with `-DWITH_DEBUG_KBD=ON` might help there, as it prints out debug messages whenever something from the keyboard is typed. (run standalone to check what should be there, then you might see what is missing with your app)

**Comment by StefanKoell** [comment]
Closing this as my PR has been accepted and merged. Thanks for all the help!
