### ISSUE TITLE
Use SmartCard MAC OS Mountain Lion

### ISSUE THREAD

**Issue by pontedabarca** [FreeRDP/FreeRDP#775]
Hello everyone,

I'm using freerdp on my Mac Mini, installed with homebrew.

My system is OK, i can access to my Windows Server 2003 R2 with no problem, keyboard and mouse are working good.

I use digital sign to all operations, but, the software for doing it can't be installed in MAC. With the software, i use a smartcard reader, SCR3310, to reader my card.

I need that freerdp permits using smartcard on my RDP session for digital sign, not for autentication. I can do this in a Windows XP because de RDP software permits using smart cards in the RDP session and my Windows Server 2003 R2 acept this.

I did a little web resource and i am using the following command xfreerdp -u <user> -g <resolution> --plugin rdpdr --data scard:scard -- <IP server> and i can acess to my server but the server don't recognizes the smart card reader.

In the terminal.app, i get the following message:
gab-03:bin macbook$ xfreerdp -u <user> -g 1024*768 --plugin rdpdr --data scard:scard -- <IP server>
loading plugin rdpdr
freerdp_load_library_symbol: failed to open /usr/local/Cellar/freerdp/1.0.1/lib/freerdp/rdpdr: dlopen(/usr/local/Cellar/freerdp/1.0.1/lib/freerdp/rdpdr, 5): image not found
freerdp_load_plugin: failed to load rdpdr/VirtualChannelEntry

Can anyone point me any solution?

Best regards

**Comment by sconstantine** [comment]
Loading SmartCard Services (https://smartcardservices.macosforge.org) the SCR3310 is working for me in OS X 10.11.x.

However, FreeRDP still crashes upon connection when set to redirect the smart card.  I'm running Royal TSX and Remote Desktop (FreeRDP) v2.2.1.1 beta with SCR3310 USB Smart Card Reader.

Suggestions or new FreeRDP plugin beta to try?

**Comment by sconstantine** [comment]
Any progress or updates to smart card redirection support with OS X?

**Comment by bmiklautz** [comment]
Should be fixed on master now. If you still see this issue please re-open or recreate a new one.
