### ISSUE TITLE
AVC sometimes leaves artifact on master but not stable 2.0

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#7753]
![image](https://user-images.githubusercontent.com/3472254/160395410-50883794-ae52-4036-b9f2-993ec3b55190.png)

reported by @pnowack

**Comment by pnowack** [comment]
Just retested. Only AVC is affected (this with AVC420 here). This cannot be reproduced with the Calista (RFX) Progressive codec.
It seems that the letter `s` in gnome-terminal always make it reproduce it in my case:
![Bildschirmfoto vom 2022-03-28 14-25-10](https://user-images.githubusercontent.com/40351335/160397820-6781c617-df42-4c2e-bdc9-856a9bc33ba5.png)

For clarification: The underscore under the `s` in the second line should NOT be there (and it is not there with xfreerdp from stable-2.0). The underscore artifact can also happen with other keys.
This was here reproduced with g-r-d. @Nexarian afaik reproduced it some time ago with xrdp too.

**Comment by pnowack** [comment]
Found an even better reproducer: If I create a virtual monitor of the size 640x480, the first frame already has issue:

xfreerdp from stable-2.0 (correct picture):
![Bildschirmfoto vom 2022-03-28 16-45-39](https://user-images.githubusercontent.com/40351335/160424685-6045d6d7-b17a-47f7-a685-58051613ee5e.png)

xfreerdp from master (wrong white line at the bottom):
![Bildschirmfoto vom 2022-03-28 16-45-52](https://user-images.githubusercontent.com/40351335/160424879-f763b3f1-3467-41a3-869a-debe231f0530.png)
