### ISSUE TITLE
Hotplug support multitouch (rdpei) channel

### ISSUE THREAD

**Issue by mojoba** [FreeRDP/FreeRDP#7759]
**Is your feature request related to a problem? Please describe.**
xfreerdp started with no mouse or keyboard attached will not auto redirect those to the currently running session if new devices are connected.

**Describe the solution you'd like**
Hotplug redirect of specified devices (by vendor and product id) to support automatic redirection into the current rdp session.

**Describe alternatives you've considered**
udev rules which kills and start a new xfreerdp session when a mouse, trackpad or keyboard is connected. This is a clunky workaround.

**Additional context**
This is particularly desired in touchscreen environments where the rdp session is running fullscreen. Without hotplug support, the entire screen is essentially unresponsive to clicks and a hard system reboot needs to be done.

**Comment by akallabeth** [comment]
works here.
Keyboard and mouse is part of libinput/evdev stuff, so any keyboard or mouse detected by normal `X11` is working (whenever that was attached)

**Comment by mojoba** [comment]
It works smoothly if the input device is connected at the time freerdp connection is established.

Scenario to reproduce -
- freerdp runs on its own via scheduled cron job with no input device present.
- Later, a touch input device is connected.
- Touch device is unresponsive inside rdp window (even though the cursor moves, no clicks are detected). This touch device is loaded by hid-generic and a few seconds later by hid-multitouch (from dmesg).

**Comment by akallabeth** [comment]
@mojoba ok, checked, the multitouch settings are applied on session start and must be registered per device (currently).
Still, mouse and keyboard do work if plugged in later, only multitouch devices have an issue here.
