### ISSUE TITLE
urbdrc: use /usb:auto with blacklist

### ISSUE THREAD

**Issue by fuzy112** [FreeRDP/FreeRDP#7766]
Hi.

In my organization we need to specify a list of USB classes and PID/VID's that I want/don't want to redirect.  I'm considering adding a command line option to the urbdrc client plugin to do that.
But I've found the following code in urbdrc:
https://github.com/FreeRDP/FreeRDP/blob/1378c8e67112c6cfe6414ae6b51e2862cb4c2baf/channels/urbdrc/client/libusb/libusb_udevman.c#L730-L749

It seems that you are trying to implement something like the `usbdevicestoredirect` setting
as described in https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/rdp-files . That setting should allow a device setup class GUID to be specified.  But I'm curious that there's no such GUIDs on linux.

Another option that I've considered is to add a config file which contains a blacklist or whitelist of USB device classes or PID/VID's.

Please tell me which option you prefer.  I'd like to create a pull request.

**************
By the way, I've found the following code in urbdrc.

https://github.com/FreeRDP/FreeRDP/blob/1378c8e67112c6cfe6414ae6b51e2862cb4c2baf/channels/urbdrc/client/data_transfer.c#L1239-L1240

I want to know if there is any impact to fill in a dummy value instead of actual frame number.  Is there any possibility to obtain real frame number in userspace on linux?

**Comment by akallabeth** [comment]
Hi,
 as for command line option, you only have `VID:PID` on linux (bus ID are changing when you attach on a different port).
Best would be to have bothe, blacklist and whitelist support.

As for the frame thing, did not find anything yet (therefore it is in there) but did not bother to look too deep as that is not really a problem (at least found nothing that has issues yet)
