### ISSUE TITLE
kerberos failed when connect to windows server in domain

### ISSUE THREAD

**Issue by JSSSSSSSSSS** [FreeRDP/FreeRDP#7770]
Is Kerberos available？I got an error：
![image](https://user-images.githubusercontent.com/58905687/161375136-1c9dba25-99bf-47b4-8a66-d88ce38ba0c7.png)

**Comment by akallabeth** [comment]
hard to tell if we know nothing about your setup ;)

**Comment by JSSSSSSSSSS** [comment]
I use this Compile line:
`cmake -DWITH_SSE2=ON -DWITH_GSSAPI=ON -DWITH_PKCS11H=ON -DWITH_KERBEROS=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DWITH_CUNIT=ON -DWITH_DEBUG_NTLM=ON -DWITH_DEBUG_NEGO=ON -DWITH_DEBUG_NLA=ON -DWITH_DEBUG_SCARD=ON`
And simply add the domain and ip of DC to my linux dev‘s kerberos5 configuration file: `/etc/krb5.conf`
![image](https://user-images.githubusercontent.com/58905687/161871700-81ceb5c2-21b2-40d4-8e0a-802c58192e03.png)
Did I miss any other setup？

**Comment by akallabeth** [comment]
@JSSSSSSSSSS Ok. then you have the following possible problems:
1. Do you use the correct destination to connect (IP might not be a proper realm/domain)
2. Do you use the correct credentials (hint: `/d:domain` might help)

Also:
1. `xfreerdp /version` and `xfreerdp /buildconfig` are often more helpful than `CMake` command line
2. we still don´t know if you use an ancient version or current ones.

**Comment by JSSSSSSSSSS** [comment]
I'm sorry about that. this is the output of `xfreerdp /buildconfig`:
![image](https://user-images.githubusercontent.com/58905687/161926402-162f37be-3d56-487c-b4d1-8a9aadf7951e.png)
This is my command line:
`xfreerdp /u:admin /v:xxx.xxx.xxx.xxx /p:pwd /d:ad11 /cert-ignore`
Are there any novice tutorials or examples about xfreerdp using Kerberos authentication for reference？Actually, I don't know how to setup the realm.

**Comment by akallabeth** [comment]
@JSSSSSSSSSS thank you. and well, no, there are none as kerberos support is still not stable (you might have seen that `option(WITH_GSSAPI "Compile support for kerberos authentication. (EXPERIMENTAL)" OFF)` defaults to being disabled.

**Comment by AdrianVollmer** [comment]
Pretty sure you need to use the host's FQDN instead of IP address

**Comment by KhazAkar** [comment]
@AdrianVollmer Most possibly won't work. We need either to wait or help maintainers/devs of FreeRDP to implement proper handling of such scenarios.

I know that it's old as hell, but can you try to use @JSSSSSSSSSS rdesktop if possible? I had some successes when connecting to CredSSP-enabled Windows endpoints using rdesktop for now.

**Comment by BryannaM** [comment]
Trying to just go through all these kerberos related issues to see if I can confirm all of them working now with the proper kerberos support being added to FreeRDP, connecting to plenty of our servers. @JSSSSSSSSSS If you would like some help to get this working i can help you set it up like we have it setup at my job

**Comment by JSSSSSSSSSS** [comment]
Thank you very much. And I want to know how to setup the kerberos client（my linux dev）and the KDC（windows domain controller） @BryannaM ,thank you.
