### ISSUE TITLE
IME not working in RAIL mode

### ISSUE THREAD

**Issue by panda2134** [FreeRDP/FreeRDP#7772]
**Describe the bug**
Win+Space, Ctrl+Space, Ctrl+Shift fail to switch the IME in RAIL mode.
The behavior is somewhat similar to #7116, however on my side the IME is never activated (even for a second).

**To Reproduce**
1. Connect to a Win10 (rev. 19041) Computer with XFreeRDP 2.6.1, enabling RAIL mode and open Microsoft Edge
2. Try to switch on Microsoft Pinyin IME
3. IME is not activated

**Expected behavior**
IME can be activated.

**Application details**
* FreeRDP version (`xfreerdp /version`): 2.6.1
* Command line used: `xfreerdp /d:"DESKTOP-I83FMUT" /u:"ljypa" /p:"Hppk9AzU" /v:192.168.122.20 +clipboard /a:drive,root,/ +decorations /cert-ignore /sound /scale:180 /dynamic-resolution /span  /wm-class:"cassowaryApp-msedge.exe" /app:"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" /app-icon:"/home/panda2134/.local/lib/python3.10/site-packages/cassowary/base/../gui/extrares/cassowary_app.png"`
* Output of `xfreerdp /buildconfig`: 
```
This is FreeRDP version 2.6.1 (2.6.1)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          None
CFLAGS:              -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -flto -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 11.2.0
Target architecture: x64
```
* OS version connecting to (server side): Windows 10 Pro (rev. 19041)

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]: Archlinux
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]: Archlinux
 - Architecture: [amd64, arm]: amd64

**Comment by amazingfate** [comment]
When connecting the remote app for the first time, I can see IME float bar at the right bottom of the window. I can click on that bar to select IME. But when I close this connection and connect it later, this bar is gone, but the IME set at the first time is kept.

**Comment by oicu** [comment]
安装第三方输入法，比如中文搜狗输入法(sougou pinyin)，在 remote app 模式里，可以用它自带快捷键 `Ctrl+,`切换。

**Comment by hardening** [comment]
@oicu sorry but spoken language is English on FreeRDP

**Comment by oicu** [comment]
> @oicu sorry but spoken language is English on FreeRDP

Install third-party input methods, such as the Chinese Sogou Pinyin input method. In the remote app mode, you can use its own shortcut key `Ctrl+,` to switch.

**Comment by SwimmingTiger** [comment]
This param fix my problem (I use Microsoft Pinyin with zh_CN locale at Windows 11 23H2):

```
/kbd:layout:0xE0010804,lang:0x0004
```

And `/kbd:layout:0x00000804,lang:0x0004` can have worked for a well, but then suddenly broke. Then I found that `/kbd:layout:0xE0010804,lang:0x0004` can work stably.

List all layout/lang codes:
```
xfreerdp /list:kbd
xfreerdp /list:kbd-lang
```
