### ISSUE TITLE
TestBacktrace fails with musl libc

### ISSUE THREAD

**Issue by floppym** [FreeRDP/FreeRDP#7773]
When built against musl libc on Gentoo Linux, TestBacktrace fails:
```
----------------------------------------------------------

75/188 Testing: TestBacktrace
75/188 Test: TestBacktrace
Command: "/var/tmp/portage/net-misc/freerdp-2.6.1/work/freerdp-2.6.1_build/Testing/TestWinPRUtils" "TestBacktrace"
Directory: /var/tmp/portage/net-misc/freerdp-2.6.1/work/freerdp-2.6.1_build/winpr/libwinpr/utils/test
"TestBacktrace" start time: Apr 03 05:12 UTC
Output:
----------------------------------------------------------
[05:12:52:399] [22101:22101] [FATAL][com.winpr.utils.debug] - Invalid stacktrace buffer! check if platform is supported!
winpr_backtrace failed!
<end of output>
Test time =   0.03 sec
----------------------------------------------------------
Test Failed.
"TestBacktrace" end time: Apr 03 05:12 UTC
"TestBacktrace" time elapsed: 00:00:00
----------------------------------------------------------
```
musl does not provide execinfo.h.

Downstream bug report: https://bugs.gentoo.org/836716

**Comment by akallabeth** [comment]
pull requests welcome.

**Comment by floppym** [comment]
> pull requests welcome.

Would it be acceptable to skip the test when there is no viable way to produce a backtrace?

**Comment by floppym** [comment]
musl doesn't provide a `backtrace()` function. A possible alternative would be to depend on [libunwind](https://www.nongnu.org/libunwind/) and make use of its `unw_backtrace()` function.

**Comment by akallabeth** [comment]
@floppym `libunwind` support is already there, but currently only for android.

**Comment by akallabeth** [comment]
Ok, is now enabled by default.
As long as `libunwind` is linked in and `dladdr` is available the backtrace backend will work.
