### ISSUE TITLE
Crash on disconnect from rdp session with usb redirection

### ISSUE THREAD

**Issue by Fantu** [FreeRDP/FreeRDP#7782]
On any disconnect from rdp session using usb redirection there is a crash.

```
...
[15:59:04:732] [1883:1922] [ERROR][com.freerdp.core] - freerdp_abort_connect:freerdp_set_last_error_ex ERRCONNECT_CONNECT_CANCELLED [0x0002000B]
remmina: ../../libusb/os/threads_posix.h:58: usbi_mutex_destroy: asserzione "pthread_mutex_destroy(mutex) == 0" non riuscita.
```
Full backtrace: https://paste.debian.net/1237000/

Application details

FreeRDP version 2.6.1
Command line used: launched from remmina
OS version connecting to (server side): windows 10 pro v21H1 build 19043.1586
custom build based on debian packages: http://debomatic-arm64.debian.net/distribution#dpr-tc-bullseye-backports
https://github.com/M2Rbiz/freerdp2-pkg-d11 https://github.com/M2Rbiz/remmina-pkg-d11
Environment (please complete the following information):

OS: linux
Version/Distribution: Debian 11
Architecture: arm64
hardware: raspberry 4b

If you need more information tell me
thanks for any reply and sorry for my bad english

**Comment by akallabeth** [comment]
@Fantu did you check with `libusb` project first? This looks like a bug there, see the topmost parts of the stack trace are in `libusb_exit`

**Comment by Fantu** [comment]
@akallabeth thanks, I tested it, crash solved and now devices redirected are full working (before some had important issue)
