### ISSUE TITLE
FreeRDP_GatewayHttpUseWebsockets setting not initialized to TRUE

### ISSUE THREAD

**Issue by akarl10** [FreeRDP/FreeRDP#7785]
FreeRDP_GatewayHttpTransport is FALSE if not set. CLI has only a option to set it explicitly to FALSE, but there is no way to set it to TRUE. The initialization is in this commit
https://github.com/FreeRDP/FreeRDP/blob/c67e4df96b/libfreerdp/core/settings.c,
but this was never backported from master

Releated pull request for master: c67e4df96b

**Comment by akallabeth** [comment]
What exactly is the issue you're trying to solve?
stable 2.0 does things a little different, the thing you reference is done at `libfreerdp/core/settings.c:489`

**Comment by akarl10** [comment]
sorry,  I missed line and copied the wrong setting.
The Setting I mean is FreeRDP_GatewayHttp**UseWebsockets**

the commit is this one: https://github.com/FreeRDP/FreeRDP/commit/5fc2290c03c2f716eac1a68c581e05b6127f7a10
the relevant part is freerdp_settings_set_bool(settings, FreeRDP_GatewayHttpUseWebsockets, TRUE) in settings.c

This is not in 2.6.1. This means there is no way to set it to true (only false by /gt:http,no-websockets).

**Comment by akallabeth** [comment]
@akarl10 ok, that was indeed a bug in the backport.
Thanks for the hint!

**Comment by akarl10** [comment]
I tried applying #7786 and now it works like it should.

Thank you
