### ISSUE TITLE
[API] rdp input scancodes mess

### ISSUE THREAD

**Issue by sss123next** [FreeRDP/FreeRDP#7793]
in current master df3737b085de8e907020faf7b9d6f0eee303f419  function freerdp_input_send_keyboard_event can't handle input code achieved from RDP_SCANCODE_LWIN, which returning 347 which failing  at WINPR_ASSERT(code <= UINT8_MAX); ( https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/core/input.c#L301 ), this change introduced in 5fb59a23a9f25f5996d7b015e20dcb5ce31208fb

before this assert i have succesfully used this macros (RDP_SCANCODE_LWIN) and it worked properly.

**Comment by sss123next** [comment]
casting to uint8_t seems works, i guess instead of assert, function signature should be changed to accept uint8_t type instead of uint16_t

**Comment by akallabeth** [comment]
Your code is wrong, see `freerdp_input_send_keyboard_event_ex` for correct usage of said API.

**Comment by akallabeth** [comment]
As for the `ASSERT`, it might be a good idea to change that to a warning log though.
