### ISSUE TITLE
/app-icon option is broken

### ISSUE THREAD

**Issue by roworu** [FreeRDP/FreeRDP#7804]
**Describe the bug**
When trying to use /app-icon option - it doesn't work in any way I tried. 
I put "win10.png" icon to "~/.icons/win10.png" and when i try to put it to my freerdp command, nothing happens, app still using default icon.
None of following variants worked:
`
/app-icon=win10
/app-icon="win10"
/app-icon=win10.png
/app-icon="win10.png"
/app-icon="~/.icons/win10.png"
/app-icon=~/.icons/win10.png
`
 
**To Reproduce**
Add /app-icon option to xfreerdp command

**Expected behavior**
App should use selected icon, but its not.  

**Screenshots**
![image](https://user-images.githubusercontent.com/36964755/163751556-fcf63bda-c9a3-4f0d-9664-51d72b8601c6.png)

**Application details**
* FreeRDP version freerdp 2:2.6.1-2

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Architecture: amd64

**Comment by akallabeth** [comment]
yes, that option is there for compatibility with `RDP` files (which sometimes provide this)
It has not yet been implemented and you seem to be the first one to complain.
Adding this to the backlog.

**Comment by roworu** [comment]
Oh, ok =)
Thank for your reply
