### ISSUE TITLE
freebsd build failure

### ISSUE THREAD

**Issue by sss123next** [FreeRDP/FreeRDP#7805]
**Describe the bug**
compilation (linking) failure on freebsd with libressl

**To Reproduce**
1. cmake  -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE -DWITH_WAYLAND=OFF -DWITH_MANPAGES=OFF -DCMAKE_INSTALL_PREFIX:PATH=./ -DBUILD_TESTING=OFF -DWITH_LIBSYSTEMD=OFF -DWITH_ALSA=OFF -DWITH_X11=OFF -DWITH_FFMPEG=OFF -DWITH_GSTREAMER_1_0=OFF -DWITH_GSTREAMER_0_10=OFF -DWITH_PULSE=OFF -DWITH_CLIENT_CHANNELS=ON -DWITH_CHANNELS=ON -DBUILTIN_CHANNELS=ON -DWITH_SERVER_INTERFACE=ON -DWITH_SERVER_CHANNELS=ON -DWITH_CLIENT_INTERFACE=ON -DBUILD_SHARED_LIBS=OFF -DCHANNEL_URBDRC=OFF -DCHANNEL_RDPDR=OFF -DCMAKE_BUILD_TYPE=Debug -DENABLE_DEBUG=ON -DWITH_DEBUG_ALL=ON  -DCMAKE_C_FLAGS_DEBUG="-O0 -ggdb3 -fno-omit-frame-pointer -fPIC -pthread" -DCMAKE_CXX_FLAGS_DEBUG="-O0 -ggdb3 -fno-omit-frame-pointer -fPIC -pthread"  -DCMAKE_SHARED_LINKER_FLAGS_DEBUG="-pthread -fsanitize=address" ../
2. make
3. See error

**Expected behavior**
succesfully compiled and linked executables and libraries

**Application details**
* FreeRDP version: 37d0a9e2b77acbe2fe4cd4fce85df84c148a9735
* see attached build log [freerdp_build_log.gz](https://github.com/FreeRDP/FreeRDP/files/8508934/freerdp_build_log.gz)

**Environment (please complete the following information):**
 - OS: FreeBSD FreeBDSM 12.2-STABLE FreeBSD 12.2-STABLE #0 c243248-g8c01699f9194-dirty:
 - Architecture: amd64

**Comment by akallabeth** [comment]
looks like `libressl` does not have `BIO_read_ex`?

**Comment by sss123next** [comment]
looks like.
is it a lot of work to add option to built without cryptolibraries at all (for use with external io and crypto) ?

**Comment by akallabeth** [comment]
@sss123next don´t know, but the specific error you have is in `winpr/tools` which can already be disabled during build with `-DWITH_WINPR_TOOLS=OFF`

**Comment by sss123next** [comment]
understood, thx for info, so probably  i have create separate ticket to completely disable internal  crypto.

**Comment by sss123next** [comment]
`-DWITH_WINPR_TOOLS=OFF ` seems to resolve this issue.
