### ISSUE TITLE
Windows 7 TLS compatibility issue with openssl3

### ISSUE THREAD

**Issue by akarl10** [FreeRDP/FreeRDP#7839]
Openssl3 changed the default security level of tls<1.2 and sha1 to from 1 to 0
This means that Windows 7 will not work (since they disabled SHA1, in practice it seems it will also not work with TLS1.2 enabled)

the cli user could workaround this by using /tls-seclevel:0, but i am not aware of such an option in remmina.
To the average user this looks like a regression in freerdp, but in reality it isn't.

I am not saying that it makes a ton of sense supporting an old unsupported OS, but if we decide to drop Windows 7 by default, we could also increase the default tls-seclevel to 2 (Windows 10 1607 LTSB does still support this, not sure if Windows 8 does)

Leaving it on 1 with openssl3 in my opinion does not make a lot of sense

**Comment by akarl10** [comment]
Remmina probably will have such a setting version 1.4.26
see
https://github.com/FreeRDP/Remmina/commit/ba5c6cec5b4df72d372b4a12af5e235412a16a35

**Comment by Neustradamus** [comment]
To follow this ticket.

**Comment by akallabeth** [comment]
documented that in https://github.com/freerdp/freerdp/wiki/FAQ
will not weaken base security (RDP already has weak defaults)
