### ISSUE TITLE
wlfreerdp session get some kind of keypress (enter key or smth) event from wayland|wlroots|sway (idk), which affects on remote desktop

### ISSUE THREAD

**Issue by meklonets** [FreeRDP/FreeRDP#7857]
For example, when some file or a folder is selected (one-click) on a remote desktop, they are opening on exit from terminal emulator which is on the container on the same workspace with wlfreerdp container. And xfreerdp has no this problem.
And I don't know which side the issue is on: wayland, wlroots, sway or wlfreerdp. 
Hope you can assume. 
I made the screencast to see what I'm talking about. On the video I open and exit termite twice to demonstrate the issue. 
https://www.youtube.com/watch?v=GkxG9beD5c0

**Comment by akallabeth** [comment]
Ok, so if I understand correctly, either a mouse click or `enter` keypress is issued in the session when you are actually working with the terminal, correct?
Need to check if that could be `wlfreerdp` event handling, adding to TODO

**Comment by meklonets** [comment]
Thank you!
> Ok, so if I understand correctly, either a mouse click or `enter` keypress is issued in the session when you are actually working with the terminal, correct?

Not exactly. Working on terminal doesn't affect wlfreerdp session. Enter key, mouse click, $mod+{some key} anything else while on terminal does't affect wlfreerdp session. 
But if I exit terminal then it does.
I found one more thing. Maybe it will help some more.
If wlfreerdp session container was the last viewed container in workspace before the current active container with terminal (doesn't matter termite or alacritty), then exiting from terminal via CTRL+D lead to deleting the selected folder on the remote desktop.
made one more screencast.
https://youtu.be/tW1bRybX5Pc

**Comment by akallabeth** [comment]
@meklonets ok, this sounds as if the focus switches to `wlfreerdp` and it captures the keyboard/mouse input. (and then handles all of these events just as intended)
might be interesting to check when focus and enter events (or any other window handling stuff) happens.
