### ISSUE TITLE
Disable mediacodec and use openh264; A compilation error occurred

### ISSUE THREAD

**Issue by FengYuanBiao** [FreeRDP/FreeRDP#7897]
[ 75%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/h264_openh264.c.o
[ 75%] Building C object libfreerdp/CMakeFiles/freerdp.dir/codec/h264_mediacodec.c.o
In file included from /home/fyb/Desktop/freerdp-2.7.0/libfreerdp/codec/h264_mediacodec.c:27:
/home/fyb/Downloads/android-ndk-r15c/sysroot/usr/include/media/NdkMediaCodec.h:94:9: error: must use 'struct' tag to refer to type 'ANativeWindow'
        ANativeWindow* surface,
        ^
/home/fyb/Downloads/android-ndk-r15c/sysroot/usr/include/media/NdkMediaCodec.h:152:15: error: expected parameter declarator
static_assert(sizeof(_off_t_compat) == sizeof(long),
              ^
/home/fyb/Downloads/android-ndk-r15c/sysroot/usr/include/media/NdkMediaCodec.h:152:15: error: expected ')'
/home/fyb/Downloads/android-ndk-r15c/sysroot/usr/include/media/NdkMediaCodec.h:152:14: note: to match this '('
static_assert(sizeof(_off_t_compat) == sizeof(long),
             ^
/home/fyb/Downloads/android-ndk-r15c/sysroot/usr/include/media/NdkMediaCodec.h:198:59: error: must use 'struct' tag to refer to type 'ANativeWindow'
media_status_t AMediaCodec_setOutputSurface(AMediaCodec*, ANativeWindow* surface);
                                                          ^
/home/fyb/Downloads/android-ndk-r15c/sysroot/usr/include/media/NdkMediaCodec.h:223:29: error: must use 'struct' tag to refer to type 'ANativeWindow'
        AMediaCodec *mData, ANativeWindow **surface);
                            ^
/home/fyb/Downloads/android-ndk-r15c/sysroot/usr/include/media/NdkMediaCodec.h:239:9: error: must use 'struct' tag to refer to type 'ANativeWindow'
        ANativeWindow **surface);
        ^
/home/fyb/Downloads/android-ndk-r15c/sysroot/usr/include/media/NdkMediaCodec.h:252:29: error: must use 'struct' tag to refer to type 'ANativeWindow'
        AMediaCodec *mData, ANativeWindow *surface);
                            ^
/home/fyb/Desktop/freerdp-2.7.0/libfreerdp/codec/h264_mediacodec.c:69:86: error: must use 'struct' tag to refer to type 'ANativeWindow'
typedef media_status_t (*AMediaCodec_configure_t)(AMediaCodec*, const AMediaFormat*, ANativeWindow*,
                                                                                     ^
                                                                                     struct 
8 errors generated.
make[2]: *** [libfreerdp/CMakeFiles/freerdp.dir/build.make:1720: libfreerdp/CMakeFiles/freerdp.dir/codec/h264_mediacodec.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2146: libfreerdp/CMakeFiles/freerdp.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
[ERROR] cmake --build . --target install retured 2

----------------------------------------------------
freerdp-2.7.0
openh264：v1.8.0
ndk：r15c

**Comment by akallabeth** [comment]
well, `you´re doing it wrong` :)
more seriously, could you add the parts of the description what you actually do? (e.g. your `cmake` command line?)

**Comment by FengYuanBiao** [comment]
I just modified some Android-build.conf；Then it is compiled directly by ./scripts/android-build-freerdp.sh

WITH_JPEG=0
**WITH_OPENH264=1**
**WITH_MEDIACODEC=0**
WITH_OPENSSL=1
WITH_FFMPEG=0
BUILD_DEPS=1
DEPS_ONLY=0
NDK_TARGET=26

JPEG_TAG=master
OPENH264_TAG=v1.8.0  # NOTE: NDK r15c or earlier needed in --openh624-ndk for v1.8.0
OPENSSL_TAG=OpenSSL_1_1_1m
FFMPEG_TAG=n4.4.1

SRC_DIR=$SCRIPT_PATH/..
BUILD_DST=$SCRIPT_PATH/../client/Android/Studio/freeRDPCore/src/main/jniLibs
BUILD_SRC=$SRC_DIR/build

CMAKE_BUILD_TYPE=Debug

BUILD_ARCH="armeabi-v7a arm64-v8a"


---------------------
Isn't it configured like this?

**Comment by akallabeth** [comment]
no, but I´ve added that option now with #7899 
anyway, your compilation error is strange. Did you run this on a unclean checkout? (there might be problems if you run it repeatedly)

**Comment by akallabeth** [comment]
@FengYuanBiao just a note though, `OpenH264` build system is still broken as hell, you need to compile with a different (old NDK) which does have issues with all other dependencies, so best build in separate steps.

**Comment by FengYuanBiao** [comment]
@akallabeth 
The environment should be OK. Then I'll try to build with n15r previous ndks. You think you can try this, right?

**Comment by akallabeth** [comment]
@FengYuanBiao just compiled successfully with:
```
ANDROID_NDK=~/Android/Sdk/ndk/23.1.7779620/
ANDROID_NDK_OPENH264=~/Android/Sdk/ndk/18.1.5063045/
```
