### ISSUE TITLE
Exiting fullscreen in MATE (Metacity WM) positions window incorrectly

### ISSUE THREAD

**Issue by OLEGSHA** [FreeRDP/FreeRDP#7908]
**Describe the bug**
In MATE, when `xfreerdp` is started in fullscreen mode (`/f`), exiting fullscreen mode with either Ctrl+Alt+Enter or the floatbar button does not make window decorations or DE panels visible. It appears as if nothing has changed.

**To Reproduce**
1. Use a MATE environment (tested with Debian 11 LiveCD with MATE)
2. Install `xfreerdp` and run `xfreerdp /v:<address> /f`
3. Use Ctrl+Alt+Enter to exit fullscreen mode
4. Observe no visual change

**Expected behavior**
On most other WMs (Debian 11 with KDE, Debian 11 with GNOME 3), window is made maximized with a visible titlebar. DE panels are also made visible, which is the point of exiting fullscreen.

**Application details**
* FreeRDP versions: tested with versions 2.3.0, 2.5.0, 2.6.1, 2.7.0 and git [13d56db](https://github.com/FreeRDP/FreeRDP/commit/13d56dbfb2b33053b315c29c35280079a1dce990).
* Command line used: `xfreerdp /v:<address> /u:<user> /d:<domain> /cert-ignore /f`

**Environment (please complete the following information):**
 - OS: tested with Debian and a Fedora-like distro
 - Version/Distribution: Debian 11
 - Architecture: [amd64, arm]: amd64

**Comment by OLEGSHA** [comment]
It appears as if [xf_window.c:243](https://github.com/FreeRDP/FreeRDP/blob/13d56dbfb2b33053b315c29c35280079a1dce990/client/X11/xf_window.c#L243) is to blame:
```c
XMoveWindow(xfc->display, window->handle, startX, startY);
```
With this line commented out, behaviour of FreeRDP on MATE changes to match the other DEs; I could not discover any change in behaviour in either KDE or GNOME 3.

Digging through git history reveals that the line was initially added by @nfedera in [7ddd15d](https://github.com/FreeRDP/FreeRDP/commit/7ddd15d8deab94a8a2c1d61c792188fa7b6e21a2) (I assume its effect was previously negated by the `_NET_WM_STATE_FULLSCREEN` change). The commit message doesn't go into any details, and I could not discover the effect that this line has; I have to assume it is necessary for some WMs, so simply commenting it out would not suffice for a proper fix.

**Comment by OLEGSHA** [comment]
**Hotfix for MATE users**:
```patch
diff --git a/client/X11/xf_window.c b/client/X11/xf_window.c
index 5c50a077b..4b3b9b1e9 100644
--- a/client/X11/xf_window.c
+++ b/client/X11/xf_window.c
@@ -230,7 +230,9 @@ void xf_SetWindowFullscreen(xfContext* xfc, xfWindow* window, BOOL fullscreen)
                if (!fullscreen)
                {
                        /* leave full screen: move the window after removing NET_WM_STATE_FULLSCREEN */
-                       XMoveWindow(xfc->display, window->handle, startX, startY);
+                       //XMoveWindow(xfc->display, window->handle, startX, startY);
                }
 
                /* Set monitor bounds */
```
As per my previous message, I assume this breaks something somewhere, so I would not call this a proper fix.

**Comment by nfedera** [comment]
What happens if you don't start initially with `/f` but let's say `/size:1024x768` instead and then enter/exit fullscreen via hotkey ?

**Comment by OLEGSHA** [comment]
With `/size`, window position is reset to 0; 0 when leaving fullscreen, which is not good.

**Comment by nfedera** [comment]
Probably the correct thing to do would be to save the pre-fullscreen position and move back to that after exiting fullscreen.  
... and to thing of the usual corner cases of course

**Comment by OLEGSHA** [comment]
I did some testing yesterday, and it appears as if `savedPosX`, `savedWidth`, ... variables are set (incorrectly?) to make the internal area of the window occupy the entire screen when started with `/f`. With KDE, right after the window is restored, KDE's KWin issues a window move that fixes the appearance. However, MATE's Metacity doesn't do that and the window remains in the janky state.

**Comment by OLEGSHA** [comment]
Alright, here are the logs:
MATE: [mate-log.tar.gz](https://github.com/FreeRDP/FreeRDP/files/8707626/mate-log.tar.gz)
KDE for reference: [kde-log.tar.gz](https://github.com/FreeRDP/FreeRDP/files/8707583/kde-log.tar.gz)

These are collected without my hotfix. Notice the ugly extra debug info.

**Comment by nfedera** [comment]
I'm pretty sure it is related to applying/removing window decorations in combination with `NET_WM_STATE_FULLSCREEN` in non-multimon fullscreen mode.   

What happens if you disable/comment the first [xf_SetWindowDecorations](https://github.com/FreeRDP/FreeRDP/blob/master/client/X11/xf_window.c#L172) call in `xf_SetWindowFullscreen` ?
