### ISSUE TITLE
freerdp does not connect to windows server

### ISSUE THREAD

**Issue by leribe** [FreeRDP/FreeRDP#7914]
Hi Guys,

Running FreeRDP version 2.7.0 (2.7.0)
have tunneled an ssh to a remote windows server, that's working, but when i try to connect to my machine getting error below, please help, after putting in the password. Have removed know host entries, not sure what to check. Thanks in-advance.

[12:42:00:237] [300333:300334] [ERROR][com.freerdp.core.connection] - Timeout waiting for activation
[12:42:00:241] [300333:300333] [ERROR][com.freerdp.core] - freerdp_abort_connect:freerdp_set_last_error_ex ERRCONNECT_CONNECT_CANCELLED [0x0002000B]

**Comment by akallabeth** [comment]
hard to tell without further information.
`Timeout waiting for activation`: The error just means the server did not proceed with the connection in time (network problems? configuration issues?)

**Comment by hardening** [comment]
Give a try by adding `/timeout:1000`

**Comment by leribe** [comment]
> Give a try by adding `/timeout:1000`

thanks but returned same error.

**Comment by akallabeth** [comment]
@leribe how do you connect? (command line)?
I can think of 2 scenarios:
1. the server is in some (broken) state (happens sometimes after updates, most of the time works again when the user is logged out, sometimes requires a reboot)
2. You are using a command line disabling required features by that server

**Comment by JoaoPBarros** [comment]
Add to your command /timeout:60000 , use like this following command:

`xfreerdp /v:<target ip> /cert:<local/cert or ignore> /u:<user> /timeout:60000`
