### ISSUE TITLE
A big file complied on linux

### ISSUE THREAD

**Issue by 317764920** [FreeRDP/FreeRDP#7933]
I want to use xfreerdp in my app, but I wish to have a single file to execute . How can I update the CMakeList? and then I can invoke like this :   

./freerdp /u:user xxxxxx

**Comment by 317764920** [comment]
can you provide a demo?

**Comment by akallabeth** [comment]
Check the `ci/` folder, there are `CMake` preload scripts for the pull request builder.
specifically the windows version builds a static `wfreerdp.exe` which is similar to what you want.

**Comment by 317764920** [comment]
> Check the `ci/` folder, there are `CMake` preload scripts for the pull request builder. specifically the windows version builds a static `wfreerdp.exe` which is similar to what you want.

but  I want a single file on linux ，not windows
