### ISSUE TITLE
Should it be c_lflag here, not c_cflag? Fix tested with tty0tty.

### ISSUE THREAD

**Issue by ursoft** [FreeRDP/FreeRDP#7939]
https://github.com/FreeRDP/FreeRDP/blob/4c4b5bfd87b9dfb54c125ea11b2644ebce8112ff/winpr/libwinpr/comm/comm.c#L368

**Comment by akallabeth** [comment]
@ursoft `-ENOCONTEXT`?
Please be a little more verbose about what you are trying to ask.

**Comment by ursoft** [comment]
> @ursoft `-ENOCONTEXT`? Please be a little more verbose about what you are trying to ask.

`lpLocalDcb->fBinary = (currentState.c_cflag & ICANON) == 0;`

ICANON bit is c_lflag - related, not c_cflag
