### ISSUE TITLE
/admin connection from Linux to Windows

### ISSUE THREAD

**Issue by rogue-agent** [FreeRDP/FreeRDP#7953]
**Is your feature request related to a problem? Please describe.**
Feature request would allow connecting to a server without licensing mode activated, and other /admin features.
![image](https://user-images.githubusercontent.com/9405663/172405857-b40bd971-dd5a-4cb5-b939-433deddaa067.png)

**Describe the solution you'd like**
Either always connect to MSTSC with /admin or have a flag/parameter when trying to connect

**Describe alternatives you've considered**
Having a WIN VM to connect from with `mstsc /admin`

**Comment by akallabeth** [comment]
How about you use `xfreerdp /admin`?
That might not work if you have a domain with certain policies enabled (freerdp does not currently support kerberos for NLA)
