### ISSUE TITLE
如何集成到ios 项目中顺利使用

### ISSUE THREAD

**Issue by 18889813350** [FreeRDP/FreeRDP#7963]
How to integrate into the IOS project? Because I have always been able to solve endless error reports, I need to guide the key steps

**Comment by akallabeth** [comment]
There is general compilation instructions at https://github.com/FreeRDP/FreeRDP/wiki/Compilation
and you can check the `CMake` compilation options for our `CI` at `ci/cmake-preloads/config-macosx.txt` and `ci/cmake-preloads/config-ios.txt`

As for (specific, non general useful) questions please contact us in our matrix room.
