### ISSUE TITLE
Problems encountered in integrating into new Xcode projects

### ISSUE THREAD

**Issue by 18889813350** [FreeRDP/FreeRDP#7964]
主服务器的相关拉取请求：

![15021654854966_ pic](https://user-images.githubusercontent.com/22466017/173042385-946c07bd-29ee-4bbc-a5e1-96b5c85749e3.jpg)

![15031654854984_ pic](https://user-images.githubusercontent.com/22466017/173042441-4490feaf-3d41-4f46-b41b-5b3d0258d8d9.jpg)

你想设置一些东西吗？我不知道如何设置此错误消息

**Comment by akallabeth** [comment]
Please read the issue template.
We can not help if all you post are some screenshots without context.
