### ISSUE TITLE
FreeRDP proxy: DynvcTracker: reassembled packet (68196) is bigger than announced length (67920)

### ISSUE THREAD

**Issue by maordadush** [FreeRDP/FreeRDP#7969]
To Reproduce
connect to the target with via the FreeRDP proxy server and passthrough all the static channels.

> [DEBUG][proxy.utils] - rdpdr -> passthrough
> [DEBUG][proxy.config] - config_plugin_channel_create: rdpdr [static]: TRUE
> [DEBUG][proxy.utils] - rdpsnd -> passthrough
> [DEBUG][proxy.config] - config_plugin_channel_create: rdpsnd [static]: TRUE
> [DEBUG][proxy.utils] - cliprdr -> passthrough
> [DEBUG][proxy.config] - config_plugin_channel_create: cliprdr [static]: TRUE
> [DEBUG][proxy.utils] - dpchnl -> passthrough
> [DEBUG][proxy.config] - config_plugin_channel_create: dpchnl [static]: TRUE
> [DEBUG][proxy.utils] - drdynvc -> passthrough
> [DEBUG][proxy.config] - config_plugin_channel_create: drdynvc [static]: TRUE

Application details
FreeRDP proxy version:  3.0.0-dev, Git commit: 3.0.0
OS version connecting to (server side): Windows 10

Environment:
OS: Windows 10
Architecture: amd64

proxy config:

> [Channels]
> GFX = TRUE
> DisplayControl = TRUE
> Clipboard = TRUE
> AudioOutput = TRUE
> RemoteApp = TRUE
> DeviceRedirection = TRUE
> VideoRedirection = TRUE
> CameraRedirection = TRUE
> PassthroughIsBlacklist = TRUE
> ; a list of comma seperated static channels that will be proxied. This feature is useful,
> ; for example when there's a custom static channel that isn't implemented in freerdp/proxy, and is needed to be proxied when connecting through the proxy.
> Passthrough =
> 
> [GFXSettings]
> DecodeGFX = TRUE
> 

I got the following error:

> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=32 received=51132(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=33 received=52730(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=34 received=54328(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=35 received=55926(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=36 received=57524(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=37 received=59122(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=38 received=60720(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=39 received=62318(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=40 received=63916(67920)
> [08:00:12:766] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=41 received=65514(67920)
> [08:00:12:779] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Video::Control::v08.01): B->F DATA frags=42 received=65790(67920)
> [08:00:12:779] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=43 received=67388(67920)
> [08:00:12:779] [474859:474865] [DEBUG][proxy.drdynvc] - DynvcTracker(Microsoft::Windows::RDS::Graphics): B->F DATA frags=44 received=68196(67920)

**[08:00:12:779] [474859:474865] [ERROR][proxy.drdynvc] - DynvcTracker: reassembled packet (68196) is bigger than announced length (67920)**

> [08:00:12:779] [474859:474865] [WARN][com.freerdp.core.channels] - ReceiveChannelData returned 0
> [08:00:12:779] [474859:474865] [DEBUG][com.freerdp.core.rdp] - rdp_recv_callback: CONNECTION_STATE_ACTIVE - rdp_recv_pdu() - -1
> [08:00:12:779] [474859:474865] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -1
> [08:00:12:779] [474859:474865] [DEBUG][com.freerdp.core.rdp] - transport_check_fds() - -1
> [08:00:12:779] [474859:474865] [DEBUG][com.freerdp.core] - rdp_check_fds() - -1
> [08:00:12:779] [474859:474865] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
> [08:00:12:779] [474859:474865] [ERROR][proxy.client] - Failed to check FreeRDP event handles
>

**Comment by hardening** [comment]
@maordadush does https://github.com/hardening/FreeRDP/tree/proxy_dynvc_frag_fix fix the problem for you ?

**Comment by maordadush** [comment]
yes, thanks!
