### ISSUE TITLE
Feature request - accept encrypted password in command line

### ISSUE THREAD

**Issue by macarthor** [FreeRDP/FreeRDP#798]
Let's consider 2 situations:
a. store username/password to disk, in order to make connection easier; and
b. the plain text password in the command line would be shown in console, so it can be read by everyone.

In both cases, the plain text password is much less secure.

So, what about considering accepting encrypted password in command line. To be compatible between windows and linux, and between mstsc and freerdp, we can refer the method that mstsc encrypts RDP password. There are two articles describing what mstsc does to encrypt/decrypt RDP password:
http://www.remkoweijnen.nl/blog/2007/10/18/how-rdp-passwords-are-encrypted/
http://www.remkoweijnen.nl/blog/2008/03/02/how-rdp-passwords-are-encrypted-2/
I think this would give us some hints.

**Comment by akallabeth** [comment]
Closing as impossible.
RDP expects the password in a usable form.
If you want to improve security pass it via stdin so it is not shown in the process details.

**Comment by hardening** [comment]
Side note: the `/pth` command line argument allow to "pass the hash".
