### ISSUE TITLE
Feature of smart card is invalid from linux to win10

### ISSUE THREAD

**Issue by hxf3751** [FreeRDP/FreeRDP#7984]
I plugin a smart card device on Linux, and I can see the device id after I typed "lsusb", I plugin the same device on Win10, I can also see the device. But I plugin the same device on Linux, and then connect Win10 from the Linux, the device can't be found in Win10, and the terminal on Linux  tell me "SCARD_E_NO_SERVICE" as the following image. Do you know why?   Thanks!
![image](https://user-images.githubusercontent.com/86779241/175039843-115a2ade-b788-44fe-8b5e-3b7b7c13b5ba.png)

**Comment by akallabeth** [comment]
your setup does not properly enable `PCSC`, nothing freerdp can do there ;)

**Comment by hardening** [comment]
To add some details, the lsusb is not enough, you should also be able to list it with pcsc tools.
