### ISSUE TITLE
Outlook screen refresh error

### ISSUE THREAD

**Issue by gotsiboon** [FreeRDP/FreeRDP#800]
Hi all,

customers reported black areas in Outlook (mainly calendar) using freerdp 1.0.1 on Ubuntu 12.04. Same black areas also appear in other programs like for instance Firefox.
While trying to reproduce this I noticed that tooltip areas in Outlook aren't refreshed properly. 

I can reproduce this for freerdp 1.0.1 stabile and 1.0.2-rc1. When moving the mouse slowly over the mailbox-tree the tooltips show up and whenever the next tooltip is displayed the one before keeps visible in fragments.

I will attach screenshots later.

Best regards,
gotsiboon.

**Comment by akallabeth** [comment]
Master drawing code has been (mostly) rewritten.
Closing, reopen if still an issue.
