### ISSUE TITLE
xfreerdp cpu too high

### ISSUE THREAD

**Issue by zhuguoquan45** [FreeRDP/FreeRDP#8002]
**Describe the bug**
The CPU usage of Xfreerdp is higher than that of 1.0.x

**Screenshots**

same operation：

![20220628175009](https://user-images.githubusercontent.com/31690416/176152856-e9ed7b24-ac98-49f0-a38b-c3db605acbf8.jpg)

1.0.x:

![20220628180200](https://user-images.githubusercontent.com/31690416/176152974-b40dfa61-fc2e-4ccb-a3b8-e79695a1168c.jpg)

![20220628180108](https://user-images.githubusercontent.com/31690416/176153029-b7054cdc-14ad-4980-932c-da2aeeabda46.jpg)

2.x:

![20220628180219](https://user-images.githubusercontent.com/31690416/176153171-e1b55bdf-5d93-4548-9f6f-c46fc58010e7.jpg)

![20220628175144](https://user-images.githubusercontent.com/31690416/176153515-b200caeb-2c55-41c8-b7a0-c6b213a97870.jpg)

**Comment by akallabeth** [comment]
1. doubt that it is `same operation`, current `xfreerdp` utilizes `gfx` graphics pipeline and others, whereas `1.0` only had the legacy bitmap codecs
2. do not compare out of date versions (current 2.x release is `2.7.0`)
