### ISSUE TITLE
/multimon /monitors:1 opens window at the wrong monitor using xfwm4

### ISSUE THREAD

**Issue by amazingfate** [FreeRDP/FreeRDP#8032]
I'm using the latest release 2.7.0 on debian bullseye with xfwm4 4.16.1-2.
I have two 1080p monitors.
Then window will open where the mouse cursor is at.
When I change the resolution of monitor 1 to 1600x900 which is smaller than the resolution of monitor 0 1920x1080, the window can open at the correct monitor 1.
After I use command `openbox --replace`, the window can open at the correct monitor 1 (two monitors are both 1920x1080 this time).

**Comment by akallabeth** [comment]
So, to sum up you´re telling:
1. with `xfwm` it does not work if both monitors have the same resolution
2. with `openbox` it works though?

did I understand that correctly?
window placement is heavily influenced by the window manager used. Check settings and maybe disable them for freerdp if possible
