### ISSUE TITLE
[proxy] Different clients have different connection results.

### ISSUE THREAD

**Issue by gemone** [FreeRDP/FreeRDP#8043]
**Describe the bug**

Using different clients to connect to the proxy will produce different results. It seems that NLA has made an error.

**To Reproduce**

1. Build `cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DWITH_PROXY_MODULES=ON -DCHANNEL_URBDRC=OFF -DWITH_PROXY=ON -DWITH_SHADOW=OFF -DWITH_SERVER=ON -DBUILD_SHARED_LIBS=OFF && make`
2. Generate cert: `winpr-makecert -rdp -n rdpgw -path certs`
3. Config proxy, set `Security.ServerNlaSecurity=true`. The `Target` is `Windows 11`. (Tested `Windows10` and `Windows Server 2016` at the same time)
    ```ini
    [Server]
    Host=0.0.0.0
    Port=3389
    
    [Target]
    Host=192.168.2.12
    Port=3389
    FixedTarget=true
    
    [Channels]
    GFX=true
    DisplayControl=true
    Clipboard=true
    AudioInput=true
    AudioOutput=true
    DeviceRedirection=true
    VideoRedirection=true
    CameraRedirection=true
    RemoteApp=false
    PassthroughIsBlacklist=true
    Passthrough=
    Intercept=
    
    [Input]
    Keyboard=true
    Mouse=true
    Multitouch=true
    
    [Security]
    ServerTlsSecurity=true
    ServerNlaSecurity=true
    ServerRdpSecurity=true
    ClientTlsSecurity=true
    ClientNlaSecurity=true
    ClientRdpSecurity=true
    ClientAllowFallbackToTls=true
    
    [Plugins]
    Modules=
    Required=
    
    [Clipboard]
    TextOnly=false
    MaxTextLength=0
    
    [GFXSettings]
    DecodeGFX=false
    
    [Certificates]
    CertificateFile=./certs/rdpgw.crt
    PrivateKeyFile=./certs/rdpgw.key
    RdpKeyFile=./certs/rdpgw.key
    ```
4. Connect using the client.
    1. xfreerdp-3.0.0-dev
    2. xfreerdp-2.7.0
    3. mstsc-10.0.19041
5. Try to modify the `Security.ServerNlaSecurity=false` for testing.

When `Nla=true`, `xfreerdp-3.0.0-dev` cannot establish a connection, but `mstsc` can.

And `Nla=false`, `mstsc` cannot establish a connection, but `xfreerdp-3.0.0-dev` can.

`xfreerdp-2.7.0` cannot establish a connection every time.

**Expected behavior**

All clients can connect to the agent normally, and the results are consistent.

**Application details**

Same `freerdp proxy`.

1. With `Nla=true`:
    1. `xfreerdp-3.0.0-dev`(not work):
        1. `proxy`:  [freerdp-proxy-xfreerdp-3.0.0.dev-nla.log](https://github.com/FreeRDP/FreeRDP/files/9047021/freerdp-proxy-xfreerdp-3.0.0.dev-nla.log)
        2. `client`: [xfreerdp.log](https://github.com/FreeRDP/FreeRDP/files/9047028/xfreerdp.log)
    2. `xfreerdp-2.7.0`(not work):
        1. `proxy`:  [freerdp-proxy-xfreerdp-2.7.0-nla.log](https://github.com/FreeRDP/FreeRDP/files/9047057/freerdp-proxy-xfreerdp-2.7.0-nla.log)
        2. `client`:  [xfreerdp-2.7.0.log](https://github.com/FreeRDP/FreeRDP/files/9047038/xfreerdp-2.7.0.log)
    3. `mstsc`(work): 
        1. `proxy`: [freerdp-proxy-mstsc-nla.log](https://github.com/FreeRDP/FreeRDP/files/9047220/freerdp-proxy-mstsc-nla.log)
2. With `Nla=false`:
    1. `xfreerdp-3.0.0-dev`(work):
        1. `proxy`:  [freerdp-proxy-xfreerdp-3.0.0.dev-no-nla.log](https://github.com/FreeRDP/FreeRDP/files/9047066/freerdp-proxy-xfreerdp-3.0.0.dev-no-nla.log)
        2. `client`: [xfreerdp-3.0.0-dev.no-nla.log](https://github.com/FreeRDP/FreeRDP/files/9047081/xfreerdp-3.0.0-dev.no-nla.log)
    2. `xfreerdp-2.7.0`(not work):
        1. `proxy`: [freerdp-proxy-xfreerdp-2.7.0-no-nla.log](https://github.com/FreeRDP/FreeRDP/files/9047094/freerdp-proxy-xfreerdp-2.7.0-no-nla.log)
        2. `client`: [xfreerdp-2.7.0.no-nla.log](https://github.com/FreeRDP/FreeRDP/files/9047092/xfreerdp-2.7.0.no-nla.log)
    3. `mstsc`(not work): 
        1. `proxy`:  [freerdp-proxy-mstsc-no-nla.log](https://github.com/FreeRDP/FreeRDP/files/9047225/freerdp-proxy-mstsc-no-nla.log)

**Environment (please complete the following information):**

 - OS: Linux/Windows (`xfreerdp`/`mstsc`)
 - Version/Distribution: 
    - `Linux`: `Gentoo`
    - `Windows10`: `21H2`
 - Architecture: `amd64`

**Additional context**

The same problem occurs when the target machine is Windows10 and Windows Server 2016.

_Originally posted by @gemone in https://github.com/FreeRDP/FreeRDP/discussions/8036#discussioncomment-3083593_

**Comment by akallabeth** [comment]
@gemone ok, now I see where we did miss each other in the discussion.

Problem here is that `cient -> proxy` needs to use `TLS` security and only `proxy -> target server` can use `NLA` 
You can use `NLA` for both if you have different credentials for the proxy and the target connection and the proxy manages the target credentials.

**Comment by gemone** [comment]
> @gemone ok, now I see where we did miss each other in the discussion.
> 
> Problem here is that `cient -> proxy` needs to use `TLS` security and only `proxy -> target server` can use `NLA` You can use `NLA` for both if you have different credentials for the proxy and the target connection and the proxy manages the target credentials.

Does it mean that the configuration needs to be modified?

I try:

```ini
[Security]
ServerTlsSecurity = true
ServerRdpSecurity = false
ServerNlaSecurity = false
ClientTlsSecurity = true
ClientRdpSecurity = false
ClientNlaSecurity = true
ClientAllowFallbackToTls = false
```

But the problem remains.

**Comment by gemone** [comment]
> @gemone ok, sorry, I did miss that I was using a custom proxy module. The authentication is currently not upstream, sorry for misleading :/

It looks like a bug.

**Comment by akallabeth** [comment]
@gemone I´ve written it above already, the `authentication` part is not upstream yet.
You can only connect using `RDP/TLS` without credentials and log in the target system

**Comment by gemone** [comment]
@akallabeth Got it. Thanks!

**Comment by gemone** [comment]
The proxy is not yet perfect.  

1. Different connection results are caused by different logic from the client.
2. The problem of connection is that the authentication is not perfect.

Turn it on again if necessary.
