### ISSUE TITLE
windows build faild when x86

### ISSUE THREAD

**Issue by godtang** [FreeRDP/FreeRDP#8062]
* branch master
* use `cmake ../.. -DOPENSSL_ROOT_DIR="D:\Program Files (x86)\OpenSSL-Win32" -DBUILD_SHARED_LIBS=OFF -DLIBUSB_1_INCLUDE_DIR="D:\code\c_c++\libusb\libusb" -DLIBUSB_1_LIBRARY="D:\code\c_c++\libusb\Win32\Debug\lib" -A Win32` generate vs2019 sln，build error
*    “int (__cdecl *)(libusb_context *,libusb_device *,libusb_hotplug_event,void *)” convert to “libusb_hotplug_callback_fn”	urbdrc-client-libusb	D:\code\c_c++\FreeRDP\channels\urbdrc\client\libusb\libusb_udevman.c	873
* static int **LIBUSB_CALL** hotplug_callback(struct libusb_context* ctx, struct libusb_device* dev, libusb_hotplug_event event, void* user_data)
* hotplug_callback add **LIBUSB_CALL** build success

**Comment by mfleisz** [comment]
@godtang just guessing from the error message but you either have to disable the USB redirection channel (`-DCHANNEL_URBDRC=OFF`) or you have to provide the correct libusb headers/library files.
