### ISSUE TITLE
CMake Error at CMakeLists.txt:85 (set_target_properties)

### ISSUE THREAD

**Issue by fengyuyxz** [FreeRDP/FreeRDP#8075]
在macos下执行xcode.sh时报错

CMake Error at CMakeLists.txt:85 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

-- Adding post-build NIB file generation event for MacFreeRDP-library
-- Adding Xcode XIB resources for MacFreeRDP
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.23)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/Users/xuezhouyan/Desktop/flutterworkspace/rdp/FreeRDP/client/Mac/xcode/CMakeFiles/CMakeOutput.log"
[CMakeOutput.log](https://github.com/FreeRDP/FreeRDP/files/9117872/CMakeOutput.log)
.

**Comment by mfleisz** [comment]
@fengyuyxz please provide more information like the used commit for building, your environment etc. as requested in the issue template

**Comment by fengyuyxz** [comment]
My MAC OS version is 11.6.7 and Cmake version is 3.23.2   
Freerdp source code is tag 2.7.0 ，xcode version 13.2.1

**Comment by mfleisz** [comment]
How does your cmake command line look like?

**Comment by fengyuyxz** [comment]
cmake command is 
cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" . && make

**Comment by mfleisz** [comment]
@fengyuyxz are you sure that your git checkout is clean (you can use `git clean -xdf` to be sure)?

In what CMakeLists.txt file does the error occur? I cannot find any CMakeLists.txt file that has a `set_target_properties` call on the line nummer that's stated in your error output.

**Comment by akallabeth** [comment]
@fengyuyxz I guess you try to build from `client/Mac` subdirectory? That will not work, you need to use the top level `CMakeLists.txt`.
