### ISSUE TITLE
MacFreeRDP/MRDPView.h' file not found

### ISSUE THREAD

**Issue by fengyuyxz** [FreeRDP/FreeRDP#8081]
Releated pull request for master: 
I have encountered a new problem. The MacFreeRDP build of the xcode project created by xcode.sh is successful but the archive fails with the error AppDelegate.h MacFreeRDP/MRDPView.h' file not found under MaFreeRDP

**Comment by fengyuyxz** [comment]
MAC OS version is 11.6.7 and Cmake version is 3.23.2
Freerdp source code is tag 2.7.0 ，xcode version 13.2.1
cmake command line
cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" . && make

**Comment by akallabeth** [comment]
Just tried a compile on an `m1` and `x86_64` mac, works.

Please check:
* You start from a clean checkout (`git clean -xdf`)
