### ISSUE TITLE
Multitouch Not Working

### ISSUE THREAD

**Issue by s28400** [FreeRDP/FreeRDP#8084]
Multitouch gestures are not being passed through to the remote. Same issue as I previously described [here](https://github.com/FreeRDP/FreeRDP/issues/7721) now returned.

1. Enable multitouch on connection with a touchscreen computer with latest nightly build installed
2. Test multitouch functionality (pinch, zoom, etc)

Expected behavior:
Multitouch should work as expected on remote connection

Application details:
* FreeRDP version: FreeRDP version 3.0.0-dev (e3cfe7300)
* Command line used: sh -c '/opt/freerdp-nightly/bin/xfreerdp /f /u:user+multitouch /scale:180 /scale-desktop:250 /v:remotehost'
* OS version connecting to (server side): Windows 10

Environment:
 - OS: Linux
 - Version/Distribution: Ubuntu 22.04 LTS
 - Architecture: amd64:

Additional context:
As stated above, the issue was present on pre 3.x.x builds and was working on version 3.0.0-dev (7bb1bc08c).

**Comment by mfleisz** [comment]
@s28400 do you have the possibility to `git bisect` and identify the broken commit?

**Comment by s28400** [comment]
I have been trying to make and install by following the instructions in the readme without success. It builds and installs without error but /usr/local/bin/xfreerdp does not exist and which xfreerdp returns nothing. It does however create some things at /usr/local/include/freerdp3. Is there something I am missing here? Also, is there somewhere I can access older pre-builds? Specifically, I am trying to revert to a build from 7bb1bc0 and then determine which commit broke the multitouch. Thanks!

**Comment by Neustradamus** [comment]
@s28400: Have you seen the @mfleisz comment?

**Comment by carlfarrington** [comment]
git bisect good
650a275ceb3eb2d02732e5adbf9487d58eaaaf62 is the first bad commit
