### ISSUE TITLE
keypress don't work

### ISSUE THREAD

**Issue by jonathanpoelen** [FreeRDP/FreeRDP#8099]
**Describe the bug**

Leaving a key pressed makes a repeat press/release when there should be no release (only a repeat press).

**To Reproduce**

1. Connect to a any RDP server
2. Open a browser on https://w3c.github.io/uievents/tools/key-event-viewer.html
3. Leave a key pressed (ex: T key)

**Expected behavior**

Many keydown, one keyup.

**Screenshots**

With freerdp:

![freerdp](https://user-images.githubusercontent.com/1436727/181767211-791b720e-5ad8-4ad7-b2a5-6045066d6d48.png)

Normally (or with mstsc on Windows):

![normal](https://user-images.githubusercontent.com/1436727/181767213-177870bc-5c56-49eb-a091-bb48ab782816.png)

No keyup and repeat option is checked.

**Application details**

* FreeRDP version (`xfreerdp /version`): **2.7.0**

**Environment (please complete the following information):**

 - OS: [e.g. Linux/Windows/Android/..] Manjaro Linux. Also with Ubuntu 22.04
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]
 - Architecture: [amd64, arm]: amd64

**Additional context**

FreeRDP always sends a packet with `FASTPATH_INPUT_KBDFLAGS_RELEASE` (0x01) / `KBDFLAGS_RELEASE` (0x8000) for slowpath.

> [MS-RDPBCGR] - 2.2.8.1.2.2.1 Fast-Path Keyboard
> 
> 2.2.8.1.1.3.1.1.1 Keyboard Event (TS_KEYBOARD_EVENT)
>
> The absence of this flag indicates a key-down event, while its presence indicates a key-release event.

**Comment by pnowack** [comment]
yeah, it is something that I encountered with xfreerdp (both master and stable-2.0) too. wlfreerdp is not affected by this though.
