### ISSUE TITLE
RDP Server to Client events.

### ISSUE THREAD

**Issue by ra-app** [FreeRDP/FreeRDP#8103]
Hello Team,

i am working on a rdp mobile app and i am using the awesome freerdp libs for it.

but now i want to trigger the client native virtual keyboard automaticly, when the user is connected to a rdp session and his mouse cursor focus is inside a input field.

i would like to know if such event exist in msrdp server and if freerdp has support for such event, i found a lot of docs about event from client to server but nothing about server to client. 

Best Regards,
Saber

**Comment by hardening** [comment]
Hum either it's something server-side, or it's a channel that I'm not aware of that does this...

**Comment by ra-app** [comment]
i think... i found it

the rdp server send's pointer property event's. for me the **text** property is important and i got already this one when i am inside a input field.

![image](https://user-images.githubusercontent.com/53370374/182146098-74c63b6e-7387-4470-9db4-0b4b7f01698c.png)

png/base64:

`AAAAAQkwAAAAAWGbpdyT4lABbvl7uBj47gYpywrctipcsCTCh6Bq2meDoyumfiLweYR5YOkfsYkcsCoij0eIu48jMLLCISxzNRJywxI5bxHGJOWB5kHLYPMI8sMUct4jipcsMSctcQghQswXGSno8RxinLDEnLYrcsMU5bxHFS5YFUo6MHjMeWB5hHlvEcHmCFlgeYQss7g8wQssB8xUtHiOMU5YOkfrjFHLA5GYWW8RwUEVLQMScth1H4VuW8RuB+YUPQPjMLLYOTBCywOTBCy3iNwcjMeWB5hCy2CYxFpwqXLeI4qXLCpctipcsKly3iOKlywrOWxinLDFHLeIvB4yHlgTGEWnYPMjlgeMgst4i8EsVLQMU5a4Koo9A+YIWW8ReMSHLDFOWdwqkdOB5gh5bxHBJir0B0n7B4yFlgeYR5bxHGJHLDEnLXB5hCywPMIst4/jEnLCpctcMSh0A8wQ8tg5DMVMg5DMVM933Ar8mK+X4Q/E3m4GraZjVtMxq2mfkwAd0KU7mI4+gJXQ065UykfxsDzjWXmcMst7t+AyueluD2S8t+uAkCajmTVtEEpJi+oACIP9hmryv9GKSAOoYRMSxAbDzFj/gHzxsGoggX9qmj+v8dzACB2yk1IjT4T2obIdRTSzyz1e8XIBE6heD56bsf8jZBIrnEG611h0MNNMJDQuggONkHolAuTw/oEZIXDR8b736+r+D0JWEpui8XS8sZ8AFrAJwQxzXlHiKRNgAIzCOSJxUIxbLSHwEhFSgJNiCSnUQj/8H44ELsfeD/U1/xPxoR3RVYBTEIaYNDD0aATjFpUwV1Cpff/f4DgAFQDg0nLOhXw7rUjeWsS0AlbCcrvXN6WLf+NgAImGZFRnKhTickPQBj9PmWeKkhskM34ARgSlZpWNbp/GDDvocXAGHXliEGmRX2AyA0fACS7SjIEn+/ALBhaYt7i0YxIwnuIA6FKtaTiVEJMD//e8zG6nOrjpWtIdiYDAKqa4Uhtu+4MJcFheqbQWSrIV3hpBAjqb3/flJg37EMfef/d3bf2kVSI/R/0mkw/k2lv/GwAEZhHJE4qEYtlpD4CQipQEmxBJTqIR/+8YJYwql7n92q8ABloxIclUZLFpD8Y1yuBvrS6MaHj+gA0BiPry0uIM0G9+8PQJ5BaWOFfUrAy4AARD8QUZ5qDqD/QTKXsB3pNERXP/1wAXBiEbpCYeUXoP7wzikEdRcEzWPz9hfzRfjmrtGnC30T89Ih/ytQahdi+B8OwAETDMiozlQpxOSHwA6P06ZZ4ySGyA3/vIlkEyfr07/9tGJQiE1zRZTDYfEGPTEtYT1MSKI7zOkNUl+0XhhrAXZq5qsNg7/8bAAeQHAg1FHiEUHrF3mHIgV7KneVzV+fUAECkwOLbQ1EZ8wHOYoXiKPSoxAuyMNuMgk0gwk9XgFDIRnYf5XSkQ3/7wa7KGMZThuXMuBHyYRl7O4DsSpjA3iMCcIN3xRpFqMD7z2QQO1XoNFIVs+GHgFMcC41BpwZ4XX/vHAhdj7wf6mv+J+HshAOGGAO12NzBq4/qYxSADG+4V37uQDnH/yCSoa5Vdl+/G/GYRyROKhGLZaQ+AkIqUBJsQSU6iEf/vCZA9mkFvUUYZ2An8CGtOKwgvkWRxY/gE6VwyHLsgRQid+8PQJ5BKWOGfUrAz4boGswkshRRpn4Hhh+Ax7Vn6QV3QxJY33zIamKUO9DQt0MNTAd/zDHsNqFiw/Jufs/eKKDq4drJzId/gNvRS/xRg1U/+PIGcAQAAfAYe88+8AAIcz8/A4AAgXgACAEHSw4AAgXgACAEHS//t98AejwAwcjFEKJJN2vXGYAHswBlDjN7caSaP//keAAIBwAh4amDwABAOAEPDZYAWyAEUMM1t1pNo7/+ePAAEA8AQwNTIAuMAnCDd4caRaO//nx4AAgHgCHBssBqIAZQ43WnWkmj//5++MgAIwnhjkF3l4rWJ0GczhPtCacceJ/9Bh4ABUBlpqw4+g6gJEc7BOtKbeccJ/9ACgmpjEE316rWpcAAKAMpFWHn0HUGAAiGtIRxaxOopidECMwTo7oaaaJ/9B/owR3CfH5LjTBP/oAWNIQriVqaRTU+HDP/H6gABAQAB5mAcAAIawfhwADQAKAi5DgAGgAUBFwPwcAA4ACyAhcg4AAgAAAMCyAYuWgWeEI1bTMatpmNW0zGraZgAZQsEyxChTuJU0h6mKZ3HxgABYDLGpmCEk5jgnzahrZ4v8F2CDpjXIQ+8AEeRvnXQCohxgJ7PAbjcuYZpY/AZFI5QVE0wiz/9vLAAboylmkhk6h0oOnMJSrW+XvjcUAAR1tsThxPifE+J8T4nxPifE+J8TyBXA4AAgLAAOByZ+HAAEAIABwDrkOAAIAQADgHXPhwABACAAcA65DgACAEAA4B1wCxwhu73d3Fb/HRqbTMam0zAOCIgY5q2B/b7QJFce0eoqIkX8/wcQzlTMHRldM/EcbB2AaUMp6ga/z9Z+/gABAHnoAL39/3Qh740q44JWdh94AdIFm+1/+5gABYDLGpn5gh+AQDgggwTZfm/wDAOSb/AMA5Jv8AwDkm/wDAOSb/AMA5Jv8AwDkl/BT/N/x/gggwTZfm//+TCFwAF5k2J8hUVkDDzf8f4IIME2X5v//kJxWMU0yMSaZGJNMjEmmAkgAAAAAFhADzJul3JPiUDYvxHBTiYGptM8am0zX044T4rAwRKmQeYTpkYk0yKlpnjJ7Cz6ywdxXxD8Q8sHLHAr8mK+X4Q/E24Gr0zGptMxqbTMJhnAcAAQEgAOBQAAhKJnw4AAgAAAwCgFXIcAAQAAAMBQCrnw4AAgAAAcAq5DgACAAADAcAq43xnEPxA8sc8fxA/csHeBY4mNW0zGraZjVtMxq2mYTCuBwABASAA4FJn4cAAQAAAOARchwABAAADAOARc+HAAEAAADgEXIcAAQAAAwDgEXALJf+CHExq2mY1NpmnVnwmFcDgACAkABwKTPw4AAgAAAcAi5DgACAAABwCLnw4AAgAAAcAi5DgACAAABwCLgFjj973u4h7ljl+BB4MMTBTJmvpp1Z8JhXA4AAgJAAcCkz8OAAIAAAHAIuQ4AAgAAAcAi58OAAIAAAHAIuQ4AAgAAAcAi4BY5Lit8vwUfibwNXpmNTaZjVtMwmFcDgACAkABwKTPw4AAgAAAwHAIuQ4AAgAAAcAi58OAAIAAAMBwCLkOAAIAAAHAIuAWeJjVtMxq2mY1NpmNTaZhMK4HAAEBIADgUmfhwABAAADAOARchwABAAAAwOARc+HAAEAAAMA4BFyHAAEAAADA4BFwCzxMatpmNTaZjU2mY1bTMJhXA4AAgJAAcCkz8OAAIAAAHAIuQ4AAgAAAwHAIufDgACAAABwCLkOAAIAAAMBwCLgFniY1bTMatpmNW0zGraZhMK4HAAEBIADgUmfhwABAAADAOARchwABAAAAwOARc+HAAEAAAMA4BFyHAAEAAADA4BFwCzxMatpmNW0zGraZjVtMwmFcDgACAkABwKTPw4AAgAAAwHAIuQ4AAgAAAcAi58OAAIAAAMBwCLkOAAIAAAHAIuAWeJjVtMxqbTMam0zGraZhMK4HAAEBIADgUmfhwABAAADAOARchwABAAAAwOARc+HAAEAAAMA4BFyHAAEAAADA4BFwCzxMam0zGptMxqbTMam0zCfFYraZGKaZFS0yMU0wCzxMam0zGptMxqZpmNW0zCYZwHAAEBIADgUAAISyZ8OAAIAAAMBwCLkOAAIAAAHAIufDgACAAADAcAi5DgACAAABwCLjQLPExq2mYuJpmNW0zGraZhPisOp0jEmmRW0yK2mAWeEI1bTMam0zGptMwP7zoB63LYPWcsDlblvF8HK3LA9Zy2D7csDlZy3i+D1uWB63LYPWcsD1nLeL4OVuWByty2D7csD1nLeL4PW5YHrctg9ZywPW5bxfBytywOVuWwcrcsDlblvF8HK3LA5W5bBytywOVuW8Xwfblgety2Dlblgcrct4vg5W5YHK3LYPtywOVuW8XwetywOVuWwetywPW5bxfBytywPW5bB63LA9blvF8HrcsD1uWwetywPW5bxfB6zlgcrctg9blgcrct4vg9blgcrctg9blgcrct4vg5W5YHrctg9blgcrct4vg9blgety2D1uWB63LeL4PW5YHrctg9blgety3i+DlblgcrOWwcrcsDlZy3i+D1uWB63LYPW5YHrct4RximmRiTTMHrcsD1nLRUtMDlG0C9N04C3393Jy3fPwn93iH38T93LBxXfF7xWK4rgP6AAAAABYQAeYm6Xck+JQAeZgAAAAAFhAAtkm6Xck+JQAZVg`

which means as soon i get this pointer property i can trigger the the routine to show up the keyboard and hidde the keyboard when the pointer property changes to something else.
