### ISSUE TITLE
Cmake error in Android Studio : find: ‘/cmake’: No such file or directory

### ISSUE THREAD

**Issue by cogandroid** [FreeRDP/FreeRDP#8110]
When I tried to use the FreeRDP of Android,I follow the docs and run the below mentioned command in the terminal:

./scripts/android-build-freerdp.sh --ndk /home/Android/Sdk/ndk/25.0.8775105 --sdk /home/Android/Sdk

And getting the below mentioned error:

find: ‘/cmake’: No such file or directory

And camke is already installed in my system. When i checked the version of the cmake in the terminal . i am getting the below mentioned installed version :
cmake --version
cmake version 3.23.3

Can you please let me know the reason of the above issue.?

So i can proceed further my development.

Thanks.

**Comment by akallabeth** [comment]
you are lacking the `CMake` in android `SDK`
