### ISSUE TITLE
RK3568 ROCK3A Board 4/5000  Whether to support

### ISSUE THREAD

**Issue by skywikia** [FreeRDP/FreeRDP#8117]
RK3568 have v4l2-request patches from libreELEC  
Freerdp h264 avc444 Whether or not compatible

**Comment by mfleisz** [comment]
FreeRDP does not make any use of v4l2 directly. It is able to decode H264/AVC444 using FFmpeg (and what FFmpeg will use for decode depends on your system).

**Comment by akallabeth** [comment]
@skywikia just as @mfleisz said, you can compile against `FFMPEG` and h264 will be decoded with that.
`AVC444` is a composite format thoug, where the YUV420 images of 2 H264 streams have to be combined manually though, so don´t expect miracles performance wise.
