### ISSUE TITLE
I can't ban rdpdr channel in my own module

### ISSUE THREAD

**Issue by chang1532** [FreeRDP/FreeRDP#8128]
I connect to the windows server through freerdp, using freerdp as a proxy。I created a module of my own，and In the plugin.ChannelCreate callback function，when I return FALSE for "rdpdr" channel，I connect to the remote server and it returns failure。

Git Commit: 29af8a45b6170cebc1661ff037d99dd1b266d660

callback function:

```
static BOOL channel_create(proxyPlugin *plugin, proxyData *pdata, void *param)
{
    const proxyChannelDataEventInfo *channel = static_cast<const proxyChannelDataEventInfo *>(param);
    WLog_INFO(TAG, "%s: %s", __FUNCTION__, channel->channel_name);
    
	if (strcmp(channel->channel_name, "rdpdr") == 0)
	{
		WLog_INFO(TAG, "ban rdpdr");
		return FALSE;
	}
	
    return TRUE;
}
```

2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.server] - freerdp-proxy version info:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.server] -       FreeRDP version: 3.0.0-dev
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.server] -       Git commit: bffbaef
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] - Proxy configuration:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -       Server:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               Host: 0.0.0.0
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               Port: 3389
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -       Target:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               TargetHost: CustomHost
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               TargetPort: 3389
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -       Input:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               Keyboard: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               Mouse: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               Multitouch: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -       Server Security:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               ServerTlsSecurity: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               ServerRdpSecurity: FALSE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -       Client Security:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               ClientNlaSecurity: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               ClientTlsSecurity: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               ClientRdpSecurity: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               ClientAllowFallbackToTls: FALSE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -       Channels:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               GFX: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               DisplayControl: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               Clipboard: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               AudioOutput: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               AudioInput: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               DeviceRedirection: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               VideoRedirection: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               CameraRedirection: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               RemoteApp: FALSE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               PassthroughIsBlacklist: TRUE
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -       Clipboard:
2022/08/16 17:09:18 [17:09:07:165] [100862:100862] [INFO][proxy.config] -               TextOnly: FALSE
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -       GFXSettings:
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -               DecodeGFX: FALSE
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -       Plugins/Modules:
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -               Modules[x]: test
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -       Plugins/Required:
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -               RequiredPlugins[x]: test
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -       Certificates:
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -               CertificateFile: server.crt
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -               CertificateContent: (null)
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -               PrivateKeyFile: server.key
2022/08/16 17:09:18 [17:09:07:166] [100862:100862] [INFO][proxy.config] -               PrivateKeyContent: (null)
2022/08/16 17:09:18 [17:09:07:168] [100862:100862] [INFO][proxy.modules] - Loaded plugins:
2022/08/16 17:09:18 [17:09:07:168] [100862:100862] [INFO][proxy.modules] -      Name: test
2022/08/16 17:09:18 [17:09:07:168] [100862:100862] [INFO][proxy.modules] -      Description: this is a tencent plugin for test
2022/08/16 17:09:18 [17:09:07:170] [100862:100862] [INFO][com.freerdp.core.listener] - Listening on [0.0.0.0]:3389
2022/08/16 17:09:18 [17:09:18:587] [100862:101304] [INFO][proxy.modules.test] - server_peer_init
2022/08/16 17:09:18 [17:09:18:590] [100862:101304] [INFO][proxy.server] - [SessionID=97201DE6DF45515011BEBE7F8B8EEA86][pf_server_handle_peer]: new connection: proxy address: 0.0.0.0, client address: 1.1.1.1
2022/08/16 17:09:19 [17:09:18:595] [100862:101304] [INFO][com.freerdp.core.connection] - Client Security: NLA:1 TLS:1 RDP:0
2022/08/16 17:09:19 [17:09:18:595] [100862:101304] [INFO][com.freerdp.core.connection] - Server Security: NLA:0 TLS:1 RDP:0
2022/08/16 17:09:19 [17:09:18:595] [100862:101304] [INFO][com.freerdp.core.connection] - Negotiated Security: NLA:0 TLS:1 RDP:0
2022/08/16 17:09:19 [17:09:18:626] [100862:101304] [INFO][proxy.modules.test] - server_peer_logon: 0
2022/08/16 17:09:19 [17:09:19:715] [100862:101304] [INFO][com.freerdp.core.connection] - Accepted client: test
2022/08/16 17:09:19 [17:09:19:715] [100862:101304] [INFO][com.freerdp.core.connection] - Accepted channels:
2022/08/16 17:09:19 [17:09:19:715] [100862:101304] [INFO][com.freerdp.core.connection] -  rdpdr
2022/08/16 17:09:19 [17:09:19:715] [100862:101304] [INFO][com.freerdp.core.connection] -  rdpsnd
2022/08/16 17:09:19 [17:09:19:715] [100862:101304] [INFO][com.freerdp.core.connection] -  cliprdr
2022/08/16 17:09:19 [17:09:19:715] [100862:101304] [INFO][com.freerdp.core.connection] -  drdynvc
2022/08/16 17:09:19 [17:09:19:715] [100862:101304] [INFO][com.freerdp.core.gcc] - Active rdp encryption level: NONE
2022/08/16 17:09:19 [17:09:19:715] [100862:101304] [INFO][com.freerdp.core.gcc] - Selected rdp encryption method: NONE

2022/08/16 17:10:20 [17:10:20:494] [100862:101305] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off their session on the server.
2022/08/16 17:10:20 [17:10:20:494] [100862:101305] [INFO][com.freerdp.core] - ERRINFO_LOGOFF_BY_USER (0x0000000C):The disconnection was initiated by the user logging off their session on the server.
2022/08/16 17:10:20 [17:10:20:495] [100862:101305] [INFO][proxy.modules.test] - client_post_disconnect
2022/08/16 17:10:20 [17:10:20:495] [100862:101305] [INFO][proxy.modules.test] - client_uninit_connect

**Comment by chang1532** [comment]
I checked where the callback function is called。

**Comment by chang1532** [comment]
Is there something wrong with this change?

**Comment by mfleisz** [comment]
@chang1532 yeah there seems to be something wrong with that commit ... I'll check with @akallabeth asap!

**Comment by akallabeth** [comment]
@chang1532 the reason it works for you with that change is, that with that no channels are loaded at all.
In that case, the RDP session falls back to legacy mode.
If you only ban `rdpdr` then you break the session as `rdpsnd` requires `rdpdr` (which is a somewhat complicated channel with many others depending on it)

**Comment by akallabeth** [comment]
I suggest you have a look at our intercept `rdpdr` implementation and only filter out the messages you don´t want to accept and keep the channel loaded to prevent such issues.
