### ISSUE TITLE
MS-RDPEAI: protocol revision 16 support

### ISSUE THREAD

**Issue by yydcnjjw** [FreeRDP/FreeRDP#8165]
microphone can't create

```
[WARN][com.freerdp.channels.audin.client] - Incompatible channel version server=2, client supports version=1
```

**Comment by edraft** [comment]
Solutions for ubuntu 20.04 for now?? 
Need this fix asap :/

**Comment by akallabeth** [comment]
@edraft added to backported commits in #8343 
for reference: if you want something in a stable release, please tell us or create a backport pull request

**Comment by edraft** [comment]
And how do i get a version installed with this fix?
Manual build fails :/

**Comment by edraft** [comment]
Got it xD
