### ISSUE TITLE
wfreerdp create .pcap file with strange content.

### ISSUE THREAD

**Issue by connected201** [FreeRDP/FreeRDP#8170]
i use latest version from here https://ci.freerdp.com/job/freerdp-nightly-windows/lastBuild/
![image](https://user-images.githubusercontent.com/20506433/188310852-71f8edcb-5526-4d04-88ad-f0a08a90ea34.png)
![image](https://user-images.githubusercontent.com/20506433/188310912-24c2eaaf-e621-4d30-b2bd-0848c1d602d6.png)
i use argument /log-level:trace
Why this file is creating and not deleting automatically?
what mean 74.125.100.200? (this ip is for google servers).
what mean 192.168.1.150? my subnet is 10.10.10.0/24.
![image](https://user-images.githubusercontent.com/20506433/188311134-d06a0d2b-6d63-439a-b5aa-6c2a260bf971.png)

**Comment by hardening** [comment]
With debug level set as trace, all packets are dumped in a pcap file with fake addresses to be able to reread then with wireshark (and so possibly inquiry bugs by examining the traffic).
