### ISSUE TITLE
/dynamic-resolution does not working.

### ISSUE THREAD

**Issue by alphasystems-atr** [FreeRDP/FreeRDP#8176]
**Describe the bug**
After running with /f, /dynamic-resolution does not work when using shortcut keys or float bar to cancel full screen.

**To Reproduce**
1. Run xfreerdp command.

        $ xfreerdp /log-level:DEBUG /f /floatbar:sticky:off,default:hidden,show:always /dynamic-resolution /v:xxx.xxx.xx.x /u:xxxxx

2. Remove the full screen display by manipulating the floatbar (or press ctrl + alt + enter)
3. Resize the window.
4. Automatic resizing does not work.The window size can be adjusted, but the resolution is not changed.

**Expected behavior**
When the window size is adjusted, I would like the resolution to automatically change to match the window size.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/112925337/188556880-65eb5778-5647-4508-929d-572bbd9863be.png)

**Additional context**
the problem did not occur in v2.2.0, but has been occurring since v2.3.0.
In addition to /f, the problem was also reproduced with /multimon.
I am connected to windows 10.

Specifically, the following commit was causing the problem:
d3ed42a7

**Comment by pnowack** [comment]
What version of FreeRDP do you have **exactly** here? Newer will default to gfx (2.7.0+), older ones do not.
Please check a current version (2.8.0), in case you use an older version here (2.3.0 is ancient).
Also, which distro do you use here?

**Comment by hardening** [comment]
@alphasystems-atr the problem is that if we remove these lines that limit the resolution updates, some version of windows server (2012 IIRC) just crash (no access to login screen)

**Comment by alphasystems-atr** [comment]
If you don't specify `/f` or `/multimon`, then `/dynamic-resolution` also works with the latest version.
But, the only solution I found was to remove these lines when specifying these options at the same time so far.

**Comment by leosongwei** [comment]
got same issue on the 2.10.0 (Debian -> Windows 10)

**Comment by pandruszkow** [comment]
I'm seeing the same issue with the latest nightly
