### ISSUE TITLE
Issue with Audio with Microsoft RDGateway 

### ISSUE THREAD

**Issue by iqbalnet1** [FreeRDP/FreeRDP#8180]
When we try to connect RDGateway environment using FreeRDP,  Audio is not working,  when ever i Open Audio settings,  i see it's session is getting feezed.  When i try to connect using Windows RDP to same RDgateway we are not having any isssues.  we are using StratoDesk No-Touch OS who's giving FreeRDP for RDP solution which is having issues with Audio.

**Comment by iqbalnet1** [comment]
We have a Microsoft RDS environment to work for both Internal and External users. For Internal users, the session will go without Microsoft RD Gateway, and everything is working fine with Audio. For any user who's outside,  the RDP session will be redirected through Microsoft RD Gateway. Any session through RD Gateway is having an issue with Audio (both in/out). When we open Audio Settings, RDP session freezes.   

The issue is when we use this with StratoDesk No Touch OS, which uses FreeRDP. If we connect to the same server using Microsoft Windows Client, which is through RD Gateway,  we don't have any issues. The audio is working as expected.  

When we approached,  StratoDesk (noTouchOS) team,  they redirected us to you.   Let us know if you need any more details.

**Comment by akallabeth** [comment]
@iqbalnet1 then please try to reproduce this and create a `xfreerdp` debug log, add the command line you use, the versions of software you have installed, ...
just as requested in the issue template, so we have something to look at.
maybe that is a configuration issue, maybe we have a bug, but without any hints nobody can tell.

And please stop double posting as you´ve done with #8196
