### ISSUE TITLE
Add support for Vietnamese with Telex typing mode

### ISSUE THREAD

**Issue by justapieop** [FreeRDP/FreeRDP#8184]
**Is your feature request related to a problem? Please describe.**
I'm very confused with the built-in Vietnamese layout. It modifies all the numbers keys into other characters which makes it hard to use

**Describe the solution you'd like**
There is a keyboard mode called Telex which is widely used to type Vietnamese, i hope there would be a `kbd` code to make this possible

**Describe alternatives you've considered**
I installed some softwares on the rdp server and change the `kbd` flag on connect but no luck

**Additional context**
no

**Comment by akallabeth** [comment]
@justapieop `RDP` needs to send `scancodes` to the server which are interpreted there with the normal windows keyboard layout (so whatever you install there will be used)
The local keyboard layout is required, as the scancode can only be guessed (you can´t get it easily from most input API)
