### ISSUE TITLE
Issue with Audio with Microsoft RDGateway 

### ISSUE THREAD

**Issue by iqbalnet1** [FreeRDP/FreeRDP#8196]
We have a Microsoft RDS environment to work for both Internal and External users. For Internal users, the session will go without Microsoft RD Gateway, and everything is working fine with Audio. For any user who's outside,  the RDP session will be redirected through Microsoft RD Gateway. Any session through RD Gateway is having an issue with Audio (both in/out). When we open Audio Settings, RDP session freezes.   

The issue is when we use this with StratoDesk No Touch OS, which uses FreeRDP. If we connect to the same server using Microsoft Windows Client, which is through RD Gateway,  we don't have any issues. The audio is working as expected.  

When we approached,  StratoDesk (noTouchOS) team,  they redirected us to you.

**Comment by akallabeth** [comment]
closed as duplicate
