### ISSUE TITLE
FreeRDP Client execution problems in Windows10

### ISSUE THREAD

**Issue by Ranga1987** [FreeRDP/FreeRDP#8206]
I followed the below steps to execute the wfreerdp.exe in Windows 10, but nothing happening after launching the freerdp client
1)  Downloaded code from the below GIT repository
    https://github.com/FreeRDP/FreeRDP
2)  Followed the FreeRDP compilation by following the below documentation.
   https://github.com/FreeRDP/FreeRDP/wiki/Compilation

To avoid libUsb build erros
-------------------------------
cmake . -DCHANNEL_URBDRC=OFF

To Get RDP Server
-----------------
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DWITH_SERVER=ON -DWITH_SAMPLE=ON -DWITH_CLIENT=ON

3) Used Visual studio 2022 to compile the code and able to build the code without any errors.
![image](https://user-images.githubusercontent.com/54504405/190171106-31a1a121-917a-458a-b025-3bac0ea3fc57.png)
4) Pointed build path to Debug folder and got the binaries into the debug folder 
   ![image](https://user-images.githubusercontent.com/54504405/190171570-2db6f11f-17de-42a9-9577-263dbba088db.png)
5) Tried to run with the below command in command prompt to launch wfreerdp.exe
**C:\FreeRdp\FreeRDP\FreeRDP-master\Debug\wfreerdp.exe /v: HOST IP /port:3389 /u:DOMAIN\\USERNAME /p:PASSWORD /cert-ignore**

![image](https://user-images.githubusercontent.com/54504405/190174389-7e2d660a-e0cf-42af-b4f4-c351aec2841d.png)

Am I missing any step to run the FreeRDP client successfully in windows 10?

Even I tried with below latest stable nightly static build binaries (wfreerdp.exe) but it doesn't work.
**C:\FreeRdp\FreeRDP\FreeRDP-master\Debug\wfreerdp.exe /v: HOST IP /port:3389 /u:DOMAIN\\USERNAME /p:PASSWORD /cert-ignore**
https://ci.freerdp.com/job/freerdp-nightly-windows/lastStableBuild/arch=win64,label=vs2013/

**Comment by akallabeth** [comment]
did you check the output of the binary? (on windows you need to do something like `wfreerdp.exe <yourargs>  >logfile.txt 2>&1` to get the output to a file)

**Comment by akallabeth** [comment]
@Ranga1987 looks like the target is not reachable? (network/server down/...?)

**Comment by Ranga1987** [comment]
@akallabeth  Thanks for help, the problem is VM is not reachable at that point of time
