### ISSUE TITLE
extended 2 monitor \Multimon 

### ISSUE THREAD

**Issue by trua88** [FreeRDP/FreeRDP#8226]
When i try to connect from linux to windows machine, instead of making a connection with 2 monitors in extend mode it merges the monitors as if it were a single wide one.
The linux machine is MX_21.2.1 with fluxbox and the windows pc is windows 7.
version of freerdp 2.7.0
the commands I tried are:
xfreerdp /v:172.20.4.72 /u:xxx /multimon /f /monitors:0,1
xfreerdp /v:172.20.4.72 /u:xxx /multimon /monitors:0,1
xfreerdp /v:172.20.4.72 /u:xxx /span /f /monitors:0,1
xfreerdp /v:172.20.4.72 /u:xxx /span /monitors:0,1
xfreerdp /v:172.20.4.72 /u:xxx /multimon
but nothing change
![IMG_9885](https://user-images.githubusercontent.com/51945676/191290149-0ee33220-830c-43a5-a652-fc406d37519f.jpg)
![IMG_9887](https://user-images.githubusercontent.com/51945676/191290161-72e102ca-22e6-43fe-a850-ca4fa16535e7.jpg)

**Comment by akallabeth** [comment]
* which window manager are you using on your local machine?
* Your `buildconfig` would be interesting (maybe a compilation problem?)
* Does the target machine support `multimon`? (not all configurations allow true multimon)

**Comment by trua88** [comment]
Hi @akallabeth
i'm very sorry for the late response, I needed some time to test what you said to me (_not all configurations allow true multimon_).
In the end you were right. 
I connected to a pc with win7 of an industrial control system. i didn't understand that the license was oem professional. (only enterprise and ultimate win7 license allow multimonitor from rdp)

thank you
