### ISSUE TITLE
[backport] Dynamic resolution fix

### ISSUE THREAD

**Issue by fujames1** [FreeRDP/FreeRDP#8242]
Releated pull request for master: 
#8194 
#8236

**Comment by xiuxiu-rgb** [comment]
hello，I found two bugs, Windows 10 configured RDP, connect Windows 7 and Debian System, set dynamic-resolution parameters, can not be maximized, maximized part of the interface is black screen. And use RDP on win systems，with the f parameter full screen. The shortcut keys ctri_alt_enter are not responding. Can You solve these two problems，please?

**Comment by fujames1** [comment]
@xiuxiu-rgb Is this related to these two pull requests?  Is it a different bug?
Which version of FreeRDP are you using?

**Comment by xiuxiu-rgb** [comment]
![微信图片_20220928172728](https://user-images.githubusercontent.com/114569258/192743428-61298aab-d357-47f0-a6e4-ef3c0885f196.jpg)

**Comment by xiuxiu-rgb** [comment]
![微信图片_20220928172916](https://user-images.githubusercontent.com/114569258/192743691-6b47a4e3-ddc8-4891-ab84-f2d53f97bdce.png)

**Comment by fujames1** [comment]
If you are reporting a bug, I'd suggest you create a new issue.  This issue is used to track the commits that need to be backported.

**Comment by xiuxiu-rgb** [comment]
Ok，Thank you
