### ISSUE TITLE
Windows installer not working

### ISSUE THREAD

**Issue by majkinetor** [FreeRDP/FreeRDP#8248]
Latest Windows installer AppSetup from [here](https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds) doesn't work.

It just emits this:

```
---------------------------

---------------------------
old version error
---------------------------
OK   
---------------------------
 ```

Furthermore, repository location doesn't look legit/official.

On related note, I am creating chocolatey package so that we can just `choco install freerdp`. 

I am downloading latest nightly release but it lacks version info, and GitHub releases do not have snapshot at release time. File properties also does not show version, and also command line parameters /help or /? or /version. Is it possible to do any of that so I can determine when to automatically update the package and what version to give it?

**Comment by akallabeth** [comment]
@majkinetor thanks for the info, this is not an installer we provide, there was some wiki vandalism.
Removed this.

**Comment by majkinetor** [comment]
I suspected so.

What about other question? :)

**Comment by akallabeth** [comment]
@majkinetor the nightlies are build every night.
Command line parameters work, but on `cmd` the output is not visible (you need to do something like `wfreerdp.exe /version >log.txt 2>&1` to write the output to a file `log.txt`

**Comment by majkinetor** [comment]
> wfreerdp.exe /version >log.txt 2>&1 

Interesting, that doesn't work from PowerShell, only via cmd.exe. Also this popup doesn't show as described on [Wiki](https://github.com/awakecoding/FreeRDP-Manuals/blob/master/User/FreeRDP-User-Manual.markdown#command-line-interface)

I find it really hard to find out if app is working at all. Initially I thought that it is not static and some dlls are missing. Only when I specify right parameters to connect to remote, it shows that it works.

Anyway, version of nightly build differs from latest released version. I get `This is FreeRDP version 3.0.0` while latest release is 2.8.0, so I can't really use that mechanism. The only thing now that comes to my mind is to monitor releases page for new version, and when I detect it, to get latest nightly build and pack it as a part of that version (which means it may have few commits more).

**Comment by akallabeth** [comment]
@majkinetor we do not ship builds of the stable branch, just nightlies. (with enabled address sanitizer and other debug related stuff)

**Comment by majkinetor** [comment]
FYI, I published automatic package on Chocolatey:
* https://community.chocolatey.org/packages/freerdp.portable

It packages nightly release taken with a day after official GitHub release. Package contains binary so people can download it there or install it with `cinst freerdp.portable --version x.y.z`.

**Comment by akallabeth** [comment]
@majkinetor first thank you for your effort, but I think you mixed up something.
`nightly` are always build from `master` branch, `releases` are from `stable-2.0` branch and they differ quite a lot. You might want to join our matrix chat (see https://freerdp.com for details ) to discuss that a little further.

**Comment by majkinetor** [comment]
I was using the same link available on Download page. This is the only place where working binary could be found. If there is an artifact for stable-2.0 release, or some other location that gets up to date builds, I can quicly change the package.

**Comment by akallabeth** [comment]
@majkinetor there are no binaries for 2.0, but the check for releases just does not make any sense, as `stable-2.0` and `master` are independent branches.

**Comment by majkinetor** [comment]
Yeah, OK, I will remove such dependency and publish it if there is file hash change.
