### ISSUE TITLE
Connect Windows 7 and Debian system can not be maximized with FreeRDP on win10

### ISSUE THREAD

**Issue by xiuxiu-rgb** [FreeRDP/FreeRDP#8256]
**Describe the bug**
Configuring freerdp on a Win10 system, connecting to a win7 or Debian system, maximization keys don't work

**To Reproduce**
1. Configuring freerdp on a Win10 system,  
Configure /dynamic-resolution parameter，connecting to a win7 or Debian system
2. Click on Maximize button
3. See error 

**Environment
 - Windows
 - Version  version 2.8.0

Please solve this problem，thankyou

**Screenshots**
![微信图片_20220928172728](https://user-images.githubusercontent.com/114569258/192927006-19d5e854-437d-4ed2-bfa9-dba5a2e82f35.jpg)

![微信图片_20220928172916](https://user-images.githubusercontent.com/114569258/192927023-f6896213-e8cd-4416-96a5-586aff2cebd5.png)

**Comment by akallabeth** [comment]
well, the RDP server has to actually have this feature supported...

**Comment by xiuxiu-rgb** [comment]
@akallabeth RDP server have this feature supported, Configuring freerdp on a Win10 system, connecting win10 or win11，maximization keys worked.but Win7 not worded

**Comment by xiuxiu-rgb** [comment]
@akallabeth please ，is there something else I need to configure for Windows 7 maximization to work ？

**Comment by xiuxiu-rgb** [comment]
@akallabeth   please，if the the RDP server not supported，Configuring freerdp on a linux system，connecting to a win7 or Debian system, maximization keys work，Why is it that the same configuration of the same code, the client configured into the debain system, can support maximization ？

**Comment by akallabeth** [comment]
@xiuxiu-rgb it is not supported by the RDP server, so nothing we can do. upgrade to a windows version supporting the display channel.
