### ISSUE TITLE
Configure xfreerdp on Windows, connect to any system with full screen , can not switch to non-full screen

### ISSUE THREAD

**Issue by xiuxiu-rgb** [FreeRDP/FreeRDP#8264]
**Describe the bug**
Configure xfreerdp on Windows, connect to any system, configure the/F parameter, use ctrl_alt_enter can not switch to non-full screen

**To Reproduce**
1. configure the /f parameter
>wfreerdp.exe /v:50.50.10.115  /u:nfs /p:123 /dynamic-resolution  /disp /f
3. Click on ctrl_alt_enter
4. No effect

**Environment (please complete the following information):**
 - OS: Windows
 - Version 2.8.0

**Comment by akallabeth** [comment]
there is no `xfreerdp.exe`, what are you talking about?

Do you mean `wfreerdp.exe`? That one is lacking a maintainer, so it does not have all features of `xfreerdp`

**Comment by xiuxiu-rgb** [comment]
Configure xfreerdp on Windows，Compile the generated package using your version 2.8.0 code，is xfreerdp.exe

**Comment by xiuxiu-rgb** [comment]
I compiled your code with VS2019, and you can see that this is the compiled DLL
![123](https://user-images.githubusercontent.com/114569258/193226499-3449e21a-243e-48ed-95f2-98385755e69d.png)

**Comment by xiuxiu-rgb** [comment]
sorry ，I say wfreerdp.exe . Are you saying xfreerdp doesn't work on Windows? There are a lot of things you can't do?

**Comment by akallabeth** [comment]
@xiuxiu-rgb exactly, `xfreerdp` is the `X11` client of `FreeRDP`. Each platform has its own client and some platform clients are more in use than others. (there also might be different keyboard shortcuts et al)
windows client has only recently received some contributions, but it has been neglected for some time, so pull requests are very welcome to bring it up to speed to the current feature set of the library (and `xfreerdp` which uses most of it, as a client that is)

**Comment by xiuxiu-rgb** [comment]
I hope to have full support for xfreerdp on Windows as soon as possible. Thank you
