### ISSUE TITLE
 wfreerdp on Win10: clipboard (local image or file copy) disconnects session upon server side paste

### ISSUE THREAD

**Issue by xiuxiu-rgb** [FreeRDP/FreeRDP#8289]
**Describe the bug**
 Xfreerdp is configured on Win10, a Debian system is connected, a file is copied from Win10, and freerdp crashes

**To Reproduce**
1. connect Debian system
2. Copy file
3. connected crashes

**Application details**
* FreeRDP version (2.8.0`)
* Command line used
* wfreerdp.exe  /v:50.50.10.199  /u:nfs /p:1 +clipboard
*  I looked at the code and the crash location is as follows
* Copying an image or file will crash, copying text will not crash
![image](https://user-images.githubusercontent.com/114569258/194740009-660f408c-2ab3-4d66-9cef-d2980a01097c.png)

**Comment by akallabeth** [comment]
* please define `crash` (sorry, everybody uses that term to describe something different :/)
* do you have some log file for that?

**Comment by xiuxiu-rgb** [comment]
I looked at the code and the crash location is as follows
![微信图片_20221009153649](https://user-images.githubusercontent.com/114569258/194744274-922ad4d0-1b43-423c-bd0b-ef919baba90b.jpg)
log is

![无标题](https://user-images.githubusercontent.com/114569258/194744280-d32bde24-3a59-4ec7-8585-cf40645bf365.png)

**Comment by xiuxiu-rgb** [comment]
This is the whole log, please take a look at
[log.txt](https://github.com/FreeRDP/FreeRDP/files/9743835/log.txt)

**Comment by xiuxiu-rgb** [comment]
@akallabeth Copy any image or file will crash, copy text will not crash
