### ISSUE TITLE
Certificate Verification Failure

### ISSUE THREAD

**Issue by rlaager** [FreeRDP/FreeRDP#830]
I'm getting this error:

Certificate details:
    Subject: serialNumber = yso/UzLuCXKtvGboF6qO1jkwZM-76oi-, OU = GT34316340, OU = See www.rapidssl.com/resources/cps (c)12, OU = Domain Control Validated - RapidSSL(R), CN = HOSTNAME
    Issuer: C = US, O = "GeoTrust, Inc.", CN = RapidSSL CA
    Thumbprint: 4b:88:3e:24:d0:9a:b2:6d:44:00:dd:95:3d:4a:01:cd:27:a9:28
The above X.509 certificate could not be verified, possibly because you do not have the CA certificate in your certificate store, or the certificate has expired. Please look at the documentation on how to create local certificate store for a private CA.
Do you trust the above certificate? (Y/N)

I'm on Ubuntu, so my system-wide certs are in /etc/ssl/certs. If I pass that to openssl s_client, the certificate validates correctly:
openssl s_client -CApath /etc/ssl/certs -connect HOSTNAME:3389

If you'd like to try connecting to the system, I can provide the hostname to FreeRDP developers privately upon request.

I tried fumbling around with patching in SSL_CTX_load_verify_locations() in libfreerdp-core/tls.c with no luck. I also tried adding X509_LOOKUP_add_dir(lookup, "/etc/ssl/certs", X509_FILETYPE_PEM); in libfreerdp-core/crypto.c. Neither seemed to accomplish anything. I may have been doing something else wrong, though.

Any thoughts?

**Comment by akallabeth** [comment]
Master has advanced quite a bit, therefore closing.
Reopen if still an issue.
