### ISSUE TITLE
run script success but no find so lib

### ISSUE THREAD

**Issue by USSTJerry** [FreeRDP/FreeRDP#8332]
command:    ./scripts/android-build-freerdp.sh --ndk /usr/local/sdk/ndk --sdk /usr/local/sdk

result:
[RUN] mkdir -p /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../build
[RUN] bash /home/rui/Workspace/FreeRDP-stable-2.0/scripts/android-build-openssl.sh --src /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../build/openssl --dst /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --sdk /usr/local/sdk --ndk /usr/local/sdk/ndk --arch armeabi-v7a --target 21 --tag openssl-1.1.1q --hash d7939ce614029cdff0b6c20f0e2e5703158a489a72b2507b8bd51bf8c8fd10ca
[RUN] cd /home/rui/Workspace/FreeRDP-stable-2.0
[RUN] mkdir -p /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../build/freerdp-build/armeabi-v7a
[RUN] cd /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../build/freerdp-build/armeabi-v7a
[RUN] export ANDROID_NDK=/usr/local/sdk/ndk
[RUN] /usr/local/sdk/cmake/Bootstrap.cmk/cmake -DANDROID_NDK=/usr/local/sdk/ndk -DANDROID_NATIVE_API_LEVEL=android-21 -DCMAKE_TOOLCHAIN_FILE=/usr/local/sdk/ndk/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=/home/rui/Workspace/FreeRDP-stable-2.0/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_MAKE_PROGRAM=make -DWITH_OPENH264=OFF -DWITH_MEDIACODEC=ON -DWITH_FFMPEG=OFF -DWITH_SWSCALE=OFF -DWITH_DSP_FFMPEG=OFF -DANDROID_ABI=armeabi-v7a -DCMAKE_INSTALL_PREFIX=/home/rui/Workspace/FreeRDP-stable-2.0/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/armeabi-v7a -DCMAKE_INSTALL_LIBDIR=. /home/rui/Workspace/FreeRDP-stable-2.0/scripts/..
/home/rui/Workspace/FreeRDP-stable-2.0
[RUN] cmake --build . --target install
[RUN] bash /home/rui/Workspace/FreeRDP-stable-2.0/scripts/android-build-openssl.sh --src /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../build/openssl --dst /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --sdk /usr/local/sdk --ndk /usr/local/sdk/ndk --arch arm64-v8a --target 21 --tag openssl-1.1.1q --hash d7939ce614029cdff0b6c20f0e2e5703158a489a72b2507b8bd51bf8c8fd10ca
[RUN] cd /home/rui/Workspace/FreeRDP-stable-2.0
[RUN] mkdir -p /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../build/freerdp-build/arm64-v8a
[RUN] cd /home/rui/Workspace/FreeRDP-stable-2.0/scripts/../build/freerdp-build/arm64-v8a
[RUN] export ANDROID_NDK=/usr/local/sdk/ndk
[RUN] /usr/local/sdk/cmake/Bootstrap.cmk/cmake -DANDROID_NDK=/usr/local/sdk/ndk -DANDROID_NATIVE_API_LEVEL=android-21 -DCMAKE_TOOLCHAIN_FILE=/usr/local/sdk/ndk/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Debug -DFREERDP_EXTERNAL_PATH=/home/rui/Workspace/FreeRDP-stable-2.0/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs -DCMAKE_MAKE_PROGRAM=make -DWITH_OPENH264=OFF -DWITH_MEDIACODEC=ON -DWITH_FFMPEG=OFF -DWITH_SWSCALE=OFF -DWITH_DSP_FFMPEG=OFF -DWITH_OPENH264=OFF -DWITH_MEDIACODEC=ON -DWITH_FFMPEG=OFF -DWITH_SWSCALE=OFF -DWITH_DSP_FFMPEG=OFF -DANDROID_ABI=arm64-v8a -DCMAKE_INSTALL_PREFIX=/home/rui/Workspace/FreeRDP-stable-2.0/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs/arm64-v8a -DCMAKE_INSTALL_LIBDIR=. /home/rui/Workspace/FreeRDP-stable-2.0/scripts/..
/home/rui/Workspace/FreeRDP-stable-2.0
[RUN] cmake --build . --target install
Successfully build library for architectures armeabi-v7a arm64-v8a

question: i can not find armeabi-v7a arm64-v8a in my project,and no make jniLibs

**Comment by USSTJerry** [comment]
i meet the same question in version 2.8.1 and 2.0 stable

**Comment by akallabeth** [comment]
@USSTJerry there is a lot of output missing (actually also the relevant parts that contain the `install ` lines)
but look into `/client/Android/Studio/freeRDPCore/src/main/jniLibs/` and you´ll find all the libraries

**Comment by USSTJerry** [comment]
no have  jniLibs dir in my project @akallabeth ,and then i make jniLibs dir in manual,i still can not  find so lib

**Comment by akallabeth** [comment]
@USSTJerry then something is wrong with your `NDK/SDK` (or you are leaving out most of the stuff the scripts print out)

**Comment by USSTJerry** [comment]
you mean that my cmake config is error?

**Comment by USSTJerry** [comment]
@akallabeth i check my cmake path and no find question ,execute cmake --version  show 3.24.1, environment varible is also right.
and i how check that if /usr/local/sdk/cmake/Bootstrap.cmk/cmake is actually executable.

**Comment by USSTJerry** [comment]
i want to ask that how can i execute the project in android studio and include freerdp c code,thank you

**Comment by akallabeth** [comment]
1. `./scripts/android-build-freerdp.sh --sdk <sdk path> --ndk <ndk path>`
2. Open `client/Android/Studio` in `AndroidStudio` or build with `cd client/Android/Studio && ./gradlew assemble`

if that does not work, check your `SDK` and `NDK`. Try the official downloads too, your installation looks broken.

**Comment by USSTJerry** [comment]
execute       ./scripts/android-build-freerdp.sh --sdk <sdk path> --ndk <ndk path>
[RUN] cmake --build . --target install
Error: could not load cache
[ERROR] cmake --build . --target install retured 1

**Comment by USSTJerry** [comment]
execute    ./scripts/android-build-freerdp.sh --sdk <sdk path> --ndk <ndk path>
[RUN] cmake --build . --target install
Error: could not load cache
[ERROR] cmake --build . --target install retured 1

besides ,i do not find CMakeCache.txt file in my project

**Comment by TECHDUSHYANT** [comment]
I am not able to run the script , can you please help me 

$ ./android-build-freerdp.sh --sdk C:\Users\POI\AppData\Local\Android\Sdk --ndk C:\Users\POI\AppData\Local\Android\Sdk\ndk\20.1.5948944
find: ‘/cmake’: No such file or directory
which: no ccache in (/c/Users/POI/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/POI/bin:/c/Program Files/Common Files/Oracle/Java/javapath:/c/Program Files/Microsoft MPI/Bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/DTS/Binn:/c/Program Files/TortoiseGit/bin:/cmd:/c/Program Files/OpenSSL-Win64/bin:/c/Users/POI/AppData/Local/Android/Sdk/cmake/3.18.1/bin:/c/Program Files/CMake/bin:/c/Users/POI/AppData/Local/Microsoft/WindowsApps:/c/Users/POI/.dotnet/tools:/c/Users/POI/AppData/Local/Android/Sdk/cmake/3.18.1/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)
find: ‘C:UsersPOIAppDataLocalAndroidSdk/cmake’: No such file or directory
[RUN] mkdir -p /c/Users/POI/downloads/rdp/freerdp-master/scripts/../build
[RUN] bash /c/Users/POI/downloads/rdp/freerdp-master/scripts/android-build-openssl.sh --src /c/Users/POI/downloads/rdp/freerdp-master/scripts/../build/openssl --dst /c/Users/POI/downloads/rdp/freerdp-master/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --sdk C:UsersPOIAppDataLocalAndroidSdk --ndk C:UsersPOIAppDataLocalAndroidSdkndk20.1.5948944 --arch armeabi-v7a --target 21 --tag openssl-1.1.1s --hash c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa
find: ‘/cmake’: No such file or directory
which: no ccache in (/c/Users/POI/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/POI/bin:/c/Program Files/Common Files/Oracle/Java/javapath:/c/Program Files/Microsoft MPI/Bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/Program Files (x86)/Microsoft SQL Server/150/DTS/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/Tools/Binn:/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/130/DTS/Binn:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/c/Program Files/dotnet:/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn:/c/Program Files (x86)/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/Tools/Binn:/c/Program Files/Microsoft SQL Server/150/DTS/Binn:/c/Program Files/TortoiseGit/bin:/cmd:/c/Program Files/OpenSSL-Win64/bin:/c/Users/POI/AppData/Local/Android/Sdk/cmake/3.18.1/bin:/c/Program Files/CMake/bin:/c/Users/POI/AppData/Local/Microsoft/WindowsApps:/c/Users/POI/.dotnet/tools:/c/Users/POI/AppData/Local/Android/Sdk/cmake/3.18.1/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)
find: ‘C:UsersPOIAppDataLocalAndroidSdk/cmake’: No such file or directory
export ANDROID_NDK to point to your NDK location.
[ERROR] bash /c/Users/POI/downloads/rdp/freerdp-master/scripts/android-build-openssl.sh --src /c/Users/POI/downloads/rdp/freerdp-master/scripts/../build/openssl --dst /c/Users/POI/downloads/rdp/freerdp-master/scripts/../client/Android/Studio/freeRDPCore/src/main/jniLibs --sdk C:UsersPOIAppDataLocalAndroidSdk --ndk C:UsersPOIAppDataLocalAndroidSdkndk20.1.5948944 --arch armeabi-v7a --target 21 --tag openssl-1.1.1s --hash c5ac01e760ee6ff0dab61d6b2bbd30146724d063eb322180c6f18a6f74e4b6aa retured 1
