### ISSUE TITLE
Issue with USB web camera redirection usign "urbdrc" virtual channel

### ISSUE THREAD

**Issue by shivamudugal** [FreeRDP/FreeRDP#834]
Tested in following environment : 

CONTOSO-CLNT : Windows 7 with SP1
RDCB-SRV : Windows Server 2008 R2 with SP1
RDSH-SRV : Windows Server 2008 R2 with SP1
CONTOSO-DC : Windows Server 2008 R2 

Web cam used : Logitech QuichCam pro 9000

Description : When tried to redirect the above said web cam via USB redirection channel(urbdrc), device got successfully redirected which could be verified by checking a device entry in device manager of rdp server. But when we launch any application which will use the web cam, the device gets deleted from the device manager and will be no longer available for use.

**Comment by akallabeth** [comment]
Fixed with #5745
