### ISSUE TITLE
FreeRDP v1.0.1 Connecting to a Farm via a Broker trys to connect to the console session rather than be redirected

### ISSUE THREAD

**Issue by MafooUK** [FreeRDP/FreeRDP#836]
FreeRDP v1.0.1 Connecting to a Farm via a Broker trys to connect to the console session rather than be redirected.
i used 'xfreerdp --no-nla --no-tls -u test-staffember -p yeslikely -d TEST rdfarm.test.lan' to connect

The destination server is Windows 2008 R2 running as a dedicated Farm redirector for the farm
however directly connecting to the farm members themselves works (and correctly redirects if the disconnected session was on a different server)

**Comment by trentasis** [comment]
With latest master branch seems to work

**Comment by akallabeth** [comment]
Related: #965 #1558
