### ISSUE TITLE
Fullscreen resolution issues with xfreerdp under KDE/wayland

### ISSUE THREAD

**Issue by freakynl** [FreeRDP/FreeRDP#8360]
Hi,

I run my laptop with 4 screens. 3 external ones at full HD (1920x1080) that are all 3 next to each other and the laptop screen itself a bit offset under the 3rd one which runs as 1920x1200.

When running xfreerdp on any of the 3 full HD screens going full screen with ctrl+alt+enter seems to get it running at 1920x1200, which causes the bottom part of the screen being invisible. Also note that when running on the 3rd monitor, due to the configuration, one would expect the bottom part on the 4th (laptop) screen partially, but it's not visible there either.
![Screenshot_20221027_153442](https://user-images.githubusercontent.com/3298106/198300438-681a8471-b1f2-452f-a6c6-75835e24487b.png)

Seems to run fine with wlfreerdp by the way, but that doesn't seem to respond to ctrl+alt+enter. Can switch via right clicking the titlebar of the wlfreerdp icon on the taskbar however. No clue so far why the hotkeys aren't picked up.

Running under gentoo linux at moment.

~ $ xfreerdp --version
This is FreeRDP version 2.8.1 (2.8.1)
~ $ wlfreerdp --version
This is FreeRDP version 2.8.1 (2.8.1)

# xfreerdp /buildconfig
This is FreeRDP version 2.8.1 (2.8.1)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_BACKTRACE=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 HAVE_EXECINFO_H=ON HAVE_EXECINFO_HEADER=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -march=native -O2 -pipe -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 12.2.1
Target architecture: x64

# qlist -Iv freerdp kde plasma
dev-libs/plasma-wayland-protocols-1.9.0
kde-apps/ark-22.08.2
kde-apps/audiocd-kio-22.08.2
kde-apps/baloo-widgets-22.08.2
kde-apps/bomber-22.08.2
kde-apps/bovo-22.08.2
kde-apps/dolphin-22.08.2
kde-apps/dragon-22.08.2
kde-apps/ffmpegthumbs-22.08.2
kde-apps/filelight-22.08.2
kde-apps/granatier-22.08.2
kde-apps/gwenview-22.08.2
kde-apps/juk-22.08.2
kde-apps/k3b-22.08.2
kde-apps/kaccounts-integration-22.08.2
kde-apps/kaccounts-providers-22.08.2
kde-apps/kamera-22.08.2
kde-apps/kapman-22.08.2
kde-apps/kate-22.08.2
kde-apps/kate-addons-22.08.2
kde-apps/kate-lib-22.08.2
kde-apps/katomic-22.08.2
kde-apps/kbackup-22.08.2
kde-apps/kblackbox-22.08.2
kde-apps/kblocks-22.08.2
kde-apps/kbounce-22.08.2
kde-apps/kbreakout-22.08.2
kde-apps/kcalc-22.08.2
kde-apps/kcharselect-22.08.2
kde-apps/kcolorchooser-22.08.2
kde-apps/kcron-22.08.2
kde-apps/kdeadmin-meta-22.08.2
kde-apps/kdebugsettings-22.08.2
kde-apps/kdecore-meta-22.08.2
kde-apps/kdegames-meta-22.08.2
kde-apps/kdegraphics-meta-22.08.2
kde-apps/kdegraphics-mobipocket-22.08.2
kde-apps/kdemultimedia-meta-22.08.2
kde-apps/kdenetwork-meta-22.08.2
kde-apps/kdenlive-22.08.2
kde-apps/kdeutils-meta-22.08.2
kde-apps/kdf-22.08.2
kde-apps/kdialog-22.08.2
kde-apps/kdiamond-22.08.2
kde-apps/keditbookmarks-22.08.2
kde-apps/kfind-22.08.2
kde-apps/kfourinline-22.08.2
kde-apps/kget-22.08.2
kde-apps/kgoldrunner-22.08.2
kde-apps/khelpcenter-22.08.2
kde-apps/kidentitymanagement-22.08.2
kde-apps/kigo-22.08.2
kde-apps/killbots-22.08.2
kde-apps/kimagemapeditor-22.08.2
kde-apps/kio-extras-22.08.2
kde-apps/kiriki-22.08.2
kde-apps/kjumpingcube-22.08.2
kde-apps/klickety-22.08.2
kde-apps/klines-22.08.2
kde-apps/kmahjongg-22.08.2
kde-apps/kmines-22.08.2
kde-apps/kmix-22.08.2
kde-apps/knavalbattle-22.08.2
kde-apps/knetwalk-22.08.2
kde-apps/knights-22.08.2
kde-apps/kolf-22.08.2
kde-apps/kollision-22.08.2
kde-apps/kolourpaint-22.08.2
kde-apps/konquest-22.08.2
kde-apps/konsole-22.08.2
kde-apps/kopete-22.08.2
kde-apps/kpat-22.08.2
kde-apps/kpimtextedit-22.08.2
kde-apps/krdc-22.08.2
kde-apps/kreversi-22.08.2
kde-apps/krfb-22.08.2
kde-apps/kruler-22.08.2
kde-apps/kshisen-22.08.2
kde-apps/ksirk-22.08.2
kde-apps/ksnakeduel-22.08.2
kde-apps/kspaceduel-22.08.2
kde-apps/ksquares-22.08.2
kde-apps/ksudoku-22.08.2
kde-apps/ksystemlog-22.08.2
kde-apps/kteatime-22.08.2
kde-apps/ktimer-22.08.2
kde-apps/ktuberling-22.08.2
kde-apps/kubrick-22.08.2
kde-apps/kwalletmanager-22.08.2
kde-apps/kwave-22.08.2
kde-apps/kwrite-22.08.2
kde-apps/libkcddb-22.08.2
kde-apps/libkcompactdisc-22.08.2
kde-apps/libkdcraw-22.08.2
kde-apps/libkdegames-22.08.2
kde-apps/libkexiv2-22.08.2
kde-apps/libkgapi-22.08.2
kde-apps/libkleo-22.08.2
kde-apps/libkmahjongg-22.08.2
kde-apps/lskat-22.08.2
kde-apps/okular-22.08.2
kde-apps/palapeli-22.08.2
kde-apps/picmi-22.08.2
kde-apps/print-manager-22.08.2
kde-apps/spectacle-22.08.2
kde-apps/svgpart-22.08.2
kde-apps/sweeper-22.08.2
kde-apps/thumbnailers-22.08.2
kde-apps/yakuake-22.08.2
kde-frameworks/attica-5.99.0
kde-frameworks/baloo-5.99.0
kde-frameworks/bluez-qt-5.99.0
kde-frameworks/breeze-icons-5.99.0
kde-frameworks/countryflags-5.99.0
kde-frameworks/extra-cmake-modules-5.99.0
kde-frameworks/frameworkintegration-5.99.0
kde-frameworks/kactivities-5.99.0
kde-frameworks/kactivities-stats-5.99.0
kde-frameworks/karchive-5.99.0
kde-frameworks/kauth-5.99.0
kde-frameworks/kbookmarks-5.99.0
kde-frameworks/kcalendarcore-5.99.0
kde-frameworks/kcmutils-5.99.0
kde-frameworks/kcodecs-5.99.0
kde-frameworks/kcompletion-5.99.0
kde-frameworks/kconfig-5.99.0
kde-frameworks/kconfigwidgets-5.99.0
kde-frameworks/kcontacts-5.99.0
kde-frameworks/kcoreaddons-5.99.0
kde-frameworks/kcrash-5.99.0
kde-frameworks/kdbusaddons-5.99.0
kde-frameworks/kdeclarative-5.99.0
kde-frameworks/kded-5.99.0
kde-frameworks/kdelibs4support-5.99.0
kde-frameworks/kdnssd-5.99.0
kde-frameworks/kdoctools-5.99.0
kde-frameworks/kemoticons-5.99.0
kde-frameworks/kf-env-5
kde-frameworks/kfilemetadata-5.99.0
kde-frameworks/kglobalaccel-5.99.0
kde-frameworks/kguiaddons-5.99.0
kde-frameworks/kholidays-5.99.0
kde-frameworks/khtml-5.99.0
kde-frameworks/ki18n-5.99.0
kde-frameworks/kiconthemes-5.99.0
kde-frameworks/kidletime-5.99.0
kde-frameworks/kimageformats-5.99.0-r3
kde-frameworks/kinit-5.99.0
kde-frameworks/kio-5.99.0
kde-frameworks/kirigami-5.99.0
kde-frameworks/kitemmodels-5.99.0
kde-frameworks/kitemviews-5.99.0
kde-frameworks/kjobwidgets-5.99.0
kde-frameworks/kjs-5.99.0
kde-frameworks/knewstuff-5.99.0
kde-frameworks/knotifications-5.99.0
kde-frameworks/knotifyconfig-5.99.0
kde-frameworks/kpackage-5.99.0
kde-frameworks/kparts-5.99.0
kde-frameworks/kpeople-5.99.0
kde-frameworks/kplotting-5.99.0
kde-frameworks/kpty-5.99.0
kde-frameworks/kquickcharts-5.99.0
kde-frameworks/krunner-5.99.0
kde-frameworks/kservice-5.99.0
kde-frameworks/ktexteditor-5.99.0
kde-frameworks/ktextwidgets-5.99.0
kde-frameworks/kunitconversion-5.99.0
kde-frameworks/kwallet-5.99.0
kde-frameworks/kwayland-5.99.0
kde-frameworks/kwidgetsaddons-5.99.0
kde-frameworks/kwindowsystem-5.99.0
kde-frameworks/kxmlgui-5.99.0
kde-frameworks/networkmanager-qt-5.99.0
kde-frameworks/plasma-5.99.0
kde-frameworks/prison-5.99.0
kde-frameworks/purpose-5.99.0
kde-frameworks/qqc2-desktop-style-5.99.0
kde-frameworks/solid-5.99.0
kde-frameworks/sonnet-5.99.0
kde-frameworks/syntax-highlighting-5.99.0
kde-frameworks/threadweaver-5.99.0
kde-misc/kdeconnect-22.08.2
kde-misc/kio-fuse-5.0.1_p20220906
kde-misc/kio-gdrive-22.08.2
kde-misc/markdownpart-22.08.2
kde-plasma/bluedevil-5.26.1
kde-plasma/breeze-5.26.1
kde-plasma/breeze-gtk-5.26.1
kde-plasma/discover-5.26.1
kde-plasma/drkonqi-5.26.1
kde-plasma/kactivitymanagerd-5.26.1
kde-plasma/kde-cli-tools-5.26.1
kde-plasma/kde-gtk-config-5.26.1
kde-plasma/kdecoration-5.26.1
kde-plasma/kdeplasma-addons-5.26.1
kde-plasma/kgamma-5.26.1
kde-plasma/khotkeys-5.26.1
kde-plasma/kinfocenter-5.26.1
kde-plasma/kmenuedit-5.26.1
kde-plasma/kpipewire-5.26.1
kde-plasma/kscreen-5.26.1
kde-plasma/kscreenlocker-5.26.1
kde-plasma/ksshaskpass-5.26.1
kde-plasma/ksystemstats-5.26.1
kde-plasma/kwallet-pam-5.26.1
kde-plasma/kwayland-integration-5.26.1
kde-plasma/kwin-5.26.1
kde-plasma/kwrited-5.26.1
kde-plasma/layer-shell-qt-5.26.1
kde-plasma/libkscreen-5.26.1
kde-plasma/libksysguard-5.26.1
kde-plasma/libkworkspace-5.26.1
kde-plasma/milou-5.26.1
kde-plasma/oxygen-5.26.1
kde-plasma/oxygen-sounds-5.26.1
kde-plasma/plasma-browser-integration-5.26.1
kde-plasma/plasma-desktop-5.26.1
kde-plasma/plasma-disks-5.26.1
kde-plasma/plasma-firewall-5.26.1
kde-plasma/plasma-integration-5.26.1
kde-plasma/plasma-meta-5.26.1
kde-plasma/plasma-nm-5.26.1
kde-plasma/plasma-pa-5.26.1
kde-plasma/plasma-systemmonitor-5.26.1
kde-plasma/plasma-vault-5.26.1
kde-plasma/plasma-workspace-5.26.1
kde-plasma/plasma-workspace-wallpapers-5.26.1
kde-plasma/polkit-kde-agent-5.26.1
kde-plasma/powerdevil-5.26.1
kde-plasma/sddm-kcm-5.26.1
kde-plasma/systemsettings-5.26.1
kde-plasma/xdg-desktop-portal-kde-5.26.1
kde-plasma/xembed-sni-proxy-5.26.1
net-misc/freerdp-2.8.1
sys-libs/libblockdev-2.28

**Comment by akallabeth** [comment]
Need to check that.
For reference, `wlfreerdp` does lack a lot of features, so also the hotkeys :/
