### ISSUE TITLE
Printer shared objects not found anymore since static

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#837]
I cannot redirect my printer anymore since the printer has become static (builtin). The error I get is:

//usr/local/bin/xfreerdp /a:printer,Brother MFC-7460DN Printer,MFC7460DN /u:user /bpp:15 /network:modem /size:1280x960 /v:192.168.0.XX
loading channel rdpdr
loading channel rdpsnd
loading channel cliprdr
connected to 192.168.0.XX:3389
Unable to get current timezone rule
Loading device service drive (static)
Loading device service printer (static)
LoadLibraryA: /usr/local/lib/i686-linux-gnu/freerdp/printer-client.so: cannot open shared object file: No such file or directory
Warning rdpsnd_process_message_formats (261): no formats supported
ERRINFO_RPC_INITIATED_DISCONNECT (0x00000001):
The disconnection was initiated by an administrative tool on the server in another session.

It looks like it is looking in the old location but I thought this plugin was builtin now. Ubuntu 10.10 w/latest git version: 
//usr/local/bin/xfreerdp /version
This is FreeRDP version 1.1.0-dev (git 1.0.1-1456-g6466)

TIA

**Comment by akallabeth** [comment]
The build system has been improved a lot since the last comment, closing. If there are still issues reopen.
