### ISSUE TITLE
Freerdp/client/Android/Studio/freeRDPCore/src/main/cpp

### ISSUE THREAD

**Issue by USSTJerry** [FreeRDP/FreeRDP#8379]
Releated pull request for master: 
i execute  "sudo cmake ." above the path,
report error

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
jnigraphics-lib

but I commented out the library in the cmakeList.txt，

report not find include<jni.h>, but i solve it 
report error
not find include<android/bitmap.h>

**Comment by USSTJerry** [comment]
i want to build for android.so

**Comment by akallabeth** [comment]
check `docs/README.android` in sources.
