### ISSUE TITLE
printer redirection

### ISSUE THREAD

**Issue by elvis-sun** [FreeRDP/FreeRDP#8391]
I am developing printer redirection on wfreerdp-server. 

After research microsoft RDP and related protocol([MS-RDPEPC] [MS-RDPEXPS]), I found there is Remote Desktop Easy Print driver(tspring.dll) which integrated to windows system, that support **xps format data**.

The protocol part([MS-RDPEPC] [MS-RDPEXPS]) I have coded,  but I don't know how to transfer print job and file data from server to client. 

Now I get the xps driver example (XPSDrvSmpl) from Windows-driver-samples, but I am confused that
    1. How to get print job?
    2. the xps format content of print job?
    3. How to get print ticket from xps driver?

**Comment by akallabeth** [comment]
we currently only implement `[MS-RDPEPC]` as converting `XPS` to `PostScript` is quite a challenge and required for anything non windows (`cups` et al speak postscript)
so, if you want to get that done you need to implement the parts in the spec regarding `XPS` support (e.g. `[MS-RDPEXPS]` client and server code.

As for using issues for questions, please prefer contacting us on our matrix chat, see https://freerdp.com for details.

**Comment by elvis-sun** [comment]
> we currently only implement `[MS-RDPEPC]` as converting `XPS` to `PostScript` is quite a challenge and required for anything non windows (`cups` et al speak postscript) so, if you want to get that done you need to implement the parts in the spec regarding `XPS` support (e.g. `[MS-RDPEXPS]` client and server code.
> 
> As for using issues for questions, please prefer contacting us on our matrix chat, see https://freerdp.com for details.

Appreciate your reply.

I has already implement [MS-RDPEXPS] part under wfreerdp-server. Communication is normal between mstsc and wfreerdp-server.
But I have no idea about print job. 
Do you know the format of print job and how to send print job from server to client?
Could you give me some advice about printer driver and print job?

**Comment by elvis-sun** [comment]
Now I acommplish the printing from server to client through xpsdrv and  MS-RDPEXPS protocol.
But how to make the preferences work？
Should I use client printer ticket in server xpsdrv？

**Comment by mfleisz** [comment]
@elvis-sun as already mentioned by @akallabeth you will have to implement the whole MS-RDPEXPS virtual channel in order to be able to do that.

**Comment by elvis-sun** [comment]
> @elvis-sun as already mentioned by @akallabeth you will have to implement the whole MS-RDPEXPS virtual channel in order to be able to do that.

@mfleisz 
I hava implemented the whole MS-RDPEXPS, but I don't know how to make preferences work in client side

**Comment by elvis-sun** [comment]
> @elvis-sun as already mentioned by @akallabeth you will have to implement the whole MS-RDPEXPS virtual channel in order to be able to do that.

Could you give some tips？

**Comment by mfleisz** [comment]
@elvis-sun since we haven't implemented anything of MS-RDPEXPS, I doubt anyone has more information other than what is written in the spec - sorry.

**Comment by elvis-sun** [comment]
> Could you give some tips？



> > @elvis-sun as already mentioned by @akallabeth you will have to implement the whole MS-RDPEXPS virtual channel in order to be able to do that.
> 
> @mfleisz I hava implemented the whole MS-RDPEXPS, but I don't know how to make preferences work in client side

@mfleisz 
I implement the MS-RDPEXPS in wfreerdps-server, then use mstsc to connect wfreerdp-server.
Now I can print document.
Just preferences not work, for example the orientation setting.
