### ISSUE TITLE
freerdp-shadow-cli quits when server sends message containing an update for a 1x1 pointer (with smart sizing)

### ISSUE THREAD

**Issue by conchyliculture** [FreeRDP/FreeRDP#8397]
**Describe the bug**
Running freerdp-shadow-cli as server & freerdp-x11 as a client (with smart sizing), the client will unexpectedly close at random times when using it.

**To Reproduce**
1. Start the server: `freerdp-shadow-cli  /sam-file:.rdprc /sec:nla`
2. Start client `xfreerdp /gfx /u:username /v:server:3389 /smart-sizing:1280x720`  (this resolution is half the server's
3. use client
4. Client will randomly exit

**Expected behavior**
No unexpected exit

**Application details**
* FreeRDP version on both machines : FreeRDP version 2.8.1 (git 2.8.1)
* Command line used: see above
* Output of `xfreerdp /buildconfig` on the client (same on server):
``` [19:58:38:612] [1882223:1882223] [INFO][com.freerdp.server.shadow] - Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_BACKTRACE=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 HAVE_EXECINFO_H=ON HAVE_EXECINFO_HEADER=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 12.2.0
Target architecture: x64
```
* OS version connecting to (server side): Debian Testing amd64
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help: While troubleshooting, I was using debuild to rebuild from the package pulled with apt source freerdp2

**Environment (please complete the following information):**
 - OS: Linux Debian
 - Version/Distribution: Testing
 - Architecture: amd64

**Additional context**
I was able to track the issue to a moment when the client acts on a Pointer update message (I suppose sent from X11):
In function `shadow_client_subsystem_process_message()` of `server/shadow/shadow_client.c`, sometimes `pointerColor->width` & `pointerColor->width` are both set to 1. 

When recieved by the client, scaling is applied in `xf_Pointer_GetCursorForCurrentScale()` in `client/X11/xf_graphics.c`: `xTargetSize` & `yTargetSize` are being scaled to 0 by the arithmetics: `xTargetSize = pointer->width * xscale` (with a xscale less than 1).
Then a `_aligned_malloc(size, 16)` is run against 0 (as `size` = `xTargetSize` * `yTargetSize` * `GetBytesPerPixel(CursorFormat)` ), which fails, triggering a premature `return FALSE`.
This means `update_pointer_new()` also returns FALSE, when called in `fastpath_recv_update()` in `libfreerdp/core/fastpath.c` in the `FASTPATH_UPDATETYPE_POINTER` branch.
The client will then close the connection.

I wasn't able to verify how/why 1x1 sized pointer updates end up on the freerdp shadow server MessageQueue, maybe some weird X11 things?

The issue disappears if I just don't send these messages to the client with
```
if ((pointerColor->width == 1) && (pointerColor->height == 1 )) {
     break;
}
```
in the `SHADOW_MSG_OUT_POINTER_ALPHA_UPDATE_ID` branch of `shadow_client_subsystem_process_message` in `server/shadow/shadow_client.c`

**Comment by akallabeth** [comment]
@conchyliculture I´ve pushed a fix for `xfreerdp` to ensure the cursor is never scaled to `0x0` pixel. Could you give that a try?

**Comment by conchyliculture** [comment]
Looks like it's working!

In case this is helpful, the one way I can trigger the "1px cursor" updates is when moving cursor around in an input field, and send keystrokes
