### ISSUE TITLE
Can't run xfreerdp when compile from source code

### ISSUE THREAD

**Issue by Saddingt0n** [FreeRDP/FreeRDP#8454]
I have a machine running Ubuntu 20.04.5. I follow the compilation guide at: https://github.com/FreeRDP/FreeRDP/wiki/Compilation. I have to change "19.08" to "22.08" or the compilation command will produce an error saying that cannot find flatpak install flathub org.freedesktop.Platform//19.08... in the system.

After compilation process is done (the build log is in the attachment), I go to [build dir]/files/bin, and run "xfreerdp". It shows these error messages:
![xfreerdp_error_log](https://user-images.githubusercontent.com/91487625/203926291-c1152446-c4ee-4305-8ff6-6117cd320cb2.png)

I have another machine running Linux Mint 21 (which is based on Ubuntu 22.04). I did the same steps as I did with the Ubuntu 20.04 machine, the output "xfreerdp" works fine.

Here are the specs of that Ubuntu 20.04 machine:
- OS: Ubuntu 20.04.5
- RAM: 16 GB
- CPU: Intel i7-7700
Please let me know if I need to provide further information. Thank you!
[freerdp_build.log](https://github.com/FreeRDP/FreeRDP/files/10089583/freerdp_build.log)

**Comment by akallabeth** [comment]
so you try to build the flatpak?
then why do you try to run it on your host shell? (that will never work ;))

(we´ve added a convenience build script for flatpak in `packaging/flatpak/build-bundle.sh` meanwhile, just run it and you have a ready to install flatpak bundle)

if you want to compile it to be run in your normal ubuntu shell follow the other build instructions below.
Mainly it consists of installing build dependencies and `cmake -GNinja -B<builddir> -S<sourcedir> -DWITH_CMAKE_INSTALL_PREFIX=<install path> && cmake --build <builddir> --target install`
