### ISSUE TITLE
macfreerdp组合键ctrl+c、ctrl+v和shift+不灵敏，ctrl与shift要先按久点或多按几次，试了几台电脑都是这样

### ISSUE THREAD

**Issue by q819438477** [FreeRDP/FreeRDP#8478]
单独按shift没问题，正常切换输入法中英文，如果想输入！@ #这些组合键shift+，输出的是1 2 3，复制粘贴功能也是这样，组合键ctrl+c、v 就只是输出c v，奇怪就是提前按一下ctrl、shift，再按ctrl+、shift+，偶尔成功，有时要ctrl、shift提前按久点，意思就是不灵敏，确定我键盘没问题，安装软件给其他mac电脑，连接远程windows电脑，试了最新的2.9.0的新包也是这样

**Comment by q819438477** [comment]
试了xfreerdp没问题，不知道为啥macfreerdp有这样现象

**Comment by lv-cpp** [comment]
xiong dei ?

**Comment by akallabeth** [comment]
mac client is currently looking for a maintainer.
