### ISSUE TITLE
windows: --help command outdated

### ISSUE THREAD

**Issue by jonnytest1** [FreeRDP/FreeRDP#8480]
**Found a bug? - We would like to help you and smash the bug away.**

snipped from --help: (but probably also applies to all the other options)
```
Usage: D:\dprogramme\freerdp\wfreerdp.exe [file] [options] [/v:<server>[:port]]
```
but when executing `./wfreerdp.exe /v:<myip>` i get a syntax error 
i played around a bit and found it worked when using 
`./wfreerdp.exe -v:<myip>` however that behaviour is not documented anywhere

**Application details**
* FreeRDP version (`xfreerdp /version`) actually: `wfreerdp.exe --version` ^^ :
`This is FreeRDP version 3.0.0-dev (0623101b6)`
* Command line used
* Output of `./wfreerdp.exe --help` (or when using a wrong syntax)

**Environment (please complete the following information):**
 - OS: Windows

**Comment by akallabeth** [comment]
Ok, just tried this:
1. `.\wfreerdp.exe /version` -> `This is FreeRDP version 3.0.0-dev (0623101b6)`
2. `.\wfreerdp.exe /help` -> prints help
3. `.\wfreerdp.exe /v:<ip> /u:<user> /p:<pwd> /cert:ignore` -> connects

so, please provide the output of said command (`.\wfreerdp /v:<ip> >log.txt 2>&1` will write it to a file `log.txt`)

**Comment by jonnytest1** [comment]
.\\wfreerdp.exe /v:someip >log.txt 2>&1 //had to add \\ instead of \ and missing .exe (i replaced <ip> with someip since > also got me syntax errors )

**Comment by akallabeth** [comment]
@jonnytest1 ok, which shell are you using?
I´ve just tried all of these in `cmd` (and some in `powershell` as well) and they all work as expected.

**Comment by akallabeth** [comment]
also, I´m using the build from https://ci.freerdp.com/job/freerdp-nightly-windows/arch=win64,label=vs2013/

**Comment by jonnytest1** [comment]
ok yes those 2 changes were probably due to using git bash

**Comment by jonnytest1** [comment]
ok all errors were form using git bash oO can stay closed

**Comment by hardening** [comment]
Yeah it's because git bash tries to convert path automatically so as soon as it sees something with a slash it converts it to backslash. There is an environment variable that you can set to avoid that.
