### ISSUE TITLE
One window for each monitor when /multimon

### ISSUE THREAD

**Issue by DasHammett** [FreeRDP/FreeRDP#8482]
**Is your feature request related to a problem? Please describe.**
When working with multiple monitors and specially with tiling window managers, it is very useful to be able to switch workspaces independently from each monitor. With the current implementation of multimonitor in freerdp this is not possible, as there is only 1 window that is expanded (automatically or not) to both monitors and switching to a different workspace moves the entire freerdp window away (that spans 2 monitors).

**Describe the solution you'd like**
A separate window for each monitor would solve this issue. Remote-viewer already does this with the Spice protocol and even qemu with gtk display allow to detach tabs, creating one window for each monitor in the VM.
This would give the freedom to fullscreen just 1 window, move to another workspace on display 2 while display  1 still shows the remote desktop. 
This option will not eliminate the current behavior, whether is fullscreen or not, as it will be possible as well in this new layout of windows.

**Describe alternatives you've considered**
At the moment there are no alternatives that I know of in freerdp/remmina

**Additional context**

**Comment by hardening** [comment]
I suspect that we're not detecting correctly your monitor layout because we do one window per monitor when in fullscreen. So if you just have big one spanning the whole workspace, it's probably because we don't get the layout correctly. Is it `wlfreerdp` or `xfreerdp` ?

**Comment by DasHammett** [comment]
I am using `xfreerdp` compiled with `xinerama` support.
I am using `dwm` as the window manager, also compiled with `xinerama`. When starting `xfreerdp` in fullscreen mode, it will open a window and both monitors will be inside that window.

In order for fullscreen to "work", I need to make the window floating, and then pressing `Ctrl+Alt+Enter` will make the window large enough so that it fits both screens, but it is all contained in 1 window in `dwm`

Please see screenshot:
![image](https://user-images.githubusercontent.com/13760961/205365198-e9999c89-553b-4aee-aa23-53ceba579239.png)

Here's the command:
`xfreerdp /multimon:force /u:<user> /p:<password> /v:localhost /f +fonts -grab-keyboard /monitors:1,0 /smart-sizing /microphone:sys:pulse,format:1,quality:high /audio-mode:sys:pulse,format:1,quality:high +clipboard`

I tried several `/monitors` options, but the output is always contained in one single window

Ideally I would have one `dwm` window for each monitor and I could place each in one monitor. Then I would be able to switch back and forth different workspaces independently.

**Comment by akallabeth** [comment]
@DasHammett could you post the output of `/buildconfig`? I suspect something in the `X11` support missing.

**Comment by DasHammett** [comment]
Output of `xfreerdp /buildconfig`
```
This is FreeRDP version 2.9.0 (2.9.0)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_BACKTRACE=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 HAVE_EXECINFO_H=ON HAVE_EXECINFO_HEADER=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=OFF WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -fgraphite-identity -floop-interchange -floop-strip-mine -floop-block -floop-nest-optimize -march=znver2 -O2 -pipe -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 12.2.1
Target architecture: x64
```
Thanks

**Comment by akallabeth** [comment]
@DasHammett ok, that is ok. what does `xrandr -q` tell you?

**Comment by DasHammett** [comment]
Hi @akallabeth 
Thanks for having a look at this. Please see below the output from `xrand -q` and `xfreerdp monitor-list`
```
[hammett][/home/hammett]$ xrandr -q
Screen 0: minimum 8 x 8, current 4480 x 1440, maximum 16384 x 16384
DVI-I-0 disconnected primary (normal left inverted right x axis y axis)
DP-4.8 connected 2560x1440+1920+0 (normal left inverted right x axis y axis) 553mm x 311mm
   2560x1440     59.95*+
   2048x1152     60.00
   1920x1200     59.88
   1920x1080     60.00    59.94    50.00    29.97    25.00    23.98
   1680x1050     59.95
   1600x1200     60.00
   1280x1024     75.02    60.02
   1280x720      60.00    59.94    50.00
   1200x960      59.90
   1152x864      75.00
   1024x768      75.03    60.00
   800x600       75.00    60.32
   720x576       50.00
   720x480       59.94
   640x480       75.00    59.94    59.93
DVI-I-1 disconnected (normal left inverted right x axis y axis)
HDMI-0 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm
   1920x1080     60.00*+
   1680x1050     59.95
   1440x900      59.89
   1280x1024     75.02    60.02
   1280x960      60.00
   1280x800      59.81
   1280x720      60.00
   1152x864      75.00
   1024x768      75.03    70.07    60.00
   800x600       75.00    72.19    60.32    56.25
   640x480       75.00    72.81    59.94
DP-0 disconnected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
DP-2 disconnected (normal left inverted right x axis y axis)
DP-3 disconnected (normal left inverted right x axis y axis)
DP-4 disconnected (normal left inverted right x axis y axis)
DP-5 disconnected (normal left inverted right x axis y axis)
``` 
```
[hammett][/home/hammett]$ xfreerdp /monitor-list
        [0] 2560x1440   +1920+0
        [1] 1920x1080   +0+0
```

**Comment by keha** [comment]
hello
I have same bug after get december updates Ubuntu 22.04
FreeRDP version 2.9.0

**Comment by keha** [comment]
I found a lot of errors in .xsession-errors, which gave me the idea to create a new user account.
In the new account, freerdp works correctly. Therefore, I think the problem is in the account files.
I then move the .config folder to a temporary location and re-login to the problematic user's account. Freerdp works great!

Then I move back all files from .config folder step by step but no error is returned.

I hope this help someone)

**Comment by DasHammett** [comment]
@keha 
Could you post the errors in your `.xsession-errors` log? I do not have errors in this file, yet the "issue" remains.
Also, what DM/WM are you using? 
Thanks

**Comment by keha** [comment]
.xsession-errors - I will try to search later
DM/WM - KDE/Plasma+SDDM

Try the following:
1. boot from livecd iso Ubuntu/Kubuntu/other distro
2. install freerdp
3. connect in /multimon mode

**Comment by xiaodong777** [comment]
@DasHammett You are a genius. Thanks to you, I have dual monitors. In the Ubuntu22.04 environment, I can successfully use two monitors to remotely access Windows 11. grateful.

**Comment by akallabeth** [comment]
this will not be implemented for `xfreerdp` anymore, but `sdl-freerdp` does it this way.

**Comment by stollr** [comment]
@akallabeth I hope it is okay to ask whether you may explain what `sdl-freerdp` is, were to find it and how to use it? 
The only reference I can find is this link https://www.mankier.com/1/sdl-freerdp
But wjat is the difference to xfreerdp?

**Comment by akallabeth** [comment]
@stollr new client, part of `FreeRDP` repo.
based on `SDL` toolkit, will replace the platform clients.
currently waiting for the next `SDL` release (3.0) as the 2.0 version does not work with clipboard.
