### ISSUE TITLE
ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred

### ISSUE THREAD

**Issue by gotsiboon** [FreeRDP/FreeRDP#852]
Hi guys,

I've got "ALSA lib pcm.c:7339:(snd_pcm_recover) underrun occurred" in todays master (FreeRDP version 1.1.0-dev (git 1.0.1-1519-g1ce9e)).
I'm using these parameters:
xfreerdp /u:user /vc:rdpsnd,sys:alsa,dev:default /mic +clipboard /workarea /v:192.168.x.x:3389

BR, gotsiboon.

**Comment by ivan-83** [comment]
Fix: https://github.com/ivan-83/FreeRDP/commit/8d5825ee007a7889992d5a01e482d1589dd6a7ee
or use: /sound:sys:alsa,format:1,quality:high

**Comment by lhzw** [comment]
/sound:sys:alsa,format:1,quality:high
works for me, thanks a lot!!
