### ISSUE TITLE
RemoteApp goes under the same icon tray

### ISSUE THREAD

**Issue by hbatra917** [FreeRDP/FreeRDP#8520]
### Discussed in https://github.com/FreeRDP/FreeRDP/discussions/8514

<div type='discussions-op-text'>

<sup>Originally posted by **hbatra917** December  9, 2022</sup>
I just had a little concern regarding the fact that when using FreeRDP to start numerous applications, they all appear in the same app tray with the same programme icon.
As an illustration, if I first open Excel and then Powerpoint, Powerpoint appears in the Excel icon tray.

One more thing: when I use FreeRDP for a remote app, the app name does not work and displays as RAIL:00180148. 
![Screenshot from 2022-12-09 17-07-35](https://user-images.githubusercontent.com/120174363/206694205-55814fdb-cd6c-4589-a630-5633b8ab82f6.png)
</div>

**Comment by roland65** [comment]
I have the same problem: all remoteapps get the same icon and the displayed icon is the one of the last started remoteapp.
I get this behaviour with xfreerdp 2.11.2 (Ubuntu 22.04 Linux client, Windows 10 20H2).
