### ISSUE TITLE
Bug in xcrush

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#8528]
#8505 introduced a subtle decoding bug that affects specifically `interleaved` decoding

**Comment by akallabeth** [comment]
@mihainradu looks like you introduced another bug with your fix. Can you give a quick example of how to reproduce your issue?

**Comment by mihainradu** [comment]
I don't have a repro, just a dump.

**Comment by mihainradu** [comment]
@akallabeth we managed to identify the context/some repro for the situation:
```
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    UserAuthentication    REG_DWORD    0x0
    SecurityLayer    REG_DWORD    0x0
```
    
and play a movie in the session it get's to that point after a while
