### ISSUE TITLE
Service Crash temporarily 

### ISSUE THREAD

**Issue by eveliqi** [FreeRDP/FreeRDP#8532]
The freerdp service keeps crashing temporarily under Windows Server 2016, is there a way to fix this?

**Comment by mfleisz** [comment]
@eveliqi there is no such thing as a freerdp service on Windows. FreeRDP is a library implementing the RDP protocol and while it also contains code for various different applications that use that library, none of them is a Windows service.

**Comment by eveliqi** [comment]
after the installation a service is deposited with the name : wsgate, but that's not the point, the problem here is that the service hangs again and again and then doesn't work at all until we restart it

**Comment by mfleisz** [comment]
wsgate is part of https://github.com/FreeRDP/FreeRDP-WebConnect and that project is unfortunately not actively developed/maintained any more.

**Comment by eveliqi** [comment]
Understand, so there is no fix
