### ISSUE TITLE
Specified size not respected anymore (shrinked width) 

### ISSUE THREAD

**Issue by kstest1** [FreeRDP/FreeRDP#8544]
After today upgrade from ubuntu 16.04 to 20.04 (via 18.04), new xfreerdp does not respect specified size.
I have notebook with 3 monitors: built in + 2 same monitors: one on vga + one on hdmi. 
Normally, I used to start xfreerdp over 2 monitors with resolution 3800*1024. This works fine and as monitors have thin edges there is no problem with that setup. 
Howewer, after upgrade, new xfreerdp shrinks width to one monitor ( about 1900 pixels) .  
Additional note: with multimon, I can get xfreerdp over two monitors but there was same other issues with that so I used this setup.  (Issues are not related to xfreerdp, rather to applications)

Used command, xfreerdp version and xrandr follows: 

Command: 
xfreerdp /kbd:0x0000041A /size:3800x1024 /u:XXXX -clipboard +fonts -wallpaper /drive:rdp,/home/XXXXX/rdp /v:192.168.X.X  /sound

x@x:~$ xfreerdp /version
This is FreeRDP version 2.2.0 (n/a)

x@x:~$ more /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

x@x:~$ xrandr
Screen 0: minimum 320 x 200, current 5760 x 1080, maximum 16384 x 16384
eDP-1 connected primary 1920x1080+3840+0 (normal left inverted right x axis y axis) 344mm x 193mm
   1920x1080     60.10*+  60.01    59.97    59.96    59.93    40.06  
   1680x1050     59.95    59.88  
   1600x1024     60.17  
   1400x1050     59.98  
   1600x900      59.99    59.94    59.95    59.82  
   1280x1024     60.02  
   1440x900      59.89  
   1400x900      59.96    59.88  
   1280x960      60.00  
   1440x810      60.00    59.97  
   1368x768      59.88    59.85  
   1360x768      59.80    59.96  
   1280x800      59.99    59.97    59.81    59.91  
   1152x864      60.00  
   1280x720      60.00    59.99    59.86    59.74  
   1024x768      60.04    60.00  
   960x720       60.00  
   928x696       60.05  
   896x672       60.01  
   1024x576      59.95    59.96    59.90    59.82  
   960x600       59.93    60.00  
   960x540       59.96    59.99    59.63    59.82  
   800x600       60.00    60.32    56.25  
   840x525       60.01    59.88  
   864x486       59.92    59.57  
   800x512       60.17  
   700x525       59.98  
   800x450       59.95    59.82  
   640x512       60.02  
   720x450       59.89  
   700x450       59.96    59.88  
   640x480       60.00    59.94  
   720x405       59.51    58.99  
   684x384       59.88    59.85  
   680x384       59.80    59.96  
   640x400       59.88    59.98  
   576x432       60.06  
   640x360       59.86    59.83    59.84    59.32  
   512x384       60.00  
   512x288       60.00    59.92  
   480x270       59.63    59.82  
   400x300       60.32    56.34  
   432x243       59.92    59.57  
   320x240       60.05  
   360x202       59.51    59.13  
   320x180       59.84    59.32  
HDMI-1 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+  50.00    59.94  
   1920x1080i    60.00    50.00    59.94  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x960      60.00  
   1280x720      60.00    50.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
DP-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
   1920x1080     60.00*+
   1680x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      59.89  
   1280x960      60.00  
   1280x720      60.00  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    59.94  
   720x400       70.08  
HDMI-2 disconnected (normal left inverted right x axis y axis)

**Comment by kstest1** [comment]
Thanks for quick response. If you are freerdp maintainer and have multiple versions available now, probably it is fastest way that you try similar connection with resolution that spans more than one monitor with new and old version. I can try to compile some of old versions and see result in next days.

**Comment by akallabeth** [comment]
@kstest1 great. I´ve only got dual monitor setups to test, but maybe that is enough.
A quick way to test is to just install in `/tmp/freerdp` or similar instead of `/usr/local`, that way no files are installed permanently on your system.
