### ISSUE TITLE
RDP 7.1 RemoteFX Broken with Windows 8 / Windows Server 2012

### ISSUE THREAD

**Issue by awakecoding** [FreeRDP/FreeRDP#855]
RDP 7.1 RemoteFX negotiation appears to be broken with Windows 8 and Windows Server 2012, not sure why exactly.

**Comment by akallabeth** [comment]
RFX/GFX working with win 7/8/8.1/10 and server 2008/2012 with c325ec5325d0a7836ef706ee6872976be6a12850
