### ISSUE TITLE
Unable to create a apk/ not able to run project in local

### ISSUE THREAD

**Issue by Pushpan80** [FreeRDP/FreeRDP#8573]
hi, need help to run the project
I am not able to create a apk or run app  in android studio.

I have clone the project and installed NDK and SDK.
After that i have complied the project with the command with script file
./scripts/android-build-freerdp.sh --ndk <ANDROID_NDK> --sdk <ANDROID_SDK>

after that i have imported the stdio project in andriod studio
to build i am using below command to generate  but its not generating the apk.
 ./gradlew assemble

thank you in advance

**Comment by Pushpan80** [comment]
I have updated my ticket please have a look.

thank you in advance

**Comment by akallabeth** [comment]
@Pushpan80 so, could you add the output of `./gradlew assemble`?

**Comment by Pushpan80** [comment]
here is the output of the cmd **./gradlew assemble**

dell@localhost:~/RDP/FreeRDP/client/Android/Studio$ ./gradlew assemble

> Configure project :
----------------- Project configuration -------------------
RELEASE_STORE_FILE: nokeyfile
RELEASE_KEY_ALIAS:  
compile API:        31
target API:         31
min API:            23
tools version:      31.0.0
-----------------------------------------------------------

BUILD SUCCESSFUL in 1s
57 actionable tasks: 10 executed, 47 up-to-date

**Comment by akallabeth** [comment]
@Pushpan80 do a fresh checkout, that is not the output you get from our sources.
should start more like:
```
✔ ~/src/freerdp/client/Android/Studio [stable-2.0|…2⚑ 7] 
13:13 $ ./gradlew assemble

> Configure project :
----------------- Project configuration -------------------
RELEASE_STORE_FILE: nokeyfile
RELEASE_KEY_ALIAS:  
compile API:        31
target API:         31
min API:            23
tools version:      31.0.0
-----------------------------------------------------------

> Configure project :aFreeRDP
Version Name: 2.9.0-21-8083f1d-stable-2.0
Version Code: 2009000
...
```

**Comment by Pushpan80** [comment]
thank you, we able get the above output, but now we are facing below issue

12/26 18:46:49: Launching 'aFreeRDP' on samsung SM-M127G.
Installation did not succeed.
The application could not be installed: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED

List of apks:
[0] '/home/dell/RDP/FreeRDP/client/Android/Studio/aFreeRDP/build/outputs/apk/debug/aFreeRDP-debug.apk'
Installation failed due to: 'INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl2077961563.tmp/base.apk (at Binary XML file line #111): com.freerdp.afreerdp.services.SessionRequestHandlerActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'
Retry
Failed to launch an application on all devices 


thank you in advance
