### ISSUE TITLE
Issues connecting to Windows 11 with remote microphone

### ISSUE THREAD

**Issue by clytbuster** [FreeRDP/FreeRDP#8592]
After upgrading to Windows 11, I seem to be getting issues when remoting in from my POP OS machine using FreeRDP. Attached are the 2 errors I am not getting, the first is when I initiate the connection and the second is when anything tries to use the remote microphone.

Here is my connection syntax: xfreerdp /microphone:sys:pulse,format:1,quality:high /sound:sys:pulse,format:1,quality:high /dynamic-resolution /u:XXX /v:192.168.1.XXX

[13:39:49:703] [16373:16374] [WARN][com.freerdp.core.rdp] - pduType PDU_TYPE_DATA not properly parsed, 562 bytes remaining unhandled. Skipping.
[13:39:55:798] [16373:16413] [WARN][com.freerdp.channels.audin.client] - Incompatible channel version server=2, client supports version=1

I have also completely removed and re-installed the freerdp2 package and still get the same errors.

Has anyone else seen this issue?

**Comment by akallabeth** [comment]
update, the microphone part was fixed with 7cfd97f5316c3c34b4ee4f4f96fafb12abb38ba8, the other thing is just a warning

**Comment by clytbuster** [comment]
So it looks like apt-get only installs 2.6.1. Is there a way to install the newer version in Ubuntu?

**Comment by akallabeth** [comment]
@clytbuster use the flatpak version `com.freerdp.FreeRDP` from flathub
