### ISSUE TITLE
there is no log for xfreerdp

### ISSUE THREAD

**Issue by RyanCode** [FreeRDP/FreeRDP#8598]
I build xfreerdp 
```shell
cmake .. -DWITH_CLIENT=ON -DWITH_X11=ON -DWITH_CAIRO=ON -DWITH_DEBUG_X11=ON -DWITH_DEBUG_X11_CLIPRDR=ON -DWITH_DEBUG_X11_LOCAL_MOVESIZE=ON
```
and i connect remote desktop by xfreerdp:
```shell
WLOG_APPENDER=FILE WLOG_LEVEL=WLOG_DEBUG WLOG_FILEAPPENDER_OUTPUT_FILE_PATH=XXX WLOG_FILEAPPENDER_OUTPUT_FILE_NAME=xfreerdp.log xfreerdp -u xxx  --sec nla -v xxx -p xxx
```
but this is no log from tag x11.something wrong i configured?

**Comment by akallabeth** [comment]
you use the wrong value for ` WLOG_LEVEL`. the definition is:
` LPCSTR WLOG_LEVELS[7] = { "TRACE", "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "OFF" };`

**Comment by akallabeth** [comment]
just tried: `WLOG_FILTER=com.freerdp.channels.rdpgfx.client:DEBUG,com.freerdp.channels.rdpdr.client:DEBUG,com.freerdp.channels.drdynvc.client:debug xfreerdp /v:foo /u:bar /p:something` and theat works nicely.
