### ISSUE TITLE
nightly build wfreerdp, nothing happen, absolutly nothing

### ISSUE THREAD

**Issue by tygerlord** [FreeRDP/FreeRDP#8602]
**Describe the bug**

I run 
`wfreerdp.exe /f /v:192.168.x.x:3389
`
and nothing happen, no window, no message, no crash. Just prompt come back that's all

**Application details**
* FreeRDP version (`xfreerdp /version`)
 The last build today, 2023/01/11
* Command line used
 wfreerdp /?
 wfreerdp /h
 wfreerdp --help
 wfreerdp -h

* Output of `xfreerdp /buildconfig`
 nothing
* OS version connecting to (server side)
 debian, bullseye xrdp
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
NA
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help
NA

**Environment (please complete the following information):**
 - OS: Windows 10

**Comment by akallabeth** [comment]
windows bug, `stdout` and `stderr` are detached for console applications.
try with `wfreerdp.exe <yourargs> >log.txt 2>&1` to get the output

**Comment by G3G4X5X6** [comment]
![image](https://github.com/FreeRDP/FreeRDP/assets/87740076/9d090f1e-bbdb-4469-aa6b-6ea34d957b82)

**Comment by akallabeth** [comment]
@G3G4X5X6 use `cmd.exe` or look up how to redirect `stdout` and `stderr` on powershell.

**Comment by G3G4X5X6** [comment]
@akallabeth Thank you, with your reminder, my doubts have been resolved. The issue lies in the program not providing any feedback when it receives incorrect parameters.
![image](https://github.com/FreeRDP/FreeRDP/assets/87740076/42a0daba-b055-4cac-a08c-6b97c17e6b25)

**Comment by G3G4X5X6** [comment]
Correction, it's not that there was no feedback, but rather it was not displayed in the terminal. After redirecting it to a file, I found that there was correct output.
![image](https://github.com/FreeRDP/FreeRDP/assets/87740076/dd04f773-6e75-4128-a78e-34c8d2c182a1)

**Comment by akallabeth** [comment]
can not reproduce with our nightly builds, entering the command line you have given I get the help output.

```
This is FreeRDP version 3.0.0-dev5 (13b44b8b7)

sha256 E3AF24ED1DAA949A986C876D3BEC4A21BCA3AC56730FF326E195E7A427176BBF *wfreerdp.exe
```

**Comment by G3G4X5X6** [comment]
I want to express that when using the command line in the terminal, there is no output displayed in the terminal itself. However, when redirecting the command line output to a file, you can open the file to see the normal output.

```bash
# no output in cmd (Terminal)
wfreerdp.exe /version

# output redirected in log.txt
wfreerdp.exe /version  >log.txt 2>&1
```
> **_log.txt_**
[10:38:34:15] [24872:00005b80] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_warn_deprecated]: [deprecated] wfreerdp.exe client has been deprecated
[10:38:34:15] [24872:00005b80] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_warn_deprecated]: As replacement there is a SDL based client available.
[10:38:34:15] [24872:00005b80] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_warn_deprecated]: If you are interested in keeping wfreerdp.exe alive get in touch with the developers
[10:38:34:15] [24872:00005b80] [WARN][com.freerdp.client.common.cmdline] - [freerdp_client_warn_deprecated]: The project is hosted at https://github.com/freerdp/freerdp and  developers hang out in https://matrix.to/#/#FreeRDP:matrix.org?via=matrix.org - dont hesitate to ask some questions. (replies might take some time depending on your timezone)
_**[10:38:34:12] [24872:00005b80] [INFO][com.freerdp.client.windows] - [wf_has_console]: Detected stdin=-1 -> gui mode
This is FreeRDP version 3.0.0-dev5 (70a360bf3)**_

**Comment by akallabeth** [comment]
@G3G4X5X6 well, read the explanation in my first reply...
