### ISSUE TITLE
Handle RedirectionGuid and TargetCertificate in ServerRedirection PDUs

### ISSUE THREAD

**Issue by pnowack** [FreeRDP/FreeRDP#8609]
Affected version: master (likely stable-2.0 too, haven't checked)

In `[MS-RDPBCGR] 2.2.13.1 Server Redirection Packet (RDP_SERVER_REDIRECTION_PACKET)`, it is specified, that the ServerRedirection PDU can contain a `RedirectionGuid` and a `TargetCertificate`. These two fields are currently unhandled.

Additionally, if a server sets the `RedirectionGuid` field or the field `TargetCertificate` in addition to the `TargetNetAddresses`, then FreeRDP reads invalid data for the `TargetNetAddresses`, as both the `RedirectionGuid` and `TargetCertificate` are written before the `TargetNetAddresses` field.

Both the `RedirectionGuid` and the `TargetCertificate` should be read, when receiving the ServerRedirection PDU. In addition to that, the `LB_PASSWORD_IS_PK_ENCRYPTED` flag should be handled.

**Comment by pnowack** [comment]
Seems like the `LB_DONTSTOREUSERNAME`, `LB_SMARTCARD_LOGON`, `LB_SERVER_TSV_CAPABLE` flags are currently unhandled too.

**Comment by akallabeth** [comment]
@pnowack ok, did create #8611 to add basic parsing support for these fields.
Not all flags are handled there, but the read/write routines should work.
