### ISSUE TITLE
Screen tearing on fedora mate 37

### ISSUE THREAD

**Issue by j6b72** [FreeRDP/FreeRDP#8619]
Hi,

I am using an up-to-date Fedora Mate 37 and am experiencing major screen tearing every time I move a window. I did not notice that of freerdp while I was still using Arch Linux with KDE, so I don't think that's intentional behavior. I'd much rather have VSYNC, so that I get my frames a little later, but complete. The rest of the system is entirely screen-tearing-free, also, the setting "Sync to VBLank" is toggled.

I tested it using 1) the latest version from the repos (2.9.0) and 2) a self-built version from the repo master yesterday (3.0.0-dev). Setting /network:auto reduces it but doesn't eliminate it entirely. Settings like /gfx, /rfx do actually improve the performance, but don't help the screen tearing. Using the self-built xfreerdp I was able to use /gfx:AVC444 & AVC420, which sadly also didn't help.

Do you know any other command line arguments or settings I could try? 

Fedora MATE works great otherwise, but I work through RDP every day and getting that cleared up would make a huge difference for me. Thank you so much.Do you know any other command line arguments or settings I could try? 

**Update**: I am able to connect tear-free using remmina - with default settings. The "Color depth" setting influences, whether I get screen tearing or not:

- Screen Tearing: RemoteFX, True Color, High Color, 256 Colors
- No Screen Tearing: Automatic, GFX RFX. GFX RFX (progressive)

I think, that should give a clear indication - I wasn't able to find out what the exact freerdp "command" to that option would be, and I pretty got lost in the remmina source code pretty early on in my search, but I think being able to set that kind of option on my normal xfreerdp command would solve, my issues, right? Sadly /gfx doesn't seem to be that option, at least that, as I said earlier, doesn't help...

**Comment by akallabeth** [comment]
@j6b72 that setting also switches between the different graphic modes of `RDP`:
* `bpp16/24/32` is windows NT/XP style (e.g. mostly bitmaps nowadays)
* `rfx` is a windows 7 age codec and transport
* `gfx` (with all sub categories) is windows 8 and newer style (the only one that might be able to give you what you want)

There is also a (implicit) setting influencing this, that is the `/network` switch (it turns on or off some bandwidth measurement, ...)

The most important thing to remember is: All these settings are mere suggestions, in the end the server decides what will be used. So you need to verify your server does send you what you requested and does not fall back to something else.

That being said, we did switch to default to `/network:auto` behavior with newer releases as that is (in most cases) the optimal solution for you. Just  do not add any of the `/bpp`, `/rfx`/ `/gfx` or `/network` options and it should work

**Comment by pnowack** [comment]
There are two possible sources for screen tearing:

The first way is the application being an x11 application (using xfreerdp, Remmina as x11, etc.). That is something, that cannot changed, as tearing is one problem of x11 itself.

The other way is by how updates are received from the server side. With the graphics pipeline, all updates must happen in logical frames, which are separated by FrameStart and FrameEnd PDUs.  
Only after the FrameEnd PDU, the client is allowed to display the resulting bitmap onto the screen.

Without the graphics pipeline (legacy path), the behaviour depends on the server submitting frame markers. In the legacy path, frame markers are optional.
So, if the server side does not send frame markers, there is nothing we can do here.

> No Screen Tearing: Automatic, GFX RFX. GFX RFX (progressive)

If we just leave the actual part away, that this depends on the actual caps exchange and assume, that all modes are supported by the server side, this leads to the graphics pipeline, where logical frames are enforced.

> Screen Tearing: RemoteFX, True Color, High Color, 256 Colors

Same here with the caps exchange. However, regardless of the codecs and caps here, frame markers are in the legacy path not obligatory. In other words: Nothing we can do here.

**Comment by j6b72** [comment]
Thanks for all the info!

I should have mentioned, the RDP server I'm mainly connecting to is a Windows 10 Pro on all the latest updates, so it should have all the features, right?

Sadly, just using xfreerdp (2.9.0 or 3.0.0-dev) without any flags other than the specified host & user name still has screen tearing - remmina, in its default setting, doesn't. How can I find out on the server side which settings are used? In the event viewer, there's  Applications and Services Logs -> Microsoft -> Windows -> RemoteDesktopServices-RdpCoreTS, which sadly doesn't include much information (other than the fact that it can't be AVC becuase that would've been logged differently).

How would you go about debugging this, is there anything I can do aside from just using remmina instead from now on?

Thank you so much.

**Comment by akallabeth** [comment]
@j6b72 from the description you experience the issue described by @pnowack (`X11` tearing)
you can debug this by enabling the client debug log `/log-level:debug` (or `/log-level:trace` for even more). Depending on which codec is used a different log entry is written (if there is something like `com.freerdp.channels.rdpgfx.client` or `progressive` or `clearcodec` then the graphics pipeline is in use)

**Comment by j6b72** [comment]
Thank you for your help!

Using the command `xfreerdp /log-level:debug /v:xxxx /u:xxx /p:xxxx /gfx +window-drag` I get the following log: https://paste.ee/p/hxRuk
Seems like the graphicss pipeline is in use, I can see `progressive`. But if I added /gfx, shouldn't it be `com.freerdp.channels.rdpgfx.client`?

Using remmina with settings where I gdoN't get screen tearing (plus loglevel debug set in the settings), I get the following output: https://paste.ee/p/HyJjq

(both recorded by running in command line and piping it via | tee <file>).

I notice that the remmina log has a lot more "PROGRESSIVE_WBT_TILE_UPGRADE" and "PROGRESSIVE_WBT_TILE_FIRST"s, does this have something to do with my issue? Seems like they both are using `progressive` of some sort.

**Comment by akallabeth** [comment]
@j6b72 both are using the same codec, so it is likely to assume it is the `X11` related tearing. `Remmina` uses `GTK` for drawing, so depending on your environment that is `X11` or `Wayland` based
