### ISSUE TITLE
I don't understand why the parameters I set don't work

### ISSUE THREAD

**Issue by RyanCode** [FreeRDP/FreeRDP#8627]
WLOG_LEVEL=DEBUG WLOG_FILTER=com.freerdp.client.x11:DEBUG xfreerdp -u foo  --sec nla -v 192.168.1.51 -p bar
I think `WLOG_LEVEL=DEBUG` effective，but WLOG_FILTER not.

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/61410262/213340572-8b8cc297-1bd0-481c-894a-d2207ed1fb21.png">

**Comment by akallabeth** [comment]
* `WLOG_LEVEL` sets the default debug level (e.g. all entries)
* `WLOG_FILTER` only sets the level for the specified `tags`
* setting both to `debug` is useless, more interesting is something like `WLOG_LEVEL=warn WLOG_FILTER=com.freerdp.client.x11:debug`

**Comment by RyanCode** [comment]
> * `WLOG_LEVEL` sets the default debug level (e.g. all entries)
> * `WLOG_FILTER` only sets the level for the specified `tags`
> * setting both to `debug` is useless, more interesting is something like `WLOG_LEVEL=warn WLOG_FILTER=com.freerdp.client.x11:debug`

Thank you very much, so it is
