### ISSUE TITLE
Redirect a USB Webcam from linux to windows.

### ISSUE THREAD

**Issue by wrutab** [FreeRDP/FreeRDP#8647]
Hello, i tried to connect to windows through FreeRDP(From Linux os), is their any way to enable the option that attached in the image to redirect usb webcam to the client 

![WhatsApp Image 2023-01-26 at 6 20 48 PM](https://user-images.githubusercontent.com/60518370/214885501-e342b3d6-d832-47fa-a660-31c4367cef33.jpeg)

**Comment by akallabeth** [comment]
1. there is `/usb` which does low level `USB` redirection (works for webcam, but needs lots of bandwidth, might be slow)
2. you can try out `FreeRDP`  based clients like https://flathub.org/apps/details/com.thincast.client
