### ISSUE TITLE
Excuse me, is there a commercial version (paid version) of this project?

### ISSUE THREAD

**Issue by 747857485** [FreeRDP/FreeRDP#8652]
Excuse me, is there a commercial version (paid version) of this project?

**Comment by bmiklautz** [comment]
@747857485 FreeRDP is an open source project and there is no 'commercial' version however there are many projects and products that use FreeRDP:

* https://remmina.org - very good GUI that integrates FreeRDP - open source (Linux)
* https://thincast.com/en/products/client - commercial product with support (Windows/macOS/Linux)
* https://royalapps.com/ts/mac/features - (macOS)

There are also others.

Depending on your need (client/library/server side) there are companies that provide commercial support for FreeRDP https://www.freerdp.com/support .
