### ISSUE TITLE
 needed by libfreerdp-android.so, missing and no known rule to make it

### ISSUE THREAD

**Issue by skyjie6** [FreeRDP/FreeRDP#8655]
I clone the code for Android Studio and run the project from client\Android\Studio\.
but it went wrong and get the build output:

`Build command failed.
Error while executing process D:\AndroidManager\sdk\cmake\3.18.1\bin\ninja.exe with arguments {-C D:\FreeRDP\client\Android\Studio\freeRDPCore\.cxx\Debug\3r4p5162\arm64-v8a freerdp-android}
ninja: Entering directory `D:\FreeRDP\client\Android\Studio\freeRDPCore\.cxx\Debug\3r4p5162\arm64-v8a'

ninja: error: 'D:/FreeRDP/client/Android/Studio/freeRDPCore/src/main/jniLibs/arm64-v8a/libfreerdp3.so', needed by 'D:/workDemo/rdp/0131/FreeRDP/client/Android/Studio/freeRDPCore/build/intermediates/cxx/Debug/3r4p5162/obj/arm64-v8a/libfreerdp-android.so', missing and no known rule to make it

`

I checked the cmakelists.txt but found nothing.
how could it build? thanks

**Comment by akallabeth** [comment]
1. https://github.com/FreeRDP/FreeRDP/blob/master/docs/README.android
1. windows is not supported by the build scripts.
