### ISSUE TITLE
Replace TCPConnect with a custom channel 

### ISSUE THREAD

**Issue by KangLin** [FreeRDP/FreeRDP#8665]
**Is your feature request related to a problem? Please describe.**

I have [a P2P channel (It has the functionality of TCP) ](https://github.com/KangLin/RabbitRemoteControl/blob/master/Channel/ICE/ChannelIce.h) and want to replace TCPConnect with it.

**Describe the solution you'd like**

```
typedef int (*pTCPConnect)(rdpContext* context, rdpSettings* settings, const char* hostname,
	                           int port, DWORD timeout);
typedef BOOL (*pTransportAttach)(rdpTransport* transport, int sockfd);
```

This function binds sockfd, which does not represent a custom channel.
I want to replace int sockfd with void* pTcpChannel:

```
typedef void* (*pTCPConnect)(rdpContext* context, rdpSettings* settings, const char* hostname,
	                           int port, DWORD timeout);
typedef BOOL (*pTransportAttach)(rdpTransport* transport, pTcpChannel);
```

**Comment by akallabeth** [comment]
Already available, just write your own transport.
If you do not use sockets of any kind you can also pass in and cast any data that fits the `int`.
if that is not good enough, there is `fmemopen`, `fileno` and `dup` to have a in memory file that can pass any data you want.

**Comment by KangLin** [comment]
Fmemopen, Fileno and DUP are not available on all systems.

**Comment by akallabeth** [comment]
but sockets are, this was just (one) example of how to use that.
