### ISSUE TITLE
Unable to run cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" . && make

### ISSUE THREAD

**Issue by pushpan70** [FreeRDP/FreeRDP#8666]
We are Compiling the Cmake but we are getting the following error

**UBUNTU :** 
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04

**CMAKE : 3.22.1**

we are unable to install cmake  2.8.12  version not supported.

**cmake -D "CMAKE_OSX_ARCHITECTURES:STRING=x86_64" . && make**

**Error**

CMake Deprecation Warning at CMakeLists.txt:21 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

**Comment by akallabeth** [comment]
1. sorry, what is your question/the issue?
2. are you compiling on `Ubuntu 22.04.1 LTS` or `Mac OS`? `CMAKE_OSX_ARCHITECTURES:STRING=x86_64` is, as the name implies, an option for `OSX` only

**Comment by akallabeth** [comment]
so, just to clarify:

1. `CMake` version `2.8` is the minimum required for our builds on stable branch (will change on master), you can always use newer versions.
2. Better build using: (NOTE: `-GNinja` is optional, but faster)
     1.  `cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<install path> -B<builddir> -S<sourcedir>
     1. `cmake --build <builddir> --target install`
