### ISSUE TITLE
How FreeRDP sets the MaximumTransferSize property of the USB storage device In USB redirection

### ISSUE THREAD

**Issue by zhengguimin** [FreeRDP/FreeRDP#8667]
**Describe the bug**
Our project needs to increase the copy rate of the U disk In USB redirection. We did not find a way to set this property on the FreeRDP client, 
But found it on the Windows server.

To increase the maximum transfer size of USB storgae devices, follow these steps:
1. Click Start win, type regedit int the Start Search box, and then press Enter.
2. Locate and then click the following registry subkey:
	HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\usbstor\VVVVPPPP
3. Click Edit, point to New, and then click DWORDValue.
4. Type MaximumTransferLength, and then press Enter.
5. Click Edit, and then click Modify.
6. In the Value data box, type a value in the 64 KB-to-1 MB range. For example, select Decimal,and type a value in the range of 65535 (64 KB) to 1048576 (1 MB).

But we wonder if the FreeRDP client can tell Windows Server to set this property.

**Application details**

FreeRDP version
master
Command line used
xfreerdp /f /u: /p:
OS version connecting to (server side)
Windows server 2022

OS: Linux
Version/Distribution: Rockchip RK3568
Architecture: arm64

**Comment by akallabeth** [comment]
@zhengguimin ok, then 
1. `there will be dragons ahead`. You are using the `usb` redirection for device classes that are not supported by the server side. (`mass storage`, `HID` and such classes are filtered)
1. If you are using `drive` redirection on the other hand, then that is not a `usb` device for the server, as the redirection is on file level
