### ISSUE TITLE
I wonder if the ios version is still being maintained? I compiled the ios version, and I also referred to docs/README.ios, but there are still some issues, hopefully they will be fixed.

### ISSUE THREAD

**Issue by cbjin** [FreeRDP/FreeRDP#8670]
Releated pull request for master: 
 FreeRDP-master % cmake -DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake -GXcode 
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error at cmake/ios.toolchain.cmake:204 (message):
  PLATFORM argument not set.  Bailing configure since I don't know what
  target you want to build for!
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:121 (include)
  CMakeLists.txt:23 (project)

-- Configuring incomplete, errors occurred!

**Comment by akallabeth** [comment]
@cbjin currently nobody is actively working on `iOS` client. It is still compiled by the pull request tester, but if the client actually works nobody has checked for a while.

That being said, if you are interested in working with it we do appreciate pull requests for fixing issues.
You might need to:

1. Update the `OpenSSL` build scripts
2. Update the `ios.toolchain.cmake` (you can just use any working toolchain file or create one)
3. Most likely add `FFMPEG` to the build (modern RDP requires image scaling support which we do with`swscale`, you also might need `OpenH264` for H264 support)
