### ISSUE TITLE
Need to add rdp protocol settings

### ISSUE THREAD

**Issue by pushpan70** [FreeRDP/FreeRDP#8674]
How to add the **Rdp Protocol settings** in the OpenURL??
What steps I need to followed to add the protocol settings. 
**Need to add the Below settings :**
Clipboard OFF Done
Compression: OFF
Network Connection: i:7
Themes: off
Wallpaper: off
gdi: sw
RFX: On
RFX: Video

**Comment by akallabeth** [comment]
@pushpan70
1. you´re talking about the android client?
2. `Compression` you don´t need (it does nothing)
3. `gdi:sw` you don´t need, it is default (and no `/gdi:hw` exists for android, only `xfreerdp` has something that implements `/gdi:hw`)
4. `RFX:video` you don´t need (it is more or less useless)

**Comment by pushpan70** [comment]
yes for the android client

**Comment by pushpan70** [comment]
**Thank You for the quick response.**

Can you please help with the other  **Rdp protocol settings** that I have mentioned below:
NSC: on
Jpeg: on
Jpeg Quality: 50%
mouse motion: 0ff
bitmap Cache: on
OffScreen Cache: off
glyph-cache: off
code-cache: RFX
Fast-Path: off

**Comment by akallabeth** [comment]
1. `Jpeg` is a custom extension nobody supports any more
2. you don´t want to turn off `fastpath` (we removed that from `master` branch altogether)
3. `nsc`, `glyph-cache`, `offscreen-cache`, `bitmap-cache` are ok
4. `codec-cache` is useless, just use `bitmap-cache`
5. you´re missing any settings with `/gfx` - that is anything that is newer than windows 7 uses that ;)

**Comment by pushpan70** [comment]
Thank You for the response
