### ISSUE TITLE
video quality and the connection speed

### ISSUE THREAD

**Issue by pushpa1226** [FreeRDP/FreeRDP#8679]
Hello,

since I am using **FreeRdp**. The problem is the video quality and the connection speed. When I open up the YouTube ,the video quality is very low, it is coming  frame by frame.  

What settings required for the /gfx?? Is /gfx is the reason for the poor performance of the video?

Any idea about this problem?

Thanks in advance

**Comment by akallabeth** [comment]
@pushpan70 a few more details please?
1. what are you using? (e.g. which freerdp version/build)?
2. what is your hardware (
3. what is your connection setting (4k multimon or just simple small resolution window?)
4. what is your remote target (e.g. a windows RDP server? which version?)
5. how do you connect? (command line / rdp file options/...)

**Comment by pushpan70** [comment]
@akallabeth Here are the details:
1. FreeRDP stable-2.0
2. UBUNTU : Ubuntu 22.04.1 LTS
3. Default Resolution is 1024X768
5. Using openUri : freerdp://user@ip:port/connect?sound=&rfx=&p=password&clipboard=%2b&themes=-

**Comment by akallabeth** [comment]
@pushpan70 ok, try command line with just `xfreerdp /v:<host>[:<port] /u:<user> /p:>pwd>` and check again.
FYI:
* the ubuntu packages do not contain `h264` support
* you might try our flatpak `com.freerdp.FreeRDP` instead which has that enabled.

**Comment by akallabeth** [comment]
@pushpan70 also, `openUri`? you were talking about the android client or do you have your own private fork?
