### ISSUE TITLE
wfreerdp has no floatbar and wont let me get out of fullscreen.

### ISSUE THREAD

**Issue by Ajith-Chandran-K** [FreeRDP/FreeRDP#8700]
Hi I am kinda new the entire freerdp world and I am finding myself unable to toggle fullscreen. My build also does not show a floatbar on top of the session. Once I go fullscreen I am stuck in the fullscreen till I disconnect. I use WFreeRDP that I built myself.

 Attaching my build config as well

This is FreeRDP version 3.0.0-dev (n/a)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H= WINPR_HAVE_EXECINFO_HEADER= WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R= WINPR_HAVE_GETPWUID_R= WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP= WINPR_HAVE_SYSLOG_H= WINPR_HAVE_SYS_EVENTFD_H= WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H= WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H= WINPR_HAVE_TM_GMTOFF= WINPR_HAVE_UNISTD_H= WINPR_HAVE_UNWIND_H= WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=ON WITH_CLIENT_SDL=OFF WITH_CLIENT_SDL_AVAILABLE=1 WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_DSP_FFMPEG_AVAILABLE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FLOATBAR=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=OFF WITH_NATIVE_SSPI=ON WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=ON WITH_OPENSSL=ON WITH_PROFILER=OFF WITH_PROGRESS_BAR=ON WITH_SAMPLE=OFF WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_EMULATE=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=0 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=OFF WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WIN8=OFF WITH_WINDOWS_CERT_STORE=ON WITH_WINMM=ON WITH_WINPR_DEPRECATED=ON WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=OFF WITH_ZLIB=ON

I did not have a WITH_FLOATBAR so when I built using cmakegui I added a boolean variable using -WITH_FLOATBAR.

Kindly help me out coz I am new to the entire thing. Thank you.

**Comment by yaBobJonez** [comment]
Still the same issue for me, on Fedora 42 KDE with FreeRDP 3.16.0

**Comment by NoHow81** [comment]
Same here. Floatbar is not shown. wfreerdp 3.17.3-dev0 on Windows 11 24H4 with the following CLI options:
`/floatbar:sticky:on,default:visible,show:always`

**Comment by Darkar25** [comment]
Same here. Floatbar is not shown. wfreerdp 3.17.3-dev0 on timy10 with the following CLI options: `/floatbar:sticky:on,default:visible,show:always`
