### ISSUE TITLE
No binaries of FreeRDP nightly for Windows to download @ Jenkins server

### ISSUE THREAD

**Issue by uploadersoasis** [FreeRDP/FreeRDP#8725]
I am not seeing any artifacts to download at [https://ci.freerdp.com/job/freerdp-nightly-windows/](https://ci.freerdp.com/job/freerdp-nightly-windows/)

![ci freerdp com(02-25-2023)](https://user-images.githubusercontent.com/72340531/221376204-93d84e07-07d3-489a-b311-a6c382edb9a7.png)

The [Workspace link](https://ci.freerdp.com/job/freerdp-nightly-windows/ws/) just has a download to the source code.

What am I missing?  Do I need an account?  I see no way to create one on the [login page](https://ci.freerdp.com/login?from=%2Fjob%2Ffreerdp-nightly-windows%2F).

**Comment by akallabeth** [comment]
you need to select the current build (left lower panel)?

**Comment by uploadersoasis** [comment]
Look, I didn't just fall off of a turnip truck.  I tried that before I ever made my initial post.  There is no download link even if following any of the links in my original screenshot.

Here is a screenshot I see from the [first build link](https://ci.freerdp.com/job/freerdp-nightly-windows/1250/).  There is no artifact download link on that page.
![screenshot](https://user-images.githubusercontent.com/72340531/221445058-fbe37a4c-00a5-4423-8353-03f8ecee479c.png)

So, where are the links to download the compiled builds?
