### ISSUE TITLE
Mac Homebrew "failed to open display"

### ISSUE THREAD

**Issue by temocj** [FreeRDP/FreeRDP#8764]
**Describe the bug**
After installing FreeRDP with Homebrew and running `xfreerdp` I get this error:

```
[08:39:04:254] [72854:e36ffa80] [ERROR][com.freerdp.client.x11] - failed to open display:
[08:39:04:254] [72854:e36ffa80] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.
```

**To Reproduce**
1. `brew update`
2. `brew install freerdp`
3. `xfreerdp`

**Expected behavior**
Not sure.

**Screenshots**
![brew-install-freerdp](https://user-images.githubusercontent.com/68073709/223675366-e02f6338-225e-411e-a6b1-563d927e6b77.gif)

**Application details**
* FreeRDP version: 2.10.0
* Command line used: `xfreerdp`
* Output of `xfreerdp /buildconfig`: N/A (same error)
* OS version connecting to (server side): Ubuntu Desktop 22.10
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`: N/A (same error)
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help: N/A (built by Homebrew)

**Environment (please complete the following information):**
 - OS: MacOS
 - Version/Distribution: 13.1 (Ventura)
 - Architecture: [amd64, arm]: arm / Apple Silicon

**Additional context**
I checked that the $DISPLAY environment variable is properly set, and it was NOT set.

_Thank you for reporting a bug!_
Ma pleasure!

**Comment by akallabeth** [comment]
`xfreerdp` is an `X11` application, so you need to have an `XServer` running.
