### ISSUE TITLE
Fails to return back to fullscreen with keyboard shortcut after first exiting it (XFCE)

### ISSUE THREAD

**Issue by mlt** [FreeRDP/FreeRDP#877]
If I start xfreerdp in fullscreen (`/f`), I can leave it with `CTRL+ALT+ENTER` however I cannot return back to it with same keyboard shortcut. Nothing happens visually only as if xfreerdp window disappears. Though it feels like there is an invisible window or something as I can't do anything with what I see though input is redirected to remote machine. The only way to get back is to call context menu on windo title and choose _fullscreen_.

I'm running recent git version on Ubuntu 12.04  with XFCE 4.10.

**Comment by pupertest** [comment]
This issue still exists in Xubuntu 16.04 (xfreerdp 1.1.0-beta1 (git n/a)). I've seen this on several different computers. Exactly as described by mlt. Pressing Ctrl-Alt-Enter again returns to windowed, but switching to fullscreen might trigger the bug. It's not always happening, but about 10 tries is usually enough for it to happen. These computers have only 1 monitor. Btw, keyboard input still works in the session in this bugged state, so be careful.

**Comment by akallabeth** [comment]
Is this still the case with current nightlies? Could not reproduce.

**Comment by urusha** [comment]
Just tested - could not reproduce anymore.
