### ISSUE TITLE
inconsistency in the server

### ISSUE THREAD

**Issue by pushpa1226** [FreeRDP/FreeRDP#8804]
Hello,

In Android client we getting this issue, for the first time it will connect to the server later after disconnecting and again connect it is disconnecting and control is going to OnConnectionFailure  in LibFreeRDPBroadcastReceiver it should go to OnDisconnected but sometimes it will go to OnConnectionFailure after that we are trying to connect control will go to direct OnConnectionFailure.

Error Logs:-
E/com.freerdp.core.transport: [pid=4060:tid=9aaedcb0] - BIO_read returned a system error 104: Connection reset by peer
E/com.freerdp.core: [pid=4060:tid=9aaedcb0] - transport_read_layer:freerdp_set_last_error_ex ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
E/com.freerdp.core: [pid=4060:tid=9aaedcb0] - freerdp_post_connect failed

**Comment by akallabeth** [comment]
1. please read the issue template and provide some useful information to help you.
1. if you have trouble with using the library/application join our matrix chat (check https://freerdp.com for details)
