### ISSUE TITLE
Android can not connect to vm.

### ISSUE THREAD

**Issue by imms20** [FreeRDP/FreeRDP#8818]
Hi,

I have compiled master branch using mac Ventura using the android script with release config without providing the ndk path for the openh264(as the ndk r15c i can not install from android studio) using the link. 

https://github.com/FreeRDP/FreeRDP/wiki/Compilation

i can run the app on my android 11. i can add my pc using the ip address as a hostname, and then the username and password. 

the problem comes when i try to connect. it always throw me an error saying that could not connect to null target. it is comming from rdp connect call.

**Comment by akallabeth** [comment]
@imms20 I´ve removed the line from the wiki as we already fixed the issue with `OpenH264` some time ago (just forgot to update the wiki),  so now you can compile with the most recent version as well.
As for your issue, check `logcat`, we write useful debug information there, it might give you a hint why that happens, hard to tell just from the result.

**Comment by imms20** [comment]
[log.txt](https://github.com/FreeRDP/FreeRDP/files/11040462/log.txt)

well i am not sure where to look. but this is the logs i am getting when i try to connect. 

this is the actual command which i have used on master branch. 

./scripts/android-build-freerdp.sh --ndk /home/shah/Android/Sdk/ndk/25.2.9519653/ --sdk /home/shah/Android/Sdk/ --openh264-ndk /home/shah/Android/Sdk/ndk/18.1.5063045/ --conf scripts/android-build-release.conf

even if i remove the h264 thingy, i get the same logs. this time i have compiled the code in a linux vm as well
