### ISSUE TITLE
client_cliprdr_file handling for remote files violates [MS-RDPECLIP] specification

### ISSUE THREAD

**Issue by pnowack** [FreeRDP/FreeRDP#8846]
Affected version: xfreerdp3/master

Reproduction steps:
1. Connect with xfreerdp3 to g-r-d
2. Copy some large folder with lots of files (e.g. some git repo) on the server side
3. Paste them on the client side (e.g. in nautilus)

Observation:
Only a few files inside the remote folder are copied, then the copy operation aborts due to an IO error.

When watching the log of g-r-d, it is noticeable, that xfreerdp3 tries to lock the file list with an id, which it already used before to lock a file list, but did not unlock, or xfreerdp3 tries to lock the same file list multiple times at the same time.

This violates `3.1.5.3.1 Sending a Lock Clipboard Data PDU`:

```
The clipDataId field MUST contain an unsigned integer value that will serve as an identifier to
uniquely tag any File Stream data (section 1.3.1.1.5) on the clipboard of the Shared Clipboard Owner
(section 1.3.2.1).
```

The "uniquely tag" is crucial here.

A weird part is also, that despite having a lock PDU sent, the `clipDataId` is not used in the subsequent file content requests.

The observation about those IO errors can also be observed, when disabling the locking behaviour (by adding a `&& FALSE` to the `cliprdr_file_context_remote_get_flags(stream->context) & CB_CAN_LOCK_CLIPDATA`).

These IO errors don't happen on lone files, but on larger folders (folder with 100+ files might already be enough).

**Comment by akallabeth** [comment]
@pnowack ok, found an issue. there was a lock missing on the hash table when discarding streams.
can you check if that fixes your duplicate locking/unlocking issues?

**Comment by pnowack** [comment]
@akallabeth I may have an idea, why the IO errors happen (not the protocol violations though, since I didn't dig that much into `client_cliprdr_file`):
Close to the end of the log, where the protocol violation happens, the `FileGroupDescriptorW` data is fetched again.
xfreerdp3 caches the data of the last request. While apparently there is no fetch for a different format of the format list, that mechanism still exposes a problem:
A refetch of `FileGroupDescriptorW` might mean, that the file list becomes invalid. And xfreerdp3 might try to replace the contents of the file list, which changes the contents of the FUSE filesystem, leading to those IO errors.

The fix might be simple, and that is by using a hash table for the cached data: Each entry in the hash table would be `formatId` -> data for the `formatId`.

---

In any case, the lock PDUs should always be used before the data of the `FileGroupDescriptorW` is fetched. The unlock will then happen at the earliest, when a new FormatList is received or sent.

In the case of g-r-d, g-r-d puts the lock (when the client supports locking) before the `FileGroupDescriptorW` data request (and caches it).
mstsc does almost the same, except, when the server supports locking, it will lock the list before even sending the `FormatListResponse` (and even regardless of whether the `FormatList` contains a `FileGroupDescriptorW` or not).
A bit overkill of mstsc, but not an error.
