### ISSUE TITLE
Failed to connect by *.rdp files

### ISSUE THREAD

**Issue by CleMooling** [FreeRDP/FreeRDP#8859]
Open rdp files by command such as "xfreerdp *.rdp -u username -p password", and similar errors occurred.
Files are created by RemoteApp Tool.
[23:17:35:104] [53417:53418] [ERROR][com.freerdp.core] - freerdp_tcp_is_hostname_resolvable:freerdp_set_last_error_ex ERRCONNECT_DNS_NAME_NOT_FOUND [0x00020005]

**Comment by akallabeth** [comment]
@CleMooling well, the description is a bit short.
(this can be a non fatal issue if there is another resource, e.g. IP address or similar supplied as well and just the DNS name does not exist)

other than that the error is quite clear, the destination DNS name does not exist. (maybe some private resource that requires a specific DNS server?)

nothing we can change regarding that ;)
