### ISSUE TITLE
Some remote applications have a 90%+ probability of not being able to display the screen

### ISSUE THREAD

**Issue by Victor2kyang** [FreeRDP/FreeRDP#8875]
NOTE: Not all apps will do this!
Can someone find something from the log?

From the windows7 process, you can see that the application has been opened, but the client has no screen, and the connection has not been disconnected.

run：
/usr/local/bin/xfreerdp  /u:xxxx /p:xxxx /v:192.168.41.24 /app:"\"C:\Program Files (x86)\ukey\UKeyKp.exe\""    /cert-ignore

server info：
os: windows7
client info：
os: UOS or ubuntu20.04
```bash
ABC@ABC-PC:~$ xfreerdp /buildconfig
This is FreeRDP version 2.10.0 (2.10.0)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_BACKTRACE=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 HAVE_EXECINFO_H=ON HAVE_EXECINFO_HEADER=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=ON WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=ON WITH_FAAD2=ON WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_ICU=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Debug
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 8.3.0
Target architecture: x64
```
[freerdp.log](https://github.com/FreeRDP/FreeRDP/files/11206793/freerdp.log)

**Comment by akallabeth** [comment]
It would help if you could tell:
1. Are you connecting to a new session or resume a running one?
2. Is the program a tray icon or does it have normal windows
3. Does this also occur with our nightly builds? (master has some improvements regarding `RAILS` that will most likely not be backported to stable-2.0 due to API breakage)

**Comment by Victor2kyang** [comment]
> It would help if you could tell:
> 
> 1. Are you connecting to a new session or resume a running one?
> 2. Is the program a tray icon or does it have normal windows
> 3. Does this also occur with our nightly builds? (master has some improvements regarding `RAILS` that will most likely not be backported to stable-2.0 due to API breakage)

1. Both
2. have normal windows. This program uses xfreerdp to run normally on UOS with only a small probability, while on Ubuntu with a high probability.
3. Where can I get nightly builds? I only found these and I don't know how to use them：
https://ci.freerdp.com/job/freerdp2-binaries/architecture=amd64,distribution=buster,label=pkg-deb/

**Comment by Victor2kyang** [comment]
> It would help if you could tell:
> 
> 1. Are you connecting to a new session or resume a running one?
> 2. Is the program a tray icon or does it have normal windows
> 3. Does this also occur with our nightly builds? (master has some improvements regarding `RAILS` that will most likely not be backported to stable-2.0 due to API breakage)

2. Replenish  other program is normal on UOS.for example ： ie , notepad++ , wspaint , Chrome.

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/Prebuilds

**Comment by Victor2kyang** [comment]
> https://github.com/FreeRDP/FreeRDP/wiki/Prebuilds

I know this page, but I don't know which file.  

[freerdp-nightly-dbg_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly-dbg_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb)	11.42 MB	 [view](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly-dbg_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb/*view*/)
[freerdp-nightly-dev_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly-dev_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb)	246.71 KB	 [view](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly-dev_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb/*view*/)
[freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d.dsc](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d.dsc)	1.54 KB	 [view](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d.dsc/*view*/)
[freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d.tar.xz](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d.tar.xz)	4.84 MB	 [view](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d.tar.xz/*view*/)
[freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.buildinfo](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.buildinfo)	15.58 KB	 [view](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.buildinfo/*view*/)
[freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.changes](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.changes)	5.16 KB	 [view](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.changes/*view*/)
[freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb)	3.04 MB	 [view](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_amd64.deb/*view*/)
[freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_source.changes](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_source.changes)	3.71 KB	 [view](https://ci.freerdp.com/job/freerdp-nightly-binaries/architecture=amd64,distribution=buster,label=pkg-deb/lastSuccessfulBuild/artifact/freerdp-nightly_3.0.0+0~20230414014819.1309~1.gbpabe49d_source.changes/*view*/)

**Comment by akallabeth** [comment]
copied from the ubuntu nightlies:
```
Project freerdp-nightly-binaries
Nightly FreeRDP master builds

Add the following entry to a sources list:

deb http://pub.freerdp.com/repositories/deb/DIST/ freerdp-nightly main

Where DIST needs to be replaced with one of the supported distributions from below.
The package is called freerdp-nightly and binaries and libraries are installed to /opt/freerdp-nightly/

To get they apt key:
wget -O - http://pub.freerdp.com/repositories/ADD6BF6D97CE5D8D.asc | sudo apt-key add - 
```

**Comment by Victor2kyang** [comment]
> It would help if you could tell:
> 
> 1. Are you connecting to a new session or resume a running one?
> 2. Is the program a tray icon or does it have normal windows
> 3. Does this also occur with our nightly builds? (master has some improvements regarding `RAILS` that will most likely not be backported to stable-2.0 due to API breakage)

3.  3.0 Nightly builds have same situation.

**Comment by Victor2kyang** [comment]
If my situation improves with Win10, but there is a half chance that I will experience incorrect window recognition. I think the same situation applies to Win7, where the window is mistakenly recognized as a very small piece.
![xfreerdp错误图](https://user-images.githubusercontent.com/42526605/233331783-c14dec7f-0b48-4666-a24b-24af2f43d38d.jpg)
