### ISSUE TITLE
x64 Bits Platform Build on Windows Visual Studio Does not detect include files

### ISSUE THREAD

**Issue by zw83133883** [FreeRDP/FreeRDP#8884]
Related to Win64 Build Platform:
I have compiled x64 FreeRDP that I am trying to write my own JNI for my java application, however, the include files from the master branch can be detected using x32 build instead of x64. When I switch it to x64 build Visual Studio cannot find the include files. This makes me think if the include files are only meant for x32 build. This does not make sense to me because the include files should be compatible with any platform.

**Comment by akallabeth** [comment]
looks like you have configured the wrong include paths?
`FreeRDP` properly installs `cmake` configuration files you can use to detect the library.
(basic rule to build is `cmake <yourargs> -B <builddir> -S <sourcedir> -DCMAKE_INSTALL_PREFIX=<install path>` followed by a `cmake --build <builddir> --target install`)
how you use that from any IDE is up to you.
