### ISSUE TITLE
Request: add communication regarding the XServer requirement for macOS 

### ISSUE THREAD

**Issue by systemresearch** [FreeRDP/FreeRDP#8885]
**Is your feature request related to a problem? Please describe.**

Please add communication regarding the XServer requirement for macOS

**Describe the solution you'd like**

On the [wiki/Compilation](https://github.com/FreeRDP/FreeRDP/wiki/Compilation) page something like the following could be added in the `macOS Specifics` section:

> `xfreerdp` is an `X11` application that requires an `XServer` be installed and running. Lack of a running `XServer` will cause a "$DISPLAY" error.
> 
> `XQuartz` provides an `XServer` for macOS. The `XQuartz` can be installed as a package from [www.xquartz.org](https://www.xquartz.org) or as a Homebrew cask:
> 
> ``` lang-sh
> brew install --cask xquartz
> ```

And the [wiki/PreBuilds](https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds) page could have something like:

> [Homebrew](http://brew.sh/) has a formula for FreeRDP. Just `brew install freerdp`. If you want to build the latest FreeRDP master use the --HEAD option. Be sure to also have an `XServer` ([XQuartz](https://www.xquartz.org/)) installed. Run like `xfreerdp ...`

**Describe alternatives you've considered**

I also created an issue/request for an _external requirement caveat_ to be added to the Homebrew `freerdp` formula:

*  ["freerdp install fails to communicate an external prerequisite (xserver) #128321 "](https://github.com/Homebrew/homebrew-core/issues/128321)

**Additional context**

I am not alone. Several others have had this same _"What am I missing??"_ experience due to lack of communication of external prequisites.

* <https://github.com/FreeRDP/FreeRDP/issues/8764>
* <https://github.com/FreeRDP/FreeRDP/issues/7420>
* <https://github.com/FreeRDP/FreeRDP/issues/7354>
* <https://github.com/FreeRDP/FreeRDP/issues/7129>

**Comment by akallabeth** [comment]
I´ve updated our build instructions.
As for the `XQuartz` thing, that is only required if you use our linux client (`xfreerdp`) on mac.
I´d switch to:
1. the native `MacFreeRDP` client that can be build
2. the SDL client (currently only available on `master`)

the latter is scheduled to replace the older platform clients and will be the one getting newer features.

**Comment by systemresearch** [comment]
I'm using `xfreerdp` with `xquartz` only because I have not yet found a path to a working alternative. [FreeRDP/wiki/Compilation](https://github.com/FreeRDP/FreeRDP/wiki/Compilation) does discuss building either `MacFreeRDP` or `SDL client` … 

> I´ve updated our build instructions.

Link? 

Thanks.
