### ISSUE TITLE
freerdp_context_new(instance)  new failed when run in systemd

### ISSUE THREAD

**Issue by kxjhcs** [FreeRDP/FreeRDP#8891]
mycode:
freerdp *instance = freerdp_new();
    if (instance == NULL)
    {
        printf("[ERROR] freerdp init failed1,errno=%d\n",errno);
        return 0;
    }
    if (freerdp_context_new(instance) == FALSE)
    {
        printf("[ERROR] freerdp init failed2,errno=%d\n",errno);
        return 0;
    }

when i run my process on linux shell,it is run ok;
when i start my process by systemd(systemctl start xxx.service), freerdp_context_new(instance) is return false,errno=2
Do I need to make any other configurations

**Comment by akallabeth** [comment]
ok, got a question first: What are you trying to do? (client? server?)
best guess your systemd environment has an empty `environment` and the `XDG` or fallback paths are not available?

**Comment by hardening** [comment]
hostname missing is also a good candidate

**Comment by akallabeth** [comment]
anyway, not really an issue but more a support question.
