### ISSUE TITLE
libfreerdp/core/nla.c Debug code isn't unicode aware

### ISSUE THREAD

**Issue by zeha** [FreeRDP/FreeRDP#891]
Debug output in libfreerdp/core/nla.c, around line 133:

    _tprintf(_T("User: %s Domain: %s Password: %s\n"),
        (char*) credssp->identity.User, (char*) credssp->identity.Domain, (char*) credssp->identity.Password);

This isn't unicode aware and only the first character of User and Password is shown instead.
(Leading me down the wrong path.)

**Comment by akallabeth** [comment]
printf has been replaced by wlog.
