### ISSUE TITLE
Excel (Office 2021 Pro Plus) on Windows 10 - Cannot resize columns or rows with mouse in app mode

### ISSUE THREAD

**Issue by ademlabs** [FreeRDP/FreeRDP#8910]
**Describe the bug**
Using Windows 10 Pro and a registered copy of Office 2021 Pro Plus, I am unable to resize columns or rows.
Hovering over the column or row edges shows the resize icon but holding and dragging doesn't do anything.
Resizing works fine when opening a full RDP session though.
In app mode, I can resize margins in Word.

**Expected behavior**
I expect to be able to resize the columns or rows in app mode similar to full desktop mode.

**Application details**
Using FreeRDP compiled from Git: `3.0.0-dev (f66110c61)` and created a flatpak package.
Tested using FreeRDP 2.10 and issue exists there as well.

**Command line used**
```
flatpak run --command=xfreerdp com.freerdp.FreeRDP /u:"MY_USER" /p:"MY_PASS" /v:MY_IP +home-drive /gfx:rfx /size:2048x1546 /scale:140 +aero +async-channels /network:lan -encryption /app:program:"C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE"
```

**Output of `xfreerdp /buildconfig`**
```
This is FreeRDP version 3.0.0-dev (f66110c61)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_JOURNALD_H=TRUE WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CJSON=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=ON WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=OFF WITH_PAM=OFF WITH_PCSC=ON WITH_PKCS11=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer  -O3 -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer
Compiler:            GNU, 12.2.0
Target architecture: x64
```

**OS version connecting to (server side)**
Edition: Windows 10 Pro
Version: 22H2
OS Build: 19045.2787
Experience: Windows Feature Experience Pack 120.2212.4190.0
Running inside a VM via QEMU/KVM

**Log output from a run with `/log-level:trace 2>&1 | tee log.txt`**
[log.txt](https://github.com/FreeRDP/FreeRDP/files/11290213/log.txt)

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: EndeavourOS/Arch
 - Architecture: amd64

**Comment by amazingfate** [comment]
That's because when clicking on resize icon of a column, there will be a new small window displaying size of this column, which causing Xorg `FocusIn/FocusOut` events of this new window and the original main window.
RDP client should avoid `FocusOut` of the original main window and `FocusIn` of the new small window.

**Comment by ademlabs** [comment]
@amazingfate Is this only a problem on Xorg? Will using the SDL client on Wayland solve it?

**Comment by victorarocha** [comment]
> @amazingfate Is this only a problem on Xorg? Will using the SDL client on Wayland solve it?

Did you found a solution for this?

**Comment by amazingfate** [comment]
> > @amazingfate Is this only a problem on Xorg? Will using the SDL client on Wayland solve it?
> 
> Did you found a solution for this?

You can try to disable `xf_keyboard_release_all_keypress` in `xf_event_FocusOut` when it is remote app session.
https://github.com/FreeRDP/FreeRDP/blob/3.6.3/client/X11/xf_event.c#L683

**Comment by ademlabs** [comment]
> > > @amazingfate Is this only a problem on Xorg? Will using the SDL client on Wayland solve it?
> > 
> > 
> > Did you found a solution for this?
> 
> You can try to disable `xf_keyboard_release_all_keypress` in `xf_event_FocusOut` when it is remote app session. https://github.com/FreeRDP/FreeRDP/blob/3.6.3/client/X11/xf_event.c#L683

Haven't tried this yet, will do and report back.

**Comment by victorarocha** [comment]
Just to ley you all know that upgrading xfreerdp to 3.6.3 fixed the problem.

**Comment by ademlabs** [comment]
I can confirm that this works correctly now, I'm able to use xfreerdp to launch Excel and resize columns in app mode.
Closing.
