### ISSUE TITLE
deprecation warnings using openssl3

### ISSUE THREAD

**Issue by hendwolt** [FreeRDP/FreeRDP#8913]
When I build the current master for openSUSE Tumbleweed, which ships already openssl3, I get a number of deprecation warnings. Are there plans, to do something about this?

`[   54s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/crypto/hash.c:193:9: warning: 'HMAC_CTX_new' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   54s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/crypto/hash.c:238:9: warning: 'HMAC_Init_ex' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   54s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/crypto/hash.c:288:9: warning: 'HMAC_Update' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   54s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/crypto/hash.c:327:9: warning: 'HMAC_Final' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   54s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/crypto/hash.c:356:17: warning: 'HMAC_CTX_free' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   58s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/libwinpr/sspi/Schannel/schannel_openssl.c:241:9: warning: 'SSL_CTX_use_RSAPrivateKey_file' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   69s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/tools/makecert/makecert.c:914:17: warning: 'RSA_new' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   69s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/tools/makecert/makecert.c:923:17: warning: 'RSA_generate_key_ex' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   69s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/winpr/tools/makecert/makecert.c:931:9: warning: 'EVP_PKEY_assign' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/cert_common.c:184:9: warning: 'PEM_write_bio_RSA_PUBKEY' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/privatekey.c:102:9: warning: 'PEM_read_bio_RSAPrivateKey' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/privatekey.c:149:9: warning: 'RSA_check_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/privatekey.c:168:9: warning: 'RSA_get0_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/privatekey.c:183:9: warning: 'RSA_free' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/certificate.c:479:9: warning: 'RSA_new' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/certificate.c:489:9: warning: 'RSA_set0_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/certificate.c:501:17: warning: 'RSA_free' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/certificate.c:1106:9: warning: 'EVP_PKEY_get1_RSA' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/certificate.c:1118:9: warning: 'RSA_get0_key' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/certificate.c:1125:9: warning: 'RSA_free' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
[   74s] /home/abuild/rpmbuild/BUILD/FreeRDP-master/libfreerdp/crypto/certificate.c:1491:9: warning: 'EVP_PKEY_get1_RSA' is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
`

**Comment by akallabeth** [comment]
some of these we can currently not  get rid of (`RSA_*` ) as `RDP security`, `licensing` are tightly coupled to `RSA` and require access to the internals which `OpenSSL 3` tries to abstract
the others we´ll have a look at sooner or later.
