### ISSUE TITLE
Ubuntu 23.04 (lunar) support

### ISSUE THREAD

**Issue by jgilbert2017** [FreeRDP/FreeRDP#8926]
please publish (and test) a nightly build for ubuntu 23.04 (lunar lobster) which is now officially released.

i installed the daily nightly kinetic build from 20230424 under lunar and it seems to have a issues related to full screen mode (half the time the window seems offset by the ubuntu taskbar height).

**Comment by akallabeth** [comment]
done, binaries are now build.
