### ISSUE TITLE
`size_t` underflow in `rts_read_auth_verifier_with_stub` causes "allocation-size-too-big"

### ISSUE THREAD

**Issue by thenextman** [FreeRDP/FreeRDP#8932]
**Describe the bug**
Connecting to a Win2k19 terminal server via RD Gateway using the rpc transport with an existing license is returning `ERROR_BAD_FORMAT`. `rts_read_pdu_fault` is called and may cause an allocation error. 

**To Reproduce**
1. Connect to a Windows 2k19 terminal server configured for per device CALs
2. Ensure connection via RD Gateway using the rpc transport
3. Client obtains a license from the sever, it is serialized and written to disk
4. Disconnect and connect a second time
5. Client sends existing license to server, server responds with ERROR_BAD_FORMAT
6. Crash while reading response

**Expected behavior**
If the existing license is not accepted, an appropriate error should be returned.

**Application details**
* FreeRDP version: master
* OS version connecting to (server side): Windows Server 2k19

**Environment (please complete the following information):**
 - OS: macOS
 - Version/Distribution: 13 (Ventura)
 - Architecture: arm64

**Additional context**
```
[10:59:24:427] [27831:6d4d7000] [DEBUG][com.freerdp.core.gateway.rts] - [rts_read_pdu_header]: Reading PDU type PTYPE_FAULT
[10:59:24:427] [27831:6d4d7000] [WARN][com.freerdp.core.gateway.rts] - [rts_read_pdu_fault]: status=ERROR_BAD_FORMAT
=================================================================
==27831==ERROR: AddressSanitizer: requested allocation size 0xfffffffffffffffc (0x800 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T5)
    #0 0x10307d600 in wrap_calloc+0x90 (libclang_rt.asan_osx_dynamic.dylib:arm64+0x3d600)
    #1 0x1055c66a8 in sdup rts.c:155
    #2 0x1055ca288 in rts_read_auth_verifier_with_stub rts.c:331
    #3 0x1055b04a8 in rts_read_pdu_fault rts.c:932
    #4 0x1055aa3a8 in rts_read_pdu_header rts.c:1147
    #5 0x1055a108c in rpc_client_recv_fragment rpc_client.c:337
    #6 0x10559c0d0 in rpc_client_default_out_channel_recv rpc_client.c:681
    #7 0x10559ad78 in rpc_client_out_channel_recv rpc_client.c:786
    #8 0x105600458 in tsg_check_event_handles tsg.c:2261
    #9 0x10571aac0 in rdp_check_fds rdp.c:2058
    #10 0x105535430 in rdp_client_wait_for_activation connection.c:271
    #11 0x1055343c0 in rdp_client_connect connection.c:456
    #12 0x105564110 in freerdp_connect_begin freerdp.c:159
    #13 0x105561f9c in freerdp_connect freerdp.c:177
    #14 0x1050e6d4c in mac_client_thread MRDPView.m:135
    #15 0x1052ffb2c in thread_launcher thread.c:520
    #16 0x102d115d0 in _pthread_start+0x90 (libsystem_pthread.dylib:arm64e+0x15d0)
    #17 0xb25e000102d1ba84  (<unknown module>)
```

![Screenshot 2023-04-27 at 11 12 01](https://user-images.githubusercontent.com/2573400/234906874-9d9def36-e834-4eea-92c3-e1f76ba2a015.png)

**Comment by akallabeth** [comment]
should now be ignored/discarded.
