### ISSUE TITLE
Possible memory corruption in `nla_server_init` (double free or corruption (!prev))

### ISSUE THREAD

**Issue by pnowack** [FreeRDP/FreeRDP#8943]
This is a stacktrace, that I did not experience myself, but I found this in Ubuntu errors. The error was reproduced with g-r-d-44.x (which depends on FreeRDP 2.10.0), but according to Ubuntu errors, somebody also reproduced it in g-r-d-42.x (that Ubuntu version there uses FreeRDP 2.6.1).

Stacktrace: 
[stacktrace.txt](https://github.com/FreeRDP/FreeRDP/files/11411417/stacktrace.txt)

Ubuntu errors link: https://errors.ubuntu.com/problem/284689e3b0d7e85f49c926bc6a67af770f73329a

Note: I personally did not ever reproduce that issue, so I unfortunately cannot test where the issue is. The total crash hit count is according to Ubuntu errors 6 times, so very low, considering it is reproducible since at least 2.6.1 (up to at least 2.10.0).

**Comment by akallabeth** [comment]
can only be a corruption, the buffer is a global one and only freed up on program termination.

**Comment by pnowack** [comment]
> the buffer is a global one

Oh. Can it be simultaneously used? I.e. having two clients connecting at the same time and authenticating at the same time.

**Comment by akallabeth** [comment]
from the trace it should always be used from the same thread (e.g. `freerdp_peer_check_fds/CheckFileDescriptor` and only later on the client uses its own thread

**Comment by pnowack** [comment]
hmm... I guess this means, that there is nothing we can do here, unless we find a way ourselves to reproduce the issue and run the server here with address sanitizer?

**Comment by akallabeth** [comment]
guess so.

**Comment by pnowack** [comment]
Ok, then I'll close this issue, so we don't have a non-actionable issue lying around open. We can still reopen the issue again, if we find a way to reproduce it.
