### ISSUE TITLE
Font subpixel hinting options

### ISSUE THREAD

**Issue by newgear0727** [FreeRDP/FreeRDP#8956]
**Is your feature request related to a problem? Please describe.**
I have a RGBW OLED screen for which the best option is to use grayscale subpixel rendering instead of rgb/bgr, etc.. Everything in sway/wayland and Xorg looks fine without color fringing but my Windows 10 connect suffers from fringing. I tried disabling and modifying ClearType options but no to avail. Is there anything supported in freerdp to help with this?

**Describe the solution you'd like**
Any options available to help enforce grayscale subpixel rendering or ideas to help improve the situation outside of freerdp even?

**Describe alternatives you've considered**
None

**Additional context**
Archlinux, swaywm, LG C2 OLED screen with RGBW subpixel layout.

**Comment by akallabeth** [comment]
windows RDP servers do change the visual representation of the session depending on connection options.
which ones do you use?

**Comment by newgear0727** [comment]
I use:
```
xfreerdp \
    /u:xxx \
    /d:xxx \
    /v:xxx \
    /p:xxx \
    /g:xxx \
    /gu:xxx \
    /gd:xxx \
    /gp:xxx \
    /gt:auto,no-websockets \
    /auto-reconnect \
    /cert:ignore \
    /f \
    /bpp:32 \
    /gfx-h264:avc444 \
    /network:auto \
    -toggle-fullscreen \
    -decorations \
    -grab-keyboard \
    -themes \
    -wallpaper \
    -window-drag \
    +gfx-progressive
```

**Comment by akallabeth** [comment]
@newgear0727 ok, drop everything starting with `/bpp:32` (except `-grab-keyboard`), then you should get the best stuff the server supports. (what that is is up to the server administrator or microsoft defaults)
other than that we can´t do anything client side as the server encodes the session data (as `video` in modern `RDP`)

only option you might want to try is `+fonts` to give the server a hint (test with and without that flag, server might also just ignore it)

**Comment by newgear0727** [comment]
I tried your suggestion and fonts in general look horrible. I think it's /gfx-h264:avc444 that is needed to really ensure fonts like bold red on black render correctly.

**Comment by akallabeth** [comment]
@newgear0727 no. that is enabled by default and does change nothing.
