### ISSUE TITLE
Can't get the remote desktop resolution via FreeRDP lib API

### ISSUE THREAD

**Issue by ivanshchitov** [FreeRDP/FreeRDP#8988]
Hello!

I use the FreeRDP lib API and try to set the my RDP-client screen size in depend on the remote desktop resolution.
I try to retrieve the desktop size when connection is successfully established. I use following ways:

```cpp
uint width = freeRdpInstance->settings->DesktopWidth;
uint height = freeRdpInstance->settings->DesktopHeight;
```

Here `DesktopWidth` and `DesktopHeight` contain values but they are incorrect. Always 1024x768, but I set different resolutions before running the code.

```cpp
uint physWidth = freeRdpInstance->settings->DesktopPhysicalWidth;
uint physHeight = freeRdpInstance->settings->DesktopPhysicalHeight;
```

Here `DesktopPhysicalWidth` and `DesktopPhysicalHeight` return 0 always.

Can you please, explain how I can retrieve the remote desktop resolution?

Remote Desktop OS is Windows 10 Pro.
Client OS is mobile Sailfish OS.

**Comment by akallabeth** [comment]
well, that is quite something you try there.

1. you need to wait for the connection to be established to know the resolution.
2. `DesktopWidth` and `DesktopHeight` are then populated with the resolution (check the `DesktopResize` callback
4. `gdi->width` and `gdi->height` might also be used (that is the framebuffer size used as decoder buffer)
5. be sure that you do not use a multimonitor layout, otherwise this will not work
6. you seem to be doing something wrong if the resolution is always `1024x768` as that is just the default value we use. (when do you set it?)

**Comment by ivanshchitov** [comment]
Thank's for answers.

1. I wait the connection and try to get remote desktop size only when it is established.

2. The `DesktopResize` callback is not called in my case. Don't understand why.. Code:

```cpp
BOOL DesktopResize(rdpContext *context)
{
    println("DesktopResize")
    uint width = freeRdpInstance->settings->DesktopWidth;
    uint height = freeRdpInstance->settings->DesktopHeight;
    return TRUE;
}
...
freeRdpInstance->context->settings->DesktopResize = TRUE;
freeRdpInstance->update->DesktopResize = DesktopResize;
```

3. `gdi->width` and `gdi->height` always return default `1024x768`. Code:

```cpp

BOOL PostConnectCallback(freerdp *instance)
{
    gdi_init(instance, PIXEL_FORMAT_XRGB32);
    
    uint width = instance->context->gdi->width;
    uint height = instance->context->gdi->height;
    return TRUE;
}
...
freeRdpInstance->PostConnect = PostConnectCallback;
```

4. I use only one monitor with the remote desktop. Or do you mean some freerdp setting?

5. I set different remote desktop resolutions via Windows settings before running my RDP-client.

**Comment by akallabeth** [comment]
what do you mean with `I set different remote desktop resolutions via Windows settings before running my RDP-client.`?
you set the resolution when you connect in `FreeRDP`

**Comment by ivanshchitov** [comment]
No, I mean I go to the Windows settings (Start -> Settings -> System -> Display -> Display resolution), change the resolution, and only after that run RDP-client and establish the connection.

**Comment by akallabeth** [comment]
:rofl: sorry, there seems to be a misconception.

your resolution when woking locally to on your machine does not have anything to do with the resolution used in a RDP session.
you set a resolution request at the beginning of the RDP session and the server might accept it (or use something else)
there is also the possibility that you change resolutions during a RDP session, which still does not influence what you will have if you log in locally...

**Comment by ivanshchitov** [comment]
Actually, I do not have problems with setting remote desktop resolution via FreeRDP lib API. I have problem with getting the remote desktop resolution via the API.

Can I get the actual remote desktop resolution via FreeRDP lib API? Or, not? as I understand your previous message.

**Comment by akallabeth** [comment]
@ivanshchitov check my first response again.
if `DesktopWidth` and `DesktopHeight` are not what you expect then you did something wrong before that.
and, as mentioned, `gdi->width` and `gdi->height` are the same variables that represent the dimension of the local framebuffer that contains the RDP session image.

just add some print statements in existing clients and check that, then you might find the difference to your implementation (I assume you have your own clients as your code snippets do not look like `FreeRDP` coding style)
