### ISSUE TITLE
fatal error: 'freerdp/config.h' file not found

### ISSUE THREAD

**Issue by thechau** [FreeRDP/FreeRDP#8999]
Hi

When i tried to install via terminal, after flowing steps from guideline, i'm sucking in this line

         ^~~~~~~~~~~~~~~~~~
     
         /FreeRDP/client/common/client.c:20:10: fatal error: 'freerdp/config.h' file not found
#include <freerdp/config.h>

**Comment by thechau** [comment]
are there any support. please help me

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/Compilation

**Comment by khanhthaiquang** [comment]
@akallabeth Is it working on MacOS? It's using chip M1. I'm Facing this problem.

**Comment by khanhthaiquang** [comment]
![image](https://github.com/FreeRDP/FreeRDP/assets/34378391/ba2886a7-fca6-4841-93c0-c93901515d97)
