### ISSUE TITLE
 "Attempting reconnect" until the end of attempts.

### ISSUE THREAD

**Issue by mshakurov** [FreeRDP/FreeRDP#9007]
Freerdp always freezes completely after 5-10 minutes of inactivity, then after some amount time - closes.

_Command line string (used with gate):_

`/usr/bin/xfreerdp /cert:ignore +clipboard /g:gatehostname /gu:gateuser /gd:gatedomain /gp:password /v:workstation /u:user /p:password /f /floatbar +auto-reconnect /auto-reconnect-max-retries:50 /log-level:TRACE >/home/qwerty/rdp.log 2>1
`

_freerdp versions_ : 2.6.1; 2.10.0
_client OS versions_ : Debian like OS; Debian GNU/Linux 11 (bullseye)
_target remote OS versions_ : Windows 10; Windows 7; Windows Server 2012

I have recorded a lot of logs in which I find the string:

2.6.1, 2.10.0:
```
[15:40:21:942] [19046:19047] [DEBUG][com.freerdp.core] - rdp_check_fds() - -1
[15:40:21:942] [19046:19047] [INFO][com.freerdp.client.common] - Network disconnect!
```

Immediately after these lines, the freerdp client freezes (stops transmitting clicks and displaying image changes). Further, in version 2.10.0 in Debian 11, one line appears, and in version 2.6.1 in Debian like OS, a cycle of lines begins until the maximum number of connection attempts is reached:

`[16:13:42:909] [23734:23735] [INFO][com.freerdp.client.common] - Attempting reconnect (1 of 50)`

A large number of identical pairs of lines appear between the specified reconnection lines:

```
[16:13:42:909] [23734:23735] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_process_x_events
[16:13:42:909] [23734:23735] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_process_x_events
```

After the last connection attempt in version 2.6.1 and after one connection attempt in version 2.10.0, several pairs of lines appear, and the freerdp client closes:

```
[16:14:07:223] [23734:23735] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:	[1] from xf_Pointer_Free
[16:14:07:223] [23734:23735] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:	[0] from xf_Pointer_Free
```
-----

Why is it not reconnecting?
If I manually close the client immediately at the moment of freezing, and start it again, then the connection is established.
But the client itself cannot reconnect.

**An important note about RDP connections from my PC to my remote server**: 

Another RDP-compatible client (Remmina) works flawlessly from my PC with my remote server, and tolerates long periods of inactivity without any problems.
Non-rdp clients (Google Remote Desktop, TeamViewer) also never hang with the same remote server.

**Comment by akallabeth** [comment]
@mshakurov best guess a network issue, but without a log hard to tell.

**Comment by akallabeth** [comment]
@mshakurov any details on this? the excerpt of log entries you posted is `something failed, look above` but without the `above`

**Comment by mshakurov** [comment]
I am posting the test run log. after starting free_rdp, I switch to another application and wait for free_rdp to close:

[rdp_server4.zip](https://github.com/FreeRDP/FreeRDP/files/11600647/rdp_server4.zip)

(_this problem occurs only when idle. I can work 10 hours, but if you leave the window inactive for 3-5 minutes, it freezes. this always happens, 100% of the time - it doesn't happen that after 5 minutes I return to the window and it worked. as I understand it, there is no **reconnection**, because, as I wrote earlier, if you close the window and open it again, the connection is quickly established and I continue to work_)

**Comment by mshakurov** [comment]
Ubuntu 22.04 (Virtual Machine)
Reconnection was successful!
The Ubuntu VM is on the same network as the target server, i.e. without gate.
Maybe it's my networking stack and gate - freerdp can't reconnect properly because it doesn't see any possibilities?

**Comment by akallabeth** [comment]
@mshakurov not sure. if possible you could try a build from `master` (we´ve put quite some effort in making each error branch log some useful message, so it might give you a better error description)
this sounds a lot like some missing heartbeat (not the RDP ones, but TLS/TCP/...) and the connection being closed.

**Comment by mshakurov** [comment]
I want to once again focus on the main problem - RECONNECTION. 
It is clear that there may be problems with the network.
But it is not clear why on some platforms freerdp does not reconnect after the full number of attempts, and on some platforms it does not attempt at all.
Maybe it can be seen from the log, but I didn't see it.

**Comment by mshakurov** [comment]
> @mshakurov not sure. if possible you could try a build from `master` - our nightly builds - (we´ve put quite some effort in making each error branch log some useful message, so it might give you a better error description) this sounds a lot like some missing heartbeat (not the RDP ones, but TLS/TCP/...) and the connection being closed.

ok, I will try
