### ISSUE TITLE
Mouse motion lag from 2.7.0 onwards including Debian Bookworm's 2.10.0, no issue in 2.6.1.

### ISSUE THREAD

**Issue by kinnairdclan** [FreeRDP/FreeRDP#9010]
**Describe the bug**
Odd behavior in which upgrading to Debian Bookworm (FreeRDP 2.10.0) from Bullseye (FreeRDP 2.3.0) gave rise to a connection with much more mouse movement lag to a second's delay or worse.

**To Reproduce**
Build and/or install 2.10.0 on Debian Bookworm system.
Connect, noticing mouse delay.
Build and install backwards until arriving at 2.6.1 on Debian Bookworm system.
Noticing far less (near-instaneous feedback) mouse delay similar to Debian Bullseye (2.3.0) behavior.

**Expected behavior**
The quick responsiveness from 2.6.1 and 2.3.0 should be similar in 2.10.0, the default Debian Bookworm package.

**Application details**
* FreeRDP version 2.10.0, 2.6.1
* Command line used:
2.10.0 (bad): `xfreerdp +toggle-fullscreen +clipboard /bpp:16 /multimon /u:xxxx /v:xxxx /g:xxxx /sound /microphone:sys:alsa /log-level:trace 2>&1 | tee log.txt`
2.6.1 (good): `/usr/local/bin/xfreerdp +toggle-fullscreen +clipboard /multimon /u:xxxx /v:xxxx /g:xxxx /sound /microphone:sys:alsa /log-level:trace 2>&1 | tee goodlog.txt`
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
2.10.0 (bad): https://www.dropbox.com/s/rur4x4gugrea1uj/log.txt?dl=0
2.6.1 (good): https://www.dropbox.com/s/65mcu7fsdfmsngj/goodlog.txt?dl=0

* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

2.6.1: `cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_CUPS=ON -DWITH_PULSE=ON  -DWITH_FAAC=ON -DWITH_FAAD2=ON -DWITH_GSM=ON`

Tag 2.6.1, Tag 2.7.0 for 'good' and 'bad' behavior, respectively.

**Environment (please complete the following information):**
Debian 12

**Comment by akallabeth** [comment]
we did not change anything related to that, only thing that could cause this (and which differs in the log) is that the newer versions try websocket transport for the gateway connection. 
We´ve received reports that some server versions (or only configurations?) have suboptimal performance with that, so you might try adding `/gt:http,no-websockets` or `/gt:auto,no-websockets` and check if that fixes your issue.

**Comment by kinnairdclan** [comment]
Thank you, `/gt:auto,no-websockets` did do the trick. I appreciate you taking the time to recommend this!
