### ISSUE TITLE
Invalid read size of when using clipboard

### ISSUE THREAD

**Issue by hardening** [FreeRDP/FreeRDP#904]
Under ubuntu 12.04 with current HEAD, if i copy and paste between local and remote host, i get the following valgrind backtrace for an invalid read access:

DBG_CLIPRDR cliprdr_process_format_list_event (51): Sending Clipboard Format List
DBG_CLIPRDR cliprdr_process_receive (207): msgType: CB_FORMAT_LIST_RESPONSE (3), msgFlags: 1 dataLen: 0
DBG_CLIPRDR cliprdr_process_receive (207): msgType: CB_FORMAT_DATA_REQUEST (4), msgFlags: 0 dataLen: 4
DBG_CLIPRDR cliprdr_process_format_data_response_event (318): Sending Format Data Response
==760== Thread 4:
==760== Invalid read of size 1
==760==    at 0x4C2D0E1: memcpy@@GLIBC_2.14 (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==760==    by 0x59A9240: cliprdr_process_format_data_response_event (cliprdr_format.c:323)
==760==    by 0x59A8425: cliprdr_process_event (cliprdr_main.c:256)
==760==    by 0x64AED7F: svc_plugin_process_data_in (svc_plugin.c:278)
==760==    by 0x64AEE9C: svc_plugin_thread_func (svc_plugin.c:305)
==760==    by 0x7102E99: start_thread (pthread_create.c:308)
==760==  Address 0x1121bf2b is 1 bytes after a block of size 58 alloc'd
==760==    at 0x4C2B6CD: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==760==    by 0x6CF22DF: ConvertToUnicode (unicode.c:306)
==760==    by 0x40FD77: xf_cliprdr_process_requested_unicodetext (xf_cliprdr.c:540)
==760==    by 0x41045A: xf_cliprdr_process_requested_data (xf_cliprdr.c:678)
==760==    by 0x41084D: xf_cliprdr_get_requested_data (xf_cliprdr.c:789)
==760==    by 0x4114DC: xf_cliprdr_process_selection_notify (xf_cliprdr.c:1075)
==760==    by 0x40E332: xf_event_SelectionNotify (xf_event.c:644)
==760==    by 0x40EB68: xf_event_process (xf_event.c:955)
==760==    by 0x416776: xf_process_x_events (xfreerdp.c:286)
==760==    by 0x4189BD: xfreerdp_run (xfreerdp.c:1122)
==760==    by 0x418BC6: thread_func (xfreerdp.c:1181)
==760==    by 0x7102E99: start_thread (pthread_create.c:308)
==760== 
DBG_CLIPRDR cliprdr_process_format_list_event (51): Sending Clipboard Format List
DBG_CLIPRDR cliprdr_process_receive (207): msgType: CB_FORMAT_LIST_RESPONSE (3), msgFlags: 1 dataLen: 0

**Comment by akallabeth** [comment]
@hardening Is this fixed or should this remain open?

**Comment by hardening** [comment]
no idea, I will give a try and let you know, that's 3 years ago !

**Comment by akallabeth** [comment]
@hardening yea, long time ^^ cleaning up a few stale issues.

**Comment by hardening** [comment]
I have tested again and I don't see that behaviour, closing.
