### ISSUE TITLE
[xf_gdi_patblt]: unimplemented brush style:129

### ISSUE THREAD

**Issue by rzsn** [FreeRDP/FreeRDP#9070]
When connecting to my WinXP machine using the latest (current as of now) version of FreeRDP from git, the background is painted (as left and right halve), and when the taskbar is supposed to be drawn, I can notice the start button and the RDP client crashes with the following error:

`[17:38:33:568] [11931:11932] [ERROR][com.freerdp.client.x11] - [xf_gdi_patblt]: unimplemented brush style:129
`

> $ xfreerdp /version
> This is FreeRDP version 3.0.0-dev (04fa5b303)
> 

The previously installed version does not exhibit this showstopper bug ( gentoo: net-misc/freerdp 1.2.1_pre20150326-r1 ) and what is now in repository available for downgrade ( net-misc/freerdp-2.10.0-r3::gentoo ) works as well - no bug in:
> $ xfreerdp /version
> This is FreeRDP version 2.10.0 (2.10.0)

Full log below:

> [17:38:27:161] [11931:11932] [INFO][com.freerdp.client.x11] - [xf_setup_x11]: Enabling X11 debug mode.
> [17:38:28:579] [11931:11932] [INFO][com.winpr.timezone] - [winpr_detect_windows_time_zone]: tzid: Europe/Brussels
> [17:38:28:581] [11931:11932] [WARN][com.freerdp.core.connection] - [rdp_client_connect_auto_detect]: messageChannelId == 0
> [17:38:28:581] [11931:11932] [ERROR][com.freerdp.core.license] - [license_read_binary_blob_data]: license binary blob::type expected BB_UNKNOWN, got BB_ERROR_BLOB
> [17:38:28:581] [11931:11932] [WARN][com.freerdp.core.license] - [license_read_binary_blob_data]: license binary blob::type BB_ERROR_BLOB, length=0, skipping.
> [17:38:28:608] [11931:11932] [WARN][com.freerdp.core.connection] - [rdp_client_connect_auto_detect]: messageChannelId == 0
> [17:38:28:657] [11931:11932] [INFO][com.freerdp.gdi] - [gdi_init_ex]: Local framebuffer format  PIXEL_FORMAT_BGRX32
> [17:38:28:657] [11931:11932] [INFO][com.freerdp.gdi] - [gdi_init_ex]: Remote framebuffer format PIXEL_FORMAT_BGR24
> [17:38:28:668] [11931:11932] [INFO][com.freerdp.channels.rdpsnd.client] - [rdpsnd_load_device_plugin]: [static] Loaded fake backend for rdpsnd
> [17:38:28:669] [11931:11932] [INFO][com.freerdp.channels.drdynvc.client] - [dvcman_load_addin]: Loading Dynamic Virtual Channel ainput
> [17:38:28:669] [11931:11932] [INFO][com.freerdp.channels.drdynvc.client] - [dvcman_load_addin]: Loading Dynamic Virtual Channel rdpsnd
> [17:38:31:266] [11931:11945] [ERROR][com.freerdp.channels.rdpdr.client] - [rdpdr_state_check]: channel [RDPDR] received PAKID_CORE_USER_LOGGEDON, expected state RDPDR_CHANNEL_STATE_READY but have state RDPDR_CHANNEL_STATE_CLIENT_CAPS, aborting.
> 
> [17:38:33:568] [11931:11932] [ERROR][com.freerdp.client.x11] - [xf_gdi_patblt]: unimplemented brush style:129
> [17:38:33:568] [11931:11932] [WARN][com.freerdp.core.update] - [update_recv_primary_order]: Primary Drawing Order [0x01] PatBlt failed
> [17:38:33:568] [11931:11932] [ERROR][com.freerdp.core.update] - [update_recv_order]: order flags 11 failed
> [17:38:33:568] [11931:11932] [ERROR][com.freerdp.core.fastpath] - [fastpath_recv_update]: Fastpath update Orders [0] failed, status 0
> [17:38:33:568] [11931:11932] [ERROR][com.freerdp.core.fastpath] - [fastpath_recv_update_data]: fastpath_recv_update() - -1
> [17:38:33:568] [11931:11932] [ERROR][com.freerdp.core.fastpath] - [fastpath_recv_updates]: fastpath_recv_update_data() fail
> [17:38:33:568] [11931:11932] [ERROR][com.freerdp.core.rdp] - [rdp_recv_callback_int]: CONNECTION_STATE_ACTIVE status STATE_RUN_FAILED [-1]
> [17:38:33:568] [11931:11932] [ERROR][com.freerdp.core.transport] - [transport_check_fds]: transport_check_fds: transport->ReceiveCallback() - STATE_RUN_FAILED [-1]
> [17:38:33:568] [11931:11932] [ERROR][com.freerdp.core] - [freerdp_abort_connect_context]: ERRCONNECT_CONNECT_CANCELLED [0x0002000B]
> [17:38:33:568] [11931:11932] [INFO][com.freerdp.client.common] - [client_auto_reconnect_ex]: Network disconnect!
> [17:38:33:568] [11931:11932] [WARN][com.freerdp.client.common] - [client_auto_reconnect_ex]: Connection aborted by user
>

**Comment by akallabeth** [comment]
do not use `/gdi:hw`and it will work.

**Comment by rzsn** [comment]
Thanks, removal of the `/gdi:hw` did solve this stability/crash issue.
**This one is closed, I agree.**

(the experience seems a bit worse though - like redraws are slower now? but okay.. will live with it)
