### ISSUE TITLE
[SDL] add clipboard support

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#9075]
add clipboard support for sdl client

most likely will require `SDL3` as their clipboard `API` should be sufficient for our needs and with `SDL2` we can not properly integrate to the native event loops

TODO:
* wayland
* x11
* windows
* apple
* android

**Comment by akallabeth** [comment]
will have to wait for `SDL3` which will provide an appropriate `API` https://github.com/libsdl-org/SDL/issues/7625

**Comment by ValentinChirikov** [comment]
> will have to wait for `SDL3` which will provide an appropriate `API` [libsdl-org/SDL#7625](https://github.com/libsdl-org/SDL/issues/7625)

Hi ! Seems SDL3 closed the issue with API 2 weeks ago

**Comment by akallabeth** [comment]
@ValentinChirikov yes, but sdl3 is not a thing yet. (release is far off)
we need to port to sdl3 first (did that in a branch) but that is incompatible with sdl2.

**Comment by shmerl** [comment]
Are there some plans to work on SDL3 soon or it's still a distant plan?

**Comment by akallabeth** [comment]
@shmerl as there are preview releases of `sdl3` now available we´ll start working on this as soon as we have more important bugs worked out.
of course, pull requests / help is always welcome.
