### ISSUE TITLE
What's the status of the native Mac client?

### ISSUE THREAD

**Issue by andreyvit** [FreeRDP/FreeRDP#909]
Hey,

I'm looking to use FreeRDP as part of a Mac application. It looks awesome, but I'm looking to use the native client from `client/Mac` rather than the X11-based one.

Unfortunately, while xfreerdp works for me, the native Mac app refuses to show anything but a grey background (xfreerdp shows a grey background plus a proper login screen with the same command-line options).

This is actually an improvement from a few weeks ago, when I could only get a black screen out of the box. After a few hours of debugging, I managed to get it to render part of the screen. Unfortunately, I cannot name the culprit because I was trying all sorts of crazy things. I think that a major progress has been made when I rewrote drawRect to use CoreImage APIs rather than NSBitmapImageRep (but it was late at night and I might have been confused).

I have reset to the master's HEAD today, and I'm getting a grey screen as mentioned above. So yay, some rendering works, but I figured that it's time to get in touch.

What's the current state of the client/Mac port? What remains to be done?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
