### ISSUE TITLE
Changelog in master?

### ISSUE THREAD

**Issue by hum4nizer** [FreeRDP/FreeRDP#9096]
Hi!

Why is there a changelog in the master branch that is last updated 3 years ago @ version 2.2.0? If the changelog isn't used it's probably better to delete it from master.

Best regards,
Johnny

**Comment by akallabeth** [comment]
@hum4nizer and do you see any 3.0 release yet?

**Comment by hum4nizer** [comment]
No. I see: 
2.3.0
2.3.1
2.3.2
2.4.0
2.4.1
2.5.0
2.6.0
2.6.1
2.7.0
2.8.0
2.8.1
2.9.0
2.10.0

not included in the changelog file in the root of master.

**Comment by akallabeth** [comment]
@hum4nizer then check the proper branch `stable-2.0` 
master is `NOT` where stable releases are tagged from.

**Comment by hum4nizer** [comment]
Thank you so much! There it is.
