### ISSUE TITLE
xfreerdp3 (master) fails to connect to FreeRDP-based servers with multimonitor configs (and `/multimon`)

### ISSUE THREAD

**Issue by pnowack** [FreeRDP/FreeRDP#9136]
Affected version: current master (stable-2.0 is unaffected)

Reproduction steps:
1. Prepare credentials for the shadow server, e.g. via `winpr-hash3 -u TEST -p 1234 -f sam -v 1 > sam`
2. Start the shadow server via e.g. `freerdp-shadow-cli3 /sam-file:sam`
3. Attach another monitor to the system (doesn't matter the size or position)
4. Connect with xfreerdp3 to the shadow server, e.g. with the cmdline `xfreerdp3 /v:[::1] /u:TEST /p:1234 /dynamic-resolution /f /multimon`

Observation: The connection sequence does not complete, xfreerdp3 hits some timeout and drops the connection.

Logs:
server side (shadow server): 
[shadow server log (end part) (without x11 error badmatch errors).txt](https://github.com/FreeRDP/FreeRDP/files/11951057/shadow.server.log.end.part.without.x11.error.badmatch.errors.txt)
client side (xfreerdp3): 
[log xfreerdp3 (just the necessary end part).txt](https://github.com/FreeRDP/FreeRDP/files/11951067/log.xfreerdp3.just.the.necessary.end.part.txt)

I came upon this issue while testing this with a local g-r-d branch first, and then tested this with the shadow server too.
This issue does not happen, when connecting with xfreerdp2 (stable-2.0) or mstsc.

**Comment by akallabeth** [comment]
@pnowack ok, looks like we handle `RNS_UD_CS_SUPPORT_MONITOR_LAYOUT_PDU` wrong.
try to set `FreeRDP_SupportMonitorLayoutPdu` to `TRUE` in shadow server (default is `FALSE`) and check if it works then.
