### ISSUE TITLE
xfreerdp SPNEGO fails  after installation of Windows 10 update kb5028166 

### ISSUE THREAD

**Issue by rkbwde** [FreeRDP/FreeRDP#9155]
**Describe the bug**
xfreerdp fails to connect with errors:

SPNEGO failed with NTSTATUS: STATUS_TRUSTED_RELATIONSHIP_FAILURE [0xC000018D]

nla_recv_pdu:freerdp_set_last_error_ex ERRCONNECT_AUTHENTICATION_FAILED [0x00020009]

rdp_recv_callback: CONNECTION_STATE_NLA - nla_recv_pdu() fail

transport_check_fds: transport->ReceiveCallback() - -1

Connecting as local admin user with  xfreerdp  works. 

Connecting from a Win10 machine works also for domain users.

**To Reproduce**
1. Connect to a Win10 box as *domain user* after installing Windows 10 update kb5028166. 

**Application details**
* FreeRDP version 2.10.0
* command line: xfreerdp +clipboard /d:dom1 /u:user1 /v:machine1 /geometry /p:password1  /size:95% /multimon /dynamic-resolution

**Environment (please complete the following information):**
 - Linux OpenSuSE 15.4

**Comment by mfleisz** [comment]
@rkbwde can you try to connect with a current master/nightly build?

**Comment by akallabeth** [comment]
@rkbwde https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/troubleshoot-broken-secure-channel suggests this is an issue with your windows 10 machine? (note: `FreeRDP` 2.0 does not use `kerberos`, so it is most likely that this is why you only get the failure with `xfreerdp` and not `mstsc`)

**Comment by rkbwde** [comment]
@akallabeth   Thnx for the link. 

I left and re-joined the domain already - no change :-(

But I can login via VNC so the trust between virtual machine and domain controller should be OK.  xfreerdp fails nevertheless :-(

And there has to be a connection to KB5028166. I connected succesfully with xfreerdp this morning. Then the VM suggested to install KB5028166. After reboot, I got the error messages mentioned above. 

BTW: Domain controller is a Samba PDC.

**Comment by rkbwde** [comment]
@mfleisz  I did a "git clone" and built a local version here.

 That version works if I add "/sec:tls". 

Thnx  :-)  :+1: 

P.S. Without that switch I get errors about an unknown Kerberos Realm.

**Comment by akallabeth** [comment]
@rkbwde if `/sec:tls` works with `master` that should also work with stable-2.0?
which error do you get with `master` exactly? (kerberos stuff are just warnings, no failures)

**Comment by rkbwde** [comment]
git-version without /sec:tls:

Kerberos messages are prefixed with "ERROR", not with "WARN":

[14:13:19:64] [23250:00005ad3] [ERROR][com.winpr.sspi.Kerberos] - [kerberos_log_msg]: KDC for Realm »DOM1« can't be found

[14:13:19:272] [23250:00005ad3] [ERROR][com.freerdp.core.nla] - [nla_recv_pdu]: SPNEGO failed with NTSTATUS: 0xC000008D
[14:13:19:272] [23250:00005ad3] [ERROR][com.freerdp.core] - [nla_recv_pdu]: ERRCONNECT_AUTHENTICATION_FAILED [0x00020009]
[14:13:19:272] [23250:00005ad3] [ERROR][com.freerdp.core.rdp] - [rdp_recv_callback_int][0x1c1ef60]: CONNECTION_STATE_NLA - nla_recv_pdu() fail
[14:13:19:272] [23250:00005ad3] [ERROR][com.freerdp.core.rdp] - [rdp_recv_callback_int][0x1c1ef60]: CONNECTION_STATE_NLA status STATE_RUN_FAILED [-1]
[14:13:19:272] [23250:00005ad3] [ERROR][com.freerdp.core.transport] - [transport_check_fds]: transport_check_fds: transport->ReceiveCallback() - STATE_RUN_FAILED [-1]

**Comment by mfleisz** [comment]
@rkbwde please attach the complete log - there might be some information before the actual `[ERROR]` lines that are relevant

**Comment by akallabeth** [comment]
@rkbwde could you:
1. run this with `/log-level:debug` and attach the full log?
1. If I don´t overlook something, this error code is sent from the server and it maps `NTSTATUS 0xC000008D` to `STATUS_FLOAT_DENORMAL_OPERAND` ?!?

**Comment by akallabeth** [comment]
@rkbwde and could you please:
1. tell if `/sec:tls` works with your `xfreerdp` 2.10.0
2. tell if `mstsc` connects using `tls` (e.g. you see a login screen if you do not provide the password) or `NLA` (credentails entered before connection)

**Comment by akarl10** [comment]
just tried with win11. same STATUS_TRUSTED_RELATIONSHIP_FAILURE

according to https://support.microsoft.com/en-us/topic/july-11-2023-kb5028166-os-builds-19044-3208-and-19045-3208-eab49ea6-3133-41c8-845f-a14a329c6c20

`This update addresses security issues for your Windows operating system.`

Whatever that means

do you have a samba based dc?

**Comment by akarl10** [comment]
they already found the issue upstream
https://bugzilla.samba.org/show_bug.cgi?id=15418

**Comment by akarl10** [comment]
just confirmed that the same happens with mstsc. They also describe the issue being the computer not being able to communicate with the domain controller.

a workaround is, a @rkbwde found out, disable require "network layer authentication" on the rdp server and use /sec:tls instead.
mstsc falls back automatically

If you have freerdp master with kerberos support and you use the /u:domainuser /v:<hostname not ip address> then it should use kerberos and work (both freerdp and mstsc if you use the hostname)

**Comment by akallabeth** [comment]
ok, closing as not our bug.

**Comment by stolzpet** [comment]
Workaround does not work for me:
- NLA is disabled on rdp server
- I use /sec:tls

xfreerdp /u:admin /v:10.21.30.20 /p:XXXX /d:schule /cert:ignore /sec:tls /gfx:rfx

Server: Windows 10 Version 22H2 fore x64
Client: freerdp 2.10.0-3.1-x86_64 on openSUSE Tumbleweed 20230719

![grafik](https://github.com/FreeRDP/FreeRDP/assets/43900659/cf75edc2-de04-4c4a-8b40-0d770ce3b65b)

![grafik](https://github.com/FreeRDP/FreeRDP/assets/43900659/fb90c3b2-a105-4b96-aad7-e7c42c566a91)

**Comment by akarl10** [comment]
@stolzpet this probably means that the login does not work enierly (it should fallback to kerberos)
Is the domain a samba nt4 domain? With that only a upgrade of samba to a version that has a fix for this issue.

**Comment by stolzpet** [comment]
Samba version 3.6.25
