### ISSUE TITLE
After using the "/admin" flag, it has been blocked indefinitely.

### ISSUE THREAD

**Issue by plume-cat** [FreeRDP/FreeRDP#9162]
freerdp 2.10
server: windows-server 2012 R2
client: freerdp 2.10

A Windows Server 2012 server can be successfully connected using a script similar to the following: /mstsc /admin /v:xxx.xxx.xxx.xx. It prompts for a username and password. I see that FreeRDP also supports the "/admin" flag, but when I enable it, the interface gets stuck.

this is the logs 
[log.txt](https://github.com/FreeRDP/FreeRDP/files/12049597/log.txt)

How to handle this issue

**Comment by akallabeth** [comment]
@plume-cat you might want to add a log you did with `FreeRDP` ;)

**Comment by akallabeth** [comment]
for reference, just tried a connect to a `2012r2 standard` machine with `xfreerdp /v:<host> /admin /u:<user>` and it connects quite fine.

**Comment by plume-cat** [comment]
> for reference, just tried a connect to a `2012r2 standard` machine with `xfreerdp /v:<host> /admin /u:<user>` and it connects quite fine.

Ok, I will regenerate the freerdp log, and then please help me to have a look
