### ISSUE TITLE
Abnormal bandwidth usage

### ISSUE THREAD

**Issue by KingingWang** [FreeRDP/FreeRDP#9163]
When I use the built-in remote desktop of Windows in Windows operating system, the bandwidth occupied is up to 10MB. When I use freerdp in Linux, the bandwidth occupied can reach 100M, and there is no remote desktop process built in Windows system. What should I configure?

**Comment by akallabeth** [comment]
well, best start with what you are doing ;)
your local setup, your command line, your remote os
