### ISSUE TITLE
For xfreerdp version 2.10.0, how can I execute 'xfreerdp ... /app:||' twice to open two browser windows

### ISSUE THREAD

**Issue by norwaytree** [FreeRDP/FreeRDP#9201]
I executed the command 'xfreerdp -v:192.168.56.122 -u:test -p:111111 /app:"||iexplore_8" /cert-ignore' to open a browser window. However, when I repeated the command in another terminal, it still displayed the first window. How can I open two browser windows by executing the command again?

**Comment by akallabeth** [comment]
@norwaytree just like that, the first session will be disconnected and a new one created (and a new window too)
there is currently no mechanism to do that other than that (or spawning a `cmd` and starting it there)

**Comment by norwaytree** [comment]
@akallabeth ,Thank you for your response, but why can the freerdp 3.10.0-dev version do this? I executed the command twice, and although the first session was disconnected, two browser windows were indeed opened.

**Comment by norwaytree** [comment]
@akallabeth I want to ask why in version 2.10.0, performing the same operation will always display only one browser window, but in version 3.10.0-dev, despite also being disconnected, it can display multiple browser windows.

**Comment by akallabeth** [comment]
@norwaytree most likely server configuration.
`stable-2.0` only supports old rails, `3.0` a newer version of it.
