### ISSUE TITLE
Washed out colors over rdp

### ISSUE THREAD

**Issue by Kamilcuk** [FreeRDP/FreeRDP#9221]
**Describe the bug**
The colors transferred by freerdp do not match colors reported by windows color picker. They are washed off.

**To Reproduce**
Connect to my company freerdp. Run a color picker on host and check the color.

**Expected behavior**
The colors should be exactly the same.

**Screenshots**
![obraz](https://github.com/FreeRDP/FreeRDP/assets/15679217/d5e55895-6d48-459c-bf91-71ac8512d7fb)

I am testing the "red" color around test. The color picker running on windows reports the color to be #b21818. Yet, KColorChooser running on my host reports it as #b61616. This happens with all colors, they are slightly off, slightly with less color.

**Application details**
* FreeRDP version (`xfreerdp /version`) 
    - `This is FreeRDP version 3.0.0-dev2 (045fcedd1)` 
    - and also 2.10.0 from Archlinux repos
* Command line used
    -  `xfreerdp /v:... /d:... /u:... /p:... /window-position:0x0 /size:1280x1378 /cert:ignore /audio-mode:2 /network:lan /log-level:INFO /rfx /bpp:32`
* Output of `xfreerdp /buildconfig`
```
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_JOURNALD_H=TRUE WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_ICU=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=OFF WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_VAAPI=ON WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WEBVIEW=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON WITH_ZLIB=ON
```
* OS version connecting to (server side)
   -  Windows10 Pro 10.0.19045 
* If available, the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
   - https://chmura.kamcuk.top/s/Eb5umMk2tn8z071
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help
   - I used https://aur.archlinux.org/packages/freerdp-git

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..] Archlinux
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10] Archlinux
 - Architecture: [amd64, arm]: amd64

**Additional context**
+bpp:8 slightly change the discoloration, but it is still very much noticeable.

I think this all may be related to `Local framebuffer format  PIXEL_FORMAT_BGRX32 Remote framebuffer format PIXEL_FORMAT_BGRA32`

And also: in 3.0, man page is totally badly generated and /list:kbd-lang segfaults.

Thanks for making xfreerdp, you are great!

**Comment by pnowack** [comment]
> I am testing the "red" color around test. The color picker running on windows reports the color to be #b21818. Yet, KColorChooser running on my host reports it as #b61616. This happens with all colors, they are slightly off, slightly with less color.

This is expected. When frame content is transmitted from the server to the client, it is compressed with codecs, such as AVC, RFX, or NSC.
These codecs are all in some way lossy. This can already be in the colour conversion (those codecs use a different colour spaces (YUV, YCbCr, YCoCg), or at the quantization stage.
Without lossy compression, the network usage of your session would be huge. There is simply nothing that can be done here, xfreerdp just displays what it received. That's it.

**Comment by Kamilcuk** [comment]
There see no difference with `-compression`, except that it is slower. Anything I might try?

**Comment by akallabeth** [comment]
@Kamilcuk you misunderstand what that option should do (it is a transport compression similar to `http` `gzip`) not a bitmap compression algorithm

**Comment by akallabeth** [comment]
@Kamilcuk you might want to experiment with some options (`/bpp:32` or `/rfx` or `/gfx:rfx` or `/gfx` or `/gfx:avc444`) and check which works best for you.
Depending on your server (the options the client supplies are mere suggestions, it is up to the server to pick something) you might get different (better? worse?) results.

**Comment by Kamilcuk** [comment]
Amazing! Closing, as I understand, this is not a bug.
Thank you for your help!
Measuring RGB 172,24,24 these are the results:
- /bpp:32 - 182,22,22
- /bpp:32 /rfx - 182,22,22
- /bpp:32 /gfx:rfx - 178,24,24 !!!!!
- /gfx:rfx - also 178,24,24
- /bpp:32 /gfx - 178,22,22
- /bpp:32 /gfx:avc444 178,22,22
That's great - /gfx:rfx looks crisp and great! I have been working on this issue for a months long time, trying to setup crisp rendering of fonts in windows, when finally realized it is just rdp not displaying properly. I'll be using /gfx:rfx, thank you so so much!
