### ISSUE TITLE
Unable to launch remoteapp via CyberArk

### ISSUE THREAD

**Issue by Nelson-Bigmouth** [FreeRDP/FreeRDP#9260]
**Describe the bug**
I try to use xfreerdp to lauch remoteapp via CyberArk running in Windows. xfreerdp is able to connect and show the remote app (Chrome). But once CyberArk intercepts the app window (Chrome) and enter the credential on behalf of me, the app window closes and no more app window shows up.

RDP file:
full address:s:psm5-uat.abc.com
server port:i:3389
username:s:PSM@2fbea6ae-ec3d-4adf-a5a0-a520b05b4324
alternate shell:s:PSM@2fbea6ae-ec3d-4adf-a5a0-a520b05b4324
desktopwidth:i:1024
desktopheight:i:768
screen mode id:i:1
redirectdrives:i:0
drivestoredirect:s:
redirectsmartcards:i:0
EnableCredSspSupport:i:0
redirectcomports:i:0
remoteapplicationmode:i:1
remoteapplicationprogram:s:||PSMInitSession
remoteapplicationname:s:PSM-Oracle-WebLogic-Chrome
disableconnectionsharing:i:1
use multimon:i:0
span monitors:i:0

Trace log before "looping":
[09:35:21:878] [10990:11012] [DEBUG][com.freerdp.codec.progressive] - rect[0]: x: 320 y: 256 w: 64 h: 64
[09:35:21:878] [10990:11012] [DEBUG][com.freerdp.codec.progressive] - PROGRESSIVE_WBT_TILE_FIRST
[09:35:21:878] [10990:11004] [DEBUG][com.freerdp.codec.progressive] - ProgressiveTileFirst: quantIdx Y: 0 Cb: 0 Cr: 0 xIdx: 5 yIdx: 4 flags: 0x7A quality: 255 yLen: 359 cbLen: 232 crLen: 232 tailLen: 0
[09:35:21:879] [10990:11012] [DEBUG][com.freerdp.codec.progressive] - ProgressiveFrameEnd
[09:35:21:880] [10990:11012] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [1] from xf_sw_end_paint
[09:35:21:882] [10990:11012] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:  [0] from xf_sw_end_paint
[09:35:21:882] [10990:11012] [DEBUG][com.freerdp.channels.drdynvc.client] - write_data: ChannelId=6 size=20
[09:35:21:882] [10990:10991] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [1] from xf_process_x_events
[09:35:21:882] [10990:10991] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:  [0] from xf_process_x_events
[09:35:21:891] [10990:10991] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [1] from xf_process_x_events
[09:35:21:891] [10990:10991] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:  [0] from xf_process_x_events
[09:35:21:905] [10990:11012] [DEBUG][com.freerdp.channels.drdynvc.client] - order_recv: Cmd=0x1, Sp=3 cbChId=0
[09:35:21:905] [10990:11012] [DEBUG][com.freerdp.channels.drdynvc.client] - process_create_request: ChannelId=15 ChannelName=AUDIO_PLAYBACK_DVC
[09:35:21:905] [10990:10991] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [1] from xf_process_x_events
[09:35:21:905] [10990:11012] [DEBUG][com.freerdp.channels.drdynvc.client] - no listener
[09:35:21:905] [10990:10991] [TRACE][com.freerdp.client.x11] - xf_unlock_x11_:  [0] from xf_process_x_events
[09:35:21:905] [10990:10991] [TRACE][com.freerdp.client.x11] - xf_lock_x11_:    [1] from xf_process_x_events

**To Reproduce**
1. Create a new RDP file from CyberArk
2. Run xfreerdp with the RDP file
3. Follow the RDP session to login

**Expected behavior**
A "Chrome" remoteapp is supposed to show

**Application details**
* FreeRDP version (`xfreerdp /version`)
This is FreeRDP version 2.10.0 (2.10.0)
* Command line used
xfreerdp cyberark.rdp /sec:rdp
* Output of `xfreerdp /buildconfig`
This is FreeRDP version 2.10.0 (2.10.0)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_BACKTRACE=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 HAVE_EXECINFO_H=ON HAVE_EXECINFO_HEADER=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_PIXMAN_REGION=OFF HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -fdebug-prefix-map=/build/freerdp2-ZaAgVo/freerdp2-2.10.0+dfsg1=/usr/src/freerdp2-2.10.0+dfsg1-1 -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 12.2.0
Target architecture: x64
* OS version connecting to (server side)
Windows 2016
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]
 ubuntu
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]
23.04
 - Architecture: [amd64, arm]:
amd64

**Comment by akallabeth** [comment]
not entirely sure we can do something here?
you might check if that works with thincast client (flatpak) as that one has another RAILS implementaion on top of FreeRDP, if not then most likely not, if yes then I´m all ears.

**Comment by Nelson-Bigmouth** [comment]
I install thincast using snap and I get this error message:

![thincast-snap](https://github.com/FreeRDP/FreeRDP/assets/141337394/72cbb6bd-084e-44b9-94c2-ca977355738c)

**Comment by akallabeth** [comment]
ah, damn, missed the server 2008 part. that does not support high def rail :/

**Comment by Nelson-Bigmouth** [comment]
But the remote server is a Windows 2016, not 2008.

**Comment by akallabeth** [comment]
@Nelson-Bigmouth then your server is configure awkwardly. (server 2016 should support that if configured correctly)
also, `rdp security` is quite outdated, is there a reason to use that?

**Comment by Nelson-Bigmouth** [comment]
I think people configure the Windows 2016 that way because of product (CyberArk) requirements.

I believe my problem is related to the "remoteapplicationprogram:s:**||PSMInitSession**" in the RDP file. If I change that line to a regular Windows program (e.g., notepad.exe), the remoteApp shows up correctly using xfreerdp.
