### ISSUE TITLE
Failed to run RemoteApp

### ISSUE THREAD

**Issue by diger74** [FreeRDP/FreeRDP#927]
Hi everybody!

I'm trying to run xfreerdp in RemoteApp mode but have no luck. Here is what I've tryed:

xfreerdp /u:user /d:domain /p:password /app:"||calc" /v:server
loading channel rail
Warning xf_GetWindowProperty (156): Property 256 does not exist
connected to server:3389
connected to server:3389
connected to server:3389
Unable to get current timezone rule
RAIL exec error: execResult=RAIL_EXEC_E_FAIL NtError=0x2

xfreerdp /u:user /d:domain /p:password /app:%SYSTEMDRIVE%\Windows\system32\calc.exe /v:server
loading channel rail
Warning xf_GetWindowProperty (156): Property 261 does not exist
connected to server:3389
connected to server:3389
connected to server:3389
Unable to get current timezone rule
RAIL exec error: execResult=RAIL_EXEC_E_NOT_IN_ALLOWLIST NtError=0x15

What am I doing wrong? Please could you give me an example of using app param?
P.S. I should note thatconnection from my Windows clien with RemoteApp mode is pretty good.

Thanks in advance!

**Comment by boospy** [comment]
Thanks too for this info :)

**Comment by Chinggis6** [comment]
I could make it work by installing [RemoteApp Tool](http://www.kimknight.net/remoteapptool) on Windows 10, editing the name of the application, and then specifying it on the command-line as `/app:'||appname'` (surround with single or double quotes, it doesn't matter).
