### ISSUE TITLE
`FindFirstFile` fails to list a directory if the parent is not accessible

### ISSUE THREAD

**Issue by thenextman** [FreeRDP/FreeRDP#9277]
**Describe the bug**
`FindFirstFile` will not be able to list a directory if the parent directory cannot be opened. For example, on Android we can redirect an SD card (the path will vary but in my case is `/storage/emulated/0`). `FindFirstFile` tries to call `opendir` on the parent directory (in this case `/storage/emulated`) which is _not_ accessible and causes the file listing to fail. Mapping a subdirectory (for example `/storage/emulated/0/Download`) does work successfully.

**To Reproduce**
Redirect a drive mapping a directory whose parent directory is not accessible.

**Expected behavior**
We should be able to list the directory.

**Application details**
* FreeRDP version: master
* OS version connecting to (server side): Windows 11

**Environment (please complete the following information):**
 - OS: Android
 - Version/Distribution: Android 13
 - Architecture: arm64

The issue was introduced in [#9197](https://github.com/FreeRDP/FreeRDP/pull/9197), however that corrected an earlier bug that prevented this scenario working (trying to find files by the "." pattern, where "." and ".." files don't exist on Android external storage).

**Comment by thenextman** [comment]
While this behaviour seems to be on-spec for [FindFirstFile](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilea):

> If the string ends with a wildcard, period (.), or directory name, the user must have access permissions to the root and all subdirectories on the path.

However, using this in the drive redirection _does_ break certain scenarios (like the original issue(

**Comment by akallabeth** [comment]
@thenextman does it work with redirecting `/storage/emulated/0/.` for android? since you have access to `/storage/emulated/0` the `opendir` should work and the fix would be contained to the android client components

**Comment by thenextman** [comment]
@akallabeth My colleague tells me that does _not_ work, I will need to debug and see exactly why not. But it's important to note that the external storage doesn't seem to use "." and ".." files...
