### ISSUE TITLE
SPNEGO received NTSTATUS: STATUS_LOGON_FAILURE [0xC000006D] from server

### ISSUE THREAD

**Issue by EaryTide** [FreeRDP/FreeRDP#9302]
**Describe the bug**
I am using xFreeRDP software on my Lenovo ThinClient M75n (LeTOS) Thinkcentre to connect from my Linux machine to a Windows Server 2019. Here, I use the YubiKey 5 NFC smartcard from Yubico for authentication. The smartcard contains a certificate which is used for login and authentication. The certificate used is valid and correct.

To narrow down the error, I have performed a test setup with a Lenovo notebook and Ubuntu 22.04.3 LTS. I get the following error message when trying to connect:

`[15:12:13:486] [10900:10901] [WARN][com.freerdp.core.nla] - SPNEGO received NTSTATUS: STATUS_LOGON_FAILURE [0xC000006D] from Server`

According to the Microsoft error code, this is an error "The attempted logon is invalid. This is either due to a bad username or authentication information." This error occurs when the credentials or username are incorrect. However, since I am working with certificates, I suspect that the certificate submission or verification is not working properly.

I am sure that the username and password are correct. Therefore, it seems reasonable to assume that there are problems with the transmission or verification of the certificates. However, I am unsure of the best way to check and fix this problem. Any tips or guidance on how I can set up the certificate transfer correctly and fix this error would be extremely helpful.

**To Reproduce**
1. Use YubiKey Smartcard with Certificate from Windows Server
2. Open Terminal on your Ubuntu or LeTOS & use my command
3. SPNEGO Error should appear

**Expected behavior**
The connection to the partner should be successfully established and the RDP session window should open.

**Screenshots**

**Application details**
* FreeRDP version: FreeRDP 2.6.1 on Ubuntu / FreeRDP 3.0.0-dev (n/a) on LeTOS
* Command line used: `xfreerdp /log-level:trace +sec-nla +sec-tls +sec-rdp  /v:<IP-ADDRESS> /smartcard-logon /u:<USERNAME> /p:"" /d:<DOMAIN> /dynamic-resolution`

> _(I think that in this case it doesn't matter if I set the password correctly or leave it blank as above, if I remove /p:"" a completely different error message pops up)_

* Output of `xfreerdp /buildconfig` on LeTOS Device
```
This is FreeRDP version 3.0.0-dev (n/a)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL= HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:               -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 7.3.0
Target architecture: x64
```
* Output of `xfreerdp /buildconfig` on Ubuntu Device (Test-Setup)
```
This is FreeRDP version 2.6.1 (2.6.1)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_H=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_ICU=ON WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -g -O2 -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 11.3.0
Target architecture: x64
```

* OS version connecting to (server side): LeTOS-2.1-B-G6-2.1.07d / Ubuntu 22.04.3 LTS (Test-Setup)

**Environment:**
 - OS: [LeTOS (Lenovo Operating System, Windows Server, Ubuntu] 
 - Version/Distribution: LeTOS-2.1-B-G6-2.1.07d, Windows Server 2019, Ubuntu 22.04.3 LTS
 - Architecture: x64

* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt`
Logs From Ubuntu Device:
[freerdplog.txt](https://github.com/FreeRDP/FreeRDP/files/12376946/freerdplog.txt)
[pcscdlog.log](https://github.com/FreeRDP/FreeRDP/files/12376947/pcscdlog.log)

  Logs From LeTOS Device:
[freedrdpLeTOSlog.txt](https://github.com/FreeRDP/FreeRDP/files/12379720/freedrdpLeTOSlog.txt)
[pcscdLeTOSlog.txt](https://github.com/FreeRDP/FreeRDP/files/12377450/pcscdLeTOSlog.txt)

If you have any questions, you can of course ask them.

With kind regards EaryTide

**Comment by EaryTide** [comment]
> smartcard logon is only plainly functional with FreeRDP 3.0. When you specify `/smartcard-logon` xfreerdp shall deduce almost all the fields for user/domain if your yubikey have only 1 cert available for logon (and of course `/p:` is not needed).
> 
> The logs from the LeTOS device are rather strange maybe I'm wrong but it looks a lot like if it was not compiled with the needed stuff for smartcard logon (WITH_PKCS11 ?)

Hello Hardening,

First of all, thank you very much for your answer. The funny thing is that I've been dealing with Yubico support and Lenovo support for over 1.5 months now and even they just pass the blame back and forth.

Unfortunately there are two certificates on the smartcard, but one is not designed for Windows login and is accordingly in a different slot on the smartcard. I have entered the USERNAME, DOMAIN, and PASSWORD as a precaution.

I'm about to try installing version 3.0.0 of FreeRDP on the Ubuntu test device and try the whole process again, but I suspect this will fail again as the LeTOS device has version 3.0.0 installed.

Can you please show me the part where the log from the LeTOS device looks faulty? Then I can report it directly back to support.

What I also notice is that (WITH_PKCS 11) does not appear in the Ubuntu installation, is that somehow relevant?

**Comment by hardening** [comment]
> What I also notice is that (WITH_PKCS 11) does not appear in the Ubuntu installation, is that somehow relevant?

Smartcard logon will never work without that.

About multiple certificates as we filter candidate certificate, if we found just one that may work out-of-the box (as our filter criteria include check of EKU and smartcard logon attr). Also note that if you specify a domain or a user, these are used to filter the candidate certs (then the user and domain are checked when we build the list of certificate candidates).

**Comment by EaryTide** [comment]
> > What I also notice is that (WITH_PKCS 11) does not appear in the Ubuntu installation, is that somehow relevant?
> 
> Smartcard logon will never work without that.
> 
> About multiple certificates as we filter candidate certificate, if we found just one that may work out-of-the box (as our filter criteria include check of EKU and smartcard logon attr). Also note that if you specify a domain or a user, these are used to filter the candidate certs (then the user and domain are checked when we build the list of certificate candidates).

I am now forwarding this to support and waiting for an answer. As soon as I know something, I would write it back in here.

**Comment by hardening** [comment]
1 year without any feedback, reopen it if needed.
