### ISSUE TITLE
REQ: Switch to from guest desktop to host desktop without moving the mouse 

### ISSUE THREAD

**Issue by guidovansteen** [FreeRDP/FreeRDP#931]
I switch between the guest desktop and the host desktop quite often. To return to the host desktop I use "ctrl-alt-enter" (toggle full-screen). However, this only returns the focus to the host desktop when the mouse pointer in the taskbar area. Otherwise the focus remains with the guest desktop. So, in order to return to the host desktop I often have to move the mouse pointer to the taskbar area. However, I usually try to avoid using the mouse. So, I would prefer switching between desktops in another way. 

Sometimes I have to move the mouse again to move the focus back from the host desktop to the guest desktop. In this case the focus will only switch when the mouse pointer outside in the host desktop's task bar. 

To me it would be very useful if I could switch between the host desktop and the guest desktop irrespective of the actual position of the mouse pointer. 

For this I would like to suggest a key combination like "ctrl-alt-arrowup". I think it would even be better if the desired key combination could be specified from the command-line. 

I also suggest removing the current behavior with respect to "alt-tab" and the location of the mouse pointer. Thus if one uses alt-tab to go to a xfreerdp window the focus should not be changed automatically when the mouse pointer is outside the host desktop's task bar. Instead I would rather use "ctrl-alt-arrowup" to change focus. 

(This is a follow-up to: https://github.com/FreeRDP/FreeRDP/issues/907) 

P.S. This feature request seems to be related to the functions XGrabKeyboard (and XUngrabKeyboard).

**Comment by daklaus** [comment]
+1 for me too! I would like to be able to switch to another desktop (on most distros with Ctrl+Alt+Up|Down|Right|Left) without having to exit fullscreen mode in my FreeRDP session.

**Comment by jiajunhuang** [comment]
+1.

**Comment by slackline** [comment]
I would like to see this too, its a minor inconvenience to have to take our hands off of the keyboard to move the mouse so that focus returns to the host desktop, but when switching lots it becomes a real bind.

Personally I switch lots because I edit my files on the host desktop then run them on the guest because of slight lag typing on the guest desktop.

**Comment by tweej** [comment]
+1
In my case, I'm looking for this feature while FreeRDP is in full screen mode.

**Comment by Rudedog9d** [comment]
There has been progress at the link mentioned before, check it out! [FreeRDP/FreeRDP-old#49](https://github.com/FreeRDP/FreeRDP-old/issues/49)

**Comment by jpeg729** [comment]
#3622 introduced temporary ungrabbing via Right-Ctrl.

So press Right-Ctrl, then press Alt-tab or whatever, then close this issue.
