### ISSUE TITLE
ffmpeg [aac @ 0x5647e568c900] Input contains (near) NaN/+-Inf

### ISSUE THREAD

**Issue by limingyuxia** [FreeRDP/FreeRDP#9318]
Releated pull request for master: 
the rpc camera rtsp stream audio codec is pcm_mulaw. i want to put it into mp4 container.so i need use ffmpeg transition the audio to aac format。but i come cross the error [aac @ 0x5647e568c900] Input contains (near) NaN/+-Inf for every frame.

**Comment by akallabeth** [comment]
@limingyuxia not much we can do here, the input is of `uint16` type and `FFMPEG` seems to have an issue with conversion to/from float format.
