### ISSUE TITLE
Cannot enforce audio input (microphone) format parameter

### ISSUE THREAD

**Issue by HazelHex** [FreeRDP/FreeRDP#9327]
Hi,
Seems that /microphone:format parameter does not work properly, except for 0x0001 (PCM).

- When used without _format_, the ALAW codec is chosen (0x0006) by default, the microphone is properly forwarded to the server, but there is no sound there, level meters are down. On client side, pavucontrol shows, that FreeRDP is using the mic, and the level meters are lit.
- When used with _format:0x0006_, the same default behavior is observed
- When used with _format:0x0001_, the microphone works properly
- When used with any other _format_, for example _format:0xA106_ (as attached in the debug log), the microphone is not forwarded at all. On the client side the PA stream is not created, pavucontrol does not show FreeRDP using the mic. There is no "microphone uses [CODEC]" message in the FreeRDP log, instead rather mysterious message is shown:
```
[16:07:33:897] [19864:19913] [ERROR][com.freerdp.channels.audin.client] - invalid format index 0 (total 0)
[16:07:33:366] [19864:19913] [ERROR][com.freerdp.channels.audin.client] - invalid format index 0 (total 0)
```
The problem reproduces in xfreerdp also.
The microphone selected as the default source in Pulseaudio (PipeWire) and works correctly on the client side, i.e. it records and plays with parecord/paplay.

The server is Windows 10 Pro 22H2. The client is Gentoo v6.1.46 amd64 running FreeRDP version 2.10.0

#### Now what is it for
While the PCM format appears to be problem-free and it just works, at the same time it is rather bandwidth-hungry and the significant voice delay is observed (e.g. Teams meetings).
Forcing the needed codec (or not advertising one) in some working way would be really sweet.

#### The command line is
wlfreerdp /log-level:debug /v:[HOST] /port:[PORT] /u:[USER] /d:[DOMAIN] /from-stdin:force /cert:ignore -sec-rdp -aero -decorations -fonts -gestures -menu-anims -multitouch -themes -wallpaper -window-drag +clipboard +fast-path +suppress-output +auto-reconnect +multitransport /network:auto -drives -home-drive **/microphone:sys:pulse,format:0xA106** /sound:sys:pulse /dynamic-resolution /f /gfx:avc444 +gfx-progressive >/tmp/freerdp.log 2>&1

#### This is Build configuration
BUILD_TESTING=OFF BUILTIN_CHANNELS=ON HAVE_AIO_H=1 HAVE_EXECINFO_BACKTRACE=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 HAVE_EXECINFO_H=ON HAVE_EXECINFO_HEADER=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_PIXMAN_REGION=OFF HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 WITH_ALSA=OFF WITH_CAIRO=OFF WITH_CCACHE=OFF WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=TRUE WITH_FFMPEG=TRUE WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_1_0=OFF WITH_ICU=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=TRUE WITH_OPENH264=TRUE WITH_OPENH264_LOADING=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=OFF WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=OFF WITH_XINERAMA=OFF WITH_XV=OFF WITH_ZLIB=ON
Build type:          RelWithDebInfo
CFLAGS:              -O2 -pipe -march=native -Wno-unused-parameter -Wno-unused-macros -Wno-padded -Wno-c11-extensions -Wno-gnu -Wno-unused-command-line-argument -Wno-deprecated-declarations -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            Clang, 16.0.6
Target architecture: x64

#### Program versions
net-misc/freerdp-2.10.0-r3::gentoo
media-libs/libpulse-16.1-r2::gentoo
media-video/pipewire-0.3.77-r1::gentoo (compiled with ffmpeg)
media-video/ffmpeg-4.4.4-r3

#### Debug log
[freerdp.log](https://github.com/FreeRDP/FreeRDP/files/12420204/freerdp.log)

**Comment by akallabeth** [comment]
that is not a bug, you must compile with `WITH_DSP_EXPERIMENTAL` to get the format encoder working.
as for `ALAW`, there seems to be a bug with pulse? need to check, maybe we should just deactivate that format

**Comment by HazelHex** [comment]
Sadly, Gentoo's portage does not have this USE flag.
Does it mean, that `WITH_DSP_EXPERIMENTAL` replaces `WITH_DSP_FFMPEG` and uses its own codecs?
Is there a way to force the required codec or format to use ffmpeg for encoding?

Well, **alaw** is really old, but it has good characteristics for voice applications, keeping very low bandwidth and latency, while maintaining decent quality. So does **gsm**. I don't know for sure, but it seems that it is working in pipewire/pulseaudio, as the pavucontrol shows the FreeRDP's meters go up and down, as I speak to the microphone. On the other side, the Windows meters are dead.

**Comment by akallabeth** [comment]
@HazelHex no, that is an additional `CMake` parameter that enables `aac` encoding. Does not work reliable with all `FFMPEG` versions though, therefore disabled.
as for `ALAW`, I know the properties, it just does not work in practice (maybe the same reason as `aac`?) and therefore should also be disabled until the issues are resolved.

**Comment by HazelHex** [comment]
Hello dear friends,
Now the same remote side (Windows 10) just hangs, when I enable the microphone forwarding, **even with the PCM!** I have rebooted everything.
It seems that even with `format:1`, when some app under Windows actually starts to use the mic (e.g. Sound Settings -> Record -> Remote input), the mic tray icon shows up, but the whole desktop just freezes and only `pkill wlfreerdp` helps.
When using other than PCM codec, the mic is just silent, so as stated under my first post.
Please advice what additional workarounds/tests I must follow, to make the microphone just work with any codec. Thanks.
[freerdp.log](https://github.com/FreeRDP/FreeRDP/files/12619651/freerdp.log)
