### ISSUE TITLE
Mutliple monitor on the server -> display on multiple windows on the client

### ISSUE THREAD

**Issue by mfauvain** [FreeRDP/FreeRDP#9336]
Not a feature request but I wanted to share something very useful that is (afaik) undocumented.

To display a specific server monitor on the freerdp client, one can use the domain option 
For ex, I connect to a 5 monitor virtualbox like so:

`xfreerdp /v:xxx.xxx.xxx.xxx  -grab-keyboard -f /d:\@1` to display server screen #1
`xfreerdp /v:xxx.xxx.xxx.xxx  -grab-keyboard -f /d:\@2` to display server screen #2

etc..
Initially found this using rdesktop, but xfreerdp has the same option and works better with vbox as it does automatic screen resize better.

**Comment by akallabeth** [comment]
@mfauvain that is actually not a `FreeRDP` (or `rdesktop`) feature but one of `VirtualBox` ;)

**Comment by mfauvain** [comment]
Ah, thx! 
How do we do then when there are physical displays (no virtualbox) on the server and want to have those in multiple windows on the client?

**Comment by akallabeth** [comment]
@mfauvain you don´t. `RDP` is not a mirroring mechanism (yes, there is shadow server, but that is not the main use case) and you have no relation to your physical monitors.
normally you have a single session (=client) with multimonitor support enabled (e.g. that tells the remote your desired monitor resolution, layout, dpi, ...) and the client displays that
by default these are fullscreen sessions, but if you want that in windows, you need to patch the client to show that in windows.

**Comment by mfauvain** [comment]
I see. I do use this functionality a lot and find it useful (remote working from a laptop on a multi display setup). 
Thx for the help.
Regards
