### ISSUE TITLE
Port Tunneling/Forwarding similar to rdp2tcp

### ISSUE THREAD

**Issue by karlmdavis** [FreeRDP/FreeRDP#935]
There's an old plugin/patch for rdesktop: http://rdp2tcp.sourceforge.net/. This provided support for tunneling/forwarding TCP connections over the RDP virtual channel protocol. This is analogous to SSH port forwarding (https://help.ubuntu.com/community/SSH/OpenSSH/PortForwarding).

This would be a very useful feature for freerdp. Any chance of someone porting/recreating this functionality?

**Comment by fred922** [comment]
would be great to have this supported in FreeRDP.

**Comment by meanbunny** [comment]
Oh I would love this! I am doing Android development with an emulator running on my host taking advantage of the Intel HAXM. The VM I remote into is a local one setup as a guest in qemu. If I could port forward ports like ssh then I would be golden. Right now I have a putty profile that starts up on login to the machine via FreeRDP

**Comment by ArturZaprzala** [comment]
rdesktop client doesn't have Network Level Authentication, so I was forced to add [rdp2tcp](http://rdp2tcp.sourceforge.net/) support to FreeRDP.

Here is rdp2tcp channel plugin for FreeRDP and a patch for rdp2tcp-0.1 fixing some important bugs:
[freerdp.patch.txt](https://github.com/FreeRDP/FreeRDP/files/58270/freerdp.patch.txt)
[rdp2tcp.patch.txt](https://github.com/FreeRDP/FreeRDP/files/58269/rdp2tcp.patch.txt)

I also created a spec file to cleanly build and install rdp2tcp RPM in Fedora:
[rdp2tcp.spec.txt](https://github.com/FreeRDP/FreeRDP/files/58275/rdp2tcp.spec.txt)

If someone has time and will to integrate this into FreeRDP, feel free to modify my patches as necessary.

## TODO
I named the plugin rdp2tcp, but a more generic name is welcome (net, forward, socket, ...). Currently TCP and SOCKS is implemented, but someone could implement also Unix sockets, UDP, TUN/TAP.

rdp2tcp is run as a separate process on the client side (such a design resulted from license incompatibility between rdesktop and rdp2tcp) and server side. Maybe the client side could be built into FreeRDP plugin.

**Comment by hardening** [comment]
@ArturZaprzala your patches look interesting, anyway doing a pull request would be a better way to hope to have them upstream. Some remarks about the patch:

* it gives the copyright to Marc-André Moreau, not sure that's expected;
* you don't check for ret < 0 et errno == EINTR when read()ing

**Comment by ArturZaprzala** [comment]
I am aware that this patches might not be ready for upstream and making them ready requires some more time, which I don't currently have. I just wanted to share my work early with the community. Surely many people want this feature.

If someone is interested and have the time, please help to improve, clean up and merge the patches upstream.

**Comment by ChaosEternal** [comment]
@ArturZaprzala maybe a brief howto is required. great thanks.

**Comment by ArturZaprzala** [comment]
Here is a source RPM with my latest patch ready to build on Fedora Linux 25:
[freerdp-2.0.0-14.20170217git842a8c5.fc25.src.rpm.zip](https://github.com/FreeRDP/FreeRDP/files/922834/freerdp-2.0.0-14.20170217git842a8c5.fc25.src.rpm.zip)

**Comment by Mirro888** [comment]
@ArturZaprzala - FreeRDP can be compiled nicely with Visual C++. However, the freerdp.patch.txt uses Unix specific stuff like unistd.h, uio.h. Could create a patch that compiles with Visual C++?
Thanks a lot.

**Comment by ArturZaprzala** [comment]
Unfortunately I'm not a Windows developer and can't do that.

Mirro888 wrote:

**Comment by Mirro888** [comment]
@ArturZaprzala - thanks for the prompt response.
Has anyone managed to cross-compile FreeRDP with rdp2tcp patches using mingw for Windows? I've spent days on playing with mingw, but without success. Could you share successfull procedure? Thanks a lot.

**Comment by bmiklautz** [comment]
@Mirro888 We don't "support" (at least we don't test) mingw as FreeRDP compiles natively on Windows.

**Comment by Mirro888** [comment]
@ArturZaprzala - I tried to compile your RPM, but I failed. Could you apply your patch to the latest version of freeRDP and post the patched freeRDP source code? Thank you very much.

**Comment by arch4ngel** [comment]
@ArturZaprzala - I hate to res this thread on you again but I'm failing to build the provided rpm as well. 
 I am likely overlooking something in translation from RPM to compiling from source (admittedly, I'm a C noob).

Feel free to request more information if desired.

Here are a few bullets describing my environment and the observed behavior:
- Compilation is taking place on a Debian based distribution (Linux ***** 4.9.0-kali4-amd64 1 SMP Debian 4.9.30-2kali1 (2017-06-22) x86_64 GNU/Linux)
- All patches apply successfully via ```patch -p[relevant number] < [relevant patch file]```
- Cmake succeeds via ```cmake .```
- Compilation via ```make``` fails at 96%

Here is relevant output from ```make```:
```
.....
Scanning dependencies of target generate_argument_docbook
[ 96%] Building C object client/X11/CMakeFiles/generate_argument_docbook.dir/generate_argument_docbook.c.o
[ 96%] Linking C executable generate_argument_docbook
../common/libfreerdp-client2.so.2.0.0: undefined reference to `rdp2tcp_VirtualChannelEntry'
collect2: error: ld returned 1 exit status
client/X11/CMakeFiles/generate_argument_docbook.dir/build.make:97: recipe for target 'client/X11/generate_argument_docbook' failed
make[2]: *** [client/X11/generate_argument_docbook] Error 1
CMakeFiles/Makefile2:3217: recipe for target 'client/X11/CMakeFiles/generate_argument_docbook.dir/all' failed
make[1]: *** [client/X11/CMakeFiles/generate_argument_docbook.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by hardening** [comment]
I feel like this discussion is totally offtopic for this project

**Comment by arch4ngel** [comment]
I feel the same honestly @hardening but I'm not sure where would be more appropriate since there isn't a repo specifically for the patched version. Should I just create one and give credit to @ArturZaprzala?

**Comment by AnatomicJC** [comment]
@arch4ngel did you manage to build the provided RPM by @ArturZaprzala ? I tried myself and got same error than you at the 96% step.
I tried to build the sb/rdp2tcp from @ArturZaprzala repo without success too :(

**Comment by VVD** [comment]
Must have feature!!!

**Comment by xychix** [comment]
> rdesktop client doesn't have Network Level Authentication, so I was forced to add [rdp2tcp](http://rdp2tcp.sourceforge.net/) support to FreeRDP.
> 
> Here is rdp2tcp channel plugin for FreeRDP and a patch for rdp2tcp-0.1 fixing some important bugs:
> [freerdp.patch.txt](https://github.com/FreeRDP/FreeRDP/files/58270/freerdp.patch.txt)
> [rdp2tcp.patch.txt](https://github.com/FreeRDP/FreeRDP/files/58269/rdp2tcp.patch.txt)
> 
> I also created a spec file to cleanly build and install rdp2tcp RPM in Fedora:
> [rdp2tcp.spec.txt](https://github.com/FreeRDP/FreeRDP/files/58275/rdp2tcp.spec.txt)
> 
> If someone has time and will to integrate this into FreeRDP, feel free to modify my patches as necessary.
> 
> ## TODO
> I named the plugin rdp2tcp, but a more generic name is welcome (net, forward, socket, ...). Currently TCP and SOCKS is implemented, but someone could implement also Unix sockets, UDP, TUN/TAP.
> 
> rdp2tcp is run as a separate process on the client side (such a design resulted from license incompatibility between rdesktop and rdp2tcp) and server side. Maybe the client side could be built into FreeRDP plugin.

does anyone still know the extact freerdp version this was for? Doesn't seem to patch in with 1.1.0-beta-2013071101

**Comment by widgetii** [comment]
@xychix 
https://github.com/AndreRH/FreeRDP works for me

**Comment by ArturZaprzala** [comment]
Here are my latest patches for freerdp-2.0.0-47.rc4.fc29.src.rpm and rdp2tcp-0.1: [rdp2tcp-20181203.zip](https://github.com/FreeRDP/FreeRDP/files/3074908/rdp2tcp-20181203.zip).
FreeRDP patch is using winpr API now.

**Comment by widgetii** [comment]
@ArturZaprzala 

I tried to build FreeRDP rc4 version with your last patch and got error:

```
FAILED: client/X11/xfreerdp 
: && /usr/bin/cc -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -DWINPR_DLL -O3 -DNDEBUG  -rdynamic client/X11/CMakeFiles/xfreerdp-client.dir/xf_gdi.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_gfx.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_rail.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_tsmf.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_input.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_event.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_floatbar.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_channels.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_cliprdr.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_monitor.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_disp.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_graphics.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_keyboard.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_video.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_window.c.o client/X11/CMakeFiles/xfreerdp-client.dir/xf_client.c.o client/X11/CMakeFiles/xfreerdp-client.dir/cli/xfreerdp.c.o  -o client/X11/xfreerdp  -Wl,-rpath,/home/dima/git/FreeRDP/Debug/client/common:/home/dima/git/FreeRDP/Debug/libfreerdp:/home/dima/git/FreeRDP/Debug/winpr/libwinpr: -lX11 -lXinerama -lXext -lXcursor -lXv -lXi -lXrender -lXrandr -lXfixes client/common/libfreerdp-client2.so.2.0.0 libfreerdp/libfreerdp2.so.2.0.0 -lm -lrt winpr/libwinpr/libwinpr2.so.2.0.0 && :
/usr/bin/ld: client/common/libfreerdp-client2.so.2.0.0: undefined reference to `rdp2tcp_VirtualChannelEntryEx'
```

Similar linking error on Mac. With rdp2tcp patch everything is ok

**Comment by shaddybaddah** [comment]
Hi. I find the rdp2tcp feature invaluable. That's why I forked the old code and tried to keep it current. Unfortunately I found it too difficult to port to freerdp2, despite an initial push. I never returned to it. If I can help though, I will. I'm keep to regain this function.

**Comment by widgetii** [comment]
Arthur's patch with help of FreeRDP contributors was merged into master. Please test and give a feedback

**Comment by H8to** [comment]
@widgetii I tested the socks proxy functionality with the nightly build 2.0.0-dev5 (ab2b288f8) which was built from the package freerdp-git from Arch Linux AUR  and can confirm that it works for my quick test cases (requesting sites through the RDP server). Great work. I might come back if any errors occur.

**Comment by VVD** [comment]
How to use "xfreerdp /rdp2tcp:executable path[:arg...]"?
Where I can find description?
Thanks!

**Comment by H8to** [comment]
Please see the readme of the rdp2tcp project. It's well described there. The executable path is the binary that you have to compile from the project. 
After starting the client, there is a server on 5867 or so which you can telnet to. "s 127.0.0.1 4444" opens a socks proxy server e.g.

**Comment by widgetii** [comment]
I've tried to write [simple notes](https://github.com/FreeRDP/FreeRDP/pull/5396#issuecomment-619348467) how to configure it, but I think it would be great if somebody will write clear explanations for new guys in documentation based on your setup experience and troubles you had.

**Comment by VVD** [comment]
Do I need admin privileges on windows server?

**Comment by H8to** [comment]
No :)

**Comment by VVD** [comment]
I can't find binary rdp2tcp after build freerdp. But I see command line option "rdp2tcp" if I run xfreerdp in console.

**Comment by H8to** [comment]
It is a project on its own. This is just the plugin to get it working with xfreerdp. 
See here how to build and src: https://github.com/V-E-O/rdp2tcp
Hope it helps.

**Comment by yoshidaatsushi15** [comment]
@widgetii, @ArturZaprzala 
I've built the rdp2tcp server and client source(https://github.com/V-E-O/rdp2tcp).
And run rdp2tcp.exe on windows server 2019. But I've got the below issue.

**error: WTSVirtualChannelOpen (50: The request is not supported. )**

Can you help me, please? And how can I check that rdp2tcp is working?

**Comment by fluzzi** [comment]
@ArturZaprzala Hi! can you share your last rdp2tcp build? i see you have a branch in github but its different from the one here, what are you using? also have you experienced this issue? https://github.com/V-E-O/rdp2tcp/issues/7
