### ISSUE TITLE
Share remote directory with local environment

### ISSUE THREAD

**Issue by Utini2000** [FreeRDP/FreeRDP#9365]
**Is your feature request related to a problem? Please describe.**
Client: Archlinux with KDE
Server: Windows
I can connect to the RDP server and also share e.g. my local /home/ with it so that I can access those files in my RDP connected Windows environment.
But I would also love to have it the other way due to performance / applications reasons.
E.g. connect to the remote RDP Server and then share one of its folder to my local Linux client. 
From there I could open the folder with e.g. Dolphin and open any files with my locally installed applications which would also then get a performance boost by using my local hardware.

**Describe the solution you'd like**
Add a way to share remote directories to my local machine.
e.g. I connect via RDP to a Windows Server. There is an EXCEL file in folder "Z:/". Instead of opening that EXCEL file in my RDP session, I want to open it on my local machine by accessing that "Z:/" folder like a shared network folder

**Describe alternatives you've considered**
I don't really know of any other alternative.

**Comment by akallabeth** [comment]
not part of the `RDP` protocol. would require client and server support (which will most likely never happen with windows RDP server), so your best option is most likely a network share.
keeping this open if someone has a better idea.

**Comment by Utini2000** [comment]
Well I can share a folder from my local machine to the external RDP server through my RDP connection.
I hoped it would be possible to also do this the other way around..

A network share would be fine as well but I can't do that on an RDP server where I don't have admin access?

**Comment by akallabeth** [comment]
closing, not planned (unless MS decides to add some spec for that)
