### ISSUE TITLE
performance of file copy

### ISSUE THREAD

**Issue by nschneider** [FreeRDP/FreeRDP#937]
* I export my home directory with disk:Home:/Users/norbert
* I see my home on the remote win machine
* I copy a file from windows to my mac, works as expected
* I copy a file from my mac to the win machine. I see a 20-30 sec delay, then the copy works as expected. This happens in about 90% of tries. in ~10% there is no delay. I tested this on different connections to exclude a network problem. The problem was discoverd on a 10 MB DSL connection against a Win7 server in a remote location.

I am using xfreerdp on a 10.7 Mac, but I checked the problem exists with my linux build, too.
Freerdp version is a current git pull as of Jan 2013. The problem exists in my older builds, too, but was only recently detected.

I build a debug version and interupted it during the wait. Here is the stack trace:

(gdb) thread 3
[Switching to thread 3 (Thread 0x2203 of process 32641)]
#0  0x91f37b5e in select$DARWIN_EXTSN$NOCANCEL () from /usr/lib/system/libsystem_kernel.dylib
(gdb) bt
#0  0x91f37b5e in select$DARWIN_EXTSN$NOCANCEL () from /usr/lib/system/libsystem_kernel.dylib
#1  0x91f36af6 in select () from /usr/lib/system/libsystem_kernel.dylib
#2  0x00024168 in freerdp_tcp_wait_write (sockfd=22) at tcp.c:208
#3  0x0006a8ba in tls_wait_write (tls=0x66f510) at tls.c:448
#4  0x000a9a88 in transport_write (transport=0x470a40, s=0x470b00) at transport.c:575
#5  0x000a41bb in rdp_send (rdp=0x470500, s=0x470b00, channel_id=1004) at rdp.c:423
#6  0x000ad4dc in freerdp_channel_send (rdp=0x470500, channel_id=1004, 
    data=0x225f880 "P*\273\032\024\360\232o\324\026M,a!\235\335\365\232\243A\321DfbQ\f\225mT\244ate+\275Hv7\347* \035\356\060\034\024V+\t\030w\366c", <incomplete sequence \363>, size=1048596)
    at channel.c:84
#7  0x000a5335 in rdp_send_channel_data (rdp=0x470500, channel_id=1004, data=0x2201000 "rDCI\001", size=1048596) at rdp.c:938
#8  0x00097567 in freerdp_send_channel_data (instance=0x4703b0, channel_id=1004, data=0x2201000 "rDCI\001", size=1048596) at freerdp.c:188
#9  0x000202cf in freerdp_channels_process_sync (channels=0x892000, instance=0x4703b0) at channels.c:1247
#10 0x00020423 in freerdp_channels_check_fds (channels=0x892000, instance=0x4703b0) at channels.c:1286
#11 0x0001643d in xfreerdp_run (instance=0x4703b0) at xfreerdp.c:1127
#12 0x00016688 in thread_func (param=0x471a50) at xfreerdp.c:1181
#13 0x962d6ed9 in _pthread_start () from /usr/lib/system/libsystem_c.dylib
#14 0x962da6de in thread_start () from /usr/lib/system/libsystem_c.dylib

**Comment by hardening** [comment]
no feedback closing.
@nschneider perhaps you could give a try with latest master
