### ISSUE TITLE
Freerdp2-wayland crashes when scrolling

### ISSUE THREAD

**Issue by karstenes** [FreeRDP/FreeRDP#9384]
**Describe the bug**
When connected to my windows 11 machine from my Artix laptop, when I scroll using either the trackpad or a mouse freerdp immediately crashes. This only happens on wayland mode. xfreerdp does not crash while scrolling. This error happens no matter the command line arguments.

**To Reproduce**
1. Connect to remote machine using `wlfreerdp /u:username /p:password /v:10.66.66.6`
2. Scroll using either the trackpad or mouse

**Expected behavior**
Whatever window is open scrolls and freerdp does not crash.

**Screenshots**

**Application details**
* FreeRDP version 2.11.1
* wlfreerdp /u:username /p:password /v:10.66.66.6
* Build options: [https://gist.github.com/karstenes/e97e546803657b9d193b0bd4f1999713](https://gist.github.com/karstenes/e97e546803657b9d193b0bd4f1999713)
* Connecting to Windows 11 22H2 22621.2283
* Log: [https://gist.github.com/karstenes/2b483c1600eb216e5b39662774837548](https://gist.github.com/karstenes/2b483c1600eb216e5b39662774837548)
* Default arch linux build of freerdp

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Artix Linux, Open-RC
 - Architecture: amd64
 - Kernel: `6.5.2-artix1-1 #1 SMP PREEMPT_DYNAMIC Fri, 08 Sep 2023 13:16:06 +0000 x86_64 GNU/Linux`

**Comment by akallabeth** [comment]
duplicate #9377
