### ISSUE TITLE
FreeRDP Freeze

### ISSUE THREAD

**Issue by Mordecaine** [FreeRDP/FreeRDP#9385]
**Describe the bug**
The application freeze. Kill -9 dont kill the xfreerdp process. A reboot or shutdown of the clien OS is not possible, you have to do a hard reset.

**To Reproduce**
It's hard to reproduce.
1. Start freerdp to connect to azure virtual desktop
``/opt/FreeRDP/freerdp-3.0.0-dev4-Linux-x86_64/bin/xfreerdp /home/user/wvd_files/MSP.rdpw /u:user@domain /sec:nla /cert:ignore +clipboard /gateway:type:arm /network:auto /rfx /gfx:avc444 /dynamic-resolution``
2. After a bit of work in the AVD the sessom freeze. Mostly it freezes if I open the grafana UI with the firefox browser in the login screen.

I now, this are not many information. I tried to debug a bit more (see below).
If someone can give me some hints to create better information to debug, let me know and I will try to reproduce the problem.

**Application details**
* FreeRDP version: 3.0.0-dev4 (a94e14fb2)
* OS version connecting to (server side): Azure virtual Desktop
* Compiler options: cmake -GNinja -DCHANNEL_URBDRC=ON -DWITH_DSP_FFMPEG=ON -DWITH_WEBVIEW_QT=ON

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Fedora 38
 - Architecture: amd64

**Additional context**
I tried to get some information.
As the problem occurs, the debug log was open:
```
[11:47:14:137] [7794:00001e73] [ERROR][com.freerdp.channels.cliprdr.client] - [cliprdr_packet_send]: VirtualChannelWrite failed with CHANNEL_RC_BAD_CHANNEL_HANDLE [00000007]
```
**Process State:**
```
[user@tpluser ~]$ grep Stat /proc/7794/status 
State:	S (sleeping)
```

Now I tried to kill the process but before that, I started a strace on the process and read the process status:
### Normal Kill
**Command:**
```
kill 7794
```

**Strace:**
```
restart_syscall(<... resuming interrupted read ...>) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGTERM {si_signo=SIGTERM, si_code=SI_USER, si_pid=11622, si_uid=1000} ---
getpid()                                = 7794
gettid()                                = 7794
write(2, "[11:49:01:532] [7794:00001e72] ["..., 115) = 115
getpid()                                = 7794
gettid()                                = 7794
write(1, "[11:49:01:535] [7794:00001e72] ["..., 133) = 133
getpid()                                = 7794
gettid()                                = 7794
write(2, "[11:49:01:536] [7794:00001e72] ["..., 128) = 128
write(2, "000B]\n", 6)                  = 6
write(8, "\1\0\0\0\0\0\0\0", 8)         = 8
getpid()                                = 7794
gettid()                                = 7794
write(1, "[11:49:01:536] [7794:00001e72] ["..., 134) = 134
newfstatat(AT_FDCWD, "/tmp/com.freerdp.client.cliprdr.7794", 
```

**Process State:**
```
[user@tpluser ~]$ grep Stat /proc/7794/status 
State:	S (sleeping)
```

### Kill -9
**Command:**
```
kill -9 7794
```

**Strace:**
No further changes

**Process State:**
```
[user@tpluser ~]$ grep Stat /proc/7794/status 
State:	D (disk sleep)
```

**Comment by Mordecaine** [comment]
> indicates your os or hardware are buggy
Normally I would agree. But only freerdp freeze my client. All other programs and the os are working fine.

>  indicates an issue with fuse, so does this also happen with -clipboard?
Well, that's a point. I will test it and give you feedback shortly.

Is there a tool, which helps me to give you more information about this issue?

**Comment by akallabeth** [comment]
@Mordecaine you might try `sdl-freerdp` as an alternative frontend?
 but no, no tool comes to mind except maybe a debugger (`gdb --args /opt/...`)

**Comment by akallabeth** [comment]
@Mordecaine you can also shorten to `/opt/FreeRDP/freerdp-3.0.0-dev4-Linux-x86_64/bin/xfreerdp /home/user/wvd_files/MSP.rdpw /u:user@domain /cert:ignore /gateway:type:arm /dynamic-resolution` (the rest is default)

**Comment by Mordecaine** [comment]
> @Mordecaine you might try `sdl-freerdp` as an alternative frontend? but no, no tool comes to mind except maybe a debugger (`gdb --args /opt/...`)

Yes. To be honest, this was my first choice. The problem here was, that the window from the AVD was too small, and I was not able to change that.
It looks like this:
![sdl-freerdp](https://github.com/FreeRDP/FreeRDP/assets/25454900/19f97a77-a9d5-4bc5-9919-835c3aba4274)

**Comment by Mordecaine** [comment]
> 1. `A reboot or shutdown of the clien OS is not possible, you have to do a hard reset.` indicates your os or hardware are buggy
> 
>     2. `newfstatat(AT_FDCWD, "/tmp/com.freerdp.client.cliprdr.7794", ` indicates an issue with `fuse`, so does this also happen with `-clipboard`?

The problem no longer occurred with ``-clipboard``

But tomorrow I will try to reproduce the problem with the debugger.

**Comment by akallabeth** [comment]
@Mordecaine hmm, the `sdl-freerdp` issue is interesting, have hearded rumors but nobody could provide a full set of details for the connection / system (most - all ? of these were on arch) and I could not reproduce such behaviour on debian nor fedora.
as for the `-clipboard`, I guess then it has to do with `FUSE` filesystem not being properly unmounted for some reason, but `wlfreerdp` is on the deprecation list, so don´t expect too many changes except minor bugfixes. better use `xfreerdp` instead until `sdl-freerdp` is major enough to replace it.

**Comment by Mordecaine** [comment]
Of course. Here is the rdpw file:

```
gatewayusagemethod:i:1
gatewayprofileusagemethod:i:1
authentication level:i:1
gatewaybrokeringtype:i:1
wvd endpoint pool:s:5249e0f7-6c95-44bc-a45a-0d756be8ffe2
geo:s:EU
armpath:s:/subscriptions/********-****-****-****-************/resourcegroups/rg-***-************-mnl01/providers/Microsoft.DesktopVirtualization/hostpools/hsp-***-**-**-mnl01
aadtenantid:s:********-****-****-****-************
full address:s:rdgateway-r1.wvd.microsoft.com
alternate full address:s:rdgateway-r1.wvd.microsoft.com
diagnosticserviceurl:s:https://rdweb-g-eu-r1.wvd.microsoft.com/api/arm/DiagnosticEvents/v1
hubdiscoverygeourl:s:https://rdweb-g-eu-r1.wvd.microsoft.com/api/arm/hubdiscovery?resourceId=5249e0f7-6c95-44bc-a45a-0d756be8ffe2
resourceprovider:s:arm
loadbalanceinfo:s:mth://localhost/5bc287a8-3180-4319-adf1-49e0252c832f/5249e0f7-6c95-44bc-a45a-0d756be8ffe2
workspace id:s:c3478746-bdd7-4bcc-8ed9-79a2a0db0c2f
gatewayhostname:s:afdfp-rdgateway-r1.wvd.microsoft.com:443
activityhint:s:ms-wvd-ep:5249e0f7-6c95-44bc-a45a-0d756be8ffe2?ScaleUnitPath={"Geo"%3a"EU"%2c"Ring"%3a1%2c"Region"%3a"westeurope"%2c"ScaleUnit"%3a100}
promptcredentialonce:i:1
gatewaycredentialssource:i:0
remoteapplicationprogram:s:||2662e847-d15c-4c3e-88ed-08d922ffa0b2
remotedesktopname:s:MSP Desktop P1
remoteapplicationmode:i:0
drivestoredirect:s:*
audiomode:i:2
videoplaybackmode:i:1
redirectclipboard:i:1
redirectprinters:i:1
devicestoredirect:s:*
redirectcomports:i:1
redirectsmartcards:i:1
usbdevicestoredirect:s:*
enablecredsspsupport:i:1
use multimon:i:1
[...]
```
At the end of the file are only the options ``signscope`` and ``signature``. If you need this information, let me know.

**Comment by akallabeth** [comment]
@Mordecaine thank you. no, you can mostly ignore `signscope` and `signature` (that is mostly just a feel good thingy)
