### ISSUE TITLE
freerdp server peer handle custom channel error.

### ISSUE THREAD

**Issue by RyanCode** [FreeRDP/FreeRDP#9391]
I send a msg "Hello server!" from rdp client custom virtual channel to freerdp server,but obviously the server did not process this message correctly.

```c
static BOOL WTSReceiveChannelData(freerdp_peer* client, UINT16 channelId, const BYTE* data,
                                  size_t size, UINT32 flags, size_t totalSize)
{
	UINT32 i;
	BOOL status = FALSE;
	rdpMcs* mcs = client->context->rdp->mcs;

	for (i = 0; i < mcs->channelCount; i++)
	{
		if (mcs->channels[i].ChannelId == channelId)
		{
			rdpPeerChannel* channel = (rdpPeerChannel*)mcs->channels[i].handle;

			if (channel)
				status = WTSProcessChannelData(channel, channelId, data, size, flags, totalSize);
			break;
		}
	}

	return status;
}
```
will return FALSE if this channle if a custom channel.

<img width="1225" alt="image" src="https://github.com/FreeRDP/FreeRDP/assets/61410262/d6901dce-7345-4543-ac40-3a7325571d34">

**Comment by akallabeth** [comment]
@RyanCode this is an issue tracker not an interactive `how to learn programming` tutorial
1. it is fundamental that *YOU* provide enough information about what you´re doing and what you expect (we are no fortune tellers here)
2. [MS-RDPBCGR](https://learn.microsoft.com/en-us/openspecs/windows_protocols/MS-RDPBCGR/5073f4ed-1e93-45e1-b039-6e30c385867c) is what you need to understand

**Comment by RyanCode** [comment]
I do not know what are you taking about.I'am here not for `how to learn programming`.I doubt if you have read my first sentence, I repeat it here,I send a msg "Hello server!" from rdp client custom virtual channel to freerdp server.But the server was immediately shut down.As for the code I posted, what I want to say is that I got channle null here

**Comment by akallabeth** [comment]
well, then tell me what should happen if a client sends random garbage?
