### ISSUE TITLE
Multiple Monitors (only spanning) with Plasma Desktop Manger (Ubuntu 23.04 and Plasma 5.27.4)

### ISSUE THREAD

**Issue by decarlo-cliff** [FreeRDP/FreeRDP#9393]
I recently upgraded to Ubuntu 23.04 and KDE plasma desktop manager 5.27.4 and now the /multimon option in xfreerd is no longer working properly.  When connecting a RDP session, the remote display is now behaving like the /span option was specified as it treats both of my local monitors as one large display instead of two separate displays.  This does however work when using GNOME Flashback (with both Compiz and Metacity), so it seems like it's only an issue when running under plasma.  FYI, I also tried remmina with the multiple monitor option and it behaves exactly the same way (works fine in GNOME Flashback, but spans under Plasma).  I am currently running sddm as my display manager but have tried lightdm and gdm3 and they both behave the same way.  

I have tried to run xfreerdp /monitor-list but that core dumps on my system.

Here are the specific versions of everything I am running:

Ubuntu : 23.04
Kernel : 6.2.0-32-generic #32-Ubuntu SMP PREEMPT_DYNAMIC Mon Aug 14 10:03:50 UTC 2023 x86_64
xfreerdp : 3.0.0-dev4 (79da16244) (I have tried the stable release version as well)
Plasma : 5.27.4
sddm : 0.19.0-3ubuntu3
Nvidia RTX 2070 with driver : 535.86.05-0ubuntu0.23.04.1
AMD Ryzen 7 3700X

Let me know if I can provide any more details.

**Comment by akallabeth** [comment]
@decarlo-cliff sounds like a feature of `kwm` (is that still the name of the plasma window manager?)?
(just a note, `sddm`, `lightdm`, `gdm3` are login managers, they do nothing once the session is started so that they behave the same is kind of expected ;))

there might be a setting regulating this, but I don´t use plasma and not near a machine I´ve installed it on for some days.

**Comment by decarlo-cliff** [comment]
Seems to be something in KDE/Plasma itself.  I have switched window managers that plasma is running on and it still behaves the same way.  I tried bspwm, i3 and xfwm4 none of which altered the spanning behavior or freerdp.  I tried stopping the kscreen service and that did not make any difference either. Other desktop environments seem to work fine (including GNOME, xfce and Cinnamon).  Not sure what else to look at.  I've read that plasma 5.27 had extensive changes specifically to better handle multiple monitor setups.

**Comment by decarlo-cliff** [comment]
Confirmed this is still the behavior in KDE Neon running plasma 6.1.5.

Running /list:monitor does show that it does detect two monitors:

      * [0] 1920x1080	+0+0
        [1] 1920x1080	+1919+0

But the RDP session is only spanning across both monitors and not treating them as two distinct displays.

**Comment by akallabeth** [comment]
@decarlo-cliff `xfreerdp` uses `xinerama` and `xrandr` extensions for multimonitor and does not create a window for each monitor.
I can only assume the implementation in `plasma` with regard to that (old, obscure) feature is broken.
will not change `xfreerdp` anymore as that is quite some work (or better rewrite)
