### ISSUE TITLE
  improve build download process

### ISSUE THREAD

**Issue by 1268** [FreeRDP/FreeRDP#9443]
first I went here:

https://github.com/FreeRDP/FreeRDP/releases/tag/2.11.2

no builds. then I went here:

https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

no builds. then I went here:

https://cloudbase.it/freerdp-for-windows-nightly-builds

and found this:

<https://www.cloudbase.it/downloads/wfreerdp_nightly_build.zip>

but its from 2020. and this:

<https://www.cloudbase.it/downloads/wfreerdp-1.1.zip>

from 2019. I also found this:

https://ci.freerdp.com/job/freerdp-nightly-windows

which is current.

**Comment by hardening** [comment]
I went on prebuilt page and found some builds.

**Comment by hardening** [comment]
Hum I guess it is so complicated to click on links and go to the build page to pick the flavor of the build you want...

**Comment by hardening** [comment]
By rereading 3 times the first report, I'm just figuring that what you may want is a prebuild of stable 2.x version ?

**Comment by 1268** [comment]
it seems the builds are already available here:

https://ci.freerdp.com/job/freerdp-nightly-windows

I think that link just needs to be moved to be the first link under windows heading here:

https://github.com/FreeRDP/FreeRDP/wiki/PreBuilds

and the other link should just be removed:

https://cloudbase.it/freerdp-for-windows-nightly-builds

cause its just old stuff. also why did you close the issue?
