### ISSUE TITLE
I need a simple C memory safe snippet to authenticate to a rdp server, AuthOnly ?

### ISSUE THREAD

**Issue by alom4hdi** [FreeRDP/FreeRDP#9446]

**Comment by alom4hdi** [comment]
@akallabeth not using command line, with C and this library, currently I've written one, but it uses a lot of memory when I use concurrency for it .

**Comment by alom4hdi** [comment]
@akallabeth not using command line, with C and this library, currently I've written one, but it uses a lot of memory when I use concurrency for it .

**Comment by alom4hdi** [comment]
@akallabeth this is my code
```c
#include <stdio.h>
#include <string.h>
#include "rdp.h"
#include <freerdp/freerdp.h>

int rdp_connect(const char* ip, const char* port, const char* username, const char* password) {
    int status = 1;
    freerdp* instance = freerdp_new();
    freerdp_context_new(instance);
    if (instance != NULL) {
        instance->settings->ServerHostname = strdup(ip);
        instance->settings->ServerPort = atoi(port);
        instance->settings->Username = strdup(username);
        instance->settings->Password = strdup(password);
        instance->settings->IgnoreCertificate = TRUE;
        instance->settings->AuthenticationOnly = TRUE;
        if (freerdp_connect(instance) == TRUE) {
            status = 0;
            freerdp_disconnect(instance);
        }
        freerdp_context_free(instance);
        freerdp_free(instance);
    }
    return status;
}
```

**Comment by akallabeth** [comment]
@alom4hdi no, you need at least the whole sample client (you do a full connect with it)

**Comment by alom4hdi** [comment]
@akallabeth how can I just authenticate with it ?

**Comment by akallabeth** [comment]
`sfreerdp /v:hostname /u:username /p:password +auth-only /cert:ignore` does the trick.

**Comment by alom4hdi** [comment]
@akallabeth this uses a lot of memory when I run it from 100 different threads

**Comment by alom4hdi** [comment]
@hardening thanks, can you give me some hints for changing the code ? like where is the main allocations for each freerdp instance and .. ?
