### ISSUE TITLE
freerdp with ffmpeg enabled on F39 makes gnome-connections/remmina etc. display blank screen when used on Hyper-V VM 

### ISSUE THREAD

**Issue by bsmojver** [FreeRDP/FreeRDP#9447]
**Description:**
With latest builds of freerdp for F39 appear to have ffmpeg enabled. When RDP connections are attempted with gnome-connections, remmina or xfreerdp, the screen appears blank. The error messages in the log contain something to the effect of:

- No VA display found for device /dev/dri/renderD128
- Could not initialize hardware decoder, failing back to to software: Invalid argument

Forcing a downgrade to F38 packages makes all of these RDP clients work again.

**Steps to reproduce the behavior:**
1. Install F39 as Hyper-V VM.
2. Open gnome-connections and attempt to connect to another machine via RDP.
3. Blank screen.

**Expected behavior:**
Should work, like it did in F38.

**Screenshots**

**Application details**
* FreeRDP version:  freerdp-2.11.2-1.fc39 
* Command line used
* Output of `xfreerdp /buildconfig`: build logs are here: https://koji.fedoraproject.org/koji/buildinfo?buildID=2297812
* OS version connecting to (server side): Windows Server 2019?

**Environment (please complete the following information):**
 - OS: Fedora Linux 39
 - Version/Distribution: Fedora Linux 39
 - Architecture: x86_64:

**Additional context**
Fedora 39 enabled FFMEG support here: https://src.fedoraproject.org/rpms/freerdp/c/2424f54884289948c8b2cec4e359573b4115d83d

**Downstream bug:**
https://bugzilla.redhat.com/show_bug.cgi?id=2242028

**Comment by akallabeth** [comment]
nothing suspicious with the changes, but you can try forcing a different mode with:

`/gfx` or `/gfx:rfx` and disabling `H264` support on the client (and therefore bypassing any `FFMPEG` usage) and check if you see something then.

**Comment by bsmojver** [comment]
Indeed, both of these options make things appear with xfreerdp. Shouldn't this kind of fallback happen automatically, especially with clients that use the library (e.g. gnome-connections, remmina etc.)?

**Comment by akallabeth** [comment]
@bsmojver fallback on what? sounds like there is an issue with ffmpeg on fedora 39

**Comment by bsmojver** [comment]
Maybe I'm not reading the errors in the log correctly, but given this is Hyper-V guest without hardware GPU, fallback to whatever is alternative to that. Of course, if these errors have nothing to do with the problem, this could all be just a red herring.

**Comment by pnowack** [comment]
FreeRDP with FFMPEG enabled works fine on Archlinux. It might make a difference with what options FFMPEG was compiled on Fedora. @bsmojver Are you sure, FFMPEG was compiled here with AVC support?

**Comment by bsmojver** [comment]
I have no idea, but I'll try to check. Anything that is patented will definitely not be on Fedora.

**Comment by pnowack** [comment]
I've looked through the parts here on the weekend and couldn't spot an issue. Whenever something fails, FreeRDP prints out an error message. You didn't get one here, so the issue is in your FFMPEG build.
The message `Could not initialize hardware decoder, falling back to software: Invalid argument` comes from FreeRDP though. The `Invalid argument` refers to why the hw decoder could not be created (the provided path was invalid). Not an issue, since FreeRDP falls back to software encoding. From then it is the same, as if you built with `WITH_VAAPI=OFF`, which works just fine here.

The difference between Archlinux' build and Fedoras is that Arch uses x264 and Fedora patched their FFMPEG to dlopen openH264. Considering the amount of custom patches, that Fedora applies here (including the dlopen openH264), this looks to be an issue in Fedora. @bsmojver Please open an issue in Fedora against their FFMPEG pkg regarding this.

Some addendum: It doesn't make sense, that Fedora builds FreeRDP with `WITH_VAAPI=ON` btw, because Fedora does not build mesa with AVC decode support (anymore) and also afaik patched that functionality out of their Intel media driver too.

**Comment by bsmojver** [comment]
Thanks @pnowack. I already have a bug opened with Fedora. I'll point them to your comments. And then move the bug to ffmpeg, so that it can be looked at there.

**Comment by bsmojver** [comment]
> I have no idea, but I'll try to check. Anything that is patented will definitely not be on Fedora.

The latest build log for x86_64 is here: https://kojipkgs.fedoraproject.org//packages/ffmpeg/6.0/12.fc39/data/logs/x86_64/build.log

>  ./configure --prefix=/usr --bindir=/usr/bin --datadir=/usr/share/ffmpeg --docdir=/usr/share/doc/ffmpeg --incdir=/usr/include/ffmpeg --libdir=/usr/lib64 --mandir=/usr/share/man --arch=x86_64 '--optflags=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer ' '--extra-ldflags=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes ' --disable-htmlpages --enable-pic --disable-stripping --enable-shared --disable-static --enable-gpl --enable-version3 --enable-libsmbclient --disable-openssl --enable-bzlib --enable-frei0r --enable-chromaprint --enable-gcrypt --enable-gnutls --enable-ladspa --enable-lcms2 --enable-libshaderc --enable-vulkan --disable-cuda-sdk --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libdc1394 --enable-libdrm --enable-libfdk-aac --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libiec61883 --enable-libilbc --enable-libjack --enable-libjxl --enable-libmodplug --enable-libmp3lame --enable-libmysofa --enable-libopenh264-dlopen --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libplacebo --enable-libpulse --enable-librabbitmq --enable-librav1e --enable-librist --enable-librsvg --enable-librubberband --enable-libsnappy --enable-libsvtav1 --enable-libsoxr --enable-libspeex --enable-libssh --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvmaf --enable-libvorbis --enable-libv4l2 --enable-libvpx --enable-libwebp --enable-libxml2 --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lto --enable-libvpl --enable-lv2 --enable-vaapi --enable-vdpau --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libxvid --enable-openal --enable-opencl --enable-opengl --enable-pthreads --enable-vapoursynth --enable-muxers --enable-demuxers --enable-hwaccels --disable-encoders --disable-decoders --disable-decoder=h264,hevc,vc1 --enable-encoder=,a64multi,a64multi5,aac,libfdk_aac,ac3,adpcm_adx,adpcm_argo,adpcm_g722,adpcm_g726,adpcm_g726le,adpcm_ima_alp,adpcm_ima_amv,adpcm_ima_apm,adpcm_ima_qt,adpcm_ima_ssi,adpcm_ima_wav,adpcm_ima_ws,adpcm_ms,adpcm_swf,adpcm_yamaha,alac,alias_pix,amv,anull,apng,ass,asv1,asv2,av1_amf,av1_nvenc,av1_qsv,ayuv,bitpacked,bmp,cinepak,cljr,dca,dfpwm,dnxhd,dpx,dvbsub,dvdsub,dvvideo,exr,ffv1,ffvhuff,flac,flashsv,flashsv2,flv,g723_1,gif,h261,h263,h263_v4l2m2m,h263p,h264_amf,h264_nvenc,h264_qsv,h264_v4l2m2m,h264_vaapi,hap,hdr,hevc_amf,hevc_nvenc,hevc_qsv,hevc_v4l2m2m,hevc_vaapi,huffyuv,ilbc,jpegls,jpeg2000,libaom,libaom_av1,libcodec2,libgsm,libgsm_ms,libilbc,libjxl,libmp3lame,libopencore_amrnb,libopenh264,libopenjpeg,libopus,librav1e,libschroedinger,libspeex,libsvtav1,libtheora,libtwolame,libvo_amrwbenc,libvorbis,libvpx_vp8,libvpx_vp9,libwebp,libwebp_anim,libxvid,mjpeg,mjpeg_qsv,mjpeg_vaapi,mlp,mp2,mp2fixed,mpeg1video,mpeg2video,mpeg2_qsv,mpeg2_vaapi,mpeg4,mpeg4_v4l2m2m,msmpeg4v2,msmpeg4v3,msvideo1,nellymoser,opus,pam,pbm,pcm_alaw,pcm_f32be,pcm_f32le,pcm_f64be,pcm_f64le,pcm_mulaw,pcm_s16be,pcm_s16be_planar,pcm_s16le,pcm_s16le_planar,pcm_s24be,pcm_s24le,pcm_s24le_planar,pcm_s32be,pcm_s32le,pcm_s32le_planar,pcm_s8,pcm_s8_planar,pcm_u16be,pcm_u16le,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,pcm_u8,pcx,pgm,pgmyuv,phm,png,ppm,qoi,qtrle,r10k,r210,ra_144,rawvideo,roq,roq_dpcm,rpza,rv10,rv20,s302m,sbc,sgi,smc,snow,sonic,sonic_ls,speedhq,srt,ssa,subrip,sunrast,svq1,targa,text,tiff,truehd,tta,ttml,utvideo,v210,v308,v408,v410,vc1_qsv,vc1_v4l2m2m,vc2,vnull,vorbis,vp8_qsv,vp8_v4l2m2m,vp8_vaapi,vp9_qsv,vp9_vaapi,wavpack,wbmp,webvtt,wmav1,wmav2,wmv1,wmv2,wrapped_avframe,xbm,xface,xsub,xwd,y41p,yuv4,zlib,zmbv, --enable-decoder=,aac,aasc,libfdk_aac,ac3,acelp_kelvin,adpcm_4xm,adpcm_adx,adpcm_afc,adpcm_agm,adpcm_aica,adpcm_argo,adpcm_ct,adpcm_dtk,adpcm_ea,adpcm_ea_maxis_xa,adpcm_ea_r1,adpcm_ea_r2,adpcm_ea_r3,adpcm_ea_xas,adpcm_g722,adpcm_g726,adpcm_g726le,adpcm_ima_acorn,adpcm_ima_alp,adpcm_ima_amv,adpcm_ima_apc,adpcm_ima_apm,adpcm_ima_cunning,adpcm_ima_dat4,adpcm_ima_dk3,adpcm_ima_dk4,adpcm_ima_ea_eacs,adpcm_ima_ea_sead,adpcm_ima_iss,adpcm_ima_moflex,adpcm_ima_mtf,adpcm_ima_oki,adpcm_ima_qt,adpcm_ima_qt_at,adpcm_ima_rad,adpcm_ima_smjpeg,adpcm_ima_ssi,adpcm_ima_wav,adpcm_ima_ws,adpcm_ms,adpcm_mtaf,adpcm_psx,adpcm_sbpro_2,adpcm_sbpro_3,adpcm_sbpro_4,adpcm_swf,adpcm_thp,adpcm_thp_le,adpcm_vima,adpcm_xa,adpcm_xmd,adpcm_yamaha,adpcm_zork,alac,alias_pix,amrnb,amrwb,amv,anm,ansi,anull,apac,ape,apng,arbc,argo,ass,asv1,asv2,atrac1,atrac3,atrac3al,atrac3p,atrac3pal,aura,aura2,av1,av1_qsv,ayuv,bethsoftvid,bfi,bink,binkaudio_dct,binkaudio_rdft,bintext,bitpacked,bmp,bmv_audio,bmv_video,bonk,brender_pix,c93,cbd2_dpcm,ccaption,cdgraphics,cdtoons,cdxl,cinepak,clearvideo,cljr,cook,cpia,cscd,cyuv,dca,dds,derf_dpcm,dfa,dfpwm,dirac,dnxhd,dolby_e,dpx,dsd_lsbf,dsd_msbf,dsicinaudio,dsicinvideo,dss_sp,dvaudio,dvbsub,dvdsub,dvvideo,dxa,dxtory,eacmv,eamad,eatgq,eatgv,eatqi,eightbps,eightsvx_exp,eightsvx_fib,escape124,escape130,evrc,exr,ffv1,ffvhuff,ffwavesynth,fits,flac,flashsv,flashsv2,flic,flv,fmvc,fourxm,ftr,g723_1,g729,gdv,gem,gif,gremlin_dpcm,gsm,gsm_ms,gsm_ms_at,h261,h263,h263_v4l2m2m,h263i,h263p,hap,hca,hcom,hdr,hnm4_video,hq_hqa,hqx,huffyuv,hymt,iac,idcin,idf,iff_ilbm,ilbc,imc,indeo2,indeo3,indeo4,indeo5,interplay_acm,interplay_dpcm,interplay_video,ipu,jacosub,jpeg2000,jpegls,jv,kgv1,kmvc,lagarith,libaom,libaom_av1,libcodec2,libdav1d,libgsm,libgsm_ms,libilbc,libjxl,libopencore_amrnb,libopencore_amrwb,libopenh264,libopenjpeg,libopus,librsvg,libschroedinger,libspeex,libvorbis,libvpx_vp8,libvpx_vp9,libzvbi_teletext,loco,lscr,m101,mace3,mace6,mdec,media100,metasound,microdvd,mimic,misc4,mjpeg,mjpeg_qsv,mjpegb,mlp,mmvideo,motionpixels,mp1,mp1float,mp2,mp2float,mp3,mp3adu,mp3adufloat,mp3float,mp3on4,mp3on4float,mpc7,mpc8,mpeg1video,mpeg1_v4l2m2m,mpeg2video,mpeg2_qsv,mpeg2_v4l2m2m,mpeg4,mpeg4_v4l2m2m,mpegvideo,mpl2,msa1,mscc,msmpeg4v1,msmpeg4v2,msmpeg4v3,msnsiren,msp2,msrle,mss1,mss2,msvideo1,mszh,mts2,mv30,mvc1,mvc2,mvdv,mvha,mwsc,mxpeg,nellymoser,nuv,on2avc,opus,paf_audio,paf_video,pam,pbm,pcm_alaw,pcm_bluray,pcm_dvd,pcm_f16le,pcm_f24le,pcm_f32be,pcm_f32le,pcm_f64be,pcm_f64le,pcm_lxf,pcm_mulaw,pcm_s16be,pcm_s16be_planar,pcm_s16le,pcm_s16le_planar,pcm_s24be,pcm_s24daud,pcm_s24le,pcm_s24le_planar,pcm_s32be,pcm_s32le,pcm_s32le_planar,pcm_s64be,pcm_s64le,pcm_s8,pcm_s8_planar,pcm_sga,pcm_u16be,pcm_u16le,pcm_u24be,pcm_u24le,pcm_u32be,pcm_u32le,pcm_u8,pcm_vidc,pcx,pfm,pgm,pgmyuv,pgssub,pgx,phm,photocd,pictor,pjs,png,ppm,prosumer,psd,ptx,qcelp,qdm2,qdmc,qdraw,qoi,qpeg,qtrle,r10k,r210,ra_144,ra_288,rasc,rawvideo,realtext,rka,rl2,roq,roq_dpcm,rpza,rscc,rv10,rv20,s302m,sami,sanm,sbc,screenpresso,sdx2_dpcm,sgi,sgirle,shorten,simbiosis_imx,sipr,siren,smackaud,smacker,smc,smvjpeg,snow,sol_dpcm,sonic,sp5x,speedhq,speex,srgc,srt,ssa,stl,subrip,subviewer,subviewer1,sunrast,svq1,svq3,tak,targa,targa_y216,tdsc,text,theora,thp,tiertexseqvideo,tiff,tmv,truehd,truemotion1,truemotion2,truemotion2rt,truespeech,tscc,tscc2,tta,twinvq,txd,ulti,utvideo,v210,v210x,v308,v408,v410,vb,vble,vcr1,vmdaudio,vmdvideo,vmnc,vnull,vorbis,vp3,vp4,vp5,vp6,vp6a,vp6f,vp7,vp8,vp8_qsv,vp8_v4l2m2m,vp9,vp9_qsv,vp9_v4l2m2m,vplayer,vqa,vqc,wady_dpcm,wavarc,wavpack,wbmp,wcmv,webp,webvtt,wmav1,wmav2,wmavoice,wmv1,wmv2,wnv1,wrapped_avframe,ws_snd1,xan_dpcm,xan_wc3,xan_wc4,xbin,xbm,xface,xl,xpm,xsub,xwd,y41p,ylc,yop,yuv4,zero12v,zerocodec,zlib,zmbv,

**Comment by akallabeth** [comment]
if fedora is using `openh264` it might be an option to build freerdp directly against openh264 if there are issues with using ffmpeg as glue.
enabling both, ffmpeg and openh264 will default to use openh264, so that should not be an issue.

**Comment by rathann** [comment]
I don't understand how the code works exactly, but it looks like freerdp is trying to set codec options that are not supported by OpenH264:

[libfreerdp/codec/h264_ffmpeg.c:175](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/codec/h264_ffmpeg.c#L175)
```C
	av_opt_set(sys->codecEncoderContext, "preset", "medium", AV_OPT_SEARCH_CHILDREN);
	av_opt_set(sys->codecEncoderContext, "tune", "zerolatency", AV_OPT_SEARCH_CHILDREN);
```

Compare:
[libavcodec/libopenh264enc.c:62](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libopenh264enc.c#L62)

The return code from `av_opt_set()` is not checked.

Similarly, at [libfreerdp/codec/h264_ffmpeg.c:177](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/codec/h264_ffmpeg.c#L177)
the loop filter is getting enabled via context flag, which seems to be picked up by x264 automatically:
[libavcodec/libx264.c:863](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libx264.c#L863)
but not for openh264, where it needs to be set via an option (although it's on by default):
[libavcodec/libopenh264enc.c:175](https://github.com/FFmpeg/FFmpeg/blob/master/libavcodec/libopenh264enc.c#L175)

So I wonder if `avcodec_open2()` call at [libfreerdp/codec/h264_ffmpeg.c#L180](https://github.com/FreeRDP/FreeRDP/blob/master/libfreerdp/codec/h264_ffmpeg.c#L180C6-L180C19)
is actually succeeding or not.

**Comment by pnowack** [comment]
@rathann The codelines, that you reference here, are unrelated. It might be the case, that `av_opt_set()` needs to be checked for the encoding paths, but changing them won't affect this situation here, as the client decodes the content provided by the server side and not encodes something here.

**Comment by rathann** [comment]
Ah, I missed that this is about the decoder, not encoder. Sorry for the noise, hiding comment.

**Comment by ondrejholy** [comment]
So I did some tests. I can reproduce it against a Windows 10 VM, just I see a slightly different error:

```
[AVHWDeviceContext @ 0x7f4770308a80] Failed to initialise VAAPI connection: -1 (unknown libva error).
[13:03:05:179] [113837:113838] [ERROR][com.freerdp.codec] - Could not initialize hardware decoder, falling back to software: Input/output error
```

The `-WITH_VAAPI=OFF` option causes the errors to be not printed, but the screen is still blank. It is needed to turn off also `-DWITH_FFMPEG=OFF` and `-DWITH_DSP_FFMPEG=OFF` to make it work.

With `-DWITH_OPENH264=ON` it works fine, however,  it is not possible to build against it directly in Fedora. Something like https://github.com/endlessm/noopenh264 would be needed...

So I will have to probably revert https://src.fedoraproject.org/rpms/freerdp/c/2424f54884289948c8b2cec4e359573b4115d83d for now :-( Or any other ideas?

**Comment by akallabeth** [comment]
@ondrejholy sorry, without header we can not build, linking is not required with defining `-DWITH_OPENH264=ON -DWITH_OPENH264_LOADING=ON`
