### ISSUE TITLE
Bug: Glyph out of bounds with Glyph-cache 

### ISSUE THREAD

**Issue by JSSSSSSSSSS** [FreeRDP/FreeRDP#9454]
When connect to win2k8 with Glyph-cache on, the glyph of notepad out of bounds. see:
![42cce045-874d-4f6e-b393-a9dd6e251ed0](https://github.com/FreeRDP/FreeRDP/assets/58905687/5d319fde-a7bd-4fda-81af-377760c710a4)

more information:
**Application details**
* FreeRDP version :2.11.2
* cmdline: xfreerdp /v:xx /u:xxx /p:xxx /bitmap-cache /glyph-cache -fonts
* Output of `xfreerdp /buildconfig`
* OS version connecting to (server side): win2k8 

And I step through the code in libfreerdp/cache/Glyph.c  and found that there is a call of `SetBounds` in `update_process_glyph_fragments`. Also `gdi_SetClipRng` and `gdi_SetNullClipRng` in function `gdi_Glyph_BeginDraw` and `gdi_Glyph_EndDraw` in libfreerdp/gdi/graphics.c. What I want to say is that when deal with **Primary drawing orders** , it already has a bounds field. These clip operations clear the limit of bounds from **Primary drawing orders**.
And I comment these "Redundant clip" calls, it works fine for me.
![image](https://github.com/FreeRDP/FreeRDP/assets/58905687/bd25a744-6c52-4d7e-8fa7-17b59cb6550c)
![image](https://github.com/FreeRDP/FreeRDP/assets/58905687/cfa16521-7bbf-4dc3-ab8f-b4163a34fd79)
![image](https://github.com/FreeRDP/FreeRDP/assets/58905687/f2fa90c2-f52f-4491-9cb1-a1e58009506e)
![image](https://github.com/FreeRDP/FreeRDP/assets/58905687/5aa1a6d1-45c5-4aab-a3a4-8012e6a5e38e)

What is the real problem ?

**Comment by JSSSSSSSSSS** [comment]
One more, when dealing with **Primary drawing orders**-- **GlyphIndex**, in the **VariableBytes** field, the 'USE' also has a delta Bytes.
![image](https://github.com/FreeRDP/FreeRDP/assets/58905687/9b1fa7aa-63a9-4b51-bbe3-1bdd19116b99)

Mssing dealing with delta Bytes in `update_process_glyph_fragments`.
![image](https://github.com/FreeRDP/FreeRDP/assets/58905687/3c097eac-6724-43ac-85c1-6058b862fdd1)

**Comment by akallabeth** [comment]
@JSSSSSSSSSS ok, looks like you already found the fix.
would be great if you could create a pull request ;)

the issue here is that you use a code path that is rarely in use (2k8 already supports at least `rfx`) so there are not too many testers going through this.

**Comment by JSSSSSSSSSS** [comment]
ok, mark
