### ISSUE TITLE
2.11.0 full screen ctrl-alt-delete behavior 

### ISSUE THREAD

**Issue by NespaLa** [FreeRDP/FreeRDP#9460]
OpenSUSE Tumbleweed up to date
xfreerdp 2.11.0 starts session in fullscreen ( based on a ad hoc downloaded rdp generated by a remote Netscaler ).

To escape fullscreen in order to return to the local desktop, ctrl-alt-delete sometimes works, so one can drag the xfreerdp session to the side, or move it to another virtual desktop.

However somethimes the xfreerdp session flashes, and stays fullscreen.   Possibly a part of the window manager crashes or dissapears ( borders round applications are gone ).   Unclear to me there is a problem inside or outside the xfreerdp process.

I wonder is there is a way to send a signal (7) from command line to the xfreerdp process in order to trigger it to go out fullscreen mode.    This would be more convenient and subtle to killing the process.

**Comment by akallabeth** [comment]
how about you use `<ctrl>+<alt>+enter` to deactivate fullscreen?

**Comment by NespaLa** [comment]
> how about you use `<ctrl>+<alt>+enter` to deactivate fullscreen?

yes, the stress of typing a report, ofcourse enter, not delete.
