### ISSUE TITLE
If i want  to send a drag file event to windows ,How can i do it

### ISSUE THREAD

**Issue by qxcoder** [FreeRDP/FreeRDP#9464]
I use the freerdp to make a qt project, when i start the remoteapp and emulation a user behavior as drag a file to the window，i can’t find some message to do it。 I find only a format （CF_HDROP），but don't know how to use it，or if have anything way could be send event like win32 api sendMessage，it also be ok，if you can help ，thanks very mush （My English is not good, please forgive me）

**Comment by akallabeth** [comment]
basically you can´t.

you can listen for local drag & drop and provide a file as clipboard contents, but that is about it.
