### ISSUE TITLE
Image clipboard not working in xfreerdp 3.0.0 beta

### ISSUE THREAD

**Issue by jobs-git** [FreeRDP/FreeRDP#9467]
**Summary**
Copied image is not being pasted to freerdp app. What is not working are the following:
- Copy paste from host browser to freerdp guest app. It just paste a blank box
- Copy paste from host file manager to freerdp guest app. It just paste the URL

**What works?**
When the app is opened from within the KVM, copying image from host browser to guest app works as expected. 

**Reproduction**
For browser (chrome linux):
1. Go to any site with image, say wikipedia
2. Right click copy an image
3. Go to freerdp guest app, say mspaint
4. Right click paste
5. Nothing happens

For file from Nautilus:
1. Select an image from nautilus
2. Right click copy
3. Go to freerdp guest app, say mspaint
4. Right click paste
5. Only address gets copied

[Virtual Machine](https://copr.fedorainfracloud.org/coprs/ligenix/enterprise-qemu-spice/)
```
win10 in KVM w/ spice
```

Guest app
```
mspaint run through kvm
```

xfreerdp -v
```
Clipboard Redirection: +clipboard

Drive Redirection: /drive:home,/home/user
Smartcard Redirection: /smartcard:<device>
Smartcard logon with Kerberos authentication: /smartcard-logon /sec:nla
Serial Port Redirection: /serial:<name>,<device>,[SerCx2|SerCx|Serial],[permissive]
Serial Port Redirection: /serial:COM1,/dev/ttyS0
Parallel Port Redirection: /parallel:<name>,<device>
Printer Redirection: /printer:<device>,<driver>,[default]
TCP redirection: /rdp2tcp:/usr/bin/rdp2tcp

Audio Output Redirection: /sound:sys:oss,dev:1,format:1
Audio Output Redirection: /sound:sys:alsa
Audio Input Redirection: /microphone:sys:oss,dev:1,format:1
Audio Input Redirection: /microphone:sys:alsa

Multimedia Redirection: /video
USB Device Redirection: /usb:id:054c:0268#4669:6e6b,addr:04:0c

```

xfreerdp --version
```
This is FreeRDP version 3.0.0-beta4 (3.0.0-beta4)
```
uname -srm
```
Linux 5.14.0-284.30.1.el9_2.x86_64 x86_64
```

xfreerdp /buildconfig
```This is FreeRDP version 3.0.0-beta4 (3.0.0-beta4)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_JOURNALD_H=TRUE WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=ON WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PKCS11=OFF WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=ON WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=0 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=0 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=0 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WEBVIEW=ON WITH_WEBVIEW_QT=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          RelWithDebInfo
CFLAGS:              -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64-v2 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer -fsanitize=address -fsanitize-address-use-after-scope
Compiler:            GNU, 11.3.1
Target architecture: x64
```

cat /etc/os-release
```
NAME="AlmaLinux"
VERSION="9.2 (Turquoise Kodkod)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="AlmaLinux 9.2 (Turquoise Kodkod)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:9::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-9"
ALMALINUX_MANTISBT_PROJECT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"/a
```

**Comment by pnowack** [comment]
Which RDP server are you using here (MS Windows RDS on Win10/Win11, ogon, g-r-d, xrdp, ...)? Do you mean with "guest" the client side here?

**Comment by jobs-git** [comment]
> Which RDP server are you using here (MS Windows RDS on Win10/Win11, ogon, g-r-d, xrdp, ...)? Do you mean with "guest" the client side here?

updated, tested on ms windows rds on win10

**Comment by akallabeth** [comment]
@jobs-git then a log with `/log-level:debug` or `/log-level:trace` might help here.
I´ve tested this (as mentioned above) and can not reproduce, so it might help to know if there is something in the log indicating what is going on.

**Comment by akallabeth** [comment]
@jobs-git as for the first scenario, works fine here, copy from chromium or firefox to remote mspaint

**Comment by akallabeth** [comment]
@jobs-git also, looks like you already did have similar questions and we´re waiting for feedback there #7270

**Comment by jobs-git** [comment]
this is the /log-level:trace:

```
[21:01:37:839] [13092:00003325] [DEBUG][com.freerdp.core.heartbeat] - [rdp_recv_heartbeat_packet]: received Heartbeat PDU -> period=1, count1=8, count2=8
[21:01:39:449] [13092:00003325] [DEBUG][com.freerdp.core.heartbeat] - [rdp_recv_heartbeat_packet]: received Heartbeat PDU -> period=1, count1=8, count2=8
[21:01:41:449] [13092:00003325] [DEBUG][com.freerdp.core.heartbeat] - [rdp_recv_heartbeat_packet]: received Heartbeat PDU -> period=1, count1=8, count2=8
[21:01:43:465] [13092:00003325] [DEBUG][com.freerdp.core.heartbeat] - [rdp_recv_heartbeat_packet]: received Heartbeat PDU -> period=1, count1=8, count2=8
#heartbeat
[21:01:43:989] [13092:00003325] [DEBUG][com.freerdp.client.common.cliprdr.file] - [cliprdr_file_context_clear]: clear file clipboard...
[21:01:43:989] [13092:00003325] [DEBUG][com.freerdp.client.common.cliprdr.file] - [cliprdr_file_context_clear]: clear file clipboard...
[21:01:43:989] [13092:00003325] [DEBUG][com.freerdp.channels.channels.cliprdr.client] - [cliprdr_client_format_list]: ClientFormatList: numFormats: 2
[21:01:43:989] [13092:00003325] [DEBUG][com.freerdp.channels.cliprdr.client] - [cliprdr_packet_send]: Cliprdr Sending (42 bytes)
[21:01:43:993] [13092:0000336f] [DEBUG][com.freerdp.channels.cliprdr.client] - [cliprdr_order_recv]: msgType: CB_FORMAT_LIST_RESPONSE (3), msgFlags: 1 dataLen: 0
[21:01:43:993] [13092:0000336f] [DEBUG][com.freerdp.channels.channels.cliprdr.client] - [cliprdr_process_format_list_response]: ServerFormatListResponse
#hearbeat
[21:01:44:981] [13092:00003325] [DEBUG][com.freerdp.core.heartbeat] - [rdp_recv_heartbeat_packet]: received Heartbeat PDU -> period=1, count1=8, count2=8
```
I only copied the most relevant, this is right after right click copy image from Linux host browser, the clipboard context is sandwitch in between the heartbeat:
```
[21:01:44:981] [13092:00003325] [DEBUG][com.freerdp.core.heartbeat] - [rdp_recv_heartbeat_packet]: received Heartbeat PDU -> period=1, count1=8, count2=8
```

**Comment by akallabeth** [comment]
@jobs-git seriously? nice that you prefiltered the log, but you managed to eliminate everything slightly interesting to analyze. 

* 90% of the clipboard related messages that are printed during session establishment are missing 
* suggest using `/log-level:trace` as `xfreerdp` only then prints details about `Atom` events

**Comment by pnowack** [comment]
According to that log, there is no copy action happening (e.g. CTRL+C not pressed on either side or via some context menu -> copy (or other way to copy something to the clipboard)). The only format list that is sent here is the initial obligatory one, that is part of the CLIPRDR initialization sequence. But actual clipboard interaction is not happening, otherwise we would see that in the log here.

**Comment by jobs-git** [comment]
exactly, tnx for explaining why I cant paste the image. The clipboard interaction is not happening, now not sure what is causing this

**Comment by akallabeth** [comment]
@jobs-git well, thank you for the update.
but you still did not run with `/log-level:trace` which would include some details about `X11 atom` events

**Comment by jobs-git** [comment]
@akallabeth here is the trace log
[trace.zip](https://github.com/FreeRDP/FreeRDP/files/13047008/trace.zip)

**Comment by akallabeth** [comment]
@jobs-git thanks. can´t find any clipboard related events there though, which is really unexpected.
so, only option left is testing with a build with `-DWITH_DEBUG_X11=ON` which dumps every `X11 event` that happens.
if then there is still nothing I don´t know if we can help :/

**Comment by jobs-git** [comment]
Here is it with `-DWITH_DEBUG_X11=ON`, note that if the app is not launched via freerdp, aka, opened inside the KVM, the copy-paste function works as expected:

both `/log-level:debug` and `/log-level:trace` outputs:
[debug_trace.log.zip](https://github.com/FreeRDP/FreeRDP/files/13060383/debug_trace.log.zip)

**Comment by akallabeth** [comment]
@jobs-git see only 2 events, and one time the number of formats is `0` the other time `2` (check for `cliprdr_client_format_list`) and no `XGetWindowProperty` events matching anything clipboard related.
can you check what is actually in the clipboard with `xclip -o -t TARGETS -selection clipboard` to be sure there is image data available

I´ll do a test run on my systems tomorrow, don´t have time now, but it looks like there is not data in clipboard (or no supported format)
only thing I can tell is that on my systems  (debian 12 and fedora 38 as well as various ubuntu vm) this works and I get a lot more clipboard related events from `X11`

**Comment by jobs-git** [comment]
here is the result of `xclip -o -t TARGETS -selection clipboard`
```
TIMESTAMP
TARGETS
SAVE_TARGETS
MULTIPLE
image/png
text/html
text/x-moz-url
```

**Comment by akallabeth** [comment]
@jobs-git ok, that might explain it.
in your case only `image/png` is announced which we do not directly map (as windows clipboard uses `image/bmp` or `image/tiff` for most stuff)

If I copy an image in firefox I have the following:
```
08:45 $ xclip -o -t TARGETS -selection clipboard
TIMESTAMP
TARGETS
MULTIPLE
SAVE_TARGETS
image/png
image/jpeg
image/bmp
image/x-bmp
image/x-MS-bmp
image/x-icon
image/x-ico
image/x-win-bitmap
image/vnd.microsoft.icon
application/ico
image/ico
image/icon
text/ico
image/tiff
image/webp
audio/x-riff
```

**Comment by akallabeth** [comment]
also, if I select some `HTML` and copy it:
```
xclip -o -t TARGETS -selection clipboard
TIMESTAMP
TARGETS
MULTIPLE
SAVE_TARGETS
text/html
text/_moz_htmlcontext
text/_moz_htmlinfo
UTF8_STRING
COMPOUND_TEXT
TEXT
STRING
text/plain;charset=utf-8
text/plain
text/x-moz-url-priv
```

**Comment by akallabeth** [comment]
@jobs-git fyi, same is true for `chromium`

**Comment by jobs-git** [comment]
What is the resolution? How do we fix it?

**Comment by akallabeth** [comment]
no, idea, check with your distro.

**Comment by jobs-git** [comment]
Should png be implemented before closing?

**Comment by akallabeth** [comment]
@jobs-git have fun patching windows ;)
aka, you can add a new format, but all client applications where you want to paste need to support it.
(there is also png mapping, but `bmp` is always required, if not then no image is announced)

**Comment by AkechiShiro** [comment]
@akallabeth Trying to understand a potential way to fix/workaround, the mapping for `image/bmp` and `image/tiff` must be done by configuring the X11 server's clipboard or would we need to add those formats to `xclip` and patch it in order to have it supported ? I'm sorry if this question makes no sense, I am not familiar with X11 internals, I will try and dig up some documentation on the clipboard.

**Comment by akallabeth** [comment]
@AkechiShiro what is there to fix?
just use `FreeRDP` 3.x and it will work (assuming you have a version that has support for these formats compiled in)

you can´t change how to transfer the image, but you can convert later on - which happens.

**Comment by AkechiShiro** [comment]
You are correct there is nothing to fix, I've seen that there are even tests for the clipboard for copying images and I saw code that does the conversions handling, regarding the formats compiled in, would you know which flags ?

I've tried looking in the changelog but only found this : 
> * FUSE for file clipboard support (linux/mac os, disable with -DWITH_FUSE=OFF)  

This flag may also be important : 
> WINPR_WITH_PNG
