### ISSUE TITLE
bad screen

### ISSUE THREAD

**Issue by zhaokaixs** [FreeRDP/FreeRDP#9469]
Branch:Master or Release
IDE:VS2019
RemoteServer:WindowsServer2022 
Commondline: wfreerdp.exe /v:ip /u:username /p:passworld
![image](https://github.com/FreeRDP/FreeRDP/assets/7833585/b52ae25f-d260-4005-9458-900052f560e1)

**Comment by akallabeth** [comment]
@zhaokaixs did you compile yourself? `buildconfig` would be interesting, as I can´t reproduce with nightly.

**Comment by zhaokaixs** [comment]
> @zhaokaixs 你自己整理好了吗?`buildconfig` 会很有趣的,因为我无法用每晚的时间繁殖。 [编辑]仔细查看您构建的H264解码器,这看起来似乎是来自`AVC` 方式

Thankyou Sir, i add args: /gfx 
The screen is normal
![image](https://github.com/FreeRDP/FreeRDP/assets/7833585/b7b8d8ab-000b-4439-a339-97a99bd7f978)

**Comment by akallabeth** [comment]
@zhaokaixs so, which `H264` decoder did you compile in? that would be helpful to find the issue ;)

**Comment by zhaokaixs** [comment]
> @zhaokaixs so, which `H264` decoder did you compile in? that would be helpful to find the issue ;)

i test WITH_OPENH264 and Default MF decoder,
With the parameter /gfx added, the final result is the same

**Comment by akallabeth** [comment]
@zhaokaixs ah, so you did enable `WITH_MEDIA_FOUNDATION`? That is not default, it is `OFF` by default ;)
I´d keep it disabled as that might be the reason why it failed.

**Comment by zhaokaixs** [comment]
> @zhaokaixs ah, so you did enable `WITH_MEDIA_FOUNDATION`? That is not default, it is `OFF` by default ;) I´d keep it disabled as that might be the reason why it failed.
![image](https://github.com/FreeRDP/FreeRDP/assets/7833585/fbeb2908-7715-4614-9922-58a0e40dd4f9)


I found that it is turned on by default
Is there any way to make the picture normal without using /gfx?
