### ISSUE TITLE
 Is it possible not to transfer video

### ISSUE THREAD

**Issue by zhaokaixs** [FreeRDP/FreeRDP#9477]
Releated pull request for master: 
My project only hopes to use freerdp to open an RDP session, but does not need to capture and transmit desktop video, because I have a streaming program myself.

**Comment by akallabeth** [comment]
sorry, but what?
the description is a bit vague so could you try with a little more detail what exactly you mean?

**Comment by zhaokaixs** [comment]
> sorry, but what?
> the description is a bit vague so could you try with a little more detail what exactly you mean?

On a Windows Server 2022, I create two RDP(Remote Desktop Protocol) users accounts. When I log on server with the two accounts, I can get two seperate desktops. But I don't want to use the complete RDP protocol, I use my own capture and streaming function to stream remote desktop to the browser(webrtc). So I want to stop RDP client display to reduce resource utilization, how can I get it?

**Comment by bmiklautz** [comment]
@zhaokaixs if I understood correctly you want to use RDP to start a session on the remote server but then not use RDP to receive graphics data but your own protocol instead.

You can try creating your own client (use the sample client as starting point) that just does the connection setup and then sends a "suppress output pdu" (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/0be71491-0b01-402c-947d-080706ccf91b) - that won't disable the whole RDP protocol but at least the server shouldn't sent any graphics data.

**Comment by zhaokaixs** [comment]
> @zhaokaixs if I understood correctly you want to use RDP to start a session on the remote server but then not use RDP to receive graphics data but your own protocol instead.
> 
> You can try creating your own client (use the sample client as starting point) that just does the connection setup and then sends a "suppress output pdu" (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/0be71491-0b01-402c-947d-080706ccf91b) - that won't disable the whole RDP protocol but at least the server shouldn't sent any graphics data.

Yes sir, that was indeed my idea, not to receive the video to reduce the network and CPU usage of the server.

**Comment by zhaokaixs** [comment]
> @zhaokaixs如果我理解正确的话，您想使用 RDP 在远程服务器上启动会话，但不使用 RDP 接收图形数据，而是使用您自己的协议。
> 
> 您可以尝试创建自己的客户端（使用示例客户端作为起点），该客户端仅执行连接设置，然后发送“抑制输出 pdu”（[https://learn.microsoft.com/en-us/openspecs/windows_protocols/ ms-rdpbcgr/0be71491-0b01-402c-947d-080706ccf91b](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/0be71491-0b01-402c-947d-080706ccf91b) ) - 这不会禁用整个 RDP 协议，但至少服务器不应发送任何图形数据。

I found this function gdi_send_suppress_output, but I don't know where it should be called, is it after the freerdp_connect function succeeds?

**Comment by akallabeth** [comment]
that one requires support server side and might put the remote on hold (depending on settings)
but yes, after `freerdp_connect` you can use it (it is used by `xfreerdp` when e.g. minimized)

**Comment by zhaokaixs** [comment]
> that one requires support server side and might put the remote on hold (depending on settings) but yes, after `freerdp_connect` you can use it (it is used by `xfreerdp` when e.g. minimized)

The window doesn't update anymore, but the network bandwidth is still occupied, I suspect that the RDP service is still sending data
![image](https://github.com/FreeRDP/FreeRDP/assets/7833585/0a014a1c-0af4-48e5-a723-b29c293f942e)
![Uploading image.png…]()

**Comment by yaowangvrviu** [comment]
@zhaokaixs Have you implemented this idea?

**Comment by zhaokaixs** [comment]
no,server video always send&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, May 27, 2024 18:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [FreeRDP/FreeRDP]  Is it possible not to transfer video (Issue#9477)




 
@zhaokaixs Have you implemented this idea?

**Comment by yaowangvrviu** [comment]
So it's only save freerdp client decoding and rendering cost. 
RDP server part always capturing, encoding and sending. 
I have tried:
1. -bpp 2/4/8, not work, wfreeRdp.exe unable to launch.
2. -size WxH, this can reduce some resouce, But it's not very obvious.

And will try:
1. minimize wfreeRDP.exe window.
2. set frameRate = 1, I see frameRate value in source code, but it is not a configuration.

**Comment by zhaokaixs** [comment]
I am doing screen recording. If I minimize, it will cause the server desktop to go blackscreen



---Original---
From: ***@***.***&gt;
Date: Mon, May 27, 2024 22:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [FreeRDP/FreeRDP]  Is it possible not to transfer video (Issue#9477)




 
@zhaokaixs
 So it's only save freerdp client decoding and rendering cost.
 RDP server part always capturing, encoding and sending.
 I have tried:
  
-bpp 2/4/8, not work, wfreeRdp.exe unable to launch.
 
-size WxH, this can reduce some resouce, But it's not very obvious.
  
And will try:
  
minimize wfreeRDP.exe window.
 
set frameRate = 1, I see frameRate value in source code, but it is not a configuration.
