### ISSUE TITLE
smartcard_unpack_locate_cards_a_call possible with an error

### ISSUE THREAD

**Issue by AndreyBarmaley** [FreeRDP/FreeRDP#9480]
Hi, about `smartcard_unpack_locate_cards_a_call` and `smartcard_unpack_locate_cards_w_call` - I think you missed the `smartcard_unpack_redir_scard_context_ref` call. Maybe I was wrong?
```
LONG smartcard_unpack_locate_cards_a_call(wStream* s, LocateCardsA_Call* call)
{
        LONG status;
        UINT32 sz1NdrPtr, sz2NdrPtr;
        UINT32 index = 0;
        status = smartcard_unpack_redir_scard_context(s, &(call->handles.hContext), &index);
        if (status != SCARD_S_SUCCESS)
                return status;
        
        if (!Stream_CheckAndLogRequiredLength(TAG, s, 16))
                return STATUS_BUFFER_TOO_SMALL;
                
        Stream_Read_UINT32(s, call->cBytes);
        if (!smartcard_ndr_pointer_read(s, &index, &sz1NdrPtr))
                return ERROR_INVALID_DATA;
        
        Stream_Read_UINT32(s, call->cReaders);
        if (!smartcard_ndr_pointer_read(s, &index, &sz2NdrPtr))
                return ERROR_INVALID_DATA;

        // <<<

        if (sz1NdrPtr)
        {
                status =
                    smartcard_ndr_read_fixed_string_a(s, &call->mszCards, call->cBytes, NDR_PTR_SIMPLE);
                if (status != SCARD_S_SUCCESS)
                        return status;
        }
        if (sz2NdrPtr)
        {
                status = smartcard_unpack_reader_state_a(s, &call->rgReaderStates, call->cReaders, &index);
                if (status != SCARD_S_SUCCESS)
                        return status;
        }
        smartcard_trace_locate_cards_a_call(call);
        return SCARD_S_SUCCESS;
}
```

**Comment by akallabeth** [comment]
@AndreyBarmaley what makes you think that?  [\[MS-RDPESC\] 2.2.2.9 LocateCardsA_Call](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpesc/c6b49a98-99e6-43c0-af63-56e4918814f3) does not tell there is one.

**Comment by AndreyBarmaley** [comment]
@akallabeth
I compared with the `smartcard_unpack_locate_cards_by_atr_a_call`. Аnd it uses `smartcard_unpack_redir_scard_context` + `smartcard_unpack_redir_scard_context_ref`

**Comment by akallabeth** [comment]
@AndreyBarmaley ok, you have a point.
looking through the history there were problems with that call.
do you have a failing test case or was this just review?

**Comment by akallabeth** [comment]
@AndreyBarmaley created a branch fixing this here: https://github.com/akallabeth/FreeRDP/tree/smartcard_context
but first need to know if that is actually a thing (e.g. not a protocol bug but one in FreeRDP)

**Comment by AndreyBarmaley** [comment]
@akallabeth  I don't have a test case, just review only.

**Comment by akallabeth** [comment]
ok, then I´ll need to get my hands on the test devices to check this first. (smartcard is really nasty as the documentation is spread over a lot of places and sometimes not quite precise)
