### ISSUE TITLE
xfreerdp lag when i play video on full HD monitor

### ISSUE THREAD

**Issue by linuxpayeh** [FreeRDP/FreeRDP#9484]
Hi!
I have a problem with xfreerdp on hp t620 client with fedora OS. When I play a video on remote windows server, xfreerdp has bad performance and consumes much CPU. I try several parameters as gfx,rfx,gdi and etc but the results are not acceptable. I test this scenario on windows 10  and remote desktop client has good performance . In windows task manager I see remote desktop client  utilize thin client gpu. I work on fedora OS installed on this client and installed vaapi  and another linux video acceleration packages as described on this link:
https://wiki.archlinux.org/title/Hardware_video_acceleration
 and test full HD video playback using mpv  on the thin client as follows:
mpv --hwdec=auto video.mp4
When mpv starts in terminal,  prints "Using hardware decoding (vaapi)." and GPU is utilized. in this situation little CPU resources will be consumed by mpv and the result was very good without any lag.
I also compiled freerdp 3.0.0-beta4 and turn on  vaapi and another graphical flags.  but there is not any improvement.
I added some comment in freerdp code and sure that VAAPI is enabled.
Have you any recommendation to solve this problem?
How to play full HD video on a remote windows server using xfreerdp and fedora client?
Is there any solution which force xfreerdp use GPU instead CPU and use GPU encoding and decoding?

**Comment by akallabeth** [comment]
@linuxpayeh which version do you use? the one bundled with fedora hast most likely h264 disabled.
as for options, don´t use any. default is autodetection which usually uses AVC444 (h264 based) with bandwidth measurement (server adjusts quality depending on lag/bandwidth)

also, as I assume you run wayland it might help using `sdl-freerdp` instead (that one can fully run wayland and draw using vulkan if SDL is compiled right - which it is for fedora)

**Comment by akallabeth** [comment]
closing as this is a question and not an issue.
