### ISSUE TITLE
National chars mangled after reconnected session

### ISSUE THREAD

**Issue by lejeczek** [FreeRDP/FreeRDP#9488]
**Describe the bug**
Hi guys.

With PL keyboard with British layout and the same on a remote Ubuntu - when I first log in then I get national chards as expected, but after a disconnection (not a logout) every subsequent session/connection has national chars mangled/gone haywire.
Then in such "mangled" connection I logout on the remote Ubuntu, (re)login a new session and all is (back to) normal.
Reproduces every time. Perhaps other languages too.

**Application details**
freerdp-2.11.2-1.fc38.x86_64
xrdp           0.9.17-2ubuntu2 amd64

**Environment (please complete the following information):**
 - client Fedora
 - server Ubuntu

**Comment by akallabeth** [comment]
sounds more like an issue of `xrdp`?
if what I got is correct (e.g. you connect with `xfreerdp` ) and that terminates and you connect again?
or are you talking about e.g. loss of network and auto-reconnect kicking in?

**Comment by lejeczek** [comment]
Yes, disconnect in orderly fashion but, I'd presume being disconnect due to broken network would be the same valid case.
In think it would be right to generalize: **disconnect**(chars mangled) VS **log out&in**(chars a ok).

**Comment by akallabeth** [comment]
@lejeczek well, yes and no.
reconnect does reset a lot of stuff within freerdp that might break.
a orderly disconnect with program termination on the other hand guarantees that at next connect the exact same settings apply for connection establishment (given same command line/rdp file)

so, what is relevant here:
* `FreeRDP` (or any `RDP` client in that case) does send a keyboard layout to the server initially. (that might be respected or ignored by the server)
* `FreeRDP` does reverse map key symbols to `scancodes` (this is entirely in the client, no interaction with the server happens for that)
* These `scancodes` are sent to the server
* The server then applies the keyboard layout set there (might be the one you sent or an entirely different one)

so, an easy way to test this would be to use a different (not `FreeRDP` based) client for connection and try this disconnect situation. (`mstsc` if possible, that is not based on `FreeRDP` and does normally use `scancode` input too, as there is another method mostly used by mobile clients, the `unicode` input)

**Comment by lejeczek** [comment]
I'll try, though I have no Windows access.
Side note - c&p: fedora->ubuntu works / fedora<-ubuntu does not

**Comment by akallabeth** [comment]
so closing as 'nothing we can fix on our end'
