### ISSUE TITLE
aFreeRDP keyboard not sending punctuation to the server

### ISSUE THREAD

**Issue by gatesphere** [FreeRDP/FreeRDP#950]
aFreeRDP will not send the following keys (perhaps others too) to the server it is connected to: 

```
 . , ! ? ' " - _ / @ # $ % & * + = ( ) < > = : ;
```

Keyboards tested: stock Android keyboard English (US), and Hacker's Keyboard.

**Comment by glitchphan** [comment]
I think this affects more than just Android version. Also, someone duped this issue in #1568.

**Comment by akallabeth** [comment]
I this still an issue with current master?

**Comment by glitchphan** [comment]
I do not have a build environment but if someone were to build it for iOS or Android, I could certainly test. The one in iOS App Store is from 2013 and the one in the Play Store is from 2014.

**Comment by lewkowski** [comment]
I have the same issue as Gatesphere (although it does transmit the @#$%&*! characters). I have tried TruRdp and have the same issue, but from Windows 10 using stock Remote Desktop Connection all characters work. For the RDP host I am using Ubuntu 16.04 (Mate) with xrdp for the server. Any help much appreciated.

**Comment by akallabeth** [comment]
@lewkowski Currently the android client sends keyboard events as unicode symbols. To my knowledge XRDP and others do not support that kind of input. I can't tell for TruRdp.

**Comment by hymer-up** [comment]
Last AfreeRDP tested on multi android devices. Keyboard unusable because punctuation and keymaps other than US layout on a debian server not correctly detected.

**Comment by akallabeth** [comment]
@hymer-up Using XRDP? Then that one is at fault. Android has no (reliable) way to use scancodes as input, only unicode. that is not supported in that case.
