### ISSUE TITLE
Enable clipboard support for image/png

### ISSUE THREAD

**Issue by jobs-git** [FreeRDP/FreeRDP#9504]
As the title says. This is because image copied may posses alpha channels. By default, copying an image w/ transparent background from Host results to pasted image in remote app w/ black background which is incorrect. For details, see: https://github.com/FreeRDP/FreeRDP/issues/9467

**Comment by akallabeth** [comment]
Please read what I have written in https://github.com/FreeRDP/FreeRDP/issues/9467 and stop creating new issues for answered questions.
