### ISSUE TITLE
static build configure

### ISSUE THREAD

**Issue by zhaokaixs** [FreeRDP/FreeRDP#9514]
Releated pull request for master: 
How to configure cmake so that when compiling static build, the Channels lib is linked to freerdp-client.lib, so that when developing your own client, only freerdp2.lib and freerdp-client2.lib are linked.
 
![image](https://github.com/FreeRDP/FreeRDP/assets/7833585/feabed8a-0792-43bf-aa11-05dd235bd824)

**Comment by akallabeth** [comment]
check the ci scripts, specifically `ci/cmake-preloads/config-windows.txt` which builds fully static binaries.
