### ISSUE TITLE
Android Error : Failed to create h264 codec context

### ISSUE THREAD

**Issue by codebreaker** [FreeRDP/FreeRDP#9526]
**Describe the bug**
 - I have built the binary .so files required for Android following the steps given in the readme.
 - I am using the .so files with the modified version of FreeRDP(an older version) android app for obvious reasons.
 - I have updated the LibFreeRDP.java with recent changes.
 - while the app runs successfully on Android version 11 and above (Checked versions Android 6, 11, 13), I notice it gives following error when I try connect to a remote desktop on Android 6.

`GetProcAddress: could not find procedure AMediaCodec_setParameters: undefined symbol: AMediaCodec_setParameters
Error resolving function AMediaCodec_setParameters f
Failed to create h264 codec context`

**To Reproduce**
1. Open the Connection Information
2. Enter connection details (IP address, username, password)
3. Disconnected, Reconnecting.
4. See error log
`GetProcAddress: could not find procedure AMediaCodec_setParameters: undefined symbol: AMediaCodec_setParameters
Error resolving function AMediaCodec_setParameters f
Failed to create h264 codec context`

**Expected behavior**
Should connect to remote desktop on Android 6 just like how it does for Android 11 and above.

**Screenshots**

**Application details**
* FreeRDP version 2.11.2 (Android)
* Windows Server - Windows 10

**Environment (please complete the following information):**
 - OS: Android
 - Version/Distribution: Android 6
 - Architecture: ARM

**Additional context**
Application is based on older version of freeRDP android app, not sure which version it is based on.

**Comment by akallabeth** [comment]
> I am using the .so files with the modified version of FreeRDP(an older version) android app for obvious reasons.
which reasons are these? (not that obvious ;))

> `GetProcAddress: could not find procedure AMediaCodec_setParameters: undefined symbol: AMediaCodec_setParameters Error resolving function AMediaCodec_setParameters f Failed to create h264 codec context`
so you run on an outdated android version (below the minimum API for mediacodec it is compiled for) and expect the API of the newer one to be there? good luck with that assumption ;)

I´d add `-DWITH_MEDIACODEC=OFF` (disables hardware H264 support) and fixes your issue
