### ISSUE TITLE
2.10.2 Failed to compile cmake

### ISSUE THREAD

**Issue by tangjpA1** [FreeRDP/FreeRDP#9527]
cmake .. -DWITH_CPUS=OFF -DWITH_FFMPEG=OFF -DWITH_X11=OFF -DWITH_ALSA=OFF -DWITH_XKBFILE=OFF -DWITH_XSHM=OFF -DWITH_XRENDER=OFF -DWITH_XFIXES=OFF -DWITH_XEET=OFF -DWITH_FASTPATH_UPDATE=OFF -DWITH_SSL_INIT=ON -DCHANNEL_CLIPRDR=ON -DCHANNEL_DRDYNVC=OFF -DCHANNEL_SERIAL=OFF -DCHANNEL_RDPSND=ON -DCHANNEL_RDPDR=ON -DCHANNEL_RALL=OFF -DWITH_SERVER=ON -DWITH_SJADOW=OFF -DWITH_CLIENT=OFF -DWITH_SAMPLE=OFF -DWITH_DEBUG=ON -DWITH_DEBUG_RDP=ON -DCHANNEL_DRIVE=OFF -DCHANNEL_DISP=OFF -DCHANNEL_URBDRC=OFF -DCHANNEL_DRIVE=OFF -DCHANNEL_DISP=OFF -DCHANNEL_URBDRC=OFF -DCHANNEL_RDPGFX=OFF -DCHANNEL_SMARTCARD=OFF -DCHANNEL_ECHO=OFF -DCHANNEL_ENCOMSP=OFF -DCHANNEL_PARALLEL=OFF -DCHANNEL_RDP2TCP=OFF -DCHANNEL_RDPEI=OFF -DCHANNEL_ERMDESK=OFF -DCHANNEL_VIDEO=OFF -DCHANNEL_GEOMETRY=OFF -DCHANNEL_VIDEO=OFF -DCHANNEL_GEOMETRY=OFF -DCHANNEL_RDPDR_SERVER=OFF -DCHANNEL_AUDIN=OFF -DCHANNEL_AINPUT=OFF -DCHANNEL_AUDIN=OFF -DCHANNEL_AINPUT=OFF -DWITH_MANPAGES=OFF -DWITH_PAM=OFF -DWITH_OSS=OFF -DWITH_PROXY=OFF -DWITH_SSE2=OFF -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF

[ 38%] Built target winpr
[ 39%] Built target winpr-tools
[ 39%] Built target winpr-makecert
[ 40%] Built target winpr-hash
[ 75%] Built target freerdp
[ 77%] Built target rdtk
[ 83%] Built target uwac
[ 83%] Built target remdesk-client
[ 84%] Built target remdesk-server
[ 85%] Built target rdpsnd-client
[ 85%] Built target rdpsnd-client-pulse
[ 86%] Built target rdpsnd-client-proxy
[ 86%] Built target rdpsnd-client-fake
[ 87%] Built target rdpsnd-server
[ 88%] Built target rdpdr-client
[ 88%] Built target rdpdr-server
[ 89%] Built target rail-client
[ 90%] Built target rail-server
[ 91%] Built target printer-client
[ 91%] Built target printer-client-cups
[ 91%] Built target cliprdr-client
[ 92%] Built target cliprdr-server
[ 93%] Built target freerdp-channels-server
[ 94%] Built target freerdp-client
[ 95%] Built target freerdp-server
[ 99%] Built target freerdp-shadow
[ 99%] Built target freerdp-shadow-subsystem
[100%] Linking C executable freerdp-shadow-cli
/usr/bin/ld: libfreerdp-shadow2.a(shadow_encomsp.c.o): in function `shadow_client_encomsp_init':
shadow_encomsp.c:(.text+0x1a8): undefined reference to `encomsp_server_context_new'
/usr/bin/ld: libfreerdp-shadow2.a(shadow_encomsp.c.o): in function `shadow_client_encomsp_uninit':
shadow_encomsp.c:(.text+0x20a): undefined reference to `encomsp_server_context_free'
/usr/bin/ld: libfreerdp-shadow2.a(shadow_audin.c.o): in function `shadow_client_audin_init':
shadow_audin.c:(.text+0x2bc): undefined reference to `audin_server_context_new'
/usr/bin/ld: shadow_audin.c:(.text+0x35a): undefined reference to `audin_server_context_free'
/usr/bin/ld: libfreerdp-shadow2.a(shadow_audin.c.o): in function `shadow_client_audin_uninit':
shadow_audin.c:(.text+0x41d): undefined reference to `audin_server_context_free'
/usr/bin/ld: libfreerdp-shadow2.a(shadow_rdpgfx.c.o): in function `shadow_client_rdpgfx_init':
shadow_rdpgfx.c:(.text+0x18): undefined reference to `rdpgfx_server_context_new'
/usr/bin/ld: libfreerdp-shadow2.a(shadow_rdpgfx.c.o): in function `shadow_client_rdpgfx_uninit':
shadow_rdpgfx.c:(.text+0x6d): undefined reference to `rdpgfx_server_context_free'
collect2: error: ld returned 1 exit status
make[2]: *** [server/shadow/CMakeFiles/freerdp-shadow-cli.dir/build.make:100: server/shadow/freerdp-shadow-cli] Error 1
make[1]: *** [CMakeFiles/Makefile2:2664: server/shadow/CMakeFiles/freerdp-shadow-cli.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by akallabeth** [comment]
@tangjpA1 well, I´d check which of your variables are options and which are internal variables (a hint: the latter should *never* be overridden)
