### ISSUE TITLE
Smartcard and drive without nla.

### ISSUE THREAD

**Issue by Bendd112** [FreeRDP/FreeRDP#9533]
**Describe the bug**
After reconnecting to an existing session on server without nla,did't redirect smartcard and drive

**To Reproduce**
1. Connect to the server, login using smart card and check that everything is ok (Smartcard is read, disk is redirected)
2. Disconnect (not logout) and connect againt
3. Login using smart card

**Application details**
* FreeRDP version 2.7.0 (2.7.0, 2.11.2, 3.0.0-beta4)
* /smartcart /drive:Storage,/mnt/usbdevice /sec:tls /cert:tofu /v:server.local
* BuildConf in logs
* Windows server 2019 nla disabled

**Environment :**
 - Thinstation6.2(freerdp 2.7.0(main) , 2.11.2 and 3.0.0-beta4) ,Fedora37 (freerdp 2.8.0)
 - Architecture: [amd64,]:
[freerdp.1.log](https://github.com/FreeRDP/FreeRDP/files/13239187/freerdp.1.log)
[freerdp.2.log](https://github.com/FreeRDP/FreeRDP/files/13239188/freerdp.2.log)

**Comment by akallabeth** [comment]
@Bendd112 silly question, but does this work with `mstsc`? (there are some weird behavior with smartcard and windows)

**Comment by Bendd112** [comment]
@akallabeth yes, works fine (win10 22h2). (But username Login username looks weird [win](https://github.com/FreeRDP/FreeRDP/assets/40834125/06011770-f96a-488f-80ba-55d2d0ff42ea)
)

**Comment by akallabeth** [comment]
@Bendd112 `yubikey` or similar? this looks like a generated one time key
something is fishy here, the logs suggest in the case where you log in a existing session the server does not send required messages

**Comment by Bendd112** [comment]
@akallabeth we have only rutoken ecp.

**Comment by akallabeth** [comment]
@Bendd112 ok, I´ve tested this now against various windows servers (2016/2019/2022) and my windows 10 22H2 test machine and can not reproduce.

What I´ve done:
1. run `xfreerdp /smartcard +home-drive /p: /sec:tls ...`
2. log in with the windows logon screen
3. check drive and smartcard are available

so, unless you can provide some more details I must assume this is a bug in your setup outside our project scope.
there are also no error messages in your log suggesting that there is something wrong.

only thing I recognized is that you run the whole thing as `root` which is generally a bad idea for various reasons (one of them that with most systems the user specific stuff is not set up correctly)

**Comment by Bendd112** [comment]
More info...
Tested in a clean virtual environment (winserver 2019 (dc, ca, nla disabled), Thinstation6.2 (3.1.1-dev0, pcscd 2.0.0))
If we drop coection for a few seconds with argument +auto-reconnect, card and drive appear.
Rdesktop 1.9.0 works fine)

**Comment by akallabeth** [comment]
@Bendd112 I´ve asked for more information (like how to recreate a test setup)
1. `clean virtual environment` is meaningless if nobody knows what you *exactly* understand with that phrase.
2. reproduction without any intermediate software (thinstation) might help eliminate outside influences

**Comment by Bendd112** [comment]
Sorry for the brevity. 1. By a clean virtual environment, I mean a newly installed Windows server 2019 and a domain configured on it, a certification authority and an issued Microsoft base smart card crypto provider certificate ([Instructions in Russian](https://dev.rutoken.ru/pages/viewpage.action?pageId=66815562)). Connections were made to this server.
2. As written above, connections were made in the same way with Fedora37 (freerdp 2.8.0). But later I will test it in other distributions (Or tell me on which ).

**Comment by Bendd112** [comment]
When autoreconnect is triggered, the smart card works again.
3.7.0 (Monjaro) same result.
