### ISSUE TITLE
Screen-contents shifting and cutting off upon window resize

### ISSUE THREAD

**Issue by danir-de** [FreeRDP/FreeRDP#9538]
**Describe the bug**
Screen content is shifted (and thus cut off on one or more sides) as soon as the SDL-FreeRDP window is resized.
This issue appears for me on Wayland with SDL-FreeRDP but I believe to have also seen it happening on X.

**To Reproduce**
1. Open an SDL-FreeRDP session on a high-resoultion/muli-monitor setup
2. Resize the window once or multiple times by maximizing the window or by simply manually resizing it with your cursor.
3. Repeat until it happens (mostly on the first resize)

**Expected behavior**
The remote screen should be fill out the FreeRDP window and be perfectly centered, not shifting contents to the side (outside of the window).

**Screenshots**
In this screenshot you can see, how the remote screen got shifted to the right, resulting contents on the right side of the FreeRDP window to be cut off by the amount it's shifted on the left side.
![Screenshot_20231024_173040](https://github.com/FreeRDP/FreeRDP/assets/4672840/1f97edc0-7e0c-476c-84bd-77ca3453b16a)

**Application details**
* FreeRDP version (`sdl-freerdp /version`): 3.0.0-dev5 (d000d9e95)
* Command line used: `sdl-freerdp /d:DOMAIN /u:USER /v:IP -grab-keyboard +fonts +credentials-delegation +auto-reconnect /sound /microphone +drives /bpp:32 +home-drive /dynamic-resolution /scale:100 /scale-desktop:100 /scale-device:100 /gfx:AVC420,thin-client:on,progressive:on /rfx /rfx-mode:image /sec:tls`
* Output of `sdl-freerdp /buildconfig`
* OS version connecting to (server side): Windows 10 Enterprise and Windows 11 Pro
* Current AUR-Build File: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=freerdp-git

**Environment (please complete the following information):**
 - OS: Arch Linux (latest)
 - Architecture: [amd64, arm]: amd64

**Comment by akallabeth** [comment]
@danir-de interesting, I can reproduce the glitches (we just do crude resizing without clearing the contents currently, could use some improvement) but the server does resize properly and the screen is good again.
 
1. does it stay that way for you?
2. could you add a `/log-level:trace` log, maybe there is something we can read from that?

**Comment by danir-de** [comment]
Couldn't test the branch before, but the issue is solved with this! Thanks!
