### ISSUE TITLE
Client Sample moudle run is error。

### ISSUE THREAD

**Issue by tangjpA1** [FreeRDP/FreeRDP#9547]
./usm-rdpc /u:tangjp /p:1 /v:10.113.6.28:3389 /cert-ignore

[15:13:47:341] [25647:25647] [INFO][com.freerdp.gdi] - Local framebuffer format  PIXEL_FORMAT_XRGB32
[15:13:47:341] [25647:25647] [INFO][com.freerdp.gdi] - Remote framebuffer format PIXEL_FORMAT_BGRA32
[15:13:47:342] [25647:25647] [INFO][com.freerdp.channels.rdpsnd.client] - [static] Loaded fake backend for rdpsnd
[15:13:47:355] [25647:25647] [INFO][com.freerdp.channels.drdynvc.client] - Loading Dynamic Virtual Channel rdpgfx
[15:13:49:361] [25647:25671] [ERROR][com.freerdp.channels.cliprdr.client] - context->custom not set!
[15:13:49:361] [25647:25671] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_general_capability failed with error 1359!
[15:13:49:361] [25647:25671] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_process_clip_caps failed with error 1359!
[15:13:49:361] [25647:25671] [ERROR][com.freerdp.channels.cliprdr.client] - cliprdr_order_recv failed with error 1359!
[15:13:49:361] [25647:25647] [ERROR][com.freerdp.core] - cliprdr_virtual_channel_client_thread reported an error. Error was 1359
[15:13:49:361] [25647:25647] [ERROR][com.freerdp.core] - checkChannelErrorEvent() failed - 0
[15:13:49:361] [25647:25647] [ERROR][com.freerdp.client.sample] - Failed to check FreeRDP event handles

I haven't changed anything to the code, so why would I be prompted for this code?
I consulted the help of -h, but did not find a solution that could be used。
The version number is 2.11.2

centos7.9
Linux localhost.localdomain 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by akallabeth** [comment]
well, you did not implement the clipboard for your client?

**Comment by tangjpA1** [comment]
I'm using client/Sample. Won't it run directly? Still need me to implement clipboard?

**Comment by akallabeth** [comment]
@tangjpA1 ok, that was not obvious (`usm-rdpc` is not the sample client name), but still. add `-clipboard` to disable it (we default to enabled)

**Comment by tangjpA1** [comment]
Dear big guy, is there a simple use case for a linux client that can run?

**Comment by tangjpA1** [comment]
For beginners, you need a demo prototype that can run, and then debug tracks the code, which is easier to get started, but I read most of the information on the Internet, and there is no perfect linux client that can run normally.

**Comment by akallabeth** [comment]
@tangjpA1 what do you want to do?
there are lots of clients, but depending on what you want (and what you already know) the answer differs ;)

1. the sample client is a good way to study the basic callbacks you need to implement
2. if you want something that is actually showing you something, then `sdl-freerdp` , `wlfreerdp` and `xfreerdp` are directly part of `FreeRDP`, but there are others ([Remmina](https://remmina.org/), [connections](https://gitlab.gnome.org/GNOME/connections), ...)

**Comment by tangjpA1** [comment]
@akallabeth I now have a requirement, is to connect to rdp server through rdp client, send instructions, and store graphics to sqlite, there is a good adaptation of the code can refer to?

**Comment by akallabeth** [comment]
well, then actually sample client is all you are looking for ;)
just disable the clipboard and store the framebuffer to some image

**Comment by tangjpA1** [comment]
@akallabeth     Dear Big man，    What I need is I need to send instructions, I need to map a program to the server and execute it, and then I need to store the graphics of the whole process. So you have to have a sticker module。
I have to integrate the paste board. I know the code module with the paste board in the code, but I am not sure which module's paste board is better for reference. Could you give me some advice?

**Comment by akallabeth** [comment]
they are all bad for your task. you will have to do some reading, check [[MS-RDPECLIP]](https://learn.microsoft.com/en-us/openspecs/windows_protocols/MS-RDPECLIP/fb9b7e0b-6db4-41c2-b83c-f889c1ee7688) for details.

**Comment by tangjpA1** [comment]
@akallabeth   
亲爱的大佬，根据你的指示，我已经把图形传输，剪贴板，模拟键盘指令都实现了，但是我现在有一个磁盘映射的功能我看是已经初始化成功的，但是我不是很明白这个映射参数在代码的setting  应该是对应的RDPDR_DEVICE，您可以写一两行代码给我距离如何初始化这个目录映射吗？
比如刚开始我设置用户密码等：

context->settings->Username = "administrator";
context->settings->Password = "123456";
context->settings->ServerHostname = "10.113.56.194";
context->settings->ServerPort = 3389;
context->settings->IgnoreCertificate = true; //忽略证书

What is the convenient way if I set up the disk mapping?
Here's what I'm referring to

static BOOL freerdp_client_add_drive(rdpSettings* settings, const char* path, const char* name)
{
RDPDR_DRIVE* drive;

drive = (RDPDR_DRIVE*)calloc(1, sizeof(RDPDR_DRIVE));

if (!drive)
return FALSE;

drive->Type = RDPDR_DTYP_FILESYSTEM;

if (name)
{
/* Path was entered as secondary argument, swap */
if (winpr_PathFileExists(name))
{
if (!winpr_PathFileExists(path) || (!PathIsRelativeA(name) && PathIsRelativeA(path)))
{
const char* tmp = path;
path = name;
name = tmp;
}
}
}

if (name)
{
if (!(drive->Name = _strdup(name)))
goto fail;
}
else /* We need a name to send to the server. */
{
if (!(drive->Name = name_from_path(path)))
goto fail;
}

if (!path || !freerdp_sanitize_drive_name(drive->Name, "\\/", "__"))
goto fail;
else
{
BOOL isSpecial = FALSE;
BOOL isPath = freerdp_path_valid(path, &isSpecial);

if ((!isPath && !isSpecial) || !(drive->Path = _strdup(path)))
goto fail;
}

if (!freerdp_device_collection_add(settings, (RDPDR_DEVICE*)drive))
goto fail;

return TRUE;

fail:
free(drive->Path);
free(drive->Name);
free(drive);
return FALSE;
}
1542/5000
[翻译](javascript:;)
Dear big guy, according to your instructions, I have implemented graphics transfer, clipboard and analog keyboard commands, but now I have a disk mapping function which I think has been successfully initialized, but I don't quite understand that this mapping parameter should be corresponding to RDPDR_DEVICE in the code setting. Can you write a line or two of code to give me the distance on how to initialize this directory map?
For example, I set the user password at the beginning:

context->settings->Username = "administrator";
context->settings->Password = "123456";
context->settings->ServerHostname = "10.113.56.194";
context->settings->ServerPort = 3389;
context->settings->IgnoreCertificate = true;  // Ignore the certificate
What is the convenient way for me to set up my certificate?
Here's what I'm referring to
static BOOL freerdp_client_add_drive(rdpSettings* settings, const char* path, const char* name)
{
RDPDR_DRIVE* drive;

drive = (RDPDR_DRIVE*)calloc(1, sizeof(RDPDR_DRIVE));

if (! drive)
return FALSE;

drive->Type = RDPDR_DTYP_FILESYSTEM;

if (name)
{
/* Path was entered as secondary argument, swap */
if (winpr_PathFileExists(name))
{
if (! winpr_PathFileExists(path) || (! PathIsRelativeA(name) && PathIsRelativeA(path)))
{
const char* tmp = path;
path = name;
name = tmp;
}
}
}

if (name)
{
if (! (drive->Name = _strdup(name)))
goto fail;
}
else /* We need a name to send to the server. */
{
if (! (drive->Name = name_from_path(path)))
goto fail;
}

if (! path || ! freerdp_sanitize_drive_name(drive->Name, "\\/", "__"))
goto fail;
else
{
BOOL isSpecial = FALSE;
BOOL isPath = freerdp_path_valid(path, &isSpecial);

if ((! isPath && ! isSpecial) || ! (drive->Path = _strdup(path)))
goto fail;
}

if (! freerdp_device_collection_add(settings, (RDPDR_DEVICE*)drive))
goto fail;

return TRUE;

fail:
free(drive->Path);
free(drive->Name);
free(drive);
return FALSE;
}
like
dislike
1542/5000
[翻译](javascript:;)
like
dislike
 使用网易有道翻译 Windows版提高你的工作效率免费下载



教育
[有道智慧教育](https://zhihui.youdao.com/)
[中国大学MOOC](https://www.icourse163.org/)
[网易有道校企合作](https://school.youdao.com/)
关于有道
[有道介绍](http://shared.youdao.com/www/about.html)
[投资者关系](https://ir.youdao.com/#/)
[社会责任](https://shared.youdao.com/dict/market/dictLawPdfRead/oldv1/web/viewer.html?file=https://shared.ydstatic.com/dict/market/socialResponsibility/%E6%9C%89%E9%81%932022%E7%A4%BE%E4%BC%9A%E8%B4%A3%E4%BB%BB%E6%8A%A5%E5%91%8A.pdf)
[同道计划](https://tongdao.youdao.com/)
[廉正举报](https://jubao.163.com/)
[联系我们](http://shared.youdao.com/www/contactus-page.html)
加入有道
[校园招聘](http://hr.youdao.com/)
[社会招聘](https://hr.163.com/)
相关资质
[营业执照](https://c.youdao.com/dict/law/business_license.html)
[出版物经营许可证](https://c.youdao.com/dict/law/publicationLicense.html)
广播电视节目
制作许可证
用户资质
[隐私政策](https://c.youdao.com/dict/law/youdao_agreement/privacy.html)
[服务条款](http://xue.youdao.com/sw/m/1191866)
企业
[有道智云 · AI 开放平台](https://ai.youdao.com/?keyfrom=fanyi-new-nav#/)
[有道智选](https://dsp.youdao.com/#/index)
[Youdao Ads](https://youdaoads.com/)
[有道人工翻译](https://f.youdao.com/)
[©2023网易公司](http://www.163.com/) 京ICP证080268号[ 京ICP备10005211号](http://beian.miit.gov.cn/)[ 京公网安备 11010802020092号](http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=11010802020092)
网上有害信息举报专区 网易廉政举报：[jb@rd.netease.com](mailto:jb@rd.netease.com) 违法和不良信息举报电话：4006666696
举报邮箱（涉未成年人）：youdao_jubao@rd.netease.com

**Comment by tangjpA1** [comment]
@akallabeth  Dear author, according to the document you gave, I successfully extracted pictures and used the disk mapping paste board during the development process, but now I encounter a problem, when I map the disk past, the window program I run will produce a file after running, at this time I know when to exit the client. However, I do not find the corresponding interface to obtain the current event handle and signal processing. I only see that the freerdp_check_event_handles function in the system library triggers image information. In version 1.0.2 there was freerdp_channel_pop_event to get the current event type. In 2.10.X what is the alternative? Or how do you get it in pubsub?
