### ISSUE TITLE
Printer redirection broken in macOS 14 (Sonoma)

### ISSUE THREAD

**Issue by thenextman** [FreeRDP/FreeRDP#9567]
Printer redirection no longer works on macOS 14 (Sonoma) clients. The printers are redirected and print jobs are added to the queue, but never progress.

1. Run macFreeRDP on a macOS 14 (Sonoma) system and redirect printers with `/printer`
2. Try to print a document to a redirected printer
3. Observe the document gets added to the print queue
4. The document never prints and remains unmoving in the queue

**Expected behavior**
The document should print on the local printer

**Application details**
* FreeRDP version 3.0.0-dev5
* /v:192.168.1.1 /sec:tls /printer
* Windows 2022

**Environment**
 - OS: macOS
 - Version/Distribution: 14 Sonoma
 - Architecture: arm64

**Additional context**
This is a regression on macOS 14, earlier versions work fine. The macOS 14 release notes state:

> [Printing](https://developer.apple.com/documentation/macos-release-notes/macos-14-release-notes#Printing)
> [Deprecations](https://developer.apple.com/documentation/macos-release-notes/macos-14-release-notes#Deprecations)
> macOS has removed the functionality for converting PostScript and EPS files to PDF format. As a result, CoreGraphics’ CGPSConverter returns an error when invoked, ImageIO no longer converts EPS files, NSEPSImageRep does not display EPS files, and PMPrinterPrintWithFile does not accept a PostScript file for non-PostScript print queues. (110019863)

Furthermore, it seems the MS RDP client was affected by the same issue. They released 10.9.4 with this changelog:

> Printer redirection has been broken when connecting from macOS Sonoma due to the removal of PostScript support.
> This release fixes printer redirection for connections from macOS Sonoma to Windows 10 or later.

Noting that they no longer support printer redirection to server OS older than Windows 10, from a macOS 14 system.

**Comment by akallabeth** [comment]
this can be worked around with:
1. goto `System Settings` ![image](https://github.com/FreeRDP/FreeRDP/assets/3472254/b2af89e1-eb4f-4e15-983e-67b77db1f9ff)
1. open printer details ![image](https://github.com/FreeRDP/FreeRDP/assets/3472254/a08da8bb-ad5c-402b-af57-4965df9efbfd)
1. open `Options & Supplies` ![image](https://github.com/FreeRDP/FreeRDP/assets/3472254/a04fd78d-d395-40dc-8173-3d09ae4bccc4)
2. remember `Device Name`
3. start with `xfreerdp /printer:<Device Name>,"Microsoft Print to PDF"`

this only works for targets that have the `Microsoft Print to PDF` driver available (windows 10 and newer)
