### ISSUE TITLE
wfreerdp able to connect but fail when run with  /app:program or /action-script: command

### ISSUE THREAD

**Issue by nklchaudhary** [FreeRDP/FreeRDP#9584]
Hi Team, I am using FreeRDP and got with version command -
This is FreeRDP version 3.0.0-dev5 (bd2ac8b11)

and help command also returning all commands - 
FreeRDP - A Free Remote Desktop Protocol Implementation
See www.freerdp.com for more information

Usage: wfreerdp [file] [options] [/v:<server>[:port]]

Syntax:
    /flag (enables flag)
    /option:<value> (specifies option with value)
    +toggle -toggle (enables or disables toggle, where '/' is a synonym of '+')

    /a:<addin>[,<options>]            Addin
    /action-script:<file-name>        Action script
    /admin                            Admin (or console) session
    +aero                             Enable desktop composition
    /app:program:[<path>|<||alias>],cmd:<command>,file:<filename>,guid:<guid>
          icon:<filename>,name:<name>,workdir:<directory>
                                      Remote application program
    /args-from:<file>|stdin|fd:<number>|env:<name>
                                      Read command line from a file, stdin or
                                      file descriptor. This argument can not be
                                      combined with any other. Provide one
                                      argument per line.

My windows configuration is

- Windows Server 2019
- 16 GB RAM
- x64- based processor

I am able to connect sucessfully with this command [Add * for confidential information]
wfreerdp /v:******  /u:****** /p:******  /cert:ignore

But when I run any command that have to execute any exe or script after remote desktop connection i got just mesaage "Preparing Window" for some time and then disconnected.

My scripts are - 

wfreerdp /v:******  /u:****** /p:******  /cert:ignore /app:program:"||calc"
wfreerdp /v:******  /u:****** /p:******  /cert:ignore /app:program:"||mspaint"
wfreerdp /v:******  /u:****** /p:******  /cert:ignore /app:program:"||chrome.exe"
wfreerdp /v:******  /u:****** /p:******  /cert:ignore /action-script:"C:\Program Files\Test\ABC\My.bat"

![Issue](https://github.com/FreeRDP/FreeRDP/assets/103640916/cd20055a-75c9-47a1-9f55-4e7e0b74412f)

Please help me.

**Comment by akallabeth** [comment]
you need to set up your windows to actually enable remote application mode.
nothing we can do here.

**Comment by nklchaudhary** [comment]
Hi @akallabeth , I am not able to understand what is remote application mode. Is it enable remote desktop connection? Can you explain and suggest how can enable it.
