### ISSUE TITLE
I'd like to know the command to execute on the power shell. (from Proxy)

### ISSUE THREAD

**Issue by soulpanic** [FreeRDP/FreeRDP#9602]
Hello.

Is there a way to know the command that the user runs on the power shell in proxy?

I'd appreciate it if you could let me know.

**Comment by soulpanic** [comment]
Thank you. It's kind of sad.
Is it difficult to know the window where the key event occurred?

**Comment by akallabeth** [comment]
to put it simply:
1. if you run `rails/remote app` mode then you have windows (one `video stream` per window)
2. in normal session mode you only have a `video stream`
3. except if you happen to run windows XP (or misconfigured your server), then there is the old `GDI` emulation (for both), but that is awfully slow
