### ISSUE TITLE
Add support for developing within Devcontainers

### ISSUE THREAD

**Issue by loligans** [FreeRDP/FreeRDP#9614]
**Is your feature request related to a problem? Please describe.**
This feature isn't related to the function of FreeRDP. My aim is to allow myself and others to compile FreeRDP from within a devcontainer. The idea here is that during initialization of the devcontainer, all required dependencies would be installed. Although not my main goal I believe it could allow others to contribute faster and lower the bar for entry

**Describe the solution you'd like**
Simply adopting the the devcontainer spec as well as implementing the Dockerfile to install all of the necessary dependencies.

**Describe alternatives you've considered**
I support installing the dependencies locally on my machine, however I'd like to not clutter my machine that way and would value the separation of development environment in docker and my work station

**Additional context**
I could implement this feature if it was accepted. Although since FreeRDP is a GUI app I suspect the usefulness of devcontainers is lower. However having reproducible builds could be convenient

**Comment by akallabeth** [comment]
a starting point would be https://github.com/FreeRDP/FreeRDP/wiki/Compilation#compilation or the ci scripts https://github.com/FreeRDP/FreeRDP/blob/master/.github/workflows/codeql-analysis.yml

**Comment by engrcyberbd** [comment]
Some people doesn't use.. Please fixed it immediately.. & any further Problem send a message on insta thank you
