### ISSUE TITLE
TestFreeRDPCodecProgressive regression on big-endian between 2.10.0 and 2.11.0

### ISSUE THREAD

**Issue by matoro** [FreeRDP/FreeRDP#9616]
Since 2.11.0, on big-endian architectures, TestFreeRDPCodecProgressive fails with the following output:

```
172/188 Testing: TestFreeRDPCodecProgressive
172/188 Test: TestFreeRDPCodecProgressive
Command: "/var/tmp/portage/net-misc/freerdp-2.11.1/work/freerdp-2.11.1_build/Testing/TestFreeRDPCodec" "TestFreeRDPCodecProgressive"
Directory: /var/tmp/portage/net-misc/freerdp-2.11.1/work/freerdp-2.11.1_build/libfreerdp/codec/test
"TestFreeRDPCodecProgressive" start time: Dec 07 04:03 UTC
Output:
----------------------------------------------------------
xxxxxxx [19:16] 1F1E1C8A != 881D1F00
<end of output>
Test time =   0.23 sec
----------------------------------------------------------
Test Failed.
"TestFreeRDPCodecProgressive" end time: Dec 07 04:03 UTC
"TestFreeRDPCodecProgressive" time elapsed: 00:00:00
```

The issue is present on latest stable-2.0 branch and is not present in 2.10.0 tag.

**Comment by matoro** [comment]
> @matoro most likely [e3ef8a0](https://github.com/FreeRDP/FreeRDP/commit/e3ef8a02ddf079bcf6dfa58888db69a709ce50c9) but I lack the test environment for big endian. so anyone who can check and fix that? @joantolo pinging you too

Yep, this reverts cleanly and fixes the issue.

In the future I offer [free shell access](https://static.matoro.tk/isa-sandbox-faq.html) to big-endian hardware and more for testing!

**Comment by akallabeth** [comment]
> > @matoro most likely [e3ef8a0](https://github.com/FreeRDP/FreeRDP/commit/e3ef8a02ddf079bcf6dfa58888db69a709ce50c9) but I lack the test environment for big endian. so anyone who can check and fix that? @joantolo pinging you too
> 
> Yep, this reverts cleanly and fixes the issue.
> 
> In the future I offer [free shell access](https://static.matoro.tk/isa-sandbox-faq.html) to big-endian hardware and more for testing!

wow, nice! finally something. would it be possible to run a pr builder or is that too much of a load for you?

**Comment by akallabeth** [comment]
oh, that could be great!
I´d suggest a github ci run and make it optional so it does not block pull requests hard. (we already have one for codeql)

**Comment by matoro** [comment]
> oh, that could be great! I´d suggest a github ci run and make it optional so it does not block pull requests hard. (we already have one for codeql)

Sure - I can draft a PR to see about adding it!

**Comment by matoro** [comment]
@akallabeth Got it working here, summary of what I've got.

On 3.0 branch, there is one test `TestConnection` which fails on all platforms.  I'm not sure this is QEMU's fail or what, so I disabled it for now.

On 2.0 and 3.0 branch, the following test fails on 32-bit ARM.  This is also a good opportunity for 32-bit coverage:
```
   168/170 Test #165: TestPrimitivesYUV ........................***Failed    1.53 sec
  Running AVC444 on frame size 54x92
  Running AVC444 on frame size 54x92
  [AVC444] Invalid destination alpha value FF at position 0
  -------------------- GENERIC ------------------------
  Testing destination color format PIXEL_FORMAT_XRGB32
  Testing destination color format PIXEL_FORMAT_XBGR32
  Testing destination color format PIXEL_FORMAT_ARGB32
  Testing destination color format PIXEL_FORMAT_ABGR32
  Testing destination color format PIXEL_FORMAT_RGBA32
  Testing destination color format PIXEL_FORMAT_RGBX32
  Testing destination color format PIXEL_FORMAT_BGRA32
  Testing destination color format PIXEL_FORMAT_BGRX32
  ---------------------- END --------------------------
  ------------------- OPTIMIZED -----------------------
  Testing destination color format PIXEL_FORMAT_XRGB32
  Testing destination color format PIXEL_FORMAT_XBGR32
  Testing destination color format PIXEL_FORMAT_ARGB32
  TestPrimitiveYUV (444) failed.
```

On 2.0 branch, you can see this exact issue reproduced on s390x!

On 3.0 branch, there are 5 additional failures on big-endian:

```
  96% tests passed, 6 tests failed out of 170
  
  Total Test time (real) =  22.95 sec
  
  The following tests FAILED:
  	109 - TestNTLM (Failed)
  	113 - TestString (Failed)
  	114 - TestUnicodeConversion (Failed)
  	132 - TestCommonAssistance (Failed)
  	155 - TestFreeRDPCodecProgressive (Failed)
  	168 - TestClientRdpFile (Failed)
  Errors while running CTest
```

3.0 run:  https://github.com/matoro/FreeRDP/actions/runs/7143485340
2.0 run:  https://github.com/matoro/FreeRDP/actions/runs/7145992057

Now, I don't want to commit something that will immediately make CI go red and make everyone start disregarding it.  Or commit this in non-enforcing mode such that everyone ignores it.  How would you like the PR to include this?

**Comment by akallabeth** [comment]
@matoro I´d skip the 2.0 branch as we are just releasing 3.0 and put that one into maintenance mode.
as for `TestConnect` it is a bit fragile (it fires up a RDP server and a client and tries to do connections. can look at that one later.
the others are most likely due to never being really tested on big endian (or not for a very long time)

anyway, will have a look this week.

**Comment by akallabeth** [comment]
ok, got the other issues:
`Error: 55:184] [15134:00003b1e] [ERROR][com.winpr.unicode] - [int_WideCharToMultiByte]: unexpected ICU error code U_INVALID_CHAR_FOUND [0x0000000a] is fatal`

the whole thing depends heavily on little endian 16bit unicode (aka the version windows uses) and ICU does seem to assume big endian unicode there? needs some investigation.

**Comment by matoro** [comment]
> @matoro I´d skip the 2.0 branch as we are just releasing 3.0 and put that one into maintenance mode. as for `TestConnect` it is a bit fragile (it fires up a RDP server and a client and tries to do connections. can look at that one later. the others are most likely due to never being really tested on big endian (or not for a very long time)
> 
> anyway, will have a look this week.

2.0 branch is really important to us as we are maintaining it downstream, check our [architecture matrix](https://packages.gentoo.org/packages/net-misc/freerdp).  This came from a [stabilization request](https://bugs.gentoo.org/918531) where we have to manually test it on all supported arches including BE ones...for now we have downstreamed a patch to revert the bad commit but of course we always prefer to have those sorts of fixes upstream.  https://github.com/gentoo/gentoo/commit/60975f5f4bdc9f9c5002ac8cfaf32e0a2095b770

I guess I can create a PR for now, and then you can create fix PRs and cherry-pick in the CI commit, then I can rebase fixes/cherry-picks as needed until there's a green CI?

**Comment by pnowack** [comment]
> where we have to manually test it on all supported arches including BE ones...for now we have downstreamed a patch to revert the bad commit but of course we always prefer to have those sorts of fixes upstream. https://github.com/gentoo/gentoo/commit/60975f5f4bdc9f9c5002ac8cfaf32e0a2095b770

Well, with reverting that commit locally, you may now have a passing test, but broken colours again on BE machines:

![Screenshot from 2023-07-28 09-05-04](https://github.com/FreeRDP/FreeRDP/assets/40351335/7d78cbb1-a830-4b9e-a027-fb9d839d366d)

**Comment by matoro** [comment]
> > where we have to manually test it on all supported arches including BE ones...for now we have downstreamed a patch to revert the bad commit but of course we always prefer to have those sorts of fixes upstream. [gentoo/gentoo@60975f5](https://github.com/gentoo/gentoo/commit/60975f5f4bdc9f9c5002ac8cfaf32e0a2095b770)
> 
> Well, with reverting that commit locally, you may now have a passing test, but broken colours again on BE machines:
> 
> ![Screenshot from 2023-07-28 09-05-04](https://private-user-images.githubusercontent.com/40351335/289383857-7d78cbb1-a830-4b9e-a027-fb9d839d366d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzkwODYsIm5iZiI6MTcwMjIzODc4NiwicGF0aCI6Ii80MDM1MTMzNS8yODkzODM4NTctN2Q3OGNiYjEtYTgzMC00YjllLWEwMjctZmI5ZDgzOWQzNjZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDIwMDYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1OTY3NzFlZWFiMmU3NzdlNDU5NjlhMDllYjZkMDk5MThiOTg5MDk1Njg5NzVlYmExOTk3NTI5ZTEyNjA3YTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MXgfvVXANqDQ9JAQL4Ob3NXSoOBv9mbchUOVoClYPc0)

So that means the test code is wrong?

**Comment by pnowack** [comment]
> So that means the test code is wrong?

If it passed before Joans commit and now not anymore, then yes. The colours were previously wrong, now they are right.

**Comment by akallabeth** [comment]
@matoro we can backport that if we have something that works, if you still require it that much ;)
but for now, I´ll have a look at the unicode thing (you might want to try `-DWITH_UNICODE_BUILTIN=ON` meanwhile and check if that implementation works)

**Comment by joantolo** [comment]
I'll take a look at what is making that test fail. However, I won't have access to a BE system until next year, so the feedback will be a bit slow.

**Comment by akallabeth** [comment]
@matoro ok, the `UNICODE_BUILTIN` is not working on big endian.
for `ICU` we´d need to change and use `ucnv_toUChars` and `ucnv_fromUChars` with a `ucnv_open("UTF-8", errorCode)` or `ucnv_open("UTF-16LE", errorCode)`

**Comment by akallabeth** [comment]
@matoro did have a look at your ci changes, created https://github.com/akallabeth/FreeRDP/tree/bigendian with the fixed ICU and a proper cmake test run.
would be interesting if this works.
