### ISSUE TITLE
Serial port (COM) redirection working very strange

### ISSUE THREAD

**Issue by diger74** [FreeRDP/FreeRDP#963]
Hi all,

I'm trying to redirect /dev/ttyUSB0 device as COM3 to my Remote Desktop session. And it's working very strange.

First of all, I made a test serial hard device that can receive data and send back confirmation about it. I've typed 4 symbols: "q", "a", "z" and "w" and here is what I've got in logs (download to view difference):
<a href="https://docs.google.com/file/d/0BwyYvXDgZQ8VMS1HdlRXQm1PUDA/edit?usp=sharing">FreeRDP log</a>
<a href="https://docs.google.com/file/d/0BwyYvXDgZQ8VQTVkZGUxZ3ZwcWc/edit?usp=sharing">mstsc log</a>
And see also at picture where difference is shown by Putty (first screen is for mstsc and the second one is for FreeRDP, note also that there are 12x spaces after each phrase):
![putty](https://f.cloud.github.com/assets/1597268/144990/2ab2e376-7448-11e2-91e6-dda6d6d3d6e7.jpg)
It seems that with FreeRDP wasn't sended CR symbol but LF was sended twice.

Next strange thing is that this redirected port can't be contacted with .NET or Delphi classes it can speak only native WinAPI functions (because Putty and <a href="http://www.comp.lancs.ac.uk/~albrecht/sw/terminal/index.html">serialterm</a> are able to contact this port). This happens only with FreeRDP. When COM ports redirection enabled in mstsc.exe all works fine both of with .NET and with WinAPI.
If it will be helpfull here is exception from .NET SerialPort class when trying to open it:

System.ArgumentException: The given port name is invalid.  It may be a valid port, but not a serial port.

This means that my program was able to find COM3 port at the system but think that it is not a serial port.

P.S. I'm running FreeRDP client in this way:

> xfreerdp /a:serial,COM3,/dev/ttyUSB0 /v:server

**Comment by pcleiter** [comment]
Realizing this is a really old post but I just found it and it revealed something to me which has been helpful and so maybe I can help someone else with what I found.

Change Port reveals different redirection when run from an administrative command prompt than it does when run under a non-administrative command prompt.  When run from the admin prompt, it does not see/have access to the same ports that the RDP session has access to.  When I run VS.NET, I do so with elevated (administrative) rights, and therefore presumably when I'm debugging my program by running it from VS.NET, I'm also using those elevated rights.  And so my program cannot see the port mappings that my RDP user has, it can only see those which the admin user has.

I've run into this before, I think with Visual Source Safe, and there was some registry modification that I did to get past it.  So I think this is a similar thing.  For me, for now, I'm going to do my best with running the debug manually rather via running from VS.NET.  I've done that a few times now and I do in fact have access to my local comm ports.
