### ISSUE TITLE
unable to leave fullscreen mode with CTRL+ALT+ENTER - after a while...

### ISSUE THREAD

**Issue by basprins** [FreeRDP/FreeRDP#9640]
I use xfreerdp to RDP into a windows laptop (from ubuntu 23.04 host). I run xfreerdp in full screen mode, taking control of all my displays. I use CTRL+ALT+ENTER to leave full screen mode, and CTRL+ALT+ENTER again to go back to full screen mode. 

This sometimes work, but often xfreerdp refuses to leave full screen mode when I hit CTRL+ALT+ENTER. I can see some visual feedback (a quick blink on all screens) where I think xfreerdp tries to leave full screen mode, but fails. 

I am using latest versions of x

I start xfreerdp as follows
xfreerdp /multimon /d:*** /u:*** /p:*** /v:***

When the RDP session is freshly started, CTRL+ALT+ENTER always works. Always. But when I am in the RDP session for a while, it pretty much never works. The only way to leave full screen mode is to choose Windows->Power->Disconnect, this closes the RDP session client side and then I can reopen it again from ubuntu, to repeat the cycle.

Maybe it has something to do with power management or auto lock settings (which I can't control on the guest OS, company policies). 

Does this sound familiar to anyone? Is there something I can do to prevent this? Is there more information I can share I don't know about? xfreerdp logging maybe (not sure if that exists and if so, where I can find them). Or wayland loggings (I don't really know what I am saying now ;-)).

**Comment by akallabeth** [comment]
well, that sounds like a possible window manager issue.
could you add some details to your machine? (os, ...)

**Comment by zhkonst** [comment]
I've got the same problem. wlfreerdp works well, but doesn't toggle full screen mode on Alt-Ctrl-Enter. xfreerdp (with switching KDE to X11) has no such problem.
Debian 12, 6.1.66-1, x86_64, KDE Plasma
If you need any additional information - feel free to demand.

**Comment by akallabeth** [comment]
@zhkonst you have the issue or not?
I think you said:
1. you have the issue with `xfreerdp` under `XWayland`
2. you do not have the issue with `wlfreerdp`
3. you do not have the issue with `xfreerdp` under `X11`

is that correct?

**Comment by zhkonst** [comment]
@akallabeth 
Not quite.
1. I have a problem with wlfreerdp under Wayland. I just copied my current settings. I need RDP to work, so I switched to X11 to use xfreerdp. The problem was when I used wlfreerdp under Wayland.
2. I have a problem with wlfreerdp.
3. I have no problems with xfreerdp under X11.

**Comment by akallabeth** [comment]
@zhkonst ah, ok. so a little off topic here (initial reporter was taling about `xfreerdp`)
btw, why switch to `X11`? `XWayland` is more than enough to use `xfreerdp`

**Comment by basprins** [comment]
Hi @akallabeth 
sorry for the late reply, was following the previous discussion. I am running ubuntu 23.04 on wayland. 
So I have 2 laptops:
one work,:
- 1x laptop screen
- windows 10 (irrelevant, I guess)
one personal (legion amd9):
- 1x laptop screen
- 2x HDMI 
- ubuntu 23.04/wayland

xfreerdp (as mentioned earlier) is RDPing with /multimon so all "host" screens used to control my windows PC. It works great, but I think since I upgraded to 23.04 (half a year ago) this problem of not being able to leave remote session is kind of annoying. 

It reproduces quite often, so if I need to collect logs please tell me (and please also tell me what to collect exactly :))

**Comment by akallabeth** [comment]
@basprins ok, so you are using the repo package I assume?
can you give our nightly a try and check if that is also exposing this behavior?
https://github.com/FreeRDP/FreeRDP/wiki/Prebuilds (note that you need to start with `/opt/freerdp-nightly/bin/xfreerdp`)

**Comment by zhkonst** [comment]
I've tryed to use xfreerdp under Wayland, but there was a blinking monitor on each mouse moving. Under X11 everything works just perfect.21:55, 16 декабря 2023 г., akallabeth ***@***.***>:
@zhkonst ah, ok. so a little off topic here (initial reporter was taling about xfreerdp)
btw, why switch to X11? XWayland is more than enough to use xfreerdp

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
Константин Жечковский

**Comment by basprins** [comment]
Apologies for the radio silence... 

I installed:
bp@legion:~/scripts(master)$ /opt/freerdp-nightly/bin/xfreerdp --version
This is FreeRDP version 3.0.1-dev0 (373544016)

1. I start RDP using:
/opt/freerdp-nightly/bin/xfreerdp /audio-mode:1 /multimon /d:$1 /u:$2 /p:$password /v:$3

2. The RDP session starts full screen.
3. CTRL+ALT+ENTER to leave full screen => OK
4. CTRL+ALT+ENTER to re-enter full screen => OK
5. CTRL+ALT+ENTER to leave full screen => NOK

Any consecutive CTRL+ALT+ENTER "nothing" happens. I see a brief screen refresh over all three physical screens, but the key event is either ignored by xfreerdp, or it never gets delivered. The only way to exit full screen is by terminating the RDP session on client side (windows => power => disconnect).

**Comment by zeroepoch** [comment]
I see the same issue on Fedora 39 with 2.11.4. I started in window mode then CTRL+ALT+Enter goes into fullscreen mode. I can never leave fullscreen mode. This sounds similar to @basprins, but I didn't start in fullscreen mode. The remote system is Ubuntu 22.04 using the built-in GNOME display sharing feature. I don't have a disconnect option on GNOME, so I have no way to get out of session other than dropping to a VT and killing `xfreerdp`.

**Comment by zeroepoch** [comment]
To add another data point, I just tried to floatbar option since that should give me a way to disconnect. The floatbar does indeed only show up by default in fullscreen mode when I add `/floatbar`. Although once I click the button to exit fullscreen on the floatbar it's still in fullscreen mode essentially and now the floatbar is gone. CTRL+ALT+ENTER goes back into what xfreerdp thinks is fullscreen mode and displays the floatbar.

**Comment by zeroepoch** [comment]
I just compiled freerdp 3.2.0 from source (via the Fedora 40 SRPM package) and it has the same problem. I also tried `sdl-freerdp` since I see that's available now, but I can't enter fullscreen from a window, or exit fullscreen with CTRL+ALT+Enter. Probably a completely different issue, but wanted to add that data point in case it matters.

**Comment by akallabeth** [comment]
> I just compiled freerdp 3.2.0 from source (via the Fedora 40 SRPM package) and it has the same problem. I also tried `sdl-freerdp` since I see that's available now, but I can't enter fullscreen from a window, or exit fullscreen with CTRL+ALT+Enter. Probably a completely different issue, but wanted to add that data point in case it matters.

for reasons of being simple to imlement `sdl-freerdp` currently uses `right shift` as modifier key, that will be adjusted later.

**Comment by rcarmo** [comment]
The same happens on the Mac client (freshly built as described in #9882). I can't even exit the client with standard macOS gestures, which is really counterproductive (I suspect this last part is because of the lack of some window hints when creating the view, might be able to fix it). Only way out is to completely quit the client with Cmd+Q.

**Comment by akallabeth** [comment]
> The same happens on the Mac client (freshly built as described in #9882). I can't even exit the client with standard macOS gestures, which is really counterproductive (I suspect this last part is because of the lack of some window hints when creating the view, might be able to fix it). Only way out is to completely quit the client with Cmd+Q.
> 
> (also, to add to the chorus around Ctrl+Alt+Enter, that too is counterproductive in some of the other platforms I use)

1. mac client has different shortcuts, so offtopic.
2. the standard gestures interfere with redirecting all input to the remote ;) moving the mouse to the top works on my mac here, then the top bar is shown and you can leave fullscreen.

**Comment by rcarmo** [comment]
Commercial clients don’t have these issues. Either way, moving the mouse to the top does not work on my fresh builds on Sonoma.

**Comment by Isles487** [comment]
Reporting the same issue as @basprins on Arch Linux in gnome.

6.7.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 23 Feb 2024 16:31:48 +0000 x86_64 GNU/Linux
xfreerdp installed from freerdp package
Version 2.11.4
Starting with these command line options: /f /smart-sizing -clipboard

Using CTRL-ALT-ENTER:

1) Can go full screen
2) Can exit full screen once 
3) On any subsequent attempts to exit full screen, the window appears to look as though it will minimize, but promptly snaps back into full screen. Cannot exit full screen.

**Comment by RobZRH** [comment]
Same problem. After a while i can't exit fullscreen. Xfreerdp with Ubuntu 22.04.

**Comment by exspecto** [comment]
I have this same problem in Ubuntu 24.04 when connecting to a Windows 11 machine. Removing the /smart-sizing flag enabled the ability to toggle fullscreen repeatedly without issue.

**Comment by hzdmnl** [comment]
After I upgraded ubuntu 22 to 24 - got the same problem. Tried x-11 and wayland, freerdp2 and freerdp3 - everywhere this problem appears. Already thinking about rolling back to ubuntu 22

**Comment by basprins** [comment]
Ctrl + tab is my new best friend now. Sometimes you need to press it twice, but at least it gets you back to the desktop of the host. I am sticking with 24, way to much improvements with rdp

**Comment by hzdmnl** [comment]
> Ctrl + windows key is my new best friend now. Sometimes you need to press it twice, but at least it gets you back to the desktop of the host. I am sticking with 24, way to much improvements with rdp. Don't press them at the same time, just press ctrl, release, then press windows key.

Thank you. It really works. Going back to Ubuntu 22 is cancelled for now )
I would like to add - that it is **Right CTRL** that needs to be pressed.

**Comment by RobZRH** [comment]
I now use  remmina remote desktop client with ubuntu 24. Same purpose, but more comfortable.

**Comment by akallabeth** [comment]
duplicates https://github.com/FreeRDP/FreeRDP/issues/10683

just as I´ve answered there you´ve already found the shortcut for `right ctrl`

note: best check the help of your application (`man xfreerdp`) or `xfreerdp /help` or whichever binary you use)
we do add stuff mostly there as it always matches the binary and it is hard to keep an online documentation matching all of the various versions shipped with distributions)
