### ISSUE TITLE
Segmentation fault when using Sessionbrooker and DNS round robin

### ISSUE THREAD

**Issue by nidelius** [FreeRDP/FreeRDP#965]
Hello!
We have a server farm with session brooker and DNS round robin.
http://technet.microsoft.com/en-us/library/cc772418(v=ws.10).aspx
## NSLOOKUP

nslookup farm.address.local
Server: X.X.X.2
Address: X.X.X.2#53

Name: farm.address.local
Address: X.X.X.7
Name: farm.address.local
Address: X.X.X.8
Name: farm.address.local
Address: X.X.X.6
Name: farm.address.local
Address: X.X.X.5

We use the following version:
apt-cache showpkg remmina
Package: remmina
## Versions: 1.0.0-1ubuntu6.1

Once connected and I try to reconnect I encounter error below.
## REMMINA in console

connected to farm.address.local:3389
null server certificate
connected to X.X.X.8:3389
null server certificate
WARNING: invalid packet signature
invalid pointer index:8855
WARNING: invalid packet signature
Warning fastpath_recv_update (221): unknown updateCode 0x7
WARNING: invalid packet signature
WARNING: invalid packet signature
Warning fastpath_recv_update (221): unknown updateCode 0xC
invalid offscreen bitmap index: 0x00FF
invalid offscreen bitmap index: 0xFF00
Segmentation fault (core dumped)

If you want me to provide more debug information, please let me know HOW and what you want.

**Comment by trentasis** [comment]
With latest master branch seems to work...

**Comment by nidelius** [comment]
I've been using this switch "/load-balance-info:tsc://SERVER.FARM.COM" to
solve Sessionbrooker with DNS round robin problem
As well as supplying the parameters through GUI as below script.


###############################################

$ cat xfreerdp.config
#Add special config parameters to connect to your server.
#Write it in one line!
#+fonts -sec-nla /rfx /sound:sys:alsa /cert-ignore /size:1280x720
/f /cert-ignore /d:DOMAIN /sec-nla /load-balance-info:tsc://SERVER.FARM.COM
/kbd:0x0000041D


###############################################

/opt/scripts$ cat xfreerdp.sh
#!/bin/sh

config=$(cat /opt/config/xfreerdp.config|grep -v '#'|tr -d '\n')
if [ -z $config ] ; then
        #there is no parameter file specified or is empty, using default:
        config=" +fonts -sec-nla /rfx /sound:sys:alsa /cert-ignore
/size:1280x720 "
fi
# get input data from user username and password by gui to bypass
roundrobin ts redirect problem
# when password passed to first server and session redirected and user
needs to enter credentials second time
user=$(zenity --forms --title="Logon to SERVERFARM" --text="Supply your
username and password to logon to our servers" --add-entry="Username"
--add-password="Password")

server=$(cat /opt/config/xfreerdp.server|grep -v '#'|tr -d '\n')
if [ -z $server ] ; then
        #there is no server configured, quering user:
        server=$(zenity --entry --title="Server address" --text="Enter the
RDP Server name or IP" --entry-text="$(cat /opt/config/xfreerdp.server|grep
-v '#'|tr -d '\n')")
        #set the server ip/name to last entered as default:
        echo $server > /opt/config/xfreerdp.server
fi

#check if server ip/name is passed in cmd line
if [ ! -z $1 ] ; then
        server=$1
fi

###################Starting xFreeRDP
xfreerdp \
$config \
/u:${user%|*} \
/p:${user#*|} \
/v:$server


      --
 ☆     Johan "Jo" Nidelius
 ☼    have a sunshiny day    ☼
  ♥     +46 (0) 730-459949
 ✈    http://www.nidelius.com
      --

**Comment by akallabeth** [comment]
So can we close this issue then?

**Comment by akallabeth** [comment]
Closing due to lack of feedback.
