### ISSUE TITLE
FreeRDP 2.11.3 fail to compile because of typo in unicode.c

### ISSUE THREAD

**Issue by roland65** [FreeRDP/FreeRDP#9651]
Compilation of FreeRDP 2.11.3 fails in Linux because of a typo in file winpr/libwinpr/crt.unicode.c

At line 362, there is:

			targetLength = ucnv_convert("UTF-8", "UTF-16LE", targetStarrt, targetCapacity,

The correct line is:

			targetLength = ucnv_convert("UTF-8", "UTF-16LE", targetStart, targetCapacity,

After fixing this typo, compilation succeeds.

**Comment by pnowack** [comment]
Created https://github.com/FreeRDP/FreeRDP/pull/9652 to address this
