### ISSUE TITLE
xfreerdp: double free or corruption (out)

### ISSUE THREAD

**Issue by nidelius** [FreeRDP/FreeRDP#967]
~$ xfreerdp --version
This is FreeRDP version 1.0.1

~$ xfreerdp -k sv -d domain -u user --no-nla FARM
connected to FARM:3389
connected to X.X.X.8:3389
Incorrect RDP header.
Failed to check FreeRDP file descriptor
**\* glibc detected **\* xfreerdp: double free or corruption (out): 0x00007f86cc04a000 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x7eb96)[0x7f86d4cb6b96]
/usr/lib/libfreerdp-utils.so.1.0(stream_free+0x17)[0x7f86d59647f7]
/usr/lib/libfreerdp-core.so.1.0(transport_free+0x1a)[0x7f86d63cd18a]
/usr/lib/libfreerdp-core.so.1.0(rdp_free+0x24)[0x7f86d63ca054]
/usr/lib/libfreerdp-core.so.1.0(freerdp_context_free+0x24)[0x7f86d63c3694]
/usr/lib/libfreerdp-core.so.1.0(freerdp_free+0xe)[0x7f86d63c371e]
xfreerdp(xfreerdp_run+0x2d7)[0x4105c7]
xfreerdp(thread_func+0xc)[0x41062c]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x7e9a)[0x7f86d4ffee9a]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f86d4d2bcbd]
======= Memory map: ========
00400000-00414000 r-xp 00000000 08:05 8262095                            /usr/bin/xfreerdp
00613000-00614000 r--p 00013000 08:05 8262095                            /usr/bin/xfreerdp
00614000-00695000 rw-p 00014000 08:05 8262095                            /usr/bin/xfreerdp
006a4000-006ea000 rw-p 00000000 00:00 0                                  [heap]
7f86cc000000-7f86cc0c7000 rw-p 00000000 00:00 0 
7f86cc0c7000-7f86d0000000 ---p 00000000 00:00 0 
7f86d2085000-7f86d209a000 r-xp 00000000 08:05 6819807                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f86d209a000-7f86d2299000 ---p 00015000 08:05 6819807                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f86d2299000-7f86d229a000 r--p 00014000 08:05 6819807                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f86d229a000-7f86d229b000 rw-p 00015000 08:05 6819807                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f86d229b000-7f86d22b3000 r-xp 00000000 08:05 6820005                    /lib/x86_64-linux-gnu/libresolv-2.15.so
7f86d22b3000-7f86d24b3000 ---p 00018000 08:05 6820005                    /lib/x86_64-linux-gnu/libresolv-2.15.so
7f86d24b3000-7f86d24b4000 r--p 00018000 08:05 6820005                    /lib/x86_64-linux-gnu/libresolv-2.15.so
7f86d24b4000-7f86d24b5000 rw-p 00019000 08:05 6820005                    /lib/x86_64-linux-gnu/libresolv-2.15.so
7f86d24b5000-7f86d24b7000 rw-p 00000000 00:00 0 
7f86d24b7000-7f86d24be000 r-xp 00000000 08:05 6820017                    /lib/x86_64-linux-gnu/libnss_dns-2.15.so
7f86d24be000-7f86d26bd000 ---p 00007000 08:05 6820017                    /lib/x86_64-linux-gnu/libnss_dns-2.15.so
7f86d26bd000-7f86d26be000 r--p 00006000 08:05 6820017                    /lib/x86_64-linux-gnu/libnss_dns-2.15.so
7f86d26be000-7f86d26bf000 rw-p 00007000 08:05 6820017                    /lib/x86_64-linux-gnu/libnss_dns-2.15.so
7f86d26bf000-7f86d26c1000 r-xp 00000000 08:05 6815802                    /lib/libnss_mdns4_minimal.so.2
7f86d26c1000-7f86d28c0000 ---p 00002000 08:05 6815802                    /lib/libnss_mdns4_minimal.so.2
7f86d28c0000-7f86d28c1000 r--p 00001000 08:05 6815802                    /lib/libnss_mdns4_minimal.so.2
7f86d28c1000-7f86d28c2000 rw-p 00002000 08:05 6815802                    /lib/libnss_mdns4_minimal.so.2
7f86d28c2000-7f86d28ce000 r-xp 00000000 08:05 6820010                    /lib/x86_64-linux-gnu/libnss_files-2.15.so
7f86d28ce000-7f86d2acd000 ---p 0000c000 08:05 6820010                    /lib/x86_64-linux-gnu/libnss_files-2.15.so
7f86d2acd000-7f86d2ace000 r--p 0000b000 08:05 6820010                    /lib/x86_64-linux-gnu/libnss_files-2.15.so
7f86d2ace000-7f86d2acf000 rw-p 0000c000 08:05 6820010                    /lib/x86_64-linux-gnu/libnss_files-2.15.so
7f86d2acf000-7f86d2ad0000 ---p 00000000 00:00 0 
7f86d2ad0000-7f86d32d0000 rw-p 00000000 00:00 0 
7f86d32d0000-7f86d359e000 r--p 00000000 08:05 8267108                    /usr/lib/locale/locale-archive
7f86d359e000-7f86d35a3000 r-xp 00000000 08:05 8268298                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f86d35a3000-7f86d37a2000 ---p 00005000 08:05 8268298                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f86d37a2000-7f86d37a3000 r--p 00004000 08:05 8268298                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f86d37a3000-7f86d37a4000 rw-p 00005000 08:05 8268298                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f86d37a4000-7f86d37a6000 r-xp 00000000 08:05 8268279                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f86d37a6000-7f86d39a5000 ---p 00002000 08:05 8268279                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f86d39a5000-7f86d39a6000 r--p 00001000 08:05 8268279                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f86d39a6000-7f86d39a7000 rw-p 00002000 08:05 8268279                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f86d39a7000-7f86d39bd000 r-xp 00000000 08:05 6819899                    /lib/x86_64-linux-gnu/libz.so.1.2.3.4
7f86d39bd000-7f86d3bbc000 ---p 00016000 08:05 6819899                    /lib/x86_64-linux-gnu/libz.so.1.2.3.4
7f86d3bbc000-7f86d3bbd000 r--p 00015000 08:05 6819899                    /lib/x86_64-linux-gnu/libz.so.1.2.3.4
7f86d3bbd000-7f86d3bbe000 rw-p 00016000 08:05 6819899                    /lib/x86_64-linux-gnu/libz.so.1.2.3.4
7f86d3bbe000-7f86d3bdb000 r-xp 00000000 08:05 8259857                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f86d3bdb000-7f86d3dda000 ---p 0001d000 08:05 8259857                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f86d3dda000-7f86d3ddb000 r--p 0001c000 08:05 8259857                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f86d3ddb000-7f86d3ddc000 rw-p 0001d000 08:05 8259857                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f86d3ddc000-7f86d3dff000 r-xp 00000000 08:05 8267531                    /usr/lib/x86_64-linux-gnu/libxkbfile.so.1.0.2
7f86d3dff000-7f86d3ffe000 ---p 00023000 08:05 8267531                    /usr/lib/x86_64-linux-gnu/libxkbfile.so.1.0.2
7f86d3ffe000-7f86d3fff000 r--p 00022000 08:05 8267531                    /usr/lib/x86_64-linux-gnu/libxkbfile.so.1.0.2
7f86d3fff000-7f86d4000000 rw-p 00023000 08:05 8267531                    /usr/lib/x86_64-linux-gnu/libxkbfile.so.1.0.2
7f86d4000000-7f86d4002000 r-xp 00000000 08:05 6816992                    /lib/x86_64-linux-gnu/libdl-2.15.so
7f86d4002000-7f86d4202000 ---p 00002000 08:05 6816992                    /lib/x86_64-linux-gnu/libdl-2.15.so
7f86d4202000-7f86d4203000 r--p 00002000 08:05 6816992                    /lib/x86_64-linux-gnu/libdl-2.15.so
7f86d4203000-7f86d4204000 rw-p 00003000 08:05 6816992                    /lib/x86_64-linux-gnu/libdl-2.15.so
7f86d4204000-7f86d43a3000 r-xp 00000000 08:05 6816893                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f86d43a3000-7f86d45a2000 ---p 0019f000 08:05 6816893                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f86d45a2000-7f86d45bd000 r--p 0019e000 08:05 6816893                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f86d45bd000-7f86d45c8000 rw-p 001b9000 08:05 6816893                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f86d45c8000-7f86d45cc000 rw-p 00000000 00:00 0 
7f86d45cc000-7f86d461e000 r-xp 00000000 08:05 6815773                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f86d461e000-7f86d481e000 ---p 00052000 08:05 6815773                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f86d481e000-7f86d4821000 r--p 00052000 08:05 6815773                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f86d4821000-7f86d4827000 rw-p 00055000 08:05 6815773                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7f86d4827000-7f86d4828000 rw-p 00000000 00:00 0 
7f86d4828000-7f86d482d000 r-xp 00000000 08:05 8268306                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f86d482d000-7f86d4a2c000 ---p 00005000 08:05 8268306                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f86d4a2c000-7f86d4a2d000 r--p 00004000 08:05 8268306                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f86d4a2d000-7f86d4a2e000 rw-p 00005000 08:05 8268306                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f86d4a2e000-7f86d4a37000 r-xp 00000000 08:05 8268332                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f86d4a37000-7f86d4c36000 ---p 00009000 08:05 8268332                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f86d4c36000-7f86d4c37000 r--p 00008000 08:05 8268332                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f86d4c37000-7f86d4c38000 rw-p 00009000 08:05 8268332                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f86d4c38000-7f86d4ded000 r-xp 00000000 08:05 6820000                    /lib/x86_64-linux-gnu/libc-2.15.so
7f86d4ded000-7f86d4fec000 ---p 001b5000 08:05 6820000                    /lib/x86_64-linux-gnu/libc-2.15.so
7f86d4fec000-7f86d4ff0000 r--p 001b4000 08:05 6820000                    /lib/x86_64-linux-gnu/libc-2.15.so
7f86d4ff0000-7f86d4ff2000 rw-p 001b8000 08:05 6820000                    /lib/x86_64-linux-gnu/libc-2.15.so
7f86d4ff2000-7f86d4ff7000 rw-p 00000000 00:00 0 
7f86d4ff7000-7f86d500f000 r-xp 00000000 08:05 6820002                    /lib/x86_64-linux-gnu/libpthread-2.15.so
7f86d500f000-7f86d520e000 ---p 00018000 08:05 6820002                    /lib/x86_64-linux-gnu/libpthread-2.15.so
7f86d520e000-7f86d520f000 r--p 00017000 08:05 6820002                    /lib/x86_64-linux-gnu/libpthread-2.15.so
7f86d520f000-7f86d5210000 rw-p 00018000 08:05 6820002                    /lib/x86_64-linux-gnu/libpthread-2.15.so
7f86d5210000-7f86d5214000 rw-p 00000000 00:00 0 
7f86d5214000-7f86d5222000 r-xp 00000000 08:05 8263260                    /usr/lib/libfreerdp-codec.so.1.0.1
7f86d5222000-7f86d5421000 ---p 0000e000 08:05 8263260                    /usr/lib/libfreerdp-codec.so.1.0.1
7f86d5421000-7f86d5422000 r--p 0000d000 08:05 8263260                    /usr/lib/libfreerdp-codec.so.1.0.1
7f86d5422000-7f86d5423000 rw-p 0000e000 08:05 8263260                    /usr/lib/libfreerdp-codec.so.1.0.1
7f86d5423000-7f86d5428000 r-xp 00000000 08:05 8264193                    /usr/lib/libfreerdp-cache.so.1.0.1
7f86d5428000-7f86d5627000 ---p 00005000 08:05 8264193                    /usr/lib/libfreerdp-cache.so.1.0.1
7f86d5627000-7f86d5628000 r--p 00004000 08:05 8264193                    /usr/lib/libfreerdp-cache.so.1.0.1
7f86d5628000-7f86d5629000 rw-p 00005000 08:05 8264193                    /usr/lib/libfreerdp-cache.so.1.0.1
7f86d5629000-7f86d5758000 r-xp 00000000 08:05 8268275                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f86d5758000-7f86d5958000 ---p 0012f000 08:05 8268275                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f86d5958000-7f86d5959000 r--p 0012f000 08:05 8268275                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f86d5959000-7f86d595d000 rw-p 00130000 08:05 8268275                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f86d595d000-7f86d5969000 r-xp 00000000 08:05 8264191                    /usr/lib/libfreerdp-utils.so.1.0.1
7f86d5969000-7f86d5b68000 ---p 0000c000 08:05 8264191                    /usr/lib/libfreerdp-utils.so.1.0.1
7f86d5b68000-7f86d5b69000 r--p 0000b000 08:05 8264191                    /usr/lib/libfreerdp-utils.so.1.0.1
7f86d5b69000-7f86d5b6a000 rw-p 0000c000 08:05 8264191                    /usr/lib/libfreerdp-utils.so.1.0.1
7f86d5b6a000-7f86d5b6e000 r-xp 00000000 08:05 8264190                    /usr/lib/libfreerdp-channels.so.1.0.1
7f86d5b6e000-7f86d5d6d000 ---p 00004000 08:05 8264190                    /usr/lib/libfreerdp-channels.so.1.0.1
7f86d5d6d000-7f86d5d6e000 r--p 00003000 08:05 8264190                    /usr/lib/libfreerdp-channels.so.1.0.1
7f86d5d6e000-7f86d5d6f000 rw-p 00004000 08:05 8264190                    /usr/lib/libfreerdp-channels.so.1.0.1
7f86d5d6f000-7f86d5d72000 r-xp 00000000 08:05 8263261                    /usr/lib/libfreerdp-rail.so.1.0.1
7f86d5d72000-7f86d5f71000 ---p 00003000 08:05 8263261                    /usr/lib/libfreerdp-rail.so.1.0.1
7f86d5f71000-7f86d5f72000 r--p 00002000 08:05 8263261                    /usr/lib/libfreerdp-rail.so.1.0.1
7f86d5f72000-7f86d5f73000 rw-p 00003000 08:05 8263261                    /usr/lib/libfreerdp-rail.so.1.0.1
7f86d5f73000-7f86d5f82000 r-xp 00000000 08:05 8264194                    /usr/lib/libfreerdp-kbd.so.1.0.1
7f86d5f82000-7f86d6181000 ---p 0000f000 08:05 8264194                    /usr/lib/libfreerdp-kbd.so.1.0.1
7f86d6181000-7f86d6187000 r--p 0000e000 08:05 8264194                    /usr/lib/libfreerdp-kbd.so.1.0.1
7f86d6187000-7f86d6188000 rw-p 00014000 08:05 8264194                    /usr/lib/libfreerdp-kbd.so.1.0.1
7f86d6188000-7f86d6189000 rw-p 00000000 00:00 0 
7f86d6189000-7f86d619e000 r-xp 00000000 08:05 8264195                    /usr/lib/libfreerdp-gdi.so.1.0.1
7f86d619e000-7f86d639d000 ---p 00015000 08:05 8264195                    /usr/lib/libfreerdp-gdi.so.1.0.1
7f86d639d000-7f86d639e000 r--p 00014000 08:05 8264195                    /usr/lib/libfreerdp-gdi.so.1.0.1
7f86d639e000-7f86d639f000 rw-p 00015000 08:05 8264195                    /usr/lib/libfreerdp-gdi.so.1.0.1
7f86d639f000-7f86d63e1000 r-xp 00000000 08:05 8264192                    /usr/lib/libfreerdp-core.so.1.0.1
7f86d63e1000-7f86d65e1000 ---p 00042000 08:05 8264192                    /usr/lib/libfreerdp-core.so.1.0.1
7f86d65e1000-7f86d65e2000 r--p 00042000 08:05 8264192                    /usr/lib/libfreerdp-core.so.1.0.1
7f86d65e2000-7f86d65e3000 rw-p 00043000 08:05 8264192                    /usr/lib/libfreerdp-core.so.1.0.1
7f86d65e3000-7f86d65e8000 r-xp 00000000 08:05 8268340                    /usr/lib/x86_64-linux-gnu/libXv.so.1.0.0
7f86d65e8000-7f86d67e7000 ---p 00005000 08:05 8268340                    /usr/lib/x86_64-linux-gnu/libXv.so.1.0.0
7f86d67e7000-7f86d67e8000 r--p 00004000 08:05 8268340                    /usr/lib/x86_64-linux-gnu/libXv.so.1.0.0
7f86d67e8000-7f86d67e9000 rw-p 00005000 08:05 8268340                    /usr/lib/x86_64-linux-gnu/libXv.so.1.0.0
7f86d67e9000-7f86d67f2000 r-xp 00000000 08:05 8268290                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f86d67f2000-7f86d69f1000 ---p 00009000 08:05 8268290                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f86d69f1000-7f86d69f2000 r--p 00008000 08:05 8268290                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f86d69f2000-7f86d69f3000 rw-p 00009000 08:05 8268290                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f86d69f3000-7f86d6a03000 r-xp 00000000 08:05 8268302                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f86d6a03000-7f86d6c02000 ---p 00010000 08:05 8268302                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f86d6c02000-7f86d6c03000 r--p 0000f000 08:05 8268302                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f86d6c03000-7f86d6c04000 rw-p 00010000 08:05 8268302                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f86d6c04000-7f86d6c06000 r-xp 00000000 08:05 8268318                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7f86d6c06000-7f86d6e05000 ---p 00002000 08:05 8268318                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7f86d6e05000-7f86d6e06000 r--p 00001000 08:05 8268318                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7f86d6e06000-7f86d6e07000 rw-p 00002000 08:05 8268318                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7f86d6e07000-7f86d6e29000 r-xp 00000000 08:05 6820014                    /lib/x86_64-linux-gnu/ld-2.15.so
7f86d6ffa000-7f86d7006000 rw-p 00000000 00:00 0 
7f86d7025000-7f86d7029000 rw-p 00000000 00:00 0 
7f86d7029000-7f86d702a000 r--p 00022000 08:05 6820014                    /lib/x86_64-linux-gnu/ld-2.15.so
7f86d702a000-7f86d702c000 rw-p 00023000 08:05 6820014                    /lib/x86_64-linux-gnu/ld-2.15.so
7fffcab45000-7fffcab66000 rw-p 00000000 00:00 0                          [stack]
7fffcabff000-7fffcac00000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

**Comment by gnshkl1** [comment]
@nidelius can you verify this issue is fixed or not in Freerdp rc3
