### ISSUE TITLE
nothing provides librdtk0.so.0()(64bit)

### ISSUE THREAD

**Issue by aebenjam** [FreeRDP/FreeRDP#9671]
Install of freerdp-nightly.x86_64:
Version      : 3.0
Release      : 0+0~20231206033814.1484~1.gitdd56308bd
from the repo https://pub.freerdp.com/repositories/rpm/fedora/fedora-$releasever/freerdp-nightly/
on Fedora 38 produces the error:

Error: 
 Problem: conflicting requests
  - nothing provides librdtk0.so.0()(64bit) needed by freerdp-nightly-3.0-0+0~20231206033814.1484~1.gitdd56308bd.x86_64 from freerdp-nightly

**Comment by elTorres** [comment]
The same problem occurs on Fedora 39

```
dnf install freerdp-nightly
Last metadata expiration check: 0:06:21 ago on vie 05 abr 2024 09:51:06.
Error: 
 Problem: conflicting requests
  - nothing provides librdtk0.so.0()(64bit) needed by freerdp-nightly-3.0-0+0~20231205033814.1483~1.gitdcefd4f86.x86_64 from freerdp-nightly
  - nothing provides librdtk0.so.0()(64bit) needed by freerdp-nightly-3.0-0+0~20231206033814.1484~1.gitdd56308bd.x86_64 from freerdp-nightly
(try to add '--skip-broken' to skip uninstallable packages)
```
