### ISSUE TITLE
When playing YouTube videos, the memory usage keeps increasing. - iFreeRDP

### ISSUE THREAD

**Issue by YKProject** [FreeRDP/FreeRDP#9672]
When playing YouTube videos on iFreeRDP (version 2.11.2), I noticed that the memory usage keeps increasing.

Memory usage:

Immediately after video playback: 123.5MB
After 1 hour: 261.6MB (+138.1MB)
After 2 hours: 373.1MB (+111.5MB)
After 3 hours: 479.0MB (+105.9MB)
After 4 hours: 606.8MB (+127.8MB)

I used Xcode's instruments to check the memory allocation and identified some areas of concern.
It seems that when the cinvalid array becomes full, its capacity is doubled. 
You can refer to the following URL for more details: https://github.com/FreeRDP/FreeRDP/blob/2.11.2/libfreerdp/gdi/region.c#L625

The data is then stored in the realloc area of the cinvalid array. 
I believe that as the capacity of cinvalid increases, the memory usage also increases.

Could you please consider addressing this issue and making the necessary corrections?

**Comment by akallabeth** [comment]
pull requests welcome, but `iFreeRDP` is not actively developed.

**Comment by akallabeth** [comment]
ok, you´re lucky, it does not require client changes for this to be fixed in a generic way.

**Comment by YKProject** [comment]
@akallabeth 
With the resolution of #9679, this event no longer occurs. 
Thank you for your prompt response.
