### ISSUE TITLE
Command -decorations not working

### ISSUE THREAD

**Issue by pes00** [FreeRDP/FreeRDP#9673]
**Describe the bug**
With FreeRDP 3.0 the command "-decorations" doesn't work, it has no effect

**To Reproduce**
Try connecting to a server with the "-decorations" command

**Expected behavior**
Disable Window decorations

**Application details**
* FreeRDP version 3.0
* Command line used: -decorations
* OS version connecting: Windows 2022, Windows 11, Windows 10

**Environment (please complete the following information):**
 - OS: Raspberry Pi OS
 - Version/Distribution: Debian 11
 - Architecture: arm64
 - Install with Flatpak

**Comment by akallabeth** [comment]
well, that is a flag that needs to be honored by your server.

**Comment by pes00** [comment]
Thanks for the reply but sorry, I don't understand. Using Freerdp version 2.11.2, with the same parameters, the command takes effect. How could this not be a version 3.0 bug? For my part, the server is the same...

**Comment by akallabeth** [comment]
@pes00 which opions do you use exactly?
the newer version supports newer protocol which might change behaviour according to that.

**Comment by pes00** [comment]
The command is:
flatpak run com.freerdp.FreeRDP /u:utente /p:password /d:domian /v:10.10.10.10 -decorations

With FreeRDP 2.11.2 is all ok
With FreeRDP 3.0 in KO

**Comment by akallabeth** [comment]
@pes00 ok, I see.
sorry, did mix this up, `-decorations` disables the client fullscreen window decorations, not the remote os decorations

**Comment by akallabeth** [comment]
@pes00 ok, fixed that, will be part of next release.

**Comment by pes00** [comment]
Thank you very very much

**Comment by pes00** [comment]
I tried the new version 3.1 but there are still a problem
![FreeRDP_2 11 2_OK1](https://github.com/FreeRDP/FreeRDP/assets/73900814/1b4b1d2c-92fa-4daf-a4f0-277033555d9c)
![FreeRDP_2 11 2_OK2](https://github.com/FreeRDP/FreeRDP/assets/73900814/2836bec9-fcd2-45f7-83f9-81b32c81e122)

With version 2.11.2, the window is correctly sized, considering the taskbar of the operating system from which freerdp is executed, as visible in the attached photos

![FreeRDP_3 1_KO1](https://github.com/FreeRDP/FreeRDP/assets/73900814/fa8e39ea-b589-4a49-9e40-d9188f6b230d)
![FreeRDP_3 1_KO2](https://github.com/FreeRDP/FreeRDP/assets/73900814/e7352164-7c78-4612-a6c9-89322bcc49a8)

With version 3.1, the window is partially covered by the taskbar of the operating system from which freerdp is executed, as visible in the attached photos

**Comment by akallabeth** [comment]
@pes00 window placement is up to the window manager? don´t see how this is a freerdp bug ;)

**Comment by pes00** [comment]
Sorry, you're absolutely right
In this case the difference is given by the "/workarea" option
So, in version 2.11.2 the command:
`flatpak run com.freerdp.FreeRDP /u:utente /p:password /d:domain /v:10.10.10.10 -decorations /workarea`
size the window correctly while in 3.1 it doesn't.
Do I have to open a new report or can I continue here?

**Comment by akallabeth** [comment]
@pes00 ah, ok, that explains it.
`sdl-freerdp` does not yet respect that, so yes, please open a bug for that.
