### ISSUE TITLE
Cursor too big when using scaling

### ISSUE THREAD

**Issue by manio** [FreeRDP/FreeRDP#9687]
**Describe the bug**
I was searching for this issue here but cannot find this problem so I am creating a new one.
I am using HiDPI/4K display to work (Linux host). I am connecting to windows machines (mostly Win10) using `xfreerdp`.

Because of this I am using `/scale:180` parameter which is the max DPI I can provide because of RDP protocol limitation.

The remote display looks perfectly fine but the problem is with the mouse cursor size.
I am pasting the images (from another thread) to visualize the problem:

This is the "big" cursor (how I see it from xfreerdp):
![image](https://github.com/FreeRDP/FreeRDP/assets/583157/e19947d4-183e-4a16-bc01-773b0b5f5458)
and this is normal cursor (running localy on windows):
![image](https://github.com/FreeRDP/FreeRDP/assets/583157/b38f9863-e98f-4960-a04b-08db16aecfbe)
This affects all cursors (normal, hourglass for waiting, text selection etc).

I found similar report here for Remmina:
https://gitlab.com/Remmina/Remmina/-/issues/1878
and this lead to a microsoft forum:
https://social.technet.microsoft.com/Forums/ie/en-US/a8b5ce47-46d5-4f78-8f1c-aa850049d14c/large-pointer-size-using-rdp?forum=winRDc

According to microsoft:
_This is totally a bug with the RDP client: the cursor should be scaled to match the remote desktop's resolution but isn't._

_RDP Mac thinks in terms of logical resolution, so it thinks the RMBP's resolution is 1440x900, which is fine, but when you run the remote session at 2880x1800, everything gets scaled back down EXCEPT the mouse cursor, which is a bug._

_So in short, when "scaling" is enabled, the mouse cursor needs to be scaled down just like everything else, but isn't._

**Application details**
* FreeRDP version (`xfreerdp /version`)
This is FreeRDP version 3.0.0-dev5 (a927bb8b6)
* Output of `xfreerdp /buildconfig`
```
This is FreeRDP version 3.0.0-dev5 (a927bb8b6)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_ICU=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PCSC=ON WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=ON WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=ON WITH_SWSCALE=ON WITH_SYSTEMD=ON WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=ON WITH_WEBVIEW_QT=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          Release
CFLAGS:              -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer
Compiler:            GNU, 13.2.1
Target architecture: x64
```
**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]
Linux
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]
Arch
 - Architecture: [amd64, arm]:
amd64

**Comment by akallabeth** [comment]
@manio 
1. do you have the same scaling settings on your windows?
2. how big is the mouse cursor for a `mstsc` connection with the same scaling settings?

background:
only for `/smart-sizing` we scale the cursor locally, in case of `/scale, /scale-desktop, /scale-device` options the size of the mouse cursor is determined by the server
(the mac bug you reference is due to mac scaling the output too but forgets the cursor which we do not do)

**Comment by manio** [comment]
1. I didn't touch any scalling setting on remote windows. I can see that this remote windows10 is able to detect this somehow automatically according to the client (FullHD laptop/4K laptop/my linux box).
It is telling me in the control panel/display settings that:
_The display settings can't be changed from a remote session_
like here: https://user-images.githubusercontent.com/129165/31641564-4b93cccc-b331-11e7-9b35-a4bfd70a521d.PNG

2. This is from `mstsc`: (sorry for the quality but I didn't want to waste my time how to make a screenshot with cursor included in windows):
![image](https://github.com/FreeRDP/FreeRDP/assets/583157/cd76faac-abb7-4c39-a88a-173080cb440d)

while this is from `xfreerdp` / Arch Linux:
![image](https://github.com/FreeRDP/FreeRDP/assets/583157/f9784f96-4f63-4847-b509-efb03e190602)

**Comment by manio** [comment]
@akallabeth 
If we have the scaling code for `/smart-sizing` so maybe I could force it somehow?
Do you think it would work? Any tips for this?

**Comment by akallabeth** [comment]
@manio you misunderstood.
the cursor might actually be of correct size.
your screenshots are not helpful, it would be interesting how they are against the UI elements of the desktop (to see the scaling applied)

like here, I´ve created a session against windows 10 with `notepad` as an example:
![grafik](https://github.com/FreeRDP/FreeRDP/assets/3472254/53839704-2627-4851-bcf8-05c624d99205)

as you can see the cursor matches the expectations.

so, either you have the wrong cursor theme remote (you can switch them to big?) or something else is off with your command line.
(might help if you add it here)

**Comment by akallabeth** [comment]
addendum: the mouse pointer size settings stay from one RDP connection to another one.
that is the only way I can get a cursor that is too large.

**Comment by manio** [comment]
Sure, here is the screenshot with cursor size against a notepad.exe:
![image](https://github.com/FreeRDP/FreeRDP/assets/583157/c765b30f-92c3-40b8-a20b-f3626ddcf200)
Command line:
```xfreerdp +auto-reconnect +clipboard /cert:ignore /dynamic-resolution /prevent-session-lock -grab-keyboard /sound /v:XXXXX /kbd:layout:0x00000415 /scale:180```

**Comment by manio** [comment]
I did another test: moved a freerdp window from HiDPI display to a "normal" small one monitor. The result is:
![image](https://github.com/FreeRDP/FreeRDP/assets/583157/c021d996-be66-4f81-94ca-83b0d7f95879)
So it seems perfectly fine (comparing to UI elements, btw the screenshot is x2). I am confused.

**Comment by akallabeth** [comment]
@manio check your cursor size settings `from within the RDP connection`
this is a thing you can adjust `on your windows RDP server`

this is the menu:
![grafik](https://github.com/FreeRDP/FreeRDP/assets/3472254/b18cc953-21db-4040-9d72-917bb3d1f1b8)

**Comment by manio** [comment]
@akallabeth 
Please look above ^^^

**Comment by manio** [comment]
OK. I think I found the problem.
I was using Xorg unscaled (https://wiki.hyprland.org/Configuring/XWayland/):
```
# unscale XWayland
xwayland {
  force_zero_scaling = true
}
```
And also scaling was enabled for this specific monitor (scale set to 2.0). When I disabled this scaling then the cursor went back to normal. So this is not a freerdp problem but XWayland or Hyprland which is doing this.

I'm sorry for wasting your time. I was pretty sure it was freerdp. Closing.

**Comment by manio** [comment]
For the reference: problem fixed in https://github.com/FreeRDP/FreeRDP/pull/9715

**Comment by grapereader** [comment]
Not sure if this is actually fixed... I have this issue using KDE Plasma + Wayland + Remmina + FreeRDP 3.4.0 on EndeavorOS

KDE desktop scaling set to 150%
Remote desktop scaling set to 150%

![scrn-cropped](https://github.com/FreeRDP/FreeRDP/assets/1329614/1d0fdbc3-d157-448b-8a0d-eed338567d88)
