### ISSUE TITLE
Shadow mouse pointer with Azure+valgrind

### ISSUE THREAD

**Issue by hardening** [FreeRDP/FreeRDP#9711]
When running xfreerdp with valgrind and connecting to an Azure VM, it seems like the mouse is drawn both client and server side. Perhaps it has to do with the MousePointer channel that we don't implement yet.

This is with last master (ad0de52ab64dbfae8c9436b9e193ac615de3fff8).

**Comment by akallabeth** [comment]
@hardening by any chance, is the relative mouse option in use with that setup?
This sounds a lot like it (and with the slowdown coming along with valgrind it would show even more)

**Comment by akallabeth** [comment]
ok, this most likely is the relative mouse option and has nothing to do with valgrind iteslf.
