### ISSUE TITLE
3.1. does not compile -DWITH_UNICODE_BUILTIN=ON -DWITH_OPUS=OFF

### ISSUE THREAD

**Issue by sfs-pra** [FreeRDP/FreeRDP#9716]
-DWITH_UNICODE_BUILTIN=ON -DWITH_OPUS=ON - compiled 
Other options:
  local _cmake_options=(
    -DCMAKE_INSTALL_PREFIX="/usr"
    -DCMAKE_INSTALL_LIBDIR="/usr/lib"
    # -DCMAKE_BUILD_TYPE=None
    -DCMAKE_SKIP_INSTALL_RPATH=ON
    -DPROXY_PLUGINDIR="/usr/lib/freerdp3/server/proxy/plugins"
-DWITH_DSP_FFMPEG=OFF
-DWITH_FFMPEG=OFF
-DWITH_PULSE=OFF
    -DWITH_CUPS=ON
    -DWITH_PCSC=ON
-DWITH_ICU=OFF
    -DWITH_JPEG=ON
    -DWITH_SERVER=ON
-DWITH_SWSCALE=OFF
    -DWITH_CHANNELS=ON
    -DWITH_CLIENT_CHANNELS=ON
    -DWITH_SERVER_CHANNELS=ON
    -DCHANNEL_URBDRC_CLIENT=ON
-DWITH_FUSE=OFF.
-DWITH_UNICODE_BUILTIN=ON -DWITH_OPENSC_PKCS11_LINKED=OFF
    -Wno-dev
    -B build
    -S "$_pkgsrc"

    -DCMAKE_BUILD_TYPE=Release
    -DWITH_X11=ON
    -DWITH_WAYLAND=ON
-DWITH_OPUS=OFF

**Comment by akallabeth** [comment]
it compiles.
if you expect a more detailed answer read the issue template again and provide information.
