### ISSUE TITLE
freerdp build android client base on v3.1.0 was collapsed at gradle build task "Task :freeRDPCore:buildCMakeDebug[arm64-v8a] FAILED"

### ISSUE THREAD

**Issue by gm7777777** [FreeRDP/FreeRDP#9734]
I download the version 3.1.0 FreeRDP ,and following the readme using script 'android-build-freerdp.sh' building android client work project 'Studio'.I also follow the recommand [https://github.com/freeRDP/freeRDP/wiki/Compilation#android-specifics](url) meanwhile I was building the lib with arm64-v8a armeabi-v7a x86 x86_64 version. but when I debug the project with my phone ,my gralde still was collasped at the task "Task :freeRDPCore:buildCMakeDebug[arm64-v8a] FAILED" and it show the log "C/C++: ninja: error: 'E:/xxxx/Studio_FreeRDP/freeRDPCore/src/main/jniLibs/arm64-v8a/libfreerdp3.so', needed by 'E:/xxxx/Studio_FreeRDP/freeRDPCore/build/intermediates/cxx/Debug/2p484y4p/obj/arm64-v8a/libfreerdp-android.so', missing and no known rule to make it".
<img width="904" alt="捕获" src="https://github.com/FreeRDP/FreeRDP/assets/3497095/c0f54b97-5e7f-4d85-8a3f-075422600c83">
 it seem the project can not build the file libfreerdp-android.so. please give me a favor to check the issue.It alsow occur at Ubuntu system.
and I changed the version to 2.11.4 ,everything is ok, gradle is ok,but I cannot debug the app. the debug program will be shutdown(Disconnected) immediately when the app set up on my phone . the log show 
<img width="800" alt="捕获" src="https://github.com/FreeRDP/FreeRDP/assets/3497095/a31f90e0-94e0-4951-a307-ebb3890139b3">

 @akallabeth

**Comment by akallabeth** [comment]
@gm7777777 while I´ve found a few glitches with current build (see https://github.com/FreeRDP/FreeRDP/pull/9735 ) the native libraries are build just as expected and gradle works with android studio. (debian 12, android studio from flathub)

if you try building under windows (I assume that is the case from the paths I can see) then you´re on your own as we do not support that configuration. (feel free to debug and fix it, we´re accepting pull requests)

if you think there is still something wrong, please provide some more details, as you only post the `error something failed, see above for details` messages without the `above` ;)
