### ISSUE TITLE
Bypass authentication dialog when passing credentials on command line

### ISSUE THREAD

**Issue by LinAGKar** [FreeRDP/FreeRDP#9743]
**Is your feature request related to a problem? Please describe.**
When sdl-freerdp is launched, it shows a dialog for user credentials, added in https://github.com/FreeRDP/FreeRDP/issues/9079. However, this is shown even if the credentials are already passed on the command line, requiring a needless extra click, on "accept".

**Describe the solution you'd like**
It would be nice if the dialog could be bypassed. Either by not automatically no showing it when username and password are passed on command line, or by bypassing it with a separate command line switch.

**Comment by akallabeth** [comment]
@LinAGKar ok, from the chat I assumed you were referring to the `connection dialog`?
there is something else going on then, I can fully connect without the `authentication dialog` to show up.

can you add a log from such a connection (`/log-level:debug` or `/log-level:trace`)?

**Comment by LinAGKar** [comment]
[sdl-freerdp.log](https://github.com/FreeRDP/FreeRDP/files/13862016/sdl-freerdp.log)

This authentication dialog (username, domain, password) is the only dialog I'm getting. I'm using the flatpak, which is on 3.0, does that have the connection dialog?

**Comment by akallabeth** [comment]
ah :)
that specific bug was already fixed with 3.1.0 release 8df97272b7
