### ISSUE TITLE
[sdl] Command "/workarea" does not size correctly

### ISSUE THREAD

**Issue by pes00** [FreeRDP/FreeRDP#9749]
Describe the bug
With FreeRDP 3.1 the command "/workarea" does not size correctly

To Reproduce
Try connecting to a server with the "/workarea" command

Expected behavior
Use available work area

Application details

FreeRDP version 3.1
Command line used: /workarea
OS version connecting: Windows 2022, Windows 11, Windows 10
Environment (please complete the following information):

OS: Raspberry Pi OS
Version/Distribution: Debian 11
Architecture: arm64
Install with Flatpak

![FreeRDP_2 11 2_OK1](https://github.com/FreeRDP/FreeRDP/assets/73900814/0ec4bb2d-c743-487a-84bb-870087d7f805)
![FreeRDP_2 11 2_OK2](https://github.com/FreeRDP/FreeRDP/assets/73900814/f8bb1e3d-4a44-4634-b07b-57b6845c20fb)

With version 2.11.2, the window is correctly sized, considering the taskbar of the operating system from which freerdp is executed, as visible in the attached photos

![FreeRDP_3 1_KO1](https://github.com/FreeRDP/FreeRDP/assets/73900814/9d9d33bc-1213-4a54-9548-40d2639fbed0)
![FreeRDP_3 1_KO2](https://github.com/FreeRDP/FreeRDP/assets/73900814/e3cf0754-a04d-484e-82b8-08b28787cc24)

With version 3.1, the window is partially covered by the taskbar of the operating system from which freerdp is executed, as visible in the attached photos

**Comment by akallabeth** [comment]
1. this is a bug in `SDL2` with `X11` .
2. The resizing is correct, but the window position is moved down after initially being at the right coordinates.
3. does not happen with `SDL_VIDEODRIVER=wayland` set.

**Comment by pes00** [comment]
Sorry, but how can I SDL_VIDEODRIVER=wayland set?

**Comment by akallabeth** [comment]
@pes00 `SDL_VIDEODRIVER=wayland sdl-freerdp /v:...`

**Comment by pes00** [comment]
With flatpak I try command
`flatpak run --command=SDL_VIDEODRIVER=wayland --command=sdl-freerdp com.freerdp.FreeRDP /u:user /p:password /d:domain /v:111.111.111.111 /workarea -decorations`

but the original problem remains

**Comment by akallabeth** [comment]
@pes00 did just run `flatpak run com.freerdp.FreeRDP /v:host /u:user /p:pwd /workarea -decorations` on my debian 12/gnome env and it works as expected.
(that is, no window decorations and the size of the window the size of the screen without the gnome top bar)

hint: with `flatpak` you already use wayland, no need to set the variable there.

**Comment by pes00** [comment]
Thank you again for your help. I'm going crazy with this setup.
I did various tests which I am going to document. In all the cases below, the command I run is always the same:
`flatpak run com.freerdp.FreeRDP /u:user /p:pwd /d:domain /v:111.111.111.111 -decorations /workarea`

This is the setup that works perfectly. Raspberry pi with bullseye OS and freerdp version 2.11.2

![bullseye_RDP_2_11_2_Perfect](https://github.com/FreeRDP/FreeRDP/assets/73900814/8b8bb0a7-5759-4d1d-bb7b-6716c02536ce)
![release_bullseye](https://github.com/FreeRDP/FreeRDP/assets/73900814/2ca4152d-1649-40c2-9277-937210467e03)
![bullseye_RDP_2_11_2](https://github.com/FreeRDP/FreeRDP/assets/73900814/4980d582-baf5-47d0-b934-666a69c87786)


Now simply updating to version 3.5.1 of freerdp, the problems begin:

![bullseye_RDP_3_5_1_KO](https://github.com/FreeRDP/FreeRDP/assets/73900814/65fc48ca-c857-4c7d-85b9-d6579021ad8a)
![bullseye_RDP_3_5_1](https://github.com/FreeRDP/FreeRDP/assets/73900814/773948da-48ef-4479-a21b-264d068c8749)

In the end, I tried on the Bookworm OS for raspberry, new, just installed with version 3.5.1 of freerdp and again I have the same problem:

![Bookworm_RDP_ko](https://github.com/FreeRDP/FreeRDP/assets/73900814/716398dd-5a13-4a84-99a3-355b6d75e387)
![Bookworm_wayland_active](https://github.com/FreeRDP/FreeRDP/assets/73900814/9a4f249c-a410-4cc0-82f2-4c34743a1018)
![release_Bookworm](https://github.com/FreeRDP/FreeRDP/assets/73900814/52c13583-6aba-4796-b297-bcb6c58498ab)

**Comment by akallabeth** [comment]
that sounds like SDL issues on your system?
you mind trying out another window manager/environment? 
if that is the case there is not much we can do, you can only fall back to `xfreerdp` then in your setup.

**Comment by pes00** [comment]
I confirm: everything is ok with Ubuntu

**Comment by pes00** [comment]
I also tried with the command 
`flatpak run --command=xfreerdp com.freerdp.FreeRDP /u:user /p:pwd /d:domain /v:111.111.111.111 -decorations /workarea`
but the result does not change. It looks like I won't be able to use version 3 of freerdp on the raspberry

![Ultimo](https://github.com/FreeRDP/FreeRDP/assets/73900814/defc6967-68cc-480d-90b0-59b9cfb47291)

**Comment by akallabeth** [comment]
@pes00 not `ubuntu` but just start a `gnome` or `plasma` or whatever session instead of the default?

**Comment by akallabeth** [comment]
I´m updating the flatpak build with newer SDL2, maybe that helps.

**Comment by pes00** [comment]
Is it into the beta repo of flatpak?

**Comment by pes00** [comment]
Forgive me, but I don't understand if this is something I can already find or that you will do in the future

**Comment by akallabeth** [comment]
@pes00 well, I don´t know why it does not work there, so can´t tell you ;)
might also be a bug of the window manager of rasperryOS as it works with `X11` and not `wayland`?

**Comment by pes00** [comment]
yes, I confirm
