### ISSUE TITLE
Add a flag for opening the window maximized

### ISSUE THREAD

**Issue by adler-amorette** [FreeRDP/FreeRDP#9758]
I always have to manually maximize the window, every single time.

I'm aware of the `/f` flag, and it's not what I need, I'm talking specifically about maximizing the window.

Would be nice to have a flag `/maximize`.

I thought maybe there's a way to do that with a desktop entry, but it's not possible.

**Comment by akallabeth** [comment]
use `/workarea`

**Comment by adler-amorette** [comment]
Documentation for that flag should be more searchable.

The description should at least include the word "window". And have an actual description, nobody knows what "work area" and "available" means.

**Comment by akallabeth** [comment]
@adler-amorette pull requests welcome.

**Comment by adler-amorette** [comment]
@akallabeth I would update the description, if I knew what that flag actually does. And reading the code to find out is not very productive, since someone already knows what it does.

And given that it's probably not very clear what that flag should do, I would remove it in favor of `/maximize`.
Though I suspect there's a use case for that flag that doesn't align with `/maximize`, thus either way there's a reason to add a flag for maximizing the window.
