### ISSUE TITLE
Memory leak && Resource leak

### ISSUE THREAD

**Issue by ghost** [FreeRDP/FreeRDP#976]
Hi,

[channels/sample/client/server_chan_test.cpp:30]: (error) Memory leak: data1
[channels/smartcard/client/smartcard_operations.c:1235]: (error) Memory leak: pAtrMasks
[client/common/file.c:478]: (error) Resource leak: fp
[libfreerdp/core/nla.c:282]: (error) Memory leak: output_buffer.pvBuffer
[libfreerdp/utils/pcap.c:200]: (error) Resource leak: pcap_fp
[server/Sample/sfreerdp.c:237]: (error) Resource leak: fp
[winpr/libwinpr/sspi/test/TestSchannel.c:272]: (error) Memory leak: lpTokenOut
[winpr/libwinpr/synch/semaphore.c:52]: (error) Memory leak: semaphore

**Comment by hardening** [comment]
no feedback, closing.
