### ISSUE TITLE
Convert hardcoded hotkeys into configurable ones

### ISSUE THREAD

**Issue by dethmourne** [FreeRDP/FreeRDP#9770]
I find myself frustrated when I need to use a hotkey on my work machine (which I RDP into from my home desktop so as to utilize my multiple monitor setup) and it turns out that hotkey is hardcoded to do something in FreeRDP. The example I've found so far is Ctrl+Alt+Enter, which is used by VS Code for "replace all occurrences" but is the FreeRDP fullscreen toggle.

I would like to see a mechanism for configuring hotkeys, even if it is just a simple on-off functionality rather than an actual "change the keybind for this" function.

I am going to look into changing the keybind in VS Code in the meantime, but this does mean relying on a non-default keybind for the function in VS Code which is not ideal as my development machine is considered ephemeral and thus I could be assigned a new machine (with default keybinds) at any time.

**Comment by akallabeth** [comment]
added the option for a per user configuration file for sdl-client.
