### ISSUE TITLE
Reconnect bug

### ISSUE THREAD

**Issue by may520java** [FreeRDP/FreeRDP#9772]
After connecting to Windows using wfreerdp, open Micrsoft Edge, then close the connection and reconnect. It was found that Micrsoft Edge cannot be opened

**Comment by akallabeth** [comment]
and this is a FreeRDP bug because?

**Comment by may520java** [comment]
> and this is a FreeRDP bug because?
But using mstsc.exe to connect and perform the same operation will not cause this problem，The first time you connect, you can open the browser. However, after disconnecting and reconnecting, opening the browser fails.

**Comment by akallabeth** [comment]
@may520java are you using `remote application mode` aka `rails` (`/app`)?
* if not then everything within the session can not be influenced by the `RDP` client.
* windows `RDP` servers open multiple `sessions` for a user, so maybe the test you did was one session reconnect and another new session? (`task manager` allows showing you the active sessions/logged in users, but not all windows versions support that, don´t ask me which ones these are ;))
* also, is only `edge` affected? if other applications work fine it is another indication that it is not `RDP client` related.

**Comment by may520java** [comment]
> @may520java are you using `remote application mode` aka `rails` (`/app`)?
> 
> * if not then everything within the session can not be influenced by the `RDP` client.
> * windows `RDP` servers open multiple `sessions` for a user, so maybe the test you did was one session reconnect and another new session? (`task manager` allows showing you the active sessions/logged in users, but not all windows versions support that, don´t ask me which ones these are ;))
> * also, is only `edge` affected? if other applications work fine it is another indication that it is not `RDP client` related.

You're right, it's true that only Edge has this issue. I changed to a Windows version and it doesn't exist anymore. Thank you.
<img width="800" alt="Snipaste_2024-01-16_16-36-44" src="https://github.com/FreeRDP/FreeRDP/assets/96558086/2fdc556d-d021-4cdf-b4eb-93b591a2cb24">
