### ISSUE TITLE
[FreeRDP 3.2.0] Compilation fails on Windows 11 x64 with Visual Studio 2022

### ISSUE THREAD

**Issue by MatteoBax** [FreeRDP/FreeRDP#9786]
**Describe the bug**
Compilation on Windows 11 x64 generates these errors (sorry if the errors are in Italian but my language is Italian):
[errors.txt](https://github.com/FreeRDP/FreeRDP/files/13999039/errors.txt)

The installation fails generating these errors:
```
-- Install configuration: "Release"
-- Installing: D:/freerdp/lib/cmake/WinPR3/WinPRConfig.cmake
-- Installing: D:/freerdp/lib/cmake/WinPR3/WinPRConfigVersion.cmake
-- Installing: D:/freerdp/lib/cmake/WinPR3/WinPRTargets.cmake
-- Installing: D:/freerdp/lib/cmake/WinPR3/WinPRTargets-release.cmake
-- Installing: D:/freerdp/lib/pkgconfig/winpr3.pc
CMake Error at freerdp-build/winpr/libwinpr/cmake_install.cmake:39 (file):
  file INSTALL cannot find
  "D:/Users/Matteo/source/repos/freerdp-build/Release/winpr3.lib": No error.
Call Stack (most recent call first):
  freerdp-build/winpr/cmake_install.cmake:80 (include)
  freerdp-build/cmake_install.cmake:37 (include)
```

**To Reproduce**
1. Configure the project with this command:
  ```
  cmake -S freerdp -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -B freerdp-build  -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DWITH_SERVER=ON -DWITH_SAMPLE=ON -DWITH_PLATFORM_SERVER=OFF -DWITH_FFMPEG=ON -DWITH_SWSCALE=ON -DWITH_DSP_FFMPEG=ON -DWITH_WEBVIEW=OFF -DCMAKE_INSTALL_PREFIX=D:\freerdp -DBUILD_SHARED_LIBS=OFF -DCHANNEL_URBDRC=OFF -DLIBUSB_1_LIBRARY=D:\Dev_Libs\lib\libusb-1.0.lib -DCMAKE_PREFIX_PATH=D:\Dev_Libs
  ```
2.  Compile the project with the following command:
  ```
  cmake --build freerdp-build
  ```
3. See error

**Expected behavior**
That the compilation is done correctly.

**Application details**
* FreeRDP version (`xfreerdp /3.2.0`)

**Environment (please complete the following information):**
 - OS: [Windows]
 - Version/Distribution: [Windows 11 23H2]
 - Architecture: [amd64]

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/Compilation#compiling-for-visual-studio-or-windows-sdk

you are missing `OpenSSL` and `FFmpeg` in your case. (maybe others too)
