### ISSUE TITLE
+clipboard vs /clipboard which one to use that works

### ISSUE THREAD

**Issue by user-629782** [FreeRDP/FreeRDP#9788]
Two problems:

(1) The man page and command line help use both forms of enabling the clipboard. That is they show +clipboard and /clipboard. First question is, which one is correct? If it is the latter, then what is the correct syntax to simply get it to act like the old +clipboard style and be consistent? Should +clipboard even still be in the man page or help options.

(2) Lately as in the v3.X series I have not been able to consistently use the +clipboard redirection function. Sometimes it works and other times it does not. The /clipboard has also been inconsistent as well. Just wanted to bring this to the devs attention.

Wanted to just start a discussion but could not figure out how to do that, sorry.

**Comment by akallabeth** [comment]
1. both are correct.
2. since 2.0 (~4 years ago) the default (as outlined in the help text) is that clipboard is enabled by default.

**Comment by user-629782** [comment]
Thank for the comment but I am still a little fuzzy on:
(1) +clipboard is not defined under the syntax in the help.
(2) I do not see where clipboard is enabled by default in the help text. I see a DEFAULT embedded in the /clipboard option but it is not clear what is default.
(3) does not explain why it does not work consistently when either +clipboard or /clipboard are used. If enabled by default, is it possible that defining the options is interfering with the correct behavior somehow.
(4) If either option (+clipboard or /clipboard) are NOT used, then we should assume that the clipboard IS redirected then?

Apologize for the rehash of this but it is not clear to me from the help text. The help text only mentions +clipboard at the bottom under the examples area but does not define it under the official syntax area at the top, which would lead you to believe it is not correct to use.

Thanks in advance for any clarity.

**Comment by akallabeth** [comment]
1. `+/-` is a generic `on / off` syntax for options, `/foo:bar` advanced syntax to turn something on with (optional) arguments. (which could indeed be explained better at a more prominent place)
1. As for the default, please read the help text.
```
 /clipboard:[use-selection:atom]
           Redirect clipboard. * use-selection:<atom> ... (X11) Specify which
           X selection to access. Default is CLIPBOARD. PRIMARY is the X-style
           middle-click selection. (default:on)
```
1. we do not have any issues regarding clipboard so far, so if you have such, please:
  * tell us what you´re using (there are 7 clients in the repo ;))
  * what does not work 
  * where it does not work (os, version, environment, ...)
