### ISSUE TITLE
Please enable WITH_VAAPI=ON in nightly builds

### ISSUE THREAD

**Issue by shmerl** [FreeRDP/FreeRDP#9791]
Is there any reason to keep it at `WITH_VAAPI=OFF`? It would be nice to be able to use GPU acceleration.

Though it would be nice to have a configuration option to enable or disable it at runtime in case you expect some instability with it.

**Comment by akallabeth** [comment]
pull requests welcome, but I doubt you will be able to implement something that is not `works on my machine for a tiny subset of connection parameters`

**Comment by shmerl** [comment]
It can be for example some environment variable if you prefer. Something like `FREERDP_USE_VAAPI=true` if  you prefer that over connection paramters.

Other than that, I just tested it (on AMD GPU) and it works fine with VAAPI. So it's sort of  waste not to have an option to use it if it's available. I see even Debian package isn't enabling it and I suspect for the same reason - there is no way to make it configurable at runtime. I can take a look at where this can be made conditional.

**Comment by shmerl** [comment]
OK, I took a look. It has a whole bunch of conditionals with
```
#ifdef WITH_VAAPI
...
```

I can add a boolean flag that would also be checked in addition to ifdefs (for parts that actually do some logic), and that flag would be set depending on some env variable like above or if may be command line parameter like `/vaapi` or something like that.

What do you think?

**Comment by shmerl** [comment]
On a side note - I've been using  a VAAPI enabled rebuilt Debian package without any issues so far.

**Comment by akallabeth** [comment]
@shmerl yes, it works for certain hardware combinations and connection settings (that is the reason we have it in there) but not for others and there is no easy way to detect which ones work and which do not.
so, we´re happy about pull requests to make this a runtime option, but definitely not to be enabled by default.

**Comment by shmerl** [comment]
Btw, do you prefer to remove VAAPI related ifdefs and simply have a runtime check, or you want to keep compile time exclusion with ifdef and add a runtime check on top for case when compile time was enabled? It feels somewhat messy to have all those ifdefs with runtime checks on top.

**Comment by akallabeth** [comment]
@shmerl keep the `#ifdef` for now (we don´t want to enable stuff not tested at all in stable releases) but if found stable we can remove these (so runtime checks on top)

**Comment by shmerl** [comment]
I made an initial PR, just enabling the /vaapi switch in the initial commit. It's not being used yet (just in case I got something wrong before proceeding further):

!10181.

**Comment by shmerl** [comment]
How can I get access to settings from h264_ffmpeg.c module? Not that familiar with the code, but other modules have something called context for that?

**Comment by akallabeth** [comment]
@shmerl depends on what you want to implement.
but basically you need to use `h264_context_set_option`  to pass it to the subsystem. (you might need to add a new value to the `H264_CONTEXT_OPTION` enum)

**Comment by shmerl** [comment]
Also, `rdpShadowEncoder* encoder` object there has access to ` encode->client->context.settings` and ` encode->server->settings`. Which one should I use to pull the info from?

**Comment by akallabeth** [comment]
@shmerl since that is a server side configuration option that is independent of the client settings `encoder->server->settings`.
`encoder->client->context.settings` has the configuration for the connected peer (graphics mode, ...) which contains the settings that both, the server and client support. (e.g. if the server supports GFX-AVC444 and the client only GFX-AVC420 that setting is disabled)

**Comment by shmerl** [comment]
OK, I made a change and tried testing it, but I don't see it kicking in even with /gdi:hw set. Must be I'm missing something or I made some mistake. Let me open a PR for review anyway and I'll try to debug it a bit later when I have a chance.

**Comment by shmerl** [comment]
Now I'm getting something confusing. Tried building without my patches simply with VAAPI_ENABLED=ON.

And I still get:

```
VCN: Powered down
```

Reported by amdgpu. So something isn't working regardless of my changes even.

**Comment by akallabeth** [comment]
@shmerl better join our matrix chat for such support questions ;)

anyway, can´t really tell without seeing your code, you got a fork with the patches somewhere?

**Comment by shmerl** [comment]
Yeah, posted the PR from it: https://github.com/FreeRDP/FreeRDP/pull/10191

See: https://github.com/shmerl/FreeRDP/tree/runtime_vaapi_2

**Comment by shmerl** [comment]
I updated the PR, but as above, I don't see actual VCN turning on according to amdgpu. I can join matrix a bit later to dig more into this.

**Comment by shmerl** [comment]
Digging into it in the debugger, somehow it skips over this part:

```
#ifdef WITH_VAAPI
		if (h264->HardwareAccelerated != 0)
		{
			if (!sys->hwctx)
			{
...
```
Checking why `h264->HardwareAccelerated` wasn't set.

**Comment by shmerl** [comment]
Hmm, `shadow_encoder_init_h264` isn't even called in my case.

**Comment by shmerl** [comment]
Going up the call chain, neither is `static DWORD WINAPI shadow_client_thread(LPVOID arg)` called anywhere.

**Comment by akallabeth** [comment]
@shmerl what are you talking about?
the init function is called on first frame sent, the other is a thread function passed to `CreateThread`
