### ISSUE TITLE
FreeRDP 3.2.0 fails to build (for Homebrew)

### ISSUE THREAD

**Issue by SMillerDev** [FreeRDP/FreeRDP#9807]
**Describe the bug**
Trying to compile 3.2.0, an error is thrown: "no member named 'add_scheme_handler' in 'webview::webview'"

**To Reproduce**
1. Compile FreeRDP like in: https://github.com/Homebrew/homebrew-core/pull/160392
2. See:
```console
  /tmp/freerdp-20240121-12144-4j4apq/FreeRDP-3.2.0/client/SDL/aad/wrapper/webview_impl.cpp:76:4: error: no member named 'add_scheme_handler' in 'webview::webview'
          w.add_scheme_handler("ms-appx-web", fkt, &scheme);
          ~ ^
```

**Expected behavior**
Succesful compile

**Application details**
* FreeRDP version: 3.2.0
* Command line used: zsh
* Output of `xfreerdp /buildconfig`: none
* OS version connecting to (server side): none
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` : none
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help:
3.2.0 tag, both GCC on Linux and CLang on macOS.
```console
cmake -S . -B build -DWITH_X11=ON -DBUILD_SHARED_LIBS=ON -DWITH_JPEG=ON -DCMAKE_INSTALL_NAME_DIR=/usr/local/Cellar/freerdp/3.2.0/lib -DWITH_MANPAGES=OFF -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/freerdp/3.2.0 -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DBUILD_TESTING=OFF -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk
```

**Environment (please complete the following information):**
 - OS: Linux or macOS
 - Version/Distribution: Ubuntu 22.04, macOS 12, 13 and 14
 - Architecture: x86 and ARM on macOS

**Comment by akallabeth** [comment]
sorry for the inconvenience, add `-DWITH_WEBVIEW=OFF`
we did not have time to finish the required changes to https://github.com/webview/webview to be compatible with mac os yet.

**Comment by SMillerDev** [comment]
Thanks for the quick response, giving it a go now.
