### ISSUE TITLE
freerdp.pc libs error with -DMONOLITHIC_BUILD=ON option

### ISSUE THREAD

**Issue by Shumen** [FreeRDP/FreeRDP#981]
With monolithic building option, there're only libfreerdp.so, libwinpr.so, and libfreerdp-client.so, therefore the required Libs in freerdp.pc should be: -L${libdir} -lfreerdp -lfreerdp-client -lwinpr.

However, the Libs flags in freerdp.pc still is statically:

Libs: -L${libdir} -lfreerdp-cache -lfreerdp-codec -lfreerdp-core -lfreerdp-crypto -lfreerdp-gdi -lfreerdp-locale -lfreerdp-rail -lwinpr-sspi -lwinpr-rpc

**Comment by akallabeth** [comment]
monolithic is default now.

**Comment by bmiklautz** [comment]
Also the .pc files where split into freerdp, freerdp-server freerdp-client and winpr. Always with the proper major version for example freerdp2 for API version 2.
