### ISSUE TITLE
Add clipboard support for JPG/JPEG, PNG, GIF, ICO, WEBP formats

### ISSUE THREAD

**Issue by kayzzen01** [FreeRDP/FreeRDP#9823]
**Is your feature request related to a problem? Please describe.**
I see that it is not possible to copy image content and place it in Google Chat, for example. However, if I do the same procedure and paste it into KolourPaint or the KDE Desktop, the image is pasted.

**Describe the solution you'd like**
It would be possible to add support for JPG/JPEG, PNG, GIF, ICO, WEBP formats.

**Describe alternatives you've considered**
I think browsers don't support BMP on the clipboard
Maybe implementing for different formats would be too much work, so we could check which format the browser is expecting. Maybe PNG or JPG.

**Additional context**
Checking the contents of the clipboard, I was able to verify that FreeRDP always copies as BMP.
I think browsers don't support BMP on the clipboard.
I used xclip to check the target formats.

- Clipboard(Snipping Tool) in remote PC.

Command:
`xclip -selection clipboard -o -t TARGETS`
output:
```
TIMESTAMP
TARGETS
image/bmp
```

- Clipboard(Spectable) in host.

Command:
`xclip -selection clipboard -o -t TARGETS`
output:
```
application/x-qt-image
x-kde-force-image-copy
image/png
image/bmp
image/cur
image/icns
image/ico
image/jp2
image/jpeg
image/jpg
image/pbm
BITMAP
image/pgm
image/ppm
PIXMAP
image/tif
image/tiff
image/wbmp
image/webp
image/xbm
image/xpm
TARGETS
MULTIPLE
TIMESTAMP
SAVE_TARGETS
```

**Comment by akallabeth** [comment]
@kayzzen01 looks like your website is at fault here:
https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types

bitmap is supported (I would have been surprised if not), even with the `mime type` we expose.
but it looks like websites do something different, I can´t, for example, paste an image copied from `gimp` (or the gnome screenshot tool) on https://pasteboard.co/ in firefox (fedora 39 here)

**Comment by akallabeth** [comment]
as for support, I´ll do a pr improving the exposed mime types for bitmaps (which every known program supports ;)), but conversion is not really something on the roadmap (and not really a good idea, just adds lots of dependencies for little gain)

**Comment by akallabeth** [comment]
so, https://github.com/FreeRDP/FreeRDP/pull/9824 adds support for alternate bitmap mime types and `tiff` if available (that is one of the native formats windows announces)

as for your issue, could you check if the same issue happens with some website that does not require auth? so we can test here and we have a common base to talk ;)

**Comment by kayzzen01** [comment]
I agree with you that the level of gain is little. It's another ease. I have a good screen and can use the remote PC in Full HD instead of full screen and use another capture tool on the host. I think full screen is a little more work.

I think your solution proposal is good.

I found this website http://onpaste.com/
It seems to respond like Google Chat, Element, Discord...

**Comment by akallabeth** [comment]
@kayzzen01 ok, did implement this now, could you check https://github.com/FreeRDP/FreeRDP/pull/9873 ?

**Comment by kayzzen01** [comment]
@akallabeth, I didn't know what the flow was like to get your code and branch, but I managed to find my way.
I managed to compile your changes, but it didn't work. I will describe the steps I took:

`git clone https://github.com/akallabeth/FreeRDP.git`

`git checkout bitmap_formats`

Arch Linux dependencies (I'm not sure I need all of these packages, next time I'll check each of the dependencies):
`sudo pacman -S base-devel libvncserver gnome-keyring libgnome-keyring cmake libappindicator-gtk3 ninja pkcs11-helper sdl2_ttf docbook-xsl`

I don't know how to define `DCMAKE_TOOLCHAIN_FILE`, so I compiled it without this option:

```
cmake -GNinja \
    -B freerdp-build \
    -S freerdp \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON \
    -DCMAKE_INSTALL_PREFIX=/opt/freerdp \
    -DWITH_SERVER=ON \
    -DWITH_SAMPLE=ON \
    -DWITH_PLATFORM_SERVER=OFF \
    -DUSE_UNWIND=OFF \
    -DWITH_SWSCALE=OFF \
    -DWITH_FFMPEG=OFF \
    -DWITH_WEBVIEW=OFF
```

`cmake --build freerdp-build`

xclip output:
```
$ xclip -selection clipboard -o -t TARGETS
TIMESTAMP
TARGETS
image/bmp
image/x-bmp
image/x-MS-bmp
image/x-win-bitmap
```

I think I must have done something wrong.

**Comment by akallabeth** [comment]
yes, you need to activate the new formats (deactivated by default) during build:
* `-DWINPR_UTILS_IMAGE_JPEG=ON`
* `-DWINPR_UTILS_IMAGE_PNG=ON`
* `-DWINPR_UTILS_IMAGE_WEBP=ON`

and install the corresponding image library development headers

**Comment by kayzzen01** [comment]
So, MS Paint and Windows Photos programs worked, but Snipping Tool or Word did not work.
A message appears in Google Chat:

Unable to upload files
The system administrator only allows images to be uploaded


Trying to paste an image into the body of an email (GMail) or Google Chat.
Output:

```
[13:33:56:471] [3520:00000dc1] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:471] [3520:00000dc1] [WARN][com.freerdp.client.x11.cliprdr] - [convert_data_from_existing_raw_data]: Failed to get converted clipboard data
[13:33:56:486] [3520:00000dd6] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:486] [3520:00000dd6] [WARN][com.freerdp.client.x11.cliprdr] - [xf_cliprdr_server_format_data_response]: failed to get clipboard data in format image/png [source format CF_DIB]
[13:33:56:487] [3520:00000dc1] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:487] [3520:00000dc1] [WARN][com.freerdp.client.x11.cliprdr] - [convert_data_from_existing_raw_data]: Failed to get converted clipboard data
[13:33:56:494] [3520:00000dd6] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:494] [3520:00000dd6] [WARN][com.freerdp.client.x11.cliprdr] - [xf_cliprdr_server_format_data_response]: failed to get clipboard data in format image/png [source format CF_DIB]
[13:33:56:495] [3520:00000dc1] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:495] [3520:00000dc1] [WARN][com.freerdp.client.x11.cliprdr] - [convert_data_from_existing_raw_data]: Failed to get converted clipboard data
[13:33:56:508] [3520:00000dd6] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:508] [3520:00000dd6] [WARN][com.freerdp.client.x11.cliprdr] - [xf_cliprdr_server_format_data_response]: failed to get clipboard data in format image/png [source format CF_DIB]
[13:33:56:509] [3520:00000dc1] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:509] [3520:00000dc1] [WARN][com.freerdp.client.x11.cliprdr] - [convert_data_from_existing_raw_data]: Failed to get converted clipboard data
[13:33:56:521] [3520:00000dd6] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:521] [3520:00000dd6] [WARN][com.freerdp.client.x11.cliprdr] - [xf_cliprdr_server_format_data_response]: failed to get clipboard data in format image/png [source format CF_DIB]
[13:33:56:522] [3520:00000dc1] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:522] [3520:00000dc1] [WARN][com.freerdp.client.x11.cliprdr] - [convert_data_from_existing_raw_data]: Failed to get converted clipboard data
[13:33:56:529] [3520:00000dd6] [ERROR][com.winpr.utils.image] - [readBitmapInfoHeader]: invalid (expected) offset 52 > biSize 40
[13:33:56:529] [3520:00000dd6] [WARN][com.freerdp.client.x11.cliprdr] - [xf_cliprdr_server_format_data_response]: failed to get clipboard data in format image/jpeg [source format CF_DIB]
```

xclip MS Paint output:
```
TIMESTAMP
TARGETS
image/bmp
image/x-bmp
image/x-MS-bmp
image/x-win-bitmap
image/webp
image/png
image/jpeg
```
xclip Windows Photos output:
```
TIMESTAMP
TARGETS
text/uri-list
x-special/gnome-copied-files
x-special/mate-copied-files
image/bmp
image/x-bmp
image/x-MS-bmp
image/x-win-bitmap
image/webp
image/png
image/jpeg
```

xclip Snipping Tool output:
```
TIMESTAMP
TARGETS
image/bmp
image/x-bmp
image/x-MS-bmp
image/x-win-bitmap
image/webp
image/png
image/jpeg
```
I couldn't build it in isolation with the options:

- -DWINPR_UTILS_IMAGE_JPEG=ON
- -DWINPR_UTILS_IMAGE_WEBP=ON

Using only PNG to build freerdp works:

- -DWINPR_UTILS_IMAGE_PNG=ON

Using the three activated options it was also possible to build or enable the PNG parameter together with JPEG/WEBP.
I found that strange.

One good thing is that now I can perform a screeshoot using the Snipping Tool, click open with MS Paint and copy from there. This is already helping me.

Is it possible to increase biSize? or am I talking nonsense.
Maybe it will solve the problem described above.

**Comment by akallabeth** [comment]
@kayzzen01 regarding 
> I couldn't build it in isolation with the options:
>
> * -DWINPR_UTILS_IMAGE_JPEG=ON
> * -DWINPR_UTILS_IMAGE_WEBP=ON

then you´re lacking some dependencies (libwebp, libjpeg?) 

as for the issues with `BMP` retrieval, checking what is wrong there.

**Comment by akallabeth** [comment]
@kayzzen01 ok, found the issue, the offset was handled wrong.

**Comment by kayzzen01** [comment]
> @kayzzen01 regarding
> 
> > I couldn't build it in isolation with the options:
> > 
> > * -DWINPR_UTILS_IMAGE_JPEG=ON
> > * -DWINPR_UTILS_IMAGE_WEBP=ON
> 
> then you´re lacking some dependencies (libwebp, libjpeg?)
> 
> as for the issues with `BMP` retrieval, checking what is wrong there.

I checked the installation and the libraries are there:

- extra/libjpeg-turbo 3.0.2-2
- extra/libpng 1.6.42-1
- extra/libwebp 1.3.2-1

But let's take it easy :wink:. We can see that later.

**Comment by kayzzen01** [comment]
> @kayzzen01 regarding
> 
> > I couldn't build it in isolation with the options:
> > 
> > * -DWINPR_UTILS_IMAGE_JPEG=ON
> > * -DWINPR_UTILS_IMAGE_WEBP=ON
> 
> then you´re lacking some dependencies (libwebp, libjpeg?)
> 
> as for the issues with `BMP` retrieval, checking what is wrong there.

I checked the installation and the libraries are there:

- extra/libjpeg-turbo 3.0.2-2
- extra/libpng 1.6.42-1
- extra/libwebp 1.3.2-1

But let's take it easy :wink:. We can see that later.

**Comment by akallabeth** [comment]
@kayzzen01 does it work for the other formats now?

**Comment by kayzzen01** [comment]
@akallabeth, working perfectly. :heavy_check_mark:  

I tested with the following build options  and they worked without problems:

```
-DWINPR_UTILS_IMAGE_JPEG=ON
-DWINPR_UTILS_IMAGE_PNG=ON
-DWINPR_UTILS_IMAGE_WEBP=ON
```

- PNG only
- PNG and JPEG
- PNG and WEBP
- PNG, JPEG and WEBP

### Note:

I just have one observation about the compilation.
I can't compile JPEG or WEBP separately from PNG or PNG and WEBP together, that is, it always depends on PNG to compile.
It could be a particularity of my Arch Linux system.

Error message:

JPEG
```
[343/559] Linking C executable winpr/tools/hash-cli/winpr-hash
FAILED: winpr/tools/hash-cli/winpr-hash
: && /usr/bin/cc -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno -omit-frame-pointer -DWINPR_DLL -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects winpr/tools/hash-cli/CMakeFiles/winpr-hash.dir/hash.c.o -o winpr/tools/hash -cli/winpr-hash -Wl,-rpath,/home/kayzzen/Desktop/freerdp/freerdp-build/winpr/libwinpr: winpr/libwinpr/libwinpr3.so.3.2.1 && :
/usr/bin/ld: winpr/libwinpr/libwinpr3.so.3.2.1: undefined reference to `clipboard_synthesize_image_format_to_bmp'
collect2: error: ld returned 1 exit status
```

WEBP
```
[315/559] Linking C executable winpr/tools/hash-cli/winpr-hash
FAILED: winpr/tools/hash-cli/winpr-hash
: && /usr/bin/cc -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno -omit-frame-pointer -DWINPR_DLL -O3 -DNDEBUG -flto=auto -fno-fat-lto-objects winpr/tools/hash-cli/CMakeFiles/winpr-hash.dir/hash.c.o -o winpr/tools/hash -cli/winpr-hash -Wl,-rpath,/home/kayzzen/Desktop/freerdp/freerdp-build/winpr/libwinpr: winpr/libwinpr/libwinpr3.so.3.2.1 && :
/usr/bin/ld: winpr/libwinpr/libwinpr3.so.3.2.1: undefined reference to `clipboard_synthesize_image_format_to_bmp'
collect2: error: ld returned 1 exit status
```

I don't know if we should check these compilation errors. So I need you to check if it's worth it. Maybe you've had this problem before or have some clue.

**Comment by akallabeth** [comment]
@kayzzen01 might require you to run `cmake` again (it has a odd feature that `cmake --build <builddir>` does not always recreate the configurations, but `cmake <builddir> && cmake --build <builddir>` does
