### ISSUE TITLE
SmartScaling requested but compiled without libcairo support! (fifth time, I know)

### ISSUE THREAD

**Issue by ricfwolff** [FreeRDP/FreeRDP#9829]
I know this has been asked four times already, but the answers are so ~~poor~~ high-level that they cannot help idiots like me.

I've read: https://github.com/FreeRDP/FreeRDP/discussions/8584, https://github.com/FreeRDP/FreeRDP/issues/7511 and https://github.com/FreeRDP/FreeRDP/issues/7202.

But I'm not compiling it myself. I only did the following:

brew install freerdp
brew install --cask xquartz

(PS: I'm on Mac M1)

When I connect using /smart-sizing, it opens the screen, but, obviously, if I try to resize, it errors:
SmartScaling requested but compiled without libcairo support! 

For noob people like me that will search GitHub in the future looking for this answer that are not compiling themselves. 
How do I fix this? What library do I have to install? Which command line to use? Please send me the steps to go through to make it work.

Thank you.

**Comment by akallabeth** [comment]
you don´t fix it by command line.

this is a compile time thing, you need to compile against `swscale` or `cairo` to have image scaling enabled.
if you think that is an error file a bug against brew issue tracker.

as mentioned in the other issues, report this to whoever does compile it for you, if you compile by some build script check that `-DWITH_SWSCALE=ON` or `-DWITH_CAIRO=ON` is set.
