### ISSUE TITLE
EL 9.3 and FIPS

### ISSUE THREAD

**Issue by Mashintime** [FreeRDP/FreeRDP#9830]
**Describe the bug**
When FIPS is enabled Remote Desktop Services doesn't appear to work.

**To Reproduce**
Enable FIPS, connect to a RDS connection broker, which then hands you off to a session host and connection fails after entering proper username, password, domain.

**Expected behavior**
Would expect the connection to succeed

**Application details**
* FreeRDP version 3.1.0, source tarball from releases
* xfreerdp3 rdpfile.rdp /cert:ignore /dynamic-resolution /sound /log-level:TRACE /gt:rpc
* Output is difficult for me to obtain
* Built based on spec file from: github.com/FreeRDP/FreeRDP/blob/master/packaging/rpm/freerdp-nightly.spec, including the internal  md4, md5, rc4 support.

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: EL 9.3
 - Architecture:  x86_64
 - Server env:  Windows Server 2019

**Additional context**
FIPS:AD-SUPPORT policy/sub-policy is set on EL 9.3.  If FIPS is disabled the same compiled binary, rdp file and arguments works fine.  Re-enabling FIPS and the issue re-appears.

Log captures between the two, I've noticed two things 
- When FIPS is disabled, NLA Security is True in [nego_enable_nla] and false when FIPS is enabled
- When FIPS is enabled, when authenticated to connection broker, and redirected to session host, the the following lines show in the ouput (hand transcribed, may be some typos and some info skipped/abbreviated):  
[TRACE][com.freerdp.core.rdp] - [rdp_read_security_header][0x..........]: SEC_LICENSE_PKT[0x00000080]
[ERROR][com.winpr.crypto.hash] - [winpr_Digest_Init_internal]:  Failed to initialize diget (null)
[DEBUG][com.freerdp.core.rdp][rdp_recv_callback_int][0x........]:CONNECTION_STATE_LICENSING - rdp_client_connect_license() - STATE_RUN_FAILED [-1]
[ERROR][com.freerdp.core.rdp][rdp_recv_callback_int][0x........]: CONNECTION_STATE_LICENSING status STATE_RUN_FAILED [-1]
[ERROR][com.freerdp.core] - [rdp_client_wait_for_activation]: ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
[DEBUG][com.freerdp.core] - [freerdp_check_fds]: rdp_check_fds() - -1

I apologize I can't provide the entire log, but if you would like anything specific please let me know and will provide what I can.  

Thank you in a advance for any assistance.

**Comment by akallabeth** [comment]
might have to do with rdp licensing, it uses  outdated RSA certificates, not sure which parameters are active in your installation though.

**Comment by Mashintime** [comment]
Thanks @akallabeth I suspected it was license related.  Our FIPS crypto policy is expecting RSA 2048 min.  Not a windows admin, but is that something that could be updated on the Win Server side and/or internal support be added like for the rc4/md5 stuff?

**Comment by akallabeth** [comment]
@Mashintime well, the licensing uses a public private key (no joke, just check for `priv_key_tssk` in `FreeRDP` source code)
that is used to encrypt the data.
not sure how to handle that ;)
so yes, should be fixed server side, but not a windows admin, so no idea how to disable that `feature`

**Comment by Mashintime** [comment]
Thanks @akallabeth.  I don't think it's related to a weak RSA cert.  EL 7 had a min requirement of 2048 bits, which is the same for EL 9.  Do you have any other ideas or things to try?  I asked the Windows Admins to look into the licensing stuff and it doesn't appear there is much configuration that can be done on that specific part.  Out of ideas at this point.  I'm not sure if we're early adopters, but suprised more people haven't experience this issue yet with FIPS.

**Comment by akallabeth** [comment]
rereading the issue, `[ERROR][com.winpr.crypto.hash] - [winpr_Digest_Init_internal]: Failed to initialize diget (null)` is the key I missed previously.
`winpr_openssl_get_evp_md` seens to return `NULL` for some digest algorightm. (most likely `rc4`, `md4` or `md5` - just add a print before `EVP_get_digestbyname` to be sure)

we´ve added `WITH_INTERNAL_RC4`,  `WITH_INTERNAL_MD4` and `WITH_INTERNAL_MD5` to have internal implementations of these algorightms

**Comment by akallabeth** [comment]
while this is sort of bad, we have no choice but to support these until microsoft updates the behaviour of their RDP server not to require these :/

**Comment by Mashintime** [comment]
Thanks.  I did compile with internal rc4, md4, and md5 support enabled.  I see if I can sort out updating the code to print out the hash type.

**Comment by Mashintime** [comment]
Not exactly sure which EVP_get_digestbyname to use the print with, but put it in the two instances I found in hash.c.  It prints out both sha1 and md5.

**Comment by akallabeth** [comment]
@Mashintime ok, found the issue. in `winpr_Digest_Init_Allow_FIPS` the internal `MD5` was not used.
