### ISSUE TITLE
xfreerdp3: Without internet access, but local network access, authentication hangs for (almost) 2 minutes

### ISSUE THREAD

**Issue by pnowack** [FreeRDP/FreeRDP#9831]
Affected version: FreeRDP3 at current master (build was done on Mo 29 Jan 2024 19:09:23 CET)

Server: g-r-d/master (46.alpha + some unrelated commits), built against FreeRDP3
Client: xfreerdp3

Reproduction steps:

1. Connect to your local network (router), e.g. with WiFi
2. Disconnect the ethernet cable from your router, that provides internet access (you should now still be able to reach devices on the network, but not the internet)
3. Connect to g-r-d (shadow-server/FreeRDP3 should work too, when set up with NTLM as auth mechanism) with xfreerdp3

Observation: xfreerdp3 completely hangs. On the server side, the following is visible:
```
[06:54:36:763] [215674:00034ba2] [DEBUG][com.freerdp.core.nego] - [nego_process_negotiation_request]: RDP_NEG_REQ: RequestedProtocol: 0x00000003
[06:54:36:763] [215674:00034ba2] [DEBUG][com.freerdp.core.connection] - [rdp_server_accept_nego]: Client Security: RDSTLS:0 NLA:1 TLS:1 RDP:0
[06:54:36:763] [215674:00034ba2] [DEBUG][com.freerdp.core.connection] - [rdp_server_accept_nego]: Server Security: RDSTLS:0 NLA:1 TLS:0 RDP:0
[06:54:36:763] [215674:00034ba2] [DEBUG][com.freerdp.core.connection] - [rdp_server_accept_nego]: Negotiated Security: RDSTLS:0 NLA:1 TLS:0 RDP:0
[06:54:36:774] [215674:00034ba2] [DEBUG][com.winpr.sspi] - [InitSecurityInterfaceExA]: InitSecurityInterfaceExA
[06:54:36:774] [215674:00034ba2] [DEBUG][com.freerdp.core.auth] - [credssp_auth_init]: Using package: Negotiate (cbMaxToken: 12256 bytes)
[06:54:36:774] [215674:00034ba2] [DEBUG][com.freerdp.core.auth] - [credssp_auth_setup_server]: Acquired server credentials
[06:54:36:774] [215674:00034ba2] [DEBUG][com.freerdp.core.nla] - [nla_set_state]: -- NLA_STATE_INITIAL	--> NLA_STATE_INITIAL
```

xfreerdp3 here completely hangs. After 1 minute the following appears on the client side:
```
[06:59:50:521] [218702:0003564f] [ERROR][com.winpr.sspi.Kerberos] - [kerberos_AcquireCredentialsHandleA]: krb5glue_get_init_creds (KDC für Realm »ATHENA.MIT.EDU« kann nicht gefunden werden [-1765328230])
```

After further 40 seconds, the following appears on the client side:
```
[07:00:30:592] [218702:0003564f] [ERROR][com.winpr.sspi.Kerberos] - [kerberos_AcquireCredentialsHandleA]: krb5glue_get_init_creds (KDC für Realm »ATHENA.MIT.EDU« kann nicht gefunden werden [-1765328230])
```

Then (after these almost 2 minutes), the fallback to NTLM finally happens, and the connection sequence proceeds. When there is an internet connection available, this hang does not happen.
In this case here, I run g-r-d locally on the very same machine. If I even disconnect from the local network, this hang also does not happen. So, for some reason Kerberos tries to access the internet, although it is not needed, and this whole process cannot be aborted. Pressing CTRL+C in the terminal window, where xfreerdp3 was started does not (immediately) stop xfreerdp3.

Is there a way, that a (shorter) timeout could be specified? Doing the same with xfreerdp2, results in an immediate connection (since it does not support Kerberos). Also, could the Kerberos calls be cancelled, when an interrupt happens?

**Comment by akallabeth** [comment]
well, fix your kerberos config.
this happens if you have configured a realm that is not reachable.

the other option is to compile without kerberos, but that will break quite soon as microsoft deprecates all older authentication methods in favor of kerberos.

if fixing kerberos config is not possible or out of scope, there is a (currently little documented) feature of `WinPR` to read settings from a config file:
`/etc/winpr/HKLM.reg` with the contents:
```
[HKEY_LOCAL_MACHINE\Software\FreeRDP\FreeRDP\SSPI\Negotiate]
"kerberos"=dword:0
```

you completely disable kerberos for freerdp

**Comment by pnowack** [comment]
> well, fix your kerberos config.
this happens if you have configured a realm that is not reachable

hmm... I don't have Kerberos set up at all here.. I think this would apply to most users out there. So, there are no files created with respect to Kerberos (-ENOENT).

> the other option is to compile without kerberos, but that will break quite soon as microsoft deprecates all older authentication methods in favor of kerberos.

Yeah, I actually want to avoid that, since I want to experiment with Kerberos later (when there is time). Not sure whether MS released something new regarding IAKerb.

**Comment by pnowack** [comment]
Would it be possible to check, whether a config was set up at all and bail out, in case none was found (manual checking, before Kerberos does its thing)?

**Comment by akallabeth** [comment]
@pnowack I´ve seen a similar issue on a gentoo system. there a `sample` kerberos config was there instead of an empty one. maybe that is the reason?
we ususally only check for a kdc we supply ourselves, but the `athena.mit.edu` looks like some sample

**Comment by akallabeth** [comment]
currently we got no way to disable the kerberos, as that is not possible with the windows builds either (we use the same SSPI API to do that.

**Comment by pnowack** [comment]
> we ususally only check for a kdc we supply ourselves, but the athena.mit.edu looks like some sample

hmmm... you are right. It seems to be a sample config provided by the `krb5` pkg (on Arch) in `/etc/krb5.conf`:
```
[libdefaults]
	default_realm = ATHENA.MIT.EDU

[realms]
# use "kdc = ..." if realm admins haven't put SRV records into DNS
	ATHENA.MIT.EDU = {
		admin_server = kerberos.mit.edu
	}
	ANDREW.CMU.EDU = {
		admin_server = kdc-01.andrew.cmu.edu
	}

[domain_realm]
	mit.edu = ATHENA.MIT.EDU
	csail.mit.edu = CSAIL.MIT.EDU
	.ucsc.edu = CATS.UCSC.EDU

[logging]
#	kdc = CONSOLE
```

Is `/etc/krb5.conf` the default path for user configs? Or is it the fallback path, in case no user set up config was found? (Assuming here a layered config, because otherwise the file in `/etc/krb5.conf` would be overwritten everytime the `krb5` pkg is updated.

**Comment by pnowack** [comment]
Ok, I think this sample file should not be provided by default in that specific path (`/etc/krb5.conf`). It seems to be the actual path and not some fallback path for layered configs. I'll close this.
