### ISSUE TITLE
[SDL]: Target "dialogs" was not found

### ISSUE THREAD

**Issue by MatteoBax** [FreeRDP/FreeRDP#9832]
**Describe the bug**
When I try to configure the project I get this error:
````
CMake Error at client/SDL/dialogs/CMakeLists.txt:71 (target_link_libraries):
  Target "dialogs" links to:

    SDL2_ttf::SDL2_ttf

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
````

**To Reproduce**
1. configure the project with the command: ```` cmake -GNinja -B freerdp-build -S freerdp -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=D:\freerdp\workspace -DWITH_SERVER=ON -DWITH_SAMPLE=ON -DWITH_PLATFORM_SERVER=OFF -DUSE_UNWIND=OFF -DWITH_FFMPEG=ON -DWITH_SWSCALE=ON -DWITH_DSP_FFMPEG=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DWITH_WEBVIEW=OFF -DCHANNEL_URBDRC=OFF ````

2. See error

**Expected behavior**
May the project setup be successful

**Application details**
* FreeRDP version (`3.2.0)
* cmake configuration command: ```` cmake -GNinja -B freerdp-build -S freerdp -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=D:\freerdp\workspace -DWITH_SERVER=ON -DWITH_SAMPLE=ON -DWITH_PLATFORM_SERVER=OFF -DUSE_UNWIND=OFF -DWITH_FFMPEG=ON -DWITH_SWSCALE=ON -DWITH_DSP_FFMPEG=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DWITH_WEBVIEW=OFF -DCHANNEL_URBDRC=OFF ````
* compiler: Visual Studio 2022

**Environment (please complete the following information):**
 - OS: [Windows.]
 - Version/Distribution: [Windows 11]
 - Architecture: [amd64]:

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/wiki/Compilation

**Comment by MatteoBax** [comment]
Now I get these errors:
````
Creating the freerdp-shadow-cli.lib library and the freerdp-shadow-cli.exp object
LINK : warning LNK4098: default library 'MSVCRT' conflicts with use of other libraries; use /NODEFAULTLIB:library
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_surface_fill not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_label_draw not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_engine_free not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_engine_new not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_surface_free not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_surface_new not resolved
````

**Comment by Kotivskyi** [comment]
@akallabeth having same issue when trying to compile as static library with DBUILD_SHARED_LIBS=OFF.
Meanwhile it compiles with DBUILD_SHARED_LIBS=NO

Steps to reproduce:
1. In scripts/bundle-mac-os.sh change DBUILD_SHARED_LIBS=OFF
2. run "sh scripts/bundle-mac-os.sh"
3. Observer error mention above

Application details:
FreeRDP version 3.2.0
compiler: Xcode 15.2
OS: MacOS 14.2.1

**Comment by akallabeth** [comment]
> @akallabeth having same issue when trying to compile as static library with DBUILD_SHARED_LIBS=OFF. Meanwhile it compiles with DBUILD_SHARED_LIBS=NO
> 

then your `CMake` is broken, report to https://cmake.org/

> Steps to reproduce:
> 
>     1. In scripts/bundle-mac-os.sh change DBUILD_SHARED_LIBS=OFF
> 

why not directly add `exit 1`?

if you try to build a fully static binary you need a few more modifications than that. (therefore the link to the wiki, the steps on how to build shared and static libraries/binaries are in there!)

**Comment by Nexarian** [comment]
The fix for me was to add `-DWITH_SDL_LINK_SHARED=OFF` to the FreeRDP build options

**Comment by akallabeth** [comment]
> DWITH_SDL_LINK_SHARED

if you try to link a statically compiled `SDL` then yes, otherwise it is not required. (`-DBUILD_SHARED_LIBS=OFF` just creates static `FreeRDP` libraries and binaries, dependencies have their own pitfalls)
