### ISSUE TITLE
freerdp-shadow3.lib unresolved external symbols

### ISSUE THREAD

**Issue by MatteoBax** [FreeRDP/FreeRDP#9835]
**Describe the bug**
When I try to compile the project, I get the following errors towards the end:
````
Creating the freerdp-shadow-cli.lib library and the freerdp-shadow-cli.exp object
LINK : warning LNK4098: default library 'MSVCRT' conflicts with use of other libraries; use /NODEFAULTLIB:library
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_surface_fill not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_label_draw not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_engine_free not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_engine_new not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_surface_free not resolved
freerdp-shadow3.lib(shadow_lobby.c.obj) : error LNK2001: external symbol __imp_rdtk_surface_new not resolved
freerdp-shadow-cli.exe : fatal error LNK1120: 6 external unresolved
````

**To Reproduce**
1. configure the project with the command: `cmake -GNinja -B freerdp-build -S freerdp -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=D:\freerdp\workspace -DWITH_SERVER=ON -DWITH_SAMPLE=ON -DWITH_PLATFORM_SERVER=OFF -DUSE_UNWIND=OFF -DWITH_FFMPEG=ON -DWITH_SWSCALE=ON -DWITH_DSP_FFMPEG=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DWITH_WEBVIEW=OFF -DCHANNEL_URBDRC=OFF`
2. Compile with: `cmake --build freerdp-build `
3. See error

**Expected behavior**
That the project is compiled.

**Application details**
* FreeRDP version (3.2.0)
* cmake parameters: `-B freerdp-build -S freerdp -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON -DCMAKE_INSTALL_PREFIX=D:\freerdp\workspace -DWITH_SERVER=ON -DWITH_SAMPLE=ON -DWITH_PLATFORM_SERVER=OFF -DUSE_UNWIND=OFF -DWITH_FFMPEG=ON -DWITH_SWSCALE=ON -DWITH_DSP_FFMPEG=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DWITH_WEBVIEW=OFF -DCHANNEL_URBDRC=OFF`

**Environment (please complete the following information):**
 - OS: [Windows]
 - Version/Distribution: [Windows 11]
 - Architecture: [amd64]:

**Comment by akallabeth** [comment]
@MatteoBax so you play randomly with `CMake` options and found a combination that does not work?

A note:
1. server side backends are not implemented for windows (the library is there, but nothing more than a sample works) - only exception is proxy which works fully
2. static linking on windows is quite a beast and we don´t test more than the clients with it. Feel free to create pull requests for stuff that you find ;)
