### ISSUE TITLE
Alpha Transparency for specific colors - seamless Desktop effect.

### ISSUE THREAD

**Issue by rbreaves** [FreeRDP/FreeRDP#9861]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, but I would like to recreate the Coherence mode vmware has had and something that works better than the RemoteApp rdp feature from microsoft as well as it is very limited in multiple ways.

**Describe the solution you'd like**
I'd like to take a specific color - let's say magenta pink, hexcode #FF00FF, and convert that to being 100% transparent while using xfreerdp or more specifically the windows version wfreerdp client. Even if the user cannot click below the transparent area, which would be nice too, it'd still be a major plus being able to see the rest of my host OS while using specific applications or the taskbar area of Windows.

Keying transparency to a specific color or threshold of colors would be most ideal as the user can then set their wallpaper to that color.

**Describe alternatives you've considered**
Creating an agent that runs and tracks the position and size of each window and convey that info the client. This could be overly complicated though where as a simple keying of color would be a better and easier implementation.

**Additional context**
Checkout vmware or parallels coherence modes from the past if what I am wanting is unclear. It seems they are largely deprecated now though and I imagine due to users not using the features heavily from the battery drain and additional heat heavy Windows vms cause. I realize they did not use a color and filter it out, but rather tracked each window separately I imagine and pipe that through, just seems like a lot of work and largely unneeded when a simpler approach can be used and something that is not easily broken from changing APIs or ABIs.

**Comment by akallabeth** [comment]
will not be implemented for `xfreerdp` but keeping this open if someone is interested to implement this.
