### ISSUE TITLE
RDP session using Entra ID (AAD) authentication frequently fails with a timeout error

### ISSUE THREAD

**Issue by FrancisRussell** [FreeRDP/FreeRDP#9870]
**Describe the bug**
When using the Entra ID authentication flow, RDPing into a remote machine frequently (but not always) fails with a timeout error.

**To Reproduce**
- Provision a Windows machine in Microsoft Azure. It must have a system assigned identity, and login with active directory enabled.
- Ensure the user you are logging in with has the `Virtual Machine Administrator Login` role on the VM.
- On the machine you are attempting to RDP from, edit the `/etc/hosts` file so that the target machine can be referred to simply by its name rather than its fully-qualified domain name. This is necessary so that FreeRDP generates a URL with the correct value for `name` to be pasted into the brower.
- Attempt an RDP connection to the remote machine using a command similar to ```xfreerdp /sec:aad '/u:AzureAD\USERNAME@DOMAIN.TLD' /v:VM_NAME_IN_AZURE /log-level:DEBUG```
- Paste the URL printed by FreeRDP into the browser and attempt to go to it.
- Paste the URL from the browser back into FreeRDP.

**Expected behavior**
* An RDP session is established.

**Observed behavior**
* In the instances where the connection blocks after printing the lines 

```
[20:25:52:791] [712778:000ae04b] [DEBUG][com.freerdp.utils.http] - [freerdp_http_request]: headers:
POST /common/oauth2/v2.0/token HTTP/1.1
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded
Content-Length: 24


[20:25:52:835] [712778:000ae04b] [DEBUG][com.freerdp.utils.http] - [freerdp_http_request]: body:
grant_type=srv_challenge
[20:25:52:870] [712778:000ae04b] [DEBUG][com.freerdp.core.rdp] - [rdp_client_transition_to_state][0x557ebf0a4e20]: CONNECTION_STATE_NEGO --> CONNECTION_STATE_AAD
```

After some time it then prints
```
[20:26:52:927] [712778:000ae04b] [ERROR][com.freerdp.core.connection] - [rdp_client_wait_for_activation]: Timeout waiting for activation
[20:26:52:927] [712778:000ae04b] [ERROR][com.freerdp.core] - [rdp_client_wait_for_activation]: ERRCONNECT_ACTIVATION_TIMEOUT [0x0002001C]
[20:26:52:928] [712778:000ae04b] [DEBUG][com.freerdp.core.rdp] - [rdp_finalize_reset_flags][0x557ebf0a4e20]: [CONNECTION_STATE_AAD] reset finalize_sc_pdus
[20:26:52:928] [712778:000ae04b] [DEBUG][com.freerdp.core.rdp] - [rdp_client_transition_to_state][0x557ebf0a4e20]: CONNECTION_STATE_AAD --> CONNECTION_STATE_INITIAL
```

**Application details**
* FreeRDP version (`xfreerdp /version`): `This is FreeRDP version 3.2.0 (3.2.0)` (tried with the version off Flathub as well as building locally from `main` and the `3.2.0` tag)
* Command line used (some information anonymized): `xfreerdp /sec:aad '/u:AzureAD\USERNAME@DOMAIN.TLD' /v:VM_NAME_IN_AZURE /log-level:DEBUG`
* Output of `xfreerdp /buildconfig`: 
```
This is FreeRDP version 3.2.0 (3.2.0)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=1 WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_BINARY_VERSIONING=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPAQUE_SETTINGS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=ON WITH_PCSC=OFF WITH_PKCS11=ON WITH_PLATFORM_SERVER=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_PULSE=OFF WITH_RDTK=ON WITH_SAMPLE=ON WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SDL_IMAGE_DIALOGS=OFF WITH_SDL_LINK_SHARED=ON WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=ON WITH_SYSTEMD=OFF WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=ON WITH_WEBVIEW=ON WITH_WEBVIEW_QT=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:
CFLAGS:               -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -fPIC -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -g -fno-omit-frame-pointer
Compiler:            GNU, 12.2.0
Target architecture: x64
```

* OS version connecting to (server side): Windows (Windows Server 2022 Datacenter Azure Edition)
* Did my own local build with the `3.2.0` tag, dependencies installed from Debian, passing `-D-DWITH_AAD=1` to `cmake` when generating build files.

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Debian bookworm, but ended up installing some packages from testing/unstable to do a local build. Also installed the version from Flatpak, which had a similar timeout issue.
 - Architecture: [amd64, arm]: amd64.

**Additional context**
My success of achieving an RDP connection while attempting to debug this was maybe 1-2 successful connections in an hour, but the fact it sometimes succeeded seems to indicate that the usage itself is correct. I saw no obvious difference between the logs in terms of URLs printed between a successful and non-successful connection. The client appeared to be blocked in `rdp_client_wait_for_activation`. I edited the source and increased `FreeRDP_TcpAckTimeout` and `FreeRDP_TcpConnectTimeout` with no success.

**Comment by akallabeth** [comment]
@s-p-k-m @FrancisRussell anyone of you can share a log? (if public is not possible, you can message me privately @akallabeth:matrix.org in our matrix chat)

**Comment by akallabeth** [comment]
ok, most likely a configuration thing, log shared via matrix did not reveal anything.
best guess the configuration requires `UDP` transport as the connection hangs in `autodetect/multitransport` state.
