### ISSUE TITLE
xRDP connection shows the same response regardless of the error code

### ISSUE THREAD

**Issue by maoning** [FreeRDP/FreeRDP#9884]
**Describe the bug**
Full context see: https://github.com/vanhauser-thc/thc-hydra/issues/923

When connecting to a xRDP service, there's no way to tell if the password login is successful or not. The freerdpclient always return the same response. 

**To Reproduce**
1. Start xrdp service: https://github.com/satishweb/docker-xrdp 
2. Connect to the xrdp service via `xfreerdp /u:guest /p:PASSWORD /v:localhost +auth-only`
now if PASSWORD is correct this will show exactly the same response and error code as when PASSWORD is incorrect.

**Expected behavior**
The error response of a connection to xRDP service with an incorrect password should be different from when using a correct password.

**Screenshots**

See screenshots linked in: https://github.com/vanhauser-thc/thc-hydra/issues/923

**Comment by akallabeth** [comment]
the `+auth-only` flag only works like you expect with `NLA` security.
with `RDP` or `TLS` every connection is successful as the authentication is done after the session is established.

**Comment by akallabeth** [comment]
> Thank you for the details, they are really valuable in helping me understand if doing brute forcing from network is worth it or it is better to do scanning of RDP weak credentials from the host itself.
> 
> Do you know if there's any way to detect which remote it is before/during establishing the session (through raw network packet)? Or everything looks the same and the client can only tell by inspecting the graphical interface after the connection is established?

image recognition is the only reliable way here, there are no protocol fields that can reliably tell what the remote is running

**Comment by maoning** [comment]
I see, doing rdp password testing is a lot tricker than I originally hoped for. I will close this issue as everything is WAI. Thank you for the detailed answers, I really appreciate it!
