### ISSUE TITLE
Parse app parameter with quotes in command line

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#9890]
**Describe the bug**

Recient freerdp versions, app parameter changed and now the command line part also goes in the same parameter.

In the past versions, with /app-cmd you could put quotes if what was inside had spaces to transfer the command correctly to the server, but in these new versions it does not seem to be possible.

**For example:**

/u:test /app:program:"||notepad",cmd:'"Untitle 1.txt"' /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100%  /cert:ignore

[13:42:11:871] [75416:00012698] [ERROR][com.winpr.commandline] - [get_element_count]: Invalid argument (misplaced quote) 'program:||notepad,cmd:"Untitle 1.txt"'

Is it possible to improve this way of parse the app parameter?

**Application details**

This is FreeRDP version 3.2.0 (3.2.0)

/u:test /app:program:"||notepad",cmd:'"Untitle 1.txt"' /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100%  /cert:ignore

OS version connecting to (server side)
Windows Server 2008R2

OS: Fedora
Version/Distribution: 33 with openbox
Architecture: amd64

**Comment by akallabeth** [comment]
@FutureKidBuu as a quick fix you can keep the old version with `WITH_FREERDP_DEPRECATED_COMMANDLINE=ON`
