### ISSUE TITLE
Integrate abi checker as workflow

### ISSUE THREAD

**Issue by akallabeth** [FreeRDP/FreeRDP#9892]
We´re currently manually creating builds and generating abi-dumps to check if the API or ABI changed between a release.
It would be great to have that run automatically on tag push (or even pull requests for stable branches?)

**Comment by ondrejholy** [comment]
That's a great idea. Perhaps https://gitlab.gnome.org/GNOME/gnome-autoar/-/commit/2703ca85ef4ae86dfaf2d4baf70589b578dd527f resp. https://gitlab.freedesktop.org/hadess/check-abi might help with it.

**Comment by akallabeth** [comment]
@ondrejholy nice tool, extended it for `CMake` support to have it usable for us :)
working on getting the workflow integrated...
