### ISSUE TITLE
Command line help text is truncated

### ISSUE THREAD

**Issue by piterq** [FreeRDP/FreeRDP#9899]
**Describe the bug**

**To Reproduce**
1. Text output to STDOUT doesn't work on Windows so redirect help text to file:
wfreerdp.exe >help.txt
2. Open help text file in any text editor

**Expected behavior**
Help text file content should match cmdline.h source file.

**Screenshots**
![image](https://github.com/FreeRDP/FreeRDP/assets/59413148/2ac91c81-c836-42b4-85ef-c4007d664287)
![image](https://github.com/FreeRDP/FreeRDP/assets/59413148/e2301226-0cb4-4740-992c-d5c5958c78ef)

**Application details**
* FreeRDP version (`xfreerdp /version`)
3.3.1-dev0 (e21afefb8)
* Command line used
wfreerdp.exe >help.txt
* Output of `xfreerdp /buildconfig`
This is FreeRDP version 3.3.1-dev0 (e21afefb8)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H= WINPR_HAVE_EXECINFO_HEADER= WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R= WINPR_HAVE_GETPWUID_R= WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP= WINPR_HAVE_SYSLOG_H= WINPR_HAVE_SYS_EVENTFD_H= WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H= WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H= WINPR_HAVE_TM_GMTOFF= WINPR_HAVE_UNISTD_H= WINPR_HAVE_UNWIND_H= WITH_AAD=ON WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=OFF WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_BINARY_VERSIONING=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=ON WITH_CLIENT_SDL_AVAILABLE=1 WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SDL_EVENTS=OFF WITH_DEBUG_SDL_KBD_EVENTS=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_DSP_FFMPEG_AVAILABLE=0 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_INTERNAL_MD4=ON WITH_INTERNAL_MD5=ON WITH_INTERNAL_RC4=ON WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=OFF WITH_MBEDTLS=OFF WITH_MEDIA_FOUNDATION=OFF WITH_NATIVE_SSPI=ON WITH_NEON=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_PKCS11=OFF WITH_PLATFORM_SERVER=OFF WITH_PROFILER=OFF WITH_PROGRESS_BAR=ON WITH_PROXY=ON WITH_PROXY_APP=ON WITH_PROXY_EMULATE_SMARTCARD=OFF WITH_PROXY_MODULES=ON WITH_RDTK=ON WITH_SAMPLE=ON WITH_SDL_IMAGE_DIALOGS=ON WITH_SDL_LINK_SHARED=OFF WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=OFF WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=OFF WITH_SYSTEMD=OFF WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=0 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=OFF WITH_VIDEO_FFMPEG_AVAILABLE=0 WITH_WEBVIEW=OFF WITH_WIN8=OFF WITH_WINDOWS_CERT_STORE=ON WITH_WINMM=ON WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_WIN_CONSOLE=OFF
Build type:          Release
CFLAGS:              /DWIN32 /D_WINDOWS  /W4 /wo4324 /Gd
Compiler:            MSVC, 19.16.27045.0
Target architecture: x64
* OS version connecting to (server side)
none
* If available the log output from a run with `/log-level:trace 2>&1 | tee log.txt` 
* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]
 Windows
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]
 Windows 11 22H2 build 22621.3155
 - Architecture: [amd64, arm]:
 x64

**Additional context**
none

**Comment by akallabeth** [comment]
@piterq thank you.
the `stdout` thing is a windows limitation, hard to work around (and in other ways annoying) so not much we can do.
the truncated text will be fixed in next patch release.
