### ISSUE TITLE
LibreOffice menu looks distorted

### ISSUE THREAD

**Issue by avollmerhaus** [FreeRDP/FreeRDP#990]
![IMG_20130220_211358](https://f.cloud.github.com/assets/1242625/180683/754bb7ec-7c3a-11e2-85d4-6382e19985b9.jpg)

Hi,

I'm using FreeRDP version 1.1.0-dev (git 1.0.1-1972-g9fd9b), checked out of git yesterday (20.2.2013).

I'm connecting to a 2008r2 sp1 server at 16bit color depths, themes disabled.
As you can see on the screenshot, the menus in libreoffice look a little distorted.
awakecoding advised me to try software rendering (--gdi sw), which improved things a lot but didn't fully solve the problem.

**Comment by akallabeth** [comment]
Is this still an issue? current master should resolve many of these issues.

**Comment by avollmerhaus** [comment]
I tried and were unable to reproduce. (using 1.2.1_pre20150326-r1 from Gentoos Portage system)
