### ISSUE TITLE
Core Dump when trying to Build FreeRDP Stable1.1 for Arm-V8a 64 Bit

### ISSUE THREAD

**Issue by aequivalent2** [FreeRDP/FreeRDP#9909]
Hello,

i need the Android Version of your libary. I want to use the Stable 1.1 version. But when i want to build the libary for android i am recieving an Error:

[ 99%] Building C object client/Android/FreeRDPCore/jni/CMakeFiles/freerdp-android.dir/android_jni_utils.c.o[100%] Building C object client/Android/FreeRDPCore/jni/CMakeFiles/freerdp-android.dir/android_jni_callback.c.o[100%] Building C object client/Android/FreeRDPCore/jni/CMakeFiles/freerdp-android.dir/generated/android_freerdp_jni.c.o[100%] Building C object client/Android/FreeRDPCore/jni/CMakeFiles/freerdp-android.dir/android_cliprdr.c.oLinking C shared library ../libs/arm64-v8a/libfreerdp-android.socollect2: error: ld terminated with signal 11 [Segmentation fault], core dumpedgmake[2]: *** [client/Android/FreeRDPCore/jni/CMakeFiles/freerdp-android.dir/build.make:230: client/Android/FreeRDPCore/libs/arm64-v8a/libfreerdp-android.so] Error 1gmake[2]: Leaving directory '/home/administrator/Desktop/FreeRDP-stable-1.1'gmake[1]: *** [CMakeFiles/Makefile2:3108: client/Android/FreeRDPCore/jni/CMakeFiles/freerdp-android.dir/all] Error 2gmake[1]: Leaving directory '/home/administrator/Desktop/FreeRDP-stable-1.1'gmake: *** [Makefile:134: all] Error 2

That is the Outpout after the Build.

I am using following ndk and SDK
SDK:http://dl-ssl.google.com/android/repository/tools_r24-windows.zip
NDK:http://dl.google.com/android/ndk/android-ndk64-r10-linux-x86_64.tar.bz2

My Configuration is:

cmake -DCMAKE_TOOLCHAIN_FILE=cmake/AndroidToolchain.cmake \
-DANDROID_NDK="/home/administrator/Desktop/android-ndk-r10" \
-DFREERDP_ANDROID_EXTERNAL_SSL_PATH="/home/administrator/Desktop/android-external-openssl-ndk-static-master" \
-DANDROID_SDK="/home/administrator/Desktop/tools" \
-DANDROID_ABI="arm64-v8a" \
-DWITH_NEON=OFF 

I hope someone can Help my with this Error and i commited the right things

Have a nice Day

Leo

**Comment by akallabeth** [comment]
stable-1.1 is long out of support, better update to something still being developed.
