### ISSUE TITLE
Use vcpkg to manage dependencies

### ISSUE THREAD

**Issue by KangLin** [FreeRDP/FreeRDP#9924]
[Vcpkg](https://github.com/microsoft/vcpkg) helps you manage C and C++ libraries on Windows, Linux and MacOS.

it is recommended that the official freerdp use vcpkg.

Some bugs found: https://github.com/microsoft/vcpkg/pull/37015

**Comment by akallabeth** [comment]
happy about pull requests addressing issues found.

as for direct integration, I´d like to hear some more arguments than `recommended` (or even better, create a pull that shows what you have in mind)
(there are various `dependency managers` for `C` and `C++` out there and all have their benefits and downsides)
