### ISSUE TITLE
Wrong colors with freerdp-shadow-cli 3 on big-endian 

### ISSUE THREAD

**Issue by ondrejholy** [FreeRDP/FreeRDP#9925]
**Describe the bug**
Colors are wrong when `freerdp-shadow-cli` 3.3.0 is started on big-endian. 

**To Reproduce**
1. Start `freerdp-shadow-cli` 3.3.0 on big-endian system (with a properly configured SAM file)
3. Connect to it over `xfreerdp /u:user /p:password /v:server` 3.3.0 or 2.11.5 (big-endian, or little-endian doesn't matter)
4. The colors are broken

**Expected behavior**
![Screenshot from 2024-02-28 12-48-43](https://github.com/FreeRDP/FreeRDP/assets/1051384/01de15b5-e350-4756-9e47-d46ef0d4d984)

**Screenshots**
![Screenshot from 2024-02-28 12-48-03](https://github.com/FreeRDP/FreeRDP/assets/1051384/6893710c-c1b6-485e-878a-3e0d2e9aee41)

**Application details**
[xfreerdp.txt](https://github.com/FreeRDP/FreeRDP/files/14445981/xfreerdp.txt)
[freerdp-shadow-cli.txt](https://github.com/FreeRDP/FreeRDP/files/14445983/freerdp-shadow-cli.txt)

**Environment (please complete the following information):**
Fedora 41 (s390x)

**Additional context**
The colors are ok when `freerdp-shadow-cli` is started on little-endian, or with 2.11.5.

All the unit tests from the test suite passed on the big-endian machine.

**Comment by ondrejholy** [comment]
It seems that the main problem is:
```
diff --git a/server/shadow/X11/x11_shadow.c b/server/shadow/X11/x11_shadow.c
index 5c1fab18d..ef9c9062d 100644
--- a/server/shadow/X11/x11_shadow.c
+++ b/server/shadow/X11/x11_shadow.c
@@ -842,6 +842,7 @@ static int x11_shadow_screen_grab(x11ShadowSubsystem* subsystem)
                if (!empty)
                {
                        BOOL success = 0;
+                       UNIT32 format = (ImageByteOrder(subsystem->display) == LSBFirst) ? PIXEL_FORMAT_BGRX32 : PIXEL_FORMAT_XRGB32;
                        EnterCriticalSection(&surface->lock);
                        extents = region16_extents(&(surface->invalidRegion));
                        x = extents->left;
@@ -854,7 +855,7 @@ static int x11_shadow_screen_grab(x11ShadowSubsystem* subsystem)
                        WINPR_ASSERT(height >= 0);
                        success = freerdp_image_copy(surface->data, surface->format, surface->scanline, x, y,
                                                     (UINT32)width, (UINT32)height, (BYTE*)image->data,
-                                                    PIXEL_FORMAT_BGRX32, (UINT32)image->bytes_per_line, x, y,
+                                                    format, (UINT32)image->bytes_per_line, x, y,
                                                     NULL, FREERDP_FLIP_NONE);
                        LeaveCriticalSection(&surface->lock);
                        if (!success)
```
But this is just part of the necessary changes because e.g. `shadow_capture_compare` blindly compares memory blocks and doesn't care about possibly different formats.

I just wonder how is possible that the colors are ok (except for cursor) with freerdp 2.11.5...

**Comment by akallabeth** [comment]
@ondrejholy we''ve added a big endian build to our default workflow, so failures uncovered in unit tests are now discoverable.
as for real world tests, we're lacking hardware for that :grin: 

as for your patch, that looks like we just need to extend `shadow_capture_compare`  (aka `shadow_capture_compare_ex`  or something like that) to take the source and destination formats into account?
