### ISSUE TITLE
OSX - Unable to run xfreerdp - xf_pre_connect: failed to open display?

### ISSUE THREAD

**Issue by victorhooi** [FreeRDP/FreeRDP#993]
Hi,

I've installed FreeRDP on OSX using Homebrew.

I've also installed XQuartz 2.7.4.

However, when I try to run `xfreerdp`, I get the following error:

```
victorhooi$ xfreerdp 10.68.34.33
xf_pre_connect: failed to open display: 
Please check that the $DISPLAY environment variable is properly set.
freerdp_pre_connect failed
```

Are there some special things you need to do to get FreeRDP working under OSX?

Cheers,
Victor

**Comment by adamziaja** [comment]
Brew still use 1.0.2 version in 2017...
```xfreerdp +clipboard /size:1280x1024 /u:Administrator /p:'test' /v:10.1.2.3```
How can I write this in old style command? @bmiklautz

**Comment by rmpbklyn** [comment]
> @victorhooi did you reboot after installing XQuartz? DISPLAY must be set before running xfreerdp otherwise there is nothing special you need to set for xfreerdp on OSX.

how to set Display ,give an example please

**Comment by rdp** [comment]
confirmed, rebooting after having installed xquartz and this message goes away: 

[14:49:55:909] [13403:163a1dc0] [ERROR][com.freerdp.client.x11] - failed to open display: 
[14:49:55:910] [13403:163a1dc0] [ERROR][com.freerdp.client.x11] - Please check that the $DISPLAY environment variable is properly set.


Maybe freerdp could add it to the error message?
