### ISSUE TITLE
Freerdp_context_new is not working properly

### ISSUE THREAD

**Issue by aequivalent2** [FreeRDP/FreeRDP#9930]
Hello,

I am currently working with the android libary of your project. But i have a problem with the freerdp_context_new function. Everytime i am calling this fuction it returns false and the previously allocated memory stays blank. Right now i am working inside unity.

```
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using RDP_ALT;
using System.Runtime.InteropServices;
using System;


public unsafe class Alternative : MonoBehaviour
{
    [DllImport("libfreerdp2.so", CallingConvention = CallingConvention.Cdecl)]
    public static extern bool freerdp_context_new(IntPtr instance);

    [DllImport("libfreerdp2.so", CallingConvention = CallingConvention.Cdecl)]
    public static extern IntPtr freerdp_new();


    void Start()
    {
        IntPtr Context = freerdp_new();
        Debug.Log(freerdp_context_new(Context));
    }

    
}
```

I hope someone can Help my with this Error 

Have a nice Day

Leo

**Comment by akallabeth** [comment]
@aequivalent2 you´re holding it wrong :grin: 
joking aside, check the `client/Sample` folder in source code and use that as a starting point. (you most likely only need to rename the main method and fill in the stubs not implemented)

you´re using the wrong API functions, these are 2 levels below the ones you are interested in.

To give you an idea:
* `libfreerdp-client2.so` is the one that holds the abstractions for a client implementation
* `libfreerdp2.so` holds the abstractions for basic protocol related stuff and common code for client and server implementations
* `libwinpr2.so` is a wrapper library for platform independent functions we use all over the place

also keep in mind that android library loader has a bug (or feature?) that it only calls the `JNI_OnLoad` function of the library you explicitly load in your code, so load all `FreeRDP` related libraries manually in reverse dependency order

also, I´d recommend directly using our newer releases as `FreeRDP 2` will get less attention now that we´ve released version 3

**Comment by aequivalent2** [comment]
@akallabeth Sorry for this interruption again I am not sure if i am wrong but we created a C# script based on the sample and it is not working either we are faceing the same problem. We load the libraries as well in another script with DLL import. Thanks for the  Feedback

**Comment by akallabeth** [comment]
@aequivalent2 well, the sample client works and also the `SDL` client uses the same pattern. (`C++` client) therefore not sure what your issue is.
you will most likely have to create a custom client context struct extending the client common struct that holds at least a reference to the `C#` class instance and create the rest of the functions just like in the sample.

also the android client uses a similar pattern (with java JNI) so maybe get some ideas there?

**Comment by aequivalent2** [comment]
@akallabeth after a bit more Debugging i found out that freerdp_client_context_new() is failing because the  creation of a new context fails. Specifically the fuction GetKnownPath which is called in freerdp_settings_new() returns null which then triggers a failure. I am building into a quest 3 within unity. Thanks for your further replies

**Comment by akallabeth** [comment]
@aequivalent2 ok, so you are using an empty environment not handled?

`GetKnownPath` is a wrapper around:
*  `XDG_*` variables for various file locations (unix)
* `SHGetFolderPath` (windows)
* `ios_get_temp`, ... (IOS)

so, you can either set up `ENV` variables conforming to the `XDG_*` variables to specify where to store various files or extend the file `./winpr/libwinpr/path/shell.c` with your platform specific code.

as you´re the first one porting to this environment you may find one or two more glitches on the way.

**Comment by aequivalent2** [comment]
@akallabeth Hello again, we brought it to live, but we are failing, when we are trying to set the settings for the connection. We could not find the explicit way inside the sample. Could you help us?

**Comment by akallabeth** [comment]
@aequivalent2 check the commandline parser?

**Comment by aequivalent2** [comment]
@akallabeth Hello, and sorry for my late response. We could not find some perfect implementation for our settings. We are students from a german school and are participating in the Jugend-Forscht contest. Is it maybe possible for you to help us via Teams or something else? 

Kind regards 

Leo

**Comment by akallabeth** [comment]
@aequivalent2 join our matrix chat, you can pm me there.
