### ISSUE TITLE
ERRINFO_DECRYPT_FAILED appears randomly.

### ISSUE THREAD

**Issue by KangLin** [FreeRDP/FreeRDP#9937]
There was an error in [RabbitRemoteControl](https://github.com/KangLin/RabbitRemoteControl) . It appears randomly. What causes this.

I've found that when I use the clipboard, the chances of showing up are a bit greater.
One thread processes one connection in the RabbitRemoteControl. The clipboard operation is also in this thread. When the clipboard is operating, there is a brief blockage.

```
09:10:44.078 5807|6007 D FreeRDP.Log - received Heartbeat PDU -> period=1, count1=8, count2=8
09:10:44.238 5807|6007 D FreeRDP.Log - updating RDP key
09:10:45.111 5807|6007 D FreeRDP.Log - received Heartbeat PDU -> period=1, count1=8, count2=8
09:10:45.549 5807|6007 D FreeRDP.Log - recv Set Error Info Data PDU (0x2F), length: 22
09:10:45.549 5807|6007 I FreeRDP.Log - ERRINFO_DECRYPT_FAILED (0x00001192):(a) Decryption using Standard RDP Security mechanisms (section 5.3.6) failed.
(b) Session key creation using Standard RDP Security mechanisms (section 5.3.5) failed.
09:10:45.549 5807|6007 E FreeRDP.Log - rdp_set_error_info:freerdp_set_last_error_ex ERRINFO_DECRYPT_FAILED [0x00011192]
09:10:45.549 5807|6007 E FreeRDP.Log - BIO_read returned a system error 104: 连接被对方重置
09:10:45.549 5807|6007 D FreeRDP.Log - transport_check_fds: transport_read_pdu() - -1
09:10:45.549 5807|6007 D FreeRDP.Log - transport_check_fds() - -1
09:10:45.549 5807|6007 D FreeRDP.Log - rdp_check_fds() - -1
```

[2024-03-05_0001.log](https://github.com/FreeRDP/FreeRDP/files/14490471/2024-03-05_0001.log)

**Comment by akallabeth** [comment]
@KangLin which version of FreeRDP do you use?

as for the error, that is `RDP` security related (the weakest of all modes)
it has some custom key rollover after a certain amount of data was transferred and some older versions did have issues with that.

whatever the reason, I´d recommend to just switch the server to `NLA` or `TLS` modes (depending on what you need) and ditch the `RDP` security mode.

**Comment by KangLin** [comment]
freerdp 2.60-2.10.0 is the issue.
Which version solved？

**Comment by akallabeth** [comment]
2.9.0 got some fixes.

**Comment by KangLin** [comment]
Tested 2.11.5 and it still appears.

**Comment by akallabeth** [comment]
@KangLin the `RDP` security mode is quite complex (you have custom key rollover and (per session global) sequence counters)
can´t tell exactly.

will check your code, give me a bit of time...

**Comment by akallabeth** [comment]
@KangLin ok, there are a few issues with your project (missing files, broken so versioning and wrong installation locations)
will take a little bit longer to get that up and running :/

**Comment by KangLin** [comment]
> @KangLin ok, there are a few issues with your project (missing files, broken so versioning and wrong installation locations) will take a little bit longer to get that up and running :/

@akallabeth Is there any more details？

**Comment by akallabeth** [comment]
@KangLin the installed `.so` files do not follow the versioning scheme in use by unix systems (should be handled correct by `CMake` by default? check freerdp installed files, there should be `libfoo.so` in dev package, `libfoo.so.1` link to `libfoo.so.1.1` link to actual lib `libfoo.so.1.1.1`

there are wrong install locations (most likely due to windows path conventions being used?) `.so` installed to `bin` directory

I see you have a `debian` build recipie there working around these things, but if `CMake` is run plain it defaults to these wrong paths.

also, I think the whole `license.md` and others should be in `share/doc` or similar, not root?

anyhow, makes it hard to just install and run. (I do prefer building my libs step by step to find out what is going on)

**Comment by KangLin** [comment]
Please use the master of RemoteCommon and RabbitRemoteControl.

the code of master is correct build.

the install folder is /opt/RabbitRemoteControl.
run RabbitRemoteControl.sh , it handle load .so

when debug, set CMAKE_INSTALL_prefix to 'pwd'/install

**Comment by akallabeth** [comment]
@KangLin using master of both.
there is also a missing `share/RabbitCommonTests.sh` file referenced in `RabbitCommon`

**Comment by akallabeth** [comment]
ok, had a look.
looks like you do not set up the session properly and it uses antiquated paths that are buggy.

the other stuff (library naming, ...) are minor issues, but you lack complete support of everything newer than windows XP ;)

**Comment by KangLin** [comment]
Because the keyboard and mouse sending thread is different from the freerdp running thread and is not in sync, there is a random error.
After syncing, the issue is resolved.

**Comment by akallabeth** [comment]
@KangLin so you are in the antiquated code paths?  `RDP` security is something that should not be used anymore.
we´re happy about pull requests though ;)

**Comment by KangLin** [comment]
@akallabeth This is a usage error, not a FreeRDP issue.
However, it can be clearly written in the document :)

**Comment by akallabeth** [comment]
@KangLin yes, that is only true for `RDP` security as there the messages must be in some order due to the way the encryption is done.
with `NLA/TLS` you should not have that restriction.
