### ISSUE TITLE
Clipboard Support on Android Mobile and Chromebook

### ISSUE THREAD

**Issue by Pankajbadhan034** [FreeRDP/FreeRDP#9941]
Do you provide clipboard support for Android mobile and Chromebook?  
Copy/paste is not working from the Local device to Remote session.

**Comment by akallabeth** [comment]
and you are using?
anyhow, not an issue but a question, so closing.

**Comment by Pankajbadhan034** [comment]
Hi, thx for responding...
And Yes i am using RDP library and Clipboard copy/paste  working in android tab only.
But in android mobile and Chromebook it is not working.
So any suggestion what needs to be done for it to work with android mobile as well ?

**Comment by akallabeth** [comment]
@Pankajbadhan034 please try to phrase your responses a little bit less generic
* we still do not know what you´re using (some kind of `FreeRDP`, ok, given, but that is not enough to answer correctly)
* a little more detail on `copy/paste` not working (with what? we still do not know which application you are using)

**Comment by Pankajbadhan034** [comment]
Hi, thx for responding...

I have implemented FreeRDP in my android app. I have remote connection working with FreeRDP Libaray in android.
But the problem i am getting is with the copy to clipboard functionality in android. When i copy text or url from my local device and trying to paste in remote session .It is not working. Please check the video for the issue.

Attached is the video of the issue.
https://github.com/FreeRDP/FreeRDP/assets/112693544/50ab94be-8411-4823-ac3a-3c262a512f1b

**Comment by akallabeth** [comment]
@Pankajbadhan034 ok, so you did not implement clipboard in your app and expect it to work?
check the android client in source and how that handles the corresponding events.

**Comment by Pankajbadhan034** [comment]
The clipboard functionality is already implemented in the freeRDP .
i just have login page and then i redirect to this freeRDP library . . 
So it looks like , it is not working for android...

**Comment by akallabeth** [comment]
> The clipboard functionality is already implemented in the freeRDP . i just have login page and then i redirect to this freeRDP library . . So it looks like , it is not working for android...

well, it works with the in source client found in `client/Android` (for the limited format support of `text copy & paste`)
as for your code, I have no idea what you´re doing.
