### ISSUE TITLE
SegmentationFault error while using +auth-only

### ISSUE THREAD

**Issue by Maheshmuddunuru** [FreeRDP/FreeRDP#9946]
**Title:** SegmentationFault error while using +auth-only

**Description:**
I encountered an issue while utilizing the xfreerdp tool within my scripts to authenticate Remote Desktop Protocol (RDP) connections to remote servers without the necessity for a graphical user interface (GUI). Specifically, I was employing the +auth-only option to solely perform authentication. Previously, I was using version 2.11 of xfreerdp, and the authentication process functioned correctly.

However, upon upgrading to the latest version of the freerdp tool on a new machine, xfreerdp was updated to version 3.3.0. Subsequently, when executing the command with the updated version, I encountered a "Segmentation fault" error. This error disrupts the functionality of the authentication process, 

**Environment:**
- MACOS Ventura 13.5.2 M2 pro(VM)
- 
**Steps to Reproduce:**
1. Try to connect to a remote server with xfreerdp /u:username /p:pass /v:server_ip +auth-only
   ...

**Expected Behavior:**
+auth-only option should not have any segmentation fault errors. Should work fine as in verison 2.11
![Expected output](https://github.com/FreeRDP/FreeRDP/assets/29726533/faee3af2-0761-4f88-9766-1f3a63b29176)

**Actual Behavior:**
Using +auth-only option results in segmentaion Fault
<img width="505" alt="Actual output" src="https://github.com/FreeRDP/FreeRDP/assets/29726533/a256106c-8b6d-4dd6-a6bb-a1c5ea6fbef2">

**Comment by akallabeth** [comment]
nice catch!
as a workaround, check you have a `DISPLAY=somevalue` variable set in your environment. (this is a `X11` application after all)

**Comment by Maheshmuddunuru** [comment]
Hi @akallabeth ,

The DISPLAY variable is already set and xfreerdp is able to connect to remote server without the +auth-only option. However this will open a x11 window which I don’t need and I’m only trying to check the authentication.
Im unable to revert back to older version(2.11) in which +auth-only works fine. Is there any workaround until this fix gets merged?

**Comment by akallabeth** [comment]
@Maheshmuddunuru I did reproduce the issue here with unsetting `DISPLAY` and it is already fixed on master.
