### ISSUE TITLE
Unable to connect with FreeRDP3 using /sec:rdp

### ISSUE THREAD

**Issue by ndonkersloot** [FreeRDP/FreeRDP#9948]
**Describe the bug**
Starting from FreeRDP 3 I cannot connect to a Windows Server that has only support for /sec:rdp.
Also when connecting using /sec:rdp I still get a pop-up to enter credentials (for NLA I guess?) which is disabled on purpose on the Windows Server. 

**To Reproduce**
Connect to a Windows Server that has TLS and NLA disabled.
flatpak run com.freerdp.FreeRDP /v:ip_address /sec:rdp

Enter credentials in the pop-up that follows.
No connection is possible.

**Expected behavior**
I expected it to:
1. Not prompt for credentials as no NLA should be used.
2. Make a connection to the server.

When connecting using FreeRDP 2
xfreerdp /v:ip_address /sec:rdp

It just works.

**Application details**
For FreeRDP 3 i'm using the latest flatpak version 3.3.0.
For FreeRDP 2 i'm using the latest version available 2.11.5

xfreerdp /buildconfig
`This is FreeRDP version 2.11.5 (2.11.5)
Build configuration: BUILD_TESTING=OFF BUILTIN_CHANNELS=OFF HAVE_AIO_H=1 HAVE_EXECINFO_BACKTRACE=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 HAVE_EXECINFO_H=ON HAVE_EXECINFO_HEADER=1 HAVE_FCNTL_H=1 HAVE_GETLOGIN_R=1 HAVE_GETPWUID_R=1 HAVE_INTTYPES_H=1 HAVE_JOURNALD_H=TRUE HAVE_MATH_C99_LONG_DOUBLE=1 HAVE_PIXMAN_REGION=OFF HAVE_POLL_H=1 HAVE_PTHREAD_MUTEX_TIMEDLOCK=ON HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 HAVE_SYSLOG_H=1 HAVE_SYS_EVENTFD_H=1 HAVE_SYS_FILIO_H= HAVE_SYS_MODEM_H= HAVE_SYS_SELECT_H=1 HAVE_SYS_SOCKIO_H= HAVE_SYS_STRTIO_H= HAVE_SYS_TIMERFD_H=1 HAVE_TM_GMTOFF=1 HAVE_UNISTD_H=1 HAVE_XI_TOUCH_CLASS=1 WITH_ALSA=ON WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_CLIPRDR=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DIRECTFB=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=ON WITH_GSSAPI=OFF WITH_ICU=ON WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_LAME=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSYSTEMD=ON WITH_MACAUDIO=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSLES=OFF WITH_OPENSSL=ON WITH_OSS=ON WITH_PAM=ON WITH_PCSC=ON WITH_PROFILER=OFF WITH_PROXY=ON WITH_PROXY_MODULES=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=ON WITH_SERVER_CHANNELS=ON WITH_SERVER_INTERFACE=ON WITH_SHADOW=ON WITH_SHADOW_MAC=ON WITH_SHADOW_X11=ON WITH_SMARTCARD_INSPECT=OFF WITH_SOXR=ON WITH_SSE2=ON WITH_SWSCALE=OFF WITH_THIRD_PARTY=OFF WITH_VAAPI=OFF WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_WAYLAND=ON WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XDAMAGE=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XKBFILE=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XSHM=ON WITH_XTEST=ON WITH_XV=ON WITH_ZLIB=ON
Build type:          Release
CFLAGS:              -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64   -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -Wall -Wno-unused-result -Wno-unused-but-set-variable -Wno-deprecated-declarations -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer -DWINPR_DLL
Compiler:            GNU, 13.2.1
Target architecture: x64
`

**Environment (please complete the following information):**
 - OS: Linux
 - Version/Distribution: Fedora Silverblue 39
 - Architecture: x64

**Comment by akallabeth** [comment]
@ndonkersloot 

first a word about `/sec:rdp`: that is always a VERY BAD idea.
I get why you disable `NLA` (you want the windows logon screen), but there is `/sec:TLS` that is from that perspective the same as `/sec:rdp` but with proper `TLS`)

as for the `unable to connect` :
* are you only talking about the credential dialog? behavior changed with `FreeRDP3` and you always need to provide `/u: /p:` to not get that dialog. (just use empty values if you don´t want the dialog but not provide any credentials either)

**Comment by akallabeth** [comment]
ok, checked with current flatpak:
* `flatpak run com.freerdp.FreeRDP /v:host /sec:tls /p: /u:`  works as expected (get the logon screen)
* `flatpak run com.freerdp.FreeRDP /v:host /sec:tls `  works as expected (get the credential dialog, hit accept and you get the logon screen)

**Comment by akallabeth** [comment]
@ndonkersloot it does work, it is just insecure.

**Comment by ndonkersloot** [comment]
@akallabeth 
In my case it does not, that's the main reason why I created this issue.
I've created a video file showcasing my issue.
[freerdp.webm](https://github.com/FreeRDP/FreeRDP/assets/10894613/c806a8af-71a0-49a3-9b3d-d0b46614488f)

I've also added a trace log.
I have this with multiple server,  but for this example I only focus on one.
[trace.log](https://github.com/FreeRDP/FreeRDP/files/14538534/trace.log)

**Comment by akallabeth** [comment]
@ndonkersloot which openssl version and are legacy ciphers allowed?
as already mentioned, RDP security works.

what might not be happy is your distribution or SSL policy.

**Comment by ndonkersloot** [comment]
@akallabeth 
Thank you for that insight, i'll experiment with that.

**Comment by akallabeth** [comment]
@ndonkersloot you might want to try with a build from master though, I´ve added additional logging with https://github.com/FreeRDP/FreeRDP/pull/9943 that might be helpful

**Comment by ndonkersloot** [comment]
@akallabeth 
I'm using openssl 3.1.1 on my system (fedora silverblue 39).

`rpm -qa | grep openssl-libs
openssl-libs-3.1.1-4.fc39.x86_64
`
I've tried the `LEGACY` crypto-policies using `update-crypto-policies` but that didn't solve the issue.
I'm gonna build from master later to have additional logging.

**Comment by akallabeth** [comment]
@ndonkersloot you can build a flatpak from source, just check out and run:
```
cd <sourcedir>/packaging/flatpak
./build-bundle.sh
```
(requires `flatpak-builder` and `flatpak` installed)

install the bundle created and run that one. (you have the improved logging from `master` now, maybe something will tell you what is wrong)

**Comment by ndonkersloot** [comment]
I haven't put a lot of time in it yet but noticed two things:

I get errors when running that the `/dev/dri/card1` can't be found. I think the permission `--device=dri` needs to be set in the flatpak manifest. Once I do that the error goes away.

```
amdgpu_device_initialize: amdgpu_get_auth (1) failed (-1)
amdgpu: amdgpu_device_initialize failed.
glx: failed to create dri3 screen
failed to load driver: radeonsi
failed to open /dev/dri/card1: No such file or directory
failed to load driver: radeonsi
```

I get errors regarding the x509 certificate, I only get this with the flatpak version, not with the local repository install. So I'm starting to think this is the reason it doesn't work.

```
[ERROR][com.freerdp.core] - [update_x509_from_info]: failed to update x509 from rdpCertInfo
[ERROR][com.freerdp.core] - [certificate_read_server_x509_certificate_chain]: Failed to read x509 certificate
[ERROR][com.freerdp.core.gcc] - [gcc_read_conference_create_response]: gcc_read_conference_create_response: gcc_read_server_data_blocks failed
[ERROR][com.freerdp.core] - [mcs_recv_connect_response]: gcc_read_conference_create_response failed
[ERROR][com.freerdp.core.rdp] - [rdp_recv_callback_int][0x561a71e0f050]: mcs_recv_connect_response failure
[ERROR][com.freerdp.core.rdp] - [rdp_recv_callback_int][0x561a71e0f050]: CONNECTION_STATE_MCS_CREATE_RESPONSE status STATE_RUN_FAILED [-1]
[ERROR][com.freerdp.core.transport] - [transport_check_fds]: transport_check_fds: transport->ReceiveCallback() - STATE_RUN_FAILED [-1]
[ERROR][com.freerdp.core] - [rdp_client_wait_for_activation]: ERRCONNECT_CONNECT_TRANSPORT_FAILED [0x0002000D]
```

I'll definitely going to spend some more time at this, but maybe this error speaks more to you than it does to me right now.

**Comment by akallabeth** [comment]
@ndonkersloot ok, that confirms my suspicion: `[update_x509_from_info]: failed to update x509 from rdpCertInfo` means that the `SSL` is not allowing raw `RSA` operations.

**Comment by akallabeth** [comment]
> I get errors when running that the /dev/dri/card1 can't be found. I think the permission --device=dri needs to be set in the flatpak manifest. Once I do that the error goes away.

will have a look.

**Comment by ndonkersloot** [comment]
> @ndonkersloot ok, that confirms my suspicion: `[update_x509_from_info]: failed to update x509 from rdpCertInfo` means that the `SSL` is not allowing raw `RSA` operations.

I'm not a programmer, let alone a C programmer, but I did some digging and think it goes into this [fail](https://github.com/FreeRDP/FreeRDP/blob/70a8b185be436218c1453d9b5760f70255869f27/libfreerdp/crypto/certificate.c#L569).
I'm not sure how to x509 cert is created, but my gut is pointing to winpr-makecert.

I've entered the flatpak sandbox with bash to poke around there to verify some things:

The flatpak itself has openSSL 3.1.5:
```
bash-5.2$ openssl version
OpenSSL 3.1.5 30 Jan 2024 (Library: OpenSSL 3.1.5 30 Jan 2024)
```

A connection from the flatpak to the RDP server is possible from within the flatpak itself:
```
bash-5.2$ openssl s_client -connect 172.19.123.184:3389
CONNECTED(00000003)
```

Creating a certificate with openssl from within the flatpak sandbox works:
```
bash-5.2$ openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out private_key.pem
.....+.+..+.+..............+++++++++++++++++++++++++++++++++++++++*....+..+.........+++++++++++++++++++++++++++++\++++++++++*....+...+...............+..+.......+......+..+..........+........+.........+.+........+......+.+...+..............+.+......+........+.....................+............+...+.+........+.............+.................+.....................+.......+...+......+.....+...+.+............+...+......+...+.....+...+.........+.+.....+.............+..............+.+..+....+......+..+.+..+.......+..+...+......+..........+......+...+.....+...+...++++++
..+++++++++++++++++++++++++++++++++++++++*......+...........+.+.....+++++++++++++++++++++++++++++++++++++++*...+...+..+..................+.+..............+.+.....+.........+...+............+..................+.......+............+.....+....+...........+..........+........+.+............+.....+..........+...+......+...........+...+....+........+....+...........+...++++++
bash-5.2$ ls
private_key.pem
```

Creating a certificate with winpr-makecert from within the flatpak sandbox does work:
```
bash-5.2$ /app/bin/winpr-makecert -rdp
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 3750714 (0x393b3a)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=lenovo-t14
        Validity
            Not Before: Mar 13 09:33:38 2024 GMT
            Not After : Mar 13 09:33:38 2025 GMT
        Subject: CN=lenovo-t14
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c1:c4:54:48:8a:c5:26:d3:67:a1:a9:71:13:a6:
                    d5:d9:e3:ca:b1:7d:2f:d8:d2:63:0c:6a:dc:95:6b:
                    07:0f:6c:a9:92:20:b0:c5:bb:ae:fd:92:b0:fc:82:
                    72:1a:3a:1e:2f:86:88:02:b8:06:55:97:79:96:a0:
                    28:a7:50:07:c6:49:43:8f:93:82:ca:57:21:94:16:
                    fc:13:7d:92:3f:87:7c:a4:ec:9a:46:2c:48:9c:00:
                    dd:c8:92:99:1a:44:8e:4d:e5:ec:5d:c2:85:71:69:
                    90:3d:45:0d:bb:05:4a:84:b9:f2:bf:c0:b9:22:fd:
                    72:ff:e6:45:bd:8b:e7:2b:e6:1d:22:ef:67:b6:87:
                    20:ff:b5:b1:ea:0e:c5:28:ce:8a:28:7e:0d:37:a8:
                    ad:34:73:32:a1:c7:59:b9:f2:5e:35:9c:f8:2f:1a:
                    2a:43:31:34:d5:b3:ec:a0:f1:40:93:f5:ae:4c:31:
                    9f:a2:e1:b4:c1:97:31:54:09:62:c2:85:2a:84:a7:
                    9d:71:77:50:a6:5f:78:7f:8f:66:44:a6:ec:ab:41:
                    1e:76:f8:77:51:5f:57:f2:0d:c5:9c:46:5e:21:cf:
                    a4:64:ed:05:15:c0:bb:67:c2:98:1d:f4:18:30:23:
                    5b:e8:87:9b:71:17:d8:84:b2:68:e0:99:71:1c:b5:
                    f4:8f
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        6a:c1:07:08:a9:60:29:e6:d1:22:ab:0f:6b:77:e2:53:d3:f1:
        b8:25:3f:3a:df:76:b3:6a:1a:1f:ba:71:22:7c:0e:e8:7f:b5:
        51:c5:55:9b:e0:b6:a2:e2:d7:61:a2:16:e7:a2:65:ca:b0:ba:
        03:ad:95:6c:12:a3:48:81:66:c5:61:eb:87:1e:d3:23:0c:b4:
        c4:a6:de:58:1f:3d:4f:f9:d0:9a:85:6e:0a:6b:b8:88:2b:31:
        4c:d3:b0:96:97:66:d7:f3:ad:54:f4:97:c7:70:8b:00:3c:65:
        09:32:c0:c0:96:24:04:df:43:0b:30:6f:ba:14:85:b5:3d:25:
        50:7d:bb:f0:19:39:85:be:fb:7b:d4:bf:53:eb:3d:8c:1e:a1:
        60:91:b5:5e:60:f3:89:21:ac:2f:f8:21:c3:63:f1:f3:3b:6c:
        a0:db:1a:91:7b:3e:7a:d7:94:b3:2d:6d:ec:07:e0:0d:6a:97:
        0c:d2:15:ae:3e:c9:d8:a3:91:d6:7e:e7:8a:e1:0b:09:ef:06:
        77:15:79:bb:5c:ae:67:e3:73:88:47:65:02:f9:17:e8:44:fa:
        f3:f8:15:06:43:6b:cd:44:e1:3a:a2:6a:fa:92:e9:da:ec:15:
        41:5a:06:8d:15:d9:b7:9d:8b:00:76:53:19:09:1f:b2:48:7b:
        e7:6e:36:a7

```

Maybe this info is helpful for you.
At a later time I'll poke around some more to hopefully locate and fix the issue.

**Comment by akallabeth** [comment]
there is quite a difference.
* the `winpr-makecert` just creates a new certificate (standard `API` calls)
* `update_x509_from_info` creates a `RSA` certificate from raw numbers (low level deprecated `API` calls)

**Comment by ndonkersloot** [comment]
I haven't found the time yet to look further into this, but I'm committed to do so.

Can you reproduce the issue yourself? 
Could you re-open the issue as it still persists, although only for the flatpak release.

**Comment by akallabeth** [comment]
yes. you can check with:
1. `flatpak run --command=bash com.freerdp.FreeRDP`
2. `openssl list -providers`
3. output should be: 
```
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.1.5
    status: active
    ```

**Comment by ndonkersloot** [comment]
That is correct:
```
[📦 com.freerdp.FreeRDP ~]$ openssl list -providers
Providers:
  default
    name: OpenSSL Default Provider
    version: 3.1.5
    status: active
```
This is the output from a build of the latest master where the issue is reproducible.
