### ISSUE TITLE
Empty HTTPS_PROXY variable in env

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#9951]
**Describe the bug**

In freerdp 3.2 versions, defining empty variables as HTTPS_PROXY/https_proxy makes freerdp believe that there is a proxy configured in the environment and fails to launch it.

**For example:**

/u:test /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100%  /cert:ignore
![image](https://github.com/FreeRDP/FreeRDP/assets/25820234/1de949e7-afd8-40ba-93b7-3fe328f79c3a)

part of the env command output:

HTTPS_PROXY=
https_proxy=

I have verified that by unsetting these variables, freerdp can now connect to the server directly without problems.

For me, this is a irregular behavior in parse environment variables and I wonder if allowing definition of those empty variables could be resolved.

**Application details**

This is FreeRDP version 3.2.0 (3.2.0)

/u:test /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100%  /cert:ignore

OS version connecting to (server side)
Windows Server 2008R2

OS: Fedora
Version/Distribution: 33 with openbox
Architecture: amd64

**Comment by akallabeth** [comment]
https://github.com/FreeRDP/FreeRDP/pull/9929

**Comment by akallabeth** [comment]
> ERRCONNECT_DNS_NAME_NOT_FOUND

then something in your env is wrong?
just did test with current master:
test server:
1. set up `Xepyr :23 -screen 1280x768`
2. `DISPLAY=:23 xterm&`
3. `DISPLAY=:23 openbox&`
4. `DISPLAY=:23 freerdp-shadow-cli /port:3333 -auth`

connect with:
1. `export HTTPS_PROXY=""` to have an empty proxy variable
2. connect with `xfreerdp /v:localhost:3333 /u:foo /p:bar /d:dom /title:test ...` (all your arguments)
3. et voila! connection established...

**Comment by FutureKidBuu** [comment]
I just saw that my build was not updated, sorry for that, I do connect with empty variables, thanks again
