### ISSUE TITLE
Problem reading password from a file without line terminators

### ISSUE THREAD

**Issue by FutureKidBuu** [FreeRDP/FreeRDP#9952]
**Describe the bug**

In freerdp 3.2 versions, I have a problem when freerdp reading the password from a file that does not have a line break (\n)

**For example:**

cat /tmp/password_tmp | xfreerdp /u:test /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100%  /cert:ignore

Failed file test:

_futurekidbuu@futurekidbuu:$ file /tmp/password_tmp 
/tmp/password_tmp: ASCII text with no line terminators_

Successful file test:

_futurekidbuu@futurekidbuu:$ file /tmp/password_tmp 
/tmp/password_tmp: ASCII text_

Is it possible to extend the check for that type of files without line terminators?

**Application details**

This is FreeRDP version 3.2.0 (3.2.0)

cat /tmp/password_tmp | xfreerdp /u:test /title:"Test" /d:test.test /smartcard /p:"test" /v:localhost:3389 /size:100%  /cert:ignore

OS version connecting to (server side)
Windows Server 2008R2

OS: Fedora
Version/Distribution: 33 with openbox
Architecture: amd64

**Comment by akallabeth** [comment]
long story short, no.
we already have a couple of ways to provide the commandline without being an argument.
check the `/args-from` option.

the way you use it is actually not one we intended, it just feeds in the text required to submit int in the terminal prompt ;)
