### ISSUE TITLE
Two presses of RCtrl key causes FreeRDP window to lose focus, even when separated by other key presses

### ISSUE THREAD

**Issue by whitpa** [FreeRDP/FreeRDP#9959]
**Describe the bug**
Pressing the right control key twice in an X11 FreeRDP session - not just in quick succession, but under *any* circumstances, including when separated by an arbitrary number of other key presses - causes the FreeRDP window to lose focus.

**To Reproduce**
Steps to reproduce the behavior (assumes Windows RDP server, Linux RDP client, and that Alt+Tab performs a window switch on both local and remote window managers):
1. Open a couple of X11 windows on the client (anything, e.g. xterm or whatever).
2. Initiate a fullscreen FreeRDP connection to a Windows RDP server.
3. In the Windows desktop, open a couple of windows (anything, e.g. notepad or whatever).
4. Press Alt+Tab and verify that remote window switching behavior occurs.
5. Press and release the RCtrl (right control) key.
6. Wait a second or two then press and release the 'a' key.
7. Press and release the RCtrl key again.
8. Press Alt+Tab again - local window switching behavior will be observed, i.e. FreeRDP window has lost keyboard focus.

**Expected behavior**
The FreeRDP window should still have keyboard focus, and therefore remote window switching behavior should be observed.  It would be OK if a double-tap of RCtrl were deliberately intended to ungrab focus, but FreeRDP should not do so with seconds between RCtrl key presses and/or an intervening keystroke.

**Application details**
* FreeRDP version (`xfreerdp /version`)
Problem observed in both 2.11.5 and 3.2.0.

* Command line used (FreeRDP 3.2.0 case):
`xfreerdp /client-hostname:pbe0b02d1 /multimon /dynamic-resolution /f /bpp:32 /cert:ignore /u:Administrator /d:TEST /from-stdin:force /network:auto /rfx /gfx:AVC420 +clipboard +multitouch /audio-mode:0 /sound:sys:alsa,quality:high /drive:storage,/media /printer /v:192.168.1.98`

* Output of `xfreerdp /buildconfig` (FreeRDP 3.2.0 case, build of FreeRDP 2.11.5 is similar ):
`This is FreeRDP version 3.2.0 (3.2.0)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=ON WITH_BINARY_VERSIONING=OFF WITH_CAIRO=ON WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=OFF WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=ON WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_URBDRC=OFF WITH_DEBUG_WND=OFF WITH_DEBUG_X11=OFF WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=ON WITH_DSP_FFMPEG_AVAILABLE=1 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=ON WITH_FREERDP_DEPRECATED=OFF WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=ON WITH_GFX_H264=ON WITH_GPROF=OFF WITH_GSM=OFF WITH_GSSAPI=OFF WITH_GSTREAMER_1_0=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=OFF WITH_KRB5=ON WITH_KRB5_NO_NTLM_FALLBACK=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=ON WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=OFF WITH_PCSC=ON WITH_PKCS11=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=ON WITH_SYSTEMD=ON WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=OFF WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=1 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=ON WITH_VIDEO_FFMPEG_AVAILABLE=1 WITH_WAYLAND=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_X264=OFF WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=ON WITH_XV=ON
Build type:          Release
CFLAGS:              -O2 -march=armv7-a -mfloat-abi=hard -mfpu=vfpv3-d16 -Wall -Wpedantic -Wno-padded -Wno-cast-align -Wno-declaration-after-statement -Wall -fvisibility=hidden -Wimplicit-function-declaration -Wredundant-decls -fno-omit-frame-pointer
Compiler:            GNU, 12.2.0
Target architecture: ARM`

* OS version connecting to (server side)
Windows Server 2016

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Windows/Android/..]
 Linux
 - Version/Distribution: [e.g. Debian 10, Windows 2008, Android 10]
 Debian 12
 - Architecture: [amd64, arm]:
 armhf

**Additional context**

- Problem does not occur using LCtrl key, only RCtrl.
- Our Linux-side window manager is xfwm4, if that is at all relevant for reproduction of problem.

**Comment by akallabeth** [comment]
right control is the `ungrab` key so this is expected.

**Comment by whitpa** [comment]
That behavior is not documented anywhere, as far as I can tell.  It's also weird - why does it have to be pressed twice, and why not as a double-tap only?

Regardless, this behavior is unwanted by one of our customers.  How can it be turned off (without source code modification, or ugly hacks such as xmodmap)?  I don't see any related command line switch.

**Comment by akallabeth** [comment]
@whitpa yes, documentation always needs improvement :/
as for the hitting twice, that is indeed a bug, should be at first press/release

there is also currently no configuration for this (only had time to add a config file for sdl-client)

**Comment by bebras123** [comment]
Hi, after this fix RCtrl does not ungrab anymore. Do i have to create some configuration at
`/home/username/.var/app/com.freerdp.FreeRDP/config/FreeRDP/FreeRDP/sdl-freerdp.json` to make ungrab work with RCtrl? 
If so example would be nice as there is no `sdl-freerdp.json` file in the provided path.

I am running freerdp  `flatpak run com.freerdp.FreeRDP /u:xxx /v:xxx /f /clipboard +auto-reconnect /log-level:DEBUG`
Version 3.4.0, Linux Mint 21.3, x11, Cinnamon 6.0.4

**Comment by akallabeth** [comment]
@bebras123 this bug was for `xfreerdp` and you are using `sdl-freerdp`.
read the help text or manpage of `sdl-freerdp` for keyboard shortcuts.

**Comment by akallabeth** [comment]
@bebras123  to set `right control` as hotkey (and automatically ungrab if no other shortcut is pressed)
```
{
    "SDL_KeyModMask": ["KMOD_RCTRL"],
    "SDL_Grab": "SDL_SCANCODE_RCTRL"
 }
 ```

**Comment by bebras123** [comment]
@akallabeth, huge thanks, provided configuration works as I want
