### ISSUE TITLE
xfreerdp crashes when initializing macaudio if STATIC_CHANNELS=off

### ISSUE THREAD

**Issue by bmiklautz** [FreeRDP/FreeRDP#996]
If static channels are disabled xfreerdp/rdpsnd crashes during initialization of macaudio. Macaudio is linked against CoreFoundation and loaded with dlopen in rdpsnd thread. But it is not possible to load libraries linked with CoreFoundation in a non-main thread (http://openradar.appspot.com/7209349)

Error output:

$> DYLD_LIBRARY_PATH=/usr/local/freerdp/lib/ ./client/X11/xfreerdp /v:10.16.5.21 /u:frdptest  /audio:sys:mac 
loading channel rdpsnd
Warning xf_GetWindowProperty (157): Property 296 does not exist
connected to 10.16.5.21:3389
Password: 
Unable to get current timezone rule
LoadLibraryA: dlopen(/usr/local/freerdp-master/lib/freerdp/rdpsnd-client-pulse.dylib, 5): image not found
LoadLibraryA: dlopen(/usr/local/freerdp-master/lib/freerdp/rdpsnd-client-alsa.dylib, 5): image not found
[1]    30191 trace trap (core dumped)  DYLD_LIBRARY_PATH=/usr/local/freerdp-master/lib/ ./client/X11/xfreerdp

**Comment by akallabeth** [comment]
Solved with #4453 and #4623
