### ISSUE TITLE
The UnicodeEvent event of the freerdp-proxy plug-in is not called.

### ISSUE THREAD

**Issue by Mr-LZG** [FreeRDP/FreeRDP#9970]
**Describe the bug**
When using freerdp3.3.0 to write an agent program, the UnicodeEvent event has not been called.

**To Reproduce**
1. I wrote an agent program using freerdp3.3.0 and called pf_server_add_module to register a plug-in.
2. When I ran the debugger, I found that the UnicodeEvent event has never been called, but the KeyboardEvent event will be called when there is input from the keyboard.

**Expected behavior**
The UnicodeEvent event is called on keyboard input.

**Screenshots**

**Application details**
* FreeRDP veersion 3.3.0
* Output of `xfreerdp /buildconfig`
   cmake .. \
                                -DCMAKE_BUILD_TYPE=Release \
                                -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON \
                                -DWITH_SERVER=ON \
                                -DWITH_SAMPLE=ON \
                                -DWITH_PLATFORM_SERVER=OFF \
                                -DUSE_UNWIND=OFF \
                                -DWITH_SWSCALE=OFF \
                                -DCHANNEL_URBDRC=OFF \
                                -DWITH_FFMPEG=OFF \
                                -DWITH_WEBVIEW=OFF \
                                -DDOCBOOK_MANPAGES=OFF \
                                -DBUILD_SHARED_LIBS=ON \
                                -DZLIB_LIBRARY=E:/2018/code/vendor/zlib/1.2.11/lib/win.x64/zlib.lib \
                                -DZLIB_INCLUDE_DIR=E:/2018/code/vendor/zlib/1.2.11/include/win.x64 \
                                -DOPENSSL_INCLUDE_DIR=E:/2018/code/vendor/openssl/1.1.1f/include/win.x64 \
                                -DOPENSSL_LIBRARY=E:/2018/code/vendor/openssl/1.1.1f/lib/win.x6
* OS version connecting to (server side)
  windows8.1 professional 

* If you built it yourself add some notes which tag/commit/branch you have used, also your cmake parameters and
  compiler can help

**Environment (please complete the following information):**
 - OS: [Windows]
 - Version/Distribution: [ Windows 10]
 - Architecture: [amd64]:

**Additional context**
* config.ini

[Server]
Host = 0.0.0.0
Port = 3389

[Target]
; If this value is set to TRUE, the target server info will be parsed using the 
; load balance info setting at runtime. The format is
; "Cookie: msts=<target server>", and can be set in an rdp file for windows/mac,
; and the /load-balance-info: CLI option for xfreerdp. Otherwise, the server
; will always connect to the same target, using the configured values of `Host`
; and `Port`.
TlsSecLevel=0
FixedTarget = TRUE
Host = 172.16.24.40
Port = 3389
;User = administrator
User = LZG
Password=123456
Domain=

[Input]
Mouse = TRUE
Keyboard = TRUE

[Certificates]
CertificateFile=C:\Bastion\etc\proxy\rdp\ca.crt
PrivateKeyFile=C:\Bastion\etc\proxy\rdp\ca.key

[Security]
ServerTlsSecurity = TRUE
ServerRdpSecurity = TRUE
ServerNlaSecurity = TRUE

ClientTlsSecurity = TRUE
ClientRdpSecurity = TRUE
ClientNlaSecurity = TRUE
ClientAllowFallbackToTls = TRUE

[Channels]
GFX = TRUE
DisplayControl = TRUE
Clipboard = TRUE
AudioInput = TRUE
AudioOutput = TRUE
DeviceRedirection = TRUE
VideoRedirection = TRUE
CameraRedirection = TRUE
RemoteApp = TRUE
; a list of comma seperated static channels that will be proxied. This feature is useful,
; for example when there's a custom static channel that isn't implemented in freerdp/proxy, and is needed to be proxied when connecting through the proxy.
PassthroughIsBlacklist = TRUE
Passthrough = "rdpdr"
;Intercept =  "rdpdr,cliprdr"

[Clipboard]
TextOnly = FALSE
MaxTextLength = 10 # 0 for no limit.

[GFXSettings]
DecodeGFX = TRUE

[Plugins]
; An optional, comma separated list of paths to modules that the proxy should load at startup.
;
; Modules = "proxy-demo-plugin.so"

; An optional, comma separated list of required plugins (names),
; that the proxy won't start without having them loaded.
;
; Required = "demo"
;Mudoles = "proxy-bitmap-filter-plugin.so,proxy-capture-plugin.so,proxy-dyn-channel-dump-plugin.so"

**Comment by akallabeth** [comment]
you seem to misunderstand what the events are for.
* `KeyboardEvent` handles [TS_FP_KEYBOARD_EVENT](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/089d362b-31eb-4a1a-b6fa-92fe61bb5dbf)
* `UnicodeEvent` handles [TS_FP_UNICODE_KEYBOARD_EVENT](https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-rdpbcgr/e7b13e98-d800-42bb-9a1d-6948537d2317)
* Same is true if you happen to use an ancient remote using `SlowPath` (see the spec for which events happen there)
