### ISSUE TITLE
Disabling zoom at client side

### ISSUE THREAD

**Issue by Jino26** [FreeRDP/FreeRDP#9975]
Hello everyone,

I've a query regarding disabling zoom (either using laptop touchpad or mouse scroll + CTRL button). Is there a command line option through which I can block these buttons/events or disable the zoom functionality totally at the client side?

I'm using the latest build of wfreerdp as the client. Any help will be most welcome. Thanks.

**Comment by akallabeth** [comment]
@Jino26 then check the server side settings for keyboard shortcuts.
client can not do that reliably (it does not know what the remote end is running)

**Comment by Jino26** [comment]
@akallabeth Our RDP backend and server is also FreeRDP (we're using Weston so this is the default backend). So can you provide a hint as to how can I achieve it server side. Thanks.

**Comment by akallabeth** [comment]
@Jino26 deactivate the keyboard shortcuts in weston/wm/application?
