### ISSUE TITLE
Error RAIL_EXEC_E_NOT_IN_ALLOWLIST When use /app

### ISSUE THREAD

**Issue by els3idi** [FreeRDP/FreeRDP#998]
We use Windows Server 2008 Server R2
 xfreerdp /v:192.168.5.208 /u:user /p:pass@123 /app:"C:\Users\Administrator\Desktop\App.exe"
The error message is:
connected to 192.168.5.208:3389
RAIL exec error: execResult=RAIL_EXEC_E_NOT_IN_ALLOWLIST NtError=0x15

I try this:
xfreerdp /v:192.168.1.211 /u:user /p:pass@123 +clipboard +decorations /app:C:\Program\ Files\Microtech\Infinity\ Enterprise\Fixed\ Assets\FixedAssets.exe /t:Fixed\ Assets
The error message is:
connected to 192.168.1.211:3389
RAIL exec error: execResult=RAIL_EXEC_E_NOT_IN_ALLOWLIST NtError=0x15

**Comment by pvgoran** [comment]
Setting registry value didn't help me in a similar situation. What helped was setting the corresponding group policy (Computer Configuration/Administrative Templates/Windows Components/Remote Desktop Services/Remote Desktop Session Host/Connections/Allow remote start of unlisted programs) to "Enabled".

**Comment by Okloks** [comment]
@bmiklautz, granting cmd to whitelist doesn't work.
Allowing launching all apps remotely is not secure solution.
Win server 2008 R2 x64

**Comment by chrislong** [comment]
Setting group policy worked for me with host Windows Server 2016. (Thanks @pvgoran!)

**Comment by patmigliaccio** [comment]
As mentioned by @bmiklautz - adding a new `fAllowUnlistedRemotePrograms` DWORD key with a value of `1` at  `HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services` did the trick.
