### ISSUE TITLE
freerdp3.3.0: remote app window maximium is not correct

### ISSUE THREAD

**Issue by amazingfate** [FreeRDP/FreeRDP#9997]
detailed behavior is in the video
[Screencast from 2024年03月19日 20时21分23秒.webm](https://github.com/FreeRDP/FreeRDP/assets/5022901/802ccbf9-c242-4898-bc8b-f38e96ac5534)
freerdp version  info:
```
This is FreeRDP version 3.3.0 (3.3.0)
Build configuration: BUILD_TESTING=OFF WINPR_HAVE_AIO_H=1 WINPR_HAVE_EXECINFO_BACKTRACE=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS=1 WINPR_HAVE_EXECINFO_BACKTRACE_SYMBOLS_FD=1 WINPR_HAVE_EXECINFO_HEADER=1 WINPR_HAVE_FCNTL_H=1 WINPR_HAVE_GETLOGIN_R=1 WINPR_HAVE_GETPWUID_R=1 WINPR_HAVE_INTTYPES_H=1 WINPR_HAVE_POLL_H=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIB=1 WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_LIBS= WINPR_HAVE_PTHREAD_MUTEX_TIMEDLOCK_SYMBOL=1 WINPR_HAVE_STDBOOL_H=1 WINPR_HAVE_STDINT_H=1 WINPR_HAVE_STRNDUP=1 WINPR_HAVE_SYSLOG_H=1 WINPR_HAVE_SYS_EVENTFD_H=1 WINPR_HAVE_SYS_FILIO_H= WINPR_HAVE_SYS_SELECT_H=1 WINPR_HAVE_SYS_SOCKIO_H= WINPR_HAVE_SYS_TIMERFD_H=1 WINPR_HAVE_TM_GMTOFF=1 WINPR_HAVE_UNISTD_H=1 WINPR_HAVE_UNWIND_H=1 WITH_AAD=OFF WITH_ABSOLUTE_PLUGIN_LOAD_PATHS=ON WITH_ADD_PLUGIN_TO_RPATH=OFF WITH_ALSA=OFF WITH_BINARY_VERSIONING=OFF WITH_CAIRO=OFF WITH_CCACHE=ON WITH_CHANNELS=ON WITH_CLANG_FORMAT=ON WITH_CLIENT=ON WITH_CLIENT_AVAILABLE=1 WITH_CLIENT_CHANNELS=ON WITH_CLIENT_CHANNELS_AVAILABLE=1 WITH_CLIENT_COMMON=ON WITH_CLIENT_INTERFACE=OFF WITH_CLIENT_SDL=OFF WITH_CLIENT_SDL_AVAILABLE=1 WITH_CUPS=OFF WITH_DEBUG_ALL=OFF WITH_DEBUG_CAPABILITIES=OFF WITH_DEBUG_CERTIFICATE=OFF WITH_DEBUG_CHANNELS=OFF WITH_DEBUG_CLIPRDR=OFF WITH_DEBUG_CODECS=OFF WITH_DEBUG_DVC=OFF WITH_DEBUG_EVENTS=OFF WITH_DEBUG_KBD=OFF WITH_DEBUG_LICENSE=OFF WITH_DEBUG_MUTEX=OFF WITH_DEBUG_NEGO=OFF WITH_DEBUG_NLA=OFF WITH_DEBUG_NTLM=OFF WITH_DEBUG_RAIL=OFF WITH_DEBUG_RDP=OFF WITH_DEBUG_RDPDR=OFF WITH_DEBUG_RDPEI=OFF WITH_DEBUG_RDPGFX=OFF WITH_DEBUG_REDIR=OFF WITH_DEBUG_RFX=OFF WITH_DEBUG_RINGBUFFER=OFF WITH_DEBUG_SCARD=OFF WITH_DEBUG_SCHANNEL=OFF WITH_DEBUG_SND=OFF WITH_DEBUG_SVC=OFF WITH_DEBUG_SYMBOLS=OFF WITH_DEBUG_THREADS=OFF WITH_DEBUG_TIMEZONE=OFF WITH_DEBUG_TRANSPORT=OFF WITH_DEBUG_TSG=OFF WITH_DEBUG_TSMF=OFF WITH_DEBUG_TSMF_AVAILABLE=0 WITH_DEBUG_WND=OFF WITH_DEBUG_X11=ON WITH_DEBUG_X11_LOCAL_MOVESIZE=OFF WITH_DEBUG_XV=OFF WITH_DSP_EXPERIMENTAL=OFF WITH_DSP_FFMPEG=OFF WITH_DSP_FFMPEG_AVAILABLE=0 WITH_EVENTFD_READ_WRITE=1 WITH_FAAC=OFF WITH_FAAD2=OFF WITH_FFMPEG=OFF WITH_FREERDP_DEPRECATED=ON WITH_FREERDP_DEPRECATED_COMMAN=ON WITH_FREERDP_DEPRECATED_COMMANDLINE=OFF WITH_FUSE=OFF WITH_GFX_H264=OFF WITH_GPROF=OFF WITH_GSM=OFF WITH_INTERNAL_MD4=OFF WITH_INTERNAL_MD5=OFF WITH_INTERNAL_RC4=OFF WITH_IPP=OFF WITH_JPEG=ON WITH_KRB5=OFF WITH_LAME=OFF WITH_LIBRARY_VERSIONING=ON WITH_LIBRESSL=OFF WITH_LIBSYSTEMD=ON WITH_LODEPNG=OFF WITH_MACAUDIO=OFF WITH_MACAUDIO_AVAILABLE=0 WITH_MANPAGES=ON WITH_MBEDTLS=OFF WITH_NATIVE_SSPI=OFF WITH_NEON=OFF WITH_OPAQUE_SETTINGS=OFF WITH_OPENCL=OFF WITH_OPENH264=OFF WITH_OPENSC_PKCS11_LINKED=OFF WITH_OPENSSL=ON WITH_OPUS=OFF WITH_OSS=ON WITH_PCSC=OFF WITH_PKCS11=ON WITH_POLL=ON WITH_PROFILER=OFF WITH_PULSE=ON WITH_SAMPLE=OFF WITH_SANITIZE_ADDRESS=OFF WITH_SANITIZE_ADDRESS_AVAILABLE=1 WITH_SANITIZE_MEMORY=OFF WITH_SANITIZE_MEMORY_AVAILABLE=1 WITH_SANITIZE_THREAD=OFF WITH_SANITIZE_THREAD_AVAILABLE=1 WITH_SERVER=OFF WITH_SERVER_INTERFACE=ON WITH_SMARTCARD_EMULATE=ON WITH_SMARTCARD_INSPECT=OFF WITH_SMARTCARD_PCSC=ON WITH_SOXR=OFF WITH_SSE2=OFF WITH_SWSCALE=OFF WITH_SYSTEMD=ON WITH_THIRD_PARTY=OFF WITH_UNICODE_BUILTIN=ON WITH_URIPARSER=OFF WITH_VAAPI=OFF WITH_VAAPI_AVAILABLE=0 WITH_VALGRIND_MEMCHECK=OFF WITH_VALGRIND_MEMCHECK_AVAILABLE=1 WITH_VERBOSE_WINPR_ASSERT=ON WITH_VIDEO_FFMPEG=OFF WITH_VIDEO_FFMPEG_AVAILABLE=0 WITH_WAYLAND=OFF WITH_WINPR_DEPRECATED=OFF WITH_WINPR_TOOLS=ON WITH_X11=ON WITH_XCURSOR=ON WITH_XEXT=ON WITH_XFIXES=ON WITH_XI=ON WITH_XINERAMA=ON WITH_XRANDR=ON WITH_XRENDER=OFF WITH_XV=ON
```
Server: windows server 2012r2
client: arm64 ubuntu 22.04, and x86_64 debian bookworm
Connect cmd:
```
./xfreerdp \
/cert:ignore \
/v:10.5.120.27:23389 \
/u:Administrator \
/p:Zx123456 \
/app:program:'||notepad' \
/tune:FreeRDP_RemoteApplicationSupportMask:0xf7 \
/log-filters:com.freerdp.core.update:DEBUG,com.freerdp.client.x11:DEBUG \
/gfx \
/relax-order-checks
```
freerdp log: https://paste.armbian.com/uwumahayex.csharp
freerdp 2.9.0 doesn't have this issue.

**Comment by akallabeth** [comment]
thank you for the report.

A few notes/questions:
* I don´t see a difference to the behavior of 2.x (that is with old rail) which is and was plagued by sync issues due to non atomic screen state changes, so are you sure this is 3.x only?
* don´t use `/gfx`, it deactivates autodetection and is usually more of a hindrance than helpful. (default is already using best options available)
* `/relax-order-checks` should never be used, it was only added because older `xrdp` servers did have some protocol violations that required a workaround
* I assume the `/tune:FreeRDP_RemoteApplicationSupportMask:0xf7 ` is for language bar behaviour?

**Comment by amazingfate** [comment]
- This is 3.x only. Here is the captured video of freerdp 2.6.1 packaged in ubuntu 22.04:
[Screencast from 03-20-2024 093612 AM.webm](https://github.com/FreeRDP/FreeRDP/assets/5022901/9488c20c-53ef-4e4b-adc6-7ba98008ef85)
log of freerdp 2.6.1: https://paste.armbian.com/epuwomeroc.yaml
- After deleting `/gfx` and `/relax-order-checks`, this issue is still here. I added `/relax-order-checks` to avoid disconnect issue when connecting windows server 2008 .
- `/tune:FreeRDP_RemoteApplicationSupportMask:0xf7` is suggested by https://github.com/FreeRDP/FreeRDP/issues/8126

We can see in freerdp 2.x the first `WindowUpdate` after `show=maximized` sent by server is `clientOffset=(-8,35) windowOffset=(-8,-8) windowClientDelta=(0,43) windowWidth=1936 windowHeight=1096 windowRects=((0,0,1936,1096)) visibleOffset=(-8,-8) visibilityRects=((0,0,1936,1096))`.
While in freerdp 3.x it is `clientOffset=(8,51) windowOffset=(0,0) windowClientDelta=(8,51) windowWidth=1920 windowHeight=1080 windowRects=((8,8,1944,1104)) visibleOffset=(0,0) visibilityRects=((8,8,1944,1104))`.

**Comment by akallabeth** [comment]
> * This is 3.x only. Here is the captured video of freerdp 2.6.1 packaged in ubuntu 22.04:
>       [Screencast from 03-20-2024 093612 AM.webm](https://github.com/FreeRDP/FreeRDP/assets/5022901/9488c20c-53ef-4e4b-adc6-7ba98008ef85)
>       log of freerdp 2.6.1: https://paste.armbian.com/epuwomeroc.yaml
> 
ok, can you do a `git bisect` and find out which commit did break it for you? As already mentioned, I don´t see a difference in (bad) behavior with any version when using the old `RAILS` mode.

>     * After deleting `/gfx` and `/relax-order-checks`, this issue is still here. I added `/relax-order-checks` to avoid disconnect issue when connecting windows server 2008 .
just wanted to check these are there for a reason and not some leftovers (they tend to break stuff if left untouched)
 
>     * `/tune:FreeRDP_RemoteApplicationSupportMask:0xf7` is suggested by [remoteapp not show language bar #8126](https://github.com/FreeRDP/FreeRDP/issues/8126)

ok, thought something like that, just wanted to be sure.

**Comment by amazingfate** [comment]
https://github.com/FreeRDP/FreeRDP/commit/c36d738a3633ad4183a44f29b94a1207ccfeb36f is causing the issue. After reverting it the maximium issue is gone.

**Comment by akallabeth** [comment]
@amazingfate nice catch.
I´ve created #10001 to allow disabling this option by command line and will check why the values differ if this option is activated server side.

**Comment by akallabeth** [comment]
@amazingfate ok, I´ve created https://github.com/FreeRDP/FreeRDP/issues/10005 to track the remaining issue.
